### ISSUE TITLE
Plans for contributing back to upstream?

### ISSUE THREAD

**Issue by alexandernst** [ValveSoftware/Proton#1]
Hi!

It's very nice to see such a big company standing behind Linux support for gaming. 

I (and probably the entire Linux community) am very interested in knowing if there are any plans to upstream the work you're putting in Proton. If there are, are you aiming at upstreaming everything or just some pieces?

Regards!

**Comment by Medath** [comment]
From their announcement:
> Modifications to Wine are submitted upstream if they're compatible with the goals and requirements of the larger Wine project; as a result, Wine users have been benefiting from parts of this work for over a year now. The rest is available as part of our source code repository for Proton and its modules.
