### ISSUE TITLE
Feedback on potential games to be whitelisted

### ISSUE THREAD

**Issue by swick** [ValveSoftware/Proton#10]
There probably should be a way to give feedback when games work well with Proton and could potentially be whitelisted.

**Comment by Bluexin** [comment]
I was looking for exactly this.
I tested `Disgaea PC` (the port of `Hour of Darkness`), and it works perfectly fine on default Proton.

 * Fedora 28 (4.17.14-202.fc28.x86_64)
 * GTX770 (396.45)
 * R7 1700X

**Comment by kisak-valve** [comment]
Hello @swick, @Bluexin, let's have whitelist requests as separate issue reports here. Those requests should at least have the game, proton version, distro version, video card and video driver version that was used to test with. Most of this can easily be collected with the system information from Steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/) to keep the whitelist request easily readable.

If there are multiple games in the same issue report, only the first unique game in the report will be tracked in that issue report.

**Comment by kisak-valve** [comment]
Re-opening for @Bluexin's whitelist request.

**Comment by Bluexin** [comment]
Oh I opened #13 already ^-^ system specs can be found there

**Comment by kisak-valve** [comment]
It's all good, I'll switch this back.

**Comment by romulasry** [comment]
Here is a large list on google docs (it is being edited by quite a few peeps, too):
https://docs.google.com/spreadsheets/d/1DcZZQ4HL_Ol969UbXJmFG8TzOHNnHoj8Q1f8DIFe8-8/edit#gid=0

**Comment by leosilvapb** [comment]
How did you install Fedora 28? for me the following error appears:
Traceback (most recent call last):
   File "./build-runtime.py", line 13, in <module>
     from debian import deb822
ImportError: No module named debian

**Comment by Bluexin** [comment]
@leosilvapb this is a bit offtopic -- but I didn't build it myself for Fedora 28 yet, just used the default Proton that comes with Steam Client

**Comment by leosilvapb** [comment]
thanks, it worked here after reinstalling steam
