### ISSUE TITLE
[Whitelist] Monkey Island 2 Special Edition: LeChuck’s Revenge (32460)

### ISSUE THREAD

**Issue by DoubyCz** [ValveSoftware/Proton#1003]
Works great on Ubuntu Linux 18.04 LTS (nvidia gpu, steam controller)

This game should be whitelisted.

[My System Info](https://gist.github.com/DoubyCz/ddfa8a99e121fc3213206aa2db8a1ff3)

**Comment by andrebadaia** [comment]
Confirmed.

Distro: Linux Mint 19 Tara
Processor: AMD Ryzen 7 1700
GPU: GTX 1070, Nvidia proprietary driver 396.54
RAM: 32GB
Kernel (custom) - 4.17.14 (optimized for Ryzen)
Resolution: 1920x1080
Proton 3.7-3

**Comment by andrew-mcmahon** [comment]
It's well worth going through the trouble of building the ["ultimate talkie editions"](http://www.gratissaugen.de/ultimatetalkies/) of Monkey Island 1 & 2 in a virtual machine. They can be run directly through ScummVM.

You get (toggle-able) voices, original graphics, item icons from the CD version (MI1) and a choice of MIDI, Roland MT32 or Special Edition soundtracks.

**Comment by dv8472** [comment]
%subject% works fine on Arch Linux too: nvidia (GeForce GTX 750) gpu, 4.14.69-1-lts kernel

**Comment by kisak-valve** [comment]
Found in the 2018-10-05 white list update.

**Comment by joshas** [comment]
Works great on Proton 5.0-9. Maybe whitelisted version could update Proton dependency to more recent one, to prevent additional download of older Proton version?
