### ISSUE TITLE
Games doesn't start

### ISSUE THREAD

**Issue by vauxx** [ValveSoftware/Proton#1004]
sys info here 
[2df871e64b3210d07e30c3c6f90afeae-2e6a02c71faae670b5d0b1f207d4c3175dde4d77.zip](https://github.com/ValveSoftware/Proton/files/2337338/2df871e64b3210d07e30c3c6f90afeae-2e6a02c71faae670b5d0b1f207d4c3175dde4d77.zip)

When i start any game using steam play, game seem to launch bu then immediately closes.
Literally nothing happens when i click play.
Games i tried to run:
NFS:Hot Pursuit
VCB: Why City
Car Mechanic Simulator 2015
Battlerite

**Comment by garpu** [comment]
I think python 3 is now a requirement? Would be nice if they documented it.

**Comment by UVClay** [comment]
Are your games on your Linux partition or an NTFS partition?  [Did you turn on logging in Proton](https://github.com/ValveSoftware/Proton#runtime-config-options)?

**Comment by vauxx** [comment]
@UVClay they're on linux partition

**Comment by garpu** [comment]
Do you have Python 3 installed? I didn't.  Installed it, and my games run again. (I was also getting a message in the console that python 3 wasn't found.)  Give it a try? If your distro is still on python 2, there are usually packages that can be installed alongside your system one.

**Comment by aeikum** [comment]
@garpu  What distro are you on?

**Comment by garpu** [comment]
Slackware 14.2.

**Comment by vauxx** [comment]
@garpu i checked my my python version. it said i have python 3.6.5.
tried to install it again and it worked.
games work now thanks
