### ISSUE TITLE
DOOM (2016) Access Violation (379720)

### ISSUE THREAD

**Issue by Kira-PH** [ValveSoftware/Proton#1005]
[Crash report](https://gist.github.com/HughPH/1315b6d10218aa810910f015749b601c)

[System Info](https://gist.github.com/HughPH/94701afc757803c72bb6c9cb03c26d1a)

**Comment by psy-q** [comment]
Same or similar issue, also with:

  * Nvidia driver 396.54
  * kwin_x11/Plasma
  * Ubuntu 18.04 LTS
  * Proton 3.7-6

Does your game show a black screen as well?

  * [Crash log](https://github.com/ValveSoftware/Proton/files/2421042/Crash.castle.00002.txt)
  * [System info](https://github.com/ValveSoftware/Proton/files/2421046/system_info.txt)

The system was set up fresh earlier today and uses the [Nvidia driver PPA](https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa). Everything else is from the Ubuntu repos. Wine is installed in addition, from the official WineHQ repo, though that hopefully doesn't matter.

I don't know why it says "r_renderAPI -2", I explicitly set `+r_renderAPI 1` in the launch options as suggested in other issues that mention black screens.

**Comment by Kira-PH** [comment]
I don't get a black screen, and I only had it once.

**Comment by eiglow** [comment]
It's been more than a year of inactivity since this issue was reported, could we get some re-tests on a newer version of Proton?

**Comment by psy-q** [comment]
I can't help with retesting since I left camp green for camp red, and on AMD/Mesa this issue does not seem to exist.

**Comment by Kira-PH** [comment]
It's not happened to me in some time now, thanks for checking.

**Comment by Tachiorz** [comment]
Still happening to me. It starts with openings and sound and crashes on 99% loading. 
I tired both vk and opengl.
Same game works just fine under lutris and windows steam.

- GPU: RX 570
- Driver/LLVM version: Mesa 20.1.0-devel (git-b93a195225)
- Kernel version: 5.5.9
- Link to full system information report: https://gist.github.com/Tachiorz/a6b9bdda2e08f5f99f7469d3870edea8
- Proton version: 5.0-4

[Crash.tachi-home.00007.html](https://gist.github.com/Tachiorz/0b81f031cffbc118f33e9475f126b418)

[steam-379720.zip](https://github.com/ValveSoftware/Proton/files/4352166/steam-379720.zip)

**Comment by kisak-valve** [comment]
Hello @Tachiorz, please open a new issue report.
