### ISSUE TITLE
Ship per-arch prefixes and bootstrap them based on binary's arch detection?

### ISSUE THREAD

**Issue by zer0def** [ValveSoftware/Proton#101]
Due to some games being shipped as 32-bit x86 binaries (in my particular case, S.T.A.L.K.E.R.: Shadow of Chernobyl), they might not launch, resulting in the following line in output:

```
wine: WINEARCH set to win32 but '/home/zer0def/.local/share/Steam/steamapps/compatdata/4500/pfx' is a 64-bit installation.**
```

The ad-hoc solution is to add `WINEARCH=win64` to the game's launch options. However, wouldn't it be appropriate to ship a dedicated prefix for 32-bit binaries and bootstrap appropriately?

**Comment by mirh** [comment]
Isn't this #8?
