### ISSUE TITLE
Grow Up (426790) Glitch Graphic

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#1022]
Distro: Manjaro XFCE 17.1.12
GPU: GTX 1060, Nvidia proprietary driver 396.54
Resolution: 1920x1080
RAM: 8GB
Proton 3.7-5 Beta
PROTON_LOG=1 %command% = https://pastebin.com/1YPSKZ0i

Run normaly = glitch
Run with PROTON_LOG=1 %command% and work is strange :D 

Game run and sound work and Xbox Controller work !

**Comment by kisak-valve** [comment]
Hello @liberodark, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/387#issuecomment-417470201.

**Comment by liberodark** [comment]
ok :D
