### ISSUE TITLE
3.7-5 Beta - Missing Resolution(s)

### ISSUE THREAD

**Issue by Glog78** [ValveSoftware/Proton#1028]
Thank you for proton. Today i tested the new Beta Build and it doesn't give me anymore the 1600x900 resolution which i prefer for windowed gaming on a full hd screen. It was available before so for me it kinda feels like a regression.

Tested Games -> FF3 / FFVIII

**Comment by aeikum** [comment]
This has been added back in the 3.7-6 Beta.
