### ISSUE TITLE
DS4 not working in Shadow Tactics: Blades of the Shogun (418240)

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/Proton#1030]
Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/5710.
@daasuharo posted on 2018-08-30T22:00:46:

#### Your system information

* Steam client version (build number or date): Aug 29 2018
* Distribution (e.g. Ubuntu): Ubuntu 18.04.1
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Under Windows 10 the game has native support for DS4 controllers that works but doesn't under my linux distro. It detects it as an unknown wireless controller with no inputs from it working.

#### Steps for reproducing this issue:

1. Load game with DS4
2. Try to use DS4

**Comment by ghost** [comment]
It's a native linux game.

**Comment by kisak-valve** [comment]
Whoops, I was on autopilot.
