### ISSUE TITLE
No Man's Sky (App ID:275850) black screen on resolution higher than 1920*1080

### ISSUE THREAD

**Issue by Liodinis** [ValveSoftware/Proton#1034]
Ubuntu 18.04.1 LTS
I7 6700K @ 4.00Ghz
Nvidia GTX 1070
Nvidia driver 396.54
Proton 3.7-3
RAM 16Go
SSHD 1To Toshiba H200
Display Acer Predator 24" 2560X1440

"No Man's Sky" doesn't work on resolution higher than 1920*1080.

Launch the game is displaying a black screen, but the game seems to be working, because sounds can be hear in background.
If you put your screen resolution at 1920*1080 or edit the config file TKGRAPHICSSETTINGS.MXML with the native resolution of your screen at the place below :

/home/username/.local/share/Steam/steamapps/common/No Man's Sky/Binaries/SETTINGS

restart the game, and it will become playable.

[Hardware Configuration.txt](https://github.com/ValveSoftware/Proton/files/2338138/Hardware.Configuration.txt)

[No Man's Sky config file.zip](https://github.com/ValveSoftware/Proton/files/2338158/No.Man.s.Sky.config.file.zip)

**Comment by kisak-valve** [comment]
Hello @Liodinis, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-417493922.
