### ISSUE TITLE
Age of Mythology: Extended Edition won't start

### ISSUE THREAD

**Issue by Israphel** [ValveSoftware/Proton#1035]
- Distro: KaOS
- Kernel: 4.16.14
- GPU: Intel HD 2500
- Mesa: 18.1.6
- Flatpak: 1.0.0
- Resolution: 1600x900
- RAM: 8 GB
- Proton 3.7-3

I selected **Bypass Launcher**

Logs:
[startup.txt](https://github.com/ValveSoftware/Proton/files/2338201/startup.txt)

**Comment by kisak-valve** [comment]
Hello @Israphel, the vulkan implementation for Intel/Ivybridge is incomplete and is expected to have trouble with dxvk. Give `PROTON_USE_WINED3D11=1 %command%` in the game's launch options a try.

Expect all directx 11 based games to have this kind of trouble on your system.

**Comment by Israphel** [comment]
Thanks kisak, it launched. But the FPS are very low though, maybe I won't be able to play this game with this hardware.

If I want to play with Steam Play using Intel graphics, which CPU is a good option? or none of them?

**Comment by kisak-valve** [comment]
I won't make a hardware recommendation, however, I can say that conformant vulkan support starts with the Intel/Broadwell generation.

Closing as this is a known video driver issue.
