### ISSUE TITLE
Alien Swarm: Reactive Drop (563560) the text for the ingame tips are blurry and DS4 controller doesn't work

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#1049]
Distro: Ubuntu 18.04.1
GPU: Intel Iris Pro 580
Resolution: 1280x720
RAM: 32GB
Controller: DS4
Proton 3.7-5 Beta

https://gist.github.com/daasuharo/cb605b8cd50227982a9bfa4dfcb1f635

**Comment by kisak-valve** [comment]
Hello @daasuharo, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/942#issuecomment-417633953.
