### ISSUE TITLE
Graphical glitches in Nier: Automata [spoilers: late game screenshots]

### ISSUE THREAD

**Issue by jrick** [ValveSoftware/Proton#1050]
[System details](https://gist.github.com/jrick/b823cbfc95f7af33b780fdee19aa1a2a)

In Nier: Automata there is always what appears to be a visible wireframe sphere around the camera or player position.  There are also surfaces which will become transparent occasionally (depending on the angle they are viewed from), and can also result in parts of the player also not being rendered correctly.

I've tested this under both Xorg and Wayland, and with Proton 3.7-3 (stable) and 3.7-5 (beta) and experienced the same glitches in all tests.

![screenshot from 2018-08-30 21-43-21](https://user-images.githubusercontent.com/1420313/44891916-ff765700-acaf-11e8-87e6-cc0026a1b7f3.png)

![screenshot from 2018-08-30 21-37-08](https://user-images.githubusercontent.com/1420313/44892183-5cbed800-acb1-11e8-9c69-bc59fc0e9886.png)

![screenshot from 2018-08-30 23-50-59](https://user-images.githubusercontent.com/1420313/44891910-f9807600-acaf-11e8-8c38-eec82f06f079.png)

**Comment by doitsujin** [comment]
Your driver is very old, please test with Mesa 18.2 and LLVM 7.

**Comment by jrick** [comment]
Thanks, I upgraded to Fedora 29 which includes both of those and the game renders perfectly now.

[Updated system details](https://gist.github.com/jrick/2d718634bd54f9fe66d338a98f5fcb4a)
