### ISSUE TITLE
Prototype (10150) crash on startup

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#1053]
Distro: Manjaro XFCE 17.1.12
GPU: GTX 1060, Nvidia proprietary driver 396.54
Resolution: 1920x1080
RAM: 8GB
Proton 3.7-5 Beta
PROTON_LOG=1 %command% =
[steam-10150.log](https://github.com/ValveSoftware/Proton/files/2338919/steam-10150.log)

**Comment by ghost** [comment]
What CPU? The game is known to insta-crash with any CPU that has SMT even under windows. If you have such a CPU, disable SMT in BIOS and try again.

**Comment by liberodark** [comment]
no have insta crash run first video and crash and video is not complete
Have intel skylake

**Comment by kisak-valve** [comment]
Hello @liberodark, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/164#issuecomment-417652649.
