### ISSUE TITLE
Fallout New Vegas crashes when Radio New Vegas is turned on (22380)

### ISSUE THREAD

**Issue by jgacas** [ValveSoftware/Proton#1056]
Every time I turn on Radio New Vegas, and speaker finishes talking about latest news, games crashes. At that moment music, that was announced by the speaker, should start playing, but instead games exits to the desktop. Issue is easily reproducible because it happens every time.

My system info: https://gist.github.com/jgacas/64704de0370633b265b2970b97ec7d35
Log file:
[steam-22380.log](https://github.com/ValveSoftware/Proton/files/2338957/steam-22380.log)

**Comment by ghost** [comment]
Make sure to add appid to title (22380)

**Comment by jgacas** [comment]
Figured out that's the problem by examining the log file, 32 bit MP3 decoding library was missing. Problem can be fixed by issuing 
`sudo apt install libmpg123-0:i386`

**Comment by kisak-valve** [comment]
Hello @jgacas, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/356#issuecomment-417636714.
