### ISSUE TITLE
Deus Ex Human Revolution Director's Cut (238010) audio issue

### ISSUE THREAD

**Issue by AccountOneOff** [ValveSoftware/Proton#1059]
Game runs great but I've noticed whenever I talk to an npc (e.g. Jenny Alexander) the audio starts crackling. I set `PULSE_LATENCY_MSEC=60 %command%` but it doesn't help. It does go away after some time but returns whenever talking to an npc.

- [System info](https://gist.github.com/AccountOneOff/83ccfce059eb0b1d001cbd3a35cbf9e6)
- Proton 3.7-5

**Comment by kisak-valve** [comment]
Hello @AccountOneOff, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/585#issuecomment-417644403.
