### ISSUE TITLE
No VR titles work in proton 3.7.5 Beta in VR mode.

### ISSUE THREAD

**Issue by Tuuvimer** [ValveSoftware/Proton#1068]
All load into 'vr desktop' (i.e large resolution not fitting monitor resolution) with no steamvr bridge interoperation at all, no tracking nor display in hmd - or they simply post "no hmd detected". (including white listed games such as Beat Saber)

Proton 3.7.4 Beta was working fine. Proton 3.7.3 official release still works fine.

**Comment by aeikum** [comment]
Can you set Beta Saber's launch options to "PROTON_LOG=1 %command%", run the game to show the failure, and then upload the resulting steam-620980.log in your Home directory here?

**Comment by aeikum** [comment]
Actually one of our QA people was able to reproduce this. Should be fixed in the next Beta, thank you for reporting.

**Comment by aeikum** [comment]
This should be fixed in the 3.7-6 Beta.

**Comment by Tuuvimer** [comment]
Can confirm it is fixed in 3.7-6 Beta for me.
