### ISSUE TITLE
Worked Games on Linux !

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#107]
**Work Great :+1: 
Not Work Great :(
Not Work :-1:** 

**Tested on (OS : Manjaro / GPU : GTX 1060 / Ram : 8 Go)**

- [Half Dead](https://store.steampowered.com/app/434730) :+1: 
- [Titan Quest](https://steamdb.info/app/4540/) :+1: 
- [Grim Dawn](https://store.steampowered.com/app/219990) :+1: 
- [Infectonator Survivor](https://store.steampowered.com/app/269310) :+1: 
- [Age of Mythology: Extended Edition](https://store.steampowered.com/app/266840) :-1: 
- [Age of Empires II HD](https://store.steampowered.com/app/221380) :-1: 
- [Alekhine's Gun](https://store.steampowered.com/app/406720) :+1: 
- [Arcane Worlds](https://store.steampowered.com/app/269610) :+1: 
- [Bloons TD 5](https://store.steampowered.com/app/306020) :(

**Comment by felisucoibi** [comment]
age of empires 2, works but with some glithces.

**Comment by mirh** [comment]
#76 

And bulk reports like this are useless.

**Comment by kisak-valve** [comment]
Hello @liberodark, we will not be tracking bulk testing results in this issue tracker. Specific issues should be tracked separately.

**Comment by Twinsonian** [comment]
Grim Dawn:
    - Missing Shaman class from list of class choices. Also, unable to select any classes on new characters. Have not tested on established characters with only one class selected.
-     Grim Dawn does not allow accessing skills menu a second time after leveling a new character

Otherwise runs amazingly well. Currently unplayable starting a new character and progressing with class and skill system
