### ISSUE TITLE
[Whitelist] Mirror's Edge (17410)

### ISSUE THREAD

**Issue by DoubyCz** [ValveSoftware/Proton#1071]
EA?! :-) Looks impossible, but its working incl. nvidia PhysX support (!)
I'am really impressed.
Absolutely no problem.

Ubuntu 18.04 LTS
[My System Info](https://gist.github.com/DoubyCz/ddfa8a99e121fc3213206aa2db8a1ff3)

**Comment by kisak-valve** [comment]
Hello @DoubyCz, this game is already being tracked at #355. Closing as a duplicate.
