### ISSUE TITLE
No Man's Sky [App ID:275850] Crash on nvidia

### ISSUE THREAD

**Issue by hitchhiker54** [ValveSoftware/Proton#1072]
The game plays flawlessly so far except for scanning when an npc base is in view. Tested on Minor Settlement and Observatory type, if the base is in view the game instantly crashes to desktop when in visor view. Player bases, ships, exocraft all seem to be fine. Using gtx980ti, i76700k on Ubuntu 18.04, Nvidia drivers 396.54

[edits additional]
Game version 1.58, issue also reported to Hello Games

sudo lshw results : 
https://www.dropbox.com/s/xxu34qjfnjp7f01/specs.txt?dl=0

**Comment by kisak-valve** [comment]
Hello @hitchhiker54, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-417668860.
