### ISSUE TITLE
Fieldrunners (original) hands while loading (209690)

### ISSUE THREAD

**Issue by josephcocoa** [ValveSoftware/Proton#1076]
Fieldrunners shows the loading screen, starts playing music, but never progresses beyond that.

**Comment by kisak-valve** [comment]
Hello @binarycocoa, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by josephcocoa** [comment]
Sorry about that.  Here is the info!

https://gist.github.com/binarycocoa/8136601c67e54d720f43bd9c51d540c0

**Comment by kisak-valve** [comment]
Hello @binarycocoa, this game was found in the 2019-07-31 whitelist update.

Are you still experiencing this issue with Proton 3.16-9?

**Comment by josephcocoa** [comment]
I have been traveling, but I should be able to retest it here shortly.

**Comment by josephcocoa** [comment]
I just did some light testing.
Set Proton to 3.16-9
Launched Fieldrunners (launched just fine)
Started a new game in classic mode.
Opened the options, tested fullscreen and windowed mode.
Played a round or two
Exited.

Things seem to be working perfectly. I think this can be closed and marked as compatible.
