### ISSUE TITLE
Fieldrunners 2 works perfectly (215710)

### ISSUE THREAD

**Issue by josephcocoa** [ValveSoftware/Proton#1077]
Fieldrunners 2 runs perfectly and can probably be whitelisted.  I was able to launch, start a new game, play some levels, and it all seemed to work perfectly well.

https://gist.github.com/binarycocoa/8136601c67e54d720f43bd9c51d540c0

**Comment by kisak-valve** [comment]
Hello @binarycocoa, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by josephcocoa** [comment]
Here is the info, let mek now if you need anything else.

https://gist.github.com/binarycocoa/8136601c67e54d720f43bd9c51d540c0

**Comment by cobblestone** [comment]
It works for me too.
https://gist.github.com/cobblestone/f1e00a8bc66f8ca73fd8debd72d447e7

**Comment by kisak-valve** [comment]
Found in the 2018-10-05 white list update.
