### ISSUE TITLE
Games with Splash launchers don't work

### ISSUE THREAD

**Issue by Vl4dim1r** [ValveSoftware/Proton#1084]
Is there a way to enable the ability for process spawning launchers to work? So far I've seen it with Interstellar Rift, Space engineers, and the EVE launcher. If the game naturally runs a splash screen/process loader, and spawns a new process for the game, Proton kills it. I can't copy verbatim due to being a separate system and i don't have synergy installed, but the logs end with:

"pid 18152 != 18151, skipping destruction (fork without exec)"

UPDATE: I am installing winetricks/corefonts to see if this resolves the issue.
UPDATE: Nope, unless there is a different process for installing corefonts in Proton

**Comment by nstgc** [comment]
I haven't encountered this issue. Dragon Age works fine, and it has a splash launcher. That's the first example that comes to mind, but there are at least two others that I've successfully tested.

As for that error message, that's normal. I get that for EVERY game regardless of whether or not it runs. Set your games to launch with PROTON_LOG=1. That is the output that matters.

**Comment by Vl4dim1r** [comment]
Here's my log from DXVK I guess, where does the PROTON_LOG=1 launch arg save the log to?
[steam-363360.log](https://github.com/ValveSoftware/Proton/files/2341139/steam-363360.log)
[steam-8500.log](https://github.com/ValveSoftware/Proton/files/2341293/steam-8500.log)
[steam-244850.log](https://github.com/ValveSoftware/Proton/files/2341294/steam-244850.log)

According to some googling, that option is for proton beta? The log I've posted was with the logging in user_settings enabled, I will try the newest beta of proton

Same output after upgrading

**Comment by aeikum** [comment]
Looks like all 3 games you've posted are .NET games, which are known to be problematic, see #18 . Nothing to do with launchers per se, except that launchers often use .NET.

**Comment by vanyasem** [comment]
`"pid 18152 != 18151, skipping destruction (fork without exec)"` doesn't mean anything by itself. it's most likely not related to the fact that game uses a "splash launcher", but a separate issue, that causes the game to crash/fail loading.

**Comment by ghost** [comment]
Looks like Interstellar Rift is failing here:
`74701.875:0008:0009:err:module:LdrInitializeThunk Main exe initialization for L"Z:\\home\\brad\\.steam\\steam\\steamapps\\common\\Interstellar Rift\\Build\\IR.exe" failed, status c0000017`

Eve Online has these:
`[0831/141016:FATAL:raw_channel_win.cc(592)] Check failed: g_vista_or_higher_functions.Get().SetFileCompletionNotificationModes( handle_.get().handle, FILE_SKIP_COMPLETION_PORT_ON_SUCCESS)`
AND 
`77584.375:0049:004a:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated`

Space Engineers:
`77939.933:0008:0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed`

I think you just have all games and situations that result in startup problems and they all just happen to have splash screens =)

**Comment by kisak-valve** [comment]
Since these games should be tracked separately, I'm going to close this issue at this point.

**Comment by ghost** [comment]
I also agree. For example, Space Engineers already has the problem listed: https://github.com/ValveSoftware/Proton/issues/18
https://appdb.winehq.org/objectManager.php?sClass=version&iId=30180

Eve Online: https://github.com/ValveSoftware/Proton/issues/1223
https://appdb.winehq.org/objectManager.php?sClass=version&iId=25823

Nothing yet for Interstellar Rift so that one can be created at this moment.
