### ISSUE TITLE
DOOM (2016) Everything's gone dark... (379720)

### ISSUE THREAD

**Issue by Kira-PH** [ValveSoftware/Proton#1089]
So DOOM was running very nicely. I had a quick look to see if anything [interesting] had changed in the newest Steam Client Beta update (which I'd already been running) and found that there is now listed Proton 3.7-5 Beta. Hurrah!

So I tried to run RAGE. Just got a black screen - and sound. And sounds when I press keys. Had to close it, that caused the machine to become unresponsive - except the mouse, and there was disk activity. Shut it down gracelessly. Rebooted. Ran RAGE again. Black screen. Same again. Ctrl+Alt+F2, killall Rage.exe. That worked. Loaded DOOM again, and everything looked good until I got to the actual game...

https://imgur.com/a/ir2fzDM

Now I'll try a reboot - but it could be a big problem (for reproducing issues at the very least) if the previous game can affect the stability of the current game...

**Comment by Kira-PH** [comment]
Comes back to life after a reboot.

**Comment by Kira-PH** [comment]
Dead again after trying some other games (Fallout: New Vegas, Fallout 3, Schein, Mafia 3) and checking if the Black Mesa team had fixed the bug that keeps crashing my game out (they haven't) - weird since Black Mesa worked.

Next I'll try rebooting, running DOOM, exiting DOOM and running DOOM again. It would be strange if it was directly affected by another game, especially after running Black Mesa which works fine.

**Comment by Kira-PH** [comment]
After rebooting DOOM is still dark (as per image) - so now unsure of how/why this is occurring. I cannot reproduce DOOM being OK after a reboot. (DOOM seems forever not OK now!)

**Comment by Kira-PH** [comment]
Works OK after deleting compatdata folder. In hindsight I should have backed up my save files... Steam hasn't redownloaded them (yet, if it will at all)

**Comment by TwoD** [comment]
Set `+r_renderapi 1` as the launch option and keep restarting it until it works.
Sometimes when it's launching to a black screen there's an error reporting dialog popping up which I have to kill to make the game quit. (How you do that depends on your window manager but usually you can do something like right/middle clicking the X to close it, or do it from a context menu while holding down Alt, or just kill the process via a terminal.)
If it keeps failing, restart Steam and try either with native libraries or the steam runtime. Eventually it'll start properly. Done it several times and finished the campaign just 10 minutes ago.

**Comment by Kira-PH** [comment]
Thanks @TwoD

**Comment by kisak-valve** [comment]
Per request of the opening user, transferred to https://github.com/ValveSoftware/Proton/issues/1067#issuecomment-417800751.
