### ISSUE TITLE
WINEDEBUG FPS Log doesn't log FPS

### ISSUE THREAD

**Issue by SteveHeist** [ValveSoftware/Proton#1090]
I was trying to setup the user-settings.py file to log FPS by editing the file to "WINEDEBUG": "+fps", but it does nothing. I can't seem to find any good FPS logging / benchmarking software, ala MSI Afterburner or Fraps, so this is vastly unfortunate. The game I was trying to use it on was Quake Champions (611500), I can test older / other games if you'd like.

Gist: https://gist.github.com/SteveHeist/1f51e113d17ac6bb8224c70a926d6508
Log, when configured as such: [steam-611500.log](https://github.com/ValveSoftware/Proton/files/2341291/steam-611500.log)

**Comment by aeikum** [comment]
The Steam Overlay has an option that should work for most games. The DXVK_HUD option will work for titles which use DXVK.

**Comment by SteveHeist** [comment]
Those will display it just fine, but I can't get a logfile for comparison purposes from either, so benchmarking and comparing results is impossible. GLXOSD used to exist, but has long since deprecated, and doesn't so much as have an Ubuntu 18.04 release key. I was hoping to get WINEDEBUG to print the FPS numbers, or at least an average FPS, to the steam-611500.log file, but it doesn't seem to work that way.

**Comment by whizse** [comment]
I would be surprised if this works given that dxvk replaces the d3d dlls provided by Wine.
