### ISSUE TITLE
How to trigger proton reinstall?

### ISSUE THREAD

**Issue by Elkasitu** [ValveSoftware/Proton#1091]
I tried deleting the Proton 3.7 Beta dir inside steamapps/common and then disabling and re-enabling proton from the Steam UI but that didn't work

**Comment by aeikum** [comment]
Try validating the local files for a game that uses it. Smaller games will validate more quickly.

**Comment by Elkasitu** [comment]
That did it, thanks!

**Comment by reavertm** [comment]
That alone doesn't work until proton related appmanifest_xxx.acf file from library folder is also removed. Only then Steam successfully sees proton as missing and re-fetches it.
