### ISSUE TITLE
Monster Hunter World - all surfaces have specular highlighting

### ISSUE THREAD

**Issue by shadywack** [ValveSoftware/Proton#1092]
Issue: specular highlighting on all surfaces
Steps to reproduce: launch game and observe surfaces
Observations: it depends on the texture and what the game engine calls for, in some cases its subtle, but it depends on the material to make it more obvious. In a rainy environment it actually looks cool, but I don't think it's what the renderer intends. I'd take a screenshot but it's obvious in motion. Wood should not have a specular highlight on its surface.
System: Ryzen 7 1800X on a Vega64 using the RADV/Mesa 18.3 driver (from the Padoka PPA listed in the quickstart guide) Ubuntu 18.04, Steam beta client running Proton 3.7-5

On a personal note: Thanks for all your hard work! This is some awesome coding to see, and probably the best thing I've ever seen Valve do. If there's a fix for this issue great, but if not, it's really not the end of the world. I can play this game natively at 4k in Windows but on Proton there's a pretty substantive hit to drop the fps down to 20-ish on my hardware. It runs buttery smooth at 60fps at 1440p however and I absolutely love it. Many thanks.

**Comment by kisak-valve** [comment]
Hello @shadywack, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/175#issuecomment-417773246.
