### ISSUE TITLE
[Request] Vulkan/DXVK not available on Optimus laptops using bumblebee

### ISSUE THREAD

**Issue by sysrq-reisub** [ValveSoftware/Proton#1099]
Due to bumblebee/primus supporting only OpenGL and not Vulkan, Optimus hybrid NVIDIA/Intel laptops are unable to run any game using DXVK with the discrete card, so the performance will be really poor.

I know this is not directly Proton-releated, but I think that should be an issue too, there also are people who use gaming laptops. And NVIDIA Prime technology is not always a good solution.

Thanks and sorry, that is not really a Proton issue.

**Comment by kisak-valve** [comment]
Hello @Lukypie, we're already tracking this issue at #65. Closing in favor of the existing issue report.

**Comment by sysrq-reisub** [comment]
Oh sorry, I've even used the search to find if there were duplicates, nvm.

**Comment by Arucard1983** [comment]
Maybe forking the primus_vk project would help to use Vulkan and DXVK on the dedicated NVidia cards when using Bumblebee ?
https://github.com/felixdoerre/primus_vk/issues/7
