### ISSUE TITLE
[Whitelist] Grand Theft Auto: Vice City (12110)

### ISSUE THREAD

**Issue by jammm** [ValveSoftware/Proton#110]
Ubuntu 18.04 with Nvidia driver 396.51 (GTX 1080)

**Comment by sehnem** [comment]
Worked on Arch Linux with RX560 and mesa-18.1

**Comment by neuromancer** [comment]
Worked on Arch Linux with Nvidia driver 396.51 (GTX 750)

**Comment by zetok** [comment]
Only some things in the game work on Gentoo Linux.

GPU: AMD R9 290
Mesa: 18.2.0_rc2
Kernel: 4.17.10-gentoo

What worked:

- launching to main menu
- starting new game on unchanged game settings

What didn't work:

- Rockstar logo when launching game (and IIRC there's also a game intro?) wasn't displayed, there's only a black screen until a key is pressed, which causes main menu to show up
- saving game(!)
- starting new game after changing resolution from default `640x480x16` to `1920x1080x32` with `wide screen ON` - after starting a new game with new settings only initial words of the first cut-scene are displayed, and then there's only a black screen, it seems that game froze (game's CPU usage alters between `0`, `0.7`, `1.3`), I could successfully close the game using my window manager's (i3) keybinding.


There doesn't seem to be anything useful in log either (or is even any useful debug info being sent to stdout?):

```
>>> Adding process 9299 for game ID 12110
Game update: AppID 12110 "", ProcID 9195, IP 0.0.0.0:0
Installing breakpad exception handler for appid(gameoverlayui)/version(20180823194714)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
PreparePathData
Done with PreparePathData
Done Initing waterlevels
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Shutdown pool started
Shutdown pool done
Game removed: AppID 12110 "", ProcID 9195 
No cached sticky mapping in ActivateActionSet.JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
pid 9197 != 9196, skipping destruction (fork without exec?)
```

**Comment by jammm** [comment]
@zetok I too faced the black screen issue at the start of a new game and enabling the frame limiter fixed it for me. Can you try that?

**Comment by zetok** [comment]
@jammm Yeah, that works, but now on my 144Hz monitor I can clearly see the hideous kaleidoscope @ 30fps.

Not sure which is worse, low resolution or frame limiting :s

**Comment by mirh** [comment]
GTA III-era games are bugged as hell even on windows xp. See: https://pcgamingwiki.com/wiki/Grand_Theft_Auto:_Vice_City#SilentPatch

**Comment by zetok** [comment]
To get savegame to work I had to manually create save dir

```
steam/steamapps/compatdata/12110/pfx/drive_c/users/steamuser/My Documents/GTA Vice City User Files
```

I also removed 

```
steam/steamapps/common/Grand Theft Auto Vice City/gta_vc.set
```

which was re-created at game launch, no idea if this step is needed.


I found the solution at https://www.steamgifts.com/go/comment/8bh98SS

**Comment by Houtworm** [comment]
This game also works flawless for me on Arch with Nvidia.

**Comment by ghost** [comment]
When I remember correctly the intro videos/screen didn't work for me on Windows either a long time ago and the only fix was to press the left mouse button after I started the game in Steam, same with Proton.

I can also confirm that turning off the frame limiter broke in game scenes.

I had no problems with savegames, everything else worked out of the box but I have only tested for minutes, not for hours(stability).

Although it is theoretically possible to regain full compatibility, that has already been broken by newer Windows versions, with Proton, so far I consider the experience equal.

With https://github.com/rwengine/openrw there  is also a project aiming to rewrite the engine that might fix these issues on the long term. Hopefully such projects can become part of proton as well.

I think this can indeed be whitelisted when the ingame stability is ok and when issue #291 is solved.

**Comment by ghost** [comment]
Camera goes to a top down view and spins when using DS4.

https://gist.github.com/daasuharo/b18e39c1f39b372a3e73892748c2da28

**Comment by kisak-valve** [comment]
Closing as blocked by #291.
