### ISSUE TITLE
Fallout Shelter doesn't start - "Oops! The game crashed."

### ISSUE THREAD

**Issue by PhonicUK** [ValveSoftware/Proton#1104]
System Information: https://gist.github.com/PhonicUK/1b2c994ca23e253dd7c6083008ef3331

    Ubuntu 18.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.18.5
    Driver:  X.Org AMD RAVEN (DRM 3.27.0 / 4.18.5, LLVM 6.0.0)

The game leaves behind the following log file: https://gist.github.com/PhonicUK/0c738ba851e1f882b93ab61596d1cab7

**Comment by kisak-valve** [comment]
Hello @PhonicUK, please retest with mesa 18.1+ and llvm 7+.

**Comment by PhonicUK** [comment]
Updating resolves the issue. Pardon me not reading the prereqs :)

**Comment by etaichoset** [comment]
I have the same issue, using mesa 18.1.6 on Proton 3.7-3 and 3.7-5 beta, with the steam stable and beta clients

`Solus 3.9999 (64bit)`
`Kernel Version: 4.18.5-90`
`X.Org Intel Ivybridge HD 3000 i915`

Specs:
https://gist.github.com/drshroomy/6c8e294ca9e8b392ffb645069a7264fa

Error log:
https://pastebin.com/SyzkFA5U

Edit: just notices kisak_valve recommended to use llvm 7+, most recent available in my distro us 6.0.1

**Comment by kisak-valve** [comment]
Hello @drshroomy, the vulkan implementation for Intel/Ivybridge is incomplete and dxvk is expected to have trouble with that chipset. You may see better results by adding `PROTON_USE_WINED3D11=1 %command%` to the game's launch options.
