### ISSUE TITLE
Treat empty linux repository as no linux version

### ISSUE THREAD

**Issue by basxto** [ValveSoftware/Proton#1112]
Allow to install games with proton when linux repository is completely empty

**Comment by Zero86Sk** [comment]
What games have empty linux repos?

**Comment by dubigrasu** [comment]
Silent Age for example: https://store.steampowered.com/app/352520/The_Silent_Age
Some other games have few Windows files inside, but this one is completely empty.
It has an Linux depot, but no build. https://steamdb.info/depot/352523/

**Comment by basxto** [comment]
Yes, exactly that game.
But I think I’ve seen empty linux repositories  before.

**Comment by kisak-valve** [comment]
This is a subset of https://github.com/ValveSoftware/steam-for-linux/issues/5638. Closing in favor of the existing feature request.
