### ISSUE TITLE
Quake Live crashes when trying to display server details. Issue with Awesomium suspected. (282440)

### ISSUE THREAD

**Issue by dawid2193487** [ValveSoftware/Proton#112]
This seems to be a Proton specific issue, unless Wine broke something since last time I used it.

Steps to reproduce:
1. Run Quake Live using Steam Play
2. Go to the server browser
3. Click on a server to see it's details
4. Crash.

This crash hasn't happened to me when I ran Steam&Quake Live simply via Wine, though last time I did that was a year ago, and I can't actually test it now because downloading doesn't work in current Steam on Wine.

When hosting a local server the issue doesn't appear.

My hardware details:
Linux 4.17.0-1-amd64 SMP Debian 4.17.8-1 (2018-07-20) x86_64 GNU/Linux
GTX 1050Ti
i5 2500k
More details in link below
https://gist.github.com/ca1ek/63c68c3c074abdcdc9330cddf19a1d72

I don't run the suggested drivers. I run 390.77-1 from Debian Buster's repository.

Backtrace:
https://gist.github.com/ca1ek/10709321f2ac610ffb057b00abd8ac0c

I blame Awesomium because Wine in general seems to have great problems with anything that does web rendering, and Awesomium is just repackaged Chromium

**Comment by dawid2193487** [comment]
WORKAROUND:
Find server's IP via some external service (Gametracker), then on startup of the game avoid the server browser and instead press ~ to open up the console and type in `connect the_servers_ip_addr` and it will work just fine.

**Comment by zzhiyi** [comment]
Fixed in proton 3.16-4

**Comment by xDShot** [comment]
Quake Live crashes Steam after exiting
