### ISSUE TITLE
Monster Hunter World - Crash on Credits Cutscene - Missing Windows Media Codecs

### ISSUE THREAD

**Issue by Estard** [ValveSoftware/Proton#1125]
After defeating the final boss in MH: World the game tries to load a cutscene where, according to this reddit post:
https://www.reddit.com/r/MonsterHunter/comments/99cqi4/xeno_save_corruption_bug_does_not_exist_proof/
it needs certain codecs contained in the Windows Media Feature Pack in order to play said cutscene.
I suppose that is the reason why the game also crashes at that point when playing it with Proton.
It would be well appreciated if a workaround could be implemented for this and other games that require it.

Tested on Proton 3-7-5 and winestaging 3.14 (64 bit) esync + dxvk

**Comment by kisak-valve** [comment]
Hello @Estard, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/175#issuecomment-417869083.
