### ISSUE TITLE
Quake Champions (611500)/Doom DEMO (479030) not working with linux mint 19

### ISSUE THREAD

**Issue by logan001** [ValveSoftware/Proton#1127]
Quake Champions crash in different places. Last time i didn't get past the health warning.
But sometimes i get in the arena and even move a bit. Im guessing thats because someone kills me and game crash. Why i guess that? well the game loads the map horible therefor the game freeze a lot with each room/character it has to load. I have no clue why this happens in all games under wine.

Doom (Demo) i can only see it for a brief moment in process list but nothing the screen. Of course except 1st setup window with DX and whatelse.
I've tried a few more games to test proton. mostly the free to play ones since i dont have many games that works only on windows and dx10/dx11
None of the games i've tried worked. the one that i remember are ashses of singularity/path of exile
i've tried a few more but i dont rememeber. i just picked them up from store.

Any suggestions?

Edit: i've installed Tomb Raider Anniversary (old game) and its working. im guessing dx11/dx10 are not working

**Comment by kisak-valve** [comment]
Hello @logan001, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/225#issuecomment-417869604.

As for Doom's demo, that's being discussed at #185, but not expected to work.
