### ISSUE TITLE
Aim Hero some font's don't render (518030)

### ISSUE THREAD

**Issue by john5788** [ValveSoftware/Proton#1145]
Aim Hero launches and runs, but a few of the text fields in the options menu do not render any text.

See the attached screenshot

![20180901122359_1](https://user-images.githubusercontent.com/9289163/44949227-495f5a00-ade2-11e8-9ae4-255ad8152004.jpg)

**Comment by kisak-valve** [comment]
Hello @john5788, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Some people have reported adding the system corefonts package helped with this kind of scenario.

**Comment by john5788** [comment]
Steam system info gist: https://gist.github.com/john5788/f1b4b2403b6965c6ada815fde57b0657

My distro is Gentoo and I do have the corefont package installed:

```
$ emerge -pv corefonts

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] media-fonts/corefonts-1-r7::gentoo  USE="X -tahoma" 7,460 KiB

Total: 1 package (1 reinstall), Size of downloads: 7,460 KiB

```

**Comment by michaelnew** [comment]
Same issue for me. Here's my [system info](https://gist.github.com/michaelnew/f2dd63ccf342c9b540ee9a3633397dd4).

In addition, I also have mouse issues. The easiest way to demonstrate is to gently shake the mouse back and forth with small movements and the mouse will drift towards the bottom right. I may be similar to #147, but regardless the solution to that issue, using wine-staging 3.15, fixes it. 

I believe it is [this patch](https://github.com/wine-staging/wine-staging/tree/master/patches/winex11-mouse-movements) that has the fix, and [here](https://bugs.winehq.org/show_bug.cgi?id=42631) is the corresponding wine bug thread.

It sounds like this issue might be popping up in all Unity games. Would be great to see this patch merged into Proton.

**Comment by john5788** [comment]
Fonts seem to be rendering as of 3.16-4. Closing this issue.
