### ISSUE TITLE
Steam play/Wine Crackling, popping, echoing Sound fix

### ISSUE THREAD

**Issue by setsunati** [ValveSoftware/Proton#1147]
https://www.youtube.com/watch?v=UQ-Ml78kiEE

**Comment by ryanmusante** [comment]
Indeed, distro maintainers should make these settings defaults for desktop based.  

However I disagree with some of them and recommend in place:
```
default-sample-format = s16le #keep default
default-sample-rate = 44100 #lowering reduces quality 
alternate-sample-rate = 48000 #lowering reduces quality 
```

**Comment by kisak-valve** [comment]
Hello @setsunati, I'm closing this as it appears to be only informational and not an actionable issue report.

**Comment by noidexe** [comment]
> 
> 
> Indeed, distro maintainers should make these settings defaults for desktop based.
> 
> However I disagree with some of them and recommend in place:
> 
> ```
> default-sample-format = s16le #keep default
> default-sample-rate = 44100 #lowering reduces quality 
> alternate-sample-rate = 48000 #lowering reduces quality 
> ```
In my case (latest Manjaro) I tried every option one by one without success until I increased the sample rate as indicated in the webpage and it fixed the crackling noise. 
I was able to keep the default sample format, though.

**Comment by ryanmusante** [comment]
_PulseAudio/Troubleshooting < PulseAudio_

https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Laggy_sound

_Optimize PulseAudio for Steam: Latency, Realtime and Noise / Echo Cancellation_

https://ludwig.im/en/projects/steam-pulseaudio-sound-latency-lagging-problem-noise#optimize-pulseaudio-settings-for-steam-games
