### ISSUE TITLE
Grid (12750) Crashes when launching a race

### ISSUE THREAD

**Issue by hswhite33** [ValveSoftware/Proton#1160]
Managed to get into the menus after a bit of fiddling (I had to do the same fiddling in Windows though, NBD). Game crashes consistently when trying to launch a race, I haven't managed to successfully launch one.

[steam-12750.log](https://github.com/ValveSoftware/Proton/files/2342909/steam-12750.log)

[System info](https://gist.github.com/hswhite33/d5872273b13aa91e29a7104c1c4866a9)

Proton 3.7-5 Beta

**Comment by kisak-valve** [comment]
Hello @hswhite33, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1061#issuecomment-417899897.
