### ISSUE TITLE
[UI Feature Request] Debug mode in menu.

### ISSUE THREAD

**Issue by Tuuvimer** [ValveSoftware/Proton#1161]
Make debug mode (WINEDEBUG=warn or all) (or PROTON_LOG) be an option in the right click launch options with a terminal popup, with UI visible complete path log saving (leaving no confusion), without needing to change launch options via text. The information from this is so commonly required it shouldn't need manually altering launch command. Also suggestion to change default save path of log files to "$HOME/SteamPlay/steam-$APPID.log" from "$HOME/steam-$APPID.log" for less clutter.

**Comment by kisak-valve** [comment]
Hello @Tuuvimer, this is a feature request for the Steam client rather than Proton itself, so I've transferred this issue to https://github.com/ValveSoftware/steam-for-linux/issues/5719.
