### ISSUE TITLE
ABZU (384190)

### ISSUE THREAD

**Issue by cddt** [ValveSoftware/Proton#1167]
Game does not load, reports unknown shader cache type and exits.

Log from ~/.steam/steam/logs/shader_log.txt:

```
[2018-09-02 17:39:48] Creating shader cache directory: ~/Steam/steamapps/shadercache/384190
[2018-09-02 17:39:52] AppID 384190 exited.
[2018-09-02 17:39:52] Unknown shader cache type, ignoring.
```

System info:

```
Distro: Fedora 27 
Kernel: 4.17.17
NVIDIA drivers: 396.54
Proton: 3.7-5 beta
Hardware: Ryzen 1600X / GTX 1080 Ti
```

Log attached: 
[steam-384190.log](https://github.com/ValveSoftware/Proton/files/2342995/steam-384190.log)

**Comment by cddt** [comment]
Attempted to open via command line, additional error here: 

```
[cddt@localhost ABZU]$ /home/cddt/data-space/Steam/steamapps/common/Proton\ 3.7\ Beta/dist/bin/wine AbzuGame.exe
wine: created the configuration directory '/home/cddt/.wine'
0009:err:file:init_redirects cannot open L"C:\\windows" (c000000f)
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0010:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0020:err:module:load_builtin_dll failed to load .so lib for builtin L"l3codeca.acm": libmpg123.so.0: cannot open shared object file: No such file or directory
0020:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
wine: configuration in '/home/cddt/.wine' has been updated.
0024:fixme:ntdll:EtwEventRegister ({5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x14000107c, 0x140016030, 0x140016050) stub.
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x140013a98, 43) stub
0026:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0026:fixme:debug_buffer:RtlCreateQueryDebugBuffer (0, 0): stub
0026:fixme:debug_buffer:RtlCreateQueryDebugBuffer (168, 0): returning 0x77be0
0026:fixme:debug_buffer:RtlQueryProcessDebugInformation (38, 14, 0x77be0): stub
0026:fixme:debug_buffer:RtlDestroyQueryDebugBuffer (0x77be0): stub
0026:fixme:thread:NtSetInformationThread info class 7 not supported yet
0027:fixme:thread:NtSetInformationThread info class 7 not supported yet
0026:fixme:ver:GetCurrentPackageId (0x5ff3f0 (nil)): stub
0026:err:module:load_library somehow failed to load steamclient
0024:fixme:ver:GetCurrentPackageId (0x60fd50 (nil)): stub
```

**Comment by mimattr** [comment]
## System Information
- GPU: **GTX 970**
- Driver/LLVM version: **NVIDIA 396.54**
- Kernel version: **4.4.0-135-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **3.7-6 Beta**

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-384190.log](https://gist.github.com/mimattr/3f07616314abea83e3e93db4654441ff)

## Symptoms 
Experiencing the same issue and `shader_log.txt` result as @cddt

> Game does not load, reports unknown shader cache type and exits.

## Reproduction
- Select the title within your `Library` using the Steam client and press the `Play` button

**Comment by nicemit** [comment]
Same happening with me.
Game: Spec Ops The Line

in the file `shader_log.txt`
![screenshot from 2019-02-12 23-51-30](https://user-images.githubusercontent.com/20738824/52658505-3b7d3b80-2f21-11e9-8a4a-05fd187d7b8d.png)

**Comment by jonbitzen** [comment]
I found this bug report on the Wine bug tracker:

https://bugs.winehq.org/show_bug.cgi?id=43845

@kisak-valve is there a corresponding flag to the one mentioned in this report?  Apparently this game used to work on Wine 2.x, and the developer seemed to think it'd be an easy fix if he could get the info needed.

**Comment by kisak-valve** [comment]
Hello @jonbitzen, take a look at [`user_settings.example.py`](https://github.com/ValveSoftware/Proton#runtime-config-options) in Proton's install folder for an easy way to set WINEDEBUG.

**Comment by jonbitzen** [comment]
@kisak-valve 

OK so trying that didn't reveal anything that posters above didn't already provide.

With that said, it still doesn't work on Proton 4.2-4.

Brief System Info:

Ryzen 1700x
32Gb RAM
GTX 970
Nvidia drivers 430.14

Linux Mint 19.1

Hope you guys can bump this one up a bit, would love to play ABZU!

Thanks,

jonbitzen

**Comment by jonbitzen** [comment]
4.2-6, still no joy

**Comment by jonbitzen** [comment]
ABZU, o ABZU?
Wherefore art though ABZU?
Not on Proton 4.2-8, alas.

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX VEGA 56
- GPU Driver: Mesa ACO 19.1.0+aco+git1564747450-10690f8d9e6-1bionic1 (Valves PPA)
- Kernel version:  5.2.5-050205-lowlatency
- Distro version: Linux Mint 19.1 Tessa (64 bit) (Cinnamon Desktop)
- Proton version: 4.11-1
- System information: [system_info.txt](https://github.com/ValveSoftware/Proton/files/3464118/system_info.txt)

Game won't launch, nothing happens.

[steam-384190.log](https://github.com/ValveSoftware/Proton/files/3464119/steam-384190.log)

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX VEGA 56
- GPU Driver: 19.1.0+aco+git1566739320-db73bde35cc-1bionic1 (Valves PPA)
- Kernel version: 5.2.10-050210-lowlatency
- Distro version: Linux Mint 19.2 Tina (64 bit) (Cinnamon)
- Proton version: 4.11-3

**Retest Compatibility Report**

Same problem persists, launching the game nothing happens.

[steam-384190-proton-4.11-3.log](https://github.com/ValveSoftware/Proton/files/3547458/steam-384190-proton-4.11-3.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3547459/system_info.txt)

**Comment by jonbitzen** [comment]
Proton 4.11-6 doesn’t work with Abzu.  I know it’s probably small fish to fry, but hopefully eventually:)

**Comment by ryliejamesthomas** [comment]
@jonbitzen nice pun 👌

**Comment by cddt** [comment]
I suspect it is due to the Denuvo DRM, since they've released a DRM-free version on GoG which works perfectly.

**Comment by niansa** [comment]
Here, the game simply spams the terminal with:
`002e:fixme:thread:NtSetInformationThread info class 7 not supported yet`

but won't ever start…

**Comment by nobodywasishere** [comment]
Steve (a Squid Dev) on their Discord regarding Denuvo DRM: "Ah, I’m sorry, :/ but yeah unfortunately steam’s DRM thing is a mandate from 505 or something. Sadly we don’t have any control over having it removed to my knowledge."

![image](https://user-images.githubusercontent.com/32797552/70855260-416fe000-1e96-11ea-9c68-02d429a41795.png)

**Comment by cddt** [comment]
Unfortunate, since apparently there is no Denuvo in the GoG version (which has been reported to work perfectly through WINE).

**Comment by cverstege** [comment]
This issue can be closed. ABZU runs perfectly with Proton 5.0-1.
It was even noted in the patch notes of 5.0-1 that ABZU is now working https://github.com/ValveSoftware/Proton/releases/tag/proton-5.0-1

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX 5700 ITX
- GPU Driver: Mesa 20.1.0-devel (ppa:ernstp/ppa)
- Kernel version: 5.3.18-050318-lowlatency
- Distro version: 19.3 Tricia (64 bit) (Cinnamon)
- Proton version: 5.0-1

**Retest Compatibility Report**

Game works as of Proton 5.0-1 out of the box :tada: , functionality and performance is similar as on Windows. The only issue I could see is that switching between fullscreen and desktop mode is not perfect (the game behaves like a borderless fullscreen windowed app, switching to desktop the game still is seen in the background).

However, this exact same problem exists with this game on Windows too, considering that I think is **whitelist material**. If the Alt+Tab issue would be fixed, then the game would be working better on Linux than it does on actual Windows.

Logs:
[system_info.txt](https://github.com/ValveSoftware/Proton/files/4175100/system_info.txt)
[steam-384190proton-5.0-1.log.zip](https://github.com/ValveSoftware/Proton/files/4175099/steam-384190proton-5.0-1.log.zip)

**Comment by cddt** [comment]
Tested with Proton 5.0-1, works fine.

**Comment by gnuletik** [comment]
Is it still working with Proton 5.0-4 ?
I got this error when running it from Steam (and forcing the use of Proton 5.0-4).
I tried removing the wine prefix, reinstalling the game, reinstalling Proton, with or without Steam Beta, on ext4 or NTFS filesystem but I still get this error.

```
wine: Unhandled exception 0xc0000409 in thread 37 at address 0000000144B2DACC (thread 0037), starting debugger...
>>> Adding process 498132 for game ID 384190
Process of pid=0036 has terminated
No process loaded, cannot execute 'echo Modules:'
Cannot get info on module while no process is loaded
No process loaded, cannot execute 'echo Threads:'
process  tid      prio (all id:s are in hex)
00000008 steam.exe
	0000002a    0
	00000009    0
0000000c services.exe
	00000026    0
	00000020    0
	00000018    0
	00000013    0
	00000012    0
	00000011    0
	0000000e    0
	0000000d    0
0000000f plugplay.exe
	00000015    0
	00000014    0
	00000010    0
00000016 winedevice.exe
	0000001d    0
	0000001c    0
	0000001b    0
	0000001a    0
	00000019    0
	00000017    0
0000001e winedevice.exe
	00000023    0
	00000022    0
	00000021    0
	0000001f    0
00000024 winedevice.exe
	00000029    0
	00000028    0
	00000027    0
	00000025    0
0000002b explorer.exe
	00000031    0
	00000030    0
	0000002d    0
	0000002c    0
00000034 
	00000035    0
pid 498060 != 498059, skipping destruction (fork without exec?)
Game removed: AppID 384190 "", ProcID 498057 
```

Thanks!

**Comment by AwesamLinux** [comment]
@gnuletik it seems the game is no longer working with 5.0-4 (nothing happens on launch). It worked fine for me back with Proton 5.0-3

**Comment by gnuletik** [comment]
@AwesamLinux Thanks for the feedback ! I was getting crazy trying to find out why it didn't work :)

**Comment by cverstege** [comment]
@cddt This issue may be reopened as the game does not work any longer with proton 5.0-4. I can confirm this as well.

**Comment by kisak-valve** [comment]
Hello, a regression was identified between Proton 5.0-3 and 5.0-4 which affected multiple games and should be fixed in the next patch release.

For now you can temporarily switch to Proton 5.0-3 by selecting it in the beta tab of Proton 5.0's per-game settings in Steam to workaround that regression.

@Citiroller, the reporting user has chosen to close this issue report. If there's any hints that there's something different from the known regression happening with the game after Proton 5.0-5 is released, then please search the issue tracker for an open compatibility report for this game and open a new issue report one to help us keep track of the game's behavior.

**Comment by AwesamLinux** [comment]
@gnuletik @Citiroller The game is working for me again with Proton 5.0-5

**Comment by gnuletik** [comment]
Thanks for the feedback @AwesamLinux !
I tried with Proton 5.0-5 but I wasn't able to get into the game.
After the intro scene and the loading screen, a new window opens a show the following error :
```
The UE4-AbzuGame Game has crashed

LowLevelFatalError [File:K:\AbzuMain\Engine
\Source\Runtime\Windows\D3D11RHI\Private
\D3D11Util.cpp][Line 200]
Direct3DDevice->
CreateVertexShader( (void*)CodePtr, Code Size
NULL, Shader->Resource.GetInitReference() )
failed
at K:\AbzuGame\Engine\Source\Runtime
\Windows\D3D11RHI\Private
\D3D11Shaders.cpp:46
with error E_INVALIDARG
```

I'm using
- Archlinux up-to-date
- Kernel 5.5.10-arch1-1
- Nvidia drivers 440.64-5
- Proton 5.0-5 or Proton 5.0-3
- GPU : RTX 2070

Thanks also for the Beta tab @kisak-valve, I was able to give a try with the Proton 5.0-3 version and got the same issue as above.

EDIT: Removing `PROTON_USE_WINED3D=1 %command%` from the game's launch option fixed it :)

**Comment by gnuletik** [comment]
In fact, it is working.
I had `PROTON_USE_WINED3D=1 %command%` as a launch option. I removed it and the game works out of the box :)
Thanks !!

**Comment by cverstege** [comment]
Thank you for the clarification @kisak-valve The game works again flawlessly after the 5.0-5 update.

**Comment by GHGibonus** [comment]
I had no luck running ABZÛ With latest 5.0-5b and 5.0-6rc Proton. Here is the log. I'm not sure what causes it to be this long
[steam-384190.zip](https://github.com/ValveSoftware/Proton/files/4433900/steam-384190.zip)

**Edit**: while looking for my System settings, I found out I didn't have the proper libraries installed to run Vulkan. I've now installed them and the game seems to run normally.
