### ISSUE TITLE
Final Fantasy IX crashes on start

### ISSUE THREAD

**Issue by lucavallerini** [ValveSoftware/Proton#1177]
Final Fantasy IX does not start. I think the relevant error is: `ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`.

The full output from the command line:
> Running Steam on fedora 28 64-bit
> STEAM_RUNTIME is enabled automatically
> Pins up-to-date!
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> [0902/154353.131861:WARNING:crash_reporting.cc(254)] Failed to set crash key: UserID with value: 0
> [0902/154353.131920:WARNING:crash_reporting.cc(254)] Failed to set crash key: BuildID with value: 1535766863
> [0902/154353.131924:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
> [0902/154353.131927:WARNING:crash_reporting.cc(254)] Failed to set crash key: Version with value: 1535766863
> [0902/154353.131930:WARNING:crash_reporting.cc(254)] Failed to set crash key: ProductName with value: cefwebhelper
> [0902/154353.131933:WARNING:crash_reporting.cc(254)] Failed to set crash key: Vendor with value: Valve
> [0902/154353.138518:ERROR:gpu_process_transport_factory.cc(1029)] Lost UI shared context.
> html_chrome.cpp (394) : Assertion Failed: CefCrashReportingEnabled()
> [0902/154353.147562:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Dev
> [0902/154353.148187:WARNING:crash_reporting.cc(254)] Failed to set crash key: UserID with value: 0
> [0902/154353.148200:WARNING:crash_reporting.cc(254)] Failed to set crash key: BuildID with value: 1535768746
> [0902/154353.148205:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
> [0902/154353.148210:WARNING:crash_reporting.cc(254)] Failed to set crash key: Version with value: 1535768746
> [0902/154353.148214:WARNING:crash_reporting.cc(254)] Failed to set crash key: ProductName with value: cefwebhelper
> [0902/154353.148218:WARNING:crash_reporting.cc(254)] Failed to set crash key: Vendor with value: Valve
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> CApplicationManagerPopulateThread took 8 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> CAppInfoCacheReadFromDiskThread took 31 milliseconds to initialize
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> 
> ** (steam:10654): WARNING **: 15:43:53.451: Unknown device type 14
> 
> ** (steam:10654): WARNING **: 15:43:53.451: Could not create object for /org/freedesktop/NetworkManager/Devices/1: unknown object type
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> 
> ** (steam:10654): WARNING **: 15:43:53.668: Unknown setting 'proxy'
> 
> ** (steam:10654): WARNING **: 15:43:53.668: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.668: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.668: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.668: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.668: Unknown setting 'proxy'
> 
> ** (steam:10654): WARNING **: 15:43:53.668: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.668: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Ignoring invalid property 'autoconnect-priority'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Ignoring invalid property 'interface-name'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Unknown setting 'proxy'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Unknown setting 'proxy'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.669: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Unknown setting 'proxy'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Unknown setting 'proxy'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'autoconnect-priority'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'interface-name'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Unknown setting 'proxy'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.670: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.671: Unknown setting 'proxy'
> 
> ** (steam:10654): WARNING **: 15:43:53.671: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.671: Ignoring invalid property 'address-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.671: Ignoring invalid property 'route-data'
> 
> ** (steam:10654): WARNING **: 15:43:53.671: Ignoring invalid property 'address-data'
> Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
> Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
> Found unsupported CDM version 1.4.9.1088, using last known good version 1.4.8.1008
> 
> (steam:10654): Gtk-WARNING **: 15:43:54.140: gtk_disable_setlocale() must be called before gtk_init()
> 
> (steam:10654): Gtk-WARNING **: 15:43:54.149: Unable to locate theme engine in module_path: "adwaita",
> /usr/share/themes/Adwaita/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'
> 
> (steam:10654): Gtk-WARNING **: 15:43:54.156: Unable to locate theme engine in module_path: "adwaita",
> /usr/share/themes/Adwaita/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
> 
> (steam:10654): Gtk-WARNING **: 15:43:54.158: Unable to locate theme engine in module_path: "adwaita",
> /usr/share/themes/Adwaita/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'
> 
> (steam:10654): Gtk-WARNING **: 15:43:54.161: Unable to locate theme engine in module_path: "adwaita",
> /usr/share/themes/Adwaita/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
> Xlib:  extension "NV-GLX" missing on display ":0".
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> roaming config store loaded successfully - 1205 bytes.
> migrating temporary roaming config store
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> [0902/154357.008454:WARNING:crash_reporting.cc(254)] Failed to set crash key: UserID with value: 0
> [0902/154357.008807:WARNING:crash_reporting.cc(254)] Failed to set crash key: BuildID with value: 1535766863
> [0902/154357.008819:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
> [0902/154357.008825:WARNING:crash_reporting.cc(254)] Failed to set crash key: Version with value: 1535766863
> [0902/154357.008829:WARNING:crash_reporting.cc(254)] Failed to set crash key: ProductName with value: cefwebhelper
> [0902/154357.008839:WARNING:crash_reporting.cc(254)] Failed to set crash key: Vendor with value: Valve
> Failed to init SteamVR because it isn't installed
> ExecCommandLine: "'/home/luca/.local/share/Steam/ubuntu12_32/steam'"
> System startup time: 4.78 seconds
> Generating new string page texture 81: 1024x256, total string texture memory is 1.36 MB
> Generating new string page texture 82: 128x256, total string texture memory is 1.49 MB
> Generating new string page texture 83: 128x256, total string texture memory is 131.07 KB
> Generating new string page texture 84: 64x256, total string texture memory is 1.56 MB
> Generating new string page texture 85: 32x256, total string texture memory is 1.59 MB
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> Generating new string page texture 93: 128x256, total string texture memory is 1.72 MB
> JS method call WebChat.GetWebChatLanguage with 1 arguments
> JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
> JS method call WebChat.GetSignIntoFriendsOnStart with 1 arguments
> JS method call WebChat.GetCurrentUserAccountID with 1 arguments
> Generating new string page texture 98: 384x256, total string texture memory is 2.11 MB
> Generating new string page texture 99: 256x256, total string texture memory is 2.38 MB
> JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
> JS method call WebChat.GetWebChatURL with 1 arguments
> Generating new string page texture 119: 8x256, total string texture memory is 2.38 MB
> Installing breakpad exception handler for appid(steam)/version(1535768746)
> JS method call FriendSettings.RegisterForSettingsChanges with 1 arguments
> JS method call WebChat.RegisterForPushToTalkStateChange with 1 arguments
> JS method call WebChat.GetPushToTalkEnabled with 1 arguments
> JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
> JS method call WebChat.RegisterForComputerActiveStateChange with 1 arguments
> JS method call SharedConnection.AllocateSharedConnection with 1 arguments
> JS method call WebChat.RegisterOverlayChatBrowserInfoChanged with 1 arguments
> JS method call FriendSettings.GetEnabledFeatures with 1 arguments
> JS method call SharedConnection.SubscribeToEMsg with 2 arguments
> JS method call SharedConnection.SubscribeToEMsg with 2 arguments
> JS method call SharedConnection.SubscribeToEMsg with 2 arguments
> JS method call SharedConnection.SubscribeToEMsg with 2 arguments
> JS method call SharedConnection.SubscribeToEMsg with 2 arguments
> JS method call SharedConnection.SubscribeToEMsg with 2 arguments
> JS method call SharedConnection.SubscribeToEMsg with 2 arguments
> JS method call SharedConnection.SubscribeToEMsg with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
> JS method call SharedConnection.RegisterOnLogonInfoChanged with 2 arguments
> JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
> JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
> JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
> JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
> JS method call Parental.RegisterForParentalSettingsChanges with 1 arguments
> JS method call Broadcast.RegisterForBroadcastStatus with 1 arguments
> JS method call Broadcast.RegisterForViewerRequests with 1 arguments
> JS method call SharedConnection.RegisterOnMessageReceived with 2 arguments
> JS method call SharedConnection.SendMsg with 2 arguments
> JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
> JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
> JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
> JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
> JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
> JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
> JS method call WebChat.BSuppressPopupsInRestore with 1 arguments
> GameAction [AppID 377840, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
> wine: Call from 0x7b43c45c to unimplemented function mscoree.dll.CorIsLatestSvc, aborting
> wine: Unimplemented function mscoree.dll.CorIsLatestSvc called at address 0x7bc50023:0x7b43c45c (thread 0017), starting debugger...
> wine: Call from 0x7b43c45c to unimplemented function mscoree.dll.CorIsLatestSvc, aborting
> wine: Unimplemented function mscoree.dll.CorIsLatestSvc called at address 0x7bc50023:0x7b43c45c (thread 0017), starting debugger...
> GameAction [AppID 377840, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
> GameAction [AppID 377840, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
> GameAction [AppID 377840, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
> GameAction [AppID 377840, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
> GameAction [AppID 377840, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
> Opted-in Controller Mask: 71
> Game update: AppID 377840 "", ProcID 10910, IP 0.0.0.0:0
> \>\>\> Adding process 10910 for game ID 377840
> GameAction [AppID 377840, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> GameAction [AppID 377840, ActionID 1] : LaunchApp changed task to Completed with ""
> \>\>\> Adding process 10911 for game ID 377840
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> \>\>\> Adding process 11036 for game ID 377840
> \>\>\> Adding process 11037 for game ID 377840
> \>\>\> Adding process 11038 for game ID 377840
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> \>\>\> Adding process 11041 for game ID 377840
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> \>\>\> Adding process 11043 for game ID 377840
> \>\>\> Adding process 11046 for game ID 377840
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> wine: Call from 0x7b43c45c to unimplemented function mscoree.dll.CorIsLatestSvc, aborting
> wine: Unimplemented function mscoree.dll.CorIsLatestSvc called at address 0x7bc50023:0x7b43c45c (thread 0015), starting debugger...
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> \>\>\> Adding process 11054 for game ID 377840
> \>\>\> Adding process 11056 for game ID 377840
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> \>\>\> Adding process 11062 for game ID 377840
> ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> \>\>\> Adding process 11071 for game ID 377840
> \>\>\> Adding process 11076 for game ID 377840
> pid 11039 != 11038, skipping destruction (fork without exec?)
> Game removed: AppID 377840 "", ProcID 10910 
> No cached sticky mapping in ActivateActionSet.

And these are all the info of my system: [Steam system info](https://gist.github.com/lucavallerini/cf4d8db97f8b8a89a62d2c9abe9fcee4).

**Comment by kisak-valve** [comment]
Hello @lucavallerini, this game is already being tracked at #708 and we'll be using one issue report per unofficially supported game title.

Separately, `wine: Call from 0x7b43c45c to unimplemented function mscoree.dll.CorIsLatestSvc, aborting` in the log indicates #18 is related.

In the future please use a [gist](https://gist.github.com/) for large pastes.

Closing as a duplicate.

**Comment by lucavallerini** [comment]
Sorry, I searched for an already open issue before posting and I did not find any for FF IX. I probably missed it.

Thank you for pointing me out to issue #18, I will take a look.

EDIT: @kisak-valve  I did not missed the other issue, the title is spelt wrong on #708 and so it did not come up as a result. If you can correct the title it would be helpful for other people.
