### ISSUE TITLE
Feature request: Allow for (non-default) running of games with a native Linux port through Proton

### ISSUE THREAD

**Issue by tadeokondrak** [ValveSoftware/Proton#118]
I realize this isn't a Proton issue, so feel free to close it, but I'm not sure where to post it.

Some Linux ports don't run as well as the Windows version in Wine, so it would be nice to have an option in the settings to enable this.

**Comment by kisak-valve** [comment]
Hello @tadeokondrak, this feature request is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5638. Closing as a duplicate.
