### ISSUE TITLE
Games will not launch on proton if the Seam library is mounted on another drive

### ISSUE THREAD

**Issue by 4thguy** [ValveSoftware/Proton#1180]
This issue drove me insane until I found out how to log what was going on. Basically the games were launching, but then crashing without ever going into the game. And it happened on everything, not just unofficial titles.

```ERROR: ld.so: object '/home/user/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wine: /mnt/sdb1/Steam Library/steamapps/compatdata/22200/pfx is not owned by you
ERROR: ld.so: object '/home/user/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wine: /mnt/sdb1/Steam Library/steamapps/compatdata/22200/pfx is not owned by you
```

Maybe it's the way that I set up my second drive, but because pfx was not owned by me, the games refused to launch.

Once I moved the game in my ~/user folder, everything worked as expected.

**Comment by cobblestone** [comment]
Hi 4th guy,
I am NOT from support. I just want to mention that I run all my steam library from an external drive and works perfectly. 

There is an article about an issue similar than yours and apparently its related to the file system of your external drive.  Have a look, maybe it will help.

https://github.com/ValveSoftware/Proton/wiki/Proton-FAQ#none-of-my-games-are-launching--prefix-not-owned-by-you-error

**Comment by 4thguy** [comment]
I'm looking into this. I added my user id in the mount options `nosuid,nodev,nofail,x-gvfs-show,uid=1000,gid=1000`, but it doesn't seem to have any effect.

No other program gives me any trouble with data on an NTFS drive. It's kind of sad to see it happen here without an error message.

**Comment by minisori** [comment]
Are you using ntfs-3g?

**Comment by 4thguy** [comment]
I'm using whatever's the default on Ubuntu 18.04 :)

**Comment by minisori** [comment]
Well you should use ntfs-3g for uid and gid to work. It looks like you are using diskmanager to mount the drive, if so change the last line where says auto to ntfs-3g, but install it before.
In the other hand, if you don't need to auto mount the partition, you can simply use filemanager to mount it when you need and it will be done as your user hence you will not have this problem.

**Comment by 4thguy** [comment]
Thanks :+1:
