### ISSUE TITLE
Doom 2016 Multiplayer Crash

### ISSUE THREAD

**Issue by ProhibitedUsername** [ValveSoftware/Proton#1190]
Attempting to play Doom via Steam Play on Linux Mint 18.3 . By in large the game seems to run very smoothly, except at the commencement of a multiplayer match, at which point the game will crash citing an error in the engine. I have tried interacting with the error window, but my mouse cannot do anything more than kill it, or drag it about the screen, and I cannot find any files detailing the crash in the directory cited. Attached is an example of my screen after a crash. I would provide more information, but I'm not sure what else you would definitely want that I have not already tried to find for you.
![screenshot from 2018-09-02 00-24-34](https://user-images.githubusercontent.com/42917355/44960169-b235f780-aef2-11e8-80ee-1ccec97d7160.png)

Thanks for reading.

**Comment by kisak-valve** [comment]
Hello @ProhibitedUsername, this issue is already being tracked at #222. Closing as a duplicate.
