### ISSUE TITLE
FlatOut 2 only UI works.

### ISSUE THREAD

**Issue by alvarlagerlof** [ValveSoftware/Proton#1192]
The UI, sound and everything like that works, but when i load a map i see only sun flares. No game. It is running, because I can drive the car and hear it crashing into stuff. But I see nothing. I have tried on both 3.7-5-beta and 3.7-3. Neither works. Is this Proton or the game? Can i fix it somehow?

[Here it seems to work](https://proton.city/game.html?id=2990)
[Steam system infromation](https://gist.github.com/alvarlagerlof/c711341605a4e13b2b888ca1799d5525)

![Looks like this](https://user-images.githubusercontent.com/14835120/44960817-5bd2b400-af06-11e8-8c02-9cc3650afa59.png)

**Comment by kisak-valve** [comment]
Hello @alvarlagerlof, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/109#issuecomment-417961452.
