### ISSUE TITLE
Witcher 2

### ISSUE THREAD

**Issue by master-caster** [ValveSoftware/Proton#1194]
I know there is a "native" version of the game for linux.
But it is of really poor quality. In the middle part of the game 
the game crashes every 5 - 10 minutes at least for me.

Since the game itself uses some sort of compatibility layer i think
this game would benefit if you can download the windows version and use proton instead.

Any chances for this?

**Comment by kisak-valve** [comment]
Hello @master-caster, this feature request is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5638. Closing as a duplicate.

**Comment by pierrep** [comment]
@master-caster this may not be your problem, but try deleting some of your save games. I had this problem..it's an issue with the Windows version as well. If you reduce your save games to less than 10 you should be fine.

**Comment by master-caster** [comment]
thank you for your replies.

@pierrep yeah having less than 10 save games helped a lot but once in a while it crashed anyway

**Comment by CuriousTommy** [comment]
The latest steam version now supports running proton for native games. I was curious to see how the performance would be compared to the native version, but it seems to silently fail. I attached a log and my specs below for proton devs to look at.

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3600 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux 4.x (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.20.3-200.fc29.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  12003000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2019-01-10

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) 
    Driver Version:  3.0 Mesa 18.2.8
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0x191b
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.78" x 7.48" (15.67" diag)
                                            35.0cm x 19.0cm (39.8cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC3266

Memory:
    RAM:  32086 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  382216 Mb
    Largest Free Hard Disk Block:  119210 Mb
    VR Headset: None detected

Recent Failure Reports:
```
[steam-20920.log](https://github.com/ValveSoftware/Proton/files/2823733/steam-20920.log)


On a sidenote, would it be possible to have this issue be reopened?

**Comment by kisak-valve** [comment]
Hello @CuriousTommy, at this point it would be better to open a new issue report and use the compatibility report template.

**Comment by CuriousTommy** [comment]
@kisak-valve Okay, I'll set up a new report later.
