### ISSUE TITLE
Icon in List View

### ISSUE THREAD

**Issue by basxto** [ValveSoftware/Proton#1195]
The situation right now is:
* cloud support is only visible in List View
* whether proton is used or not is only visible in Detail View

It would be great to see proton support also in the much smaller List View.
It must not be an icon, I think a different status would also do: `Ready to play with Steam Play` and `Not installed with Steam Play`

Right now for easily finding proton games in your library you need external tools like https://www.lorenzostanco.com/lab/steam/

**Comment by kisak-valve** [comment]
Hello @basxto, this is a feature request for the steam client rather than Proton itself, so I've gone and transferred this request to https://github.com/ValveSoftware/steam-for-linux/issues/5722.
