### ISSUE TITLE
Update DXVK to v0.71

### ISSUE THREAD

**Issue by romulasry** [ValveSoftware/Proton#1196]
https://github.com/ValveSoftware/dxvk/pull/4

**Comment by tingvarsson** [comment]
And enable dx10 support (requires some minor changes to proton as well to get the dll overrides in place)

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/dxvk/pull/4.

**Comment by jmannanc** [comment]
@tingvarsson if/when DXVK is updated, feel free to open a PR of you know how to do that. I'm not too sure myself, so best if someone else does it.

**Comment by gbdlin** [comment]
@SneakyFish5 there is no need to wait for DXVK to be updated - support for DX10 is already present in v0.71. It just have to be enabled on Proton side.
