### ISSUE TITLE
Force Proton on native linux games.

### ISSUE THREAD

**Issue by OVERPWREDCATSCIENCE** [ValveSoftware/Proton#1197]
Would it be possible to add a setting to force games to use Proton instead of running natively, this would allow for more testing and polish, as well as a possible performance/user experience increase, let's say a company makes a bad Linux version, but a stellar Windows version, so the only way to enjoy the game would be to run in through Proton, instead of natively.

See picture:
![steam proton](https://user-images.githubusercontent.com/17804617/44964596-532aaf80-aeff-11e8-9a3a-4c8c8a4c365c.png)

**Comment by ghost** [comment]
Maybe a second option too that just does this for problematic linux ports; a separate whitelist. Wouldn't good ports also be affected if we only have a force proton option?

**Comment by OVERPWREDCATSCIENCE** [comment]
Hmm. Maybe an option to force Proton on certain games, let's say a game runs well only through Proton, you could force it for that game, and still play another game natively. So it would be a toggle for each individual game, instead of every game.

**Comment by daasuharo** [comment]
And maybe like the controller config shows how many people are using a shared configuration we could have the amount of people with the toggle on for a game. This way we'd have less people downloading the linux port only to find it with issues and having to redownload the windows port to try to see if it works better. The toggle would also allow Valve to collect that data too if it'll help in creating an automated whitelist. What do you think of that @OVERPWREDCATSCIENCE ?

**Comment by linkjay** [comment]
Already made an issue for this that was closed in favor for another issue on a different repo.

See: https://github.com/ValveSoftware/Proton/issues/52

**Comment by ghost** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/5638
Link to open issue being tracked

**Comment by nstgc** [comment]
Throwing my two cents in in regards to this specific design idea, I would rather NOT force Steam Play onto ALL Linux titles. Many of them are fine.

**Comment by Dexter9313** [comment]
@nstgc Yes, choice is always better ! Make it a per game feature.

**Comment by kkmzero** [comment]
One specific flag (-parameter) for launcher maybe?

**Comment by kisak-valve** [comment]
Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5638.

**Comment by nstgc** [comment]
@kkmzero I don't think so, since you need to download the Windows version. Launch options are just that: options at application launch.

**Comment by freerunnerlive** [comment]
Yes, because of "little racers street" :-D native port but doesn't work on linux :-)

**Comment by draxil** [comment]
If you could do this selectively, it would be nice. For example the Civ 6 port is very behind the windows version which is very annoying if you want to play multiplayer.
