### ISSUE TITLE
xcb/xcb.h missing on macOS

### ISSUE THREAD

**Issue by eisnerguy1** [ValveSoftware/Proton#12]
So, I'm trying to compile this on macOS Sierra.  I followed all of the instructions for building on macOS.  
I just got this error message:
`/Users/eisnerguy1/proton/SDL-mirror/src/video/./khronos/vulkan/./vk_platform.h:117:10: fatal error: 'xcb/xcb.h' file not found`

Here's the full Terminal output after running "./build_proton.sh":
[terminal_output.txt](https://github.com/ValveSoftware/Proton/files/2308532/terminal_output.txt)

Looks like there's something missing here.  Is it something I need to install via Homebrew?

**Comment by Mikerr1111** [comment]
This looks like an issue with Vulkan. Something you might want to try testing is to see if you can successfully install and run [MoltenVK ](https://github.com/KhronosGroup/MoltenVK) on your system.

**Comment by eisnerguy1** [comment]
I did the [Installing MoltenVK](https://github.com/KhronosGroup/MoltenVK#installing-moltenvk), [Building MoltenVK](https://github.com/KhronosGroup/MoltenVK#building) & [Running the MoltenVK Demo Applications](https://github.com/KhronosGroup/MoltenVK#demos) sections without issue.  Was there another section you were referring to?

**Comment by eisnerguy1** [comment]
I'm still getting the same exact error message with the newest source. Here's the Terminal output after running "./build_proton.sh":
[terminal_ouput_new.txt](https://github.com/ValveSoftware/Proton/files/2362979/terminal_ouput_new.txt)

There's got to be a dependency missing but, I'm not sure what exactly or how to fix the problem.

**Comment by eisnerguy1** [comment]
Still having the same issue.  Here's the Terminal output after running "./build_proton.sh":
[terminal_output_new.txt](https://github.com/ValveSoftware/Proton/files/2430309/terminal_output_new.txt)

**Comment by nobodywasishere** [comment]
This issue should be closed due to the removal of MacOS support
