### ISSUE TITLE
Fallout shelter fullscreen freeze Gnome Shell

### ISSUE THREAD

**Issue by Xenega** [ValveSoftware/Proton#1202]
Running Fallout Shelter in full screen freeze Gnome Shell and Xorg, not only with the proton window, but all windows. The desktop become unusable and restart after some time.

Tested with proton 3.7.3 and 3.7.5-beta.

Ubuntu 18.04.5
Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
4.15.0-33-generic x86_64
GeForce GTX 1060 Mobile
NVIDIA 390.48
GNOME Shell 3.28.3
X.Org version: 1.19.6
resolution 1920x1080

**Comment by kisak-valve** [comment]
Hello @Xenega, please update your nvidia driver to 396.51 or newer.

**Comment by Xenega** [comment]
Thx. I installed it, the driver 390 was at fault. 

Unfortunately, the 396 is not currently available in long term support repository. Furthermore, 390 is the long-lived branch, it would be better it works with.

**Comment by kisak-valve** [comment]
Closing as nvidia 396.51 or newer is a [prerequisite](https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md) for Proton.
