### ISSUE TITLE
DOOM (2016) crashing when trying to load multiplayer map

### ISSUE THREAD

**Issue by DarkMorty-PL** [ValveSoftware/Proton#1203]
I'm running single player mode in DOOM (2016) with Vulkan API and it works perfectly. 
When I join to lobby in multiplayer mode and few seconds later game trying to load multiplayer map, then screen turns black and window with the following error appears:

DOOM Unhandled Exception
The engine has crashed!

Tested with Proton 3.7-5 beta. Playing offline multiplayer with bots works fine.
Ubuntu 18.04.1
Intel(R) Core(TM) i5-760 CPU @ 2.80GHz
Kernel version: 4.15.0-33-generic
Graphics card: GeForce GTX 1050 Ti
Driver version: NVIDIA 390.48
GNOME Shell 3.28.3
Resolution: 1920x1080

Here's the crash reports, from Vulkan and OpenGL 4.5 API:
[DOOM crash (OpenGL).txt](https://github.com/ValveSoftware/Proton/files/2345167/DOOM.crash.OpenGL.txt)
[DOOM crash (Vulkan).txt](https://github.com/ValveSoftware/Proton/files/2345168/DOOM.crash.Vulkan.txt)

**Comment by kisak-valve** [comment]
Hello @DarkMorty-PL, this issue is already being tracked at #222. Closing as a duplicate.
