### ISSUE TITLE
[Mac OS] Corresponding binaries of glslang

### ISSUE THREAD

**Issue by 3t0n** [ValveSoftware/Proton#121]
Linux binaries of glslang can't be run on Mac OS. 
So should be replaced on Mac (https://github.com/KhronosGroup/glslang/releases)

**Comment by zakk4223** [comment]
MoltenVK actually pulls in glslang as part of its build; the build script could just swap that linux binary with a symlink to the MoltenVK glslangvalidator

**Comment by flukejones** [comment]
See issue #29 also - duplicate.
