### ISSUE TITLE
Puyo Puyo™Tetris® audio issue

### ISSUE THREAD

**Issue by Inglebard** [ValveSoftware/Proton#1215]
Hi,

I just test Puyo Puyo™Tetris® on proton 3.7-3.

The game seems to work globally.
There is audio issue. Maybe more information here : https://appdb.winehq.org/objectManager.php?sClass=version&iId=36583 .

Tested on : Inspiron 15 3567
OS : Archlinux
CPU : intel i5-7200u
GPU : intel i5-7200u
RAM : 8G

**Comment by kisak-valve** [comment]
Hello @Inglebard, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/359#issuecomment-418177370.
