### ISSUE TITLE
Stalker clear sky (20510) Screen resolution disappeared proton 3.7-5 Beta

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/Proton#1221]
Stalker clear sky (20510) screen resolution 1366x768 disappeared, also, order of resolutions became random.

**Comment by kisak-valve** [comment]
Hello @XakepSDK, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1166#issuecomment-418204276.
