### ISSUE TITLE
dead space keyboard input dont work after 1 minute on main menu

### ISSUE THREAD

**Issue by mrdeathjr28** [ValveSoftware/Proton#1222]
dead space keyboard input dont work after 1 minute on main menu and after this dont work on game

input works without issues on regular wine

**Comment by kisak-valve** [comment]
Hello @mrdeathjr28, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/293#issuecomment-418210528.
