### ISSUE TITLE
Gran Skrea Online - the whole system freezes with Proton stable (595110)

### ISSUE THREAD

**Issue by Reiddragon** [ValveSoftware/Proton#1224]
When running the game with the Stable version of Proton, the game hangs for a few seconds before the whole system does the same. Obviously, can't get any crash log for the game when something like that happens.
Afterwards I tried Proton Beta, and it was slightly better. "Slightly", because the game still hangs, but the rest of the system isn't affected anymore.
I tried digging trough the game files for some log files, but couldn't find anything.

Sorry if my issue isn't of much help on why any of this happens.

**Comment by kisak-valve** [comment]
Hello @Reiddragon, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Reiddragon** [comment]
Here is it:
https://gist.github.com/Reiddragon/1be606f60ad9959cf724ecd5d055df14

**Comment by kisak-valve** [comment]
If possible, please retest with mesa built against LLVM 7+.

**Comment by Reiddragon** [comment]
not possible, this is my only machine that I can't afford to run unstable software on

**Comment by Reiddragon** [comment]
closing this issue as it is nearly 5 years old and a lot has changed since then
