### ISSUE TITLE
The Witness

### ISSUE THREAD

**Issue by glubsy** [ValveSoftware/Proton#1228]
SPECS:
[Steam system information report](https://gist.github.com/glubsy/add907528ea037938bcfe2047b9044b6)
Kernel: 4.14.67-1-lts x86_64
Desktop Env: i3 4.15
Distro: Antergos Linux (Arch Linux based)
Device: laptop System: CLEVO Mobo: P370EM
CPU:    Quad core Intel Core i7-3740QM (-MT-MCP-) 3700 MHz
Graphics:
GPU: NVIDIA GK104M [GeForce GTX 670MX]
Display Server: X.Org 1.20.1 Resolution: 1920x1080 60.02hz
OpenGL: renderer: GeForce GTX 670MX/PCIe/SSE2 
Nvidia driver version: 4.6.0 NVIDIA 396.54
Memory: 16 GB

The game fails to start. I noticed these two lines in the [Proton log](https://gist.github.com/glubsy/6a7cce767fe4923fa42456d536b8bb9b):
```
124076.437:0025:0026:err:vulkan:wine_vk_init Failed to load libvulkan.so.1.
124076.437:0025:0026:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
```

Dota2 (native, not Wine) using Vulkan work just fine though, so I think my GPU should be able to use DXVK.
Using `PROTON_USE_WINED3D11` works but the performance is terrible and some graphical glitches, obviously the OpenGL renderer is not ideal here.

Using Proton 3.7.5 beta.

**Comment by kisak-valve** [comment]
Hello @glubsy, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/344#issuecomment-418399957.
