### ISSUE TITLE
Warframe (230410)

### ISSUE THREAD

**Issue by valeth** [ValveSoftware/Proton#1229]
There wasn't a tracking issue for Warframe yet like for other games.

Current issues mentioned in https://github.com/ValveSoftware/Proton/issues/167 so far:
- [ ] Regular launcher does not start, requires workaround
- [ ] Game exits after ~5 minutes if no controller is plugged in
- [ ] Game stutters a lot, probably due to shader compilation

Other issues I found:
Sound crackling/stutter after playing for a while. Does not always occur, but most of the time after ~1h of playtime.

**Comment by kisak-valve** [comment]
Hello @valeth, we'll be using one issue report per unofficially supported game title and there shouldn't be any meta-tracking issue reports for single games. Where did you see one?
