### ISSUE TITLE
Graphics and Controller issues

### ISSUE THREAD

**Issue by sorin255** [ValveSoftware/Proton#1232]
I'm having a couple issues with special edition.

One is getting the graphics options to stick. The launcher auto-detect sets things to Ultra, but when I launch the game I get windowed and low graphics settings. I go into settings on the launcher and set everything manually, but that doesn't stick either. I'm not sure if there's an issue generating an ini file or something else.

The second is controller. I'm having issues with controller support through proton in general, but my controller isn't detected at all.

**Comment by parkerlreed** [comment]
First off, you don't even say what game you're talking about.

Second, check to see if there's already a topic for whatever game you are going on about.

Third, post specs along with it.
