### ISSUE TITLE
[Whitelist] Wolcen: Lords of Mayhem (424370)

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#1234]
Distro: Manjaro XFCE 17.1.12
GPU: GTX 1060, Nvidia proprietary driver 396.54
Resolution: 1920x1080
RAM: 8GB
Proton 3.7-5 Beta

All is fine

**Comment by kisak-valve** [comment]
Hello @liberodark, this game is already being tracked at #496, so I've transferred this issue report to https://github.com/ValveSoftware/Proton/issues/496#issuecomment-418453086.
