### ISSUE TITLE
No Proton games will launch on Ryzen 2500U/Vega M laptop

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#1236]
I've tried enough at this point that I think my problem merits some kind of bug report.
 
I have a ThinkPad E585 with an AMD Ryzen 5 2500U / Vega M. I simply cannot get any game to launch.  I double click the game, Steam shows it's "Running...." for about 0.5 seconds and that's it.  No game window ever pops up.   I'm on KDE Neon ([Ubuntu 18.04 base](https://files.kde.org/neon/images/bionic-preview/neon-useredition/20180823-0538/))

Here is a screen recording of what happens when I try to launch any Steam Play games:
https://gfycat.com/NervousSleepyAmericancrayfish

As far as I can tell, I've done everything necessary to meet the requirements.  

- padoka ppa added
- mesa-vulkan-drivers and mesa-vulkan-drivers:i386 installed
- **EDIT**: also libvulkan1, libvulkan1:i386
- llvm-8 installed **EDIT**: also llvm-8:i386
- running very new kernel
- mesa 18.3.0
- tested 3.7-5 beta as well as 3.7-3 default
- **EDIT**: also python 2.7 and 3.6 are installed

I've tried running Steam from the terminal to see if I could get some error message to pop up, but no messages come through.  

I received a recommendation on the unofficial SteamPlay Discord to try adding two different commands to the game's launch parameters to dump a log, but no log is created.

`WINEDEBUG="+timestamp,+pid,+tid,+seh,+debugstr,+module" %command%`
~~`PROTON_LOG %command%`~~ **EDIT**: `PROTON_LOG=1 %command%` 

~~I can't seem to find any error output to debug the cause of this.   System info below.  Happy to provide more info as requested.  Thanks.~~ **EDIT**: I had the command wrong, it's generating logs now.

If something is missing from my system and this isn't a bug, then perhaps the PREREQS.md doc should be updated.

```
$ screenfetch -n
 OS: KDE neon 5.13
 Kernel: x86_64 Linux 4.18.5-041805-generic
 Uptime: 20m
 Packages: 1789
 Shell: bash 4.4.19
 Resolution: 1920x1080
 DE: KDE 5.49.0 / Plasma 5.13.4
 WM: KWin
 GTK Theme: Breeze [GTK2/3]
 Icon Theme: breeze
 Font: Noto Sans Regular
 CPU: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx @ 8x 2GHz [50.0°C]
 GPU: AMD RAVEN (DRM 3.26.0, 4.18.5-041805-generic, LLVM 8.0.0)
 RAM: 2563MiB / 15725MiB
```

```
$ glxinfo | grep "OpenGL version"
OpenGL version string: 4.4 (Compatibility Profile) Mesa 18.3.0-devel - padoka PPA
```

```
$ sudo lshw -c video
  *-display                 
       description: VGA compatible controller
       product: Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:05:00.0
       version: c4
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi msix vga_controller bus_master cap_list
       configuration: driver=amdgpu latency=0
       resources: irq:73 memory:b0000000-bfffffff memory:c0000000-c01fffff ioport:1000(size=256) memory:c0600000-c067ffff
```

```
$ uname -r
4.18.5-041805-generic
```

```
$ lsmod | grep amd
edac_mce_amd           28672  0
kvm_amd                94208  0
ccp                    81920  1 kvm_amd
kvm                   622592  1 kvm_amd
amdkfd                237568  1
amd_iommu_v2           20480  1 amdkfd
amdgpu               2940928  41
chash                  16384  1 amdgpu
gpu_sched              24576  1 amdgpu
i2c_algo_bit           16384  1 amdgpu
ttm                   106496  1 amdgpu
drm_kms_helper        172032  1 amdgpu
drm                   458752  21 gpu_sched,drm_kms_helper,amdgpu,ttm
```

```
$ vulkaninfo
Lots of output, linked here so this thread isn't a mile long: 
https://pastebin.com/raw/uTAUwAT6
```

**Comment by kisak-valve** [comment]
Hello @arcooke, Proton 3.7-3 needs Python 2.7 to run, can you check if you system has that installed?

**Comment by ghost** [comment]
Thanks @kisak-valve .. yes I do have python 2.7 installed.  That was another thing I did yesterday trying to troubleshoot.  I have 2.7.15rc3 installed as of writing.

I also have Python 3.6 installed

**Comment by ghost** [comment]
My vulkaninfo output does show two errors directly at the top, not sure if this could be related:

```
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
```

**Comment by LeJimster** [comment]
Make sure you have the vulkan loader library installed, this seems to be quite a common problem.
```
sudo apt-get install libvulkan1
sudo apt-get install libvulkan1:i386
```

**Comment by ghost** [comment]
@LeJimster Those are both installed already, version 1.1.70 on both

**Comment by LeJimster** [comment]
@arcooke do you have some intel vulkan drivers installed?  Maybe try removing them.

**Comment by ghost** [comment]
@LeJimster I don't think so.. there's no Intel hardware in my system.  How can I check for this?  Thanks

**Comment by lieff** [comment]
Most probably libvulkan_intel.so is from mesa package, apt-file search libvulkan_intel.so
must show file origin.

**Comment by aeikum** [comment]
I'd try to get some logging out of Steam itself. Close all instances of Steam, open a Terminal, and launch it there with `steam`. Watch for any output as you launch a game.

There is also a small error in your game launch options. It should be `PROTON_LOG=1 %command%`. If proton is able to run, this will output a file in your Home directory called `steam-1234.log`, where 1234 is the game's appid on Steam. Additionally, this variable will only work on the 3.7-5 Beta. Do not set WINEDEBUG (or any other WINE variable) in the game launch options.

What happens if you run "python3" in a terminal?

Finally, Skyrim is a pretty demanding game. It might be better to start with a smaller, less demanding game, if you have one available, just to ensure Proton itself is working before you try to diagnose Skyrim issues.

**Comment by LeJimster** [comment]
Can you check what files are in `/usr/share/vulkan/icd.d`

You should only need `radeon_icd.i686.json` & `radeon_icd.x86_64.json`

**Comment by ghost** [comment]
@lieff That does show up in a search.. but I found the issue

```
sudo apt-file search libvulkan_intel.so
mesa-vulkan-drivers: /usr/lib/x86_64-linux-gnu/libvulkan_intel.so
```

@aeikum 

> It should be PROTON_LOG=1 %command%. 

That did the trick, I now have a log!  Thanks for that

Banished:
```
ERROR: ld.so: object '/home/adam/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wine: /mnt/700047A204100D0F/Games/Steam/SteamPlay/steamapps/compatdata/242920/pfx is not owned by you
ERROR: ld.so: object '/home/adam/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/adam/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wine: /mnt/700047A204100D0F/Games/Steam/SteamPlay/steamapps/compatdata/242920/pfx is not owned by you
```

Skyrim
```
ERROR: ld.so: object '/home/adam/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wine: /mnt/700047A204100D0F/Games/Steam/SteamPlay/steamapps/compatdata/72850/pfx is not owned by you
ERROR: ld.so: object '/home/adam/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/adam/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wine: /mnt/700047A204100D0F/Games/Steam/SteamPlay/steamapps/compatdata/72850/pfx is not owned by you
```



Turns out there's a Wine access problem on my mounted drive I'm using as an additional content library in Steam.  

I moved my game files to the local disk and I got a game to launch!  Thanks everyone for the help.. I can take it from here.

It does seem though that there's a slight problem.  The games are installed by steam under the root user instead of me.  

```
/mnt/700047A204100D0F/Games/Steam/SteamPlay/steamapps$ ls -l
total 18
-rwxrwxrwx 1 root root  821 Sep  4 14:18 appmanifest_72850.acf
-rwxrwxrwx 1 root root  570 Sep  3 20:14 appmanifest_858280.acf
-rwxrwxrwx 1 root root  580 Sep  4 14:21 appmanifest_930400.acf
drwxrwxrwx 1 root root 4096 Sep  4 14:21 common
drwxrwxrwx 1 root root    0 Sep  3 20:13 compatdata
drwxrwxrwx 1 root root 4096 Sep  4 14:21 downloading
drwxrwxrwx 1 root root    0 Sep  3 20:13 shadercache
drwxrwxrwx 1 root root    0 Sep  4 14:21 temp
drwxrwxrwx 1 root root 4096 Sep  4 14:21 workshop
```

**Comment by aeikum** [comment]
It's an NTFS drive, right? There's a bunch of open issues about that, it's not well supported.

**Comment by ghost** [comment]
@aeikum Yep.  Funnily enough, I did have it formatted as fat32 mounted as vfat in fstab.. but I was having issues getting steam to add that location as a library.  It was giving me an error about needing to be marked as executable or something, so I formatted to NTFS

Is fat OK?  This is meant to be a partition I can share between windows and linux to store games.

**Comment by kisak-valve** [comment]
Sharing steam libraries between installs is not supported and your mileage will vary. People are able to use NTFS partitions, but it needs to be handled carefully.

Close this in favor of #11 / #104.

**Comment by aeikum** [comment]
Windows filesystems (FAT, NTFS) aren't good fits for Linux software because they don't provide the features the Linux filesystems support. For example they have stricter filename requirements, their permissions and ownership capabilities are mutually incompatible, symlink support is weak, case insensitivity can be awkward. It can be done, but it's best avoided if possible. For Proton in particular, we didn't design for those limitations, so these problems crop up.

**Comment by lieff** [comment]
On windows ext4 can be accessed using http://www.paragon-drivers.com/extfs-windows/

**Comment by ghost** [comment]
Thanks for the help everyone. I'll rethink my storage strategy.  I'm good to go now otherwise.

Skyrim runs at a surprisingly nice 30-40FPS on high settings @ 1080, and Banished ran at full 60FPS.  Not bad for this little AMD APU.  Very impressed

@kisak-valve I do think it might be helpful to add information about the libvulkan1 and python requirements to the PREREQS doc.
