### ISSUE TITLE
[Whitelist] SEGA Mega Drive and Genesis Classics (34270)

### ISSUE THREAD

**Issue by shane-powell** [ValveSoftware/Proton#1238]
Works fine without issue and using USB xbone controller.

Specs https://gist.github.com/kenjara/b9aae11a5124fca193bbb6c7e5615ee8

**Comment by kisak-valve** [comment]
It's also a native linux game.

**Comment by shane-powell** [comment]
Store page needs updating as it shows only the Windows logo. Sorry about that.

**Comment by khanson679** [comment]
The normal version (the virtual bedroom) is not working for me with Proton 4.2.7 (on Ubuntu 19.04). On launch, it complains that DirectX11 is not available. After adding `PROTON_USE_WINED3D11=1 %command%` to the launch options, it runs, but gets stuck on a black screen.

The "Simple Launcher" seems to work, but I haven't tested it thoroughly.
