### ISSUE TITLE
Compatibility with Resident Evil Remake HD on Ubuntu 16.04 

### ISSUE THREAD

**Issue by fredericokremer** [ValveSoftware/Proton#1239]
The game installs and can be executed. The Capcom logo is showed in a non-full screen window. Then, a black screen remains in the window, and the game is not loaded. There is my system settings:

 OS: Ubuntu 16.04 xenial
 Kernel: x86_64 Linux 4.15.0-33-generic
 Uptime: 15m
 Packages: 3356
 Shell: bash 4.3.48
 Resolution: 1366x768
 DE: Unity 7.4.0
 WM: Compiz
 WM Theme: Ambiance
Ambiance [GTK2]
, Ambiance [GTK3]
 Icon Theme: Papirus-Dark
 Font: Cantarell 11
 CPU: Intel Core i7-6500U CPU @ 3.1GHz
 GPU: GeForce 930M
 RAM: 5344MiB / 15742MiB

**Comment by kisak-valve** [comment]
Hello @fredericokremer, this game is already being tracked at #576. Closing as a duplicate.
