### ISSUE TITLE
S.T.A.L.K.E.R.: Call of Pripyat crashes on startup using DX11

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#1243]
When trying to use Enhanced Full Dynamic Lighting (DX11), the game will crash on startup.

Using Arch Linux with Proton 3.7-5beta.

**Comment by kisak-valve** [comment]
Hello @shoober420, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1174#issuecomment-418706266.
