### ISSUE TITLE
SteamOS Proton no activation docs

### ISSUE THREAD

**Issue by benrosie** [ValveSoftware/Proton#1251]
Steam on Debian linux shows Steam Play in settings where is this in SteamOS to activate Steam Play Proton a Doc would be useful.

Steam Support
Home > My Recent Help Requests > HT-CFM6-3HMD-Y46X
Ticket: HT-CFM6-3HMD-Y46X
Your help request: I am having trouble with Big Picture
Related to:	Steam

Message from you on Aug 29 @ 12:17pm	| 7 days ago
Good day.

I have setup SteamOS on a separate system have selected participate in Steam Beta on system preferences with the goal of running the WineHQ / Proton Build running Windows games on SteamOS. However the "Steam Play" settings are illusive i.e. I cannot find it or any docs on steam searches on a search engine. In the non big picture version it appears in settings as seen on ( https://www.back2gaming.com/reviews/b2g-games/pc/playing-windows-games-on-linux-is-now-easy-with-steams-proton/ ) screenshot with the Proton 3.7-4 Beta options. Can you help to describe how I "Enable Steam Play for all titles" as shown in this screenshot for SteamOS.

Many Thanks

Files attached:	support_system_report.vdf	  minidumps_and_logs.zip	 

Message from you on Aug 29 @ 1:10pm	| 7 days ago
Hi So I aatempted this:->

On SteamOS->Existed to Desktop->Home->Computer->home->desktop->Steam->Desktop->clicked steam

Steam updated with the standard steam installer non big picture version i logged in and then went to settings->Steam Play->Enabled Steam Play on all titles

Will see how that works.

Message from you on Aug 29 @ 1:18pm	| 7 days ago
So the big picture SteamOS is a separate install of steam to the 2nd install i created. SteamOS no obvious way to initialise the Proton options for Steam Play. Exiting to desktop and running the second version of steam results in Steam Play options availble.

Message from Steam Support on Aug 29 @ 7:34pm	| 7 days ago
We are glad to hear that you were able to resolve the issue with enabling all your games to run through Proton.

Please keep in mind that Proton is still in beta, if you have any issues then we encourage you submit a bug report on GitHub for the development team to review:

https://github.com/ValveSoftware/Proton 

Thanks,	
Dillinger
Did this response help you solve the issue?
 
No, I need more help

**Comment by kisak-valve** [comment]
Hello @benrosie, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5631. Closing as a duplicate.
