### ISSUE TITLE
Feel The Snow (538100) - game do not downloads

### ISSUE THREAD

**Issue by lieff** [ValveSoftware/Proton#1255]
Distro: Ubuntu 18.04
GPU: GTX 980, Nvidia proprietary driver 390.48
Resolution: 2560x1440
RAM: 16GB
Proton 3.7-5 Beta

Game folder empty, file validation says all OK.

**Comment by kisak-valve** [comment]
Hello @lieff, looks like this game got a [linux test build](https://steamdb.info/app/538100/depots/) about 8 months ago, switch to the test beta branch. If that doesn't work, report the issue to the game's dev(s).
