### ISSUE TITLE
The Guild II Renaissance (39680) - dark faces on icons

### ISSUE THREAD

**Issue by lieff** [ValveSoftware/Proton#1258]
Distro: Ubuntu 18.04
GPU: GTX 980, Nvidia proprietary driver 390.48
Resolution: 2560x1440
RAM: 16GB
Proton 3.7-5 Beta

![screenshot from 2018-09-05 23-57-17](https://user-images.githubusercontent.com/10080078/45120746-b7e84300-b167-11e8-86a3-665f71abe384.png)

**Comment by kisak-valve** [comment]
Hello @lieff, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1064#issuecomment-418909705.
