### ISSUE TITLE
Adding DL library from previous Windows leaves games in update loop state (confirmation needed)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#126]
After adding a Library folder (previously used by windows), and setting Steam Play for every game, (at least) some games seem to enter an update loop state.
Monster Hunter World displayed it was updating (full game size) and after finishing, it went back to needing update.
A clean install of the game to a different Library folder seem to work past that problem, not issuing any more updates.

Can anyone confirm if this is reproducible? (will add machine information if needed, if you can get me what info/commands I need to get from my side)

**Comment by kisak-valve** [comment]
Hello @Gokuroro, iterated several times over on the steam-for-linux issue tracker. Transferring steamapps folders between OSes is unsupported and completely untested. Your luck with doing that will vary.

Closing as this is not a Proton issue.

**Comment by ghost** [comment]
@kisak-valve while your reasoning is (obviously) correct, I seem to have gotten into that state from a clean install, by changing the Steam Play for all games options as so:
- Set to enable to all games
- Download some windows (Steam Play) games
- Unset the "Enable Steam Play to all games"
- Restart Steam

This gets me to a point where all of those Steam Play games need "updates" (basically redownloads, it seem).

Where can I log this issue if not here, for this specific case?

**Comment by kisak-valve** [comment]
Feel free to open an issue in the [steam-for-linux](https://github.com/ValveSoftware/steam-for-linux) for issues with the steam client.
