### ISSUE TITLE
DiRT 4 (421020) Not disabling Sleep Mode properly

### ISSUE THREAD

**Issue by SteveHeist** [ValveSoftware/Proton#1263]
When playing DiRT 4 in Proton, the computer is still able and even prone to entering Sleep Mode, which can break cutscenes and force the user to restart the game.

Otherwise it is totally playable.

Gist: https://gist.github.com/SteveHeist/1f51e113d17ac6bb8224c70a926d6508

**Comment by kisak-valve** [comment]
Hello @SteveHeist, are you using a controller to play the game? This should be covered by #287.

**Comment by SteveHeist** [comment]
Yes. I was using a Logitech F310 in xinput mode.

**Comment by kisak-valve** [comment]
Thanks, closing in favor of #287.
