### ISSUE TITLE
Dark Souls 3: Gamepad controls mouse (374320)

### ISSUE THREAD

**Issue by mlassnig** [ValveSoftware/Proton#127]
Default installation, wired XBox360 gamepad is correctly recognized as event (not js) device. However, once started the gamepad controls the mouse, instead of, well, being a gamepad. Works as expected in standalone wine-staging+dxvk.

**Comment by bakcxoj** [comment]
My experience has been different. In Dark Souls 3, I can't click anything. I can use the mouse and scroll, but can't click buttons.

**Comment by RCal-Dev** [comment]
I managed to get into game, but I CAN'T MOVE... for some reason D:

**Comment by deah77** [comment]
Ant you help me editing script brow

Pada tanggal Kam, 23 Agt 2018 11:28, Richard C. <notifications@github.com>
menulis:

**Comment by liamphmurphy** [comment]
Maybe this has been fixed in an update? Dark Souls 3 is working for me out of the box, keyboard/mouse and xbox one controllers are working as intended, with a consistent 60 fps.

OS: Arch Linux (Using steam-runtime)
GPU: GTX 1070
Driver: 396.51
CPU: AMD R7 2700

**Comment by mlassnig** [comment]
Ok, I figured it out. I had inadvertedly configured my Xbox controller as a Steam Controller, which defaults to control the mouse in menus.

Everything works as expected, game plays great. Ticket can be closed. Thanks.
