### ISSUE TITLE
SENRAN KAGURA series games stuck at start when full screen mode set in game settings (502800 550080 696170)

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/Proton#1273]
![screenshot from 2018-09-06 08-26-15](https://user-images.githubusercontent.com/200750/45137030-599b7e80-b1c0-11e8-8a9b-6b67124c21c1.png)

https://store.steampowered.com/app/696170/
https://store.steampowered.com/app/502800/
https://store.steampowered.com/app/550080/

This three games was able launched before they are configured for working in full screen mode.
I don't know how to reset game settings for restoring working. Uninstall/install not helps here.

```
$ inxi -bM
System:    Host: localhost.localdomain Kernel: 4.19.0-0.rc2.git0.1.fc30.x86_64 x86_64 bits: 64
           Desktop: Gnome 3.30.0 Distro: Fedora release 29 (Rawhide)
Machine:   Type: Desktop Mobo: ASUSTeK model: ROG STRIX X470-I GAMING v: Rev 1.xx serial: <root required>
           UEFI: American Megatrends v: 0901 date: 07/23/2018
CPU:       8-Core: AMD Ryzen 7 2700X type: MT MCP speed: 2231 MHz min/max: 2200/3700 MHz
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Vega 10 XT [Radeon RX Vega 64] driver: amdgpu v: kernel
           Display: wayland server: Fedora Project X.org 11.0 driver: amdgpu resolution: 3840x2160~60Hz
           OpenGL: renderer: Radeon RX Vega (VEGA10 DRM 3.27.0 4.19.0-0.rc2.git0.1.fc30.x86_64 LLVM 7.0.0)
           v: 4.5 Mesa 18.2.0-rc5
Network:   Device-1: Intel I211 Gigabit Network driver: igb
           Device-2: Realtek RTL8822BE 802.11a/b/g/n/ac WiFi adapter driver: r8822be
Drives:    Local Storage: total: 11.35 TiB used: 4.39 TiB (38.7%)
Info:      Processes: 566 Uptime: 1h 24m Memory: 31.34 GiB used: 25.00 GiB (79.8%) Shell: bash inxi: 3.0.21
```

[steam-696170.log](https://github.com/ValveSoftware/Proton/files/2364236/steam-696170.log)
[steam-502800.log](https://github.com/ValveSoftware/Proton/files/2364235/steam-502800.log)
[steam-550080.log](https://github.com/ValveSoftware/Proton/files/2364234/steam-550080.log)

**Comment by NTMan** [comment]
The games start working after applying patch: https://gitlab.freedesktop.org/xorg/xserver/merge_requests/48
FPS on 4K is acceptable

**Comment by kisak-valve** [comment]
Closing as obsolete, the merge request was backported https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/85 and is in X 1.20.4+
