### ISSUE TITLE
SteamPlay titles keep receiving 0 byte updates

### ISSUE THREAD

**Issue by Reiddragon** [ValveSoftware/Proton#1274]
Title says it all. Games installed trough SteamPlay receive 0 byte updates every time the Steam client is launched.
Not a big issue but annoying nonetheless.

**Comment by lieff** [comment]
Same here.

**Comment by SteveHeist** [comment]
Given these updates move incredibly rapidly, I'd imagine this is a "Proton check" of sorts. Just making sure Proton is still enabled when Steam is booted. Presumably so that if someone disabled Proton it would stop trying to use Proton to boot.

**Comment by minisori** [comment]
With 3.7-5 looks like it does not happen with every game.

**Comment by kisak-valve** [comment]
Hello @Reiddragon, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5644. Closing as a duplicate.
