### ISSUE TITLE
Games do not start

### ISSUE THREAD

**Issue by mtrp12** [ValveSoftware/Proton#1275]
I am using stable steam  on kubuntu 18.04 with proton version 3.7-3. When i press play button it shows running beside the game name for a bit then nothing happens. This happens for all the windows game I have installed, both white listed and non white listed. I have python 2.7 installed with python-minimal package. Inside steamapps/compatdata folder is created with steamapp id but nothing inside that folder. My steamlibrary is on a non default directory in another hdd and partition and contains space in it's path. File system type is ext4. I have tried both 3.7-3 and 3.7-5 beta version. I have restarted steam multiple times and even restarted pc.

**Comment by omicron-b** [comment]
You can try getting a log using [runtime-config-options](https://github.com/ValveSoftware/Proton#runtime-config-options), running the game as `PROTON_LOG=1 %command%`

Also you can try removing spaces from the path.

**Comment by kisak-valve** [comment]
Hello @mtrp12, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by mtrp12** [comment]
Following @m-svo's suggestion, i remounted the partition on /mnt to remove the spaces in path. Now games are working. I was using dolphin file manager to mount the partitions and it was using the label name which contains space, as mounted folder name.

When it does have space in the path, no proton log is generated using `PROTON_LOG=1 %command%`. It is generating after removing spaces. It would be nice to not worry about spaces.

@kisak-valve [here](https://gist.github.com/mtrp12/520e8954c1f7f83c44a3e982a66fe2a3) is the system info

Edit: I also had apostrophe in the label. It may also cause problems, probably.

**Comment by mtrp12** [comment]
I have already solved the problem as mentioned in previous comment. Feel free to close the issue.

**Comment by gbdlin** [comment]
I think you can (and should) close it by yourself. There should be "close" button just next to "Comment" below the comment box.
