### ISSUE TITLE
5 GB of RAM locked after playing DiRT 3 Complete Edition (321040)

### ISSUE THREAD

**Issue by FurretUber** [ValveSoftware/Proton#1284]
Hi

I am having some issues with DXVK related to [problems with Intel Mesa drivers](https://bugs.freedesktop.org/show_bug.cgi?id=107760) and, while I was making tests to see if I could reproduce the bug under certain conditions, I noticed another problem. About 5 GB of RAM are locked, being unable to be used by anything. This limits greatly what I can do with my computer as it has only 2,76 GB of memory it can use now.

As I'm not using DXVK git, I think it's better to report this here.

I observed that in one of the logs (dirt3_game_dxgi.log) there is:

```
info:    Memory Heap[0]: 
info:      Size: 4936 MiB
```

Which is around the value of inaccessible memory.

System information: https://gist.github.com/FurretUber/15fbf541c98ae6d096a02383f0285ce0
IMPORTANT: Mesa is patched, see the Mesa bug to see the content of the patches. It was impossible to play for long periods as the GPU would hang without the patches.

**Comment by ghost** [comment]
https://github.com/ValveSoftware/Proton/issues/773

**Comment by FurretUber** [comment]
I reported this in [DXVK GitHub](https://github.com/doitsujin/dxvk/issues/632) and the rc kernel has this fixed already. This issue can be closed

**Comment by kisak-valve** [comment]
Also landed in 4.18.14.
