### ISSUE TITLE
Age of Empires II: HD Edition - game works with issues

### ISSUE THREAD

**Issue by hogar1977** [ValveSoftware/Proton#1285]
Hi there,
the game works if 'AoK HD.exe' is renamed into 'Launcher.exe' and nostartup is added into launch options. 
**Issue 1:** ELO system is not behaving properly - the game 'thinks' that elo is 0:0 and reports it as out of bounds at selecting multiplayer and after every played multiplayer game it tries to add/subtract elo points to/from 0:0 values which still makes them out of bounds and elo finally gets reset to 1600 every time. The game is completely playable except for the ELO bug in multiplayer.
I play this game regularly via Crossover and the elo bug is not present there - I presume because the Steam client itself is part of the wine 'bottle' and it is the windows version of Steam client that is also emulated. Since elo system is tightly interwoven with the Steam client, I guess that's where the problem lies...

**Issue 2:** In-game chat windows - text is black on black background, so during typing of a message it's not possible to see it. This particular bug is wine related I guess... It exists in my Crossover installation and now it's also present in the Steam for Linux via Proton variant. Haven't found any solution for it until now.

Other than this, the game runs smoothly with no crashes... For me it actually performs better than on my Windows 10 machine (there I experience at least one crash per session of gaming and is somehow slower...).

**Comment by kisak-valve** [comment]
Hello @hogar1977, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/72#issuecomment-419201745.
