### ISSUE TITLE
Wine not responding dialog can't be used

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#1288]
Proton 3.7-5 beta

As title states, its possible to receive a "Wine not responding" dialog with force close or cancel buttons but be unable to reach it while in fullscreen. It can be seen during application switch such as alt+tab but the game window hides it.

This comes with a second side effect of the game window possibly being on top of other windows (which happened to me here) so if this happens then cannot close the game window. For me, trying to get to the Linux terminal or system monitor eventually resulted in the computer freezing and the only choice then is a hard reboot.

Wine not responding dialog should be displayed and on top of game window.

Specs: https://gist.github.com/byte1024/ae88bc29f9531b86c7b4d9187572dc27

**Comment by lieff** [comment]
It's more like gnome3 issue.

**Comment by ryanmusante** [comment]
System Information:

https://gist.github.com/ryanmusante/e0789f11ca3adfa4442297ac0099461f

On XFCE, the workaround I use is, **ctrl+alt+del**, it blanks my screen and enters screensaver lock, than I can enter my password to login. At that point the dialog box is front and center to force close.

**Comment by ghost** [comment]
Not sure how being unable to reach the dialog is a Gnome issue. It should be on top and reachable which should be a Wine issue unless Gnome isn't doing that correctly. I haven't seen any other problems like this =)

Also its fullscreen only it seems. Been using windowed mode and the dialog just showed up and was available to use.

**Comment by alasky17** [comment]
Which specific games were you seeing this with?

**Comment by roadapathy** [comment]
Well, now I know what distro you use.

First, you're using NVIDIA 396.45. That's somewhat old and the recommended version for your GPU is the 410.66

https://www.nvidia.com/Download/Find.aspx?lang=en-us

The other thing, I used Fedora before too and my experience is that it ran a little too slow for games. Maybe you could download the Kernel and compile it?

https://www.kernel.org/

I'm sorry that I don't know how to do this on Fedora. I use to, but too much in Fedora has changed but I do have a howto that could help:

https://compilethekernel.blogspot.com/

The other thing might be to update Wine. In Ubuntu, we can add a PPA and this will give us more options but I don't know how to do that in Fedora. If there are alternative repositories which allow the latest stable version of Wine, I would recommend adding that.

The other thing is that it really could be Gnome 3. It could also be the MESA libraries, or even the Fedora choice of Libraries itself. I used MX Linux for a while and loved it but too many things didn't work and a friend had a hypothesis that the libraries were just too old. I checked it against others on distrowatch.com and sure enough, he was right. Old libraries!

Hope this helps.

**Comment by ryanmusante** [comment]
This is all encompassing NVIDIA guide for FEDORA.

https://www.if-not-true-then-false.com/2015/fedora-nvidia-guide/
