### ISSUE TITLE
NieR:Automata crashes on startup: "No Graphic Memory"

### ISSUE THREAD

**Issue by meganekko** [ValveSoftware/Proton#129]
The game NieR:Automata crashes on startup:

> HW *garbled japanese text*
> ERROR: Graphic::Startup() FAILED.
> No Graphic Memory

Running on Debian sid, A10-7890K (8 GB VRAM) + RX 560 (4 GB VRAM). Mesa 18.1.5, DRM 3.25.0, 4.17.0-1-amd64. The issue seems to happen with and without the FAR mod. The game doesn't seem to drop any other debugging logs but I will try to provide more information as soon as I have it...

[System information](https://gist.github.com/meganekko/ad9c9cdac0afb638cc2a15b7d35f98db)
[glxinfo output](https://gist.github.com/meganekko/64ddfd2d0f5b159dd8017b2a1df8669f)

**Comment by doitsujin** [comment]
The game shows this error message if D3D11 initialization fails. Can you please attach `vulkaninfo` output in addition to the logs you already provided?

Also, please note that the FAR mod is not supported on Linux and is most likely not going to work, but is also not necessary to work around the fullscreen resolution issue that is only present on Windows.

**Comment by cjwijtmans** [comment]
i dont know anything about AMD but do you have AMD drivers that support latest vulkan.

**Comment by meganekko** [comment]
Well, this is embarrassing. While compiling vulkan-tools I found out I was missing the [mesa-vulkan-drivers](https://packages.debian.org/sid/mesa-vulkan-drivers) package. Installing this makes the game work. Closing this issue. Sorry! I'm not very familiar with Vulkan... 🤪

Thank you!
