### ISSUE TITLE
Quake Champions (611500) Connection error on latest update

### ISSUE THREAD

**Issue by SteveHeist** [ValveSoftware/Proton#1291]
# Compatibility Report
- Name of the game with compatibility issues: Quake Champions
- Steam AppID of the game: 611500

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 18.3.0-devel
- Kernel version: 4.15.0-33-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/SteveHeist/1f51e113d17ac6bb8224c70a926d6508
- Proton version: Tested in both Proton 3.7-5 Beta and 3.7-3

## I confirm:
- [Y] that I haven't found an existing compatibility report for this game.
- [Y] that I have checked whether there are updates for my system available.

[steam-611500.log](https://github.com/ValveSoftware/Proton/files/2358957/steam-611500.log)
## Symptoms
Game refuses to connect to servers on latest update - worked nearly flawlessly on previous update.

## Reproduction
It should be as simple as installing the game and trying to run it.

For expedience's sake, and trying to see if there's any way of fixing this quick, I combed through the above log and made a sort of "highlighted points" segment.

[Log Excerpt-611500 Sept. 6, 2018.txt](https://github.com/ValveSoftware/Proton/files/2358969/Log.Excerpt-611500.Sept.6.2018.txt)

There is an older "whitelist" request from the last update that might be worth noting. I have already made a comment there, but wanted an updated one to specifically mention the error revolving around the new update to the game.

https://github.com/ValveSoftware/Proton/issues/225

**Comment by kisak-valve** [comment]
Hello @SteveHeist, we're be using one issue report per unofficially supported game title, and you've already mentioned this where it matters at https://github.com/ValveSoftware/Proton/issues/225#issuecomment-419231634.

Closing in favor of the existing issue report.
