### ISSUE TITLE
Hellblade: Senua's Sacrifice Crashes When Starting New Game (414340)

### ISSUE THREAD

**Issue by Simmonz** [ValveSoftware/Proton#1292]
I tried running Hellblade: Senua's Sacrifice through Proton and it launches fine but when starting a new game it crashes seconds later before getting to any intro cinematic, level, etc. The Steam AppID of the game: 414340. I added `PROTON_LOG=1 %command%` to the game's launch options but no log was generated. I haven't found an existing compatibility report for this game and I have checked whether there are updates for my system available.

## System Information
- OS: Solus
- GPU: RX 580 8GB
- Driver/LLVM version: Mesa 18.1.6
- Kernel version: 4.18.5-90.current
- Proton version: 3.7-3

- https://gist.github.com/Simmonz/ee96fbeb3d32de20b2ebea979bf1746f

**Comment by kisak-valve** [comment]
Hello @Simmonz, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/943#issuecomment-419270763.

That said, you may have better luck with mesa built against llvm 7+.
