### ISSUE TITLE
[Whitelist] HeXen: Beyond Heretic (2360)

### ISSUE THREAD

**Issue by omicron-b** [ValveSoftware/Proton#1294]
# ~~Compatibility Report~~
- Name of the game with compatibility issues: HeXen: Beyond Heretic
- Steam AppID of the game: 2360

## System Information
- GPU: GTX 1060
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.18
- Link to full system information report as [Gist](https://gist.github.com/omicron-b/756962165db02f9e6c45c5829979fca7)
- Proton version: 3.7-5 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

~~Log is 96MB, so google drive link:~~

## Symptoms 
~~FPS is unstable, can drop to 6 or 11 FPS~~
~~PROTON_NO_ESYNC doesn`t help~~

## Reproduction
~~Install and run HeXen: Beyond Heretic, play through first level at least until opening the green door~~

**Comment by whizse** [comment]
Looks like another title that uses Dosbox.

From the log it looks like you're missing some SDL libraries, presumably 32-bit ones? Maybe Dosbox falls back to a slower output method?

**Comment by omicron-b** [comment]
@whizse you are right, there is something missing on my Arch
tested on Ubuntu 16.04 based distro, and changing this to a whitelist request

# Whitelist Request
- Name of the game to be whitelisted: HeXen: Beyond Heretic
- Steam AppID of the game: 2360

## System Information
- GPU: GTX 1060
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.15
- Link to full system information report as [Gist](https://gist.github.com/omicron-b/4d4de99c8ea1504fda49db3e0344cab3)
- Proton version: 3.7-6 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)       are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

**Comment by kisak-valve** [comment]
Found in the 2018-10-05 white list update.
