### ISSUE TITLE
Peggle Deluxe crashes / freezes when alt-tabbing out of it

### ISSUE THREAD

**Issue by founderio** [ValveSoftware/Proton#1302]
# Compatibility Report
- Name of the game with compatibility issues: Peggle Deluxe
- Steam AppID of the game: 3480

## System Information
- GPU: NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
- Driver/LLVM version: 4.6.0 NVIDIA 396.54
- Kernel version: 4.18.5
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/founderio/3295c24d5608d505fcced5205a32e1fc
- Proton version: 3.7-3, 3.7-5 beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-3480.log](https://github.com/ValveSoftware/Proton/files/2362230/steam-3480.log)

## Symptoms 

* The game screen will black out - sound keeps playing for a while, until it freezes
* Game has to be killed via terminal or similar, will not respond to close, alt-f4, etc
* Other than that, the game seems to be playable

## Reproduction

* Start the game
* Alt-Tab to a different window
* The game will minimize
* Switch back to the game
* See symptoms.

* This happens whether I'm using the steam runtime or native libraries.

## Additional Info
Related whitelist request: #331

**Comment by kisak-valve** [comment]
Hello @founderio, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/331#issuecomment-419541976.
