### ISSUE TITLE
Dungeons & Dragons: Chronicles of Mystara. Just a black screen. (229480)

### ISSUE THREAD

**Issue by MuchiMuchiPink** [ValveSoftware/Proton#1306]
# Compatibility Report
- Name of the game with compatibility issues: Dungeons & Dragons: Chronicles of Mystara
- Steam AppID of the game: https://steamcommunity.com/app/229480/

## System Information
- GPU: AMD Ryzen 3 2200G with Radeon Vega Graphics
- Driver/LLVM version: Mesa 1.8.7-1 / 6.0.1-4
- Kernel version: 4.18.5-arch1-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/MuchiMuchiPink/aaa267d9cd46980b738b4d1342e66161)
- Proton version: 3.7-5 Beta

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

## Symptoms 

Game starts and just produces a black screen. Has to be killed manually. 
## Reproduction
Just start the game.

**Comment by lavadrop** [comment]
Setting PROTON_USE_WINED3D=1 %command% as a launch option makes the game play normally.

**Comment by MuchiMuchiPink** [comment]
@lavadrop thanks a lot. This works for me.
