### ISSUE TITLE
[Whitelist] HeXen: Deathkings of the Dark Citadel (2370)

### ISSUE THREAD

**Issue by omicron-b** [ValveSoftware/Proton#1307]
# Whitelist Request
- Name of the game to be whitelisted: HeXen: Deathkings of the Dark Citadel
- Steam AppID of the game: 2370

## System Information
- GPU: GTX 1060
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.15
- Link to full system information report as [Gist](https://gist.github.com/omicron-b/4d4de99c8ea1504fda49db3e0344cab3)
- Proton version: 3.7-6 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)       are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

**Comment by kisak-valve** [comment]
Found in the 2018-10-05 white list update.
