### ISSUE TITLE
The Witcher 3 and R9 270X (292030)

### ISSUE THREAD

**Issue by MikaelBox** [ValveSoftware/Proton#1309]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher 3: Wild Hunt
- Steam AppID of the game: 292030

## System Information
- GPU: AMD R9 270X
- Driver/LLVM version: 4.5 Mesa 18.3.0-devel 
- Kernel version: 4.15.0-32-generic x86_64
- Link to full system information report as [Gist](https://gist.github.com/): [https://gist.github.com/MikaelBox/e11233c32548380b2a56c1a20ed70894](https://gist.github.com/MikaelBox/e11233c32548380b2a56c1a20ed70894)
- Proton version: 3.7.5-beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-292030.log](https://github.com/ValveSoftware/Proton/files/2363124/steam-292030.log)

## Symptoms 
Game isn't start with message: _GPU does not meet minimal requirements. Support for DirectX 11 is required._ 
But my video card has support for DirectX11.

**Comment by kisak-valve** [comment]
Hello @MikaelBox `err:vulkan:wine_vkCreateInstance Failed to load physical devices, res=-3` in your log indicates vulkan is not working on your system. Give #813 a read.

**Comment by MikaelBox** [comment]
Thanks a lot! All starts normally!

**Comment by aldonogueira** [comment]
I would like to add that installing mesa-vulkan-drivers and vulkan-utils fixed the directx 11 problem in my machine. It's an Ubuntu 18.04.1 with an AMD RX470 and padoka PPA drivers, proton 3.7-6. Maybe we could add these packages as a dependency somewhere...
