### ISSUE TITLE
pid !=, skipping destruction

### ISSUE THREAD

**Issue by SteveHeist** [ValveSoftware/Proton#131]
Been running several unofficial games, which have been feeding me a particular error:

`pid 12677 != 12676, skipping destruction (fork without exec?)`

Why might that be?

**Comment by kisak-valve** [comment]
Hello @SteveHeist, this is generally harmless and has to do with how Steam starts games.

Various other issue reports that mention it: https://github.com/ValveSoftware/steam-for-linux/search?p=2&q=skipping+destruction+%28fork+without+exec%3F%29&type=Issues&utf8=%E2%9C%93

Closing as this is not a Proton issue.

**Comment by ColorfulCode728** [comment]
Fixed this by installing lib32-vulkan-intel. Using Arch KDE on a T480

**Comment by M4nt0** [comment]
> Fixed this by installing lib32-vulkan-intel. Using Arch KDE on a T480

Don't know why this is off topic, it solved an error i tried to bugfix for literal hours/days, tysm, fml lol
