### ISSUE TITLE
Compatibility Report: Batman: Arkham Asylum Game of the Year Edition (appID: 35140)

### ISSUE THREAD

**Issue by furai** [ValveSoftware/Proton#1311]
# Compatibility Report
- Name of the game with compatibility issues: `Batman: Arkham Asylum Game of the Year Edition`
- Steam AppID of the game: `35140`

## System Information
- GPU: `NVIDIA Corporation GeForce GTX 970M/PCIe/SSE2`
- Driver/LLVM version: `NVIDIA 396.54`
- Kernel version: `4.18.6`
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/furai/c8ce8a1c183c5ed769f72aefba0513dd
- Proton version: `3.7-6 Beta`

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-35140.log](https://github.com/ValveSoftware/Proton/files/2363195/steam-35140.log)

## Symptoms 
Game won't even start.

## Reproduction
Install the game on Ubuntu 18.04 via Steam and try to launch it.

**Comment by whizse** [comment]
Tracked in #421

**Comment by furai** [comment]
Uhm, what? This is weird, I've searched for issues before posting this, made sure it's not there. I have no idea how I missed that report. Should I post there instead?

**Comment by kisak-valve** [comment]
Hello @furai, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/421#issuecomment-419643821.

**Comment by furai** [comment]
Thanks.
