### ISSUE TITLE
[Feature Request] Allow overriding the proton version per game

### ISSUE THREAD

**Issue by Sbte** [ValveSoftware/Proton#1312]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
In the Steam options we can choose "Use this tool instead of game-specific selections from Steam" to use an alternative version of Proton. It would be nice to be able to select this per game.

## Justification [optional] 
It seems like for every game Proton is downloaded separately (I have to download 300+ MB for every game every time Proton is updated). Since this is happening anyway, it would be nice to be able to select which version is downloaded per game.

Also, if all games work fine with the default selection, but you want to try one game with the latest version, updating all of them to the newer version might actually break games that worked fine with the default version.

## Risks [optional]
Actually reduces risks, because working games are not updated to an unstable version.

**Comment by jarrard** [comment]
An ability to ignore native clients would also be handy for the sake of installing a windows version of a game when their exists a native client. This sometimes is needed for games that get better performance via proton then via the native version of the game.

Examples at the moment I can think of right off top of my head:  Warthunder (neglecting vulkan alpha test), and Tomb Raider 2013.  Both of these games have pretty poor OpenGL native clients and are often much more playable when run via DXVK (or proton).

I couldn't find a topic about this so hence dumping the suggestion here. Its sort of similar to this feature request.

**Comment by vanyasem** [comment]
@jarrard ValveSoftware/steam-for-linux#5638. Your suggestion is unrelated, and is, in fact, a duplicate

**Comment by jarrard** [comment]
Ok cheers,.

**Comment by kisak-valve** [comment]
Hello @Sbte, this is a feature request for the Steam client rather than Proton itself, so I've gone ahead and transferred this feature request to https://github.com/ValveSoftware/steam-for-linux/issues/5740.
