### ISSUE TITLE
The Messenger (764790)

### ISSUE THREAD

**Issue by jonlap** [ValveSoftware/Proton#1329]
# Compatibility Report
- Name of the game with compatibility issues: The Messenger
- Steam AppID of the game: 764790

## System Information
- GPU: RX 480 and iGPU HD 4600
- Driver/LLVM version: Mesa 18.1.7 / LLVM 6.0.1
- Kernel version: 4.18.5
- Link to full system information report as [Gist](https://gist.github.com/): AMD system [here](https://gist.github.com/skry/4e2fd229ffb108d565dce6737952dd08) and Intel system [here](https://gist.github.com/skry/e9a3bb71522b395a9623d3f3f0e01476)
- Proton version: 3.7-3, 3.7-5 Beta, 3.7-6 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Logs:
[Proton log](https://gist.github.com/skry/b1701485957ee6f223da6f757b28b9e7)
[Console output](https://gist.github.com/skry/8ad5cdca4595c00b5179ac0b94eae208)

More reports:
[Thread at Steam](https://steamcommunity.com/app/764790/discussions/0/2727382174630882153/)
[SPCR page](https://spcr.netlify.com/app/764790)

## Symptoms 
Game does not work with controller. Controller is either not detected or input is not registered. Tested on both machines with wired Xbox 360 controller and DS4 via BT. It is worth noting that game does not have any means of configuring controllers, developer has promised this "feature" will come in future update.

Game crashes in background on game exit and sometimes has to be manually killed.

## Reproduction
Controller problem can be reproduced every time by starting the game and trying to use controller.
Crash on exit can be reproduced on every game by starting the game and exiting.
Freeze on exit cannot be reliably reproduced. Seems to not happen anymore with Proton 3.7-6 Beta.

**Comment by juef17** [comment]
I have a different issue I will briefly describe here.

I'm running Steam (Dec. 4th build) on Linux Lite 4.2 (kernel 4.15.0-43-generic), and mesa-vulkan-drivers:amd64 (18.0.5-0ubuntu0~18.04.1) for my Intel i5-3570K. When running the game through Steam with Proton 3.16-6 Beta and default configuration, the fonts don't appear correctly. When running the game through Wine, or with `PROTON_USE_WINED3D=1 %command%`, they appear perfectly. I have the corefonts package installed, and the font cache was updated.

Alt-Tabbing also seems to freeze the game.

**Comment by kisak-valve** [comment]
Hello @juef17, i5-3xxx is Ivybridge generation, which has incomplete vulkan support. It's unlikely anything using vulkan will work without issues on your system.

**Comment by juef17** [comment]
> incomplete vulkan support

Ah, I didn't know about that, sorry. Surprisingly, Wine'ing the game does make it run without issue (although with a sad framerate), and I'm guessing it uses Vulkan since it wouldn't run without installing the mesa drivers... but I guess it doesn't really matter. Thank you very much for your comment!

**Comment by jonlap** [comment]
I have retested this game by creating a new save and completing first area.
I can confirm that problems in my previous [compatibility report](https://github.com/ValveSoftware/Proton/issues/1329#issue-358311342) are now fixed:
- Xbox 360 controller works ootb
- Game exits correctly, does not crash

# Whitelist Request

## System Information
- GPU: RX 480
- Driver/LLVM version: Mesa 19.0.3
- Distro version: Arch
- Link to full system information report as [Gist](https://gist.github.com/): [info](https://gist.github.com/skry/8c9e87a99102e8a529d081235cff6826)
- Proton version: 4.2-3

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
This game was found in the 2019-07-31 whitelist update.

If you encounter an issue with this game, please search the open issues for 764790, and report any issues encountered with this game in separate issue reports, one issue per issue report.

**Comment by frioux** [comment]
This game doesn't work for me at all; it's just a black screen.  I tried both latest proton and proton 4.2 that was reported to work.

 *   GPU: GeForce GTX 970/PCIe/SSE2
 *  Driver/LLVM version: 4.6.0 NVIDIA 415.27
 * Distro version: SteamOS
 * Proton version: 4.2-9 and 4.11-7

**Comment by kisak-valve** [comment]
Hello @frioux, please open a new issue report.

**Comment by shoober420** [comment]
# Whitelist Request
- Name of the game to be whitelisted: The Messenger
- Steam AppID of the game: https://steamdb.info/app/764790/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.44
- Distro version: Arch
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia
- Proton version: 4.11-12

Works great out of the box!
