### ISSUE TITLE
Installing proton without replacing the release?

### ISSUE THREAD

**Issue by compholio** [ValveSoftware/Proton#133]
Is there a way to install proton without replacing the "Proton 3.7" release version?

I was hoping that it would just pick up directories in "~/.steam/steamapps/common" named "Proton X.Y", but that does not appear to be the case.  I would like to be able to do testing without interfering with the release version.

**Comment by alasky17** [comment]
Verifying the integrity of the game files on any game will restore the release version of Proton.  

Steam should pick up directories just named "Proton" if you delete the release version directory.  When I tested using rm -rf just now, I found that the "Proton 3.7" folder was immediately recreated after being deleted, but the contents were not propagated and Steam defaulted to using my non-release "Proton" directory until I verified the integrity of a game.

**Comment by aeikum** [comment]
(Closing old bugs.) This has been in for a while, see the "Install Proton locally" section of the README.
