### ISSUE TITLE
Nier Automata requires Python 2.7

### ISSUE THREAD

**Issue by Kedstar99** [ValveSoftware/Proton#1331]
# Compatibility Report
- Name of the game with compatibility issues: Nier Automata
- Steam AppID of the game: 524220

## System Information
- GPU: GTX 1060
- Driver/LLVM version: nvidia 396.54
- Kernel version:  4.15.0-33-generic
- Link to full system information report as [Gist](https://gist.github.com/Kedstar99/f2c286abf5dc41e55dea81da90f0df03):
- Proton version: 3.7.6 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Without Python 2.7 the game fails to start at all.

## Reproduction
On Ubuntu 18.04, it is possible to install steam without python 2.7 or python packages. For example, the multiverse version of Steam on Ubuntu 18.04 doesn't have python2.7 as a requirement and runs perfectly fine. For most games this setup seems ok, I can start AoE II, Crysis Maximum Warhead and multiple other games just fine with just python 3.

Nier automata seems to require python 2.7 and python2.7-minimal packages installed. As there are no py or pyc files in Nier Automata, I am guessing this is a requirement for proton/DVWK or something else.

In any case, it may be useful to either fix this, or perhaps issue a disclaimer as this is supposed to be a fully supported game and this requirement isn't listed for the game.

**Comment by eeyrjmr** [comment]
This is a requirement of proton. 
iirc the beta of proton is moving to py3. could you try that

**Comment by Kedstar99** [comment]
I am running the 3.7.6 beta of Proton, is there a newer version that needs to be compiled from source? 

If this was a general proton issue I am curious why AoEII, Skyrim and Crysis Warhead seems to run just fine.

The only issue I seem to have is with Nier Automata. There seems to be a python script somewhere that is explicitly calling for python2.7 because the game seems to function even if python isn't linked to python3.

If it is a requirement, should it not be listed along with the others here for Ubuntu users?
https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md

**Comment by Kedstar99** [comment]
Sorry by the above i mean python isn't symbolically linked to python2.7.

**Comment by Kedstar99** [comment]
This issue I can now confirm is resolved. With Proton 3.7-7 beta, this game launches fine without the python2.7-minimal package.

**Comment by kisak-valve** [comment]
Closing per the last comment.
