### ISSUE TITLE
The Evil Within 2

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/Proton#1332]
# Compatibility Report
- Name of the game with compatibility issues: The Evil Within 2
- Steam AppID of the game: 757570

## System Information
- GPU: AMD Vega 56
- Driver/LLVM version: 18.2.0-rc5/7.0.0
- Kernel version: 4.19.0-0.rc2.git2.1
- Link to full system information report as [Gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec):
- Proton version: 3.7-6 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-757570.log](https://github.com/ValveSoftware/Proton/files/2363677/steam-757570.log)

## Symptoms 
Low 1 FPS at splash screen.
In game itself ~20 FPS in 4K resolution on Vega 56

## Reproduction
Just launch the game.

**Comment by kisak-valve** [comment]
Hello @NTMan, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/755#issuecomment-419671004.
