### ISSUE TITLE
DOOM 2016 couldn't start

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/Proton#1333]
# Compatibility Report
- Name of the game with compatibility issues: DOOM
- Steam AppID of the game: 479030

## System Information
- GPU: AMD Vega 56
- Driver/LLVM version: 18.2.0-rc5/7.0.0
- Kernel version: 4.19.0-0.rc2.git2.1
- Link to full system information report as [Gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)
- Proton version: 3.7-6 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-479030.log](https://github.com/ValveSoftware/Proton/files/2363694/steam-479030.log)

## Symptoms 
The game didn't start.

## Reproduction
Just try launch the game.

**Comment by kisak-valve** [comment]
Hello @NTMan, this game demo is being tracked at #185. Closing as a duplicate.

Likely due to denuvo leftovers in the demo.
