### ISSUE TITLE
Remember Me

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/Proton#1334]
# Whitelist Request
- Name of the game to be whitelisted: Remember Me
- Steam AppID of the game: 228300

## System Information
- GPU: AMD Vega 56
- Driver/LLVM version: 18.2.0-rc5/7.0.0
- Kernel version: 4.19.0-0.rc2.git2.1
- Link to full system information report as [Gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)
- Proton version: 3.7-6 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [x] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

The game playable in 4K on high settings.

**Comment by kisak-valve** [comment]
Hello @NTMan, again, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/145#issuecomment-419672029.
