### ISSUE TITLE
Mirror's Edge™

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/Proton#1336]
# Whitelist Request
- Name of the game to be whitelisted: Mirror's Edge™
- Steam AppID of the game: 17410

## System Information
- GPU: AMD Vega 56
- Driver/LLVM version: 18.2.0-rc5/7.0.0
- Kernel version: 4.19.0-0.rc2.git2.1
- Link to full system information report as [Gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)
- Proton version: 3.7-6 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [x] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

May be insufficient FPS for comfort playing in some scenes on high settings and 4K

![screenshot from 2018-09-09 01-55-27](https://user-images.githubusercontent.com/200750/45258639-49f48380-b3d4-11e8-8f9b-7608d4930cb5.png)

**Comment by kisak-valve** [comment]
@NTMan, your repeated failure to check the existing issue reports has earned yourself a 24 hour timeout.

I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/355#issuecomment-419672848.
