### ISSUE TITLE
Subnautica - Mouse issues, no proper mouse focus

### ISSUE THREAD

**Issue by asdf1234-deleted** [ValveSoftware/Proton#1337]
# Compatibility Report
- Name of the game with compatibility issues: Subnautica
- Steam AppID of the game: 264710

## System Information
- GPU: Nvidia GTX 1080
- Driver/LLVM version:Nvidia proprietary 396.54
- Kernel version: 4.16.0-0.steamos2.1-amd64
- Link to full system information report: https://gist.github.com/mtdeguzis/efbf8e2fac5f42f24b460cc67db32f97
- Proton version: Tried both Proton 3.7 and Proton 3.7 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton log: https://gist.github.com/mtdeguzis/539d0ab9ebb89b13f144febc0d8ef43f

## Symptoms 

No mouse lock, left/right mouse button actions cause sporadic movement

## Reproduction

When the game starts, you can only get mouse control by clicking left/right mouse first. Things work well enough, but when you start the game, you cannot look around until you pause the menu first. After this, using left/right mouse cause sporadic movement instead of the expected action.

Game was started with:
```
PROTON_USE_WINE3D11=1 PROTON_LOG=1 %command%
```

**Comment by kisak-valve** [comment]
Hello @mtdeguzis, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/79#issuecomment-419674039.

**Comment by asdf1234-deleted** [comment]
Ok, i'll remember this for the future, hopefully things can get a bit more organized if that's the case or we should be titling the issues with a generic "GAME - APPID - Support issues" Or, create a milestone for each game to track multi-issues.
