### ISSUE TITLE
Pro Evolution Soccer 2018 (592580) - no lighting in game

### ISSUE THREAD

**Issue by carzacc** [ValveSoftware/Proton#1357]
# Compatibility Report
- Name of the game with compatibility issues: Pro Evolution Soccer 2018
- Steam AppID of the game: 592580

## System Information
- GPU: RX 460
- Driver/LLVM version: Mesa 18.0.5
- Kernel version: 4.17
- Link to full system information report as [Gist](https://gist.github.com/carzacc/2b21acdba69c64ee2c310364c83a9a63):
- Proton version: 3.7-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms

The menus work perfectly but it's unplayable because there is no lighting when a game is started, like in the following screenshots

![schermata da 2018-09-09 16-06-08](https://user-images.githubusercontent.com/3612573/45265406-a85c4900-b44a-11e8-86ba-50b6fe122581.png)
![schermata da 2018-09-09 16-06-20](https://user-images.githubusercontent.com/3612573/45265410-b1e5b100-b44a-11e8-9796-64d4a938cf21.png)
![schermata da 2018-09-09 16-06-24](https://user-images.githubusercontent.com/3612573/45265413-c2962700-b44a-11e8-869d-93599a46377c.png)
![schermata da 2018-09-09 16-06-28](https://user-images.githubusercontent.com/3612573/45265418-c7f37180-b44a-11e8-8eb1-65a443791404.png)
![schermata da 2018-09-09 16-06-51](https://user-images.githubusercontent.com/3612573/45265424-cfb31600-b44a-11e8-8bc2-5d15243ba849.png)

As you can see, there are light sources, but they don't actually light the scene.

**Comment by kisak-valve** [comment]
Hello @carzacc, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/361#issuecomment-419728515.
