### ISSUE TITLE
[QUESTION] Will this work on a i386 CPU?

### ISSUE THREAD

**Issue by saloniamatteo** [ValveSoftware/Proton#1358]
Basically I have Lubuntu x86 (32 bit) installed on my 11 year old laptop. Will the Steam client work, along with Proton?

**Comment by saloniamatteo** [comment]
Also been running Steam on WINE as Windows XP (instead of 7, otherwise nothing would load), I just want to play some games like Team Fortress Classic (which runs smoothly, even for this 11 year old laptop), and maybe TF2.

**Comment by ryanmusante** [comment]
I suppose Steam doesn't have requirements persay, it's the individual games themselves that limit you. I could be wrong though. Steam website about only lists operating systems.

https://store.steampowered.com/about/

To note, Windows XP mode will not function soon as support is being discontinued.

https://support.steampowered.com/kb_article.php?ref=1558-AFCM-4577

**Comment by saloniamatteo** [comment]
Supported Operating Systems
Windows 7, 8, 8.1, 10, or later.

Intel Mac, OS X version 10.11 (El Capitan), or later.

Ubuntu Linux (latest version).

Internet connection required (high speed recommended)

—————

Alright! Tomorrow will see how it goes!

**Comment by saloniamatteo** [comment]
Though only works with XP on Wine (for me) or else the store won’t load (just the library). Again, tomorrow will see how it goes!

**Comment by aeikum** [comment]
We haven't tried it, but I don't think it will work on a 32-bit-only system, no.

**Comment by saloniamatteo** [comment]
Currently Steam is updating

(installed it using
```apt
sudo apt install steam-launcher -y
```
will comment again if Proton works.)

**Comment by saloniamatteo** [comment]
Sadly, nothing works. Not even installing games. I guess I’ll stick to Wine.

**Comment by saloniamatteo** [comment]
Update: error on my side, everything works fine. I guess steam even works on a 11 year old laptop. Good job! Issue closed.

**Comment by mirh** [comment]
Cool (I would have swear I had read proton was x64 only)

Is valve planning to keep i486 supported for ~ever then?
It's already bad enough XP is going to be dropped, with no way to keep downloading games.
