### ISSUE TITLE
[Whitelist Request] World of Tanks Blitz (444200)

### ISSUE THREAD

**Issue by ihusky02** [ValveSoftware/Proton#1359]
# Whitelist Request
- Name of the game to be whitelisted:World of Tanks Blitz
- Steam AppID of the game: 444200

## System Information
- GPU: GTX860M
- Driver/LLVM version: 4.6.0 NVIDIA 390.48
- Kernel version: 4.15.0-33-generic
- Proton version:3.7-6 Beta

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [X] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [X] that no workarounds other than the mentioned ones are necessary.

## Issues
- [ ] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [X] Although I consider the gaming experience equal to Windows there are
      remaining issues:
When I try open in-game shop, messages section or tournament section game close without any error.

**Comment by kisak-valve** [comment]
Closing as blocked by #1293.
