### ISSUE TITLE
Whitelisted Game (Final Fantasy VI) Does not Launch

### ISSUE THREAD

**Issue by kemra102** [ValveSoftware/Proton#136]
Ubuntu 18.04.01  // NVIDIA 396.51

After getting the latest NVIDIA drivers and opting into the Steam Client Beta I downloaded & installed Final Fantasy VI without error. I tried to launch the game and I get the Play/Start Launcher pop-up, choosing either the pop-up disappears but the game never launches.

Launching from the CLI achieves exactly the same end result with no discernible error:

```sh
➜ kemra102@iacon  ~  steam steam://rungameid/382900  
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
```

I have tried restart the client as well as my machine but always with the same end result.

**Comment by thunder1410** [comment]
Is final fantasy VI installed on an NTFS formatted drive?
Is python 2.7 installed?

**Comment by kemra102** [comment]
No on ext4 & no python 2.7 is not installed as Ubuntu 18.04 has migrated to python3.

**Comment by thunder1410** [comment]
As noted already in #15, you do need to install python 2.7 to make proton work.

**Comment by kemra102** [comment]
Installing `python2.7` works. As per #15 ideally the python script should be written in a version agnostic way and the python2.7 shebang update. Thanks.
