### ISSUE TITLE
Dead Space 2 - Keyboard doesn't work ingame

### ISSUE THREAD

**Issue by P4NCH1** [ValveSoftware/Proton#1363]
# Compatibility Report
- Name of the game with compatibility issues: **Dead Space 2**
- Steam AppID of the game: **47780** ([steam-47780-log](https://gist.github.com/P4NCH1/91be77612cb130189fd915ef3fa8de30#file-steam-47780-log))

## System Information
- GPU: AMD Radeon R7 Kaveri 1GB
- Driver/LLVM version: Mesa 17.2.4/5.0.0
- Kernel version:  4.14.0-0.steamos.81-amd64
- [Full system information report](https://gist.github.com/P4NCH1/93502637c9e1b0fceda250dd5dfeb52b#file-steamos-system-information)
- Proton version: 3.7-3 and 3.7-6 Beta

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

## Symptoms
Keyboard doesn't work ingame or even in menu selection. Sometimes works in menu selection but when game starts and you have to move the character you can't. If you [Alt]+[Tab] out, the game freezes so this is not [a workarround like in MX Linux](https://www.youtube.com/watch?v=wOp4kvqBUIk)

## Reproduction
1. Start game
2. Keboard does not work

or

1. Start game
2. Keyboard works
3. Start a new game
4. Wait until video presentation ends
5. Keboard does not work

## NOTE:
The game have the same issue in another machine with MX Linux 17.1 64bits but keyboard gets detected again ingame  by removing the focus off the game and returning it ([Alt] + [Tab]).

**Comment by kisak-valve** [comment]
Hello @P4NCH1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/894#issuecomment-419732333.

**Comment by P4NCH1** [comment]
I saw it @kisak-valve but that's a whitelist request and nobody spoke about this problem. And is not only a problem in this game (on SteamOS) but in others too, issue that is not in other systems like MX Linux 17.1

I'd opened a one-game issue because of the requeirements to open one, but it's more a SteamOS+Proton problem than a game problem.
