### ISSUE TITLE
bully scholarship editions

### ISSUE THREAD

**Issue by palmer-eldritch** [ValveSoftware/Proton#1366]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
In the early proton release , bully scolarship edition worked wery fine. Hoever since a few days I've been getting a sound card error not compatible with dx9 and the game just stopes.
It used to work...

## Reproduction
Not sure how you could get to reproduce tit now, if if you can get it work i'd love to know how you did it. 

Steam app id is /12200/

Hope this could be of help , it just worked great before that (well you had to skip the annoyeing vieos but that's it..)

[steam-12200.log](https://github.com/ValveSoftware/Proton/files/2364577/steam-12200.log)
hope this can help
[steam-12200.log](https://github.com/ValveSoftware/Proton/files/2364578/steam-12200.log)

**Comment by kisak-valve** [comment]
Closing in favor of #517.
