### ISSUE TITLE
AMD/Intel Hybrid Graphics DX11 through DXVK issues

### ISSUE THREAD

**Issue by rednaxela600** [ValveSoftware/Proton#1367]
## System Information
- Distro: Linux Mint 19 Cinnamon 64-bit
- CPU: Intel i7-3630qm
- GPU: Radeon HD 8970m + Intel HD 4000 (Muxless switchable graphics setup)
- Driver/LLVM version: Mesa 18.3.0-devel - padoka PPA, LLVM 8.0.0
- Kernel version: 4.15.0-33-generic
- Link to full system information report as:[systeminfo.txt](https://github.com/ValveSoftware/Proton/files/2364592/systeminfo.txt)

## PROTON_LOGS:
Crysis 2 Maximum Edition: [steam-108800.log](https://github.com/ValveSoftware/Proton/files/2364560/steam-108800.log)
Skyrim Special Edition:[steam-489830.log](https://github.com/ValveSoftware/Proton/files/2364561/steam-489830.log)

## Symptoms
DXVK in general seems to have artifacts or simply fails to run a game entirely. 
-Crysis 2 Maximum Edition runs with artifacts such as cutscenes being entirely magenta/pink as well as text rendering being broken. 
-Skyrim Special edition hangs on a black screen before anything even starts. If I use wined3d11 instead, both games render without artifacts. I would make threads for each game, but I think the issue is less with the games and more with DXVK and my systems drivers. Although, I am unsure if this is the correct place to post the issue. 

Using vulkaninfo tells me: 
INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete 
Since DRI_PRIME does not change the results of vulkaninfo, I believe DXVK is having difficulty grabbing the 8970m over the Intel chip that it claims is incomplete. I honestly am not sure if this is a proton issue, DXVK issue, mesa issue, or something else. 

## Reproduction
As I only have one such computer, I have no way of telling if other similar configurations will have the same results. However, results are consistent, for me at least, that If I do not use flags to disable dxvk, the same issues will occur, and that using wined3d11 resolves these issues albeit with what I assume is lesser performance than DXVK.

**Comment by whizse** [comment]
Try setting DXVK_FILTER_DEVICE_NAME to the AMD card, or moving the Intel icd files out of the way.

**Comment by doitsujin** [comment]
Does `vulkaninfo` show your AMD GPU? If it doesn't, did you make sure to use the `amdgpu` kernel module rather than the `radeon` module?

Keep in mind that this card is GCN 1.0, which generally doesn't receive a lot of testing with RADV, so you might run into issues even when running RADV.

**Comment by rednaxela600** [comment]
Moving the intel icds from usr/share/vulkan/icd.d/ received the same results from skyrim special edition, and crysis 2 simply launched as dx9 and acted like dx11 did not exist.
I've also tried setting the environment variable for VK_ICD_FILENAME to the radeon icds, and the results did not change.

As for the DXVK_FILTER_DEVICE_NAME, sorry for my ignorance whizse, but how would I do that? DXVK_FILTER_DEVICE_NAME="AMD" %command%?
Since the 8970m card occasionally appears as a 7800 as well, how would I determine the necessary string? (I can't get to the old dxvk pages anymore, I only get a page not found from github)

In any case, since moving the Intel icd files didn't work, I'm beginning to wonder if my 8970m isn't registering for vulkan at all.

**Comment by whizse** [comment]
DXVK_HUD=1 should tell you which GPU is used, and if dxvk and Vulkan is used at all. 

I think it's the deviceName from vulkaninfo DXVK_FILTER_DEVICE_NAME is supposed to use.

**Comment by rednaxela600** [comment]
I believe that may confirm my previous fear. DXVK_HUD shows the intel IvyBridge Mobile as the device, even in spite of DRI_PRIME=1.
On top of that I only see the gpu id: 0 for the ivy bridge present in vulkaninfo. DRI_PRIME makes no difference to vulkaninfo, unlike glxinfo.

These text documents are the same.
Without DRI_PRIME=1
[IntelVKInfo.txt](https://github.com/ValveSoftware/Proton/files/2364708/IntelVKInfo.txt)
With DRI_PRIME=1
[AMDVKInfo.txt](https://github.com/ValveSoftware/Proton/files/2364707/AMDVKInfo.txt)

Do you believe this might be a bug in mesa? Or is my card, despite being gcn, not supported for vulkan on linux (yet)?

**Comment by kisak-valve** [comment]
Hello @rednaxela600, give #813 a read and see if it applies to you.

**Comment by rednaxela600** [comment]
That did the trick. Thank you very much! I could have sworn I saw the amdgpu module loaded before, but I must have been mistaken.

**Comment by kisak-valve** [comment]
Is there an actionable issue here besides the known incomplete vulkan driver for Ivybridge?

**Comment by rednaxela600** [comment]
I don't believe so anymore. The link you gave me resolved my issues with the 8970m not running vulkan, I just mistakenly believed that amdgpu was loaded when mint had defaulted to radeon. I must have missed that information before.
