### ISSUE TITLE
Worms: Armageddon (217200)

### ISSUE THREAD

**Issue by 4LT** [ValveSoftware/Proton#1372]
# Compatibility Report
- Name of the game with compatibility issues:  Worms: Armageddon
- Steam AppID of the game: 217200

## System Information
- GPU: Radeon HD 5850
- Driver/LLVM version: Mesa 18.1.7/6.0.1
- Kernel version: 4.18.5-arch1-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/4LT/adc1f3abdac277515d6320d978f67dbc
- Proton version: 3.7-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

_Please add `PROTON_LOG=1 %command%` to the game's launch options and drag
and drop the generated `$HOME/steam-$APPID.log` into this issue report_
Ran game with **PROTON_LOG=1**, but file of the name **steam-217200.log** does not exist in $HOME

## Symptoms 
1. Warning dialog appears about running W:A as administrator.
2. Dragging window moves viewport, but the visual contents of the window do not move; menu buttons however do move with the window, such that they do not align with the graphics.
3. Window goes black on other "Graphics" options. Cursor still visible.

## Reproduction
1.
* Launch the game.
2.
* Launch the game.
* Click "OK" on each dialog box that appears
* Move the window
* After the intro plays, move mouse around inside window.
3.
* Launch the game.
* Click "OK" on each dialog box that appears
* Go to Options > Advanced after the intro plays
* Select "Direct3d 9 (Shader)" from the menu next to the "Graphics" label
* Click "Exit", "OK"
* Restart the game

## Remarks
Game is playable (except when changing graphics settings as mentioned).

**Comment by grabmateusz** [comment]
## System Information
- GPU: GeForce GT 540M
- Driver/LLVM version: NVidia driver 390.48
- Kernel version: 4.15.0-33-generic
- [Link to full system information report](https://gist.github.com/grabmateusz/9df08b1e0ec5ab3cf81fa4b8431c3bca)
- Proton version: 3.7-6 Beta

## I confirm:
- [x] that I have checked whether there are updates for my system available.

[Game log for session with rendered UI](https://gist.github.com/grabmateusz/3987818c7bfc56a04c159ad32a794104)
[Game log for session with black screen](https://gist.github.com/grabmateusz/769300096a2dbe4361faf3e8c2b5a596)

## Symptoms
I confirm - all 3 issues reported by @4LT occur on my setup as well.

## Reproduction
Like in @4LT post

**Comment by 4LT** [comment]
To fix the black screen, you need to reset the options.  This can be done through regedit and running the script `Worms Armageddon/Tweaks/ResetRegistryOptions.reg`   Since running regedit through proton requires setting launch options to long, hard-to-remember path names and I can only have one set of launch options configured at a time, I created a custom launcher: https://gitlab.com/4LT/steam-game-launchers/blob/master/wa-launcher.tcl (Requires Tcl/Tk, which should be available on most *nix systems)  Set the W:A launch options to `/path/to/script %command%` to use.  If it's a one-time fix, and you don't want to download the script, you can set the launch options to `'/path/to/proton' waitforexitandrun '/path/to/regedit.exe' && echo %command% >/dev/null` to run regedit, then import the ResetRegistryOptions.reg file or find the W:A registry options and set the renderer to "1".

**Comment by jwatte** [comment]
I am seeing the same behavior -- this is a legitimate report.
Additionally, changing resolution in the game seems to not work as well.
I played around with Wine configuration settings and in-game registry entries, and couldn't get it any better than what the default comes up with.
The main problem in the default configuration is the coordinate system confusion, where the cursor is correctly at 0,0 in the top-left corner of the content area of the window, but the graphics are rendered "underneath the title bar" with a black strip at the bottom, i e, it seems to be using the "outer window coordinates" rather than the "client rect" coordinates.
I've tried turning off "let the window manager decorate the window" but it still comes up with a title bar, and it doesn't solve the problem.

**Comment by felisucoibi** [comment]
It hanged when accepting all the start popups.... using proton 4.2, i tried a few times, in the second popup telling you about admin mode...

**Comment by mrc0mmand** [comment]
After the first start the game asks to enable several Wine tweaks, and after confirming a few UAC related pop-ups, a game windows is shown. However, the only thing I saw was a black window with a sound. After a few minutes playing around it looks like the game is *anchored* to the (0,0) coords of the desktop (i.e. on the leftmost display in case of a multi-monitor setup), so you have to move the window to the *correct* position:

![wa](https://user-images.githubusercontent.com/679338/56474225-27047480-6477-11e9-8177-dc31b36a53f7.gif)

As mentioned above, changing resolution has no effect.

Specs:
Proton:4.2-3
Distro: Fedora release 29 (Twenty Nine)
Kernel: 4.20.14-200.fc29.x86_64
RAM: 12 GB
GPU Driver: 3.0 Mesa 18.3.4
GPU: Intel Haswell Mobile
CPU: Intel Core i7-4600U @ 2.10GHz

Proton log: 
[steam-217200.log](https://github.com/ValveSoftware/Proton/files/3101496/steam-217200.log)

**Comment by SuperPrower** [comment]
Issue above seems to be resolved with the game's 3.8 update, works like native now with no tweaking or issues.

**Comment by felisucoibi** [comment]
Yes , it works perfect now! thanks steam, and team17 another working game for linux and proton

**Comment by SuperPrower** [comment]
https://github.com/ValveSoftware/Proton/issues/1372#issuecomment-662701988
> team17 

This is slightly offtopic, but team17 has nothing to do with the fixes for this game. It's thanks to community, specifically Deadcode and CyberShadow, that this game is alive and up-to-date.

Otherwise, I've been playing the game for the last week on the Arch Linux with Intel HD 620 integrated graphics and have been having a great time, no issues whatsoever.

**Comment by felisucoibi** [comment]
> This is slightly offtopic, but team17 has nothing to do with the fixes for this game. It's thanks to community, specifically Deadcode and CyberShadow, that this game is alive and up-to-date.

GREAT! as long as i know team17 gave them the source code to fix the game... did team17 paid to devs for the latest release? who gets the money from steam and gog?

**Comment by 4LT** [comment]
Closing this, as the issue appears to be resolved.
