### ISSUE TITLE
VKD3D support?

### ISSUE THREAD

**Issue by oscarbg** [ValveSoftware/Proton#138]
Hi,
news sites point proton supports VKD3D for D3D12 support via Vulkan.. but searching on this site I found no  references to  VKD3D..
so even in alpha state, it's coming soon?
also VKD3D also yesterday gained Macos support via MoltenVK..
hope you support VKD3D on Macos once support comes..
thanks..

**Comment by Thinkaboutmin** [comment]
AFAIK, VKD3D is already released. It's probably on the wine code. [VKD3D Situation](https://source.winehq.org/git/vkd3d.git/)
So yeah, it actually does support it.

**Comment by Thinkaboutmin** [comment]
VKD3D is already on Wine. Is was [released](https://source.winehq.org/git/vkd3d.git/) 2 months ago if I'm not wrong.

**Comment by oscarbg** [comment]
yes but not enabled on Proton builds seems..

**Comment by parkerlreed** [comment]
https://github.com/ValveSoftware/wine/search?q=d3d12&unscoped_q=d3d12

Even has vulkan mentions at the bottom. I think it's enabled (Have nothing to test on my end)

**Comment by oscarbg** [comment]
I think no..
this only shows d3d12 portion of wine.. but Wine needs to be build with VKD3D supports which seems is not the case yet..

**Comment by SteveEbey73742** [comment]
as of wine 3.19, vkd3d is NOT working for DX12 to Vulkan.  I use Nvidia GTX 970 and it supports DX12 in Windows 10, but fails to get the feature information for Linux (Fedora).  I would hope that vkd3d would work soon, but so far, no luck.

**Comment by popsUlfr** [comment]
There's the issue that DXVK and vkd3d replace the same dll, so it's either or.
But work is on going to support vkd3d in dxvk see here : https://github.com/doitsujin/dxvk/issues/685

**Comment by oscarbg** [comment]
Why proton builds still don't ship with VKD3D enabled (d3d12.dll) as standard wine Ubuntu builds.. DXVK is irrelevant as disabling DXVK via user settings should be enough to not use DXVK and not interfere with original dxgi for VKD3D..
Tomb raider and Metro exodus now run under VKD3D!

**Comment by laichiaheng** [comment]
Is there any way to enable VKD3D in Proton now?

**Comment by TaiTair** [comment]
As of december 2018 DXVK has been modified to use wine's dxgi.dll. This means vkd3d can be fully supported in proton alongside dxvk. Where is the status on this?

Edit: There is a caveat, since we are not using dxvk's dxgi.dll we will not be able to change DXGI-related config options.

**Comment by viggy96** [comment]
I realise this is a very niche use case, but will Proton's vkd3d implementation allow for the ability for games to use multiple gpus? To clarify, I'm only referring to games that already support multi GPU on DX12, I'm NOT asking Proton devs to add multi-GPU support to games that don't already have it. I would be willing to help debug such a feature if need be.

**Comment by Patola** [comment]
Aaaaand, will VKD3D allow the use of raytracing on NVIDIA RTX series?

**Comment by kisak-valve** [comment]
Proton 5.0 has this as a submodule.
