### ISSUE TITLE
Most games won't survive to Alt-Tab when run in fullscreen mode

### ISSUE THREAD

**Issue by jaubin** [ValveSoftware/Proton#1380]
Hi,

Did not know where to put the issue, but most games will simply go back to black screen if run in fullscreen mode after switching windows with Alt-Tab. Among the affected games : 
- Doom
- Tropico 4
- ...

Test environment : 
- Debian Stretch 9
- NVidia 390.77
- KDE 5
- Locale : fr_FR

Workaround consists in having them to work in windowed mode.

**Comment by dasJ** [comment]
Can confirm with GTA V. Workaround is using a borderless window

**Comment by evandro777** [comment]
I can confirm this on Doom, sometimes a fast alt tab works, but when you delay about a minute, than a black screen and crash.

I think this is related to https://github.com/ValveSoftware/Proton/issues/583

**Comment by MasterCATZ** [comment]
noticed this with direct 3d only games

**Comment by luisalvarado** [comment]
Confirm with GTA 5, HITMAN, HITMAN 2, Mad Max, Shadow of Mordor, Shadow of War, Dying Light, Deus Ex, Shadow of the Tomb Raider and Rise of the Tomb Raider. There are more games but this are for sure the ones that I have where this occurs. The solution is to go back to the game, force it to user borders, then use ALT+TAB again, then back to the game and start clicking away at it, until "it works". Then presst ALT+ENTER to go back to fullscreen. On some cases like Deus Ex, Shadow of the Tomb Raider, GTA 5 and HITMAN 2, you might have a really bad luck and the game will crash or you will literally need to reboot the PC.

**Comment by jaubin** [comment]
The other solution consists in working simply with windowed mode. But the same actually happens with Windows.
    Le mercredi 26 juin 2019 à 22:37:55 UTC+2, Luis Alvarado <notifications@github.com> a écrit :  
 
 
Confirm with GTA 5, HITMAN, HITMAN 2, Mad Max, Shadow of Mordor, Shadow of War, Dying Light, Deus Ex, Shadow of the Tomb Raider and Rise of the Tomb Raider. There are more games but this are for sure the ones that I have where this occurs. The solution is to go back to the game, force it to user borders, then use ALT+TAB again, then back to the game and start clicking away at it, until "it works". Then presst ALT+ENTER to go back to fullscreen. On some cases like Deus Ex, Shadow of the Tomb Raider, GTA 5 and HITMAN 2, you might have a really bad luck and the game will crash or you will literally need to reboot the PC.

**Comment by luisalvarado** [comment]
Just created a video for Proton 4.2-9 For Hitman 2, Shadow of Tomb Raider and GTA5 You can watch it here https://www.youtube.com/watch?v=Ais0Pkgk4gs but the results are new:

1. On GTA5 if I press ALT+TAB and I come back to the game, it shows the game in Windows Mode. You would need to ALT+ENTER to show it in fullscreen again.

2. On HITMAN 2, if you ALT+TAB and come back in, works perfectly. It works perfectly either by going back again to the game pressing ALT+TAB or by clicking the HITMAN 2 icon.

3. On Shadow of the Tomb Raider, if you ALT+TAB and then come back to the game by pressing ALT+TAB again, it works perfect BUT, if you ALT+TAB out of the game and then come back by clicking on the game's icon, it shows "frozen", you would need to ALT+TAB out and then ALT+TAB in again.

This is just some feedback about the whole ALT+TAB issue, so the changes previously done on Proton 4.2-8 did fix HITMAN 2 and Shadow of the Tomb Raider, but GTA 5 and most likely others remain. Excellent work so far.

**Comment by fabiojb** [comment]
This problem still occurs with Doom 2016, but switching from linux-zen kernel 5.9.13 to linux lts 5.4.82 did solve the problem and switching back to the newer kernel made the problem come back. Different versions of proton didn't take effect on the problem.

@aeikum can this issue be re-opened?

**Comment by ghost** [comment]
For me it's kwin compositor settings. changing 'keep window thumbnails' to 'only for shown windows' or 'never' resolved it, the default setting is 'only for shown windows'. for those plasma user who had this issue it's not hurt to check this option.
and my system info:
```
$ uname -r
5.10.9-1-default
$ cat /etc/os-release                                                                                130 ↵
NAME="openSUSE Tumbleweed"
# VERSION="20210127"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210127"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210127"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo"
```

**Comment by se5a** [comment]
Why was this closed? 
it's still a *massive* issue, especially with unity games.

**Comment by xmawja** [comment]
i have the same issue, using dwm window manager when move to another tag its gone black screen

**Comment by TrainDoctor** [comment]
I still encounter this issue when playing Gunner Heat PC (a Unity game) on my EndeavourOS install.
```
[traindoctor@endeavour ~]$ uname -a
Linux endeavour 6.1.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 01 Feb 2023 17:07:39 +0000 x86_64 GNU/Linux
[traindoctor@endeavour ~]$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```
