### ISSUE TITLE
F.E.A.R. slowdown

### ISSUE THREAD

**Issue by dlove67** [ValveSoftware/Proton#1389]
# Compatibility Report
- Name of the game with compatibility issues: F.E.A.R.
- Steam AppID of the game: 21090

## System Information
- GPU: RX Vega
- Driver/LLVM version: Mesa 18.3.0-Devel LLVM8.0
- Kernel version: 4.18.0
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/dlove67/2420b2af8ff9049f6a9afe4d2db23b53
- Proton version: Proton 3.7-6

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

[steam-21090.log](https://github.com/ValveSoftware/Proton/files/2368329/steam-21090.log)

## Symptoms 
When playing the game and there are particle effects or bodies ragdoll, the FPS will drop to less than 1 fps at times. I found this is particularly bad at a location in the level "Bad Water".

## Reproduction
I have created a save game at and uploaded to google drive here: https://drive.google.com/open?id=1tO5e6CvkyUnQ0i1uowVCRxazDvAoU3PM (the save file is "Bad Water" at time 1:41:54)

You can also see the issue when doing the benchmark, to a much more minor degree, when the soldiers are shooting at each other, framerate drops on my system from around 200+ fps to about 20-30fps.

**Comment by kisak-valve** [comment]
Hello @dlove67, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/481#issuecomment-420070300.
