### ISSUE TITLE
Shadowverse crashes at launch (453480)

### ISSUE THREAD

**Issue by pinkfloydsito** [ValveSoftware/Proton#1398]
# Compatibility Report
- Name of the game with compatibility issues: Shadowverse
- Steam AppID of the game:453480

## System Information
- GPU: NVIDIA Corporation GM108M [GeForce 940M] 
- Driver/LLVM version: 
- Kernel version: 4.18.6-arch1-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/PinkFLoyd92/004e5329f1ac8d60f352bcddc244c4fd
- Proton version: 3.7.6 - Beta

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

> ERROR LOG FROM SHADOWVERSE

[error.log](https://github.com/ValveSoftware/Proton/files/2371514/error.log)

> ERROR LOG FROM PROTON
[steam-453480.log](https://github.com/ValveSoftware/Proton/files/2371525/steam-453480.log)

## Symptoms 
**Using bumblebee**.  The game is not launching, the command used was: `PROTON_LOG=1 primusrun %command%` I also tried to use optirun and my Intel card but it just does not launch.
![image](https://user-images.githubusercontent.com/8844096/45371559-87156d00-b5b0-11e8-8870-f6283fb280b7.png)

**Comment by krepflap** [comment]
It works if you use following launch options:

`PROTON_NO_D3D11=1 %command%`

**Comment by pinkfloydsito** [comment]
that fixes it! Thanks
