### ISSUE TITLE
SteamOS - no settings option to toggle "try with all games"

### ISSUE THREAD

**Issue by asdf1234-deleted** [ValveSoftware/Proton#14]
Tested a few games from the list, and many many thanks! I saw you could enable the option to allow Proton to work with any game, even if not on the approved list (say you wanted to test one out). Is this possible to toggle on SteamOS?

![image](https://user-images.githubusercontent.com/27829577/44437355-ea9b1480-a587-11e8-954e-7857e1f7a1db.png)

```
Q: Can I try a game with Proton even if it's not marked as compatible?

Yes; head to the Steam Play options of your Steam Client and you'll be able to enable it for all games.
```

https://steamcommunity.com/games/221410/announcements/detail/1696055855739350561

**Comment by asdf1234-deleted** [comment]
As a work around:

1. Power > Exit to Desktop (enable in settings)
2. Open terminal
3. sudo -i -u steam
4. Kill and start steam again
```
pkill steam
steam
```
5. Enable the option in settings menu, per the above.
6. restart system or click "return to steam" from the desktop.

**Comment by kisak-valve** [comment]
Hello @mtdeguzis, since this is an issue with steam's interface and not Proton itself, let's track this issue in the Steam-for-Linux issue tracker at https://github.com/ValveSoftware/steam-for-linux/issues/5631.
