### ISSUE TITLE
Feture Request: Better drive defaults in prefixes, and several other links.

### ISSUE THREAD

**Issue by Ruedii** [ValveSoftware/Proton#1407]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
A quick link to place the game's directory on the D: virtual drivelink under "D:\[game directory]"  A unified user directory should be placed here as well, linking to $HOME/.share/local/SteamPlayUserFiles/[steamlogin] (or whatever you want to call it.)
A second Quicklink under H: to the user's home directory.

## Justification [optional] 
This would make accessing the game directory and home directory when doing manual wine commands much easier.  This is rather proton specific.

## Risks [optional]
Moving the user directory means making a transition copy directory.  It also means changing the instructions to purge that directory, and notifying everyone of the new directory structure.   

Having a shared user directory for all SteamPlay games may introduce interactions between games, just like on Windows.  This can also be a benefit.

Using a separate user directory changes presumes players want to use separate settings/game-play paths for instances of different steam users logging in under the same system username.  This may not be a safe assumption.

Making it easier to access to files from the Wine execution environment might allow some users to do stupid stuff.  Add a documentation on how to purge the two sets of data directories in order to fix it.

**Comment by kisak-valve** [comment]
Hello @Ruedii, this is already being discussed at #231, so I've transferred this to https://github.com/ValveSoftware/Proton/issues/231#issuecomment-420478915. Closing in favor of the existing issue report.
