### ISSUE TITLE
Total War: Warhammer II White Launcher and no sound (594570)

### ISSUE THREAD

**Issue by weidtn** [ValveSoftware/Proton#1414]
# Compatibility Report
- Name of the game with compatibility issues: Total War: Warhammer II
- Steam AppID of the game: 594570

## System Information
- GPU: Ryzen 1600x
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.14.68-1-MANJARO
- Proton version: 3.7-3
- System info: https://gist.github.com/weidtn/a421f7057d96369315300a3b63f5847a
## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 
The launcher just is a white window. After guessing where the "PLAY" button is, the game starts without any sound.

## Reproduction

Just try to play, play button is on the right side 1/4 down.

**Comment by liberodark** [comment]
But is coming on linux for what you try this game ?

**Comment by weidtn** [comment]
Multiplayer with windows players

**Comment by kisak-valve** [comment]
This game now has a [native linux version](https://www.feralinteractive.com/en/news/918/).
