### ISSUE TITLE
Problems to launch and install game  - Viscera Cleanup (246900)

### ISSUE THREAD

**Issue by geekaia** [ValveSoftware/Proton#1415]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: gtx 660
- Driver/LLVM version: 390.87 
- Kernel version: 4.15.0-34-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 
[steam-246900.log](https://github.com/ValveSoftware/Proton/files/2375084/steam-246900.log)

The download never finish
![image](https://user-images.githubusercontent.com/5241165/45424791-f1d8ae00-b66d-11e8-9493-5e5c410d0be5.png)

**Comment by geekaia** [comment]
Proton version 3.7-6 beta

**Comment by geekaia** [comment]
Ubuntu 18.04 64 bits

**Comment by geekaia** [comment]
[steam-246900.log](https://github.com/ValveSoftware/Proton/files/2375224/steam-246900.log)
I have installed the offline version of .net 4, but the game still doesn't start 

env WINEPREFIX="/media/DADOS/geekaia/.steam/steamapps/common/Proton 3.7 Beta/dist/share/default_pfx" WINEPATH="/media/DADOS/geekaia/.steam/steamapps/common/Proton 3.7 Beta/dist/bin/wine64" wine dotNetFx40_Full_x86_x64.exe

**Comment by kisak-valve** [comment]
Hello @geekaia, this issue is already being tracked at #672. Closing as a duplicate.
