### ISSUE TITLE
No Compatibility Message after hitting Play (Option)

### ISSUE THREAD

**Issue by CentralPython** [ValveSoftware/Proton#1428]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description

Would it be possible for the devs to create an option in Steam Play so that the compatibility warning message after hitting play does NOT occur so that it'll be normal with no popups and then it just plays after no message appearing obviously we know its in compatibility mode after fiddling with the settings options. Could this be added if doable?

**Comment by tingvarsson** [comment]
Maybe my setup is weird, but is it not only the first time a game is started it gives the compatibility message? And I am assuming it is only for the non official titles?

**Comment by CentralPython** [comment]
> Maybe my setup is weird, but is it not only the first time a game is started it gives the compatibility message? And I am assuming it is only for the non official titles?

If it doesn't appear to Official titles then the popup message may appear only to unofficial titles which is what I had enabled at that time though with the new clean install of Ubuntu I would prefer to wait for others to test and report the games and for me just waiting till the feature requests which has been reported to be implemented such as the full screen fixes etc for classical games like Pharoah & Cleopatra, 7 Wonders 2, 4 Elements which I had tested but experienced problems with the full screen bit.

**Comment by gbdlin** [comment]
This message shows up only on not whitelisted games and only at first launch. I don't think that it is something that should be removed.

Also, that is not request for proton but for steam client itself. Go to steam community forums and report it there if you think it still should be changed.
