### ISSUE TITLE
Full screen on classic games only show in square (rectangle) box please add fix to stretch it and scale.

### ISSUE THREAD

**Issue by CentralPython** [ValveSoftware/Proton#1429]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Certain games which are classics like 7 Wonders, Pharoah + Cleopatra and Robin hood are not fully in Full Screen mode even though Full Screen is ticked and active could fixes be done so that old games are automatically scaled to full screen without graphical issues or text issues and that it'll be actuall full screen and not just showing a rectangle window mode in full screen mode.

**Comment by kisak-valve** [comment]
Hello @FederalRecall, this feature request is already being tracked at #1249. Closing as a duplicate.
