### ISSUE TITLE
Fallout 1 & 2 : Crash at startup because of missing native .net framework libs

### ISSUE THREAD

**Issue by mbouchar** [ValveSoftware/Proton#144]
When trying to start Fallout 1 or 2 result in the following error :
```
wine: Call from 0x7b43c45c to unimplemented function mscoree.dll.CorIsLatestSvc, aborting
wine: Unimplemented function mscoree.dll.CorIsLatestSvc called at address 0x760023:0x7b43c45c (thread 0015), starting debugger...
```

The game doesn't even load (no window). The error could be resolved by installing the official .Net Framework using winetricks in Wine.

**Comment by kisak-valve** [comment]
Hello @mbouchar, this unimplemented function is already being tracked at #18. Closing in favor of the existing issue report.
