### ISSUE TITLE
[FR]Anticheat?

### ISSUE THREAD

**Issue by yurikoles** [ValveSoftware/Proton#1446]
There is possibility to use modifiy translation layer fo cheating purposes, e.g. hiding walls. This raises question about integration of VAC or some DRM for libs that proton is using.

**Comment by kisak-valve** [comment]
Hello @yurikoles, on any open system this is a possibility that has to be handled carefully for it to be generally accepted by all parties involved.

In the specific context of this issue report by itself, I'm interpreting the intent of your issue report as an effort to spread drama related to a non-steam game and I'm not going to allow this as out-of-scope for the Proton issue tracker. (This should not be read as a general precedent.)

```
Q: Are there any games that will never work with Proton?

It's likely that some games using complex DRM or anti-cheat systems will be difficult, or even impossible to support.
```
- From https://steamcommunity.com/games/221410/announcements/detail/1696055855739350561
