### ISSUE TITLE
Path of Exile - crashes after ~15m gameplay

### ISSUE THREAD

**Issue by zaggynl** [ValveSoftware/Proton#1447]
# Compatibility Report
- Name of the game with compatibility issues: Path of Exile
- Steam AppID of the game:238960

## System Information
- GPU: RX 56
- Driver/LLVM version:   AMDGPU/8.0 git from unstable padoka as of 2018-09-14: https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/mesa
- Kernel version: 4.18.7-041807-lowlatency
- Link to full system information report as [Gist](https://gist.github.com/): 
sysinfo command output:
https://gist.githubusercontent.com/zaggynl/382e129b0d7b48482923f62c57ee5651/raw/67f90e61c38a5a17924347859caa18eab188dc99/sysinfo_zaggynl
steam sysinfo output: 
https://gist.githubusercontent.com/zaggynl/d5443757827a2649013142836ca6c411/raw/599be7e2d3744347aaa06b3147ce73145e05fa3c/steam_sysinfo_zaggynl
- Proton version: 3.7-6 Beta

## I confirm:
- [V ] that I haven't found an existing compatibility report for this game.
- [V] that I have checked whether there are updates for my system available.

Steam debug log: https://gist.githubusercontent.com/zaggynl/6d55e984035244ec54274db14a2f77ea/raw/f2ab23db3dace4c6032ffb6aa6389a03ad364240/poe_log_zaggynl

## Symptoms 
Game crashes to desktop after about 15m of playtime
PoE settings: 
http://i.imgur.com/8C2p65Y.png
http://i.imgur.com/9TlwF2U.png

**Comment by kisak-valve** [comment]
Hello @zaggynl, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/58#issuecomment-421402376.
