### ISSUE TITLE
Update to 3.7.6 regular deleted every SteamPlay game

### ISSUE THREAD

**Issue by nilleairbar** [ValveSoftware/Proton#1448]
Every game that I had downloaded via SteamPlay got deleted. Folder structure of the games are still intact but the Steam update deleted all other files of the games. Back to Windows I guess. No way in hell will I download hundreds of GB again just to get those removed again with the next update.

**Comment by kisak-valve** [comment]
Hello @nilleairbar, game updates are handled by the Steam client instead of Proton itself, so I've transferred this issue to https://github.com/ValveSoftware/steam-for-linux/issues/5761.
