### ISSUE TITLE
[Whitelist] Zoombinis (397430)

### ISSUE THREAD

**Issue by CentralPython** [ValveSoftware/Proton#1449]
# Whitelist Request
- Name of the game to be whitelisted: Zoombinis
- Steam AppID of the game: 397430

## System Information
- GPU: GTX 750 Ti
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.15
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/FederalRecall/cd98b62cde3ae0ebdb11fbc8909a1559
- Proton version: 3.7

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [ ] that no workarounds other than the mentioned ones are necessary.

## Issues
- [X] I haven't experienced any issues.
- [X] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

**Comment by tatsujb** [comment]
zoombinis <3 I'd forgotten about them!

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.
