### ISSUE TITLE
[Whitelist] The Secret of Monkey Island: Special Edition (32360)

### ISSUE THREAD

**Issue by CentralPython** [ValveSoftware/Proton#1450]
# Whitelist Request
- Name of the game to be whitelisted: The Secret of Monkey Island: Special Edition
- Steam AppID of the game: 32360

## System Information
- GPU: GTX 750 Ti
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.15
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/FederalRecall/cd98b62cde3ae0ebdb11fbc8909a1559
- Proton version: 3.7

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [ ] that no workarounds other than the mentioned ones are necessary.

## Issues
- [X] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

**Comment by kisak-valve** [comment]
Hello @FederalRecall, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/939#issuecomment-421434985.
