### ISSUE TITLE
The Secret of Monkey Island: Special Edition - broken graphics

### ISSUE THREAD

**Issue by dv8472** [ValveSoftware/Proton#1451]
# Compatibility Report
- Name of the game with compatibility issues: The Secret of Monkey Island: Special Edition
- Steam AppID of the game: 32360
- This is actually first Windows game I've tried via Steam's Proton. Other games or programs (steam, gog, wine, scummvm, dosbox) work fine.

## System Information
- GPU: GeForce GTX 750
- Driver/LLVM version: 396.54
- Kernel version: 4.14.68-1-lts
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/dv8472/cf95aa321ddbe2e63b63e6d1c3009e7e
- Proton version: 3.7-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Graphics gets broken during the gameplay.
Happens very randomly after some time, several times per hour.
Game gets frozen after all, have to press Alt+F4 and wait for a dialog to kill the process.

![image](https://user-images.githubusercontent.com/22549066/45569140-ea2c2b80-b85e-11e8-94e4-55f5d0340af1.png)
![image](https://user-images.githubusercontent.com/22549066/45569145-ebf5ef00-b85e-11e8-8f34-6a7f0d584b6e.png)
![image](https://user-images.githubusercontent.com/22549066/45569147-ed271c00-b85e-11e8-9837-e150832943df.png)
![image](https://user-images.githubusercontent.com/22549066/45569151-ef897600-b85e-11e8-91e0-de4e3d20c6ae.png)
![image](https://user-images.githubusercontent.com/22549066/45569152-f1533980-b85e-11e8-84f5-fb6f726d1ba2.png)

**Comment by kisak-valve** [comment]
Hello @dv8472, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/939#issuecomment-421451709.

**Comment by dv8472** [comment]
> Hello @dv8472, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#939 (comment)](https://github.com/ValveSoftware/Proton/issues/939#issuecomment-421451709).

ok
