### ISSUE TITLE
[ISSUE] No Man`s Sky no sound ( 275850) 

### ISSUE THREAD

**Issue by UnknownRedStar** [ValveSoftware/Proton#1459]
# Compatibility Report
- Name of the game with compatibility issues: No Man`s Sky 
- Steam AppID of the game: 275850

## System Information
- GPU: GTX 1050ti
- Driver/LLVM version: Nvidia 396.54
- Kernel version: 4.15
- Link to full system information report as [Gist](https://gist.github.com/):

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 5 2600 Six-Core Processor            
    CPU Family:  0x17
    CPU Model:  0x8
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3400 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 18.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-34-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2018-06-14

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.54
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1c82
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.08" x 11.30" (23.03" diag)
                                            51.0cm x 28.7cm (58.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Nvidia GPU 80 HDMI/DP

Memory:
    RAM:  16052 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  194192 Mb
    Largest Free Hard Disk Block:  107787 Mb
    VR Headset: None detected

Recent Failure Reports:

- Proton version: 3.7-6

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

[steam-275850.log](https://github.com/ValveSoftware/Proton/files/2385562/steam-275850.log)

## Symptoms 
The sound was working initially for about a week and for some reason yesterday the sound completely stopped working everything else still runs fine and performance is great but the sound simply does not work any longer 

## Reproduction
for me its easily done by launching the game

**Comment by kisak-valve** [comment]
Hello @Rainakins, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-421572939.
