### ISSUE TITLE
[BUG] Missing achievements - Age of Empires II: HD Edition

### ISSUE THREAD

**Issue by methos789** [ValveSoftware/Proton#146]
Ubuntu 16.04.5 (64-bits) - NVIDIA 396.51 (NVIDIA GeForce GTX 750)

The game works fine once you rename AoK HD.exe to Launcher.exe

BUT I noticed that I lost all my won achievements (my savegames and play hours are still there)
Previously I was playing through Wine and didn't have any problem

**Comment by kisak-valve** [comment]
Hello @methos789, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5643. Closing as a duplicate.
