### ISSUE TITLE
Games can not connect to servers under Proton ( Connection problem )

### ISSUE THREAD

**Issue by MuhammedKpln** [ValveSoftware/Proton#1462]
I can not connect game servers because it can reach the server (some how internet problem cant access to internet.) But on wine without proton connection works both for http and https.

# System Information
GPU: GTX 1050Ti
Driver/LLVM version: NVIDIA 396.54.5
Kernel version: 4.18.7-arch1-1-ARCH
Proton version: 3.7-6 Beta

System information from [Steam](https://gist.github.com/MuhammedKpln/b219c1b2fb76b5219c1908bd902918e4)

Proton [log](https://gist.github.com/MuhammedKpln/c658647e7c05aa3fa19e3b4a1c2817c7)

**Comment by jonlap** [comment]
If you are using steam-native, try again with steam-runtime and see if it works.

**Comment by MuhammedKpln** [comment]
> If you are using steam-native, try again with steam-runtime and see if it works.

I'm already running steam with runtime.

**Comment by jonlap** [comment]
I tried Darwin Project (544920), which I assume posted Proton log is from, and can confirm this issue. My system information [here](https://gist.github.com/skry/1c6460bd766638632fcb7e3d63a446e7).

**Comment by MuhammedKpln** [comment]
> posted

Same happens with Quake Champions, which gives "Connection error" 103 as well.

[Quake champions log](https://gist.github.com/MuhammedKpln/65fda0e7b3e0e8a0e62fefcc0233157f)

**Comment by kisak-valve** [comment]
Hello @MuhammedKpln, @skry, there's no point in having another general network issue report. We already have one at #162 as well as the connectivity issues mentioned on compatibility reports for individual games. Closing in favor of the existing issue report (and individual game reports).
