### ISSUE TITLE
Home Design 3D (420000)

### ISSUE THREAD

**Issue by hasanenalbana** [ValveSoftware/Proton#1463]
# Compatibility Report
- Name of the game with compatibility issues: Home Design 3D
- Steam AppID of the game: 420000

## System Information
- GPU: GTX 1050 
- Driver/LLVM version: nvidia 390
- Kernel version: 4.15.0.-23-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/hasanenalbana/f98f94bcd4cbb912ec5df0ffb6064557

- Proton version: 3.7 Beta

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

[steam-420000.log](https://github.com/ValveSoftware/Proton/files/2385694/steam-420000.log)

## Symptoms 
The app won't start at all

## Reproduction
Simply running the game from steam menu.

**Comment by zzhiyi** [comment]
Works fine on proton 4.2-1. Please retest.

**Comment by hasanenalbana** [comment]
Confirmed working on proto. 4.2-1.
