### ISSUE TITLE
[Whitelist] Glass Masquerade (511470)

### ISSUE THREAD

**Issue by jonlap** [ValveSoftware/Proton#1467]
# Whitelist Request
- Name of the game to be whitelisted: Glass Masquerade
- Steam AppID of the game: 511470

## System Information
- GPU: RX480
- Driver/LLVM version: Mesa 18.2.0/6.0.1
- Kernel version: 4.18.7
- Link to full system information report as [Gist](https://gist.github.com/): [System info](https://gist.github.com/skry/1c6460bd766638632fcb7e3d63a446e7)
- Proton version: 3.7-6 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

## More
Played for about 2 hours total, several sessions. Everything works as expected, performance is great and no workarounds are needed. I have also tested this with same hardware but Mesa 18.1.7 with same results.

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.
