### ISSUE TITLE
Cannot find games

### ISSUE THREAD

**Issue by formbi-kupiec** [ValveSoftware/Proton#1475]
When I try to launch a game, I get something like this:
```
wine: cannot find '/d/Deus Ex Human Revolution Director's Cut/DXHRDC.exe'
pid 16450 != 16449, skipping destruction (fork without exec?)
Game removed: AppID 238010 "", ProcID 16445
```
(not only for Deus Ex HR) and the debug script doesn't appear even though i set `PROTON_DUMP_DEBUG_COMMANDS=1`

**Comment by ghost** [comment]
You did use it with the %command% like below? 
PROTON_DUMP_DEBUG_COMMANDS=1 %command%

Apparently, though at least one person has gotten it to work with Steam Play: https://steamcommunity.com/app/238010/discussions/0/1736588252397412524/

So it might be fixable on your end.

Wine should be able to find the game exe so... the /d/ is interesting. Doesn't seem like the path is correct, but its either part of the issue or not (and is correct =)

The only other similar thing I could find is here: https://www.reddit.com/r/linux_gaming/comments/9ff1vt/cant_launch_any_steam_play_games_error_log/

which is highly similar and also people suggest workaround/fixes for it:

```
wine: cannot find '/media/soulburner/sea_shit/games/_linuxSteam/steamapps/common/PAYDAY The Heist/payday_win32_release.exe'
7288.418:0008:0009:trace:module:LdrShutdownProcess ()
pid 4417 != 4416, skipping destruction (fork without exec?)
```

**Comment by formbi-kupiec** [comment]
OK, I found the solution - I had to remove the old prefix. But it's good that you told me about the «%command%», I thought that it's not necessary. About /d - why would I make my paths long? :p
