### ISSUE TITLE
Frostpunk (323190) fails to start

### ISSUE THREAD

**Issue by mcodax** [ValveSoftware/Proton#1477]
# Compatibility Report
- Name of the game with compatibility issues: Frostpunk
- Steam AppID of the game: 323190

## System Information
- GPU: GeForce GTX 1080 Ti
- Driver/LLVM version: 4.6.0 NVIDIA 396.54
- Kernel version: 4.18.7-arch1-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/mcodax/d66b3c337e1ce764c9f87d740f64ed9a
- Proton version: 3.7-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-323190.log](https://github.com/ValveSoftware/Proton/files/2386231/steam-323190.log)
## Symptoms 

Frostpunk doesn't start after I press 'Play'. It tries to load for a few seconds but then I see the option to press 'Play' again.

## Reproduction

Start steam (native/runtime through a desktop shortcut or library item).
Start Frostpunk.

**Comment by kisak-valve** [comment]
Hello @mcodax, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/412#issuecomment-421671114.
