### ISSUE TITLE
Psychonauts (3830) - Whitelist Request

### ISSUE THREAD

**Issue by EmmanuelMess** [ValveSoftware/Proton#1478]
# Whitelist Request
- Name of the game to be whitelisted: Psyconauts
- Steam AppID of the game: 3830

## System Information
- GPU:  Gráficos HD Intel® 530 
- Driver/LLVM version: 3.0 Mesa 18.0.5
- Kernel version:  4.15.0-34-generic
- Link to full system information report as [Gist](https://gist.github.com/): [System info](https://gist.github.com/EmmanuelMess/27de5674866f07085040a2908d540df3)
- Proton version: 3.7-6

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.

**Comment by d10sfan** [comment]
This is a native Linux game

**Comment by HonkingGoose** [comment]
For reference and future searches for this game, the correct title of the game is: **Psychonauts**

And of course as @d10sfan said, it's a Linux native game.

But @EmmanuelMess don't feel too bad, its easy to get this wrong. Thanks for trying to contribute. :smile:
