### ISSUE TITLE
Fallout 3 black screen without xlive.dll

### ISSUE THREAD

**Issue by Kryuko** [ValveSoftware/Proton#1483]
# Compatibility Report
- Name of the game with compatibility issues: Fallout3
- Steam AppID of the game: 22370

## System Information
- GPU: GTX970
- Driver/LLVM version: nvidia 396.54 
- Kernel version: 1.15
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Kryuko/cbe1d228889d81914fe9d1e149a80f2a
- Proton version: every version

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Reproduction

Just open the game. You will see the launcher, if you click play you will have a black fullscreen window. 
Putting the xlive.dll file in the root game directory solve the issue.

Thank you in advance.

**Comment by kisak-valve** [comment]
Hello @Kryuko, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/370#issuecomment-421761419.
