### ISSUE TITLE
Run Utilities with Proton

### ISSUE THREAD

**Issue by 4LT** [ValveSoftware/Proton#1485]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description

I'm requesting an easier means of running utilities under Proton.  I think a good solution would be to have Steam auto-detect the file type of programs added through 'Add a non-Steam game' and run them under proton if they are Windows executables.

## Justification

Some games provide utilities that need wine/proton to run, such as *Worms Armageddon's* sound bank editor.   Currently, the only way to get at them (that I know of) is to take an existing steam game and set its launch options to something like `/path/to/proton waitforexitandrun /path/to/utility && echo %command% >/dev/null`.  This is cumbersome, and requires swapping launch options every time you want to switch between the game and the utility.  Additionally, trying to run Proton as a non-steam game does not work because it does not run under the same environment as it does when run from a steam game's launcher.

## Risks

* Determining which Proton installation to use when installed on multiple paths.

**Comment by kisak-valve** [comment]
Hello @4LT, this reads as a feature request for the Steam client instead of Proton itself, so I've transferred this issue to https://github.com/ValveSoftware/steam-for-linux/issues/5766.

**Comment by lucifertdark** [comment]
Winetricks is your friend, in Winetricks & the prefix of your choice, run task manager & use that to start up any application you want in that prefix, from anywhere on your hard drive.
