### ISSUE TITLE
Supreme Commander Forged Alliance

### ISSUE THREAD

**Issue by tatsujb** [ValveSoftware/Proton#1487]
# Whitelist Request
- Name of the game to be whitelisted: Supreme Commander Forged Alliance
- Steam AppID of the game: 9420

## System Information
- GPU: GTX 760
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.15.0-34-generic
- Link to full system information: https://gist.github.com/tatsujb/275e7e3817dac46c7b1bce26b1e94c15
- Proton version: 3.7

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [X] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [X] that no workarounds other than the mentioned ones are necessary.

## Issues
- [ ] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [X] Although I consider the gaming experience equal to Windows there are
      remaining issues:

The game runs perfect past the main menu. 

(normally the games starts up to a black screen (you hear the intro video's audio but the screen is black))

I used to use `alt`-`F4` to trick the graphics stack into refreshing by making the "do you really want to exit prompt" modal show up (which I then closed).

but thanks to this github's config section : https://github.com/ValveSoftware/Proton#runtime-config-options , I've figured out that actually, enabling `PROTON_NO_ESYNC` solves this in much cleaner fashion and utterly removes menu issues altogether and makes the game as a whole run identically to windows.

Off-Topic : 
--------------

Is there a place I can get counsel on figuring out how to execute a game via proton but only in command-line?

Supreme Commander Forged Alliance's online community, despite using steam's Supreme Commander Forged Alliance is practically entirely on an online platform built around this game called Forged Alliance Forever, (aka FAF) which runs natively in Linux, in which case in a wine scenario, it does nothing specific, you simply point FAF to the bin directory in the same fashion you would under windows and the communication between the two apps happens flawlessly.

since under ubuntu 18.04.1 wine has ceased to work for a number of apps including Forged Alliance and since proton performs much better, doing all this with proton instead would be much better.

I hoped that running the app with the following commands was what steam did :

    cd ~/.local/share/Steam/steamapps/common/Proton*
    STEAM_COMPAT_DATA_PATH=/home/t/.local/share/Steam/steamapps/compatdata/9420 ./proton run /home/t/.local/share/Steam/steamapps/common/Supreme\ Commander\ Forged\ Alliance/bin/SupremeCommander.exe

but as it happens I must be missing some arguments or what steam does is completely different because this ends immediately with a popup error saying with `PROTON_NO_ESYNC` off : 

> Application load error P : 0000065615

or with `PROTON_NO_ESYNC` on : 

> Application load error P : 0000065434

whereas, via steam, it runs flawlessly

**Comment by kisak-valve** [comment]
Hello @tatsujb, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/688#issuecomment-421791298.
