### ISSUE TITLE
does this mean it will be available for mac as well?

### ISSUE THREAD

**Issue by hexeric** [ValveSoftware/Proton#149]
i often use wineskin and many titles work, is proton more advanced and would it be possible to make it run on macOS as well in the future? it does not replace developer's native linux versions, right? it is still emulation and a feature of steam? thanks, not really an issue, i know! sorry.

**Comment by HereInPlainSight** [comment]
MacOS info was in the FAQ in the announcement.

Q: Any plans for macOS support?

While Wine and Proton work on macOS, there are no plans to support the new Steam Play functionality on macOS at the moment. 

Sourced from: https://steamcommunity.com/games/221410#announcements/detail/1696055855739350561
