### ISSUE TITLE
Not start Kingdom Come: Deliverance with bumblebee

### ISSUE THREAD

**Issue by kuraleb** [ValveSoftware/Proton#1490]
# Compatibility Report
- Name of the game with compatibility issues: Kingdom Come Deliverance
- Steam AppID of the game: 379430

## System Information
- GPU: NVIDIA Corporation GK208BM [GeForce 920M] (rev a1)
- Driver/LLVM version: Mesa 18.0.2-lp160.17.2 and nvidia-bumblebee 390.87
- Kernel version: <4.12.14>
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:3.7.6-Beta

## I confirm:
- [v] that I haven't found an existing compatibility report for this game.
- [v] that I have checked whether there are updates for my system available.

 
[steam-379430.log](https://github.com/ValveSoftware/Proton/files/2386827/steam-379430.log)

**Comment by kisak-valve** [comment]
Hello @kuraleb, we're using one issue per unofficially supported game title, and this game is already being tracked at #692. You possibly are also running into #65.

Closing in favor of the existing issue reports.
