### ISSUE TITLE
Fallout 4 on Steam Play, New Game won't start

### ISSUE THREAD

**Issue by amsalazar777** [ValveSoftware/Proton#1495]
# Compatibility Report
- Name of the game with compatibility issues: Fallout 4
- Steam AppID of the game:

## System Information
- GPU:  GTX 1080ti
- Driver/LLVM version:  396.54
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 3.7-6 BETA

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms  I've installed Steam on Ubuntu and have enabled "Steam Play". Steam Play works for most of my games. For fallout 4 specifically I can't get past the Main Menu. Everything works fine until I want to start a new game. As soon as I click "New Game" the loading icon pops up at the bottom right screen and will continue as the menu screen cycles through the camera angles. That's as far as it gets. Never finishes loading, never allows to quit the game, never starts a new game.

PC Specs:
CPU: AMD Threadripper 1950x
GPU: NVIDIA 1080ti OC edition (latest GPU driver installed: 396.54)
Mother Board: ROG Zenith Extreme
Memory: 32 GB 

I have no mods on this game, but i do have all the dlc from the Game Of The Year Edition

**Comment by GloriousEggroll** [comment]
I've reported this in the main fallout 4 bug report here: https://github.com/ValveSoftware/Proton/issues/308#issuecomment-419923966

it may be noted we both have the same issue and both are using a threadripper 1950x. unsure if that has any relation to the issue

**Comment by kisak-valve** [comment]
Hello @amsalazar777, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/308#issuecomment-422128234.

**Comment by amsalazar777** [comment]
okay, thank you. didn't see the other reports
