### ISSUE TITLE
Left 4 Dead Is Broken In Proton (Unplayable)

### ISSUE THREAD

**Issue by Hicks83** [ValveSoftware/Proton#1496]
Left 4 Dead launches fine and the menu and settings seem to function properly. Whenever joining a game or creating one, the game crashes to desktop during the loading process. This issue has been reported on Stean threads multiple times. Any information on how to resolve the crashing would be appreciated. 
Specs:
OS: Linux Mint 19 Tara
Machine: Device: desktop Mobo: ASUSTeK model: M5A97 LE R2.0 v: Rev 1.xx serial: N/A
UEFI: American Megatrends v: 1903 date: 07/11/2013
CPU: 8 core AMD FX-8350 Eight-Core (-MCP-) arch: Bulldozer rev.0 cache: 16384 KB
flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm) bmips: 64217
clock speeds: min/max: 1400/4000 MHz 1: 1404 MHz 2: 1402 MHz 3: 1403 MHz 4: 1401 MHz
5: 1403 MHz 6: 1384 MHz 7: 1432 MHz 8: 1406 MHz
Graphics: Card: NVIDIA GK106 [GeForce GTX 660] bus-ID: 01:00.0 chip-ID: 10de:11c0
Display Server: x11 (X.Org 1.19.6 ) drivers: nouveau (unloaded: modesetting,fbdev,vesa)
Resolution: 1280x1024@60.02hz
OpenGL: renderer: NVE6 version: 4.3 Mesa 18.0.5 (compat-v: 3.0) Direct Render: Yes
Graphics Driver: nvidia driver version 390.48-0ubuntu3

**Comment by kisak-valve** [comment]
Hello @Hicks83, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/406#issuecomment-422132795.
