### ISSUE TITLE
Dwarfs!?(35480)

### ISSUE THREAD

**Issue by Wandang** [ValveSoftware/Proton#1497]
# Compatibility Report
- Name of the game with compatibility issues: Dwarfs!?
- Steam AppID of the game: 35480

## System Information
- GPU: RX 460
- Driver/LLVM version: OpenGL version string: 4.4 (Compatibility Profile) Mesa 18.2.0
- Kernel version: 4.18.7
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Wandang/b44c8175ce50e17f60e623f989546971
- Proton version: 3.7-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

No log is being generated.

## Symptoms 

Game does not start.
Terminal Log: https://gist.github.com/Wandang/7fb92991fb3b06a28348c7c1f90b5f26

## Reproduction

Start the game.

**Comment by Wandang** [comment]
Dwarfs!? has a native version now

**Comment by Wandang** [comment]
The native version does not work as well (was apparently abandoned by the devs).
The windows version should work, so I am going to reopen the issue in hopes that we can still play this game on linux this way.

**Comment by kisak-valve** [comment]
Hello @Wandang, for the time being we're not tracking games with a native linux version and https://github.com/ValveSoftware/steam-for-linux/issues/5638 is tracking that feature request.

**Comment by waspennator** [comment]
@kisak-valve 
Could this report be reopened, I tried it on my oled steam deck LE with proton Experimental  and it crashes as soon as I try to start it, guessing it also effects the f2p version too.

[steam-35480.log](https://github.com/user-attachments/files/30992974/steam-35480.log)
