### ISSUE TITLE
[Whitelist] STAR WARS™ Jedi Knight II - Jedi Outcast™ (6030)

### ISSUE THREAD

**Issue by dreamer** [ValveSoftware/Proton#1501]
# Whitelist Request
- Name of the game to be whitelisted: STAR WARS™ Jedi Knight II - Jedi Outcast™
- Steam AppID of the game: 6030

## System Information
- GPU: **system 1:** GTX 770, **system 2:** Intel® HD Graphics 3000 (Sandy Bridge)
- Driver/LLVM version: **system 1:** 4.6.0 NVIDIA 396.54 **system 2:** 3.0 Mesa 18.0.5
- Kernel version: 4.17.19
- Link to full system information report as [Gist](https://gist.github.com/): [system 1](https://gist.github.com/dreamer/03179db6f82b01e06ec8fa41faf09f00), [system 2](https://gist.github.com/dreamer/4f3773020ded88d4612e41de4dd67b7e)
- Proton version: 3.7-6-git (with #1423 merged-in)

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [x] Although I consider the gaming experience equal to Windows there are remaining issues:

This is an old game, which does not support modern resolutions - it is possible to play in FHD (using usual Q3A console commands), but the interface is stretched. For me, playing through Proton provides **better** experience than [native build](https://github.com/JACoders/OpenJK), because it centres the screen when using 4:3 aspect ratio.

I tested both singleplayer and multiplayer.

I repeat, to get this game to state appropriate for whitelist, PR #1423 would need to be merged. Without this PR game would have two issues:

- crash at start due to bug in engine
- "grey screen filter", for some users it manifests as "white screen filter" - some reports indicate, that it's because of Screen overlay (but I'm not sure). It can be fixed by parameter "+r_ignorehwgamma 1" (which is handled by my PR automatically)

**Comment by kisak-valve** [comment]
Hello @dreamer, I have to reject this while list request because you are using a modified version of Proton. This is the literal purpose of the "that no workarounds other than the mentioned ones are necessary." checkbox in the template.

If at some point this works in a release version of Proton and nobody has opened an issue report for this game, then give me a ping here with the updated information and I can reopen the request at that time.
