### ISSUE TITLE
Fallout: A Post Nuclear Role Playing Game (38400)

### ISSUE THREAD

**Issue by dreamer** [ValveSoftware/Proton#1503]
# Compatibility Report
- Name of the game with compatibility issues: Fallout: A Post Nuclear Role Playing Game
- Steam AppID of the game: 38400

## System Information
- GPU: GTX 770
- Driver/LLVM version: NVIDIA 396.54
- Kernel version: 4.17.19
- Link to full system information report: [Gist](https://gist.github.com/dreamer/03179db6f82b01e06ec8fa41faf09f00)
- Proton version: 3.7-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-38400.log](https://github.com/ValveSoftware/Proton/files/2393323/steam-38400.log)

## Symptoms

Game launcher does not start (neither Classsic nor HD version). Proton refuses to launch it with following error:

    err:module:LdrInitializeThunk Main exe initialization for L"Z:\\home\\dreamer_\\.local\\share\\Steam\\steamapps\\common\\Fallout\\FalloutLauncher.exe" failed, status c0000017

Status c0000017 in this context means: STATUS_NO_MEMORY (but it probably really means, that Wine failed to secure page protection bytes on x86_64). Seems to happen only when launching this game using wine64.

## Reproduction

Just press "Play" - seemingly nothing happens.

## Workarounds

As indicated in community reports: https://spcr.netlify.com/app/38400 - the game itself works if you disregard launcher app by renaming "falloutHR.exe" to "FalloutLauncher.exe".

Original `FalloutLauncher.exe` works in wine-3.14 (Staging) using `wine`, but does not work through `wine64`.

**Comment by HeavyHamster** [comment]
Hello,
I can confirm that game works fine after renaming the .exe file.
I would like to add if is there some way to change the path where the start button searches for the .exe file, like for using the FIXT instead of the original version.
I can run under wine the FIXT version when calling it from it's folder (/home/.../Fallout/Fallout Fixt/) but copying or symlink the "falloutw.exe" into root folder (/home/.../Fallout/) just launches the original game version. Also I've tried to move the patched files into Fallout folder but then it asks for the CD.
Thanks

**Comment by dreamer** [comment]
Just tested with Proton 3.7-7 Beta and situation improved considerably.

Launcher does not crash on start any more, now it's just complaining, that Wine Mono is not installed. To workaround that, `dotnet40` needs to be installed using winetricks or protontricks (technically, it's already installed by Steam, but winetricks will repair existing installation). After that game complains, that it cannot be started, then launcher app starts anyway :).

On subsequent runs, no errors appear at all. File renaming is not needed any more.

Tested both default version and Classic. Default works perfect, Classic works fine, but is extremely slow.

**Comment by ghost** [comment]
Can confirm results from Proton 3.7-7:  Game does not start due to Fallout2Launcher.exe requiring dotnet/mono.

```
err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed
```
Attempted dotnet40 installation via [protontricks](https://github.com/Sirmentio/protontricks) as @dreamer suggested.  After successfully repairing the dotnet40 installation and a couple rundll32 error popups, launcher starts and game (fallout2HR.exe) works fine.

Unsure about cause so far, possible corrupted or incomplete dotnet binary set included with Proton?  dll overrides needed?  

I'll keep messing around with it, but I'd suggest Proton/Steam simply bypass the launcher as it's completely unnecessary, and launch **fallout2HR.exe** / **fallout.exe** directly as a easy and preferred solution in this case.

**Comment by omicron-b** [comment]
Wine mono is not included in Proton. This is being tracked in https://github.com/ValveSoftware/Proton/issues/18

**Comment by dreamer** [comment]
@m-svo that's not the issue - Steam attempts to install .net 4.0 when Fallout is started for the first time, the problem is, that installation is somehow "broken", and subsequent manual installation fixes it.

**Comment by ghost** [comment]
Yeah, that seems to be my observation as well.

**Comment by dreamer** [comment]
There's a new issue: after several seconds cursor stops responding to input. Then it works for a second or two and then it stops again - this happens all the time (in game, in menus, etc). It makes the game pretty much unplayable...

It is a regression from 3.7-8 to 3.16.* (tested with 3.16-3). I can't compare between various 3.16-* builds, as only '3' is is available.

I tried if PROTON_NO_ESYNC=1 will resolve the issue, but it made no difference at all. I am not 100% sure, but installing dotnet40 to fix launcher also seems to not work any more. 

All the same regressions happen to Fallout 2 (38410).

**Comment by dreamer** [comment]
Played for few minutes using 3.16-4 and regression with mouse input seems gone.

**Comment by madewokherd** [comment]
This has a winforms launcher that seems to work fine with wine-mono, so it should work once #18 is fixed.

**Comment by dreamer** [comment]
@kisak-valve @aeikum with pleasure I must report than release 4.2-3 fixed the launcher. Tested using Mesa 18.3.6 on Intel integrated GPU [gist with hardware info](https://gist.github.com/dreamer/4f3773020ded88d4612e41de4dd67b7e).

On the first run after a clean installation, Steam got stuck for some time on "first time setup", but I'm not sure if it was really a bug (and even if it was - it might've been in the Steam client). I closed the window, clicked "Play" again and it worked just fine. I'll attach logs if I'll be able to reproduce this behaviour.

Launcher works correctly ("Play" starts the game, "README" runs Wine Wordpad, "Tech support" redirects to https://help.bethesda.net/).

While in-game, the mouse cursor works without any lag and alt-tab works perfectly. Steam overlay does not work - to me it seems like Fallout is taking over keyboard input (Shift-tab does not work, F12 does not trigger in-Steam screenshots), but I don't think it's a deal breaker.

In my opinion, applying Whitelist label and maybe Retest-needed is in order :)

**Comment by kisak-valve** [comment]
Hello, is anyone seeing any issues with this game that would block it from being whitelisted?

**Comment by omicron-b** [comment]
Works fine for me, with the exception of overlay.

## System Information
- GPU: GTX 1060
- Driver/LLVM version: nvidia 418.56
- Kernel version: 5.0.0-13
- Link to full system information report as [Gist](https://gist.github.com/omicron-b/6ed1f6895f6a5678af836737c9fbadc5)
- Proton version: 4.2-3

**Comment by kapsh** [comment]
Reporting in: Fallout couldn't launch before with old Proton version, but now it works on the same configuration after forcing to use Proton 4.2.

[System info](https://gist.github.com/kapsh/545a06d3a0a1bd795268fd1cb0cfb532)

**Comment by dreamer** [comment]
Turns out lack of Steam Overlay is not a bug - publisher **disabled** this feature by setting [DisableOverlay=Yes](https://steamdb.info/app/38400/info/). In fact, when testing GOG version of the game added as a shortcut - Steam Overlay works great.

**Comment by kisak-valve** [comment]
This game was found in the 2019-07-31 whitelist update.

If you encounter an issue with this game, please search the open issues for 38400, and report any issues encountered with this game in separate issue reports, one issue per issue report.
