### ISSUE TITLE
Dragon's Dogma: Dark Arisen - poor performance

### ISSUE THREAD

**Issue by MrWissenschaft** [ValveSoftware/Proton#1505]
Is anyone getting bad performance for Dark Arisen? I've seen that loads of people are having success with it but it seems like the latency is crazy, like my character is in slow motion.

Framerate is lowish as well. Any ideas on a fix at all?

**Comment by MrWissenschaft** [comment]
https://gist.github.com/MrWissenschaft/19d7a73c997a2af6998bf240f6a70dfc

**Comment by kisak-valve** [comment]
Hello @MrWissenschaft, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1235#issuecomment-422598976.
