### ISSUE TITLE
Auto whitelist Proton games which were played for one hour+ ?

### ISSUE THREAD

**Issue by tr37ion** [ValveSoftware/Proton#151]
How about data mine all games which were played with Proton for at least 1 hour (without AFK) to auto whitelist those games. Possibly adding a mixture of distributions and hardware configs, too.

**Comment by ArekPiekarz** [comment]
That alone wouldn't detect if the game worked without bugs.

**Comment by Houkime** [comment]
I've played No Man's Sky for several hours in wine even with nonworking, requiring from mesa not yet implemented opengl 4.5 compatibility terrain shaders.
Have spoken to Atlas. Probably one of a few who did this on Linux machine with radeon card ^_^
This was quite psychedelic but surprisingly playable.
Time is not an indicator.

**Comment by prcastro** [comment]
Maybe 1+ hour by more than 10 (or more) gamers. This way we could discard outliers (such as people playing broken games). Or even using this to select games for manual inspection.

**Comment by ghost** [comment]
A special option in the Steam Overlay screen on Proton games allowing us to rate the experience might be helpful (Perfect/Good/Buggy/Poor/etc).  Adding an optional tick box to send hardware information along with the rating to identify hardware/driver-specific issues would be useful too.

**Comment by parkerlreed** [comment]
Also eventually a configuration similar to the controllers would be sweet. Being able to vote on profiles based on usage and have different profiles for different OS/hardware setups. Make it community driven.

**Comment by Exagone313** [comment]
Since you can change the command line for starting the game, you could fool steam in believing a game is playable.

**Comment by tr37ion** [comment]
The chosen timeframe is just an example. But setting the most obvious working games by analysing game time per Proton game eg. might help to get a first bunch of games auto whitelisted and if they don't work, people can open an issue ... instead of opening an issue asking for whitelisting the game, without being sure, that the gamer also tested Big Picture, Controllers, SaveGames, Cloud eg.
... just a thought.

**Comment by ibrokemypie** [comment]
Some games crash but shows in steam as "running" forever. this would not be a suitable metric on its own, however perhaps asking users in a dialog whether a game works after it has been running for some time may be a better idea

**Comment by hzulla** [comment]
> A special option in the Steam Overlay screen on Proton games allowing us to rate the experience might be helpful (Perfect/Good/Buggy/Poor/etc). Adding an optional tick box to send hardware information along with the rating to identify hardware/driver-specific issues would be useful too.

Yes, please, please, please, exactly that. Those people who install a beta Steam client and activate the unsupported "Enable Steam Play for all titles" option are probably more than willing to provide useful feedback in that manner. The [current way to report success](https://github.com/ValveSoftware/Proton/issues/283) can't be very useful to the Steam client developers.

**Comment by Stumpftopf** [comment]
@Houkime
Hi, how did you do that? I am also an Radeon Card owner. Didn't even get NMS to pass Loadingscreen on Savegame or new Game on Wine(3.9>) with Oibaf Mesa Drivers, due Shader Error. Now in Proton it works, but Shaders also fucked up. See only white screen and ui artefacts. Menu works flawless.

**Comment by Houkime** [comment]
@Stumpftopf
This is offtopic. You probably want to create a separate issue for No Man's Sky compatibility issues with description of your troubles just like issues marked with "compatibility: unofficial" where people can discuss troubles with NMS.
Short answer: NMS relies on OpenGL4.5-specific methods. Support for it in mesa is currently limited and is forcibly enabled by launching with MESA_GL_VERSION_OVERRIDE=4.5COMPAT env. variable. This is effective in current git version or 18.2 when it comes out. See  
https://cgit.freedesktop.org/mesa/mesa/commit/?id=0cb6537deecbbb5f330b5835de29f64e4faf61c4

**Comment by Stumpftopf** [comment]
@Houkime 
Done: https://github.com/ValveSoftware/Proton/issues/438

**Comment by CuriousTommy** [comment]
Instead of outright adding a game to the whitelist, I think it should be added in a list of future potentional whitelisted games. That way, [people don't have to resort to using a platform-specific wishlist](https://steamcommunity.com/games/221410/announcements/detail/1475356649450732547).

**Comment by FreeSevenSix** [comment]
no, after playing mass effect for 10 hours, it started crashing every 5-10 minutes

**Comment by monyarm** [comment]
A checkbox to allow people to whitelist a game for themselves would be great.
