### ISSUE TITLE
Steam client crashes when trying to start any Proton game on OpenSUSE Leap 15.0

### ISSUE THREAD

**Issue by digulla** [ValveSoftware/Proton#1512]
# Compatibility Report
- Name of the game with compatibility issues: Steam client itself

## System Information
- GPU: NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
- Driver/LLVM version: 4.6.0 NVIDIA 390.87
- Kernel version: 4.12.14-lp150.12.16-default
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/digulla/63395ab6379228576d379fbdcc85901c
- Proton version: ???

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

No log file is written when I use `PROTON_LOG=1 %command%`. I guess it crashed before that.

## Symptoms 
When I click play, the steam client opens a dialog box and then crashes immediately before I can click anything:

```
GameAction [AppID 590380, ActionID 1] : LaunchApp changed task to ShowSteamPlayWarning with ""
GameAction [AppID 590380, ActionID 1] : LaunchApp waiting for user response to ShowSteamPlayWarning ""
Cannot connect to server socket err = No such file or directory
Cannot connect to server socket
jack server is not running or cannot be started
Failed to open digital audio driver No mixer services exist.
crash_20180919224859_1.dmp[30645]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180919224859_1.dmp
/storage/adigulla/.local/share/Steam/steam.sh: Zeile 876: 29272 Speicherzugriffsfehler  (Speicherabzug geschrieben) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
html_chrome.cpp (394) : Assertion Failed: CefCrashReportingEnabled()
crash_20180919224859_1.dmp[30645]: Finished uploading minidump (out-of-process): success = yes
crash_20180919224859_1.dmp[30645]: response: CrashID=bp-041a3c36-df11-4f1f-9e5a-ce5e22180919
crash_20180919224859_1.dmp[30645]: file ''/tmp/dumps/crash_20180919224859_1.dmp'', upload yes: ''CrashID=bp-041a3c36-df11-4f1f-9e5a-ce5e22180919''
```

There is a lot of weird output in the log:

```
Running Steam on opensuse-leap 15.0 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1536436120)
...
[0919/224904.579466:WARNING:crash_reporting.cc(254)] Failed to set crash key: UserID with value: 0
[0919/224904.579515:WARNING:crash_reporting.cc(254)] Failed to set crash key: BuildID with value: 1536434509
[0919/224904.579518:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
[0919/224904.579521:WARNING:crash_reporting.cc(254)] Failed to set crash key: Version with value: 1536434509
[0919/224904.579524:WARNING:crash_reporting.cc(254)] Failed to set crash key: ProductName with value: cefwebhelper
[0919/224904.579527:WARNING:crash_reporting.cc(254)] Failed to set crash key: Vendor with value: Valve
```

This might be relevant, too:

    Found unsupported CDM version 1.4.9.1088, using last known good version 1.4.8.1008

The steam client also crashes when I try to switch to the beta client.

## Reproduction
Happens always.

**Comment by digulla** [comment]
All other games work. It's just when the client needs to use Proton that it crashes.

**Comment by kisak-valve** [comment]
Hello @digulla, issues with the steam client are being tracked in the steam-for-linux issue tracker, so I've transferred this issue to https://github.com/ValveSoftware/steam-for-linux/issues/5772.
