### ISSUE TITLE
[Whitelist] Primordia (227000)

### ISSUE THREAD

**Issue by veikk0** [ValveSoftware/Proton#1514]
# Whitelist Request
- Name of the game to be whitelisted: Primordia
- Steam AppID of the game: 227000

## System Information: Desktop
- GPU: Radeon RX 470 4GB
- Driver/LLVM version: 4.5 (Compatibility Profile) Mesa 18.3.0-devel - padoka PPA, DRM 3.23.0, LLVM 8.0.0
- Kernel version: 4.15.0-34-generic
- Link to full system information report: https://gist.github.com/veikk0/d0ebb1ddda8f9582d1799df343bfefe5
- Proton version: 3.7-6 Beta

## System Information: Laptop
- GPU: Intel HD Graphics 3000
- Driver/LLVM version: 3.0 Mesa 18.0.5
- Kernel version: 4.15.0-34-generic
- Link to full system information report: https://gist.github.com/veikk0/cb39ea5b6ec13e073ff5897aa53d1ffe
- Proton version: 3.7-6

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.

## Issues
- [x] I haven't experienced any issues.

## Other
I've played the game for about three hours spread over my laptop and deskto and have experienced no issues.

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.

**Comment by konkode** [comment]
This game just received a native Linux version, but its whitelist status forces the download of the Windows version and runs it through Proton.

The Linux version can only be downloaded if Steam Linux Runtime is forced through Compatibility Tools.

**Comment by Dualnames1** [comment]
Hello, James Spanos, developer of Primordia here, please do remove the whitelist.
I've opened up a post here, https://steamcommunity.com/groups/steamworks/discussions/0/3032599335599121285/

That explains the problem with the whitelist.
