### ISSUE TITLE
Use Proton to play windows version of games with bad linux ports

### ISSUE THREAD

**Issue by mkaito** [ValveSoftware/Proton#1518]
# Feature Request
Play windows version of games with shoddy Linux ports.

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
There are games with native Linux ports that are just bad, and little hope to be fixed. It would be really nice if we could use Steam Play to launch the Windows version instead.

For example, two that I own:
* Doom & Destiny
* Doom & Destiny Advanced

Both are compiled against specific Mono versions, that are not bundled. I've contacted the developer repeatedly and obtained no response. I'm not holding my breath that they will ever do anything about it.

**Comment by kisak-valve** [comment]
Hello @mkaito, this feature request is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5638. Closing as a duplicate.
