### ISSUE TITLE
Battlerite crashes while connecting to a match after the recent update

### ISSUE THREAD

**Issue by ogdenwebb** [ValveSoftware/Proton#1524]
# Compatibility Report
- Name of the game: Battlerite
- Steam AppID of the game:  504370

## System Information
- GPU: GTX 650 TI Boost
- Driver/LLVM version:  nvidia 396.54 
- Kernel version: 4.18-5
- Link to full system information: [here](https://gist.github.com/ogdenwebb/e98cd9e7f76e741b2f7f894598e1628d)
- Proton version: 3.7.6

## Symptoms 
Today after the recent update Battlerite(i.e. 1.8.0) I can't play a match. Menu is still working well, but when I start a match or a practice the game will almost immediately crash while connecting.

**NOTE:** this issue is only related to Steam Play/Proton, because with Lutris 0.4.18 and wine-staging 3.16 Battlerite works fine.
Also the reddit user Lethiks confirms it [here](https://www.reddit.com/r/BattleRite/comments/9heg01/patch_18_bug_report_megathread/e6btlsy)

## Reproduction

1. Run Battlerite the AppID is `504370`.
2. Select Practice -> Playground or  Play -> Casual/League -> Ready
3. The game will stuck on loading and Steam displays popup window about crash.

## Log files
- Log files from the game directory:
[error.log](https://github.com/ValveSoftware/Proton/files/2403249/error.log)
[output_log.txt](https://github.com/ValveSoftware/Proton/files/2403251/output_log.txt)
- Proton log via PROTON_LOG=1 %command%:
[steam-504370.log](https://github.com/ValveSoftware/Proton/files/2403252/steam-504370.log)

**Comment by kisak-valve** [comment]
Hello @ogdenwebb, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/326#issuecomment-423362210.
