### ISSUE TITLE
The Technomancer Crashes At Launch (338390)

### ISSUE THREAD

**Issue by Simmonz** [ValveSoftware/Proton#1525]
I tried running The Technomancer through Proton and it crashes at launch. The Steam AppID of the game is 338390. I added PROTON_LOG=1 %command% to the game's launch options and received the following log:

[steam-338390.log](https://github.com/ValveSoftware/Proton/files/2403689/steam-338390.log)

I haven't found an existing compatibility report for this game and I have checked whether there are updates for my system available.

System Information:

OS: Solus

GPU: RX 580 8GB

Driver/LLVM version: Mesa 18.1.6

Kernel version: 4.18.5-90.current

Proton version: 3.7-6

https://gist.github.com/Simmonz/ee96fbeb3d32de20b2ebea979bf1746f

**Comment by ziabice** [comment]
Take a look here: #656

**Comment by kisak-valve** [comment]
Hello @Simmonz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/656#issuecomment-423528152/
