### ISSUE TITLE
Nier Automata freezes on first combat in the introduction (524220)

### ISSUE THREAD

**Issue by rainecheck** [ValveSoftware/Proton#1529]
# Compatibility Report
Name of the game with compatibility issues: Nier Automata
Steam AppID of the game: 524220

## System Information
- GPU: RX580
- Driver/LLVM version: Mesa 18.1.5, LLVM6
- Kernel version: Both 4.17.0 and 4.18.8
- Link to full system information report as Gist: [Link](https://gist.github.com/rainecheck/b8377a404143be9e583cc104a7b4c27f)
- Proton version: Both 3.7-6 and 3.7-6beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Steam log: [steam-524220.log](https://github.com/ValveSoftware/Proton/files/2405143/steam-524220.log)

## Symptoms 
Game starts and plays through the intro until the ships start firing. On friendly ships first hitting enemies in the intro, the system crashes and requires rebooting.

Updates and config variances I tried after installing and triggering this bug:
 - Update mesa
 - Install LLVM7 (based on older reports) - didn't seem to do anything
 - Try both beta proton and stable proton
 - Update kernel from 4.17.0 -> 4.18.8
 - Changing resolution from 1060x1050 -> the default 900p resolution
 - Change graphics quality settings from medium -> low
 - Fullscreen -> windowed

Also tried different gameplay behaviours: Shooting enemies, letting other ships shoot the enemies, crash into ships before friendly ships have a chance to fire...no dice.

On bug triggering the entire machine freezes up, except for the mouse. However, once I attempt to interact with anything (click anything, trigger albert, move workspaces etc), the mouse freezes up too. If the mouse pointer is untethered to the app I can move it to the second screen, but cannot interact with any other applications.

## Reproduction

Start game via Steam
Continue 
Select save file (which still records a Played time of 00:00)
Start Game
Watch the cutscene, avoid (or run into) the blasts, and watch the computer freeze up on a shot of 2/4 enemy ships exploding

**Comment by doitsujin** [comment]
You have to build Mesa against LLVM 7, just installing the libraries is not enough. Have you tried the Padoka PPA?

**Comment by rainecheck** [comment]
I've been using Ubuntu-X for x-org/mesa etc. I'll try Padoka and report back.

**Comment by rainecheck** [comment]
I've been using Ubuntu-X for x-org/mesa etc previously. I've just tried the mesa from Padoka and the same effect occurs.

Unless there are any other suggestions, I'll try building mesa against LLVM7 (though this will be new to me).

**Comment by doitsujin** [comment]
Should have noted to use mesa-git from the PPA rather than the stable packages (didn't know it had stable packages as well).

Anyway, the problem you're running into has definitely been fixed in LLVM 7, you just have to find a way to actually use it.

**Comment by rainecheck** [comment]
OK, I'll try out the unstable padoka PPA, which seems to now be on LLVM8 (hmm). Will confirm afterwards if it does fix it (fingers crossed).

**Comment by rainecheck** [comment]
OK, confirmed as working. It's hitting some pretty big frame drops and short freezes in the same spot and further on, assuming it's a cache being built or something. But, confirmed as fixed once running on Podoka-git Mesa. Thanks a bunch @doitsujin
