### ISSUE TITLE
Switching between 3.7-6 beta and 3.7-6 causes games to not work

### ISSUE THREAD

**Issue by julianovs** [ValveSoftware/Proton#1531]
Example: I install elder scroll online and choose a beta version of proton, so it will download the game and the beta version of proton
however if I want to change the version of proton to some other the game does not work anymore
I see that the game gets connected with the version of proton you chose the first time

**Comment by kisak-valve** [comment]
Hello @julianovs, for the moment, Proton 3.7-6 and 3.7-6 beta should be the same version and you should be able to freely switch between them. Please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by julianovs** [comment]
when I change the proton version(3.7.6 to 3.7.6 beta) no log is created inside my home and the elder scroll launcher does not run
when I go back to using the version that was already proton (3.7.6) thelauncher comes back to run and a log is created in my home (steam-306130.log)
