### ISSUE TITLE
Naruto Shippuden: Ultimate Ninja Storm 4 Crash on Startup

### ISSUE THREAD

**Issue by JustEnoughDucks** [ValveSoftware/Proton#1533]
# Compatibility Report
- Name of the game with compatibility issues: Naruto Shippuden: Ultimate Ninja Storm 4
- Steam AppID of the game: 349040

## System Information
- GPU: Nvidia GTX 770
- Driver/LLVM version: nvidia 396.54-6
- Kernel version: 4.18.9.arch1-1
- Link to full system information report as [Gist](https://gist.github.com/bpgerber/948bfb542138e7402159f5652e9a712a):
- Proton version: Both 3.7-6 and 3.7-6beta

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-349040.log](https://github.com/ValveSoftware/Proton/files/2406590/steam-349040.log)

## Symptoms 
Game crashes while loading the main title screen.

## Reproduction
Start game under proton 3.7-6 or beta

**Comment by kisak-valve** [comment]
Hello @bpgerber, this game is already being tracked at #103. Closing as a duplicate.
