### ISSUE TITLE
Nier: Automata not work with 4K (524220)

### ISSUE THREAD

**Issue by semsemyonoff** [ValveSoftware/Proton#1541]
# Compatibility Report
- Nier: Automata
- Steam AppID of the game: 524220

## System Information
- GPU: GTX 1070
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.15
- [system information](https://gist.github.com/seddor/0e53959eebdffa9a09f626606a0b8046)
- Proton version: 3.7-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Game not work after change resolution to 3840x2160 and other video setting.

After relunch game show into then show black screen and nothing more.

Or it run farther, but stuck to change to full screen.

[steam-524220.log](https://github.com/ValveSoftware/Proton/files/2407696/steam-524220.log)

## Reproduction

1. Run game
2. Change resolution to  3840x2160
3. Change screen mode to full screen
4. Game stuck

**Comment by 1player** [comment]
This can probably be closed, I have 5 hours played on 4K resolution, no issues at all.

**Comment by kisak-valve** [comment]
Closing per the last comment.
