### ISSUE TITLE
[Gamepad] Gamepad stopped working in Dragon Quest XI (742120)

### ISSUE THREAD

**Issue by DistantThunder** [ValveSoftware/Proton#1544]
# Compatibility Report
- Name of the game with compatibility issues: Dragon Quest XI
- Steam AppID of the game: 742120

## System Information
- GPU: GTX 1060
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.18.9-arch1-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/): 
Attached
[steam_system_info.txt](https://github.com/ValveSoftware/Proton/files/2408000/steam_system_info.txt)

- Proton version: 3.7-6 / Beta (both)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

* Steam client version (build number or date): Sep 20 2018 21:57:21
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

The gamepad stopped working in Dragon Quest XI. I cannot pinpoint the exact moment but I'd wagger it was during this week. 

I've changed gamepads, tried to run it using vanilla Wine and all the Lutris tricks to get the gamepad working, to no avail.

Other games retained gamepad support, like FFXII via Steam Play or the natives games.

#### Steps for reproducing this issue:

1. Launch the game 
2. Try to use the gamepad
3. No input is registered. 

Tested with original XBOX 360 wired controller and Original Dualshock 3 wired controller.

**Comment by kisak-valve** [comment]
Hello @DistantThunder, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1419#issuecomment-423760063.

**Comment by DistantThunder** [comment]
Ok.
