### ISSUE TITLE
Brightness / Gamma Settings have no effect 

### ISSUE THREAD

**Issue by MasterCATZ** [ValveSoftware/Proton#1550]
Been trying old OpenGL capable games like Quake 3 Arena , Quake 4, Doom 3, Unreal Tournament,  etc and the gamma settings does not affect the Brightness 

on Ubuntu via Steam

**Comment by Userwithaname** [comment]
As far as I can tell, this affects all games which interact with the driver/display directly to set their gamma (rather than using a post-effect).

I also noticed this with Dead Space 1/2 and Call Of Cthulhu: Dark Corners Of The Earth, which I think are DirectX games.

**Comment by fn-ix** [comment]
Same problem for me on the Source-based INFRA.

**Comment by Lyle-Tafoya** [comment]
I have noticed this as well. I have also noticed that running games in Windowed mode tends to resolve the issue for me.

**Comment by dreamer** [comment]
Affected games are the ones, that try to control gamma of the whole desktop and not just it's own window. This is an unfortunate side-effect of [this change](https://github.com/ValveSoftware/wine/commit/8cb0311#diff-1ab1520ea4f5563fdaad5f920b0c58fa).

Here's the workaround:

    $ protontricks <appid> regedit

Click on "Registry" menu, then "Import Registry File…" and select [usexvidmode.reg](https://gist.githubusercontent.com/dreamer/2486a82b55e9ec573245cc9f1aaa9eca/raw/b670030de78016ba066218457d12f148be5e0698/usexvidmode.reg).

After this, game will be able to change display resolution and modify brightness. Tested it using Jedi Knight I (#1744) and II (#1732) - it worked fine. Also in UT:GOTY (#568) - the game does not set original brightness value after exit (it does not crash).

**Comment by soredake** [comment]
Any progress on this?

**Comment by zaps166** [comment]
Can't set Gamma in Witcher 3 + Proton.
Gamma works when running Windows Steam (wine-staging) + DXVK.

**Comment by nghitran** [comment]
I tried @dreamer's workaround but still not working in Witcher 3 + Proton 5.0

**Comment by dolour** [comment]
Neither does Doom 3 with GE 5.4, Proton 3.16, 4.11 or 5.0.

**Comment by ZereoX** [comment]
Hi @kisak-valve,

As of Proton 6.3-3, brightness and gamma adjustments should be working correctly in most games (this was mostly affecting titles that still relied on WineD3D).

Witcher 3 however still requires the use of DXVK's DXGI. This can be enabled by running the following launch option: `WINEDLLOVERRIDES="dxgi=n" %command%`

The following have been confirmed to work on 6.3-3:
- Blood Omen 2: Legacy of Kain
- Bully: Scholarship Edition
- Deus Ex: GOTY
- Deus Ex: Invisible War
- DOOM 3
- Evil Genius
- Fallout: New Vegas
- Hitman 2: Silent Assassin
- Quake 4
- RAGE (32-bit)
- Thief: Deadly Shadows
- Tomb Raider IV: Last Revelation
- Unreal Tournament 2004

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by ZereoX** [comment]
Proton-Experimental also now ships DXVK's DXGI by default, so the work around for Witcher 3 should no longer be required with it.
