### ISSUE TITLE
Documenation issue: Windows or Linux Client

### ISSUE THREAD

**Issue by ShalokShalom** [ValveSoftware/Proton#1551]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

https://github.com/ValveSoftware/Proton#introduction

From within this description, I dont know if I am supposed to install the Windows client or the Linux one. Is it meant to get used by the Windows client on top of Proton/WINE? 
Or is it build in the Linux client?

**Comment by kode54** [comment]
A binary package is acquired by and used by the Linux client.

**Comment by KGOrphanides** [comment]
Proton is built into the Linux Steam client, but can also be run stand-alone if you're thus inclined and comfortable doing so. 

More detailed instructions for the Steam client version may be found at https://steamcommunity.com/games/221410/announcements/detail/1696055855739350561

By default, the version built into Steam is only enabled for a handful of whitelisted games but you can easily enable it to (experimentally and with no guarantees) work with all games.

Make sure you're opted into the Steam Client Beta (Steam > Settings > Account - Beta Participation), and in the Steam Play tab of the settings menu, ensure that both Enable Steam Play for supported titles and Enable Steam Play for all titles are ticked.

(I know you highlighted this as a docs issue, but I've stuck full details on activating the feature in here in case anyone comes looking for an answer IRL.)

**Comment by ShalokShalom** [comment]
Thanks a lot, very helpful. I send a pull request which clarify that. 
As a secondary issue: Does any of you know anything about the 64 Bit version?
