### ISSUE TITLE
Tracking new feature requests

### ISSUE THREAD

**Issue by imkarthikk** [ValveSoftware/Proton#1557]
This is not a feature request as such. But was wondering if we could use some platform like hellonext (https://hellonext.co) to track all the feature requests.

**Comment by kisak-valve** [comment]
[Feature request search for Proton.](https://github.com/ValveSoftware/Proton/issues?q=is%3Aopen+is%3Aissue+label%3A%22Feature+Request%22)

**Comment by imkarthikk** [comment]
Yep. Noticed it. Thought it could be better on a platform. Much easier for users to file new feature requests.
