### ISSUE TITLE
[Whitelist] Faerie Solitaire (38600)

### ISSUE THREAD

**Issue by KGOrphanides** [ValveSoftware/Proton#1559]
# Whitelist Request
- Name of the game to be whitelisted: Faerie Solitaire
- Steam AppID of the game: 38600

## System Information
- GPU: AMD Radeon HD 6990
- Driver/LLVM version: Mesa 18.0.5
- Kernel version: 4.15.0-33-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/KGOrphanides/c0fe99f0d9824a8ab434907637c07400
- Proton version: 3.7-6

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

**Comment by kisak-valve** [comment]
It's also a native linux game.

**Comment by KGOrphanides** [comment]
Sorry, wrong version. I was testing Faerie Solitaire Remastered. (D'oh.)
I'll create a new report for the correct game.
