### ISSUE TITLE
Proton 3.7 unable to launch 

### ISSUE THREAD

**Issue by aldr-** [ValveSoftware/Proton#1568]
from the log file at /tmp/dumps/user_stdout.txt

ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/sh: /run/media/nvme/Steam/steamapps/common/Proton 3.7/proton: Permission denied
GameAction [AppID 292030, ActionID 3] : LaunchApp changed task to Completed with ""

my installed stem location is: /home/user/.local/share/Steam/
but I changed a steamapps folder linking /run/media/nvme/Steam/steamapps a ntfs formated and in fstab mounted hdd:
UUID=4842D50642D4FA20                   /run/media/nvme         auto    defaults,nls=utf8,umask=000,dmask=027,fmask=137,uid=1000,gid=1000,windows_names 0 0

when trying to launch Witcher 3 using the Steam app GUI clicking the Play button, I get that error message. 
/bin/sh: /run/media/nvme/Steam/steamapps/common/Proton 3.7/proton: Permission denied

I checked all permissions everywhere. Permission for every folder or file is my usern and group the user is in, so I'm not sure what permissions missing

**Comment by kisak-valve** [comment]
Hello @aldr-, please read #1057 and see if the discussion there helps.

**Comment by aldr-** [comment]
its the same issue like in #1057 I'll close this one and continue there
