### ISSUE TITLE
Question: LLVM vs LLVM-libs.

### ISSUE THREAD

**Issue by nstgc** [ValveSoftware/Proton#1572]
I noticed that LLVM 7 is now listed as a prereq, so I checked my version. Seeing that it is 6.0.1, I looked to see if it was flagged as outdated. It was at this time that I saw that Arch has both LLVM and LLVM-libs. I'm guessing that Proton only needs the libs, but wanted to make sure.

**Comment by kisak-valve** [comment]
Hello @nstgc, the llvm 7 recommendation is for mesa/AMDGPU users, as LLVM is used to compile shaders for those video cards and LLVM 6 has known issues. How your distro chooses to split LLVM is irrelevant for Proton and should follow mesa's package dependencies. The recommendation is a general "Please us mesa built against LLVM 7 or newer with Proton."
