### ISSUE TITLE
F.E.A.R 3 (21100)

### ISSUE THREAD

**Issue by KorinFlakes** [ValveSoftware/Proton#1575]
# Compatibility Report
- Name of the game with compatibility issues: F.E.A.R 3
- Steam AppID of the game: 21100

## System Information
- GPU: GTX 1060 (6gb)
- Driver/LLVM version: Nvidia 396.54
- Kernel version: Kernel version: 4.15.0-34
- [My System Info](https://gist.github.com/vikeyev/811fd811c070704bd996020db51913c6)
- Proton version: 3.7-6

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Game never launchers. When you press play, steam says you are playing the game, 60 seconds later it will go back to online.

[steam-21100.log](https://github.com/ValveSoftware/Proton/files/2410023/steam-21100.log)

**Comment by kisak-valve** [comment]
Hello @vikeyev, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/963#issuecomment-423957465.
