### ISSUE TITLE
[Whitelist] Everyday Shooter (16300)

### ISSUE THREAD

**Issue by ArekPiekarz** [ValveSoftware/Proton#158]
Everything works flawlessly in this game.

https://store.steampowered.com/app/16300/Everyday_Shooter/

My config:
Proton: 3.7 (default)
OS: Xubuntu 18.04 x64 (fully updated)
Linux kernel: 4.15.0-32 (default)
GPU: Nvidia Geforce GTX 1050 Ti Mobile
GPU drivers: Nvidia 396.51 (from graphics-drivers PPA)
CPU: Intel Core i7-7700HQ
Screen: 1920x1080
RAM: 16 GB

[Full system info from Steam](https://gist.github.com/ArekPiekarz/89c0066a2c86b4d6752c0460b7add468)

**Comment by L1Q** [comment]
I have sound crackling when in game.
I had similar issue in Audiosurf, but less severe and only in menus.
This does not happen in gta:sa

[hardware info from steam](https://gist.github.com/L1Q/a1761c67bc8b0c1f2b93d00a6b13a354)
[phoronix-test-suite system-info](https://gist.github.com/L1Q/0351ddf9060fc795313d4f5f96a06db6)

UPD: killing pulseaudio (``pulseaudio -k``) is a common fix and it works for me

UPD2: on Proton 3.7-6 I no longer have this issue

**Comment by kisak-valve** [comment]
Found in the 2018-10-05 white list update.
