### ISSUE TITLE
Whitelist Request TrackMania Forever

### ISSUE THREAD

**Issue by stephanlachnit** [ValveSoftware/Proton#1592]
Whitelist Request
Name: TrackMania Nations Forever / TrackMania United
App-ID: 11020 / 7200

(both games use the same engine)

System Information
- GPU: Intel Ironlake GPU
- Driver version: modesetting @ Mesa 18.1.7
- Kernel version: 4.18
- Proton version: 3.7-6 Beta

I haven't experienced any issues.

Attached file is Steam System Information
[steam.txt](https://github.com/ValveSoftware/Proton/files/2412665/steam.txt)

**Comment by kisak-valve** [comment]
Hello @9Strike, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/467#issuecomment-424114042.
