### ISSUE TITLE
Include features from Wine Staging to Proton and Sync Wine features to 3.16

### ISSUE THREAD

**Issue by CentralPython** [ValveSoftware/Proton#1595]
A lot of the games such as Aliens vs Predator work well on Wine Staging and other games but they don't work with Proton. Could a lot of the patches including features like gallium nine be integrated into Proton and be updated to the most recent Wine version and synced with both Wine and Wine staging from the current Wine release as of today or now which is 3.16 and not 3.7 which is considered outdated in my view.

**Comment by mirh** [comment]
#870

**Comment by Corben78** [comment]
If you refer to Aliens vs Predator from 2010, app id 10680, it doesn't start due to custom executable generation (CEG) copy protection. See https://github.com/ValveSoftware/Proton/issues/530#issuecomment-423771706 for details.

This is a Linux Steam client issue, not a wine issue.
