### ISSUE TITLE
Final Fantasy XII: The Zodiac Age - Crashes (595520)

### ISSUE THREAD

**Issue by asim-vax** [ValveSoftware/Proton#1596]
# Compatibility Report
Final Fantasy XII: The Zodiac Age
595520
## System Information
OS: Ubuntu 18.04.01
GPU: Nvidia gtx 060 3gb
Driver: 396.54.05
Gist: https://gist.github.com/asim-vax/d6deb52066207d2bc4096a3c1782286b
Proton: 3.9.6 (and -beta)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Attached steam log
[steam-595520.log](https://github.com/ValveSoftware/Proton/files/2412806/steam-595520.log)

## Symptoms 
Games crashes on launch, black screen stays, only way to close is via terminal

## Reproduction
Click run game, game launches, steam overlay icon appears, game crashes to black screen with wine error "A fatal error encountered"

**Comment by kisak-valve** [comment]
Hello @asim-vax, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/711#issuecomment-424121566.
