### ISSUE TITLE
Project Cars 2 Demo (737770)

### ISSUE THREAD

**Issue by mimattr** [ValveSoftware/Proton#1603]
# Compatibility Report
- Name of the game with compatibility issues: **Project Cars 2 Demo**
- Steam AppID of the game: **737770**

## System Information
- GPU: **GTX 970**
- Driver/LLVM version: **NVIDIA 396.54**
- Kernel version: **4.4.0-135-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **3.7-6 Beta**

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

- [steam-737770.log](https://gist.github.com/mimattr/7547d72d8bbc29a77a4e426c0bec830b)
- [pCARS2DemoAVX_d3d11.log](https://gist.github.com/mimattr/47aba3305e77f4a6fa95646a08073c72)
- [pCARS2DemoAVX_dxgi.log](https://gist.github.com/mimattr/898375575d7e5af4aa52e703bcd9a29e)

## Symptoms 
Consistent application crashes during loading stage:

> doitsujin/dxvk#641 Looks like we're actually supposed to return the virtual buffer length in Row/Depth Pitch and not the actual buffer length (unlike for images)

Issue is resolved using **DXVK 0.80** (doitsujin/dxvk@19408f0ebede526a1aad2a594b3b25619d1737e5)

## Reproduction
1. Select the title within your `Library` using the Steam client and press the `Play` button
1. Select any `Scenario` from the title screen and wait for the loading stage to complete

**Comment by libcg** [comment]
Should fixed with DXVK 0.80 included in Proton 3.7-7 Beta. https://github.com/doitsujin/dxvk/issues/641
