### ISSUE TITLE
Batman: Arkham Origins not showing all graphics settings

### ISSUE THREAD

**Issue by GitThisBugOff** [ValveSoftware/Proton#1604]
# Compatibility Report
- Name of the game with compatibility issues: Batman: Arkham Origins
- Steam AppID of the game: 209000

## System Information
- GPU: <RX 480>
- Driver/LLVM version: <Mesa 18.1.7>
- Kernel version: <4.15.0.34>
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 3.7-6 Beta

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

[steam-209000.log](https://github.com/ValveSoftware/Proton/files/2415901/steam-209000.log)

## Symptoms 
Graphics settings do not go higher than 'normal' options. 

These are the settings as seen in-game with my system: 
![20180925114537_1](https://user-images.githubusercontent.com/39744079/46026159-a3d59880-c0b8-11e8-8526-e60552a766c9.jpg)

This is what it's supposed to look like at Max settings on a Windows system.
[
![image](https://user-images.githubusercontent.com/39744079/46026017-44778880-c0b8-11e8-8412-a1ad6e3ae257.png)
](url)

## Reproduction
Download and run the game as normal.

**Comment by kisak-valve** [comment]
Hello @GitThisBugOff, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1385#issuecomment-424415683.
