### ISSUE TITLE
Restore Windows Games through the Backup & Restore Tool

### ISSUE THREAD

**Issue by HadetTheUndying** [ValveSoftware/Proton#1609]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
You can currently backup your games installed using Steam Play but cannot Restore them through the Linux Client
## Justification [optional] 
This is a Major Oversight and hampers low bandwidth users that take advantage of the backup system as to not go over on their datacaps. I 
## Risks [optional]
None, this functionality should already be present it appears to be an oversight

## References [optional] 
Try Backing up a Windows Only Game in the Linux Client(It will allow you.) Now try restoring it. (It will not allow you to do so.)

**Comment by kisak-valve** [comment]
Hello @HadetTheUndying, this is an issue with the steam client rather than Proton itself, so I've transferred this issue to https://github.com/ValveSoftware/steam-for-linux/issues/5786.
