### ISSUE TITLE
Battlefield: Bad Company 2

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#1610]
# Whitelist Request
- Name of the game to be whitelisted:Battlefield: Bad Company 2
- Steam AppID of the game: 24960

## System Information
- GPU: RX 570 4GB
- Driver/LLVM version: 18.2.1/6.01
- Kernel version: 4.18.9-arch1-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/CrackedCrafterz/0b11a1642a77e8d0a6f0d1de6a736c9a):
- Proton version: 3.7-6 & 3.7-6 Beta also works

## I confirm:
- [ x] that pressing the `Play` button in the Steam client is sufficient.

## Issues
- No issues here

**Comment by kisak-valve** [comment]
Hello @CrackedCrafterz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/200#issuecomment-424840438.
