### ISSUE TITLE
AaAaAA!!! - A Reckless Disregard for Gravity (15520)

### ISSUE THREAD

**Issue by KorinFlakes** [ValveSoftware/Proton#1612]
## Whitelist Request
- Name of the game with compatibility issues: AaAaAA!!! - A Reckless Disregard for Gravity
- Steam AppID of the game: 15520

## System Information
- GPU: GTX 1060 (6gb)
- Driver/LLVM version: Nvidia 396.54
- Kernel version: Kernel version: 4.15.0-34
- [My System Info](https://gist.github.com/vikeyev/811fd811c070704bd996020db51913c6)
- Proton version: 3.7-6

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [X] that no workarounds other than the mentioned ones are necessary.

## Issues
- [X] I haven't experienced any issues.

**Comment by Ashleyz4** [comment]
Since this is a native game, I would assume there would be no issues created since there is no need for any.

**Comment by parkerlreed** [comment]
I thought "AaAaAA!!! For the Awesome" basically remade the original levels? That is on Linux natively.

**Comment by KorinFlakes** [comment]
Wouldn't know, I own it but I've never bothered to play For the Awesome...like half of my library lol.

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.
