### ISSUE TITLE
wine-staging 3.15 mouse patch

### ISSUE THREAD

**Issue by rawsh** [ValveSoftware/Proton#1620]
In several games, the mouse hits a invisible wall. These games are perfectly playable using newer wine versions, such as wine-staging 3.15 or later. I've experienced the bug in Darwin Project and No Man's Sky. https://github.com/wine-staging/wine-staging/tree/master/patches/winex11-mouse-movements

**Comment by aeikum** [comment]
This is tracked at #147 .
