### ISSUE TITLE
Grand Theft Auto: San Andreas (12120)

### ISSUE THREAD

**Issue by KorinFlakes** [ValveSoftware/Proton#1630]
# Compatibility Report
- Name of the game with compatibility issues: Grand Theft Auto: San Andreas
- Steam AppID of the game: 12120

## System Information
- GPU: GTX 1060 (6gb)
- Driver/LLVM version: Nvidia 396.54
- Kernel version: Kernel version: 4.15.0-34
- [My System Info](https://gist.github.com/vikeyev/811fd811c070704bd996020db51913c6)
- Proton version: 3.7-6

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-12120.log-Part_1](https://gist.github.com/vikeyev/b3aeffe0a1d119da7391dbe489f28dbd)
[steam-12120.log-Part_2](https://gist.github.com/vikeyev/5bb9b9ccce2d308f5919d28bbbb49965)
[steam-12120.log-Part_3](https://gist.github.com/vikeyev/f3a0c49a0ef1d70e7919dbc5e8022f43)

## Symptoms
The game itself appears to run perfectly. The only problem is the game locks up (crashing) quite often and I can't really figure out why. It first froze seconds after clicking the new game button. After restarting I was able to get a good half hour in before the game crashed again. The longest stretch I've managed was about an hour. But it only locks in between cutscenes (like when you walk into a red circle to accept a new mission, or when the game first starts) and never when you have control of the character.

If the crashing problem could be fixed then this game could easily be whitelisted.

**Comment by kisak-valve** [comment]
Hello @vikeyev, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/143#issuecomment-425422710.
