### ISSUE TITLE
[Whitelist] Sam & Max Season 3 (31220, 31230, 31240, 31250, 31260)

### ISSUE THREAD

**Issue by Zero86Sk** [ValveSoftware/Proton#1633]
# Whitelist Request
- Name of the game to be whitelisted: Sam & Max Season 3
- Steam AppID of the game: 31220, 31230, 31240, 31250, 31260

## System Information
- GPU:  GTX 1050 Ti
- Driver/LLVM version:  Nvidia driver 396.54
- Kernel version:  4.15.0-34
- Link to full system information report as [Gist](https://gist.github.com/): [Sytem Info](https://gist.github.com/Zero86Sk/d629f657c1ae861c36657cdf238a7765)
- Proton version: 3.7-7 beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

All 5 episodes run great. They all run on the same engine, so I put all 5 episodes in 1 reqiest.

**Comment by kisak-valve** [comment]
Found in the 2018-10-05 white list update.

**Comment by lucifertdark** [comment]
> Found in the 2018-09-05 white list update.

Where would one find that list?

**Comment by kisak-valve** [comment]
https://steamdb.info/app/891390/history/?changeid=5187653
