### ISSUE TITLE
Oblivion running at 20fps regardless of settings

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#1635]
# Compatibility Report
- The Elder Scrolls IV: Oblivion® Game of the Year Edition running at 20fps regardless of settings:
- 22330:

## System Information
- GPU: 1080ti
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.18.10
- Link to full system information report as [Gist](https://gist.github.com/buddicus/f985af9adae85af052bbffb3b6a6dab6):
- Proton version: 3.7-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When I launch the game the menu is fine, but when I enter a save or start a new game I get 20fps varying a little.
I have tried every variation of settings from absolute minimum to max and the game gets 20fps even at it's lowest resolution.

## Reproduction
The game does this every time I enter a save or start a new game.

**Comment by kisak-valve** [comment]
Hello @buddicus, this game is already being tracked at #718. Closing as a duplicate.

https://github.com/ValveSoftware/Proton/issues/718#issuecomment-417730093 sounds like what you encountered.
