### ISSUE TITLE
Cannot compile on Mac OS 10.13.6

### ISSUE THREAD

**Issue by mmmatthewm** [ValveSoftware/Proton#1640]
Hi all, 

Been trying to compile proton on Mac os ive had the issues the others have had but am now stuck on a new one that is not referenced. 

.....
    export XCODE_VERSION_MINOR=1000
    export XPCSERVICES_FOLDER_PATH=MoltenVK.framework/Versions/A/XPCServices
    export YACC=yacc
    export arch=undefined_arch
    export diagnostic_message_length=236
    export variant=normal
    /bin/sh -c /Users/matthew/Library/Developer/Xcode/DerivedData/MoltenVKPackaging-ggzcicabgweddwavtpspfnwquisk/Build/Intermediates.noindex/MoltenVK.build/Release/MoltenVK-macOS.build/Script-A93F47C91D7E389E002AF700.sh
Undefined symbols for architecture x86_64:
  "mvk::SPIRVToMSLConverter::convert(mvk::SPIRVToMSLConverterContext&, bool, bool, bool)", referenced from:
      MVKShaderModule::convert(mvk::SPIRVToMSLConverterContext*) in MoltenVK(MoltenVK-x86_64-master.o)
  "mvk::SPIRVToMSLConverter::setSPIRV(unsigned int const*, unsigned long)", referenced from:
      MVKShaderModule::MVKShaderModule(MVKDevice*, VkShaderModuleCreateInfo const*) in MoltenVK(MoltenVK-x86_64-master.o)
  "mvk::SPIRVToMSLConverterContext::alignUsageWith(mvk::SPIRVToMSLConverterContext const&)", referenced from:
      MVKShaderLibraryCache::getShaderLibrary(mvk::SPIRVToMSLConverterContext*, MVKShaderModule*, bool*) in MoltenVK(MoltenVK-x86_64-master.o)
      MVKShaderLibraryCache::findShaderLibrary(mvk::SPIRVToMSLConverterContext*) in MoltenVK(MoltenVK-x86_64-master.o)
      MVKShaderLibraryCache::merge(MVKShaderLibraryCache*) in MoltenVK(MoltenVK-x86_64-master.o)
  "mvk::SPIRVToMSLConverterContext::isVertexBufferUsed(unsigned int) const", referenced from:
      MVKGraphicsPipeline::getMTLRenderPipelineDescriptor(VkGraphicsPipelineCreateInfo const*) in MoltenVK(MoltenVK-x86_64-master.o)
  "mvk::SPIRVToMSLConverterContext::isVertexAttributeLocationUsed(unsigned int) const", referenced from:
      MVKGraphicsPipeline::getMTLRenderPipelineDescriptor(VkGraphicsPipelineCreateInfo const*) in MoltenVK(MoltenVK-x86_64-master.o)
  "mvk::SPIRVToMSLConverterContext::matches(mvk::SPIRVToMSLConverterContext const&) const", referenced from:
      MVKShaderLibraryCache::getShaderLibrary(mvk::SPIRVToMSLConverterContext*, MVKShaderModule*, bool*) in MoltenVK(MoltenVK-x86_64-master.o)
      MVKShaderLibraryCache::findShaderLibrary(mvk::SPIRVToMSLConverterContext*) in MoltenVK(MoltenVK-x86_64-master.o)
      MVKShaderLibraryCache::merge(MVKShaderLibraryCache*) in MoltenVK(MoltenVK-x86_64-master.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Create\ Dynamic\ Library /Users/matthew/Library/Developer/Xcode/DerivedData/MoltenVKPackaging-ggzcicabgweddwavtpspfnwquisk/Build/Intermediates.noindex/MoltenVK.build/Release/MoltenVK-macOS.build/Script-A93F47C91D7E389E002AF700.sh
(1 failure)

**Comment by podycust** [comment]
am getting the same on Mojave too

**Comment by Gcenx** [comment]
The version of MoltenVK won't build with Xcode10 you would need to replace it with a newer version, but that's not even the main problem you won't be compiling wine with Xcode 10 anyway.

Edit;
Actually you can compile wine with XCode10 it just requires the 10.13 SDK for the 32Bit portion of the compile.

**Comment by gen1321** [comment]
I guess this issue is duplicate. checkout this response and solution https://github.com/ValveSoftware/Proton/issues/108#issuecomment-429176539

**Comment by aaronfranke** [comment]
macOS support has been removed: https://github.com/ValveSoftware/Proton/commit/a84120449d8177fa40f3de729e55d238d3c24877

**Comment by nobodywasishere** [comment]
This issue should be closed due to the removal of macOS support
