### ISSUE TITLE
Proton doesn't sync save files in cloud

### ISSUE THREAD

**Issue by zvbarev** [ValveSoftware/Proton#1644]
Currently Proton doesn't sync save files in cloud. It wiil be very useful if Proton will sync with cloud. 
Also it will be perfect if sync can be between Windows and Linux saves.

**Comment by kisak-valve** [comment]
Hello @Sebastian1978, syncing cloud saves is handled by the steam client and not by Proton itself. Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5640.
