### ISSUE TITLE
Shantae and the Pirate's Curse - Crashes on launch

### ISSUE THREAD

**Issue by whitelilydragon** [ValveSoftware/Proton#1650]
# Compatibility Report
- Shantae and the Pirate's Curse
- AppID: 345820

## System Information
- AMD A10-7800 Radeon R7, 12 Compute Cores 4C+8G 
- Driver/LLVM version: 3.0 Mesa 18.0.5
- Kernel version: 4.15.0-34-generic
- Full System Report: https://gist.github.com/whitelilydragon/b996cb0fbc3c1615a08d1b0167bef34f#file-steam-system-information-9-30-2018

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

Steam Error Log:
https://gist.github.com/whitelilydragon/6f87ebf5ad57b5b2fefca69bd3a13bc7

## Symptoms
Crashes on launch with the following error window: D3d.cpp : D3D11CreateDevice() failed E_FAIL:

## Reproduction
Attempting to launch the game

**Comment by lodriguez** [comment]
You usually need Mesa 18.2 and LLVM 7 (for DXVK) to run most games.

**Comment by kisak-valve** [comment]
Hello @whitelilydragon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/982#issuecomment-425719152.

**Comment by whitelilydragon** [comment]
I'll consider upgrading my versions of MESA and LLVM, then, horstderheld! No amount of Googling was able to tell me why this error happens, so I appreciate the solution.

And thanks for the transferal, kisak. I wasn't aware of the "one issue report per unofficially supported game title"; will keep this in mind if I have any issues to post in the future.
