### ISSUE TITLE
Skyrim (72850) Script Extender (SKSE) (365720) fail to load

### ISSUE THREAD

**Issue by powerman** [ValveSoftware/Proton#1654]
# Compatibility Report
- Name of the game with compatibility issues: Skyrim with Skyrim Script Extender
- Steam AppID of the game: 72850 + 365720

## System Information
- GPU: GTX 560 Ti
- Driver/LLVM version: mesa-18.1.9, nvidia-drivers-390.87
- Kernel version: 4.9.74-unofficial+grsec
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/powerman/b5175e19343dc63389ba1bad8c5e5173
- Proton version: 3.7-6, 3.7-7 Beta

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

There are compatibility reports for both apps, but no one mention this specific issue.

[steam-72850.log](https://github.com/ValveSoftware/Proton/files/2431992/steam-72850.log)

## Symptoms

At a glance symptoms looks very similar to https://bugs.winehq.org/show_bug.cgi?id=43844 - any chance this year-old change wasn't merged to Proton yet?

## Reproduction

Install (using Steam) Skyrim, Skyrim Script Extender. Then manually install SkyUI mod from https://www.nexusmods.com/skyrim/mods/3863 by copying SkyUI.bsa and SkyUI.esp files into steamapps/common/Skyrim/Data/. Now start Skyrim, start new game, and you'll see error from SkyUI about absent Skyrim Script Externder (SKSE).

**Comment by kisak-valve** [comment]
Hello @powerman, we're using one issue report per unofficially supported game title, and this leans more to the SKSE side, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/170#issuecomment-425751729.

**Comment by ThePreviousOne** [comment]
I believe SkyUI can also be found in the steam work shop. But its actually simpler than that, when correctly started with SKSE their version number will be displayed in the bottom left of the screen
