### ISSUE TITLE
Unable to use steam play if linux game build exist

### ISSUE THREAD

**Issue by Inglebard** [ValveSoftware/Proton#1663]
Hi,

I would like to play Frozen synapse 2 on my linux computer.

Actually this game is only playable under windows but developers will build it under macOs/linux.

However, when I try to download the game, it download a linux build which is not exist (or at least not stable/finish/official) and so not working. I suppose developers are currently testing the game on linux and push a kind of test version on steam. 

I don't know if it's a bug or I don't know.

But It would be great if we can explicitly download a windows build even if a linux build exist.

**Comment by kisak-valve** [comment]
Hello @Inglebard, this feature request for the steam client rather than Proton itself and is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5638. Closing as a duplicate.
