### ISSUE TITLE
Dragon Age: Origins Ultimate (47810)

### ISSUE THREAD

**Issue by tr37ion** [ValveSoftware/Proton#1665]
# Compatibility Report
- Name of the game with compatibility issues: Dragon Age: Origins Ultimate
- Steam AppID of the game: 47810

## System Information
- GPU: GTX1070
- Driver/LLVM version: Nvidia 410.57
- Kernel version: 4.18.10-arch1-1-ARCH
- Proton version: 3.7-6

## I confirm:
- [✔] that I haven't found an existing compatibility report for this game.
- [✔] that I have checked whether there are updates for my system available.

## Symptoms
 1. Textures are low resolution (see #749) and shaders are broken if `Frambuffer Effects` is activated
 2. If switching to Desktop and back (Plasma 5.13.5) the mouse and keyboard input is broken.

I added this general report cause the other one #749is very specific and this one adds the mouse/keyboard issue, too.

**Comment by kisak-valve** [comment]
Hello @tr37ion, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/749#issuecomment-426090961.
