### ISSUE TITLE
Assetto Corsa (244210)

### ISSUE THREAD

**Issue by DougBeney** [ValveSoftware/Proton#1669]
# Compatibility Report
- Name of the game with compatibility issues: Assetto Corsa
- Steam AppID of the game: 244210

## System Information
- GPU: GTX 1050
- Driver/LLVM version: nvidia 396
- Kernel version: 4.15.0-36-generic
- Link to full system information report as [Gist](https://gist.github.com/DougBeney/1feb990102bcef2a1570b84351ea2b77)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[Proton Log Gist](https://gist.github.com/DougBeney/83bb8c6370f9b7f7638d7164e7b6b2b4)

## Symptoms 

Launched game, Steam shows running next to the game's title, then it disappears and nothing else happens. Nothing pops up on my screen except for the "Preparing to Launch Assetto Corsa Steam dialog.

## Reproduction

I am actually on a pretty fresh install I just did today. I used KDE Neon which is exactly the same as Ubuntu 18.04 or Kubuntu 18.04 except that it has a newer KDE version.

This should be reproducible on any Ubuntu 18.04 distribution.

Others' have had similar experiences and you can read about them on the unofficial Steam Compatibility Reports: https://spcr.netlify.com/app/244210

**Comment by kisak-valve** [comment]
Hello @DougBeney, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/148#issuecomment-426120798.

**Comment by DougBeney** [comment]
Thanks, @kisak-valve. Didn't see that one.
