### ISSUE TITLE
Middle-Earth TM: Shadow of War TM - Won't Start

### ISSUE THREAD

**Issue by ShannonVanWagner** [ValveSoftware/Proton#1671]
# Compatibility Report
- Name of the game with compatibility issues: Middle-Earth TM: Shadow of War TM
- Steam AppID of the game: 356190

## System Information
- GPU: GeForce GTX 950
- Driver/LLVM version: NVIDIA 396.54
- Kernel version: 4.15.0-34-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ShannonVanWagner/b47a9a4ee40737c62b721b978191a841
- Proton version: 3.7-7 Beta

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.
[steam-356190.log](https://github.com/ValveSoftware/Proton/files/2436411/steam-356190.log)

**Comment by ShannonVanWagner** [comment]
Middle-Earth: Shadow of Mordor - is native Linux port and is totally awesome and works like a champ. Would be nice to see Middle-Earth: Shadow of War work as well! Thanks for your efforts!

**Comment by lucifertdark** [comment]
Feral are working on the Native port of Shadow of War right now, I'm pretty sure it's being released toward the end of this month.

**Comment by HonkingGoose** [comment]
@lucifertdark What is your source on that? As far as I can see, there is no official news on a port for Shadow of War. 

There is already a port for the first Shadow of Mordor game, so it would make some sense for Feral to also work on the sequel...

I see no mention of Shadow of War on here:
https://www.feralinteractive.com/en/linux-games/
or here:
https://www.feralinteractive.com/en/news/?platform=linux
or here:
https://www.reddit.com/r/linux_gaming/search?q=shadow%20of%20war&restrict_sr=1&sort=new

Also @ShannonVanWagner there is already a report for Shadow of War, its in #135 
We only use 1 issue per unofficially supported game. So I think it would be best if you add your findings to issue #135 in a comment.

**Comment by lucifertdark** [comment]
@HonkingGoose put it down to a senior moment, I confused it with another game, apologies all round.

**Comment by kisak-valve** [comment]
Hello @ShannonVanWagner, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/135#issuecomment-426275577.
