### ISSUE TITLE
Please add a "Request Steam Play Compatibility" & "Notify me When this Game Works in Steam Play" buttons to all games in the store

### ISSUE THREAD

**Issue by ShannonVanWagner** [ValveSoftware/Proton#1673]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Justification [optional]  Just want to repeatedly buy some more good games that will work on my Linux machine.

**Comment by ghost** [comment]
https://steamcommunity.com/games/221410/announcements/detail/1475356649450732547
That feature might be the closest to "Request Steam Play Compatibility"

**Comment by tr37ion** [comment]
The intention is good. From a marketing perspective it is not so good idea to show mostly negative information of games not running on Steam. It might be something to add to dev's backend interface.

PS: Please don't use bold fonts often. This might be counter-productive to your intention. Keep your writing simple and lean on Github.

**Comment by HonkingGoose** [comment]
You can even filter your wishlist to only show Linux games, so you could just wishlist away, and then filter out the Windows games in the wishlist.

However: this breaks one of the intended usecases for a wishlist: indicating to others what games you would like to get as gifts. So this system isn't perfect as of yet.

I also found this, on the steam-for-linux tracker: ValveSoftware/steam-for-linux/issues/447

**Comment by kisak-valve** [comment]
Hello @ShannonVanWagner, this is a feature request for the Steam Store rather than Proton itself, so I've transferred this issue to https://github.com/ValveSoftware/steam-for-linux/issues/5809.
