### ISSUE TITLE
[Feature Request] - Support Controller Hotplugin

### ISSUE THREAD

**Issue by Brunfunstudios** [ValveSoftware/Proton#1675]
# Feature Request
Hi, I've been playing a lot of of Gta V since it works so great in proton. But once in a while my controller randomly shuts down and immediately reconnects. This wouldn't be a Problem in native games or even wine but proton doesn't pick the controller up again until a game restart. This is rather annoying having to restart every time you connect another controller or turned your steam controller on to late into the game start and so on.

I also tried TrackMania2, Nidhogg and the 2 working batman games and always the same behavior for new controllers although never got just disconnected like in gta.

Tested with 2 Steam Controllers and Xbox360.

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
The ability for proton to recognize new controllers during gameplay and give them to wine.
## Justification
I've tried hotpugin in a wine prefix and it did recognize new controllers during runtime.
So it seems that proton handles Controllers differently.

**Comment by Azelphur** [comment]
If it helps at all, you can work around this issue by using Moltengamepad. You can set it up to emulate an xbox 360 controller, and have your xbox 360 controller connect to that. I use wireless xbox controllers (8 of them) so it'd be a nightmare without it. Obviously would be nice to have a proper fix, but in the meantime Moltengamepad helps.

**Comment by Lucki** [comment]
Generally gamepad hotswap works and is supported through proton.

I've tested this by myself with Z55Z and others mentioned that it's working for sure with [yakuza kiwami 2 and dark souls remastered](https://discordapp.com/channels/277857463384932353/490220625764548609/679475165943562294).

So this seems to be somewhat game dependent where it shouldn't.
Now the really strange part is that I was able to get it working in GTA V by "calibrating" the newly plugged in gamepad in the ingame menu. I even was able to plug it in and out again without any problems and without another recalibration. **But** this only worked for that game sessions run time. After another game start I was unable to use the controller anymore. Even the "calibration" wasn't available anymore.

There's something wrong here and it looks this isn't really a feature request but a bug instead.

**Comment by aeikum** [comment]
Controller hotplugging is working pretty well these days, so I'm going to close this. If you find remaining problems, please report them on the game's issue. Note that some games do not support controller hotplugging, even on Windows, and there is nothing we can do about that.

**Comment by aod** [comment]
Hi there, I'm currently experiencing this problem with Rocket League. My PS4 controller will sometimes disconnect (due to an hardware issue) and after reconnecting it the game does not recognize the device, you'll have to restart the game. Is this the right thread to post this or should a separate issue be created?

**Comment by eathtespagheti** [comment]
I would like to point out that this it's still an issue with GTA V, which support hotplugging on Windows
