### ISSUE TITLE
"Ride game demo" not proceeding past the initial setting screen

### ISSUE THREAD

**Issue by Reddiiiee** [ValveSoftware/Proton#1678]
# Compatibility Report
- Name of the game with compatibility issues: Ride game demo
- Steam AppID of the game: 355660

## System Information
- GPU: GTX 750ti
- Driver/LLVM version: nvidia 384.130
- Kernel version: 4.4.0-135-generic
- Link to full system information report as [Gist](https://gist.github.com/Redneckita/43ebc7b4ebe33becc6c65f54f2ae78a7#file-gistfile1-txt)
- Proton version: 3.7-6 and 3.7-7 beta 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
I tried running the game demo and it did nothing beside downloading VC Redist for MS Windows and DX. Then i tried using Proton 3.7-6 and it showed me the initial setting screen but after clicking "OK") the game crashed. Same with Proton 3.7-7 beta.

## Reproduction
Launch the game on Ubuntu 16.04 (i have eOS Loki - based on Ubuntu 16.04).

**Comment by lucifertdark** [comment]
I can confirm this is not working. Results in Black Screen after the settings screen, has to be killed manually or it just sits there forever.
https://gist.github.com/lucifertdark/584c14275612e8e3c4a8070d428d8a02
[steam-355660.log](https://github.com/ValveSoftware/Proton/files/2439636/steam-355660.log)

**Comment by Reddiiiee** [comment]
Also tried after the recent update and with proton 3.7.8 beta without any result

**Comment by Reddiiiee** [comment]
After updating to elementary OS 18.04 the game worked fine!
