### ISSUE TITLE
The Elder Scrolls Legends (364470)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#1681]
# Compatibility Report
- Name of the game with compatibility issues: "The Elder Scrolls: Legends"
- Steam AppID of the game: 364470

## System Information
- GPU: GTX 760M
- Driver/LLVM version: nvidia 390.87 /  3.0 Mesa 18.1.8     
- Note: I run steam games through bumblebee, the system info of steam shows my other gpu chip, but the issue persists, regardless of which gpu I run it with.
- Kernel version: 4.9
- Link to full system information report as [Gist](https://gist.github.com/Deckweiss/3f35ab492b094418a5e05e661fa851c6):
- Proton version: 3.7-6

## I confirm:
- [✔] that I haven't found an existing compatibility report for this game.
- [✔] that I have checked whether there are updates for my system available.

[Proton Log](https://gist.github.com/Deckweiss/2fab92eb0d319154504c627f2e3b274d)

## Symptoms 
When I run the game it shows an Error prompt with: 
"Legends has encountered an error and must close.
A crash report named "Crash_2018-10-03-133856" has been generated. These files can be sent to Bethesda Softworks LLC for analysis. Would you like to open this folder now? Yes/No"

When I open the folder there is an error.log and a crash.dmp, but I cannot upload the dump here.
[error.log](https://gist.github.com/Deckweiss/5aee359e593b913e8c45b864e6cd00ea)

## Reproduction

Start The Elder Scrolls Legends through Steam Play

**Comment by kisak-valve** [comment]
Hello @Deckweiss, you may have better luck with nvidia 396.54 or newer.

Additionally, if dxvk is being used, then the game may be tripping over mesa/Intel/Haswell's incomplete vulkan implementation. You could try temporarily disabling intel vulkan support by moving `/usr/share/vulkan/icd.d/intel*` somewhere out of the way.

Also, there are some Proton [runtime options](https://github.com/ValveSoftware/Proton#runtime-config-options) you could try out.

**Comment by ghost** [comment]
I updated the nvidia driver to the suggested version and encountered this problem: https://github.com/ValveSoftware/Proton/issues/65

So I can't confirm if it works until optimus/ primusrun/ optirun is working for me
