### ISSUE TITLE
Tekken 7 - Does not start (389730)

### ISSUE THREAD

**Issue by alkazar** [ValveSoftware/Proton#1686]
# Compatibility Report
- Name of the game with compatibility issues: Tekken 7
- Steam AppID of the game: 389730

## System Information
- GPU: GTX 1080
- Driver/LLVM version: nvidia 396.54
- Kernel version: unknown (latest SteamOS beta)
- Link to full system information report as [Gist](https://gist.github.com/): cannot obtain from SteamOS
- Proton version: unknown (latest beta)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. (did not find a report of this error)
- [x] that I have checked whether there are updates for my system available.

## Symptoms
After starting the game, the error "DX11 feature level 10.0 is required to run the engine." is displayed. Clicking OK closes the game.

## Reproduction
1. start game
2. observe the error

## Notes
I am using the latest SteamOS beta (SteamOS 2.0 update 1:2.166), Steam client beta and Steam Play beta.

The game used to work perfectly until a week or so ago. As far as I could tell there were no updates to the game, proton, Steam OS, nor Steam at the time.

I tried validating the game data, re-downloading the game from scratch and deleting the compat files without success.

Steam support sent me here and advised me to file a bug report.

**Comment by kisak-valve** [comment]
Hello @alkazar, this issue is already being tracked at https://github.com/ValveSoftware/SteamOS/issues/652. Closing as a duplicate.
