### ISSUE TITLE
Where is the whitelist file for proton located?

### ISSUE THREAD

**Issue by romulasry** [ValveSoftware/Proton#1700]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

I would like to see the most up to date list of the whitelisted games but I am having trouble finding it. Anyone know?

Thanks in advance.

**Comment by martinpl** [comment]
https://steamdb.info/app/891390/info/
