### ISSUE TITLE
[Whitelist] STEINS;GATE (412830) 

### ISSUE THREAD

**Issue by raikirii** [ValveSoftware/Proton#1709]
# Whitelist Request
- Name of the game to be whitelisted: STEINS;GATE
- Steam AppID of the game: 412830

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 410.57
- Kernel version: 4.18
- Link to full system information report: [System Information](https://gist.github.com/raikirii/c9b96773709ac08a62f338cd22c4c016)
- Proton version: 3.7-6

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [X] that no workarounds other than the mentioned ones are necessary.

## Issues
- [X] I haven't experienced any issues.
- [X] There are no issues left open for this game.
- [X] Although I consider the gaming experience equal to Windows there are
      remaining issues: 
 - When Controller disconnects during gameplay a restart of the game is needed to register input of the controller again
 - Game has an unskippable launcher that minimizes BigPictureMode on launch

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.

**Comment by ghost** [comment]
On my system the audio is crackling under Proton 3.16-4 (selected by Valve testing), the problem goes away if I force the game to use Proton 4.2-7

**Comment by kisak-valve** [comment]
Hello @coltondrg, please open a new issue report with your system information included.
