### ISSUE TITLE
DOOM 2016 Requires update everytime steam loads

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/Proton#1712]
# Compatibility Report
- Name of the game with compatibility issues: DOOM
- Steam AppID of the game: 379720

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 410.57
- Kernel version: 4.18.12-arch1-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/231cdd8edd89900aafd4386b375eaee5010c3e90/gistfile1.txt
- Proton version: 3.7-7 Beta
- Happens on both steam and steam beta client.

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

When I start steam, DOOM always needs to download a 0 byte update before you can run it. I have already tried validating steam files twice. It happens on both steam-native and steam-runtime version. The game otherwise runs fine.

![2018-10-10_13-42](https://user-images.githubusercontent.com/425930/46761667-55b4bd80-cc92-11e8-8d97-f658107eb0cc.png)

**Comment by kisak-valve** [comment]
Hello @jazztickets, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5644. Closing as a duplicate.
