### ISSUE TITLE
In-Home Streaming Freezes

### ISSUE THREAD

**Issue by jardon** [ValveSoftware/Proton#1713]
# Compatibility Report

## System Information
- GPU: NVIDIA GTX 1060 6GB
- Driver/LLVM version: Nvidia 396.54
- Kernel version: 4.15.0-36
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/jardon/e272b1822905ae16badcd86622e72984
- Proton version: 3.7-7 beta (have had this issue since the initial release)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

I grabbed the log for Doom if that helps
[steam-379720.log](https://github.com/ValveSoftware/Proton/files/2467069/steam-379720.log)

## Symptoms 
I wouldnt really consider this to be a compatibility report for a single game but more of a compatibility report that spans multiple games.  When using In-Home Streaming from my desktop to another device, It appears that many proton games video stream freezes up on the client but are still running perfectly on the host.  

**Here are some details that I have observed:**
1. I have yet to find a native game that exerts these symptoms
2. Not every proton game has the problem
3. It appears that as I unfocus the window and focus on something else, the stream resumes as normal until refocused(although difficult to observe as many games minimize when unfocused).
4. Most of them start streaming very briefly before freezing up. Usually not getting past the opening game credits
5. I've tried just about every combination of streaming settings with little to no difference at all.

### Working
- Wolfenstein the New Order (201810)
- RAGE (9200)
- The Last Remnant (23310)

### Working with Issues
- Dark Souls Prepare to Die Edition (211420) - Has decent frames on the host but on the client its very poor even on streaming quality set to fast

### Borked
- Dark Souls 3 (374320)
- Doom 2016 (379720)
- Dragon Quest XI (742120)
- Metal Gear Solid V (287700)
- Prey (480490)
- Stick Fight (674940)
- The Witcher 3 (292030)
- Quantum Break (474960)
- Devil May Cry 4 SE (329050)
- Crysis 2 ME (108800)

I realize that maybe this needs to be broken up into multiple bug reports but I thought that it might be useful to have a view from above on this one.  I also realize that this may not even be a proton specific issue and may be in home streaming itself.  If there is anything that I can do to help, I'll gladly do what I can.  I mostly just dont know where to start.

## Reproduction

1. Configure Streaming host with the linked system specs
2. Configure network and steam link or other device
3. Install one of the borked proton streaming games
4. Try to stream it to steam link or other device on the network
5. Get really sad

**Comment by kisak-valve** [comment]
Hello @jardon, in home streaming is handled by the steam client rather than Proton itself, so I've transferred this issue to https://github.com/ValveSoftware/steam-for-linux/issues/5831.
