### ISSUE TITLE
Doom 2016 black screens on launch (379720)

### ISSUE THREAD

**Issue by Seeboooo** [ValveSoftware/Proton#1718]
# Compatibility Report
- Name of the game with compatibility issues: Doom 2016
- Steam AppID of the game: 379720

## System Information
- GPU: AMD RX 580 8g
- Driver/LLVM version: Mesa 18.2.2-1
- Kernel version: 4.19
- Link to full system information report as : [sys info](https://gist.github.com/Seeboooo/4a6025cb4659618774907d12145fbf87)
[inxi](https://gist.github.com/Seeboooo/f0e3e999fde4e9996e5dbbc8f11f124a)
- Proton version: 3.7 (installed seperately)

[steam-379720.log](https://github.com/ValveSoftware/Proton/files/2471222/steam-379720.log)

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game will go to a black screen with a frozen console. 2 CPU cores stay at 100% use but nothing works when using “+r_renderAPI 1”. Game crash when trying to launch using OpenGL (but an error message is reported in the console). 

## Reproduction
Launching the game.

-----------

Uninstalled vulkan-intel (64 and 32 bits versions), installed vcrun2015 and xinput as found on other threads but nothing worked. Doom never worked since proton was launched, but I've waited a few patched to see if something would change but it didn't.

![screenshot_2018-10-11_20-01-20](https://user-images.githubusercontent.com/30348548/46842731-4706fd00-cd9d-11e8-88d0-f82f5ee148d4.png)

**Comment by LeJimster** [comment]
There was an update to Doom that broke mesa support.  Can't remember exactly what version it was fixed on.

I would suggest you try installing the latest mesa-git.  The easiest way is to use this repo:

https://wiki.archlinux.org/index.php/unofficial_user_repositories#mesa-git

Then make sure you have everything for Vulkan to work correctly.

```
vulkan-radeon-git
lib32-vulkan-radeon-git
lib32-vulkan-icd-loader
vulkan-icd-loader
xf86-video-amdgpu-git
mesa-git
lib32-mesa-git
```
Also doesn't hurt to have the latest LLVM
```
llvm-libs-svn
lib32-llvm-libs-svn
```
All available from the same repo linked above.



I thought the fixes had already been backported to 18.2...  But maybe they haven't yet.  This should get you up and running, no extra workarounds needed for Doom.

**Comment by LeJimster** [comment]
@Seeboooo I managed to replicate your issue running `Steam (Native)`.  To get Doom working you need to be running `Steam (Runtime)`.  Have fun =)

**Comment by Seeboooo** [comment]
> @Seeboooo I managed to replicate your issue running `Steam (Native)`. To get Doom working you need to be running `Steam (Runtime)`. Have fun =)

Uninstalling steam-native to use steam-runtime (without removing steam-native dependencies) worked using +r_renderAPI 1 launch options (no issue with intro videos). 

Only thing is the fps counter disappear once I load a game (it's there when I start and I'm in the menu, but once I start playing it disappear).

Thanks @LeJimster for the tip. 

(mesa is still 18.2.2, dxvk received an update since first post).

**Comment by LeJimster** [comment]
@Seeboooo you can always enable the "Performance Metrics" to show your FPS.
Select **Campaign** > **Game Slot** > **Settings** > **Advanced** > **Show Performance Metrics** (it's at the bottom)

**Comment by Seeboooo** [comment]
@LeJimster good to know, thanks. It's not a big deal for me, but I was pointing it out in case it was related to my software version only (the steam fps counter disappearing once you load your saved game).
