### ISSUE TITLE
Dark Souls: Prepare To Die Edition, No in-game video playback support

### ISSUE THREAD

**Issue by Rabcor** [ValveSoftware/Proton#1723]
# Compatibility Report
- Dark Souls: Prepare To Die Edition
- 211420

## System Information
- Proton version: 3.7.8

## Symptoms 
- In-Game videos do not work.
- Dsfix does not work.

## Solutions
- In-Game videos work with windows media player 9 (wmp9), however I had issues getting it to install on a 64 bit prefix (and therefore problems installing it on proton); it's also possible it requires devenum.
- DSFix works if 'dinput8' library support is added. (Can be done via winecfg as a workaround)

Besides these two points, the game runs smoothly on appropriate hardware/driver configurations.

**Comment by kisak-valve** [comment]
Hello @Rabcor, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1319#issuecomment-429484411.
