### ISSUE TITLE
UE4 / Nvidia - What remains of Edith Finch / Tekken 7 - dxvk.conf ignored

### ISSUE THREAD

**Issue by darkpumpkins** [ValveSoftware/Proton#1729]
# Compatibility Report
- Name of the game with compatibility issues: What remains of Edith Finch
- Steam AppID of the game: 501300

## System Information
- GPU: GTX 970
- Driver/LLVM version: 396.54.05
- Kernel version: 4.15.0-38-generic
- Link to full system information report as [Gist](https://gist.github.com/):
[configSteam.txt](https://github.com/ValveSoftware/Proton/files/2475670/configSteam.txt)
- Proton version: 3.16-1beta
- OS : Ubuntu 18.04.1 LTS
- Desktop : gnome 3.28.2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Proton log :
[steam-501300.log](https://github.com/ValveSoftware/Proton/files/2475674/steam-501300.log)

## Symptoms 
Since i switched from proton "3.7-8" to "3.16-1beta" the dxvk.conf file that i put next the binary of the game seems not longer efficient. UE4 games as Tekken 7 or What remains of Edith Finch does run at something like 20fps without the fake graphic card operation with the dxvk files ( nvapi issue from what i understood ). With the dxvk file next to the binary, i can't reach 60fps on most situation on the both games.

## Reproduction
Switch to proton 3.16-1beta and launch the game with an nvidia card.

**Comment by doitsujin** [comment]
Does it work if you set the `DXVK_CONFIG_FILE` env var to the absolute path to your configuration file?

**Comment by darkpumpkins** [comment]
@doitsujin Yes ! In both Tekken 7 or What remains of Edith Finch it solved the issue.
Tekken 7 goes to 40 - 45 fps to 60 fps 
WROEF goes to 20fps to 60fps.

**Comment by dragonfly-lover** [comment]
@doitsujin i'm not enough skilled to test this workaround. Can you explain It to me extensively? I have the same issue in UE4 games. Also, i thought nvapi was patched by wine 3.16 but maybe the patch is yet in the staging branch.

**Comment by darkpumpkins** [comment]
@dragonfly-lover  create a file named dxvk.conf that contains : 
dxgi.customDeviceId = E366
dxgi.customVendorId = 1002

Into steam add to your game launch option
DXVK_CONFIG_FILE=path_to_your_dxvk_file_without_space %command%
