### ISSUE TITLE
DXVK no longer working on SteamOS with Proton 3.16-1 Beta

### ISSUE THREAD

**Issue by dubigrasu** [ValveSoftware/Proton#1730]
### Compatibility Report
- All DX11 games using DXVK are affected

### System Information
- GPU: AMD Radeon HD 7970
- Driver/LLVM version: 3.1 Mesa 18.1.6, LLVM 7.0.0
- Kernel version: 4.16.0-0.steamos2.1-amd64
- Link to full system information report: https://gist.github.com/dubigrasu/28dcfba4e5dc1e3d4863b7d7bcfe098b
- Proton version: 3.16-1 Beta

### I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

#### From the log file:
```
59892.103:0008:0009:err:module:load_builtin_dll failed to load .so lib for builtin L"d3d11.dll": /media/steam/BIGSTEAM/steamapps/common/Proton 3.16/dist/lib/wine/dxvk/d3d11.dll.so: symbol _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

59892.282:0008:0009:err:module:load_builtin_dll failed to load .so lib for builtin L"dxgi.dll": /media/steam/BIGSTEAM/steamapps/common/Proton 3.16/dist/lib/wine/dxvk/dxgi.dll.so: symbol _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

#### Symptoms: 
All DX11 games using dxvk are not starting, or reverting to DX9. From the log above I take it that the new native dxvk libraries were compiled against a newer libstdc++.so.6 than the one SteamOS provides?
```
steam@steamos:~$ strings /usr/lib/i386-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_DEBUG_MESSAGE_LENGTH
steam@steamos:~$
``` 
The libstdc++.so.6 provided by the steam-runtime is newer (and I am using the steam-runtime):
```
steam@steamos:~$ strings /home/steam/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_DEBUG_MESSAGE_LENGTH
steam@steamos:~$ 
```
But when grepping for the specific symbol mentioned in the log:
**_ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE**
in all libstdc++.so.6 files on my system, it couldn't be found.

 Reverting Proton to 3.7-8 restores DXVK functionality.

#### Reproduction: 
Switch to Proton 3.16-1 Beta and try starting any DX11 game.

**Comment by GloriousEggroll** [comment]
confirming same problem here on Arch using steam-runtime, steam-native works properly (using arch native libraries). Manually installing the latest dxvk release to proton works as a workaround as well.

**Comment by garpu** [comment]
Same issue, here, with Slackware 14.2. 3.7-8 works fine.  Did some other requirement change?

**Comment by LeJimster** [comment]
In the release notes for [3.16-1](https://github.com/ValveSoftware/Proton/commit/93bfce4869f854bb2d3e24310ff0c59e67737b4d)

> - DXVK is now built as a native Linux library, which may give a small performance boost, and should make debugging easier for DXVK and driver developers.

**Comment by dubigrasu** [comment]
@garpu 
> Same issue, here, with Slackware 14.2. 3.7-8 works fine. Did some other requirement change?

The difference is that previously Proton used DXVK compiled as Windows DLL files, while now they are native Linux libraries (like the d3d11.dll.so and dxgi.dll.so files you can see in the log file posted above).
I see that Slackware 14.2 is about two years old, so in the same boat as SteamOS in term of outdated libraries.

**Comment by GloriousEggroll** [comment]
@dubigrasu to clarify, steam-native works fine on arch, steam-runtime does not. (steam-runtime uses steam's runtime libraries instead of arch's native libraries)

**Comment by dubigrasu** [comment]
@GloriousEggroll 
Is interesting that the libstdc++.so.6 from the steam-runtime should work (?):
```
steam@steamos:~$ strings /home/steam/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_DEBUG_MESSAGE_LENGTH
steam@steamos:~$ 
```
I see that GLIBCXX_3.4.21 is present in the libstdc++.so.6 file provided by the steam-runtime.
Not sure what's going on (I am using the steam-runtime).

Edit: Never mind, the symbol mentioned in the log: _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE is not present in my libstdc++.so.6 files.

**Comment by ghost** [comment]
> @garpu
> 
> > Same issue, here, with Slackware 14.2. 3.7-8 works fine. Did some other requirement change?
> 
> The difference is that previously Proton used DXVK compiled as Windows DLL files, while now they are native Linux libraries

This in itself is backwards. If compiling it differently broke Steam OS because its not Windows then all Linux distros are not Windows either lol.

That's just something they cited in the changelog.

**Comment by garpu** [comment]
Edit:  To answer my own question, STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1 is a workaround for now. (like mentioned upthread.)

**Comment by romulasry** [comment]
Looks like they are compiling with a newer version of ibstdc++.so.6 on DXVK than SteamOS supports.

**Comment by dubigrasu** [comment]
OK, since I'm not gonna muck around with the older libstdc++.so.6 files from my system, as a temp solution I just "updated" the steam-runtime with newer ones from Ubuntu 18.04.
Everything working now, but of course waiting for a proper fix from Valve.

**Comment by meowmeowfuzzyface** [comment]
@dubigrasu Can you detail how you did this?

**Comment by kode54** [comment]
This may explain #1570 still being broken even though it should be fixed by the new 0.9.0 (or relevant Git revision) DirectX 11 Stream Output -like functionality that is now available. Well, by all accounts, I assume it's a newer revision fix, since wine-staging 3.15 also fixed the graphics in that game.

**Comment by aeikum** [comment]
Thanks for reporting and the diagnosis. Will get a fix for this ASAP.

**Comment by dubigrasu** [comment]
Tested again with Proton 3.16-2 and the issue is solved. Thank you.
As far as I can tell, this can be closed.

**Comment by garpu** [comment]
Everything works great on my end, too! Many thanks!

**Comment by aeikum** [comment]
Thanks again for reporting, and for retesting.
