### ISSUE TITLE
Dirt 3 Complete Edition (321040)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#1734]
# Whitelist Request
- Name of the game to be whitelisted: Dirt 3 Complete Edition
- Steam AppID of the game: 321040

## System Information
- GPU: GTX 750 2 GB
- CPU: Intel Core 2 Quad Q9550 2.83 Ghz
- Driver/LLVM version: NVIDIA Vulkan 396.54.09, works too on 396.54 stable release
- Kernel version: Liquorix 4.18
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kassindornelles/a3f9c31a31b5b6cef5be3d23254b7e08
- Proton version: 3.16-1 Beta

Tested on Antergos Linux, Ubuntu 18.04.1 and Elementary OS. in all of this distros works out of the box.

## I confirm:
- that pressing the `Play` button in the Steam client is sufficient.
- that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are **not necessary** to run the game.
-  that **no workarounds are necessary**
- Performance is great.

## Issues
- I haven't experienced any issues.

**Comment by kisak-valve** [comment]
Hello @kassindornelles, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/773#issuecomment-429583200.

**Comment by jm2** [comment]
Just as a heads up, this game is now failing in both Linux and Windows because WINE recently removed it's built-in OpenAL library, and DiRT 3 for whatever reason doesn't include it as an installation prerequisite.
