### ISSUE TITLE
Elder Scrolls Online not Launching

### ISSUE THREAD

**Issue by spiritstr** [ValveSoftware/Proton#1736]
# Compatibility Report
- The Elder Scrolls Online
- Steam AppID of the game: 306130

## System Information
- GPU: GTX 1070
- Driver/LLVM version: Nvidia 396.54.05
- Kernel version: 4.15.0-36
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 3.16-1

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Log doesn't work.
https://gist.github.com/spiritstr/9a7bf9d881ddede89691950a7fa49a78

## Symptoms 
Game not launching, i've just installed Steam setup the steamplay for both 3.7-8 and 3.16-1 but they are not working, the game doesn't launch and there's no log.

**Comment by kisak-valve** [comment]
Hello @spiritstr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/556#issuecomment-429628493.
