### ISSUE TITLE
xbox one elite no longer working on SteamOS with Proton 3.16-1 Beta 

### ISSUE THREAD

**Issue by Ichinix** [ValveSoftware/Proton#1746]
# Compatibility Report
- Name of the game with compatibility issues:Final Fantasy XIV
- Steam AppID of the game:39210

## System Information
- GPU:RX 580
- Driver/LLVM version: Mesa 18.2.2 LLVM 7.0.0
- Kernel version: 4.18.12-arch1-1-ARCH
- Proton version: Proton 3.16-1 Beta 

In FFXIV the xbox one elite controller connected via USB is no longer working, It was working with Proton 3.7-8.
When i switch back from proton 3.16-1 beta to proton 3.7-8 the controller input works again.
Personally i think this is due to Wine as i had the same on a plain FFXIV install (But i initially thought it was due to a kernel/edev update), although i have no idea where to start troubleshooting. I was hoping to get some help here.

The USB is recognized by Wine via the wine control panel, even in game i see the controller mentioned. But no input is registered when i try to configure the controller in the game.

Many Thanks,

Tommy

**Comment by alasky17** [comment]
Could you please retest this with the latest Proton (3.16-3)?  The xbox one elite controller is working for me in a very similar test environment with the same game.  

Also, did you have to do any special configuration to get FFXIV working with Proton?

**Comment by Ichinix** [comment]
Once im back at the hotel i will surely test it.
Only "special" configuration in order to get FFXIV working was manually install DXVK on the prefix and corefonts.
Besides editing the FFXIV conf file of the game.

**Comment by Ichinix** [comment]
Just tested it with the new 3.16-4 beta and all is working as a charm, gosh i love this version xD

Many many thanks
