### ISSUE TITLE
How v-sync is implemented in Proton?

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#1750]
As I know, Steam Proton using DirectX to Vulcan convert. But how it do v-sync? I can't find any information about Vulkan and V-Sync on linux.

**Comment by Rabcor** [comment]
I think it generally just does what the in-game settings tell it to if that's what you're referring to... 

If you want more details you'll have to look into DXVK (for DX10/11 games) and how Wine implements Vsync in DX9 and below games.

**Comment by justeff** [comment]
Vsync leads to a crash in Rome 2 Total War.
