### ISSUE TITLE
Deep Rock Galactic doesn't start anymore

### ISSUE THREAD

**Issue by DerBunman** [ValveSoftware/Proton#1751]
# Compatibility Report
- Name of the game with compatibility issues: Deep Rock Galactic
- Steam AppID of the game: 548430

## System Information
- GPU: GTX980ti 
- Driver/LLVM version: 396.54
- Kernel version: 4.18.0
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/DerBunman/2cc98b29464caf7585d65fddd635908f
- Proton version: 3.16-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-548430.log](https://github.com/ValveSoftware/Proton/files/2479907/steam-548430.log)

## Symptoms 
The game wont start since updating to 3.16-1.

It only displays the (non fullscreen) splash screen, after that the screen goes black and the game crashes back to desktop.

The game worked fine with 3.7-8 after installing xact and raising ulimits as described here:
https://github.com/ValveSoftware/Proton/issues/284

## Reproduction
Start the game with proton 3.16-1 enabled.

**Comment by kisak-valve** [comment]
Hello @DerBunman, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/284#issuecomment-429953097.
