### ISSUE TITLE
WWE 2k19 no character models (817130)

### ISSUE THREAD

**Issue by shanefagan** [ValveSoftware/Proton#1752]
# Compatibility Report
- Name of the game with compatibility issues: WWE 2k19
- Steam AppID of the game: 817130

## System Information
- GPU: RX480
- Driver/LLVM version: 18.3~git1810151930.2241be~oibaf~c
- Kernel version: 4.18.10
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/shanefagan/e853b4e9dbcef52cc7230cfa2fcd2063
- Proton version: 3.16-1 Beta

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

[steam-817130.log](https://github.com/ValveSoftware/Proton/files/2480229/steam-817130.log)

## Symptoms 

No character models loaded in the game. Other parts of the game loaded, belts, character picking menus, music, commentary. The bit that is missing is the gameplay itself really.

## Reproduction

You need no esync turned switch to run without crashing. Then it works fine after that. Easiest way to reproduce is going to benchmarks in options but also opening a one vs one game in the play section. Open a match and you will see physics going on, match loaded, no characters.

**Comment by shanefagan** [comment]
Update on this, the characters are loading as of the most recent beta update to Proton (3.16-4). If esync is disabled in the config for the game this could be whitelisted. @kisak-valve should I make a whitelist request with the suggestion and close this one?

**Comment by lucifertdark** [comment]
If you do anything other than hit the play button to run a game that _Should_ bar it from being White Listed.

**Comment by shanefagan** [comment]
@lucifertdark the only thing it needs is a config to disable esync. That is the only crasher it has. No other changes needed. EDIT: I'm sure they can have game specific settings like disabling esync and still whitelist it, to answer your comment
