### ISSUE TITLE
All 3 Dark Souls games crashing on launch since 3.16 update

### ISSUE THREAD

**Issue by meowmeowfuzzyface** [ValveSoftware/Proton#1754]
- Name of the game with compatibility issues: Dark Souls PTDE, Dark Souls II Scholar of the First Sin, and Dark Souls III
- Steam AppID of the game: 211420, 335300, and 374320

- GPU: Radeon Fury X
- Driver/LLVM version: mesa 18.3.0-devel from Padoka PPA, LLVM 8.0.0
- Kernel version: 4.15.0-36-generic
- Link to full system information report: [Gist](https://gist.github.com/meowmeowfuzzyface/4012884daebfbf3f2aecd3606647f33d)
- Proton version: 3.16 and 3.7-8

[steam-211420.log](https://github.com/ValveSoftware/Proton/files/2480642/steam-211420.log)
[steam-335300.log](https://github.com/ValveSoftware/Proton/files/2480643/steam-335300.log)
[steam-374320.log](https://github.com/ValveSoftware/Proton/files/2480644/steam-374320.log)

Description:
All 3 games were working perfectly with 3.7-8 until the 3.16 update.  Switching back to 3.7-8 does not solve this crash.  The behavior is the same for both versions.

Since the update, Dark Souls PTDE, Dark Souls II Scholar of the First Sin, and Dark Souls III all crash on launch.  Other DX11 games are working fine with DXVK (Witcher 3, Skyrim SE, Killing Floor 2).

Oddly, Dark Souls II and III do not crash if they are minimized (using alt + pgdn).  Upon maximizing, they are stable if there is no input.  If I press any button, the game crashes after one or two seconds.  Dark Souls PTDE crashes even when minimized.

Things I have tried:
Using the launch option for WINED3D11 or NO_D3D11.
Using the -fullscreen launch option.
Deleting the WINE prefix.
Verifying integrity of the game files.
Disabling the compositor.

Reproduction:
For all 3 games:  Launch the game normally.  A window will pop up and crash without displaying anything.

For Dark Souls 2 and 3: Launch the game and immediately minimize the window.  The game will launch normally in the background.  Upon maximizing the window, press any button.  The game will crash after 1-2 seconds.

**Comment by kisak-valve** [comment]
Hello @meowmeowfuzzyface, we're using one issue report per unofficially supported game title. Feel free to add this to the existing issue reports (#1319, #137, #478).
