### ISSUE TITLE
GTA V - very small issue with Proton 3.16-1 beta

### ISSUE THREAD

**Issue by fls2018** [ValveSoftware/Proton#1761]
Using the latest beta version of Proton there appears to be a small but noticeable white dot in the cut scenes, I rolled back to 3.7.8 and the issue disappeared. I have no idea what this might be other than maybe related to the in game cursor.

## System Information
- GPU: GTX 1070
- Driver/LLVM version: 396.54.09
- Kernel version: 4.18.12-1
- Proton version: 3.16-1 beta

**Comment by kisak-valve** [comment]
Hello @fls2018, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-430240275.
