### ISSUE TITLE
Steamplay / Proton stopped working after updating Manjaro Linux

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/Proton#1762]
Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/5845.
@germangoergs posted on 2018-10-16T19:01:46:

#### Your system information

* Steam client version: Oct 13 2018
* Distribution: Manjaro 18-rc
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

about 2 months ago Valve added the compatibility layer Proton to Steamplay to make Windows games run under Linux.

When I heard about it, I tried it instantly and for example No Man's Sky was one of the titles that worked without any problems.

But since a few weeks it is no longer possible for me to start No Man's Sky nor other games with Steam Play / Proton.
There is neither a message that the game is running with Steam Play, nor is Steam installing the game, as previously displayed at every game start.

I have already de-installed and re-installed the Steam Client several times, as well as the games, and I have switched between the Proton versions multiple times, enabled and disabled it, and deleted the Proton/games specific files in the Steam Games installation folder.

I already found out that an update broke it, since I recovered an older version of Manjaro (17.1.12) and Steam and it worked again - I updated and it's broken again.

But now I don't know how to solve this problem without keeping the system not up-to-date.

I don't get an error message when I try to start a game, I just get a message that the game is running for about half a second until nothing happens and nothing else is displayed in the Steam client.

I have attached my system information.

Thank you very much for your support!

#### Steps for reproducing this issue:

1. Update Manjaro to 18-rc
2. Open Steam
3. Try to start a game via Proton

#### System information:
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4200 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.18.12-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12001000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2018-09-03

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1080/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 410.57
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1b80
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  3840 x 2160
    Desktop Resolution: 5760 x 2160
    Primary Display Size: 34.57" x 19.09" (39.49" diag)
                                            87.8cm x 48.5cm (100.3cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 8192 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  24049 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Total Hard Disk Space Available:  114656 Mb
    Largest Free Hard Disk Block:  46467 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @germangoergs, this issue should also be brought to the attention of your distro's package maintainer for steam.

**Comment by TobiPeterG** [comment]
@kisak-valve Yeah, sure, thank you. :)

**Comment by Rabcor** [comment]
@germangoergs Here you go https://forum.manjaro.org/c/technical-issues-and-assistance

What are you doing with RC kernel anyways? You shouldn't use an RC kernel for day to day use, it's basically like a late beta.

**Comment by TobiPeterG** [comment]
@Rabcor Thanks for the link, it's Manjaro 18-rc (guess that means "release candidate, since Manjaro 18 wasn't released yet, but my system still updated to it lol), I'm on "normal" kernel 4.18.

But thanks for the advice. :D ;)

**Comment by aeikum** [comment]
If you run Steam from a terminal, do you get any obvious error messages in the output?  Do you have python3 available?

**Comment by TobiPeterG** [comment]
@aeikum Wow man, thanks for your advice! :)

Found out that I didn't have permissions to write on the partition on which I have my steam games, since I configured auto mount options wrong. 😂

Thank you very much.

Can I close this thread somehow?

**Comment by kisak-valve** [comment]
Closing per the last comment.
