### ISSUE TITLE
The proton_dist.tar.gz is not created by make install

### ISSUE THREAD

**Issue by ernado** [ValveSoftware/Proton#1764]
Seems like the `proton_dist.tar.gz` is expected in `compatibilitytools.d/proton-localbuild/`, but is not created.

Current workaround is to create it by yourself:
In ~/proton/mybuild/dist/**dist**
```bash
tar -cvzf \
  ~/.local/share/Steam/compatibilitytools.d/proton-localbuild/proton_dist.tar.gz .
```

**Comment by aeikum** [comment]
In theory this shouldn't be needed, since it should provide a dist/ folder with everything already unpacked. However this path isn't very well tested, so there could be a problem with it. What error were you seeing when no tarball is present?

**Comment by ernado** [comment]
I was unable to start Proton, and there were some errors from python somewhere in `/tmp/dumps/` folder.

But currently I can't reproduce it, so I'll close that ticket for now.
