### ISSUE TITLE
Proton 3.16 folder is empty

### ISSUE THREAD

**Issue by Saroufim** [ValveSoftware/Proton#1767]
The steam client displayed 3.16.2 as an available proton beta. However, games won't launch and the corresponding folder in ~/steamapps/common is empty. What can be done to redownload the release?

**Comment by kisak-valve** [comment]
Hello @Saroufim, does verifying the game files of any game using Proton help?

**Comment by Saroufim** [comment]
Unfortunately not,  it finds no errors and doesn't download Proton 3.16.2

**Comment by LeJimster** [comment]
Try deleting the Proton 3.16 directory, switch to an older Proton, restart client, switch back to 3.16 and restart client.  If it still doesn't download, try verifying the game files of a steamplay title as mentioned above.

I would hold off a bit though, 3.16-2 has a performance regression and I'm sure they will be release a new version soon.

@Saroufim 3.16-3 is out now, I would give that a try.

**Comment by Saroufim** [comment]
An update for a game downloaded proton with it.
