### ISSUE TITLE
Elex unplayable with Steam Controller

### ISSUE THREAD

**Issue by ekkia** [ValveSoftware/Proton#1769]
# Compatibility Report
- Name of the game with compatibility issues :Elex
- Steam AppID of the game: 411300

## System Information
- GPU: GTX 970
- Driver/LLVM version: Nvidia 396.54 
- Kernel version: 4.15.0
- Proton version: 3.7.8 & 3.16.2-beta

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

Opted-in Controller Mask for AppId 411300: 2
[1017/205211.625465:INFO:crash_reporting.cc(239)] Crash reporting enabled for process: renderer
Loaded Config for Local Selection Path for App ID 411300: /home/user/.steam/steamapps/workshop/content/241100/1175409549/860610936971543001_legacy.bin
[411300]Non-Steam Controller Configs Enabled: 1
GameAction [AppID 411300, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 411300, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 411300, ActionID 1] : LaunchApp changed task to ProcessingShaderCache with ""
GameAction [AppID 411300, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 411300, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 411300, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 411300, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 411300 "", ProcID 5525, IP 0.0.0.0:0
Loaded Config for Local Selection Path for App ID 411300: /home/user/.steam/steamapps/workshop/content/241100/1175409549/860610936971543001_legacy.bin
>>> Adding process 5525 for game ID 411300
GameAction [AppID 411300, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/user/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 411300, ActionID 1] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/user/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 5526 for game ID 411300
>>> Adding process 5527 for game ID 411300
>>> Adding process 5528 for game ID 411300
>>> Adding process 5529 for game ID 411300
>>> Adding process 5531 for game ID 411300
>>> Adding process 5534 for game ID 411300
>>> Adding process 5536 for game ID 411300
>>> Adding process 5539 for game ID 411300
>>> Adding process 5548 for game ID 411300
>>> Adding process 5553 for game ID 411300
>>> Adding process 5569 for game ID 411300
Game update: AppID 411300 "", ProcID 5529, IP 0.0.0.0:0
Installing breakpad exception handler for appid(gameoverlayui)/version(20181013004717)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
[1017/205309.185321:INFO:crash_reporting.cc(239)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
OnFocusWindowChanged to game window type: AppID 411300, 411300
Controller 4 Gamepad With Camera Controls uses xinput : true
Loaded Config for Local Selection Path for App ID 411300: /home/user/.steam/steamapps/workshop/content/241100/1175409549/860610936971543001_legacy.bin
Controller 4 Gamepad With Camera Controls uses xinput : true
OnFocusWindowChanged to window type: k_nGameIDControllerConfigs_Desktop, AppID 413080
Controller 4 Gamepad With Camera Controls uses xinput : true
Loaded Config for Local Selection Path for App ID 413080: /home/user/.steam/steamapps/workshop/content/241100/650764041/controller_configuration.vdf
Controller 4 Gamepad With Camera Controls uses xinput : true
Game removed: AppID 411300 "", ProcID 5529 
JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments

## Symptoms 

If Steam Controller is plugged via USB, game hangs with black screen after show inital 2 logo videos.
Without controller the game runs fine.

**Comment by kisak-valve** [comment]
Hello @ekkia, we're using one issue report per unofficially supported game title, and you've already mentioned this at https://github.com/ValveSoftware/Proton/issues/855#issuecomment-430432010.

Closing in favor of the existing issue report.
