### ISSUE TITLE
General question about the building process for end-users.

### ISSUE THREAD

**Issue by roadapathy** [ValveSoftware/Proton#1772]
I hope this is the correct place for this sort of question.

Can a somewhat basic guide be added for Ubuntu-based distributions since this is the most popular Steam Linux OS? I would write one myself but I haven't gotten Proton to build fully yet. Close!

The guide provided is a great start, especially for Debian, but it missed its largest target audience, which would be the Ubuntu folks. I'm on Ubuntu after trying to use MX LInux and Manjara. Ubuntu 18.04 just works better with Steam and with compiling the libraries (and Kernel) needed to run games at their peak performance in Linux. I really think this is why most Steam Linux users are running Ubuntu.

Thank you!

**Comment by roadapathy** [comment]
Here are the Steam for Linux statistics. Ubuntu is the most used and has been rising:

https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam?platform=linux

**Comment by roadapathy** [comment]
I posted this where it would be seen, it was locked. Now I post it here where it seems it should be posted and no replies. Hmmm.

**Comment by Joinyy** [comment]
https://github.com/ValveSoftware/Proton#building

Here is what you probably search. This won't be any different on Ubuntu / Arch / Mint etc...
