### ISSUE TITLE
Batman: Arkham City GOTY fails to launch

### ISSUE THREAD

**Issue by jennarowan** [ValveSoftware/Proton#1773]
I'm on Linux Mint 19 Cinnamon version 3.8.9 (kernel 4.15.0-36-generic).
I'm using an AMD A10-7700K Radeon R7.

I cannot get Arkham City to launch.  When I try to launch it from within the Steam client (Big Picture Mode) it tells me it's preparing for first time use, then the entire window turns blue (as in everything vanished but the Steam background), then a moment later everything comes back.  Instead of launching, however, it just tells me the game is ready to play.  Nothing else happens; the game never launches.

When I try to launch the game directly from the Start Menu it pops up a box saying it is installing the Microsoft .NET framework.  The progress bar never moves, though, and after about 30 seconds the window vanishes and nothing else happens.

I have set my Wine version to Windows XP (as has been suggested in previous issue fixes) and am still having no luck.

![ac](https://user-images.githubusercontent.com/40580057/47127820-add45c80-d25c-11e8-8844-30eae41baa46.png)

**Comment by NoXPhasma** [comment]
There is already an issue for this game: #309

**Comment by jennarowan** [comment]
I read through that.  Multiple people used lineber's suggested solution and it worked for them.  I did what lineber said and still can't get it to work.

**Comment by kisak-valve** [comment]
Hello @jentrxm, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/309#issuecomment-430996005.
