### ISSUE TITLE
Add install button on Games page for SteamPlay-compatible games

### ISSUE THREAD

**Issue by Salvatos** [ValveSoftware/Proton#1776]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [N/A] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description
When you visit your Games page in a browser from a computer on which Steam is installed, the righthand part tells you whether each game is _Ready to play_,  _Not available for this computer_ or _Not installed_, with a button to do so.

On uninstalled SteamPlay (whitelisted) titles, the listing says _Not available for this computer_. I suggest it should have the install button instead (possibly with a SteamPlay notice and/or icon).

Behavior noticed with _Monkey Island 2: Special Edition_. I have no other whitelisted games to compare against.

**Comment by kisak-valve** [comment]
Hello @Salvatos, this is an issue with Steam's website rather than proton itself, so I've transferred this issue to https://github.com/ValveSoftware/steam-for-linux/issues/5847.
