### ISSUE TITLE
SOULCALIBUR VI: no connection to online servers (544750)

### ISSUE THREAD

**Issue by sudodude** [ValveSoftware/Proton#1784]
# Compatibility Report
- Name of the game with compatibility issues: SOULCALIBUR VI
- Steam AppID of the game: 544750

## System Information
- GPU: GTX 1050 Ti
- Driver/LLVM version: nvidia 410.57
- Kernel version: 4.18
- Link to full system information report: [Gist](https://gist.github.com/sudodude/5d2ec1bc06a2e2af597becda30cd6df3)
- Proton version: 3.16-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-544750.log](https://github.com/ValveSoftware/Proton/files/2496441/steam-544750.log)

## Symptoms 
No online play/connection to online server available.

## Reproduction
Start the game, an error message appears: Network data could not be retrieved. If you begin the game in this state, you will be unable to use online features. 

Also, a wine error message appears after exiting the game.
![screenshot_20181019_005810](https://user-images.githubusercontent.com/3153768/47228580-dfb50280-d3c5-11e8-9ef2-6369e73dfdc4.png)

**Comment by kisak-valve** [comment]
Hello @sudodude, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1780#issuecomment-431409880.
