### ISSUE TITLE
Yakuza 0 (638970)

### ISSUE THREAD

**Issue by thatlordbaal** [ValveSoftware/Proton#1796]
With Proton 3.16-1 Beta I was finally able to get the game to launch and get over 2 hours into the game. however after it updated to  3.16-2 the game no longer launches. any clues to what could of cause it to now stop working? 
It should be noted i was on Nvidia driver 396.54 for 3.16-1 and 3.16-2.
https://gist.github.com/thatlordbaal/74a59fc5a1f87c4946006a1add136e75

**Comment by kisak-valve** [comment]
Hello @thatlordbaal, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/492#issuecomment-431684216.
