### ISSUE TITLE
Games don't launch on my system

### ISSUE THREAD

**Issue by jvschiavo** [ValveSoftware/Proton#181]
Hi, I cannot get any game I've tried to launch. When I click play it tries to launch but it seems like nothing has happened.
I tried **Spelunky**, then **The Binding of Isaac**, then **Doki Doki Literature Club**.

Machine: Samsung Chromebook 2 XE500C12
OS: Ubuntu 16.04 (via crouton)

Latest Steam Beta Client with mesa-vulkan-drivers mesa-vulkan-drivers:i386 from ppa:paulo-miguel-dias/mesa as suggested by PREREQS.md.

**Comment by Leopard1907** [comment]
Did you reboot Steam?

Also i think there is no support for ChromeOS - Crouton nor tried before.

I hope you can make it work.

**Comment by Yukari-Kuramoto** [comment]
Are you running the games off of an ntfs drive?
Running games on ntfs drives is currently bugged for a lot of users.
Had the same issue as you until I put them on ext4.

**Comment by jvschiavo** [comment]
@Leopard1907 Yes.
@Yuri-Makina No.

Thank you guys.

I've just noticed about #9 and #15. I'm gonna test now if this is my problem.

**Comment by ghost** [comment]
solved this issue on ubuntu with
``sudo apt install python2.7 python-pip``

**Comment by jvschiavo** [comment]
OMG I'M PLAYING SPELUNKY ON LINUX!

Er.. I mean.. thanks guys, that was indeed my problem. xD

@kassindornelles actually I just did `sudo apt install python`.


I guess the python 2.7 problem is still going to make a lot of users confused...
