### ISSUE TITLE
[REGRESSION] Alan Wake stopped launching in proton 3.16-3

### ISSUE THREAD

**Issue by Patola** [ValveSoftware/Proton#1815]
# Compatibility Report
- Alan Wake (appid 108710) launches correctly in all proton 3.7 releases. When being run in 3.16-3, however, it clears the screen for a couple seconds then crashes.

## System Information
- Ubuntu 18.04 64 bits 16 GiB RAM, using LXDE as desktop environment
- GPU: NVIDIA GTX 1070
- Driver/LLVM version: NVIDIA binary driver 396.54.09
- Kernel version: 4.15.0-38-lowlatency
- Proton version: 3.16-3

## I confirm:
- [X] that I HAVE found an existing compatibility report for this game. It should run.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
- Click "Play". If it is the first time, it spends some time installing requisites. Then it clears the screen and enters fullscreen mode. Then it crashes. On versions of proton prior to 3.16, it launches correctly.
- Note: Alan Wake's American Nightmare (a sequel) _works_ with the same setup, either in proton 3.7 or proton 3.16.

[steam-108710.log](https://github.com/ValveSoftware/Proton/files/2518816/steam-108710.log)

## Reproduction
Install Alan Wake and click play.

**Comment by Patola** [comment]
Game runs with launch options "PROTON_NO_ESYNC=1 PROTON_NO_D3D11=1 %command%". But it should run without them since it works that way on 3.7.

**Comment by kisak-valve** [comment]
Hello @Patola, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/156#issuecomment-433391535.
