### ISSUE TITLE
Option to play native games on Proton instead

### ISSUE THREAD

**Issue by Rabcor** [ValveSoftware/Proton#1817]
# Feature Request
I would like to have an option to make a game install the windows version with proton instead of installing the linux native version.

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
I would like to have an option to make a game install the windows version with proton instead of installing the linux native version. The reason why users might want to do this is to possibly circumvent issues with bad ports.

## Justification 
Although it's fairly uncommon, there exist several cases where certain games will play better on proton/wine than on their native linux ports. Possible examples off the top of my head would include witcher 2 and dungeon defenders.

**Comment by kisak-valve** [comment]
Hello @Rabcor, this feature request is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5638. Closing as a duplicate.
