### ISSUE TITLE
Games not launching with proton

### ISSUE THREAD

**Issue by Millie290** [ValveSoftware/Proton#1824]
Well all of my games using steam play dosen't work... in all distro (ubuntu 18, mint 19, Arch, Manjaro...)
the game say it's launching and when the steam pop up close game quite immediately without any messages and before with proton 3.7.6 that was working...

**Comment by jomarocas** [comment]
your game, you need specified the games an compability support o something that broken, yo no specified the gist and others

**Comment by aaronfranke** [comment]
What are your graphics drivers? Do you have Python installed?

**Comment by Millie290** [comment]
> What are your graphics drivers? Do you have Python installed?

yes i got python and my drivers are 410.66 ps also not working with 396

**Comment by xexpanderx** [comment]
Well, I have the same problems, game not launching. Although they works perfectly fine if launching outside Steam with wine-staging + DXVK.

**Comment by LeJimster** [comment]
Have you tried 3.16-3 beta?

**Comment by aaronfranke** [comment]
Are you trying to launch supported games or unsupported games? How many games have you tried?

**Comment by Millie290** [comment]
> Are you trying to launch supported games or unsupported games? How many games have you tried?

A lot of supported games and some unsuported

**Comment by Millie290** [comment]
> Well, I have the same problems, game not launching. Although they works perfectly fine if launching outside Steam with wine-staging + DXVK.

Yep work perfectly on wine

**Comment by Millie290** [comment]
> Have you tried 3.16-3 beta?

Still not working

**Comment by meowmeowfuzzyface** [comment]
@Millie290 Are your games installed on an NTFS formatted drive?  Which games specifically have you tried?  What is your hardware?  What is the output of vulkaninfo in terminal?

**Comment by Millie290** [comment]
> @Millie290 Are your games installed on an NTFS formatted drive? Which games specifically have you tried? What is your hardware? What is the output of vulkaninfo in terminal?

i'm on a ntfs drive for games (all games) and lutris cant install and play nicely so ikd why that dosent work
my hardware Gtx 1070 I7 6700k 16 Gb ram
i tried games that worked before with steamplay like shootmania it was working on proton 3.7.6 but not now.... and how see vulkan info ?

**Comment by xexpanderx** [comment]
I see many are using NTFS-partitions for their games, why?

**Comment by Millie290** [comment]
> I see many are using NTFS-partitions for their games, why?

cause i still dualbooting the fault to ubisoft cause we can't play R6 or Watchdogs or The division ect...

**Comment by meowmeowfuzzyface** [comment]
A lot of people dual boot and share a storage hard drive with their Windows OS.

**Comment by meowmeowfuzzyface** [comment]
@Millie290 The NTFS drive is the most likely culprit.  Can you check the mount options in /etc/fstab for the partition where your games are installed?  Make sure it contains exec, uid and gid for your user (usually 1000), and does NOT include windows_names.  If possible, I would recommend you install your games on an ext4 drive, but with the proper mount options it does seem to work on NTFS as well.

For vulkaninfo, just type it into a terminal and link us the output in gist or pastebin.

**Comment by Millie290** [comment]
> @Millie290 The NTFS drive is the most likely culprit. Can you check the mount options in /etc/fstab for the partition where your games are installed? Make sure it contains exec, uid and gid for your user (usually 1000), and does NOT include windows_names. If possible, I would recommend you install your games on an ext4 drive, but with the proper mount options it does seem to work on NTFS as well.
> 
> For vulkaninfo, just type it into a terminal and link us the output in gist or pastebin.

got error when i install vulkan tool or vulkan utils

Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Certains paquets ne peuvent être installés. Ceci peut signifier
que vous avez demandé l'impossible, ou bien, si vous utilisez
la distribution unstable, que certains paquets n'ont pas encore
été créés ou ne sont pas sortis d'Incoming.
L'information suivante devrait vous aider à résoudre la situation : 

Les paquets suivants contiennent des dépendances non satisfaites :
 vulkan-utils : Dépend: vulkan-tools mais ne sera pas installé
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».

**Comment by meowmeowfuzzyface** [comment]
Well, I don't know any French but I think that would be a problem. I believe the Nvidia PPA provides a vulkan package and a vulkan-loader package. Do you have those installed?

Also, did you check the mount options? The Ubuntu recommended mount options will prevent Proton from working due to the windows_names option. Best thing is to install and run your games from an ext4 drive. If that's not an option, you need to check your /etc/fstab to make sure the drive is mounted in a usable state for Proton.

For example (disclaimer: can make your system unbootable so be careful):
ntfs-3g defaults,exec,gid=1000,uid=1000 0 2

**Comment by Millie290** [comment]
> Well, I don't know any French but I think that would be a problem. I believe the Nvidia PPA provides a vulkan package and a vulkan-loader package. Do you have those installed?
> 
> Also, did you check the mount options? The Ubuntu recommended mount options will prevent Proton from working due to the windows_names option. Best thing is to install and run your games from an ext4 drive. If that's not an option, you need to check your /etc/fstab to make sure the drive is mounted in a usable state for Proton.
> 
> For example (disclaimer: can make your system unbootable so be careful):
> ntfs-3g defaults,exec,gid=1000,uid=1000 0 2

kay but i cant resize the drive on gparted ... and the diskmanager...

**Comment by meowmeowfuzzyface** [comment]
This has nothing to do with resizing. The mount options are used when making the hard drive available to the OS. Open up /etc/fstab (be very careful here), find the entry for the partition where your games are installed, and copy paste the mount options for that drive here so we can see how it's being mounted.

**Comment by aaronfranke** [comment]
This is not a support forum, this is a bug tracker for Proton.

**Comment by Millie290** [comment]
> This has nothing to do with resizing. The mount options are used when making the hard drive available to the OS. Open up /etc/fstab (be very careful here), find the entry for the partition where your games are installed, and copy paste the mount options for that drive here so we can see how it's being mounted.

yay but i need to keep a ntfs part so i want to reduce it to create a Ext4 part

**Comment by Millie290** [comment]
> This is not a support forum, this is a bug tracker for Proton.

yay but the support of steam told me to go here so well

**Comment by meowmeowfuzzyface** [comment]
@Millie290 Admittedly, some of the things you are asking are out of the scope of Proton issues.  If you're not sure how to resize your partitions, find and edit mount options, or get Vulkan working for your GPU, then that's something to Google or ask at another location.

If you can provide the output of vulkaninfo and provide us your mount options, we might be able to determine if this is a known bug or not.

**Comment by HonkingGoose** [comment]
@Millie290 Hi, I understand that its frustrating that your games are not working when they used to work before. It is better to add your findings to the already issued issues, most popular games are already listed on the Proton issue tracker.

## Some helpful tips for you:
1. Go to https://steamdb.info/search/
1. Type in the name of the game that has issues for you.
1. Click *search*
1. The table of results has a column labeled *appid*.
1. Search on the Proton issue tracker with the appid number; this should lead you to the game.
1. If the game you're having issues with is not listed yet; try searching on the Proton GitHub by name.
1. If you still can't find the game on the issue tracker: open a new issue report for that game.

**Comment by Millie290** [comment]
> @Millie290 Admittedly, some of the things you are asking are out of the scope of Proton issues. If you're not sure how to resize your partitions, find and edit mount options, or get Vulkan working for your GPU, then that's something to Google or ask at another location.
> 
> If you can provide the output of vulkaninfo and provide us your mount options, we might be able to determine if this is a known bug or not.

but lutris with overwatch use DXVK and that work :(

**Comment by meowmeowfuzzyface** [comment]
@Millie290 I'm trying to help you, but I've been asking for two things since the start of this thread and you have yet to give me either of them: vulkaninfo output and the mount options for your NTFS partition.

**Comment by ghost** [comment]
This sounds like an NTFS issue. Its already known that Proton and drive sharing with Windows is a problem.

Easiest thing is to just not do that which is my recommendation. Even if its working, that doesn't mean it won't get borked at any time.
