### ISSUE TITLE
The Flame in the Flood (318600)

### ISSUE THREAD

**Issue by ProfessorChill** [ValveSoftware/Proton#1827]
# Whitelist Request
- Name of the game to be whitelisted: The Flame in the Flood
- Steam AppID of the game: 318600

## System Information
- GPU: GTX 980
- Driver/LLVM version: nvidia 410.66-4
- Kernel version: 4.19.arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ProfessorChill/761ec5bbd91ea558daec39db4b216442
- Proton version: 3.7-8

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [X] that no workarounds other than the mentioned ones are necessary.

## Issues
- [X] I haven't experienced any issues.
- [X] There are no issues left open for this game.
- [X] Although I consider the gaming experience equal to Windows there are remaining issues:

I averaged a solid 5 FPS when the game actually started, I however did play through (a bit of the game) and test to ensure it was working.

**Comment by jonlap** [comment]
[#379](https://github.com/ValveSoftware/Proton/issues/379)

**Comment by kisak-valve** [comment]
Hello @ProfessorChill, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/379#issuecomment-433647270.
