### ISSUE TITLE
Spelunky (239350)

### ISSUE THREAD

**Issue by ProfessorChill** [ValveSoftware/Proton#1828]
# Whitelist Request
- Name of the game to be whitelisted: Spelunky
- Steam AppID of the game: 239350

## System Information
- GPU: GTX 980
- Driver/LLVM version: nvidia 410.66-4
- Kernel version: 4.19.arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ProfessorChill/761ec5bbd91ea558daec39db4b216442
- Proton version: 3.7-8

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [X] that no workarounds other than the mentioned ones are necessary.

## Issues
- [X] I haven't experienced any issues.
- [X] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

**Comment by kisak-valve** [comment]
Hello @ProfessorChill, this game is already white listed.
