### ISSUE TITLE
Grand Theft Auto V (271590) - Offline Mode Not Available

### ISSUE THREAD

**Issue by qantourisc** [ValveSoftware/Proton#1832]
# Compatibility Report
- Grand Theft Auto V
- 271590

## System Information
- GPU: GeForce GTX 650 Ti BOOST
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.12.12
- Steam system report: https://gist.github.com/qantourisc/7d265339db89925bdd71b0395dfef925
- Proton version: 3.16-3 Beta (and other versions)
* Log file to large to attach, compressed file cannot be uploaded.

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
Unable to "get online" to play online or offline.
"Offline Mode Not Available"
I have made several attempts to get it work: play with wine/proton settings dll overrides, Deleted Social Club files, repaired, corefonts installation, ... 

## Reproduction
1. Install game
2. Start game
3. Find yourself unable to play due to some form of DRM.

**Comment by kisak-valve** [comment]
Hello @qantourisc, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-433648294.
