### ISSUE TITLE
DOOM (2016) worse performace on Vulkan compared to OpenGL (379720)

### ISSUE THREAD

**Issue by igo95862** [ValveSoftware/Proton#1841]
# Compatibility Report
- Name of the game with compatibility issues: DOOM (2016)
- Steam AppID of the game: 379720

## System Information
- GPU: AMD RX480
- Driver/LLVM version: Mesa 18.2.3/ LLVM 7.0.0
- Kernel version: 4.18.16
- Link to full system information report as [Gist](https://gist.github.com/igo95862/4e4c5dace6a494ea57719bff6e7ee34d):
- Proton version: 3.16-3 Beta

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## PROTON_LOG:
[steam-379720.log.zip](https://github.com/ValveSoftware/Proton/files/2524087/steam-379720.log.zip)

## Symptoms
OpenGL: 107-110 frames
![image](https://user-images.githubusercontent.com/8576552/47632133-0f6eb380-db06-11e8-9ae8-d62f06f168bb.png)
Vulkan: 43-50 frames
![image](https://user-images.githubusercontent.com/8576552/47632146-24e3dd80-db06-11e8-8666-37fa8744f3b6.png)

Vulkan version can't even sustain 60 frames in the main menu.

Those screenshots are on minimum settings.

Last time I checked on Windows DOOM (2016) on Vulkan had generally more performance than OpenGL. I also checked other peoples reports and they seem to indicate generally better performance when Vulkan is activated.

I've tested Vulkan with Dota 2 and performance seemed to be equal or slightly better than OpenGL implementation.

I wanted to test some other game to verify if this was DOOM (2016) specific or a general proton issue, however, the only other game that supports Vulkan and does not have native linux port I know of is Wolfenstein II: The New Colossus but I do not own that game.

**Comment by kisak-valve** [comment]
Hello @igo95862, can you temporarily move the `/usr/share/vulkan/icd.d/intel*.json` files somewhere safe or rename them to something that does not end in .json and see if that makes a difference?

**Comment by Volkinaz** [comment]
**System Information**

- GPU: AMD RX480(8gb)
- Driver/LLVM version: Mesa 18.3-dev/ LLVM 7.0.0
- Kernel version: 4.18.10
- OS: Ubuntu 18.04.1
- CPU: r5 1600 (SMT OFF)

**Spent from:**

The difference is about 10-20% in favor of the API Vulkan. Perhaps not correct or partial installation of drivers. Try Mesa 18.3
Wolfenstein II: The New Colossus shows 60-100 FPS at high settings.
Based on this, I see that your problem is not standard. Please write more info: OS, CPU, RAM

**Comment by kisak-valve** [comment]
Hello @Volkinaz, more system info was already provided: https://gist.github.com/igo95862/4e4c5dace6a494ea57719bff6e7ee34d

**Comment by GloriousEggroll** [comment]
@igo95862 Try disabling your iGPU in your bios. I had the same issue on a system with 2400g + rx 580, problem was vulkan was using the first GPU it found, which was my iGPU. I couldn't figure out for the life of me why I was only getting 30ish fps at high settings 1080p. Once I disabled the iGPU vulkan used my 580 and my framerates returned to normal

what is the output of:

`vulkaninfo | grep "GPU id"`

you may need the vulkan-tools package for this command to work.

**Comment by igo95862** [comment]
`                ERROR: [Loader Message] Code 0 : /usr/lib32/libvulkan_radeon.so: wrong ELF class: ELFCLASS32

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))

                GPU id       : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))`

I don't even have Vulkan Intel driver installed. Disabling the IGPU in bios changed nothing.

**Comment by GloriousEggroll** [comment]
yikes, maybe try llvm-svn and mesa-git, only other thing i can think of

**Comment by igo95862** [comment]
Hmmmmmmmmmmmmmmmmmm, I think I discovered something.

I switched to LTS kernel which has version 4.14.78 and it seems like this fixed performance:

![doom fixed2](https://user-images.githubusercontent.com/8576552/47697308-a8193800-dbc7-11e8-936b-639b689ea70d.png)

**Comment by GloriousEggroll** [comment]
@igo95862  something else changed. look at your vulkan version. 1.0.68 compared to normal 1.1.70. A friend mentioned to check cpu usage, the razer chroma bug is known to get first two cores stuck at 100%

**Comment by igo95862** [comment]
The CPU usage always stays low. Its the GPU that gets maxed out on newer kernel.
