### ISSUE TITLE
Bejeweled Twist (3560) requires adding -changedir to launch options

### ISSUE THREAD

**Issue by LunarLambda** [ValveSoftware/Proton#1843]
# Compatibility Report
- Name of the game with compatibility issues: Bejeweled Twist
- Steam AppID of the game: 3560

## System Information
- GPU: Nvidia GTX 750
- Driver/LLVM version: nvidia-driver-396
- Kernel version: 4.15.0-38
- Link to full system information report as [Gist](https://gist.github.com/LunarLambda/4e1b346d340505290f9feb92fe7f7ee4):
- Proton version: 3.7-8

## I confirm:
- [x] that I have checked whether there are updates for my system available.

[steam-3560.log](https://github.com/ValveSoftware/Proton/files/2524604/steam-3560.log)

## Symptoms
The game fails to launch with a "Invalid command line parameter: -changedir" message box.
See https://github.com/ValveSoftware/Proton/issues/340 and https://github.com/ValveSoftware/Proton/issues/238

**Comment by kisak-valve** [comment]
Hello @LunarLambda, this issue is already being tracked in #340. Closing in favor of the existing issue report.
