### ISSUE TITLE
[Feature Request] Corefonts and Proton.

### ISSUE THREAD

**Issue by HonkingGoose** [ValveSoftware/Proton#1847]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Many games rely on Corefonts to run/look right. There are some possible solutions to this.

1. Bundle Corefonts with Proton itself.
1. Bundle some kind of corefonts-lookalike font, *I think this is called metrically compatible font?* Issue #571 seems to have some discussion on this.
1. Have a notice/pop-up when running a game that needs Corefonts: "Reminder: you need to install Corefonts. Go to: (insert link to Distro-wiki for Corefonts) for more information and instructions on how to do this."

Possible issues:
1. Bundling Corefonts itself with Proton will likely be difficult due to licensing issues.
1. Bundling some kind of lookalike will probably lead to complaints from old Windows users, due to them not being 100% matches for the old fonts.
1. The notice/pop-up would need to be maintained (Distro-wikis are bound to change from time to time.)

## Justification [optional] 
Many games seem to rely on Corefonts being installed to work/look right.

## References [optional] 
#571

**Comment by kisak-valve** [comment]
Hello @HonkingGoose, I don't see any value in rehashing the discussion that has already happened on #571 in another issue report. Closing in favor of the existing issue report.
