### ISSUE TITLE
Bloons TD Battles (444640)

### ISSUE THREAD

**Issue by downloadpizza** [ValveSoftware/Proton#1855]
# Compatibility Report
- Name of the game with compatibility issues: BTD Battles
- Steam AppID of the game: 444640

## System Information
- GPU: Intel Integrated (Pentium B960)
- Driver/LLVM version:   3.0 Mesa 18.2.3 - padoka PPA
- Kernel version: 4.15-38
- Full System info: https://gist.github.com/Gabgab2003/eee50670af0ba7746bde5bdd460e0eb6
- Proton version: 3.7-8 (latest stable as of writing this

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
- No Audio
(checked system audio and game setting, also tried disabling esync and so on.)

## Reproduction
- Start the game

## Log
- [steam-444640.log](https://github.com/ValveSoftware/Proton/files/2531094/steam-444640.log)

**Comment by kisak-valve** [comment]
This looks like a line of interest: `warn:debugstr:OutputDebugStringA ">> :63 void __thiscall WinMusicManager::Load(void) Failed to init XAudio2 engine: 0X800401F0"`

**Comment by Gabgab2003** [comment]
Maybe `winetricks xact` could fix it?

**Comment by nsivov** [comment]
Please retest with 3.16-7, this should be fixed now with ValveSoftware/wine@7af2914.

**Comment by vpzomtrrfrt** [comment]
Works fine for me now

**Comment by downloadpizza** [comment]
Works on Pop_OS! 18.04 now.
