### ISSUE TITLE
Update Nvidia requirements to nvidia-410

### ISSUE THREAD

**Issue by leifmetcalf** [ValveSoftware/Proton#1856]
The wiki requirements page recommends the following line to be run:
`sudo apt install nvidia-driver-396`

From the PPA page, the current long-lived branch release is nvidia-410. Should this line be updated to:
`sudo apt install nvidia-driver-410`
?

**Comment by kisak-valve** [comment]
Hello @leifmetcalf, that wiki page in general reflects the oldest known good driver that is required for support with Proton. The documentation should not be incrementally updated as new drivers come available, only when there is a functional difference that makes the older driver version unsupportable.

**Comment by Rotscha** [comment]
Additionally, 410.x doesn't support newer Vulkan extensions (such as the important VK_EXT_transform_feedback) yet. 396.x is factually their Vulkan driver.

**Comment by Askannz** [comment]
@Rotscha  Beware version numbers, though. 396.54 doesn't support transform feedback, but 396.54.9 (the Vulkan beta) does.
