### ISSUE TITLE
The Witness performance regression vs Lutris w/DXVK (210970)

### ISSUE THREAD

**Issue by LeJimster** [ValveSoftware/Proton#186]
Seems like I'm losing upto 50% performance with Proton 3.7 compared to Lutris w/DXVK+esync.

All game settings are the same.
Proton 3.7
![thewitness_proton3 7_1](https://user-images.githubusercontent.com/35663469/44495319-75067580-a667-11e8-8bae-5e98fb4e24e7.jpg)
Lutris (esync-3.13)
![thewitness_lutris_esync-3 13_1](https://user-images.githubusercontent.com/35663469/44495329-7b94ed00-a667-11e8-8321-493fba379311.jpg)
Proton 3.7
![thewitness_proton3 7_2](https://user-images.githubusercontent.com/35663469/44495336-7f287400-a667-11e8-9aca-51b5247dfe53.jpg)
Lutris (esync-3.13)
![thewitness_lutris_esync-3 13_2](https://user-images.githubusercontent.com/35663469/44495338-82236480-a667-11e8-9cc7-bacc68103265.jpg)

My system

System specs:
OS: Arch Linux
Kernel: x86_64 Linux 4.18.3-arch1-1-ARCH
CPU: AMD Ryzen 7 1700
GPU: Radeon RX Vega 56
OpenGL version string: 4.4 (Compatibility Profile) Mesa 18.3.0-devel (git-aa79cc2bc8)

**Comment by ghost** [comment]
Maybe it's because Proton uses Version 3.7 of Wine that is a bit old compared to the current one, it may apply to the DXVK

**Comment by LeJimster** [comment]
Performance is the same as Lutris now since bug #192 was fixed.  You can close this now. =)
