### ISSUE TITLE
[Whitelist] Saints Row: The Third

### ISSUE THREAD

**Issue by ThePreviousOne** [ValveSoftware/Proton#1862]
# Whitelist Request
Saints Row: The Third
55230

## System Information
AMD RX 580
Mesa 18.1.7
4.18.6
- Link to full system information report as [Gist](https://gist.github.com/ThePreviousOne/e94ed3b8e44223ab31f29daf36c3b783):
3.16-3 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

**Comment by d10sfan** [comment]
I believe this game is native. Not using proton

**Comment by kisak-valve** [comment]
Closing as this is a linux native game.

**Comment by ThePreviousOne** [comment]
ya sorry my bad
