### ISSUE TITLE
Alicia Quartermain 2 has no executable

### ISSUE THREAD

**Issue by crabel** [ValveSoftware/Proton#1870]
# Compatibility Report
- Name of the game with compatibility issues:  Alicia Quatermain 2: The Stone of Fate
- Steam AppID of the game: 667040

## System Information
- GPU: Vega 64
- Driver/LLVM version: Mesa 18.2.2
- Kernel version: 4.18
- Link to full system information report as [Gist](https://gist.github.com/): Not needed here
- Proton version: 3.16-4

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Symptoms
Game does not start because there is no executable (actually there are no files at all).

## Reproduction
Install the game, installer finishes instantly. The game folder (in steamapps/common) is created in filesystem, but it is empty. Obviously the game cannot be started (no executable)
I tried to verify game files, uninstall, reinstall, ...

**Comment by nsivov** [comment]
I can reproduce this. Install dialog does not show required/available disk space info.

**Comment by kisak-valve** [comment]
Hello @crabel, looks like this game has an unused linux depot, but no corresponding launch config or content.

This game falls under the feature request at https://github.com/ValveSoftware/steam-for-linux/issues/5638. Alternatively, you could make a polite request to the game's dev to remove depot 667043 if there is no intention to have a native linux version.

**Comment by crabel** [comment]
I already thought that it would be something like this. I will ask them. AFAIK there is indeed a port planned, but till it is here, it would be nice to use Proton instead ...

Thanks for looking into it. A fix/option for Issue 5638 would indeed be very helpful.
