### ISSUE TITLE
[Whitelist]  Fieldrunners 2 (215710)

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#1872]
# Whitelist Request
- Name of the game to be whitelisted: Fieldrunners 2
- Steam AppID of the game: 215710

## System Information
- GPU: Intel HD Graphics 520
- Driver/LLVM version: Mesa 18.2.3
- Kernel version: 4.19
- Link to full system information report as [Gist](https://gist.github.com/): 
- Proton version: 3.16-4 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

**Comment by kisak-valve** [comment]
Hello @liberodark, this game is already white listed.
