### ISSUE TITLE
Dark Souls Prepare to Die edition: Only ENG and Jap available

### ISSUE THREAD

**Issue by Kryuko** [ValveSoftware/Proton#1878]
Hello.

Game ID: 211420

The game is available in multiple languages, but when i install the game in ubuntu i have only english and japanase available as language settings.

When i had windows i was able to choose my own language (italian) and others as well.

I think languages files are not even installed.

Thank you in advance :)

**Comment by kisak-valve** [comment]
Hello @Kryuko, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1319#issuecomment-435162672.
