### ISSUE TITLE
[Whitelist] Fallout: New Vegas (22380)

### ISSUE THREAD

**Issue by DennisBednarz** [ValveSoftware/Proton#1879]
# Compatibility Report
- Name of the game with compatibility issues: Fallout: New Vegas
- Steam AppID of the game: 22380

## System Information
- GPU: AMD Radeon AMD Radeon R7 M265
- Driver/LLVM version: 4.5, Mesa 18.3.0-devel
- Kernel version: 4.19.0
- Link to full system information report as [Gist]: https://gist.github.com/DennisBednarz/cd19d28dc24d2c378eaed42fb5bb7089
- Proton version: 3.16~4 Beta

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

[steam-22380.log](https://github.com/ValveSoftware/Proton/files/2540213/steam-22380.log)

## Symptoms 

There are two problems. The first one is the more serious one. Using a bluetooth mouse (or at least the Microsoft Arc Touch mouse) is impossible in this game because as soon as you move the mouse at all, the game goes down to single-digit FPS if it doesn't freeze altogether. As soon as the mouse stops moving and giving input, it's back to "normal" which is still not good (something I'll describe in a second). I have not tested this game with other bluetooth or wired mice. 

The second issue is that the game has constant micro-freezes. The FPS also seems to be unaffected no matter if I set the settings to absolute maximum or the lowest settings possible. This is odd as neither max out at 60 FPS. This freeze/micro-stuttering doesn't seem to happen while standing still, only when there's input passed to the game, hence why I'm reporting two issues at the same time as they seem to be related.

**Comment by kisak-valve** [comment]
Hello @DennisBednarz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/356#issuecomment-435205174.
