### ISSUE TITLE
No Proton Games Starting

### ISSUE THREAD

**Issue by dhasial** [ValveSoftware/Proton#1886]
Both Rocket League and Stardew Valley worked fine earlier today, but now nothing loads even though the process can be seen in the process manager (and must be killed).

I've used every version of Proton available with none working. I noticed something strange happening though - when I ran sudo apt-get update, a previously unresponsive Rocket League process properly loaded, though it said I was logged out of Steam and had to restart the game, after which it goes back to not loading. I saw that the same thing happened when I tried uninstalling fglrx and installing the open-source AMD drivers*,* after I ran this command: sudo apt-get install --reinstall libgl1-mesa-glx libgl1-mesa-dri xserver-xorg-core . After rebooting, they still don't load. I also tried installing python 2.7 and by checking with: python --version , I see that I have Python 2.7.15rc1.

**Comment by felisucoibi** [comment]
Looks like a drivers problem, did you try to run steam from command line?

**Comment by dhasial** [comment]
I did, I get the output:

user@ubuntu: steam steam://rungameid/925930
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
user@ubuntu:

Same thing happens though. I've heard that after running this, the command line should have more output than that, but it just goes right back to normal almost immediately.

To be specific, that's trying to start Rocket League, launching Steam itself from command line gives me this:

user@ubuntu: steam
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Gtk-Message: 03:35:05.650: Failed to load module "gail"
Gtk-Message: 03:35:05.650: Failed to load module "atk-bridge"

(steam:9733): Gtk-WARNING **: 03:35:05.671: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita-dark/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'

(steam:9733): Gtk-WARNING **: 03:35:05.672: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
Installing breakpad exception handler for appid(steam)/version(1539393410)
[1102/033506.025561:INFO:crash_reporting.cc(216)] Crash reporting enabled for process: browser
[1102/033506.038581:WARNING:crash_reporting.cc(255)] Failed to set crash key: UserID with value: 0
[1102/033506.038636:WARNING:crash_reporting.cc(255)] Failed to set crash key: BuildID with value: 1539391679
[1102/033506.038639:WARNING:crash_reporting.cc(255)] Failed to set crash key: SteamUniverse with value: Public
[1102/033506.038641:WARNING:crash_reporting.cc(255)] Failed to set crash key: Vendor with value: Valve
[1102/033506.060619:ERROR:gpu_process_transport_factory.cc(1026)] Lost UI shared context.
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
CAppInfoCacheReadFromDiskThread took 29 milliseconds to initialize
CApplicationManagerPopulateThread took 92 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)

** (steam:9733): WARNING **: 03:35:06.189: Unknown device type 16

** (steam:9733): WARNING **: 03:35:06.189: Could not create object for /org/freedesktop/NetworkManager/Devices/6: unknown object type

** (steam:9733): WARNING **: 03:35:06.189: handle_property_changed: failed to update property 'devices' of object type NMActiveConnection.

** (steam:9733): WARNING **: 03:35:06.194: Unknown device type 13

** (steam:9733): WARNING **: 03:35:06.194: Could not create object for /org/freedesktop/NetworkManager/Devices/4: unknown object type

** (steam:9733): WARNING **: 03:35:06.194: handle_property_changed: failed to update property 'devices' of object type NMActiveConnection.

** (steam:9733): WARNING **: 03:35:06.194: Unknown device type 14

** (steam:9733): WARNING **: 03:35:06.194: Could not create object for /org/freedesktop/NetworkManager/Devices/1: unknown object type

** (steam:9733): WARNING **: 03:35:06.196: Unknown device type 13

** (steam:9733): WARNING **: 03:35:06.196: Could not create object for /org/freedesktop/NetworkManager/Devices/4: unknown object type

** (steam:9733): WARNING **: 03:35:06.196: Unknown device type 16

** (steam:9733): WARNING **: 03:35:06.196: Could not create object for /org/freedesktop/NetworkManager/Devices/5: unknown object type

** (steam:9733): WARNING **: 03:35:06.196: Unknown device type 16

** (steam:9733): WARNING **: 03:35:06.196: Could not create object for /org/freedesktop/NetworkManager/Devices/6: unknown object type

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'autoconnect-priority'

** (steam:9733): WARNING **: 03:35:06.329: Unknown setting 'proxy'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'route-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'address-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'route-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'address-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'interface-name'

** (steam:9733): WARNING **: 03:35:06.329: Unknown setting 'proxy'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'route-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'dns-priority'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'address-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'route-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'dns-priority'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'address-data'

** (steam:9733): WARNING **: 03:35:06.329: Unknown setting 'tun'

** (steam:9733): WARNING **: 03:35:06.329: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/5 settings: (3) type

** (steam:9733): WARNING **: 03:35:06.329: Unknown setting 'proxy'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'route-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'address-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'route-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'address-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'interface-name'

** (steam:9733): WARNING **: 03:35:06.329: Unknown setting 'proxy'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'route-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'dns-priority'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'address-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'route-data'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'dns-priority'

** (steam:9733): WARNING **: 03:35:06.329: Ignoring invalid property 'address-data'

** (steam:9733): WARNING **: 03:35:06.329: Unknown setting 'bridge'

** (steam:9733): WARNING **: 03:35:06.329: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/3 settings: (3) type
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)

(steam:9733): Gtk-WARNING **: 03:35:07.035: gtk_disable_setlocale() must be called before gtk_init()
Segmentation fault (core dumped)
Installing breakpad exception handler for appid(steam)/version(1539393410)
roaming config store loaded successfully - 8658 bytes.
migrating temporary roaming config store
[1102/033509.426005:INFO:crash_reporting.cc(239)] Crash reporting enabled for process: renderer
[1102/033509.438562:WARNING:crash_reporting.cc(255)] Failed to set crash key: UserID with value: 0
[1102/033509.438628:WARNING:crash_reporting.cc(255)] Failed to set crash key: BuildID with value: 1539391679
[1102/033509.438632:WARNING:crash_reporting.cc(255)] Failed to set crash key: SteamUniverse with value: Public
[1102/033509.438635:WARNING:crash_reporting.cc(255)] Failed to set crash key: Vendor with value: Valve
[1102/033509.439052:INFO:crash_reporting.cc(216)] Crash reporting enabled for process: gpu-process
Failed to init SteamVR because it isn't installed
ExecCommandLine: "'/home/user/.local/share/Steam/ubuntu12_32/steam'"
System startup time: 4.79 seconds
[1102/033510.031451:INFO:crash_reporting.cc(239)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(steam)/version(1539393410)
JS method call WebChat.GetWebChatLanguage with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.RegisterOverlayChatBrowserInfoChanged with 1 arguments
JS method call WebChat.GetSignIntoFriendsOnStart with 1 arguments
JS method call WebChat.GetCurrentUserAccountID with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.GetWebChatURL with 1 arguments
JS method call FriendSettings.RegisterForSettingsChanges with 1 arguments
JS method call WebChat.RegisterForPushToTalkStateChange with 1 arguments
JS method call WebChat.RegisterForComputerActiveStateChange with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call SharedConnection.AllocateSharedConnection with 1 arguments
JS method call WebChat.RegisterOverlayChatBrowserInfoChanged with 1 arguments
JS method call FriendSettings.GetEnabledFeatures with 1 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.RegisterOnLogonInfoChanged with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
JS method call Parental.RegisterForParentalSettingsChanges with 1 arguments
JS method call Broadcast.RegisterForBroadcastStatus with 1 arguments
JS method call Broadcast.RegisterForViewerRequests with 1 arguments
JS method call SharedConnection.RegisterOnMessageReceived with 2 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call WebChat.GetPushToTalkEnabled with 1 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call WebChat.BSuppressPopupsInRestore with 1 arguments
Installing breakpad exception handler for appid(steam)/version(1539393410)

**Comment by NoXPhasma** [comment]
Both, Rocket League and Stardew Valley, have native Linux ports. You are not using Proton.

**Comment by dhasial** [comment]
Unless I am mistaken, I am using Proton - I selected the checkbox "Use this tool instead of game-specific selections from Steam" because that was the only way it worked before this. I've tried using it and not, doesn't make a difference.

**Comment by aeikum** [comment]
Nope, these are both native Linux titles and are not running through Proton. Proton is only used when you are running Windows titles with the Linux Steam client. I'm afraid you have some other problem :( I agree with @felisucoibi that it looks like your drivers may be badly installed.

**Comment by kisak-valve** [comment]
Closing as Proton is not involved with these games.

As a side note, please use [gist](https://gist.github.com) or similar pastebin service when making large pastes on issue reports.
