### ISSUE TITLE
Project CARS 2 (378860)

### ISSUE THREAD

**Issue by GottaSlay** [ValveSoftware/Proton#1889]
# Compatibility Report
- Name of the game with compatibility issues: Project CARS 2 
- Steam AppID of the game: 378860

## System Information
- GPU: RX580 
- Driver/LLVM version: Driver Version:  4.4 (Compatibility Profile) Mesa 18.2.3 - padoka PPA
- Kernel version: 4.19
- Link to full system information report as [Gist] https://gist.github.com/GottaSlay/66874aaaf2ecfc3d5d0e56cbb1e481e4
- Proton version: 3.16-4 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

[steam-378860.log](https://github.com/ValveSoftware/Proton/files/2543529/steam-378860.log)

**Comment by kisak-valve** [comment]
Hello @GottaSlay, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/908#issuecomment-435475910.
