### ISSUE TITLE
[Compatibility Report] Dragon Ball Xenoverse 2 - Multiplayer is disabled

### ISSUE THREAD

**Issue by KayKay91** [ValveSoftware/Proton#1892]
# Compatibility Report
- Dragon Ball Xenoverse 2
- Steam AppID of the game: 454650

## System Information
- GPU: GTX 970
- Driver: NVIDIA 396.54.09
- Kernel version:4.18.16
- [Gist](https://gist.github.com/KayKay91/b0b9ae1126a2f610ccc755941558cf28)
- Proton version: 3.16-4
[steam-454650.log](https://github.com/ValveSoftware/Proton/files/2544279/steam-454650.log)

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms
Online features of the game is disabled, mostly due to Easy Anti-Cheat not being compatible with Proton.

## Reproduction
Just run the game.

**Comment by kisak-valve** [comment]
Hello @KayKay91, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1453#issuecomment-435527169.
