### ISSUE TITLE
[Whitelist] Getting Over It with Bennett Foddy (240720)

### ISSUE THREAD

**Issue by edn9** [ValveSoftware/Proton#1895]
# Whitelist Request
- Name of the game to be whitelisted: Getting Over It with Bennett Foddy
- Steam AppID of the game: 240720

## System Information
- GPU:  Intel(R) HD Graphics 3000
- Driver/LLVM version:  mesa 18.2.4-1
- Kernel version:  4.18.16
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/necronoise/834a36761d0d7ac4b364e7ed27454986
- Proton version: 3.7-8 beta

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [X] that no workarounds other than the mentioned ones are necessary.

## Issues
- [X] I haven't experienced any issues.
- [X] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

Its working amazing, I was surprise that no one was comment about the game yet.

**Comment by NoXPhasma** [comment]
The game [has a Linux build](https://steamcommunity.com/app/240720/discussions/0/1743343017624699121/), you are not using Proton. Just the Store page is missing the Linux icon.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by edn9** [comment]
> The game [has a Linux build](https://steamcommunity.com/app/240720/discussions/0/1743343017624699121/), you are not using Proton. Just the Store page is missing the Linux icon.

Welp the steam page on the store did not say he has it so thats why I posted here, still thanks for you info.
![image](https://user-images.githubusercontent.com/28832216/47956112-68af6a80-df7e-11e8-8476-89de78897c86.png)
