### ISSUE TITLE
Allow Installation of Native Linux Games Through Proton

### ISSUE THREAD

**Issue by Beinsezii** [ValveSoftware/Proton#1897]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description
Simply put, allow the ability to install a game that has a native Linux version as a Windows Proton game on the installation options screen.

## Justification
Some games have wonky / feature-incomplete Linux ports.
Take _[Ark: Survival Evolved](https://store.steampowered.com/app/346110/ARK_Survival_Evolved/)_ for example: it needs special launch commands to not CTD from sound driver errors, and it's OpenGL shaders haven't been updated since the dawn of time, resulting in it looking like a smartphone game and having multiple graphical glitches.

## Risks
Misuse. Should have a warning message if user attempts to enable for a game clearly stating that it will result in performance impacts and other possible issues, and shouldn't be used unless user knows what they are doing.

**Comment by NoXPhasma** [comment]
There is already a feature request for this on Steam for Linux: https://github.com/ValveSoftware/steam-for-linux/issues/5638

**Comment by tycho** [comment]
Yeah. Let's close this in favor of the existing issue mentioned above.
