### ISSUE TITLE
PRO EVOLUTION SOCCER 2018 and PRO EVOLUTION SOCCER 2018 Lite won't run

### ISSUE THREAD

**Issue by caiodev** [ValveSoftware/Proton#1907]
**Compatibility Report**

    Name of the game with compatibility issues: PRO EVOLUTION SOCCER 2018 / PRO EVOLUTION SOCCER 2018 Lite
    Steam AppID of the game: 342560 / 592600

**System Information**

    OS: Ubuntu MATE 18.04.1 LTS (Bionic Beaver) 64-bit / MATE Version: 1.20.1
    CPU: Intel® Core™ i5-3230M CPU @ 2.60GHz × 4
    RAM: 8GB (7.7GB used)
    GPU: Intel HD Graphics 4000
    Driver/LLVM version: 3.0 Mesa 18.3.0-devel
    Kernel version: Kernel Linux 4.19.0-041900-generic x86_64
    Proton version: 3.16-4

**I confirm:**

- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

**Symptoms**

When i click the "Launch" button, all dependencies (DirectX and .NET stuff) are installed but after that nothing happens.

**Reproduction**

Just click the "Launch" button

**Comment by kisak-valve** [comment]
Hello @caiodev, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/361#issuecomment-435600682. (the lite variant is also at #305)

**Comment by caiodev** [comment]
Oh, i didn't see there were an issue already open. Sorry @kisak-valve

**Comment by escarneiro** [comment]
I had the same problem. It was running flawless before some steam updates.

[steam-592600.log](https://github.com/ValveSoftware/Proton/files/2871828/steam-592600.log)

**Comment by kisak-valve** [comment]
Hello @escarneiro, `amdgpu_device_initialize: DRM version is 2.50.0 but this driver is only compatible with 3.x.x.` in your log indicates your video driver install is broken.
