### ISSUE TITLE
Megadimension Neptunia VII (460120)

### ISSUE THREAD

**Issue by skid9000** [ValveSoftware/Proton#1908]
# Compatibility Report
- Name of the game with compatibility issues: Megadimension Neptunia VII
- Steam AppID of the game: 460120

## System Information
- GPU: Intel Sandybridge Desktop
- Driver/LLVM version: 3.0 Mesa 18.2.4
- Kernel version: 4.19.0-4-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/skid9000/92a2a9222c7c5a8299bb7a6dfc25a485
- Proton version: 3.16-4 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

When you start the game you have a popup "The application has crashed".
[steam-460120.log](https://github.com/ValveSoftware/Proton/files/2545258/steam-460120.log)

## Reproduction

Start the game.

**Comment by kisak-valve** [comment]
Hello @skid9000, Intel/Sandybridge is an OpenGL 3.3 generation video card and does not meet the corresponding requirements for this game. You'll need an directx11/opengl4.x capable video card, preferably one that supports vulkan to be able to play this game.
