### ISSUE TITLE
Botanicula / 207690 works

### ISSUE THREAD

**Issue by thackel** [ValveSoftware/Proton#1914]
# Whitelist Request
- Name of the game to be whitelisted: Botanicula
- Steam AppID of the game: 207690

## System Information
- GPU: GTX 750
- Driver/LLVM version: NVIDIA 396.54
- Kernel version: 4.18.0-10-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/thackel/45200e1efbb0caf7553cdf0f9175c9d7
- Proton version: 3.7.8

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

**Comment by kisak-valve** [comment]
Found in the 2018-12-11 white list update.
