### ISSUE TITLE
Track mania nations forever no sound effects (menue, car ... musik works)

### ISSUE THREAD

**Issue by toger5** [ValveSoftware/Proton#1918]
# Compatibility Report
- Name of the game with compatibility issues:
Track mania nations forever
- Steam AppID of the game:

## System Information
- GPU: HD7850
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

## Symptoms 
There are no sound effects (for cars, menue ... ) the musik and background sound (wind) is working

**Comment by kisak-valve** [comment]
Hello @toger5, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/467#issuecomment-435698894.

**Comment by toger5** [comment]
oh ty very much. sorry for bad report in general... little time. hope it is still better than no report..
