### ISSUE TITLE
Witcher 3 - can't use kb/mouse

### ISSUE THREAD

**Issue by qsecofr** [ValveSoftware/Proton#1927]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher 3: Wild Hunt
- Steam AppID of the game: 292030

## System Information
- GPU: RX 580 8GB
- Driver/LLVM version: Mesa 18.1.7-208.1
- Kernel version: 4.18.15-1.2
- Link to full system information report as [Gist](https://gist.github.com/): 
   https://gist.github.com/qsecofr/6de931cc0639fab425ee26b7aeac9230.js
- Proton version: 3.16-4 Beta (3.7-8)

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-292030.log](https://github.com/ValveSoftware/Proton/files/2554562/steam-292030.log)

## Symptoms 
When I launch Witcher 3 I am stuck with the controller control scheme, Keyboard assignements are empty and I can't use kb/mouse to control the character nor interact with the game. Big Picture shows controller icon. 
I opened a ticket with steam support (Ticket: HT-VQJ4-RCXT-865Y), they pointed me to github/proton.

## Reproduction
Everytime I start the game

None found

**Comment by kisak-valve** [comment]
Hello @qsecofr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-436368790.
