### ISSUE TITLE
Witcher 3 (292030) Vega 64 support

### ISSUE THREAD

**Issue by bogdans41472** [ValveSoftware/Proton#1929]
# Compatibility Report
- Witcher 3 Wild Hunt
- Steam AppID of the game: 292030

## System Information
- GPU: Vega 64
- Driver/LLVM version: 4.5.13540 Compatibility Profile Context 18.40.2.15
- Kernel version: 4.15.0-38-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Sebi1436/b11eeea0ed0b7bea45ee0cd8ffa59a37
- Proton version: 3.16-4 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When loading save games, Wine stops responding.

## Reproduction
1. Start game
2. Continue story
3. Wait for story cinematic
4. Loading bar is displayed
5. Observe freeze

Note, I have also tried installing mesa-vulkan-drivers and vulkan-utils from the default ubuntu ppa, but that didn't help at all, so I stuck with the latest drivers from AMD - 18.4.

Additionally, I have also tried starting a new game, but the same issue occurred after the beginning cinematic.

**Comment by kisak-valve** [comment]
Hello @bogdans41472, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-436428898.
