### ISSUE TITLE
Doom (2016) performance is terrible! (379720)

### ISSUE THREAD

**Issue by RCal-Dev** [ValveSoftware/Proton#194]
When trying to play DOOM (2016), I get terrible performance using Vulkan or OpenGL, stuttering at 30 fps. On Windows, this game usually runs past 100 fps for me. What could be causing this performance dip?

System: Ubuntu 18.04.1 (Linux Kernel 4.18.4)
Processor: AMD R5 1600
Graphics Card: AMD Radeon RX 480
Memory: 16gb DDR4 2933mhz
Drive: 7200rpm NTFS formatted internal drive (Not a windows-install drive, just NTFS formatted) 2TB

**Comment by vanyasem** [comment]
What graphics drivers are installed on your system?

**Comment by RCal-Dev** [comment]
According to GLXINFO, Mesa 18.1.0-rc4

Should also note: Using AMDGPU 18.30-633530

**Comment by yaomtc** [comment]
> ## Core OpenGL games (DOOM 2016, Google Earth VR, etc):
> 
> You will need Mesa 18.2.0 at a minimum.

https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md

RTFM

**Comment by RCal-Dev** [comment]
Yeah, which is why I went ahead and uninstalled AMDGPU. I thought I was running at 18.3 already, turns out the drivers in AMDGPU were overriding that. Back at MESA 18.3, will test in a bit.

**Comment by RCal-Dev** [comment]
Performance is still bad, linked a screenshot of game (running the uac arcade mode, just took a screenshot when I fell down)
![screenshot from 2018-08-22 17-57-59](https://user-images.githubusercontent.com/16506004/44498758-4a9bc480-a635-11e8-9e28-a60be606ce1d.png)

**Comment by RCal-Dev** [comment]
I noticed the CPU was spiking a ton. I let the game play longer this time, and as I was playing, the spikes went down and the game returned to how it would perform on Windows. Odd. Should I go ahead and close this issue?

**Comment by kisak-valve** [comment]
Hello @RaptorRCX, that would indicate that the video driver was busy compiling shaders.

**Comment by RCal-Dev** [comment]
Thanks, Kisak. That's probably the issue, so I guess this is normal. Thanks for the help.
