### ISSUE TITLE
Dark Souls III low fps drops since 3.16 

### ISSUE THREAD

**Issue by icemanx7** [ValveSoftware/Proton#1942]
Using proton 3.7.8 I get full 60fps on Dark Souls 3 but using the latest 3.16.4 beta I get drops to about 30fps on with both settings on max.

GPU: GTX 1060
CPU: 2400g
RAM 16G
OS: Arch Linux
Nvidia Drivers: 410.66

**Comment by kisak-valve** [comment]
Hello @icemanx7, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/478#issuecomment-437585507.
