### ISSUE TITLE
Proton fails to build in Linux (arch)

### ISSUE THREAD

**Issue by redstik** [ValveSoftware/Proton#1944]
After completing what seems to be a full compile, this error appears and quits (previous line included for context):
``make[1]: Leaving directory '/home/two/proton/mybuild'``
``make: *** [../build/makefile_base.mak:15: nested_make] Error 2``

Installed all necessary prereqs to the compile, cant figure out what it could be.

**Comment by ah-** [comment]
How exactly did you try to build it?

Can you include the whole log? These two lines just say that something earlier has gone wrong.

**Comment by redstik** [comment]
I tried to ``make`` again, it reconfigured by the looks of it and just spat out those 2 lines. I dont know how to access the old log. Should I just recompile from scratch? also I used the guide in the readme with ``--no-steam-runtime ``

**Comment by dreamer** [comment]
I've never successfully completed build with `--no-steam-runtime`, but it's pretty easy to build using Docker - so I would recommend doing that first. I documented all steps on wiki: https://github.com/ValveSoftware/Proton/wiki/Build-instructions-(Fedora) - if you'll manage to build it on Arch, it would be nice to document it as well (preferably on separate page).

**Comment by redstik** [comment]
@dreamer It doesnt build with the runtime, using ``make -j13 all dist``. Logging it with STDERR as well, here is the file.
[makej13alldist.log](https://github.com/ValveSoftware/Proton/files/2568563/makej13alldist.log)

**Comment by nsivov** [comment]
@redstik you'll need to install fontforge. From your log:

fontforge -quiet -script ../fonts/scripts/generatefont.pe obj-fonts/LiberationSans-Regular.sfd "Arial" "Arial" "Arial"
/bin/sh: fontforge: command not found
make[1]: *** [../build/makefile_base.mak:969: obj-fonts/LiberationSans-Regular.ttf] Error 127
make[1]: *** Waiting for unfinished jobs....

**Comment by redstik** [comment]
after installing fontforge and compiling, it errors out again. here is the log after running make for the second time.
[my.log](https://github.com/ValveSoftware/Proton/files/2569973/my.log)
EDIT: running ``make install`` installs sucessfully, however the build fails to launch any games.

**Comment by lieff** [comment]
```
In file included from ../../include/d3d10sdklayers.h:31:0,
                 from ../../include/d3d10.h:5757,
                 from ../../include/d3d10_1.h:48,
                 from ../../include/d2d1.h:257,
                 from ../../../../wine/dlls/dwrite/dwrite_private.h:20,
                 from ../../../../wine/dlls/dwrite/analyzer.c:26:
../../include/ocidl.h:9:0: internal compiler error: Segmentation fault
```
Compiler crash.

**Comment by redstik** [comment]
What should I do?

**Comment by lieff** [comment]
Well, most simple way - try another compiler version. Or try fire compiler bug, they will probably ask to try latest git, because bug can be already fixed upstream.

**Comment by redstik** [comment]
by the looks of it, this is a ryzen hardware issue.
after disabling ASLR ``echo 0 | sudo tee /proc/sys/kernel/randomize_va_space``
 and toning down my overclock on CPU and RAM it compiled sucessfully.
Thanks.

**Comment by Rabcor** [comment]
did you try the AUR package?

**Comment by GloriousEggroll** [comment]
@redstik I was able to duplicate this problem in a debian VM with my threadripper host cpu structure passed through, that resolved it for me as well

-edit-

that fix got past the first one, but it came back to haunt me again 
```
-- Installing: /home/ge/proton/mybuild/obj-tools32/share/openal/presets/square.ambdec
-- Installing: /home/ge/proton/mybuild/obj-tools32/share/openal/presets/presets.txt
make: Leaving directory `/home/ge/proton/mybuild/obj-openal32'
mkdir -pv ./dist/dist/lib/wine/
mkdir -p ./dist/dist/lib64
mkdir -p ./dist/dist/lib
cp -a ./obj-lsteamclient64/lsteamclient.dll.so ./dist/dist/lib64/wine/
cp -L ./obj-tools64/lib/libopenal* ./dist/dist/lib64/
cp -a ./obj-lsteamclient32/lsteamclient.dll.so ./dist/dist/lib/wine/
cp -L ./obj-tools32/lib/libopenal* ./dist/dist/lib/
[ x"strip" = x ] || strip ./dist/dist/lib64/libopenal.so
[ x"strip" = x ] || strip ./dist/dist/lib/libopenal.so
make[1]: Leaving directory '/home/ge/proton/mybuild'
../build/makefile_base.mak:15: recipe for target 'nested_make' failed
make: *** [nested_make] Error 2
```

**Comment by alasky17** [comment]
I ran into problems when compiling with a -j4 flag.  Compiling without the flag took longer but avoided some issues.

**Comment by dreamer** [comment]
If you have a build failing for random reason like that, I suggest running `make -j1` to see exactly what caused a failure. One of the common problems may be e.g. lack of some dependency or not initialized git submodule.

**Comment by GloriousEggroll** [comment]
fixed it. stupid fontforge wasn't installed

somehow missed that in this thread earlier. that should probably be added to the readme

**Comment by aeikum** [comment]
Yes, we missed adding fontforge to the readme. Sorry about that. It will be added soon.

**Comment by omentic** [comment]
Adding onto this, the newest update also does not install on Manjaro (derivative of Arch). [Here's my build log in a Gist.](https://gist.github.com/j-james/9e2232c2cdfa9d7a4295458ab1f446a6) This is from the AUR, I have not tried compiling from source. 

It doesn't seem to be the same error.

**Comment by kisak-valve** [comment]
Hello @j-james, AUR packaging issues should be reported to the package maintainer (in the AUR).

**Comment by aeikum** [comment]
Fontforge is now documented via the Vagrant setup files. OK to close this?

**Comment by GloriousEggroll** [comment]
@aeikum I was able to make a test build last night without issue, it's safe to close IMO

**Comment by fls2018** [comment]
Hello I'm having this issue but with the vagrant VM, if someone can explain what I'm doing wrong it would be great:

```
make dist -f Makefile NO_NESTED_MAKE=1
make[1]: Entering directory '/home/vagrant/proton/mybuild'
cp -n ../fonts/liberation-fonts/src/LiberationSans-Regular.sfd ../fonts/liberation-fonts/src/LiberationSans-Bold.sfd ../fonts/liberation-fonts/src/LiberationSerif-Regular.sfd ../fonts/liberation-fonts/src/LiberationMono-Regular.sfd obj-fonts
cp -n ../fonts/liberation-fonts/src/LiberationSans-Regular.sfd ../fonts/liberation-fonts/src/LiberationSans-Bold.sfd ../fonts/liberation-fonts/src/LiberationSerif-Regular.sfd ../fonts/liberation-fonts/src/LiberationMono-Regular.sfd obj-fonts
cp -n ../fonts/liberation-fonts/src/LiberationSans-Regular.sfd ../fonts/liberation-fonts/src/LiberationSans-Bold.sfd ../fonts/liberation-fonts/src/LiberationSerif-Regular.sfd ../fonts/liberation-fonts/src/LiberationMono-Regular.sfd obj-fonts
fontforge -quiet -script ../fonts/scripts/generatefont.pe obj-fonts/LiberationSans-Regular.sfd "Arial" "Arial" "Arial"
fontforge -quiet -script ../fonts/scripts/generatefont.pe obj-fonts/LiberationSans-Bold.sfd "Arial-Bold" "Arial" "Arial Bold"
fontforge -quiet -script ../fonts/scripts/generatefont.pe obj-fonts/LiberationSerif-Regular.sfd "TimesNewRoman" "Times New Roman" "Times New Roman"
mkdir -p dist/dist/share/fonts
cp ./obj-fonts/*.ttf "dist/dist/share/fonts"
mkdir -p obj-wine64
Unable to find image 'steam-proton-dev:latest' locally
docker: Error response from daemon: pull access denied for steam-proton-dev, repository does not exist or may require 'docker login'.
See 'docker run --help'.
../build/makefile_base.mak:234: recipe for target 'obj-wine64' failed
make[1]: *** [obj-wine64] Error 125
make[1]: Leaving directory '/home/vagrant/proton/mybuild'
../build/makefile_base.mak:17: recipe for target 'nested_make' failed
make: *** [nested_make] Error 2
```
