### ISSUE TITLE
Rise of Nations: Extended Edition Sound Problem

### ISSUE THREAD

**Issue by hsnnsnc** [ValveSoftware/Proton#1947]
# Compatibility Report
- Name of the game with compatibility issues: Rise of Nations: Extended Edition
- Steam AppID of the game: 287450

## System Information
- GPU: GeForce GTX 1050 Ti
- Driver/LLVM version: nvidia 410.73
- Kernel version: 4.18.0-10-generic
- Proton version: 3.16-4 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 ISSUE
Rise of Nations: Extended Edition of has no sound.

OS
Ubuntu 18.10

STEPS

Select Library from the main menu
Select All Games
Select Rise of Nations: Extended Edition
Click Play

RESULTS
Rise of Nations: Extended Edition has been opened but there is no sound.

EXPECTED
ise of Nations: Extended Edition should be the sounds of the game.

**Comment by kisak-valve** [comment]
Hello @hsnnsnc, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/298#issuecomment-437632220.
