### ISSUE TITLE
All VR games are not working

### ISSUE THREAD

**Issue by TheHellBox** [ValveSoftware/Proton#1948]
# Compatibility Report
- Name of the game with compatibility issues: Google Earth VR or any other VR game
- Steam AppID of the game:

## System Information
- GPU: Nvidia GTX 960
- Driver/LLVM version: nvidia 396.51 / nvidia 410
- Kernel version: x86_64 Linux 4.9.0-7-amd64
- System information report: https://gist.github.com/TheHellBox/b8100f1b30314aecb1b12ad80c9d0573
- Proton version: Any, tried both 3.7-8 and 3.16-4

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-348250.log](https://github.com/ValveSoftware/Proton/files/2569149/steam-348250.log)

## Symptoms
VR games just refuse to init OpenVR(eg black screen or they go into non VR mode)
Google Earth VR crashes on startup with `VRInitError_Init_PathRegistryNotFound`

## Reproduction

Install SteamVR

Install any Proton Game(Google earth VR for example)

**Comment by FictionX** [comment]
VR works fine for me. You need Nvidia driver v396.54.09 (you mention that you're using v396.51):

https://github.com/ValveSoftware/Proton/wiki/Requirements

**Comment by aeikum** [comment]
Is VR working for you outside of Proton? For example, do you see anything in the headset when you run SteamVR? You may need to launch SteamVR first before trying to launch a VR title.

**Comment by TheHellBox** [comment]
Yep, all native games are working(SteamVR home, vive craft). Also I reinstalled the system, didn't help at all. Will try to install 396.54, will see if it will help

**Comment by aeikum** [comment]
Updating your drivers is a good idea.  Beyond that, I can think of two useful things you could do. First would be to launch Steam itself from a Terminal and see if it outputs any obvious error messages when running a VR game.  If not, then you can try editing user_settings.py to gather a log with +vrclient. See the README for more information about user_settings.py. The line to change would become:
`    "WINEDEBUG": "+timestamp,+pid,+tid,+seh,+debugstr,+module,+vrclient",`

**Comment by TheHellBox** [comment]
Installed nvidia 396.54 driver, didin't help. There is a log for google earth VR
[steam-348250.log](https://github.com/ValveSoftware/Proton/files/2582014/steam-348250.log)

**Comment by FictionX** [comment]
.. and you're on 396.54.09? The .09 is important.

**Comment by TheHellBox** [comment]
This one
![default](https://user-images.githubusercontent.com/21022722/48551696-19f7be00-e8f8-11e8-9a86-6719825a7784.png)

**Comment by FictionX** [comment]
You need Developer Beta Driver 396.54.09:
https://developer.nvidia.com/vulkan-driver

**Comment by aeikum** [comment]
That shouldn't prevent VR from working. The .09 is only important for transform feedback support, which usually manifests as missing models in the game, not a failure to initialize VR.

**Comment by TheHellBox** [comment]
There is a small video with the problem https://youtu.be/3qw75CGZ7ec

**Comment by aeikum** [comment]
Did you try running Steam itself from a Terminal and seeing if it dumps any errors when you try to launch a VR game? Keywords to look for are "Traceback" and "Proton". It looks like we're failing to detect the SteamVR installation in Proton, so the game never tries to load vrclient.

**Comment by FictionX** [comment]
> That shouldn't prevent VR from working. The .09 is only important for transform feedback support, which usually manifests as missing models in the game, not a failure to initialize VR.

You're probably right.. Sorry for giving wrong information. I had problems getting it to work myself, and read somewhere that .09 was needed. I thought it was in the official instructions, but apparently not. It did however solve the problem for me.

**Comment by TheHellBox** [comment]
There is the error. Found it `Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Application Data\openvr\openvrpaths.vrpath
`

**Comment by TheHellBox** [comment]
Going to look at this file, maybe because I have russian in path

**Comment by TheHellBox** [comment]
No luck with that. This file is temporary and it was created and removed at the same time. Anyway, this file contains this: 
[openvrpaths.vrpath.txt](https://github.com/ValveSoftware/Proton/files/2585587/openvrpaths.vrpath.txt)

**Comment by FictionX** [comment]
Which HMD are you using? I noticed from your video that the HMD icon isn't showing - and I'm not sure what the controller icons represent?
Does your System Information still say "VR Headset: None detected" after updating the driver?

**Comment by TheHellBox** [comment]
I'm using OpenHMD emulated HMD. https://github.com/ChristophHaag/SteamVR-OpenHMD

**Comment by aeikum** [comment]
Neat, I didn't know that existed. My guess is the game is expecting something from the VR config files that OpenHMD is not providing. You could ask the OpenHMD author to look into this, they might find it interesting.

**Comment by TheHellBox** [comment]
The thing is that it worked 4 months ago. And it was nice, no errors at all, also OpenHMD-SteamVR author have no idea why it isn't working, already asked him

**Comment by aeikum** [comment]
OK. All this info would have been useful in the initial report :) I don't think we'll have time to look into this in the near term, but if it worked before, it may not be hard for you or some interested developer to fix.

**Comment by FictionX** [comment]
I agree with Aeikum that the issue is probably with OpenHMD rather than with SteamVR - even if it's maybe caused by an update to Proton or something. 

Maybe you could convince Christoph Haag to test it himself? He's very active in the community, and usually very helpful. That way he could verify if this is an issue with OpenHMD or with your specific configuration.

**Comment by TheHellBox** [comment]
![default](https://user-images.githubusercontent.com/21022722/48560443-9fd33380-e90f-11e8-9936-8665f8edd810.png)

**Comment by ChristophHaag** [comment]
Image link for the lazy: https://i.imgur.com/V4OpJCE.png
I tried it with OpenHMD's Vive driver (you can see SteamVR showing my very sophisticated HMD logo for it) and google earth VR works so far, just without controllers it's not very useful.

There really should really not be much of a difference between the official lighthouse SteamVR plugin and the SteamVR-OpenHMD plugin, except the yet to be finished controller support in SteamVR-OpenHMD.

**Comment by FictionX** [comment]
Well... I haven't tried OpenHMD, but the OHMD icon from Christophs screenshot is missing in TheHellBox' video - but instead there are two controller icons? Is that expected?

I would probably try reinstalling from scratch if it was me - but just out of curiosity.. can you run non-VR Proton games? - And is python 3 installed (also a requirement, but I don't know the effect of not having the proper version installed)

**Comment by h1z1** [comment]
@TheHellBox https://github.com/ValveSoftware/SteamVR-for-Linux/issues/89#issuecomment-357093897

**Comment by TheHellBox** [comment]
@h1z1 Thanks! It works now.

**Comment by TheHellBox** [comment]
The problem was cyrillic in driver path, I don't know why it was there, but after changing path it works again
