### ISSUE TITLE
Shantae: Half-Genie Hero works perfectly in 64-bit Wine; crashes on launch with Proton (253840)

### ISSUE THREAD

**Issue by yaomtc** [ValveSoftware/Proton#195]
With a recent 64-bit Wine installation, and a 64-bit Wine prefix and WINEARCH, [Shantae: Half-Genie Hero](https://store.steampowered.com/app/253840/) performs perfectly. I [would have rated it Platinum on Wine's AppDB](https://appdb.winehq.org/objectManager.php?sClass=version&iId=34622) if it weren't for the fact that the 32-bit version of the game doesn't really work at all, with about 1 frame per second. Using Proton, you get that same poor result when you try to launch the game (it uses the 32-bit code), but if you choose "64-bit DX11", the game crashes when you try to launch it. Here's the terminal output.

[shantae64crash.txt](https://github.com/ValveSoftware/Proton/files/2312371/shantae64crash.txt)

Software: Ubuntu 18.04.1 (64-bit), Mesa 18.3.0, LLVM 8.0
Hardware: Intel i5-4690k, Radeon RX 580

**Comment by LeJimster** [comment]
I could be wrong, but looking at the crash log it appears to be trying (and failing) to use your cpu's onboard gpu with Vulkan.  Could it be that Vulkan isn't setup correctly on your machine? Wrong icd loader or something?  Try running vulkaninfo and see what it spits out.

Also, have you also tried running it in OpenGL rather than DXVK?
Go into the games Properties, select "Set Launch Options" and try
`PROTON_USE_WINED3D11=1 %command%`

**Comment by yaomtc** [comment]
Well, OpenGL works just fine! Something must be wrong with the Vulkan setup, but... nothing is plugged into the motherboard's video output, and this is a fresh Ubuntu install, so everything is default.

Dear god that's a lot of output.

[vulkaninfo.txt](https://github.com/ValveSoftware/Proton/files/2312995/vulkaninfo.txt)

**Comment by commandhat** [comment]
It appears you may be running a hybrid graphics card.

Vulkan reports two active GPU sources: The integrated graphics chip that comes with most CPUs, and an actual graphics card running in discrete mode. You may want to reconfigure your graphics pipeline to use the discrete GPU instead (see the instructions listed in [this article](https://wiki.archlinux.org/index.php/PRIME) for more information on doing that).

**Comment by yaomtc** [comment]
It's just a regular desktop PCI-e graphics card, nothing hybrid about it. Doesn't seem relevant.
```
$ xrandr --listproviders
Providers: number : 2
Provider 0: id: 0x90 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 6 outputs: 5 associated providers: 0 name:Radeon RX 580 Series @ pci:0000:02:00.0
Provider 1: id: 0x45 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 3 associated providers: 0 name:modesetting
```
```
$ glxinfo | grep "OpenGL renderer"
OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.23.0, 4.15.0-32-generic, LLVM 8.0.0)
```

For what it's worth, I just now went to my BIOS and disabled the IGD multi monitor feature, which disables the shared memory, but that doesn't seem to have changed anything for this, vulkaninfo still looks the same I think. Might not have been relevant for this.

**Comment by yaomtc** [comment]
The 64-bit version also crashes on Proton 3.7-3 and on -4 Beta. However, 32-bit now works in those versions! I do get unavoidable screen tearing though... Any way to force v-sync, since this game doesn't have an option for it?

EDIT: The tearing occurs on Ubuntu with Gnome, but not on Solus with Budgie. Should I edit the title for tearing instead, or just close this issue and open a new one?

**Comment by yaomtc** [comment]
Since the game works fine now (aside from the tearing issue) I'm gonna go ahead and close this.
