### ISSUE TITLE
Scaling issues in Dark Souls II: Scholar of the First Sin (335300)

### ISSUE THREAD

**Issue by rihardsk** [ValveSoftware/Proton#1953]
Screen scaling is broken for all resolutions except 1280x720 in windowed mode:
- In full-screen mode in any resolution there's a white clipped border area on the right part and on the lower part of the screen and mouse inputs seem to be offset by the size of the border.
- In windowed mode with resolution greater than 1280x720 same thing happens as in the full-screen case above.
- In windowed mode with resolution below 1280x720 the game screen renders correctly (without any clipped areas) but mouse inputs are still off by some amount.

The issue is worse if i use a 1920x1080 external monitor (instead of the 1366x768 builtin display of my laptop).

I'm running the game with these options:
```
PROTON_USE_WINED3D11=1 optirun %command%
```

Here's the log: [steam-335300.log](https://github.com/ValveSoftware/Proton/files/2569975/steam-335300.log)

Here's my [system's info](https://gist.github.com/rihardsk/ac00bfc43d09a88cdf1b94dc567b8f21). What's missing there is that i have a dedicated GT530m GPU on which i'm running the game using bumblebee.

I haven't tested other games on Steam Play so i'm not sure whether the issue is exclusive to Dark Souls 2 or not.

**Comment by kisak-valve** [comment]
Hello @rihardsk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/137#issuecomment-437717955.
