### ISSUE TITLE
Witcher 3 not running when esync is used

### ISSUE THREAD

**Issue by bit-stone** [ValveSoftware/Proton#1954]
## System Information
- GPU: RX480
- Driver/LLVM version: Mesa 19.0.0-devel - padoka PPA
- Kernel version: 4.18.14-041814-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kzoltner/934cc4d079afaebb660ccc566a19632c
- Proton version: 3.16-4 Beta

## PROTON_LOG
https://gist.github.com/kzoltner/280a6af0acf5b561e924171aa86fa8cc

## Symptoms
Hey there,

I do have a small problem with Witcher 3 on Steam Play.
A little while ago it worked out of the box without me changing anything. Had similar performance to Windows.

Today I wanted to play again but I was unable to get it working.

I start the game, wait a few seconds. Screen turns black and I get quite some load on my CPU.
I can see some copyright text appear at about 0.5 frames per second. I can skip that but the game crashes.

If I disable ESYNC by using
PROTON_NO_ESYNC=1 %command%
it does start without any problems but I only get around 15 to 35 FPS and sometimes during a fight the game just locks up and I need to restart my computer.

**Comment by kisak-valve** [comment]
Hello @kzoltner, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-437718438.
