### ISSUE TITLE
Steam Play miss 1800p resolution

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#1955]
Add the option for 3200x1800 resolution, it´s a very common resolution on Game consoles and gives a 4K image quality with lower system resource usage. It shoud be integrated into proton instead wine as it is a game driven application.

**Comment by Kreyren** [comment]
Why would you want such a resolution for a non-console games? Afaik this resolution will cause a black bars in upper and bottom position of the screen (assuming that you didn't make 3200x1800 monster from scratch).

Anyhow i like the idea to have something like resolution variable in `Steam/<GAME>/Properties` to chose the resolution using GUI since this option is present using [Steam Launch Options](https://support.steampowered.com/kb_article.php?ref=1040-JWMT-2947) namely `-w` and  `-h` variable.

**Comment by ghost** [comment]
> Why would you want such a resolution for a non-console games? Afaik this resolution will cause a black bars in upper and bottom position of the screen (assuming that you didn't make 3200x1800 monster from scratch).
> 
> Anyhow i like the idea to have something like resolution variable in `Steam/<GAME>/Properties` to chose the resolution using GUI since this option is present using [Steam Launch Options](https://support.steampowered.com/kb_article.php?ref=1040-JWMT-2947) namely `-w` and `-h` variable.

at least on windows and consoles there's no black bars on the screen, it just works. There's a lot of games that 4K demands to much from the GPU and 1440p is to little, 1800p is great middle ground resolution that gives around 80% pixels from a 4k screen. Lot's of PS4pro titles operates in 1800p. The idea of a resolution variable is also good.

**Comment by Kreyren** [comment]
> at least on windows and consoles there's no black bars on the screen, it just works. There's a lot of games that 4K demands to much from the GPU and 1440p is to little, 1800p is great middle ground resolution that gives around 80% pixels from a 4k screen. Lot's of PS4pro titles operates in 1800p. The idea of a resolution variable is also good.

afaik consoles and Windows usually just deforms the image if you are using different resolution from your system-wide display resolution. 

On linux if you use wrong resolution the X just apply just place it and fills the rest with graphical glitches by default for example. 

Deforming game resolution is just terrible to watch to me, but i agree with steam GUI for `-w` and `-h`. 

If you really want to use this resolution use launch option as mensioned before and add:
```-w 1800 -h 3200```

EDIT: I disagree with deforming the game resolution by default.. It may increase the FPS, but it looks terrible..

**Comment by ghost** [comment]
> > at least on windows and consoles there's no black bars on the screen, it just works. There's a lot of games that 4K demands to much from the GPU and 1440p is to little, 1800p is great middle ground resolution that gives around 80% pixels from a 4k screen. Lot's of PS4pro titles operates in 1800p. The idea of a resolution variable is also good.
> 
> afaik consoles and Windows usually just deforms the image if you are using different resolution from your system-wide display resolution.
> 
> On linux if you use wrong resolution the X just apply just place it and fills the rest with graphical glitches by default for example.
> 
> Deforming game resolution is just terrible to watch to me, but i agree with steam GUI for `-w` and `-h`.
> 
> If you really want to use this resolution use launch option as mensioned before and add:
> `-w 1800 -h 3200`
> 
> EDIT: I disagree with deforming the game resolution by default.. It may increase the FPS, but it looks terrible..

Thanks for the answer  Kreyken, even if valve doesn´t aprove the feature you already gave me a reasonable way to make it work.

**Comment by parkerlreed** [comment]
@Kreyren 3200x1800 is still 16:9. There shouldn't be any stretching involved. Maybe a little scaling, but Proton is already scaling for lower resolutions than native.

**Comment by parkerlreed** [comment]
Also 3200x1800 is QHD+. Fairly common in laptops

https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=13-inch+Laptop+QHD+Display

**Comment by Kreyren** [comment]
> Thanks for the answer Kreyken

I AM NOT KREY**K**EN!!!!!!!!!

**K R E Y R E N... KREYREN!! KREY..REN! KREEEEYREEEEEEEENNNNNN!!!!**

**Comment by Kreyren** [comment]
> Also 3200x1800 is QHD+. Fairly common in laptops
> 
> https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=13-inch+Laptop+QHD+Display

I wasn't aware of that thanks for info. *thinking about forking notebook display into a 1800p monitor now*

Isn't this resolution detected by a game itself if it's invoked on notebook? Afaik proton should adjust to game settings.

**Comment by ghost** [comment]
@Kreyren the code "-w 1800 -h 3200" in launch options worked, but as you said, i got blackbars on the screen. Now we need some scaling as @parkerlreed said. Is there command in launch options for that ?

**Comment by Kreyren** [comment]
> @Kreyren the code "-w 1800 -h 3200" in launch options worked, but as you said, i got blackbars on the screen. Now we need some scaling as @parkerlreed said. Is there command in launch options for that ?

I'm not aware of this configuration via [Steam Launch Option](https://support.steampowered.com/kb_article.php?ref=1040-JWMT-2947), but proton is able to scale it automatically. 

So my theory is that it scaled it like that so you woudn't have deformations of pixels with this resolution.

**Comment by tamodolo** [comment]
I think the idea is somewhat a thing I do a lot: 3200x1800 scaled to 4k.

1800p indeed is a great middle ground when you have a GPU that isn't enough for native 4k like the flawed gtx 1080.

In a native 4k panel, 1800p will look a lot better than 1080p. 1440p isn't really an option as it is too much close to 1080p to users see any improve. But starting from 2880x1620 you do get a good improve over 1080p.

A easy way to configure that insite steam would be awesome as resolution scaling is very hard for average users to get working.

**Comment by ghost** [comment]
@tamodolo thanks for the point. [Proton-tkg](https://github.com/Tk-Glitch/PKGBUILDS) already has this option. If valve wants it can be done. I recomend you give it a try.

**Comment by jarrard** [comment]
no progress with this? I'm finding games that have missing 1800p options. Also those -w -h commands are for SOURCE engine games.

**Comment by ghost** [comment]
No progress... nowadays i just stick to proton-tkg, it has all the missing features including custom resolutions. You grab a pre-compiled build compatible with any distribution here:

https://github.com/Tk-Glitch/PKGBUILDS/releases

**Comment by jarrard** [comment]
> No progress... nowadays i just stick to proton-tkg, it has all the missing features including custom resolutions. You grab a pre-compiled build compatible with any distribution here:
> 
> https://github.com/Tk-Glitch/PKGBUILDS/releases

Do you know if there is a build that works with KCD? I'm using Proton-4.11-GE-1 atm but it doesn't have the 1800p patch. There is a big regression in latest proton with KCD and likely other games, not sure if valve is going to fix it.

**Comment by benjamimgois** [comment]
I don't know man... i don't have KCD for testing. But the latest lutris installer uses the wine-tkg-4.0 build.

https://lutris.net/games/install/7347/view

**Comment by ghost** [comment]
> > No progress... nowadays i just stick to proton-tkg, it has all the missing features including custom resolutions. You grab a pre-compiled build compatible with any distribution here:
> > https://github.com/Tk-Glitch/PKGBUILDS/releases
> 
> Do you know if there is a build that works with KCD? I'm using Proton-4.11-GE-1 atm but it doesn't have the 1800p patch. There is a big regression in latest proton with KCD and likely other games, not sure if valve is going to fix it.



> > No progress... nowadays i just stick to proton-tkg, it has all the missing features including custom resolutions. You grab a pre-compiled build compatible with any distribution here:
> > https://github.com/Tk-Glitch/PKGBUILDS/releases
> 
> Do you know if there is a build that works with KCD? I'm using Proton-4.11-GE-1 atm but it doesn't have the 1800p patch. There is a big regression in latest proton with KCD and likely other games, not sure if valve is going to fix it.

I don't know man... i don't have KCD for testing. But the latest lutris installer uses the wine-tkg-4.0 build.

https://lutris.net/games/install/7347/view

**Comment by jarrard** [comment]
I managed to figure out howto do it via EDID editing and switching to 1800p before launching the game. Still it would have been nice for proton to support all resolutions and just use its scaling system to stretch.

Games still fail to detect 3200x1800 as a option unless I switch to this resolution via desktop where it is present and selectable. This means steamplay is not seeing 1800p as a valid resolution option unless that is what desktop is set too.

**Comment by jarrard** [comment]
Has this been resolved in the latest proton version?  (by adding in the missing sub resolutions)
I know its still good in TKG releases, but NOT in Proton-GE releases.

**Comment by ghost** [comment]
@jarrard it is fixed in proton 5.13 and latest TKG, but GE is lacking the FS hack.

**Comment by kisak-valve** [comment]
Closing as fixed in https://github.com/ValveSoftware/wine/commit/9ad09babd5c9758ce6a5433f490e5590ce3956df.
