### ISSUE TITLE
Game documents path definition in proton.

### ISSUE THREAD

**Issue by Kreyren** [ValveSoftware/Proton#1959]
Asking for verification of https://github.com/ValveSoftware/Proton/wiki/Proton-FAQ#where-are-game-documents-defined-in-proton

Looks like the correct path for Game Documents to me (mensioned folder in linux has the same data as windows version), contributed based on my personal experience with 20920 (The Witcher 2 EE).

- Krey

**Comment by aeikum** [comment]
The Witcher 2 is a native Linux game, so its save data location doesn't belong on the Proton wiki. I removed that section. Please refer to the other existing FAQ entries if you need to locate the data for games that do run in Proton.

**Comment by Kreyren** [comment]
> The Witcher 2 is a native Linux game, so its save data location doesn't belong on the Proton wiki. I removed that section. Please refer to the other existing FAQ entries if you need to locate the data for games that do run in Proton.

Sorry my fault.
