### ISSUE TITLE
Fallout Shelter Game crashes on launch. (588430)

### ISSUE THREAD

**Issue by OMTDesign** [ValveSoftware/Proton#196]
Hello.

After launching Fallout Shelter, it immediately crashes and displays a dialogue box pointing to the crash dump file.

![screenshot from 2018-08-23 12-08-07](https://user-images.githubusercontent.com/39666543/44497552-38ba3000-a6ce-11e8-9605-2910fdd73ec6.png)

My Specs are:
HP Zbook 15
Ubuntu 16.04 
Linux Kernel 4.15.0-32
4700MQ Intel CPU
32GB Ram
K2100M Quadro GPU Nvidia driver 384.130

[2018-08-23_120748.zip](https://github.com/ValveSoftware/Proton/files/2312374/2018-08-23_120748.zip)

**Comment by kisak-valve** [comment]
Hello @OMTDesign, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by OMTDesign** [comment]
https://gist.github.com/OMTDesign/f0139824b9b23572b021be4764136472

**Comment by kisak-valve** [comment]
Your video drivers are older than the [prerequisites](https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md). On the Intel side, you have a haswell, which has an incomplete implementation of vulkan and #65 applies to the nvidia side with the optimus-based laptop.

**Comment by OMTDesign** [comment]
Yeah there seemed to be an issue with optimus not engaging the GPU. But I don't know what happened but on my third restart Fallout Shelter now opens, and its running fine.
![screenshot from 2018-08-23 13-05-21](https://user-images.githubusercontent.com/39666543/44498858-43c48e80-a6d5-11e8-8ac5-59d334a90a3e.png)
