### ISSUE TITLE
Castlevania : Lords of Shadow Ultimate Edition - crash at start up

### ISSUE THREAD

**Issue by darkpumpkins** [ValveSoftware/Proton#1960]
# Compatibility Report
- Name of the game with compatibility issues: Castlevania : Lords of Shadow Ultimate Edition, crash at launch
- Steam AppID of the game: 234080

## System Information
- GPU: GTX 1070 ti
- Driver/LLVM version: nvidia 396.54.09
- Kernel version: 4.18.0-11-generic
- Link to full system information report as [Gist](https://gist.github.com/):
[config.txt](https://github.com/ValveSoftware/Proton/files/2578429/config.txt)
- Proton version: 3.16-4beta and olders

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-234080_chunk.log](https://github.com/ValveSoftware/Proton/files/2578444/steam-234080_chunk.log)
I had to take a piece of the log cause it reached more than 70Mb .... 

## Symptoms 
The game doesn't launch at all. i try with all version of proton, with a GTX 970 and a GTX 1070 ti on both gnome-shell or openbox Window manager.

## Reproduction
Just run the game with any version of proton.

**Comment by kisak-valve** [comment]
Hello @darkpumpkins, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/443#issuecomment-438472698.
