### ISSUE TITLE
ELEX AppID: 411300  / Game locks up from spawning particle effects

### ISSUE THREAD

**Issue by DPTJKKVH** [ValveSoftware/Proton#1964]
# Compatibility Report
- Name of the game with compatibility issues: ELEX
- Steam AppID of the game: 411300

## System Information
- GPU: NVIDIA GeForce GTX 680
- Driver/LLVM version: NVIDIA 410.73
- Kernel version: 4.18.0-11-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/DPTJKKVH/ac3925811dbf1730099adfa35744ba1b
- Proton version: 3.16-4 Beta

## I confirm:
- [X] that I haven't found an existing compatibility report for this game. // There is none following this template and acknowledging this bug while giving precise information and log files.
- [X] that I have checked whether there are updates for my system available.

Proton log:
[steam-411300.log](https://github.com/ValveSoftware/Proton/files/2581691/steam-411300.log)

Additional error logs produced by the game itself with potentially interesting graphics card information:
[ELEX_35.log](https://github.com/ValveSoftware/Proton/files/2581772/ELEX_35.log)
[ELEX_36.log](https://github.com/ValveSoftware/Proton/files/2581773/ELEX_36.log)

I also have a DMP file produced by the game but I cannot decode/read it to check if it contains sensitive information. If you want @kisak-valve i will send it to you over a non-public channel.

## Symptoms 
The game runs fine as long as no particle effects are shown/spawned. When using the jet-pack, firing an energy weapon or doing other activities repeatedly that spawn particle effects the game quickly locks up. The music continues to play normally but the sound effect tied to the particle effect (e.g. rocket blast of the jet-pack) loops continuously. The game (or wine) must be closed forcefully with ALT+F4 and then confirming a force close. Here is a picture of one of the particle effects in question:

![img_eggsif_248315054169](https://user-images.githubusercontent.com/7238653/48498461-9aee8100-e836-11e8-9eb3-8a5f9926fbc6.jpg)

## Reproduction
The quickest way to reproduce the bug is to start the game and fly around with the jetpack repeatedly. After 10 to 15 minutes tops the game will lock up in the above described way.

**Comment by kisak-valve** [comment]
Hello @DPTJKKVH, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/855#issuecomment-438744171.

Steam uses Google's Breakpad minidumps. There's some info at https://www.chromium.org/developers/decoding-crash-dumps if you want to read them yourself.

**Comment by DPTJKKVH** [comment]
Sorry for double posting @kisak-valve . The original report is both messy and wrong since it doesn't follow the template and states there were no problems with ELEX which is untrue. This is why I thought opening a proper report would be fine. Thanks for the explanation and moving my report. I hope it won't go by the board.

**Comment by ghost** [comment]
> Sorry for double posting @kisak-valve . The original report is both messy and wrong since it doesn't follow the template and states there were no problems with ELEX which is untrue. This is why I thought opening a proper report would be fine. Thanks for the explanation and moving my report. I hope it won't go by the board.

I'm sure Valve won't whitelist a game based on one person's experience (I hope not as compatibility and problems range quite a lot with Proton/Wine from computer to computer and they should know this) so its best to say in the same issue as the whitelist [request] why it shouldn't be whitelisted other than Valve using one issue per unofficially supported game anyway. [Until there's a better idea of what's going on with it].
