### ISSUE TITLE
Force Feedback for Gamepad

### ISSUE THREAD

**Issue by corvusd** [ValveSoftware/Proton#1965]
# Force Feedback for Gamepads

## I confirm:
- In the next games, with Steam in wine-staging or wine have FF with [kozec/dumbxinputemu
](https://github.com/kozec/dumbxinputemu) for Steampad and Xbox360 Wired Gamepads, with Linux default driver for Xbox360 and SC Controller for Steampad, perfectly works:
 - Strider
 - Bionic Commando Rearmed.
 - Darksiders
 - Darksiders Warmastered Edition
 - Sonic Generations

In Proton not FF in any of them. The gamepad work properly but without FF.

## Description 
 Same support like wine or wine-staging.

## Justification [optional]
 Perfect experience in native Steam client

**Comment by alasky17** [comment]
Does FF work in Proton if you turn off "Xbox Configuration Support" in general controller settings?

**Comment by corvusd** [comment]
Yes I configure Xbox Configuration Support and Generic... and setup for a game. Not work.

**Comment by alasky17** [comment]
What is your system information?  (Can be found in Steam under Help)

I tried Sonic Generations with the xbox 306 wired controller.  On my setup, when I turned **off** the Xbox Configuration Support, the rumble was working.  The rumble was only broken for me with the support turned on.

**Comment by corvusd** [comment]
https://gist.github.com/corvusd/9c0c8ff48755fa5e3b59fa366b1edd1f
I remember that I tried this. 
I think that problem whit the xbox360 wired is the Steam driver for gamepad are work on top of linux driver... maybe this are the real problem.
For the Steampad, I don't know. Because I played native games whit rumble. And not are possible use at same time native linux Steam client and Kozec SC Controller.

**Comment by alasky17** [comment]
Could you confirm that you have the Xbox Configuration support for controllers turned off in settings and then upload 2 things:
1) the configuration file located in ~/.steam/userdata/(your user string of #)/config/localconfig.vdf
[if there is more than one folder with a string of numbers in the userdata folder, you can look at the localconf.vdf in each folder, and near the top it will say which steam user the config file is for]
2) a log of Sonic Generations with the xbox 360 controller.  Please add the following extra logging channels to the end of "WINEDEBUG":  +hid,+plugplay,+dinput,+joystick,+tid,+winmm,+xinput

**Comment by corvusd** [comment]
Hello @alasky17 

Finally I turn totally off Steam gamepad driver and finally run whit Rumble:
Strider
Darksiders Warmastered Edition

For Xbox360 Gamepad Wired, with xpad linux driver default.
And Steampad with Kozec SC Controller.

All rest games uninstalled. But I try to reinstall an recheck the rest.

When you say logging channels, is activate debugger variables in Wine?? Because the problem is in proton? Is possible debbuger like wine in proton?

**Comment by alasky17** [comment]
To clarify: where is rumble currently still failing for you?  

There is a brief guide to creating Proton logs here: https://github.com/ValveSoftware/Proton/wiki/Proton-FAQ  
Basically, go to ~/.steam/steam/steamapps/common/[proton version you are using].
Then you need to make a copy of user_settings.sample.py and rename it user_settings.py.  
Edit that file and add the channels I specified in the line titled "WINEDEBUG"  after the basic channels.

**Comment by corvusd** [comment]
In steam in general. Native games and proton. The problem is steam input or this driver. Not work rumble. Almost in this games. I can add native game Mad max. Same issue like proton games. 
I try to report to valve in other place? you know where? We can close this ticket, because not a issue of proton.

**Comment by alasky17** [comment]
I think that the steam-for-linux repo would be the best place: https://github.com/ValveSoftware/steam-for-linux/issues

Thanks for troubleshooting!

**Comment by corvusd** [comment]
Yes, it is exist: https://github.com/ValveSoftware/steam-for-linux/issues/4338 For everyone that will arrive here.
