### ISSUE TITLE
HITMAN 2 (863550) "Denuvo" offline play only.

### ISSUE THREAD

**Issue by lucifertdark** [ValveSoftware/Proton#1972]
# Compatibility Report
- Name of the game with compatibility issues: HITMAN 2
- Steam AppID of the game:863550

## System Information
- GPU: GTX 770
- Driver/LLVM version: nvidia 396.54.09
- Kernel version: 4.15
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/lucifertdark/584c14275612e8e3c4a8070d428d8a02
- Proton version:3.16-4 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-863550.log](https://github.com/ValveSoftware/Proton/files/2584571/steam-863550.log)

## Symptoms 
The game runs perfectly but only offline, unable to connect to the IOI content servers for the online part of the game to function.

## Reproduction
1. Install
2. Run
3. wait for online connection to fail.

**Comment by mati865** [comment]
Remove space from `[x ]` to make look like:
- [x] this

**Comment by MuhammedKpln** [comment]
This is a general problem for Proton. #162

**Comment by lucifertdark** [comment]
Closing this in favour of #162. Thanks Muhammed.
