### ISSUE TITLE
The Room (288160)

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/Proton#1983]
# Compatibility Report
- Name of the game with compatibility issues:  The Room
- Steam AppID of the game:  288160

## System Information
- GPU: NVIDIA Corporation GeForce GTX 1070/PCIe/SSE2
- Driver/LLVM version: 4.6.0 NVIDIA 410.78 (was working with 4.6.0 NVIDIA 390.87)
- Kernel version: 4.18.0-13-generic
- Link to full system information report as [Gist](https://gist.github.com/):  https://gist.github.com/nightsky30/3c0e858e645a6c5cd41f67f9c667e65c
- Proton version: 3.16-6 Beta, (was working in 3.7-8 Beta)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-288160.log](https://github.com/ValveSoftware/Proton/files/2705285/steam-288160.log)

## Symptoms
Game is crashing at startup now with updated NVIDIA drivers and newer version of Proton.

## Reproduction
1. Start the game
2. Notice the crash dialog
3. Manually terminate the game executable

**Comment by kisak-valve** [comment]
Hello @nightsky30, this game is already whitelisted.

**Comment by nightsky30** [comment]
@kisak-valve The game has stopped working for me.  It now crashes at startup.  I'm updating the original post with my current config and details.

**Comment by kisak-valve** [comment]
In the future, please open a new issue report when you have an issue with a whitelisted game instead of recycling/vandalizing your own issue report.

**Comment by nightsky30** [comment]
This appears to be working again with nvidia driver version 415.25, but broken with 410.78.

**Comment by kisak-valve** [comment]
Glad to hear. Closing per the last comment.
