### ISSUE TITLE
DOOM (2016) Crash: vkCreateInstance failed with error (VK_ERROR_OUT_OF_HOST_MEMORY)

### ISSUE THREAD

**Issue by monreal** [ValveSoftware/Proton#1986]
# Compatibility Report
- Name of the game with compatibility issues: DOOM (2016)
- Steam AppID of the game: 379720

## System Information
- GPU: GTX 960
- Driver/LLVM version: nvidia 387.22 (the one shipping with steam os)
- Kernel version: 4.14 (the one shipping with steam os)
- Proton version: both 3.7.-8 and 3.16-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available

## Symptoms
The game crashes with

FATAL ERROR: vkCreateInstance failed wit error (VK_ERROR_OUT_OF_HOST_MEMORY)

A few weeks ago the game worked perfectly on the same system.

**Comment by monreal** [comment]
So, if I set +r_renderapi 0 (OpenGL) the screen just stays black and nothing happens. If I set +r_renderapi 1 (Vulkan) I get the crash I mentioned above.

**Comment by monreal** [comment]
[ErrorLog_11-17-2018__06-20-46pm.txt](https://github.com/ValveSoftware/Proton/files/2592069/ErrorLog_11-17-2018__06-20-46pm.txt)

**Comment by monreal** [comment]
[Crash.steamos.00001.html.txt](https://github.com/ValveSoftware/Proton/files/2592070/Crash.steamos.00001.html.txt)

**Comment by monreal** [comment]
BTW, no idea why it says "r_renderAPI -2", I had it set to 1 at the time of the crash

**Comment by monreal** [comment]
I removed the wine prefix folder manually and let it create a new one, no change. I also uninstalled and reinstalled the whole game, no effect.

Is there anything more I can do?

**Comment by aeikum** [comment]
You likely need to update your nvidia drivers to at least 396.54. I don't know what that entails for SteamOS users, sorry.

**Comment by monreal** [comment]
> 396.54

Tanks, @aeikum.
I have read something like that somewhere else so I guess this is true but... really? I thought SteamOS was the only really supported Linux distribution?

**Comment by aeikum** [comment]
We're mostly focusing on Ubuntu, although we do try to support other distros. But we can't do anything about older drivers, we simply need newer drivers to provide the features that we use. I don't know the status of SteamOS driver support.

**Comment by monreal** [comment]
Well, so the main problem is Valve not updating SteamOS/drivers which should be addressed elsewhere. However, my problem here is that the officially supported game DOOM (2016) used to work on Valve's own distribution using the provided stable Proton. I bought the game because of this, only to find it not working anymore a few days later. While I can understand the technical problem this is a nightmare in user friendliness. Use SteamOS and be told that your drivers are to old. Use another distribution and be told that only SteamOS is supported. It hurts me to say because I love Linux but sadly Steam on Linux is still years behind PS and XBOX in this regard.

**Comment by aeikum** [comment]
> Use another distribution and be told that only SteamOS is supported.

I don't think we've said this anywhere in the Proton documentation. Ubuntu is the primary target distro, like I said.
