### ISSUE TITLE
Building fails :make: *** [nested_make] Error 2

### ISSUE THREAD

**Issue by TheError404** [ValveSoftware/Proton#1994]
When i run "make -j6 all dist" I get this:
make[1]: Leaving directory '/home/user/proton/mybuild'
../build/makefile_base.mak:15: recipe for target 'nested_make' failed
make: *** [nested_make] Error 2
for reference:
uname -a
Linux legend 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Im a bit of a user so any help would be appreciated

**Comment by kisak-valve** [comment]
Hello @TheError404, your log snippet is too late. Please copy a much more before these lines into a [gist](https://gist.github.com) and include a link into this issue report.

**Comment by TheError404** [comment]
ok willco:
https://gist.github.com/TheError404/54b4b2acb60ef3be8438ab1009a2936f

**Comment by TheError404** [comment]
@kisak-valve

**Comment by jsreid13** [comment]
I'm having the same issue, running ```make -j6 all dist``` runs for a couple minues, then ends with the same output saying that nested_make failed. Running ```make install``` then fails quickly saying ```/bin/sh: 1: fontforge: not found```.

**Comment by kisak-valve** [comment]
Hello @jsreid13, assuming you hit the same issue as @TheError404, then this issue was a duplicate of https://github.com/ValveSoftware/Proton/issues/1944#issuecomment-438716803.

**Comment by jsreid13** [comment]
Thank you! Installing fontforge using 
```
sudo add-apt-repository ppa:fontforge/fontforge
sudo apt-get update
sudo apt-get install fontforge python-fontforge 
```
solved the issue and it now builds using make install, thanks!

**Comment by ardadem** [comment]
I'm experiencing same issue. Tried to install fontforge.
[build.log](https://github.com/ValveSoftware/Proton/files/3349387/build.log)
