### ISSUE TITLE
Witcher 3  (292030) - black screen :/

### ISSUE THREAD

**Issue by rafik777** [ValveSoftware/Proton#1997]
# Compatibility Report
- Name of the game with compatibility issues: Witcher 3
- Steam AppID of the game: 292030

## System Information
- GPU: GTX 850M
- Driver/LLVM version: nvidia 410.73
- Kernel version: 4.15.0-39-generic
- Link to full system information report:  [Gist system information](https://gist.github.com/rafik777/294be24356b16a95a70af8e356f2e12b)
- Proton version: 3.16

## Symptoms 
After I start the game I see only black screen (no sound too).
Only thing I can do is killing the process.

[steam-292030.log](https://gist.github.com/rafik777/a1f4bfd74adac98693839773b17da312)

**Comment by kisak-valve** [comment]
Hello @rafik777, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-439711721.
