### ISSUE TITLE
libjpeg-turbo dependency for macOS

### ISSUE THREAD

**Issue by spotlightishere** [ValveSoftware/Proton#2]
libjpeg-turbo depends on `nasm` from Homebrew/MacPorts, as it's not natively provided by the Xcode toolchain.

**Comment by flukejones** [comment]
Other dependencies for macOS seem to be:

- `realpath`
- `i686-w64-mingw32-gcc`
- `x86_64-w64-mingw32-gcc`
- `meson` and `ninja`

**Comment by henrebotha** [comment]
`meson` depends on `ninja` so just `brew install meson` will take care of the latter.

You can get `realpath` using `brew install coreutils`.

I'm no C developer so I'm not sure how to grab the other two.

**Comment by zsxsoft** [comment]
``autoconf`` and ``automake`` is required too

**Comment by petmac** [comment]
`brew install mingw-w64` should work for the mingw dependencies.

**Comment by henrebotha** [comment]
My build fails on:

```
FAILED: src/dxvk/src@dxvk@@dxvk@sta/dxvk_clear_buffer_u.h
/Users/henrebotha/dev/proton/glslang/bin/glslangValidator -V --vn dxvk_clear_buffer_u ../../dxvk/src/dxvk/shaders/dxvk_clear_buffer_u.comp -o src/dxvk/src@dxvk@@dxvk@sta/dxvk_clear_buffer_u.h
/bin/sh: /Users/henrebotha/dev/proton/glslang/bin/glslangValidator: cannot execute binary file
```

The included `glslangValidator` binary is compiled for GNU/Linux. I'm now doing `brew install glslang` & I'll try and use that instead.

**Comment by petmac** [comment]
I deleted that `glslangValidator` locally and the build seemed to continue. Not a proper solution obviously, but time was a factor.

**Comment by 3t0n** [comment]
Change glslangValidator with proper binaries from https://github.com/KhronosGroup/glslang/releases
Vote for https://github.com/ValveSoftware/Proton/issues/29 to make submodule

Also, you can download Proton3.7 dist for MacOS High Sierra [here](https://github.com/3t0n/Proton/releases/tag/20180822)

**Comment by aaronfranke** [comment]
macOS support has been removed: https://github.com/ValveSoftware/Proton/commit/a84120449d8177fa40f3de729e55d238d3c24877

**Comment by nobodywasishere** [comment]
This issue should be closed due to no longer having MacOS support
