### ISSUE TITLE
 Crash Bandicoot N. Sane Trilogy Black screen

### ISSUE THREAD

**Issue by AgostinoA** [ValveSoftware/Proton#2001]
# Compatibility Report
- Name of the game with compatibility issues: Crash Bandicoot N. Sane Trilogy
- Steam AppID of the game:731490

## System Information
- GPU: NVIDIA Corporation GeForce GTX 860M/PCIe/SSE2
- Driver/LLVM version: 4.6.0 NVIDIA 415.13
- Kernel version: 4.18
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 3.16-4 Beta

[sys.txt](https://github.com/ValveSoftware/Proton/files/2595953/sys.txt)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Blackscreen

## Reproduction

![schermata da 2018-11-19 16-23-17](https://user-images.githubusercontent.com/28324952/48717284-5d646c00-ec19-11e8-89c6-ad7f95f830cf.png)

**Comment by kisak-valve** [comment]
Hello @AgostinoA, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/731#issuecomment-439952334.
