### ISSUE TITLE
Zuma's revenge (3620)

### ISSUE THREAD

**Issue by Gepp35** [ValveSoftware/Proton#2004]
# Compatibility Report
- Name of the game with compatibility issues: Zuma's revenge
- Steam AppID of the game: 3620

## System Information
- GPU: AMD RAVEN (ryzen 7 pro 2700U/ radeon vega)
- Driver/LLVM version: mesa 19.0.0-devel (2018-11-15 bionic oibaf), DRM 3.27.0, LLVM 7.0.1
- Kernel version: kernel 4.19.0-041900-generic (ubuntu LT 18.04 uptodate)
- Link to full system information report as Gist: OpenGL 4.5
- Proton version: proton 3.16-4 beta

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. --> grouped with multiple popcap games https://github.com/ValveSoftware/Proton/issues/340 
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
just after launching the game, a window pops up "title: fatal error. Invalid command line parameter: -changedir "ok" button"

## Reproduction

[steam-3620.log](https://github.com/ValveSoftware/Proton/files/2597336/steam-3620.log)

**Comment by kisak-valve** [comment]
Hello @Gepp35, as you noted, this issue is already being tracked at #340. Closing in favor of the existing issue report.
