### ISSUE TITLE
Grand Theft Auto V (271590)

### ISSUE THREAD

**Issue by Reonu** [ValveSoftware/Proton#2006]
# Whitelist Request
- Grand Theft Auto V
- Steam AppID of the game: 271590

## System Information
- GPU: GTX 1070
- Driver/LLVM version: Nvidia 410.73
- Kernel version: 4.18
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Leon422/15f1906b04e48ab3d03e6b946e008979
- Proton version: 3.16-4 beta

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [X] that no workarounds other than the mentioned ones are necessary.

## Issues
- [X] I haven't experienced any issues.
- [X] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

The Proton beta fixes the launcher loop issue. Now everything works, even the online mode. Once this Proton version gets out of beta I don't see why not to whitelist this game. 

The game launched in DX10 mode, which worked fine, and I changed it to DX11 mode in the in-game options, which also worked fine.

**Comment by kisak-valve** [comment]
Hello @Leon422, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-440334647.
