### ISSUE TITLE
Adventure Communist (462930) fonts not rendering in Proton 3.16-4

### ISSUE THREAD

**Issue by WillHaRSI** [ValveSoftware/Proton#2012]
# Compatibility Report
- Adventure Communist
- Steam AppID of the game: 462930

## System Information
- CPU Brand: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
- Operating System Version: "Manjaro Linux" (64 bit)
- Kernel Version:  4.19.2-1-MANJARO
- Video Card: Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile 
- Sound card: Audio device: Realtek ALC269VC
- Memory:  RAM:  31740 Mb
- UI Language:  English
- LANG:  en_US.utf8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

![screenshot_2018-11-22_09-15-56](https://user-images.githubusercontent.com/43677545/48908053-41d6ac80-ee37-11e8-88e2-73e3b1e78073.png)

**Comment by kisak-valve** [comment]
Hello @WillHaRSI, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

Separately, at a glance this looks like a side effect of mesa/Intel/Ivybridge's incomplete vulkan support. Please put `PROTON_USE_WINED3D=1 %command%` in the game's launch options and check if it improve's the game's behavior.

**Comment by WillHaRSI** [comment]
"PROTON_USE_WINED3D=1 %command%" fixed the problem. Can confirm works fine on Radeon GPUs. This ticket can be closed. Thanks.
