### ISSUE TITLE
[Compatibility Report] Novus Inceptio (App-ID 386590)

### ISSUE THREAD

**Issue by fer-rum** [ValveSoftware/Proton#2015]
# Compatibility Report
- Name of the game with compatibility issues: Novus Inceptio
- Steam AppID of the game: 386590

## System Information
- GPU:  AMD Radeon (TM) RX 480
- Driver version: 4.5 (Compatibility Profile) Mesa 19.0.0-devel (git-41c8f99 2018-11-12 cosmic-oibaf-ppa)
- LLVM version: 7.0.1
- Kernel version: 4.18.0-11-generic
- Link to full system information report as [Gist](https://gist.github.com/fer-rum/5e80ed383efbdac5a61774889fd678d9)
- Proton version: 3.7.8

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-386590.log.txt](https://github.com/ValveSoftware/Proton/files/2609491/steam-386590.log.txt)

## Symptoms 
Animated models are invisible. 
Static models render fine though.

## Reproduction
1. Start the game.
2. Use _F1_ to switch between first and third person view. Contrary to the Windows version you will not see the player model.
Walking around in the game world, one also can often find animals: their health bars are visible, their models are not.

**Edit:** I gave the wrong key for switching first/third person.

**Comment by kisak-valve** [comment]
Hello @fer-rum, please retest with Proton 3.16-4.

**Comment by fer-rum** [comment]
Proton 3.16-4 solves the problem. Awesome!
