### ISSUE TITLE
Silent Hunter Wolves of the Pacific (15200)

### ISSUE THREAD

**Issue by supagu** [ValveSoftware/Proton#2016]
# Compatibility Report
- Name of the game with compatibility issues: Silent Hunter Wolves of the Pacific
- Steam AppID of the game: 15200

https://store.steampowered.com/app/15200/Silent_Hunter_Wolves_of_the_Pacific/
https://store.steampowered.com/app/15240/Silent_Hunter_Wolves_of_the_Pacific_UBoat_Missions/

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 18.2/7.0.0
- Kernel version: 4.18
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 
Launching game crashes on launch

## Reproduction
Launching game causes crash strait away

**Comment by supagu** [comment]
[steam-15200.log](https://github.com/ValveSoftware/Proton/files/2609612/steam-15200.log) Attached log file

**Comment by kisak-valve** [comment]
Hello @supagu, it looks like you've skipped mentioning what issue(s) you are seeing with these games, which makes this an invalid issue report. Please describe what the game is doing on your system.

**Comment by supagu** [comment]
Thanks, fixed

**Comment by zzhiyi** [comment]
Unhandled exception: unimplemented function FileManager.dll.?GetPrivateProfileStringPtr@CIniFile@@UAEPBDPBD00@Z called in 32-bit code (0x7bc541f1).

FileManager.dll is a native dll. I wonder why wine failed to locate the function.

**Comment by zzhiyi** [comment]
Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)  (0x3e92)
    Version: 18.2.2

Works rather well here. Could you try proton 3.16 and maybe reinstall the game?

**Comment by supagu** [comment]
This is working now! I used Proton 3.16-6 Beta
