### ISSUE TITLE
Rumble / Force Feedback: What is the correct setting?

### ISSUE THREAD

**Issue by hzulla** [ValveSoftware/Proton#2020]
My very cheap `0079:0006 DragonRise Inc. PC TWIN SHOCK` gamepad comes with force feedback effect vibration motors. I can confirm that these work under Linux with [`fftest`](http://manpages.ubuntu.com/manpages/cosmic/man1/fftest.1.html). What is the proper setting for Steam with Proton to enjoy rumble effects?

**Comment by hzulla** [comment]
(e.g. there are no rumble effects with this gamepad in "Duck Tales: Remastered", although the game options offer this as a controller setting.)

**Comment by aeikum** [comment]
Try disabling Gamepad Configuration Support in the Steam client options. Let us know if that doesn't work.

**Comment by hzulla** [comment]
Ok, disabling "generic gamepad configuration support" makes the rumble effects work.

(Great! That means that I can now have rumble effects with gamepads that are supported in Linux, even if the same device has no rumble device driver in Linux... Yay!)

![steam-works](https://user-images.githubusercontent.com/1705654/49091331-dee27c80-f25f-11e8-9eaa-7a5591fb3059.png)

**Comment by aeikum** [comment]
Cool, thanks for confirming. This is due to a Steam client limitation, see https://github.com/ValveSoftware/steam-for-linux/issues/4338 . I've updated the Proton FAQ on the Wiki.

**Comment by hzulla** [comment]
This is really cool, as I own a gamepad that rumbles on Linux, but does not on Windows. :-D

**Comment by hzulla** [comment]
@aeikum It would be *really* cool to have this work out of the box without changing any setting.

**Comment by aeikum** [comment]
Agreed, but it's a Steam client issue, and I don't work for Valve. Head to their bug tracker :)
