### ISSUE TITLE
Danmaku Unlimited 3

### ISSUE THREAD

**Issue by Racercowboy** [ValveSoftware/Proton#2024]
# Compatibility Report
- Name of the game with compatibility issues: Danmaku Unlimited 3
- Steam AppID of the game: 450950

## System Information
- GPU: RX 480
- Driver/LLVM version: Mesa 19.0.0/7.0.1
- Kernel version: 4.19.3-041903-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Racercowboy/777ec544f4de427987ee224f416950a8
- Proton version: 3.16-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-450950.log](https://github.com/ValveSoftware/Proton/files/2611854/steam-450950.log)

## Symptoms
When the game starts, the launcher appears where you can change various settings. After launching the game from the launcher a window will briefly appear after which a warning popup comes up saying that my card does not support Opengl 2.0, and that updating the graphics driver may solve this issue. After this, the game closes. Changing the settings in the launcher seems to have no effect.

## Reproduction
1. Start the game from steam
2. Launcher appears, then start the game from launcher.

**Comment by Shugyousha** [comment]
Unfortunately this issue still persists 3 years later (I have a RX 480 as well).

Here is my steam Proton log for the game
[steam-450950.log](https://github.com/ValveSoftware/Proton/files/7765085/steam-450950.log)

Let me know if more debugging data is needed!

**Comment by Shugyousha** [comment]
I have looked into a little bit. Sadly I am not too familiar with Wine but maybe what I found could be helpful for someone else.

First I have gotten some logs with more active Wine debug channels (Note that these are up to 190MB when decompressed).

+relay,+seh+tid: https://sillymon.ch/data/steam-450950.relay-seh-tip.log.zstd
+relay,+seh+wgl: https://sillymon.ch/data/steam-450950.relay-seh-wgl.log.zstd

Interestingly, while I did get the message box about OpenGL compatibility in the +relay,+seh+tid case I didn't in the +relay,+seh+wgl one (the +wgl log seems to have hit an exception of some sort).

The reason I added the +wgl to get the logs was that the original proton log contains a line saying `4537.319:010c:0110:fixme:wgl:fs_hack_get_attachments_config Unsupported depth buffer size 16.`. This fixme only seems to be in the Wine fork that Valve uses in proton. I wonder if this missing support could be what causes the OpenGL check to fail, causing the message box to be shown. This is mostly speculation on my part though.

I have run the game with plain Wine and the same message box was shown. This indicates that it's not a Proton-specific issue at least.

**Comment by waspennator** [comment]
Testing on a 512 gb steam deck with Experimental seems to result in the same opengl 2.0 support error. I also checked on protondb and all the reports there that got it working were using nvidia gpus, while the one report that says it didn't work was using an AMD gpu, so I think it might be a vendor specific issue.

[steam-450950.log](https://github.com/ValveSoftware/Proton/files/10223791/steam-450950.log)

Interesting thing about it, there is a beta branch for the game that's public, if you opt into it and then try the game, the error doesn't pop up on deck and it's able to get in game. Have a feeling it fixes it for amd gpus.

**Comment by waspennator** [comment]
Ran a log with the beta up to the title screen incase anything seems noticably different enough to figure out what's going on. 

[steam-450950 beta.log](https://github.com/ValveSoftware/Proton/files/10224324/steam-450950.beta.log)

**Comment by Racercowboy** [comment]
I just tried the game again in the beta branch and it worked. While I don't have the same computer anymore, it still has an AMD gpu in it, and if I run the non beta version of the game the same error pops up still. That beta branch wasn't there before when I first got the game, perhaps they "fixed" it silently or something?

**Comment by waspennator** [comment]
> I just tried the game again in the beta branch and it worked. While I don't have the same computer anymore, it still has an AMD gpu in it, and if I run the non beta version of the game the same error pops up still. That beta branch wasn't there before when I first got the game, perhaps they "fixed" it silently or something?

I dunno when it popped up exactly, I just noticed someone made a thread on the community hub about it around June. Also believe the dev was made aware of the issues back in may as well and said they were gonna look into getting a dev unit steam deck to troubleshoot.

**Comment by waspennator** [comment]
https://steamcommunity.com/games/450950/announcements/detail/3644013628344211900

Beta branch has now been officially pushed into stable and the game now starts up without issue on deck. If it works on your end I think this issue can finally be closed now.

~~Update: I'm not sure if it's proton or the game, but I can only seem to get the game to launch if full screen is disabled, which it is off by default when I tried it, but i'm still posting for recordings sake.~~

~~[steam-450950.log](https://github.com/ValveSoftware/Proton/files/10963514/steam-450950.log)~~

**Comment by Racercowboy** [comment]
Just tried it, the game launches for me regardless of settings now in the stable branch. Tried it with proton experimental and 7.0-6, not with the others though.

**Comment by waspennator** [comment]
Actually disregard my last update, tried it out on windows and for whatever reason, the game seems to have a fit trying to play full screen on certain resolutions. Not a proton problem it seems and the game seems to boot in full screen if you set it to 1280 X 720.

I think this issue should be safe to close now if it works.

**Comment by Shugyousha** [comment]
I can confirm that this game now works on the Steam Deck without using the beta branch (I have tested this with ProtonGE, Proton Experimental and Proton version 6.3-8).

It also works on my AMD-based desktop machine (AMD RX 6700XT using Proton Experimental).

I also think that this issue can now be closed.
