### ISSUE TITLE
Fallout: New Vegas (Radio Music Doesn't Play

### ISSUE THREAD

**Issue by osilkin98** [ValveSoftware/Proton#2028]
# Compatibility Report
- Name of the game with compatibility issues: Fallout: New Vegas
- Steam AppID of the game: 22380

## System Information
- GPU: GTX 960
- Driver/LLVM version: 396.54
- Kernel version: 4.15.0-39-generic
- Link to full system information report as [Gist](https://gist.github.com/osilkin98/1f3b65bf8ccd65d12405e17cf81ecc29):
- Proton version: 3.7-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-22380.log.gz](https://github.com/ValveSoftware/Proton/files/2612580/steam-22380.log.gz)

## Symptoms 
The game runs pretty smoothly for the most port, the only issue is that songs won't play if you try listening to the radio. For instance, you can listen to Radio New Vegas, and Mr. New Vegas' voice will come on every so often, but the songs won't. I'm not sure if it's a codec issue or what, it's just kind of unnerving.

## Reproduction

Just run the game with the settings above and it should replicate the error

**Comment by kisak-valve** [comment]
Hello @osilkin98, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/356#issuecomment-441398911.
