### ISSUE TITLE
Beat Saber: Black screen and XID errors (620980)

### ISSUE THREAD

**Issue by ali1234** [ValveSoftware/Proton#2030]
# Compatibility Report
- Name of the game with compatibility issues: Beat Saber
- Steam AppID of the game: 620980

## System Information
- GPU: GTX 780
- Driver/LLVM version: nvidia 396.54.09
- Kernel version: 4.15
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ali1234/1a2a47c23e335f81265009a39d0df152
- Proton version: 3.16-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

When running the game, first this pops up:

![screenshot_2018-11-25_16-35-00](https://user-images.githubusercontent.com/651970/48981645-3ce05a00-f0d0-11e8-8871-aa28cedfbbad.png)

After pressing enter the screen goes black, and nothing more happens.

Then on dmesg I see this
```
[1133120.640829] NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: Shader Program Header 9 Error
[1133120.640833] NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x405840=0x82000200
[1133120.640843] NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ChID 007a, Class 0000a197, Offset 00001a2c, Data 00000000
[1133285.439260] vrcompositor[16288]: segfault at 0 ip 00007fb2a7bac5d7 sp 00007ffe9567eff0 error 4 in libnvidia-glcore.so.396.54.09[7fb2a6ace000+10e9000]
```
Log: [steam-620980.log](https://github.com/ValveSoftware/Proton/files/2613242/steam-620980.log)

## Reproduction

Just run it.

**Comment by ali1234** [comment]
PS I forgot to mention that lots of other VR games work fine.

**Comment by Waddlen** [comment]
Do you have those 32-bit libraries installed?

For example, `sudo apt install libxtst6:i386` and `sudo apt install libxrandr2:i386`

You can find their package names by using the [Ubuntu package search](https://packages.ubuntu.com/search?suite=bionic&arch=i386&searchon=contents&keywords=libXtst.so.6)

Note that because you are using a 64-bit OS, you will need to append `:i386` to the end of the package name, to indicate you wish to install the 32-bit version.

**Comment by ali1234** [comment]
libva.so.1 and libva-x11.so.1 are not available.

**Comment by Waddlen** [comment]
Try `sudo apt install libva2:i386 libva-x11-2:i386`

**Comment by ali1234** [comment]
After installing 32 bit libraries that error message is no longer displayed. However there is no change in the behavior of the game. It still displays nothing but a black screen and causes XID errors on dmesg.

**Comment by Waddlen** [comment]
I believe the dmesg points to an error within the Nvidia driver. How did you install your drivers? Did you use the [official Ubuntu ppa](https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa) (or [here](https://launchpad.net/~graphics-drivers/+archive/ubuntu/dev) for 396.54.09)? 
Perhaps reinstalling the Nvidia drivers and rebooting will clear up your issues, I don't think libva.so.1 and libva-x11.so.1 would have been missing if the Nvidia driver had been installed correctly.

**Comment by ali1234** [comment]
libva.so.1 and libva-x11.so.1 are missing because they are not available in Ubuntu.

libva2:i386 and libva-x11-2:i386 installs libva.so.2 and libva-x11.so.2 respectively. These are different ABI versions and are not compatible.

It turns out the 32 bit error only appears after running beat saber one time. It still displays the error, but now it only lists libva as missing, because I installed all the others. And what's more, after running beat saber, every game on steam displays this error. Despite this they all work fine.

This isn't an installation error. I installed from the Xorg team PPA. Reinstalling won't make any difference because apt guarantees that the same files will be installed in the same place. And I have rebooted many times - I have to reboot about 50% of the time when I run beat saber because the whole computer freezes on a black screen. Sometimes I can switch to a terminal and kill it. Other times all the monitors turn off and the computer is completely unresponsive.

This is only a problem with beat saber. It does not happen with any of the other 200+ games in my library, many of which are VR, nor when I run intensive CUDA applications such as Blender.

**Comment by Waddlen** [comment]
Okay, I'm not sure what the issue is then. Beat Saber works on my Ubuntu 18.04 / Ryzen 1700 / GTX 1080 396.54.09 system. Good luck finding the solution.

**Comment by ali1234** [comment]
btw in addition to the versions in the initial report, I have tested beat saber with several versions of proton since the initial release as well as multiple nvidia driver versions - the default for Ubuntu 18.04, 396.54, and 396.54.09 and it has never worked with any of them. Always the exact same result.

**Comment by yaomtc** [comment]
This is may be unrelated, but I don't want to create a new issue for this game.

I couldn't get Beat Saber to work without esync disabled (PROTON_NO_ESYNC). This is on Solus, but I've already increased the limits [as explained here.](https://github.com/lutris/lutris/wiki/How-to:-Esync)

**Comment by JulianGro** [comment]
No idea if this is related the same bug, but me and another user had problems with XID errors and nvidia fixed them: https://devtalk.nvidia.com/default/topic/1051300/linux/inconsistent-but-frequent-freeze-caused-by-steamvr/3

**Comment by kisak-valve** [comment]
Hello @ali1234, are you still experiencing this issue on an up to date system? This reads like it was a video driver issue.

**Comment by ali1234** [comment]
To be honest I haven't tried it since my last comment and I don't even have the same GPU any more. I just did a quick test (without headset plugged in) and it seemed to load up okay. This can be closed.
