### ISSUE TITLE
Lego Star Wars - The Complete Saga

### ISSUE THREAD

**Issue by Reonu** [ValveSoftware/Proton#2033]
# Whitelist Request
- Name of the game to be whitelisted: Lego Star Wars - The Complete Saga
- Steam AppID of the game: 32440

## System Information
- GPU: GTX 1070
- Driver/LLVM version: Nvidia 410.73
- Kernel version: 4.18
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Leon422/15f1906b04e48ab3d03e6b946e008979
- Proton version: 3.16-4 beta

## I confirm:
- [ ] that pressing the `Play` button in the Steam client is sufficient.
- [X] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game. (Disabling esync to fix an audio loop bug)
- [X] that no workarounds other than the mentioned ones are necessary.

## Issues
- [X] I haven't experienced any issues.
- [X] There are no issues left open for this game.
- [X] Although I consider the gaming experience equal to Windows there are
      remaining issues: 
The audio loops incorrectly unless you disable esync. But once you do, it's perfect.

**Note:** I also tested the game on a laptop with a Nvidia 820M and it ran at a locked 60 FPS at 1600x900. Therefore, we can conclude that this game can run on a toaster, even with esync disabled.

**Comment by kisak-valve** [comment]
Hello @Leon422, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/524#issuecomment-441484361.
