### ISSUE TITLE
Error when start [star wars: battlefront 2]

### ISSUE THREAD

**Issue by engFelipeMonteiro** [ValveSoftware/Proton#2036]
I try to start but it give a error.

steam.desktop[2897]: Traceback (most recent call last):
steam.desktop[2897]:   File "/media/felipe/SteamData/SteamLibrary/steamapps/common/Proton 3.16/proton", line 249, in <module>
steam.desktop[2897]:     upgrade_pfx(f.readline().strip())
steam.desktop[2897]:   File "/media/felipe/SteamData/SteamLibrary/steamapps/common/Proton 3.16/proton", line 63, in upgrade_pfx
steam.desktop[2897]:     old_proton_ver, old_prefix_ver = old_ver.split('-')
steam.desktop[2897]: ValueError: not enough values to unpack (expected 2, got 1)

the full log is bellow:

steam.desktop[2897]: No cached sticky mapping in ActivateActionSet.GameAction [AppID 6060, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
steam.desktop[2897]: Proton: Upgrading prefix from  to 3.16-1 (/media/felipe/SteamData/SteamLibrary/steamapps/compatdata/6060)
steam.desktop[2897]: Traceback (most recent call last):
steam.desktop[2897]:   File "/media/felipe/SteamData/SteamLibrary/steamapps/common/Proton 3.16/proton", line 249, in <module>
steam.desktop[2897]:     upgrade_pfx(f.readline().strip())
steam.desktop[2897]:   File "/media/felipe/SteamData/SteamLibrary/steamapps/common/Proton 3.16/proton", line 63, in upgrade_pfx
steam.desktop[2897]:     old_proton_ver, old_prefix_ver = old_ver.split('-')
steam.desktop[2897]: ValueError: not enough values to unpack (expected 2, got 1)
steam.desktop[2897]: installscript_posix.cpp (416) : Assertion Failed: Standalone evaluator returned error code for app 6060
steam.desktop[2897]: GameAction [AppID 6060, ActionID 3] : LaunchApp changed task to SynchronizingCloud with ""
steam.desktop[2897]: Proton: Upgrading prefix from  to 3.16-1 (/media/felipe/SteamData/SteamLibrary/steamapps/compatdata/6060)
steam.desktop[2897]: Traceback (most recent call last):
steam.desktop[2897]:   File "/media/felipe/SteamData/SteamLibrary/steamapps/common/Proton 3.16/proton", line 249, in <module>
steam.desktop[2897]:     upgrade_pfx(f.readline().strip())
steam.desktop[2897]:   File "/media/felipe/SteamData/SteamLibrary/steamapps/common/Proton 3.16/proton", line 63, in upgrade_pfx
steam.desktop[2897]:     old_proton_ver, old_prefix_ver = old_ver.split('-')
steam.desktop[2897]: ValueError: not enough values to unpack (expected 2, got 1)
steam.desktop[2897]: GameAction [AppID 6060, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
steam.desktop[2897]: GameAction [AppID 6060, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
steam.desktop[2897]: GameAction [AppID 6060, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
steam.desktop[2897]: GameAction [AppID 6060, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
steam.desktop[2897]: Game update: AppID 6060 "", ProcID 3978, IP 0.0.0.0:0
steam.desktop[2897]: >>> Adding process 3978 for game ID 6060
steam.desktop[2897]: GameAction [AppID 6060, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
steam.desktop[2897]: ERROR: ld.so: object '/home/felipe/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
steam.desktop[2897]: ERROR: ld.so: object '/home/felipe/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
steam.desktop[2897]: GameAction [AppID 6060, ActionID 3] : LaunchApp changed task to Completed with ""
steam.desktop[2897]: ERROR: ld.so: object '/home/felipe/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
steam.desktop[2897]: >>> Adding process 3979 for game ID 6060
steam.desktop[2897]: >>> Adding process 3980 for game ID 6060
steam.desktop[2897]: Proton: Upgrading prefix from  to 3.16-1 (/media/felipe/SteamData/SteamLibrary/steamapps/compatdata/6060)
steam.desktop[2897]: Traceback (most recent call last):
steam.desktop[2897]:   File "/media/felipe/SteamData/SteamLibrary/steamapps/common/Proton 3.16/proton", line 249, in <module>
steam.desktop[2897]:     upgrade_pfx(f.readline().strip())
steam.desktop[2897]:   File "/media/felipe/SteamData/SteamLibrary/steamapps/common/Proton 3.16/proton", line 63, in upgrade_pfx
steam.desktop[2897]:     old_proton_ver, old_prefix_ver = old_ver.split('-')
steam.desktop[2897]: ValueError: not enough values to unpack (expected 2, got 1)
steam.desktop[2897]: Game removed: AppID 6060 "", ProcID 3978

**Comment by aeikum** [comment]
Interesting, the version file in the prefix was created, but empty. We should handle this in the Proton script, but do you know how this could have happened?

**Comment by aeikum** [comment]
The proton script should now handle this corrupted prefix. I'd still love to know how the version file ended up wrong...

**Comment by AQDuck97** [comment]
Reviving this issue as I'm having problem with the game too.

Arch Linux 6.7.9-Zen kernel
Plasma 6 Wayland

--------------------------------------------------------------------------------------------------------
Proton-GE 8.14, Proton 9, Proton Experimental, Proton 8 and Proton 7 tested.
Proton 7 produced a frozen black screen while the others were just a very quick black screen that lasted about half a second.

--------------------------------------------------------------------------------------------------------

[System and runtime info gist](https://gist.github.com/AquaDuck97/d93d2ee225c20cd630aeb80336682537)
[steam-6060.log](https://github.com/ValveSoftware/Proton/files/14608710/steam-6060.log)

**Comment by kisak-valve** [comment]
Hello @AquaDuck97, your issue is unrelated to this specific issue. Instead, you've configured your system to use AMDVLK with 32 bit Vulkan applications, but the version of AMDVLK  you're using has dropped support for your hardware generation (https://gist.github.com/AquaDuck97/d93d2ee225c20cd630aeb80336682537#file-system-and-runtime-info-L158-L172).

Add the `lib32-vulkan-radeon` system package, remove the `lib32-amdvlk` system package, then retest.

**Comment by kisak-valve** [comment]
It looks like the investigation into this issue concluded in 2018. Closing as resolved.
