### ISSUE TITLE
All games Kubuntu KDE taskbar and time issue

### ISSUE THREAD

**Issue by EngiBob** [ValveSoftware/Proton#2043]
# Compatibility Report
- I have this problem with every game run in full screen or windowed mode

## System Information
- https://gist.github.com/EngiBob/b7cfe7ab8a0718be3bd2fcbc92efe5f1
- Proton version: 3.16-4 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

KDE appears to get a new taskbar created with a different time and different taskbar buttons that don't include all running applications.  When the game quits in windowed mode or successfully moves to the background the different taskbar flashes and disappears leaving the correct taskbar with the correct app list and correct time.  My time as I launch Rust right now goes from 1am to 9:28am.

I'm not sure if it is related but if I alt-tab out of full screen Rust I start getting major high speed artifacts across multiple monitors and eventually a KDE process spinning at 100%

## Reproduction

I was just testing with State of Decay since it loads so fast and successfully goes to the background very quickly allowing you to watch the taskbar and Rust in windowed mode.  Reproduction should be possible with just a default Kubuntu install and any game.

**Comment by kisak-valve** [comment]
Hello @EngiBob, this sounds abnormal, especially with a windowed game. Can you grab some screenshots and drag and drop them into a comment? Is kwin's compositor turned on or off? This may be a KDE and/or nvidia issue.

**Comment by OvermindDL1** [comment]
I've never seen this with games either and I have a computer both with an older and with 'latest' KDE versions, *however* I have seen that in the 'latest' KDE versions (but not prior) that the plasma interface sometimes gets 'duplicated' like OP described when under extreme load (I'm uncertain if it does it without compositor, but it definitely does it with).  I haven't figured out a way to reliably reproduce it and I haven't checked if it's been reported, but I'm pretty sure this is a recent KDE issue.  If a bug report is found on the KDE bug tracker then a link back here would be fantastic for any others to follow-up on that have a similar issue.  The 'latest' system it runs in here is a VM built on an Intel GPU as well, so it is not strictly an NVidia issue.  The computer it doesn't happen on, which runs a slightly older (few months) version of KDE is running an AMD GPU however.

**Comment by byte1024** [comment]
Since the time changes and applications go missing, I feel its probably something KDE is doing in this situation. Have no idea why though, but it sounds too much like a fake static image of it, maybe for performance reasons or something.

I don't see Wine/Proton manipulating the taskbar or something like that.

**Comment by ghost** [comment]
Since the time changes and applications go missing, I too feel its probably something KDE is doing in this situation. Have no idea why though, but it sounds too much like a fake static image, maybe for performance reasons or something.

I don't see Wine/Proton manipulating the taskbar or something like that. And since it switches back when the game is no longer focused, I feel it makes sense that its just a fake image, but why you have it and not someone else that is the mystery.

If it was Wine/Proton then you probably couldn't click out of a windowed game window and cause it to lose focus but would have to ALT+TAB, etc.

**Comment by OvermindDL1** [comment]
> Since the time changes and applications go missing, I too feel its probably something KDE is doing in this situation. Have no idea why though, but it sounds too much like a fake static image, maybe for performance reasons or something.

No, rather it really is two full instances of plasma and related application helpers running but 'overlapping' on the same display.  It's really weird but I have tested as much as I can really stand before I have to kill them all and relogin...  ^.^;

They both get their full inputs and outputs, like a single click on the screen will send the click to both of them and they will each respond accordingly, it's very weird...

**Comment by EngiBob** [comment]
Before:

![before](https://user-images.githubusercontent.com/4041407/49297869-ea18f080-f489-11e8-96f7-3fe7571c4d8c.png)

Immediately starting any game in windowed mode or not.  I did not close any programs the new taskbar is missing things from before.  Also when I try to use my mouse on the taskbar I think it also hits the old taskbar and the responses are not what is expected.  I have to wait for a mouseover popup to see what the cursor is actually on:

![after](https://user-images.githubusercontent.com/4041407/49297906-f8670c80-f489-11e8-953a-d4ae4f6fc733.png)

No irregularities in kwin_x11 resource usage.  I'm using 3 monitors and forced the primary to a different one.  It always shows 9:28am when the game is running.

**Comment by EngiBob** [comment]
I just confirmed it is also happening with native Linux games so it is unlikely Steamplay.  I did just switch to KDE a couple weeks ago right after I signed up for the beta.  This never happened in GNOME.

**Comment by kisak-valve** [comment]
Thanks for digging a bit further @EngiBob. At this point I'm reasonably sure this issue needs to be investigated on KDE's side (https://bugs.kde.org/). If they find a hint to what's going on here, please post a comment here and I'll transfer this issue over to the steam-for-linux issue tracker.

Closing pending an actionable hint that this is a Steam or Proton issue.

**Comment by greydmiyu** [comment]
I believe this is because Compositing is turned off on most games.  When running a game hit ALT-SHIFT-F12 to toggle compositing.  This will turn it back on and the bars should be back to their updated state.

**Comment by EngiBob** [comment]
That fixes it for me.  The compositor default settings allow applications
to disable it but running games doesn't seem to do it.  It would be nice if
it was automatic but that workaround is good.
