### ISSUE TITLE
GTA V Crashes After Intro: Proton 3.7-8

### ISSUE THREAD

**Issue by TonsOfBricks** [ValveSoftware/Proton#2044]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @TonsOfBricks, we're using one issue report per unofficially supported game title. Closing in favor of #37.

(Also, only filling out the title of an issue report is not enough information to evaluate your issue)
