### ISSUE TITLE
X4: Foundations (392160)

### ISSUE THREAD

**Issue by zezic** [ValveSoftware/Proton#2045]
# Compatibility Report
- Name of the game with compatibility issues: X4: Foundations
- Steam AppID of the game: 392160

## System Information
- GPU: GTX 1060 (6GB)
- Driver/LLVM version: nvidia 410.73
- Kernel version: 4.15
- Link to full system information report: https://gist.github.com/zezic/6dad81fe8633a0edb7f9fed58db3c5f0
- Proton version: 3.16-4 Beta

## I confirm:
- [v] that I haven't found an existing compatibility report for this game.
- [v] that I have checked whether there are updates for my system available.

[steam-392160.log](https://github.com/ValveSoftware/Proton/files/2634539/steam-392160.log)

## Symptoms 
Game launches, plays short intro video and then hangs with black screen with custom cursor activated and menu music playing. While game launches the crash reporter is appearing and crashing when trying to collect system info.

## Reproduction

1. Install game and run it with Steam Play.

**Comment by chrzyki** [comment]
I think that this has got something to do with `utf8_64.dll` in `X4 Foundations/ui/core/lualibs`. Wine reports an invalid ELF header for the file:

```
.local/share/Steam/steamapps/common/X4 Foundations/ui/core/lualibs/utf8_64.dll: invalid ELF header
```

later on resulting in an exception:

```
263.247:0022:004f:trace:module:MODULE_InitDLL (0x3b570000,PROCESS_ATTACH,(nil)) - RETURN 1
1263.247:0022:004f:trace:module:process_attach (L"utf8_64.dll",(nil)) - END
1267.355:0022:004f:trace:seh:NtRaiseException code=c0000005 flags=0 addr=0xf7673f ip=f7673f tid=004f
1267.355:0022:004f:trace:seh:NtRaiseException  info[0]=0000000000000001
1267.355:0022:004f:trace:seh:NtRaiseException  info[1]=00000000fe03c018
```

Symlinking the file to the (possibly?) equivalent `utf8.so` (or replacing it with an empty file of the same name?) from X:Rebirth removes the crash entirely and seemingly successfully enters the game engine. However, the main menu is completely borked and doesn't react to input. The game also reports being unable to initialize the UI, probably due to the problematic `utf8_64.dll.`

/edit: On the other hand, the invalid ELF headers might not be a problem at all, since these are reported for multiple DLLs (`utf8_64.dll` just caught my attention because replacing it makes the game kind of work).

**Comment by Warringer** [comment]
I am going to add my own log into the mix. And I have found 12 'invalid ELF' entries in the log file.

[steam-392160.log](https://github.com/ValveSoftware/Proton/files/2635118/steam-392160.log)

**Comment by Victoralm** [comment]
I'm also adding my log:
[steam-392160.log](https://github.com/ValveSoftware/Proton/files/2635333/steam-392160.log)

**Comment by Ichinix** [comment]
Here is my log, hoping we can play this game soon.

[steam-392160.log](https://github.com/ValveSoftware/Proton/files/2636527/steam-392160.log)

**Comment by baracoder** [comment]
The developers might add native support in a later release https://twitter.com/EGOSOFT/status/1017779469216514049

**Comment by foxxtrot** [comment]
With some of the recent patches, the crash seems like we might be closer to actually running, not sure. Attaching a log.

And yeah, baracoder, Egosoft will be doing a Native Port, but it'd still be nice if this was playable now.

[steam-392160.log](https://github.com/ValveSoftware/Proton/files/2651838/steam-392160.log)

**Comment by Ichinix** [comment]
It seems from Foxxtrot hes log file that the execution location or something is not correct, I've seen this in the past with Native Ports of X3 as well. Unfortunately im not skilled enough to further investigate and im usually just messing around :P but maybe someone with some actual skill gets an idea with this information:
Line 15337 File I/O: Could not find file '.\ui\addons\ego_eventmonitor\ui.xml'
Line 15340 XLib::XMLInputOpenCallback(): Failed to open the file: ui/addons/ego_eventmonitor/ui.xml
Line 15343 error message is to long, i will not include this in the post.

I will check later today on my box to see if i have similar messages now with the latest patches.

**Comment by radcapricorn** [comment]
@Ichinix that particular message is due to the file literally not being there. There is no `ui\addons\ego_eventmonitor\ui.xml` file listed in the game files.

**Comment by Ichinix** [comment]
@radcapricorn aaaahh yeah well thats a problem ))) i was in the office so i could not check.
Here is the latest log file with the last patches they have released, there is indeed a change in behavior.
[steam-392160.log](https://github.com/ValveSoftware/Proton/files/2653261/steam-392160.log)

**Comment by zezic** [comment]
@Ichinix the `ui/addons/ego_eventmonitor/ui.xml` is enlisted in `08_sig.cat` so it's probably packed somewhere in `08.dat` or `08_sig.dat`. I could be wrong but the same way of packaging was used in X3 series.

**Comment by sobfiggis** [comment]
Just providing some information. May or may not be helpful.

I've unpacked the files and did a search for what you are looking for here.
https://i.imgur.com/1qK4tPe.png

**Comment by davvvve1** [comment]
With latest wine i can get it to run BUT no menu ui . So i cant start the game . Just after the splashscreen when loading screen shows , press alt+enter and the game start .

**Comment by kraetzin** [comment]
For anybody still interested, the Linux version has now been released on Steam so Proton is no longer needed.

**Comment by JotaVeUltra** [comment]
Can this issue be closed now?

**Comment by qsniyg** [comment]
@JotaVeUltra I don't think so, as (unless I'm wrong) the issue still isn't resolved in proton.

**Comment by zezic** [comment]
I think, it's better to close this as a native Linux version is available.
