### ISSUE TITLE
All proton games just won't launch

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#2046]
When I launch the game I am trying to play instead of opening nothing happens. i tried diffrent versions of proton and still no luck. before this happened i was having proton audio problems (audio crackling and gliching) and before that proton worked as intended. i did not modify or delete any steam play files. help.
i have lubuntu 18.10
i have all my games on a separate high speed removable hdd and play from there.
All other games work fine but the ones that use proton don't, even the officially supported ones...

**Comment by aeikum** [comment]
Try running Steam from a Terminal and see if you get any suspicious output when launching a game.

**Comment by mercuriete** [comment]
If you are using an external drive probably you are using Ntfs or another partition type.
Make sure you are the owner of the files.

If thats the case... Mount the filesystem with uid=1000,gid=1000 or something similar.

Try to not use something different to ext4.

Check for another bug similar to this.

Edit: another thing you can try is not use external drive and use the folder that Steam sets by default. If this works for you, then you will be sure that is a permission problem.

**Comment by flukejones** [comment]
> Try running Steam from a Terminal and see if you get any suspicious output when launching a game.

Do this. It's likely that you don't have Python installed.

**Comment by Tbird761** [comment]
Truth be told I have the same issue on Debian Testing.  I've tried all manner of things including newer versions of Mesa and every version of Proton that Valve is currently publishing.  Nothing seems to help.

Some games don't produce anything interesting in the terminal for Steam.  Others do.  A curious one is when I try to launch DOOM 2016:

> GameAction [AppID 379720, ActionID 17] : LaunchApp changed task to WaitingGameWindow with ""
/bin/sh: +_: invalid option
Usage:	/bin/sh [GNU long option] [option] ...
	/bin/sh [GNU long option] [option] script-file ...

Another curious one is if I try Unreal Tournament 3:

> Adding process 89597 for game ID 13210
inaries/UT3.exe: ../../../../wine/dlls/ntdll/loader.c:3338: LdrInitializeThunk: Assertion ``wm' failed.
pid 89576 != 89575, skipping destruction (fork without exec?)
Game removed: AppID 13210 "", ProcID 89565

I assume that assertion failed message is important.  It also seems like Steam is trying to do things that Bash doesn't understand.  My interpreter used to be Dash.  It didn't work either but did produce a different error.

**Comment by ghost** [comment]
I fixed the issue by fully deleting all proton files under common and then rebooting.
Running steam in terminal only steam launching error and nothing related to proton. 
However I still have the audio problem but only in some games and not others.
Thanks for replying to me and helping me :)

**Comment by ghost** [comment]
i also fixed the audio. i messed with the game settings and it was fixed...
THANK YOU for helping me !!!! :)

**Comment by bonkmaykr** [comment]
> I fixed the issue by fully deleting all proton files under common and than rebooting.
> Running steam in terminal only steam launching error and nothing related to proton.
> However I still have the audio problem but only in some games and not others.
> Thanks for replying to me and helping me :)

Sorry for the necro-post, what files specifically are you referring to?

**Comment by paulstansifer** [comment]
I think it's everything under `~/.steam/steam/steamapps/compatdata`.

I did 
```
mv ~/.steam/steam/steamapps/compatdata/ /tmp/
mkdir ~/.steam/steam/steamapps/compatdata/
```
and it seems to have solved the problem for me.

Seems like the problem was caused by me copying my whole home directory from a previous Ubuntu installation.
