### ISSUE TITLE
[Whitelist Request] Fez (224760)

### ISSUE THREAD

**Issue by OMTDesign** [ValveSoftware/Proton#205]
The game Fez works perfectly fine, and even synced my save from my Windows PC.
![screenshot from 2018-08-23 13-34-10](https://user-images.githubusercontent.com/39666543/44499804-b8013100-a6d9-11e8-9ae2-9789206f0573.png)

My Specs are:
HP Zbook 15
Ubuntu 16.04
Linux Kernel 4.15.0-32
4700MQ Intel CPU
32GB Ram
K2100M Quadro GPU Nvidia driver 384.130
[Steam System Information](https://gist.github.com/OMTDesign/f0139824b9b23572b021be4764136472)

**Comment by kisak-valve** [comment]
Fez is a native linux game.

**Comment by OMTDesign** [comment]
I'm a moron.

**Comment by tgharib** [comment]
This made me giggle. :)

**Comment by flibitijibibo** [comment]
Easily my favorite review of FEZ Linux, glad it works!
