### ISSUE TITLE
All proton games frequently have zero download updates

### ISSUE THREAD

**Issue by oblitum** [ValveSoftware/Proton#2057]
I have around 20 proton games in my library, and frequently when I restart the system or the steam client, there's updates for all of them, and in general I need to click update for each one, and all of the updates are zero download size.

This [has been reported to happen](https://steamcommunity.com/groups/SteamClientBeta/discussions/1/1483235412197539850/) with Steam at other times, but with Proton games it's simply for all games, all the time.

**Comment by Ichinix** [comment]
Im curious about that behavior as well, i personally assumes these were minor updates to the proton wine implementation of Valve, but i would like to know if this is really the case or not :P

**Comment by kisak-valve** [comment]
Hello @oblitum, game updates are handled by the Steam client and this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5644. Closing as a duplicate.

**Comment by oblitum** [comment]
@kisak-valve I'm getting 0 bytes updates again lately.... I'm not using beta client (and I try to avoid them). I think this issue is back.
