### ISSUE TITLE
FINAL FANTASY XIII-2 (292140)

### ISSUE THREAD

**Issue by crowlogic** [ValveSoftware/Proton#2060]
Every time I try to run the game, it repeatedly tries to install dotnetfx35+.exe

# Compatibility Report
- FINAL FANTASY XIII-2
-FINAL FANTASY XIII-2

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @crowlogic, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Additionally, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by crowlogic** [comment]
thank you @kisak-valve 

https://gist.github.com/crowlogic/ed4d6af1695d4cb8f9a6ac67463816a0

**Comment by kisak-valve** [comment]
`err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed` in the log appears to be the more significant detail and points towards #18.

**Comment by madewokherd** [comment]
The launcher works in wine-mono, so this should work when #18 is fixed.

**Comment by iWeaker** [comment]
for me is working with FFXIII Prefix.. 
Change the prefix of FFXIII-2 to FFXIII, only the problem is that it has no sound, only voices.
Only if you have Final Fantasy XIII :P

**Comment by Loacoon1** [comment]
I confirm the bug reported, and there are others :
- First, there are no voices during the FMVs. In game audio is ok though.
- Second, the game is hugely CPU limited. It runs between 25 and 60 FPS, more often between 35 and 45, and my GPU fans don't even start (and that is with the FFXIIIfix). 
- Finally it has random HUGE stutters. The fix helps with it but it still happens pretty often.

**Comment by ghost** [comment]
This game now runs perfectly with the exception that it has massive stutters pretty often even on a Ryzen 3600 and 5500XT/mesa

I am not entirely sure if it's shader compilation but I don't necessarily see the shader compilation message during stutters when running with DXVK_HUD=compiler. I have not found a fix.

**Edit:**

Game significantly improved on stutters and performance when I switched to a kernel with fsync (5.9.14, slightly modified Arch kernel config (no dynticks/1000Hz), compiled with -march=znver2). Also installed an nVME drive and moved it off a slower hard drive, which made a large difference in general loading of stuff (sometimes during gameplay).

I'd say I am happy with how the game runs now and consider it much more playable than before.

The following are also changes I have made, that may or may not help, but I haven't noticed them to cause any problems:

Boot options: `PROTON_NO_WRITE_WATCH=1 %command%`

Using Steam's shader cache feature (comes with a 6.7MB dxvk cache for the game)

My dxvk.conf (next to `FFXiii2Launcher.exe` in the game folder):

```
dxvk.hud = compiler
d3d9.lenientClear = True
d3d9.forceSwapchainMSAA  = 0
d3d9.samplerAnisotropy  = 0
dxvk.numCompilerThreads = 12
dxvk.useRawSsbo = True
dxvk.useEarlyDiscard = True
d3d9.strictPow = False
d3d9.lenientClear = True
```

And using latest mesa-git.
