### ISSUE TITLE
Planetbase GC Issue

### ISSUE THREAD

**Issue by Drecondius** [ValveSoftware/Proton#2061]
# Compatibility Report
Planetbase
403190

## System Information
Nvidia GT760M
nvidia 410
4.18.0-12-generic x86_64

https://gist.github.com/Drecondius/c2c4d7dff81287ac14f2cc7a130f9dc0

proton version 3.7.8 and 3.16.4 beta

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

[steam-403190.log](https://github.com/ValveSoftware/Proton/files/2650989/steam-403190.log)

## Symptoms 
Fatal error in gc 
GetThreadContext Failed

I've deleted and wiped everything thus far multiple times. Switched between 3.7.8, 3.16.4beta multiple times all to no avail.

**Comment by Drecondius** [comment]
I want to add that I can run planetbase by running it from a terminal with the installed wine on the system.

**Comment by Drecondius** [comment]
Workaround is using PROTON_USE_WINED3D in launch options

**Comment by kisak-valve** [comment]
Hello @Drecondius, this is a known video driver regression, please downgrade to nvidia 410.xx (or older) or upgrade to nvidia 415.18.04. You're currently using 415.18.
