### ISSUE TITLE
DiRT 4 doesn't start

### ISSUE THREAD

**Issue by 5005007** [ValveSoftware/Proton#2063]
# Compatibility Report
- Name of the game with compatibility issues: DiRT 4
- Steam AppID of the game: 421020

## System Information
- GPU: 1060
- Driver/LLVM version: 410.78
- Kernel version: 4.15.0-42-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/5005007/2a276b2cdce17be5a419d268f4001c97
- Proton version: 3.7-8

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

[steam-421020.log](https://github.com/ValveSoftware/Proton/files/2654974/steam-421020.log)

## Symptoms 
Game doen't start

**Comment by kisak-valve** [comment]
Hello @5005007, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/992#issuecomment-445040081.

**Comment by 5005007** [comment]
@kisak-valve thanks a lot
