### ISSUE TITLE
[Whitelist] Delicious! Pretty Girls Mahjong Solitaire (540610)

### ISSUE THREAD

**Issue by magos-linux** [ValveSoftware/Proton#2068]
CPU: Intel(R) Core(TM) i7-4765T RAM: 16G SSD: KINGSTON SUV300S37A120G
Video: NVIDIA GeForce GTX 960 4G (nvidia 410.78)
OS: MagOS Linux 2016.64
DE: Plasma+compiz-fusion 1680x1050
Proton version: 3.7-8, 3.16-4beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.

**Comment by kisak-valve** [comment]
This game was found in the 2019-07-31 whitelist update.

If you encounter an issue with this game, please search the open issues for 540610, and report any issues encountered with this game in separate issue reports, one issue per issue report.
