### ISSUE TITLE
Sven Coop - Failed to create SDL Window

### ISSUE THREAD

**Issue by kgorol** [ValveSoftware/Proton#2071]
# Compatibility Report
- Name of the game with compatibility issues: Sven Coop
- Steam AppID of the game: 225840

## System Information
- GPU: AMD Radeon RX580 8GB
- Driver/LLVM version: Mesa 18.2.5-110 / AMDGPU 18.1.0-21
- Kernel version: 4.19.7-103.current
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kgorol/889cbbbb524cbdca5ec90b72c1860dfa
- Proton version: 3.7-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

When launching the game it causes the error with the message in title.

## Reproduction

Try to launch the game.

**Comment by kisak-valve** [comment]
Hello @kgorol, Sven Coop is a native linux game.
