### ISSUE TITLE
!!! Libmpg123 !!!

### ISSUE THREAD

**Issue by PaulCoral** [ValveSoftware/Proton#2073]
TO ADD
Libmpg123-0:i386 package is really important for many games (...oblivion) 
It makes the game more stable with better performances
This should be added in proton libraries

**Comment by PaulCoral** [comment]
up

**Comment by kisak-valve** [comment]
Hello @lepaincestbon, this issue is already being tracked at #957. Closing as a duplicate.

Also, https://github.com/ValveSoftware/steam-runtime/commit/d71625fe19d054d61392517b2f9c9febf4b99734.
