### ISSUE TITLE
Add the nvapi fake dlls and .so's to Proton

### ISSUE THREAD

**Issue by Alexmitter** [ValveSoftware/Proton#2079]
The nvapi dlls from steam aren't shipped with Proton, I have to add them manually to get some games running. It seems Doitsujin recommended to not use them so DXVK runs best, so i guess based on this, valve removed them. But as DXVK now by default act like a AMD GPU, i guess this is obsolete.

So far i did not see problems with adding the .so's and fake dlls from wine.

Xubuntu 18.04
Xfce 4.12
Intel i7-7700K
NVIDIA GeForce GTX 1060 6GB @ 396.54

**Comment by aeikum** [comment]
What game are you having trouble with? Proton 3.16 now pretends that all Nvidia cards are actually AMD cards, so applications shouldn't try to load nvapi.

**Comment by Alexmitter** [comment]
@aeikum It does, but only for DXVK Games. Games like GTA4 that run based on Wines own DX9 to OpenGL Translator do not do this and require it.

**Comment by aeikum** [comment]
No, we override the nvidia device IDs for wined3d, too. See ValveSoftware/wine@1091eaf13692b16ed66328ceeebfc587075fec6c.

**Comment by Alexmitter** [comment]
@aeikum Sorry, my fault. But then here must be a different problem as it still only starts with the libs in place.

**Comment by ghost** [comment]
You can use the nvapi dll stubs from wine staging with dxvk. I have had no problems with any of the affected games long since before the fake device id hack was implemented.
I don't think you should be going around messing with the device ids, especially when there is a working solution to the problem already.

**Comment by Alexmitter** [comment]
@ItsiAdam Thats exactly what i do. But its not the One Click solution.

**Comment by ghost** [comment]
Isn't it the purpose of proton to be a one click solution? 
Wine staging patches should be included with Proton to begin with... I see no reason for them not to. 
It'd also be wise for hacks like the device id hack to not be implmented at a renderer level.

**Comment by pchome** [comment]
@aeikum 
I'm not sure if it worth attention, but [DXVK supports some interfaces](https://github.com/doitsujin/dxvk/blob/684355dfcae0b1054b7cf62bb4146a88bb03b4b7/src/d3d11/d3d11_context_ext.h#L9-L64) for D3D11 extensions, so at least [NvAPI_D3D11_SetDepthBoundsTest](https://github.com/wine-staging/wine-patched/blob/master/dlls/nvapi/nvapi.c#L686-L711) could be implemented using them.

This should add some headache and ~1-2fps(unlikely) in some d3d11 games ([UE4](https://pcgamingwiki.com/w/index.php?title=Special:Ask&q=%5B%5BCategory%3AGames%5D%5D+%5B%5BUses+engine%3A%3AEngine%3AUnreal+Engine+4%5D%5D&p=format%3Dbroadtable%2Flink%3Dall%2Fheaders%3Dshow%2Fintro%3D-20-3Ch2-3EUnreal-20Engine-204-20Games-3C-2Fh2-3E%2Fsearchlabel%3D...-20further-20results%2Fclass%3Dsortable-20wikitable-20smwtable&po=%3FDirect3D+versions%3DD3D%0A%3FAvailable+on%3DSystems%0A%3FRelease+date%23ISO%7C%2Blimit%3D1%0A&limit=100&eq=no), [CryEngine3](https://pcgamingwiki.com/w/index.php?title=Special:Ask&q=%5B%5BCategory%3AGames%5D%5D+%5B%5BUses+engine%3A%3AEngine%3ACryEngine+3%5D%5D&p=format%3Dbroadtable%2Flink%3Dall%2Fheaders%3Dshow%2Fintro%3D-20-3Ch2-3ECryEngine-203-20Games-3C-2Fh2-3E%2Fsearchlabel%3D...-20further-20results%2Fclass%3Dsortable-20wikitable-20smwtable&po=%3FDirect3D+versions%3DD3D%0A%3FAvailable+on%3DSystems%0A%3FRelease+date%23ISO%7C%2Blimit%3D1%0A&limit=100&eq=no) and others using this function).

_p.s. For curious ones
I still looking for an adequate benchmark to test this, but if anyone want to experiment -- here is [nvapi{,46}.dll.so](https://github.com/ValveSoftware/Proton/files/3331911/dxvk.nvapi.zip) files compiled for Proton 4.2. Just make sure you have `dxgi.nvapiHack = False` in `dxvk.conf` and no other nvapi™ dlls installed (like `nvcuda`, they wouldn't work)._
