### ISSUE TITLE
[Whitelist] Neverwinter (109600) 

### ISSUE THREAD

**Issue by vampywiz17** [ValveSoftware/Proton#2089]
# Whitelist Request
- Name of the game to be whitelisted: Neverwinter
- Steam AppID of the game: 109600

## System Information
- GPU: GTX1060 3GB
- Driver/LLVM version: nvidia 390.87
- Distro version: Ubuntu 18.10
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/vampywiz17/5711eb79a513b9157773b2691b07bd41
- Proton version: 3.16-5

## I confirm:
- [ x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [ ] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ x] Although I consider the gaming experience equal to Windows there are remaining issues:

Only one thing. Need to set mouse to 125hz to resolve input lag. No other problem at all.

**Comment by kisak-valve** [comment]
Hello @vampywiz17, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1725#issuecomment-447415852.
