### ISSUE TITLE
Age of Mythology doesn't start

### ISSUE THREAD

**Issue by NatoBoram** [ValveSoftware/Proton#209]
I saw [here](https://github.com/ValveSoftware/Proton/issues/107#issuecomment-415073127) that specific issues about non-whitelisted games would be reported, so I wanted to try and report non-working games as well.

It would be cool to have a few issue templates for reporting what games does or doesn't work.

**Game :** [Age of Mythology](https://store.steampowered.com/app/266840/)

**Problem :** If I select "bypass launcher", I have an error message that I screenshoted below. If I select "play game", some dependencies gets installed then nothing happens.

**System :**

```bash
nato@NatoUbuntu 
--------------- 
OS: Ubuntu 18.04.1 LTS x86_64 
Kernel: 4.15.0-32-generic 
Uptime: 2 hours, 11 mins 
Packages: 2222 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: GNOME 3.28.2 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Ubuntu-mono-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3570K (4) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 3913MiB / 7922MiB 
```

![screenshot from 2018-08-22 22-26-30](https://user-images.githubusercontent.com/10495562/44501425-2b179280-a65b-11e8-8f23-0b1353b0396b.png)

**Comment by NatoBoram** [comment]
Problem was with my setup. I didn't correctly install the latest driver. [PREREQS.md](https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md#nvidia) solved my problem.

I'd add some extra security steps just to be sure it doesn't brick my system because the Nvidia drivers often did just that. Before continuing, close all programs and save your work.

```bash
sudo add-apt-repository ppa:graphics-drivers/ppa
sudo apt full-upgrade -y --auto-remove
sudo reboot
```

Then go to *Software & Updates/Additional Drivers/**Using NVIDIA driver metapackage from nvidia-driver-396 (open source)***, click **Apply Changes**, reboot when the installation finishes, and it should work just fine.

**Comment by cRaZy-bisCuiT** [comment]
@NatoBoram I have correctly installed drivers (RX580 with Mesa and amdgpu) but I got the same error. In addition, the game tries to install prerequisites  on every launch again and those seems to fail. Any ideas?

Should I add logs here and we re-open the issue or just create a new one?

**Comment by kisak-valve** [comment]
Hello @cRaZy-bisCuiT, since this issue was closed, go ahead and open a new issue report.
