### ISSUE TITLE
Blackwake

### ISSUE THREAD

**Issue by LieutenantLuciano** [ValveSoftware/Proton#2090]
# Whitelist Request
- Name of the game to be whitelisted: Blackwake
- Steam AppID of the game: 420290

## System Information
- GPU: GTX 1060
- Driver/LLVM version: nvidia 410.78
- Distro version: Solus 3.9999
- Proton version: 3.16-4

## I confirm:
- [✔] that pressing the `Play` button in the Steam client is sufficient.
- [✗] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [✔] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [✔] I haven't experienced any issues.
- [✔] There are no issues left open for this game.
- [✗] Although I consider the gaming experience equal to Windows there are remaining issues

## How To:
https://steamcommunity.com/sharedfiles/filedetails/?id=1572108095

**Comment by kisak-valve** [comment]
Hello @LieutenantLuciano, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1909#issuecomment-447532277.
