### ISSUE TITLE
Mega Man Legacy Collection (363440) Crash at startup

### ISSUE THREAD

**Issue by Agemndon** [ValveSoftware/Proton#2093]
# Compatibility Report
- Name of the game with compatibility issues: Mega Man Legacy Collection
- Steam AppID of the game: 363440

## System Information
- CPU: AMD Ryzen 7 1700x
- GPU: GTX 970
- Driver/LLVM version: NVIDIA 415.18
- Kernel version: 4.15.0-42-generic

- Link to full system information report as [Gist](https://gist.github.com/Agemndon/f6909875d112da6ca50250615c87c45e#file-steam_system_info)
- Proton version: 3.7, 3.16

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-363440.log](https://github.com/ValveSoftware/Proton/files/2682568/steam-363440.log)

## Symptoms
Does not start at all. After clicking "play" in steam, a black window appears and closed after a half of a second. I tried to use different proton versions, but they all produce the same behavior. 

The workaround from 
https://steamcommunity.com/app/363440/discussions/0/521643320370342705/#c1744479698813111075
does not work.

## Reproduction
Just start the game.

**Comment by Zero86Sk** [comment]
## System Information
- GPU:  GTX 1070
- Driver/LLVM version:  Nvidia driver 415.23
- Kernel version:  4.15.0-42
- Link to full system information report as [Gist](https://gist.github.com/Zero86Sk/849961ad66438e3e6240198d06fbce5c)
- Proton version: 3.16-5 beta

Game runs fine on my end
Ryzen 7 2700
GTX 1070

but saves dont work, it says saves are corrupted and it cant even save the options

not sure if its the latest patch doing it.
Mark as Regession please.

**Comment by Zero86Sk** [comment]
> # Compatibility Report
> * Name of the game with compatibility issues: Mega Man Legacy Collection
> * Steam AppID of the game: 363440
> 
> ## System Information
> * CPU: AMD Ryzen 7 1700x
> * GPU: GTX 970
> * Driver/LLVM version: NVIDIA 415.18
> * Kernel version: 4.15.0-42-generic
> * Link to full system information report as [Gist](https://gist.github.com/Agemndon/f6909875d112da6ca50250615c87c45e#file-steam_system_info)
> * Proton version: 3.7, 3.16
> 
> ## I confirm:
> * [x]  that I haven't found an existing compatibility report for this game.
> * [x]  that I have checked whether there are updates for my system available.
> 
> [steam-363440.log](https://github.com/ValveSoftware/Proton/files/2682568/steam-363440.log)
> 
> ## Symptoms
> Does not start at all. After clicking "play" in steam, a black window appears and closed after a half of a second. I tried to use different proton versions, but they all produce the same behavior.
> 
> The workaround from
> https://steamcommunity.com/app/363440/discussions/0/521643320370342705/#c1744479698813111075
> does not work.
> 
> ## Reproduction
> Just start the game.

nvidia drivers 415.18 seem broken, try going with 410 drivers or 415.22 and up

**Comment by Agemndon** [comment]
Confirmed. The 410 and the new 415.23 works... I actually thought I used the 410 driver some weeks before... maybe a weird driver<->game version combination.

Thanks for the help!

It seems to be a driver issue, so I close the issue again.
