### ISSUE TITLE
Witcher 1 When  set language as Chinese and save game will cause crash

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#2094]
# Compatibility Report
The game work fine unless you set the language as chinese.when save the game it will crash and wont save. 

- Steam AppID of the game:
20900
## System Information
- GPU: gtx960m hd 4600
- Driver/LLVM version:  Mesa 18.3.1 or nvidia 415.23 
- Kernel version: 4.19.8
- Link to full system information report as [Gist](https://gist.github.com/):
https://gist.github.com/spphinslove/9d3ec6a3b82f63e855e98f8372da67a5
I use bumblebee to switch videocard between intel and nvidia.
- Proton version:
3.16-5Beta
## I confirm:
- [] that I haven't found an existing compatibility report for this game.
- [YES] that I have checked whether there are updates for my system available.

## PROTON_LOG

[steam-20900.log](https://github.com/ValveSoftware/Proton/files/2682604/steam-20900.log)
## Symptoms 
Crash
## Reproduction
option->subtitles->chinese
run game and save game or wait autosave.

**Comment by kisak-valve** [comment]
Hello @spphinslove, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/255#issuecomment-447584408.
