### ISSUE TITLE
Spacelords (436180)

### ISSUE THREAD

**Issue by KibaGasteiz** [ValveSoftware/Proton#2098]
Since this issue (https://github.com/ValveSoftware/Proton/issues/441) is closed now and the game works just fine i ask for whitelisting it.

# Whitelist Request
- Name of the game to be whitelisted: Spacelords
- Steam AppID of the game: 436180

## System Information
- GPU: GTX 1070
- Driver/LLVM version: nVidia 415.22
- Distro version: Antergos x64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/KibaGasteiz/f90ab0f1bd5509e4139fa99b79c1c067
- Proton version: 3.16-5 Beta

## I confirm:
- [*] that pressing the `Play` button in the Steam client is sufficient.

## Issues
- [*] I haven't experienced any issues.
- [*] There are no issues left open for this game.

**Comment by mimattr** [comment]
# Compatibility Report
- Name of the game with compatibility issues: **Spacelords**
- Steam AppID of the game: **436180**

## System Information
- GPU: **GTX 970**
- Driver/LLVM version: **NVIDIA 415.25**
- Kernel version: **4.4.0-141-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **3.16-6 Beta**

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. (#441 closed)
- [x] that I have checked whether there are updates for my system available.

[steam-436180.log](https://gist.github.com/mimattr/3e74050f425e8ba848be6279b2578bad)

## Symptoms
Consistent application hang/freeze during the launch process (black screen)

## Reproduction
1. Select the title within your `Library` using the Steam client and press the `Play` button

**Comment by KibaGasteiz** [comment]
The game is working great, but i have one problem.
I played a lot with normal speakers, but one day i played with earphones, the game worked fine too, but today the sound and music only play through earphones, if i don't connect any the game has no sound, and there is no option in the game to switch sound output, so i can only play with earphones.
Using Logitech G430, a very common earphones on Antergos/Arch.

**Comment by cvelasco88** [comment]
Hi, I can play the tutorial perfectly, but when it finishes the game closes and, when I try to run again it start the tutorial again.
`PROTON_LOG=1 %command%`
[steam-436180.log](https://github.com/ValveSoftware/Proton/files/5203964/steam-436180.log)

I tried too:
`LD_DEBUG=libs PROTON_LOG=1 %command%`
[steam-436180.log](https://github.com/ValveSoftware/Proton/files/5207942/steam-436180.log)

**Comment by cvelasco88** [comment]
My experience says that: 
- **Proton 5.0-9** didn't worked for me on this game. After run with 5.9-GE-6-ST the main screen at least works.

Custom proton `https://github.com/GloriousEggroll/proton-ge-custom/wiki`
- **Proton 5.9-GE-3-ST** (50% sure) doesn't works (to move from tutorial to campaign). After run with 5.9-GE-6-ST the main screen at least works.
- **Proton 5.9-GE-6-ST** works. I was playing a couple games (ping extremly high) but all the other worked fine
