### ISSUE TITLE
Importing a library from a windows install /w steam play forced can overwrite files if the title has a linux version

### ISSUE THREAD

**Issue by Midaychi** [ValveSoftware/Proton#21]
If you have steam play beta enabled+forced and import a windows steam library, if any of the titles have linux compat they will be overwritten with the linux versions. 
Normally this wouldn't be an issue (besides kind of ruining the windows side of things), but there are some games that are listed as having linux compat but haven't actually implemented it yet. 

Example:
"Battletech" for instance, is listed as having linux compat, but it consists of an empty folder (with a JPG in a folder if you have the dlc). If you import a windows version of Battletech, during validation it will delete all the data and replace it with an empty folder (and dlc jpg if you have it).

**Comment by kisak-valve** [comment]
Hello @Midaychi, the feature request at https://github.com/ValveSoftware/steam-for-linux/issues/3189 covers this issue.

Issues with empty depots should be brought to the attention of the game dev(s).

Closing in favor of the existing issue report.
