### ISSUE TITLE
[Suggestion] Add an option to open the prefix folder of the game on Steam

### ISSUE THREAD

**Issue by KayKay91** [ValveSoftware/Proton#2115]
Let's be honest, hunting down a steam ID to find the WINEPREFIX in Proton can be tedious. Why not add an option to open the game's prefix folder in Preferences if it uses the software to play it.

Another one would be running an EXE file inside that prefix for people who wanna install mods, something which Lutris has.

**Comment by CSahajdacny** [comment]
It will be useful to have, if Proton is enabled, a Protoncfg (winetricks) button per game.
example: right clicking Game--» Properties --» General --» ProtonCFG

**Comment by kisak-valve** [comment]
Hello @KayKay91, this is a feature request for the Steam client, not Proton itself, and is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5667. Closing as a duplicate.
