### ISSUE TITLE
Short note to the Developers.

### ISSUE THREAD

**Issue by lucifertdark** [ValveSoftware/Proton#2116]
I'd just like to say a quick THANK YOU to everyone who has been working on Proton/Steam Play over the last few months, I don't think it gets said often enough, you have all done an amazing job, THANK YOU!

Happy Christmas to Everyone & a Linux New Year too. :smile:

**Comment by aeikum** [comment]
You're welcome, glad you're enjoying it :) The networking fixes and DXVK 0.94 were too good to wait until after holiday break, so we worked hard to get them out yesterday. Have a good holiday!
