### ISSUE TITLE
The Witcher: Enhanced Edition (20900)

### ISSUE THREAD

**Issue by ItsDaFaz** [ValveSoftware/Proton#2118]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher: Enhanced Edition
- Steam AppID of the game: 20900

## System Information
- GPU: NVIDIA GTX 750
- Driver/LLVM version: 
- Kernel version: Linux 4.18.0-13-generic
- Link to full system information report as <a href="https://gist.github.com/ItsDaFaz/63014ef5da7583358f8deeeb4d24cada#file-sysinfo-txt">GIST</a>
- Proton version: 3.16-4

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When I try to run the game which is installed in an ext4 partition, the game closes right after the DirectX install dialog pops up. There is no other message that pops up afterwards.
I do have Python 2.7+ installed. I believe installing the game on a separate HDD formatted to ext4 is an issue

## Reproduction
Just clicking play

**Comment by kisak-valve** [comment]
Hello @ItsDaFaz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/255#issuecomment-449582332.
