### ISSUE TITLE
Wrong default audio device for proton titles

### ISSUE THREAD

**Issue by MayeulC** [ValveSoftware/Proton#2120]
(Using the issue template from steam-for-linux)
#### Your system information

* Steam client version (build number or date): Dec 14 2018 at 22:19:08
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Audio API: Pulseaudio 12.2
* Desktop environment: KDE plasma 5 (X.org)

##### Expected behaviour:
When launching a Proton title, I expect it to choose my default audio device as an output.
For reference, I have three outputs:
* (pulseaudio index 1) HDMI port on my R9 Fury card
* (pulseaudio index 2) Analog output on my motherboard
* (pulseaudio index 3, default) USB headset

##### Observed behaviour:
Instead, proton games always choose the second device, and I must manually switch them to the correct one at first launch.

Most native titles do not exhibit this issue, even if some do exhibit other ones (FEZ _always_ switches back to the second one, it seems).

This can get annoying as some titles cut their audio output when they lose focus, making it hard to switch devices.

**Comment by aeikum** [comment]
Can you list a couple specific games that show this problem for you?

**Comment by MayeulC** [comment]
This turned out to be completely my fault, sorry for not following up earlier on this.

I hanged my `$HOME` to prevent steam from cluttering it [which is a big issue to me], but that prevented pulseaudio from accessing the correct settings. Symlinking `$NEWHOME/.config/pulse` to `$HOME/.config/pulse` worked around the issue.

Thank you for your help, and sorry for the noise.
