### ISSUE TITLE
Vagrant build fails due to updated Wine key

### ISSUE THREAD

**Issue by chrahunt** [ValveSoftware/Proton#2124]
Running the Vagrant-based build per the README instructions results in an error

```
...
    default: Need to get 171 MB of archives.
    default: After this operation, 1,107 MB of additional disk space will be used.
    default: WARNING: The following packages cannot be authenticated!
    default:   wine-devel-amd64 wine-devel-i386:i386 wine-devel winehq-devel
    default: E: There were unauthenticated packages and -y was used without --allow-unauthenticated
...
```

This leads to a large number of packages not being installed and subsequent build failing with missing dependencies.

Per [the wiki](https://wiki.winehq.org/index.php?title=Ubuntu&oldid=3147) the Wine signing key was updated on 2018-12-19 and is now available from `https://dl.winehq.org/wine-builds/winehq.key`.

**Comment by optlink** [comment]
If you update line 27 of the Vagrantfile with that URL it appears to build.

EDIT: The built Proton does not work in Steam.

**Comment by aeikum** [comment]
Thanks, pushed 4a5f7064b3a7f20cc7206db946d5f8a47b8ca7e7 to fix this.
