### ISSUE TITLE
PS3 Controllers not working as expected in GTA VC

### ISSUE THREAD

**Issue by CyberManifest** [ValveSoftware/Proton#2126]
# Compatibility Report
- Name of the game with compatibility issues: Grand Theft Auto Vice City
- Steam AppID of the game:

## System Information
- GPU:  Whatever is on Steam Play
- Driver/LLVM version:  nvidia on Steam Play ?
- Kernel version:  ? Steam Play
- Link to full system information report as [Gist](https://gist.github.com/): (On Different Machine Presently)
- Proton version: Don't Know

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 Can't I'm having problems also on Nvidia Shield and it doesn't have terminal access. 

## Symptoms 

In GTA Vice City for Steam Play in Linux or STEAM Play on Nvidia Shield I can't get a Dualshock 3 Playstation 3 Sixaxis controller to work properly or like it has traditionally worked outside of steam in the game. The camera constantly spins and I can't remap some keys in game. I've tryed different templets and different controller profiles but nothing seems to work. It's worth noting my controller works in other aspects of my Linux setup and on the Nvidia Shield like with other non steam games. So drivers are installed and functioning, but there seems to be an issue between the Steam layer and the Grand Theft Auto Vice City game.

I Reported it on Steam and was directed here to report it.

**Comment by kisak-valve** [comment]
Hello @CyberManifest, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/291#issuecomment-449637385.
