### ISSUE TITLE
The Surge (378540)

### ISSUE THREAD

**Issue by ziabice** [ValveSoftware/Proton#2129]
# Whitelist Request
- Name of the game to be whitelisted: The Surge
- Steam AppID of the game: 378540

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 18.2.6/7.0.0
- Distro version: Manjaro
- Link to full system information: [https://gist.github.com/ziabice/8c19008e58f82b16a62f7ab65ba235d4](https://gist.github.com/ziabice/8c19008e58f82b16a62f7ab65ba235d4)
- Proton version: 3.16-6 (works also with 3.16-5)

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [x] Although I consider the gaming experience equal to Windows there are remaining issues: 
some users experienced this issue #410

This game is working perfectly at very high graphic detail. Everything worked like expected, controls where smooth and I haven't noticed any issue after 2 hours of gameplay.

**Comment by kisak-valve** [comment]
Hello @ziabice, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/410#issuecomment-449638083.
