### ISSUE TITLE
Witcher 3 on linux mint 18

### ISSUE THREAD

**Issue by Bartasparkur** [ValveSoftware/Proton#2130]
# Compatibility Report
- Name of the game with compatibility issues: Witcher 3
- Steam AppID of the game: 292030

## System Information
- GPU: GTX 950
- Driver/LLVM version: nvidia 415.25
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Bartasparkur/15571b1fe84ec8596148ef73b960ba06
- Proton version: 3.7-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 I refunded the game, so i can't do this. I just wanna know if it's possible to play on my pc

## Symptoms 
Game crashes after the "preparing to launch witcher 3" screen with no error message

## Reproduction
Every time

I haven't found a similar issue

**Comment by kisak-valve** [comment]
Hello @Bartasparkur, without a proton log and your refund of the game, there's no reasonable way to evaluate why the game was not working for you. There's some discussion about this game at #607.

Closing as invalid.
