### ISSUE TITLE
Battlefleet Gothic: Armada (363680) - game freeze with XID error

### ISSUE THREAD

**Issue by Zlopez** [ValveSoftware/Proton#2132]
# Compatibility Report
- Name of the game with compatibility issues: Battlefleet Gothic: Armada
- Steam AppID of the game: 363680

## System Information
- GPU: GeForce GTX 960
- Driver/LLVM version: nvidia 415.22
- Kernel version: 4.19.9
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Zlopez/1433022f5f75aebc3155a622997b2997
- Proton version: 3.16-6
- Proton log: [steam-363680.log](https://github.com/ValveSoftware/Proton/files/2706301/steam-363680.log)

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms

The game freezes on same place in tutorial mission after boarding the station. I assume there should be some explosion.

This is shown in journalctl:
```
Dec 23 22:23:24 zlopez-gamestation kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x405848=0x80000000
Dec 23 22:23:24 zlopez-gamestation kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: Shader Program Header 5 Error
Dec 23 22:23:24 zlopez-gamestation kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: Shader Program Header 10 Error
Dec 23 22:23:24 zlopez-gamestation kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: Shader Program Header 18 Error
Dec 23 22:23:24 zlopez-gamestation kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x405840=0x84040420
Dec 23 22:23:24 zlopez-gamestation kernel: NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ChID 003b, Class 0000b197, Offset 00002390, Data 433de000
```
## Reproduction
1. Start the game
2. Start new campaign
3. Go through the tutorial (the game freezes in dialogue after station is boarded)

**Comment by kisak-valve** [comment]
Hello @Zlopez, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2002#issuecomment-449664939.

**Comment by Zlopez** [comment]
Sorry, the issue was different, so I created a new issue to prevent the confusion.
