### ISSUE TITLE
Katamari Damacy REROLL (848350) - Unplayable game

### ISSUE THREAD

**Issue by kddlb** [ValveSoftware/Proton#2133]
# Compatibility Report
- Name of the game with compatibility issues: Katamari Damacy REROLL
- Steam AppID of the game: 848350

## System Information
- GPU: Intel Iris Pro 580
- Driver/LLVM version: 3.0 Mesa 18.3.1
- Kernel version: 4.19.12
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kddlb/49fa8b6dd194c62f20e67484d2373a80
- Proton version: 3.16-6

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

_Important: this is a different issue from #2125 - in this case, the game is unplayable._

## Symptoms 
The game freezes when the "Produced by NAMCO" screen fades out.

## Reproduction
1. Open the game
2. Wait for the logo slideshow (Bandai Namco, Criware, etc) to end.

[steam-848350.log](https://github.com/ValveSoftware/Proton/files/2706458/steam-848350.log)

**Comment by kisak-valve** [comment]
Hello @kddlb, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2125#issuecomment-449674604.
