### ISSUE TITLE
Grand Theft Auto V Crash

### ISSUE THREAD

**Issue by octinhuh** [ValveSoftware/Proton#2140]
# Compatibility Report
- Name of the game with compatibility issues: Grand Theft Auto V
- Steam AppID of the game: 271590

## System Information
- GPU: RX 480
- Driver/LLVM version: AMD GPU Pro 18.50
- Kernel version: 4.15.0-43-generic
- Link to full system information report as [Gist](https://gist.github.com/octinhuh/f5af40dd105d0cb574f78ee27b1d0cfa):
- Proton version: 3.16-6

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

No Proton Log was created, computer hard locks

## Symptoms

Game runs smoothly until certain seemingly scripted events occur, in which case the computer hard locks up; no keyboard/mouse/controller response, still image, but music continues to play. It happens in both story and online mode. In the benchmark, it crashes exactly when the jet flies under the bridge. I have to reset the computer when a crash occurs.

## Reproduction
Launch the game
Choose story/online mode or run the graphics benchmark.
Play/wait for a bit
Crash

I've updated Mesa drivers, changed proton versions, tried disabling esync in the launch options, but to no avail. The same symptoms occur no matter what I do. Without a crash log, it is hard to diagnose anything at all.

I'm having a hard time with this, and it looks like this issue hasn't been reported before.

**Comment by Guy1524** [comment]
AMDGPU Pro is not supported for proton, see https://github.com/ValveSoftware/Proton/wiki/Requirements

**Comment by kisak-valve** [comment]
Hello @octinhuh, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-449891289.
