### ISSUE TITLE
[Whitelist] Deathsmiles (314180)

### ISSUE THREAD

**Issue by roothorick** [ValveSoftware/Proton#2144]
# Whitelist Request
- Name of the game to be whitelisted: Deathsmiles
- Steam AppID of the game: [314180](https://store.steampowered.com/app/314180/Deathsmiles/)

## System Information
- GPU: GeForce GTX 1080 Ti
- Driver/LLVM version: Nvidia official 396.54
- Distro version: Ubuntu 18.04.1 LTS
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/roothorick/d396d9bf9f4a568c7d6cb82224c85307
- Proton version: 3.7-2

## I confirm:
- that pressing the `Play` button in the Steam client is sufficient.

## Issues
- I haven't experienced any issues.
- Caveat: I have not tested controller support.

**Comment by jonlap** [comment]
# Whitelist Request

## System Information
- GPU: RX 480
- Driver/LLVM version: Mesa 19.0.3 / 8.0.0
- Distro version: Arch
- Link to full system information report as [Gist](https://gist.github.com/): see [here](https://gist.github.com/skry/8c9e87a99102e8a529d081235cff6826)
- Proton version: 4.2-3

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

Complementing the original whitelist request, I did test controller support with 360 controller. It works.

**Comment by AwesamLinux** [comment]
Distro: Linux Mint 19.1 Tessa (64 bit)
GPU: Vega 56
Driver/LLVM version: Mesa 19.1.0-devel/9.0.0
Kernel version: 5.1.0-050100-lowlatency
Proton version: 4.2-3

I can confirm the game works perfectly

- Tried windowed and fullscreen
- Minimizing and Maximizing window works
- Alt+Tab between desktop/game works
- Switching between fullscreen and windowed works
- Performance like on Windows
- Nintendo Switch Pro controller over bluetooth worked

Including a log for scrutiny of when I just launched the game and played for a bit
[steam-314180.log](https://github.com/ValveSoftware/Proton/files/3169929/steam-314180.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3169930/system_info.txt)

**Comment by kisak-valve** [comment]
This game was found in the 2019-07-31 whitelist update.

If you encounter an issue with this game, please search the open issues for 314180, and report any issues encountered with this game in separate issue reports, one issue per issue report.
