### ISSUE TITLE
Heroes® of Might & Magic® III - HD Edition (297000) No sound

### ISSUE THREAD

**Issue by Takios** [ValveSoftware/Proton#2146]
# Compatibility Report
- Name of the game with compatibility issues: Heroes® of Might & Magic® III - HD Edition
- Steam AppID of the game: 297000

## System Information
- GPU: RX 480
- Driver/LLVM version: 18.3.1/7.0.0
- Kernel version: 4.19.11
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Takios/5dbfd1043520ddace6a8977c7300a3d7
- Proton version: Tested with 3.16-6 Beta and 3.7-8
- Pulseaudio Version: 12.2
- SDL2 Version: 2.0.9
- SDL1 Version: 1.2.15

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
There is no sound at all when playing the game. The game does not show up in `pavucontrol` or other sound managing programs at all. Ingame sound is turned up to full. Starting Steam and the game via command line, the following line is probably indicative of the problem:

`"Warning: Couldn't initialize SDL Audio: Audio target 'pulse' not available"`

My system does use Pulseaudio. Other applications and SDL games can output sound without issue. Tried to `export 

SDL_AUDIODRIVER=alsa` beforehand, but I get the same error message, but with alsa instead of pulse.

## Reproduction
Start the game.

[steam-297000.log](https://github.com/ValveSoftware/Proton/files/2710927/steam-297000.log)

**Comment by kisak-valve** [comment]
Hello @Takios, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/631#issuecomment-450033111.
