### ISSUE TITLE
Halo Wars don't start with Bumblebee or Intel HD only

### ISSUE THREAD

**Issue by ycharbi** [ValveSoftware/Proton#2147]
# Compatibility Report
- Name of the game with compatibility issues: "Halo Wars: Definitive Edition"
- Steam AppID of the game: 459220

## System Information
- PC: Dell XPS 9550
- GPU: Nvidia GTX 960M
- Driver/LLVM version: 390.87
- Kernel version: Tested on 4.18.0 and 4.19.0
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ycharbi/7fea52a2b12695a48a6b19456cf6dcf8#file-yohan_stdout-txt
- Proton version: Tested on 3.7-8 and 3.16-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-459220.log](https://github.com/ValveSoftware/Proton/files/2712230/steam-459220.log)

## Symptoms 
In English:
-On a desktop PC with a Nvidia GTX 970 graphics card and an Intel Core i7 960 processor (without Intel HD), the game works perfectly.
-With a Dell XPS 15 9550 equipped with an Nvidia GTX 960M graphics card and an Intel Core i7 6700HQ processor (with Intel HD), the game does not start (we see a black window open and close immediately). I use Bumblebee (Optimus) and I run the game with the following parameters to use the Nvidia card: `LD_PRELOAD="libpthread.so.0 libGL.so.1" _GL_THREADED_OPTIMIZATIONS=1 PROTON_LOG=1 optirun %command%` (I specify that the game "portal (appids = 400)" starts well with these arguments)
-With a Shuttle DS57U equipped with an Intel Core I5 5005U only with an Intel HD, I have the same symptoms as the Dell XPS 15.

The three machines are under Debian Sid (The Shuttle has also been tested under Ubuntu 18.04) with Gnome 3.30.2 and up to date with a Linux 4.19.0 kernel and a Steam client in version 1543346820 (updated on 12/27/18). I tested under Wayland and Xorg.

---------------------
En Français:
-Sur un PC fixe avec une carte graphique Nvidia GTX 970 et un processeur Intel Core i7 960 (sans Intel HD), le jeux fonctionne parfaitement.
-Avec un Dell XPS 15 9550 équipé d'une carte graphique Nvidia GTX 960M et d'un processeur Intel Core i7 6700HQ (avec Intel HD), le jeux ne se lance pas (on voit une fenêtre noire s'ouvrir et se fermer imédiatement). J'utilise Bumblebee (Optimus) et je lance le jeux avec les paramètres suivants pour utiliser la carte Nvidia: `LD_PRELOAD="libpthread.so.0 libGL.so.1" _GL_THREADED_OPTIMIZATIONS=1 PROTON_LOG=1 optirun %command%` (je précise que le jeu "portal (appids=400)" se lance bien avec ces arguments)
-Avec un Shuttle DS57U équipé d'un Intel Core I5 5005U seulement avec une Intel HD, j'ai les mêmes symptomes qu'avec le Dell XPS 15.

Les trois machines sont sous Debian Sid (le Shuttle a également été testé sous Ubuntu 18.04) avec Gnome 3.30.2 et à jour avec un noyau Linux 4.19.0 et un client Steam en version 1543346820 (à jour au 27/12/18). J'ai testé sous Wayland et Xorg.

## Reproduction
In English:
Just install a raw Debian Sid with Nvidia drivers from non-free sid repository as well as bumblebee via this procedure: https://doc.ycharbi.fr/index.php/Bumblebee. After installing the Steam client via this procedure: https://doc.ycharbi.fr/index.php/Steam_linux, I install the Halo Wars game by using the "Backup and Restore Games..." function of the "Steam" menu because my ADSL does not allow you to reinstall several gigabytes of data (the game has already been downloaded beforehand and a passage of "CHECK FACTOR INTEGRITY..." indicating no problems) ...
I add the launch options to the games and I execute it -> fail.

En Français:
Il suffit d'installer un Debian Sid vièrge avec les pilotes Nvidia des dépôts Sid non-free ainsi que bumblebee via cette procédue: https://doc.ycharbi.fr/index.php/Bumblebee. Après installation du client Steam via cette procédure: https://doc.ycharbi.fr/index.php/Steam_linux, j'installe le jeux Halo Wars en utilisant la fonction "Sauvegarder et restaurer des jeux..." du menu "Steam" car mon ADSL ne permet pas de réinstaller à foison plusieurs gigaoctets de données (le jeu ayant déjà été téléchargé au préalable et un passage de "VÉRIFIER L'INTÉGRITÉ DES FICHIERS..." n'indiquant aucun problèmes)...
J'ajoute les options de lancement au jeux et je l'exécute -> échec.

## Other
I am available for any further information.

**Comment by kisak-valve** [comment]
Hello @ycharbi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/480#issuecomment-450152385.
