### ISSUE TITLE
Bioshock Remastered - Won't Start (409710)

### ISSUE THREAD

**Issue by Thinkaboutmin** [ValveSoftware/Proton#215]
Hello,

Whenever I try to run Bioshock Remastered it's given a message saying that to play it I need Windows 7 or higher. I tried tweaking the version of Proton using Winecfg, but still nothing. Btw, I did some search on it and seems that the same happened on a guy with [Wine](https://appdb.winehq.org/objectManager.php?sClass=version&iId=35804).

**Comment by DissCent** [comment]
It actually starts fine for me using stock Proton on Manjaro Linux, although it has some problems in-game.

**Comment by miguev** [comment]
Freezes early on, so early on I can't even start playing.
First time froze while adjusting gamma.
Last time froze during the 2K logo animation.

Ubuntu 18.04.1 LTS x86_64 
Kernel: 4.15.0-32-lowlatency 
CPU: AMD Ryzen 5 1600X
GPU: NVIDIA GeForce GTX 1070 (driver 390.48)

**Comment by Thinkaboutmin** [comment]
I noticed that I might have done something wrong. Before I installed Bioshock Remastered, I had modified the Pronton/Wine using Winecfg. Perharps, as I did that, it might have happened something, such as not installing the prerequisites thus, making the game unable to be open. Thanks for the answers, it opens as you guys said.

**Comment by miguev** [comment]
Why close this issue? Game freezes and crashes with stock Proton on Ubuntu 18.04 for me and other users. Only 4 out of other 12 users[1] report the game as Stable.

[1] as seen in the unofficial SteamPlay Compatibility Report Sheet (3025 reports so far) at https://docs.google.com/spreadsheets/d/1DcZZQ4HL_Ol969UbXJmFG8TzOHNnHoj8Q1f8DIFe8-8/htmlview

**Comment by dubigrasu** [comment]
@miguev 
Try with:
PROTON_NO_ESYNC=1 %command%

**Comment by Thinkaboutmin** [comment]
Actually, the game just didn't start for me. If it crashes or freezes then I think that another issue report should be created. And looking at that sheet, it shows that the ones who are having trouble are using Nvidia old drivers or AMD open source driver. Btw, the driver that you are using should be updated to the newest 396.51 as said in the [prerequisites](https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md) for Proton as the newest DXVK may have some problems on the older Nvidia driver.

**Comment by Thinkaboutmin** [comment]
seeing the @dubigrasu post, @miguev might as well try this too.
PROTON_USE_WINED3D11=1 %command%
This should disable DXVK and run the Wine D3D11 and maybe the game will run as expected in your computer.

**Comment by dubigrasu** [comment]
Tried just now (more extensively) Bioshock Remastered on my system and it works (almost) perfectly. It recognized the save I made few months ago and went straight in the game where I left.

I say almost perfectly because of two issues that can be solved though:
- One is that it hangs sometimes when I access the menus or try to save. This one is solved by adding:
PROTON_NO_ESYNC=1 %command%
to the launch options.
- The second one is the mouse having only a limited range of movement, left+right, up+down (an issue well known for those using Wine). This one can be solved (is actually more like a workaround) by using the Steam Controller with the "Gamepad with Camera Controls" template.
I also tested an Xbox 360 wired gamepad, which can be argued that it delivers a better experience because it also has the Rumble working.

The performance is good (playing at highest settings) not dropping below 60 FPS, and as a bonus, it doesn't have the stutter I had while playing on Windows, which is the reason I stopped playing the Remastered version back then.

**Comment by miguev** [comment]
Thank you! Adding PROTON_NO_ESYNC=1 %command% to the launch options seems to have fixed both the original and remastered game. The original game was freezing for a few seconds every time I accessed a menu or started a hack of picked up a new plasmid, not anymore!

**Comment by DissCent** [comment]
I can indeed confirm that `PROTON_NO_ESYNC=1 %command%` fixes all issues! The game runs smoothly, graphics are perfect and I don't even have the "mouse gets stuck when moving" bug.

**Comment by P4NCH1** [comment]
In my case `PROTON_USE_WINED3D11=1 %command%` was the command that make it work.

**Comment by Xeers** [comment]
The games work "perfectly" with:
BioShock:           PROTON_NO_D3D11=1 PROTON_NO_ESYNC=1 %command%  
BioShock Remastered:  PROTON_USE_WINED3D11=1 PROTON_NO_ESYNC=1 %command%

**Comment by dreamer** [comment]
@Xeers PROTON_USE_WINED3D**10** ? Such variable is not recognized by Proton. Do you mean PROTON_USE_WINED3D**11**?

**Comment by Xeers** [comment]
Right, corrected. The game can, exceptionally, close. Save the game every so often.

**Comment by DissCent** [comment]
Actually, `PROTON_NO_ESYNC=1` alone does the trick for me. The game runs totally stable for me then (already played half-way through).

**Comment by Xeers** [comment]
BioShock ™ Remastered has a bug. In the bathisphere station (Point Prometheus) there is an enemy that never dies so it stops you from moving forward and open the door.
Images:
1. https://i.imgur.com/GvuUl3b.png
2. https://i.imgur.com/qddKnd1.png
---------------------------------------
I loaded a previous game and this time if I could continue.

**Comment by Corben78** [comment]
If core dumps are enabled, and the game crashed once, just the mere existence of the core file in `<SteamLibrary>/steamapps/common/BioShock Remastered/Build/Final` causes the game to segfault.
This is now also mentioned on the corresponding [PCGamingWiki](https://www.pcgamingwiki.com/wiki/BioShock_Remastered#Game_doesn.27t_start_anymore) article.
