### ISSUE TITLE
Farming Simulator 17 (447020)

### ISSUE THREAD

**Issue by framingnoone** [ValveSoftware/Proton#2150]
# Compatibility Report
Farming Simulator 17
447020

## System Information
- GPU: GTX 650
- Driver/LLVM version: 415.18
- Kernel version: 4.4
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/framingnoone/0df32aa1017412a9482b40bf94724a22
- Proton version: 3.16-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton Log
[steam-447020.log](https://github.com/ValveSoftware/Proton/files/2713632/steam-447020.log)

## Symptoms
Can't alt-tab without graphics rendering failure. Gameplay and fps otherwise is fine.

## Reproduction
Start game
load save game so you've got a farm visible
alt-tab out, alt-tab back in
Screen is now black, nothing visible.

I believe this also occurs in the main menu of Farming Simulator, though the proton log is of the previous described steps.

**Comment by kisak-valve** [comment]
Hello @framingnoone, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1361#issuecomment-450266040.
