### ISSUE TITLE
Devil May Cry 4 SE, Numerous graphical problems.

### ISSUE THREAD

**Issue by DigitalDevilSummoner** [ValveSoftware/Proton#2151]
# Compatibility Report
-Devil May Cry 4 Special Edition
- Steam AppID of the game: 329050

## System Information
https://gist.github.com/DigitalDevilSummoner/d7a227765539daee04f9fd1d98d2be93

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

When starting a level as Vergil, Lady, or Trish, the level doesn't load correctly, and it isn't always consistent either, I was able to play Lady's opening story missions just fine, but not vergil. Picking Vergil and Tris for Bloody Palace, also did not work.

When starting bloody Palace as Trish, I get this:

![dmc4se](https://user-images.githubusercontent.com/43498489/50499895-4b959600-0a1b-11e9-9d53-be7c16784a9e.png)

I get similar results for Vergil and Lady.

**Comment by kisak-valve** [comment]
Hello @DigitalDevilSummoner, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1779#issuecomment-450276284.
