### ISSUE TITLE
BIT.TRIP RUNNER (63710)

### ISSUE THREAD

**Issue by afettouhi** [ValveSoftware/Proton#2152]
# Compatibility Report
- Name of the game with compatibility issues: BIT.TRIP RUNNER
- Steam AppID of the game: 63710

## System Information
- GPU: GTX 1080
- Driver/LLVM version:  nvidia 415.25
- Kernel version: 4.19.12
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/afettouhi/aedb2e527d0acad7c7980dda0e9974e3#file-gistfile1-txt
- Proton version: 3.16-6

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

[steam-63710.log](https://github.com/ValveSoftware/Proton/files/2714409/steam-63710.log)

## Symptoms
Running the game gives this error widow stating "shader: failed to compile vertex shader". Game can be run using the beta branch though but there is no sound in the game.

## Reproduction

Install the game and run it with proton.

**Comment by kisak-valve** [comment]
Hello @afettouhi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/915#issuecomment-450362245.
