### ISSUE TITLE
DuckTales: Remastered crashes during final cutscene

### ISSUE THREAD

**Issue by drcouzelis** [ValveSoftware/Proton#2173]
# Compatibility Report
- Name of the game with compatibility issues: DuckTales: Remastered
- Steam AppID of the game: 237630

## System Information
- GPU: RX 560
- Driver/LLVM version: Mesa 18.3.1
- Kernel version: 4.20
- Link to full system information report as [Gist](https://gist.github.com/): [Gist](https://gist.github.com/drcouzelis/69cfe1457c9520f2dae862fd1ca29295)
- Proton version: 3.16-6 Beta

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

[steam-237630.log](https://github.com/ValveSoftware/Proton/files/2719128/steam-237630.log)
[steam-bash.log](https://github.com/ValveSoftware/Proton/files/2719129/steam-bash.log)

## Symptoms
Upon beating the final boss (Dracula Duck) and escaping from the volcano, the final cutscene will begin (Scrooge McDuck escaping in a helicopter). After a few seconds, the game will close.

## Reproduction
I have experienced this crash 3 out of 3 times when completing the game and attempting to view the final cutscene.

**Comment by drcouzelis** [comment]
This is the one and only issue I experienced in playing DuckTales: Remastered on Linux. Everything else has been perfectly functional, no bugs, 100% just "click and play".

**Comment by kisak-valve** [comment]
Hello @drcouzelis, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/597#issuecomment-450728446.
