### ISSUE TITLE
Into the breach wont start due to no available Audio targets (590380)

### ISSUE THREAD

**Issue by Barba-Q** [ValveSoftware/Proton#2174]
# Compatibility Report
- Name of the game with compatibility issues: Into the Breach
- Steam AppID of the game: 590380

## System Information
- System: Tried on several systems
- OS: openSuse Tumbleweed
- Proton version: Tried everything available to date

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 
- The game wont start at all. In the games log file it says: 
"SDL Error: Audio target 'pulse' not available".
So I've tried several options to bypass pulseaudio with steam and game parameters as well like: SDL_AUDIODRIVER=alsa steam 
and several other tricks. Even removing pulseaudio from the system only changes the log a bit:
"SDL Error: Audio target 'alsa' not available" but the game wont start whatsoever.

## Reproduction
Seems like this problem occurs on openSuse installations only. Some users got lucky using proton tricks but whether I'm untalented in fixing things by myself or I'm just unlucky. 

I understand that the whitlisting is based on Debianoid systems like Ubuntu, Mint or SteamOS itself but as long as Proton is a Steam-integrated thing it should be possible to make things run in this case

[log.txt](https://github.com/ValveSoftware/Proton/files/2719310/log.txt)
[steam-590380.log](https://github.com/ValveSoftware/Proton/files/2719311/steam-590380.log)

**Comment by kisak-valve** [comment]
Hello @Barba-Q, `SDL_AUDIODRIVER=pulse` isn't [a valid value for SDL 2](https://wiki.libsdl.org/FAQUsingSDL), you might have better luck with `SDL_AUDIODRIVER=pulseaudio`.

**Comment by Barba-Q** [comment]
Tried that as well, no luck

**Comment by aeikum** [comment]
This is actually a known Wine issue, see https://wiki.winehq.org/Sound#SDL_applications . If you set your SDL_AUDIODRIVER to a Windows backend like "directsound", it will work, I think. I'll add a workaround for this to Proton.

**Comment by Barba-Q** [comment]
directsound does the trick, thank you very much Sir.

**Comment by jdamboeck** [comment]
ty :) i'm in search for a fix for a month now :)

**Comment by aeikum** [comment]
Hello, Proton 3.16-7 now handles SDL_AUDIODRIVER automatically, so this workaround should no longer be necessary. Thanks for reporting.

**Comment by kisak-valve** [comment]
Reopening as a request to bump the whitelist for this game.

**Comment by kisak-valve** [comment]
Hello, this game has been bumped to Proton 4.11 in the 2020-03-10 whitelist update.
