### ISSUE TITLE
No audio in Blockland (250340)

### ISSUE THREAD

**Issue by 1024x2** [ValveSoftware/Proton#218]
When I play blockland, there is no sound at all. Otherwise, the game works perfectly fine!

I'm using Arch Linux (Linux 4.18.3) on a Thinkpad T430.

**Comment by Thinkaboutmin** [comment]
#206 
?

**Comment by 1024x2** [comment]
I've checked in `pavucontrol`, and the game isn't even showing up in there. I think it's because OpenAL (the audio library the game uses) might not be supported on Proton.

**Comment by Thinkaboutmin** [comment]
Hmmm, that's strange. Wine should support OpenAL, in a certain way. Anyway, not an expert so can't help any further. Just to check the basics :P

**Comment by mirh** [comment]
#177 ?

**Comment by vanyasem** [comment]
Cannot reproduce https://gist.github.com/vanyasem/f787469ec8c50cdd3728340ef4c73269

**Comment by 1024x2** [comment]
Oof, I've just tested the game again now and audio works perfectly fine. Must've been an issue with ALSA or PulseAudio when I first tested it.

Closing now.

**Comment by vanyasem** [comment]
Opened a whitelist request #1343
