### ISSUE TITLE
Failure to load embedded web page in game launcher (appid: 39210)

### ISSUE THREAD

**Issue by TenaarFeiri** [ValveSoftware/Proton#2183]
# Compatibility Report
- Name of the game with compatibility issues: Final Fantaxy XIV Online
- Steam AppID of the game: 39210

## System Information
- GPU: GTX 980M
- Driver/LLVM version: nVidia 390.87
- Kernel version: 4.18.0-13
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/TenaarFeiri/2733a8f25f8818a5c3e85777eed9be22
- Proton version: 3.7-8

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

https://gist.github.com/TenaarFeiri/9e560a89346b17cc2de0ac9b508259e8

## Symptoms 

The issue is Proton doesn't seem able to help ffxivlauncher.exe use the correct web browser to embed its login page with. I've had reports that the game itself is functional once you get past the launcher, but I'm unable to test it as this is a crucial step for downloading the game.

The launcher itself reports a HTTPS 404 error, as it can't find a browser to use for the launcher's landing page.

## Reproduction

- Download and install Final Fantasy XIV Online.
- Launch the game. ffxivboot.exe will launch, and will give you no useful information as the font is broken.
- ffxivboot.exe will eventually finish its download, and then it will open ffxivlauncher.exe
- Inform the launcher that you already have an account with the game.
- Proceed through its prompts until it's done guiding you through it.
- Observe the launcher attempt to open a webpage necessary to initiate the running of the game and fail.
- Close and restart the game as many times as desired.

**Comment by kisak-valve** [comment]
Hello @TenaarFeiri, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/580#issuecomment-451023179.
