### ISSUE TITLE
can't move character in Dark Souls 3 (374320)

### ISSUE THREAD

**Issue by labatts** [ValveSoftware/Proton#2184]
I can start the game, and got a character created (although I had to use my keyboard for the name), and then get into the actual game.  I cannot move the character.  I have tried this with a keyboard, ps4 controller, and steam controller.  In all instances, the character will face the direction that I indicate, but will not actually move.  Also, I can navigate menus.

I saw a similar discussion here: https://github.com/ValveSoftware/Proton/issues/127.  However, the said solution (forcing the steam control configurations off) does not work for me.  

FWIW:  proton 3.16-6.  ryzen 7 1700, vega 56.  manjaro kde

EDIT:  I also noticed that there were a whole host of windows folks who had the same issue.  The said solution was to move the Dark Souls folder outside of the default steam directory.  I tried this, but I of course could not get steam to start the game with it not there, nor could I start it outside of steam (I don't have wine installed).  So, maybe I am missing something obvious here....

**Comment by thatlordbaal** [comment]
Did you create a new steam library folder first?

**Comment by labatts** [comment]
> Did you create a new steam library folder first?

Oh, I miss understood what they meant (if that is what they meant anyway).  Okay, I am installing it right now under a newly created steam library folder.  I will update.  Hopefully that is all it is.

EDIT:  Okay, that is what it was.  Thank you for your help.  Seems I really did miss something obvious!!

EDIT 2: not sure if I should do something other than just closing this...
