### ISSUE TITLE
[Whitelist] Heat Signature (268130)

### ISSUE THREAD

**Issue by dericke** [ValveSoftware/Proton#2185]
# Whitelist Request
- Name of the game to be whitelisted: Heat Signature
- Steam AppID of the game: 268130

## System Information
- GPU: GTX 1050 Ti
- Driver/LLVM version: Nvidia 390.77
- Distro version: Ubuntu 18.04
- Link to full system information report as [Gist](https://gist.github.com/): [Here](https://gist.github.com/dericke/6fd871c523c75dadfd332d2ddc4e7a75)
- Proton version: 3.7-8

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [x] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

Played this for several hours with Proton and found the experience to be identical to that on Windows. No problems of any sort, and has a platinum rating on protondb with 19 reports.

**Comment by kisak-valve** [comment]
This game was found in the 2019-07-31 whitelist update.

If you encounter an issue with this game, please search the open issues for 268130, and report any issues encountered with this game in separate issue reports, one issue per issue report.
