### ISSUE TITLE
Can't Alt+Tab on Unreal Tournament: Game of the Year Edition (UT99)

### ISSUE THREAD

**Issue by absorber** [ValveSoftware/Proton#2187]
# Compatibility Report
- Name of the game with compatibility issues: Unreal Tournament: Game of the Year Edition
- Steam AppID of the game: 13240

## System Information
- GPU: Intel HD3000
- Driver/LLVM version: 3.0 Mesa 18.0.5
[steam-13240.log](https://github.com/ValveSoftware/Proton/files/2723304/steam-13240.log)

- Kernel version: 4.15.0-42-generic
- Link to full system information report as [Gist](https://gist.github.com/absorber/abe615aa12514c517de7109576e63968):
- Proton version: 3.16-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When I start the game, I can't Alt+Tab out of it anymore. This does not happen on Software Rendering.

## Reproduction
0. Start game
1. (If launch menu pops up choose Direct3D under rendering options)
3. Start a practice session
4. Alt+Tab

**Comment by kisak-valve** [comment]
Hello @absorber, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/568#issuecomment-451147417.
