### ISSUE TITLE
[Whitelist] Lego Incredibles 

### ISSUE THREAD

**Issue by eeyrjmr** [ValveSoftware/Proton#2188]
# Whitelist Request
- Lego Incredibles
- 818320

## System Information
- GPU: [GeForce GTX 970
- Driver/LLVM version: NVIDIA 415.25
- Distro version: Gentoo
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/eeyrjmr/446c791fdd0e0860cbcb3102dbd01373
- Proton version: 3.16-6 Beta 

## I confirm:
- [ x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

I have completed Lego:Incredibles completley in linux, using steam controllers and all via steam link with no issues since Proton 3.16-6

**Comment by kisak-valve** [comment]
Hello @eeyrjmr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1186#issuecomment-451273519.

**Comment by eeyrjmr** [comment]
Thats great, the role of a bug wrangler is never ending.
