### ISSUE TITLE
Spintires showing black screen on launch. Plays sound but doesn't crash.

### ISSUE THREAD

**Issue by TheYeetest** [ValveSoftware/Proton#2190]
**System Information**

Processor: AMD Ryzen 3 1200 Quad-Core
Graphics Card: Radeon RX 560 (Driver v.4.5.13540)
RAM: 8 GB DDR4
Operating System: Ubuntu Linux 18.04.1 LTS (64 bit)

**Comment by kisak-valve** [comment]
Hello @TheYeetest, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/777#issuecomment-451445663.
