### ISSUE TITLE
[Feature Request] Ability to select the program to execute in the application folder

### ISSUE THREAD

**Issue by Rene2LeLorrain** [ValveSoftware/Proton#2201]
# Feature Request

## I confirm:
- [X ] that I haven't found another request for this feature.
- [ ] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Add the ability to select from Steam client the name of the program to execute in the application folder, similar to selecting the game editor or the D3D level.

## Justification [optional] 
Some games requires some additional programs to be executed before the application program. These programs are not usually provided with the official bundle.

For example Bethesda games:
Morrowind:  Graphic Extender (MWGE) provide way better visuals, Script Extender (MWSE)  allows the addition of some very useful or interesting mods that many people love to have. Also it work under Wine, I prefer to use the Steam Client.

Oblivion, Fallout 3, Fallout NewVegas: Scrip Extender similar to Morrowind, but these do not work under Wine (Crash on loading, or black screen with or without sound!)

## Risks [optional]
Inability to play the Steam version of the games without these options. i.e.: I have them in my library, but I have removed them from my PC now, and use PlayOnLinux to play Morrowind!

**Comment by kisak-valve** [comment]
Hello @Rene2LeLorrain, this is a feature request for Steam rather than Proton itself and is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5766. Closing as a duplicate.
