### ISSUE TITLE
PROTON_LOG=0 %command% produces log

### ISSUE THREAD

**Issue by omicron-b** [ValveSoftware/Proton#2209]
#### Your system information

* Steam client version (build number or date): Jan 4 2019
* Distribution (e.g. Ubuntu): Arch Linux
* System info as [Gist](https://gist.github.com/omicron-b/9a0033b0bae82a4b10290d709cc8e895)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Proton version: 3.16-6 Beta

#### Please describe your issue in as much detail as possible:
Running any SteamPlay (Proton) game with `PROTON_LOG=0 %command%` produces log.
Argumentation: there are times I play games to test them, and there are times I play games just to play them. I would like to avoid deleting and pasting back `PROTON_LOG=1 %command%` launch option every time, so I just set `PROTON_LOG=0 %command%` which should disable the log.

#### Steps for reproducing this issue:

1. Install a Windows game via SteamPlay (officially whitelisted or not)
2. Set `PROTON_LOG=0 %command%` launch option
3. Start the game and quit the game.
4. Check home folder and see that log has been generated.

**Comment by doitsujin** [comment]
I'd agree that this is counter-intuitive and should probably be fixed, but if you test games regularly you might consider starting Steam as a whole with `PROTON_LOG=1` set when testing games to avoid having to modify launch options every single time.

**Comment by omicron-b** [comment]
@doitsujin thank you, never thought about running Steam like that, will do so when I need a log

**Comment by aeikum** [comment]
Hello, this should be fixed in 3.16-7. Thanks for reporting.
