### ISSUE TITLE
GTA V (271590): Unhandled exception: page fault on read access

### ISSUE THREAD

**Issue by davidjmemmett** [ValveSoftware/Proton#2211]
The game was working fine until yesterday evening. I can't recall if there was a Steam update or a GTA V update, but the game crashes on the loading screen and falls back to the Social Club with a generic error. Please find attached crash log from syslog.
[gta_crash_fromsyslog_12jan2019.log](https://github.com/ValveSoftware/Proton/files/2751971/gta_crash_fromsyslog_12jan2019.log)

**Comment by kisak-valve** [comment]
Hello @davidjmemmett, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-453743326.
