### ISSUE TITLE
Valkyria Chronicles 4 (790820)

### ISSUE THREAD

**Issue by Gryzbastian** [ValveSoftware/Proton#2212]
# Compatibility Report
- Name of the game with compatibility issues: Valkyria Chronicles 4
- Steam AppID of the game: 790820

## System Information
- GPU: GTX 970 nvidia
- Driver/LLVM version: NVIDIA 415.25
- Kernel version: 4.19.13-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/Gryzbastian/56365bf931549a2c3496fd6c70f91a48
- Proton version: 3.16-4 (tryed also 3.7-8)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-790820.log](https://github.com/ValveSoftware/Proton/files/2752046/steam-790820.log)

## Symptoms 

After launching the game i get popup saying that
"The server is not reachable, check your Internet connection and click "Retry".
In case the problem persists, click "Next" to open the support website in the default browser."
I assumed that denuvo is having trouble connecting to the internet, i am sure my internet connection is fine, problem persists even on disabled firewall. There is on problem on windows machine connected to the same router.

## Reproduction
launch the game

**Comment by kisak-valve** [comment]
Hello @Gryzbastian, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1728#issuecomment-453749170.
