### ISSUE TITLE
Koi-Koi Japan [Hanafuda playing cards] (364930)

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/Proton#2214]
# Whitelist Request
- Name of the game to be whitelisted:  Koi-Koi Japan [Hanafuda playing cards]
- Steam AppID of the game:  364930

## System Information
- GPU: NVIDIA Corporation GeForce GTX 1070/PCIe/SSE2
- Driver/LLVM version:  4.6.0 NVIDIA 415.25
- Distro version: Xubuntu 18.10
- Link to full system information report as [Gist](https://gist.github.com/):  https://gist.github.com/nightsky30/15f73ad422a5db48cf4cf13cd39cc914
- Proton version:  3.16-6 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
This game was found in the 2019-07-31 whitelist update.

If you encounter an issue with this game, please search the open issues for 364930, and report any issues encountered with this game in separate issue reports, one issue per issue report.
