### ISSUE TITLE
Kingdom Come Deliverance: Weird frame stutter after hr of play, fps is ok but.

### ISSUE THREAD

**Issue by jarrard** [ValveSoftware/Proton#2215]
# Compatibility Report
- Kingdom Come Deliverance
- 379430

## System Information
- GPU: 1080Ti
- Driver/LLVM version: 415.22.05
- Kernel version: 4.19/4.20
- Specs: https://gist.github.com/jarrard/69d7c752fae460acba60d77d189649d1
- Proton version: 3.16-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Steam log (just to main menu then back out again.)
[steam-379430.log](https://github.com/ValveSoftware/Proton/files/2754086/steam-379430.log)

## Symptoms 
After about a hour or so of game-play a weird issue occurs when looking around that causes mouse stutter, however frame-rate is otherwise fine. Game is unplayable when it does this.

## Reproduction
Play for a sufficient amount of time.

**Comment by jarrard** [comment]
If anyone else gets this issue (likely NVIDIA related) then please do comment. It seems pretty consistent with about 1-2hrs worth of play time when it happens.

**Comment by kisak-valve** [comment]
Hello @jarrard, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/692#issuecomment-454013332.

**Comment by astillich** [comment]
I have this issue, too. Each time I move the mouse, Proton loads and unloads dinput8.dll. After doing this a lot of times, something seems to slow down DLL loading (?) and cause the stutter.

`
48621.964:0024:0025:trace:module:LdrAddRefDll (L"dinput8.dll") ldr.LoadCount: 2
48621.964:0024:0025:trace:module:LdrUnloadDll (0x7f6fd19f0000)
48621.964:0024:0025:trace:module:LdrUnloadDll (L"dinput8.dll") - START
48621.964:0024:0025:trace:module:MODULE_DecRefCount (L"dinput8.dll") ldr.LoadCount: 1
48621.964:0024:0025:trace:module:LdrUnloadDll END
48621.965:0024:0025:trace:module:LdrGetDllHandle L"C:\\windows\\system32\\dinput8.dll" -> 0x7f6fd19f0000 (load path L"Z:\\home\\torque\\.steam\\steam\\steamapps\\common\\KingdomComeDeliverance\\Bin\\Win64;C:\\Program Files (x86)\\Steam;C:
\\windows\\system32;C:\\windows\\system;C:\\windows;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem")
48621.965:0024:0025:trace:module:LdrAddRefDll (L"dinput8.dll") ldr.LoadCount: 2
48621.965:0024:0025:trace:module:LdrUnloadDll (0x7f6fd19f0000)
48621.965:0024:0025:trace:module:LdrUnloadDll (L"dinput8.dll") - START
48621.965:0024:0025:trace:module:MODULE_DecRefCount (L"dinput8.dll") ldr.LoadCount: 1
48621.965:0024:0025:trace:module:LdrUnloadDll END
48621.965:0024:0025:trace:module:LdrGetDllHandle L"C:\\windows\\system32\\dinput8.dll" -> 0x7f6fd19f0000 (load path L"Z:\\home\\torque\\.steam\\steam\\steamapps\\common\\KingdomComeDeliverance\\Bin\\Win64;C:\\Program Files (x86)\\Steam;C:\\windows\\system32;C:\\windows\\system;C:\\windows;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem")
48621.965:0024:0025:trace:module:LdrAddRefDll (L"dinput8.dll") ldr.LoadCount: 2
48621.965:0024:0025:trace:module:LdrUnloadDll (0x7f6fd19f0000)
48621.965:0024:0025:trace:module:LdrUnloadDll (L"dinput8.dll") - START
`

**Comment by jarrard** [comment]
I'm not even sure if this is still a issue, been a long time since I played this game.
