### ISSUE TITLE
Feature Request + Modding Report: The Elder Scrolls V: Skyrim Special Edition (489830)

### ISSUE THREAD

**Issue by 8BitCerberus** [ValveSoftware/Proton#2216]
# Feature Request

Integrate patch found here: https://github.com/hdmap/wine-hackery/tree/master/f4se They were originally done for Fallout 4/F4SE but also works for SKSE64.

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

Non-SKSE64 mods are working. You can either manually drop them in the Data folder and edit your loadorder.txt and plugins.txt files, or you can install a mod manager (I'm using Nexus' Vortex currently) via Wine or Proton. I have played a few hours now with several mods, both plugins and loose files/texture and audio replacers.

SKSE64 however does not work. It silently fails and just goes on to load Skyrim without hooking in. I've been doing some digging and it's a difference in how it loads into memory compared to SKSE for Skyrim Legendary Edition (72850). There are patches for Wine that address the same issue with F4SE for Fallout 4, and because SKSE64 works in the same way this fixes the problem.

## Justification [optional] 

This would open up Skyrim SE and Fallout 4 modding without needing to jump through hoops or compile their own versions of Proton and/or Wine. They still would need to get a mod manager working on their own if they want to use one, but having SKSE64 or F4SE working without hassle would eliminate a major roadblock.

Combined with the FAudio patches which seem to be already being worked on, this could help make both Skyrim Special Edition and Fallout 4 candidates for whitelisting.

## Risks [optional]

None known.

## References [optional] 

https://github.com/ValveSoftware/Proton/issues/308

**Comment by kisak-valve** [comment]
Hello @8BitCerberus, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/170#issuecomment-454015565.

**Comment by 8BitCerberus** [comment]
Ahh, ok. I saw that report but I figured since that was for the original Skyrim, not Special Edition, and a different version of SKSE that it wasn't related. Sorry about that!
