### ISSUE TITLE
Project Cars 2 photo mode not working

### ISSUE THREAD

**Issue by wleoncio** [ValveSoftware/Proton#2217]
# Compatibility Report
- Name of the game with compatibility issues: Project Cars 2
- Steam AppID of the game: 378860

## System Information
- GPU: Nvidia GTX 650 Ti Boost
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.15.0-43-generic
- Proton version: 3.16-6 Beta
- System information gist: https://gist.github.com/wleoncio/39f777969041c7ee5cb2075e2294d683

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Proton log gist: https://gist.github.com/wleoncio/41ad3c33d0459d54a95cbe312028ecbe

## Symptoms

Photo mode does not work

## Reproduction

1. Start the game and get on track (game mode doesn't matter)
2. Pause the game and choose "photo mode"
3. Try to take a photo by pressing "take photo" or pressing the left mouse button

(alternatively)
1. Start the game and go to "private testing", then "vehicle select"
2. Choose "Showroom" and "Photo mode"
3. Try to take a photo by pressing "take photo" or pressing the left mouse button

Instead of taking the photo, the game temporarily freezes, with the shutter sound repeating indefinitely. Pressing "Esc" goes back to "photo mode" and game can be played normally. Photo is not taken, as it won't show up in "My Profile / Images" and the "Snap snap snap" achievement for taking a photo doesn't pop up.
[steam-378860.log](https://github.com/ValveSoftware/Proton/files/2756122/steam-378860.log)

**Comment by wleoncio** [comment]
I've also tried with nvidia driver 415.25 and game version 1.7.1 (OP using 1.7.0) with same results.

**Comment by kisak-valve** [comment]
Hello @wleoncio, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/908#issuecomment-454092997.
