### ISSUE TITLE
Increase the open files limits values to prevent games craches?

### ISSUE THREAD

**Issue by julienbenjamin** [ValveSoftware/Proton#2218]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description

Since some games require a number of files open per process higher than the default values, it would be a good idea to have it increased without having to troubleshoot and modify it yourself.

Default values can be found with the following commands in a terminal:
>ulimit -Sn # soft limit; can be raised up to the hard limit
>ulimit -Hn # hard limit

By default, these values are respectively 1024 and 4096.

For certain games, it results in a bug that you can find in the standard output or the log(s):
> eventfd: Too many open files

## Justification

The modifications of the defaults limits values is necessary to play some games or it results in a crash of the game.

## Risks

If set values are too high, could lower the security against fork bombs.

**Comment by kisak-valve** [comment]
Same as https://github.com/ValveSoftware/steam-for-linux/issues/6021#issuecomment-454089704.
