### ISSUE TITLE
Stickfight Sayas it's running on Ubuntu Bionic beaver but there's no screen, Just a zombie process

### ISSUE THREAD

**Issue by thepetercasey** [ValveSoftware/Proton#2219]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Closing as there is no actionable information. Possible workarounds at #537.
