### ISSUE TITLE
Killer Instinct

### ISSUE THREAD

**Issue by massatt212** [ValveSoftware/Proton#2222]
Game Runs very well could be Whitelisted but their is no Online Gameplay
[steam-577940.log](https://github.com/ValveSoftware/Proton/files/2764433/steam-577940.log)

Is it possible to fix the Online Feature in this game ?

**Comment by nded03** [comment]
You say the only problem you have is lack of online? Last time I tried this game there were severe rendering issues at the character select screen in addition to connectivity issues.

**Comment by kisak-valve** [comment]
Hello @massatt212, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/348#issuecomment-454792367.
