### ISSUE TITLE
gta-sa.exe running in the background but there is no display

### ISSUE THREAD

**Issue by sourcyed** [ValveSoftware/Proton#2225]
# Compatibility Report
- Name of the game with compatibility issues: GTA: San Andreas
- Steam AppID of the game: 12120

## System Information
- GPU: GTX 720M
- Driver/LLVM version: nvidia 340.107
- Kernel version: 4.18
- Link to full system information report as [Gist](https://gist.github.com/YEDrekt/58f4fa817718f7c04708a91c774b88ae:
- Proton version: 3.7-8

## I confirm:
- [✔] that I haven't found an existing compatibility report for this game.
- [✔] that I have checked whether there are updates for my system available.

[steam-12120.log](https://github.com/ValveSoftware/Proton/files/2769611/steam-12120.log)

## Symptoms 
When I try to launch Grand Theft Auto: San Andreas, the process (gta-sa.exe) starts, Steam says the game is running but I don't see any screen or any display. There is just a running background process named gta-sa.exe
The same problem occurs with GTA: Vice City as well.

## Reproduction
It happens everytime I try to launch the application.

**Comment by kisak-valve** [comment]
Hello @YEDrekt, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/143#issuecomment-455250400.
