### ISSUE TITLE
Consider Adding "Run EXE in this prefix"

### ISSUE THREAD

**Issue by 7oxicshadow** [ValveSoftware/Proton#2227]
Certain games require additional installs in order for them to to work.

As an example, SONIC THE HEDGEHOG 4 - EPISODE I requires the java runtime installing in order to work.

In a normal wine install this can be downloaded from the internet and installed manually to allow the game to work correctly. 

In proton there is no way to run the executable from an external location. I tried replacing the game exe with the java exe just to get it to launch. Sadly the game tires to pass some parameters that the java exe does not recognise and it halts.

**Comment by kisak-valve** [comment]
Hello @7oxicshadow, this is a feature request for the Steam client rather than Proton itself, and is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5766. Closing as a duplicate.
