### ISSUE TITLE
RE2 1-shot demo Non-Stop Shooting / Judder / Drop Frames Suddenly / Strange Texture (961440)

### ISSUE THREAD

**Issue by laichiaheng** [ValveSoftware/Proton#2236]
# Compatibility Report
- Name of the game with compatibility issues: RESIDENT EVIL 2 / BIOHAZARD RE:2 "1-Shot Demo"
- Steam AppID of the game: 961440

## System Information
- GPU: <RX 580>
- Driver/LLVM version: <Mesa 19.0.0-devel (git-6ca652f 2019-01-19 bionic-oibaf-ppa)/LLVM 7.0.1>
- Kernel version: <4.20.3>
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 3.16-6-BETA with the DXVK0.95 dlls

## I confirm:
- [V] that I haven't found an existing compatibility report for this game.
- [V] that I have checked whether there are updates for my system available.

[steam-961440.log](https://github.com/ValveSoftware/Proton/files/2775338/steam-961440.log)

## Symptoms 
1. non-stop shooting
2. judder
3. drop frames suddenly
4. strange texture

## Reproduction
1. non-stop shooting: I don't know, it happens a lot if I have shot many bullets, when I aim the target, it keeps shooting.
2. judder: walk around.
3. drop frames suddenly: Sometimes I shoot or walk around or into an animation.
4. strange texture:
There is a setting which is called Screen Space Reflection
![2019-01-19 15-49-37](https://user-images.githubusercontent.com/9532105/51424108-6dda9800-1c04-11e9-9c69-549274d2cfdf.png)
If I enable Screen Space Reflection, the pillar looks like this:
![2019-01-19 15-49-02](https://user-images.githubusercontent.com/9532105/51424102-51d6f680-1c04-11e9-8a69-c8cdd3fe920c.png)
If I disable it, it looks normal:
![2019-01-19 15-49-44](https://user-images.githubusercontent.com/9532105/51424105-5dc2b880-1c04-11e9-9599-87aea37df7ed.png)

**Comment by kisak-valve** [comment]
Hello @laichiaheng, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2210#issuecomment-455782483.
