### ISSUE TITLE
Dark Souls 3 (374320) instantly crashes, can't generate logs

### ISSUE THREAD

**Issue by tonijarjour** [ValveSoftware/Proton#2248]
# Compatibility Report
- Name of the game with compatibility issues: Dark Souls 3
- Steam AppID of the game: 374320

## System Information
- GPU: GTX 970
- Driver/LLVM version: Mesa 18.3.1-1
- Kernel version: 4.20.3-arch1-1-ARCH
- Proton version: 3.16-6 BETA

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

The game is instantly crashing when I try to run it.
Generating logs does not work. I've added PROTON_LOG=1 %command% to the launch options of Dark Souls 3 and there is no log file in my home directory nor anywhere else on my system. 
[Steam output of crash](https://gist.github.com/tonijarjour/69a1d11eb83cfacd9420979ddce2a5a8)

## Reproduction

1. Install Arch Linux
2. Install mesa lib32-mesa xf86-video-nouveau xorg-server steam lib32-libglvnd awesome
3. In awesomewm (I also tried in XFCE) run steam and install Dark Souls 3
4. Run Dark Souls 3

## Fixed
Steam requires Python 3 to run games through Proton. Install Python 3.

**Comment by tonijarjour** [comment]
If I run `PROTON_LOG=1 steam steam://rungameid/374320` in the terminal, it gives this:
`/home/toni/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable`
`/home/toni/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable`
`Running Steam on arch  64-bit`
`/home/toni/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable`
`STEAM_RUNTIME is enabled automatically`
`Pins up-to-date!`
`ERROR: ld.so: object '/usr/$LIB/libgpg-error.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

**Comment by kisak-valve** [comment]
Hello @tonijarjour, not particularly clear why no log is generated, but dxvk needs a vulkan capable driver, which nouveau currently is not. Please retest with nvidia 415.22 or newer.

**Comment by tonijarjour** [comment]
Ya I've tested with both nvidia and nouveau and neither work.

For nvidia I installed nvidia and lib32-nvidia-utils packages.

**Comment by tonijarjour** [comment]
[Output when running](https://gist.github.com/tonijarjour/69a1d11eb83cfacd9420979ddce2a5a8)

Based off this I will install Python and try again.
Ok installing Python fixed it. WOW
