### ISSUE TITLE
Subnautica - Game does not start executable file

### ISSUE THREAD

**Issue by Darwin-II** [ValveSoftware/Proton#2256]
After installing Subnautica and attempting to run it I have ran into a problem - the game does not run. There are entries for Wine in my task manager when I run Subnautica but the game itself lacks an entry. I have validated game files multiple times and attempted to use fixes related to poor performance for native Windows installations of the game, but to no avail. Interestingly I have clocked 56 minutes of gameplay despite the game's executable never running. Even after letting my computer sit and attempt to run the game for 15 minutes with no other non-background tasks there was no evidence of the game running, again, a lack of an executable entry on my task manager.

I am running Ubuntu 18.10 on a Dell Inspiron 15 3000 with a 2.6 GHz dual core CPU and 4 GB of RAM, using Intel UHD 600 graphics, all above the minimum specifications. Using Steam Play with other games has never been an issue, and running software outside of Steam through Wine has never failed me either.

**Comment by kisak-valve** [comment]
Hello @Darwin-II, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/79#issuecomment-456209666.
