### ISSUE TITLE
PROTON_LOG=1 doesn't work for non-steam games

### ISSUE THREAD

**Issue by FictionX** [ValveSoftware/Proton#2259]
Using the "PROTON_LOG=1 %command%" launch option doesn't work for non-steam games. No log is generated.

I tested with a couple of non-steam games, and a few steam games as well to verify that it works with those (and it does). 

Activating user_settings.py doesn't work either.

Apparently the log is only generated if the game has a STEAM_ID (which is used as part of the logfile name) - which of course non-steam games doesn't have.

**Comment by kisak-valve** [comment]
Hello @FictionX, this is an issue with the Steam client rather than Proton itself, and is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/6046. Closing as a duplicate.

**Comment by Danny3** [comment]
> Hello [@FictionX](https://github.com/FictionX), this is an issue with the Steam client rather than Proton itself, and is being tracked at [ValveSoftware/steam-for-linux#6046](https://github.com/ValveSoftware/steam-for-linux/issues/6046). Closing as a duplicate.

What has the Steam client have to do with someone just running Proton from the command line with a non-Steam game?
I tested myself with a script preparing environment variables and then calling proton, on a game and Proton doesn't write anything to any folder.
Why should we be forced to use the proprietary Steam client for any game, even if the game doesn't belong to Steam or Steam is just not installed on our systems?

**Comment by Danny3** [comment]
and that issue is also closed, while the problem still exists!
