### ISSUE TITLE
Witcher 3 performance regression with 3.16-6

### ISSUE THREAD

**Issue by sirkon** [ValveSoftware/Proton#2262]
There's noticeably performance regression in Witcher 3 at least in Toussaint: looking around with mouse doesn't smooth anymore although it was with before Proton 3.16 (didn't try with older Protons 3.16-X)

System info: https://gist.github.com/sirkon/601db826009f1fb02ac48ac0c5e87c6e

**Comment by kisak-valve** [comment]
Hello @sirkon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-457196424.
