### ISSUE TITLE
Subnautica Has No Window

### ISSUE THREAD

**Issue by Darwin-II** [ValveSoftware/Proton#2264]
When I run Subnautica, similar to my previous Subnautica related issue there is no game window. At least now the game has an executable entry in my task manager, but there is no associated window. How can I resolve this?

I am running Ubuntu 18.10 on a Dell Inspiron 15 3000 with a 2.6GHz Dual Core CPU and Intel UHD 600 graphics with 4GB of RAM with 12GB of swap space. I am using Proton 3.16 Beta.

**Comment by kisak-valve** [comment]
Hello @Darwin-II, we're still using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/79#issuecomment-457356071.
