### ISSUE TITLE
Subnautica, Despite Running The Executable, Has No Window

### ISSUE THREAD

**Issue by Darwin-II** [ValveSoftware/Proton#2265]
When I run Subnautica, similar to my previous Subnautica related issue there is no game window. At least now the game has an executable entry in my task manager, but there is no associated window. How can I resolve this?

I am running Ubuntu 18.10 on a Dell Inspiron 15 3000 with a 2.6GHz Dual Core CPU and Intel UHD 600 graphics with 4GB of RAM with 12GB of swap space. I am using Proton 3.16 Beta.

I am displeased with the responses I have been receiving for my issues. I should not have to file error reports for a paid game only to have them forwarded to the main thread. It is very unhelpful and appears quite lazy. Could I please receive some help **ON THIS THREAD** or at least be forwarded to somewhere that could better help me, not just the game's main thread? Your system of one issue report per unsupported title is no doubts unhelpful to a great many people.

**Comment by kisak-valve** [comment]
@Darwin-II, feel free to continue looking for help with this game on #79. However, for repeatedly opening duplicate issue reports you've earned yourself a 24 hour timeout. Continuing to do so will not go well.
