### ISSUE TITLE
Upgrade DXVK version

### ISSUE THREAD

**Issue by laichiaheng** [ValveSoftware/Proton#2267]
# Feature Request
Please upgrade DXVK to 0.95 for the bug fixes.

## Description 
upgrade DXVK
## Justification [optional] 
It is easier than WINE
## Risks [optional]
None
## References [optional] 
#2210

**Comment by kisak-valve** [comment]
Hello @laichiaheng, Proton devs will update subcomponents at their discretion. Making this request will not change when this happens.
