### ISSUE TITLE
Huge download size for update

### ISSUE THREAD

**Issue by D-357** [ValveSoftware/Proton#2277]
I usually only get one game updated, which I think is strange because I thought all games received different updates respectively from wine/proton (how ever it works). Anyway the size of this download is just odd to me.
![screenshot from 2019-01-27 21-48-33](https://user-images.githubusercontent.com/5043786/51816972-be459b80-227d-11e9-8f6d-0e0cddd19860.png)

**Comment by kisak-valve** [comment]
Hello @D-357, game updates are handled by the Steam client, not Proton itself. You are most likely using the Steam client beta and encountered https://github.com/ValveSoftware/steam-for-linux/issues/5901 as a side effect of "Fixed an issue with invalid Steam Play tool selections if user had previously opted in to enable Steam Play for all titles. (Note: this will cause a one-time reset of all Steam Play global and per-app selections to the default state)." in the [2019-01-18](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1703951108833155107) Steam client beta update.

Closing as out-of-scope for this issue tracker.
