### ISSUE TITLE
Merge with battleye patches that are being worked on in a separate repo

### ISSUE THREAD

**Issue by redpiller** [ValveSoftware/Proton#2278]
# Feature Request
https://github.com/Guy1524/wine/commits/battleye-work-stable
this repo contains wine patches that enables the use of battleye anticheat in games like
Arma2, Arma3, Fortnite, Planetside 2 ... and so on...
take a look, maybe you could establish a cross repo patching pipeline 

## I confirm:
- [ x ] that I haven't found another request for this feature.
- [ x ] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Battleye support

## Justification [optional] 
Battleye is broken in proton

## Risks [optional]
Not every game will be supported at first

## References [optional] 
https://github.com/Guy1524/wine/commits/battleye-work-stable

**Comment by kisak-valve** [comment]
Hello @redpiller, I don't see any value in having this split for the existing battleye discussion at #30, so I've transferred this request to https://github.com/ValveSoftware/Proton/issues/30#issuecomment-458237261.
