### ISSUE TITLE
esync patchset requires system configuration

### ISSUE THREAD

**Issue by libcg** [ValveSoftware/Proton#228]
Following [these steps](https://github.com/zfigura/wine/blob/esync/README.esync) can be a huge barrier for new users and will also create bugs for users unaware of it. This needs to be addressed.

**Comment by jaccarmac** [comment]
Can you elaborate? What issues does adding the line in the linked file cause? Beyond determining whether or not one is running a systemd system, what part of the configuration is particularly confusing?

**Comment by Mushoz** [comment]
Users unaware that these settings need to be changed might be running with values with a too low file descriptor limit. These users will experience crashes and might attribute these crashes to the game/Proton, while in fact their system is improperly configured.

**Comment by jaccarmac** [comment]
I understand that much, but the feature is only available in the beta client at the moment and the steps to fix the problem are pretty clearly documented here. Was wondering if there was more to the esync change, clearly onboarding should become easier over time :)

**Comment by Mushoz** [comment]
I think @libcg simply meant this as feedback for the current beta which needs to be addressed before it can be released to the mainstream, which I agree with.

**Comment by SwooshyCueb** [comment]
As of September 13, Proton and Steam Play are in the standard, non-beta client. It is my understanding that all versions of Proton, beta or not, had the esync patchset. Is this not the case?

**Comment by Snuggle** [comment]
I've seen multiple people get confused by the ordering of the [esync documentation linked above](https://github.com/zfigura/wine/blob/esync/README.esync). They literally look for the first fix, for _non-systemd systems_, and wonder why it's not working.

This would be awesome to do automagically.
