### ISSUE TITLE
The Ship - "unable to load authentication library" (2400)

### ISSUE THREAD

**Issue by benbrockn** [ValveSoftware/Proton#2297]
# Compatibility Report
- Name of the game with compatibility issues: **The Ship**
- Steam AppID of the game: **2400**

## System Information
- GPU:  **GTX-1080**
- Driver/LLVM version:  **Nvidia 410.78**
- Kernel version:  **4.19.11-041911-generic** 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/benbrockn/cb4e2d40da111262bc9e479b88592b70#file-steam-system-info
- Proton version:  **3.16-4 & 3.16-6 Beta**

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

https://gist.github.com/benbrockn/b03988d827277e8598803ef04b0b95d3#file-the-ship-proton-3-16-4-log

## Symptoms <!-- What's the problem?

The Ship Singleplayer (different version of this game) works flawlessly, but the original version (multiplayer) errors out. The game loads fine, all menus are navigable, and the game seems fine. The error happens when you start any new game session, the game is loading textures and such with a progress bar, and as soon as it hits 100% and attempts to start a new session, it errors out and crashes. The exact error is:  "unable to load authentication library".

I created this thread first (https://steamcommunity.com/app/221410/discussions/8/1778261844035379808/) and users suggested either using the latest Proton beta (for me, that's 3.16-6 Beta) and I did that but it still gives me this error. I also tried this with using the latest Steam client Beta (Build Jan 31 2019 @ 23:11:14), but it also didn't work (as it seems to be a Proton/Wine issue).

## Reproduction

<me>:~$ neofetch
            .-/+oossssoo+/-.               <me> 
        `:+ssssssssssssssssss+:`           ------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: MS-7C02 1.0 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.19.11-041911-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 19 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2230 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.19 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 2560x1440 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Xfce 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Xfwm4 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Greybird 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Greybird [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Elementary-xfce-darker [GTK2/ 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: xfce4-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      Terminal Font: Monospace 12 
    .ossssssssssssssssssdMMMNysssso.       CPU: AMD Ryzen 7 2700 (16) @ 3.877GH 
      -+sssssssssssssssssyyyssss+-         GPU: NVIDIA GeForce GTX 1080 
        `:+ssssssssssssssssss+:`           Memory: 1527MiB / 32115MiB 
            .-/+oossssoo+/-.

**Comment by kisak-valve** [comment]
`err:steamclient:create_win_interface Don't recognize interface name: SteamClient006` in the log looks like a line of interest.

**Comment by aeikum** [comment]
Support for SteamClient006 was added in 3.16-7. Please retest.

**Comment by benbrockn** [comment]
Recommend close. Works as of Proton 4.2-5, played for several hours the other day.
