### ISSUE TITLE
Cogmind installs the VC redistributable package on every install. (722730)

### ISSUE THREAD

**Issue by jaccarmac** [ValveSoftware/Proton#230]
This one-time setup seemed to only happen once for Dungeon of the Endless, the other Steam Play game I've experimented with so far. This happens across Steam restarts and also within a single session. A download shows up for Cogmind though it is 0 bytes/0 bytes as reported by Steam.

**Comment by kisak-valve** [comment]
Hello @jaccarmac, we'll be keeping one issue report open per unofficially supported game title, so I'm merging this into #226.
