### ISSUE TITLE
Wolfenstein: The Old Blood ending cutscene does not play (350080)

### ISSUE THREAD

**Issue by sat3ll** [ValveSoftware/Proton#2306]
# Compatibility Report
- Name of the game with compatibility issues: Wolfenstein: The Old Blood
- Steam AppID of the game: 350080

## System Information
- GPU: AMD Fury X
- Driver/LLVM version: Mesa 18.3.1, LLVM 7.0.1
- Kernel version: 4.20.3-200.fc29.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/sat3ll/609e92e00f6a2a8669e512054661b334
- Proton version: 3.7-8, 3.16-4

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Log unavailable, game finished.

## Symptoms 

After defeating the last boss, interacting with the folder that plays the ending cutscene leads to a black screen but game can be paused and resumed by pressing ESC (game is not frozen, the cutscene simply does not play). This breaks finishing the game and achievements for finishing at a certain difficulty do not kick in.
Switching from official Valve selection of *Proton* `3.7-8` to `3.16-4` fixes this (allows cutscene to play) and grants achievements for finishing the game.

## Reproduction
Simply play the ending/game (no special steps).

**Comment by kisak-valve** [comment]
The whitelist entry for this game has been updated to Proton 3.16 (non-beta).
