### ISSUE TITLE
Age of Mythology crashes upon start with error message "Initialization Failed Direct3D initialization failed. Frequent cause is an old or corrupted driver." 

### ISSUE THREAD

**Issue by TheAnimatedFreak** [ValveSoftware/Proton#2310]
Age of Mythology crashes after starting up using proton 3.7-8. Gives error "Initialization Failed Direct3D initialization failed. Frequent cause is an old or corrupted driver." 
I have a AMD card so I upgraded it using the oibaf repository at ppa:oibaf/graphics-drivers to get the  vulkan stuff working. I installed  libvulkan1, mesa-vulkan-drivers and vulkan-utils but it didn't help
I tried different Environment Variable options in the launch option such as` PROTON_USE_WINED3D`
but it didn't help.

I also tried different version of proton such as 3.7-8 beta, 3.16-4 and 3.16-6 beta but none of these even start the game up. 

I generated this log file using `PROTON_LOG`
[steam-266840.log](https://github.com/ValveSoftware/Proton/files/2828504/steam-266840.log)
But I don't know what to read from it. I also have the log file that the game itself generated 
[startup.txt](https://github.com/ValveSoftware/Proton/files/2828512/startup.txt)
According to it, it seems to have problem rendering things. It falls back to use  D3D11 mode but it fails to use that too. 

At this point I've tried everything, I've read others threads on here but nothing seems to be working. According to protondb.com others have gotten this game working with the same version of proton and even similar hardware. But no such luck for me.

My specs
OS: Kubuntu 18.10
CPU: AMD Ryzen 5
GPU: AMD Radeon RX 570
RAM: 16GB

If there is anything missing in the issue I'll gladly provide it. 
Cheers

**Comment by kisak-valve** [comment]
Hello @TheAnimatedFreak, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1547#issuecomment-460282545.
