### ISSUE TITLE
[RE2] Savegame import not possible because of region mismatch

### ISSUE THREAD

**Issue by Mershl** [ValveSoftware/Proton#2313]
# Compatibility Report
- Name of the game with compatibility issues: RESIDENT EVIL 2
- Steam AppID of the game: 883710

## System Information
- GPU: GTX 1080
- Driver/LLVM version: nvidia 415.27
- Kernel version: 4.19
- Proton version: 3.16-6

## I confirm:
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Resident Evil 2 saves contain the regional settings they were created in. At startup it performs a region check (reading sCountry, Locale and sLanguage from registry, eventually more) and marks the saves invalid if the regions do not match.
Setting the regional settings in the Windows Region&Language panel to match the ones used to create the savegame solves this issue.
Editing the wine prefix managed by Proton for RE2 does not solve this issue as the fields are (automatically) reset to "United States"/"ENU"/"409" after the edit.

## Reproduction
- Enable Steam cloud saves for RE2 on a Windows machine with a region setting **different than** United States. Start game and save.
- Install RE2 via SteamPlay. First dialog ingame should mention "This save data is not compatible and cannot be used".

**Comment by kisak-valve** [comment]
Hello @Mershl, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2266#issuecomment-460790101.
