### ISSUE TITLE
Transparent surfaces render as opaque in The Witness (210970)

### ISSUE THREAD

**Issue by rileyinman** [ValveSoftware/Proton#2314]
# Compatibility Report
- Name of the game with compatibility issues: The Witness
- Steam AppID of the game: 210970

## System Information
- GPU: Intel UHD 620
- Driver/LLVM version: Mesa 18.3.3
- Kernel version: 4.20
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/rileyinman/75fe5af884cc4823cae3fe3d9387e94d
- Proton version: 3.7-8

## I confirm:
- [X] that I haven't found an existing compatibility report for this game. (A comment in #1701 mentions rendering bugs but they seem separate from this, or at the very least I'm unaffected by them.)
- [X] that I have checked whether there are updates for my system available.

[steam-210970.log](https://github.com/ValveSoftware/Proton/files/2834115/steam-210970.log)

## Symptoms
In certain areas of the game specifically (spoilers) the greenhouse by the foot of the mountain. Several puzzles in this area depend on translucent glass of different colors that filter groupings of dots for panels on the other side. When loading up this area in Proton, the "glass" is instead completely opaque and simply looks like a blackout window.

## Reproduction
Launch The Witness via Steam with the autoselected version of Proton and navigate to the building circled on [this map](https://user-images.githubusercontent.com/37246692/52308553-9b954000-296b-11e9-8f9a-e8c0e0d84373.png). Inside, the glass should be transparent but in my case is not. Launching with Proton 3.16 makes the glass transparent but breaks controls and the rendering of most polygonal textures in the game, so it's not really viable as a solution.

**Comment by kisak-valve** [comment]
Hello @rileyinman, if possible, please retest with Proton 3.16 and mesa 19.0.0-rc2.

**Comment by rileyinman** [comment]
With Proton 3.16 and mesa 19.0 the surfaces render as transparent and controls work fine, but the issue with polygons still remains and the game takes a decent performance hit.

**Comment by rileyinman** [comment]
I should probably mention that the transparency only rendered once I added PROTON_USE_WINED3D=1 to the launch options in this setup. I tried going back to 3.7 with mesa 19.0 to see if it would do anything there, but it seemed to work the same as without it.

**Comment by Leopard1907** [comment]
Please try with Proton 3.16-7 Beta.

https://github.com/doitsujin/dxvk/issues/724

@kisak-valve

Would be good to bump up either Witness Proton version or DXVK version on 3.7 base.

**Comment by rileyinman** [comment]
@Leopard1907 attempting to launch with 3.16-7 causes it to close out immediately. I tried adding PROTON_LOG=1 to the launch options but it didn't generate anything.

**Comment by Leopard1907** [comment]
Do you have Proton 3.16 listed at tools section on Steam and is it listed as installed?

**Comment by rileyinman** [comment]
Strangely enough, all versions of Proton were listed as not installed under the tools menu. I installed 3.16-7 manually and launched the game, it seems to be functionally identical to 3.16-4 as far as I can tell (i.e. working transparency but broken rendering of most everything else).

**Comment by awr1** [comment]
Can confirm this still happens on 3.7-8. You can also observe the bug in the particles from the secret puzzles, [like this one from the beginning of the game.](https://www.youtube.com/watch?v=ShBGn2ZM1LQ)

GPU: Intel HD Graphics 520 (Skylake GT2)
Mesa: 18.3.4
Kernel: 5.0.2

**Comment by rileyinman** [comment]
Fixed in 4.11-6! This could probably be the new "Valve selected" version of Proton for The Witness, it has neither of the issues with the previous ones :) I'll leave open for a bit in case anyone else still has the problem though.

**Comment by FreeFull** [comment]
I still run into this issue with 4.11-11

**Comment by kisak-valve** [comment]
Hello, this game has been bumped to Proton 4.11 in the 2020-03-10 whitelist update.
