### ISSUE TITLE
Valkyria Chronicles FPS Performance issues

### ISSUE THREAD

**Issue by yokiraamato** [ValveSoftware/Proton#2315]
# Compatibility Report
- Name of the game with compatibility issues: Valkyria Chronicles 4
- Steam AppID of the game: 790820

## System Information
Arch Linux:
- GPU: GTX 960m
- CPU: AMD FX-8320E Eight-Core @ 8x 3.2GHz
- RAM : 8GB
- Driver/LLVM version: nvidia 415.27-4
- Kernel version: 4.20
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: * 3.7-8

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
in main menu it runs smoothly no problems at all but when it starts the match ingame it starts a terrible fps drop like 10-20 fps while on windows i have like 60 fps no problem

## Reproduction
Launch the game in steam with proton 3.7-8, press load game / new game wait until the actual game start (no dialogues) then it starts the terrible fps drop

**Comment by kisak-valve** [comment]
Hello @yokiraamato, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1728#issuecomment-460854857.
