### ISSUE TITLE
Steam Play - All Games Settings not preserved, games uninstalled

### ISSUE THREAD

**Issue by mebesoco** [ValveSoftware/Proton#2317]
After the most recent steam client update for the ubuntu 18.04 client my option to enable steam play for all games was unchecked and a game I had installed and had been playing was uninstalled. I'll grab my system information later today when I'm on that machine again and add a link to a gist with that information.

**Comment by kisak-valve** [comment]
Hello @mebesoco, looks like you encountered https://github.com/ValveSoftware/steam-for-linux/issues/5901 as a side effect of "Fixed an issue with invalid Steam Play tool selections if user had previously opted in to enable Steam Play for all titles. (Note: this will cause a one-time reset of all Steam Play global and per-app selections to the default state)." from the  [2019-01-18](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1703951108833155107) Steam client beta update, which went into the stable client release.

Closing in favor of the existing report.
