### ISSUE TITLE
PC Building Simulator is stuck on initial screen

### ISSUE THREAD

**Issue by rdlf4** [ValveSoftware/Proton#2326]
# Compatibility Report
- Name of the game with compatibility issues: PC Building Simulator. 
- Steam AppID of the game: 621060

## System Information
- GPU: AMD Radeon RX540 (Mobile dedicated Polaris 12 GPU)
- Driver/LLVM version: Mesa 18.3.3 (Padoka PPA) / LLVM 7.0.0
- Kernel version: 4.15.0-45-generic
- Proton version: 3.16-6 Beta

## I confirm:
- [OK] that I have checked whether there are updates for my system available.

## Symptoms:
Once the game is launched, I can see the logo of the game with a red exclamation point on the top left corner***. After that the game thinks some more and then it gets stuck on this screen:
![20190209193316_1](https://user-images.githubusercontent.com/17544190/52527088-a15b9000-2ca1-11e9-9b86-e2c79f3e43dd.jpg)
Music plays, but that's it. The game won't do anything after this point.
I tried clicking everywhere, Pressing Tab, Enter, space, you name it. Nothing happens after this screen is displayed.

*** = that popup with the exclamation point shows up only for the first time the game is launched. After that, Steam launcher jumps straight to the screen above.
Proton Log file is attached:
[steam-621060.log](https://github.com/ValveSoftware/Proton/files/2848333/steam-621060.log)

Mods, please note: I did my research about existing topics for this game, but the only one there is on Github/SteamPlay is the one that reports a problem _*when quitting*_ the game.
This topic aims at addressing the issue there is after starting it.

Anyone else with the same issues?

**Comment by kisak-valve** [comment]
Hello @rdlf4, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1919#issuecomment-462086414.
