### ISSUE TITLE
Endless Legend (289130)

### ISSUE THREAD

**Issue by tharbad08** [ValveSoftware/Proton#2327]
# Compatibility Report
- Name of the game with compatibility issues: Endless Legend
- Steam AppID of the game: 289130

## System Information
- GPU: GTX 670
- Driver/LLVM version: nvidia 415.27
- Kernel version: 4.20.7
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/shaygover/6582ae4b9c6289d99c2353d61bda8c1c
- Proton version: 3.16-6 beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
Seen that: https://github.com/ValveSoftware/Proton/issues/2014 Not the same issue
- [x] that I have checked whether there are updates for my system available.

[Uploading steam-289130.log…]()

## Symptoms 
Black screen on startup. I can hear the nvidia (I think) slogan and then the game crashes.

## Reproduction
Start the game.

**Comment by kisak-valve** [comment]
Hello @shaygover, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/619#issuecomment-462132463.
