### ISSUE TITLE
HITMAN 2 launcher crash with Proton 3.16-6

### ISSUE THREAD

**Issue by hardware** [ValveSoftware/Proton#2328]
# Compatibility Report
- Name of the game with compatibility issues: HITMAN 2
- Steam AppID of the game: 863550

## System Information
- GPU: RTX2080
- Driver/LLVM version: 415.27
- Kernel version: 4.20.7
- Link to full system information report : [Gist](https://gist.github.com/hardware/1804094a380ee1354de681c2e770cf6a)
- Proton version: 3.16-6

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms

With Proton **3.16-6 beta**, the game launcher does not launch at all. 

No log files are generated under `$HOME/steam-$APPID.log` in that case.

If I use Proton 3.16-4, I can launch the game but online mode does not work.
If I use Proton 3.7-8, I can launch the game and online connectivity work out of the box.

## Reproduction

1. Switch Proton to 3.16-6
2. Launch the game
3. Game Launcher crash

Do you have an idea to find some logs about this issue ?

**user_settings.py :**

```python

user_settings = { 
    # logs are saved to $HOME/steam-$STEAM_APP_ID.log, overwriting any previous log with that name
    "WINEDEBUG": "+timestamp,+pid,+tid,+seh,+debugstr,+module",

    "DXVK_LOG_LEVEL": "info",

    # Enable DXVK's HUD
    "DXVK_HUD": "fps,devinfo,frametimes,memory,version"

    # Use gl-based wined3d for d3d11 and d3d10 instead of vulkan-based dxvk
    # "PROTON_USE_WINED3D": "1",

    # Disable d3d11 entirely
    # "PROTON_NO_D3D11": "1",

    # Disable in-process synchronization primitives
    # "PROTON_NO_ESYNC": "1",
}
```

**Game's launch options :**

```
PROTON_LOG=1 %command%
```

**Comment by kisak-valve** [comment]
Hello @hardware, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2121#issuecomment-462138014.
