### ISSUE TITLE
[Whitelist] DX-Ball 2: 20th Anniversary Edition (922400)

### ISSUE THREAD

**Issue by veikk0** [ValveSoftware/Proton#2334]
# Whitelist Request
- Name of the game to be whitelisted: DX-Ball 2: 20th Anniversary Edition
- Steam AppID of the game: 922400

## System Information: Desktop
- GPU: RX 470 4GB
- Driver/LLVM version: 4.4 Mesa 18.2.2, LLVM 7.0.0
- Distro version: Linux Mint 19.1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/veikk0/33ddc74ce228ff348965efac0f29662b
- Proton version: 3.16-6 Beta

## System Information: Laptop
- GPU: Intel HD Graphics 3000
- Driver/LLVM version: 3.0 Mesa 18.2.2
- Distro version: Linux Mint 19
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/veikk0/d546d3f9c1b89a0a3b7f072d7e04bc59
- Proton version: 3.16-6 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.

## Issues
- [x] I haven't experienced any issues.

## Notes
- This is a recent re-release of a 20-year-old classic that apparently [has worked in Wine for over a decade.](https://appdb.winehq.org/objectManager.php?sClass=version&iId=7693) Based on about an hour of play between two machines everything seems to function perfectly, including the online leaderboards and boardsets downloaded from Steam Workshop. I was even able to create a boardset of my own using the included editor.

**Comment by kisak-valve** [comment]
This game was found in the 2019-07-31 whitelist update.

If you encounter an issue with this game, please search the open issues for 922400, and report any issues encountered with this game in separate issue reports, one issue per issue report.
