### ISSUE TITLE
Into the breach fullscreen is not fixed (590380)

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/Proton#2338]
# Compatibility Report
- Name of the game with compatibility issues: Into the Breach
- Steam AppID of the game: 590380

## System Information
- GPU: 980ti
- Driver/LLVM version: 415.27
- Kernel version: 4.18.0-15-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/LiamDawe/b9ea7140267cdc643946bb2faa682d3c
- Proton version: 3.16-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. (there are other reports, but this is with the new proton beta)
- [x] that I have checked whether there are updates for my system available.

Proton log: 
[steam-590380.log](https://github.com/ValveSoftware/Proton/files/2871800/steam-590380.log)

## Symptoms 

When going into fullscreen, it will make it into a big window, turn it black and freeze the game forcing me to kill it from system monitor

**Comment by Bleuzen** [comment]
Well, maybe because 3.16-7 seems like a rebuild of 3.16-6, see:
https://github.com/ValveSoftware/Proton/issues/2337#issuecomment-464346718

**Comment by LiamDawe** [comment]
Actually it is, the issue is that Proton won't update unless you install it via the tools menu (as reported elsewhere).
