### ISSUE TITLE
UPlay no longer works when it automatically updates itself to the recent version

### ISSUE THREAD

**Issue by KayKay91** [ValveSoftware/Proton#2339]
# Compatibility Report
Any Ubisoft game which requires UPlay to run.

## System Information
- GPU: GTX 970
- Driver/LLVM version: NVIDIA 415.27
- Kernel version: 4.20.8
- Link to full system information report as [Gist](https://gist.github.com/KayKay91/b0b9ae1126a2f610ccc755941558cf28):
- Proton version: 3.16-7

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms
Once UPlay updates it's client after launching the game through Steam, it'll no longer show up at all, making any Ubisoft game relying on UPlay to no longer run, while Steam will mention that the game is still running.

upc.exe , which is the main UPlay Client executable is shown as <defunct> through `ps -e

## Reproduction
Launch any Ubisoft game on Steam which relies on UPlay.

Note: I couldn't upload the log file due to the fact that the file logs so many stuff on UPlay which causes it's size to reach beyond 10 MB limit (In my case with Assassin's Creed 4, it's log file is 80 MB big!)

**Comment by kisak-valve** [comment]
Hello @KayKay91, this issue is already being discussed at #2268. Closing in favor of the existing issue report.
