### ISSUE TITLE
Grand Theft Auto V Social Club Infinite Loading (271590)

### ISSUE THREAD

**Issue by jellz** [ValveSoftware/Proton#2343]
# Compatibility Report
- Name of the game with compatibility issues: Grand Theft Auto V
- Steam AppID of the game: 271590

## System Information
- GPU: GTX 1070 Max-Q
- Kernel version: 4.20.7-arch1-1-ARCH
- [System information report](https://gist.github.com/jellz/c3aa198d935e8140022aa1777933b690)
- Proton version: 3.16-4

## I confirm:
- [x] that I have checked whether there are updates for my system available.

*I added `PROTON_LOG=1` to the launch options; the file was not created*

## Symptoms 
Upon launching, Social Club opens, with a brief loading spinner, then says "Steam failed to initialize. Please exit and try again." [Screenshot](https://i.imgur.com/6ci9rfY.png)

If I use the LATEST Proton version 3.16-7 Beta, nothing happens after launching the game.

## Reproduction
- Use Proton 3.16-4
- Install GTA 5
- Launch GTA 5

**Comment by jellz** [comment]
I think I updated Proton (or something, there was a "Proton" thing queued in Downloads, so I downloaded it) and now [it's stuck on Loading](https://i.imgur.com/oZ4cFJK.png)

**Comment by ghost** [comment]
Try to reinstall the RGSC by executing the following command : `WINEPREFIX=~/.steam/steam/steamapps/compatdata/271590/pfx wine ~/.steam/steam/steamapps/common/Grand Theft Auto V/Installers/Social-Club-Setup.exe`

btw your post could get merged by @kisak-valve with #37

**Comment by kisak-valve** [comment]
Hello @jellz, as hinted by @Alexander88207, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-464455664.
