### ISSUE TITLE
configure.sh missing arg_steamrt initialization

### ISSUE THREAD

**Issue by MagmaiKH** [ValveSoftware/Proton#2344]
mkdir build;cd build;../configure.sh --no-steam-runtime 
Will result in an error, line ~253: if [[ -n $arg_no_steamrt && (-n $arg_steamrt32 || -n $arg_steamrt64 || -n $arg_steamrt) ]]; then

Adding
line ~129: arg_steamrt=""
Resolves the issue

**Comment by aeikum** [comment]
Sorry about that. Should be fixed now. Thanks for reporting! 7249989
