### ISSUE TITLE
Proton 3.16-7 is actually Proton 3.16-6

### ISSUE THREAD

**Issue by Niroc** [ValveSoftware/Proton#2346]
# Compatibility Report
- Name of the game with compatibility issues: Proton 3.16-7
- Steam AppID of the game: ???

## System Information
- GPU: GTX 870m
- Driver/LLVM version: NVIDIA 415.27
- Kernel version: 4.19.20-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Niroc/ab1f133f7e79e9e0d7932670b5f6cdc5
- Proton version: 3.16-7

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
I noticed that Proton 3.16-7 updated to DXVK 0.96 so I thought I'd try the `DXVK_HUD=full` option introduced in DXVK 0.95 but, it didn't work. So, I tried `DXVK_HUD=version` which revealed that I was running DXVK 0.94. 

I did double check that the games are set to run using 3.16-7...
![ds3-proton version](https://user-images.githubusercontent.com/12100786/52916448-7a234500-32d7-11e9-99f3-e310e518d2f3.png)
 
I then checked the "/home/niroc/.steam/steam/steamapps/common/Proton 3.16 Beta/" folder and noticed that files haven't had their Date Modified stamp updated this month. 

So, I think that it's still 3.16-6. If this has happened to anyone else then you may be getting erroneous error reports for things that have been fixed in Proton 3.16-7.

I have tried verifying integrity of games files, restarting steam, disabling and enable proton... to no avail 

## Reproduction
Use Proton 3.16-7

Proton log for DS3
[steam-374320.log](https://github.com/ValveSoftware/Proton/files/2873180/steam-374320.log)

**Comment by CSahajdacny** [comment]
It happened to me...
It can be solved going to Library--»Tools and manually installing Proton 3.16 beta.
![proton 3 16 beta](https://user-images.githubusercontent.com/45825041/52916776-851faa80-32c2-11e9-988e-d7859422ee19.png)

**Comment by Niroc** [comment]
excellent, let's hope everyone reads this thread.

**Comment by kisak-valve** [comment]
Hello @Niroc, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/6093. Closing as a duplicate.
