### ISSUE TITLE
The Elder Scrolls V: Skyrim freezes for a few seconds on every mouse movement

### ISSUE THREAD

**Issue by o-alquimista** [ValveSoftware/Proton#2348]
Proton version affected: 3.16-x Beta and Stable (**does not affect 3.7-x Beta or Stable**)
OS: elementary OS 5 Juno
_Specs:
i3-8100 w/ UHD Graphics 630
8 GB of DDR4-2400 Mhz RAM
Kingston SATA SSD A400_

**The problem**
The Elder Scrolls V: Skyrim freezes for a few seconds on every mouse movement. If I don't move the cursor and just press the arrow keys to walk around, it won't freeze and the game runs smooth.

**Comment by kisak-valve** [comment]
Hello @o-alquimista, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/460#issuecomment-465127086.
