### ISSUE TITLE
Final Fantasy IX - No Sound

### ISSUE THREAD

**Issue by Pantar2205** [ValveSoftware/Proton#2349]
# Compatibility Report
- Name of the game with compatibility issues: Final Fantasy IX
- Steam AppID of the game: 377840

## System Information
- GPU: RX480
- Driver/LLVM version: Mesa18.3.3
- Kernel version: 4.20.10-arch1-1-ARCH
- Proton version: 3.16-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
No Sound

Tried installing directsound via winetricks [This fixed sound in FF8] but no luck. Can't find anything else on protondb or in this github. Steam Controller and graphics are flawless, even on 4k monitor.

**Comment by kisak-valve** [comment]
Hello @Pantar2205, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/708#issuecomment-465212708.

**Comment by Pantar2205** [comment]
Oh my apologies, thank you.
