### ISSUE TITLE
[macOS] Any app with Vulkan/D3D11->DXVK crashes on start

### ISSUE THREAD

**Issue by pblyp** [ValveSoftware/Proton#235]
Hardware: Macbook Air 13" late 2015
Software: macOS 10.13.6

Tried running cube.exe demo from the Vulkan SDK and it failed:

```
MacBook-Air-gman:dist gman$ STEAM_COMPAT_DATA_PATH=~/SteamCompatDataPath ./proton run ~/SteamCompatDataPath/pfx/drive_c/cube.exe 
[mvk-info] MoltenVK version 1.0.10. Vulkan version 1.0.75.
[mvk-info] GPU device:
		model: Intel(R) Iris(TM) Graphics 6000
		type: Integrated
		vendorID: 0x8086
		deviceID: 0x1626
		pipelineCacheUUID: 00000000-0000-0000-0000-27130000271A
	supports the following Metal Feature Sets:
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
wine: Unhandled page fault on read access to 0xffffffffffffffff at address 0x46164da4 (thread 0009), starting debugger...
winedbg: Internal crash at 0x431257a5
MacBook-Air-gman:dist gman$ wine: Unhandled page fault on execute access to 0x4561b4b0 at address 0x4561b4b0 (thread 0025), starting debugger...
```

Also tried running Banished in DX11, but it resorts to using DX9 render.

**Comment by flukejones** [comment]
This occurs for anything using Vulkan currently (either direct or with D3D11).

**Comment by Mushoz** [comment]
If the .exe is using Vulkan itself (as is the case with demos from the Vulkan SDK), then the calls do not go through any translational layer, so DXVK isn't used in this case.

Have you tried running native Vulkan demos for MacOS? Do these run properly?

**Comment by pblyp** [comment]
@Mushoz Yes, cube.app and cubepp.app from the official Mac dist of Vulkan SDK do run.

**Comment by Mushoz** [comment]
Then unfortunately I do not know what is going wrong. Hopefully someone else with more knowledge than me will chime in :)

**Comment by Luke-Nukem** [comment]
I don't think wine and/or DXVK are linking and using MoltenVK perhaps.

**Comment by flukejones** [comment]
It looks like this is an issue with something on the Valve side. I was able to build a wine version from winhq using the MoltenVK compiled by the proton build script, and then run the `cube.exe` from the Vulkan SDK - Doom still crashes however (threading issue?). Will keep digging.

**Comment by flukejones** [comment]
Replacing the Wine version in Proton with the git source from winehq allows cube.exe to run fine.

<img width="1470" alt="screen shot 2018-08-28 at 11 55 56 am" src="https://user-images.githubusercontent.com/2015870/44692942-667deb00-aab9-11e8-842f-ca5e68fc2083.png">

**Comment by flukejones** [comment]
Running vkQuake windows build is also working fine through the MoltenVK layer, using winehq source and not Valve modified source.

**Comment by aaronfranke** [comment]
macOS support has been removed: https://github.com/ValveSoftware/Proton/commit/a84120449d8177fa40f3de729e55d238d3c24877

**Comment by nobodywasishere** [comment]
This issue should be closed due to the removal of macOS support
