### ISSUE TITLE
Killing Floor 2 (232090) game crashes when voice chat is used by someone in game

### ISSUE THREAD

**Issue by opal1974** [ValveSoftware/Proton#2360]
# Compatibility Report
- Name of the game with compatibility issues: Killing Floor 2
- Steam AppID of the game: 232090

## System Information
- GPU:  GTX 960
- Driver/LLVM version:  nvidia 415.27
- Kernel version:  4.18.0
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 3.16-7 Beta

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

When in game, if someone else in the server (ie not you the player) uses voice chat, it will crash the game most of the time.  There seems to be sound issues with this game to begin with, ie samples cutting out if 'interrupted' by another sample, but I don't find any compatibility report related to that.  I also note that at least for me, I never actually hear the other players who use the voice channel, but I see the notification on the screen of it and then *crash*. Absolutely annoying and I am tired of this killing the game. 

## Reproduction

Seems to happen in 90 percent of cases. Very rarely, someone the silent voice notification will happen it won't crash, but 9/10 it leads to a crash.

**Comment by kisak-valve** [comment]
Hello @opal1974, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1328#issuecomment-466643607.
