### ISSUE TITLE
World of Tanks Blitz MMO switching the keyboard to Russian not work

### ISSUE THREAD

**Issue by Ubuntu-RUS** [ValveSoftware/Proton#2362]
# Compatibility Report
- Name of the game with compatibility issues: World of Tanks Blitz MMO
- Steam AppID of the game:444200

## System Information
- GPU:  GTX 1030
- Driver/LLVM version: nvidia 390.00
- Kernel version:  4.18.0-15 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 3.16.4 or 3.7.8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

When switching the keyboard to Russian, the keyboard does not work. Space and numbers exception.

## Reproduction

1. You can find the Steam AppID in the URL of the shop page of the game.
   e.g. for `World of Tanks Blitz MMO` the AppID is `444200`.
2. The game works fine. Stable 60 FPS. I have no other comments on the work. 
3. The community has already had a discussion on this issue https://steamcommunity.com/app/221410/discussions/8/3441214221469756469/

**Comment by kisak-valve** [comment]
Hello @Ubuntu-RUS, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1293#issuecomment-466723189.
