### ISSUE TITLE
[Question]: Can I use Windows steam downloads folder 

### ISSUE THREAD

**Issue by mritunjaymusale** [ValveSoftware/Proton#2368]
I have already downloaded games for windows and are in my steam library for windows, so instead of re-downloading everything can I just move them and do "verify integrity...." and proceed?

**Comment by kisak-valve** [comment]
Hello @mritunjaymusale, in general cross-OS sharing of Steam libraries is not supported.

That said, Steam does attempt to discover existing game files in the Steam library when you tell it to install a game. So, you can give it a try, but if anything goes awry, it's up to you to figure it out.

Closing as this is not a Proton issue.
