### ISSUE TITLE
compiling proton with make inside vagrant vm ends with error

### ISSUE THREAD

**Issue by LinuxSquare** [ValveSoftware/Proton#2369]
**Hey there.**

As already written in the title, the command `make` inside the `$HOME/build` directory of vagrant, ends in an error, telling, that the image `steam-proton-dev32-beta:latest` could not be found:

Here is the whole console-output:
```
make  -f Makefile NO_NESTED_MAKE=1
make[1]: Entering directory '/home/vagrant/build'
mkdir -p obj-cmake32
Unable to find image 'steam-proton-dev32-beta:latest' locally
docker: Error response from daemon: pull access denied for steam-proton-dev32-beta, repository does not exist or may require 'docker login'.
See 'docker run --help'.
../proton/build/makefile_base.mak:241: recipe for target 'obj-cmake32' failed
make[1]: *** [obj-cmake32] Error 125
make[1]: Leaving directory '/home/vagrant/build'
../proton/build/makefile_base.mak:17: recipe for target 'nested_make' failed
make: *** [nested_make] Error 2
```

`docker login` was executed but not helping in any way..

I would appreciate any help..

EDIT: 
Forgot to mention my distribution details:

OS: Arch Linux x86_64
Kernel: 4.19.25-1-lts
CPU: Intel i7-4770
Memory: 16GB

Yours sincerely
LinuxSquare

**Comment by IanTrudel** [comment]
I am also having troubles building Proton on CentOS 7. The Vagrant VM is certainly not fully self contained because the dependencies requirements on the host OS are overwhelming. Unfortunately, many libraries on CentOS are dated and the whole thing needs to compile newer versions on the side. Not working too well so far.

**Comment by aeikum** [comment]
@LinuxSquare We've switched back and forth between the beta and non-beta runtimes a few times. For the forseable future, we should be on the non-beta runtime, so hopefully that is settled. I think if you pull the latest proton-3.16 branch (pushed just now), and then delete your vagrant vm with `vagrant destroy` to start over from a clean state, it should be working well.

**Comment by LinuxSquare** [comment]
Well, thanks for your answer @aeikum 
But I have to give up trying to compile proton for myself.

I'm just to dumb for it..

**Comment by j1m1l0k0** [comment]
Try using this step by step
https://github.com/ValveSoftware/Proton/wiki/Build-instructions-(Fedora)
