### ISSUE TITLE
Trials Fusion doesn't start (245490)

### ISSUE THREAD

**Issue by fsyy** [ValveSoftware/Proton#2377]
# Compatibility Report
- Name of the game with compatibility issues: Trials Fusion
- Steam AppID of the game: 245490

## System Information
- GPU: GTX 1060 6GB
- Driver/LLVM version: nvidia 418.43
- Kernel version: 4.20.13
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/fsyy/b5a9c0ecd22d26cbfce8faab8b0076f4
- Proton version: 3.16-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-245490.log](https://github.com/ValveSoftware/Proton/files/2922551/steam-245490.log)

## Symptoms
if i click play it says running, then after a few seconds running disappears and that's it

## Reproduction
install game and click play

**Comment by kisak-valve** [comment]
Hello @fsyy, your log is missing a header that was added with Proton 3.16-7, which hints that you're not using the version of Proton that you expected. Please go to Steam -> Library dropdown -> Tools and install Proton 3.16 beta from the list.

**Comment by fsyy** [comment]
Hello @kisak-valve,

strange, my steam client tells me i have 3.16-7 set up for all games.

**Comment by fsyy** [comment]
ok, i tried it again, it works now :) :+1:
