### ISSUE TITLE
GTA 5 crashes when you do GTA Online 

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#2383]
# Compatibility Report
- Game: Grand Theft Auto 5 
- Steam AppID of the game: 271590

## System Information
- GPU: GTX 1060 6GB
- Driver/LLVM version: Nvidia 418.43
- Kernel version: 4.20.10-111.current
- Link to full system information report
 https://gist.github.com/coreybruce/dcd2bec911594c9212d351ac2e7a3f98:
- Proton version: 3.16-4

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

log is 400mb so I can't upload it on here.

## Symptoms 
When I go to play GTA online as soon as the character walks onto the mat to make your new character the game crashes making it impossible to play GTA online 

## Reproduction
just go to GTA online and go create a character, the game will crash.

**Comment by kisak-valve** [comment]
Hello @coreybruce, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-470528267.

You should be able to mitigate this issue by adding `WINEDLLOVERRIDES=winedbg.exe=d %command%` to the game's launch options (https://github.com/ValveSoftware/Proton/issues/37#issuecomment-464733057).

**Comment by coreybruce** [comment]
oh ok thanks, what do I do if it doesn't help? -Edit- It works thanks

**Comment by LordJABA** [comment]
Does not seem to work for me. But attaching strace does work
`strace -p $(ps -C GTA5.exe -o pid=) ` when game is running but before going online. It halves my fps but I can kill it after I log in.
Also logging in takes minimum 10-15 minutes on loading screen.
I would appreciate any suggestions for better solution. winedbg.exe as described above has no effect for me - It's crushing back to launcher after 15 minutes of "loading" and prompts for restart - same as if I just run it without any  additional "moves"
