### ISSUE TITLE
Ape out (447150)

### ISSUE THREAD

**Issue by seppaleinen** [ValveSoftware/Proton#2385]
# Compatibility Report
- Ape out
- 447150

## System Information
- GPU: Intel Iris Plus 640 (Kaby Lake GT3e)
- Driver/LLVM version: 3.0 Mesa 19.1.0-devel 
- Kernel version: 4.15.0-46-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 3.16-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-447150.log](https://github.com/ValveSoftware/Proton/files/2943445/proton.log)

## Symptoms 
Game starts perfectly unless I have my ps4 controller connected via bluetooth.
If it's connected, the game crashes after the initial loading screen.

## Reproduction
Connect ps4 controller, and start game. Doesn't matter if wined3d, or esync is on or off.

**Comment by seppaleinen** [comment]
I am for some reason able to start the game if my controller is off.
Connecting the controller when the game is loaded is also working.

**Comment by kisak-valve** [comment]
Hello @seppaleinen, this game was found in 2019-07-31 whitelist update.

Are you still experiencing this issue with Proton 4.2 or newer?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by krompus** [comment]
This game might be on the whitelist, but I'd like to note that it was incredibly sluggish before I put `PROTON_USE_WINED3D=1 %command%` in the launch options; runs perfectly afterwards.
