### ISSUE TITLE
Devil May Cry 5 (601150)

### ISSUE THREAD

**Issue by Lumatf** [ValveSoftware/Proton#2398]
# Compatibility Report
- Name of the game with compatibility issues: Devil May Cry 5 
- Steam AppID of the game:601150

## System Information
- GPU: RX 580

- Driver/LLVM version: Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 4.19.24-1-MANJARO, LLVM 7.0.1)

- Kernel version: 4.19.24-1-MANJARO

- Link to full system information report as 
https://gist.github.com/Lumatf/378e8418f037d9279800c5c72105a638

- Proton version:3.16-8
## I confirm:
- [x] that I haven't found an existing compatibility report for this game.

- [x] that I have checked whether there are updates for my system available.

[steam-601150.log](https://github.com/ValveSoftware/Proton/files/2949103/steam-601150.log)

##Symptoms 
The game will crash if with anything related to mfplat being used.

##Reproduction
Selecting The History of Devil May Cry video on the title screen or trying to access the shop to buy abilities.

**Comment by kisak-valve** [comment]
Hello @Lumatf, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2386#issuecomment-471238879.
