### ISSUE TITLE
Running Men of War: Assault Squad via command-line

### ISSUE THREAD

**Issue by tupo2** [ValveSoftware/Proton#2399]
I did:
```
cd ~/.local/share/steam/steamapps/common/Proton\ 3.7/dist/bin
./wine ~/.local/share/steam/steamapps/common/Men\ of\ War\ Assault\ Squad/mow_assault_squad.exe
```

But I get:
> wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
> 000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
> 0021:err:module:load_builtin_dll failed to load .so lib for builtin L"winebus.sys": libudev.so.0: cannot open shared object file: No such file or directory
> 0021:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\WineBus": c0000142
> 0021:err:winedevice:create_driver failed to create driver L"WineBus": c0000142
> 0015:err:service:process_send_command service protocol error - failed to write pipe!
> 000f:fixme:service:scmdatabase_autostart_services Auto-start service L"WineBus" failed to start: 1114
> Wine cannot find the FreeType font library.  To enable Wine to
> use TrueType fonts please install a version of FreeType greater than
> or equal to 2.0.5.
> http://www.freetype.org
> 0009:err:module:load_library somehow failed to load steamclient

Otherwise it works perfectly with the Steam client.

**Comment by aeikum** [comment]
Proton is not intended to be invoked that way. Why are you trying to run Proton's wine directly?

**Comment by tupo2** [comment]
In fact, I would like to run the Gem editor that way.

**Comment by aeikum** [comment]
The `PROTON_DUMP_DEBUG_COMMANDS` scripts are probably the right way to do what you want.

**Comment by tupo2** [comment]
Thanks, works fine with the "run" script.

**Comment by aeikum** [comment]
Great!
