### ISSUE TITLE
Football manager 2019 Refuses to launch due to SteamAPI unable to initialize

### ISSUE THREAD

**Issue by celebdor** [ValveSoftware/Proton#2402]
# Compatibility Report
- Name of the game with compatibility issues: Football Manager 2019
- Steam AppID of the game: 872790

## System Information
- GPU: Intel HD Graphics 520
- Driver/LLVM version: mesa-libGL-18.3.4-1
- Kernel version: 4.19.2-301.fc29.x86_64
- Link to full system information report as [System information](https://gist.github.com/celebdor/4ee97a75b1ceda50a72c2df3d244fff8):
- Proton version: 3.16-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

It did not generate any log by setting the launch options.

## Symptoms: A Proton dialog shows up stating:
Unable to initialize SteamAPI.
Please make sure Steam is running and you are logged in to an account entitled to the game.

## Reproduction
Just click play on the game in the library.

## Workaround

Steam -> Settings -> Steam Play -> Run other titles with == 'Proton 3.7-8'

**Comment by kisak-valve** [comment]
Hello @celebdor, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2123#issuecomment-471519578.

**Comment by celebdor** [comment]
Thanks @kisak-valve !
