### ISSUE TITLE
Allow playing games from Windows partition seamlessly

### ISSUE THREAD

**Issue by jharmer95** [ValveSoftware/Proton#2406]
# Feature Request
Allow playing games from Windows partition seamlessly
## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Add the ability to play games installed under Steam for Windows using Proton and Steam for Linux. While Steam supports adding external .exe files to run under Proton now, Steam games won't work because they require Steam (for Windows). Additionally, it would be nice to be able to keep save games and achievements going. It would be a great way to test Proton compatibility on games you already have installed without having to re-download them or take up additional storage space.
## Justification [optional] 
This feature is only relevant to Steam and Steam games

**Comment by parkerlreed** [comment]
I would assume that would have to be a Steam feature request. Proton would just be told where to load the games from. 

https://github.com/ValveSoftware/steam-for-linux/issues

**Comment by kisak-valve** [comment]
Hello @jharmer95, would be a feature request for the Steam client, not Proton, and sharing libraries across OSes is not supported.

This is noted at "Application files installed by Steam for Linux should not be shared (e.g. between Windows and Linux). This is a requirement of the Steam for Linux client." on https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation (from https://github.com/ValveSoftware/steam-for-linux/issues/546).
