### ISSUE TITLE
Neverwinter works with Wine but not with Steam Play

### ISSUE THREAD

**Issue by FinixFighter** [ValveSoftware/Proton#2411]
# Compatibility Report
- Name of the game with compatibility issues: Neverwinter
- Steam AppID of the game: 109600

## System Information
- GPU: AMD KABINI
- Driver/LLVM version: 4.4 Mesa 18.2.2
- Kernel version: 4.15.0-45-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 3.16-8 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-109600.log](https://github.com/ValveSoftware/Proton/files/2958645/steam-109600.log)

## Symptoms  The game works perfectly with Wine, but it doesn't start with Steam Play. This is a screenshot of the error:
![Neverwinter error](https://user-images.githubusercontent.com/19877271/54233242-d0695980-450c-11e9-8580-5345d4884e9a.png)

**Comment by kisak-valve** [comment]
Hello @FinixFighter, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1725#issuecomment-472172409.
