### ISSUE TITLE
Future Proof (844130)

### ISSUE THREAD

**Issue by ehea617** [ValveSoftware/Proton#2416]
# Compatibility Report
- Name of the game with compatibility issues: Future Proof
- Steam AppID of the game: 844130

## System Information
- GPU: NVIDIA GeForce GT 1030
- Driver/LLVM version: NVIDIA 410.93
- Kernel version: 4.19.0-2-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ehea617/c1138ee7d2068313e37e45bcc9de29bb
- Proton version: 3.16-8 Beta

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-844130.log](https://github.com/ValveSoftware/Proton/files/2968088/steam-844130.log)

## Symptoms
Game crashes after the introduction. If you skip the introduction, it goes in game but crashes shortly after.

## Reproduction
1. Start a new game.
2. Go through the introduction.
3. The game will crash after the introduction.

## Additional notes
I tested the game with the following options and they did not fix the crash:

- PROTON_USE_WINED3D=1 
- PROTON_NO_D3D11=1
- PROTON_NO_ESYNC=1

After testing with the new Proton 4.2-1 and 4.2-2 updates, the game crashes after the splash screen and no longer makes it to the main menu.

**Comment by HonkingGoose** [comment]
Maybe your crash is Media Foundation related? But I only see one line related to mf in the log:

19:0024:0051:trace:module:LdrGetDllHandle L"mf.dll" -> (nil) (load path L"Z:\\media\\evan\\Files\\Video Games\\Steam\\steamapps\\common\\Future Proof;C:\\Program Files (x86)\\Steam;C:\\windows\\system32;C:\\windows\\system;C:\\windows;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem")

**Comment by ehea617** [comment]
> Maybe your crash is Media Foundation related? But I only see one line related to mf in the log:
> 
> 19:0024:0051:trace:module:LdrGetDllHandle L"mf.dll" -> (nil) (load path L"Z:\media\evan\Files\Video Games\Steam\steamapps\common\Future Proof;C:\Program Files (x86)\Steam;C:\windows\system32;C:\windows\system;C:\windows;.;C:\windows\system32;C:\windows;C:\windows\system32\wbem")

Probably not. That line appears way up at the beginning of the file and is the only thing that appears related to Media Foundation. Closer to the end of the file, there is:

[0314/143918.584:ERROR:crashpad_client_win.cc(174)] crash server did not respond, self-terminating
14027.047:0024:0036:trace:module:GetModuleFileNameW L"Z:\\media\\evan\\Files\\Video Games\\Steam\\steamapps\\common\\Future Proof\\Future Proof.exe"

so maybe something around there?

**Comment by HonkingGoose** [comment]
Do the "splash screen"-videos and other video files playback in-game? Maybe the game is crashing because playback of those files is not working. If those videos all work, then the problem is likely somewhere else. :smile: 

https://en.wikipedia.org/wiki/Splash_screen

**Comment by ehea617** [comment]
The game is an RPG Maker MV game. You can open the file Future Proof/www/index.html in a web browser to see what it's supposed to do. The splash screen renders fine.

**Comment by ehea617** [comment]
After testing with the new Proton 4.2-1 and 4.2-2 updates, the game crashes after the splash screen and no longer makes it to the main menu.

**Comment by kisak-valve** [comment]
Hello @ehea617, please add a proton log with the game and Proton 4.2-2.

**Comment by ehea617** [comment]
@kisak-valve Here's the log for it on 4.2-2: 
[steam-844130-4.2-2.log](https://github.com/ValveSoftware/Proton/files/3036640/steam-844130-4.2-2.log)

**Comment by ehea617** [comment]
Good news! I just retested the game on the latest 4.13-4 and Proton Experimental and it is now working perfectly as far as I can tell.
