### ISSUE TITLE
HITMAN 2 can't connect to the server (863550)

### ISSUE THREAD

**Issue by mashedkeyboard** [ValveSoftware/Proton#2417]
# Compatibility Report
- Name of the game with compatibility issues: HITMAN 2
- Steam AppID of the game: 863550

## System Information
- GPU:  GTX 1060
- Driver/LLVM version:  nvidia 418.43
- Kernel version:  4.19.28-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/mashedkeyboard/6413c6e6efabcb2e8426a2ec4b557ce0
- Proton version: 3.7-8 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-863550.log](https://github.com/ValveSoftware/Proton/files/2968724/steam-863550.log)

## Symptoms 
Looks like a similar issue to #1972, which was closed in favour of #162, but #162 appears to be solved, and the last post there was asking to make a separate issue, so I'll put it here instead.

Upon trying to launch HITMAN 2, I get an error as below:

![error "Failed to fetch version information for the HITMAN 2 server"](https://user-images.githubusercontent.com/16772519/54395905-11967080-46a9-11e9-94cc-a25233688e24.png)

This doesn't happen on Windows, only on Linux. I'm not using a VPN or a proxy or anything like that, and I've tried on both 3.7-8 and 3.7-8 Beta.

Offline play works absolutely fine.

## Reproduction
1. Launch HITMAN 2
2. Press "enter"
3. The error immediately appears

**Comment by Brisse89** [comment]
HITMAN 2 works perfectly fine for me on latest Proton. Have you tried 3.16-8?

**Comment by mashedkeyboard** [comment]
Works on 3.16-8. And I've just realised that 3.16-8 isn't 3.1 v6-8, it's 3.16 on its own - and thus a later version than 3.7. Ugh.

Thanks! That fixes the issue for anyone else who sees this problem.
