### ISSUE TITLE
Proton 3.16-8 Beta - Nothing launches

### ISSUE THREAD

**Issue by parkerlreed** [ValveSoftware/Proton#2419]
# Compatibility Report
- Proton

## System Information
- GPU: RX 480
- Driver/LLVM version: Mesa 19.1.0/LLVM 9.0.0
- Kernel version: 5.0.1
- Link to full system information report: https://gist.github.com/parkerlreed/e11a8bbbbec86c9e1907d59dccef38b2
- Proton version: 3.16-8 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Whenevr I try to launch any title using the latest beta, I get this error. z: folder does not exist.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/parker/easystore/SteamLibrary/steamapps/common/Proton 3.16 Beta/proton", line 168, in <module>
    tar.extractall(path=basedir + "/dist")
  File "/usr/lib/python3.7/tarfile.py", line 2002, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2044, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2122, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2215, in makelink
    targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2116, in _extract_member
    self.makedir(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2145, in makedir
    os.mkdir(targetpath, 0o700)
OSError: [Errno 22] Invalid argument: '/run/media/parker/easystore/SteamLibrary/steamapps/common/Proton 3.16 Beta/dist/./share/default_pfx/dosdevices/z:'
Traceback (most recent call last):
  File "/usr/lib/python3.7/tarfile.py", line 2204, in makelink
    os.symlink(tarinfo.linkname, targetpath)
OSError: [Errno 22] Invalid argument: '/' -> '/run/media/parker/easystore/SteamLibrary/steamapps/common/Proton 3.16 Beta/dist/./share/default_pfx/dosdevices/z:'
```

## Reproduction

Launch any title with newest beta

**Comment by NoXPhasma** [comment]
Can you please check if Proton 3.16 Beta is installed under the Tools tab of your library?

![Unbenannt](https://user-images.githubusercontent.com/7719590/54421321-7e8f2200-470c-11e9-87a3-bc73b25dc37b.png)

**Comment by parkerlreed** [comment]
It is indeed.

![Screenshot_20190315_121457](https://user-images.githubusercontent.com/841440/54445840-06305d00-471c-11e9-82da-5900b1f48fda.png)

Weird thing is on my other machine, it works.

The machine erroring out has the Steam library on an NTFS drive. It runs other games from there fine (native)

I tried uninstalling the tool but it complains about "missing shared context" (Even on the machine that works)

**Comment by kisak-valve** [comment]
Hello @parkerlreed, using Proton on NTFS is known to be problematic https://github.com/ValveSoftware/Proton/issues/82#issuecomment-415099440. Please give #11 a read.

**Comment by parkerlreed** [comment]
Ahh thanks. I could have sworn this was working for a while. Just coming back to this after finally resizing NTFS down to less than 2TB free... https://github.com/ValveSoftware/steam-for-linux/issues/5742

Honestly at this point I'm done. I'll just move everything over to EXT4. Thanks.
