### ISSUE TITLE
Grand Theft Auto 5 doesn't lock mouse after alt tab dual screen

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#2422]
# Compatibility Report
- Game: Grand Theft Auto 5
- Steam AppID of the game: 271590

## System Information
- GPU: GTX 1060 6GB
- Driver/LLVM version: Nvidia 418.43
- Kernel version: 4.19.28-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/coreybruce/dcd2bec911594c9212d351ac2e7a3f98):
- Proton version: 3.16-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
After alt tabbing the game does not lock the mouse resulting my mouse appearing on my second screen

## Reproduction
Alt tab game when using multi monitors

**Comment by kisak-valve** [comment]
Hello @coreybruce, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-473367271.
