### ISSUE TITLE
Videos not displayed on Unreal Engine 4 games

### ISSUE THREAD

**Issue by leillo1975** [ValveSoftware/Proton#2430]
I tried 4 different games created with Unreal Engine 4 and in all of game the game videos are not displayed. Three of this games are:

-**Assetto Corsa Competizione** (805550): Intro video (https://github.com/ValveSoftware/Proton/issues/1420)
-**Dakar 18** (767390) : Podium video (https://github.com/ValveSoftware/Proton/issues/2113)
-**Everspace** (396750) : This game has native support, but when you execute it with Proton, the intro videos are not displayed. You can see only the subtitles.
-A game that I tried a few months ago and that I don't remember, but I know it was made with UE4....I'm sorry, I know it's not very professional.... I've been trying to remember, like, 10 minutes....

I would like that if there really are more games made with EU4 with the same problem you put them here

**Comment by kisak-valve** [comment]
Hello @leillo1975, these games most likely need Media Foundation and/or quartz support to mature in upstream wine. In general this is being tracked at #1464.

Please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to Assetto Corsa's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box on #1420.

Dakar 18 needs Media Foundation support to mature in upstream wine.

Please open a new compatibility report for Everspace.

Closing in favor of the existing issue reports.
