### ISSUE TITLE
Return to Castle Wolfenstein (9010)

### ISSUE THREAD

**Issue by dreamer** [ValveSoftware/Proton#2432]
# Whitelist Request
- Name of the game to be whitelisted: Return to Castle Wolfenstein
- Steam AppID of the game: 9010
- Related compatibility report: #542 

## System Information
- GPU: system 1: GTX 770, system 2: Intel HD Graphics 3000
- Driver/LLVM version: system 1: 4.6.0 NVIDIA 418.43, system 2: 3.0 Mesa 18.3.3
- Distro version: Fedora 29
- Link to full system information report as [Gist](https://gist.github.com/): [1](https://gist.github.com/dreamer/03179db6f82b01e06ec8fa41faf09f00), [2](https://gist.github.com/dreamer/4f3773020ded88d4612e41de4dd67b7e)
- Proton version: 3.16-8 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [x] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [x] that no workarounds other than PROTON_* env variables are necessary (PROTON_OLD_GL_STRING=1)

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

## Additional comments

Briefly tested both singleplayer and multiplayer, also tested alt-tabbing behaviour - everything worked perfectly.

**Comment by kisak-valve** [comment]
Hello @dreamer we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/542#issuecomment-474510703.
