### ISSUE TITLE
Vagrant build (with steam runtime) fails during wine-intermediate target: d3dx9_28.so

### ISSUE THREAD

**Issue by IkeBroflovskiForPresident** [ValveSoftware/Proton#2433]
Using Vagrant vm with steam runtime and easy build path from readme. Happens when issuing "make install" or "make proton" from Ubuntu x86_64 18.04 LTS host.

Attached file is output from within the vagrant VM, using:

"make -C build/ dist 2>&1 | tee vagrant.make.proton.error"

A couple things I found noteworthy from the output:

Early in the build we see

"make dist -f Makefile NO_NESTED_MAKE=1"

yet the very last error given is

../proton/build/makefile_base.mak:17: recipe for target 'nested_make' failed
make: *** [nested_make] Error 2
make: Leaving directory '/home/vagrant/build'

and seems like it could be suspicious given "nested_make and no_nested_make=1". However soon enough we run into a series of:

../../../../proton/wine/dlls/d3dx9_28/d3dx9_28.spec:7: function 'D3DXCheckCubeTextureRequirements' not 
defined

which is then followed by:

winegcc: ../../tools/winebuild/winebuild failed
make[1]: *** [Makefile:1164: d3dx9_28.dll.so] Error 2
make[1]: Leaving directory '/home/vagrant/build/obj-wine32/dlls/d3dx9_28'
make: *** [Makefile:8409: dlls/d3dx9_28] Error 2
make: *** Waiting for unfinished jobs....

and eventually ending with:

../proton/build/makefile_base.mak:729: recipe for target 'wine32-intermediate' failed
make[1]: *** [wine32-intermediate] Error 2
make[1]: Leaving directory '/home/vagrant/build'
../proton/build/makefile_base.mak:17: recipe for target 'nested_make' failed
make: *** [nested_make] Error 2
make: Leaving directory '/home/vagrant/build'

[vagrant.make.proton.error.txt](https://github.com/ValveSoftware/Proton/files/2985290/vagrant.make.proton.error.txt)

**Comment by aeikum** [comment]
Hm, haven't seen that before. Is it possible you have corrupt `.o` files in there, from a previous VM crash or disk space exhaustion? You can try doing a `make clean` from within `obj-wine32/dlls/d3dx9_28` to force it to rebuild the `.o` files and try linking again.

**Comment by IkeBroflovskiForPresident** [comment]
make clean within /home/build/obj-wine32/dlls/d3dx9_28 seems to have fixed my problem.
