### ISSUE TITLE
Witcher 3 not detecting graphics card

### ISSUE THREAD

**Issue by eebrinsfield** [ValveSoftware/Proton#2437]
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD FX(tm)-8320 Eight-Core Processor           
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  1482 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 18.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.18.0-16-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12001000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2019-01-10

Video Card:
    Driver:  X.Org Radeon RX 570 Series (POLARIS10, DRM 3.26.0, 4.18.0-16-generic, LLVM 7.0.0)
    Driver Version:  4.5 (Compatibility Profile) Mesa 18.3.3
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x67df
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 18.78" x 10.55" (21.54" diag)
                                            47.7cm x 26.8cm (54.7cm diag)
    Primary VRAM: 8192 MB

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  15938 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  2476189 Mb
    Largest Free Hard Disk Block:  1878286 Mb
    VR Headset: None detected

Recent Failure Reports:

Everytime I try to load the game it will say "Minimal Graphics card undetected for direct x 11". I know this graphics card is good for direct x 12. I am running RX 570.

**Comment by kisak-valve** [comment]
Hello @eebrinsfield, install vulkan drivers for your video card with `sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386`.

**Comment by eebrinsfield** [comment]
Thank you, it works now.
