### ISSUE TITLE
Proton can't work without symlinks. And symlinks aren't supported in FAT32

### ISSUE THREAD

**Issue by Encritary** [ValveSoftware/Proton#2439]
Hello! I'm using my HDD with FAT32 partition for Steam library. But, as I understand, Proton tries to symlink some files into Wine prefix. However, FAT32 doesn't support symlinks. That's why Proton doesn't work for me.

My idea: check if symlinks are applicable. If not, use copy.

**Comment by kisak-valve** [comment]
Related: #1402

**Comment by lucifertdark** [comment]
You don't need a fat32 partition for windows games in Linux, use ext4 or whatever your flavour of Linux uses by default & everything will work as it should.

**Comment by kisak-valve** [comment]
Hello @Encritary, thanks for finding the root cause of your issue. I've heard from a Proton dev that we are not going to support FAT32 due to the lack of support for symlinks and the max file size of 4GB. Please use a linux native filesystem for the best experience.

**Comment by jvschiavo** [comment]
@kisak-valve What are the file system formats supported by Proton?

This information should be easily accessible since it may lead to a lot of confusion.
