### ISSUE TITLE
Doom 2016 (379720) mouse sensitivity not uniform

### ISSUE THREAD

**Issue by axb993** [ValveSoftware/Proton#2440]
# Compatibility Report
- Name of the game with compatibility issues: DOOM 2016
- Steam AppID of the game: 379720

## System Information
- GPU: RTX 2070
- Driver/LLVM version: nvidia 418.43
- Kernel version: 5.0.2
- Link to full system information report as [Gist](https://gist.github.com/axb993/1335f879346877eb413d84bae1ebbefa)
- Proton version: 3.16-8 Beta

## I confirm:
- [ Y ] that I haven't found an existing compatibility report for this game.
- [ Y ] that I have checked whether there are updates for my system available.

(Cannot attach log as it's ~70MB, I can upload to Drive or something if necessary)

## Symptoms

Mouse is more sensitive when moving to the right than any other direction. Trying to move the cursor to the left edge of the screen results in it hovering near the edge before moving slightly back to the right. The cursor also starts in the top left corner of the screen.

[I recorded the problem in case that description doesn't make sense.](https://i.imgur.com/XNtLyrv.mp4)

This happens with Vulkan and OpenGL, fullscreen or windowed. Using Proton 3.16-8 Beta as both 3.16-4 and 3.7-8 Beta do not launch, and 3.7-8 hangs on a black screen. Everything was working perfectly before today.

## Reproduction

Start game, move mouse. Thought this could be a duplicate of #147 but changing polling rate/DPI has no effect.

**Comment by kisak-valve** [comment]
Hello @axb993, in general proton logs should compress well in an archive if you want to attach your log here. Can you note what model of mouse you are using and what polling rates you tried?

**Comment by axb993** [comment]
[steam-379720.zip](https://github.com/ValveSoftware/Proton/files/2991925/steam-379720.zip) should have thought of that sorry. Using a Razer Naga 2014, tried at 1000Hz, 500Hz and 125Hz. Actually I just noticed at 125Hz it's worse, at least with the hovering when moving to the left edge. [Recording](https://i.imgur.com/CF3hCvz.mp4)

**Comment by axb993** [comment]
Appears to be fixed in Proton 4.2-1 :)

**Comment by kisak-valve** [comment]
Hello, please retest this game with Proton 6.3-6 and see if any regressions have crept in since this issue was last evaluated.
