### ISSUE TITLE
Batman Arkham City GOTY Error Message

### ISSUE THREAD

**Issue by SahilPlays** [ValveSoftware/Proton#2442]
So I got the game recently. I had a launching issue which was fixed by one of the solutions i found.
The worked normally, but I wanted to adjust the settings of the game. When I opened it again, it game me this error message after the nvidia intro,
![Screenshot from 2019-03-21 17-05-20](https://user-images.githubusercontent.com/48796121/54755006-53ba3780-4bfe-11e9-904e-a5cbe2c41711.png)

**Comment by SahilPlays** [comment]
OS: Ubuntu 18.10 (I used to get it to work)
CPU: Intel Core i3 4005U @ 1.7 GHz
Ram: 4 GB
GPU: Intel HD Graphics 4400
Please ask if you need any more Info

**Comment by SahilPlays** [comment]
OS: Ubuntu 18.10 (I used Wine to get the game to work)
CPU: Intel Core i3 4005U @ 1.7 GHz
Ram: 4 GB
GPU: Intel HD Graphics 4400

**Comment by kisak-valve** [comment]
Hello @SahilPlays, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/309#issuecomment-475238849.
