### ISSUE TITLE
Upgrade default Spelunky (239350) Proton version

### ISSUE THREAD

**Issue by jakemagee** [ValveSoftware/Proton#2443]
# Whitelist Request
- Name of the game to be whitelisted: Spelunky
- Steam AppID of the game: 239350

## System Information
- GPU: GTX 670
- Driver/LLVM version: nvidia 418.43
- Distro version: Ubuntu 18.10
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/jakemagee/8652bca48de711fc26757d9a0cf64ac6
- Proton version: 3.16-8

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [X] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [X] I haven't experienced any issues.
- [X] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

Please update the default Proton version to 3.16-8.  With 3.7-8, I was getting small graphical shuddering (hard to describe) that while playable, was very visually annoying.  I also tried 3.16-4, but then the game fails to launch.

**Comment by jvschiavo** [comment]
I think it doesn't work with 3.16 for me, but works with 3.7-8 instead. I'll test again to be sure.
Also, I think we should start testing it with the new Proton 4.2 version.

**Comment by jakemagee** [comment]
Please try 3.16-8 specifically... 3.16-4 would not work for me either.

**Comment by lucifertdark** [comment]
I can confirm Spelunky is working with Proton 4.2-1 & the latest Nvidia drivers. Solid 60fps at all times. No launch options or workarounds needed to get it running.

**Comment by jakemagee** [comment]
Same here... I didn't realize that 4.2-1 had been released, but I just switched to it and its working fine (along with the latest 418.56 Nvidia drivers).  Please update the default Proton version to 4.2-1.

**Comment by jakemagee** [comment]
Proton 4.2-3 with latest Nvidia drivers (418.56) is still working great.  Please update the default Proton version to 4.2-3.

**Comment by kisak-valve** [comment]
Hello, please retest this game with Proton 6.3-6 and see if any regressions have crept in since this issue was last evaluated.
