### ISSUE TITLE
How to start a game with proton that is not in steam?

### ISSUE THREAD

**Issue by 0d1n89** [ValveSoftware/Proton#2448]
Hey,

i just wanted to know what do i have to do when i want to add a game to steam that is not on steam. I have the option to add this but what entry do i need so that i can start it with proton? 

greetings

odin89

**Comment by XakepSDK** [comment]
1. https://support.steampowered.com/kb_article.php?ref=2219-YDJV-5557
2. In shortcut settings mark checkbox 'Launch with proton' or similar

**Comment by ghost** [comment]
[How do I run Windows games I don't own on Steam?](https://github.com/NoXPhasma/protondb_faq#how-do-i-run-windows-games-i-dont-own-on-steam)
