### ISSUE TITLE
Ryse Son of Rome not working

### ISSUE THREAD

**Issue by gituser823** [ValveSoftware/Proton#2451]
# Compatibility Report
- Name of the game with compatibility issues:
Ryse: Son of Rome
ID: 302510

## System Information
- GPU: NVIDIA Geforce GTX 960
- Driver/LLVM version: nvidia 415.27
- Kernel version: 4.15.0-46
- Link to full system information report as [Gist](https://gist.github.com/): --
- Proton version: 3.16-8 Beta and 3.16-4

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

[steam-302510.log](https://github.com/ValveSoftware/Proton/files/3000950/steam-302510.log)

## Symptoms 
I see no Video output. The mouse cursor changes to a different than the Cinnamon-Cursor and I can move it only in the top left corner of my desktop.
The Sound for the Startmenu works though.

## Reproduction
Start the Game.

**Comment by kisak-valve** [comment]
Hello @gituser823, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2365#issuecomment-476008777.
