### ISSUE TITLE
Bloons TD5 (306020)

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/Proton#2453]
# Whitelist Request
- Name of the game to be whitelisted: Bloons TD5
- Steam AppID of the game: 306020

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 418.43
- Distro version: Fedora Workstation 29
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Newbie13XD/a119a36b89e1481dbfae1d6f8e463392
- Proton version: Proton 3.16-8 beta

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [X] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @Newbie13XD, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/937#issuecomment-476246837.
