### ISSUE TITLE
Bloob Bowl 2 writes gigabytes of log spam to ~/.xsession-errors

### ISSUE THREAD

**Issue by jwakely** [ValveSoftware/Proton#2457]
# Compatibility Report
- Name of the game with compatibility issues: Blood Bowl 2
- Steam AppID of the game: 236690

## System Information
- GPU: GTX 1060 6gb
- Driver/LLVM version:  nvidia 418.43
- Kernel version:  4.20.16
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/jwakely/875fc2b863129f1e1118fc7a7bb9490a
- Proton version: 3.16-8 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

After starting the game and then quitting as soon as the main menu appeared, the `steam-236690.log` file was 246MB and so github won't allow me to upload it!

This is a log file created by interrupting the game as soon as the first "Viewport hasn't been setted" errors were written to the log:

[steam-236690.log](https://github.com/ValveSoftware/Proton/files/3005350/steam-236690.log)

## Symptoms

The game writes the line "`Viewport hasn't been setted`" to the file `~/.xsession-errors` thousands of times per minute. Over the space of a few days it logged that line 3.8 billion times, and filled my home partition (which previously had 100gb free).

## Reproduction

In a terminal run `tail -f ~/.xsession-errors | grep setted` and then start the game. Watch the logs fly by ...

**Comment by kisak-valve** [comment]
Hello @jwakely, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1978#issuecomment-476367893.

**Comment by jwakely** [comment]
OK, sorry for the new report. As that one was tagged "Mesa drivers" I thought it might be best to keep it separate. I'll follow that one for updates.
