### ISSUE TITLE
Quell (344480)

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/Proton#2458]
# Whitelist Request
- Name of the game to be whitelisted: Quell
- Steam AppID of the game: 344480

## System 1 Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 418.56
- Distro version: Fedora Workstation 29
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Newbytee/a119a36b89e1481dbfae1d6f8e463392
- Proton version: 3.16-8 beta

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [X] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
This game was found in the 2019-07-31 whitelist update.

If you encounter an issue with this game, please search the open issues for 344480, and report any issues encountered with this game in separate issue reports, one issue per issue report.
