### ISSUE TITLE
Games don't start with Proton 4.2-1

### ISSUE THREAD

**Issue by Lastique** [ValveSoftware/Proton#2459]
# Compatibility Report
- Name of the game with compatibility issues: Any game running under Proton. E.g. We Happy Few.
- Steam AppID of the game: 320240

## System Information
- GPU: RTX 2080Ti
- Driver/LLVM version: Nvidia 418.56
- Kernel version: 4.18
- Proton version: 4.2-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Adding `PROTON_LOG=1 %command%` to the game launch options does not produce a `$HOME/steam-$APPID.log` file.

## Symptoms 

When the Proton version in the Steam setting is set to 4.2-1, no Proton-based game starts. The "Starting" window from Steam blinks for an instant and then nothing happens. When Proton 3.16-8 Beta is selected, the games start as expected. I have tried with multiple titles, "We Happy Few" for one example.

I suspect that Steam doesn't download Proton 4.2-1 runtime for some reason. There are various Proton versions in my game library folder, including 3.16 and 3.16 Beta, but there is no 4.2 folder. I tried restarting Steam client and changing the Proton version in the settings and checking for Steam client updates multiple times. Nothing helps, the Steam update says the client is at the latest version.

## Reproduction

1. Set Proton version to 4.2-1 in Steam Play settings.
2. Try running a Proton-based game, e.g. "We Happy Few".

**Comment by dlove67** [comment]
Per https://twitter.com/Plagman2/status/1110665993590759425 make sure you download it in "tools"

**Comment by Lastique** [comment]
I can confirm that the problem is indeed that Steam client does not download Proton 4.2 by default, even if it is selected in the settings. I can see this in the Library -> Tools list. I can download Proton 4.2 in that list, and after that the games begin to work again.

PS:
@dlove67 Thanks, I've just managed to find this out myself. It's still a bug in the Steam client though.

**Comment by dlove67** [comment]
@Lastique I think this would be a bug in https://github.com/ValveSoftware/steam-for-linux not proton, though.

Besides, Pierre-Loup Griffais is a "valve coder" so I think they're aware that the issue exists ;)

**Comment by Lastique** [comment]
Fair enough, I'll close this since this is not a Proton bug.
