### ISSUE TITLE
Lineage II (373700)

### ISSUE THREAD

**Issue by guglovich** [ValveSoftware/Proton#2460]
# Compatibility Report
- Name of the game with compatibility issues: Lineage 2
- Steam AppID of the game: other

## System Information
- GPU: Radeon RX460
- Driver/LLVM version: Mesa 19.0.0
- Kernel version: 5.0.4-arch1-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/guglovich/538223d0519c07ee47cea06ffe9056d1
- Proton version: 4.2-1

## I confirm:
- [+] that I haven't found an existing compatibility report for this game.
- [+] that I have checked whether there are updates for my system available.

## Symptoms 
Not running. Cannot run in this locale

## Reproduction
Tried in startup options LC_ALL=ru_RU.UTF-8 %command% and LC_ALL=C

Runs on Proton 3.16-8 Beta. But the font is partially displayed, even numbers.

**Comment by kisak-valve** [comment]
Hello @guglovich, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by guglovich** [comment]
@kisak-valve The game is third-party, so I do not know where to look for the log file. If he created at all.

**Comment by guglovich** [comment]
Works fine on 4.2-3
