### ISSUE TITLE
OneShot (420530)

### ISSUE THREAD

**Issue by leo60228** [ValveSoftware/Proton#2461]
# Compatibility Report
- Name of the game with compatibility issues: OneShot
- Steam AppID of the game: 420530

## System Information
- GPU:  RX Vega 12 (Ryzen 5 2400G integrated graphics)
- Driver/LLVM version:  4.4 Mesa 18.2.1
- Kernel version:  4.19.0-rc8
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/leo60228/66ff456c624027f074dc68cc2d867cd8
- Proton version: 3.16-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-420530.log](https://github.com/ValveSoftware/Proton/files/3015682/steam-420530.log)

## Symptoms 
Game opens a black window and closes about half a second later. Possible regression; according to several users, it worked fine on 3.7-3. Note that as part of standard gameplay on Windows/macOS, the game places a .exe file in Documents which must be launched as part of the story. This should work when added as a non-Steam game, but would likely prevent whitelisting.

## Reproduction
Install and launch the game.

**Comment by kisak-valve** [comment]
Hello @leo60228, when you get a chance to test further, please verify that the version of Proton you are testing is marked as installed in the list at Steam -> Library dropdown -> Tools.

**Comment by leo60228** [comment]
@kisak-valve Done.

**Comment by aeikum** [comment]
This happens because of this hideous chunk of code in Ruby: https://github.com/ruby/ruby/blob/trunk/win32/win32.c#L2497 We'll need a workaround in Wine, or possibly installing native ucrtbase will work.

**Comment by dreamer** [comment]
This game just got ported and is now [available natively on Linux](https://steamcommunity.com/games/420530/announcements/detail/1638657787407667872). I believe due to specific aspects of this game it is recommended to run native version over Windows version. Perhaps this issue should be closed?

**Comment by leo60228** [comment]
@dreamer Done.

**Comment by aeikum** [comment]
That's great! This one would've been a real challenge to do well in Proton...
