### ISSUE TITLE
FAudio multiple versions in 4.2

### ISSUE THREAD

**Issue by kiroma** [ValveSoftware/Proton#2462]
In `dist/lib64`, `libFAudio.so` differs from `libFAudio.so.0.19.03`.
Locally built FAudio has `libFAudio.so` and `libFAudio.so.0` being symlinks to `libFAudio.so.0.19.03`, so why not just do that?

**Comment by aeikum** [comment]
You're right, that is rather clumsy. I'll look at cleaning that up, thanks for bringing it up. FWIW the difference is the `.so` file is stripped and the others are unstripped.

**Comment by aeikum** [comment]
This was fixed in 4.2-2 by 898a4c5d77b769d8cd9a45d419587fb29e1d8ca2.
