### ISSUE TITLE
GTA 5 Script Hook

### ISSUE THREAD

**Issue by rado84-github** [ValveSoftware/Proton#2466]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Please add the GTA 5's ability to load user made scripts. When I used to play GTA 5 on Windows, it also loaded the custom script ( https://bg.gta5-mods.com/tools/script-hook-v ) I had downloaded for the single player campaign. GTA 5 with Proton doesn't load that script.

## Justification [optional] 
My game is licensed in Steam, so I use Proton to play it, not Wine.

## Risks [optional]
None that I know of. Either way the scripts (which sometimes can be trainers) are mostly meant for single player use.

## References [optional]

**Comment by kisak-valve** [comment]
Hello @IvoAndonov, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-477582419.
