### ISSUE TITLE
upgrade from 3.16-8 => 4.2.1 within steam, no game starts

### ISSUE THREAD

**Issue by dominikzogg** [ValveSoftware/Proton#2469]
Games like GTA V and Shadow of a Tomb Raider worked very well on (3.16-8). Some known glitches. But after i've upgraded Proton to 4.2.1 within Steam no Game starts. Downgrade solves the issue

**Comment by kisak-valve** [comment]
Hello @dominikzogg, this was previously discussed at #2459. Please go to Steam -> Library dropdown -> Tools and install Proton 4.2 in the list.

**Comment by kisak-valve** [comment]
"Fixed an issue where the Steam Client wouldn’t automatically update or download Proton before launching games through Steam Play" in the [2019-03-28](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1730979046038104727) Steam client beta update should have resolved this issue. Please opt into Steam's beta client.
