### ISSUE TITLE
Fullscreen "Into the Breach" freezes on alt-tab or after steam inventory popup during play (590380)

### ISSUE THREAD

**Issue by fcostin** [ValveSoftware/Proton#247]
game:
- title: into the breach
- version: Steam v 1.0.22 (4-23-2018)

steam client:
- built: aug 22 2018 at 22:20:42
- steam api: v018
- steam package versions: 1534979715

steam client configuration:
- steam play enabled for supported titles
- steam play compatibility tool: proton 3.7

environment:
- OS: ubuntu 16.04 LTS 
- machine: an old lenovo thinkpad T410
- processor: Intel® Core™ i5 CPU M 520 @ 2.40GHz × 4 
- graphics: Intel® Ironlake Mobile 
- ram: 7.6 GiB

to reproduce:

Enable proton in steam play settings in steam client
Launch "Into the Breach" from steam for linux client
Ensure "Into the Breach" is configured to run in fullscreen mode
Alt-tab to switch window to some other application
Alt-tab to switch back to the steam application (repeat until this brings the game window back into the foreground)

Behaviour: game interface is locked up, game ui is not animating, music is still playing

Expected behaviour: game interface doesn't lock up, game ui still animating.

Sometimes before locking up completely the fullscreen UI flickers with graphical artefacts but it is still responsive to input and animates. Repeatedly switching to another application and back again via alt-tab makes it freeze.

This lockup also seems to be triggered when steam displays a "you have a new steam inventory item!" popup via the steam overlay while the game is in fullscreen mode.

After the game has locked up, it is possible to exit the game by sending SIGTERM to all processes that mention "proton" and sending SIGKILL to all processes that mention "Breach".

**Comment by LiamDawe** [comment]
I think my issue is related here.

When loading the game, if I tell it to go fullscreen I just get a black screen with audio. When I quit it and reload, it says it's set to fullscreen but the window is just maximised. Trying it again, results in the same blackscreen.

Proton: Latest Beta 3.16-6
System info: https://pastebin.com/F5uKAs8N

Example video (unlisted, only viewable by the link): https://youtu.be/cJUnUcrALHc

**Comment by kisak-valve** [comment]
Hello @fcostin, noted at https://github.com/ValveSoftware/Proton/issues/204#issuecomment-616830044, this game was recently removed from the whitelist, and we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/204#issuecomment-616830336.
