### ISSUE TITLE
Blades of Time (208670) graphics layers missing

### ISSUE THREAD

**Issue by louisvd** [ValveSoftware/Proton#2471]
# Compatibility Report
- Name of the game with compatibility issues: Blades of Time
- Steam AppID of the game: 208670

## System Information
- GPU: GeForce GTS 450
- Driver/LLVM version: NVIDIA 390.116 (issue also occurred on 390.87)
- Kernel version: 5.0.3-200.fc29.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/louisvd/697b1909c65e95690c17229ddeed55e0
- Proton version: 4.2-1 (issue also occurred on 3.16-4)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The introduction video plays fine, but once the menu appears, and also during gameplay, Ayumi the Heroine's face becomes partly see-through.  Her teeth and jaw show, but her lips are not drawn.  You can see her hair through her head.

## Reproduction
This has happened since I bought the game.  First on Proton 3.16-4 and now on 4.2-1.  There have been driver updates and Steam client updates, but this issue has not gone away.

[steam-208670.log](https://github.com/ValveSoftware/Proton/files/3020405/steam-208670.log)
![20190101162633_1](https://user-images.githubusercontent.com/12628529/55197949-d6259700-51bc-11e9-84db-731fb007e797.jpg)
![20190329003438_1](https://user-images.githubusercontent.com/12628529/55197950-d6be2d80-51bc-11e9-8f4b-7e766851305a.jpg)
![20190329003446_1](https://user-images.githubusercontent.com/12628529/55197953-d756c400-51bc-11e9-929d-4c43053f9200.jpg)
![20190329003515_1](https://user-images.githubusercontent.com/12628529/55197955-d7ef5a80-51bc-11e9-99c3-7faec31765cd.jpg)

**Comment by kisak-valve** [comment]
Hello @louisvd, the previous issue wasn't game specific, but this one is. We're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1206#issuecomment-477800899.

**Comment by louisvd** [comment]
100%.  I saw those as whitelist requests, and since mine was a compatibility issue, I assumed a new thread was needed.  Thanks!
