### ISSUE TITLE
Force Proton on Windows host.

### ISSUE THREAD

**Issue by yurikoles** [ValveSoftware/Proton#2475]
# Feature Request
## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.
## Description 
It may be good to have option to force Proton on Windows host.
## Justification [optional] 
There is a lot of old titles that work incorrectly on modern Windows, e.g. 10.

## References [optional] 
#1197

**Comment by CuriousTommy** [comment]
I was under the impression that (official) wine does work on Windows. Has that changed recently?

**Comment by yurikoles** [comment]
Yes, it does work.

**Comment by Frontear** [comment]
Question:

> There is a lot of old titles that work incorrectly on modern Windows, e.g. 10.

Do you have any source which confirms that somehow, Wine actually makes these games work better than using the default compatibility mode?

**Comment by Leopard1907** [comment]
Dual boot to Linux then in the meantime.

**Comment by ghost** [comment]
Another way of going about it is to get the older Windows and install that to a vm making Wine/Proton unnecessary. Its a different point if Steam cannot be installed to the OS though.
