### ISSUE TITLE
[Feature Request] Include key translation patch from wine-staging

### ISSUE THREAD

**Issue by ritalat** [ValveSoftware/Proton#2477]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Some games have issues with non-us keyboard layouts on vanilla Wine and Proton. The most common issue I've faced is the inability to open the ingame console in games such as Stalker: Shadow of Chernobyl and Skyrim.

Wine-staging includes a patch that fixes the issue. I think that Proton should include this patch since being able to access the ingame console is important, especially when you are modding the games.

The patch in question:
https://github.com/wine-staging/wine-staging/tree/master/patches/winex11-key_translation
Related wine issue:
https://bugs.winehq.org/show_bug.cgi?id=30984

**Comment by Leopard1907** [comment]
Agreed. That is a serious issue for many Bethesda games.

https://bugs.winehq.org/show_bug.cgi?id=46102

**Comment by alasky17** [comment]
@ritalat There was some work for this issue included in Proton 6.3-1.  Are you still seeing the problem on the 6.3 branch?

**Comment by kattjevfel** [comment]
I tried this in 6.3-3 and I can open the console just fine now, even with a Swedish keyboard layout selected.

**Comment by ritalat** [comment]
Yeah, this seems to be fixed in 6.3. Thank you!
