### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by BloodyIron** [ValveSoftware/Proton#2479]
Can we please get Release Notes on the [Releases](https://github.com/ValveSoftware/Proton/releases) on Git Hub going forward?

**Comment by kisak-valve** [comment]
https://github.com/ValveSoftware/Proton/wiki/Changelog

**Comment by BloodyIron** [comment]
closed, re-opened, uhh?

**Comment by kisak-valve** [comment]
Hello @BloodyIron, indeed, I hit the wrong button.

**Comment by BloodyIron** [comment]
@kisak-valve well, to clarify, what I'm more meaning is when you go to the "Release" section ( https://github.com/ValveSoftware/Proton/releases ), if we could get the Release Notes there, that'd be swell. :)

You know, just like every other GitHub project XD

**Comment by aeikum** [comment]
I'm kind of new to this whole GitHub thing... I'll try to remember to look into it.

**Comment by minionprocyk** [comment]
FWIW I agree to add release notes to the releases section. I didn't even know there was a changelog until this thread.

**Comment by aeikum** [comment]
OK, easy enough. I'll try to do this going forward.

**Comment by BloodyIron** [comment]
Thanks! :D
