### ISSUE TITLE
Assassin's Creed II (33230) refuses to install

### ISSUE THREAD

**Issue by vjr2** [ValveSoftware/Proton#2481]
# Compatibility Report
- Name of the game with compatibility issues: Assassin's Creed II
- Steam AppID of the game: 33230/

## System Information
- GPU: GTX 1060, 6 GB
- Driver/LLVM version: nvidia 418.56
- Kernel version: 4.18.0-16-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/vjr2/77d2c0d0d5a0472ca11161e38ed27dbb
- Proton version: 4.2-1

## I confirm:
- [   } that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

Actually is nothing about the game itself. It's just that steam won't create the files. It will download the game, but since it wont create the files, exit the window prompt will uninstall the game. I don't know if this is an issue from Valve's client or not. But since Proton installs steam games I post this here. 

## Reproduction

Install Assassin's Creed 2 in Steam root folder. Creating files window will appear and it wont close. The game will just download and will finish. If you close the window of "creating files" the game will be automatically uninstalled. Since it's not a launching-issue I can't/won't submit a PROTON.log

**Comment by kisak-valve** [comment]
Hello @vjr2, downloading and managing game files is handled by Steam and this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5649. Closing as a duplicate.
