### ISSUE TITLE
Proton 4-2-1 Games think steam hasn't started

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#2484]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: GTX 1060
- Driver/LLVM version: Nvidia 418.43
- Kernel version: 5.0.5-1-MANJARO
- Link to full system information: https://gist.github.com/coreybruce/dcd2bec911594c9212d351ac2e7a3f98
- Proton version: 4-2-1

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
When using Proton 4-2-1 all games running through it think Steam hasn't started 

## Reproduction
Use Proton 4-2-1 on any non Linux game and you will get the same error (effects all games)

**Comment by fsyy** [comment]
did you install proton using library -> tools -> proton 4.2 already?

**Comment by coreybruce** [comment]
Didn't need to, it was already installed I assume from the Steam update

**Comment by fsyy** [comment]
nice, but i had the problem that it didn't install the correct proton version, didn't know if they fixed it.

but i don't have this problem, i'm on arch linux and i got the same gpu

**Comment by aeikum** [comment]
What games?

**Comment by coreybruce** [comment]
Hmm maybe I should try removing it and reinstalling it the manual way like mentioned

**Comment by coreybruce** [comment]
GTA 5 and age of empires 2 for example had the same message about Steam

**Comment by Evernow** [comment]
Weird. Exact same GPU, exact same kernel and OS. No issues. I updated to 4.2-1 like a day after it was initially released

**Comment by coreybruce** [comment]
Turns out despite it saying it was installed, it wasn't actually installed. We can close this but Steam really shouldn't show it unless it actually is installed and auto install it.
