### ISSUE TITLE
FEAR

### ISSUE THREAD

**Issue by childebert** [ValveSoftware/Proton#2486]
# Whitelist Request
- Name of the game to be whitelisted: FEAR
- Steam AppID of the game: 21090

## System Information

  OS : "Solus" (64 bits)
Nom du noyau : Linux
Version du noyau : 4.20.16-112.current
Version proton : 3.16-8 beta, 4.2-1
 
Pilote : NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
 Version du pilote : 4.6.0 NVIDIA 390.116
 Version OpenGL : 4.6

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [] There are no issues left open for this game.
- [] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @childebert, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/481#issuecomment-478736421.
