### ISSUE TITLE
The Elder Scrolls V: Skyrim vertical map scrolling issue w/Proton 4.2-1

### ISSUE THREAD

**Issue by Noskid23** [ValveSoftware/Proton#2487]
# Compatibility Report
- The Elder Scrolls V: Skyrim
- Steam AppID of the game: 72850

## System Information
- GPU: RX 470
- Driver/LLVM version: 4.5 (Compatibility Profile) Mesa 19.0.1 - padoka PPA
- Kernel version: 4.15.0-46-generic
- Link to full system information report as [Gist]:
https://gist.github.com/Noskid23/647724c620b55ceb5205628ba5e1ad55
- Proton version: 4.2-1

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
 Since upgrading to Proton 4.2-1 (from 3.16-8 Beta), map scrolling no longer works as it should (it did on every earlier version I tried). Horizontal map scrolling still works, but vertical is non-functional. I have tried older game save files to make sure it was not related to corruption in a saved game file. I then reloaded 3.16-8 Beta and can confirm that map scrolling again works as it should; changed back to 4.2 and it's broken again. As this seems to be a regression in 4.2, I wanted to report it. In case it helps, I've uploaded logs for 4.2.1 and for 3.16-8 - in each case I loaded the same save game file and attempted to scroll from top to bottom on the map.

I have over 400 hours on this title and the only other issue I have with it is that quitting to desktop locks up the system so I quit to menu and then kill tesv.exe process, this is with all versions of Proton.

I have tested this with Skyrim Special Edition (489830) also, and the effect is not present there, i.e. map scrolling works normally with 4.2-1 in this title.

## Reproduction
Change start options to use Proton 4.2-1 and issue recurs.

**Comment by kisak-valve** [comment]
Hello @Noskid23, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/460#issuecomment-478788948.
