### ISSUE TITLE
Games no longer work in windows after using them with proton on linux

### ISSUE THREAD

**Issue by mybaum** [ValveSoftware/Proton#2489]
I have some games installed on an external hard drive. I tried to run them trough proton and while that works for Linux, after doing that the games won't work in windows anymore. I also tried to verify the integrity of game files in windows to make them work there again, but that also didn't work. Is it possible to make them work on both using the same installation? Otherwise is it possible to make a backup of certain files and replace them with whichever you need for the current OS?

**Comment by kisak-valve** [comment]
Hello @mybaum, sharing Steam libraries across multiple OSes is not supported.

"Application files installed by Steam for Linux should not be shared (e.g. between Windows and Linux). This is a requirement of the Steam for Linux client." (from https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation)
