### ISSUE TITLE
GTAV: Stutter at any imput that would move the car/character

### ISSUE THREAD

**Issue by Alexmitter** [ValveSoftware/Proton#2491]
# Compatibility Report
- Name of the game with compatibility issues: GTAV
- Steam AppID of the game: 271590

## System Information
- GPU: Radeon VII
- Driver/LLVM version: AMD Radeon VII (VEGA20, DRM 3.27.0, 5.0.5-050005-generic, LLVM 9.0.0) (0x66af)
- Kernel version: 5.0.5
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Alexmitter/7ba77a3fd276586d15fa91ba95773994
- Proton version: 4.2-1 and 3.16-8

## Symptoms
Weird stutter at any car/character movement, that includes standing still with the car but moving the front tires. This issue appears with both Keyboard and Controller. It is very noticeable, FPS drops down to 30 at maxed out settings while being smooth and stable without any stutter while just driving without touching the steering. The issue is also very visible with the lowest settings.
The issue does not appear with Proton 3.7-8 Beta. Everything is smooth using it.
The issue appears in 4.2-1 and also the latest 3.16 Beta, it did not appear in older 3.16 versions.
Here is a video that shows me just standing still with the car and moving the steering, you can clearly see how the the FPS drops every-time I touch the steering and returning to butter smooth if I don't: https://youtu.be/uV6CEKBuN9I

Edit: This issue is exclusive to GTA5 and does not appear with any other game Ive tried with any of the as problematic listed Proton versions.

I have the feeling that it is a issue with the recent DXVK updates.

**Comment by kisak-valve** [comment]
Hello @Alexmitter, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-479160164.
