### ISSUE TITLE
Blackwell Deception (80360)

### ISSUE THREAD

**Issue by minisori** [ValveSoftware/Proton#2492]
# Whitelist Request
- Name of the game to be whitelisted: Blackell Deception
- Steam AppID of the game: 80360

## System Information
- GPU: NVIDIA GeForce GTX 1080 Ti
- Driver/LLVM version: NVIDIA 418.56
- Distro version: Debian GNU/Linux 9.8
- Link to full system information report as [Gist](https://gist.github.com/): [Full system report](https://gist.github.com/minisori/217be39a24ae8a58e7d70a022df8c481)
- Proton version: 3.7-8

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [X] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [X] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [X] Although I consider the gaming experience equal to Windows there are remaining issues:

Newer version of proton up to 4.2-1 crash the game at startup with the following message:
Warning Game Studio
Unable to determine startup path:
GetShortPathName failed. The specified game file might be missing.

With 3.7-8 is playable from start to finish.

I add both reports with the game working and crashing with newer versions.
[steam-80360-3.7-8.log](https://github.com/ValveSoftware/Proton/files/3036093/steam-80360-3.7-8.log)
[steam-80360-4.2-1.log](https://github.com/ValveSoftware/Proton/files/3036094/steam-80360-4.2-1.log)

**Comment by kisak-valve** [comment]
Hello @minisori, per "Corrected command line parameters for some games, including Wadjet Eye games like Blackwell Epiphany." in the Proton [4.2-2](https://github.com/ValveSoftware/Proton/wiki/Changelog#42-2) update, please retest the regression.

**Comment by minisori** [comment]
Working with the new version but it's generating very big logs.

[steam-80360-4.2-2.log](https://github.com/ValveSoftware/Proton/files/3038440/steam-80360.log)

**Comment by Dualnames1** [comment]
The game has been updated to have a fully working LINUX NATIVE, but for some reason for some users it's forcing them to use Proton, [can we unlist this and Blackwell Epiphany?] I ported the games to Linux and work directly for/with the publisher/creator of them, Wadjet Eye Games.

**Comment by kisak-valve** [comment]
Hello @Dualnames1, it sounds like some players have encountered https://github.com/ValveSoftware/steam-for-linux/issues/7023. If that's the case, then the affected users should be able to workaround that issue by going to the per-game properties, force the game to use the `Steam Linux Runtime` compatibility tool, and then optionally deselect the compatibility tool to get the Steam client to re-check the OS platform override that goes along with Proton.

Closing per the last comment.
