### ISSUE TITLE
High Fidelity - Instant Crash

### ISSUE THREAD

**Issue by Casuallynoted** [ValveSoftware/Proton#2496]
# Compatibility Report
- Name of the game with compatibility issues: High Fidelity
- Steam AppID of the game: 390540

## System Information
- GPU: RTX 2070
- Driver/LLVM version: 418.56
- Kernel version: 4.18.0-16-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Casuallynoted/90da1946bffb0399a3c702e755f7be66
- Proton version: 4.2-2

## I confirm:
- [Y ] that I haven't found an existing compatibility report for this game.
- [ Y] that I have checked whether there are updates for my system available.

(Would not let me attach it due to filesize so sharing via link in reply)

## Symptoms 
High Fidelity doesn't run/open any windows at all, and after a second completely crashes.

## Reproduction
Download High Fidelity using the latest proton, and run as is.

**Comment by kisak-valve** [comment]
Hello @Casuallynoted, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1716#issuecomment-479698822.
