### ISSUE TITLE
Slap City - Fullscreen Freezes Game

### ISSUE THREAD

**Issue by oct2pus** [ValveSoftware/Proton#25]
I am running Debian Buster, and with the steam beta version of Proton I have a variety of issues compared to running Steam in Wine Staging.

I had set the game to use Fullscreen, and now with Fullscreen, the game stalls until Gnome prompts me to kill the process.

Edit: I have a Radeon RX 570, and I am running Gnome under Wayland (So Steam is running under xWayland)

**Comment by oct2pus** [comment]
This can be fixed with `-force-d3d9` as a launch option, i'm not certain if this is also a windows issue.

**Comment by kisak-valve** [comment]
Hello @oct2pus, we'll be using one issue report to track each unofficially supported game title, so I've gone ahead and transferred this to https://github.com/ValveSoftware/Proton/issues/23#issuecomment-415536345.
