### ISSUE TITLE
FAudio not compiled with ffmpeg support in 4.2-2

### ISSUE THREAD

**Issue by kiroma** [ValveSoftware/Proton#2504]
Breaks audio in Warframe

**Comment by kisak-valve** [comment]
Closing in favor of #2082.

**Comment by foresto** [comment]
@kisak-valve I don't often see issues closed in favor of unresolved pull requests.  Was that deliberate, or did you think #2082 was an issue rather than a PR?

**Comment by kisak-valve** [comment]
Hello @foresto, no, it was not an error. Github handles issue reports and pull requests together, and allows discussion on the pull request. There was no value in fragmenting this topic.

**Comment by foresto** [comment]
Thanks for clarifying.
