### ISSUE TITLE
War Thunder (236390)

### ISSUE THREAD

**Issue by jarrard** [ValveSoftware/Proton#2515]
# Compatibility Report [UPDATED]
- Name of the game with compatibility issues: War Thunder (win64 exe)
- Steam AppID of the game: 236390

## System Information
- GPU: 1080TI
- Driver/LLVM version: 418.74
- Kernel version: 5.1.2
- Link to full system information report as [Gist]: [Gist](https://gist.github.com/jarrard/4b3a62eb815854793bdf49084c04a8ac)
- Proton version: 4.2-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

No proton log generated

## Symptoms 
1) Fails to launch. [solved]
2) Zombies with reshade4 dxgi.dll injector use.

## Reproduction
Launch win64/aces.exe within steam as a shortcut using proton library, it may require appid text file in folder! include dxgi.dll from reshade421 (or 411) in the exe folder.

## Additional error logs/messages
Under inspection of steam-native I see this as last line.

```
Starting app 236390
>>> Adding process 15566 for game ID 33554432
>>> Adding process 15568 for game ID 33554432
pid 15537 != 15536, skipping destruction (fork without exec?)
Game removed: AppID 236390 "", ProcID 15534 
Exiting app 236390
**No cached sticky mapping in ActivateActionSet.**
```

## Important Notes
-Win64 War Thunder works fine under Lutris/DXVK/Proton with reshade4 dxgi.dll injector (esync must be disabled). 
-ESYNC needs to be disabled as it causes login crashes/freezes. [now works under steamplay]

WHY not use the broken native opengl client you ask? that is why, its horribly broken! 
Also the native Vulkan render driver (alpha) has black screen AND crash issues so its no longer usable. 

I would like to figure out why this just doesn't work via Steam itself, be nice to not need to run via lutris all the time. Also might be worth figuring out why esync crashes the client sometime.

**Comment by kisak-valve** [comment]
Hello @jarrard, is a Proton log generated if you go to the game's properties and check `Force the use of a specific Steam Play compatibility tool`, then try to run the game with its regular play button instead of using a non-steam shortcut.

**Comment by jarrard** [comment]
It appears to get further but aces.exe closes down after 10seconds.

The log file is 470mb and compressed to 16mb so I can't post it.

The issue mainly with running it via launcher is for some reason gaijin auto deletes dxgi.dll which makes it hard to run reshade. (d3d11.dll might be alternative solution)

**Comment by kisak-valve** [comment]
For the esync part of the riddle, please run [`ulimit -Hn`](https://github.com/ValveSoftware/Proton/wiki/Requirements#fd-limit-requirements-systemd--240) and verify it is a high value and not 4096.

**Comment by jarrard** [comment]
Yeah I think I set that while ago, its 524288 on this system

Here is the log file compressed max with 7zip format (renamed to .zip)

Proton Log File: [test.zip](https://github.com/ValveSoftware/Proton/files/3051108/test.zip)

I should mention DXVK 1.1 currently causes a crash after login with this game so I've had to use DXVK 1.0.2 for the moment (lutris method). I don't think steam is at dxvk1.1 yet so probably not a issue (yet).

**Comment by Nayr438** [comment]
I am able to launch the game by setting the following Launch Commands
`"STEAMPATH/steamapps/common/War Thunder/win64/aces.exe" %command%`
Launching via the Launcher, results in an immediate crash, I didn't see any useful info from the logs on it.
You can however access the Launcher when prompted after using the above Launch Commands and it launches as it should. 

I can also only obtain a playable state when setting the render to opengl(test) through the launcher.

Using the default renderer has several graphical glitches rendering majority of the textures black or non existent with a unplayable framerate of around 15 FPS and constantly sets the Graphic Detail to Ultra Low due to its Video Card Check that I couldn't seem to get around.

I also have to manually kill "gjagent.exe" majority of the time.

I will try to get a Log up for directx, but proton isn't playing nice with creating them at the moment. 

Auto(Default DirectX)
 ![20190412004938_1](https://user-images.githubusercontent.com/49525644/56015169-9f23ab00-5cbd-11e9-90c6-b39ccea78b53.jpg)

OpenGL(test)
![20190412005248_1](https://user-images.githubusercontent.com/49525644/56015172-a1860500-5cbd-11e9-8bdb-5274d5659e64.jpg)

**Comment by jarrard** [comment]
Yeah opengl is the reason for running the game this way. The performance under Opengl is quite bad! 

gjagent.exe can be disabled in the launcher its auto update tickbox. 

Again game only works via lutris for me. 

Also are you making a shortcut with those launch commands? I can't imagine your overwriting steams hardlocked launcher.exe link for the game! 

"STEAMPATH/steamapps/common/War Thunder/win64/aces.exe" %command% = aces.exe launcher.exe, that's what your saying.

LASTLY, please always state if your using NVIDIA or AMD hardware, this is extremely critical information since both vendors get drastically different results with some games like this!

**Comment by jarrard** [comment]
"/mnt/GamesSSD/SteamLibrary/steamapps/common/War Thunder/win64/aces.exe" %command%

this line works for me in the war thunder steam link, it shouldn't however, and also it sets to ultralow due to graphics driver issue, seems DXVK isn't working correctly?  I do get the same graphical issues, I suspect wined3d is being used and not DXVK. odd

I think I know whats happening, its executing your linux systems installed wine for the first argument being aces.exe somehow.. That's what it looks like, and most people don't install DXVK on their default wine dependancy. So this is bypassing proton perhaps?

**Comment by jarrard** [comment]
Goto ~/.steam/steam/steamapps/compatdata/ delete 236390 if it exists.

If the game uses proton/steamplay it will create that number there for it. But it doesn't, so you've found a bug in the steamplay launch system to bypass proton basically. 

Obviously it only executes proton for the %command% and everything else is handled by linux, and in this case linux sees your trying to run a windows exe and just loads it up via the default system wine install which has not got DXVK installed.

If you install DXVK no doubt it will work, but its bypassing proton then so isn't a realistic solution to this problem.

I hope that helps explain whats going on. Also if you launch the game via the launcher it appears to not create a proton prefix, and just loads nothing instead. 

So only way to get proper behaviour is add a non-steam game line and point it to the exe (you need to set target after adding the shortcut due to steam bug), and then launching the exe from there, but as I've being saying it just fails to load.

What we want is the game to launcher correctly via either the default launcher.exe or by steams non-steam shortcut system, and for some reason this game glitches that process, quite odd indeed. Maybe someday someone will figure it out but I'm not smart enough to be that person. 


PS. my ~/.steam/steam/steamapps/compatdata/ folder is symlinked to my secondary SSD NTFS drive where games are launched from. As per proton wiki, (I had UID etc setup correctly, most other games work fine).,

**Comment by jarrard** [comment]
Just a update,

Game works (win64 exe via launcher) fine with Proton4.2-3 now so people can use that. HOWEVER there is a bug which prevents dxgi.dll injectors from working with this game and under proton such as reshade4. 

I have the game working with wine4.6 and esync off under Lutris AND with the reshade enabled. This problem could be related to esync somehow not letting reshade work when enabled with proton. Not sure if it affects other games.

The reason one might want to use reshade is to get better fsaa options or sharpening, for instance War Thunders TAA fsaa is not bad but it blurs everything too much and I found turning on reshade lumasharpen improves it quite a bit.
The ingame TPS sharpening is terrible, no idea what gaijin is doing with that failed filter.

PS. I'll close this for now since the reshade4 issue is a separate problem and until others come forward with a similar issue then I doubt a fix can get any traction.

**Comment by jarrard** [comment]
Instead of opening another ticket, I would like to reopen this one for the purpose of investigating why reshade dxgi.dll causes aces.exe to zombie when running under steamplay. 
Without the reshade4 dxgi.dll injector, it works fine, even with esync.

Here is the offending log file, very suspect! 
[dxgi.log](https://github.com/ValveSoftware/Proton/files/3185054/dxgi.log)

**Comment by telans** [comment]
Is anyone experiencing stuttering in the main menu? About every second it freezes for a few hundred ms. This doesn't happen ingame

**Comment by jarrard** [comment]
dxgi.dll still causes this title to zombie, no solution found except to avoid using steamplay.

**Comment by jarrard** [comment]
This game will no longer work in 1.91 patch as Warthunder is going to use EAC, rip playable framerate under Linux (I got poor visuals and bad fps under Linux native). 

Everyone will need to use the semi broken vulkan native render config from 1.91 onwards. Also under windows I dunno if EAC works with reshade but it probably won't so that's bad because Gaijin has the worse anti-aliasing and sharpening in any DX11 game I've seen!

**Comment by physios** [comment]
There it is.. update 1.91 and wine support for it.... is gone...

Cool night vision tho :DDDD :<

**Comment by jarrard** [comment]
I'll close this since the reshade issue was resolved, and the game does seem to load with proton for a while now in DX11 mode. Also it has DRM which kills wine, so no point discussing this further. Hope they fix up the vulkan native render path sometime (it has issues still).

**Comment by Kreyren** [comment]
@kisak-valve I am not sure if this is the correct place for this, please reassign if not

---

War Thunder started using `PROTON_LOG=1 PROTON_USE_WINED3D=1 DRI_PRIME=1 gamemoderun %command%` has graphical issues on my end in aircraft cockpit view:

![image](https://user-images.githubusercontent.com/11302521/85474282-b98d3000-b5b4-11ea-8816-78d74be78399.png)

LOG: not generated

### System info

```
kreyren@leonid 
-------------- 
OS: Kreyrock Linux 9999 Anubis x86_64 
Host: 20089 Lenovo G770 
Kernel: 5.6.0-18.1-liquorix-amd64 
Uptime: 1 day, 3 hours, 34 mins 
Packages: 1794 (dpkg), 153 (cave), 7 (flatpak) 
Shell: /bedrock/cross/bin/bash 5.0.16 
Resolution: 3200x1600 @ 119.94Hz 
DE: Xfce 
WM: Xfwm4 
WM Theme: Default 
Theme: Arc-BLACK [GTK2], Adwaita [GTK3] 
Icons: Cinnabar [GTK2], Adwaita [GTK3] 
Font: Sans 15 [GTK2], Cantarell 11 [GTK3] 
Terminal: xfce4-terminal 
Terminal Font: Monospace 12 
CPU: Intel i7-2620M (4) @ 2.701GHz [53.0°C] 
GPU: AMD ATI Radeon HD 6550M (DRM 2.50.0, LLVM 10.0.0)
GPU: Intel 2nd Generation Core Processor Family 
GPU Driver: i915 
Memory: 3826MiB / 7907MiB (48%) 
```

This is a system without Vulkan support

Steam is installed using Flatpak

dmesg: https://gist.githubusercontent.com/Kreyren/1862c1f2d58e6d396f630726937a62aa/raw/7cebb701dbc2dc70c00507ac5f42f48a92cd2aaf/gistfile1.txt

### Additional info

This behavior has been observed on `Proton 5.0-9`

The game seems to run on OpenGL 

![image](https://user-images.githubusercontent.com/11302521/85474795-741d3280-b5b5-11ea-803a-b0b31854dd8d.png)

Running the game on "Old videocard support" 

![image](https://user-images.githubusercontent.com/11302521/85476667-1985d580-b5b9-11ea-8f27-bc33cb264850.png)

causes the driver to halt on game loading:

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/11302521/85475865-26a1c500-b5b7-11ea-8bcd-b62620af0580.png)

![image](https://user-images.githubusercontent.com/11302521/85475876-2e616980-b5b7-11ea-95d0-050f9f2a270e.png)

![image](https://user-images.githubusercontent.com/11302521/85476472-a54b3200-b5b8-11ea-8cb8-01503b10546b.png)


![image](https://user-images.githubusercontent.com/11302521/85476464-a0867e00-b5b8-11ea-992f-3c516c126601.png)

</details>

I didn't notice any other issues in the game, without the cockpit view the game works seemingly on platinum

Same issue observed on `wine-5.10 (Staging)` packaged for Debian Bullseye by WineHQ

May be relevant: https://bugs.winehq.org/show_bug.cgi?id=35182

I tried to force dx11, but the game crashes with: 

![image](https://user-images.githubusercontent.com/11302521/85482775-e432b500-b5c3-11ea-9ed1-3e0fc4b223d1.png)

Seems that forcing dx11 allows me to capture a log: https://gist.githubusercontent.com/Kreyren/33505f41d6f6691f5c409bead01fe989/raw/78ddbb5bab38e7c666b7664d1dcb3754a6d2174d/gistfile1.txt

**Comment by jarrard** [comment]
That is WINE d3d translator and note really under development by valve itself (they work on dxvk/d9vk mostly). 

I thought AMD ATI Radeon HD 6550M supported Vulkan?

**Comment by Kreyren** [comment]
> That is WINE d3d translator and note really under development by valve itself (they work on dxvk/d9vk mostly).

Seems to be present in native client too see https://github.com/Kreyren/kreyren/issues/17

> I thought AMD ATI Radeon HD 6550M supported Vulkan?

Not to my knowledge, any source on that? afaik only GCN 1.0+ support vulkan

EDIT: FWIW apparently it's using same core as 7690M and it seems to work on 7690M BIOS, but i kept the original for now

**Comment by Kreyren** [comment]
Relevant: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3206

**Comment by Herostico** [comment]
So, i installed War Thunder for the first time in Pop_OS and after i press Steam login it crash, i got these errors:
![Screenshot from 2021-10-03 11-06-38](https://user-images.githubusercontent.com/73008601/135759096-612cb39e-6315-4dba-b130-dec896996bfa.png)

**Comment by kisak-valve** [comment]
Hello @Herostico, that error message looks like it's coming from a native linux build of the game, not from running this game with Proton. Support for the the native linux build comes directly from the game's devs, not this issue tracker which is for Proton.

**Comment by Herostico** [comment]
Ok. Sorry...
