### ISSUE TITLE
Stick Fight: The Game (674940)

### ISSUE THREAD

**Issue by oblitum** [ValveSoftware/Proton#2521]
# Compatibility Report
- Name of the game with compatibility issues: "Stick Fight: The Game"
- Steam AppID of the game: 674940

## System Information
- GPU: GTX 1080 TI
- Driver/LLVM version: nvidia 418.56
- Kernel version: 5.0.7
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/oblitum/565000b68b6483d325f7cb49a427825a
- Proton version: 4.2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available

## Symptoms 

This game worked fine before, but now I'm getting this error:

```
sh: /mnt/seagate/Steam/steamapps/common/Proton 3.7: No such file or directory
```

My current Proton is 4.2, I ignore why this game in specific is reaching for 3.7. I have uninstalled the game and removed `rm -rf /mnt/seagate/Steam/steamapps/common/StickFightTheGame` and `rm -rf /mnt/seagate/Steam/steamapps/compatdata/674940/`. There's only `common/Proton 4.2`. I reinstalled the game, still same behavior.

## Reproduction

Start the game

**Comment by kisak-valve** [comment]
Hello @oblitum, are you using the stable or beta branch of the Steam client? If you are using the stable client, please opt into Steam's beta client and retest.

**Comment by oblitum** [comment]
Hi @kisak-valve. I'm running the stable branch, I used the beta branch for a while, sometime back, until stable reached good enough state for Proton. I'm not willing to switch to beta branch because I had very bad experiences with sudden game deletion due to steam updates when using beta, and I'm not sure switching now will make the client consider games require updates and will redownload them, I really don't want risk missing a single game sized over a few GB on my connection.

**Comment by kisak-valve** [comment]
The beta client should have better management of Proton versions. As an alternative, please go to Steam -> Library dropdown -> Tools and verify that Proton 3.7 is installed in the list.

The version of Proton used by a game is currently determined by per-game override > whitelisted version > global override.

**Comment by oblitum** [comment]
Ah, OK. So this game in specific should have a Proton 3.7 override. I will install that Proton too, but I just wished it to run using my default Proton.

**Comment by oblitum** [comment]
Installing Proton 3.7 fixed the problem, gaming running fine.

**Comment by JustinSpedding** [comment]
The game runs fine for me in Proton 6.3-6, but does not load correctly in Proton Experimental as of 2021-09-21. The game goes fullscreen with a solid blue color as its initial loading screen. In 6.3-6, it finished loading in a second or two. In Experimental, it hangs on the solid blue screen before it can even display the main game logo. I have to kill the process to close it. The same issue happens in the custom 6.16-GE-1 if that makes any difference.

**Comment by alasky17** [comment]
@JustinSpedding could you get a basic log of the hang on experimental?  You can just add "PROTON_LOG=1 %command%" to the launch options and the log will show up in ~ by default.

**Comment by JustinSpedding** [comment]
[steam-674940.log](https://github.com/ValveSoftware/Proton/files/7219611/steam-674940.log)

Here is the log

**Comment by alasky17** [comment]
@JustinSpedding Just to be safe, could you try disabling MangoHUD?  Probably not the issue here, but I'm not having any trouble loading into the game.

**Comment by JustinSpedding** [comment]
@alasky17 Disabling mangohud does not help. Proton 6.3-7 works, but Proton Experimental and 6.19-GE-1 both still do not work.

I also noticed that while it is stuck at the solid blue loading splash screen, the `steam` process is pegged at 12% cpu and the `StickFight.exe` process is using the rest of the CPU. I have a 16-core AMD CPU, so I guess it is 2 CPUs used by one process and the rest used by the other.

According to system monitor, the `steam` process's command line is `steam /path/to/StickFight.exe` and the `StickFight.exe` process's command line is `Z:\path\to\StickFight.exe`. idk if that helps with debugging at all.

For reference, I am using an RTX 3080 with the 470 series drivers and Linux Mint 20.2.
