### ISSUE TITLE
Divinity: Original Sin 2 - Definitive Edition (435150)

### ISSUE THREAD

**Issue by Bamsey** [ValveSoftware/Proton#2523]
# Compatibility Report
- Name of the game with compatibility issues: Divinity: Original Sin 2 - Definitive Edition
- Steam AppID of the game: 435150

## System Information
- GPU:GTX950M
- Driver/LLVM version:nvidia 418. 56
- Kernel version:4.18.17
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:4.2-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-435150.log](https://github.com/ValveSoftware/Proton/files/3063703/steam-435150.log)

**Comment by kisak-valve** [comment]
Hello @Bamsey, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/413#issuecomment-481671536.
