### ISSUE TITLE
Agony UNRATED (879420)

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/Proton#2527]
# Compatibility Report
- Agony UNRATED
- Steam AppID of the game: 879420

## System Information
Distro: Linux Mint 19.1 Tessa (64 bit)
GPU: Vega 56
Driver/LLVM version: Mesa 19.1.0-devel/9.0.0
Kernel version: 5.0.5-050005-generic
Proton version: 4.2-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-879420.log](https://github.com/ValveSoftware/Proton/files/3070794/steam-879420.log)

## Symptoms 
The game works fine did not notice any issues, but when exiting the game it crashes with an error message "LowLevelFatalError [File D:\Engine\Engine\Source\Runtime\Windows\D3D11RHI\..."
![Untitled](https://user-images.githubusercontent.com/43387963/55996849-f1ae9880-5cb8-11e9-88ab-3d6797056d6a.png)

Included log of when I just loaded the game and then exited it

[steam-879420.log](https://github.com/ValveSoftware/Proton/files/3070817/steam-879420.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3070819/system_info.txt)

**Comment by kisak-valve** [comment]
Looks like this game would benefit from Media Foundation support.

**Comment by AwesamLinux** [comment]
## System Information
- GPU: RX VEGA 56
- Driver/LLVM version: 19.1.0+aco+git1563542492-3f3665b8d52-1bionic1 (Valve-Experimental PPA)
- Kernel version: 5.0.13-050013-lowlatency
- Distro version: Linux Mint 19.1 Tessa (64 bit) (Cinnamon Desktop)
- Proton version: 4.2-9
- System information: [system_info.txt](https://github.com/ValveSoftware/Proton/files/3414903/system_info.txt)

The game appears to be working fine now, no crash when exiting and also less stuttering with the experimental ACO drivers. Went through the files, and the videos that were easily accessed were: MPEG-4, AVC+AAC format. 

[media_info.txt](https://github.com/ValveSoftware/Proton/files/3414912/media_info.txt)

I'm closing this ticket because I'm no longer seeing issues. As for Media Foundation, the intro video at least plays, but there could perhaps be a problem with the unlocked extras/gallery videos after finishing the game. Some videos have been packaged into .pak files and I did not go through the effort extracting/examining those. 

Including a log of launching the game and then exiting without getting an error message
[steam-879420.log](https://github.com/ValveSoftware/Proton/files/3414917/steam-879420.log)
