### ISSUE TITLE
DOOM (379720) 2016 crashes at beginning of level 6.

### ISSUE THREAD

**Issue by duckinator** [ValveSoftware/Proton#2535]
# Compatibility Report

- Game: DOOM 2016
- Steam AppID: 379720

## System Information

- GPU: Intel(R) HD Graphics 630 (Kaby Lake GT2) x86/MMX/SSE2
- Driver/LLVM version: 3.0 Mesa 18.3.5
- Kernel version: 5.0.6
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/duckinator/c12bc2a71ddd30ce603321176ce797f6
- Proton version: 3.7-8

## I confirm:

- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Got through the first 5 levels; now, when it's part of the way through loading level 6 (Kadingir Sanctum/Into the Fire), it crashes.

## Reproduction

- Play through the first 5 levels.
- Attempt to continue playing.

**Comment by duckinator** [comment]
Also, the issue template said to drag/drop the `steam-<app id>.log` file, but it's apparently 38MB and GitHub disapproves.

**Comment by kisak-valve** [comment]
Hello @duckinator, the log should compress well in an archive.

Does a newer version of proton behave better if you right click on the game -> Properties -> and check `Force the use of a specific Steam Play compatibilty tool`?

**Comment by duckinator** [comment]
For 3.7-8 (what the default is), it does what I described above.

For the following, it doesn't even start:
- 3.7-8 Beta
- 3.16-4
- 3.16-8 Beta
- 4.2-2

**Comment by duckinator** [comment]
Here's zip files that each contain the logs for the Proton version mentioned in the file name.

- [steam-logs-4.2-2.zip](https://github.com/ValveSoftware/Proton/files/3077526/steam-logs-4.2-2.zip)
- [steam-logs-3.7-8.zip](https://github.com/ValveSoftware/Proton/files/3077527/steam-logs-3.7-8.zip)

**Comment by kisak-valve** [comment]
There's a good chance you've encountered https://github.com/ValveSoftware/steam-for-linux/issues/6045. Please opt into Steam's beta client and/or go to Steam -> Library dropdown -> Tools and manually install the Proton versions you want to use.

**Comment by duckinator** [comment]
Yup, you were right -- it hadn't downloaded the other Proton versions. I opted in to the Steam beta client, and it downloaded them, now.

However, still no luck: [steam-beta-logs-4.2-2.zip](https://github.com/ValveSoftware/Proton/files/3077644/steam-beta-logs-4.2-2.zip)

**Comment by duckinator** [comment]
(Corrected the AppID in the issue title.)

**Comment by aeikum** [comment]
`"GPU    : Intel(R) HD Graphics 630 (Kaby Lake GT2)\n"`

Possibly an Intel GPU issue, I'm not sure how well Vulkan is supported there.

**Comment by duckinator** [comment]
I just noticed that there were mesa updates available, so I did a system update to see if that'd help.

Now it never shows a window, then drops a `.dmp` file in /tmp.

Logs: [steam-379720.log](https://github.com/ValveSoftware/Proton/files/3081924/steam-379720.log)

ZIP file containing the `.dmp` file: [crash_20190415161810_2.zip](https://github.com/ValveSoftware/Proton/files/3081925/crash_20190415161810_2.zip)

**Comment by kisak-valve** [comment]
Hello @duckinator, your log and minidump look like a general Steam issue. Maybe try restarting Steam?

**Comment by duckinator** [comment]
I had already done so, but looks like restarting Steam a second time made it so it shows the window and doesn't crash.

It doesn't work even as well as it did before the update, though. I'm going to poke at it some more later and try to at least get back to the original problem, heh.

**Comment by hakzsam** [comment]
Are you still able to reproduce this problem?

**Comment by duckinator** [comment]
Hey, sorry, I couldn't manage to get it to even launch the game properly any more after that Steam update I mentioned before. This is still the case, 7 months later. (I tried again a moment ago, just to see.)

I wound up just dual-booting Windows 10 and playing it there. :woman_shrugging:

**Comment by duckinator** [comment]
So since nobody else has mentioned having my original problem here, you can go ahead and close it if you want, since I can't reproduce it anymore lol

**Comment by kisak-valve** [comment]
Closing per the last comment.
