### ISSUE TITLE
Tropico 4 wont start (57690)

### ISSUE THREAD

**Issue by MordragT** [ValveSoftware/Proton#254]
Tropico 4 will crash at start.
Steam Play is enabled for all titles.
My System:
Manjaro 17.1.12
Mesa 18.1.6 with R9 270x
Console Output:

> GameAction [AppID 57690, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
> GameAction [AppID 57690, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
> GameAction [AppID 57690, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
> GameAction [AppID 57690, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
> GameAction [AppID 57690, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
> Opted-in Controller Mask: 70
> Game update: AppID 57690 "", ProcID 28096, IP 0.0.0.0:0
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 28096 for game ID 57690
> GameAction [AppID 57690, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
> GameAction [AppID 57690, ActionID 2] : LaunchApp changed task to Completed with ""
> >>> Adding process 28097 for game ID 57690
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 28098 for game ID 57690
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 28109 for game ID 57690
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 28110 for game ID 57690
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 28113 for game ID 57690
> >>> Adding process 28115 for game ID 57690
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 28118 for game ID 57690
> >>> Adding process 28129 for game ID 57690
> >>> Adding process 28134 for game ID 57690
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 28143 for game ID 57690
> Game update: AppID 57690 "", ProcID 28109, IP 0.0.0.0:0
> Game removed: AppID 57690 "", ProcID 28109 
> No cached sticky mapping in ActivateActionSet.pid 28111 != 28110, skipping destruction (fork without exec?)

**Comment by thunder1410** [comment]
is python 2.7 installed?

**Comment by MordragT** [comment]
Yes some other games like Risen or Star Wars Battlefront 2 do work on my pc

**Comment by MordragT** [comment]
After I restartet my Pc and Steam updatet Tropico it works now fine so this can be closed

**Comment by kisak-valve** [comment]
Closing per the last comment.
