### ISSUE TITLE
Total War: Warhammer II (594570)

### ISSUE THREAD

**Issue by morvael** [ValveSoftware/Proton#2542]
# Compatibility Report
- Name of the game with compatibility issues: Total War: Warhammer II
- Steam AppID of the game: 594570

## System Information
- GPU: GTX 1070
- Driver/LLVM version: nvidia 418.56
- Kernel version: 4.15.0-47
- Link to full system information report as [Gist](https://gist.github.com/): 
https://gist.github.com/morvael/34f3b18dd6cecb292bbacbe3692d4c24
https://gist.github.com/morvael/3be30861960b89a8e59becd3383e3c67
- Proton version: 4.2-2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-594570.log.zip](https://github.com/ValveSoftware/Proton/files/3081692/steam-594570.log.zip)

## Symptoms

The game crashes when trying to run Windows version using Steam Play. The game runs without problems when using Lutris script. It seems Steam version of Wine/Proton lacks some libraries the game wants to find, whereas Lutris version of Wine/Proton installs them by default.

Please ignore the fact that there is dedicated version for Linux platform. The problem is multiplayer on Linux is non existent, and most people would prefer to run Windows version on Linux to be able to play multiplayer using Windows version, because that's where the playerbase is.

## Reproduction

Force the game to run using Steam Play, launch, observe crash on title screen (after starting the game from launcher).

**Comment by morvael** [comment]
The same issue troubles Total War: Warhammer (app id 364360), and will be probably solved together with this one, so I'm not opening another issue.

**Comment by morvael** [comment]
Lutris version is configured to use System Wine 4.5 (staging) and DXVK 1.0.2, without esync (as it says this version of Wine is not esync-enabled).

**Comment by Namerian** [comment]
Hi, how did you get the windows version to work with Lutris? I can't even get the launcher to start.

**Comment by morvael** [comment]
Well, when I was first trying to run it via Proton, I did all the steps from:
https://github.com/ValveSoftware/Proton/wiki/Requirements
Later, I did all the steps from:
https://github.com/lutris/lutris/wiki (How to: DXVK, How to: Esync, Wine, Wine Dependencies)
...and it worked. The biggest problems I had with downloading runner files from Lutris, the download stalled and never finished.

**Comment by Shyrak** [comment]
Hey @morvael, i've checked the Lutris install script and tried to execute it but I get the same result as executing it through steam play. Given your comment, I understand that you have wine version 4.5 installed "manually" on your system. Have you tried to run the prefix with another wine version to check if indeed is the wine version the reason you can run the game?

**Comment by morvael** [comment]
No, I've just followed Lutris instructions, and selected newest wine build for Steam Windows runner (don't remember exact Lutris terminology). I guess Steam built-in Proton is using an outdated version of Wine? Can it be even considered to be using Wine? I'm not that knowledgeable to tell.

**Comment by morvael** [comment]
Since I've reported this I have switched to some other version of modified Wine build that Lutris allows to select, one that supports esync. I get some 45 FPS on ultra with that version. Not great, not terrible :-)

**Comment by Shyrak** [comment]
> No, I've just followed Lutris instructions, and selected newest wine build for Steam Windows runner (don't remember exact Lutris terminology). I guess Steam built-in Proton is using an outdated version of Wine? Can it be even considered to be using Wine? I'm not that knowledgeable to tell.

well, as far as i know, Proton is wine + dxvk + Steam fixes, so the wine version they are running on top should have some effect. I've tried to run with Lutris with different versions and all seems to work fine with wine version 4.5 and above. Using older versions or even Proton (4.2-7) through Lutris results in a crash. I've not tested every version, but with 4.2 wine doesn't run (which i suspect is the basis for 4.2 Proton, but don't quote me on that) while 4.5 and 4.10 wine work. 

So, yeah, it seems that something that wine did between those versions unborked this game. Hope this info is usefull for next one googling this :)

**Comment by morvael** [comment]
Looks like it's working now on Proton 4.2-9!
![benchmark](https://user-images.githubusercontent.com/1133953/60300099-862aad80-992e-11e9-8ede-11995feb6376.png)
High settings with unit size set to Ultra.

**Comment by morvael** [comment]
Same settings on Windows (I usually play with Adaptive V-SYNC, but for this test I turned it off):
![benchmark_win](https://user-images.githubusercontent.com/1133953/60301768-8036cb80-9932-11e9-9175-1e0f47897c76.png)

**Comment by morvael** [comment]
I think this can be closed now.

**Comment by morvael** [comment]
FPS 53.1 on Proton 4.11.1 with 4.15.0-55-generic. Tried 5.0.0-20-mfutex but the benchmark failed to load.

**Comment by morvael** [comment]
After rebuilding dkms and rebooting managed to load benchmark on 5.0.0-20-mfutex. Got 52.8 FPS, so no impact here.

**Comment by morvael** [comment]
BTW, got 51.~ on Wine 4.12 in Lutris.

It's nice that the game works, but the impact on FPS is so high that you'll have to invest money saved on buying Windows in a better GPU to have the same level of FPS... I think 10% reduction would be acceptable, but 40% is a bit too much.

**Comment by ccasar** [comment]
In the past I was able to run Total War: Warhammer II via Proton flawlessly. A few days ago I reinstalled the game and now the game crashes (Creative Assembly launcher works, but the game does not launch just a black screen appears). 
I've tried different Proton versions (5.0-7, 5.4 GE-2, 4.11-13) all show the same behavior. Logging the startup with `PROTON_LOG=1 %command%` produced a 100MB log file:

[steam-594570.log.zip](https://github.com/ValveSoftware/Proton/files/4628007/steam-594570.log.zip) (The last line appears because I killed the process)

But there does seem to be an obvious error to me. I see the same crash when using X11 (i3) or wayland (sway). No mods are active.

Other games work fine via Proton (e.g. Doom Eternal, Brothers, Frostpunk). 

Steam system info:

Processor Information:
    CPU Brand:  AMD Ryzen 7 3700X 8-Core Processor             

Operating System Version:
    Kernel Version:  5.4.39-1-MANJARO

Video Card:
    Driver:  X.Org AMD Radeon RX 5700 XT (NAVI10, DRM 3.35.0, 5.4.39-1-MANJARO, LLVM 10.0.0)
    Driver Version:  4.6 (Compatibility Profile) Mesa 20.0.6
    OpenGL Version: 4.6

I know there is a Linux port, but the port usually lags quite far behind with game updates.

**Comment by ccasar** [comment]
In the past I was able to run Total War: Warhammer II via Proton flawlessly. A few days ago I reinstalled the game and now the game crashes (Creative Assembly launcher works, but the game does not launch just a black screen appears). 
I've tried different Proton versions (5.0-7, 5.4 GE-2, 4.11-13) all show the same behavior. Logging the startup with `PROTON_LOG=1 %command%` produced a 100MB log file:

[steam-594570.log.zip](https://github.com/ValveSoftware/Proton/files/4628007/steam-594570.log.zip) (The last line appears because I killed the process)

But there does seem to be an obvious error to me. I see the same crash when using X11 (i3) or wayland (sway). No mods are active.

Other games work fine via Proton (e.g. Doom Eternal, Brothers, Frostpunk). 

Steam system info:

Processor Information:
    CPU Brand:  AMD Ryzen 7 3700X 8-Core Processor             

Operating System Version:
    Kernel Version:  5.4.39-1-MANJARO

Video Card:
    Driver:  X.Org AMD Radeon RX 5700 XT (NAVI10, DRM 3.35.0, 5.4.39-1-MANJARO, LLVM 10.0.0)
    Driver Version:  4.6 (Compatibility Profile) Mesa 20.0.6
    OpenGL Version: 4.6

I know there is a Linux port, but the port usually lags quite far behind with game updates.

**Comment by Shyrak** [comment]
I have it working right now with proton 4.11-13.

I've attached the log file in case it shares any light on your issue. [steam-594570.log.zip](https://github.com/ValveSoftware/Proton/files/4628411/steam-594570.log.zip)

System info:
 CPU Brand:  AMD Ryzen 5 2600 Six-Core
Operating System Version:
    Ubuntu 18.04.4 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-99-generic
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 440.82
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime_0.20200417.0

**Comment by ccasar** [comment]
Same problem with 4.11-13 for me.

**Comment by ccasar** [comment]
Okay, after some more testing, this seems to be related to wayland.

After starting a Gnome session the game started and afterwards also launched under i3. Still does not work wayland+sway.

**Comment by class101** [comment]
If you are attempting to run it under Proton 5.13-6 or Proton 6.1-GE-2 you will need the following override

`WINEDLLOVERRIDES="*atiadlxx=d;"`

Enjoy

**Comment by ahjolinna** [comment]
for me both 1 & 2  won't launch at all tried v7.0-6, experimental and GE7-49.....haven't tested the 3rd game as I don't own it
I seem to get same error for both.


Log file for 1st one: [steam-364360.log](https://gist.githubusercontent.com/ahjolinna/dbdb5d5b9008d7563620527b3380bc81/raw/e2da1560934b66bb01da6a75f7db35dcf60aa101/steam-364360.log) 

Log file for 2nd one with experimental: [steam-594570.log ](https://gist.github.com/ahjolinna/dbdb5d5b9008d7563620527b3380bc81/raw/e2da1560934b66bb01da6a75f7db35dcf60aa101/steam-594570.log)


PS . I don't know if this is proton issue or [openSUSE MicroOS](https://microos.opensuse.org/) issue, as this is my first time using it for past few days....but other games I have tested before still work for me just fine, with some exception of few mmorpg (FF XIV, GW2 and SWTOR).


----

my system spec:

```
             .;ldkO0000Okdl;.                
         .;d00xl:^''''''^:ok00d;.            OS: openSUSE MicroOS
       .d00l'                'o00d.          Kernel: x86_64 Linux 6.1.12-1-default
     .d0K^'  Okxoc;:,.          ^O0d.        Uptime: 12h 47m
    .OVVAK0kOKKKKKKKKKKOxo:,      lKO.       Packages: RPM / Flatpak
   ,0VVAKKKKKKKKKKKKK0P^,,,^dx:    ;00,      Shell: bash 5.2.15
  .OVVAKKKKKKKKKKKKKk'.oOPPb.'0k.   cKO.     Resolution: 3072x1728
  :KVAKKKKKKKKKKKKKK: kKx..dd lKd   'OK:     DE: KDE 5.103.0 / Plasma 5.27.1
  lKlKKKKKKKKKOx0KKKd ^0KKKO' kKKc   lKl     WM: KWin_wayland
  lKlKKKKKKKKKK;.;oOKx,..^..;kKKK0.  lKl     GTK Theme: Breeze [GTK2],  [GTK3]
  :KAlKKKKKKKKK0o;...^cdxxOK0O/^^'  .0K:     Icon Theme: Papirus-Dark
   kKAVKKKKKKKKKKKK0x;,,......,;od  lKP      Disk: 16T / 21T (75%)
   '0KAVKKKKKKKKKKKKKKKKKK00KKOo^  c00'      CPU: AMD Ryzen 7 5700G with Radeon Graphics @ 16x 4.3GHz
    'kKAVOxddxkOO00000Okxoc;''   .dKV'       GPU: NVIDIA GeForce RTX 3060 Ti (Driver: v525.89.02)
      l0Ko.                    .c00l'        RAM: 12736MiB / 47963MiB
       'l0Kk:.              .;xK0l'         
          'lkK0xc;:,,,,:;odO0kl'            
              '^:ldxkkkkxdl:^'

**Comment by ahjolinna** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/2542#issuecomment-1446538928

okay I found the solution for my MicroOS issue or more exact SELinux issue

apparently I need to run this command: `sudo setsebool selinuxuser_execmod 1` to get the game run and other (mmo) games that had the same issue

more about it here: 
https://en.opensuse.org/Portal:MicroOS/Desktop#Steam_Proton,_Bottles,_WINE,_Lutris,_Android_Studio_emulator_not_working_from_flatpaks
