### ISSUE TITLE
No Man's Sky - Vulkan branch (experimental)

### ISSUE THREAD

**Issue by Rodhin** [ValveSoftware/Proton#2546]
# Compatibility Report
- Name of the game with compatibility issues: No Man's Sky
- Steam AppID of the game: 275850

## System Information
- GPU: GTX 980Ti
- Driver/LLVM version: nvidia 418.56
- Kernel version: 4.18
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Rodhin/98698055599b676e3e8c868604cc75cf
- Proton version: 4.2-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-275850.log](https://github.com/ValveSoftware/Proton/files/3085904/steam-275850.log)

## Symptoms 
Today the game received an experimental branch, they will switch from OpenGL to Vulkan. The OpenGL version runs like a dream, but the Vulkan version barely runs with 2-5 FPS. When the next big update is released for the game they will drop the OpenGL renderer completely.

More info about the Vulkan release and access to the experimental branch:
https://www.nomanssky.com/2019/04/vulkan-update/

## Reproduction
Switch to the experimental branch and launch the game.

**Comment by kisak-valve** [comment]
Hello @Rodhin, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-483738338.

**Comment by garpu** [comment]
GPU: GTX 1050ti
Driver/LLVM version: nvidia 418.49.04
Kernel version: 4.4.172
Link to full system information report as Gist: https://gist.github.com/garpu/20a8d8928b67f691d56b355c39b4ac28
Proton version: 4.2-2

Same issue, here. Bad fps, and it seems like no settings affect performance.  (I reset graphics options to default, around medium, where I was able to play on all high on the OpenGL renderer.)

**Comment by garpu** [comment]
Log from running it: https://gist.github.com/garpu/bd9d23b1821bbb5f4a6b5f95a9947d02
