### ISSUE TITLE
Squad - Public Testing (774941)

### ISSUE THREAD

**Issue by Lenart12** [ValveSoftware/Proton#2549]
# Compatibility Report
- Name of the game with compatibility issues: Squad - Public Testing
- Steam AppID of the game: 774941

## System Information
- GPU: RX 580
- Driver/LLVM version: 4.5 (Compatibility Profile) Mesa 19.0.1
- Kernel version:  4.19.34-1-lts
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Lenart12/ce9cd19d01408bb8c406247151259412
- Proton version: 3.16-8 Beta

## Proton log
https://gist.github.com/Lenart12/afe32b796cb41dab2e850c4335bc29bb
The whole file is >30MB (314374 lines) so i split it in 62 5000-line files because gist had problems processing the whole file alone. If you want the whole single file please contact me.
You can also find the compressed file [here.](https://github.com/ValveSoftware/Proton/files/3091138/steam-774941.log.tar.gz)

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

## Symptoms
After the splash screen game opens into a black window and crashes to desktop.

## Reproduction
Start the game.

**Comment by kisak-valve** [comment]
Hello @Lenart12, in the future, it's probably less hassle to throw large logs into an archive and drag and drop the compressed log into the comment box.

**Comment by Lenart12** [comment]
[steam-774941.log.tar.gz](https://github.com/ValveSoftware/Proton/files/3091138/steam-774941.log.tar.gz)

**Comment by Lenart12** [comment]
[A member](https://www.reddit.com/user/dudesomeone) on the reddit community found [a fix](https://www.reddit.com/r/joinsquad/comments/bewdmn/psa_for_v13_linux_players/) to the problem:

> Proton doesn't include the Windows Media Foundation libraries required to play the V13 intro video. There have been recent fixes upstream that may address this, but for now you can use this workaround. If the game is crashing after the splash screen, simply rename the "Movies" directory and it should launch. It's in your steam library directory. The default for me is here:
> 
> `$HOME/.steam/steam/steamapps/common/Squad - Public Testing/SquadUAT/Content/Movies`
> 
> After this, If it still crashes before it gets to the main menu, try putting this in your launch options (Right click -> Properties in Steam):
> 
> `PROTON_USE_WINED3D11=1 %command% `
> 
> This allowed the game to start and I was able to remove it after messing around with the graphics settings. Other than this the game still seems to work fine on Linux. I tested on Debian Buster with proton 4.2-3.
