### ISSUE TITLE
DOOM (379720) particles artifacts regression

### ISSUE THREAD

**Issue by Francesco149** [ValveSoftware/Proton#2550]
# Compatibility Report
- Name of the game with compatibility issues: DOOM (2016)
- Steam AppID of the game: 379720

## System Information
- GPU: r9 270x
- Driver/LLVM version: Mesa 19.0.2
- Kernel version: 5.0.7
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/358ef590f2425d5cb4abbf137e315199
- Proton version: 3.7-8

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-379720.log.gz](https://github.com/ValveSoftware/Proton/files/3091115/steam-379720.log.gz)

## Symptoms 
particles look like this:

![](https://media.giphy.com/media/TKe9vbcMxZs0WOy1XH/giphy.gif)

this is particularly noticeable in "Kagindir sanctum". I tried both Vulkan and OpenGL, the issue persists.

another interesting thing I noticed is that on a cold start the game runs at worse framerate than usual, but switching to 1080p and then back to 720p improves framerate for no apparent reason

these issues started appearing somewhere between january and now. the game was running great last december on the same hardware (but older kernel & mesa)

## Reproduction
Play any level that has particles for example "Kagindir sanctum"

**Comment by Francesco149** [comment]
it's a regression in mesa. I just downgraded mesa to 18.3.4 and it fixed the particles. so yeah, tl;dr if you use amdgpu avoid mesa 19

**Comment by romulasry** [comment]
I looked on https://bugs.freedesktop.org/buglist.cgi?quicksearch=doom I coudn't find the bug. Someone should post it.

**Comment by hakzsam** [comment]
Can you record a renderdoc capture of the problem with RADV please?

**Comment by Francesco149** [comment]
yep, here's the renderdoc capture. ```bunzip2``` to decompress it https://mega.nz/#!EV53mC5Q!vAugOwDn2iKqGaQ-KYNvfXg7oDNlhB3i74DvSnwdYD4

**Comment by Francesco149** [comment]
I have created a bug report on freedesktop: https://bugs.freedesktop.org/show_bug.cgi?id=110636

**Comment by Francesco149** [comment]
i just noticed my distro switched from llvm7 to llvm8 with mesa 19. it might be a llvm regression. currently recompiling against llvm7

**Comment by hakzsam** [comment]
It's a LLVM 8 regression, I'm working on.

**Comment by hakzsam** [comment]
Fixed with LLVM r360293, I'm not sure if the fix will be backported to LLVM 8,
but it's fixed with master now.

Note that if you want to use LLVM master, you need
https://reviews.llvm.org/D60457 to workaround a recent regression affecting SI.
That one should be pushed soon too.

**Comment by Francesco149** [comment]
great, thanks for the quick fix! now we wait for a stable release to include this. in the meantime I'll either package llvm master for myself or keep using mesa 18

**Comment by kisak-valve** [comment]
Upstream backport request: https://bugs.llvm.org/show_bug.cgi?id=41811

**Comment by kisak-valve** [comment]
Hello @Francesco149, please retest this issue with mesa built against llvm 8.0.1-rc2 or newer.

**Comment by kisak-valve** [comment]
Closing as this issue has been fixed in the video driver stack.
