### ISSUE TITLE
After install steam update 1.0.0.61 World of Tanks Blitz (444200) don`t work 

### ISSUE THREAD

**Issue by ihusky02** [ValveSoftware/Proton#2557]
# Compatibility Report
- Name of the game with compatibility issues:World of Tanks Blitz
- Steam AppID of the game:444200

## System Information
- GPU: <!GTX 860M -->
- Driver/LLVM version: <!418.56 -->
- Kernel version: <!4.18.0-7 Generic -->
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:4.2-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

When I try launch game, circle move for few seconds and nothing more
## Reproduction

[steam-444200.log](https://github.com/ValveSoftware/Proton/files/3096986/steam-444200.log)

After, while I back to proton version 3.7.6 everything works, it look like new chromium base is corrupted

**Comment by HonkingGoose** [comment]
Hi, we only use one report per unofficially supported game. This game is tracked at: https://github.com/ValveSoftware/Proton/issues/1293

@kisak-valve this is a duplicate.

**Comment by kisak-valve** [comment]
Hello @ihusky02, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1293#issuecomment-485042854.
