### ISSUE TITLE
Risk of rain 2 no longer starts with `4.2.3`

### ISSUE THREAD

**Issue by AlexandreBonneau** [ValveSoftware/Proton#2558]
# Compatibility Report
- Name of the game with compatibility issues: Risk of rain 2
- Steam AppID of the game: 632360

## System Information
- GPU: Vega 64
- Driver/LLVM version: Mesa 18.3.4
- Kernel version: 4.19.0-4-amd64
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 4.2.3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game *and that version of proton*
- [x] that I have checked whether there are updates for my system available.

## Symptoms
When clicking 'Play', Steam briefly shows that you are running the game, but no windows are shown and you are immediately back to the 'non-playing' state.

## Reproduction
Using Proton `4.2.3`, then click Play.

**Note: RoR2 works out of the box with `4.2.2` and `3.16-9 Beta`**

The [system information](https://gist.github.com/AlexandreBonneau/b3ec2a8bbdcac358319a91858661c55f).
The [steam-632360.log](https://gist.github.com/AlexandreBonneau/3ba9c3c9dcd28abcc67f6c4bcd4fcd0e) file.

**Comment by KorinFlakes** [comment]
Still working for me on 4.2-3, although I'm on Nvidia/Intel.
 
- GPU: GTX 1060 (6gb)
- Driver/LLVM version: Nvidia 418.43
- Kernel version: 4.19.32-1-MANJARO
- Link to full system information report as Gist: [System Info](https://gist.github.com/KorinFlakes/ee4cb7d022a7ab18c33675858d4d0a58)
- Proton version: 4.2.3
- Log file: [RoR2-Log](https://github.com/ValveSoftware/Proton/files/3097529/log.tar.gz)

**Comment by HonkingGoose** [comment]
Hi, we only use one report per unofficially supported game. This game is tracked at: https://github.com/ValveSoftware/Proton/issues/2476

@kisak-valve this is a duplicate.

**Comment by AlexandreBonneau** [comment]
ah, sorry, I was not sure about the wording there

**Comment by aeikum** [comment]
```
/mnt/espace3/SteamLibrary/steamapps/common/Proton 4.2/dist/bin/wineserver: error while loading shared libraries: libwine.so.1: wrong ELF class: ELFCLASS32
```
This is worrying. Do any games work in 4.2-3 for you?

**Comment by AlexandreBonneau** [comment]
Some yes ;

Works (as usual):
Castle crashers
DOOM 2016

Does not work anymore:
RoR2
Mortal Kombat Komplete Edition

**Comment by Skiski** [comment]
I've tried and I can play RoR2 with Proton 4.2-3.
I sometimes have the problem of games not launching, just quitting without showing anything, but usually, if I try again or restart Steam, it works.

**Comment by AlexandreBonneau** [comment]
@Skiski can you be more specific? Are you using an AMD Vega 64 card too? Which distro? Mesa version? etc.

**Comment by kisak-valve** [comment]
Hello @AlexandreBonneau, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2476#issuecomment-485210960.
