### ISSUE TITLE
Hello, have you seen these pathces before?

### ISSUE THREAD

**Issue by aaaaaaaaaaav** [ValveSoftware/Proton#256]
Hi, I was wondering if you have already seen these patches before, and if not, if you could consider adding these in?

https://github.com/Tk-Glitch/PKGBUILDS/tree/master/wine-tkg-git

**Comment by mkljczk** [comment]
They have, but they probably want to keep it as close to upstream wine as possible, valvesoftware/wine doesn’t even use wine-staging patches which I don’t understand…

**Comment by vanyasem** [comment]
esync patch is there. and well all other patches introduce regressions or are irrelevant. read https://github.com/ValveSoftware/Proton/issues/86 for more info about PBA patches

**Comment by aaaaaaaaaaav** [comment]
Ahh, alright. Thanks for the info!
