### ISSUE TITLE
Ferrari FGT 3in1 not working in Project cars 2 (378860)

### ISSUE THREAD

**Issue by s7relok** [ValveSoftware/Proton#2560]
# Compatibility Report
- Name of the game with compatibility issues: Project Cars 2
- Steam AppID of the game: 378860

## System Information
- GPU: 1070TI
- Driver/LLVM version: Proprietary Nvidia 418
- Kernel version: 4.18 ubuntu hwe
- Link to full system information report as [Gist](https://gist.github.com/): (not at home, can complete later, basically, up to date KDE neon 18.04 (ubuntu 18.04 with UTD KDE packages) with HWE stack installed, 8700k, 32GB RAM, 1070Ti with 418 proprietary driver, / installed on RAID 0 NVME SSDs and /home installed on a raid 0 SATA SSDs, linux  kernel 4.18)
- Proton version: 3.16

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game. (not for this problem)
(game is working, and keyboard controls works well, not tested with controllers like xbox controller bc I don't have one)
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Thrustmaster Ferrari FGT 3in1 is not recognized correctly

## Reproduction

Plug the wheel, start the game, start a race. Depending of the controller options in steam, the wheel, pedal or both are not working. The wheel works well in native game like F1 2017 and perfectly recognized by the system (all axis and buttons working in the KDE controller test). Already tried calibration and controller management options in steam. No option gives acceptable behaviour (pedals, wheel or both have no action in game)

**Comment by kisak-valve** [comment]
Hello @s7relok, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/908#issuecomment-485215159.
