### ISSUE TITLE
Painfully Slowdowns

### ISSUE THREAD

**Issue by inukaze** [ValveSoftware/Proton#2565]
## System Information
- GPU: GT 620
- Driver/LLVM version: nvidia 304.137
- Kernel version: 4.9.0-8-amd64
- Link to full system information report as [Gist](https://gist.github.com/): ¿?

MotherBoard : ASUSTeK | Model : M2N68-AM SE2 
SBES : American Megatrends | Version : 1409
Processor : AMD Athlon 64 X2 6000+ | Cache : 2 MB
Family : k8 | Cores : 2 , Speed : 3 GHz
RAM : 3,00 GB | 2 (1=1GB y 1=2GB)
DDR2 | Bus : 800 Mhz | CL : Desconocido
GPU : Nvidia GT 620, 2GB VRAM

- Proton version: All

## Reproduction
Load any game using 64-Bit wine and wineprefix and execute any videogame.

i can play 60 seconds perfectly (60 fps), but after that minute, i receive a painfully slowdown from 60 fps to 1 fps during 4 minutes. after that 4 minutes, i can play again a minute perfectly. and again the same, in an infinite loop.

This issue don't happen to me in a 32 Bits an versions before 2.0.0, i don't know the things really important change from wine 1.8.6 to 2.0.0. because of that i had request multiple times, from years ago links like this -> https://steamcommunity.com/discussions/forum/10/1771511442690947851/

the videogame don't matter, ever is the same with any title.

**Comment by ziabice** [comment]
Honestly, your PC specs are very low, what do you expect?

**Comment by tannisroot** [comment]
>nvidia 304.137
This driver is VERY outdated.

**Comment by GloriousEggroll** [comment]
https://github.com/ValveSoftware/Proton/wiki/Requirements

"Linux users with NVIDIA graphics cards should install the latest NVIDIA proprietary drivers; **418.49.0**4 or newer is required."

Although I don't think that will help your situation as your hardware is very, very old. Also would help knowing what game you're trying to run.

**Comment by Anti-Ultimate** [comment]
Your computer is overheating, that's why it slows down to 1FPS to cool down, then goes back up and slows down again.

With how old this system is I don't think it's even worth it to remove the dust tbh...

**Comment by kisak-valve** [comment]
Hello @inukaze, I don't see how this is a proton issue because you were encountering issues far before the Proton project was started. You may have better luck with the 390.xx series nvidia driver, which is the newest series that supports your video card.

**Comment by inukaze** [comment]
@ziabice : i expect proton let me choise if i want to use 64 Bits or 32 Bits. like i said before, in 32 Bits this don't happend. because for example Bloodrayne 2 works perfectly with Wine 3.7 32 Bits, the unique i just need to install LAV Video Filters to fix MPEG-1 video reproduction. but with Proton 3.7 this issue happend because is using 64 Bits

@tannisroot : its a very bad idea, because versions of driver >304 . don't work, the system never start because don't have access to Framebuffer, DRI, Aceleration 2D and/or 3D.

@GloriousEggroll : The same answer for tannisroot for you too. the versions of drivers superior of 304 don't work. i try to install using the package manager and/or manully using the run file, and the result is the same. the lastest version of driver supported for my GPU is "390.87"

@Anti-Ultimate : Don't my pc is not overheating. i make mantenience every weekend, ever is clean, and i said before, this don't happend in 32 Bits version

@kisak-valve : like i said, its heredate from Wine. i know the first versions of proton, don't called Proton, because, on some games like X-Blades, Gorky 17, Septerra Core, etc . its a modify version of Wine, version 1.8.5G with a lot of fixes like the reproduction of videos of format MPEG-1.

i expect valve considere my [**Suggestion**](https://steamcommunity.com/discussions/forum/10/1771511442690947851/)

To let the user, add a custom version of wine, for each game. using environment variables

**PATH
WINESERVER
WINELOADER
WINEDLLPATH
WINEPREFIX
WINEDEBUG**

because a lot of title works perfectly with wine : 

|                                                               |                   |                                    |
|:---:|:---:|:---:|
|**Title**| -> |**Wine:**
|Ragnarok Online International| -> |Wine 1.4-rc3|
|BloodRayne 1| ->| Wine 1.7.50|
|BloodRayne 2| ->| Wine 2.1.0|
|Commandos 1/2/3| -> | Wine 1.6.2 |
|Street Racing Syndicate| ->| Wine 1.2|
|Metal Gear Solid 2 Substance| ->| Wine 1.3.30|
|Resident Evil 4| ->| Wine 1.3.8|
|Silent Hill 3| ->| Wine 1.8.6|
|Resident Evil 3 : Nemesis| ->| Wine 1.5.4|
|Microsoft Pandora's Box| ->| Wine 1.6.2|
|紅蓮華 -ぐれんか-| ->| Wine 2.21-staging|
|Need For Speed Porsche 2000| ->| Wine 1.3.23|
|Dragon Age II| ->| Wine 1.8.6|
|Bejeweled 3| -> | Wine 1.9.21|

and i really dunno the team of proton, want to make old versions starting from wine 1.2 to make proton 1.2. i know wine work, because i had replace proton using version of wine, download from playonlinux, and replacing files, and preserving another files steam required. but is a not an efficient solution for me. 
[**Here my script for replace proton 3.7 by wine**](https://github.com/inukaze/maestro/blob/master/Videojuegos/Guion/Reemplazar_Proton37_Por_Wine)

Here my [**Mockup**](https://i.postimg.cc/qB8Yztzx/Inukaze-Maqueta-Wine-Steam.png) of my suggestion (Spanish Text on Image):
