### ISSUE TITLE
Bullet Witch (696180)

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/Proton#2566]
# Compatibility Report
- Name of the game with compatibility issues: Bullet Witch
- Steam AppID of the game: 696180

## System Information
Distro: Linux Mint 19.1 Tessa (64 bit)
GPU: Vega 56
Driver/LLVM version: Mesa 19.1.0-devel/9.0.0
Kernel version: 5.0.7-050007-generic
Proton version: 4.2-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
All the cut-scene videos are skipped, game works fine otherwise. Cut-scenes videos are stored with ".ssu" extention and can be played back with VLC, MediaInfo reports they are WMV.

Included log of from MediaInfo. 

[media_info.txt](https://github.com/ValveSoftware/Proton/files/3099996/media_info.txt)
[steam-696180.log](https://github.com/ValveSoftware/Proton/files/3099997/steam-696180.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3099998/system_info.txt)

## Reproduction
Just launch start the game (log is of me doing that and getting into gameplay without any cut-scenes being played back.

**Comment by kisak-valve** [comment]
`err:quartz:GetClassMediaFile Media class not found` looks like a line of interest in the log.

**Comment by HonkingGoose** [comment]
Whoops, I got my #issue-number mixed up when referencing from issue 2567. I fixed my reference in issue 2567, but I can't undo the wrong reference...

**Comment by AwesamLinux** [comment]
## System Information
- GPU: AMD Radeon RX 5700
- Driver/LLVM version: Mesa 23.0.0-git
- Kernel version: 5.17.9-302.fsync.fc36.x86_64
- Proton Version: proton-7.0-2
[system_info.txt](https://github.com/ValveSoftware/Proton/files/8800985/system_info.txt)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Good news: The publisher/developer videos now work, but the rest of the in-game videos do not.
Bad news: The actual game is now completely black except the HUD graphics as seen here:
![Screenshot_20220531_013112](https://user-images.githubusercontent.com/43387963/171068309-ad2eb837-cb69-4794-b4cc-e405c90f1bc3.png)

Logs:
[steam-696180.log](https://github.com/ValveSoftware/Proton/files/8800986/steam-696180.log)

**Comment by AwesamLinux** [comment]
## System Information
- GPU: AMD RX 5700
- Driver/LLVM version: Mesa 22.2.3
- Kernel version: 6.0.12-300.fc37.x86_64
- Proton version: proton-7.0-5

Re-tested the game and everything is working now, including the cut-scenes with audio and video. So I'm closing this issue as I'm no longer seeing any problems :tada: 

Including logs for reference:
[system_info.txt](https://github.com/ValveSoftware/Proton/files/10249995/system_info.txt)
[steam-696180.log](https://github.com/ValveSoftware/Proton/files/10249996/steam-696180.log)

**Comment by mlawther44123** [comment]
I dont know if people still look at this but im having an issue where i open the game and it works fine, but when i select new game and difficulty, during the load screen after the cutscenes it just closes with no explenation.
