### ISSUE TITLE
Recettear: An Item Shop's Tale (70400)

### ISSUE THREAD

**Issue by FurretUber** [ValveSoftware/Proton#2576]
# Compatibility Report
- Name of the game with compatibility issues: Recettear: An Item Shop's Tale
- Steam AppID of the game: 70400

## System Information
- GPU: Intel HD Graphics 520
- Driver/LLVM version: Mesa 19.1.0-devel (git-c4478889b7)
- Kernel version: 4.18.0-17-lowlatency
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/FurretUber/03c5915868c0c037be0f2216282aaae5
- Proton version: 4.2-3

[steam-70400.log](https://github.com/ValveSoftware/Proton/files/3101468/steam-70400.log)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

(This game had the issue 5, but somehow it no longer exists, so I'm opening a new issue).

## Symptoms 
It was noticed the game has no sound. Using `winetricks directmusic` on Recettear's prefix makes the sound work but with some delay.

It was noticed that the videos do not work. It has a video on main menu that plays after waiting for long enough, which is just skipped and returns to the main menu. Probably the same happens on the game credits.

This game currently only works properly when using the i965 Mesa driver. It has (seizure warning) [significant graphical errors](https://cdn.discordapp.com/attachments/457747189616214019/562094085565841438/recettear-iris-.webm) when using the iris Mesa driver.

Other than that, the game seems to work properly in all parts (store, city and dungeons).

## Reproduction
Open the game and wait in the main menu, it will be noticed there is silence only while there should be music and sound effects when changing the options. When the screen turns white it's when the video should start, but then it returns to the main menu immediately.

**Comment by BillFleming** [comment]
Just tested and the graphics issues don't show on up AMD GPUs.

**Comment by kisak-valve** [comment]
Hello @BillFleming, the flickering issue should also be brought to the attention of a mesa/iris dev.

Possible line of interest in the log: `fixme:quartz:Parser_QueryInterface No interface for {37d84f60-42cb-11ce-8135-00aa004bb851}!`

**Comment by FurretUber** [comment]
@kisak-valve Looks like this is a known issue. Doing a git bisect, the result is:
```
9d1334d2a0f983e175ffe371bee33f4ce048f910 is the first bad commit
commit 9d1334d2a0f983e175ffe371bee33f4ce048f910
Author: Kenneth Graunke <kenneth@whitecape.org>
Date:   Fri Dec 21 03:04:18 2018 -0800

    iris: Use copy_region and staging resources to avoid transfer stalls
    
    This is similar to intel_miptree_map_blit and intel_buffer_object.c's
    temporary blits in i965.
    
    Improves performance of DiRT Rally by 20-25% by eliminating stalls.
    
    Breaks piglit's spec/arb_shader_image_load_store/host-mem-barrier,
    by using the GPU to do uploads, exposing a st/mesa issue where it
    doesn't give us memory_barrier() calls.  This is a pre-existing issue
    and will be fixed by a later patch (currently out for review).

:040000 040000 b8dc11145b9f4a4f9667478a16fb4b55116765b8 b5b10f27d3819c55767f3a4825251fdce38cf5ed M	src
```

Edit: it seems this is the [same happening](https://bugs.freedesktop.org/show_bug.cgi?id=109969) with Microsoft Flight Simulator X: Steam Edition. While it's not Recettear, the bisect result is the same. So a bug report already exists on Freedesktop Bugzilla for iris.

**Comment by BillFleming** [comment]
@kisak-valve I was not trying to suggest that the mesa dev's shouldn't be told about this. I was just trying to be helpful to add a quick data point for comparison. To be even more helpful later I can dig up my save for this game and try to beat it on proton (including some lower spec system configs).

**Comment by FurretUber** [comment]
Good news! The `iris` driver issues are fixed. And the fix worked for many different games beyond Recettear. It is not only rendering correctly now, it is performing very well too.

**Comment by AwesamLinux** [comment]
Can confirm that the game skips videos and there is no sound or music. Graphics were fine for me though.

Distro: Linux Mint 19.1 Tessa (64 bit)
GPU: Vega 56
Driver/LLVM version: Mesa 19.1.0-devel/9.0.0
Kernel version:  5.0.10-050010-lowlatency
Proton version: 4.2-3

[media_info_music.txt](https://github.com/ValveSoftware/Proton/files/3134401/media_info_music.txt)
[media_info_video.txt](https://github.com/ValveSoftware/Proton/files/3134402/media_info_video.txt)
[steam-70400_proton-4.2-3.log](https://github.com/ValveSoftware/Proton/files/3134403/steam-70400_proton-4.2-3.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3134404/system_info.txt)

Videos are: WMV, VC-1 + WMA
Music are: WAV, PCM

**Comment by shoober420** [comment]
# Compatibility Report
- Name of the game to be whitelisted: Recettear: An Item Shop's Tale
- Steam AppID of the game: https://steamdb.info/app/70400/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.44
- Distro version: Arch
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia
- Proton version: 4.11-12

Graphics work great, but videos and sound are still broken.

https://github.com/ValveSoftware/Proton/issues/3469

**Comment by kisak-valve** [comment]
Hello @shoober420, the previously reported video playback issues need to be confirmed fixed before this game can be whitelisted.

**Comment by kisak-valve** [comment]
This is quite the blast from the past. There was two compatibility reports tracking this game, and either something went wrong with a duplication check back then or the current policy wasn't in place yet. The older issue report takes priority, so I've gone ahead and transferred the discussion from here to https://github.com/ValveSoftware/Proton/issues/5#issuecomment-1518720179.

Please continue discussing this game on #5.
