### ISSUE TITLE
The Elder Scrolls Online (306130) Framerate drops to unplayable levels.

### ISSUE THREAD

**Issue by bronso-of-ix** [ValveSoftware/Proton#2587]
The game launches and runs fine without any tinkering. My problem is that after just few minutes my framerate falls to a stable 10(ten)fps. I have tried turning off esync, tried different settings within the game and by editing settings file. Also checked all Proton versions available via Steam Play. Nothing prevents the framerate degradation except relaunching the game. I have no addons, it's a clean installation. Additionally no other game I play exhibits such behavior.

Proton:4.2-3
Distro:Ubuntu 18.10
Kernel:4.18.0-16-generic
RAM:8 GB

GPU Driver:NVIDIA 418.56
GPU:NVIDIA GeForce GTX 950M
CPU:Intel Core i5-6300HQ @ 2.30GHz

**Comment by kisak-valve** [comment]
Hello @dziad-cmentarny, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/556#issuecomment-485469899.
