### ISSUE TITLE
Spintires: Some particles are only rendered as black rectangles.

### ISSUE THREAD

**Issue by toqgit** [ValveSoftware/Proton#2589]
In game Spintires[263280] some particles are only rendered as black rectangles.
(whirling up leaves, burst mushrooms, mud pieces)

![black-particles](https://user-images.githubusercontent.com/22708447/56586904-d9a41680-65e0-11e9-99b5-83d450acda5b.png)

**Comment by kisak-valve** [comment]
Hello @toqgit, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/777#issuecomment-485819880.
