### ISSUE TITLE
[Whitelist] Space Invaders Extreme (744050)

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/Proton#2591]
# Whitelist Request
- Name of the game to be whitelisted: Space Invaders Extreme
- Steam AppID of the game: 744050

## System Information
Distro: Linux Mint 19.1 Tessa (64 bit)
GPU: Vega 56
Driver/LLVM version: Mesa 19.1.0-devel/9.0.0
Kernel version: 5.0.9-050009-generic
Proton version: 4.2-3

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

 Works out of the box with similar performance as windows. 
- Both fullscreen and wndowed mode works
- No problems to alt+tab between game and desktop
- No problems switching between fullscreen and windowed. 
- Was playable with Nintendo Switch Pro Controller (sans rumble, but that is not supported yet by any game yet as far as I know).

I have tried this game with many Proton versions since it became a thing, and it was working decently already with Proton 3.7-6.

[system_info.txt](https://github.com/ValveSoftware/Proton/files/3108771/system_info.txt)

## Issues:
- [X] I haven't experienced any issues.
- [X] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
This game was found in the 2019-07-31 whitelist update.

If you encounter an issue with this game, please search the open issues for 744050, and report any issues encountered with this game in separate issue reports, one issue per issue report.
