### ISSUE TITLE
Slap City - No Stock Icons

### ISSUE THREAD

**Issue by oct2pus** [ValveSoftware/Proton#26]
I am running Debian Buster, and this is an issue I also had running steam through wine staging, I am missing stock icons for all characters in Slap City.

Edit: I have a Radeon RX 570, and I am running Gnome under Wayland (So Steam is running under xWayland)

**Comment by Mikerr1111** [comment]
I think you should just add this to the list of your previous issue #25. Since it's for the same game.

**Comment by kisak-valve** [comment]
Hello @oct2pus, we'll be using one issue report to track each unofficially supported game title, so I've gone ahead and transferred this to https://github.com/ValveSoftware/Proton/issues/23#issuecomment-415536511.
