### ISSUE TITLE
Ability to run game trainers on single player games like witcher series

### ISSUE THREAD

**Issue by mritunjaymusale** [ValveSoftware/Proton#2604]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
On windows what I used to do was, launch the game and alongside that I use to launch trainers that use to give me the ability like infinite health, infinite resources, etc. in a nutshell enjoy the single player experience while modifying the game rules. Here on Linux I can't seem to figure out a way to launch the game and then run the trainer.exe file once the game is running.
## Justification [optional] 
Streamline the experience just like the way it is on windows. Wine doesn't have a concrete solution either.
## Risks [optional]
As long as it in single player there are usually no risks involved

**Comment by kisak-valve** [comment]
Hello @mritunjaymusale, this feature request is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5766. Closing as a duplicate.
