### ISSUE TITLE
Little Nightmares (424840)

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/Proton#2622]
# Compatibility Report
- Name of the game with compatibility issues: Little Nightmares
- Steam AppID of the game: 424840

## System Information
Distro: Linux Mint 19.1 Tessa (64 bit)
GPU: Vega 56
Driver/LLVM version: Mesa 19.1.0-devel/9.0.0
Kernel version:  5.0.10-050010-lowlatency
Proton version: 4.2-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Out of the box game crashes on launch with a window saying "Fatal Error!".

Launching the game with launch option "-onethread" the game appears to work perfectly. Solid 60fps+ performance and also Nintendo Switch Pro controller worked.

Including logs of both scenarios:
[steam-424840.log](https://github.com/ValveSoftware/Proton/files/3135208/steam-424840.log)
[steam-424840-onethread.log](https://github.com/ValveSoftware/Proton/files/3135209/steam-424840-onethread.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3135210/system_info.txt)

## Reproduction
Just launch the game

**Comment by NTMan** [comment]
I can confirm too that the game crashes without option "-onethread".
[steam-424840.log](https://github.com/ValveSoftware/Proton/files/3194857/steam-424840.log)
Proton version: 4.2-4

**Comment by AwesamLinux** [comment]
- GPU: RX VEGA 56
- Driver/LLVM version: 19.2.0-devel - padoka PPA/9.0.0
- Kernel version: 5.0.13-050013-lowlatency
- Distro version: Linux Mint 19.1 Tessa (64 bit) (Cinnamon Desktop)
- Proton version: 4.2-7
- System information: [system_info.txt](https://github.com/ValveSoftware/Proton/files/3311654/system_info.txt)

Re-tested the game with Proton 4.2-7 and bleeding edge Mesa drivers, the problem still remains with game crashing without "-onethread" option.

[steam-424840.log](https://github.com/ValveSoftware/Proton/files/3311656/steam-424840.log)

**Comment by BLaDZer** [comment]
Proton 5.10/5.13 still facing same problem

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX 5700
- GPU Driver: Mesa 21.0.0-devel (git-f89b29f 2020-11-12 focal-oibaf-ppa)
- Kernel version: 5.10.0-051000rc3-lowlatency
- Distro version: Mint 20 (64 bit) (Cinnamon)
- Proton version: 5.13-2 

**Retest Compatibility Report**

I confirm that the problem still persists, with option "-onethread" the game works. Without it launches to a black screen and a window pops up with an error message "Fatal Error!"

[steam-424840.log](https://github.com/ValveSoftware/Proton/files/5539728/steam-424840.log)
[steam-424840-onethread.log](https://github.com/ValveSoftware/Proton/files/5539730/steam-424840-onethread.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/5539731/system_info.txt)

**Comment by Leopard1907** [comment]
Same issue here. Proton 5.13-4. -onethread is needed as a launch option , otherwise game crashes with Fatal Error warning.

**Comment by joshas** [comment]
Works out of the box with Proton 6.3-4, no additional launch options required. Completed base game (no DLC) without any issues.

**Comment by AwesamLinux** [comment]
## System Information
- GPU: AMD Radeon RX 5700
- Driver/LLVM version: Mesa 23.0.0-git
- Kernel version:  5.18.8-200.fsync.fc36.x86_64
- Proton Version: proton-7.0-3
[system_info.txt](https://github.com/ValveSoftware/Proton/files/9074371/system_info.txt)

The game works now for me now too without needing any launch options, so I'm closing this issue :tada:

Including log of launching the game successfully:
[steam-424840.log](https://github.com/ValveSoftware/Proton/files/9074356/steam-424840.log)
