### ISSUE TITLE
ALLTYNEX Second (283840)

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/Proton#2626]
# Compatibility Report
- Name of the game with compatibility issues: ALLTYNEX Second
- Steam AppID of the game: 283840

## System Information
Distro: Linux Mint 19.1 Tessa (64 bit)
GPU: Vega 56
Driver/LLVM version: Mesa 19.1.0-devel/9.0.0
Kernel version:  5.0.10-050010-lowlatency
Proton version: 4.2-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
The game won't launch, window just opens up and exits immediately. 

The config tool does launch but the characters are just boxes like with the developers previous game #2625. Suspecting either locale is detected wrong or some ANSI/UTF character set problem.
![Screenshot from 2019-05-02 20-10-49](https://user-images.githubusercontent.com/43387963/57097202-710f1500-6d17-11e9-99f4-6c54b1e2208c.jpg)

[steam-283840.log](https://github.com/ValveSoftware/Proton/files/3139408/steam-283840.log)
[steam-283840-configtool.log](https://github.com/ValveSoftware/Proton/files/3139409/steam-283840-configtool.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3139410/system_info.txt)
[sislog.txt](https://github.com/ValveSoftware/Proton/files/3139391/sislog.txt)

## Reproduction
Just launch the game or the config tool

**Comment by kisak-valve** [comment]
Possible line of interest from the log:
`fixme:d3dx:d3dx9_mesh_OptimizeInplace D3DXMESHOPT_ATTRSORT vertex reordering not implemented.`

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX VEGA 56
- GPU Driver: 19.1.0+aco+git1566739320-db73bde35cc-1bionic1 (Valves PPA)
- Kernel version: 5.2.10-050210-lowlatency
- Distro version: Linux Mint 19.2 Tina (64 bit) (Cinnamon)
- Proton version: 4.11-3

**Retest Compatibility Report**

Same problems persist with newer Proton and Mesa. 

The configuration tools fonts are just boxes, and the game won't launch. Launching the game a black window opens up and then immediately exits. Tried also with d9vk, on launch I could see a black window with the d9vk overlay and then it exited.

[steam-283840-proton-4.11-3.log](https://github.com/ValveSoftware/Proton/files/3547409/steam-283840-proton-4.11-3.log)
[steam-283840-proton-4.11-3-d9vk.log](https://github.com/ValveSoftware/Proton/files/3547414/steam-283840-proton-4.11-3-d9vk.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3547410/system_info.txt)

**Comment by kisak-valve** [comment]
Possible line of interest from the log: `fixme:d3dx:d3dx9_mesh_OptimizeInplace D3DXMESHOPT_ATTRSORT vertex reordering not implemented`

**Comment by IanTrudel** [comment]
The game is now working with the latest version of Proton (4.11-11), installing **dxsdk_jun2010** using Protontricks and **disabling Steam Input** to allow the controller to work.

Note that DirectX End-User Runtimes (June 2010) would also work but it is no longer available as a trick. It can be downloaded from https://www.microsoft.com/en-us/download/details.aspx?id=8109

<details><summary>Screenshots</summary><p>

![20191228233922_1](https://user-images.githubusercontent.com/8844578/71552608-80418200-29ce-11ea-96aa-74adfca2165b.jpg)
![20191228233925_1](https://user-images.githubusercontent.com/8844578/71552610-83d50900-29ce-11ea-9dd9-b1c5a3b85a9b.jpg)
![20191228234019_1](https://user-images.githubusercontent.com/8844578/71552612-8b94ad80-29ce-11ea-8a38-2c743788bc5b.jpg)
![20191228234028_1](https://user-images.githubusercontent.com/8844578/71552620-9a7b6000-29ce-11ea-8819-a0e045e45e2a.jpg)
![20191228234044_1](https://user-images.githubusercontent.com/8844578/71552621-9d765080-29ce-11ea-80fe-55b134d04de0.jpg)
![20191228233909_1](https://user-images.githubusercontent.com/8844578/71552623-9f401400-29ce-11ea-9c82-19e917f99dbc.jpg)

</p></details>

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX 5700 ITX
- GPU Driver: Mesa 20.1.0-devel (git-5cc3ab0 2020-03-21 bionic-oibaf-ppa)
- Kernel version: 5.5.11-050511-lowlatency
- Distro version: 19.3 Tricia (64 bit) (Cinnamon)
- Proton version: 5.0-5

**Retest Compatibility Report**

Same problems remain with Proton 5.0-5, out of the box game does not launch. And the characters on the configuration tool are not readable. 

[steam-283840.log](https://github.com/ValveSoftware/Proton/files/4364486/steam-283840.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/4364487/system_info.txt)

**Comment by AwesamLinux** [comment]
## System Information
- GPU: AMD Radeon RX 5700
- Driver/LLVM version: Mesa 23.0.0-git
- Kernel version: 5.17.14-301.fsync.fc36.x86_64
- Proton Version: proton-7.0-3

## Re-test compatibility report
Game is working now out of the box, configuration tool is also readable. 
![Screenshot_20220618_040051](https://user-images.githubusercontent.com/43387963/174418645-e2610271-f61e-4a0f-a246-445c89fb39b3.png)

including log and system info for reference
[steam-283840.log](https://github.com/ValveSoftware/Proton/files/8932804/steam-283840.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/8932805/system_info.txt)

Closing this issue as I'm no longer seeing any problems.
