### ISSUE TITLE
Origin: Alice Madness Returns workaround

### ISSUE THREAD

**Issue by bendat78** [ValveSoftware/Proton#2635]
# Compatibility Report
- Name of the game with compatibility issues: Origin: Alice Madness Returns
- Steam AppID of the game: -

## System Information
- GPU: RX 560
- Driver/LLVM version: Mesa 19.1.0-dev (git-801c5f3319)
- Kernel version: 5.1.0-050100rc7-generic / Ubuntu 18.04.2
- Proton version: 4.2-3
- Origin version: 10.5.38.25027 - 0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Reproduction + Workaround on Ubuntu 18.04.2
1. Installing Origin
- Download: https://download.dm.origin.com/origin/live/OriginSetup.exe
- Create a directory for Origin and copy the setupfile there
- edit /etc/systemd/user.conf and /etc/systemd/system.conf so the line reads
DefaultLimitNOFILE=1024:1048576
- reboot
- verify with
ulimit -Hn
should be 1048576
- Open a shell and run
while true; do inotifywait Origin; chmod u+w Origin; done
in it (Origin being the directory you copied the setup file to) this keeps all files in that directory writable while the installer tries to create them read-only and then tries to write them :)
- Use Steam to run OriginSetup.exe by adding it as a non-steam game, choose Proton 4.2-3
- Run the installer through steam
- Choose the directory you created (and running the above shell for) as target for the installer
- Installing might not work at once, you might have to restart (kill steam, origin and wine processes before you try again)
- After installation change the properties of OriginSetup in Steam to run Origin.exe instead
2. Run Origin from within Steam (remember me on login seems to be the best bet to start Origin reliably) (btw: no need for running the shell anymore)
3. Download Alice
4. Start Alice
5. Enjoy

**Comment by kisak-valve** [comment]
Hello @bendat78, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/522#issuecomment-489325041.

**Comment by bendat78** [comment]
@kisak-valve I dont mind you closing, however this workaround does not apply to the steam version of Alice but the one on Origin, which might be different in itself. (i.e. mirrors edge on Origin doesn't work with this workaround and the steam version doesnt require it)
