### ISSUE TITLE
Mouse Control is lost

### ISSUE THREAD

**Issue by holzbit** [ValveSoftware/Proton#2636]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 301640 ( Zombie Army Trilogy )

## System Information
- GPU: NVIDIA GeForce GTX 1070 Ti
- Driver/LLVM version: NVIDIA 418.56
- Kernel version: 4.15.0-48-generic
- Proton version: 4.2-3
- Ubuntu 18.04

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

## Symptoms

Mouse control is lost after returning to the game menus / restarting after dying ingame. This does only happen if the graphics are running in flipping-mode.

## Reproduction

Enable flipping/g-sync in the nvidia graphics driver. Ensure flipping is active (turn off 2nd monitor, watch indicator). Start random multiplayer game. Get overrun by zombies.

**Comment by kisak-valve** [comment]
Previously mentioned at https://github.com/ValveSoftware/Proton/issues/168#issuecomment-440107101, possibly not a game-specific issue.

**Comment by holzbit** [comment]
Not sure if this is same issue. https://github.com/ValveSoftware/Proton/issues/168 talks about an invisible cursor while mouse input still works, but in this case all mouse input seems to be lost. The menus are only usable with the keyboard, and when back in action it is no more possible to move the camera around using the mouse.

**Comment by kisak-valve** [comment]
Thanks for clarifying. On second thought, what you've described could be a game-specific issue, so I've transferred this issue to https://github.com/ValveSoftware/Proton/issues/980#issuecomment-489347055 because we're using one issue report per unofficially supported game title.
