### ISSUE TITLE
ProtonDB needs changes / ProtonDB ratings atm are mostly useless

### ISSUE THREAD

**Issue by Lalarian** [ValveSoftware/Proton#2638]
Hello!

I am not talking about a specific game's compatibility here, but about ProtonDB and it's supposed worth.
First, for making my position clear:
By my definition, the intend for Proton is to make Linux as feasible as a gaming platform, as Windows. If it's otherwise than just tell me, and I will never come back here again.

Than there is ProtoDB. A great source for gamers on finding if their favorite game will run on Linux, before reinstalling their system and also good for developers who just want to contribute by improbing support for a game.

In regards to Proton's purpose this means, that game ratings on ProtonDB should reflect an average user's position.
The type of user that previously played on Windows or even on Console and who wants to play a game within 5 minutes after installation.
From ProtonDB's own definition, the rating scheme is as follows:

Platinum: Runs perfectly out of the box
Gold    : Runs perfectly after tweaks
Silver  : Runs with minor issues, but generally is playable
Bronze  : Runs, but often crashes or has issues preventing from playing comfortably
Borked  : Either won't start or is crucially unplayable

So as an example I now take the game "Civilization 4 (3900)" for consideration.
(https://www.protondb.com/app/3900)
If you read the issues thouroughly, or even tried it youself, you can easily tell that the game is by fact not playable using Proton, yet. You will inevitably come to the point where your screen becomes black and you can't see anything. Not even after saving and reloading the game. 
Not being able to progress in a game from a certain point is no minor problem for sure, but it's game breaking.
So there's no doubt that this behaviour matches the definition of "Borked" in the meaning that most people will never be able to finish this game using Proton. (Borked  : Either won't start or is crucially unplayable).
But still the game got an overall "silver" rating, telling people who are in search for this game, and also people who are at general probing on gaming on Linux, that there should be no problem preventing a playthrough. then they try and will be very disapointed, for saying the least. For sure this discrepancey will vastly hurt the reputation of Proton and gaming on Linux.

Of course this isn't an issue only for this game. In all games that don't run perfectly are affected by this. I think it's obvious why this happens. The average Linux users is far more experienced than the average Windows user or even console gamer. Many people just write a solution they found after fiddling around, or searching the web for hours and proceeding with trial and error until they have worked around the bug. But this clearly does not comply to the definition of ProtonDB.  Although those people are clever enough, for solving the problem, they aren't clever enough for remembering what Proton is intended to be. Also many might be just so happy about running this Windows game on their Linux machine, that they submit their rating based on their personal feeling instead of the official definition of ProtonDB.

So I take it for proven, that most ProtonDB submitters are not able for using the rating scheme as it was intended.

Thats why I suggest a major  rework. It should be simplified, for giving evaluable results.
All existing entries should be converted into a new rating scheme, with just two options.
Either:
a) The game runs and is possible to play through, with no fiddling outside maybe Steam options.
b) It doesn't

Otherwise I don't see that ProtonDB will be of any worth for long, because in it's current state it lacks reliabililty for the vast majority of games and users, thus makeing for a loss of the intended prupose.

Thank you!

**Comment by kisak-valve** [comment]
Hello @Lalarian, ProtonDB is not affiliated with Valve Software or this issue tracker.

**Comment by dreamer** [comment]
@Lalarian The closest thing to ProtonDB bugtracker is https://github.com/bdefore/protondb-data/issues

**Comment by Lalarian** [comment]
Thank you!
I will report there.
