### ISSUE TITLE
Cuphead not launching

### ISSUE THREAD

**Issue by dylanmtaylor** [ValveSoftware/Proton#2640]
I just get a pop-up that says:

Failed to initialize graphics.
Make sure you have DirectX 11 installed, have up to date
drivers for your graphics card and have not disabled
3D acceleration in display settings.
InitializeEngineGraphics failed

I'm running Antergos Linux (fully up to date) on GNOME with an AMD 2700X CPU and a Radeon VII graphics card.

**Comment by kisak-valve** [comment]
Hello @dylanmtaylor, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/304#issuecomment-489366624.
