### ISSUE TITLE
Onechanbara Z2: Chaos (446390)

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/Proton#2642]
# Compatibility Report
- Name of the game with compatibility issues: Onechanbara Z2: Chaos
- Steam AppID of the game: 446390

## System Information
Distro: Linux Mint 19.1 Tessa (64 bit)
GPU: Vega 56
Driver/LLVM version: Mesa 19.1.0-devel/9.0.0
Kernel version:  5.0.12-050012-lowlatency
Proton version: 4.2-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Trying to launch the game a window with a black screen pops up and then exits, nothing else happens. Tried different launch options but none made any difference.

Including logs from different Proton versions I tried with:
[steam-446390_proton-4.2-3.log](https://github.com/ValveSoftware/Proton/files/3144933/steam-446390_proton-4.2-3.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3144934/system_info.txt)
[steam-446390_proton-3.7-8.log](https://github.com/ValveSoftware/Proton/files/3144936/steam-446390_proton-3.7-8.log)
[steam-446390_proton-3.16-9.log](https://github.com/ValveSoftware/Proton/files/3144937/steam-446390_proton-3.16-9.log)
[OnechanbaraZ2_d3d11.log](https://github.com/ValveSoftware/Proton/files/3144938/OnechanbaraZ2_d3d11.log)
[OnechanbaraZ2_dxgi.log](https://github.com/ValveSoftware/Proton/files/3144939/OnechanbaraZ2_dxgi.log)
[media_info.txt](https://github.com/ValveSoftware/Proton/files/3144940/media_info.txt)

The codecs used by the games videos are: WMV, VC-1 + WMA

## Reproduction
Just launch the game

**Comment by kisak-valve** [comment]
Possible line of interest in the log `fixme:process:GetNumaHighestNodeNumber (0x22f744): semi-stub`

**Comment by AwesamLinux** [comment]
## System Information
- GPU: AMD RX 5700
- Driver/LLVM version: Mesa 22.2.3
- Kernel version: 6.0.12-300.fc37.x86_64
- Proton version: proton-7.0-5

Re-tested the game and everything is working correctly now. Game launches without problems, and intro/cut-scene videos are working with audio/video. 

So I'm closing this as I'm no longer seeing any problems :tada: 

Including logs of playing the game successfully just for reference:
[steam-446390.zip](https://github.com/ValveSoftware/Proton/files/10252157/steam-446390.zip)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/10252159/system_info.txt)
