### ISSUE TITLE
Ninja Blade (37010)

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/Proton#2643]
# Compatibility Report
- Name of the game with compatibility issues: Ninja Blade
- Steam AppID of the game: 37010

## System Information
Distro: Linux Mint 19.1 Tessa (64 bit)
GPU: Vega 56
Driver/LLVM version: Mesa 19.1.0-devel/9.0.0
Kernel version:  5.0.12-050012-lowlatency
Proton version: 4.2-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

Game works out of the box except that videos are just black. When starting a new game there is a video supposed to be played but you only see the subtitles, hitting escape gets you into gameplay.

- Fullscreen and windowed works
- Alt+tab and minimizing/maximizing game works
- Nintendo Switch Pro controller works

[media_info.txt](https://github.com/ValveSoftware/Proton/files/3145007/media_info.txt)
[steam-37010.log](https://github.com/ValveSoftware/Proton/files/3145008/steam-37010.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3145009/system_info.txt)

In the log I see "7634.490:0028:0029:err:quartz:GetClassMediaFile Media class not found"

Looks like a game that uses Quartz, and the video codecs are: WMV, VC-1 + WMA
Another game to add to the list #1464

## Reproduction
Launch and start a new game

**Comment by corvusd** [comment]
I only have one graphic issue with this game, a not serious. This issue in the body in this main character, very weird:
![20220620005412_1](https://user-images.githubusercontent.com/10695292/180052841-da24fa29-45b1-4c4e-9ab5-9a85b63659b3.jpg)
![20220620005432_1](https://user-images.githubusercontent.com/10695292/180052846-b95a0d4d-42d0-45f0-8655-e7b0823636cc.jpg)
![20220620005435_1](https://user-images.githubusercontent.com/10695292/180052851-91581d58-94cf-4fae-be60-1348231b533c.jpg)

I played in lutris with lutris-fshack-7.2-x86_64 and DXVK v1.10.2, D3D extras v2 and DXVK NVAPI v0.5.4. With the newer lutris wine version, I could see the FMV perfectly.

OS: Ubuntu 20.04.4 LTSKERNEL: 5.15.35-xanmod1CPU: AMD Ryzen 5 3400G with Radeon Vega GraphicsGPU: NVIDIA GeForce GTX 1660 SUPERGPU DRIVER: NVIDIA 510.60.02RAM: 16 GB

**Comment by AwesamLinux** [comment]
## System Information
- GPU: AMD RX 5700
- Driver/LLVM version: Mesa 23.1.2
- Kernel version: 6.3.8-200.fc38.x86_64
- Proton version: proton-8.0-3-rc1

Re-tested the game and it is **working now without problems**. Cut scene videos are working and also the graphics are rendered correctly (see below).  I'm closing this issue as I'm no longer seeing any problems with the game :tada: 

![20230623171136_1](https://github.com/ValveSoftware/Proton/assets/43387963/6525c5cc-2938-4be3-b6d8-fb96f72c26f6)

Including log of playing game successfully, just in case for future reference:
[steam-37010.zip](https://github.com/ValveSoftware/Proton/files/11849810/steam-37010.zip)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/11849811/system_info.txt)
