### ISSUE TITLE
Peregrin (573080)

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/Proton#2645]
# Compatibility Report
- Name of the game with compatibility issues: Peregrin
- Steam AppID of the game: 573080

## System Information
Distro: Linux Mint 19.1 Tessa (64 bit)
GPU: Vega 56
Driver/LLVM version: Mesa 19.1.0-devel/9.0.0
Kernel version:  5.0.12-050012-lowlatency
Proton version: 4.2-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Launching the game Steam client just says running for a few seconds and then nothing. Tried with different Proton versions:

[steam-573080_proton-3.16-4.log](https://github.com/ValveSoftware/Proton/files/3145767/steam-573080_proton-3.16-4.log)
[steam-573080_proton-3.16-9.log](https://github.com/ValveSoftware/Proton/files/3145768/steam-573080_proton-3.16-9.log)
[steam-573080_proton-4.2-3.log](https://github.com/ValveSoftware/Proton/files/3145769/steam-573080_proton-4.2-3.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3145770/system_info.txt)

## Reproduction
Just launch the game

**Comment by HonkingGoose** [comment]
Hi @AwesamLinux, I think this is the problem:
```
8300.910:0027:0028:warn:module:load_builtin_dll cannot open .so lib for builtin L"Steam2.dll": /mnt/Games/SteamLibrary/steamapps/common/Proton 4.2/dist/lib/wine/steam2.dll.so: cannot open shared object file: No such file or directory
```
I'll put it on my list.

**Comment by kisak-valve** [comment]
`fixme:process:GetNumaHighestNodeNumber (0x32ed68): semi-stub` in the log looks like a line of interest.

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX VEGA 56
- GPU Driver: 19.1.0+aco+git1565970353-650031018b4-1bionic1 (Valves PPA)
- Kernel version: 5.2.8-050208-lowlatency
- Distro version: Linux Mint 19.2 Tina (64 bit) (Cinnamon)
- Proton version: 4.11-2

**Retest Compatibility Report**

Game works out of the box with Proton 4.11-2

- Windowed/Fullscreen mode works
- Nintendo Switch Pro controller works
- Good performance

included a Proton log of some gameplay for future reference, closing this issue as I'm no longer seeing any problems.

[steam-573080.log](https://github.com/ValveSoftware/Proton/files/3512915/steam-573080.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3512916/system_info.txt)
