### ISSUE TITLE
Warhammer 40,000: Dawn of War II - Retribution (56400)

### ISSUE THREAD

**Issue by danich93** [ValveSoftware/Proton#2648]
# Compatibility Report
- Name of the game with compatibility issues: Warhammer 40,000: Dawn of War II - Retribution
- Steam AppID of the game: 56400

## System Information
- GPU: GeForce GTX 1070
- Driver/LLVM version: 4.6.0 NVIDIA 430.09
- Kernel version: 4.15.0-48-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Ohmu93/0cd21a887b1923eecd5ece1293d90d95
- Proton version: 4.2-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Log: 
[steam-56400.log](https://github.com/ValveSoftware/Proton/files/3146047/steam-56400.log)

## Symptoms

Playing the multiplayer game always leads to a synchronization error of some sort, failing and stopping the match for everybody in the session with a following message: "You have been defeated". Takes at most 5 minutes for this to happen.

## Reproduction

- Launch the game
- Join any MP game
- Play
- Observe a "You have been defeated" message within 5 min

**Comment by kisak-valve** [comment]
Hello @Ohmu93, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2517#issuecomment-489460826.
