### ISSUE TITLE
Space Channel 5: Part 2 (71260)

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/Proton#2649]
# Compatibility Report
- Name of the game with compatibility issues: Space Channel 5: Part 2
- Steam AppID of the game: 71260

## System Information
Distro: Linux Mint 19.1 Tessa (64 bit)
GPU: Vega 56
Driver/LLVM version: Mesa 19.1.0-devel/9.0.0
Kernel version:  5.0.12-050012-lowlatency
Proton version: 4.2-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
When launching the game there is just a black screen and nothing happens. Games configuration tool works though (launching the game through the config tool too results in a black screen).

[steam-71260_config.log](https://github.com/ValveSoftware/Proton/files/3153968/steam-71260_config.log)
[steam-71260_game.log](https://github.com/ValveSoftware/Proton/files/3153969/steam-71260_game.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3153970/system_info.txt)

## Reproduction
Just launch the game

**Comment by HonkingGoose** [comment]
Seems related to ```Steam2.dll``` support missing in Proton.
```
166860.085:002d:002e:warn:module:load_builtin_dll cannot open .so lib for builtin L"Steam2.dll": /mnt/Games/SteamLibrary/steamapps/common/Proton 4.2/dist/lib/wine/steam2.dll.so: cannot open shared object file: No such file or directory
```
I'll add it to my list.

**Comment by AwesamLinux** [comment]
## System Information
- GPU: AMD Radeon RX 5700
- Driver/LLVM version: Mesa 23.0.0-git
- Kernel version:  5.18.8-200.fsync.fc36.x86_64
- Proton Version: proton-7.0-3

Game is working now out of the box including the videos. One curious thing was that it launched the first time with Japanese audio, not sure if that is normal behavior for this game but it could be changed in the games configuration launcher (and it retained the setting)

I don't see any remaining issues, so I'm closing this :tada: . Including a log running this game successfully just for future reference:
[steam-71260.zip](https://github.com/ValveSoftware/Proton/files/9074000/steam-71260.zip)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/9073999/system_info.txt)
