### ISSUE TITLE
Call of Duty Modern Warfare 2 (10180) Single Player does not Start.

### ISSUE THREAD

**Issue by Sickday** [ValveSoftware/Proton#2668]
# Compatibility Report
- Name of the game with compatibility issues:

Call of Duty: Modern Warfare 2

- Steam AppID of the game:

10180

## System Information
- GPU: GTX 1070
- Driver/LLVM version: NVIDIA 430.09
- Kernel version: 5.1.0
- Link to full system information report as [Gist](https://gist.github.com/Sickday/33ca0b9e5839ae31ed9fb932f8998f51):
- Proton version: 4.2-3

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

## Symptoms 

Single Player does not launch. Steam indicates the game is running, but it does not start at all and eventually stops running with no error messages.

## Reproduction

Download the Game via Steam
Press "Play" once the download has completed.

[steam-10180.log](https://github.com/ValveSoftware/Proton/files/3168131/steam-10180.log)

**Comment by kisak-valve** [comment]
Hello @Sickday, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1037#issuecomment-491433730.
