### ISSUE TITLE
More modern msstyle as default

### ISSUE THREAD

**Issue by mkljczk** [ValveSoftware/Proton#267]
Using this windows95-like style which is default for wine might be discouraging for new users, they might really think that wine wasn't updated since these days (i'm serious, I know it might sound funny)… I recommend you to include the “Modern” theme that was recently added to ReactOS and set it as default. It's (in my opinion) not perfect, but much better than the current one…
How it looks vs. how it might look:
![wine95](https://user-images.githubusercontent.com/21127288/44524958-a6bb2300-a6df-11e8-906e-580a2eae3b63.png)
![winemodern](https://user-images.githubusercontent.com/21127288/44524961-a91d7d00-a6df-11e8-91ec-a8d2d9d5f98a.png)

**Comment by kisak-valve** [comment]
Hello @m4sk1n, the aesthetics of winecfg is outside the scope of this project and more appropriate for discussion in winehq's bug tracker.

**Comment by mkljczk** [comment]
I’m not talking about winecfg, but about all wine apps, proton user might see one dialog with this style and feel like the project has more in common with Windows 95 times… Typical wine user who installs everything manually and uses winecfg where he can change msstyle doesn’t need a nice style by default, but I think Proton user would prefer to have a nicer style…
