### ISSUE TITLE
install external programs to proton game?

### ISSUE THREAD

**Issue by codeman101** [ValveSoftware/Proton#2670]
# Feature Request

## I confirm:
- [x ] that I haven't found another request for this feature.
- [ x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description
Ability to add external programs to a proton game install

## Justification 
I've started to work on trying to make a mod manager native for Linux. Tonight it suddenly hit me that it wouldn't matter if the program had a native Linux version because it would still need to interact with the "proton bottle" of the individual game that uses wine anyway and you would therefore need the Windows version anyway. (since it would still need to interact with the Windows binaries of the game) I'm requesting that it be possible to do this for the sake of games like Skyrim.

Better example of what I mean is if I ran the windows version of steam via a wine prefix wine allows me to add any program I want to that prefix. I'm requesting this be made possible for proton prefixes.

**Comment by kisak-valve** [comment]
Hello @codeman101, this feature request is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5766. Closing as a duplicate.

**Comment by codeman101** [comment]
@kisak-valve 

Thanks for pointing that out to me. I will try to make a separate install of the steam client so I can use a fork I'll make of proton and the steam client without affecting my actual.


I also I read in a thread that you said your not a valve dev but do you know how to get in touch with them? It seems like all recent commits are by a volunteer.

P.S. Please ignore that reference I made to the other issue it's because I referenced this issue there because I was explaining over there why I stopped working on making that mod manager native for Linux.

@kisak-valve 

Edit: Actually since I can't make a fork of the steam client code I have no idea how I'd be able to help the proton repo with a fork since I don't want replace the upstream version that my steam-client is using and I don't want to make a VM of Linux since I already have everything installed on the host. Any ideas? I assume that I changed the title of my fork so that it didn't conflict with that actual version of proton in my steam client that would make my commits unmeragable hence why I'm stumped.

Edit2:

I realized I can use steam client on my laptop although it uses the open-source but hopefully that will still work for testing.
