### ISSUE TITLE
Errno::ENOENT: No such file or directory - nproc

### ISSUE THREAD

**Issue by garranaruto47** [ValveSoftware/Proton#2673]
When I run 'Make install' from the proton directory I get this error message:
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: <provider config: virtualbox>
Line number: 10
Message: Errno::ENOENT: No such file or directory - nproc

**Comment by garranaruto47** [comment]
I'm on MacOS 10.14

**Comment by dreamer** [comment]
@garranaruto47 Proton does not support OS X currently.

In case you don't care, on Linux `nproc` is part of GNU Coreutils - this program simply returns a number of CPU cores on stdout:

    $ nproc
    4

**Comment by aeikum** [comment]
Proton doesn't support macOS, but there's no reason you couldn't build the Linux version on it if you have a functioning Vagrant install.

@garranaruto47 I'd accept a PR for adding some kind of CPU count detection to the Vagrantfile that works on both macOS and Linux.

**Comment by aeikum** [comment]
This was fixed by 7f0b398e16d0d58a92fe98c7b231bb59b5d90e8b. You should be able to build Proton for Linux via Vagrant on macOS now.
