### ISSUE TITLE
Fallout 2 (38410) ignores ddraw.ini and possibly f2_res.ini

### ISSUE THREAD

**Issue by zopsicle** [ValveSoftware/Proton#2675]
# Compatibility Report
- Name of the game with compatibility issues: Fallout 2
- Steam AppID of the game: 38410

## System Information
- GPU: Intel Corporation Device 591b (rev 04)
- Driver/LLVM version: Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) x86/MMX/SSE2
- Kernel version: 4.19.34
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/chloekek/c03df6ba16e834a7420e8823dc2e9da7
- Proton version: 4.2

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-38410.log](https://github.com/ValveSoftware/Proton/files/3169539/steam-38410.log)

The logs hint at ddraw.dll being taken from C:\windows\system32\ddraw.dll rather than the patched version in ~/.local/share/Steam/steamapps/common/Fallout 2. I tried playing around with Wine DLL overrides in the Proton settings but I have too little knowledge about this.

## Symptoms 

The Steam release of Fallout 2 includes two mods (sfall and f2_res). They don't seem to be applied when running under Proton.

Changing settings in ddraw.ini and f2_res.ini (both found in ~/.local/share/Steam/steamapps/common/Fallout 2) don't seem to have any effect. I tried the following options in ddraw.ini and they did not have any effect:

 - SkipOpeningMovies=1 (this one is easy to test with)
 - ProcessorIdle=30 (but CPU usage was still over 150%)

Other than these mods not being applied the game seems to run normally and is playable, however constantly using over 150% CPU according to htop.

## Reproduction

When starting the game from Steam it asks whether you want to play Fallout 2 or the classic version. Both versions exhibit the issue described above.

**Comment by kisak-valve** [comment]
Hello @chloekek, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1774#issuecomment-491552367.
