### ISSUE TITLE
The Legend of Heroes: Trails of Cold Steel II (748490)

### ISSUE THREAD

**Issue by goldhawlk** [ValveSoftware/Proton#2677]
# Whitelist Request
- Name of the game to be whitelisted: The Legend of Heroes: Trails of Cold Steel II
- Steam AppID of the game: 748490

## System Information
- GPU: RX580
- Driver/LLVM version: 4.5.13536 Compatibility Profile Context 18.30.2.15
- Distro version: Ubuntu 16.04.6
- Link to full system information report as [Gist]: https://gist.github.com/goldhawlk/c2e9dffe0d289dfa89bbfbf788b288d2
- Proton version: 4.2-3

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @goldhawlk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2134#issuecomment-491598479.
