### ISSUE TITLE
GTA V - Crash Loop

### ISSUE THREAD

**Issue by gitshipdone** [ValveSoftware/Proton#2688]
# Compatibility Report
- GTA V
- 271590

## System Information
- GPU: GTX 1080ti
- Driver/LLVM version: nvidia 418.56
- Kernel version: 4.15.0-48-generic
- https://gist.github.com/bitbucket90/86673f9ef3a6f8e3569895ff51b7b066
- Proton version: 4.2.2

## I confirm:
- [/] that I haven't found an existing compatibility report for this game. (I have but none that address this and I am able to reproduce on an identical setup) 
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Game will launch, open windows, then back off and tell me it can retry in safe mode, the log has both methods in it, at any rate it will not launch.

## Reproduction

Review above, also log file below(14 day expiration);
https://www.transfer.sh/x9xlY/steam-271590.log

**Comment by kisak-valve** [comment]
Hello @bitbucket90, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-492392247.
