### ISSUE TITLE
Warframe (230410) Launcher DX10/DX11 not working

### ISSUE THREAD

**Issue by DiCA014** [ValveSoftware/Proton#2690]
When launching warframe via steam play, the launcher opens up but unable to launch the game with an error saying "Support for DirectX 9 has ended"

so i went to the launcher settings and found that the DX10 and DX11 option has been greyed out in the graphics API section.

The launcher works with lutris but i don't want to redownload the whole 20+GB of the game.

Is there a workaround if i want to play the game directly with steam play?

## System Information
- GPU: AMD A8-6410 with Radeon R5.
- Driver: Mesa 19.0.3
- Kernel version: 5.0.9-2
- Proton version: 4.2-4

**Comment by kisak-valve** [comment]
Hello @DiCA014, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/167#issuecomment-492465975.
