### ISSUE TITLE
wine prefix manager and multiple games in a same wineprefix

### ISSUE THREAD

**Issue by Weirdo1312** [ValveSoftware/Proton#2691]
# Feature Request

## I confirm:
- that I haven't found another request for this feature.
- that I have checked whether there are updates for my system available that contain this feature already.

## Description 
wineprefix manager and install multiple games in a same wineprefix
for example i wanna create a wineprefix for proton on steam called "Uplay" and install all my ubisoft games in that wineprefix
this also can save space because i can stop making bunch of wineprefixes for each game and i will not install uplay multiple times on my PC
and we need an option to just launch an specific exe file in that wineprefix (uplay lancher) without launching a game
ty so much for everything

**Comment by kisak-valve** [comment]
Hello @aligodlike, in general multiple requests in the same issue report is bad for any issue tracker, so only the first request (shared wine prefixes) will be tracked here and is a continuation of #1011.

The second part is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5766.

**Comment by Weirdo1312** [comment]
This isn't necessary anymore, since the games that needed this like cod:bo2 Zombies now work just wine.
