### ISSUE TITLE
Proton 4.2-4 causes flickering and breaks compat with Tokyo Xanadu eX+

### ISSUE THREAD

**Issue by jcfrosty** [ValveSoftware/Proton#2692]
# Compatibility Report
- Name of the game with compatibility issues: Tokyo Xanadu eX+
- Steam AppID of the game: 587260

## System Information
- GPU: Radeon VII
- Driver/LLVM version: Mesa 19.0.3/LLVM 8.0.0
- Kernel version:5.0.9
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 4.2-4

## I confirm:
- [x] that I have found an existing compatibility report for this game.
There is a whitelist request for this game. This game used to work perfectly. I've been playing it for over a month now. After recent upgrade to proton 4.2-4, its now flickering and unplayable.
- [x] that I have checked whether there are updates for my system available.

[steam-587260.log](https://github.com/ValveSoftware/Proton/files/3185155/steam-587260.log)

## Symptoms 
Tokyo Xanadu eX+ has been working great for some time now. Proton 4.X has been working with no issues until recently when 4.2-4 was released. Now the game flickers a black screen on and off. Now if you have an extra wide monitor it uses a still image to fill in the gap and the still image doesn't flicker, the HUD of the game doesn't flicker, only the game play portion flickers.

## Reproduction
upgrade from proton 4.2-3 to 4.2-4 and the game stops being playable.

https://gist.github.com/jcfrosty/938c89ecb73d38dfe032f2c129d4f978

Showing others have been able to play the game for quite some time now as well:
https://github.com/ValveSoftware/Proton/issues/1295

**Comment by kisak-valve** [comment]
Hello @jcfrosty, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1295#issuecomment-493051807.
