### ISSUE TITLE
Steam client: previous 4.x proton version is not listed

### ISSUE THREAD

**Issue by DFOXpro** [ValveSoftware/Proton#2694]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Add proton version 4.2-3 to the list of available steam play

## Justification [optional] 
Right now there is just 4.2-4 or 3.16-X versions
Enabling versions like 4.2-3 is important for (AMD)users who want to test the diferences between DXVK 1.0.X and 1.1.X(which depends on AMD changes) and also using the latest winehq 4.x branch which proton 3.16-9 does not have.

## Risks [optional]
N/A

## References [optional] 
Right now I'm testing Hellblade game with mixed(some glitches) results in 3.X proton version
and borked results on 4.2-4 results, I want to test variations in the DXVK 1.1 and 1.0 with the latest wine code, Right now I can't do that via steam.

**Comment by JakeStanger** [comment]
Having a download for at least 4.2-3 would be useful, I've had some peculiar issues since upgrading to 4.2-4.

**Comment by Zorrototo** [comment]
I was going to open similar feature request. What I would suggest is having one or multiple previous version available in the BETA tab of the current Proton properties. This way, when a Proton update comes, if any issue comes with the update, the user can easily revert back to previous update from the properties->BETA tab. This would be great this way in case of problem the user could simply go back and not wait for issues to be found and fixed. 
Having this feature would also avoid people the need to do 'complicated stuff' to have a fallback working recent Proton version in case of such issue with a coming Proton update.
