### ISSUE TITLE
Elite Dangerous on Vega 56 has shader problems

### ISSUE THREAD

**Issue by Byter09** [ValveSoftware/Proton#2701]
# Compatibility Report
- Name of the game with compatibility issues: Elite Dangerous
- Steam AppID of the game: 359320

## System Information
- GPU: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XL/XT [Radeon RX Vega 56/64] (rev c3)
- Driver/LLVM version: Mesa 19.0.4-1 / amdgpu
- Kernel version: 5.0.15-1-MANJARO
- [full system information report](https://gist.github.com/Byter09/fc8f00ede19a42d32f67963a09b55c6b)
- Proton version: 4.2-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-359320.log](https://github.com/ValveSoftware/Proton/files/3191838/steam-359320.log)

## Symptoms
- when in game, the lighting is way to bright
![ed](https://user-images.githubusercontent.com/16060697/57934746-a5123a80-78c0-11e9-83b0-a1404a6408c8.png)

## Reproduction
Create a new prefix with:
```
export WINEPREFIX=~/SteamLibrary/steamapps/compatdata/359320/pfx
rm -rf $WINEPREFIX
winetricks -q dotnet40 vcrun2015 win7 dxvk
```
The reason for this can be found here: https://github.com/redmcg/wine/wiki#the-official-build-of-proton-42-runs-ed

After that start Elite Dangerous with `VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/amd_icd64.json" PROTON_NO_ESYNC=1 %command%`
The VK_ICD part is supposedly workaround to use radv instead of amdvlk as reported [here](https://www.protondb.com/app/359320) to prevent exactly the problem I'm facing.
It does not matter though, even without any modified launch options the same problem occurs.

I believe, that the `VK_ICD_FILENAMES` variable is not being passed to the Elite Dangerous process itself from the launcher. I already used it in X4: Foundations and that worked great.

**Comment by kisak-valve** [comment]
Hello @Byter09, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/150#issuecomment-493482229.
