### ISSUE TITLE
Home Design 3D (420000)

### ISSUE THREAD

**Issue by Gryxx** [ValveSoftware/Proton#2706]
# Compatibility Report
- Name of the game with compatibility issues:Home Design 3D
- Steam AppID of the game:420000

## System Information
- GPU: RX 580
- Driver/LLVM version: 4.5 Mesa 19.0.3
- Kernel version: 5.0.11-1-default
- Link to full system information report as [Gist](https://gist.github.com/Gryxx/c0120d683ac2e3d5ac1241a4af8657ce):
- Proton version:4.2-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-420000.log](https://github.com/ValveSoftware/Proton/files/3194018/steam-420000.log)

## Symptoms 
3D view is not working 
(only white screen, nothing appears except for navigation buttons)

## Reproduction
Open project and switch to 3D view

**Comment by kisak-valve** [comment]
Hello @Gryxx, please verify you have the `libvulkan_radeon` and `libvulkan_radeon-32bit` packages installed.

**Comment by Gryxx** [comment]
I have "libvulkan_radeon", i haven't got "libvulkan_radeon-32bit". Installed, retested. Same result.
[steam-420000.log](https://github.com/ValveSoftware/Proton/files/3194829/steam-420000.log)

**Comment by ghost** [comment]
@Gryxx you also have the [lib32-vulkan-icd-loader](https://www.archlinux.org/packages/multilib/x86_64/lib32-vulkan-icd-loader/) ?

**Comment by Gryxx** [comment]
> @Gryxx you also have the [lib32-vulkan-icd-loader](https://www.archlinux.org/packages/multilib/x86_64/lib32-vulkan-icd-loader/) ?

There is no such package in my repositories. If that's not clear, I'm running OpenSuse Tumbleweed.
2D view
![image](https://user-images.githubusercontent.com/18641905/57983698-5d70e780-7a55-11e9-9908-690e8b53109e.png)
3D view
![image](https://user-images.githubusercontent.com/18641905/57983710-82655a80-7a55-11e9-9384-bcea3a1d8fee.png)

**Comment by ghost** [comment]
@Gryxx The package for you distro is called: [libvulkan_radeon-32bit ](https://software.opensuse.org/package/libvulkan_radeon-32bit)

**Comment by Gryxx** [comment]
> @Gryxx The package for you distro is called: [libvulkan_radeon-32bit ](https://software.opensuse.org/package/libvulkan_radeon-32bit)

Yes, it is installed

**Comment by Gryxx** [comment]
Retest using 4.2-5
[steam-420000.log](https://github.com/ValveSoftware/Proton/files/3216658/steam-420000.log)
Still no 3D preview

**Comment by ghost** [comment]
Do you get this issue with amdvlk too?

**Comment by Gryxx** [comment]
I don't know what amdvlk is

**Comment by Gryxx** [comment]
Works fine now- ready to close
