### ISSUE TITLE
Europa Universalis: Rome Gold Edition

### ISSUE THREAD

**Issue by assolutooccidentale** [ValveSoftware/Proton#2710]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/assolutooccidentale/07e798cb74e734328fbf18a560efbeca
- Proton version:

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Closing because there's no actionable information in this issue report.
