### ISSUE TITLE
Chat completely breaks games

### ISSUE THREAD

**Issue by UwUnyaa** [ValveSoftware/Proton#2713]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
I'd love to be able to receive chat messages without losing focus on the game. Besides severe performance issues whenever notifications pop up (which are normal for Steam in general), the chat window focuses whenever I receive a chat message, and rather than having my inputs go to the game, I end up writing nonsensical replies to messages. This ruins whatever I'm trying to play, and it can take a while for things to go back to being normal if they ever do.

The way to reproduce this is to play a game via proton and get a chat message from someone. In my case, I set a virtual desktop in the wine prefix, as otherwise windows won't get managed properly by dwm (adding a way to get into `winecfg` easily is another issue entirely).

## Justification [optional] 
Steam chat is tied to steam, so resolving this issue here makes sense.

## Risks [optional]
Not implementing this might end up annoying more people than me.

## References [optional] 
I haven't found any.

**Comment by kisak-valve** [comment]
Hello @DoMiNeLa10, this is a Steam client issue, not a Proton issue and is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5286. Closing as a duplicate.
