### ISSUE TITLE
Nothing works anymore

### ISSUE THREAD

**Issue by toluschr** [ValveSoftware/Proton#2714]
# Compatibility Report
 - Name of the game with compatibility issues: most games
 - Steam AppID of the game: -1

## System Information
 - GPU: GT 1060 6G
 - Driver/LLVM version: lib32-nvidia-utils 430.14-1, nvidia 430.14-1, nvidia-utils 430.14-1
 - Kernel version: linux 5.1.2.arch1-1
 - Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/toluschr/3de19087922ea2dbe28d53fe47600ab9

- Proton version: any

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. -> all rated gold+
- [x] that I have checked whether there are updates for my system available.

[steam-650500.log](https://github.com/ValveSoftware/Proton/files/3195457/steam-650500.log)
[nvidia-bug-report.log.gz](https://github.com/ValveSoftware/Proton/files/3195469/nvidia-bug-report.log.gz)
[dmesg](https://github.com/ValveSoftware/Proton/files/3195470/logfile.txt)

## Symptoms
Most of the games I tested and played before don't work anymore with any version of proton. I installed Steam with Lutris and that way everything runs just fine. The games I have tested are:
 - Wolfenstein II: The New Colossus: GPU hang, until reboot
 - Witcher 3: The game just exists
 - Brawlhalla: Black screen
 - Just Cause 4: Works fine
 - Wolfenstein 3D: Works fine
 - Others: Most just crash, not resulting in a GPU hang

## Reproduction
Start any game

## Ending
If anyone could help me resolve my issue, I would be very happy :)!

**Comment by kisak-valve** [comment]
Hello @toluschr, this sounds like there's an issue with your video driver. Does any vulkan application like `vulkaninfo` from `vulkan-tools` work?

**Comment by toluschr** [comment]
Yes. `vulkaninfo` works and gives me this output 
[vkinfo](https://github.com/ValveSoftware/Proton/files/3195532/vkinfo.log)

**Comment by kisak-valve** [comment]
A couple of things to try separately:
- Adding `PROTON_USE_WINED3D=1 %command%` to Witcher 3's launch options to test if the game runs without DXVK.
- Downgrading to nvidia 418.xx

**Comment by dreamer** [comment]
@toluschr Your link to gist with systeminfo is broken.

**Comment by toluschr** [comment]
I already tried downgrading my driver to 418, but xorg stopped working. I deleted my `shader cache`, `compadata` and `common` folder and also enabled virtual desktop mode, but nothing seemed to work. Sadly enabling `d3d11` didn't seem to work either. I will update the gist link as soon as possible.

**Comment by dreamer** [comment]
@toluschr Waiting for that system info to see if there's something surprising reported in there (runtime, weird versions of libraries).

Whenever a problem like yours happened to me, it was always a result of me messing with proton itself (e.g. broken user_settings file, broken dist or something similar) - it's easiest to detect such situations by running steam in a terminal and looking at stdout while running the game.

Another thing to consider is installation - how did you install and update Steam? Arch package? flatpak? snap? And where do you have set your library (did you perhaps move your only library to NTFS drive and it got mounted read-only after dual booting to Windows?). Did you change your XDG env variables? If yes - does `$ readlink ~/.steam/root` points to the location pointed by your changed XDG vars?

**Comment by toluschr** [comment]
Here you go! The URL got cut of by Github. Thanks for helping me out :)
[Steam Information](https://gist.github.com/toluschr/3de19087922ea2dbe28d53fe47600ab9)

**Comment by toluschr** [comment]
So I switched away from Arch to Fedora today. I can now confirm that everything works just fine out of the box without any tweaks required!

**Comment by dreamer** [comment]
Can confirm, Fedora is really stable :)

**Comment by minisori** [comment]
I know it's late but maybe it helps others. One month ago or so i had a similar problem and nothing was working the solution was to update SDL.
