### ISSUE TITLE
Mafia (40990) only configuration dialog starts

### ISSUE THREAD

**Issue by stsp** [ValveSoftware/Proton#2719]
# Compatibility Report
- Name of the game with compatibility issues: Mafia
- Steam AppID of the game: 40990

## System Information
- Radeon R9 380
- AMD Radeon (TM) R9 380 Series (TONGA, DRM 3.27.0, 5.0.9-200.fc29.x86_64, LLVM 7.0.1) (0x6939)
- Kernel version: 5.0.9-200.fc29.x86_64
- Link to full system information report as [Gist](https://gist.github.com/):
https://gist.github.com/stsp/e9bcfa94704e4ef137652841a270458c
- Proton version: 4.2-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-40990.log](https://github.com/ValveSoftware/Proton/files/3201737/steam-40990.log)

## Symptoms 
Only the settings dialog opens.
It has "Save and Exit" button.
Under windows, the subsequent start would launch
the game itself. But under proton, settings launches always.

## Reproduction
Just try to start the game.

**Comment by soredake** [comment]
Not a wine problem, see https://pcgamingwiki.com/wiki/Mafia#Game_doesn.27t_start.2FSettings_aren.27t_saved

**Comment by stsp** [comment]
Thanks for the tip.
Will try later and post back.

**Comment by stsp** [comment]
Sorry but how to install this?
The game folder is
`/home/stas/.local/share/Steam/steamapps/common/Mafia/Mafia`.
`rw_data.dll` there and in the patch are identical -
checked with md5sum. `d3d8.dll` and `d3d8.ini`
are not in the game folder, and putting them there
changes nothing. `scripts` and `models` dirs are
not in the game folder, and putting them there
changes nothing.
I think this patch should be installed with the
`modupdater` tool, which is not for linux.
Maybe someone can compare the patched and
unpatched versions, and release the patch as
an easy to install archive?

**Comment by soredake** [comment]
use WINEDLLOVERRIDES="d3d8=n,b" %command%

**Comment by stsp** [comment]
Whooah!
It work. :)
Thanks!
