### ISSUE TITLE
Permissions with shared games

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#2725]
'Proton: Permission denied" error launching shared Proton games but only for the user who don't own the game. It's maybe because Proton use a different folder for his things?

I have a shared folder for multiple users (with ACL), it works perfectly, the only problem is with Proton games, and only for the user who don't own the games.

**Comment by madacol** [comment]
In my case, it didn't showed any error, the game simply did not do anything.
I had to launch proton with the launch option `PROTON_LOG=1 %command%`

In the logs, the error comes from wine, telling that a file was not owned by me.

I was installing a game in a NTFS partition mounted by root (so owned by root), with all permissions open (777)

The problem went away when I mounted the disk with my user, but it was very hard to find the problem, a normal user would have give up, I spent a couple days thinking the game was corrupted and redownloading more than 30Gb

**Comment by kisak-valve** [comment]
Closing in favor of #4820 because the reporting user has turned into a ghost.
