### ISSUE TITLE
ARCH Compiling gives vulkan missing header.h problem

### ISSUE THREAD

**Issue by jarrard** [ValveSoftware/Proton#2727]
Just wanting to know if anyone can help me out building this with --no-steam-runtime because I wish to patch in script extender 64bit support myself since Valve probably isn't going to any time soon.

Non the less, the error so far. I'm not using the vagrant vm (no idea howto configure it).
I ran the 'source ~/Downloads/proton/vulkan/1.1.106.0/setup-env-sh' command to setup the sdk but it seems compiler doesn't detect it, is that not enough? 

```
rm -f ./dist/dist/bin/{msiexec,notepad,regedit,regsvr32,wineboot,winecfg,wineconsole,winedbg,winefile,winemine,winepath}
rm -rf ./dist/dist/share/man/
env LDFLAGS="-m32" CXXFLAGS="-m32 -Wno-attributes -std=c++0x -O2 -march=nocona -mtune=core-avx2 -mfpmath=sse -fwrapv -fno-strict-aliasing -g" CFLAGS="-m32 -O2 -march=nocona -mtune=core-avx2 -mfpmath=sse -fwrapv -fno-strict-aliasing -g" PATH="/home/riddick/Downloads/proton/obj-tools32/bin:/home/riddick/Downloads/proton/vulkan/1.1.106.0/x86_64/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" \
        make -C ./obj-vrclient32
make[2]: Entering directory '/home/riddick/Downloads/proton/obj-vrclient32'
winegcc -c -m32 -O2 -march=nocona -mtune=core-avx2 -mfpmath=sse -fwrapv -fno-strict-aliasing -g  -I/home/riddick/Downloads/proton/obj-tools32/include/ -I/home/riddick/Downloads/proton/obj-tools32/include/wine/ -I/home/riddick/Downloads/proton/obj-tools32/include/wine/windows/ -I/home/riddick/Downloads/proton/vrclient_x64 -I.   -o vrclient_main.o .././syn-vrclient32/vrclient/vrclient_main.c
In file included from .././syn-vrclient32/vrclient/vrclient_main.c:20:
.././syn-vrclient32/vrclient/dxvk-interop.h:39:10: fatal error: vulkan/vulkan.h: No such file or directory
 #include <vulkan/vulkan.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
winegcc: gcc failed
make[2]: *** [Makefile:223: vrclient_main.o] Error 2
make[2]: Leaving directory '/home/riddick/Downloads/proton/obj-vrclient32'
make[1]: *** [../proton/build/makefile_base.mak:897: vrclient32] Error 2
make[1]: Leaving directory '/home/riddick/Downloads/proton'
make: *** [../proton/build/makefile_base.mak:17: nested_make] Error 2
```

**Comment by ZachBacon** [comment]
what's your distro? If it's archlinux, you need vulkan-headers package

**Comment by jarrard** [comment]
antergos, which is basically arch linux, ill check for this package.

seems that has worked, however I'm not certain its going to compile the changes I did in dlls/ntdll/virtual.c (wine), maybe it would be better to just build wine separately and inject that into proton4.2-4, if that works.

**Comment by jarrard** [comment]
Yep looks like it ignored wine and didn't compile my changes, damn. Any tips?

--no-steam-runtime probably disables wine building I'm guessing. Anyway to tell it to just build wine? :)

**Comment by jarrard** [comment]
Ok I finally did it, interesting that proton compiles wine so fast, anyway the only file needed was ntdll.dll.so, all you do is apply the script extender changes to the correct source file and copy the compiled file over top of proton's version once done. 

getskseversion in the console will confirm if it works or not.
