### ISSUE TITLE
Allow URLs to open into Linux Browsers from Apps/Games

### ISSUE THREAD

**Issue by jarrard** [ValveSoftware/Proton#2731]
# Feature Request
Allow URLs to open into browsers

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
It would be nice if programs were allow to open URL links in form of http shttp etc into linux default browser. At present this feature exists in wine but not proton, I don't see why it should be removed. 

## Current Behaviour
If click on a button in an application that directs to a external browser, it will fail and do nothing, sometimes freeze the application as it waits for response. 

## Justification [optional] 
For use with applications like Nexus Vortex or Mod Organizer 2 and similar apps that are for games but require web browser access to gain access to specific features (api requests for example).  

Lets make proton more user friendly shall we?

**Comment by madewokherd** [comment]
I don't see any changes in Proton's Wine fork that look like they were intended to remove this. I think this is just a bug.

**Comment by kisak-valve** [comment]
I've got a hunch that Proton may need to unset the Steam runtime (or hand off the url to Steam to do the same) when calling the system-wide xdg-open for it to work as expected.

**Comment by madewokherd** [comment]
Is there a standard way for native Steam games to do this?

**Comment by jarrard** [comment]
Well standard web links like those in War Thunders Launcher news-feed work, its just stuff like mod manager API authentication and such don't (for proton, fine in wine standalone).

**Comment by kisak-valve** [comment]
@jarrard, what you asked for in this feature request (open URLs in the the system-default browser) and the issue you're encountered (some mechanism used by mod organizer 2 does not work) are distinctly different and I'm going to close this as invalid.

Please either grab the grab the compatibility report template and provide a proton log of the issue you're encountering and I can re-open this issue report afterwards, or discuss the issue you're seeing on the compatibility report of the game you're trying to use the third party tool with.

**Comment by jarrard** [comment]
I only used MO2 as an example of where this feature was failing to work, but whatever.
