### ISSUE TITLE
How to run " Grid 2 (44350) "

### ISSUE THREAD

**Issue by Pakrohk** [ValveSoftware/Proton#2743]
https://github.com/ValveSoftware/Proton/issues/1647#issuecomment-473953948
--------------------------------------------------
https://github.com/ValveSoftware/Proton/issues/1647#issuecomment-474460265
--------------------------------------------------
https://github.com/ValveSoftware/Proton/issues/1647#issuecomment-474861561

Plz fixed proton

**Comment by kisak-valve** [comment]
Hello @APakrohk, we're using one issue report per unofficially supported game title, making this issue report invalid.
