### ISSUE TITLE
Exclude wine-mono and wine-gecko from proton_dist.tar.gz

### ISSUE THREAD

**Issue by pchome** [ValveSoftware/Proton#2745]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description
Would reduce `proton_dist.tar.gz` file size and increase download speed by ~2x.

content | size    | unpacked size
-------- |  ------ | ----------------
with | 494384K | 1.2G
w/o | 272243K | 905094K

## Justification [optional] 
`wine-gecko` wasn't updated since forever (2.47 was introduced in ~wine-1.9.13).
`wine-mono` also updating rarely.

Likely several next Proton updates(releases) would include the same `wine-gecko` and `wine-mono` versions. So I wondering if it's possible easily switch them to
`SteamApps/common/Steamworks Shared/_CommonRedist/`, where all shared redistributable components stored.

## Risks [optional]
None.

## References [optional]
#1011

**Comment by aeikum** [comment]
It's a reasonable request, but no, it's not super easy (we don't have access to those depots, and even if we did, coordinating those updates adds complication). Compared to typical download sizes on Steam, I don't think ~300MB is terribly much to ask, considering Proton doesn't update that often.
