### ISSUE TITLE
Games not launching on 4.2-5

### ISSUE THREAD

**Issue by Kaznae** [ValveSoftware/Proton#2747]
None of the games installed on my hard drive are launching with the new release of proton, but reverting to 3.16-4 works fine. The single game I have on my OS drive (Dark Souls III) launches fine. Both are ext4.

In the output log, near the bottom there's 
>/media/harddrive/SteamLibrary/steamapps/common/Proton 4.2: Permission denied

I'm not sure what's causing this as I've never had this issue in the past. The Proton 4.2 folder is owned by me, same as all the others. I've tried restarding my computer, reinstalling steam, and reinstalling games all with no success.

Currently running Ubuntu 18.04

**Comment by TheGreatMcPain** [comment]
Have you tried deleting the 'Proton 4.2' folder, and trying again?

Also it might not be a bad idea to check if you have exec permissions on that drive.

**Comment by Kaznae** [comment]
Can't believe I didn't try reinstalling proton earlier. That fixed it, thanks for the help!
