### ISSUE TITLE
Layers of Fear 2 (1029890)

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/Proton#2751]
# Compatibility Report
- Name of the game with compatibility issues: Layers of Fear 2
- Steam AppID of the game: 1029890

## System Information
- GPU: RX VEGA 56
- Driver/LLVM version: Mesa 19.0.1 - padoka PPA/8.0.0
- Kernel version: 5.0.13-050013-lowlatency
- Distro version: Linux Mint 19.1 Tessa (64 bit) (Cinnamon Desktop)
- Proton version: 4.2-5
- System information: [system_info.txt](https://github.com/ValveSoftware/Proton/files/3229593/system_info.txt)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Out of the box game crashes on launch (included logs of that happening with different Proton versions). Setting Steam launch option "-onethread" you can get into gameplay, but the videos/cut-scenes are skipped/do not display.

[media_info.txt](https://github.com/ValveSoftware/Proton/files/3229599/media_info.txt)
[steam-1029890_proton-3.7-8.log](https://github.com/ValveSoftware/Proton/files/3229602/steam-1029890_proton-3.7-8.log)
[steam-1029890_proton-3.16-9.log](https://github.com/ValveSoftware/Proton/files/3229603/steam-1029890_proton-3.16-9.log)
[steam-1029890_proton-4.2-5.log](https://github.com/ValveSoftware/Proton/files/3229604/steam-1029890_proton-4.2-5.log)
[steam-1029890_proton-4.2-5-onethread.log](https://github.com/ValveSoftware/Proton/files/3229605/steam-1029890_proton-4.2-5-onethread.log)

#1464 I see mentions about mfplat.dll in the logs, videos are: MPEG-4, AVC + AAC
The subtitles are not embedded but in separate .srt files.

## Reproduction
Just launch the game.

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX VEGA 56
- GPU Driver: 19.1.0+aco+git1569582082-d0ed7ce952c-1bionic1 (Valves PPA)
- Kernel version: 5.3.1-050301-lowlatency
- Distro version: Linux Mint 19.2 Tina (64 bit) (Cinnamon)
- Proton version: 4.11-6

**Retest Compatibility Report**

Game runs now without needing launch option "-onethread". Remaining issue is that videos are skipped (I have tested that installing Microsoft Media Foundation does fix that).

[steam-1029890-proton-4.11-6.log](https://github.com/ValveSoftware/Proton/files/3693644/steam-1029890-proton-4.11-6.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3693645/system_info.txt)

**Comment by AwesamLinux** [comment]
Re-Test Report

## System Information
- GPU: AMD Radeon RX 5700
- Driver/LLVM version: Mesa 23.0.0-git
- Kernel version: 5.17.11-301.fsync.fc36.x86_64
- Proton Version: proton-7.0-3-rc2

## Symptoms 

Game works now without issues out of the box including video playback. Except on Intel 10th gen+ CPU's because of OpenSSL bug. This is another UE4 game affected by this OpenSSL bug: https://github.com/ValveSoftware/Proton/issues/5830

I was able to play this game without problems setting Steam Launch option:
"OPENSSL_ia32cap=0x20000000 %command%"

Closing this issue as I'm no longer seeing any Proton/game specific problems. Logs for future reference:
[steam-1029890.log](https://github.com/ValveSoftware/Proton/files/8856798/steam-1029890.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/8856799/system_info.txt)
![Screenshot_20220607_232313](https://user-images.githubusercontent.com/43387963/172489165-61ee3848-fc70-45ce-b4ec-1dc416002a8c.jpg)
^ Screenshot of working video

**Comment by Zlopez** [comment]
Finished the game with Proton 7.0-5 on Steam Deck. Every video works except the final one for formless ending (didn't get to testing other endings). Instead the game will froze and you need to forcefully shut it down.

With Proton 7.0-4 this happened on the first video you encounter in the game.
