### ISSUE TITLE
VRChat avatars with >1 skinned meshes render only the first mesh (the one named "Body" in Unity), and not others

### ISSUE THREAD

**Issue by Icekhaos** [ValveSoftware/Proton#2764]
# Compatibility Report
- Name of the game with compatibility issues: VRChat
- Steam AppID of the game:438100

## System Information
- GPU: RX480
- Driver/LLVM version: Mesa 18.2.8, DRM 3.32.0, LLVM 7.0.0
- Kernel version: 5.2.0-050200rc2-generic
- Link to full system information report as [Gist](https://gist.github.com/): [Gist](https://gist.github.com/Icekhaos/4ea3373f70ea60c3d3ee031af3721283)
- Proton version: 4.2-5

## I confirm:
- [Y] that I haven't found an existing compatibility report for this game.
- [Y] that I have checked whether there are updates for my system available.

[steam-438100.log](https://github.com/ValveSoftware/Proton/files/3244194/steam-438100.log)

## Symptoms 
Player models with more than one skinned mesh (confirmed secondhand by an Unity avatar creator) do not render any skinned meshes besides the only one required by the game, that is, the one named "Body".

Here is the list of meshes, the first group (Mishe) is the unoptimized avatar that does not render properly, and the latter one (MisheOptimized) is an optimized avatar that correctly renders.
![UnityMisheOpti](https://user-images.githubusercontent.com/4009373/58753320-b3f61100-84ac-11e9-8a01-08456a4146b8.png)

Here is what Mishe looks like:
![unknown (1)](https://user-images.githubusercontent.com/4009373/58753329-f0c20800-84ac-11e9-89b8-e7813a9a98d1.png)

Here is what MisheOptimized looks like:
![unknown](https://user-images.githubusercontent.com/4009373/58753334-05060500-84ad-11e9-8cb6-8fece9e6492a.png)

## Reproduction
1: Launch VRChat
2: Enter a hub world
3: Wait for an avatar with multiple skinned meshes
4: Compare screenshots

**Comment by kisak-valve** [comment]
Hello @Icekhaos, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1199#issuecomment-497977988.

**Comment by Icekhaos** [comment]
Thanks a bunch.
