### ISSUE TITLE
Need for Speed Hot Pursuit has no sound at all (47870)

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/Proton#277]
Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/5651.
@landjalan posted on 2018-08-23T13:27:26:

#### Your system information

* Steam client version (build number or date): current
* Distribution (e.g. Ubuntu): gentoo
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] no

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. install game with proton 3.7
2. start and play
3. no sound

**Comment by parkerlreed** [comment]
Seeing the same issue here

* Steam client version (build number or date): current
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

**Comment by landjalan** [comment]
After restart game runs fine :)

**Comment by kisak-valve** [comment]
Possibly pulseaudio related? If you see this issue again, try restarting pulseaudio with `pulseaudio -k` and see if it makes a difference.

**Comment by parkerlreed** [comment]
@landjalan Restart of game or computer?

**Comment by ryad-lindner** [comment]
No problems with the game itself at all. Could finish the first race without hiccups.
Sound working but it is at maximum volume without the possibility to manage volume via pavucontrol (no application channel for the game available).

**Comment by artur9010** [comment]
Audio works fine.


- Steam client version (build number or date): current
- Distribution (e.g. Ubuntu): ubuntu 18.04
- Opted into Steam client beta?: [Yes/No] yes
- Have you checked for system updates?: [Yes/No] yes

**Comment by parkerlreed** [comment]
Ok audio is working here now too. Weird.

**Comment by kisak-valve** [comment]
Closing per the last several comments.
