### ISSUE TITLE
Into The Breach crashes X session with nVidia 430.14 (590380)

### ISSUE THREAD

**Issue by VancouverJohn** [ValveSoftware/Proton#2772]
# Compatibility Report
- Name of the game with compatibility issues: Into the Breach
- Steam AppID of the game: 590380

## System Information
- GPU: GeForce GTX 1050 Mobile
- Driver/LLVM version: nvidia 430.14-7
- Kernel version: 5.1.6-arch1-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/VancouverJohn/eaa9dca50db5efc4610b3ae6d0243bcc):
- Proton version: 4.2-5

## I confirm:
- [y] that I haven't found an existing compatibility report for this game.
- [y] that I have checked whether there are updates for my system available.

[steam-590380.log](https://github.com/ValveSoftware/Proton/files/3254123/steam-590380.log)

## Symptoms 

After a few moments of gameplay, the game crashes and takes down the entire X server.

## Reproduction

1. Start Game, go through title and squad selection
2. Within a few moments of gameplay the game crashes

**Comment by kisak-valve** [comment]
Hello @VancouverJohn, this game is rendering with OpenGL and in general no OpenGL application should cause the system-wide issues, which hints that this is a video driver issue. Are there any hints in `dmesg` that go along with this?

**Comment by VancouverJohn** [comment]
This is the [output](https://gist.github.com/VancouverJohn/b6e2e81d82888f8bd65351e3c326735e) of my dmesg between crashes.

**Comment by VancouverJohn** [comment]
I found the following [logs](https://gist.github.com/VancouverJohn/f17b877789bfd9489e1c7d3fb395c3f6) in journalctl which correspond to the crash of X.

**Comment by peret** [comment]
I had this same issue on Ubuntu 19.04 with the nvidia-driver-418 package, but not with nvidia-driver-390.

**Comment by kisak-valve** [comment]
Hello @VancouverJohn, noted at https://github.com/ValveSoftware/Proton/issues/204#issuecomment-616830044, this game was recently removed from the whitelist, and we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/204#issuecomment-616831409.
