### ISSUE TITLE
STAR WARS™ - Dark Forces (32400) fails to launch

### ISSUE THREAD

**Issue by Spacexplosion** [ValveSoftware/Proton#2775]
This game is whitelisted for Proton 3.16-4, but it doesn't launch at all on a Linux Mint / Ubuntu system. Logs verify it is running and exiting, but not much else.
[compat_log.txt](https://github.com/ValveSoftware/Proton/files/3255104/compat_log.txt)
[shader_log.txt](https://github.com/ValveSoftware/Proton/files/3255106/shader_log.txt)

**Comment by kisak-valve** [comment]
Hello @Spacexplosion, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box. Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Spacexplosion** [comment]
[steam-32400.log](https://github.com/ValveSoftware/Proton/files/3255191/steam-32400.log)

https://gist.github.com/Spacexplosion/ecbffaa92be63fa2021679a06078512e

**Comment by Spacexplosion** [comment]
Turning off the in-game Steam overlay has no effect.

Everything in the compatdata directory is owned by root but permission mode 777.

**Comment by dreamer** [comment]
@Spacexplosion as a workaround, you can try running the game through https://github.com/dreamer/steam-dos

**Comment by aeikum** [comment]
> Everything in the compatdata directory is owned by root

This is your problem. How did this happen?

**Comment by Spacexplosion** [comment]
@aeikum It is the default behavior for non-POSIX file systems like NTFS or FAT. Note the permission mode 777 is full read-write-execute. There are no access limitations. To additionally require ownership of a shared directory would be an erroneous requirement, especially since in this case new files created there will also be full access. On a POSIX filesystem it could make more sense, because new files created in the directory would default to the directory's ownership. Having the group set appropriately should be enough in that case though, not actual owner. Perhaps the error message is just imprecise? I'll try setting the group id mount option on that partition.

**Comment by Spacexplosion** [comment]
@dreamer Steam-dos works like a charm, and is a much more elegant solution than running a Windows build of Dosbox through Wine I might add.

**Comment by aeikum** [comment]
No, Wine actually checks ownership and refuses if you don't own the directory, see https://source.winehq.org/git/wine.git/blob/4d5c874f42e27ac992f361c71490985d7553571a:/libs/wine/config.c#l330 This was added in commit 65d865d96313. I don't know the reason for it, but there likely was one.

**Comment by madewokherd** [comment]
I think at the time we were having problems with users running Wine as root and ending up with a default prefix in $HOME that they can't access.

**Comment by Spacexplosion** [comment]
So that upstream decision breaks support for running Wine with its config directory in a shared non-POSIX filesystem. Or possibly any shared directory... I'm not sure it would work for multiple users even if I made a special Steam library (say at /usr/share/Steam) just for Proton games. Should I file a bug upstream?

It looks like the config directory defaults to in the user's home. Could Proton be given an option to store the compatdata directory somewhere else, other than in the library? Should I split this off to a feature request?

**Comment by madewokherd** [comment]
Putting the config directory in a non-POSIX filesystem isn't supported by Wine generally. There may be other problems, such as inability to create symlinks or set the "read only" flag.

Is this a configuration you were able to make in the Steam GUI? If so, we need to handle it somehow.

**Comment by Spacexplosion** [comment]
Yep, the GUI seems to let you set a library at any valid path. 
![image](https://user-images.githubusercontent.com/1591279/59148655-b212dd00-89d9-11e9-9d00-236252071e51.png)

**Comment by madewokherd** [comment]
I think transferring to a bug report (or relabeling this one?) would make sense, since it's not specific to this one game. @kisak-valve ?

**Comment by kisak-valve** [comment]
Hello @Spacexplosion, looks like the discussion has become a rehash of the interaction issues with NTFS that are tracked in several issue reports (#11 / #104 / #1824). We're not going to support FAT32 (#2439).

It would be best to continue the discussion on #11. Closing in favor of the older issue report.
