### ISSUE TITLE
Wolfenstein: The New Order - no sound, poor performance (201810)

### ISSUE THREAD

**Issue by dukesilver28** [ValveSoftware/Proton#2778]
# Compatibility Report
- Name of the game with compatibility issues: Wolfenstein: The New Order
- Steam AppID of the game: 201810

## System Information
- GPU: GTX 970
- Driver/LLVM version: 4.15.27
- Kernel version: 4.15.0-51
- Link to full system information report: https://gist.github.com/dukesilver28/146c78997c507eaa079888429f250e18
- Proton version: 4.2-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms What's the problem?
The game ran flawlessly (e.g. 60 fps at max settings) on proton 4.2-5. Since updating to 4.2-6, the game has no sound and the performance has regressed significantly (e.g. around 15 fps in the opening level). To confirm this was a proton related issue, I reverted back to 3.16-9, and then everything worked fine again, though the fps is a little under 60 fps at times. It performed slightly better on 4.2-5.

## Reproduction
Start game

### Note
I generated the steam log by adding 'PROTON_LOG=1 %command%' to the launch options. However, the log file is around 40 MB, and apparently I can only add a file that's 10 MB or smaller. I tried creating a gist page for it, but it won't work (I'm assuming for a similar reason). If you all have a specific recommendation on how to get around this issue, let me know.

**Comment by BlueGoliath** [comment]
Can reproduce on Arch Linux with a GTX 1080. The intro cutscenes have sounds but menu and in-game do not. Performance starts out initially at the 60FPS limit but within a minute gradually drops to 20FPS and under.

Valve, please fix.

**Comment by Leopard1907** [comment]
@dukesilver28 Compress log file as .gz and add it into your post.

**Comment by kisak-valve** [comment]
Hello @dukesilver28, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/606#issuecomment-499870298.
