### ISSUE TITLE
Tekken 7 [389730] won't launch

### ISSUE THREAD

**Issue by nilleairbar** [ValveSoftware/Proton#278]
Just finished downloading Linux in my Arch VM. Whenever I try to launch it the splashscreen appears but the game gets shutdown immediately after without any error message.
- Linux kernel is 4.18.3
- Nvidia is at 396.51
- LLVM is on version 6
- GPU is a GTX 1070
- CPU a Ryzen 1700
- Python2.7 is installed

The game does launch when PROTON_USE_WINED3D11 is set to true but all graphics are artifacted and glitched.

**Comment by tesfabpel** [comment]
Are you using Steam (Native) or Steam (Runtime)?
I'm downloading Tekken 7 right now so I can't say for that game but with NieR: Automata it didn't launch with (Native).

**Comment by nilleairbar** [comment]
Was using the Native branch as of now, will try it now with Runtime.

Just tested it on the Runtime branch, the exact same issue persists.

**Comment by tesfabpel** [comment]
Ok I've downloaded the game and I have the same issue (the game won't launch) but it's a bit different since I don't get the splashscreen but I get an error message...
I worked around it with the same trick I used for Thief...
Try to set in the launch options: `PROTON_NO_ESYNC=1 %command%`

This is the error message that appears without that:
![screenshot_20180824_074320](https://user-images.githubusercontent.com/1371976/44567660-c13edc00-a773-11e8-9a55-0297c3bfc31f.png)

**Comment by nilleairbar** [comment]
I tested again, updated drivers to 396.54 and tried every possible launch option and the game still just shutsdown after the splashscreen.
Some reddit post explained how to get Proton to dump a debug log which I did for Tekken. The respective Gist of the log can be found [here](https://gist.github.com/nilleairbar/0b659094e27262a836e1383ea626a848)

**Comment by doitsujin** [comment]
Can you please attach your `vulkaninfo` output? Given that it works for you with wined3d but not dxvk, there might be some Vulkan issues.

**Comment by nilleairbar** [comment]
The dump from vulkaninfo can be found [here](https://gist.github.com/nilleairbar/d1559021b7b4103e8d0f3bac9ee02067).
To add to that though, non whitelisted games like Prey ('17) work right out of the box with the default Vulkan driver.

**Comment by nilleairbar** [comment]
So I just finished the download for the game again and without changing anything on my system the game now just runs right out of the box.  
My guess is that something was wrong during download/installation but now the game starts without issue.
Edit: So the game works really good right now, the only problem left is a slight audio delay, but I guess that could be just because of my setup.
