### ISSUE TITLE
Rocket League (252950) AA not working

### ISSUE THREAD

**Issue by Sliderpro** [ValveSoftware/Proton#2781]
Hi. Game id "252950"
Antialiasing doesnt work through latest Steam Proton in any way. Proton version 4.2.6. GPU - AMD Rx570. Linux Mint 19 cinnamon. Latest updates. Tried forcing AA through game configs (MSAA and TAA) - wasnt succesfull with either. Thanks.

**Comment by kisak-valve** [comment]
Hello @Sliderpro, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by Sliderpro** [comment]
https://gist.github.com/Sliderpro/e1fc63149152b8e50e012e290367211a

**Comment by Sliderpro** [comment]
Hm. I wasnt able to find that log file... I tried both PROTON_LOG=1 %command% and without command to game launch options
![Screenshot from 2019-06-07 16-42-15](https://user-images.githubusercontent.com/2086796/59108299-3b2b0500-8943-11e9-9f96-ba6fe738f928.png)

**Comment by Sliderpro** [comment]
![Screenshot from 2019-06-07 16-43-55](https://user-images.githubusercontent.com/2086796/59108409-7d544680-8943-11e9-9151-ab74d7da2ccf.png)

**Comment by kisak-valve** [comment]
By default, Proton logs should end up in your home folder, not a subfolder. Is it hiding in plain sight?

**Comment by Sliderpro** [comment]
Haha, sorry, seems like an issue on my end. Reinstalled OS to Zorin, native Rocket league from Steam really cant use FXAA. And works quite wonky with sudden flashes and stuff.

However, if you force Steam Proton, 4.2.6, game magically learns to use FXAA. The difference is noticable. Game runs much better.
The issue is closed.
