### ISSUE TITLE
DEAD OR ALIVE 6 - Proton 4.2-6 - no sound (838380)

### ISSUE THREAD

**Issue by bg2908** [ValveSoftware/Proton#2783]
# Compatibility Report
- Name of the game with compatibility issues: DEAD OR ALIVE 6
- Steam AppID of the game: 838380

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 19.0.5
- Kernel version: 5.1.7-arch1-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/bg2908/f9586e20e1e64032d7a13c24a42ea810
- Proton version: 4.2-6

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-838380.log](https://github.com/ValveSoftware/Proton/files/3265670/steam-838380.log)

## Symptoms 
Game runs with completely no sound.
Game doesn't have this problem with older Proton version.

## Reproduction
Run the game with Proton version 4.2-6

**Comment by kisak-valve** [comment]
Hello @bg2908, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2420#issuecomment-499872966.
