### ISSUE TITLE
Ability to use the mac version

### ISSUE THREAD

**Issue by Nicopara** [ValveSoftware/Proton#2785]
# Feature Request
Hello, a lot of old games were ported to Mac such as Call of Duty Black Ops, these kind of games already run on OpenGL and there should be no complex translation layer such as DXVK needed. I Would like you guys to add the option to run the mac version instead of the windows one that steam defaults. How hard can it be?

Thank you for your time.

**Comment by nsivov** [comment]
It is hard, because it will require different kind of Wine-like component, implementing macos system libraries. It's not just about OpenGL.

**Comment by kisak-valve** [comment]
Hello @Nicopara, the short answer is very hard.

There's little to no reusable system and common framework support between Windows and Mac. As far as I'm aware, [Darling](https://github.com/darlinghq/darling) is currently the closest to a usable upstream project to piggyback on, but it's nowhere close to being able run mainstream games.

Given the low amount of Mac games on Steam that do not have a Windows release, I don't think expanding Proton's project scope to include this feature request is worth considering at this time.

If there's a viable example of integration for Mac game support or any Proton dev disagrees with this assessment, we could consider re-opening this feature request.
