### ISSUE TITLE
Yakuza Kiwami (834530) - Crash to Desktop

### ISSUE THREAD

**Issue by kuroko143** [ValveSoftware/Proton#2787]
# Compatibility Report
- Name of the game with compatibility issues: Yakuza Kiwami
- Steam AppID of the game: 834530

## System Information
- GPU: Nvidia RTX 2080
- Driver/LLVM version: nvidia 430.14-8
- Kernel version: 5.1.7
- Distro: Arch Linux
- Proton version: 4.2-6

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game crashes to desktop everytime I try to go into a specific room of the game.
Using Sony PS3 controller to play.

## Reproduction
Load save file, go into a hostess club called Shine. Crashes to desktop.
[steam-834530.log](https://github.com/ValveSoftware/Proton/files/3268077/steam-834530.log)

**Comment by kisak-valve** [comment]
Hello @kuroko143, we're using one issue report per unofficially supported game title, and you've already made a note of your issue at https://github.com/ValveSoftware/Proton/issues/2403#issuecomment-495448726.

Closing in favor of the existing issue report.
