### ISSUE TITLE
Add Media Fundation to proton build

### ISSUE THREAD

**Issue by XlzDIEzlX** [ValveSoftware/Proton#2788]
Hi, you should implement that tool, fix several games like Final Fantasy Type 0 HD, so you can already consider  as "Whitelist" at the same time.

 FIX #2213

**Comment by kisak-valve** [comment]
Hello @XlzDIEzlX, this feature request is functionally a duplicate of #1464. [Work on implementing the framework](https://source.winehq.org/git/wine.git/?a=search&h=HEAD&st=commit&s=mf) is ongoing in upstream wine and I don't see any value in having another feature request for the framework on Proton's side.

Closing in favor of #1464.
