### ISSUE TITLE
FAudio FFMpeg support

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/Proton#2789]
For some reasons, valve can't ship FAudio with FFMpeg support enabled.
Is this possible to ship simple script with proton, which would compile and install faudio with ffmpeg support enabled?
So everything user need is run this script.

**Comment by lucifertdark** [comment]
I just put this little bash script together, it deletes the folder if it's there, downloads a new copy of the source, sets up the folders, compiles & then moves the FAudio file to the correct folder for the current version of Proton, Easily edited to update to the next version, all you have to do is save it to a .sh file & make it executable. (you need git & all the bits you'd need to compile, but you have them already)

```
#!/bin/bash
# A simple script to compile FAudio
rm -rf FAudio
git clone git://github.com/FNA-XNA/FAudio.git
cd FAudio
mkdir flibitBuild
cd flibitBuild
cmake .. -DXNASONG=OFF -DFFMPEG=ON
make
cp libFAudio.so.0 ~/.local/share/Steam/steamapps/common/Proton\ 4.2/dist/lib64/
```
ps I'm not one of the devs on this project, I'm just a gamer, hopefully helping out. :)

**Comment by aeikum** [comment]
Sorry, no, we can't do this.
