### ISSUE TITLE
Warframe Stuttering After Latest Proton Update

### ISSUE THREAD

**Issue by LichGirl** [ValveSoftware/Proton#2790]
# Compatibility Report
- Name of the game with compatibility issues: Warframe
- Steam AppID of the game: 230410

## System Information
- GPU:  GTX 1060
- Driver/LLVM version:   nvidia 430.14-8
- Kernel version:  5.1.5-arch1-2-ARCH
- Link to full system information report as [Gist](https://gist.github.com/): https://pastebin.com/230QJieu
- Proton version: 4.2-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Shortly after opening the game (5-10 minutes), framerate and audio stuttering occurs. It can go all the way down to 20FPS, usually leveling out there and not degrading further. This issue has only happened after the latest Proton update and before that the game was working flawlessy with the suggested audio patch and xboxdrv to prevent crashes. Leaving the game open for some time (1hr+) just amplifies the problem and does not help.  

## Reproduction
Issue occurs both on my desktop and laptop, which have similar specs. Again, only happened after the latest in game patch.

**Comment by kisak-valve** [comment]
Hello @EchoDuplication, we're using one issue report per unofficially supported game title, and this issue has already been assessed, please see https://github.com/ValveSoftware/Proton/issues/167#issuecomment-500039704.

Closing in favor of #167.

**Comment by LichGirl** [comment]
Issue fixed. Ran:

cd ~/.local/share/Steam/steamapps/common/Proton\ 4.2/dist/lib64
curl -O flibitijibibo.com/opexit.tar.bz2
tar xvfj opexit.tar.bz2
