### ISSUE TITLE
Path of Exile random crashes

### ISSUE THREAD

**Issue by MrPaj** [ValveSoftware/Proton#2795]
Hi,

Path of Exile running  is randomly crashing while I am fighting. 
Sometimes I can play for hours without issues, other times it happens every 10 minutes.
If you need any logs, please let me know which ones. Below details of my specs 

Thank you

Proton 4.2.6
CPU:  AMD Ryzen 5 2600X Six-Core Processor           
Debian GNU/Linux 10 (buster) (64 bit)
Kernel Version:  4.19.0-5-amd64
Driver:  NVIDIA Corporation GeForce GTX 1060 6GB/PCIe/SSE2
Driver Version:  4.6.0 NVIDIA 418.56
RAM:  16056 Mb

**Comment by kisak-valve** [comment]
Hello @MrPaj, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/58#issuecomment-500603515.
