### ISSUE TITLE
Headliner: NoviNews listed as native when it isn't

### ISSUE THREAD

**Issue by ChildishGiant** [ValveSoftware/Proton#2796]
![image](https://user-images.githubusercontent.com/13716824/59310431-372e1880-8c9e-11e9-9370-0a2318bd8dea.png)

Headliner: NoviNews (918820) is listed as native but also doesn't show a tux since it's not actually native.

**Comment by OvermindDL1** [comment]
@ChildishGiant Where is this listed in the Steam Client?  I've never seen a screen that looks anything remotely like that in Steam.

**Comment by kisak-valve** [comment]
Hello @ChildishGiant, protondb.com is not affiliated with Valve or this project.

**Comment by ChildishGiant** [comment]
oops sorry, I posted this on the wrong repo 🤦‍♀
