### ISSUE TITLE
STEINS;GATE (412830) crackling audio

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#2797]
# Compatibility Report
- Name of the game with compatibility issues: STEINS;GATE
- Steam AppID of the game: 412830

## System Information
- GPU: Nvidia GeForce GTX 1080
- Driver/LLVM version: nvidia 430.26-1
- Kernel version: Linux 5.1.8-arch1-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/coltondrg/5e2936796e4b0d179b4826647ee57e4f
- Proton version: 3.16-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-412830.log](https://github.com/ValveSoftware/Proton/files/3282012/steam-412830.log)

## Symptoms 
Audio is crackling and distorted, and the speed of music/sound effects changes randomly.

Forcing the game to use Proton 4.2-7 resolves the issue.

## Reproduction
The issue is usually apparent on the title screen but occasionally things will behave correctly for a couple minutes before it becomes noticeable.

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
