### ISSUE TITLE
F.E.A.R. 3 (21100) - Does Not Start

### ISSUE THREAD

**Issue by alligatorshoes** [ValveSoftware/Proton#2808]
# Compatibility Report
- Name of the game with compatibility issues: F.E.A.R. 3
- Steam AppID of the game: 21100

## System Information
- GPU: GTX 1070
- Driver/LLVM version: nvidia 430.14
- Kernel version: 5.1.8-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/alligatorshoes/3442d61b0f448b90987a245b1a441caa
- Proton version: 4.2-7

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Proton log file: [steam-21100.log](https://github.com/ValveSoftware/Proton/files/3291391/steam-21100.log)

## Symptoms 

Clicking "Play" shows the game as "Running" but nothing appears on the desktop. Eventually, after a little time, the game no longer shows as "Running".

## Reproduction

Start the game.

**Comment by kisak-valve** [comment]
Hello @alligatorshoes, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/963#issuecomment-502170564.
