### ISSUE TITLE
File path case problem

### ISSUE THREAD

**Issue by math-rock** [ValveSoftware/Proton#2813]
# Compatibility Report
- Name of the game with compatibility issues: KOFXIII
- Steam AppID of the game: 292030

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [xx] that I have checked whether there are updates for my system available.

## Symptoms 

Steam client can't start KOFXIII.

Here is the reason:

Traceback (most recent call last):
File "/home/user/.local/share/Steam/SteamApps/common/Proton 4.2/proton", line 325, in <module>
with prefix_lock:
File "/home/user/.local/share/Steam/SteamApps/common/Proton 4.2/filelock.py", line 322, in __enter__
self.acquire()
File "/home/user/.local/share/Steam/SteamApps/common/Proton 4.2/filelock.py", line 251, in acquire
self._acquire()
File "/home/user/.local/share/Steam/SteamApps/common/Proton 4.2/filelock.py", line 383, in _acquire
fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/share/Steam/steamapps/compatdata/222940/pfx.lock'

Steam client did not make "steamapps" directory, it made "SteamApps" directory. The files are in '/home/user/.local/share/Steam/SteamApps/compatdata/222940'.

**Comment by dreamer** [comment]
Is this a new Steam installation? Steam Beta? Upload a gist with your system information, please.

**Comment by aeikum** [comment]
I've never heard of the SteamApps folder being created by Steam for Linux with that casing. Did you do something special to create the SteamApps folder, like copy it from a Windows installation?

**Comment by kisak-valve** [comment]
Old steam installs can have a camel case SteamApps folder that's been grandfathered in and remained functional.

**Comment by aeikum** [comment]
I see, looks like a Steam client bug then. We don't create that path in Proton, we just pass through what the Steam client hands us in $STEAM_COMPAT_DATA_PATH. Thanks for reporting.

**Comment by Plagman** [comment]
The code is supposed to check for that, so is it possible that `/home/user/.local/share/Steam/steamapps/` also exists on your machine?

**Comment by thecyberd3m0n** [comment]
I have same issue with all games. I tried changing Proton Version and reinstalling Steam.

**Comment by rbarclay4711** [comment]
Quick&dirty hack got me to being able to play my games (Dishonored 1+2, Mass Effect 1+2) again:
`cd ~/.local/share/Steam/ && mv steamapps/* SteamApps/ && rmdir steamapps && ln -s SteamApps steamapps`

Would probably work the other way around, too.

**Comment by alexzk1** [comment]
It seems they changed cases ... old (for years) installation says "SteamApps", but proton script is searching for "steamapps" now.
On case-sensitive file system that is a problem.
