### ISSUE TITLE
Witcher 3 on ubuntu with Steam play won't start

### ISSUE THREAD

**Issue by milka123** [ValveSoftware/Proton#2817]
# Compatibility Report
- Name of the game with compatibility issues: Witcher 3: Wild hunt
- Steam AppID of the game: 292030

## System Information
- GPU: NVIDIA GeForce GTX 1050 Ti
- Driver/LLVM version: 396.54, also tried with 418.56
- Kernel version: 4.15.0-51-generic
- Link to full system information report as [Gist](https://gist.github.com/):
https://gist.github.com/milka123/f9d06e849c2e0e7fed695af72af5d3ef
- Proton version:

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

When I start the game, Steam client says it's running but nothing shows up. When I check system monitor I can see witcher3.exe in processes as running but nothing happens.
I couldn't find any more details about potential crashes in steam app log file.

## Reproduction

Downloaded Witcher 3: Wild hunt through steam client and tried to run it 

[steam-292030.log](https://github.com/ValveSoftware/Proton/files/3297786/steam-292030.log)

**Comment by kisak-valve** [comment]
Hello @milka123, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-502745127.
