### ISSUE TITLE
Empyrion - Galactic Survival (383120)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#2819]
# Compatibility Report
- Name of the game with compatibility issues: Empyrion - Galactic Survival
- Steam AppID of the game: 383120

## System Information
- GPU: GeForce GTX 1060 6GB/PCIe/SSE2
- Driver/LLVM version: 4.6.0 NVIDIA 418.56
- Kernel version: 5.0.0-16-generic
- Link to full system information report as [Gist](https://gist.github.com/azsorlex/6d9cb465604c49f6497d2a7b32ee756e):
- Proton version: 4.2-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-383120.log](https://github.com/ValveSoftware/Proton/files/3299759/steam-383120.log)

## Symptoms 
It just doesn't work. After clicking "Play" and the initial window goes away, my name text turns green for three seconds, then back to blue.

## Reproduction
Trying to run the game.

A lot of people say EAC is the problem, but I don't think that's true since a clean install of the game on Windows (on the exact same machine (I have a dual-boot setup)) has it disabled by default.

**Comment by d10sfan** [comment]
The issue is the launcher, EAC won't work most likely, but you can play the game by bypassing the launcher. I did it by doing the following (creating a custom launch script), mainly to avoid having to do it each update:

Create a .bat file (I named it EmpyrionLauncher) in the same directory as your installation of Empyrion. It should look like the following:

```
cd Client
start /wait Empyrion.exe
```

After this, you'll want to create an exe out of the bat script named EmpyrionLauncher.exe (replacing the one that's already there). Once you do this, you should be able to play the game from Steam.

You may also be able to use the .bat as a replacement for the .exe but I haven't tried that.

**Comment by ghost** [comment]
@d10sfan wait so how do I create an exe file from a bat script? I searched, but only found conversion scripts/algorithms for windows and not linux. Also, steam doesn't like the bat file as it is; it has to be made into an exe.

**Comment by azsorlex** [comment]
So after switching to windows and following [these instructions](https://stackoverflow.com/questions/51098378/converting-bat-to-exe-with-no-additional-external-software-create-sfx), I got an exe, but upon clicking "Play", the bubble initially showed itself with the "Play game as soon as it's ready" checkbox and the progress bar as if it were downloading, then those vanished, leaving the "Play game" button, and clicking that yielded the same result as before.

After running `cat` on the exe I generated as well as the one in the empyrion folder after trying to run it, I could see that the ends of the files were different, which can only mean that steam replaced it with the previous one.

**Comment by ghost** [comment]
@d10sfan So after switching to windows and following [these instructions](https://stackoverflow.com/questions/51098378/converting-bat-to-exe-with-no-additional-external-software-create-sfx), I got an exe, but upon clicking "Play", the bubble initially showed itself with the "Play game as soon as it's ready" checkbox and the progress bar as if it were downloading, then those vanished, leaving the "Play game" button, and clicking that yielded the same result as before.

After running `cat` on the exe I generated as well as the one in the empyrion folder after trying to run it, I could see that the ends of the files were different, which can only mean that steam replaced it with the previous one.

**Comment by d10sfan** [comment]
For the replacement part, can't speak to that other than you might want to rename the executable you're replacing, so it's still in the folder, and then try that again.

**Comment by ghost** [comment]
@d10sfan It just isn't working. I tried it again, this time recording everything I did, and it resulted in the initial problem. 
[Process.zip](https://github.com/ValveSoftware/Proton/files/3303856/Process.zip)

Edit: I only now just understood what you meant by that... But still, doing that changed nothing.

**Comment by d10sfan** [comment]
You may want to try some of the things listed in these thread then: https://steamcommunity.com/app/383120/discussions/0/485622866440607945/?ctp=14

**Comment by ghost** [comment]
So I followed the instructions of comment #198 (adding a link to Empyrion.exe in Steam), and it worked! Thanks for your help!

Here are some observations I thought I'd compile together when comparing this linux workaround running at maximum settings (not the "Best" preset) to the Windows installation:

- Lower performance (though it runs fine on the "Best" preset. Around 30-60 fps based on the time and place).
- The "Good" preset has horrible performance.
- The "Exclusive Fullscreen" screen mode breaks the game when selected, and after the game is restarted, it has a chance to break it again (the break is being unable to click anything). The fix is to use "Fullscreen Window". If you've already selected Exclusive Fullscreen, you'll have to fiddle around with the resolutions until you get the game into a window, then you can set it back to native and Fullscreen Window.
- Alt-tabbing has a chance to break the game as described in the last point or crash the game entirely. EDIT: The latest Proton version (4.2-8) fixed this issue (as far as I can tell). 
- Lastly (this one really surprised me), there's less video tear! Usually, linux is the one that has nasty tearing issues without vsync enabled, but nope, Windows is atrocious compared to linux. Also, I might be imagining things, but the tearing appears to be non-existent when enabling "Force Full Composition Pipeline" in NVIDIA X Server Settings.

**Comment by azsorlex** [comment]
> * Alt-tabbing has a chance to break the game as described in the last point or crash the game entirely.

The latest Proton version (4.2-8) fixed this issue (as far as I can tell). Still have to use a custom link to Empyrion.exe, however.

**Comment by jarrard** [comment]
With the recent Unity2019 update for this game, it no longer works in proton. (yet tested in lutris).

Tested with/without dotnet472/vcrun2015 installed, tested launcher and direct empyrion.exe. 

Perhaps re-open this issue.

**Comment by ghost** [comment]
Nothing's changed for me. It doesn't work out of the box, and it can be run by creating a shortcut to Empyrion.exe, setting the target again in the shortcut's properties, and forcing the use of proton.

**Comment by jarrard** [comment]
Yeah that doesn't work any longer for me. Maybe there is something wrong in my kernel or nvidia driver 430.26-6

**Comment by ghost** [comment]
I tried recreating the shortcut to give the benefit of the doubt, and it still works with the latest version of the game. I found that using proton 4.11-1 doesn't work, but 4.2-9 does.

**Comment by jarrard** [comment]
Ahh so its a bug in 4.11-1, then this should be reopened and maybe top post updated to reflect the issue.  Not even the custom 4.11-GE version of proton works. Well, another regression for 4.11 it seems....

**Comment by ghost** [comment]
Definitely a problem with 4.11; just tried the other versions and they work with the shortcut.

**Comment by kisak-valve** [comment]
Hello @aorozsa, @jarrard, can one of you please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by ghost** [comment]
@kisak-valve I tried gathering logs for both running the game normally and running it through the shortcut, but I couldn't get the shortcut logs. There's other stuff already there, so I tried adding the above property before (`PROTON_LOG=1 %command% - Galactic Survival/Client/Empyrion.exe`) and after (`- Galactic Survival/Client/Empyrion.exe PROTON_LOG=1 %command%`) . When trying to run empyrion via the shortcut again, a window came up that didn't appear before when I tested this (I even removed the log property and recreated the shortcut). Perhaps that can help?

Log for trying to run the game normally (doesn't work regardless of proton version, but running via shortcut only doesn't work using 4.11):
[steam-383120.log](https://github.com/ValveSoftware/Proton/files/3460979/steam-383120.log)

Window that previously didn't appear when attempting to run via shortcut using 4.11:
![Screenshot from 2019-08-02 21-20-36](https://user-images.githubusercontent.com/8101141/62366961-a6700c80-b56b-11e9-86f2-4c8fc8f0f535.png)

**Comment by kisak-valve** [comment]
Thanks, looks like you hit https://github.com/ValveSoftware/steam-for-linux/issues/6046. Perhaps you can get a Proton log for the non-steam game shortcut by copying user_settings.example.py to user_settings.py as mentioned in https://github.com/ValveSoftware/Proton#runtime-config-options.

**Comment by ghost** [comment]
@kisak-valve That worked! Here are two logs for the shortcut. I added the version number near the end of the file name.

[steam-17762952556864077824-4.11.log](https://github.com/ValveSoftware/Proton/files/3461124/steam-17762952556864077824-4.11.log)

[steam-17762952556864077824-4.2.log](https://github.com/ValveSoftware/Proton/files/3461125/steam-17762952556864077824-4.2.log)
