### ISSUE TITLE
Gato Roboto (916730)

### ISSUE THREAD

**Issue by galaxite** [ValveSoftware/Proton#2820]
# Compatibility Report
- Name of the game with compatibility issues: Gato Roboto
- Steam AppID of the game: 916730

## System Information
- GPU: Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) x86/MMX/SSE2
- Driver/LLVM version: 3.0 Mesa 19.0.6
- Kernel version: 4.19.50_1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/galaxite/6f863b50538b61a186bf550ef08ad07f
- Proton version: 4.2-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-916730.log](https://github.com/ValveSoftware/Proton/files/3302674/steam-916730.log)

## Symptoms 
Upon trying to start the game, the only thing that happens is the appearance of a window that says: Win32 function failed: HRESULT: 0x80004005 
Call: at line 226in file \Graphics_DisplayM.cpp

## Reproduction
With the listed system configuration, simply attempt to start the game.

**Comment by kisak-valve** [comment]
Hello @galaxite, does any vulkan application like `vulkaninfo` work? `err:   DxvkInstance: Failed to create instance` `err:   D3D11CreateDevice: Failed to create a DXGI factory` in your log hints that you're missing mesa/anv.

**Comment by galaxite** [comment]
`vulkaninfo` does work and produces output, though the output is enormous and difficult to glean much information from. I've also installed the `vulkan-loader` packages for my system. However, when launching Lutris, another game launcher program, it informs me that it is unable to find 32-bit vulkan libraries on my computer. Would it be useful to upload the `vulkaninfo` output to a gist?

**Comment by kisak-valve** [comment]
The actual contents of `vulkaninfo` is not particularly interesting, but 32 bit vulkan having trouble is interesting and worth pursuing.

**Comment by galaxite** [comment]
After a recent update to the Intel driver, the game finally launches. However, what happens now is even more bizarre to me. After about a minute after launching (plus or minus a second), the game crashes. This happens every single time. The new log that is generated when experiencing this behavior has been attached.
[steam-916730.log](https://github.com/ValveSoftware/Proton/files/3438730/steam-916730.log)

**Comment by kisak-valve** [comment]
Hello @galaxite, `eventfd: Too many open files` in your log is the line of interest. Please run [`ulimit -Hn`](https://github.com/ValveSoftware/Proton/wiki/Requirements#fd-limit-requirements-systemd--240) and verify it gives you a high value and not 4096.

**Comment by galaxite** [comment]
Running `ulimit -Hn` returns 4096. What would be a sufficiently high number that should prevent errors like this in the future?

**Comment by kisak-valve** [comment]
https://github.com/zfigura/wine/blob/esync/README.esync suggests 1048576. The specific value will vary by game and playtime, this is just a high ceiling that should not cause trouble.

**Comment by galaxite** [comment]
Increasing the limit to 1048576 increased the amount of time that the game could be played, but this time Steam itself crashed after about five minutes of the game running. The log from this is attached.
[steam-916730.log](https://github.com/ValveSoftware/Proton/files/3443201/steam-916730.log)

**Comment by galaxite** [comment]
The issue I mentioned in my previous comment has disappeared after a steam update, and the game can now be played for as long as I want. Thank you so much for all the help!
