### ISSUE TITLE
Proton will not launch games if user's shell is fish.

### ISSUE THREAD

**Issue by flounders** [ValveSoftware/Proton#2823]
I just switched my main shell to fish. After the change any games I would try to launch with version of Proton would fail to launch. I couldn't find anything in the logs to indicate why. I started an instance of bash from fish, launched Steam from there and the games started working again.

Currently I'm running Arch Linux with kernel 5.1.12, and fish 3.0.2. The versions of Proton that I tried are 4.2-7 and 3.16-4.

**Comment by aeikum** [comment]
I'm not able to reproduce. I switched my shell to fish using chsh and relogging in, as described here: https://wiki.archlinux.org/index.php/Command-line_shell#Changing_your_default_shell THOTH running in Proton continues to work fine. I tried 3.16-9 and 4.2-7.

Did you use the same method to change your shell? What desktop environment do you use? What are some games that showed this problem? Can you attach a Proton log here?

**Comment by flounders** [comment]
I used the same procedure as in the wiki, I didn't notice problems until after I rebooted after the shell change. Currently I'm using sway (https://swaywm.org/). The two games that I have running through Proton are IL-2: 1946 and Star Trek: Starfleet Command. When I try to launch those games from Steam with fish as my default shell, it starts and stops immediately. The logs for that have fish in the name. 

[steam-15320-fish.log](https://github.com/ValveSoftware/Proton/files/3316381/steam-15320-fish.log)
[steam-364820-fish.log](https://github.com/ValveSoftware/Proton/files/3316382/steam-364820-fish.log)

When I launch Steam from a bash instance, it just works. And the logs for that have bash in the name.

[steam-15320-bash.log](https://github.com/ValveSoftware/Proton/files/3316379/steam-15320-bash.log)
[steam-364820-bash.log](https://github.com/ValveSoftware/Proton/files/3316380/steam-364820-bash.log)

I hope these are the logs you are looking for. If not just let me know how to get it for you.

**Comment by N00byKing** [comment]
Can't reproduce on Arch running sway 1.1
Same procedure used to change shell

**Comment by flounders** [comment]
So after more thorough testing on my part. I tried it on my laptop which has Arch, fish and sway and it worked there. I then tried launching it directly from fish and it was fine. My launcher is a combination of bemenu and j4-dmenu-deskop. My laptop just uses dmenu. After reverting my desktop to dmenu it's working fine now. Sorry to bother you guys.

**Comment by aeikum** [comment]
If you're happy, I guess we can forget about this, but I'm still curious to know what the problem was. Is there some incompatibility with bemenu or j4-menu-desktop? Is that worth investigating?

**Comment by flounders** [comment]
At this point I don't think it's Proton's or Steam's responsibility to fix it. I used `dex` to launch via the desktop files and that worked fine. I'll try to track down where the problem is next between bemenu or j4-menu-desktop or my configuration and see where to go next.
