### ISSUE TITLE
Joystick works but throttle is ignored

### ISSUE THREAD

**Issue by Cyclic3** [ValveSoftware/Proton#2833]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 359320

## System Information
- GPU:  Vega 56
- Driver/LLVM version:  mesa 19.0.0-1
- Kernel version:  5.0.2-1~exp1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Cyclic3/d9824cec2b3771962b77469b07abb9e5
- Proton version: 4.2-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

 [steam-9420.log](https://github.com/ValveSoftware/Proton/files/3326272/steam-9420.log)

## Symptoms 
I have just bought a T16000m HOTAS. Both the joystick and the throttle are recognised under linux (jstest-gtk works fine), and wine control on elite's prefix with proton's wine shows all axes of both joysticks to work.

However, when I try to bind the throttle to the game, it flat out ignores it, as if I was not moving any axis. The joystick works fine. If I disconnect the joystick, and just use the throttle, it continues to not work.

Any ideas?

**Comment by kisak-valve** [comment]
Hello @Cyclic3, does jstest-gtk say what axis number the throttle uses?

**Comment by Cyclic3** [comment]
@kisak-valve "js2"

**Comment by kisak-valve** [comment]
That sounds like a device node (as in `/dev/input/js2`) for the entire controller, not an axis.

**Comment by Cyclic3** [comment]
Sorry, I realised my initial description was unclear. The throttle is a distinct unit, with a distinct usb.

**Comment by Cyclic3** [comment]
i would also like to add that my previous hotas (which was a HOTAS-X, which is an all in one unit), worked fine.

**Comment by Cyclic3** [comment]
@kisak-valve If I unplug both joysticks, and then plug in in only the throttle, it still is not recognised

**Comment by Cyclic3** [comment]
I purged several things multiple times, and then it fixed itself. Sorry, and thanks for the help!
