### ISSUE TITLE
[Whitelist request] Football manager 2019

### ISSUE THREAD

**Issue by shanefagan** [ValveSoftware/Proton#2837]
# Whitelist Request
- Football manager 2019
- 872790

## System Information
- GPU: RX480
- Driver/LLVM version: Mesa 19.0.6-1 
- Distro version: Manjaro Gnome
- https://gist.github.com/shanefagan/43e640e28a3dc354a8ac0f10fa2d9964
- Proton version: 4.2-7

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [x] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

Press play and it just works on the current Proton build. Works better than Windows for my system with 60fps consistent on max settings.

**Comment by kisak-valve** [comment]
Hello @shanefagan, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2123#issuecomment-505864741.
