### ISSUE TITLE
SCP: Secret Laboratory (700330)

### ISSUE THREAD

**Issue by Qvaut** [ValveSoftware/Proton#2839]
# Compatibility Report
- Name of the game with compatibility issues:SCP: Secret Laboratory
- Steam AppID of the game:700330

## System Information
- GPU: NVIDIA GTX 720m
- Driver/LLVM version:340.107
- Kernel version: 4.15.0-52-generic #56~16.04.1-Ubuntu SMP Thu Jun 6 12:03:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Link to full system information report as [Gist]:https://gist.github.com/Qvaut/7fbe8ee550188045038d3b03532d7b5e
- Proton version:4.2-8

## I confirm:
- Yes that I haven't found an existing compatibility report for this game.
- Yes that I have checked whether there are updates for my system available.
[bootstrap_log.txt](https://github.com/ValveSoftware/Proton/files/3334186/bootstrap_log.txt)
![Снимок экрана от 2019-06-27 13-20-08](https://user-images.githubusercontent.com/52280681/60259741-9320b000-98e0-11e9-90c0-7fec6a1a720c.png)

**Comment by kisak-valve** [comment]
Hello @Qvaut, there's 2 variants of the nVidia 720M video card, one that supports Vulkan and the other that does not. The GF in `NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (rev a1)` of your system information indicates that you have the Fermi generation variant, which does not support Vulkan.

Proton includes DXVK which translates DirectX 11 to Vulkan and your video card is unsupported, but you may have some luck with adding `PROTON_USE_WINED3D=1 %command%` to the game's launch options to tell Proton to use the DirectX 11 to OpenGL render path.

Alternatively, it looks like there's a native linux beta branch that you can try.

**Comment by agent188** [comment]
The native version under linux is broken

**Comment by Qvaut** [comment]
Oh no.
![Снимок экрана от 2019-06-28 19-57-22](https://user-images.githubusercontent.com/52280681/60358558-0d375e80-99df-11e9-898a-2461dd12834d.png)

**Comment by agent188** [comment]
My friend inserted the startup parameters not there)

**Comment by agent188** [comment]
My friend's problem is solved
