### ISSUE TITLE
Risk of Rain 2 multiplayer broken on latest proton (4.8-8)

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [ValveSoftware/Proton#2841]
# Compatibility Report
- Name of the game with compatibility issues: Risk Of Rain 2
- Steam AppID of the game: 632360

## System Information
- GPU: GTX 770
- Driver/LLVM version: nvidia 430.26 
- Kernel version: 4.15.0-52-generic 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/A-UNDERSCORE-D/9f7be2490a5ae792fd6fb78a3b4d3cee
- Proton version: 4.2-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-632360.log](https://github.com/ValveSoftware/Proton/files/3336136/steam-632360.log)

## Symptoms 

Risk of Rain 2's multiplayer system does not appear to work

## Reproduction

1. Open RoR2
1. Hit multiplayer
1. notice the greyed out options

**Comment by kisak-valve** [comment]
Hello @A-UNDERSCORE-D, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2476#issuecomment-506461750.
