### ISSUE TITLE
Moss (846470)

### ISSUE THREAD

**Issue by DerRidda** [ValveSoftware/Proton#2843]
# Compatibility Report
- Name of the game with compatibility issues: Moss 
- Steam AppID of the game: 846470

## System Information
- GPU: Nvidia GTX 1080 Ti
- Driver/LLVM version: Nvidia 430.26
- Kernel version: 5.1.14
- Proton version: 4.2-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Fails to create input device. No controllers/hands rendered in-game.

[steam-846470.log](https://github.com/ValveSoftware/Proton/files/3339428/steam-846470.log)

Issue identical to #2836 

Requires newer wrapper. Historical ProtonDB reports show the game probably used to run perfectly: https://www.protondb.com/app/846470

## Reproduction
 Play game on Linux.

**Comment by mimattr** [comment]
> Fails to create input device. No controllers/hands rendered in-game.

Also experiencing the same issue, [Moss](https://store.steampowered.com/app/846470) is currently unplayable as hands are required for interaction but not visible.

## System Information
- GPU: **RTX 2060**
- Driver/LLVM version: **NVIDIA 430.26**
- Kernel version: **4.15.0-54-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **4.2-9**
- SteamVR version: **1.6.4**

## I confirm:
- [x] that I have checked whether there are updates for my system available.

[steam-846470.log](https://gist.github.com/mimattr/23f0d94cf9f3d5bf720ddaa55822b7c9)

## Reproduction
1. Select the title within your `Library` using the Steam client and press the `Play` button

**Comment by aeikum** [comment]
We updated our openvr support in Proton 4.11. Can you please retest with 4.11 and see if this is working now?

**Comment by mimattr** [comment]
> Can you please retest with 4.11 and see if this is working now?

This issue appears to be resolved with **Proton 4.11**, great work as usual from @aeikum and the team!

## System Information
- GPU: **RTX 2060**
- Driver/LLVM version: **NVIDIA 430.40**
- Kernel version: **5.0.0-23-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **4.11-1**
- SteamVR version: **1.6.10**

**Comment by DerRidda** [comment]
Works fine now with Proton 4.11.

**Comment by mimattr** [comment]
> Works fine now with Proton 4.11.

@DerRidda Please close this issue if you're happy it's resolved, thanks.

**Comment by agalakhov** [comment]
This seems to reappear under new versions of Proton in both Moss and Moss Book 2.
