### ISSUE TITLE
Poker Night at The Inventory (31280) black screen with GL_INVALID_OPERATION 

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#2846]
Culprits: The Sims 3 and Poker Night at The Inventory
Steam AppID of the games: 47890 and 31280

System Information
- GPU: NVIDIA Corporation GeForce MX150
- Driver/LLVM version: 4.6.0 NVIDIA 430.26
- Kernel version: 4.15.0-54-generic
- [System Information Gist](https://gist.github.com/swoodmood/5ffb8c4c5dc58ab81092d2be1a242b82)
- Proton versions: 3.16-4 and 4.2-9

Relevant logs:
[steam-47890.log](https://github.com/ValveSoftware/Proton/files/3343558/steam-47890.log)
[steam-31280.log](https://github.com/ValveSoftware/Proton/files/3343559/steam-31280.log)

Symptoms: 
This is a weird one. This bug should not happen, yet it does. In both cases I boot the game up, the audio plays, but the screen is black and the game cannot be interacted with. I am also the only person, according to ProtonDB, to report an error like this. The part I'd like to bring attention to is this one:
`45125.871:0027:0035:err:d3d:wined3d_debug_callback 0x1f5ad0: "GL_INVALID_OPERATION error generated. Source and destination dimensions must be identical with the current filtering modes.". `

This one appears in both logs, meaning the error is the same in both games. It appears to be some form of openGL rendering error, but I couldn't find anyone else reporting the error in the context of Proton, only some vague forum posts featuring the error on running WINE with Call of Duty 2, and the thread did not contain any answers. 

Reproduction:
This is a tricky one. As I am the first to discover this error and the link between these games, I'm not sure if it can be replicated. The steps I go through to cause this error is simply launching either game as normal, with the tweak for sims 3. To replicate this you'd have to share my OS, graphics card, driver and kernel version, I think.

**Comment by kisak-valve** [comment]
Hello @swoodmood, let's focus on Poker Night at The Inventory in this issue report because that game is on the whitelist.

**Comment by aeikum** [comment]
Does turning off the Steam Overlay help?

**Comment by ghost** [comment]
> Does turning off the Steam Overlay help?

I just tested, turning off the Steam Overlay does nothing I'm afraid. Thanks for the advice anyways!

**Comment by aeikum** [comment]
According to one of our d3d devs, this can be caused by certain anti-aliasing settings. See these winehq bugs:
https://bugs.winehq.org/show_bug.cgi?id=39649
https://bugs.winehq.org/show_bug.cgi?id=37175
Are you able to turn off anti-aliasing somehow? Maybe by editing config files directly. I wonder why other users haven't seen this; could be specific to your GPU or for some reason AA got turned on for you but not for others.

**Comment by ghost** [comment]
> According to one of our d3d devs, this can be caused by certain anti-aliasing settings. See these winehq bugs:
> https://bugs.winehq.org/show_bug.cgi?id=39649
> https://bugs.winehq.org/show_bug.cgi?id=37175
> Are you able to turn off anti-aliasing somehow? Maybe by editing config files directly. I wonder why other users haven't seen this; could be specific to your GPU or for some reason AA got turned on for you but not for others.

Thank you for the help, but Anti-Aliasing was already disabled in the default settings of Sims 3. I played around with the Options.ini files anyways but no progress. 

As for Poker Night at The Inventory, I couldn't find any config file related to it, "prefs.prop" could not be opened via terminal or any of my text editors. Attempts at changing the file extension didn't work either, so on this part I am stuck, sorry.

**Comment by kisak-valve** [comment]
Hello @swoodmood, although it's most likely not a factor, can you check if you're using the anti-aliasing override settings in nVidia's X settings config?

**Comment by ghost** [comment]
Holy smokes on a golden gun, you're spot on the money! I vaguely recall enabling this setting back when I first got the x-settings to properly work, and disabling it did the trick for Poker Night at The Inventory. Thank you Kisak! We have solved a mystery!

**Comment by tehno1** [comment]
Hey there! I hope you're doing well. I saw your post about the black screen issue with GL_INVALID_OPERATION on Poker Night at The Inventory and The Sims 3. That sounds like a frustrating bug to deal with! Have you tried reaching out to the developers or searching the internet for solutions? It's always worth a shot. I'm sure they can help you and make your mental health better. For a long time, I have been playing Jeetwin online casino at [jeetwinonline.com](http://jeetwinonline.com) as it is a great way to pass the time. The game also allows you to relax and enjoy the process. I wish you good luck in fixing the error!
