### ISSUE TITLE
The cursor does not work in games via proton and steamcompmgr

### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/Proton#2849]
#### Your system information

* Steam client version:1561768292
* SteamOS version: 2.0 1 2 190
* Opted into Steam client beta?: [Yes/No] yes
* Opted into SteamOS beta?: [Yes/No] yes
* Have you checked for updates in Settings > System?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.
The cursor does not work in games via proton after the first click. Check it out in the witcher 3 and fallout new vegas.
#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by flibitijibibo** [comment]
There's a good chance this is a duplicate of https://github.com/ValveSoftware/SteamOS/issues/475.

**Comment by Vladislavuz** [comment]
The cursor issue resolved with the upgrade to Proton 5.0 on SteamOS.
