### ISSUE TITLE
DmC: Devil May Cry (220440) crash to desktop with controller

### ISSUE THREAD

**Issue by VennStone** [ValveSoftware/Proton#2850]
# Compatibility Report
- Name of the game with compatibility issues: DmC: Devil May Cry
- Steam AppID of the game: 220440

## System Information
- GPU: RTX 2060
- Driver/LLVM version: 418.52.14
- Kernel version: 5.1.15
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/LGCW/a328efe88882ad51ae54cfceebd4f200
- Proton version: 4.2-9

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

 
LOG https://gist.github.com/LGCW/d0cc68de73c9f6311bf9abfb9d5231dc

## Symptoms 
Crashes to desktop when Xbox 360 or Steam controller input is registered. 

Note: dotnet40 was installed using winetricks to make the game launch. 
## Reproduction
Pressing 'start' at title screen.

**Comment by kisak-valve** [comment]
Hello @LGCW, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/820#issuecomment-507418538.
