### ISSUE TITLE
DOOM (2016) Crash on launch (VK)

### ISSUE THREAD

**Issue by Elkasitu** [ValveSoftware/Proton#286]
Having experienced the same problems presented in #69, I went ahead and set `+r_renderAPI 1` in the game's launch options, unfortunately this doesn't work either, here's the error log:

```
Configured log listener print-redirect tags
Added structured log listener print-redirect
Added structured log listener mp-cloud-gobbler
2018-08-23T16:08:26.217+02:00 LOG: Process started
Added structured log listener aws-kinesis-logger
Winsock Initialized
------ Initializing File System ------
Current search path:
    - C:/users/steamuser/Saved Games/id Software/DOOM/base/
    - Z:/home/elkasitu/.local/share/Steam/steamapps/common/DOOM/base/
------ File System initialized.
------ Command Line ------
 "Z:\home\elkasitu\.local\share\Steam\steamapps\common\DOOM\DOOMx64vk.exe"  +r_renderAPI -2 
2018-08-23T16:08:26.219+02:00 LOG: Command Line: "Z:\home\elkasitu\.local\share\Steam\steamapps\common\DOOM\DOOMx64vk.exe"  +r_renderAPI -2 
------ CPU Information ------
    1 CPU package, 4 physical cores, 4 logical cores
    3400 MHz    Intel CPU with MMX & SSE & SSE2 & SSE3 & SSSE3 & SSE41 & SSE42 & AVX
    32768 kB 1st level cache, 262144 kB 2nd level cache, 6291456 kB 3rd level cache
    15968 MB System Memory
initializing resource container gameresources.resources
initializing resource container gameresources.patch
idLib::SetProduction( PROD_PRODUCTION )
------- Initializing renderSystem --------
PreliminaryRenderSetup
...registered window class
FATAL ERROR: vkCreateInstance failed with error (VK_ERROR_INITIALIZATION_FAILED)
Dumped console text to C:\users\steamuser\Saved Games\id Software\DOOM\base\ErrorLog_08-23-2018__04-08-26pm.txt.

idRenderSystem::Shutdown()
log file 'qconsole.log' opened on Thu Aug 23 16:08:26 2018

CrashHandler: Storing data and writing local report.
idStackTracer::GetSource: Failed
No address, error: 2
idStackTracer::GetSource: Failed
No address, error: 2
idStackTracer::GetSource: Failed
No address, error: 2
idStackTracer::GetSource: Failed
No address, error: 2
idStackTracer::GetSource: Failed
No address, error: 2
idStackTracer::GetSource: Failed
No address, error: 2
idStackTracer::GetSource: Failed
idStackTracer::GetSource: Failed
```

System information:

```
Arch Linux x86_64
4.18.3-arch1-1-ARCH
Intel i5-4460 (4) @ 3.400GHz
AMD Radeon R9 280
vulkan-radeon 18.1.6-1
mesa 18.1.6-1
```

Let me know if you need any more information.

**Comment by vanyasem** [comment]
Please read the requirements before posting issues. Your mesa is outdated. https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md#core-opengl-games-doom-2016-google-earth-vr-etc

**Comment by LeJimster** [comment]
Also make sure you have all the correct Vulkan drivers installed for your GPU, I have:
vulkan-icd-loader
lib32-vulkan-icd-loader
vulkan-radeon
lib32-vulkan-radeon

You might also want to try using mesa-git which you can find on [Laurent Carlier's mesa-git repo](https://wiki.archlinux.org/index.php/unofficial_user_repositories#mesa-git)

**Comment by parkerlreed** [comment]
+1 for mesa-git. Make sure to also pull in llvm-svn, llvm-libs-svn and the clang packages from the same repo.

**Comment by Elkasitu** [comment]
Thanks for the help, using Laurent Carlier's binaries I was able to run Doom (2016) using the OpenGL backend, however I still get the same error for the VK backend.

I installed the following packages from the `mesa-git` repo:
```
vulkan-radeon
vulkan-icd-loader
mesa
llvm-svn
llvm-libs-svn
clang-svn
clang-tools-extra-svn
```
and their lib32 variants for those who have it.

It's playable as it is but Vulkan should have better performance if the Windows version is any indication.

**Comment by parkerlreed** [comment]
mesa-git repo has mesa as `mesa-git`

None of the packages actually have the same names as official so they aren't auto replaced.

````
mesa-git
lib32-mesa-git
vulkan-radeon-git
````

**Comment by Elkasitu** [comment]
Yes sorry I meant I installed the mesa package from the mesa-git repo so mesa-git, vulkan-radeon-git, etc.

![screenshot_20180823_182125](https://user-images.githubusercontent.com/4931545/44538398-6f5d6e00-a701-11e8-89f3-7783e6f414cb.png)

**Comment by LeJimster** [comment]
One last thing to check is that you are running the **AMDGPU** kernel and not the **radeon** kernel.  Vulkan won't work with the latter.

Use this command to check:
`lspci -k | grep -EA3 'VGA|3D|Display' `

**Comment by Elkasitu** [comment]
@LeJimster Thank you, indeed amdgpu requires extra steps to be enabled for my GPU, it works perfectly now :-)

**Comment by rkunschke** [comment]
I need these two arguments to launch the game:
+com_SkipIntroVideo 1 +r_renderapi 1
maybe this ist the solution for someone else :)

**Comment by LeJimster** [comment]
@rkunschke If you are a mesa user you need a recent 18.2 or possibly even 18.3 for OpenGL to work.

**Comment by lautaroramos** [comment]
If anyone crashes into this same error, I found the solution adding the following line to launch options 
`VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json %command% +r_renderAPI 1`
Of course you would replace that path for the one that matches your system.

I found this solution in the following post on reddit
https://www.reddit.com/r/linux_gaming/comments/r0cbcp/cant_seem_to_run_doom_2016_in_vulkan_mode/

**Comment by fontanon** [comment]
> I need these two arguments to launch the game: +com_SkipIntroVideo 1 +r_renderapi 1 maybe this ist the solution for someone else :)

Worked like a charm
