### ISSUE TITLE
monitor goes to sleep when using controller

### ISSUE THREAD

**Issue by codeman101** [ValveSoftware/Proton#2860]
I noticed when I play with my xbox 360 controller for an extended period of time my monitor shuts off as if it thinks the machine is inactive until I wake it up with the mouse. I don't think this is an issue for native Linux games just ones that are Windows only. I didn't put a game in the title because I think it's a general issue but for those who want to know the game I discovered this issue with is fable anniversary.

**Comment by kisak-valve** [comment]
Hello @codeman101, this issue is already being tracked at #287 / https://github.com/ValveSoftware/steam-for-linux/issues/1693. Closing as a duplicate.

**Comment by codeman101** [comment]
@kisak-valve 

Ok cool yeah I figured it probably was already mentioned but I couldn't find it. :+1:
