### ISSUE TITLE
The Talos Principle (257510) Displays, "Unable to set display" when launching from Ubuntu 19.04 AMD64

### ISSUE THREAD

**Issue by jandrusk** [ValveSoftware/Proton#2861]
# Compatibility Report
- Name of the game with compatibility issues: The Talos Principle
- Steam AppID of the game:257510

## System Information
- GPU: ATI Cape Verde PRO / Venus LE / Tropo PRO-L [Radeon HD 8830M / R7 250 / R7 M465X]
- Driver/LLVM version: Radeon
- Kernel version:  5.0.0-20-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/jandrusk/8b221c0e6baf2e06be2f59e02eb7b3fb

- Proton version:

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

## Symptoms 
When attempting to run The Talos Principle on Ubuntu 19.04 AMD64, I keep getting the error, "Unable to set display". I've tried updating the graphics driver via an PPA for the Radeon driver and some other suggestions from Google search results, but nothing seems to resolve the issue. 

## Reproduction
- Anytime I launch The Talos Principle game from the Steam client.

**Comment by jandrusk** [comment]
[Talos.All.log](https://github.com/ValveSoftware/Proton/files/3365189/Talos.All.log)
[Talos.log](https://github.com/ValveSoftware/Proton/files/3365190/Talos.log)
[Talos_Unrestricted.All.log](https://github.com/ValveSoftware/Proton/files/3365191/Talos_Unrestricted.All.log)
[Talos_Unrestricted.log](https://github.com/ValveSoftware/Proton/files/3365192/Talos_Unrestricted.log)

**Comment by kisak-valve** [comment]
Hello @jandrusk, this game has a native linux version and the logs indicate you're using it without Proton involved, so your issue is unrelated to Proton.

~That set aside, you may have some luck with the workarounds suggested at https://steamcommunity.com/app/257510/discussions/0/541906348056987270/#c541906989389482231.~ 

Closing as out-of-scope.

**Comment by kisak-valve** [comment]
On second thought, Talos Principle dropped support for OpenGL (available in a legacy branch) a while back, and it looks like you've not encountered a suggestion similar to https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games to get Vulkan working on your SI-generation video card.

**Comment by ranplayer** [comment]
I've noticed two issues with The Talos Principle running on  Proton 9.0-4, 10.0-3 (RC) and Experimental (2025-10-24)

1. Minor: it displays an AMD driver issue (but you can skip it)

<img width="904" height="516" alt="Image" src="https://github.com/user-attachments/assets/49024286-c00d-4266-bdf2-b3371e99943d" />


2. If you select the Vulkan renderer in-game, it crashes ([steam-257510.tar.gz](https://github.com/user-attachments/files/23375386/steam-257510.tar.gz))

Specs:
- OS: Arch
- Kernel: 6.12.57
- GPU: RX 6700 XT (Mesa 25.2.6)
- CPU: Ryzen 7 5700G
- DE: Plasma 6.5.1 (Wayland)

**Comment by ranplayer** [comment]
The game no longer works properly with Proton 11.0-1. After the intro logos, you need to mouse click to display a "login credentials form" that doesn't work and you can't pass by. This form is not displayed with Proton 10.

Proton logs: [steam-257510.tar.gz](https://github.com/user-attachments/files/29854320/steam-257510.tar.gz)

Specs:
- OS: Arch
- Kernel: 6.18.35 (ntsync)
- GPU: RX 6700 XT (mesa 26.0.6)
- CPU: Ryzen 7 5700G
- DE: Plasma 6.6.5 (wayland)
