### ISSUE TITLE
Peggle Nights (3540)

### ISSUE THREAD

**Issue by edoantonioco** [ValveSoftware/Proton#2867]
# Compatibility Report
- Name of the game with compatibility issues: Peggle Nights
- Steam AppID of the game: 3540

## System Information
- GPU:  GTX 960M
- Driver/LLVM version: nvidia 430.26 
- Kernel version: 5.12
- Link to full system information report as [Gist](https://gist.github.com/):
https://gist.github.com/edoantonioco/3806601fb1ec35e634e5e0670f95104a
- Proton version: 4.2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

https://gist.github.com/edoantonioco/c8288bdd1ba6b7cc7d77ea63ec6bee69

## Symptoms 
![Screenshot_20190709_073733](https://user-images.githubusercontent.com/5560824/60892927-31840e00-a21d-11e9-95b5-a9ae3bfd8b65.png)

## Reproduction

run the game

**Comment by kisak-valve** [comment]
Hello @edoantonioco, this game is already being tracked at #340. Closing in favor of the existing issue report.

**Comment by edoantonioco** [comment]
Fair enough, I did now saw that when I searched with the name of the game.
