### ISSUE TITLE
Some Games work in Steam for windows using Lutris/Wine, but not with SteamPlay/Proton

### ISSUE THREAD

**Issue by rednaxela600** [ValveSoftware/Proton#2869]
## System Information
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3375294/system_info.txt)

## Example Games
Tales of Symphonia (372360): [steam-372360.log](https://github.com/ValveSoftware/Proton/files/3375300/steam-372360.log)
Sniper Elite V2 (63380): [steam-63380.log](https://github.com/ValveSoftware/Proton/files/3375301/steam-63380.log)

## Symptoms 
Some games I have encountered do not work in Proton as of yet, I believe it might be Steam DRM issues. I have listed the examples I have seen, and reading around I believe this issue probably affects a fair number of other games. 

I think it would be worth while if we could collect a list here of such games from other users to compare against and possibly fix. I'm not expecting this thread to stumble on a one size fits all solution for them, but it might help debug solutions to some of them by comparing similarities. At the very least it could be a resource for some people to find and get their games running until a fix is found for their titles.

In the cases above, Tales of Symphonia just launches to a black screen for me using any proton version, and Sniper Elite V2 just closes after clicking play in the launcher. Running steam for windows in Wine (staging 4.12 atm) will allow them to run.

I wanted to test Steam for Windows in Proton to see if proton could run the games themselves after this hurdle, but Proton would not run Steam for Windows on my end.

## Reproduction
Run the games above through native steam and they will crash. Run them with Steam for Windows in wine and they work (mostly).

**Comment by kisak-valve** [comment]
Hello @rednaxela600, we're using one issue report per unofficially supported game title. Tales of Symphonia is being tracked at #822 and Sniper Elite V2 is at #392. While there are issues with these games and Proton, they do not appear to be related to each other. Feel free to add your per-game findings to each of these issue reports.

Sniper Elite V2 is using CEG (#753).

Closing in favor of the existing issue reports.
