### ISSUE TITLE
Steam overlay makes game drop to 1fps (EDIT: Wine bug related to mouse polling rate)

### ISSUE THREAD

**Issue by Zorrototo** [ValveSoftware/Proton#2875]
I have an issue wit hthe Steam overlay in my Proton games. After using the overlay a lot (opening chats, accepting game invite, using the browser), I have an issue where the fps drops to 1fps as soon as I make circles with my mouse. I can fairly easily reproduce the issue in games like Killing Floor 2, or Deep Rock Galactic. I just have to play a little, do some stuff multiple time in overlay (opening overlay, accepting game invite, closing overlay, opening overlay again, opening browser, replying to chat, and so on). Then if I stand still in game I have proper fps, but as soon as I move the mouse it drops FPS, to the point if I do little circles in game or in overlay, fps drops to 1 and go instantly up if I stop moving mouse.

System information: https://gist.github.com/Zorrototo/533bb4f3b9d8d5abc137cd8cf5c00f02

I can provide more information just tell me what you need.

**Comment by Zorrototo** [comment]
May be related to that issue: https://github.com/ValveSoftware/Proton/issues/2455
I have a G400s Logitech mouse and polling rate is reported at 1000Hz when using the command `sudo evhz` (no specific drivers for this mouse on Linux).

For now I stopped using the Steam overlay and that seemed to fix this issue. I will try to re-enable it in these games I have issues with, and try to mess with the polling rate https://wiki.archlinux.org/index.php/Mouse_polling_rate#Set_polling_interval to see if that is my issue, and will report back.

**Comment by Zorrototo** [comment]
I have set the mouse polling rate to 125Hz (was 1000Hz by default) and so far so good, no issue with Steam overlay yet when I do little circles.

Unfortunately, a bug report for this issue has been made on Wine forums https://bugs.winehq.org/show_bug.cgi?id=46976 (the root of the issue being actually a problem outside of Proton with plain original WINE), but they consider it now a "NOTOURBUG" bug, because the guy reporting the issue fixed it by updating his bios, but we are many many people with this issue (FPS dip with 1000Hz polling rate for the mouse), just look at the Proton issue linked above, and I can't say that it is a motherboard issue, I personally have latest bios for my motherboard and they are not updating it since a few years already so...

**Comment by rednaxela600** [comment]
I have a Logitech G600 and I've noticed this as well. I made a comment about it  in #1235 as that was one of the first games I was actually using the overlay for web browsing in after switching to linux. I mistakenly thought it was DDDA, but I've seen it in just about every game after web browsing in the overlay. The more I use the overlay, the worse the issue becomes. I'm gonna try the 500Hz option that Piper gives me and see how that goes for a little while.

**Comment by Zorrototo** [comment]
I see absolutely no difference with the mouse polling rate set to 125Hz and it definitely fixed this huge FPS drop for me. If you still have issue try directly 125Hz ;)

**Comment by zelifcam** [comment]
From the reading I’ve done it’s impossible to drop the polling rate if your using usb3? My motherboard does not have usb2 and all the suggestions in the arch wiki do not work. Mouse always has rate of 1000.

**Comment by Zorrototo** [comment]
https://wiki.archlinux.org/index.php/Mouse_polling_rate#Polling_rate_not_changing
> The xhci-hcd module should respect the interval requested by the device, so check the documentation for the device for a hardware or firmware setting.
> 
So check if you can do this on the mouse, for example with a custom firmware/driver from AUR, or directly from official driver from a supported OS.

> A work-around that may help is to connect the device to a port using a different driver.
> 
> Another work-around is to disable xHCI. There might be a BIOS setting for this or you can do so by blacklisting the xhci-hcd module. However, either way will cause any USB 3 ports to act as USB 2 as the kernel will use the ehci-hcd module instead.
