### ISSUE TITLE
no proton games starting

### ISSUE THREAD

**Issue by fedorovenskiy** [ValveSoftware/Proton#2878]
my steam is on NTFS but I am owner and problem is not in NTFS
here is steam logs
https://termbin.com/2hou

**Comment by dreamer** [comment]
Please try without native runtime, only steam runtime is officially supported.

**Comment by kisak-valve** [comment]
Hello @fedorovenskiy, Proton is known to have a hard time with NTFS. There are various other NTFS-related issue reports on this issue tracker that have workarounds in the comments.

Can you share how the drive is mounted and what `mount` gives for that partition.

**Comment by fedorovenskiy** [comment]
@kisak-valve, line from fstab
UUID=7D83C07E493697F1               /home/fedya/AllFiles ntfs-3g defaults,x-gvfs-show,exec,permissions,auto,umask=022,uid=1000,gid=1001 0 0

**Comment by kisak-valve** [comment]
Comparing the notes at https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows, maybe umask=022 is giving Proton trouble?

**Comment by fedorovenskiy** [comment]
@kisak-valve, no, I,ve removed umask and nothing changed an proton doesn't work

**Comment by dreamer** [comment]
@fedorovenskiy can you upload logs with native runtime disabled? The logs you uploaded earlier are missing info from actual Proton invocation. I presume you were trying to play Hitman 2?

**Comment by fedorovenskiy** [comment]
@kisak-valve,yes, I am trying to launch Hitman 2, but the logs are same with all proton games
Here is new logs
https://termbin.com/tuzj

**Comment by dreamer** [comment]
OK, now - please run the game using launch options `PROTON_LOG=1 %command%`; log will be left in your home directory (it will be called `steam-<appid>.log`). It would be also helpful if you attached a file with your Steam System Information (Help -> System Information), maybe it will include some helpful information.

**Comment by fedorovenskiy** [comment]
@dreamer, no, it gives the same information that in steam logs

**Comment by dreamer** [comment]
Well, we can't help you to debug the issue if you don't provide us with proton logs nor system information, so…

**Comment by fedorovenskiy** [comment]
@dreamer 
[steam-863550.log](https://github.com/ValveSoftware/Proton/files/3388592/steam-863550.log)

**Comment by dreamer** [comment]
13655.984:0008:0009:err:file:init_redirects /home/fedya/AllFiles/SteamLibrary/steamapps/compatdata/863550/pfx/dosdevices/c:/windows: Нет такого файла или каталога ("No such file or directory")
    ...
    13656.022:000a:000b:err:wineboot:main Cannot set the dir to L"C:\\windows" (2)
    ...
    13656.347:000a:000b:err:shell:SHGetFolderPathAndSubDirW Failed to create directory L"C:\\users\\steamuser\\Application Data".
    13656.349:000a:000b:err:shell:SHGetFolderPathAndSubDirW Failed to create directory L"C:\\users\\steamuser".
    13656.351:000a:000b:err:shell:SHGetFolderPathAndSubDirW Failed to create directory L"C:\\users\\steamuser\\Local Settings\\Application Data".
    ...    
    13656.476:0008:000f:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    13656.476:0008:000f:err:winediag:nodrv_CreateWindow The explorer process failed to start.
    ...
    13656.485:0008:0009:err:steam:run_process Failed to create process L"\"\\\\?\\unix\\home\\fedya\\AllFiles\\SteamLibrary\\steamapps\\common\\HITMAN2\\Launcher.exe\"": 1115

OK, so indeed Steam has no full write access to your Steam Library and can't generate Wine prefix. I noticed in your `mount` line that your user id (1000) does not match group id (1001) - this might be a Manjaro thing or maybe a typo sowhere. Can you confirm, that you belong to group with id 1001? Type command `id` in terminal and paste the output, it should look something like this:

    $ id
    uid=1000(dreamer_) gid=1000(dreamer_) groups=1000(dreamer_),10(wheel),1002(docker)

Also, it would be helpful to see your Steam System information, as I mentioned earlier, this way I could check if you're using Steam installed from Flatpak and maybe there's some sandboxing going on or confirm exact version of steam runtime, if you use Steam Beta, etc. Upload that info somewhere, please.

**Comment by fedorovenskiy** [comment]
@dreamer 
uid=1000(fedya) gid=1001(fedya) groups=1001(fedya),3(sys),90(network),98(power),991(lp),998(wheel),1000(autologin)

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.1.16-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12005000
    X Window Manager:  KWin
    Steam Runtime Version:  jenkins-steam-runtime-beta-release_0.20190320.2

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 430.26
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1c82
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1600 x 900
    Desktop Resolution: 1600 x 900
    Primary Display Size: 17.44" x 9.80" (20.00" diag)
                                            44.3cm x 24.9cm (50.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  16003 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Total Hard Disk Space Available:  205606 Mb
    Largest Free Hard Disk Block:  145410 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by jarrard** [comment]
This is what I use on my NTFS SSD's and they benchmark 733MB/s write speeds (normally its only 200 or so).

NTFS Flags used for optimal performance:

> noatime,async,big_writes,inherit,windows_names,uid=1000,gid=1000,rw,user,exec,umask=000 0 0

Also you will want to symlink the compatdata folder (~/.steam/steam/steamapps/) to your NTFS steamapps folder location, it recommends this in the wiki for proton.

**Comment by fedorovenskiy** [comment]
@jarrard will this flags good for hdd?

**Comment by dreamer** [comment]
@fedorovenskiy do you actually have a flag named `permissions` in your `fstab`? Such flag does not exist.

**Comment by jarrard** [comment]
> @jarrard will this flags good for hdd?

Yeah I've had no problems, except for a amazon 5400rpm Hybrid drive dying on me recently causing me to loose 200gb of data... :(  not going to buy seagate again!

**Comment by fedorovenskiy** [comment]
Nothing has helped to me. Proton games haven't been starting. So, I've converted my drive from NTFS to EXT4 (I've just moved all my data to the another drive, removed my partition, created new ext4 and moved data back to that drive) and all works perfect, I've just set owner to me (chown -R user:user /directory/where/I/mount/my/drive).
