### ISSUE TITLE
xPlane 11 (269950) crashes immediatly after launch

### ISSUE THREAD

**Issue by verkohltesToast** [ValveSoftware/Proton#2879]
#### My system information

* Steam client version:  v018
* Distribution (e.g. Ubuntu): Void Linux x86_64 (Kernel: 4.19, Mate version 1.22.1)
* I have checked for system updates

#### The Issue:
After starting the Game "xPlane 11" viaSteamPlay (any Proton version) it first starts the loading screen normally. Then it crashes and shows a message telling me that the software has crashed. The complete starting process is in the following Video:
[2019-07-12 17-18-27.flv.zip](https://github.com/ValveSoftware/steam-for-linux/files/3386996/2019-07-12.17-18-27.flv.zip)
I'm sorry for sending it in German but changing it would require a reinstallation of xPlane. 

#### Steps for reproducing this issue:
I think (didn't try):
1. Install Void Linux with Mate desktop
2. Install Steam and xPlane 11 
3. Launch the Game

**Comment by kisak-valve** [comment]
Hello @verkohltesToast, issues with games using Proton are being tracked in the Proton issue tracker, so I've transferred this issue report.

Please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box. Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by verkohltesToast** [comment]
I'm sorry for this mad question but what exactly do you mean with $HOME/steam-$APPID.log? I looked up my home, steam and xPlane directory and didn't find such a file. But I just set my Steam language to English and copied the system information here: https://gist.github.com/verkohltesToast/3fa5ac52961c1b52a45e8bd0977b165f

**Comment by verkohltesToast** [comment]
Thank you for your help

**Comment by kisak-valve** [comment]
When running a game with PROTON_LOG=1 set, a log should be generated in your home folder. That set aside, your issue is that you're currently using mesa/nouveau which does not support Vulkan, which is a prerequisite for DXVK. Please install a recent nVidia proprietary driver version and retest.

Alternatively, you could try adding `PROTON_USE_WINED3D=1 %command%` to tell Proton to use the DirectX 11 to OpenGL render path, but expect substantial performance issues.

**Comment by verkohltesToast** [comment]
I swichd to the proprietary driver and the Game runs now. Thank you very much for your help
