### ISSUE TITLE
Muse Dash (774171) crashes immediately after launch

### ISSUE THREAD

**Issue by kbeckmann** [ValveSoftware/Proton#2880]
# Compatibility Report
- Name of the game with compatibility issues: Muse Dash
- Steam AppID of the game: 774171

## System Information
- GPU: Radeon VII
- Driver/LLVM version: 19.2.0-devel / LLVM 8.0.0 *using mesa-aco-git 19.2.0_devel.113513.b8daf015462-1*
- Kernel version: 5.2.0-arch2-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kbeckmann/559270ca03389296d209aa53a7bd20cf
- Proton version: 4.2-9

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

The game crashes during launch.

## Reproduction

Launch the game.

Crash report from the game: [error.log](https://github.com/ValveSoftware/Proton/files/3388112/error.log)

Crash dump from the game: [crash.zip](https://github.com/ValveSoftware/Proton/files/3388115/crash.zip)

Proton log: [steam-774171.log](https://github.com/ValveSoftware/Proton/files/3388068/steam-774171.log)

I tried running with and without ACO ( by setting RADV_PERFTEST=llvm ), no difference.

I debugged this a bit...

During launch, it crashes. Looking at the crash, it crashes in 
EIP:    0x1c335069

During this run, ZFProxyWeb.dll was loaded with the base address 0x1c300000 (seen in the proton log), so the actual address is 0x35069.

Disassembling ZFProxyWeb.dll shows that 0x35069 is inside the function Concurrency::details::SchedulerBase::Initialize.

Googling this function, I found that it's some sort of Microsoft runtime code, docs here https://docs.microsoft.com/en-us/cpp/parallel/concrt/reference/concurrency-namespace?view=vs-2019 and some code here https://github.com/rituraj0/Old-Codes/blob/master/SchedulerBase.cpp#L436

Based on the disassembly I am guessing it crashes here https://github.com/rituraj0/Old-Codes/blob/master/SchedulerBase.cpp#L489 , perhaps numaNodeNumber is out of bounds or m_numaInformation is incorrectly allocated. Wild guesses here!

Since the code touches upon the number of logical processors, which in my case is 64, and NUMA, I am guessing this might be a bit system specific. I'm using a 2990WX where NUMA is always enabled. Also I have 4 channel memory which could be problematic in this case. Just throwing out ideas.

I tried to disable SMT and thus get 32 threads instead (1 per core). The issue is still there unfortunately.

Please let me know if you need more logs or want me to test something.

Thanks!

**Comment by kisak-valve** [comment]
Hello @kbeckmann, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2856#issuecomment-511069697.

**Comment by kbeckmann** [comment]
Oh sorry I didn't know that. Thanks for moving it.
