### ISSUE TITLE
Tilt Brush (327140)

### ISSUE THREAD

**Issue by mimattr** [ValveSoftware/Proton#2884]
# Compatibility Report
- Name of the game with compatibility issues: **Tilt Brush**
- Steam AppID of the game: **327140**

## System Information
- GPU: **RTX 2060**
- Driver/LLVM version: **NVIDIA 430.26**
- Kernel version: **4.15.0-54-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **4.2-9**
- SteamVR version: **1.6.4**

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-327140.log](https://gist.github.com/mimattr/d39ba2d5038095bc2edb25cb1e3fa5f6)

## Symptoms
Failure to detect [Valve Index Headset](https://store.steampowered.com/app/1059530) after loading screen:
![Screenshot](https://i.imgur.com/2wDzLT1.png)

## Reproduction
1. Select the title within your `Library` using the Steam client and press the `Play` button

**Comment by kisak-valve** [comment]
Hello @mimattr, looks like Proton's SteamVR wrapper needs to be updated.

`err:vrclient:create_win_interface Don't recognize interface name: IVRInput_006` in the log should be the same as #2836 / #2882.

**Comment by mimattr** [comment]
> looks like Proton's SteamVR wrapper needs to be updated

Thanks for the confirmation @kisak-valve, will test again on the next **Proton** release.

**Comment by ebbit1q** [comment]
Works fine for me

**Comment by mimattr** [comment]
> Works fine for me

@ebbit1q Interesting, are you definitely using the latest release? (i.e. `public` branch)

https://steamdb.info/app/327140/depots

Could you provide a copy of your [Proton log](https://github.com/ValveSoftware/Proton/wiki/Proton-FAQ#how-to-enable-proton-logs) and system information for reference?

Many thanks in advance.

**Comment by aeikum** [comment]
We updated our openvr support in Proton 4.11. Can you please retest with 4.11 and see if this is working now?

**Comment by mimattr** [comment]
> Can you please retest with 4.11 and see if this is working now?

This issue appears to be resolved with **Proton 4.11**, great work as usual from @aeikum and the team!

## System Information
- GPU: **RTX 2060**
- Driver/LLVM version: **NVIDIA 430.40**
- Kernel version: **5.0.0-23-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **4.11-1**
- SteamVR version: **1.6.10**
