### ISSUE TITLE
Dead Rising 4(543460) - Doesn't start

### ISSUE THREAD

**Issue by Shelvak** [ValveSoftware/Proton#2887]
# Compatibility Report
Dead Rising 4 - 543460

## System Information
- Proton:4.2-9  (and 3.16.9)
- Distro:Manjaro Linux
- Kernel:5.1.16-1-MANJARO  (and 4.20)
- RAM:16 GB
- GPU Driver:NVIDIA 430.26 (cuda 10.1.168-4, nvidia-utils 1:430.26-1)
- GPU:NVIDIA GeForce GTX 1050 Ti
- CPU:AMD A8-3870 APU with Radeon HD Graphics
- Full steam info: https://gist.github.com/Shelvak/2872fa7b727e4bc68ded382bfc4ccfc2

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
The game show a small black window and then exits
log: [steam-543460.log](https://github.com/ValveSoftware/Proton/files/3389220/steam-543460.log)

## Reproduction
Things I tried:
environment variables I changed in user_settings.py:
- PROTON_FORCE_LARGE_ADDRESS_AWARE
- PROTON_OLD_GL_STRING
- PROTON_NO_ESYNC
- PROTON_USE_WINED3D
- PROTON_NO_D3D11 # If I put this, the black window doesn't appear and n2n process says "not responding"

If you need anything else let me know.

**Comment by kisak-valve** [comment]
Not that it helps, but the log hints that your issue is that it's trying to use an illegal cpu instruction (something that your cpu doesn't understand).

The minimum specs in Steam's store includes "Additional Notes: Not compatible with AMD CPUs that do not support SSE 4.1 multi-threading."

**Comment by Shelvak** [comment]
That explain everything... Thanks for the fast response :+1:
