### ISSUE TITLE
Trouble with getting d9vk working for Fable Anniversary (288470)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#2888]
# Compatibility Report
- Name of the game with compatibility issues: Fable Anniversary
- Steam AppID of the game: 288470

## System Information
- GPU: GeForce GTX 1060 6GB/PCIe/SSE2
- Driver/LLVM version: 4.6.0 NVIDIA 418.56
- Kernel version: 5.0.0-21-generic
- Link to full system information report as [Gist](https://gist.github.com/azsorlex/6d9cb465604c49f6497d2a7b32ee756e):
- Proton version: 4.2-9

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-288470.log](https://github.com/ValveSoftware/Proton/files/3390759/steam-288470.log)

## Symptoms 
The problems (most of them described [here](https://github.com/ValveSoftware/Proton/issues/1542)) are: the menu is dark, there are frequent black artifacts, and some wood, some stone, player and NPCs eyes are black. I tried following the fix stated in a later comment (which is referring to [this](https://github.com/Joshua-Ashton/d9vk) (found this through ProtonDB)), but when I do it, it just doesn't fix the issues.

## Reproduction
From my home directory, I ran these commands (based on the fix and my personal experience):
`git clone https://github.com/Joshua-Ashton/d9vk.git`
`cd d9vk/`
`export WINEPREFIX=~/.steam/debian-installation/steamapps/compatdata/288470/pfx`
`chmod +x setup_dxvk.sh`
`./setup_dxvk.sh install`

[This is the output for the last command](https://gist.github.com/azsorlex/c216ede69f34042b18bffdd7befa3098). Rebooting the system afterwards didn't help.

**Comment by ghost** [comment]
Did you build d9vk as per the instructions? You only show cloning the git then running setup_dxvk.sh https://github.com/Joshua-Ashton/d9vk

You also may need any missing prerequisites for building that's listed there as well.

Its not obvious from anything you typed there except maybe the missing dlls in the last gist you included: /home/alex/d9vk/x32/dxgi.dll: File not found. Skipping. **You probably didn't build d9vk**

If you have any problems building, you will need to work through them.

This isn't really a Proton problem (at least nothing to do with Valve really).

**Comment by kisak-valve** [comment]
Hello @azsorlex, as noted by @byte1024, this is outside the scope of Proton. Feel free to continue discussing your issue, but this is not an issue for Proton.

**Comment by ghost** [comment]
Took a look at this again. The instructions you probably wanted (or missed) was to grab a download from here: https://github.com/doitsujin/dxvk/releases

In order to install a DXVK package **obtained from the release page** (I linked just above this line)

Using that you do "setup_dxvk.sh install" otherwise when you grab the source code files as  you did but you need to build that first.

I don't know which works for Proton if both or if only building does. That I'm not looking into it far enough to find out ;-)

By the way, yes d9vk linked releases page is doitsujin's dxvk. https://github.com/Joshua-Ashton/d9vk see release page link.

**Comment by ghost** [comment]
> install a DXVK package obtained from the release page

Ah, I see. Didn't know about the releases thing. You linked me to the wrong repository, but after downloading from the proper one and running through the instructions, the game works flawlessly (I mean, it did freeze my computer the first time I ran it), though I haven't yet extensively tested it. I now realise that I should've posted to the d9vk issues page instead of here, but still, thank you so much for your help.

**Comment by ghost** [comment]
I don't know what happened but at least you got it :+1:
