### ISSUE TITLE
Skyrim Special Edition: No Voices and Background music

### ISSUE THREAD

**Issue by Anti-Ultimate** [ValveSoftware/Proton#289]
The game boots up perfectly fine on my GTX970, runs a bit sluggish but it's missing the Music and Speech. Have only tested until character customization right now, but it worked well until that point.

According to https://appdb.winehq.org/objectManager.php?sClass=version&iId=34366&iTestingId=102851

you need to install xact with winetricks to get working audio. Can this be included in Proton or is using stuff that winetricks does a nono?

EDIT: The game seems to ship with these libraries, as it does install the DirectX runtime at first launch.

**Comment by Anti-Ultimate** [comment]
I noticed this has already been reported

**Comment by E100Beta** [comment]
If you need temporary solution while this is being worked on, see https://github.com/ValveSoftware/Proton/issues/54 for how to use winetricks on proton prefix

**Comment by Anti-Ultimate** [comment]
I already did that, but it didn't seem to work for me @E100Beta 

EDIT: That's probably because SSE uses a 64-bit executable which xact doesn't seem to work with.

**Comment by FreeLikeGNU** [comment]
Try this (no need to install xact, modify preset, etc)
right click the game in your library chose Properties and put this in Launch options:

WINEDLLOVERRIDES="xaudio2_7=n,b" %command%

**Comment by Anti-Ultimate** [comment]
@FreeLikeGNU doesn't work. Seems like FAudio is moving at a spectacular pace though, so maybe it'll be in Proton in a few days.

**Comment by vkk800** [comment]
This issue has been closed, but I still have the same problem. Is this being worked on?

**Comment by mpaccione** [comment]
Same.

WINEDLLOVERRIDES="xaudio2_7=n,b" %command%

Does not work for me. Is there a special thing I need to install for this to work?

I'm on Ubuntu 18.04.4 LTS

**Comment by samrocketman** [comment]
```
WINEDLLOVERRIDES="xaudio2_7=n,b" %command%
```
works for me

Proton 5 and Ubuntu 18.04.5.  AMD RX5700XT

---

To be clear I used the command on _The Elder Scrolls V: Skyrim Special Edition_ which may be different than the original Skyrim release.  It's Bethesda's "pay for community mods" money grab edition.  The vanilla game still looks great without mods, though.

**Comment by zefkerr** [comment]
> Try this (no need to install xact, modify preset, etc)
> right click the game in your library chose Properties and put this in Launch options:
> 
> WINEDLLOVERRIDES="xaudio2_7=n,b" %command%

Works for me too! Must be by default, dear Proton developers!

**Comment by HasBert** [comment]
>    Try this (no need to install xact, modify preset, etc)
>   right click the game in your library chose Properties and put this in Launch options:
>
>    WINEDLLOVERRIDES="xaudio2_7=n,b" %command%

Still works for me with _Proton Experimantal_ and _Skyrim Special Edition + Anniversary Edition_.
