### ISSUE TITLE
The Elder Scrolls III: Morrowind freezes every five seconds for about two seconds.

### ISSUE THREAD

**Issue by nickgrier07** [ValveSoftware/Proton#2896]
Not sure what the problem is, system specs are: 

OS: Ubuntu 18.04.2 LTS, 64-bit

Memory 3.8 Gb

Processor: Intel core i3-4005U CPU @ 1.70GHz X4

Graphics: Intel Haswell mobile

Gnome: 3.28.2

**Comment by kisak-valve** [comment]
Hello @nickgrier07, we're using one issue report per unofficially supported game title, and it's not clear if you're referring to [The Elder Scrolls III: Morrowind](https://github.com/ValveSoftware/Proton/issues/157) or [The Elder Scrolls IV: Oblivion](https://github.com/ValveSoftware/Proton/issues/718). Please add your experience to the corresponding issue report. Also, adding [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and dropping the generated $HOME/steam-$APPID.log into the comment box of one of those issue reports may have a hint as to what's happening.

**Comment by nickgrier07** [comment]
@kisak-valve that issue report doesn't corrispond to my experance. 

It has nothing to do with the menu, it has to do with the game itself. If you want a catch all for Morrowind issues, then close that one, and make a new one, cause otherwise it's just confusing. 

I'll see what i can do about that log thing.
