### ISSUE TITLE
Allow using local wine over proton on demand

### ISSUE THREAD

**Issue by Kreyren** [ValveSoftware/Proton#2900]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Requesting function which allows running local wine on demand using steam, reasoning beeing for the games which runs on original wine, but has issues on proton.

## Justification [optional] 
End-user always has this option it's just sometime pita to make work + it would probably help with development since it could use steam runtime (which should also be toggle on demand if runtime has issue with said wineapp or if end-user's system is not optimized on binary packages) and report results to proton.

## Risks [optional]
none

## References [optional] 
none

**Comment by kisak-valve** [comment]
Hello @Kreyren, this is a feature request for the Steam client rather than Proton itself, and is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5674. Closing as a duplicate.

**Comment by Kreyren** [comment]
> Hello @Kreyren, this is a feature request for the Steam client rather than Proton itself, and is already being tracked at [ValveSoftware/steam-for-linux#5674](https://github.com/ValveSoftware/steam-for-linux/issues/5674). Closing as a duplicate.

noted, sorry
