### ISSUE TITLE
Nioh crash at random (usually killing an enemy) [485510]

### ISSUE THREAD

**Issue by RorraVox** [ValveSoftware/Proton#2902]
https://www.protondb.com/app/485510
A lot of pepole say same thing, after killing some enemies (non every time the same) the game crash, before that work perfectly exept for video cutscene.

CPU: Intel i7 4770k
GPU: Sapphire AMD Radeon RX 580 8GB Pulse
MOB: Gigabyte Z97X-Gaming GT
RAM: Corsair Vengeance Pro Series 16GB (2 x 8GB) DDR3 DRAM 2400MHz C10 Memory Kit (CMY16GX3M2A2400C10R)

Proton 4.2-9
Linux archlinux 5.2.2-arch1-1-ARCH #1 SMP PREEMPT Sun Jul 21 19:18:34 UTC 2019 x86_64 GNU/Linux

**Comment by kisak-valve** [comment]
Hello @RorraVox, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1287#issuecomment-514194532.
