### ISSUE TITLE
Kingdom Come: Devilerance terrible performance

### ISSUE THREAD

**Issue by carz0** [ValveSoftware/Proton#2904]
# Compatibility Report
- Kingdom Come: Deliverance
- Steam AppID of the game: 379430

## System Information
- GPU: gtx1070
- Driver/LLVM version: up-to-date propietary nvidia prime drivers, zero issues in all other games
- Kernel version: 5.2.2-arch1-1-ARCH
- Proton version: 4.2-9

## I confirm:
- [V] that I haven't found an existing compatibility report for this game.
- [V] that I have checked whether there are updates for my system available.

This game used to work great but now it's nearly unplayable. Less than 50% fps i used to have. Doesn't happen with any other game i have tried. Please check that this is a common issue here:
https://www.protondb.com/app/379430

Glorius eggroll version fixes it, but i believe this should be included in the official proton build
https://github.com/GloriousEggroll/proton-ge-custom/releases

**Comment by spooknik** [comment]
This is not necessarily anything to do with Proton / Wine. 

It's some back-end changes they made in the 1.9 update of the game. Downgrading to 1.8 basically makes things go back to expected performance. 

I've written Warhorse and they said they will fix it in an upcoming patch. 

![image](https://user-images.githubusercontent.com/40317809/61775615-8f0d8280-adf9-11e9-977b-3ed5fdd70d21.png)

**Comment by carz0** [comment]
Thanks so much for taking your time to take a look at it and for your quick reply.
Have a good day!
