### ISSUE TITLE
Wolfenstein: Youngblood

### ISSUE THREAD

**Issue by ImebZ** [ValveSoftware/Proton#2913]
# Compatibility Report

-Name of the game with compatibility issues: Wolfenstein: Youngblood     
-Steam AppID of the game: 1056960

## System Information
- GPU: Nvidia GTX 1080
- Driver/LLVM version: nvidia 430.26
- Kernel version: 5.3.0-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/ImebZ/f2a205ffc1cd84448e9cc14940d523a9/):
- Proton version:4.2-9/3.7-8/3.16-9

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-1056960.zip](https://github.com/ValveSoftware/Proton/files/3437807/steam-1056960.zip)
**_(log is from base steam-runtime install with no extra flags enabled)_**

## Symptoms:
- Game does not launch, title in steam shows running for a few seconds and then stops

## Reproduction:
Open steam, click Wolfenstein: Youngblood, click play. 

## What I have tried:
-Forcing native libraries, using steam runtime and beta runtime 
-Disabling esync, d3d11, and forcing d3d11, along with all applicable combinations of those flags  
-Forcing vulkan(I think) with the +r_renderAPI 1 flag
-Reinstalling proton, steam, and of course the game itself along with the first launch dependencies
-Moving install folder to another drive
-Switching the native manjaro video drivers to the nvidia-430.36 beta drivers and updating vulkan
-Switching video drivers to Manjaro Open-source Linux drivers
-Updating my Asus Prime x570-Pro's bios
-Installing on fresh install of Manjaro 18.1.0rc-5-stable
-Restarting many, many times
 
Almost all of the information I could find on this title referenced the game running flawlessly without any additional configuration. ProtonDB has not refreshed the listing yet, and aside from one other user I have found, my system seems to be the odd one out experiencing issues launching the game.
Most games I own run with steamplay out of the box or with basic troubleshooting, but this one refuses to. My friend was very excited to play the multiplayer, but I just can't get the game to launch :(

**Comment by kisak-valve** [comment]
Hello @ImebZ, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2909#issuecomment-515681003.
