### ISSUE TITLE
A Plague Tale: Innocence (752590) - Controller not working

### ISSUE THREAD

**Issue by Lastique** [ValveSoftware/Proton#2915]
# Compatibility Report
- Name of the game with compatibility issues: A Plague Tale: Innocence
- Steam AppID of the game: 752590

## System Information
- GPU: RTX 2080 Ti
- Driver/LLVM version: Nvidia 430.26
- Kernel version: 5.0.0-21-lowlatency
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Lastique/79ec1b005b1bbe66f8db3b06bbd671a9
- Proton version: 4.2-9
- Gamepad: Dualshock 4, connected via Bluetooth.

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-752590.log](https://github.com/ValveSoftware/Proton/files/3438523/steam-752590.log)

## Symptoms

The game starts but gamepad is not working. Pressing buttons and moving sticks gives no reaction in the game menu.

The gamepad is working in other games, including via Proton.

## Reproduction

Start the game and try interacting with the game menu via a gamepad.

**Comment by kisak-valve** [comment]
Hello @Lastique, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2739#issuecomment-515708985.
