### ISSUE TITLE
Performance regression on The Witcher 3, unstable frame times after 4.11-1

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#2921]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher 3
- Steam AppID of the game: 292030

## System Information
- GPU: Nvidia GTX 970
- Driver/LLVM version: Nvidia 430
- Kernel version: 5.0.0-21
- Link to full system information report as [Gist](https://gist.github.com/): (will update tomorrow, not on my main PC now)
- Proton version: 4.11-1

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Frame times on The Witcher 3 under same GPU driver, same graphical settings and in the same area are unstable in 4.11-1 when they were completely stable and well performing in 4.2-9. I attach a picture of DXVK_HUD showing frame times in both proton version on same location and behavior in the game.
[Link to the image comparing the 2 versions](https://cdn.discordapp.com/attachments/481924470777577502/605913882577469441/unknown.png)
I was not sure whether the issue is Wine, DXVK or Proton related so I made an issue here and hopefully if it's not a proton issue directly, someone can point it to right direction.

## Reproduction
Either open the game under one version or another and compare the performance fps and frame times, stuttering on the latest version is VERY noticable, and isn't related to shader compiling since I've been running around the same location for more than 15 minutes in game.

**Comment by kisak-valve** [comment]
Hello @MaCroX95, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-516649791.
