### ISSUE TITLE
Nier: Automata (524220) crash with Proton 4.11

### ISSUE THREAD

**Issue by yuiiio** [ValveSoftware/Proton#2923]
crash after login menu.
[steam-524220.log](https://github.com/ValveSoftware/Proton/files/3450068/steam-524220.log)
I use dxvk-git but proton 4.11 with stock-dxvk does not works too.
PROTON_NO_FSYNC=1 is not helpful. I use 5.1.15-steamvr-generic.

**Comment by aeikum** [comment]
What operating system are you using? SteamOS?

**Comment by yuiiio** [comment]
linux mint 19.1

**Comment by CSahajdacny** [comment]
> crash after login menu.
> [steam-524220.log](https://github.com/ValveSoftware/Proton/files/3450068/steam-524220.log)
> I use dxvk-git but proton 4.11 with stock-dxvk does not works too.
> PROTON_NO_FSYNC=1 is not helpful. I use 5.1.15-steamvr-generic.

I noted that some games crash when I change the Proton version... And I also noted that deleting the shader cache solve the problem.

**Comment by jeffshee** [comment]
Can reproduce on Fedora 30. Proton 4.11. Always crash after loading the save.
Here is the log file. 
[steam-524220.log](https://github.com/ValveSoftware/Proton/files/3473501/steam-524220.log)

**Comment by yuiiio** [comment]
I have reverts faudio to 19.06 and fix this problem.
bisect ?

**Comment by flibitijibibo** [comment]
I wasn't able to reproduce this with FAudio 19.08 or 19.09. The only changes to the mixer since 19.06 is an increased buffer size for submixes and some error checking for when the audio device fails to open (which would have still crashed but in a different way on 19.06 and older).

The crash log suggests it's a different thread entirely:

```
Unhandled exception: page fault on read access to 0x40000000520 in 64-bit code (0x00000001405c1282).
006f:fixme:dbghelp:elf_search_auxv can't find symbol in module
Register dump:
 rip:00000001405c1282 rsp:000000003985fc30 rbp:000000003985ffd0 eflags:00010206 (  R- --  I   - -P- )
 rax:00000001418f8b50 rbx:0000040000000500 rcx:0000000141106340 rdx:0000000140000000
 rsi:0000000006000958 rdi:0000000000000000  r8:00000001418b6d7c  r9:0000000141911a40 r10:0000000000000000
 r11:0000000000000002 r12:0000000000000000 r13:0000000000000000 r14:0000000000000000 r15:0000000000000000
Stack dump:
0x000000003985fc30:  000000000c8b8dd0 000000003985ffd0
0x000000003985fc40:  0000000006000958 0000000000000000
0x000000003985fc50:  0000000000000000 0000000140519e0b
0x000000003985fc60:  000000000c8b8dd0 0000000006000958
0x000000003985fc70:  000000000c8b8dd0 0000000006000958
0x000000003985fc80:  0000000000000000 000000014051a056
0x000000003985fc90:  0000000006000958 0000000000000000
0x000000003985fca0:  0000000000000000 0000000000000000
0x000000003985fcb0:  000000014092d000 000000014092d01d
0x000000003985fcc0:  0000000006000958 0000000000000000
0x000000003985fcd0:  0000000006000958 000000014092d000
0x000000003985fce0:  0000000004374ac8 000000014092dd8d
Backtrace:
=>0 0x00000001405c1282 in nierautomata (+0x5c1282) (0x000000003985ffd0)
  1 0x0000000140519e0b in nierautomata (+0x519e0a) (0x000000003985ffd0)
  2 0x000000014051a056 in nierautomata (+0x51a055) (0x000000003985ffd0)
  3 0x000000014092d01d in nierautomata (+0x92d01c) (0x000000003985ffd0)
  4 0x000000014092dd8d in nierautomata (+0x92dd8c) (0x000000003985ffd0)
  5 0x000000014092d8bd in nierautomata (+0x92d8bc) (0x000000003985ffd0)
  6 0x00000001409d32a7 in nierautomata (+0x9d32a6) (0x000000003985ffd0)
  7 0x00000001409d344e in nierautomata (+0x9d344d) (0x000000003985ffd0)
  8 0x000000007bcada5d call_thread_func+0xbc() in ntdll (0x000000003985ffd0)
0x00000001405c1282: movl	0x0000000000000020(%rbx),%eax
```

**Comment by yuiiio** [comment]
Sorry... for losing your time
It is not faudio issue.
It seems like same this bug.
https://github.com/ValveSoftware/Proton/issues/2929
