### ISSUE TITLE
Gigantic steam-gameid.log

### ISSUE THREAD

**Issue by IM-OUT-OF-ORDER** [ValveSoftware/Proton#2924]
I was looking through my steam logs and I found one that was rather....odd to say the least. I found one for Marvel's Guardians of the Galaxy: The Telltale Series. When I clicked on it to open it refused to. So I was looking at the properties of it and I realized that it was 51 Gib. I don't know if this is odd enough to pass for a problem on my end or in general. But I thought at the very least I should see if anyone else had a clue to why this would be the case. Thanks in advance for any info.

**Comment by nsivov** [comment]
By default logs are not created. To enable logging you'll need to have user_settings.py configuration file for respective proton version. It's used for everything started with respective proton build. 

Regarding log sizes, it's not unusual, and will depend on how verbose logging is, for how long game was running, and would certainly differ for different games.

**Comment by nsivov** [comment]
You can also enable it per-game, using launch options. See https://github.com/ValveSoftware/Proton#runtime-config-options.

**Comment by IM-OUT-OF-ORDER** [comment]
I've kept the logging to whatever the default is for proton. But I find a log file that is multiple times larger than the actual game to be a little odd. Especially when the biggest I've seen for other ones is less than 500 Mib. 51 Gib is massive compared to the rest that I have seen. But I don't know much about log file sizing, it's just something I've never seen with any of the other log files for proton. So I was curious. Thanks for the reply.
