### ISSUE TITLE
Space Engine on Steam Linux

### ISSUE THREAD

**Issue by Spacesteve451** [ValveSoftware/Proton#2931]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

**Comment by Spacesteve451** [comment]
Hello, I recently switched from Windows to Linux. I have enabled SteamPlay and Proton for all games. I previously bought Space Engine and Space Engine Pro. I also upgraded to Steam beta. I have upgraded linux software. After all of that I am still unable to load Space Engine. The closest i've gotten is a white screen window loading and music but nothing more. Please help me with this issue. I have previously downloaded previous versions of Space Engine and I don't want to miss out on this program. Thank you.The error message i'm getting is as follows: "Error loading texture generator shaders. Press yes to run program with procedural planets disabled. Press no to exit." When I press yes the program loads but only with a blank white screen and I can hear music. Nothing more. When I press no the program closes. Does anyone else have this issue?

**Comment by kisak-valve** [comment]
Hello @Spacesteve451, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2842#issuecomment-520856056.
