### ISSUE TITLE
RollerCoaster Tycoon 3: Platinum! (2700)

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/Proton#2933]
# Compatibility Report
- Name of the game with compatibility issues: RollerCoaster Tycoon 3: Platinum!
- Steam AppID of the game: 2700

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 430.26
- Kernel version: 5.1.20
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Newbie13XD/70c8d82304e9881412591a4d526246f7
- Proton version: 4.11-1

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-2700.log](https://github.com/ValveSoftware/Proton/files/3456456/steam-2700.log)

## Symptoms 
With D9VK enabled, holding shift to elevate buildings while placing them does not work. Works when using WineD3D for DirectX 9, and on Windows (duh). 

While testing this, I also noticed another issue: the intro films that play (more like pictures since Proton lacks WMV support) cannot be skipped when using D9VK, but can with WineD3D. (you should be able to skip them with space)

## Reproduction
1. Start the game with launch options set to `PROTON_USE_D9VK=1`
2. Start a scenario or sandbox
3. Place an object and hold down shift while moving the mouse
4. Notice that it does not work as expected (compare to what it does when using WineD3D)

Note: I'm aware there is an open report for this game, but it seems to be focused on the lack of music, which this is unrelated to.

**Comment by kisak-valve** [comment]
Hello @Newbie13XD, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/208#issuecomment-517263695.
