### ISSUE TITLE
Question: Does PROTON_USE_D9VK works with non Steam games?

### ISSUE THREAD

**Issue by logan001** [ValveSoftware/Proton#2934]
Is it possible to run non steam games with PROTON_USE_D9VK? (DXVK too).
Im trying to run GW2 with the new proton but adding `PROTON_USE_D9VK=1 DXVK_HUD=full %command%`
 to launch option does not work. i have no hud and also fps is lower than lutris version of d9vk.

**Comment by kisak-valve** [comment]
Hello @logan001, unfortunately you've encountered https://github.com/ValveSoftware/steam-for-linux/issues/6046. Closing in favor of the existing issue report.
