### ISSUE TITLE
Dishonoured 2 menu freeze on proton 4.11

### ISSUE THREAD

**Issue by regulator-g** [ValveSoftware/Proton#2936]
## Symptoms 
Using Proton 4.11,
 I launch Dishonoured 2.. It works for about a minute then quicksave/quickload stops working, I press ESC for the menu, it starts bringing up the menu then freezes. I can alt+tab and quit the game.

Additionally in-game when I look around I see shadows that appear then disappear as I move the mouse.

e.g.
https://imgur.com/a/o4FtkPv

No obvious messages in console

-vsync off
-fps_max 60
-triple buffering off

Proton 4.2 does not have these issues

I have renderdoc installed if you need me to try and use that for diagnosis.

# Compatibility Report
- Name of the game with compatibility issues: Dishonoured 2
- Steam AppID of the game: 403640

## System Information
- GPU: RX 570
- Driver/LLVM version:  Mesa 19.2 ACO
- Kernel version: 5.0.0-21
- Proton version: 4.11

**Comment by kisak-valve** [comment]
Hello @regulator-g, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/823#issuecomment-517508977.
