### ISSUE TITLE
World of warships on i3. Cursor bound to very small space in center of screen. Proton 4.11-1

### ISSUE THREAD

**Issue by anonymous133** [ValveSoftware/Proton#2939]
Hi,

After switching workspaces I encountered a bug where the mouse is bound to a very small space in the center of the screen of the game so I can no longer look around properly. As if another window has focus and I can only move my mouse inside that space.

This doesn't happen for me with 4.2-9

**Comment by kisak-valve** [comment]
Hello @anonymous133, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/333#issuecomment-517664685.

**Comment by anonymous133** [comment]
Thank you!!
