### ISSUE TITLE
MGSV (287700) Crashes Immediately After Launch

### ISSUE THREAD

**Issue by lo4952** [ValveSoftware/Proton#2940]
# Compatibility Report
- Name of the game with compatibility issues: Metal Gear Solid V: The Phantom Pain
- Steam AppID of the game: 287700

## System Information
- GPU: GTX 1060 6GB
- Driver/LLVM version: nvidia 430.40
- Kernel version: 5.0.0-23-generic
- Link to full system information report as [Gist](https://gist.github.com/): [Full Info Report](https://gist.github.com/lo4952/4514b453e18ea7a6c65f5051ed721ec0)
- Proton version: 4.11-1

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

<!-
[steam-287700.log](https://github.com/ValveSoftware/Proton/files/3462134/steam-287700.log)
- Please add `PROTON_LOG=1 %command%` to the game's launch options and drag
and drop the generated `$HOME/steam-$APPID.log` into this issue report -->

## Symptoms 
MGSV crashes immediately after launch, logs show the error "wine: Unhandled page fault on read access to 0x000005e7 at address 0x7f4bfc0d45b3 (thread 0056)" on line 645 of steam log.

## Reproduction
Occurs on every launch of MGSV. Have already tried verifying file integrity, using other versions of proton.

**Comment by kisak-valve** [comment]
Hello @lo4952, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/124#issuecomment-517767007.
