### ISSUE TITLE
Batman: Arham Asylum no sound on 4.11-1

### ISSUE THREAD

**Issue by jefferyrlc** [ValveSoftware/Proton#2942]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 35140

## System Information
- GPU:  GTX 960
- Driver/LLVM version:  430.26
- Kernel version:  4.19
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/jefferyrlc/8d5e28d888756608d05168437bb5aac0
- Proton version: 4.11-1

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

[steam-35140.log](https://github.com/ValveSoftware/Proton/files/3462545/steam-35140.log)

## Symptoms 
There is no audio output, audio worked in 4.2 but upon cleaning the pfx and setting the game up to use 4.11-1 there is no audio output

## Reproduction
install the game, winetricks, and protontricks
run protontricks 35140 mdx d3dx9 d3dcompiler_43 win10
change the launch options to
PROTON_USE_D9VK=1 %command%
run the game
have no sound

**Comment by jefferyrlc** [comment]
https://gist.github.com/jefferyrlc/e1cbfe2b4eaca61f6b33363bb63af1f8

**Comment by LeJimster** [comment]
Just tried deleting my working prefix, letting steam create a fresh 4.11-1 prefix and running the same commands..  Everything works fine for me, including sound...

[My system](https://gist.github.com/LeJimster/7751f48f10bf0082158bace47dec7430)

**Comment by aeikum** [comment]
Can you check your volume mixer (e.g. `pavucontrol`) to verify that the game's audio output isn't muted or directed to some other audio device?

**Comment by kisak-valve** [comment]
Hello @jefferyrlc, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/421#issuecomment-520638537.
