### ISSUE TITLE
Command submission failed: VK_ERROR_OUT_OF_DATE_KHR [The Witcher 3]

### ISSUE THREAD

**Issue by abhishek-rawal** [ValveSoftware/Proton#2944]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher 3 : Wild Hunt
- Steam AppID of the game: 292030

## System Information
- GPU: GTX 1050 Ti
- Driver/LLVM version: Nvidia 418.52.18
- Kernel version: 5.2.4
- Link to full system information report : [Gist](https://gist.github.com/0x221E/712a53fab4eb83d63a7c285603816477)
- Proton version: 4.11

## Symptoms 
Game freezes and have to kill it using terminal.

## Logs & Screenshot
[steam-292030.log](https://github.com/ValveSoftware/Proton/files/3463459/steam-292030.log)
![Screenshot from 2019-08-03 11-43-23](https://user-images.githubusercontent.com/10757422/62408667-d1994100-b5e9-11e9-9aad-87402460cb24.png)

**Comment by tannisroot** [comment]
Does that happen on every single launch or only sometimes?

**Comment by ghost** [comment]
~~Affects multiple games https://github.com/ValveSoftware/Proton/issues/2818#issuecomment-516653299~~

Not using DXVK will work around it.

**Comment by doitsujin** [comment]
How **exactly** do you reproduce the hang?

The error message you quoted is normal and nothing to worry about; it's expected to happen when you change resolutions, or in case of Nvidia, even alt+tab out of the game when it is running in fullscreen mode.

Can you test if **disabling** "Allow Flipping" in nvidia-settings fixes the hangs? Does anyone have the hang issue on non-Nvidia systems?

**Comment by abhishek-rawal** [comment]
@tannisroot Actually I am not sure about the pattern. Some times every single load game crashes, while some time it hangs in between.

@doitsujin I am not sure how can i reproduce the hang. I will test several times and will check if i could observe any pattern while crash.
I will perform testing with disabled flipping.

**Comment by abhishek-rawal** [comment]
@doitsujin Tested by disabling flipping. Played around 30-40 minutes, no hang in between. The moment I went back to Novigrad from Skellige, the game crashed. Found below mentioned trace, I am not sure if it is related to crash.

> 35176.705:0027:0049:err:seh:RtlUnwindEx invalid frame 3af10008 (0x3ad12000-0x3af10000)
35176.705:0027:0049:err:seh:call_stack_handlers invalid frame 3af10010 (0x3ad12000-0x3af10000)
35176.705:0027:0049:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.

Full logs : [steam-292030.log](https://github.com/ValveSoftware/Proton/files/3464105/steam-292030.log)

**Comment by doitsujin** [comment]
This particular crash was probably caused by doitsujin/dxvk#1100:
```
err:   DxvkMemoryAllocator: Memory allocation failed
  Size:      4147200
  Alignment: 256
  Mem flags: 0x6
  Mem types: 0x681
```
So, this is unrelated to the hangs you were experiencing (your original log doesn't contain that error).

If disabling flipping is consistently stable, we're most likely triggering a driver bug on Nvidia.

**Comment by abhishek-rawal** [comment]
Tested and played around 10 hours, I can confirm that disabling flipping solves the hang issue.

**Comment by abhishek-rawal** [comment]
Closing the issue.
