### ISSUE TITLE
Heat Signature (268130) Possible regression.

### ISSUE THREAD

**Issue by lucifertdark** [ValveSoftware/Proton#2945]
The game was previously working but since updating to the latest Kernel & drivers the game crashes on hitting the play button.

[steam-268130.log](https://github.com/ValveSoftware/Proton/files/3463529/steam-268130.log)

https://gist.github.com/lucifertdark/584c14275612e8e3c4a8070d428d8a02

Hopefully it's something simple that I can fix.

**Comment by imaami** [comment]
The log says you're using `proton-3.16-9`. Maybe try with the latest release instead?

**Comment by lucifertdark** [comment]
Newest Proton 4.11-1b, same result, wish I knew what to look for in the logs.
[steam-268130.log](https://github.com/ValveSoftware/Proton/files/3464609/steam-268130.log)

**Comment by lucifertdark** [comment]
Something somewhere is seriously broken so I'm doing a full wipe & reinstall of the entire system, the world shall hear from me again.

**Comment by lucifertdark** [comment]
I'm back & everything is working as intended, not sure what broke before so I'm going to leave things alone & see how it goes.

**Comment by ghost** [comment]
Looks like your problem was with libsdl2 but I've got no idea why.

    Unhandled exception: page fault on read access to 0x6977307b in 32-bit code (0xf42d7645)
    ...
    Backtrace:
    =>0 0xf42d7645 in libsdl2-2.0.so.0 (+0x35645) (0x0032f588)

-

    Unhandled exception: page fault on read access to 0x0000011a in 32-bit code (0xf429c645).
    ...
    Backtrace:
    =>0 0xf429c645 SDL_GL_UnloadLibrary+0xbf55() in libsdl2-2.0.so.0 (0x0032f608)

**Comment by lucifertdark** [comment]
I managed to have 3 different versions installed at the same time, don't ask me how cause I haven't a clue, that with the broken drivers made games that should work stop working, I wiped the drive & started again with a fresh install of Ubuntu 18.04, so everything is back to how it should be, I forgot the golden rule, if it ain't broke, don't fix it.

**Comment by ghost** [comment]
Sadly, that means not updating anything either but we can't have everything - security updates are of greater importance than breaking stuff with how things are today.

If it ain't broke, break it for security lol
