### ISSUE TITLE
Cricket 19 (1028630)

### ISSUE THREAD

**Issue by bradgy** [ValveSoftware/Proton#2948]
# Compatibility Report
- Name of the game with compatibility issues: Cricket 19
- Steam AppID of the game: 1028630

## System Information
- GPU: Radeon RX 580 Series 
- Driver/LLVM version: X.Org (POLARIS10, DRM 3.32.0, 5.2.5-arch1-1-ARCH, LLVM 8.0.1)

- Kernel version: 5.2.5-arch1-1-ARCH
- Link to full system information report: [Gist](https://gist.github.com/bradgy/7c59757d9ad7ab3e18e5aedc92ef61a2)
- Proton version: 4.11.1

## I confirm:
- [Yes] that I haven't found an existing compatibility report for this game.
- [Yes] that I have checked whether there are updates for my system available.

[steam-1028630.log](https://github.com/ValveSoftware/Proton/files/3463981/steam-1028630.log)

## Symptoms
Game crashes on start:
Wine C++ Runtime error popup reads:
r
Program:Z
a

## Reproduction
1. Start Steam
2. Launch game
3. See error message
This occurs reliably.

**Comment by Chathula** [comment]
@bradgy, did u find a way to run this on linux?

**Comment by bradgy** [comment]
@Chathula no, but to be honest I didn't try much else in the way of winetricks etc. I had to refund so that I could get my money back before the 2 week/hour window closed.

**Comment by ParitoshBh** [comment]
Tried as well and crashed right away with error message as mentioned under Symptoms. Also, I tried demo version of game. Uninstalled the demo but if there's someone from Valve with possible fixes (wine arguments, etc.), I'll re-download the demo!

**Comment by Chathula** [comment]
@ParitoshBh, if demo is free i would like to try and run it. Can you share me a url.

**Comment by kisak-valve** [comment]
Cricket 19 game DirectX11 issue in Steam Proton

Issue transferred from https://github.com/ValveSoftware/Proton/issues/3605.
@RVV55 posted on 2020-03-06T16:04:27:

# Compatibility Report
- Name of the game with compatibility issues: Hey guys, I was trying to launch a game called Cricket 19 from my Zorin OS (based on Ubuntu 18.04) laptop in steam proton. But, I only got a message stating that:- No compatible graphics device found. Minimum DirectX 11 graphics device is required!. I tried lot of things, but nothing seems to work. Someone Please help me out.
- Steam AppID of the game:  1028630
## System Information
- GPU: AMD Radeon R5 M230, Intel HD Graphics 620 
- Proton version: 5.0.3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.


## Symptoms 
--Hey guys, I was trying to launch a game called Cricket 19 from my Zorin OS (based on Ubuntu 18.04) laptop in steam proton. But, I only got a message stating that:- No compatible graphics device found. Minimum DirectX 11 graphics device is required!. I tried lot of things, but nothing seems to work. Someone Please help me out.
[steam-1028630.log](https://github.com/ValveSoftware/Proton/files/4299191/steam-1028630.log)
[steam-1028630.log](https://github.com/ValveSoftware/Proton/files/4299193/steam-1028630.log)
[steam-1028630.log](https://github.com/ValveSoftware/Proton/files/4299196/steam-1028630.log)
[steam-1028630.log](https://github.com/ValveSoftware/Proton/files/4299202/steam-1028630.log)

**Comment by kisak-valve** [comment]
Hello @RVV55, where ever you found that your system has an `Intel HD Graphics 620`, that is incorrect, your Intel GPU is from the Haswell generation, which has experimental and incomplete Vulkan support.

Setting that aside, Proton uses a subcomponent called DXVK to translate DirectX 11 to Vulkan. Your R5 M230 is a Southern Island (SI) generation video card and your system uses the `radeon` kernel module by default with it. The `radeon` kernel module does not support Vulkan. Please give https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games a read.

Separately, it may be worthwhile to check if you have both the `mesa-vulkan-drivers` and `mesa-vulkan-drivers:i386` packages installed with something like `apt policy mesa-vulkan-drivers mesa-vulkan-drivers:i386` and install them if they are not installed.

That may help some other games start working, but unfortunately, you'll most likely most likely hit the C++ error previously mentioned in this compatibility report.

**Comment by RVV55** [comment]
> Hello @RVV55, where ever you found that your system has an `Intel HD Graphics 620`, that is incorrect, your Intel GPU is from the Haswell generation, which has experimental and incomplete Vulkan support.
> 
> Setting that aside, Proton uses a subcomponent called DXVK to translate DirectX 11 to Vulkan. Your R5 M230 is a Southern Island (SI) generation video card and your system uses the `radeon` kernel module by default with it. The `radeon` kernel module does not support Vulkan. Please give https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games a read.
> 
> Separately, it may be worthwhile to check if you have both the `mesa-vulkan-drivers` and `mesa-vulkan-drivers:i386` packages installed with something like `apt policy mesa-vulkan-drivers mesa-vulkan-drivers:i386` and install them if they are not installed.
> 
> That may help some other games start working, but unfortunately, you'll most likely most likely hit the C++ error previously mentioned in this compatibility report.

I have already installed the mesa drivers you have told. Why I am writing about this issue is that the game is launching in Lutris without the DirectX11 issues, but I am getting dxvk memory issues there, so the game crashes after some time.

**Comment by RVV55** [comment]
I am getting the version info when I run vulkaninfo command. I am a complete newbie in Linux, I have only started to use it from the past few weeks.

**Comment by bukyapavankumar** [comment]
Does it run on opengl

**Comment by srikargottipati** [comment]
I can confirm the same issue on PopOS running the nvidia 440.82 driver on a 2080 with Steam. 

It errors out withe the message 'No compatible graphics device found. Minimum DirectX 11 graphics device is required!'. I'm willing to provide any additional logs or info to any developer or others willing to look into the issue. Thanks

**Comment by aki237** [comment]
I did try running it under virtual desktop. Starts up. But hung at black screen. No more "No compatible graphics device found". I'll try digging up more logs when I get time.

**Comment by aelango97** [comment]
Doesn't work with Steam's bundled proton. Tried with [GE's proton 5.9-GE-3-ST](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.9-GE-3-ST). Works flawlessly. Breaks when exiting. Which seems to occur due to some resolution changes.

**Comment by aki237** [comment]
Doesn't work with Steam's bundled proton. Tried with [GE's proton 5.9-GE-3-ST](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.9-GE-3-ST). Works flawlessly. Breaks when exiting. Which seems to occur due to some resolution changes.

EDIT: Added GE link

**Comment by bukyapavankumar** [comment]
> Doesn't work with Steam's bundled proton. Tried with GE's proton 5.9-GE-3-ST. Works flawlessly. Breaks when exiting. Which seems to occur due to some resolution changes.

Can you link me to custom proton link

**Comment by aki237** [comment]
Also seems like a media foundation issue. Might work with steam's proton with `<Workaround removed by moderator>` tooo. Didn't try.

**Comment by kisak-valve** [comment]
Hello @aki237, that workaround is legally problematic and has been removed.

**Comment by bukyapavankumar** [comment]
Do u face any other issues or it works out ofthe box with proton-ge @aki237

**Comment by aki237** [comment]
Oops. Sorry @kisak-valve 

@bukyapavankumar : yeah it does. Haven't tested mp though.

**Comment by bukyapavankumar** [comment]
@aki237  can you test multiplayer.its much needed these days

**Comment by aki237** [comment]
I would if I could.

**Comment by aki237** [comment]
@bradgy Seems like this is working fine with the latest proton. Can we close this issue?

**Comment by bradgy** [comment]
Sounds good @aki237 , I don't own it anymore so I'll trust you to make the Whitelist Request ;)

**Comment by sandesh266** [comment]
i getting blank screen when i open cricket19 on solus 4.2 also i have used the latest proton ge and the 5.9 ge.please help me\
