### ISSUE TITLE
SteamVR games with Index Controller support stutter at consistent intervals

### ISSUE THREAD

**Issue by TamsenSpelchak** [ValveSoftware/Proton#2949]
# Compatibility Report
- Name of the game with compatibility issues: multiple
    - Hotdogs, Horseshoes, and Hand Grenades
    - Superhot VR
    - Many other VR games that support the new Index Controllers, with the notable exception of Pavlov
- Steam AppID of the game: multiple
    - 450540
    - 617830
    - etc

## System Information
- GPU: nVidia GeForce GTX 1070
- Driver/LLVM version:  nVidia 418.52.18
- Kernel version: 5.2.5-arch1-1-fsync
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/tizzir/4b8c9846bab16ca8570f0e0a3216e766
- Proton version: 4.11-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
As soon as a VR controller is connected while the SteamVR application is running on Proton, the application suffers from significant frame drops on a consistent interval. If the application is started without any controllers connected, the stuttering does not occur.
Stutter pattern looks like this:

![image](https://user-images.githubusercontent.com/22967446/62415655-da424500-b5f2-11e9-8e47-d9f68fad6e79.png)

## Reproduction
1. Start affected application without any controllers connected
2. Look at the SteamVR frame timing graph, notice no significant frame drop
3. Turn on a SteamVR controller (HTC Vive wand and Valve Index controller has been confirmed to be affected)
4. Note the pattern of frame drops in the frame timing graph

[steam-450540.log](https://github.com/ValveSoftware/Proton/files/3464185/steam-450540.log)

**Comment by Zamundaaa** [comment]
This seems to be finally fixed with SteamVR 1.7.2 :smile:
Tested it in Blade & Sorcery as well as Arizona Sunshine.

**Comment by TamsenSpelchak** [comment]
I can confirm that SteamVR 1.7.3 does not exhibit this issue! Thanks devs, we appreciate the hard work!
