### ISSUE TITLE
Symlink Temp to actual /tmp

### ISSUE THREAD

**Issue by vanyasem** [ValveSoftware/Proton#295]
It would be great if Proton would symlink `pfx/drive_c/users/steamuser/Temp/` in wineprefixes to actual `/tmp`. This works well with regular wine, I don't see why wouldn't it be integrated into Proton.

**Comment by aeikum** [comment]
Why is this useful?

**Comment by vanyasem** [comment]
Temp gets cleared on system reboots. Also there might be a performance benefit because of tmpfs

**Comment by aeikum** [comment]
I worry that Unix /tmp has different semantics from Windows Temp directories. I don't think we want that kind of hack in Proton.

**Comment by kisak-valve** [comment]
Hello @vanyasem, you may have better luck making this request at wine's upstream bug tracker.

**Comment by vanyasem** [comment]
Maybe consider keeping the issue open for some time? It could be an opt-in feature in the future.
