### ISSUE TITLE
Rebalance votings and ask for used settings

### ISSUE THREAD

**Issue by ShalokShalom** [ValveSoftware/Proton#2961]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

It seems to me, that certain games like [this](https://www.protondb.com/app/235600) suffer from bad reviews, simply because an easy setting is not used. 

The ironic thing there is, that the very description of the game actually shows that, since many people showcasing how to do it. 

Now, my proposal is that we collect the particular information about how to start a game and ask in the very process of rating a game if that one method is used. 

Otherwise, we have perfectly running games rated at bronze forever. 

Also consider rebalancing these particular games manually, with explanation why in a blog post or so.

**Comment by dlove67** [comment]
ProtonDB is not Valve operated or owned. You'd do better talking to the maintainers of it, maybe on discord (there's a link on the protondb.com page)
