### ISSUE TITLE
Hitman 2: PS4 controller doesn't work with Proton 4.11

### ISSUE THREAD

**Issue by skeevy420** [ValveSoftware/Proton#2963]
# Compatibility Report
- Hitman 2
- 863550

## System Information
- GPU: MSI RX 580 4GB Armor 
- Driver/LLVM version: Mesa 19.1.99 (mesa-aco)/LLVM 9
- Kernel version: 5.2.4 to 5.2.6; 4.19.61, 4.19.62; 5.2.5 & .6 are fsync enabled.
- [My system information report](https://gist.github.com/skeevy420/acff5c64e2c314612bd2b2162e57c02c)
- Proton version: 4.11

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

# Including the log from 4.11 where it doesn't work and the log from 4.2 where it does work.
4.11 -- [steam-863550-4.11.log](https://github.com/ValveSoftware/Proton/files/3478816/steam-863550-4.11.log)

4.2   -- [steam-863550-4.2.log](https://github.com/ValveSoftware/Proton/files/3478817/steam-863550-4.2.log)

## Symptoms
PS4 controller doesn't work with Hitman 2.  Wireless or wired makes no difference and both have the same results.

## Reproduction
Turn on a PS4 controller and try to play the game.  Controller doesn't work.  Controller settings in menu are inaccessible.  Revert to Proton 4.2 and it works perfectly.

Enabling PS4 controller configuration in Steam's controller settings leaves the PS4 controller in desktop mode when in-game.  Allows accessing controller settings in-game but nothing there is helpful to this issue.  Enabling that option in Steam was not necessary for 4.2 nor is it necessary for other games I've played with Proton 4.11.

## Additional Notes
Have tried:
Mesa 19.1.3 stable with llvm 8
mesa-git & mesa-aco both with llvm 9 & llvm 10
five different kernel versions; two with fsync (listed above)
Proton builds with different patches from Tk-Glitch
unplugging my keyboard since I saw that in another controller issue
using xinput with Proton 4.11

All have the same results.

I also deleted compatdata/863550 when changing Proton versions and when trying different things to try to figure this out.

**Comment by TacoDeBoss** [comment]
I can replicate with my Xbox One S pad - simply go to any game's Properties and enable Steam Input Per Game Setting to "Forced On" and watch as your controller completely ceases to work.

**Comment by skeevy420** [comment]
Just tested with Proton 4.11-2 and it has the same results.

**Comment by kisak-valve** [comment]
Hello @skeevy420, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2121#issuecomment-520531017.
