### ISSUE TITLE
Tropico 6 (492720) crashes when creating new save game in Proton 4.11

### ISSUE THREAD

**Issue by Shished** [ValveSoftware/Proton#2969]
# Compatibility Report
- Name of the game with compatibility issues:
Tropico 6, appid 492720

## System Information
- GPU: GTX 1060
- Driver/LLVM version: nvidia 430.40
- Kernel version: 5.2.5
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Shished/3e7b6b351b6c40c6427ebc9387d28b14
- Proton version: 4.11, 4.11-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

# Proton log (archived)
[steam-492720.zip](https://github.com/ValveSoftware/Proton/files/3488681/steam-492720.zip)

## Symptoms 
When Proton 4.11 is used, game crashes after pressing "New Save Game" button. Existing savestates can be overwritten without problems.
This problem does not appears in older Proton versions.

## Reproduction
1. Start a game from Steam
2. Start a new game or Continue existing game.
3. after game loaded, press ESC and press Save Game button
4. Press New Save Game button.
5. ?????????????????
6. Crash to desktop.

**Comment by ghost** [comment]
Hello @Shished,

can you try to start the game with the following startparameter? 

`unset LC_ALL && %command%`

**Comment by Shished** [comment]
No change, game still crashes.

**Comment by Shished** [comment]
Just to clarify, game crashes right after pressing the "New Save Game" button.

Also, this problem does not appears when "Proton-i 4.13-3" is used.

**Comment by ghost** [comment]
Doesnt the game have an native port?

**Comment by Shished** [comment]
Native version performs worse than windows version in Proton. Also it has edge scrolling bug which was not fixed since the release day.

**Comment by Shished** [comment]
This bug is fixed in Proton 4.11-3. Game no longer crashes.
Here is relevant line from the changelog:

> Fix new crashes related to text input, especially in Unreal Engine 4 games including Mordhau and Deep Rock Galactic.

Tropico 6 is an Unreal Engine game and that save menu contains text input field.

**Comment by ghost** [comment]
nice! have fun :)
