### ISSUE TITLE
DOOM 2016 crashes system if vulkan is enabled and steam overlay

### ISSUE THREAD

**Issue by blastermaster77** [ValveSoftware/Proton#2974]
#### Your system information
 CPU Vendor:  AuthenticAMD
 CPU Brand:  AMD FX-8370 Eight-Core Processor          
Operating System Version:
   
    Kernel Name:  Linux
    Kernel Version:  5.0.0-23-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12004000
    X Window Manager:  GNOME Shell
  Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1060 6GB/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 430.40
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz

* Steam client version (build number or date): Steam Runtime Version:  steam-runtime_0.20190711.3
* Distribution (e.g. Ubuntu):  Ubuntu 19.04 (64 bit)
* Opted into Steam client beta?:YES
* Have you checked for system updates?: YES

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Start Doom 2016 with Vulkan and steam overlay enabled

If its running vulkan and and you activate the overlay or recive a messege from the overlay it locks up the system and only the music is active. The Problem does not occur with OpenGL 4.5 it works with overlay enable.

I disable the steam overlay the game works but can not use the game pad or steam controller.

**Comment by Plagman** [comment]
Can you post your detailed system specs if this reproduces for you?

**Comment by blastermaster77** [comment]
well sorry cant give my system specs my pc died on me. when i get the
replacement parts will test again sorry

**Comment by omicron-b** [comment]
I tested this and my system did not crush, but DOOM was unresponsive and had to be killed, after loading main menu to 99% it turned to black screen, although main menu music played fine.

## System Information
- GPU: GTX 1060
- Driver/LLVM version: nvidia 430.40
- Kernel version: 5.2.8-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/m-svo/3c2fea70f0575f498e278c4e1934c361)
- Proton version: 4.11-2

[steam-379720.zip](https://github.com/ValveSoftware/Proton/files/3504329/steam-379720.zip)

Edit: can confirm this also happens with Proton 3.16-9 with overlay enabled, and game works fine with overlay disabled with either Proton version.

**Comment by jsecchiero** [comment]
With AMD gpu don't crash but blink continuously

spec:
GPU: RX 580
Driver/LLVM version: 19.1.2-0dpadoka0
Kernel version: Linux master 5.0.0-21-generic #22-Ubuntu SMP
Proton version: 4.11-2

**Comment by AlexP11223** [comment]
The same issue, tried Proton 3.16 and 4.11

``` 
Processor Information: 
    CPU Brand:  Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
   
Operating System Version:
    Pop!_OS 19.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.0.0-27-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12004000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20190711.3

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1080/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 435.21
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 143 Hz
    VendorID:  0x10de
    DeviceID:  0x1b80
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 5120 x 1440
    Primary Display Size: 23.54" x 13.23" (26.97" diag)
                                            59.8cm x 33.6cm (68.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 8192 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC1220

Memory:
    RAM:  64342 Mb
```

**Comment by Leopard1907** [comment]
Still broken. Proton 4.11, Nvidia 435 driver.

**Comment by Leopard1907** [comment]
https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1591383946838639778

Fixed at new Steam client beta. I tested it and it worked for me.

-Linux:

    Fix GPU crashes and overlay corruption with games that use Vulkan async compute, such as DOOM 2016.

**Comment by blastermaster77** [comment]
yes! thanks will test now! 😙😀

**Comment by Sporif** [comment]
The new beta fixed it for me too.

**Comment by Leopard1907** [comment]
@blastermaster77

So did it work for you also?

**Comment by jsecchiero** [comment]
confirm that is fixed with the latest client with AMD gpu

**Comment by MasterCATZ** [comment]
Thanks seems to be working I get a small crash every few missions 

Finally I can play this game on Ubuntu , Open GL was under 6 FPS getting 60+ FPS with Vulkan :P

when existing game steam crashes how ever , disabling overlay this time and seeing what happens 

 still random crash 


[aio_stdout.txt](https://github.com/ValveSoftware/Proton/files/3777357/aio_stdout.txt)


[assert_20191028141154_1.dmp.txt](https://github.com/ValveSoftware/Proton/files/3777359/assert_20191028141154_1.dmp.txt)

[crashes.zip](https://github.com/ValveSoftware/Proton/files/3777837/crashes.zip)
[terminal.txt](https://github.com/ValveSoftware/Proton/files/3777852/terminal.txt)

**Comment by Leopard1907** [comment]
I think this issue can be closed. Multiple people had positive reports and that is even rolled out to stable client.

https://store.steampowered.com/news/55600/

**Comment by kisak-valve** [comment]
Thanks for retesting. Closing as fixed.
