### ISSUE TITLE
Earth Defense Force 5 (1007040) - Crash on Game Launch

### ISSUE THREAD

**Issue by jameswinegar** [ValveSoftware/Proton#2977]
# Compatibility Report
- Name of the game with compatibility issues: Earth Defense Force 5
- Steam AppID of the game: 1007040

## System Information
- GPU:   GTX 1060
- Driver/LLVM version:  430.34  
- Kernel version:  5.0.0
- Link to full system information report as [Gist](https://gist.github.com/jameswinegar/42a35836fd6abddd8df65e1fb26e28d5): 
- Proton version: 4.11-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1007040.log](https://github.com/ValveSoftware/Proton/files/3499515/steam-1007040.log)

## Symptoms 

1. Game starts but won't load any graphics, fails with an error 
err:   DXGI: EnterFullscreenMode: Cannot query containing output

## Reproduction

1. Start game
2. Black Screen appears and then crashes.

## Additional Details

```
jameswine@pop-os:~$ nvidia-smi
Tue Aug 13 21:03:37 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.34       Driver Version: 430.34       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   62C    P0    30W /  N/A |   1451MiB /  6069MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

```
jameswine@pop-os:~$ uname -a
Linux pop-os 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kisak-valve** [comment]
Hello @jameswinegar, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2874#issuecomment-521228135.
