### ISSUE TITLE
Galactic Civilizations III Stardock window does not draw (update)

### ISSUE THREAD

**Issue by jbwyatt4** [ValveSoftware/Proton#2985]
# Compatibility Report
- Name of the game with compatibility issues: Galactic Civilizations III
- Steam AppID of the game: 226860

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 4.30.40
- Kernel version: 4.15.0-51-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/jbwyatt4/b187724fb43265b490bedc54803b16c6
- Proton version: 4.11-2 (also tested with 4.2-9)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game. (I have Sep 2018, but they did not have this problem. https://github.com/ValveSoftware/Proton/issues/1508 )
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
The Stardock window provides news and a button to play the game when you launch the game on Steam. You need to click a button to close the window and run the game.
The dock after the second launch refuses to paint itself on the GUI. Whatever was on the screen before the window was launch stays there despite that you click random parts and you may trigger a button.
Of note: If you were to switch to another virtual desktop this section of the screen would still refuse to update even if the dock was not on that virtual desktop. That section of the XWindows screen is grabbed by Proton and refuses to repaint.

## Reproduction

You can reproduce this by starting the dock, running the game, exiting, then relaunching the game from the steam client.
The dock should now refuse to paint.

This is reproducible even if you switch distros. Initially encountered on Manjaro Cinnamon, reproduced on Ubuntu 18.04.

**Comment by kisak-valve** [comment]
Hello @jbwyatt4, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1508#issuecomment-522208589.
