### ISSUE TITLE
Move mouse to second monitor

### ISSUE THREAD

**Issue by PierfrancescoArdino** [ValveSoftware/Proton#2988]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

I do not know if it is already an open issue for this problem (I do not think so) or if it is actually a problem of Proton, but when I play a game in a dual monitor setup (using a laptop + external monitor connected via HDMI with the game rendering on the external monitor) I can not move the mouse in the second display unless alt-tabbing. There is a way to move the mouse in the second monitor and using the applications that are rendered there?

**Comment by kisak-valve** [comment]
Hello @PierfrancescoArdino, this sounds like the expected and proper behavior for fullscreen games.

If the game has a fullscreen windowed or windowed mode, then those modes should let the mouse escape the game when it's appropriate.

**Comment by PierfrancescoArdino** [comment]
Fine. I'll close the issue
