### ISSUE TITLE
Skyrim Mods need to be launched with Skyrims Id

### ISSUE THREAD

**Issue by DadSchoorse** [ValveSoftware/Proton#2993]
# Compatibility Report
- Name of the game with compatibility issues: Enderal: Forgotten Stories, Skyrim Script Extender (SKSE)
- Steam AppID of the game: 933480, 365720

## System Information
- GPU: GTX 1060 6gb
- Driver/LLVM version:  nvidia 430.40
- Kernel version: 
- Link to full system information report as : https://gist.github.com/DadSchoorse/8b1f6792faa5e2e4f2511dbeb813085b
- Proton version: 4.11-2

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

[steam-933480.log](https://github.com/ValveSoftware/Proton/files/3521705/steam-933480.log)

Enderal and SKSE do not launch, but with the SteamGameId and SteamAppId set to 72850 in the run debug script they will work

## Reproduction
Run Normal-> does not start

Start with
PROTON_DUMP_DEBUG_COMMANDS=1  %command%
change the SteamGameId and SteamAppId in the run file to 72850
run the run script
game works

**Comment by kisak-valve** [comment]
Hello @DadSchoorse, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2340#issuecomment-523106092 and added a note at https://github.com/ValveSoftware/Proton/issues/170#issuecomment-523106676 as well.

There's also a general feature request for Steam at https://github.com/ValveSoftware/steam-for-linux/issues/5766.

Closing in favor of the existing issue reports.
