### ISSUE TITLE
[Whitelist] Football, Tactics & Glory (375530)

### ISSUE THREAD

**Issue by GitoMat** [ValveSoftware/Proton#300]
Played for a few hours and it works flawlessly.

Ubuntu 18.04.1
Proton 3.7
Kernel 4.15.0-32-generic
Radeon R9 380

System information: https://gist.github.com/GitoMat/16d14cbe2db371fb245b750d442aea94

**Comment by kisak-valve** [comment]
Found in the 2018-12-11 white list update.
