### ISSUE TITLE
Arma 3 (107410) DX11 Error: E_INVALIDARG

### ISSUE THREAD

**Issue by RookySoap** [ValveSoftware/Proton#3004]
# Compatibility Report
- Name of the game with compatibility issues: Arma 3
- Steam AppID of the game: 107410

## System Information
- GPU: GTX 970
- Driver/LLVM version: NVIDIA 418.56
- Kernel version: 5.0.0-25-Generic
- Link to full system information report as [Gist](https://gist.github.com/RookySoap/a268e63bb193f115c052a9bd0eed7e6e):
- Proton version: 4.2-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-107410.log](https://github.com/ValveSoftware/Proton/files/3535671/steam-107410.log)

## Symptoms 

Hello! I'm running Arma 3 on Ubuntu 19.04 with Proton 4.2-9, and it works fairly well other than crashing every so often with the message 

"DX11 error: CreateTexture failed: E_INVALIDARG"

![Screenshot from 2019-08-22 15-13-21](https://user-images.githubusercontent.com/54451025/63613305-0de70e00-c5a6-11e9-8e8d-8e99a882ed2e.png)

Sometimes it says "CreateBuffer failed" or "CreateTexture2D failed" but it always has the "E_INVALIDARG"

The error often happens when placing things in the editor, but also happens walking around in game when it has to draw new textures. It doesn't seem to be any specific texture that the game doesn't like, it's more random.

The error is not mod-related as the crash happens with or without any mods enabled. Graphics settings do not seem to affect the crash either.

I've tried running with all of the other Proton versions available in the menu (3.7-8, 3.16-9, 4.11-2). They don't seem to affect the error.

There's another (unimportant) issue that might be related. About 1/5 of the time the game is launched, it puts out this loud, continuous beep until the game is closed. Probably not helpful, though.

I've tried reinstalling the game several times, but the issue has persisted over a few weeks. 

Usually, the game last about 10 minutes before crashing, but several times I've left it open for a few hours and it never crashed. I wasn't doing anything different with the game in those cases.

I don't think it's a memory thing, as my RAM doesn't fill up and VRAM hovers around 98%-100% without seeming to trigger a crash.

I looked online for the error message. It seems a few people have gotten the error but only in specific circumstances like streaming video in game and with somebody's mod. If you know any way to fix it, it would be much appreciated. Thank you!

Or maybe my computer is just haunted.

Logs from one crash (Github doesn't support Arma's log files):
https://drive.google.com/open?id=16ZjTpPmJyHwEq-3aLIJeUo-vEOmvvBcE

## Reproduction

Not quite sure - in my case, just running the game and waiting until some texture loads that crashes the game.

**Comment by ryao** [comment]
@RookySoap It would have been better had you filed the issue against 4.11-2.

By the way, does using `PROTON_USE_WINED3D=1 %command%` as your launch options help?

**Comment by kisak-valve** [comment]
Hello @RookySoap, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2364#issuecomment-524435839.
