### ISSUE TITLE
Change Castle Crashers default proton (204360)

### ISSUE THREAD

**Issue by FurtadoPires** [ValveSoftware/Proton#3013]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
I'd like to suggest to change the default proton version used in the already whitelisted Castle Crashers Game
## Justification 
While the default option already works out of the box, I have experienced some issues with audio crackling while playing. This can be fix by change the default proton to a higher version (3.16+) which fix the problem with the audio (due to Faudio improvements I believe). 

While it's not hard to change manually, this might be a problem to users who don't know how to do this to fix it.

## References 
[My machine info](https://gist.github.com/FurtadoPires/331ba48eaf4ef82fff6c15dee2691904)

**Comment by MysticTempest** [comment]
Hi, I just wanted to add my support for this request to update the whitelisted version.


There was a recent update to Castle Crashers - https://steamdb.info/patchnotes/4355158/
And, now the whitelisted version of Proton 3.7-8, is no longer able to start the game.
You receive a popup saying "Steam failed to initialize."
To play you need to override the whitelisted version with Proton 4.11-9(or 4.11-8 a few days ago).


I generated 2 logs, one broken & one working.
**Broken with Whitelisted Proton:** https://gist.github.com/MysticTempest/a756f8b3d0fe9f5471ee65e3bb191a68
**Working with the Override:** https://gist.github.com/MysticTempest/ec6cf843a4e1c3089430cb5f6d11319f

In the broken log, I found this (Line 3514):
```71138.134:0008:0009:err:steamclient:create_win_interface Don't recognize interface name: SteamClient019```

@kisak-valve, I noticed this matches some of your comments with the same issue in another game.
https://github.com/ValveSoftware/Proton/issues/1472#issuecomment-544140403
https://github.com/ValveSoftware/Proton/issues/1472#issuecomment-544140563

And, lines up with the Proton 4.11-9 override fixing this issue with Castle Crashers not starting.
So I agree; updating the whitelisted Proton version would be welcome.

**Comment by x4mers** [comment]
Definitely needs to have white listed proton version changed. I noted the problem in the press release comments for the new version of Castle Crashers (they updated to 64 bit for Mac compliance and I guess updated Windows version at the same time). They responded, puzzled at the fact that they never released a Linux version. :-)

**Comment by kisak-valve** [comment]
Hello, this game has been bumped to Proton 4.11 in the 2020-03-10 whitelist update.
