### ISSUE TITLE
[Question] Running .exe files under Proton

### ISSUE THREAD

**Issue by Frontear** [ValveSoftware/Proton#3017]
I want to run some .exe games that I downloaded off of a different site to play. Obviously, I can just run them under normal wine, however I'd like to do so from the client. However, it does not seem to run if I simply add the .exe as a non-steam game to my library. What am I supposed to do?

**Comment by kisak-valve** [comment]
Hello @Frontear, in Steam, you should be able to enable Proton by right clicking on the non-steam game -> Properties and check the `Force the use of a specific Steam Play compatibility tool` option to use Proton in this case.

Closing as this is a question about the Steam client and not Proton itself.

**Comment by Frontear** [comment]
I appreciate this answer, however I've tried this, and the application itself will still not launch through steam.

For future reference, where should I go to ask such questions?

**Comment by kisak-valve** [comment]
This question is about the Steam client's integration of Proton, so the [steam-for-linux](https://github.com/ValveSoftware/steam-for-linux) issue tracker is where it makes sense to discuss this.

It was previously discussed at https://github.com/ValveSoftware/steam-for-linux/issues/5677 and you may have encountered https://github.com/ValveSoftware/steam-for-linux/issues/5220.
