### ISSUE TITLE
Snapcraft package

### ISSUE THREAD

**Issue by joeky888** [ValveSoftware/Proton#3018]
Distributed via snap package https://snapcraft.io

It would be great if we can simply install it via command `sudo snap install proton` on most Linux distros.

**Comment by kisak-valve** [comment]
Hello @joeky888, snap packages are meant to be self-contained and Proton is expected to directly interact with the host system's Steam install, which makes this request awkward to do sanely.

It would make more sense to package another flavor of wine with some of the extras found with Proton than to make a snap package of Proton itself, or for the entire Steam client to be in the environment, which is outside the scope of this issue tracker.

**Comment by joeky888** [comment]
Update: use flatpak instead.

Proton is on [flathub](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton), for anyone interested you can install it via flatpak:

```fish
flatpak install flathub com.valvesoftware.Steam.CompatibilityTool.Proton
```

Or [this](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE) command if you prefer the [GE distribution](https://github.com/GloriousEggroll/proton-ge-custom):

```fish
flatpak install flathub com.valvesoftware.Steam.CompatibilityTool.Proton-GE
```
