### ISSUE TITLE
Mouse View Stuck Between Angles

### ISSUE THREAD

**Issue by Kiltenth** [ValveSoftware/Proton#3020]
Hello everyone. So, I'm using Ubuntu 18.04 LTS and I'm having this strange problem with games where when I alt-tab and back to the game, I can't look around beyond an angle.

Feels like when I alt-tab and back to the game, mouse cursor can't stay locked in the middle of the screen. So (in the background I guess) mouse cursor hits screen borders and that prevents me from looking around in game after certain angles.

I'm not sure if there are any other ways to trigger this problem but currently alt-tabbing triggers it most of the time, which renders the game unplayable. Simply not alt-tabbing is not a good solution since sometimes I just spend hours while alt-tabbing here and there to chill and maybe add few more lines to my codes in 5-10 minutes, and then get back to the game.

Switching screen resolution or changing between window modes don't fix the problem. Any solution? Thanks in advance.

**Comment by kisak-valve** [comment]
Hello @Kiltenth, this issue is already being tracked at #579. Closing as a duplicate.
