### ISSUE TITLE
Iratus: Lord of the Dead (807120)

### ISSUE THREAD

**Issue by larkaa** [ValveSoftware/Proton#3021]
# Compatibility Report
- Name of the game with compatibility issues: Iratus: Lord of the Dead
- Steam AppID of the game: 807120

## System Information
- GPU: GeForce GTX 1060 6GB
- Driver/LLVM version: nvidia 430.40
- Kernel version: 4.15.0-58-generic
- Link to full system information report as [Gist](https://gist.github.com/larkaa/b3a530d7e9c66740f5fe32c012d44f57):
- Proton version: 4.11-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game opens to a black screen with no sound. No introduction, no music, just a simple black screen with a rendered cursor.

## Reproduction
Open Iratus.

**Comment by kisak-valve** [comment]
Hello @larkaa, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2941#issuecomment-526569933.
