### ISSUE TITLE
Elite Dangerous doesn't load: "Add value to collection of type System.Windows.Controls.UIElementCollection’ threw an exception"

### ISSUE THREAD

**Issue by kingo55** [ValveSoftware/Proton#3027]
# Compatibility Report
- Name of the game with compatibility issues: Elite Dangerous
- Steam AppID: 359320

## System Information
- GPU: NVIDIA GeForce GTX 970
- Driver/LLVM version: nvidia 435.21
- Kernel version: 5.2.11
- Link to full system information report: https://gist.github.com/kingo55/750b0151c1f46d0bfa3785c9ab239371
- Proton version: 4.11-3

## I confirm:
- [ y ] that I haven't found an existing compatibility report for this game.
- [ y ] that I have checked whether there are updates for my system available.

Proton logs: https://gist.github.com/kingo55/8f5048c79a05dca708f1ece063074593

## Symptoms 

When I start the game, it fails with the following message:

![Screenshot_20190831_131717](https://user-images.githubusercontent.com/2361388/64059937-0c05f600-cc09-11e9-83b3-67a7a17e5c0e.png)

```
Internal error creating window: 

Add value to collection of type ‘System.Windows.Controls.UIElementCollection’ threw an exception.
```

And there are lines from the log which look suspicious:

```
11309.473:0037:0038:fixme:dbghelp:elf_search_auxv can't find symbol in module
11309.474:0030:0031:trace:seh:NtRaiseException code=80000003 flags=0 addr=0x7bcab604 ip=7bcab605 tid=0031
```

Proton logs: https://gist.github.com/kingo55/8f5048c79a05dca708f1ece063074593

## Reproduction

I installed ED via Steam and originally the game would not start or show any messages.

Scouring the internet, I found I could use Winetricks to install certain dependencies: https://github.com/redmcg/wine/wiki

E.g. like: 

```
STEAMAPPS=~/.steam/steam/steamapps
export WINEPREFIX=$STEAMAPPS/compatdata/359320/pfx
rm -rf $WINEPREFIX
winetricks -q dotnet40 vcrun2015 win7
```

After this, ED stays active for longer but it now shows the prompt with the `System.Windows.Controls.UIElementCollection` message.

**Comment by kisak-valve** [comment]
Hello @kingo55, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/150#issuecomment-526824631.
