### ISSUE TITLE
Proton library seem to break my native games update

### ISSUE THREAD

**Issue by Patrick-Edouard** [ValveSoftware/Proton#303]
Hello and thanks for all your work on this new feature.

Unfortunately it seem installing a game with Proton broke my (native) dota2 updating.

I'm running Fedora 28, OS and main steam library (where my dota2 is installed) are installed on a SSD. I have a secondary steam library on a mounted hard disk and made a new library on the same disk for Proton games (can't use the same as native games?).
Now there is a Dota2 update, and when it finishes I get an error message (https://imgur.com/PgB9Gdj) mentionning dota2 and my Proton library (where dota is NOT installed).

By launching steam from a terminal I can see the following trace:

> GameAction [AppID 570, ActionID 1] : LaunchApp failed with AppError_31 with "/mnt/1A10781E1077FF57/Jeux/SteamLibraryProton/steamapps/downloading/570/game/bin/built_from_cl.txt"
> GameAction [AppID 570, ActionID 1] : LaunchApp changed task to Failed with ""

Thanks;

**Comment by kisak-valve** [comment]
Hello @Patrick-Edouard, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/4800. Closing as a duplicate.

**Comment by Patrick-Edouard** [comment]
Thanks for the update.

Seems to be related indeed though Dota is installed on my SSD which is a EXT4. Don't know why it tries to update it on the proton library.
