### ISSUE TITLE
Switch to GCC 9.2.0 compiler

### ISSUE THREAD

**Issue by ryao** [ValveSoftware/Proton#3032]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
@tk-glitch and I found that switching to the GCC 9.2.0 compiler causes a slight reduction in runtime overhead. My own tests show that the per frame direct3d 11 performance in the 3DMark API Overhead test increases by 4% to 10% in comparison to the upstream DXVK binary (which is built the same way as the Proton binaries).

The current Proton 4.11-3 release was built with a mix of GCC 9.1.0 and GCC 8.3.0 (likely the mingw runtime). Switching to GCC 9.2.0 for Proton 4.11-4 would increase performance in CPU limited situations.

**Comment by aeikum** [comment]
Update. Everything that is cross-compiled is built with gcc 9.2. Things that are built natively may still be built with gcc 5.4 or gcc 8.3, but I'm not sure if those components have any performance impact. @ryao Should we close this bug?
