### ISSUE TITLE
Crazy Taxi: some Objects invisible / Game crashes when using Proton 4.11-3

### ISSUE THREAD

**Issue by Hanouta** [ValveSoftware/Proton#3036]
# Compatibility Report
- Name of the game with compatibility issues: Crazy Taxi
- Steam AppID of the game: 71230

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 19.1.5 / LLVM 8.0.1
- Kernel version: 5.2.11
- Link to full system information report as [Gist](https://gist.github.com/): [https://gist.github.com/Brn9hrd7/cd0fdc87bd1fe0ceede3cad2b40ab033](https://gist.github.com/Brn9hrd7/cd0fdc87bd1fe0ceede3cad2b40ab033)
- Proton version: 4.11-3

## I confirm:

- [x] that I haven't found an existing compatibility report for this game.

- [x] that I have checked whether there are updates for my system available.

[steam-71230_invisible.log](https://github.com/ValveSoftware/Proton/files/3571691/steam-71230_invisible.log)
[steam-71230_crash.log](https://github.com/ValveSoftware/Proton/files/3571692/steam-71230_crash.log)

## Symptoms 
Depending on which driver and map you pick, there are either some Vehicles like Taxis and Trams invisible, or the game just crashes.
- When choosing the "Original" map at the menu, the game just freezes
- When choosing the "Arcade" map, it depends on which driver you pick
   - Axel: Taxi completely invisible(except Shadows), Tram invisible
   - B.D. Joe: Screen turns green and game crashes
   - Gena: Taxi visible, Tram invisible
   - Gus: Taxi visible while driving, but when the camera changes(at the start of the game, when picking someone up, while jumping, etc.) most of the Taxi is invisible, Tram invisible

This issue seems to occur only on some resolutions, I have this issue when running the game at 1080p, it doesn't occur when running at 720p. I don't have this problem when using Proton 4.2-9.

## Reproduction
Click on "Configure Crazy Taxi" in the popup, set the resolution to 1080p and launch the game

**Comment by kisak-valve** [comment]
Hello @Brn9hrd7, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1794#issuecomment-527658668.
