### ISSUE TITLE
Tell users to install 430 series Nvidia driver

### ISSUE THREAD

**Issue by ryao** [ValveSoftware/Proton#3037]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
The documentation recommends that users install the 418 series:

https://github.com/ValveSoftware/Proton/wiki/Requirements

While that is fine for a minimum requirement, the latest long lived branch is the 430 series:

https://www.nvidia.com/en-us/drivers/unix/

There is even a 435 series short lived branch. Users should be told to install one of them.

**Comment by kisak-valve** [comment]
Hello @ryao, this is a repeat of https://github.com/ValveSoftware/Proton/issues/1856#issuecomment-434439928 and I don't see a reason to change my stance on incremental updates.

**Comment by ryao** [comment]
@kisak-valve Would it help if someone from Nvidia were the one who asked? @ahuillet should be happy to confirm that users should be installing the 430 series or newer.

**Comment by ahuillet** [comment]
I believe in general our guidance would be to install the most recent available driver. Stability concerns may justify sticking to long lived branches.
Not upgrading drivers is rarely the right thing to do, especially with features that are under active development.

**Comment by kisak-valve** [comment]
Of course the latest and greatest driver from the vendor tends to give the best results, and "Linux users with NVIDIA graphics cards should install the latest NVIDIA proprietary drivers" is the first line of that section. That doesn't change the intent of the **Requirements** page is to convey what is needed for support and there will always be a newer driver series than what is needed.

**Comment by ryao** [comment]
@kisak-valve It is fine to tell users what the minimum required version is, but saying that the latest is the best and then giving them instructions that explicitly ignores the latest is contradictory.
