### ISSUE TITLE
Mega Man X Legacy Collection 1/2: Some titles dont start

### ISSUE THREAD

**Issue by ichirou2910** [ValveSoftware/Proton#3039]
# Compatibility Report
- Name of the game with compatibility issues: Mega Man X Legacy Collection 1/2
- Steam AppID of the game: 743890 / 743900

## System Information
- GPU:  GTX 960M
- Driver/LLVM version:  nvidia-driver-435
- Kernel version:  5.0.0-27-generic (buildd@lgw01-amd64-031) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1))
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ichirou2910/3077254bb2b23d0e35f883f8bcdf4e0a
- Proton version: 4.11-3

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
X1-3 work fine
X4-8 didnt start, stuck in black screen (though there was "loading data" message in x8 when start)
X Challenges 1-2 work fine

## Reproduction
Open the game and select any of the titles
P/s: I did set the launch option to PROTO_LOG=1 %command% but cannot find the log file

![image](https://user-images.githubusercontent.com/51302893/64359255-2ccbb280-d032-11e9-9638-ce454b8eab58.png)

**Comment by kisak-valve** [comment]
Hello @ichirou2910, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1556#issuecomment-528449604.
