### ISSUE TITLE
Slap City - Native GC Issue

### ISSUE THREAD

**Issue by Settyness** [ValveSoftware/Proton#3043]
Slap City - AppID 725480

This game had worked nearly flawlessly with just `-force-d3d9` defined under "Set launch options..." however, roughly six months ago, the game refused to launch under any circumstances and ProtonDB has been plagued  by "Borked" reports ever since.

This was right around the time of [this](https://steamcommunity.com/games/725480/announcements/detail/1754619776318997947) update. In a nutshell, I've found that Slap City's native GameCube controller support has somehow completely broken Proton compatibility. Running the game with `-disable-native-gc` makes the game playable once more.

**Comment by kisak-valve** [comment]
Hello @Settyness, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/23#issuecomment-528866039.
