### ISSUE TITLE
Shadow of the Tomb Raider works fine

### ISSUE THREAD

**Issue by darkfinedelight** [ValveSoftware/Proton#3045]
# Whitelist Request
- Name of the game to be whitelisted: Shadow of the Tomb Raider
- Steam AppID of the game: 750920 

## System Information
- GPU: GTX1050Ti
- Driver/LLVM version: 4.6.0 NVIDIA 435.21
- Distro version: Kubuntu 18.04
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/darkfinedelight/b86fbfa688d4853bd210e83f73c43e7f
- Proton version: 4.11-3

## I confirm:
- [ ##] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [ ##] I haven't experienced any issues.
- [ ##] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @darkfinedelight, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1417#issuecomment-529198722.
