### ISSUE TITLE
Beat Saber log file gets filled with NullReferenceException (620980)

### ISSUE THREAD

**Issue by Corben78** [ValveSoftware/Proton#3046]
Since Proton 3.16-9 the log file under `SteamLibrary/steamapps/compatdata/620980/pfx/drive_c/users/steamuser/AppData/LocalLow/Hyperbolic Magnetism/Beat Saber/output_log.txt` gets filled with these exceptions:
```
NullReferenceException: Object reference not set to an instance of an object
  at (wrapper managed-to-native) System.Object.wrapper_native_0000000006D003C0(Valve.VR.VREvent_t&,uint)
  at Valve.VR.CVRSystem.PollNextEvent (Valve.VR.VREvent_t& pEvent, System.UInt32 uncbVREvent) [0x00061] in <e214f8ec5d4d45eeb4a35631e2607e94>:0 
  at OpenVRHelper.Update () [0x0002b] in <26ec787945bf43e5aae4af5dd3394845>:0 
  at VRPlatformHelper.Update () [0x00008] in <26ec787945bf43e5aae4af5dd3394845>:0 
 
(Filename: <e214f8ec5d4d45eeb4a35631e2607e94> Line: 0)
```
Here the log files for Proton 4.11-3 and 3.16.9:
[output_log-4.11-3.txt](https://github.com/ValveSoftware/Proton/files/3587602/output_log-4.11-3.txt)
[output_log-3.16-9.txt](https://github.com/ValveSoftware/Proton/files/3587603/output_log-3.16-9.txt)
This seems not to happen with 3.7-8: 
[output_log-3.7-8.txt](https://github.com/ValveSoftware/Proton/files/3587604/output_log-3.7-8.txt)

Here are the corresponding proton log files, with `PROTON_LOG=1 %command%`:
[steam-620980-3.7-8.log](https://github.com/ValveSoftware/Proton/files/3587606/steam-620980-3.7-8.log)
[steam-620980-3.16-9.log](https://github.com/ValveSoftware/Proton/files/3587607/steam-620980-3.16-9.log)
[steam-620980_4.11-3.log](https://github.com/ValveSoftware/Proton/files/3587608/steam-620980_4.11-3.log)

When using mods with Beat Saber, these error messages are duplicated into the log files of the mods as well, letting them grow quickly into hundreds of megabytes, which might cause side effects, especially with performance.

My steam system information:
[system_information.txt](https://github.com/ValveSoftware/Proton/files/3587613/system_information.txt)

Steam VR system report:
[SteamVR-2019-09-08-PM_02_24_18.txt](https://github.com/ValveSoftware/Proton/files/3587614/SteamVR-2019-09-08-PM_02_24_18.txt)

**Comment by aeikum** [comment]
Thanks for the very nice bug report. I see the problem and will have a fix for it soon.

**Comment by aeikum** [comment]
The problem turned out to be more complicated than I thought. Didn't manage to get it done in time for 4.11-4, hopefully next release.

**Comment by Corben78** [comment]
Was just about to check out 4.11-4, no worries and thank you for keeping us posted!

**Comment by aeikum** [comment]
Still not in 4.11-5, but I'm working on it :)

**Comment by Corben78** [comment]
I guess the release window for 4.11-6 was also too short, wasn't it?

**Comment by aeikum** [comment]
Yeah, not yet, sorry. I have it completed, but we haven't had time to do a QA pass on it yet. If you're curious, I pushed the branch over here https://github.com/aeikum/Proton/tree/proton_4.11-vrclient

**Comment by aeikum** [comment]
Hooray, this should be fixed in 4.11-7. Thanks for your patience. Please retest (you may need to restart the Steam client for it to update).

**Comment by Corben78** [comment]
Played yesterday 2h of Beat Saber on stream and no signs of the NullReferenceException in the log files anymore. I also have the impression it has helped with most of my frame drops. Thank you very much!

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as fixed.
