### ISSUE TITLE
Metro 2033: Lighting issue, very dark

### ISSUE THREAD

**Issue by RafaelLinux** [ValveSoftware/Proton#3052]
# Compatibility Report
- Metro 2033 
- AppID: 43110

## System Information
- GPU:  NVidia GP107 [GeForce GTX 1050 Ti]
- Driver/LLVM version: OpenGL 4.6.0 NVIDIA 418.87.00
- System info: https://gist.github.com/RafaelLinux/9b634a295e84571e69e9c2db464e3939
- Kernel version: 4.12.14
- Proton version:  4.11.3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

https://fromsmash.com/3aZdKKAGCe-c0

## Symptoms 
Using Proton > 4.2.9,  some scenes illumination disappear, making the game so dark that's unplayable. Moreover (independently of Proton version)  each time I launch "Metro 2033", it fails to start and I must launch Metro again for a second time. Then a window asking to launch in "safe mode" and I need to configure again video option to HD. 

## Reproduction
Here two screenshot with Proton 4.2.9 and Proton > 4.2.9
https://fromsmash.com/Th2yk8Ou3i-c0

**Comment by kisak-valve** [comment]
Hello @RafaelLinux, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1660#issuecomment-531431929.

**Comment by RafaelLinux** [comment]
Thank you kisak. In fact, there are two distinct issues in my post. On is
Proton related and the other seems not related to Proton itself, but I
don't know what's the problems. I'll follow that thread.
