### ISSUE TITLE
Beat Saber (620980) fails to start from steam UI

### ISSUE THREAD

**Issue by yesmar12** [ValveSoftware/Proton#3054]
# Compatibility Report
- Name of the game with compatibility issues: Beat Saber
- Steam AppID of the game:620980

## System Information
- GPU: GTX 1080
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/yesmar12/d1376a699cf08a7f6a2c33f8ce7fd279):
- Proton version: 3.7-8, 4.11-3

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
Similar [issue](https://github.com/ValveSoftware/Proton/issues/1731#issuecomment-531226197)
- [ x ] that I have checked whether there are updates for my system available.

## Symptoms 
[Starting from steam UI: steam-620980.txt](https://github.com/ValveSoftware/Proton/files/3612356/steam-620980.txt) <-- This fails
[Starting from VR home: steam-620980.log](https://github.com/ValveSoftware/Proton/files/3612359/steam-620980.log)<-- This works

When I open up beatsaber on the desktop it crashes. But if I open it from the headset it works fine.

Also it seems that steam is unable to tell that beatsaber crashed, cause I am still listed as playing beatsaber and have the option to exit. Trying to exit the game through the steam ui, is ineffective and fails quietly. If I kill the process called steam child monitor ( or something like that) I can then start the game from the headset.

## Reproduction
Open the game through the steam desktop UI.

**Comment by aeikum** [comment]
There is a known issue in the Steam for Linux client where VR titles will fail to start if Steam VR is not already running. Does starting Steam VR before launching the game in the Steam client help?

**Comment by yesmar12** [comment]
Yes this seems like an effective work around. If there is already an issue for this, then I guess this can be closed. Where is that issue being tracked, a couple quick searches have not found it.
