### ISSUE TITLE
Launchers with transparency now have a blank window with a WM Bar and don't show launcher.

### ISSUE THREAD

**Issue by RonnieTiger** [ValveSoftware/Proton#3062]
# Compatibility Report
- Name of the game with compatibility issues: Elder Scrolls Online
- Steam AppID of the game: 306130

## System Information
- GPU: nVidia GTX 1070
- Driver/LLVM version: 435.21
- Kernel version: 5.0.0-27
- Link to full system information report as [Gist](https://gist.github.com/ronlaws86/a845a559894131b1077b6c004fa89f62):
- Proton version: 4.11-4

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.

- [*] that I have checked whether there are updates for my system available.

[steam-306130.log](https://github.com/ValveSoftware/Proton/files/3614126/steam-306130.log)

## Symptoms 
Since latest update that pushed out for Proton, launchers (Possibly ones that use transparency) fail to set the window size correctly and have now gained a window title bar where they previously did not exhibit this behaviour.

![Screenshot from 2019-09-15 19-21-48](https://user-images.githubusercontent.com/11991709/64925982-ffc88e00-d7ef-11e9-9603-5e15b4e8d20d.png)
![Screenshot from 2019-09-15 19-22-08](https://user-images.githubusercontent.com/11991709/64925983-00f9bb00-d7f0-11e9-8051-1cf16715be40.png)

## Reproduction
Ensure latest proton is in use
Click launch.
Minimise launcher then bring back to focus.

**Comment by kisak-valve** [comment]
Hello @ronlaws86, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/556#issuecomment-531589730.
