### ISSUE TITLE
Cube World (1128000)

### ISSUE THREAD

**Issue by ShadowMen** [ValveSoftware/Proton#3066]
# Compatibility Report
- Name of the game with compatibility issues: Cube World
- Steam AppID of the game: 1128000

## System Information
- GPU: RX 5700 XT 
- Driver/LLVM version: Mesa 19.3/10.0.0  
- Kernel version: 5.3 
- Link to full system information report as [Gist](https://gist.github.com/ShadowMen/2bae22eae6099ab12fe1667aa7d5c78c)
- Proton version: 4.11-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1128000.log](https://gist.github.com/ShadowMen/e7325c1fe7c3ae0b2d4fde8c50a5207e)
## Symptoms 
Window frame is rendered and then the game exits.

## Reproduction
1. Download the game
2. Start the game
3. Window frame will appear and disappear
4. Game exits

**Comment by kisak-valve** [comment]
Hello @ShadowMen,
```
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
INFO: OpenAudioDevice failed: ALSA: Couldn't open audio device: Datei oder Verzeichnis nicht gefunden
INFO: Assertion failed: 0 && "Failed to open audio device!"
```
These look like lines of interest in your log and might hint that there's an alsa config issue with your system.

**Comment by ShadowMen** [comment]
@kisak-valve 
Good catch! I installed the `pulseaudio-alsa` package which provides the configuration. Now its starting :smiley: 
Thank you
