### ISSUE TITLE
GTA5 wont start anymore since 2 days "unable to find rockstar games launcher"

### ISSUE THREAD

**Issue by guustflater** [ValveSoftware/Proton#3067]
# Compatibility Report
- Name of the game with compatibility issues: GTA5
- Steam AppID of the game: 271590

## System Information
Ubuntu 19.04 
- GPU: RX 580
- CPU: AMD Ryzen 5 1600 Six-Core 
- Driver/LLVM version: OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.3.0-devel
- Kernel version: 5.0.0-27-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/guustflater/066e3f2e19ed03836f5940e482833d83
- Proton version: 4.11.-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
GTA5 doesn't start anymore since today. It's only preparing first time setup and gives an error "unable to find rockstar games launcher". Only thing I noticed steam started downloading some shaders for GTA5 during startup.

**Comment by kisak-valve** [comment]
Hello @guustflater, we're using one issue report per unofficially supported game title, and this launcher issue is already being discussed on #37 starting at https://github.com/ValveSoftware/Proton/issues/37#issuecomment-532310257. Closing in favor of the existing compatibility report.
