### ISSUE TITLE
Squad (sudden fps drops)

### ISSUE THREAD

**Issue by aly199** [ValveSoftware/Proton#3071]
Latest Proton (4.11-5) has Squad dropping fps, from 60-90fps, down to 15fps. It happens sort of every 20-30s, drops for about 5-10s, then gets back to normal, cycling like this through the entire game.
Reverting back to Proton 4.2-9, the issue disappears.

Proton 4.11-5
Linux Mint 19.1 (Tessa)
NVIDIA Driver 430.4
Kernel 4.15.0-55-generic

**Comment by kisak-valve** [comment]
Hello @aly199, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/938#issuecomment-533346690.
