### ISSUE TITLE
Cube World (112800) wont launch

### ISSUE THREAD

**Issue by GrimIcarus** [ValveSoftware/Proton#3072]
# Compatibility Report
- Name of the game with compatibility issues: Cube World
- Steam AppID of the game: 1128000

## System Information
- GPU:GTX 950m/ intel 530
- Driver/LLVM version: nouveau/ i915
- Kernel version: 5.1.21-1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 4.11-5

## I confirm:
- [y] that I haven't found an existing compatibility report for this game.
- [y] that I have checked whether there are updates for my system available.

[steam-1128000.log](https://github.com/ValveSoftware/Proton/files/3633548/steam-1128000.log)
## Symptoms
launch game, nothing happens

**Comment by kisak-valve** [comment]
Hello @GrimIcarus, what filesystem is the Steam library the game is installed on?

**Comment by GrimIcarus** [comment]
@kisak-valve according to my fstab it's ntfs-3g

**Comment by kisak-valve** [comment]
Thanks, Proton is known to have finicky issues with NTFS. There's some notes at https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows and you can [search the issue tracker](https://github.com/ValveSoftware/Proton/search?q=ntfs&type=Issues) for NTFS to find some hints.

Off the top of my head, the partition needs to be mounted with the regular user as the owner and without the `windows_names` mount option.
