### ISSUE TITLE
FYI Some 4.11-5 binaries are being detected by a few AVs

### ISSUE THREAD

**Issue by duderand** [ValveSoftware/Proton#3077]
Some AVs are being triggered with proton exe's. This is not that uncommon but I would like to inform the proton team.

After a user reported the issue on Steam community 
https://steamcommunity.com/app/221410/discussions/0/1627412171715145835/

I checked and with proton 4.11-5 build 32bit clock.exe is being detect by some AVs.

https://www.virustotal.com/gui/file/da7cc7448241103e7866e7f5570e9d709534b9527ab82a7e87af8875ceea0f2c/detection

64bits version shows no detection https://www.virustotal.com/gui/file/b80ca46544d2a3425e454edbbe9b89d8d0eec50f75dd9d1699733143c60c0675/details

**Comment by aeikum** [comment]
I think you'll want to work with the AV vendors to fix the false positive.
