### ISSUE TITLE
Hitman 2 stopped working after update

### ISSUE THREAD

**Issue by b3nis** [ValveSoftware/Proton#3083]
# Compatibility Report
- Name of the game with compatibility issues: Hitman 2
- Steam AppID of the game: 863550

## System Information
- GPU: GTS 1650
- Driver/LLVM version: 435.21
- Kernel version: 5.0.0-25-generic
- Link to full system information report as https://gist.github.com/b3nis/e10344386544506f9c0d0f9ad04ab502
- Proton version: 4.11

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

##Proton log
https://gist.github.com/b3nis/0cc4e722324e5013f287a6be22b26896

## Symptoms 
Getting this error (printscreen) when trying to start the game. I have played it for 25 hours and haven't changed anything (drivers, etc). The only new thing is that Hitman 2 got a new DLC.

![Screenshot from 2019-09-24 17-58-39](https://user-images.githubusercontent.com/54119148/65541124-013f3800-df0d-11e9-8ca9-3604f1ff242f.png)

## Reproduction
1. Install Hitman 2
2. Try and run the game

**Comment by kisak-valve** [comment]
Hello @b3nis, we're using one issue report per unofficially supported game title, and this issue is already being discussed on #2121 starting at https://github.com/ValveSoftware/Proton/issues/2121#issuecomment-534677264. Closing in favor of the existing compatibilty report.
