### ISSUE TITLE
Batman Arkham City borked with 4.11-6 (worked with 4.11-5)

### ISSUE THREAD

**Issue by is-gray-wolf** [ValveSoftware/Proton#3084]
# Compatibility Report
- Name of the game with compatibility issues: Batman Arkham City 
- Steam AppID of the game: 200260

## System Information
- GPU: Nvidia RTX2080
- Driver/LLVM version: nvidia 418.56
- Kernel version: 5.0
- Link to full system information report as [Gist]:https://gist.github.com/the-black-wolf/9161867478638fd3016e742a12f67867
- Proton version: 4.11-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-200260.log](https://github.com/ValveSoftware/Proton/files/3649294/steam-200260.log)

## Symptoms 
It errors out before entering the main menu, as pictured below. It worked properly with 4.11-5, something in v6 broke it. 

## Reproduction
Just start and wait till the splash videos end. 

![image](https://user-images.githubusercontent.com/15175507/65546986-d6f37780-df18-11e9-98be-4f1b1db6f65a.png)

**Comment by is-gray-wolf** [comment]
Just switched Steam proton to 4.2-9 and it works. Definitely something to do with 4.11-6

**Comment by kisak-valve** [comment]
Hello @the-black-wolf, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/309#issuecomment-534741580.
