### ISSUE TITLE
Onirism (1057640)

### ISSUE THREAD

**Issue by ryliejamesthomas** [ValveSoftware/Proton#3087]
# Compatibility Report
- Name of the game with compatibility issues: _Oniriam_
- Steam AppID of the game: 1057640

## System Information
- GPU: AMD Radeon Vega 8 (integrated)
- Driver/LLVM version: Mesa 19.1.6/8.0.1
- Kernel version: 5.2.14-arch2-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ryliejamesthomas/1a7effe0e6ca92218e29e719a6b3f204
- Proton version: 4.2-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1057640.log](https://github.com/ValveSoftware/Proton/files/3651418/steam-1057640.log)

## Symptoms 
Game hangs when loading. Most often after selecting langauge but before the title screen. A few times I've made it to the title, but it will hang when entering the options or trying to start playing.

I've tried multiple versions of Proton.

**Comment by kisak-valve** [comment]
Possible lines of interest from the log:
```
amdgpu: Not enough memory for command submission.
vk: error: failed to submit CS 0
```

**Comment by ryliejamesthomas** [comment]
Thanks kisak. I increased the RAM I allocate to the APU and that seems to have fixed it (or a Proton update).
