### ISSUE TITLE
Astroneer : Freezing on splash screen.  OS remains running

### ISSUE THREAD

**Issue by z5d69** [ValveSoftware/Proton#3091]
# Compatibility Report
- Name of the game with compatibility issues: Astroneer
- Steam AppID of the game: 361420

## System Information
- GPU: NVIDIA GTX 1060 6 GB
- Driver/LLVM version: 430.40-17
- Kernel version: 4.4.180-102
[steam-361420.log](https://github.com/ValveSoftware/Proton/files/3663463/steam-361420.log)

- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:4.11-6
Gist: https://gist.github.com/z5d69/72d7278bdbcf9ee8459298b0cb221c4b
## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
When I try to run Astroneer through Steam Play, it freezes.  Wine is running, Astroneer is still running, but the splash screen remains on the screen.  I don't see any errors in the log indicating that anything has failed.  

![image](https://user-images.githubusercontent.com/44180425/65782333-0cfc4b80-e113-11e9-98f6-9c98cbaaf150.png)

## Reproduction

Please see above.

**Comment by kisak-valve** [comment]
Hello @z5d69, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/243#issuecomment-536007622.
