### ISSUE TITLE
Dead by Daylight, Linux User, DX11 Feature 11.0 Error Message

### ISSUE THREAD

**Issue by acornleaf** [ValveSoftware/Proton#3095]
# Compatibility Report
- Name of the game with compatibility issues: Dead by Daylight
- Steam AppID of the game: 381210

## System Information
- GPU: 
- Driver/LLVM version: bcmwl-kernel-source - distro non-free
- Kernel version: 4.15.0-20-generic
- Proton version: 4.11-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms  
I have posted this on the PC Bugs section of the Dead by Daylight's forums and no response from the community.
I got a response from Steam Support to submit a ticket here, I hope I'm in the right place. I've tried to fix this but am still dealing with the pop up that said DX11 feature level 11.0 is required to run the engine. I have tried many fixes, details below.
Fixes I've tried:

- Updating Steam Play to Proton 4.11-6
- Changing the game's launch settings to d3dll_UE4Features
- [ In Terminal ]
- sudo apt-get install mesa-vulkan-drivers mesa-vulkan-drivers:i386
- sudo apt install nvidia-drivers

I'm using Linux Mint 19.1 Tessa, devices and drivers below:
== /sys/devices/pci0000:00/0000:00:1c.0/0000:02:00.0 ==
modalias : pci:v000014E4d00004727sv00001028sd00000010bc02sc80i00
vendor : Broadcom Limited
model : BCM4313 802.11bgn Wireless Network Adapter (Inspiron M5010 / XPS 8300)
driver : bcmwl-kernel-source - distro non-free

**Comment by kisak-valve** [comment]
Hello @acornleaf, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/519#issuecomment-536139942.
