### ISSUE TITLE
Deus Ex Mankind Divided - Windows build not Native (337000)

### ISSUE THREAD

**Issue by fls2018** [ValveSoftware/Proton#3096]
# Compatibility Report
- Name of the game with compatibility issues: Deus Ex Mankind Divided
- Steam AppID of the game: 337000

## System Information
- GPU: GTX 1070
- Driver/LLVM version: 435.21
- Kernel version: 5.3.1
- Proton version: 4.11-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton log: 

[steam-337000.log](https://github.com/ValveSoftware/Proton/files/3665049/steam-337000.log)

## Symptoms

The game does have a native Linux build but I tested to see if the Windows build was working in Proton. Unfortunately for me it appears to crash at launch, and I've seen conflicting reports online of some saying this game working with wine while others say it doesn't work due to Denuvo.

I would like somebody to confirm which is the case.

## Reproduction

Force Steam Compatibility Tool for the game and launch.

**Comment by John-Gee** [comment]
As others said, the game does not start with Proton, no matter the version, but it starts fine with wine-staging, at least 4.16 in my tests, and from what others said also 4.5 and 4.15.

Non-staging wine 4.16 seems to do better than Proton as the process does not die, but apart from using a lot of CPU not much is happening which forces me to kill it.

With staging, the launcher shows with and without DXVK, so that one doesn't matter.

**Comment by fls2018** [comment]
> As others said, the game does not start with Proton, no matter the version, but it starts fine with wine-staging, at least 4.16 in my tests, and from what others said also 4.5 and 4.15.
> 
> Non-staging wine 4.16 seems to do better than Proton as the process does not die, but apart from using a lot of CPU not much is happening which forces me to kill it.
> 
> With staging, the launcher shows with and without DXVK, so that one doesn't matter.

I've tried custom tkg/GE proton builds and it doesn't appear to work, then just now I tried Lutris wine-steam and it appears to work (glitchy graphics but that's something for dxvk).

Maybe a communication problem between the Linux version of Steam and the Windows launcher?

**Comment by John-Gee** [comment]
To see if that was the case, I've tried using Steam's Proton 4.11 instead of my distribution's Wine to start Windows' Steam.exe, but I am unable to do so, it complains about not being able to access the network so no idea.

If someone knows how to do that, it could be a good test to verify your hypothesis.

**Comment by Guy1524** [comment]
@John-Gee Proton implements steam APIs globally, and I suspect that it will intercept communication intended for windows steam.

**Comment by John-Gee** [comment]
@Guy1524  Oh that's interesting, yet a bit annoying in this case.
Do you have any idea of something else to try?

Thank you!

**Comment by John-Gee** [comment]
The game now works with Proton 5.0, the issue can be closed.

**Comment by soredake** [comment]
@kisak-valve 
Game is stuck with infinite loading when ESYNC/FSYNC is enabled.

[steam-337000.log](https://github.com/ValveSoftware/Proton/files/4221605/steam-337000.log)

**Comment by soredake** [comment]
@kisak-valve can you reopen this?

**Comment by kisak-valve** [comment]
Hello @soredake, the reporting user has chosen to close this issue report, search for the appid and open a new compatibility report if there isn't an open one already.

**Comment by kopr12** [comment]
This was working fine 2 days ago, in the meantime there was mesa update that I remember and I'm not sure but I think Proton as well, anyway it doesn't launch anymore, it crashes and exits after several seconds.

Proton 5.0-4
Mesa  20.0.1

**Comment by fls2018** [comment]
Yes can confirm Proton 5.0.4 has broke this, unofficial GE 5.1 Proton (maybe later versions although haven't tested yet) still works.

**Comment by kopr12** [comment]
Indeed it runs with GE 5.2
Thanks for the information!

**Comment by kisak-valve** [comment]
Hello @fls2018, you previously chose to close this issue report, #3589 was opened in the mean time to track this game, and we're using one issue report per unofficially supported game title.

Feel free to comment on the active compatibility report. Closing.
