### ISSUE TITLE
Support for legacy Nvidia GPUs

### ISSUE THREAD

**Issue by smurfhunter** [ValveSoftware/Proton#31]
The requirement of Nvidia 396.51 means that many GPUs will never function with this software. This should really be changed to at least work with the legacy 390xx drivers.

**Comment by jbalme** [comment]
I don't believe 396.51 is a hard requirement for DirectX 9 games, only DX12 games and DX11 games via DXVK.

Nevertheless, if you want to see continued support for GPUs which NVidia is dropping support for, you should support the Nouveau project.

**Comment by smurfhunter** [comment]
Do the Nouveau drivers work with this?

**Comment by NoXPhasma** [comment]
The need for 396.51 will probably be because of DXVK, which needs that driver due to driver bugs.

**Comment by jbalme** [comment]
Nouveau doesn't yet have functional Vulkan support, but it's your best hope of seeing it on legacy cards.

Also, I tested SteamPlay on 390xx, works fine on DDLC, so can confirm 396xx is not a hard requirement.

**Comment by mirh** [comment]
DDLC is a direct3d 9 game, so there's no surprise in that. 

Dxvk [doesn't seem to be interested](https://github.com/doitsujin/dxvk/pull/484) to older gpus (but I may be wrong), so either nag nvidia (for as much as they could add new features to their legacy driver), or make this issue about having graceful fallbacks to opengl.

**Comment by smurfhunter** [comment]
Closing this issue because it's an issue with the Nvidia driver that will likely be solved with a future Nouveau/Mesa driver, and not an issue on Valve's front.

**Comment by mirh** [comment]
Friendly reminder mesa is a joke on nvidia cards (or we could say nvidia cards are a joke with it, take your favourite)

**Comment by smurfhunter** [comment]
Yet the Nvidia driver for my card doesn't support this software and is now legacy. Any suggestions?

**Comment by John-Gee** [comment]
Maybe Proton should include the legacy DXVK branch for this, or disable itself in favor of the OGL backend I suppose.

**Comment by mirh** [comment]
No point in sticking with dead forever software. If any a patch should be sent to workaround the missing extension. 

As for switching to OGL, that's an available thing.. I just still couldn't test whether that's automatic though.
