### ISSUE TITLE
games that work for me and notes for other users

### ISSUE THREAD

**Issue by CauchoPato** [ValveSoftware/Proton#310]
manjaro amd hd 6 series

full mojo rampage  (needed to lower graphic settings, or id get to look at character in full blk screen)
simcity 4 deluxe
state of decay
toy soldiers

==games that didnt===
kenshi
quake champion
fallout 3 goty

===notes===
you may have to use htop to kill all processes after starting the game and finding it dont work.
restarting the game or steam will sometimes reinstall the missing packages, it didnt catch the first time..  at least it happened for me.
remember this is a beta

**Comment by kisak-valve** [comment]
Hello @CauchoPato, we won't be keeping general collections of test results open on this issue tracker.
