### ISSUE TITLE
7 Days to Die (251570)

### ISSUE THREAD

**Issue by betam4x** [ValveSoftware/Proton#3102]
NOTE:  7 Days To Die has a Linux port, but it's buggy and doesn't perform well.  In addition, the developer has shown little interest in maintaining it.  Running the game via Proton has always worked fantastic in the past, with frame rates exceeding Windows in many instances.  I don't know if it was a new proton version or my switch from Ubuntu to ArchLinux, but something has caused a few issues:

1) Game freezes on quit and has to be killed.
2) New game can only start on random gen.  The built in map freezes.  I do not have a log for this, but will try and provide one.
3) Quite a few "Object not set to instance of Object" errors (Unity Engine, so .NET framework) that don't happen under Windows.

GPU:  NVIDIA GTX 1080ti
Driver:  435.21
Kernel: 5.3.1
Proton Version:  4.11-6 (I will try other versions later as I have time and update this post, will also try running steam itself under wine and installing it that way.)
System Log:  https://gist.github.com/betam4x/fd0cbe712d51c3fce28b689f748c1e33
Debug Log:  https://gist.github.com/betam4x/b9db1a940c78569a47543ed167a5f724

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.  (There is another issue open for this game for an unrelated bug)
- [ X] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @betam4x, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2845#issuecomment-536237047.
