### ISSUE TITLE
Noita (881100)

### ISSUE THREAD

**Issue by bobpatraque** [ValveSoftware/Proton#3105]
# Compatibility Report
- Game Name : Noita
- Steam AppID of the game : 881100

## System Information
-CPU : Ryzen 5 1600
- GPU: GTX 1080
- Driver/LLVM version: NVIDIA 418.56
- Kernel version: 5.0.0-29-generic
- Proton version: 4.11.6

## Symptoms : 

Game doesn't lanch at all

## Reproduction

1 - Try to launch the game
2 - Wait and see the "running" status for 1 sec
3 - Cry while seeing the steam sync beginning...

<details><summary>Steam Log</summary><p>

```
======================
Proton: 1569267010 proton-4.11-6
SteamGameId: 881100
Command: ['/mnt/0412113612112E64/Games/SteamLibrary/steamapps/common/Noita/noita.exe']
Options: set()
======================
ERROR: ld.so: object '/home/bob/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wine: /mnt/0412113612112E64/Games/SteamLibrary/steamapps/compatdata/881100/pfx is not owned by you
ERROR: ld.so: object '/home/bob/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/bob/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
wine: /mnt/0412113612112E64/Games/SteamLibrary/steamapps/compatdata/881100/pfx is not owned by you
```

</p></details>

**Comment by TwoAbove** [comment]
@bobpatraque This issue arises from the fact that the installation folder is not owned by you. Check to see that it is.

In my case, Noita's game folder was owned by root. chown ing it fixed this crash

**Comment by kisak-valve** [comment]
Hello @bobpatraque, what filesystem is the game installed on? This reads like #35.

When starting games, Steam LD_PRELOADs a 32 bit and 64 bit variant of the Steam overlay. One silently works while the other harmlessly fails, which is unrelated to your issue.

**Comment by bobpatraque** [comment]
You'r rigth @kisak-valve. The issue comes from the filesystem, and not from proton itself. Thank you a lot for your answer.
