### ISSUE TITLE
Black screen in Flat Out 2 in 4k (2990)

### ISSUE THREAD

**Issue by RazrFalcon** [ValveSoftware/Proton#3109]
# Compatibility Report
- Name of the game with compatibility issues: Flat Out 2
- Steam AppID of the game: 2990

## System Information
- GPU: GTX 1070 Ti
- Driver/LLVM version: 435.21
- Kernel version: 5.3.1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/RazrFalcon/18e3bb75b249e8c577f47e9a017a5ca2
- Proton version: 3.16-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2990.zip](https://github.com/ValveSoftware/Proton/files/3671669/steam-2990.zip)

## Symptoms

The game starts with a black screen in 4k, but there is music and menu sound effects in the background. So it's actually started.
1080p works fine. 

## Reproduction

Reproduces every time. Also tested with Proton 4.11-6 - the same results.

**Comment by kisak-valve** [comment]
Hello @RazrFalcon, `err:d3d:wined3d_debug_callback 0x205460: "GL_OUT_OF_MEMORY error generated. Failed to allocate CPU address space mapping for texture (consider building 64-bit app).".` looks like the line of interest in the log.

Does adding `PROTON_FORCE_LARGE_ADDRESS_AWARE=1 %command%` to the game's launch options make a difference?

**Comment by RazrFalcon** [comment]
@kisak-valve Yep, it's works now. Thanks!

**Comment by kisak-valve** [comment]
Hello @RazrFalcon, PROTON_FORCE_LARGE_ADDRESS_AWARE was enabled by default in Proton 5.0.
