### ISSUE TITLE
Tekken 7 (389730) DLCs not detected on Ubuntu.

### ISSUE THREAD

**Issue by Loffah** [ValveSoftware/Proton#3111]
#### Your system information

* Steam client version (build number or date): 0.20190927.0
 
* Distribution (e.g. Ubuntu): Ubuntu 19.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Hello! I own a bunch of DLC character in Tekken 7 and they do not seem to be activated on my Linux distro. They are clearly locked ingame and no DLC section seem to appear in the Tekken 7 section of my steam library. The DLC section do seem to appear for other games like Dota2, Darkest Dungeon and Borderlands 2. 
When i tried to boot Tekken 7 the first time on Ubuntu after previously having a save from Windows 10 i got the ingame message about my game save file being corrupted. So i wiped it and started a fresh one. But i'd assume that this shouldn't affect extra content that is provided by steam from the server side. 

#### Steps for reproducing this issue:
I guess you could try to reproduce the last step if you want to
1. Have a tekken 7 save file on windwos 10
2. Try to boot the same file from Ubuntu with the steam cloud service
3. Agree to wiping your savefile when prompted after launching the game.

**Comment by kisak-valve** [comment]
Hello @Loffah, can you go to Steam -> Settings -> Steam Play and check the `Enable Steam Play for  all other titles` checkbox, then test if that makes the DLC show up?

**Comment by Loffah** [comment]
That seem to have fixed it thanks!

**Comment by aleksvor** [comment]
And why was this issue closed? The bug is still there - despite main Tekken 7 was whitelisted, DLC don't work unless user overrides default Proton configuration, either globally in Steam settings or in the main game's properties.
I guess, the problem is DLC weren't added to whitelist? If yes, shouldn't they be whitelisted too @kisak-valve ?

**Comment by NyaomiDEV** [comment]
Yeah, Valve forgot to whitelist ALL DLCs. Also PLEASE bump Proton's version to some recent one; Tekken will run smoother in 4.x releases compared to 3.x ones.
