### ISSUE TITLE
RAGE 2 - machine lockup / hangs while loading checkpoints.

### ISSUE THREAD

**Issue by rcbrufatto** [ValveSoftware/Proton#3113]
Currently facing an odd behavior within RAGE 2 with Proton 4.11-6.
Game starts and works flawlessly, but usually freezes while loading from last save or checkpoint. The only thing that becomes available is the infamous Alt+SysRq REISUB. 
I have tried a bunch of tweaks as proposed on multiple places also driver updates without luck. Also, I haven't found much relevant information in the logs.

HW info:

```
System:
  Host: xxxxxx Kernel: 5.3.0-13-generic x86_64 bits: 64 
  Desktop: Xfce 4.14.1 Distro: Ubuntu 19.10 (Eoan Ermine) 
Machine:
  Type: Laptop System: Micro-Star product: GS65 Stealth Thin 8RF v: REV:1.0 
  serial: <root required> 
  Mobo: Micro-Star model: MS-16Q2 v: REV:1.0 serial: <root required> 
  UEFI: American Megatrends v: E16Q2IMS.112 date: 05/21/2019 
Battery:
  ID-1: BAT1 charge: 79.8 Wh condition: 83.0/80.3 Wh (103%) 
CPU:
  6-Core: Intel Core i7-8750H type: MT MCP speed: 899 MHz 
  min/max: 800/4100 MHz 
Graphics:
  Device-1: Intel UHD Graphics 630 driver: i915 v: kernel 
  Device-2: NVIDIA GP104M [GeForce GTX 1070 Mobile] driver: nvidia v: 435.21 
  Display: x11 server: X.Org 1.20.5 driver: modesetting,nvidia 
  unloaded: fbdev,nouveau,vesa resolution: 1920x1080~144Hz 
  OpenGL: renderer: GeForce GTX 1070 with Max-Q Design/PCIe/SSE2 
  v: 4.6.0 NVIDIA 435.21 
Network:
  Device-1: Intel Wireless-AC 9560 [Jefferson Peak] driver: iwlwifi 
  Device-2: Qualcomm Atheros Killer E2500 Gigabit Ethernet driver: alx 
Drives:
  Local Storage: total: 931.51 GiB used: 488.34 GiB (52.4%) 
Info:
  Processes: 317 Uptime: 1h 23m Memory: 31.28 GiB used: 2.00 GiB (6.4%) 
  Shell: bash inxi: 3.0.36
```
I am also attaching steamapp logs.

Let me know what other info I can provide. In the meantime, I will keep looking if I can find something more relevant in the logs.

Thanks in advance!

[steam-548570.log](https://github.com/ValveSoftware/Proton/files/3678122/steam-548570.log)

**Comment by kisak-valve** [comment]
Hello @rcbrufatto, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2686#issuecomment-537190169.

**Comment by rcbrufatto** [comment]
Thanks!
