### ISSUE TITLE
Yakuza Kiwami 2 GPU usage

### ISSUE THREAD

**Issue by Alpha-180** [ValveSoftware/Proton#3121]
# Compatibility Report
- Name of the game with compatibility issues: Yakuza Kiwami 2
- Steam AppID of the game: 927380

## System Information
- GPU: GTX 1080
- Driver/LLVM version: Nvidia 435.21
- Kernel version: 5.2.11
- Link to full system information report as [Gist](https://gist.github.com/): [https://gist.github.com/Alpha-180/f5f20b25b88fff71bf31d33a4e7be49c](url)
- Proton version: 4.11-6

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

[steam-927380.log](https://github.com/ValveSoftware/Proton/files/3688096/steam-927380.log)

## Symptoms 
The game has low GPU usage when you are in game however in the menus the GPU usage spikes up normally. To test this I uncapped the frame rate and on both the main menu and when you pause the game the GPU can hit 100% load and is not being limited by the CPU. However once the menus go away and you are just in game GPU load drops dramatically and I have seen as low as 37% usage. Forcing SSAA increases GPU load but does not affect the frame rate at all. For example in one area I could be getting 46 FPS at 56% load, I enable SSAA and load jumps to 87% but the FPS remains the same. 

## Reproduction
Being in game and out of a menu reduces GPU load. 

Below are some screenshots I took to showcase the increase/decrease in GPU load

![menu](https://user-images.githubusercontent.com/56136735/66165060-e69e4a80-e601-11e9-9a9d-9bb2317da34d.png)

![inGame](https://user-images.githubusercontent.com/56136735/66165070-eaca6800-e601-11e9-9303-5c992486c9b2.png)

![paused](https://user-images.githubusercontent.com/56136735/66165076-ed2cc200-e601-11e9-83d5-4ad4dc996fa3.png)

**Comment by kisak-valve** [comment]
Hello @Alpha-180, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2659#issuecomment-538134485.
