### ISSUE TITLE
PLAYNE (865540)

### ISSUE THREAD

**Issue by anonymous133** [ValveSoftware/Proton#3124]
# Compatibility Report
- Name of the game with compatibility issues: PLAYNE
- Steam AppID of the game: 865540

## System Information
- GPU: Vega 64
- Driver/LLVM version: mesa-aco-git 19.3.0_devel.20190927.d0ed7ce952c-4 (Also tested RADV_PERFTEST=llvm %command% same issue)
- Kernel version: 5.3.1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.githubusercontent.com/anonymous133/b059271e406e412f871cf4e9aa9269ce/raw/8119bf92917e9e2cbfb7ba32f4594c19eb58e603/gistfile1.txt
- Proton version: 4.11-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-865540.log](https://github.com/ValveSoftware/Proton/files/3691554/steam-865540.log)

## Symptoms 
When starting the game this error gets displayed: 
DX11 Feature level 10.0 is required to run the engine

## Reproduction
Run the game.

**Comment by kisak-valve** [comment]
Hello @anonymous133, Proton uses DXVK to translate DirectX 10/11 into Vulkan and `err:   DxvkInstance: Failed to create instance` in your log hints that there's an issue with your Vulkan driver stack.

**Comment by anonymous133** [comment]
Hi @kisak-valve 
Thank you. 

I didn't manage to fix the error (I don't know how, I uninstalled mesa-aco-git and just reinstalled it - didn't work).

I got it to run with PROTON_USE_WINED3D11=1 %command%

**Comment by anonymous133** [comment]
@kisak-valve 
Do you think that is a valid fix so that I should close this report?
