### ISSUE TITLE
PLANET ALPHA (485030)

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/Proton#3125]
# Compatibility Report
- Name of the game with compatibility issues: PLANET ALPHA 
- Steam AppID of the game: 485030

## System Information
- GPU: RX VEGA 56
- GPU Driver: 19.1.0+aco+git1569582082-d0ed7ce952c-1bionic1 (Valves PPA)
- Kernel version: 5.3.1-050301-lowlatency
- Distro version: Linux Mint 19.2 Tina (64 bit) (Cinnamon)
- Proton version: 4.11-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Game launches to a black screen, you can hear music playing but nothing happens.

[media_info.txt](https://github.com/ValveSoftware/Proton/files/3691987/media_info.txt)
[steam-485030-proton-4.11-6.log](https://github.com/ValveSoftware/Proton/files/3691977/steam-485030-proton-4.11-6.log)
[steam-485030-proton-4.11-6-d9vk.log](https://github.com/ValveSoftware/Proton/files/3691978/steam-485030-proton-4.11-6-d9vk.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3691979/system_info.txt)

Logs mention mfplat.dll and codecs are: MPEG-4, AVC + AAC

This is another game for issue #1464 , game allegedly works fine if you install Windows Media Foundation (guides can be found just by googling "Planet Alpha Linux DXVK Wine", I have not tested it though myself)

## Reproduction

Just launch the game

**Comment by mozo78** [comment]
The game is running fine. Just read video description:
https://youtu.be/qiEJ75PG8eU

**Comment by NoXPhasma** [comment]
As already hinted, the game needs Media Foundation. Installing it with `<Link removed by moderator>` the game will start and works fine with Proton 4.11-6.

**Comment by kisak-valve** [comment]
Hello @NoXPhasma, the link you've posted is legally problematic and has been removed.

**Comment by NoXPhasma** [comment]
Didn't know this was a problem, will not post it ever again. Thanks.

**Comment by AwesamLinux** [comment]
Re-tested with Proton 7.0-2 and the videos now work and the game is playable out of the box on AMD CPU's. But the game does still crash on a Intel 10th gen and newer CPU's after a few minutes of gameplay, because this game is affected by the Unreal Engine OpenSSL bug as mentioned in #5830

To play this game on Intel CPU's (tried it myself on i7-12700T) use launch option  "OPENSSL_ia32cap=0x20000000 %command%"

I'm closing this issue as the game crashes on Intel CPU are not Proton exclusive, I have reported this particular problem separately in #5830
