### ISSUE TITLE
Saint Seiya: Soldiers' Soul (348710) some arenas doesn' t work fine

### ISSUE THREAD

**Issue by root2185** [ValveSoftware/Proton#3128]
# Compatibility Report
- Name of the game with compatibility issues: Saint Seiya: Soldiers' Soul
- Steam AppID of the game: 348710 

## System Information
```
inxi -G -S
System:    Host: debian-desktop Kernel: 5.0.0-19.1-liquorix-amd64 x86_64 bits: 64 Desktop: Gnome 3.22.3 
           Distro: Debian GNU/Linux 9 (stretch) 
Graphics:  Device-1: NVIDIA GP106 [GeForce GTX 1060 3GB] driver: nvidia v: 418.74 
           Display: x11 server: X.Org 1.19.2 driver: nvidia unloaded: fbdev,modesetting,nouveau,vesa 
           resolution: 3840x2160~60Hz 
           OpenGL: renderer: GeForce GTX 1060 3GB/PCIe/SSE2 v: 4.6.0 NVIDIA 418.74 
```
- Proton version: 4.2-9 (default of my system it is not set " Force to use a specific Steam Play compatibility tool")

## I confirm:
- That I found a compatibility report here https://github.com/ValveSoftware/Proton/issues/1408
- [X] That I have checked whether there are updates for my system available.

[steam-348710.log](https://github.com/ValveSoftware/Proton/files/3694099/steam-348710.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3694109/system_info.txt)

## Symptoms    
A lot of arenas have some interferences that block my view, sometimes are very big. 
Here you can see the interferences:
![Screenshot from 2019-10-05 21-35-16](https://user-images.githubusercontent.com/32654091/66265972-0c546b00-e81f-11e9-8dc6-86cdb717d17b.png)

Also those arenas works bad there is some heavy lag.
Indeed if you watch the timer it behaves in a very strange way, sometimes it changes of 10+ seconds (in 1 second).

Beside that I can play flawlessly, the arenas without interferences are fine.

Maybe should I try another proton version? Which?

**Comment by kisak-valve** [comment]
Hello @Scorpion2185, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1408#issuecomment-538742807.
