### ISSUE TITLE
Doom (2016) (379720) crashes on Mesa 19.2 and Radeon 380 with Vulkan (worked on Mesa 19.1)

### ISSUE THREAD

**Issue by vrodic** [ValveSoftware/Proton#3129]
# Compatibility Report
Doom (2016)

- Steam AppID of the game: 379720

## System Information
- GPU: Radeon 380
- Driver/LLVM version: Mesa 19.2+
- Kernel version: 5.x
- Link to full system information report as [Gist](https://gist.github.com/vrodic/aa9f631330c4e623955df8aca906572c):
- Proton version: 4.11-6, 3.16-9

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

This is a regression with Mesa 19.2 and vulkan-radeon (radv) code. It used to work with Mesa 19.1

## Symptoms 
Game crashes on startup

## Reproduction

Try launching the game. 

Proton log:
[steam-379720.log](https://github.com/ValveSoftware/Proton/files/3695752/steam-379720.log)
Game crash log:
[doom-2016-mesa-19.2-radeon-vulkan-crash.txt](https://github.com/ValveSoftware/Proton/files/3695741/doom-2016-mesa-19.2-radeon-vulkan-crash.txt)

**Comment by vrodic** [comment]
I've also reported this issue at https://gitlab.freedesktop.org/mesa/mesa/issues/1902, the developers suggested fix works.

**Comment by hakzsam** [comment]
Fixed.
https://gitlab.freedesktop.org/mesa/mesa/commit/ad96c4987cb2b23a9314a0a01fea8153843de8ef

**Comment by hakzsam** [comment]
@vrodic Can you please confirm that mesa master now works in order to remove the "Mesa drivers" label on it? Thanks!

**Comment by vrodic** [comment]
Yeah, it's fixed in Mesa master now.

**Comment by kisak-valve** [comment]
Hello @vrodic, thanks for reporting this issue. The [fix](https://gitlab.freedesktop.org/mesa/mesa/commit/03df69d6a1264d968f3afa2e64552e473bf19e6f) has made its way into Mesa 19.2.2.

Closing as fixed in the driver.
