### ISSUE TITLE
Cube World - D3D11CreateDevice failed: -2147467259

### ISSUE THREAD

**Issue by chwergy** [ValveSoftware/Proton#3131]
# Compatibility Report
- Name of the game with compatibility issues: Cube World
- Steam AppID of the game: 1128000

## System Information
- GPU: 
Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2
    Driver Version:  3.0 Mesa 18.3.6
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0x126

00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0126] (rev 09) (prog-if 00 [VGA controller])
        Subsystem: Lenovo 2nd Generation Core Processor Family Integrated Graphics Controller [17aa:21ce]
        Flags: bus master, fast devsel, latency 0, IRQ 28
        Memory at f0000000 (64-bit, non-prefetchable) [size=4M]
        Memory at e0000000 (64-bit, prefetchable) [size=256M]
        I/O ports at 5000 [size=64]
        [virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: i915
        Kernel modules: i915

- Driver/LLVM version: 3.0 Mesa 18.3.6
- Kernel version: 4.19.0-6-amd64
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 4.11-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Proton Log
https://gist.github.com/chwergy/1315d0bca22be65afd826e09a170c142

## System Information - Steam
https://gist.github.com/chwergy/9d0ba12114d95f3f9998d75ab5a73a04

## Symptoms 

Cube World won't start; displaying a dialog box that reads:
"Could not initialize Direct3d." grey wine-style dialog box

The dev seems to think that it should run thru proton out-of-the-box. Here are the contents of log_startup.txt which is the only log file I managed to find in the Cube World install directory.

"""
Start
load logo
create splash window
set splash image
SteamAPI_Init
InitRelayNetworkAccess
create main window
enum display settings
load options
select resolution
initialize graphics
D3D11CreateDevice
failed: -2147467259
failed
"""

Attached is a picture of the dialog box that pops up a few seconds after attempting to run Cube World using the latest version of proton (4.11).

I also attempted to run Cube World with versions 4.2 and 3.6 of Proton, but the log only got as far as SteamAPI_Init before exiting without an error (crash?) and the game failing to start.

Debian Buster.

## Reproduction

Enable Steam Play / Proton, Install Cube World, Click Play

![2019-10-07-121525_1366x768_scrot](https://user-images.githubusercontent.com/5986474/66350370-f672a300-e90f-11e9-90b5-f5b6adc28497.png)

**Comment by kisak-valve** [comment]
Hello @chwergy, we're using one issue report per unofficially supported game, and usually I'd transfer this issue report to #3079, but in this case it's pretty clear your hardware does not meet the minimum requirements for this game. Intel Sandybridge (Gen 6) graphics is DirectX 10 / OpenGL 3 generation hardware which is older than what the game requires. Additionally, Proton uses DXVK to translate DirectX 10/11 to Vulkan, and Sandybridge does not support Vulkan.

You may have luck trying `PROTON_USE_WINED3D=1 %command%` in the game's launch options, to make Proton use the DirectX 10 / 11 to OpenGL render path, but this is also not considered supported.

The same will be true for any other DirectX 10/11 games on that system.

**Comment by chwergy** [comment]
Thank-you for the prompt reply kisak.

You saved me from attempting an upgrade to bullseye (debian testing).

Hopefully this helps someone from attempting the same.
