### ISSUE TITLE
how to survive and xbox 360 controllers

### ISSUE THREAD

**Issue by bernardodpc** [ValveSoftware/Proton#3134]
sounds like the analogue triggers are mapped as one axis so the right trigger is always activated making the chars run all the time. its impossible to play it.
I was told the game is reading an xinput style controller via directinput but I dont know how to solve it.

**Comment by kisak-valve** [comment]
Hello @bernardodpc, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/666#issuecomment-540291801.
