### ISSUE TITLE
Grand Theft Auto V won't start anymore.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3139]
# Compatibility Report
- Name of the game with compatibility issues: Grand Theft Auto V
- Steam AppID of the game: 271590

## System Information
- GPU: GTX 1050 TI
- Driver/LLVM version: Nvidia 435.21
- Kernel version: 5.2.20-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Chou128/8efb716f3c92a2934ff7cb37a224eb96
- Proton version: 4.11-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 
[steam-271590.log](https://github.com/ValveSoftware/Proton/files/3715255/steam-271590.log)

## Symptoms 
After new update to Rockstar Game Launcher, GTA V no longer runs.  I receive this error: "Unable to locate the Rockstar Games Launcher, please verify your game data."

Game data is verified, executable exists in proper directory.

## Reproduction
Try to start GTA V

**Comment by kisak-valve** [comment]
Hello @Chou128, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-540867162.
