### ISSUE TITLE
Games suffer from performance regression on proton 4.11-7 (374320)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3140]
# Compatibility Report
- Name of the game with compatibility issues: MONSTER HUNTER: WORLD, Dark Souls III
- Steam AppID of the game: 582010, 374320

## System Information
- GPU: RX 480 8gb
- Driver/LLVM version: mesa 19.2.1
- Kernel version: 4.19
- Link to full system information report :https://gist.github.com/Utopanic/edfcf6a24846d1777e79d3aa6f67c914
- Proton version: 4.11-7

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ Yes] that I have checked whether there are updates for my system available.

Using `PROTON_LOG=1 %command%` didn't generate a report

## Symptoms 
The games on 4.11-6 ran more smoothly and with higher frame rates.  The regression also happened on mesa 19.1

I can run Rise of the tomb raider without problem.

**Comment by kisak-valve** [comment]
Hello @Utopanic, in general, performance regressions should be investigated on a per-game basis. Let's focus on Dark Souls III in this issue report because it's on the whitelist.

Feel free to add a note to #175 for the performance drop you've noticed with Monster Hunter World.

**Comment by ghost** [comment]
Today it works just fine.
The only thing that changed was an update to pamac which is totally unrelated to steam.
I hate technology.
Sorry for wasting your time.
