### ISSUE TITLE
Assassin's Creed Odyssey (812140) broken since 4.11-7 (can't find Uplay installation)

### ISSUE THREAD

**Issue by donutloop** [ValveSoftware/Proton#3148]
i updated from 4.11-6 to  4.11-7 since then this game isn't playable anymore because it can't anymore detect the Uplay installation on the machine. Everything worked on 4.11-6 without issues.

![Selection_001](https://user-images.githubusercontent.com/9432921/66715231-f287ca80-edc0-11e9-845f-43ec557f22ad.png)

# Compatibility Report
- Name of the game with compatibility issues: Assassin's Creed Odyssey
- Steam AppID of the game: 812140

## System Information
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0xc
    CPU Type:  0x0
    Speed:  5000 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 18.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-65-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20190711.3

Video Card:
    Driver:  NVIDIA Corporation GeForce RTX 2080 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 415.27
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 120 Hz
    VendorID:  0x10de
    DeviceID:  0x1e07
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.94" x 11.97" (24.09" diag)
                                            53.2cm x 30.4cm (61.2cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 11264 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC1220

Memory:
    RAM:  32098 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  467922 Mb
    Largest Free Hard Disk Block:  37278 Mb
    VR Headset: None detected

## Proton version 
* 4.11-7

**Comment by kisak-valve** [comment]
Hello @donutloop, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1757#issuecomment-541413006.
