### ISSUE TITLE
Arma 3 (107410) mouse input broken as of Proton 4.11-7

### ISSUE THREAD

**Issue by MaxBrains** [ValveSoftware/Proton#3149]
# Compatibility Report
- Name of the game with compatibility issues: Arma 3
- Steam AppID of the game: 107410

## System Information
- GPU: GTX 970
- Driver/LLVM version: 4.6.0 NVIDIA 435.21
- Kernel version: 5.3.5-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/MaxBrains/ed3afa54cd59b699bcbe36b13955b9c3
- Proton version: 4.11-7

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-107410.log](https://github.com/ValveSoftware/Proton/files/3721985/steam-107410.log)

## Symptoms 
Mouse button input in menus is non-functional. All mouse control in-game is non-functional. This is a REGRESSION from 4.11-6, in which mouse input was fully functional.

## Reproduction
1) Start Arma 3 using Proton 4.11-7
2) Move the mouse cursor over any clickable widget and click; nothing happens.
3) Use the tab key to navigate to VR Arsenal. Press enter to enter VR Arsenal.
4) Press enter once VR Arsenal is loaded to take control of the player character.
5) Move the mouse; nothing happens. Click the mouse buttons; nothing happens.

**Comment by kisak-valve** [comment]
Hello @MaxBrains, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2364#issuecomment-541437982.
