### ISSUE TITLE
Controller connect before game start cause game fail

### ISSUE THREAD

**Issue by howdev** [ValveSoftware/Proton#3153]
# Compatibility Report
- Darksiders 3
- Steam AppID of the game: 606280

## System Information
- GPU: 1060
- Driver: Nvidia 340.40
- Kernel version: <4.15>
- Proton version: 4.11-7

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
dualshock 4 Bluetooth. When controller connected before starting the game, Steam exists and the game trying to continue but freezes, need to force close the game. 

The game starts OK without the controller connected, then connect the controller, the game continued to work.

## Reproduction
Using Steam Overlay and game controller option "forced on"
Start Steam
Turn on Dualshock 4 controller using Bluetooth connection
Start Darksiders 3
[steam-system.log](https://github.com/ValveSoftware/Proton/files/3732016/steam-system.log)
[steam-606280.log](https://github.com/ValveSoftware/Proton/files/3732017/steam-606280.log)

**Comment by kisak-valve** [comment]
Hello @howdev, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2357#issuecomment-542471683.
