### ISSUE TITLE
Mordhau (629760)

### ISSUE THREAD

**Issue by Gregzenegair** [ValveSoftware/Proton#3156]
# Compatibility Report
- Mordhau
- Steam AppID of the game: 629760

## System Information
OS: Linux Mint 19.2 Tina (64 bits)
KERNEL: 4.15.0-58-generic
CPU: Intel Core i5-4690K @ 3.50GHz
GPU: NVIDIA GeForce GTX 970
GPU DRIVER: NVIDIA 430.40
RAM: 16 GB
Sound card :
0 [CA0106 ]: CA0106 - CA0106
Live! 7.1 24bit [SB0410] at 0xc000 irq 16
- https://gist.github.com/Gregzenegair/c73433987f2614287569338380ee7a5e
- Proton version: 4.11-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-629760.log](https://github.com/ValveSoftware/Proton/files/3736167/steam-629760.log)

The game only outputs stereo audio whereas I have a surround 5.1 audio system.

## Reproduction

Launch the game, try to hear sound spatialized with 5.1 outputs

**Comment by kisak-valve** [comment]
Hello @Gregzenegair, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2629#issuecomment-542869926.
