### ISSUE TITLE
Add vkBasalt to proton

### ISSUE THREAD

**Issue by andreldmonteiro** [ValveSoftware/Proton#3160]
# Feature Request

Add vkBasalt to proton.

It makes a huge difference in image quality, demo here: `https://cutt.ly/DegSQDx`

`https://github.com/DadSchoorse/vkBasalt/`

## I confirm:
- [yes ] that I haven't found another request for this feature.
- [ yes] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

I suggest adding this interesting optional feature to proton called Contrast Adaptive Sharpening.

## Justification [optional] 

Because it would never be merged in wine.

## Risks [optional]

None.

**Comment by Valmar33** [comment]
I wouldn't consider adding it at this stage ~ it's far too early in development for that.

Please, wait a few months before even beginning to evaluate it.

Consider this: https://www.gamingonlinux.com/imagecompare.php?1=9017237031571658615gol1.png&2=17122218051571658614gol1.png

Left image is vanilla, right image is vkBasalt.

**Comment by doitsujin** [comment]
Why does this need to be part of Proton? This is basically like asking Steam on Windows to ship Reshade - which also probably isn't ever going to happen.

**Comment by aeikum** [comment]
Yes, this is outside the scope of Proton. I think the right way to do this is to implement it as a Vulkan layer and distribute it as distro packages, which the user can then enable. It would then also work for non-Proton games.

**Comment by doitsujin** [comment]
It actually **is** already a Vulkan layer that users can install and enable, for Arch there is even a [PKGBUILD](https://aur.archlinux.org/packages/vkbasalt/) in the AUR.
