### ISSUE TITLE
Add Path of Exile to Proton

### ISSUE THREAD

**Issue by cvelasco88** [ValveSoftware/Proton#3161]
Hi Valve/Proton team,

last month I could play Path of Exile "without" problems on Linux (Ubuntu 19.04) but trying updates and upgrades 4 nvidia and ubuntu 19.10 everything went to hell.
The thing is that I could play normally. I am not sure if the title was allowed to run on Steam with Proton and is just now that it's needed to "force all titles to play with", but please, check this title to be playable with Steam.

Additionally, one month ago the pre-content cache for shaders started every day for this game (downloading 6.3 GB before starts)  but now (some weeks ago) the game doesn't create shaders cache. I think that this functionallity is useful, specially if you have a nvidia 1050ti and the fps are on the limit. Please check that too.

Regards,

**Comment by kisak-valve** [comment]
Hello @hollowsaibot, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/58#issuecomment-544699830.
