### ISSUE TITLE
Atelier Arland series Deluxe Pack - アトリエ ～アーランドの錬金術士１・２・３～ DX (9121)

### ISSUE THREAD

**Issue by BillFleming** [ValveSoftware/Proton#3163]
# Compatibility Report
- Name of the game with compatibility issues:  `Atelier Arland series Deluxe Pack - アトリエ ～アーランドの錬金術士１・２・３～ DX`
- Steam AppID of the game: 9121

## System Information
- GPU: Vega 64
- Driver/LLVM version: Mesa 19.3/9.0.0 (ACO git AUR 19.3.0_devel.20191017.fe930ad92ab-7)
- Kernel version: 5.3.1
- Proton version: 4.18.r2.ge380c1e9 (proton-tkg staging build from this morning)

## Description
After seeing a hint posted from Philip Rebohle I went back and retested all 3 of these games and got them working. This so far only works on the newer staging builds, not vanilla proton yet and not the 4.18 plain wine based custom build.
I set the steam input setting to "Forced Off" as at least in one of the 3 games the x360 controller didn't work with default settings.
I set the following the launch options: "PROTON_USE_WINED3D=1 %command%"

All 3 games I see the menu appear, I can load up my save game, audio works and the game appears to be fully playable now. I will have to wait to provide more info after work but wanted to let yall know.
I see there is already a report just for Rorona, but if it is allowed to have one report for the bundle pack I have posted this separately to cover all 3 Arland games. Note the video does not play still, but you can of course load up the beginning/ending videos in a video player to see them.

**Comment by kisak-valve** [comment]
Hello @BillFleming, 9121 is a subid for the game bundle, not an appid and we're using one issue report per unofficially supported game title. I see no value in splitting this feedback from #2724, so
I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2724#issuecomment-545436800.
