### ISSUE TITLE
building Proton in Ubuntu 18.04 with steam-runtime

### ISSUE THREAD

**Issue by Slavjan** [ValveSoftware/Proton#3164]
# overview

I followed to [build instuctions](https://github.com/ValveSoftware/Proton/wiki/Build-instructions-(Fedora))

- [x] programs was installed via `apt`;
- [x] repositories was cloned;
- [x] dockers amd64 && i386 was built via `./steam-runtime/setup_docker.sh ...`:
><pre>$ docker images
>REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
>steam-proton-dev32   latest              5bd5bd93f7aa        44 hours ago        1.9GB
>steam-proton-dev     latest              2e8533b50c6c        45 hours ago        2.01GB
></pre>

- [ ]  congiure of Makefile for `proton-mybuild` is successful;

But when I tried to build `$ make`
I've been got error, associated with `docker_init` binary file:
<pre>make  -f Makefile NO_NESTED_MAKE=1
make[1]: Entering directory &apos;/home/slavjan/Downloads/proton/proton/build&apos;
mkdir -p obj-cmake32
[FATAL tini (8)] exec /sbin/docker-init failed: No such file or directory
../build/makefile_base.mak:267: recipe for target &apos;obj-cmake32&apos; failed
make[1]: *** [obj-cmake32] Error 127
make[1]: Leaving directory &apos;/home/slavjan/Downloads/proton/proton/build&apos;
../build/makefile_base.mak:17: recipe for target &apos;nested_make&apos; failed
make: *** [nested_make] Error 2
</pre>

I tried to correct that.
- [x] I found `docker_init` file in next directories `/snap/docker/current`
- [x] I tried to swap line `/sbin/docker_init` to `/snap/docker/current/bin/docker_init` in `makefile_base.mak`,  but that did not lead to a decision. I got the same trouble, but with swapped line.
<pre>make  -f Makefile NO_NESTED_MAKE=1
make[1]: Entering directory &apos;/home/slavjan/Downloads/proton/proton/build&apos;
mkdir -p obj-cmake32
[FATAL tini (7)] exec /snap/docker/current/bin/docker-init failed: No such file or directory
../build/makefile_base.mak:267: recipe for target &apos;obj-cmake32&apos; failed
make[1]: *** [obj-cmake32] Error 127
make[1]: Leaving directory &apos;/home/slavjan/Downloads/proton/proton/build&apos;
../build/makefile_base.mak:17: recipe for target &apos;nested_make&apos; failed
make: *** [nested_make] Error 2
</pre>

I think that problem assocated with `snap` features in Ubuntu 18.04, but I can`t found solution.

## I confirm:
- [ ] that I haven't found another request for this feature.
- [ ] that I have checked whether there are updates for my system available that
      contain this feature already.
- [ ] searching in `forum.ubuntu.ru :: proton` and many other forums, many google pages...

![tp0hFfKN_400x400](https://user-images.githubusercontent.com/10784962/67406199-f47f3400-f5df-11e9-952a-79d0e078de2f.jpg)

**Comment by Slavjan** [comment]
Sorry for my English

**Comment by aeikum** [comment]
That's weird. How old are your Steam runtime Docker containers? Back in July, the init path was changed from `/dev/init` to `/sbin/docker-init`, see 02ce41610d0839346947db149ff4e43a1d59d37a. I just rebuilt my containers this morning and it is still `/sbin/docker-init`, so I can't explain why your Docker containers don't have that path, unless they are very old.

**Comment by Slavjan** [comment]
thank you for advice. I insert `/dev/init` and building-up was running.
