### ISSUE TITLE
NosTale gets wrong font rendering (550470)

### ISSUE THREAD

**Issue by memegauste** [ValveSoftware/Proton#3165]
# Compatibility Report
- Name of the game with compatibility issues: NosTale
- Steam AppID of the game: 550470

## System Information
- GPU: Rx480 4GB
- Driver/LLVM version: Mesa 19.2.1-2
- Kernel version: 5.3.7-arch1-1-ARCH
- Proton version: 4.11

## Symptoms 
Font are rendered badly, because wrong FREETYPE settings.

## Solution
Set 
`FREETYPE_PROPERTIES="truetype:interpreter-version=35"`
Before launching wine, but I'm not sure how to do that in steam proton.

**Comment by kisak-valve** [comment]
Hello @HoshiYamazaki, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/635#issuecomment-545560633.
