### ISSUE TITLE
BATTLETECH (637090)

### ISSUE THREAD

**Issue by jarrard** [ValveSoftware/Proton#3168]
I wish to throw this out there to see if anyone knows why this Unity3D game fails to launch when forced to use proton? 

At present it crashes and spits out a error log similar to the one linked below. I know there is a native version but it uses OpenGL and has significant performance issues, so I want to test the d3d11 version to do some comparisons.

[steam-637090.log](https://github.com/ValveSoftware/Proton/files/3766307/steam-637090.log)

**Comment by jarrard** [comment]
It seems installing dotnet4.5 was enough to get it working?

**Comment by jarrard** [comment]
Game appears to run better then on windows10 (I dual boot). This could be either because I only installed dotnet45 and not 472 (it failed to go past 45), OR most likely I set the container to Win7 via protontricks, its possible the issues I faced under windows10 are isolated to windows10 itself because I read about plenty of people who have no issues with general performance of the game under windows.

The typical issue you face under windows10 and linux with this game is gradual slow down after several missions which can also show themselves as stutters and such (could still happen via proton), VERY slow AI turn times (doesn't seem to be happening with proton/win7 config). 

I have yet to test a urban mission to see how it performs, but so far this configuration looks like a winner, also I should mention I'm running modtek advanced 3062 mod. (i've tested vanilla and issues still existed, tho the turn time issue was more severe)

UPDATE: Urban maps do run better then native, overall game performs better then native Unity3D build of the game.

**Comment by thatcosmonaut** [comment]
Works pretty much fine out of the box but the game hangs on exit and I have to kill the process. Tested with Proton 5.0.7

**Comment by jarrard** [comment]
Wine-Mono may also work, and now dotnet 5.0 can be compiled under Linux (apparently) so lets just say this works just fine if people want to play the windows version for added stability/smoothness since the Linux version runs off OpenGL its a bit jenky _(common for older Linux ports)_. 

Proton-TKG will install wine-mono automatically, not sure about proton-ge.
