### ISSUE TITLE
Disco Elysium (632470)

### ISSUE THREAD

**Issue by albertzdic** [ValveSoftware/Proton#3169]
# Compatibility Report
- Name of the game with compatibility issues: Disco Elysium
- Steam AppID of the game: 632470

## System Information
- GPU: NVIDIA Corporation GM107M [GeForce 940M] (rev a2)
-2nd GPU: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
- Driver/LLVM version: 3.0 Mesa 19.2.1 and 4.6.0 NVIDIA 435.21
[steam-632470.log](https://github.com/ValveSoftware/Proton/files/3766943/steam-632470.log)

- Kernel version: 5.3.0-19-generic
- Link to full system information report as 
intel --> https://gist.github.com/albertzdic/313790853635fed421648eeaf4754966
nvidia ---> https://gist.github.com/albertzdic/b597d0e8c26596fae5ed56ad08e5b551
- Proton version: 4.11-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
I can play with the integrated intel graphics card without problem (with the PROTON_USE_WINED3D=1) but if i try to play 
 with the nvidia 940M the game start but fails to render background texture, in game, the background in the menu is normal.

## Reproduction
1. start the game with <PROTON_USE_WINED3D=1 %command%> option

this is a sceenshot: 
![Screenshot from 2019-10-24 12-06-39](https://user-images.githubusercontent.com/36342370/67476343-650d6b80-f647-11e9-8be6-34d4487642ef.png)

<!--
![Screenshot from 2019-10-24 12-01-16](https://user-images.githubusercontent.com/36342370/67476788-3e9c0000-f648-11e9-9fc5-c961b1a0de02.png)

<!--

**Comment by kisak-valve** [comment]
Hello @albertzdic, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3167#issuecomment-545899095.

**Comment by albertzdic** [comment]
Sorry.
