### ISSUE TITLE
Doom (2016 ) fails to load when Steam Overlay is enabled (379720)

### ISSUE THREAD

**Issue by kwahoo2** [ValveSoftware/Proton#317]
To reproduce:
Set graphics API to Vulkan
Set Steam Overlay as enabled
Set graphics preset to Ultra

Doom freezes after intro videos, loading meter stops at 99%, and I can hear menu music.

My specs https://gist.github.com/kwahoo2/033eedf8e8462e0957cf17039c84aa27

**Comment by LeJimster** [comment]
I experience no crash, but the steam overlay doesn't display in Vulkan mode, I see a faint flicker and then it disappears. In OpenGL mode it displays correctly.

My specs https://gist.github.com/LeJimster/7751f48f10bf0082158bace47dec7430

**Comment by kwahoo2** [comment]
After today update of libdrm from PADOKA PPA to 2.4.94+git1808281609.f3d90e8~b~padoka0 the problem does not happen anymore.
