### ISSUE TITLE
Donut Country - Unity GetThreadContextFailed crash after each level

### ISSUE THREAD

**Issue by xsgb** [ValveSoftware/Proton#3170]
# Compatibility Report
- Name of the game with compatibility issues: Donut Country
- Steam AppID of the game: 702670

## System Information
- GPU: GM107M
- Driver/LLVM version: 435.21
- Kernel version: 5.0.0-32-generic
- System informations: https://gist.github.com/xsgb/c304553efee1dcc2a4739f6e00c52c4c
- Proton version: 4.11.7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
The games crash with a **Fatal error in gc** dialog, saying _GetThreadContext failed_. after each level ending dialogue scene.

## Reproduction
Start the game, play until the end of one level and the end of the dialog scene.
[steam-702670.log](https://github.com/ValveSoftware/Proton/files/3769543/steam-702670.log)

**Comment by kisak-valve** [comment]
Hello @xsgb, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2158#issuecomment-546112205.
