### ISSUE TITLE
dirt rally 2.0 racenet

### ISSUE THREAD

**Issue by jaspi72** [ValveSoftware/Proton#3177]
![IMG_20191028_183422](https://user-images.githubusercontent.com/34282195/67698331-d5ebb500-f9b2-11e9-935b-acdda9c4a764.jpg)

Racenet not working on using FerenOS steam.
Tryed now week and same error everytime opening game. Game works ok but racenet not, please help!

**Comment by kisak-valve** [comment]
Hello @jaspi72, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2366#issuecomment-547091038.
