### ISSUE TITLE
Suggestion: Automatically use WineD3D when Vulkan is unavailable

### ISSUE THREAD

**Issue by Technohacker** [ValveSoftware/Proton#3178]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
On systems without Vulkan support, many games fail to run because DXVK reports no support for a given Direct3D level. As an example, on an Intel Sandybridge processor with Intel HD 3000 graphics, it lacks Vulkan support but WineD3D works well with the OpenGL 3.0 support. There is an environment variable `PROTON_USE_WINED3D` for this already, but most users would not find it first hand. Defining this automatically when we don't see Vulkan support will ease this process.

## Justification [optional] 
Proton uses DXVK by default, hence this is useful in Proton more than Wine

## Risks [optional]
There could be situations with incorrect Vulkan detection, but we can always provide an override if that happens

## References [optional] 
N/A

**Comment by kisak-valve** [comment]
Hello @Technohacker, this request was previously evaluated at #1749 and concluded with https://github.com/ValveSoftware/Proton/pull/1749#issuecomment-489606572 and https://github.com/ValveSoftware/Proton/pull/1749#issuecomment-489618385.

**Comment by Technohacker** [comment]
Ah shoot, didn't see those earlier. Sorry for the duplicate :sweat_smile:
