### ISSUE TITLE
Pamali: Indonesian Folklore Horror (854570)

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/Proton#3179]
# Compatibility Report
- Name of the game with compatibility issues: Pamali: Indonesian Folklore Horror
- Steam AppID of the game:854570

## System Information
- GPU: RX VEGA 56
- GPU Driver: `19.3.0~git1910291605.f9ad73cdfd2~b~mesaaco0 (ppa:ernstp/mesaaco)`
- Kernel version: 5.4.0-050400rc5-lowlatency
- Distro version: Linux Mint 19.2 Tina (64 bit) (Cinnamon)
- Proton version: 4.11-7

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

Launching the game there is just a black screen and an error message pops up saying "Fatal Error!". Launching the game with Steam launch option "-onethread" the game appears to work perfectly without issues (the performance is solid 60fps with maxed settings at 1600p too).

Tried LLVM and ACO, also older Proton version, but it made no difference.

Logs of crashes, and one of successfully playing two missions:
[steam-854570-proton-4.2-9.log](https://github.com/ValveSoftware/Proton/files/3785863/steam-854570-proton-4.2-9.log)
[steam-854570-proton-4.11-7.log](https://github.com/ValveSoftware/Proton/files/3785865/steam-854570-proton-4.11-7.log)
[steam-854570-proton-4.11-7-onethread.log](https://github.com/ValveSoftware/Proton/files/3785866/steam-854570-proton-4.11-7-onethread.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3785867/system_info.txt)

_Note that there is a demo version of this game on Steam too, the demo worked on this same setup out of the box without any launch options. The full version I tested here is the Folklore Anthology version with all the content_ 

## Reproduction
- Just launch the game

**Comment by Guy1524** [comment]
I see you're getting an exception while the executable is loading, however I am unable to reproduce your issue, as the game boots fine without any extra command line parameters.

**Comment by AwesamLinux** [comment]
@Guy1524 hmm... I suspect that this could be an Unreal Engine 4 in combination with Threadripper CPU specific issue. 

Especially considering that the game works for me when setting it to use one thread. I have encountered a couple of Unreal Engine 4 games before that crashed in a similar way on my hardware (regardless of Proton version, Kernel or GPU driver), even though the game appeared to work for most other people.

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX 5700
- GPU Driver: Mesa 20.0.0-devel (git-2ebfc6d 2020-01-16 bionic-oibaf-ppa)
- Kernel version: 5.3.18-050318-lowlatency
- Distro version: 19.3 Tricia (64 bit) (Cinnamon)
- Proton version: 4.11-12

**Retest Compatibility Report**

Game works now for me out of the box without needing to limit to one thread (game recently got an update, so this could have been actually a bug in the game). 

There is just one minor remaining issue, the startup video is skipped (contains just developer logo animations). It appears to be the only video used in the game.

#1464 Log mentions mfplat.dll
Codecs are: MPEG-4, AVC1 + AAC

[media_info.txt](https://github.com/ValveSoftware/Proton/files/4087669/media_info.txt)
[steam-854570-aco.log](https://github.com/ValveSoftware/Proton/files/4087670/steam-854570-aco.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/4087671/system_info.txt)

**Comment by AwesamLinux** [comment]
Closing this issue, as videos look like they work now, and I did not spot any other issues from briefly testing this on proton-7.0-3-rc1

[system_info.txt](https://github.com/ValveSoftware/Proton/files/8835652/system_info.txt)
