### ISSUE TITLE
Warsim: The Realm of Aslona

### ISSUE THREAD

**Issue by Huw2k8** [ValveSoftware/Proton#3180]
# Whitelist Request
- Name of the game to be whitelisted: Warsim: The Realm of Aslona
- Steam AppID of the game: 659540

## System Information
- GPU: 
- Driver/LLVM version: 
- Distro version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [ ] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @Huw2k8, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2829#issuecomment-548182158.
