### ISSUE TITLE
GTA V Unable to locate launcher

### ISSUE THREAD

**Issue by Adenis890** [ValveSoftware/Proton#3182]
# Compatibility Report
- Name of the game with compatibility issues: Grand Theft Auto V
- Steam AppID of the game: 271590

## System Information
- GPU:  GTX 1050TI
- Driver/LLVM version:  nvidia 435.21
- Kernel version:  5.3.0-19-generic (Ubuntu 19.10)
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Adenis890/fed556d5ef7720dd31ffd18e3646c0c3
- Proton version: 4.11-7

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @Adenis890, we're using one issue report per unofficially supported game title, and this is a known issue with fresh installs of the game and is being discussed on #37. There's an experimental build of Proton at https://github.com/ValveSoftware/Proton/issues/37#issuecomment-546055205.

Closing in favor of #37.

**Comment by Adenis890** [comment]
I'm really sorry i didn't know that there are specific threads. Thanks a
lot!!!! It worked.
