### ISSUE TITLE
The Witcher 3 and Mesa 19.3/git (292030)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3185]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher 3
- Steam AppID of the game: 292030

## System Information
- GPU: RX 570
- Driver/LLVM version: Mesa git, LLVM 9.0.0
- Kernel version: 5.3.0
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/atomsymbol/e1c42aedb0d366fdbb2e7bf82c5a9015
- Proton version: 4.2-9, 4.11-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

The Witcher 3 works fine with Mesa 19.2.2, but fails to start with Mesa git. This issue may also be reproducible with other Proton games.

The game seems to start fine in plain Wine 4.18 outside of Steam.

## Reproduction

1. Update Mesa to latest git version
2. Start The Witcher 3
3. An exception is reported by Proton's Wine in the terminal running Steam. The game does not create any window.

**Comment by kisak-valve** [comment]
Hello @atomsymbol, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-549057753.

It would also be a good idea to bring this to the attention of your video driver vendor.

**Comment by ghost** [comment]
> It would also be a good idea to bring this to the attention of your video driver vendor.

Hi @kisak-valve. Because the game works with mesagit+wine4.18 and does not work with mesagit+Proton4.2/4.11 the current conclusion is that the component causing the failure is Proton 4.2/4.11. The conjecture that mesagit is the cause of this issue is currently not supported by evidence/measurement.

**Comment by kisak-valve** [comment]
The conclusion should be that DXVK in Proton goes to a vulkan render path instead of OpenGL with upstream wine's wined3d.

Let's continue this discussion on #607.

**Comment by ghost** [comment]
> we're using one issue report per unofficially supported game title

I would like to note that this strategy leads to the one issue report containing stale comments mentioning problems that have already been resolved. Effort must be devoted to identifying meaningful (non-stale) comments.
