### ISSUE TITLE
can't reliably disable esync, Proton ignores PROTON_NO_ESYNC=1 and WINEESYNC=0

### ISSUE THREAD

**Issue by qptain-Nemo** [ValveSoftware/Proton#3191]
# Compatibility Report
- Name of the game with compatibility issues: primarily testing Disco Elysium, but it also affects every other game I've tried
- Steam AppID of the game: 632470 is an example, but not unique to a single game

## System Information
- GPU: GeForce GTX 750 Ti
- Driver/LLVM version: nvidia 435.21
- Kernel version: 5.3.7-arch1-2-ARCH
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/qptain-Nemo/2058e70320020c202cbb89491c3659ea
- Proton version: 4.11-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-632470.log](https://github.com/ValveSoftware/Proton/files/3806005/steam-632470.log)

## Symptoms 
Adding PROTON_NO_ESYNC=1 to the launch options makes any game exit immediately with the "Server is running with WINEESYNC but this process is not, please enable WINEESYNC or restart wineserver" output in the log. Running the whole Steam with WINEESYNC=0 seemed to work for a while but then modifying unrelated launch options (such as enabling the Steam overlay) made Proton fail to disable esync again. Deleting the prefix seems to fix it for one run, but then on a second launch it is ignoring these options and refusing to run again. This seems to be repeatable indefinitely. Steam outputs "esync: up and running." in the terminal when this issue manifests.

## Reproduction
Passing PROTON_NO_ESYNC=1 in the launch options to a game intermittently causes the issue for me.

**Comment by aeikum** [comment]
Good catch. Will fix, thanks for reporting!

**Comment by zany130** [comment]
Also get this issue with valkyrie chronicles deleting the prefix doesn't solve it for me nor does starting steam with wineesync =0

**Comment by aeikum** [comment]
This should be fixed in 4.11-8. Please retest.

**Comment by qptain-Nemo** [comment]
Tested PROTON_NO_ESYNC=1 with Disco Elysium (several times) and Fallout 4. Seems to be working as intended without any additional steps. Thank you for your good work!

**Comment by zany130** [comment]
Fixed for me too.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as fixed.
