### ISSUE TITLE
Wreckfest crashes with full system freeze

### ISSUE THREAD

**Issue by mroote** [ValveSoftware/Proton#3192]
# Compatibility Report
- Name of the game with compatibility issues: Wreckfest
- Steam AppID of the game: 228380

## System Information
- GPU: GTX 1060
- Driver/LLVM version: 435.21
- Kernel version: 5.3.8-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/mroote/1b47f9a6d3c624204453de5819062db2
- Proton version: 4.11-7

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

## Symptoms 

The game will completely freeze my desktop with no ability to alt-tab or make any actions on the system like switch window sessions. I can only recover with a reboot to get back to the normal desktop.  

The only error I can see being logged in the system logs are regarding a fault with the video card but I haven't found anything else that seems to stand out as causing this issue.

`Nov 04 19:10:07 ghost kernel: NVRM: Xid (PCI:0000:01:00): 31, pid=647, Ch 00000043, intr 10000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_T1_4 faulted @ 0x5fff_55b17000. Fault is of type FAULT_PDE ACCESS_TYPE_READ`

**Comment by kisak-valve** [comment]
Hello @mroote, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/758#issuecomment-549619246.
