### ISSUE TITLE
ValveSoftware/vkd3d is 404

### ISSUE THREAD

**Issue by chuck-r** [ValveSoftware/Proton#3197]
The vkd3d folder is a submodule linked to https://github.com/ValveSoftware/vkd3d. However, this repository doesn't exist. Also, the commit that the submodule points to doesn't exist upstream. This means that it's impossible to build Proton-4.11-8 as provided.

**Comment by kisak-valve** [comment]
Hello @chuck-r, thanks for reporting. The repo is now available.
