### ISSUE TITLE
Crashing with esync enabled

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#32]
Phantom Doctrine (UE4) crashes on startup with esync enabled. With it disabled using `PROTON_NO_ESYNC`  in `user_settings.py`, the game starts up fine. (however there are still some issues)

In terminal while crashing:
```
eventfd: Too many open files
esync: write: Bad file descriptor
Protocol error: process 0028: sendmsg: Bad file descriptor
```

**Comment by ghost** [comment]
Solution: increase systemd `DefaultLimitNOFILE` [as explained here](https://github.com/zfigura/wine/blob/esync/README.esync)

**Comment by Guy1524** [comment]
I think that upon installation steam should increase the FD limit.

**Comment by kisak-valve** [comment]
Hello @DougTy, @Guy1524, increasing FD limits is a privileged operation requiring root permission and most likely will not change any time in the future. This is also documented at https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md#fd-limit-requirements.
