### ISSUE TITLE
EVE Online

### ISSUE THREAD

**Issue by aravoth** [ValveSoftware/Proton#3202]
# Compatibility Report
- Name of the game with compatibility issues: EVE Online
- Steam AppID of the game: 8500

## System Information
- GPU: NVIDIA 360m
- Driver/LLVM version: 340
- Kernel version: 4.15.0-66
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/aravoth/421aa47dfc3b4924a622ab54f426686d
- Proton version:4.11.8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton log is too large to post link to gist here : https://gist.github.com/aravoth/45d32fc84bf326f067b7c7f5afaa6f85

## Symptoms 
Game crashes at start. Worked flawlessly under proton 4.11.7. Cannot get past the launcher.

## Reproduction
Running EVE with proton 4.11.8 reproduces crash every time

**Comment by kisak-valve** [comment]
Hello @aravoth, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1223#issuecomment-552215545.
