### ISSUE TITLE
The Witcher 3 + Mesa 19.1 - game trying to start, but windows hangs (black screen)

### ISSUE THREAD

**Issue by Gman1988** [ValveSoftware/Proton#3203]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher 3
- Steam AppID of the game: 292030

## System Information
- GPU: Radeon R9 390 Gaming G1,
- Driver/LLVM version: Mesa 19.1.8
- Kernel version: 5.3.8-200.fc30.x86_64
- Link to full system information report as [Gist](https://gist.github.com/):
https://gist.github.com/Gman1988/5220e19f6838438aa10c98d1294d2276
- Proton version: 4.11-8

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

[steam-292030.log](https://github.com/ValveSoftware/Proton/files/3828914/steam-292030.log)

## Symptoms 
Gamer is trying to start, new full-screen window opens, but stays black. After a while it stops responding.

## Reproduction
Just start the game.

**Comment by kisak-valve** [comment]
Hello @Gman1988, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-552228870.
