### ISSUE TITLE
4.11-8 - Assassins Creed has stopped to work properly

### ISSUE THREAD

**Issue by vinifmor** [ValveSoftware/Proton#3217]
# Compatibility Report
- Assassin's Creed
- 15100

## System Information
- GPU: Nvidia GTX 970
- Driver/LLVM version: nvidia 440.26
- Kernel version: 5.3.8.MANJARO
- Log: https://gist.github.com/vinifmor/fe07485b89f3ff0625656f50825044f3
- Proton version: 4.11-8

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
The game was working properly with Proton 4.11-7 using D9VK or DXVK (DX10 using d3dcompiler_43). In 4.11-8 the main screen becomes very slow (almost frozen) and it seems the mouse does not work ( the screen ask to press any key to continue, but the mouse / keyboard input seems not to be recognized). It becomes impossible to play the game.

## Reproduction
1) For D9VK -> launch options: PROTON_USE_D9VK=1 PROTON_NO_D3D11=1 %command%
2) For DXVK -> launches the games the first time and the main screen will get black. Quit the game and install d3dcompiler_43 (protontricks 15100 d3dcompiler_43). Launch it again.

**Comment by kisak-valve** [comment]
Hello @vinifmor, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/183#issuecomment-553215059.
