### ISSUE TITLE
Final Fantasy X/X-2 HD Remaster (359870) Steam Input non-functional

### ISSUE THREAD

**Issue by Rossco1337** [ValveSoftware/Proton#3219]
# Compatibility Report
- Name of the game with compatibility issues: Final Fantasy X/X-2 HD Remaster
- Steam AppID of the game: 359870

## System Information
- GPU: GTX 1070 Ti
- Driver/LLVM version: nvidia-440.26
- Kernel version: 5.3.8.3
- Link to full system information report as [Gist](https://gist.github.com/Rossco1337/7860c4459caabd07b05b89f6b12c791f)
- Proton version: 4.11-8 (Also tested 4.19-GE)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-359870.log](https://github.com/ValveSoftware/Proton/files/3845476/steam-359870.log)

## Symptoms 
Steam Input is not working correctly in this game. Guide button/Big Picture can be navigated but none of my 3 controllers can interact with the game. Tested Switch Pro Controller, Dualshock 3 and Nyko Airflo (Generic Gamepad ID 124b:4d01), 

## Reproduction
- Launch Final Fantasy VII/another Proton game to verify that Steam Input is working in other Proton games.
- Launch Final Fantasy X and pause the intro cutscene with Esc.
- None of the buttons are working.

I don't have a Windows environment or any friends who own this game to verify that this is a Proton issue, but I can't find anyone online using Windows with this issue. If this isn't a Proton issue, please direct me to the correct bug tracker. Thanks.

**Comment by kisak-valve** [comment]
Hello @Rossco1337, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/555#issuecomment-553884745.

**Comment by jefferyrlc** [comment]
Trying to launch this game with DXVK requires PROTON_FORCE_LARGE_ADDRESS_AWARE=1, otherwise the game will freeze, either in the opening CS, or loading a save. Playing the game with PROTON_FORCE_LARGE_ADDRESS_AWARE=1 is fine until you summon an Aeon in-game, where the animation never finishes and the game essentially "softlocks." Since the game uses DX10/11 using PROTON_USE_WINED3D leads to significant artifacting, and is essentially unplayable.
