### ISSUE TITLE
Weird audio issue with PROTON 4.11-8 that wasn't present on previous versions.

### ISSUE THREAD

**Issue by CSahajdacny** [ValveSoftware/Proton#3220]
Environmental sounds effects, like the music coming from a radio, disappear totally when I move the mouse...
With PROTON 4.11-7 that didn't happen.

Here is an example of what I am writing about with the audio of Borderlands: The Presequel via forced PROTON 4.11-8 when I am the same place of, for example, Moxxi's at Concord, pointing the mouse to different directions... **Is not the only game with this audio issue..**

Music from speakers loud and clear
![20191114133012_1](https://user-images.githubusercontent.com/45825041/68881103-48ff6600-06eb-11ea-89af-0e614f125f13.jpg)

Music from speakers is gone (and I am exactly in the same place).

![20191114133051_1](https://user-images.githubusercontent.com/45825041/68880197-911d8900-06e9-11ea-8feb-834430c380f8.jpg)

The same problem happen with the voices of NPCs and weapons sounds. 

How to download PROTON 4.11-7 or previous?

**Comment by kisak-valve** [comment]
Hello @CSahajdacny, what other games are you hearing this issue with? Also, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by CSahajdacny** [comment]
Sorry for the time wasted.
It was a hardware issue... 
Solved.
