### ISSUE TITLE
Noita (881100)

### ISSUE THREAD

**Issue by TehCorwiz** [ValveSoftware/Proton#3221]
# Compatibility Report
- Name of the game with compatibility issues: Noita
- Steam AppID of the game: 881100

## System Information
- GPU: Nvidia GTX 1080
- Driver/LLVM version: Nvidia 440.31
- Kernel version: 5.3.0-22-generic
- Link to full system information report as [Gist](https://gist.github.com/TehCorwiz/fff9358141d13962f1fd58ecc8518075):
- Proton version: 4.11-8

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

There are two other reports for the game:
- The first was a user file-system issue: https://github.com/ValveSoftware/Proton/issues/3105
  - I've already verified that my directories have the correct ownership and permissions.
- The second is an in-game performance issue: https://github.com/ValveSoftware/Proton/issues/3176

[steam-881100.log](https://github.com/ValveSoftware/Proton/files/3849131/steam-881100.log)

## Symptoms
Game does not launch. No window, No sound. Crash occurs within 2 seconds of starting.

## Reproduction
1. Open Steam
1. Enable Steam Play
1. Install Noita
1. Click 'Play'
1. Crash

**Comment by kisak-valve** [comment]
Hello @TehCorwiz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3176#issuecomment-554139347.
