### ISSUE TITLE
Original "Resident Evil" and "Resident Evil 2" fail to recognize hardware acceleration support

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#3222]
# Compatibility Report

Resident Evil and Resident Evil 2 (originals)

https://appdb.winehq.org/objectManager.php?sClass=version&iId=9396

https://appdb.winehq.org/objectManager.php?sClass=application&iId=8375

## System Information
- GPU: GTX 760
- Driver/LLVM version: Nvidia 440.31
- Kernel version: 5.3.11
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia
- Proton version: 4.11-8

The original RE1 and RE2 fail to recognize video card hardware acceleration, only software mode is selectable.

Patch available:
https://bugs.winehq.org/show_bug.cgi?id=19153

## Reproduction

Install RE1 and/or RE2 and try and enable hardware acceleration, which can’t be done at the moment.

**Comment by FurtadoPires** [comment]
Can we post issues with non-steam games in this git?

**Comment by shoober420** [comment]
I don’t see why not, just make a separate issue about it.

**Comment by shoober420** [comment]
I made a pull request about this issue instead, closing.

https://github.com/ValveSoftware/Proton/pull/3730
