### ISSUE TITLE
Crashing Everytime i respawn a car

### ISSUE THREAD

**Issue by Headscientist** [ValveSoftware/Proton#3223]
My beam.ng Game keeps crashing every-time i re-spawn a car in a big map, i think its my
GPU but i don't really know, i hope i would get some answers!

**Comment by kisak-valve** [comment]
Hello @Headscientist, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1237#issuecomment-554171342.
