### ISSUE TITLE
Age Of Mythology: dxvk::DxvkError

### ISSUE THREAD

**Issue by RastaTux** [ValveSoftware/Proton#3228]
# Compatibility Report
- Name of the game with compatibility issues: Age Of Mythology (Extended Edition)
- Steam AppID of the game: 266840

## System Information
- GPU: NVIDIA GM107M [GeForce GTX 850M]
- Driver/LLVM version: nvidia-driver-435
- Kernel version: 5.3.0-23-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/RastaTux/ff6648dbf7dde9681c09eb601c3e7a31
- Proton version: 4.11-8

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-266840.log](https://github.com/ValveSoftware/Proton/files/3856152/steam-266840.log)

## Symptoms
When the title screen starts, the game breaks (Also happens when i bypass the launcher). The game worked before, this issue happens since I installed some bumblebee things. Unfortunally, i don't know what i exactly did.
PS: I have a double graphics card setup, the NVIDIA is the second one.

## Reproduction
Start the game with proton steam play activated.

**Comment by kisak-valve** [comment]
Hello @RastaTux, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1547#issuecomment-554792723.
