### ISSUE TITLE
S.T.A.L.K.E.R: Call of Pripyat performance regression

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#3229]
# Compatibility Report
- Name of the game with compatibility issues: S.T.A.L.K.E.R: Call of Pripyat / System Shock: Enhanced Edition
- Steam AppID of the game: https://steamdb.info/app/41700/ - https://steamdb.info/app/410710/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.31
- Kernel version: 5.3.11
- https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341
- Proton version: 4.11-8

## Symptoms
Serious performance regression

**Comment by kisak-valve** [comment]
Hello @shoober420, are you using d9vk with these games? This reads like #3198.

**Comment by shoober420** [comment]
I dont think its related to D9VK, since I've run some other games and they are ok. Heres a list of games that are working and not running properly, regardless if "PROTON_USE_D9VK=1" is used.

WORK: S.T.A.L.K.E.R.: Shadow of Chernobyl, SHOGO, Grand Theft Auto 3, Final Fantasy VII, System Shock 2

UNPLAYABLE (5FPS): S.T.A.L.K.E.R.: Call of Prypyat and System Shock: Enhanced Edition

**Comment by shoober420** [comment]
I believe you are right about this being an issue with a D9VK update. I made an issue on the D9VK github, and its being address there. Sorry for the confusion.

https://github.com/Joshua-Ashton/d9vk/issues/455
