### ISSUE TITLE
Dirt Rally crashes with Proton 4.11-8

### ISSUE THREAD

**Issue by laichiaheng** [ValveSoftware/Proton#3231]
# Compatibility Report
- Name of the game with compatibility issues: Dirt Rally
- Steam AppID of the game: 310560

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 19.2.4
- Kernel version: 5.4-rc7
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/laichiaheng/b8e6eb9ccff4772c07ea1ebe69a178eb
- Proton version: 4.11-8

[steam-310560.zip](https://github.com/ValveSoftware/Proton/files/3858382/steam-310560.zip)

## Symptoms 
The graphic crashes.

## Reproduction
Play the game.

**Comment by laichiaheng** [comment]
I haven't run into issue since I switched to native opengl and switched back to Proton, so later.

**Comment by kisak-valve** [comment]
Hello @laichiaheng, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3022#issuecomment-555022402.
