### ISSUE TITLE
Painkiller: Black Edition crash on startup patch for d9vk

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#3234]
# Compatibility Report
- Name of the game with compatibility issues: Painkiller: Black Edition
- Steam AppID of the game: https://steamdb.info/app/39530/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.31
- Kernel version: 5.3.11
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia
- Proton version: 4.11-8

## Symptoms 
Painkiller: Black Edition crashes on startup using d9vk

## Reproduction
Enable d9vk, and attempt to launch

More info here.
https://github.com/Joshua-Ashton/d9vk/issues/234
https://source.winehq.org/patches/data/167679

**Comment by kisak-valve** [comment]
Hello @shoober420, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/661#issuecomment-555991044.
