### ISSUE TITLE
System Shock: Enhanced Edition texture bugs in OpenGL

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#3236]
# Compatibility Report
- Name of the game with compatibility issues: System Shock: Enhanced Edition
- Steam AppID of the game: https://steamdb.info/app/410710/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.31
- Kernel version: 5.3.11
- https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341
- Proton version: 4.11-8

## Symptoms 
Texture bugs are present when playing the game. Even during intro.

## Reproduction
Play the game

![757AA7D0-E98D-4409-8658-9D233F66B2CA](https://user-images.githubusercontent.com/5150898/69214908-37c4b800-0b36-11ea-9223-cff1b30e904f.jpeg)
![7417292B-FA2E-4F45-AC61-6722B2B43C0A](https://user-images.githubusercontent.com/5150898/69214909-37c4b800-0b36-11ea-8c62-23b091a6051e.jpeg)
![7089A2C6-683F-4EAC-9C87-582FC7EC542C](https://user-images.githubusercontent.com/5150898/69214910-37c4b800-0b36-11ea-8552-8092e429dc70.jpeg)

**Comment by kisak-valve** [comment]
Hello @shoober420, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3235#issue-525600388.
