### ISSUE TITLE
The Witcher 2 memory allocation

### ISSUE THREAD

**Issue by kkleinw** [ValveSoftware/Proton#3238]
There seems to be a memory allocation bug that leads to the game crashing on proton. Shortly before the crash there may be a warning that 3.9 of 4.0 gb memory are allocated and that OpenGL is not clearing it's cache. This warning may not always be seen. Easier to reproduce in second act.

**Comment by kisak-valve** [comment]
Hello @kkleinw, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2309#issuecomment-556430003.
