### ISSUE TITLE
Proton 4.11-8 D9VK has weird frametime spikes while same release from D9VK github doesn't have

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/Proton#3241]
As described in the title. With Proton 4.11-8 D9VK you will see periodic frame time spikes while those spikes doesn't happen if you replace it with release from projects Github page.

![Ekran Görüntüsü - 2019-11-14 02-25-05](https://user-images.githubusercontent.com/24878978/69329929-0dbce400-0c63-11ea-896e-8e8f8e90a487.png)

**Comment by kisak-valve** [comment]
Hello @Leopard1907, please read the discussion on #3198.

**Comment by Leopard1907** [comment]
Thanks , i've read it. If it is being tracked, i will close this. One question tho ; same situation also exist on DXVK i assume? Since i saw various people on Reddit etc complaining about stutters and low perf with dxvk titles too.

**Comment by aeikum** [comment]
Yes, it can also affect DXVK. So far it seems to only affect 32-bit titles, but I'm not sure if that's actually true. We should have a fix for it very soon.

**Comment by Leopard1907** [comment]
Thanks for the answer. Might be affecting dxvk also because strangely despite i even used shader_build <appid> there are frametime spikes ( stutters ) happens on Witcher 3.

It wasn't like that before.

**Comment by Leopard1907** [comment]
Sleeping Dogs Definitive Edition - 64 bit 

![20191127193458_1](https://user-images.githubusercontent.com/24878978/69743358-5be45280-114f-11ea-8f22-ebd3829aabf9.jpg)

![20191127194820_1](https://user-images.githubusercontent.com/24878978/69743365-6272ca00-114f-11ea-86ad-c0f0218d6cba.jpg)

It affects dxvk and 64 bit titles as well it seems.

**Comment by aeikum** [comment]
This should be fixed in 4.11-9. Please retest.

**Comment by Leopard1907** [comment]
I've tested both games on 4.11-9 and issue is fixed. Thanks. Closing.
