### ISSUE TITLE
SCUM Crashes

### ISSUE THREAD

**Issue by Klairm** [ValveSoftware/Proton#3242]
# Compatibility Report
- Name of the game with compatibility issues: SCUM
- Steam AppID of the game:513710

## System Information
- GPU: GTX 750Ti
- Driver/LLVM version: Nvidia 435.21
- Kernel version: 5.3.11-1MANJARO
- Link to full system information report as https://gist.github.com/Klairm/16075fe7bc0e3934b30e558b8835e010
- Proton version: Tried with 4.11 and 4.2 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

`PROTON_LOG=1 %command%`  -> https://github.com/Klairm/proton-scum-log/blob/master/steam-513710.log
`WINEDEBUG="-all,trace-err" %program% >> $HOME/test.log` -> https://pastebin.com/c8uC7FBU

## Symptoms 
I launch the game and it stucks at the loading screen, also seems to be an error window which i can't see -> https://imgur.com/a/YkhRXv4 

## Reproduction
Launch the game
Expect that the game will crash

EDIT: I know that EAC kicks players using Linux, but the offline mode should be working good

**Comment by kisak-valve** [comment]
Hello @Klairm, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1248#issuecomment-557142663.
