### ISSUE TITLE
Build fail with "*** No rule to make target '../proton/openvr/bin/win32/openvr_api.dll', needed by 'dist/dist/lib/wine/dxvk/openvr_api_dxvk.dll'.  Stop."

### ISSUE THREAD

**Issue by avrilfanomar** [ValveSoftware/Proton#3248]
git tag: proton-4.2-9

vagrant ssh -c 'make -C "build--local"/ STEAM_DIR=/vagrant/ install'
Platform: 8 CPUs, 7962 MB memory
make: Entering directory '/home/vagrant/build--local'
make install -f Makefile NO_NESTED_MAKE=1
make[1]: Entering directory '/home/vagrant/build--local'
mkdir -p dist/dist
cp -a ../proton/toolmanifest.vdf dist/toolmanifest.vdf
cp -a ../proton/filelock.py dist/filelock.py
cp -a ../proton/proton dist/proton
cp -a ../proton/proton_3.7_tracked_files dist/proton_3.7_tracked_files
cp -a ../proton/user_settings.sample.py dist/user_settings.sample.py
make[1]: *** No rule to make target '../proton/openvr/bin/win32/openvr_api.dll', needed by 'dist/dist/lib/wine/dxvk/openvr_api_dxvk.dll'.  Stop.
make[1]: Leaving directory '/home/vagrant/build--local'
../proton/build/makefile_base.mak:17: recipe for target 'nested_make' failed
make: *** [nested_make] Error 2

**Comment by aeikum** [comment]
Is your `openvr` submodule up to date?

**Comment by avrilfanomar** [comment]
@aeikum Sorry for stupid question, but how do I check it?

**Comment by aeikum** [comment]
`git submodule status` in the parent repo will do it. I suggest googling around for how Git submodules work, we use them a lot in Proton.

**Comment by avrilfanomar** [comment]
Apparently I did plain clone without `--recurse-submodules` option, that was the problem.
Thanks for help!
