### ISSUE TITLE
Allow users to use Wine Instead Of Proton

### ISSUE THREAD

**Issue by trymeouteh** [ValveSoftware/Proton#3249]
Proton is great, but for some games some users may want to use Wine instead of Proton. Please allow users to download any specific wine version and wine staging version and set any games to run with wine instead of Proton. Here is how I can see this working.

In the Steam client, users can download any wine version just like they can with any Proton version. Once it is downloaded, users can select Wine #.## for a specific game.

Instead of using a wine version you have installed within Steam, users can select the path to a Wine version that was installed with another program such as PlayOnLinux and use that. Custom paths will be allowed such as _/home/USER/Documents/Wine 4.20-staging/bin/wine_

Soon, it will be easy to use Proton without the Steam client with the upcoming update PlayOnLinux update which will allow users to use any wine version and any Proton version. Please give Steam users the choice between Wine and Proton for their Steam library games.

**Comment by kisak-valve** [comment]
Hello @trymeouteh, Steam already has the required functionality to allow you to run other compatibility tools with the games, however, vanilla wine by itself is not really suitable as a drop in replacement. You're free to experiment and make your own flavor of Proton, or some other tool to run the games with. There are a couple other projects that take advantage of this like [Boxtron](https://github.com/dreamer/boxtron) or [proton-ge-custom](https://github.com/GloriousEggroll/proton-ge-custom).

In terms of support, Proton devs decide when they want to rebase the project on a newer upstream wine version and that's not going to change in the near future.

On Steam's side, there's a feature request at https://github.com/ValveSoftware/steam-for-linux/issues/5674 for this.
