### ISSUE TITLE
Can't launch warframe

### ISSUE THREAD

**Issue by M-ROZNIECKI** [ValveSoftware/Proton#3250]
# Compatibility Report
- Name of the game with compatibility issues: Warframe
- Steam AppID of the game: 230410

## System Information
- GPU: Nvidia 1050 Ti M
- Driver/LLVM version: nvidia-435
- Kernel version: 4.15.0

- Link to full system information report as [Gist](https://gist.github.com/FenrirAetherius/9a3d8a62cee60ff2711290fd7a53a1d6):
- Proton version: 4.11

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-230410-errors.log](https://github.com/ValveSoftware/Proton/files/3884211/steam-230410-errors.log)
(I did a grep on the log because they were too big to be send via github `cat steam-230410.log | grep -y Error > steam-230410-errors.log`)

## Symptoms 

After setup Nvidia-prime on Nvidia GPU I can't launche Warframe. The launcher got no problem but the game crash instantly after clicking on play.
After looking at errors on logs I can't define witch one is the cause of the crash and how to correct it.

**Comment by kisak-valve** [comment]
Hello @FenrirAetherius, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/167#issuecomment-557936460.
