### ISSUE TITLE
The Legend of Heroes - Trails in the Sky FC *cutscenes problems*

### ISSUE THREAD

**Issue by krauser87** [ValveSoftware/Proton#3255]
# Compatibility Report
- Name of the game with compatibility issues: The Legend of Heroes: Trails in the Sky FC
- Steam AppID of the game:251150

## System Information
- GPU: NVIDIA GM108M [GeForce 940M]
- Driver/LLVM version: nvidia
- Kernel version: 4.19
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 4.11.8-flatpak

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

[steam-251150.log](https://github.com/ValveSoftware/Proton/files/3886404/steam-251150.log)

## Symptoms 
The VIdeo and Audio from the cutscenes are not synchronized. The video scenes show up a bit delayed unlike the audio, so near the end when the cutscene is still happening, there's no more audio(looks like a 20 second difference between the audio ending and the video ending). Plus, I have to press a key/mouse button to start the video otherwise only audio plays
I followed these steps on the game's entry in protondb

> The game works fine except for videos. In game videos: 1. Startup logo. 2. Intro movie shortly after starting a new game. 3. End game movies.
> 
> Running protontricks 251150 directshow allowed the logo video to work. Installing K-Lite Codec Pack Basic into the prefix allowed the intro movie to work.

**Comment by kisak-valve** [comment]
Hello @krauser87, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1079#issuecomment-558158718.
