### ISSUE TITLE
Proton use iGPU instead of dGPU

### ISSUE THREAD

**Issue by Ahmed-E-86** [ValveSoftware/Proton#3257]
## System Information
- GPU: AMD HD 8750M
- Driver/LLVM version: Mesa 19.99 LLVM 10 (Padoka PPA)
- Kernel version: 5.0.0-36
- Proton version: 4.11-8

## Symptoms

I was playing The Awesome Adventure of Captain Spirit, and the game was so slow, with weird graphic glitches, then I closed the game, and went to Set Launch Options, and paste this command:

DRI_PRIME=1 %command%

and BAM, the game works as it should be.

I always do that when running games with Wine, but I didn't think that I will ever need to do that with Proton especially with DXVK using dGPU by default.

I don't know what is wrong here, and that was not the only game that has this issue. I encountered performance issues with multiple games, and I used Wine instead of Proton in the past, because I thought that something was wrong with Proton.

**Comment by kisak-valve** [comment]
Hello @ahmed-elsayed2017, this reads like the issue being tracked at #3215. Let's track this issue on the existing issue report, but of this issue isn't resolved when a fix ships for that issue and it's closed, let me know and I can re-open this issue report.

Adding `WINEDLLOVERRIDES="dxgi=n" %command%` to the game's launch options should also work as a workaround.

As a side note "mesa 19.99" is not a valid mesa version.
