### ISSUE TITLE
Dark Souls III(374320) crashing after a certain amount of time since 4.11.8

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3262]
# Compatibility Report
- Name of the game with compatibility issues: Dark Souls III
- Steam AppID of the game: 374320

## System Information
- GPU: nvidia rtx 2080
- Driver/LLVM version: 435.21
- Kernel version: manjaro 5.3.12
- Proton version: 4.11.8

Logs: https://pastebin.com/43qxEJUy

**Comment by laichiaheng** [comment]
I have just bought it, hope it will be solved soon.

**Comment by Newbytee** [comment]
> I have just bought it, hope it will be solved soon.

Proton 4.2-9 should be fine, you can go back to that in the meantime.

**Comment by ghost** [comment]
4.2-9 works, latest proton versions are also ok.
