### ISSUE TITLE
[INTEL test request] "ACPI-CPUfreq performance" leads to considerably LESS stutter than "intel_pstate performance" with Proton!

### ISSUE THREAD

**Issue by ACPI-ftw** [ValveSoftware/Proton#3265]
First of all, it would be really cool if Valve's engineers could also benchmark this observation and post their results! Please don't close this immediately and give it a chance to be proven right! Who knows, it might even help your Steam Cloud Gaming efforts...
Thanks in advance!

So, for those few of us who haven't yet been able to switch over to a AMD RyZen CPU, here's something you can do in the meantime to alleviate some of the impact from all those mitigations:
Disable Intel's P-State CPU driver by adding the following parameter to your Linux boot command-line:
`intel_pstate=disable`
Additionally, for the best gaming experience you should also switch over to the "performance" governor.
Don't worry about overheating by the way, since your CPU cores will alternate between the highest frequency and the deepest sleep state; you can check with `sudo cpupower monitor`.
Now try your favorite games with Proton and notice how much smoother they are running!

**Comment by kisak-valve** [comment]
Hello @ACPI-ftw, regardless of the outcome of testing, there's no action to be taken as a result of this request. General system tuning is a personal and distro maintainer's choice and outside the scope of this project.
