### ISSUE TITLE
Lord of the Rings Online - initial game self-update fails

### ISSUE THREAD

**Issue by binkley** [ValveSoftware/Proton#3266]
# Compatibility Report
- Name of the game with compatibility issues: The Lord of the Rings Online
- Steam AppID of the game: 212500

## System Information
- GPU: `lspci | grep -i nvid` says:
01:00.0 VGA compatible controller: NVIDIA Corporation TU106M [GeForce RTX 2070 Mobile] (rev a1)
01:00.1 Audio device: NVIDIA Corporation TU106 High Definition Audio Controller (rev a1)
01:00.2 USB controller: NVIDIA Corporation TU106 USB 3.1 Host Controller (rev a1)
01:00.3 Serial bus controller [0c80]: NVIDIA Corporation TU106 USB Type-C UCSI Controller (rev a1)
- Driver/LLVM version: `lsmod | grep -i nvid` says:
nvidia_uvm            913408  0
nvidia_drm             49152  14
nvidia_modeset       1122304  33 nvidia_drm
nvidia              19517440  1635 nvidia_uvm,nvidia_modeset
drm_kms_helper        184320  2 nvidia_drm,i915
drm                   491520  18 drm_kms_helper,nvidia_drm,i915
ipmi_msghandler       102400  2 ipmi_devintf,nvidia
i2c_nvidia_gpu         16384  0
- Kernel version: Linux bree 5.3.0-23-generic #25-Ubuntu SMP Tue Nov 12 09:22:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Link to full system information report as [Gist](https://gist.github.com/binkley/5d668384528a5c377c21f120cfc01d5a)
- Proton version: 4.11

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Attached (below): `$HOME/steam-212500.log`.

## Symptoms 

See error message, below.

## Reproduction

Run the game from Steam, which starts the LotRO launcher.  Before the came can run, the launcher downloads lots of data files and unpacks them.  It is during this phase of game launch that failure happens:

```
PatchFlow::AdmitFailure  [ "PatchClientDLL::CheckDatFiles Failed. [Unable to decrypt and de-serialize the data downloaded from the server.]"
```

**Comment by binkley** [comment]
[steam-212500.log](https://github.com/ValveSoftware/Proton/files/3906052/steam-212500.log)

**Comment by kisak-valve** [comment]
Hello @binkley, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1816#issuecomment-559851073.

**Comment by binkley** [comment]
@kisak-valve Thank you!  This is my first time using Proton, so wasn't aware of how issue reporting worked.  Your system makes a lot of sense.  Cheers!

**Comment by LankyFranky89** [comment]
When I am using experiemental the mouse sticks to the middle of the screen when I rotate the camera. It is not like that on Windows or earlier version of Proton-GE before 7-5
