### ISSUE TITLE
Sakura Clicker (383080)

### ISSUE THREAD

**Issue by laichiaheng** [ValveSoftware/Proton#3280]
# Compatibility Report
- Name of the game with compatibility issues: Sakura Clicker
- Steam AppID of the game: 383080

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 19.2.6
- Kernel version: 5.4.1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/laichiaheng/613c83fdfb4cd8e93e991e7c719d313b
- Proton version: 4.11-9

## I confirm:
- [V] that I haven't found an existing compatibility report for this game.
- [V] that I have checked whether there are updates for my system available.

## Symptoms 
Out of memory

## Reproduction
Run the game.

**Comment by kisak-valve** [comment]
Hello @laichiaheng, the log you've attached doesn't really show a failure, but in any case, can you check if adding `PROTON_FORCE_LARGE_ADDRESS_AWARE=1 %command%` to the game's launch options has an effect?

**Comment by laichiaheng** [comment]
@kisak-valve Thanks, it works. It also fixes the low frame rate issue in this game. What cause this?
