### ISSUE TITLE
Proton Version 4.11 - DCS World, GTR - FIA Racing Game do not launch

### ISSUE THREAD

**Issue by Jeducious** [ValveSoftware/Proton#3282]
Hi,

So I have followed the instructions [here](https://github.com/ValveSoftware/Proton/wiki/Requirements) to install the necessary drivers. I have a attached a dump of the output of steam after trying to launch DCS World. There is a crash with a stack trace near the end of the game, see [DSC WORLD STEAM stdout/stderr.txt](https://github.com/ValveSoftware/Proton/files/3915084/DSC.WORLD.STEAM.stdout.txt)

This happens also for GTR. Though I can try to start the game, it never loads and I get similar output from GTR also.

My hardware is nothing out of the ordinary, software is Ubuntu 19.04. For the exact setup I have, see [steam_system_info.txt](https://github.com/ValveSoftware/Proton/files/3915205/steam_system_info.txt)

Also in the system info file I see a lot of errors related to steam trying to list the items in the "graphics-details" section of "architectures". 

Any help would be appreciated, but I am not holding my breath there, this information is for the devs to hopefully make things work for average linux users like me. Gaming on linux would be nice, but so far I feel I have spent so much time trying to get this to work that its a bit of a turn off, and I am going to try and find a way to get a windows box up and running instead since I know I can run all these games on win 10 platform.

**Comment by kisak-valve** [comment]
Hello @Jeducious, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1722#issuecomment-561174151.
