### ISSUE TITLE
Nancy Drew: Midnight in Salem (1038450)

### ISSUE THREAD

**Issue by katspen** [ValveSoftware/Proton#3286]
# Compatibility Report
- Name of the game with compatibility issues: Nancy Drew: Midnight in Salem
- Steam AppID of the game: 1038450

## System Information
- GPU: Radeon HD 7950/8950
- Driver/LLVM version: [AMD/ATI] Tahiti PRO [Radeon HD 7950/8950 OEM / R9 280]
- Kernel version:  5.4.1-arch1-1
- Link to full system information report: https://gist.github.com/katspen/e3d8ee1b136d9ae602c6bfe300999abc
- Proton version: 4.11-9 

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Proton Log: https://gist.github.com/katspen/c11fd0a6564c20e8523849c0b36edfb9

## Symptoms
The game will start running, and the first few times a little window came up with a loading bar (the game's own launcher). This loading bar would fill up, the window would close, and then a few seconds later the game would stop running.

Since working on uploading the logs for this, the game will not open any windows or load at all. Steam will recognize it as running though. 
Tried using the [vulkan-radeon](https://www.archlinux.org/packages/extra/x86_64/vulkan-radeon/) package, and then the [amdvlk](https://www.archlinux.org/packages/extra/x86_64/amdvlk/) one, but didn't seem to help. (Noticed something in the logs that might've been relevant.)

## Reproduction
Game crashes when trying to launch

**Comment by kisak-valve** [comment]
Hello @katspen, you have a Southern Island (SI) generation video card and Linux uses the `radeon` kernel module with that generation by default. The `radeon` kernel module is not compatible with Vulkan. Please give https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games a read.

**Comment by katspen** [comment]
This worked! Thank you so much! You have changed my life.
