### ISSUE TITLE
Halo: The Master Chief Collection - Xbox Login

### ISSUE THREAD

**Issue by cryptodan** [ValveSoftware/Proton#3290]
I purchased this game yesterday, and upon installing it and running I get an error screen that says it failed to connect to the xbox network please try again or cancel.  I am running it on the following system:

[code]
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3800 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.4.1-arch1-1
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12006000
    X Window Manager:  Mutter(Budgie)
    Steam Runtime Version:  steam-runtime_0.20191119.3

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1070/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 440.36
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 75 Hz
    VendorID:  0x10de
    DeviceID:  0x1be1
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 15.04" x 8.46" (17.24" diag)
                                            38.2cm x 21.5cm (43.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 8192 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  16029 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  1877664 Mb
    Largest Free Hard Disk Block:  817894 Mb
    VR Headset: None detected

Steam Linux Runtime Information:
{
  "can-write-uinput" : true,
  "steam-installation" : {
    "path" : "/home/cryptodan/.local/share/Steam",
    "data_path" : "/home/cryptodan/.local/share/Steam",
    "issues" : [
    ]
  },
  "runtime" : {
    "path" : "/home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime",
    "version" : "0.20191119.3",
    "issues" : [
    ],
    "pinned_libs_32" : {
      "list" : [
        " 43122756      4 drwxr-xr-x   2 cryptodan cryptodan     4096 Dec  3 13:16 pinned_libs_32",
        " 43123293      4 -rw-r--r--   1 cryptodan cryptodan       69 Dec  3 13:16 pinned_libs_32/system_libdbusmenu-gtk.so.4",
        " 43123266      4 lrwxrwxrwx   1 cryptodan cryptodan      100 Dec  3 13:16 pinned_libs_32/libcurl.so.4 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libcurl.so.4.2.0",
        " 43123270      4 lrwxrwxrwx   1 cryptodan cryptodan      103 Dec  3 13:16 pinned_libs_32/libGLU.so.1 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libGLU.so.1.3.08004",
        " 43123272      4 lrwxrwxrwx   1 cryptodan cryptodan      100 Dec  3 13:16 pinned_libs_32/libjack.so.0 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libjack.so.0.1.0",
        " 43123291      4 -rw-r--r--   1 cryptodan cryptodan       70 Dec  3 13:16 pinned_libs_32/system_libgtk-x11-2.0.so.0",
        " 43124161      4 lrwxrwxrwx   1 cryptodan cryptodan       98 Dec  3 13:16 pinned_libs_32/libdbus-1.so.3 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libdbus-1.so.3.5.8",
        " 43123274      4 lrwxrwxrwx   1 cryptodan cryptodan      111 Dec  3 13:16 pinned_libs_32/libgtk-x11-2.0.so.0 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0.2400.10",
        " 43124177      4 -rw-r--r--   1 cryptodan cryptodan       55 Dec  3 13:16 pinned_libs_32/system_libudev.so.0",
        " 43123271      4 -rw-r--r--   1 cryptodan cryptodan       50 Dec  3 13:16 pinned_libs_32/system_libGLU.so.1",
        " 43123267      4 -rw-r--r--   1 cryptodan cryptodan       52 Dec  3 13:16 pinned_libs_32/system_libcurl.so.4",
        " 43123292      4 lrwxrwxrwx   1 cryptodan cryptodan      109 Dec  3 13:16 pinned_libs_32/libdbusmenu-gtk.so.4 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libdbusmenu-gtk.so.4.0.13",
        " 43124178      0 lrwxrwxrwx   1 cryptodan cryptodan       12 Dec  3 13:16 pinned_libs_32/libcurl.so.3 -> libcurl.so.4",
        " 43123295      4 lrwxrwxrwx   1 cryptodan cryptodan      110 Dec  3 13:16 pinned_libs_32/libdbusmenu-glib.so.4 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libdbusmenu-glib.so.4.0.13",
        " 43123268      0 -rw-r--r--   1 cryptodan cryptodan        0 Dec  3 13:16 pinned_libs_32/has_pins",
        " 43123273      4 -rw-r--r--   1 cryptodan cryptodan       53 Dec  3 13:16 pinned_libs_32/system_libjack.so.0",
        " 43124165      4 -rw-r--r--   1 cryptodan cryptodan       58 Dec  3 13:16 pinned_libs_32/system_libdbus-1.so.3",
        " 43124176      4 lrwxrwxrwx   1 cryptodan cryptodan       97 Dec  3 13:16 pinned_libs_32/libudev.so.0 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libudev.so.0.13.0",
        " 43124157      4 -rw-r--r--   1 cryptodan cryptodan       71 Dec  3 13:16 pinned_libs_32/system_libdbusmenu-glib.so.4"
      ]
    },
    "pinned_libs_64" : {
      "list" : [
        " 43122772      4 drwxr-xr-x   2 cryptodan cryptodan     4096 Dec  3 13:16 pinned_libs_64",
        " 43122830      4 -rw-r--r--   1 cryptodan cryptodan       65 Dec  3 13:16 pinned_libs_64/system_libdbusmenu-gtk.so.4",
        " 43122774      4 lrwxrwxrwx   1 cryptodan cryptodan      102 Dec  3 13:16 pinned_libs_64/libcurl.so.4 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libcurl.so.4.2.0",
        " 43122779      4 lrwxrwxrwx   1 cryptodan cryptodan      105 Dec  3 13:16 pinned_libs_64/libGLU.so.1 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libGLU.so.1.3.08004",
        " 43122782      4 lrwxrwxrwx   1 cryptodan cryptodan      102 Dec  3 13:16 pinned_libs_64/libjack.so.0 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libjack.so.0.1.0",
        " 43124159      4 -rw-r--r--   1 cryptodan cryptodan       51 Dec  3 13:16 pinned_libs_64/system_libudev.so.0",
        " 43122781      4 -rw-r--r--   1 cryptodan cryptodan       46 Dec  3 13:16 pinned_libs_64/system_libGLU.so.1",
        " 43122775      4 -rw-r--r--   1 cryptodan cryptodan       48 Dec  3 13:16 pinned_libs_64/system_libcurl.so.4",
        " 43122817      4 lrwxrwxrwx   1 cryptodan cryptodan      111 Dec  3 13:16 pinned_libs_64/libdbusmenu-gtk.so.4 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libdbusmenu-gtk.so.4.0.13",
        " 43124180      0 lrwxrwxrwx   1 cryptodan cryptodan       12 Dec  3 13:16 pinned_libs_64/libcurl.so.3 -> libcurl.so.4",
        " 43123241      4 lrwxrwxrwx   1 cryptodan cryptodan      112 Dec  3 13:16 pinned_libs_64/libdbusmenu-glib.so.4 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4.0.13",
        " 43122778      0 -rw-r--r--   1 cryptodan cryptodan        0 Dec  3 13:16 pinned_libs_64/has_pins",
        " 43122783      4 -rw-r--r--   1 cryptodan cryptodan       49 Dec  3 13:16 pinned_libs_64/system_libjack.so.0",
        " 43124158      4 lrwxrwxrwx   1 cryptodan cryptodan       99 Dec  3 13:16 pinned_libs_64/libudev.so.0 -> /home/cryptodan/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu/libudev.so.0.13.0",
        " 43123260      4 -rw-r--r--   1 cryptodan cryptodan       67 Dec  3 13:16 pinned_libs_64/system_libdbusmenu-glib.so.4"
      ]
    }
  },
  "os-release" : {
    "id" : "arch",
    "name" : "Arch Linux",
    "pretty_name" : "Arch Linux",
    "build_id" : "rolling"
  },
  "architectures" : {
    "i386-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "ERROR: [Loader Message] Code 0 : /home/cryptodan/.local/share/Steam/ubuntu12_64/libVkLayer_steam_fossilize.so: wrong ELF class: ELFCLASS64\n",
          "renderer" : "GeForce GTX 1070",
          "version" : "1.1.119 (device 10de:1be1) (driver 440.144.0)"
        },
        "glx/gl" : {
          "renderer" : "GeForce GTX 1070/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.36"
        },
        "egl_x11/gl" : {
          "renderer" : "GeForce GTX 1070/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.36"
        },
        "egl_x11/glesv2" : {
          "renderer" : "GeForce GTX 1070/PCIe/SSE2",
          "version" : "OpenGL ES 3.2 NVIDIA 440.36"
        }
      }
    },
    "x86_64-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "ERROR: [Loader Message] Code 0 : /home/cryptodan/.local/share/Steam/ubuntu12_32/libVkLayer_steam_fossilize.so: wrong ELF class: ELFCLASS32\n",
          "renderer" : "GeForce GTX 1070",
          "version" : "1.1.119 (device 10de:1be1) (driver 440.144.0)"
        },
        "glx/gl" : {
          "renderer" : "GeForce GTX 1070/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.36"
        },
        "egl_x11/gl" : {
          "renderer" : "GeForce GTX 1070/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.36"
        },
        "egl_x11/glesv2" : {
          "renderer" : "GeForce GTX 1070/PCIe/SSE2",
          "version" : "OpenGL ES 3.2 NVIDIA 440.36"
        }
      }
    }
  },
  "locale-issues" : [
    "c-utf8-missing",
    "i18n-supported-missing"
  ],
  "locales" : {
    "<default>" : {
      "resulting-name" : "en_US.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    },
    "C" : {
      "resulting-name" : "C",
      "charset" : "ANSI_X3.4-1968",
      "is_utf8" : false
    },
    "C.UTF-8" : {
      "error-domain" : "srt-locale-error-quark",
      "error-code" : 0,
      "error" : "No such file or directory"
    },
    "en_US.UTF-8" : {
      "resulting-name" : "en_US.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    }
  },
  "egl" : {
    "icds" : [
      {
        "json_path" : "/usr/share/glvnd/egl_vendor.d/10_nvidia.json",
        "library_path" : "libEGL_nvidia.so.0"
      },
      {
        "json_path" : "/usr/share/glvnd/egl_vendor.d/50_mesa.json",
        "library_path" : "libEGL_mesa.so.0"
      }
    ]
  },
  "vulkan" : {
    "icds" : [
      {
        "json_path" : "/usr/share/vulkan/icd.d/nvidia_icd.json",
        "library_path" : "libGLX_nvidia.so.0",
        "api_version" : "1.1.119"
      }
    ]
  }
}

The Steam Linux Runtime container tool is not installed.
[/code]

**Comment by vsod99** [comment]
See https://github.com/ValveSoftware/Proton/issues/2907.

**Comment by cryptodan** [comment]
Where is the fix in that mess of comments and discussion?  I did not see anything in that post regarding a fix for the issue.  So I thought to create a completely related one to the xbox login issue so a proper fix can be posted here without a lot of comments with no determined fix and a lot of random unrelated issues I saw.

**Comment by vsod99** [comment]
Try this build. 

https://github.com/ValveSoftware/Proton/issues/2907#issuecomment-561917242

This is a work in progress. There is no magic fix and people are going to have varying issues - it's how ongoing development is.

**Comment by kisak-valve** [comment]
Hello @cryptodan, we're using one issue report per unofficially supported game title, and this issue has been discussed extensively on #2907. Closing in favor of the existing issue report.

**Comment by cryptodan** [comment]
Then can you please be so kind to direct me to the fix in the massive comment thread in the other report as there is no definitive fix highlighted that will get me going on my game on linux. THat thread and reported issue is a complete mess and does not address the xbox login screen error specifically.  I can see multiple issues being discussed which makes it difficult to find a fix for the xbox login issue.

**Comment by OvermindDL1** [comment]
Right now just look near the end.  A working fix was only recently just discovered and it's very manual work right now, but it will be made into something easily distributable soon no doubt.

**Comment by McMarius11** [comment]
this is the best version to this date:
https://github.com/rkfg/proton-ge-custom/releases/tag/Guy1524
i'm running manjaro KDE with nvidia without any problems

**Comment by cryptodan** [comment]
And how do you implement the fix and use that version of Proton?  There is no definitive instruction on what to do with the files once you download and extract it.  The package also does not include a readme.

**Comment by OvermindDL1** [comment]
@cryptodan As with all github things, the instructions are on the homepage of the project, see the "How to install" section:  https://github.com/rkfg/proton-ge-custom

:-)

**Comment by cryptodan** [comment]
Thank you, and there should be a readme.md located in the files that are downloadable on the above link that McMarius11 posted.
