### ISSUE TITLE
Phantom Doctrine (UE4) - all audio sources are at max volume

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#33]
After getting the game to launch (see #32), all audio sources ingame are at max volume regardless of distance from the camera. The volume sliders in the ingame settings menu don't do anything (always max volume).

Additionally, audio is very crackly and skippy.

**Comment by E100Beta** [comment]
Having similar issue with A Hat in Time (UE3), all sounds are equal value, audio settings do nothing. Can't hear people talking because of overly loud music.

**Comment by ghost** [comment]
@E100Beta Thanks for sharing!! Because of that I was actually able to find a solution for A Hat in Time, which also works with Phantom Doctrine. Apparently you need the `xact` audio library installed. If you have wine installed natively you can do this with the following command:

```
WINEPREFIX=/home/doug/Storage/SteamLibrary/steamapps/compatdata/559100/pfx/ winetricks xact
```

Just replace the path & app id of course.

It would be great to have a way to automate winetricks configs like this.

**Comment by ghost** [comment]
I've made a new issue for this as affects many games #54

**Comment by ghost** [comment]
Same thing happens with The Solus Project. Also uses UE4 engine.
