### ISSUE TITLE
DOOM(2016) freezing after 1-30 minutes (379720)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3310]
### System information
- Setting: 1440p at 144hz and ultra
- GPU: RTX 2080
- Driver: 440.31
- CPU Ryzen 1800x
- Proton version: from 3.16-9 to 4.11-9

The smallest log was 290Mb so I only uploaded the beginning and the end of it [here](https://pastebin.com/mCa7e9r1). The freeze doesn't need any specific trigger to appear - it can happen when no other app runs or when I'm fighting, walking or just standing still.

I also experienced crashes in Dark Souls 3 since 4.11-8(https://github.com/ValveSoftware/Proton/issues/3262) but not nearly as much as in Doom. Other games like the Witcher 3 and Dying Light do not crash with proton.

**Comment by ghost** [comment]
Enabling the steam overlay didn't help.

**Comment by ghost** [comment]
This only happens with the vulkan backend.

**Comment by Hasshu** [comment]
@trialism Could your RAM be unstable? I have a Ryzen 5 3600, and kept encountering freezes and crashes in some games under Proton, until I realized that my B450 board couldn't handle the XMP of my RAM ([MemTest86](https://www.memtest86.com/) would detect large amounts of errors). Slightly lowering the memory frequency made all those issues go away.

**Comment by ghost** [comment]
Nope, the RAM was fine. I finished the game with a new driver.

**Comment by Hasshu** [comment]
I see. Incidentally, did the new driver help with #3262?

**Comment by ghost** [comment]
@Hasshu no, only new proton versions. Older ones also work.
