### ISSUE TITLE
Distraint (395170): Fullscreen and DS4 controller work in Wine but not in Proton

### ISSUE THREAD

**Issue by namandixit** [ValveSoftware/Proton#3314]
# Compatibility Report
- Name of the game with compatibility issues: DIstraint
- Steam AppID of the game: 395170

## System Information
- GPU: NVidia MX 150
- Driver/LLVM version: 3.0 Mesa 19.2.7
- Kernel version: 5.3.15 (on Fedora 31)
- Link to full system information report as [Gist](https://gist.github.com/): [System Information](https://gist.github.com/namandixit/5f10d36fb45e8a55b63c59cf9a1d41a8)
- Proton version: 4.11-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-395170.log](https://github.com/ValveSoftware/Proton/files/3959121/steam-395170.log)

## Symptoms 

When running through Proton, the game can not be switched to Fullscreen. Moreover, the Steam Overlay doesn't come up and DS4 controller does not work.

However, when launching the game directly from Wine (version `wine-4.21 (Staging)`) , both fullscreen and DS4 work properly.

## Reproduction

With Proton:

1. Launch game through Proton.
2. Trying to switch to fullscreen just results in a screen flash.
3. Steam overlay's "popup" doesn't show up.
4. Dualshock 4 input do not seem to get detected.

With Wine:
1. Launch through wine using `wine distraint.exe`
2. Both fullscreen and DS4 input works.

**Comment by kisak-valve** [comment]
Hello @namandixit, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1939#issuecomment-565442640.
