### ISSUE TITLE
Alien Swarm (630)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3319]
# Whitelist Request
- Name of the game to be whitelisted: Alien Swarm
- Steam AppID of the game: 630

## System Information
- GPU: RV710
- Driver/LLVM version: 3.0 Mesa 19.2.0
- Distro version: Ubuntu 18.04
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kakolisgay/51a5a76a38b33d66f1f7e4dff63da1de
- Proton version: 4.11-9

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [ ] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [x] Although I consider the gaming experience equal to Windows there are remaining issues:
  - Uncommon random lag spikes which last for one to two minutes.
  - FPS slowly lowering over time

I have not encountered #276 (Alien Swarm Freezes after clicking "Offline Practice"), Alien Swarm has been free of crashes and (game-breaking) freezes for me. Since I'm using an old machine a config was required to get acceptable fps, someone on a mid-range machine likely wouldn't need to bother with that.

**Comment by kisak-valve** [comment]
Hello @kakolisgay, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/276#issuecomment-565719847.
