### ISSUE TITLE
Gothic Playable Teaser

### ISSUE THREAD

**Issue by KJVGalations216** [ValveSoftware/Proton#3328]
I played Gothic Playable Teaser on Linux (Pop OS!) through Steam Play and the syslogs (syslog, syslog.1) grew quite a bit in size, including syslog.1 becoming at least 9gb according to file manager. I tried clearing the syslogs now but I think it was showing over and over about something in the game files, including words like blueprint and bird.  Thank you. 
https://ffbrkjv.com/The_Gospel_Story

**Comment by KJVGalations216** [comment]
RX 580 I5 9400f Pop! OS latest Proton on Steam I can see 4.11-10
https://ffbrkjv.com/The_Gospel_Story

**Comment by kisak-valve** [comment]
Hello @KJVGalations216, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3321#issuecomment-565840466.

Also, please stop posting links that are unrelated to your issue report.
