### ISSUE TITLE
Add option to execute shell command before and after game launch.

### ISSUE THREAD

**Issue by y-salnikov** [ValveSoftware/Proton#3335]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
You can execute specific commands before and after launching of game with `Set Launch Options` button, but only for native games. Can you add some variables like PROTON_BEFORE_CMD and PROTON_AFTER_CMD? For example It can be useful for temporary disabling of standalone compositing manager, like `PROTON_BEFORE_CMD="killall picom" PROTON_AFTER_CMD="nohup picom" %command%`.

**Comment by aeikum** [comment]
Should this be moved to the Steam client tracker? If it works for native games, there's no reason it can't work for Proton games as well.

**Comment by kisak-valve** [comment]
Hello @aeikum, this scenario has come up before on the Steam client side at https://github.com/ValveSoftware/steam-for-linux/issues/6306 and the previous assessment should still be true. If there isn't interest in handling the direct request, then this is better handled by a short launcher script similar to the one proposed in that issue report.

**Comment by aeikum** [comment]
I don't think we want to add this. Please use a wrapper script like suggested.
