### ISSUE TITLE
[Whitelist] Elder Scrolls: Legends (364470)

### ISSUE THREAD

**Issue by Draecal** [ValveSoftware/Proton#334]
It would be awesome to add this game or any similar (Not Duelyst) to the compatibility list. Many of us are looking to play **TCGS** Games like **ES: Legends** or **Hearthstone**.

**Comment by kisak-valve** [comment]
Hello @Draecal, are you asking for this game or reporting that it works for you without issues?

If it's the latter, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by thunder1410** [comment]
@Draecal  you know you can enable steam play for all titles?
Steam -> settings -> steam play -> enable steam play for all titles.
If the game works you can ask to whitelist it and create a gist with your system information.

**Comment by GriefNorth** [comment]
Works fine for me. My specs - https://gist.github.com/GriefNorth/7f4820f319fda7e45ff44c5b83c20cd0

**Comment by kisak-valve** [comment]
Because my question was not answered, this issue report is now being closed. This game is now being tracked at #1681.
