### ISSUE TITLE
Title Screen and Story Mode FMVs won't display in SoulCalibur VI through Steam Play Proton

### ISSUE THREAD

**Issue by AngelStepStyle** [ValveSoftware/Proton#3340]
# Compatibility Report
- Name of the game with compatibility issues: SoulCalibur VI
- Steam AppID of the game: 544750

## System Information
- GPU: RX 590
- Driver/LLVM version: Mesa 19.2.8
- Kernel version: 5.4
- Link to full system information report as [Gist](https://gist.github.com/): N/A
- Proton version: 4.11.10

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms:
I've been trying to get SC6 to run through Steam Play Proton on any Linux distro and so far I had no luck getting the title screen and story mode FMVs to display. Any help would be nice. =)

## Reproduction:

Run through Proton. Play the game.

**Comment by kisak-valve** [comment]
Hello @AngelStepStyle, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1780#issuecomment-567509930.
