### ISSUE TITLE
Launching Killing Floor 2 installs .NET framework everytime

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/Proton#3342]
# Compatibility Report
- Name of the game with compatibility issues: Killing Floor 2
- Steam AppID of the game: 232090

## System Information
- GPU: RX 570
- Driver/LLVM version: mesa 19.3.1
- Kernel version: Arch linux, 5.4.5
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.githubusercontent.com/jazztickets/41d42605558c161e539360335039be87/raw/fd9ed5620514275aa003d7e36fa22ce50a35b6cc/ryzen
- Proton version: 4.11-11

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When launching killing floor 2, it installs Microsoft .NET framework everytime.

## Reproduction
Launch killing floor 2

[steam-232090.log](https://github.com/ValveSoftware/Proton/files/3989899/steam-232090.log)

**Comment by kisak-valve** [comment]
Hello @jazztickets, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1328#issuecomment-568060225.
