### ISSUE TITLE
Age of Empire II Definitive Edition

### ISSUE THREAD

**Issue by 6randomize9** [ValveSoftware/Proton#3348]
# Compatibility Report
- Name of the game with compatibility issues: Age of Empire II Definitive Edition
- Steam AppID of the game: 813780

## System Information
- GPU: RTX 2080 Ti
- Driver/LLVM version:  nvidia driver 440
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 4.11-11

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @6randomize9, we're using one issue report per unofficially supported game title. Feel free to add your experience with this game to #3189.

Closing because this is a mostly empty issue report template.
