### ISSUE TITLE
World of Final Fantasy - Crashes with read access fault to 0x0 at 0x1409b111f (552700)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#335]
When starting WOFF it opens a black window before crashing with: 

> Unhandled page fault on read access to 0x00000000 at address 0x1409b111f

Log: https://gist.github.com/fureloka/b00ca9af56154de452c2dd3c3733b2d9

OS: Debian Sid
CPU: AMD FX-6100
GPU: Nvidia GTX 970
GPU Driver: Nvidia 396.51

**Comment by ghost** [comment]
This issue now depends on #306

**Comment by kisak-valve** [comment]
Hello @fureloka, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this to https://github.com/ValveSoftware/Proton/issues/306#issuecomment-416000290.
