### ISSUE TITLE
Call of Duty World at War crash with Proton 4.11.11 ( does not use DXVK because DirectX installation) 

### ISSUE THREAD

**Issue by iWeaker** [ValveSoftware/Proton#3351]
# Compatibility Report
- Name of the game with compatibility issues: Call of Duty World at War
- Steam AppID of the game: 10090

## System Information
- GPU: GTX1050
- Driver/LLVM version: NVIDIA 440.43.01
- Kernel version: 5.4.6-arch1-1
- Proton version: 4.11.11

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-10090.log](https://github.com/ValveSoftware/Proton/files/3993024/steam-10090.log)

## Symptoms 

DirectX installation causes the game not to start with the D9VK dll (DXVK 1.5 ), i use the PROTON_USE_D9VK = 1% command%, it works but in certain points crash , the first time crashing at 5 minutes, [](url) in the second attempt crashing at 20min.

**Comment by kisak-valve** [comment]
Hello @iWeaker4you, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/360#issuecomment-568304799.
