### ISSUE TITLE
Fix Esync error when launching some Steam games

### ISSUE THREAD

**Issue by Galcian79** [ValveSoftware/Proton#3361]
# Compatibility Report
- Name of the game with compatibility issues: Banished
- Steam AppID of the game: 242920

## System Information
- GPU: Geforce GTX 1060 6GB
- Driver/LLVM version: 435.21 -0ubuntu0.18.04.2
- Kernel version: 5.0.0-37 generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Galcian79/3bcf5a31da6ea5abd17257dfe6277a50
[steam-242920.log](https://github.com/ValveSoftware/Proton/files/4002796/steam-242920.log)

- Proton version: 4.21-GE-2

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 
When Launching some games Whine exits with 'File not found' error.

## Reproduction
From proton log i can find 

> 4298.365:002e:002f:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.

Disabling esync fixes that. It worked out of the box with Proton 4.20-GE-1

**Comment by folknor** [comment]
Why was this issue closed? I'm having the same problem.

**Comment by 2155507151** [comment]
same
