### ISSUE TITLE
Proton/ wine sometimes detected as wine preloader instead of game tittle

### ISSUE THREAD

**Issue by Jhackler** [ValveSoftware/Proton#3362]
When using steam play if game launches fast enough correct title shows in activities. However if not only way to get it to stop displaying wine proloader 64bit is to restart discord while game is running. adding a refresh button for miss detection or adding a delay before checking seems like it would work around this issue.

**Comment by kisak-valve** [comment]
Hello @Jhackler, can you list some games you're seeing this behavior with?

**Comment by Jhackler** [comment]
sorry I was on discord bug page and must have wound up here this is a discord bug

**Comment by kisak-valve** [comment]
Closing in favor of #1473.
