### ISSUE TITLE
No surround audio in most of the games

### ISSUE THREAD

**Issue by Loacoon1** [ValveSoftware/Proton#3363]
Surround audio seems to only work with a few games (and may requires tweaks). Others only output stereo no matter the setting.
Games tested with only stereo so far :
Borderlands GOTY
Resident Evil 5
Anno 1404

I'm using Pulse with upmixing disabled on 5.1 analog out.

**Comment by kisak-valve** [comment]
Hello @Loacoon1, we're already tracking a general surround sound issue at #1803, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1803#issuecomment-569268237.
