### ISSUE TITLE
Doom 2016 crashes to console with Vulkan renderer on Fury X with latest mesa (379720)

### ISSUE THREAD

**Issue by meowmeowfuzzyface** [ValveSoftware/Proton#338]
Using the recommended unstable Padoka drivers with a Fury X on Ubuntu 18.04.

Doom runs fine in OpenGL, but will not even launch with Vulkan.  It crashes immediately to an error console.  Game is running from an internal secondary ext4 drive.

Here is the log:

```
Configured log listener print-redirect tags
Added structured log listener print-redirect
Added structured log listener mp-cloud-gobbler
2018-08-23T19:52:43.142-04:00 LOG: Process started
Added structured log listener aws-kinesis-logger
Winsock Initialized
------ Initializing File System ------
Current search path:
    - C:/users/steamuser/Saved Games/id Software/DOOM/base/
    - Z:/media/LStorage/Steam/steamapps/common/DOOM/base/
------ File System initialized.
------ Command Line ------
 "Z:\media\LStorage\Steam\steamapps\common\DOOM\DOOMx64vk.exe" Z:\media\LStorage\Steam\steamapps\common\DOOM\DOOMx64.exe +r_renderAPI -2  +com_gameType 0 
2018-08-23T19:52:43.145-04:00 LOG: Command Line: "Z:\media\LStorage\Steam\steamapps\common\DOOM\DOOMx64vk.exe" Z:\media\LStorage\Steam\steamapps\common\DOOM\DOOMx64.exe +r_renderAPI -2  +com_gameType 0 
------ CPU Information ------
    1 CPU package, 4 physical cores, 8 logical cores
    4400 MHz    Intel CPU with MMX & SSE & SSE2 & SSE3 & SSSE3 & SSE41 & SSE42 & AVX & HTT
    32768 kB 1st level cache, 262144 kB 2nd level cache, 8388608 kB 3rd level cache
    15904 MB System Memory
initializing resource container gameresources.resources
initializing resource container gameresources.patch
idLib::SetProduction( PROD_PRODUCTION )
------- Initializing renderSystem --------
PreliminaryRenderSetup
...registered window class
-------------------------
Application Info
-------------------------
App    : DOOM - 1.0.2
Engine : idTech - 6.1.1
-------------------------
Instance Extensions
-------------------------
 + VK_KHR_surface
 + VK_KHR_win32_surface
FATAL ERROR: vkCreateDevice failed with error (VK_ERROR_FEATURE_NOT_PRESENT)
```

**Comment by kisak-valve** [comment]
Hello @meowmeowfuzzyface, can you confirm any vulkan application like `vulkaninfo` from vulkan-utils works?

**Comment by meowmeowfuzzyface** [comment]
Yes it does, here is the output:

[vulkaninfo.txt](https://github.com/ValveSoftware/Proton/files/2316604/vulkaninfo.txt)

**Comment by libcg** [comment]
Try uninstalling `vulkan-intel` package. It's probably interfering with RADV.

**Comment by kisak-valve** [comment]
Temporarily renaming intel_icd.x86_64.json to something that doesn't end in .json should have the same effect.

**Comment by meowmeowfuzzyface** [comment]
Looks like I don't have that package installed, but renaming /usr/share/vulkan/icd.d/intel_icd.x86_64.json worked!  Thanks to both.

**Comment by meowmeowfuzzyface** [comment]
@kisak-valve @libcg I thought it might be important to mention that this has fixed a bunch of other issues I was having with other games.  I guess they were all trying to use my integrated GPU for Vulkan?  Not sure if that is specific to Proton or not.

**Comment by kisak-valve** [comment]
It's not surprising that Intel/Haswell would cause you trouble since it there is only an incomplete implementation of vulkan available for that chipset.

**Comment by meowmeowfuzzyface** [comment]
But why are games trying to use the integrated GPU?  Seems like it should always default to the discrete card.

**Comment by meowmeowfuzzyface** [comment]
Just wanted to give an update on this problem.  I thought I saw something related to this issue in one of the DXVK patch notes, but it seems the workaround of renaming the Intel files is still required for me after a system update that restored those files.

**Comment by GloriousEggroll** [comment]
instead of renaming the intel icd files just specify `VK_ICD_FILENAMES=/path/to/correct/icdfile %command%` in launch options.  I do this all the time when toggling between amdgpu-pro and amdgpu/radv vulkan drivers. @kisak-valve this may need to go in the readme, unsure. Probably a better way of handling it than renaming the icd file though.

**Comment by meowmeowfuzzyface** [comment]
@GloriousEggroll Wouldn't this be necessary to put in for each game that uses DXVK?  I would rather rename the files which has a global effect.

**Comment by GloriousEggroll** [comment]
@meowmeowfuzzyface yes, or you could just launch steam with it, which has the same global effect on all programs run inside steam.
