### ISSUE TITLE
[Whitelist] Castle Crashers (204360)

### ISSUE THREAD

**Issue by romulasry** [ValveSoftware/Proton#34]
I tested Castle Crashers https://store.steampowered.com/app/204360/Castle_Crashers/ and it worked perfectly for me, including sounds, controller input, effects,etc.
    Opensuse Tumbleweed (4.18.0-1.4 x86_64)
    X.Org AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.26.0, 4.18.0-1-default, LLVM 6.0.1)
    Proton 3.7 (default configuration)

System Information from Steam https://gist.github.com/romulasry/53cee3f7d527e72762d6e9d06572d5f3

**Comment by FurretUber** [comment]
Sound has some issues to me (music distorted, popping noise as if there were underruns), otherwise it was pretty good.

https://gist.github.com/FurretUber/4b9e506475e91f64e4204555a20a0886

**Comment by FurretUber** [comment]
Apparently the sound issues aren't related to Castle Crashers, but to pulseaudio after waking the computer from hibernation. `pulseaudio -k` resolved the problem.

Castle Crashers is running very well.

**Comment by jarrard** [comment]
pulseaudio -k should probably be done at the start of any proton game launch, its a common troublemaker.

**Comment by OvermindDL1** [comment]
> pulseaudio -k should probably be done at the start of any proton game launch, its a common troublemaker.

That would be highly irritating to lose sound on everything else on the system every time you start a game though... please don't..

**Comment by FurretUber** [comment]
I only had this issue after waking from hibernation. `pulseaudio -k` on every launch seems really bad.

This pulseaudio problem is another issue, unrelated to Castle Crashers.

**Comment by Houtworm** [comment]
Works great under Arch with Nvidia 396.54

**Comment by ben914** [comment]
Works for me as well on Linux Mint 19 / Nvidia 396.54. [My steam_systeminfo.txt](https://gist.github.com/ben914/fbdb706ff3fcdb62c3999362bc226774)

**Comment by edn9** [comment]
Working perfect for me.
Arch Linux Kernel 4.18.3
Proton 3.7
bspwm 0.9.5
CPU Intel Core i3-2350m @ 4x 2.3GHz RAM 4gb GPU Intel(R) HD Graphics 3000

**Comment by RlndVt** [comment]
Works well for me, but screen doesn't stay awake (using steam controller). 

Kernel 4.18.4 w/ hid_steam blacklisted
Proton 3.7.3
Plasma 5.13.4

**Comment by 4nik4** [comment]
Can confirm that the game works without issues. I didn't test the online game tho, just local.

[System info](https://gist.github.com/AnikaErceg/6594cc0b4275a9449910585863fa1294)

**Comment by Yar4e** [comment]
Game runs perfect expect sound - sometimes it crackles. Looks like another Pulse issue..
Linux Mint 18.3, Nvidia GTX970 with 396.54, Proton 3.7.5 Beta.

**Comment by jonlap** [comment]
Runs flawlessly. [Steam info](https://gist.github.com/skry/4e2fd229ffb108d565dce6737952dd08).

**Comment by jonlap** [comment]
Also works flawlessly on my laptop. Played this game 3+ hours with gf, two controllers (Wired X360 and wireless DS4). No audio issues, nothing extra to configure, solid framerate no stutter, no crashes, just perfect. System info [here](https://gist.github.com/skry/e9a3bb71522b395a9623d3f3f0e01476).

**Comment by jomarocas** [comment]
for me working good but when i go to multiplayer it crash and later stay in black screen, ubuntu 18.04, gtx 970, fx 8350, 16 ram, proton 3.7.6 beta

**Comment by Yar4e** [comment]
After upgrade to Linux Mint 19 all audio crackles was gone. So yeah, i can confirm it's runs perfect now.

**Comment by kisak-valve** [comment]
Found in the 2018-10-05 white list update.
