### ISSUE TITLE
Multiple PopCap games: Invalid command line parameter -changedir (3620 3560 3540)

### ISSUE THREAD

**Issue by NanoSector** [ValveSoftware/Proton#340]
When launching several PopCap games using Proton, games which otherwise works perfectly in regular Wine, the following error pops up:

![screenshot_20180824_022727](https://user-images.githubusercontent.com/1280380/44558586-62626e00-a745-11e8-9685-a21c2880c620.png)

This applies to (from my testing):
* Zuma's Revenge
* Bejeweled Twist
* Peggle Nights

I suspect most modern Popcap titles will be affected.

* OS: Fedora 28
* CPU: Intel Core i5 6400
* GPU: Radeon RX580

**Comment by NanoSector** [comment]
This does not appear to affect older popcap titles like Bejeweled (2), Zuma, Peggle, Insaniquarium, Big Money, Astropop, and others I missed. In fact I think those are candidates for a whitelist.

**Comment by parkerlreed** [comment]
Also Bejeweled 3 runs fine.

**Comment by NanoSector** [comment]
I've made a list of working games in https://github.com/ValveSoftware/Proton/issues/331#issuecomment-415618214
Figured that'd be more appropriate.

**Comment by derram** [comment]
You might be able to get them working by adding -changedir to the launch options.

Works for Plants Vs Zombies, at least.

**Comment by edoantonioco** [comment]
derram option to add -changedir to the steam launch parameter works with peggle nights. Thats probably the way to fix this error in all these popcam games.

**Comment by davidak** [comment]
Since Proton 5.0-8, at least Plants vs Zombies works out of the box.

https://www.protondb.com/app/3590

**Comment by kisak-valve** [comment]
Yes, `cmdlineappend:-changedir` now used with Proton 5.0-9 and 3540, 3560, 3580, 3590, 3620 as of this writing. Since this specific issue is resolved, let's track these games separately from now on, one game per issue report like other unofficially supported game titles.
