### ISSUE TITLE
Books dont have any text

### ISSUE THREAD

**Issue by desecaw13** [ValveSoftware/Proton#3403]
I have no clue what is going on. I haven't seen anybody talking about this at all so I'm guessing its just me. Google has failed me pls help.

![alduin is real](https://user-images.githubusercontent.com/47424966/71701093-c1e27c00-2d84-11ea-8569-222b8d89723e.jpg)

**Comment by kisak-valve** [comment]
Hello @Joe-O, please clarify which game and Proton version you're seeing this issue with. Also, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by desecaw13** [comment]
I'm using proton 4.2-9 and Skyrim Special edition.
Also, I don't have any mods but did change some stuff to the wine (I forgot what it was but could relook it up if you need that)

edit: found it
[steam-489830.log](https://github.com/ValveSoftware/Proton/files/4018182/steam-489830.log)

Thanks for responding

**Comment by kisak-valve** [comment]
Thanks, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4#issuecomment-570570379.
