### ISSUE TITLE
King's Bounty: Armored Princess crash after changing "Objects" (graphical setting) to "Low" (3170)

### ISSUE THREAD

**Issue by mikkovedru** [ValveSoftware/Proton#3412]
# Compatibility Report
- Name of the game with compatibility issues: King's Bounty: Armored Princess
- Steam AppID of the game: 3170

## System Information
Distro: Linux Mint 19.2 Tina
Kernel: 5.3.0-24-generic
GPU Driver: NVIDIA 440.44
GPU: NVIDIA GeForce GTX 650
CPU: Intel Core i7-4790K @ 4.00GHz
Proton: 4.11-11

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-3170.log](https://github.com/ValveSoftware/Proton/files/4023728/steam-3170.log)

## Symptoms 
King's Bounty: Armored Princess crashes after changing "Objects" (graphical setting) to "Low". Error message is strange:
```
Application aborted!
C:\work\skyfallen\tbm\BMRender\rmode.cpp(4045): DirectX call failed: 256, 256, code=0x80004001 (-2147467263)
```
![image](https://user-images.githubusercontent.com/2521942/71783683-0d9a5d00-2ff3-11ea-8090-a5c496f9ba6f.png)

The relevant information:
1. The Whitelist issue #1073.
2. Issue #1580. 
3. https://www.protondb.com/app/3170

- The only report with a similar sounding problem is found here: https://github.com/ValveSoftware/Proton/issues/1580#issuecomment-426546586
- Multiple reports about the same low fps (10) problem that I also encountered.
- has information about the crashes in the Tower in the first island as well as crashes in some Mines/Dungeons. I haven't encountered such problem (yet?).

## Reproduction
1. Run the game
2. Go to `Options`
3. Change `Objects` setting to `Low`
4. Press `Apply`

**Comment by kisak-valve** [comment]
Hello @mikkovedru, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1580#issuecomment-570937600.

**Comment by mikkovedru** [comment]
@kisak-valve. Thank you!
