### ISSUE TITLE
Quake Live (282440)

### ISSUE THREAD

**Issue by wfstuff** [ValveSoftware/Proton#3413]
# Whitelist Request
- Name of the game to be whitelisted: Quake Live
- Steam AppID of the game: 282440

## System Information
- GPU: GTX 960
- Driver/LLVM version: nvidia 418.56
- Distro version: Ubuntu 19.04
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 4.2-9

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.

## Issues
- [x] Although I consider the gaming experience equal to Windows there are remaining issues:
After about 1 hour of uninterrupted gameplay the game sometimes exits without any warning or message. Restarting the game after about 1 hour of gameplay prevents this.

**Comment by kisak-valve** [comment]
Hello @wfstuff, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3406#issuecomment-570948147.
