### ISSUE TITLE
FlatOut 4: Total Insanity (402130)

### ISSUE THREAD

**Issue by R3D9477** [ValveSoftware/Proton#3419]
# Compatibility Report
- Name of the game with compatibility issues: FlatOut 4: Total Insanity
- Steam AppID of the game: 402130

## System Information
- GPU: GeForce 930MX
- Driver/LLVM version: nvidia 440.44
- Kernel version: 5.0.0-37-generic 40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Link to full system information report as [Gist](https://gist.github.com/r3d9u11/a08548e24f4cf17b8878868e4b90f0a1#file-flatout4_20200109)
- Proton version: 4.11-11

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-402130.log](https://github.com/ValveSoftware/Proton/files/4042446/steam-402130.log)

## Symptoms 
Can't launch the game

## Reproduction
Just install an run

**Comment by kisak-valve** [comment]
Hello @r3d9u11, please retest with no PROTON_* env variables. `PROTON_NO_D3D11` has lead to `err:module:import_dll Library d3d11.dll (which is needed by L"Z:\\mnt\\hdd-data\\Software\\SteamLibrary\\steamapps\\common\\FlatOut 4 Total Insanity\\Flatout.exe") not found` in the log.

**Comment by R3D9477** [comment]
@kisak-valve Hello.
What do you mean?
I have no any extra variables in my system:
```
$ env | grep PROTON_NO
$
```
or you are talking about variables somewhere in Steam's config?

**Comment by kisak-valve** [comment]
At the top of your proton log `Options: {'d9vk', 'nofsync', 'noesync', 'nod3d11', 'wined3d'}` indicates several config options were turned on with this game. This can be done in [a couple places](https://github.com/ValveSoftware/Proton#runtime-config-options) and the blocking option is `nod3d11`.

**Comment by R3D9477** [comment]
@kisak-valve Many thanks for hint and advice!
It really works!!!
