### ISSUE TITLE
Serious Sam 2 (204340)

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/Proton#3420]
# Whitelist Request
- Name of the game to be whitelisted: Serious Sam 2
- Steam AppID of the game: 204340

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 440.44
- Distro version: Fedora 31
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Newbytee/f7d7d977d3cf23bead0a61a06270a732
- Proton version: 4.11-11

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient. (however it runs significantly better with PROTON_USE_D9VK set to 1)
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [ ] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [X] Although I consider the gaming experience equal to Windows there are remaining issues:

There is still this issue: https://github.com/ValveSoftware/Proton/issues/1081, however I don't see it as very significant any more due to that using D9VK results in excellent performance (2 to 3 times the performance of WineD3D) in my experience. In addition to this, from what I can tell there is no in-game method of switching from DirectX 9 to OpenGL.

For what it's worth, here's the log I get when trying to launch the OpenGL mode by setting gfx_iAPI to 1 in Sam2.ini: [steam-204340.log](https://github.com/ValveSoftware/Proton/files/4045065/steam-204340.log)

**Comment by kisak-valve** [comment]
Hello @Newbytee, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1081#issuecomment-573034818.
