### ISSUE TITLE
Divinity Original Sin Crash on Launch | Arch

### ISSUE THREAD

**Issue by lo4952** [ValveSoftware/Proton#3421]
# Compatibility Report
Divinity: Original Sin 2
435150

## System Information
- GPU: GTX 1060 6GB
- Graphics Driver: nvidia-440.44
- Kernel version: 5.4.8-arch1-1
- [Gist](https://gist.github.com/lo4952/18b6445112c4a99be49719edba5d47d6):
- Proton version: 4.11-11

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-435150.log](https://github.com/ValveSoftware/Proton/files/4048696/steam-435150.log)

## Symptoms 
DOS2 crashes on boot, shows status as "Launching" for a few seconds and then back to "Play"

## Reproduction
Launching DOS2

**Comment by kisak-valve** [comment]
Hello @lo4952, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/413#issuecomment-573256304.
