### ISSUE TITLE
Unreal Tournament 3 (13210)

### ISSUE THREAD

**Issue by BloodyIron** [ValveSoftware/Proton#3422]
# Compatibility Report
- Unreal Tournament 3 Black
- Steam AppID 13210

## System Information
- GPU: RX 580
- Driver/LLVM version: mesa-va-drivers/eoan,now 19.2.1-1ubuntu1 amd64
- Kernel version: 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18
- Proton version: 4.2-9 & 4.11-11
- CPU: Ryzen 5 2600

FPS for the game is utter crap considering how beefy my computer is and how old the engine is. It's a DirectX9 game and I get 30-45 FPS, when I should be pulling well over 300-450FPS. It also forges my graphical detail settings (apart from resolution) each time I launch the game. Game also encounters stuttering as if it is a frame time issue frequently. Completely terrible performance. Bioshock Infinite (written on the exact same engine) gives me way more FPS on much higher detail settings.

**Comment by kisak-valve** [comment]
Hello @BloodyIron, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2628#issuecomment-573318091.

**Comment by BloodyIron** [comment]
Oops sorry about that. Looked it up and didn't initially see which one I should post in. Thanks for your help though! :)
