### ISSUE TITLE
Resident Evil 2 Remake Crashes Constantly on Arch-Based Systems

### ISSUE THREAD

**Issue by gardotd426** [ValveSoftware/Proton#3425]
# Compatibility Report
- Name of the game with compatibility issues: Resident Evil 2 Remake
- Steam AppID of the game: 883710

## System Information
- GPU:  XFX RX 580 4GB
- Driver/LLVM version:  Mesa-ACO from valveaur (20.0.0.devel) 
- Kernel version:  Multiple. 5.4.3-5.4.10-MANJARO and -arch, 5.5rc kernels, custom kernels from Tk-Glitch, all of them. 
- Link to full system information report as [Gist](https://gist.github.com/gardotd426/f895070c431b9cea05ecf642511ac516):
- Proton version: Multiple, but as far as official versions, 4.11-11

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 
The game crashes within 10-15 minutes of actual in-game gameplay time, no matter what. YES, THE MEDIA FOUNDATION FIX IS INSTALLED. I have like 8 or 9 hours in the game, but I didn't play it for about 3 weeks or so, and now since I've tried to start back up again, I can't play for more than 10 minutes. It was never a problem with 4.11-9. Honestly it keeps getting worse, now I can't even get it to run for 5 minutes. I'm installing Proton-4.2-9 right now to see if that makes any difference, since all the versions of Proton I've tried are either 4.11 or based on 4.11 (like Glorious Eggroll's Proton-GE).

## Reproduction
On Manjaro or Arch Linux, with the current 5.4 kernel (5.4.10 as of this writing), install RE2, then after applying the Media Foundation fix, try running the game. It will crash within 10 minutes in the middle of the game. It's not cutscenes, those are fine. It'll just be in the middle of the game, running down the hall or anything like that. It just shuts down/exits, and the logs don't seem to indicate anything other than a problem with Wine. 
[steam-883710.log](https://github.com/ValveSoftware/Proton/files/4050831/steam-883710.log)

**Comment by kisak-valve** [comment]
Hello @gardotd426, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2266#issuecomment-573438301.
