### ISSUE TITLE
Ni no Kuni Wrath of the White Witch Remastered (798460)

### ISSUE THREAD

**Issue by DevStorage** [ValveSoftware/Proton#3430]
# Compatibility Report
- Name of the game with compatibility issues: Ni no Kuni Wrath of the White Witch Remastered
- Steam AppID of the game: https://steamdb.info/app/798460/

## System Information
- GPU: vega 8(raven, ryzen 5 2500u)
- Driver/LLVM version: 4.5 Mesa 19.3.1
- Kernel version: 5.5.0-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/DevStorage/805c086ff67a5af4d3699ed53d06424d
- Proton version: 4.11-11

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-798460.log](https://github.com/ValveSoftware/Proton/files/4057945/steam-798460.log)

## Symptoms 
Game starts, but freeze and stay as icon in tray, no sound\graphics at all, can't fullscreen or windowed. Tried to start with PROTON_USE_D9VK, PROTON_NO_FSYNC, PROTON_USE_WINED3D, but no luck, the same behavior. 

## Reproduction
Force to use Proton 4.11-11, or any Proton version - tested all available in options with same results including Proton 4.11-11, 4.2-9, 3.16-9, 3.7-8.

**Comment by shoober420** [comment]
# Compatibility Report
- Name of the game with compatibility issues: Ni no Kuni Wrath of the White Witch™ Remastered
- Steam AppID of the game: https://steamdb.info/app/798460/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.44
- Kernel version: 5.4.15
- https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341
- Proton version: 4.11-12

LOG:
[steam-798460.log](https://github.com/ValveSoftware/Proton/files/4125742/steam-798460.log)


## Symptoms
Nothing happens, it just crashes after launching

**Comment by shoober420** [comment]
# Compatibility Report
- Name of the game with compatibility issues: Ni no Kuni Wrath of the White Witch™ Remastered
- Steam AppID of the game: https://steamdb.info/app/798460/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.64
- Kernel version: 5.5.7-zen
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia
- Proton version: 5.0-3

LOG:
[steam-798460.log](https://github.com/ValveSoftware/Proton/files/4272926/steam-798460.log)

## Symptoms
Crashes after BANDAI NAMCO Entertainment screen.

**Comment by kisak-valve** [comment]
@shoober420 your log has the same FAudio issue as your comment on Wolfenstein: The New Order.

**Comment by shoober420** [comment]
Upon rebooting and starting a clean slate, I still crash in the same spot.

LOG:
[steam-798460.log](https://github.com/ValveSoftware/Proton/files/4279373/steam-798460.log)

**Comment by Shin-Aska** [comment]
How do you guys even manage to get it running? Mine is always stuck on the tray and I can't even manage to get into the BANDAI NAMCO logo. Here is my Debug log

[steam-798460.log](https://github.com/ValveSoftware/Proton/files/4302928/steam-798460.log)

**Comment by DevStorage** [comment]
> How do you guys even manage to get it running? Mine is always stuck on the tray and I can't even manage to get into the BANDAI NAMCO logo. Here is my Debug log
> 
> [steam-798460.log](https://github.com/ValveSoftware/Proton/files/4302928/steam-798460.log)

we don't :( dunno what to do, still experiencing the same behavior with staying at the tray.

**Comment by Shin-Aska** [comment]
Sad, because I have seen reports of people do being able to play it. Probably false reports? or somethings missing with our setup?

**Comment by DevStorage** [comment]
Any news?

**Comment by trytonlux** [comment]
### System Information

GPU: AMD RX 5700 XT
Driver/LLVM version: Mesa 20.0.5-1
Kernel version: 5.6.7
Distro: Arch Linux
Proton version: 5.0-6

---

I've been playing Ni No Kuni and was able to launch the game. I currently have about 20 hours, and haven't had any issues so far.

**Comment by DevStorage** [comment]
Still can't play, even with new proton. Stacked at the tray, that's all :(

**Comment by Shin-Aska** [comment]
@tryton-vanmeer  mind sharing us a proton log of yours so I can compare?

**Comment by trytonlux** [comment]
Adding my proton log.

[steam-798460.log](https://github.com/ValveSoftware/Proton/files/4548362/steam-798460.log)

**Comment by Shin-Aska** [comment]
> Adding my proton log.
> 
> [steam-798460.log](https://github.com/ValveSoftware/Proton/files/4548362/steam-798460.log)

Thanks @tryton-vanmeer, by any chance are you using wayland and not x11?

**Comment by DevStorage** [comment]
It works. Try to delete and reinstall.

**Comment by Shin-Aska** [comment]
Just had the time to actually reinstall, and wow it works. 🥳
