### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by KonaArctic** [ValveSoftware/Proton#3431]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description: What do you want to be added? 
Instead of fiddling with the Steam client and the terminal to figure out where my `proton_dist.tar` tarball is and why it's not there;
Instead of attempting the massive journey of compiling Proton myself and running out of SSD in the process;
I suggest we have binary Proton distributions available via Github.

## Justification [optional]: Why integration in Proton instead of Wine?
```
~$ sudo apt-get install wine
```
Or at least make Proton independently downloadable!

**Comment by aeikum** [comment]
Proton isn't really useful outside of the Steam client, so I'm not sure what you're trying to get at here. If your Proton tool files are missing/corrupted for some reason, you can use the Verify Local Files feature in the Steam client to re-download them.

**Comment by mozo78** [comment]
Proton actually is very useful outside of the Steam client. One can play No Man's Sky GOG version with only Proton for example :)

**Comment by Guy1524** [comment]
@mozo78 It's better to use another tool like Lutris to set that up.

**Comment by mozo78** [comment]
Nope, I don't use Lutris. I prefer to install my games manually :)

**Comment by KonaArctic** [comment]
Okie~! I've compiled Proton!

```
~$ make deploy
~$ make redist
```

https://mega.nz/#F!LOo2zIKT!TJhklra8_zTae0s6MqJg6w
