### ISSUE TITLE
Battlefield Bad Company 2 - BFBC2 - Proton 14.11-12 - initial observations

### ISSUE THREAD

**Issue by BETLOG** [ValveSoftware/Proton#3433]
## System Information
- GPU: 
    Gigabyte Technology Co., Ltd GK106 [GeForce GTX 660]
- Driver/LLVM version: 
    NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1 
    OpenGL version string: 4.6.0 NVIDIA 435.21
    libglu1-mesa Version: 9.0.0-2.1build1
- Kernel version:
    4.15.0-74-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:
    Proton 14.11-12

- Launch Options    
    DXVK_HUD=fps,gpuload vblank_mode=1 position=top-right PROTON_LOG=1 %command%

- GPU: 
    Gigabyte Technology Co., Ltd GK106 [GeForce GTX 660]

    
- Driver/LLVM version: 
    4.6.0 NVIDIA 435.21
    libglu1-mesa 9.0.0-2.1build1

- Kernel version: 
    4.15.0-74-generic
    
- Link to full system information report as [Gist](https://gist.github.com/):
    https://gist.github.com/BETLOG/1f0d05777036289fd4b1f7aab0660e92

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-24960.log](https://github.com/ValveSoftware/Proton/files/4064979/steam-24960.log)

## Symptoms 
This is more of a general comment than a specific issue.
1) I had been using the prior 14.10.... and when I went looking for a newer version I noticed that 14.11-12 did not appear until I DE-selected the "Force the used of a specific.." checkbox, and then re-enabled

2) The mouse, general framerate, and GPU load of a small BFBC2 game today felt quite nice.
But...
3) Then the game crashed while I was flicking between rear view and in-tank view. It crashed in such a horrible way that audio looped, and screen went black. My desktop and alt-tabbing was present, but completely unuseable. I was able to ctrl-alt-F2 into a TTY, but killing steam proved to be  impossible. So I soft rebooted.
This was such an unusual experience that I promptly wrote a script to kill -9 anything wine/wineserver/steam/bfbc2 related, and bound a hotkey to it.
Then I played another game, and again it felt quite slick. As the game ended and 'your team lost' cutscene played.. the game vanished.. to desktop. Graceful, but not as expected.

NOTE: I record all games using ffmpeg. And launch BFBC2 via a script that monitors various keybinds and conveniences. So this may or may not be related, and can be included if required.

## Reproduction
I suspect something similar will happen every second round I play, and i will be reverting to the specially-installed 14.11-9rc... all too soon. Which sucks, because crashing aside 14.11-12 seems quite efficient. But the type of crashing is distasteful enough to be avoided if possible.

**Comment by BETLOG** [comment]
Strange. I just attempted to have another game, and despite again being a less populated server the mouse felt horrible, with an almost imperceptible stutter that occasionally became disturbingly obvious as the mouse lagged when moved suddenly. Very bad. 
Also I'll have to check the video ....after I re-encode the first one with seeking that was made during the first crash... but Im sure the framerate was 2/3 of the earlier 'good' game with the awful crash and the GPU running at 100% instead of 60%-ish.
Similarly, after quitting the most recent game in disgust, several minutes later I realised that my fans were still thrashing., and sure enough steam was sitting there chewing 25%+ of my cpu. As I watched it and added filters for wine/bfbc2/steam to see the list properly it magically subsided and released its resources. Quite strange.
The only thing I have done since last reboot about an hour ago was the tests required to post the system reports above... but I'll reboot again now and see if the next game is useful or not.
Very strange.

[update]
Nope, still bad mouse and frequent small pauses when I go to move the mouse suddenly.
I'm stunned that it can go from feeling so good to being total crap.

[update again]
Had a quick game with 14.11-9rc, and despite not being the smoothest ever, it's still a lot better than 14.11-12 is now. If it could go back to the way it was when I first started using it, and not crash so brutally, that would be great.

[and another game with 14.11-12..update]
Seems better, but the server was a different one and nearly empty.
As before: it's been several minutes since I quit the game and stopped recording, and yet 
/home/user/.steam/ubuntu12_32/steam -console 
is still eating 25% CPU. ie: 100% of one core. After what I guess is about 5 minutes it has subsided.
I'm also a bit suspicious of 
/bin/bash /home/user/.steam/ubuntu12_64/steamwebhelper.sh -lang=en_US -cachedir=/home/user/.steam/steam/config/htmlcache -steampid=1743 -buildid=1578700296 -steamid=0 -steamuniverse=Public -clientui=/home/user/.steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --disable-accelerated-video-decode --log-file=/home/user/.steam/steam/logs/cef_log.txt 
and how "--disable-accelerated-video-decode" might be playing with my
ffmpeg... -hwaccel cuvid ....-vcodec h264_nvenc 
video recording.

**Comment by kisak-valve** [comment]
Hello @BETLOG, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/200#issuecomment-574690457.

**Comment by BETLOG** [comment]
> Hello @BETLOG, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#200 (comment)](https://github.com/ValveSoftware/Proton/issues/200#issuecomment-574690457).

Looks like an issue graveyard, and despite the word sequencing of the my post title, it's Proton I'm commenting on, not so much BFBC2 directly. But ok, I just wanted to document the strange input and behavioral changes I was seeing :)
