### ISSUE TITLE
Tales of Vesperia: Definitive Edition (738540) stability degradation

### ISSUE THREAD

**Issue by Dvakote** [ValveSoftware/Proton#3434]
# Compatibility Report
- Name of the game with compatibility issues: Tales of Vesperia: Definitive Edition
- Steam AppID of the game: 738540

## System Information
- GPU:  Nvidia GTX 960
- Driver/LLVM version: 440.44
- Kernel version: 5.4.6-2-MANJARO
- [Link to full system information report](https://gist.github.com/Dvakote/97b902e90f44a0e8b4932a921531d853)
- Proton version: 4.11-12

## I confirm:
- [] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

I found whitelist request https://github.com/ValveSoftware/Proton/issues/2578 and would totally support it if stability problems on newest proton would be fixed.

Proton log: [steam-738540.log](https://github.com/ValveSoftware/Proton/files/4066268/steam-738540.log)

## Symptoms 
Game have become very unstable after release of proton 4.11-11. Proton 4.11-12 didn't fixed the problem either. All worked fine on 4.11-10 and there weren't any problems before update. 

I tried to launch game on proton 4.2-9 and it worked flawlessly like on 4.11-10.

## Reproduction
There are several ways to cause game crash:
1) Launch the game
2) Try to move to different location
3) Engage in combat

**Comment by kisak-valve** [comment]
Hello @Dvakote, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2578#issuecomment-574772595.
