### ISSUE TITLE
[Whitelist] The Witness (210970)

### ISSUE THREAD

**Issue by LeJimster** [ValveSoftware/Proton#344]
Really good performance, played for a few hours no real issues.

My specs https://gist.github.com/LeJimster/7751f48f10bf0082158bace47dec7430

**Comment by tingvarsson** [comment]
Confirm, works for me as well.

[SysInfo](https://gist.github.com/tingvarsson/dc2eec45ac3e1b67cc5316b61f32bd75)

**Comment by glubsy** [comment]
Doesn't work for me. Did you use `PROTON_USE_WINED3D11=1`? It only works with that command line argument for me, but terrible performance and some graphical glitches.

**Comment by LeJimster** [comment]
@glubsy do you have all the vulkan drivers installed properly?  Are their any logs in The Witness directory like.
witness64_d3d11_d3d11.log & witness64_d3d11_dxgi.log
Also post your system info from Steam (Help > System Info) and add it to a gist.

**Comment by glubsy** [comment]
Thanks I have posted in a new thread: https://github.com/ValveSoftware/Proton/issues/1228

I don't see any of these log names anywhere.

**Comment by kisak-valve** [comment]
The Witness

Issue transferred from https://github.com/ValveSoftware/Proton/issues/1228.
@glubsy posted on 2018-09-04T14:43:43:

SPECS:
[Steam system information report](https://gist.github.com/glubsy/add907528ea037938bcfe2047b9044b6)
Kernel: 4.14.67-1-lts x86_64
Desktop Env: i3 4.15
Distro: Antergos Linux (Arch Linux based)
Device: laptop System: CLEVO Mobo: P370EM
CPU:    Quad core Intel Core i7-3740QM (-MT-MCP-) 3700 MHz
Graphics:
GPU: NVIDIA GK104M [GeForce GTX 670MX]
Display Server: X.Org 1.20.1 Resolution: 1920x1080 60.02hz
OpenGL: renderer: GeForce GTX 670MX/PCIe/SSE2 
Nvidia driver version: 4.6.0 NVIDIA 396.54
Memory: 16 GB


The game fails to start. I noticed these two lines in the [Proton log](https://gist.github.com/glubsy/6a7cce767fe4923fa42456d536b8bb9b):
```
124076.437:0025:0026:err:vulkan:wine_vk_init Failed to load libvulkan.so.1.
124076.437:0025:0026:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
```

Dota2 (native, not Wine) using Vulkan work just fine though, so I think my GPU should be able to use DXVK.
Using `PROTON_USE_WINED3D11` works but the performance is terrible and some graphical glitches, obviously the OpenGL renderer is not ideal here.

Using Proton 3.7.5 beta.

**Comment by LeJimster** [comment]
@glubsy Are you sure you're running Dota with Vulkan and it's not just falling back to OpenGL?

The error log looks like you're missing something.  Make sure you have these installed:
```
vulkan-icd-loader
lib32-vulkan-icd-loader
```
and vulkaninfo (contained in the `vulkan-tools` package) is handy for verifying your Vulkan installation is working properly.

**Comment by glubsy** [comment]
Thanks! 

Indeed I was simply missing `lib32-vulkan-icd-loader`, now it works with Vulkan renderer.  No graphical glitches in water reflections either. 

Xbox 360 controller also works very well. Problem solved for me.

My only problem is my GPU temperatures going very high, but that's a common issue I've had in many games, so this is out of topic.

**Comment by Cuddlypuff** [comment]
works perfectly for me as well, using proton beta
sys info: https://gist.github.com/Cuddlypuff/a518019d119623d9a1b7552e284c1f6d

**Comment by kisak-valve** [comment]
Found in the 2018-10-05 white list update.

**Comment by sweeze** [comment]
works mostly well, but reflections in the water only flicker on occasionally, making some of the reflection based puzzles much harder

**Comment by kisak-valve** [comment]
Hello @sweeze, please open a new issue report.
