### ISSUE TITLE
7 Days to Die (EAC)

### ISSUE THREAD

**Issue by franksouza183** [ValveSoftware/Proton#3445]
# Compatibility Report
- Name of the game with compatibility issues: 7 Days to Die (especifically the Easy Anti Cheat)
- Steam AppID of the game: 251570

## System Information
- GPU: R9 380 2GB
- Driver/LLVM version: Mesa 19.3.1-1 LLVM 9.0.0-4
- Kernel version: 5.4.6-2
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/franksouza183/4264690232a78d12de8450b81c601229
- Proton version: 4.11-12

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-251570.log](https://github.com/ValveSoftware/Proton/files/4106005/steam-251570.log)

## Symptoms

The game runs well, the problem is in Easy Anti-cheat, witch doesn't allow me to connect to EAC servers.

## Reproduction

Enable proton. Run with EAC enabled, try to connect to any EAC server.

**Comment by kisak-valve** [comment]
Hello @franksouza183, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2845#issuecomment-577922429.
