### ISSUE TITLE
Crysis 1 not Launching via Steamplay Proton

### ISSUE THREAD

**Issue by mukildev** [ValveSoftware/Proton#3450]
# Compatibility Report
- Name of the game with compatibility issues: Crysis
- Steam AppID of the game: 17300

## System Information
- GPU: NVIDIA RTX 2070 SUPER
- Driver/LLVM version: nvidia 440.44
- Kernel version: 5.4.0-769-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/mukildev/5bb62dd9f84ddb50ba668cfe3f126ff5
- Proton version: 4.11-12

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

======================

Proton: 1578946641 proton-4.11-12

SteamGameId: 17300

Command: ['/mnt/6AB0375DB0372F47/Steam_Linux/steamapps/common/Crysis/Bin32/Crysis.exe']

Options: {'noesync'}

======================

**Comment by kisak-valve** [comment]
Hello @mukildev, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/178#issuecomment-578500507.
