### ISSUE TITLE
IL-2 Sturmovik: Battle of Kuban (629700)

### ISSUE THREAD

**Issue by mimattr** [ValveSoftware/Proton#3452]
# Compatibility Report
- Name of the game with compatibility issues: **IL-2 Sturmovik: Battle of Kuban**
- Steam AppID of the game: **629700**

## System Information
- GPU: **RTX 2060**
- Driver/LLVM version: **NVIDIA 440.48**
- Kernel version: **5.3.0-26-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **4.11-12**

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Further to #3106 it appears the various DLC for [IL-2 Sturmovik](https://store.steampowered.com/app/307960) also require **.NET 4.0** "PresentationFramework" otherwise the application will fail to launch: (Proton log)

`[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.`

## Reproduction
1. Select the title within your `Library` using the Steam client and press the `Play` button

**Comment by kisak-valve** [comment]
Hello @mimattr, I'm not seeing any indication that this DLC is using a separate game engine or would act any differently from the base game and we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3106#issuecomment-578525152.
