### ISSUE TITLE
1993 Space Machine (373480)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#3458]
# Whitelist Request
- Name of the game to be whitelisted: 1993 Space Machine
- Steam AppID of the game: https://steamdb.info/app/373480/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.44
- Distro version: Arch
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia
- Proton version: 4.11-12

Works great out of the box!

**Comment by kisak-valve** [comment]
Hello @shoober420, this game has a native linux build. Any particular reason why you're requesting a whitelist for it over the native build?

**Comment by shoober420** [comment]
@kisak-valve 
According to steamdb page, there is a Mac port, but no Linux port.

**Comment by kisak-valve** [comment]
Recheck, focusing on depot 373484.

**Comment by shoober420** [comment]
Woops, I do see now (https://steamdb.info/depot/373484/). My apologize.
