### ISSUE TITLE
Proton is installed in last selected library location and can't be moved

### ISSUE THREAD

**Issue by Sanaki** [ValveSoftware/Proton#347]
While this doesn't directly cause problems for me, when Proton is installed (by steam) it will install in the last selected steam library, whatever that may be. In my case it installed on my SSD when I would have installed it to my HDD instead, but for some people that may result in an install on a removable drive, NAS, or otherwise disadvantageous location. So far as I can tell, no mechanism currently exists to move proton to another drive (other than I assume manually).

**Comment by 2A4U** [comment]
> other than I assume manually

Correct--if you move the proton directory manually I guess you should move "appmanifest_858280.acf" too in the [Ss]teamapps directory.

Also, there should be a way to "check file integrity" of Proton.

**Comment by Sanaki** [comment]
>Correct--if you move the proton directory manually I guess you should move "appmanifest_858280.acf" too in the [Ss]teamapps directory.

I figured that would work, but my desire to test it and risk finding out proton doesn't behave like steam games is pretty limited.

> Also, there should be a way to "check file integrity" of Proton.

Hadn't considered that. Definitely a needed feature.

**Comment by Sanaki** [comment]
Closing this issue and moving it to ValveSoftware/steam-for-linux#5659, where the correct devs can address it.
