### ISSUE TITLE
Collapse (289620)

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/Proton#3474]
# Compatibility Report
- Name of the game with compatibility issues: Collapse
- Steam AppID of the game: 289620

## System Information
- GPU: RX 560
- Driver/LLVM version: Mesa 19.3.2
- Kernel version: 5.4.14
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/soredake/ed1fa30f885371dda5f331815920a3ae
- Proton version: 4.11-12

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-289620.log](https://github.com/ValveSoftware/Proton/files/4128200/steam-289620.log)

## Symptoms 
Game opens a black window for a second than closes.

**Comment by kisak-valve** [comment]
Looks like this game would benefit from support for wmvcore maturing.

**Comment by soredake** [comment]
Yes, installing wmp10 and win32 prefix with lutris makes game run.

**Comment by soredake** [comment]
Retesting with proton 5.0-2

Vanilla proton:
[steam-289620.log](https://github.com/ValveSoftware/Proton/files/4231532/steam-289620.log)

Protonfixes with wmp11:
[steam-289620.log](https://github.com/ValveSoftware/Proton/files/4231549/steam-289620.log)

Protonfixes with wmp10/win98 and win32 prefix:
Shows error
![Screenshot_20200220_173007](https://user-images.githubusercontent.com/5204968/74949671-ba476700-5406-11ea-8737-0c56eb1facb0.png)
[steam-289620.log](https://github.com/ValveSoftware/Proton/files/4231575/steam-289620.log)

Protonfixes with wmp11/winxp:
[steam-289620.log](https://github.com/ValveSoftware/Proton/files/4231616/steam-289620.log)

**Comment by soredake** [comment]
Works now with latest proton + wmp9.

**Comment by soredake** [comment]
Proton 5.13-1, game displays black window for second and crashes.

[steam-289620.log](https://github.com/ValveSoftware/Proton/files/5397270/steam-289620.log)
