### ISSUE TITLE
Cryostasis (7850)

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/Proton#3475]
# Compatibility Report
- Name of the game with compatibility issues: cryostasis
- Steam AppID of the game: 7850

## System Information
- GPU: RX 560
- Driver/LLVM version: Mesa 19.3.2
- Kernel version: 5.4.14
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/soredake/ed1fa30f885371dda5f331815920a3ae
- Proton version: 4.11-12

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-7850.log](https://github.com/ValveSoftware/Proton/files/4128254/steam-7850.log)

## Symptoms 
Game does not start.

**Comment by kisak-valve** [comment]
This looks like a line of interest from the log: `err:module:import_dll Library PhysXLoader.dll (which is needed by L"Z:\\home\\bausch\\.local\\share\\Steam\\steamapps\\common\\Cryostasis\\Cryostasis.exe") not found`

**Comment by soredake** [comment]
Installing physx does not helped, physx+win32 prefix too. Works when installed from lutris.

**Comment by soredake** [comment]
Retesting with proton 5.0-2.

Vanilla proton:
[steam-7850.log](https://github.com/ValveSoftware/Proton/files/4231455/steam-7850.log)

Protonfixes with physx:
[steam-7850.log](https://github.com/ValveSoftware/Proton/files/4231477/steam-7850.log)

Protonfixes with physx+win32 prefix:
[steam-7850.log](https://github.com/ValveSoftware/Proton/files/4231492/steam-7850.log)

**Comment by soredake** [comment]
Works now with latest proton + physx.

**Comment by soredake** [comment]
https://github.com/doitsujin/dxvk/issues/1298

**Comment by soredake** [comment]
https://bugs.winehq.org/show_bug.cgi?id=48879

**Comment by soredake** [comment]
Wine bug is fixed now, only dxvk bug is remains.
