### ISSUE TITLE
enable dxvk d3d9 support by default

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/Proton#3476]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Enable d3d9 from dxvk, it is mature enough already, hundreds of games will benefit from this.

**Comment by shoober420** [comment]
I support this change as well.

**Comment by kisak-valve** [comment]
Closing as implemented per "Direct3D 9 games will now use DXVK for rendering by default. Users without Vulkan support can return to the OpenGL-based wined3d renderer with the PROTON_USE_WINED3D configuration option." in [Proton 5.0-1](https://github.com/ValveSoftware/Proton/releases/tag/proton-5.0-1).

**Comment by soredake** [comment]
Thanks!
