### ISSUE TITLE
enable LAA by default

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/Proton#3477]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Enable LAA by default and disable for problem ones.

## Justification [optional] 
Many games will benefit from this.

## Risks [optional]
Some games might crash https://github.com/Tk-Glitch/PKGBUILDS/issues/401, but we can disable laa for them.

## References [optional] 
TKG did this
https://github.com/Tk-Glitch/PKGBUILDS/commit/b0fe54e1e3b939b3faf97d78340626cac25fb411
https://github.com/Tk-Glitch/PKGBUILDS/commit/5a694743b95586857b034129725b7ce353769ed3

**Comment by mirh** [comment]
I don't know, this seems more like a hack to workaround the bigger problem of mysteriously higher memory usage (#177 https://github.com/doitsujin/dxvk/issues/1318) than anything

**Comment by Tk-Glitch** [comment]
It most definitely is. But can this actually be fully fixed? I would assume DXVK's memory overhead reduction has its limits.

**Comment by mirh** [comment]
I mean, just this month nvidia finally fixed a big bug with that. So.. we are progressing?
It doesn't help that the number of users actually reasoning with the memory map numbers under the eyes is pretty low.

**Comment by CSahajdacny** [comment]
Well.. Borderlands: The Pre-sequel running via forced Proton still crash complaining about memory allocation error if UHD textures pack is installed, with D9VK/DXVK enabled.... With PROTON_USE_WINED3D enabled it doesn't crash, but the performance sucks!

**Comment by vinifmor** [comment]
@CSahajdacny, if you are running over a Nvidia GPU, try to disable the game vsync. It's not a rule, but one of my games was raising DxvkMemoryAllocationError because of its own vsync implementation. The sync is still done even when the setting is turned off. It makes me believe somehow for this specific game the vsync was done twice and the memory crashed.

**Comment by CSahajdacny** [comment]
> @CSahajdacny, if you are running over a Nvidia GPU, try to disable the game vsync. It's not a rule, but one of my games was raising DxvkMemoryAllocationError because of its own vsync implementation. The sync is still done even when the setting is turned off. It makes me believe somehow for this specific game the vsync was done twice and the memory crashed.

Thanks for the tip. I'm gonna try and report the result.

**Comment by soredake** [comment]
![image](https://user-images.githubusercontent.com/5204968/76403817-29710500-638e-11ea-9648-23df04175d3e.png)

**Comment by aeikum** [comment]
As you noted, the Large Address Aware flag is enabled by default beginning with Proton 5.0-4. If you find this causing issues with certain games, please let us know in the game's issue page.

You can disable forcing the LAA flag by setting `PROTON_FORCE_LARGE_ADDRESS_AWARE=0`.

**Comment by shoober420** [comment]
Awesome!
