### ISSUE TITLE
make[1]: *** No rule to make target 'dxvk', needed by 'dist'.  Stop.

### ISSUE THREAD

**Issue by amadain17** [ValveSoftware/Proton#3479]
STRIPPROG="strip" ../../Proton/wine/tools/install-sh -s server/wineserver-installed /home/mark/proton-mybuild/obj-tools64/bin/wineserver
make: Leaving directory '/home/mark/proton-mybuild/obj-wine64'
if [ "" == "" ]; then rm -rf ./dist/dist/lib64/wine/.debug; fi
if [ "" != "" ]; then make -C ./obj-wine64 STRIP="strip" INSTALL_PROGRAM_FLAGS="-s" prefix="/home/mark/proton-mybuild/obj-tools64" libdir="/home/mark/proton-mybuild/obj-tools64/lib64" dlldir="/home/mark/proton-mybuild/obj-tools64/lib64/wine" install-cross-debug; cp -a ./obj-tools64/lib64/wine/.debug ./dist/dist/lib64/wine/; fi
rm -f ./dist/dist/bin/{msiexec,notepad,regedit,regsvr32,wineboot,winecfg,wineconsole,winedbg,winefile,winemine,winepath}
rm -rf ./dist/dist/share/man/
make[1]: *** No rule to make target 'dxvk', needed by 'dist'.  Stop.
make[1]: Leaving directory '/home/mark/proton-mybuild'
../Proton/build/makefile_base.mak:17: recipe for target 'nested_make' failed
make: *** [nested_make] Error 2

system -Ubuntu 18.04.3 LTS

**Comment by aeikum** [comment]
Are your submodules up to date?  E.g. `git submodule update --init`.
