### ISSUE TITLE
Lineage 2 drop fps (373700)

### ISSUE THREAD

**Issue by guglovich** [ValveSoftware/Proton#3482]
# Compatibility Report
- Name of the game with compatibility issues: Lineage 2
- Steam AppID of the game: 373700

## System Information
- GPU: AMD RX 460 (unlocked)
- Driver/LLVM version: Mesa RADV 19.3.2-2
- Kernel version: 5.4.15-arch1-1
- Link to full system information report as  https://gist.github.com/guglovich/4b456bd51bfa44515142e35d40761a1c
- Proton version: automatic selection

## I confirm:
- [+] that I haven't found an existing compatibility report for this game.
- [+] that I have checked whether there are updates for my system available.

[l2_d3d9.log](https://github.com/ValveSoftware/Proton/files/4134329/l2_d3d9.log)

## Symptoms 
- Low fps
- Friezes, FPS drops when the camera is rotated, up to 1

I tried with the active patch DXVK_ASYNC, it seems to me that it helped, but I need more tests.

**Comment by kisak-valve** [comment]
Hello @guglovich, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2574#issuecomment-580283890.

**Comment by guglovich** [comment]
In my case, everything is fine now. Wine-staging 5.18
