### ISSUE TITLE
20XX (322110)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#3486]
# Whitelist Request
- Name of the game to be whitelisted: 20XX
- Steam AppID of the game: https://steamdb.info/app/322110/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.44
- Distro version: Arch
- https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341
- Proton version: 4.11-12

Works great out of the box.

**Comment by kisak-valve** [comment]
Hello @shoober420, this game is already whitelisted.
