### ISSUE TITLE
Anno 1404 black screen

### ISSUE THREAD

**Issue by Loacoon1** [ValveSoftware/Proton#3490]
# Compatibility Report
- Name of the game with compatibility issues: Anno 1404 Venice
- Steam AppID of the game: 33350

## System Information
- GPU: Geforce RTX 2070
- Driver/LLVM version: Nvidia 440.44
- Kernel version: 5.4.15
- Proton version: 4.11.12

[steam-33350.log](https://github.com/ValveSoftware/Proton/files/4161787/steam-33350.log)

## Symptoms : The screen remains black all the way from the start. The game seems to start correctly, the audio is ok, but the screen remains black. I used to play it without any problems, but I stopped paying it for a few weeks, and when a started it recently, this happened.
My launch command options are : PROTON_LOG=1 PROTON_USE_D9VK=1 PROTON_FORCE_LARGE_ADDRESS_AWARE=1 PROTON_NO_D3D11=1 PROTON_NO_D3D10=1 %command%
Maybe it's normal but I see some D3Dx10 lines on the log, could be the problem?!...

## Reproduction
Lauching the game .

**Comment by kisak-valve** [comment]
Hello @Loacoon1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/641#issuecomment-582593578.
