### ISSUE TITLE
Ride 345660

### ISSUE THREAD

**Issue by Reddiiiee** [ValveSoftware/Proton#3491]
# Compatibility Report
- Name of the game with compatibility issues: Ride
- Steam AppID of the game: 345660

## System Information
- GPU: AMD RX 580
- Driver/LLVM version: 
> Driver:  X.Org Radeon RX 580 Series (POLARIS10, DRM 3.23.0, 4.15.0-76-generic, LLVM 9.0.0)
> Versione dei driver: 4.5 (Compatibility Profile) Mesa 19.2.8

- Kernel version: 4.15.0-76
- Link to full system information report: https://gist.github.com/Redneckita/79c12e6b84287f65e739f3230e00c420
- Proton version: 3.7-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-345660.log](https://github.com/ValveSoftware/Proton/files/4162089/steam-345660.log)

## Symptoms
The game won't start using Proton 3.7-8, it only loads the initial screen. With Proton 4.11-12 it does not even load.
The initial setting screen doesn't recognize the display and the refresh rate, only the resolution. I tried launching it in window mode or lowering graphic details.

## Reproduction
Launch the game, click start, it does not load

**Comment by kisak-valve** [comment]
Hello @Redneckita, please verify you have vulkan driver installed for your video card with something like `apt policy mesa-vulkan-drivers mesa-vulkan-drivers:i386` and install them if they are not already.

**Comment by Reddiiiee** [comment]
It worked! You made my day, thanks a lot!
