### ISSUE TITLE
Lego Jurassic World (352400): stopped working after Proton 4.2

### ISSUE THREAD

**Issue by brauliobo** [ValveSoftware/Proton#3494]
# Compatibility Report
- Name of the game with compatibility issues: Lego Jurassic World
- Steam AppID of the game: 352400

## System Information
- GPU: RX 590
- Driver/LLVM version: mesa 19.3.3
- Kernel version: 5.5.1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.0 or 4.11 don't work, 4.2 works

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Don't launch on Proton 5.0 or 4.11

## Reproduction
Select Proton 5.0 or 4.11 and try to launch game. Works fine with Proton 4.2

**Comment by kisak-valve** [comment]
Hello @brauliobo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1143#issuecomment-583668643.
