### ISSUE TITLE
Launchers have a transparent window

### ISSUE THREAD

**Issue by Linubuser** [ValveSoftware/Proton#3495]
# Compatibility Report
- Name of the game with compatibility issues: The elder scrolls online
- Steam AppID of the game: 306130

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Reproduction
Launch any application having a launcher using 5.0-1
![Windows over transparent window](https://user-images.githubusercontent.com/38225213/74085562-0928f000-4a48-11ea-8081-510d1b905b5b.png)

**Comment by maboleth** [comment]
I have this too as well, same issue, past Proton v4.11 version didn't have this.

Arch Linux, latest Gnome.

**Comment by hopafoot** [comment]
What shows up in the log file?

**Comment by Linubuser** [comment]
Here is log file.
[steam-306130.log](https://github.com/ValveSoftware/Proton/files/4186755/steam-306130.log)

**Comment by Linubuser** [comment]
Problem is fixed with 5.0-3
