### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by KonaArctic** [ValveSoftware/Proton#3499]
The latest release (proton-5.0-1) does not compile.

With this error message
```
Unable to find image 'steam-proton-dev32:latest' locally
docker: Error response from daemon: pull access denied for steam-proton-dev32, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

[Last few lines of terminal output](https://akona.me/media/proton-build.log)

Thanks!

**Comment by kisak-valve** [comment]
Hello @ArcticKona, this is a repeat of your previous issue report at #3264, so I've transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3264#issuecomment-559351946.

Closing as a duplicate.

**Comment by KonaArctic** [comment]
Oops. Sorry. 

Thanks
