### ISSUE TITLE
Winetricks/Protontricks GUI doesn't work with Proton 5.0-1

### ISSUE THREAD

**Issue by NoXPhasma** [ValveSoftware/Proton#3500]
## System Information
- GPU: GTX 1080
- Driver/LLVM version: nvidia 440.59
- Distro version: Manjaro Linux
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/NoXPhasma/84f31bd65a2c939f9dfbe609cb661307
- Proton version: 5.0-1

With Proton 5.0-1 the GUI of WInetricks won't open. It always exits with a symbol loopup error in libsoup:

```
$ winetricks --version
20191224 - sha256sum: afe039a7d72553cb761f0367f9f2085b92af8caf86e025c34bbc1fdd89a1f9ee

$ protontricks 244850 --gui
zenity: symbol lookup error: /usr/lib/libsoup-2.4.so.1: undefined symbol: g_file_info_get_modification_date_time
winetricks GUI enabled, using zenity 
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
zenity: symbol lookup error: /usr/lib/libsoup-2.4.so.1: undefined symbol: g_file_info_get_modification_date_time
Using winetricks 20191224 - sha256sum: afe039a7d72553cb761f0367f9f2085b92af8caf86e025c34bbc1fdd89a1f9ee with wine-5.0 and WINEARCH=win64
zenity: symbol lookup error: /usr/lib/libsoup-2.4.so.1: undefined symbol: g_file_info_get_modification_date_time
winetricks GUI enabled, using zenity 
zenity: symbol lookup error: /usr/lib/libsoup-2.4.so.1: undefined symbol: g_file_info_get_modification_date_time
```

With any older Proton version this is no issue.

**Comment by Newbytee** [comment]
Works for me both with a Wineprefix created by Proton 5.0 and one upgraded from 4.11 to 5.0. 

```
$ winetricks --version
winetricks 20191224 - sha256sum: 143d8b4ce5c86758724b6d9551aef03a7c6a3f0731fb273084d98312e05b1468

$ protontricks --version
protontricks (1.3.1)
```

**Comment by ghost** [comment]
I recently had a file conflict with system updates that caused Steam to stop working with a file that should not even have existed where it was. Brief research shows one possibility for this error is conflict so you could make sure libsoup-2.4.so.1 has no conflicting duplicates.

On my system there's only these which are correct:
/usr/lib/libsoup-2.4.so.1
/usr/lib64/libsoup-2.4.so.1

If you have any others then the others with only that exact name should be incorrect.

There are other possible reasons though. Proton isn't necessarily at fault.

**Comment by NoXPhasma** [comment]
I have only this ones:
```
/usr/lib/libsoup-2.4.so
/usr/lib/libsoup-2.4.so.1
/usr/lib/libsoup-2.4.so.1.8.0
```

**Comment by aeikum** [comment]
I would guess your system zenity is trying to use Proton's glib instead of your system's. The fix is probably something like protontricks should empty LD_LIBRARY_PATH before invoking zenity.

**Comment by NoXPhasma** [comment]
@aeikum I tested is with plain winetricks and that GUI works, so you seem to be right. I'll close this issue and open a new one at protontricks repository.
