### ISSUE TITLE
Transformers: Devastation (338930)

### ISSUE THREAD

**Issue by Galcian79** [ValveSoftware/Proton#3501]
The only hint i found in the log is this:

`Assertion 'pa_atomic_load(&(c)->_ref) >= 1' failed at ../pulseaudio/src/pulse/context.c:1055, function pa_context_disconnect(). Aborting.`

I managed to launch it on Lutris once and it worked fine except there was no audio during animated cutscenes. So i suspect this is definitely an issue concerning pulse audio.
[steam-338930.log](https://github.com/ValveSoftware/Proton/files/4175301/steam-338930.log)

**Comment by kisak-valve** [comment]
Hello @Galcian79, you might get lucky trying `PROTON_FORCE_LARGE_ADDRESS_AWARE=1 %command%` in the game's launch options.

**Comment by Galcian79** [comment]
> PROTON_FORCE_LARGE_ADDRESS_AWARE=1

Worked like a charm! Thank you, you saved my life!
