### ISSUE TITLE
Not properly detecting input from pedals anymore. PROJECT CARS

### ISSUE THREAD

**Issue by Lepidos** [ValveSoftware/Proton#3507]
# Compatibility Report
- GAME: PROJECT CARS
- steamappid: 234630

## System Information
 - Proton version: 5.0-1

## Symptoms 
Using Logitech G29, game detects multiple inputs pressing pedals. Cannot properly assign throttle or brake. 
Wheel and pedals inputs are correctly detected with previous Proton versions.

**Comment by kisak-valve** [comment]
Hello @Lepidos, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/244#issuecomment-583869143.
