### ISSUE TITLE
Secret World Legends not detects video card on proton 5.0-1

### ISSUE THREAD

**Issue by Peter82kr** [ValveSoftware/Proton#3510]
Linux manjaro 18.1.5,nvidia rtx 2060,drivers nvidia 440.59
Game works very good on proton 4.11-12 but on 5.0-1 wont detect videocard on launcher start.
With option: PROTON_USE_WINED3D i have graphic bugs and very low fps.On proton 4.11-12 no need to use launch parameters.

**Comment by kisak-valve** [comment]
Hello @Peter82kr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1511#issuecomment-583912406.
