### ISSUE TITLE
Unable to disable nvapiHack

### ISSUE THREAD

**Issue by Zorrototo** [ValveSoftware/Proton#3512]
I would like to have my Nvidia card reported as a Nvidia card for some specific games, and I can't find the proper way to do that.

I tried by creating a dxvk.conf file in my home directory, with the content 'dxgi.nvapiHack = False' and adding the startup parameter DXVK_CONFIG_FILE= to indicate to use this file.
I can confirm that it sees the dxvk.conf file from my home directory, and that it reads the setting dxgi.nvapiHack=false properly as it is reported in Proton log, but in game, the nvidia specific settings are still unavailable like if the card was still reported as an AMD card.

How can I make my nvidia card reported as nvidia instead of AMD in Proton?

**Comment by aeikum** [comment]
What game do you see this problem with?

**Comment by Zorrototo** [comment]
I'm not sure this is a problem, if you're talking about my Nvidia card reported as an AMD card, Proton is intended to work like this since version 3.14-something, all Nvidia cards are reported as AMD card to avoid some issues in some games especially Unreal Engine 4 games. I just want to revert this for a specific game, Killing Floor 2, to be able to enable FLEX in game.

I could use the [modified Proton version from Glorious Eggroll](https://github.com/GloriousEggroll/proton-ge-custom/releases) in which FLEX works in Killing Floor 2, but with his modified version old Proton issues come back in Killing Floor 2, like the instant crash if someone in game use the voice chat. 

So I would like to report my video card as an Nvidia card for Killing Floor 2 to be able to enable Nvidia FLEX in game settings, which is not possible if Proton reports my card as an AMD card.

Only solution I found was using a dxvk.conf file to try to disable the nvapiHack, I also tried to directly report my card vendor and model in the dxvk.conf file with 'dxgi.customDeviceId = 1c03' and 'dxgi.customVendorId = 10de', I see the settings are properly parsed in Proton log, but the result is the same as if I didn't have the dxvk.conf file, so I'm stuck and don't know what to do to make Proton see my card as an Nvidia card.

**Comment by Zorrototo** [comment]
And now I don't get it, I switch back to the Glorious Eggroll modified Proton in Steam, but I don't have FLEX anymore in menu, tried with clean  fresh prefix too.. same result, what the hell happened?! I don't understand, it was working 100% a few days ago, I even took screenshots you can see the FLEX blood and gibs https://steamcommunity.com/sharedfiles/filedetails/?id=1991511749 and now I can't even have it to work anymore on this modified Proton.
Only thing I can think of, is that I enabled then disable the Steam Shader Precaching in Steam settings, I updated my system which had a video driver update too.. but I don't understand that shouldn't have made impossible to have FLEX with the Glorious Eggroll Proton, it was working before and it is still the same version I used before which is installed in my Steam.

**Comment by aeikum** [comment]
I can't explain how Flex worked before, but I'm not surprised it doesn't work. It probably requires special Nvidia driver support, which we don't currently map to the Linux drivers.

**Comment by Zorrototo** [comment]
That's what I'm saying to myself, this was probably more an unexplainable bug I can't reproduce rather than intended behavior, because as far as I understand, Glorious Eggroll applies all the Proton patches + more patch from other sources so I don't know.. I will close the issue for now.. It was fun when it was working.

**Comment by aeikum** [comment]
I did notice the Flex DLLs that the game ships depend on nvidia's CUDA stuff. There's some wine-staging patches floating around that enable CUDA. Maybe GE used to ship that and stopped? I don't know, just a stab in the dark.

**Comment by Zorrototo** [comment]
Maybe, but then, why the 'Flex working' version I kept in my Steam (so this one didn't change at all) stopped working, I don't understand.
I guess it is most likely something that changed on my system that broke this working feature between my tests.

Thanks for you inputs even if I still don't get it yet :D
