### ISSUE TITLE
Just Cause 3 does not save game progress

### ISSUE THREAD

**Issue by viktorheli** [ValveSoftware/Proton#3515]
- Name of the game with compatibility issues: Just Cause 3 
- Steam AppID of the game: 225540

## System Information
- GPU: GeForce RTX 2080Ti
- Driver/LLVM version: 440.44
- Kernel version: Ubuntu 18.04.4 LTS with kernel 5.3.18-050318-generic
- Link to full system information report: https://gist.github.com/viktorheli/92473f03448af267e141063bb1f682a8
- Proton version: 5.0-1

## Symptoms
The game starts and works fine. But the progress of the game is not saved. How to reproduce:
1. Install the game
2. Start playing before the first save
3. Quit the game.
4. Start the game again
5. The menu of the game will only “start a new game” but there is no “continue” item.

Apparently the game saves some files in:
$HOME/.steam/steamapps/compatdata/225540/pfx/drive_c/users/steamuser/My Documents /Square Enix/Just Cause 3/Saves/76561198035641064/
File creation dates and access times change after the game starts. But file uploads probably don't happen.

Proton log: https://gist.github.com/viktorheli/ebdd086ad924a0cd30197cf49cf24bd9

**Comment by kisak-valve** [comment]
Hello @viktorheli, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/682#issuecomment-584628915.
