### ISSUE TITLE
Wolcen: Lords of Mayhem. Main charter have big "Afro"

### ISSUE THREAD

**Issue by neonlight-child** [ValveSoftware/Proton#3526]
I play Wolcen: Lords of Mayhem in steamplay with proton 5.02 in xubuntu 18.04. All ok and great perfomance, but main charter have big brown ball around head, similary "Afro" hair style.
https://postimg.cc/WDpKGmzg
Today (after game update): adding glitch with lighting (sheaking effect) and downgrade perfomance. Afro, also, is here
Theme in Bug Tracker on steam community: https://steamcommunity.com/app/424370/discussions/1/3554966164230226665/?tscn=1581703802

**Comment by kisak-valve** [comment]
Hello @neonlight-child, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/496#issuecomment-586481651.
