### ISSUE TITLE
Azur Lane: Crosswave

### ISSUE THREAD

**Issue by legendxpidea** [ValveSoftware/Proton#3527]
# Compatibility Report
- Name of the game with compatibility issues: Azur Lane: Crosswave
- Steam AppID of the game: 1150080

## System Information
- GPU: Intel® HD Graphics 520 (Skylake GT2)
- Driver/LLVM version: 3.0 Mesa 19.2.8
- Kernel version: 5.3.0-28-generic
- Link to full system information report as https://docs.google.com/document/d/1Fs_DHhIBR4GaU-AiLV6rpDQEFU7Ro9lSK1q83bnHFjI/edit?usp=sharing
- Proton version: 5.0-2

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

Log: https://drive.google.com/drive/folders/130PPSgTzN_gkl58mlQrPhZ8gJg80W-tc?usp=sharing

## Reproduction

**Comment by kisak-valve** [comment]
Hello @legendxpidea, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3524#issuecomment-586590648.
