### ISSUE TITLE
Doom 2016 (379720) mouse lags considerably after proton 5.0+

### ISSUE THREAD

**Issue by folknor** [ValveSoftware/Proton#3529]
# Compatibility Report
- Name of the game with compatibility issues: DOOM 2016
- Steam AppID of the game:379720

## System Information
- GPU: GTX 1070
- Driver/LLVM version: nvidia 440.59
- Kernel version: 5.5.1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/folknor/7a9cf73b91df7c5fc26cbb6e8553fd4f
- Proton version: 5.0-1 and 5.0-2 (and any custom .steam/root/compatibilitytools.d built from wine sources after 5.x)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

**NOTE** The following .zip file is _not_ a ZIP file, it's a `.tar.xz` file. Github did not let me upload a .tar.xz file, and it compressed to 2mb compared to 6.5 for ZIP. I had 169mb of logs for Doom, including for custom Proton versions like https://github.com/GloriousEggroll/proton-ge-custom version 5.1 and such. The problem exists there as well.
[steam-379720.zip](https://github.com/ValveSoftware/Proton/files/4209019/steam-379720.zip)

## Symptoms 

The mouse in game, both in the menues and during play, both using OpenGL _and_ Vulkan, lags considerably. It takes me a good minute to move the mouse from one end of the screen to the other.

Mouse movement is not uniform either.

This problem does not exist using Proton 4.11-12.

**Comment by Hasshu** [comment]
Same issue here. Oddly enough, moving the mouse slowly makes the pointer move in a somewhat continuous manner.

**Comment by aboutafter** [comment]
I have this problem too! If I move the mouse very slowly it works correctly, but if I move it a bit faster (maybe a bug with mouse acceleration? although I have my acceleration profile set to flat) the FPS go to practically 0 until I stop moving the mouse. 

It's not a problem with Doom 2016 though, it's global for Proton, at least for me. 


Fedora 31 KDE with Nvidia GTX 770 driver 440.59. I have a Logitech G502.

**Comment by folknor** [comment]
This issue is fixed for me in Proton 5.0-3.

**Comment by Hasshu** [comment]
> Fix high polling rate mouse regression.

That did the trick, it seems.
