### ISSUE TITLE
Deep Rock Galactic, can't click on the menu and mouse not captured

### ISSUE THREAD

**Issue by Linko-3D** [ValveSoftware/Proton#3538]
# Compatibility Report
- Name of the game with compatibility issues: Deep Rock Galactic
- Steam AppID of the game: 548430

## System Information
- GPU: GTX 1070
- Driver/LLVM version: Nvidia 418.74
- Kernel version:4.19.0-6-amd64
- Proton version: 5.0-2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms

We can't click on the buttons of the menus, I must hover the mouse en press enter on the keyboard. When entering the game the mouse isn't captured so we can't look around and shoot.

## Reproduction

You can directly see the bug after starting the game on the menu. You must use Enter key to valide the button your are hovering. Once you enter the game the mouse is still visible like if it was on the menu, so you can't look arround. But you can use the keyboard to walk and jump.
The menus that opens in  our base for example to equip our character or select a mission aren't clickable too.

**Comment by kisak-valve** [comment]
Hello @Linko-3D, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/284#issuecomment-587113459.
