### ISSUE TITLE
Microsoft Flight Simulator X: Steam Edition very high loading times and low performance due to I/O (314160)

### ISSUE THREAD

**Issue by FurretUber** [ValveSoftware/Proton#354]
I noticed the process `mount.ntfs-3g` was using 23% of CPU all the time with the game open, making loadings slow and performance low, significantly worse than on Windows.

System specifications: https://gist.github.com/FurretUber/78c1db97e438ad915e2d6da41dbc28ca

**Comment by kisak-valve** [comment]
Hello @FurretUber, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue to https://github.com/ValveSoftware/Proton/issues/352#issuecomment-415781303.
