### ISSUE TITLE
NecroVision (7860)

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/Proton#3546]
# Compatibility Report
- Name of the game with compatibility issues: NecroVision
- Steam AppID of the game: 7860

## System Information
- GPU: RX 560
- Driver/LLVM version:  Mesa 19.3.4 LLVM 9.0.1
- Kernel version: 5.5.4-15-tkg-pds
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/soredake/ed1fa30f885371dda5f331815920a3ae
- Proton version: 5.0-2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-7860.log](https://github.com/ValveSoftware/Proton/files/4236274/steam-7860.log)

## Symptoms 
Game does not launch.

**Comment by kisak-valve** [comment]
Same hints in the log as #3545.

**Comment by soredake** [comment]
Looks like doitsujin/dxvk@c1627a1 will help.

**Comment by soredake** [comment]
Proton 5.13-6, game crashes at start.
[steam-7860.log](https://github.com/ValveSoftware/Proton/files/6172668/steam-7860.log)

**Comment by soredake** [comment]
https://bugs.winehq.org/show_bug.cgi?id=47581

**Comment by Blisto91** [comment]
I don't own this game on steam but just making a note here if anyone have trouble with the dx10 version together with dxvk.
At least for the non steam version through wine you need to install `d3dx10` with winetricks for it to work in dx10 mode.
See my original comment in the dxvk issue. https://github.com/doitsujin/dxvk/issues/2299#issuecomment-1196160307
