### ISSUE TITLE
Unity games load and then stop running

### ISSUE THREAD

**Issue by pikaotaku** [ValveSoftware/Proton#3547]
System Information: [Gist](https://gist.github.com/pikaotaku/86609fd379ff8829972acedd02a3b0f9)
OS: Arch-Linux
DE: Gnome
GPU: Radeon HD 6570
Proton Version: 5.02
Games I see the issue with: Re:Legend, Inferna

I Haven't been able to play any Unity game, in both games I tried a Unity loading window of the game appears and when it's done it disappears and the game stops running
![Screenshot from 2020-02-21 13-25-53](https://user-images.githubusercontent.com/61324970/75052257-0ac5cf80-54ae-11ea-9527-66d54f4b0796.png)
This is the log from steam: 
[steam-823950.log](https://github.com/ValveSoftware/Proton/files/4237029/steam-823950.log)
I also tried running with the launch option PROTON_USE_WINED3D=1 %command% but the same happened

**Comment by kisak-valve** [comment]
Hello @pikaotaku, your Radeon HD 6570 is a Terascale 2 generation ATi card. All Terascale cards do not support Vulkan, which is used by DXVK with DirectX 9, 10, and 11. By extension, your video card is not considered supported by Proton.

You may have some luck adding `PROTON_USE_WINED3D=1 %command%` to the game's launch options, or setting it globally somewhere to get Proton to use wine's DirectX to OpenGL render path, however, this is unsupported and expected to have performance issues.
