### ISSUE TITLE
Might & Magic: Heroes VI (48220)

### ISSUE THREAD

**Issue by xcom169** [ValveSoftware/Proton#3551]
# Compatibility Report
- Name of the game with compatibility issues: Might & Magic: Heroes VI
- Steam AppID of the game: 48220

## System Information
- GPU: RX480
- Driver/LLVM version: MESA 19.3
- Kernel version: 5.5
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/xcom169/89e720c493ac0beb686c0269e8360e0f
- Proton version: 5.0.2

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
The game freezes on the start page. It was working before with wine 4.x

## Reproduction

Install windows version Might & Magic: Heroes VI and start it with Proton 5. 
It will freeze. 

This helps on Win 10:
I recently reinstalled HoMM 6 and was having the same problem. This fix worked for me: browse to the program folder, right-click "Might & Magic Heroes VI.exe" and select Properties. Click the Compatibility tab and check "Disable fullscreen optimizations." Click OK.

**Comment by mozo78** [comment]
Open ProfileData with some text editor:


find `"<SkipOpening>false</SkipOpening>" `and change it to true.

**Comment by kisak-valve** [comment]
Hello @xcom169, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the freeze, and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by xcom169** [comment]
> Open ProfileData with some text editor:
> 
> find `"<SkipOpening>false</SkipOpening>" `and change it to true.

Sorry, but it's still not 100%.

Can I set this " Disable fullscreen optimizations." for the  .exe in Proton too?

**Comment by xcom169** [comment]
> 
> 
> Open ProfileData with some text editor:
> 
> find `"<SkipOpening>false</SkipOpening>" `and change it to true.

I think it's already patched in Proton 5.0.5.
I can play it again.

**Comment by xcom169** [comment]
I think it's already patched in Proton 5.0.5.
I can play it again.

**Comment by mozo78** [comment]
It's fixed in Wine 5.5 too.
