### ISSUE TITLE
Black Screen video codec WMF

### ISSUE THREAD

**Issue by arrowgent** [ValveSoftware/Proton#3562]
# Feature Request

## I confirm:
- [ ] that I haven't found another request for this feature.
- [ ] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

tired of this problem games using WMF codecs to play videos

when playing them with Wine/Proton the video is black
even in-game videos.

when do we get this fixed?

`<Link removed by moderator>`

ive had to replay entire games to see the video after installing the codec

**Comment by kisak-valve** [comment]
Hello @arrowgent, the workaround you linked is legally problematic and has been removed.

**Comment by ghost** [comment]
There's already an issue open for this: https://github.com/ValveSoftware/Proton/issues/1464

Its just not directed specifically at the specific wording (eg black screen). I consider this a duplicate.

https://github.com/ValveSoftware/Proton/issues/1464#issuecomment-576720313

**Comment by arrowgent** [comment]
great thanks, but the issue is still open, and the problem continues

it will be frustrating for linux proton users to see this without knowing what the problem is and then accuse proton of being garbage and it doesnt work.

if we could find a FOSS method to fix this without "infringing microsoft's petty copyrights" that would be ideal...

thanks for the link
