### ISSUE TITLE
Dying Light Won't Launch because global_opengl.mp is missing. 

### ISSUE THREAD

**Issue by gardotd426** [ValveSoftware/Proton#3563]
# Compatibility Report
Dying Light (239140)

## System Information
- GPU: RX 5600 XT
- Driver/LLVM version: Mesa 19.3.4
- Kernel version: 5.5,5.6
- Link to full system information report as [Gist](https://gist.github.com/gardotd426/ce575050f709cb67bebe78ca76ee46dc):
- Proton version: 5.0 (Vanilla), 5.2(GE and TKG)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-239140.log](https://github.com/ValveSoftware/Proton/files/4240699/steam-239140.log)

When trying to launch the game through Proton, there's just a black screen with a popup error window saying: "Materials database was not correctly initialized. Please make sure that global_*. mp files are present in Assets_XXX (platform specific) folder or in build Data folder." Upon clicking "OK" the game exits. After searching for the issue, it seems there's supposed to be a `global_opengl.mp` file or something like that in the `Data` folder for the game. There's not. Everything I've searched for online show people with this issue fixing it by renaming the incorrectly named `data` folder to `Data`, but mine is already `Data`, and those people also DID have the missing file already. I've spoke with one other person who similarly can't get the game to work in Proton and doesn't have that file. 

I know there's a native version, it runs like trash and most people can't even hardly get it to run. 

For some reason, this game has a platinum db rating (for the Windows version) but it won't launch at all and it apparently didn't install all the necessary files. Yes, I've already tried verifying the game files in Steam. 

## Reproduction
Install Dying Light
Check "Force the use of a specific Steam Play compatibility tool" and select a proton version
Wait for any necessary updates
Launch the game

**Comment by kisak-valve** [comment]
Hello @gardotd426, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2569#issuecomment-590069740.
