### ISSUE TITLE
Easy Anti-Cheat tanks games attempting to run on Linux with proton.  Please fix. 

### ISSUE THREAD

**Issue by bmirtsching** [ValveSoftware/Proton#3569]
# Compatibility Report
- Name of the game with compatibility issues:  Any game on linux using Easy Anti-Cheat software. 
- Steam AppID of the game:  Hell Let Loose;  Post-Scriptum.  Not sure where to find AppID. 

## System Information
- GPU:  GTX1030
- Driver/LLVM version: All my GPU drivers have been updated with my MSI software.  
- Kernel version: Using latest stable release of KDE Neon on Lenovo laptop, i7-6700 processor.  .  
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:  Tried all available, none will run with Easy Anti-Cheat. 

## I confirm: Yes.  I have
- [ ] that I haven't found an existing compatibility report for this game---NO, I have found many blogs and chats complaining that devs for the games and the company behind Easy Anti-Cheat are not fixing the problems for Linux gamers, ruining the games.  Essentially, the games open, but the server list for the multiplayer just doesn't populate or function.  Get a message about Easy AntiCheat not loading a system user file of some sort.  Happens with every version of Proton or Steam on Linux options available for running the games on Linux in the menu available under game properties.  
- [ ] that I have checked whether there are updates for my system available--Yes, I update my KDE system daily.  

  I don't know how to do that.

**Comment by kisak-valve** [comment]
Hello @bmirtsching, EAC issues need to be evaluated on a per game basis, and we have compatibility reports for those games at #2901, #3423.

Closing in favor of the exising compatibilty reports.
