### ISSUE TITLE
 The Elder Scrolls Online (306130)

### ISSUE THREAD

**Issue by okaluk** [ValveSoftware/Proton#3572]
# Compatibility Report
- Name of the game with compatibility issues:Elder Scrolls Online
- Steam AppID of the game:306130

## System Information
- GPU: GTX 1060
- Driver/LLVM version: nvidia 440
- Kernel version: 5.4
- Link to full system information report as [Gist](https://gist.github.com/): cant copy it
[steam-306130.log](https://github.com/ValveSoftware/Proton/files/4255142/steam-306130.log)

- Proton version: 5.0-3 / 4.2-9 / 4.11-12 / 3.7-8 / 3.16-9

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
Installation hangs at 97%~ - Installing Uninstaller
ergo i cant play at all :(

## Reproduction
at every launch of the game.

EDIT
here is my GIST System information : https://gist.github.com/manaog/2ffb1e6cdeee5cc853db88579647278f
/EDIT

**Comment by kisak-valve** [comment]
Hello @manaog, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/556#issuecomment-591410637.
