### ISSUE TITLE
No game works with Proton 5.0 with Vulkan

### ISSUE THREAD

**Issue by JacobSvenningsen** [ValveSoftware/Proton#3573]
No single game I've tried running works with Proton 5.0-3 without using the **PROTON_USE_WINED3D** environment variable. Attached are just 4 examples of games that works fine with the environment variable set, and fails in the same way without. The example games work fine with Proton 4.11, both using Vulkan and with OpenGL.

The games fail with the same symptoms, all crashing immediately upon launch, and the logs look very similar as well, all with the message "_Unhandled exception: page fault on execute access to 0x00000000_". It seems very much like the issue is the same.

I also attached my system information provided by Steam, in case this would be of assistance.

[logs.zip](https://github.com/ValveSoftware/Proton/files/4256474/logs.zip)
[SystemInformation.txt](https://github.com/ValveSoftware/Proton/files/4256475/SystemInformation.txt)

**Comment by ghost** [comment]
I was confused on that since there are native Vulkan games and the rest attempt to run via DXVK or VKD3D.

These are not native from what I can tell.

The use of Vulkan is a bit misleading. These are technically Directx games running from DXVK.

**Comment by byte1024** [comment]
Might be related to: https://github.com/doitsujin/dxvk/issues/1476

I'm just not sure if its for the black screen or crash or both. Joshua's comment on that is rather poor in my opinion. Performance is all I get from it even though its supposed to close that issue :-O

**Comment by alasky17** [comment]
@JacobSvenningsen Could you try a couple of things?  
1) Delete and redownload the Proton 5.0-3 folder. (Standard location is ~/.steam/steam/steamapps/common/Proton 5.0-3.  After deleting the folder, you can trigger the redownload by searching for Proton 5.0-3 in your library and then going to Properties -> Local Files -> Verify Integrity of Tool Files)

2) If that doesn't work, run Steam from a terminal (Exit Steam completely and then open a terminal and type "steam").  Then try launching one of those games -- a bunch of things should get spit out into the terminal if you exited Steam completely before launching from the terminal.  Please post the output from the terminal here - sometimes it will give a hint about what is happening.

**Comment by magicmyth** [comment]
I've also got the same issue of games using DXVK/D9VK now crashing with proton 5.0.*. Using Wine's OpengGL translation layer (`PROTON_USE_WINED3D=1`) works just fine.

Note I am on Ubuntu 20.04 using an RX 580 on a Intel i5 2500K.

Nothing interesting in the logs. Just the same unhandled exception page fault on read access error.

Just throwing it out there, though the Op and I both are using RX 580 and Mesa (but different versions) one thing in common with both CPU's is neither has avx2 support.

**Comment by alasky17** [comment]
@magicmyth @JacobSvenningsen 

In addition to posting the output of running Steam in a terminal and attempting to launch a game with dxvk/d9vk (see my previous comment) could you try using the dxvk version from 4.11-12(1.5.1) to confirm that it is not a regression there? 

You can try the older dxvk/d9vk with Proton 5.0-3 by:
1) Download the dxvk tarball: https://github.com/doitsujin/dxvk/releases/tag/v1.5.1
2) Untar the tarball
3) Drop all of the files into the correct locations in the Proton 5.0 dist folder (standard paths used as an example):
cp -r ~/Downloads/dxvk-1.5.1/x32/*   ~/.steam/steam/steamapps/common/Proton\ 5.0/dist/lib/wine/dxvk/.
cp -r ~/Downloads/dxvk-1.5.1/x64/* ~/.steam/steam/steamapps/common/Proton\ 5.0/dist/lib64/wine/dxvk

To reset after making changes, you can delete the dist folder and it will be automatically recreated the next time you launch a game with Proton 5.0-3.

**Comment by JacobSvenningsen** [comment]
@alasky17 Deleting proton and forcing redownloading it, didn't help. Output from steam after launching the game is attached, although none of it seems too helpful.
[steamOutput.txt](https://github.com/ValveSoftware/Proton/files/4260232/steamOutput.txt)

However, downloading the DXVK 1.5.1 tarball and replacing the dlls did make the games launch successfully again. I then tried downloading the newer tarballs, and replacing the dlls with those provided by the 1.5.2 tarball causes the crashes to reappear. So it might just be a regression from upstream DXVK

**Comment by JacobSvenningsen** [comment]
I did a bisection and found this commit https://github.com/doitsujin/dxvk/commit/252ec9406d864e64949ec60ab20fe24e1dbc6262 to be the first bad one. Recompiling the master branch after reverting that commit "fixed" the problems on my end. I'll go ahead and open an issue there

**Comment by JacobSvenningsen** [comment]
It turned out upon further inspection, that I had earlier .json files saved on my system describing what version of the Vulkan API was supported. These files were saved under /etc/vulkan/icd.d/
The files stated only version 1.0.3 of the API was supported, and I guess by default, this file was used by Proton to determine what API to use, causing some sort of incompatibility.
On my system, these files are now saved under /usr/share/vulkan/icd.d/, which was also picked up by Steam, as can be seen under the "vulkan" field in the sytemSpecification attachment. Deleting the /etc/vulkan/icd.d/ directory, fixed this issue for me.

@magicmyth check the "vulkan" field under the system information tab of Steam and see if you've got multiple entries for **libvulkan_radeon.so**. If you do, try removing the ones with the oldest api_version and restart Steam. This might just solve the problem for you too, if we do indeed have the same issue.

I guess Steam should report the newest available api_version for the loaded driver in case multiple versions are found

**Comment by magicmyth** [comment]
Well spotted JacobSvenningsen! I did indeed have icd.d copies in /etc/ with older API values. `apt-file search` shows they do not belong to any installed packages but I definitely never added those so I'm guessing an upgrade did not clean up some of the old files? I upgraded to Ubuntu 20.04 recently so it might happen because of that. I think it would be worth adding to a support FAQ to keep an eye out for outdated vulkan icd files if things start crashing. Until now I never would have thought to look out for such a thing.

**Comment by JacobSvenningsen** [comment]
Probably installed in the very early days of Vulkan support in Mesa, and then never got removed. In either case, DXVK must have failed because it thought the supported Vulkan version was older than was actually the case, so some component must have reported the wrong version somewhere. 
There must be a better way to detect the supported Vulkan version than parsing an easily-editable json file

**Comment by ghost** [comment]
> Probably installed in the very early days of Vulkan support in Mesa, and then never got removed. In either case, DXVK must have failed because it thought the supported Vulkan version was older than was actually the case, so some component must have reported the wrong version somewhere.
> There must be a better way to detect the supported Vulkan version than parsing an easily-editable json file

If DXVK fails from a minimum Vulkan version then it may always need to be tested before release or crashes caught / tested on running and an error displayed about requiring a newer version or something.

I don't think checking a version via Vulkan API for example would work well here as one of the above would still need to be done since there's no way to know what the minimum can be in all cases (they would have to know ahead of time, but I don't think that's 100% possible here).

Maybe if they forced the latest version but that's another problem.

**Comment by jomarocas** [comment]
i have the same issue but with the new proton working good the games
