### ISSUE TITLE
Rome-2 doesn't work with newer proton version than 4.11-12

### ISSUE THREAD

**Issue by Sporknife** [ValveSoftware/Proton#3575]
# Compatibility Report
- Name of the game with compatibility issues: Total War: Rome 2
- Steam AppID of the game: 214950

## System Information
- GPU:rx 480
- Driver/LLVM version: LLVM 9.0.1
- Kernel version: linux-pds 5.5.6.arch.1-1
- Link to full system information report as [Gist](https://gist.github.com/RubixPower/11289cd26891d843430ca8a09f90bbc5)
- Proton version: 5.0.3

## I confirm:
- [x] that I have checked whether there are updates for my system available.
- [ ] that I haven't found an existing compatibility report for this game.
## Log file
[steam-214950.log](https://github.com/ValveSoftware/Proton/files/4263146/steam-214950.log)

## Symptoms
The launcher starts but when i launch/start the game there is the intro video and it crashes when after 1-2 seconds of the intro video.

## Reproduction
I don't know how could others reproduce this issue because some people don't have this issue according to [protondb](https://www.protondb.com/app/214950)'s Total War: Rome II report.

## Additional Info
The game run somewhat fine with proton 4.11-12 but it crashes frequently it got it somewhat fixed by installing d3dx11_42 but the game still crashes but not as many times as before.                                        
I also found a report from 2018 (Proton 3.7.5-beta) which is old and not usefull.

**Comment by kisak-valve** [comment]
Hello @RubixPower, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/512#issuecomment-592102366.
