### ISSUE TITLE
NosTale crashes on latest proton (was working before) (550470)

### ISSUE THREAD

**Issue by memegauste** [ValveSoftware/Proton#3576]
# Compatibility Report
NosTale
(550470)

## System Information
- GPU: Rx5700 XT
- Driver/LLVM version: AMDGPU 19.1.0-1
- Kernel version: 5.5.6-arch1-1
- Proton version: 5.0-3

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

https://pastebin.com/nvKTvcGS

## Symptoms
NosTale crashes on startup.

## Reproduction
Just run game, was working on Proton 4.11.

**Comment by kisak-valve** [comment]
Hello @HoshiYamazaki, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/635#issuecomment-545620701.
