### ISSUE TITLE
Mouse Issue with OpenGL - Doom (379720)

### ISSUE THREAD

**Issue by devonallie** [ValveSoftware/Proton#3578]
#### Your system information

* Steam client version (build number or date): Most Recent
* Distribution (e.g. Ubuntu): Pop_OS! 19.10
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When using OpenGL in DOOM (2016), mouse movements will cause the CPU to spike to 100%.
This issue does not exist when running in Vulkan or running OpenGL with a controller.
Running through OpenGL because vulkan causes horrible performance when streaming through remote play. 

#### Steps for reproducing this issue:

1. Launch DOOM (2016)
2. Enable OpenGL
3. Load game and move with mouse

**Comment by kisak-valve** [comment]
Hello @pr-delta, issues with games run with Proton are being tracked in Proton's issue tracker. What version of Proton are you running Doom with?

**Comment by devonallie** [comment]
Hello @kisak-valve, I thought proton was not used when running with OpenGL?

**Comment by devonallie** [comment]
So I forced the latest version of Proton, 5.0-3, and that solved the issue. Didnt realize that proton influenced OpenGL...

**Comment by kisak-valve** [comment]
Most likely a duplicate of #2440.
