### ISSUE TITLE
Katana ZERO (460950)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#3583]
# Whitelist Request
- Name of the game to be whitelisted: Katana ZERO
- Steam AppID of the game: https://steamdb.info/app/460950/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.59
- Distro version: Arch
- https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341
- Proton version: 5.0-3

LOG:
[steam-460950.log](https://github.com/ValveSoftware/Proton/files/4269971/steam-460950.log)

Works great out of the box.

**Comment by kisak-valve** [comment]
Hello @shoober420, this game is already whitelisted.

**Comment by c02y** [comment]
It is weird that I cannot open it at all.
