### ISSUE TITLE
Middle-earth™: Shadow of War™ (356190) showstopper: freezes when trying to start quest "No Man's Land"

### ISSUE THREAD

**Issue by playeronlinux** [ValveSoftware/Proton#3584]
# Compatibility Report
- Name of the game with compatibility issues: [Middle-earth™: Shadow of War™](https://store.steampowered.com/app/356190/Middleearth_Shadow_of_War/)
- Steam AppID of the game: 356190

## System Information
- GPU:NVIDIA TU116 [GeForce GTX 1660]
- Driver/LLVM version: nvidia 418.74
- Kernel version: 4.19.0-8-amd64
- Link to full system information report as [Gist](https://gist.github.com/): ask if needed
- Proton version: 4.11-12, 5.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms / Reproduction

Atart the quest "No Man's Land". A window about opening the army screen is shown ("Hold [ESC] to view the Army menu"). At this point the game freezes every time and becomes unresponsive to any input.

**Comment by kisak-valve** [comment]
Hello @playeronlinux, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/135#issuecomment-592944024.
