### ISSUE TITLE
"CreateSwapChainForHwnd: Invalid Parameter" Exception

### ISSUE THREAD

**Issue by degausser11** [ValveSoftware/Proton#3585]
# Compatibility Report
- Name of the game with compatibility issues: Path of Exile
- Steam AppID of the game: 238960

## System Information
- GPU:  Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) 
- Driver/LLVM version:   Intel Open Source Technology Center Mesa DRI 
- Kernel version:  Linux 4.19.0-8-amd64 x86_64
- Link to full system information report as [Gist](https://gist.github.com/bullfroggie/600d9d74bc68ff4e58eaa62186c01a47)
 
- Proton version: 5.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-238960.log](https://github.com/ValveSoftware/Proton/files/4270628/steam-238960.log)

## Symptoms 
![Screenshot_2020-02-29_15-12-03](https://user-images.githubusercontent.com/36682210/75612021-135a7d80-5b20-11ea-9161-49864b89253f.png)

After installing PoE and trying to run it, I'm presented with the above mentioned exception, after which the game exits.

## Reproduction
Run PoE without any launch options.

**Comment by kisak-valve** [comment]
Hello @bullfroggie, the indicators here are `"cannot-draw"` at https://gist.github.com/bullfroggie/600d9d74bc68ff4e58eaa62186c01a47#file-steam-system-information-L130 in your system information and
```
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
err:   Failed to create surface
```
in your Proton log.

Intel's vulkan support requires DRI3 is enabled to be usable.

Check with your distro's documentation on how to enable this. In general, it should be the same as https://wiki.archlinux.org/index.php/Vulkan#Error_-_vulkan:_No_DRI3_support.

Closing as this is a system config issue.
