### ISSUE TITLE
The Last Remnant (23310)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#3587]
# Whitelist Request
- Name of the game to be whitelisted: The Last Remnant
- Steam AppID of the game: https://steamdb.info/app/23310/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.59
- Distro version: Arch
- https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341
- Proton version: 5.0-3

Works great out of the box.

**Comment by kisak-valve** [comment]
Hello @shoober420, this game is already whitelisted.

**Comment by soredake** [comment]
@shoober420 https://steamdb.info/app/891390/info/
