### ISSUE TITLE
Final Fantasy III Font Problem (239120)

### ISSUE THREAD

**Issue by iWeaker** [ValveSoftware/Proton#3588]
# Compatibility Report
- Name of the game with compatibility issues: Final Fantasy III
- Steam AppID of the game: 239120

## System Information
- GPU: GTX1080
- Driver/LLVM version: 440.58.02
- Kernel version: 5.5.6-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.0-3

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

Recently Square Enix released an update that many users have problems with the fonts, especially because position font problem, but in this case it is not only that position problem in  the options box, but it also shows square figures,  I have installed Calibri, Corefonts and Gdiplus with Protontricks, and I have not made it work, I leave the link of an image of a comment that has the same problem.

https://steamuserimages-a.akamaihd.net/ugc/789757411161816589/5128F8634BF950A1EDE725501296A0EE33067F73/

I have found a temporary solution in Windows that a user managed to make, but in Wine I have done it as the image and I can't make it work, or in Wine does it work different FontReplacement?

https://steamuserimages-a.akamaihd.net/ugc/783001864313881234/E92D5E3C6F625BDABD1C4482F6B1502037B064A0/?fbclid=IwAR0dvaLHqSekxS5ixk1OvvaZtz-ryUqDJxOIL8dUItdBAq12sC5MLhRsEW4

**Comment by kisak-valve** [comment]
Hello @iWeaker4you, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/707#issuecomment-593040180.
