### ISSUE TITLE
Just Cause 3 autosave

### ISSUE THREAD

**Issue by BarrelKnight723** [ValveSoftware/Proton#3591]
I downloaded Just Cause 3 for my Linux gaming PC and while it runs like a beauty it has trouble autosaving where I basically have to start all the way from the beginning.

**Comment by kisak-valve** [comment]
Hello @CSForever07, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/682#issuecomment-593131973.
