### ISSUE TITLE
Can't play Doom 2016 (379720) on Linux Mint 19

### ISSUE THREAD

**Issue by alexei-28** [ValveSoftware/Proton#3592]
My notebook's configuration:

17.3" IPS Full HD (1920x1080) Intel Core i7-9750H (6x Core, 2.6GHz - 4.5GHz, 12Mb), 16Gb (2x 8Gb) PC4-21300, 512Gb M.2 PCIE, GeForce GTX 1650 4Gb

Game launched via compatibility tool: Steam Play
Hi
Notebook Legion Lenovo Y540,
Linux Mint 19.3

- purchase game Doom 2016 on Steam 
- download game
- set steam launch option game = +renderAPI 1
- press button Play , but the game is not started
- set proton version 5.0.3

**Comment by kisak-valve** [comment]
Hello @alexei-28, please set the game's launch options to [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) (or `PROTON_LOG=1 %command% +renderAPI 1`) and drag and drop the generated $HOME/steam-$APPID.log into the comment box. Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by alexei-28** [comment]
1. I set game's launch to 
`PROTON_LOG=1 %command%`

2. Not found file $HOME/steam-$APPID.log 

3.  my system info
https://gist.github.com/alexei-28/27c39912f966e4720ae1a4b7a192d117

**Comment by kisak-valve** [comment]
If no log is generated by Proton when run with `PROTON_LOG=1` set, that hints that there's an issue with the Proton install or Steam's not configured to use Proton with the game.

**Comment by alexei-28** [comment]
> If no log is generated by Proton when run with `PROTON_LOG=1` set, that hints that there's an issue with the Proton install or Steam's not configured to use Proton with the game.

So you want to say that I can't play Doom 2016 on Linux Mint 19.3? It's very bad

**Comment by WernerAUT** [comment]
no he just told you that something with your setup is wrong. Are you using the snap version of steam and if so why are you doing that in Mint?
I would remove the snap steam version and then install the normal version over the Software Manager (not flathub!! or snap!!) after that you also need to enable in Steam Settings under "Steam Play" this two settings "Enable Steam Play for supported titles" and "Enable Steam Play for all other titles" and choose Run titles with: Proton 5.0-3.

**Comment by alexei-28** [comment]
1. I remove Steam
2. Install by Software Manager - Steam (Valve's Steam digital)
3. Enable two settings "Enable Steam Play for supported titles" and "Enable Steam Play for all other titles"
4. Run titles with: Proton 5.0-3
5. Success run Doom 2016.

Thanks
