### ISSUE TITLE
Windows Defender detects Occamy.c trojan in steam proton 5.0 folder

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3593]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): arcolinux/windows 10
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes 

#### Please describe your issue in as much detail as possible:
I installed steam on arcolinux to try a game via proton the game did not work, so i reinstalled windows but i backed up my steam folder i had on linux and was in the process to copy it over to another internal backup drive since i copied it to an external backup drive initially, during the copy windows defender popped up with a "severe threat" warning with the name of Trojan:Win32/Occamy.C it found it in: D:\Steam games\steamapps\common\Proton 5.0\dist\share\wine\mono\wine-mono-4.9.4\support\installinf-x86.exe Obviously i am unsure if this is a false possitive but defender seems to think it is a severe threat. Just informing you guys. Thank you for all your work.

#### Steps for reproducing this issue:

1. install a proton game and copy it to a ntfs partition drive
2. then run a updated windows 10 and copy that linux steam folder to
![Untitled](https://user-images.githubusercontent.com/61514535/75371512-8de08e80-58cf-11ea-9b4f-74c1b0e1cf5c.png)
 another ntfs partition using windows
3.

**Comment by aeikum** [comment]
Anti-virus programs have been very snippy about our conversion to PE files. You can report it to your anti-virus vendor as a false positive.

**Comment by GitCaps** [comment]
I know this is closed but I did run into this, this morning and submitted the file and false-positive user opinion to the Microsoft Windows Defender team, and the report back is that they have concurred and 'removed this detection' from the client and cloud side. Screenshot attached.
![mono-proton-mw-submission](https://user-images.githubusercontent.com/29682736/87611898-064cbe00-c6be-11ea-9269-3894de8e78cf.PNG)
