### ISSUE TITLE
Risk of Rain 2 hangs launching indefinitely

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3595]
# Compatibility Report
- Name of the game with compatibility issues: Risk of Rain 2
- Steam AppID of the game: 632360

## System Information
- GPU: Quadro P500
- Driver/LLVM version: Nvidia 430.50
- Kernel version: 5.3.0-40-generic
- Proton version: 5.0-3, 4.2-9
[Gist here](https://gist.github.com/DoubleRHR/b57200030d2bff302df10baf877b8bab)
![Screenshot from 2020-02-28 20-47-55](https://user-images.githubusercontent.com/20192625/75739184-7a636800-5cc1-11ea-95d1-b136bb89f8d9.png)

Hi, recently my game has stopped launching at all. Usually I force it to use Proton 4.2-9, but that has just stopped working. It does not work with other versions of proton, and only started acting up once proton 5 was released. 
Occasionally a unity crash screen (attached) pops up. When Proton 4.11-2 was released I had the same issue, but fixed it by using 4.2-9 instead. The application never stops displaying as "currently running" unless I manually kill it--the game hangs indefinitely. I have verified the file integrity of the game, and have cleared the download cache. I have also tried restarting my computer, logging out of steam, and uninstalling/reinstalling the app.

**Comment by wantija** [comment]
I had this issue recently, had to re-install mesa, lib32-mesa, mesa-vulkan ect but it worked fine after that. I have an RX 580, but try re-installing/updating your Nvidia drivers? No idea what caused it.

**Comment by kisak-valve** [comment]
Hello @DoubleRHR, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2476#issuecomment-593947284.

**Comment by kylejbrk** [comment]
@wantija, can you post your exact steps? having the same issue.
