### ISSUE TITLE
Titan Quest Anniversary Edition crashes immediately without error message.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3596]
# Compatibility Report
- Name of the game with compatibility issues: Titan Quest Anniversary Edition
- Steam AppID of the game: 475150

## System Information
- GPU: AMD Ryzen 3500U
- Driver/LLVM version: AMD RAVEN (DRM 3.33.0, LLVM 9.0.0 
- Kernel version: 5.3.0-40-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.0-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms:

Game crashes immediately after I press "start" without further notice. Has been working fine a few months ago. 

## Reproduction

Just press "start" and the game attempts to launch, only to crash right back to steam.

[steam-475150.log](https://github.com/ValveSoftware/Proton/files/4282403/steam-475150.log)

**Comment by kisak-valve** [comment]
Hello @Logicisart, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/567#issuecomment-594048695.
