### ISSUE TITLE
Proton is most likely overengineering

### ISSUE THREAD

**Issue by es20490446e** [ValveSoftware/Proton#3598]
https://youtu.be/4oepBPloAYU

**Comment by kisak-valve** [comment]
Hello @es20490446e, the majority of Proton is wine under the hood. If you have an issue with individual games where they work with upstream wine, but not Proton, please give feedback on the compatibility report of the individual games so that we can look into them.

**Comment by es20490446e** [comment]
There should be a key difference. Also it just makes more sense to report to Wine directly, and not having an intermediate silo.
