### ISSUE TITLE
Proton can not find game executable

### ISSUE THREAD

**Issue by FamousL** [ValveSoftware/Proton#3601]
All proton versions
Any game used with proton (Below logs use Doom 2016 as the attempted program to launch)

I have the game installed on an external harddrive, the full path to the executable is correct in the below error, and is indeed present. This error is occurring when attempting to launch the game, I have verified the files, reinstalled both Doom and Proton, and rebooted more times than I believe should have been necessary.

-rwxrwxrwx 1 phil phil 76022480 Mar 3 10:58 '/run/media/phil/New Volume/Steam/steamapps/common/DOOM/DOOMx64.exe'

>>> Adding process 82985 for game ID 379720
wine: cannot find '/run/media/phil/New Volume/Steam/steamapps/common/DOOM/DOOMx64.exe'
pid 82989 != 82988, skipping destruction (fork without exec?)
>>> Adding process 82986 for game ID 379720
>>> Adding process 82988 for game ID 379720
Game removed: AppID 379720 "", ProcID 82983
Uploaded AppInterfaceStats to Steam
Exiting app 379720
No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(steam)/version(1581460722)

**Comment by ghost** [comment]
I wonder if the space in "New Volume" could be the problem?

Many times when something cannot be found when it exists, its something to do with the path, permissions being too low or too high, or some other access issue.

For example, the main Steam path on same drive has no space and a test exe has permission of -rwxr-xr-x.

I would suggest that more testing could be done. However, Valve might already know what it is.

**Comment by FamousL** [comment]
It shouldn't have been due to the single quotes, but I decided to test it out anyway by renaming the volume, and resetting the paths in steam so the library no longer has the space:

>wine: cannot find '/run/media/phil/NewVolume/Steam/steamapps/common/DOOM/DOOMx64.exe'
pid 118812 != 118811, skipping destruction (fork without exec?)
> Adding process 118809 for game ID 379720
> Adding process 118811 for game ID 379720
>Game removed: AppID 379720 "", ProcID 118806 
>Uploaded AppInterfaceStats to Steam
>Exiting app 379720

**Comment by kisak-valve** [comment]
Hello @FamousL, what distro are you using? Also, are you using Steam in an environment that would restrict its access to a secondary drives (like Flatpak)?

What filesystem are you using with `/run/media/phil/NewVolume`?

**Comment by FamousL** [comment]
Fedora 31, no this was installed through the rpmfusion repos.

The file system is ntfs

**Comment by JacobSvenningsen** [comment]
Proton has issues with NTFS partitions: https://github.com/ValveSoftware/Proton/issues/11

**Comment by ghost** [comment]
Edit: I tested this and can confirm that Steam isn't liking NTFS on Fedora 31 as expected. You would have to test external Ext4 and see if it still happens. I don't feel like doing so as my internal Linux ssd has enough space.

Like JacobSvenningsen says, I wouldn't use Steam Linux with NTFS formatted drives. You can split the drive into 2 partitions, one for NTFS, one for Ext4.

**Comment by FamousL** [comment]
Apologies for the delay, 
I am in the process of re-formatting the drive entirely, the reasons this was ntfs is no longer relevant. ext4 here i come!

Ext4 solved the issue.
