### ISSUE TITLE
DOOM (379720) won't start on Arch

### ISSUE THREAD

**Issue by Jerely** [ValveSoftware/Proton#3604]
# Compatibility Report
- Name of the game with compatibility issues: DOOM
- Steam AppID of the game: 379720

## System Information
- GPU: nvidia GTX 1060 
- Driver/LLVM version: nvidia 440.64
- Kernel version: 5.5.7-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Jerely/63f77d50b5c7c15ecd2ad9bb7d7dacf7
- Proton version: 5.0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
I'm using Arch, no matter what I do Doom 2016 just won't start. I push Play and nothing happens, Play button just becomes green again just as if I played game for 1 second and then quit except I didn't. I run vkcube and it works, so looks like Vulkan works properly. Native linux games like Portal also working perfectly. I used all available Proton versions and tried to launch a game with "+renderAPI 1" option and without it. Also I installed game on a ntfs drive mounted with ntfs-3g, so maybe that is the problem. Here is a Proton log output by the way:
> ======================
Proton: 1582148269 proton-5.0-3
SteamGameId: 379720
Command: ['/mnt/1TB/ArchLibrary/steamapps/common/DOOM/DOOMx64.exe', '+renderAPI', '1']
Options: set()
======================
ERROR: ld.so: object '/home/misha/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wineserver: /mnt/1TB/ArchLibrary/steamapps/compatdata/379720/pfx is not owned by you
ERROR: ld.so: object '/home/misha/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/misha/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
wine: /mnt/1TB/ArchLibrary/steamapps/compatdata/379720/pfx is not owned by you
## Reproduction
Described above.

**Comment by kisak-valve** [comment]
Hello @Jerely, NTFS and Proton are known to be a bit finicky. Please give https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows a read. In particular, it sounds like you need to mount the NTFS partition as your current user.

Additional reference: https://github.com/ValveSoftware/Proton/wiki/Proton-FAQ#none-of-my-games-are-launching--prefix-not-owned-by-you-error

**Comment by Jerely** [comment]
@kisak-valve thank you, that worked.
