### ISSUE TITLE
Cricket 19 game DirectX11 issue in Steam Proton

### ISSUE THREAD

**Issue by RVV55** [ValveSoftware/Proton#3605]
# Compatibility Report
- Name of the game with compatibility issues: Hey guys, I was trying to launch a game called Cricket 19 from my Zorin OS (based on Ubuntu 18.04) laptop in steam proton. But, I only got a message stating that:- No compatible graphics device found. Minimum DirectX 11 graphics device is required!. I tried lot of things, but nothing seems to work. Someone Please help me out.
- Steam AppID of the game:  1028630
## System Information
- GPU: AMD Radeon R5 M230, Intel HD Graphics 620 
- Proton version: 5.0.3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
--Hey guys, I was trying to launch a game called Cricket 19 from my Zorin OS (based on Ubuntu 18.04) laptop in steam proton. But, I only got a message stating that:- No compatible graphics device found. Minimum DirectX 11 graphics device is required!. I tried lot of things, but nothing seems to work. Someone Please help me out.
[steam-1028630.log](https://github.com/ValveSoftware/Proton/files/4299191/steam-1028630.log)
[steam-1028630.log](https://github.com/ValveSoftware/Proton/files/4299193/steam-1028630.log)
[steam-1028630.log](https://github.com/ValveSoftware/Proton/files/4299196/steam-1028630.log)
[steam-1028630.log](https://github.com/ValveSoftware/Proton/files/4299202/steam-1028630.log)

**Comment by kisak-valve** [comment]
Hello @RVV55, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2948#issuecomment-595838197.
