### ISSUE TITLE
Logitech G203 Prodigy getting hot while using Proton

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3611]
When i am playing native linux games my mouse is cold but when i start a Steam Play game like DOOM 2016 with proton 5.0-3 it starts to get hot, at some point i just have to stop playing the game to avoid damage.
It started recently.
I'm not sure of what is causing the issue.
also im using the mouse in a USB2.0 port, i'm not sure if it would happen on USB3.0.

I will comment on this bug report confirming if it happens with older versions of proton, it still requires testing so wait for updates.

**Comment by kisak-valve** [comment]
Hello @kassindornelles, this sounds like a hardware issue and not related to Proton. There's [a suggestion](https://www.reddit.com/r/MouseReview/comments/5z8603/logitech_g_pro_led_heat_issue/) that this related to the LEDs in the mouse. Try reducing the brightness of those LEDs in your mouse.

**Comment by ghost** [comment]
@kisak-valve already turned off my mouse LED's, it's funny because it only starts to get hot with Proton games, native one's the mouse remains cold :man_shrugging:

**Comment by ghost** [comment]
I'm closing the issue for now until i get some proof that proton/wine is the problem and not the hardware itself.
