### ISSUE TITLE
Tomb Raider: Legend (7000)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#3615]
# Whitelist Request
- Name of the game to be whitelisted: Tomb Raider: Legend
- Steam AppID of the game: https://steamdb.info/app/7000/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.64
- Distro version: Arch
- https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341
- Proton version: 5.0-3

LOG:
[steam-7000.log](https://github.com/ValveSoftware/Proton/files/4302835/steam-7000.log)

Works great out of the box.

**Comment by kisak-valve** [comment]
Hello @shoober420, this game is already being tracked at #371 and is a whitelist request.

If you find functional difference between these games, we can split that issue report apart, but for now let's track this in the existing whitelist request.
