### ISSUE TITLE
Web redirect not working with Proton 5

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3617]
# Problem Report
- Name of the game with compatibility issues: World of Warships (though more might be affected)
- Steam AppID of the game: 552990 (again, more might be affected)

## System Information
- GPU: GTX 1060 6GB
- Driver/LLVM version: 440.44
- Kernel version: 5.3.0-7629-generic
- Link to full system information report as [Gist](https://gist.github.com/aorozsa/d9e5d6829d7ab5212b9c9a085bd1b311):
- Proton version: 5.0-3

## I confirm:
- [N/A] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

With Proton 5.0-3: [steam-552990.zip](https://github.com/ValveSoftware/Proton/files/4304885/steam-552990.zip) (had to compress this one)
With Proton 4.11-13: [steam-552990.log](https://github.com/ValveSoftware/Proton/files/4304863/steam-552990.log)

## Symptoms 
Firstly, I modified the game to log in with my Wargaming account (fix [here](https://steamcommunity.com/sharedfiles/filedetails/?id=1890831652)). I noticed that whenever I try to click on one of the quick login buttons, the webpage doesn't open up in my browser. The game minimises, but the page doesn't open, even if my browser is already open. I tried this with 4.11-13 and it worked just fine.

I also noticed that this issue carries over to Lutris (I also play World of Tanks, and the other Wine versions just aren't as good). Like before, logging in with Proton 5 doesn't work, but it does with 4.11.

Also, Proton 5 doesn't like to work with Lutris very well in other aspects. Can we discuss that here or should I open a new issue?

## Reproduction
Trying to log in with social media accounts.

**Comment by kisak-valve** [comment]
Hello @aorozsa, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/333#issuecomment-596508687.

In general, issues with Lutris should be reported to the Lutris devs unless you find something specific and actionable by Proton devs.

**Comment by ghost** [comment]
@kisak-valve It's a problem with using Proton with Lutris, not Lutris itself. However, this issue also occurs with other later versions of wine.
