### ISSUE TITLE
Yooka-Laylee and the Impossible Lair (846870)

### ISSUE THREAD

**Issue by Zyneris** [ValveSoftware/Proton#3625]
# Whitelist Request
- Name of the game to be whitelisted: Yooka-Laylee and the Impossible Lair
- Steam AppID of the game: 846870

## System Information
- GPU:  RTX 2070 Super
- Driver/LLVM version:  4.6.0 NVidia 440.64
- Distro version:  5.5.8-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): [Link](https://gist.github.com/ZVak18/3c3d4e3828dd90045e17ccd30ae0318e)
- Proton version: 5.0.4

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Closing in favor of #3133.
