### ISSUE TITLE
Sword Art Online: Fatal Bullet (626690)

### ISSUE THREAD

**Issue by CygnusTerminal** [ValveSoftware/Proton#3626]
# Compatibility Report
- Name of the game with compatibility issues: Sword Art Online: Fatal Bullet
- Steam AppID of the game: 626690

## System Information
- GPU: RX 480
- Driver/LLVM version: Mesa 19.3.4
- Kernel version: 5.5.8-22-tkg-pds
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/rossophantasma/9e92c6fc524dd761405cad39ae4a14af
- Proton version: 5.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
[steam-626690.log](https://github.com/ValveSoftware/Proton/files/4319112/steam-626690.log)

After quitting the game from the menu, it still runs on background unless its manually killed. Otherwise, the game works fine.

## Reproduction
Open the game, exit it, open htop, search for the game executable open.

**Comment by kisak-valve** [comment]
Hello @rossophantasma, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1178#issuecomment-597706309.
