### ISSUE TITLE
Fahrenheit: Indigo Prophecy (312840)

### ISSUE THREAD

**Issue by adrianlshaw** [ValveSoftware/Proton#3628]
# Whitelist Request
- Name of the game to be whitelisted: Farenheit: Indigo Prophecy
- Steam AppID of the game: 312840

## System Information
- GPU: GTX 1060 6GB
- Driver/LLVM version: Nvidia 440
- Distro version: Ubuntu 18.04 
- Link to full system information report as [Gist](https://gist.github.com/adrianlshaw/09a3cd8be69843a6d523fb37e3b64da5/):
- Proton version: 5.0-4

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @adrianlshaw, it looks like this game has a native linux build.

Are you sure you tested this game with Proton and why should the Windows build be used with Proton instead of the native build?

**Comment by adrianlshaw** [comment]
Oh, you're right! I didn't realise it was released for Linux/SteamOS.
