### ISSUE TITLE
DoDonPachi Resurrection (464450)

### ISSUE THREAD

**Issue by iBringsTheRuckus** [ValveSoftware/Proton#3629]
# Compatibility Report
- Name of the game with compatibility issues: DoDonPachi Resurrection
- Steam AppID of the game: 464450

## System Information
- GPU: Nvidia GeForce RTX 2070 Super
- Driver/LLVM version: 440.44
- Kernel version: 5.3.0-7629-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/BigB86/decd9f171bcc03db029927396fb8e3ca
- Proton version: 5.0-4

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

https://gist.github.com/BigB86/cd69e1af00ea09d0162e15f5040af87f

## Symptoms 
I click play and a blank window pops up. It hangs for a few seconds and then closes.

## Reproduction
Install the application and click Play. I did find out that the game does not crash with proton version 4.11-13. The game was not fully tested with this version of proton.

**Comment by kisak-valve** [comment]
Hello @BigB86, can you check if setting the game's launch options to  `PROTON_USE_WINED3D=1 %command%` has an effect on the game and Proton 5.0?

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX 5700 ITX
- GPU Driver: 20.1.0-devel (git-0103f02 2020-03-07 bionic-oibaf-ppa)
- Kernel version: 5.3.18-050318-lowlatency
- Distro version: 19.3 Tricia (64 bit) (Cinnamon)
- Proton version: 5.0-4

**Compatibility Report**

@kisak-valve I'm seeing the same issue with Proton 5.0-4. Game launches to a black window and then closes, with launch option "PROTON_USE_WINED3D=1 %command%" game worked without issue.

Also tried older Proton 4.11-13 and it worked without having to set a WINED3D launch option.

[steam-464450-proton-4.11-13.log.zip](https://github.com/ValveSoftware/Proton/files/4321737/steam-464450-proton-4.11-13.log.zip)
[steam-464450-proton-5.0-4.log.zip](https://github.com/ValveSoftware/Proton/files/4321738/steam-464450-proton-5.0-4.log.zip)
[steam-464450-proton-5.0-4-WINED3D.log.zip](https://github.com/ValveSoftware/Proton/files/4321739/steam-464450-proton-5.0-4-WINED3D.log.zip)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/4321740/system_info.txt)

**Comment by iBringsTheRuckus** [comment]
> Hello @BigB86, can you check if setting the game's launch options to `PROTON_USE_WINED3D=1 %command%` has an effect on the game and Proton 5.0?

It does indeed launch without crashing! Was this something I did wrong or failed to do in the first place?

> **System Information**
> 
>     * GPU: RX 5700 ITX
> 
>     * GPU Driver: 20.1.0-devel (git-0103f02 2020-03-07 bionic-oibaf-ppa)
> 
>     * Kernel version: 5.3.18-050318-lowlatency
> 
>     * Distro version: 19.3 Tricia (64 bit) (Cinnamon)
> 
>     * Proton version: 5.0-4
> 
> 
> **Compatibility Report**
> 
> @kisak-valve I'm seeing the same issue with Proton 5.0-4. Game launches to a black window and then closes, with launch option "PROTON_USE_WINED3D=1 %command%" game worked without issue.
> 
> Also tried older Proton 4.11-13 and it worked without having to set a WINED3D launch option.
> 
> [steam-464450-proton-4.11-13.log.zip](https://github.com/ValveSoftware/Proton/files/4321737/steam-464450-proton-4.11-13.log.zip)
> [steam-464450-proton-5.0-4.log.zip](https://github.com/ValveSoftware/Proton/files/4321738/steam-464450-proton-5.0-4.log.zip)
> [steam-464450-proton-5.0-4-WINED3D.log.zip](https://github.com/ValveSoftware/Proton/files/4321739/steam-464450-proton-5.0-4-WINED3D.log.zip)
> [system_info.txt](https://github.com/ValveSoftware/Proton/files/4321740/system_info.txt)

Glad you confirmed it as well!

**Comment by BigB86** [comment]
> **System Information**
> 
>     * GPU: RX 5700 ITX
> 
>     * GPU Driver: 20.1.0-devel (git-0103f02 2020-03-07 bionic-oibaf-ppa)
> 
>     * Kernel version: 5.3.18-050318-lowlatency
> 
>     * Distro version: 19.3 Tricia (64 bit) (Cinnamon)
> 
>     * Proton version: 5.0-4
> 
> 
> **Compatibility Report**
> 
> @kisak-valve I'm seeing the same issue with Proton 5.0-4. Game launches to a black window and then closes, with launch option "PROTON_USE_WINED3D=1 %command%" game worked without issue.
> 
> Also tried older Proton 4.11-13 and it worked without having to set a WINED3D launch option.
> 
> [steam-464450-proton-4.11-13.log.zip](https://github.com/ValveSoftware/Proton/files/4321737/steam-464450-proton-4.11-13.log.zip)
> [steam-464450-proton-5.0-4.log.zip](https://github.com/ValveSoftware/Proton/files/4321738/steam-464450-proton-5.0-4.log.zip)
> [steam-464450-proton-5.0-4-WINED3D.log.zip](https://github.com/ValveSoftware/Proton/files/4321739/steam-464450-proton-5.0-4-WINED3D.log.zip)
> [system_info.txt](https://github.com/ValveSoftware/Proton/files/4321740/system_info.txt)

**Comment by AwesamLinux** [comment]
@BigB86 You did nothing wrong, you just discovered a Proton bug/regression. Launch options are generally only needed when a game is not working out of the box as expected :smile:

**Comment by iBringsTheRuckus** [comment]
> @BigB86 You did nothing wrong, you just discovered a Proton bug/regression. Launch options are generally only needed when a game is not working out of the box as expected

Awesome! Glad I reported it. So should I keep this launch option enabled? Not sure if when I update steam if it will remove the launch option because of the fix in the near future. I've enabled Steam beta. Sorry for not knowing the process. Thanks a lot guys!

**Comment by AwesamLinux** [comment]
Yea you can keep playing the game using the launch option, Steam will have the launch option saved until you uninstall the game. In the future when you see that there is a new Proton version/update released, you can try removing the launch option and see if the game works without it.

**Comment by iBringsTheRuckus** [comment]
> Yea you can keep playing the game using the launch option, Steam will have the launch option saved until you uninstall the game. In the future when you see that there is a new Proton version/update released, you can try removing the launch option and see if the game works without it.

Thanks a lot for the reply. I'll play the game fully tomorrow to see if there are any other issues. Have a good night.

**Comment by iBringsTheRuckus** [comment]
I would like to report that this game now launches without issue on Proton 5.0-5 without launch options. Thank you for your help and hard work!
