### ISSUE TITLE
Puyo Puyo Tetris (546050)

### ISSUE THREAD

**Issue by fagnerln** [ValveSoftware/Proton#3630]
# Compatibility Report
- Name of the game with compatibility issues: Puyo Puyo Tetris
- Steam AppID of the game: 546050

## System Information
- GPU: RX580
- Driver/LLVM version: Mesa 20.1
- Kernel version: 5.3

- Link to full system information report as [Gist](https://gist.github.com/fagnerln/18fa34bae26c4132b86936072dd83e10):
- Proton version: 5.0-4

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

I can't add the LOG because it's a very large file, with 561756 lines and 56MB, so I uploaded it to Google Drive:

https://drive.google.com/file/d/1Cc_aFGP14FFVKP_raldPquM8Z4Bdvswr/view?usp=sharing

## Symptoms 

The game simply don't run anymore, it worked perfectly fine until yesterday, with 5.0-3

## Reproduction

1- Click Play, and nothing happens

**Comment by kisak-valve** [comment]
Hello @fagnerln, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/359#issuecomment-598188047.
