### ISSUE TITLE
Xbox 360 controller issue

### ISSUE THREAD

**Issue by nenoro** [ValveSoftware/Proton#3634]
Hello

Some months ago i could launch any game and use my x360 controller but since 2 weeks whatever protron i use the controller isn't recognize anymore.

Works native/non native: Iconoclats, Alpha Protocol (Is that the option in-game settings to activate the controller) same for The Technomancer, TB Anniversary, Legend, Underworld.

But Mafia 3, the witcher 3 even i turn on in steam settings nope nothing change.

It was working perfectly before.

Proton: 5.0.4, 5.2 GE-2 (I already try with under version for both)
Distro: Gentoo 5.5.8 (between stable version to 5.5.8 nothing only on 5.5.5 it worked for 2 days)
CPU/GPU: R7 1800X / RX 480 8GB

i tried some days ago with xboxdrv but nope. I usually activate the module in the kernel as [M] even as [x] it didn't work.

I'm tired of trying to make it work i thought it was gentoo but nope something from proton is off

**Comment by aeikum** [comment]
Can you gather a log file with these channels set: `+tid,+pid,+dinput,+xinput,+rawinput,+plugplay,+hid`. Upload it here and I'll take a look. You may need to compress it.

**Comment by nenoro** [comment]
[steam.log](https://github.com/ValveSoftware/Proton/files/4354765/steam.log)

i have launched witcher 3 and exit

**Comment by nenoro** [comment]
hi
so i finally manage to make it work again it is in the kernel i had to turn on a module who it doesn't by default
