### ISSUE TITLE
Imposible to calibrate pedals in Project Cars

### ISSUE THREAD

**Issue by leillo1975** [ValveSoftware/Proton#364]
After playing a little more to this game, I found more errors than reported in this issue:

https://github.com/ValveSoftware/Proton/issues/244

Is impossible to calibrate the pedals of my G27 wheel, that is detected correctly by the game. If you go to game settings and start to calibrate it, this action finish without doing anything. Instead, is possible to calibrate the wheel normally.

**Comment by arzardk** [comment]
I think you should write about this problem in #244 because they keep one thread for one unofficial game.

**Comment by leillo1975** [comment]
You are right.... posted: https://github.com/ValveSoftware/Proton/issues/244#issuecomment-415687006

**Comment by kisak-valve** [comment]
Thanks for adding this to #244. Closing in favor of the existing issue report.
