### ISSUE TITLE
Can't input CJK on proton.

### ISSUE THREAD

**Issue by Libert-Sin** [ValveSoftware/Proton#3641]
I input Korean with nimf on my arch linux.

but In proton can be input only English.

ibus, fxitc also can't input CJK.

how input CJK on proton?

**Comment by jzengc** [comment]
XIM is disabled for working around a X11 issue: https://github.com/ValveSoftware/wine/commit/557144d3b78b1dbe1b8e9dc14e2e6ccda2a1c11d#diff-adc23fa7bcadeff404bb73143ff1699f

**Comment by aeikum** [comment]
There is some information about how you can work around this issue here: https://github.com/ValveSoftware/Proton/issues/3528#issuecomment-589828273

**Comment by Libert-Sin** [comment]
> XIM is disabled for working around a X11 issue: [ValveSoftware/wine@557144d#diff-adc23fa7bcadeff404bb73143ff1699f](https://github.com/ValveSoftware/wine/commit/557144d3b78b1dbe1b8e9dc14e2e6ccda2a1c11d#diff-adc23fa7bcadeff404bb73143ff1699f)

i try XIM disabled and enabled but ibus · fxitc not work on ptoron.

**Comment by wengxt** [comment]
> XIM is disabled for working around a X11 issue: [ValveSoftware/wine@557144d#diff-adc23fa7bcadeff404bb73143ff1699f](https://github.com/ValveSoftware/wine/commit/557144d3b78b1dbe1b8e9dc14e2e6ccda2a1c11d#diff-adc23fa7bcadeff404bb73143ff1699f)

Though, with xim enabled, Compose key won't work on client side. But with a proper implemented input method server (e.g. fcitx), the compose key will be handled on input method server side. Disabling XIM is not the right approach for the problem. Or at least, this should be able to be configured (e.g. environment variable).

**Comment by aeikum** [comment]
@wengxt  We disable XIM because libx11 has a bug that causes a crash. We can't work around this in Wine. We're trying to upstream a fix into libx11 but they haven't been very responsive. It is configurable. See the link I posted earlier in this thread. If you get lucky your application may not crash.

**Comment by OctopusET** [comment]
Here's alternative xim handler wrote in Rust.
Can this be solution?

https://github.com/Riey/xim-rs

**Comment by alasky17** [comment]
XIM is no longer disabled by default with Proton 9.0-beta.  Could anyone impacted by this please retest and see if XIM input is now behaving as they would expect with Proton 9.0-beta?

**Comment by kisak-valve** [comment]
Closing as fixed in Proton 9.0-1.
