### ISSUE TITLE
endless legend stucks while loading new game

### ISSUE THREAD

**Issue by JaiRadhe** [ValveSoftware/Proton#3642]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: Intel® UHD Graphics 620 
- Driver/LLVM version: 3.0 Mesa 19.2.8 
- Kernel version: 4.15.0-88-generic

- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/JaiRadhe/c362ea66f960123bf2dcd0c0f38b5e04
- Proton version: 4.11-13

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

## Symptoms 
not loading new game or tutorial. stucks after connection to server. here screenshot and 
[steam-289130.log](https://github.com/ValveSoftware/Proton/files/4334278/steam-289130.log)

![Снимок экрана от 2020-03-15 20-42-20](https://user-images.githubusercontent.com/19622772/76701702-61fe3f00-66fe-11ea-8893-6b0e9bc58b5e.png)

**Comment by kisak-valve** [comment]
Hello @JaiRadhe, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/619#issuecomment-599212341.
