### ISSUE TITLE
Granblue Fantasy Versus (1090630)

### ISSUE THREAD

**Issue by Supreeeme** [ValveSoftware/Proton#3643]
# Compatibility Report
- Name of the game with compatibility issues: Granblue Fantasy: Versus
- Steam AppID of the game: 1090630

## System Information
- GPU: GTX 1060 6GB
- Driver/LLVM version: nvidia 440.64
- Kernel version: 5.5.9-arch1-2
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/YungDaVinci/d5fbc41ae31812574d9346968df8e014
- Proton version: 5.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Attempting to queue up an online match in Proton 5.0-4 results in the game instantly removing you from the queue and saying connection was lost. This problem is not present in 4.11-13. ProtonDB reports suggest it works without any extra configuration on other systems. Problem is present in both native runtime and the packaged runtime.

## Reproduction
1. Start up the game using Proton 5.0-4
2. Go to the online menu
3. Attempt to queue up a match

**Comment by kisak-valve** [comment]
Hello @YungDaVinci, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by Supreeeme** [comment]
Ah sorry, forgot
[granblue-5.0.log](https://github.com/ValveSoftware/Proton/files/4334441/granblue-5.0.log)

**Comment by Supreeeme** [comment]
Thought it would be worth noting that online functionality works using vanilla Wine 5.4 + DXVK but not using GloriousEggroll's custom Proton 5.4 build.

**Comment by Supreeeme** [comment]
Fixed in 5.0-5.

**Comment by jeromealane1** [comment]
Compatibility Issue

    Name of the game with compatibility issues: Granblue Fantasy: Versus
    Steam AppID of the game: 1090630

System Information

    GPU:1080 TI
    Driver/LLVM version: nvidia 465
    Kernel version: 5.10
    Proton version: 7.0
    Controller: custom hit-box using Universal Fight board


Issue,
When using a Universal fight board controller, I cannot set the controls in game while steam input is disabled.
Changing the controls with my ps4 fight stick works fine.


Reproduce
    Disable steam input
    Start up the game using Proton 7 using a controller that has a Universal fight board
    Go to the system settings
    Try to change your controls in the controller settings

**Comment by kibivolt** [comment]
# Compatibility Report
- Name of the game with compatibility issues: Granblue Fantasy: Versus
- Steam AppID of the game: 1090630

## System Information
- GPU: AMD Custom GPU 0405
- Driver/LLVM version: (vangogh, LLVM 14.0.6, DRM 3.45, 5.13.0-valve36-1-neptune), 4.6 (Compatibility Profile) Mesa 22.2.0 (git-17e5312102)
- Kernel version: 5.13.0-valve36-1-neptune
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kibivolt/5e808ef7ab9daa1a57f34aef3569a1b0
- Proton version: proton-7.0-6e
- Proton log: [steam-1090630.log](https://github.com/ValveSoftware/Proton/files/11009255/steam-1090630.log)
## I confirm:
- [x] that I have checked whether there are updates for my system available.



## Symptoms 
Game locks up / becomes unresponsive when viewing the command list. Also has gotten stuck on the loading screen after exiting training, however I have not reproduced it.

## Reproduction
1. Launch one of the game modes (e.g. Free Training)
2. Select characters (e.g. Percival vs Katalina)
3. Select a stage (e.g. Port Breeze)
4. Open the Command List from the pause menu
5. Scroll through the list of commands (some reports on protondb suggest you may need to view the move preview video for a bit)
6. Music will continue to play but the game will no longer respond to input

**Comment by kibivolt** [comment]
Hi @Supreeeme, I've tagged you here in case you are no longer following this issue. This issue tracker maintains one issue per unofficial game, so I believe that other compatibility reports/feedback as above would go here, but they may be overlooked if this issue is closed. Could you please re-open this issue when you get a chance? Thank you.

**Comment by kisak-valve** [comment]
Hello @kibivolt, if there's no open compatibility report for a game, then you can go ahead an open a new compatibility report to track the game title.

**Comment by kibivolt** [comment]
I've created a [new report for the game here](https://github.com/ValveSoftware/Proton/issues/6632). Sorry for the confusion.
