### ISSUE TITLE
Age Of Empires 2 Just the launcher working

### ISSUE THREAD

**Issue by ahmedselim2017** [ValveSoftware/Proton#3645]
# Compatibility Report
- Name of the game with compatibility issues: Age Of Empires 2 (2013)
- Steam AppID of the game: 221380

## System Information
- GPU: Intel Corporation HD Graphics 6000 (rev 09) Subsystem: Apple Inc. HD Graphics 6000
- Driver/LLVM version: Kernel driver in use: i915
- Kernel version: 5.5.9-arch1-2
- Link to full system information report as [Gist](https://gist.github.com/ahmedselim2017/75cdb013f1bbddb1a5674aa935c6b1f8)
- Proton version: 5.0.4

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

It just shows the launcher, I click play and the game stops.

## Reproduction

Open the game, click the start button.

**Comment by kisak-valve** [comment]
Hello @ahmedselim2017, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/72#issuecomment-599500419.
