### ISSUE TITLE
[question] how can i help if i know setting for game to work in wine

### ISSUE THREAD

**Issue by sarlej** [ValveSoftware/Proton#365]
Hello,
if i know settings for game to work in wine (e.g. game needs msxml4) how can i test it in proton?
Can i use components as in wine?
Where to contribute with game specific settings?

**Comment by c0r73x** [comment]
Not sure if this is the way that they want you to send in the fixes. but this is what you can do.

You add the dll override to this file https://github.com/ValveSoftware/wine/blob/1c79a38ca494d9e32fee9fc7543b7779b184c878/loader/wine.inf.in

For example like they did with this commit https://github.com/ValveSoftware/wine/commit/4f4cf00d62e6800bc71894ce569220ccc75ca359
