### ISSUE TITLE
Doom Eternal not starting

### ISSUE THREAD

**Issue by APoniatowski** [ValveSoftware/Proton#3655]
# Compatibility Report
- Name of the game with compatibility issues: Doom Eternal
- Steam AppID of the game: 782330

## System Information
GPU: nVidia GTX 1070
Driver/LLVM version: nvidia 440.64-2
Kernel version: 5.4.24-1
Link to full system information report as Gist:
 https://gist.github.com/APoniatowski/0a59f0b3fe5056f5156ecb24a6880a1e
Proton version: 5.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-782330.log](https://github.com/ValveSoftware/Proton/files/4357468/steam-782330.log)

## Symptoms 
Game crashes on start

## Reproduction
-install
-start

**Comment by oscarcp** [comment]
Crap, we both started the ticket at the same time. Shall I put mine as duplicate?

**Comment by kisak-valve** [comment]
Hello @APoniatowski, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3654#issuecomment-601481752.

**Comment by gardotd426** [comment]
@oscarcp no, @kisak-valve has already merged this one into yours, so your post is the official thread now.

**Comment by APoniatowski** [comment]
fine by me :)
