### ISSUE TITLE
Borderlands 3 will not launch

### ISSUE THREAD

**Issue by faelus** [ValveSoftware/Proton#3660]
# Compatibility Report
- Name of the game with compatibility issues: Borderlands 3
- Steam AppID of the game: 397540

## System Information
- GPU: RTX 2080 Super
- Driver/LLVM version: NVidia 440.64
- Kernel version: 5.3.0-42-generic 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/faelus/2e635c6b597c3396085e5dcad146da5f
- Proton version: 5.0-4

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

This setting created two logs in the steamapps/common/Borderlands 3 directory, "Borderlands3_d3d9.log" and "Borderlands3_d3d11.log". Both files were blank.

## Symptoms 

Game fails to launch. No error messages are reported.

## Troubleshooting Steps

As per related issues with getting the game to launch, performed following steps, with no change in behavior:

installed `<Workaround removed by moderator>` package
copied mfplat.dll into Borderlands 3 program folder

added "PROTON_USE_WINED3D11=1 %command%" to launch options

## Reproduction

Game fails to launch following fresh install, and after above steps are taken.

**Comment by Newbytee** [comment]
https://github.com/ValveSoftware/Proton/issues/2927 Could this be what you're running into? If it is, an error should appear in `dmesg` whenever you launch Borderlands 3.

Also, the mfplat-related workaround you suggested should not be mentioned here as it is of questionable legality.

**Comment by faelus** [comment]
That appears to have been it. I hadn't run across any information about checking the dmesg for errors before this, though I had stumbled across the boot option fix. I thought I had already implemented it, but when I went to verify, it turns out I hadn't. Thank you for the help.
