### ISSUE TITLE
Stuttering or Unrecognized/Incorrectly Mapped Controller in TrackMania² Stadium

### ISSUE THREAD

**Issue by AuroransSolis** [ValveSoftware/Proton#3661]
# Compatibility Report
- Name of the game with compatibility issues: TrackMania² Stadium
- Steam AppID of the game: 232910

## System Information
- GPU: AMD Radeon RX 480
- Driver/LLVM version: Mesa 20.0.1
- Kernel version: 5.4.2-gentoo
- Link to full system information report as [Gist](https://gist.github.com/AuroransSolis/eae682d0e5c5a3514a525cf4f49a336f):
- Proton versions: 5.0-4, 5.0-3, 4.11-13, 4.2-9, 3.16-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Log using Proton 3.16-9: [steam-232910-3.16-9.log](https://github.com/ValveSoftware/Proton/files/4358543/steam-232910-3.16-9.log)
Log using Proton 4.2-9: [steam-232910-4.2-9.log](https://github.com/ValveSoftware/Proton/files/4358539/steam-232910-4.2-9.log)
Log using Proton 4.11-13: [steam-232910-4.11-13.log](https://github.com/ValveSoftware/Proton/files/4358540/steam-232910-4.11-13.log)
Log using Proton 5.0-3: [steam-232910-5.0-3-1.log](https://github.com/ValveSoftware/Proton/files/4358590/steam-232910-5.0-3-1.log)
Log using Proton 5.0-3: [steam-232910-5.0-3-2.log](https://github.com/ValveSoftware/Proton/files/4358592/steam-232910-5.0-3-2.log)
Log using Proton 5.0-4: [steam-232910-5.0-4-1.log](https://github.com/ValveSoftware/Proton/files/4358541/steam-232910-5.0-4-1.log)
Log using Proton 5.0-4: [steam-232910-5.0-4-2.log](https://github.com/ValveSoftware/Proton/files/4358542/steam-232910-5.0-4-2.log)

Note: there's a difference in the settings and behaviour of the logs using 5.0-{3,4}, and I believe they are related. In the first one for each, the game is being run with the "Steam Input Per-Game Setting" set to "Use your global Steam Input settings (Xbox)". This was unintentional for the very first log I made (5.0-4), but I changed it to "Forced off" when I realized that the controller wasn't recognized in the game. Curiously, when it wasn't set to "Forced off", the game ran without stuttering, but as soon as I changed it back to that it started stuttering again. I don't know exactly what's going on here, but I do find it interesting.

## Symptoms
I have two choices with the game presently:
1. Extreme stuttering that makes the game unplayable (5.0-4, 5.0-3, 4.11-13)
2. Unrecognized/incorrectly mapped controller (4.2-9, 3.16-9)

## Reproduction
1. Choose any of the mentioned Proton versions
    a) Set "Steam Input Per-Game Setting" to "Forced off" or "Use your global Steam Input settings (Xbox)" for your choice of unplayable stuttering or unrecognized controller respectively if using >= 4.11-13
2. Start the game

**Comment by kisak-valve** [comment]
Hello @AuroransSolis, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/193#issuecomment-601719547.
