### ISSUE TITLE
Issues with SKSE64 in Skyrim SE (489830)

### ISSUE THREAD

**Issue by TheChriZ** [ValveSoftware/Proton#3665]
Since Proton 5.x.x (also GE Versions) SKSE either crashes after failing to load certain plugins (Engine Fixes, RaceMenu, etc) or if I disable certain plugins the starts I load a save and after the loading screen I just get a black screen. The music still plays, but my system locks up and I have to do a hard reset. When using Proton 4.11 everything works thing with all of my mods, using the known fAudio fix and sometimes having to Alt F4 when the game freezes when exiting (but this are known issues which should have been fixed in newer Proton Versions).

**Comment by kisak-valve** [comment]
Hello @TheChriZ, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/170#issuecomment-601733951.
