### ISSUE TITLE
Resident Evil 3: Raccoon City Demo (1173690)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3666]
# Compatibility Report
- Name of the game with compatibility issues: Resident evil 3 demo
- Steam AppID of the game: 1173690

## System Information
- GPU:  GT1060M
- Driver/LLVM version: NVIDIA 435.21
- Kernel version: 5.3.0-42-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/bobaxxx/04cf78b8bd1b1b630f9f2825b0922cb0
- Proton version: 5.0.4

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

## Symptoms 

Resident evil 3 demo is properly installed but the game crashed (black screen) when i launch it
i have to reboot the computer every time i try to launch the game

[steam-1173690.log](https://github.com/ValveSoftware/Proton/files/4360271/steam-1173690.log)

**Comment by iWeaker4you** [comment]
![Captura de pantalla_2020-03-19_17-53-34](https://user-images.githubusercontent.com/49424816/77214878-63e54b00-6ace-11ea-96cf-cebcf2ba6e5c.png)

You need install with WinePrefix mf-installcab and put mfplat.dll into .exe folder

here mf-installcab
https://github.com/z0z0z/mf-installcab

**Comment by kisak-valve** [comment]
Hello @iWeaker4you, your comment was removed because that workaround is legally problematic.

That said, it tells us is that this game would benefit from support for Media Foundation maturing.

**Comment by adrianlshaw** [comment]
FYI the demo worked out of the box on my [pc](https://gist.github.com/adrianlshaw/09a3cd8be69843a6d523fb37e3b64da5). Played for about an hour before getting bored. Flawless.
Ubuntu 18.04. Proton 5.05. NVIDIA GTX 1060

**Comment by laichiaheng** [comment]
There are glitches with DX12 in this game, but fine with DX11.
Proton 5.0-5
5.5.10-1-MANJARO
Mesa Gallium driver 20.0.1 for Radeon RX 580 Series
https://youtu.be/BDcmbxYqIlA

**Comment by ghost** [comment]
I read @iweakerforyou post, but i didnt even know how to set a WINEPREFIX, so this is a little bit risky for me if we dont get a proton fix, i dont want to get more issues thant i have if im doing wrong.

**Comment by laichiaheng** [comment]
The Xbox One Controller D-pad and left stick are opposite with Remote Play in this game.
It runs perfectly with this controller on local PC.

**Comment by tronje** [comment]
I had a few graphics glitches with DX11, and the demo froze completely after the completion screen, but otherwise it was playable.
Proton 5.0-5
Radeon RX 5700 XT, Driver:  X.Org AMD NAVI10 (DRM 3.36.0, 5.5.10-arch1-1, LLVM 9.0.1)

**Comment by ghost** [comment]
maybe ppl can do some reports on protondb for this game

**Comment by laichiaheng** [comment]
> I had a few graphics glitches with DX11, and the demo froze completely after the completion screen, but otherwise it was playable.
> Proton 5.0-5
> Radeon RX 5700 XT, Driver: X.Org AMD NAVI10 (DRM 3.36.0, 5.5.10-arch1-1, LLVM 9.0.1)

There is a known mfplat issue for Resident Evil 2, and it also happens to Resident Evil 3.
Here is the way to solve it: `<Workaround removed by moderator>`
WINE developers haven't solved this issue, yet.

By the way, I have graphical issue with DX12, but no issue with DX11.

**Comment by kisak-valve** [comment]
Hello @laichiaheng, the workaround you linked is legally problematic and has been removed. 

Please don't play dumb games with the edit button. You've been given a 24 hour timeout for the edit war.

**Comment by ghost** [comment]
after a new re-install, i got a new error message

my computer dont crash this time, but there is still the black screen after game launched

![dx12](https://user-images.githubusercontent.com/56174027/77228040-d4e73a00-6b84-11ea-8daa-6d220358125f.png)

seems to be relative to dx12

**Comment by ghost** [comment]
Is there any way to launch it via dx11 ? except something like WINEPREFIX or else

**Comment by 414n** [comment]
> There are glitches with DX12 in this game, but fine with DX11.
> Proton 5.0-5
> 5.5.10-1-MANJARO
> Mesa Gallium driver 20.0.1 for Radeon RX 580 Series
> https://youtu.be/BDcmbxYqIlA

I confirm the glitches with DX12 too (have an AMD Radeon RX590 card, see also [my system information](https://gist.github.com/414n/34891616266f2d4e4489173e8bbee632)), although I haven't tried with DX11 settings yet.
The glitches are the same as in the linked video, but they seem to appear only in the initial area of the metro/subway, not further on.
I also had a hang after completing the demo, probably due a cinematic that cannot be played. I guess this is related to missing mfplat support as in #1464 (the same as RE2).

[steam-1173690.log.gz](https://github.com/ValveSoftware/Proton/files/4364484/steam-1173690.log.gz)

**Comment by indeedwatson** [comment]
Been googling around to see if anyone else has my issues but apparently not. There's some areas where I just get a grey fog that doesn't allow me to see almost anything:

https://steamcommunity.com/sharedfiles/filedetails/?id=2034553502

AMD R9 270x, proton 5.0-5

**Comment by gort818** [comment]
@indeedwatson I believe your gpu only has experimental support with amdgpu. That might be the cause of your issue.

**Comment by ghost** [comment]
Answers litterally has nothing to do with the original question.

I resolve this problem by updating my nvidia-435 drivers to nvidia-440 drivers (adding through ppa, because linux mint doesnt have for the moment the 440 version).

 After that, the game finally launch, but still suffer from severe stuttering. I went to the option and choose "dx11" at 30-35 fps. then I needed also to set up graphic parameters almost to the max settings to more than 50 fps.

If that helps nvidia graphic cards owners.

ppl just glue to my thread and it doesnt go further. Just open a new thread if you get glitches with an AMD GPU. The problem isnt really the same.

i close the thread.

**Comment by 414n** [comment]
As far as i know (@kisak-valve, correct me if I'm wrong), Valve is using one issue report per unofficially supported game title, so "people gluing" to your thread were doing what is done also for other titles.
