### ISSUE TITLE
Grand Theft Auto 4 - first run on SteamOS 

### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/Proton#3667]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU:  GTX 1060
- Driver/LLVM version:  nvidia 415.27
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.0-5

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

The log is not recorded at this stage.

## Symptoms 

Game start stops when you install Rockstar games launcher.

**Comment by kisak-valve** [comment]
Hello @vladislavyuzbekov, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/350#issuecomment-602037678.
