### ISSUE TITLE
Nier: Automata Freezes entire system during flight of first mission  

### ISSUE THREAD

**Issue by minake14** [ValveSoftware/Proton#367]
Hi,

I've been having an with Nier: Automata freezing my entire system during the intro sequence right at the moment when the introduces an enemy and it fires a projectile. The computer freezes at exactly this moment every time and the music keeps playing in the background. Just the music, no other sound effects(i.e. combat, dialog, etc..). Normally I would drop into a terminal to look at whats happening, but I can't due to the freeze. 

[vulkaninfo output](https://gist.github.com/minake14/bc57ac8b0e929eb53d2b4aba8c96041f#file-vulkaninfo_output)

System info:
OS- Debian Buster
CPU- Intel i7-3770K 
GPU- RX 580
Driver: Mesa 18.1.6(LLVM 6.0.1)

Any assistance would be much appreciated!

**Comment by LeJimster** [comment]
You might want to try a newer LLVM.
https://github.com/doitsujin/dxvk/wiki/Driver-support

**Comment by minake14** [comment]
I'll give it a shot, but I'll have to find a different source than the Debian repos. I'll report if I find anything.

**Comment by doitsujin** [comment]
This is indeed a known issue with LLVM 6, you have to use LLVM 7 to run this game without hangs.

**Comment by minake14** [comment]
Thank you both and sorry for the late reply. I ended up having to compile mesa from git and now it runs flawlessly.

(For other Debian users)The devs behind LLVM have provided repos for Debian and Ubuntu here:
https://apt.llvm.org
