### ISSUE TITLE
Serious Sam 2 (204340)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#3672]
# Whitelist Request
- Name of the game to be whitelisted: Serious Sam 2
- Steam AppID of the game: https://steamdb.info/app/204340/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.64
- Distro version: Arch
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia
- Proton version: 5.0-5

LOG:
[steam-204340.log](https://github.com/ValveSoftware/Proton/files/4364294/steam-204340.log)

Works great out of the box.

**Comment by kisak-valve** [comment]
Hello @shoober420, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1081#issuecomment-602111726.

**Comment by shoober420** [comment]
Whoops! Sorry about that.
