### ISSUE TITLE
Serious Sam: The Random Encounter (201480)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#3675]
# Compatibility Report
- Name of the game with compatibility issues: Serious Sam: The Random Encounter
- Steam AppID of the game: https://steamdb.info/app/201480/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.64
- Kernel version: 5.5.10
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia
- Proton version: 5.0-5

LOG:
[steam-201480.log](https://github.com/ValveSoftware/Proton/files/4364380/steam-201480.log)

## Symptoms
Game plays, but there is no sound

**Comment by kisak-valve** [comment]
Hello @shoober420, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2996#issuecomment-602115787.

**Comment by shoober420** [comment]
Whoops, my apologize again.
