### ISSUE TITLE
make failed with "mkdir: command not found"

### ISSUE THREAD

**Issue by radonthetyrant** [ValveSoftware/Proton#3677]
I followed this guide: https://github.com/ValveSoftware/Proton/wiki/Build-instructions-(Fedora)

my environment:
```
cat /proc/version
Linux version 5.5.9-200.fc31.x86_64 (mockbuild@bkernel04.phx2.fedoraproject.org) (gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC)) #1 SMP Thu Mar 12 13:55:19 UTC 2020
```
proton version 5.0-5 with commit 22f40122788d5f65389f59144705309ce9d6d403

docker images exist:
```
docker image ls | grep steam
steam-proton-dev32                latest              4fd54d1a7c44        3 hours ago         1.94GB
steam-proton-dev                  latest              75ada99fe614        4 hours ago         2.11GB
```

I followed all the commands up until the "Build" section that says `Now it's time to build Proton itself`
the `make` command failed:

```
rdn@localhost:~/proton-mybuild|⇒  make
make  -f Makefile NO_NESTED_MAKE=1
make[1]: Entering directory '/home/rdn/proton-mybuild'
mkdir -p obj-glib32
/bin/bash: mkdir: command not found
make[1]: *** [../proton/build/makefile_base.mak:314: obj-glib32] Error 127
make[1]: Leaving directory '/home/rdn/proton-mybuild'
make: *** [../proton/build/makefile_base.mak:17: nested_make] Error 2
```
i noticed that i didnt install steam, i did that via dnf from the 3rd party repos, but that didnt change the situation

**Comment by Newbytee** [comment]
Not necessarily a solution to your issue, but the "easy build path" in the README worked just fine for me on Fedora 31. Install vagrant and its qemu backend (assuming you have virtualisation available) from dnf and you're good to go.

**Comment by aeikum** [comment]
Yeah I'd strongly recommend using the Vagrant-based build path that @Newbytee mentioned. Setting up a system to build Proton is not easy, and the Vagrant stuff will take care of that for you.
