### ISSUE TITLE
CTD on start game on Navi10

### ISSUE THREAD

**Issue by Atrosha** [ValveSoftware/Proton#3682]
# Compatibility Report
- Name of the game with compatibility issues: Witcher 3
- Steam AppID of the game: 292030

## System Information
- GPU: Sapphire AMD Radeon RX 5700 PULSE (8 GB)
- Driver/LLVM version: 4.6 Mesa 20.1.0-devel
- Kernel version: 5.6.0-0.rc5.git0.2.fc32.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Atrosha/65d146556983bdeb438c1d7ca3d721b7
- Proton version: Proton 5.4 GE-2 and Proton 5.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-292030.log](https://github.com/ValveSoftware/Proton/files/4371041/steam-292030.log)
[(MESA_DEBUG)terminal,log](https://github.com/ValveSoftware/Proton/files/4371045/MESA_DEBUG.terminal.log)

**Comment by kisak-valve** [comment]
Hello @Atrosha, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-602758075.
