### ISSUE TITLE
Call of Cthulhu (399810) Cutscenes Won't Trigger

### ISSUE THREAD

**Issue by ConnorA3** [ValveSoftware/Proton#3686]
# Compatibility Report
- Name of the game with compatibility issues:
Call of Cthulhu
- Steam AppID of the game:
399810

## System Information
- GPU: Nvidia GeForce GTX 1050
- Driver/LLVM version: 4.6.0 Nvidia 435.21
- Kernel version: 5.3.0-42-generic
- Link to full system information report as [Gist](https://gist.github.com/):
https://gist.github.com/ConnorA3/2e4fd8cc2ee69d805caa7e9b12db5f35
- Proton version: All to date

## I confirm:
- [ ✓] that I haven't found an existing compatibility report for this game.
- [ ✓] that I have checked whether there are updates for my system available.

## Symptoms 
The game itself runs as smooth as butter on High settings, and with impressive smoothness on Ultra, too, with no lag or graphical hiccups, however, the cutscenes are not being triggered and they are a requirement in order to progress in the story. I've tried setting the videos in their rightful folder to "read and write", I've tried playing them as individual video files and they work perfectly well, so I am unsure of what the actual issue is, especially since all the other games I have tested/played on Steam Play trigger cutscenes as they should.

**Comment by kisak-valve** [comment]
Hello @ConnorA3, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by ConnorA3** [comment]
[steam-399810.log](https://github.com/ValveSoftware/Proton/files/4381233/steam-399810.log)

**Comment by kisak-valve** [comment]
Thanks, looks like this game would benefit from support for Media Foundation maturing.

**Comment by ConnorA3** [comment]
Ah, I see....hopefully there will be official support for that soon. Thanks for the reply, much appreciated!

**Comment by jalabb** [comment]
@ConnorA3 The latest release of Proton-GE includes some support for Media Foundation, maybe you can try it : https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.5-GE-1

If you don't know how to install it : https://github.com/GloriousEggroll/proton-ge-custom#installation

**Comment by MrCraigen** [comment]
@jalabb @ConnorA3 I can confirm that the latest Proton-GE fixes the issue with Media Foundation. The background video in main menu works and intro video aswell.

**Comment by ConnorA3** [comment]
> @ConnorA3 The latest release of Proton-GE includes some support for Media Foundation, maybe you can try it : https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.5-GE-1
> 
> If you don't know how to install it : https://github.com/GloriousEggroll/proton-ge-custom#installation

Thank you very much, greatly appreciated!

**Comment by ConnorA3** [comment]
> @jalabb @ConnorA3 I can confirm that the latest Proton-GE fixes the issue with Media Foundation. The background video in main menu works and intro video aswell.

Cheers, it works fine! It seems really well optimized apart from that.

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX 5700 ITX
- GPU Driver: Mesa 20.1.0-rc1 (ppa:ernstp/mesarc)
- Kernel version: 5.7.0-050700rc4-lowlatency
- Distro version: 19.3 Tricia (64 bit) (Cinnamon)

Just for future reference, I'm commenting here to say that with custom/unofficial Proton 5.8-GE-1 the game does work for me out of the box. With regular Proton game gets stuck on any cut-scenes.

[steam-399810-5.8-GE-1-MF-4-gbefbdfc.log.zip](https://github.com/ValveSoftware/Proton/files/4606470/steam-399810-5.8-GE-1-MF-4-gbefbdfc.log.zip)
[steam-399810-proton-5.0-7.log](https://github.com/ValveSoftware/Proton/files/4606471/steam-399810-proton-5.0-7.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/4606472/system_info.txt)

**Comment by brandonegbert** [comment]
Cutscenes still don't work with 5.13-1.

Also, this should probably be kept open at least until it works without tweaks.

**Comment by auyer** [comment]
With Proton 6.3-2, I get a weird screen glich on every cutscene (they just get skiped) 
Hands here for a while: ![image](https://user-images.githubusercontent.com/12375421/115090000-08aca480-9eea-11eb-8c19-85dc1113a11d.png)
Even the Menu looks weird: 
How the medu looks: ![image](https://user-images.githubusercontent.com/12375421/115090006-0c402b80-9eea-11eb-8d0d-bdd38f7a762d.png)
