### ISSUE TITLE
Borderlands 3 (397540) not launching despite Ryzen workaround

### ISSUE THREAD

**Issue by Astror** [ValveSoftware/Proton#3687]
# Compatibility Report
- Name of the game with compatibility issues: Borderlands 3
- Steam AppID of the game: 397540

## System Information
- GPU: GTX 1070
- Driver/LLVM version: 440 and 435 (tested both)
- Kernel version: 5.0.3-42-generic
- Link to full system information report as [Gist](https://gist.github.com/): [System specs](https://gist.github.com/Astror/2ff415d7f232621869a8c08a7461443a)
- Proton version: 4.11-13 and 5.0-5 (tested both)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-397540.log](https://github.com/ValveSoftware/Proton/files/4383562/steam-397540.log)

## Symptoms 

Game started fine on i7-2600 but does not work on Ryzen 5 3600 anymore:
After pressing play, the _preparing to launch_ window appears, followed by the Borderlands 3 banner but instead of the loading screen launching as the third window, the game crashes.

## Reproduction

Same behavior on every start.

## Steps that I've tried
- Added `clearcpuid=514` to kernel boot parameters according to [this](https://github.com/ValveSoftware/Proton/issues/2927) workaround for Ryzen 3XXX cpus. Verified that `dmesg` no longer shows a problem with Borderlands 3
- Downgraded driver from 440 to 435, which the game launched with on old cpu
- Tried 4.11-13 and 5.0-5 Proton versions (former worked previously)
- Used a workaround for .mp4 files not playing (this also worked previously)

**Comment by kisak-valve** [comment]
Hello @Astror, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3635#issuecomment-604108895.
