### ISSUE TITLE
Our And The Blond Forest (Definitive Edition)

### ISSUE THREAD

**Issue by EMorris71** [ValveSoftware/Proton#3688]
# Compatibility Report
- Name of the game with compatibility issues: Ori And The Blind Forest Definitive Edition
- Steam AppID of the game:387290

## System Information
- GPU: Intel Bay Trail
- Driver/LLVM version: 
- Kernel version: Gnome 3.34.2
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Not sure how to verify 

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @EMorris71, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/67#issuecomment-604178163.
