### ISSUE TITLE
Far cry New Daw not launching

### ISSUE THREAD

**Issue by pcfirebeats** [ValveSoftware/Proton#3689]
# Compatibility Report
- Name of the game with compatibility issues: Far Cry New Dawn
- Steam AppID of the game: https://store.steampowered.com/app/939960/Far_Cry_New_Dawn/

## System Information
- GPU: :RX 470
- Driver/LLVM version: Mesa 19.2.8
- Kernel version:  5.3.0-7642-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/pcfirebeats/4a39dac3bc02a1eebe8f9ca557f3e501
- Proton version: 4.11.-13 **and** 5.0-5 **and** 5.4-GE-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. (not with these problems)
- [x] that I have checked whether there are updates for my system available.

## Symptoms : 

1 - Sometimes it starts launching the game but it does not launch, although on steam it says it is running.

2 - Sometimes it says Uplay is not installed.

3 - Once I got it to play, but I couldn't join a co-op game

**Comment by kisak-valve** [comment]
Hello @pcfirebeats, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2381#issuecomment-604474349.

**Comment by pcfirebeats** [comment]
Ok thanks, I will update on it.
