### ISSUE TITLE
Age of Empires III: Complete Collection - Error loading the PID generator DLL

### ISSUE THREAD

**Issue by Holzhaus** [ValveSoftware/Proton#369]
After installing and starting Age of Empires III: Complete Collection, the Product Key window pops up. After entering my key, and clicking OK, the following error message pops up:

> Error loading the PID generator DLL. The DLL could not be found! Please make sure the file is available int he installation directory and try again.

It's not possible to progress further.

**EDIT:** Logfile and system info can be found here: https://gist.github.com/Holzhaus/e1a5e7ad8b59d1b5a698a18042c109a8

**EDIT 2:** I'm using the flatpak installation of steam.

**Comment by arzardk** [comment]
You need to attach game log file and your system specs via [github gist](https://gist.github.com) to this issue. You can obtain log file if you running Proton with user settings, which you can find in your /home directory. Path to this folder is something like this `/home/arzardk/.steam/steam/steamapps/common/Proton 3.7`. In this folder you find file called `user_settings.example.py` or something similar. Just rename it to `user_settings.py` and run your game again. You can find log file in your /home directory after that.

**Comment by Holzhaus** [comment]
Thanks for the info. I added the gist link to my original post.

**Comment by Holzhaus** [comment]
`PidGen.dll` does exist:

```
$ cd ~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Age Of Empires 3/bin
$ ls -l | grep -i pid
-rwxr-xr-x  1 user user    95248 22. Aug 14:51 mgspid.dll
-rwxr-xr-x  1 user user    92944 22. Aug 14:52 mgspidx.dll
-rwxr-xr-x  1 user user    82968 22. Aug 14:52 mgspidy.dll
-rwxr-xr-x  1 user user    48656 22. Aug 14:52 PidGen.dll
-rwxr-xr-x  1 user user    31040 22. Aug 14:50 PidGenX.dll
-rwxr-xr-x  1 user user    30912 22. Aug 14:49 pidgeny.dll
```

I already tried symlinking `PidGen.dll` to `PIDGen.dll` (filename from the logs), but that didn't help.

**Comment by arzardk** [comment]
I have problems with flatpak version of Steam, like games with Proton unable to running at all. Have you tried running this game on default Steam?

**Comment by Holzhaus** [comment]
No, but the issue that flatpak was unable to start any games with Proton should now be fixed: flathub/com.valvesoftware.Steam#152
And I can start games other than AOE3 using flatpak'ed steam, e.g. Fallout: New Vegas or Stronghold Crusader 2.

**Comment by kisak-valve** [comment]
Hello @Holzhaus, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this to https://github.com/ValveSoftware/Proton/issues/17#issuecomment-415766461.
