### ISSUE TITLE
Steam runtime update causes regression for Proton (dxvk::DxvkError)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3691]
#### Your system information

* Steam client version (build number or date): Mar 26 2020, at 22:26:20
* Distribution (e.g. Ubuntu): Ubuntu 19.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
[sysinfo](https://gist.github.com/kakolisgay/64f07cffa58c780d0f61589add5d24e3)
[Gist (Alien Swarm)](https://gist.github.com/kakolisgay/23524e47e1acb2319623af8f779bec48), [Proton Log](https://gist.github.com/kakolisgay/21d1edf0387d901a99f7522b849c7193)
[Gist (SCP:SL)](https://gist.github.com/kakolisgay/a850a05e6420a412000ed757175e0e11), [Proton Log](https://gist.github.com/kakolisgay/048b08af558ebbb556d14d5ae4011610)
The recent steam update has broken Proton for some games, games that are ran using it will fail with various errors. Downgrading the version of proton to the last version will fix this issue for Alien Swarm (source), but not for SCP:SL (unity)

The `ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.` errors appear to be harmless, they appear even when a game is started successfully.

#### Steps for reproducing this issue:

1. Update to the latest steam version as of posting
2. Start a windows-only game (such as Alien Swarm or SCP:SL)
3. The game should run in the background for a brief moment, then crash.

**Comment by kisak-valve** [comment]
Hello @kakolisgay, we're tracking issues with games run with Proton in the Proton issue tracker, which is why this issue report was transferred.

**Comment by ghost** [comment]
@kisak-valve I believe this is a steam runtime issue, proton was fine until the last update.

**Comment by kisak-valve** [comment]
Let's use https://github.com/ValveSoftware/steam-for-linux/issues/6990 to track this issue, because removing Proton from the differential greatly reduces the scope of the issue.
