### ISSUE TITLE
N++ (230270)

### ISSUE THREAD

**Issue by 808-cowbell** [ValveSoftware/Proton#3692]
# Compatibility Report
- Name of the game with compatibility issues: N++
- Steam AppID of the game: 230270

## System Information
- GPU: GTX 1070 Ti
- Driver/LLVM version: 440.64
- Kernel version: 5.5.13-arch1-1
- Link to full system information report as Gist: [Gist](https://gist.github.com/808-cowbell/c0dc25540858e5f9793d22fcdef29c3a)
- Proton version: All versions up to and including 5.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
Networking doesn't work in-game, cannot connect to leaderboards, scores fail to sync upon finishing a stage.

## Reproduction
Launch game, attempt to view leaderboards, and/or finish a stage. I can reproduce this on all Proton versions I have tested.

I am using the Windows build in Proton as opposed to the native build because the native build doesn't work correctly on my system.

[steam-230270.log](https://github.com/ValveSoftware/Proton/files/4394942/steam-230270.log)

**Comment by 808-cowbell** [comment]
Native client has the same behavior, problem is likely not related to Steam Play. Closing issue.

**Comment by SeongGino** [comment]
For what it's worth, this title when running under Proton does not get past initial loading.

[steam-230270.log](https://github.com/ValveSoftware/Proton/files/9657956/steam-230270.log)

**Comment by kisak-valve** [comment]
Hello @SeongGino, since the reporting user has chosen to close this issue report, feel free to open a new compatibility report.
