### ISSUE TITLE
Grim Dawn with no launcher yields VR error

### ISSUE THREAD

**Issue by alex-gunning** [ValveSoftware/Proton#3696]
Whilst trying to run Grim Dawn through Steam with ProtonDB, I'm coming across the following error

```
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Application Data\openvr\openvrpaths.vrpath
terminate called after throwing an instance of 'dxvk::DxvkError'
```
Not sure why it's asking for VR paths.

Running with `PROTON_USE_WINED3D=1 %command%` the game runs fine.

**Comment by kisak-valve** [comment]
Hello @alex-gunning, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/466#issuecomment-605446506.
