### ISSUE TITLE
Act of aggression works on one of two systems with the same specs

### ISSUE THREAD

**Issue by ripper81** [ValveSoftware/Proton#3697]
On my PC the game Act of aggression is running fine. However if i try to start the game on a second nearly identical PC it crashes on startup. The Systemspecs listed above are the same for both machines. 

Kubuntu 19.10 64bit
Kernel 5.5
MESA 20.0.2
Proton: 5.0.5
GPU AMD Radeon RX 5700
CPU AMD Ryzen 5 3600

**Comment by kisak-valve** [comment]
Hello @ripper81, please grab the [compatibility report template](https://github.com/ValveSoftware/Proton/issues/new?template=compatibility-report.md), copy it to this issue report, and fill it out with info on the failing system.

**Comment by kisak-valve** [comment]
Closing in favor of #3698.
