### ISSUE TITLE
Mordhau Patch #17 on Proton

### ISSUE THREAD

**Issue by scraatch** [ValveSoftware/Proton#3699]
# Compatibility Report
- Mordhau
- Steam AppID of the game: 629760
- Current Steam Discussion Thread Regarding This Issue: https://steamcommunity.com/app/629760/discussions/1/2149846913186214881/

## System Information
- GPU: GTX 1050TI
- Driver/LLVM version: 440.64
- Kernel version: 5.4.28_1
- Proton version: 5.0-5

## Symptoms 
Does not Run

## Reproduction
Newest update breaks game

This seems to be the issue for me and other users.
`LogShaderLibrary: Display: Failed to load Shared Shader Library: Global and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: WebBrowserWidget and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: WebBrowserWidget_SC and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: WebBrowserWidget and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: WebBrowserWidget_SC and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: DiscordRpc and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: DiscordRpc_SC and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: DiscordRpc and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: DiscordRpc_SC and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: modio and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: modio_SC and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: modio and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: modio_SC and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: CryptoKeys and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: CryptoKeys_SC and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: CryptoKeys and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: CryptoKeys_SC and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: MeshEditor and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: MeshEditor_SC and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: MeshEditor and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: MeshEditor_SC and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: DatasmithContent and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: DatasmithContent_SC and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: DatasmithContent and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: DatasmithContent_SC and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: MediaCompositing and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: MediaCompositing_SC and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: MediaCompositing and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: MediaCompositing_SC and no native library supported.
LogRHI: Display: Failed to open default shader pipeline cache for Mordhau using shader platform 0.
LogShaderLibrary: Display: Failed to load Shared Shader Library: Mordhau and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: Mordhau_SC and no native library supported.
LogRHI: Display: Failed to open default shader pipeline cache for Mordhau using shader platform 0.
LogShaderLibrary: Display: Failed to load Shared Shader Library: Mordhau and no native library supported.
LogShaderLibrary: Display: Failed to load Shared Shader Library: Mordhau_SC and no native library supported.
LogRHI: Display: Failed to open default shader pipeline cache for Mordhau using shader platform 0.
`

I have done basics such as switching wine versions, enabling/re-enabling precache shaders, reinstall and verifying the game's files integrity

**Comment by kisak-valve** [comment]
Hello @scraatch, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2629#issuecomment-605510298.
