### ISSUE TITLE
Startup issue for the sim 3 on Ubuntu

### ISSUE THREAD

**Issue by jimmerd1** [ValveSoftware/Proton#3705]
# Compatibility Report
- Name of the game with compatibility issues: The Sims 3
- Steam AppID of the game: 47890

## System Information
- GPU: GTX 720m
- Driver/LLVM version:  nvidia 340 and nvidia 390
- Kernel version: 5.3
- Link to full system information report as [Gist](https://gist.github.com/): <script src="https://gist.github.com/jimmerd1/af872d81aa42123c460cc4b209e72135.js"></script>
- Proton version: 5.0-5

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

======================
Proton: 1584918606 proton-5.0-5b
SteamGameId: 47890
Command: [&apos;/home/kennoisthebest/.local/share/Steam/steamapps/common/The Sims 3/Support/EA Help/Electronic_Arts_Technical_Support.htm&apos;]
Options: {&apos;forcelgadd&apos;}
======================
ERROR: ld.so: object &apos;/home/kennoisthebest/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so&apos; from LD_PRELOAD cannot be preloaded (wrong $
ERROR: ld.so: object &apos;/home/kennoisthebest/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so&apos; from LD_PRELOAD cannot be preloaded (wrong $
ERROR: ld.so: object &apos;/home/kennoisthebest/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so&apos; from LD_PRELOAD cannot be preloaded (wrong $
ERROR: ld.so: object &apos;/home/kennoisthebest/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so&apos; from LD_PRELOAD cannot be preloaded (wrong $
esync: up and running.
ERROR: ld.so: object &apos;/home/kennoisthebest/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so&apos; from LD_PRELOAD cannot be preloaded (wrong $
7014.511:000a:000b:trace:loaddll:load_native_dll Loaded L&quot;C:\\windows\\system32\\kernelbase.dll&quot; at 0x7b000000: PE builtin
7014.511:000a:000b:trace:loaddll:load_so_dll Loaded L&quot;C:\\windows\\system32\\kernel32.dll&quot; at 0x7b410000: builtin
7014.512:000a:000b:trace:loaddll:load_native_dll Loaded L&quot;C:\\windows\\system32\\wineboot.exe&quot; at 0x400000: PE builtin
7014.516:000a:000b:trace:loaddll:load_so_dll Loaded L&quot;C:\\windows\\system32\\sechost.dll&quot; at 0x7fb34d5e0000: builtin
7014.516:000a:000b:trace:loaddll:load_so_dll Loaded L&quot;C:\\windows\\system32\\advapi32.dll&quot; at 0x7fb34d730000: builtin
7014.518:000a:000b:trace:loaddll:load_so_dll Loaded L&quot;C:\\windows\\system32\\msvcrt.dll&quot; at 0x7fb34d510000: builtin
ERROR: ld.so: object &apos;/home/kennoisthebest/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so&apos; from LD_PRELOAD cannot be preloaded (wrong $
7014.665:000c:000d:trace:loaddll:load_native_dll Loaded L&quot;C:\\windows\\system32\\kernelbase.dll&quot; at 0x7b000000: PE builtin
7014.665:000c:000d:trace:loaddll:load_so_dll Loaded L&quot;C:\\windows\\system32\\kernel32.dll&quot; at 0x7b410000: builtin
7014.667:000c:000d:trace:loaddll:load_native_dll Loaded L&quot;C:\\windows\\system32\\services.exe&quot; at 0x400000: PE builtin
7014.671:000c:000d:trace:loaddll:load_so_dll Loaded L&quot;C:\\windows\\system32\\sechost.dll&quot; at 0x7f87637a0000: builtin
7014.671:000c:000d:trace:loaddll:load_so_dll Loaded L&quot;C:\\windows\\system32\\advapi32.dll&quot; at 0x7f87638f0000: builtin
7014.673:000c:000d:trace:loaddll:load_so_dll Loaded L&quot;C:\\windows\\system32\\msvcrt.dll&quot; at 0x7f87636d0000: builtin
7014.673:000c:000d:trace:loaddll:load_native_dll Loaded L&quot;C:\\windows\\system32\\rpcrt4.dll&quot; at 0x6fbc0000: PE builtin
7014.674:000c:000d:trace:loaddll:load_native_dll Loaded L&quot;C:\\windows\\system32\\version.dll&quot; at 0x65780000: PE builtin
7014.674:000c:000d:trace:loaddll:load_native_dll Loaded L&quot;C:\\windows\\system32\\setupapi.dll&quot; at 0x6a700000: PE builtin
7014.675:000c:000d:trace:loaddll:load_native_dll Loaded L&quot;C:\\windows\\system32\\userenv.dll&quot; at 0x67d00000: PE builtin
ERROR: ld.so: object &apos;/home/kennoisthebest/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so&apos; from LD_PRELOAD cannot be preloaded (wrong $
7014.734:000f:0010:trace:loaddll:load_native_dll Loaded L&quot;C:\\windows\\system32\\kernelbase.dll&quot; at 0x7b000000: PE builtin
7014.735:000f:0010:trace:loaddll:load_so_dll Loaded L&quot;C:\\windows\\system32\\kernel32.dll&quot; at 0x7b410000: builtin

**Comment by kisak-valve** [comment]
Hello @jimmerd1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2502#issuecomment-605740241.
