### ISSUE TITLE
[252350] Double Dragon Neon: crashes at launch

### ISSUE THREAD

**Issue by toalex77** [ValveSoftware/Proton#3707]
# Compatibility Report
- Name of the game with compatibility issues: Double Dragon Neon
- Steam AppID of the game: 252350

## System Information
- GPU: nVidia GTX 970
- Driver/LLVM version: nVidia 440.66.03
- Kernel version: 5.5.11
- Link to full system information report as [Gist](https://gist.github.com/toalex77/051a95a0cbdd8d823dadadace4f07cc1/):
- Proton version: 5.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-252350.log](https://github.com/ValveSoftware/Proton/files/4404628/steam-252350.log)

## Symptoms 

Game starts, then suddenly crashes.

## Reproduction

I suppose the issue is related to the 32 cores of my system, in fact, if I turn off some of the cores, the game starts and it's playable.

**Comment by kisak-valve** [comment]
Hello @toalex77, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2128#issuecomment-606226219.
