### ISSUE TITLE
Sonny (586750) - Compatibility Report

### ISSUE THREAD

**Issue by nbusser** [ValveSoftware/Proton#3709]
# Compatibility Report
- Name of the game with compatibility issues: Sonny
- Steam AppID of the game: 586750

## System Information
- GPU: GT630M
- Driver/LLVM version: nvidia 390.132
- Kernel version: 4.18
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/nbusser/73a93250489046c32789f4ac570373aa
- Proton version: 3.7.8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Launching the game results in a sort of black screen: a display of my screen at the moment I clicked play is shown.

## Reproduction

Launch the game

[steam-586750.log](https://github.com/ValveSoftware/Proton/files/4410105/steam-586750.log)

**Comment by kisak-valve** [comment]
Hello @nbusser, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1401#issuecomment-606756328.

**Comment by nbusser** [comment]
I'm really sorry: I saw the Whitelist Request but not the compatibility report beside it.
