### ISSUE TITLE
No game files installed (Wolcen: Lords of Mayhem)

### ISSUE THREAD

**Issue by p0kR** [ValveSoftware/Proton#3710]
Since last weel I cannot start Wolcen.
Steam tells me that the binary is missing (see first picture below), but in fact all game files - except some profile and config files - are missing.
I already tried to uninstall and reinstall the game (with and without manually deleting the undeleted game files after uninstallation and with and without a reboot between uninstallation and reinstallation; all combinations).
When I try to install the game (after I uninstalled it), the "installation" takes no time and is instant "successfully finished", but it does not create/install any file.
I also tried using a new SteamLibrary-directory somewhere else, but I get the same issue.
When I try to open the properties of that game, my Steam client crashes.
I owas able to open the properties once and validating the the gamefiles, just validated 0 of 1 file(s) and told me, the validation would have been successful.
Clearing Steam's download cache also didn't help me.

I am using Steam on Ubuntu 19.10 and until today it just worked. This is also the only game I have such an issue.
I used tried Proton 5.0-5 and 4.11-13 via the general Steam settings.

![error](https://user-images.githubusercontent.com/26470877/78065557-bf97ba00-7393-11ea-83b3-9f7e661ad3e1.png)
![install](https://user-images.githubusercontent.com/26470877/78064901-beb25880-7392-11ea-8239-95688ce8c1b2.png)

**Comment by kisak-valve** [comment]
Hello @p0kR, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/496#issuecomment-606849620.
