### ISSUE TITLE
TemTem: some graphics missing

### ISSUE THREAD

**Issue by nicodemus144** [ValveSoftware/Proton#3711]
# Compatibility Report
- Name of the game with compatibility issues: TemTem
- Steam AppID of the game: 745920

## System Information
- GPU: AMD RX5700
- Driver/LLVM version: mesa 20.0.2 / aco
- Kernel version: 5.5.13-arch2-1
- Link to full system information report as [Gist](https://gist.github.com/): [Sys Info](https://gist.github.com/nicodemus144/cb47231a5efb208c95f1613b9a26cb3f)
- Proton version: 5.0-5. same issue in 4 series also

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

## Symptoms 
Certain icons and graphical effects do not appear, including:

* The multipliers in battle
* The type effectiveness ring when selecting a target for a move

## Reproduction

Get into a battle. Use a super effective move on a Tem. Use a weak move on a Tem.

Other reports mention this issue in protondb.

[steam-745920.log](https://github.com/ValveSoftware/Proton/files/4411209/steam-745920.log)

**Comment by nicodemus144** [comment]
word from another user is that these missing graphics and icons work with AMDVLK. i cannot test that, however.

**Comment by kisak-valve** [comment]
Hello @nicodemus144, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3441#issuecomment-606853032.
