### ISSUE TITLE
The Witness (210970) won't start, failing silently

### ISSUE THREAD

**Issue by stuglaser** [ValveSoftware/Proton#3713]
# Compatibility Report
- Name of the game with compatibility issues: The Whitness
- Steam AppID of the game: 210970

## System Information
- GPU: 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
- Driver/LLVM version: Mesa 19.2.8-0ubuntu0~18.04.3
- Kernel version: 4.15.0-88-generic (Ubuntu)
- Link to full system information report as [Gist](https://gist.github.com/stuglaser/28b2d9ef6ccb36802b54529252b230ad):
- Proton version: Version that steam defaults to, and I also tried Proton 5.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Steam log report: [steam-210970.log](https://github.com/ValveSoftware/Proton/files/4412861/steam-210970.log)

## Symptoms 

I click "Play" in steam, get the "Preparing to launch the Witness" dialog, which eventually disappears, and then...nothing.  The game does not start.  The "Stop" button reverts back to "Play".

## Reproduction

Click "Play"

(I did not find any relevant PR's or issues)

Thanks!

**Comment by kisak-valve** [comment]
Hello @stuglaser, your system information tells us you do not have Vulkan drivers installed for your video chipset. Please run `sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386` and retest.

**Comment by stuglaser** [comment]
Installed Vulkan, and enabled DRI 3, and now it seems to work!  Thank you!
