### ISSUE TITLE
Wer weiß denn sowas? (782130)

### ISSUE THREAD

**Issue by vfioexperte** [ValveSoftware/Proton#3714]
# Compatibility Report
- Name of the game with compatibility issues: Wer weiß denn sowas?
- Steam AppID of the game: 782130

## System Information
- GPU: AMD RX VEGA 64
- Driver version:  Mesa 20.0.2
- Kernel version: 5.3.5-fsync archlinux
- Proton version:5.0.5
- Link to full system information report as
[system_infos.log](https://github.com/ValveSoftware/Proton/files/4415330/system_infos.log)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

[steam-782130.log](https://github.com/ValveSoftware/Proton/files/4415338/steam-782130.log)

## Symptoms 
The game can't play the intro video and the answer videos from the questions.

## Reproduction

start the game with Proton 5.0.5.
The Intro can't play with black screen.
in the game can't play the answer video form the questions.

**Comment by kisak-valve** [comment]
Hello @vfioexperte, it looks like this game would benefit from support for Media Foundation maturing.

**Comment by vfioexperte** [comment]
Can you fix it.
with winetricks?

**Comment by vfioexperte** [comment]
I have tested:
protontricks -c "winetricks mf" 782130
not work the video files.

**Comment by kisak-valve** [comment]
There's [ongoing work](https://source.winehq.org/git/wine.git/?a=search&h=HEAD&st=commit&s=mf) upstream to improve support for Media Foundation, but there currently isn't a legal and easy to apply workaround for this framework.

**Comment by vfioexperte** [comment]
ok cant't fix mf.
good luck and thanks

**Comment by vfioexperte** [comment]
The game works.
1.
export WINEPREFIX='../steamapps/compatdata/782130/pfx' 
2.
delete '../steamapps/compatdata/782130/pfx' 
3.
`<Workaround removed by moderator>`
5.
start with Proton 4.11-13.
with Proton 5.0.5 not work.

**Comment by kisak-valve** [comment]
Hello @vfioexperte, that workaround is legally problematic and has been removed.
