### ISSUE TITLE
Preinstall physx to prefix

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/Proton#3717]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Preinstall physx to prefix to make some games work.

## Justification [optional] 
Some games like https://github.com/ValveSoftware/Proton/issues/3475 require physx installed to start.

## Risks [optional]
none?

## References [optional] 
https://github.com/Winetricks/winetricks/blob/6aa7f3388c7101d622161a8cc818c710eb8c8165/src/winetricks#L11106-L11119
https://github.com/ValveSoftware/Proton/issues/3475

**Comment by aeikum** [comment]
I don't think that's the right fix. The game does seem to include PhysX: https://steamdb.info/app/7850/depots/ so we should look into why it's not getting installed in Proton.

**Comment by soredake** [comment]
Ok, i'll report installer error to upstream.

**Comment by soredake** [comment]
https://bugs.winehq.org/show_bug.cgi?id=48879
