### ISSUE TITLE
Assign Origin and Uplay their own STEAM ID number

### ISSUE THREAD

**Issue by CSahajdacny** [ValveSoftware/Proton#3720]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description: 
Install and run Origin and Uplay by their own, like an Steam game. 

## Justification 
The idea is to make easy and simple to install and run Uplay and Origin games with a couple of clicks:

Example: 
Step one: Download and install Uplay via PROTON.
Step two: run it.
Step three: log in to uplay account.
Step four: download and play games from Uplay library.

**Comment by kisak-valve** [comment]
Hello @CSahajdacny, this would be a feature request for Steam, not Proton, and realistically I don't see a fake game entry happening for this.

**Comment by CSahajdacny** [comment]
My mistake, sorry: 
Then, Uplay and Origin should have their entry in tools section of the steam client.
