### ISSUE TITLE
TERA

### ISSUE THREAD

**Issue by Davetheraveuk** [ValveSoftware/Proton#3727]
**OS**: Reborn OS (Arch derivative)
**Proton Version**: 5.0.5
**Steam run package**: Steam (Runtime)
**Game**: TERA.
**RAM**: 8 GB
**CPU**: AMD FX-8370 Eight-Core Processor × 4
**GPU**: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti]
**Kernal**: 5.5.13-arch2-1

![Screenshot from 2020-03-08 16-41-52](https://user-images.githubusercontent.com/11774054/78450314-aafa4100-7675-11ea-9597-d5d5a7277484.png)
![Screenshot from 2020-03-10 14-55-44](https://user-images.githubusercontent.com/11774054/78450319-ae8dc800-7675-11ea-88c7-e8d88f4c94f2.png)

The game seems to randomly crash several times a day without warning.
Sometimes there are error messages and sometime there is not.
Let me know if there is anything else you require (logs or screengrabs).
Thanks.
Dave.

**Comment by kisak-valve** [comment]
Hello @Davetheraveuk, please copy the [game compatibility template](https://github.com/ValveSoftware/Proton/issues/new?template=compatibility-report.md) to this issue report and fill it out. There's more than one game called TERA and it's not clear which one you're referring to.

**Comment by Davetheraveuk** [comment]
@kisak-valve 
Please find below the completed game form as requested.
(https://github.com/ValveSoftware/Proton/issues/3729)
Thank you for your time.
Dave.
