### ISSUE TITLE
Patch backport request: Audio fixes for TrackMania Nations Forever

### ISSUE THREAD

**Issue by qwertychouskie** [ValveSoftware/Proton#3728]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
There are two patches that fix audio issues in TrackMania Nations Forever:
- `* dsound: Use an SRW lock for buffer_list_lock.`  This patch was introduced in Wine Staging 5.0-rc5, and upstreamed in Wine-devel 5.2.  It fixes a long-standing audio regression where virtually all SFX would not play.
- `* [48832] winmm: Use _lopen to avoid the 128 character path limit.`  This fixes the engine sound, and a few other SFX.  These SFX never worked until this patch (at least for me), so this bring full sound to the game.

## Justification [optional] 
These are already in Wine (devel for the first, staging for the second), but aren't in the current Proton builds.  They should be a safe backport, and fix known regressions/bugs in at least one game.

## Risks [optional]
Probably quite low.

## References [optional] 
https://github.com/ValveSoftware/Proton/issues/467#issuecomment-608138490 (and the following comments)

**Comment by kisak-valve** [comment]
Hello @qwertychouskie, please make a pull request with the commits and a link to where they landed upstream in https://github.com/ValveSoftware/wine/pulls.

**Comment by qwertychouskie** [comment]
@kisak-valve Done: https://github.com/ValveSoftware/wine/pull/89

**Comment by kisak-valve** [comment]
Thanks, let's use that merge request for any further discussion.
