### ISSUE TITLE
Update of steam client renders games unplayable

### ISSUE THREAD

**Issue by ShalokShalom** [ValveSoftware/Proton#3732]
Your recent update has lead to Resident Evil 2 Remake and Assassin`s Creed Odyssey being unplayable.

I had both running 4 days ago, then your update come in and both are crashing without any error information.

I can launch Portal 2, so its not the whole library.

I run it on Linux, in a Flatpak and tried both the current and previous version of Proton.

When launching from the command line, it simply shows me a seg fault.

**Comment by kisak-valve** [comment]
Hello @ShalokShalom, you most likely encountered https://github.com/ValveSoftware/steam-for-linux/issues/6990. Please read https://github.com/ValveSoftware/steam-for-linux/issues/6990#issuecomment-605415889.
