### ISSUE TITLE
Darksiders II Deathintive Edition Graphic Subsystem Regression 

### ISSUE THREAD

**Issue by iWeaker** [ValveSoftware/Proton#3734]
# Compatibility Report
- Name of the game with compatibility issues: Darksiders II Deathnative Edition Graphic Subsystem Regression 
- Steam AppID of the game: 388410

## System Information
- GPU: GTX1050 
- Driver/LLVM version: 440.66.08
- Kernel version: 5.6.2-5-tkg-pds
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.0.5, 5.0.6rc 

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

Proton Log: 
[steam-388410.log](https://github.com/ValveSoftware/Proton/files/4435567/steam-388410.log)

## Symptoms 
The game has resolution detection problems, this happens since Proton 5.0.5, I have tried Proton GE and happen  the same  problem, it worked correctly in version 5.0.3 and is currently working in version 4.11.13 without any type of problem.

Proton 5.0.5 and Proton GE 5.5
![Captura de pantalla_2020-04-05_19-20-15](https://user-images.githubusercontent.com/49424816/78517704-03633880-7773-11ea-8e2f-1d0439486b8d.png)

Proton 4.11.13 
![Captura de pantalla_2020-04-05_19-23-16](https://user-images.githubusercontent.com/49424816/78517713-0a8a4680-7773-11ea-88ec-d211352ace1e.png)

**Comment by kisak-valve** [comment]
Hello @iWeaker4you, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/325#issuecomment-609764222.
