### ISSUE TITLE
Nier: Automata (524220) crashes

### ISSUE THREAD

**Issue by LongerHV** [ValveSoftware/Proton#3735]
# Compatibility Report
- Name of the game with compatibility issues: Nier: Automata
- Steam AppID of the game: 524220

## System Information
- GPU: GTX 1050Ti
- Driver version: nvidia-drivers-440.64
- Kernel version: 5.4.28-gentoo
- Link to full system information report: https://gist.github.com/LongerHV/30bcc8f906c8d25d207896ec16ea3690
- Proton version: 5.0-5

## I confirm:
- [ * ] that I haven't found an existing compatibility report for this game.
- [ * ] that I have checked whether there are updates for my system available.

## Symptoms
Game crashes in random moments. I get a pop up message:
"Runtime Error!
R6025
- pure virtual function call"

![Screenshot_20200405_115238](https://user-images.githubusercontent.com/46924944/78530707-7658c780-77e4-11ea-92bb-127d425c2c31.png)

**Comment by kisak-valve** [comment]
Hello @LongerHV, can you check if setting the game's launch options to `PROTON_NO_ESYNC=1 %command%` avoids the crash? (#1643)

**Comment by LongerHV** [comment]
Unfortunately PROTON_NO_ESYNC=1 did not do the trick for me. Sorry for duplicating the issue, I did not find the previous one.

**Comment by LongerHV** [comment]
Actually it did work. I didn't do it the right way first time... Thanks for help.
