### ISSUE TITLE
Doom 2016 doesn't want to launch

### ISSUE THREAD

**Issue by NicoloZorzetto** [ValveSoftware/Proton#3740]
* Game compatibility

    Name of the game with compatibility issues: DOOM (2016)
    Steam AppID of the game: 379720

* System Information

    GPU: RX5700XT
    Driver/LLVM version: latest OpenGL
    Kernel version: 5.5.7-arch1-1
    Proton version: 5.0

* Symptoms
I tried basically any guide and forum post I could find (previous issues included) and even reinstalled both the game and hole operating system. The game says it's ready, when I click 'PLAY' it says 'launching DOOM' but after a couple of seconds goes back to the green 'PLAY' button.

The game is in a ext4 disk that has no problems playing CS:GO for example (Linux native tho)

* System Information:
https://gist.github.com/NicoloZorzetto/6d28ae0173700f5de8f04b4437cca9a9

**Comment by kisak-valve** [comment]
Hello @NicoloZorzetto, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Additionally, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by NicoloZorzetto** [comment]
> Hello @NicoloZorzetto, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Additionally, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

hi there, added the System Information and added PROTON_LOG=1 %command% to the game's launch options but it doesn't seem to have created any log

**Comment by kisak-valve** [comment]
If Proton doesn't generate a log when you try to run a game with that environment variable set, that hints that something's gone wrong when Proton unpacked itself for the first time.

Separately, Mesa 19.2.7/LLVM 9.0.0 feels abnormally old for a Manjaro system, and given the age of Navi10 cards, would benefit from newer drivers, but that may be unrelated to your issue. Does any Vulkan-based game work on your system?

**Comment by NicoloZorzetto** [comment]
> If Proton doesn't generate a log when you try to run a game with that environment variable set, that hints that something's gone wrong when Proton unpacked itself for the first time.
> 
> Separately, Mesa 19.2.7/LLVM 9.0.0 feels abnormally old for a Manjaro system, and given the age of Navi10 cards, would benefit from newer drivers, but that may be unrelated to your issue. Does any Vulkan-based game work on your system?

I'll update them, I reinstalled the system this afternoon and didn't let it update everything just yet. I think I have only Doom that is Vulkan based. You'll have probably noticed this at the bottom of my System Information, dumb question: has it somehing to do with this hole thing?
`CClientJobGatherRuntimeInformation: container read output failed`

**Comment by kisak-valve** [comment]
> dumb question: has it somehing to do with this hole thing?
> `CClientJobGatherRuntimeInformation: container read output failed`

This is telling you the attempt to gather extended diagnostics information from the Steam Linux Runtime compatibility tool failed. This isn't an indication of an issue with Proton and unrelated.

**Comment by NicoloZorzetto** [comment]
> > dumb question: has it somehing to do with this hole thing?
> > `CClientJobGatherRuntimeInformation: container read output failed`
> 
> This is telling you the attempt to gather extended diagnostics information from the Steam Linux Runtime compatibility tool failed. This isn't an indication of an issue with Proton and unrelated.

okay. I also reinstalled proton but nothing changed

**Comment by Evernow** [comment]
Update your Manjaro system, it's way out of date: `sudo pacman-mirrors -f 5 && sudo pacman -Syyu
`

**Comment by NicoloZorzetto** [comment]
> Update your Manjaro system, it's way out of date: `sudo pacman-mirrors -f 5 && sudo pacman -Syyu `

will do right now, even tho my previous install should have been up to date

**Comment by NicoloZorzetto** [comment]
late follow up: after updating everything I checked and it still wouldn't load, so I tried dualbooting windows (to make sure I didn't have any sort of strange hardware problem) and it works just fine there

**Comment by fastoslinux** [comment]
is like this?
![Captura de tela de 2020-05-17 17-32-10](https://user-images.githubusercontent.com/17401812/82159456-8abcc500-9864-11ea-881e-d1e0cd7ffa4a.png)
