### ISSUE TITLE
Call of Duty: Black Ops II

### ISSUE THREAD

**Issue by tpurde** [ValveSoftware/Proton#3749]
# Compatibility Report
- Name of the game with compatibility issues: Call of Duty: Black Ops II
- Steam AppID of the game: 202970

## System Information
- GPU:  GeForce GTX 1050ti
- Driver/LLVM version:  440.64
- Kernel version:  5.3.0
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/tpurde/1c1755c604987191c80c05cdc0c00365
- Proton version: 5.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Log Files

[steam-202970.log](https://github.com/ValveSoftware/Proton/files/4458116/steam-202970.log) Log for Campaign

[steam-202990.log](https://github.com/ValveSoftware/Proton/files/4458117/steam-202990.log) Log for Multiplayer

[steam-212910.log](https://github.com/ValveSoftware/Proton/files/4458129/steam-212910.log) Log for Zombies

## Symptoms 
The game fails to launch

## Reproduction
Just launching the game.

## Useful Information 
Some people at [WineHQ](https://bugs.winehq.org/show_bug.cgi?id=46472) reported that Kernel version 4.19 broke this game. They also reported 
that if you revert back to Kernel 4.18, the game works perfectly but crashes after 35 minutes. The game consists of 3 Launchers (Campaign, Multiplayer and Zombies), please check
 all of these if anyone looks into this issue.

**Comment by kisak-valve** [comment]
Hello @tpurde, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/808#issuecomment-611708285.
