### ISSUE TITLE
Call of Juarez: Bound in Blood (21980)

### ISSUE THREAD

**Issue by FanderWasTaken** [ValveSoftware/Proton#3751]
# Compatibility Report
- Name of the game with compatibility issues: Call of Juarez: Bound in Blood
- Steam AppID of the game: 21980

## System Information
- GPU: Radeon RX 570
- Driver/LLVM version: 4.5 Mesa 19.2.8
- Kernel version: 5.5.15-200.fc31.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/FanderWasTaken/d67c65b9a0ce2ed507bdb31c91d9c9eb
- Proton version: 5.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-21980.log](https://github.com/ValveSoftware/Proton/files/4460028/steam-21980.log)

## Symptoms 

- All of the audio is fine except for the voices - they are all very low quality.
- There is no intro video and no background videos in main menu.

## Reproduction
Just boot up the game, load into singleplayer.

## Notes
This issue with audio is also present on Windows. I know this game is from 2009, but I don't think that such low res voice lines were intentional. This issue on linux can be fixed by running [this version of proton](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.5-GE-1).

**Comment by FanderWasTaken** [comment]
Btw, there's also this issue #1831 but I didn't come across that.

**Comment by kisak-valve** [comment]
Hello @FanderWasTaken, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1831#issuecomment-612010980.
