### ISSUE TITLE
The King of Fighters XIII (222940) Videos doens't play

### ISSUE THREAD

**Issue by Lucario24** [ValveSoftware/Proton#3753]
# Compatibility Report
- Name of the game with compatibility issues: The King of Fighters XIII
- Steam AppID of the game: 222940

## System Information
- GPU: Radeon RX 550
- Driver/LLVM version: 4.5 Mesa 19.2.8
- Kernel version: 5.3.0-46-generic
- full system information report: [Gist](https://gist.github.com/Lucario24/108967e1e6e0c2ca927a006e95686030)
- Proton version: 4.11-13

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game plays fine. However. videos don't play. Whenever a video is mean to play, it just get skipped and the game continues. For axample, there is an opening video at the beggining, who just gets skipped and the game goes directly to start screen. I know this must some be another case of the media foundation issue since the game uses wmv videos.

I tried many workarounds in order the solve this:

- Using another oficial proton version (5.0-5): Game doesn't start.
- Using unofficial oficial proton versions (proton 4.11-GE-1, 4.21-GE-2, 5.4-GE-3, 5.5-GE-1): Game doesn't start.

(the following methods are with proton 4.11-13, also I attached logs for each one. Every method was made after manually deleting a modified game's prefix and letting steam create a clean one)

- Install mf, ffdshow, directshow and other codecs with protontricks: Game works, but videos are skipped

- Install wmp9 with winetricks and a workaround (because of the 64 bits issue) mentioned for the user fallenguru [here:](https://github.com/Winetricks/winetricks/issues/1087#issuecomment-583763440) Game works, but videos are skipped 
[steam-222940-WMP9.log](https://github.com/ValveSoftware/Proton/files/4463777/steam-222940-WMP9.log)

`<Workarounds removed by moderator>`

It is worth mentioning that the first time I started the game after installing it, the opening video WORKED normally, this is also mentioned by an unknown user in a report [here](https://www.protondb.com/app/222940#LA59MMSg3W). Thats the only time I saw a video working normally after all this time playing the game.

**Comment by kisak-valve** [comment]
Hello @Lucario24, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/214#issuecomment-612283403. Additionally, some workarounds you've tested are legally problematic and have been removed.
