### ISSUE TITLE
Problems with chat/console

### ISSUE THREAD

**Issue by nididak** [ValveSoftware/Proton#3758]
# Compatibility Report
- Name of the game with compatibility issues: Alien Swarm:Reactive Drop
- Steam AppID of the game: 563560

## System Information
- GPU: Nvidia GT 710 
- Driver/LLVM version: nvidia 435.21 
- Kernel version: 5.3.0-46-generic 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/yiitbrak/b874b5b77c8372ee984cae5e4d588f43
- Proton version: 5.0-5

## I confirm:
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
-All kinds of text comes to chat box disappears from history between 5-10 seconds
-The font that console uses is so hard to read, mostly un visible and some letters are inside anothers

## Reproduction
-For chat  bug just write something to chat
-For console bug open console

**Comment by kisak-valve** [comment]
Hello @yiitbrak, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/942#issuecomment-612889779.
