### ISSUE TITLE
Risk of Rain 2 doesn't run with Proton

### ISSUE THREAD

**Issue by Primo909** [ValveSoftware/Proton#3760]
# Compatibility Report
- Name of the game with compatibility issues: Risk of Rain 2
- Steam AppID of the game: 632360

## System Information
- GPU:  GTX 980m
- Driver/LLVM version:  nvidia 440.64
- Kernel version:  Ubuntu 5.3.0-7642.34~1584408018~19.10~21df4b1-generic 5.3.18
- Link to full system information report as [Gist](https://gist.github.com/): 
[Systeminfo.log](https://github.com/ValveSoftware/Proton/files/4469050/Systeminfo.log)

- Proton version: 5.0-5

## I confirm:
- [+] that I haven't found an existing compatibility report for this game.
- [+ ] that I have checked whether there are updates for my system available.

 

[steam-632360.log](https://github.com/ValveSoftware/Proton/files/4469039/steam-632360.log)

**Comment by kisak-valve** [comment]
Hello @Primo909, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2476#issuecomment-612891665.
