### ISSUE TITLE
 42/5000 configuring the proton (I'm a new user)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3762]
#Use OpenGL-based wined3d for d3d11 and d3d10 instead of Vulkan-based DXVK **(I want it to be based on DXVK)**
     "PROTON_USE_WINED3D": "0",

     #Use Vulkan-based D9VK instead of OpenGL-based wined3d for d3d9. **(I want it to be based on DXVK)**
     "PROTON_USE_D9VK": "1",

     #Disable d3d11 entirely **(I did not understand this configuration, when putting 1 the game does not open and then the error. So by setting 0 the game works)**
     "PROTON_NO_D3D11": "0",

     #Disable eventfd-based in-process synchronization primitives **(I want it to remain disabled because when I leave it on I notice a loss of frames)**
     "PROTON_NO_ESYNC": "0",

     #Disable futex-based in-process synchronization primitives **(I want it to remain disabled because when I leave it on I notice a loss of frames)**
     "PROTON_NO_FSYNC": "0",

**Comment by kisak-valve** [comment]
Hello @Alisonmontteiro, all of these environment variables are for troubleshooting. Unless you're tinkering or troubleshooting an issue, you don't need to set any of them to get the fast path with Proton 5.0. `PROTON_USE_D9VK` is also obsolete and the equivalent is enabled by default in Proton 5.0.

**Comment by ghost** [comment]
> Hello @Alisonmontteiro, all of these environment variables are for troubleshooting. Unless you're tinkering or troubleshooting an issue, you don't need to set any of them to get the fast path with Proton 5.0. `PROTON_USE_D9VK` is also obsolete and the equivalent is enabled by default in Proton 5.0.

Thanks for your quick reply.
