### ISSUE TITLE
Fallout 76 (1151340)

### ISSUE THREAD

**Issue by Freso** [ValveSoftware/Proton#3767]
# Compatibility Report
- Name of the game with compatibility issues: Fallout 76
- Steam AppID of the game: 1151340

## System Information
- GPU: GTX 1070
- Driver/LLVM version: nvidia 440.66.08
- Kernel version: `Linux din 5.6.3-arch1-1 #1 SMP PREEMPT Wed, 08 Apr 2020 07:47:16 +0000 x86_64 GNU/Linux`
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Freso/593a4ae7878a6a674f1094ebea8a8f56
- Proton version: Proton 5.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

When you enter into the Atom store, all items show up as "Free" regardless of their actual price.

## Reproduction

1. Open game
2. Go into Atom store

Note: This is possibly (exactly?) the same issue as what I described in https://github.com/ValveSoftware/Proton/issues/4#issuecomment-583854991 and it has been an issue with Fallout 76 under Wine for probably as long I at least have been able to run the game under Wine, regardless of what Wine version.

**Comment by Freso** [comment]
Looks like https://github.com/ValveSoftware/Proton/issues/3766 was opened while I was typing up this report, so I guess this can be closed as duplicate.

**Comment by kisak-valve** [comment]
Hello @Freso, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3766#issuecomment-613498602.
