### ISSUE TITLE
the mouse feels different in games

### ISSUE THREAD

**Issue by chorriwuarri** [ValveSoftware/Proton#3769]
hello, everyone

The first thing is to apologize for my English. I'll try to explain as best I can.

I would like to ask for your help. Can someone with dual boot with windows try to install the game aim lab in steam? the game is free

the idea is that you configure the game exactly the same on windows and linux, to test the mouse behavior, you can configure any task to 10 min, i suggest you try with motioshot and try on both OS

I have the feeling that in linux the mouse is more nerdy, however if I make a 360º turn, the mouse travels the same distance on the table

but if I play in linux 10 min when I play in windows I have the feeling that the mouse is heavier, but it can't be a problem of sensitivity because the mouse travels the same distance on the table

Would that mean there's some kind of acceleration in linux?

my mouse is g502 and my profile is flat

xinput list-props {1..50} 2>/dev/null | fgrep 'libinput Accel Profile Enabled ('

libinput Accel Profile Enabled (301):   0, 1

**Comment by kisak-valve** [comment]
Hello @chorriwuarri, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2664#issuecomment-614029011.

**Comment by chorriwuarri** [comment]
Why did you close it?
using aim lab was just an example, it happens with other games
It also happens with wine-tkg + proton-raw-input patch and overwatch

2020-04-15 15:08 GMT+02:00, kisak-valve <notifications@github.com>:
