### ISSUE TITLE
Repeating root file on .steam folder

### ISSUE THREAD

**Issue by BarrelKnight723** [ValveSoftware/Proton#3772]
Hi, I was trying to get Proton GE and when J went on the root file in the .steam folder, it kept on repeating the .steam folder. I am on Linux Mint 19.3 Tricia and I am currently using Proton 5.0-5.

**Comment by kisak-valve** [comment]
Hello @CSForever07, this is not a Proton issue. (https://github.com/ValveSoftware/steam-for-linux/issues/6885)
