### ISSUE TITLE
VrMod For Garry's Mod

### ISSUE THREAD

**Issue by benrob0329** [ValveSoftware/Proton#3777]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:
Garry's Mod (ID 4000) with the VrMod (https://steamcommunity.com/sharedfiles/filedetails/?id=1678408548)

## System Information
- GPU: Nvidia GTX 980ti
- Driver/LLVM version: nvidia 440
- Kernel version: 5.5
- Proton version: 5.0-6
- System Information: https://gist.github.com/benrob0329/6d3aad583d043cc6e10ae2096995525b

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. (in this configuration)
- [x] that I have checked whether there are updates for my system available.

[steam-4000.log](https://github.com/ValveSoftware/Proton/files/4496040/steam-4000.log)
## Symptoms 
The mod is Windows-only, but seems to work for those users just fine. However upon starting it in Proton:

```
] vrmod_start

[VRMod] lua/autorun/vrutil.lua:390: g_sharedTexture is null
  1. VRMOD_ShareTextureFinish - [C]:-1
   2. VRUtilClientStart - lua/autorun/vrutil.lua:390
    3. unknown - lua/autorun/vrutil.lua:47
     4. unknown - lua/includes/modules/concommand.lua:54

CShaderAPIDX8::BlitTextureBits: couldn't lock texture rect or use UpdateSurface
(these continue for some time)
```

I have attempted to adjust library overrides, use a real d3d9 library (via Proton tricks) and generally take stabs in the dark but it has not led to any new information unfortunately.

## Reproduction

1. install Gmod
2. Force Use Of Proton
3. Install The VrMod As Per Link Above
4. Install VrMod Module As Per Workshop Page Instructions
5. Use Console To Start VR Mode

**Comment by kisak-valve** [comment]
Hello @benrob0329, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2848#issuecomment-615852659.
