### ISSUE TITLE
vagrant minimum memory size

### ISSUE THREAD

**Issue by axet** [ValveSoftware/Proton#3778]
Hello!

gcc failed to compile wine when vagrant resulting memory == 2G (using your formula from Vagrantfile). I'm getting a lot of "killed signal terminated program cc1" looks like memory issue. I changed it to 5940 and build succeed (not sure how much minimum is recurred I choice 5940 on first guess).

I guess Vagrantfile missing this:

memory = [memory, 4096].min

**Comment by aeikum** [comment]
I guess that's a reasonable thing to do. I set it to use half of the total system memory so it wouldn't greedily take over all the RAM on your system, forcing it to swap or activate the OOM killer. We could set a minimum like you suggest, or just show an error if we think there isn't enough available memory to build Proton. I'm not sure which is better.

**Comment by axet** [comment]
As I observe virtualbox is quite clever, even when you set all available memory to the VM it never takes it all until requested by apps. If you set all available memory and VM apps requests it all swap will be activated on host machine. Right now we need configure swap on virtualbox or use more memory to be able to compile wine. I think more memory as the only option.

**Comment by aeikum** [comment]
Sure, makes sense. I'll set a lower bound of 4096 like you suggest. You can try it out and see if it works for you:

```
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -35,6 +35,7 @@ else
   memory = 1024
   puts "Vagrant launched from unsupported platform."
 end
+memory = [memory, 4096].max
 puts "Platform: " + cpus.to_s + " CPUs, " + memory.to_s + " MB memory"
 
 Vagrant.configure(2) do |config|
```

**Comment by axet** [comment]
Typo?

```
memory = [memory, 4096].max
```

**Comment by axet** [comment]
4000 no longer enough with recent proton-5.13-4 build, gcc fails. I'm using 8000 (maybe it is overkill, probably 6000 should be enougth)
