### ISSUE TITLE
AOE 2 DE stuck on black screen

### ISSUE THREAD

**Issue by chirag-manwani** [ValveSoftware/Proton#3779]
# Compatibility Report
- Name of the game with compatibility issues: Age of Empires 2 Definitive Edition
- Steam AppID of the game: 813780

## System Information
- GPU: Nvidia GF117M (820M)
- Driver/LLVM version: 390.132
- Kernel version: 5.3.0-46
- Link to full system information report as [Gist](https://gist.github.com/):
https://gist.github.com/cmkmanwani/f1e3fb38c631c26fda7da3aeec28719e

- Proton version: 4.11-13 (also tried 5)

## I confirm:
- [Y] that I haven't found an existing compatibility report for this game.
- [Y] that I have checked whether there are updates for my system available.

The file is 44MB could not attach it here, So adding google drive link.
https://drive.google.com/open?id=1G4BVQlXo9I2F83DwaWerDMb0tVb1LHzu

## Symptoms 
The game opens with the logo, and then a black screen comes up. The AOE cursor is visible on the screen and I can move it. Clicking or pressing the keys on the keyboard does not do anything. The game just gets stuck at the black screen.
Tried things mentioned in this link- 
https://www.reddit.com/r/aoe2/comments/dwuplr/how_to_run_age_of_empires_2_definitive_edition_on/

## Reproduction
Install game using steam and run it.

**Comment by Evernow** [comment]
This is ridiculous. You are on an ancient branch of the Nvidia driver, and basically everything else about your system is also out of date. 

The game works flawlessly on an updated system, please update. 

Also there is already an open compatibility report about this, only one report per game. 

https://github.com/ValveSoftware/Proton/issues/3189

Just update.

**Comment by chirag-manwani** [comment]
I tried installing Nvidia driver 440, but I think it is not compatible with it, as it shows that it was not able to detect any hardware.
Apart from that even if the system is out of date, Is it possible to run it on the current configuration?
Since buying a new system is a bit of a luxury for me that I cannot afford. 
I referred to the other compatibility report, but it's about some other issue. I could post there too if you want.

**Comment by Evernow** [comment]
> I tried installing Nvidia driver 440, but I think it is not compatible with it, as it shows that it was not able to detect any hardware.
> Apart from that even if the system is out of date, Is it possible to run it on the current configuration?
> Since buying a new system is a bit of a luxury for me that I cannot afford.
> I referred to the other compatibility report, but it's about some other issue. I could post there too if you want.

The Nvidia driver for you is 430.40. 

There are guides on how to set it up on a modern distro like Manjaro (which I recommend, not Ubuntu): https://forum.manjaro.org/t/guide-install-and-configure-optimus-manager-for-hybrid-gpu-setups-intel-nvidia/92196

If you want to stay on Ubuntu for some reason, may need to consult their documentation on this.

**Comment by chirag-manwani** [comment]
Thank you. I will try this and get back to you.
Edit: I tried it and the same error as 440 pops up-
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

**Comment by kisak-valve** [comment]
Hello @cmkmanwani, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3189#issuecomment-616122055.

**Comment by chirag-manwani** [comment]
Oh Thanks. It might get resolved faster there.
