### ISSUE TITLE
Into The Breach (590380) has native Linux support now- It is whitelisted on Proton also

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/Proton#3784]
Hi , this title gained Linux support. But it is also whitelisted against Proton 4.11. 

https://www.gamingonlinux.com/articles/into-the-breach-from-subset-games-ftl-now-supports-linux.16475

https://steamdb.info/app/891390/

According to this article , it defaults to Proton due to whitelisting. So i think dropping it from whitelisting should be something to consider.

I don't have this game btw , purpose of this issue is purely informative.

**Comment by kisak-valve** [comment]
Closing per the note at https://github.com/ValveSoftware/Proton/issues/204#issuecomment-616830044.
