### ISSUE TITLE
CIV4 Beyond the Sword installs/downloads 0 bytes

### ISSUE THREAD

**Issue by onurkulak** [ValveSoftware/Proton#3790]
CIV4 Beyond the Sword
- Steam AppID of the game: 8800

## System Information
- GeForce GTX 1650
- Driver/LLVM version: 440.64
- Kernel version: 5.3.0-7648-generic
- [Link to full system information](https://gist.github.com/onurkulak/e4b45127a09b4e51f6e015f7a37bfb37):
- Proton version: tried with 4.11 / 5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

this is most likely not a proton problem but steam support is refusing to give me any help and they are forcing me to write it here. 

when I try to download this game, it doesn't download anything, it immediately finishes after downloading 0 bytes. 
I tried cleaning the download cache and changing my download servers, but they didn't work.

I can install and play other Civ4 clones just fine: base game and CIV4 COL are working fine but I couldn't install this expansion.

## Reproduction

Clicking install on Beyond the Sword game.

**Comment by kisak-valve** [comment]
Hello @onurkulak, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/179#issuecomment-617505460.
