### ISSUE TITLE
Jump King keeps crashing

### ISSUE THREAD

**Issue by BarrelKnight723** [ValveSoftware/Proton#3794]
I just got Jump King and it keeps crashing. I tried Proton 5.0-6 and Proton 5.6-GE-2. If someone knows a solution please help me out. I am using Ubuntu 20.04.

**Comment by kisak-valve** [comment]
Hello @CSForever07, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2810#issuecomment-619039786.
