### ISSUE TITLE
Cannot enable VKD3D in Monster Hunter World (ID 582010)

### ISSUE THREAD

**Issue by Galcian79** [ValveSoftware/Proton#3795]
Proton Version: 5.6-GE-2

Issue:

using `PROTON_USE_VKD3D=1`
forced `DirectX12Enable=On` in graphics-option.ini

now in game menu shows Directx 12 API: Yes
still DXVK_HUD has a different opinion

![Schermata del 2020-04-24 21-11-47 - 1](https://user-images.githubusercontent.com/38818634/80249530-4b8ac200-8672-11ea-91f3-8cd89f30d942.png)
Any idea how to fix this?

**Comment by kisak-valve** [comment]
Hello @Galcian79, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/175#issuecomment-619201125.
