### ISSUE TITLE
Doom Eternal Monitor/Resolution fail

### ISSUE THREAD

**Issue by Kalevr1** [ValveSoftware/Proton#3797]
# Compatibility Report
- Name of the game with compatibility issues: Doom Eternal
- Steam AppID of the game: 782330

## System Information
- GPU: RTX 2060 SUPER
- Driver/LLVM version: 4.6.0 NVIDIA 440.82
- Kernel version: 5.5.6
- Link to full system information report: https://gist.github.com/Kalevr1/6f5f51d29cc2e60e370c7dda858ace34
- Proton version: 5.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-782330.log.zip](https://github.com/ValveSoftware/Proton/files/4531885/steam-782330.log.zip)

## Symptoms 
After installing latest SteamPlay Proton 5.06 I got one perfect play session that lasted several hours. I took a break to eat and then came back to continue play. I have a 2 monitor setup. When I tried to launch the game a second time, it switched to a small window on the the secondary monitor.  The lower monitor is my default screen and sits at eye level. I can see the upper left corner of the Doom Intro being rendered within the quarter-sized window on the secondary monitor. The game engine thinks it is rendering on the entire screen but I only see the portion that overlaps the window. I can see 2 buttons in the UI and I can interact with them. I Alt-F4 to exit.

Seems fixable if I can manually force the monitor and resolution for the app but I don't know if that would work. One workaround I have found is if I delete ../steamapps/compatdata/782330 the game does 'first run' again, which always runs perfectly. 

I have included a screenshot of both monitors (1920x2160 pixels). Steam is fullscreen below on primary and you see the Doom Window above on the secondary.

![DoomEternalScreenshot-2020-04-18 14-56-48](https://user-images.githubusercontent.com/18370585/80263694-bd263880-8691-11ea-9d57-cc142c6e5e13.jpg)

**Comment by Kalevr1** [comment]
This is my first post so I hope it is correct starting a new report rather than attaching to another. If not apologies.

**Comment by kisak-valve** [comment]
Hello @Kalevr1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3773#issuecomment-619279354.
