### ISSUE TITLE
DXVK 0.70

### ISSUE THREAD

**Issue by ibrokemypie** [ValveSoftware/Proton#38]
Not sure if this is already being worked on, but here is an issue to track it.

Assume this is more of a difficult update due to the change of install mechanism and the inclusion of directx 10

**Comment by romulasry** [comment]
https://github.com/ValveSoftware/dxvk/issues/1

**Comment by Faalagorn** [comment]
Isn't it resolved now with 46967e3 in place?

**Comment by romulasry** [comment]
Yes.

**Comment by jp7677** [comment]
The DXVK hud and `~/.steam/steam/steamapps/common/Proton 3.7 Beta/dist/lib64/wine/dxvk/version` shows 0.64. Could it be that the version info is not correct anymore?

`~/.steam/steam/steamapps/common/Proton 3.7 Beta/dist/lib64/wine/dxvk/version` says:
`c24497d3ac8e3c79ad6161de3353f7d31de57a8c dxvk (v0.64-126-gc24497d)`
`~/.steam/steam/steamapps/common/Proton 3.7 Beta/version` says:
`1535137180`
Within the Steam UI the selected compatibility tool is listed as:
'Proton 3.7-4 Beta'

**Comment by dubigrasu** [comment]
@jp7677 
As far I can tell it is DXVK 0.70 though, see this: https://github.com/ValveSoftware/Proton/issues/479#issuecomment-415929650
Also I dumped the strings from the both (3.7-3 and 3.7-4 beta) DXVK binaries and compared them, in the 3.7-4 beta I could find the "Implemented D3D11.1 ClearView method" which was implemented only in 0.70.

**Comment by jp7677** [comment]
@dubigrasu thanks a lot for the links and the confirmation. I already had the feeling that just the version info was wrong.
I think it is wise to fix the version info to match the actual DXVK version to avoid lots of miscommunication in the future :).
