### ISSUE TITLE
SKSE64

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3801]
All version of proton past 4.15 break SKSE64 and SKSE compatibility, Mods will fail to run with the script engine. The script engine provides performance improvements in addition to enabling mod functionality.

The fallout 4 script extender functions similarly.

**Comment by kisak-valve** [comment]
Hello @Desulate, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/170#issuecomment-619451463.
