### ISSUE TITLE
Trials of Mana (924980)

### ISSUE THREAD

**Issue by darkpumpkins** [ValveSoftware/Proton#3803]
# Compatibility Report
- Name of the game with compatibility issues: Trials of Mana 
- Steam AppID of the game: 924980

## System Information
- GPU: Nvidia GTX1070 ti
- Driver/LLVM version: Nvidia 440.82
- Kernel version: 5.3.0-46-generic
- Link to full system information report as [Gist](https://gist.github.com/):
[configSteam.txt](https://github.com/ValveSoftware/Proton/files/4535022/configSteam.txt)
- Proton version: 5.0.6
-OS: Ubuntu 19.10 with LxQt / OpenBox WM

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

[steam-924980_save.log](https://github.com/ValveSoftware/Proton/files/4535023/steam-924980_save.log)

## Symptoms 
The game simply crash on start up. Not even a black screen, nothing just try to open during a few seconds than close itself.

## Reproduction
Just setup the game, the driver version 440.82 and launch the game.
`<Workaround removed by moderator>`

**Comment by kisak-valve** [comment]
Hello @darkpumpkins, the workaround you tried is legally problematic and has been removed. Also, there's no hint in the log that that subsystem was in use.

**Comment by kisak-valve** [comment]
It looks like you're encountering #2927, please give it a read.

**Comment by darkpumpkins** [comment]
> It looks like you're encountering #2927, please give it a read.

Thanks for the help !
I tried with the command : taskset -c 0-11 %command%
It didn't work but I did update my Ubuntu 19.10 to the 20.04 with the kernel 5.4 and now it works !
The issue seems to be related to the kernel 5.3 with my hardware configuration.
