### ISSUE TITLE
Derail Valley sound crackling and echoing (588030)

### ISSUE THREAD

**Issue by Thulium-Drake** [ValveSoftware/Proton#3808]
# Compatibility Report
- Name of the game with compatibility issues: Derail Valley
- Steam AppID of the game: 588030

## System Information
- GPU: GTX11070
- Driver/LLVM version: 440.82
- Kernel version: Debian 4.19.98-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Thulium-Drake/454fbc6bc0d08e91362eead0b1f10981
- Proton version: 5.0

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. There is, different issue. Way older version of Proton.
- [X] that I have checked whether there are updates for my system available.

[steam-588030.tar.bz2.zip](https://github.com/ValveSoftware/Proton/files/4536617/steam-588030.tar.bz2.zip)
NOTE: Remove .zip (github's rules...) and it's 522MB when unpacked :-)

## Symptoms 
Playing the game is OK, but seems to suffer from serious issue with sound. When running the game from Steam (which requires no additional setup at all), it works, but the frame rate suffers and all the sounds are echoing/cracking.

I have also tried running the game with a different version of WINE via Lutris (I just pointed Lutris at the executable delivered by Steam), which does not have this problem. It also has a better framerate and smoother gameplay.

So this has to have something to do with something that's on or off in "lutris-fshack-5.6-2-x86_64"

## Reproduction
1. Install game from Steam
2. Run it using Proton 5.0 (or any version or Proton-GE)
3. Notice awful sound and impacted framerate
4. Install Lutris
5. Configure a new game using lutris-fshack-5.6-2-x86_64 as the runner and run the game
6. Notice smooth framerates and good sound
7. ???
8. Profit!

**Comment by kisak-valve** [comment]
Hello @Thulium-Drake, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2301#issuecomment-619637326.
