### ISSUE TITLE
Warhammer 40000: Space Marine - Game crushes after applying nocd "fix"

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3809]
# Compatibility Report
- Name of the game with compatibility issues: Warhammer 40,000: Space Marine
- Steam AppID of the game: 55150

## System Information
- GPU: GeForce 920M
- Driver/LLVM version: NVIDIA-SMI 440.82
- Kernel version: 5.3.0-46-generic
- Link to full system information report:: [Gist](https://gist.github.com/dropestein/0184e8135fb3c83af7cc8a8e78611ffd)
- Proton version: 5.0

## I confirm:
- [Ok] that I haven't found an existing compatibility report for this game.
- [Ok] that I have checked whether there are updates for my system available.

The only report I found is only about the game not starting at all.

## Symptoms 

In a very specific part of the game, the game crashes.

## Reproduction

In the 10th mission/part, you place a power source in a platform, go to an elevator and the game just closes.

This is after replacing the .exe with a cracked version, as someone suggested in the other issue.

[steam-55150.log](https://github.com/ValveSoftware/Proton/files/4537572/steam-55150.log)

PS.: I tried to create this report the best I could, but it's my first time. If something is wrong or missing, please tell me and I'd gladly fix it. Thanks!

**Comment by kisak-valve** [comment]
Hello @dropestein, we can't support cracked games.
