### ISSUE TITLE
Symlink problem when launching games on an exFAT drive

### ISSUE THREAD

**Issue by rionerdo** [ValveSoftware/Proton#381]
I have installed games on an exFAT-formatted HDD.
But when I try to start the game, I receive a following error.
```
Traceback (most recent call last):
  File "/mnt/harddrive/arch/Steam/steamapps/common/Proton 3.7/proton", line 100, in <module>
    tar.extractall(path=basedir + "/dist")
  File "/usr/lib/python2.7/tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "/usr/lib/python2.7/tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib/python2.7/tarfile.py", line 2202, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/usr/lib/python2.7/tarfile.py", line 2280, in makelink
    os.symlink(tarinfo.linkname, targetpath)
OSError: [Errno 38] Function not implemented
```
It might be happened because exFAT doesn't support symbolic links.

**Comment by sir-maniac** [comment]
Wine prefixes do require symbolic links.  

A workaround to this is to move the game to a steam library on a native linux filesystem.  AFAIK proton installs itself in the same steam library the game is at.

If moving to an NTFS filesystem is a more desirable alternative, there is also a workaround(though it appears to be unsupported by valve): https://github.com/ValveSoftware/Proton/issues/82#issuecomment-415099440

**Comment by lf94** [comment]
I also encountered this. At the very least I wish the steam client would notify where the error log is to investigate. I had to do some searching to find it.

My solution is moving the games back onto the local drive, reformatting the USB 3.0 drive to NTFS, and copy back. Since both are flash-based storage it was fast.
