### ISSUE TITLE
Logitech G25 steering wheel is not recognized

### ISSUE THREAD

**Issue by atommaki** [ValveSoftware/Proton#3816]
# Compatibility Report
- Name of the game with compatibility issues: Dirt Rally 2.0 (but I guess the issue is more generic)
- Steam AppID of the game: 690790

## System Information
- GPU:  Nvidia GTX 970 
- Driver/LLVM version: nvidia 440.64
- Kernel version: 5.4.0-26-lowlatency
- Proton version: 5.0-6 

## I confirm:
-  that I haven't found an existing compatibility report for this game.
-  that I have checked whether there are updates for my system available.

## Symptoms 

Logitech G25 steering wheel is not recognized in the game (it's not possible to chose as an input device, it's simply not in the list) with proton version 5.0-6 (and 4.11-13), but it works fine with Proton 4.2-9

## Reproduction

Start Dirt Rally 2.0 with connected Logitech G25 steering wheel and try to use it during the game.
Try it with different proton version, what I tried:

- 4.2-9: works (force feedback doesn't work, but that's another known issue: #2366)
- 4.11-13: doesn't recognize the wheel
- 5.0-6: doesn't recognize the wheel

**Comment by kisak-valve** [comment]
Hello @atommaki, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2366#issuecomment-620913710.
