### ISSUE TITLE
SoulCalibur6 does not start appid = 544750

### ISSUE THREAD

**Issue by jeromealane1** [ValveSoftware/Proton#3817]
Does not work on any version of proton including the Glorious eggroll versions and using `<Workaround removed by moderator>`  for this hardware configuration. Crashes after installing c++

linux mint 19

inxi 

CPU: 24-Core (3-Die) AMD Ryzen Threadripper 3960X (-MT MCP MCM-) 
speed/min/max: 1867/2200/3800 MHz Kernel: 5.3.0-40-generic x86_64 
Up: 2d 7h 51m Mem: 16267.5/31982.8 MiB (50.9%) 
Storage: 2.73 TiB (85.5% used) Procs: 725 Shell: bash 4.4.19 inxi: 3.0.27 

lspci | grep NVIDIA
21:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1)

**Comment by kisak-valve** [comment]
Hello @jeromealane1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1780#issuecomment-621510355. Also, the workaround mentioned is legally problematic and has been removed.

**Comment by jeromealane1** [comment]
Ok thanks
