### ISSUE TITLE
Proton: Missing or invalid openvrpaths.vrpath file! [Errno 2] when trying to install DirectX

### ISSUE THREAD

**Issue by dodgypast** [ValveSoftware/Proton#3819]
The full error is:
`Proton: Missing or invalid openvrpaths.vrpath file! [Errno 2] No such file or directory: '/home/duncanm/.config/openvr/openvrpaths.vrpath'`
During the step in the picture:
![gscreenshot_2020-05-01-191014](https://user-images.githubusercontent.com/24266439/80804460-6d8ac400-8bdf-11ea-9d14-bd156d898e13.png)
This happens with other games as well.

I tried installing proton separately and got the following error which seems similar:
`sed: couldn't edit vrclient_x64/vrclient_x64/json: not a regular file`

This is running on Endeavour OS which is based on Arch

**Comment by kisak-valve** [comment]
Hello @dodgypast, these log messages should be harmless and non-fatal.

**Comment by dodgypast** [comment]
> Hello @dodgypast, these log messages should be harmless and non-fatal.

Many thanks... was taking such a long time to install I thought it was an error.
