### ISSUE TITLE
Elder Scrolls Online FPS dropdown

### ISSUE THREAD

**Issue by MadMagnetic** [ValveSoftware/Proton#3821]
# Compatibility Report
- Name of the game with compatibility issues: Elder Scrolls Online
- Steam AppID of the game: 306130

## System Information
- GPU: RX560X
- Driver/LLVM version: Mesa 20.0.5
- Kernel version: 5.6-pf
- Link to full system information report as [Gist](https://gist.github.com/): Doesn't work, so here's my inxi -Fxxxz
`System:    Host: madmagnetic-lp Kernel: 5.6.2-pf x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: KDE Plasma 5.18.4 
           tk: Qt 5.14.2 info: latte-dock wm: kwin_x11 dm: SDDM Distro: Manjaro Linux 
Machine:   Type: Laptop System: ASUSTeK product: TUF Gaming FX705DY_FX705DY v: 1.0 serial: <filter> 
           Mobo: ASUSTeK model: FX705DY v: 1.0 serial: <filter> UEFI: American Megatrends v: FX705DY.315 date: 03/09/2020 
Battery:   ID-1: BAT0 charge: 57.1 Wh condition: 60.0/64.0 Wh (94%) volts: 15.6/15.6 model: ASUSTeK ASUS Battery type: Li-ion 
           serial: <filter> status: Not charging 
CPU:       Topology: Quad Core model: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx bits: 64 type: MT MCP arch: Zen+ rev: 1 
           L2 cache: 2048 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 33535 
           Speed: 399 MHz min/max: 1400/2100 MHz boost: enabled Core speeds (MHz): 1: 399 2: 399 3: 399 4: 399 5: 399 6: 399 
           7: 399 8: 399 
Graphics:  Device-1: AMD Baffin [Radeon RX 460/560D / Pro 450/455/460/555/555X/560/560X] vendor: ASUSTeK driver: amdgpu 
           v: kernel bus ID: 01:00.0 chip ID: 1002:67ef 
           Device-2: Advanced Micro Devices [AMD/ATI] Picasso vendor: ASUSTeK driver: amdgpu v: kernel bus ID: 04:00.0 
           chip ID: 1002:15d8 
           Display: x11 server: X.Org 1.20.8 driver: amdgpu FAILED: ati unloaded: modesetting alternate: fbdev,vesa 
           compositor: kwin_x11 resolution: 1920x1080~60Hz 
           OpenGL: renderer: AMD RAVEN (DRM 3.36.0 5.6.2-pf LLVM 10.0.0) v: 4.6 Mesa 20.0.5 direct render: Yes 
Audio:     Device-1: Advanced Micro Devices [AMD/ATI] Raven/Raven2/Fenghuang HDMI/DP Audio vendor: ASUSTeK 
           driver: snd_hda_intel v: kernel bus ID: 04:00.1 chip ID: 1002:15de 
           Device-2: Advanced Micro Devices [AMD] Family 17h HD Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel 
           bus ID: 04:00.6 chip ID: 1022:15e3 
           Sound Server: ALSA v: k5.6.2-pf 
Network:   Device-1: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter vendor: AzureWave driver: rtl8821ce v: N/A 
           port: e000 bus ID: 02:00.0 chip ID: 10ec:c821 
           IF: wlp2s0 state: down mac: <filter> 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: ASUSTeK driver: r8169 v: kernel port: d000 
           bus ID: 03:00.0 chip ID: 10ec:8168 
           IF: enp3s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 931.51 GiB used: 243.70 GiB (26.2%) 
           ID-1: /dev/sda vendor: Toshiba model: MQ04ABF100 size: 931.51 GiB speed: 6.0 Gb/s rotation: 5400 rpm 
           serial: <filter> rev: 0J scheme: GPT 
Partition: ID-1: / size: 388.11 GiB used: 243.66 GiB (62.8%) fs: ext4 dev: /dev/sda6 
Sensors:   System Temperatures: cpu: 40.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
           GPU: device: amdgpu temp: 40 C device: amdgpu temp: 40 C 
Info:      Processes: 305 Uptime: 24m Memory: 15.52 GiB used: 4.41 GiB (28.5%) Init: systemd v: 244 Compilers: gcc: 9.3.0 
           clang: 10.0.0 Shell: fish v: 3.1.0 running in: yakuake inxi: 3.0.37`

- Proton version: 5.0-7

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

Logfile has 84.6 Mb weight, so I can't attach it here.

**Comment by kisak-valve** [comment]
Hello @MadMagnetic, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/556#issuecomment-622596569.

**Comment by MadMagnetic** [comment]
> Hello @MadMagnetic, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#556 (comment)](https://github.com/ValveSoftware/Proton/issues/556#issuecomment-622596569).

Ok, thank You.
