### ISSUE TITLE
Proton 5.0-7 regression for Splinter Cell Blacklist

### ISSUE THREAD

**Issue by HenrikHolst** [ValveSoftware/Proton#3822]
## Game Info
- Name of the game with issues: Tom Clancy's Splinter Cell: Blacklist
- Steam AppID of the game: 235600

## System Information
- GPU: RX480
- Driver/LLVM version: Mesa 19.2.8
- Kernel version: 5.0.0
- Proton version: 5.0-7

With 5.0-7 the game freezes and dies after aprox 5-10minutes of play. 5.0-6 worked perfectly so it must be a regression in 5.0-7 that causes this.

Have attached the proton log from such a crash but unsure if proton created a log for the game that crashed or if it just did it for the launcher (I noticed that the game starts 3 wine-processed [it's a Uplay game]).

[steam-235600.zip](https://github.com/ValveSoftware/Proton/files/4568953/steam-235600.zip)

**Comment by kisak-valve** [comment]
Hello @HenrikHolst, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3074#issuecomment-623014987.
