### ISSUE TITLE
Gears Tactics (1184050)

### ISSUE THREAD

**Issue by screwylightbulb** [ValveSoftware/Proton#3823]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 1184050

## System Information
- GPU: RTX2060M
- Driver/LLVM version: nvidia 440.82
- Kernel version: 5.4
- Link to full system information report: https://gist.github.com/screwylightbulb/f2850a1adc5f4c1daf7c6641692d55a0
- Proton version: 5.0-7

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

This log is it hanging after loading a Chapter 2 save game, did not actually get to gameplay:
[steam-1184050-1.log.tar.gz](https://github.com/ValveSoftware/Proton/files/4570292/steam-1184050-1.log.tar.gz)

This log is after about 2 turns in the tutorial mission, stuck in a state between actions:
[steam-1184050-2.log.tar.gz](https://github.com/ValveSoftware/Proton/files/4570273/steam-1184050-2.log.tar.gz)

## Symptoms 

Inconsistent. Can load the game, see the logos, log in via Xbox acct, start the game, etc. some of the time, but other times freezes at intermittent points. Not like a system hang, but more like the game getting stuck in a state and not progressing. Sometimes at the end of a cutscene, sometimes after a turn in-game, sometimes after loading a save game. 

Other issues are stutters at the beginning of cutscenes. Seems consistent with shader compiling or texture streaming.

Note, this is a DX12 only game, although I have not noticed anything wrong with the graphics. Seems fine when it does work.

## Reproduction
Load up game (using PROTON_NO_ESYNC=1 seems to have best results), log in, play through tutorial mission.

**Comment by mozo78** [comment]
There's a Win7 folder with d3d11on12.dll and d3d12.dll contents. I wonder if they can be used to force DXVK in some way. I tried to no avail.

**Comment by screwylightbulb** [comment]
> There's a Win7 folder with d3d11on12.dll and d3d12.dll contents. I wonder if they can be used to force DXVK in some way. I tried to no avail.

The whole "requires DX12" and "Win10 only" thing does seem a bit like artificially tacked on constraints. But anyhoo, will save my griping about that sort of thing for another place.

**Comment by jonek2k3** [comment]
as i reported on protondb i'm running game without issues. proton 5.0.9 with
PROTON_NO_FSYNC=1 PROTON_NO_ESYNC=1. 
played over 2h at first run, about 3 or missions, couple of cuscenes. no crash or anything like that. saying that game doesn't work with DXVK or VKD3D enabled.

**Comment by Bulbyzarr** [comment]
Are you sure to disable vkd3d ?
Without it, the game does not run ...

**Comment by screwylightbulb** [comment]
Not launching at all for me any more. Just gets stuck. (proton 5.13 and 5.09 same) This might be useful to someone:

```
3282.640:00c4:00cc:trace:seh:NtQueryInformationThread (0xfffffffffffffffe,12,0x4349fc50,4,(nil))
3297.598:00c4:00d0:trace:seh:NtQueryInformationThread (0xfffffffffffffffe,12,0x43c5fc50,4,(nil))
3333.654:00c4:0144:err:ntdll:RtlpWaitForCriticalSection section 000000007BC6E1C0 "../../../../proton/wine/dlls/ntdll/threadpool.c: wait_thread_executeinwaitthread_cs" wait timed out in thread 0144, blocked by 014c, retrying (60 sec)
3333.654:00c4:0100:err:ntdll:RtlpWaitForCriticalSection section 000000007BC6E1C0 "../../../../proton/wine/dlls/ntdll/threadpool.c: wait_thread_executeinwaitthread_cs" wait timed out in thread 0100, blocked by 014c, retrying (60 sec)
3333.654:00c4:0150:err:ntdll:RtlpWaitForCriticalSection section 000000007BC6E1C0 "../../../../proton/wine/dlls/ntdll/threadpool.c: wait_thread_executeinwaitthread_cs" wait timed out in thread 0150, blocked by 014c, retrying (60 sec)
3333.658:00c4:0124:err:ntdll:RtlpWaitForCriticalSection section 000000007BC6E1C0 "../../../../proton/wine/dlls/ntdll/threadpool.c: wait_thread_executeinwaitthread_cs" wait timed out in thread 0124, blocked by 014c, retrying (60 sec)
3398.656:00c4:0144:err:ntdll:RtlpWaitForCriticalSection section 000000007BC6E1C0 "../../../../proton/wine/dlls/ntdll/threadpool.c: wait_thread_executeinwaitthread_cs" wait timed out in thread 0144, blocked by 014c, retrying (60 sec)
3398.656:00c4:0150:err:ntdll:RtlpWaitForCriticalSection section 000000007BC6E1C0 "../../../../proton/wine/dlls/ntdll/threadpool.c: wait_thread_executeinwaitthread_cs" wait timed out in thread 0150, blocked by 014c, retrying (60 sec)
3398.656:00c4:0100:err:ntdll:RtlpWaitForCriticalSection section 000000007BC6E1C0 "../../../../proton/wine/dlls/ntdll/threadpool.c: wait_thread_executeinwaitthread_cs" wait timed out in thread 0100, blocked by 014c, retrying (60 sec)
3398.656:00c4:0124:err:ntdll:RtlpWaitForCriticalSection section 000000007BC6E1C0 "../../../../proton/wine/dlls/ntdll/threadpool.c: wait_thread_executeinwaitthread_cs" wait timed out in thread 0124, blocked by 014c, retrying (60 sec)
```

**Comment by screwylightbulb** [comment]
`32573.802:00e0:016c:err:ntdll:RtlpWaitForCriticalSection section 000000007BC6E1C0 "../../../../proton/wine/dlls/ntdll/threadpool.c: wait_thread_executeinwaitthread_cs" wait timed out in thread 016c, blocked by 0160, retrying (60 sec)`

**Comment by screwylightbulb** [comment]
Closing this for now as the game does seem to start for me now for no specific reason. Also it generally seems to work for people. There are some graphical glitches, but they are minor and very possibly not even related.

**Comment by esistgut** [comment]
I have extremely bad performances on this game: less than 8 fps on a 6900 XT.

## System Information
- GPU: RX 6900 XT
- Driver/LLVM version: Mesa 21.2.5
- Kernel version: 5.15.5
- Link to full system information report: https://gist.github.com/esistgut/56721ba0e25c3f833b6a0c110f80698f
- Proton version: Experimental


[steam-1184050.log](https://github.com/ValveSoftware/Proton/files/7636021/steam-1184050.log)

![Screenshot_20211201_182332](https://user-images.githubusercontent.com/869693/144284169-8f088f86-0e7b-43eb-bcb0-d1c0c84f6121.png)

**Comment by kisak-valve** [comment]
Hello @esistgut, the game is running with AMDVLK. It may be interesting to test if running it with mesa/RADV behaves the same.

**Comment by esistgut** [comment]
@kisak-valve it jumped to 100 fps right away, thank you.

**Comment by alosarjos** [comment]
For some reason this isn't working for me... I click play, Gnome shows some kind of invisible window with the game, the top panel hides like it's going to launch a fullscreen game, but that's all. Arch Linux + Gnome + Wayland on a 5700XT.

I have tried another couple of games and they worked just fine.

EDIT: Just tried on Xorg and kinda more the same. Here instead of an invisible window is a window with a "screenshot" of the desktop

EDIT2: Using Proton 7.0-4 is working fine. Maybe some regression in Experimental?


[steam-1184050.log](https://github.com/ValveSoftware/Proton/files/9375487/steam-1184050.log)

**Comment by alosarjos** [comment]
Proton Experimental as 2022/08/19 still failing with stable working. I'm not sure if notifications are send for closed issues, so just in case... @kisak-valve
