### ISSUE TITLE
SFV does not recognize generic control

### ISSUE THREAD

**Issue by dinhokusanagi** [ValveSoftware/Proton#3824]
proton 5.0.7 was released but not to play sfv because the generic control is not recognized by the game
![Captura de tela de 2020-05-03 12-11-13](https://user-images.githubusercontent.com/43162113/80917713-3fb89300-8d37-11ea-95d3-d58ca871aabe.png)
![Captura de tela de 2020-05-03 12-13-15](https://user-images.githubusercontent.com/43162113/80917764-85755b80-8d37-11ea-80e7-4bb043684cac.png)

**Comment by kisak-valve** [comment]
Hello @dinhokusanagi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/400#issuecomment-622994580.

You've clearly communicated this information multiple times. Please do not intentionally open duplicate issue reports.

**Comment by dinhokusanagi** [comment]
as there was no response opening a report, with your breath I was satisfied because attention was paid. I am grateful to you
