### ISSUE TITLE
Star Wars: Battlefront (2004) (1058020)

### ISSUE THREAD

**Issue by ProperBrgdbald** [ValveSoftware/Proton#3828]
# Compatibility Report
- Name of the game with compatibility issues: STAR WARS™ Battlefront (Classic, 2004)
- Steam AppID of the game: 1058020

## System Information
- GPU: GTX 750
- Driver/LLVM version: 4.4.0 NVIDIA 340.107
- Kernel version: 4.15.0-20-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 4.11-13, 4.2-9, 5.0-7, Steam Linux Runtime

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.

## Symptoms 
_For ease, I've replicated a submission to Steam Support, who referred me here._

I purchased and installed Star Wars: Battlefront. It appears to have downloaded the full game (~3GB) and then its appropriate Proton version. I tried running the game using Proton 4.11-13. A black window appeared, then disappeared.

I tried again using Proton 4.2-9. An error prompt stating "Steam must be running to play this game" and "or you don't own this game" appeared.

I tried again using Proton 5.0-7, and a black window appeared, then disappeared.

I tried again using the Steam Linux Runtime option, and was given the warning that the .exe in /home/<user>/.steam/steam/steamapps/common/Star Wars Battlefront (Classic 2004)/ did not exist.

Further inspection shows that the folder is completely empty.

Following this page (https://support.steampowered.com/kb_article.php?ref=2274-IFLV-5334):
I've restarted my computer.
I've cleared the download cache. This step had no effect on starting or downloading the game. Uninstalling and then re-installing creates a folder for the game and then the download promptly ends.
I've attempted to repair the library folder by verifying my game cache (it promptly completed with no errors).
I've changed my download region. This has no effect on the download: uninstalling and then re-installing creates a folder for the game and then the download promptly ends.
I do not want to re-install steam and need to re-download all games.
I do not want to install the game in an alternate folder.

It appears that the Steam Linux Runtime option clears all files from my game folder location.

Re-testing using Proton 4.11-13, the game files downloaded, and the game appeared to be ready to run. When I pressed play, a black window appeared, then disappeared.

Re-testing using Proton 4.2-9, the game files downloaded after clearing the download cache again, and the game appeared to be ready to run. This time I received an error prompt stating "Steam must be running to play OR you does not own this game!" (attached). A restart of the computer did not help.
![Steam Running Owning Game 2020-05-02](https://user-images.githubusercontent.com/64764903/80936084-6f41bc80-8d84-11ea-965a-05868f2be736.png)

Logs per Proton version are attached.

[steam-1058020 (4.2-9).log](https://github.com/ValveSoftware/Proton/files/4572786/steam-1058020.4.2-9.log)
[steam-1058020 (4.11-13).log](https://github.com/ValveSoftware/Proton/files/4572787/steam-1058020.4.11-13.log)
[steam-1058020 (5.0-7).log](https://github.com/ValveSoftware/Proton/files/4572788/steam-1058020.5.0-7.log)

## Reproduction
Install, then attempt to run through Steam. 
Force appropriate version of Proton (in order to match ProtonDB's recommendations).

**Comment by kisak-valve** [comment]
Hello @ProperBrgdbald, nVidia 340.xxx is older than the [minimum requirements](https://github.com/ValveSoftware/Proton/wiki/Requirements#nvidia) for Proton. It appears you're using an Ubuntu 16.04 based system, which may cause additional due to the age of the release.

As a side note, the Steam Linux Runtime compatibility tool is a container runtime for Linux games on Linux. If there isn't a native linux variant of a game, that's the expected result for that tool.

**Comment by ProperBrgdbald** [comment]
Reason for 340.107 was that games I've previously tried, including Star Wars: Battlefront II (2005), successfully ran without issues. Rhetorically, did I miss updates to Battlefront (I just purchased)?

It appears that updating to nvidia 435.21 drivers solve the issue. My second test running with Proton 4.11-13 functions. For documentation's sake, the log is here: 
[steam-1058020 (4.11-13 nvidia 435.21).log](https://github.com/ValveSoftware/Proton/files/4578781/steam-1058020.4.11-13.nvidia.435.21.log)

Proton 4.2-9 still gives the windowed error prompt as seen above. The log is here:
[steam-1058020 (4.2-9 nvidia 435.21).log](https://github.com/ValveSoftware/Proton/files/4578774/steam-1058020.4.2-9.nvidia.435.21.log)

I'll submit reports to ProtonDB for information's sake regarding both the above success and failure, hopefully this will help the next person like myself.

Thank you for your assistance.
