### ISSUE TITLE
rFactor 2 Demo (400330)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3829]
# Compatibility Report
- Name of the game with compatibility issues: RFactor 2 demo
- Steam AppID of the game: 365960 found in the title folder; however generated log mentions 400330. Maybe one of them is for the demo and the other for the paid version.

## System Information
- GPU: GTX660
- Driver/LLVM version: Mesa 19.2.8 / nvidia 440.59
- Kernel version: 5.3.0
- Link to full system information report as [Gist](https://gist.github.com/): Ubuntu 19.10 for desktops with all updates incl. backports. https://gist.github.com/MartinHerrman/609a7ef9a7f9de7ac8abd3db0e3e6b94
- Proton version: 5.0-7

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
Issue 245 mentions that rFactor2 is working, except force feedback
- [X] that I have checked whether there are updates for my system available.
I have also tried several proton versions and steam beta client.

File attached.

## Symptoms 
Game doesn't run, I only get a black screen for a moment and then it returns to Steam client.

In the logs I also found this: ERROR: Could Not Get Primary Adapter Handle

## Reproduction
1. install ubuntu 19.10 desktop incl. updates and backports
2. install steam either from the ubuntu repository or manual by downloading the steam deb from steam website
3. enable steam play for non supported titles
4. install rfactor 2 demo
5. run it

I have tried:
- several versions of proton
- steam beta client
- on another PC that is running Ubuntu 19.10 as well, but has an AMD2400G with internal graphics. Same issue.

[steam-400330.log](https://github.com/ValveSoftware/Proton/files/4574352/steam-400330.log)

**Comment by kisak-valve** [comment]
Hello @MartinHerrman, looks like this game would benefit from d3dcompiler maturing.

**Comment by ghost** [comment]
Hi @kisak-valve, you propose to update the ddl file as described [here](https://forum.studio-397.com/index.php?threads/rfactor-2-works-in-linux-via-steam-play.61021/#post-968766)? I forgot to mention, but I tried it and it didn't help :-(

**Comment by ghost** [comment]
Before installing steam I was playing around with wine. Assumption: maybe steam is confused with this additional wine install. So I did an apt-get remove wine wine64 followed by apt-get autoremove. Many 32-bit libraries were removed as well.

When launching steam:

Pins potentially out-of-date, rebuilding...
Found newer runtime version for 64-bit libdbusmenu-glib.so.4. Host: 4.0.12 Runtime: 4.0.13
Found newer runtime version for 64-bit libvulkan.so.1. Host: 1.1.114 Runtime: 1.2.135
Forced use of runtime version for 64-bit libcurl.so.4. Host: 4.5.0 Runtime: 4.2.0
Found newer runtime version for 64-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004

But still no change: rfactor2 doesn't run.

**Comment by ghost** [comment]
On the rfactor discord channel I was advised to try the full game, the code in the demo is a bit outdated while everyone else has good experiences with the full game.

**Comment by ghost** [comment]
"Solved" it! I bought the full version of the game and that worked out of the box with latest proton.
