### ISSUE TITLE
Mordhau : Compatibility issue

### ISSUE THREAD

**Issue by htjan** [ValveSoftware/Proton#3830]
# Compatibility Report
- Name of the game with compatibility issues: Mordhau
- Steam AppID of the game: 629760

## System Information
- GPU: VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti PRO [Radeon HD 7950/8950 OEM / R9 280]
- Driver/LLVM version:  Mesa 19.1.2 - padoka PPA (LLVM 8.0.0)
- Kernel version: 5.4.0-0.bpo.4-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/htjan/987e32af503947a8e66e560a4569f72a
- Proton version: 5.0-7, 4.11-13, 4.2-9, 3.16-9, Proton-5.2-GE-2, Proton-5.4-GE-3, Proton-5.6-GE-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-629760.log](https://github.com/ValveSoftware/Proton/files/4575022/steam-629760.log)

## Symptoms 
Hi,
I can't start Mordhau. When I launch the game, it crashes in less than a second. 
Steps :
- Open Steam
- Select Mordhau
- Press the "play" button.
- The play button turns to a "stop" button for less than a second
- The button turns back to the play button.
- Neither Mordhau screen nor error message are displayed.
I tried several Proton version, including some Glorious Eggroll one's without any succes, and experiencing the same problem.

## Reproduction
On steam, select Mordhau then press play.

**Comment by kisak-valve** [comment]
Hello @htjan, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2629#issuecomment-623485348.

**Comment by htjan** [comment]
Hi @kisak-valve,
my bad, thanks for the transfer.
