### ISSUE TITLE
Release Final Fantasy X/X-2 HD remaster as 64 bit or with Large Address Aware support

### ISSUE THREAD

**Issue by gdonval** [ValveSoftware/Proton#3832]
- Game: Final Fantasy X/X-2 HD remaster
- Steam AppID of the game: 359870

## Problem

The problem is described at length in https://github.com/doitsujin/dxvk/issues/263: basically that 32-bit game runs out of Video RAM because of both inefficiencies and DXVK and different VRAM layout in Linux compared to Windows. See https://github.com/doitsujin/dxvk/issues/1318#issuecomment-574464662 (and full issue) for more context, noting that what applies to D9VK does apply to DXVK.

## Common mitigation does not work

Large Address Aware (LAA), now activated by default in Proton, is commonly used to increase memory limits in 32-bit applications. However it **does NOT work** in this game. Activation triggers a soft crash: the game mechanics is stuck on specific, reproducible, conditions necessary for the gameplay.

## Actions

The point of this bug request is to ask both:

- to invest in some work in DXVK's memory allocator to collect and defragment memory (long term solution for all 32 bit games out there that can't make use of DXVK);
- and kindly ask Square Enix to release that specific game in 64-bit (or at the very least, fix their pointers so that LAA becomes possible).

## System Information
- GPU: 5700XT (but internet reports with nvidia and other amd cards as well)
- Driver/LLVM version: Mesa 20.0
- Kernel version: 5.6.10
- Proton version: 5.0-7

## Compatibility report?

I don't consider this to be a compatibility report: I'm kindly asking you to contact Square Enix to see if they can fix their game for Proton in very specific ways.

**Comment by kisak-valve** [comment]
Hello @gdonval, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/555#issuecomment-624075272.
