### ISSUE TITLE
Implement a more efficient memory manager in DXVK

### ISSUE THREAD

**Issue by gdonval** [ValveSoftware/Proton#3833]
Many 32-bit Proton games are not working because they are running out of Video RAM (address space to be precise). More details in https://github.com/doitsujin/dxvk/issues/1318 (and numbers in https://github.com/doitsujin/dxvk/issues/1318#issuecomment-574464662). Noting that D9VK shares the same limitations as DXVK.

There are many demanding 32-bit games on Steam that do no work because DXVK occupies more memory than native DirectX implementations and does not manage collection and defragmentation as well as its native counterparts.

Large Address Aware (LAA) flag does not always work (see https://github.com/ValveSoftware/Proton/issues/555 for anecdotal example) and LAA might just not be enough. 

Proton is a big DXVK consumer and working on more advanced memory allocation mechanisms within DXVK would help with many Steam games.

**Comment by kisak-valve** [comment]
Hello @gdonval, DXVK memory management should be discussed on the DXVK issue tracker, and as you've pointed out, it's at https://github.com/doitsujin/dxvk/issues/1318. Closing in favor of that issue report.

**Comment by gdonval** [comment]
Oh, now everything makes sense! Proton is just a marketing device... I should have noticed before spending any of my time one this.

**Comment by Ruedii** [comment]
I believe they are saying this is an upstream issue.  File the bug report upstream.

Valve does contribute to the upstream project and they will see it there.
