### ISSUE TITLE
Tekken 7 (389730) used to work, but now doesn't.

### ISSUE THREAD

**Issue by dodgypast** [ValveSoftware/Proton#3838]
#### Your system information

* Steam client version (build number or date):
![Screenshot from 2020-05-07 17-35-43](https://user-images.githubusercontent.com/24266439/81285173-50e00780-9089-11ea-8a97-50285bf895ce.png) 
* Distribution Endeavour OS ( arch based ) 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
a)Click play on Tekken 7 button from the library page.
b)Preparing to play window opens, then closes.

The only non-native Steam game that I have found that works is Bastion. The Witcher 3 and Sekiro have the same behaviour.

Below is the output in the terminal:
`Loaded Config for Local Selection Path for App ID 389730, Controller 4: /home/duncanm/.local/share/Steam/steamapps/workshop/content/241100/926870667/838078703168055933_legacy.bin
Loaded Config for Local Override Path for App ID 389730, Controller 4: /home/duncanm/.local/share/Steam//controller_base/empty.vdf
GameAction [AppID 389730, ActionID 4] : LaunchApp changed task to ProcessingInstallScript with ""
/data/src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
/data/src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
/data/src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
/data/src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
Proton: Missing or invalid openvrpaths.vrpath file! [Errno 2] No such file or directory: '/home/duncanm/.config/openvr/openvrpaths.vrpath'
wine: /MyMedia/Steam/steamapps/compatdata/389730/pfx is not owned by you
GameAction [AppID 389730, ActionID 4] : LaunchApp changed task to SynchronizingCloud with ""
Proton: Missing or invalid openvrpaths.vrpath file! [Errno 2] No such file or directory: '/home/duncanm/.config/openvr/openvrpaths.vrpath'
wine: /MyMedia/Steam/steamapps/compatdata/389730/pfx is not owned by you
GameAction [AppID 389730, ActionID 4] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 389730, ActionID 4] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 389730, ActionID 4] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 389730, ActionID 4] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 389730 "", ProcID 280785, IP 0.0.0.0:0
Starting app 389730
Loaded Config for Local Selection Path for App ID 389730, Controller 4: /home/duncanm/.local/share/Steam/steamapps/workshop/content/241100/926870667/838078703168055933_legacy.bin
ERROR: ld.so: object '/home/duncanm/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Loaded Config for Local Override Path for App ID 389730, Controller 4: /home/duncanm/.local/share/Steam//controller_base/empty.vdf
>>> Adding process 280785 for game ID 389730
GameAction [AppID 389730, ActionID 4] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/duncanm/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/duncanm/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 389730, ActionID 4] : LaunchApp changed task to Completed with ""
>>> Adding process 280786 for game ID 389730
Proton: Missing or invalid openvrpaths.vrpath file! [Errno 2] No such file or directory: '/home/duncanm/.config/openvr/openvrpaths.vrpath'
ERROR: ld.so: object '/home/duncanm/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wine: /MyMedia/Steam/steamapps/compatdata/389730/pfx is not owned by you
ERROR: ld.so: object '/home/duncanm/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/duncanm/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
wine: /MyMedia/Steam/steamapps/compatdata/389730/pfx is not owned by you
>>> Adding process 280787 for game ID 389730
>>> Adding process 280788 for game ID 389730
Game removed: AppID 389730 "", ProcID 280785 
Uploaded AppInterfaceStats to Steam
Exiting app 389730
No cached sticky mapping in ActivateActionSet.No cached sticky mapping in ActivateActionSet.
`

**Comment by kisak-valve** [comment]
Hello @dodgypast, we're tracking issues with games that are run with Proton in the Proton issue tracker, so I've moved this issue report over.

Glad to hear you got this working. As far as I'm aware, Proton doesn't mess with the ownership of files, so we'd need a decent hint and steps to reproduce the issue to ponder what happened here. We do know that wine, and by extension Proton, requires that the wine prefix is owned by the current user to avoid an entire category of annoying to troubleshoot issues.

If you find some hints, let me know and we can re-open this issue report.
