### ISSUE TITLE
Steam Star Wars Empire at War: Gold Pack Loading Issues

### ISSUE THREAD

**Issue by timlfuller2nd** [ValveSoftware/Proton#3842]
# Compatibility Report
- Name of the game with compatibility issues: Star Wars Empire at War: Gold Pack
- Steam AppID of the game: 32470

## System Information
- GPU:  AMD® Aruba A10-5750m apu with radeon(tm) hd graphics × 4
- Driver/LLVM version:  Mesa 18.2/7.0.0
- Kernel version:   4.15.0-99-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.0-7

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @timlfuller2nd, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/584#issuecomment-625559300.
