### ISSUE TITLE
Games are being dowloaded with incorrect permissions to a mounted nfs share

### ISSUE THREAD

**Issue by dodgypast** [ValveSoftware/Proton#3846]
#### Your system information

* Steam client version (build number or date): 
![gscreenshot_2020-05-08-161031](https://user-images.githubusercontent.com/24266439/81390966-8b5baa00-9146-11ea-8c3e-ca5edca19ef0.png)
* Distribution (e.g. Arch): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
When I try to run a game for the first time it cannot install the VC_Redists etc, it fails with the error:
`wineserver: /MyMedia/Steam/steamapps/compatdata/1072500/pfx is not owned by you`
If I run `sudo chown -R duncanm /MyMedia/Steam` it then works.
BUT
When I install another game to the same share it fails again and I have to rerun the permissions.

#### Steps for reproducing this issue:

1. Mount an NFS share
2. Download a game to the share
3. Try and run the game

**Comment by kisak-valve** [comment]
Hello @dodgypast, the wine prefix used by Proton is setup locally, and I suspect this is most likely an issue with how the filesystem is mounted. What are the mount options used with /MyMedia/Steam?

**Comment by dodgypast** [comment]
Thanks for looking into this for me.

The fstab line is:
`192.168.1.153:/mnt/user/MyMedia	/MyMedia	nfs	defaults	0	0`

I did dig around enoungh to know uid= doesn't work with nfs mounting.

**Comment by kisak-valve** [comment]
Maybe the uid mapping on the server doesn't match the client? (https://unix.stackexchange.com/a/9474)

If this is the case, then it looks like you can make adjustments with `/etc/nfs.map` (https://stackoverflow.com/a/27769444)

**Comment by dodgypast** [comment]
I've fixed it with the following in /etc/exports of the fileserver:
`"/mnt/user/MyMedia" -async,no_subtree_check,fsid=100 (sec=sys,rw,insecure,all_squash,anongid=1000,anonuid=1000)`
