### ISSUE TITLE
Proton 5.0-x USB EXT4 crash

### ISSUE THREAD

**Issue by arrowgent** [ValveSoftware/Proton#3847]
Proton 5.0-6+ Launching games from USB EXT4 ssd will launch crash 100% of the time

forcing proton 4.11 works fine using USB EXT4
proton 5.0-5 previous was working fine

confirmed this moving game from SATA SSD (EXT4) to USB SSD (EXT4)
tested several games

proton log was not helpful in diagnosing an error.

**Comment by BillFleming** [comment]
Have you verified that you are using the same mount options and permissions on the folders from top level down to the steam folders?

**Comment by arrowgent** [comment]
/dev/sdb3 on /home type ext4 (rw,noatime,errors=remount-ro,stripe=32718,data=ordered)
/dev/sda1 on /media/catbox/CrucialXTB type ext4 (rw,nosuid,nodev,relatime,stripe=8191,uhelper=udisks2)

the USB is auto mounted, i dont add any fstab options for the USB drives
and yes all of these are the same user:group rwxrwxrwx 0777 for example
