### ISSUE TITLE
Secret World Legends (215280) Not close properly

### ISSUE THREAD

**Issue by OursBlanc42** [ValveSoftware/Proton#3848]
# Compatibility Report
- Name of the game with compatibility issues: Secret World LEgend
- Steam AppID of the game: 215280

## System Information
- GPU: **NVIDIA GeForce GTX970**
- Driver/LLVM version: **nvidia-driver-440 (version 440.82-0ubuntu0~0.18.04.1)**
- Kernel version: **5.3.0-51-generic**
- Link to full system information : https://gist.github.com/Hennel/9b3f0ad72c28a96372880d03df1f59c5
- Proton version: **4.2-9**

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

Proton Log : 
https://gist.github.com/Hennel/c71c2de4248264d7b44f7296049bb754

## Symptoms 
Once the game is shut down, it does not close properly. Steam continues to indicate it as "in progress" and cannot be stopped. (Except by killing the process)

## Reproduction
Launch the game, quit the game, keep an eye on Steam.

sorry for my dirty english and for my no knowledge about proton and github.
thank.

**Comment by kisak-valve** [comment]
Hello @Hennel, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1511#issuecomment-625985707.
