### ISSUE TITLE
Rising Storm/Red Orchestra 2 Game crashes on multiplayer section (35450)

### ISSUE THREAD

**Issue by MuhammedKpln** [ValveSoftware/Proton#385]
Single trainin mode works perfectly but when i try to go in todo multiplayer mode game crashes. Same happens on Mirage: Arcane Warfare.

Deepin 15.7
Proton 3.7
Nvidia 390.67

System information from Steam:
https://gist.github.com/MuhammedKpln/b219c1b2fb76b5219c1908bd902918e4

**Comment by ghost** [comment]
You should update you NVIDIA driver take a look to https://github.com/doitsujin/dxvk/wiki/Driver-support

**Comment by kisak-valve** [comment]
Hello @MuhammedKpln, this issue is already being tracked at #155. Closing as a duplicate.
