### ISSUE TITLE
Delores: A Thimbleweed Park Mini-Adventure (1305720)

### ISSUE THREAD

**Issue by arrowgent** [ValveSoftware/Proton#3854]
# Compatibility Report
https://store.steampowered.com/app/1305720/Delores_A_Thimbleweed_Park_MiniAdventure/
- Name of the game with compatibility issues: Delores: A Thimbleweed Park Mini-Adventure 
- Steam AppID of the game:1305720

## System Information
- Proton version: 4-11 & 5.0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.

## Symptoms 
Requires Windows 10 popup box (ok) and closes

does not run.

**Comment by Funatiker** [comment]
> Requires Windows 10 popup box (ok) and closes

This symptom can be cured easily. Just start the `winecfg` in the game's prefix and set the operating system from Windows 7 to Windows 10. Like this: `WINEPREFIX=$HOME/.steam/steamapps/compatdata/221380/pfx wineprefix`

Then, the popup box doesn't open, the game window appears, and immediately disappears. Log file attached.
[steam-1305720.log](https://github.com/ValveSoftware/Proton/files/4612422/steam-1305720lol.log)

**Comment by kisak-valve** [comment]
Hello @Funatiker, `err:module:import_dll Library d3d12.dll (which is needed by L"Z:\\home\\$USER\\.steam\\steamapps\\common\\Delores\\ZiplineLT.dll") not found` is a line of interest in the log. Please retest with Proton 5.0.

**Comment by Funatiker** [comment]
@kisak-valve Thank you for your quick reply.
> Please retest with Proton 5.0.

Now it does not crash but it shows a dialog box saying “Critical Error!” with the text “Your graphics card does not support the DirectX 12 features the game requires.” and a button OK that ends the process.

[steam-1305720_proton5.log](https://github.com/ValveSoftware/Proton/files/4614517/steam-1305720_proton5.log)

**Comment by Sebastiangperez** [comment]
Same here , i got the same message.

**Comment by Funatiker** [comment]
> Same here , i got the same message.

The Windows 10 Message? Set your Windows version to Windows 10 in winecfg, and Proton to Proton 5 in steam. Then you will get the message that your graphics card doesn't support DirectX Features.

**Comment by Sebastiangperez** [comment]
> > Same here , i got the same message.
> 
> The Windows 10 Message? Set your Windows version to Windows 10 in winecfg, and Proton to Proton 5 in steam. Then you will get the message that your graphics card doesn't support DirectX Features.


Both , the first message, then i changed the windows version and now appear the DirectX message. 
Sorry if i wasn't clear in my comment.

**Comment by lavadrop** [comment]
I'm getting this error instead:

Critical error

ZLDX12Shader: Failed to compile a cs_5_1 shader. (error 8876086C)
Unknown Error

Also, if I use Proton-GE with vkd3d, now it complains about: “Your graphics card does not support the DirectX 12 features the game requires.”

**Comment by purpleidea** [comment]
I'm confused because the homepage for the game say "Linux" but it's not seemingly available... Anyone know what's going on? Cheers!

**Comment by tocsinde** [comment]
> I'm confused because the homepage for the game say "Linux" but it's not seemingly available... Anyone know what's going on? Cheers!

Thimbleweed Park is indeed released for Linux, but this issue is about the spinoff "Delores". It has been released for Windows and macOS only.

**Comment by joshas** [comment]
Good news, there's an official Linux post-alpha, pre-beta build of Delores: https://forums.thimbleweedpark.com/t/open-beta-testing/4482

**Comment by arrowgent** [comment]
Proton 5.0-x

**Install d3dcompiler_47 with winetricks:**

proton version loaded successfully
i literally only played the game for 1 minute to verify it loaded


discussions and answer found in:
https://steamcommunity.com/app/1305720/discussions/0/2246677986017458955/

issue otherwise is now closed, they have a working Linux version out
