### ISSUE TITLE
Proton on OSX ?

### ISSUE THREAD

**Issue by stuaxo** [ValveSoftware/Proton#3855]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Wine builds on OSX, could Proton come to OSX ?

## Justification [optional] 
Being able to run more games from Steam in OSX must be a good idea.

**Comment by kisak-valve** [comment]
Hello @stuaxo, this is already being tracked at #1344. Closing as a duplicate.

**Comment by stuaxo** [comment]
Thanks :)
