### ISSUE TITLE
D9VK never works, even though DXVK works with DirectX 11.

### ISSUE THREAD

**Issue by gardenappl** [ValveSoftware/Proton#3857]
I recently tried Proton 5.0-7 and found that DirectX 9 games just do not launch.

The Steam log says `Required Vulkan extension VK_KHR_surface not supported`. I know for a fact that it should be supported because a) `vulkaninfo` says so and b) I've been playing DirectX 11 games using Proton with no issues.

Affected games:

- GTA San Andreas - log [here](https://gist.github.com/gardenappl/2382af45783e20fde075f308544a3926)
- Need for Speed: Hot Pursuit (2010) - log [here](https://gist.github.com/gardenappl/18e0edddd6e48804fade406d836589a9)

System information as reported by Steam: https://gist.github.com/gardenappl/fb90c9300a3834321700788ba3529156

Vulkaninfo output: https://gist.github.com/gardenappl/d7df3ddc08790008c1ce10233e8e44a4

Using Arch Linux.

**Comment by kisak-valve** [comment]
Hello @gardenappl, your system information indicates you do not have a vulkan 32 bit userspace driver installed for your video card. Please verify that the `lib32-vulkan-radeon` package is installed.

**Comment by gardenappl** [comment]
@kisak-valve Whoops, I just installed it and that fixed the problem. Thanks for the quick reply!
