### ISSUE TITLE
Age of empires II: Definitive edition sync error while playing online 

### ISSUE THREAD

**Issue by pablovivo98** [ValveSoftware/Proton#3858]
# Compatibility Report
- Name of the game with compatibility issues: Age of empires 2: Definitive Edition
- Steam AppID of the game: 813780

## System Information
- GPU: NVIDIA Corporation GeForce 940M/PCIe/SSE2
- Driver/LLVM version: 4.6.0 NVIDIA 440.82
- Kernel version: 4.15.0-88-generic
- Link to full system information report: https://gist.github.com/pablovivo98/b747c622eba2cc3bb0406284e99f6cbc
- Proton version: 4.11-13

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms  Hi, I bought Age Of Empires 2: Definitive Edition via steam, and everithing it's okay but I CAN'T play multiplayer games. It crashes 15 seconds after starting multiplayer game, with an "sync error" report (attached pic)
![Captura de pantalla de 2020-05-12 18-53-08](https://user-images.githubusercontent.com/65252684/81740289-07365900-949d-11ea-9399-08958169d121.png). I have already applied the multiplayer fix, changed my 5.0-7 version to older and restarted both steam and my computer. I'm truly new here and I don't now what to do. Thanks a lot for your help.

**Comment by kisak-valve** [comment]
Hello @pablovivo98, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3189#issuecomment-627573119.
