### ISSUE TITLE
can't use windows version of linux ported games

### ISSUE THREAD

**Issue by olaulau** [ValveSoftware/Proton#386]
some linux ported games have very bad performance.
it may be worth testing their windows version through proton, it may be a better alternative someday !

examples : ARK survival evolved, ARK Survival of the fittest, Counter Strike Global Offensite ...

**Comment by pprotonrep** [comment]
This'd be a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5638#issuecomment-415720168

**Comment by olaulau** [comment]
yes it's a duplicate, thanks.
