### ISSUE TITLE
Missing images in Path of Exile when using Ubuntu 20.04

### ISSUE THREAD

**Issue by robert-olofsson** [ValveSoftware/Proton#3861]
# Compatibility Report
- Name of the game with compatibility issues: Path of Exile
- Steam AppID of the game: 238960

## System Information
- GPU: Radeon RX Vega M GH  (Intel hades canyon nuc)
- Driver/LLVM version: whatever is in ubunutu 20.04 (20.0.4, 
- Kernel version: 5.4.0-28-generic
- Proton version: Proton 5.0, version-file say: 1588350139 proton-5.0-7-rc3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms
Missing pictures in game. Most visible on the startup screen where the current info images
are missing and in the game the minimap do not show extras on top of it. 

## Reproduction
Start game.  look at login screen

Starting from console I see a few log lines like:
0024:err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng12.so.0

Look around and notice that modern ubuntu uses libpng16 and does not have an easy libpng12. It is available in a PPA though and installing it solves the issue.

Would be good to build with a more modern libpng.

**Comment by kisak-valve** [comment]
Hello @robert-olofsson, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/58#issuecomment-628102625.
