### ISSUE TITLE
World of Warships (0.9.4) UI broken.

### ISSUE THREAD

**Issue by rogowskys** [ValveSoftware/Proton#3862]
After the latest World of Warships update - 0.9.4 - the GUI is missing items and in places corrupt (see images).  Specifically the Top Bar, Modules and "Tech Tree"
![Screenshot from 2020-05-13 16-00-10](https://user-images.githubusercontent.com/39506451/81857789-2256a680-9539-11ea-8505-870247f18481.png)
 

The following was tried, with NO EFFECT:

- Proton 5.0-7 (default) and Proton 4.11 

- Mesa 20.0.6 and 20.2 git ( to rule out RADV or radeonsi)

- Fedora kernel 5.6.11 and xxmitsu 5.6.0-amdgpu-next (to rule out amdgpu)

- PROTON_USE_WINED3D=1 ( to rule out DXVK)

Local steam files were verified - ok.  I verified that the game loads and displays the GUI just fine using Steam on Windows.  Previous WoWs versions 0.9.3 also exhibited random crashes that I could not track down.

**Comment by kisak-valve** [comment]
Hello @rogowskys, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/333#issuecomment-628210049.
