### ISSUE TITLE
Gallium nine patches dont work.

### ISSUE THREAD

**Issue by Oczkins92** [ValveSoftware/Proton#3863]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: AMD Mars XTX [Radeon HD 8790M]/Mesa DRI Intel HD Graphics 4600 (HSW GT2)
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.0-7 and olders

Hi i have problem to launch gallium nine patches.I have tried like on this post:https://www.reddit.com/r/SteamPlay/comments/b6xpg9/proton_gallium_nine_standalone_dx9/ and add option PROTON_USE_GALLIUM_NINE=1 %command%  but all games running in DXVK.Only one version of proton working with gallium patches - it's Proton 3.16 with gallium nine patches but is not supported anymore.

**Comment by kisak-valve** [comment]
Hello @Oczkins92, gallium nine is not supported, and wasn't supported previously.

There's a feature request at #66 tracking the request for integration.

**Comment by Oczkins92** [comment]
Ok thank you for reply.I am asking because when i use D9Vk perfomance in games are terrible compared to gallium nine.
