### ISSUE TITLE
Grafik Bug and Problems with Uplay.

### ISSUE THREAD

**Issue by 19Topgun93** [ValveSoftware/Proton#3864]
Hello,

I have to Problems. Number one is that Migh & Magic VII says, "Unable to locate Uplay PC" "Please Reinstall Uplay PC"
How can I get Uplay for Proton?

Number 2 is:

I have update on Ubuntu 20.04 LTS and I have Grafik Bugs. There are serveralls games like Heroes of Migh & Magic 3 Civ 6 and Stardew Valley. I don't have so much games on this PC, so I have a couple of Screenshots.

Best Regrads

Lukas
![Bildschirmfoto vom 2020-05-14 13-42-30](https://user-images.githubusercontent.com/41064191/81930722-42de3980-95e9-11ea-9933-0a3c531e8dab.png)
![Bildschirmfoto vom 2020-05-14 13-42-12](https://user-images.githubusercontent.com/41064191/81930725-4376d000-95e9-11ea-8583-f4d86a28e611.png)
![Bildschirmfoto vom 2020-05-14 13-41-11](https://user-images.githubusercontent.com/41064191/81930727-440f6680-95e9-11ea-8e0a-9b21ebb5eae1.png)
![Bildschirmfoto vom 2020-05-14 13-40-35](https://user-images.githubusercontent.com/41064191/81930732-44a7fd00-95e9-11ea-9415-ec6502ca6407.png)
![Bildschirmfoto vom 2020-05-14 13-40-20](https://user-images.githubusercontent.com/41064191/81930734-45409380-95e9-11ea-9fc1-00d8cd926e0e.png)

**Comment by kisak-valve** [comment]
Hello @19Topgun93, graphical issues need to be investigated on a per-game basis. Also, friendly note that we're using one issue report per unofficially supported game title. I'd appreciate if you search the existing compatibility reports for the game you're seeing issues with, then add the quirk you're seeing, the Proton version, and your system information from Steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/) to a comment on the existing compatibility report.

Civilization VI and Stardew Valley are native linux games, so if you're seeing rendering issues with them, it's more likely that you're encountering a video driver issue.

The HoMM7 issue with uplay is already described and has a workaround at #3005.
