### ISSUE TITLE
Path of Exile: CreateShaderResourceViewEx: Invalid parameter

### ISSUE THREAD

**Issue by Opencode-foss** [ValveSoftware/Proton#3868]
# Compatibility Report
- Name of the game with compatibility issues: Path of Exile
- Steam AppID of the game: 238960

## System Information
- GPU: i7-4790K Intel HD Graphics
- Driver/LLVM version: Intel Open Source Technology Center Mesa DRI
Intel(R) HD Graphics 4600 (HSW GT2)
3.0 Mesa 20.0.6
- Kernel version: 5.6.11-arch1-1 x86_64
- Link to full system information report as [Gist](https://gist.github.com/): [systemreport.txt](https://github.com/ValveSoftware/Proton/files/4630090/systemreport.txt)
- Proton version: 5.0-7

## I confirm:
- [ I confirm] that I haven't found an existing compatibility report for this game.
- [ I confirm] that I have checked whether there are updates for my system available.

[steam-238960.log](https://github.com/ValveSoftware/Proton/files/4630091/steam-238960.log)

## Symptoms 
When I am loading into a game it crashes and gives me a CreateShaderResourceViewEx: Invalid parameter exception.
Found it log file: "[CRIT Client 192] [D3D11] CreateShaderResourceViewEx: Invalid parameter."

**Comment by kisak-valve** [comment]
Hello @Opencode-foss, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/58#issuecomment-628793877.
