### ISSUE TITLE
Dxvk reporting time in utc rather than local?

### ISSUE THREAD

**Issue by LizziAS** [ValveSoftware/Proton#3869]
# Compatibility Report
- ESO - works great except for whn i used an addon called libdebuglogger
- Steam AppID of the game:i dont know that  306130?

## System Information
sudo inxi -Fxzmc0

System:    Host: manjaroed Kernel: 5.6.13-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.1.0 Desktop: MATE 1.24.0 
           Distro: Manjaro Linux 
Machine:   Type: Desktop System: Gigabyte product: AB350M-DS3H v: N/A serial: N/A 
           Mobo: Gigabyte model: AB350M-DS3H-CF v: x.x serial: N/A UEFI [Legacy]: American Megatrends v: F50a date: 11/27/2019 
Battery:   Device-1: hidpp_battery_0 model: Logitech M570 charge: 90% status: Discharging 
           Device-2: hidpp_battery_1 model: Logitech Wireless Keyboard K360 charge: 55% (should be ignored) 
           status: Discharging 
Memory:    RAM: total: 15.65 GiB used: 2.92 GiB (18.7%) 
           Array-1: capacity: 128 GiB slots: 4 EC: None max module size: 32 GiB note: est. 
           Device-1: DIMM 0 size: No Module Installed 
           Device-2: DIMM 1 size: 8 GiB speed: 3000 MT/s type: DDR4 
           Device-3: DIMM 0 size: No Module Installed 
           Device-4: DIMM 1 size: 8 GiB speed: 3000 MT/s type: DDR4 
CPU:       Topology: Quad Core model: AMD Ryzen 5 2400G with Radeon Vega Graphics bits: 64 type: MT MCP arch: Zen 
           L2 cache: 2048 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 57513 
           Speed: 1421 MHz min/max: 1600/3600 MHz Core speeds (MHz): 1: 1420 2: 1420 3: 1460 4: 1523 5: 1592 6: 1405 7: 1486 
           8: 1426 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] vendor: ASRock 
           driver: amdgpu v: kernel bus ID: 01:00.0 
           Display: server: X.Org 1.20.8 driver: amdgpu,ati unloaded: modesetting resolution: 1920x1080~60Hz 
           OpenGL: renderer: Radeon RX 570 Series (POLARIS10 DRM 3.36.0 5.6.13-1-MANJARO LLVM 10.0.0) v: 4.6 Mesa 20.0.6 
           direct render: Yes 
Audio:     Device-1: AMD Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590] vendor: ASRock driver: snd_hda_intel v: kernel 
           bus ID: 01:00.1 
           Device-2: Advanced Micro Devices [AMD] Family 17h HD Audio vendor: Gigabyte driver: snd_hda_intel v: kernel 
           bus ID: 0a:00.6 
           Sound Server: ALSA v: k5.6.13-1-MANJARO 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Gigabyte driver: r8169 v: kernel 
           port: e000 bus ID: 05:00.0 
           IF: enp5s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel port: e000 bus ID: 08:00.0 
           IF: wlp8s0 state: down mac: <filter> 
Drives:    Local Storage: total: 1.37 TiB used: 362.41 GiB (25.9%) 
           ID-1: /dev/nvme0n1 model: Sabrent Rocket Q size: 931.51 GiB 
           ID-2: /dev/sda vendor: SanDisk model: Ultra II 500GB size: 465.76 GiB 
           ID-3: /dev/sdb type: USB vendor: Generic model: Flash Disk size: 1.92 GiB 
Partition: ID-1: / size: 48.97 GiB used: 26.20 GiB (53.5%) fs: ext4 dev: /dev/nvme0n1p3 
           ID-2: /boot size: 968.3 MiB used: 186.0 MiB (19.2%) fs: ext4 dev: /dev/nvme0n1p2 
           ID-3: /home size: 865.62 GiB used: 208.49 GiB (24.1%) fs: ext4 dev: /dev/nvme0n1p4 
Sensors:   System Temperatures: cpu: 43.0 C mobo: N/A gpu: amdgpu temp: 35 C 
           Fan Speeds (RPM): N/A gpu: amdgpu fan: 1495 
Info:      Processes: 331 Uptime: 8m Init: systemd Compilers: gcc: 10.1.0 clang: 10.0.0 Shell: bash v: 5.0.16 inxi: 3.0.37 

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.  
The game works.
- [ ] that I have checked whether there are updates for my system available.
I am up to date with the latest version of the game and with proton and dxvk

Have no idea whgat that is

## Symptoms 
2 things. When playing with the addon libdebuglogger which is used for many other addons, the time in game shifts from my local system time to UTC

Also when trying to use mangohud Vulkan reports time in utc but opengl reports local system time

https://lh3.googleusercontent.com/UOJaNfyNyTg7ZNlrD6fCxK4kfHnZI5vabkITO2w2UN05zTGVL2NaAgnsppXXpusKfEo-Pwc8RWmt9POfP3CMxSH9IfTP9dUWmxsI0yeXfN4Mom-X3JW7q_Tenzh9fjdljsCdvr5mrg=w2400

https://lh3.googleusercontent.com/a36uOuiIpgi0iS1WHqysA3f9ikTfRh4mvbxnD05Z-yswLXa-08pEVc0uTHnMUuycZrP5OAVuy-8xCRbKlQZb7aT6Ng_S-ZKd9F37yTlhAOr2FgQBj_vrtAklhP4gLVEUvbhUgJpDvA=w2400

Something seems wonky with dxvk i think?  but i dont know anyone else having this issue so maybe its something with my system hardware?  i have the latest bios and the bios is on the correct local time.

I filed a request for for with libdebuglogger at esoui because something in that causes the in time game to shift from local to utc but it isnt just there.  while running mangohud the time in vulkan driver is reported as utc?  but in opengl it is local time?

https://www.twitch.tv/videos/620189454

someone even uderstands what is happening here because i do not...  i tried to switch my rtc to local time and rebooted but no improvement...

**Comment by kisak-valve** [comment]
Hello @LizziAS, please use [DXVK's issue tracker](https://github.com/doitsujin/dxvk/issues) for issues issues with DXVK's overlay.

**Comment by doitsujin** [comment]
DXVK does not report any time at all, so quite franky I have no idea what you're talking about.

Edit: Looks like you're using MangoHud, maybe report a bug [here](https://github.com/flightlessmango/MangoHud) instead.

**Comment by kisak-valve** [comment]
Thanks @doitsujin, closing because MangoHud is outside of this project.

**Comment by LizziAS** [comment]
mangohud is only exposing the error.  i dont know where the error lies.  but it is something wonky for sure to see my in game time switching....  the fact that two programs, klibdebuglogger and mango hub are both showing the same symptom suggests the problem lies outside of both programs...

**Comment by LizziAS** [comment]
i reported a bug with mangohud and with esoui, and her and on manjaro forums and even on r/linux_gaming... as wall as now with dxvk....

**Comment by LizziAS** [comment]
honestly i suspect everyone will pass the buck on this but i have no idea what is really happening
