### ISSUE TITLE
DPI info is not configurable/does not get passed to game properly

### ISSUE THREAD

**Issue by Semperverus** [ValveSoftware/Proton#3870]
Tested on all currently available versions of proton.

This issue affects games that have DPI scaling options or are generally DPI-aware, such as Guild Wars 2. DPI scaling works perfectly fine under normal WINE after setting DPI in the winecfg menu, but when running winecfg on the proton wineprefix related both to the game, and to the default proton wineprefix (for games that do not have their own), DPI is not passed along and games do not scale, leaving in-game UIs very small in relative comparison.

Currently running Arch Linux, kernel 5.6.11-arch1-1, on the latest version of KDE plasma, and latest version of Steam. This has been a persistent issue since Proton came out.

Suggested short-term fix: Add a Proton parameter such as `PROTON_DPI=96` for manually overriding

**Comment by Semperverus** [comment]
This was due to my error. I still suggest adding an override flag to make it easier to set per-game (or add a way to launch winecfg from within the game's settings menu in Steam which targets that game's wineprefix)

I was able to finally get to the proper wineprefix by performing this witchcraft either as a bash script or by copying and pasting each line one by one into a terminal:
```
PROTON_VERSION=5.0
PROTON_DIR=~/.local/share/Steam/steamapps/common
GAMEPFX_DIR=~/.steam/steam/steamapps/compatdata/{REPLACE ME WITH GAME ID}/pfx/
export WINEPREFIX="$GAMEPFX_DIR" WINEARCH=win64
"$PROTON_DIR/Proton $PROTON_VERSION/dist/bin/wine64" 'winecfg.exe'
```

**Comment by sfjuocekr** [comment]
This should really be passed to the game!

**Comment by sophie-la-li** [comment]
I would like to be able to set this per game without witchcraft.

**Comment by emanvidmaker** [comment]
This should definitely be a Launch Option, its my 100% of the time using Proton and its very hard to reach
