### ISSUE TITLE
The controller buttons in Castle Crashers are misplaced

### ISSUE THREAD

**Issue by ketetefid** [ValveSoftware/Proton#3872]
Using a Steam Controller or another controller, I have to reassign some buttons. The game starts and runs fine, but some buttons are misplaced. For example, X is A or, Right Trigger is start and because of this, I have to reassign the keys in the Big Picture mode. I should mention that I did not have this problem and after an update to the steam it has appeared (unfortunately do not know when).
In other games and in the steam client itself, everything is fine, so the problem is confined to this game.
This happens with the current proton i.e., 4.11. The system information and the proton log have been attached.
[steam-204360.log](https://github.com/ValveSoftware/Proton/files/4635864/steam-204360.log)
[SysInfo.log](https://github.com/ValveSoftware/Proton/files/4635865/SysInfo.log)

**Comment by kisak-valve** [comment]
Hello @ketetefid, most likely unrelated, but please rebuild libsdl2 with `USE=haptic` to resolve `err:plugplay:deviceloop_thread Can't init SDL: SDL not built with haptic (force feedback) support` in the log.

**Comment by ketetefid** [comment]
Such a hero.
I have been dealing with this for weeks and did everything in vain. I did not open an issue earlier just because I saw you were already dealing with so many other ones and did not want to increase the burden. But I wish I had done so earlier!
Huge thanks for your swift reply and your solution.
