### ISSUE TITLE
Half-Life: Alyx - Workshop Tools (1295040)

### ISSUE THREAD

**Issue by llamasking** [ValveSoftware/Proton#3874]
# Compatibility Report
- Name of the game with compatibility issues: Half-Life: Alyx - Workshop Tools
- Steam AppID of the game: 1295040

## System Information
- GPU: GTX 980
- Driver/LLVM version: Nvidia 440.82
- Kernel version: 5.6.13-zen
- Link to full system information report: [Gist](https://gist.github.com/llamasking/5e7a6e4060b3534c25d52285de488ec9)
- Proton version: 5.0-7

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-546560.log](https://github.com/ValveSoftware/Proton/files/4637683/steam-546560.log)

## Symptoms
The tools do not launch. There are no windows or popups indicating an error.

**Comment by kisak-valve** [comment]
Hello @llamasking, we're using one issue report per unofficially supported game title, and this is DLC for Half-Life: Alyx, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3681#issuecomment-629630753.
