### ISSUE TITLE
Killing Floor 2 Game crashes before the boss's presentation

### ISSUE THREAD

**Issue by jrrabier** [ValveSoftware/Proton#3876]
# Compatibility Report
- Name of the game with compatibility issues: Killing Floor 2
- Steam AppID of the game: 232090

## System Information
- GPU: GTX 1050
- Driver/LLVM version: 4.6.0 NVIDIA 440.82
- Kernel version: 5.3.0-7648-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/jrrabier/9178379fa0dafcb8c2d8e137c1e3b3e7
- Proton version: 5.0-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
[steam-232090.log](https://github.com/ValveSoftware/Proton/files/4638324/steam-232090.log)

## Symptoms 

Since the release of the latest 5.0-7 proton version, the game crashes just before the boss's presentation (just after the wave announcement), redirecting me to the bug report (i already sent some reports), i had no problems with the previous version (5.0-6), i tried with some custom proton versions (5.6-GE-2, 5.8-GE-1-MF), don't have this bug but another... :)

## Reproduction

Everytime

**Comment by kisak-valve** [comment]
Hello @jrrabier, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1328#issuecomment-629640320.
