### ISSUE TITLE
[The Elder Scrolls V: Skyrim Special Edition] The game's pointer total freeze after Alt+Tab.

### ISSUE THREAD

**Issue by zefkerr** [ValveSoftware/Proton#3877]
# Compatibility Report
- Name of the game with compatibility issues: The Elder Scrolls V: Skyrim Special Edition;
- Steam AppID of the game: 489830

## System Information
- OS: Arch Linux; DE: GNOME 3.36 on Wayland;
- GPU: AMD Radeon HD7850;
- CPU: Intel® Core™2 Duo CPU E8400 @ 3.00GHz × 2 
- RAM: 8GB DDR3
- Driver/LLVM version: Mesa git, LLVM 10 from official Arch Linux repository; Manually switched to amdgpu kernel driver for Vulkan access;
- Kernel version: Linux 5.6.10-arch1-1-fsync from Valve's Arch binary repo;
- Proton version: 5.0-7.
- https://gist.github.com/Kerrung/fb2df78b430af5a193cabd20923be10a

## I confirm:
- [Yes] that I haven't found an existing compatibility report for this game.
- [Yes] that I have checked whether there are updates for my system available.

Please add `PROTON_LOG=1 %command%` to the game's launch options and drag
and drop the generated `$HOME/steam-$APPID.log` into this issue report
(may be later)

## Symptoms 
The game's pointer total freeze after Alt+Tab. And the game still works, my keyboard still works in the game.
But the game works perfect, no issues with Windows version of Stream with the latest Wine Staging;

## Reproduction
1) Start game;
2) Switch to any other window pressing Alt+Tab;
3) Return to the game window pressing Alt+Tab again.

**Comment by kisak-valve** [comment]
Hello @Kerrung, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4#issuecomment-629646690.
