### ISSUE TITLE
[macOS] Error when trying to build Proton

### ISSUE THREAD

**Issue by radzo73** [ValveSoftware/Proton#3878]
macOS 10.11.6, installed all the requirements using `brew install wget mingw-w64 cmake nasm libtool automake meson glslang`, cloned the repo, updated it using `git submodule update --init`, and the moment of truth, let's run `./build_proton.sh`!..

`-bash: ./build_proton.sh: No such file or directory`
What do I do?

**Comment by artemyto** [comment]
There is no build_proton.sh file in Proton nowadays:
https://github.com/ValveSoftware/Proton
But this file was there before in Proton 3.7:
https://github.com/ValveSoftware/Proton/tree/proton_3.7
I think you are trying to use some outdated guide. You can either use build instructions from this repo or use the old branch with your guide. But I think Proton is not supposed to be built under macOS.
