### ISSUE TITLE
Age of Wonders: Planetfall - ingame blank

### ISSUE THREAD

**Issue by reactormonk** [ValveSoftware/Proton#3882]
# Compatibility Report
- Name of the game with compatibility issues: Age of Wonders: Planetfall
- Steam AppID of the game: 718850

## System Information
- GPU: RX580
- Driver/LLVM version: amdgpu 19.1.0-1
- Kernel version: 5.6.13-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/reactormonk/5d1d37ec26edd0434e7873715fb3d406
- Proton version: proton-5.0-7 (Launcher doesn't seem to work with another version)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. (There is one, but it's a distinct issue)
- [x] that I have checked whether there are updates for my system available.

[steam-718850.log](https://github.com/ValveSoftware/Proton/files/4639258/steam-718850.log)

## Symptoms 

The actual game screen (after the menu) is just black (with the FPS counter of 60 at the top right). When hitting Alt+F4 something blue that looks like the AoW ingame flashes, then is out.

## Reproduction

Start the tutorial (or any game, for that matter). Graphics don't seem to matter, I set highest and lowest.

**Comment by kisak-valve** [comment]
Hello @reactormonk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2959#issuecomment-629710179.
