### ISSUE TITLE
Dungeon Defenders 2

### ISSUE THREAD

**Issue by Gibbz** [ValveSoftware/Proton#3883]
# Compatibility Report
- Name of the game with compatibility issues: Dungeon Defenders II
- Steam AppID of the game:
236110
https://store.steampowered.com/app/236110/Dungeon_Defenders_II/

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 20.0.6
- Kernel version: 5.6
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Gibbz/9599aca1fa5485d1584e4837b72bd976
- Proton version: 5.0-7

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
The game crashes/freezes after some amount of time. Usually seems to be every 2-3 games it will suddenly freeze requiring the user to kill the game

## Reproduction
It seems very intermittent, but have some logs.
[steam-236110_2.log](https://github.com/ValveSoftware/Proton/files/4639417/steam-236110_2.log)
[steam-236110.log](https://github.com/ValveSoftware/Proton/files/4639419/steam-236110.log)

**Comment by kisak-valve** [comment]
Hello @Gibbz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/393#issuecomment-629720581.
