### ISSUE TITLE
Shadow of war (Proton) - Shadow of mordor (native) - others

### ISSUE THREAD

**Issue by 4lphac** [ValveSoftware/Proton#3885]
# Compatibility Report
- Shadow of war (Proton) - Shadow of mordor (native) - others
- Steam AppID of the game: 356190, 241930

## System Information
- GPU: RX 470
- Driver/LLVM version: amdgpu, Mesa  kisak-mesa latest (20.0.7 i suppose) (happens with and without RADV_PERFTEST=aco) 
- Kernel version: 5.4.0-29-generic
- Link to full system information report as [Gist](https://gist.github.com/): Ubuntu budgie 20.04, Ryzen 1600, AMD B450, 16Gb ram, SSD or HDD has no impact on this problem (tried both)
- Proton version: 5.0.7

steam-356190.log is 156MB!!! wtf?? Cannot attach it, there's for sure something goin on..

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
It happens both games (first with steam linux version, second with proton) shadow of mordor and shadow of war, the game speed turns "uneven" after a few seconds of playing (1920x1080 details to lowest) , it begin going from very slow to very fast (like someone turining from slowspeed to fastspeed a fictional knob), and back again, endlessly, in the second title it is so persistent that the game is unplayable. Note that there is no stuttering, internal game benchmark gives 82 fps (without RADV_PERFTEST=aco) and 98 fps (with RADV_PERFTEST=aco) and has no trace of that cyclic speeding up and down. It's the first time I see something like this, very strange.

## Reproduction

I think it's very much hadware/driver related

**Comment by kisak-valve** [comment]
Hello @4lphac, we're using one issue report per unofficially supported game title, and issues with native linux games are outside the scope of this issue tracker, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/135#issuecomment-629806754.

That said, if native linux games are equally affected, then that hints the issue you've encountered is outside of Proton.
