### ISSUE TITLE
Lichdom : Battlemage - Crashing while loading a save or starting a new game

### ISSUE THREAD

**Issue by ConnorA3** [ValveSoftware/Proton#3888]
[steam-261760.log](https://github.com/ValveSoftware/Proton/files/4641290/steam-261760.log)
# Compatibility Report
- Name of the game with compatibility issues: Lichdom : Battlemage
- Steam AppID of the game: 261760

## System Information
- GPU: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti]
- Driver/LLVM version: 440
- Kernel version: 5.3.0-51-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ConnorA3/d4066e3ad7b9de11c68ed50d32cbc398
- Proton version: 5.0-7

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
![Screenshot from 2020-05-18 00-04-55](https://user-images.githubusercontent.com/62213788/82162441-72689c80-989c-11ea-9de8-87494bd8e181.png)
![Screenshot from 2020-05-17 22-08-14](https://user-images.githubusercontent.com/62213788/82162443-772d5080-989c-11ea-96c0-eb7f221ef5fe.png)

The game starts as it should from Steam with Proton 5.0-7 and a few other Proton versions I've tried, and the menu displays perfectly fine with no glitches, but when I go to load or start a new game, it crashes, displaying the error messages as included in the screenshots. I read on ProtonDB that the problem is due to wininet being missing, and that installing wininet using protontricks solved the problem for a few people, so I tried just that, but to no avail. I am really unsure about why this game refuses to load properly when all others apart from Red Dead 2 and, at first, Call of Cthulhu, have worked without any issues at all. Any help or assistance would be greatly appreciated!

**Comment by kisak-valve** [comment]
Hello @ConnorA3, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1581#issuecomment-629878372.

**Comment by ConnorA3** [comment]
> Hello @ConnorA3, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#1581 (comment)](https://github.com/ValveSoftware/Proton/issues/1581#issuecomment-629878372).

Ah, thank you!
