### ISSUE TITLE
Dishonored (205100)

### ISSUE THREAD

**Issue by MetalNeo** [ValveSoftware/Proton#3889]
# Compatibility Report
- Name of the game with compatibility issues: Dishonored
- Steam AppID of the game: 205100

## System Information
- GPU: Radeon RX 5700XT
- Driver/LLVM version: mesa 20.0.7-2
- Kernel version: 5.6.13.arch1-1
- Link to full system information report as [Gist](https://gist.github.com/MetalNeo/45c5f674194bbd9cefead559d9a3b2ca)
- Proton version: 5.0-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-205100.log](https://gist.github.com/MetalNeo/982e1ef8bc73f10d550fd45018f9d1d7)

## Symptoms 

The credits do not roll at the end of the game.

## Reproduction

1. Start the game.
2. Play until the end of the game is reached.
3. Wait for the pre-rendered cinematic to play.
4. The game will skip the end credits and return to the main menu.

**Comment by kisak-valve** [comment]
Hello @MetalNeo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/51#issuecomment-630264638.
