### ISSUE TITLE
Alien Rage - Unlimited (217920)

### ISSUE THREAD

**Issue by springwurm** [ValveSoftware/Proton#3895]
# Whitelist Request
- Name of the game to be whitelisted: Alien Rage - Unlimited
- Steam AppID of the game: 217920

## System Information
- GPU: AMD Radeon RX 580
- Driver/LLVM version: Mesa 20.0.7
- Distro version: Arch Linux
- Link to full system information report as [Gist](https://gist.github.com/springwurm/e237bcad1940fb7a4c44b98b5109d04f):
- Proton version: 5.0-7

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [X] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [X] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @springwurm, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/160#issuecomment-631916918.
