### ISSUE TITLE
[Whitelist] Bioshock Infinite (8870) 

### ISSUE THREAD

**Issue by Dakunier** [ValveSoftware/Proton#390]
10 Minutes playtime, worked without problems

Systeminfo: https://gist.github.com/Dakunier/352c4f0b1b7c027065f71993367b0249

**Comment by tfaller** [comment]
@Dakunier Bioshock Infinite is a native Linux game. Are you sure that you tested the Windows version with Proton and not the native Game?

**Comment by Dakunier** [comment]
oh you are right. it starts the native linux version... 

is it possible to download windows version somehow?^^

**Comment by tfaller** [comment]
Unfortunately no, its currently not possible.
Take a look at issue ValveSoftware/steam-for-linux#5638

**Comment by danielmotaleite** [comment]
native games should never be played via proton, this will only make support harder as this will mix native and proton problems/bugs.
Proton is only for windows only games

**Comment by legluondunet** [comment]
@danielmotaleite no one ask to launch Linux native game with proton (that's not possible), just the possibility to launch the Windows port when the Linux native port is bad or obsolete (example: Enclave).

**Comment by Dakunier** [comment]
should i close the issue now?
its a native Game and at the moment its not possible to install the Windows Version on Linux.

**Comment by kisak-valve** [comment]
Closing as Bioshock Infinite is a native linux game.

**Comment by legluondunet** [comment]
yes you can close it. There is already an opened issue to ask for the possibility to install the Windows version, even if Linux port is available.

**Comment by miguev** [comment]
Bioshock Infinite is a native linux game with missing features, e.g. no controller support. Very disappointed to find this out only after buying and trying a PS4 Dualshock for this very game. I'd be willing to run it with WINE just to replay it with the controller, but I'd rather do it through SteamPlay.

**Comment by dubigrasu** [comment]
@miguev
It has controller support including rumble for many gamepads though, can't speak for PS4 Dualshock because I don't have one, but the PS3, Xbox360 (wired or wireless) and some Logitechs controllers are working fine.

**Comment by jaycee1980** [comment]
@miguev the game uses the SDL gamepad mapping system, which means for your controller to be identified you must either a) edit SDLGamepad.config to include the mapping for the PS4 pad, or b) define the mapping via Steam Big Picture.

**Comment by miguev** [comment]
Got the controller to work, thanks for the hints!

**Comment by JTPete123** [comment]
I cannot get my xbox controller to work (controller option is greyed out in game options), I have defined setup in Steam Big Picture where it shows as controller icon with game. Funny, controller works flawlessly on another 2K game Borderlands 2.  I could sure use some suggestions!
