### ISSUE TITLE
Doom 2016 (379720) freezes after killing an enemy

### ISSUE THREAD

**Issue by jonnyrobbie** [ValveSoftware/Proton#3909]
# Compatibility Report
- Name of the game with compatibility issues: Doom 2016
- Steam AppID of the game: steam-379720

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 20.0.7-3
- Kernel version: Linux 5.6.14-zen1-1-zen x86_64 GNU/Linux
- Link to full system information report as [Gist](https://gist.github.com/jonnyrobbie/5982d49a73f2940630d36bfc6a64a903)
- Proton version: 5.0-7 and 4.11.13

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

PROTON_LOG: [steam-379720.tar.gz](https://github.com/ValveSoftware/Proton/files/4673665/steam-379720.tar.gz)

## Desc

The game freezes right after killing first enemy I see. Almost like some shader used to display drop pellets crashes (speculation). It shots down the compositor. Even switching to another TTYs gets funky and broken.

I've tried both the 5.0 and 4.11 version of proton. It is worth noting that it used to work a month ago. I came back after a month and it suddenly doesn't work. I've not experienced issues with other proton games, like Witcher III or The Sims 3.

## Repro

Load a save, shoot and kill the first enemy you see.

**Comment by hakzsam** [comment]
Are you able to reproduce with RADV_PERFTEST=aco ?

**Comment by jonnyrobbie** [comment]
Interesting. First things first: RADV_PERFTEST=aco did not help, still reproducible crash on my end. I've also tried mainline kernel (not zen) and the problem is still there.

But I've noticed that the game crashes when I kill the demon before he finishes spawning. I'm in some section where I need to press a button and that triggers a battle sequence and while I was in a testing loop, I tried to be as efficient with time as possible, so I pre-aimed at the spawn location and started shooting as soon as I saw the demon spawning. That crash is still reproducible. But when I let the demon spawn and run away and kill him a few meters away, the game does not seem to crash.

**Comment by hakzsam** [comment]
@jonnyrobbie Are you still able to reproduce with Mesa 20.2.x ?

**Comment by zeratax** [comment]
I might be reading this wrong, but your system info has ICDs for amdvlk, where until very recently there was a bug that also affected me: https://github.com/GPUOpen-Drivers/AMDVLK/issues/175#issuecomment-692442852

but has been very recently fixed

**Comment by hakzsam** [comment]
Yeah, both drivers are installed, so maybe he was using AMDVLK instead of RADV.

**Comment by kisak-valve** [comment]
Closing as pending feedback.
