### ISSUE TITLE
Hereos & Generals Starting Issue (227940)

### ISSUE THREAD

**Issue by MuhammedKpln** [ValveSoftware/Proton#391]
Getting "Please, start Hereos and Generals through Steam" error on startup.

Deepin 15.7
Proton 3.7
Nvidia 390.67

System information from Steam:
https://gist.github.com/MuhammedKpln/b219c1b2fb76b5219c1908bd902918e4

**Comment by cyberkhalil** [comment]
Why did you close this issue ?
I have the same issue with
{
linux : 4.19.32-1
distro : MANJARO
desktop enivornment : KDE
proton version : Proton 4.2-1
}

**Comment by GrbavaCigla** [comment]
Same problem,
Linux: 5.2.5
Distro: Arch
DE: Gnome
Proton: 4.11-1
