### ISSUE TITLE
Cows VS Vikings (854860)

### ISSUE THREAD

**Issue by crabel** [ValveSoftware/Proton#3911]
# Compatibility Report
- Name of the game with compatibility issues: Cows and Vikings
- Steam AppID of the game: 854860

## System Information
- GPU: RX Vega 64
- Driver/LLVM version: X.Org Radeon RX Vega (VEGA10, DRM 3.35.0, 5.4.0-31-generic, LLVM 9.0.1)
 Mesa 20.0.4
- Kernel version:  5.4.0-31-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/crabel/2eb1dae42e5e950553a75c54c9e3d490
- Proton version: 5.0-7

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-854860.log](https://github.com/ValveSoftware/Proton/files/4678100/steam-854860.log)

## Symptoms
Game starts, looks working in general, but when a new game is started, the screen goes black stays that way. The game does not hang, it is possible to move the mouse. Music is playing. Since the file path to the intro video is among the last entries in the logfile I am guessing it has something to do with the issue.

## Reproduction
1) Start game (windowed or fullscreen, doesn't make a difference)
2) Click "New game" button
Screen goes blank, game has to be killed.

**Comment by kisak-valve** [comment]
Hello @crabel, looks like this game would benefit from support for Media Foundation maturing.

**Comment by crabel** [comment]
Yes, it looks that way. Probably relates to #1464.

**Comment by crabel** [comment]
A Linux version of the game was added by the developer in the mean time.
