### ISSUE TITLE
Black Desert Online - game launcher crashes 

### ISSUE THREAD

**Issue by Gman1988** [ValveSoftware/Proton#3913]
# Compatibility Report
- Name of the game with compatibility issues: Black Desert Online
- Steam AppID of the game: 582660

## System Information
- GPU: Radeon R9 290/290X / 390/390X
- Driver/LLVM version: Mesa 20.0.7
- Kernel version: 5.6.13-300.fc32.x86_64
- Link to full system information report as [Gist](https://gist.github.com/Gman1988/de2744bb73414bf6282af4d4b3c1561b):
- Proton version: 5.0.7

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

https://gist.github.com/Gman1988/966d43fac5e79323652626a29ec9d617

[steam-582660.log](https://github.com/ValveSoftware/Proton/files/4679121/steam-582660.log)

## Symptoms 

Game installs fine. Launcher open up, when I press "start game", account creation shows up for 1 sec and that is it, nothing else is happening.

## Reproduction

1. Install game.
2. Launch game.
3. Press "start game"
4. Observe issue.

**Comment by kisak-valve** [comment]
Hello @Gman1988, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3620#issuecomment-633738742.
