### ISSUE TITLE
Insurgency Sandstorm Anti cheat

### ISSUE THREAD

**Issue by PipeSquirrel** [ValveSoftware/Proton#3914]
# Compatibility Report
- Name of the game with compatibility issues: insurgency sandstorm 
- Steam AppID of the game: 581320

- Proton version: 5.0-7

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 
Playing on linux via steam play, Anti cheat kicks me out of every game.

**Comment by kisak-valve** [comment]
Hello @PipeSquirrel, we're using one issue report per unofficially supported game title, and this game is already being tracked at #1651 with this information. Closing as a duplicate.
