### ISSUE TITLE
Doom 2016 (379720) not opening after switching to Vulkan

### ISSUE THREAD

**Issue by KairanD** [ValveSoftware/Proton#3919]
# Compatibility Report
- Name of the game with compatibility issues: Doom (2016)
- Steam AppID of the game: 379720

## System Information
- GPU: EVGA GeForce GTX 1070Ti SC
- CPU: Intel Core i5 4670K @ 3.8 GHz
- Driver/LLVM version: NVidia 440.64
- System: Ubuntu 20.04 LTS
- Kernel version: 5.4.0-33-generic
- Link to full system information report as [Gist](https://gist.github.com/KairanD/31feb36ba9ea9af42478e26e3858dbba)
- Proton version: 5.0-7

## I confirm:
- [  ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

I tried to change the renderer from OpenGL 4.5 to Vulkan in game options and the game doesn't even open (it tries to open and then closes very fast). If I set it to run with Open GL again using launch option "+r_renderAPI 0", it works. However, the performance with OpenGL is not great (my CPU is not exactly a powerhouse) and I need Vulkan to get stable 75 FPS using max settings at 2560x1080p. 

The game is installed in an ext4 partition and Steam overlay is disabled. The command "vulkaninfo | less" works. My system, my drivers and Steam (Beta) are all updated. 

## Reproduction

Select Vulkan in game options and restart the game.

**Comment by kisak-valve** [comment]
Hello @KairanD, blind guess, but I suspect that the game is trying to run off the Intel Haswell chipset and falling over. Does setting the game's launch options to `VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/nvidia_icd.json" %command%` have an effect? This should tell the vulkan-loader to only try to use the nVidia gpu.

**Comment by KairanD** [comment]
@kisak-valve Thank you SO MUCH! It worked. Now the demons can punch me at constant 75 FPS!

So, it's a specific issue with these chips? Guess I will need to use this option in any game running with Vulkan.
