### ISSUE TITLE
Option to easily open compdata/prefix folder

### ISSUE THREAD

**Issue by regulator-g** [ValveSoftware/Proton#3920]
Feature Request:
I would like an "open prefix" button added to the game properties under the local files tab
A "reset prefix" button would be useful too

## I confirm:
- [x ] that I haven't found another request for this feature.
- [x ] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
I would like an "open prefix" button added to the game properties under the local files tab
A "reset prefix" button would be useful too

## Justification [optional] 
I posted this in steam suggestions but it got buried.

Currently if you want to open the games prefix folder, you also have to find the games steam ID by opening a web browser and looking at the store page URL. The compdata folder is also hard for new Linux users to find 

## Risks [optional]
new users could accidentally delete the prefix folder and loose their save games

## References [optional] 
n/a

**Comment by kisak-valve** [comment]
Hello @regulator-g, this is a feature request for the Steam client, not Proton itself, and is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5667. Closing as a duplicate.

**Comment by regulator-g** [comment]
thanks for the info, sorry didn't see the steam-for-linux repo
