### ISSUE TITLE
RX 580 being reported as ATI Radeon HD 5600 Series

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3921]
Proton Version: 5.0-7
OS: Manjaro Linux
KERNEL: 5.6.12-1-MANJARO
CPU: AMD Ryzen 5 1500X Quad-Core
GPU: ATI Technologies Inc. Radeon RX 580
GPU DRIVER: 4.6.13572 Compatibility Profile Context
RAM: 24 GB

All games running under Proton are reporting my GPU as ATI Radeon HD 5600 Series (a 0.5GB card) when my GPU is a RX 580 (a 8GB card). Normally this isn't an issue, but in some games (such as Trackmania Stadium) the textures are compressed and look awful compared to running under Windows. Other games it does not appear to matter, but some games don't run right and it seems to be because they think my card is only a 0.5GB card.

**Comment by doitsujin** [comment]
Does `WINEDLLOVERRIDES=dxgi=n` fix the problem? wined3d has its own hardware table for some reason, it might just be lacking an entry for your card.

**Comment by ghost** [comment]
Hi, so I used `WINEDLLOVERRIDES=dxgi=n %command%` in the Launch Options on Trackmania (since it shows me the most info about my card) and it showed up as a RX 580 and it's now reporting 3GB instead of 0.5GB. Any way I can get this to show the full 8GB?

Edit: It's now reporting 8GB, thank you very much!

**Comment by doitsujin** [comment]
It's normal for it to report 3GB for 32-bit games since because DXGI simply cannot handle more than 4GB there, and some applications are broken if we try to report e.g. 3.5GB so DXVK just settles for 3GB.

**Comment by ghost** [comment]
Yeah, forgot about 32-bit not able to handle more than 4GB (been a while since I've had to deal with 32-bit stuff). I launched the configuration tool for TM, it said 3GB but when I launched the actual program it was reporting 8GB. Thank you so much for your help, much appreciated!
