### ISSUE TITLE
Thief (239160)

### ISSUE THREAD

**Issue by Galcian79** [ValveSoftware/Proton#3925]
Game crashes after several hours of play and multiple load/savings.
I suspect something is flooding the FD cache. Increasing the fd limit to 1048576, as suggested in wine wiki, seems to have boosted game stability.
I attached the log of `WINEDEBUG=err+all`
[steam-239160.log](https://github.com/ValveSoftware/Proton/files/4706327/steam-239160.log)

**Comment by kisak-valve** [comment]
Hello @Galcian79, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/279#issuecomment-636377944.
