### ISSUE TITLE
Wallachia: Reign of Dracula (1189780)  - Not launching

### ISSUE THREAD

**Issue by leandiez** [ValveSoftware/Proton#3928]
# Compatibility Report
- Name of the game with compatibility issues: Wallachia: Reign of Dracula
- Steam AppID of the game: 1189780

## System Information
- GPU: GTX 1650 SUPER
- Driver/LLVM version: Nvidia 440.82
- Distro: Manjaro 20 KDE Plasma
- Kernel version: 5.6.11
- Link to full system information report as [Gist](https://gist.github.com/lamodey/5a4b6d62431f5108406024412293303d):
- Proton version: 5.0-7

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

[steam-1189780.log](https://github.com/ValveSoftware/Proton/files/4708569/steam-1189780.log)

## Symptoms 
The game installs without problems, but at launching time nothing happens. 
The game itself is only an executable (.exe)

## Reproduction
1) Open the game launcher on Steam
2) Click on Play button
3) The button show Stop... action, but after a seconds the game closes automatically  and Play is showed again.

**Comment by kisak-valve** [comment]
Hello @lamodey, `fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!` in the log points towards https://bugs.winehq.org/show_bug.cgi?id=45277.

**Comment by leandiez** [comment]
Hello @kisak-valve 
Thank you very much for the feedback. 

Setting this on launching parameters solves the problem and i can continue testing in running time:

PROTON_USE_WINED3D=1 %command%

This is how look likes the log right now:

[steam-1189780.log](https://github.com/ValveSoftware/Proton/files/4712471/steam-1189780.log)
