### ISSUE TITLE
Death end re;Quest (990050), Crashes in-game

### ISSUE THREAD

**Issue by CygnusTerminal** [ValveSoftware/Proton#3933]
# Compatibility Report
- Name of the game with compatibility issues: Death end re;Quest
- Steam AppID of the game: 990050

## System Information
- GPU: RX 480
- Driver/LLVM version: Mesa 20.0.7
- Kernel version: 5.6.15-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/CygnusTerminal/b7198c3f50dd887eeb42aac4643d9a6c
- Proton version: 5.0-7

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

LOG: 
[steam-990050.log](https://github.com/ValveSoftware/Proton/files/4724024/steam-990050.log)
Line of interest:
1356.376:00c0:00c4:trace:seh:RtlRestoreContext returning to 7b475ca6 stack 32de60
1519.584:00c0:00fc:err:ntdll:RtlpWaitForCriticalSection section 0x100a8 "../../../../proton/wine/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 00fc, blocked by 00c4, retrying (60 sec)
1519.833:00c0:018c:err:ntdll:RtlpWaitForCriticalSection section 0x100a8 "../../../../proton/wine/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 018c, blocked by 00c4, retrying (60 sec)
1529.905:00c0:0150:err:ntdll:RtlpWaitForCriticalSection section 0x100a8 "../../../../proton/wine/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0150, blocked by 00c4, retrying (60 sec)

## Symptoms
Game freezes and never recovers. Sometimes is instantly, sometimes takes a good while

## Reproduction
Launch the game with Proton 5.0
Play until the freeze
Kill the .exe

**Comment by kisak-valve** [comment]
Hello @CygnusTerminal, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2705#issuecomment-638239125.
