### ISSUE TITLE
VRChat post udon update (438100)

### ISSUE THREAD

**Issue by jaydenhawkes123** [ValveSoftware/Proton#3934]
# Compatibility Report
- Name of the game with compatibility issues: VRChat
- Steam AppID of the game: 438100

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 20.1.0-rc3 ... aco compiler instead of llvm
- Kernel version: Linux 5.6.15-1
- Link to full system information report as [Gist](https://gist.github.com/jaydenhawkes123/4b14a7af5907df87bb0eafc72d8ee1ad):
- Proton version: Proton 5.0-8 RC testing, Proton 5.*, 4.11, 4.3 and all versions of glorious egroll proton in desktop mode (Could not test glorious egroll proton in vr mode as no vr games seem to launch with glorious egroll proton).
VR SYSTEM: Valve index full kit

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. (Found one for an older version, game worked fine on proton until its last major update April 2nd)
- [x] that I have checked whether there are updates for my system available.

Log ended up being half a gig after 5mins of gameplay.... Gist didnt seemt to like it and you can only upload 10M files to github issues. Ended up uploading it to Mega
https://mega.nz/file/3SxxiJIR#jVtIb80nkLFQ8QW2eiIu_rLyxhHQKMdyFNaA-ZyUFGk

## Symptoms 
(Same problems appear in both desktop mode and vr mode)
Some player avatars dont load in and instead display an error avatar (This was not an issue before the last major update)

Some worlds have broken lighting (e.g japan shrine if you walk forward) giant rays of binding light appear (Also dont think this was an issue before the update) Tried d9vk, same problem, game doesnt seem to work with d3d.

Video players do not play (Both with `<Workaround removed by moderator>` script and glorious egroll proton)

Users at protondb rename youtube-dl.exe in the game files to something else to avoid a crash in worlds with media players but running `<Workaround removed by moderator>` seems to also help avoid that crash (Tho the players still don't work)

## Reproduction

Start vrchat (Either vr or desktop)

For Error ed models
Join a public world thats almost full, mots of time time you will get a few errored models after the most of the models successfully load in... does seem to depend on luck tho, may need to try a couple worlds

For lighiting bug
Go to Japan shrine and walk forward, Go to black cat world and go upstairs to the bar.

For media player.
Join a world that says you can watch things here and attempt to play a video, nothing will happen if you renamed youtube-dl or you did `<Workaround removed by moderator>`. You will most likely freeze and crash if you didnt to either of these things.

**Comment by kisak-valve** [comment]
Hello @jaydenhawkes123, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1199#issuecomment-638820883.

Additionally, one of the workarounds you've used is legally problematic and has been removed.
