### ISSUE TITLE
Witcher 2

### ISSUE THREAD

**Issue by Matheusmagcosta** [ValveSoftware/Proton#3936]
# Compatibility Report
- Name of the game with compatibility issues: Witcher 2: Assassins king enhanced edition
- Steam AppID of the game: ebesathyr

## System Information
System:    Host: matheus-desktop Kernel: 5.0.0-32-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.4.5 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Desktop Mobo: ASRock model: A320M-HD serial: <filter> 
           UEFI [Legacy]: American Megatrends v: P5.40 date: 07/09/2019 
CPU:       Topology: Dual Core model: AMD Athlon 240GE with Radeon Vega Graphics bits: 64 
           type: MT MCP arch: Zen L2 cache: 1024 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 28001 
           Speed: 3484 MHz min/max: 1600/3500 MHz Core speeds (MHz): 1: 3480 2: 1990 3: 3415 
           4: 1999 
Graphics:  Device-1: AMD Bonaire XTX [Radeon R7 260X/360] vendor: Gigabyte driver: amdgpu 
           v: 5.0.19.20.7 bus ID: 01:00.0 chip ID: 1002:6658 
           Display: x11 server: X.Org 1.20.4 driver: amdgpu,ati unloaded: fbdev,modesetting,vesa 
           resolution: 1920x1080~75Hz 
           OpenGL: 
           renderer: AMD Radeon R7 200 Series (BONAIRE DRM 3.31.0 5.0.0-32-generic LLVM 7.1.0) 
           v: 4.5 Mesa 18.3.0-rc4 direct render: Yes 

Proton: 5.0-7

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 
O jogo não inicia, assim que coloco para rodar o mesmo desliga sozinho

**Comment by kisak-valve** [comment]
Hello @ebesathyr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2309#issuecomment-639010923.
