### ISSUE TITLE
Cannot get Proton to work with *any game* (4.11 with Star Wars: Empire at War example)

### ISSUE THREAD

**Issue by Madwand99** [ValveSoftware/Proton#3941]
I have Steam on my Linux Mint machine, and it works well for a variety of Linux-native games. However, I have tried half a dozen Proton games, and I've never been able to get them to work. I've tried various winetricks things, and hours of Googling, but nothing so far. I need help. Here's a log from my attempt at running Star Wars: Empire at War, which (according to ProtonDB) is supposed to work well on Proton:
https://pastebin.com/GviaZP85
Can anyone help me understand what I need to do to get Proton working?

**Comment by kisak-valve** [comment]
Hello @Madwand99, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Madwand99** [comment]
Here is system info:
https://gist.github.com/Madwand99/146a9e86ba34b791124803697e0611c1

**Comment by deathxxx123** [comment]
> I have Steam on my Linux Mint machine, and it works well for a variety of Linux-native games. However, I have tried half a dozen Proton games, and I've never been able to get them to work. I've tried various winetricks things, and hours of Googling, but nothing so far. I need help. Here's a log from my attempt at running Star Wars: Empire at War, which (according to ProtonDB) is supposed to work well on Proton:
> https://pastebin.com/GviaZP85
> Can anyone help me understand what I need to do to get Proton working?

Hi there. Maybe you'r OS, kernel, video driver, Proton is little old?
First, you need apply steam-beta, then add ppa for lastest Nvidia drivers, then apply lastest Proton. For lastest kernel maybe upgrade OS or install XanMod kernel ( https://xanmod.org/ )
That is my gueses, but i'm not a pro.
If all this cannot help you, then you mess with some configuration in hidden files in /home directory.
Easyest think to do, is to install lastest distro in separate disk or partition, and try Proton games with Fresh OS install.

**Comment by Madwand99** [comment]
Upgrading video driver seems to have helped, I'll see if things improve.
