### ISSUE TITLE
When using the "Move Install Folder" feature the compatdata isn't moved with the game

### ISSUE THREAD

**Issue by BillFleming** [ValveSoftware/Proton#3943]
# Feature Request
When moving a game to another library update the Linux client to check for a prefix folder in compatdata then also move it to the other steam library folder.
If any paths need to be updated to point to the new prefix also change the paths. (Not sure how that part works, but Plagman would know.)

## I confirm:
- [X] that I haven't found another request for this feature. (If there is I am retarded and can't find it.)
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Justification [optional] 
I believe that when you move the game without the prefix it will not be able to find your game saves. Also of course to goal might be to completely remove an old steam library folder so you don't want to lose your game saves.

## Risks [optional]
If we already are losing game saves on folder moves there shouldn't be any today. BUT if any enhancements are made to allow for common prefix or similar feature those could affect this possible fix.

## References [optional] 
https://github.com/ValveSoftware/Proton/issues/2553
Any other issues related to having a single compat prefix for all games or other similar types of requests. Once these features are complete moving the compatdata will become more complicated. (Do you move just the game saves? The who prefix? etc.)

**Comment by kisak-valve** [comment]
Hello @BillFleming, this is a Steam client issue, not an issue with Proton itself, and is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5717. Closing as a duplicate.
