### ISSUE TITLE
Cossacks 3 (333420)

### ISSUE THREAD

**Issue by nerzhul** [ValveSoftware/Proton#3956]
# Compatibility Report
- Name of the game with compatibility issues: Cossacks 3
- Steam AppID of the game: 333420

## System Information
- GPU: RX 580
- Driver/LLVM version: 20.0.7-3
- Kernel version: 5.6
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/nerzhul/f6c75073cbabb97d40c55433a0747fa1
- Proton version: 5.0-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

In cossacks 3 all units are rendered as black , same for trees. Appart that game work fine (unlike the linux native version which crash at startup)

Here is the rendering
![Capture d’écran de 2020-06-08 23-12-27](https://user-images.githubusercontent.com/119752/84081474-4f826180-a9de-11ea-8bed-adb93088cc22.png)

**Comment by kisak-valve** [comment]
Hello @nerzhul, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the issue, and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by mozo78** [comment]
@nerzhul 
The map is broken too.

**Comment by nerzhul** [comment]
[steam-333420.log](https://github.com/ValveSoftware/Proton/files/4774533/steam-333420.log)
Here is the log @kisak-valve , sorry for the delay

**Comment by kisak-valve** [comment]
Thanks, can you check if setting the game's launch options to `PROTON_USE_WINED3D=1 %command%` has an effect?

**Comment by nerzhul** [comment]
hello @kisak-valve thanks, but nothing more, it's the same rendering

**Comment by przmkg** [comment]
I tried various Proton versions but none seem to render the game as it should.

By setting the `ShaderType` field in `profile.cfg` to `stNone`, I was able to get it to render slightly better, but still wrong :

![cossacks](https://user-images.githubusercontent.com/4224655/98109465-e4aa5900-1e9d-11eb-9a27-6fdea42be735.png)

**Comment by nerzhul** [comment]
@przmkg you put it in the Engine struct ?

**Comment by przmkg** [comment]
@nerzhul Yes, if you open `steamapps/compatdata/333420/pfx/drive_c/users/steamuser/My Documents/cossacks/profiles/Cossack/profile.cfg`, you can tweak some settings there.

For a list of possible values, you can check [here](http://www.cossacks3.com/forum/index.php?threads/profile-cfg-possible-values-list.18065/).

**Comment by nerzhul** [comment]
ah ! i check than, i did it in my home, will test here too

**Comment by cirrusblau** [comment]
I've got the same issue.

When I run newer versions of Proton, the game starts but cannot be seen.  In the task bar where icons normally appear for running apps, the game icon briefly appears before disappearing.  Steam shows the game as running and the game music can be heard and the mouse cursor is that you would expect in the game.  Despite being able to see the desktop/steam, the mouse doesn't interact with it unless I alt+tab.

So it seems the game is running, just something to do with the display isn't working properly.

This occurs with the following versions of Proton.

- 7.0-1
- 6.3-8
- 5.13-6

If I run Proton 5.0-10 the game launches and I can see it but once in game I get the texture issues that @nerzhul reported.

What would have changed between Proton 5.0-10 and later versions that led to this issue?  I've tried some Proton launch options without any luck.  Is there anything in the logs that might give some clues as to what is failing and how to get a newer version of Proton running?  @kisak-valve any suggestions would be appreciated.

**Comment by kisak-valve** [comment]
Hello @cirrusblau, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by cirrusblau** [comment]
@kisak-valve thanks for getting back to me.

Here's the system information https://gist.github.com/cirrusblau/fecb60a923fd48163636dc13887117de

Logs attached for 5.0-10 (game runs but there are display issues with units, buildings and the mini-map) and 7.0-1 (game launches and may be running but cannot be seen).

In both cases I get a warning "Your video card does not support hardware acceleration.  Try to update your video card drivers.".  

Let me know if there's anything else I can test or provide.

[steam-333420-5.0-10.log](https://github.com/ValveSoftware/Proton/files/8509548/steam-333420-5.0-10.log)
[steam-333420-7.0-1.log](https://github.com/ValveSoftware/Proton/files/8509549/steam-333420-7.0-1.log)

![Screenshot from 2022-04-18 23-08-17](https://user-images.githubusercontent.com/44950387/163913266-6afe1e9f-b4c1-470d-9727-6c55dc74c39f.png)


![Screenshot from 2022-04-18 23-05-27](https://user-images.githubusercontent.com/44950387/163913239-e1416b98-576e-47ed-aeeb-fcc24c792632.jpg)

**Comment by kodatarule** [comment]
I think it needs re-test as I'm able to play the game just fine on latest Proton Experimental and even on a wayland session on an Nvidia gpu.
![Screenshot_20220731_133609](https://user-images.githubusercontent.com/65848953/182022221-65167a2b-4964-446a-96f3-58009910930a.png)

**Comment by nerzhul** [comment]
exact it's solved for me now (archlinux, proton experimental), let's play few hours and see if all is fine :)

**Comment by nerzhul** [comment]
everything is okay, a bit laggy on my big setup when there is many units, but playable
