### ISSUE TITLE
Install native d3dcompiler_47.dll library for vkd3d

### ISSUE THREAD

**Issue by jqadev** [ValveSoftware/Proton#3958]
# Feature Request
Install native `d3dcompiler_47.dll` library during game installation using Proton.

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description
@doitsujin  explained here https://github.com/HansKristian-Work/vkd3d/issues/122#issuecomment-630757866 that there is needed native `d3dcompiler_47.dll` library to run D3D12 game using `vkd3d`.

I found that this library is available in Lutris tools here https://lutris.net/files/tools/dll/d3dcompiler_47.dll so I put it to directory with the launcher and the game started to work.

It would be great to install it using Proton without tinkering.

**Comment by kisak-valve** [comment]
Hello @jqadev, including proprietary libraries in Proton is not the way forward. Instead, wine's d3dcompiler should be improved until an alternative is not needed. (This is true for any other part of Proton as well.)

**Comment by soredake** [comment]
https://source.winehq.org/WineAPI/d3dcompiler_47.html
