### ISSUE TITLE
Proton 5.0 - Games fail due to driver downgrade from Vulkan 1.1 to 1.0

### ISSUE THREAD

**Issue by alatecj** [ValveSoftware/Proton#3963]
# Compatibility Report
- Name of the game with compatibility issues: Deep Rock Galactic, Astroneer
- Steam AppID of the game: 548430, 361420

## System Information
- GPU: RX480
- Driver/LLVM version:  Driver:  X.Org AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.8.0, 4.9.223-158.lts, LLVM 9.0.1)
    Driver Version:  4.5 (Compatibility Profile) Mesa 19.3.4
- Kernel version:    "Solus" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.9.223-158.lts
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/alatecj/094395d65ab7a15965ae5d7b29b7f77c
- Proton version: Proton 5.0-8
[steam-548430.log](https://github.com/ValveSoftware/Proton/files/4757873/steam-548430.log)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
After getting Proton 5.0-8, some games fail on "DX11 feature level 10.0 is required to run engine.".

## Reproduction
Run the game, get the error. Reverting to proton 4.11-13 does help with running the games.

**Comment by kisak-valve** [comment]
Hello @alatecj, Proton uses DXVK to translate Direct3D 9/10/11 to Vulkan and whenever you see an error message like that, it means that vulkan failed to initialize. Between Proton 4.11 and 5.0, DXVK dropped buggy fallback support for vulkan 1.0.

There's something fishy going on with your vulkan driver stack. What I'm seeing in your system information is the vulkan icd has `"api_version" : "1.1.107"` which matches up to mesa 19.3.X, but when Steam does a simple activation test it gave you `"version" : "1.0.68 (device 1002:67df) (driver 19.3.4)"` which tells us that something is too old (or broken) for vulkan 1.1.

It looks like you're using Solus's Linux Steam Integration to disable the Steam runtime. Any issues with the Steam runtime disabled must be resolved by you or the package maintainers that helped you disable it. Please retest with the Steam runtime enabled.

**Comment by alatecj** [comment]
Hi @kisak-valve , thank you for checking my initial report out. I've disabled the Solus steam integration and re-run the steam information tool - can you have a look now, please?

https://gist.github.com/alatecj/6484cb7f099c8222149fb50742a7befe

**Comment by kisak-valve** [comment]
Thanks, that silenced a bunch of library issues detected by s-r-t-info, but unfortunately it didn't help with the video driver riddle.

**Comment by kisak-valve** [comment]
A mesa dev took a look at this and the response that came back is that your kernel is too old to support Vulkan 1.1.

More specifically, RADV needs syncobj support, which was introduced somewhere around 4.15 (early 2018), and your 4.9 series kernel has features from late 2016. Looking around, I think you'll want to add the `linux-current` package to get a 5.4 series linux kernel.

**Comment by alatecj** [comment]
@kisak-valve and you are absolutely right. Solus has a kernel selection option at boot time - it seems that I accitentaly selected the LTS branch instead of the current one. Switching to 5.6 solved the issue and I am very grateful for your time and help!
