### ISSUE TITLE
 Fallout: New Vegas (22380)

### ISSUE THREAD

**Issue by CallieEZ** [ValveSoftware/Proton#3965]
# Compatibility Report
- Name of the game with compatibility issues: Fallout: New Vegas
- Steam AppID of the game: 22380

## System Information
- GPU: RTX 2080ti
- Driver/LLVM version: nvidia 440.82
- Kernel version:5.4.43-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/cncz42/262fc6c4732969ec9cc90bbacdd0ffdd
- Proton version: 5.0-8

## I confirm:
- [ *] that I haven't found an existing compatibility report for this game.
- [ *] that I have checked whether there are updates for my system available.

[steam-22380.log](https://github.com/ValveSoftware/Proton/files/4760452/steam-22380.log)

## Symptoms
The in game radio music is completely silent, all other audio including ambient music, npc voices, radio voices, and jukebox voices are perfectly fine.

## Reproduction
Start game, play through intro from new game, get "pip-boy 3000" select "mojave music radio" in the menu

**Comment by kisak-valve** [comment]
Hello @cncz42, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/356#issuecomment-642182746.
