### ISSUE TITLE
DOOM 64 (1148590)

### ISSUE THREAD

**Issue by CallieEZ** [ValveSoftware/Proton#3966]
# Compatibility Report
- Name of the game with compatibility issues: DOOM 64
- Steam AppID of the game: 1148590

## System Information
- GPU: RTX 2080ti
- Driver/LLVM version: nvidia 440.82
- Kernel version:5.4.43-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/cncz42/262fc6c4732969ec9cc90bbacdd0ffdd
- Proton version: 5.0-8

## I confirm:
- [ *] that I haven't found an existing compatibility report for this game.
- [ *] that I have checked whether there are updates for my system available.

[steam-1148590.log](https://github.com/ValveSoftware/Proton/files/4760486/steam-1148590.log)

## Symptoms
Mice with high polling rates cause heavy fps drops when moving camera with mouse. This affects other "Kex engine" games as well such as BLOOD: FRESH SUPPLY (which I cannot file a report on due to me owning the gog version of that game and using third party tools to use proton with it)

## Reproduction
Start a new game and use a high polling rate mouse to move camera

**Comment by kisak-valve** [comment]
Hello @cncz42, again, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3663#issuecomment-642185695.
