### ISSUE TITLE
Path of Exile does not launch with Proton 5.0-8

### ISSUE THREAD

**Issue by Dragallur** [ValveSoftware/Proton#3969]
Path of Exile appears for a moment in my processes but then it just disappears and does not launch. (Using Ubuntu 18)

**Comment by kisak-valve** [comment]
Hello @Dragallur, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/58#issuecomment-642595613.
