### ISSUE TITLE
Sound issues with Skyrim and Skyrim SE (Possible Solution)

### ISSUE THREAD

**Issue by Xeroderma** [ValveSoftware/Proton#3974]
# Game
- Name of the game: The Elder Scrolls V: Skyrim (Special Edition)
- Steam AppID of the game: 72850, 489830

## System Information
- GPU: NVIDIA GeForce GTX 1080ti
- Driver/LLVM version: nvidia 418.113
- Kernel version: 4.19.0-9-amd64
- Proton version: 5.0

## Symptoms
Sound stops playing after some minutes of play. 
This is a known Engine-Bug of both Skyrim versions. To fix this the game needs to be installed on drive C.
Proton seems to use the Z-drive to load the game, what may lead to this issue.
Reports of players having this issue in windows can be found all across the internet.

## Possible solution
Instead of using the Z-drive to access the game files, a symbolic link could be made pointing into the prefix, so the game could be launched from the c-drive.
The registry would need to be changed accordingly.

**Comment by kisak-valve** [comment]
Hello @Xeroderma, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/460#issuecomment-643259751.
