### ISSUE TITLE
Styx: Shards of Darkness (355790)

### ISSUE THREAD

**Issue by springwurm** [ValveSoftware/Proton#3980]
# Whitelist Request
- Name of the game to be whitelisted: Frontlines: Styx: Shards of Darkness
- Steam AppID of the game: 355790

## System Information
- GPU: AMD Radeon RX 580
- Driver/LLVM version: Mesa 20.1.1
- Distro version: Arch Linux
- Link to full system information report as [Gist](https://gist.github.com/springwurm/10b9ae03c39ad871ce714f01ea4bc384):
- Proton version: 5.0-9

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [X] I haven't experienced any issues.
- [X] There are no issues left open for this game.
- [X] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @springwurm, there's a previous whitelist request for this game at #964, but there's currently a Github bug prevents it from appearing in Github's search which is why it was hard to find.
