### ISSUE TITLE
Wolfenstein II: The New Colossus, unplayable, white flashing screen

### ISSUE THREAD

**Issue by mrjohnc** [ValveSoftware/Proton#3989]
# Compatibility Report
- Name of the game with compatibility issues: Wolfenstein II: The New Colossus
- Steam AppID of the game: 612880

## System Information
- GPU:  Intel UHD Graphics 620 - 1024 MB, Core: 1150 MHz, Integrated
- Driver/LLVM version:  Mesa 20.0.7
- Kernel version:  Linux Kernel 5.6
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/mrjohnc/5a8183d2829cf175ee593979b5a61922
- Proton version: 5.0.9

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

The log is over 20mb, 

## Symptoms 
Some of the opening cutscene plays normally, the rest are just very fast white flashing, once game starts who screen is white flash
[steam-612880.log](https://github.com/ValveSoftware/Proton/files/4782005/steam-612880.log)
ing but with overlay visible. The game is running fine judging from the sound, just can't see anything...

## Reproduction
Start game
Try any graphics setting (I've tried changing resolution and changing all graphics options
[steam-612880.log](https://github.com/ValveSoftware/Proton/files/4781996/steam-612880.log)

**Comment by kisak-valve** [comment]
Hello @mrjohnc, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1113#issuecomment-644281382.

**Comment by mrjohnc** [comment]
OK, thanks

**Comment by mrjohnc** [comment]
> Hello @mrjohnc, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#1113 (comment)](https://github.com/ValveSoftware/Proton/issues/1113#issuecomment-644281382).

posted here https://gitlab.freedesktop.org/mesa/mesa/-/issues/3138
