### ISSUE TITLE
Burnout Paradise Remaster can't run in Debian 10.4

### ISSUE THREAD

**Issue by sandhilt** [ValveSoftware/Proton#4012]
# Compatibility Report
- Name of the game with compatibility issues: Burnout Paradise Remaster Edition
- Steam AppID of the game: 1238080

## System Information
- GPU: GTX 1050 Ti 
- Driver/LLVM version: nvidia 418.113 
- Kernel version: 4.19.0-9-amd64 
- Link to full system information report as [Gist](https://gist.github.com/): [Link](https://gist.github.com/SandHilt/777c8b4de520443bd282418fdd891e13)
- Proton version: 5.0-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Origin install but can't open game like this guys https://www.protondb.com/app/1238080

## Reproduction
1, Install origin setup.
2. Log in origin.
3. Try start (game appear installed) but can't open.

## Extra
- This guy appear can run the game via lutris: https://youtu.be/dezNtc9ZNhs
- I try this method without success. https://lutris.net/games/burnout-paradise-remastered/

**Comment by kisak-valve** [comment]
Hello @SandHilt, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3960#issuecomment-647480081.
