### ISSUE TITLE
The Lord of the Rings Online (212500)

### ISSUE THREAD

**Issue by kasha695** [ValveSoftware/Proton#4013]
# Compatibility Report
- Name of the game with compatibility issues: The Lord of the Rings Online
- Steam AppID of the game: 212500

## System Information
- GPU: GTX 970
- Driver/LLVM version:  4.6.0 NVIDIA 440.82
- Kernel version: 5.7.0-3-MANJARO
- Link to full system information report: [Gist](https://gist.github.com/kasha695/bdbee781324beb1122d45c1190de57cb)
- Proton version: 5.0.9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Using the Overlay to browse the web on about 3-5+ tabs starts to cause significant FPS drops in-game, even after all the tabs and browser are closed.
The FPS drops are interesting because they only occur when the mouse moves, if I leave the mouse still the FPS stays the same even when moving by keyboard, any movement by the mouse and there's significant drops and choppiness.

## Reproduction
1. Launch LOTRO
2. Start using the overlay, open 3+ tabs and go to different sites (e.g. reddit, wikipedia etc)
3. Close tabs and go back to game, move mouse around

**Comment by kisak-valve** [comment]
Hello @kasha695, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1816#issuecomment-647598464.
