### ISSUE TITLE
[DOOM 2016] - Hangs on black screen with all versions of proton (379720)

### ISSUE THREAD

**Issue by vide0hanz** [ValveSoftware/Proton#4016]
# Compatibility Report
- Doom 2016
- 379720

## System Information
- GPU: <Nvidia GTX 1070>
- Driver/LLVM version: <Nvidia 440.82-23>
- Kernel version: <5.7.4.arch1-1>
- Proton version: 5.0-9 - but happens on all versions

## I confirm:
- [x] that I have checked whether there are updates for my system available.

[steam-379720.log](https://github.com/ValveSoftware/Proton/files/4822376/steam-379720.log)

## Reproduction

Nothing specific to note, the game used to work just fine for me a couple of months ago. I have tried launching the game with all current available versions of Proton (no custom builds) and no matter what I do, the game just does not launch correctly. 

I know there are other compatibility reports for this, but since they are closed I figured I'd open a new one - sorry if this is the wrong way to go about it.

**Comment by googleson78** [comment]
Here's another log with the same thing (even the logs look similar)

System-info: https://gist.github.com/googleson78/fc6af74ef1889f70d49ca124be008d31
Log: [steam-379720.log](https://github.com/ValveSoftware/Proton/files/4839320/steam-379720.log)

**Comment by vide0hanz** [comment]
Okay, coming back to this - I don't think this has anything to do with proton. 

I've been having other issues with a couple of native linux titles as well that I recently isolated to a relationship with my audio setup, more specifically when addressing ALSA directly when my primary device is powered on. I have been using an external USB DAC/AMP combo as my primary sound device WITHOUT pulseaudio installed and nearly everything else on my system has worked fine, so I didn't even think this would have anything to do with it until I accidentally discovered that the other titles I was having issues with suddenly launched fine when my DAC/AMP was powered OFF. I was able to successfully reproduce this multiple times -- launching these games with the external USB device powered OFF worked (albeit without audio, of course), powering it ON and then attempting to launch these titles would crash them immediately. 

I decided to install pulseaudio to see if that had anything to do with it, and voila - now those two titles launch and run just fine. I tested this out on Doom 2016 and it launches just fine with pulseaudio installed. I've been able to launch it and run it as expected several times now. 

I haven't ruled out the recent Nvidia driver updates as well as the several steam beta client updates that have been deployed since I originally opened this issue as potentially resolving this, but I suspect since having pulseaudio installed has resolved the other two odd issues I described above that this is most likely related to my recent success with getting Doom 2016 to progress past the intro movie sequence. 

I should note that I did not get around to testing Doom 2016 with my DAC powered OFF so I'm not sure if the game would have progressed past the intro sequence in this scenario. After all, why would anyone play Doom without audio? :D 

Does anyone know if the intro sequences are using a different linux audio system? Those would play just fine when my system was addressing ALSA directly. Many other titles functioned just fine without pulseaudio installed as well -- again, I didn't even think this would have been related in any way. 

This is also **probably** specific to my setup though, but I can't be certain. My system has several audio devices -- onboard audio, a USB dongle for my wireless headset/mic, the Nvidia GPU HDMI audio driver, and my USB DAC are generally all connected and recognized by my system. Its entirely possible that my combination of hardware was mucking things up since I never bothered to write up a proper `.asoundrc` file beyond setting my default device. 

I don't know if any of this is relevant, but figured I should mention this in case anyone else happens to come across something similar. I can't stress enough that this is probably somehow very specific to my combination of hardware since many applications functioned fine without pulseaudio installed, addressing ALSA directly, regardless of the power state of my DAC unit. I have another system which is also addressing alsa directly which does not have these issues, but it only has one device... 

Any thoughts? Sorry for the info dump, just trying to be thorough here :) Please let me know if there are any other scenarios I can test with to provide any necessary info.

**Comment by vide0hanz** [comment]
Closing this because it is not Proton related.

**Comment by lazypingu** [comment]
@vide0hanz Thanks for the hint with ALSA and PulseAudio!
I also had a audio setup with just plain ALSA. I've installed PulseAudio and now the game starts fine and didn't stop on a black screen.
See https://www.gog.com/forum/doom_series/linux_doom_2016/post27 for details.
