### ISSUE TITLE
vrclient_x64 as standalone repo?

### ISSUE THREAD

**Issue by frostworx** [ValveSoftware/Proton#4019]
as
https://github.com/ValveSoftware/Proton/tree/proton_5.0/vrclient_x64

is a static part of the whole Proton project I wonder if it wouldn't be a good idea to implement it as standalone project
and therefore as submodule in proton instead.
you would have better, selective bugreports and easier packagemanagement for all distros.
also it would be easier for the user to see which commits were made, so you could  retest your submitted bug-reports earlier.
btw last commit was 3 months ago - is development stalled in vrclient_x64 or are you working on it behind the scenes?

**Comment by kisak-valve** [comment]
Hello @frostworx, unless a Proton dev directly wants this, there's no point in the additional overhead and coordination needed to split out this subcomponent. Vrclient_x64 is a forwarding library and in general, it only needs to be updated to support new spec versions being forwarded to the native linux SteamVR implementation. Almost all development the end user cares about is in the native linux SteamVR beta.

As for what has changed in it, Github allows you to see per-project-folder history like https://github.com/ValveSoftware/Proton/commits/proton_5.0/vrclient_x64.

**Comment by frostworx** [comment]
hi, @kisak-valve.
thanks for the reply! Sad to see development looks stalled in vrclient_x64.
