### ISSUE TITLE
[782330] - Doom eternal - blinking screen after launching

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#4023]
# Compatibility Report
- Name of the game with compatibility issues: Doom eternal
- Steam AppID of the game: 782330

## System Information
- GPU: GTX 1060 (mobile)
- Driver/LLVM version: NVIDIA 440
- Kernel version: Linux version 5.3.0-61-generic
- Link to full system information report : https://gist.github.com/bobaxxx/e453840a627188f57f4cb20851b5b0fc
- Proton version: 5.0.9

## I confirm:
- [X that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

Game install is OK, but when i start, i can reach the menu, but screen is blinking like hell.

## Reproduction

- Install
- Launch the game (linux mint tricia)

Here is the log :

[log.txt](https://github.com/ValveSoftware/Proton/files/4837341/log.txt)

**Comment by kisak-valve** [comment]
Hello @bobaxxx, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3773#issuecomment-650197295.

**Comment by ghost** [comment]
Ok thx
