### ISSUE TITLE
Titanfall 2 through Proton can't even launch, everytime Origin says "We are unable to connect to EA servers to activate DisplayName field missing from registry. on this computer using your account. Please try again later."

### ISSUE THREAD

**Issue by R0NAM1** [ValveSoftware/Proton#4025]
# Compatibility Report
- Name of the game with compatibility issues: Titanfall 2
- Steam AppID of the game: 1237970

## System Information
- GPU:  RX 470
- Driver/LLVM version:  amdgpu
- Kernel version:  4.19.0-9-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/R0NAM1/a8154858492f71993ef0e08592a44055
- Proton version: 5.0-9

## I confirm:
-

- [O] that I haven't found an existing compatibility report for this game.

- [O] that I have checked whether there are updates for my system available.

 
[steam-1237970.log](https://github.com/ValveSoftware/Proton/files/4838984/steam-1237970.log)

## Symptoms 
When I launch TitanFall 2, it installs Origin, but when it is installed and running, it always gives the error of ""We are unable to connect to EA servers to activate DisplayName field missing from registry. on this computer using your account. Please try again later." Clicking the "Exit" button on the window causes the game to exit.

## Reproduction

It happens every time Origin starts.

**Comment by kisak-valve** [comment]
Hello @R0NAM1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4001#issuecomment-650376223.
