### ISSUE TITLE
Super Neptunia RPG - Not Starting

### ISSUE THREAD

**Issue by LarnuUK** [ValveSoftware/Proton#4028]
# Compatibility Report
- Name of the game with compatibility issues: Super Neptunia RPG
- Steam AppID of the game: 1016960

## System Information
- GPU: Radeon RX 590>
- Driver/LLVM version: 4.6 Mesa 20.2.0-devel (git-c0c03f4 2020-06-27 focal-oibaf-ppa)
- Kernel version: 5.4.0-39-generic
- Link to full system information report as [Gist](https://gist.github.com/): [Gist](https://gist.github.com/LarnuUK/8fc389bc23ca9fb64733967dfaff9eba)
- Proton version: 5.0-9

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. *(Found this [issue](https://github.com/ValveSoftware/Proton/issues/2827) from 2019 with different symptoms.)*
- [x] that I have checked whether there are updates for my system available.

[sn-rpg-5.0-9.log](https://github.com/ValveSoftware/Proton/files/4840902/sn-rpg-5.0-9.log)

## Symptoms
Game doesn't start at all. Clicking play presents nothing on screen apart from play changing to "Stop". After a few seconds, goes back to play. Although not supported here, same behaviour on 5.11-GE-1-MF. [ProtonDB](https://www.protondb.com/app/1016960) does imply it should play with little to no tweaking. Logs don't appear to suggest much, as any errors are ignored.

## Reproduction
Install game. Try to start.

**Comment by kisak-valve** [comment]
Hello @LarnuUK, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2827#issuecomment-650594298.
