### ISSUE TITLE
Fallout 76 (1151340)

### ISSUE THREAD

**Issue by TheChriZ** [ValveSoftware/Proton#4030]
Photo Mode does not save Photos. The folder it is supposed to save them stays empty and so does the ingame gallery and I can not create a Character Picture. Also when I am in photo mode I can only shoot a photo once, afterwards it does nothing when I am hitting spacebar only if I re-enter photo mode.
This problem might not be Linux/Proton specific as I have read about issues like this happen on Windows 10 too and the solution seemed to be disabling the Anti-Virus.
How could this be solved on Linux?

**Comment by kisak-valve** [comment]
Hello @TheChriZ, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3766#issuecomment-650745803.
