### ISSUE TITLE
PS4 controller stopped working for multiple games

### ISSUE THREAD

**Issue by brauliobo** [ValveSoftware/Proton#4032]
After coming back to play after 5 days off, all LEGO games (tested Marvel Super Heroes 1, Jurassic World and Worlds) don't respond to any PS4 controller button.

Using Proton 5.0-9 and latest Archlinux packages.

The problem seems specific to LEGO games and Warplanes: WW1 Sky Aces and it *worked* with "Ball 3D: Soccer Online"

**Comment by kisak-valve** [comment]
Hello @brauliobo, please verify you have an up to date system. In particular, that you've updated from libwacom 1.4-1 to 1.4-2 if you have it installed (if it's not installed, that's fine too). (from https://github.com/ValveSoftware/steam-for-linux/issues/7230)

**Comment by brauliobo** [comment]
thanks, updating libwacom to 1.4-2 fixed it!
