### ISSUE TITLE
Detroit: Become Human stuttering an PS4 controller issues

### ISSUE THREAD

**Issue by Johnnii360** [ValveSoftware/Proton#4035]
# Compatibility Report
- Name of the game with compatibility issues: Detroit: Become Human
- Steam AppID of the game: 1222140

## System Information
- GPU: Nvidia Geforce RTX2070 8GB
- Driver/LLVM version: Nvidia 440.100 (proprietary)
- Kernel version: 5.3.0-61-generic

- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Johnnii360/359a294e615be18c7849948c48ec4f43
- Proton version: Doesn't matter - issue occurs on 5.0-9 and 5.11-GE-2-MF

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1222140.log](https://github.com/ValveSoftware/Proton/files/4856408/steam-1222140.log)

## Symptoms 
The game is mostly working very well but stutters especially in open areas. Another issue is by the PS4 controller. In the drawing scene with Markus the interactions fail. It is a interaction for right thumb stick shown but it doesn't work. 

## Reproduction
I've already tried to loose the FPS lock and set it manually to 4 (no limit) in the config file but it doesn't work. Set the game to 30 FPS lock tempers the issue a bit but it's still present. Regarding to the PS4 controller issue the failed interaction could triggered by mouse.

## Appendix
5.11-GE-2-MF is a hint glitchy in Detroit. 5.11-GE-1-MF works a bit better.

**Comment by kisak-valve** [comment]
Hello @Johnnii360, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4003#issuecomment-652391728.
