### ISSUE TITLE
Space Engineers - Incorrect Launch Location

### ISSUE THREAD

**Issue by BloodBlight** [ValveSoftware/Proton#4037]
When attempting to launch Space Engineers in Linux using the Steam Linux Runtime, it failed due to the binary being in the "Bin64" folder rather than "Bin".

Screenshot:
https://imgur.com/a/pHayD94

**Comment by kisak-valve** [comment]
Hello @BloodBlight, the Steam Linux Runtime compatibility tool is a container environment to run Linux native games on Linux. It is not Proton. Please retest with Proton and report any issues with Space Engineers in #1792.
