### ISSUE TITLE
Age of Empires II: Definitive Edition out of sync

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#4038]
Hey, wanted to report a multiplayer issue with Age of Empires II: Definitive Edition.

Every time you go to play multiplayer with someone it will bring up a message saying out of sync and say that the host disconnected. I tested the game in Windows and it works but I have also seen a bunch of reports about this issue but can confirm the multiplayer is not working correctly at the moment using the latest proton 5

**Comment by kisak-valve** [comment]
Hello @coreybruce, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3189#issuecomment-652735033.
