### ISSUE TITLE
[Feature Request] Ability to choose between Proton and native Linux versions in Steam client

### ISSUE THREAD

**Issue by robertc** [ValveSoftware/Proton#404]
Some games which have a native Linux port (e.g. Tomb Raider 2013, Company of Heroes 2) do not allow multiplayer with Windows users.  I would like to be able to choose to install either version in order to play with my friends, at the moment we can only install the native Linux version of such games.

**Comment by kisak-valve** [comment]
Hello @robertc, this feature request is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5638. Closing as a duplicate.
