### ISSUE TITLE
Trailmakers

### ISSUE THREAD

**Issue by UltraBlackLinux** [ValveSoftware/Proton#4046]
# Compatibility Report
- Name of the game with compatibility issues: Trailmakers
- Steam AppID of the game: 585420

## System Information
- GPU: Asus RX 560
- Driver/LLVM version: Mesa 20.0.7
- Kernel version: 5.6.16-1
- Link to full system information report as [Gist](https://gist.github.com/UltraBlackLinux/9f236ace63c590f933b20e926254a5d4):
- Proton version: I tried every version

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. (I hope a whitelist request isnt the same)
- [x] that I have checked whether there are updates for my system available.

[steam-585420.log](https://github.com/ValveSoftware/Proton/files/4879042/steam-585420.log)

## Symptoms 
Trailmakers doesnt start, this is the console output:

GameAction [AppID 585420, ActionID 6] : LaunchApp changed task to ShowLaunchOption with ""
GameAction [AppID 585420, ActionID 6] : LaunchApp waiting for user response to ShowLaunchOption ""
GameAction [AppID 585420, ActionID 6] : LaunchApp continues with user response "0"
GameAction [AppID 585420, ActionID 6] : LaunchApp changed task to ProcessingInstallScript with ""
/data/src/clientdll/installscript_posix.cpp (418) : Assertion Failed: Standalone evaluator returned error code for app 585420
GameAction [AppID 585420, ActionID 6] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 585420, ActionID 6] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 585420, ActionID 6] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 585420, ActionID 6] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 585420, ActionID 6] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 585420 "", ProcID 10504, IP 0.0.0.0:0
Starting app 585420
.>>> Adding process 10504 for game ID 585420
GameAction [AppID 585420, ActionID 6] : LaunchApp changed task to WaitingGameWindow with ""
.>>> Adding process 10505 for game ID 585420
GameAction [AppID 585420, ActionID 6] : LaunchApp changed task to Completed with ""
Game removed: AppID 585420 "", ProcID 10504 
Exiting app 585420
No cached sticky mapping in ActivateActionSet.

## Reproduction
Start Trailmakers

**Comment by kisak-valve** [comment]
Hello @UltraBlackLinux, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3409#issuecomment-654235762.

**Comment by UltraBlackLinux** [comment]
ok thanks ;)
