### ISSUE TITLE
Getting 32-bit games running out of the box

### ISSUE THREAD

**Issue by afettouhi** [ValveSoftware/Proton#4052]
One issue I still have with Proton is some older games like Giana Sisters: Twisted Dreams, Giana Sisters: Twisted Dreams - Rise of the Owlverlord & Aliens: Colonial Marines Collection these require 32-bit wine bottles. In the case of Giana Sisters it requires wmp10 which only available in 32 bit. Are there any patches atc. to make those games run with this custom version of Proton?

**Comment by kisak-valve** [comment]
Hello @afettouhi, this feature request is already being tracked at #449. Closing as a duplicate.

**Comment by frostworx** [comment]
Hey @afettouhi
Just searching for games depending on wmp10 and found this issue.
You might want to try my brandnew : https://github.com/frostworx/steamtinkerlaunch/releases/tag/v1.4.3
which supports both Gianas ootb.

**Comment by afettouhi** [comment]
Cool, I have to try that. Does Aliens: Colonial Marines work with this?

**Comment by frostworx** [comment]
no idea yet :)

**Comment by frostworx** [comment]
@afettouhi 49540 is CEG protected, the crash doesn't have anything to do with wmp10.
See ACM.exe.[0-9]{3}'.STEAMSTART in gamedir.
In fact is also has an open issue https://github.com/ValveSoftware/Proton/issues/3810

**Comment by afettouhi** [comment]
Didn't know that the game used Valve's CEG DRM. I was aware that wmp10 was not an issue with it. Do you happen to know what is meant here in this comment?

https://github.com/ValveSoftware/Proton/issues/3810#issuecomment-620189184

**Comment by frostworx** [comment]
CEG copy protection works fine via wine, when the whole steam client is running inside wine.
The linux native steam client simply doesn't have CEG support. Would be nice if CEG would be simply patched out, but looks like the few games depending on it are not relevant enough to work on this.
There are drm free builds of several games (f.e. on GOG) which don't have CEG. Copying their exe to the steam game often 
*just works*
