### ISSUE TITLE
naruto shippuden ultimate ninja storm 4 crash at startup

### ISSUE THREAD

**Issue by ninch1** [ValveSoftware/Proton#4053]
when i open naruto shippuden ultimate ninja storm 4 it opens 3 sec and then exits please help

**Comment by kisak-valve** [comment]
Hello @claimax10, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2389#issuecomment-655578252.

**Comment by Tinki01** [comment]
hello I have a problem with naruto storm 4 qaund I use the proton 7.05 its blocking and also the experimental proton I also have the same problem help me please when I want to play the story mode the fight between hashirama and madara its blocking

**Comment by Tinki01** [comment]
![Uploading IMG_5153.jpeg…]()
