### ISSUE TITLE
FINAL FANTASY XIII-2 (controller issues when in begin game menu) (292400)

### ISSUE THREAD

**Issue by robzombie91** [ValveSoftware/Proton#4056]
# Compatibility Report
- Name of the game with compatibility issues: FINAL FANTASY XIII-2
- Steam AppID of the game: 292410

## System Information
- GPU: NVIDIA GTX 1070
- Driver/LLVM version: 440.66.17
- Kernel version: 5.7.7-15
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/85a2d5bd5a8427dc6da0aca6990ce2d8
- Proton version:  WINE 5.12-TKG

[output.log](https://github.com/ValveSoftware/Proton/files/4893665/output.log)

## Reproduction:
Start game (lutris or wine), click new game, select normal mode, controller doesnt work anymore (using either an xbox one s controller or ps4 controller)

**Comment by kisak-valve** [comment]
Hello @robzombie91, this issue tracker is for games run with Proton from the Steam for Linux client. While your feedback is appreciated, this can't be used to improve Proton.

`002c:fixme:winediag:__wine_start_process Wine TkG 5.12 is a testing version containing experimental patches.
002c:fixme:winediag:__wine_start_process Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.`
