### ISSUE TITLE
Can't launch Proton games through Steam, but they run from terminal

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#4057]
#### Your system information

* Steam client version (build number or date): Jul 8 2020
* Distribution (e.g. Ubuntu): Ubuntu Studio 20.04 (System info [here](https://gist.github.com/penguout/d69b947b7a599dc189b095f1122674e6))
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Any game I try launching through Proton quits after a few seconds without actually starting. This issue started happening a few days ago. 

I can launch the exact same game through terminal, using the Proton wineprefix and wine binary, like so:
```WINEPREFIX=/path/to/steam/proton5/dist/share/default_pfx/ /path/to/steam/proton5/dist/bin/wine /path/to/steamlibrary/SomeGame/SomeGame.exe```

Games run perfectly fine with the above command. Of course there's no Steam overlay. Given that it seems Proton itself still works, I'm opening this under steam-for-linux

Tried a fresh install of my OS as well as a new user in /home/, with no success.

Here are log outputs from Rocket League as an example. Other games behave similarly.
[Steam terminal output](https://gist.github.com/penguout/49b8f427a9f026b8a217e3c30dfe1021)
[Application log (steam-252950.log)](https://gist.github.com/penguout/e6545fa024101d43b78ec00461d8fce0)

EDIT: Running games with PROTON_USE_WINED3D=1 allows them to launch as a workaround.

#### Steps for reproducing this issue:

1. Choose "Enable Steam Play for all other titles" in settings.
2. Launch any game forcing the use of Proton

**Comment by aeikum** [comment]
Definitely don't try to launch games manually from the command-line like that. It's not supported and it may break your installation. I'd suggest wiping your Proton installation and re-verifying its files, as you may have broken the default prefix by running things in it.

If games are working with wined3d, that hints that you may have a broken Vulkan installation.

**Comment by jibarofoss** [comment]
Something similar happened to me today on Arch Linux and it was caused by today's Vulkan upgrades.

**Comment by kisak-valve** [comment]
Hello @jibarofoss, the system information from @penguout indicates that libvulkan.so.1 1.2.135 from the Steam runtime is being used, which means that the general issue that's appeared with vulkan-loader 1.2.145 -> 1.2.146 is unrelated to this issue report.

**Comment by C0rn3j** [comment]
@jibarofoss You can follow this bug for the `1.2.145 -> 1.2.146` issue on Arch https://bugs.archlinux.org/task/67277

**Comment by skain80** [comment]
Thanks! i was going crazy!

**Comment by ghost** [comment]
Thanks for the response @aeikum. As you suggested, this was an issue with the Vulkan install. Everything's good now!

(If anyone's curious, switching from amdgpu to amdgpu-pro did the trick)
