### ISSUE TITLE
GTA IV offline mode inaccessible

### ISSUE THREAD

**Issue by sipsu** [ValveSoftware/Proton#4063]
# Compatibility Report
- Name of the game with compatibility issues: Grand Theft Auto IV: The Complete Edition (Rockstar launcher)
- Steam AppID of the game:  12210

## System Information
- GPU: GeForce GTX 650
- Driver/LLVM version: nvidia 390.138
- Kernel version: 4.15.0-109-generic
- Proton version: 5.0-9

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-12210.log](https://github.com/ValveSoftware/Proton/files/4910054/steam-12210.log)
## Symptoms 
The game will not allow offline mode. Game does not allow saves and SocialClub says "Offline Mode Not Available".
[steam-12210.log](https://github.com/ValveSoftware/Proton/files/4910051/steam-12210.log)

Rockstar launcher (opened independently via proton) runs successfully, but does not recognized GTA IV as being owned or installed (as it does under Windows).

To open RockStar launcher:
PRELOAD=:/home/user/.steam/ubuntu12_32/gameoverlayrenderer.so:/home/user/.steam/ubuntu12_64/gameoverlayrenderer.so STEAM_COMPAT_DATA_PATH="/home/user/.steam/steam/steamapps/compatdata/12210/" /home/user/.steam/steam/steamapps/common/Proton\ 4.11/proton waitforexitandrun /home/user/.steam/steam/steamapps/compatdata/12210/pfx/drive_c/Program\ Files/Rockstar\ Games/Launcher/LauncherPatcher.exe

**Comment by kisak-valve** [comment]
Hello @sipsu, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/350#issuecomment-657307857.
