### ISSUE TITLE
Access Uplay settings

### ISSUE THREAD

**Issue by teunissenstefan** [ValveSoftware/Proton#4064]
I recently bought Watch Dogs 2 and the game itself is working without any problems. I however have this in my screen and I can't get rid of it:
![image](https://user-images.githubusercontent.com/1182849/87354087-41d07680-c55e-11ea-8b4c-bbbbe3ed1450.png)
I also can't open the Uplay overlay. I know you can disable it in the Uplay settings, but how do I start Uplay without starting Watch Dogs 2 so I can go into the settings? I tried going into the Watch Dogs 2 C:/ drive and starting Uplay from there but it seems to not be the same as the one that actually launches the game because:

- When I change a setting there, it doesn't translate into the Uplay that starts Watch Dogs 2
- It thinks Watch Dogs 2 isn't installed

**Comment by kisak-valve** [comment]
Hello @teunissenstefan, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/172#issuecomment-657807374.
