### ISSUE TITLE
AC Odyssey doesn't work in full-screen mode.

### ISSUE THREAD

**Issue by Dimitrov1295** [ValveSoftware/Proton#4065]
# Compatibility Report
- Name of the game with compatibility issues: Assassins' Creed Odyssey
- Steam AppID of the game: 812140

## System Information
- GPU: GP106M [GeForce GTX 1060 Mobile]
- Driver/LLVM version: Nvidia 440.100
- Kernel version: 5.4.0-40-generic
- Link to full system information report as [Gist](https://gist.github.com/):  https://gist.github.com/Dimitrov1295/86a4497f908a65db9937aeee761951ee
- Proton version: 5.0-9

## I confirm:
- [ yes] that I haven't found an existing compatibility report for this game.
- [ yes] that I have checked whether there are updates for my system available.

[steam-812140.log](https://github.com/ValveSoftware/Proton/files/4915271/steam-812140.log)

## Symptoms 

This is what the game looks like when I start it in fullscreen: https://prnt.sc/th6469
It doesn't look like that when I run it in borderless mode.

## Reproduction 

It does it 99% of the time I launch it.
![Screenshot from 2020-07-13 22-01-55](https://user-images.githubusercontent.com/33392789/87355725-c15b4700-c558-11ea-9e89-b05c95594e42.png)

**Comment by kisak-valve** [comment]
Hello @Dimitrov1295, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1757#issuecomment-657808409.
