### ISSUE TITLE
[DOOM 2016] Game hangs on black screen (379720)

### ISSUE THREAD

**Issue by alraspe** [ValveSoftware/Proton#407]
I've seen this issue all over this GitHub but I've yet to have found a fix that works for me. I'm running Arch Linux btw. I'm already running Steam in Runtime by default because for some reason it forces me to regardless of whether of not I start from the Native launcher. Both API's (Vulkan and OpenGL) result in the same black screen hang.

**Comment by kisak-valve** [comment]
Hello @MSTVIRUS, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by alraspe** [comment]
https://gist.github.com/MSTVIRUS/2e6d80dc0ba2c75afbdf88fb60f308f7
There's my system info
Dunno if you want it in the original post or not

**Comment by Elkasitu** [comment]
Have you tried [skipping the intro cinematic](https://github.com/ValveSoftware/Proton/issues/286#issuecomment-415721856)?

**Comment by alraspe** [comment]
No I haven't. Trying right now

**Comment by alraspe** [comment]
That strangely worked. Thanks! I got it working last night but then this morning it stopped working for some reason.
