### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by rodrigobbarros** [ValveSoftware/Proton#4071]
I'm trying to run red dead redemption 2 with proton-5.0-rdr2-4 and I'm using the boot command WINEDLLOVERRIDES = "dxgi = n, b" taskset -c 0-7% command%
and it opens but has a completely black window screen,
If I take the command, it won't even open.
Does anyone know how to help me?
I'm using ubuntu 20.04 lts
i7-7700hq cpu
nvidia gtx 1050ti gpu with 440.100 driver

**Comment by kisak-valve** [comment]
Hello @rodrigobbarros, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-659072802.
