### ISSUE TITLE
Proton for the Rockstar Launcher version of RDR2

### ISSUE THREAD

**Issue by kenkaniffer** [ValveSoftware/Proton#4076]
Hello lads, I saw that there is a working steam version of the Red Dead Redemption 2, the problem is that I have the rockstar launcher version of the game and I cant make it run no matter what, I tried putting the mrpippys proton version into the compatibilitytools.d folder and even the lutris/wine folder but lutris wont detect this version and even when it once did it simply didnt want to run, Is there any way to make this game run without the steam version ?

Any help is really appreciated.

**Comment by kisak-valve** [comment]
Hello @kenkaniffer, we're using one issue per unofficially supported game title, and usually I'd transfer this issue to #3291, but this is clearly a Lutris issue, not a Proton issue. Please use the Lutris forums to get support.

**Comment by kenkaniffer** [comment]
Will do, and thanks for letting me know  @kisak-valve
