### ISSUE TITLE
ReShade doesn't work under Proton but works with DXVK/Wine

### ISSUE THREAD

**Issue by GottaSlay** [ValveSoftware/Proton#4079]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
 ReShade functionality for games ran via Proton

## Justification [optional] 
It already works if the game is ran via Wine and DXVK but not if the game is ran via Proton

## Risks [optional] 
None
## References [optional] 
#2908 Has the same issue but it has been closed. The tip mentioned there to use `WINEDLLOVERRIDES="dxgi=n,b;d3dcompiler_47=n"` as launch options does not work for me.

I generated a proton log file and it has a bunch of `fixme:dxgi` lines in it that do not appear when running a game with Wine/DXVK. I genuinely hope they prove useful and we can have ReShade working under proton.
[steam-306130.log](https://github.com/ValveSoftware/Proton/files/4939158/steam-306130.log)

**Comment by GottaSlay** [comment]
I had a typo in my launch options.

Using this as a launch options fixes the issue: `WINEDLLOVERRIDES="dxgi=n,b" %command%`

**Comment by jarrard** [comment]
I have been running into a issue lately after allot of testing with configurations and fresh OS installs where reshade was causing all games to freeze up if I use keyboard input.  The games would unfreeze after 30seconds or so, it was like reshade got saturated with keyboard inputs somehow and froze games..

Anyone have this issue? not sure what could be cause.  Might try and spare USB keyboard.
