### ISSUE TITLE
No Man's Sky "No connection to matchmaking services" with Proton 5.0-9, works with 4.11-13

### ISSUE THREAD

**Issue by JPLeBreton** [ValveSoftware/Proton#4082]
# Compatibility Report
- Name of the game with compatibility issues: No Man's Sky
- Steam AppID of the game: 275850

## System Information
- GPU: 
- Driver/LLVM version: nvidia 440.82
- Kernel version: 5.4.44-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/JPLeBreton/27ee957c57ea36298312ca3a09eadd70
- Proton version: 5.0-9

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-275850.log](https://github.com/ValveSoftware/Proton/files/4941967/steam-275850.log)

## Symptoms 
Can't play multiplayer since the game's Cross Play Update last month. The older release version of Proton, 4.11-13, doesn't seem to have this issue.
Note that I can still connect to the game's "discovery services", ie the server that lets players log and see each other's discovered planets, bases, etc, just fine. I believe that's a whole separate kind of network access.

## Reproduction
1. Launch the latest version of the game (2.60) with Proton 5.0-9.
2. Load a savegame.
3. Enter the options menu, and select the "network" section.
4. Observe: a box pops up that says "No connection to matchmaking services".
5. Quit the game and set it to run using Proton 4.11-13 instead.
6. Relaunch the game, load a save and enter the same options menu.
7. Observe: networking error doesn't occur as before.

Expected behavior: Multiplayer works with all versions of Proton.

**Comment by kisak-valve** [comment]
Hello @JPLeBreton, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-660514671. Seen previously around https://github.com/ValveSoftware/Proton/issues/438#issuecomment-648231884.

**Comment by colla69** [comment]
@JPLeBreton 
Thank you kind stranger for finding for asking this question :)
I am finally online again :)
