### ISSUE TITLE
Use NVIDIA NGX library for DLSS upscaling - possible? Planned?

### ISSUE THREAD

**Issue by kakra** [ValveSoftware/Proton#4084]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

NVIDIA released the 450.57 driver update which is supposed to support AI upscaling in Linux which is probably provided by the NGX library that comes with the driver. It looks like also the Vulkan beta 450.56 has this library.

## Justification [optional] 

Proton has the fshack patches which provide upscaling from the game resolution to native screen resolution. It would be a logical step to integrate AI upscaling there so all games could benefit.

**Comment by doitsujin** [comment]
Not really possible since the NGX API is not public.

**Comment by DanMan** [comment]
Is this now possible with the 470 driver? https://www.nvidia.com/download/driverResults.aspx/176525/en-us

> Added an NVIDIA NGX build for use with Proton and Wine. A new library,nvngx.dll, has been added to enable driver-side support for running Windows applications which make use of DLSS. Changes to Proton, Wine, and other third-party software are needed for this feature.

Or is this something that ought to be implemented directly in Wine instead of Proton? Or is the issue still that the API isn't public?

**Comment by kisak-valve** [comment]
Hello @DanMan, see https://github.com/ValveSoftware/Proton/pull/4877, https://github.com/ValveSoftware/Proton/pull/4878, https://github.com/ValveSoftware/wine/pull/111.
