### ISSUE TITLE
Magicka 2 can't launch through steam linux platform

### ISSUE THREAD

**Issue by y-hsien** [ValveSoftware/Proton#4090]
# Compatibility Report
- Magicka 2 can't launch through steam linux platform:
- app/238370

I can play this game normally but now I can't. I don't know why

## System Information
- GPU: msi gtx 1660ti ventus
- mesa 18.3.6-2+deb10u1,  nvidia       440.100-1~bpo10+1 
- Kernel version: 4.19.0-9-amd64, linuxmint lmde latest version
- https://termbin.com/nu9w

below shown when launch by terminal
gine $ ./Magicka2_x64
./Magicka2_x64: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.1' not found (required by ./Magicka2_x64)
./Magicka2_x64: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./Magicka2_x64)
./Magicka2_x64: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./Magicka2_x64)

but
I actually have those files

$ ls -l /usr/lib/x86_64-linux-gnu/{libcrypt*,libssl*}
-rw-r--r-- 1 root root 53K May 2 2019 /usr/lib/x86_64-linux-gnu/libcrypt.a
-rw-r--r-- 1 root root 5.2M Apr 21 04:23 /usr/lib/x86_64-linux-gnu/libcrypto.a
lrwxrwxrwx 1 root root 16 Apr 21 04:23 /usr/lib/x86_64-linux-gnu/libcrypto.so -> libcrypto.so.1.1
lrwxrwxrwx 1 root root 11 Jul 23 18:22 /usr/lib/x86_64-linux-gnu/libcrypto.so.10 -> libcrypt.so
lrwxrwxrwx 1 root root 16 Jul 9 12:42 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 -> libcrypto.so.1.1
-rw-r--r-- 1 root root 2.9M Apr 21 04:23 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
lrwxrwxrwx 1 root root 35 May 2 2019 /usr/lib/x86_64-linux-gnu/libcrypt.so -> /lib/x86_64-linux-gnu/libcrypt.so.1
-rw-r--r-- 1 root root 349K Jul 9 02:37 /usr/lib/x86_64-linux-gnu/libssl3.so
-rw-r--r-- 1 root root 978K Apr 21 04:23 /usr/lib/x86_64-linux-gnu/libssl.a
lrwxrwxrwx 1 root root 13 Apr 21 04:23 /usr/lib/x86_64-linux-gnu/libssl.so -> libssl.so.1.1
lrwxrwxrwx 1 root root 13 Jul 23 18:21 /usr/lib/x86_64-linux-gnu/libssl.so.10 -> libssl.so.1.1
lrwxrwxrwx 1 root root 13 Jul 23 18:22 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 -> libssl.so.1.1
-rw-r--r-- 1 root root 580K Apr 21 04:23 /usr/lib/x86_64-linux-gnu/libssl.so.1.1

- Proton version: 

## I confirm:
- [V] that I haven't found an existing compatibility report for this game.
- [V] that I have checked whether there are updates for my system available.

## Reproduction
every time i click "play" button on steam user interface

**Comment by kisak-valve** [comment]
Hello @blytheren, Proton is a compatibility tool to run Windows games on Linux. The native Linux version of games is out of scope for this project. You'll want to ask around the Steam forums if anyone else has encountered this issue and/or let the game's dev(s) know about your issue.
