### ISSUE TITLE
SCP: Secret Laboratory (700330)

### ISSUE THREAD

**Issue by ominitay** [ValveSoftware/Proton#4094]
# Compatibility Report
- Name of the game with compatibility issues: SCP: Secret Laboratory
- Steam AppID of the game: 700330

## System Information
- GPU: RX 580 (8GB)
- Driver/LLVM version: 4.6 Mesa 20.1.3
- Kernel version: 5.7.10-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/Ominitay/4651c11e40dfaa8432fa2bacb75db080):
- (All tested) Proton versions: 5.0-9, 5.9-GE-1-MF, 5.9-GE-2-MF, 5.9-GE-3-ST, tkg 5.13.r1.g26d3815d

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Log
[steam-700330.log](https://github.com/ValveSoftware/Proton/files/4977488/steam-700330.log)

## Symptoms 
Starting the game with Proton (tried with multiple GE and TKG versions as well) results in the game hanging in the background. It continues to use CPU, but ultimately does nothing. Neither forcing OpenGL, or disabling Esync and Fsync help.

## Reproduction
1. Install SCP: SL. 
2. Run it with Proton.
3. Result.

**Comment by aidenmadaffri** [comment]
I can confirm this result also on Arch with a GTX 1080.

**Comment by AlmightyLks** [comment]
Confirmation from my side as well.
Ubuntu 20.04 | AMD Radeon RX 5700 XT

**Comment by GottaSlay** [comment]
Same issue here on Manjaro using RX5700.

**Comment by PaintedCat** [comment]
Vega 8,Debian Sid. This issue.

**Comment by tidle** [comment]
Same issue

**Comment by ominitay** [comment]
Resolved by new update.

**Comment by tidle** [comment]
I'm still having the same issue

**Comment by ominitay** [comment]
Make sure you are up-to-date, and using GE or TKG Proton.

**Comment by tidle** [comment]
What are GE or TKG Proton? I am just using regular Steam Play

**Comment by ominitay** [comment]
Steam Play Proton doesn't work with SCP:SL for whatever reason. GE and TKG Proton are custom versions of Proton with modifications applied to improve support and performance. [GE Releases](https://github.com/GloriousEggroll/proton-ge-custom/releases) and [TKG Releases](https://github.com/Frogging-Family/wine-tkg-git/releases). Just follow the instructions on the README.md for GE Proton, and you should be good!

**Comment by tidle** [comment]
Ok.  Should I uninstall and reinstall SCP:SL?

**Comment by ominitay** [comment]
> Ok. Should I uninstall and reinstall SCP:SL?

You don't have to reinstall SCP:SL. If you want to be safe, you can delete the prefix before using GE or TKG Proton, but you shouldn't *need* to.

**Comment by tidle** [comment]
Delete the prefix? What does that mean?

**Comment by ominitay** [comment]
Go to your Steam library, and in the folder named compatdata, there should be a bunch of folders named by numbers, one for each game. You may delete the one with SCP:SL's gameid (700330).

The default path is ~/.steam/steam/steamapps/compatdata/700330

**Comment by tidle** [comment]
Thank you for the help, it runs!

**Comment by ominitay** [comment]
I'm glad that I could -- enjoy the game!
