### ISSUE TITLE
Vulkan Driver install?

### ISSUE THREAD

**Issue by Supervisor83** [ValveSoftware/Proton#4097]
Hello,

99% of Windows games did not work. One game pointed out to me that the Vulkan libs were missing. Was unknown to me until then. After consultation with the publisher I got a link to the Vulkan driver on Github, since then all Windows games work without problems.

My question, why doesn't Steam install it automatically? After I installed it from Github, only then did Steam install additional Vulkan files?

Steam didn't point out to me what was missing and the games either just quit or an error message appeared. Except for one game (JackBoxParty Pack 3)

Best regards
Supervisor83

**Comment by msmafra** [comment]
I think the answer is drivers are system wide installations. Like you install your AMD or NVIDIA drivers you'll install Vulkan drivers.
Which distro are you on?

**Comment by msmafra** [comment]
> Hello,
> 
> 99% of Windows games did not work. One game pointed out to me that the Vulkan libs were missing. Was unknown to me until then. After consultation with the publisher I got a link to the Vulkan driver on Github, since then all Windows games work without problems.
> 
> My question, why doesn't Steam install it automatically? After I installed it from Github, only then did Steam install additional Vulkan files?
> 
> Steam didn't point out to me what was missing and the games either just quit or an error message appeared. Except for one game (JackBoxParty Pack 3)
> 
> Best regards
> Supervisor83

I think the answer is drivers are system wide installations. Like you install your AMD or NVIDIA drivers you'll install Vulkan drivers.
Which distro are you on?

**Comment by Supervisor83** [comment]
I use Debian 10 (Buster) 64bit and the Vulkan drivers were completely unknown to me until recently.

Thanks for your answer.

**Comment by kisak-valve** [comment]
Hello @Supervisor83, Steam's base requirements is for there to be approximately OpenGL 2.0 era hardware available, well below what we expect for Proton to need. Vulkan support is not a hard requirement for most native linux games, so it isn't enforced as a baseline requirement on all systems.

Additionally, installation of system packages requires elevated permissions and that's better left to the system's administrator.

There is a feature request on Steam's side to make this easier to figure out at https://github.com/ValveSoftware/steam-for-linux/issues/6445.

Closing because this isn't a Proton issue.

**Comment by msmafra** [comment]
> I use Debian 10 (Buster) 64bit and the Vulkan drivers were completely unknown to me until recently.
> 
> Thanks for your answer.
You're welcome. Glad it was useful.
I'm on Fedora, I am not sure about Debian and related, but there are some mesa-vulkan-drivers, vulkan-headers etc.

**Comment by Supervisor83** [comment]
> > I use Debian 10 (Buster) 64bit and the Vulkan drivers were completely unknown to me until recently.
> > Thanks for your answer.
> > You're welcome. Glad it was useful.
> > I'm on Fedora, I am not sure about Debian and related, but there are some mesa-vulkan-drivers, vulkan-headers etc.

I think this applies to all Linux distros. I have an AMD graphics card

https://github.com/GPUOpen-Drivers/AMDVLK/releases

**Comment by msmafra** [comment]
> > > I use Debian 10 (Buster) 64bit and the Vulkan drivers were completely unknown to me until recently.
> > > Thanks for your answer.
> > > You're welcome. Glad it was useful.
> > > I'm on Fedora, I am not sure about Debian and related, but there are some mesa-vulkan-drivers, vulkan-headers etc.
> 
> I think this applies to all Linux distros. I have an AMD graphics card
> 
> https://github.com/GPUOpen-Drivers/AMDVLK/releases

Actually I was referring to the packages names that I don't know if the names would be the same.
