### ISSUE TITLE
Batman Arkham Asylum Proton 3.7 is missing dot.net 2.0 and physx install

### ISSUE THREAD

**Issue by fcmircea** [ValveSoftware/Proton#4098]
Game installs fine and everything but then fails on launch with the follow error:

Failed to compile global shader

Issue seems to have been indentfied by lutris users here:

https://forums.lutris.net/t/batman-arkhan-asylum-goty-crash-solved/1268

The same update should be made to the steam / proton environment for the game to function properly.

**Comment by kisak-valve** [comment]
Hello @fcmircea, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/421#issuecomment-664682242.
