### ISSUE TITLE
Conqueror's Blade (905370)

### ISSUE THREAD

**Issue by Sporknife** [ValveSoftware/Proton#4099]
# Compatibility Report
- Name of the game with compatibility issues: Conqueror's Blade (season IV)
- Steam AppID of the game: 905370

## System Information
- GPU: RX 480
- Driver/LLVM version: Mesa 20.1.4/ACO
- Kernel version: 5.7.7-17-tkg-pds, 5.7.10-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/RubixPower/d7645e11a9c4c0a704b7bd0db4e4e35b)
- Proton version: 5.0-9

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I haven't found an existing compatibility report for this game on github.
- [x] that I have checked whether there are updates for my system available.

## Logs
- [Proton log file](https://github.com/ValveSoftware/Proton/files/4988498/steam-905370.log)
- [Game log file](https://github.com/ValveSoftware/Proton/files/4988526/main.log)

## Symptoms 
The game doesn't launch and a error window appears.
![Screenshot from 2020-07-28 13-23-07](https://user-images.githubusercontent.com/48149258/88670356-401dbb80-d0e5-11ea-92ae-33e764761b93.png)

## Reproduction
Run the game.

## Extra
Link to other reports on [ProtonDB reports](https://www.protondb.com/app/905370).

**Comment by cvelasco88** [comment]
I have the same error. Just in case I attach my logs

[steam-905370.log](https://github.com/ValveSoftware/Proton/files/5003866/steam-905370.log)
[steam-905370_before_press_play.log](https://github.com/ValveSoftware/Proton/files/5003867/steam-905370_before_press_play.log)

**Comment by ZeoWorks** [comment]
It has a weird russian anti-cheat also.
The game won't even run on windows 10 virtual machines.

**Comment by milpster** [comment]
Why has this been closed? It is still very much relevant. I am getting the same error. However if i start the "proven_ground_client.exe" the game actually launches but without steam connection. What is the status here? What can i do to support this?

**Comment by Sporknife** [comment]
@milpster the game isn't officially supported and (iirc) they use their own AC that probably uses some windows kernel stuff.  So cooperation from the Conquere's Blade AC devs would probably be needed to make it work with proton(wine).

**Comment by milpster** [comment]
> 
> 
> @milpster the game isn't officially supported and (iirc) they use their own AC that probably uses some windows kernel stuff. So cooperation from the Conquere's Blade AC devs would probably be needed to make it work with proton(wine).

Thanks for replying so quickly!

Yes they use "mrac" which is mail.ru anticheat - mail.ru seems to be involved corporate wise.

And there is no sort of mapping of kernel calls i could do to support this cause? I now have the working game on dualboot anyways.

I'm a dev myself and willing to learn and support the project if you can point me in the right direction.

**Comment by Sporknife** [comment]
Proton(wine) currently doesn't support windows kernel operations. So to support the AC their AC devs would need to cooperate with wine devs. You can't do anything personally because its a company issue and not something a single person can resolve.

**Comment by milpster** [comment]
> Proton(wine) currently doesn't support windows kernel operations. So to support the AC their AC devs would need to cooperate with wine devs. You can't do anything personally because its a company issue and not something a single person can resolve.

Thank you for elaborating.

There are only two questions i have left:

- You say "wine doesn't support windows kernel operations" - has noone started a subproject to add or map or reverse engineer any sort of kernel operations so we can do the compatibility mapping to the linux kernel?

- As i mentioned in the original post there is an international/chinese version of conquerors blade, which seems to use the same anti cheat software, but a different launcher. It starts and runs without problems.

**Comment by Sporknife** [comment]
> > Proton(wine) currently doesn't support windows kernel operations. So to support the AC their AC devs would need to cooperate with wine devs. You can't do anything personally because its a company issue and not something a single person can resolve.
> 
> Thank you for elaborating.
> 
> There are only two questions i have left:
> 
> * You say "wine doesn't support windows kernel operations" - has noone started a subproject to add or map or reverse engineer any sort of kernel operations so we can do the compatibility mapping to the linux kernel?

I don't know. I am not a wine dev but a simple user of it. I suggest you check Collabora or some other source if there is some mention of it being done.

> * As i mentioned in the original post there is an international/chinese version of conquerors blade, which seems to use the same anti cheat software, but a different launcher. It starts and runs without problems.

Seems weird to me. I suggest you don't play with proton until it's confirmed that you won't get banned by their AC (which would suck).

Make a thread on their forum or something and ask them if they plan to support Linux through proton(wine).
Reminder: I am just a user like yourself so don't take my words like they are from a Valve empleyee.

**Comment by arch-user-france1** [comment]
The game works by running proven_ground_client.exe directly? Haha the worst anticheat. It could be possible to let proton just run that file instead of the launcher am I right?

**Comment by arch-user-france1** [comment]
yep it crashes as soon the start-video's finished. Maybe it's possible to spoof that it got checked or .. idk

**Comment by arch-user-france1** [comment]
Checking your browser before accessing guidedhacking.com.

This process is automatic. Your browser will redirect to your requested content shortly.

Please allow up to 5 seconds…
DDoS protection by Cloudflare
Ray ID: 6b7ddb071ee401e3 

I can't access cloudflare sites with javascript challenge anymore because I use a proxy.. It sucks

But it looks like there are some bypasses.. Could we make use of them for linux?

https://guidedhacking.com/threads/warface-mrac-bypass-ring0-anti-cheat.18591/
