### ISSUE TITLE
Astroneer Borks GPU/system and needs hard restart to use PC again

### ISSUE THREAD

**Issue by hellofu** [ValveSoftware/Proton#4100]
specs
OS: Linux Mint 19.3 Tricia Or Win 7 home 64bit
KERNEL: 5.4.0-42-generic
CPU: AMD Ryzen 5 1600 Six-Core
GPU: AMD Radeon RX 480
GPU DRIVER: 4.5 Mesa 18.3.0-rc4 and win7 Radeon software 20.7.2
RAM: 16 GB

Both OS's Each has the same crash results. the issue starts with the screen going black and the monitor searching for a display input. Audio from the game will continue playing. and the PC will require the hold down till the power supply cuts power then you can restart the system but you need to also turn off the monitor or It will not restart yet. the GPU fans Spin up to full speed as long a the system is left running.

Win 7 has less stability in either fullscreen or in windowed mode each crash shortly after intro graphics load and begins playing to the main menu.

LM both fullscreen and windowed mode doesn't show the developer/ Company logos on loading and the planetary loading logo doesn't play but the loading bars do show up. fullscreen crashes much more often mostly near special animations like loading in after death or during saving but the save will survive. otherwise, the crashes just happen during random gameplay without a clear reason this is how the windowed mode crashes most often but can play for 20-40 minutes between crashes at a time.

**Comment by kisak-valve** [comment]
Hello @hellofu, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/243#issuecomment-665106865.
