### ISSUE TITLE
Create symlink to compatdata directory

### ISSUE THREAD

**Issue by dpanter** [ValveSoftware/Proton#4103]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
During game installation or game start, create a symlink to the proper compatdata directory, inside the game installation directory. Probably a good idea to first check if symlink exists and that it links to the correct compatdata directory.

Example, Doom 2016
Installation: `.../SteamLibrary/steamapps/common/DOOM/`
Compatdata: `...SteamLibrary/steamapps/compatdata/379720/`

Example installation directory contents
`/mnt/1900GiBn/SteamLibrary/steamapps/common/DOOM/`
Created symlink **compatdata379720**
```
base/
compatdata379720 -> /mnt/1900GiBn/SteamLibrary/steamapps/compatdata/379720//
EmptySteamDepot/
fontconfig/
virtualtextures/
bink2w64.dll
CChromaEditorLibrary.dll
DOOMx64.exe
DOOMx64vk.exe
steam_api64.dll
superscriptx64.dll
```
Additionally, if switching back to Linux native version, this symlink should be deleted.

## Justification [optional] 
Why integration in Proton instead of Wine? This would be a Steam + Proton specific feature. 
Such a symlink could save quite a bit of time for those who tinker with Proton.
It would be much easier and faster for everyone to find the compatdata directory.
While browsing the files, the presence of said symlink would instantly identify the title is set to run with Proton.

## Risks [optional]
None... or maybe deleting the symlink. Just make it smart enough to not delete anything else.

## References [optional] 
N/A

**Comment by kisak-valve** [comment]
Hello @dpanter, this is a feature request for the Steam client, instead of Proton itself, and functionally the same as the request at https://github.com/ValveSoftware/steam-for-linux/issues/5667. Closing in favor of the existing feature request.

**Comment by dpanter** [comment]
Sorry, I searched and did not find that feature request. 
However, a button in the Steam client is not the same and would not satisfy this request.
