### ISSUE TITLE
Pathologic Classic HD keeps crashing

### ISSUE THREAD

**Issue by Veikrom** [ValveSoftware/Proton#4109]
The game starts with a black screen then closes. After each attempted launch it needs to files to verify. Here is my logs 
[steam-384110.log](https://github.com/ValveSoftware/Proton/files/5004896/steam-384110.log)
Debian 10 

Proton 5.0-9

**Comment by kisak-valve** [comment]
Hello @Veikrom, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2584#issuecomment-667068348.
