### ISSUE TITLE
Warhammer 40,000: Space Marine text not displaying correctly

### ISSUE THREAD

**Issue by JordanPlayz158** [ValveSoftware/Proton#4127]
# Compatibility Report
- Name of the game with compatibility issues: Warhammer 40,000: Space Marine
- Steam AppID of the game: 55150

## System Information
- GPU: GTX 1050 Ti 4GB (Dual Fan, Asus)
- Driver/LLVM version: 4.6.0 NVIDIA 440.100
- Kernel version: 5.7.9-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/JordanPlayz158/21255a17e2975a08694bd4ede69e8fc1
- Proton version: Proton 5.0-9

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
The text is messed up (I believe due to corefonts being missing and if I am correct how would I install corefonts into proton manually because iirc there are reasons (licensing issues) for why proton can't include corefonts in the proton files) (See attached image for visual of messed up text)
![2020-08-08_17-35](https://user-images.githubusercontent.com/22566618/89723072-9c26f080-d9bf-11ea-9a8b-307a379ec167.png)

## Reproduction
Install Warhammer 40,000: Space Marine
Run it under Proton 5.0-9

**Comment by kisak-valve** [comment]
Hello @JordanPlayz158, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/934#issuecomment-670994881.
