### ISSUE TITLE
F1 2018

### ISSUE THREAD

**Issue by bthiebault** [ValveSoftware/Proton#4128]
# Compatibility Report
- Name of the game with compatibility issues: F1 2018
- Steam AppID of the game: 737800

## System Information
- GPU: NVIDIA GeForce RTX 2070 SUPER 
- Driver/LLVM version: 450.57
- Kernel version: 5.7.12-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/bthiebault/0b5fb7a7aaf6266287dd99f201d45cb2
- Proton version: 4.2-9

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

[steam-737800.log](https://github.com/ValveSoftware/Proton/files/5047958/steam-737800.log)

## Symptoms 

During cut-scenes, the textures are very pixelated and models look ugly
![2020-08-09-180230_2560x1440_scrot](https://user-images.githubusercontent.com/50426075/89736631-f9c44700-da6a-11ea-8b9d-cb2a08c79238.png)

During the game, the graphics are good.

I have an XBox One (wired) controller. The vibrations are not correlated to the game events. I sometimes trigger when nothing is happening, but does not when I drive on the kerb.

Finally, changing the screen resolution in the settings freezes the game for quite some time, then succeeds.

## Reproduction

Launch the game

**Comment by kisak-valve** [comment]
Hello @bthiebault, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1567#issuecomment-671074253.
