### ISSUE TITLE
Mouse problem with Zuma Deluxe under Linux

### ISSUE THREAD

**Issue by khvolk** [ValveSoftware/Proton#4129]
Proton Version 5.0-9

I am running Zuma Deluxe on my Notebook Lenovo E14 (2. Gen, Ryzen 4000) with Manjaro Linux (Plasma Desktop). The Game runs well and the aspect ratio is 4:3. The mouse cursor can be moved outside the screen into the black borders left and right. If this happens, you cannot shoot any more. It is blocked: very annoying. Any idea how this can be solved?

**Comment by kisak-valve** [comment]
Hello @khvolk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3033#issuecomment-674037905.
