### ISSUE TITLE
How to force use intel xe gpu when I run the 3DMark test. 

### ISSUE THREAD

**Issue by easytrader** [ValveSoftware/Proton#4132]
have a notebook that have two gpu. One is UMA another is intel xe gpu. How to force use intel xe gpu when I run the 3DMark test. I use proton to run the test. I use Ubuntu for the test.

Thank you.

**Comment by kisak-valve** [comment]
Hello @easytrader, forcing the use of a secondary gpu is something for the video driver stack to handle.

That said, you should be able to set a game's launch options to `DRI_PRIME=1 %command%` to tell mesa to use a secondary GPU with OpenGL-based games (and also with Vulkan as of mesa 20.1).

You can also look into using https://github.com/aejsmith/vkdevicechooser or https://github.com/doitsujin/dxvk#device-filter.
