### ISSUE TITLE
Proton not working across al games

### ISSUE THREAD

**Issue by juliocormor** [ValveSoftware/Proton#4139]
Hello.

A few weeks ago i upgraded my PC and reinstaled Linux, (Solus OS) and proton doesn't work in any game. I have been trying to solve this on my own but haven't been able to. I know for a fact the issue is Proton related as every game log has the same output before closing.

The disk is ext4, different from the one where the OS is installed in, solus steam integration tool is configured to use steam own native libraries, and I have tried both Proton 4 and 5 versions.

Any help is apreciated.

**Logs from some games i've tried with Proton 5.0.9:**

[steam-444640.log](https://github.com/ValveSoftware/Proton/files/5099729/steam-444640.log)
[steam-379720.log](https://github.com/ValveSoftware/Proton/files/5099720/steam-379720.log)
[steam-17390.log](https://github.com/ValveSoftware/Proton/files/5099717/steam-17390.log)
[steam-201810.log](https://github.com/ValveSoftware/Proton/files/5099718/steam-201810.log)
[steam-242760.log](https://github.com/ValveSoftware/Proton/files/5099719/steam-242760.log)
[steam-286160.log](https://github.com/ValveSoftware/Proton/files/5099743/steam-286160.log)

**Comment by ghost** [comment]
`err:file:init_redirects`

About all I can say it look here https://bbs.archlinux.org/viewtopic.php?id=226672

Something you did or weird happened. So try logging out and into XWayland/X11. You may also need to try removing Proton and Wine stuff (hidden folders, or whatever) then reinstall it all. I don't really know what causes it but I would assume its something you did or didn't do.

**Comment by juliocormor** [comment]
> `err:file:init_redirects`
> 
> About all I can say it look here https://bbs.archlinux.org/viewtopic.php?id=226672
> 
> Something you did or weird happened. So try logging out and into XWayland/X11. You may also need to try removing Proton and Wine stuff (hidden folders, or whatever) then reinstall it all. I don't really know what causes it but I would assume its something you did or didn't do.

Hi. I'm sorry I didn't answer, tried your solution but didn't work. At the end I nuked the games partition of the HDD and reinstalled all of my games, which was tedious but made it work.

I think the issue was something related with copying the folders from a ntfs partition where originally downloaded to a ext4 partition, but no idea.
