### ISSUE TITLE
Hitman: Contracts (247430)

### ISSUE THREAD

**Issue by krzysztofcichocki** [ValveSoftware/Proton#4144]
# Compatibility Report
- Name of the game with compatibility issues: Hitman: Contracts
- Steam AppID of the game: 247430

## System Information
- GPU: GTX 1070
- Driver/LLVM version: nvidia 450.57
- Kernel version: 5.4.0-42-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/krzysztofcichocki/8e90776cd9dcce2eaae5d45c47a3878e
- Proton version: 5.0-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-247430.log](https://github.com/ValveSoftware/Proton/files/5113846/steam-247430.log)

## Symptoms 
Mouse buttons do not work in game eg game menu options, selecting weapons, firing weapons. However mouse movement works fine. Menus could be navigated with a keyboard but firing a weapon does not work with mouse 1.

## Reproduction
Launch game, try to navigate main menu with mouse cursor. If you start the game by navigating the menu option with a keyboard, the mission loads and mouse movement works however mouse buttons do not.

**Comment by kisak-valve** [comment]
Hello @krzysztofcichocki, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3532#issuecomment-678771218.
