### ISSUE TITLE
Fall Guys Won't Launch

### ISSUE THREAD

**Issue by NickEckardt** [ValveSoftware/Proton#4145]
# Compatibility Report
- Name of the game with compatibility issues: Fall Guys Ultimate Knockout
- Steam AppID of the game: 1097150

## System Information
- GPU: Radeon RX 560
- Driver/LLVM version: glxinfo | grep OpenGL: OpenGL version string: 4.5 (Compatibility Profile) Mesa 18.3.6
- Kernel version: 5.8.3
- Link to full system information report as [Gist](https://gist.github.com/NickEckardt/e83151a68c48601113757befd287d0b8):
- Proton version: Proton 5.0-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1097150.log](https://github.com/ValveSoftware/Proton/files/5115300/steam-1097150.log)

## Symptoms 
Fall Guys won't launch. I get a loading screen with a bar that sometimes fills up, then nothing. 

## Reproduction
1. Open Steam
2. Click play on Fall Guys
3. Watch the loading screen show up, then disappear without the game launching

**Comment by kisak-valve** [comment]
Hello @NickEckardt, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue to #4123, but in your case it's clear that you do not have any vulkan drivers installed for your system, which is a prerequisite for Proton.

Please run `sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386` (https://github.com/ValveSoftware/Proton/wiki/Requirements#amdintel). Additionally, mesa 18.3 is older than the support cutoff for DXVK (https://github.com/doitsujin/dxvk/wiki/Driver-support#amd-radv-252), so you might experience additional issues from the age of mesa on your system.

**Comment by NickEckardt** [comment]
Thanks for your help, that was the issue! The game is working fine now.
