### ISSUE TITLE
P4G crashes when selecting 'back to 1 week ago'.

### ISSUE THREAD

**Issue by tousei-seiso** [ValveSoftware/Proton#4147]
# Compatibility Report
- Name of the game with compatibility issues:Persona 4 Golden
- Steam AppID of the game:1113000

## System Information
- GPU: GTX 970
- Driver/LLVM version: 4.6.0 NVIDIA 440.100/LLVM???no information.
- Kernel version: 5.4.0-42-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:5.0-9

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
I did found an existing compatibility report for this game, but it is not a report about what I want to describe.
- [ ] that I have checked whether there are updates for my system available.
I did found 3 hotfix updates of P4G, but after installing them, P4G starts with black screen and not respond. So currently I'm still using the released version of P4G. The tweak that 'proton tricks 1113000  wmp9 quartz devenum' have effect on released version but have no effect on hotfixes.

I added `PROTON_LOG=1 %command%` to the game's launch options but after the application crashed , no logs are generated at all to /home/user/.steam/debian-installation/steamapps/common/Persona 4 Golden/Logs and no other places.

## Symptoms
When selecting 'back to 1 week ago', an errror message dialog and a crash message dialog showed, and the application crashes. But no error logs are generated at all.(P4G_d3d9.log, P4G_d3d11.log are created but no error logs are created.)
I did not converted a PSVita save data. I have been playing this game on steam right from the beggining.

1. When selecting 'back to 1 week ago', an error message dialog showed(below).
(translated: title:warning!, message:Old version of save data. Please save again.)
![p4g errormessage](https://user-images.githubusercontent.com/45998954/91174676-93058580-e71a-11ea-97f0-f2d2abf2e3e6.jpg)

2. Crash message dialog(translated: title:application crash, message:The application crashed.) showed and the P4G crashes.
![p4g crashes](https://user-images.githubusercontent.com/45998954/91174306-14a8e380-e71a-11ea-97f2-6693d2069286.jpg)

## Reproduction
1. Select 'back to 1 week ago'.
2. An error log showed and the application crashes.(100%)

**Comment by kisak-valve** [comment]
Hello @tousei-seiso, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3982#issuecomment-680010629.

**Comment by tousei-seiso** [comment]
oh I see. This was my first report, thanks for your transferring.
