### ISSUE TITLE
King's Quest (345390)

### ISSUE THREAD

**Issue by joshas** [ValveSoftware/Proton#4149]
# Whitelist Request
- Name of the game to be whitelisted: King's Quest
- Steam AppID of the game: 345390

## System Information
- GPU: AMD Radeon RX 5600 XT
- Driver/LLVM version: Mesa 20.1.5 / LLVM 10.0.0
- Distro version: Fedora 32 (Workstation Edition)
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/joshas/b5d991b590e9ac9283179339418be775
- Proton version: 5.0-9

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [x] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

Completed all five episodes using mouse and keyboard controls, no issues.

**Comment by kisak-valve** [comment]
Hello @joshas, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/525#issuecomment-680244384.
