### ISSUE TITLE
System Shock Enhanced Edition

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#4150]
# Compatibility Report
- Name of the game with compatibility issues:System Shock Enhanced Edition
- Steam AppID of the game:410710

## System Information
- GPU:RX580
- Driver/LLVM version:LLVM 10.0.1
- Kernel version:5.8.1-3
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/Toadfield/913f47316f805eb071193f7d6a25671a
- Proton version:5.0-9

## I confirm:
- [-] that I haven't found an existing compatibility report for this game.
- [+] that I have checked whether there are updates for my system available.
I found this report,but he doesn't use the same gpu and I have some other problems too:
https://github.com/ValveSoftware/Proton/issues/3235

## Protonlogs
[steam-410710.log](https://github.com/ValveSoftware/Proton/files/5127324/steam-410710.log)

## Symptoms 
1. I can't exit the game by pressing "quit" in the menu,I have to spam Alt+F4.
2. Windowed mode doesn't work.
3. It has big frame drops on Vulkan,Direct3D and OpenGL

## Reproduction
Lauch the game.

**Comment by kisak-valve** [comment]
Hello @Toadfield, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3235#issuecomment-680830499.
