### ISSUE TITLE
Ashes of the Singularity: Escalation native Vulkan support

### ISSUE THREAD

**Issue by outsidefactor** [ValveSoftware/Proton#4151]
# Compatibility Report
- Name of the game with compatibility issues: Ashes of the Singularity: Escalation
- Steam AppID of the game: 507490

## System Information
- GPU: Radeon RX Vega (VEGA10, DRM 3.38.0, 5.8.1-3-MANJARO, LLVM 10.0.1)
- Driver/LLVM version: 20.1.5
- Kernel version: 5.8.1-3
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/outsidefactor/b51e4e409653f2a074a75a644fdd6e52
- Proton version: 5.0.9

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. - this is not relevant to my report. existing reports are for DX11/Proton-4.2

- [X] that I have checked whether there are updates for my system available.

[steam-507490.log](https://github.com/ValveSoftware/Proton/files/5127605/steam-507490.log)

## Reproduction
1 - Launch game as per current compat report (Proton 4.2)
2 - Set game to use Vulkan instead of DX11 - game will say you need to restart
3 - Exit game
4 - Set Steam to Launch game with Proton 5.0.9
5 - Start game. Reaches launcher, but main game fails to launch.

**Comment by kisak-valve** [comment]
Hello @outsidefactor, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1479#issuecomment-680833854.
