### ISSUE TITLE
[Whitelist] Stronghold HD (40950)

### ISSUE THREAD

**Issue by llikeitt** [ValveSoftware/Proton#416]
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux 4.x (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.18.3-arch1-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12001000
    X Window Manager:  KWin
    Steam Runtime Version:  Runtime disabled

Video Card:
    Driver:  X.Org AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.26.0, 4.18.3-arch1-1-ARCH, LLVM 6.0.1)
    Driver Version:  3.1 Mesa 18.1.6
    OpenGL Version: 3.1
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x67df
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 20.08" x 11.42" (23.07" diag)
                                            51.0cm x 29.0cm (58.6cm diag)
    Primary VRAM: 8192 MB

Sound card:
    Audio device: Realtek ALC1150

**Comment by swick** [comment]
The game breaks for me when changing to another Window. Does it work for you?

**Comment by llikeitt** [comment]
It seems that all the games have the same problem: #314 #373 #417

**Comment by swick** [comment]
No change with Proton beta

**Comment by kisak-valve** [comment]
Found in the 2018-12-11 white list update.

@swick, if you're still experiencing the issue you previously saw, please open a new issue report.
