### ISSUE TITLE
okami won't launch

### ISSUE THREAD

**Issue by rimekko** [ValveSoftware/Proton#4166]
hi, i can't get Okami to launch
steam says it's running for maybe 30 seconds before it stops on its own, and no game screen ever pops up

i've tried different proton versions (5.0-9, 4.11-13, 4.2-9, 3.16-9, 3.7-8) but none are working

system info: https://gist.github.com/rimekko/1ea09190f3a0df963f29eab33ed3a607
proton log for 5.0-9: https://gist.github.com/rimekko/54d94e1f52dc22d0f43c9154aa01a069

**Comment by kisak-valve** [comment]
Hello @rimekko, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #756, but in this case it's clear that you have no Vulkan drivers installed for your video card.

Please run `sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386` (from https://github.com/ValveSoftware/Proton/wiki/Requirements#amdintel).
