### ISSUE TITLE
Chilla's Art games graphics errors (1306620 1228520 1349960)

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/Proton#4167]
Chilla's Art latest games have black graphics artifacts when SSR (ScreenSpaceReflections) is enabled

Affected games are:
Missing Children (1306620)
The Convenience Store (1228520)
The Ghost Train (1349960)

**System Information**
- GPU: RX 5700
- GPU Driver: Mesa 20.3.0-devel (git-1459cce 2020-09-01 focal-oibaf-ppa)
- Kernel version: 5.9.0-050900rc3-lowlatency
- Distro version: Mint 20 (64 bit) (Cinnamon)
- Proton version: 5.0-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When SSR (ScreenSpaceReflections) are enabled, there are graphical artifacts when in some specific indoors areas.

- Tested different Mesa drivers: Mesa 20.0.8, Mesa 20.1.6, Mesa 20.3.0-devel
- Tried with both ACO and LLVM 
- Tried Proton versions 3.16-9, 4.2-9, 5.0-9, 5.0-10-rc4 amd also unofficial 5.11-GE-3-MF

## Reproduction
Steps to re-produce issue in Missing Children:
- Enable SSR in games options
- use the flashlight, and you will see glitches when entering Mizukis house. You can also see glitches in the Akikos house kitchen when using the flashlight.
![children](https://user-images.githubusercontent.com/43387963/91914088-90290880-ecb7-11ea-93a8-6980161753bd.jpg)

Steps to re-produce issue in The Convenience Store:
- Enable SSR in games options
- At the very beginning pick up the flashlight, stand beside the table where you picked it up. Use the flashlight and look down the stairs. This is the spot, it is not supposed to be dark:
![convini](https://user-images.githubusercontent.com/43387963/91914101-99b27080-ecb7-11ea-8b2d-37bcd37f4199.jpg)

Steps to re-produce issue in The Ghost Train:
- Enable SSR in games options
- Right at the very start going down the escalator you will see glitches 
![train](https://user-images.githubusercontent.com/43387963/91914115-9f0fbb00-ecb7-11ea-8469-e998d105eb93.jpg)

It is easiest to see the problem in Ghost Train, as it is right at the beginning and you don't have to stand in a special spot for the problem to occur. 

**Logs**
[logs.zip](https://github.com/ValveSoftware/Proton/files/5159197/logs.zip)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/5159198/system_info.txt)

**Comment by kisak-valve** [comment]
Hello @AwesamLinux, it may be worthwhile to also mention this to the mesa/radv devs.

**Comment by hakzsam** [comment]
I can also reproduce the issue with Ghost Train with AMDVLK, so it's probably not RADV specific.

**Comment by hakzsam** [comment]
@AwesamLinux It appears that setting `d3d11.enableRtOutputNanFixup = True` inside `dxvk.conf` fix the issue on my side. Can you confirm?

**Comment by AwesamLinux** [comment]
@hakzsam Thanks, I tried it on all of these and it worked! 

Missing Children (1306620)
The Convenience Store (1228520)
The Ghost Train (1349960)

Including the dxvk logs here in case the games executable names would be useful:
[Missing Children_d3d11.log](https://github.com/ValveSoftware/Proton/files/5271529/Missing.Children_d3d11.log)
[The Convenience Store Yakin Jiken_d3d11.log](https://github.com/ValveSoftware/Proton/files/5271531/The.Convenience.Store.Yakin.Jiken_d3d11.log)
[TheGhostTrain_d3d11.log](https://github.com/ValveSoftware/Proton/files/5271532/TheGhostTrain_d3d11.log)

**Comment by AwesamLinux** [comment]
Confirming that as of Proton 5.13-1 these games are rendering properly.
