### ISSUE TITLE
Persona 4 golden does not work after the recent 1.1 update

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#4171]
Persona 4 golden has been working with valve's proton since lauch, but required you to run `protontricks 1113000 wmp9 quartz devenum` in order to get the game working, however since the last 1.1 update the game does not work even with the right protontricks command

**Comment by kisak-valve** [comment]
Hello @Chico3589, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3982#issuecomment-687490132.

**Comment by ghost** [comment]
ok thanks

Em sex, 4 de set de 2020 21:28, kisak-valve <notifications@github.com>
escreveu:
