### ISSUE TITLE
Rust (3.9.2020 Update)

### ISSUE THREAD

**Issue by TheBlackPenguin** [ValveSoftware/Proton#4175]
# Compatibility Report
- Name of the game with compatibility issues: Rust
- Steam AppID of the game: 252490

## System Information
- GPU: GTX 750 Ti
- Driver/LLVM version: nvidia 450.66
- Kernel version: 5.4.61-1-lts
- Link to full system information report: [Report](https://gist.github.com/TheBlackPenguin/375ce9d3b68acb71f155c0f0c6582211)
- Proton version: 5.0-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.

- [x] that I have checked whether there are updates for my system available.

[steam-252490.log](https://github.com/ValveSoftware/Proton/files/5178881/steam-252490.log)

## Symptoms 
The game worked fine with Proton, but since the latest Rust update, the game crashes while loading. The error.log of the game report an Access Violation by the steam_api64.dll ([error.log](https://gist.github.com/TheBlackPenguin/05c473e400e57cca40ccd72d8b4caa8b)). The game now only works with a regular wine installation of steam.

## Reproduction
Launch Rust with Proton

**Comment by kisak-valve** [comment]
Hello @TheBlackPenguin, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3104#issuecomment-687677795.
