### ISSUE TITLE
Soul Calibur VI fails to launch as of its newest patch

### ISSUE THREAD

**Issue by motmontheinternet** [ValveSoftware/Proton#4182]
# Compatibility Report
- Name of the game with compatibility issues: Soul Calibur VI
- Steam AppID of the game: 544750

## System Information
- GPU: Radeon Vega 56
- Driver/LLVM version: Mesa 20.0.8
- Kernel version: 5.7.1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/motmontheinternet/58f6e258c1998809feb314046f4f7f8f
- Proton version: 5.0-9 (also tried earlier stable builds)

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

Can't upload error log because it's 1.5 GB in size.

## Symptoms 
SC6 released an update a few hours ago that seems to have broken Linux compatibility, apparently this is happening to multiple people.  This thread linked indicates that the issue might be that the patch updated Denuvo and now the game won't run.
https://steamcommunity.com/app/544750/discussions/0/2953754543764162810/

**Comment by kisak-valve** [comment]
Hello @motmontheinternet, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1780#issuecomment-690216311.
