### ISSUE TITLE
Path of Exile 3.11.2 crashes on launch

### ISSUE THREAD

**Issue by Storm-Engineer** [ValveSoftware/Proton#4188]
Path of Exile just released a large patch that required re-downloading the whole game because it changed how it stores data. (Info: https://www.pathofexile.com/forum/view-thread/2933680)

Since then, the game crashes on start. I've tried several different versions of Proton, but it always crashes. Before the patch I was using 4.11-GE-1. Below are the terminal outputs for all the versions I tried. Apart from the 4.11 version, they contain stack traces.

[poe-crash-Proton-4.11-GE-1.txt](https://github.com/ValveSoftware/Proton/files/5213387/poe-crash-Proton-4.11-GE-1.txt)
[poe-crash-Proton-5.0-1.txt](https://github.com/ValveSoftware/Proton/files/5213389/poe-crash-Proton-5.0-1.txt)
[poe-crash-Proton-5.11-GE-1-MF.txt](https://github.com/ValveSoftware/Proton/files/5213390/poe-crash-Proton-5.11-GE-1-MF.txt)
[poe-crash-Proton-5.11.GE.3.MF-1.txt](https://github.com/ValveSoftware/Proton/files/5213391/poe-crash-Proton-5.11.GE.3.MF-1.txt)

System information:
[poe-crash-sysinfo.txt](https://github.com/ValveSoftware/Proton/files/5213399/poe-crash-sysinfo.txt)

**Comment by kisak-valve** [comment]
Hello @Storm-Engineer, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/58#issuecomment-691575998.
