### ISSUE TITLE
Can't get git clone

### ISSUE THREAD

**Issue by daniel-camino** [ValveSoftware/Proton#4191]
I'm trying to install Proton on Linux following the instructions and I get this error when doing: git clone --recurse-submodules git@github.com:ValveSoftware/Proton.git proton

```
Cloning into 'proton'...
Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by kisak-valve** [comment]
Hello @daniel-camino, use `git clone --recurse-submodules https://github.com/ValveSoftware/Proton.git proton` (https://github.com/ValveSoftware/Proton#obtaining-proton-from-source).
