### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by daniel-camino** [ValveSoftware/Proton#4192]
Hi!
Neither of this it's working:
```
$ ./steam-runtime/setup_docker.sh amd64 --extra-bootstrap=./proton/steamrt-bootstrap.sh steam-proton-dev
$ ./steam-runtime/setup_docker.sh i386 --extra-bootstrap=./proton/steamrt-bootstrap.sh steam-proton-dev32
```

Got this message:
```
Script started, file is /tmp/steam-runtime-setup-chroot-ZDS.log
!! WARNING: /home/daniel/GitProjects/steam-runtime/setup_docker.sh is deprecated and should not be used anymore! Instead follow the "Building in the runtime"  section of the README.md
!! Extra bootstrap file does not exist (./proton/steamrt-bootstrap.sh)

real	0m0,008s
user	0m0,004s
sys	0m0,004s
Script done, file is /tmp/steam-runtime-setup-chroot-ZDS.log
```

**Comment by daniel-camino** [comment]
It's there any way to installl Proton easer than this?

**Comment by daniel-camino** [comment]
I can't find the way to install Proton... Any easy guide to do it, please???

**Comment by kisak-valve** [comment]
Hello @daniel-camino, most users get Proton by letting Steam download it and there is Steam client integration to use it with games on their Steam account. Outside of the typical environment, it's recommended to use vagrant to setup the build environment. (https://github.com/ValveSoftware/Proton#easy-build-path).

**Comment by daniel-camino** [comment]
How do I get Proton from Steam? I want to play some Windows games in Linux and I could not find the way, (seem that you need a degree in computers to install anything)...

**Comment by kisak-valve** [comment]
There's several guides around, here's a randomly picked one: https://www.gamingonlinux.com/articles/a-simple-guide-to-steam-play-valves-technology-for-playing-windows-games-on-linux.14552

**Comment by daniel-camino** [comment]
Thanks!
