### ISSUE TITLE
Sims 4 OriginThin Setup Continues Indefinitly

### ISSUE THREAD

**Issue by TritonSr** [ValveSoftware/Proton#4193]
# Compatibility Report
- Name of the game with compatibility issues: The Sims 4
- Steam AppID of the game: 1222670

## System Information
- GPU: Intel UHD Graphics 620
- Driver/LLVM version:  Intel Open Source Technology Center Mesa DRI (3.0 Mesa 18.3.6)
- Kernel version: 5.4.64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/betterthanyou710/ed58c59394e5d2a869c4b9e399951ff0
- Proton version: 5.0

## I confirm:
- [v] that I haven't found an existing compatibility report for this game.
- [v] that I have checked whether there are updates for my system available.

## Symptoms 
For first time setup, gets caught on "Installing: OriginThinSetup (step 1 of 2)" indefinitely and doesn't fill up the blue bar, instead there is a timed out icon.

## Reproduction
Starting the game
(Usually verifying files first)

I can't find the APPID log anywhere in my files, let me know if there is some obvious place that I'm missing that would have it.

**Comment by kisak-valve** [comment]
Hello @betterthanyou710, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4174#issuecomment-691738582.

**Comment by IlgazC** [comment]
I have the exact same issue on openSUSE Tumbleweed
