### ISSUE TITLE
Fall Guys doesn't work anymore, caused by Anti Cheat software

### ISSUE THREAD

**Issue by wiz21b** [ValveSoftware/Proton#4197]
# Compatibility Report
- Name of the game with compatibility issues: Fall Guys
- Steam AppID of the game: 1097150

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: latest (5)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game. (No info on ProtonDB website)
- [X ] that I have checked whether there are updates for my system available.

## Symptoms 

Program starts as usal, with the menu etc. But as soon as you try to join a game, the game says "anit cheat not initialized" and don't go any further, rendering the game totally useless (I'm a bit furious here, I've paid for the game so it'd be the least to allow me to revert to the older version that was working fine).

**Comment by kisak-valve** [comment]
Hello @wiz21b, we're using one issue report per unofficially supported game title, and this has already been mentioned at https://github.com/ValveSoftware/Proton/issues/4123#issuecomment-692689353.

Closing as in favor of #4123.
