### ISSUE TITLE
ARK: Survival Evolved - Crystal Isles Map will not start when joining server (works on local single player)

### ISSUE THREAD

**Issue by rastermann** [ValveSoftware/Proton#4203]
# Compatibility Report
- Name of the game with compatibility issues: ARK: Survival Evolved
- Steam AppID of the game: 346110

## System Information
- GPU: AMD Vega64
- Driver/LLVM version: Mesa git master 85cc2950a045ca0fe153498fb7d48322d2906482
- Kernel version: 5.8.8
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/rastermann/fcc3eb36fde0a3212f079b0abf204508
- Proton version: 5.0-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-ark-join-crystal-isles-map.log](https://github.com/ValveSoftware/Proton/files/5240673/steam-ark-join-crystal-isles-map.log)

## Symptoms

This issue happens with CrystalIsles map (recently released). IT does not happen with Ragnarok, TheIsland etc. that I have seen. The amdvlk driver works with single player and CrystalIsles. If you use the new ACO compiler in Mesa git, it also works like amdvlk. 20.01 Mesa does not. So this assumes wither amdvlk or Mesa git

## Reproduction

Game name and id as above. You will need a game server that doesn't need BattlEye. For example:

Go to Steam -> View -> Servers and "Add a server": IP Address: 195.201.57.56:7780

And "find games on this IP" and then add one of them and close that dialog. Now 

Start ARK, then "join game" and select "favorites" at the bottom and select the above server (S2 EliteArk 25x).

It will begin loading and part way through just dump you back into the main menu and not join. It works find for other Maps I have tried. BattlEye does not work so I have not enabled/installed that when prompted. We know that already - another bug, so avoiding that one as above.

Note that if you do not use amdvlk or last mesa with ACO enabled then your system may go down in flames with amdgpu kernel paging request failures and the entire display stack dies with a GPU reset. That is a separate issue and already solved by ACO or amdvlk, but if you hit this issue the above solutions (ACO shader compiler for AMD cards in git master or amdvlk) will solve the problem.

**Comment by kisak-valve** [comment]
Hello @rastermann, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3218#issuecomment-694366821.
