### ISSUE TITLE
fall guys ultimate knockout starting ok but first person player not showing

### ISSUE THREAD

**Issue by thsnielsen** [ValveSoftware/Proton#4207]
In short i am on opensuse tumbleweed 5.8.7-1-default on a lenovo x220 16g ram much ssd disk free
I have the same problem on 2 different equal machines
I had to add this option to make the game launch, which it does fine now my son even completed a game with this invisible player!!: 
This option makes the game run : PROTON_USE_WINED3D=1 %command%
This screenshot says it all - there should be the player in the middle of the screen, but he is missing ...???...

![image](https://user-images.githubusercontent.com/16719354/93664469-8f41f600-fa6f-11ea-8479-d07f9ab8f641.png)

There are many errors below - not sure where to begin, and then again - the game mainly works?? Well except i do not see the players :-) 

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3300 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "openSUSE Tumbleweed" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.8.7-1-default
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12009000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20200910.0

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)
    Driver Version:  3.0 Mesa 20.1.7
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x126
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 10.91" x 6.14" (12.48" diag)
                                            27.7cm x 15.6cm (31.7cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Conexant CX20590

Memory:
    RAM:  15776 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  POSIX
    Total Hard Disk Space Available:  216688 Mb
    Largest Free Hard Disk Block:  87774 Mb

"LD_* scout runtime" information:
{
  "can-write-uinput" : true,
  "steam-installation" : {
    "path" : "/root/.local/share/Steam",
    "data_path" : "/root/.local/share/Steam",
    "bin32_path" : "/root/.local/share/Steam/ubuntu12_32",
    "issues" : [
    ]
  },
  "runtime" : {
    "path" : "/root/.local/share/Steam/ubuntu12_32/steam-runtime",
    "version" : "0.20200910.0",
    "issues" : [
    ],
    "pinned_libs_32" : {
      "list" : [
        "  9840182      4 drwxr-xr-x   2 root     root         4096 Sep 19 11:42 pinned_libs_32",
        "  9840186      0 -rw-r--r--   1 root     root            0 Sep 19 11:42 pinned_libs_32/has_pins",
        "  9840185      4 -rw-r--r--   1 root     root           54 Sep 19 11:42 pinned_libs_32/system_libdbus-1.so.3",
        "  9840190      4 -rw-r--r--   1 root     root           46 Sep 19 11:42 pinned_libs_32/system_libGLU.so.1",
        "  9840201      0 lrwxrwxrwx   1 root     root           12 Sep 19 11:42 pinned_libs_32/libcurl.so.3 -> libcurl.so.4",
        "  9840187      4 lrwxrwxrwx   1 root     root          101 Sep 19 11:42 pinned_libs_32/libgtk-x11-2.0.so.0 -> /root/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0.2400.10",
        "  9840188      4 -rw-r--r--   1 root     root           66 Sep 19 11:42 pinned_libs_32/system_libgtk-x11-2.0.so.0",
        "  9840189      4 lrwxrwxrwx   1 root     root           93 Sep 19 11:42 pinned_libs_32/libGLU.so.1 -> /root/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libGLU.so.1.3.08004",
        "  9840192      4 -rw-r--r--   1 root     root           48 Sep 19 11:42 pinned_libs_32/system_libcurl.so.4",
        "  9840184      4 lrwxrwxrwx   1 root     root           88 Sep 19 11:42 pinned_libs_32/libdbus-1.so.3 -> /root/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libdbus-1.so.3.5.8",
        "  9840191      4 lrwxrwxrwx   1 root     root           90 Sep 19 11:42 pinned_libs_32/libcurl.so.4 -> /root/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libcurl.so.4.2.0"
      ]
    },
    "pinned_libs_64" : {
      "list" : [
        "  9840183      4 drwxr-xr-x   2 root     root         4096 Sep 19 11:42 pinned_libs_64",
        "  9840198      4 -rw-r--r--   1 root     root           71 Sep 19 11:42 pinned_libs_64/system_libdbusmenu-glib.so.4",
        "  9840196      0 -rw-r--r--   1 root     root            0 Sep 19 11:42 pinned_libs_64/has_pins",
        "  9840195      4 -rw-r--r--   1 root     root           50 Sep 19 11:42 pinned_libs_64/system_libGLU.so.1",
        "  9840202      0 lrwxrwxrwx   1 root     root           12 Sep 19 11:42 pinned_libs_64/libcurl.so.3 -> libcurl.so.4",
        "  9840194      4 lrwxrwxrwx   1 root     root           95 Sep 19 11:42 pinned_libs_64/libGLU.so.1 -> /root/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libGLU.so.1.3.08004",
        "  9840200      4 -rw-r--r--   1 root     root           52 Sep 19 11:42 pinned_libs_64/system_libcurl.so.4",
        "  9840197      4 lrwxrwxrwx   1 root     root          102 Sep 19 11:42 pinned_libs_64/libdbusmenu-glib.so.4 -> /root/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4.0.13",
        "  9840199      4 lrwxrwxrwx   1 root     root           92 Sep 19 11:42 pinned_libs_64/libcurl.so.4 -> /root/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libcurl.so.4.2.0"
      ]
    }
  },
  "os-release" : {
    "id" : "opensuse-tumbleweed",
    "id_like" : [
      "opensuse",
      "suse"
    ],
    "name" : "openSUSE Tumbleweed",
    "pretty_name" : "openSUSE Tumbleweed",
    "version_id" : "20200917"
  },
  "container" : {
    "type" : "none"
  },
  "driver_environment" : [
  ],
  "architectures" : {
    "i386-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "ERROR: [Loader Message] Code 0 : /usr/lib64/libvulkan_radeon.so: wrong ELF class: ELFCLASS64\nERROR: [Loader Message] Code 0 : /usr/lib64/libvulkan_intel.so: wrong ELF class: ELFCLASS64\nERROR: [Loader Message] Code 0 : /root/.local/share/Steam/ubuntu12_64/steamoverlayvulkanlayer.so: wrong ELF class: ELFCLASS64\nERROR at /usr/src/packages/BUILD/vulkaninfo/vulkaninfo.h:242:vkEnumerateInstanceExtensionProperties failed with ERROR_INITIALIZATION_FAILED\nfailed to find GPUs with Vulkan support!\n",
          "renderer" : null,
          "version" : null,
          "issues" : [
            "cannot-load",
            "cannot-draw"
          ],
          "exit-status" : 1
        },
        "x11/vdpau" : {
          "messages" : "Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory\nvdp_device_create_x11 (display, screen, &device, &vdp_get_proc_address) failed: 1\n",
          "renderer" : null,
          "version" : null,
          "issues" : [
            "cannot-draw"
          ],
          "exit-status" : 1
        },
        "x11/vaapi" : {
          "messages" : "libva info: VA-API version 1.1.0\nlibva info: va_getDriverName() returns 0\nlibva info: Trying to open /usr/lib/i386-linux-gnu/dri/i965_drv_video.so\nlibva info: Trying to open /usr/lib/i386-linux-gnu/dri/intel-vaapi-driver/i965_drv_video.so\nlibva info: Trying to open /usr/lib/i386-linux-gnu/GL/lib/dri/i965_drv_video.so\nlibva info: Trying to open /usr/lib32/dri/i965_drv_video.so\nlibva info: Trying to open /usr/lib/dri/i965_drv_video.so\nlibva error: /usr/lib/dri/i965_drv_video.so has no function __vaDriverInit_1_0\nlibva info: va_openDriver() returns -1\nvaInitialize (va_display, &major_version, &minor_version) failed: unknown libva error (-1)\n",
          "renderer" : null,
          "version" : null,
          "issues" : [
            "cannot-draw"
          ],
          "exit-status" : 1
        },
        "glx/gl" : {
          "renderer" : "Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)",
          "version" : "3.0 Mesa 20.1.7",
          "library-vendor" : "glvnd"
        },
        "egl_x11/gl" : {
          "messages" : "Waffle error: 0x2 WAFFLE_ERROR_UNKNOWN: eglGetDisplay failed with error EGL_BAD_PARAMETER(0x300c)\n",
          "renderer" : null,
          "version" : null,
          "library-vendor" : "glvnd",
          "issues" : [
            "cannot-load"
          ],
          "exit-status" : 1
        },
        "egl_x11/glesv2" : {
          "messages" : "Waffle error: 0x2 WAFFLE_ERROR_UNKNOWN: eglGetDisplay failed with error EGL_BAD_PARAMETER(0x300c)\n",
          "renderer" : null,
          "version" : null,
          "library-vendor" : "glvnd",
          "issues" : [
            "cannot-load"
          ],
          "exit-status" : 1
        }
      },
      "dri_drivers" : [
        {
          "library_path" : "/usr/lib/dri/i915_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/i965_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/iris_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/kms_swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/r200_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/r300_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/r600_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/radeon_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/radeonsi_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/virtio_gpu_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/vmwgfx_dri.so"
        }
      ],
      "va-api_drivers" : [
        {
          "library_path" : "/root/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/dri/dummy_drv_video.so"
        }
      ],
      "vdpau_drivers" : [
        {
          "library_path" : "/root/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/vdpau/libvdpau_trace.so.1",
          "library_link" : "libvdpau_trace.so.1.0.0"
        }
      ],
      "glx_drivers" : [
        {
          "library_soname" : "libGLX_indirect.so.0",
          "library_path" : "/usr/lib/libGLX_mesa.so.0.0.0"
        },
        {
          "library_soname" : "libGLX_mesa.so.0",
          "library_path" : "/usr/lib/libGLX_mesa.so.0.0.0"
        }
      ]
    },
    "x86_64-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
        "cannot-load"
      ],
      "library-details" : {
        "libbz2.so.1.0" : {
          "soname" : "libbz2.so.1",
          "path" : "/usr/lib64/libbz2.so.1.0"
        },
        "libcurl.so.4" : {
          "messages" : "Unable to find the library: /root/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4: undefined symbol: SSL_CTX_set_srp_password, version OPENSSL_1.0.1\n",
          "soname" : null,
          "path" : null,
          "issues" : [
            "cannot-load"
          ],
          "exit-status" : 1
        }
      },
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "ERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_intel.so: wrong ELF class: ELFCLASS32\nERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_radeon.so: wrong ELF class: ELFCLASS32\nERROR: [Loader Message] Code 0 : /root/.local/share/Steam/ubuntu12_32/steamoverlayvulkanlayer.so: wrong ELF class: ELFCLASS32\nERROR at /usr/src/packages/BUILD/vulkaninfo/vulkaninfo.h:242:vkEnumerateInstanceExtensionProperties failed with ERROR_INITIALIZATION_FAILED\nfailed to find GPUs with Vulkan support!\n",
          "renderer" : null,
          "version" : null,
          "issues" : [
            "cannot-load",
            "cannot-draw"
          ],
          "exit-status" : 1
        },
        "x11/vdpau" : {
          "messages" : "Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory\nvdp_device_create_x11 (display, screen, &device, &vdp_get_proc_address) failed: 1\n",
          "renderer" : null,
          "version" : null,
          "issues" : [
            "cannot-draw"
          ],
          "exit-status" : 1
        },
        "x11/vaapi" : {
          "messages" : "libva info: VA-API version 1.8.0\nlibva info: Trying to open /usr/lib64/dri/iHD_drv_video.so\nlibva info: va_openDriver() returns -1\nlibva info: Trying to open /usr/lib64/dri/i965_drv_video.so\nlibva info: Found init function __vaDriverInit_1_8\nfailed to open /usr/lib64/dri/hybrid_drv_video.so\nlibva info: va_openDriver() returns 0\nvaRenderPicture (va_display, context, &misc_buf_id, 1) failed: the requested VABufferType is not supported (15)\n",
          "renderer" : null,
          "version" : null,
          "issues" : [
            "cannot-draw"
          ],
          "exit-status" : 1
        },
        "glx/gl" : {
          "renderer" : "Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)",
          "version" : "3.0 Mesa 20.1.7",
          "library-vendor" : "glvnd"
        },
        "egl_x11/gl" : {
          "renderer" : "Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)",
          "version" : "3.0 Mesa 20.1.7",
          "library-vendor" : "glvnd"
        },
        "egl_x11/glesv2" : {
          "renderer" : "Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)",
          "version" : "OpenGL ES 3.0 Mesa 20.1.7",
          "library-vendor" : "glvnd"
        }
      },
      "dri_drivers" : [
        {
          "library_path" : "/usr/lib64/dri/i915_dri.so"
        },
        {
          "library_path" : "/usr/lib64/dri/i965_dri.so"
        },
        {
          "library_path" : "/usr/lib64/dri/iris_dri.so"
        },
        {
          "library_path" : "/usr/lib64/dri/kms_swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib64/dri/r200_dri.so"
        },
        {
          "library_path" : "/usr/lib64/dri/r300_dri.so"
        },
        {
          "library_path" : "/usr/lib64/dri/r600_dri.so"
        },
        {
          "library_path" : "/usr/lib64/dri/radeon_dri.so"
        },
        {
          "library_path" : "/usr/lib64/dri/radeonsi_dri.so"
        },
        {
          "library_path" : "/usr/lib64/dri/swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib64/dri/virtio_gpu_dri.so"
        },
        {
          "library_path" : "/usr/lib64/dri/vmwgfx_dri.so"
        }
      ],
      "va-api_drivers" : [
        {
          "library_path" : "/usr/lib64/dri/i965_drv_video.so"
        },
        {
          "library_path" : "/usr/lib64/dri/nouveau_drv_video.so"
        },
        {
          "library_path" : "/usr/lib64/dri/r600_drv_video.so"
        },
        {
          "library_path" : "/usr/lib64/dri/radeonsi_drv_video.so"
        },
        {
          "library_path" : "/root/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/dri/dummy_drv_video.so"
        }
      ],
      "vdpau_drivers" : [
      ],
      "glx_drivers" : [
        {
          "library_soname" : "libGLX_indirect.so.0",
          "library_path" : "/usr/lib64/libGLX_mesa.so.0.0.0"
        },
        {
          "library_soname" : "libGLX_mesa.so.0",
          "library_path" : "/usr/lib64/libGLX_mesa.so.0.0.0"
        }
      ]
    }
  },
  "locale-issues" : [
    "i18n-supported-missing",
    "i18n-locales-en-us-missing"
  ],
  "locales" : {
    "<default>" : {
      "resulting-name" : "LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=C;LC_COLLATE=C;LC_MONETARY=C;LC_MESSAGES=C;LC_PAPER=C;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=C;LC_IDENTIFICATION=C",
      "charset" : "UTF-8",
      "is_utf8" : true
    },
    "C" : {
      "resulting-name" : "C",
      "charset" : "ANSI_X3.4-1968",
      "is_utf8" : false
    },
    "C.UTF-8" : {
      "resulting-name" : "C.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    },
    "en_US.UTF-8" : {
      "resulting-name" : "en_US.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    }
  },
  "egl" : {
    "icds" : [
      {
        "json_path" : "/usr/share/glvnd/egl_vendor.d/50_mesa.json",
        "library_path" : "libEGL_mesa.so.0"
      }
    ]
  },
  "vulkan" : {
    "icds" : [
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.x86_64.json",
        "library_path" : "/usr/lib64/libvulkan_radeon.so",
        "api_version" : "1.2.131"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/intel_icd.i686.json",
        "library_path" : "/usr/lib/libvulkan_intel.so",
        "api_version" : "1.2.131"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.i686.json",
        "library_path" : "/usr/lib/libvulkan_radeon.so",
        "api_version" : "1.2.131"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/intel_icd.x86_64.json",
        "library_path" : "/usr/lib64/libvulkan_intel.so",
        "api_version" : "1.2.131"
      }
    ]
  },
  "desktop-entries" : [
    {
      "id" : "steam.desktop",
      "commandline" : "/usr/bin/steam %U",
      "filename" : "/usr/share/applications/steam.desktop",
      "default_steam_uri_handler" : true,
      "steam_uri_handler" : true
    }
  ],
  "cpu-features" : {
    "x86-64" : true,
    "sse3" : true,
    "cmpxchg16b" : true
  }
}

"scout runtime container" is not installed.

"soldier runtime container" is not installed.

**Comment by kisak-valve** [comment]
Hello @thsnielsen, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4123#issuecomment-695207067.
