### ISSUE TITLE
Support for non Vulkan GPUs

### ISSUE THREAD

**Issue by es20490446e** [ValveSoftware/Proton#4208]
If you use a graphic card that doesn't support Vulkan no title will launch on Proton, but it will do seamlessly on Wine.

The work-around for this is to manually instruct Proton to use Wine3D instead, by adding the following launch option to each game:

PROTON_USE_WINED3D=1 %command%

This would be better detected and set automatically.

**Comment by kisak-valve** [comment]
Duplicate of #3738.
