### ISSUE TITLE
Using Proton Soldier Several Games Download Nothing

### ISSUE THREAD

**Issue by ethanmassie** [ValveSoftware/Proton#4209]
Proton Version: Soldier
Problematic Games: Final Fantasy III (239120), Final Fantasy IV (312750), Final Fantasy XIII (292120), Paper Ball (1198510), Princess Maker Refine (583040), and Princess Maker 2 Refine (523000).
OS: Fedora 32

Issue: 
When installing these titles the Install prompt lists no Disk Space Required, Disk Space Available, nor Estimated Download Time.  After clicking next the game finishing installing instantly and the install directory is empty.  It doesn't affect all titles and I couldn't find commonality between the titles affected.  No errors are reported from the client or the command output and steam thinks the games are installed fine.  This appears to be a steam play issue since changing to Proton 5.0-9 fixes the issue.

**Comment by kisak-valve** [comment]
Hello @ethanmassie, the Soldier Steam linux runtime is a separate compatibility layer from Proton. You've encountered the issue being tracked at https://github.com/ValveSoftware/steam-runtime/issues/200.

Closing in favor of the existing issue report.
