### ISSUE TITLE
Return of the Obra Dinn (653530)

### ISSUE THREAD

**Issue by nolbap** [ValveSoftware/Proton#4210]
# Compatibility Report
- Name of the game with compatibility issues: Return of the Obra Dinn
- Steam AppID of the game: 653530

## System Information
- GPU: Intel HD Graphics 620
- Driver/LLVM version: Mesa 20.2.0-rc4
- Kernel version: Linux gentoo 5.8.10
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/nolbap/ea52cf7b8a3e3dcff54209a076789a2e
- Proton version: Proton-5.9-GE-6-ST and Proton-5.0-9

## I confirm:

- [x] that I haven't found an existing compatibility report for this game.

- [x] that I have checked whether there are updates for my system available.

## Symptoms 

The game launches but I cant interact with anything beside the credits and the exit button, also when I change workspace and I get back into the game the game freezes (using dwm).

_"The game starts, but the "Begin" button in the main menu does nothing but flash white when clicked. The credits play correctly and the quit (X) button work though."_
(same issue as mine from a https://www.protondb.com/app/653530 report)

## Reproduction

Everytime I launch the game.

## Log file
[steam-653530(proton-5.0-9).log](https://github.com/ValveSoftware/Proton/files/5256893/steam-653530.proton-5.0-9.log)
[steam-653530(proton-5.9GE).log](https://github.com/ValveSoftware/Proton/files/5256894/steam-653530.proton-5.9GE.log)

**Comment by kisak-valve** [comment]
Hello @nolbap, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1833#issuecomment-696245332.
