### ISSUE TITLE
Resident Evil 7 graphical issues with menus

### ISSUE THREAD

**Issue by poperigby** [ValveSoftware/Proton#4215]
# Compatibility Report
- Name of the game with compatibility issues: Resident Evil 7
- Steam AppID of the game: 418370

## System Information
- GPU:  RX 5700 XT
- Driver/LLVM version:  mesa 20.1.8-1
- Kernel version:  5.8.10.arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/PopeRigby/1e4df53972638052a2cab7de86f4f847
- Proton version: 
    - 5.0-9
    - 5.11-GE-2-MF
    - 5.11-GE-3-MF
    - 5.6-GE-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-418370.log](https://github.com/ValveSoftware/Proton/files/5265047/steam-418370.log)

## Symptoms 
The tape recorder in the main menu has glitched out text, and all the menu options in the options menu have black bars over them.

## Reproduction
I've tried multiple different versions of Proton GE and none of them fix the issue. I also tried using Proton 5.0-9 along with `<Workaround removed by moderator>`

**Comment by kisak-valve** [comment]
Hello @PopeRigby, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1029#issuecomment-697081535. Additionally, the workaround you mentioned is legally problematic and has been removed.

**Comment by poperigby** [comment]
Sorry about that.
