### ISSUE TITLE
Rabi-Ribi (400910)

### ISSUE THREAD

**Issue by wetwayne** [ValveSoftware/Proton#4217]
# Compatibility Report
- Name of the game with compatibility issues: Rabi-Ribi
- Steam AppID of the game: 400910

## System Information
- GPU: RX 480
- Driver/LLVM version: Mesa 20.1.6, LLVM 10.0.1
- Kernel version: 5.8.4
- Link to full system information report: https://gist.github.com/NoahWestervelt/13846973c09cbfd9de4d85d01479b32e
- Proton version: 5.0-9

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Log file
[steam-400910.log](https://github.com/ValveSoftware/Proton/files/5272764/steam-400910.log)

## Symptoms
A black screen appears, then closes when the game crashes. This happens whenever I launch the game from steam.
The game runs fine on Proton version 4.2-9 with the launch options PROTON_NO_ESYNC and -nopreload, but not on newer versions of Proton.

## Reproduction
Set the proton version to 5.0-9.
Start the game from steam.
Click the option 'Play Rabi-Ribi' from the dialog that appears

**Comment by kisak-valve** [comment]
Hello @NoahWestervelt, your log tells us that Vulkan failed to initialize and your system information tells us that you do not have 32 bit vulkan drivers installed for your video card. Please install the `libvulkan_radeon-32bit` package.

**Comment by wetwayne** [comment]
@kisak-valve I could've sworn that I had made sure I had the correct drivers installed, but you were right. How could you tell that was the problem?
