### ISSUE TITLE
Among Us (945360)

### ISSUE THREAD

**Issue by naoliv** [ValveSoftware/Proton#4223]
# Whitelist Request
- Name of the game to be whitelisted: Among Us
- Steam AppID of the game: 945360

Maybe asking for whitelist is too strong here, but consider this as a positive feedback, saying that I was able to properly run the game with Proton.

## System Information
- GPU: Intel HD Graphics 3000
- Driver/LLVM version: 3.0 Mesa 20.1.8
- Kernel version: `5.8.10`
- Link to full system information report as Gist: https://gist.github.com/naoliv/dd213f2c3de50ab1c3878378f2b95ffb
- Proton version: `5.0-9`

Since the GPU doesn't support Vulkan, the game was called with `PROTON_USE_WINED3D=1 %command%`

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [X] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [X] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [X] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @naoliv, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4190#issuecomment-699954465.
