### ISSUE TITLE
Compatibility Report - STAR OCEAN - THE LAST HOPE

### ISSUE THREAD

**Issue by LucasSymons** [ValveSoftware/Proton#4226]
---
name: Compatibility Report
about: Game compatibility issues.

---

# Compatibility Report
- Name of the game with compatibility issues: STAR OCEAN - THE LAST HOPE - 4K & Full HD Remaster 
- Steam AppID of the game: 609150

## System Information
- GPU: AMD Radeon 5700XT
- Driver/LLVM version: Mesa 20.1.7-1 / LLVM 10.0.1-2
- Kernel version: 5.8.6-1
- Link to full system information report as [Gist](https://gist.github.com/):[system info](https://gist.github.com/Akin2Silver/4cb336a355f4a3a2faee30ff8d340bb6)
- Proton version: 5.0-9, 4.11-13, 4.2-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-609150.log](https://github.com/ValveSoftware/Proton/files/5296270/steam-609150.log)
## Symptoms 

Game crashes when selecting any option from the main menu. 
Proton log only shows process exceptions no extra info. 

## Reproduction

Launch game with basic proton support, select `new game` from main menu.

**Comment by kisak-valve** [comment]
Hello @Akin2Silver, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1268#issuecomment-700688870.
