### ISSUE TITLE
Resident Evil 4(UHD Edition) Crashing during gameplay 

### ISSUE THREAD

**Issue by minilandl** [ValveSoftware/Proton#4228]
# Compatibility Report
- Resident Evil 4(UHD Edition)
- 254700

## System Information
- Distro: Arch Linux
- GPU: 750ti
- Driver/LLVM version:  nvidia 455.23.04
- Kernel version: 5.8.12-zen1-1-zen 
- Link to full system information report as [Gist](https://gist.github.com/minilandl/7ee7ae44f888551e3defdb62b2c9f4a2):
- Proton version: 5.9-GE-5-ST

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Resident Evil 4 will eventually crash during gameplay. This is mitigated slightly by installing either faudio in GE or switching to proton 5.0.9 however certain sounds such as  reloading of weapons down play and audio in general inst as good breaking immersion 

## Reproduction
start the game it will eventually crash 

## Related Issues 
https://github.com/ValveSoftware/Proton/issues/890

## Logs
[steam-254700.log](https://github.com/ValveSoftware/Proton/files/5300443/steam-254700.log)

**Comment by kisak-valve** [comment]
Hello @minilandl, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/890#issuecomment-700844970.

**Comment by minilandl** [comment]
after testing again and rebooting the problems I reported seem to not be an issue this could be close but I would be interested if other people had the same issuesw
