### ISSUE TITLE
Games don't launch with Proton.

### ISSUE THREAD

**Issue by jermyork** [ValveSoftware/Proton#4233]
This happens on all games. When I push play, a new black window launches as if the game is going to start, but then it disappears after ~2 seconds. This is a new OpenSuse tumbleweed installation. I ran the same games in my previous tumbleweed installation with no issues. I am launching with a 2nd drive that is formatted in EXT4, with my ownership and 755 access. I was able to pull the following error while running with cli:<br>
> Unhandled exception: page fault on read access to 0x00000008 in 64-bit code

**Comment by kisak-valve** [comment]
Hello @jermyork, the vulkan loader currently being distributed by OpenSUSE Tumbleweed is not compatible with Steam. This is not a Proton issue. Please give https://github.com/ValveSoftware/steam-for-linux/issues/7368 a read.
