### ISSUE TITLE
Make seccomp default

### ISSUE THREAD

**Issue by Liemaeu** [ValveSoftware/Proton#4239]
Would be great if seccomp would be enabled by default, because e.g. Denuvo DRM could ban you for 24h if you don't have seccomp enabled when starting the game.

**Comment by kisak-valve** [comment]
Hello @Liemaeu, my understanding is that there's a performance penalty attached to this workaround which would lower the performance of all games if it was unconditionally enabled. It should only be used with games that are known to need it to run.
