### ISSUE TITLE
Cuphead Working now (268910)

### ISSUE THREAD

**Issue by edn9** [ValveSoftware/Proton#424]
Arch Linux
Kernel 4.18.3
Proton 3.7
bspwm 0.9.5
CPU Intel Core i3-2350m @ 4x 2.3GHz
RAM 4gb
GPU Intel(R) HD Graphics 3000

Logs: https://gist.github.com/necronoise/46b76ddc898ebba805b92eed18329206

**Comment by edn9** [comment]
I clicked in 'Verify integrity of game files...' and now its working more than better, my FPS is amazing and i'm so happy to play it on Linux!

Used this command to run. Working very nice.

> PROTON_USE_WINED3D11=1 %command%

The only bug i get its the / its not showing up.
![image_2018-08-26_12-02-40](https://user-images.githubusercontent.com/28832216/44629649-c4c79400-a928-11e8-858e-39cbd86a86a0.png)

**Comment by bisby** [comment]
I have the game beaten but my parry achievements are still at 0/20 and 0/100. Everything is working great (playing with an Xbox one controller, the steam controller stuff wasn't working properly) except these achievements. Already have most of the other achievements, just wasn't sure if there was an issue with proton counting incremental achievements, or if there is some other weird thing happening (or if it's just me).

**Comment by kisak-valve** [comment]
Hello @necronoise, @bisby, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/304#issuecomment-417771942.
