### ISSUE TITLE
Add the possibility to have the native and the Windows version (with Proton) installed at the same time

### ISSUE THREAD

**Issue by Liemaeu** [ValveSoftware/Proton#4240]
It would be great of you could have both the native version and the Windows version (with Proton) installed at the same time.

E.g. campaign in Total War: Warhammer 2 works better in the native version, but for multiplayer/tournaments you need the Windows version.

**Comment by kisak-valve** [comment]
Hello @Liemaeu, this is a feature request for the Steam client instead of Proton itself, and is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/6085. Closing as a duplicate.
