### ISSUE TITLE
Fallout 4

### ISSUE THREAD

**Issue by dwlyles** [ValveSoftware/Proton#4244]
# Compatibility Report
- Name of the game with compatibility issues: Fallout 4
- Steam AppID of the game: 377160

## System Information
- GPU: AMD 5600xt
- Driver/LLVM version: 4.6 Compatibility Profile Mesa 20.2.0 - kisak-mesa PPA
- Kernel version: 5.4.0-48-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.0-9 currently

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-377160.log](https://github.com/ValveSoftware/Proton/files/5337687/steam-377160.log)

## Symptoms: Game doesn't launch the fallout 4 launcher. Downloads shaders, never goes to launcher and then stops. Game worked on NTFS for awhile. I then moved the game off the disk and formatted to ext4. Moved the game back with same symptoms. Even went as far as re-downloading 80GBs again but still having the same issue.
I have WINEDLLOVERRIDES="xaudio2_7=n,b" PROTON_NO_ESYNC=1 %command% as launch settings
Tried Proton 5.0-9, 4.11 and 5.9GE.

**Comment by kisak-valve** [comment]
Hello @dwlyles, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/308#issuecomment-704630238.
