### ISSUE TITLE
Among Us russian input does not work

### ISSUE THREAD

**Issue by apiprutt** [ValveSoftware/Proton#4246]
# Compatibility Report
- Name of the game with compatibility issues: Among Us
- Steam AppID of the game: 945360

## System Information
- Proton version: 5.0

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

## Symptoms 
Russian input does not work in proton. I tried to launch with options > LC_ALL=ru_RU.UTF-8 %command% < but nothing has happened. If I run this game on wine via > LC_ALL=ru_RU.UTF-8 wine "Among Us.exe" < It's works fine.

**Comment by kisak-valve** [comment]
Hello @lenwtet, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4190#issuecomment-705757569.
