### ISSUE TITLE
Hades (1145360) missing mouse hover on Wayland

### ISSUE THREAD

**Issue by Mershl** [ValveSoftware/Proton#4247]
# Compatibility Report
- Name of the game with compatibility issues: Hades
- Steam AppID of the game: 1145360

## System Information
- GPU: RX 570
- Driver/LLVM version: Mesa 20.2
- Kernel version: 5.8.13
- Proton version: 5.0.9

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
Tooltips/effects in the game are not shown when hovering over any UI element.
The issue is not reproducable and the hover effects are working as intended with Proton-5.9-GE-7-ST.

## Reproduction
Start Hades with Proton 5.0.9 on a Wayland desktop. Hover over the main menu selections - the selections are not changing. Clicking is possible, but the intended tooltips and/or effects while hovering are missing.

**Comment by kisak-valve** [comment]
Hello @Mershl, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3312#issuecomment-705816406.
