### ISSUE TITLE
Ikenfell (854940)

### ISSUE THREAD

**Issue by Darkhogg** [ValveSoftware/Proton#4248]
##  System Information
- GPU: AMD ATI Radeon R7 260X/360
- Driver/LLVM version: Mesa 20.2.0
- Kernel version: 5.8.13-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Darkhogg/c9d2f7e77f34970d9d8808535534869b
- Proton version: 5.0-9

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms

Game doesn't start.

The issue seems to be partially fixed by using the proton version linked in #3886, but some extra errors appear about other unimplemented interfaces or whatever that error means.

## Reproduction
I guess just try to launch it.

**Comment by lilac-galaxy** [comment]
Yep, along with the changes mentioned in #3886 it looks like it's missing an update to the UserStats version (expects 012, but the latest in TOT is 011). Created a quick branch [here](https://github.com/tealnoise/Proton) that takes the relevant commit from that fork and adding the update to the user stats; and with those changes was able to launch the game. 

In general, it looks like the root cause of the issue is based on some updates to the steamworks sdk in version 1.49 that looks to have incremented the expected version numbers (see [here](https://steamcommunity.com/groups/steamworks/announcements/detail/2413314342151736078)).

**Comment by Darkhogg** [comment]
I can confirm that @tealnoise 's fixes work like a charm, the game runs perfectly after launching.

**Comment by rvolgers** [comment]
For those looking for a quick fix, doing a quick and dirty patch on the game binary seems to work as well. Do this at your own risk, of course. I run this Python 3 script in the game directory (the one that contains `IkenfellWin.exe`):


    #!/usr/bin/env python3

    def u(txt):
        return txt.encode('utf-16le')

    with open('IkenfellWin.exe', 'r+b') as f:

        data = f.read()
        f.seek(0)
        
        assert u('SteamUser021') in data, "patch already applied"

        open('IkenfellWin_backup.exe', 'wb+').write(data)

        data2 = data
        data2 = data2.replace(u('SteamUser021'), u('SteamUser020'))
        data2 = data2.replace(u('STEAMUSERSTATS_INTERFACE_VERSION012'), u('STEAMUSERSTATS_INTERFACE_VERSION011'))

        assert len(data) == len(data2)

        f.write(data2)


After applying this patch I can run the game from Steam normally. I do have it set to use the latest 5.x.x version of Proton I can select within Steam, so if it doesn't work for you, you might need to change that setting.

**Comment by Darkhogg** [comment]
It seems that Ikenfell works perfectly for me after the latest Proton 5.13 release, without needing to do any manual patching/compiling from my part.

If @tealnoise or @rvolgers can check and confirm this, I'll close this issue.

**Comment by lilac-galaxy** [comment]
Can confirm latest proton release supports the game (as it now supports steamworks sdk versions 1.49 and 1.50).

**Comment by rvolgers** [comment]
Fwiw, can confirm it works for me too.
