### ISSUE TITLE
Visage missing rendering in mirror.

### ISSUE THREAD

**Issue by ericwomer** [ValveSoftware/Proton#4255]
# Compatibility Report
- Name of the game with compatibility issues: Vissage
- Steam AppID of the game: 594330

## System Information
- GPU: GTX 960
- Driver/LLVM version: NVidia 455.23.04
- Kernel version: 5.4.0-48-generic
- [System Information](https://gist.github.com/ericwomer/cc9435b67f08506e4f239c0721595e6d)
- Proton version: 5.0-9 and 5.9-GE-6-ST

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

Proton Log: Please see #4254

Missing rendering of a scene in the level through a mirror
[Video clip show what should be in the mirror](https://youtu.be/qzxB-vzqB_E)

## Reproduction
Look through the mirror, its black, doesn't show what it is supposed to show.
[Spoilers](https://gist.github.com/ericwomer/a49a4e9294763a8aba94f079e7f800f7)

**Comment by kisak-valve** [comment]
Hello @ericwomer, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1687#issuecomment-706717636.
