### ISSUE TITLE
Call of Duty World at War Crashes with DXVK

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#4256]
# Compatibility Report
- Name of the game with compatibility issues: Call of Duty: World at War
- Steam AppID of the game: 10090

## System Information
- GPU: AMD R5 M430
- Driver/LLVM version: Mesa 20.0.5
- Kernel version: 5.4.0-48-generic
- Link to full system information report as https://gist.github.com/billybob32/a5da6bab842d3bdc4ebb1a9891a0a179
- Proton version: 5.0-9

## I confirm:
- [Yes] that I haven't found an existing compatibility report for this game.
- [Yes] that I have checked whether there are updates for my system available.
======================
Proton: 1591828072 proton-5.0-9
SteamGameId: 10090
Command: ['/home/aiden/.local/share/Steam/steamapps/common/Call of Duty World at War/CoDWaW.exe']
Options: {'forcelgadd'}
======================
ERROR: ld.so: object '/home/aiden/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/aiden/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/aiden/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/aiden/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
esync: up and running.
ERROR: ld.so: object '/home/aiden/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
1020.089:0028:002c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\kernelbase.dll" at 0x7b000000: PE builtin
1020.089:0028:002c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\kernel32.dll" at 0x7b410000: builtin
1020.104:0028:002c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\wineboot.exe" at 0x400000: PE builtin
1020.108:0028:002c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\sechost.dll" at 0x7f379cd40000: builtin
1020.108:0028:002c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\advapi32.dll" at 0x7f379ce90000: builtin
1020.109:0028:002c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\msvcrt.dll" at 0x7f379cc60000: builtin
ERROR: ld.so: object '/home/aiden/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
1020.232:0030:0034:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\kernelbase.dll" at 0x7b000000: PE builtin
1020.232:0030:0034:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\kernel32.dll" at 0x7b410000: builtin
1020.247:0030:0034:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\services.exe" at 0x400000: PE builtin
1020.250:0030:0034:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\sechost.dll" at 0x7f7640170000: builtin
1020.250:0030:0034:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\advapi32.dll" at 0x7f76402c0000: builtin
1020.251:0030:0034:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\msvcrt.dll" at 0x7f7640090000: builtin
1020.252:0030:0034:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0x6fbc0000: PE builtin
1020.253:0030:0034:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\version.dll" at 0x65780000: PE builtin
1020.253:0030:0034:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\setupapi.dll" at 0x6a700000: PE builtin
1020.254:0030:0034:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\userenv.dll" at 0x67d00000: PE builtin
ERROR: ld.so: object '/home/aiden/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
1020.429:003c:0040:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\kernelbase.dll" at 0x7b000000: PE builtin
1020.429:003c:0040:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\kernel32.dll" at 0x7b410000: builtin
1020.444:003c:0040:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\plugplay.exe" at 0x400000: PE builtin
1020.447:003c:0040:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\sechost.dll" at 0x7fc66f860000: builtin
1020.447:003c:0040:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\advapi32.dll" at 0x7fc66f9b0000: builtin
1020.448:003c:0040:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\msvcrt.dll" at 0x7fc66f780000: builtin
1020.480:003c:0040:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0x6fbc0000: PE builtin
ERROR: ld.so: object '/home/aiden/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
1020.816:0058:005c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\kernelbase.dll" at 0x7b000000: PE builtin
1020.816:0058:005c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\kernel32.dll" at 0x7b420000: builtin
1020.828:0058:005c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\PnkBstrA.exe" at 0x400000: native
1020.834:0058:005c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\sechost.dll" at 0x7ea90000: builtin
1020.834:0058:005c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\advapi32.dll" at 0x7eae0000: builtin
1020.834:0058:005c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\iphlpapi.dll" at 0x7eb50000: builtin
1020.836:0058:005c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\msvcrt.dll" at 0x7e9d0000: builtin
1020.838:0058:005c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\ws2_32.dll" at 0x7e980000: builtin
1020.838:0058:005c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\WSOCK32.dll" at 0x6c2c0000: PE builtin
1020.844:0058:005c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\gdi32.dll" at 0x7e600000: builtin
1020.844:0058:005c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\version.dll" at 0x65980000: PE builtin
1020.844:0058:005c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\USER32.dll" at 0x7e770000: builtin
1020.855:0058:005c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\shlwapi.dll" at 0x68c40000: PE builtin
1020.856:0058:005c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\rpcrt4.dll" at 0x6fdc0000: PE builtin
1020.856:0058:005c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\ole32.dll" at 0x65200000: PE builtin
1020.856:0058:005c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\shcore.dll" at 0x64b40000: PE builtin
1020.856:0058:005c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\SHELL32.dll" at 0x7dc00000: builtin
1020.860:0058:005c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\bcrypt.dll" at 0x7dac0000: builtin
1020.860:0058:005c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\crypt32.dll" at 0x7daf0000: builtin
1020.860:0058:005c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\WINTRUST.dll" at 0x62740000: PE builtin
1021.288:0058:005c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\imm32.dll" at 0x6c0c0000: PE builtin
ERROR: ld.so: object '/home/aiden/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
1021.628:006c:0070:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\kernelbase.dll" at 0x7b000000: PE builtin
1021.628:006c:0070:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\kernel32.dll" at 0x7b420000: builtin
1021.641:006c:0070:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\PnkBstrB.exe" at 0x400000: native
1021.647:006c:0070:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\sechost.dll" at 0x7ea90000: builtin
1021.647:006c:0070:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\advapi32.dll" at 0x7eae0000: builtin
1021.648:006c:0070:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\iphlpapi.dll" at 0x7eb50000: builtin
1021.650:006c:0070:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\msvcrt.dll" at 0x7e9d0000: builtin
1021.651:006c:0070:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\ws2_32.dll" at 0x7e980000: builtin
1021.651:006c:0070:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\WSOCK32.dll" at 0x6c2c0000: PE builtin
1021.656:006c:0070:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\gdi32.dll" at 0x7e600000: builtin
1021.657:006c:0070:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\version.dll" at 0x65980000: PE builtin
1021.657:006c:0070:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\USER32.dll" at 0x7e770000: builtin
1021.668:006c:0070:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\shlwapi.dll" at 0x68c40000: PE builtin
1021.669:006c:0070:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\rpcrt4.dll" at 0x6fdc0000: PE builtin
1021.669:006c:0070:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\ole32.dll" at 0x65200000: PE builtin
1021.669:006c:0070:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\shcore.dll" at 0x64b40000: PE builtin
1021.669:006c:0070:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\SHELL32.dll" at 0x7dc00000: builtin
1021.673:006c:0070:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\bcrypt.dll" at 0x7dac0000: builtin
1021.673:006c:0070:trace:loaddll:load_so_dll Loaded L"C:\\windows\\syswow64\\crypt32.dll" at 0x7daf0000: builtin
1021.673:006c:0070:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\WINTRUST.dll" at 0x62740000: PE builtin
1021.817:006c:0070:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\imm32.dll" at 0x6c0c0000: PE builtin
1022.125:006c:007c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\syswow64\\psapi.dll" at 0x6aec0000: PE builtin
ERROR: ld.so: object '/home/aiden/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
1022.163:0080:0084:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\kernelbase.dll" at 0x7b000000: PE builtin
1022.163:0080:0084:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\kernel32.dll" at 0x7b410000: builtin
1022.183:0080:0084:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\winedevice.exe" at 0x400000: PE builtin
1022.188:0080:0084:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\sechost.dll" at 0x7fd891c50000: builtin
1022.188:0080:0084:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\advapi32.dll" at 0x7fd891da0000: builtin
1022.189:0080:0084:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\msvcrt.dll" at 0x7fd891b70000: builtin
1022.190:0080:0084:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\ntoskrnl.exe" at 0x67a00000: PE builtin
1022.226:0080:0084:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0x6fbc0000: PE builtin
1022.686:0080:008c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\drivers\\winebus.sys" at 0x7fd891b20000: builtin
1022.687:0080:008c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\version.dll" at 0x65780000: PE builtin
1022.687:0080:008c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\setupapi.dll" at 0x6a700000: PE builtin
1022.842:0080:008c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\hidclass.sys" at 0x62c40000: PE builtin
1022.842:0080:008c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\drivers\\winehid.sys" at 0x6b3c0000: PE builtin
1022.941:0080:008c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\hid.dll" at 0x64b80000: PE builtin
1023.051:0080:008c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\gdi32.dll" at 0x7fd8914e0000: builtin
1023.051:0080:008c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\user32.dll" at 0x7fd8916a0000: builtin
1023.183:0080:008c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\ole32.dll" at 0x65000000: PE builtin
1023.183:0080:008c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\imm32.dll" at 0x6bec0000: PE builtin
ERROR: ld.so: object '/home/aiden/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
1023.535:00a0:00a4:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\kernelbase.dll" at 0x7b000000: PE builtin
1023.535:00a0:00a4:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\kernel32.dll" at 0x7b410000: builtin
1023.550:00a0:00a4:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\winedevice.exe" at 0x400000: PE builtin
1023.553:00a0:00a4:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\sechost.dll" at 0x7f2cd6e30000: builtin
1023.553:00a0:00a4:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\advapi32.dll" at 0x7f2cd6f80000: builtin
1023.555:00a0:00a4:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\msvcrt.dll" at 0x7f2cd6d50000: builtin
1023.555:00a0:00a4:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\ntoskrnl.exe" at 0x67a00000: PE builtin
1023.586:00a0:00a4:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0x6fbc0000: PE builtin
1023.990:00a0:00ac:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\drivers\\mountmgr.sys" at 0x7f2cd6d00000: builtin
1024.011:00a0:00ac:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\version.dll" at 0x65780000: PE builtin
1024.011:00a0:00ac:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\setupapi.dll" at 0x6a700000: PE builtin
1024.110:0028:002c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\gdi32.dll" at 0x7f379c050000: builtin
1024.113:0028:002c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\version.dll" at 0x65780000: PE builtin
1024.113:0028:002c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\user32.dll" at 0x7f379bde0000: builtin
1024.113:0028:002c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\shlwapi.dll" at 0x68a40000: PE builtin
1024.115:0028:002c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0x6fbc0000: PE builtin
1024.115:0028:002c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\ole32.dll" at 0x65000000: PE builtin
1024.115:0028:002c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\shcore.dll" at 0x64940000: PE builtin
1024.243:0028:002c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\imm32.dll" at 0x6bec0000: PE builtin
1024.344:0028:002c:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\shell32.dll" at 0x7f379c210000: builtin
1024.393:0020:0024:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\kernelbase.dll" at 0x7b000000: PE builtin
1024.393:0020:0024:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\kernel32.dll" at 0x7b420000: builtin
1024.406:0020:0024:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\steam.exe" at 0x7eb30000: builtin
1024.411:0020:0024:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\sechost.dll" at 0x7ea20000: builtin
1024.411:0020:0024:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\advapi32.dll" at 0x7ea70000: builtin
1024.413:0020:0024:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\gdi32.dll" at 0x7e8d0000: builtin
1024.414:0020:0024:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\msvcrt.dll" at 0x7e800000: builtin
1024.415:0020:0024:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0x6fdc0000: PE builtin
1024.418:0020:0024:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\version.dll" at 0x65980000: PE builtin
1024.418:0020:0024:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\user32.dll" at 0x7e5d0000: builtin
1024.418:0020:0024:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\ole32.dll" at 0x65200000: PE builtin
1024.428:0020:0024:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\shlwapi.dll" at 0x68c40000: PE builtin
1024.428:0020:0024:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\shcore.dll" at 0x64b40000: PE builtin
1024.428:0020:0024:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\shell32.dll" at 0x7d4b0000: builtin
1024.574:0020:0024:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\imm32.dll" at 0x6c0c0000: PE builtin
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed
1024.653:0020:0024:err:steam:setup_steam_registry SteamAPI_Init failed
1024.712:0020:0024:trace:seh:raise_exception code=c0000005 flags=0 addr=(nil) ip=00000000 tid=0024
1024.712:0020:0024:trace:seh:raise_exception  info[0]=00000008
1024.721:0020:0024:trace:seh:raise_exception  info[1]=00000000
1024.721:0020:0024:trace:seh:raise_exception  eax=7e655550 ebx=00000076 ecx=7e8e4a61 edx=0031ee48 esi=002190ac edi=002190a8
1024.721:0020:0024:trace:seh:raise_exception  ebp=0031ee38 esp=0031edfc cs=0023 ds=002b es=002b fs=0063 gs=006b flags=00010212
1024.722:0020:0024:trace:seh:call_stack_handlers calling handler at 0x7b46bf10 code=c0000005 flags=0
wine: Unhandled page fault on execute access to 00000000 at address 00000000 (thread 0024), starting debugger...
1024.727:0020:0024:trace:seh:start_debugger Starting debugger L"winedbg --auto 32 100"
1024.728:0020:0024:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 32 100" (1115)
Read the Wine Developers Guide on how to set up winedbg or another debugger
1024.728:0020:0024:trace:seh:__regs_RtlUnwind code=c0000005 flags=2
1024.728:0020:0024:trace:seh:__regs_RtlUnwind eax=00000000 ebx=00000000 ecx=c0000005 edx=0031ff78 esi=0031eda4 edi=0031ff78
1024.728:0020:0024:trace:seh:__regs_RtlUnwind ebp=0031e998 esp=0031e990 eip=7b46bebe cs=0023 ds=002b fs=0063 gs=006b flags=00000206
1024.728:0020:0024:trace:seh:__regs_RtlUnwind calling handler at 0x7bcce700 code=c0000005 flags=2
1024.728:0020:0024:trace:seh:__regs_RtlUnwind handler at 0x7bcce700 returned 1
1024.801:0080:0090:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\drivers\\winehid.sys" : builtin
1024.801:0080:0090:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\hidclass.sys" : builtin
1024.803:0080:0090:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\drivers\\winebus.sys" : builtin
pid 4216 != 4215, skipping destruction (fork without exec?)

## Symptoms
Game just doesn't run. It runs for a bit, then crashes. used to crash my whole pc. Now it just crashes the game.

## Reproduction
I just have to launch it on steam, it crashes. Forcing it to not use DXVK with PROTON_USE_WINED3D=1 %command% fixes the issue.

**Comment by kisak-valve** [comment]
Hello @billybob32, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/360#issuecomment-706805237.
