### ISSUE TITLE
Rocket League not launching

### ISSUE THREAD

**Issue by Owez** [ValveSoftware/Proton#4257]
# Compatibility Report
- Name of the game with compatibility issues: Rocket League
- Steam AppID of the game: 252950

## System Information
- GPU: RX580
- Driver/LLVM version: Mesa 20.0.8 (LLVM 10.0.0) (taken from `vulkaninfo`)
- Kernel version: 5.4.0-48-generic
- Link to full system information report as [Gist](https://gist.github.com/): [Info](https://gist.github.com/Owez/41c560aba9fd8dc0f0c278fcaa72db5b)
- Proton version: `Proton 5.0-9`

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-252950.log](https://github.com/ValveSoftware/Proton/files/5366364/steam-252950.log)

## Symptoms 

I have tried to launch the game but it doesn't show anything and fails after ~5 seconds of a "cancel x" or "stop x" button. I have tried reinstalling steam and wiping all `.steam/` along with reinstalling the game from my ext-4 partitioned external drive to root ssd (even though that shouldn't be a problem). Can't seem to get it to work apart, using the `PROTON_USE_WINED3D=1` or leaving it out of the launch options.

## Reproduction

Not sure how to reproduce, I can only find some errors regarding cryptic memory addresses, pid swaps once it crashes (which I assume is steam handling pid control, not the game) and possibly something to do with 32bit vs 64bit ELF as I had 32bit vs 64bit errors when trying do debug via using `wine` directly and I remember an error regarding ELF linking in general. This started a week ago and it may be an issue with updated graphics drivers but a lot has been changed apart from a `upgrade` updating drivers near the time for my RX580. Running on linux mint 20, all stock with only steam and programming tools installed (e.g. vscode which shouldn't affect in any way).

**Comment by kisak-valve** [comment]
Hello @Owez, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3521#issuecomment-707233259.
