### ISSUE TITLE
Human Fall Flat

### ISSUE THREAD

**Issue by jshaker000** [ValveSoftware/Proton#4261]
# Compatibility Report
- Name of the game with compatibility issues: Human Fall Flat
- Steam AppID of the game: 477160/

## System Information
- GPU: Integrated 
- Driver/LLVM version: 
GPU0:
        apiVersion         = 4202641 (1.2.145)
        driverVersion      = 83894272 (0x5002000)
        vendorID           = 0x8086
        deviceID           = 0x1626
        deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
        deviceName         = Intel(R) HD Graphics 6000 (BDW GT3)
        driverID           = DRIVER_ID_INTEL_OPEN_SOURCE_MESA
        driverName         = Intel open-source Mesa driver
        driverInfo         = Mesa 20.2.0
        conformanceVersion = 1.2.0.0

- Kernel version: 5.8.14-arch1-1
- Proton version:  default

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Single Player works correctly.

Multiplayer with either another computer on windows / mac host fails with this error: (note that I seem to be able to choose to launch in Play 64 or Human Fall Flat, but neither seem to make an error). I experience this failure on both launch options, with either my as the host of the native runner as the host.

https://imgur.com/a/htKehaK

**Comment by topsyandpip56** [comment]
You're running the Linux native build of Human Fall Flat, which hasn't been updated for a long while; hence the version mismatch. You need to force Proton in the game options to use the Windows version which is working fine in Proton.

**Comment by ruineka** [comment]
@kisak-valve This game should not be deck verified it crashes alot especially when loading new scenes. My kids beat this game over the weekend with frequent crashes both on my Steam Decks and our Linux PCs.

I tested with alot of proton versions as well.
The crash logs are massive in size.
