### ISSUE TITLE
Star Trek Online chat issue, Proton 5.0.9

### ISSUE THREAD

**Issue by fbenedett** [ValveSoftware/Proton#4264]
People... I am not sure if this is the right place to put this issue.  Apologies if I am mistaken.

# Compatibility Report
- Name of the game with compatibility issues:  Star Trek Online
- Steam AppID of the game: 9900

## System Information
Distro:Ubuntu 18.04.5 LTS
Kernel:5.4.0-48-generic
RAM:32 GB
GPU Driver:NVIDIA 450.66
GPU:NVIDIA GeForce 930MX
CPU:Intel Core i5-8250U @ 1.60GHz
- Proton version: 5.0.9

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-9900.log](https://github.com/ValveSoftware/Proton/files/5385992/steam-9900.log)
## Symptoms
The game runs smoothly using also: SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0; %command%
BUT the chat does not work anymore if a person switch to another character.

## Reproduction
Log in Star Trek Online with a character.  Press esc and use the Switch character option.
It is impossible to write or read anything in the chat.  The chat result to be completely empty all the time.

**Comment by kisak-valve** [comment]
Hello @fbenedett, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1198#issuecomment-709406629.
