### ISSUE TITLE
Allow an alternate directory for log files

### ISSUE THREAD

**Issue by madewokherd** [ValveSoftware/Proton#4265]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

Please add an option that I can set, possibly in `user_settings.py`, to put steam-*.log files somewhere other than $HOME. I'd rather avoid cluttering that directory if possible.

**Comment by aeikum** [comment]
This is available now in 5.0-10. You can set `PROTON_LOG_DIR` to set where log files will go. It will also be in an upcoming 5.13 release, let's leave this open until then.

**Comment by aeikum** [comment]
This is also now available on the 5.13 branch.
