### ISSUE TITLE
Galactic Civilizations III: No mouse cursor painted in-game

### ISSUE THREAD

**Issue by someg33zer** [ValveSoftware/Proton#4276]
# Compatibility Report
- Name of the game with compatibility issues: Galactic Civilizations III
- Steam AppID of the game: [226860](https://store.steampowered.com/app/226860/Galactic_Civilizations_III/)

## System Information

- GPU: custom Nvidia GPU based on the GeForce 860M (Dell Alienware Alpha R1)
- Driver/LLVM version: 4.6.0 NVIDIA 453.21
- Kernel version: 5.4.0-51-generic
- Link to full system information report as Gist: https://gist.github.com/someg33zer/be2456e36038175c8663687b02f27233
- Proton version: 4.2-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

NB: When adding PROTON_LOG=1, the game does not run.  The screen goes black as if the game is loading but then it disappears and the game is no longer running.  Removing PROTON_LOG=1 makes the game run OK.  Here is the the log anyway:

[steam-226860.log](https://github.com/ValveSoftware/Proton/files/5391249/steam-226860.log)

## Symptoms

When you start a new game, there is no mouse cursor painted on the screen although controls highlight and unhighlight while moving the mouse around.

Originally I created this issue to say that the screen freezes when clicking on ships.  However while collating all the information for the issue, the mouse cursor seems to have disappeared and I can't seem to get the game to run in a way that makes the mouse cursor visible.

Various issues persist using combinations of PROTON_USE_WINED3D=1, PROTON_NO_EFUSE=1 and all versions of Proton.  Sometimes the game will just crash on startup.  With the Glorious Eggroll version of Proton, sometimes the game starts eating up memory until it's killed by the kernel.

## Reproduction

Run game.  Click on "Quick start" in the main menu (with visible mouse cursor).  When the new game appears, no mouse cursor is visible.

**Comment by kisak-valve** [comment]
Hello @someg33zer, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1508#issuecomment-710017864.
