### ISSUE TITLE
GRID (2019) Crashing When Changing Graphics Presets - 5.13-1

### ISSUE THREAD

**Issue by cow-killer** [ValveSoftware/Proton#4280]
# Compatibility Report
- Name of the game with compatibility issues: [GRID (2019)](https://store.steampowered.com/app/703860/GRID/)
- Steam AppID of the game: 703860

## System Information
- GPU: GTX 1660
- Driver/LLVM version: 455.28
- Kernel version: 5.9
- System information report at [Gist](https://gist.github.com/cow-killer/e97b983728e2f391627c04ee40e5c5de)
- Proton version: 5.13-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Proton log posted [here](https://gist.github.com/cow-killer/dc81614808d1018751c73a4d83754103)

## Symptoms 
GRID (2019) now works with Proton 5.13-1, including video playback. However, changing the graphics preset and applying the changes causes the game to hang. Resolution can still be changed without hanging. Graphics can also be changed manually in the `hardware_settings_config.xml` located at `~/.steam/root/steamapps/compatdata/703860/pfx/drive_c/users/steamuser/My Documents/My Games/GRID (2019)/hardwaresettings`.

If it helps I managed to get a couple of crash reports from the crash dialog box that appears whenever the preset is changed: https://www.dropbox.com/s/sixpxzgejnfl9e2/a10b7d18-f261-4f9c-ac24-615bb0be0b87.zip?dl=0

**Comment by kisak-valve** [comment]
Hello @cow-killer, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3143#issuecomment-710233764.

**Comment by GaultGame** [comment]
GRID is running very well again with the latest version of Proton Experimental.
