### ISSUE TITLE
Satisfactory Proton 5.13-1 regression (game not starting), 5.0-9 and 5.9-GE-8-ST are fine.

### ISSUE THREAD

**Issue by Optimus22Prime** [ValveSoftware/Proton#4281]
# Compatibility Report
- Name of the game with compatibility issues: Satisfactory
- Steam AppID of the game: 526870

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 450.66
- Kernel version: 5.4.57
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Optimus22Prime/cdb96640af9ca811b6afd5f4874e3176
- Proton version: 5.13-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Satisfactory game won't starting with Proton 5.13-1. It's working fine with Proton 5.0-9 and 5.9-GE-8-ST.

## Reproduction
rm -rf ~/.steam/steam/steamapps/compatdata/526870 
Delete Satisfactory (If Satisfactory was installed before)
Install Satisfactory
Select Proton 5.13-1 in game parameters
Run
Game will show Satisfactory splash, then crash without any warnings or errors on screen

Game working fine with Proton 5.0-9 and 5.9-GE-8-ST

[steam-526870.log](https://github.com/ValveSoftware/Proton/files/5394692/steam-526870.log)

**Comment by kisak-valve** [comment]
Hello @Optimus22Prime, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3957#issuecomment-710697799.
