### ISSUE TITLE
vr games don't run outside of steam

### ISSUE THREAD

**Issue by flutterbrony** [ValveSoftware/Proton#4302]
Hi,

I'm having an issue with proton when launching a game with steam vr outside of steam, the game always launch without using steamvr, but when I launch it inside steam, it work.

I tried using WineOpenVR, but it's not updated anymore and still use OpenVR 1.0.13 (I could update it to 1.0.17, but after, it start to fail to build) and the apps don't work (probably because it's a 3 years old Openvr).

There must be a way to get the vr working on proton as vrchat or beat saber on steam are working fine with steamvr on linux, and they are running inside proton, but I don't know how to do it outside of steam ?

When I try to launch it with /opt/proton/5.13/bin/wine, or with ~/.local/share/Steam/ubuntu12_32/run.sh /opt/proton/5.13/bin/wine, I get this error : 

Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Application Data\openvr\openvrpaths.vrpath

How can I make it working ?

Thanks,
Flutter

**Comment by aeikum** [comment]
You can't run Proton's wine directly, you must use the `proton` script. I'm not sure what you're trying to do, but you may want to use the non-Steam game feature of the Steam client. Running Proton outside of Steam isn't something we support.

**Comment by Lyle-Tafoya** [comment]
I can confirm that VR games work when calling the proton script. For example:

    STEAM_COMPAT_DATA_PATH=/some/path ~/.local/share/Steam/steamapps/common/Proton\ 5.0/proton run /path/to/game.exe

**Comment by flutterbrony** [comment]
Thanks a lot Lyle, it works for some of my games, I'll watch for the other what is causing the games to boot then close immediately after later.

I'm sorry aeikum, I didn't knew it's not supported to run a windows game with proton outside of steam. I did that because all windows games I add on steam don't work with proton, even a simple game like Tomb Raider iv (I have the game on steam and on cd). The game work fine if I download it from steam and launch it from steam, but if I install the cd version, it works well with wine, but if I add it to steam and I try to launch it, nothing happens.
Should steam launch the game with proton without issue, or steam block the game to restraint proton to steam only ?

**Comment by flutterbrony** [comment]
Ok, everything work, thanks for the help Lyle-Tafoya !
