### ISSUE TITLE
After `make install`, local build of Proton looks for shared object files in wrong directory

### ISSUE THREAD

**Issue by bradley-evans** [ValveSoftware/Proton#4311]
After running `make install` per the README on the root repository page, I have a local `proton_5.13-local` folder in my `~/.steam/root/compatabilitytools.d/`. Attempting to run `~/.steam/root/compatabilitytools.d/proton_5.13-local/dist/bin/wine64 winecfg` returns the following error:

```
wine: failed to initialize: /home/vagrant/build-proton_5.13-local/dist-wine32/lib/wine/ntdll.dll.so: cannot open shared object file: No such file or directory
```

I suspect an environment variable is not getting set somewhere, but I'm not sure where. This breaks tools like `protontricks`, which will return an error like:

```
------------------------------------------------------
warning: /home/brad/.cache/protontricks/proton/Proton 5.13/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "wine: failed to initialize: /home/vagrant/build-proton_5.13-local/dist-wine32/lib/wine/ntdll.dll.so: cannot open shared object file: No such file or directory" 
------------------------------------------------------
```

**Comment by Ammako** [comment]
It's pretty crappy, but on Linux, when you run something like this through command line, active directory by default is the directory from which you're running the command. To get around this, I use a script that sets the active directory before running the binary.

```
#!/bin/bash

pushd $HOME/.steam/root/compatabilitytools.d/proton_5.13-local/dist/bin && wine64 winecfg && popd
```

See if this helps

**Comment by ghost** [comment]
Does it work if you use `make redist` instead?

**Comment by aeikum** [comment]
You cannot run Proton's wine directly, you must use the `proton` script. If you want to run winecfg in a Proton prefix, I suggest using the `PROTON_DUMP_DEBUG_COMMANDS` option. Note that you will also need to set `PROTON_DEBUG_DIR` to someplace in your Home directory, since the container deletes its `/tmp/` upon exit.

**Comment by h1z1** [comment]
@aeikum  This happens WITH the debug script from proton

```
./run cmd.exe
wine: failed to initialize: /home/vagrant/build-proton_5.13-local/dist-wine32/lib/wine/ntdll.dll.so: cannot open shared object file: No such file or directory
```

I don't know when that broke but I've used it for .. years?  Since it was added.
