### ISSUE TITLE
Elder Scrolls Online - stuck at login screen (happens 3 out of 4)

### ISSUE THREAD

**Issue by maboleth** [ValveSoftware/Proton#4314]
# Compatibility Report
- Elder Scrolls Online
- Steam AppID of the game: 306130

## System Information
- Nvidia 1060 6gb vram
- Nvidia 455.28
- Kernel 5.8.14
- Arch Linux gnome
- Proton: 5.0.9 and 5.13

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Once the initial logos go off, the game is stuck at the login screen. It's like it's frozen. The pointer works but I cannot click on anything inside the game. After I go out of the game and back, I perform a 'force quit'. If I do it enough times (restarting the game from the launcher) the game will eventually continue logging in without any problems.

## Reproduction

Start the game, wait for the logos to come and go and see if the game will log you in.

I'm sorry but I couldn't find $HOME/steam-$APPID.log file anywhere in .steam dir after putting Proton log in the launch line.

**Comment by kisak-valve** [comment]
Hello @maboleth, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/556#issuecomment-716140445.
