### ISSUE TITLE
[Whitelist] Mighty Switch Force! Hyper Drive Edition (366970)

### ISSUE THREAD

**Issue by vandergail** [ValveSoftware/Proton#432]
Tested on two different machines and runs well on both of them.

Machine 1 [System Info](https://gist.github.com/bikkusu/e66891a7ef79d8649460f70af70d0fb8)
Machine 2 [System Info](https://gist.github.com/bikkusu/fd134218d11c62fa75e9ea11cd300693)

**Comment by kisak-valve** [comment]
Found in the 2018-10-05 white list update.
