### ISSUE TITLE
SCP: Secret Laboratory is not working in version 5.13-1

### ISSUE THREAD

**Issue by rogeritos** [ValveSoftware/Proton#4320]
I'm trying to play the game "SCP: Secret Laboratory" but I'm not able to start it, every time I click "play" it gives an error "Can't obtain system code integrity info (C0000003)!".I tested it on proton version 5.13-1

**Comment by kisak-valve** [comment]
Hello @rogeritos, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4229#issuecomment-717343322.
