### ISSUE TITLE
Ys VIII: Lacrimosa of DANA (579180)

### ISSUE THREAD

**Issue by daigennki** [ValveSoftware/Proton#4325]
# Compatibility Report
- Name of the game with compatibility issues: Ys VIII: Lacrimosa of DANA
- Steam AppID of the game: 579180

## System Information
- GPU: AMD Radeon R9 390
- Driver/LLVM version: amdvlk 2020.Q4.1-1 (happens with Mesa vulkan-radeon 20.2.1-1 as well)
- Kernel version: 5.9.1-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/daigennki/973117d6025250d6403458074b7225d1
- Proton version: 5.13-1 (happens with 5.0-9 as well)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-579180.log](https://github.com/ValveSoftware/Proton/files/5452423/steam-579180.log)

## Symptoms 
This is a weird one. Lipsyncing in cutscenes with full voiceovers doesn't seem to work. To be specific, none of the characters' lips move in cutscenes ("events") with voiceovers and subtitles at the bottom of the screen, but they do move in short cutscenes with the text in speech bubbles. This problem definitely doesn't happen when run on Windows natively.

## Reproduction
Launch the game and start a new game, then wait for voiceovers to be played in the opening cutscene. If there is already a save file, either load that and trigger a cutscene with full voiceovers, or go to the event gallery in "Gallery" in the title screen and play any event. Happens for save files that were created on either a Windows or Linux machine.

**Comment by kisak-valve** [comment]
Hello @daigennki, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3820#issuecomment-717974223.

**Comment by daigennki** [comment]
I understand. Sorry about that!
