### ISSUE TITLE
Is Proton compatible with Nouveau drivers?

### ISSUE THREAD

**Issue by TildeEthDoUsPart** [ValveSoftware/Proton#4327]
I've been having issues with NVidia lately, mainly because no games will start with NVidia 418, and installing 435 works but causes a lot of different issues I do not want to deal with.
I learned about the Nouveau drivers recently, but I just wanted to make sure: Does Proton run properly with the nouveau drivers?
I only want to install it for proton, but if it doesn't work, I'd rather avoid all the trouble that goes with installing new drivers.

**Comment by kisak-valve** [comment]
Hello @ThatDamGuy, Proton uses DXVK to translate DirectX 9/10/11 to Vulkan, and vkd3d-proton to translate DirectX 12 to Vulkan. Nouveau does not support Vulkan, making it unsupported. That said, with nouveau, you could try setting `PROTON_USE_WINED3D=1` to tell Proton to use wine's DirectX to OpenGL render path for DirectX 11 and older games, but this is also not considered supported and comes with a significant performance penalty on top of the low performance expected from nouveau.
