### ISSUE TITLE
Proton titles appear as wine64-preloader on Discord

### ISSUE THREAD

**Issue by alosarjos** [ValveSoftware/Proton#4335]
When launching a game from Steam, Discord recognizes I'm playing something, but it shows up as "wine64-preloader"

![image](https://user-images.githubusercontent.com/29999427/97807033-d5899800-1c5e-11eb-9c7d-d14b411e570b.png)

- Arch Linux x64
- Proton 5.13

**Comment by kisak-valve** [comment]
Hello @alosarjos, this issue is already being tracked at #1473. Closing as a duplicate.
