### ISSUE TITLE
Tokyo Dark (687260) Game installs, shows "running", then stops

### ISSUE THREAD

**Issue by benbrockn** [ValveSoftware/Proton#4337]
# Compatibility Report
- Name of the game with compatibility issues: **Tokyo Dark**
- Steam AppID of the game: **687260**

## System Information
- GPU: **GTX-1080**
- Driver/LLVM version: **455.28**
- Kernel version: **5.9.1-arch1-1**
- Link to full system information report as **[System Info Gist here](https://gist.github.com/benbrockn/d10cb8c5e3affbcb180f57e38ede13d9#file-steam_system_info)**
- Proton version: **5.0-9**

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms

Game installs, shows "Running", then stops the game

**[Tokyo Dark Gist here](https://gist.github.com/benbrockn/d10cb8c5e3affbcb180f57e38ede13d9#file-steam-687260-log)**

These commands (each separately & together) won't allow the game to load

    `PROTON_USE_WINED3D=1 PROTON_NO_ESYNC=1 PROTON_LOG=1 %command%`

**[This other issue](https://github.com/ValveSoftware/Proton/issues/2405)** might be related

**My specs:**

OS: EndeavourOS Linux x86_64
Kernel: 5.9.1-arch1-1
Shell: bash 5.0.18
Resolution: 2560x1440 @ 144Hz, 1920x1080 @ 60Hz
DE: Xfce
WM: Xfwm4
CPU: AMD Ryzen 7 2700 (16) @ 3.966GHz
GPU: NVIDIA GeForce GTX 1080
Memory: 32125MiB

## Reproduction

N/A

**Comment by kisak-valve** [comment]
Hello @benbrockn, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2405#issuecomment-720179157.
