### ISSUE TITLE
F1 Race Stars

### ISSUE THREAD

**Issue by thesnable** [ValveSoftware/Proton#4338]
# Compatibility Report
- Name of the game with compatibility issues: F1 Race Stars
- Steam AppID of the game: 203680

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
CTD

## Reproduction
Every time. No Error Message

https://gist.github.com/thesnable/da4f0258d7e8f513f1af9a19c3d8907f

**Comment by kisak-valve** [comment]
Hello @thesnable, we're using one issue report per unofficially supported game title, and this game is already being tracked at #2765. Looks like a CEG issue.

Closing in favor of the existing compatibility report.
