### ISSUE TITLE
[Whitelist] PAC-MAN Championship Edition DX+ (236450)

### ISSUE THREAD

**Issue by Zero86Sk** [ValveSoftware/Proton#434]
Game runs at full speed with no slowdowns

My Specs:
https://gist.github.com/Zero86Sk/d629f657c1ae861c36657cdf238a7765

**Comment by martynhare** [comment]
Game just works including controller support.

System Specs: https://gist.github.com/MartynHare/dfc6bcccb35c8f28dd5c1399c2db5c71

**Comment by shane-powell** [comment]
Game works fine with USB xbone controller.

Ubuntu 18.04.1 LTS
GeForce GTX 1060 6GB (396.54)
Proton 3.7 (default configuration)

**Comment by flibitijibibo** [comment]
@kisak-valve Requesting an XAudio2 label for this game...

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.

**Comment by flibitijibibo** [comment]
This likely affects other games but I'm logging this here for myself... when using 5.1 output games like CEDX+ will fail with native XAudio2 will segfault when creating the WASAPI device. I believe FAudio fixes this but I don't think we want to enable the builtin for 32-bit games (yet?).

Tested with Bill's Hat: https://plus.google.com/+flibitijibibo/posts/f11ZFpyUzob

This doesn't appear to be a regression, just a bug that was never caught even with the whitelisted version.

**Comment by mwprado** [comment]
on steamos i have to set -l1920 -w1080 to fix resolution (Screen was showing only 1/4 from game pixesl).
