### ISSUE TITLE
No Man's Sky

### ISSUE THREAD

**Issue by taldarus** [ValveSoftware/Proton#4342]
# Compatibility Report
- Name of the game with compatibility issues: No man's sky
- Steam AppID of the game: 275850

`System Information
- GPU: GeForce GTX 970
- Driver/LLVM version: nvidia v: 390.138
- Kernel version: 5.4.0-52-generic x86_64
- Proton version: 3.16, 3.7 are both installed, but I thought I was using 5.13/up to date

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Log:
Did this got nothing, see the problem.

## Symptoms 

Run the game and I am getting still getting "SteamAPI_Init failed. No license or steam isn't running."

I wasn't up to date when the error started, I have rebooted and restarted everything multiple times.

Sorry if this is the wrong place. I mostly want to return game atm, but it's for my kids. I searched multiple times and turned up nothing. It feels like a missing file, not a compatibility issue, but steam support drone referred me to here.

## Reproduction

It's easy to reproduce :)

I just hit play and it doesn't work. Sorry I can't give you a fancy log, as steamAPI is the problem, so asking it for a log doesn't work.

**Comment by kisak-valve** [comment]
Hello @taldarus, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-720658016.
