### ISSUE TITLE
[Regression 5.13] Vulkan layers are no longer loaded by DXVK

### ISSUE THREAD

**Issue by mcoffin** [ValveSoftware/Proton#4351]
# Summary 

In `Proton 5.0-9`, setting the `VK_INSTANCE_LAYERS` environment variable correctly loads given Vulkan layers. After `Proton 5.13`, the Vulkan layers no longer load. I have tried with upstreamed [`dxvk`](https://github.com/doitsujin/dxvk) and `wine-staging`, and it still works there, so I think the issue is in Proton rather than DXVK.

Layers that I have tried as test cases:

* [vkBasalt](https://github.com/DadSchoorse/vkbasalt)
* [vulkan-device-filter](https://gitlab.com/mcoffin/vulkan-device-filter)
* `VK_LAYER_MESA_overlay` from [`mesa`](https://mesa3d.org)

This has prevented me from switching to 5.13 for many titles, as I have a pretty heavy set of layers for nigh every game that I run. Any tips on where to start looking would also be appreciated, as after checking that the issue isn't with a change in the [`dxvk`](https://github.com/doitsujin/dxvk) version, I'm sort-of at a loss for where to start looking.

Checking `/proc/THE_GAME_PID/environ`, it seems that `VK_INSTANCE_LAYERS` is indeed still being set, but just somehow not used by Vulkan.

# Expected Behavior

Setting `VK_INSTANCE_LAYERS` in the environment should properly load Vulkan layers.

# Observed Behavior (post 5.13)

`VK_INSTANCE_LAYERS` has no effect on loaded vulkan layers

# Relevant system information

* [`mesa`](https://mesa3d.org) version - `20.2.1`

Thank in advance for the help,
Matt

**Comment by kisak-valve** [comment]
Hello @mcoffin, this issue is already being tracked at https://github.com/ValveSoftware/steam-runtime/issues/295. Closing as a duplicate.

**Comment by mcoffin** [comment]
> ValveSoftware/steam-runtime#295

@kisak-valve Ah, thanks. I didn't think to look in `steam-runtime` since I don't really use it on it's own for any games. Thanks!
