### ISSUE TITLE
Mafia definitive edition

### ISSUE THREAD

**Issue by Mark-papi** [ValveSoftware/Proton#4359]
# Compatibility Report
- Name of the game with compatibility issues: mafia definitive edition
- Steam AppID of the game:1030840

## System Information
- GPU:  GTX 1660 SUPER

## Reproduction

When starting the game it crashes automatically with an error https://pastebin.com/F8WgDEuE

**Comment by kisak-valve** [comment]
Hello @Mark-papi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4220#issuecomment-723577323.
