### ISSUE TITLE
Dead Rising 3: Apocalypse Edition (265550)

### ISSUE THREAD

**Issue by SeraphisCain** [ValveSoftware/Proton#4361]
EDIT: My apologies, please delete, I didn't see the existing compatibility report the first time I searched. I've added this report to that thread. 

# Compatibility Report
- Name of the game with compatibility issues: Dead Rising 3: Apocalypse Edition
- Steam AppID of the game: 265550

## System Information
- GPU: Radeon RX Vega 11
- Driver/LLVM version: X.Org AMD RAVEN (DRM 3.35.0)/LLVM 10.0.0
- Kernel version:  5.4.0-52-generic
- Link to full system information report as [Gist](https://gist.github.com/SeraphisCain/858e4036c0bac4e0dd4e0009580e21af):
- Proton version: 5.13

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-265550.log](https://github.com/ValveSoftware/Proton/files/5514807/steam-265550.log)

## Symptoms 
Game crashes after opening cutscene.

## Reproduction
Start a new game in Story Mode, either watch or skip the opening cutscene.

**Comment by kisak-valve** [comment]
Closing in favor of #2238.
