### ISSUE TITLE
Thank you for your hard work, Kisak

### ISSUE THREAD

**Issue by ctjlewis** [ValveSoftware/Proton#4364]
Sorry for opening up a junk issue @kisak-valve, but there's no other way to really get a message to you, since GH doesn't support DMs. Please close this when you see it.

Read: [A thank-you letter to Kisak at Valve](https://medium.com/telework/a-thank-you-letter-for-kisak-at-valve-a74115c35d8e)

**Comment by kisak-valve** [comment]
Hello @ctjlewis, please do not promote a subreddit that was created to coordinate trolling and trick the passing user to donate to scam patreon accounts.

Closing as spam.
