### ISSUE TITLE
S.T.A.L.K.E.R.: Shadow of Chernobyl (4500) always uses OpenGL and not DXVK

### ISSUE THREAD

**Issue by Deus-nsf** [ValveSoftware/Proton#4368]
This is with Proton 5.0-10 and 5.13-1, I even tried to downgrade to version 4 and force D9VK with PROTON_USE_D9VK=1 %command% in the steam launch options for the game, but no success. No problems launching with DXVK on other Direct3D games.

The game works in OpenGL but since it is very single thread bottlenecked (even on native windows) Vulkan can definitely help with performance.

**Comment by kisak-valve** [comment]
Hello @RSF-Deus, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by kisak-valve** [comment]
Also, please check your in-game lighting settings. Supposedly, if static lighting is set, then the game renders with DirectX 8 instead of DirectX 9, and would exclude you from taking advantage of DXVK.

**Comment by Deus-nsf** [comment]
Thank you for answering so fast!

The game is in full dynamic lighting (aka DX9), I noticed something strange however, on windows 10, it is one of the only game engines to tolerate alt + tab and injectors like RTSS but only if you manually launch the game's executable (XR_3DA.exe) as administrator... (even compatibility as admin doesn't work, really only right click and launch as admin does) and I had this issue on many windows machines, probably as old as windows 7 actually. I'm not sure but I think the original Metro 2033 (not redux) had the same issue, it works very well with DXVK from DX11 though.

Maybe if I'll launch the game on linux with elevated priviledges something different might happen, I'll be sure to get the log asap (I don't have access to my friend's linux build right now)

**Comment by kisak-valve** [comment]
It should be noted that Steam does not support being run as root and there's no legitimate reason to do that with any game on Linux.

**Comment by Deus-nsf** [comment]
Launching games as admin has actually been a workaround on windows to be able to use the steam overlay on some games that does not support it (the stalker series and the original metro 2033 for example, but there are others).
Not trying to discredit what you are saying of course, just thought it was interesting to share this.
I'll come back with that log as soon as I get it :)

**Comment by Deus-nsf** [comment]
[steam-4500.log](https://github.com/ValveSoftware/Proton/files/5539436/steam-4500.log)

Here it is!

`Linux FabienPC 5.8.18-1-MANJARO #1 SMP PREEMPT Sun Nov 1 14:10:04 UTC 2020 x86_64 GNU/Linux`

**Comment by kisak-valve** [comment]
When you were testing, did you try changing the per-game compatibility tool override setting or just the global compatibility tool setting? Since this is a whitelisted game title, the whitelisted Proton version takes priority over the global setting.

Steam Library -> select game -> Gear icon -> Properties... -> check `Force the use of a specific Steam Play compatibility tool`

The whitelist currently has this game set to Proton 3.16, which predates DirectX 9 support in DXVK.

**Comment by Deus-nsf** [comment]
Indeed, forcing a specific Proton version switches the game back to Vulkan, allowing for double the framerate compared to OpenGL on the exact same scene! (120 -> +-225)!
Thank you very much!

EDIT: I was certain of it! With the exact same parameters and the exact same save file on the exact same machine, Linux has better performance than Windows!! 240 FPS vs 190 FPS on the same scene (Vulkan VS D3D9), an other scene more taxing with again the same save file, 170 FPS VS 130 FPS! Since there is a huge CPU single thread bottleneck on this game, Vulkan helps lift it and the performance is better, even still on a single thread! If only DXVK worked on Windows for that game! But I understand it is not officially supported. It is incredible though.
