### ISSUE TITLE
[WHITELIST] Sonic Mania & Sonic Mania Plus

### ISSUE THREAD

**Issue by dominichayesferen** [ValveSoftware/Proton#437]
Tried both Sonic Mania and Sonic Mania Plus in Steam Play, as well as the in-game route of buying the Plus DLC, and I can confirm it all works ABSOLUTELY FINE for me... The game works just like it would on Windows, minus the Steam Controller support (also happened in Geometry Dash (they don't recognise inputs from the Steam Controller like they would if ran natively))...

**Comment by kisak-valve** [comment]
Hello @feren, this is already being tracked at #105. Closing as a duplicate.
