### ISSUE TITLE
Fallout: New Vegas crashes to desktop on launch with Proton 5.13.2 and 5.0.10

### ISSUE THREAD

**Issue by Antarctic-Ice-Shelf** [ValveSoftware/Proton#4371]
# Compatibility Report
- Name of the game with compatibility issues: Fallout: New Vegas
- Steam AppID of the game: 22380

## System Information
- GPU: Intel Mesa Intel(R) Iris(R) Plus Graphics (ICL GT2)
Note: I am pretty sure I also have an Nvidia graphics card in this laptop
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 20.2.1
- Kernel version: 5.9.3-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Antarctic-Ice-Shelf/b1c652a5e0fcfa661a7f463b45c9ff08
- Proton version: 5.13.2 and also 5.0.10

## I confirm:
- [Yes] that I haven't found an existing compatibility report for this game.
- [Yes] that I have checked whether there are updates for my system available.

## Symptoms 
Fallout: New Vegas instantly crashes to desktop on launch when run with Proton 5.13.2. When I run the game with `PROTON_LOG=1 %command%`, no log file is generated.

If I run the game in Proton 5.0.10, there is about a five second wait, after which the start menu pops up for a fraction of a second, before crashing to desktop. In version 5.0.10 I was able to produce the following log file: https://gist.github.com/Antarctic-Ice-Shelf/fcb3eed807f79c9461512755251ee0a4

The game wasn't working in Proton 5.13.1 either, but I don't remember whether the start menu popped up at all in that version.

The game was running fine in Proton 5.0.9.

I am also getting this same issue in a couple of other steam games, namely "The Elder Scrolls V: Skyrim Special Edition", and "The Elder Scrolls IV: Oblivion", which also ran fine in Proton 5.0.9.

## Reproduction
1) Install Fallout: New Vegas
2) Set in properties to force it to run with Proton 5.13.2 or with Proton 5.0.10
3) Run the game

**Comment by kisak-valve** [comment]
Hello @Antarctic-Ice-Shelf, in general, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #356, however, from your system information it's clear that you do not have a working vulkan driver right now. Please install the `vulkan-intel` and `lib32-vulkan-intel` packages and retest with Proton 5.0. You can look into tinkering with [PRIME render offload](https://wiki.archlinux.org/index.php/PRIME#PRIME_render_offload) and the nvidia driver later.

Separately, since Proton 5.13 didn't generate a log, that hints that you encountered an issue with Steam Linux Runtime - Soldier. If you completely close Steam, then run `steam` from a terminal, there should be a hint as to what went wrong in the terminal spew when you try to run a game with Proton 5.13.

**Comment by Antarctic-Ice-Shelf** [comment]
Okay, so I installed those two packages, and retested with Proton 5.0.10. Some good news on that front: Fallout:New Vegas managed to open, and the start menu appeared. I wasn't able to click on "Options", which caused a crash to desktop, and produced the following log: https://gist.github.com/Antarctic-Ice-Shelf/b5db5476e6c2bce909f84bd28a617a40

I was, however, able to click on "Play", and got the game to load. I did notice that the FPS was quite a lot lower than it used to be when I was using Proton 5.0.9.

I also tested Skyrim Special Edition with Proton 5.0.10, and that opened too, albeit also with much lower FPS.

Nevertheless, this is a great step in the right direction, so thanks!

As for Proton 5.13.2, Fallout:New Vegas still crashes with it, and doesn't produce a log. I opened Steam using the terminal and ran Fallout:New Vegas using Proton 5.13.2, and it produced the following terminal spew: https://gist.github.com/Antarctic-Ice-Shelf/9a690fe36d40b118edea6bad58da02e5

**Comment by Antarctic-Ice-Shelf** [comment]
Oh, and I went into the Manjaro Settings Manager and found that I have a GeForce MX250 GPU on my laptop, with the driver video-hybrid-intel-nvidia-440xx-prime. I am not sure if Steam is actually making use of that.

**Comment by kisak-valve** [comment]
We're juggling completely unrelated issues here, and that's bad for issue tracking in general.

For Proton 5.0-10, `wine: Unimplemented function atiadlxx.dll.ADL_Adapter_NumberOfAdapters_Get called at address 7B00DD67 (thread 00bc), starting debugger...` looks like the line of interest from the log. It's not surprising that the Intel GPU has different performance characteristics compared to the nVidia GPU if you had the game running with that before. Which GPU the game gets to use and why the nVidia Vulkan driver stack is broken is likely a system config issue. Please add your findings with Proton 5.0-10 to #356.

Then, completely separately, Pressure Vessel is failing to start Steam Linux Runtime - Soldier, which Proton 5.13 runs on top of. Pressure Vessel issues are being tracked in the [steam-runtime](https://github.com/ValveSoftware/steam-runtime/) issue tracker. Please open a new issue report on that issue tracker focusing on the failure to start Proton 5.13 on your system.
