### ISSUE TITLE
On proton 5.0-4 it works, but every 20-30 minutes it hangs tight. And I went through about half of the game, and before that there were no problems.

### ISSUE THREAD

**Issue by abinmansour** [ValveSoftware/Proton#4373]
On proton 5.0-4 it works, but every 20-30 minutes it hangs tight. And I went through about half of the game, and before that there were no problems.
At proton 5.13-1 the game starts but endless revolver drum when loading the main menu.

Mesa 20.2.2, rx 480
--------------------------------------------------

I do have the same issue here 

I can't run it neither on the proton-5.0-rdr2-4 nor the 5.13 ( nor its variants 5.13-1, 5.13-2, rc) 
Fedora 33 
Rx580 8gb
I7

_Originally posted by @rejedai in https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-726714253_

**Comment by kisak-valve** [comment]
Hello @abinmansour, we're using one issue report per unofficially supported game title. Your original comment was the best place to add feedback on Red Dead Redemption 2 being run with Proton.
