### ISSUE TITLE
GTA V Sign In Failed

### ISSUE THREAD

**Issue by wildcard-f8** [ValveSoftware/Proton#4378]
![Screenshot from 2020-11-14 16-50-06](https://user-images.githubusercontent.com/51791246/99162056-df69cb80-2733-11eb-98c0-78915648d698.png)

I've tried Proton versons 4.11-13, 5.0-10 and 5.13-2. The game was running fine yesterday but today it won't run. I've tried reinstalling it but I still get this error. I've looked around for a fix and it says to delete the Social Club folder from Documents, but I don't know where to find that in linux.

**Comment by kisak-valve** [comment]
Hello @wildcard-f8, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-727563142.
