### ISSUE TITLE
[BUG] Proton 5.13 ntdll.dll.so No such file or directory

### ISSUE THREAD

**Issue by dizcza** [ValveSoftware/Proton#4381]
Cannot run any .exe file due to the same error:
```
$ STEAM_COMPAT_DATA_PATH=~/.proton/ ~/.steam/steam/steamapps/common/Proton\ 5.13/proton run /path/to/exe
wine: failed to initialize: /home/vagrant/build-proton_5.13-local/dist-wine32/lib/wine/ntdll.dll.so: cannot open shared object file: No such file or directory
```
I'm trying to launch Fallout 3, but I get this error while running other windows executable files, therefore, I post it as a general issue with this release. Proton 5.0 does NOT have such an issue.
I have `wine-stable-amd64/bionic,now 5.0.2~bionic amd64` system-wide installed to launch other games of mine.
Lubuntu 18.04.

**Comment by aeikum** [comment]
Running Proton like that is not supported. You must launch it from the Steam client.

**Comment by dizcza** [comment]
@aeikum 
do you mean that protone command line API is not supported anymore? oO

**Comment by aeikum** [comment]
It never was. It depends on the Steam client to set a bunch of environment variables, and, in the case of 5.13, launch Proton inside the Steam Linux Runtime container.

**Comment by dizcza** [comment]
How the users are then supposed to deal with small issues like unable to install Microsoft .NET 3 that a game requires to install? I overcome this by running `proton run install.exe` manually for all exe files I want to install, skipping dnet 3 because (correct me if I'm wrong) it's already included in proton wine that won't be possible otherwise for games that install dependencies sequentially and quit on the first fail? What should I do then, open an issue here for each such game?
For example, this issue: https://github.com/ValveSoftware/Proton/issues/2951

**Comment by ghost** [comment]
> How the users are then supposed to deal with small issues like unable to install Microsoft .NET 3 that a game requires to install? I overcome this by running `proton run install.exe` manually for all exe files I want to install, skipping dnet 3 because (correct me if I'm wrong) it's already included in proton wine that won't be possible otherwise for games that install dependencies sequentially and quit on the first fail? What should I do then, open an issue here for each such game?
> For example, this issue: #2951

I've never seen this way you show above. Always done it by using eg "$ WINEPREFIX=prefix-of-the-game winetricks ..." and as long as there's a prefix, I would expect this should work.

Edit: Indeed, using 5.13, there's still a prefix created for a game in ...Steam/steamapps/compatdata/game_store_id/pfx so you should be able to install anything to that such as dotnet3.

**Comment by dizcza** [comment]
Then I googled the wrong usage of proton API.
I suppose, that winetricks is installed system-wide, and, in fact, I can use any wine command with a WINEPREFIX pointing to a steam compatdata drive folder like you mention, right?
In this case, you can close the issue.
Thank you.
