### ISSUE TITLE
Fallout 3 won't start (Proton 5.13)

### ISSUE THREAD

**Issue by dizcza** [ValveSoftware/Proton#4382]
# Compatibility Report
- Name of the game with compatibility issues: Fallout 3
- Steam AppID of the game: 22300

## System Information
- GPU: Intel HD Graphics (Iris 550)
- Driver/LLVM version: Intel Neo 20.22.16952
- Kernel version: 5.4.0-52-generic
- System info: [system_report.log](https://github.com/ValveSoftware/Proton/files/5549587/system_report.log)

- Proton version: 5.13

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-22300-proton4.11.log](https://github.com/ValveSoftware/Proton/files/5549572/steam-22300-proton4.11.log)
[steam-22300-proton5.13.log](https://github.com/ValveSoftware/Proton/files/5549573/steam-22300-proton5.13.log)

## Symptoms 
The game does not launch (shows Fallout 3 launcher for a moment and quickly disappears) with Proton 5.13 but does launch with Proton 4.11 (see the attached logs). The game does not start with Proton 5.0 either.

I bypassed d3d9.dll, as described here: https://www.youtube.com/watch?v=YYtX_NCDMe0

There is a similar [issue](https://github.com/ValveSoftware/Proton/issues/370), however, it's (1) for Fallout 3 GOTY and (2) outdated Proton version.

**Comment by kisak-valve** [comment]
Hello @dizcza, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2069#issuecomment-728337154.
