### ISSUE TITLE
SteamOS / Frostpunk

### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/Proton#4383]
# Compatibility Report
- Name of the game with compatibility issues: Frostpunk
- Steam AppID of the game: 323190

## System Information
- GPU:  GTX 1060
- Driver/LLVM version:  415.27
- Kernel version:  4.19
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Vladislavuz/3a43867547f4a00610debf77870cd3ac
- Proton version: 5.0-10b

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-323190.log](https://github.com/ValveSoftware/Proton/files/5551811/steam-323190.log)

## Symptoms 
The game doesn't start.

## Reproduction
Try to launch the game.

**Comment by kisak-valve** [comment]
Hello @Vladislavuz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/412#issuecomment-728861935.
