### ISSUE TITLE
Ryse: Son of Rome: Very Low FPS performance when launched from BPM (302510)

### ISSUE THREAD

**Issue by dragonfly-lover** [ValveSoftware/Proton#439]
I installed Ryse:Son of rome
On my hardware i expected at least 30fps. 
While the game runs pretty well in menus and intro, fps rate drops at 9-16 at minimum detail and constantly under 10fps (also stuttering for seconds) while playing.
textures seem ok with no glitches, shading problems or distortions. 
possibly could be whitelisted if only this problem was solved.

System informations:

Steam client version: 23/08/2018
Distribution: Ubuntu LTS 18.04
Opted into Steam client beta?: Yes
Have you checked for system updates?: Yes
CPU: AMD Ryzen5 1500
RAM: 8GB
Video Card: NVIDIA GTX750ti
Driver version: NVidia 396.54
Video memory: 2GB

**Comment by romulasry** [comment]
You might want to retry with a new Proton when they compile it with DXVK 0.70 and put it on Steam.

**Comment by romulasry** [comment]
Try the new beta, you can get it under Settings --> Steam Play --> Comparability Tool | Proton 3.7-4 Beta. See if that helps.

**Comment by dragonfly-lover** [comment]
Finally i verified that Ryse behaves very different if it starts from BPM or desktop mode. In desktop mode i get 25-30fps as expected (a bit low to be honest, but this game has never been considered so speedy).
Launched in BPM the fps fall down to less then 10 and some stuttering and freeze. i suspect there's something related with steam overlay.

Can't verify under proton 3.7.4 because i can't get it work (most games don't start until i revert back to 3.7.3).

**Comment by dragonfly-lover** [comment]
I verified that disabling steam overlay i don't get any result. Googling around i found this https://pcgamingwiki.com/wiki/Ryse:_Son_of_Rome#Low_FPS_issue . So It seems ryse doesn't ask for the best CPU Power available. I wonder if using something like feral gamemode il would find a workaround for this problem.

**Comment by dragonfly-lover** [comment]
After updgrading my card to a 1050ti 4gb i verifyied that not only Speed gets better (as was obvious) but also the difference beteween starting from BMP and normal mode falls to zero. This means that having 2gb of vram or less, the weight of vram consumed by BPM is so important that this games slows down to unplayable. So, this game under Proton requires at least 4gb vram.
