### ISSUE TITLE
Gas Guzzlers Extreme: random crashes

### ISSUE THREAD

**Issue by ranplayer** [ValveSoftware/Proton#4391]
# Compatibility Report
- Name of the game with compatibility issues: Gas Guzzlers Extreme
- Steam AppID of the game: 243800

## System Information
- GPU:GTX 970
- Driver/LLVM version: Nvidia 455.38
- Kernel version: 5.4
- Link to full system information report as [Gist](https://gist.github.com/): [steam-243800.tar.gz](https://github.com/ValveSoftware/Proton/files/5560197/steam-243800.tar.gz)

- Proton version: 5.0-10 | 5.13-2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game. ( I've found a different report about the steering wheel: [#1578](https://github.com/ValveSoftware/Proton/issues/1578)
- [X] that I have checked whether there are updates for my system available.

## Symptoms:
Game randomly crashes in both 32 and 64 bit mode. Sometimes you play for 2 hours without a crash, sometimes for a few minutes.

## Reproduction
1. Just play the game for a while in 32 or 64 bit mode.

**Comment by kisak-valve** [comment]
Hello @ranplayer, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1578#issuecomment-729676139.
