### ISSUE TITLE
Remember Me not run Proton 5.0.x and 5.11.xx

### ISSUE THREAD

**Issue by guglovich** [ValveSoftware/Proton#4396]
# Compatibility Report
- Name of the game with compatibility issues: Remember Me
- Steam AppID of the game: 228300

    GPU: AMD RX460
    Driver/LLVM version: Mesa 20.2.2-2, LLVM 11.0.0-1
    Kernel version: 5.9.8
    System information : https://gist.github.com/guglovich/40a7f0d65d21600c864dbe8c25581566
    Proton version: 5.0-10 and 5.13-2

I confirm:

    [+] that I haven't found an existing compatibility report for this game.
    [+] that I have checked whether there are updates for my system available.

## Symptoms 
The game does not run on both Proton 5 branches.

## Reproduction
100% repetition

**Comment by kisak-valve** [comment]
Hello @guglovich, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/145#issuecomment-729836991.
