### ISSUE TITLE
Fifa 21 not working on linux ubuntu

### ISSUE THREAD

**Issue by sudipta90** [ValveSoftware/Proton#4398]
I have tried to run fifa 21 on linux ubuntu 18.04.01. Every time it gets stuck at the very first step "thinorigin installation". Several times I saw origin's window pop up and being installed. However, whenever I try to play fifa 21 it tries to install origin and gets stuck at the first of the 9 steps. I am using the latest version of proton

**Comment by kisak-valve** [comment]
Hello @sudipta90, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4234#issuecomment-730014662.
