### ISSUE TITLE
Whitelist Request: Ghostrunner

### ISSUE THREAD

**Issue by bonkmaykr** [ValveSoftware/Proton#4403]
# Whitelist Request
- Name of the game to be whitelisted: Ghostrunner
- Steam AppID of the game: 1139900

## System Information
- GPU:  EVGA Geforce GTX 1060 3GB ACX 2.0
- Driver/LLVM version:  nvidia 450.80.02
- Distro version: Ubuntu 20.04
- [Link to full system information report as Gist.](https://gist.github.com/bonkmaykrQ/f94609f87c1ab47a067d39a65c9fd513)
- Proton version: 5.21 GE

## I confirm:
- [ Y ] that pressing the `Play` button in the Steam client is sufficient.
- [ N ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ Y ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [ Y ] I haven't experienced any issues.
- [ N ] There are no issues left open for this game.

https://youtu.be/5fkBsW-zLXk

**Comment by kisak-valve** [comment]
Hello @bonkmaykrQ, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4322#issuecomment-730743386. Also, third party Proton builds can not be used with the whitelist.
