### ISSUE TITLE
Spacelords: no terrain (436180)

### ISSUE THREAD

**Issue by rkfg** [ValveSoftware/Proton#441]
In the very first mission, "Short-Fused" the terrain almost always is not rendered appearing only in certain locations on the map. Other than that the game is fully playable and has great framerates.

![20180823232203_1](https://user-images.githubusercontent.com/184066/44607310-b11d1000-a7f8-11e8-9bad-754429c19d6b.jpg)

My specs: Intel Core i7-7700k, 32Gb RAM, NVIDIA GeForce 1070 GTX driver v396.54, Debian Buster GNU/Linux amd64, Awesome WM 3.5.6, kernel v4.17.12

**Comment by KibaGasteiz** [comment]
The game no longer has this problem for me, it must be something related to transform feedback or with nVidia drivers. The game works like native for me.
Distro:Antergos Linux
Kernel:4.19.4-arch1-1-ARCH
RAM:16 GB
GPU Driver:NVIDIA 415.22
GPU:NVIDIA GeForce GTX 1070
CPU:Intel Core i5-6600K @ 3.50GHz

**Comment by rkfg** [comment]
Great, I haven't played it for a long time and even uninstalled but might return back. Thanks!

**Comment by rkfg** [comment]
Can confirm, the terrain renders correctly now as of driver v410.78 and Proton 3.16-5 Beta.
