### ISSUE TITLE
Proton Doesn't Access External Drives 

### ISSUE THREAD

**Issue by IogaMaster** [ValveSoftware/Proton#4413]
Proton Doesn't Access External Drives

**Comment by kisak-valve** [comment]
Hello @Ioga-Master, you're going to need to be more clear than that. What exactly are you trying to do and with what Proton version?

**Comment by IogaMaster** [comment]
I'm trying to install a windows only game on an external drive. But The Latest Proton won't start them, the only way is to modify the fstab file but its to finicky.

**Comment by kisak-valve** [comment]
What game are you testing, and what filesystem are you using with the secondary drive? Please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by IogaMaster** [comment]
Any windows game on an external drive, I have tried to log and it doesn't generate a file. file system is exFAT

**Comment by kisak-valve** [comment]
Sounds like you've encountered #3835. Your problem is with Proton interacting with exFAT, not external drives in general. Please retest with a native linux filesystem.

**Comment by IogaMaster** [comment]
I reformatted the drive to Ext4 and it worked. Thanks for your help.
