### ISSUE TITLE
Elite Dangerous (Exception initializing application)

### ISSUE THREAD

**Issue by daxime** [ValveSoftware/Proton#4415]
# Compatibility Report
- Name of the game with compatibility issues: Elite Dangerous
- Steam AppID of the game:359320

## System Information
- GPU: Radeon HD7850
- Driver/LLVM version: Mesa 20.3.0-rc2 / LLVM 11.0.0
- Kernel version: 5.4.0-54-generic
- Link to full system information: https://gist.github.com/daxime/f1cd1b0e488e8985e0994949006d432a
- Proton version: 5.13-2 ; 5.0-10

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.
[steam-359320.log](https://github.com/ValveSoftware/Proton/files/5593916/steam-359320.log)

## Symptoms
It's been 3-4 days since I've been trying to launch Elite Dangerous (which worked very well). But now I have an error window:

Exception initializing application:
Could not find a part of the path 'C:\users\steamuser\Local Settings\Application Data\Elite Dangerous Launcher_evidencehere'.

I tried with Proton 5.13-2 and 5.0-10. I also deleted the folder "359320" in "compatdata". Still nothing same problem...

## Reproduction
Just launch the game

**Comment by kisak-valve** [comment]
Hello @daxime, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/150#issuecomment-733417698.
