### ISSUE TITLE
game crash after finish the last mission 

### ISSUE THREAD

**Issue by SimpleMindedGuy** [ValveSoftware/Proton#4416]
OS: Arch Linux x86_64 
Kernel: 5.9.10-arch1-1
CPU: AMD Ryzen 3 3200G (4) @ 3.600GHz
GPU: AMD ATI Radeon RX 580
Memory: 16 GB
proton : 5.13-2

i finish the last mission of the game and after the game saved it crashed while in a loading screen 

and now every time i launch the game i get to the "press any key" screen 
i press something 
then i get a menu pop up for 1 sec 
and my game crashes

**Comment by kisak-valve** [comment]
Hello @Darkx97, please clarify which game you're seeing an issue with. Also, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, then reproduce the issue and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by SimpleMindedGuy** [comment]
my bad

the game is monster hunter world 

i tired uploading the file but its 50 mb and i dont know how to upload that

**Comment by kisak-valve** [comment]
From the discussion on #175, we know that the end game has a video which uses Media Foundation, and general support for that framework needs to mature in wine and Proton.

In general, we're using one issue per unofficially supported game title, so feel free to add any other feedback related to Monster Hunter World to #175. This particular issue is fairly well understood.

Closing in favor of #175.

**Comment by SimpleMindedGuy** [comment]
im sry but i still didnt find any solution for the problem where
