### ISSUE TITLE
Men of war

### ISSUE THREAD

**Issue by igorriok** [ValveSoftware/Proton#4417]
# Compatibility Report
- Name of the game with compatibility issues: Men of War: Assault Squad 2
- Steam AppID of the game: 244450

## System Information
- GPU: RX 5500 XT
- Driver/LLVM version: Mesa 18.2/7.0.0
- Kernel version: 5.4
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/igorriok/2274a8a74cded369e2a5d5b35cf0a9be
- Proton version: 5.13-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-244450.log](https://github.com/ValveSoftware/Proton/files/5597571/steam-244450.log)

## Symptoms 
When try to save or load game get error and game exits.

## Reproduction
Save or load game

**Comment by kisak-valve** [comment]
Hello @igorriok, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/626#issuecomment-733787475.
