### ISSUE TITLE
Steam DXVK games can't be run on AMD Vulkan Driver from Proton 5.13-2

### ISSUE THREAD

**Issue by Kai-AMD** [ValveSoftware/Proton#4420]
# Compatibility Report
- Name of the game with compatibility issues: Wolfenstein II, Witcher3, Strange Brigade and ...
- Steam AppID of the game: 612880, 292030, 312670 and ...

## System Information
- GPU: All AMD GPUs Supported
- Driver: AMDGPU-PRO 20.45 or open source AMDVLK v-2020.Q4.5 (Not Mesa/Radv)
- Kernel version: All Linux Kernel Supported
- Full system information: Ubuntu 20.04 + Kernel 5.4.0-53-generic
- Proton version: 5.13-2

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

## Symptoms 
DXVK games crash with 5.13-2, but pass with 5.0-10.

Crash info:
(1) Something regarding libGL error
(2) Something regarding VK_ERROR_EXTENSION_NOT_PRESENT error

The reason maybe OpenGL/Vulkan libraries (Loader and ICD) in /opt can NOT be accessed in game:

/opt/amdgpu-pro/lib/x86_64-linux-gnu/libGL.so.1.2
/opt/amdgpu-pro/lib/x86_64-linux-gnu/libGL.so -> libGL.so.1.2
/opt/amdgpu-pro/lib/x86_64-linux-gnu/libGL.so.1 -> libGL.so.1.2
/usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so
/opt/amdgpu/lib/x86_64-linux-gnu/dri/amdgpu_dri.so -> /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so

/usr/lib/x86_64-linux-gnu/libvulkan.so.1.2.148
/usr/lib/x86_64-linux-gnu/libvulkan.so -> libvulkan.so.1
/usr/lib/x86_64-linux-gnu/libvulkan.so.1 -> libvulkan.so.1.2.148
/opt/amdgpu-pro/lib/x86_64-linux-gnu/amdvlk64.so

Issue can be workarounded by following steps:
(1) Add “PROTON_DUMP_DEBUG_COMMANDS=1 %command%” in the launch options
(2) Run game to generate a file called "run" at /tmp/proton_root
(3) Run with command “/tmp/proton_root/run”

Issue can also be workarounded by:
(1) Change the "library_path" in json file of AMD Vulkan ICD from "/opt/amdgpu-pro/lib/x86_64-linux-gnu/amdvlk64.so" to "/usr/lib/x86_64-linux-gnu/amdvlk64.so".
(2) Copy amdvlk64.so from /opt/amdgpu-pro/lib/x86_64-linux-gnu/ to /usr/lib/x86_64-linux-gnu/, then launch steam games.

## Reproduction
(1) Install Ubuntu 20.04 64 bit OS
(2) Install AMDGPU-PRO 20.45 or set up open source AMDVLK v-2020.Q4.5
(3) Run DXVK steam games and see the crash

**Comment by kisak-valve** [comment]
Hello @Kai-AMD, this issue is already being tracked at #4288 and https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/29. It should be fixed by the [Steam Linux Runtime - Soldier 0.20201124.0](https://steamcommunity.com/app/221410/discussions/2/2962768718547168164/) update.

If switching to the `client_beta` beta branch of `Steam Linux Runtine - Soldier` in Steam doesn't improve the situation, then please let me know and we can look at this issue further.

**Comment by Kai-AMD** [comment]
Hi @kisak-valve, by updating Steam Linux Runtime - Soldier to 0.20201124.0, the issue can still be reproduced.

**Comment by Kai-AMD** [comment]
Hi @kisak-valve, by updating Steam Linux Runtime - Soldier to 0.20201124.0, the issue can still be reproduced.
