### ISSUE TITLE
The Elder Scrolls Online(306130) doesn't start at all on NTFS

### ISSUE THREAD

**Issue by RodolpheGohard** [ValveSoftware/Proton#4426]
# Compatibility Report
- Name of the game with compatibility issues: The elder Scrolls online
- Steam AppID of the game: 306130

## System Information
- GPU: 1660 super
- Driver/LLVM version: 
- Kernel version: 5.8.0
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/RodolpheGohard/c3b1bfa449ce4c3994598df81b79d513
- Proton version: Proton 5.13

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

add `PROTON_LOG=1 %command%`: **I did and no log file is not generated**

## Symptoms 
I click 'Play'. Nothing happens, 3 seconds later, the button comes back from "Cancel"(running) to "Play"

## Reproduction
I just installed the game from steam, it never ran

## Additionnal information
- Manually running wine eso64.exe launches the game, but I can't login, It says I should open the game through Steam
- Manually running wine zosSteamStarter.exe opens the launcher, but it's stuck at "loading"
- I tried Proton 3 runtime, Proton 4 runtime, same
- setting a variety of launch options (combinations of PROTON_USE_WINED3D11=1, PROTON_NO_ESYNC=1 mesa_glthread=true vblank_mode=0) doesn't change a thing
- I lacked free storage (TESO is greedy, 90 GB required) on my ext4 ubuntu partition, so I added a new library location on my HDD drive, which is NFTS
- **running from a terminal "PROTON_NO_ESYNC=1 mesa_glthread=true vblank_mode=0 STEAM_COMPAT_DATA_PATH=/media/rodolphe/HDD/games/steamapps/compatdata/306130 /home/rodolphe/.local/share/Steam/steamapps/common/Proton\ 5.13/proton run /media/rodolphe/HDD/games/steamapps/common/Zenimax\ Online/The\ Elder\ Scrolls\ Online/game/client/eso64.exe" yields the following**:
```
wineserver: using server-side synchronization.
wine: could not open working directory L"unix\\home\\rodolphe\\", starting in the Windows directory.
wine: could not open working directory L"unix\\home\\rodolphe\\", starting in the Windows directory.
wine: Unhandled page fault on read access to 0000000000000012 at address 000000014138FDA6 (thread 0040), starting debugger...

```
- Edit: I ran this same installation in windows Steam (by adding the folder in games library) and it updates and runs without any issues, So the install seems OK

**Comment by intelligentgaming** [comment]
"I lacked free storage (TESO is greedy, 90 GB required) on my ext4 ubuntu partition, so I added a new library location on my HDD drive, which is NFTS"

This is likely your issue, as you are playing the game on NTFS, although it is possible to get Proton to work with NTFS, this is not recommended, so try installing the game on EXT4 and seeing if that resolves your problem.

**Comment by kisak-valve** [comment]
Hello @RodolpheGohard, in general, we're using one issue report per unofficially supported game title. Usually I'd transfer this issue report to #556, however, the symptoms you've described sounds like the known finicky behavior Proton has when used with NTFS and is most likely not game specific.

You might have some luck with https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows. You may also find some workarounds to try in [various similar issue reports](https://github.com/ValveSoftware/Proton/search?q=ntfs+launch&type=issues).

**Comment by RodolpheGohard** [comment]
I copied the whole library folder to an ext4 drive, changed the library in steam. The issue still persist with steam or command line:

```
PROTON_NO_ESYNC=1 mesa_glthread=true vblank_mode=0 STEAM_COMPAT_DATA_PATH=/media/rodolphe/ext4storage/games/steamapps/compatdata.bak/306130 /home/rodolphe/.local/share/Steam/steamapps/common/Proton\ 5.13/proton run /media/rodolphe/ext4storage/games/steamapps/common/Zenimax\ Online/zosSteamStarter.exe 
wineserver: using server-side synchronization.
wine: could not open working directory L"unix\\home\\rodolphe\\", starting in the Windows directory.
wine: could not open working directory L"unix\\home\\rodolphe\\", starting in the Windows directory.
```

```
PROTON_NO_ESYNC=1 mesa_glthread=true vblank_mode=0 STEAM_COMPAT_DATA_PATH=/media/rodolphe/ext4storage/games/steamapps/compatdata.bak/306130 /home/rodolphe/.local/share/Steam/steamapps/common/Proton\ 5.13/proton run /media/rodolphe/ext4storage/games/steamapps/common/Zenimax\ Online/The\ Elder\ Scrolls\ Online/game/client/eso64.exe 
wineserver: using server-side synchronization.
wine: could not open working directory L"unix\\home\\rodolphe\\", starting in the Windows directory.
wine: could not open working directory L"unix\\home\\rodolphe\\", starting in the Windows directory.
wine: Unhandled page fault on read access to 0000000000000012 at address 000000014138FDA6 (thread 0040), starting debugger...
```

**Comment by RodolpheGohard** [comment]
Update: I deleted the old compat data, now the launcher opens, I can run the game, Log in, but but it freezes about 20seconds after launch. I'll continue my digging ...

**Comment by kisak-valve** [comment]
Glad to hear you made progress. I expect the issue you've encountered is the same as what's already being tracked in various issue reports like #11.

Please use #556 for further discussion of Elder Scrolls Online when run with Proton.

**Comment by saulopz** [comment]
Well, I see that is not just me that problem. I'm trying hardly, but nothing yet. http://saulo.arisa.com.br/eso/

I've tried to talk to the steam and proton folks on forums and discord, but they always send me the same links and seem to ignore the problem even though I saw several people as the same problem. I feel a little abandoned by steam and proton.

Well, let's continue to trying... Good luck!

**Comment by RodolpheGohard** [comment]
> Well, I see that is not just me that problem. I'm trying hardly, but nothing yet. http://saulo.arisa.com.br/eso/
> 
> I've tried to talk to the steam and proton folks on forums and discord, but they always send me the same links and seem to ignore the problem even though I saw several people as the same problem. I feel a little abandoned by steam and proton.
> 
> Well, let's continue to trying... Good luck!

My issue was related to the game and compatdata folder being on an NTFS drive, are you also trying an install on an NTFS drive ?

**Comment by saulopz** [comment]
> > Well, I see that is not just me that problem. I'm trying hardly, but nothing yet. http://saulo.arisa.com.br/eso/
> > I've tried to talk to the steam and proton folks on forums and discord, but they always send me the same links and seem to ignore the problem even though I saw several people as the same problem. I feel a little abandoned by steam and proton.
> > Well, let's continue to trying... Good luck!
> 
> My issue was related to the game and compatdata folder being on an NTFS drive, are you also trying an install on an NTFS drive ?

No, I have no NTFS partition, but EXT4. But I have same problem and I did see other users with this problem too.

**Comment by RodolpheGohard** [comment]
> > > Well, I see that is not just me that problem. I'm trying hardly, but nothing yet. http://saulo.arisa.com.br/eso/
> > > I've tried to talk to the steam and proton folks on forums and discord, but they always send me the same links and seem to ignore the problem even though I saw several people as the same problem. I feel a little abandoned by steam and proton.
> > > Well, let's continue to trying... Good luck!
> > 
> > 
> > My issue was related to the game and compatdata folder being on an NTFS drive, are you also trying an install on an NTFS drive ?
> 
> No, I have no NTFS partition, but EXT4. But I have same problem and I did see other users with this problem too.

If your issue is not related to NTFS, you're posting in the wrong thread. You shoulf find an issue related to yours or create a new one if it's not reporterd
