### ISSUE TITLE
Halo: The Master Chief Collection - Fatal Error

### ISSUE THREAD

**Issue by Richard-Payne** [ValveSoftware/Proton#4427]
# Compatibility Report
- Title Halo: The Master Chief Collection
- Steam AppID of the game: 976730

## System Information
- GPU: NVidia GeForce GTX 1060
- Driver/LLVM version: 455.45.01
- Kernel version: 5.8.18-1-MANJARO
- https://gist.github.com/Richard-Payne/2862f289aa31cbdcf96de650a12c3f5f
- Proton version: 5.13-2 and 5.21-GE-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-976730.log](https://github.com/ValveSoftware/Proton/files/5618216/steam-976730.log)

## Symptoms 
Splash screen loads, disappears and then a Fatal Error Windows dialog appears.  Screenshot attached.
![Screenshot_20201130_185904](https://user-images.githubusercontent.com/6730730/100652044-44c9d900-333e-11eb-8333-4a0be78a77b8.png)

**Comment by kisak-valve** [comment]
Hello @Richard-Payne, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2907#issuecomment-735991854.
