### ISSUE TITLE
Build-process for releases

### ISSUE THREAD

**Issue by LeonFretter** [ValveSoftware/Proton#4428]
In your README you explain the process of building proton from source.
The problem is that this process seems to require the proton-directory to be a git-repository, i.e. contain a .git subdirectory (The makefile-script seems to require it, and you also mention to "update the git-submodules").
The releases however don't contain the .git-folder (aren't git-repositories)

It would be helpful if you could add a section to the README that explains how to build these releases since the steps in your current README don't apply exactly to building one of your releases.

**Comment by RarogCmex** [comment]
git init .

**Comment by aeikum** [comment]
The README starts with `git clone` instructions. I do the releases because some users requested it. I think it gives them github notifications or something. Anyway yes, you'll need to clone it from the GH repo.

**Comment by LeonFretter** [comment]
With a plain `git init .` which @RarogCmex recommended, the submodules couldn't be handled, right?
Okay, so the recommended procedure is not to download a release, but rather rollback the cloned git-repository to the version desired, or switch the branch to the appropriate version, is this correct? 
Maybe a short note about this in the README would be helpful then, because I think if one wants to obtain a certain version, but not tinker with, or commit to the git-repository oneself, downloading a release comes to mind first - I know the README talks about the procedure of cloning the git-repository, but maybe there should be a warning about the releases.
Anyway, thanks for the help!

**Comment by aeikum** [comment]
> Okay, so the recommended procedure is not to download a release, but rather rollback the cloned git-repository to the version desired, or switch the branch to the appropriate version, is this correct?

Yes.

> Maybe a short note about this in the README would be helpful then

It's not a bad idea. Does this diff seem sufficient to you?

```diff
diff --git a/README.md b/README.md
index 7ba6b3d..2c6a361 100644
--- a/README.md
+++ b/README.md
@@ -29,10 +29,11 @@ or guarantee that anyone will help you with this process.
 
 We strongly recommend that most users use the production build of Proton.
 
-The most current source for Proton is here:
-  <https://github.com/ValveSoftware/Proton>
+Acquire Proton's source by cloning <https://github.com/ValveSoftware/Proton>
+and checking out the branch you desire. Be sure to update submodules when
+switching branches.
 
-Which you can clone to your system with this command:
+You can clone the latest Proton to your system with this command:
 
         git clone --recurse-submodules https://github.com/ValveSoftware/Proton.git proton
         cd proton
```

**Comment by LeonFretter** [comment]
> > Okay, so the recommended procedure is not to download a release, but rather rollback the cloned git-repository to the version desired, or switch the branch to the appropriate version, is this correct?
> 
> Yes.
> 
> > Maybe a short note about this in the README would be helpful then
> 
> It's not a bad idea. Does this diff seem sufficient to you?
> 
> ```diff
> diff --git a/README.md b/README.md
> index 7ba6b3d..2c6a361 100644
> --- a/README.md
> +++ b/README.md
> @@ -29,10 +29,11 @@ or guarantee that anyone will help you with this process.
>  
>  We strongly recommend that most users use the production build of Proton.
>  
> -The most current source for Proton is here:
> -  <https://github.com/ValveSoftware/Proton>
> +Acquire Proton's source by cloning <https://github.com/ValveSoftware/Proton>
> +and checking out the branch you desire. Be sure to update submodules when
> +switching branches.
>  
> -Which you can clone to your system with this command:
> +You can clone the latest Proton to your system with this command:
>  
>          git clone --recurse-submodules https://github.com/ValveSoftware/Proton.git proton
>          cd proton
> ```

I personally would go for a version that explicitly tells the reader not to use the releases, but that's just my own opinion.
Apart from that this can be closed I think :) thanks again!

**Comment by aeikum** [comment]
I put in the more clarifying language as 8d44166b16d119d100b29a68b453fb99fb0d6275. I don't want to refer specifically to GH releases, that seems like an implementation detail that doesn't belong in the docs.
