### ISSUE TITLE
Budget Cuts Audio Issues

### ISSUE THREAD

**Issue by zefrof** [ValveSoftware/Proton#4432]
# Compatibility Report
- Name of the game with compatibility issues: Budget Cuts 
- Steam AppID of the game: 400940

## System Information
- GPU: RX 5700XT
- Driver/LLVM version: Mesa 20.0.8/LLVM 10.0.0
- Kernel version: 5.8.0-7630-generic
- Link to full system information report as [Gist](https://gist.github.com/zefrof/c2eb55119fbf97c0b77e35fd4f3685d1):
- Proton version: 5.13-2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Issue Report
[steam-400940.log](https://github.com/ValveSoftware/Proton/files/5639116/steam-400940.log)

## Symptoms
When playing Budget Cuts (tried The Lab as well) there's a constant crackling sound coming from both speakers. The crackling goes away when using an older version of Proton (5.0-10 doesn't have audio issues). Native games also don't have any audio crackling. Leading me to believe it's an issue with Proton 5.13-2.

Of note, the audio works fine until step 3 below. Once the audio starts crackling though it doesn't stop until I reboot SteamVR. 

## Reproduction
1) Launch SteamVR.
2) Swap audio output source to VR headset.
3) Launch Budget Cuts from SteamVR home.

**Comment by kisak-valve** [comment]
Hello @zefrof, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3437#issuecomment-738346116.

**Comment by zefrof** [comment]
Sorry, I didn't see/know that. Thank you for moving it!
