### ISSUE TITLE
Unable to alt+tab away and back, aka Xorg focus view

### ISSUE THREAD

**Issue by kaihendry** [ValveSoftware/Proton#4443]
# Compatibility Report
- Company of Heroes 2
- [231430](https://www.protondb.com/app/231430)

## System Information
- GPU: AMD Ryzen 7 PRO 4750U with Radeon Graphics
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 20.2.3 (git-8440307a61)
- Kernel version: 5.9.12-arch1-1
- https://gist.github.com/kaihendry/ad8411e7287c1f296b120443694960f6
- Proton version: 5.0-10 https://s.natalian.org/2020-12-08/coh2-proton.png

Btw Neither Proton 5.13-3 or the Steam Linux Runtime is able to launch this game. It does have a Linux port 5.x, but I need to run under Proton to play multiplier online. :/ 

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

https://s.natalian.org/2020-12-08/steam-231430.log

## Symptoms 

When I Alt-Tab aka change views in my Xorg environment, I can't switch back to the game.

<img src="https://s.natalian.org/2020-12-08/1607401226_1918x1047.png">

## Reproduction

Launch and Alt-Tab twice

**Comment by kisak-valve** [comment]
Hello @kaihendry, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3875#issuecomment-740590827.
