### ISSUE TITLE
Doom 2016 (379720) uses Proton 3.16 by default

### ISSUE THREAD

**Issue by Lastique** [ValveSoftware/Proton#4446]
When I start Doom 2016 (appid: 379720), it is always using Proton 3.16 to run, even if a newer version is installed and selected in Steam Play settings as the default. If Proton 3.16 is not installed, it is downloaded first.

This happens when "Force the use of a specific Steam Play compatibility tool" is not enabled in Doom 2016 properties. When I enable it and select a different Proton version, then that manually selected version is used.

Doom 2016 runs well with the recent Proton versions (5.0, 5.13), there is no reason to lock it to Proton 3.16 by default. Please, remove that association and make it use the globally configured Proton version by default.

**Comment by kisak-valve** [comment]
Hello @Lastique, the order preference for which Proton version a game should use is Per-game compatibility tool override > whilelisted Proton version > Global compatibilty tool setting.

There are [some requests](https://github.com/ValveSoftware/Proton/issues?q=is%3Aopen+is%3Aissue+label%3A%22Whitelist+Update+Request%22+379720) for the game to be bumped to a newer Proton version in the whitelist, but you're requesting that the game be dropped from the whitelist entirely, and this is not a valid reason to do so.

**Comment by Lastique** [comment]
@kisak-valve If you read those requests, you will notice that the problem reports mentioned there are fixed in the newer Proton versions. In fact, when I'm running the game with Proton 3.16 it doesn't go into fullscreen mode and stays in the background, which does not happen with 5.0 and 5.13.

So I see no reason to keep this game attached to Proton 3.16. I suppose, you could change the whitelist to allow a newer Proton version (which would still be better than the status quo), but I'm also not seeing why it should be in a whitelist in the first place. The game just works fine nowdays with any recent Proton.

If I'm missing something and the game absolutely must stay using a whitelist, please consider this a request to whitelist the recent Proton versions (5.0, 5.13) for this game.
