### ISSUE TITLE
Conan Exiles does not work with 5.13

### ISSUE THREAD

**Issue by ThomasLocke** [ValveSoftware/Proton#4447]
# Compatibility Report
- Name of the game with compatibility issues: Conan Exiles
- Steam AppID of the game: 440900

## System Information
- GPU: AMD Radeon RX 480 Graphics (POLARIS10, DRM 3.35.0, 5.4.0-56-generic, LLVM 11.0.0)
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 20.3.0 - kisak-mesa PPA
- Kernel version: 5.4.0-56-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ThomasLocke/478189dbcf4792b1d4a6a991a19cb490
- Proton version: 5.13-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
You can start the game, but not actually play the game. Trying to either start a new singleplayer game or continue an existing one results in the game hanging at a load screen.

This only happens with 5.13-x whereas 5.0-10 works fine.

## Reproduction
Start the game and then attempt to actually play a singleplayer game.

## steam-440900.log
https://gist.github.com/ThomasLocke/94e2890ddd5ba2de6842c550630d14f7

**Comment by kisak-valve** [comment]
Hello @ThomasLocke, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2563#issuecomment-740779934.
