### ISSUE TITLE
A vulkan check on the device

### ISSUE THREAD

**Issue by nda-cunh** [ValveSoftware/Proton#4449]
# Feature Request

## Description 
vulkan is not yet everywhere, and DXVK crashes games if you don't have it. just checked if vulkan exists otherwise use wined3d.
## Justification

we test if vulkan is present on the PC and that it works, if vulkan is not on the machine we activate PROTON_USE_WINED3D=1

because many users do not have vulkan and vulkan crashes the game while it can work with wined3d.

this would add ease of use without losing anything!

so many games on PROTONDB.com are rated OR because users add the mention (WINED3D=1 if your game dont work) which means that with my suggestion a lot of OR programs could become platinum

**Comment by kisak-valve** [comment]
Hello @hydrasho, this request was previously evaluated at #1749 and concluded with https://github.com/ValveSoftware/Proton/pull/1749#issuecomment-489606572 and https://github.com/ValveSoftware/Proton/pull/1749#issuecomment-489618385.
