### ISSUE TITLE
Cyberpunk 2077: AMD GPU and Mesa Git crashing after CDPR logo

### ISSUE THREAD

**Issue by lostpolaris** [ValveSoftware/Proton#4451]
Crashes graphics with RX5700 and mesa-git after logo

_Originally posted by @xDShot in https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-742647420_

**Comment by lostpolaris** [comment]
A separate thread for users with AMD GPUs who get graphics stack crashes after seeing the CDPR Logo.

**Comment by TheChriZ** [comment]
I also have this Problem with Proton 5.13-4 and Proton GE 5.22. I got into the game using tkg proton 6.0, but i have flickering textures in the character creation.

**Comment by xDShot** [comment]
Should probably just add emoji to the comment

**Comment by kisak-valve** [comment]
Hello @BobRawr101, we're using one issue report per unoffically supported game title, and this game is being tracked at #4450. Beyond that, driver-specific issues should be reported to the video driver vendor, and this sounds like https://gitlab.freedesktop.org/mesa/mesa/-/issues/3960. Closing as a duplicate.
