### ISSUE TITLE
Experimental 5.13 issues/regressions

### ISSUE THREAD

**Issue by tim77** [ValveSoftware/Proton#4452]
Hi. Found some noticeable issues and regressions in new https://github.com/ValveSoftware/Proton/commit/04e9b36c78ff7021c2187fb6bca63c395e805cce Experimental 5.13 Proton version. Self compiled build. No such regressions in current stable Proton 5.13.

- Tomb Raider 2: The Dagger Of Xian (Unreal Engine 4)
http://tombraider-dox.com/downloads/
  - Experimental
![Снимок экрана от 2020-12-11 01-34-09](https://user-images.githubusercontent.com/5614476/101849432-568e5600-3b60-11eb-87e3-902c7d03b4ac.png)
  - Stable
![Снимок экрана от 2020-12-11 01-33-08](https://user-images.githubusercontent.com/5614476/101849492-7291f780-3b60-11eb-95cb-fa4e3b449835.png)

- Elemental Demo (Unreal Engine 4)
https://www.unrealengine.com/marketplace/en-US/learn/elemental-demo
![Снимок экрана от 2020-12-11 02-06-39](https://user-images.githubusercontent.com/5614476/101849755-06fc5a00-3b61-11eb-9e1c-bd2a2a5cd100.png)

In same time there one game which found that run better with new Experimental Proton - Baldur’s Gate III. No game crash when Alt+TAB'ing when the game is running:
![Снимок экрана от 2020-12-11 01-48-39-2](https://user-images.githubusercontent.com/5614476/101850030-9bff5300-3b61-11eb-9b72-07b605754b53.png)

**Comment by tim77** [comment]
DXVK/vkd3d was missed for some reason. No issues with Tomb Raider 2: The Dagger Of Xian and Elemental Demo. And improvement in windows managing and Baldur’s Gate III in particular.

**Comment by aeikum** [comment]
For the record, we are definitely interested to know about problems you find that are exclusive to the Experimental branch. Thanks for reporting these issues, even though this turned out to be a false positive.
