### ISSUE TITLE
Cyberpunk 2077 screen freezing afther cutscene

### ISSUE THREAD

**Issue by BoomWortel** [ValveSoftware/Proton#4455]
# Compatibility Report
Cyberpunk 2077
- Steam AppID of the game: ルーク

## System Information
- GPU: RTX 2060
- Driver/LLVM version: Nvidia 455.38
- Kernel version: 5.8.0-7630-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.13
- Proton version: Proton-5.21-GE-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

**Comment by McMarius11** [comment]
Hello @BoomWortel, your thread is a duplicate.
your using the wrong proton version and you have an old nvidia driver. Please do your homework and close this thread

**Comment by kisak-valve** [comment]
Hello @BoomWortel, we're using one issue per unofficially supported game title. Feel free to discuss your experience with this game on #4450. In general, the game is not expected to work reliably on the currently available nVidia drivers.

Closing in favor of #4450.
