### ISSUE TITLE
use existing inst

### ISSUE THREAD

**Issue by alexzk1** [ValveSoftware/Proton#4463]
# Feature Request

well, some games ( i did all for elite dangerous) - have own launcher, which binds to steam etc. so no online probs.
but sometimes cool stuff happens - like those 2 launchers (steam & game) start update each other ...
..u do wine copy ..and play for a year...then ssl for .net gets broken
...,and u reverse to steam 
(my true story)
...but all those changes - they keep download copies

so...what i ask - any pop window - give it a path - and is it uses/checks/whatever - instead download copy.
i would like to have some separtaed tool like
> ihavecopy at ./some
and then both proton & wine get hey should check that folder prior start plain download.

yes it can be manually done etc, but problem/request is to automate it to 1 line. so i can just add it to linux launch script.

**Comment by kisak-valve** [comment]
Hello @alexzk1, Proton does not manage downloading and updating game content at all. As for Steam, it is capable of detecting existing game content when you install the game, however, that would always compare to what's available on Steam servers and can't know what a third party launcher/updater changed over time.

Running a game with both Steam for Linux and Proton and with system installed wine might work by luck, but is generally not supported.

**Comment by alexzk1** [comment]
> Hello @alexzk1, Proton does not manage downloading and updating game content at all. As for Steam, it is capable of detecting existing game content when you install the game, however, that would always compare to what's available on Steam servers and can't know what a third party launcher/updater changed over time.
> 
> Running a game with both Steam for Linux and Proton and with system installed wine might work by luck, but is generally not supported.

I understand this in general, but I don't think "i have a copy" from user side is on steam. 
And well, u can push harder steam then me.


this one idea is not final - it must be re-thinked.
but final is - if i have 2 copies - i need a way to supply path to avoid 2nd copy DOWNLOAD

**Comment by alexzk1** [comment]
ye..maybe from programming view it should go to upper levers like steam

...but just think, who goes there? I don't
i work on terms proton.wine
maybe u could do a tool? which launched will handle things and force steam to "know" new path?

**Comment by alexzk1** [comment]
or just paste to steam guys as they listen u more then me. they could do option

**Comment by alexzk1** [comment]
but steam guys will have 2 copies for sure...from their level

**Comment by alexzk1** [comment]
i want to  avoid to have 2 copies

**Comment by alexzk1** [comment]
so it is ur level, when user says
"1copy ./thisfolder"
and then steam updates whatever he wants based on content

**Comment by alexzk1** [comment]
..and then i need console..

..any way, i'm sure I wrote to proper guys - start discuss that with steam guys.
what i ask - avoid download if i already have 1 by game launcher etc.
it should pick & use in 1 click instead what i build links here

**Comment by kisak-valve** [comment]
To reiterate, you can already copy game content into `<Steam Library folder>/common/<game folder>` and when you tell Steam to install the game, it will detect the existing game content and only download what's missing or changed, however, what Steam has available for the game can be extremely different from what the third party launcher/updater has changed since the game was last updated on Steam.

Giving users the option to install a game without downloading or verifying game content at all sounds like an anti-feature and will cause more trouble than it solves.
