### ISSUE TITLE
Rocket League crash on discrete graphics

### ISSUE THREAD

**Issue by nuno1212s** [ValveSoftware/Proton#4465]
# Compatibility Report
- Name of the game with compatibility issues: Rocket League
- Steam AppID of the game:252950

## System Information
- GPU:GTX 1660 Ti (Notebook) + Radeon RX Vega 7
- Driver/LLVM version: Nvidia 455.38
- Kernel version: 5.8.0-7630-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/nuno1212s/5f926ea532435f80f96d0f3797083098
- Proton version: 5.10, 5.13-4, Proton Experimental were tested, none worked.

## I confirm:
- [ X] that I have checked whether there are updates for my system available.

## Symptoms 
The game starts and runs when running the hybrid graphics mode however it starts using the integrated graphics card. When I boot linux in discrete graphics mode, the game opens a black window followed by a black screen and then crashes a few seconds later, without any output to the display.

## Reproduction
Boot PC in NVidia graphics mode, try to open game, game closes.

**Comment by kisak-valve** [comment]
Hello @nuno1212s, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3521#issuecomment-743925997.
