### ISSUE TITLE
Visual Particle Artifacts

### ISSUE THREAD

**Issue by LuxLucian** [ValveSoftware/Proton#4468]
# Compatibility Report
- Name of the game with compatibility issues: DOOM ETERNAL
- Steam AppID of the game:782330

## System Information
- GPU: 5700 XT
- Driver/LLVM version: <amdgpu / mesa 20.3.0-3>
- Kernel version: <Linux 5.9.13-arch1-1 x86_64>
- https://gist.github.com/LuxLucian/5ef4f74d643f6a15095ad6a846f9bdf1
- Proton version: 5.13-4

## I confirm:
- [ Y ] that I haven't found an existing compatibility report for this game.
- [ Y ] that I have checked whether there are updates for my system available.

## Symptoms 
The mega link is for the steam log.
https://mega.nz/file/xYMHAYDD#wzBl_k03oHgYgVo72mneTmandYpmrK-jjn45gF0RCk4
Certain particles glow a rainbow color. Rain and some fire effects do this, including blood in specific areas of the game. I have seen the other report mentioning this issue but wasn't able to make sense of it.
![Screen](https://user-images.githubusercontent.com/63475999/102021372-96aa3000-3d3c-11eb-9361-4fe73ee47287.png)

**Comment by kisak-valve** [comment]
Hello @LuxLucian, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3773#issuecomment-744061602.
