### ISSUE TITLE
anti cheat issue

### ISSUE THREAD

**Issue by bgkillas** [ValveSoftware/Proton#4472]
# Feature Request

## I confirm:
- [*] that I haven't found another request for this feature.
- [*] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
something that makes so you can see processes outside of the game so cheat engine cant just effect games that have an anti cheat that just looks for the process also prob someway to see if this feature is implemented for the anti cheat somehow
a game that is effected by this right now is totally accurate battlegrounds as it uses equ8 which trys to be nice with proton
## Justification [optional] 
so anti cheat would be useful in games

**Comment by kisak-valve** [comment]
Hello @bgkillas, there's no magic bullet to solve compatibility with anti-cheat software. The specific methods of any given anti-cheat mechanism have to be understood and also needs cooperation from the anti-cheat vendor. Since it doesn't look like Equ8 is used anywhere except Totally Accurate Battlegrounds, please use #3030 to discuss it and the game.

Closing in favor of #3030.

**Comment by bgkillas** [comment]
> Hello @bgkillas, there's no magic bullet to solve compatibility with anti-cheat software. The specific methods of any given anti-cheat mechanism have to be understood and also needs cooperation from the anti-cheat vendor. Since it doesn't look like Equ8 is used anywhere except Totally Accurate Battlegrounds, please use #3030 to discuss it and the game.
> 
> Closing in favor of #3030.

tabg launches and works perfectly besides a 15~% performance thing but that does not matter i can play the game and hack with cheat engine by just using cheat engine and if any other anti cheat supports proton it will also be effected unless some actually can detect cheat engine messing with the memory which i doubt

**Comment by bgkillas** [comment]
maybe ill explain it simpler because im bad at explaining things
anti cheat is in wine so it cant see outside processes
cheat engine can mess with game without anti cheat noticing that its running
