### ISSUE TITLE
GTA V. No Directx Runtime or Device Found. on nVidia

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#4473]
# Compatibility Report
GTA V

## System Information
-GPU: nVidia GTX1050
- Driver/ nVidia 455
- Kernel version: 5.10
- kDE Neon
- Proton version:Expertiment
- Linux Runtime Soldier Beta
- -Steam Client Beta

game currently updating will post log when finished

Symptoms 
When trying to access Advanced Graphics Settings this error box appears.

 [ No Directx runtime or device found ]
Then the game crashes. I can access this settings tab onces every 5 or so game launches.

**Comment by kisak-valve** [comment]
Hello @username-murphy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-745729106.
