### ISSUE TITLE
Skyrim Special Edition Creation Club and Mods don't work

### ISSUE THREAD

**Issue by JFortun** [ValveSoftware/Proton#4474]
# Compatibility Report
- Name of the game with compatibility issues: Skyrim Special Edition
- Steam AppID of the game: 489830

## System Information
- GPU: RX 5700 XT
- Driver/LLVM version: Mesa 2.3.0
- Kernel version: 5.10.1
- Proton version: 5.13-4

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

## Symptoms
Everything works fine besides the known audio bug but when you enter in-game mods or creation club you can't download any mods and those mods don't even load. I've tried on different computers and on different proton versions but none seems to work.

## Reproduction
Enter in-game mods or creation club and try to download any mod.

**Comment by kisak-valve** [comment]
Hello @JFortun, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4#issuecomment-746259424.
