### ISSUE TITLE
Unable to launch games with Proton 5.13 (Black screen on launch)

### ISSUE THREAD

**Issue by BRM95** [ValveSoftware/Proton#4485]
The titles work fine on Proton 5.0 but not with Proton 5.13. I'm running KDE Neon based on ubuntu 20.04. I've attached the relevant proton logs in case they help
https://gist.github.com/BRM95/6d2fd1006db008f9c7b870dc8e52ff64#file-steam-714010-log
https://gist.github.com/BRM95/b955c81e45232c9010775f3e9c96447d#file-steam-252950-log

I've also added the errors.log gist in case it might be useful.
https://gist.github.com/BRM95/c4e9714ca42a057b96e042f390a6d97e#file-errors-log

**Comment by kisak-valve** [comment]
Hello @BRM95, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

I suspect this is the same scenario as https://github.com/ValveSoftware/steam-runtime/issues/312#issuecomment-739441559. Please give the workaround in that comment a try.

**Comment by BRM95** [comment]
Seems to work! Thanks!
