### ISSUE TITLE
Far Cry 5 (552520) CTD once loaded and showing main menu

### ISSUE THREAD

**Issue by ri0t** [ValveSoftware/Proton#4487]
# Compatibility Report
- Name of the game with compatibility issues: Far Cry 5
- Steam AppID of the game: 552520

## System Information
- GPU:  Radeon Vega 56
- Driver/LLVM version:  Mesa 18.3.6, libdrm-amdgpu1 2.4.97
- Kernel version:   5.9
- Proton version: 5.13, 5.6-GE

## I confirm:
Since the game worked fine up until a mainboard/CPU swap, i'll leave these unchecked:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

[steam-552520.log](https://github.com/ValveSoftware/Proton/files/5721444/steam-552520.log)

## Symptoms 

Game ran fine until i swapped out mainboard and CPU (i7 6600 > Ryzen 3900), now:
- it starts,
- shows the epilepsy etc. warnings,
- plays back the AMD/Engine intro movies, 
- then proceeds to display the animated main menu background and the usual message "Logging in user" 
- then crashes to Desktop

## Reproduction

Start game, wait for shaders and Ubisoft Launcher updated etc., click away (or don't) intro movies, observe crash.

**Comment by kisak-valve** [comment]
Hello @ri0t, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2356#issuecomment-748665900.

**Comment by ri0t** [comment]
Oups, could've noticed the other ones below the initial one.. Thank you!
