### ISSUE TITLE
Cannot launch any game after reinstalling OS

### ISSUE THREAD

**Issue by tmvkrpxl0** [ValveSoftware/Proton#4490]
I recently re-installed Linux mint, and i have issue starting games with Proton
None of proton versions seems to work, they worked before re-installing
Games are installed on NTFS drive, but i made symbolic link compatdata directory from ext4 drive to NTFS drive, which worked before re-installing
I also have moved Protons to ext4 drive, but it did not solve the issue

root partition is installed on SSD, and /home is installed on HDD1, and NTFS drive is HDD2
this is the only log i was able to get, message "An error occurred while updating [GAME](compatibility tool configuration failed)"
Games that don't use proton, like Team fortress 2, launches fine, but games that do use proton don't work
Tested Proton versions are: Proton-Experiment, Proton 5.13, Proton 5.0
Tested Games that use Protons are: Doom(2016), Doom Eternal, Sonic generations
They all don't start with same message and same log

I tried re-installing steam and resetting steam, but it did not worked. I also tried re-installing Proton by deleting all Proton files manually and Checking Integrity did not worked

```
esync: up and running.
GameAction [AppID 782330, ActionID 6] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 782330, ActionID 6] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 782330, ActionID 6] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 782330, ActionID 6] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 782330, ActionID 6] : LaunchApp continues with user response "CreatingProcess"
src/clientdll/compatmanager.cpp (853) : Assertion Failed: GetCompatibilityToolCommandLineInternal on dependent tool failed
src/clientdll/compatmanager.cpp (853) : Assertion Failed: GetCompatibilityToolCommandLineInternal on dependent tool failed
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 782330, ActionID 6] : LaunchApp failed with AppError_51 with ""
GameAction [AppID 782330, ActionID 6] : LaunchApp changed task to Failed with ""
```

**Comment by intelligentgaming** [comment]
What GPU have you got, have you installed the latest driver for Vulkan support?

If I remember correctly, Linux Mint has a GUI tool for installing drivers, otherwise see - https://github.com/lutris/docs/blob/master/InstallingDrivers.md

It is not clear from what you have said but are your games still installed on a NTFS partition, if so if you install them on ext4 do the game then load?

**Comment by tmvkrpxl0** [comment]
:( I did complete re-installation of steam and it works now... I should've done this first
I simply deleted /home/tmvkrpxl0/.steam entirely
