### ISSUE TITLE
Leaf Blower Revolution (1468260)

### ISSUE THREAD

**Issue by somebody1234** [ValveSoftware/Proton#4494]
# Compatibility Report
- Name of the game with compatibility issues: Leaf Blower Revolution
- Steam AppID of the game: 1468260

## System Information
- GPU: GTX 1060 
- Driver/LLVM version: nvidia 455.45.01 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/): [link.](https://gist.github.com/somebody1234/4acb77ce3423ce10cb2ffb4638cf5472)
- Proton version: 1608325607 experimental-5.13-20201218c

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1468260.log](https://github.com/ValveSoftware/Proton/files/5740147/steam-1468260.log)

## Symptoms 
Works completely fine, then closes without warning about 30 seconds in.

## Reproduction
- Open game
- Wait 30 seconds. Gameplay may be needed, but what kind of gameplay should not matter. Behavior happens even without clicking.

**Comment by kisak-valve** [comment]
Hello @somebody1234, your log contains `eventfd: Too many open files`, please check [`ulimit -Hn`](https://github.com/ValveSoftware/Proton/wiki/Requirements#fd-limit-requirements-systemd--240) and verify it gives you a high value and not 4096.

**Comment by somebody1234** [comment]
welp, it gives 4096

**Comment by kisak-valve** [comment]
There's a write up on how to increase the limit at https://github.com/zfigura/wine/blob/esync/README.esync.

**Comment by somebody1234** [comment]
that seems to have fixed the issue, thanks
