### ISSUE TITLE
Install destination filesystem type 0 disk space

### ISSUE THREAD

**Issue by rhagu** [ValveSoftware/Proton#45]
Hi,
I have been running standard steam client on Manjaro for two years with a zfs dataset as the storage location for games. No problems so far.
After activating the beta I can install new games to folders with an xfs filesystem but not to a mounted zfs dataset.
I guess wine/proton does not yet recognize zfs. Can this be added?

ZFS mount:
![grafik](https://user-images.githubusercontent.com/3169452/44444581-c79b4f80-a5dd-11e8-93ba-2b6f61c689df.png)

xfs partition:
![grafik](https://user-images.githubusercontent.com/3169452/44444625-fca7a200-a5dd-11e8-9823-8c4ed3889f15.png)

**Comment by soredake** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/4982

**Comment by kisak-valve** [comment]
Hello @rhagu, as @soredake points out this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/4982. Closing as a duplicate.
