### ISSUE TITLE
PROTON_LOG has no effect

### ISSUE THREAD

**Issue by Flat** [ValveSoftware/Proton#450]
When setting PROTON_LOG=1 in the game "Set Launch Options" the environment variable has no effect and is appended to the executable launch string. No log file is generated under $HOME as specified https://github.com/ValveSoftware/Proton#runtime-config-options

<details>
<summary>System Information</summary>
<br>
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 1800X Eight-Core Processor         
    CPU Family:  0x17
    CPU Model:  0x1
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3656 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.18.4-arch1-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12001000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.54
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 20.91" x 11.77" (23.98" diag)
                                            53.1cm x 29.9cm (60.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Nvidia GPU 71 HDMI/DP

Memory:
    RAM:  32097 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Total Hard Disk Space Available:  434126 Mb
    Largest Free Hard Disk Block:  266709 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by Elkasitu** [comment]
I believe the changes introduced by commit https://github.com/ValveSoftware/Proton/commit/af9eb0240116d5f89ad6346ddcb54c314de399ce have not been pushed to steam users yet, my local proton file doesn't reflect the changes, despite restarting steam and launching a steam play title (which supposedly is the way to trigger a proton update).

Can you check your local proton file and see if it has the changes introduced by the aforementioned commit? If not, you can replace it by the file in the repo and see if that works (or wait till it is pushed to steam users).

**Comment by Flat** [comment]
Replacing `proton` with the version from master had no effect either. using `user_settings.py` does generate the log file however.

**Comment by Elkasitu** [comment]
Did you make the file you replaced it with executable? I tried the option with Hitman: Absolution and it worked:

![screenshot_20180825_003540](https://user-images.githubusercontent.com/4931545/44610927-e0368000-a7fe-11e8-8aca-4b999e564982.png)

 [The log itself](https://gist.github.com/Elkasitu/3f3e9d4ae84754dee30f32a38624ef06)

**Comment by Flat** [comment]
Yes, the file is executable.

**Comment by Elkasitu** [comment]
Did you set the launch option to `PROTON_LOG=1` or `PROTON_LOG=1 %command%`? If the former, try the latter, if not then maybe you could try setting it up in `user_settings.py` instead and if it still doesn't work then I have no clue :/

**Comment by Flat** [comment]
Works with `PROTON_LOG=1 %command%` so closing as working as intended I suppose. Still think its odd that `%command%` is needed.

**Comment by Elkasitu** [comment]
I believe the reason for the `%command%` is because by default the launch options are meant for the game executable and thus are appended to the end of the launch game command, if the env variable is after the launch game command then it won't have any effect on the game.

`%command%` allows to prepend anything to the launch game command, which is why it's the recommended way of using these variables in the README.

Hope that explains it :)
