### ISSUE TITLE
Batman Arkham Origins, 209000 left trigger of controller doesn't work

### ISSUE THREAD

**Issue by sizezero** [ValveSoftware/Proton#4502]
# Compatibility Report
- Name of the game with compatibility issues: Arkham Origins
- Steam AppID of the game: 209000

## System Information
- GPU: GeForce GTX 970
- Driver/LLVM version: 390.138
- Kernel version: 5.8
- Link to full system information report as [Gist](https://gist.github.com/): [system information](https://gist.github.com/sizezero/57a7a09e401a8242a949404be1dd52be)
- Proton version: 4.2-9, 4.11.13, 5.0-10, 5.13-4, 5.9-GE-8-ST

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-209000.log](https://github.com/ValveSoftware/Proton/files/5743963/steam-209000.log)

## Symptoms 

When in the game the left trigger does not work at all. (it's supposed to select and aim a weapon). I've tried both a wireless xbox one controller and a wired xbox 360 controller and both exhibit the same symptom. The controllers (and left trigger) work fine in other games including Batman Arkham City. (via Proton 4.2-9)

This appears to be a regression as I was able to play the game via steam/proton in March 2020 (with the same controllers) with no problems. Unfortunately I don't know the version of Proton I used then.

## Reproduction

I can get the game to run on Proton 4.2-9, 4.11.13, and 5.9-GE-8-ST. I need to set PROTON_USE_WINE3D or I get an error that "your graphics card does not support alpha blending". I have not been able to run the game at all with Proton 5.0-10 or 5.13-4. I'm launching the game from steam.

Enter the game in story mode, select a weapon/tool with the dpad and hold the left trigger. The tool is not selected to aim. The right trigger and all other buttons and controls work fine. Everything else in the game seems to work fine.

I haven't found any other issues that reference similar controller problems.

**Comment by kisak-valve** [comment]
Hello @sizezero, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1385#issuecomment-751415392.

As a side note, the nVidia 390 series video driver is older than the [minimum requirements](https://github.com/ValveSoftware/Proton/wiki/Requirements#nvidia) for Proton, which is why you're having a bad time with the Vulkan render path.
