### ISSUE TITLE
Game Won't Open at all when you press play

### ISSUE THREAD

**Issue by blackmagezeraf** [ValveSoftware/Proton#4505]
# Compatibility Report
- Ori and the Blind Forrest Definitive Edition
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report (https://gist.github.com/BlackMageZeraf/4b75f55e23a7e94d17bccc0de2457ee6#file-system-report-txt)
- Proton version: 5.13-4

## I confirm:
- [ o ] that I haven't found an existing compatibility report for this game.
- [ o ] that I have checked whether there are updates for my system available.

## Symptoms 
Game doesn't not open at all.

## Reproduction
I do not know how on protonDB there aren't people who ran into issues like this.

**Comment by kisak-valve** [comment]
Hello @BlackMageZeraf, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/67#issuecomment-751532445.
