### ISSUE TITLE
SpaceEngine (314650) crashes with Mesa 20.3.x and an AMD GPU

### ISSUE THREAD

**Issue by Anonymous1157** [ValveSoftware/Proton#4507]
# Compatibility Report
- Name of the game with compatibility issues: SpaceEngine
- Steam AppID of the game: 314650

## System Information
- GPU: Strix RX 580 4GB
- Driver/LLVM version: Mesa 20.3.1, LLVM 11.0.0
- Kernel version: 5.10.1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Anonymous1157/9e409e8ec41df03ef25596476e1228b3
- Proton version: 5.13-4

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-314650.log](https://github.com/ValveSoftware/Proton/files/5746542/steam-314650.log)

## Symptoms 

SpaceEngine crashes from the splash screen very early in the loading process if the system has an AMD GPU and Mesa is version 20.3.1. Downgrading to Mesa 20.2.6 allows the game to run normally.

This is also happening to an Arch Linux user with newer hardware, and they were able to reproduce the downgrade workaround: https://steamcommunity.com/app/314650/discussions/1/5242718027649464482/

## Reproduction

1. Switch the system Mesa version to 20.2.x
2. Start Steam, launch SpaceEngine, watch it run normally
3. Switch to Mesa 20.3.x
4. Restart Steam, launch SpaceEngine, watch it crash

**Comment by kisak-valve** [comment]
Hello @Anonymous1157, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2842#issuecomment-751703727.
