### ISSUE TITLE
The Curse of Monkey Island (730820)

### ISSUE THREAD

**Issue by doublez13** [ValveSoftware/Proton#4508]
# Whitelist Request
- Name of the game to be whitelisted: The Curse of Monkey Island
- Steam AppID of the game: 730820

## System Information
- GPU: GTX 970
- Driver/LLVM version: 455.45.01
- Distro version: Arch Linux
- Proton version: experimental_5.13

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.

## Issues
- [X] I haven't experienced any issues.

**Comment by kisak-valve** [comment]
Hello @doublez13, this game is already whitelisted. Also, Proton Experimental is an unstable build and not an eligible version for games to be whitelisted with.
