### ISSUE TITLE
Proton launches the initial installer script every game launch.

### ISSUE THREAD

**Issue by Phalen** [ValveSoftware/Proton#4509]
I have seen this in multiple versions of the proton / steam client as well as games.  Currently No Man's Sky is doing it and takes about 5 min to launch due to this. 

It does run the game normally afterwords but makes restarting the game arduous especially for those making changes to mods etc.

**Comment by kisak-valve** [comment]
Hello @Phalen, this kind of issue needs to be evaluated on a per-game basis, and we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-751880463,

**Comment by ghost** [comment]
I don't think this is a game-specific issue. But I also don't think it's a Proton issue, because the same thing has started happening on my end with Proton 4.11, which hasn't seen any changes since March last year. So it's probably the Steam app doing something wrong.
