### ISSUE TITLE
CODE VEIN demo Saves getting wiped after full Install

### ISSUE THREAD

**Issue by Gladox114** [ValveSoftware/Proton#4517]
# Bug Report
- Name of the game with issues: CODE VEIN
- Steam AppID of the game: 678960

## System Information
- GPU: GTX 1060 6GB
- Driver/LLVM version: nvidia 455.38
- Kernel version: 5.8.0-7630-generic
- Link to full system information report as [Gist](https://gist.github.com/): Not needed, can be provided if yes
- Proton version: Proton Experimental (Probably 5.13-4)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Characters made in Demo version of CODE VEIN are getting lost during full buy and install of the game

## Reproduction
Start new game and create Appearance (Character) in the Demo version.
Buy and install the full game. 
 `CODE VEIN demo isn't in your library anymore (Normal) `
       ` [Steam probably wipes the prefix where the saved data is located, this is bad]`
Start new game and check if `Load Character's Appearance from Demo` is available.

**Comment by kisak-valve** [comment]
Hello @Gladox114, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/7080 / #428 / #231. Closing in favor of the older issue reports.

**Comment by Gladox114** [comment]
EDIT: It already got mentioned https://github.com/ValveSoftware/Proton/issues/428#issuecomment-610331246

Issue https://github.com/ValveSoftware/steam-for-linux/issues/7080 and mine are very similiar or even the same.

Wouldn't it be easy to fix this problem by just merging the demo version prefix and the full game prefix. Or merging the steamuser folder in both prefixes `because in windows they would stay in the same place meaning that it shouldn't cause problems.` 
While https://github.com/ValveSoftware/Proton/issues/428 / https://github.com/ValveSoftware/Proton/issues/231 are maybe not as that easy fixable like my situation and his ValveSoftware/steam-for-linux#7080
