### ISSUE TITLE
All Proton games crash when inserting a new AMD Radeon RX GPU

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#4521]
Hello, I just switched out my GTX 1080 with a RX 5600 XT (for testing purposes). When I installed the GPU, everything works fine. Any Linux steam game and non-steam game (like Minecraft) runs perfectly. When I tried to launch Ori and the Blind Forest though, it crashes (the game screen does not even pop up at all). I then tried it out with Ace Combat 7, and the loading screen launched, but it greeted me with this message:
![image](https://user-images.githubusercontent.com/21233238/103450877-1ebb8f80-4c82-11eb-9231-79ef30f0a0f3.png)

Every other Proton game crashes too. I have tried:
- Installing the proprietary AMD GPU drivers.
- Installing the latest beta Ubuntu kernel (https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10/ note that it was giving me warnings that it probably was missing some things from the amdgpu module while I was installing).
- Deleting and reinstalling Proton 5.13.
- Using Proton 5.0.
- And searching this issue on the internet to no avail.

System info:
https://gist.github.com/Dreamurrrr/4b1021859d0d78041744908f3a4d554c

~~Steam system info:~~
~~https://gist.github.com/Dreamurrrr/c4ea7bae076a720c0bb99aece1b246ea~~

~~Linux Mint system-reports machine information:~~
~~https://gist.github.com/Dreamurrrr/08e6a9d208fb8f636105c54dbf6ba793~~

**Comment by kisak-valve** [comment]
Hello @Dreamurrrr, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) with the extended diagnostics information and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by ghost** [comment]
> Hello @Dreamurrrr, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) with the extended diagnostics information and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Done, @kisak-valve!

**Comment by kisak-valve** [comment]
I take it you switched back to your nVidia GPU before collecting that system information from Steam. There's no hints of an AMD video card there.

Blind guess that you needed to add `mesa-vulkan-drivers` and `mesa-vulkan-drivers:i386` to the system for the AMD card to have Vulkan drivers.

**Comment by Dreamurrrr** [comment]
> I take it you switched back to your nVidia GPU before collecting that system information from Steam. There's no hints of an AMD video card there.
> 
> Blind guess that you needed to add `mesa-vulkan-drivers` and `mesa-vulkan-drivers:i386` to the system for the AMD card to have Vulkan drivers.

Yeah I did. I can switch it back to the AMD GPU and then get the steam system info again. Though, the Linux Mint reports should show the info when I had my AMD gpu installed with the custom kernel.

I will switch it out when I have time and then reupload the system info.

**Comment by ghost** [comment]
> I take it you switched back to your nVidia GPU before collecting that system information from Steam. There's no hints of an AMD video card there.
> 
> Blind guess that you needed to add `mesa-vulkan-drivers` and `mesa-vulkan-drivers:i386` to the system for the AMD card to have Vulkan drivers.

Yeah I did. I can switch it back to the AMD GPU and then get the steam system info again. Though, the Linux Mint reports should show the info when I had my AMD gpu installed with the custom kernel.

I will switch it out when I have time and then reupload the system info.

I will also try the suggestion, @kisak-valve.

**Comment by ghost** [comment]
Great news, the blind guess worked! The Vulcan drivers were just missing, so I just ran `sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386` and I can now boot into games like I did with my Nividia card.
![image](https://user-images.githubusercontent.com/21233238/104083099-589c1100-5201-11eb-83a0-29b45c4ba362.png)
![image](https://user-images.githubusercontent.com/21233238/104083229-9c434a80-5202-11eb-941d-2c9841bad73b.png)
![image](https://user-images.githubusercontent.com/21233238/104083308-28557200-5203-11eb-9f08-c0dedf82359e.png)

I recommending some sort of notification upon enabling Proton to install these packages so people like me don't get confused, lol.
I will also upload my system stats by editing the first post upon closing this issue, @kisak-valve.
