### ISSUE TITLE
Detroit Become Human no launch

### ISSUE THREAD

**Issue by Richterman** [ValveSoftware/Proton#4525]
Game will nonly launch to do it's built in shader cache, yes this game has a built in shader cache, does it after steam's shader cache.
After the game does it, it will no longer launch. Here's the log.
My os is arch, latest as of pacman -Syu. My hardware is, amd 3800x, 5700xt, and i'm using amdgpu with mesa. I also belive i may have llvm installed as well(not sure, been 6 months since i built this computer). I tried all versions of proton and it still won't launch.
Please let me know if you need more information, I tried my best to be blunt, but his is also my first time writing a report.
[steam-1222140.log](https://github.com/ValveSoftware/Proton/files/5761055/steam-1222140.log)

**Comment by kisak-valve** [comment]
Hello @richterman, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4003#issuecomment-753549773.
