### ISSUE TITLE
Borderlands 3 endless black screen 

### ISSUE THREAD

**Issue by MEJacoby529** [ValveSoftware/Proton#4530]
# Compatibility Report
- Name of the game with compatibility issues: Borderlands 3
- Steam AppID of the game: 397540

## System Information
- GPU: nVidia Quadro M1000M
- Driver/LLVM version: nvidia v: 455.45.01
- Kernel version: 5.10.2-2
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Tried Experimental, & also Proton 5.21-GE-1

## I confirm:
- [There are reports, but not of this issue specifically, that I can see. ] that I haven't found an existing compatibility report for this game.
- [Y ] that I have checked whether there are updates for my system available.

## Reproduction: Not sure how one would do this....
I think I've uploaded the right error file, but not sure. New to this! Just trying to post a correct report.

**Comment by MEJacoby529** [comment]
[steam-397540.log](https://github.com/ValveSoftware/Proton/files/5765371/steam-397540.log)

Here's the log file, I think.

**Comment by kisak-valve** [comment]
Hello @MEJacoby529, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3635#issuecomment-754034985 with minor formatting adjustments.

**Comment by MEJacoby529** [comment]
> Hello @MEJacoby529, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#3635 (comment)](https://github.com/ValveSoftware/Proton/issues/3635#issuecomment-754034985) with minor formatting adjustments.

Thanks!
