### ISSUE TITLE
Doom Eternal extreme stuttering mainly when I move my mouse.

### ISSUE THREAD

**Issue by ufoludekxyz** [ValveSoftware/Proton#4532]
# Compatibility Report
- Name of the game with compatibility issues: Doom Eternal
- Steam AppID of the game: 782330

## System Information
- GPU: GTX 1070
- Driver/LLVM version: nvidia-dkms 455.45.01-1
- Kernel version: 5.10.4-arch2-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ufoludekxyz/50a08d9100223364b20a649b3c6d7c29
- Proton version: 5.13-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-782330.log.zip](https://github.com/ValveSoftware/Proton/files/5776348/steam-782330.log.zip)

## Symptoms 
I played the game for 20+ hours without any issues, one day for no reason the game started stuttering, after some research I found out it was somehow related to ESYNC, disabling it helped for few days, after Linux 5.10 update the game stutters just like it did before. It stutters with both ESYNC enabled and disabled, I also noticed that even my voice and the voice of others stutters on software like Discord when the game is running and stuttering. When I somehow manage to run the game without stuttering even Discord runs perfectly. When the game is running and stutterig it somehow afflicts my whole computer. I also tried with a different mouse and changed the polling rate to 125hz and 500hz, the stuttering persists.

## Reproduction
I just have to start the game. Sometimes the stuttering goes away if I switch between proton versions a bunch of times, but as soon as I reboot my computer the stuttering comes back.

**Comment by kisak-valve** [comment]
Hello @ufoludekxyz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3773#issuecomment-755338471.
