### ISSUE TITLE
[feature] Able to set a custom DXVK version

### ISSUE THREAD

**Issue by ranplayer** [ValveSoftware/Proton#4536]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description
It would be useful if a custom DXVK version could be set per game.

## Justification
Some DXVK versions present regressions in some games, like [Bayonetta](https://github.com/ValveSoftware/Proton/issues/262#issuecomment-757945870) running on Proton 5.13 (other D3D9 games might be facing the same issue). If you just change the Proton build from a previous version, you might loose bug fixes and performance improvements related to Wine.

**Comment by kisak-valve** [comment]
Hello @ranplayer, I think the intent for #4201 applies here. Regressions in DXVK or other sub-components of Proton should always be reported and fixed, not avoided. There are methods to swap out the version DXVK in use, but that shouldn't be considered supported.

**Comment by ranplayer** [comment]
@kisak-valve , I agree with you. The thing is: fixes may take time to be available for the final users, and in the meantime an easier workaround mechanism would be useful. I've been tracking some Proton regressions that took more than 6 months to get fixed (like this [one](https://github.com/ValveSoftware/Proton/issues/348#issuecomment-552694632) from Killer Instinct). 

Anyway, I just like to express here that I really enjoy this project and all the hard work from people involved.
