### ISSUE TITLE
Pacing issue with Project Cars 2 (id 378860)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#4537]
CPU: i7
RAM: 16Gb
GPU: GTX1050ti (driver version 460.32.03)
Proton: 5.13-4

I've never been able to get the game running smoothly. I set all the graphics options to the lowest possible and disabled all post processing effects. I also tried using libstrangle to enforce 60fps, with didn't help.

What happens is that, every 10 seconds or so, the game goes into 'slow motion' for a couple of seconds, and then 'catches up' by going very fast briefly, making the game very difficult to play.

The game has a platinum rating on ProtonDB, and a friend (with comparable specs) is able to run the game just fine as well.

Perhaps anyone else is experiencing the same issue?

**Comment by kisak-valve** [comment]
Hello @RalfVB, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/908#issuecomment-758025059.
