### ISSUE TITLE
The Turing Test (499520) - Cannot install

### ISSUE THREAD

**Issue by michaelclarkcuadrado** [ValveSoftware/Proton#454]
I cannot install the Turing Test game. It fails during UE4 Prerequisites are being installed with an error 'invalid ACL'.

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD FX(tm)-8320 Eight-Core Processor           
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3500 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux 4.x (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.18.4-arch1-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12001000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2018-06-14

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.54
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1401
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 3360 x 1050
    Primary Display Size: 18.50" x 11.81" (21.93" diag)
                                            47.0cm x 30.0cm (55.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  8010 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Total Hard Disk Space Available:  110278 Mb
    Largest Free Hard Disk Block:  46560 Mb
    VR Headset: None detected

**Comment by kisak-valve** [comment]
Hello @michaelclarkcuadrado, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue to https://github.com/ValveSoftware/Proton/issues/263#issuecomment-415900956.
