### ISSUE TITLE
Unfortunate Spacemen Microphone not detected 

### ISSUE THREAD

**Issue by FabioSedia** [ValveSoftware/Proton#4548]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 408900

## System Information
- GPU:  RX 570 8 GB 
- Driver/LLVM version: Mesa-tkg-git 21 
- Kernel version: 5.10.6-zen 
- Proton version: all versions have been tested

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Audio game is fine, but the game doesn't recognize the microphone, and thus you can't talk to other players in the match. From what I have heard in their discord they use the Windows default communication device as an input device, and proton can't handle this. The communication is fundamental to the game and then at this point it is unenjoyable. 

## Reproduction
Install game 
Start game 
Ask players If mic does not work 
(Spoiler: it doesn't)

**Comment by kisak-valve** [comment]
Hello @FabioSedia, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4095#issuecomment-760942063.
