### ISSUE TITLE
Hyperdimension Neptunia Re;Birth2 Sisters Generation (351710)

### ISSUE THREAD

**Issue by CygnusTerminal** [ValveSoftware/Proton#4549]
# Compatibility Report
- Name of the game with compatibility issues: Hyperdimension Neptunia Re;Birth2 Sisters Generation
- Steam AppID of the game: 351710

## System Information
- GPU: RX 480
- Driver/LLVM version: Mesa 20.3.2
- Kernel version: 5.10.6-110-tkg-bmq
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/CygnusTerminal/70e276f032863ea0f3f6337f7ef31b03
- Proton version: 5.0-10/5.13-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-351710.log](https://github.com/ValveSoftware/Proton/files/5820461/steam-351710.log)

## Symptoms 
Since days ago, this game and the other two (Re;birth 1 and 3) have been running pretty bad on my machine, fights and dungeons are below the 20 FPS mark. In combat, when the characters transform, the FPS go up to my vsync limit, only to go back to 17~20 when it's over. They use OpenGL. Native OpenGL games work like a charm (tested the entire Half-Life 2 franchise and Left 4 Dead franchise). I could observe the GPU usage ranging from values between 0% and 90%, every second. I've tried clean prefixes, disabling compositor manually, gamemode, no gamemode, setting the governor to performance, closing all background apps. Nothing seems to work. On Windows the games work as intended. I have also recorded a video with my external capture card, so the issues can be understood better (https://youtu.be/0JaVWKphLz0). Also, aside from the low quality due to pulseaudio being pulseaudio, and ALSA sounding with enough reverb to blow my eardrums, the popping is very noticiable, this has been an issue i've benn having with Wine/Proton since a month ago.

## Reproduction
Start the game, enter a dungeon/fight/observe the performance.

**Comment by kisak-valve** [comment]
Hello @CygnusTerminal, in general, we're using one issue report per unofficially supported game title, and since both games in #189 are equally affected, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/189#issuecomment-760220210.

If at some point there's an indication that there's a difference in the behavior between those two games, then it would make sense to track them separately.
