### ISSUE TITLE
[Question] Can I make compatibility reports for mods?

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#4555]
The Deus Ex Mod Launcher and Half-Life 2 MMod doesn't work right.
So can I report it here?
If "yes",how?
With the id of the base game?

**Comment by kisak-valve** [comment]
Hello @Toadfield, as part of the compromise made with us having one issue report per unofficially supported game title, feel free to discuss game mods on the compatibility report of those games.
