### ISSUE TITLE
Tomb Raider 2 crash, freezelags

### ISSUE THREAD

**Issue by noisecode3** [ValveSoftware/Proton#4558]
# Compatibility Report
- Name of the game with compatibility issues:Tomb Raider 2
- Steam AppID of the game:225300

## System Information
- tried both Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
-  NVIDIA Corporation GK106GLM [Quadro K2100M]
- nvidia prime 455.45.01-2 from mhwd
- Kernel version: 5.9.1-1-rt19-MANJARO #1 SMP PREEMPT_RT
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/martinbangens/038d081c9d4ab382499c8f5c6d3891d9
- Proton version:4.11-13

## I confirm:
- [ searched ] that I haven't found an existing compatibility report for this game.
- [updated Manjaro check today] that I have checked whether there are updates for my system available.

[steam-225300.log](https://github.com/ValveSoftware/Proton/files/5832776/steam-225300.log)

## Symptoms 
Input get stuck or messed up, the jump key gets stuck and kill me. Game crash and freezes, at specific places, and for some time before menu.

On windows I used to play this game with https://github.com/Arsunt/TR2Main with steam input, it worked grate. Now on proton everything seem to work the same and I also get rumble support from this method. except is not stable enough to play. Im happy to see it is working.

## Reproduction

download the patch https://github.com/Arsunt/TR2Main/issues/14
connect a ps4 to Bluetooth
activate steam input in settings
run tomb raider 2 setup
make sure there is only 1 xinput controller enable. menu is grayed out.
play the game

**Comment by kisak-valve** [comment]
Hello @martinbangens, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/932#issuecomment-762521616.
