### ISSUE TITLE
Everyversion of proton causes this same error when trying to launch eso on linux for me

### ISSUE THREAD

**Issue by LizziAS** [ValveSoftware/Proton#4559]
# Compatibility Report[0118/192043.218141:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
[0118/192043.334442:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
CAPIJobRequestUserStats - Server response failed 2
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

- ESO:
- Steam AppID of the game:

## System Information
- GPU: RX 580 
- Driver/LLVM version: 
- Kernel version: 5.10
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: All versions

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @LizziAS, we're using one issue report per unofficially supported game title. Please use #556 to discuss issues with Elder Scrolls Online.

Closing due to poor quality.
