### ISSUE TITLE
Proton 5.0 does not update

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#4563]
Hallo,
with Proton 5.0 I get the persistent error message (translated, so english version may have other text):
**During updating Proton 5.0 an error occurred (Invalid application configuration)**

On the other hand, all games which are using Proton run without error message regarding Proton or Proton update.....

I have started Proton directly, not via Steam Client. All troubleshooting from the Steam forum did not help.
Dont know if the attached files are th relevant ones.... and if the inability to update directly is an issue for Github... but Steam support suggested to open an issue on Github.

Regards Udo

[error.log](https://github.com/ValveSoftware/Proton/files/5847806/error.log)
[update_hosts_cached.txt](https://github.com/ValveSoftware/Proton/files/5847808/update_hosts_cached.txt)

Overall config:  

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-64-generic
OS Type: 64-bit
Processors: 32 × AMD Ryzen Threadripper 1950X 16-Core Processor
Memory: 62,7 GiB

**Comment by kisak-valve** [comment]
Hello @TroKhon, this is the same as https://github.com/ValveSoftware/steam-for-linux/issues/7192.

It's useful to have Proton listed in the tools section of Steam to have access to some options like verifying the tool's files and the ability to switch to beta branches of Proton, but Proton is not intended to be run as a stand alone application and this is error message from Steam is expected.
