### ISSUE TITLE
Farming Simulator 17 do not open (447020)

### ISSUE THREAD

**Issue by srtomy** [ValveSoftware/Proton#457]
click the button to play and nothing happens.

Computer Information:
Informações do computador:
    Fabricante: Unknown
    Modelo: Unknown
    Tipo: Computador de mesa
    Sem entrada de toque

Informações do processador:
    Fabricante da CPU: AuthenticAMD
    Marca da CPU: AMD FX(tm)-6300 Six-Core Processor             
    Família do processador: 0x15
    Modelo do processador: 0x2
    Stepping do processador: 0x0
    Tipo do processador: 0x0
    Velocidade: 3500 MHz
    6 processadores lógicos
    6 processadores físicos
    HyperThreading: Não suportado
    FCMOV: Suportado
    SSE2: Suportado
    SSE3: Suportado
    SSSE3: Suportado
    SSE4a: Suportado
    SSE41: Suportado
    SSE42: Suportado
    AES: Suportado
    AVX: Suportado
    CMPXCHG16B: Suportado
    LAHF/SAHF: Suportado
    PrefetchW: Não suportado

Versão do sistema operacional:
    Ubuntu 18.04.1 LTS (64-bit)
    Nome do kernel: Linux
    Versão do kernel: 4.15.0-29-generic
    Consórcio do Servidor X: The X.Org Foundation
    Versão do Servidor X: 11906000
    Gerenciador de janelas X: GNOME Shell
    Versão do runtime do Steam: steam-runtime-beta-release_2018-06-14

Placa de vídeo:
    Driver: NVIDIA Corporation GeForce GTX 660/PCIe/SSE2
    Versão do driver: 4.6.0 NVIDIA 390.48
    Versão do OpenGL: 4.6
    Profundidade de cor da área de trabalho: 24 bits por pixel
    Taxa de atualização do monitor: 59 Hz
    VendorID: 0x10de
    DeviceID: 0x11c0
    Revisão não detectada
    Número de monitores: 1
    Número de placas de vídeo lógicas: 1
    Resolução do monitor primário: 1366 x 768
    Resolução da área de trabalho: 1366 x 768
    Tamanho do monitor primário: 13.54" x 7.64" (15.51" diag)
 34.4cm x 19.4cm (39.4cm diag)
    Barramento primário: PCI Express 16x
    VRAM primária: 2048 MB
    Modos de MSAA suportados: 2x 4x 8x 16x 

Placa de som:
    Dispositivo de áudio: Realtek ALC887-VD

Memória:
    RAM: 7959 Mb

Outros:
    Idioma da interface: Português (Brasil)
    IDIOMA: pt_BR.UTF-8
    Total de espaço disponível em disco: 293153 MB
    Maior bloco livre do disco rígido: 245621 Mb
    Headset de RV: Nenhum encontrado

Relatórios de falha recentes:

**Comment by kisak-valve** [comment]
Hello @srtomy, you may have better luck after updating to nvidia 396.51 or newer

**Comment by srtomy** [comment]
Thank you very much. Games not works, I just removed the steam and updated the drive.
Now it worked.
I'm very happy to know that I can play my favorite games on my linux. Thank you.
