### ISSUE TITLE
Steam Play on Ubuntu 20.04 -- video card issue?

### ISSUE THREAD

**Issue by jcpahman77** [ValveSoftware/Proton#4573]
I contacted Steam tech support and was directed here. This is my issue: I have 2 laptops that I have installed Steam Play on with the intention of playing Among Us. One is a Lenovo T530 and runs Steam Play and Among Us without fault. The other is a Lenovo T520 with the Nvidia graphics (NVS 4200M) running the latest proprietary driver from Nvidia. Steam loads as it should be the game hangs at the launching window. I enjoy playing on the T530, but am considering streaming my game play and the T520 with the Nvidia card is much more suited to that task. Possible side issue, is it possible to run a game through Steam Play with multiple displays? Perhaps that is also an issue.

**Comment by kisak-valve** [comment]
Hello @jcpahman77, Proton uses DXVK to translate DirectX 9, 10, and 11 to Vulkan. It looks like the Lenovo T520 is an Intel Sandybridge / nVidia Fermi generation laptop. Neither of these graphics chipsets support Vulkan.

Additionally, it looks like the Lenovo T530 is a Intel Ivybridge laptop. There's incomplete Vulkan support available for that generation, but don't be surprised if you encounter significant rendering anomalies.

You may get lucky by telling Proton to use wine's DirectX to OpenGL render path by adding `PROTON_USE_WINED3D=1 %command%` to the game's launch options, but that comes with a significant performance penalty and is not considered supported.

In general, Proton is able to run on systems with multiple monitors, but there's a fairly long history of fullscreen games sometimes going to an unexpected display.
