### ISSUE TITLE
Smite

### ISSUE THREAD

**Issue by amirping** [ValveSoftware/Proton#4581]
# Compatibility Report
- Name of the game with compatibility issues: Smite
- Steam AppID of the game: 386360

## System Information
- GPU: intel UHD 620
- Driver/LLVM version: 3.0 Mesa 18.3.6
- Kernel version: 4.90.0-13-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/amirping/16799195fea00c21b11cfaf0b7cae5b8
- Proton version:  5.13-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-386360.log](https://github.com/ValveSoftware/Proton/files/5898687/steam-386360.log)

## Symptoms 
The game crash just after few seconds from the splash screen shows up, I do the test with Proton Experimental - 5.13 and 5.0
it gives the same behavior 

## Reproduction
Install smite with on Debian 10.

**Comment by kisak-valve** [comment]
Hello @amirping, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2208#issuecomment-770278742.
