### ISSUE TITLE
Company Of Heroes Pur Virtual Function Call

### ISSUE THREAD

**Issue by Ludo-code** [ValveSoftware/Proton#4582]
# Compatibility Report
- Name of the game with compatibility issues: Company of Heroes 
- Steam AppID of the game: 228200

## System Information
- GPU:  UHD Graphics 605
- Driver/LLVM version:  i915
- Kernel version:  5.8.0-42-generic x86_64
- Link to full system information report as [Gist](https://gist.github.com): https://gist.github.com/Ludo-code/f052aeafc8859cebcb0c21ebf77e81fa/
- Proton version: tried with all version but the best result is with the proton experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-228200.log](https://github.com/ValveSoftware/Proton/files/5899501/steam-228200.log)

## Symptoms 
Can't launch Vierville mission i have an error of pur virtual function call.

## Reproduction

Launch Company of Heroes and try to start Vierville mission.

**Comment by kisak-valve** [comment]
Hello @Ludo-code, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1381#issuecomment-770377314.
