### ISSUE TITLE
Invalid argument with PR_SET_SECCOMP and failed to start wineboot c00000e5

### ISSUE THREAD

**Issue by mwigzell** [ValveSoftware/Proton#4583]
# Compatibility Report
- Name of the game with compatibility issues: Dyson Sphere Program
- Steam AppID of the game: 1366540

## System Information
- GPU: GTX 960 
- Driver/LLVM version: 460.32.03
- Kernel version: 4.15.0
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/mwigzell/8521f1b0befb51b06330a12d16c44a49
- Proton version: 5.13-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1366540.log](https://github.com/ValveSoftware/Proton/files/5900566/steam-1366540.log)

## Symptoms 
Can't launch Dyson Sphere Program (or Warframe). 
Tried with latest Proton and with 4 previous versions offered: none work.
Log shows:
4097.939:0020:0030:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
4097.939:0020:0030:err:winediag:nodrv_CreateWindow The explorer process failed to start.

## Reproduction
Click "Play" in steam client, launcher window pops up, then goes away. Nothing more
This issue seems similar: https://github.com/ValveSoftware/Proton/issues/4266 but I'm unable to quite understand what might be wrong with X on my system: it works fine.

**Comment by kisak-valve** [comment]
Hello @mwigzell, in general, we're using one issue report per unofficially supported game title, but this sounds like general Proton issue and a not game-specific issue.

From the log, `prctl(PR_SET_SECCOMP, ...): Invalid argument` `err:environ:run_wineboot failed to start wineboot c00000e5` looks like the first sign of trouble.

Maybe try Ubuntu's hardware enablement kernel with something like `sudo apt install linux-generic-hwe-18.04 xserver-xorg-hwe-18.04`? The linux 4.15 kernel has a significant amount of age at this point.

**Comment by mwigzell** [comment]
Hi @kisak-valve I tried installing those hwe packages and unfortunately it won't boot to graphics run level. The recovery entry boots to non-graphic run level. I suppose this means that the kernel is somehow incompatible with my i7 cpu/graphic card, and that is the end of it I guess?

**Comment by kisak-valve** [comment]
Indeed, that's unfortunate. Blind guess that an nVidia dkms package (or by other means) didn't kick off a build, so the kernel-specific nVidia kernel module is missing.

**Comment by mwigzell** [comment]
to fix? I would have to build the nvidia driver with the kernel module sources ?

**Comment by mwigzell** [comment]
Hi @kisak-valve I spent last 6 days building a new ARCH installation and today I finally got sound working, so I installed STEAM and it started Dyson Sphere Program flawlessly. So I have a handle on it now. The Mint kernel was just too old like you say. Plus, my graphics card is SLOOOOWWWWW! Not sure if maybe I need to make sure it has hardware acceleration. 
Thanks for helping out!
