### ISSUE TITLE
/tmp/proton_$USER runfile not being generated anymore?

### ISSUE THREAD

**Issue by RhianneMoll** [ValveSoftware/Proton#4585]
Hi,

I play Supreme Commander Forged Alliance with the Forged Alliance Forever community client. Or, at least, I'm trying to :(

The community client requires the runfile generated in /tmp (with some slight modification) in order to launch the game directly instead of running it via steam.

I now have a freshly minted Ubuntu installation and am unable to figure out how Steam is launching the game using the latest Steam client. Instead of a runfile, there is some weird socket stuff being generated of which I grok nothing.

I have tried using the PROTON_DUMP_DEBUG_COMMANDS=1 launch option in the game properties (my understanding is that it's a requirement for the runfile to be created), to no avail.

I have tried setting up a runfile manually using some old resources I had, but I am getting an "Application load error 5:000065434" error, which - needless to say - isn't of much help.

At this point I'm stuck and have no idea how to get my favourite game running again :'(

Please help!
Thanks

**Comment by aeikum** [comment]
The debug commands option is working for me. You had this in the game's launch options: `PROTON_DUMP_DEBUG_COMMANDS=1 %command%` ?

**Comment by RhianneMoll** [comment]
aeikum, I forgot to add the %command% bit :woman_facepalming: 

It works. Thank you.

**Comment by aeikum** [comment]
Yeah, it's a bit non-obvious how Steam uses that field. If you just put something in that field, it will give whatever you put there to the game as a command line switch:

    Game.exe PROTON_DUMP_DEBUG_COMMANDS=1

The game probably won't recognize that command line switch, so it's just ignored.

But if you put `%command%` somewhere in there, then it interprets the whole thing as a shell command, including parsing it for environment variables, and substitutes the game executable for `%command%`:

    PROTON_DUMP_DEBUG_COMMANDS=1 Game.exe 

The proton script then picks up on that variable and dumps the scripts as requested.

**Comment by domdfcoding** [comment]
Even with `PROTON_DUMP_DEBUG_COMMANDS=1 %command%` nothing gets generated for me on anything newer than Proton 7.

**Comment by kisak-valve** [comment]
Hello @domdfcoding, please see https://github.com/ValveSoftware/Proton/issues/7575#issuecomment-1988299086 for more recent discussion on that.
