### ISSUE TITLE
Napoleon Total War crashes at end of turn with ELF error

### ISSUE THREAD

**Issue by Tasty213** [ValveSoftware/Proton#4589]
# Compatibility Report
- Napoleon Total War Definitive Edition
- Steam AppID: 34030

## System Information
- Mesa Intel HD graphics 520 (SKL GT2)
- 5.8.0-41-generic
- Ubuntu 20.04
- Proton version: 4.11

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-34030.log](https://github.com/ValveSoftware/Proton/files/5918239/steam-34030.log)

## Symptoms 
After ending and the AI simulating all the other nations the game crashes just before starting the players next turn.

## Reproduction
Open game, create a new campaign, play for a turn, end turn and wait until game crashes.

**Comment by kisak-valve** [comment]
Hello @Tasty213, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2245#issuecomment-772516453.
