### ISSUE TITLE
Batman Arkham Origins runs on older Proton versions but not on newer ones

### ISSUE THREAD

**Issue by Niveth2** [ValveSoftware/Proton#4590]
Hello,

I installed Batman Arkham Origins and while trying to launch it with the newest version of Steam Proton, it kept crashing, after troubleshooting for a while, I tried Steam Proton version 3.7-8 and it launched. Can you please fix on it so that it would work on newer proton versions

**Comment by kisak-valve** [comment]
Hello @Niveth2, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1385#issuecomment-772534907.
