### ISSUE TITLE
Add %command% substitution to non-steam games

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [ValveSoftware/Proton#4599]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Unlike native steam games, steam just appends the launch options after the target on non-steam games, even when %command% is added.

**Comment by kisak-valve** [comment]
Hello @Unkn0wn-MDCLXIV, this is an issue with the Steam client, not Proton itself, and this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/6046. Closing as a duplicate.
