### ISSUE TITLE
DOOM Demo crashes on Acer Nitro 5 w/Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by tptignor** [ValveSoftware/Proton#4602]
# Compatibility Report
- Name of the game with compatibility issues: DOOM Demo
- Steam AppID of the game: 479030

## System Information
- GPU:   Mesa Intel UHD Graphics 630 (CFL GT2)
- Driver/LLVM version:  nvidia-driver-460
- Kernel version:      Kernel Version:  5.8.0-40-generic
- Link to full system information report as [Gist](https://gist.github.com/):

https://gist.github.com/tptignor/b87d4a1685a55e6e4c962e9a82276881

- Proton version: Proton 5.13-5

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

No such log produced with this launch option.

## Symptoms 

The game crashes 10 seconds into startup.

## Reproduction

Open Steam. Accept any updates. Launch DOOM Demo.

**Comment by tptignor** [comment]
This crash report may also be helpful. 
Please let me know what other info I can provide or things I can try. Thanks in advance.


Callstack Function(desc)              Line Bytes File       Process Address
---------------------------           ---- ----- ----       ------- -------
** UNKNOWN **(** FUNC_PARAM_ERROR **) ...  +     0x7b01193e ?       
** UNKNOWN **(** FUNC_PARAM_ERROR **) ...  +     0x5b629255 ?       
** UNKNOWN **(** FUNC_PARAM_ERROR **) ...  +     0x5b2087be ?       
** UNKNOWN **(** FUNC_PARAM_ERROR **) ...  +     0x5b1eff47 ?       
** UNKNOWN **(** FUNC_PARAM_ERROR **) ...  +     0x5a754e4f ?       

Register Info                
---------------------------  
EDI:    0x0000000006447480  ESI: 0x0000000006447560  EAX:   0x0000000006447460
EBX:    0x00000001428DDD98  ECX: 0x0000000006447440  EDX:   0x0000000000000001
EIP:    0x000000007B01193E  EBP: 0x0000000006447560  SegCs: 0x0000000000000033
EFlags: 0x0000000000000202  ESP: 0x0000000006447420  SegSs: 0x000000000000002B

Exception Info               
---------------------------  
ExpCode:          0xE06D7363 (Undefined Exception)
ExpFlags:         1         
ExpAddress:       0x000000007B01193E 

Build & Runtime Info        
--------------------------- 
User:             steamuser        
Version:          20160720-180331-purple-razzmatazz        
File Path:        Z:\home\ttignor\.local\share\Steam\steamapps\common\DOOM Demo\DOOMx64vk.exe        
System Time:      2/9/2021 07:59:04        
Build String:     20160720-180331-purple-razzmatazz        
VT File Path:             
VMTR Override:    generated/pagefiles        
Launch Command:   "Z:\home\ttignor\.local\share\Steam\steamapps\common\DOOM Demo\DOOMx64vk.exe"  +r_renderAPI -2         

Memory Info                 
--------------------------- 
In Use:           80%      
MB Physical RAM:  4096        
MB Physical Free: 4096        
MB Paging File:   4096        
MB Paging Free:   4294965248        
MB User Address:  4096        
MB User Free:     4096        

CPU Info                    
--------------------------- 
Num Packages:     1        
Num Cores:        4        
Num Logical:      8        
CPU ID:           Generic        
CPU MHz:          4100

**Comment by kisak-valve** [comment]
Hello @tptignor, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/185#issuecomment-775931005.

**Comment by tptignor** [comment]
Hello kisak-valve,
I noticed #185 is 2 1/2 years old now and has no one assigned. Are you able to get someone assigned? Or do you think we should open a new issue?
Tom    :-) 

    On Tuesday, February 9, 2021, 08:22:43 AM EST, kisak-valve <notifications@github.com> wrote:  
 
 


Hello @tptignor, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to #185 (comment).
