### ISSUE TITLE
Valfaris (600130)

### ISSUE THREAD

**Issue by SoftwareSchlosser** [ValveSoftware/Proton#4611]
# Compatibility Report
- Name of the game with compatibility issues: Valfaris
- Steam AppID of the game: 600130

## System Information
- GPU: RTX 2060
- Driver/LLVM version: nvidia 460.39
- Kernel version: 5.4.0
- Link to full system information report as [Gist](https://gist.github.com/): [click](https://gist.github.com/SoftwareSchlosser/468cdbee8b620ef7cfbc4f4eb7d0083d)
- Proton version: 5.13-1

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[Log](https://gist.github.com/SoftwareSchlosser/0fc8240968a724bcd9aa6e3643827b87)

## Symptoms
Can't get my xbox 360 controller to work. Tried various Proton and Proton GE versions.
In the game settings, the gamepad option is grayed out.

## Reproduction
Start the game, try to use controller.

Big picture game controller configuration also shows an "ASRock LED Controller". Maybe this has to do with the problem?

**Comment by kisak-valve** [comment]
Hello @SoftwareSchlosser, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3208#issuecomment-778623859.
