### ISSUE TITLE
library folder on different drive, makedir fails, then make symlink fails

### ISSUE THREAD

**Issue by BMaxV** [ValveSoftware/Proton#4613]
I ran into the issue with "proton experimental" and "spellforce 3 soul harvest"

"A05E940E5E93DB7C" is the name of the drive the library is on.

Here is the console output:

Could not connect to X session manager: Authentication Rejected, reason : None of the authentication protocols specified are supported and hО��
Could not connect to X session manager: Authentication Rejected, reason : None of the authentication protocols specified are supported and h
GameAction [AppID 817540, ActionID 2] : LaunchApp changed task to ShowLaunchOption with ""
GameAction [AppID 817540, ActionID 2] : LaunchApp waiting for user response to ShowLaunchOption ""
Could not connect to X session manager: Authentication Rejected, reason : None of the authentication protocols specified are supported and h
Could not connect to X session manager: Authentication Rejected, reason : None of the authentication protocols specified are supported and h
GameAction [AppID 817540, ActionID 2] : LaunchApp continues with user response "0"
GameAction [AppID 817540, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
Traceback (most recent call last):
  File "/usr/lib/python3.7/tarfile.py", line 2206, in makelink
    os.symlink(tarinfo.linkname, targetpath)
OSError: [Errno 22] Invalid argument: '/' -> '/media/user/A05E940E5E93DB7C/SteamLibrary/steamapps/common/Proton - Experimental/dist/./share/default_pfx/dosdevices/z:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/user/A05E940E5E93DB7C/SteamLibrary/steamapps/common/Proton - Experimental/proton", line 939, in <module>
    g_proton.extract_tarball()
  File "/media/user/A05E940E5E93DB7C/SteamLibrary/steamapps/common/Proton - Experimental/proton", line 186, in extract_tarball
    tar.extractall(path=self.dist_dir)
  File "/usr/lib/python3.7/tarfile.py", line 2004, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2046, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2124, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2217, in makelink
    targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2118, in _extract_member
    self.makedir(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2147, in makedir
    os.mkdir(targetpath, 0o700)
OSError: [Errno 22] Invalid argument: '/media/user/A05E940E5E93DB7C/SteamLibrary/steamapps/common/Proton - Experimental/dist/./share/default_pfx/dosdevices/z:'
src/clientdll/installscript_posix.cpp (419) : Assertion Failed: Standalone evaluator returned error code for app 817540
src/clientdll/installscript_posix.cpp (419) : Assertion Failed: Standalone evaluator returned error code for app 817540
GameAction [AppID 817540, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 817540, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 817540, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 817540, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 817540, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 817540 "", ProcID 15842, IP 0.0.0.0:0
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Starting app 817540
>>> Adding process 15842 for game ID 817540
GameAction [AppID 817540, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
>>> Adding process 15843 for game ID 817540
>>> Adding process 15844 for game ID 817540
pid 15847 != 15844, skipping destruction (fork without exec?)
GameAction [AppID 817540, ActionID 2] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15845 for game ID 817540
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15846 for game ID 817540
>>> Adding process 15848 for game ID 817540
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15849 for game ID 817540
>>> Adding process 15850 for game ID 817540
>>> Adding process 15853 for game ID 817540
>>> Adding process 15854 for game ID 817540
>>> Adding process 15855 for game ID 817540
>>> Adding process 15857 for game ID 817540
>>> Adding process 15858 for game ID 817540
>>> Adding process 15859 for game ID 817540
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 16332 for game ID 817540
>>> Adding process 16333 for game ID 817540
>>> Adding process 16334 for game ID 817540
>>> Adding process 16335 for game ID 817540
>>> Adding process 16337 for game ID 817540
>>> Adding process 16341 for game ID 817540
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 16343 for game ID 817540
>>> Adding process 16346 for game ID 817540
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 16348 for game ID 817540
>>> Adding process 16350 for game ID 817540
>>> Adding process 16352 for game ID 817540
>>> Adding process 16354 for game ID 817540
>>> Adding process 16356 for game ID 817540
>>> Adding process 16359 for game ID 817540
>>> Adding process 16361 for game ID 817540
>>> Adding process 16362 for game ID 817540
Traceback (most recent call last):
  File "/usr/lib/python3.7/tarfile.py", line 2206, in makelink
    os.symlink(tarinfo.linkname, targetpath)
OSError: [Errno 22] Invalid argument: '/' -> '/media/user/A05E940E5E93DB7C/SteamLibrary/steamapps/common/Proton - Experimental/dist/./share/default_pfx/dosdevices/z:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/user/A05E940E5E93DB7C/SteamLibrary/steamapps/common/Proton - Experimental/proton", line 939, in <module>
    g_proton.extract_tarball()
  File "/media/user/A05E940E5E93DB7C/SteamLibrary/steamapps/common/Proton - Experimental/proton", line 186, in extract_tarball
    tar.extractall(path=self.dist_dir)
  File "/usr/lib/python3.7/tarfile.py", line 2004, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2046, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2124, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2217, in makelink
    targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2118, in _extract_member
    self.makedir(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2147, in makedir
    os.mkdir(targetpath, 0o700)
OSError: [Errno 22] Invalid argument: '/media/user/A05E940E5E93DB7C/SteamLibrary/steamapps/common/Proton - Experimental/dist/./share/default_pfx/dosdevices/z:'
Game removed: AppID 817540 "", ProcID 15842 
Uploaded AppInterfaceStats to Steam
Exiting app 817540
No cached sticky mapping in ActivateActionSet.

**Comment by kisak-valve** [comment]
Hello @BMaxV, what filesystem are you using with `/media/user/A05E940E5E93DB7C`?

**Comment by BMaxV** [comment]
Hi, impressive reply speed!

The drive is NTFS formatted if that's what you mean.

**Comment by kisak-valve** [comment]
Thanks, this is a long-standing issue with Proton interacting with NTFS going back to #11.

Using NTFS formatted partitions is temperamental at best, and using a native linux filesystem instead is recommended, but if you really want to tinker with that partition, then give https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows a read.

Closing in favor of the older issue report.

**Comment by BMaxV** [comment]
Cool, thanks, that's at least an answer. 

Although I would appreciate it if there was some system in place that would provide this kind of feedback in the steam client, or in another similarly obvious place.

What I got from the client itself was just nothing, it tried to start it and then the game quit, there was not even a notice that something had gone wrong at all.
