### ISSUE TITLE
Proton 5.13 breaks fullscreen

### ISSUE THREAD

**Issue by sebaro** [ValveSoftware/Proton#4615]
My display resolution is 1280x1024 and game resolution is set to 800x600.
The game doesn't start in full-screen but windowed mode (maximized).
Also the mouse position is not detected correctly, I have to click above game's clickable items/buttons.

If I change the game resolution to 1280x1024, the game flickers on start and it gets in full-screen but not correctly, I can see parts of the desktop. Toggling full-screen off/on in game setting fixes this issue but I have to do it every time I start the game.

Tried 5.13-5, 5.13-6.
Proton 5.0 is working fine.

Games:
The Witcher 1 (20900)
Railroad Tycoon II: Platinum (7620)

Attached logs for both 5.0 and 5.13:
[steam-20900.tar.gz](https://github.com/ValveSoftware/Proton/files/5936442/steam-20900.tar.gz)

System Info
[systeminformation.tar.gz](https://github.com/ValveSoftware/Proton/files/5977423/systeminformation.tar.gz)

Thanks.

**Comment by kisak-valve** [comment]
Hello @sebaro, `warn:  winevulkan detected, disabling exclusive fullscreen support` in the Proton 5.13 log makes this look like an intentional change in behavior. From https://github.com/doitsujin/dxvk/commit/cf1ff99b10cbbd6dfe1b19657b339cae0ed8dec7 in DXVK 1.7.1.

**Comment by DadSchoorse** [comment]
> Hello @sebaro, `warn: winevulkan detected, disabling exclusive fullscreen support` in the Proton 5.13 log makes this look like an intentional change in behavior. From [doitsujin/dxvk@cf1ff99](https://github.com/doitsujin/dxvk/commit/cf1ff99b10cbbd6dfe1b19657b339cae0ed8dec7) in DXVK 1.7.1.

I think the dxvk change is unrelated, `VK_EXT_full_screen_exclusive` in wine was just a stub implementation because some game (early version of Doom Eternal iirc) didn't start without it. So it shouldn't change anything if dxvk uses it or not.

**Comment by alasky17** [comment]
@sebaro  I don't exactly understand your report.  Railroad Tycoon II does not have the ability to switch to windowed mode or to change resolutions as far as I am aware.  Are you seeing all of the described behavior with both games or only with Witcher 1?  Are there any games besides Witcher 1 where you are seeing this?

Also, I did not see any of the behavior you mentioned with Witcher 1 on 5.13-6 with the same monitor resolution.  What did you mean by "The game doesn't start in full-screen but windowed mode (maximized)" - is this every launch?  Do you mean that the game starts in 800x600 resolution, but maximized to fill the screen and yet not fullscreen somehow?  Is this a feature of your WM?  

Once you've changed the resolution to 1280x1024 once, does the game not remember that on subsequent launches?   Or does it launch to 1280x1024 fullscreen mode, but flickers until you toggle fullscreen on/off?

**Comment by alasky17** [comment]
@sebaro also, you can check if this is a dxvk regression like kisak suggested pretty easily by dropping in the 32 and 64 bit dxvk files from 5.0-10 into the Proton 5.13-6 dist folder (delete the dist folder after to reset).  The files are located: ~/.steam/steam/steamapps/common/Proton 5.0/dist/lib/wine/dxvk/* and .../Proton 5.0/dist/lib64/wine/dxvk/*

**Comment by sebaro** [comment]
@alasky17 If the game resolution is set to 800x600, the game does not enter in full-screen  but in windowed mode (title-bar and borders). If full-screen is off the window size is 800x600, if full-screen is on, the window size is display size 1280x1024. If the game resolution is set to 1280x1024, the game enters full-screen but with issues, no title-bar and borders but I can see parts of the desktop. Toggling full-screen off/on fixes this issue. This happens on every start for all non-native games (I have these two installed now).

I tried with 5.0 dxvk files in 5.3, the same issue.

**Comment by alasky17** [comment]
@sebaro to confirm, this is only with Witcher 1?  I don't think it is possible to run Railroad Tycoon II on Proton in windowed mode at all.

Thank you for trying the dxvk file swap :)

**Comment by sebaro** [comment]
When the games starts, for a moment it is in full-screen but then it flickers and it shows the window title-bar and borders, like in windowed mode but I can't access them, can't hover mouse over them. If I move to a different virtual desktop using keyboard and move back to the game's virtual desktop, I can access the game's window, I can resize it but it's still in full screen because I can't click the steam window behind it unless I switch windows (alt+tab). It's the same for both games, but for RT2 when I switch to a different virtual desktop the game freezes and I see a Windows error.

Attached videos, some things are not visible, like the flickering.
[videos.tar.gz](https://github.com/ValveSoftware/Proton/files/5994538/videos.tar.gz)

**Comment by alasky17** [comment]
@sebaro Thank you for the video.  That really clarifies things.  I have a very strong suspicion that the problem is with your WM.  Especially because Railroad Tycoon II doesn't even have a way to go in windowed mode, so it is your WM forcing it to appear that way with window decorations.  

Could you check if the same behavior happens with Witcher 1 if you force it to use wined3d instead of dxvk?  You can just stick  PROTON_USE_WINED3D=1 %command% in the launch options.

**Comment by sebaro** [comment]
It is a WM issue (FVWM2), no problems with Fluxbox and KDE.
Thank you for your help.

**Comment by arrowgent** [comment]
good to know that WM issues are more likely a cause of frustration than the proton itself

i use MATE (gnome2 fork) and have few issues with proton handling resolution scaling

**Comment by sebaro** [comment]
This FVWM style fixes the issue:
```Style * MWMFunctions, MWMDecor, HintOverride, ResizeHintOverride```

There are games that require more tweaks, but it's not a Proton issue.
