### ISSUE TITLE
Superpower 2 Steam Edition (282400)

### ISSUE THREAD

**Issue by ioannis120** [ValveSoftware/Proton#4618]
# Compatibility Report
- Name of the game with compatibility issues:Superpower2 Steam Edition
- App ID:282400

## 

ptoms It does not start

**Comment by kisak-valve** [comment]
Hello @ioannis120, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by ioannis120** [comment]
[steam-282400.log](https://github.com/ValveSoftware/Proton/files/5982362/steam-282400.log)

**Comment by kisak-valve** [comment]
Comments from #4619.
***
@ioannis120 commented on 2021-02-15T14:32:30:

[Joshua_Client.log](https://github.com/ValveSoftware/Proton/files/5982104/Joshua_Client.log)
[joshua_d3d9.log](https://github.com/ValveSoftware/Proton/files/5982105/joshua_d3d9.log)
[video_config_d3d9.log](https://github.com/ValveSoftware/Proton/files/5982106/video_config_d3d9.log)

***
@ioannis120 commented on 2021-02-15T14:33:34:


[steam-282400.log](https://github.com/ValveSoftware/Proton/files/5982339/steam-282400.log)
Anything else or not I am new to this
***
@kisak-valve commented on 2021-02-15T14:49:54:

Looking through your system information, there's some kind of system issue with Vulkan on your system. OpenGL is running on the video chipset, but with Vulkan, it's not seeing your video card at all. It's also trying to use lavapipe which is a software-based render path and that is currently not compatible with Proton, but lavapipe's involvement is just a distraction.
***
@kisak-valve commented on 2021-02-15T14:54:33:

Looks like your A10-7860K is a Kaveri chipset which is part of the Sea Islands (CIK) generation of AMD cards. By default, Linux uses the `radeon` kernel module with this generation but the `radeon` kernel module is not compatible with Vulkan. Please give https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games a read.

**Comment by ioannis120** [comment]
The Football manager 2019 plays fine as it is

**Comment by ioannis120** [comment]
thank you!

**Comment by ioannis120** [comment]
that is the new one if it is the same with (314980) i will try
[steam-282400.log](https://github.com/ValveSoftware/Proton/files/5998664/steam-282400.log)

**Comment by ioannis120** [comment]
It works now after i changed the kernel that loads amd gpu, thank you!
