### ISSUE TITLE
World Of Warships Proton 5.13.5 crash (dump included)

### ISSUE THREAD

**Issue by webaake** [ValveSoftware/Proton#4623]
# Compatibility Report
- Name of the game with compatibility issues: World Of Warships
- Steam AppID of the game: 552990

## System Information
- GPU: Nvidia GT750
- Driver/LLVM version: Nvidia 450.102.04
- Kernel version: 5.4.0-62
- Link to full system information report as [Gist](https://gist.github.com/): Ubuntu 18.04
- Proton version: 5.13.5
## I confirm:
- [ Yes] that I haven't found an existing compatibility report for this game.
- [Yes ] that I have checked whether there are updates for my system available.

## Symptoms 
**Crash Dump:** 

Application Z:/mnt/506GB/STEAM/steamapps/common/World of Warships/bin/3343484/bin64/WorldOfWarships64.exe crashed 02.16.2021 at 09:14:39

Message:
Unhandled exception

Hash: 51319
EIP: 0x00000000410A1550

Current thread #276 native trace:
(0) : WorldOfWarships64.exe!0x00000001410A1550
(0) : WorldOfWarships64.exe!0x00000001410E590E
(0) : WorldOfWarships64.exe!0x00000001410E2C3C
(0) : WorldOfWarships64.exe!0x00000001410E6699
(0) : WorldOfWarships64.exe!0x000000014113A645
(0) : WorldOfWarships64.exe!0x000000014114DFE9
(0) : WorldOfWarships64.exe!0x00000001410B89D0
(0) : WorldOfWarships64.exe!0x00000001410E69F6
(0) : WorldOfWarships64.exe!0x00000001411B0011
(0) : WorldOfWarships64.exe!0x00000001411ADFD3
(0) : WorldOfWarships64.exe!0x00000001411ADB32
(0) : WorldOfWarships64.exe!0x00000001411AC2FD
(0) : WorldOfWarships64.exe!0x000000014114DFE9
(0) : WorldOfWarships64.exe!0x00000001410E1113

System info:
	OS Name: Windows 7
	OS Version: 6.6 SP1
	OS Architecture: x86_64

Memory info:
	Virtual memory: 64Kb/137438953343Kb (1%)
	Working set (process physical memory): 2735752Kb/16795388Kb (16%)
	Commit charge (working set + process page file usage): 2375564Kb/16795392Kb (14%)
	Global physical memory: 5319884Kb/16795388Kb (31%)
	Global commitable memory (physical + pagefile): 4833232Kb/16795392Kb (29%)

System info:
APPLICATION = DISPLAYDEVICE 0 = \\.\DISPLAY1, GeForce GTX 745, PCI\VEN_10DE&DEV_1382&SUBSYS_00000000&REV_00

**Comment by kisak-valve** [comment]
Hello @webaake, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/333#issuecomment-779807294.
