### ISSUE TITLE
EAC on Rust

### ISSUE THREAD

**Issue by davidaamesjr** [ValveSoftware/Proton#4624]
Just curious if there are any resolutions on the EAC not working for Rust on Proton.. requested a refund and I'm only played 3 hours on a windows box but cannot connect to servers on Linux.. main PC is linux, deleted windows anyway now.,, they are denying my refund request over and over again and wont forward me to a supervisor or manager or anything... really either want my money back or for it to work.. lol.  Thanks.

# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @davidaamesjr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3104#issuecomment-780255529. Additionally, any account issues including refunds are not handled here.
