### ISSUE TITLE
Proton in steam is unable to create renderer for non-vulkan system without PROTON_USE_WINED3D

### ISSUE THREAD

**Issue by Kreyren** [ValveSoftware/Proton#4629]
Proposing there to be check for vulkan support and set the `PROTON_USE_WINED3D` automatically.

**Comment by kisak-valve** [comment]
Hello @Kreyren, this request was previously discussed on #1749. Using `PROTON_USE_WINED3D` is not supported. (https://github.com/ValveSoftware/Proton/pull/1749#issuecomment-489606572)
