### ISSUE TITLE
Update MoltenVK to current (>=1.0.18)

### ISSUE THREAD

**Issue by oscarbg** [ValveSoftware/Proton#463]
Hi,
seems using MotlenVK 1.0.10 but on seems project is already at 1.0.19 on master as latest commits logs show "Update to MoltenVK version 1.0.19"..

**Comment by jmannanc** [comment]
I would wait until 1.0.19 for Xcode 10 support and maybe Vulkan 1.1.

**Comment by romulasry** [comment]
It supports Xcode 10, now just for Vulkan 1.1:

https://github.com/KhronosGroup/MoltenVK/issues/223

**Comment by jmannanc** [comment]
1.0.18 supports Xcode 10? They haven't made an official tag of 1.0.19 yet but I'm going to go ahead and open a PR to update to 1.0.18. When they do update to 1.0.19 we can update then as well.

**Comment by romulasry** [comment]
In current MASTER (git HEAD):
https://github.com/KhronosGroup/MoltenVK/commit/5bc8403cc1b3eb3464c5c5314844e473796247e9

**Comment by jmannanc** [comment]
I only want to go up to the official release though, not to HEAD.

**Comment by oscarbg** [comment]
moltenvk 1.0.20 has been released!

**Comment by romulasry** [comment]
v1.0.23
    26c7b69

Release for Vulkan SDK 1.1.85

@billhollings billhollings released this 2 days ago · 18 commits to master since this release
Assets 2

    Source code
    (zip)
    Source code
    (tar.gz)

    Add support for features:
        shaderStorageImageMultisample
        shaderStorageImageReadWithoutFormat
        shaderStorageImageWriteWithoutFormat
        shaderUniformBufferArrayDynamicIndexing
        shaderSampledImageArrayDynamicIndexing
        shaderStorageBufferArrayDynamicIndexing
        shaderStorageImageArrayDynamicIndexing
    Support reduced render area
    Support rasterization to missing attachment
    Allocate MVKCommandBuffers from a pool within MVKCommandPool.
    Update glslang version
    Update to latest SPIRV-Cross version:
        MSL: Improve coordinate handling for buffer reads.
        MSL: Expand arrays of buffers passed as input.
