### ISSUE TITLE
Brawlhalla (291550) exits on startup

### ISSUE THREAD

**Issue by Kreyren** [ValveSoftware/Proton#4630]
![image](https://user-images.githubusercontent.com/11302521/108191442-6a7fa680-7113-11eb-859b-e7a8073f94fb.png)

# Compatibility Report
- **Name of the game with compatibility issues**: Brawlhalla
- **Steam AppID of the game**: 291550

## System Information
- **GPU**: AMD ATI Radeon HD 6630M/6650M/6750M/7670M/7690M
- **Driver/LLVM version**: AMD TURKS (DRM 2.50.0 / 5.9.0-5-amd64, LLVM 11.0.1)
- **Kernel version**: 5.9.0-5-amd64 (packaged by devuan)
- **Link to full system information report as [Gist](https://gist.github.com/)**: https://gist.githubusercontent.com/Kreyren/2a5a163219817e23c0378e63482740af/raw/41577ef4a89809529c21547ff39b31a974ef4323/gistfile1.txt
- **Proton version**: 5.13-6
- **Steam Distribution**: Flatpak
- **Hostname**: kreyren@leonid.rixotstudio.cz (used for my identification of system)

## I confirm:
- [-] that I haven't found an existing compatibility report for this game.
	- Found https://github.com/ValveSoftware/Proton/issues/83 -> Concluded different issue
- [X] that I have checked whether there are updates for my system available.

## Symptoms

Game exits on startup

## Reproduction

1. Start the game on steam and expect failure
1.1. On non-vulkan system try to set `PROTON_USE_WINED3D=1` to exclude https://github.com/ValveSoftware/Proton/issues/4629 and expect failure

**Comment by kisak-valve** [comment]
Hello @Kreyren, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/83#issuecomment-780554618.
