### ISSUE TITLE
MotoGP™20 (1161490)

### ISSUE THREAD

**Issue by mpasquini** [ValveSoftware/Proton#4631]
Proton version: 4.11-13
App ID: 1161490
Build Id: 6006326
OS: Linux --- 5.7.0-0.bpo.2-amd64 #1 SMP Debian 5.7.10-1~bpo10+1 (2020-07-30) x86_64 GNU/Linux

Game crashed once while saving, loaded game differ. 
Game files saved on Steam cloud.

Details: 
In career mode
Completed portion of weekend, the Friday tests at Jerez 
Exiting to main menu game crashed
Pc restarted
Game loaded 
Found career at LeMans, that is the ride next to Jerez, with Friday test completed.
Got -1000 points for not having completed Jerez
Got position "0th" on podiums from first up to Jerez one.

Game currently crash selecting Jerez week-end. 

Attempted to: 
Removed steam cloud file save -> no difference, game crash if Jerez week-end is selected.

Opened game and make a change (hired a staff member) 
Closed game
Opened game, game has the change (hired staff member)
Other issues are still present.
 

Extra info: Proton version 4.11-13 is used due other crashes :
- 5.13-6 - crash
- 5.0.10 - crash
- Experimental : never used

<details><summary>System info:</summary><p>

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0xc
    CPU Type:  0x0
    Speed:  4600 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Debian GNU/Linux 10 (buster) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.7.0-0.bpo.2-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12004000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20201203.1

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1650/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 418.181.07
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1f82
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.90" x 10.63" (21.65" diag)
                                            48.0cm x 27.0cm (55.0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC1220

Memory:
    RAM:  15922 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  C
    Total Hard Disk Space Available:  207525 Mb
    Largest Free Hard Disk Block:  112893 Mb

```

</p></details>

**Comment by kisak-valve** [comment]
Hello @mpasquini, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the crash, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by mpasquini** [comment]
Hello @kisak-valve 

This is the result log file
[steam-1161490.log](https://github.com/ValveSoftware/Proton/files/5996322/steam-1161490.log)

Thanks.

**Comment by ipr** [comment]
Seems to work fine on Proton 7.0.
Is there a chance reporter could retest to see if problem still appears?

**Comment by mpasquini** [comment]
Thanks
