### ISSUE TITLE
Tomb Raider: Underworld (8140)

### ISSUE THREAD

**Issue by hotwinter** [ValveSoftware/Proton#4640]
# Compatibility Report
- Name of the game with compatibility issues: Tomb Raider: Underworld
- Steam AppID of the game: 8140

## System Information
- GPU: GTX 1660 Super
- Driver/LLVM version: NVIDIA 460.39
- Kernel version: 5.8.0-43-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/hotwinter/096349371ad10e75cec5d3252ef39826
- Proton version: 5.13-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game does not launch, lots of repeated c0000005 exception thrown, log is too large, thus compressed

[steam-8140.zip](https://github.com/ValveSoftware/Proton/files/6014591/steam-8140.zip)

**Comment by kisak-valve** [comment]
Hello @hotwinter, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3616#issuecomment-782642254.
