### ISSUE TITLE
Just Cause 2 (8190)

### ISSUE THREAD

**Issue by ioannis120** [ValveSoftware/Proton#4644]
# Compatibility Report
- Just Cause 2
- App ID:8190
-Proton version:Experimental

https://gist.github.com/ioannis120/c664f015742641d8441b0f4fdddf985b
[steam-8190.log](https://github.com/ValveSoftware/Proton/files/6022237/steam-8190.log)

It does not start
it is also here but no the same issue:https://github.com/ValveSoftware/Proton/issues/670

**Comment by kisak-valve** [comment]
Hello @ioannis120, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/670#issuecomment-783382928.
