### ISSUE TITLE
Eve Online Launcher Stopped Working After Update

### ISSUE THREAD

**Issue by odhinnsrunes** [ValveSoftware/Proton#4645]
# Compatibility Report
- Name of the game with compatibility issues: Eve Online (Launcher)
- Steam AppID of the game: 8500

## System Information
- GPU: RTX 2080
- Driver/LLVM version: NVidia 460
- Kernel version: 5.4.0
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/odhinnsrunes/a61c3a8a21c15750b5b916638a7ce2be
- Proton version: All including experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

The proton logging seems to have triggered a race condition causing a thread deadlock in the Eve Launcher preventing it from starting. I've attached it anyway.

## Symptoms 
Try to start the Launcher from inside Steam. The CCP logo appears, then a black box where the launcher should load.  Then it turns white and crashes. The "Stop" button in steam goes back to "Play". It worked perfectly until CCP pushed a new version of the Launcher on the 8th. I've also tried in Wine and it has stopped working there as well. My understanding from Wine is, that it has something to do with an incompatibility in the built-in MSVC 140 runtimes. In wine, if you override them to use the native runtimes, specifically msvcp140_1, the launcher will run, but can't contact the server to set up the HTML-based UI in the launcher. Running the network diagnostics in the launcher shows that it can not do any network functions in that configuration.
[steam-8500.log](https://github.com/ValveSoftware/Proton/files/6022257/steam-8500.log)

The crash in Wine is here:
Unhandled exception: unimplemented function msvcp140_1.dll._Aligned_get_default_resource called in 32-bit code 
## Reproduction
Download, install and Run Eve Online in any version of Proton from steam.

**Comment by kisak-valve** [comment]
Hello @odhinnsrunes, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1223#issuecomment-783386149.
