### ISSUE TITLE
DQB_EU.exe lockup during gameplay

### ISSUE THREAD

**Issue by awsdert** [ValveSoftware/Proton#4648]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 1072420

## System Information
- GPU: Reported as "Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]"
- Driver/LLVM version: Under Manjaro's "Hardware Configuration" section of it's settings it just says "video-linux"
- Kernel version: 5.11.0-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/awsdert/681695524864c36a78729e643cd5b902
- Proton version: "Proton Experimental"

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. - Couldn't think of a suitable search for this one, if you find one of the same nature that's still open just link it then close this one
- [x] that I have checked whether there are updates for my system available. - Fully upto date

## Proton Log
This came out pretty big as I had left the game on overnight while steam downloaded a fresh copy of FFXV (which is now reporting it couldn't verify my copy, these online requirements for games that should be offline are really annoying), the main reason was that I was doing a scan for a particular value at 3am, decided f**k it, just turn the monitor off and go to sleep.
https://drive.google.com/file/d/1ZWW2ARIaXC70mHpjOA7cIdnvF65SYrar/view?usp=sharing

## Symptoms 
Locked up on me during gameplay, true I had been editing values with PINCE but it wasn't when I was doing that that the lockup occurred, it was while I was placing down castle blocks in Furrowfield. Lot of effort went to waste due to the unexpected lockup.

## Reproduction
Just build I guess, as I said I was placing down blocks when it happened but I had placed down a lot of blocks prior to that and nothing unexpected happened until that random lockup

**Comment by kisak-valve** [comment]
Hello @awsdert, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3309#issuecomment-784180049.

**Comment by awsdert** [comment]
Thx
