### ISSUE TITLE
Proton can no longer run games from NTFS drive

### ISSUE THREAD

**Issue by Psuedomonas** [ValveSoftware/Proton#4651]
Proton 5.13-6, 5.0, 4.11; 
Nvidia drive 460.39; 
5.4.0-66-generic x86_64 bits

After a clean upgrade of Linux Mint 19.3 to 20.1, no games from my separate NTFS drive will launch. Re-installation and verify files does not remedy the issue. I tried modifying fstab to ensure ntfs-3g as directed in the post https://support.steampowered.com/kb_article.php?ref=7611-FHLZ-4319, and the associated Ubuntu articles. These games can be run off the drive using wine, but often require a connection to steam. 

Workaround 1: I can install a couple of games on my system drive (ext4), and they work fine
Workaround 2: I have not tested this, but in the past I had a version of steam run in wine. I don't know how well this would work for many titles, but it may get a few to work.

Thank you for supporting Linux and developing proton, let me know if I can help you help me :)
Cheers

**Comment by Psuedomonas** [comment]
Workaround 1 is apparently not consistent.

**Comment by kisak-valve** [comment]
Hello @Psuedomonas, Proton interacting with NTFS is known to be finicky and it is recommended that you use a native Linux filesystem with Proton. That said, you might have some luck with https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows.

**Comment by Psuedomonas** [comment]
Hello and thanks for the response! I found one possible issue is that my NTFS is owned by root. I'll check out the link and check if ownership/access is an issue. If that is all it is, I apologize in advance for the spam.

**Comment by Psuedomonas** [comment]
Yes this was an NTFS issue. It is fixed! Sorry for bothering this you with this. I'll try to broadcast the link for others that may stubbornly use NTFS game drives.

**Comment by Psuedomonas** [comment]
Thank you
