### ISSUE TITLE
Age of Empires II: Definitive Edition - freezing, FPS below 1 Hz

### ISSUE THREAD

**Issue by lgmventura** [ValveSoftware/Proton#4654]
# Compatibility Report
- Name of the game with compatibility issues: Age of Empires II: Definitive Edition
- Steam AppID of the game: 813780

## System Information
- GPU: GTX 760M
- Driver/LLVM version: nvidia-driver-450
- Kernel version: 5.4.0-52-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/lgmventura/999f15f0975983d7a2e1c0ad48a9e82f
- Proton version: 5.13-4 and Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Running Steam with `STEAM_LINUX_RUNTIME_LOG=1 steam` generated [this](https://gist.github.com/lgmventura/3c04f3fc7b772f4f3bc743c5089102b2)

## Symptoms 
Until May of 2020, the game was working fine for Single Player games. In June there was an update that made the game start to freeze all the time, also in the menus, except for the main menu. The FPS goes below 1 Hz. Actually it mostly goes fluid for a fraction of a second and freezes for several seconds, including mouse pointer, even when I do an Alt+Tab to switch to another window and start moving the mouse over something else. But the main menu of the game is still fluid, even if it looks exactly like the other menus. None of the updates from June 2020 onwards changed this. At the current state, the game is completely unplayable in Linux.

## Reproduction
- Install Age of Empires II: Definitive Edition
- Set up Steam Play to use Proton 5.13 or Proton Experimental.
- Click play.

**Comment by kisak-valve** [comment]
Hello @lgmventura, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3189#issuecomment-786798114.

**Comment by lgmventura** [comment]
OK, thanks for transferring into there, but I posted there again with the correct gist links.
