### ISSUE TITLE
Company of Heroes 2 (64-bit) (231430)

### ISSUE THREAD

**Issue by ms178** [ValveSoftware/Proton#4656]
# Compatibility Report
- Name of the game with compatibility issues: Company of Heroes 2 (64-bit version)
- Steam AppID of the game: 231430

## System Information
- GPU: AMD Vega 56
- Driver/LLVM version: mesa-git-21.1.0_devel.135852.0a7224f3ff7-1-x86_64
- Kernel version: 5.11.2

System:    Host: klx99 Kernel: 5.11.2-xanmod1 bits: 64 Desktop: KDE Plasma 5.21.1 Distro: Manjaro Linux 
Machine:   Type: Desktop Mobo: N/A model: KLX99 v: 1.0 serial: <superuser required> UEFI: American Megatrends v: 5.11 
           date: 04/27/2020 
CPU:       Info: 12-Core model: Intel Xeon E5-2678 v3 bits: 64 type: MT MCP L2 cache: 30 MiB 
           Speed: 3279 MHz min/max: 1200/3300 MHz Core speeds (MHz): 1: 3279 2: 2834 3: 2362 4: 1564 5: 3296 6: 1817 7: 3293 
           8: 1344 9: 2479 10: 3293 11: 3263 12: 3193 13: 3293 14: 2720 15: 3267 16: 2079 17: 3293 18: 3164 19: 2527 20: 2055 
           21: 1925 22: 1980 23: 1693 24: 3263 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Vega 10 XL/XT [Radeon RX Vega 56/64] driver: amdgpu v: kernel 
           Display: x11 server: X.Org 1.20.10 driver: loaded: amdgpu,ati unloaded: modesetting resolution: 1920x1080 
           OpenGL: renderer: Radeon RX Vega (VEGA10 DRM 3.40.0 5.11.2-xanmod1 LLVM 11.1.0) 
           v: 4.6 Mesa 21.1.0-devel (git-0a7224f3ff) 

- Proton version: every version above 5.0-10 crashes while loading the in-game benchmark (e.g. 5.13-6 and Experimental; 5.0-10 is working fine)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Log for Proton Experimental [crash]: 
[steam-231430.log](https://github.com/ValveSoftware/Proton/files/6056530/steam-231430.log)

Log for Proton 5.13-6 [crash]:
[steam-231430.log](https://github.com/ValveSoftware/Proton/files/6056536/steam-231430.log)

## Symptoms 
Game crashes while loading the level.

## Reproduction
Just try to run the in-game-benchmark, it will crash with the mentioned Proton versions while loading the benchmark.

**Comment by kisak-valve** [comment]
Hello @ms178, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3875#issuecomment-787452450.
