### ISSUE TITLE
"Proton Stable" what is it?

### ISSUE THREAD

**Issue by arrowgent** [ValveSoftware/Proton#4659]
PROTON STABLE

https://i.imgur.com/7qDnj5W.png

a few days ago
this appears under the game property options and in steam settings

what is it and how does it effect proton versioning?

no "fanfare" has come out about it, news or otherwise.

and selecting it as an option doesnt do anything, "compatibility error" when launching game

steamdb shows nothing
https://steamdb.info/search/?a=app&q=proton&type=5&category=0

**Comment by kisak-valve** [comment]
Hello @arrowgent, looks like an experiment which was removed. Nothing to see here.

**Comment by arrowgent** [comment]
youre right, updated and restarted steam

"Proton Stable" is no longer there
