### ISSUE TITLE
Town of Salem (334230)

### ISSUE THREAD

**Issue by ferretwithaberet** [ValveSoftware/Proton#4661]
# Compatibility Report
- Name of the game with compatibility issues: Town of Salem
- Steam AppID of the game: 334230

## System Information
- GPU: GTX1650m Max-Q
- Driver/LLVM version: 460.39-1
- Kernel version: 5.10.18-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): [Click here](https://gist.github.com/ferretwithaberet/b648d4e957106581c4c934baf432a994)
- Proton version: Proton-6.1-GE-2 (Happened with latest and other Proton versions too, but I am currently using this one)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
```bash
ferretwithaberet@ferret-FX505DT in ~
$ tail -f /proc/27621/fd/2
[13568:13568:0302/011829.660891:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: The message port closed before a response was received.", source: chrome://newtab/ (0)
kdeinit5: Got EXEC_NEW '/usr/lib/qt/plugins/kf5/kio/tags.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt/plugins/kf5/kio/tags.so'
kdeinit5: PID 30077 terminated.
kdeinit5: PID 30082 terminated.
kdeinit5: PID 30092 terminated.
kdeinit5: PID 30106 terminated.
kdeinit5: PID 30083 terminated.
kdeinit5: PID 30626 terminated.
Fontconfig error: Cannot load default config file: No such file: (null)
```

## Reproduction
Sometimes, while playing the game, it will randomly freeze.

## Notes
- Will edit to contain the generated steam app log when it happens again.

**Comment by kisak-valve** [comment]
Hello @ferretwithaberet, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1191#issuecomment-788402687.

**Comment by ferretwithaberet** [comment]
> Hello @ferretwithaberet, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#1191 (comment)](https://github.com/ValveSoftware/Proton/issues/1191#issuecomment-788402687).

I am sorry, I saw that issue, I thought I should make a new one because that was a whitelist request. Thank you for transferring it for me.
