### ISSUE TITLE
Loop Hero (1282730)

### ISSUE THREAD

**Issue by LoreRealm** [ValveSoftware/Proton#4671]
# Compatibility Report
- Name of the game with compatibility issues: Loop Hero
- Steam AppID of the game:1282730

## System Information
- GPU: AMD RADEON RX 6800XT
- Driver/LLVM version: MESA 20.3.4
- Kernel version: 5.11.2-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/lorddickfist/9ecddbe3832d27ac7bb11f3ea3aef116):
- Proton version: 5.13 and experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1282730.log](https://github.com/ValveSoftware/Proton/files/6126522/steam-1282730.log)
[steam-1282730-experimental.log](https://github.com/ValveSoftware/Proton/files/6126520/steam-1282730-experimental.log)

## Symptoms 
Game crashes after 2 runs approx an hour

## Reproduction
Play the game for two to three runs without dying

**Comment by kisak-valve** [comment]
Hello @lorddickfist, `eventfd: Too many open files` looks like a line of interest from the log. Although unlikely for a current Arch install, can you check [`ulimit -Hn`](https://github.com/ValveSoftware/Proton/wiki/Requirements#fd-limit-requirements-systemd--240) and verify that it gives you a high value and not 4096. Increasing that limit should delay the game's crash.

Setting the game's launch options to `PROTON_NO_ESYNC=1 %command%` or trying an fsync-enabled kernel have a decent chance of having an effect on the game's behavior.

**Comment by LoreRealm** [comment]
> Hello @lorddickfist, `eventfd: Too many open files` looks like a line of interest from the log. Although unlikely for a current Arch install, can you check [`ulimit -Hn`](https://github.com/ValveSoftware/Proton/wiki/Requirements#fd-limit-requirements-systemd--240) and verify that it gives you a high value and not 4096. Increasing that limit should delay the game's crash.
> 
> Setting the game's launch options to `PROTON_NO_ESYNC=1 %command%` or trying an fsync-enabled kernel have a decent chance of having an effect on the game's behavior.

With ulimit -Hn I get "524288" which is definitely higher that 4096. I will try with the no-esync command and if it happens again ill post updated log.

**Comment by LoreRealm** [comment]
> Hello @lorddickfist, `eventfd: Too many open files` looks like a line of interest from the log. Although unlikely for a current Arch install, can you check [`ulimit -Hn`](https://github.com/ValveSoftware/Proton/wiki/Requirements#fd-limit-requirements-systemd--240) and verify that it gives you a high value and not 4096. Increasing that limit should delay the game's crash.
> 
> Setting the game's launch options to `PROTON_NO_ESYNC=1 %command%` or trying an fsync-enabled kernel have a decent chance of having an effect on the game's behavior.

Esync Fixes the issue for sure, closing issue. Thanks again!
