### ISSUE TITLE
Sniper ELite V2 Doesn't launcher!

### ISSUE THREAD

**Issue by AndyMxM** [ValveSoftware/Proton#4676]
# Compatibility Report
Sniceper Elite V2 Doens't launch
- Steam AppID of the game: 63380

## System Information
- GPU: GTX 1050
- Driver/LLVM version: NVIDIA-DIRVER 460(propietary)
- Kernel version: 5.4.0-67-generic
- Link to full system information report as [Gist](https://gist.github.com/)
-  (https://gist.github.com/AndyMxM/a1fc7e26ed0f73dbbae9597b1c817731#file-steam-63380-log)
- 
- Proton version: 5.13-6

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

(https://gist.github.com/AndyMxM/a1fc7e26ed0f73dbbae9597b1c817731#file-steam-63380-log)

## Symptoms 
I am trying to launch the game Sniper Elite V2, but it trying to load but doesn't work, and even it doesn't show me any error message!

**Comment by kisak-valve** [comment]
Hello @AndyMxM, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/392#issuecomment-801467760.
