### ISSUE TITLE
Outward (794260)

### ISSUE THREAD

**Issue by HenryJk** [ValveSoftware/Proton#4679]
# Compatibility Report
- Name of the game with compatibility issues: `Outward`
- Steam AppID of the game: `794260`

## System Information
- GPU: `GTX 1650 Max-Q`
- Driver/LLVM version: `nvidia 560.56`
- Kernel version: `5.11.7-arch1-1`
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.13-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

`File is too big`

## Symptoms 
Memory leak and performance degradation every time loading new area. It seems that rendered objects are not culled properly when changing area. 

## Reproduction
Start a new game, go in and out of the starter town back and forth. The memory spike is the highest the first time going out and in the starter town.

**Comment by kisak-valve** [comment]
Hello @HenryJk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2506#issuecomment-803109142.

As a side note, Proton logs compress fairly well in an archive if you need to reduce their size.
