### ISSUE TITLE
Elder Scrolls Online, Zenimax Free Space Error / Directory Not Writable

### ISSUE THREAD

**Issue by jmgant** [ValveSoftware/Proton#4682]
# Compatibility Report
- Name of the game with compatibility issues: Elder Scrolls Online
- Steam AppID of the game: 306130

## System Information
- GPU: GTX 1650
- Driver/LLVM version: nvidia 460.56
- Kernel version: 5.11.7-zen1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/jmgant/a1ebe8e180b4c61661994c9575d5646f
[steam-346110.log](https://github.com/ValveSoftware/Proton/files/6176252/steam-346110.log)

- Proton version: All
[steam-346110.log](https://github.com/ValveSoftware/Proton/files/6176226/steam-346110.log)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When I launch the game with Proton Experimental, the Zenimax installer says I only have 3GB available while I have over 1TB and won't install. When I launch with older Proton versions, the free space is reported correctly, however the Zenimax installer says the path to the game is not writable. I assure you it is, or has been made so.

I had this game on this system running at first. I removed it from an old, small drive, and it is only upon the reinstall that this has happened.

[steam-346110.log](https://github.com/ValveSoftware/Proton/files/6176234/steam-346110.log)

**Comment by kisak-valve** [comment]
Hello @jmgant, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/556#issuecomment-803453152.
