### ISSUE TITLE
Rhythm Doctor (774181)

### ISSUE THREAD

**Issue by huantianad** [ValveSoftware/Proton#4686]
# Compatibility Report
- Name of the game with compatibility issues: Rhythm Doctor
- Steam AppID of the game: 774181

## System Information
- GPU: RTX 2070
- Driver/LLVM version: nvidia 460.56
- Kernel version: 5.11.6
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/huantianad/cababa6f9e4fa55a791b98890e037933
- Proton version: 5.13-6 (also happens on experimental-5.13-20210311)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-774181.log](https://github.com/ValveSoftware/Proton/files/6178199/steam-774181.log)
Also the game log, might be helpful: [Player.log](https://github.com/ValveSoftware/Proton/files/6178200/Player.log)

## Symptoms 
The game has a mechanic where the game goes out of fullscreen and moves its own window around the desktop. This mostly works fine; however, when the game attempts to move off my monitor (to create a screen wrap type of effect), it seems to be "blocked" by the edge of my monitor, and isn't allowed to be partially allowed off my screen. (I'm using KDE Plasma 5.21.3)

## Reproduction
1. Launch the game, and either enter an official level with window dance (i.e. 2-X, 4-1N).
2. Play the level, and observe the window movement when it attempts to wrap around the screen or go off the screen.
(this can also be observed with custom levels with window dance, you can reproduce it with a simple "wrap" event)

**Comment by KiteAB** [comment]
unsolved issue

**Comment by huantianad** [comment]
This could be a KDE specific issue; testing with a separate program, the window seems to be prevented from leaving the screen if not already off the screen

**Comment by Saraistupid** [comment]
> This could be a KDE specific issue; testing with a separate program, the window seems to be prevented from leaving the screen if not already off the screen

KWin does stop that from happening unless the `wmctrl` command is used to move the window

**Comment by kisak-valve** [comment]
If any window manager outright does not allow application windows to be placed in inaccessible locations, then that behavior is something to discuss with the developers of that desktop environment. Proton should not use abusive methods to override that.

**Comment by huantianad** [comment]
@kisak-valve Makes sense, closing this issue since it's not necessarily Proton related.

@Saraistupid You seem to know more about this, have you filed an issue with KDE/KWin?

**Comment by Saraistupid** [comment]
> @Saraistupid You seem to know more about this, have you filed an issue with KDE/KWin?

nope, i haven't, didn't bother tbh since i'm not affected by this
