### ISSUE TITLE
Grand Theft Auto: Vice City - black screen

### ISSUE THREAD

**Issue by ropromei** [ValveSoftware/Proton#4687]
# Compatibility Report
- Name of the game with compatibility issues: Grand Theft Auto: Vice City
- Steam AppID of the game: 12110

## System Information
- GPU:  Intel HD Graphics 520
- Driver/LLVM version:  4.6 Mesa 20.2.6
- Kernel version:  5.4
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ropromei/67b49d992e2126d053ed5bcb8694eb79
- Proton version: Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
When starting the game, the screen is black but there are sounds playing when pushing arrow keys (I assume the main menu is open).

**Comment by kisak-valve** [comment]
Hello @ropromei, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/291#issuecomment-803999005.
