### ISSUE TITLE
Crashing issues with WarFrame.

### ISSUE THREAD

**Issue by TildeEthDoUsPart** [ValveSoftware/Proton#4689]
# Compatibility Report
- Name of the game with compatibility issues: Warframe
- Steam AppID of the game: 230410

## System Information
- GPU: GTX 1060
- Driver/LLVM version: Nvidia 450.80.02
- Kernel version: 4.19.0
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ThatDamGuy/09a65c2a6c954b26f663450b754aeee2
- Proton version: All have been tried, currently on Proton Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
The game keeps closing to desktop after a few minutes of playing. When I restart the game, the Warframe Issue report wondow opens and asks me to describe the problem, then sends the data to the tracker system. The game starts normally, the launcher doesn't crash, but nothing I do seems to work as it will inevitably crash after a few minutes.

## Reproduction
Unknown.

As the proton log is 67MB large, I was forced to split the log into 14 smaller parts.
[file00.txt](https://github.com/ValveSoftware/Proton/files/6189762/file00.txt)
[file01.txt](https://github.com/ValveSoftware/Proton/files/6189763/file01.txt)
[file02.txt](https://github.com/ValveSoftware/Proton/files/6189764/file02.txt)
[file03.txt](https://github.com/ValveSoftware/Proton/files/6189765/file03.txt)
[file04.txt](https://github.com/ValveSoftware/Proton/files/6189766/file04.txt)
[file05.txt](https://github.com/ValveSoftware/Proton/files/6189768/file05.txt)
[file06.txt](https://github.com/ValveSoftware/Proton/files/6189769/file06.txt)
[file07.txt](https://github.com/ValveSoftware/Proton/files/6189770/file07.txt)
[file08.txt](https://github.com/ValveSoftware/Proton/files/6189771/file08.txt)
[file09.txt](https://github.com/ValveSoftware/Proton/files/6189772/file09.txt)
[file10.txt](https://github.com/ValveSoftware/Proton/files/6189774/file10.txt)
[file11.txt](https://github.com/ValveSoftware/Proton/files/6189775/file11.txt)
[file12.txt](https://github.com/ValveSoftware/Proton/files/6189777/file12.txt)
[file13.txt](https://github.com/ValveSoftware/Proton/files/6189779/file13.txt)
[file14.txt](https://github.com/ValveSoftware/Proton/files/6189780/file14.txt)

**Comment by kisak-valve** [comment]
Hello @ThatDamGuy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/167#issuecomment-804910805.
