### ISSUE TITLE
Normal fixes for Skyrim SE's audio not working.

### ISSUE THREAD

**Issue by nstgc** [ValveSoftware/Proton#469]
Trying to get Skyrim SE to run with Proton. I have installed xact, used winecfg --force xact, and tried combinations of setting xaudio2_6 and 2_7 to native. This has allowed me to get past the opening wagon scene, however audio kind of dies after the dragon lands which breaks scripted events. From everything I've found, this should work, but it doesn't.

Note that I've only used Proton for all of this (by specifying the full path to the binary) until this most recent attempt where I used wine64 to "update" the prefix using local wine (3.13)

I'm on Arch Linux.

**Comment by kisak-valve** [comment]
Hello @nstgc, we'll be using one issue report per unofficially supported game, so I've gone ahead and transferred this issue to https://github.com/ValveSoftware/Proton/issues/4#issuecomment-415920335.
