### ISSUE TITLE
Bug GTAV online

### ISSUE THREAD

**Issue by jeremy99981** [ValveSoftware/Proton#4698]
Hello, I found a bug in proton GE or the online mode of GTA V on the Rockstar launcher unfortunately does not work! Unable to find people, join or other in the online mode

**Comment by kisak-valve** [comment]
Hello @jeremy99981, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-808561442.
