### ISSUE TITLE
Brawlhalla

### ISSUE THREAD

**Issue by DarkArc** [ValveSoftware/Proton#470]
Brawlhalla works well, with the exception of one issue. You have to put it into windowed mode, and not resize it, otherwise the game area won't render.

For instance with default full screen gameplay, you'll see nothing but a black screen. If you change to windowed mode, restart the game, and then play, everything will render/work properly.

**Comment by kisak-valve** [comment]
Hello @DarkArc, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue to https://github.com/ValveSoftware/Proton/issues/83#issuecomment-415920568.

**Comment by DarkArc** [comment]
Oh sorry, I didn't see that! :man_facepalming:
