### ISSUE TITLE
Joystick not detected under American Truck Simulator

### ISSUE THREAD

**Issue by writequit** [ValveSoftware/Proton#4703]
# Compatibility Report
- Name of the game with compatibility issues: American Truck Simulator
- Steam AppID of the game: 270880

## System Information
- GPU:  nvidia 1080 Ti
- Driver/LLVM version: 460.67
- Kernel version: 5.10.26
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/writequit/93729b5000f216e3c3062df5e8fceb9d
- Proton version: 5.13-6
[steam-270880.log](https://github.com/ValveSoftware/Proton/files/6218103/steam-270880.log)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

I have a range/splitter attachment for the gearshift (Logitech G29), it's an arduino device that shows up as /dev/input/js0 and /dev/input/event3. It has 3 buttons and works under linux version of ATS but is not detected whe running ATS with proton. Using different joystick testing utilities it works from both js and event interfaces.

Running this command brings up the windows joystick widget and it shows the 3 button presses ok:

WINEPREFIX=/home/geoff/.steam/steam/steamapps/compatdata/270880/pfx /home/geoff/.steam/steam/steamapps/common/Proton\ 5.13/dist/bin/wine64 control joy.cpl

I'm trying ATS under proton as it brings some additional functionality e.g. VR, trackIP, truckersMP and also a lot of modders don't process textures correctly and they appear black under the opengl client. ATS itself runs well under proton, possibly better than the native client.

## Reproduction

Could possibly reproduce the issue with an ordinary joystick, it should show up as an available input device.

**Comment by kisak-valve** [comment]
Hello @writequit, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4380#issuecomment-808963684.
