### ISSUE TITLE
[Whitelist] Jamestown (94200)

### ISSUE THREAD

**Issue by diegogangl** [ValveSoftware/Proton#471]
Game runs pefect, gamepad and achivements work too.

- Ubuntu 16.04 (KDE Neon)
- GTX 980
- Nvidia drivers 396.51
- Kernel 4.15.0

**Comment by Faalagorn** [comment]
Not directly related, and nothing Valve can do directly but instead something dev should do, but it may be worth adding that Jamestown also work with native files with distributed with Humble Bundle (or Groupees) and apparently achievements work too. More info [here](https://www.reddit.com/r/linux_gaming/comments/5yf5sn/drmfree_version_of_jamestown_can_use_steam/).

**Comment by swick** [comment]
Can confirm. No problems.

    OpenGL renderer string: AMD Radeon(TM) HD 8800 Series (PITCAIRN, DRM 3.26.0, 4.18.0, LLVM 6.0.1)
    OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.1.6

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.
