### ISSUE TITLE
nVidia Driver Prompt Doom Eternal

### ISSUE THREAD

**Issue by DarkXero-dev** [ValveSoftware/Proton#4716]
Hey

Using any Proton version but as of this post using Proton-GE-Custom-6.5 a keep getting prompted to update nVidia Drivers on game launch . Clicking Play I can play game but performance is less than 100%.. I already have latest drivers 460+ dunno why this has never been resolved... Proton detects v360+ of nVidia though I have 460+

Am on Arch KDE BTW...

**Comment by kisak-valve** [comment]
Hello @TechXero, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3773#issuecomment-811916689.
