### ISSUE TITLE
Improve Proton uninstall UX

### ISSUE THREAD

**Issue by DanMan** [ValveSoftware/Proton#4720]
This is from the terminal when trying to uninstall v5.13:

```
GameAction [AppID 1420170, ActionID 1] : UninstallApps waiting for user response to ConfirmUninstall "1420170"
GameAction [AppID 1420170, ActionID 1] : UninstallApps continues with user response "ConfirmUninstall"
GameAction [AppID 1420170, ActionID 1] : UninstallApps changed task to StartNextApp with ""
GameAction [AppID 1420170, ActionID 1] : UninstallApps changed task to InstallScript with ""
GameAction [AppID 1420170, ActionID 1] : UninstallApps changed task to RemoveFromOS with ""
GameAction [AppID 1420170, ActionID 1] : UninstallApps changed task to WaitRunning with ""
App ID 311340 depends on compatibility tool 1420170, cannot uninstall!GameAction [AppID 1420170, ActionID 1] : UninstallApps failed with AppError_17 with ""
```

I wouldn't have known it's because of "App ID 311340", if I hadn't started Steam from the terminal. It also stops trying after the first one. So if there are multiple games depending on that Proton version, you won't know until you've tried uninstalling again and it failing with a different AppId again.

The Steam UI only complains about an "unexpected error".

**Comment by kisak-valve** [comment]
Hello @DanMan, this is an issue with the Steam client, not Proton itself, and is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/7407. Closing as a duplicate.
