### ISSUE TITLE
RPG Maker MZ doesn't work on current version of proton

### ISSUE THREAD

**Issue by whitequill** [ValveSoftware/Proton#4722]
# Compatibility Report
- Name of the game with compatibility issues: RPGMaker MZ
- Steam AppID of the game: 1096900

## System Information
- GPU: nVidia GTX 1080
- Driver/LLVM version: OpenGL version string: 4.3 (Compatibility Profile) Mesa 20.3.5
- Kernel version: 5.11.10-200.fc33.x86_64
- https://gist.github.com/whitequill/fab4d5eff6c7d0a92f5574bd14c7ef8d
- Proton version: 4.11-13

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

I can't get a proton log 
## Symptoms 
RPG Maker MZ only works on this old version of Proton (4.11-13) and only exclusively if you use beta version 1.0.2 or 1.1.1 of RPG Maker MZ.
I would like to see it running on version 6+. I want to make sure that it is given attention so it can be used in up to date versions.

There is a small issue that when running a playtest it gives an error: "Failed to initialize graphics". Otherwise MZ is completely unusable in all other versions of Proton. 

## Reproduction
Download RPG Maker MZ and try and run it with any other version of proton. it failed to run and crashed prematurely for me.

**Comment by kisak-valve** [comment]
Hello @whitequill, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4185#issuecomment-812496274.
