### ISSUE TITLE
ASTRONEER freezes on startup in Proton 6.3

### ISSUE THREAD

**Issue by Captain-Rage** [ValveSoftware/Proton#4726]
# Compatibility Report
- Name of the game with compatibility issues: ASTRONEER
- Steam AppID of the game: 361420

## System Information
- GPU: AMD Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.11.11-arch1-1, LLVM 11.1.0)
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 21.0.1
- Kernel version:  5.11.11-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): "https://gist.github.com/Captain-Rage/d37ad485fd98f412567249af8ca41925.js"
- Proton version: 6.3-1

## I confirm:
- [y ] that I haven't found an existing compatibility report for this game.
- [y] that I have checked whether there are updates for my system available.

## Symptoms 
When starting ASTRONEER using Proton 6.3 a test card screen is shown for a brief moment, the loading bar appears, the main shows but freezes immediately and the game cannot be closed gracefully and has to be terminated. ASTRONEER was working fine in Proton 5.13.

## Reproduction
Start ASTRONEER using Proton 6.3.

**Comment by kisak-valve** [comment]
Hello @Captain-Rage, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/243#issuecomment-812559582.
