### ISSUE TITLE
[Feature Request] Warn users when the prefix directory of a game is about to be deleted or modified

### ISSUE THREAD

**Issue by steffenWi** [ValveSoftware/Proton#4727]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description
When Steam/Proton is about to delete or modify the compatdata folder of a game it should display a warning or confirmation message to give the user some time to save data that a game or application might store in the prefix.

Use case: When I switched from Proton 5.13 to 6.3 today and started Beatsaber the files in _steamapps/compatdata/620980/pfx/drive_c/users/steamuser/AppData/LocalLow/Hyperbolic Magnetism/Beat Saber_ were deleted. This is where it stores the configuration, the amount of times a level was played, campaign process... while this is a minor annoyance in Beatsaber, losing these files would be very annoying for story based games that store save files inside the prefix.

## Justification
I've never seen Wine delete the files of a game inside a prefix.

**Comment by aeikum** [comment]
That definitely shouldn't happen. Sounds like a bug. We try not to destroy files that Proton didn't create.

**Comment by steffenWi** [comment]
huh. I thought that switching from one Proton version to another on an installed game could cause this. However, I now also tried a few other games and I didn't observe that behavior on any of them. Closing this 'cause whatever caused this wasn't Proton. Probably the game itself did something weird.

**Comment by class101** [comment]
This issue should not be closed. My prefix got deleted today

- I uninstalled a few Proton games
- On a game offered in Windows and Linux, I switched a few time compat option on/off to download Windows vs Linux

Anyway yes, this shouldn't happen , I lost several save files, very disappointing.

**Comment by class101** [comment]
I have opened a newer issue here https://github.com/ValveSoftware/Proton/issues/4774
