### ISSUE TITLE
Proton 6.3-1 input stuttering

### ISSUE THREAD

**Issue by Eonfge** [ValveSoftware/Proton#4734]
# Compatibility Report
- Multiple games observed: Quake Champions, Amid Evil
- Multiple games observed: 611500, 673130

## System Information
- GPU: NVidia GTX 970
- Driver/LLVM version: NVidia version 460.67
- Kernel version: 5.11.11-200.fc33.x86_64
- https://gist.github.com/Eonfge/5ed01a898dfacf502654ef00e943eca4
- Proton version: 6.3-1

## I confirm
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
After some play, anywhere between half an hour and two hours, I notice a significant input stuttering/choppiness. With Mango Hud, I can deduct that it's not something FPS or frametime related and I've also checked for background tasks that could potentially ruin things.

Based on feedback, it seems to be that this is a regression:
https://github.com/ValveSoftware/Proton/issues/3316

## Reproduction
1. Unclear yet. I have been able to log it at least once, but it's not very consistent.

## Logs
- [steam-673130.log](https://github.com/ValveSoftware/Proton/files/6252661/steam-673130.log)

**Comment by heav-4** [comment]
i can confirm this happens on Risk of Rain 2 and Scrap Mechanic.

**Comment by Mushoz** [comment]
I am not sure if this is the same issue, but after playing for a while (30 minutes to 2 hours is a good estimate for me as well), mouse input gets really poor and stuttery. I ran into the issue with both RDR2 (which I could fix by switching to a software cursor) and Amnesia: Rebirth (Didn´t have a software cursor option, so restarting was the only fix). Happening for me under 6.3-1 proton as well.

**Comment by thulle** [comment]
Same issue in Natural Selection 2 here, it's like issue #3316 reappeared. Mouse input seems to drop to a ~4Hz pollrate which makes for insane amounts of stutter when looking around.

**Comment by Mushoz** [comment]
Yes, a 4hz pollrate seems best to describe my experience as well once this bug is triggered.

**Comment by nutta-git** [comment]
I think I am also facing this issue. 
While playing Doom 2016 the mouse movement feels choppy. It usually take effect after playing a while(30+ mins). 
frame rate seems stable; however, the mouse movement feels extremely choppy. 
[gist.txt](https://github.com/ValveSoftware/Proton/files/6255396/gist.txt)

**Comment by imaami** [comment]
Got this in Squad as well.

Initially it does feel as if the input poll rate drops to a constant 5-10 Hz (not really 4 Hz IMHO), but I don't think I'm seeing what I'd expect in that case. I get a slideshow, but I don't remember noticing motion blur between the frames although it's enabled in-game. If it were just relatively large jumps in mouse input then wouldn't the frame postprocessing add a noticeable amount of "blur streaks"?

I'm not 100% sure though. I need to run a test with in-game blur maxed out and see what happens. Maybe it's input stutter and UE4 handles long input intervals as if recovering from a network lag spike, i.e., a quick screen update with minimal postproc?

**Comment by Zorrototo** [comment]
Happened in Killing Floor 2 and Phasmophobia, probably happens on all games. It is like mouse input is refreshed every time you move 50 pixels so it moves very 'blocky' like it reposition mouse only after a specific movement threshold.

**Comment by Eonfge** [comment]
For people sharing this experience, make a gist with your Steam: System Information so we can gather all the data. It might be combination of hardware and drivers, like a missing VK_ extension, so give all the info you can. It takes only a minute or two, but speaking from experience, it really helps in fixing bugs.

**Comment by dennis1248** [comment]
I have experienced the bug in Halo MCC and Subnautica. The bug appears to occur randomly typically after 15 minutes - 1 hour of play.

[System information gist](https://gist.github.com/dennis1248/0f99db8d17690bd8d0dcd515ae0c7a2c)

I doubt it's a system config issue, looks a lot more like a WINE bug to me.

**Comment by Zorrototo** [comment]
Here is my sys info https://gist.github.com/Zorrototo/a66b5307ae5deced2352dfa41a786846

**Comment by Corben78** [comment]
I'm experiencing an input lag of my mouse after a while in Death Stranding. Game itself runs smooth (as shown with MangoHud, solid 60 FPS). It's like the mouse would snap into certain positions (similar to turning in VR with snap turning) when looking around.

**Comment by karsonatorz** [comment]
I am also experiencing mouse stutters after a while of playing on 6.3-1

rx 580 ryzen 5 1600x
manjaro linux 21 ornara
confirmed in mordhau and natural selection 2

**Comment by xpander69** [comment]
confirming the bug. It also happens when you run scripts with recent enough wine version through steam as non-steam game.
for example wine-staging 6.2 to 6.5

short video of warhammer online run through a script inside steam client (sadly didn't have mangohud enabled)
https://www.youtube.com/watch?v=QrqKAoyw12g

happens after 1+ hour of playing, but only when launched through steam.

LD_PRELOAD="" seems to work around this nasty issue for now.

from the VKx discord it looks like its already known what causes it. something to do with explorer.exe and PE builds of dlls that interact with the steamoverlay or something along those lines.

**Comment by Eonfge** [comment]
> LD_PRELOAD="" seems to work around this nasty issue for now.

I tried that with Amid Evil but it seemed to reintroduce this bug: https://github.com/ValveSoftware/Proton/issues/4577

Clearing the LD_PRELOAD can be a nice workaround (looking at you, Civilization) but generally speaking it's a bad idea. Perhaps somebody else can try it with another game and have more success.

**Comment by raQai** [comment]
Can we please properly define which issue we try to describe here and change the title accordingly?
Input lag and mouse stuttering/choppy mouse movement are two completely different topics and ppl searching for the latter will most likely not be able to find this issue.

@Eonfge Can you verify whether you reported this issue due to stuttering or input lag and change the title accordingly?
Also if this is related to stuttering, could you mention #3316 in the initial report since this is most likely a regression (if this was fixed at some point after 4.11-10 which I dont know).

**Comment by raQai** [comment]
Here is my steam info: https://gist.github.com/raQai/37a4554130250b9be9dab9e1be824e9f

Stuttering also occurs in Borderlands 1 and 2 (probably also Borderlands The Pre-Sequel).
Proton 6.5-GE-1 (and earlier Proton 5.X-GE versions) seems to have this issue fixed although inputs seem to multiply there (keyboard inputs in menus sometimes trigger two or more times, also mouse sensitivity is extremly high compared to expected values).

**Comment by Zorrototo** [comment]
@raQai  it is neither stuttering nor input lag. It is like the mouse teleports itself after you have moved a specific threshold, like it has been said the mouse snaps in places when you move it, it doesn't follow the real mouse movement but it snaps like on a grid.
And what do you know? the thread you linked which is the same old issue reappearing, also has "mouse stutter/lag" in its title so I guess this title will not be a problem either.

**Comment by DrShadow34** [comment]
Same here with Mordhau on Arch Linux via Proton 6.3-1
Is there any chance we at least have workaround for now?
Also, mouse filtering in game kinda works, but that not an ideal solution even for now.

**Comment by Bumbadawg** [comment]
Confirming Quake Champions.

**Comment by Zorrototo** [comment]
> Is there any chance we at least have workaround for now?

Go back to Proton 5.13

**Comment by aeikum** [comment]
Thanks all for reporting. We understand the problem and hope to have a fix soon. In the meantime, Proton 5.13 is unaffected, as @Zorrototo said.

**Comment by Eonfge** [comment]
@aeikum Sounds like a plan. Let us know when you got a patch and we can run it through the gauntlet.

**Comment by aeikum** [comment]
Hey everyone. I've uploaded a build that will hopefully fix this on the "next" branch of the Proton 6.3 app. Please give it a try and report back if it is working correctly for you.

**Comment by Eonfge** [comment]
@aeikum Seems to be fine for me with 6.3-2-rc1. Others will have to confirm, but input stuttering seems te be gone.

**Comment by iWeaker** [comment]
@aeikum  The problem was solved, but now in Alan Wake, when wanting to exit the game, it freezes, after a minute I have to force it to exit.
It did not happen before updating to this beta, 
Not even in the experimental version
[steam-108710.log](https://github.com/ValveSoftware/Proton/files/6267166/steam-108710.log)

**Comment by kisak-valve** [comment]
Hello @iWeaker4you, that sounds like a note to add to the Alan Wake compatibility report since that isn't directly linked to the issue being tracked here.

**Comment by thulle** [comment]
Earlier the issue appeared within 30-60minutes. Now I've played using 6.3-next for 3½hours without triggering it. Seems solved.

**Comment by gbschenkel** [comment]
Proton Experimental is Proton 6? I am having this problem on World of Warships, after 3 or 4 games, like 40min of game play, the  game start to stuttering when moving the mouse, I need quit and enter the game again.

**Comment by Zorrototo** [comment]
Proton experimental is its own branch.

**Comment by FeralBytes** [comment]
Same stuttering on mouse input noticeable when looking around in game, only happens after an hour or so of play. 
Noticeable in ARK: Survival Evolved, but I did not yet notice it in Horizon Zero Dawn, both are using Proton 6.3.1.
Linux Mint 20.1 x64

<details><summary>System information</summary><p>

```
System:    Kernel: 5.4.0-70-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.8.6 
           wm: muffin dm: LightDM Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
Machine:   Type: Desktop Mobo: ASRock model: X570 Pro4 serial: <filter> BIOS: American Megatrends 
           v: P3.20 date: 08/11/2020 
CPU:       Topology: 12-Core model: AMD Ryzen 9 3900X bits: 64 type: MT MCP arch: Zen 
           L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 182063 
           Speed: 2195 MHz min/max: 2200/3800 MHz Core speeds (MHz): 1: 2196 2: 2196 3: 3334 
           4: 2000 5: 2196 6: 2195 7: 2196 8: 2305 9: 2024 10: 2039 11: 2000 12: 2014 13: 2195 
           14: 2291 15: 2038 16: 4289 17: 2139 18: 2933 19: 2122 20: 2056 21: 1918 22: 1865 
           23: 2312 24: 1915 
Graphics:  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] vendor: ASRock 
           driver: amdgpu v: 5.6.20.20.45 bus ID: 0a:00.0 chip ID: 1002:731f 
           Display: x11 server: X.Org 1.20.9 driver: amdgpu,ati 
           unloaded: fbdev,modesetting,radeon,vesa tty: N/A 
           OpenGL: renderer: AMD Radeon RX 5700 XT v: 4.6.14756 Core Profile Context 20.45 
           compat-v: 4.6.14756 direct render: Yes 
Audio:     Device-1: AMD Navi 10 HDMI Audio driver: snd_hda_intel v: kernel bus ID: 0a:00.1 
           chip ID: 1002:ab38 
           Device-2: AMD Starship/Matisse HD Audio vendor: ASRock driver: snd_hda_intel v: kernel 
           bus ID: 0c:00.4 chip ID: 1022:1487 
           Sound Server: ALSA v: k5.4.0-70-generic 
Network:   Device-1: Intel I211 Gigabit Network vendor: ASRock driver: igb v: 5.6.0-k port: f000 
           bus ID: 04:00.0 chip ID: 8086:1539 
           IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 953.87 GiB used: 566.81 GiB (59.4%) 
           ID-1: /dev/nvme0n1 vendor: Intel model: SSDPEKNW010T9 size: 953.87 GiB speed: 31.6 Gb/s 
           lanes: 4 serial: <filter> 
Partition: ID-1: / size: 901.23 GiB used: 565.43 GiB (62.7%) fs: ext4 dev: /dev/nvme0n1p5 
           ID-2: swap-1 size: 37.25 GiB used: 1.37 GiB (3.7%) fs: swap dev: /dev/nvme0n1p1 
Sensors:   System Temperatures: cpu: 41.5 C mobo: N/A gpu: amdgpu temp: 56 C 
           Fan Speeds (RPM): N/A gpu: amdgpu fan: 0 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/amdgpu-pro-local.list 
           1: deb [ trusted=yes ] file: /var/opt/amdgpu-pro-local/ ./
           Active apt repos in: /etc/apt/sources.list.d/lutris-team-lutris-focal.list 
           1: deb http: //ppa.launchpad.net/lutris-team/lutris/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/mono-official-stable.list 
           1: deb https: //download.mono-project.com/repo/ubuntu stable-focal main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com ulyssa main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/vscode.list 
           1: deb [arch=amd64,arm64,armhf] http: //packages.microsoft.com/repos/code stable main
           Active apt repos in: /etc/apt/sources.list.d/zerotier.list 
           1: deb http: //download.zerotier.com/debian/xenial xenial main
Info:      Processes: 439 Uptime: 2d 10h 51m Memory: 31.29 GiB used: 21.51 GiB (68.7%) 
           Init: systemd v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 
           Client: Unknown python3.8 client inxi: 3.0.38 
```

</p></details>

https://termbin.com/c059

**Comment by Eonfge** [comment]
> Proton Experimental is Proton 6? I am having this problem on World of Warships, after 3 or 4 games, like 40min of game play, the game start to stuttering when moving the mouse, I need quit and enter the game again.

@gbschenkel No, you'll have to go to Proton 6.3, preferences and then under beta's you can select 'Next'. It also wasn't completely clear to me initially, but from Steam's point of view Proton 5.13, 6.1, and Experimental are different products. To test something related to a specific version, you'll have to use the build-in beta system.

**Comment by aeikum** [comment]
Thanks all for reporting and retesting. I've just pushed that build live on the Proton 6.3 app.  The Experimental app should be updated later today.

**Comment by aeikum** [comment]
The fix is now also on the Experimental branch.

**Comment by unquote7083** [comment]
Thanks @aeikum, how was this fixed (what commit/change)?

**Comment by FeralBytes** [comment]
Just commenting back that the fix works for ARK: Survival Evolved. Thanks @aeikum

**Comment by aeikum** [comment]
@slmb3 See `git log proton-wine-6.3-1..proton-wine-6.3-2` in the wine submodule.

`Moderator addition:` https://github.com/ValveSoftware/wine/compare/proton-wine-6.3-1...proton-wine-6.3-2
