### ISSUE TITLE
Potential trojan distributed by Steam via Proton Experimental

### ISSUE THREAD

**Issue by RealTehreal** [ValveSoftware/Proton#4738]
Hey folks,

the current Proton Experimental version distributed by Steam has iexplore.exe with potential trojan infection included.
[https://www.virustotal.com/gui/file/e46d083ba31a8d51796b5191bead6d0a9f12cc7564f0ac7b300b0697c1840c44/detection](https://www.virustotal.com/gui/file/e46d083ba31a8d51796b5191bead6d0a9f12cc7564f0ac7b300b0697c1840c44/detection)

Maybe it's a false positive but there are quite some anti virus engines reacting to this file.

Greets

**Comment by chayleaf** [comment]
FWIW so does regular Wine iexplore.exe https://www.virustotal.com/gui/file/3f1c3c96646b8d4e9fe43784bc2a47e6a451ab01104d0aa2de4b0de742708a63/detection

**Comment by Bumbadawg** [comment]
sounds like an .exe doesn't correspond to Windows official signatures. Nothing alarming mate.

**Comment by RealTehreal** [comment]
I see. First time this happened  at my end though.

**Comment by Bumbadawg** [comment]
You run virustotal on your PC files on Linux ?

**Comment by RealTehreal** [comment]
I run nod32 which found the file in question suspicious. I then used virustotal to see what other engines think about the file.

**Comment by Bumbadawg** [comment]
[Seems like Windows Defender exists even on Linux nowadays](https://www.microsoft.com/en-us/microsoft-365/security/endpoint-defender?ocid=cx-blog-mmpc). Maybe this one should know which operating system the analyzed ieplorer.exe is running.

**Comment by aeikum** [comment]
The switch to PE files has set off a lot of anti-virus checkers, unfortunately. There's not much to be done about it other than report the false positives to the vendors.

**Comment by RealTehreal** [comment]
I see. That's what I already did.
