### ISSUE TITLE
No games launch.

### ISSUE THREAD

**Issue by 143mailliw** [ValveSoftware/Proton#474]
When I try to launch any game, it does not launch. I am on Manjaro Linux, with NVDIA driver 396.51

**Comment by Sanaki** [comment]
Have you checked that you fulfill all of the prerequisites?
https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md

Pay close attention to the last section in particular, regarding esync.

**Comment by 143mailliw** [comment]
Yes. It turns out that games only work and installs prereqs like vc *when installed*. If there is an existing folder with the game downloaded and it is in the library, when you try to launch it nothing happens. You need to install the game fresh. I suppose when first ran it should install prerequisites regardless if the game was already downloaded or not.

**Comment by Sanaki** [comment]
I've moved dozens of games over from my windows system manually over the last couple days (including manifests of course) and they install dependencies on first run. Not really sure what to tell you there.

**Comment by kust2708** [comment]
Did you install your Windows games on NTFS disk ? If this is the case, check if you're the owner.
I had a problem at first using NTFS disk. I just add uid and gid on mount settings to fix it.

**Comment by vanyasem** [comment]
I directly added a Steam Library from my Windows partition, so well your point is wrong @ComputeLinux. Can't really help much without logs. Launch Steam from the terminal and capture the output.

**Comment by sir-maniac** [comment]
If you have the games on an NTFS partition, see https://github.com/ValveSoftware/Proton/issues/82#issuecomment-415099440 and https://github.com/ValveSoftware/Proton/issues/35#issuecomment-414935724
