### ISSUE TITLE
Doesn't work with Steam's bundled proton. Tried with [GE's proton 5.9-GE-3-ST](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.9-GE-3-ST). Works flawlessly. Breaks when exiting. Which seems to occur due to some resolution changes.

### ISSUE THREAD

**Issue by sandesh266** [ValveSoftware/Proton#4740]
Doesn't work with Steam's bundled proton. Tried with [GE's proton 5.9-GE-3-ST](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.9-GE-3-ST). Works flawlessly. Breaks when exiting. Which seems to occur due to some resolution changes.

EDIT: Added GE link

_Originally posted by @aki237 in https://github.com/ValveSoftware/Proton/issues/2948#issuecomment-663881255_

**Comment by kisak-valve** [comment]
Closing as out of date information (https://github.com/ValveSoftware/Proton/issues/2948#issuecomment-725939807).
