### ISSUE TITLE
blank screen on opening of cricket 19

### ISSUE THREAD

**Issue by sandesh266** [ValveSoftware/Proton#4741]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @sandesh266, we can't do anything productive with a blank compatibility report template. Please fill out the requested information, then give me a ping and we can ponder this some more.
