### ISSUE TITLE
version conflict in afdko dependencies

### ISSUE THREAD

**Issue by platyple** [ValveSoftware/Proton#4749]
Hey there!

When creating a vm through vagrant, during setup this error pops up:
`debian10: fontparts 0.9.6 has requirement booleanOperations>=0.9.0, but you'll have booleanoperations 0.8.2 which is incompatible. `
Ignoring it leads to `makeotf` not being found during the build process, similar to #4162 
I managed to work around this by removing afdko and manually installing version 2.8.1 through pip, I haven't tried out any later versions.

**Comment by kisak-valve** [comment]
Hello @platyple, this sounds like the afdko issue mentioned at https://github.com/ValveSoftware/Proton/issues/4715#issuecomment-811926932.

**Comment by platyple** [comment]
Sure does, didn't find that one when looking through existing issues. No point in keeping this open, then.
