### ISSUE TITLE
Request: Let us choose to make 32b prefixes.

### ISSUE THREAD

**Issue by nstgc** [ValveSoftware/Proton#475]
Some things (most notably .Net) do not play nice on 64b Wine/Proton/CrossOver. The work around is to use a 32b prefix. Currently what I've done (without knowing if it really worked or not) was to make a prefix in advance with `WINEARCH=win32 WINEPREFIX/path/to/steam/SteamApps/compatdata/gameID/pfx /path/to/proton/wine winecfg`.

**Comment by ahjolinna** [comment]
same as #449

**Comment by kisak-valve** [comment]
Hello @nstgc, this is already being tracked at #449. Closing as a duplicate.
