### ISSUE TITLE
Preserve environment variables when starting proton from shell?

### ISSUE THREAD

**Issue by basenc** [ValveSoftware/Proton#4751]
Game ID: 9420, proton experimental
When starting proton game from shell it doesn't respect environment variables i passed to it via env or export command:
`PROTON_DUMP_DEBUG_COMMANDS=1 PROTON_NO_ESYNC=1`
Tried launching it using url, like steam://run/9420//PROTON_DEBUG_DIR=somedir PROTON_DUMP_DEBUG_COMMANDS=1 PROTON_NO_ESYNC=1 %25command%25/
It showed this dialog, but the game started as if i didnt provided any launch options at all (heavy lags because of esync and no debug output)
![image](https://user-images.githubusercontent.com/26507468/114297713-e9adad00-9aba-11eb-9fde-879a307ec19b.png)
steam -applaunch 9420 PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 PROTON_DUMP_DEBUG_COMMANDS=1 prime-run %command% was useless too
Could try to edit localconfig.vdf, but that solution is a bit hacky and requires a working config parser.
Using steam GUI is not the option.

**Comment by kisak-valve** [comment]
Hello @NIGRELOID, this reads like an issue with the Steam client, not Proton itself, and is already being tracked as a feature request at https://github.com/ValveSoftware/steam-for-linux/issues/6443. Closing in as a duplicate.
