### ISSUE TITLE
Cyberpunk 2077 freezes after a few seconds

### ISSUE THREAD

**Issue by platyple** [ValveSoftware/Proton#4757]
# Compatibility Report
- Name of the game with compatibility issues: Cyberpunk 2077
- Steam AppID of the game: 1091500

## System Information
- GPU: RX 5600 XT
- Driver/LLVM version: Mesa 21.0.2
- Kernel version: 5.11.13
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/platyple/70c1a15633e5de0ee1c4721c618c525e
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1091500.log](https://github.com/ValveSoftware/Proton/files/6320033/steam-1091500.log)

## Symptoms 
Cyberpunk 2077 starts just fine, the text in the Main Menu is invisible and upon loading into the game, it black screens and freezes after a couple seconds.

## Reproduction
Unfortunately this seems specific to my hardware, the issue persists across Proton versions, reinstalling OSes, different distros as well as reinstalling the game and deleting the compatdata folder.
I'm gonna test my current install on different hardware when I get around to it, in the interrim perhaps someone better versed in Proton's logs can find something in the logs.

**Comment by kisak-valve** [comment]
Hello @platyple, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-820603513.
