### ISSUE TITLE
DxDiag seems faulty - Proton 5.13.6

### ISSUE THREAD

**Issue by webaake** [ValveSoftware/Proton#4761]
Proton 5.13.6 - DxDiag always shows a message just after starting World of Warships in Steam. The message is (translated): "Usage: dxdiag[/whql :off]  | [/whql:on] | [/t filename] | [/x filename]"

This is always when starting Wows and has been with version 5.13.6.

The problem is that it really seems to take a lot longer to start the game. Is there a fix for this in Proton? Can I edit some text file and tell Dxdiag to relax?

Wows/Steam/Proton works really wonderful so this is  a small problem. I am very thankful for Proton and how well it works. So thanks for the hard work guys! 

Other info: Ubuntu LTS 18.04, Nvidia 450.102.04

**Comment by kisak-valve** [comment]
Hello @webaake, we're using one issue report per unofficially supported game title, and this reads like game-specific feedback, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/333#issuecomment-822000713.
