### ISSUE TITLE
MGSV:TPP Crashes after second mission

### ISSUE THREAD

**Issue by SirRolls** [ValveSoftware/Proton#4767]
# Compatibility Report
- Name of the game with compatibility issues: Metal Gear Sold V: The Phantom Pain
- Steam AppID of the game:287700

## System Information
- GPU: Quadro P2000
- Driver/LLVM version: Nvidia 465.24.02
- Kernel version: 5.11.15-zen1-2-zen
- [steam-287700.log](https://github.com/ValveSoftware/Proton/files/6346799/steam-287700.log)
- Proton version: Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
After extracting Miller, the ending cutscene plays, but crashes after attempting to load the next

## Reproduction

1. Complete the mission titled "Phantom Limbs"
2. After watching the cutscene at the end, the game will crash

**Comment by kisak-valve** [comment]
Hello @SirRolls, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/124#issuecomment-823626435.
