### ISSUE TITLE
Proton fails to load games unless a terminal is linked to the game

### ISSUE THREAD

**Issue by Lillievela** [ValveSoftware/Proton#4771]
#### Your system information

* Steam client version (build number or date): april 12 2021
* Distribution (e.g. Ubuntu): Manjaro KDE testing 21.0.2-1
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] no (unneeded as i recently updated)

#### Please describe your issue in as much detail as possible:
Whats supposed to happen: Open steam or desktop shortcut from anywhere and play a game that uses proton
What actually happens: proton games do not work unless ran through a terminal that is linked to the game

#### Steps for reproducing this issue:

1. Open steam from anywhere
2. click on the green Play button of your proton game
3. watch it fail 

1. open a terminal and type `steam`
2. when steam launches click the green Play button of the proton game
3. it should run just fine

As for some additional info: getting the direct desktop shortcuts to work is tricky as you need to amend `nohup` to the beginning of the exec command, make sure `terminal` is enabled, run the game, when it runs go back into the shortcut and then disable the terminal and itll run fine, however this doesnt seem to work at all with any steam only shortcuts, just ones with `steam://rungameid/` in it

**Comment by kisak-valve** [comment]
Hello @Lillievela, this reads more like a Proton issue than a Steam client issue, so I've transferred this issue report to the Proton issue tracker.

Mentioned previously at https://github.com/ValveSoftware/Proton/issues/4600#issuecomment-780254679.

**Comment by aeikum** [comment]
I can't reproduce on XFCE with Arch Linux. I tried launching Steam from the XFCE menu, and games running in Proton are working fine. I wonder if this is specific to KDE? Although I feel like more users would be impacted if it was widespread.

**Comment by Lillievela** [comment]
At first i had to use the nohup solution as mentioned, but now everything seems to be just fine and works out of the box aside from trying out which proton version works best for the game, maybe something from before was interring, closing this as it seems to be system specific and random without a reason
