### ISSUE TITLE
Deep Rock Galactic, all long hold actions broken

### ISSUE THREAD

**Issue by maevesechrist** [ValveSoftware/Proton#4773]
Steam AppID: 548430

### System Information
- GPU: GTX 1080
- Driver/LLVM version: 460.67
- Kernel version: 5.11.0-7612-generic
- Proton version: 5.13-6

All hold actions (revive, call for drop pod, etc.) start but immediately start repeating and do not progress. The other hold actions (ex. repair pipeline) work but also repeat the animation. It seems the key is being repeated.

**Comment by kisak-valve** [comment]
Hello @bensechrist, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/284#issuecomment-825234328.
