### ISSUE TITLE
Ape Out (447150) launches but doesn't reach the title screen

### ISSUE THREAD

**Issue by deoxal** [ValveSoftware/Proton#4780]
Game: Ape Out
App ID: 447150

I've seen this issue on a few games now and reading around it seems to mean that a 64 bit process is trying to load gameoverlayrenderer.so but it fails because it was expecting it to also be a 64 bit library.

This happens regardless of Proton version or arguments and is unaffected by switching from my Nvidia card to integrated graphics. What can be done to get the game to progress further?

    ======================
    Proton: 1561645030 proton-4.2-9
    SteamGameId: 447150
    Command: ['/home/user/.steam/debian-installation/steamapps/common/Ape Out/ApeOut.exe']
    ======================
    ERROR: ld.so: object '/home/jjl/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

[System info](https://gist.github.com/deoxal/7ede9d35140a29bcae5d995afb3dab8b)

**Comment by deoxal** [comment]
I tried running the game again and this game got a lot more output.

https://gist.github.com/deoxal/65b9abf0d487e4c26e3703db428dbf52

**Comment by kisak-valve** [comment]
Hello @deoxal, the video driver for your Intel Ivy Bridge generation graphics provide an incomplete implementation of Vulkan, making it unsupported by Proton in general, but setting that aside, your log hints at there being a pulseaudio related issue leading to FMOD failing to initialize:
```
2490.803:0026:0027:err:pulse:pulse_spec_from_waveformat Invalid channel mask: 1/2 and 4(4)
2490.803:0026:0027:err:pulse:pulse_spec_from_waveformat Invalid format! Channel spec valid: 0, format: 3
FMOD failed to initialize. This may be because your sound card is configured to give applications exclusive access, thus preventing Unity from using this device. You can change this in Control Panel > Audio Devices and Sound Themes > Playback Device > Properties > Options ... : "Soundcard does not support the minimum features needed for this soundsystem (16bit stereo output). " (59)
Forced to initialize FMOD to to the device driver's system output rate 44100, this may impact performance and/or give inconsistent experiences compared to selected sample rate 48000
 
(Filename:  Line: 1356)

2490.805:0026:0027:err:pulse:pulse_spec_from_waveformat Invalid channel mask: 1/2 and 4(4)
2490.806:0026:0027:err:pulse:pulse_spec_from_waveformat Invalid format! Channel spec valid: 0, format: 3
FMOD failed to initialize. This may be because your sound card is configured to give applications exclusive access, thus preventing Unity from using this device. You can change this in Control Panel > Audio Devices and Sound Themes > Playback Device > Properties > Options ... : "Soundcard does not support the minimum features needed for this soundsystem (16bit stereo output). " (59)
```

If you go into the game's properties in the Steam Library view, and set the per-game Steam Play override to Proton 6.3-5, does that improve the game's behavior at all?

Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by deoxal** [comment]
I added a link to my system info above.

Changing to version 6.3-5, didn't help but adding `PROTON_USE_WINED3D=1` to the launch options did. The reason I didn't try that before is that I thought for systems without Vulkan support, it would attempt to use OpenGL instead because DDLC and Spelunky launch without having to add the OpenGL launch option.

As for FMOD issue, you were right, and Spelunky has this issue too. For some reason they didn't like that I [mixed the audio channels to make them mono](
https://askubuntu.com/questions/17791/can-i-downmix-stereo-audio-to-mono). Switching back to the original audio device makes audio work fine for both of them.

Thanks for the help, I really appreciate what you do.
