### ISSUE TITLE
After upgrade to Ubuntu 21.04 all steam play games crashes within a minute

### ISSUE THREAD

**Issue by dominikzogg** [ValveSoftware/Proton#4782]
I've upgraded my gaming pc from Ubuntu 20.04 to 20.10 to 21.04. Before all steam play games worked without crashes. While native games still work the steam play games crash within a minute (GTA 5, Tomb Raider - Win Version, Wreckfest)

System: Ryzen 7 5800x, NVIDIA RTX 3070

**Comment by kisak-valve** [comment]
Hello @dominikzogg, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by dominikzogg** [comment]
Hello @kisak-valve 

https://gist.github.com/dominikzogg/1b4f63935ef58c469ff765cec64cb705
GTA V: [steam-271590.zip](https://github.com/ValveSoftware/Proton/files/6389147/steam-271590.zip)
Wreckfest: [steam-228380.zip](https://github.com/ValveSoftware/Proton/files/6389150/steam-228380.zip)
Wreckfest second try: [steam-228380.zip](https://github.com/ValveSoftware/Proton/files/6389227/steam-228380.zip)

Crash means not only the game or steam crashes, but the whole system.

**Comment by dominikzogg** [comment]
The point about native games was false: I tested another linux game (Shadow of a Tomb Raider) today and it crashed too, doesn't seemed to be related to proton.

**Comment by shyam-s00** [comment]
> Hello @kisak-valve
> 
> https://gist.github.com/dominikzogg/1b4f63935ef58c469ff765cec64cb705
> GTA V: [steam-271590.zip](https://github.com/ValveSoftware/Proton/files/6389147/steam-271590.zip)
> Wreckfest: [steam-228380.zip](https://github.com/ValveSoftware/Proton/files/6389150/steam-228380.zip)
> Wreckfest second try: [steam-228380.zip](https://github.com/ValveSoftware/Proton/files/6389227/steam-228380.zip)
> 
> Crash means not only the game or steam crashes, but the whole system.

If the whole system crashes, perhaps something to do with your operating system installation or the hardware may be? Because I'm using 21.04 from day one and never had this...

**Comment by dominikzogg** [comment]
@shyam-s00 operating system then (already reinstall nvidia driver without any success, also tested other kernels), hardware was fine before upgrade

**Comment by Leopard1907** [comment]
@dominikzogg Maybe purge the driver and make sure you're on X, not Wayland etc?

**Comment by dominikzogg** [comment]
@Leopard1907 did that without success.

In the meanwhile i was thinking it could be related to my displaylink (evdi) dock (which worked with the same kernel version). The only difference is that while with the dock the screen freeze incl. the mouse and without the dock the screen freeze but mouse movement is still possible. To me its like a different error handling, but with the same source.

**Comment by dominikzogg** [comment]
Hopefully ubuntu delivers the nvidia-driver-465 soon (the packages from nvidia doesn't work, cause missing i386 support).

**Comment by dominikzogg** [comment]
I close this issue, cause i don't think its proton related atm.

**Comment by dominikzogg** [comment]
It seems it had nothing todo with the upgrade. After the upgrade i've tested all the games, also those which i did not start a while ago. Some games had issue with a minimal overclocking of gpu and instead of a game crash, what i would expect, the whole system crashed.
