### ISSUE TITLE
Eternal Return: Black Survival (#1049590): After 0.31.0/0.31/0a patch, game crashes with Fatal error: "Failed to load il2cpp"

### ISSUE THREAD

**Issue by tacklebox8** [ValveSoftware/Proton#4783]
# Compatibility Report
- Name of the game with compatibility issues: Eternal Return: Black Survival (build 0.31.0a)
- Steam AppID of the game: 1049590

## System Information
- GPU: nvidia Quadro K3000M
- Driver/LLVM version: 418.181.07
- Kernel version: 4.19
- Link to full system information report as [Gist]: https://gist.github.com/tacklebox8/0fbab36520a1fd2413f8dafa654046c3
- Proton version: 6.3-2 (also happens using experimental)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1049590.log](https://github.com/ValveSoftware/Proton/files/6395503/steam-1049590.log)

## Symptoms 
Game crashes on load with Windows Fatal error message "Failed to load il2cpp".  Problem did not occur with build 0.30.x.  Another linux user on the ERBS discord reported the same issue.

## Reproduction
Launch the game.

**Comment by sjTaylor** [comment]
I am the other Linux user mentioned in the discord.
Additionally, someone else DM'd me so there's at least 3 of us.

## System Information
* GPU: nvidia GTX 1070
* Driver Version: Driver Version: 460.67
* OS: Pop!_OS 20.04
* Proton version: 6.3-2 (Proton Experimental and 6.5-GE-2 too)
* Kernel version: 5.11.0-7612-generic (from `uname -a`)

**Comment by jeffrey-xiao** [comment]
I also have the same issue and added a comment to #4653.

**Comment by kisak-valve** [comment]
Hello @tacklebox8, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4653#issuecomment-828871218.

**Comment by tacklebox8** [comment]
Error is gone after 0.31.2 patch and game runs.

**Comment by tacklebox8** [comment]
Error is back after 0.32.0 patch.
