### ISSUE TITLE
World of Tanks

### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/Proton#4786]
# Compatibility Report
- Name of the game with compatibility issues: World of Tanks
- Steam AppID of the game: 1407200

## System Information
- GPU:  GTX 1060
- Driver/LLVM version:  415.27
- Kernel version:  4.19
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Vladislavuz/78a0aaf7045dc237ac0a8ae6363e556f
- Proton version: experimental-6.3-20210427b

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 
[steam-1407200.log](https://github.com/ValveSoftware/Proton/files/6401085/steam-1407200.log)

## Symptoms 
The game crashes after launch.

## Reproduction
Try to start the game.

**Comment by kisak-valve** [comment]
Hello @Vladislavuz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1369#issuecomment-829530240.
