### ISSUE TITLE
[Regression] [Proton Experimental] Mouse cursor visible in Cyberpunk 2077

### ISSUE THREAD

**Issue by piquan** [ValveSoftware/Proton#4789]
# Compatibility Report
- Name of the game with compatibility issues: Cyberpunk 2077
- Steam AppID of the game: 1091500

## System Information
- GPU: RTX 3090
- Driver/LLVM version: Nvidia 460.73.01
- Kernel version: 5.10.0-6-amd64 (Debian Bullseye)
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/piquan/315b5a32b2a4e2b3f482b64383659f03
- Proton version: experimental-6.3-20210429

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- Elaboration: Not for this issue!  I know that CP2077 with Nvidia is considered "iffy", but this seems unrelated to the known issues.
- [X] that I have checked whether there are updates for my system available.
Proton log attached
[steam-1091500.log](https://github.com/ValveSoftware/Proton/files/6405294/steam-1091500.log)

## Symptoms

Mouse cursor visible in the middle of the screen.  Cursor is arrow-shaped, and apparently rendered post-scaling: even though my resolution in the game is set to 2880x1620 (display is 3840x2160), the cursor is quite tiny, yet with sharp definition.

The cursor stays in the center of the screen, with its hotspot right where an interaction cursor or weapon crosshair appears, while the game's UI cursor (a `[-]` look) moves normally.

## Reproduction

Happens every time I launch the game with the current version of Proton Experimental (experimental-6.3-20210429).  Tried several combos of rebooting, turning off or forcing on WM compositing (I'm using KDE's default WM, KWin), etc, but the problem was persistent.  I switched to the default Proton (5.13-6) and the problem stopped.

**Comment by kisak-valve** [comment]
Hello @piquan, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-830073282.
