### ISSUE TITLE
[Proton 3.7-3] Can't launch games and "dist" folder does not generate without python2

### ISSUE THREAD

**Issue by Warrengbrn** [ValveSoftware/Proton#479]
I got the updated Proton compatibility tools and now instead of seeing Proton 3.7, I see Proton 3.7-3 and Proton 3.7-4 Beta. When I have 3.7-3 selected I cannot launch any games. There also is no "dist" folder generated as seen in this screenshot:

![screenshot from 2018-08-24 22-53-15](https://user-images.githubusercontent.com/37555856/44614328-8202a080-a7f0-11e8-93ba-f9c1c0f3ff11.png)

**Its because I switched back to 3.7-3 without having python2 installed. My mistake.
The files in the dist folder were not filling out and games were not launching because of this.**

Proton 3.7-4 Beta does work however, but it does not contain DXVK 0.70, its still on dxvk (v0.64-126-gc24497d).

**Thanks for the explanation pchome.**

**Comment by pchome** [comment]
If you'll create new branch on tag `v0.64` and start changing things there -- it always will be `v0.64` with growing changes number. Even if you'll pull `v0.70` -- only "changes" will change.

At least it's usual behaviour of my branches.

`git describe --help`
```
The command finds the most recent tag that is reachable from a commit.
If the tag points to the commit, then only the tag is shown.
Otherwise, it suffixes the tag name with the number of additional commits
on top of the tagged object and the abbreviated object name of the most recent commit.
```

In other words -- `v0.64-126-gc24497d` can contain all changes from `v0.70`.

**Comment by dubigrasu** [comment]
@Warrengbrn 
Leave 3.7-3 selected (and eventually restart Steam), install some other game, (any game) and start it.

**Comment by Warrengbrn** [comment]
Its because I switched back to 3.7-3 without having python2 installed. My mistake.
The files in the dist folder were not filling out and games were not launching because of this.
