### ISSUE TITLE
Add Option to Automatically use Latest Proton Version for All Titles including Tested Ones

### ISSUE THREAD

**Issue by MetalNeo** [ValveSoftware/Proton#4791]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description
I would like to have the ability to choose which version of Proton should be used for all games, including the games that Valve originally tested. I would like the fixes/improvements from the new versions to be more accessible. Currently, games with a recommended Proton version need to be manually checked and edited to use the newest version of Proton.

## Justification
Checking and manually altering games with Valve testing to the latest Proton version is tedious. An option to choose whether to install the recommended version vs the latest version would be helpful to reduce the amount of manual configuration needed.

**Comment by kisak-valve** [comment]
Hello @MetalNeo, this is a feature request for the Steam client rather than Proton itself, and is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/7410 / https://github.com/ValveSoftware/steam-for-linux/issues/6859. Closing in favor of the existing feature request.
