### ISSUE TITLE
Avernum 4 (206020)

### ISSUE THREAD

**Issue by xenopeek** [ValveSoftware/Proton#4792]
# Compatibility Report
- Name of the game with compatibility issues: Avernum 4
- Steam AppID of the game: 206020

## System Information
- GPU: Intel HD Graphics 3000
- Driver/LLVM version: Mesa 21.0.3
- Kernel version: 5.11.16
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/xenopeek/f6cbdd46f1a2969ba58d7976a7ecb625
- Proton version: 6.3-2 (also tried Experimental, 5.13-6, 3.16-9)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-206020.log](https://github.com/ValveSoftware/Proton/files/6409461/steam-206020.log)

## Symptoms 

After clicking to play the game a black window opens which then resizes to full screen and instead of the game load screen appearing it immediately crashes. I take it this happens when it tries to switch to 1024x768 resolution in 16 bit color. That's the only resolution the game works on and it can't play in a window.

The game worked fine with Mesa 20.3.4 but after upgrading to Mesa 21 it crashes as described.

## Reproduction

1. Upgrade to Mesa 21.x
2. Click to play the game
3. It cashes as described

After downgrading to Mesa 20.3.4 the game will play again.

**Update:** upgrade to [Mesa 21.0.3-3](https://github.com/archlinux/svntogit-packages/commit/db92b6b3fc82f9e474f5663b782a2f990bdbf1b1#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a) includes fix for the issue that caused the game to stop working with Steam Play.

**Comment by kisak-valve** [comment]
Blind guess that your issue is https://gitlab.freedesktop.org/mesa/mesa/-/issues/3969.

**Comment by xenopeek** [comment]
I think you hit the nail on the head @kisak-valve, that looks like it. I see a patch was done today so I'll wait for a Mesa update and hopefully that will fix it and make this game compatible again. Thanks for the quick response!

**Comment by xenopeek** [comment]
Update to [Mesa 21.0.3-3](https://github.com/archlinux/svntogit-packages/commit/db92b6b3fc82f9e474f5663b782a2f990bdbf1b1#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a) on Arch Linux includes the patch from the issue you linked to. After updating the immediately runs again so I think I can close this? Thanks for your quick pointer to the right suspect.
