### ISSUE TITLE
Tainted Grail Conquest (1199030)

### ISSUE THREAD

**Issue by mibli** [ValveSoftware/Proton#4795]
# Compatibility Report
- Name of the game with compatibility issues: Tainted Grail Conquest
- Steam AppID of the game: 1199030

## System Information
- GPU: AMD AMD Radeon RX 5600 XT
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 21.0.1;  LLVM 11.1.0
- Kernel version: 5.4.108-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/mibli/d8657ccdf98904744d19495b5e0fc3cf)
- Proton version: 5.13-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[Link to download Proton logs archive](https://github.com/mibli/proton-logs/raw/master/steam-1199030.log.tar.gz)

## Symptoms

After finishing character creation, a screen with text will be displayed, after that a sound effect is played and You get stuck on black screen, which suposedly was going to be a video or something. Pressing Esc pops up a hint to press LMB, but pressing anywhere on screen doesn't do anything

[Link to video file showing the problem](https://github.com/mibli/proton-logs/raw/master/steam-1199030.mp4)

## Reproduction

1. Select Proton 5.13-6 from force specyfic compatibility tool option
2. Start the game
3. Select start new game
4. After character creation proceed with start game
5. Skip disclaimation screen with text
6. Hear a sound effect and now Youre stuck.

## Additional comments

The game doesn't start (opens a black window) with Proton version > 6.0

**Comment by kisak-valve** [comment]
Hello @mibli, it looks like this game would benefit from support for Media Foundation maturing. A Proton log from Proton Experimental might be more interesting to ponder.

From the log:
```
WindowsVideoMedia error 0x80004001 while reading archive:/CAB-11cf361c29fd29c6ece4d725d7bc5efa/CAB-11cf361c29fd29c6ece4d725d7bc5efa.resource

Context: MFCreateSourceReaderFromMediaSource
Error details: Not implemented.
```

**Comment by mibli** [comment]
# Report for Proton Experimental and 6.3-2

[Link to the compressed log running on experimental](https://github.com/mibli/proton-logs/raw/master/steam-1199030-experimental.log.tar.gz)

[Link to the compressed log running on 6.3-2](https://github.com/mibli/proton-logs/raw/master/steam-1199030-6.3-2.log.tar.gz)

## Symptoms

Pressing Play creates unresponsive window, which gets stuck on a deadlock it seems – has to be killed manually.

## Reproduction

1. Press Play Button

**Comment by alasky17** [comment]
@mibli Could you see if you are still getting a black screen?  I just tried the game and it is working for me on 6.3-3 and experimental-6.3-20210503.  I'm wondering if maybe a game update fixed the problem?

**Comment by mibli** [comment]
Works for me on experimental and on 5.13 (although I used the skip intro option).

**Comment by alasky17** [comment]
@mibli Edit: whoops, looks like I already said that haha.  So you are still getting a launch failure with 6.3-4?

**Comment by mibli** [comment]
> @mibli Edit: whoops, looks like I already said that haha. So you are still getting a launch failure with 6.3-4?

No I'm not getting launch failure or video failure. Seems ok now.
