### ISSUE TITLE
Read dead redemption 2 requires purchase again after social club update

### ISSUE THREAD

**Issue by JannickWeisshaupt** [ValveSoftware/Proton#4797]
Proton 6.3.2

After the newest social club update (from 27th or 28th of April) the game does not recognize that I already purchased it.
I am correctly logged into my social club account and it lists the game as purchased.
Still the story mode is locked with the following screen

![rdr2_screen](https://user-images.githubusercontent.com/19517440/116793168-5833c880-aac5-11eb-8bc0-ece63a01e890.png)

**Comment by Leopard1907** [comment]
https://github.com/ValveSoftware/Proton/wiki/Changelog#available-in-proton-experimental-as-of-20210429

> Fix Red Dead Redemption 2 "Not Purchased" error.

Try Proton Experimental.

**Comment by kisak-valve** [comment]
Hello @JannickWeisshaupt, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-830688627.
