### ISSUE TITLE
Spellforce 3 - broken fonts rendering

### ISSUE THREAD

**Issue by nadrolinux** [ValveSoftware/Proton#4802]
# Compatibility Report
- Name of the game with compatibility issues: Spellforce 3
- Steam AppID of the game: 311290

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 21.0.3
- Kernel version: 5.11.0-16-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/nadrolinux/bf5b9c415c81a97ba264dd7090c21474
- Proton version: experimental-6.3-20210429

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Fonts rendering is broken (I attached print screen) regardless of chosen language.

## Reproduction

Just run a game.

![broken_fonts](https://user-images.githubusercontent.com/11942352/117003479-331da080-ace5-11eb-86dc-1a7dd4869b17.png)
[steam-311290.log](https://github.com/ValveSoftware/Proton/files/6421059/steam-311290.log)

**Comment by kisak-valve** [comment]
Hello @nadrolinux, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1033#issuecomment-831907134.
