### ISSUE TITLE
Arma 3 (107410)

### ISSUE THREAD

**Issue by cudla100** [ValveSoftware/Proton#4803]
# Compatibility Report
- Name of the game with compatibility issues: Arma 3
- Steam AppID of the game: 107410

## System Information
- GPU: NVIDIA Corporation TU106 [GeForce RTX 2060 Rev. A]
- Driver/LLVM version: 460.73.01
- Kernel version: 5.8.0-50-generic
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/cudla100/99e13d51c10787718d17b750919742ee
- Proton version:6.3-3

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. -I have found an existing compatibility report for this game, but it does not describe my issue.
- [x] that I have checked whether there are updates for my system available.

[steam-107410.log] (https://github.com/ValveSoftware/Proton/files/6421627/steam-107410.log)

## Symptoms 
Crash on startup with following message.
![Snímek z 2021-05-04 15-54-43](https://user-images.githubusercontent.com/27821549/117016917-7848cf00-acf3-11eb-8def-d6e3449f2658.png)

## Reproduction
Starting the game.

**Comment by kisak-valve** [comment]
Hello @cudla100, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2364#issuecomment-831981813.
