### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by slynobody** [ValveSoftware/Proton#4806]
as wine in 6.5 has not fully fixed the 'start.exe' issues in several conditions, would you please provide a pre-release of 6.7?

**Comment by kisak-valve** [comment]
Hello @slynobody, Proton gets rebased on a newer at the discretion of the Proton devs and it's a substantial time commitment each time. You can not request that the Proton devs fast track that process before they're ready.

If there are specific commits you know fixes issues, you can open a pull request to request that those commits get backported to Proton and the Proton devs can consider that. It's also useful to reference the upstream wine commits to make it easier to track.

That said, Proton is currently based on wine 6.3, and I suspect this feedback was intended for @GloriousEggroll, and not the Proton team.
