### ISSUE TITLE
Mortal Kombat Komplete edition 237110

### ISSUE THREAD

**Issue by mathew2214** [ValveSoftware/Proton#4813]
# Compatibility Report
- Name of the game with compatibility issues: Mortal Kombat Komplete Edition
- Steam AppID of the game: 237110

## System Information

- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/mathew2214/fea4feeeb449061647df03e19ac2e6ec
- Proton version: 6.3.3

proton log:
https://gist.github.com/mathew2214/80366d5e0c8d8699c9e5fde1a329b316

## Symptoms 
cannot play any online match. always gives "Game Session No Longer Availible"

## Reproduction

try to play online

**Comment by kisak-valve** [comment]
Hello @mathew2214, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1185#issuecomment-836602663.
