### ISSUE TITLE
Euro Truck Simulator 2 (227300)

### ISSUE THREAD

**Issue by fluttirci** [ValveSoftware/Proton#4817]
# Compatibility Report
- Name of the game with compatibility issues: Euro Truck Simulator 2
- Steam AppID of the game: 227300
-- | --

## System Information
- GPU: RX 470 4 GB 
- Driver/LLVM version: Mesa 20.3.4 
- Kernel version: 5.11.0-7614-generic 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/fluttirci/093442da71a106aded93c2d7e4628b94
- Proton version: 6.3.3

## I confirm: ALL THESE.
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 

## Symptoms 
When I launch the game with proton 6.3.3, it won't work anymore. It used to work exactly like that. Nevertheless, linux native works. Here is my gist: https://gist.github.com/fluttirci/093442da71a106aded93c2d7e4628b94 
I also tried to create a log file but no such file was created.

**Comment by kisak-valve** [comment]
Hello @fluttirci, can you also test how the game behaves with Proton Experimental? This might be another example of #4815 or #4816.

Separately, it may be interesting to test Proton 6.3-3 while having the game's launch options set to `WINEDLLOVERRIDES=dxgi=n %command%`.

**Comment by fluttirci** [comment]
That command about 6.3.3 worked pretty well. Thank you! My problem is solved now. You may close it or should I do it?

Also a side note about proton experimental, it didn't work well. Too black screen in the menu. There has to be a truck in the menu but there is only black, only menu buttons visible. Also in game, weird shadows. https://imgur.com/a/W1fNbSU
