### ISSUE TITLE
Skyrim SE after the Proton expermintal update have fps drop (stable platinium 60 -> 20)

### ISSUE THREAD

**Issue by kczereczon** [ValveSoftware/Proton#4818]
New update of proton experimental have regression in my opinion eg. in skyrim Se the frame rate went down to 20 in open world in caves to 50 fps, when before it was stable 60 FPS no metter what I was doing (platinium in my opinion). 

**Quickfix:**
Change proton version from experimental to proton6.3-3

**CPU:** Intel Core i5-2400 - cpu usage was the same
**GPU:** RX480 8GB
**RAM:** 16GB - ram usage was the same

I found out that other guy have the same issue:
![image](https://user-images.githubusercontent.com/22079016/118036294-b0dc4e80-b36c-11eb-9af4-11c9f86b0921.png)
![image](https://user-images.githubusercontent.com/22079016/118036318-b9cd2000-b36c-11eb-9a09-080c59450448.png)

**Comment by kisak-valve** [comment]
Hello @kczereczon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4#issuecomment-840057986.
