### ISSUE TITLE
Can't launch any game using proton.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#4822]
# Compatibility Report
- Name of the game with compatibility issues: Any windows game

## System Information
- GPU: GTX 750 Ti
- Driver/LLVM version: nvidia 460.73.01
- Kernel version: 5.10
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/wichyslav/9b6d640416a0a148ae5ba2436a6bd816
- Proton version:6.3-3

## I confirm:
- [Y] that I haven't found an existing compatibility report for this game.
- [Y] that I have checked whether there are updates for my system available.

## Symptoms 
No Windows title will launch. It stays on preparing to launch, and then nothing.

## Reproduction
No idea

Additional Info:
I have distro hopped multiple times to see if the issue persists on multiple distros, and yes, the issue persists. Kernels tested: 5.10, 5.11, 5.12
Currently on Neptune 6.5

**Comment by kisak-valve** [comment]
Hello @wichyslav, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to any game's launch options that you have configured to use with Proton and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

Blind guess that you're seeing something similar to https://github.com/ValveSoftware/steam-runtime/issues/312 and https://github.com/ValveSoftware/steam-runtime/issues/312#issuecomment-739441559 might be worth trying.

**Comment by ghost** [comment]
> Hello @wichyslav, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to any game's launch options that you have configured to use with Proton and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)
> 
> Blind guess that you're seeing something similar to [ValveSoftware/steam-runtime#312](https://github.com/ValveSoftware/steam-runtime/issues/312) and [ValveSoftware/steam-runtime#312 (comment)](https://github.com/ValveSoftware/steam-runtime/issues/312#issuecomment-739441559) might be worth trying.

I did add the launch options, but it didn't generate a log file.
Also regarding the issue you have sent, i am using a desktop and nvidia drivers are the only ones installed. I've also tried older versions of Proton, but they don't work aswell.

**Comment by fuomag9** [comment]
Same issue here, no log was generated. Proton <= 5.0-10 works fine. Here's the steam console log. The drive was at first a NTFS drive but I formatted it to btrfs because I tought that was the issue at first but nothing changed
```
GameAction [AppID 1118200, ActionID 23] : LaunchApp changed task to ProcessingInstallScript with ""
/mnt/hdd2/Games/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point: line 378: /mnt/hdd2/Games/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/bin/pressure-vessel-adverb: No such file or directory
/mnt/hdd2/Games/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point: line 378: /mnt/hdd2/Games/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/bin/pressure-vessel-adverb: No such file or directory
src/clientdll/installscript_posix.cpp (420) : Assertion Failed: Standalone evaluator returned error code for app 1118200
src/clientdll/installscript_posix.cpp (420) : Assertion Failed: Standalone evaluator returned error code for app 1118200
GameAction [AppID 1118200, ActionID 23] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 1118200, ActionID 23] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1118200, ActionID 23] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1118200, ActionID 23] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1118200, ActionID 23] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0PROTON_LOG=1 /home/fuomag9/.local/share/Steam/ubuntu12_32/../ubuntu12_32/reaper SteamLaunch AppId=1118200 -- '/mnt/hdd2/Games/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/mnt/hdd2/Games/SteamLibrary/steamapps/common/Proton 6.3'/proton waitforexitandrun  '/mnt/hdd2/Games/SteamLibrary/steamapps/common/People Playground/People Playground.exe'\0
Game update: AppID 1118200 "", ProcID 48511, IP 0.0.0.0:0
Starting app 1118200
>>> Adding process 48511 for game ID 1118200
GameAction [AppID 1118200, ActionID 23] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/fuomag9/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fuomag9/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/fuomag9/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fuomag9/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fuomag9/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1118200, ActionID 23] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/fuomag9/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 48515 != 48512, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/fuomag9/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fuomag9/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/mnt/hdd2/Games/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/run: line 22: /mnt/hdd2/Games/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/bin/pressure-vessel-unruntime: No such file or directory
>>> Adding process 48512 for game ID 1118200
>>> Adding process 48513 for game ID 1118200
>>> Adding process 48514 for game ID 1118200
>>> Adding process 48516 for game ID 1118200
>>> Adding process 48517 for game ID 1118200
Game removed: AppID 1118200 "", ProcID 48511 
Uploaded AppInterfaceStats to Steam
Exiting app 1118200
No cached sticky mapping in ActivateActionSet.
```

Edit: for anyone that may need this in my case manually deleting all the runtimes, reinstalling wine and reinstalling the soldier as well (with steam restarts in between) seems to have solved the issue for now!

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
