### ISSUE TITLE
Proton - Steam - AoW3 Planetfall

### ISSUE THREAD

**Issue by bengtsod** [ValveSoftware/Proton#4831]
This game used to work for me, now it's not :)

Raised a support ticket at paradox (game publisher) but thought I'd put an issue here as well (feel free to close it if it's nothing proton-related). Just making an issue here as well in case.

`
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Working directory: Z:\home\bengt\.local\share\Steam\steamapps\common\Age of Wonders Planetfall
Setting breakpad minidump AppID = 718850
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198037505609 [API loaded no]
UserPath set to: C:\users\steamuser\My Documents\Paradox Interactive\Age of Wonders Planetfall\
Build Number: 43820 - Build Time: UnknownDate UnknownTime -STEAM BUILD
Running SSL version: OpenSSL 1.0.2t  10 Sep 2019
POPS_Initialize took 0.005802s
POPS first (nop) callback took 0.056234s
POPS Log: [CurlCallPool::create] SUCCESS new call '0000000001F90050'
POPS Log: [CurlCallBuilder] START build '0000000001F90050'
POPS Log: [CurlCallBuilder::set_async] 1
POPS Log: [CurlCallBuilder::set_user_data] 0000000001F80050
POPS Log: [CurlCallBuilder::set_user_callback] 00000000006F0210
POPS Log: [CurlCallBuilder::set_user_agent] aow_planetfall/1.404.43820:pops_api/1.20.0-0-gd8047acc/win
POPS Log: [CurlCallBuilder::set_url] https://api.paradox-interactive.com/legal/documents/list
POPS Log: [CurlCallBuilder::set_callback] 20079 000000000076E980
POPS Log: [CurlCallBuilder::set_callback] 20011 000000000076EB60
POPS Log: [CurlCallBuilder::build] BUILD '0000000001F90050'
POPS Log: [CurlCallManager::update] SENT ASYNC '0000000001F90050'
POPS Log: [CurlCallManager::handle_curl_write] '0000000001F90050' {"documents":[{"title":"privacy-
POPS Log: [CurlCallManager::update] DONE msg '0000000001F90050'
POPS Log: [CurlCallManager::update] DONE curl easy handle '0000000001F90050'
POPS Log: [CurlCallManager::update] SUCCESS '0000000001F90050' 200
FixStartupHang took 711 ms
TESearchPathManager::Initialize took 0 ms
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Application Data\openvr\openvrpaths.vrpath
-----Listing outputs & display modes for adapter GeForce RTX 2060-----
 - Output 0: \\.\DISPLAY1 (21 modes)
   [0] 1920 x 1080 @ 60.00 Hz
   [1] 1920 x 1080 @ 50.00 Hz
   [2] 1920 x 800 @ 60.00 Hz
   [3] 1680 x 1050 @ 60.00 Hz
   [4] 1600 x 900 @ 60.00 Hz
   [5] 1440 x 960 @ 60.00 Hz
   [6] 1440 x 900 @ 60.00 Hz
   [7] 1280 x 1024 @ 75.00 Hz
   [8] 1280 x 1024 @ 60.00 Hz
   [9] 1280 x 800 @ 60.00 Hz
   [10] 1280 x 720 @ 60.00 Hz
   [11] 1280 x 720 @ 50.00 Hz
   [12] 1024 x 768 @ 75.00 Hz
   [13] 1024 x 768 @ 60.00 Hz
   [14] 960 x 540 @ 60.00 Hz
   [15] 800 x 600 @ 75.00 Hz
   [16] 800 x 600 @ 60.00 Hz
   [17] 720 x 576 @ 50.00 Hz
   [18] 720 x 480 @ 60.00 Hz
   [19] 640 x 480 @ 75.00 Hz
   [20] 640 x 480 @ 60.00 Hz

----------

Selected display adapter: GeForce RTX 2060 (No adapter found by UID)

1.161320s in: Loading dustball
Selected display adapter: GeForce RTX 2060 (No adapter found by UID)

Open: Could not create file DUSTBALL: File not found.

Dustball load took 0.000527s
DirectX Version: 11.0
Assertion failed at c:\.workspace\src\creator\re\source\Device/REDeviceResource.cpp (111): pResource->FManager==this (Assertion failed: pResource->FManager==this)
c:\.workspace\src\creator\re\source\Device/REScreenVertices.cpp(19): TREScreenVerticesSharedResources::AllocateDevice FAILED
`
Getting the same output for several versions of proton (running the ones included in steam from terminal). Used to work fine a while back, now it's not, probably been both updates for nvidia drivers, proton and the game itself since last I ran it so unsure what's causing the problem :)

**Comment by kisak-valve** [comment]
Hello @bengtsod, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2959#issuecomment-842391143.
