### ISSUE TITLE
Phoenix Wright: Ace Attorney Trilogy (787480)

### ISSUE THREAD

**Issue by sonic2kk** [ValveSoftware/Proton#4837]
# Whitelist Request
- Name of the game to be whitelisted: Phoenix Wright: Ace Attorney Trilogy
- Steam AppID of the game: 787480

## System Information
- GPU: AMD Vega 7 iGPU (Ryzen 4700U)
- Driver/LLVM version: Mesa 21.1.0/LLVM 11.1.0
- Distro version: Arch Linux
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/sonic2kk/cfff841ad847aa5a1296e30ccd74fca3
- Proton version: 6.3-4

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [ ] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [X] Although I consider the gaming experience equal to Windows there are remaining issues:
  - Very rarely on first boot only, the Capcom logo splash may be scaled incorrectly. Once the game loads, this is fixed and **does not happen on subsequent reboots.**

I have tested this game on three different machines:
- Current laptop with an AMD iGPU
- Laptop with Intel UHD 620
- Desktop with RX 5700XT

With the latest releases of Proton there have been no issues running the game save for the minor visual bug described above. I do not have access to any devices with an Nvidia GPU to test the game on, but on various Intel and AMD devices the game runs without any problems. I have played 147 hours exclusively with Proton without issue across these devices.

The [open issue](https://github.com/ValveSoftware/Proton/issues/3324) for this game has only a few replies, but also mentions that the previous issues with the game and DXVK have been resolved.

**Comment by kisak-valve** [comment]
Hello @sonic2kk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3324#issuecomment-845175409.
