### ISSUE TITLE
elder scrolls online steam proton crash

### ISSUE THREAD

**Issue by r3k2** [ValveSoftware/Proton#4838]
# Compatibility Report
- Elder Scrolls online
- SteamID: 306130

## System Information
- GPU: VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1)
- Driver: extra/nvidia 465.31-3 [23.42MiB 23.42MiB] [Installed]
- Kernel version: 5.12.5-arch1-1
- gist: https://gist.github.com/r3k2/0b3212f1ff8c3f5a63eed77823ff663c
- Proton version: 5.x and 6.x

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
   - not with this issue.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Sorry for my bad English.
Playing ESO is usually ok until a big fight on cyradell the open world pvp area. it was working fine up until November that I stop playing... just got back to play the game and now is crashing.. I downgraded proton version to have the same I had before 5.x and still crashing under same circumstances.

**Comment by kisak-valve** [comment]
Hello @r3k2, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/556#issuecomment-845562003.
