### ISSUE TITLE
Borderlands 3 Unable to access Main Menu

### ISSUE THREAD

**Issue by LoreRealm** [ValveSoftware/Proton#4845]
# Compatibility Report
- Name of the game with compatibility issues:Borderlands 3
- Steam AppID of the game:397540

## System Information
- GPU: Radeon 6800
- Driver/LLVM version: mesa 21.1
- Kernel version: 5.12.4
- Link to full system information report as [Gist](https://gist.github.com/lorddickfist/3dd9fde27b9a40db2eea384036c30cc4):
- Proton version: Experimental, and 6.3-4 tried

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

[steam-397540.log](https://github.com/ValveSoftware/Proton/files/6527012/steam-397540.log)

## Symptoms 
Cannot get game to go to title screen gets stuck at black screen if you skip movies and stuck at no signal if there's 

## Reproduction
Use proton 6.3-4 or experimental and launch the game
![20210522122405_1](https://user-images.githubusercontent.com/22435766/119238671-a81c1300-baf8-11eb-9724-f78c4c0fbc9e.jpg)

**Comment by kisak-valve** [comment]
Hello @lorddickfist, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3635#issuecomment-846454748.
