### ISSUE TITLE
Elite Dangerous: Odyssey DLC performance issues

### ISSUE THREAD

**Issue by hanspaerna** [ValveSoftware/Proton#4846]
# Compatibility Report
- Name of the game with compatibility issues: Elite Dangerous (only with Odyssey DLC)
- Steam AppID of the game: 359320

## System Information
- GPU: NVIDIA GeForce GTX 1060 6GB
- Driver/LLVM version: NVIDIA 460.73.01
- Kernel version: 5.8.0-53-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton 6.3-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
There's a problem that makes Odyssey DLC totally unplayable for me: it's a huge FPS drop (from 30 to 1-3 FPS) that happens if I open and close the System map while being on a station or any other space-leg location. After this my VRAM is used at 100% and the only way to return the game to its normal state is to restart it completely. 

## Reproduction
1. Start the game
2. Visit any space-leg location
3. Open the system or galaxy map one or multiple times while standing there
4. Get a huge FPS drop after closing the map

**Comment by kisak-valve** [comment]
Hello @artemantcev, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/150#issuecomment-846545787.
