### ISSUE TITLE
[Whitelist] Farming Simulator 2013 (220260)

### ISSUE THREAD

**Issue by nic96** [ValveSoftware/Proton#485]
Runs flawless on my system:

- OS: Arch Linux
- Kernel: 4.18.4-arch1-1-ARCH
- GPU:  Intel® HD Graphics 4400
- Driver: xf86-video-intel 1:2.99.917+831+ge7bfc906-1
- Vulkan Driver: vulkan-intel 18.1.7-1
- Proton: 3.7-4

Edit:
I tried it again and I had to edit `~/.local/share/Steam/steamapps/compatdata/220260/pfx/drive_c/users/steamuser/My Documents/My Games/FarmingSimulator2013/game.xml` and change the width and height properties to my screens resolution or set fullscreen to false for it to work. Otherwise the screen is black with only the audio apparent.

**Comment by kisak-valve** [comment]
Hello @nic96, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this to https://github.com/ValveSoftware/Proton/issues/446#issuecomment-415999986.
