### ISSUE TITLE
Sea Glitch issue

### ISSUE THREAD

**Issue by josh56432** [ValveSoftware/Proton#4853]
I'm on ubuntu and using any proton version that runs the game makes the sea flicker its really annoying on all graphics settings, nobody i can find has the same issue and everything else functions perfectly.

SPECS:
rx 5600xt GPU up to date drivers

Proton 5.13 - 6.9-GE all broken

![Screenshot from 2021-05-23 11-01-14](https://user-images.githubusercontent.com/79372027/119385864-af8d1900-bcbe-11eb-97af-c842618bdefc.png)

glitches and flickers everything else works perfectly.

**Comment by kisak-valve** [comment]
Hello @josh56432, I had to make an educated guess that you're referring to Sea of Thieves. We're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3931#issuecomment-847228288.

If this is from a different game, please clarify that here.
