### ISSUE TITLE
How to start game + additional Windows Programm in same prefix?

### ISSUE THREAD

**Issue by kallestrop** [ValveSoftware/Proton#4855]
I play Euro Truck Simulator 2 (227300) with Proton 6.3-4. 

There is an additional Windows program called trucksbook which logs your freights by reading telemetry data provided by the game. 

It has to be started before the main Game.

I successfully installed trucksbook in game prefix and i can start it in terminal with:

`STEAM_COMPAT_DATA_PATH="/home/user/.steam/steam/steamapps/compatdata/227300" "/home/user/.local/share/Steam/steamapps/common/Proton 6.3/proton" run "/home/user/.steam/steam/steamapps/compatdata/227300/pfx/drive_c/Program Files (x86)/TrucksBook Client/TB Client.exe"`

But when i  start the main game in Steam client, it doesn´t come up not till i close the TB Client.exe. After that, the game continuous booting and starts normal.

So how can i start both programs?

[steam-227300.log](https://github.com/ValveSoftware/Proton/files/6539755/steam-227300.log)

**Comment by olav-valle** [comment]
I've previously had good results for things like this using [proton-exec](https://gitlab.com/SparrowOchon/proton-exec) and [this script](https://gist.github.com/smo0z/620d9d98e27dbba01345a5b21948f545). 

There's also [Steam Tinker Launch](https://github.com/frostworx/steamtinkerlaunch), which I've been meaning to check out. It seems really robust and full of the kind of features you're looking for. 

This kind of thing is a feature that has been [requested by many](https://github.com/ValveSoftware/steam-for-linux/issues/5766) for Steam over the years, and I echo that sentiment.

**Comment by kallestrop** [comment]
Thanks for the hint. I'll try it.
