### ISSUE TITLE
Game not launching. Linux mint.

### ISSUE THREAD

**Issue by Rasputinbkz** [ValveSoftware/Proton#4857]
# Compatibility Report
- Name of the game with compatibility issues:**Age of empires 2**

## System Information
- GPU: AMD Radeon 5430/5450/5470
- Kernel version: 4.4.0-210 Linux mint
- Proton version:

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

 OK

## Symptoms 
Game is not launching

## Reproduction

I can see the error code:
Unhandled exception: page fault on read access to 0x00000000 in 64-bit code (0x00000001405e01a5).
Register dump:
rip:00000001405e01a5 rsp:000000000a08fab0 rbp:000000000a08fc00 eflags:00010202 ( R- -- I - - - )
rax:0000000000000000 rbx:000000000a08fbb0 rcx:0000000000000000 rdx:000000000a08fbb0
rsi:0000000000000000 rdi:00000001430a04b0 r8:0000000000de82b0 r9:0000000000230000 r10:000000014225fba8
r11:000000000a08fad0 r12:0000000000000000 r13:0000000000000000 r14:0000000000000000 r15:0000000000000000
Stack dump:
0x000000000a08fab0: 0000000000000001 fffffffffffffffe
0x000000000a08fac0: 000000000a08fbb0 00000001405d5dc9
0x000000000a08fad0: 0000000000000000 0000000000000000
0x000000000a08fae0: 0000000000000000 0000000000000000
0x000000000a08faf0: 00000001430a04b0 00000001405db994
0x000000000a08fb00: 0000000000000000 0000000000000000
0x000000000a08fb10: 0000000000000000 0000000000000000
0x000000000a08fb20: 0000000000000000 0000000000000000
0x000000000a08fb30: 0000000000000000 0000000000000000
0x000000000a08fb40: 0000020000001ab0 0000000000000000
0x000000000a08fb50: 0000000000000001 0000000000000000
0x000000000a08fb60: 0000000000000000 0000000000000000
Backtrace:
=>0 0x00000001405e01a5 in aoe2de_s (+0x5e01a5) (0x000000000a08fc00)
0x00000001405e01a5: movq (%rax),%r8
Modules:
Module Address Debug info Name (229 modules)
PE 230000- 246000 Deferred vcruntime140
PE 250000- 2a1000 Deferred concrt140
PE c50000- ce7000 Deferred openvr_api_dxvk
PE 6a340000- 6a543000 Deferred d3d11
PE 6f200000- 6f39a000 Deferred dxgi
ELF 7a800000- 7aa04000 Deferred opengl32<elf>
\-PE 7a850000- 7aa04000 \ opengl32
ELF 7b400000- 7b811000 Deferred kernel32<elf>
\-PE 7b420000- 7b811000 \ kernel32
ELF 7bc00000- 7bd32000 Deferred ntdll<elf>
\-PE 7bc20000- 7bd32000 \ ntdll
ELF 7c000000- 7c003000 Deferred <wine-loader>
PE 13b400000- 13b44a000 Deferred steam_api64
PE 140000000- 143b24800 Export aoe2de_s
PE 180000000- 18009c000 Deferred msvcp140
ELF 7f3a85b22000- 7f3a85e22000 Deferred libasound.so.2
ELF 7f3a85e22000- 7f3a8604d000 Deferred libvorbis.so.0
ELF 7f3a8604d000- 7f3a86256000 Deferred libogg.so.0
ELF 7f3a86256000- 7f3a864ff000 Deferred libvorbisenc.so.2
ELF 7f3a864ff000- 7f3a86774000 Deferred libflac.so.8
ELF 7f3a86774000- 7f3a86984000 Deferred libapparmor.so.1
ELF 7f3a86984000- 7f3a86b8a000 Deferred libasyncns.so.0
ELF 7f3a86b8a000- 7f3a86df4000 Deferred libsndfile.so.1
ELF 7f3a86df4000- 7f3a86ffe000 Deferred libwrap.so.0
ELF 7f3a8c0f1000- 7f3a8c36e000 Deferred libpulsecommon-8.0.so
ELF 7f3a8c36e000- 7f3a8c5be000 Deferred libpulse.so.0
ELF 7f3a8c5be000- 7f3a90000000 Deferred libllvm-6.0.so.1
ELF 7f3a94143000- 7f3a94159000 Deferred midimap<elf>
\-PE 7f3a94150000- 7f3a94159000 \ midimap
ELF 7f3a94159000- 7f3a94172000 Deferred msacm32<elf>
\-PE 7f3a94160000- 7f3a94172000 \ msacm32
ELF 7f3a94172000- 7f3a941a9000 Deferred winealsa<elf>
\-PE 7f3a94180000- 7f3a941a9000 \ winealsa
ELF 7f3a941a9000- 7f3a941d6000 Deferred winepulse<elf>
\-PE 7f3a941b0000- 7f3a941d6000 \ winepulse
ELF 7f3a941d6000- 7f3a941fd000 Deferred mmdevapi<elf>
\-PE 7f3a941e0000- 7f3a941fd000 \ mmdevapi
ELF 7f3a941fd000- 7f3a9422b000 Deferred msvfw32<elf>
\-PE 7f3a94200000- 7f3a9422b000 \ msvfw32
ELF 7f3a9435c000- 7f3a943b1000 Deferred dsound<elf>
\-PE 7f3a94360000- 7f3a943b1000 \ dsound
ELF 7f3a943b1000- 7f3a943c6000 Deferred avicap32<elf>
\-PE 7f3a943c0000- 7f3a943c6000 \ avicap32
ELF 7f3a943c6000- 7f3a943f0000 Deferred devenum<elf>
\-PE 7f3a943d0000- 7f3a943f0000 \ devenum
ELF 7f3a94671000- 7f3a94886000 Deferred libbsd.so.0
ELF 7f3a94886000- 7f3a94aaf000 Deferred libtinfo.so.5
ELF 7f3a94aaf000- 7f3a94ce7000 Deferred libedit.so.2
ELF 7f3a94ce7000- 7f3a94eff000 Deferred libelf.so.1
ELF 7f3a94eff000- 7f3a95109000 Deferred libdrm_amdgpu.so.1
ELF 7f3a95109000- 7f3a95315000 Deferred libdrm_radeon.so.1
ELF 7f3a95315000- 7f3a9551d000 Deferred libdrm_nouveau.so.2
ELF 7f3a9551d000- 7f3a9572c000 Deferred libsensors.so.4
ELF 7f3a9572c000- 7f3a96644000 Deferred r600_dri.so
ELF 7f3a96644000- 7f3a96686000 Deferred wbemprox<elf>
\-PE 7f3a96650000- 7f3a96686000 \ wbemprox
ELF 7f3a96686000- 7f3a96721000 Deferred ddraw<elf>
\-PE 7f3a96690000- 7f3a96721000 \ ddraw
ELF 7f3a96721000- 7f3a96891000 Deferred wined3d<elf>
\-PE 7f3a96740000- 7f3a96891000 \ wined3d
ELF 7f3a968eb000- 7f3a9690d000 Deferred netprofm<elf>
\-PE 7f3a968f0000- 7f3a9690d000 \ netprofm
ELF 7f3a9690d000- 7f3a9694e000 Deferred rsaenh<elf>
\-PE 7f3a96910000- 7f3a9694e000 \ rsaenh
ELF 7f3a96994000- 7f3a96bf3000 Deferred libvulkan.so.1
ELF 7f3a96bf3000- 7f3a96c08000 Deferred api-ms-win-core-localization-l1-2-1<elf>
\-PE 7f3a96c00000- 7f3a96c08000 \ api-ms-win-core-localization-l1-2-1
ELF 7f3a96c08000- 7f3a96c1c000 Deferred api-ms-win-core-fibers-l1-1-1<elf>
\-PE 7f3a96c10000- 7f3a96c1c000 \ api-ms-win-core-fibers-l1-1-1
ELF 7f3a96c1c000- 7f3a96c31000 Deferred api-ms-win-core-synch-l1-2-0<elf>
\-PE 7f3a96c20000- 7f3a96c31000 \ api-ms-win-core-synch-l1-2-0
ELF 7f3a96c31000- 7f3a96ea1000 Deferred libpcre.so.3
ELF 7f3a96ea1000- 7f3a97182000 Deferred libgcrypt.so.20
ELF 7f3a97182000- 7f3a973a4000 Deferred liblzma.so.5
ELF 7f3a973a4000- 7f3a975c6000 Deferred libselinux.so.1
ELF 7f3a975c6000- 7f3a9764b000 Deferred libsystemd.so.0
ELF 7f3a9764b000- 7f3a97866000 Deferred libresolv.so.2
ELF 7f3a97866000- 7f3a97a6a000 Deferred libkeyutils.so.1
ELF 7f3a97a6a000- 7f3a97cb6000 Deferred libdbus-1.so.3
ELF 7f3a97cb6000- 7f3a97f36000 Deferred libgmp.so.10
ELF 7f3a97f36000- 7f3a98169000 Deferred libhogweed.so.4
ELF 7f3a98169000- 7f3a9839f000 Deferred libnettle.so.6
ELF 7f3a9839f000- 7f3a985d2000 Deferred libidn.so.11
ELF 7f3a985d2000- 7f3a987dd000 Deferred libkrb5support.so.0
ELF 7f3a987dd000- 7f3a989e1000 Deferred libcom_err.so.2
ELF 7f3a989e1000- 7f3a98c10000 Deferred libk5crypto.so.3
ELF 7f3a98c10000- 7f3a98ee2000 Deferred libkrb5.so.3
ELF 7f3a98ee2000- 7f3a990f3000 Deferred libavahi-client.so.3
ELF 7f3a990f3000- 7f3a992ff000 Deferred libavahi-common.so.3
ELF 7f3a992ff000- 7f3a9962f000 Deferred libgnutls.so.30
ELF 7f3a9962f000- 7f3a99879000 Deferred libgssapi_krb5.so.2
ELF 7f3a99879000- 7f3a99af9000 Deferred libcups.so.2
ELF 7f3a99af9000- 7f3a99b37000 Deferred uxtheme<elf>
\-PE 7f3a99b00000- 7f3a99b37000 \ uxtheme
ELF 7f3a99b39000- 7f3a99d43000 Deferred libxcursor.so.1
ELF 7f3a99d43000- 7f3a99f4d000 Deferred libxrender.so.1
ELF 7f3a99f4d000- 7f3a9a15d000 Deferred libxi.so.6
ELF 7f3a9a15d000- 7f3a9a360000 Deferred libxcomposite.so.1
ELF 7f3a9a360000- 7f3a9a563000 Deferred libxinerama.so.1
ELF 7f3a9a563000- 7f3a9a60c000 Deferred winex11<elf>
\-PE 7f3a9a570000- 7f3a9a60c000 \ winex11
ELF 7f3a9a60c000- 7f3a9a821000 Deferred gnome-keyring-pkcs11.so
ELF 7f3a9a821000- 7f3a9aa34000 Deferred libtasn1.so.6
ELF 7f3a9aa34000- 7f3a9ac70000 Deferred p11-kit-trust.so
ELF 7f3a9ac70000- 7f3a9ae78000 Deferred libffi.so.6
ELF 7f3a9ae78000- 7f3a9b08c000 Deferred libgpg-error.so.0
ELF 7f3a9b08c000- 7f3a9b2f0000 Deferred libp11-kit.so.0
ELF 7f3a9b2f0000- 7f3a9b56f000 Deferred libgcrypt.so.11
ELF 7f3a9b56f000- 7f3a9b780000 Deferred libtasn1.so.3
ELF 7f3a9b780000- 7f3a9ba40000 Deferred libgnutls.so.26
ELF 7f3a9bb36000- 7f3a9bd79000 Deferred libfontconfig.so.1
ELF 7f3a9bd79000- 7f3a9bf9e000 Deferred libpng12.so.0
ELF 7f3a9bf9e000- 7f3a9c248000 Deferred libfreetype.so.6
ELF 7f3a9c248000- 7f3a9c2c5000 Deferred setupapi<elf>
\-PE 7f3a9c260000- 7f3a9c2c5000 \ setupapi
ELF 7f3a9c2c5000- 7f3a9c2d9000 Deferred api-ms-win-crt-utility-l1-1-0<elf>
\-PE 7f3a9c2d0000- 7f3a9c2d9000 \ api-ms-win-crt-utility-l1-1-0
ELF 7f3a9c2d9000- 7f3a9c2ed000 Deferred api-ms-win-crt-environment-l1-1-0<elf>
\-PE 7f3a9c2e0000- 7f3a9c2ed000 \ api-ms-win-crt-environment-l1-1-0
ELF 7f3a9c2ed000- 7f3a9c302000 Deferred api-ms-win-crt-filesystem-l1-1-0<elf>
\-PE 7f3a9c2f0000- 7f3a9c302000 \ api-ms-win-crt-filesystem-l1-1-0
ELF 7f3a9c302000- 7f3a9c317000 Deferred api-ms-win-crt-time-l1-1-0<elf>
\-PE 7f3a9c310000- 7f3a9c317000 \ api-ms-win-crt-time-l1-1-0
ELF 7f3a9c317000- 7f3a9c32f000 Deferred api-ms-win-crt-multibyte-l1-1-0<elf>
\-PE 7f3a9c320000- 7f3a9c32f000 \ api-ms-win-crt-multibyte-l1-1-0
ELF 7f3a9c32f000- 7f3a9c349000 Deferred api-ms-win-crt-math-l1-1-0<elf>
\-PE 7f3a9c340000- 7f3a9c349000 \ api-ms-win-crt-math-l1-1-0
ELF 7f3a9c349000- 7f3a9c35d000 Deferred api-ms-win-crt-locale-l1-1-0<elf>
\-PE 7f3a9c350000- 7f3a9c35d000 \ api-ms-win-crt-locale-l1-1-0
ELF 7f3a9c35d000- 7f3a9c373000 Deferred api-ms-win-crt-convert-l1-1-0<elf>
\-PE 7f3a9c360000- 7f3a9c373000 \ api-ms-win-crt-convert-l1-1-0
ELF 7f3a9c373000- 7f3a9c389000 Deferred api-ms-win-crt-stdio-l1-1-0<elf>
\-PE 7f3a9c380000- 7f3a9c389000 \ api-ms-win-crt-stdio-l1-1-0
ELF 7f3a9c389000- 7f3a9c39d000 Deferred api-ms-win-crt-heap-l1-1-0<elf>
\-PE 7f3a9c390000- 7f3a9c39d000 \ api-ms-win-crt-heap-l1-1-0
ELF 7f3a9c39d000- 7f3a9c3b4000 Deferred api-ms-win-crt-string-l1-1-0<elf>
\-PE 7f3a9c3a0000- 7f3a9c3b4000 \ api-ms-win-crt-string-l1-1-0
ELF 7f3a9c3b4000- 7f3a9c4d3000 Deferred ucrtbase<elf>
\-PE 7f3a9c3e0000- 7f3a9c4d3000 \ ucrtbase
ELF 7f3a9c4d3000- 7f3a9c4e9000 Deferred api-ms-win-crt-runtime-l1-1-0<elf>
\-PE 7f3a9c4e0000- 7f3a9c4e9000 \ api-ms-win-crt-runtime-l1-1-0
ELF 7f3a9c4e9000- 7f3a9c56d000 Deferred d3dcompiler_47<elf>
\-PE 7f3a9c500000- 7f3a9c56d000 \ d3dcompiler_47
ELF 7f3a9c56d000- 7f3a9c642000 Deferred msvcrt<elf>
\-PE 7f3a9c590000- 7f3a9c642000 \ msvcrt
ELF 7f3a9c642000- 7f3a9c68b000 Deferred winevulkan<elf>
\-PE 7f3a9c650000- 7f3a9c68b000 \ winevulkan
ELF 7f3a9c68b000- 7f3a9c6a4000 Deferred vulkan-1<elf>
\-PE 7f3a9c690000- 7f3a9c6a4000 \ vulkan-1
ELF 7f3a9c6a4000- 7f3a9c6c2000 Deferred jsproxy<elf>
\-PE 7f3a9c6b0000- 7f3a9c6c2000 \ jsproxy
ELF 7f3a9c6c2000- 7f3a9c706000 Deferred winhttp<elf>
\-PE 7f3a9c6d0000- 7f3a9c706000 \ winhttp
ELF 7f3a9c706000- 7f3a9c74f000 Deferred winspool<elf>
\-PE 7f3a9c710000- 7f3a9c74f000 \ winspool
ELF 7f3a9c74f000- 7f3a9c79d000 Deferred usp10<elf>
\-PE 7f3a9c760000- 7f3a9c79d000 \ usp10
ELF 7f3a9c79d000- 7f3a9c8ef000 Deferred comctl32<elf>
\-PE 7f3a9c7b0000- 7f3a9c8ef000 \ comctl32
ELF 7f3a9c8ef000- 7f3a9c9f0000 Deferred comdlg32<elf>
\-PE 7f3a9c900000- 7f3a9c9f0000 \ comdlg32
ELF 7f3a9c9f0000- 7f3a9cb69000 Deferred oleaut32<elf>
\-PE 7f3a9ca10000- 7f3a9cb69000 \ oleaut32
ELF 7f3a9cb69000- 7f3a9ce57000 Deferred shell32<elf>
\-PE 7f3a9cb80000- 7f3a9ce57000 \ shell32
ELF 7f3a9ce57000- 7f3a9ce7a000 Deferred bcrypt<elf>
\-PE 7f3a9ce60000- 7f3a9ce7a000 \ bcrypt
ELF 7f3a9ce7a000- 7f3a9cf63000 Deferred crypt32<elf>
\-PE 7f3a9ce90000- 7f3a9cf63000 \ crypt32
ELF 7f3a9cf63000- 7f3a9cf93000 Deferred iphlpapi<elf>
\-PE 7f3a9cf70000- 7f3a9cf93000 \ iphlpapi
ELF 7f3a9cf93000- 7f3a9cfb0000 Deferred wsock32<elf>
\-PE 7f3a9cfa0000- 7f3a9cfb0000 \ wsock32
ELF 7f3a9cfb0000- 7f3a9cff2000 Deferred ws2_32<elf>
\-PE 7f3a9cfc0000- 7f3a9cff2000 \ ws2_32
ELF 7f3a9cff2000- 7f3a9d082000 Deferred shlwapi<elf>
\-PE 7f3a9d000000- 7f3a9d082000 \ shlwapi
ELF 7f3a9d082000- 7f3a9d0b0000 Deferred msacm32<elf>
\-PE 7f3a9d090000- 7f3a9d0b0000 \ msacm32
ELF 7f3a9d0b0000- 7f3a9d149000 Deferred rpcrt4<elf>
\-PE 7f3a9d0c0000- 7f3a9d149000 \ rpcrt4
ELF 7f3a9d149000- 7f3a9d2ec000 Deferred ole32<elf>
\-PE 7f3a9d170000- 7f3a9d2ec000 \ ole32
ELF 7f3a9d2ec000- 7f3a9d3b2000 Deferred winmm<elf>
\-PE 7f3a9d300000- 7f3a9d3b2000 \ winmm
ELF 7f3a9d3b2000- 7f3a9d3cd000 Deferred version<elf>
\-PE 7f3a9d3c0000- 7f3a9d3cd000 \ version
ELF 7f3a9d3cd000- 7f3a9d45f000 Deferred advapi32<elf>
\-PE 7f3a9d3e0000- 7f3a9d45f000 \ advapi32
ELF 7f3a9d45f000- 7f3a9d5dd000 Deferred gdi32<elf>
\-PE 7f3a9d470000- 7f3a9d5dd000 \ gdi32
ELF 7f3a9d5dd000- 7f3a9d83d000 Deferred user32<elf>
\-PE 7f3a9d600000- 7f3a9d83d000 \ user32
ELF 7f3a9d93d000- 7f3a9d966000 Deferred imm32<elf>
\-PE 7f3a9d940000- 7f3a9d966000 \ imm32
ELF 7f3a9da67000- 7f3a9dc79000 Deferred libnss_files.so.2
ELF 7f3a9dc79000- 7f3a9de85000 Deferred libnss_nis.so.2
ELF 7f3a9de85000- 7f3a9e09e000 Deferred libnsl.so.1
ELF 7f3a9e09e000- 7f3a9e2a7000 Deferred libnss_compat.so.2
ELF 7f3a9f987000- 7f3a9fb8d000 Deferred libxdmcp.so.6
ELF 7f3a9fb8d000- 7f3a9fd91000 Deferred libxau.so.6
ELF 7f3a9fd92000- 7f3a9ffa4000 Deferred libdrm.so.2
ELF 7f3a9ffa4000- 7f3aa01aa000 Deferred libxxf86vm.so.1
ELF 7f3aa01aa000- 7f3aa03cc000 Deferred libxcb.so.1
ELF 7f3aa03cd000- 7f3aa05d2000 Deferred libxcb-dri2.so.0
ELF 7f3aa05d2000- 7f3aa07eb000 Deferred libxcb-glx.so.0
ELF 7f3aa07eb000- 7f3aa0b25000 Deferred libx11.so.6
ELF 7f3aa0b26000- 7f3aa0d28000 Deferred libx11-xcb.so.1
ELF 7f3aa0d28000- 7f3aa0f2e000 Deferred libxfixes.so.3
ELF 7f3aa0f2e000- 7f3aa1131000 Deferred libxdamage.so.1
ELF 7f3aa1132000- 7f3aa1344000 Deferred libxext.so.6
ELF 7f3aa1344000- 7f3aa1575000 Deferred libglapi.so.0
ELF 7f3aa1575000- 7f3aa1778000 Deferred libxshmfence.so.1
ELF 7f3aa1779000- 7f3aa1980000 Deferred libxcb-sync.so.1
ELF 7f3aa1980000- 7f3aa1b83000 Deferred libxcb-present.so.0
ELF 7f3aa1b83000- 7f3aa1d86000 Deferred libxcb-dri3.so.0
ELF 7f3aa1d87000- 7f3aa1fb0000 Deferred libexpat.so.1
ELF 7f3aa1fb0000- 7f3aa21ca000 Deferred libz.so.1
ELF 7f3aa21ca000- 7f3aa23e0000 Deferred libgcc_s.so.1
ELF 7f3aa23e1000- 7f3aa26ea000 Deferred libm.so.6
ELF 7f3aa26ea000- 7f3aa295e000 Deferred libgl.so.1
ELF 7f3aa295e000- 7f3aa2b66000 Deferred librt.so.1
ELF 7f3aa2ee9000- 7f3aa30ed000 Deferred libdl.so.2
ELF 7f3aa30ed000- 7f3aa34b7000 Deferred libc.so.6
ELF 7f3aa34b8000- 7f3aa36d5000 Deferred libpthread.so.0
ELF 7f3aa36d5000- 7f3aa3a7b000 Export libwine.so.1
ELF 7f3aa3a7b000- 7f3aa3abb000 Deferred gameoverlayrenderer.so
ELF 7f3aa3abd000- 7f3aa3ce5000 Deferred ld-linux-x86-64.so.2
ELF 7ffed47ba000- 7ffed47bb000 Deferred [vdso].so

Couldn't find any fix yet.

**Comment by kisak-valve** [comment]
Hello @Rasputinbkz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3189#issuecomment-848197711.
