### ISSUE TITLE
Quake Champions PTS (743650)

### ISSUE THREAD

**Issue by d3rhans** [ValveSoftware/Proton#4867]
# Compatibility Report
- Name of the game with compatibility issues: Quake Champions PTS
- Steam AppID of the game: 743650

## System Information
- GPU: NVIDIA RTX 2060
- Driver/LLVM version: nvidia 460.80 and 460.56
- Kernel version: 5.12.7 (previously also several 5.11 versions)
- Link to full system information report as [Gist](https://gist.github.com/d3rhans/7354f21e4a4a7935f79795da91ae2ea4):
- Proton version: 6.3.4 also tested 5.13-6, Proton Experimental and several Proton-GE builds (6.1-GE2, G.8-GE2, 6.9-GE1)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-743650.log](https://github.com/ValveSoftware/Proton/files/6563887/steam-743650.log)

## Symptoms 
Game crashes immediately, doesn't even show a black screen or anything else. Quake Champions PTS (Public Test Server) is the test/beta version of Quake Champions (Steam AppID: 611500) and will become the live version in ~4 weeks. Quake Champions works perfectly fine with any recent Proton version, so did previous versions of PTS.

I tried with different Proton versions, NVIDIA driver versions, Kernels, display managers (Gnome and i3) and multiple variants of launch options (none, PROTON_NO_ESYNC, PROTON_NO_FSYNC, PROTON_USE_WINED3D and combinations). The result is always the same.

I asked two other players that (at least sometimes) play the game on Linux and they confirmed the issue.

## Reproduction
- Install latest PTS build (Form the Steam store page of Quake Champions, there is a link under the Early Access warning)
- Launch Quake Champions PTS with any recent proton version

**Comment by kisak-valve** [comment]
Hello @d3rhans, some possible lines of interest from your log: `fixme:bthpropscpl:BluetoothFindFirstRadio (000000000022F7E8 000000000022F7E0): stub!` immediately followed by and access violation (c0000005) and `wine: Unhandled page fault on read access to 0000000000000000 at address 0000000141F61AAE (thread 0118), starting debugger...`.

**Comment by d3rhans** [comment]
Hi, thanks for your prompt reply. I am following things in the Quake discord and as it seems their are at least some crashes on Windows 7 and 10 which may or may not be related to this. Those supposedly were fixed before I opened this issue - but seems like they aren't.

I'll see how this plays out and update this issue accordingly when new versions of PTS are released and when it goes live.

**Comment by Eonfge** [comment]
## Summer 2021 update breaks Quake Champions

### Release notes
https://quake.bethesda.net/en/news/2WsLdFFKtoQRmjvrKUebWA

<details><summary>Stacktrace</summary><p>

```
Unhandled exception: page fault on read access to 0x00000000 in 64-bit code (0x0000000141f582fe).
Register dump:
 rip:0000000141f582fe rsp:000000000022e630 rbp:000000000022e740 eflags:00010246 (  R- --  I  Z- -P- )
 rax:000000000000008b rbx:ffffffffffffffff rcx:000000000022ef78 rdx:0000000000000101
 rsi:000000000022ef78 rdi:ffffffff80000002  r8:000000000022e6c0  r9:0000000000b6fe60 r10:0000000000000000
 r11:000000000022e5a8 r12:0000000000000000 r13:0000000142d02b80 r14:0000000000cd0960 r15:0000000000000101
Stack dump:
0x000000000022e630:  0000000141f582c6 0000000141f70959
0x000000000022e640:  ffffffffffffffff 000000000022ef78
0x000000000022e650:  0000020000000070 ffffffffffffff68
0x000000000022e660:  00000001423d8720 ba246beb10b7a200
0x000000000022e670:  000000007f0102b0 0000000000000001
0x000000000022e680:  0000000000cd09e0 0000000000000000
0x000000000022e690:  0000000000000001 0000000000000000
0x000000000022e6a0:  0000000000000000 00007fe7a8659cf8
0x000000000022e6b0:  00000000007c007c 000000000022e6f0
0x000000000022e6c0:  00007fe700000030 0000000000000000
0x000000000022e6d0:  000000000022e6b0 0000000000000040
0x000000000022e6e0:  0000000000000000 0000000000000000
Backtrace:
=>0 0x0000000141f582fe EntryPoint+0xfffa7e82() in quakechampions (0x000000000022e740)
  1 0x0000000141f582c6 EntryPoint+0xfffa7e49() in quakechampions (0x000000000022e740)
  2 0x0000000141f70959 EntryPoint+0xfffc04dc() in quakechampions (0x000000000022e740)
  3 0x0000000141f23377 EntryPoint+0xfff72efa() in quakechampions (0x000000000022f030)
  4 0x0000000141f230e9 EntryPoint+0xfff72c6c() in quakechampions (0x000000000022f910)
  5 0x0000000141f1836f EntryPoint+0xfff67ef2() in quakechampions (0x0000000000000000)
  6 0x0000000141f1610d EntryPoint+0xfff65c90() in quakechampions (0x0000000000000000)
  7 0x0000000140160f74 EntryPoint+0xfe1b0af7() in quakechampions (0x00000003af6ee560)
  8 0x00000003af68de3a EntryPoint+0x2fffa1f69() in ucrtbase (0x00000003af6ee560)
  9 0x0000000141fb035d EntryPoint+0xfffffee0() in quakechampions (0x0000000000000000)
  10 0x000000007b62c809 EntryPoint+0xffffffffffffffff() in kernel32 (0x0000000000000000)
  11 0x000000007bc59803 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)
0x0000000141f582fe EntryPoint+0xfffa7e82 in quakechampions: movq	(%r10),%r10
```

</p></details>

### Full log
[steam-611500.log](https://github.com/ValveSoftware/Proton/files/6750277/steam-611500.log)

**Comment by kisak-valve** [comment]
Hello @Eonfge, your log looks similar to the opening post with `fixme:bthpropscpl:BluetoothFindFirstRadio (000000000022F620 000000000022F618): stub!` immediately followed by an access violation (c0000005).

**Comment by Eonfge** [comment]
:thinking: I did not play Quake Champions since April, so It might have broken since then, although there are reports of it working on [ProtonDB](https://www.protondb.com/app/611500) as recent as three weeks.

**Comment by d3rhans** [comment]
The changes that caused the crash I initially reported for PTS went live this afternoon for the main game. The reason it isn't running with proton anymore are some built-in Anti-Cheat/Anti-Tamper measures that seem to be custom for this game. 

@kisak-valve to my understanding the Bluetoth stuff can be ignored if I recall correctly, that message showed up in the logs previous to the update, not sure though. The access violation is where it fails though.

@Eonfge the reports on protondb were before today's update, so they are outdated. I'll post a new report there later.

I don't know what exactly they've implemented, but the game also refuses to run on Windows, if any program attempts to do anything with it's memory, tries to inject dlls or something like that (e.g. afterburner, rivatuner, programs that do macros for keyboards/gamepads etc.)

I am not sure if anything can be done about this from proton/wine side

**Comment by kisak-valve** [comment]
Hello @d3rhans, let's not merge this compatibility report with 611500. Instead, add a note to #225 with a fresh log for the game when it is run with that appid. The alternative is closing this compatibility report and continuing the discussion on #225.

**Comment by d3rhans** [comment]
@kisak-valve ok, makes sense. I'll get a new log and everything later this evening, update #225 accordingly and close this one, as PTS is just the test version of QC and down atm anyways.

**Comment by d3rhans** [comment]
Updated #225 - will close this one.

**Comment by Zeioth** [comment]
On wayland (manjaro-sway), the game launches fine, but the buttons are not clickable, so there's no way to start a match.

EDIT: This seem to be [an issue of sway itself ](https://github.com/swaywm/sway/issues/4857) when passing an screen position to the config file.

After removing the 'position' parameter of the output. Everything works well.
