### ISSUE TITLE
Far Cry 5 (552520)

### ISSUE THREAD

**Issue by juanandresdavila** [ValveSoftware/Proton#4869]
# Compatibility Report
- Name of the game with compatibility issues: Far Cry 5
- Steam AppID of the game: 

## System Information
- GPU:  RX580
- Driver/LLVM version:  Version: 21.1.0
- Kernel version:  5.8.0-53-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ZAD4YTV/fd4fe18d5854c0f6fea17a475db1306c
- Proton version: 6.3-4

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

I can't play with a friend, I tried to invite him and he can't join and the other way around. When I touch some Ubisoft features, it gives me an error, the attached image, is that error.

## Reproduction

![image](https://user-images.githubusercontent.com/69881939/120086647-f7dd7a00-c0b6-11eb-84e7-dcd6b1d194ea.png)

**Comment by kisak-valve** [comment]
Hello @ZAD4YTV, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2356#issuecomment-850911629.
