### ISSUE TITLE
DOOM Eternal with Nvidia graphics

### ISSUE THREAD

**Issue by lothrond** [ValveSoftware/Proton#4872]
While attempting to launch DOOM Eternal I would get a prompt telling me that my Nvidia graphics drivers were out of date.

I just wanted to share a few fixes that allow me to play this game. These fixes can be found 
[here](https://gist.github.com/lothrond/9f67338cb3f66a05f128e61cba7ec952).

I made this gist in response to [this](https://github.com/ValveSoftware/Proton/issues/3773) open issue.

Perhaps the two can be linked together?

**Comment by kisak-valve** [comment]
Hello @lothrond, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3773#issuecomment-851428342.
