### ISSUE TITLE
SpellForce: Platinum Edition (39540)

### ISSUE THREAD

**Issue by ZarimSF** [ValveSoftware/Proton#4873]
# Compatibility Report
- Name of the game with compatibility issues: SpellForce: Platinum Edition
- Steam AppID of the game: 39540

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 18.3.6
- Kernel version: 4.19.0-16-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ZarimSF/c39da568493312ee48d1fe4e208ea50e
- Proton version: Proton Experimental
- Log: [steam-39540.log](https://github.com/ValveSoftware/Proton/files/6570010/steam-39540.log)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
When right- or middle-clicking, the click does not release anymore. 
Afterwards, you are not able to give any mouse button inputs, not even in the menu.
The same does not happen for left clicks. 

## Reproduction
Perform a right or middle click in the game (menu is fine) that lasts longer than a couple milliseconds. If you almost instantaneously release the mouse button, the click releases normally.

## Notes
This only happens with Proton Experimental, with other releases this issue does not exist.
I understand that the designation "Experimental" doesn't come from nowhere, however the performance is a *lot* better compared to 6.3-4 and prior. I am mainly hoping, that someone might know what causes the issue or has experienced something similar.

**Comment by kisak-valve** [comment]
Hello @ZarimSF, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/686#issuecomment-851485607.

**Comment by ZarimSF** [comment]
Sorry about that, I thought it was one issue per bug. If I had thought a bit longer I could have guessed that it was meant as one issue per game.
Thanks for explaining and moving
