### ISSUE TITLE
GTX 1650 recognized as a GTX 470

### ISSUE THREAD

**Issue by eXt73** [ValveSoftware/Proton#4874]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: GTX 1650 Max-Q
- Driver/LLVM version: Nvidia 465.31
- Kernel version: 5.12.8-ext73-91.8-ryzen-3
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

 later ;)

## Symptoms 

Battlefield V, Ghostrunner - DX11, DX12 > recognize GTX 1650 as GTX 470, which results in the lack of support for DX 11 and DX 12, and the above mentioned games cannot be run.

screenshots: https://www.dropbox.com/sh/hoy7rk4yln2cdw2/AADLaVmofGlboZMglLjj8I9ia?dl=0

Regards

Tomek

**Comment by kisak-valve** [comment]
Hello @eXt73, this is a cosmetic issue with upstream wine. Any card wine hasn't been taught about will use a generic name with roughly the same features. For DirectX 11+ capable nVidia cards that is the GTX 470 (https://source.winehq.org/git/wine.git/blob/HEAD:/dlls/wined3d/directx.c#l884).

In almost all cases, that should not prevent DXVK or VKD3D-PROTON from translating DirectX 11/12 to Vulkan.

**Comment by eXt73** [comment]
Hi Kisak

But unfortunately, it results in the fact that none of these games start on the GTX 1650. I tested on the MSI Prestige 14 11gen and on the ASUS ROG Flow x13 - here is an example. For example, under the GTX 1060 such a message does not appear and everything works.

**Comment by Leopard1907** [comment]
@eXt73 `WINEDLLOVERRIDES=dxgi=n %command%`

Can you try with DXVK dxgi? Using launch option above should be enough.

**Comment by eXt73** [comment]
Hi, thanks for the information - I'll check at home in the evening and give you info.

**Comment by eXt73** [comment]
@Leopard1907 You're right, the workaround works ! The question is why not out of the box. After all, such solutions are 'to be done' ... we use 'in the background' also dynamically built solutions depending on the configuration on which our solution for the optimization of xUbuntu [NeteXt73] is runing. After all, Proton or Steam itself can implement such solutions in the background - including dependencies: machine configuration | the game ... Thanks again ;)

**Comment by Leopard1907** [comment]
https://github.com/ValveSoftware/Proton/issues/4835#issuecomment-845242511

DXVK dxgi will be default soon. Wine dxgi causes multiple problems.

**Comment by eXt73** [comment]
@Leopard1907 Thanks for the info

**Comment by Leopard1907** [comment]
@eXt73 Can you try with Proton 6.3-5 now, without workaround? 6.3-5 switched to using DXVK dxgi by default so your gpu should be recognized properly by default.

**Comment by eXt73** [comment]
Of course, Experimental works without a workaround - this time I use Ryzen 9 + RTX 3050 Ti [also Asus ROG Flow x13]. I will see in a moment how it is under the latest 6.3 - I just had an update.

**Comment by eXt73** [comment]
Yes, I can confirm, also version 6.3-5 works OOTB. Thanks.

**Comment by Leopard1907** [comment]
Then you can close the issue since it is solved.

Yw.

**Comment by eXt73** [comment]
Solved
