### ISSUE TITLE
Proton 6.3-4 DirectX 11 won't install for Rust

### ISSUE THREAD

**Issue by EscapedAI** [ValveSoftware/Proton#4887]
# Compatibility Report
- Name of the game with compatibility issues: Rust
- Steam AppID of the game: 252490

## System Information
- GPU: Advanced Micro Devices [AMD/ATI] Vega 10 XT [Radeon RX Vega 64]
- Driver/LLVM version: 4.6 Mesa 21.1.2 - kisak-mesa PPA
- Kernel version: 4.15.0-144-generic x86_64
- Link to full system information report as: [Gist](https://gist.github.com/EscapedAI/59e8d7fad60b05f264412f948bb08680)
- Proton version: 6.3-4

Vulkan and 32-bit is enabled, I used [this guide](https://github.com/lutris/docs/blob/master/InstallingDrivers.md) for my drivers, which is more detailed than [your guide](https://github.com/ValveSoftware/Proton/wiki/Requirements).

## I confirm:
- [Y] that I haven't found an existing compatibility report for this game.
- [Y] that I have checked whether there are updates for my system available.

[steam-252490.log](https://github.com/ValveSoftware/Proton/files/6604320/steam-252490.log)

## Symptoms 

When running Rust, it will either not try or will get stuck half way with installing DirectX 11

![DirectX-hangs](https://user-images.githubusercontent.com/85445538/120928066-122cde80-c6db-11eb-8f4b-c1292af39b51.png)

## Reproduction

I am not sure how to reproduce this. It seems to possibly be specific to my system. 

Rust worked on Proton 5.13-6 three months ago but for Linux gamers only 6.3-4 works now and that won't install Dx11 for me. 

I have:
- tried reinstalling Steam, including deleting my /.steam folder. 
- re-installed Proton 6.3-4 using Steam Tools. 
- re-installed Rust multiple times.
- installing the game and Proton on my boot NVME instead of the ZFS RAID.
- tried deleting just the /pfx folder
- used WINEPREFIX="../pfx" winetricks to install DirectX 11 manually.
- removing just the "HasRunKey" from the user.reg file.

**Comment by kisak-valve** [comment]
Hello @EscapedAI, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3104#issuecomment-855408897.
