### ISSUE TITLE
Cloudpunk crash while gamepad is connected

### ISSUE THREAD

**Issue by ipr** [ValveSoftware/Proton#4889]
# Compatibility Report
- Name of the game with compatibility issues:Cloudpunk
- Steam AppID of the game:746850

## System Information
- GPU: AMD Radeon RX Vega
- Driver/LLVM version: VEGA10, DRM 3.40.0, 5.12.9, LLVM 11.0.1
- Kernel version: 5.12.9
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:6.3-4 & Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game will crash on start when gamepad is connected. Disconnecting gamepad makes game start but obviously gamepad is not available then,
Problem affects plain Wine 6.10 as well. Crash dump points to HID-device caps handling.

## Reproduction
1. Connect gamepad (PS4 controller)
2. Start game
3. Observe game crash

**Comment by ipr** [comment]
Unhandled exception: page fault on read access to 0x00000000 in 64-bit code (0x00000000664c2665).
Register dump:
 rip:00000000664c2665 rsp:000000000011eee0 rbp:000000000011ef70 eflags:00010246 (  R- --  I  Z- -P- )
 rax:0000000000000000 rbx:0000000000000000 rcx:0000000000000000 rdx:000000000011efa0
 rsi:000000000011efa0 rdi:0000000000000000  r8:000000000011e790  r9:000000007bc679fc r10:0000000000000008
 r11:0000000000000000 r12:000000000bb83e00 r13:000000000011efa0 r14:000000000011ef64 r15:000000006ebd0eb7
Stack dump:
0x000000000011eee0:  000000000011eef4 000000000000000c
0x000000000011eef0:  000000000011ef04 000000000000000c
0x000000000011ef00:  000000000011ef80 0000000000ae0830
0x000000000011ef10:  000000000011ef80 0000000000ae0830
0x000000000011ef20:  000000000011ef80 000000006eb6fcbd
0x000000000011ef30:  0000000001617470 0000000000000044
0x000000000011ef40:  000000000011efb1 0000000006080000
0x000000000011ef50:  000000000011ef80 000000007b61bfff
0x000000000011ef60:  0000000c00000000 000000007b026e3f
0x000000000011ef70:  11cff16f4d1e55b2 300000111100cb88
0x000000000011ef80:  4d1e55b200000020 1100cb8811cff16f
0x000000000011ef90:  0000000130000011 000000000bb80e70
Backtrace:
=>0 0x00000000664c2665 HidP_GetCaps+0x15(PreparsedData=(nil), Capabilities=0x11efa0) [O:\usr\src\wine\dlls\hid\hidp.c:223] in hid (0x000000000011ef70)
  1 0x000000006eb6fcbd find_devices+0x17c() [O:\usr\src\wine\dlls\user32\rawinput.c:213] in user32 (0x000000000011ef70)
  2 0x000000006eb70300 GetRawInputDeviceList+0x2f(devices=0x1046f50, device_count=0x11fa30, size=0x10) [O:\usr\src\wine\dlls\user32\rawinput.c:435] in user32 (0x000000000011f190)
  3 0x00000001805e20fb EntryPoint+0xff42a052() in unityplayer (0x000000000011f190)
  4 0x00000001805ddae1 EntryPoint+0xff425a38() in unityplayer (0x000000000001004e)
  5 0x00000001805f40ef EntryPoint+0xff43c046() in unityplayer (0x000000000011fbb0)
  6 0x00000001805f874b EntryPoint+0xff4406a2() in unityplayer (0x0000000000000000)
  7 0x00000001400011fa EntryPoint+0xffffff91() in cloudpunk (0x0000000000000000)
  8 0x000000007b62c959 BaseThreadInitThunk+0x8(unknown=<is not available>, entry=<is not available>, arg=<is not available>) [O:\usr\src\wine\dlls\kernel32\thread.c:61] in kernel32 (0x0000000000000000)
  9 0x000000007bc56c43 RtlUserThreadStart+0x82(entry=0x140001268, arg=0x67ff0000) [O:\usr\src\wine\dlls\ntdll\thread.c:165] in ntdll (0x0000000000000000)
0x00000000664c2665 HidP_GetCaps+0x15 [O:\usr\src\wine\dlls\hid\hidp.c:223] in hid: cmpl	$0x8491759,(%rbx)
223	    if (data->magic != HID_MAGIC)
Modules:
Module	Address					Debug info	Name (56 modules)
PE	          230000-          393000	Deferred        winmm
PE	          3a0000-          3e5000	Deferred        jsproxy
PE	          3f0000-          760000	Deferred        windowscodecs
PE	          e60000-          e6f000	Deferred        api-ms-win-core-com-l1-1-1
PE	         2f30000-         4cd7000	Deferred        gameassembly
PE	         6080000-         60a6000	Deferred        xinput1_3
PE	         9a40000-         9cd8000	Deferred        d3d11
PE	         a030000-         a430000	Deferred        comctl32
PE	        61540000-        6162f000	Deferred        advapi32
PE	        62980000-        6298e000	Deferred        api-ms-win-core-localization-l1-2-1
PE	        62c80000-        62db6000	Deferred        wbemprox
PE	        62dc0000-        62fb9000	Deferred        rpcrt4
PE	        63280000-        6329b000	Deferred        version
PE	        639c0000-        63a06000	Deferred        shcore
PE	        64840000-        6492a000	Deferred        shlwapi
PE	        64cc0000-        65094000	Deferred        oleaut32
PE	        66040000-        66085000	Deferred        bcrypt
PE	        664c0000-        664eb000	Dwarf           hid
PE	        66c40000-        66c4e000	Deferred        api-ms-win-appmodel-runtime-l1-1-2
PE	        67600000-        6760d000	Deferred        api-ms-win-core-string-l1-1-0
PE	        67640000-        676b2000	Deferred        winepulse
PE	        67b40000-        67bd0000	Deferred        mmdevapi
PE	        68300000-        6843b000	Deferred        combase
PE	        68f80000-        68fa5000	Deferred        wsock32
PE	        69400000-        694f7000	Deferred        winhttp
PE	        69740000-        697ab000	Deferred        propsys
PE	        69e40000-        69e9e000	Deferred        msacm32
PE	        6a200000-        6a654000	Deferred        ole32
PE	        6aa80000-        6aa8d000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	        6b300000-        6b30d000	Deferred        api-ms-win-core-localization-obsolete-l1-2-0
PE	        6b580000-        6b58e000	Deferred        api-ms-win-core-winrt-l1-1-0
PE	        6ba00000-        6ba90000	Deferred        sechost
PE	        6bac0000-        6bc3f000	Deferred        setupapi
PE	        6c7c0000-        6cd5d000	Deferred        gdi32
PE	        6dc80000-        6dc8e000	Deferred        api-ms-win-core-synch-l1-2-0
PE	        6e200000-        6e20e000	Deferred        api-ms-win-core-winrt-string-l1-1-0
PE	        6e6c0000-        6e958000	Deferred        crypt32
PE	        6ea40000-        6ea5b000	Deferred        dwmapi
PE	        6eb00000-        6f18a000	Dwarf           user32
PE	        6fd80000-        6fd8d000	Deferred        api-ms-win-core-datetime-l1-1-1
PE	        6fec0000-        6fece000	Deferred        api-ms-win-core-sysinfo-l1-2-1
PE	        70940000-        70c22000	Deferred        ucrtbase
PE	        71000000-        7104d000	Deferred        imm32
PE	        7a850000-        7a854000	Deferred        opengl32
PE	        7b000000-        7b30c000	Deferred        kernelbase
PE	        7b600000-        7b91b000	Dwarf           kernel32
PE	        7bc00000-        7be6e000	Dwarf           ntdll
PE	       140000000-       1400a3000	Export          cloudpunk
PE	       180000000-       18173d000	Export          unityplayer
PE	    7f372a850000-    7f372a85b000	Deferred        winspool
PE	    7f372c6c0000-    7f372c6c4000	Deferred        wined3d
PE	    7f372c970000-    7f372c974000	Deferred        dxgi
PE	    7f372d3f0000-    7f372d3f4000	Deferred        winex11
PE	    7f372e290000-    7f372e294000	Deferred        iphlpapi
PE	    7f372e3d0000-    7f372eca7000	Deferred        shell32
PE	    7f372fb90000-    7f372fb96000	Deferred        ws2_32
Threads:
process  tid      prio (all id:s are in hex)
00000020 start.exe
	00000024    0
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	00000070    0
	000000cc    0
	000000e0    0
00000044 winedevice.exe
	00000048    0
	00000054    0
	00000058    0
	0000005c    0
00000060 plugplay.exe
	00000064    0
	00000074    0
	00000078    0
	0000007c    0
00000068 explorer.exe
	0000006c    0
	0000009c    0
	000000a0    0
000000c0 svchost.exe
	000000c4    0
	000000d0    0
	000000d4    0
000000d8 rpcss.exe
	000000dc    0
	000000e4    0
	000000e8    0
	000000ec    0
	000000f0    0
	000000f4    0
00000100 conhost.exe
	00000104    0
00000108 (D) H:\SteamLibraryAlien\steamapps\common\Cloudpunk\Cloudpunk.exe
	0000010c    0 <==
	00000118    0
	0000011c    0
	00000120    0
	00000124    0
	00000128    0
	0000012c    0
	00000130    0
	00000134    0
	00000138    0
	0000013c    0
	00000140    0
	00000144    0
	00000148    0
	0000014c    0
	00000150    0
	00000154    0
	00000158   -2
	0000015c   -2
	00000160   -2
	00000164   -2
	00000168   -2
	0000016c   -2
	00000170   -2
	00000174   -2
	00000178   -2
	0000017c   -2
	00000180   -2
	00000184   -2
	00000188   -2
	0000018c   -2
	00000190   -2
	00000194   -2
	00000198   -1
	0000019c    0
	000001a4    0
	000001a8    0
	000001ac    0
	000001b0    0
	000001b4   15
	000001b8    0
	000001bc    2
	000001c0   15
	000001c4    2
00000110 UnityCrashHandler64.exe
	00000114    0
	000001a0    0
System information:
    Wine build: wine-6.10
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 5.12.9

**Comment by ipr** [comment]
[steam-746850.log](https://github.com/ValveSoftware/Proton/files/6609002/steam-746850.log)

**Comment by kisak-valve** [comment]
Hello @ipr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3800#issuecomment-855907159.

As a side note, please use a [gist](https://gist.github.com) or other pastebin service when attaching large copy/pastes, instead of posting them inline with the comment so that it's easier to have a conversation along with the technical details.
