### ISSUE TITLE
Make Proton-related bugs on CW bugtracker available to the public

### ISSUE THREAD

**Issue by tannisroot** [ValveSoftware/Proton#4890]
Lately, commit messages for Proton have been referencing bugs on CW's bugtracker quite a lot, quite often without no other clarification for the changes.
Although I am sure it wasn't intentional, but it makes it harder for people that don't work for CW or Valve to understand the work that's being done for Proton and perhaps make use of it in other Linux Gaming projects, such as TKG PKGBUILDS, Lutris, and GE-Proton. 
Additionally, whatever information is discussed in those bugs is not available to independent developers, who might want to explore those bugs themselves to get a better understanding of the issue, and maybe even make a contribution.
I understand that neither Codeweavers nor Valve owe anything to anyone, but it would be really awesome if bugs referenced in Proton's git history were open to be viewed to the public. I can already try to look up those bugs on CW's website (https://www.codeweavers.com/support/bugs), but when I do, I am denied access. 
If those bugs don't contain anything sensitive, they could be open to be viewed by public as they are. But if they do have something sensitive, then at least referencing the issue # from Proton's Github in git messages would still be very useful.

**Comment by GloriousEggroll** [comment]
While I don't work for CW, coming from a similar side (Red Hat), I do not feel this request is feasible nor fair to CW. They provide plenty already to the community, including the wine source and wine bug tracker. Speaking from experience I know at Red Hat we attach client cases to bugs which are not all visible to the public, and client information is confidential. Keep in mind CW also provide commercial products. I feel they provide more than enough as is, especially considering most of the bugs they resolved end up with the fixes in our hands when they are ready to be made public. Until they are officially released, I don't feel it's fair to ask for more from them. Just my two cents. "Don't bite the hand that feeds" as they say.

**Comment by kisak-valve** [comment]
Hello @tannisroot, how CodeWeavers chose to manage their issue tracker is at their discretion and outside the scope of this project. The developers who are triaging technical issues with games run with Proton are getting feedback on many different issue trackers (and other sources) and not all of those discussions will be publicly available. Personally, I appreciate any and all details and references that get added to the commit messages.

As a side note, this is why we ended up making the counter-cultural choice to have one issue report per unofficially supported game title, even with largely popular games. With Proton being introduced into a well developed community, there already were multiple issue trackers saturated with technical riddles to solve, there was little value to add in effectively duplicating the feedback in WineHQ's bug tracker here along with the overhead that comes along with managing what issues are current. By having one issue per unofficially supported game title here, we also don't need to reject mildly out-of-scope feedback meant for upstream wine or third party Proton builds.

**Comment by tannisroot** [comment]
Being able to provide feedback was never really a request, I am fully aware how unhelpful it can be for a product like Proton, but at least knowing what the bugs (which would have been read-only for the public) were about would have been nice.
Oh well.
