### ISSUE TITLE
Ty the Tasmanian Tiger 3 (411980)

### ISSUE THREAD

**Issue by CalebQ42** [ValveSoftware/Proton#4891]
# Compatibility Report
- Name of the game with compatibility issues: Ty the Tasmanian Tiger 3
- Steam AppID of the game: 411980

## System Information
- GPU: RTX 3070
- Driver/LLVM version: 465.31-1
- Kernel version: 5.12.9.zen1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/CalebQ42/261ef1ed69d127c2d68ef841e1c32cd2
- Proton version: All of them.

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

[steam-411980.log](https://github.com/ValveSoftware/Proton/files/6621149/steam-411980.log)

## Symptoms

The game fails to launch. After a bit of experimentation, it seems the game might not be able to communicate with the Steam api. This problem also seems to affect the second game, but not the first. Varified to be working on Windows.

## Reproduction

Try to run the game. Tried on all available Proton versions including the latest GE version.

**Comment by kisak-valve** [comment]
Hello @CalebQ42, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2271#issuecomment-857651044.
