### ISSUE TITLE
Foxhole stop working. Black Screen and closes upon start.

### ISSUE THREAD

**Issue by pbaesse** [ValveSoftware/Proton#4895]
# Compatibility Report
- Foxhole
- Steam AppID of the game: 505460

## System Information
- GPU: NVIDIA GeForce GTX 1060 6GB
- GPU DRIVER: NVIDIA 460.73.01
- KERNEL: 5.4.0-72-generic
- System: https://gist.github.com/pbaesse/4d2bd179bfeee0501e8fe4cd18f74b64
- Proton version: Default

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 

- It used to work amazingly, but the game will not even start anymore
- Black Screen and closes upon start

## Reproduction
- Just try to start the game.

**Comment by kisak-valve** [comment]
Hello @pbaesse, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/725#issuecomment-860037952.

As a side note, "Proton Version: Default" means absolutely nothing. There is no default version of Proton for non-whitelisted game. At some point you manually chose a version to run other titles with use in Steam's settings.

**Comment by pbaesse** [comment]
"As a side note, "Proton Version: Default" means absolutely nothing. There is no default version of Proton for non-whitelisted game. At some point you manually chose a version to run other titles with use in Steam's settings."

I was almost sure, it was wrong hoHOHO Thanks for the heads-up!
