### ISSUE TITLE
Ascension game doesn't launch possibly a game engine compatibility issue.

### ISSUE THREAD

**Issue by khumi01** [ValveSoftware/Proton#4898]
# Compatibility Report
- Name of the game with compatibility issues: Ascension
- Steam AppID of the game: 320430

## System Information
- GPU: Intel HD 3000
- Driver/LLVM version: OpenGL version string: 3.0 Mesa 21.1.2
- Kernel version: 5.12.10-182.current
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/khumi01/d9142e2bd9bf8bce0435b5c62085bccf
- Proton version: 5.0-10

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-320430.log](https://github.com/ValveSoftware/Proton/files/6649160/steam-320430.log)

## Reproduction
1.Launch Steam Client on Solus OS.
2.Go to 'Library' on Steam.
3.Right click on 'Ascension' on the game list provided by the 'Library'.
4.Click 'Properties...' go to the 'Compatibility' tab.
5.Check the box next to where it says 'Force the use of a specific Steam Play compatibility tool'.
6.Select 'Proton 5.0-10' from the drop menu then exit.
7.Launch the game by clicking 'Play' button on 'Library' where it says 'Ascension'.
8.After few that games doesn't launch it does indicate running for few seconds but the 'Play' button turns green again
   indicating a failed launch.

**Comment by khumi01** [comment]
The game still works with W. I. N. E. version I believe version 6 something.

**Comment by kisak-valve** [comment]
Hello @khumi01, Proton uses DXVK to translate DirectX 9/10/11 to Vulkan, and your Sandybridge generation Intel graphics does not support Vulkan, which makes your system unsupported by Proton in general.

Your log contains:
```
err:vulkan:wine_vk_instance_load_physical_devices Failed to enumerate physical devices, res=-3
err:vulkan:wine_vkCreateInstance Failed to load physical devices, res=-3
```
Which confirms that the game is trying to use Vulkan.

You might get lucky by setting the game's launch options to `PROTON_USE_WINED3D=1 %command%` which tells Proton to use wine's DirectX to OpenGL render path, but that setting comes with a significant performance penalty and is not considered supported. Alternatively, you could try `-force-glcore` or similiar Unity3D launch options from https://docs.unity3d.com/Manual/CommandLineArguments.html to get the game engine to use an OpenGL render path, but the game's developer may not have tested against those Unity backends to confirm they should work in the first place.

**Comment by khumi01** [comment]
> 
> 
> Hello @khumi01, Proton uses DXVK to translate DirectX 9/10/11 to Vulkan, and your Sandybridge generation Intel graphics does not support Vulkan, which makes your system unsupported by Proton in general.
> 
> Your log contains:
> 
> ```
> err:vulkan:wine_vk_instance_load_physical_devices Failed to enumerate physical devices, res=-3
> err:vulkan:wine_vkCreateInstance Failed to load physical devices, res=-3
> ```
> 
> Which confirms that the game is trying to use Vulkan.
> 
> You might get lucky by setting the game's launch options to `PROTON_USE_WINED3D=1 %command%` which tells Proton to use wine's DirectX to OpenGL render path, but that setting comes with a significant performance penalty and is not considered supported. Alternatively, you could try `-force-glcore` or similiar Unity3D launch options from https://docs.unity3d.com/Manual/CommandLineArguments.html to get the game engine to use an OpenGL render path, but the game's developer may not have tested against those Unity backends to confirm they should work in the first place.

thanks for the speedy response much apreciated it 👍
