### ISSUE TITLE
100% Orange Juice (282800): Game is not connecting with Steam.

### ISSUE THREAD

**Issue by MrThatKid** [ValveSoftware/Proton#490]
OS: Ubuntu 18.04.1, 64-bit, 4.15.0-23-generic kernel
HW: i7-4770T CPU, GeForce GTX 750 Ti GPU
Driver: NVIDIA 396.54
While the game itself plays fine, it appears that the game does not connect to Steam properly under Proton.
The in-game store (denoted as "Shopping" in the main menu) explicitly says "No Steam Connection"

Further testing in WINE with the Windows Steam client shows that the game needs a Steam connection to allow access to special events, like the (as of this posting) currently ongoing summer event.
In WINE, an option for the summer event would show up in the top right corner of the main menu, however this doesn't happen in Proton.

I do not know what else in the game requires a steam connection. If a connection is needed for user stats, it may explain #211

If you need specific logs from me, let me know what is needed!

**Comment by arzardk** [comment]
I think you should copy this issue in #211 because they keep one thread per one unofficial game.

**Comment by MrThatKid** [comment]
Oh. I wasn't sure how connected these two issues were, and I do see at least one game with more than one thread (Cuphead)
If others think I should post this in the other issue, then I'll do so and close this issue.

**Comment by kisak-valve** [comment]
Hello @MrThatKid, as @arzardk said we are using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue to https://github.com/ValveSoftware/Proton/issues/211#issuecomment-415998686.
