### ISSUE TITLE
Skyrim "Failed to initialize renderer" on Wayland

### ISSUE THREAD

**Issue by RavenOchlich** [ValveSoftware/Proton#4900]
# Compatibility Report
- Name of the game with compatibility issues: The Elder Scrolls V: Skyrim
- Steam AppID of the game: 72850

## System Information
https://gist.github.com/RavenOchlich/ab89e8b570c8a8540084b300fa1b2e3d

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game. One similar Issue is:  #4859
- [X ] that I have checked whether there are updates for my system available.

##Log File
https://gist.github.com/RavenOchlich/cc361f3de7a84c8658cdf71aadb3e7a6

## Symptoms 
The Launcher starts fine, but when i hit Play a messagebox opens with "Failed to initialize renderer". Changing the resolution or enable windowed mode doesn't changes the error. The game was running under Xorg (Awesome vm) fine. Now on Wayland(Sway) the error occurs.

## Reproduction
start Skyrim
hit Play in the Launcher
the Messagebox appears, hitting ok closes Skyrim

**Comment by kisak-valve** [comment]
Hello @RavenOchlich, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/460#issuecomment-861508554.
