### ISSUE TITLE
The King of Fighters XIII crashes just after the SNK/Playmore logo 

### ISSUE THREAD

**Issue by zelfir** [ValveSoftware/Proton#4901]
# Compatibility Report
- Name of the game with compatibility issues: The King of Fighters XIII
- Steam AppID of the game: 222940

## System Information
- GPU: RTX 2070 Super
- Driver/LLVM version: Nvidia 465.31
- Kernel version: 5.12.9-300.fc34.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/zelfir/f757abc479e47fc5b5d5202d37aaf6f8#file-gistfile1-txt
- Proton version: 1623347030 experimental-6.3-20210610

## I confirm:
- [v] that I haven't found an existing compatibility report for this game.
- [v] that I have checked whether there are updates for my system available.

## Symptoms 
The game crashes just after the SNK/Playmore logo

## Reproduction
Always
[steam-222940.log](https://github.com/ValveSoftware/Proton/files/6658347/steam-222940.log)

**Comment by kisak-valve** [comment]
Hello @zelfir, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/214#issuecomment-861793558.

**Comment by ranplayer** [comment]
@zelfir add the `-v`parameter to the Launch Options to bypass the intro logos and avoid the crash

**Comment by zelfir** [comment]
> @zelfir add the `-v`parameter to the Launch Options to bypass the intro logos and avoid the crash

Indeed passing the video seems to work.

**Comment by zelfir** [comment]
Now that I've been able to play the game I just noticed another issue with the gamepad detection.
I've a Sony DS4 and it's not detected by the game, which is expecting an Xbox 360 gamepad.
I don't know if it's a Steam Input bug or a general bug with the game.

**Comment by kisak-valve** [comment]
Hello @zelfir, please add that feedback to #214 and use that compatibility report for further discussion of this game.
