### ISSUE TITLE
SteamVR not working on Fedora 34

### ISSUE THREAD

**Issue by l33tllama** [ValveSoftware/Proton#4905]
# Compatibility Report
- Name of the game with compatibility issues: SteamVR
- Steam AppID of the game: 250820

## System Information
- GPU: AMD RX 5700 XT
- Driver/LLVM version: Mesa 21.1.2
- Kernel version: 5.12.10-300.fc34.x86_64
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental (Jun 19 2021)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-250820.log](https://github.com/ValveSoftware/Proton/files/6677616/steam-250820.log)
First few lines:
```
Using breakpad crash handler
Setting breakpad minidump AppID = 250820
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
653.679:00dc:00fc:trace:seh:NtQueryInformationThread (0xfffffffffffffffe,12,0x263fe2c,4,(nil))
654.682:00dc:00f4:trace:seh:NtQueryInformationThread (0xfffffffffffffffe,12,0x1a1fe2c,4,(nil))
654.682:0030:00ac:trace:seh:NtQueryInformationThread (0xfffffffffffffffe,12,0x386fe2c,4,(nil))
654.683:00dc:00f8:trace:seh:NtQueryInformationThread (0xfffffffffffffffe,12,0x202fe2c,4,(nil))
654.683:005c:0090:trace:seh:NtQueryInformationThread (0xfffffffffffffffe,12,0x204fe2c,4,(nil))
654.683:005c:0070:trace:seh:NtQueryInformationThread (0xfffffffffffffffe,12,0x1a3fe2c,4,(nil))
654.684:005c:006c:trace:seh:NtQueryInformationThread (0xfffffffffffffffe,12,0x142fe2c,4,(nil))
654.684:0074:00a0:trace:seh:NtQueryInformationThread (0xfffffffffffffffe,12,0x2e8fe2c,4,(nil))
654.685:003c:0050:trace:seh:NtQueryInformationThread (0xfffffffffffffffe,12,0x162fe2c,4,(nil))
654.685:0074:0084:trace:seh:dispatch_exception code=6ba flags=0 addr=000000007B01236E ip=000000007B01236E tid=0084
654.685:0074:0084:warn:seh:dispatch_exception unknown exception (code=6ba) raised
```

## Symptoms 
SteamVR does not launch on Fedora 34. See specs above. Competely out of the box fresh install.

## Reproduction
1. Install Fedora 34
2. Install Steam
3. Install SteamVR for Windows (Compatibility -> Force Steam Play (Proton))
4. Run SteamVR

**Comment by kisak-valve** [comment]
Hello @l33tllama, we're using one issue report per unofficially supported game title (in this case a utility), so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2595#issuecomment-864091142.
