### ISSUE TITLE
Logitech G29 red rotary switch does not work reliably (227300)

### ISSUE THREAD

**Issue by kallestrop** [ValveSoftware/Proton#4912]
How to reproduce:

Starting `WINEPREFIX=/home/user/.steam/steam/steamapps/compatdata/227300/pfx /home/user/.steam/steam/steamapps/common/Proton\ 6.3/dist/bin/wine64 control joy.cpl`

![logitech_g29_22-23](https://user-images.githubusercontent.com/79357601/122827918-4ca29800-d2e5-11eb-9bf5-47a7400b3bc9.png)

When turning the red rotary switch of the Logitech G29 Wheel to the left (23) or right (22), every step should be recognized. But i have to turn the switch 10 - 20 steps for triggering the switch.

This issue affected Euro Truck Simulator (227300) when running with Proton. When running in native Linux version, there is no issue with the switch.

I made also a test with evtest. The event time when switching from value 1 to value 0 (turning the switch for 1 step) is very low, (about 2 milliseconds?) maybe too low for recognizing triggering the switch.

```
user@debian:~$ evtest
No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event6:	Logitech G29 Driving Force Racing Wheel
Select the device event number [0-6]: 6
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x46d product 0xc24f version 0x111
Input device name: "Logitech G29 Driving Force Racing Wheel"
Properties:
Testing ... (interrupt to exit)
Event: time 1624307156.950783, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90016
Event: time 1624307156.950783, type 1 (EV_KEY), code 709 (BTN_TRIGGER_HAPPY6), value 1
Event: time 1624307156.950783, -------------- SYN_REPORT ------------
Event: time 1624307156.952772, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90016
Event: time 1624307156.952772, type 1 (EV_KEY), code 709 (BTN_TRIGGER_HAPPY6), value 0
Event: time 1624307159.678826, -------------- SYN_REPORT ------------
Event: time 1624307167.130949, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90016
Event: time 1624307167.130949, type 1 (EV_KEY), code 709 (BTN_TRIGGER_HAPPY6), value 1
Event: time 1624307167.130949, -------------- SYN_REPORT ------------
Event: time 1624307167.132938, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90016
Event: time 1624307167.132938, type 1 (EV_KEY), code 709 (BTN_TRIGGER_HAPPY6), value 0
Event: time 1624307174.293043, -------------- SYN_REPORT ------------
Event: time 1624307174.879066, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90017
Event: time 1624307174.879066, type 1 (EV_KEY), code 710 (BTN_TRIGGER_HAPPY7), value 1
Event: time 1624307174.879066, -------------- SYN_REPORT ------------
Event: time 1624307174.881053, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90017
Event: time 1624307174.881053, type 1 (EV_KEY), code 710 (BTN_TRIGGER_HAPPY7), value 0
Event: time 1624307174.881053, -------------- SYN_REPORT ------------
Event: time 1624307175.373081, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90017
Event: time 1624307175.373081, type 1 (EV_KEY), code 710 (BTN_TRIGGER_HAPPY7), value 1
Event: time 1624307175.373081, -------------- SYN_REPORT ------------
Event: time 1624307175.375059, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90017
Event: time 1624307175.375059, type 1 (EV_KEY), code 710 (BTN_TRIGGER_HAPPY7), value 0
```

Tested Proton versions:  5.0 / 5.13 / 6.3 / 6.3 experimental

My systems specification: https://gist.github.com/kallestrop/58ca1f73e1961232637c2a10099fb7e3

**Comment by whizse** [comment]
Just for reference. The same erratic behavior with the switch is observed in Windows if you _don't_ install the G-HUB driver from Logitech. 

When installed, it works reliably. I guess there's some sort of software de-bounce done on the driver side.

**Comment by kallestrop** [comment]
FYI:

Since Proton 7.0 the red rotary switch is working as intended in Euro Truck Simulator 2.
