### ISSUE TITLE
GTA V doesn't run or create log files on launching from an external hard drive

### ISSUE THREAD

**Issue by murkeh217** [ValveSoftware/Proton#4916]
Proton version: 6.3--4
Game title: GTA V

I'm trying to run GTA V on my Ubuntu 20.04 LTS through one of the EXT4 partition from my 1 TB external hard drive which has other NTFS partition. Game has installed fine but whenever I press play button, it shows game is starting then stops within 1-2 seconds. No logs are generated at all.

Steps I have tried:
1. Adding 777 permissions to the folder which has steam backup inside, also changed owner from root to my username. The drive stays mounted at all times automatically.
2. Completely exiting steam and launching through terminal also shows nothing of relevance in terminal.
3. Tried to execute the PlayGTAV.exe directly from terminal, it gives Rockstart Launcher not found error.

Command I use to print log file is - PROTON_LOG=1 %command% >> logerror.txt

**Comment by kisak-valve** [comment]
Hello @murtazakan, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-867851612.
