### ISSUE TITLE
Dual sense controller take a while to connect to Proton games.

### ISSUE THREAD

**Issue by blastermaster77** [ValveSoftware/Proton#4920]
#### Your system information

* Steam client version (1624329075): 
* Distribution (Manjaro KDE): 
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Dual sense controller takes a while to connect to Proton games, it works instantly with native games. I linked 2 videos comparing the connection between Dual sense and xbox one s, the xbox one s connects instantly ,  see videos.

#### Steps for reproducing this issue:

1. Pair dual sense controller
2. Launch proton game
3. It take a while to connect to game.

https://user-images.githubusercontent.com/9307070/123464180-7d6f1f80-d5ba-11eb-9ea1-815105be67f0.mov

https://user-images.githubusercontent.com/9307070/123464356-b3ac9f00-d5ba-11eb-910f-b9bda1ff0af3.mov

**Comment by kisak-valve** [comment]
Hello @blastermaster77, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report.

For reference, can you find a native linux game that works equally well with the default config and if you set the per-game Steam Play option to Steam Linux Runtime, then see if you can reproduce the controller behavior with that game? That should give us a hint if this should be looked at from Proton's side or the container environment which it is run in.

**Comment by blastermaster77** [comment]
> Hello @blastermaster77, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report.
> 
> For reference, can you find a native linux game that works equally well with the default config and if you set the per-game Steam Play option to Steam Linux Runtime, then see if you can reproduce the controller behavior with that game? That should give us a hint if this should be looked at from Proton's side or the container environment which it is run in.

Linux native

https://user-images.githubusercontent.com/9307070/123479248-a699ab00-d5ce-11eb-94c1-cb068f9f16f2.mov

Steam Linux runtime

https://user-images.githubusercontent.com/9307070/123479485-01330700-d5cf-11eb-9665-17a249410814.mov

With Proton


https://user-images.githubusercontent.com/9307070/123479656-41928500-d5cf-11eb-9617-61e8bf8fd8cb.mov

Hope this helps.

**Comment by blastermaster77** [comment]
Just to followup with Glorious version  of proton this does not happen, maybe you can look in to it, to know what did he do. https://github.com/GloriousEggroll/proton-ge-custom @kisak-valve

**Comment by Vash63** [comment]
Are you using the hid-playstation kernel module? Check if it's loaded with lsmod. I have a lot of problems with various Steam games when using it, it was added with kernel 5.12. If so, try rmmod-ing it, blacklist it and see if it still has issues with your games (see your distro's wiki for module management instructions).

**Comment by blastermaster77** [comment]
now it is working fine with the current proton., going to close it.
