### ISSUE TITLE
F1 2020 (1080110) G920 Steering Wheel Issue

### ISSUE THREAD

**Issue by deviljin112** [ValveSoftware/Proton#4922]
# Compatibility Report
- Name of the game with compatibility issues: F1 2020
- Steam AppID of the game: 1080110 

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 460
- Kernel version: 5.11.0-18-generic
- Link to full system information report as [Gist](https://gist.github.com/deviljin112/c9328c725ef298ddaa1022305046c473):
- Proton version: 6.3-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Steam Logs:  [steam-1080110.log](https://github.com/ValveSoftware/Proton/files/6719051/steam-1080110.log)

## Symptoms

When going into settings (or into a race) the brake is always at 100%, even after remapping to another pedal / button it remains at 100%. No issues with the acceleration pedal. Checked with "oversteer" - Steering wheel manager - and the brake pedal is detected and reporting correct values. When remapping the pedal again it says "Z-" and when using the clutch it says "X-", but when I remap to a gas pedal it just shows the usual acceleration pedal icon (with either of the 3 mapped to brake it still shows 100% and is non-functioning). I tried USB2 and USB3 and also had no issues with this wheel on Windows 10 (recently made a move to Ubuntu).

## Reproduction

- Plug in G920 Steering Wheel
- Boot F1 2020
- Go to settings
- Edit steering
- Press brake and nothing happens (at the bottom display)
- Going into a race also fully applies brake

Edit: According to ProtonDB it does appear that G920 works for some people although those reports are months old, could the recent game update cause this problem?

**Comment by kisak-valve** [comment]
Hello @deviljin112, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4047#issuecomment-868866041.
