### ISSUE TITLE
Source SDK Base 2006 - Crashing when creating server in any multiplayer mod (215)

### ISSUE THREAD

**Issue by fennka** [ValveSoftware/Proton#493]
![proton source 2006 error](https://user-images.githubusercontent.com/40859028/44616393-831ae880-a857-11e8-83d7-86fe3b90dd36.png)

**Comment by kisak-valve** [comment]
Hello @Cerega1827, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/297#issuecomment-415998823.
