### ISSUE TITLE
Can you please stop overwriting old Proton versions? 6.3-3 broke Killing Floor 2

### ISSUE THREAD

**Issue by Shotweb** [ValveSoftware/Proton#4933]
Is it really necessary to remove old versions when a new one is released? I have been playing Killing Floor with Proton 6.0 till 6.3-2, but now it doesn't work with 6.3-3. Why can't I just stay on a working version, and play my game instead of having to spend time troubleshooting again?

# Compatibility Report
- Name of the game with compatibility issues: Killing Floor 2
- Steam AppID of the game: 232090

## System Information
- GPU: RX 480
- Driver/LLVM version: 18.3
- Kernel version: 5.10
- Proton version: 6.3

## Symptoms 
[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Checking for updates...

[Core] INFO: Getting authentication token...

[cli] INFO: Launching Finch...

Proton: Upgrading prefix from 6.3-2 to 6.3-3 (/home/langley/.wine/)

Proton: Removing ShellExecute DDE registry entries.

Traceback (most recent call last):
  File "/home/shotweb/.steam/steam/steamapps/common/Proton 6.3/proton", line 1031, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")

  File "/home/shotweb/.steam/steam/steamapps/common/Proton 6.3/proton", line 860, in init_session
    g_compatdata.setup_prefix()

  File "/home/shotweb/.steam/steam/steamapps/common/Proton 6.3/proton", line 483, in setup_prefix

    steamdir = os.environ["STEAM_COMPAT_CLIENT_INSTALL_PATH"]

  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None

KeyError: 'STEAM_COMPAT_CLIENT_INSTALL_PATH'

**Comment by kisak-valve** [comment]
Hello @Shotweb, `Proton: Upgrading prefix from 6.3-2 to 6.3-3 (/home/langley/.wine/)` pointing to `~/.wine` and `KeyError: 'STEAM_COMPAT_CLIENT_INSTALL_PATH'` is abnormal, hinting that you're not running Proton from Steam, and that is unsupported. The second detail sounds related to the discussion on #4833.

**Comment by Shotweb** [comment]
Yes, I'm running the EGS version through the Heroic launcher, and I understand if you're not helping with that. I just wanted to request/rant that old Proton versions are not removed when a new version is released.

**Comment by kisak-valve** [comment]
The root of your issue is with the environment that Heroic Games Launcher sets up around Proton when run in this unsupported configuration. That should be evaluated on their side.

Looking around a bit, there already is an issue report regarding older patch versions of Proton at #3954.

Closing as unsupported for the first part, and a duplicate for the second part.
