### ISSUE TITLE
Devil May Cry 5 

### ISSUE THREAD

**Issue by xcom169** [ValveSoftware/Proton#4938]
[system.txt](https://github.com/ValveSoftware/Proton/files/6758008/system.txt)
[steam-601150.log](https://github.com/ValveSoftware/Proton/files/6757993/steam-601150.log)
# Compatibility Report
- Name of the game with compatibility issues: Devil May Cry 5 
- Steam AppID of the game: 601150/

## System Information
- GPU: AMD Vega56
- Driver/LLVM version:  Mesa 21
- Kernel version: 5.12
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 6.3-5

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 

The game is totally borked - not starting up - with current Proton. 
Only older 5.10 Proton version works.

## Reproduction

Just start up the game with Proton 6.x

**Comment by kisak-valve** [comment]
Hello @xcom169, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2386#issuecomment-873401999.
