### ISSUE TITLE
Prey (2017) (appid 480490) - green screen during cut-scene "black-outs" 

### ISSUE THREAD

**Issue by thomasfsteeples** [ValveSoftware/Proton#4939]
# Compatibility Report
- Name of the game with compatibility issues: Prey (2017)
- Steam AppID of the game:  480490

## System Information
- GPU: Radeon RX 6900 XT
- Driver/LLVM version:  4.6 (Compatibility Profile) Mesa 21.1.3
- Kernel version: 5.12.14-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/thomasfsteeples/c8f4dedb47db9b3dd1a59cb540c6a337
- Proton version: Experimental (have also tried numbered versions, but same result)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Log File

[steam-480490.log](https://github.com/ValveSoftware/Proton/files/6758487/steam-480490.log)

## Symptoms 

Recently downloaded Prey but am experiencing this really annoying visual bug where in cut-scenes where the screen "blacks out", I instead get a screen with green lines. The HUD is preserved, and when the screen actually renders something non-trivial, it's fine.

As an example, I've attached two images from the intro - when Alex has their eyes closed, I get the green screen, but when they go to turn off their alarm clock, rendering kicks in.

![Screenshot from 2021-07-03 13-59-35](https://user-images.githubusercontent.com/32720359/124356262-f864b580-dc0c-11eb-8925-94a7d74acc44.png)
![Screenshot from 2021-07-03 13-59-46](https://user-images.githubusercontent.com/32720359/124356263-f8fd4c00-dc0c-11eb-84f4-b0b306260d08.png)

It's not an absolute deal-breaker, but it's definitely breaking immersion. Has anyone else come up against this problem before? Does anyone have any tips for troubleshooting this? I'm experiencing it both on X and Wayland. Any help would be greatly appreciated.

**Comment by kisak-valve** [comment]
Hello @thomasfsteeples, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/251#issuecomment-873410725.

**Comment by thomasfsteeples** [comment]
Cheers!
