### ISSUE TITLE
build_proton.sh cannot find winegcc

### ISSUE THREAD

**Issue by GregSutcliffe** [ValveSoftware/Proton#494]
I think I have the build environment correctly set up - DXVK builds, then Wine kicks off, gets most of the way through, and then fails missing winegcc:
```
make[1]: Entering directory `/opt/proton/build/wine.win32/server'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/opt/proton/build/wine.win32/server'
/opt/proton/wine/tools/install-sh -m 644  server/wineserver.de.UTF-8.man /opt/proton/build/tools.win32/share/man/de.UTF-8/man1/wineserver.1
/opt/proton/wine/tools/install-sh -m 644  server/wineserver.fr.UTF-8.man /opt/proton/build/tools.win32/share/man/fr.UTF-8/man1/wineserver.1
/opt/proton/wine/tools/install-sh -m 644  server/wineserver.man /opt/proton/build/tools.win32/share/man/man1/wineserver.1
STRIPPROG="strip" /opt/proton/wine/tools/install-sh  server/wineserver-installed /opt/proton/build/tools.win32/bin/wineserver
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_GB:en",
	LC_ALL = (unset),
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Winemaker 0.8.4
Copyright 2000-2004 François Gouget <fgouget@codeweavers.com> for CodeWeavers
Copyright 2004 Dimitrie O. Paun
Copyright 2009-2012 André Hentschel
Scanning the source directories...
Generating project files...
  .
winegcc -c -O2 -g  -I/opt/proton/build/tools.win64/include/ -I/opt/proton/build/tools.win64/include/wine/ -I/opt/proton/build/tools.win64/include/wine/windows/ -I. -DSTEAM_API_EXPORTS  -o steamclient_main.o steamclient_main.c
make: winegcc: Command not found
winegcc -c -O2 -g  -I/opt/proton/build/tools.win64/include/ -I/opt/proton/build/tools.win64/include/wine/ -I/opt/proton/build/tools.win64/include/wine/windows/ -I. -DSTEAM_API_EXPORTS  -o steamclient_wrappers.o steamclient_wrappers.c
make: winegcc: Command not found
make: *** [steamclient_main.o] Error 127
make: *** Waiting for unfinished jobs....
make: *** [steamclient_wrappers.o] Error 127
```
winegcc is definitely present in the host enviroment:
```
root@proton:/opt/proton# winegcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Do I need to make it available to the chroots as well?

**Comment by c0r73x** [comment]
Humm it's odd, because I built it without even having wine (winegcc) on my machine. Could it be that it tries to use wine if it's installed but fails?

**Comment by GregSutcliffe** [comment]
Sadly that made no difference, I'm still getting command not found. Can you share your setup notes for your build host?

**Comment by thronezilla** [comment]
I'm having the same issue. It should be using `winegcc` from `build/tools.win(32|64)/bin` and you can see the PATH being updated to include those binaries here: https://github.com/ValveSoftware/Proton/blob/proton_3.7/build_proton.sh#L334

Though I've noticed that for me, `PATH` is getting clobbered within the chroot environment
```
$ PATH="/usr/bin" schroot --chroot steamrt_scout_beta_i386 env | grep PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/
```

I've not yet had much time to dig in further - let me know if you find anything!

**Comment by GregSutcliffe** [comment]
@thronezilla good spot! I can confirm the same behaviour with $PATH, it's easy to reproduce with `schroot --chroot steamrt_scout_beta_amd64 -- env`

What I can't figure out is how to stop it... I've tried:
* ~/.bashrc (both host and chroot)
* /etc/profile and /etc/profile.d
* /etc/environment
* /etc/login.defs

I even resorted to using `strace` on `schroot` to try and see how it was being overridden... no luck yet!

**Comment by rafaziz** [comment]
I'm getting the same error, have you found any solution to this?
