### ISSUE TITLE
Quake Champions (appid 611500)

### ISSUE THREAD

**Issue by mefff** [ValveSoftware/Proton#4941]
# Compatibility Report
- Name of the game with compatibility issues: Quake Champions
- Steam AppID of the game: 611500

## System Information
- GPU: GTX 1050 ti
- Driver/LLVM version: 465.31
- Kernel version: 5.12.12-xanmod1-1
- System info: [gist](https://gist.github.com/mefff/bdb276ce07bc44e8929fca70a94e10fc#file-gistfile1-txt)
- Proton version: 6.3-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
After the [latest update of Quake Champions on 1st of July](https://quake.bethesda.net/en/news/2WsLdFFKtoQRmjvrKUebWA) the game stopped working. When you open it, it closes before even show a window. They added an anticheat, so that could be the reason, but I can't say for sure.

Before that the game worked just fine.

[Proton log](https://gist.github.com/mefff/bdb276ce07bc44e8929fca70a94e10fc#file-gistfile2-txt)

## Reproduction

Just launch the game through steam.

**Comment by kisak-valve** [comment]
Hello @mefff, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/225#issuecomment-873477342.
