### ISSUE TITLE
Arcania

### ISSUE THREAD

**Issue by 4164696f73** [ValveSoftware/Proton#4942]
# Compatibility Report
- Name of the game with compatibility issues: Arcania
- Steam AppID of the game: 39690

## System Information
- GPU: Nvidia GeForce 750 Ti
- Driver/LLVM version: Nvidia 465.31
- Kernel version: 5.10.47-1 Linux LTS
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/4164696f73/6479c176600c545446cc0a6218bd5115
- Proton version: [6.3.5], [5.13.6], [5.0.10]

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Failed to obtain a log.

## Symptoms 
The game refuses to launch - infinite loading, game not opening at all.

## Reproduction
Launch the game, get a black screen.

## Additional info:
Found some information here: https://www.protondb.com/app/39690 but nothing helped. This website is quite good when it comes to user feedback on if a game works or not. Issued a refund, so I'll be unable to test anything more.

**Comment by kisak-valve** [comment]
Hello @4164696f73, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/770#issuecomment-873577376.

**Comment by 4164696f73** [comment]
Pardon. I should've searched in here before posting.
