### ISSUE TITLE
"bwrap: Failed to make / slave: Operation not permitted"

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [ValveSoftware/Proton#4943]
I don't have enough room on my ${HOME} directory for my steam library, and the only other place I have for it is a NTFS hdd that I didn't bother to reformat because I didn't have anywhere to move the other game files that were already on it. But after moving the library to ti, nothing would run. I finally managed to figure out which mount options were necessary to make files executable on the drive, but now I'm stuck with this error for every launch attempt...

**Comment by neurodiverseEsoteric** [comment]
Oh, apparently it was due to firejail, not pmount or the file permissions....

**Comment by ZLima12** [comment]
If someone figures out how to avoid this problem while still using Firejail, please say so here.

**Comment by kisak-valve** [comment]
Hello @ZLima12, https://github.com/ValveSoftware/steam-runtime/issues/372 might be worth reading.

**Comment by rusty-snake** [comment]
FYI https://github.com/netblue30/firejail/issues/4366
