### ISSUE TITLE
Witcher 3 has significant input delay

### ISSUE THREAD

**Issue by Sakura0134** [ValveSoftware/Proton#4944]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher 3
- Steam AppID of the game: 292030

## System Information
- GPU: Vega 8
- Driver/LLVM version: Mesa 21.1.3-2/llvm 12.0.0-2
- Kernel version: linux-zen 5.12.14
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Sakura0134/8f0762273fa1445911f7d1c57685b598
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Significant Input delay by 1 to 2 s

## Reproduction
Open Witcher 3(Steam Version) and play the game. You will notice input delay by 1 to 2 s

**Comment by kisak-valve** [comment]
Hello @Sakura0134, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-873519770.
