### ISSUE TITLE
Multi-Screen-issue - Changing to fullscreen lead the game change to secondary screen.

### ISSUE THREAD

**Issue by JokerGermany** [ValveSoftware/Proton#4947]
Distribution: Ubuntu Mate 20.04
effected tested Proton Versions: 6.3-5

Config:
Secondary Screen on the left side.
Secondary Screen:
1920x1080
Primary Screen:
3440x1440

When i use in the game a resolution which would fit on both screens and change from window mode to fullscreen, this happens:
![protonbug](https://user-images.githubusercontent.com/30293477/124575031-554daf00-de4b-11eb-89cd-9fd05b9b3208.png)
(The Window was on the primary screen!)

Workaround:
Having a bigger primary screen and change the resolution to something bigger than the secondary screen...
Then the fullscreen appears on the primary screen.
I am glad, that i sold my second 3440x1440 screen a couple of weeks ago...

**Comment by kisak-valve** [comment]
Hello @JokerGermany, this issue is already being tracked at #720. Since you've added some additional insight, I've transferred this issue report to https://github.com/ValveSoftware/Proton/issues/720#issuecomment-874646460.

Closing in favor of the older issue report.
