### ISSUE TITLE
Sea of Thieves (1172620)

### ISSUE THREAD

**Issue by iSaluki** [ValveSoftware/Proton#4948]
# Compatibility Report
- Name of the game with compatibility issues: Sea of Thieves
- Steam AppID of the game: 1172620

## System Information
- GPU: GTX 1060 6GB
- Driver/LLVM version: NVIDIA 460.80
- Kernel version: 5.11
- Link to full system information report as [Gist](https://gist.github.com/): This issue shouldn't require additional system information. It has been confirmed by other people on all systems on protondb.
- Proton version: 6.3-5

## I confirm:
- [ ✓] that I haven't found an existing compatibility report for this game.
- [✓ ] that I have checked whether there are updates for my system available.

Due to the nature of the issues it would be quite time consuming to get the logs needed. I definitely could do it if required, but it would likely be a few days. These issues should be reproducible.

## Symptoms 

1) Major: If a friend invites you to a game through Steam, then joining them leads to you getting stuck in a loading screen forever.

2) Mild annoyance: It takes significantly longer for the game to load in than on Windows.

3) Mild annoyance: There are occasional frame drops throughout the game, usually during intense combat or cinematics.

## Reproduction

1) To reproduce perpetual loading screen issue (requires 2 people, friends on Steam):

- Load the game up and go to the main menu (both)
- One person should create a closed crew. (Play -> Closed Crew -> Sloop)
- Crew creator should then press Shift + Tab and invite the other player to join their game
- Other player should accept the invite
- Observe how the joining player gets stuck on "Loading fresh supplies" forever.

2) To reproduce slower than Windows loading times:

- Load the game up on Windows, and join a server (Play Game -> Adventure -> Closed Crew -> Sloop -> Set Sail). Observe time it takes to load into the game.
- Load the game up on Linux and replicate the steps. Observe how the time is significantly longer.

3) To reproduce frame drops:

- Join a game (Play -> Adventure -> Closed Crew -> Sloop -> Set Sail)
- Play the game for a while, and notice how there are occasional frame drops. These don't occur on Windows. 

**Note:** If you do require any more details, anything at all, then let me know. I'll do my best to get it to you within a couple of days.

**Comment by kisak-valve** [comment]
Hello @iSaluki, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3931#issuecomment-875109767.

**Comment by iSaluki** [comment]
> Hello @iSaluki, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3931#issuecomment-875109767.

Alright, thank you!

**Comment by iSaluki** [comment]
Alright, thank you!
