### ISSUE TITLE
Deep Rock Galactic (548430)

### ISSUE THREAD

**Issue by iSaluki** [ValveSoftware/Proton#4953]
# Whitelist Request
- Name of the game to be whitelisted: Deep Rock Galactic
- Steam AppID of the game: 548430

## System Information
- GPU: GTX 1060 6GB
- Driver/LLVM version: NVIDIA 460.80
- Distro version: Ubuntu 21.04
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/iSaluki/c874cc2cc0cd9a69609f7c7d9f281a03
- Proton version: 6.3-5

## I confirm:
- [✓ ] that pressing the `Play` button in the Steam client is sufficient.
- [ ✓] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ✓] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [ ] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ✓] Although I consider the gaming experience equal to Windows there are remaining issues:

There are no issues that have any real impact on your experience, so I think that, in its current state the game is ready to be whitelisted.

The one issue that I am still experiencing is during the game loading screen. Audio stutters badly and sounds very robotic, however this resolves itself before the first interactible menu loads up. None of the actual gameplay is impacted, and this only occurs once per session for several seconds.

**Comment by kisak-valve** [comment]
Hello @iSaluki, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/284#issuecomment-875540277.
