### ISSUE TITLE
S.T.A.L.K.E.R.: Shadow of Chernobyl (4500) crashes with newer Proton versions

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#4957]
- Name of the game: S.T.A.L.K.E.R.: Shadow of Chernobyl
- Steam AppID of the game: https://steamdb.info/app/4500/

## System Information
- GPU: Radeon RX 5500 XT
- Driver/LLVM version: Mesa 21.2.0-devel (git-d677120cae) / LLVM 13 git master
- Kernel version: 5.13.0-pf2+
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfoamd
- Proton version: 6.12-GE-1 / Experimental
- Log GE: [steam-4500.log](https://github.com/ValveSoftware/Proton/files/6795927/steam-4500.log)
- Log Experimental: [steamex-4500.log](https://github.com/ValveSoftware/Proton/files/6795929/steamex-4500.log)

The game crashes on launch.

**Comment by gofman** [comment]
I have started debugging the game and could reproduce the issue with the Experimental version leading to crash on start (which I hope to fix soon). I am not completely sure if that is the same issue you are hitting though, this error from your log before the crash is suspicious:

"629.318:0100:0104:fixme:file:errno_to_status Converting errno 38 to STATUS_UNSUCCESSFUL".

The game worked for me out of the box with stable Proton 6.3-5. If it doesn't start for you this way, can you please try that with standard distribution kernel? Kernel version: 5.13.0-pf2+ suggests you have a custom built one.

**Comment by gofman** [comment]
The issue which I could reproduce with Experimental back then should be fixed in the latest Experimental update.

**Comment by shoober420** [comment]
The latest Proton Experimental as of this post and Proton-6.13-GE-1 both work now for me with Stalker SoC.

**Comment by kisak-valve** [comment]
Thanks fore retesting @shoober420, closing.
