### ISSUE TITLE
hitman 2 (863550) doesnt start

### ISSUE THREAD

**Issue by CrCrate** [ValveSoftware/Proton#4962]
upon pressing play after a few seconds it just goes back to play, no windows opens and nothing happens. PROTON_LOG is extremely unhelpful as theres pretty much nothing in it
**experimental**
`======================
Proton: 1625839307 experimental-6.3-20210709
SteamGameId: 863550
Command: ['/media/dumbass/ext/SteamLibrary/steamapps/common/HITMAN2/Launcher.exe']
Options: {'forcelgadd'}
SteamLinuxRuntime: v0.20210317.0-0-ge09b2e6
pressure-vessel: 0.20210415.0+srt1 scout 0.20210415.0
soldier: 0.20210415.0 soldier 0.20210415.0
======================`
**3.16-9**
`======================
Proton: 1554732609 proton-3.16-9
SteamGameId: 863550
Command: ['/media/dumbass/ext/SteamLibrary/steamapps/common/HITMAN2/Launcher.exe']
======================`

**Comment by kisak-valve** [comment]
Hello @CrCrate, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2121#issuecomment-878218397.
