### ISSUE TITLE
[Question] How can I install mods for a proton game with the same proton version and prefix that the game uses?

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#4963]
I want to install a mod for a proton game,the installer searches for where the game is located on the wine c: drive,the problem is that when I try to install the mod with normal wine,then it can't find the proton game,cause that is on a different prefix.

So I want to install the mod via the same proton version and prefix as the game.

**Comment by kisak-valve** [comment]
Hello @Toadfield, the feature request at https://github.com/ValveSoftware/steam-for-linux/issues/5766 covers this scenario. Closing in favor of the older issue report.
