### ISSUE TITLE
Debugging checkbox and dumpfile path

### ISSUE THREAD

**Issue by zaggynl** [ValveSoftware/Proton#4964]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
A checkbox that can be set in the Steam Proton options to enable debugging tools as mentioned here: https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/.gitlab/issue_templates/Bug%20Report%20-%20AMD%20Radeon%20Vulkan.md
This would mean adding said debugging tools to Steam, gdb, apitrace, gfxreconstruct.
A textbox to specify the path to a place on a disk with enough space, as the dumpfiles from tools such as gfxreconstruct grow rather large (tens or hundreds of GBs).

## Justification [optional] 
Most games are still played through Proton.
While I am knowledgeable in most things Linux it is a challenge to get all the debugging tools to work.
Lowering the barrier would ensure users can bring bugreports properly and quickly to the developers.

## Risks [optional]
Needs a notification that dump files can become large, add a button clear clear the dumpfile path?

## References [optional] 
N/A

**Comment by kisak-valve** [comment]
Hello @zaggynl, this is a feature request for the Steam Client, not Proton itself, and we need for https://github.com/ValveSoftware/steam-for-linux/issues/5874 to exist before requesting more fine grained enhancements.

For now, there's no point in evaluating this feature request until steam-for-linux#5874 happens. Closing in favor of the older issue report.
