### ISSUE TITLE
On Linux kernel 5.13 all Proton games stopped working

### ISSUE THREAD

**Issue by norbusan** [ValveSoftware/Proton#4968]
# Compatibility Report
- Name of the game with compatibility issues: Assassin's Creed: Odyssee, Supraland
- Steam AppID of the game: 812140 (AC:O)

## System Information
- GPU: AMD RX 5700xt
- Driver/LLVM version: Mesa 20.3.5
- Kernel version: 5.13
- Link to full system information report as [Gist](https://gist.github.com/norbusan/2e396046679d62596956dd107a6cb56a):
- Proton version: Proton experimental, stable, ...

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-812140.log.gz](https://github.com/ValveSoftware/Proton/files/6812617/steam-812140.log.gz)

## Symptoms 

Logging into Uplay works
Synchronizing games with the cloud works
After that the launch image appears for a short time, then disappears
Uplay client remains running, but game never starts

**Comment by supersteeeeeeeve** [comment]
4557.906:04d4:04d8:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

Winbind is part of the samba Package, is it installed/updated?

**Comment by norbusan** [comment]
Hi @supersteeeeeeeve 
thanks for your comment, unfortunately that didn't help either. The problem is (after installation of the required package) say 70% reproducible, sometimes it starts, but if it doesn't the processes are somehow stopped and not reacting:
```
  8970 ?        S      0:00 /bin/sh -c PROTON_LOG=1 /home/norbert/.steam/ubuntu12_32/reaper SteamLaunch AppId=812140 -- '/home/norbe
   8971 ?        S      0:00 /home/norbert/.steam/ubuntu12_32/reaper SteamLaunch AppId=812140 -- /home/norbert/.steam/steam/steamapps
   8972 ?        S      0:00 /usr/bin/bwrap --args 41 /run/pressure-vessel/pv-from-host/bin/pressure-vessel-adverb --generate-locales
   9228 ?        I      0:00 [kworker/2:0-events]
   9386 ?        Ss     0:00 /run/pressure-vessel/pv-from-host/bin/pressure-vessel-adverb --generate-locales --fd 13 --exit-with-pare
   9411 ?        Ss     0:08 /home/norbert/.steam/compatibilitytools.d/Proton-6.12-GE-1/files/bin/wineserver
   9415 ?        Ssl    0:00 C:\windows\system32\services.exe
   9419 ?        Sl     0:00 C:\windows\system32\winedevice.exe
   9427 ?        Sl     0:04 C:\windows\system32\winedevice.exe
   9442 ?        Sl     0:00 C:\windows\system32\plugplay.exe
   9458 ?        Sl     0:00 C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted
   9470 ?        Sl     0:00 C:\windows\system32\explorer.exe /desktop
   9502 ?        Sl     0:00 C:\windows\system32\rpcss.exe
   9507 pts/1    S+     0:00 tail -f steam-812140.log
   9518 ?        Ssl    0:00 steam /xp/SteamLibrary/steamapps/common/Assassins Creed Odyssey/ACOdyssey.exe -uplay_steam_mode
   9533 ?        Sl     0:13 C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\upc.exe -upc_uplay_id 5092 -uplay_steam_mode
   9618 ?        Sl     0:03 C:/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/UplayWebCore.exe --type=renderer --no-sandbox --dis
```

And during the long wait, the proton log just adds and adds lines of the form:
```
733.021:0120:0140:trace:seh:NtGetContextThread 0xfffffffe: eax=000000d5 ebx=0000000c ecx=40010006 edx=0bf7f69c esi=0000000c edi=0bf7fcb0
733.021:0120:0140:trace:seh:NtGetContextThread 0xfffffffe: ebp=0bf7fdc8 esp=0bf7fc6c eip=7bc0c86c cs=0023 ss=002b flags=00200246
733.021:0120:0140:trace:seh:NtGetContextThread 0xfffffffe: ds=002b es=002b fs=0063 gs=006b
```

I have no idea how to debug that, it seems that the program is waiting for some event, but doesn't receive it.

**Comment by SimplyCorbett** [comment]
Regular proton games run fine on kernel 5.13.2. It's hard to help you without the gist being filled out.

If you're on arch I'd consider this an arch specific issue and you would need to file a bug upstream.

**Comment by brauliobo** [comment]
I'm using 5.13.1 here without problems, on ArchLinux

**Comment by ghost** [comment]
it could be amd-gpu causing an issue ---> https://github.com/ValveSoftware/steam-runtime/issues/309#issuecomment-740989870

**Comment by norbusan** [comment]
@SimplyCorbett @brauliobo are you running amdgpu driver from the kernel, too, or some other hardware?

@ElcoinGL unfortunately, this is not a problem in my case, I have never touched the amdgpu-pro drivers, and use plain kernel included ones. Also, there are no loading errors in the proton log file, simply hanging and waiting.

**Comment by SimplyCorbett** [comment]
> 
> 
> @SimplyCorbett @brauliobo are you running amdgpu driver from the kernel, too, or some other hardware?

No I am not using amdgpu.

**Comment by norbusan** [comment]
> No I am not using amdgpu.

Thanks for letting me know.

Maybe I can come around a bisecting session on the kernel to isolate the bad behavior.

**Comment by SimplyCorbett** [comment]
> 
> 
> > No I am not using amdgpu.
> 
> Thanks for letting me know.
> 
> Maybe I can come around a bisecting session on the kernel to isolate the bad behavior.

Perhaps you can provide your specifications in the gist so we can help you better.

**Comment by norbusan** [comment]
> Perhaps you can provide your specifications in the gist so we can help you better.

Added it to the initial report, and here [Gist](https://gist.github.com/norbusan/2e396046679d62596956dd107a6cb56a)

**Comment by SimplyCorbett** [comment]
Mesa is outdated. Update to the latest 21.1.5 and see if that fixes your problem.

**Comment by norbusan** [comment]
> Mesa is outdated. Update to the latest 21.1.5 and see if that fixes your problem.

Ok, I will try this later (after work), but since it started only recently to fail, and was working with the same version of MESA before, I am doubtful. Anyway, will try.

**Comment by norbusan** [comment]
> > Mesa is outdated. Update to the latest 21.1.5 and see if that fixes your problem.
> 
> Ok, I will try this later (after work), but since it started only recently to fail, and was working with the same version of MESA before, I am doubtful. Anyway, will try.

I stand corrected. Indeed, the update of kernel required an updated of mesa. With Mesa 21.1.4 (Debian/experimental) all the games work as expected.

Thanks!
