### ISSUE TITLE
Corrupt menu text in NieR:Automata (524220)

### ISSUE THREAD

**Issue by NyaomiDEV** [ValveSoftware/Proton#4973]
# Compatibility Report
- Name of the game with compatibility issues: NieR:Automata
- Steam AppID of the game: 524220

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 21.1.4 / LLVM 12.0.0
- Kernel version: 5.12.14-artix1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/AryToNeX/077e4c637bbf67325d120321b00ec5a1
- Proton version: 6.3-5; Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. (okay I may have cheated on this one, actually there are plenty but no general one)
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Text is unreadable, all over the place: can it be a shader problem?

![image](https://user-images.githubusercontent.com/13177694/125869669-5b30d53a-fb0f-4c74-8230-369ccbdfb9c8.png)

## Reproduction
Just try to go to the settings page

**Comment by ignogueiras** [comment]
Same thing happen to me on Windows, yesterday after the new game update. I solved it by reinstalling the game.
So maybe not a Proton problem?

**Comment by NyaomiDEV** [comment]
> Same thing happen to me on Windows, yesterday after the new game update. I solved it by reinstalling the game.
> So maybe not a Proton problem?

I also reinstalled it and I think that Steam was having some problems with 'delta updating' the game, indeed. Sad that's happened though. Sorry everyone!

**Comment by Scrumplex** [comment]
For anyone that doesn't want to reinstall the whole game: These files should be the ones that are broken:
```
data
├── message_box.txt
└── ui
    ├── ui_core_de.dtt
    ├── ui_core.dtt
    ├── ui_core_es.dtt
    ├── ui_core_fr.dtt
    ├── ui_core_it.dtt
    ├── ui_core_us.dtt
    ├── ui_option_de.dtt
    ├── ui_option.dtt
    ├── ui_option_es.dtt
    ├── ui_option_fr.dtt
    ├── ui_option_it.dtt
    └── ui_option_us.dtt
```

So deleting `data/ui` and `data/message_box.txt`and then re-validating files might fix the issue

**Comment by clee3092** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/4973#issuecomment-881862828

This! It works
