### ISSUE TITLE
Witcher 3 weird lighting

### ISSUE THREAD

**Issue by ryandbair** [ValveSoftware/Proton#4974]
# Compatibility Report
- Name of the game with compatibility issues:  The Witcher 3: Wild Hunt - Game of the Year
- Steam AppID of the game: 292030

## System Information
- GPU: R9 280 X
- Driver/LLVM version: Mesa 21.1.4
- Kernel version: 5.12.15
- Link to full system information: [Gist](https://gist.github.com/ryandbair/0760f1aafb53ef53bd84cdc762bf1e8d)
- Proton version: Experimental & 6.3-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Lighting in the game is generally a bit weird. Light parts of outdoor scenes are very bright and dark parts are very dark. Caves are near total darkness. 

## Reproduction
The gamma adjust screen is a good example with Proton Experimental. The background (white) seems to be adjusted but the image in the center is almost always complete black, maybe just flickering into sight here and there. 

In game play, just look around. Maybe go into a cave for fun.

[steam-292030.log.gz](https://github.com/ValveSoftware/Proton/files/6826993/steam-292030.log.gz)

**Comment by kisak-valve** [comment]
Hello @ryandbair, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-881103994.
