### ISSUE TITLE
mafia 2 (classic) dont start 

### ISSUE THREAD

**Issue by thatdrigues** [ValveSoftware/Proton#4977]
so i  play on linux and this is happening :press the start button the game looks like is starting but then dont start and just apear the start button again

**Comment by kisak-valve** [comment]
Hello @thatdrigues, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/330#issuecomment-881942394.
