### ISSUE TITLE
Astroflux (489560)

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#4979]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 489560

## System Information
- GPU: GTX 1060 6GB
- Driver/LLVM version: Nvidia 470.42.01
- Kernel version: 5.10.49-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/coreybruce/dcd2bec911594c9212d351ac2e7a3f98
- Proton version: 6.3-5

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

[steam-489560.log](https://github.com/ValveSoftware/Proton/files/6836058/steam-489560.log)

## Symptoms 

Game will open up as a black window and will crash, Will only work if you use Proton 4.11-13 but does have some performance issues but idk if that is the game or not.

## Reproduction

Use latest proton version for game.

**Comment by kisak-valve** [comment]
Hello @coreybruce, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

From your log:
```
err:vulkan:wine_vk_instance_load_physical_devices Failed to enumerate physical devices, res=-3
err:vulkan:__wine_create_vk_instance_with_callback Failed to load physical devices, res=-3
[...]
terminate called after throwing an instance of 'dxvk::DxvkError'
```
This hints that something went wrong with initializing Vulkan for DXVK to use.

As a test, you could try if setting the game's launch options to `PROTON_USE_WINED3D=1 %command%` and see if that makes the game behave the same as Proton 4.11 with Proton 5.0 and newer.

**Comment by coreybruce** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/4979#issuecomment-882044959

Sure here you go

https://gist.github.com/coreybruce/dcd2bec911594c9212d351ac2e7a3f98

Ok so I did it with the latest proton and it does now work but there is some wierd colour issues as if it's running in a lower colour mode

E.g

Proton 4.11
![Screenshot_2021-07-18_23-23-35](https://user-images.githubusercontent.com/8393780/126068741-802f2c0f-73e2-43f5-899c-6d7ca1e1f98f.png)

Proton 6.3 with launch command
![Screenshot_2021-07-18_23-22-31](https://user-images.githubusercontent.com/8393780/126068766-6d00804a-65cd-4974-872e-c347eacd9a83.png)

Is there anything that can be done stop improve the performance and remove stuttering? I mean it's a 2D came on high end hardware and idk why it's running at 30fps and stutters a little lol

**Comment by coreybruce** [comment]
Issue was on my end and has been fixed fixing the issue. Sorry about that.

**Comment by damnkrat** [comment]
> Issue was on my end and has been fixed fixing the issue. Sorry about that.

What was the problem, and how did you fix it?
