### ISSUE TITLE
savegames get deleted when game is uninstalled

### ISSUE THREAD

**Issue by christianrauch** [ValveSoftware/Proton#4981]
I used proton 6.3 via Steam and uninstalled a game. I noticed that the corresponding folder with the game's AppID in `$HOME/.steam/steamapps/compatdata/<AppID>` gets fully removed. This usually includes all user preferences and savegames. In contrary to cloud-synced savegames and native Linux games, this means that a user cannot continue from where he/she left off when re-installing the game.

Please provide a way to have persistent settings and especially savegames for proton games.

**Comment by kisak-valve** [comment]
Hello @christianrauch, this issue is already being tracked at #428. Closing as a duplicate.
