### ISSUE TITLE
Post-processing injectors (ReShade, GShade, enbseries, etc) not responding to UI hotkeys in Skyrim Special Edition

### ISSUE THREAD

**Issue by mmatis** [ValveSoftware/Proton#4984]
I know this is really niche, but I wanted to at least document it somewhere other than random Reddit posts. I've been trying to get post-processing injectors working in SkyrimSE and I've found an issue that affects every one I've tried, including reshade, gshade, and enbseries. Basically, none of them respond to their hotkeys to bring up their respective GUIs after the main Skyrim menu appears. However the hotkeys DO work during the few seconds the Bethesda logo is on the screen. As far as I can tell, the actual injection of effects is working-- it's just the settings interface that won't come up. All three injectors exhibit the exact same behavior. All you have to do to reproduce is install SkyrimSE, install Reshade, and start the game. You should see the banner along the top indicating ReShade loaded, but pressing the Home key will not bring up its UI after the main menu appears.

I've tested using the following Proton versions with SSE on clean prefixes with no mods/SKSE installed. Just Reshade. All exhibited the same behavior:

- Proton Experimental  
- 6.12-GE-1
- 5.13-6
- 5.9-GE-8-ST
- 5.21-GE-14.11-13

I went all the way back to 3.16-9 as well, but SSE wouldn't even load. I also tested in a more stripped down desktop environment (openbox) and that didn't change anything. 

The first of the two logs attached below is from trying to trigger the Reshade UI (unsuccessfully) from the Skyrim SE menu screen. The second is from (successfully) triggering it during the Bethesda logo. That second run produced a weird effect as I was fiddling with settings where I couldn't get back out of the ReShade UI. After spamming the Home key several times, all input locked up and I had to Alt-Tab back to my desktop and kill SSE. 

Scattered forum/reddit posts describe similar issues and Eorn over at the GShade project was able to reproduce it as well. Though I couldn't find any existing WINE or Proton bugs that might be relevant. Please let me know anything else I can provide to anyone willing to tackle this admittedly niche issue!

Specs:OS: Linuxmint 20.2 uma
Kernel: x86_64 Linux 5.11.0-22-generic
DE: Cinnamon 5.0.5
CPU: AMD Ryzen 7 3700X 8-Core @ 16x 3.6GHz
GPU: NVIDIA GeForce RTX 2060 (Driver vers. 465.31)
RAM: 32034MiB

Full spec dump from Steam attached.

[sse-reshade-no-ui.log](https://github.com/ValveSoftware/Proton/files/6843358/sse-reshade-no-ui.log)
[sse-reshade-ui-responds.log](https://github.com/ValveSoftware/Proton/files/6843361/sse-reshade-ui-responds.log)
[fullspecs.txt](https://github.com/ValveSoftware/Proton/files/6843363/fullspecs.txt)

**Comment by kisak-valve** [comment]
Hello @mmatis, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4#issuecomment-882805743.
