### ISSUE TITLE
Cyberpunk 2077 Chinese Simpiled REDprelauncher garbled

### ISSUE THREAD

**Issue by zhairuiyao15** [ValveSoftware/Proton#4985]
Hi,

Proton Experimental:

```
[zhairuiyao@localhost Proton - Experimental]$ ./files/bin/wine64 --version
wine-6.3
```

Cyberpunk 2077 V1.23

![Screenshot_20210719_205541](https://user-images.githubusercontent.com/68763952/126250321-ab2e0cd9-a936-4463-bdcf-ad53e9de4588.png)

Workaround:

![Screenshot_20210720_094703](https://user-images.githubusercontent.com/68763952/126250320-c1a05ff2-d427-4751-80d4-d5489bfa7902.png)

Thanks,
Ray Zhai

**Comment by kisak-valve** [comment]
Hello @zhairuiyao15, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-882996582.
