### ISSUE TITLE
The Elder Scrolls IV: Oblivion [22330]: Music skipping Proton 6.3-5

### ISSUE THREAD

**Issue by katawful** [ValveSoftware/Proton#4989]
# Problem:
On Proton version 6.3-5, the music to this game skips every 5-10 seconds to the next track in the music queue

# Steps to reproduce:
Install Oblivion from Steam normally, making sure that Proton 6.3-5 is the Proton version use. Set up graphics setting as you like and then play the game. Music will skip repeatedly when in-game. Proton 5.13-6 does not have this problem

**Comment by kisak-valve** [comment]
Hello @katawful, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/718#issuecomment-884554766.
