### ISSUE TITLE
Cyberpunk 2077 break in loading screen

### ISSUE THREAD

**Issue by shonidan** [ValveSoftware/Proton#4992]
# Compatibility Report
- Name of the game with compatibility issues: Cyberpunk 2077
- Steam AppID of the game: 1091500

## System Information
- GPU: GTX 1070
- Driver/LLVM version: nvidia 470.57.02
- Kernel version: 5.13.4-arch1-1
- Proton version: 6.3-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
My archlinux had a nvidia update in driver, then the game broke in loading screen.

## Reproduction
1. Launch game with proton 6.3-5 and this parameter [PROTON_LOG=1 PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 %command% --launcher-skip]
2. Select "Continue game"

Result: Game broke in loading screen.

**Comment by kisak-valve** [comment]
Hello @C0MODIN, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-884999508.

**Comment by shonidan** [comment]
> Hello @C0MODIN, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#4450 (comment)](https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-884999508).

Thanks kisak-valve :)
