### ISSUE TITLE
wine_vk_init Failed to load Wine graphics driver supporting Vulkan

### ISSUE THREAD

**Issue by cn293** [ValveSoftware/Proton#4993]
Attempting to run The Elder Scrolls V: Skyrim via Proton 6.3. Steam loads without problems. When pressing the Play button Steam displays a Stop button for a while then appears to time out with the Play button displayed again. The game does not start or load. 

The problem appears to be within Proton specifically relating to a failure in the loading of the Wine graphics driver. Error messages are issued for libopenvr_api.so which is not in the Proton libraries and for which I cannot find a native Mint or Ubuntu package that contains the wrapper. Note that the game is not a VR game. Also don't see this as a compatibility issue.

There are also errors raised for gameoverlayrenderer.so.

**HARDWARE:**
Lenovo P52s
Intel Core i7-8550U
Nvidia Quadro P500

**OS:**
Linux Mint 19.1 Cinnamon version 4.0.10
Kernel 4.15.0-51

**STEAM/PROTON**
Steam package version 1626824053
Steam API: v020
Built Jul 20 2021, at 22:25:57
Proton 6.3-5
Build ID: 6933694

**ATTACHMENTS**
![Screenshot from 2021-07-22 10-47-01](https://user-images.githubusercontent.com/87828880/126692251-2781d061-8ced-4b5e-baf4-231123d7d3b3.png)
![Screenshot from 2021-07-22 10-48-50](https://user-images.githubusercontent.com/87828880/126692261-9daa8a78-b50a-46d1-a68b-d0f91488631e.png)
![Screenshot from 2021-07-22 10-58-01](https://user-images.githubusercontent.com/87828880/126692262-b280fcf0-4cdc-402e-9d45-2fe1d6909cda.png)
[steam-72850.tar.gz](https://github.com/ValveSoftware/Proton/files/6864573/steam-72850.tar.gz)
[vulkaninfo.txt](https://github.com/ValveSoftware/Proton/files/6864575/vulkaninfo.txt)

**cat steam-72850.log | grep :err**
4052.982:00b8:00bc:err:seh:dispatch_exception Fatal EXCEPTION_WINE_ASSERTION exception (code=80000101) raised
4052.998:00b8:00c0:err:rpc:rpcrt4_protseq_np_wait_for_new_connection wait failed with error 998
4053.000:00b8:00bc:err:ole:start_rpcss Failed to open service manager
4053.002:0020:00c8:err:steam:initialize_vr_data Could not load libopenvr_api.so.
4053.002:0020:00b4:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
4053.002:0020:00b4:err:winediag:nodrv_CreateWindow Unknown error (317).
4053.140:00cc:00d0:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
4053.140:00cc:00d0:err:winediag:nodrv_CreateWindow Unknown error (317).
4053.150:00cc:00d0:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
4054.153:00b8:00bc:err:ole:start_rpcss Failed to open service manager

**cat steam-72850.log | grep ERROR:**
ERROR: ld.so: object '/home/<username>/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/<username>/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/<username>/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/<username>/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/<username>/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/<username>/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/<username>/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/<username>/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/<username>/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/<username>/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/<username>/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

**Comment by kisak-valve** [comment]
Hello @cn293, `apiVersion     = 0x400041  (1.0.65)` in vulkaninfo tells us that you're using the nVidia 390.xx series proprietary driver.

This is older than the support cutoff for Proton and is known to cause problems. Please update your video driver.

**Comment by cn293** [comment]
Thanks for the quick reply. Yes you are quite right. I apologise for not checking that. The minimum Nvidia graphics driver requirement is 418.49.04 as stated on Steam. I had 390.144 installed. Upgraded to 460.91.03.

The problem is now resolved. Thanks again!
