### ISSUE TITLE
[Whitelist] Bullet Candy (6600)

### ISSUE THREAD

**Issue by pprotonrep** [ValveSoftware/Proton#50]
I tested [Bullet Candy](https://store.steampowered.com/app/6600/) and it worked perfectly fine for me, including sounds and controller input (after some tweaking in the game's settings).

- Ubuntu 18.04.1 LTS (64 bit 4.15.0-32-generic)
- GeForce GTX 1070/PCIe/SSE2 (396.51)
- Proton 3.7 (default configuration)

[System information from steam](https://gist.github.com/pprotonrep/43f7265a7457b17ceb5b848e89c26147)

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.
