### ISSUE TITLE
Sonic CD Does not run

### ISSUE THREAD

**Issue by Houtworm** [ValveSoftware/Proton#500]
Game does not run, Crashes immediately in Steam Runtime
Arch Linux 
GNOME 3.28.2
Nvidia 396.54

**Comment by Houtworm** [comment]
This is a duplicate, Closing it myself.

**Comment by bruno-fs** [comment]
just to help anyone jumping directly here from google:

duplicate of #455

**Comment by Merkosas** [comment]
https://github.com/ValveSoftware/Proton/issues/455
