### ISSUE TITLE
A Tale of Paper Demo (1657400)

### ISSUE THREAD

**Issue by RiantAnda** [ValveSoftware/Proton#5006]
# Compatibility Report
- Name of the game with compatibility issues: A Tale of Paper Demo
- Steam AppID of the game: 1657400

## System Information
- GPU: RTX 2060 S
- Driver/LLVM version: NVIDIA 470.57.02
- Kernel version: 5.13.4-zen2-1-zen
- Link to full system information report as [Gist](https://gist.github.com/RiantAnda/15857507e25f351966ad282d5ff5d0c8)
- Proton version: 6.3-5

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-1657400.log](https://github.com/ValveSoftware/Proton/files/6872908/steam-1657400.log)

## Symptoms 
There is an error message upon launch that tells me that "Microsoft Visual C++ Runtime" is required and if I want to install it. After "Yes" is selected, a "UE4 Prerequisites (x64)" window opens. When selecting "Install", the install fails with "0x80070538 - Invalid ACL". Now the game terminates.
I have tried to install vcrun via winetricks, but no version (2003-2019) seems to satisfy the requirements.

There is a log created when the UE4 Prerequisites installer fails: 
[UE4_log.txt](https://github.com/ValveSoftware/Proton/files/6872924/UE4_log.txt)

## Reproduction
Click PLAY in Steam to launch game

**Comment by gofman** [comment]
This looks like a known issue which should be fixed in Proton Experimental. Can you try that with Experimental?

**Comment by RiantAnda** [comment]
@gofman Thanks, the demo is working with Proton Experimental!

**Comment by RiantAnda** [comment]
Works perfectly with Proton 6.3-6, closing issue.
