### ISSUE TITLE
Sonic Mania fails to work unless you use Proton 3.16

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#5011]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 584400

## System Information
https://gist.github.com/coreybruce/dcd2bec911594c9212d351ac2e7a3f98

- Proton version: 6.3-5

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

Log:
https://gist.github.com/coreybruce/6373473b1bc8bc076e2b7130b6ec0ae4

## Symptoms 
If you use any version newer than proton 3.16 the game will fail to launch

## Reproduction
Launch game with latest version of proton, than switch back to proton 3.16 and you will see the game will only work on that version.

**Comment by kisak-valve** [comment]
Hello @coreybruce, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/105#issuecomment-886658413.
