### ISSUE TITLE
No Man's Sky Steam: Intel iGPU

### ISSUE THREAD

**Issue by theno2soco** [ValveSoftware/Proton#5013]
# Compatibility Report
- Name of the game with compatibility issues: No Man's Sky
- Steam AppID of the game: 275850

## System Information
- GPU: Intel® UHD Graphics 750
- Driver/LLVM version: 3.1 Mesa 21.0.3 - kisak-mesa PPA
- Kernel Version:  5.11.0-051100-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/theno2soco/261049db03d575b5aab2a21fa37360f0
- Proton version: 6.3-5

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @theno2soco, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-886694210.
