### ISSUE TITLE
Non-steam games

### ISSUE THREAD

**Issue by TenDoumi** [ValveSoftware/Proton#5014]
I would like to ask if run only games that I have purchased on Steam or games purchased outside of Steam, such as Rockstar Games Launcher, Epic Games, Uplay, etc., can be launched on ProtonDB.

**Comment by kisak-valve** [comment]
Hello @TenDoumi, Proton is intended to be run from Steam with Steam games. That said, it's an open source compatibility layer and you can figure out how to use it in ways that were not strictly intended. Supporting other store fronts is not a primary objective of Proton.

As a side note, ProtonDB is a collection of community reports on how various games are running with Proton. That site is not affiliated with Valve.
