### ISSUE TITLE
ARK Survival Evolved

### ISSUE THREAD

**Issue by Curve** [ValveSoftware/Proton#5017]
# Compatibility Report
- Name of the game with compatibility issues: ARK Survival Evolved
- Steam AppID of the game: 346110
 
## System Information
- GPU: RTX 2060
- Driver/LLVM version: Nvidia 470.57.02
- Kernel version: 5.13.4
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Curve/29e780e6f6fa5fff5b33e955fa03456e
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game (that report the same error, there is one with a different issue #3218).
- [x] that I have checked whether there are updates for my system available.

[steam-346110.log](https://github.com/ValveSoftware/Proton/files/6885206/steam-346110.log)

## Symptoms 
The game crashes with the following message:
```
Fatal error!



VERSION: 0.0 
UnknownModule!EntryPoint() (0x000000007b01236e) + 0 bytes [UnknownFile:0]
UnknownModule!__delayLoadHelper2() (0x000000014385bcb5) + 0 bytes [UnknownFile:0]
UnknownModule!__tailMerge_ApexFramework_x64_dll() (0x00000001437778d6) + 0 bytes [UnknownFile:0]
UnknownModule!InitGamePhys() (0x0000000142cd9fbe) + 0 bytes [UnknownFile:0]
UnknownModule!FEngineLoop::PreInit() (0x0000000140111311) + 0 bytes [UnknownFile:0]
UnknownModule!GuardedMain() (0x000000014010e3c0) + 0 bytes [UnknownFile:0]
```

The issue seems to only occur since the latest ARK-Update from the 24th, before it ran fine

## Reproduction
Start the Game, the issue occurs before any menus / windows are visible.

**Comment by kisak-valve** [comment]
Hello @Curve, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3218#issuecomment-887463031.

**Comment by schrummy14** [comment]
Experiencing issues with starting ark.

# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: AMD Radeon RX 7900 XT (gfx1100, LLVM 15.0.7, DRM 3.51, 5.15.0-91-generic)
- Video driver version: Mesa 23.1.0-devel
- Kernel version: 5.15.0-91-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 8.0 and experimental


Adding `PROTON_LOG=1 %command%` does not generate a log file.

## Symptoms
States that ark is "Launching" or "Running" but nothing is shown. Sometimes audio starts.

https://gist.github.com/schrummy14/17cbafcedbcba9e8feebbfccbd7d4dd0
