### ISSUE TITLE
Sonic Generations "Game files either missing or corrupt please reinstall"

### ISSUE THREAD

**Issue by dhalucario** [ValveSoftware/Proton#5021]
# Compatibility Report
- Name of the game with compatibility issues: Sonic Generations
- Steam AppID of the game: 71340

## System Information
- GPU: Nvidia GTX 1050 Ti (a friend tried with AMD Radeon RX 570)
- Driver/LLVM version: OpenGL version string: 4.6.0 NVIDIA 470.57.02 (my friends: OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.1.5)
- Kernel version: 5.13.4-200.fc34.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/dhalucario/b809e5c2e8265e2feb48cbbba5735362
- Proton version: 1627075293 experimental-6.3-20210723b

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-71340.log.gz](https://github.com/ValveSoftware/Proton/files/6888262/steam-71340.log.gz)

## Symptoms
The game seems to launch but gets stuck at "Game files either missing or corrupt please reinstall"
![grafik](https://user-images.githubusercontent.com/10533763/127217443-8418384f-0a70-4ffd-9440-b5a7287cf206.png)

The issue persists even after verifying the game files and running the ConfigurationTool.exe in the games folder.
We tried deleting the config files too.

## Reproduction
Run the latest [Fedora 34]( https://download.fedoraproject.org/pub/fedora/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-34-1.2.iso)
Install steam from [RPMFusion](https://rpmfusion.org/)
```
sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf update --refresh --best --allowerasing
sudo dnf install steam
```
Install the game on steam: https://store.steampowered.com/app/71340/Sonic_Generations_Collection/
Run it from steam

**Comment by kisak-valve** [comment]
Hello @dhalucario, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/380#issuecomment-887790458.

**Comment by dhalucario** [comment]
Thank you, I wasn't sure if a new issue was appropriate since its a different issue than listed.
