### ISSUE TITLE
Directx 12, Random Crashing, working on DX12? - EA SPORTS™ FIFA 21 (1313860)

### ISSUE THREAD

**Issue by ElChaska** [ValveSoftware/Proton#5026]
# Compatibility Report
- Name of the game with compatibility issues:  EA SPORTS™ FIFA 21
- Steam AppID of the game: 1313860

## System Information
- GPU: ASUS STRIX GTX 1080
- Driver/LLVM version: Nnvidia 470.57
- Kernel version: 5.12.0-19.3-liquorix-amd64
- Proton version: Proton Experimental / Proton 6.3-5
## Symptoms 
Random Crash, in random moment DX12.

## Reproduction
Open the game, maybe enter the game and maybe at some random moment, it crashes throwing a problem with DX12.

## Question
Is possible working on DX12? or only DX11?

**Comment by kisak-valve** [comment]
Hello @ElChaska, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4234#issuecomment-888709730.
