### ISSUE TITLE
Processur usage stays high after closing game ran with proton

### ISSUE THREAD

**Issue by Wallby** [ValveSoftware/Proton#5035]
After having run a game with proton (i.e. omno in this case).. processor usage stays high (over 60% for some cores) and e.g. the start menu becomes slow (i.e. a noticible delay of about half a second before the menu opens/closes after mouseclick).

For me.. what I did was..
.. start the game by pressing play in the steam GUI
.. stand still for a while in the game until "all is loaded" (it looks like UE4 streams higher LODs for assets in over time, so I wait for that to be done)
.. exit the game using the in game gui
NOTE: now already the processor usage will stay high for me
.. close steam
.. processor usage will still stay high for a while for me now, but after waiting (less than a minute) the processor usage will drop back to normal

Info..
proton 6.3-5
linux mint 20.1 (cinnamon 4.8.6, "linux 5.4.0-74-generic")

NOTE: steam ran with..
```
#! /bin/sh

cd "${0%/*}"

__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia "$@"
```

**Comment by kisak-valve** [comment]
Hello @Wallby, you've described part of the behavior of Steam's shader pre-cache instead of Proton itself.

This issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/6811. Closing as a duplicate.
