### ISSUE TITLE
Red Faction: Armageddon freeze when "repairing"

### ISSUE THREAD

**Issue by christianrauch** [ValveSoftware/Proton#5036]
# Compatibility Report
- Name of the game with compatibility issues: Red Faction: Armageddon
- Steam AppID of the game: 55110

## System Information
- GPU: Intel HD Graphics 5500
- Driver/LLVM version: Mesa 21.0.3
- Kernel version: 5.8.0-64-generic
- Link to full system information report: https://gist.github.com/christianrauch/18936ea9123a6e112f1274f5ca702c62
- Proton version: 6.3-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

The game allows to destroy and repair objects in the environment. Very frequently (almost always) when something in the environment is repaired (via the middle mouse button) the game freezes to halt, while the background music is still playing in the background.

The proton log [steam-55110.log](https://github.com/ValveSoftware/Proton/files/6911408/steam-55110.log) mentions:
```
MESA-INTEL: error: ../src/intel/vulkan/anv_device.c:3316: GPU hung on one of our command buffers (VK_ERROR_DEVICE_LOST)
err:   DxvkSubmissionQueue: Command submission failed: VK_ERROR_DEVICE_LOST
info:  Restoring display mode: 1366x768@60
info:  Setting display mode: 1366x768@60
warn:  DXGI: MakeWindowAssociation: Ignoring flags
```
which seems to be relevant to this problem.

## Reproduction

1. start the game
2. select something in the environment that is destructible, e.g. buildings, and damage it
3. try to repair the destroyed object using the middle mouse button

**Comment by kisak-valve** [comment]
Hello @christianrauch, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/848#issuecomment-890371528.
