### ISSUE TITLE
Project Cars 2, Steam says running but game does not launch.

### ISSUE THREAD

**Issue by azsxwazsx** [ValveSoftware/Proton#5038]
# Compatibility Report
- Name of the game with compatibility issues: Project Cars 2
- Steam AppID of the game: 378860

## System Information
- GPU: AMD RX 580
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 21.1.5, amdgpu
- Kernel version: 5.10.53-1
- Link to full system information report: 
      https://gist.github.com/azsxwazsx/43c2d12de121c14a4e58dc151994727c
- Proton version: proton 6.3-5, proton 5.13-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
After pressing the start/launch, steam shows the game launched and running, but actually the game did not launch at all.
No crash, no error,no window, no nothing. Only steam says the game is running.
Here is the log:
[steam-378860.log](https://github.com/ValveSoftware/Proton/files/6912411/steam-378860.log)

## Reproduction
Install the game and launch.

Everyone says the game works out of the box and I cannot find related discussion my problem.

**Comment by kisak-valve** [comment]
Hello @azsxwazsx, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/908#issuecomment-890513576.
