### ISSUE TITLE
Totally Accurate Battlegrounds (823130)

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/Proton#5039]
# Compatibility Report
- Name of the game with compatibility issues: Totally Accurate Battlegrounds
- Steam AppID of the game: 823130

## System Information
- GPU: GTX 970
- Driver/LLVM version: 470.57.02
- Kernel version: 5.13.5
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 6.3-5

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-823130.log](https://github.com/ValveSoftware/Proton/files/6913147/steam-823130.log)

## Symptoms 

When launching into a match, it says Anti Cheat Error and moments after, crashes. With Proton Experimental, the game crashes on launch.

## Reproduction

1. Launch the game
2. Load into a match
3. Observe that it says Anti Cheat Error and subsequently crashes.

**Comment by kisak-valve** [comment]
Hello @Newbytee, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3030#issuecomment-890573649.
