### ISSUE TITLE
BioShock 2 Remastered displays black screen during first start (409720)

### ISSUE THREAD

**Issue by pprotonrep** [ValveSoftware/Proton#504]
I could not even Alt+Tab out of it, and had to kill it changing to a terminal via `Ctrl+Alt+F Key`.

Changing the configuration file `steamapps/compatdata/409720/pfx/drive_c/users/steamuser/Application Data/BioshockHD/Bioshock2/Bioshock2SP.ini` wouldn't work at all (the settings would be reset as soon as the game starts). I had to start the game within a virtual desktop¹ and then change the settings from the game's UI. After that i experienced https://github.com/ValveSoftware/Proton/issues/482.

- Ubuntu 18.04.1 LTS (64 bit 4.15.0-33-generic)
- GeForce GTX 1070/PCIe/SSE2 (396.54)
- tested with Proton 3.7-3 and 3.7-4 Beta

[System information from steam](https://gist.github.com/pprotonrep/c67cbb6f56d9b88af24952fa45652cdf)

----
¹ via
```
WINEPREFIX=/media/pedro/SteamWin/Steam/steamapps/compatdata/409720/pfx winecfg
```
as suggested [here](https://github.com/ValveSoftware/Proton/issues/141#issuecomment-415740637).

**Comment by kisak-valve** [comment]
Hello @pprotonrep, we'll be using one issue report per unofficially supported game, so I've gone ahead and transferred this issue to https://github.com/ValveSoftware/Proton/issues/482#issuecomment-415997286.
