### ISSUE TITLE
Controller Companion (367670)

### ISSUE THREAD

**Issue by Weirdo1312** [ValveSoftware/Proton#5041]
# Compatibility Report
- Name of the game (not a game) with compatibility issues: Controller Companion
- Steam AppID of the game: 367670

## System Information
- GPU: GTX 970
- Driver/LLVM version: NVIDIA 470.57.02
- Kernel version: 5.13.7-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/barfin/502e3a1636e72dd572e2b04eb94b6394
- Proton version: experimental-6.3-20210730

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-367670.log](https://github.com/ValveSoftware/Proton/files/6924666/steam-367670.log)

## Symptoms 
It doesn't run at all

## Reproduction
1. Launch
2. Fail

**Comment by kisak-valve** [comment]
Hello @barfin, these look like some lines of interest from your log:
```
Unhandled Exception:
System.TypeLoadException: Could not load type '=OXozHKLBDzOzm7S4DJ4QnepXds=' from assembly ''.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type '=OXozHKLBDzOzm7S4DJ4QnepXds=' from assembly ''.(1)
```

**Comment by madewokherd** [comment]
This is going to need a native port to work correctly anyway. Wine/Proton can't actually send inputs to the native X11 or Wayland windowing system.

**Comment by Weirdo1312** [comment]
not necessary since steam input can do everything that this app can
