### ISSUE TITLE
The Medium

### ISSUE THREAD

**Issue by byIlsa** [ValveSoftware/Proton#5044]
# Compatibility Report
- Name of the game with compatibility issues:
- The Medium
- Steam AppID of the game:
- 1293160

## System Information
- GPU: AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.41.0, 5.13.4-1 default, LLVM 12.0.1)
- Driver/LLVM version: Mesa 21.1.5
- Kernel version: 5.13.4-1 default
- Link to full system information report as [Gist](https://gist.github.com/):
- https://gist.github.com/byIlsa/be55520e91bf2fb5b8573e14eaae9b38
- Proton version:
- Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
[steam-1293160.zip](https://github.com/ValveSoftware/Proton/files/6926399/steam-1293160.zip)

## Symptoms 

Game crashes on random moments. First the screen freezes and the sound is gone. Then the sound comes back for a second or two and then the game crashes and I'm returned to the library of steam. Ive tried both Play The Medium and Play The Medium DX12 with the same result.

## Reproduction
Launch game and play.

**Comment by kisak-valve** [comment]
Hello @byIlsa, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4574#issuecomment-892096192.
