### ISSUE TITLE
VK9 should be added to Proton for Directx 9 games. Direct3D 9 to Vulkan.

### ISSUE THREAD

**Issue by setsunati** [ValveSoftware/Proton#505]
Runs Direct3D 9 applications on Windows or Linux (/w Wine) over Vulkan.

https://github.com/disks86/VK9

**Comment by Zero86Sk** [comment]
This could solve issues on a lot of older games

**Comment by jarrard** [comment]
As its been pointed out before the project is not quite far enough along for integration, there are 39+ milestones needed to pass first and the chap is only at the 26th or so.

**Comment by vanyasem** [comment]
Duplicate of #102

**Comment by kisak-valve** [comment]
Closing as a duplicate of #102.

**Comment by caioalarcon** [comment]
bacana
