### ISSUE TITLE
Games do not detect vulkan support

### ISSUE THREAD

**Issue by CJ1169** [ValveSoftware/Proton#5050]
#### Your system information

* Steam client version (build number or date): 
* Jul 20 2021, at 22:25:57
* Distribution (e.g. Ubuntu): 
* Manjaro; `Linux ceejay-desktop 5.12.19-1-MANJARO ValveSoftware/steam-for-linux#1 SMP PREEMPT Tue Jul 20 20:57:37 UTC 2021 x86_64 GNU/Linux`
* Opted into Steam client beta?: [Yes/No]
* No, nor have I tried for this issue.
* Have you checked for system updates?: [Yes/No]
* Yes

Output for `yay -Qs`:
[yay.mesa.log](https://github.com/ValveSoftware/steam-for-linux/files/6942224/yay.mesa.log)
[yay.steam.log](https://github.com/ValveSoftware/steam-for-linux/files/6942227/yay.steam.log)
[yay.vulkan.log](https://github.com/ValveSoftware/steam-for-linux/files/6942229/yay.vulkan.log)

#### Please describe your issue in as much detail as possible:
[steam.log](https://github.com/ValveSoftware/steam-for-linux/files/6942202/steam.log)
[vulkan.log](https://github.com/ValveSoftware/steam-for-linux/files/6942203/vulkan.log)
[hardwareinfo.log](https://github.com/ValveSoftware/steam-for-linux/files/6942256/hardwareinfo.log)
#### Steps for reproducing this issue:

1. Clear .local/share/Steam
2. Sign in and set up steam
3. Reboot steam and collect logs from here
4. Attempt to boot game that has worked prior
5. Game complains about DX11 not being available and closes
6. Close steam

Extra details:
- This issue exists for multiple games (looks like all games that attempt to use vulkan, only tried proton games)
- This issue continues to exist despite changing proton versions
- I used https://www.protondb.com/app/933110 for these logs
- vulkaninfo attached as vulkan.log
- Proton Experimental used for provided logs. Changing versions does not seem to fix issue.
- Help -> System Information attached as hardwareinfo.log

**Comment by kisak-valve** [comment]
Hello @CJ1169, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report.

A couple details, can you let Steam's system information finish collecting the extended diagnostic information, then update the attached hardware info? I suspect your issue is related to the game using AMDVLK. Can you retest with mesa/RADV?

**Comment by CJ1169** [comment]
[hardwareinfo.log](https://github.com/ValveSoftware/Proton/files/6942593/hardwareinfo.log)
Attached is an updated hardware info (pre-running `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json steam`)

Ran the above code snippet. The game did boot as expected. This is the behavior I'm used to.
[hardwareinfo.radv.log](https://github.com/ValveSoftware/Proton/files/6942623/hardwareinfo.radv.log)
Attached a second hardware info, just in case.

That seemed to be the case!

Do you need another steam.log for extra information?


For all others that stumble here, the fix was to add RADV to the vulkan loader to select the RADV driver.
Add `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json` to your `/etc/environment` file to make the change permenant.
OR remove the `amdvlk` packages to remove the other driver.
