### ISSUE TITLE
FSR hack support in mainstream proton

### ISSUE THREAD

**Issue by Sakura0134** [ValveSoftware/Proton#5051]
# Feature Request
FSR hack support for mainstream proton
## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
I have used proton_FSR hack in a custom proton version called proton_ge and it works great. The best part is it works on all games(Only Windows games that run through proton) even if it(the game) doesn't have fsr by default.
## Justification [optional] 
Because it depends on how proton works rather than wine based on the documentation of the feature in proton_ge
## Risks [optional]
unknown as of now
## References [optional] 
https://github.com/GloriousEggroll/proton-ge-custom

**Comment by GloriousEggroll** [comment]
the original author already has a pull request open for it:

https://github.com/ValveSoftware/wine/pull/116

**Comment by kisak-valve** [comment]
Right, there's no point in tracking this as a general feature request when there's already direct communication between the patch author and the Proton devs. Closing in favor of https://github.com/ValveSoftware/wine/pull/116.
