### ISSUE TITLE
Sync error in multiplayer games! 

### ISSUE THREAD

**Issue by diemuellermilch85** [ValveSoftware/Proton#5058]
Dear Ladies and Gentlemen,

I generally wanted to point out a problem with Proton / Linux!

I also use Linux Manjaro (Kernel 5.13), all drivers up to date and Steam with Proton.
Ryzen 3900x + 6900xt + 32GB ram 

Unfortunately with ALL multiplayer games like Dawn of War Soulstorm, but also with Company of Heroes 2 and AOE 2 Definitv Edition, if this starts with Proton, regardless of the Proton version, there is always a disconnection in multiplayer games.

SYNC ERROR!

The problem seems to affect a lot of people on the Internet as there are numerous reports about it in forums.

Is it possible, that you fix the problem? 

Kind regards

diemuellermilch85

**Comment by supersteeeeeeeve** [comment]
Without a filled gist report or proton logs, nobody can help you.
When creating an issue, just fill out the template.

**Comment by diemuellermilch85** [comment]
Hey supersteve, 
thank you for the answer.  

I uploaded the proton log for Company of Heroes 2. 

[steam-231430.log](https://github.com/ValveSoftware/Proton/files/7001642/steam-231430.log)
[syncerror_previousframe_-1.2021-08-17.18-24-29.txt](https://github.com/ValveSoftware/Proton/files/7001644/syncerror_previousframe_-1.2021-08-17.18-24-29.txt)
[syncerror_outofsyncframe_0.2021-08-17.18-24-29.txt](https://github.com/ValveSoftware/Proton/files/7001646/syncerror_outofsyncframe_0.2021-08-17.18-24-29.txt)

**Comment by diemuellermilch85** [comment]
![Screenshot_20210817_182726](https://user-images.githubusercontent.com/88731634/129801405-44a4394c-529e-4271-8960-c39199985351.png)

Match lost

Sync-Error. Sometimes after a few seconds, after 1-2 min., sometimes after 10 min. 
For Dawn of War Soulstorm its the same.

**Comment by supersteeeeeeeve** [comment]
COH2 requires VC 2015

Navigate to the proton dir and install it in the right prefix.

```
cd /home/$USER/.steam/steam/steamapps/compatdata/231430/pfx/drive_c/windows/system32/
wget “https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145"
cabextract vc_redist.x64.exe
cabextract a10
```

**Comment by diemuellermilch85** [comment]
I installed it, like you described it, but it still crashes......
[steam-231430.log](https://github.com/ValveSoftware/Proton/files/7025866/steam-231430.log)

**Comment by diemuellermilch85** [comment]
Do you have another idea?

**Comment by diemuellermilch85** [comment]
https://www.protondb.com/app/231430

To "REPLACE" the ucrtbase.dll ---> then it works!

**Comment by kisak-valve** [comment]
Hello @diemuellermilch85, each game you're seeing multiplayer sync issues with needs to be evaluated separately. We shouldn't assume that there is a common issue between them.

Please check the existing compatibility reports at #3481. #3875, and #3189, and add a note if you've found some new insight to help troubleshoot the individual games.
