### ISSUE TITLE
Doom Eternal goes black after alt-tabbing out of game

### ISSUE THREAD

**Issue by MilkJug1** [ValveSoftware/Proton#5059]
# Compatibility Report
- Name of the game with compatibility issues: Doom Eternal
- Steam AppID of the game:782330

## System Information
- GPU: GTX 1650
- Driver/LLVM version: nvidia-470.57.02-9
- Kernel version:5.13.9-arch1-1
- Proton version: 6.3.5

## I confirm:
- [ :heavy_check_mark: ] that I haven't found an existing compatibility report for this game.
- [:heavy_check_mark: ] that I have checked whether there are updates for my system available.

## Symptoms 
Doom Eternal stops display game after alt-tabbing causing me to restart game,
Also has choppy performance when playing borderless  

## Reproduction
Go into Settings -> Video Settings -> Make Sure Fullscreen is on, then apply changes. Then alt-tab out and alt-tab back in.

**Comment by kisak-valve** [comment]
Hello @MilkJug1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3773#issuecomment-896307249.
