### ISSUE TITLE
No text/Menu on the start screen

### ISSUE THREAD

**Issue by pcfirebeats** [ValveSoftware/Proton#5060]
# Compatibility Report
- Name of the game with compatibility issues: Black Mesa
- Steam AppID of the game: 362890

## System Information
- GPU:  AMD Rrx 470
- Driver/LLVM version:  Mesa 21.2.0

- Kernel version:  5.11.0-25-generic

- Link to full system information report as [Gist](https://gist.github.com/): gist:8da25f34cc45d8ac0d954111ea68a899
- Proton version: Experimental 6.3-5

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 

On the Windows version of the game (the Linux native is very bad), there is no text in the start screen with the menu, so we can't select start a new game/load/options... There is only the background image.

## Reproduction

Open the game.

**Comment by kisak-valve** [comment]
Hello @pcfirebeats, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4545#issuecomment-896329163.
