### ISSUE TITLE
The Riftbreaker: Prologue fails to run.

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#5061]
# Compatibility Report
- Name of the game with compatibility issues: The Riftbreaker: Prologue
- Steam AppID of the game: 1293860

## System Information
System information: https://gist.github.com/coreybruce/dcd2bec911594c9212d351ac2e7a3f98
- Proton version: 6.3-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Game log: https://gist.github.com/coreybruce/d4f30393cd9923f5cec5e0b5c5d69825#file-steam-1293860-log

## Symptoms 
Launches the game and it just comes up with a error box 

"Unable to load game dll!

ERROR: unable to load: 'riftbreaker_dll_win_Release.dll'"

Than once you click ok the game stops.

## Reproduction
Launch game using proton.

**Comment by kisak-valve** [comment]
Hello @coreybruce, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4405#issuecomment-896657378.
