### ISSUE TITLE
Gets stuck before launching any window

### ISSUE THREAD

**Issue by RedDocMD** [ValveSoftware/Proton#5062]
# Compatibility Report
- Name of the game with compatibility issues: eFootball PES 2020
- Steam AppID of the game: 996470

## System Information
- GPU: NVIDIA GeForce GTX 1050
- Driver version: nvidia-470.57.02
- Kernel version: 5.11.0-7620-generic
- Link to full system information report [here](https://gist.github.com/RedDocMD/d5a8cb6b73cca6b64fef6815cc89bae5)
- Proton version: 6.3.5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Gets stuck at launch saying "Performing first time setup. Installing (step 1 of 1)"
![image](https://user-images.githubusercontent.com/54888685/129078544-7e70a566-842c-4afd-a8c4-fb6fd5f45720.png)

## Reproduction
- Install game
- Hit "Play" for the game
- Then it gets stuck

**Log file not produced**

**Comment by kisak-valve** [comment]
Hello @RedDocMD, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3227#issuecomment-897039808.
