### ISSUE TITLE
Mousecursor stuck on the wrong monitor in Quake Champions.

### ISSUE THREAD

**Issue by gituser823** [ValveSoftware/Proton#5063]
hello,

I am running Quake Champions with Proton experimental.

I have a two monitor setup and the mouse cursor is stuck on the right monitor, while the game is on the left.
The mouse "clicks" and works on the left monitor, but it is shown to be on the right monitor.

I am on Linux Mint 20.

Thanks!

**Comment by kisak-valve** [comment]
Hello @gituser823, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/225#issuecomment-897046634.
