### ISSUE TITLE
the game dont even starts 

### ISSUE THREAD

**Issue by thatdrigues** [ValveSoftware/Proton#5064]
so i try to open the game the vulkan [shaders] start but wen that ends this message appears and redirect to this link (https://support.codefusion.technology/mk11_9mn8iq2/?e=88500006&l=english)
![Screenshot from 2021-08-12 14-55-35](https://user-images.githubusercontent.com/79659980/129213339-8e1e02d3-c55a-4fd2-be44-10382976821a.png)

**Comment by kisak-valve** [comment]
Hello @thatdrigues, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2594#issuecomment-897684809.
