### ISSUE TITLE
Total War: SHOGUN 2 (34330)

### ISSUE THREAD

**Issue by tele1** [ValveSoftware/Proton#5066]
# Compatibility Report
- Name of the game with compatibility issues: SHOGUN 2
- Steam AppID of the game: 34330

## System Information
```
$ inxi -Fxxxrz
System:
  Kernel: 5.11.0-25-lowlatency x86_64 bits: 64 compiler: N/A 
  Desktop: MATE 1.24.0 info: mate-panel wm: marco 1.24.0 dm: LightDM 1.30.0 
  Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
Machine:
  Type: Desktop Mobo: MSI model: B150M PRO-VDH (MS-7982) v: 1.0 
  serial: <filter> UEFI [Legacy]: American Megatrends v: 3.H0 
  date: 07/10/2018 
CPU:
  Topology: Quad Core model: Intel Core i5-6400 bits: 64 type: MCP 
  arch: Skylake-S rev: 3 L2 cache: 6144 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 21599 
  Speed: 3244 MHz min/max: 800/3300 MHz Core speeds (MHz): 1: 3301 2: 3301 
  3: 3300 4: 3300 
Graphics:
  Device-1: NVIDIA GK106 [GeForce GTX 660] vendor: Gigabyte driver: nvidia 
  v: 470.57.02 bus ID: 01:00.0 chip ID: 10de:11c0 
  Display: x11 server: X.Org 1.20.11 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa compositor: marco v: 1.24.0 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: NVIDIA GeForce GTX 660/PCIe/SSE2 
  v: 4.6.0 NVIDIA 470.57.02 direct render: Yes 
```

## Symptoms 
Only info for people who played it and  game now not working.
Game working with Proton **4.11-13**
and after run game will window and there you need choose **Direct 9**
Game not working ( at least for me) with a newer like Proton 6.3-5

**Comment by kisak-valve** [comment]
Hello @tele1, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Separately, it might be interesting to test the game with the game's launch options set to `PROTON_USE_WINED3D=1 %command%` because DXVK grew to support DirectX 9 in Proton 5.0-1.

**Comment by tele1** [comment]
Log not exist.
I found the cause.
I use firejail ( sandbox for apps ).
After disable firejail ( sudo firecfg --clean ) game working with **Proton 6.3-5**

Maybe the game is button-sensitive "Esc" when starts video , 
because sometimes the game shuts down, 
but working.
Example log with crash https://gist.github.com/tele1/0a9e613eca18587a5f28c83764952d95

**Comment by tele1** [comment]
Game working.

**Comment by kisak-valve** [comment]
These look like some lines of interest from the log:
```
warn:seh:dispatch_exception EXCEPTION_INT_DIVIDE_BY_ZERO exception (code=c0000094) raised
[...]
wine: Unhandled division by zero at address 62515F2D (thread 0198), starting debugger...
[...]
Unhandled exception: divide by zero in 32-bit code (0x62515f2d).
[...]
Backtrace:
=>0 0x62515f2d in d3d9 (+0xd5f2d) (0x00000000)
0x62515f2d: divl	%ebx,%eax
```

**Comment by tele1** [comment]
It looks like with "wine" problem
https://bugs.winehq.org/show_bug.cgi?id=33890#c3

**Comment by Lenny003** [comment]
Game would crash after a battle unless I turned Terrain Detail to low, otherwise game would run perfect, wanted to write this here for anyone else potentially having this issue. 
Tested with 6.3-8 and Proton Experimental.

**Comment by justeff** [comment]
> Game would crash after a battle unless I turned Terrain Detail to low, otherwise game would run perfect, wanted to write this here for anyone else potentially having this issue. Tested with 6.3-8 and Proton Experimental.

Thank you, thought I'm the only one having this problem. Too bad, the native port seems to be slower then running Proton.

**Comment by Patola** [comment]
Why is this report closed? Since the native version of this game doesn't work anymore (glibc compatibility issues), the proton version became more important, and it is not running. The launcher runs and then crashes.

**Comment by digitalinferno** [comment]
@Patola the native version works if you: 
1. force compatibility Steam Linux Runtime (Scout)
2. copy/link all .so file in game folder lib/i686 to lib
3. fix [this](https://github.com/GitoMat/Shogun2-Linux-Fix)

**Comment by Patola** [comment]
Thanks, @killing-vodka. However that's a lot of hassle to make it work, so much that I'm comfortable now in playing it via Proton (as it works now).
