### ISSUE TITLE
[Whitelist] Sam & Max 101: Culture Shock (8200)

### ISSUE THREAD

**Issue by felisucoibi** [ValveSoftware/Proton#507]
works perfect 

Información del equipo:
    Fabricante: Unknown
    Modelo: Unknown
    Factor de forma: Portátil
    Entrada táctil no detectada

Información sobre el procesador:
    Fabricante de la CPU: GenuineIntel
    Marca de la CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Familia de la CPU: 0x6
    Modelo de la CPU: 0x9e
    Stepping de la CPU: 0x9
    Tipo de CPU: 0x0
    Velocidad: 3800 MHz
    Procesadores lógicos: 8
    Procesadores físicos: 4
    HyperThreading:  Compatible
    FCMOV:  Compatible
    SSE2:  Compatible
    SSE3:  Compatible
    SSSE3:  Compatible
    SSE4a:  No compatible
    SSE41:  Compatible
    SSE42:  Compatible
    AES: Compatible
    AVX: Compatible
    CMPXCHG16B: Compatible
    LAHF/SAHF: Compatible
    PrefetchW: No compatible

Versión del sistema operativo:
    Ubuntu 18.04.1 LTS (64 bits)
    Nombre de kernel: Linux
    Versión de kernel: 4.15.0-32-generic
    Editor de X Server: The X.Org Foundation
    Versión de X Server: 11906000
    Gestor X Window: Compiz
    Versión del runtime de Steam: steam-runtime-beta-release_2018-06-14

Tarjeta de vídeo:
    Controlador:  Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) x86/MMX/SSE2
    Versión del controlador: 3.0 Mesa 18.0.5
    Versión de OpenGL: 3.0
    Densidad de color del escritorio: 24 bits por píxel
    Frecuencia de actualización del monitor: 60 Hz
    Identificador del fabricante: 0x8086
    Identificador del dispositivo: 0x591b
    Revisión no detectada
    Número de monitores: 1
    Número de tarjetas de vídeo lógicas: 1
    Resolución de pantalla principal: 1920 x 1080
    Resolución de escritorio: 1920 x 1080
    Tamaño de la pantalla principal: 73.70" x 41.46" (84.53" diag)
 187.2cm x 105.3cm (214.7cm diag)
    No se ha detectado la memoria VRAM principal

Tarjeta de sonido:
    Dispositivo de sonido: Realtek ALC233

Memoria:
    RAM: 15925 MB

Varios:
    Idioma de la IU:  Español
    IDIOMA: es_ES.UTF-8
    Espacio total en disco disponible: 452317 MB
    Bloque libre más grande en el disco: 147785 MB
    HMD de RV: Ninguno detectado

Informes de fallos recientes:

**Comment by Zero86Sk** [comment]
Do other games in the sam and mas seasons 1 and 2 work?

**Comment by felisucoibi** [comment]
all of them

**Comment by kisak-valve** [comment]
Found in the 2018-10-05 white list update.
