### ISSUE TITLE
Certain Xbox One controller inputs are registered incorrectly

### ISSUE THREAD

**Issue by konaOnTheHub** [ValveSoftware/Proton#5073]
I'm using a generic Xbox One controller in an over bluetooth setup and using xpadneo as a driver. The issue is that certain buttons get registered as other buttons on the controller in game. The buttons affected seem to be both LB and RB, X and Y and finally the little buttons below the silver xbox button. First I thought it was a driver-related issue however when testing controller inputs on this https://gamepad-tester.com/ online tool all the inputs checked out.

The games I tested so far are GTA V and Risk of Rain 2 in both of which the issue persisted although not in the same manner. 
For example in GTA V the Y button performed the action that X was supposed to and LB performed Y's all the rest of the affected buttons seemed to not do anything. In Risk of Rain 2 Y replaced X the same way however LB didn't replace Y (like in gta) instead both LB and RB's actions could be initiated by their directionnally corresponding menu buttons. 

I now tried this with both Proton Experimental and Proton 6.3.5 and the issue persisted in both of them.

Interestingly this does NOT happen in wine (Only tested in overwatch)
Similar issue: https://www.reddit.com/r/linux_gaming/comments/mu8sn9/xbox_one_controller_has_a_couple_incorrect/
![Screenshot from 2021-08-14 17-28-28](https://user-images.githubusercontent.com/88909837/129452996-c582f781-0d24-46c3-9a84-036b31b4a787.png)

**Comment by kisak-valve** [comment]
Hello @konaOnTheHub, we've seen this before at https://github.com/ValveSoftware/steam-for-linux/issues/7531, and is most likely not a Proton-specific issue. Closing in favor of the older issue report.
