### ISSUE TITLE
Proton does not properly set the "_NET_WM_BYPASS_COMPOSITOR" window property

### ISSUE THREAD

**Issue by katawful** [ValveSoftware/Proton#5074]
With Proton 6.3-5 and 5.13-6, games launched through either do not set the `_NET_WM_BYPASS_COMPOSITOR` flag to 1. This means that the X11 compositor in use does not know to unredirect itself, leading to worse performance and higher VRAM usage. I cannot set my compositor to manually disable without killing it, which is undesirable. This bug affects every Proton game I have downloaded (around 10), but no native titles

**Comment by kisak-valve** [comment]
Hello @katawful, there's no value in fragmenting the discussion at #4469 over multiple issue reports. Closing as a duplocate.
