### ISSUE TITLE
Disney Epic Mickey 2 | 245300

### ISSUE THREAD

**Issue by timdevorg** [ValveSoftware/Proton#5077]
# Compatibility Report
- Name of the game with compatibility issues: Disney Epic Mickey 2
- Steam AppID of the game: 245300

## System Information
- GPU: RX 590
- Driver/LLVM version: Mesa 21.1.6
- Kernel version: 5.13.9
- Link to full system information report as Gist: https://gist.github.com/Proton64/40008b3be106365892708eb6c97ffb0a
- Proton version: Proton-6.14-GE-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-245300.log](https://github.com/ValveSoftware/Proton/files/6988117/steam-245300.log)

## Symptoms 

The background of menus and the main menu are completely green as well as in game HUD elements.
Due to this, you do not know which buttons to press in order to control the game / navigate through the menus.

## Reproduction

Start the game and look at the main menu / play the game and see green boxes for HUD elements.

**Comment by mrhanman** [comment]
I'm seeing the same issue with Valve's default Proton 6.3-6. Does another issue need to be opened, or can the "Unofficial" label be changed?

I also tried Proton-6.16-GE-1 with the same results. Apart from the GUI/HUD rendering issues, it seems to run well, though with a lower than expected framerate.

Nvidia RTX 3070
Proprietary driver version 470.63.01
Arch 5.14.5-zen2-1-zen

**Comment by mrhanman** [comment]
As of Proton 7.0-1, this game works perfectly.

**Comment by timdevorg** [comment]
Can confirm.

**Comment by lividhen** [comment]
Game no longer works. Testing with 7.0-6. The green is back.
Cant get 7.0-1 to build so if anyone has a redist , would you mind sharing until this is fixed?

**Comment by kisak-valve** [comment]
Hello @lividhen, since the reporting user has chosen to close this compatibility report and there is no other open compatibility report for this game, please open a new issue report to track your feedback for this game.
