### ISSUE TITLE
Temtem keyboard hints display foreign characters/symbols

### ISSUE THREAD

**Issue by Weetile** [ValveSoftware/Proton#5079]
# Compatibility Report
- Name of the game with compatibility issues: Temtem
- Steam AppID of the game: 745920

## System Information
- GPU: RX 480
- Driver/LLVM version: Mesa 21.1.6 LLVM 12.0.1
- Kernel version: 5.12
- Link to full system information report as [Gist](https://gist.github.com/Weetile/a438be4f9d160486173400be231ef79c/):
- Proton version: Proton 6.3-5
- OS: Manjaro Linux

## I confirm:
- [Y] that I haven't found an existing compatibility report for this game.
- [Y] that I have checked whether there are updates for my system available.

[steam-745920.log](https://github.com/ValveSoftware/Proton/files/6994724/steam-745920.log)

## Symptoms 
The ingame keyboard hints are displaying alternate languages and symbols in game.
When a keyboard button is pressed, these symbols go through rotations to different non-English languages (e.g: random Japanese and Chinese symbols)
The same issues occur on other machines, and with and without Steam Input enabled.

## Reproduction
Open Temtem and view the in-game keybinding menu or keyboard hints in game.

**Comment by Weetile** [comment]
![image](https://user-images.githubusercontent.com/7700383/129615647-8a3e3048-8a32-4c61-8863-b7c89adff27e.png)
![image](https://user-images.githubusercontent.com/7700383/129615732-69aac187-5518-4825-a4aa-6b2c2fbf8427.png)

This is an example of what I'm referring to.

**Comment by kisak-valve** [comment]
Hello @Weetile, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3441#issuecomment-899758770.
