### ISSUE TITLE
Elder Scrolls IV: Oblivion GOTY cannot launch game

### ISSUE THREAD

**Issue by C01NoP** [ValveSoftware/Proton#5080]
# Compatibility Report
- Name of the game with compatibility issues: The Elder Scrolls IV: Oblivion® Game of the Year Edition
- Steam AppID of the game: 22330

## System Information
- GPU: NVIDIA Corporation NVIDIA GeForce GTX 980/PCIe/SSE2
- Driver/LLVM version:  4.6.0 NVIDIA 470.63.01
- Kernel version:  5.13.10-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/C01NoP/13f68bd026950c303b488d8dbc1a8971
- Proton version: Proton 6.3-5

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

 [steam-22330.log](https://github.com/ValveSoftware/Proton/files/6995596/steam-22330.log)

## Symptoms 

Game launcher window opens and a game cannot be started. The following options are greyed out: play, data files, options, technical support, uninstall. Only available options are "elderscrolls.com" and "exit." You should be able to configure graphics settings/etc in options and then click "play" to launch the game.

## Reproduction

Install the game and launch using the Proton compatibility tool. The launcher window will appear with the aforementioned issues.

**Comment by kisak-valve** [comment]
Hello @C01NoP, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/718#issuecomment-899849500.
