### ISSUE TITLE
Nights of Azure 2 (636570)

### ISSUE THREAD

**Issue by CygnusTerminal** [ValveSoftware/Proton#5082]
# Compatibility Report
- Name of the game with compatibility issues: Nights of Azure 2
- Steam AppID of the game: 636570

## System Information
- GPU: GTX 1650 Laptop
- Driver/LLVM version: 470.63.01
- Kernel version: 5.13
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/CygnusTerminal/86ae4ed7ac5e377f92d4b9c276bf593c
- Proton version: 6.3-5

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-636570.log](https://github.com/ValveSoftware/Proton/files/7004046/steam-636570.log)

## Symptoms 
Games instantly crashes to desktop while trying to load a game/starting a new game. Unplayable on this state.

## Reproduction
1. Launch game
2. Load a game/start new game
3. Crash to desktop

**Comment by kisak-valve** [comment]
Hello @CygnusTerminal, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2763#issuecomment-901043423.
