### ISSUE TITLE
Warhammer® 40,000: Dawn of War® - Dark Crusade (4580) not running on Fedora

### ISSUE THREAD

**Issue by makingglitches** [ValveSoftware/Proton#5083]
# Compatibility Report
- Name of the game with compatibility issues:  Warhammer 40k dawn of war: dark crusade
- Steam AppID of the game: 4580 

## System Information
- GPU: 
-   Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 610 (KBL GT1) (0x5906)
    Version: 21.1.7
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2

- Kernel version: 5.13.9-200.fc34.x86_64

- Proton version: 6.35  same as before.

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 

The steam dialog indicates the game is starting, it spawns two processes in task manager and silently dies with no visible error message.

## Additional
Seems like there are alot of isses with these games listed however. Differing versions of dawn of war are having problems of different sorts.

## Reproduction
Start the game on fedora linux

##Logs retrieved from system journal
08:16:01 dleyna-renderer: dLeyna: Exit
08:16:00 gnome-logs: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
08:16:00 dleyna-renderer: Calling GetRenderers method
08:16:00 systemd: Started dbus-:1.2-com.intel.dleyna\x2drenderer@10.service.
08:15:59 nautilus: Source ID 117195 was not found when attempting to remove it
08:15:59 gnome-shell: Failed to set the markup of the actor 'ClutterText': Error on line 1 char 28: Odd character “S”, expected a “=” after attribute name “Less-than” of element “:”
08:15:59 systemd: Started dbus-:1.2-org.gnome.clocks@7.service.
08:15:54 steam: Exiting app 4580
08:15:54 wine: wine: /Data/SteamLibrary/steamapps/compatdata/4580/pfx is not owned by you
08:15:54 steam: >>> Adding process 10702 for game ID 4580
08:15:54 wine: ERROR: ld.so: object '/home/john/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
08:15:54 steam: >>> Adding process 10701 for game ID 4580
08:15:54 wine: ERROR: ld.so: object '/home/john/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
08:15:54 wineserver: wine: /Data/SteamLibrary/steamapps/compatdata/4580/pfx is not owned by you
08:15:53 steam: >>> Adding process 10696 for game ID 4580
08:15:53 proton: ERROR: ld.so: object '/home/john/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
08:15:53 steam: GameAction [AppID 4580, ActionID 3] : LaunchApp changed task to Completed with ""
08:15:53 proton: ERROR: ld.so: object '/home/john/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
08:15:53 steam: GameAction [AppID 4580, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
08:15:53 sh: ERROR: ld.so: object '/home/john/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
08:15:53 steam: Game update: AppID 4580 "", ProcID 10695, IP 0.0.0.0:0
08:15:52 dleyna-renderer: dLeyna: Exit
08:15:52 bash: /home/john/.local/share/Steam/ubuntu12_32/steam steam://rungameid/4580
08:15:51 dleyna-renderer: Client :1.515 lost
08:15:51 bash: STEAM_RUNTIME is enabled automatically

**Comment by kisak-valve** [comment]
Hello @makingglitches, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by makingglitches** [comment]
Eh crap will do.
Sorry been kind of you know held hostage from life for a few months

**Comment by makingglitches** [comment]
I think I already said this, heh.
several kernel releases etc in this repetitive time period where the country's soul dies in shame, has seemingly fixed launch and game play.

Still on release 34.

Kernel however is 5.17.8-100.fc34.x86_64
And Proton version that is apparently working is 4.2-9 which somehow it defaulted to.
