### ISSUE TITLE
[Whitelist] Star Wars: Dark Forces (32400)

### ISSUE THREAD

**Issue by kforney** [ValveSoftware/Proton#509]
Runs perfectly out of the box on Fedora 28.

This one barely even needs Proton; if you swapped the included Windows version of DosBox for a native Linux version, it would run just as well.

[System Information](https://gist.github.com/kforney/d58aecb8e8fedfd15e0743643e264eeb)

**Comment by kisak-valve** [comment]
Hello @kforney, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by ghost** [comment]
Can confirm that the game runs fine, with sound on [my setup](https://gist.github.com/DrWindu/1a10ea5e4305d2f4716bc75fdf6fdfff), but there is one issue.

I have a french, AZERTY keyboard, and the keyboard bindings for some of weapons like the Bryar (2/é) do not work. Switching in KDE to a US QWERTY layout confusingly swaps zqsd/wasd for movement, but does not fix the issue of 'é' being unregistered, making the game half unplayable (there is no way to rebind the keys).

I cannot test if the same issue exists on Windows, but it might be the case. I know that an ISO copy of my own french CD of Dark Forces works as intended in DosBox, but trying to switch the game's language in Steam to either French or English does not help.

**Comment by kforney** [comment]
@kisak-valve : Done. [System Information](https://gist.github.com/kforney/d58aecb8e8fedfd15e0743643e264eeb)

@DrWindu : You could maybe try adding the following lines to the "dosbox.conf" file in the game's data folder, to manually tell the game's emulator what keyboard layout to use?

[dos]
keyboardlayout=fr

All the keyboard layout codes are [here](https://www.dosbox.com/wiki/KEYB) , and all the dosbox.conf information is [here](https://www.dosbox.com/wiki/dosbox.conf) .

**Comment by ghost** [comment]
Unfortunately, fiddling with `keyboardlayout` in the dosbox config file did not help the issue.

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.
