### ISSUE TITLE
Quake (2310)

### ISSUE THREAD

**Issue by stuartpb** [ValveSoftware/Proton#5094]
The new version of Quake, released today, doesn't start under Proton - it shows as "Launching", then "Running" for a few seconds, then stops.

**Comment by Mrstansbeary** [comment]
WinQuake works if you go to where the Quake folder is but Do not use GlQuake and plan Quake doesn't work. I just tried it and yes the GlQuake will give you a nightmare trying to fix your Desktop but Winquake at least works.

**Comment by KayKay91** [comment]
It does not start because Valve's whitelist takes priority, it tries to run with Proton 3.7-8 which was used for original Quake. Forcing it to use a newer version will do the trick. Works fine under 6.3-5.

The whitelist for it needs to be updated

**Comment by Mrstansbeary** [comment]
Start Steam and go to Quake and right Click and Go to the Folder and look for a Folder called Rerelease and click on the Quake64.exe and play. The Quake in Steam is the Quake Dos version which doesn't work on Windows let alone on Linux. yes this sucks but go Figure they make it so you have to go through these steps on Windows\Linux both.

**Comment by JPLeBreton** [comment]
> It does not start because Valve's whitelist takes priority, it tries to run with Proton 3.7-8 which was used for original Quake. Forcing it to use a newer version will do the trick. Works fine under 6.3-5.

On my system, checking "Force the use of a specific Steam Play compatibility tool" and setting Proton 6.3-6 does not allow the game to launch (ie it still goes from "launching" to "running" then stops after a few seconds). Does this mean the whitelist is still forcing it to the older Proton?

> Start Steam and go to Quake and right Click and Go to the Folder and look for a Folder called Rerelease and click on the Quake64.exe and play. The Quake in Steam is the Quake Dos version which doesn't work on Windows let alone on Linux. yes this sucks but go Figure they make it so you have to go through these steps on Windows\Linux both.

This works for me, but I don't get the benefits of running it through Steam, eg achievements.

**Comment by kisak-valve** [comment]
Hello @JPLeBreton, Steam should tell you which compatibility tool it is going to use if you go to the game in Steam's Library view, click the ⓘ button on the right, and in the section that expands, it should have something like "Runs on this computer via Steam Play. Proton # selected by you for this title."

The per-game compatibility tool override takes priority over Valve's whitelist, which takes priority over the global setting.

**Comment by JPLeBreton** [comment]
> Hello @JPLeBreton, Steam should tell you which compatibility tool it is going to use if you go to the game in Steam's Library view, click the ⓘ button on the right, and in the section that expands, it should have something like "Runs on this computer via Steam Play. Proton # selected by you for this title."
> 
> The per-game compatibility tool override takes priority over Valve's whitelist, which takes priority over the global setting.

Thanks! Hmm, according to that info it is indeed running with Proton 6.3-6 then. So 6.3-6 does not run this game on my system.

**Comment by rjzak** [comment]
> So 6.3-6 does not run this game on my system.

Proton 6.3-6 and prior versions don't work on my machine either. Either the game just crashes, or I have a blank screen and hear Bethesda's logo/intro, then it crashes. If it matters, I've got an Nvidia 2070 with drivers 470.57.02,

**Comment by aidans02** [comment]
I've also noticed that the multiplayer component of the Quake re release does not work unless you change wines windows version to Windows 7. In the rerelease folder inside Quake it contains PartyWin.dll and PartyWin7.dll, so I guess wine doesn't like the modern windows version of whatever networking components the game is using.

**Comment by felipsmartins** [comment]
I can confirm the same behavior like in the @JPLeBreton Steam. The game starts, runs and then/suddenly stops.

**Comment by mahalel** [comment]
I have just tried it tonight and it seems to work now, using Proton experimental.

**Comment by felipsmartins** [comment]
Now using Proton Experimental (like @mahalel said before) works to me :)

**Comment by thomond** [comment]
> > So 6.3-6 does not run this game on my system.
> 
> Proton 6.3-6 and prior versions don't work on my machine either. Either the game just crashes, or I have a blank screen and hear Bethesda's logo/intro, then it crashes. If it matters, I've got an Nvidia 2070 with drivers 470.57.02,

Try setting the launch command to `%COMMAND% +r_rhirenderfamily d3d11`
Appears to be an issue with vulcan and the engine Nightdive studios use. Quake64 has the same problem/solution.

https://www.gamepretty.com/quake-how-to-fix-crashing-in-new-remastered-version/

**Comment by arrowgent** [comment]
game runs fine using proton5.0 and proton6.3

_dont need to use_ `+r_rhirenderfamily d3d11` it works fine with stock **vulkan**  `+r_rhirenderfamily vulkan`

**opengl is not supported, i dont know why people keep suggesting that
if you set "opengl" it defaults to d3d11 as shown in the console
there are no opengl shaders at all in the KEX rerelease**
only HLSL and SPIRV


### other notes
multiplayer with bots seems to crash within 2 minutes no matter what map or amount of bots
i have not tested online multiplayer.  i block internet access and dont wish to be tracked by telemetry by bethesda

**Comment by thomond** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/5094#issuecomment-907648766

`+r_rhirenderfamily d3d11` works for me too, it seems if you put any value apart from vulkan it uses d3d11 anyway so opengl is a red herring.  Using `+r_rhirenderfamily vulkan` results in a  black screen and eventually a crash for me. Only `+r_rhirenderfamily d3d11` works for me.

**Comment by Leopard1907** [comment]
https://steamdb.info/app/891390/history/?changeid=12431645

There is no longer a whitelist so this shouldn't be an issue anymore. Games defaults to whatever you set as your global Proton selection on Steam Play menu in the client.

**Comment by jefferyrlc** [comment]
I got +r_rhirenderfamily vulkan to work after using AMDVLK over RADV. Otherwise I had to use +r_rhirenderfamily d3d11 to get the game to work.

CPU Ryzen 7 5800X
GPU Radeon RX 6800XT
Kernel 5.17
Arch Linux

**Comment by BNieuwenhuizen** [comment]
> I got +r_rhirenderfamily vulkan to work after using AMDVLK over RADV. Otherwise I had to use +r_rhirenderfamily d3d11 to get the game to work.

What mesa version and what proton version did you use? And what did not work with radv? (FWIW I tried to give it a spin and it just worked for me, so maybe I'm missing symptoms or there is a setup difference that matters)

**Comment by jefferyrlc** [comment]
Mesa 22.0.1
Proton 7.0-2 and GE-Proton 7-15
And it crashed as soon as I launched the game. It said see the error log

**Comment by radgeRayden** [comment]
Today's update fails to launch under gamescope. I'm not sure whether this is a proton or gamescope issue. It doesn't really say anything in the logs.

**Comment by arrowgent** [comment]
working fine on my end..

```
AMD Ryzen 9 7945HX
GPU AMD Radeon RX 7900M navi31
Mesa 26.1.6 - kisak-mesa
Vulkan 1.4.350
Linux 7.1.6-amdr18
gcc (Ubuntu 15.2.0-16ubuntu1) 15.2.0
Ubuntu 26.04 LTS
```

proton 10.0-4b
proton-cachyos-10.0-sunset-slr-x86_64_v3

both working

example log:
```
Proton: 1781706534 cachyos-10.0-sunset-slr
SteamGameId: 2310
Command: ['/home/amdr18/.local/share/Steam/steamapps/common/QUAKE/rerelease/quake_x64_steam.exe', '-skipmovies']
Options: {'ntsync', 'forcelgadd', 'gamedrive', 'oldglstr'}
depot: 3.0.20260714.251853
pressure-vessel: 0.20260714.0
pressure-vessel-arm64: 0.20260714.0
scripts: 0.20260714.0
sniper: 3.0.20260714.251853 sniper 3.0.20260714.251853
Kernel: Linux 7.1.6-amdr18 #1 SMP PREEMPT_DYNAMIC TKG Wed Aug  5 19:00:45 PDT 2026 x86_64
Language: LC_ALL None, LC_MESSAGES None, LC_CTYPE None
PATH: /home/amdr18/.local/share/Steam/compatibilitytools.d/proton-cachyos-10.0-sunset-slr-x86_64_v3/files/bin/:/usr/bin:/bin
Effective WINEDEBUG: +timestamp,+pid,+tid,+seh,+unwind,+threadname,+debugstr,+loaddll,+mscoree
```

just checked proton-cachyos-11.0-20260703-slr-x86_64_v3
that one is working too

i dont use steam's proton 11.0-1
sorry...

**Comment by radgeRayden** [comment]
> working fine on my end..

@arrowgent with gamescope? I don't see a reference to it in your message

**Comment by arrowgent** [comment]
> > working fine on my end..
> 
> [@arrowgent](https://github.com/arrowgent) with gamescope? I don't see a reference to it in your message

steam deck?

i use gamescope, when needed.
i also am on X11, not wayland.

what is your version of gamescope?

```
apt list gamescope -a
gamescope/resolute,resolute,resolute,resolute,now 3.16.20+ds-1 amd64 [installed]
```

i normally would compile gamescope myself.  i havent needed to on this install.
`gamescope_3.16.24_2604`
latest git src: [3.16.25](https://github.com/ValveSoftware/gamescope/releases/tag/3.16.25)


lastly...
what is your steam launch option command?
`gamescope -- %command%` example

**Comment by radgeRayden** [comment]
On PC with an NVIDIA card.
gamescope version: gamescope version 3.16.24-20-ga563226d (gcc 16.1.1)
steam launch command is `gamescope -- %command%`
NVIDIA driver version: 610.57.4.0
