### ISSUE TITLE
Total War: Rome 2 Crashing during play

### ISSUE THREAD

**Issue by Sackbuoy** [ValveSoftware/Proton#5096]
# Compatibility Report
- Name of the game with compatibility issues: Total War: Rome 2
- Steam AppID of the game: 214950

## System Information
- GPU: GTX 1060
- Driver/LLVM version: Nvidia 470.63.01
- Kernel version: 5.10.59-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/01db891982c23cf4999a58d315150ca2)
- Proton version: 6.3-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-214950.log](https://gist.github.com/Sackbuoy/66d9ee2821a5280079603a2deb232ed7)

## Symptoms 
Game is crashing during a campaign, seemingly at random after about 10-15 minutes of play, typically when ending a turn while it is processing all of the other factions moves. It produces not output, nothing happens, the game window simply closes without warning.

## Reproduction
The only way I can reproduce it is by playing the game for about 15 minutes. I cannot seem to intentionally trigger it any way, though I will keep trying and update If i find anything

https://github.com/ValveSoftware/Proton/issues/512 is the only other issue I can find, but it appears to be a different issue that never got resolved. I am opening this one since that one seems unrelated.

**Comment by kisak-valve** [comment]
Hello @Sackbuoy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/512#issuecomment-902970442.
