### ISSUE TITLE
Some games refuse to start in full screen

### ISSUE THREAD

**Issue by dragonfly-lover** [ValveSoftware/Proton#510]
Some games don't start in full screen mode. Trying to Force It by ALT+ENTER gives no result. 

I have two examples:

Pro Evolution soccer 2018 starts only in Windowed mode.

Tekken 7 starts in borderless window mode.

Should be a great idea to Force fullscreen (ideally in a per-game setting) either incapsulating the corresponding wine setting or forcing It by steam client itself.

**Comment by fabry92** [comment]
yeah it happen on my ubuntu 18.04. This issue happen with Tekken 7. Below the screenshot of the problem
![schermata da 2018-08-26 10-37-22](https://user-images.githubusercontent.com/20151225/44626419-19b0dd80-a91c-11e8-9fc6-e845c55b22c0.png)

**Comment by leillo1975** [comment]
Pro Evolution soccer has a configuration utility when you start the game (in Windows), where you can set the game in fullscreen. In linux, it's not shown at the start

**Comment by NTMan** [comment]
> Tekken 7 starts in borderless window mode.

How start Tekken 7 in borderless window mode? By default it start in fullscreen mode and demonstrate always black screen. So I can't enter in game settings for change fullscreen to borderless window.

**Comment by ghost** [comment]
Same for me, I can have the game fullscreen when changing the resolution.

**Comment by Saladin1812** [comment]
Is this bug on KDE or other desktop environments ?
