### ISSUE TITLE
Version 6.3.6 broke Far Cry 2 compatibility

### ISSUE THREAD

**Issue by halvors** [ValveSoftware/Proton#5100]
# Compatibility Report
- Name of the game with compatibility issues: Far Cry 2
- Steam AppID of the game: 19900

## System Information
- GPU: AMD RADV NAVI10
- Driver/LLVM version: amdgpu
- Kernel version: 5.13
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/halvors/0d67036c1b81f0e4c1e4cae583466262
- Proton version: 6.3.6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Far Cry 2 instantly crash on launch.

## Reproduction
Try to launch Far Cry 2.
[steam-19900.log](https://github.com/ValveSoftware/Proton/files/7025531/steam-19900.log)

**Comment by kisak-valve** [comment]
Hello @halvors, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/775#issuecomment-903113026.
