### ISSUE TITLE
The Ascent DX12 has real bad stutters, crashes often

### ISSUE THREAD

**Issue by eitch** [ValveSoftware/Proton#5103]
[steam-979690.log](https://github.com/ValveSoftware/Proton/files/7026091/steam-979690.log)
# Compatibility Report
- The Ascent
- Steam AppID of the game: 979690

## System Information
- GPU: AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.41.0, 5.13.9-051309-generic, LLVM 12.0.1) (0x73bf)
- Driver/LLVM version: OpenGL renderer string: AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.41.0, 5.13.9-051309-generic, LLVM 12.0.1)
- Kernel version: 5.13.9-051309-generic
- Link to full system information report as https://gist.github.com/eitch/7eac05d3ca61a0c4ba802199df462343
- Proton version: 6.3 and also tried 6.13-GE-1, 6.14-GE-2, 6.15-GE-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game runs quite alright with DX11, even though it has micro stutters quite continuously. Nothing that is too annoying.

Changing the game to DX12 let's it start, but usually won't allow me to enter a game. The main menu loads, has very high stutters, even though the FPS overlay says i have over 100 FPS-

## Reproduction
Start the game, change the driver type to DX12 from DX11 in the graphics settings, restart the game and see the bad stutters.

**Comment by kisak-valve** [comment]
Hello @eitch, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5034#issuecomment-903165012.

**Comment by eitch** [comment]
oh, ok. Thanks
