### ISSUE TITLE
Stationeers (544550)

### ISSUE THREAD

**Issue by MrBigss** [ValveSoftware/Proton#5105]
# Compatibility Report
- Name of the game with compatibility issues: Stationeers
- Steam AppID of the game: 544550

## System Information
- GPU: GeForce GTX 860M
- Driver/LLVM version: nvidia 460.91.03
- Kernel version: 5.4.0-81-generic
- Link to full system information report as Gist: [System report](https://gist.github.com/MrBigss/13722a91823d0c87228bf60c5868860e)
- Proton version: 6.3-6

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[Log from PROTON_LOG=1 steam-544550.log.zip](https://github.com/ValveSoftware/Proton/files/7026305/steam-544550.log.zip)

## Symptoms 

In the game, the mouse is used in two way. First, when interacting with the environment with the items, or in the menus before the game. Those are simple "you click, it does something".
When in first person, in the game, you can also hold alt, and the cursor shows up. This allows opening the inventories, and manipulating things in the inventory, without using the keyboard.
The issue is that, while the mouse shows up, and the cursor shows up, now the clicks do not seem to register anymore.
I can't pick up items, or even open/close the inventory menus.

Also tried with Proton experimental, same problem now. Experimental didn't use to work correctly for the game, hence why I was plagin on Proton 6.3.-5
There was no update to the game since the problem showed up.
Compositing has been off for all versions.

## Reproduction
Start a game, get in first person mode, and then try to manipulate the UI with the mouse. Mouse shows up, "highlighting" shows up when hovering items, but mouse clicks do not register.

**Comment by MrBigss** [comment]
Even more strange.
When holding alt to do these actions, it's also possible to also hold shift to get information on the object instead.
That, alt+shift+left click, actually does work. O_o
(There's an option for "legacy inventory" in the game, I made sure it is not selected, obviously.)

**Comment by alasky17** [comment]
@MrBigss Thank you for the detailed report.  I was able to reproduce the exact behavior and reported the regression. Interestingly (but not too surprisingly) it seems to only be a regression on xfce -- I also tested Gnome and KDE and neither had the alt menu problem with Stationeers.

**Comment by MrBigss** [comment]
Found a workaround.  
If I disable the "acessibility" function where alt is used to drag windows, the behavior returns to normal.  
It seems like somehow alt click is intercepted by whatever as "move window"  
I am on xfce, did I specify?

**Comment by alasky17** [comment]
@MrBigss It said XFWM in your system report output which is how I knew where to test :)  Is the "accessibility function" in XFCE settings somewhere?  

It makes sense that there is a change in behavior here by the way - there were some patches in 6.3-6 that changed focus behavior specifically with the alt key :+1:

**Comment by MrBigss** [comment]
I think it's "window tweaks" or something in the config panel. Sorry no acess right now.  
It's on by default.

**Comment by alasky17** [comment]
@MrBigss I found the difference between 6.3-5 and 6.3-6 - we changed the default for the "Automatically capture the mouse in full-screen windows" setting in winecfg (https://github.com/ValveSoftware/Proton/issues/53).  Since wine and xfce are both doing sane things and they just happen to interact unfortunately for this particular game on xfce, we are planning to keep the default as it is.  In addition to the other workaround you've found, you could also use protontricks or winetricks to change this setting for the game prefix, although the setting might get wiped and need to get reset on some future prefix upgrades.

**Comment by MrBigss** [comment]
Does Steam support "tricks" "per game".  
As in, can the launch environment be different for some games throught Steam itself, so it gets propagated to amy other users?

**Comment by alasky17** [comment]
@MrBigss I don't have a good general answer to that question.  In this specific case, the change is in the prefix, which should be used by all Steam users in one environment, but it will have to be set in every environment.  Hopefully that answers at least part of your question.
