### ISSUE TITLE
L.A. Noire

### ISSUE THREAD

**Issue by Clifhanger3** [ValveSoftware/Proton#5108]
I Hope I am reporting this in the correct place. Steam help sent me here....

L.A Noire does not work well with steam play.

-The menu's text is missing.
-Generic Controller Config is all wrong
-cut scenes are black, no video plays. However there is audio.

its above my head in how to help fix these issues sorry.

**Comment by kisak-valve** [comment]
Hello @Clifhanger3, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/544#issuecomment-903349590.
