### ISSUE TITLE
Red Dead Online possible vulkan regression

### ISSUE THREAD

**Issue by gtlsgamr** [ValveSoftware/Proton#5109]
# Compatibility Report
- Name of the game with compatibility issues: Red Dead Online
- Steam AppID of the game: 1404210

## System Information
- GPU: GTX 1660Ti MaxQ
- Driver/LLVM version: nvidia 470.63.01-3
- Kernel version: 5.13.10
- Link to full system information report as [Gist](https://gist.github.com/gtlsgamr/425a10a9aa617ee158d2a9613ecde0d9):
- Proton version: 6.3

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game worked fine before 20th August. I used proton version 6.3, My launch options were ```prime-run %command%``` and it all worked fine. On 21st I updated my system and it updated some packages, some of which I suspect are causing this behaviour, namely
```
[2021-08-21T15:52:12+0530] [ALPM] upgraded glib2 (2.68.3-1 -> 2.68.4-1)
[2021-08-21T15:52:12+0530] [ALPM] upgraded lib32-glib2 (2.68.3-1 -> 2.68.4-1)
[2021-08-21T15:52:12+0530] [ALPM] upgraded mesa (21.1.6-1 -> 21.2.1-1)
[2021-08-21T15:52:13+0530] [ALPM] upgraded lib32-mesa (21.1.6-1 -> 21.2.1-1)
[2021-08-21T15:52:13+0530] [ALPM] upgraded lib32-pam (1.5.1-1 -> 1.5.1-2)
[2021-08-21T15:52:13+0530] [ALPM] upgraded lib32-vulkan-radeon (21.1.6-1 -> 21.2.1-1)
```
This lead to the game giving ``` Error: Failed to initialize graphics device. Please reboot or reinstall latest graphics drivers.``` error everytime I try to start it with my dGPU. It start normally with my iGPU. This issue is persistent ONLY with this game. Other games seem to work fine as before.

## Reproduction
1. Start the game with ```prime-run %command%``` as launch option.

**Comment by kisak-valve** [comment]
Hello @gtlsgamr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4429#issuecomment-903868483.
