### ISSUE TITLE
Hearts of Iron IV - 394360

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#5110]
# Compatibility Report
- Name of the game with compatibility issues: Hearts of Iron IV
- Steam AppID of the game: 394360

## System Information
- GPU: Dedicated: GTX 1650Ti, Integrated: AMD Radeon Vega 7
- Driver/LLVM version: Nvidia 470.63.01
- Kernel version: 5.13.12-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Alphvino/d8a11d5fb7050a51908bada709ab9fa7
- Proton version: 6.3-6

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

## Symptoms 
When i run hearts of iron4 from the paradox launcher(i start it from steam then it loads the paradox launcher) it crashes while using the dedicated gpu. I use optimus-manager in hybrid mode and the only game that gives problems is hearts of iron 4. Every game i launch has these launch options:
prime-run %command% 
Every game works fine, only hearts of iron 4 seems to have problems. 
(I have my laptop(ideapadgaming 3 15arh05) connected to a hdmi screen)

## Reproduction
I open steam and then i start hearts of iron 4. At first it loads the paradox launcher and when i click start, the launcher disappears and then the paradox crash report shows.
PS: I can't get the proton log file, it doesnt even generate it

**Comment by kisak-valve** [comment]
Hello @Alphvino, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4130#issuecomment-904012583.
