### ISSUE TITLE
Skyrim SE no speach

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [ValveSoftware/Proton#5116]
# Compatibility Report
- Name of the game with compatibility issues: Skyrim Se
- Steam AppID of the game: 

[steam-489830.log](https://github.com/ValveSoftware/Proton/files/7046152/steam-489830.log)

## Symptoms 

Started game  all sounds persist but no speech
tried to use workaround :
1) WINEDLLOVERRIDES="xaudio2_7=n,b" %command% not - no success

## Reproduction

1) Enable russian 
2) start game 
3) no speach in dialogues

**Comment by kisak-valve** [comment]
Hello @jpVm5jYYRE1VIKL, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4#issuecomment-905487590.
