### ISSUE TITLE
Two gamepad connected, the wrong gamepad rumbles

### ISSUE THREAD

**Issue by kakra** [ValveSoftware/Proton#5117]
I've played Cyberpunk 2077 a few days ago and had both my gamepads attached:

* Xbox One S controller via USB cable (using the kernel xpad driver)
* Xbox Series X/S controller via Bluetooth BLE (using the xpadneo driver)
* Steam Input is disabled for the game

I was playing with the wireless gamepad from the couch when I noticed it doesn't rumble at all BUT the wired gamepad on my desk did rumble instead.

I did disconnect the wired gamepad but the wireless gamepad still would not rumble. It required a restart of the game to make it rumble properly.

Expected results: Either the gamepad I'm playing with should rumble, or none should rumble, because gamepads not held by any hand tend to rumble down the desk.

**Comment by ivyl** [comment]
This is a game's bug. CP2077 always rumbles the first controller (in the enumeration order) but accepts input from all the devices. It behaves the same way on Windows, I've just checked.

**Comment by kisak-valve** [comment]
Thanks for investigating @ivyl. Since this is game-specific feedback, and we're using one issue report per unofficially supported game title, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-905600761.
