### ISSUE TITLE
SCP: Secret Laboratory (700330)

### ISSUE THREAD

**Issue by Jordan-Jay** [ValveSoftware/Proton#5121]
# Compatibility Report
- Name of the game with compatibility issues: SCP: Secret Laboratory
- Steam AppID of the game: 700330

## System Information
- GPU: RTX 2080 Super
- Driver/LLVM version: Nvidia 470.63.01/LLVM 12.0.1
- Kernel version: 5.13.13-arch
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Jordan-Jay/3f1157c7c32cc4d23089668e4f7b2300
- Proton version: 6.15-GE-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 
[steam-700330.log](https://github.com/ValveSoftware/Proton/files/7070160/steam-700330.log)

## Symptoms  

The game does not launch

## Reproduction

1. Click play

**Comment by Jordan-Jay** [comment]
With Wine TKG 6.14 i get error c0000026 after launch
[steam-700330.log](https://github.com/ValveSoftware/Proton/files/7070197/steam-700330.log)

**Comment by Jordan-Jay** [comment]
With 4.2-9 and 4.11-13 i get into the beginning loading screen of the game but receive the unity crash handler.
[steam-700330.log](https://github.com/ValveSoftware/Proton/files/7070231/steam-700330.log)

**Comment by kisak-valve** [comment]
Hello @Jordan-Jay, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4229#issuecomment-907618319.
