### ISSUE TITLE
Phasmophobia (739630)

### ISSUE THREAD

**Issue by tr1ckyv2** [ValveSoftware/Proton#5122]
# Compatibility Report
- Name of the game with compatibility issues: Phasmophobia
- Steam AppID of the game: 739630

## System Information
- GPU: GTX 750 Ti
- Driver/LLVM version: Nvidia 470.63.01/LLVM 12.0.1
- Kernel version: 5.13.13-zen1-1-zen
- Link to full system information report as : https://gist.github.com/tr1ckyv2/bd0870d84dece1da0d386a6efae37fd3
- Proton version: 6.3-6

## I confirm:
- [✓] that I haven't found an existing compatibility report for this game.
- [✓] that I have checked whether there are updates for my system available.

[steam-739630.log](https://github.com/ValveSoftware/Proton/files/7070575/steam-739630.log)

## Symptoms 
FPS is VERY low compared to windows, always under than 30 fps and sometimes 8-2 fps
example: i get always higher than 60 fps on windows.

current distro: Endeavour OS (arch linux distro)

## Reproduction
FPS

**Comment by kisak-valve** [comment]
Hello @tr1ckyv2, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4295#issuecomment-907619442.
