### ISSUE TITLE
An annoying graphical bug in Grand Theft Auto V via steamplay

### ISSUE THREAD

**Issue by edvejak** [ValveSoftware/Proton#5123]
Name of the game with compatibility issues: Grand Theft Auto V
    Steam AppID of the game: 271590

## System Information
- GPU: NVIDIA GeForce GTX 660/PCIe/SSE2
- Driver/LLVM version: NVIDIA 470.63.01
- Kernel version: 5.4.0-81-generic
https://gist.github.com/edvejak/6c24919d49bdfaa5bed0eb13fba92350
- Proton version: 6.3.6

## I confirm:
that I haven't found an existing compatibility report for this game.
that I have checked whether there are updates for my system available.

## Symptoms 
An annoying graphical bug in gta 5 appears immediately at the beginning of the game
## Reproduction
Launch GTA V via steamplay
![Снимок экрана от 2021-08-28 22-04-51](https://user-images.githubusercontent.com/81964247/131218721-97f3930e-5664-4acf-baeb-93c1f0008eb8.png)

**Comment by kisak-valve** [comment]
Hello @edvejak, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-907627410.

**Comment by edvejak** [comment]
ok
