### ISSUE TITLE
Dead Rising issues

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#5127]
# Compatibility Report
- Name of the game with compatibility issues: Dead Rising
- Steam AppID of the game: 427190

## System Information
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/coreybruce/dcd2bec911594c9212d351ac2e7a3f98
- Proton version: 6.3-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

Proton Log: https://gist.github.com/coreybruce/fe8403b881ce4550601d98268750b258

## Symptoms 
-Game will infinitely load once you start a new game
-Game will go black screen if you alt tab or minimise game

## Reproduction
run game using latest proton and start new game also try and minimise or alt tab from the game.

**Comment by kisak-valve** [comment]
Hello @coreybruce, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1969#issuecomment-908314766.
