### ISSUE TITLE
Primordia (#227000) - Please remove the whitelist.

### ISSUE THREAD

**Issue by Dualnames1** [ValveSoftware/Proton#5128]
Hello, James Spanos, developer of Primordia here, please do remove the whitelist.
It was requested by a non-dev, and now that we've uploaded a proper native version, it's creating all sorts of problems.
I've opened up a post here, https://steamcommunity.com/groups/steamworks/discussions/0/3032599335599121285/
that explains the problem with the whitelist.

**Comment by Leopard1907** [comment]
https://steamdb.info/app/891390/history/?changeid=12431645

According to this change it is no longer in the whitelist.

To be clear, whitelist is not a thing anymore for any game.

**Comment by kisak-valve** [comment]
Closing per the last comment.
