### ISSUE TITLE
Sekiro: Shadows Die Twice has the screen blinking when I click 'play'

### ISSUE THREAD

**Issue by johnlennon1991** [ValveSoftware/Proton#5129]
Sekiro: Shadows Die Twice has the screen blinking when I click 'play' and doesn't start.
Proton Version: 5.13-6
OS: Linux Mint Cinnamon
CPU: AMD, Ryzen 3, Vega 8

**Comment by kisak-valve** [comment]
Hello @johnlennon1991, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2444#issuecomment-908531182.
