### ISSUE TITLE
Game crashes on start when trying to run under Steam Play

### ISSUE THREAD

**Issue by johnfisherman** [ValveSoftware/Proton#5131]
# Compatibility Report
- Name of the game with compatibility issues: The Secret of Monkey Island Special Edition
- Steam app ID: 32360

## System Information
- GPU: GeForce GTX 560 Ti (GPU 0)
- Driver/LLVM version: nvidia 390.144
- Kernel version: 5.11.0-27-generic
- Link to full system information report as [Gist](https://gist.github.com/johnfisherman/7c6d747142f5eff232a8c0c0927d783c)
- Proton version: 6.3-6

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
I'm on Elementary OS 6 Odin. The game crashes on startup, briefly showing a blank window. I tried all different versions of Proton, and have 

`PROTON_USE_WINED3D=1 PROTON_LOG=1 %command%`

As launch options.

Also, I installed Steam from the official .deb, not from the Flatpak.

I also tried adding 

```
shift 2
exec "${@}"
```

`to <steam-library>/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point`

as recommended by the kind people on the Proton discord server.

## Reproduction
Enable Steam Play, choose Proton version and Launch the game. Crashes.

[steam-32360.log](https://github.com/ValveSoftware/Proton/files/7086503/steam-32360.log)

**Comment by kisak-valve** [comment]
Hello @johnfisherman, we're using one issue per unofficially supported game title, and usually I'd transfer this issue report to #939, but in your case it's fairly clear that there are some major issues.

First and most significant, while the nVidia 390 video driver series is the newest to support your generation of video card, it is also [older than the support cutoff](https://github.com/ValveSoftware/Proton/wiki/Requirements#nvidia) for Proton. Also, any driver for your video card generation does not support Vulkan, which makes your system unsupported by Proton.

Your system information ends with `CClientJobGatherRuntimeInformation: container read output failed` which tells us something's going wrong with the Steam Linux Runtime - Soldier container environment. Proton 5.13 and newer is run inside the Steam Linux Runtime - Soldier container environment. There's an additional known complication with the nVidia 390 series video driver interacting with that container environment which is being tracked at https://github.com/ValveSoftware/steam-runtime/issues/420. Running Proton 5.13 and newer outside the container environment is not supported and you've most likely encountered that issue.

The suggestion to use `PROTON_USE_WINED3D=1` to tell Proton to use wine's DirectX to OpenGL render path was a good recommendation for your system, but that launch option is also unsupported and comes with a significant performance penalty. You might get lucky using that with Proton 5.0 and older, then give #939 a read for additional known quirks with that game.

Sorry, but your system is unsupportable overall. Closing.
