### ISSUE TITLE
No Man's Sky (275850) Crashes etc. at random points

### ISSUE THREAD

**Issue by Srogozins** [ValveSoftware/Proton#5133]
# Compatibility Report
- Name of the game with compatibility issues: No Man's Sky
- Steam AppID of the game: 275850

## System Information
- GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 
- Driver/LLVM version:   4.6 (Compatibility Profile) Mesa 21.1.4
- Kernel version: 5.12.12
- Link to full system information report as [Gist](https://gist.github.com/):  https://gist.github.com/Srogozins/61515238c382e3edc3f82f13533a212b 
[steam-275850.log](https://github.com/ValveSoftware/Proton/files/7094920/steam-275850.log)
[dmesg.log](https://github.com/ValveSoftware/Proton/files/7094921/dmesg.log)
https://gist.github.com/Srogozins/5d7485fec382b77a5551e5bc77c85b3b 
- Proton version: 5.0-10

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 

After some in-game, ranging from a few minutes to hours the game would often freeze, with visual artifacts appearing on the screen in and out of game/crash/crash the X-server/freeze the system to the point of needing to kill the X-server/cause the computer to reboot. Seems to occur during any sort of activity.

## Reproduction

Play the game for a few hours.

**Comment by kisak-valve** [comment]
Hello @Srogozins, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-910865979.
