### ISSUE TITLE
Disabling VSync causes system crash/freeze!

### ISSUE THREAD

**Issue by Rabcor** [ValveSoftware/Proton#5136]
I've experienced this issue in two games (No Man's Sky and Subnautica).

If I disable VSync while running a game on proton, it will cause linux to crash/freeze (I have not tested this with a large amount of games, nor do I feel any desire to, force-poweroffing a PC too often is a recipe for breaking it after all).

## Symptoms 
The crash was the same in both games tested, when VSync is disabled:

- Sound continues playing as normal.
- Image on the screen freezes
- Keyboard stops responding (notably also things like toggling caps lock which is supposed to turn a LED on and off does not affect the corresponding LED, if it was on when the crash happens, it stays on till forced reboot. If it was off, ditto), this includes common combinations like alt+tab, alt+f4 or even ctrl+alt+f1-7 (changing console, which should always work on a linux system)

## Reproduction
In the two games I mentioned this is 100% reproducible for me, if I disable VSync in subnautica, it will crash within 1 minute of turning it on (whether in main-menu or not), usually in around the 30 second range.

If I disable VSync in no mans sky, it crashes within 5 seconds, practically instant, if I turn the game on  with VSync off, it will crash on the cutscene right at the start before I even make it to the main menu.

The issue is not present in Wine (I played Subnautica with regular Wine (With DXVK) for long periods of time without vsync and without issue, this issue is proton specific.)

Have not tested this with many versions of proton, just the experimental branch, 6.3-6, 4.11-13 and I believe I also tested it on 5.13-6.

Result was the same on all tested versions of proton..

## System Information
[Gist for steam's detected system information](https://gist.github.com/Rabcor/295ce7e92510cf9898af29d7816532d8) (some values were not detected or incorrect, I added in some notes on how this could be easily resolved if anyone's interested in that...)

## Logfile
[Proton Log for No Man's Sky](https://gist.github.com/Rabcor/e0ee502b544669429b3199369db2e1a7)

(The logfile is for a case where I turned the game on with vsync on, loaded a save, then turned vsync off and crashed about 10 seconds later as described in the symptoms)

**Comment by kisak-valve** [comment]
Hello @Rabcor, this reads like a kernel or hardware issue.

Can you check your system logs for a dying message from the kernel when it froze? If this was my system, I'd look at setting up netconsole so that the kernel has the chance to send a dying message to another system on the network.

**Comment by Rabcor** [comment]
Well, I would be doing that too if I even knew what to look for or how to look for it. The extent of my knowledge is "dmesg has some stuff" and "journalctl has some stuff" and that I can use grep to probe their outputs for errors. 😅 

I can figure out how to configure the kernel to use netconsole just fine, but how do I parse the output? What am I looking for? (Evevn just vaguely? Just errors?) Which file will I find it in?

**Comment by Rabcor** [comment]
I just encountered the same issue on a native game, so this is not a proton issue, closing.
