### ISSUE TITLE
All Proton games stopped working after crash

### ISSUE THREAD

**Issue by tukkek** [ValveSoftware/Proton#5144]
I was playing Grim Dawn today and at one point the game crashed. After that, no other Proton title will launch - I have not added, removed or changed any system packages, Steam games or permissions between the games working, the crash and them stopping working for good. I have also been playing Proton games with my current system setup for weeks and now nothing works anymore.

I can still launch native games and play them fine (from within or without Steam). I cannot launch any Proton games. I cannot generate logs for any Proton games.

I have since reinstalled the Proton games, Proton itself, changed Proton versions and nothing helped.

I have a dual-user setup, with two users sharing the same Steam library, both on the same user group and I have a script that I run when I run into trouble to make sure every file under the Steam install directory (where the Steam library is located) is owned by the main user and has the correct group read-and-write access. 

I have never run into any trouble before that couldn't be fixed by making sure permissions are correct. Now with even a full reinstall of the games and Proton, the games aren't working.

**Comment by tukkek** [comment]
(Pressed Control+Enter by mistake, which submitted the report. Continuing....)

Please advise on how I can provide more information or figure out what the problem is, since I cannot generate logs with `PROTON_LOG=1 %command%`.

I had been running Grim Dawn and Dawn of War: Dark Crusade flawlessly on Linux for quite a while before this problem happened today. Again I haven't made any changes to system or Steam between the games working flawlessly every time I launched them and now they not being able to run at all (when I press Play it shows the game running for a couple seconds then goes back to Play for both games).

Thanks to all for the great work on Proton. It's very nice to be able to run these games on my Linux system.

**Comment by tukkek** [comment]
After the crash I immediately tried to run the game again and it wouldn't launch, nor would any other Proton title I have. I am reinforcing this fact because I believe this rules out any system or permission issues, despite the fact that I have a dual-user, one-library setup. Proton was working flawlessly from one moment then completely broken the next (after the crash),  and will not run any games anymore, while nothing else of note was running in the background as I was simply gaming before the crash occurred.

**Comment by tukkek** [comment]
I was using Proton Experimental when the crash occurred. Reinstalling it and trying old versions of Proton doesn't fix the problem.

**Comment by tukkek** [comment]
Restarting Steam or doing a hard-restart of the machine also doesn't help.

**Comment by tsilvs** [comment]
Having similar issue on Pop!_OS 20.04 (updated 2021-09-06) with "Divinity: Original Sin 2 - Definitive Edition"

# Issue 1
Game doesn't launch with an error:

`[0906/194936.817120:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.`

After the Larian Launcher starts, I click on "Play" in it, and then I only hear a Larian logo intro and see a black screen. Then game crashes.

# Issue 2
Another error message I was receiving in terminal is this:

`wine: RLIMIT_NICE is <= 20, unable to use setpriority safely`

I tried to fix this issue by launching my Steam client like so:

`nice -n 20 flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam-wrapper --file-forwarding com.valvesoftware.Steam`

So far it seems that this particular sub-issue is solved, but the main one persists.

# My setup
## System configuration
```
$ neofetch
OS: Pop!_OS 20.04 LTS x86_64
Kernel: 5.11.0-7633-generic
Shell: bash 5.0.17
Resolution: 1920x1080, 1280x1024
DE: GNOME
WM: Mutter
Terminal: gnome-terminal
CPU: Intel i7-6700HQ (8) @ 3.500GHz
GPU: NVIDIA GeForce GTX 960M
```

Games installed at external drive in additional SteamLibrary. All (rwx) permissions granted.

## OS updates
```
$ cat /var/log/apt/history.log

Start-Date: 2021-09-05 17:42:56
Commandline: packagekit role='update-packages'
Requested-By: tanhok (1000)
Upgrade: ntfs-3g:amd64 (1:2017.3.23AR.3-3ubuntu1, 1:2017.3.23AR.3-3ubuntu1.1), libntfs-3g883:amd64 (1:2017.3.23AR.3-3ubuntu1, 1:2017.3.23AR.3-3ubuntu1.1), pop-launcher:amd64 (1.0.0~1630341338~20.04~777fe78, 1.0.0~1630370024~20.04~8b7c835), thermald:amd64 (1.9.1-1ubuntu0.4, 1.9.1-1ubuntu0.5)
End-Date: 2021-09-05 17:43:29
```

## GPU Driver
```
$ nvidia-smi
(some info omitted)
Mon Sep 6 21:38:38 2021
NVIDIA-SMI 470.57.02 Driver Version: 470.57.02 CUDA Version: 11.4
```

## Steam Client
* running using eGPU (Nvidia GeForce GTX 960M)
* installed via flatpak:
```
$ flatpak info com.valvesoftware.Steam

Steam - Manage and play games distributed by Steam

ID: com.valvesoftware.Steam
Ref: app/com.valvesoftware.Steam/x86_64/stable
Arch: x86_64
Branch: stable
Version: 1.0.0.70
License: LicenseRef-proprietary
Origin: flathub
Collection: org.flathub.Stable
Installation: user
Installed: 41.1 MB
Runtime: org.freedesktop.Platform/x86_64/20.08
Sdk: org.freedesktop.Sdk/x86_64/20.08

Commit: b5bc849bc8e5b8ac924a2538a71b342b929d7ca3f1d53e2f2de57e6dea9753ea
Parent: 59ca423d1b9ecd3d6b819c63b070c7ce1c31362b0107cd7287b0005a97d51c4e
Subject: Drop network manager permission This seems to be really wide and if system policies are not set properly, it might allow access to eg WiFi passwords (af6f1609)
Date: 2021-06-20 10:22:15 +0000
```

## Proton
Game launched via compatibility tool: Steam Play

Using Proton Flatpak Community build (com.valvesoftware.Steam.CompatibilityTool.Proton) version 6.3-6b

```
$ flatpak info com.valvesoftware.Steam.CompatibilityTool.Proton

Proton (community build) - Latest Proton version built on the Flatpak
Freedesktop SDK

ID: com.valvesoftware.Steam.CompatibilityTool.Proton
Ref: runtime/com.valvesoftware.Steam.CompatibilityTool.Proton/x86_64/stable
Arch: x86_64
Branch: stable
Version: 6.3-6b
License: BSD-3-Clause and LGPL-2.1 and zlib-acknowledgement and Zlib and OFL-1.1 and MIT and MPL-2.0 and LicenseRef-proprietary
Origin: flathub
Collection: org.flathub.Stable
Installation: user
Installed: 1.3 GB

Commit: e48892a3c6aff7ce23220d6fcbe413896e8da9cbe92d8107a36137ddaf211dc7
Parent: 77ea42993a37668456c5a88bc238711785632eac13e62871b69c9d8a82214ee4
Subject: Update wine-mono to 6.3.0 (5cd6e777)
Date: 2021-08-21 16:35:00 +0000
```

**Comment by tukkek** [comment]
I have fixed the issue by going as far back as Proton 5.0. No newer releases, including Experimenal can launch games.

**Comment by ghost** [comment]
> I have fixed the issue by going as far back as Proton 5.0. No newer releases, including Experimenal can launch games.

Common denominator here is steam Linux runtime soldier, fwiw

**Comment by kisak-valve** [comment]
Hello @Ammako, while that's true for the Steam-distributed Proton 5.13 and newer, the mentioned com.valvesoftware.Steam.CompatibilityTool.Proton build of Proton isn't part of that system and specifically rebuilt to run in the Flatpak'd environment. As far as I know, that specific variant of Proton does not use Steam Linux Runtime - Soldier.

**Comment by ghost** [comment]
@kisak-valve different person, OP doesn't mention flatpak

**Comment by kisak-valve** [comment]
Fair point. @tukkek, can you gather the information requested at https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information and generally check that Steam Linux Runtime - Soldier is healthy?

**Comment by jtrees** [comment]
I am also experiencing this issue. Since the big client update, none of my Steam Proton games work any more.

Update: https://github.com/ValveSoftware/Proton/issues/4069#issuecomment-917682317

**Comment by tukkek** [comment]
> generally check that Steam Linux Runtime - Soldier is healthy?

I'll see about posting the information soon. In specific, by healthy do you just mean running a validation check on the item listed in my Library?

Glad to see you're on the issue now kisak! Thanks for your time and Valve's excellent work on Proton.

**Comment by tukkek** [comment]
Also, before I post anything else, what is the most sure-fire way of doing a proper reset on all my Proton-related installs? **After** everything stopped working I did try clearing and hacking a bunch of stuff and while I hope that I have everything back in order, I wouldn't feel very comfortable doing more testing in my setup if I have further compromised it manually in some way.

I have, for example, uninstalled and reinstalled all my Proton versions and games and the issue persists. Would that be enough to make sure I'm working on a "factory-default" environment again? Would a full reinstall of Steam and games/tools accomplish this goal?
