### ISSUE TITLE
Death stranding stuck at 99%

### ISSUE THREAD

**Issue by ornelasnarciso** [ValveSoftware/Proton#5148]
I'm using Proton Experimental (the only version in which the game launches).

I start a new game and it gets stuck at 99%. 

Any fix for this?

**Comment by kisak-valve** [comment]
Hello @ornelasnarciso, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4069#issuecomment-916280672.

**Comment by ornelasnarciso** [comment]
I've seen that trend. There's no fix for this. 

I'll try to run the game in the future when a new version of proton comes out. 

Thanks.

**Comment by TheDiscordian** [comment]
@ornelasnarciso FWIW for me on a new game, even on an NVME SSD I need to wait a very very long time for load, it'll just sit at 99% for a while. I recommend having absolutely nothing running except Steam + Death Stranding, and leave it alone for up to 30mins. It shouldn't be frozen, just taking it's sweet time.
