### ISSUE TITLE
Far Cry 4 launches from UPlay then immediately crashes

### ISSUE THREAD

**Issue by ChaosBlades** [ValveSoftware/Proton#5149]
# Compatibility Report
- Name of the game with compatibility issues: Far Cry 4
- Steam AppID of the game: 298110

## System Information
- GPU: 6900XT
- Driver/LLVM version: Mesa 21.0.1
- Kernel version: 5.13.15-xanmod1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ChaosBlades/afc2f85876c2427f6a86c7832273c1a4
- Proton version: Any

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

[steam-298110.log](https://github.com/ValveSoftware/Proton/files/7143321/steam-298110.log)

## Symptoms 
Uplay launches the game then it immediately closes.
I see in the proton logs an error for...
[0828/085556.679:ERROR:dxva_video_decode_accelerator_win.cc(1440)] DXVAVDA fatal error: could not LoadLibrary: msmpeg2vdec.dll: Module not found. (0x7E)\n
... I tried to download that dll from the internet and put it in system32 but that did not seem to help

## Reproduction
I have tried a completely stock fresh install of Pop OS.
Up to date modded xanmod kernel
Proton GE
Adding mesa and wine repo
All versions of Proton available in Steam
This is the only game I have tried that does not work. Other UPlay games work without issue
I have Far Cry 4 Gold edition with all the DLC if that matters.

**Comment by kisak-valve** [comment]
Hello @ChaosBlades, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2143#issuecomment-916891915.
