### ISSUE TITLE
Fallout New Vegas (22380)

### ISSUE THREAD

**Issue by Budgieplucker** [ValveSoftware/Proton#5152]
# Compatibility Report
- Name of the game with compatibility issues: Fallout New Vegas
[steam-22380.log](https://github.com/ValveSoftware/Proton/files/7148953/steam-22380.log)

- Steam AppID of the game: 22380

## System Information
- GPU: 
- Driver/LLVM version: 
- nvidia 470.63.01
- Kernel version: 
- 5.14.2-zen1-2-zen
- Link to full system information report as [Gist](https://gist.github.com/):
- https://gist.github.com/Budgieplucker/629053c50301a17a4990afcc6058d649
- Proton version: All versions

## I confirm:
- [ yes ] that I haven't found an existing compatibility report for this game.
- [ yes ] that I have checked whether there are updates for my system available.

## Symptoms 
Launching the game via the steam client, just opens the game launcher. The launcher itself, does not allow you to launch the game, only showing an install button, which when clicked, states that the game does not appear to be installed and to check the CD-ROM.

## Reproduction
Launch the game through the steam client and press the "install" button.

**Comment by kisak-valve** [comment]
Hello @Budgieplucker, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/356#issuecomment-917627680.
