### ISSUE TITLE
Cruelty Squad (1388770)

### ISSUE THREAD

**Issue by addrmicro** [ValveSoftware/Proton#5153]
# Compatibility Report
- Name of the game with compatibility issues: Cruelty Squad
- Steam AppID of the game:  1388770
## System Information
- GPU: Radeon Vega 8 Mobile Series (Raven Ridge)
- Driver/LLVM version: mesa 21.2.1
- Kernel version: 5.10.61
- Link to full system information report as: [Gist](https://gist.github.com/addrmicro/de869043f264c6b97235102a3fcfaf63)
- Proton version: 6.3-6

## I confirm:
- [Y] that I haven't found an existing compatibility report for this game.
- [Y] that I have checked whether there are updates for my system available.

[steam-1388770.log](https://github.com/ValveSoftware/Proton/files/7149002/steam-1388770.log)

## Symptoms 
When launching the main splash screen appears but after a few seconds the game
crashes.

This is different from a similar issue mentioned on the discussion forums where empty save files are stored
in `Users\USERNAME\AppData\Roaming\Godot` **In this case the Godot directory doesn't exist.**

After checking debug logs the game states errors in internal directory creation functions
`ERROR: DirAccess::make_dir_recursive: Method failed. Returning: err
   At: core\os\dir_access.cpp:184
ERROR: OS::ensure_user_data_dir: Condition "err != OK" is true.
   At: core\os\os.cpp:478
ERROR: DirAccess::make_dir_recursive: Method failed. Returning: err
   At: core\os\dir_access.cpp:184`
and 
`ERROR: _File::store_line: Condition "!f" is true.
   At: core\bind\core_bind.cpp:2256
ERROR: _File::store_line: Condition "!f" is true.
   At: core\bind\core_bind.cpp:2256
ERROR: _File::get_len: Condition "!f" is true. Returned: 0
   At: core\bind\core_bind.cpp:2054
ERROR: _File::store_line: Condition "!f" is true.
   At: core\bind\core_bind.cpp:2256
ERROR: _File::get_line: Condition "!f" is true. Returned: String()
   At: core\bind\core_bind.cpp:2157
ERROR: GDScriptFunctions::call: Error parsing JSON at line 0:
   At: modules\gdscript\gdscript_functions.cpp:1268`

Checking reports on ProtonDB indicates that the issue is rare but isn't common to any system configuration.

## Reproduction

1. Enable Steam Play on Steam runtime client
2. Set any proton version for appid 1388770
3. Launch game

Issue can be reproduced on vanilla wine-6.0.1

**Comment by addrmicro** [comment]
Game now works in Proton-experimental

**Comment by wantija** [comment]
Game is crashing at launch for me, tried with proton 7, 8 and experimental. Kernel 6.4.1 linux-zen, mesa-git, RX 6800XT, R7 5800X, Arch Linux.
[steam-976730.tar.gz](https://github.com/ValveSoftware/Proton/files/11938385/steam-976730.tar.gz)
