### ISSUE TITLE
Sonic & All-Stars Racing Transformed Collection stopped working.

### ISSUE THREAD

**Issue by RuthlessSlayer820** [ValveSoftware/Proton#5155]
Game was working fine until today, and all games on the Sumo Engine seem borked all of a sudden. It also seems to completely corrupt some files, pretty weird.

[steam-212480.log](https://github.com/ValveSoftware/Proton/files/7157644/steam-212480.log)

**Comment by kisak-valve** [comment]
Hello @RuthlessSlayer820, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/426#issuecomment-918651378.
