### ISSUE TITLE
DELTARUNE (CHAPTER 1 & 2 DEMO) (1690940)

### ISSUE THREAD

**Issue by CuriousTommy** [ValveSoftware/Proton#5162]
# Compatibility Report
- Name of the game with compatibility issues: DELTARUNE (CHAPTER 1 & 2 DEMO)
- Steam AppID of the game: 1690940

## System Information
- GPU: GeForce GTX 1060 6GB
- Driver/LLVM version: NVIDIA 470.63.01
- Kernel version: 5.13.16-200.fc34.x86_64
- Link to full system information report: [steam_system_info_desktop_workstation.txt ](https://gist.github.com/CuriousTommy/bdbfb367871864001e546d8ec88f738e)
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

One out of the four arrow keys will work. Which arrow key works depends on where you are.

## Reproduction

[steam-1690940_chapter_one_prompt_down_press_works_only.log](https://github.com/ValveSoftware/Proton/files/7188899/steam-1690940_chapter_one_prompt_down_press_works_only.log)

![image](https://user-images.githubusercontent.com/3105794/133865596-77bf981b-176c-44e9-8c3d-09752e9a663a.png)

1. Open demo
2. Press down
3. Now try to press up

---

[steam-1690940_chapter_one_character_selection_screen_left_press_works_only.log](https://github.com/ValveSoftware/Proton/files/7188906/steam-1690940_chapter_one_character_selection_screen_left_press_works_only.log)
![image](https://user-images.githubusercontent.com/3105794/133865985-eb6e038e-c3f5-4200-a384-66f5c376a0d5.png)

1. Open demo
2. Press enter
3. Press left
4. Now try to press right

**Comment by kisak-valve** [comment]
Hello @CuriousTommy, in your log this looks curious:
```
***** Event = gamepad discovered
***** GAMEPAD DESCRIPTION: = ASRock LED Controller
```
Hypothetically, if the game's trying to get controller input from that first, it could be causing your snafu.

Maybe try blacklisting that device with something similar to the discussion at https://bbs.archlinux.org/viewtopic.php?id=261161.

**Comment by CuriousTommy** [comment]
Thanks @kisak-valve! That was indeed the issue.

Sorry for the spam. I'll close this ticket.
