### ISSUE TITLE
How to get logs from Proton/Games

### ISSUE THREAD

**Issue by danielw1990** [ValveSoftware/Proton#5167]
Proton does not write any logs to my home folder. So i tried explicitly adding a path to the "user_settings.py".

Still nothing.

How do i enable logging or display a visible terminal from a Proton launch?

The game in question usually runs flawless if it starts, but starting has random failstates i want to analyze. Because the current process is:
"Just hit stop and start in steam until it starts."

So i assume if i can figure out what it tries to do when it doesn't work i can fix the problem.

**Comment by kisak-valve** [comment]
Hello @danielw1990, this is documented at https://github.com/ValveSoftware/Proton#runtime-config-options. Proton's logging is off by default for performance reasons, and you can enable it by adding `PROTON_LOG=1 %command%` to the game's launch options. This should write the log to `${HOME}/steam-<appid>.log` by default, or the log folder if you set that env variable.
