### ISSUE TITLE
[Might and Magic HerosVII] Unable to locale Uplay PC.

### ISSUE THREAD

**Issue by damon-kwok** [ValveSoftware/Proton#5170]
Might and Magic Heros VII: Unable to locale Uplay PC. Please reinstall Uplay PC.
OS: Linux (Manjaro)
Kernel: 5.13.15

``` sh
# uname -a
Linux damon-manjaro 5.13.15-1-MANJARO #1 SMP PREEMPT Wed Sep 8 14:12:50 UTC 2021 x86_64 GNU/Linux

```

---

![Screenshot from 2021-09-20 19-25-05](https://user-images.githubusercontent.com/1702133/133995024-a16488ba-0a8c-49d6-b014-df48f155d986.png)

**Comment by kisak-valve** [comment]
Hello @damon-kwok, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3005#issuecomment-922912268.
