### ISSUE TITLE
BUG: Keyboard non-functional if game launched with a non-english keyboard layout 

### ISSUE THREAD

**Issue by arseniiarsenii** [ValveSoftware/Proton#5172]
I am using Proton v. 6.3-6 to launch Enter The Gungeon.

I have two keyboard layouts: Russian and English. If the game is launched with English layout selected all the keys are functional (WASDEQ etc.). However, if Russian keyboard layout is set prior to launching the game, keys are not recognized and pressing any of them does nothing as no input is recognized by the game. I have tried switching to Proton version Experimental in the settings, but this didn't resolve the issue.

My configuration:
Operating System: EndeavourOS
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.14.6-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800H with Radeon Graphics
Memory: 13.5 GB of RAM
Graphics Processor: AMD RENOIR

**Comment by kisak-valve** [comment]
Hello @arseniiarsenii, this issue is already being tracked at #3783. Closing in favor of the older issue report.
