### ISSUE TITLE
World War Z: Aftermath (699130)

### ISSUE THREAD

**Issue by alexcrow89** [ValveSoftware/Proton#5174]
# Compatibility Report
- Name of the game with compatibility issues: World War Z: Aftermath
- Steam AppID of the game: 699130

## System Information
- GPU: Nvidia GTX 1080Ti
- Driver/LLVM version: Nvidia 460.91.03
- Kernel version: 5.10.0-8-amd64
- Link to full system information report as [Gist](https://gist.github.com/alexcrow89/2150e323377e15401b5d82c103c82250):
- Proton version: Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-699130.log](https://github.com/ValveSoftware/Proton/files/7212129/steam-699130.log)

## Symptoms
After running the game (seemingly successfully) on my initial try, rather than immediately playing the game I went into the options menu, changing the game's renderer from DX11 to Vulkan. I also enabled AMD's FSR technology, just to see if it would work. I was prompted to restart the game. Upon doing so, the game no-longer reaches the main menu, rather crashing on the initial loading screen with a zombie's face.

## Reproduction
This crash happens at the same spot, every time I've tried re-running the game, without fail. I've uninstalled, re-installed, deleted "WWZ"-related directories, etc. The game still crashes at the initial loading screen with a zombie's face.

**Comment by alexcrow89** [comment]
Hello everyone. Want to report that after the game's latest update (on the 23rd), the game seems to run perfectly fine now. Going to close this issue. Thanks for everyone's help.

**Comment by intrigus-lgtm** [comment]
Running `winetricks -q mfc140` in my wine prefix helped me when running WWZ via Epic Games Store via Lutris.
Using wine version `lutris-6.0-rc1-x86_64`.

Before doing that I always got a "Crashreporter window" (on start) that asked me to send a crash report.

**Comment by intrigus** [comment]
Running winetricks -q mfc140 in my wine prefix helped me when running WWZ via Epic Games Store via Lutris.
Using wine version lutris-6.0-rc1-x86_64.

Before doing that I always got a "Crashreporter window" (on start) that asked me to send a crash report.

**Comment by FerLuisxd** [comment]
Vulkan backend seems broken on the steam deck.

**Comment by kisak-valve** [comment]
Hello @FerLuisxd, since the reporting user has chosen to close this compatibility report and there are no other reports for this game title, please open a new compatibility report with the details of your experience.
