### ISSUE TITLE
Space Engineers Needs DotNet Update 4.6.1

### ISSUE THREAD

**Issue by TheFloatingBrain** [ValveSoftware/Proton#5175]
# Compatibility Report
- Name of the game with compatibility issues: Space Engineers
- Steam AppID of the game: 244850

## System Information
- GPU: NVIDIA GeForce GTX 960M
- Driver/LLVM version: nvidia-driver-470
- Kernel version: Linux 5.13.0-7614-generic
- Link to full system information report as [Gist](https://gist.github.com/TheFloatingBrain/96124f9cf1544f1e6808c3d3bdad857e)
- Proton version: Experimental (also tried: 6.3, 5.13, 5.0, 4.11)
- [Proton Log](https://gist.github.com/TheFloatingBrain/79f717899663052f28fedc89eb2f4cf1)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game launches, but it tells me I need to download a [hotfix from here](https://support.microsoft.com/en-us/topic/hotfix-rollup-3120241-for-the-net-framework-4-6-and-4-6-1-on-windows-0941be9f-e587-2c77-6fe0-1af95ac3f4ac)

The download is not even available. I tried installing most of the DotNet runtimes available through winetricks, but it did not make a difference, I was told enabling a "virtual desktop" on WINE might help, but it did nothing. 

The game appears to exit gracefully, once you press the "Ok" button to the message stating that you need the hotfix, it quits and opens a browser window with the linked hotfix above.

## Reproduction

- Install Pop OS (with NVIDIA Driver)
- Apply system updates
- Install Steam
- Install Proton
- Install Space Engineers
- Attempt to run Space Engineers

**Comment by kisak-valve** [comment]
Hello @TheFloatingBrain, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1792#issuecomment-925103738.

**Comment by TheFloatingBrain** [comment]
> Hello @TheFloatingBrain, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#1792 (comment)](https://github.com/ValveSoftware/Proton/issues/1792#issuecomment-925103738).

Okay, sorry, saw the issue was old, didn't think it was still relevant. Thanks for the speedy reply!
