### ISSUE TITLE
Proton 6.3-7 RC testing

### ISSUE THREAD

**Issue by ivyl** [ValveSoftware/Proton#5179]
Hey. We've put together a new 6.3 Release Candidate build for you to test.

In the Steam client, the Proton 6.3 app should have a "proton-6.3-7-rc" beta
branch which you can choose to start testing the 6.3-7 Release Candidates (note
that the name of the build in the Steam Settings dialog will not be updated). I
will post changes here when we push new builds. The source for the latest RC
build is available on the proton_6.3-rc branch in this repositories. This branch
may be force pushed.

In this issue, we are interested only in problems that are new to the 6.3-7 RC
builds. If you find new problems in the release candidate branch, please confirm
that the problem does not occur in on the "none" branch before reporting it
here.

Here is the tentative changelog. As always, this changelog has not yet been
verified by our QA staff, and can change before the final release as we add or
remove features during RC testing.

 * The following games are now playable:
   - Life is Strange: True Colors
   - Quake Champions (broken after a game update)
   - Divinity Original Sin 2 (broken after a game update)
   - eFootball PES 2021
   - EVERSLAUGHT VR
   - WRC 8, 9 and 10
 * Fix Logitech G920 mapping for F1 2020.
 * Fix Resident Evil Village display settings.
 * Improve Forza Horizon 4 windowing.
 * Update DXVK to v1.9.2.
 * Update vkd3d-proton to include the latest development work.

**Comment by ivyl** [comment]
RC3 is up. We had to revert a few changes (Industries of Titans monitor and resolution selection fix and wine-mono bump) due to regressions found during testing.

**Comment by zaps166** [comment]
Please look at issue: https://github.com/doitsujin/dxvk/issues/2300 introduced in DXVK 1.9.2

**Comment by ivyl** [comment]
> Please look at issue: [doitsujin/dxvk#2300](https://github.com/doitsujin/dxvk/issues/2300) introduced in DXVK 1.9.2

RC4 is up with the revert included. Thanks for pointing this out :-)

**Comment by ivyl** [comment]
6.3-7 is now live, thanks for testing
