### ISSUE TITLE
AoE2DE: DxvkMemoryAllocator: Memory allocation failed

### ISSUE THREAD

**Issue by mushunrek** [ValveSoftware/Proton#5181]
Hi,
I have just installed Steam on Linux to play AoE2DE and I have encountered different problems. With the different solved issues on the internet, I have been able to get past every one except for this Memory allocation failure. I have tried everything I have been seeing on the internet, but nothing worked.

My system specifications are:
OS: Linux Mint 19.1
CPU:  Intel Core i5-4300U
RAM: 7.5 GiB
Graphics Card: Intel Haswell-ULT

I tested this with the following Proton versions:
5.13, 6.3 and Experimental

Symptoms:
The game starts, but directly after the screen getting black and the AoE mouse icon appears, the program freezes and exits after some time. Here is the relevant part of the log from PROTON_LOG=1:

err:   DxvkMemoryAllocator: Memory allocation failed
err:     Size:      25427968
err:     Alignment: 4096
err:     Mem flags: 0x1
err:     Mem types: 0x1
err:   Heap 0: 1216 MB allocated, 931 MB used, 1266 MB allocated (driver), 1536 MB budget (driver), 1536 MB total
err:   DxvkMemoryAllocator: Memory allocation failed
err:   DxvkMemoryAllocator: Memory allocation failed
err:     Size:      25427968
err:     Alignment: 4096
err:     Mem flags: 0x1
err:     Mem types: 0x1
err:   Heap 0: 1216 MB allocated, 931 MB used, 1266 MB allocated (driver), 1536 MB budget (driver), 1536 MB total
err:   DxvkMemoryAllocator: Memory allocation failed
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1600x900
info:    Image count:  4
info:    Exclusive FS: 1
err:   DxvkMemoryAllocator: Memory allocation failed
err:     Size:      33554432
err:     Alignment: 16
err:     Mem flags: 0x6
err:     Mem types: 0x1
err:   Heap 0: 1216 MB allocated, 937 MB used, 1334 MB allocated (driver), 1536 MB budget (driver), 1536 MB total
err:   DxvkMemoryAllocator: Memory allocation failed

Before that, everything seems normal in the log.

What I tried so far:
  - I renamed the movie directory
  - I tried to install ucrtbase.dll, but there is an error, when I execute cabextract u10 (see https://github.com/ValveSoftware/Proton/issues/1538#issuecomment-529896867)
  - I added SKIPINTRO as a command
  - I added PROTON_FORCE_LARGE_ADDRESS_AWARE=1
  - I added PROTON_USE_WINED3D=1 in which case the game would'nt start at all

I would be very happy for any direction I could continue to search.
Musxhu

**Comment by kisak-valve** [comment]
Hello @mushunrek, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3189#issuecomment-926962879.
