### ISSUE TITLE
Enable native xinput1_3 for more KT Engine games

### ISSUE THREAD

**Issue by whizse** [ValveSoftware/Proton#5185]
Hi,

The WRC titles required [a specific dll override](https://github.com/ValveSoftware/wine/commit/5848899423dbbf763997577e476cf630689c59c6) to work around a problematic dll shipped with the game. It was brought to my attention that the game engine, the KT Engine, is used for additional games.
 
According to SteamDB, the following titles ship with "UWP/xinput1_3.dll" and may also need the override:

TT Isle of Man Ride on the Edge 626610 
TT Isle of Man Ride on the Edge 2 1082180
V-Rally 4 658700 
RiMS Racing 1346010 

I own none of these, but another user confirmed that at least TT Isle of Man Ride on the Edge (626610) needed the override to start.

**Comment by ivyl** [comment]
Thanks for the report. I'll look into this. At this point, since there is so many games affected, it may be worth introducing a compat config switch.

Here's a list of the games by the same dev that has to be checked: https://en.wikipedia.org/wiki/Kylotonn

**Comment by whizse** [comment]
I can vouch for WRC 5,6, and 7 working. I _think_ the dll shenanigans only applies to recent'ish titles, 2018 and later.

**Comment by ghost** [comment]
> I can vouch for WRC 5,6, and 7 working. I _think_ the dll shenanigans only applies to recent'ish titles, 2018 and later.

on my PC (via Steam Link),

* just work with Proton 6.3-7 and prior
  * Truck Racer (B)
  * FlatOut 4 (B)
  * WRC 7 (B)
  * V-Rally 4 (B) (*1)
* crash just after "Play"
  * TT Isle of Man (B) (*2)
  * FIA European Truck Racing Championship (A) (*2)
  * TT Isle of Man: Ride on the Edge 2 (A) (*3)
* misc
  * WRC 8 (A) (*3) (*4)

(A) A: confirm/yes / B: cancel/no
(B) B: confirm/yes / A: cancel/no

(*1) fix for A/B buttons https://steamcommunity.com/sharedfiles/filedetails/?id=2576605732
(*2) workaround: remove prefix, first time setup with Proton 4.11-13, "Play" (no crash), then no crash with Proton 6.3
(*3) it crashes with Proton 4.11-13. I think it worked fine before...
(*4) it starts without workaround with Proton 6.3-7, but gamepad (Logitec F710) is not detected.

**Comment by ivyl** [comment]
Those games require the override on win10 prefixes:

* https://store.steampowered.com/app/626610/TT_Isle_of_Man_Ride_on_the_Edge/
* https://store.steampowered.com/app/1082180/TT_Isle_of_Man_Ride_on_the_Edge_2/
* https://store.steampowered.com/app/1346010/RiMS_Racing/
* https://store.steampowered.com/app/940580/FIA_European_Truck_Racing_Championship/
* https://store.steampowered.com/app/1004750/WRC_8_FIA_World_Rally_Championship/
* https://store.steampowered.com/app/1267540/WRC_9_FIA_World_Rally_Championship/
* https://store.steampowered.com/app/1462810/WRC_10_FIA_World_Rally_Championship/

I am working on having that enabled by default.

>  (*4) it starts without workaround with Proton 6.3-7, but gamepad (Logitec F710) is not detected.

That's expected, https://github.com/ValveSoftware/wine/commit/5848899423dbbf763997577e476cf630689c59c6 has some context.

**Comment by ivyl** [comment]
We now have https://github.com/ValveSoftware/Proton/commit/5e2cf117ce06104da0a582414a27ec0594a02b51 and the `usenativexinput13` compat option has been added for the games listed in the previous comment.
