### ISSUE TITLE
Error when trying to run Secret World Legends using Proton

### ISSUE THREAD

**Issue by pehkawn** [ValveSoftware/Proton#5186]
# Compatibility Report
- Name of the game with compatibility issues: Secret World Legends
- Steam AppID of the game: 215280

## System Information
- GPU: NVIDIA Corporation NVIDIA GeForce MX130/PCIe/SSE2
- Driver/LLVM version: 4.6.0 NVIDIA 470.63.01
- Kernel version: 5.4.0-86-generic
- [Full system information report](https://gist.github.com/pehkawn/49858c1beb01e245c3e9c3d1a2df6aae)
- Proton version: 6.3-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-215280.log](https://github.com/ValveSoftware/Proton/files/7235208/steam-215280.log)

## Symptoms 
I recently downloaded Secret World Legends from my Steam library. (I am currently running Ubuntu 20.04.) When I try starting the launcher in Steam, a progress bar saying it's downloading "DX 9.0 Web setup" appears. Once completed, it seem to try open the game's update manager, resulting in the game crashing and get a prompt for sending an error report to Funcom. According to [protondb](https://www.protondb.com/app/215280), the game should be possible to run with the following dependencies installed in Protontricks:

> Customizations: Protontricks Installed: d3dx9_43 d3dx11_43 d3dcompiler_43

I found [tutorial for installing Protontricks](https://www.maketecheasier.com/troubleshoot-steam-games-work-linux/). I tried installing the the game dependencies listed on protondb following the tutorial.

Example syntax:

```sh
protontricks -s Secret World Legends
Found the following games:
Secret World Legends (215280)

protontricks 215280 d3dx9_43
protontricks 215280 d3dx11_43
protontricks 215280 d3dcompiler_43
```
When trying to install either of the dependencies, the same happens: The installation starts, then hangs returning the following error message:

```sh
00bc:err:xrandr:xrandr14_get_adapters Failed to get adapters
```
I was wondering if anyone could help me understand what this error message means and how to resolve the issue? A tutorial on how to install these dependencies correctly would be much appreciated.

**Comment by kisak-valve** [comment]
Hello @pehkawn, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1511#issuecomment-927832291.
