### ISSUE TITLE
The Elder Scrolls Online (appid 306130) doesn't start since last proton update

### ISSUE THREAD

**Issue by swistak35** [ValveSoftware/Proton#5190]
# Compatibility Report
- Name of the game with compatibility issues: The Elder Scrolls Online
- Steam AppID of the game: 306130

## System Information
- GPU: RTX 2080 Ti
- Driver/LLVM version: 4.6.0 NVIDIA 460.73.01
- Kernel version: 5.11.0-17-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/swistak35/8a859753e3fbc041feb48d9b1fe6bc3a
- Proton version: 6.3-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
[steam-306130.log](https://github.com/ValveSoftware/Proton/files/7269213/steam-306130.log)

## Symptoms 

Today The Elder Scrolls Online stopped working (yesterday it worked). Therefore I assume that the issue is in recent proton update, 6.3-7. After starting the game in steam nothing happens, but the game is visible as running in steam and I can stop it. It can be running like that for the longer time, it does not crash itself. After picking 5.13-6 version in steam it works. Unfortunately I can't pick 6.3-6 version in steam so can't confirm for 100% that the problem is in recent update.

**Comment by kisak-valve** [comment]
Hello @swistak35, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/556#issuecomment-932439337.
