### ISSUE TITLE
Force Windows build?

### ISSUE THREAD

**Issue by linkjay** [ValveSoftware/Proton#52]
Is there any way to force a game that does have support for Linux to work with the Windows build through Steam play? If not, can we get a method for doing that?

Some games might run better due to more support being put into the Windows version of that game so it would be better to actually run it through Proton instead.

**Comment by ghost** [comment]
One such example: Pillars of Eternity. Capes are invisible in the Linux version because the physics middleware they used has no Linux build, so they simply removed capes instead of fixing it. It would be nice to have easy access to the Windows version of the game to remedy this (and similar issues with other games).

**Comment by mhsabbagh** [comment]
I agree with this suggestion. Some games may have glitches and local bugs on their Linux version, so providing a Windows version of them could solve the issues.

**Comment by BlauerHunger** [comment]
And there are games without cross-platform multiplayer, like Saints Row IV.

**Comment by Urfoex** [comment]
+1
E.g. Risk of Rain: Spikestrip-item freezes the game
E.g. Dungeon Defenders: Missing PhysX makes some mana-objects static.

**Comment by cjwijtmans** [comment]
+1 to this. some games run better on the windows version even in wine.

**Comment by jarrard** [comment]
Another example is Tomb Raider 2013 (the original remake) runs better with its windows version under DXVK then its native OpenGL version, more consistent framerates and less stutters.

**Comment by vadi2** [comment]
In some cases there is a native game but the betas for the game are not yet available (ie Thrones of Brittania is native but the Allegiance beta is Windows-only).

**Comment by Despruk** [comment]
This should probably be done in the Steam client Project
Here it's already open #https://github.com/ValveSoftware/steam-for-linux/issues/5638

**Comment by kisak-valve** [comment]
Let's track this feature request for the steam client in the steam-for-linux issue tracker. Closing in favor of https://github.com/ValveSoftware/steam-for-linux/issues/5638.
