### ISSUE TITLE
Wreckfest Create Server Crash Fedora 34

### ISSUE THREAD

**Issue by goshansp** [ValveSoftware/Proton#5204]
Since around upgrading from Fedora33->34 (on three boxes) Wreckfest on all systems shows same behavior when creating a server, a crash to desktop. Singleplayer and Online work without issue.

https://gist.github.com/goshansp/579f65974f47a6c76ff4aee50421960e

Re-Installation of Steam and different Proton-Versions exhibit identical behavior. Any advice highly appreciated.

**Comment by kisak-valve** [comment]
Hello @goshansp, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/758#issuecomment-937924831.
