### ISSUE TITLE
Hot Wheels Unleashed - Out of video memory

### ISSUE THREAD

**Issue by diegosandovalramirez** [ValveSoftware/Proton#5207]
# Compatibility Report
- Name of the game with compatibility issues: Hot Wheels Unleashed
- Steam AppID of the game:1271700

## System Information
- GPU:  GTX 1050 Ti
- Driver/LLVM version:  470.63.01
- Kernel version:  5.14.10-1
- Link to full system information report as [Gist](https://gist.github.com/diegosandovalramirez/caa60d617a024d3a231c3e84aee98a92):
- Proton version: Proton-6.18-GE-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1271700.log](https://github.com/ValveSoftware/Proton/files/7312038/steam-1271700.log)

## Symptoms 
Game exists with a wine message "Not enough memory for rendering resource" despite the game being fine in windows and the hardware being over the minnimum requirements.

## Reproduction
Runnning the game at any graphic setting will display this error. 
Depending on the graphic settings, the error will be displayed at different points of the game.
With my current setting it usaully happened at the first loop while at the top of it, now I got flipped so it crashed before. (Maybe a correlation with the camera being pointed up?)
![Screenshot_2021-10-08_11-41-48](https://user-images.githubusercontent.com/29217412/136577239-41f8970c-7007-4e04-8b9a-4fcd3015c494.png)

![Screenshot_2021-10-08_11-43-18](https://user-images.githubusercontent.com/29217412/136577249-2abc6e8f-0c40-426b-bc97-26a428066e57.png)

**Comment by kisak-valve** [comment]
Hello @diegosandovalramirez, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5196#issuecomment-938721267.
