### ISSUE TITLE
virtual desktop 5760 x 1080 seems broken since Proton 5.0 in some games

### ISSUE THREAD

**Issue by addeps3** [ValveSoftware/Proton#5208]
Hi, 

am testing some racing sims such as Assetto Corsa/Competizione, and Beam Ng Drive and all will boot and run in a virtual desktop set to 5760 x 1080 on triple screens with proton 5.0

If switching to proton 5.13 or Experimental then Asetto Corsa/Competizione crash soon after launching ends, although Beam Ng will work with Experimental. 

If testing with 6.3, then Corsa/Competizione will run on virtual desktop, but the game window ends up on the far right part of the VD, and the full width of the game window is "outside" the far right edge of it.

I have tried pulling the window inside VD to the left and the VD itself to the far left but the game window will not go past the sceen bezel between my middle and left hand monitor. 

Thus Assetto Corsa/Competizione and other games must use proton 5.0 to run in triple screen or boot will fail or the game window is too far to the right.

Please make it possible to use a later and faster version of proton with the same, perfect functionality as 5.0. /Best wishes, Adam

**Comment by kisak-valve** [comment]
Hello @addeps3, this issue is already being tracked at #4673. Closing as a duplicate.
