### ISSUE TITLE
Call of Duty: Black ops III (311210)

### ISSUE THREAD

**Issue by deadmeme5** [ValveSoftware/Proton#5209]
# Compatibility Report
- Name of the game with compatibility issues:
- Alsa driver Loads and unloads : Consequence: I have no sound.

## System Information
- GPU:  Nvidia GTX 1060 6GB 
- Driver/LLVM version:  Nvidia Driver version: 470.63.01 
- Kernel version:  5.14.10
- Proton version: Proton 6.36-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
- [x] that I have tried reinstalling ALSA driver

 
[steam-311210.log](https://github.com/ValveSoftware/Proton/files/7315828/steam-311210.log)

## Reproduction
1. Download BO3  from steam
2. That's it, the rest i suspect is a wine bug!

## My notes: Most important logs

 This is the most likely killer log: 
```
26902.328:010c:0188:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\winealsa.drv" at 00007F959C080000: builtin
26902.328:010c:0188:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\winealsa.drv" : builtin 
```

Also pulse audio initiates as fixme:
 `26902.381:010c:0188:fixme:pulse:AudioSessionControl_RegisterAudioSessionNotification (0x322c06b0)->(0x1591b33e8) - stub`

Pls help.

**Comment by kisak-valve** [comment]
Hello @deadmeme5, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/864#issuecomment-939310072.
