### ISSUE TITLE
Non-HID devices no longer detected as gamepad (Steam Input disabled)

### ISSUE THREAD

**Issue by kakra** [ValveSoftware/Proton#5211]
I'm not sure if this is related to the Steam Beta client, or using Proton Experimental:

Games no longer detect my USB-connected gamepad. Gamepads connected via HID drivers still seem to work. If I turn on Steam Input, the gamepad is detected again - but the problem is that the input profile defaults to keyboard/mouse emulation for many games which is just unusable, I'm not sure why Steam does that for some games. And outside of BPM, it's really difficult to load a different game-specific profile. But that doesn't matter, it should simply not default to a keyboard/mouse emulation profile. That's one reason why I don't use Steam Input.

Steam Beta client and Proton Experimental versions: 2021-10-10

This problem exists for at least 2 days now, I didn't need the gamepad previously.

Tested games so far:

* Elite Dangerous
* Assassins Creed: Odyssey

**Comment by kakra** [comment]
Seems to be fixed - I tried again yesterday (2021-10-17). I'm not sure what caused it, there seems nothing relevant in the commit logs of wine.

**Comment by kisak-valve** [comment]
Closing per the last comment.
