### ISSUE TITLE
Microsoft Flight Simulator 2020 - Microsoft account window bugs and crash

### ISSUE THREAD

**Issue by andanders** [ValveSoftware/Proton#5215]
# Compatibility Report
- Name of the game with compatibility issues: Microsoft Flight Simulator 2020
- Steam AppID of the game: [1250410](https://store.steampowered.com/app/1250410/Microsoft_Flight_Simulator/)

## System Information
- GPU: GTX980
- Driver/LLVM version: Nvidia 470.63.01
- Kernel version: 5.13.0-7614-generic  (Pop!_OS 21.04 (64 bit))
- Link to full system information report as [Gist](https://gist.github.com/andanders/3ebd81afe8b8d593170bf5954e496e50):
- Proton version: 6.3-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[Proton log in gist](https://gist.github.com/andanders/d1bf0e6b24225c28cb58a7ec072e35d2)

## Symptoms 
The Microsoft account windows that appears when the game launches is broken.
A. When creating a new account, the game does not proceed to the main menu, but is stuck with the Microsoft window.
B. The game crashes when navigating back in the Microsoft account window.

### A:
Create Microsoft account
Get stuck in a Microsoft products window.

![20211010204131_1](https://user-images.githubusercontent.com/49952149/136849425-b7df4576-07f1-404d-aaae-a65f12cc083b.jpg)

### B: 
Start the game
press 'back' arrow in Microsoft account window
game crashes

![20211010205001_1](https://user-images.githubusercontent.com/49952149/136850212-cfec5acd-ec8f-4a99-88fe-3564c032d7f3.jpg)

**Comment by kisak-valve** [comment]
Hello @andanders, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-940418536.
