### ISSUE TITLE
Dark Souls III refuses to launch

### ISSUE THREAD

**Issue by poperigby** [ValveSoftware/Proton#5216]
# Compatibility Report
- Name of the game with compatibility issues: DARK SOULS™ III
- Steam AppID of the game: 374320

## System Information
- GPU: RX 5700 XT
- Driver/LLVM version: Mesa 21.2.3
- Kernel version: 5.14.10
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/lumbo7332/813664057e5892904cbb82d65a62f0c0
- Proton version: 6.3-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-374320.log](https://github.com/ValveSoftware/Proton/files/7326208/steam-374320.log)

## Symptoms 
Beginning two days ago, Dark Souls III will no longer launch. I click "PLAY", the button changes to "STOP" for a few seconds, and then it switches back to "PLAY."

## Reproduction
1. Launch Dark Souls III.

I've found other issues about Dark Souls III having trouble launching, but all of those people get a black screen for a few seconds before the game crashes. In my case, it doesn't launch at all.

**Comment by kisak-valve** [comment]
Hello @lumbo7332, it looks like the wineprefix for the game is corrupted. Can you move `/home/cassidy/.local/share/Steam/steamapps/compatdata/374320/` somewhere out of the way and then try running the game to generate a new wineprefix for the game? If Steam's cloud save doesn't work for this game, then you might need to find the save files for the game in the old wineprefix and copy them over to the newly created wineprefix.

**Comment by poperigby** [comment]
That fixed it, thanks! Do you know why that happened/how I can prevent it in the future? Also, what line in the log tipped you off?

**Comment by kisak-valve** [comment]
Glad to hear that helped.

```
system.reg is not a valid registry file
userdef.reg:4: Mismatched architecture '#arch=win64'
userdef.reg is not a valid registry file
user.reg is not a valid registry file
```
This looks like wine's equivalent of the Windows registry is broken, and the rest of the log is missing wine dlls that should be around, which hints that something happened to trash the wineprefix.

In this case, unfortunately, we only get to see the aftermath of whatever happened and not the cause. There's no way to give a suggestion to prevent a similar incident in the future without being able to reliably reproduce this kind of issue.

**Comment by poperigby** [comment]
Thank you! I guess I'll check for that next time it stops working. Should I re-open this issue if I find a way to reliably reproduce the problem?
