### ISSUE TITLE
Conan Exiles Crash

### ISSUE THREAD

**Issue by LiSiaoCheng** [ValveSoftware/Proton#5217]
# Compatibility Report
- Name of the game with compatibility issues:Conan Exiles
- Steam AppID of the game:440900

## System Information
- CPU: AMD Ryzen Threadripper 3970X 32-Core Processor
- GPU: NVIDIA Corporation NVIDIA Geforce RTX 3090 
- Driver/LLVM version: 4.6.0 NVIDIA 470.74
- Kernel version: 5.14.9-200.fc34.x86_64 
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/LiSiaoCheng/551745ce08800ee92bb11d4880478a0a
- Proton version:6.3.7

## I confirm:
- [yes] that I haven't found an existing compatibility report for this game.
- [yes] that I have checked whether there are updates for my system available.

## Symptoms 
Game exits when trying to start. There is no error message, game simply quits before showing anything. 

## Reproduction

1. Start the game (press "play"),Observe game exiting,it cannot launch;
2. I tried all available Proton visions(Experimental,6.3.7,5.13-6,5.0-10,4.11-13,4.2-9,3.16-9,3.7-8) from steam apps,the same fail;
3. Reinstall steam and Conan Exiles,the same fail;
3. I have noticed that Changelog proton 6.3-5 "Fix Conan Exiles and other Funcom launchers crashing", but steam proton list have not proton 6.3-5,i cannot download Proton 6.3-5 to confirm wether it has fixed or not.
4. You can check my system information details from this link:https://gist.github.com/LiSiaoCheng/551745ce08800ee92bb11d4880478a0a

**Comment by LiSiaoCheng** [comment]
Add scripts  'PROTON_LOG=1 %command%'  to the game's launch options, now Conan Exiles can be Launched.but I'm not sure it can play smoothly, and the BattlEye still can not install on Linux based Operate System,i have nothing to do but disable BattlEye,also I'am not sure all games that users have to add scripts  'PROTON_ENABLE_NVAPI=1'  to support Nvidia's NVAPI GPU  library and DLSS, and scripts 'PROTON_LOG=1 %command%'  to avoid game crashing ,and the scripts can not be save like steam cloud,maybe Valve can do something like set-default or release some patch for games.There is not everyone can know visiting the right website and say:"help me",hoping we have better solution.

**Comment by kisak-valve** [comment]
Hello @LiSiaoCheng, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2563#issuecomment-940927122.
