### ISSUE TITLE
Bug - Launching Steam spins up 1000s of instances of 'explorer.exe' until system crashes.

### ISSUE THREAD

**Issue by pnomolos** [ValveSoftware/Proton#5218]
I feel like this falls under Proton because it's clearly related to the Proton compatibility layer - just not within a specific game.

With 30s of launching Steam, instances of `explorer.exe /desktop` begin to be launched at the rate of several hundred a second, until the limit on open files on my system is overwhelmed.

This is on the latest Steam beta, Ubuntu 21.04, Linux 5.14.11-051411-generic

**Comment by pnomolos** [comment]
I reinstalled Steam and nuked all my proton prefixes (not the games-specific ones, but the actual tool ones) and it seems to have fixed the problem, but I'll leave it open for a little longer because this came about without me making any changes to cause it.

**Comment by veganvelociraptor** [comment]
I have the same issue on one of my computers (but not the other, strangely, as both run the exact same Steam Beta versions).

Though I didn't have to reinstall Steam, it was enough to kill all the explorer.exe and wineboot.exe processes repeatedly, until they stopped respawning. And then I could manually uninstall all the Proton versions from Steam, disable Proton in the settings, restart Steam and re-enable Proton. Then it worked again as it used to before all this happened.

**Comment by kisak-valve** [comment]
For anyone coming across this issue report, this is from a previously hidden quirk in some third party Proton builds. Please see the discussion on https://github.com/ValveSoftware/steam-for-linux/issues/8114.

**Comment by mkrupczak3** [comment]
bump

**Comment by mkrupczak3** [comment]
@kisak-valve recommend this issue be re-opened, causes significant system impairment and prevents customers from launching Steam or any of their purchased games

**Comment by kisak-valve** [comment]
Hello @mkrupczak3, the current indicator is that this issue only happens with older third party Proton builds, which are unsupported by anybody. A proper fix would need to be there, but there isn't an automated update process for user-added Proton builds.

No, this issue will not be re-opened.

**Comment by mkrupczak3** [comment]
Thanks for taking a look nonetheless
