### ISSUE TITLE
Crysis3 not starting

### ISSUE THREAD

**Issue by zohozer** [ValveSoftware/Proton#5219]
[steam-1282690.log](https://github.com/ValveSoftware/Proton/files/7332934/steam-1282690.log)
# Compatibility Report
- Name of the game with compatibility issues: Crysis3
- Steam AppID of the game: 1282690 

## System Information
- GPU: RTX 3070
- Driver/LLVM version: 470.74
- Kernel version: 5.13.0-19-generic 
- Proton version: All

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

## Symptoms

Every time I launch the game it is asking me to install the Origin Launcher, and after installation it is flashing for a second a white window and the game stops.

**Comment by kisak-valve** [comment]
Hello @zohozer, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3975#issuecomment-941467452.
