### ISSUE TITLE
Whitelist Bloons TD 6

### ISSUE THREAD

**Issue by jannis3005** [ValveSoftware/Proton#5221]
# Whitelist Request
- Name of the game to be whitelisted: Bloons TD 6
- Steam AppID of the game: 960090

## System Information
- GPU: RTX 3080
- Driver/LLVM version: nvidia 470.74
- Distro version: Arch Linux
- Link to full system information report as [Gist](https://gist.github.com/jannis3005/7770f36912a90025c4ab643a3a892c9f):
- Proton version:

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [ ] There are no issues left open for this game. <- But no comments for over 10 Months
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @jannis3005, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2330#issuecomment-942598652.

**Comment by jannis3005** [comment]
Whoops, sorry @kisak-valve
