### ISSUE TITLE
GTA IV Hangs Unrecoverable

### ISSUE THREAD

**Issue by CrezyDud** [ValveSoftware/Proton#5224]
# Compatibility Report
- Name of the game with compatibility issues: Grand Theft Auto IV: The Complete Edition
- Steam AppID of the game: 12210

## System Information
- GPU:  Radeon RX Vega 64
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 6.3-7 or Experimental or Custom proton (proton-ge-custom)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
None

## Reproduction

Hangs directly when loading
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
--== or: i dont rememeber what i did but i was able to get in the game, past the loading screen ==--
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
playing a little, it's been reported multiple times, and its usuall very random, sometimes it hangs short sometimes long.
It usually corrupts everything, computer becomes almost unusable, it seems to corrupt video memory

**Comment by kisak-valve** [comment]
Hello @CraezyDud, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/350#issuecomment-944970830.
