### ISSUE TITLE
The Great Ace Attorney Chronicles 

### ISSUE THREAD

**Issue by ioletsgo** [ValveSoftware/Proton#5226]
When running The Great Ace Attorney Chronicles with Proton, the entire system crashes.

When running it through Wine, i get this error message.
[backtrace.txt](https://github.com/ValveSoftware/Proton/files/7358913/backtrace.txt)

**Comment by kisak-valve** [comment]
Hello @ioletsgo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5016#issuecomment-945104627.
