### ISSUE TITLE
Ni no Kuni: Wrath of the White Witch Remastered

### ISSUE THREAD

**Issue by dylanmtaylor** [ValveSoftware/Proton#5228]
# Whitelist Request
- Name of the game to be whitelisted: Ni no Kuni: Wrath of the White Witch
- Steam AppID of the game: 798460

## System Information
- GPU: NVIDIA Quadro T1000 Mobile
- Driver/LLVM version: Nvidia 495.29.05-183
- Distro version: Arch Linux
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/dylanmtaylor/47fe948dd374c894e851a880f3d3fa67
- Proton version: Experimental

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @dylanmtaylor, we're using one issue report per unofficially supported game title, and there's already a whitelist request for this game at #4346. Additionally, by its nature, Proton Experimental can not be used as a whitelist target.

Closing as a duplicate.
