### ISSUE TITLE
Path of Exile (238960) Regression: Mouse cursor black block

### ISSUE THREAD

**Issue by rgehlen** [ValveSoftware/Proton#5230]
# Compatibility Report
- Name of the game with compatibility issues: Path of Exile
- Steam AppID of the game: 238960

## System Information
- GPU: RX 570
- Driver/LLVM version: mesa 20.1.6
- Kernel version: 5.14
- Proton version: current experimental from steam (7554304)

## Symptoms 

Mouse cursor is a black block. This problem only appeared today. Worked fine before.

https://rgehlen.github.io/output.webm

https://gist.githubusercontent.com/rgehlen/8ae51d4b7101c3f4b374ed30de10b334/raw/8d673d23a120a45bd921ce28ba2233facf14105e/steam-238960.log

Also works fine on Proton 6.3-7

**Comment by kisak-valve** [comment]
Hello @rgehlen, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/58#issuecomment-946659660.
