### ISSUE TITLE
Low GPU usage + consistently poor performance with all Proton titles

### ISSUE THREAD

**Issue by avalonv** [ValveSoftware/Proton#5231]
Games on proton infrequently hit 60 fps, and there are frequent dips below 30fps, despite GPU utilization never going above 50%. Tested with Nier Automata, MGSV, and Ultrakill.
With Ultrakill in particular, it usually runs well, but it randomly drops to 30fps when standing still, and moving again causes a lag spike which lasts a few seconds. I've recorded footage of this, and can post it if requested. This struck me as unusual as this doesn't happen on another system without a dedicated GPU.
Native games run flawlessly, Dusk, CSGO, and Devil Daggers all rarely drop below 200 fps.

- Distro: Arch Linux with KDE Plasma
- GPU: GTX 1660 Ti Mobile
- Driver/LLVM version: Tested with both Nvidia 470 and 495-beta
- Kernel version: 5.14.12-arch1-1
- Proton version: Tested with 6.3, 5.13, and 4.2

**Comment by avalonv** [comment]
Here's a proton log of Nier Automata: https://gist.github.com/avalonv/7b251a65a038dc6b1cedafaf7a3c42f5

**Comment by popsUlfr** [comment]
I see that fsync is not enabled but I'm not sure it would really make that much of a difference compared to esync. linux-zen has fsync enabled so you can check if that helps.
Another thing which I'm not sure is still a problem but it seems to fit your description of dropping fps when moving, a mouse with a polling rate of 1000Hz displayed some high dips in performance in the past in certain games (I've mine at 500Hz).
Set your cpu governor to performance.

**Comment by avalonv** [comment]
@popsUlfr I see, thanks for the reply, I'll test that and report back here.
> Set your cpu governor to performance.

I've seen several examples of how to do that, any you would recommend in particular? Is
`echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor` enough?

**Comment by popsUlfr** [comment]
Sure that works :)

If you install `cpupower` you can also simply do
```
sudo cpupower frequency-set -g performance
```

**Comment by avalonv** [comment]
@popsUlfr Sorry for the delay, a bios update overwrote my bootloader, took a while to fix >_>

Anyway, you were right, my cpu governor was set to powersaving for whatever reason, setting it to performance fixed everything! The games I tested run smoothly now, night and day difference. 
Thank you SO much, this was really ticking me off and it would've taken me a lot longer to figure it out by myself.

**Comment by popsUlfr** [comment]
That's great! I'm glad you're finally enjoying a better gaming experience.
Also check out if a fsync enabled kernel gives you an even smoother experience. Happy gaming!
