### ISSUE TITLE
Project Cars showing error when assigning buttons with gaming wheel

### ISSUE THREAD

**Issue by MoriGM** [ValveSoftware/Proton#5233]
# Compatibility Report
- Name of the game with compatibility issues: Project Cars
- Steam AppID of the game: 234630

## System Information
- GPU: RX 580 8G
- Driver/LLVM version: Mesa 22.0.0-devel
- Kernel version: 5.13.13
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/MoriGM/fb8c6de3e8f7207ef027d1e537cbbdaa
- Proton version: 6,3-7

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-234630.log](https://github.com/ValveSoftware/Proton/files/7381750/steam-234630.log)

## Symptoms
Logitech Driving Force GT and Thrustmaster T150RS both getting detected but when reassigning the buttons it will throw an error saying to many inputs.

## Reproduction
1. Starting Project Cars.
2. Going into the Options.
3. Going into Input Settings.
4. Assigning a button.

I think this problem happens because wine passes the wheel through as a event and as a joystick.
But i couldn't find any way to only use one of the two.

**Comment by kisak-valve** [comment]
Hello @MoriGM, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/244#issuecomment-947699266.
