### ISSUE TITLE
Rise of the Tomb Raider (391220) Crashes Immediately on Start ... After Playing for 99 min

### ISSUE THREAD

**Issue by PorcelainMouse** [ValveSoftware/Proton#5236]
# Compatibility Report
- Name of the game with compatibility issues: Rise of the Tomb Raider
- Steam AppID of the game: 391220

## System Information
- GPU: AMD Radeon 5700XT
- Driver/LLVM version: AMD AMD Radeon RX 5700 XT (NAVI10, DRM 3.42.0, 5.14.9-200.fc34.x86_64, LLVM 12.0.1)
- Kernel version: 5.14
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/PorcelainMouse/501732a24b2c407b9b0e74f221aa1aa5
- Proton version: no specific version forced, using default

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game (that was similar).  One compatibility report exists, but symptoms where wildly different and different hardware.
- [ x ] that I have checked whether there are updates for my system available.

I tried several times to get this log, but it was never created.  I checked everywhere.

## Symptoms 
I played ROTR for about 99 after launching it for the first time.  But, after quitting the game & steam, the next time I started Steam and launched the game, it crashed and continues to crash no matter what I do.  I reached on to Steam (no help) and Feral Interactive, who kindly sent me troubleshooting instructions.  They suggested clearing the Steam cache and verifying the game files.  I tried those and still the game crashes.  This makes no sense, since it ran perfectly find just two days before.  I didn't even reboot the computer between working & crashing conditions, no updates to flatpak, or system occurred between conditions.  Since then, I have rebooted an updated flatpak, but not any part of my system.

I let the automated crash reporting system report the first crash dump. But, subsequent dump files have not been reported.

## Reproduction
- Install ROTR
- Start game, play for an hour or so
- quit game
- quit Steam
- start Steam
- launch ROTR, crashes

Crash msg:
![Screenshot-20211014000447-ROTRerror](https://user-images.githubusercontent.com/159714/138220440-3673f40a-c21d-4a07-a346-0fab08f451e6.png)

**Comment by kisak-valve** [comment]
Hello @PorcelainMouse, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4691#issuecomment-948566896.
