### ISSUE TITLE
Proton Experimental OSError: [Errno 39] Directory not empty on Application Data backup folder

### ISSUE THREAD

**Issue by Kromilan** [ValveSoftware/Proton#5238]
Hello.
I am not sure if this is the right place to ask for help. Steam didn't have a Forum about Proton either, so I am not sure where to turn with issues and turned here, but if this is not the right place, please redirect me.

No games running through Proton work any more and I don't know the reason. I haven't played any games over the last days, so I cannot pinpoint when exactly this issue arose. I expect that there might have been updates to some part of the system, but I didn't pay attention to that. In short, I don't know if anything mayor changed.
Anyhow, I can suddenly no longer run any Games Via Proton. I already tried reinstalling steam, including deleting ~/.steam and ~/.local/share/steam. I also tried different versions of Proton. I also reinstalled the games and deleted their entries in comptdata. 
The issue presents itself like so:
For Among Us and , when I click play, a window opens. That window is fullscreen, displays a screenshot of my screen at the moment I clicked Start and is not responding. Same for Dark Souls III (whitelisted for Proton), but there the window is white and I have the cursor.
With Sekiro when I click Start, the button changes to running but no window appears. After a couple of moments the button turns back to Start.
With the Game Catherine I get a little window with the Text "unable to create renderer. Please correct settings and try again." followed by one saying: `Error in NiRendererTabController::InitDialog() Unable to save class pointer using SetWindowLongPtr(). Windows reports error 0x57a.`
Surprisingly, the Game Brawlhalla runs without any issues. It's the only one that works fine out of the ones in my library.

Games, that run natively on Linux, run without issues.
Furthermore, and I expect this is important, wine games which I installed via Lutris without involving Steam or Proton (Final Fantasy XIV, Magic the Gathering: Arena and LackeyCCG) all run without any issues too, however they launch slower than I'm used to.

((I tried if this error persists on a fresh install of my OS. It does, but on a fresh install I also cannot run wine games through Lutris, so I think on a fresh install it's a different issue.))

I use Manjaro. My Graphics card is an Nvidia RTX2060. I have the hybrid driver for it and Intel installed and am running it in nvidia mode through optimus manager.

Can anyone help me or point me in the right direction?
Thank you all in advance!

**Comment by kisak-valve** [comment]
Hello @Kromilan, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the launch options of some of the failing games and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by Kromilan** [comment]
https://gist.github.com/Kromilan/cd15233ee651accd4e49018fa2d3974b
I attached the logs for Deep Rock Garlactic (stays at a black screen), Digimon Story Cyber Sleuth(closes itself instantly), Sekiro (also closes itself instantly) and for Frostpunk (takes ages to start but then actually works fine)
[steam-548430.log](https://github.com/ValveSoftware/Proton/files/7391497/steam-548430.log)
[steam-1042550.log](https://github.com/ValveSoftware/Proton/files/7391517/steam-1042550.log)
[steam-814380.log](https://github.com/ValveSoftware/Proton/files/7391671/steam-814380.log)
[steam-323190.log](https://github.com/ValveSoftware/Proton/files/7391672/steam-323190.log)

**Comment by kisak-valve** [comment]
This is sounding similar to some of the feedback on #5237. Can you give the workaround at https://github.com/ValveSoftware/steam-runtime/issues/312#issuecomment-739441559 a try to simplify the Vulkan render path setup and also completely close Steam, then run `steam-runtime` from a terminal and check if Proton gives a hint when you tell Steam to start Sekiro and Digimon Story Cyber Sleuth?

The Deep Rock Galactic log points to a separate issue to be pondered after the system is in a healthier state.
```
15467.300:011c:0120:err:module:open_builtin_file failed to load .so lib "/home/milan/Games/SteamLibrary/steamapps/common/Proton - Experimental/files/lib64/wine/x3daudio1_7.dll.so"
15467.301:011c:0120:err:module:import_dll Loading library X3DAudio1_7.dll (which is needed by L"Z:\\home\\milan\\Games\\SteamLibrary\\steamapps\\common\\Deep Rock Galactic\\FSD\\Binaries\\Win64\\FSD-Win64-Shipping.exe") failed (error c000007a).
15467.302:011c:0120:err:module:open_builtin_file failed to load .so lib "/home/milan/Games/SteamLibrary/steamapps/common/Proton - Experimental/files/lib64/wine/xapofx1_5.dll.so"
15467.302:011c:0120:err:module:import_dll Loading library XAPOFX1_5.dll (which is needed by L"Z:\\home\\milan\\Games\\SteamLibrary\\steamapps\\common\\Deep Rock Galactic\\FSD\\Binaries\\Win64\\FSD-Win64-Shipping.exe") failed (error c000007a).
[...]
15467.327:011c:0120:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\milan\\Games\\SteamLibrary\\steamapps\\common\\Deep Rock Galactic\\FSD\\Binaries\\Win64\\FSD-Win64-Shipping.exe" failed, status c0000135
```

**Comment by Kromilan** [comment]
I tried the workaround. It didn't change anything. Here is everything that appeared in the terminal when I clicked play on Sekiro. https://gist.github.com/Kromilan/9d88513481e299304a81935e0faed2aa

**Comment by kisak-valve** [comment]
Thanks. these look like lines of interest:
```
Traceback (most recent call last):
  File "/home/milan/Games/SteamLibrary/steamapps/common/Proton - Experimental/proton", line 1294, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/milan/Games/SteamLibrary/steamapps/common/Proton - Experimental/proton", line 1108, in init_session
    g_compatdata.setup_prefix()
  File "/home/milan/Games/SteamLibrary/steamapps/common/Proton - Experimental/proton", line 655, in setup_prefix
    self.migrate_user_paths()
  File "/home/milan/Games/SteamLibrary/steamapps/common/Proton - Experimental/proton", line 630, in migrate_user_paths
    os.rename(old, old + " BACKUP")
OSError: [Errno 39] Directory not empty: '/home/milan/Games/SteamLibrary/steamapps/compatdata/814380/pfx/drive_c/users/steamuser/Application Data' -> '/home/milan/Games/SteamLibrary/steamapps/compatdata/814380/pfx/drive_c/users/steamuser/Application Data BACKUP'
```

**Comment by Kromilan** [comment]
Thank you for your help and sorry that I am only coming back to this now.
I don't believe that it's a problem with Proton Experimental because the results are the same when I use Proton 6.1 and Proton 5.7.
I tried out a different graphics driver; the one only for nvidia without a hybrid mode. the result is that some games (Sekiro, Among us, Dark Souls 3) now run again, but the majority of games show no change.

**Comment by Kromilan** [comment]
I no longer require help with this. The issue was not resolved and I have no idea where it came from. However, I simply reinstalled Linux and that fixed everything. 

Sorry to everyone who stumbles upon this with the same problem.

**Comment by eprovst** [comment]
This issue seems to be rather pervasive. A bunch of backups of folders are made throughout startup of a game, if one of those end up not being cleared at shutdown, the game will refuse to start.

I do not know exactly what the aim of those backups is, if one can safely assume old backups to be irrelevant at the start of the game, then it is simple enough to attempt to remove the folder if it exists before attempting create the new backup. If that is not a valid assumption, I have no idea what the right fix would be, except perhaps providing an error message instead of quitely giving up.
