### ISSUE TITLE
How run logging for Non-Steam games with Proton inside Steam?

### ISSUE THREAD

**Issue by tele1** [ValveSoftware/Proton#5243]
I made a task for myself.
- To check
- Create a guide 

I download Blender because it is under the GNU License.
Because I can advertise, download for free, edit, debug it, and no one can ever put me in jail for it.

1. I download portable app for win.
https://www.blender.org/download/

* Working with Proton 6.3-7
* But not working when I added option:  PROTON_LOG=1 and I can not create log.
( opens the window and closes )

----

2. I download installer.

2.1 I needed change Win. to Win. 8.1 inside
```
winecfg
```

2.2 I run installer 
```
msiexec /i blender-2.93.5-windows-x64.msi
```
2.3 I found .exe file
/home/user_name/.wine/drive_c/Program Files/Blender Foundation/Blender 2.93/blender.exe

2.4 I added game ( app :smile:  ) to Steam

> Inside Steam go to "+Add a game" > Add a non-steam Game (bottom left hand corner of the screen).

> Click "browse" and locate your game.

> Double click the executable of your game. If you can't see the executable, make sure "All files" is selected in the "File type".

> Again click "+Add a game" > Add a non-steam Game. Then make sure you executable is selected and click "Add selected programmes".

> Right click on the game name in your library and click "Properties". Go to Compatibility and enable "Force the use of a specific Steam Play compatibility tool.

* And here Blender not working. And I can not create log also.

**Comment by kisak-valve** [comment]
Hello @tele1, it sounds like https://github.com/ValveSoftware/steam-for-linux/issues/6046 is interfering with your troubleshooting. As an alternative, you should be able to completely close Steam, then run `PROTON_LOG=1 steam` from a terminal.

**Comment by tele1** [comment]
> run 
> ```
> PROTON_LOG=1 steam 
> ```
> from a terminal.

It works. Thank you for your help. :smile:
