### ISSUE TITLE
Awful performance on Tekken 7

### ISSUE THREAD

**Issue by nikseyy** [ValveSoftware/Proton#5247]
# Compatibility Report
- Name of the game with compatibility issues: TEKKEN 7 
- Steam AppID of the game: 389730 

## System Information
- GPU: GTX 650
- Driver/LLVM version:  NVIDIA 470.63.01
- Kernel version:  5.13.19-2-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/nikseyy/76e5f7a04effdce2ed80a2581606cae2
- Proton version: 6.3-7

## I confirm:
- [✓] that I haven't found an existing compatibility report for this game.
- [✓] that I have checked whether there are updates for my system available.

[steam-389730.log](https://github.com/ValveSoftware/Proton/files/7406109/steam-389730.log)

**Comment by kisak-valve** [comment]
Hello @nikseyy, your video card has half the VRAM of the minimum requirements, which is where your performance trouble is coming from.

From your log:
```
err:vulkan:init_fs_hack_images vkAllocateMemory: -2
err:vulkan:wine_vkCreateSwapchainKHR creating fs hack images failed: -2
[...]
err:   D3D11SwapChain: Failed to recreate swap chain
```
This looks like where the game is having a hard time, and that is also from your system not meeting the game's listed minimum requirements.

In general, many games run with Proton on video cards with 1GB of vram are going to have a hard time.
