### ISSUE TITLE
Drone Racing League game not recongnizing the throttle input

### ISSUE THREAD

**Issue by mrlinux11** [ValveSoftware/Proton#5249]
I am using a Radiomaster TX16s remote as a joystick, under Windows it works fine, but under Linux using Proton the throttle is not recognized but all other inputs are.  I tested using https://gamerpad-test.com and it recognizing all the inputs.

**Comment by kisak-valve** [comment]
Hello @mrlinux11, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2910#issuecomment-950918398.
