### ISSUE TITLE
Using folder browser to select a mounted drive's path, emulated windows fails to show correct free space amount

### ISSUE THREAD

**Issue by hzulla** [ValveSoftware/Proton#5251]
This issue happened with Proton Experimental on Steam Built Oct 13 2021 19:47:24 / package version 1634158817.

Microsoft Flight Simulator (1250410) requires downloading a massive amount of 130+ GB of game data. The game launcher offers to browse the windows system's harddrives and folders to find a desired download location.

The Linux root filesystem `/` on my computer is small and only has 26GB free space.
There is a harddrive for game data mounted as `/storage` with 250+GB of free space for the game data, more than enough.

However, when I use the windows-styled file browser offered by the emulation to the game binary, it will allow me to choose the `/storage` path and will let me create a folder for the game data there, but then report the free space of the root filesystem for that path back to the game.

As a result, the game launcher will refuse to start the game, despite there being enough free space at the desired download location.

**Comment by kisak-valve** [comment]
Hello @hzulla, this is not an issue in Proton. Instead, it's part of the behavior of the Steam Linux Runtime - Soldier container environment which Proton 5.13 and newer is run inside.

The container environment is not allowed unlimited access to the host system, but you can ask for additional folders to be mounted into the container environment by setting the game's launch options to `STEAM_COMPAT_MOUNTS=/path/to/unexpected/folder %command%` (from https://github.com/ValveSoftware/steam-runtime/issues/393).

**Comment by hzulla** [comment]
Thanks for clarifying.

**Comment by smcv** [comment]
> The container environment is not allowed unlimited access to the host system, but you can ask for additional folders to be mounted into the container environment by setting the game's launch options to `STEAM_COMPAT_MOUNTS=/path/to/unexpected/folder %command%` (from [ValveSoftware/steam-runtime#393](https://github.com/ValveSoftware/steam-runtime/issues/393)).

Starting from today's beta of "Steam Linux Runtime - soldier", there is less need to do this. See ValveSoftware/steam-runtime/issues/470 for details.
