### ISSUE TITLE
Cyberpunk 2077 : nVidia GTX 1050 (2G) works without issue on the very lowest settings using GER Proton.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#5252]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

**Comment by ghost** [comment]
Just thought I would mention it.

**Comment by gardotd426** [comment]
Close this and move it to #4450. You don't open separate issues for this stuff.
