### ISSUE TITLE
make install fails w/ afdko 

### ISSUE THREAD

**Issue by mr-xeroth** [ValveSoftware/Proton#5260]
cloned from git, make install interrupts like these

vagrant rsync debian10
Platform: 4 CPUs, 7986 MB memory
==> debian10: Rsyncing folder: /home/user/proton/ => /home/vagrant/proton
==> debian10:   - Exclude: [".vagrant/", "vagrant_share"]
if [ ! -e "build-proton_6.3-local"/Makefile ]; \
	then mkdir -p "build-proton_6.3-local"; \
	(cd "build-proton_6.3-local" && ../proton/configure.sh --build-name="proton_6.3-local"); \
fi
Platform: 4 CPUs, 7986 MB memory
:: Configuring with build name: proton_6.3-local
!! Couldn't find 'afdko'. Install it and make sure that 'makeotf' is in your PATH or 'afdko makeotf' works.
!! Missing dependencies, cannot continue.
Connection to 127.0.0.1 closed.
Makefile:123: recipe for target 'configure' failed
make: *** [configure] Error 1
user@user-desktop:~/proton$ ^C
user@user-desktop:~/proton$ sudo makeotf
makeotf [Error] Could not find any of the default input font files ['font.ufo', 'font.pfa', 'font.ps', 'font.txt'].
user@user-desktop:~/proton$ 

care to elaborate??

**Comment by rawlingsr** [comment]
it looks like there is a sub-dependency that was updated out from under proton in a way that breaks the provisioning of the build environment VM. Modifying the Vagrantfile to explicitly install this dependency fixed the issue for me. 

Open Vagrantfile, in your favorite text editor, and add the following line right above `pip install afdko`.

```pip install zopfli==0.1.8```

next time you run vagrant up, it should provision correctly, and you should subsequently be able to build proton.

**Comment by ivyl** [comment]
This is fixed in experimental by using the python3 version of afdko https://github.com/ValveSoftware/Proton/commit/dd288bf872ddc739c975b01e6ec671b137974463

It will be included in the proton_6.3 branch with the next release.
