### ISSUE TITLE
Problem launching S.T.A.L.K.E.R.: Clear Sky

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#5262]
# Compatibility Report
- Name of the game with compatibility issues: S.T.A.L.K.E.R.: Clear Sky
- Steam AppID of the game: 20510

## System Information
- GPU: NVIDIA GeForce MX250
- Driver/LLVM version: NVIDIA 470.74
- Kernel version: 5.14.14-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): [link](https://gist.github.com/foresle/43e14755fafdab564ed60df7d05ec50e)
- Proton version: proton-6.3-7

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms  

Attempting to start the game opens an error window with the message: 'Your video card doesn't meet game requirements pixel shaders v1.1 or higher required'

## Reproduction

Attempting to start the game opens an error window with the message: 'Your video card doesn't meet game requirements 
Pixel Shaders v1.1 or higher required'

[steam-20510.log](https://github.com/ValveSoftware/Proton/files/7443335/steam-20510.log)

**Comment by kisak-valve** [comment]
Hello @foresle, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1166#issuecomment-954870002.
