### ISSUE TITLE
Spelunky 2: Renderer error creating DXGI factory (0x80004005)

### ISSUE THREAD

**Issue by KSXGitHub** [ValveSoftware/Proton#5265]
# Compatibility Report
- Name of the game with compatibility issues: Spelunky 2
- Steam AppID of the game: 418530

## System Information
- GPU: GP106 [GeForce GTX 1060 3GB]
- Driver/LLVM version: 
- Kernel version: 5.14.14
- Link to full system information report as [Gist](https://gist.github.com/KSXGitHub/cc93cfbd49dd6b19e0f16a3d8da24223):
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

The game does not launch. Instead, an error message box appears:

"Renderer error creating DXGI factory (0x80004005)"

## Reproduction

Enable Steam Play and launch the game.

## Additional information

> `sudo lshw -C display`

```
  *-display                 
       description: VGA compatible controller
       product: GP106 [GeForce GTX 1060 3GB]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:82:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nouveau latency=0
       resources: irq:54 memory:fa000000-faffffff memory:e0000000-efffffff memory:f0000000-f1ffffff ioport:f000(size=128) memory:c0000-dffff
```

**Comment by Leopard1907** [comment]
Nouveau driver is not supported i think. You should try with official NV prop driver.

**Comment by iWeaker** [comment]
Dont use NOUVEAU for gaming, its just bad

**Comment by kisak-valve** [comment]
Hello @KSXGitHub, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #4230, but it's fairly obvious that your issue is due to a general lack of Vulkan support in your video driver. Proton requires a spec-compliant Vulkan video driver for most games.
