### ISSUE TITLE
Mass Effect Legendary Edition: Mass Effect 1 no audio

### ISSUE THREAD

**Issue by Trombach** [ValveSoftware/Proton#5270]
# Compatibility Report
- Name of the game with compatibility issues: Mass Effect Legendary Edition
- Steam AppID of the game: 1328670

## System Information
- GPU: 5700 XT
- Driver/LLVM version: Mesa 21.2.3
- Kernel version: 5.14
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Trombach/9bc3b3fe7a5d0ba932e792627b63f120
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1328670.log](https://github.com/ValveSoftware/Proton/files/7447958/steam-1328670.log)

## Symptoms 

After Mass Effect 1 is launched there is no sound output

## Reproduction

1. Start Mass Effect Legendary Edition
2. Once the menu has loaded select Mass Effect 1
3. Mass Effect 1 launches but there is no sound output

NOTE: This issue can be fixed by deleting Local Files > Game > ME1 > Binaries > Win64 > OpenAL32.dll

**Comment by kisak-valve** [comment]
Hello @Trombach, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4823#issuecomment-955693425.
