### ISSUE TITLE
Proton Experimental bleeding-edge uses all CPU

### ISSUE THREAD

**Issue by kattjevfel** [ValveSoftware/Proton#5271]
As of `Proton: 1635544687 experimental-bleeding-edge-6.3-1836-20211029-paf96ce-w8a5bac-d1b1206-v430c77`, as soon as Proton Experimental is launched, even when performing first time setup or even in a games launcher, it will consume all CPU with `winedevices.exe` being the worst offender. This does not happen with "normal" Proton Experimental.

See screenshot below where I've launched The Witness with the previously mentioned build, its launcher should certainly not be enough to bring an AMD 3700x to its knees.

System information: https://gist.github.com/kattjevfel/9f8145327601b8449f5f1f30fdb1f53a

![2021-10-31_18-59-32](https://user-images.githubusercontent.com/6226312/139596265-38d50276-ef2e-4eb4-8937-6dd342613f79.png)

**Comment by kisak-valve** [comment]
Hello @kattjevfel, please be aware that bleeding edge is quite literal. There is no level of quality control or support this close to active development and snafus like this will occur.

**Comment by mathew2214** [comment]
can confirm. performance on this particular proton build is abysmal.

**Comment by NoXPhasma** [comment]
Can you guys try to disable esync and fsync and see if that reduces the load?

`PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 %command%`

**Comment by kattjevfel** [comment]
Disabling both esync and fsync greatly lowers the CPU usage for me.

**Comment by kisak-valve** [comment]
there's a futex2 / futex waitv mismatch noted at https://github.com/ValveSoftware/wine/pull/128#issuecomment-956223232. Only downstream kernels that are carrying the now obsolete futex2 patch set should be affected and `PROTON_NO_FSYNC=1` should be the workaround.

**Comment by kisak-valve** [comment]
https://github.com/ValveSoftware/wine/commit/a55a995020e09bfb844b12cac02351cf970287c7 in Proton Experimental 2021-11-01 should detect this scenario and disable fsync in this situation.
