### ISSUE TITLE
Resident Evil HD Remaster (Black Screen after Capcom Logo)

### ISSUE THREAD

**Issue by PokeRuto898** [ValveSoftware/Proton#5273]
# Compatibility Report
- Name of the game with compatibility issues: [Resident Evil HD Remaster](https://store.steampowered.com/app/304240/Resident_Evil/)
- Steam AppID of the game: [304240](https://store.steampowered.com/app/304240/Resident_Evil/)

## System Information
- Laptop: HP Laptop 15s-eq0564ng
- GPU: AMD Radeon™ Vega 8 Graphics (Integrated Graphics)
- CPU: AMD Ryzen™ 5 3500U with Radeon Vega Mobile Gfx
- Driver/LLVM version: Mesa 21.2.1
- Kernel version: Linux 5.13.0-7614-generic x86_64
- Full system information report as [Gist](https://gist.github.com/PokeRuto898/a766837b7b5ce272b4ff1555619ce058)
- Proton versions: 
```
v6.3-7
v5.13-6
v5.0
v4.11-13
v3.16-9
v3.7-8
```

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.

- [x] that I have checked whether there are updates for my system available.

## Symptoms
Black Screen after Capcom Logo

on v3.7-8 [Resident Evil HD Remaster](https://store.steampowered.com/app/304240/Resident_Evil/) crashes

## Reproduction

1. Start the game
2. Black Screen

## Logs
**None of the versions worked**
v6.3-7: [steam-304240.log](https://github.com/ValveSoftware/Proton/files/7449781/steam-304240.log)
v5.13-6: [steam-304240.log](https://github.com/ValveSoftware/Proton/files/7449795/steam-304240.log)
v5.0: [steam-304240.log](https://github.com/ValveSoftware/Proton/files/7449804/steam-304240.log)
v4.11-13: [steam-304240.log](https://github.com/ValveSoftware/Proton/files/7449807/steam-304240.log)
v3.16-9: [steam-304240.log](https://github.com/ValveSoftware/Proton/files/7449811/steam-304240.log)
v3.7-8: [steam-304240.log](https://github.com/ValveSoftware/Proton/files/7449817/steam-304240.log)

**Comment by kisak-valve** [comment]
Hello @PokeRuto898, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/296#issuecomment-955800126.
