### ISSUE TITLE
[feature request] per game whitelist

### ISSUE THREAD

**Issue by s3rg3** [ValveSoftware/Proton#528]
Hello,

For now, it is possible to add all windows games in the steam play parameters, but if you have a large library it could add a lot of games (hundreds,thousands).

i think the possibility to pick the games from the "GAMES" category of the library, would be better than bloating the "STEAMOS+LINUX" category with all the windows title.

it could be done by adding a steam play panel in the games properties.

**Comment by diraven** [comment]
You can still make a category of your own and add desired games there.

**Comment by s3rg3** [comment]
@diraven it is a solution when you have a low number of games on your library.

i have 952 games in total and 566 on linux, i don't think you would like to search 386 games on your library and add them one by one into a category.

**Comment by nstgc** [comment]
Still, I'm not sure how a per-game white list will help in a way that categorizing your games won't.

**Comment by s3rg3** [comment]
@nstgc if i have to categorizing all my 952 games it will take me hours, if i only want to test 10 games it will take only few minutes to white list them one by one, plus the other games i don't need will stay hidden in the "GAMES" section.

**Comment by kisak-valve** [comment]
Hello @s3rg3, this is a feature request for the steam client, not the Proton project.

The nearest open feature request is https://github.com/ValveSoftware/steam-for-linux/issues/5679.
