### ISSUE TITLE
Horizon Zero Dawn (1151640)

### ISSUE THREAD

**Issue by wgbcamp** [ValveSoftware/Proton#5280]
# Compatibility Report
- Name of the game with compatibility issues: Horizon Zero Dawn: Complete Edition
- Steam AppID of the game: 1151640

## System Information
- GPU: NVIDIA RTX 3060 Ti
- Driver/LLVM version: Nvidia 470.74
- Kernel version: 5.13.0-20-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/wgbcamp/feb809ce51b3e9df32df2d5197d616b5
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1151640.log](https://github.com/ValveSoftware/Proton/files/7470440/steam-1151640.log)

## Symptoms 
The game will randomly crash when I alt-tab out of the game and back in.

## Reproduction
1. Launch game.
2. Alt-tab to any other program.
3. Alt-tab back into game.

**Comment by kisak-valve** [comment]
Hello @wgbcamp, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4125#issuecomment-959968764.
