### ISSUE TITLE
Age of empires 4 does not work in Spanish

### ISSUE THREAD

**Issue by rodrigoGA** [ValveSoftware/Proton#5282]
# Compatibility Report
- Name of the game with compatibility issues: Age of empires 4
- Steam AppID of the game: 1466860

## System Information
- GPU:  RTX 3070ti
- Driver/LLVM version:  nvidia-driver-470
- OS: Ubuntu 20.04
- Proton version: Proton experimental

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

Proton log: [steam-1466860.log](https://github.com/ValveSoftware/Proton/files/7476365/steam-1466860.log)

# Symptoms
The game does not open after I put it in Spanish

## Reproduction

1. Install ubuntu on english.
2. Install steam and age of empires 4
3. Open age of empires 4 and work
4. change the language of the game to Spanish Latinamerica and the game doesn't work anymore,

it shows a black screen, the game mouse is visible, and it closes. I try:
* reinsall the game
* change the os language to spanish

**Comment by kisak-valve** [comment]
Hello @rodrigoGA, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5258#issuecomment-961198908.
