### ISSUE TITLE
Proton Experimental as of 4-Nov-2021 + Elite Dangerous launcher

### ISSUE THREAD

**Issue by alexzk1** [ValveSoftware/Proton#5284]
.NET Web-based launcher of Elite Dangerous pops some error, which when closed blocks all. That is new by today's update. Before it was ok. (using non-experimental just works too)

![image](https://user-images.githubusercontent.com/4589845/140449395-046716ba-35aa-4d18-90b1-eba8aee32d1a.png)

**Comment by kisak-valve** [comment]
Hello @alexzk1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/150#issuecomment-961855313.
