### ISSUE TITLE
Eac proton / steam's overlay

### ISSUE THREAD

**Issue by nda-cunh** [ValveSoftware/Proton#5286]
Hello I tried brawlhalla with these two options:
-noeac and without it

The game works well with both options.

however the steam overlay no longer works when eac is activated, and neither do the joysticks! I saw other report of this one on protonDb and on other computer.

**Comment by kisak-valve** [comment]
Hello @hydrasho, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/83#issuecomment-961859347.
