### ISSUE TITLE
[Whitelist] No Man's Sky (App ID:275850)

### ISSUE THREAD

**Issue by icf20** [ValveSoftware/Proton#529]
i played for few hours and everything goes ok also i did join a random multiplayer game even if on wine say it wont work

**Comment by Zero86Sk** [comment]
do you have an nvidia card? because its been documented the game crashes on AMD cards.

I have a GTX 1050ti and it works for me.

**Comment by Shished** [comment]
NMS uses openGL 4.5-compat. This is not yet implemented in stable Mesa.

**Comment by fazo96** [comment]
The game only works in windowed mode, or in borderless fullscreen but only at the native monitor resolution. Any other mode makes the screen black most of the time, but I'm not sure if it is a Proton issue.

Also some HUD elements flicker occasionally at a resolution higher than 1080p. There are no other issues and the performance is the same as in windows (Nvidia GTX 1080)

**Comment by kisak-valve** [comment]
Hello @icf20, #438 is blocking this whitelist request.
