### ISSUE TITLE
Hotdogs, Horseshoes, and Hand Grenades (7189098)

### ISSUE THREAD

**Issue by Frityet** [ValveSoftware/Proton#5290]
# Compatibility Report
- Name of the game with compatibility issues: Hotdogs, Horseshoes, and Hand Grenades (H3VR)
- Steam AppID of the game: 450540

## System Information
- GPU: GTX 1080
- Driver/LLVM version: NVIDIA 470.74 
- Kernel version: 5.4.0-86-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Frityet/6093640fd4e71a60a6657e9edd5521d7
- Proton version: Proton Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-450540.log](https://github.com/ValveSoftware/Proton/files/7489961/steam-450540.log)

## Symptoms 
Despite previously working one week ago, when I switch scenes from the main menu scene to any other scene, my wrist-menu (menu which shows all the options of the game, and allows switching of the scenes) is completely not there, and my quickbelt slots (Stores items on the players) are also missing.

Here is my game log: [output_log.txt](https://github.com/ValveSoftware/Proton/files/7489963/output_log.txt)

## Reproduction

Launch H3VR
Open a scene

**Comment by kisak-valve** [comment]
Hello @Frityet, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2836#issuecomment-962444825.
