### ISSUE TITLE
Shaders pre-cache download.

### ISSUE THREAD

**Issue by Galcian79** [ValveSoftware/Proton#5292]
Allow to exclude Linux native games from downloading shaders or, at least, allow to set option per game.

**Comment by kisak-valve** [comment]
Hello @Galcian79, Steam's shader pre-caching is managed by Steam, not Proton, and this feature request is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/6486.

Closing as invalid / duplicate.
