### ISSUE TITLE
ARK Survival evolved BE not working.

### ISSUE THREAD

**Issue by blastermaster77** [ValveSoftware/Proton#5298]
# Compatibility Report
- ARK: Survival Evolved:
- SteamGameId: 346110

## System Information
- GPU: Nvidia GTX 1060 6Gb
- Driver nvidia 470.63.01
- Kernel version: 5.14.10-1-MANJARO
- Link to full system information report as [Gist]:https://gist.github.com/blastermaster77/7801e099cdb0ee1a36a920afb32e3ef0
- Proton version: Proton Experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
After  updating to steam beta and using proton experimental 
the game does not lauch. I provided the proton log as indicated.

## Reproduction

[steam-346110.log](https://github.com/ValveSoftware/Proton/files/7500059/steam-346110.log)

**Comment by kisak-valve** [comment]
Hello @blastermaster77, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3218#issuecomment-963550931.

**Comment by blastermaster77** [comment]
> # Compatibility Report
> 
>     * ARK: Survival Evolved:
> 
>     * SteamGameId: 346110
> 
> 
> ## System Information
> 
>     * GPU: Nvidia GTX 1060 6Gb
> 
>     * Driver nvidia 470.63.01
> 
>     * Kernel version: 5.14.10-1-MANJARO
> 
>     * Link to full system information report as [Gist]:https://gist.github.com/blastermaster77/7801e099cdb0ee1a36a920afb32e3ef0
> 
>     * Proton version: Proton Experimental
> 
> 
> ## I confirm:
> 
>     * [ ]  that I haven't found an existing compatibility report for this game.
> 
>     * [ ]  that I have checked whether there are updates for my system available.
> 
> 
> ## Symptoms
> 
> After updating to steam beta and using proton experimental the game does not lauch. I provided the proton log as indicated.
> ## Reproduction
[steam-346110.log](https://github.com/ValveSoftware/Proton/files/7500050/steam-346110.log)
