### ISSUE TITLE
GTA 5 will eventually crash

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#5300]
# Compatibility Report
- Name of the game with compatibility issues: GTA IV
- Steam AppID of the game: 271590

## System Information
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/coreybruce/dcd2bec911594c9212d351ac2e7a3f98
- Proton version: Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

https://gitlab.com/coreybruce/gta-iv-log/-/raw/main/steam-271590.log

## Symptoms 
I have tested it with Proton 6.x.x and Proton Experimental and after a while of game play the game will crash tho wierdly enough all tho it says it's using Proton Experimental if you force it than from one testing for a session it didn't  crash.

## Reproduction
Run the game using either Proton 6.x.x or Experimental as your global steam play versions and leave the game not forcing a specific version. I did also test Proton-GE 6.19-2 and had the same issue.

**Comment by kisak-valve** [comment]
Hello @coreybruce, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-965086392.
