### ISSUE TITLE
Freesync running at half rate when framerate is above native refresh rate in Planetside 2 (and possibly some other games)

### ISSUE THREAD

**Issue by Atemu** [ValveSoftware/Proton#5314]
# Compatibility Report
- Name of the game with compatibility issues: Planetside 2
- Steam AppID of the game: 218230

## System Information
- GPU: RX 570
- Driver/LLVM version: Mesa 21.2.5
- Kernel version: 5.14.16-lqx1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Atemu/25baf10cbaf6db2ecf1492acbf237c3c
- Proton version: Experimental

Atemu/Nixpkgs@f8e92efb576a88d9b687499425cb0ac3cf170a62
Atemu/nixos-config@d7066af064997845240f63f469552faabfd04951

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-218230.log.zip](https://github.com/ValveSoftware/Proton/files/7532329/steam-218230.log.zip)

## Symptoms 

When controlling the character in-game and when the FPS are above or close to 144, my monitor drops to 1/2 refresh rate (so, 80Hz for 160fps for example). This is very unexpected and ruins responsiveness.

The bug does not happen in the loading screens weirdly (not just because of the higher framerate though).

I've only found one instance of another user experiencing this: https://www.reddit.com/r/linux_gaming/comments/p5lxzv/freesync_setting_refresh_rate_to_half_the_fps/

I don't own the games they've had issues with, so I can't confirm their findings but I thought it'd be better to keep this bug separate from [Planetside 2 compatibility](https://github.com/ValveSoftware/Proton/issues/5295).

## Reproduction

1. Have a Freesync monitor with LFC
2. Start game
2. Log in and launch using the workaround described in https://github.com/ValveSoftware/Proton/issues/5295
3. Select a character and press play
4. Have a framerate greater than monitor refresh rate
5. Open monitor OSD and observe refreshrate being roughly 1/2 of the fps

**Comment by kisak-valve** [comment]
Hello @Atemu, we're using one issue report per unofficially supported game title, and without logs or other usable evidence that there's a general issue affecting multiple games here, it's better to ponder this on a per-game basis. Sorry, but a second hand report on a different medium doesn't really help with troubleshooting.

I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5295#issuecomment-968095517.

**Comment by Atemu** [comment]
I see. You should perhaps mention that in a contributing guide or something (I couldn't find one).
