### ISSUE TITLE
EA  Sports  21 Steam  Online Problem 

### ISSUE THREAD

**Issue by Batamnxx** [ValveSoftware/Proton#5319]
When I try to play on Fifa 21 online I have a archlilinux distribution (archman) it keeps saying at the start of every game:
" An error has occured and you no long synced with the online match " and I'm not able to play any match online any help please

**Comment by kisak-valve** [comment]
Hello @Batamnxx, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4234#issuecomment-968377105.

**Comment by Batamnxx** [comment]
Can anyone help me please having these problem when I try to play online with FIFA 21
" An error has occurred and you no long synced with the online match " this message shows up. all help is greatly appreciated
