### ISSUE TITLE
No man's sky crashes after trying to start a game

### ISSUE THREAD

**Issue by moeraccoon** [ValveSoftware/Proton#5322]
# Compatibility Report
- Name of the game with compatibility issues: No man's sky
- Steam AppID of the game: 275850

## System Information
- GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT
- Driver/LLVM version: Mesa
- Kernel version: Linux 5.15.2-arch1-1 x86_64
- Link to full system information report as [Gist](https://gist.github.com/arkindal/48d894cea66249249f07997622b6aa31)
- Proton version: 4.11-13 (but tried multiple versions)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
I can't play, the game boots fine but when I try to actually start playing it crashes.

## Reproduction
Boot game
Click on play game OR multiplayer
Load a save file OR start a new one
The loading screen animation starts, it's very slow and extremely blurry, it shows it struggles to load the animation properly
Eventually an error screen pops out with this reference token: 79372_0x1E20A19_ST76561198032370916

## Extra non required things
I don't know if this can be of any help, but here's the output I get from the terminal if I start steam from it and try to start the game.
https://pastebin.com/YdRZAhry
I've been trying to fix this problem for days now, I looked in many forums and chats, including and not limited to the proton discord server. I also tried multiple versions of proton, the problem changes ever so slightly but the end result is always the same.
The different outcomes I can get are that the loading screen animation doesn't even try to start and the game crashes right away or that the game doesn't even start at all.

**Comment by kisak-valve** [comment]
Hello @arkindal, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-969292339.
