### ISSUE TITLE
proton-5.0: build-mingw-w64.sh ISL_URL no longer online 

### ISSUE THREAD

**Issue by addeps3** [ValveSoftware/Proton#5323]
Im not familiar with protons code but the ISL project has apperantly moved to sourceforge.io making the `vagrant up` command time out deo to connection issues.
The virtual machine is unable to update itself. 
This, I gather, is due to the gforge.infria.fr server been taken offline. 

Here is some information on the subject: https://github.com/crosstool-ng/crosstool-ng/issues/769 

https://github.com/crosstool-ng/crosstool-ng/pull/1614

Information for new sim-racers under Linux: 

Sadly, sim racing is still not mature under Linux, with wine-games. 
In order to use multi-head; proton 5.0 must be used, due to 5.13 breaking virtual desktop in ultra-wide screen.
Also, there is a proton-fix for Assetto Corsa that makes the FPS not drop when in-game UI-apps are used. Unfortunately, the proton-5.0 supplied by Steam does not have this fix enabled, forcing users to build proton-5.0 themselves. There have been a few bugs that broke manual build of proton-5, due to its age. 

Below is the ISL_URL bug, and solution, for DIY-ers.

`debian10: Connecting to isl.gforge.inria.fr (isl.gforge.inria.fr)|128.93.193.15|:80... failed: Connection timed out.
    debian10: Retrying.
    debian10: 
    debian10: --2021-11-15 21:11:40--  (try: 2)  http://isl.gforge.inria.fr/isl-0.21.tar.bz2
`

**Comment by addeps3** [comment]
~~Ahh, hold on, mightve forgot to check out submodules~~

nope, its borked

Edit: This is my edit to build-mingw-w64.sh 

`ISL_URL="https://sourceforge.net/projects/libisl/files/isl-$ISL_VER.tar.bz2"
#ISL_URL="http://isl.gforge.inria.fr/isl-$ISL_VER.tar.bz2"`

google groups thread that suggested the mirror https://groups.google.com/g/isl-development/c/JGaMo2VUu_8?pli=1

**Comment by aeikum** [comment]
Thanks for the information, but I think you're on your own here. We've redone the build system to no longer reference this URL, and we're not maintaining the 5.0 branch anymore.
