### ISSUE TITLE
Suspects: Mystery Mansion (1576060)

### ISSUE THREAD

**Issue by Francehelder** [ValveSoftware/Proton#5324]
# Compatibility Report
- Name of the game with compatibility issues: Suspects: Mystery Mansion
- Steam AppID of the game: 1576060

## System Information
- GPU:  AMD Radeon 540X
- Driver/LLVM version:  Mesa 21.2.5
- Kernel version:  5.15.2-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/Francehelder/e8e77bc4684e238a32a95993ceecf39c):
- Proton version: 6.3-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game freezes and crashes soon after

![image](https://user-images.githubusercontent.com/14970431/141880023-73e57be2-9c05-42c6-9bbe-392ba21f176e.png)

## Reproduction
Try start a match

Log file: 
[steam-1576060.log](https://github.com/ValveSoftware/Proton/files/7542677/steam-1576060.log)

**Comment by Francehelder** [comment]
Game now works! Voice chat too!!

**Comment by WhundAlt** [comment]
dead game :(
