### ISSUE TITLE
Marsupilami Hoobaventures(1586700) - Black Screen (Fixed) - Set Wine to Win7 please

### ISSUE THREAD

**Issue by rboxeur** [ValveSoftware/Proton#5325]
Hi,

To support this game in your white list, can you please modify Proton to set Wine to Win7 for this game.
That should help to avoid black screen when starting this game

Here is a video I did before purchasing this game

`<Link to video removed by moderator>`

This tiny fix works

Thanksm

**Comment by kisak-valve** [comment]
Hello @rboxeur, the third party build of Proton you used is legally problematic and can not be used as a reference for development of the mainline Proton project.

Feel free to open a compatibility report for how this game behaves with a mainline version of Proton, but this specific feedback is invalid.
