### ISSUE TITLE
Sonic and SEGA All Stars Racing, config dosn't run (34190)

### ISSUE THREAD

**Issue by Zero86Sk** [ValveSoftware/Proton#533]
The game runs fine from what i tested.

But running the config crashes, so you cant select details or resolution.

My Steam info:
https://gist.github.com/Zero86Sk/d629f657c1ae861c36657cdf238a7765

**Comment by kisak-valve** [comment]
Hello @Zero86Sk, this is already being tracked at #106. Closing as a duplicate.
