### ISSUE TITLE
The Witcher 3: Wild Hunt

### ISSUE THREAD

**Issue by rexhent** [ValveSoftware/Proton#5331]
# Whitelist Request
- Name of the game to be whitelisted: The Witcher 3: Wild Hunt
- Steam AppID of the game: 292030

## System Information
- GPU: GTX 1050 Mobile
- Driver/LLVM version: Nvidia 470
- Distro version: Manjaro Rolling
- Link to full system information report as [Gist](https://gist.github.com/rexhent/57cb62c585d280907cdc950a78dd8652):
- Proton version: Proton Experimental

## I confirm:
- [ Yes] that pressing the `Play` button in the Steam client is sufficient.
- [ No] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ No] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [ Yes] I haven't experienced any issues.
- [ No] There are no issues left open for this game.
- [ None] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @rexhent, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-974664363.

Side note: Due to its nature, Proton Experimental can not be a whitelist target.
