### ISSUE TITLE
Nintendo Switch Pro Controller Issues

### ISSUE THREAD

**Issue by Sterophonick** [ValveSoftware/Proton#5332]
Certain games running in Proton will crash when having a Nintendo Switch Pro Controller attached via USB. Not every game is affected, and I haven't seen this happen over Bluetooth.

### System Information
Distro: EndeavourOS Linux (Also happens on Manjaro)
GPU: Intel CometLake-U GT2 [UHD Graphics]
Driver: Mesa 21.2.5
Kernel: 5.15.2-zen1-1-zen 
Proton: 1637264280 experimental-6.3-20211118 (and earilier)

### Proton Logs
Quake Remastered (Didn't respond, Crashed on Exit)
[steam-2310.log](https://github.com/ValveSoftware/Proton/files/7575219/steam-2310.log)

Rivals of Aether (Crashed)
[steam-383980.log](https://github.com/ValveSoftware/Proton/files/7575220/steam-383980.log)

Rikki & Vikki (Crashed)
[steam-893690.log](https://github.com/ValveSoftware/Proton/files/7575221/steam-893690.log)

TY the Tasmanian Tiger (Working)
[steam-411960.log](https://github.com/ValveSoftware/Proton/files/7575223/steam-411960.log)

DOOM 64 (Crashed)
[steam-1148590.log](https://github.com/ValveSoftware/Proton/files/7575250/steam-1148590.log)

### Other notes
Outside of Proton, certain native Linux games will experience autonomous erratic controller inputs when a Nintendo Switch Pro Controller is attached over USB. A prime example would be DUSK. This also did not happen over Bluetooth.

**Comment by Blisto91** [comment]
Since you are on Arch derived distros I'm guessing you've looked at the [Arch wiki](https://wiki.archlinux.org/title/Gamepad#Nintendo_Switch_Pro_Controller_and_Joy-Cons).
Are you playing with steams built in driver or are you using `hid-nintendo` / `joycond` (i don't actually own a pro controller so just read up on it a bit)

Hopefully some of these controller issues will be sorted with switch controller driver support in kernel 5.16 :)

**Comment by Sterophonick** [comment]
I was using Steam's built-in driver.

**Comment by mpawlowski7** [comment]
Latest Steam beta updated today, Ubuntu 22.04 beta (happened also on Ubuntu 21.10 and previous Steam beta) gryo doesn't work with USB connection in non steam input games like Control or DOOM Eternal. 
Works fine in Horizon Zero Dawn which I think fully utilizes the steam input and native software.

**Comment by Sterophonick** [comment]
In kernel 5.16 the issues with native titles behaving unpredictably were fixed thanks to a new HID driver, and all of the SDL_JOYSTICK_HIDAPI issues were fixed/worked around in Proton, it's now just various issues with the steam client. :P
