### ISSUE TITLE
protons newer than 4.11 do not see my graphic card

### ISSUE THREAD

**Issue by legacychimera247** [ValveSoftware/Proton#5341]
hello,

so, seems that proton runtimes newer than 4.11 do not see my graphic card

to give you an example
if i open the Race 07 configuration tool with proton 4.11, my nvidia card is selected as rendering device
if open the configuration tool with proton from 5.x.x on to experimental, llvmpipe is the only rendering i do have

this is quite frustrating cause some games that only have compatibility in experimental (and i assume will then be merged in proton 6.x.x) are completely unplayable due to this, because of course llvmpipe (my cpu) is not powerful enough to render the thing alone

just in case, this is my configuration : fedora workstation 35, nvidia geforce 530 with proprietary 390 drivers installed, ssd, 8 gb of ram and latest stable steam client

**Comment by kisak-valve** [comment]
Hello @legacychimera247, the nvidia 390 series video driver is older than the support cutoff for Proton (https://github.com/ValveSoftware/Proton/wiki/Requirements#nvidia) and your video card is part of the Fermi generation of nVidia cards, which does not support Vulkan. This makes your system unsupported by Proton.

That said, you might have luck trying to set the game's launch options to `PROTON_USE_WINED3D=1 %command%`, which tells Proton to use wine's DirectX to OpenGL render path, but that launch option comes with a significant performance penalty and is also not considered supported.

Using Proton 5.13 and newer will most likely hit https://github.com/ValveSoftware/steam-runtime/issues/420.

**Comment by legacychimera247** [comment]
ok, and why then proton 4 correctly supports my graphic card?

EDIT : i was having issues with a game (raceroom that only got compatible now) cause since proton was not recognizing my card i had really unplayable performances even at lowest settings, don't really know what your command did, but now the game seems to be perfectly playable, thank you
