### ISSUE TITLE
Age of Empires III: Definitive Edition (933110)

### ISSUE THREAD

**Issue by tridoxx** [ValveSoftware/Proton#5342]
# Compatibility Report
- Name of the game with compatibility issues: age of empires 3 definitive edition 
- Steam AppID of the game: 933110

## System Information
- GPU: AMD ATI 30:00.0 Cezanne integrated
- Driver/LLVM version: latest mesa driver
- Kernel version: 5.13.0-7620-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: proton experimental

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
the multiplayer does not work after the encryption of the new African maps, the error is produced by the proton

## Reproduction

this is the error that show proton 

crypt:get_gnutls_cipher AES mode 1 with key length 64 not supported wine linux

**Comment by kisak-valve** [comment]
Previously mentioned on #3712.

**Comment by kisak-valve** [comment]
Hello @tridoxx, after reviewing #3712 and this issue report, I think it makes more sense to continue this discussion on the older compatibility report, so I've transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3712#issuecomment-977441036.
