### ISSUE TITLE
Arma 3 with ACRE2 mod (107410)

### ISSUE THREAD

**Issue by Tinter** [ValveSoftware/Proton#5344]
# Compatibility Report
- Name of the game with compatibility issues: Arma 3
- Steam AppID of the game: 107410

## System Information
- GPU: Nvidia Geforce RTX 2080ti
- Driver/LLVM version: nvidia-dkms 495.44-3 
- Kernel version: Linux 5.15.2-arch1-1 x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Tinter/05efcd93ef40951b0f9aa0218d9a063c
- Proton version: Proton 6.21-GE-2

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
An ACRE2 issue, the authors believe it to be Proton: https://github.com/IDI-Systems/acre2/issues/1157
When running the game with the ACRE 2 mod in singleplayer or local multiplayer, the game will freeze within a minute and become unresponsive, necessitating a sigkill. 

Logs are in the issue linked above.

**Comment by Tinter** [comment]
I know there is an issue for Arma 3, but this is specifically for the ACRE 2 mod, so I figured it really fit better in its own issue.

**Comment by kisak-valve** [comment]
Hello @Tinter, we're using one issue report per unofficially supported game title, and in general, mods for a game are still considered the same game, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2364#issuecomment-978118731.
