### ISSUE TITLE
Games installed on an NTFS partition won't launch with Proton.

### ISSUE THREAD

**Issue by Syvar** [ValveSoftware/Proton#5345]
To be more specific, native Linux games seem to work perfectly; only games launched with Proton have that issue.
I have followed this guide: [https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows](url) and the issue persists.
I have also tried reinstalling both the games (Alien Swarm, Alien Swarm: Reactive Drop and Hades) and Steam.
The thing is that I moved AS:RD to a btrfs partition and it worked but since I use Windows a lot and I can't just wipe my entire drive just now I prefer having the games installed on that NTFS partition.
System specs shouldn't matter but I will list them anyway.
CPU: Ryzen 1600X
GPU: AMD RX 580

**Comment by kisak-valve** [comment]
Hello @Syvar, using Proton with NTFS is known to be finicky and there are [several issue reports](https://github.com/ValveSoftware/Proton/issues?q=is%3Aissue+is%3Aopen+NTFS+-label%3A%22Game+compatibility+-+Unofficial%22+) tracking various issues with Proton interacting with NTFS partitions.

The general recommendation is to use a linux native filesystem with Proton.

Closing in favor of the older issue reports.
