### ISSUE TITLE
Age of Empires II Definitive Edition (813780) + Enhanced Graphics Pack DLC

### ISSUE THREAD

**Issue by lukurde** [ValveSoftware/Proton#5349]
# Compatibility Report
- Name of the game with compatibility issues: Age of Empires II Definitive Edition + Enhanced Graphics Pack (version 101.101.56005.0 7694700). **This bug doesn't occur in vanilla game, only with the Enhanced Graphics Pack DLC enabled**
- Steam AppID of the game: 813780

## System Information
- GPU: Device: Radeon RX550/550 Series (POLARIS12, DRM 3.42.0, 5.14.18-300.fc35.x86_64, LLVM 13.0.0) (0x699f)
- Driver/LLVM version: Mesa 21.2.5
- Kernel version:5.14.18-300.fc35.x86_64
- Link to full system information report as [Gist](https://gist.github.com/lukurde/33fb0b85662b7a0a4bcdccc02908267e):
- Proton version: 6.3-8 and Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. Well... I've found #3189 but that's for the vanilla version. 
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Game and Steam crashes completely while Advancing to Castle Age.

```
26547.400:010c:0110:trace:seh:dispatch_exception code=80000003 flags=0 addr=0000000140A0350C ip=0000000140A0350B tid=0110
26547.409:010c:0110:trace:seh:dispatch_exception  info[0]=000000000063e9b0
26547.409:010c:0110:warn:seh:dispatch_exception EXCEPTION_BREAKPOINT exception (code=80000003) raised
26547.409:010c:0110:trace:seh:dispatch_exception  rax=000000000063e9b0 rbx=000000005f0c2790 rcx=000000007bc692c0 rdx=000000000013f020
26547.409:010c:0110:trace:seh:dispatch_exception  rsi=0000000007ba0050 rdi=0000000007ba0050 rbp=000000000063e990 rsp=000000000063e958
26547.409:010c:0110:trace:seh:dispatch_exception   r8=0000000000000020  r9=000000000063e898 r10=0000000064d98080 r11=000000000063ee20
26547.409:010c:0110:trace:seh:dispatch_exception  r12=0000000000030070 r13=0000000040000000 r14=000000000063ee68 r15=0000000043b10b10
26547.409:010c:0110:trace:seh:call_vectored_handlers calling handler at 00000001447D7E01 code=80000003 flags=0
26547.409:010c:0110:trace:seh:call_vectored_handlers handler at 00000001447D7E01 returned ffffffff
26547.980:010c:0110:trace:seh:dispatch_exception code=c000001d flags=0 addr=0000000144835BC7 ip=0000000144835BC7 tid=0110
26547.980:010c:0110:warn:seh:dispatch_exception EXCEPTION_ILLEGAL_INSTRUCTION exception (code=c000001d) raised
26547.980:010c:0110:trace:seh:dispatch_exception  rax=000000000063e9f8 rbx=000000005f0c2790 rcx=000000007bc692c0 rdx=000000000013f020
26547.980:010c:0110:trace:seh:dispatch_exception  rsi=0000000007ba0050 rdi=0000000007ba0050 rbp=000000000063e990 rsp=000000000063e958
26547.980:010c:0110:trace:seh:dispatch_exception   r8=0000000000000020  r9=000000000063e898 r10=0000000064d98080 r11=000000000063ee20
26547.980:010c:0110:trace:seh:dispatch_exception  r12=0000000000030070 r13=0000000040000000 r14=000000000063ee68 r15=0000000043b10b10
26547.980:010c:0110:trace:seh:call_vectored_handlers calling handler at 00000001448A54F6 code=c000001d flags=0
26547.980:010c:0110:trace:seh:call_vectored_handlers handler at 00000001448A54F6 returned ffffffff
26549.036:010c:012c:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
26549.037:010c:012c:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (SIO_IDEAL_SEND_BACKLOG_QUERY)
26549.603:010c:0110:trace:seh:dispatch_exception code=80000003 flags=0 addr=0000000140A0350C ip=0000000140A0350B tid=0110
26549.607:010c:0110:trace:seh:dispatch_exception  info[0]=000000000063e9b0
26549.607:010c:0110:warn:seh:dispatch_exception EXCEPTION_BREAKPOINT exception (code=80000003) raised
26549.607:010c:0110:trace:seh:dispatch_exception  rax=000000000063e9b0 rbx=000000005f0c2790 rcx=000000007bc692c0 rdx=000000000013f020
26549.607:010c:0110:trace:seh:dispatch_exception  rsi=0000000007ba0050 rdi=0000000007ba0050 rbp=000000000063e990 rsp=000000000063e958
26549.607:010c:0110:trace:seh:dispatch_exception   r8=0000000000000020  r9=000000000063e898 r10=0000000064d98080 r11=000000000063ee20
26549.607:010c:0110:trace:seh:dispatch_exception  r12=0000000000030070 r13=0000000040000000 r14=000000000063ee68 r15=0000000043b10b10
26549.607:010c:0110:trace:seh:call_vectored_handlers calling handler at 00000001447D7E01 code=80000003 flags=0
26549.607:010c:0110:trace:seh:call_vectored_handlers handler at 00000001447D7E01 returned ffffffff
```
source: [steam-813780_AoE.log](https://github.com/ValveSoftware/Proton/files/7610893/steam-813780_AoE.log)

## Reproduction
Learn to Play -> William Wallace -> 6. Forge an Alliance -> Skip -> Gather at least 800 of food to be able to Advance to Castle Age (or just wait)-> left click on the Town Center (central building) -> left bottom corner last icon "III - Advance to Castle Age" -> game and Steam crashes

This is reproducible. I tested it multiple times, I can play for hours, have lots of army, building etc and it's fine. The moment I want to advance to the Castle Age (in that particular scenario) it crashes. Every single time.

**Comment by kisak-valve** [comment]
Hello @lukurde, in general, DLC considered a direct part of the game it adds content to, and we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3189#issuecomment-980475087.
