### ISSUE TITLE
Make steam save previous proton version

### ISSUE THREAD

**Issue by edvejak** [ValveSoftware/Proton#5350]
# Feature Request

## I confirm:
- [ ] that I haven't found another request for this feature.
- [ ] that I have checked whether there are updates for my system available that
      contain this feature already.

## References [optional] 
Hi.  I choose in steam play my game with proton 6.3.7. But after recent update I have discovered that my game runs with proton 6.3.8. I have very big problems with new proton version. Please make steam to save previous proton version and don't delete it from steam!

**Comment by kisak-valve** [comment]
Hello @edvejak, this topic is already being tracked at #3954. Closing in favor of the older issue report.

If you encounter a regression in Proton, please add a note on the existing compatibility report for the game so that Proton devs can look into what happened.
