### ISSUE TITLE
Elite dangerous crashes before launcher loads

### ISSUE THREAD

**Issue by ninjaijr** [ValveSoftware/Proton#5353]
# Compatibility Report
- Name of the game with compatibility issues: Elite dangerous
- Steam AppID of the game:359320

## System Information
- GPU:AMD ATI Radeon R9 390
- Driver/LLVM version: 
- Kernel version:5.14.18-1-MANJARO 
 

- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ninjaijr/eced37d0830c214ba04ce8e2d60b32c8
- Proton version:6.3.8, 6.21-GE-2

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
When i launch ED it starts to run but after about 10-30 sec it quits and the play button reappears. started in the last week or so

## Reproduction
install Elite dangerous
select the most recent stable proton or recent GE version
hit play.
game starts to load but then crashes

Steam log has been attached

[steam-359320.log](https://github.com/ValveSoftware/Proton/files/7612729/steam-359320.log)

**Comment by kisak-valve** [comment]
Hello @ninjaijr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/150#issuecomment-981089850.
