### ISSUE TITLE
Windows Security marks wordpad.exe as a trojan

### ISSUE THREAD

**Issue by derocs** [ValveSoftware/Proton#5354]
I dual boot windows and popos.  On my windows machine I ran windows security and got a severe warning.  

It identified the following as Tnega!ml

 Trash-1000\files\SteamLibrary\steamapps\common\proton 6.3\proton_dist.tar/lib/wine/wordpad.exe

Can you evaluate. Is this truly a malicious bit?  Or a false positive?

**Comment by Martinligabue** [comment]
upload it to virustotal and send the link

**Comment by kisak-valve** [comment]
Hello @derocs, https://github.com/ValveSoftware/Proton/issues/4738#issuecomment-814271235 is relevant here.

**Comment by derocs** [comment]
Ok, thanks!  That eases my mind!
