### ISSUE TITLE
Pathfinder: Wrath of the Righteous - mouse cursor not rendered correctly

### ISSUE THREAD

**Issue by errestan** [ValveSoftware/Proton#5355]
When running Pathfinder Wrath of the Righteous via Steam Proton, the mouse pointer is not rendered correctly. At least it looks different than it does under Windows. 

Tested with both NVIDIA Proprietary drivers and AMD Open Source derivers. Using Ubuntu 20.04, 21.10. Tested with the latest stable version of proton and the current experimental version. 

Windows:
![WotR-Windows](https://user-images.githubusercontent.com/12820466/143764651-88191949-8ac9-4700-877a-4e3bd9f1d0a0.png)

Linux:
![WotR-Linux](https://user-images.githubusercontent.com/12820466/143764470-43061a2e-4cc9-4808-80d3-3bab58f2f160.png)

**Comment by kisak-valve** [comment]
Hello @errestan, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5150#issuecomment-981092570.
