### ISSUE TITLE
"Hellblade Senua's Sacrifice" stopped to work after 2021 Update

### ISSUE THREAD

**Issue by spagoc** [ValveSoftware/Proton#5356]
On my PC, after the 2021 November update, "Hellblade Senua's Sacrifice" stopped to work giving the following error:

DX12 is not supported on your system. Try running without the -dx12 or -d3d12 command line argument.

I don't know if there is a workaround to solve the problem.
My conf:
Ryzen 3600, Nvidia 2060 Super GPU with v. 470.82.00 driver
Proton 6.3-8 and Proton Experimental
Ubuntu 21.10 with X11

**Comment by kisak-valve** [comment]
Hello @spagoc, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/943#issuecomment-981093173.
