### ISSUE TITLE
Add to blacklist

### ISSUE THREAD

**Issue by LeandroStanger** [ValveSoftware/Proton#536]
[Driver Booster 3 for STEAM](https://store.steampowered.com/app/403040/Driver_Booster_3_for_STEAM/?snr=1_7_7_230_150_21)
[Driver Booster 3 Upgrade to Pro (Lifetime)](https://store.steampowered.com/app/412090/Driver_Booster_3_Upgrade_to_Pro_Lifetime/)
[Driver Booster 5 for Steam](https://store.steampowered.com/app/735360/Driver_Booster_5_for_Steam/)
[Driver Booster 5 Upgrade to Pro (Lifetime)](https://store.steampowered.com/app/735370/Driver_Booster_5_Upgrade_to_Pro_Lifetime/)
[Driver Booster 4 for Steam](https://store.steampowered.com/app/545110/Driver_Booster_4_for_Steam/)
[Driver Booster 4 Upgrade to Pro (Lifetime)](https://store.steampowered.com/app/546360/Driver_Booster_4_Upgrade_to_Pro_Lifetime/)

**Comment by parkerlreed** [comment]
I don't think there's a blacklist... Just don't use the software.

**Comment by Leopard1907** [comment]
Lol.

There is no need for a blacklist though , Proton can be adjusted to only work with applications listed as a "Game" on Steam. 

@plagman
