### ISSUE TITLE
cant hold a key in psychonauts 2. It goes on repeat

### ISSUE THREAD

**Issue by voidplayer** [ValveSoftware/Proton#5360]
# Compatibility Report
- Name of the game with compatibility issues:psychonauts 2
- Steam AppID of the game: 607080

## System Information
- GPU: NVIDIA Corporation NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
- Driver/LLVM version: 4.6.0 NVIDIA 470.86
- Kernel version: 5.15.0-1-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.githubusercontent.com/voidplayer/6e80a5292be1dcc0a1569ac24e9b6d32/raw/9f537d4aee59a6031454a3554cdffc2ddd3728d5/gistfile1.txt
- Proton version: experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
You cant skip scenes with escape because it never hold the whole time. It shows like i were tapping the key

It happens the same thing with other buttons that need hold. Claravoyant, etc.. It works if you bound the power to second mouse button

![Peek 2021-11-28 10-34](https://user-images.githubusercontent.com/4019910/143782746-cd984716-59ec-47a6-9ef0-ea5714d28e96.gif)

## Reproduction
Try to hold a key

**Comment by kisak-valve** [comment]
Hello @voidplayer, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5119#issuecomment-981139906.

**Comment by voidplayer** [comment]
This has been fixed in latest update of the game

**Comment by voidplayer** [comment]
I saw an update yesterday, and it was fixed and i thought it worked already, but today its not working again
