### ISSUE TITLE
Allow Users To Manually Prompt First Install Script

### ISSUE THREAD

**Issue by ruineka** [ValveSoftware/Proton#5361]
After spending a few hours trying to get Far Cry 3 to work on my brothers computer (I got it working on mine, doing a bunch of tedious stuff with Uplay/Ubisoft Connect) I'm having the issue where Steam will not try to install all the game redistributables making it where the game won't run. It's annoying deleting the game, redownloading the game, or doing whatever random to get Steam to be like "hey, we're going to do the first time setup". So this leads to my request.

Steam should have an option to force a reinstall of redistributables to avoid these sort of headaches.

**Comment by kisak-valve** [comment]
Hello @ruineka, this feature request is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/6346. Closing as a duplicate.
