### ISSUE TITLE
Mount & Blade II: Bannerlord (261550)

### ISSUE THREAD

**Issue by serhanekicii** [ValveSoftware/Proton#5362]
# Compatibility Report
- Name of the game with compatibility issues: Mount & Blade II: Bannerlord 
- Steam AppID of the game: 261550

## System Information
- GPU: RX 560
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 21.2.5
- Kernel version: 5.15.5 (also tried with 5.10.82-1-lts)
- Link to full system information report as [Gist](https://gist.githubusercontent.com/serhanekicii/b851bc0714c6daa859fa672040c673f0/raw/8c07b3b76d84fa9c5dfdef61e6cce69db8d1dfde/steam_system-information)
- Proton version: Proton 6.3-8 (issue also producing with experimental)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms

Launcher starts but game crashes after clicking play. Link to log produced by Proton as [Gist](https://gist.github.com/serhanekicii/1b045dab8793077274c95e68d1ee60a0)

**Comment by kisak-valve** [comment]
Hello @serhanekicii, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3706#issuecomment-981630630.
