### ISSUE TITLE
The Witcher 3 freezes at the start of game 

### ISSUE THREAD

**Issue by x-crowbar-x** [ValveSoftware/Proton#5363]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher 3: Wild Hunt
- Steam AppID of the game: 292030

## System Information
- CPU:  AMD Ryzen 3 4300U with Radeon Graphics
- GPU: AMD RENOIR (integrated) 1 GiB.
- Driver:  AMD AMD RENOIR (DRM 3.42.0, 5.15.5-arch1-1, LLVM 13.0.0)
- Driver Version:  4.6 (Compatibility Profile) Mesa 21.2.5
- OpenGL Version: 4.6
- Kernel version: 5.15.5-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/x-crowbar-x/e47167df997085a2e385258374290ef1)
- Proton version: 6.3-8

## I confirm:
- [🗸] that I haven't found an existing compatibility report for this game.
- [🗸] that I have checked whether there are updates for my system available.

[steam-292030.log](https://github.com/ValveSoftware/Proton/files/7618308/steam-292030.log)

## Symptoms 
I started the game and everything was fine until I started a new game. I skipped the videos and it freezed after a couple of seconds in gameplay. It always freezes at the same spot. I ran it in the lowest settings and even chose the lowest resolution.  
Also, the laptop does not even get hotter and the fan is almost quiet, as if it doesn't try to load anything, but I can hear the sounds perfectly.

P.S. I found videos of people playing the game in 30-34 fps on my hardware on Windows, so it should also work on Linux.

## Reproduction
Open the game and click on "NEW GAME", skip the video, or don't, it does not matter.

**Comment by kisak-valve** [comment]
Hello @x-crowbar-x, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-981638275.
