### ISSUE TITLE
Red Dead Redemption 2 (1174180) - PopOS 21.04 - ERR_GTX_INIT - Failed to initialize graphic device. Please reboot or reinstall latest driver

### ISSUE THREAD

**Issue by deadmantfa** [ValveSoftware/Proton#5365]
# Compatibility Report
- Name of the game with compatibility issues: Red Dead Redemption 2
- Steam AppID of the game: 1174180

## System Information
- GPU: NVIDIA GeForce RTX 3080 
- Driver/LLVM version: 4.6.0 NVIDIA 470.86
- Kernel version: 5.15.2-051502-generic
- Link to full system information report as [System Information](https://gist.github.com/deadmantfa/67b878d9b21e69939c029fe56d5a9726)
- Proton version: Proton Experimental/ Proton 6.3.-8 / Proton 5.13-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1174180.log](https://github.com/ValveSoftware/Proton/files/7626923/steam-1174180.log)

## Symptoms 
Cannot run the game.

## Reproduction
Download the game
Let the installer finish
Then play

After Rockstar launcher and Rockstore social club are installed, an error will occur saying 
**Title**: ERR_GTX_INIT 
**Message**: "Failed to initialize graphic device. Please reboot or reinstall latest driver"

**Comment by kisak-valve** [comment]
Hello @deadmantfa, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-982764691.

**Comment by deadmantfa** [comment]
Thank you
