### ISSUE TITLE
Red Filter on my game proton [bug]

### ISSUE THREAD

**Issue by nda-cunh** [ValveSoftware/Proton#5367]
Hello, I have this bug on some game like Garrys mod, Spyro trilogy and sonic mania. but not on any other game. But I can't solve it! I tried to change DE (DESKTOP ENVIRONMENT) with: KDE-wayland, KDE-X11, Wayfire, Cinnamon. the problem therefore remains it does not come from the DE.

I also tried to use GaliumNine to see if the project came from WINED3D, but could not use galiumnine on proton; /

Help me ! (I am using wined3d because I am not compatible with Vulkan. Having an AMD ATI Radeon HD 5830)

![photo_2021-12-01_00-52-45](https://user-images.githubusercontent.com/40312793/144193431-f7fb56dc-4fa4-43c4-b801-5979caf92d33.jpg)

![photo_2021-12-01_00-21-28](https://user-images.githubusercontent.com/40312793/144193426-869b9f60-e4ba-4ccb-8e6d-649edd803c4e.jpg)

**Comment by nda-cunh** [comment]
I add, is it possible to have a native wayland proton? rather than the one on XWAYLAND, maybe that will fix it.

**Comment by kisak-valve** [comment]
Hello @hydrasho, Proton expects that Vulkan is available and the wined3d and gallium-nine render paths are not supported. Your VLIW5 video card is unsupported.

The best option for you is to reproduce this issue with vanilla wine, then report the issue on [wine's upstream bug tracker](https://bugs.winehq.org/).

**Comment by nda-cunh** [comment]
how can i run a game steam with wine vanillia ?
