### ISSUE TITLE
Wrong colors on videos

### ISSUE THREAD

**Issue by esistgut** [ValveSoftware/Proton#5370]
https://imgur.com/a/qCF7BZ2 this is the intro video of The Outer Worlds (the background should be black) but I get this kind of colors on a lot of videos. I can workaround this using `<Workaround removed by moderator>` but I would like to avoid it.

I'm on Arch, this is the proton log: https://gist.github.com/esistgut/791e7c7f83e9c2ce646d495ac01b666c

**Comment by kisak-valve** [comment]
Hello @esistgut, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4309#issuecomment-983736974. Additionally, the workaround you mentioned is legally problematic and has been removed.

**Comment by esistgut** [comment]
@kisak-valve this is not an issue specific to "The Outer Worlds". I have seen similar behavior in other games, like "Call of Cthulhu".

**Comment by kisak-valve** [comment]
Feel free to also add a note to #1464.
