### ISSUE TITLE
Dual Shock 3 no input in windows-only game

### ISSUE THREAD

**Issue by gamendez98** [ValveSoftware/Proton#5377]
#### Your system information

* Steam client version (build number or date): steam-manjaro 1.0.0.73-1
* Distribution (e.g. Ubuntu): Manjaro 21.2.0
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
My control(dual shock 3) is not detected by Dark Souls Remastered(proton 6.3-8) nor can I get any inputs. My control config is the default one in both the general steam config and the game.

The control works perfectly both in big picture mode and in proton-native games

#### Steps for reproducing this issue:

1. Download dark souls remastered
2. Use dual shock 3

#### Work-aronud

I already solved this issue for myself but I wanted to post this for feedback. I got it to work by checking only the **XBOX configuration support** and **Guide Button focuses steam** in the general steam controler configuration, and by selecting **force on** in the game. If this is necesary for all windows-only games(as i recall I had to do this before) why isn't this the default config.

**Comment by kisak-valve** [comment]
Hello @gamendez98, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1026#issuecomment-985522879.
