### ISSUE TITLE
After uninstalling amdpro-gpu and reinstall amd open source driver, no game can run in steam play.

### ISSUE THREAD

**Issue by gzqx** [ValveSoftware/Proton#5380]
Tested all proton version from experimental to 5.X. Fedora Plasma 34 running on Ryzen 5 3600 and Radeon 5700XT

(I don't know if it is a proton problem, but I spend a week looking around and can't solve it)

I used open source driver before, later installed amd's pro gpu. In both time, Proton works perfectly fine. 
Last week I uninstalled amdgpu-pro, and reinstalled amd gpu, but either game complain about can't find Directx 11 or 12, or run under 1~2 fps. However, native vulkan game like Dota, still runs perfectly fine.

Packages now on my computer with amd is:
```
➜  ~ sudo dnf list installed | grep amd
amdgpu-lib.x86_64                                21.20-1271047.el8                      @amdgpu                                             
amdgpu-pro-core.noarch                           21.20-1271047.el8                      @amdgpu                                             
clinfo-amdgpu-pro.x86_64                         21.20-1271047.el8                      @amdgpu                                             
comgr-amdgpu-pro.x86_64                          2.1.0-1271047.el8                      @amdgpu                                             
hip-rocr-amdgpu-pro.x86_64                       21.20-1271047.el8                      @amdgpu                                             
hsa-runtime-rocr-amdgpu.x86_64                   1.3.0-1271047.el8                      @amdgpu                                             
hsakmt-roct-amdgpu.x86_64                        1.0.9-1271047.el8                      @amdgpu                                             
libdrm-amdgpu.x86_64                             1:2.4.100-1271047.el8                  @amdgpu                                             
libdrm-amdgpu-common.noarch                      1.0.0-1271047.el8                      @amdgpu                                             
libwayland-amdgpu-client.x86_64                  1.18.0-1271047.el8                     @amdgpu                                             
libwayland-amdgpu-egl.x86_64                     1.18.0-1271047.el8                     @amdgpu                                             
libwayland-amdgpu-server.x86_64                  1.18.0-1271047.el8                     @amdgpu                                             
llvm-amdgpu-libs.x86_64                          1:12.0-1271047.el8                     @amdgpu                                             
mesa-amdgpu-dri-drivers.x86_64                   1:21.1.0-1271047.el8                   @amdgpu                                             
mesa-amdgpu-filesystem.x86_64                    1:21.1.0-1271047.el8                   @amdgpu                                             
mesa-amdgpu-libEGL.x86_64                        1:21.1.0-1271047.el8                   @amdgpu                                             
mesa-amdgpu-libGL.x86_64                         1:21.1.0-1271047.el8                   @amdgpu                                             
mesa-amdgpu-libGLES.x86_64                       1:21.1.0-1271047.el8                   @amdgpu                                             
mesa-amdgpu-libgbm.x86_64                        1:21.1.0-1271047.el8                   @amdgpu                                             
mesa-amdgpu-libglapi.x86_64                      1:21.1.0-1271047.el8                   @amdgpu                                             
mesa-amdgpu-libxatracker.x86_64                  1:21.1.0-1271047.el8                   @amdgpu                                             
mesa-amdgpu-vdpau-drivers.x86_64                 1:21.1.0-1271047.el8                   @amdgpu                                             
ocl-icd-amdgpu-pro.x86_64                        21.20-1271047.el8                      @amdgpu                                             
opencl-rocr-amdgpu-pro.x86_64                    21.20-1271047.el8                      @amdgpu                                             
teamd.x86_64                                     1.31-4.fc35                            @fedora                                             
texlive-examdesign.noarch                        9:svn15878.1.02-45.fc35                @fedora                                             
xorg-x11-amdgpu-drv-amdgpu.x86_64                1:24.1.0-1271047.el8                   @amdgpu                                             
xorg-x11-drv-amdgpu.x86_64                       21.0.0-1.fc35                          @fedora                                             
```

**Comment by kisak-valve** [comment]
Hello @gzqx, this reads like a system config issue, not a Proton issue. That said, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by gzqx** [comment]
Thanks for reply @kisak-valve ! The gist is following:
https://gist.github.com/gzqx/6bbf9576f2f9cbe1c58857c2cd150058

**Comment by kisak-valve** [comment]
Your system information tells us you should have 64 bit Vulkan through the driver that `/usr/share/vulkan/icd.d/radeon_icd.x86_64.json` points towards, however, when the extended diagnostics tried to exercise that render path, it could not use your video card (64 bit Vulkan is broken on your system). Does any 64 bit vulkan application like `vulkaninfo` see your video card?

I would expect that Fedora 34's repositories should be providing mesa 21.1.8, not mesa 21.2.5, which also doesn't match 21.1.0 in your package list. This reads like a frankenstein of a driver install, with a mismatch of Fedora 35 and RHEL8 parts forced onto Fedora 34.

**Comment by gzqx** [comment]
The vulkan info is as [this](https://gist.github.com/gzqx/f5391ff512e480cabcd456c0bb2c9844), I am not sure whether it sees the card.

For version, the problem occurred when I was using Fedora 34, and I updated to Fedora 35 yesterday and the problem remains. Sorry for the confusion.

**Comment by kisak-valve** [comment]
The short version of the output from vulkaninfo is that GPU 0 is lavapipe (llvmpipe) which is vulkan on the CPU and nothing else. That removes Steam and Proton from the picture. This is a system issue.

Sorry but I don't have any suggestions beyond reinstalling the video driver, which might be called `mesa-vulkan-drivers`.

**Comment by gzqx** [comment]
Thanks for you help, one last foolish question, I am wondering why is Dota2 still running 144 fps at all high spec.

**Comment by gzqx** [comment]
I find out that it is because AMD's newest opencl driver. It will link several *_dri.so to its own package which somehow breaks it through RHEL to fedora. Removing it and reinstalling mesa driver solves the problem.
