### ISSUE TITLE
Age of Empires IV (1466860) de-synchronization in multiplayer

### ISSUE THREAD

**Issue by jaafit** [ValveSoftware/Proton#5386]
# Compatibility Report
- Name of the game with compatibility issues: Age of Empire IV
- Steam AppID of the game: 1466860

## System Information
- GPU: Radeon R9 290/390
- Driver/LLVM version: Mesa 20.1.6
- Kernel version: 5.11.0-41-generic 
- Link to full system information report as [[Gist](https://gist.github.com/):](https://gist.github.com/jaafit/2b883c20e4d0f534c1ce80a8a1f2143e)
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Even after adding PROTON_LOG=1 to my own app shortcut AND to Steam's app properties, I could find no file in my ~ or any subdirectories named anything ending in 1466860.log  The closest matches were:
./.local/share/Steam/steamapps/compatdata/1466860
./.local/share/Steam/steamapps/shadercache/1466860
./.local/share/Steam/userdata/9056932/1466860
./.local/share/Steam/userdata/9056932/config/shaderhitcache/SteamSwarm/VulkanPipelinesV6_c051953b051a89e3/1466860
./.local/share/Steam/userdata/9056932/config/shaderhitcache/SteamSwarm/VulkanPipelinesV6/1466860
./.local/share/Steam/userdata/9056932/config/shaderhitcache/SteamSwarm/VulkanPipelinesV6_904f69d2b1b44b66/1466860
./.local/share/Steam/userdata/9056932/config/shaderhitcache/AMD RADV HAWAII (ACO)/f3b4f12dad1a098723d107cc63907e58/1466860
./.local/share/Steam/userdata/9056932/config/shaderhitcache/AMD RADV HAWAII/4ba41ce9d828c2d1751a273c27b2296f/1466860

## Symptoms 

Every time I play or observe a multiplayer game, the game will freeze at some point and announce a de-sychronization error.  Playing single-player is fine.  

![Screenshot_20211205_194832](https://user-images.githubusercontent.com/296158/144909610-3ec59bd0-f34a-49ac-9d6d-05684d814070.png)

## Reproduction

Play or observe a Multiplayer game for 3-5 minutes.  

I have tried reinstalling.  I tried resetting all settings to defaults.  Lowest graphics settings.  I contacted support and they auto-suggested opening ports, but I do see opponent units moving during the 3 minutes.  So packets are getting through. I did forward the ports they recommended but to no avail.

![Screenshot_20211206_100628](https://user-images.githubusercontent.com/296158/144909900-24e911b6-b318-472a-a4f9-1094ac3998e6.png)

**Comment by kisak-valve** [comment]
Hello @jaafit, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5258#issuecomment-987122693.
