### ISSUE TITLE
Help on a graphic card with proton

### ISSUE THREAD

**Issue by legacychimera247** [ValveSoftware/Proton#5387]
i have a question, i actually have a geforce 530, which has drivers 390, with no support for latests protons (from 5.13 and newer) since they use vulkan

Considering a 730 has support till official nvidia 470 drivers, would buying one of that help me in having a better compatibility with newer protons?

**Comment by kisak-valve** [comment]
Hello @legacychimera247, purchase decisions are out of scope for this issue tracker. Please use a community forum.

That said, specific to the GT 730, there's 3 variants of that card, two of those are Kepler generation, which is supported up to the nVidia 470 driver series like you expected. The third variant is Fermi generation, which is supported up to the 390 series video driver like your current card. The Kepler variants should have some support for Vulkan.
