### ISSUE TITLE
Little Busters! English Edition (635940)

### ISSUE THREAD

**Issue by GreekSummer** [ValveSoftware/Proton#5389]
# Compatibility Report
- Name of the game with compatibility issues: Little Busters! English Edition
- Steam AppID of the game: 635940

## System Information
- GPU: Nvidia GT 730
- Driver/LLVM version: nvidia 470.86
- Kernel version: 5.13.0-22
- Full system info: [link to Gist](https://gist.github.com/myronas34/7979a053916be611bb8c0c9432b3e753)
- Proton version: 6.3-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
1. The game will not start after restarting my computer.
2. The game will only start again at random if I launch it enough times. After it launches, there are no problems. Restarting the game itself after it begins to start again poses no problems until I restart my computer.
3. There is no pattern to when the game will decide to run again other than to install a completely new Proton version, but it will eventually stop working on the other Proton version too. Re-installing steam doesn't work, re-installing proton doesn't work, installing new kernel does until the game fails again much like it does with a newer proton version.

This ZIP file has two logs, one of when the game starts successfully, and of when it doesn't.
[littlebusters_logs_double_log.zip](https://github.com/ValveSoftware/Proton/files/7672419/littlebusters_logs.zip)

## Reproduction
Try starting the game. It will likely work the first time.

[](url)

**Comment by kisak-valve** [comment]
Hello @myronas34, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1802#issuecomment-988379471.
