### ISSUE TITLE
BeamNG.drive PBR textures are broken

### ISSUE THREAD

**Issue by Ember-ruby** [ValveSoftware/Proton#5390]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 21.3.1
- Kernel version: 5.15
- Link to full system information report: https://gist.github.com/MagentaPuppy/0301208a90e3cd3f55a335b44856079c
- Proton version: Latest experimental

## I confirm:
- [☑ ] that I haven't found an existing compatibility report for this game.
- [☑ ] that I have checked whether there are updates for my system available.

Log file
[steam-284160.log.zip](https://github.com/ValveSoftware/Proton/files/7672886/steam-284160.log.zip)

## Symptoms 

The new PBR textures only load as black
![image](https://user-images.githubusercontent.com/48266942/145137963-75975aa5-f028-4c9c-be55-a4d6d3627e8d.png)

## Reproduction

Open the game and enter a map with PBR textures (Jungle Rock Island, Utah, and Small Island) they will load as a  glossy black material rather than the proper texture

**Comment by kisak-valve** [comment]
Hello @MagentaPuppy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1237#issuecomment-988444929.

**Comment by Ember-ruby** [comment]
> Hello @MagentaPuppy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#1237 (comment)](https://github.com/ValveSoftware/Proton/issues/1237#issuecomment-988444929).

good to know.
