### ISSUE TITLE
STAR WARS: The Old Republic (1286830)

### ISSUE THREAD

**Issue by vasiliyaltunin** [ValveSoftware/Proton#5392]
# Compatibility Report
- Name of the game with compatibility issues: Star Wars The Old Republic (SWTOR)
- Steam AppID of the game: 1286830

## System Information
- GPU: GTX 1050 Ti
- Driver/LLVM version: 470.57.02
- Kernel version: 5.10
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/vasiliyaltunin/c631b87ea1108ab89f62c04d1fe90e7b
- Proton version: Experemental, 6.3-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Colors depth seems to low, in Experemental and 6.3-8 in 5.13-6 all looks just fine

## Reproduction

here i make screenshot to show color problems:
![experemental](https://user-images.githubusercontent.com/417082/145284178-faa2193c-0c15-4691-8da9-394ccecc22b2.png)
![5136](https://user-images.githubusercontent.com/417082/145284190-77669e07-0968-4660-b0bb-9a594e54a4bf.png)
[steam-1286830.log](https://github.com/ValveSoftware/Proton/files/7678954/steam-1286830.log)

As you can see in experimental colors looks like in old pc games you can clearly see it in places in shadows in torso

**Comment by kisak-valve** [comment]
Hello @vasiliyaltunin, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4326#issuecomment-989197768.
