### ISSUE TITLE
BIOSHOCK: Infinite

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#5395]
# Whitelist Request
- Name of the game to be whitelisted: BIOSHOCK: Infinite
- Steam AppID of the game: BioShock Infinite · AppID: 8870

## System Information
- GPU: nVidia GTX 1050 2GvRAM
- Driver/LLVM version: nVidia-495 Canonical Launchpad Graphics PPA
- Kisak PPA / Canonical-X Staging PPA
- Kernel: 5.13-23.23-Generic Canonical Proposed w/ nVidia Modules/ Objects/ Signatures
- Distro version: kDE Neon 20.04 w/ Backports and Proposed [ enabled] w/ Kwin X11 Compositor [ ON ]
- https://gist.github.com/username-murphy/cecc0bf365612034a71fc2ccc8aa1484
- Valve Steam Client - Beta / Valve Steam Linux Runtime / Sniper / Soldier -all- [ beta client ]
- Proton version: 6.3-8_101221

## I confirm:
- [ X ] that pressing the `Play` button in the Steam client is sufficient.
- [ X ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are NOT necessary to run the game.
- [X ] that no workarounds other than PROTON_* env variables are necessary.
- [ NO_PROTON_LAUNCH_OPTIONS_USED ]

## Issues
- [X ] I haven't experienced any issues.
- [X] There are no issues left open for this game.

**Comment by kisak-valve** [comment]
Hello @username-murphy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2700#issuecomment-990504156. (Link changed to user editable comment)
