### ISSUE TITLE
Microsoft Flight Simulator (1250410) [A32NX extension]

### ISSUE THREAD

**Issue by freijon** [ValveSoftware/Proton#5397]
# Compatibility Report
- Name of the game with compatibility issues: Microsoft Flight Simulator (A32NX extension). This is a **very popular** extension for MSFS. See https://flybywiresim.com/. I create a new compatibility report because it's unrelated to the main game which runs fine.
- Steam AppID of the game: 1250410

## System Information
- GPU: AMD ATI Radeon 5700 XT
- Driver/LLVM version: NAVI10, DRM 3.42.0, 5.15.6-gentoo, LLVM 13.0.0, 4.6 (Compatibility Profile) Mesa 21.3.1
- Kernel version: 5.15.6-gentoo
- Link to full system information report as [Gist](https://gist.github.com/freijon/4191b914c6707d66141224d2226b943e):
- Proton version: experimental-6.3-20211209

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When starting a flight (press the "Fly" button) the loading process starts and runs for a while. Suddenly the game crashes to Desktop. In the console I can see the following error:
`Unhandled exception: unimplemented function api-ms-win-crt-runtime-l1-1-0.dll.feclearexcept called in 64-bit code (0x000000007b0123be).`

[steam-1250410.log.tar.gz](https://github.com/ValveSoftware/Proton/files/7690312/steam-1250410.log.tar.gz)

## Reproduction
1. Install the A32NX extension for MSFS
2. Select the new Aircraft
3. Start the flight by clicking on the "Fly" button.

**Comment by kisak-valve** [comment]
Hello @freijon, we're using one issue report per unofficially supported game title including game mods, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-990929312.
