### ISSUE TITLE
GUI way to run Windows executables in Proton

### ISSUE THREAD

**Issue by Alex-Bujorianu** [ValveSoftware/Proton#5407]
# Feature Request

## Description 

A GUI way to (try to) run Windows executables inside a Proton prefix. This could be a right-click menu on a game entry in the Steam Library named “Run .exe…” This feature would be really helpful for the various mod managers out there, especially for games like Dragon Age: Inquisition (Frosty and DAI Mod Manager), Witcher 3 (Nexus) and the Skyrim games. Most games do not have Steam Workshop support. Some games, like Dragon Age: Origins, ship with their own mod manager.

Bonus points if this could be integrated with a file manager like Nautilus or Dolphin.

Currently, I have to use the command line to launch the DAO mod installer. It involves fiddling around with a bunch of paths.

```
#!/bin/bash
cd /mnt/2fc5a9a8-67ad-479f-ab77-2ca48c29ac8c/SteamLibrary2/steamapps/compatdata/47810/pfx
STEAM_COMPAT_DATA_PATH="/mnt/2fc5a9a8-67ad-479f-ab77-2ca48c29ac8c/SteamLibrary2/steamapps/compatdata/47810" WINEPREFIX=$PWD \
    /home/alex/.steam/root/steamapps/common/Proton\ 5.13/proton run \
    /mnt/2fc5a9a8-67ad-479f-ab77-2ca48c29ac8c/SteamLibrary2/steamapps/common/Dragon\ Age\ Ultimate\ Edition/bin_ship/DAUpdater.exe
```

## Justification 

Wine already does this, the issue is about integration with Steam games.

**Comment by kisak-valve** [comment]
Hello @Alex-Bujorianu, this feature request is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5766. Closing as a duplicate.
