### ISSUE TITLE
No Man's Sky (275850)

### ISSUE THREAD

**Issue by Bloodis94** [ValveSoftware/Proton#5409]
# Compatibility Report
- Name of the game with compatibility issues: No Man's Sky
- Steam AppID of the game: 275850

## System Information
- GPU: GTX 1080 AMP!
- Driver/LLVM version: 495.44
- Kernel version: 5.13
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/Bloodis94/3fe34ebfad674e004d1cd14baa9f2fb5
- Proton version: Proton 6.3-8
- [x] KVM

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Installing with both Proton 6.3-8 and Proton-6.21-GE-2 make the games run but without multiplayer. To make the multiplayer work i had to enable Win 7 prefix as suggested on the protondb page (https://www.protondb.com/app/275850) using protontricks.

The  report where i find the solution:
`
Using the custom version of Proton, I was able to run the game out of the box without issues. When I tried to play on multiplayer, it was unable to connect. After some research I found I had to set the prefix of the game in Proton to win7. So here’s some assistance on how to set these things up:
To download and install ProtonGE, use this: https://github.com/Termuellinator/Proton-Community-Updater (Be sure to download the Proton Golden Egg version, or ProtonGE.)
To download and set up ProtonTricks, use this article: https://simpler-website.pages.dev/html/2021/1/protontricks
To set the game’s prefix to win7, use this command: “protontricks 275850 win7” This will allow multiplayer to work.
`

## Reproduction
Install using the latest Proton version and try to connect to a friend in multiplayer.

[steam-275850.log](https://github.com/ValveSoftware/Proton/files/7715054/steam-275850.log)

**Comment by kisak-valve** [comment]
Hello @Bloodis94, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-994092715.

**Comment by RSerejo** [comment]
for my case the game don't work setting prefix with win7, and the problem looks like to be with mf and the game work using taskset -c 1-12 %command% but online still don't work.
[steam-275850.log](https://github.com/ValveSoftware/Proton/files/7872619/steam-275850.log)

**Comment by RSerejo** [comment]
i like use gamescope with on "No Man's Sky" to fix some "alt+tab" problem, but now mouse and keyboard don't work if i use it.
