### ISSUE TITLE
The Witcher 3: Wild Hunt (292030)

### ISSUE THREAD

**Issue by minionprocyk** [ValveSoftware/Proton#5417]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher 3
- Steam AppID of the game: 292030

## System Information
- GPU: AMD 5700XT
- Driver/LLVM version: 21.3.1
- Kernel version: 5.15.6-200.fc35.x86_64
- Link to full system information report as [Gist](https://gist.github.com/minionprocyk/c216ba4ed2a939f28a849f8c91e77c13):
- Proton version: proton-6.3-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-292030.log](https://github.com/ValveSoftware/Proton/files/7737449/steam-292030.log)

## Symptoms 
Game crashes on launch. This started happening after upgrading my CPU/Motherboard. 

## Reproduction
Launch Game

**Comment by kisak-valve** [comment]
Hello @minionprocyk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-997002874.
