### ISSUE TITLE
Brawlhalla not starting. Blackscreen on startup, crashes after ~10 seconds.

### ISSUE THREAD

**Issue by ArcSpammer** [ValveSoftware/Proton#5418]
I tried a couple different fixes/workarounds such as:
   - adding -noeac in the launch options, this did give me an application window, which I did not receive prior to this.
   - temporarily disabling some drivers so that the vulkan loader could only pick up my 
nvidia drivers.
   - Tried to use a lot of different proton versions, including ProtonGE.
   - I reinstalled the game once more. this time also used -windowed in the launch options

Error I got on proton log (on the last line):
"pid 18728 != 18727, skipping destrruction (fork without exec?)"

System information:
   - Archlinux 
   - KDE plasma
   - hp pavilion 15 laptop
   - 2 graphic chips: Nvidia GTX 1050 (Mobile), Intel(R) HD Graphics 630
   - Intel core i5-7300HQ

Using proton with steam (native), I don't know what else to try. I am an archlinux noob btw.

**Comment by kisak-valve** [comment]
Hello @ArcSpammer, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/83#issuecomment-997066134.
