### ISSUE TITLE
Arma 2 Color Shift

### ISSUE THREAD

**Issue by l4dbill8745** [ValveSoftware/Proton#5419]
I have been able to get Arma 2 working with a solution found in [Arma 2 (33900)](https://github.com/ValveSoftware/Proton/issues/1308#issuecomment-519400472). However I have encountered another issue with the game being completely red shifted.
![red shifted](https://user-images.githubusercontent.com/37612093/146626446-587a7c4f-a1a1-4514-b0b9-5d05935a07b8.png)
I am not sure if proton is the source of this issue but I am making issue reports on the softwares that I think could be responsible.

I am using Proton 6.3-8, on Manjaro 21.2c. I have not had this issue with any other games and I have not done anything to my knowledge that could be causing this.

**Edit with addition possibly helpful information**
Additionally, I have been running every game I play, with proton, with the PROTON_USE_WINED3D option because if I do not use this option the games crash instantly. I use this setting for every game and have not seen a similar effect in any.

**Comment by kisak-valve** [comment]
Hello @l4dbill8745, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1308#issuecomment-997131445.
