### ISSUE TITLE
Metro exosdus 

### ISSUE THREAD

**Issue by Jernel-dotcom** [ValveSoftware/Proton#5422]
# Compatibility Report
- Name of the game with compatibility issues: Metro exodus
- Steam AppID of the game: 181906

## System Information
- GPU: Vega56 AsusRog
- Driver/LLVM version: client glx vendor string: Mesa Project and SGI
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.2.5
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.2.5
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.2.5

- Kernel version: 5.14.21-2-MANJARO
- Proton version: Any version cause to failure 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Metro exodus crash with any proton version after working perfectly for long time

## Reproduction
Install Metro exodus on arch linux 
try to launch 

****** A crash report attached to the ticket.

[steam-412020.log](https://github.com/ValveSoftware/Proton/files/7739580/steam-412020.log)
[MetroExodus_error_report_211218-181906.zip](https://github.com/ValveSoftware/Proton/files/7739582/MetroExodus_error_report_211218-181906.zip)

**Comment by Jernel-dotcom** [comment]
![image](https://user-images.githubusercontent.com/60522029/146648889-b51f73e2-8537-4092-97df-43e175b2c4af.png)

**Comment by kisak-valve** [comment]
Hello @Jernel-dotcom, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2414#issuecomment-997232939.
