### ISSUE TITLE
Grand Theft Auto V stopped working after the last update

### ISSUE THREAD

**Issue by bkdwt** [ValveSoftware/Proton#5428]
# Compatibility Report
- Name of the game with compatibility issues: Grand Theft Auto V
- Steam AppID of the game: 271590

## System Information
- GPU: RX 550 2GB
- Driver/LLVM version: Mesa 21.3.2 
- Kernel version: 5.15.10-201.fsync.fc35.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/bkdwt/20775b55f70ba7d78373636a44afab06
- Proton version: 6.3.8

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

 I can't get this log

## Symptoms 
Can't run GTA V because Rockstar Social Launcher can't be installed. I think the last GTA V update has broken the game on Linux (I'm using Fedora 35 with the latest updates installed.)

## Reproduction

1- Install GTA V 
2- Start
3- RSL error
![Screenshot from 2021-12-21 02-12-27](https://user-images.githubusercontent.com/51302074/146877061-5d6e5bb7-d225-40b4-9593-a6f47b06802d.png)

**Comment by kisak-valve** [comment]
Hello @bkdwt, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-998787414.
