### ISSUE TITLE
Horizon Zero Dawn Complete Edition with new update 1.11 - Grass and foliage is artifacting

### ISSUE THREAD

**Issue by AgostinoA** [ValveSoftware/Proton#5429]
# Compatibility Report
- Name of the game with compatibility issues: Horizon Zero Dawn Complete Edition
- Steam AppID of the game: 1151640

## System Information
- GPU: RTX Nvidia 2070 Mobile Max-Q
- Driver/LLVM version: 495.44
- Kernel version:  5.14.15
- Proton version: experimental-6.3-20211220

##LOG
[steam-1151640.log](https://github.com/ValveSoftware/Proton/files/7752205/steam-1151640.log)

## I confirm:
- [x] that I have checked whether there are updates for my system available.

- [x] that I haven't found an existing compatibility report for this game.

## Symptoms 

Horizon Zero Dawn Complete Edition with new update 1.11
![issue](https://user-images.githubusercontent.com/28324952/146917319-4d4cac67-1807-428a-80a9-e78d7a6672a0.png)

When added upscaling (DLSS and FidelityFX SuperResolution). These bugs were born.

**Comment by kisak-valve** [comment]
Hello @AgostinoA, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4125#issuecomment-998788235.
