### ISSUE TITLE
Avicii Invector Issues on SteamPlay (Proton Experimental)

### ISSUE THREAD

**Issue by balokdecoy** [ValveSoftware/Proton#5430]
# Compatibility Report
- Name of the game with compatibility issues: Avicii Invector
- Steam AppID of the game: 15424

## System Information
- GPU: NVIDIA GeForce RTX 2060 Mobile
- Driver/LLVM version: 4.6.0 NVIDIA 470.86
- Kernel version: 5.15.8
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/balokdecoy/43b305139b4258294989b470ea0f7a26
- Proton version: Proton Experimental

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

## Symptoms 
I am able to install Avicii Invector and launch the game. The game starts with an intro song that introduces the player to the controls. I am able to play this intro. Once the intro is done, the user is sent to the main menu screen. Clicking on the Single Player option closes the menu options as if it's going to send the user to a new screen, but it gets hung up here. The game doesn't crash -- the Avicii Invector logo is still there, but the menu is gone, the music cuts out, and user is stuck here for good. The only recourse at this point is to return to the Steam page and force close the game. The game does not seem to produce a Proton Log report -- I tried this several times.

## Reproduction
To reproduce, run Avicii Invector using Steam Play and Proton Experimental. Play through the intro song, and once on the main menu page, click Single Player. Game should at that point get hung up and not proceed.

**Comment by kisak-valve** [comment]
Hello @balokdecoy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4678#issuecomment-998796775.
