### ISSUE TITLE
The Witcher: Enhanced Edition wont launch

### ISSUE THREAD

**Issue by glag15** [ValveSoftware/Proton#5431]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher: Enhanced Edition 
- Steam AppID of the game: 20900

## System Information
- GPU:  rtx 3080 ti
- Driver/LLVM version:  495.46
- Kernel version:  5.15.10-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/glag15/7e56710611d3f97780eca00efa2fd4d0
- Proton version: 6.3.8 (i did try with all available version as well as the GE and TKG)

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. i did but the problem wasn't the same and the solution didn't help
- [ ] that I have checked whether there are updates for my system available. system is updated

[steam-20900.log](https://github.com/ValveSoftware/Proton/files/7756430/steam-20900.log)

## Reproduction
press play
nothing happends

did try to look around and tried a few solutions to similar problems (from different games) also tried to diagnose with this https://wiki.archlinux.org/title/Steam/Troubleshooting but i am a linux newbie and couldn't solve it
also tried reinstalling the game/proton/steam/drivers

**Comment by kisak-valve** [comment]
Hello @glag15, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/255#issuecomment-998888529.
