### ISSUE TITLE
Deathloop crashes every time on first slab cutscene

### ISSUE THREAD

**Issue by KidDogDad** [ValveSoftware/Proton#5433]
# Compatibility Report
- Name of the game with compatibility issues: Deathloopo
- Steam AppID of the game: 1252330

## System Information
- GPU:  NVIDIA GeForce RTX 3060
- Driver/LLVM version:  NVIDIA 495.44
- Kernel version:  5.15.10.zen1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/KidDogDad/5659705c7b6187edd3be7d1e3feb3a44
- Proton version: Tried on Proton Experimental 12/20/2021 update, and on Proton Experimental Bleeding Edge (build ID 7918251)

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

 

## Symptoms 
The game launches and plays fine until the cutscene on picking up the first slab. It crashes reliably every time on this cutscene, rendering the game unplayable.

## Reproduction
On my system, this reproduces every time I get to that cutscene.

[steam-1252330.zip](https://github.com/ValveSoftware/Proton/files/7758809/steam-1252330.zip)

**Comment by kisak-valve** [comment]
Hello @KidDogDad, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5156#issuecomment-999151440.
