### ISSUE TITLE
World of Warships not launching

### ISSUE THREAD

**Issue by demib72** [ValveSoftware/Proton#5434]
# Compatibility Report
- Name of the game with compatibility issues: World of Warships
- Steam AppID of the game: 552990

Your system information
https://gist.github.com/demib72/2f915c3c97a29f3d722006f6dab0b173

Tried Proton Experimental, 6.3-8, 5.13-6, 3.16-9

Please describe your issue in as much detail as possible:
I recently reinstalled World of Warships and got it to work once. Afterwards, the game would start but fail to properly render the game and now it will not start at all. It might be related to ValveSoftware/Proton#5340, but one of the fixes like no_fsync option has made any difference for me.

Command and cli logs: https://gist.github.com/demib72/5c5cbbc74d10bd98ea9fad92c8e21689
Proton log: https://gist.github.com/demib72/bed3f92807e1a24cdeac80acc192ca3b

The Proton logs aren't telling me anything, so I think I need some help in figuring this out.

Steps for reproducing this issue:
1. Run World of Warships from Steam

**Comment by kisak-valve** [comment]
Hello @demib72, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/333#issuecomment-999583833.
