### ISSUE TITLE
Resizeable BAR  of Nvidia cause artifacts, ghosting and glitching 

### ISSUE THREAD

**Issue by AgostinoA** [ValveSoftware/Proton#5436]
I am testing many games. I have discovered very strange bugs that cause artifacts, ghosting and glitching depend on Resizeable BAR of Nvidia. I am testing with the same OS and driver, but with 2 different video cards.

- Nvidia RTX 3070 Max-Q (Resizeable BAR ON) Razer Blade 2021
- Nvidia RTX 2070 Max-Q (Resizeable BAR OFF) Razer Blade 2020
The Resizeable BAR is present only from the RTX 3000 series version.

Resizer Bar ON, some recent games like: Days Gone, Fallout 4, etc.
The problem is very obvious and truly causes epilesia.

With Nvidia's current drivers, the Resizeable BAR cannot be disabled. But with older versions, where the Resizeable BAR function was still off, these problems don't arise.
 
Does anyone know of a way to disable it from the Linux Nvidia driver, the Resizeable BAR?
There is a tweak to disable the Resizeable BAR from the Bios.
But from my bios, trying to activate CSM, the Resizeable BAR, it doesn't work. Moreover, on laptops the management of the basic bios is very limited.
It does not have a dedicated entry to disable it

# Razer Blade 2021 - System Information 
GPU: - Nvidia RTX 3070  Max-Q - Resizeable BAR ON
Driver/LLVM version:  Nvidia 495.44
Kernel version: 5.14.15
Proton version:  all

# Razer Blade 2020 - System Information 
GPU: - Nvidia RTX 2070 Max-Q - Resizeable BAR OFF
Driver/LLVM version:  Nvidia 495.44
Kernel version: 5.14.15
Proton version:  all

**Comment by kisak-valve** [comment]
Hello @AgostinoA, ~please list specific games you've tested~. Also, this issue should be reported to your video driver vendor.

**Comment by AgostinoA** [comment]
@kisak-valve  Okok, I also reported it here, to understand if other people have the same problem. I have if anyone knew how to work around the problem.

https://user-images.githubusercontent.com/28324952/147268927-f2ee85db-4f33-44ec-8471-c441b4ecc048.mp4

 I have already contacted both Razer and Nvidia, to ask for a way to disable or give in future versions the possibility to deactivate. But I think the problem is on Proton.

**Comment by NalianNalis** [comment]
@AgostinoA   have you tried to use at least for games that use VKD3D -proton this command in the launch options?

VKD3D_CONFIG=no_upload_hvv   

also if you have in bios the options for above 4G decoding  you can disable that.

**Comment by AgostinoA** [comment]
@NalianNalis Yes I tried but it doesn't solve, on my Razer 2021 BIOS there is no option to disable 4G decoding.  I contacted Razer to add this feature, but obviously it seems impossible that I add it just for me 😅.
On laptops, it is very difficult for them to add this option, but in fact it is very useful.

**Comment by ruineka** [comment]
> @NalianNalis Yes I tried but it doesn't solve, on my Razer 2021 BIOS there is no option to disable 4G decoding. I contacted Razer to add this feature, but obviously it seems impossible that I add it just for me sweat_smile. On laptops, it is very difficult for them to add this option, but in fact it is very useful.

I love the Razer Blade laptops and I own a few of them, but Razer when it comes to support is just bad. They are good at getting you to buy their product, but they don't care what you do or don't do with it after the point of sale. I do recall reading an article at one point that said Razer was looking for get feedback and suggestions on how to make their products more Linux friendly, but seeing how I have to disable a kernel feature to prevent a sleep loop I'm not sure if anything has come from it.

**Comment by AgostinoA** [comment]
Problem solved with the latest version of Proton
