### ISSUE TITLE
Cannot launch GTA V online after Contract update : Pop OS / Steam / Proton

### ISSUE THREAD

**Issue by DumpsterVirus** [ValveSoftware/Proton#5437]
# Compatibility Report
https://gist.github.com/DumpsterVirus/d426ef6e5c0a31a7a392a3fce7c25f95

## System Information
- Link to full system information report as [Gist](https://gist.github.com/):
- https://gist.github.com/DumpsterVirus/d426ef6e5c0a31a7a392a3fce7c25f95
- 
- Proton version: 6.3-8

## I confirm:
- [ # ] that I haven't found an existing compatibility report for this game.
- [ # ] that I have checked whether there are updates for my system available.

[ LOG in GitHub Gist link: 
https://gist.github.com/DumpsterVirus/d426ef6e5c0a31a7a392a3fce7c25f95

## Symptoms 
[Symptom shown in GitHub Gist Link: https://gist.github.com/DumpsterVirus/d426ef6e5c0a31a7a392a3fce7c25f95 

" An error has occurred.  Please make sure all instances of the Rockstar Games Launcher have been closed and try again.  If you continue to see this error, please visit https://support.rockstargames.com"

## Reproduction

<!--
1. The Steam AppID in the URL of the shop page of the game for `Grand Theft Auto V online' : the AppID is 271590
![Screenshot from 2021-12-23 10-53-12](https://user-images.githubusercontent.com/96588247/147269719-80165e37-a7ac-47df-aa47-c7d66a67afa1.png)

**Comment by kisak-valve** [comment]
Hello @DumpsterVirus, we're using one issue report per unofficially supported game title and this issue has already been evaluated https://github.com/ValveSoftware/Proton/issues/37#issuecomment-999114189.

Please use that issue report for future feedback on running Grand Theft Auto 5 with Proton.
