### ISSUE TITLE
Portal Knights locks up when in focus with Fullscreen and Windowed Fullscreen enabled.

### ISSUE THREAD

**Issue by ruineka** [ValveSoftware/Proton#5438]
If I press the windows key to open up my activities menu on Gnome the game works, but when I go to the actual game it's moving extremely slow and even freezing. I attempted Windowed Fullscreen as well as Fullscreen settings, I can play in Windowed mode.

I have to enable Vulcan in the settings to get the game to work and this issue is prominent in all versions of Proton 5.0-10 to Experimental.

**Comment by kisak-valve** [comment]
Hello @ruineka, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1009#issuecomment-1000465073.
