### ISSUE TITLE
Persona 4 Golden (1113000)

### ISSUE THREAD

**Issue by G10B** [ValveSoftware/Proton#5439]
# Compatibility Report
- Name of the game with compatibility issues: Persona 4 Golden
- Steam AppID of the game: 1113000

## System Information
- GPU: GTX 960M
- Driver/LLVM version: video-hybrid-intel-nvidia-470xx-prime
- Kernel version: 5.15.7-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/G10B/531ad185f678f72fea3af1ff70a19f23
- Proton version: 6.3-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. (I have found one other report but it's a different issue)
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game randomly freezes and stops working.

## Reproduction
It can happen anytime e. g. during the game loading screen, during the gameplay.

**Comment by kisak-valve** [comment]
Hello @G10B, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3982#issuecomment-1000483816.
