### ISSUE TITLE
Impossible to start an online session on Impossible Creature

### ISSUE THREAD

**Issue by RocketKevQt** [ValveSoftware/Proton#5443]
# Compatibility Report
- Name of the game with compatibility issues: Impossible Creatures
- Steam AppID of the game: 324680

## System Information
- GPU: Nvidia gtx 1050 2GO 
- Driver/LLVM version: nvidia 470
- Kernel version: 5.15.6-xanmod2-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/DIDIK3V1/1d1e21136602d337d72bfffd089a7c61
- Proton version: Proton Experimental 
-  Proton logs as [Gist](https://gist.github.com/) : https://gist.github.com/DIDIK3V1/a4622d0671e7f69c07ec23f2a078ce97
## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game crashes when starting an online party

## Reproduction
launch the game create an ic online account then create a party the first time it will do nothing and the second time it will crash with an error code :
![image](https://user-images.githubusercontent.com/54941168/147391029-8db051b7-619e-4637-be74-0c039e99d048.png)

**Comment by kisak-valve** [comment]
Hello @DIDIK3V1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1055#issuecomment-1001080066.
