### ISSUE TITLE
Proton 3.6-8 on Arch Linux: wine not found

### ISSUE THREAD

**Issue by TnTo** [ValveSoftware/Proton#5446]
Trying to use Proton 3.6-8 on Arch Linux (independently from the game) results in 
```
No such file or directory: '~/.local/share/Steam/steamapps/common/Proton 6.3/dist/bin/wine': '~/.local/share/Steam/steamapps/common/Proton 6.3/dist/bin/wine'
```
Checking local files doesn't solve the issue.

**Comment by arch-user-france1** [comment]
It works on Arch Linux. Maybe you should change the proton version (so steam downloads it again).

**Comment by TnTo** [comment]
Changing the version doesn't work but I was able to work around the issue by manually extracting the .tar file in the Proton folder.

**Comment by aeikum** [comment]
How are you running Proton? It is not intended for use outside of the Steam client. Don't try to run Proton's Wine directly.

**Comment by arch-user-france1** [comment]
As far as I understand is that he downloaded proton and unzipped it to the directory where proton usually is.

@TnTo, do may want to close the issue since it's solved.

**Comment by TnTo** [comment]
Maybe I express myself not clearly enough, sorry.

Even after checking file integrity or uninstalling and reinstalling proton 3.6 through stem, the folder `Steam/steamapps/common/Proton 6.3/dist/` has only the subfolder `share`.

The work around I found is to manually extract `Steam/steamapps/common/Proton 6.3/proton_dist.tar` into `Steam/steamapps/common/Proton 6.3/dist/`.

I follow your knowledge in evaluating if this work around is enough to close this issue or if more investigation is required (I don't know how to gather usefull infos but I'm available).

Thank you!

**Comment by arch-user-france1** [comment]
You may close the issue if you think that it don't happen again but if you think that  it must be fixed than feel free to leave  it open.

I don't know how we can get enough information to know what happened too.
