### ISSUE TITLE
Low color depth in games, visible in dark areas

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/Proton#5447]
I'm using Proton 6.3-8 with PROTON_USE_WINED3D=1 %command%, because I don't have proper Vulkan drivers.

Here's GTA San Andreas with Proton:
![20211225213906_1](https://user-images.githubusercontent.com/957339/147420891-b33a09b6-51a8-4d90-8fb1-73928751481d.jpg)
The same with vanilla Wine 7.0-rc2 (earlier versions were also fine):
![20211226150527_1](https://user-images.githubusercontent.com/957339/147420941-90254c13-30c0-4a11-acdb-1fd62883cc3c.jpg)

You can also see this issue in other bugreports, I presume they are using Vulkan by default https://github.com/ValveSoftware/Proton/issues/143#issuecomment-417058843

It's not limited to GTA, here's a screenshot of Tomb Raider Anniversary for example:
![20211226224712_1](https://user-images.githubusercontent.com/957339/147420932-0e218714-931a-4b4a-88ed-1ebec2a4c7f8.jpg)

**Comment by kisak-valve** [comment]
Hello @mtmkls, wine's DirectX to OpenGL render path is not supported in Proton, which makes this issue a non-starter.

**Comment by mtmkls** [comment]
I know you guys don't care, but Proton 7.0 fixed this color depth issue. Now the dynamic shadows on the characters are broken in Tomb Raider Legend with next gen graphics enabled....
