### ISSUE TITLE
Beam NG Driver Crash

### ISSUE THREAD

**Issue by Lolothepro** [ValveSoftware/Proton#5449]
BeamNG

- GPU:  GTX 1070
- Driver/LLVM version: nvidia 495
- Kernel version: 5.15
- Proton version: 6.0

[steam-284160.log](https://github.com/ValveSoftware/Proton/files/7781627/steam-284160.log)

The game does not start and closes instantly (only happens with DirectX)

**Comment by kisak-valve** [comment]
Hello @Lolothepro, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1237#issuecomment-1001725734.
