### ISSUE TITLE
Problems installing Proton | Some files no longer linked?

### ISSUE THREAD

**Issue by RealSourceOfficial** [ValveSoftware/Proton#5451]
# Compatibility Report
- Name of the game with compatibility issues: Proton 6.3
- Steam AppID of the game: 1580130

## System Information
- GPU: AMD Radeon RX 580
- Driver/LLVM version: [LLVM] LLVM 11.0.1, [Mesa] libglu1-mesa-dev (9.0.1-1)
- Kernel version: 5.10.0-10-amd64
- Link to full system information report as Gist: [Here](https://gist.github.com/RealSourceOfficial/0758d0f0256845a6047699fceadcb6c2)
- Proton version: 6.3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Unable to install Proton 6.3 itself. Cloning hangs on /gst-orc, using 
```git
git clone --recurse-submodules http/https/git://github.com/ValveSoftware/Proton.git Proton_6.3
``` 
or opening the Linux port of GithubDesktop ([Here](https://github.com/shiftkey/desktop/releases/download/release-2.9.3-linux3/GitHubDesktop-linux-2.9.3-linux3.deb)) and cloning it with `ValveSoftware/Proton`

## Reproduction

Run 
```git
git clone --recurse-submodules http/https/git://github.com/ValveSoftware/Proton.git Proton_6.3
``` 
Wait for it to reach the GST-ORC module 
```git
Cloning into 'home/source/Applications/Proton_6.3/gst-orc'...
```

Git is now stuck trying to clone, using `^C` is the only way to quit

On `^C`:
```git
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

## Notes

Checking the [homepage](https://github.com/ValveSoftware/Proton) seems to show `gst-orc @ 9901a96`, `gst-plugins-base @ ce69d10`, `gst-plugins-good @ 941312f`, `gstreamer @ eacb7aa`, and `vkd3d @ 5dc544e` unattached from the repository

**Comment by aeikum** [comment]
Yeah unfortunately the upstream FDO gitlab is broken right now :( https://gitlab.freedesktop.org/freedesktop/freedesktop/-/issues/407

Hopefully they will fix it soon. If you really need this now, you can clone over ssh (requires creating an FDO account and associating a public key with it) and point your submodules to that.
