### ISSUE TITLE
Wine 7.0-rc3 release fixes audio underflox bug

### ISSUE THREAD

**Issue by romulasry** [ValveSoftware/Proton#5456]
https://www.phoronix.com/forums/forum/software/desktop-linux/1298563-wine-7-0-rc3-released-with-22-more-fixes?p=1298574#post1298574

**Comment by kisak-valve** [comment]
Hello @romulasry, the Proton devs will rebase to a newer version of wine when they are ready. Until then, if you have specific commits for a Proton developer to ponder if its worth backporting, then that can be discussed, but just linking a random news article isn't useful.

**Comment by romulasry** [comment]
https://github.com/ValveSoftware/SteamOS/issues/647

**Comment by romulasry** [comment]
@kisak-valve 

This patch would be nice to backport if wine-staging doesn't have it already: https://source.winehq.org/git/wine.git/commit/033cd6013ea9852244b8d58360554c964a7bb540

That is the fix.
