### ISSUE TITLE
Elite Dangerous

### ISSUE THREAD

**Issue by srsimon7** [ValveSoftware/Proton#5459]
# Compatibility Report
- Name of the game with compatibility issues: Elite Dangerous Horizons
- Steam AppID of the game: 359320

## System Information
- GPU:  AMD Radeon RX 580 Series
- Driver/LLVM version:  Mesa 21.3.2
- Kernel version:  5.10.88-2-lts
- Link to full system information report as [Gist](https://gist.github.com/): 
srsimon7/gist:ff0674e9c173b0fcf4c77378ed17f180
- Proton version: 5.0.10

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms  This game has been working flawlessly since June, 2020. After the last Steam update it stopped launching. Pressing the Play button will attempt to launch the game then it stops and the Play button comes back on.

In looking through the Proton Log File, this came up as a potential problem... The entry point method could not be loaded due to Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

Any help you can provide is much appreciated. 

Thanks, S

**Comment by srsimon7** [comment]
Here's the gist link for the Proton Log file... gist:27a13fccbedd60f8fb8ee16390d305f8

**Comment by kisak-valve** [comment]
Hello @srsimon7, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/150#issuecomment-1003200358.
