### ISSUE TITLE
The Forest (242760)

### ISSUE THREAD

**Issue by juanandresdavila** [ValveSoftware/Proton#5461]
# Compatibility Report
- Name of the game with compatibility issues: The Forest
- Steam AppID of the game: 242760

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 21.3.2
- Kernel version: 5.15.12-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/ZAD4YTV/8847f2061dd981203328eefa5eda0bfe): 
- Proton version: Proton 6.3-8, 5.13-6, 5.0-10, 4.11-3, 4.2-9.

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-242760.log](https://github.com/ValveSoftware/Proton/files/7795263/steam-242760.log)

## Symptoms 
When I touch the "play" button, it prepares to launch the game, but nothing happens, it's like I'm playing but I don't see any window.
Sometimes, I did the same, but it automatically crashed.

I tried to run it with also the proton GE versions
Before, I disabled esync, followed some protondb instructions which have been given by users.

## Reproduction
Run the game, with steam & lutris after those errors.

**Comment by kisak-valve** [comment]
Hello @ZAD4YTV, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/411#issuecomment-1003376451.
