### ISSUE TITLE
[Spelunky 2] Crashes when the Switch Pro controller config is loaded

### ISSUE THREAD

**Issue by Munzu** [ValveSoftware/Proton#5462]
# Compatibility Report
- Name of the game with compatibility issues: Spelunky 2
- Steam AppID of the game: 418530

## System Information
- GPU: GeForce GTX 970
- Driver/LLVM version:  nvidia 495.46
- Kernel version: 5.15.12-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/Munzu/35ad8798966d53aba51a24d0803eb819):
- Proton version: Experimental, 6.3-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-418530.log](https://github.com/ValveSoftware/Proton/files/7796399/steam-418530.log)

## Symptoms 

Game crashes when the Switch Pro controller config is loaded

## Reproduction
1. Plug in Switch Pro controller via USB
2. Enable "Switch Pro Configuration Support" in Steam's controller settings.
2. Launch Spelunky 2
3. Game crashes when controller config is loaded.

This does not happen with my wired Xbox One controller.

Not sure how relevant but I have following setups as per [Arch Wiki](https://wiki.archlinux.org/title/Gamepad#Nintendo_Switch_Pro_Controller_and_Joy-Cons):
* `hid-nintendo-dkms` arch package is installed. Without it, I wasn't able to play Hollow Knight using my Switch Pro controller.
* https://wiki.archlinux.org/title/Gamepad#Steam udev rule

My Switch Pro controller works for other titles such as Hollow Knight, Super Meat Boy, and The Talos Principle.

**Comment by kisak-valve** [comment]
Hello @Munzu, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4230#issuecomment-1003390694.
