### ISSUE TITLE
Rollercoaster Tycoon crashes when saving

### ISSUE THREAD

**Issue by gituser823** [ValveSoftware/Proton#5463]
Hello,

I started RCT Deluxe on Proton Experimental.
It ran fine, but when I tried to save a game, the Windows saving dialogue came, but is hung and then the game ultimately crashed.

**Comment by kisak-valve** [comment]
Hello @gituser823, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/281#issuecomment-1003403026.
