### ISSUE TITLE
Middle-Earth Shadow of War

### ISSUE THREAD

**Issue by brzozowskia** [ValveSoftware/Proton#5464]
# Compatibility Report
- Name of the game with compatibility issues: Middle-Earth Shadow of War
- Steam AppID of the game: 356190

## System Information
- GPU: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti]
- Driver/LLVM version: 
- Kernel version: Ubuntu 21.10
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 6.3-8, proton experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

When the game goes to a cut scene or you try to access the character's army screen, the game freezes up almost instantly. Otherwise, the game has become quite playable.

**Comment by kisak-valve** [comment]
Hello @brzozowskia, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/135#issuecomment-1003451172.

**Comment by brzozowskia** [comment]
NVIDIA Driver 470.86
