### ISSUE TITLE
Can't launch games from VeraCrypt container

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#5466]
No games launch with Proton from my NTFS partition which is encrypted with VeraCrypt. Direct ports work just fine, and same can be said about applications used with Wine.
Proton log returns the following:

`wine: cannot find '/path/to/game.exe'`

**System info:**
Steam build date: 2021-12-16 22:39:26 (stable, not beta)
Distro/kernel: Arch/5.15.10-arch1-1
Driver: nvidia 495.46-6
Window system: x11
VeraCrypt mount options: uid=1000,gid=1000,umask=0000,fmask=0000,dmask=0000
Proton version: doesn't matter, issue exists in all of them
Wine version: 7.0rc3-1

**How to reproduce:**
1. Encrypt (NTFS, unsure if matters) partition with VeraCrypt
2. Try launching games with Proton

**Comment by kisak-valve** [comment]
Hello @sneakysnakeX299, Proton (and wine) are known to be finicky with NTFS partitions, regardless of encryption or not. This is a long standing issue [being tracked in several issue reports](https://github.com/ValveSoftware/Proton/search?q=ntfs+-label%3A%22Game+Compatibility+-+Unofficial%22&type=issues) and it's not really worth pondering if VeraCrypt causes additional trouble.

The general recommendation is to use a Linux native filesystem with Proton. Closing in favor of the older issue reports.
