### ISSUE TITLE
Slowness after hitting escape to go into settings while in game

### ISSUE THREAD

**Issue by brzozowskia** [ValveSoftware/Proton#5469]
# Compatibility Report
- Name of the game with compatibility issues: Star Wars Jedi Fallen Order
- Steam AppID of the game: 1172380

## System Information
- GPU: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti]
- Driver/LLVM version: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti]
- Kernel version: Ubuntu 21.10
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton Experimental, Proton GE

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

The game runs reasonably well but drops to very low frame rates after escaping to the settings menu even one time. It does this reliably but if i don't do this i can play the game uninterrupted for hours. Game will run cut scenes.

**Comment by kisak-valve** [comment]
Hello @brzozowskia, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3224#issuecomment-1003605204.
