### ISSUE TITLE
Game runs slowly or not at all on Ubuntu 21.10

### ISSUE THREAD

**Issue by brzozowskia** [ValveSoftware/Proton#5470]
# Compatibility Report
- Name of the game with compatibility issues: Borderlands GOTY Enhanced
- Steam AppID of the game: 8980

## System Information
- GPU:  NVIDIA Corporation GP107 [GeForce GTX 1050 Ti]
- Driver/LLVM version: 470.86
- Kernel version:  Ubuntu 21.10
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Game starts on some versions but runs very slowly when that happens. In contrast, ran smoothly on windows previously.  With some recent attempts to run it, does not run at all.

**Comment by kisak-valve** [comment]
@brzozowskia, again, we're using one issue per unofficially supported game title. Please search for the game's appid before opening new compatibility reports. Transferred to https://github.com/ValveSoftware/Proton/issues/598#issuecomment-1003615642.
