### ISSUE TITLE
Inscryption (1092790)

### ISSUE THREAD

**Issue by owentams** [ValveSoftware/Proton#5473]
#### Your system information

* Steam client version (build number or date): 1.0.0.74-1
* Distribution (e.g. Ubuntu): Garuda
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes, it says it's up to date

#### Please describe your issue in as much detail as possible:
What should happen: game launch and run
What happens: game starts to launch, throws the following error message (in later versions of Proton) and quits.
`Failed to initialize graphics.
Make sure you have DirectX 11 installed, have up to date drivers for your graphics card and have not disabled 3D acceleration in display settings.
InitializeEngineGraphics failed`

I have tried:
- Changing Proton versions in Steam: 4.11-5.13 doesn't throw the error msg, it just stops; 6.3-8 & Experimental throw the error msg.
- Using launch option PROTON_USE_WINED3D=1 (no error msg, just stops launching)
- Disabling Steam Overlay & Shader Pre-caching [per the ProtonDB page](https://www.protondb.com/app/1092790) (no change)

#### Steps for reproducing this issue:

1. Install Inscryption.
2. Run Inscryption on the following machine specs: https://gist.github.com/owentams/093d67ce614b0df2f29383c4882da420

Thanks!
edit: fixed link to gist with specs
edit2: added steam log using the PROTON_LOG launch option and [steam system info gist ](https://gist.github.com/owentams/0cbb9c3d8dc58c7e1d8481e541368fcc)
[steam-1092790.log](https://github.com/ValveSoftware/Proton/files/7799284/steam-1092790.log)

**Comment by kisak-valve** [comment]
Hello @owentams, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report. The video drivers for your Ivybridge generation Intel graphics provides an incomplete implementation of Vulkan, which makes your system unsupported by Proton in general. Graphical quirks and crashes are expected on your system.

That said, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by owentams** [comment]
> Hello @owentams, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report. The video drivers for your Ivybridge generation Intel graphics provides an incomplete implementation of Vulkan, which makes your system unsupported by Proton in general. Graphical quirks and crashes are expected on your system.
> 
> That said, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Hey, thanks so much for responding. I've added the requested info to the original post, I hope. Still new to GitHub. And yeah, I'm not expecting perfection, but I was hoping since Pony Island worked well enough, Inscryption would too (same dev, and I think same rendering software, Unity).

**Comment by kisak-valve** [comment]
In your system information, https://gist.github.com/owentams/0cbb9c3d8dc58c7e1d8481e541368fcc#file-gistfile1-txt-L2739 tells us that you have no Vulkan driver installed. I would add the `vulkan-intel` and `lib32-vulkan-intel` system packages (or equivalent) so that Proton can at least try to use the incompete Vulkan driver and see what happens.

The alternative is to test having the game's launch options set to `PROTON_USE_WINED3D=1 %command%` which tells Proton to use wine's DirectX to OpenGL render path, but you've already tried that and the launch option is not considered supported. You can also look at game engine options like `-force-glcore` (try it after or without `%command%` in the game's launch options) from https://docs.unity3d.com/Manual/PlayerCommandLineArguments.html, but it's possible that the game's dev(s) have not tested using the game with other render backends.

**Comment by owentams** [comment]
ok, i yay'd 'vulkan-intel' and 'lib32-vulkan-intel' and attempted to launch the game using Proton 4.11 and...it works!!!! Thank you so much, I didn't realize I didn't actually have any vulkan drivers installed! this might actually help a couple other games work, too.

Will post again if I run into further issues that I can't deal with, but this looks to be solved!
