### ISSUE TITLE
The Elder Scrolls V: Skyrim Special Edition crashes when entering the museum in Dawnstar entering (house of Silus Vesuius)

### ISSUE THREAD

**Issue by nvaert1986** [ValveSoftware/Proton#5474]
Basically as the title suggests. As soon as you enter the museum in Dawnstar, the game crashes. I've tried both Proton and Proton-GE builds, but both are having the same behavior. The rest of the game is working completely fine.

Using kernel 5.15.x with nvidia-drivers-495.46

**Comment by kisak-valve** [comment]
Hello @nvaert1986, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4#issuecomment-1003757249.
