### ISSUE TITLE
Farcry 5 shows black screen

### ISSUE THREAD

**Issue by Codeatron5000** [ValveSoftware/Proton#5479]
# Compatibility Report
- Name of the game with compatibility issues: Farcry 5
- Steam AppID of the game: 552520

## System Information
- GPU: RX 5600
- Driver/LLVM version: Mesa 21.3.3-2
- Kernel version: 5.15.12.arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Codeatron5000/0136c0de2061f4cff8d07bfc0cbdd7e6
- Proton version: 6.3-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
[steam-552520.log](https://github.com/ValveSoftware/Proton/files/7801459/steam-552520.log)

## Symptoms
The game launches and I can hear the title screen but only a blank screen is visible.

## Reproduction
- Download Farcry 5
- Click Play
- Sign in to Ubisoft
- Wait for game to launch
- Notice blank screen

**Comment by kisak-valve** [comment]
Hello @Codeatron5000, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2356#issuecomment-1004105343.

**Comment by Codeatron5000** [comment]
Good to know

Thank you.
