### ISSUE TITLE
(447040) Watch_Dogs 2

### ISSUE THREAD

**Issue by elijahr2411** [ValveSoftware/Proton#5489]
# Compatibility Report
- Name of the game with compatibility issues: Watch_Dogs 2
- Steam AppID of the game: 447040

## System Information
- GPU: AMD Radeon 6700 XT
- Driver/LLVM version: amdgpu 21.0.0-2
- Kernel version: 5.15.13-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/elijahr2411/3c2bf1113d18a0bcfaf0da1b092cba55
- Proton version: 6.3-8 or experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-447040.log](https://github.com/ValveSoftware/Proton/files/7834479/steam-447040.log)

## Symptoms 
Splash screen opens and loads uplay, then screen goes black as if the game is going to launch but immediately closes. Steam still lists the game as running

## Reproduction
Start the game

**Comment by kisak-valve** [comment]
Hello @elijahr2411, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/172#issuecomment-1008301677.
