### ISSUE TITLE
Just Cause 3 stuttering with Proton 6.3-8

### ISSUE THREAD

**Issue by ayush-sharma** [ValveSoftware/Proton#5491]
Hi,

I'm playing Just Cause 3 on Ubuntu 20.04 with Steam and I'm experiencing a lot of stuttering with Proton 6.3-8 and Proton Experimental.

# Compatibility Report
- Name of the game with compatibility issues: Just Cause 3
- Steam AppID of the game: 225540

## System Information
- GPU: Geforce GTX 980 TI AMP Edition
- Driver/LLVM version: Nvidia 470
- Kernel version: 5.11.0-40-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ayush-sharma/7a780dbad970613bfed2033217bcb96f
- Proton version: 6.3-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Lots of stuttering while playing the game on low and high settings.

**Comment by kisak-valve** [comment]
Hello @ayush-sharma, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/682#issuecomment-1008913206.

**Comment by ayush-sharma** [comment]
Just to update, the game actually works fine. No crashes. I'm able to log in and play normally. It's just that there is stuttering during gameplay when moving around. Happy to attach logs if needed.
