### ISSUE TITLE
Dark Souls: Remastered unable to use Dualsense controller

### ISSUE THREAD

**Issue by Lodger** [ValveSoftware/Proton#5492]
# Compatibility Report
- Name of the game with compatibility issues: Dark Souls: Remastered
- Steam AppID of the game: 570940

## System Information
- GPU: GTX 1080 TI
- Driver/LLVM version: Nvidia 470.94
- Kernel version: 5.15.11
- Link to full system information report as [Gist](https://gist.github.com/Lodger/de82a6fb900eca30154922d590e2f96a):
- Proton version: 6.3-8

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
I'm unable to use a Dualsense controller with Dark Souls: Remastered. These are my current controller settings: 
![shot-2022-01-12_13-43-11](https://user-images.githubusercontent.com/24976475/149202158-3745dbda-9be2-41ad-8b8f-a1cde807b5c5.jpg)

The game behaves simply as if no controller is plugged in; no input from the controller affects the game at all, except for the touch pad, because that also controls the mouse. Portal 2 works flawlessly with the same settings (although it doesn't use Proton), so I'm certain the controller works. Enabling Steam Input in the properties tab does not fix the problem, nor does big picture mode. I haven't tested this with any other controllers because I don't have any.

## Reproduction
As far as I know, just try to use a Dualsense controller with Dark Souls: Remastered.

**Comment by kisak-valve** [comment]
Hello @Lodger, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1026#issuecomment-1011372084.
