### ISSUE TITLE
No Man's Sky - Win7 and online problem

### ISSUE THREAD

**Issue by RSerejo** [ValveSoftware/Proton#5496]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Reproduction

[steam-275850.log](https://github.com/ValveSoftware/Proton/files/7875075/steam-275850.log)

[steam-275850.log](https://github.com/ValveSoftware/Proton/files/7875074/steam-275850.log)

The game needs to run in windows 7 mode for the mulltplayer to work, but then the game doesn't work, for that I need to put "taskset -c 1-12 %command%" for the game to run, it seems to be some old problem with "mf" and even so the online is not working.

**Comment by kisak-valve** [comment]
Hello @RSerejo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-1013696181.
