### ISSUE TITLE
Mesa PPA for Ubuntu 22.04

### ISSUE THREAD

**Issue by JokerGermany** [ValveSoftware/Proton#5499]
pls continue your great work on the Mesa PPA for Ubuntu 22.04, when it's released.
( https://github.com/ValveSoftware/Proton/wiki/Requirements#amdintel )

**Comment by kisak-valve** [comment]
Closing as out of scope for this issue tracker.

**Comment by JokerGermany** [comment]
Where is the right scope?

**Comment by JokerGermany** [comment]
> Closing as out of scope for this issue tracker.

Where is the right scope?
