### ISSUE TITLE
Keyboard/Mouse input doesn't work in rendered games

### ISSUE THREAD

**Issue by TrevtheForthDev** [ValveSoftware/Proton#55]
OS: NixOS 18.03.133126.4df3426f5a5 (Impala) x86_64
Drivers: mesa

I don't know what specifics I should give but input doesn't work with any games at all. If I run something graphical like the Creation Kit however, input and everything works perfectly. I can't test controllers but I tried an external keyboard and nothing changed. 
Games Tested:
Skyrim(Vanilla)
Star Wars Battlefront 2(2005)
Mount & Blade Demo (This one works a little bit but pressing buttons to load a new game or anything doesn't work, the mouse just flickers)
TESIII: Morrowind doesn't even work, crashes once it opens, though idc because OpenMW

**Comment by TrevtheForthDev** [comment]
Oh also, In-Game Overlay still works in all games, Shift+Tab still opens it, though no game takes input.

**Comment by salty-horse** [comment]
For me the keyboard doesn't work only in some games. The mouse always works in the games I tested.
Keyboard is not responsive in these games: (it's easiest to test the ESC key)
* Twilight Struggle
* Campfire Cooking

**Comment by asdf1234-deleted** [comment]
Can confirm this affects me in Skyrim: intel i7, Nvidia GTX 1080, but after hitting Play on the splash screen, I do not have proper mouse movement.

**Comment by TrevtheForthDev** [comment]
The only game that has responsive input for me is Fallout Shelter. None of the other whitelisted games I own work. Am about to try Subnautica.

**Comment by asdf1234-deleted** [comment]
I really think we should still have separate issues for each game, as it's hard to track an issue with the title here being vague ("rendered games"?).

**Comment by TrevtheForthDev** [comment]
This has been fixed for a while now, the problem was that the SteamRuntime wasn't updated but the program itself was. Fix: update Steam via NixPkgs.
