### ISSUE TITLE
Games immediately close; empty logs

### ISSUE THREAD

**Issue by jarruda** [ValveSoftware/Proton#5500]
I tried two games, Final Fantasy V Pixel Remaster and Torchlight.

Trying to launch the games results in them immediately closing before a window is created.  I launched with `PROTON_LOG=1` but the logs only contain an info header.  How can I get more information?

```
======================
Proton: 1642175652 experimental-6.3-20220114
SteamGameId: 41500
Command: ['/home/jarruda/.local/share/Steam/steamapps/common/Torchlight/Torchlight.exe']
Options: {'forcelgadd'}
depot: 0.20211209.37
pressure-vessel: 0.20211207.0
scripts: v0.20211029.0-0-g2d89be4
soldier: 0.20211207.0 soldier 0.20211207.0
Kernel: Linux 5.13.0-25-generic #26-Ubuntu SMP Fri Jan 7 15:48:31 UTC 2022 x86_64
======================
```
```
======================
Proton: 1642175652 experimental-6.3-20220114
SteamGameId: 1173810
Command: ['/home/jarruda/.local/share/Steam/steamapps/common/FINAL FANTASY V PR/FINAL FANTASY V.exe']
Options: {'forcelgadd'}
depot: 0.20211209.37
pressure-vessel: 0.20211207.0
scripts: v0.20211029.0-0-g2d89be4
soldier: 0.20211207.0 soldier 0.20211207.0
Kernel: Linux 5.13.0-25-generic #26-Ubuntu SMP Fri Jan 7 15:48:31 UTC 2022 x86_64
======================
```

System information: https://gist.github.com/jarruda/07d7ff9d70c7af668a8ff8fe99a8e7c1

**Comment by kisak-valve** [comment]
Hello @jarruda, header only logs hint that Proton encountered an issue before it got a chance to run the actual game executable. It might be interesting to completely close steam, then run `steam` from a terminal and see if there's a hint in the stdout/stderr terminal spew.

**Comment by jarruda** [comment]
Here's the log from doing that, starting from launching the game: https://gist.github.com/jarruda/304b2d88c28eb0f23626bcb5e9a31629

I think these are the relevant lines:
```
ERROR: ld.so: object '/home/jarruda/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jarruda/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
GameAction [AppID 1173810, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/jarruda/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1173810, ActionID 1] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/jarruda/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jarruda/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 10306 != 10303, skipping destruction (fork without exec?)
pressure-vessel-adverb[10536]: W: Unable to generate locales: Child process exited with code 1
*** stack smashing detected ***: terminated
```

**Comment by kisak-valve** [comment]
Thanks for checking. You've encountered https://github.com/ValveSoftware/steam-runtime/issues/420. The NVIDIA 390 driver series is older than the support cutoff of Proton. Please update your video driver.

NVIDIA's Kepler generation laptop parts were left in an awkward spot where support for the laptop variant of the generation ended with the 418 series driver, but there's been users who have had success using up to the 470 series since support for the desktop variants were kept until then.
