### ISSUE TITLE
Cannot launch any game using Proton experimental (Debian 12 (bookworm))

### ISSUE THREAD

**Issue by segvee** [ValveSoftware/Proton#5504]
Hi,

I am not sure whether anyone else has encountered this issue but it seems that no matter what game I try to start with Proton experimental: it doesn't start.

Here is the system information:
[system_information.txt](https://github.com/ValveSoftware/Proton/files/7887923/system_information.txt)

As an example I include the logs for Slipways. This games does not have a native Linux version. This game has been working with Proton since its release. However, when I try starting this game with Proton Experimental it doesn't start. When I switch to Proton 6.3-8 it works flawlessly.

Here are the logs.

Proton experimental:
[slr-app1264280-t20220118T101954_proton_experimental.log](https://github.com/ValveSoftware/Proton/files/7887919/slr-app1264280-t20220118T101954_proton_experimental.log)
[steam-1264280_proton_experimental.log](https://github.com/ValveSoftware/Proton/files/7887922/steam-1264280_proton_experimental.log)

Proton 6.3-8
[slr-app1264280-t20220118T102125_proton_6.3-8.log](https://github.com/ValveSoftware/Proton/files/7887920/slr-app1264280-t20220118T102125_proton_6.3-8.log)
[steam-1264280_proton_6.3-8.log](https://github.com/ValveSoftware/Proton/files/7887921/steam-1264280_proton_6.3-8.log)

**Comment by rbernon** [comment]
Hi, would you mind adding logs with the `+x11drv,+cursor,+event` `WINEDEBUG` channels added in addition to the default ones? It looks like it may be related to winex11 not loading correctly for some reason.

**Comment by segvee** [comment]
Hello,

thanks for the reply. I would be glad to do that but I'm unsure where to add them.

Cheers!

**Comment by segvee** [comment]
Hey, I added the channels to user_settings.py and tried it again. I hope that was correct.

Here are the logs:

[steam-1264280_proton_experimental.log](https://github.com/ValveSoftware/Proton/files/7903384/steam-1264280_proton_experimental.log)
[steam-1264280_proton_6.3-8.log](https://github.com/ValveSoftware/Proton/files/7903385/steam-1264280_proton_6.3-8.log)

Cheers!

**Comment by rbernon** [comment]
Thanks, sadly it's still not really enough to tell what is going on. For some reason (and this actually shouldn't normally happen), `winex11.drv` loads but fails to initialize, with both Proton versions.

With Proton 6.3 however, this is only the case for the first `explorer.exe` process, and a second one is spawned and starts up fine. With Proton Experimental, even the second one (and all subsequent processes) fail to load `winex11.drv`, which ends up ultimately crashing the game.

I have no clue why this happens yet, so maybe adding more debugging channel could tell if you don't mind doing another try. This time with `+cursor,+event,+fshack,+systray,+vulkan,+wgl,+winediag,+x11drv,+x11settings,+xdnd,+xim,+xrandr,+xrender,+xvidmode,+user,+explorer,+module,warn+all` (in addition to the default ones) which should hopefully cover enough `winex11.drv` channels and some useful others.

**Comment by segvee** [comment]
Hey, I added that to the user settings python file. Here are the logs. :)

[steam-1264280_proton_experimental.log](https://github.com/ValveSoftware/Proton/files/7905130/steam-1264280_proton_experimental.log)
[steam-1264280_proton_6.3-8.log](https://github.com/ValveSoftware/Proton/files/7905132/steam-1264280_proton_6.3-8.log)

They've gotten quite large.

Cheers!

**Comment by serhii-nakon** [comment]
In Debian 12 some dependencies can be broken or doesn't exist for now (for example i can't find crda package).

**Comment by serhii-nakon** [comment]
Also please try switch between Wayland and X Server sessions.

**Comment by serhii-nakon** [comment]
Also looks like you use nvidia graphics with intel apu. How you select primary device?

**Comment by segvee** [comment]
Hey, I am not sure what the crda package is. Is that important?
In the end of November 2021/beginning of December 2021 Proton Experimental was still working. Then I didn't have any time anymore until recently and only then I found out that it stopped working.

The X session is running on the Intel GPU but whenever I need the dedicated video card I set the following environment variables: `__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia %command%`
In case I definitely want the dedicated card off (because some games automatically switch to the dedicated card) I use
 `__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=non_NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=mesa %command%`, like in this example with Slipways.

However, no matter what environment variables I use I still cannot get the game to start with Proton experimental.

I am also not sure whether it's related to Debian because I asked people on IRC who also used Debian testing and they didn't have any problems with Proton Experimental.

**Comment by Blisto91** [comment]
@segvee Is it possible for you to update to the nvidia 510 driver and try again? (Not that i really expect it to make a difference)

Also i'm guessing you've tried launching with 
```
 VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json %command%
```

**Comment by segvee** [comment]
Unfortunately that driver is not yet available on Debian but the problem disappeared just as it appeared. It seems that I can use Proton Experimental now. Unfortunately I cannot say what the reason is that it works now.
