### ISSUE TITLE
How to add a new partition in Proton 6.3?

### ISSUE THREAD

**Issue by ZGLinus** [ValveSoftware/Proton#5508]
Proton version: 6.3
The saves of the windows games are in their drive_C folders. I want to put them together. 
I created a d: folder link connect to a folder with the saves with ln -s command. But after changing the path to the saves in the game setting and the driver, I open the game and find that my save is missing. I open explorer.exe with the game running and find nothing in the driver D. 
I think I created D disk in the wrong way. What is the correct way?

**Comment by kisak-valve** [comment]
Hello @ZGLinus, starting with Proton 5.13, Proton is run inside the Steam Linux Runtime - Soldier container environment, and that container is not expected to have unlimited access to the host system.

Please see the discussion on https://github.com/ValveSoftware/steam-runtime/issues/334 / https://github.com/ValveSoftware/steam-runtime/issues/393.

**Comment by smcv** [comment]
> that container is not expected to have unlimited access to the host system

Starting from today's beta of "Steam Linux Runtime - soldier", some common locations for removable media are visible to the container by default. See ValveSoftware/steam-runtime/issues/470 for details.
