### ISSUE TITLE
Torchlight (41500)

### ISSUE THREAD

**Issue by WineBottles** [ValveSoftware/Proton#5512]
# Compatibility Report
- Name of the game with compatibility issues: Torhclight
- Steam AppID of the game: 41500

## System Information
- GPU: Nvidia RTX 2080 Super
- Driver/LLVM version: nvidia 495.46-9 (proprietary)
- Kernel version: linux 5.16.1.arch1-1
- Proton version: impacts Proton 6.21 also 7.0 RC2.
**- According to protondb, 3.7-8 did not have loading issues. So this would be a regression
https://www.protondb.com/app/41500
ctrl+f for "loading" to see all the reports.**

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

**There is no compatibility report for this game, but a "whitelist" does exist from 2018/2019 that also mentions the game load fine in 3.7-8.
https://github.com/ValveSoftware/Proton/issues/548#issuecomment-524554484**

## Symptoms
Abnormally long load times throughout the game.
1) Launching the game
2) Loading characters
3) Moving in and out of town/dungeons

## Reproduction

1) Launch the game, if it ever loads (sometimes  takes up to 2-3 minutes or it loads "forever" aka becomes a zombie process and you need to kill it)
2) Load a character, will have very long load times. Anywhere between 15 seconds to 1 minute
3) Going in and out of towns, dungeons have load times anywhere between 15 seconds to 1 minute

**Comment by kisak-valve** [comment]
Hello @Githob2021, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/548#issuecomment-1018926962.
