### ISSUE TITLE
Warlock - Master of the Arcane (203630) - switching away causes mouse input issues

### ISSUE THREAD

**Issue by Mastnosis** [ValveSoftware/Proton#5514]
# Compatibility Report
- Name of the game with compatibility issues: Warlock - Master of the Arcane
- Steam AppID of the game: 203630

## System Information
- GPU: GTX 760, Vega 10, RX 6600
- Driver/LLVM version: Mesa 21.3.4 or nvidia 470xx -->
- Kernel version: 5.16
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Mastnosis/617ddd53131b4bf0b87ba84f44f8c8f7
- Proton version: Proton Experimental, Proton 6.10-GE and more

## I confirm:
- [Y ] that I haven't found an existing compatibility report for this game.
- [Y ] that I have checked whether there are updates for my system available.

## Symptoms 
Game loads up fine and as long as you do not switch away and come back there seems to be few if any issues. But after switching away when you come back you can click some game elements such as HUD, but you cannot interact with the map or units on the map. Issue is sometimes intermittent.

## Reproduction
Launch Warlock and start a game. You should be able to click on units and move as normal. Switch away from the game and then switch back. You should still be able to click on HUD items like menus, side notifications, however when you will not be able to select a unit by clicking and if a unit is already selected the mouse will not update the pathing or allow interacting with other objects on the map. 

Tested on AMD laptop with Vega 10 as well as desktop using Nvidia GTX 760 and later AMD RX 6600
Arch Linux and Manjaro
KDE on  X11 and Wayland
Gnome on X11 and Wayland
XFCE
tried with and without PROTON_USE_WINED3D=1 i.e. openGL and Vulkan

[Game_d3d9.log](https://github.com/ValveSoftware/Proton/files/7930447/Game_d3d9.log)
[steam-203630.log](https://github.com/ValveSoftware/Proton/files/7930449/steam-203630.log)

**Comment by kisak-valve** [comment]
Hello @Mastnosis, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1188#issuecomment-1021226879.
