### ISSUE TITLE
RPG Maker XP (235900)

### ISSUE THREAD

**Issue by Nathan-MV** [ValveSoftware/Proton#5515]
# Compatibility Report
- Name of the game with compatibility issues: RPG Maker XP
- Steam AppID of the game: 235900

## System Information
- GPU: Intel UHD 630 (KBL GT2)
- Driver/LLVM version: Mesa Intel
- Kernel version: 5.15.16-200.fc35.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Nathan-MV/058dd22441626943d53d934ff17c9085
- Proton version: Experimental (lastest)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 
[steam-235900.log](https://github.com/ValveSoftware/Proton/files/7932472/steam-235900.log)

## Symptoms 
Every time i launch the software appear **RGSS-RTP Standard not installed.** and the software close after clicking in **OK**.
![Screenshot from 2022-01-25 06-47-57](https://user-images.githubusercontent.com/67521199/150953280-04171d23-d03a-4e98-8ad6-ad8e52746958.png)

## Reproduction
Just launch the software.

**Comment by iSaluki** [comment]
I'm fairly sure RGSS-RTP is an RPG Maker specific thing.

Also, RPG Maker XP is a very old program, that supports Windows 2000 at the latest, and has no support for 64 bit systems. You might be able to get it working with a custom prefix (try using `winecfg` (or a Proton equivalent) to set the system to Windows XP, and make sure the prefix is 32-bit. In theory, that should get it working, but I have not tried running this program.


You may find this useful: https://appdb.winehq.org/objectManager.php?sClass=version&iId=5206

And if you want an install script, POL seems to have one: https://www.playonlinux.com/en/app-1617-RPG_Maker_XP.html

Good luck with getting it fixed!
