### ISSUE TITLE
German Keyboard Layout Problem

### ISSUE THREAD

**Issue by Chr1s70ph** [ValveSoftware/Proton#5518]
Running Proton 6.3-8 (and prior), there seems to be some key mapping issues. The `v`-Key is mapped to `ö`. Also, `ä` is mapped to the `d` key. This gets really annoying to reconfigure the key bind in every game manually.

Using manjaro 5.15 with KDE 5.23.4

**Comment by aeikum** [comment]
Can you list some games you are seeing this issue in?

**Comment by Chr1s70ph** [comment]
> Can you list some games you are seeing this issue in?

Its not just one game, its universally applicable to every game.

**Comment by aeikum** [comment]
I understand. Please list some of them.

**Comment by Chr1s70ph** [comment]
- Assassin's Creed Odyssey
- Far Cry 5
- Garry's Mod
- Grand Theft Auto V
- Saint's Row IV
- Warframe

**Comment by Chr1s70ph** [comment]
Seems to be fixed with proton 7
