### ISSUE TITLE
Nier Automata: Crashes on startup in SteamOS (524220)

### ISSUE THREAD

**Issue by mikix** [ValveSoftware/Proton#552]
When using the new Steam Play proton support for the whitelisted game Nier Automata on a Steam Machine, the game crashes on startup, after going through a few screens of graphical noise (white, black, TV static, black, crash).

I'm guessing that the Nvidia drivers in the stable version of SteamOS are too old and I should just wait for SteamOS 3.0? But I wanted to flag this in case it's something else.

SteamOS version: 2.0 update 1:2.154
Steam client version: 1535062307
Steam client built on: Aug 23, 2018, at 19:47:25
Hardware: Alienware Steam Machine i3
Proton version: 3.7-3 (still true with 3.7-6-beta)

**Comment by dubigrasu** [comment]
They say that: "You will need NVIDIA 396.51 or Mesa 18.1.x at a minimum. LLVM7 or above is recommended to play DX11 games without GPU hangs."
https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md
This is related to Ubuntu, but I think is the same for SteamOS.
Probably that's why they recently updated SteamOS beta with NVIDIA 396.54.

**Comment by dragonfly-lover** [comment]
How did you activate Proton in bpm?

**Comment by mikix** [comment]
@dragonfly-lover, if you are using the beta client, Proton is automatically enabled for the set of whitelisted games (you can see that list in the initial Proton announcement). Nier is one of those games.

**Comment by P4NCH1** [comment]
@dragonfly-lover Steam Play / Proton for all titles (non whitelisted) can only be activated in desktop client mode. [Here](https://github.com/ValveSoftware/Proton/issues/204#issuecomment-415951812) you have the steps to exit BPM.
I assume that you already gave a password to allow `desktop` user use `sudo`
if not, it's as easy as typing `passwd` in a new terminal and write your desired password twice, like said in the [SteamOS FAQ](https://steamcommunity.com/groups/steamuniverse/discussions/1/648814395741989999/)

**Comment by mikix** [comment]
I tested SteamOS beta 2.166 (which has NVIDIA 396.54) and it now launches correctly. So it was the drivers after all.

I'll close this issue because it's not a problem with Proton (requirements are clearly stated). But ideally SteamOS would update its stable version soon. Feels weird to have the flagship SteamOS offering not meet Proton's requirements.
