### ISSUE TITLE
Space Engineers (244850) crashes arbitrarily in faudio and SDL2

### ISSUE THREAD

**Issue by priand1** [ValveSoftware/Proton#5523]
# Compatibility Report
- Name of the game with compatibility issues: Space Engineers
- Steam AppID of the game: 244850

## System Information
- GPU: AMD RX 5700 XT
- Driver/LLVM version: Mesa 21.3.4
- Kernel version: 5.16.1
- Link to full system information report as [Gist](https://gist.github.com/priand1/6c0059d4a5c3955e01dcd7b57f0af128):
- Proton version: 6.3

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

 Proton-crash-log: [Gist](https://gist.github.com/priand1/a901217ca29c8167a2726056f5b566dd)

## Symptoms 
Space Engineers crashes arbitrarily. This can happen after 5 minutes of playing or after 5 hours.

Proton leaves crash reports in /tmp/proton_crashreports/ every time the game crashes.
According to these reports there seems to be a problem with faudio and/or SDL2

This happens with proton 6.3 as with proton experimental as well.

## Reproduction

Play SE.

#1792

**Comment by kisak-valve** [comment]
Hello @priand1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1792#issuecomment-1024586675.
