### ISSUE TITLE
Tekken 7 (389730) fails to start on Manjaro

### ISSUE THREAD

**Issue by ARDev1161** [ValveSoftware/Proton#5524]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU:  GTX 970
- Driver/LLVM version: nvidia 396.54
- Kernel version: 5.16, 5.10
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.13-6, 6.3-8, experimental

## I confirm:
- [+] that I haven't found an existing compatibility report for this game.
- [+] that I have checked whether there are updates for my system available.

## Symptoms 
Fails after movie. Game can not enter into main menu.

## Reproduction
Start game

**Comment by kisak-valve** [comment]
Hello @ARDev1161, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by ARDev1161** [comment]
[steam-389730.log](https://github.com/ValveSoftware/Proton/files/8011120/steam-389730.log)

**Comment by ARDev1161** [comment]
https://gist.github.com/ARDev1161/ea50ce9a0a4437256e3eee96e603f67f

**Comment by ARDev1161** [comment]
> Hello @ARDev1161, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Completed

**Comment by kisak-valve** [comment]
Looks like an access violation (c0000005) immediately after `fixme:process:GetNumaHighestNodeNumber (0x2b98ea50): semi-stub` and the game falls over.

Maybe try something like `taskset -c 0-7 %command%` in the game's launch options?

**Comment by ARDev1161** [comment]
> Looks like an access violation (c0000005) immediately after `fixme:process:GetNumaHighestNodeNumber (0x2b98ea50): semi-stub` and the game falls over.
> 
> Maybe try something like `taskset -c 0-7 %command%` in the game's launch options?

taskset -c 0-4 is worked, thank you!
