### ISSUE TITLE
Steam Proton and Star Trek Online

### ISSUE THREAD

**Issue by Zabrat01** [ValveSoftware/Proton#5525]
# Compatibility Report
- Name of the game with compatibility issues: Star Trek Online
- Steam AppID of the game:

## System Information
- GPU: NVIDIA Corporation GM206 [GeForce GTX 960]
- Driver/LLVM version: NVIDIA Driver 495
- Kernel version: Zorin OS
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton Experimental, Proton 6:3-8 and Proton 6.9-GE-2

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

## Symptoms 
This is my first entry for issues due to being new.  

STO had a recent update as of the 25th Jan 2022.  Since then, the screen to enter my credentials suddenly ends to desktop.  I have tried various other Proton drivers (ones seen on ProtonDb and random via Steam) and the same screen drop occurs every time.  Now I can launch the game with the .exe but control in-game is not as good as it is via Steam/Proton. I have been using Proton Experimental since October 2021 and I did try the other 2 to see any effect.  The same issue occurs.  I have updated Proton DB with my entry.  Thank you.

**Comment by kisak-valve** [comment]
Hello @Zabrat01, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1198#issuecomment-1024969606.
