### ISSUE TITLE
Mortal online 2 crashing on startup

### ISSUE THREAD

**Issue by Cantdoo** [ValveSoftware/Proton#5529]
# Compatibility Report
- Name of the game with compatibility issues: Mortal Online 2 
- Steam AppID of the game: 1170950
## System Information
- GPU: NVIDIA GeForce GTX 1
- Driver/LLVM version: Mesa 21.3.5-1
- Kernel version:  5.16.3-arch1-1
- Link to full system information report as Gist: https://gist.github.com/Cantdoo/fc18888c86b36d405ae00e40da13209b
- Proton version: Experiemental

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

[steam-1170950.log](https://github.com/ValveSoftware/Proton/files/7966233/steam-1170950.log)

## Symptoms 
I had read on protonDB that people have been able to play this game despite it having VAC, aside from 1 person having a crash on startup. I wanted to give it a shot, and i have the same issue: It crashes immediately after selecting graphics driver on startup menu.

I have tried to force start it with OpenGL but it won't work. And i have also installed DXVK to turn the DirectX signals to Vulcan, but i hear that that's something that's already implemented in Proton? im not sure.. Didn't work either way

## Reproduction
Start the game and pick a graphic driver

**Comment by kisak-valve** [comment]
Hello @Cantdoo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4721#issuecomment-1025172244.

**Comment by Cantdoo** [comment]
Thank you!
