### ISSUE TITLE
Proton breaks, can't get past booting any game using it.

### ISSUE THREAD

**Issue by dmannorflow** [ValveSoftware/Proton#5530]
Systems tested: Ubuntu 20.04, Fedora 35 Workstation
GPU: Radeon RX570
CPU: AMD® Ryzen 5 1600

Title says it all. Launch any title, offically or unoffically supported, and the game starts. It closes shortly after, and I have an idea of what it is. It mentions something about X session authentication failing, but it has worked beautifully in the past.  If anyone knows the error logs for Fedora, I'd love that.

**Comment by kisak-valve** [comment]
Hello @dmannorflow, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to one of the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by dmannorflow** [comment]
https://gist.github.com/dmannorflow/f91f8116d96b37397adbdd8bc015b445
For some reason I can't find the log, is there another way to get it?

**Comment by Hasshu** [comment]
@dmannorflow The log file should appear in your home folder, or in `~/.var/app/com.valvesoftware.Steam/` if you're using Flatpak.

Incidentally, do native Linux games launch properly?

**Comment by dmannorflow** [comment]
@Hasshu incidentally, native games **do** launch. I have tried titles such as Muck and Project Zomboid, and they both work flawlessly. I've checked both my home folder and the one you have suggested, and `~/.var/app/com.valvesoftware.Steam/` does not not exists. I only have up to the app directory. Any other suggestions?

**Comment by Hasshu** [comment]
@dmannorflow Hmm... If you added `PROTON_LOG=1 %command%` (verbatim) to the game's launch options in the properties window, but no log file appeared, that's odd. Something wrong with permissions, perhaps?

> Any other suggestions?

Does the path to the Proton games contain any unusual characters? Say, a trailing dot in a folder's name.

> It mentions something about X session authentication failing

Something like *"Could not connect to X session manager: None of the authentication protocols specified are supported"*? These seem to be just harmless warnings.

**Comment by dmannorflow** [comment]
> Hmm... If you added PROTON_LOG=1 %command% (verbatim) to the game's launch options in the properties window, but no log file appeared, that's odd. Something wrong with permissions, perhaps?

I've copied the command verbatim, so I guess so? I've tried setting the perms to create and destroy files for my user, but it doesn't seem to affect it.

>Does the path to the Proton games contain any unusual characters? Say, a trailing dot in a folder's name.

I've tried the default install location and an external hard drive, so I can't say it does. Here's both of them, for example
`Home/.local/share/Steam/steamapps/common/Game`
`(HHD)/SteamLibrary/steamapps/common/(Game)`

> Something like "Could not connect to X session manager: None of the authentication protocols specified are supported"? These seem to be just harmless warnings.

That's what the error was! Yeah, I've had that error, but I don't think it could be harmless. I'm just a guy trying to play videogames, I don't know.

**Comment by Hasshu** [comment]
> I've copied the command verbatim, so I guess so? I've tried setting the perms to create and destroy files for my user, but it doesn't seem to affect it.

Probably a stupid question, but just in case: are Proton & Co actually installed? In your Library, if you filter by tools, there should be at least one version of Proton, a Steam Linux Runtime, and (likely) Steamworks Common Redistributables. If they are present, try using, say, `PROTON_LOG=1 PROTON_LOG_DIR=~/Proton %command%` as the launch options this time; if there's no "Proton" folder with a log file in your $HOME after that, I'm out of ideas.

> I've tried the default install location and an external hard drive, so I can't say it does.

Assuming that Proton is installed properly, could it be that your home folder and/or HDD have unusual names? Asking since I encountered a similar problem when I did a clean install of Fedora Linux 35 the other day: no games would launch via Proton, but native ones ran just fine (and that's how I found this here GitHub issue). Apparently, a trailing dot in my $HOME made Proton stumble, as the said dot was omitted in the paths mentioned in the logs. I ended up reinstalling the OS once more, with no trailing dots in my username this time, and now Proton seems to work as it should.

> That's what the error was! Yeah, I've had that error, but I don't think it could be harmless.

It appears to be randomly spammed all over the logs when I have Steam running, yet everything works fine. Just X11 things, I suppose.

> I'm just a guy trying to play videogames, I don't know.

I hear ya.

**Comment by dmannorflow** [comment]
> Probably a stupid question, but just in case: are Proton & Co actually installed? In your Library, if you filter by tools, there should be at least one version of Proton, a Steam Linux Runtime, and (likely) Steamworks Common Redistributables. If they are present, try using, say, PROTON_LOG=1 PROTON_LOG_DIR=~/Proton %command% as the launch options this time; if there's no "Proton" folder with a log file in your $HOME after that, I'm out of ideas.

I have every single one except battle eye lol. I've tried to run that command, and it doesn't work. I've also installed Wine, and Winetricks if that helps at all.

> Assuming that Proton is installed properly, could it be that your home folder and/or HDD have unusual names? Asking since I encountered a similar problem when I did a clean install of Fedora Linux 35 the other day: no games would launch via Proton, but native ones ran just fine (and that's how I found this here GitHub issue). Apparently, a trailing dot in my $HOME made Proton stumble, as the said dot was omitted in the paths mentioned in the logs. I ended up reinstalling the OS once more, with no trailing dots in my username this time, and now Proton seems to work as it should.

See above, I have a suspicion that it's my home folder being weird. I don't think I have any trailing dots in my username, I'll double check. It doesn't appear that it has any periods in the name, so...

**Comment by ipr** [comment]
So you have Fedora with Gnome running X. Have you tried Gnome and Wayland session instead? 
That would mean you don't need to deal with X issues. It should work fine since you have AMD GPU.
In the login screen there should be a gear icon where you can select session type (Gnome, Gnome on X, KDE.. whatever you have installed).

**Comment by Hasshu** [comment]
@dmannorflow I see. You could try running some Windows game(s) with Wine to see if they work at all (`wine-dxvk` should come as a dependency).

@ipr Wouldn't Steam just run under XWayland in that case?

**Comment by ipr** [comment]
> @ipr Wouldn't Steam just run under XWayland in that case?

Yes, it has X11 handling, but it is different from old X in many ways. Different way of handling drivers (DRM/KMS) means it doesn't need same permissions as old X, for instance. If the problem still persists it is something else, but most testing and development happens with Wayland these days, including most development in Gnome, for example. X itself is in "hard maintenance mode" and Xwayland does not need many parts of X at all.

Xwayland and Xserver handle the X11 protocol, but the way they implement the handling is different. Xwayland renders into Wayland surfaces while Xserver has another way.

**Comment by Hasshu** [comment]
> Xwayland and Xserver handle the X11 protocol, but the way they implement the handling is different. Xwayland renders into Wayland surfaces while Xserver has another way.

In this case it's worth trying. That said, I see the same log spam on the same OS with X11, yet everything works on my end. Since Proton can't even produce any logs, there may be some major breakage involved.

If nothing else helps, reinstalling your OS might be a good idea. @dmannorflow

**Comment by ipr** [comment]
Another thing that wasn't mentioned is that Fedora has stopped support for 32-bit x86 (only 64-bit now). So you might be missing something essential that prevents Proton from starting at all. Wine 7.0 changed the way it handles 32- and 64-bit PE-binaries (Wow64) so that 32-bit Unix-libraries would not be needed but Proton does not have that yet. So you'll need some 32-bit versions side by side with the 64-bit versions installed.

**Comment by Hasshu** [comment]
Normally, both `wine` and `steam` (including the Flatpak) would pull all the required 32-bit stuff as dependencies, so that shouldn't be a problem.

Hmm... OP, does anything happen if you run `vkcube` in the terminal?

**Comment by dmannorflow** [comment]
> I see. You could try running some Windows game(s) with Wine to see if they work at all (wine-dxvk should come as a dependency).

I'll try, don't have a clue to how wine works.

> Hmm... OP, does anything happen if you run vkcube in the terminal?

@Hasshu I had to install it, but it displays the LunarG/LunarC? Logo on a rotating cube. As usual, I've tried to launch a windows game, but doesn't work.

**Comment by Hasshu** [comment]
> I'll try, don't have a clue to how wine works.

Assuming that you have any installable (or portable) Windows games on hand, normally, you just double-click an executable file (or type, e.g., `wine setup.exe` in the terminal), and Wine does the rest.

> I had to install it, but it displays the LunarG/LunarC? Logo on a rotating cube.

That should mean that your GPU has proper Vulkan support, so it's unlikely to be a DXVK-related issue.

> As usual, I've tried to launch a windows game, but doesn't work.

One more question: when you select "Show more details" (the i-shaped icon to the right of the "Play" button) on the Steam Library page of the game you're trying to run, what does it say after "Runs on this computer via Steam Play"?

**Comment by dmannorflow** [comment]
> One more question: when you select "Show more details" (the i-shaped icon to the right of the "Play" button) on the Steam Library page of the game you're trying to run, what does it say after "Runs on this computer via Steam Play"?

It says for MCC "Proton 4.11-13 selected by you for this title.". I doubt it's a proton issue, as I've tried running it without the anti cheat. Thinking out loud, maybe it's anti-cheat software that's causing it? It shouldn't be, cause I believe I had it running under Ubuntu before.... I've tried it with a different game (without anti-cheats) and it doesn't work as well...

**Comment by ipr** [comment]
> > One more question: when you select "Show more details" (the i-shaped icon to the right of the "Play" button) on the Steam Library page of the game you're trying to run, what does it say after "Runs on this computer via Steam Play"?
> 
> It says for MCC "Proton 4.11-13 selected by you for this title.". I doubt it's a proton issue, as I've tried running it without the anti cheat. Thinking out loud, maybe it's anti-cheat software that's causing it? It shouldn't be, cause I believe I had it running under Ubuntu before.... I've tried it with a different game (without anti-cheats) and it doesn't work as well...

4.x is too old for many games. At least try using 6.3

**Comment by Hasshu** [comment]
@dmannorflow Try going to Settings -> Steam Play; make sure that "Enable Steam Play for all other titles" is checked, then choose to run all other titles with (e.g.) Proton 6.3-8. As @ipr said, the version in use is a bit too old at this point.

**Comment by dmannorflow** [comment]
Holy shit. I don't know what the hell happened to do that, but Proton works again!
Titles tested: 
Proton 6.8 - Halo MCC (OS SSD); Halo Wars: DE (OS SSD)

Still testing titles as of writing, will update when I continue.

**Comment by dmannorflow** [comment]
Update:
Seems like there's a problem with games on an external drive. Using Proton Experimental and 6.3-8 does not seem to work with them at all. Any ideas?

**Comment by kisak-valve** [comment]
Hello @dmannorflow, what filesystem are you using with the secondary drive? Using NTFS with Proton is known to be finicky.

**Comment by dmannorflow** [comment]
How did you know? Yes, I'm using NTFS...

**Comment by dmannorflow** [comment]
How did you know? Yes, I'm using NTFS.

**Comment by kisak-valve** [comment]
The behavior of Proton interacting with NTFS is being tracked in several issue reports going back to #11. The general recommendation is to use a linux native filesystem with Proton.

Closing in favor of the older issue report.
