### ISSUE TITLE
Deep Rock Galactic / 548430. Fails to start. Failed to load ThirdParty.

### ISSUE THREAD

**Issue by MainDallasCL** [ValveSoftware/Proton#5532]
# Compatibility Report
- Deep Rock Galactic
- Steam ID: 548430

## System Information
- AMD R9 390x / Hawaii Pro / GCN 2.0
- Drivers: llvm 13.0.0-6, mesa 21.3.5-1, vulkan-radeon 21.3.5-1, xf86-video-amdgpu 21.0.0-2
- Kernel version: 5.16.4-arch1-1 (Tried zen as well, same thing)
- Link to full system information report as [Gist](https://gist.github.com/): [here](https://gist.github.com/MainDallasCL/ce14f02aa11d8279c6ddad2054e3fdd7)
- Proton version: Tried every single one, with through reinstalls
- Proton logs: [here](https://gist.github.com/MainDallasCL/0cd81dbee0f84d259c7a8475e539b167)
- Using 2x SSD RAID 0 using MDADM for root partition. Steamlibrary resides on a HDD with NTFS that is properly mounted.

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Installs, creates a Windows sub-directory, prepares it for the game, then tries really hard to do anything but crash.
Then crashes.

## Reproduction
Reinstall the game.

## Additional information
[Logs](https://gist.github.com/MainDallasCL/0cd81dbee0f84d259c7a8475e539b167) are talking about:
`LogWindows: Failed to load '../../../Engine/Binaries/ThirdParty/PhysX3/Win64/VS2015/APEXFramework_x64.dll`
And many more .dll files from the same directory. Those fail right before:
`LogCore: Engine exit requested (reason: EngineExit() was called)`

It seems that the physics engine is unable to load up since the files seem to be missing, so calls the game to shut down. Even though all the other files are clearly loading up as expected.

Yes, the files are indeed where they should be when I checked for them.
And yes, I did reinstall/verify the game.

Every other game using Proton/Vulkan works happily and well.
I have uninstalled this game a week ago, yet reinstalled when the update dropped, which wasn't supposed to change much.

**Comment by kisak-valve** [comment]
Hello @MainDallasCL, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/284#issuecomment-1026300730.
