### ISSUE TITLE
Hybrid Graphics: Vulkan Shader conversion targets primary GPU?

### ISSUE THREAD

**Issue by philipl** [ValveSoftware/Proton#5538]
Proton 6.3-8, latest steam client beta.

I've been playing around with a hybrid graphics configuration on my desktop (Intel iGPU + nvidia dGPU on-demand mode) and while everything works well in-game, I noticed that it seemed to trigger full shader conversion the first time I played games after switching to hybrid mode, even though I was playing on the same nvidia gpu in both cases.

I suspect it's doing shader conversion for the iGPU even though I'm not using it. I have not tested whether it would also do conversion for the dGPU if I didn't have those cached already, or whether it would result in the game running with no cached shaders at all.

**Comment by kisak-valve** [comment]
Hello @philipl, Steam's shader pre-cache is managed by Steam and Fossilize. Proton is not involved with managing those shaders.

Closing in favor of https://github.com/ValveSoftware/steam-for-linux/issues/7903.
