### ISSUE TITLE
Bloody Spell - Patch for Videos not properly rotated

### ISSUE THREAD

**Issue by rboxeur** [ValveSoftware/Proton#5540]
Booting on Win10, video are rotated by 180.
Setting it to Win7 helps to make videos as default.

Could you please add this line so videos can work to the file wine/loader/wine.inf.in

> HKCU,Software\Wine\AppDefaults\ForzaHorizon5.exe\DllOverrides,"amd_ags_x64",0x2,"builtin"
> HKCU,Software\Wine\AppDefaults\Avengers.exe\DllOverrides,"atiadlxx",,"builtin"
> HKCU,Software\Wine\AppDefaults\starwarssquadrons.exe\DllOverrides,"atiadlxx",,"builtin"
> ++HKCU,Software\Wine\AppDefaults\BloodySpell.exe,"Version",,"win7"
> ;;Likely want *80 and *90 too, but those require removing Wine's manifest

 files.

**Comment by kisak-valve** [comment]
Hello @rboxeur, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3126#issuecomment-1029023332.
