### ISSUE TITLE
Age of Empires IV won't start

### ISSUE THREAD

**Issue by scorp10n2000** [ValveSoftware/Proton#5545]
# Compatibility Report
- Name of the game with compatibility issues: Age of Empires IV, Game no longer starts after latest update.
- Steam AppID of the game: https://store.steampowered.com/app/1466860/Age_of_Empires_IV/

## System Information
- GPU: NVIDIA GeForce GTX TITAN X
- Driver/LLVM version: 4.6.0 NVIDIA 510.47.03
- OS: EndeavourOS
- Kernel version: 5.16.5-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/scorp10n2000/76fab4f82847b3d0906b3b7b01df683c
- Tried Proton version: 6.3.8 & Experimental

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

Proton Log:
https://gist.github.com/scorp10n2000/1485669801c714254d5821918c468d71

## Symptoms 
Game won't start, CTD

## Reproduction
Start game in steam with any Proton version.

**Comment by kisak-valve** [comment]
Hello @scorp10n2000, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5258#issuecomment-1030631418.
