### ISSUE TITLE
Proton does not launch games that are on NTFS partition

### ISSUE THREAD

**Issue by Maciejka1** [ValveSoftware/Proton#5546]
Proton: experimental, 6.3-8, 5.13-6, 5.0-10, 4.11-13, 4.2-9, 3.16-9, 3.7-8

Proton does not crash nor it is showing any error, its just trying to start a game.
I have tried a few games, for example: FNaF:SB, Forza horizon 5, scrap mechanic, no mans sky and sea of thieves, none of them worked on NTFS partition but all of them worked on ext4 .
My fstab looks like this:
       UUID=2E2A4CD52A4C9C29       		      /media/lokalny ntfs-3g    defaults,uid=1000,gid=1000,rw,user,exec,umask=000 0 0
ls -l /media looks like this:
       drwxrwxrwx 1 maciejka maciejka  4096 Feb  5 19:58 lokalny
I only found this https://github.com/benjamimgois/ntfix but it sometimes works sometimes not.
I use ntfs because I've already installed those games on windows and there is no sense to reinstall them, also I played RDR2 and CP2077 on ntfs with rockstar launcher and gog with no problems at all.

**Comment by kisak-valve** [comment]
Hello @Maciejka1, the long standing issues with Proton interacting with NTFS is already being tracked in several issue reports going back to #11.

Closing as a duplicate.
