### ISSUE TITLE
ESYNC/FSYNC causes origin to fail to upgrade

### ISSUE THREAD

**Issue by Logical-sh** [ValveSoftware/Proton#5549]
#### Your system information

* Steam client version (build number or date): Feb 1 2022
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Tried two games (Assassin's Creed Origins and Oddesy) In Proton-Experemental
Both needed an origin upgrade.
Disabling ESYNC and FSYNC allowed the upgrade to succeed immediately after trying several other things.

Origin launches fine with them enabled unless an update is needed.

Others have reported it can update with them enabled, but it may take several tried, seems to be luck/random.
#### Steps for reproducing this issue:
Download a fresh Origin game/clear compat data.
Try to launch the game and Origin will attempt to update.
It may work, it may not.
If it doesn't it is usually consistent and disabling esync/fsync will make it work right away (I did not try it individually)

**Comment by ipr** [comment]
This report is bogus/faulty: mentioned games do not use Origin, they are not EA games. Both use Uplay which can be installed manually with:
WINEPREFIX=/path/steamapps/compatdata/582160/pfx /path/steamapps/common/Proton\ 6.3/dist/bin/wine64 /path/steamapps/common/Assassins\ Creed\ Origins/Installer_Resources/UPlayInstaller.exe 

Maybe a problem exists but games used as example are not correct for this case.

**Comment by Logical-sh** [comment]
Oh! I mean Uplay not origin, I got my annoying launchers mixed up! Will close and reopen with the correct names!
