### ISSUE TITLE
Doom Eternal minor graphical glitch with certain particles

### ISSUE THREAD

**Issue by something12356** [ValveSoftware/Proton#5553]
# Compatibility Report
- Name of the game with compatibility issues: DOOM Eternal
- Steam AppID of the game: 782330

## System Information
- GPU: Radeon 6600xt
- Driver/LLVM version: Mesa 21.3.5-1
- Kernel version: linux-zen 5.16.5.zen1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/something12356/f35686e129e5c9215b1a3d98ff40abde
- Proton version: 6.3-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Reproduction
Install DOOM Eternal, select 6.3-8, run DOOM Eternal, might require an AMD GPU?

Here are some screenshots: I know the game is modded in these photos but I can reproduce the issue on an unmodded install as well. https://imgur.com/a/BfOBnhB

**Comment by kisak-valve** [comment]
Hello @something12356, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3773#issuecomment-1032127991.
