### ISSUE TITLE
Symlinks for game config files are overwritten

### ISSUE THREAD

**Issue by kallestrop** [ValveSoftware/Proton#5556]
- Proton version 6.3-8
- Tested with Euro Truck Simulator 2 (227300) running with Proton
- Game library is located on a etx4 formated SSD
- OS: Debian 11 Bullseye

When creating a symbolic link for a game config file located in `/home/user/.local/share/Steam/steamapps/compatdata/227300/pfx/drive_c/users/steamuser/Documents/Euro Truck Simulator 2/profiles/56616E696C6C61`, the link will always be overwritten after changes are applied in game config menu.

How to reproduce:

- Navigate to profile folder - in my case: `~/.local/share/Steam/steamapps/compatdata/227300/pfx/drive_c/users/steamuser/Documents/Euro Truck Simulator 2/profiles/56616E696C6C61`
- rename `controls.sii` to `controls.reference`
- create symbolic link `ln -s controls.reference controls.sii`

```
user@bullseye:ls controls.*
-rw-r--r--  1 user users  35K  8. Feb 07:00 controls.reference
lrwxrwxrwx  1 user users   18  8. Feb 07:25 controls.sii -> controls.reference
```

Now start the game and apply changes to a keybinding. After that, symlink is overwritten:

```
user@bullseye:ls controls.*
-rw-r--r-- 1 user users 35K  8. Feb 07:00 controls.reference
-rw-r--r-- 1 user users 35K  8. Feb 07:26 controls.sii
```

**Comment by kisak-valve** [comment]
Hello @kallestrop, this reads like game engine specific behavior and we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5049#issuecomment-1032592697.
