### ISSUE TITLE
SSHFS causes some games to crash / load indefinetly

### ISSUE THREAD

**Issue by hasezoey** [ValveSoftware/Proton#5563]
- Proton 6.3-8
- Proton Experimental (1642614452 experimental-6.3-20220119)

## What is the issue

Many games work fine with Proton over SSHFS, but some games (listed below) either crash outright or hang indefinitely

## Games that do no work

Below are the Games that i noticed do not work over sshfs (some of them not anymore, but had worked before):

- No Man's Sky (275850) [no report from me yet]
- Disgaea 4 Complete+ (1233880) https://github.com/ValveSoftware/Proton/issues/5164#issuecomment-1030587007
- Assasin's Creed Odyssey (812140) https://github.com/ValveSoftware/Proton/issues/1757#issuecomment-1006078471

## My System / Setup

My system (currently) is:
- Manjaro 21.2.3 (Kernel 5.16.5-1) KDE Plasma Wayland + Pipewire
- SSHFS version 3.7.2
- FUSE library version 3.10.5
- ssh(fs) is done with a keyfile
- sshfs is mounted with a `systemctl` `.mount` file on login
- my local drive is btrfs (raid0) (this is the drive that i use for non-sshfs games)

My server / nas system (currently):
- Ubuntu Server 21.10 (Kernel 5.13.0-22)
- openssh-server 1:8.4p1-6ubuntu2.1
- drive is btrfs (raid10) (that is used over sshfs)

---

PS: i had already tried with each game to set `PROTON_NO_ESYNC=1` and `PROTON_NO_FSYNC=1`

**Comment by aeikum** [comment]
I think this is just something that isn't realistically going to be supported. Some games depend on specific filesystem features (file sizes, whether or not the file is a symlink, special characters in filenames, the list goes on...). SSHFS may interfere with some of those corner-case features, such that tracking them down and fixing everything would be a huge task.

**Comment by hasezoey** [comment]
> I think this is just something that isn't realistically going to be supported.

kinda sad, but understandable

> Some games depend on specific filesystem features (file sizes, whether or not the file is a symlink, special characters in filenames, the list goes on...).

i just made a issue because i noticed that only some (small amount) of games have this weird behavior many others just work without problems

> SSHFS may interfere with some of those corner-case features, such that tracking them down and fixing everything would be a huge task.

i would be able to provide logs / outputs if interested (currently dont have any provided, because i dont know what else than proton logs are useful or with that options to generate the log outputs), but i will not be able to debug / change the code myself because i have no experience in c/c++ (and also dont really plan on learning it)

**Comment by hasezoey** [comment]
Closing this issue because it seems like it will not be fixed and i myself am not using sshfs for games anymore
