### ISSUE TITLE
DRAGON QUEST® XI: Echoes of an Elusive Age™ - Digital Edition of Light [742120]

### ISSUE THREAD

**Issue by mikakev1** [ValveSoftware/Proton#5568]
# Compatibility Report
- DRAGON QUEST® XI: Echoes of an Elusive Age™ - Digital Edition of Light 
- 742120

## System Information
[Tested on 2 different computers]
- GPU: RX 480, RX 570 (on both my systems)
- CPU: Ryzen 1700, 2700
- Driver/LLVM version: Any stable version since Ubuntu 20.04 
- Kernel version: 5.04(LTS)  <-> 5.15 (LTS)
- OS Ubuntu 20.04, 20.10, 21.04 21.10, 22.04
- Wayload or Xorg 
- Controllers: X360, XBOX ONE, XBOX ONE S ;  DUALSHOCK: 3, 4, 5 ( DUALSENSE)
- Link to full system information report as [Gist](https://gist.github.com/mikakev1/a2cf30cad43b54f181ae590424c524f9#file-specs-steam):
- Proton version: I tested most of them during the last two years. I currently use experimental or Proton-7.1-GE-2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

###  LIBINPUT

$ sudo libinput list-devices | grep -Ev 'n/a|none'
Failed to open /dev/input/event14 (No such file or directory)
Failed to open /dev/input/event15 (No such file or directory)
Device:           Power Button
Kernel:           /dev/input/event1
Group:            1
Seat:             seat0, default
Capabilities:     keyboard 

Device:           Power Button
Kernel:           /dev/input/event0
Group:            2
Seat:             seat0, default
Capabilities:     keyboard 

Device:           SINOWEALTH GXT 144 Gaming Mouse
Kernel:           /dev/input/event2
Group:            3
Seat:             seat0, default
Capabilities:     pointer 
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Scroll methods:   button
Accel profiles:   flat *adaptive

Device:           SINOWEALTH GXT 144 Gaming Mouse Keyboard
Kernel:           /dev/input/event3
Group:            3
Seat:             seat0, default
Capabilities:     keyboard 

Device:           USB usb keyboard
Kernel:           /dev/input/event4
Group:            4
Seat:             seat0, default
Capabilities:     keyboard 

Device:           USB usb keyboard Consumer Control
Kernel:           /dev/input/event5
Group:            4
Seat:             seat0, default
Capabilities:     keyboard pointer 
Nat.scrolling:    disabled

Device:           USB usb keyboard System Control
Kernel:           /dev/input/event6
Group:            4
Seat:             seat0, default
Capabilities:     keyboard 

## Symptoms 
[I've got an french azerty keyboard.]

All controllers work (I mean they react to inputs well) but the screen rotates continuously as if I was tilting the right analog stick on the right hand (camera clockwise rotation) BUT, it does rotate way faster than I could if I'd do it manually.
Tried all controllers mentioned above and without, disconnected keyboard or mouse, I'm still facing the issue.

### How to reproduce

Start game, everything's fine in the menu until there's 3D model rendered, then camera rotates endlessly.

**Comment by kisak-valve** [comment]
Hello @mikakev1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1419#issuecomment-1037421458.
