### ISSUE TITLE
Please provide pre-built proton archives going forward

### ISSUE THREAD

**Issue by BETLOG** [ValveSoftware/Proton#5571]
Please supply precompiled and packaged proton versions.
I have an issue with windows losing focus post Proton-5.0, but frankly...after using Glorious Eggrolls packages and being able to just drop them into compatibilitytools.d... the need to jump through compiler and docker hoops half a dozen times before I can even begin to isolate where the issue first appears in mainline Proton is making me reconsider if it's worth the effort.

**Comment by kisak-valve** [comment]
Hello @BETLOG, this feature request is already being tracked at #5042. Closing as a duplicate.

**Comment by trymeouteh** [comment]
Would like to download the proton builds that work for my games and be able to add them to my compatibilitytools.d folder manually.
