### ISSUE TITLE
Video memory overflow in Mortal Online 2.

### ISSUE THREAD

**Issue by toktarov84** [ValveSoftware/Proton#5573]
# Compatibility Report
- Name of the game with compatibility issues: Mortal Online 2
- Steam AppID of the game: 1170950

## System Information
- GPU: Nvidia RTX 2060
- Driver Version: nvidia 510.47.03
- Kernel version: 5.16
- Proton version: 6.3-8, Experimental, 7.2-GE
- DirectX version: 11&12

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms

When setting textures above low ones or turning on dlss, the video memory is completely filled and the video card is loaded at 100 percent and the fps drops dramatically.

## Reproduction

In Haven, the problem is not observed, but as soon as you go to Mirland, the problem reproduces very quickly with active movement through locations.

**Comment by kisak-valve** [comment]
Hello @toktarov84, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4721#issuecomment-1040281121.
