### ISSUE TITLE
BUG: no vibration in rocket league (dualsense controller)

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [ValveSoftware/Proton#5575]
I am using proton experimental using heroic games launcher, and there's no vibration when I am playing in rocket league. 
(vibration is enabled and at max strength)

**Comment by kisak-valve** [comment]
Hello @Etaash-mathamsetty, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3521#issuecomment-1041016946.
