### ISSUE TITLE
Cyberpunk 2077 Patch 1.5 Won't run using Proton

### ISSUE THREAD

**Issue by p0ryae** [ValveSoftware/Proton#5576]
# Compatibility Report
- Name of the game with compatibility issues: Cyberpunk 2077
- Steam AppID of the game: 1091500

## System Information
- GPU: RTX 2060
- Driver/LLVM version: Latest Nvidia Driver (510.54)
- Kernel version: Latest Zen Kernel (5.16.9-zen1-1-zen)
- Proton version: Proton Experimental and any other Proton Version

## I confirm:
- that I have checked whether there are updates for my system available.

## Symptoms 
Game seems to be hanging after launch. Nothing pops up other then the report the bug to CDKProjectRED.
Cyberpunk 2077 ran totally fine before the today's patch, 1.5 meaning that the new patch has broken the compatibility.

Proton Log here: [steam-1091500.log](https://github.com/ValveSoftware/Proton/files/8077007/steam-1091500.log)

## Reproduction

1. Download Cyberpunk 2077 
2. Run it.

**Comment by LiamDawe** [comment]
Worked fine here last night with NVIDIA 2080Ti on 510.54 too. Also runs fine this morning with Proton 7.

**Comment by chapstikk** [comment]
same issue on amd with 6700 xt

**Comment by kurobeats** [comment]
Worked for a few hours and after a reboot, stopped launching, the following error from debugging might assist:

`wine: Read access denied for device L"\\??\\E:\\", FS volume label and serial are not available.`

Same error for Proton  versions 6.3-8, 7.0-1 and Experimental.

**Comment by ipr** [comment]
> Worked for a few hours and after a reboot, stopped launching, the following error from debugging might assist:
> 
> `wine: Read access denied for device L"\\??\\E:\\", FS volume label and serial are not available.`
> 
> Same error for Proton versions 6.3-8, 7.0-1 and Experimental.

No, that is pointless. There are many "drives" mapped to different directories, they are not even used but scan finds them and label and serial are useless.

**Comment by ipr** [comment]
I am guessing something in the D3D12 code is not supported now since my logs have plenty of this:

0488:warn:d3d12_pipeline_library_load_pipeline: Pipeline "-671166324" does not exist.

**Comment by ipr** [comment]
Some Windows users are reporting problems regarding some audio software called "Nahimic" being a problem. I don't see anything like that in Cyberpunk files so it must be something else they've installed?

On Proton 7.0 the launcher is flickering strangely while trying to input login information to it making it hard to enter any information. This did not happen with old Cyberpunk (pre-1.5) with old Proton (6.3).

On Proton 7.0 the is a crash in A_SHAFinal(), so broken hash-function or error using it?

[steam-1091500.log.gz](https://github.com/ValveSoftware/Proton/files/8079765/steam-1091500.log.gz)

**Comment by TheRiisager** [comment]
I have the same issue. It started, and ran, without issue immediately after the 1.5 update, but after a system restart it no longer works.

System:
GPU: RX 5700XT
Driver: Mesa 21.3.6
Kernel: 5.16.8
Distro: Fedora Workstation 35

I've tried Proton 6.3-8, 7.0-1, 7.1-GE-2, and 7.2-GE-2.

I'm using --launcher-skip -skipStartScreen flags in steam launch options.
[steam-1091500.log](https://github.com/ValveSoftware/Proton/files/8079801/steam-1091500.log)

**Comment by haui97** [comment]
I also have this issue. Game started and ran fine after the 1.5 update, but stopped working after a system restart.

System:
GPU: RX 6600XT
Driver: Mesa 21.3.6
Kernel: 5.16.9
Distro: Garuda Linux

**Comment by j-rav** [comment]
Removing and reinstalling the full game fixed it for me (since the patch is about 50Gb it's barely any difference).

But it reintroduced a bug I already had a year ago: Looking into specific directions in the game lead to huge framerate drops, but it is no shader compilation since GPU and CPU load as well drop to idle mode (AMD 5800X, 6900 XT, Manjaro 5.16 kernel, tested in various Proton versions including GE).

Another (maybe related?) bug: After 5 min of playing the game is using almost exactly 20 GB of RAM and keeps that amount of memory for the rest of the time.

**Comment by kisak-valve** [comment]
Hello, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1041518133.
