### ISSUE TITLE
Star Trek Online banned Windows 7... - This also affects proton.

### ISSUE THREAD

**Issue by Kepsz** [ValveSoftware/Proton#5581]
# Compatibility Report
- Name of the game with compatibility issues: Star Trek Online
- Steam AppID of the game: 9900

## Symptoms 
STO dev's decided to ban Windows 7 pc's from it's gamer base. Sadly it affects proton too, the game thinks it is running on a Windows 7 pc and throws a notification message...

## Reproduction
Just try to launch the game. It's free.

The game worked fine with proton so far.

**Comment by kisak-valve** [comment]
Hello @Kepsz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1198#issuecomment-1042047456.
