### ISSUE TITLE
F1 2021 Missing FFB Proton7.0

### ISSUE THREAD

**Issue by hodasemi** [ValveSoftware/Proton#5582]
# Compatibility Report
- Name of the game with compatibility issues: F1 2021
- Steam AppID of the game: 1134570

## System Information
- GPU: RTX 2060
- Driver/LLVM version: nvidia 510.47
- Kernel version: 5.15
- Link to full system information: https://gist.github.com/hodasemi/2b886b2a48722d1646608d9d6908466f
- Proton version: 7.0-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Using Proton 6.3-8 force feedback works as intended with F1 2021, changing to Proton 7.0-1 it doesn't work at all. I'm using Thrustmaster T300.

## Reproduction
Force specific Proton version to 7.0-1. Start the game and go into a race (or time trial). The wheel has no force feedback.

**Comment by kisak-valve** [comment]
Hello @hodasemi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4966#issuecomment-1042062352.

**Comment by Draluy** [comment]
This issue seems similar to: https://github.com/ValveSoftware/Proton/issues/1420
Edit: Works again with proton experimental.
