### ISSUE TITLE
Dead Rising 4 (543460)

### ISSUE THREAD

**Issue by DoomedSouls** [ValveSoftware/Proton#5583]
# Compatibility Report
- Name of the game with compatibility issues: Dead Rising 4
- Steam AppID of the game: 543460

## System Information
- GPU: AMD RX 6900XT
- Driver/LLVM version: Mesa 21.3.6-1 / LLVM 13.0.1-1
- Kernel version: 5.16.8-xanmod1-1
- Link to full system information report as [Gist](https://gist.github.com/DoomedSouls/8437ba46f3dcd5fbdc6d2afce4da7282)
- Proton version: 7.0-1

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
No Audio

[steam-543460.log](https://github.com/ValveSoftware/Proton/files/8087402/steam-543460.log)

**Comment by ipr** [comment]
Crash when trying to continue (load) with Proton 7.0.
Game works with audio in main menu.

[steam-543460.log](https://github.com/ValveSoftware/Proton/files/8097841/steam-543460.log)

Edit: starting a game in "capcom heroes" mode works, so it is possible my "story mode" save is in a position that causes something to break and crash.

**Comment by DoomedSouls** [comment]
Today's pipewire 0.3.49 completely fixed this issue.
