### ISSUE TITLE
Nioh 2 – The Complete Edition 120 Fps mode not working & incorrect gamespeed

### ISSUE THREAD

**Issue by DoomedSouls** [ValveSoftware/Proton#5584]
# Compatibility Report
- Name of the game with compatibility issues: Nioh 2 – The Complete Edition
- Steam AppID of the game: 1325200

## System Information
- GPU: AMD RX 6900XT
- Driver/LLVM version: Mesa 21.3.6-1 / LLVM 13.0.1-1
- Kernel version: 5.16.8-xanmod1-1
- Link to full system information report as [Gist](https://gist.github.com/DoomedSouls/8437ba46f3dcd5fbdc6d2afce4da7282)
- Proton version: 7.0-1

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Selecting 120 fps will not change the frame rate and game speed is half. Selecting afterwards 30 fps will also no change frame rate. Its stuck at 60 fps with incorrect gamespeed.

[steam-1325200.log](https://github.com/ValveSoftware/Proton/files/8087663/steam-1325200.log)

**Comment by kisak-valve** [comment]
Hello @DoomedSouls, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4593#issuecomment-1043021878.

**Comment by DoomedSouls** [comment]
I fixed this issue with launch option "mangohud %command%" and adding this line "vsync=2" to MangoHud.conf.
