### ISSUE TITLE
Proton 6.3 not downloading all files via Steam?

### ISSUE THREAD

**Issue by dataprolet** [ValveSoftware/Proton#5585]
I took a look in the ../steam/steamapps/common/ directory and inside the respective Proton folders. I noticed that in the ./dist/bin folder for Proton 6.3 there are some files missing. It's supposed to contain "msidb", "wine", "wine-loader", "wine64", "wine64-loader" and "wineserver", but for Proton 6.3 it only contained "wineserver". Same for the other folders in ./dist.

But the missing files are inside the proton_dist.tar, that gets downloaded to the Proton's directory.

Is this intentionally or a bug? Also reinstalling Proton 6.3 through Steam got the exact same result.

**Comment by kisak-valve** [comment]
Hello @Arjab, this sounds like something went wrong with Proton unpacking itself. Maybe try moving/removing the `dist` folder and then try running a game with that version of Proton?

**Comment by dataprolet** [comment]
Thanks, that must've been the case. Trying to run a game using Proton 6.3 downloaded the missing files. I assumed reinstalling Proton would do the same, but it neither actually removes the old files, nor downloaded the missing files.
