### ISSUE TITLE
SMITE EAC files not found by proton 7.0-1

### ISSUE THREAD

**Issue by thekindstranger** [ValveSoftware/Proton#5586]
# Compatibility Report
- Name of the game with compatibility issues: SMITE
- Steam AppID of the game: 386360

## System Information
- GPU: RTX2070 Super
- Driver/LLVM version: nividia 470.86
- Kernel version: 5.15.15-76051515-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/thekindstranger/67f7bd82b7f5ed0cc0142014c82c8b67
- Proton version: 7.0-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Starting SMITE results in EAC error message saying  "File Not Found >:\home\kindstranger\.steam\debian-installation\steamapps\common\SMITE\Binaries\EasyAntiCheat\EasyAntiCheat_x86.dll". I have verified that the file is in the expected location (backslashes obviously replaced with forwardslashes), and have attached screenshot of my verification.

Game has worked with an earlier version of proton, but had other minor issues (related to proton not closing properly, not EAC)

## Reproduction
Launching SMITE, getting the error.

[steam-386360.log](https://github.com/ValveSoftware/Proton/files/8090183/steam-386360.log)

![SMITE_EAC_issue](https://user-images.githubusercontent.com/87834245/154520977-d87ff23f-80b7-455a-b064-9995a12caea4.jpg)

**Comment by kisak-valve** [comment]
Hello @thekindstranger, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2208#issuecomment-1043143373.
