### ISSUE TITLE
CSGO SDK NVIDIA ERROR

### ISSUE THREAD

**Issue by dev-original** [ValveSoftware/Proton#5589]
# Compatibility Report
- Name of the game with compatibility issues: CSGO SDK HAMMER EDITOR
- Steam AppID of the game: 745

## System Information
- GPU: <GTX 1660 -->
- Driver/LLVM version: <NVIDIA Driver Version: 460.91.03 -->
- Kernel version: <Linux version 5.13.0-27-generic (buildd@lgw01-amd64-045) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #29~20.04.1-Ubuntu SMP -->
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Tried: 3.7-8, 3.16-9, 4.2-9, 4.11-13(this worked but very slow and laggy), 5.0-10, 5.13-6, 6.3-8, Proton-6.19-GE-2, Proton-6.21-GE-2, Proton-7.0rc3-GE-1 and Proton Experimental(worked a few days ago)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 (could not get PROTON_LOG=1 %command% to work)

## Symptoms 
I start the sdk, and get the selection between the map editor, the model viewer and the face poser. When i select hammer editor, a box pops up with an nvidia error

## Reproduction
Open csgo sdk, and choose hammer. Use any of the named proton versions except version 4.11-13.

**Comment by kisak-valve** [comment]
Hello @dev-original, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/851#issuecomment-1045203573.
