### ISSUE TITLE
Cyberpunk 2077 do not work after patch 1.5

### ISSUE THREAD

**Issue by 3DRaven** [ValveSoftware/Proton#5595]
# Compatibility Report
- Name of the game with compatibility issues: Cyberpunk 2077
- Steam AppID of the game: 1091500

## System Information
- GPU: NVIDIA GeForce RTX 3080 Laptop GPU/PCIe/SSE2
- Driver/LLVM version: 4.6.0 NVIDIA 510.47.03
- Kernel version: 5.13.0-30-generic
- Link to full system information report as [Gist](https://gist.github.com/): What is it?
- Proton version: 7.0-1

## I confirm:
- [-] that I haven't found an existing compatibility report for this game.
i found https://www.protondb.com/app/1091500
- [+] that I have checked whether there are updates for my system available.

[steam-1091500.log](https://github.com/ValveSoftware/Proton/files/8104913/steam-1091500.log)

## Symptoms 

After patch 1.5 game not start at all.

## Reproduction

1. Install game
2. update to patch 1.5
3. Just start it

**Comment by kisak-valve** [comment]
Hello @3DRaven, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1046324491.

As a side note, ProtonDB is a third party website and is not affiliated with Valve.
