### ISSUE TITLE
Horizon Zero Dawn (1151640) performance regression proton experimental

### ISSUE THREAD

**Issue by vulturm** [ValveSoftware/Proton#5598]
First of all, the game looks and works great on my system, and thank you for that!
I just wanted to raise awareness that there is a performance regression in proton experimental.

# Compatibility Report
- Name of the game with compatibility issues: Horizon Zero Dawn
- Steam AppID of the game: 1151640

## System Information
- GPU: AMD Radeon RX 6700 XT (navy_flounder)
- Driver/LLVM version: [mesa-git-22.1.20220221](https://copr.fedorainfracloud.org/coprs/xxmitsu/mesa-git/), LLVM 13.0.0, DRM 3.44
- Kernel version:  5.16.9-200.fc35.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/vulturm/de076431e192af78de3fe4cb761efced
- Proton version: 7.0-1 vs Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Proton experimental has regressed the performance for HZD  Proton 6.3 vs 7.0-1.
Performnace with 7.0-1: 
![Proton-7 0-1-mesa-c108a68](https://user-images.githubusercontent.com/1300842/155031951-3f50a728-01ae-4891-93b4-ea9361e8d122.jpg)
Perfomance with proton experimental

![Proton-exp-mesa-c108a68](https://user-images.githubusercontent.com/1300842/155031954-bbc93916-003e-4cba-a5b5-d0c8a94f0d42.jpg)

## Reproduction
I'm using Fedora 35 with [mesa-git copr](https://copr.fedorainfracloud.org/coprs/xxmitsu/mesa-git/), latest fedora provided kernel as of today: 5.16.9-200

Start the game with Ultimate quality preset and the following Display settings:
![game-settings](https://user-images.githubusercontent.com/1300842/155031950-6c9ca6a8-ed24-48a4-a1f4-386ae9a9a3b5.jpg)

Proton logs, if required:
[proton-7.0-1.tar.gz](https://github.com/ValveSoftware/Proton/files/8112336/proton-7.0-1.tar.gz)
[proton-exp.tar.gz](https://github.com/ValveSoftware/Proton/files/8112337/proton-exp.tar.gz)

**Comment by kisak-valve** [comment]
Hello @vulturm, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4125#issuecomment-1047268177.

**Comment by vulturm** [comment]
Hello,

I haven't added it to the other bug report because I considered that this
one is related to performance regression and the other issue is related to
compatibility/game isn't starting/is crashing.. and there are already lots
of post there and it might get lost.

But, if you consider is better that way, then thank you!
