### ISSUE TITLE
Duplicate mount point after invoking make install

### ISSUE THREAD

**Issue by rawlingsr** [ValveSoftware/Proton#5599]
Podman is the recommended build tool, but using it, instead of docker, results in error during compilation. When using the official build instructions from proton 7.0, the a make file invokes podman or docker with a duplicate mount parameter. Docker is fine with this, but podman complains about the duplicate mount destination.

```
make -j16  -f Makefile -w V=1 VERBOSE=1 NO_NESTED_MAKE=1 CONTAINER=1 
Error: /home/seti/projects/proton: duplicate mount destination
make[1]: *** [Makefile.in:118: container-build] Error 125
make[1]: Leaving directory '/home/seti/projects/proton'
make: *** [Makefile.in:32: nested_make] Error 2
```

The podman developers consider the same mount point being mentioned twice in the same invocation to be a bug in whatever script or individual is invoking podman.
[](https://github.com/containers/podman/issues/4217)

Repro steps:
1. Install Podman, but not docker. 
2. Navigate to proton root directory.
3. invoke `./configure.sh`
4. invoke `make install`
5. Observe that the error included above appears. 
I have tried this on Arch and on Fedora, with identical results. 

An example commit of one way this might be resolved can be found here:
https://github.com/setibeings/Proton/commit/e4cd18184e1277734508cddd70cac95ddfc55d21

**Comment by rawlingsr** [comment]
Welp. If I had read all the build instructions more carefully I'd have seen that a separate build directory is recommended. Maybe the instructions could mention creating a parent folder before cloning proton, or something like that.

**Comment by ivyl** [comment]
I'll add an error for the case when `./configure` is invoked from the same top level directory + see what we can improve about the README. Thanks for the feedback :-)
