### ISSUE TITLE
issue with root permissions on other drives

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [ValveSoftware/Proton#56]
So i have a 4tb steam drive i mount in linux its ntfs and games that are installed wont run but if i install those games local they run just fine now i ran steam in term to see what the issue was and it could use the games at all said there was a permission error

**Comment by linkjay** [comment]
Install ntfs-3g and mount your drive that way. That will setup read/write permissions and file permissions properly.

**Comment by sir-maniac** [comment]
See also: https://github.com/ValveSoftware/Proton/issues/82#issuecomment-415099440
