### ISSUE TITLE
Everything has worked great, except joining dedicated servers.

### ISSUE THREAD

**Issue by spexgaelen** [ValveSoftware/Proton#5600]
# Compatibility Report
- Name of the game with compatibility issues: Astroneer
- Steam AppID of the game: 361420

## System Information
- GPU: NVIDIA GeForce RTX 2080 Ti
- Driver/LLVM version: 470.86-1pop0~1637635465~21.10~47710c4 amd64
- Kernel version: 5.15.23-76051523-generic
- Link to full system information report as [Gist](https://gist.github.com/): not provided
- Proton version: Proton-7.1-GE-2

<details><summary>- Computer Information:</summary>

```
    Manufacturer:  System76
    Model:  Thelio
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 9 3900X 12-Core Processor            
    CPU Family:  0x17
    CPU Model:  0x71
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4672 Mhz
    24 logical processors
    12 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Pop!_OS 21.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.15.23-76051523-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12013000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20220119.0

Video Card:
    Driver:  NVIDIA Corporation NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 470.86
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1e07
    Revision Not Detected
    Number of Monitors:  3
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 5760 x 1080
    Primary Display Size: 20.08" x 11.30" (23.03" diag)
                                            51.0cm x 28.7cm (58.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 11264 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Nvidia GPU 91 HDMI/DP

Memory:
    RAM:  32105 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  1100379 MB
    Largest Free Hard Disk Block:  29955 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 0

The runtime information tool is preparing a report, please wait...
```

</details>

[steam-361420.systeminformation.txt.gz](https://github.com/ValveSoftware/Proton/files/8113060/steam-361420.systeminformation.txt.gz)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-361420.log.gz](https://github.com/ValveSoftware/Proton/files/8113030/steam-361420.log.gz)

## Symptoms
-- Unable to connect to dedicated server "Server Full", connects when attempted from windows. No other noticeable issues.

## Reproduction
Connect to dedicated server. Get denied because its "full" despite the server being empty.

**Comment by kisak-valve** [comment]
Hello @spexgaelen, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/243#issuecomment-1047362771.
