### ISSUE TITLE
Civilization 6 regression

### ISSUE THREAD

**Issue by MissyMalaprop** [ValveSoftware/Proton#5601]
# Compatibility Report
- Name of the game with compatibility issues: Sid_Meiers_Civilization_VI
- Steam AppID of the game: 289070

## System Information
- GPU: NVIDIA GeForce RTX 3080 Laptop GPU/PCIe/SSE2
- Driver/LLVM version: NVIDIA 510.47.03
- Kernel version: 5.16.7
- Link to full system information report as [Gist](https://gist.github.com/): This is not system or GPU specific, happens on AMD and nvidia GPUs on more than 1 system with different distros.
- Proton version: Experimental as of 02/18/2022

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
This game used to work fine with DX12 mode, **and still does seem to work fine with Proton 7.0-1**, the problem only seems to be with latest _Experimental updates on Feb 18th 2022_.
When using latest Experimental, it only runs for a while (20-30 minutes), and the screen will eventually freeze even though the game is technically still running.  Getting out of the game and killing it is a pain as the Civ6 cursor stays stuck over everything and trying to kill everything command line only.  I assume its something to do with vkd3d changes, as I used to play for many hours with no issues.  I have seen this happen on a friends AMD GPU system and my nvidia GPU system, so its not GPU or driver specific.  I have had to kill my system twice and risk issues due to this, so I will not reproduce it again. FYI, I know there is a Native Linux version of this game, but it runs like total trash and is almost unplayable in giant games, while it runs fantastic in Proton (until this update).

## Reproduction
Just play the game for a while in DX12 mode after latest Experimental as of 02/18/2022

**Comment by kisak-valve** [comment]
Hello @MissyMalaprop, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4068#issuecomment-1047812820.
