### ISSUE TITLE
steamdeck unsuported

### ISSUE THREAD

**Issue by nda-cunh** [ValveSoftware/Proton#5603]
Hello, I don't know where to write this report, but nostale is displayed as unsupported, however this is a bug since proton 6, we can't move the character since this version.

on the other hand run nostale with proton 5 and lower, it works perfectly!

My request:
    force nostale on steamdeck to run with proton 5 or less
    or correct proton 7 to be able to move the character again.

Thanks !

![Capture d’écran de 2022-02-22 15-07-47](https://user-images.githubusercontent.com/40312793/155148690-593f107c-89c2-4ea2-9671-96fe18a76208.png)

**Comment by kisak-valve** [comment]
Hello @hydrasho, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/635#issuecomment-1047859425.
