### ISSUE TITLE
Final Fantasy XIII

### ISSUE THREAD

**Issue by guibou** [ValveSoftware/Proton#5604]
# Compatibility Report
- Name of the game with compatibility issues: Final Fantasy XIII
- Steam AppID of the game: 292120

## System Information
- GPU: Intel Iris XE
- Driver/LLVM version: Mesa 21.3.5
- Kernel version: 5.16.4
- Link to full system information report as [Gist](https://gist.github.com/): 
https://gist.github.com/guibou/d84a33f50dd82cdfa512a3b847604775#file-system-log
(Note the interesting missing VRAM informations).

- Proton version: I tried all of the one available on steam at current time

## I confirm:
- [X] that I haven't found an existing compatibility report for this game. (There are, but not for my GPU)
- [X] that I have checked whether there are updates for my system available.

https://gist.github.com/guibou/d84a33f50dd82cdfa512a3b847604775#file-steam-292120-log

## Symptoms 

I can start the game, I ends on the "launcher", and whatever the settings I'm using, the game fails with the following error message:

![image](https://user-images.githubusercontent.com/9705357/155159326-665c9866-b9aa-483a-a734-7d8fc96f49d3.png)

## Reproduction

Start the game, on the launcher, click `Start game`, and see the error message.

**Comment by kisak-valve** [comment]
Hello @guibou, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1785#issuecomment-1047897520.

**Comment by guibou** [comment]
Ha, thank you. I have missed the existing issue when searching (I'm wondering how, so let's admit that I failed at searching ;)
