### ISSUE TITLE
【startup failure】FINAL FANTASY XIV Online (39210)

### ISSUE THREAD

**Issue by TANE1978** [ValveSoftware/Proton#5608]
# Compatibility Report
- Name of the game with compatibility issues:FINAL FANTASY XIV Online
- Steam AppID of the game:39210
- I've encountered a glitch and am following the recommendations of the steam support guide.

## System Information
- GPU: RADEON RX6700XT
- Driver/LLVM version: Mesa 22.1.0-devel (git-7ec8a32 2022-02-22 jammy-oibaf-ppa
- Kernel version: 15.0-18-generic(Kubuntu 22.04 dairy)
- Link to full system information report as [Gist](https://gist.github.com/): [https://gist.github.com/TANE1978/1b91ce7b4030eaf79a85b2c5a62c6391](url)
- Proton version:Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
[steam-39210.log](https://github.com/ValveSoftware/Proton/files/8121979/steam-39210.log)

## Symptoms 
The program itself closes immediately after pressing the start button.
The program itself does not start even if I set it to Browser 1 in FFXIV_BOOT.cfg. Even if I set it to 0 or 2, it doesn't start at all.
There is a possibility that I am making a rudimentary mistake, but since the program does not start even after modifying the config file, it is difficult to search beyond it, so I reported it.

## Reproduction
1.Just press the PLAY button.
2. The "Preparing to start" progress bar will appear.
3. The "Playing" button will change to "Play".
4. Game launch fails

**Comment by TANE1978** [comment]
It seems that the game could not be launched due to a permission-related problem 
since it was installed on an NTFS-formatted SSD.

I reformatted the SSD with Ext4 and mounted it.
I was able to update the game anyway.

I haven't gotten into the game yet, but I think it should be fine.

**Comment by kisak-valve** [comment]
Hello @TANE1978, using NTFS with Proton is known to be finicky and as you've found, using a Linux native filesystem is recommended.

In general, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #580, but it sounds like you've resolved your immediate issue. Feel free to add any other compatibility details you encounter with this game to that compatibility report. Closing per the last comment.
