### ISSUE TITLE
DOOM (2016) Mouse movement after alt-tab cycle causes CPU spikes

### ISSUE THREAD

**Issue by Fenix2412** [ValveSoftware/Proton#561]
Distro: openSuse Tumbleweed 20180820
CPU: AMD Ryzen 5 2600 @ 4.0 GHz
GPU: Asus RX 580 8 GB
Kernel version: 4.18.0
GPU drivers: AMDGPU with Mesa 18.1.6

I've recently started playing DOOM (2016) through Steam Play and I've noticed that after I alt-tab from the game and then back into it my game would stutter when I move my mouse. The ingame performance metric also revealed the problem. Before alt-tabbing out of the game "CPU max" would max out at 14 - 16 when moving the mouse constantly. After an alt-tab cycle that value would rise to 45 - 65 during constant mouse movement causing large fps drops and stuttering. The game is running on a vulkan renderer.

**Comment by Fenix2412** [comment]
It looks like it's caused by a high polling rate of my mouse. Dropping it down from 1000 Hz to 500 Hz seems to fix the problem.

**Comment by Fenix2412** [comment]
Seems to be related to issue #147

**Comment by kisak-valve** [comment]
Hello @Fenix2412, I'm going to close this in favor of #147. If that issue is resolved and you're still seeing this issue, give me a ping and I can re-open.
