### ISSUE TITLE
Sea of Thieves - Mouse Capture Broken in Proton 7

### ISSUE THREAD

**Issue by JoeRLDuncan** [ValveSoftware/Proton#5610]
# Compatibility Report
- Name of the game with compatibility issues: Sea of Thieves
- Steam AppID of the game: 1172620

## System Information
Proton 7.0-1

<details><summary>System Information</summary><p>

```
Computer Information:
    Manufacturer:  MSI
    Model:  X99S GAMING 7 (MS-7885)
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
    CPU Family:  0x6
    CPU Model:  0x3f
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3600 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux Mint 19.3 Tricia (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.4.0-99-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12008000
    X Window Manager:  Metacity (Marco)
    Steam Runtime Version:  steam-runtime_0.20211207.0

Video Card:
    Driver:  NVIDIA Corporation NVIDIA GeForce GTX 970/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 470.103.01
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 20.91" x 11.77" (23.98" diag)
                                            53.1cm x 29.9cm (60.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  15903 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Total Hard Disk Space Available:  468426 MB
    Largest Free Hard Disk Block:  121487 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 0
```

</details>

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
    - none that have reported this issue
- [x ] that I have checked whether there are updates for my system available.

I added  `PROTON_LOG=1 %command%` to the game's launch options but there wasn't any log file generated in $HOME/steam-$APPID.log, sorry.

## Symptoms 
Prior to Proton 7, proton would capture the mouse properly in Sea of Thieves, and I would have to alt-tab to get out. Now, Sea of Thieves frequently loses mouse capture altogether resulting in input not being received by the game, and the mouse exiting the game window at in opportune times :(

Please restore the previous mouse capture functionality, it worked just fine. This is broken.

## Reproduction
1 - Run Sea of Thieves in Linux with Proton 7
2 - Open a radial menu (e.g. the item menu)
3 - Notice the mouse is no longer properly captured
4 - Try to use the keyboard shortcuts for the radial menu

Expected result: menus should work
Actual result: 9 times out of 10 they don't

**Comment by kisak-valve** [comment]
Hello @JoeRLDuncan, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3931#issuecomment-1049089690.
