### ISSUE TITLE
Train Sim World 2 (1282590)

### ISSUE THREAD

**Issue by Carlgo11** [ValveSoftware/Proton#5612]
# Compatibility Report
- Name of the game with compatibility issues: Train Sim World 2
- Steam AppID of the game: 1282590

## System Information
- GPU: GTX 1080
- Driver/LLVM version: 4.6.0 NVIDIA 470.103.01
- Kernel version: 5.13.0-30
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Carlgo11/7e80a509e09971af64f46e5efc5cc127
- Proton version: 7.01 & Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1282590.log ](https://gist.github.com/Carlgo11/423e498d2f31450b25f01dd12db8b3bb)

## Symptoms
Game returns error saying VisualStudio C++ and DirectX runtimes are missing.
Log reveals that VS C++ DLLs can't be found as the program searches for the files [in uppercase](https://gist.github.com/Carlgo11/423e498d2f31450b25f01dd12db8b3bb#file-steam-1282590-log-L1138-L1139) while the actual DLL files are lowercase. Renaming the files to uppercase fixes VS C++ Runtime not being found but I'm unable to find DirectX errors in the log.

![screenshot - error](https://camo.githubusercontent.com/db0da6d73d26d6f2b3704a0311a9ec6beb3e284f91f854895a5a723ccf833b82/68747470733a2f2f642e74656d7066696c65732e646f776e6c6f61642f44363231374645433434383533392f3f703d3338315a4978554264453046636770)

## Reproduction

1. Download [TSW2](https://store.steampowered.com/app/1282590/Train_Sim_World_2/)
2. Start the game

**Comment by kisak-valve** [comment]
Hello @Carlgo11, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4142#issuecomment-1050315179.
