### ISSUE TITLE
Elden Ring EAC

### ISSUE THREAD

**Issue by wcaglia** [ValveSoftware/Proton#5614]
# Compatibility Report
- Name of the game with compatibility issues: Elden Ring
- Steam AppID of the game: 1245620

## System Information
OS: Arch Linux
KERNEL: 5.16.10-zen1-1-zen
CPU: AMD Ryzen 9 3900X 12-Core
GPU: NVIDIA GeForce GTX 1070 Ti
GPU DRIVER: NVIDIA 510.54
RAM: 16 GB
[steam-1245620.log](https://github.com/ValveSoftware/Proton/files/8137284/steam-1245620.log)

https://gist.github.com/wcaglia/76fed4c7c336f626cd9a4bc53bb71159)
- Proton version: Tried 7.0, expiremental, and latest untested beta expirmental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Failed to load anti cheat

## Reproduction
Attemptto launch Elden Ring using Proton.

**Comment by netthier** [comment]
Has anyone tried a Proton build including https://github.com/ValveSoftware/Proton/commit/35a4101ac8bbf914304d35dc8d1d965aa7d29773 yet?

EDIT: I tried manually patching the proton executable and copying the eos library files to the mixed-case variants, but neither fixed the error.

**Comment by wcaglia** [comment]
> Has anyone tried a Proton version including [35a4101](https://github.com/ValveSoftware/Proton/commit/35a4101ac8bbf914304d35dc8d1d965aa7d29773) yet?
I tried Proton Experimental [bleeding-edge], no luck, same error.

**Comment by zupatisc** [comment]
Maybe the `-noEAC` flag can help?

**Comment by kisak-valve** [comment]
Hello @wcaglia, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1050388728.
