### ISSUE TITLE
Document how to properly file bug reports

### ISSUE THREAD

**Issue by ryao** [ValveSoftware/Proton#562]
I have refrained from filing bug reports because I don't know how to get the wine log to include when a failure happens. It would be nice if some documentation describing what to capture and how to capture it to aid in filing useful bug reports was written. See the zfsonlinux issue tracker for an example of one say of doing this:

https://github.com/zfsonlinux/zfs/issues/new

There is some documentation on it here:

https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by Thinkaboutmin** [comment]
#266

**Comment by kisak-valve** [comment]
Closing in favor of #266.
