### ISSUE TITLE
Audio Regression in Guilty Gear -STRIVE- (app ID 1384160) under Proton 7.0 and higher

### ISSUE THREAD

**Issue by Ilazki** [ValveSoftware/Proton#5622]
Guilty Gear Strive was working well with Proton 6.3, but with Proton 7.0 and Proton Experimental the audio becomes extremely choppy, making the game unplayable under newer Proton versions.  Didn't notice any errors or new messages in the console log, so not much useful info to provide beyond that.

**Comment by kisak-valve** [comment]
Hello @Ilazki, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4894#issuecomment-1052121060.
