### ISSUE TITLE
Dinner with an Owl (1567420)

### ISSUE THREAD

**Issue by Mephistople** [ValveSoftware/Proton#5623]
# Compatibility Report
- Name of the game with compatibility issues: Dinner with an Owl
- Steam AppID of the game: 1567420

## System Information
- GPU: NVIDIA GeForce RTX 2080 Ti Rev. A
- Driver/LLVM version: 510.54
- Kernel version: 5.16.7-1-MANJARO
- [System Info](https://gist.github.com/Mephistople/f441b038726ab26ced3ff637f4892d5c)
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
   [steam-1567420.log](https://github.com/ValveSoftware/Proton/files/8146471/steam-1567420.log)

## Symptoms 
When I hit play, it says that the games running but no game ever opens.

## Reproduction
1. Install game
2. Hit play
3. Observe the game is not starting.

In the game folder the game is located there is an .exe file called Settings.
If you open it in regular wine, it gives you the option to choose from either OpenGL, DX9 or DX11.
You can also choose between windows mode or fullscreen.
Have tried all different combinations, witch none of them worked.
By default it's set to DX11 in full screen.

![Settings](https://user-images.githubusercontent.com/53997310/155841985-9e09ec08-78fa-4fa7-8741-439c9390030d.jpg)

**Comment by kisak-valve** [comment]
Hello @Mephistople, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5373#issuecomment-1052123567.
