### ISSUE TITLE
Unable to use Proton from Steam client on Windows game demos

### ISSUE THREAD

**Issue by MouseOfMadness** [ValveSoftware/Proton#5626]
To way launch a Windows game on Linux from the Steam client using Proton is to enable compatibility mode from the library, but the client refuses to add a Windows only demo to the library citing the incompatible OS. Even though Proton would most likely run the demo just fine, the user is prevented from even attempting it. This behavior has been tested with a variety of demos from the current Next Fest, but was initially discovered on Small Saga.

I worked my way through Steam support until I was advised to report the bug here.

**Comment by kisak-valve** [comment]
Hello @MouseOfMadness, the download of game content and the OS platform override to allow Windows content to be run through the Steam for Linux client is managed by the Steam client, not Proton itself.

Please give https://github.com/ValveSoftware/steam-for-linux/issues/7877 a read as the original report in that issue report covers this scenario.
