### ISSUE TITLE
Forager crashes almost instantly after trying to start

### ISSUE THREAD

**Issue by linus-jansson** [ValveSoftware/Proton#5628]
# Compatibility Report
- Name of the game with compatibility issues: Forager
- Steam AppID of the game: 751780

## System Information
- GPU: NVIDIA GeForce RTX 2060
- Driver/LLVM version: nvidia 510.54
- WM: dwm
- Kernel version: 5.16.11-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/linus-jansson/556f31a7cae4eba472d01ddee2a0c1a9):
- Proton version: 7.0-1, Experimental and 6.3-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

No logs are found even after setting  `PROTON_LOG=1 %command%` in the game's launch options. No logs are produced even though a create `$HOME/Proton/` and specify `PROTON_LOG=1 PROTON_LOG_DIR=~/Proton %command%`
```
> ls $HOME
Desktop  Downloads  Github  Pictures
```

## Symptoms 
- Game starts with a blackscreeen taking up half of the display (dwm tiles), then instantly crashes after 3-5 seconds. Tested with proton 7.0-1, Experimental and 6.3-8

## Reproduction
1. Launch forager
2. Window pops up
3. Window closes

**Comment by kisak-valve** [comment]
Hello @linus-jansson, Forager has a native Linux variant. Are you sure that your testing was with Proton? Please go to the game in Steam's library view and click the ⓘ symbol on the right side and see if the additional information includes a like that reads something like `Runs on this computer via Steam Play. Proton # selected by you for this title.` If that line does not show, then Proton is not involved and this feedback should be directly mentioned to the game's dev(s).

**Comment by linus-jansson** [comment]
Seems like it ran with the native version.. Tried forcing it to launch with proton eperimental and it worked out of the box. 
Thank you!
