### ISSUE TITLE
Age of Empires IV (1466860)

### ISSUE THREAD

**Issue by atif-rehman-ideofuzion** [ValveSoftware/Proton#5629]
When I first installed the game it would start only sound and faded color gradients would flicker on the screen. Upon pressing a key cursor also appear with a normal game sound but the color remains faded and nothing shows up on the screen.

What have I tried so far?
1. Update NVIDIA drivers - Game never started DXGIFACTORY FAILURE.
2. Used previous version of proton 7-0-1 ... up to 3 - NONE WORKED DXGI FACTORY FAILURE
3. Restored nvidia drivers, reinstalled Proton Experimental. DID NOT WORK DXGI FACTORY FAILURE.
4. https://www.protondb.com/app/1466860
followed above link with launch option and mp-fix script. DID NOT WORK DXGI FACTORY FAILURE.
5. REINSTALLED GAME - REINSTALLED PROTON - Now game is back to showing blured screen and sound only.

WARNINGS.log
[warnings.log](https://github.com/ValveSoftware/Proton/files/8153627/warnings.log)

Attaching screenshot of loaded game.
![image](https://user-images.githubusercontent.com/50943809/155991402-0feb3d1a-20d3-46bb-8d74-118ecf2d2ee1.png)

What can i do?

**Comment by kisak-valve** [comment]
Hello @atif-rehman-ideofuzion, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5258#issuecomment-1054270498.
