### ISSUE TITLE
Elden Ring does not launch

### ISSUE THREAD

**Issue by R3D4CT3D1** [ValveSoftware/Proton#5630]
# Compatibility Report
- Name of the game with compatibility issues: ELDEN RING
- Steam AppID of the game: 1245620

## System Information
- GPU: NVIDIA GeForce GTX 1660 Ti
- Driver/LLVM version: 510.54-3
- Kernel version: 5.16.11-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/R3D4CT3D1/82fcb6f7f384805136b58ed0b8db61c2
- Proton version: Proton Experimental with bleeding edge beta 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1245620.log](https://github.com/ValveSoftware/Proton/files/8159441/steam-1245620.log)

## Symptoms 

Game does not start.

## Reproduction

Clicking the play button.

**Comment by larouxn** [comment]
Looks like there's an issue with discussion over here:
- https://github.com/ValveSoftware/Proton/issues/5613

**Comment by kisak-valve** [comment]
Hello @R3D4CT3D1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1055449367.

**Comment by laichiaheng** [comment]
It doesn't work with the latest Proton Experimential Beta Bleeding Edge build.
The game crashes immediately.
