### ISSUE TITLE
Winetricks GUI zenity libwebkit2gtk-4.0.so.37 undefined symbol gst_element_request_pad_simple in libgstreamer-1.0.so.0.1805.0

### ISSUE THREAD

**Issue by noabody** [ValveSoftware/Proton#5631]
Wine 7.0 based Steam Proton with installed libgstreamer-1.0.so.0.1805.0 (Proton 7.0/Experimental).  Related to - [Bug 2000563  - gnome-control-center - undefined symbol error](https://bugzilla.redhat.com/show_bug.cgi?id=2000563).  

Symbol ```gst_element_request_pad_simple``` missing from ```libgstreamer-1.0.so.0.1805.0```

Related to feature request:  [Prefer the system gstreamer libs over Proton gstreamer libs #5424 ](https://github.com/ValveSoftware/Proton/issues/5424)

I use custom prefix 0 with my tool [wstart](https://noabody.wordpress.com/2021/10/04/wstart/) to launch winetricks with proper environment where LD_LIBRARY_PATH must be used to prioritize Steam Proton Libraries over OS provided.  

Removing LD_LIBRARY_PATH from command (or deleting Proton libgstreamer-1.0.so.0.1805.0) allows GUI to run since we revert to Manjaro 21.2.4 libgstreamer-1.0.so.0.2000.0 which contains the symbol.

Winetricks without GUI seems to work.

Command: 
```"env" "PATH=/home/user/.local/share/Steam/steamapps/common/Proton 7.0/dist/bin:/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/home/user/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin" "WINEDLLPATH=/home/user/.local/share/Steam/steamapps/common/Proton 7.0/dist/lib64/wine:/home/user/.local/share/Steam/steamapps/common/Proton 7.0/dist/lib/wine" "LD_LIBRARY_PATH=/home/user/.local/share/Steam/steamapps/common/Proton 7.0/dist/lib64:/home/user/.local/share/Steam/steamapps/common/Proton 7.0/dist/lib" "WINEPREFIX=/home/user/.steam/steam/steamapps/compatdata/0/pfx" "STEAM_COMPAT_DATA_PATH=/home/user/.steam/steam/steamapps/compatdata/0" "STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/user/.steam" winetricks --gui```

Result: 
```zenity: symbol lookup error: /usr/lib/libwebkit2gtk-4.0.so.37: undefined symbol: gst_element_request_pad_simple
winetricks GUI enabled, using zenity 
Executing mkdir -p /home/user/.steam/steam/steamapps/compatdata/0
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
zenity: symbol lookup error: /usr/lib/libwebkit2gtk-4.0.so.37: undefined symbol: gst_element_request_pad_simple
Using winetricks 20210206-next - sha256sum: fa8e1cac62953f13f0964441eac40097d7054a78852ab5a35c925c78a6e89a65 with wine-7.0 and WINEARCH=win64
zenity: symbol lookup error: /usr/lib/libwebkit2gtk-4.0.so.37: undefined symbol: gst_element_request_pad_simple```

**Comment by kisak-valve** [comment]
Hello @noabody, starting with Proton 5.13, Proton is intended to be run in the Steam Linux Runtime - Soldier container environment. Running the wine executable directly and bypassing the container environment which Proton has been compiled to run inside is unsupportable.
