### ISSUE TITLE
Age of Empires 2: Definitive Edition (Alt+Tab hangs Window Manager) 

### ISSUE THREAD

**Issue by ziprasidone146939277** [ValveSoftware/Proton#5636]
# Compatibility Report
- Name of the game with compatibility issues: Age of Empires 2: Definitive Edition
- Steam AppID of the game: 813780

## System Information
- GPU: Intel Mesa Intel(R) HD Graphics 520 (SKL GT2)
- Driver/LLVM version: Mesa 21.3.6
- Kernel version: 5.16.11-200.fc35.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ziprasidone146939277/6878eed41130fff4a0afdff46efb4b20
- Proton version: 7.0-1, 6.3-8, Experimental; Proton-GE 7.1-GE-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
[steam-813780.log](https://github.com/ValveSoftware/Proton/files/8174090/steam-813780.log) (Proton-GE 7.1-GE-2)

## Symptoms

- Crash or (Proton 6, 7)
- Does not start (Proton-GE 7)

Proton 7.1-GE-2: the game does not start anymore.
Proton 7.0-1, 6.3-8: the game starts. If I do alt+tab the whole window manager hangs. Have to move to another TTY and restart gdm.service.

## Reproduction

- Proton 7.1-GE-2:

1. Set the compatibility tool above
2. Start the game (the game never starts like before (Mid Feb.)

- Proton 7.0-1, 6.3-8:
1. Set the compatibility tool above
2. Start the game
3. Press Alt+Tab

Note:
I found that this crash only happens under Gnome Xorg session; if You use Wayland the problem cannot reproduce. The game works fine (only under Wayland session)

Hope this report helps anyone.

Thank You

**Comment by kisak-valve** [comment]
Hello @ziprasidone146939277, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3189#issuecomment-1057587121.
