### ISSUE TITLE
exanima graphics problem

### ISSUE THREAD

**Issue by adcdam** [ValveSoftware/Proton#5637]
Exanima 
steam id 362490

CPU : AMD Ryzen 7 3700X 8-Core Processor             
kernel: 5.16.11
X Server: The X.Org Foundation
X Server version : 12014000
GPU: AMD AMD Radeon RX 5700 (NAVI10, DRM 3.44.0, 5.16.11, LLVM 13.0.1)
 Mesa 21.3.6

the game was working fine until version 0.8.3 they changed the render and  now the game has color graphic artifacts that make it unplayable, in protondb some say its solved using the beta but is not (perhaps a rx5700 problem?) tried both the normal and the beta the color graphics artifacts are there using any proton version, some times (very few times) when it start it start without problems, but after restarting the game it has the same graphic glitches.

**Comment by kisak-valve** [comment]
Hello @adcdam, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5450#issuecomment-1057995696.
