### ISSUE TITLE
Whitelist request: Persona 4 Golden

### ISSUE THREAD

**Issue by dylanmtaylor** [ValveSoftware/Proton#5640]
# Whitelist Request
- Name of the game to be whitelisted: Persona 4. Golden
- Steam AppID of the game:1113000

## System Information
Valve steam deck running steam OS 3
- Proton version: 7

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [x] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [x] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

This game is currently listed as incompatible with the Steam Deck but I just got mine today and decided to try it out. With proton version 7, the latest version, it works out of the box and is definitely playable. I didn't have to perform any sort of custom proton installation or anything. There is already an issue for this game but this is the first time that it is being requested to be whitelisted.

**Comment by kisak-valve** [comment]
Hello @dylanmtaylor, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3982#issuecomment-1058545903.
