### ISSUE TITLE
Red Dead Redemption 2 (1174180)

### ISSUE THREAD

**Issue by DeeBeeDouble** [ValveSoftware/Proton#5641]
# Compatibility Report
- Name of the game with compatibility issues: Red Dead Redemption 2
- Steam AppID of the game: 1174180

## System Information
- GPU: Amd Radeon Vega 7
- Driver/LLVM version: 21.3.7-1
- Kernel version: 5.16
- Proton version: Proton 7, 6, Proton-GE 7, 6
- [Gist](https://gist.github.com/DeeBeeDouble/23e80314c5250908ca2865ab779ed8b2)

[steam-1174180.log](https://github.com/ValveSoftware/Proton/files/8181840/steam-1174180.log)

After I spend some time in the game, the video driver and with it the game and my entire desktop crashes.
The problem here is RADV. When I have AMDVLK installed, the crash doesn't appear anymore. However, full screen doesn't work, the fps are worse, and I could spot a few graphical issues, so AMDVLK is not really an option. I have created a [mesa issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/5810#note_1220363), (take a look over there if you need more information) but that didn't get me anywhere, so now I'm trying it here.

Reproduction
1. Start the game.
2. Play the game for about 5 to 30 minutes. Do some missions or just move around. So far, it didn't happen without me moving to different locations.
3. Enjoy your crashed pc.

I would really love to play this game, so I would be very happy to find any better solution than AMDVLK. Have a nice day everyone ;)

**Comment by kisak-valve** [comment]
Hello @DeeBeeDouble, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-1058670047.
