### ISSUE TITLE
Elder Scrolls Online: Minion App

### ISSUE THREAD

**Issue by Arcitec** [ValveSoftware/Proton#5645]
# Compatibility Report
- Name of the game with compatibility issues: Minion (https://minion.mmoui.com/?download) for Elder Scrolls Online. It's the official way to install addons for this MMO.
- Steam AppID of the game: 306130

## System Information
- GPU: RTX 3090
- Driver/LLVM version: 510.47.03
- Kernel version: 5.16.11
- Proton version: 7.0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

The application works well with Wine-Staging or Wine-TKG.

Under Proton, it crashes with:

```
wine: Unhandled page fault on execute access to 0000000000000000 at address 0000000000000000 (thread 0024), starting debugger...
```

## Reproduction

1. Download Minion from https://minion.mmoui.com/?download
2. Run the installer with Steam Proton. It works and lets you install the application.
3. Now try starting the application.
4. Instant crash with null pointer. This doesn't happen when using Wine-Staging or Wine-TKG instead.

**Comment by Arcitec** [comment]
Chances are that this crash is something that affects a ton of applications under Proton. Since this null-pointer bug doesn't exist in Wine-Staging or Wine-TKG. Some emulated Windows API is returning a null-pointer under Proton.

**Comment by kisak-valve** [comment]
Hello @Bananaman, we're using one issue report per unofficially supported game title (including mods), so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/556#issuecomment-1059171727.
