### ISSUE TITLE
Minecraft Dungeons Freezing & crashing at random

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#5647]
# Compatibility Report
- Name of the game with compatibility issues: Minecraft Dungeons
- Steam AppID of the game: 1672970

## System Information
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/coreybruce/dcd2bec911594c9212d351ac2e7a3f98
- Proton version: 7.0.1

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

Log via gist: https://gist.github.com/coreybruce/3aa6949fc10a42194fbc85d0f55c0131

## Symptoms 
Will freeze at ranmdom, sometimes crash
## Reproduction

Run game using proton 7.0.1

**Comment by kisak-valve** [comment]
Hello @coreybruce, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5246#issuecomment-1059720840.
