### ISSUE TITLE
MIR4 (1623660)

### ISSUE THREAD

**Issue by M4rQu1Nh0S** [ValveSoftware/Proton#5648]
The game open but not respond anymore while patch download.
[steam-1623660.log](https://github.com/ValveSoftware/Proton/files/8191225/steam-1623660.log)

**Comment by kisak-valve** [comment]
Hello @M4rQu1Nh0S, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5405#issuecomment-1059813235.
