### ISSUE TITLE
VRChat has huge shader precache on Steam

### ISSUE THREAD

**Issue by tamara-schmitz** [ValveSoftware/Proton#5656]
# Compatibility Report
- Name of the game with compatibility issues: VRChat
- Steam AppID of the game: 438100

## System Information
- GPU: AMD Custom GPU 0405 Vangogh
- Driver/LLVM version: Mesa 22.0.0-devel (git-676ccacebc) LLVM 13.0.0
- Kernel version: 5.13.0-valve10.1-1-neptune-02144-g7fffaf925dfb
- HW: Steam Deck. Reproducible on other AMD hardware
- Proton version: Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
The shader download size is at least 5 GB. This is due to the huge plethora of content available in the game.
This game thrives on user generated content which is downloaded on demand and is very individual. Therefore having a shared shader cache seems useless as apart from a small set of content the fast majority of cached shader mutations, other players will never get to see.
This also slows down the preprocessing of Vulkan shaders.

## Reproduction
Check the Proton 7.0 or Experimental branch.

**Comment by kisak-valve** [comment]
Hello @tamara-schmitz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1199#issuecomment-1062025121.
