### ISSUE TITLE
Windows games not crash right after launch after moving library and Proton to a new partition

### ISSUE THREAD

**Issue by Vartaghan** [ValveSoftware/Proton#5660]
Intially:
- the whole steam install and library were in the default install folder (~/.steam and ~/.local/share/Steam) in the /home partition which is a LVM volume, with ext4, on a RAID 5 array of HDD. Everything was working fine although loading was very slow.

Now:
- in order to improve performances, I created a new LVM volume, with ext4, using a partition on a NVMe SSD as PV
- this volume mounts on /usr/local
- I created a /usr/local/share/Steam directory owned by my_user:my_group
- I declared this new Steam directory as default installation directory in my Steam library
- I moved all my games and proton installs in this new directory. Only "Steamworks Common Redistributables" was not moved because Steam did not want to.

What happens:
All the native games are launching and running fine.

For all the Windows games, I get the popup saying Steam is preparing to launch the game and when it disappears, he game did not launch and is not seen as running by Steam. It is not listed in my running processes either. It just plain crashed.

What I tried:
Thinking it must have something to do with Proton, I tried to uninstall all Proton versions on my computer, except for Experimental which Steam refused to remove, and launch a game again, forcing a specific version of Proton so it had to be installed anew. It did not work.

I tried to just uninstall a game and reinstall it. It did not work (I expected that).

I tried to empty the compatdata directories both in the old and the new library directories. It did not work.

I tried to symlink the compatdata from the old library directory to the new one. It did not work.

I tried putting PROTON_LOG=1 %command% in a game launch options but the logs do not appear in my /home directory

My system:
See file attached: [system_report.txt](https://github.com/ValveSoftware/Proton/files/8216881/system_report.txt)

**Comment by kisak-valve** [comment]
Hello @Vartaghan, starting with Proton 5.13, Proton is run inside the Steam Linux Runtime - Soldier container environment. This container environment does not support Steam Libraries mounted under /usr/local. Please mount your secondary Steam library somewhere else in you filesystem tree.

Related: https://github.com/ValveSoftware/steam-runtime/issues/288
