### ISSUE TITLE
Strange updating input delay

### ISSUE THREAD

**Issue by HexExecute** [ValveSoftware/Proton#5661]
# Compatibility Report
- Name of the game with compatibility issues: Elden Ring
- Steam AppID of the game: 432247

## System Information
- GPU: GTX 1660 SUPER
- Driver/LLVM version: 510.54
- Kernel version: 5.16
- Proton version: Experimental [bleeding-edge]

- Neofetch:
```
OS: Manjaro Linux x86_64 
Host: B450M DS3H 
Kernel: 5.16.11-2-MANJARO 
Uptime: 5 mins 
Packages: 1587 (pacman) 
Shell: zsh 5.8.1 
Resolution: 1920x1080, 2560x1440 
DE: GNOME 41.4 
WM: Mutter 
WM Theme: Flat-Remix-Magenta-Dark-fullPanel 
Theme: Flat-Remix-GTK-Magenta-Dark [GTK2/3] 
Icons: Vimix-Black-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 2700X (16) @ 3.700GHz 
GPU: NVIDIA GeForce GTX 1660 SUPER 
Memory: 3891MiB 
```

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Strange input delay.

## Reproduction
    1. Hold W key to move forward for 5 seconds.
    2. Release W key.
    3. I will continue to move forward as if I hadn't released it for a couple seconds.
    4. Note: If I move my mouse after releasing W key it will update and I will stop moving.

**Comment by kisak-valve** [comment]
Hello @HexExecute, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1063425623.
