### ISSUE TITLE
[581320] Insurgency: Sandstorm EAC module failure

### ISSUE THREAD

**Issue by Irets** [ValveSoftware/Proton#5662]
# Compatibility Report
- Name of the game with compatibility issues: Insurgency: Sandstorm
- Steam AppID of the game: 581320

## System Information
- GPU:  GTX 1070 
- Driver/LLVM version: LLVM 13.0.1 / nvidia 470.103.01
- Kernel version: 5.15.26
- Link to full system information report as [Gist](https://gist.github.com/Irets/13e76a5afcbcabcd0cd434f5fed12aaf):
- Proton version: 1646943044 experimental-7.0-20220310
[steam-581320.log](https://github.com/ValveSoftware/Proton/files/8227824/steam-581320.log)

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
Upon launching Insurgency: Sandstorm, an EasyAntiCheat splash screen will pop up saying "Launch Error, Failed to load the anti-cheat module" and at this point the only way forward is to click the "Exit" button below the message.

I've tackled with this issue for about a week now and have found a probable source of the problem:
**easyanticheat_linux_x86_x64.eac.metadata** and **easyanticheat_linux_x86_x64.eac** are missing from _~/.steam/steam/steamapps/compatdata/581320/pfx/drive_c/users/steamuser/AppData/Roaming/EasyAntiCheat/eb330869cd5f4881b0a8a0220a8c284d/2324da9a1c0341eea4cf43c070760c75/_.

From my understanding these files should be present after the EAC installer has done it's job when Steam is running the installscript on a fresh prefix, but they never appear, thus causing EAC to bail on game start.

To try to solve this issue, I've tried the following:

- Move Proton Experimental, Proton EasyAntiCheat Runtime and Insurgency:Sandstorm to a ext4 filesystem and reinstall all these titles & tools through Steam. 
- Opt into Steam Experimental Bleeding Edge beta branch 
- Try Proton 7.0 & GE-Proton7-9 
- Wipe the Proton prefix & shadercache folders numerous times
- Copy the missing **easyanticheat_linux_x86_x64.eac.metadata** and **easyanticheat_linux_x86_x64.eac** on to my system from my friend's PC, but EAC will delete these files on game start.
- Copy the whole Proton prefix from my friend's computer and place into _~/.steam/steam/steamapps/compatdata/_
- Attempt to invoke the **EasyAntiCheat_EOS_Setup.exe** with Proton Experimental manually, only to be faced by an empty command prompt which will close shortly after.
- Install Insurgency: Sandstorm on my laptop that resulted in the same issue as in this Issue Ticket.

## Reproduction

- Install Proton EasyAntiCheat Runtime, Proton Experimental and Insurgency: Sandstorm
- Proceed to launch Insurgency: Sandstorm
##
I will include **service.log**, **anticheatlauncher.log** and **loader.log** from _~/.steam/steam/steamapps/compatdata/581320/pfx/drive_c/users/steamuser/AppData/Roaming/EasyAntiCheat_
[service.log](https://github.com/ValveSoftware/Proton/files/8227929/service.log)
[anticheatlauncher.log](https://github.com/ValveSoftware/Proton/files/8227930/anticheatlauncher.log)
[loader.log](https://github.com/ValveSoftware/Proton/files/8227932/loader.log)

Is this the right place to ask for support or report the issue?
I'm not very familar with Github.

Cheers.

**Comment by kisak-valve** [comment]
Hello @Irets, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1651#issuecomment-1064644988.
