### ISSUE TITLE
Elden Ring crashing immediately

### ISSUE THREAD

**Issue by klmkyo** [ValveSoftware/Proton#5669]
# Compatibility Report
- Name of the game with compatibility issues: Elden Ring
- Steam AppID of the game: 245620

## System Information
- GPU: GTX 960m 4GB
- Driver/LLVM version: Nvidia 510.54
- Kernel version: 5.16.13-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/klmkyo/34226dabc7c310f5e6103fdd90ed2a89
- Proton version: Proton Experimental (also tried other recent Proton versions)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
After initiating EAC, the game opens up with a white screen and closes abruptly. Same thing happens in Windows, but in my specific case is fixable by using modded dx12 dll's from [this github](https://github.com/tuffee88/d3d12ProxyEdrDx11_0) (my gpu does not support the level 12_0 required by the game, but this can be fixed with this patch). Was thinking that when using proton this issue would not happen, since my gpu works with Vulkan just fine, but I guess the issue lies somewhere else.

Things I've tried, and some of my findings:
 - I've noticed, by watching nvidia smi while the game boots, that the gpu is not initialised by the time the game crashes
 - Tried steam native, and steam flatpak
 - Tried using both X11 and Wayland
 - Tried using a bunch of enviroment variables, none worked.

## Reproduction
Simply launching the game

## Proton Logs
[steam-1245620.log](https://github.com/ValveSoftware/Proton/files/8237825/steam-1245620.log)

**Comment by kisak-valve** [comment]
Hello @klmkyo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1065908176.
