### ISSUE TITLE
Apex Legends closes immediately after EAC splashscreen opens

### ISSUE THREAD

**Issue by masonnl** [ValveSoftware/Proton#5671]
# Compatibility Report
- Name of the game with compatibility issues: Apex Legends
- Steam AppID of the game: 1172470

## System Information
- GPU: GTX 2060
- Driver/LLVM version: Nvidia Driver: 510.54 | LLVM: 13.0.1
- Kernel version: 5.15.25-1-Manjaro
- Link to full system information report as Gist: n/a
- Proton version: Experimental (Mar 11) & Proton7.0-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1172470.log](https://github.com/ValveSoftware/Proton/files/8238068/steam-1172470.log)

## Symptoms
EAC closes immediately after the splash screen shows. The game does not open and the process closes.

## Reproduction
Without compatibility tools specified OR with Proton7.0-1 OR with Proton Experimental (Mar 11, 2022):
- (without an existing compat folder)
- Press play
- 8/8 install steps complete
- Vulkan shaders build
- EAC splash screen for Apex Legends opens
- EAC closes immediately

## More info:
- `Proton EasyAntiCheat Runtime` has been uninstalled/reinstalled in `.local/share/Steam`
- `Steam Linux Runtime - Soldier` has been uninstalled/reinstalled `.local/share/Steam`
- The game is installed on a separate NTFS drive with the compat data for `1172470/` symlinked to my `.local/share/Steam` similar to other games I have installed in the NTFS drive as encouraged in the [Proton help article](https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows#preventing-ntfs-read-errors). Can confirm other games work fine with this symlink structure.

**Comment by kisak-valve** [comment]
Hello @masonnl, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1065932197.
