### ISSUE TITLE
Elden Ring not launching

### ISSUE THREAD

**Issue by gabrielgcc** [ValveSoftware/Proton#5674]
# Compatibility Report
- Name of the game with compatibility issues: ELDEN RING
- Steam AppID of the game: 1245620

## System Information
- GPU: GTX 1650
- Driver/LLVM version: 4.6.0 NVIDIA 510.54
- Kernel version: 5.16.14-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/gabubonico/2dec26b921a46ac572681953ceec0528
- Proton version: bleeding edge

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

[steam-1245620.log](https://github.com/ValveSoftware/Proton/files/8238725/steam-1245620.log)

## Symptoms 

Instantly crashes when I try to open the game, unable to play it not even the easy-anti cheat screen. Not even able to play offline without internet connection, in game screen doesn't even load before crashing.

## Reproduction

I just click the "Play" button.

**Comment by kisak-valve** [comment]
Hello @gabubonico, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1065988961.
