### ISSUE TITLE
Deus Ex: HR - erratic view jumps

### ISSUE THREAD

**Issue by stixholder** [ValveSoftware/Proton#5676]
# Compatibility Report
- Name of the game with compatibility issues: Deus Ex: Human Revolution
- Steam AppID of the game: 28050

## System Information
- AMD FX-8350  / 16GB
- GPU: AMD RX 580
- Driver/LLVM version: 21.3.7-1
- Kernel version: 5.15.25-1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Moving the mouse to look around causes erratic viewing jumps/skipping of larger parts, i. e. your're turning 90° instantaneously instead of what would be expected according to the mouse movement; the effect gets worse near complex graphic content with many objects.

## Reproduction
Just play the game.

**Comment by stixholder** [comment]
UPDATE: 
I've found a similar issue here, maybe the same problem #590
The game is unplayable under Linux in this state.

**Comment by kisak-valve** [comment]
Hello @stixholder, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/47#issuecomment-1066101614.

**Comment by stixholder** [comment]
UPDATE2:
I was mistaken there - it's not simply a duplicate of #590 and seems not to be a mouse issue in the first place.
The problem seems to be, that visual data is not (pre-)processed in time during movement and also occurs while only using the keys to move, even if not as bad. It's pretty serious and in no way playable anyways. Changing all video settings to lowest/off (also DirectX11) won't help. The graphic 'hickups' also come with short sound echos. To some small extent, also video cutscenes are affected.

**Comment by stixholder** [comment]
UPDATE3:
The exit freeze bug described in #47 hits me EVERY time btw. If I don't task-switch -> rightclick -> close the frozen game timely, it will sometimes exit in an unclean way, leaving all kinds of wine libs and dependencies running, which then require manual kill each.
