### ISSUE TITLE
Deus Ex: HR keypad support buggy

### ISSUE THREAD

**Issue by stixholder** [ValveSoftware/Proton#5677]
# Compatibility Report
- Deus Ex: Human Revolution
- Steam AppID of the game: 28050

## System Information
- GPU: RX 580
- Driver/LLVM version: 21.3.7-1
- Kernel version: 5.15.25-1
- Proton version: 7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The keypad keys are not entirely recognized as KP_0 to KP_9 and so on, most only show as '???' in the keyboard settings menu.
Some keypad keys, that e. g. also act as arrow-keys, DELETE and so on (depending on NUM LOCK status), seem not to be distinguished correctly from corresponding keys, during gameplay, although differently named in the settings menu. 
This is a huge problem, if you want to use keypad for gaming. For instance, KP_ENTER will not work for jumping either.

## Reproduction
Just play the game

**Comment by kisak-valve** [comment]
Hello @stixholder, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/47#issuecomment-1066100728.
