### ISSUE TITLE
Warframe - no sound in game.

### ISSUE THREAD

**Issue by derFeef** [ValveSoftware/Proton#5681]
# Compatibility Report
- Name of the game with compatibility issues: Warframe
- Steam AppID of the game: 230410

## System Information
Steam Deck, Beta branch
- Proton version: Latest Experimental

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

[steam-230410.zip](https://github.com/ValveSoftware/Proton/files/8245290/steam-230410.zip)

## Symptoms 
Warframe does not have sound in game. Tried switching to manual sound device PULSEAUDIO in game without difference. Launcher sound is there.

**Comment by kisak-valve** [comment]
Hello @derFeef, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/167#issuecomment-1066835712.
