### ISSUE TITLE
Apex Legends crashing Steam on Wayland (Manjaro)

### ISSUE THREAD

**Issue by PC-Heini** [ValveSoftware/Proton#5682]
# Compatibility Report
- Name of the game with compatibility issues: Apex Legends
- Steam AppID of the game: 1172470

## System Information
- GPU: Nvidia T600
- Driver/LLVM version: Nvidia 510.54
- Kernel version: 5.16
- Link to full system information report as [Gist](https://gist.github.com/): [System summary](https://gist.github.com/PC-Heini/35cd4ac4dde06b89802e6ff0834740a1)
- Proton version: Experimental

## I confirm:
- [  ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1172470.log](https://github.com/ValveSoftware/Proton/files/8251721/steam-1172470.log)

## Symptoms 
On x11 everything is fine but when I run wayland the game crashes every few minutes and often kills steam while crashing. Running Steam in a terminal got me this: [Steam Terminal output after game has crashed](https://gist.github.com/PC-Heini/6685e52c04f49172ce1f1c52e34912cd)
Steam will never upload these dumps for some reason. Two of the .dmp files:
[assert dmp.zip](https://github.com/ValveSoftware/Proton/files/8251605/assert.dmp.zip)
Wayland on Manjaro is still fairly wonky, especially on Nvidia GPUs but maybe Proton has a part in this.

## Reproduction
Login on a wayland session on Manjaro, start Apex Legends and play for a few minutes.

**Comment by kisak-valve** [comment]
Hello @PC-Heini, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1067933505.
