### ISSUE TITLE
Red Dead Redemption 2 Service Crash

### ISSUE THREAD

**Issue by vars1ty** [ValveSoftware/Proton#5685]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: MSI GeForce RTX 3070 TI
- Driver/LLVM version: nvidia 510.54-7
- Kernel version: 5.15.27-rt35-xanmod1-1-rt
- Link to full system information report as [Gist](https://gist.github.com/qqtc0/81265a2e1695b28fff9a8a85e5e727d2):
- Proton version: Proton Experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-1174180.log](https://gist.github.com/qqtc0/ec56a5fe14f257d8d204ca37f77818bc)

## Symptoms
Launching the game loads the Rockstar Launcher for about 2 seconds before showing an error message, displaying the attached image as error.
![image](https://user-images.githubusercontent.com/54314240/158532915-ef6af96c-02d7-4262-909b-f6a24c646a9c.png)

## Reproduction
Not sure if it can be reproduced for others, as ProtonDB is mainly filled with it working.

It worked the first 1/2 times before this error started occurring, tried with all kinds of different launch arguments, reinstalling the game, trying different kernels and such to no avail.

**Comment by kisak-valve** [comment]
Hello @qqtc0, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-1069089331.
