### ISSUE TITLE
Detect Proton emulation

### ISSUE THREAD

**Issue by Symbai** [ValveSoftware/Proton#5686]
As a developer how can I detect if my app is launched through Proton? I've searched the Wiki but unfortunately its not explained there.

**Comment by kisak-valve** [comment]
Hello @Symbai, Proton, like wine is not an emulator, it's an API/ABI translation layer and games should not bake in assumptions based on if it is being run on Proton. That said, https://wiki.winehq.org/Developer_FAQ#How_can_I_detect_Wine.3F is equally relevant to Proton as it is to upstream wine.
