### ISSUE TITLE
Mouse tracking strange oddities for Apex Legends

### ISSUE THREAD

**Issue by Scout339** [ValveSoftware/Proton#5689]
# Compatibility Report
- Apex Legends
- 1172470

## System Information
- GPU: AMD RX5700 (Gigabyte Windforce)
- CPU: AMD Ryzen 5 2600
- Driver: Out of box proprietary, most up to date with AMD Proprietary drivers
- Kernel version: latest stable from Manjaro [KDE 21.2.4]
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When aiming down sights, mouse tracking is slowed down at times. Specifically when doing fine movements upper-right. May also happen when not ADSing, but I haven't noticed it yet. Confirmed it's not my mouse as it doesn't do this on my windows partition.

## Reproduction
Easily recreated by ADS ingame and doing circles of varying intensity/speed.

**Comment by kisak-valve** [comment]
Hello @Scout339, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1069694146.

**Comment by Scout339** [comment]
Sounds good, thank you!
