### ISSUE TITLE
Graphical Corruption caused by an inability to set whole desktop gamma through driver calls

### ISSUE THREAD

**Issue by LethalManBoob** [ValveSoftware/Proton#5693]
Hello. Please could you revert the changes to:
BOOL usexvidmode
BOOL usexrandr
The changes have caused gamma issues that result in at best, colour banding and at worst extreme graphical corruption.
https://i.imgur.com/uB0KK1N.png

**Comment by kisak-valve** [comment]
Hello @LethalManBoob, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3776#issuecomment-1071240261.
