### ISSUE TITLE
How to launch an app in the same instance of a game

### ISSUE THREAD

**Issue by Symbai** [ValveSoftware/Proton#5697]
Despise everyone here says Proton is not a sandbox, an app running in Proton doesn't see the process of another app running in Proton. But some apps need access to these game processes. How do I launch an app in Proton which uses the same instance of an already running app in Proton so they can see each other?

**Comment by kisak-valve** [comment]
Hello @Symbai, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5766. Closing as a duplicate.
