### ISSUE TITLE
Can`t not using optirun/primusrun when play a non-steam game

### ISSUE THREAD

**Issue by lin-calvin** [ValveSoftware/Proton#5699]
i tried use "optirun %commands%" but it dosn't work
Game is Genshin Impact(with patches)

**Comment by kisak-valve** [comment]
Hello @calvinweb, the issue you've described is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/6046#issuecomment-1006221650. Closing as a duplicate.
