### ISSUE TITLE
Steam Play Compatibility List (Google Docs)

### ISSUE THREAD

**Issue by romulasry** [ValveSoftware/Proton#57]
https://docs.google.com/spreadsheets/d/1DcZZQ4HL_Ol969UbXJmFG8TzOHNnHoj8Q1f8DIFe8-8/edit#gid=0

**Comment by linkjay** [comment]
I think this is better than making an issue for every single game that tests successfully...

**Comment by reversesh3ll** [comment]
Wouldn't it make sense to disallow entries from machines that don't even meet the minimal requirements set by Valve/Proton?

For example: Don't allow an entry if they are not using the latest GPU driver as Valve/Proton has directly specified this as a requirement? Why would they or anyone else care if Ubuntu 14.04 with ancient NVidia drivers crashes a game??

This would clean up the list significantly. Maybe also make it a drop down list on the submission form for the excepted drivers.

**Comment by Askannz** [comment]
Not to mention some of those reports are already outdated. Especially for DX11 games, most of them were submitted before the DXVK debug libs issue fix (https://github.com/ValveSoftware/Proton/issues/192), which had a huge impact on performance.

Ideally, we should have a database very similar to AppDB for Wine.

**Comment by romulasry** [comment]
Yes it should be scripted if possible. Also it should have a script for making logs and push them to a Steam log folder for easy uploading...

**Comment by isaacabrahamjames** [comment]
You can clearly see in the spreadsheet that some games don't work with the latest nvidia driver but work with some of the previous versions. Disallowing entries from people with outdated drivers would be very silly.

**Comment by Sirnanigans** [comment]
I've submitted some rows to this for Endless Legend and have since then discovered more about an issue I was having. Is there a way I should edit my added rows instead of bloating the document with new rows?

**Comment by noraj** [comment]
https://spcr.netlify.com/

**Comment by kisak-valve** [comment]
Closing as this issue report is informational and not actionable.

**Comment by noraj** [comment]
@kisak-valve Yeah the doc what not actionable nor formal but I assume that you are aware of *Steam Play Compatibility Reports* (SCPR) https://spcr.netlify.com/ that is collecting precious information about compatibility.
