### ISSUE TITLE
Spyro™ Reignited Trilogy start prerendered cutscenes are in wrong language

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#5704]
# Compatibility Report
- Name of the game with compatibility issues: Spyro™ Reignited Trilogy
- Steam AppID of the game: 996580

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as Gist: https://gist.github.com/coreybruce/dcd2bec911594c9212d351ac2e7a3f98
- Proton version: 7.0-1

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
watch any cutscenes of games and they will play in the incorrect language when it's set to English on the Steam game settings.

## Reproduction

Play game any of the 3 games on the trilogy

**Comment by kisak-valve** [comment]
Hello @coreybruce, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3035#issuecomment-1073246467.

**Comment by coreybruce** [comment]
This isn't the same issue, my cut scenes run it's just the fact they are in the wrong language.
