### ISSUE TITLE
Random freeze on some titles.

### ISSUE THREAD

**Issue by Selhar** [ValveSoftware/Proton#5708]
Hello, although i saw similar issues related to various games, there doesn't seem to be a post related to proton as a whole.
Some games (right now i can only point towards Pathfinder: Wrath of the righteous and Final fantasy xiv) cause my entire system to freeze, i can't even move to TTY mode. Nothing seems to be logged, i can only get out of it by pressing the power button. I'm not really sure how to debug this issue since i couldn't find anything relevant on journalctl.

This started to happen after i installed an m.2, but it might be a coincidence. I don't remember ever having this issue when i was using an old SSD. 

System info below, i'm willing to try installing other games or doing whatever else would help me debug this issue. Besides current kernel, i've also tried 514, 515 and 516.

![image](https://user-images.githubusercontent.com/8282304/159382911-85d59783-b1b3-447a-bd23-c22da6b210fe.png)

This is a fresh install, i tried leaving x11 as a last ditch attempt but to no avail, same happens under wayland.

Update:
Pathfinder: Kingmaker works flawlessly. Dark souls as well. So far final fantasy xiv and wrath of the righteous are the only ones i face this issue with. In both cases it can happen even in menus, seems to happen entirely randomly.

**Comment by Blisto91** [comment]
@Selhar How does the crash behave? Does it just freeze or does the screen turn weird?
I have seen some people having issues with your type of GPU. But i cant say if it's related.

Here are some issues about the problem [MESA](https://gitlab.freedesktop.org/mesa/mesa/-/issues/4036) & [AMDGPU](https://gitlab.freedesktop.org/drm/amd/-/issues/892)

If you suspect the SSD you could try to run a scan on it to see if it can find issues. Maybe also scan your system memory.

**Comment by Selhar** [comment]
@Blisto91 It just freezes, really. At first the screen stutters a little, then it freezes completely, audio works normally for about 5 seconds, then it freezes as well. It behaves like a proccess that is taking all your memory.

I haven't checked memory since i was never above 50% usage, but i can try checking it later today.

**Comment by Blisto91** [comment]
@Selhar Roger.
You could also try checking if your motherboard BIOS have any updates relating to the m.2 slots. Tho i'm just spitting general support stuff out I guess 😁 
Could you post a steam system information report?

**Comment by Selhar** [comment]
@Blisto91 Yeah i updated my BIOS before installing the M.2, i'm using the latest release atm.

I checked memory usage and it stays under 20%, cpu usage stays below 40%. One thing i noticed this time though is that as soon as the game opens (even before menu), my gpu fans get extremely noisy, i would guess they're going 100%. Do you know of any diagnostics tool that can overlay the game and show me this kinda info? Fan speed, gpu temperatures, etc.. Since everything freezes, overlays are the only way i can run diagnostics. Logs mostly get trashed.

As for steam system, sure thing: https://pastebin.com/LaZVpnSR

**Comment by Selhar** [comment]
Well, some good news kinda. I tried installing windows on an old SSD and playing the same game (wrath of the righteous, since it's relatively easy to reproduce the bug) and.. it froze everything! It's not a proton issue then, for once it's a developer's issue.

**Comment by Blisto91** [comment]
@Selhar Roger.
It's still weird it's freezing everything.
If you updated your bios the same time it started happening i would maybe try to install a earlier version again and see if it goes away

**Comment by weeviltime** [comment]
@Blisto91 has the same suspect that I do. I came from #5722 and after reading this one, windows happens the same, I don't believe its Dev or Proton problem. Has this issues started after updating bios, because you were installing M.2?

**Comment by Selhar** [comment]
@Pobre initially i also thought that, but pathfinder breaking in the same way on both OSes might indicate that something is triggering the freezes, and it's way more frequent under proton (i will try bare wine later on just n case).

I can't really pinpoint if it starter right after updating the bios or shortly before. I remember seeing this issue last year on final fantasy xiv, but since i wasn't playing much i just ignored it. I bought the M.2 this year.

**Comment by weeviltime** [comment]
@Selhar and that's the reason we are saying its not Steam or proton problem. It may be your own computer since in both OS it causes the freeze.
