### ISSUE TITLE
menyo tab not opening in gtav

### ISSUE THREAD

**Issue by ayushlol** [ValveSoftware/Proton#5709]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

**Comment by ayushlol** [comment]
my menoy tab not opening it sowing sing in to social club and i sign in to social club itnot opening .

**Comment by kisak-valve** [comment]
Hello @ayushlol, we're using one issue report per unofficially supported game title. Please add GTA V related feedback to #37.

**Comment by ayushlol** [comment]
my menoy tab not opening it sowing sing in to social club and i sign in to social club itnot opening . GTA V
