### ISSUE TITLE
Wreckfest Online Tournament mode not loading

### ISSUE THREAD

**Issue by bludvig1** [ValveSoftware/Proton#5712]
# Compatibility Report
- Name of the game with compatibility issues: Wreckfest
- Steam AppID of the game: 228380

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 21.3.7 / LLVM 13.0.1
- Kernel version: 5.15.30-1-lts
- Link to full system information: [Gist](https://gist.github.com/bludvig1/7714dbfc361a3b3042f9f309d242029f)
- Proton version: 7.0-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Wreckfest Online Tournament mode not loading

Additional information:
-Tournament mode worked with Proton 5.0-10
-With the latest Wreckfest Getaway Chase Tournament Update the *game* is not loading anymore with Proton 5.0-10, the *game* only loads with Proton 7.0-1 now
-I have checked with Wreckfest developers on their Discord support to make sure that my game files and my Steam Cloud game profile is not corrupted
-I did a full Wreckfest re-install, verified all the game files
-I have created a clean game profile within the game (fresh start with no career progress) but it did not helped
-Online multiplayer works without any problems
-There is nothing blocking the game at the network level (Firewall, etc.)
-The Tournament mode works on Steam + native Windows 10 OS

## Reproduction
1. Launch Wreckfest
2. Click on the 'Tournament' in the Main Menu
3. Game stucked on 'Loading Tournaments..' screen
4. After a few minutes / retries the following appears: 'Error occured while loading tournaments'

[5.0-10_steam-228380.log](https://github.com/ValveSoftware/Proton/files/8331201/5.0-10_steam-228380.log)
[5.13-6_steam-228380.log](https://github.com/ValveSoftware/Proton/files/8331202/5.13-6_steam-228380.log)
[6.3-8_steam-228380.log](https://github.com/ValveSoftware/Proton/files/8331203/6.3-8_steam-228380.log)
[7.0-1_steam-228380.log](https://github.com/ValveSoftware/Proton/files/8331204/7.0-1_steam-228380.log)

<details><summary>Screenshots</summary>

![Screenshot from 2022-03-23 07-50-43](https://user-images.githubusercontent.com/43682171/159655528-391da50b-0645-46c4-992f-b50bd5e64419.png)

![Screenshot from 2022-03-23 08-23-54](https://user-images.githubusercontent.com/43682171/159655553-4a88da57-6458-426a-87d8-eec3c23fa65f.png)

![Screenshot from 2022-03-23 07-50-34](https://user-images.githubusercontent.com/43682171/159655506-40005568-4d6a-40c5-91d7-f4e3380ad7d5.png)

</details>

**Comment by kisak-valve** [comment]
Hello @bludvig1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/758#issuecomment-1076345733.
