### ISSUE TITLE
The Long Dark (305620)

### ISSUE THREAD

**Issue by jchiversAND** [ValveSoftware/Proton#5713]
# Compatibility Report
- Name of the game with compatibility issues: The Long Dark
- Steam AppID of the game: 305620

## System Information
Steam Deck 512GB
- Proton version: 7.0-1, Experimental, 7-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Framerate halves instantly with any camera movement.

Even with minimum graphics settings, 480p resolution, staring directly at the floor, the second you move with either the right or left stick, framerate cuts in half from 60fps to around 35fps.

As soon as you stop moving, framerate returns to 60.

Plenty of performance headroom when not moving, performance bug linked to movement/camera movement.

Unsure how this passed verification as this is a Steam Deck Verified game.

## Reproduction
Stand still, check fps
Move character or camera, framerate drops almost half

**Comment by kisak-valve** [comment]
Hello @jchiversAND, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3892#issuecomment-1076721366.
