### ISSUE TITLE
Spyro™ Reignited Trilogy microstutters at random

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#5721]
# Compatibility Report
- Name of the game with compatibility issues: Spyro™ Reignited Trilogy
- Steam AppID of the game: 996580

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as GIST: https://gist.github.com/coreybruce
- Proton version: 7.0-1

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 
Game will microstutter at times while playing the game

## Reproduction
Play game

**Comment by kisak-valve** [comment]
@coreybruce, again, we're using one issue report per unofficially supported game title. Please use #3035 for all feedback related to this game.

Issue report transferred to https://github.com/ValveSoftware/Proton/issues/3035#issuecomment-1078995953.

**Comment by coreybruce** [comment]
I know @kisak-valve but I don't know where to make the report so I know if I do it will be moved to the correct place to be looked over.

**Comment by kisak-valve** [comment]
You can put the game's appid into the search box for this issue tracker, and if there's compatibility report for that particular game already, then adding a comment to the existing issue report with your findings is preferable to generating issue reports that you know will get moved.

**Comment by coreybruce** [comment]
> You can put the game's appid into the search box for this issue tracker, and if there's compatibility report for that particular game already, then adding a comment to the existing issue report with your findings is preferable to generating issue reports that you know will get moved.

Oh alright I didn't even know that, thanks!
