### ISSUE TITLE
Freezing on various games, multiple proton versions.

### ISSUE THREAD

**Issue by Selhar** [ValveSoftware/Proton#5722]
Yesterday i posted [this issue](https://github.com/ValveSoftware/Proton/issues/5708) and while i thought it was a gpu problem, i'm not sure anymore. Rome total war 2 works flawlessly on windows, but doesn't even load on linux, it freezes my entire computer.

Can anyone help me debug that? I really don't know what else to try here or where the problem might be coming from.

TL;DR:
- Games that previously worked now freeze my computer. It freezes like when you're out of memory, at first the visuals freeze, then audio bugs out and keyboard becomes unresponsive. Memory and cpu usage don't get past 30% ever though. I can't really pinpoint when this started to happen, due to work i haven't played games in a while.
- Final fantasy xiv, Pathfinder: wrath of the righteous and rome 2 are some examples of games that barely load a map before freezing. Although in final fantasy i can walk around for a few minutes. On Rome total war 2 the game completely freezes during loading screen, and on Wrath it freezes during initial cutscene.
- Other games works without any hiccups. Examples are Dark souls 1 and pathfinder: kingmaker. I can try other games, just give me what kind of game you want me to try out.
- While rome 2 works on windows, pathfinder wrath of the righteous breaks both on windows and on linux, which is puzzling.
- Tried different kernels, distros, proton versions, x11 and wayland, glorious eggroll, dx9, dx10, dx11, vulkan and openGL, RAM frequencies and gpu settings. Same behavior in all cases.

Steam system info: https://pastebin.com/SM6dSive
Proton log when attempting to load a total war map (couldn't use pastebin because it's just too much text): https://pastebin.com/SM6dSive

**Comment by Selhar** [comment]
Yeah, since this is happening across different OSes, probably not a proton issue. If someone has any light on this issue feel free to drop a comment, it'd be terribly helpful.

**Comment by Blisto91** [comment]
My input would still be to try a earlier BIOS version if it's possible.
