### ISSUE TITLE
No force feedback on either Automobilista 2 or Assetto Corsa Competizione

### ISSUE THREAD

**Issue by Draluy** [ValveSoftware/Proton#5724]
# Compatibility Report
- Name of the game with compatibility issues: Automobilista 2 and Assetto Corsa Competizione
- Steam AppID of the game: 1066890 and 805550

## System Information
- GPU: AMD AMD Radeon RX 5700 XT
- Driver/LLVM version:  (NAVI10, DRM 3.41.0, 5.13.0-37-generic, LLVM 12.0.1)
- Kernel version:  5.13.0-37-generic
- Link to full system information report as [Gist](https://gist.github.com/):  https://gist.github.com/Draluy/9fba014c2bcef2fcb8e89b01051c53be
- Proton version: Experimental or 6.3-8
I am using a Thrustmaster T248.

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

No force feedback in both games, even if the controller is recognized correctly. I can play the game, but there is a uniform resistance of the wheel, with no proper force feedback felt.

## Reproduction

Launch any of the games in proton experimental or 6.3-8, and feel no feedback. I am using a Thrustmaster T248.

**Comment by Draluy** [comment]
[steam-805550.zip](https://github.com/ValveSoftware/Proton/files/8354251/steam-805550.zip)

**Comment by kisak-valve** [comment]
Hello @Draluy, to me, this reads like something that needs to be evaluated on a per-game basis. Feel free to also add a note to #3748 and #1420 where those games are being discussed.

Tracking note: Issue report not summary transferred because it's unclear if there's a common element between these two games.

**Comment by Draluy** [comment]
@kisak-valve  Ok, I added a note on both tickets, but I believe this issue should be addressed separately. The fact that fftest does not work seems like a problem with the device (see https://github.com/scarburato/hid-tminit). I'm not tech savvy enough to know if this is a problem with the kernel driver, or steam input, or proton...

**Comment by Draluy** [comment]
So, the general solution to my problem was to use the t248 branch of the https://github.com/Kimplul/hid-tmff2/ project.
THere are still proton problems, than relate to each game separately. Closing this issue to keep conversation purposelful.
