### ISSUE TITLE
Quake Champions (611500)

### ISSUE THREAD

**Issue by virnik0** [ValveSoftware/Proton#5728]
# Compatibility Report
- Name of the game with compatibility issues: Quake Champions
- Steam AppID of the game: 611500

## System Information
- GPU: GTX1650
- Driver/LLVM version: NVIDIA 510.54
- Kernel version: 5.15.0-23-generic
- Link to full system information report as [[Gist](https://gist.github.com/virnik0/3a1ac67fd099fe43b28adef01c498000)]
- Proton version: 6.3-8, 7.0-1, Experimental

## I confirm:
- [ * ] that I haven't found an existing compatibility report for this game.
- [ * ] that I have checked whether there are updates for my system available.

Application log attached: [steam-611500.log.gz](https://github.com/ValveSoftware/Proton/files/8358614/steam-611500.log.gz)

## Symptoms
- The game doesn't start
- If started with Proton 6.3-8, the game starts loading while briefly showing black screen...then returns to the desktop.
- If started with Proton 7.0-1 or Experimental, the game starts to load, then shows Quake Champions logo on black background - my screen blinks, and that is it....back to desktop
- Started past 2022-03-24 Quake Champions update, which introduced upgraded AntiCheat protection

## Reproduction
Start the game (**launch options:** `__GL_SHADER_DISK_CACHE=1 __GL_THREADED_OPTIMIZATION=1 PROTON_NO_GLSL=1 PROTON_ENABLE_NVAPI=1 VSYNC=0 PROTON_NO_ESYNC=1 WINEFSYNC=1 PROTON_NO_FSYNC=0 DXVK_ASYNC=1 ENABLE_VKBASALT=1 VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json %command%` )

FYI: The same symptoms are with Quake Champions PTS.

**Comment by kisak-valve** [comment]
Hello @virnik0, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/225#issuecomment-1080043716.

**Comment by virnik0** [comment]
> Hello @virnik0, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#225 (comment)](https://github.com/ValveSoftware/Proton/issues/225#issuecomment-1080043716).

Thanks. Didn't know that rule.

**Comment by virnik0** [comment]
After QC update today, Proton behaves the same like during the last case - black window, nothing else happens. I assume they have updated anti-cheat or something similar again?

Using Proton bleeding edge.
