### ISSUE TITLE
Elden Ring Does Not Start

### ISSUE THREAD

**Issue by AlexanderWMacFarlaneIV** [ValveSoftware/Proton#5729]
I am trying to start Elden Ring on Linux Mint with Proton Experimental.

It pops up a box that says "Preparing to Launch Elden Ring" then another one with a picture in it that says "Initializing", and then it terminates.

I do not think this is a problem with my computer or setup since several other Windows games run fine on Steam.
The game was recently updated and I suspect the Easy Anti-Cheat system is somehow preventing it from starting.

Alex

**Comment by kisak-valve** [comment]
Hello @AlexanderWMacFarlaneIV, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1080638841.
