### ISSUE TITLE
Forza Horizon 5 Stuttering Issue

### ISSUE THREAD

**Issue by robotman40** [ValveSoftware/Proton#5730]
## System Information
- GPU: Rx 6600 XT
- CPU: Ryzen 5 5600X
- Driver/LLVM version: Latest Mesa
- Kernel version: 5.16
- OS: PopOS 21.10
- Proton version: 7.0 and experimental

## Game Info
Game: Forza Horizon 5
AppID: 1551360
## Problem with the game

My problem right now with Forza Horizon 5 is that it has a weird stuttering issue when driving at high speeds. Linus Tech Tips experienced a similar issue on the Steam Deck, so I don't know why Forza Horizon 5 is marked as playable on Steam Deck.

So please fix the stuttering issue

## Reproduction
Run it on Linux through Proton (either 7.0 or experimental), then drive at fast speeds for the stuttering to kick it (It doesn't happen when moving slowly or doing nothing).

**Comment by kisak-valve** [comment]
Hello @GalacticalEdge, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5285#issuecomment-1081214112.
