### ISSUE TITLE
TheHunter - Call of the Wild // Linux Mint

### ISSUE THREAD

**Issue by FluffyFoxy89** [ValveSoftware/Proton#5732]
# Compatibility Report
- Name of the game with compatibility issues: TheHunter - Call of the Wild
- Steam AppID of the game: 518790

## System Information
- GPU:  Intel Core i5-10300H CPU @ 2.50GHz
- Driver/LLVM version:  Linux Mint 20.3 (64 Bit) 
- Kernel version:  5.4.0-105-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: alle / all of the version

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
Hallo, ich kann das Spiel TheHunter - Call of the Wild nicht mehr starten. Betriebssystem ist Linux Mint und ich spiele über Steam Play. Zuvor ließ sich das Spiel ohne Probleme mit Proton Experimental starten, doch seit neuestem, ich vermute seitdem Proton 7.0-1 erschienen ist, lässt sich das Spiel nicht mehr starten. Können Sie das bitte wieder beheben? Vielen Dank im Voraus. // Hello, I can no longer launch the game TheHunter - Call of the Wild. Operating system is Linux Mint and I play via Steam Play. Previously the game could be launched without problems using Proton Experimental, but recently, I guess since Proton 7.0-1 was released, the game no longer launches. Can you please fix this again? Thank you very much in advance.

**Comment by kisak-valve** [comment]
Hello @FluffyFoxy89, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3073#issuecomment-1083066317.
