### ISSUE TITLE
Persona 4 Golden Wrong Audio In Animated Cutscenes.

### ISSUE THREAD

**Issue by tlneondo** [ValveSoftware/Proton#5733]
Compatibility Report
    Steam AppID of the game: 1113000

System Information

  Steam Deck

I confirm:

    [ X] that I haven't found an existing compatibility report for this game.
    [ X] that I have checked whether there are updates for my system available.

Symptoms

If You play with Japanese Audio, the Animated Cut-scenes will still be in english.

Possible the MF workaround doesn't take different languages into account?

**Comment by kisak-valve** [comment]
Hello @tlneondo, we're using one issue per unofficially supported game title. Closing in favor of https://github.com/ValveSoftware/Proton/issues/3982#issuecomment-1083955326.
