### ISSUE TITLE
DOOM 64 (1148590)

### ISSUE THREAD

**Issue by Sterophonick** [ValveSoftware/Proton#5738]
# Compatibility Report
- DOOM 64 (1148590)

## System Information
- GPU: Intel CometLake-U GT2 [UHD Graphics]
- Driver/LLVM version: Mesa 22.0.0
- Kernel version: Kernel 5.17.1-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Sterophonick/ffef6f397661b75cdeafd830770d17b1
- Proton version: Experimental-7.0-20220331

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Constant stuttering when using a controller. Works fine with keyboard and mouse though.

## Reproduction
1. Boot the game with a controller attached.
2. Play the game with the controller.

## Log:
[steam-1148590.log](https://github.com/ValveSoftware/Proton/files/8394675/steam-1148590.log)

**Comment by kisak-valve** [comment]
Hello @Sterophonick, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3663#issuecomment-1085829991.
