### ISSUE TITLE
Fallout 76 start up crash

### ISSUE THREAD

**Issue by Paperozza** [ValveSoftware/Proton#5740]
# Compatibility Report
- Name of the game with compatibility issues: Fallout 76
- Steam AppID of the game:1151340

## System Information
- GPU: RTX 3060
- Driver/LLVM version: 510.154
- Kernel version: 5.16.15-76051615-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Paperozza/22daef35881e6f0af305e05c2c848ecd
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Every time I try to launch the game it crashes.

**Comment by kisak-valve** [comment]
Hello @Paperozza, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3766#issuecomment-1085932980.
