### ISSUE TITLE
Couldnt launch Football Manager 21- linux RHEL 8

### ISSUE THREAD

**Issue by AdiY10** [ValveSoftware/Proton#5741]
# Compatibility Report
- Name of the game with compatibility issues: Football manager
- Steam AppID of the game: 

## System Information
![Screenshot from 2022-04-02 01-41-14](https://user-images.githubusercontent.com/83010776/161377265-b70aaf8a-9026-49e5-b401-9cd966425558.png)

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

## Symptoms 
I'm trying to launch the game FM21, but nothing happens (attach photos). I follow all instructions, and the "play" button is now available to me, but the game isn't launching. any help?

![Screenshot from 2022-04-02 01-40-08](https://user-images.githubusercontent.com/83010776/161377279-28307c5b-e40b-4212-a77b-b0d0dc27368a.png)
![Screenshot from 2022-04-02 01-39-27](https://user-images.githubusercontent.com/83010776/161377280-efd20ab8-1eb2-4b89-be07-b0a43279c233.png)

**Comment by kisak-valve** [comment]
Hello @AdiY10, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4365#issuecomment-1086637951.

**Comment by AdiY10** [comment]
hello @kisak-valve 
you transferred this issue report to another issue (https://github.com/ValveSoftware/Proton/issues/4365#issuecomment-1086637951)
but even there, there is no solution... what should I do?
