### ISSUE TITLE
[MESA] [NOTICE] MESA cache vars are getting renamed

### ISSUE THREAD

**Issue by DistantThunder** [ValveSoftware/Proton#5742]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

Heads up on the Mesa cache variables being renamed.

## Justification [optional] 

Just wanted to know if you guys were aware since the initial MR just disabled the current vars completely with no deprecation phase. Fortunately a contributor reminded the dev that  maybe a dry removal was a bit too brutal.

## Risks [optional]

Averted for now but could have impeded Proton runtime architecture?

## References [optional] 
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/15390

**Comment by kisak-valve** [comment]
Hello @DistantThunder, there is no functional impact until the deprecated environment variable is removed. (https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/15390#note_1299782)

Closing as not a Proton issue.
