### ISSUE TITLE
Space Hulk: Tactics 

### ISSUE THREAD

**Issue by BlackSheepxs** [ValveSoftware/Proton#5746]
Game : Space Hulk: Tactics 
Ongoing issue on steam since 2018. Many many reported similar issues all over the internet the last two years but no solution.
When trying to run in windows 10 or windows 11 the game loads up supporting studios short video runs but when the game gets to the loading screen it drops out back to desktop with no error message and also crashes steam app. Each time you have to restart app and log in again.. 

Trying to run it on Linux: Manjaro, Pop OS!, Fedora or Garuda in all cases when hitting start in steam doesn't load anything just crashes steam app immediately. Tried with Proton Layuer 6.3-8 , 7.0-1 and experimental .... does the same thing with all of them.

Digging into the game files to look for some crash report all I could find is this: 
[CrashReportClient]
bHideLogFilesOption=false
bIsAllowedToCloseWithoutSending=true
CrashConfigPurgeDays=2

Some people claim it's something to do with Unreal Engine 4 combined with 11th Gen Tiger Lake CPU that may cause the crash  but no definite Answer. My friend have an all AMD Machine and it works for him no problem (2nd gen thread ripper and Vage 64 GPU) 

## System Information = Alienware x17 r1
- GPU: RTX 3070
- CPU: 11 Gen Intel Core I7-11800H @2.3GHz
- Driver/LLVM version: latest NVIDA 510 driver in win10/11 and on Linux 510 proprietary driver.
- Kernel version: Manjaro 5.15.28.1
- Link to full system information report as [Gist](https://gist.github.com/):
- [CrashReportClient]
bHideLogFilesOption=false
bIsAllowedToCloseWithoutSending=true
CrashConfigPurgeDays=2 
- Proton version: 6.3-8, 7.0-1 and experimental 

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. Confirm
- [ ] that I have checked whether there are updates for my system available. Confirm

**Comment by kisak-valve** [comment]
Hello @BlackSheepxs, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5254#issuecomment-1086916698.

**Comment by BlackSheepxs** [comment]
Thank you

**Comment by BlackSheepxs** [comment]
I been looking for a quick fix for a while now. As it happens I may just finally have a fix. Please close this topic or I'm happy to provide my solution if you wish to keep this for further reference. 
Thank you
