### ISSUE TITLE
Steam constantly shows updates being available for Proton titles

### ISSUE THREAD

**Issue by CorruptComputer** [ValveSoftware/Proton#575]
Every time I restart steam, ALL my Proton titles will show as an update available. Running the update seems to do nothing as well:
![image](https://user-images.githubusercontent.com/5573038/44621081-74d3c900-a865-11e8-9497-9f18c9c38120.png)

**Comment by Zero86Sk** [comment]
This is a known issue with the Steam Client not Proton
[#5644](https://github.com/ValveSoftware/steam-for-linux/issues/5644)

**Comment by nstgc** [comment]
Interesting. I've never had this problem until now.

**Comment by kisak-valve** [comment]
Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5644.
