### ISSUE TITLE
Crystal Project Demo (1760770)

### ISSUE THREAD

**Issue by MadByteDE** [ValveSoftware/Proton#5753]
# Compatibility Report
- Name of the game with compatibility issues: Crystal Project
- Steam AppID of the game: 1760770

## System Information
- GPU:  AMD RADEON 5700XT
- Driver/LLVM version:  Mesa 22.0.1-3
- Kernel version:  5.17.1.arch1-1
- Link to full system information report: [Gist](https://gist.github.com/MadByteDE/f2645abcf3c17cd4d5dc5cbbcf455fe5)
- Proton version: Proton 7.0-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1760770.log](https://github.com/ValveSoftware/Proton/files/8445505/steam-1760770.log)

## Symptoms 
- Out of the box (using DXVK), the game does not launch using Proton (no window will show up - hangs)
- Using `PROTON_USE_WINED3D=1` will let the game crash and generate useful crash log info (see attached .log file)

## Reproduction
- Launch the game with Proton (there is a native Linux version that appear to work fine since it most likely uses OpenGL by default)

## Workaround
- Use command `PROTON_NO_D3D11=1 %command%` to make the game fallback to OpenGL drivers (FNA3D Driver: OpenGL)

## Notes
- This game is using XNA/FNA game libraries
- This seems like the interesting bit from the log using WINED3D:

```
FNA3D Driver: D3D11
D3D11 Adapter: Radeon RX 5700 / 5700 XT
6546.227:0134:0138:fixme:d3d11:d3d11_device_CheckFormatSupport iface 00AA10D8, format 71, format_support 052C6900 partial-stub!
6546.227:0134:0138:fixme:d3d11:d3d11_device_CheckFormatSupport iface 00AA10D8, format 74, format_support 007EEF40 partial-stub!
6546.227:0134:0138:fixme:d3d11:d3d11_device_CheckFormatSupport iface 00AA10D8, format 77, format_support 007EEF44 partial-stub!
6546.227:0134:0138:fixme:d3d11:d3d11_device_CheckFormatSupport iface 00AA10D8, format 98, format_support 052C6908 partial-stub!
6546.227:0134:0138:fixme:d3d11:d3d11_device_CheckFormatSupport iface 00AA10D8, format 29, format_support 007EEF48 partial-stub!
6546.228:0134:0138:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\d3dcompiler_47.dll" at 69D80000: builtin
6546.228:0134:0138:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\libvkd3d-shader-1.dll" at 6DF80000: native
Could not get UserDefinedAnnotation! Error Code: 0x80004002
[00000138:] EXCEPTION handling: System.InvalidOperationException: Could not get UserDefinedAnnotation! Error Code: 0x80004002
[00000138:] EXCEPTION handling: Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Could not get UserDefinedAnnotation! Error Code: 0x80004002
```
Link to line in FNA method "D3D11_CreateDevice" containing the error check for UserDefinedAnnotation: [Github](https://github.com/FNA-XNA/FNA3D/blob/9c00af2bfe30e28d48f93f4c1b4c62c38b3e13a3/src/FNA3D_Driver_D3D11.c#L5213). The check only executes for feature level 11_1.

**Comment by kisak-valve** [comment]
Hello @MadByteDE, we're using one issue report per unofficially supported game title (specifically for the game's demo in this case), so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5197#issuecomment-1092134636.
