### ISSUE TITLE
Mass Effect Legendary Edition - ME1&ME2 - launcher starts, me1&m2 quit with "wine: Unhandled page fault"

### ISSUE THREAD

**Issue by spirritus** [ValveSoftware/Proton#5755]
# Compatibility Report
- Mass Effect Legendary Edition - ME1&ME2
- Steam AppID of the game: 1328670

## System Information
- GPU: GTX 980
- Driver/LLVM version: nvidia 510.54
- Kernel version: 5.16.0-0.bpo.3-amd64
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7.0 and experimental

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
ME1 and ME2 do not start,  launcher works
this worked in february 2022

## Reproduction
start launcher
start me1 or me2
observe return to launcher

steam reports:
wine: Unhandled page fault on write access to 000000000000005C at address 0000000140251135 (thread 0888), starting debugger...

[steam-1328670.log](https://github.com/ValveSoftware/Proton/files/8453087/steam-1328670.log)

**Comment by kisak-valve** [comment]
Hello @spirritus, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4823#issuecomment-1092971519.
