### ISSUE TITLE
Hyperdevotion Noire: Goddess Black Heart (415480)

### ISSUE THREAD

**Issue by ComicBookGrunty** [ValveSoftware/Proton#5762]
**Compatibility Report**

Name of the game with compatibility issues: Hyperdevotion Noire: Goddess Black Heart
Steam AppID of the game: 415480

**System Information**

Steam Deck

**I confirm:**

that I haven't found an existing compatibility report for this game.
that I have checked whether there are updates for my system available.

**Symptoms**

The game won't create a save file.

**Reproduction**

Can reboot and play again, choose to save in the menu, no save file is created.  First time reporting anything, hope I did everything right.

**Comment by kisak-valve** [comment]
Hello @ComicBookGrunty, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/762#issuecomment-1094154904.
