### ISSUE TITLE
Textures on Deathloop become black with viewed up close. The sky also corrupts.

### ISSUE THREAD

**Issue by LethalManBoob** [ValveSoftware/Proton#5765]
# Compatibility Report
- Name of the game with compatibility issues: Deathloop
- Steam AppID of the game: 1252330

## System Information
- GPU: RTX 3070
- Driver/LLVM version: 510.60.02
- Kernel version: 5-15-33-xanmod1-tt-1
- Proton version: Experimental (works fine on 7.0.1)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms: 
Textures become black when viewed up close. This sometimes takes a view seconds to start happening. 
First person weapons exibit this as well, becoming completly black.
The sky sometimes will be corrupted into a crystal-like circlular pattern. 

## Reproduction:
On experimental, run the game with textures higher than low and/or enable dxr via command line.

I cannot take a screenshot with gnome as it softlocks the pc.

**Comment by kisak-valve** [comment]
Hello @LethalManBoob, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5156#issuecomment-1097204454.
