### ISSUE TITLE
Experimental proton, amd radeon Archlinux Disgaea 5 not working

### ISSUE THREAD

**Issue by chriztheanvill** [ValveSoftware/Proton#5767]
# Compatibility Report
- Name of the game with compatibility issues: Disgaea 5 complete
- Steam AppID of the game: 803600

## System Information
- GPU: Advanced Micro Devices, Inc. [AMD/ATI] Wani [Radeon R5/R6/R7 Graphics] (rev cc)
- Driver/LLVM version: Amd amd Carrizo (LLVM 13.0.1 DRM 3.44)
- Kernel version:  5.17.2-arch3-1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam_log.txt](https://github.com/ValveSoftware/Proton/files/8492253/steam_log.txt)

## Symptoms 
I have this game installed in a laptop with Intel and Nvidia, with Fedora 35 and works fine with the experimental Proton. In the another laptop, with amd and radeon with Archlinux, does not work the game.
Edit: Works on proton 7.0.1

Can be opened, shows 3 screens, and quit the game, before the intro video starts

## Reproduction
Open game
Wait to continue the game.

**Comment by kisak-valve** [comment]
Hello @chriztheanvill, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1801#issuecomment-1099649533.
