### ISSUE TITLE
Monster Train (1102190)

### ISSUE THREAD

**Issue by renatopereyra** [ValveSoftware/Proton#5768]
# Compatibility Report
- Name of the game with compatibility issues: Monster Train
- Steam AppID of the game: 1102190

## System Information
- GPU: Intel® Iris® Xe Graphics (11th Gen i7-1165G7)
- Driver/LLVM version: 21.2.6
- Kernel version: 5.13
- Link to full system information report: [gist](https://gist.github.com/renatopereyra/f2ddf57a01ff5ddee96daa6f38bdd791)
- Proton version: Experimental and 7.0

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. // There is https://github.com/ValveSoftware/Proton/issues/4298 but that seems very stale and no longer applicable.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
Rendering and audio corruption in intro video _when Video player set to Unity_. Both issues go away with `WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER=1 %command%` in the launch options

[steam-1102190.log](https://github.com/ValveSoftware/Proton/files/8492478/steam-1102190.log)
[steam-1102190_no_dxgi_device_mgr.log](https://github.com/ValveSoftware/Proton/files/8492479/steam-1102190_no_dxgi_device_mgr.log)

![monster_train](https://user-images.githubusercontent.com/88858798/163483322-d9b166d2-6076-4b3f-86cb-0fd9d52ca071.png)

## Reproduction
Run Monster Train with Settings > Graphics > Video player set to Unity

**Comment by kisak-valve** [comment]
Hello @renatopereyra, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4298#issuecomment-1099676451.
