### ISSUE TITLE
Resident evil 0 Color bars

### ISSUE THREAD

**Issue by songsofsyx** [ValveSoftware/Proton#5770]
# Compatibility Report
- Name of the game with compatibility issues: Resident Evil 0
- Steam AppID of the game:

There are color bars on Resident Evil 0, playing it on the steam deck.
Proton 7.x has color bars on cutscenes and color bars in-game
Proton experimental has color bars in-game

The in-game color bars do not occur at first glance, one must progress in the game a bit.

By color bars, I mean stripes of colors, with a noisy flickering in the lower right. 

I'm pretty sure this is codec-related, maybe having a look at the game files will identify the offending codec.

I'm sorry, due to technical issues I'm reporting this on my windows machine, and can not offer logs.

**Comment by kisak-valve** [comment]
Hello @songsofsyx, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/576#issuecomment-1100654293.
