### ISSUE TITLE
Horizon Zero Dawn freezes every 15 minutes! 

### ISSUE THREAD

**Issue by tooyipjee** [ValveSoftware/Proton#5771]
# Compatibility Report
- Name of the game with compatibility issues: Horizon Zero Dawn Complete Edition
- Steam AppID of the game: 1151640

## System Information
- Steam Deck 64GB with Sandisk Extreme 128GB
- Proton version: Tried with versions 6, 7, and Experimental (problem persisted)

## I confirm:
- It was indicated as fully "Verified" for the Steam Deck in the store.
-I have checked whether there are updates for my system available.

## Symptoms 
The game freezes every 10-15 minutes. The sound in the background still plays but the screen is frozen and the controls do not work. 
I have not had any issues with any other games just Horizon Zero Dawn. The graphics settings have been turned down to the lowest as well as resolution reduced. Problem persisted. Please advice.

**Comment by kisak-valve** [comment]
Hello @tooyipjee, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4125#issuecomment-1100925941.
