### ISSUE TITLE
New World (1063730)

### ISSUE THREAD

**Issue by hagenmt** [ValveSoftware/Proton#5774]
# Compatibility Report
- Name of the game with compatibility issues: New World
- Steam AppID of the game: 1063730

## System Information
Distro: Ubuntu 20.04.4 LTS
Kernel: 5.13.0-39-generic
RAM:32 GB
GPU Driver:NVIDIA 510.54
GPU:NVIDIA GeForce GTX 1060 3GB
CPU:Intel Core i7-8700 @ 3.20GHz

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

log for experimental (not bleeding edge run):
[experimental-steam-1063730.zip](https://github.com/ValveSoftware/Proton/files/8509682/experimental-steam-1063730.zip)

log for 7.0.1:
[701-steam-1063730.zip](https://github.com/ValveSoftware/Proton/files/8509680/701-steam-1063730.zip)

## Symptoms 
Tried experimental, 7.0.1, and experimental bleeding edge.  It crashes about 2-5 minutes into playing. Early on I was able to play for quite a while, but not that I have about 4-6 hours into the game it crashes every time almost instantly.  I am sitting in the wilderness at this point just collecting some ore and hemp and it crashes usually about 3-4 resources nodes into collecting every time.

I only see this other New World issue reported: https://github.com/ValveSoftware/Proton/issues/5772
But it appears to be more related to memory issues, I have 32GB of memory and I have always had a swap file as well so I don't think they are the same issue?

## Reproduction
Start steam
Launcher options: PROTON_LOG=1 bash -c 'exec "${@/NewWorldLauncher.exe/bin64\/NewWorld.exe}"' -- %command%
Hit Play
Select my character 
Search the near locations for some hemp or iron nodes and start mining
Crash after about 3-4 nodes

**Comment by kisak-valve** [comment]
Hello @hagenmt, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5772#issuecomment-1102661835.
