### ISSUE TITLE
Propnight (1549180)

### ISSUE THREAD

**Issue by Spencer-0003** [ValveSoftware/Proton#5777]
Propnight recently added Linux BattlEye support and it worked on 7.0-1 but the game refuses to boot on 7.0-2

Log file: https://pastebin.com/raw/EWsUGwLA

**Comment by kisak-valve** [comment]
Hello @Spencer-0003, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5372#issuecomment-1105713759.
