### ISSUE TITLE
Dark Souls: Remastered can't be launched 

### ISSUE THREAD

**Issue by mwprado** [ValveSoftware/Proton#5778]
The last Proton version(7.0-2 and experimental) this game had been launched was 5.0-10. Running using 7.0-2 stop after few seconds. In 5.6-13 and 6.3-8 opens a window with "Preparing to launch Dark Souls: Remastered..." and no response.

My system is Rocky Linux 8.5 using steam client from EL8 fedora fusion.

**Comment by kisak-valve** [comment]
Hello @mwprado, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1026#issuecomment-1105746444.

**Comment by mwprado** [comment]
Sorry I didn't know.

> Hello @mwprado, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#1026 (comment)](https://github.com/ValveSoftware/Proton/issues/1026#issuecomment-1105746444).

Sorry I didn't know.
