### ISSUE TITLE
Jurassic World Evolution 2 (1244460)

### ISSUE THREAD

**Issue by mwprado** [ValveSoftware/Proton#5779]
[steam-1244460.zip](https://github.com/ValveSoftware/Proton/files/8544221/steam-1244460.zip)
# Compatibility Report
- Name of the game Jurassic World Evolution:
- Steam AppID of the game:  1244460

## System Information
- GPU: GTX1650
- Driver/LLVM version: Mesa 21/ nvidia 510.47 using prime
- Kernel version: 4.18
- Link to full system information report as https://gist.github.com/mwprado/a60f3e5c81d811d7ed639930e44f91c7):
- Proton version: all

## I confirm:
- [  ] that I haven't found an existing compatibility report for this game.
  The game was working until last update.
- [X ] that I have checked whether there are updates for my system available.

[steam-1244460.zip](https://github.com/ValveSoftware/Proton/files/8544221/steam-1244460.zip)

## Symptoms 
The game doesn't launch.

## Reproduction
Try launch with all proton version

**Comment by Blisto91** [comment]
@mwprado Your steam systems report isn't fully complete, you need to let it run for at least 10 seconds to be sure. It isn't obvious i know :)
Also your zip file seem to have not uploaded correctly

**Comment by mwprado** [comment]
> @mwprado Your steam systems report isn't fully complete, you need to let it run for at least 10 seconds to be sure. It isn't obvious i know :) Also your zip file seem to have not uploaded correctly

Done!

**Comment by Blisto91** [comment]
Could you also link a new full systems report? :)

**Comment by mwprado** [comment]
> Could you also link a new full systems report? :)

Done II: The File Strike Back!

**Comment by kisak-valve** [comment]
Hello @mwprado, looking at your system information, https://gist.github.com/mwprado/a60f3e5c81d811d7ed639930e44f91c7#file-gistfile1-txt-L363-L387 looks normal for an optimus laptop and the 64 bit Vulkan render path, but https://gist.github.com/mwprado/a60f3e5c81d811d7ed639930e44f91c7#file-gistfile1-txt-L192-L206 doesn't look right in the 32 bit Vulkan render path. Can you verify you have the 32 bit userspace libraries for your distro's NVIDIA driver package?

**Comment by mwprado** [comment]
It works again! I am running over wayland with libvdpau and libva installed (x86_64 e i686). I've submitted another gist file with my specs.
