### ISSUE TITLE
No game will launch - ubuntu 18.04

### ISSUE THREAD

**Issue by asim-vax** [ValveSoftware/Proton#578]
Hoping someone can point me to a simple mistake i've made - tried 2 games
The Last Remnant (whitelisted by Valve)
Final Fantasy VII (whitelisted https://docs.google.com/spreadsheets/d/1DcZZQ4HL_Ol969UbXJmFG8TzOHNnHoj8Q1f8DIFe8-8/htmlview?sle=true#)
both games go to "preparing to launch" then in steam "running" no window opens and then it goes back to normal

* Enabled steam play in steam client and enabled steam play for all games, tried 3.7.3 and 3.7.4-beta
* Nvidia driver 396.54, vulkan installed (WoW with DXVK plays)
* esync /etc/security updated *username* soft nofile 204800 and *username* hard nofile 204800
* ubuntu 18.04
* python -V // Python 2.7.15rc1 and python3 is already the newest version (3.6.5-3ubuntu1)
* system wine // wine --version wine-3.14 (Staging)

**Comment by kormic** [comment]
I don't think you need wine installed (just saying)
I had the same problem cause I had installed ubuntu with minimal installation. My solution was to install python (version 2.7). 
Also you could try to enable logs through proton user settings in ~/.steam/steam/steamapps/common/Proton3.7/user_setting.sample.py and see if there are any logs in your home folder name steam-steam_app_id.log

**Comment by asim-vax** [comment]
Was just trying to provide all system information that could be relevant :)
sudo apt install python2.7 
python2.7 is already the newest version (2.7.15~rc1-1).

There is no Proton3.7 folder created in ~/.steam/steam/steamapps/common which is what concerns me that i'm doing something dumb

**Comment by michaelwerkel** [comment]
You should tick all checkboxes under the Steam Play category, or the Proton folder won't appear, I guess.
When you installed the games on an external NTFS harddrive, then there could be some permission issues.

**Comment by asim-vax** [comment]
![screenshot from 2018-08-25 22-45-31](https://user-images.githubusercontent.com/4798940/44622810-9d38e300-a8b8-11e8-8d36-19f6f9163a75.png)
They are and ff vii is installed to my main ubuntu drive ext4 format, the last remnant installed to exfat HDD (tried both formats)

**Comment by flukejones** [comment]
Under "Compatibility tool" select the latest beta version. If that fails, start steam via a terminal and check what the output is (may or may not be Python 2.7 not installed if using first release).

**Comment by felisucoibi** [comment]
Hi, are you using a laptop with to graphics cards and using hdmi? Bests

**Comment by asim-vax** [comment]
tried with the beta, makes no difference - Tried starting steam via the terminal, but no output after launching the client:
```
You are in the 'publicbeta' client beta.
[2018-08-26 09:13:08] Verifying installation...
[2018-08-26 09:13:08] Verification complete
```
I click play game, but nothing is output to the terminal

Not using a laptop, desktop with nvidia gtx 1060, 396.54 drivers

**Comment by kormic** [comment]
OK, this happened also to me (not finding the Proton folder). Try to opt-out from the beta, uninstall steam completely and try from the beginning. In my case this worked.

To uninstall steam:
```
sudo apt-get remove steam
sudo apt-get purge steam
rm -rf ~/.local/share/Steam && rm -rf ~/.steam
```

**Comment by asim-vax** [comment]
@kormic tyvm, this was the issue - i hope this doesn't affect more people as it was the most infuriating thing!
