### ISSUE TITLE
Assassins Creed Odyssey(812140): FPS problem

### ISSUE THREAD

**Issue by k3ssl0sh4y** [ValveSoftware/Proton#5780]
# Compatibility Report
- Name of the game with compatibility issues: Assassins Creed Odyssey
- Steam AppID of the game: 812140

## System Information
- GPU: NVIDIA TITAN X (Pascal)
- Driver/LLVM version: 4.6.0 NVIDIA 510.60.02
- Kernel version: 5.17.3-1-default
- Link to full system information report as [Gist]: [Full system information report](https://gist.github.com/k3ssl0sh4y/ddcc1c388efd41a2a579c818d2ed7a11)
- Proton version: 7.0-2

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
The game didn't have the problem with proton version 7.0-1.
- [x] that I have checked whether there are updates for my system available.

[steam-812140.log](https://github.com/ValveSoftware/Proton/files/8540967/steam-812140.log)

## Symptoms 

I run the game and it drops to 90-1 FPS. This is an instant drop to 1 and back to 90. I can run the game on low, medium and high, but the frames are inconsistent. The image below shows the problem
![image](https://user-images.githubusercontent.com/44761918/164713003-faba13af-603d-486d-97c3-a0995d460605.png)

## Reproduction
it's during the game

**Comment by kisak-valve** [comment]
Hello @k3ssl0sh4y, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1757#issuecomment-1106500739.
