### ISSUE TITLE
Phantasy Star Online 2: New Genesis framerate problems

### ISSUE THREAD

**Issue by CathyRina** [ValveSoftware/Proton#5781]
# Compatibility Report
- Name of the game with compatibility issues: Phantasy Star Online 2: New Genesis
- Steam AppID of the game: 1056640

## System Information
- GPU: AMD AMD Custom GPU 0405 (vangogh, LLVM 13.0.0, DRM 3.45, 5.13.0-valve10.1-1-neptune-02144-g7fffaf925dfb)
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 22.0.0-devel (git-676ccacebc)
- Kernel version: 5.13.0-valve10.1-1-neptune-02144-g7fffaf925dfb
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/CathyRina/ec924f5ac8776136bd2c12e194755661
- Proton version: 7.0-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
[steam-1056640.log](https://github.com/ValveSoftware/Proton/files/8543714/steam-1056640.log)

## Symptoms 
Game boots up fine however the framerate dies after selecting a character & loading the main map.

## Reproduction
Boot up the game, select a server, select a character

**Comment by kisak-valve** [comment]
Hello @CathyRina, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4122#issuecomment-1106880555.
