### ISSUE TITLE
Games do not launch

### ISSUE THREAD

**Issue by mariomadproductions** [ValveSoftware/Proton#5782]
## System Information
- GPU: GeForce GT 620
- Driver/LLVM version: nvidia-driver-390
- Kernel version: 5.4.0-109-generic
- Link to full system information report: [system-info.txt](https://github.com/ValveSoftware/Proton/files/8543955/system-info.txt)

## Symptoms
All windows games apparently close straightaway, or never launch. Its inconsistent if a log is produced or not.
| Game                                                                                | Experimental                                                                                 | v7.0-2                                                                                     | 6.3-8                                                                                        | 5.13-6      | 5.0-10                                                                                     | 4.11-13                                                                                    | 4.2-9                                                                                      | 3.16-9                                                                                     | 3.7-8                                                                                      |
|-------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------|-------------|--------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------|
| https://store.steampowered.com/app/424840/Little_Nightmares/                        | [steam-424840.log](https://github.com/ValveSoftware/Proton/files/8543994/steam-424840.log)   | [steam-424840.log](https://github.com/ValveSoftware/Proton/files/8544001/steam-424840.log) | [steam-424840.log](https://github.com/ValveSoftware/Proton/files/8544017/steam-424840.log)   | No log      | [steam-424840.log](https://github.com/ValveSoftware/Proton/files/8544304/steam-424840.log) | [steam-424840.log](https://github.com/ValveSoftware/Proton/files/8544302/steam-424840.log) | [steam-424840.log](https://github.com/ValveSoftware/Proton/files/8544297/steam-424840.log) | [steam-424840.log](https://github.com/ValveSoftware/Proton/files/8544291/steam-424840.log) | [steam-424840.log](https://github.com/ValveSoftware/Proton/files/8544287/steam-424840.log) |
| https://store.steampowered.com/app/868520/killer7/                                  | [steam-868520.log](https://github.com/ValveSoftware/Proton/files/8544658/steam-868520.log)   | No log                                                                                     | [steam-868520.log](https://github.com/ValveSoftware/Proton/files/8544737/steam-868520.log)   | No log      | No log                                                                                     | No log                                                                                     | No log                                                                                     | No log                                                                                     | No log                                                                                     |
| https://store.steampowered.com/app/1911390/Knightfall_A_Daring_Journey/             | [steam-1911390.log](https://github.com/ValveSoftware/Proton/files/8544785/steam-1911390.log) | Didn't test                                                                                | Didn't test                                                                                  | Didn't test | Didn't test                                                                                | Didn't test                                                                                | Didn't test                                                                                |                                                                                            | Didn't test                                                                                |
| https://store.steampowered.com/app/1048540/Kao_the_Kangaroo_Round_2_2003_rerelease/ | [steam-1048540.log](https://github.com/ValveSoftware/Proton/files/8544792/steam-1048540.log) | Didn't test                                                                                | [steam-1048540.log](https://github.com/ValveSoftware/Proton/files/8544803/steam-1048540.log) | Didn't test | Didn't test                                                                                | Didn't test                                                                                | Didn't test                                                                                |                                                                                            | Didn't test                                                                                |

**Comment by kisak-valve** [comment]
Hello @mariomadproductions, the NVIDIA GeForce GT 620 video card is part of the Fermi generation video cards. The video drivers for this generation of video card does not support Vulkan. Additionally, the Sandybridge generation GPU on the Intel side also does not support Vulkan, which makes your hardware unsupportable by Proton.

**Comment by mariomadproductions** [comment]
[deleted]

**Comment by Orochikyocr** [comment]
I have been using PROTON_USE_WINED3D=1 %command% to circumvent this with Proton 5.0-10. Many Fighting games I play work fine with this.
This way you'll use Proton will use Open GL instead of Vulkan. Sadly it does not work with newer versions of Proton.
