### ISSUE TITLE
Warhammer 40k: Inquisitor - Martyr (527430) fps crash from ~100 to ~1 in 5min of play

### ISSUE THREAD

**Issue by tharbad08** [ValveSoftware/Proton#5783]
# Compatibility Report
- Name of the game with compatibility issues: Warhammer 40k: Inquisitor - Martyr
- Steam AppID of the game: 527430

## System Information
- GPU: 2060 Super
- Driver/LLVM version: 510.60.2
- Kernel version: 5.17.3-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/):  https://gist.github.com/shaygover/ee9712e99b6873532873751a8396804c
- Proton version: 7.0-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton log:
https://drive.google.com/file/d/1Z8cO24_sUdV9iMUbwPgzFbQ5QUu8kW5S/view?usp=sharing

## Symptoms 
After 5 min inside a level fps goes down to 1fps.
Works fine on 6.3-8

## Reproduction
1. Run the game
2. Select your character.
3. Play a random level.
4. After ~5 min fps will drop bellow 10 and game will be unplayable.

**Comment by kisak-valve** [comment]
Hello @shaygover, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4282#issuecomment-1107192333.
