### ISSUE TITLE
"Danganronpa V3: Killing Harmony" launching problem.

### ISSUE THREAD

**Issue by IrisImmortal** [ValveSoftware/Proton#5785]
I downloaded **all parts** of "Danganronpa V3: Killing Harmony" from a website called `<removed by moderator>` Then I **extracted** them and **put them in one file** like this:

![Picture Nr  1](https://user-images.githubusercontent.com/95183270/164913488-727ca4ba-b06e-477e-9b36-7fa7c79b06de.png)

I tried to **launch** it, **but an error came up:**

![Picture Nr  3](https://user-images.githubusercontent.com/95183270/164913611-fe5dd324-4fef-4745-a9c3-ed6ef78b7a35.png)

Then I **put all of the parts in part one** like this:

![Picture Nr  2](https://user-images.githubusercontent.com/95183270/164913649-85abcab1-16b4-4eab-a3e8-07a0298fcc1a.png)

**Launched** it again, and the **same error came up**.

Can you please tell me what is wrong or what am I doing wrong because I really want to play this game?

P.S. The highlighted words might be important, so that is why I highlighted them.

**Comment by kisak-valve** [comment]
Hello @IrisImmortal, we can't support pirated games.
