### ISSUE TITLE
The Binding of Isaac: Rebirth (250900) Afterbirth+ DLC (570660) issue on Steam Deck

### ISSUE THREAD

**Issue by GunstarXX** [ValveSoftware/Proton#5787]
# Compatibility Report
- Name of the game with compatibility issues: The Binding of Isaac: Rebirth (Afterbirth+ DLC)
- Steam AppID of the game: 570660 (AppID of parent game, The Binding of Isaac: Rebirth (250900))

## System Information
- GPU: AMD Custom GPU 0405 (vangogh, DRM 3.45)
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 22.0.0-devel (git-676ccacebc), LLVM 13.0.0
- Kernel version: 5.13.0-valve10.1-1-neptune-02144-g7fffaf925dfb
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/GunstarXX/90d46e15c8fe88d27b31e46731755630
- Proton version: 7.0-2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
As long as the Afterbirth+ DLC is installed, the game will crash instantly and kick me back to Steam.

## Reproduction
Download all DLC for Binding of Isaac Rebirth up to Afterbirth+ on your Steam Deck and attempt to launch the game.

**Comment by kisak-valve** [comment]
Hello @GunstarXX, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4868#issuecomment-1107648935.
