### ISSUE TITLE
Elex 2 crashes after proton update 7.0-1 to 7.0-2 

### ISSUE THREAD

**Issue by crone66** [ValveSoftware/Proton#5788]
# Compatibility Report
- Name of the game with compatibility issues: Elex 2
- Steam AppID of the game: 900040

## System Information
Steam Deck with everything up to date
- Proton version: 7.0-2 (worked flawlessly with 7.0-1)

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

https://gist.github.com/crone66/abfaf9bb06f83c654551b6ff00846022

## Symptoms
Game Crashs after splash screen

## Reproduction
Start the game :)

**Comment by kisak-valve** [comment]
Hello @crone66, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5670#issuecomment-1107650970.
