### ISSUE TITLE
Deus Ex: Mankind divided

### ISSUE THREAD

**Issue by stixholder** [ValveSoftware/Proton#5789]
# Compatibility Report
- Name of the game with compatibility issues: Deus Ex: Mankind dividded
- Steam AppID of the game: 337000

## System Information
- GPU: AMD Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 5.4.0-109-generic)
- AMD FX-8350
- Driver/LLVM version:  4.6 (Compatibility Profile) Mesa 21.2.6 / LLVM 12.0.0)
- Kernel version: 5.4.0-109-generic
- Linux Mint 20.3 (64 bit)
- Proton version: Proton Experimental
- X Server Release:  12013000
- X Window Manager:  Mutter (Muffin)
- Steam Runtime Version:  steam-runtime_0.20220119.0

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
After playing some prolonged time the game will freeze, with only music playing and mouse still working, while following error popup shows:
"Microsoft Visual C++ Runtime Li...
Runtime Error!
Program: N:\.steam\debian-installati...
R6025
-pure virtual function call"

## Reproduction
Intermittent / after prolonged playing (0.5 to 2h), while the game will freeze - probably always, during using, combining, or moving items around a lot inside the inventory

Using starting parameters "env LD_PRELOAD='' DISABLE_VK_LAYER_VALVE_steam_overlay_1=1 %command%", to prevent the notorious stuttering issues otherwise kicking in after some time (see https://github.com/ValveSoftware/Proton/issues/47). But the freeze would seem to occur also without those params.

**Comment by kisak-valve** [comment]
Hello @stixholder, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3589#issuecomment-1107678772.
