### ISSUE TITLE
Dark Souls Remastered (570940)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#5791]
# Compatibility Report
- Name of the game with compatibility issues: Dark Souls Remastered
- Steam AppID of the game: 570940

## System Information
- GPU: NVIDIA GeForce GT730
- Driver/LLVM version: 4.6.0 NVIDIA 470.103.01
- Kernel version: 5.16.20-200
- Link to full system information report as gist: https://gist.github.com/Vovkiv/e90bf2ec01961bb5db0f9aba75ca75c8
- Proton version: 7.0-2

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

## Symptoms 

Game works fine first around 15 seconds after lauched (i can interact with interface, try start new game, etc), but after that time game just crash

## Reproduction
1. Launch game
2. Wait around ~15 seconds
3. Crash

> 7. Please copy it to your clipboard by pressing `Ctrl+A` and then `Ctrl+C`.
>    Then paste it in a gist and post the link in
>    this issue.

(For some reasons, ctrl+c and right click + copy don't copy anything in this window)

**Comment by kisak-valve** [comment]
Hello @Vovkiv, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1026#issuecomment-1107887170.
