### ISSUE TITLE
No Shared Fences

### ISSUE THREAD

**Issue by dwekiweujsawoeopaoiwdisejredfksei** [ValveSoftware/Proton#5801]
# Compatibility Report
- Name of the game with compatibility issues: Cyberpunk2077 w/ Realmod VR
- Steam AppID of the game: 1091500

## System Information
- GPU: RX6900XT
- Driver/LLVM version: AMD AMD Radeon RX 6900 XT (SIENNA_CICHLID, DRM 3.44.0, 5.17.4-200.fc35.x86_64, LLVM 13.0.0)
- Kernel version: 5.17.4-200.fc35.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/dwekiweujsawoeopaoiwdisejredfksei/700454654547ee4eb7dc318f99316edc
- Proton version: 1638789187 proton-6.3-8c

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-1091500.log](https://github.com/ValveSoftware/Proton/files/8579020/steam-1091500.log)

## Symptoms 
Game opens, then crashes a few seconds after the logo shows

## Reproduction
Tried on multiple versions of proton across 6, 7, GE and have tried with launch commands, and as shown here, without, even tried launching the game first and then launching VR once the game was playing in desktop mode, same outcome

**Comment by kisak-valve** [comment]
Hello @dwekiweujsawoeopaoiwdisejredfksei, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1112136369.
