### ISSUE TITLE
Lego Harry Potter: Years 1-4 (21130) compatibility issue

### ISSUE THREAD

**Issue by cook-f** [ValveSoftware/Proton#5802]
# Compatibility Report
- Name of the game with compatibility issues: Lego Harry Potter: Years 1-4
- Steam AppID of the game: 21130

## System Information
- GPU: Integrated Graphics (AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx)
- Kernel version: 5.15.32-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/nectariner/cc69070238ea8545bf86ef87dd0ffe64
- Proton version: Experimental

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Proton Logs:
[steam-21130.log](https://github.com/ValveSoftware/Proton/files/8583997/steam-21130.log)

## Symptoms 
Seizure inducing colours flashing when starting the game and not stopping, making the game unplayable
Main menu intro: ![Screenshot_20220428_161531](https://user-images.githubusercontent.com/22417704/165785981-74d6a55c-d45b-411a-b11c-1c043d3a4265.png)

## Reproduction
Launch the game

**Comment by kisak-valve** [comment]
Hello @nectariner, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1920#issuecomment-1112349542.
