### ISSUE TITLE
Mortal Kombat X - Steam Deck

### ISSUE THREAD

**Issue by jds12us** [ValveSoftware/Proton#5810]
# Compatibility Report
- Name of the game with compatibility issues: Mortal Kombat X
- Steam AppID of the game:

## System Information
- GPU:  Steam Deck
- Driver/LLVM version:  Latest Steam Deck
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/): 
- Proton version: Latest for steam deck

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @jds12us, we're using one issue report per unofficially supported game title. Please use #513 for any feedback related to Mortal Kombat X.

Closing blank compatibility report template.
