### ISSUE TITLE
King Arthur: Knight's Tale

### ISSUE THREAD

**Issue by 3DRaven** [ValveSoftware/Proton#5811]
# Compatibility Report
- Name of the game with compatibility issues: King Arthur: Knight's Tale
- Steam AppID of the game: 1157390

## System Information
- GPU: Nvidia 3080 RTX
- Driver/LLVM version: Nvidia 510.60.02
- Kernel version: 5.17.0-5.1-liquorix-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/3DRaven/9797bdce6442b535bc0099d943c70fdf
- Proton version: Experimental

## I confirm:
- [+] that I haven't found an existing compatibility report for this game.
- [+] that I have checked whether there are updates for my system available.

[steam-1157390.log](https://github.com/ValveSoftware/Proton/files/8598685/steam-1157390.log)

## Symptoms 
After start I hear sound and see cursor, but on black screen.

## Reproduction
Download and start the game.

**Comment by kisak-valve** [comment]
Hello @3DRaven, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5809#issuecomment-1114221628.
