### ISSUE TITLE
Unity of Command 2 crashes often using Proton experimental and after upgrading to Kubuntu 22.04

### ISSUE THREAD

**Issue by mokmeister** [ValveSoftware/Proton#5813]
Unity of Command 2 was running well using Proton Experimental under Kubuntu 21.10. However, since upgrading to Kubuntu 22.04 the games crashes regularly. The latest crash produced these results in log.txt:

INF 2022-05-02 13:29:38,437                tools.steam_api:230  Shutting down Steam
ERR 2022-05-02 13:29:38,442                       uoc2-exe:24   Traceback (most recent call last):
ERR 2022-05-02 13:29:38,442                       uoc2-exe:24     File "uoc2-exe.py", line 17, in <module>
ERR 2022-05-02 13:29:38,443                       uoc2-exe:24     File "E:\code\uoc2\uoc2\main.py", line 311, in main
ERR 2022-05-02 13:29:38,444                       uoc2-exe:24     File "E:\code\uoc2\engine\ui\system.py", line 716, in main_loop
ERR 2022-05-02 13:29:38,444                       uoc2-exe:24   OSError: exception: access violation writing 0x0000000000000054

based on the crash log, developer reports that the game crashes in SDL_GL_SwapWindow()

**Comment by kisak-valve** [comment]
Hello @mokmeister, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3841#issuecomment-1114831213.
