### ISSUE TITLE
Bloons TD6 touchscreen crashing

### ISSUE THREAD

**Issue by guyish1** [ValveSoftware/Proton#5819]
# Compatibility Report
- Name of the game with compatibility issues: Bloons TD6
- Steam AppID of the game: 960090

## System Information
- GPU: GTX 970mx
- Driver/LLVM version: Nvidia 510.68.02
- Kernel version: 5.16.19-76051619-generic
- Link to full system information report as [Gist](https://gist.github.com/):  https://gist.github.com/guyish1/cfc1680bb9ee883e77a69d578919b813 
- Proton version: experimental

## I confirm:
- [ yes] that I haven't found an existing compatibility report for this game.
- [ yes] that I have checked whether there are updates for my system available.

[steam-960090.log](https://github.com/ValveSoftware/Proton/files/8633087/steam-960090.log)

## Symptoms 
everything works as expected, but when I use a touchscreen, the game instantly crashes. This was not a problem with this game before. I don't know when this problem started because I took a hiatus from the game for a couple of months, the last I remember playing on this device was mid-February 2022 and the touchscreen did not cause the game to crash. I played on this device again on 5/3/2022 and that is when it was an issue.

## Reproduction
launching the game and touching the touchscreen

**Comment by kisak-valve** [comment]
Hello @guyish1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2330#issuecomment-1118850818.
