### ISSUE TITLE
[Steam] Eador. Masters of the Broken World (232050 / missing executable?)

### ISSUE THREAD

**Issue by llikeitt** [ValveSoftware/Proton#582]
The requested **runme.sh** not exist!

![screenshot_20180825_213737](https://user-images.githubusercontent.com/5028336/44621917-1e8b7800-a8af-11e8-8ca4-2aac27a0f742.png)

**Comment by d10sfan** [comment]
If I remember correctly, that's because there was a Linux version for that game (their own wine port). A good way to tell if it's using proton or not for sure is that steamplay message on the top right of the steam library page.

**Comment by llikeitt** [comment]
The **Steam Play** message is missing. But it seems that the downloaded files are for Windows.

![screenshot_20180825_221228](https://user-images.githubusercontent.com/5028336/44622179-fb16fc00-a8b3-11e8-98e2-3d385131ea2a.png)

**Comment by kisak-valve** [comment]
The game devs have linux depots and it looks like you need to opt into the linux-version-wine beta branch https://steamdb.info/app/232050/depots/?branch=linux-version-wine.

Closing as this is not a proton issue.
