### ISSUE TITLE
Star Wars Episode 1 Racer broken audio in cutscenes (808910)

### ISSUE THREAD

**Issue by jonkoops** [ValveSoftware/Proton#5820]
# Compatibility Report
- Name of the game with compatibility issues: Star Wars Episode 1 Racer
- Steam AppID of the game: 808910

## System Information
- GPU: AMD Radeon RX 6900 XT
- Driver/LLVM version: Mesa 22.0.1, LLVM 13.0.1
- Kernel version: 5.17.5-300.fc36.x86_64
- Link to full system information report: https://gist.github.com/jonkoops/e2c23f4e473c334198d0aedeee66d11d
- Proton version: 7.0-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-808910.log](https://github.com/ValveSoftware/Proton/files/8636047/steam-808910.log)

## Symptoms 

During any of the cutscenes, such as the game intro no sound is audible.

## Reproduction

Start the game and view the introduction cutscene.

**Comment by kisak-valve** [comment]
Hello @jonkoops, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2603#issuecomment-1119072213.

**Comment by jonkoops** [comment]
Ahhh, that makes sense. Thank you.
