### ISSUE TITLE
Games not launches through Proton

### ISSUE THREAD

**Issue by IDeathByte** [ValveSoftware/Proton#5823]
####  System information

* Current beta and stable
* Manjaro
* Opted into Steam client beta?: yes
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
Steam doesn't run any games through proton

#### Steps for reproducing this issue:

1. Install any game for windows
2. Run it through any proton version
3. See how nothing happens

I tryed switch to stable steam, use different proton builds (7.0, Experimental bleeding-edge, GE, tkg), full reinstall packages. clean caches etc.
Native games works fine, through system wine/lutris all works too. 
I'm not think what's is proton issue, because i use builds, whats works fine a couple day ago. 
Problem caused from Tuesday or Wednesday as i think, after last steam update.

[steam.log](https://github.com/ValveSoftware/steam-for-linux/files/8644835/steam.log)
[steam-proton-887450.log](https://github.com/ValveSoftware/steam-for-linux/files/8644836/steam-proton-887450.log)

**Comment by Blisto91** [comment]
A couple of things you could try.
In `Steam/steamapps/common/` delete `SteamLinuxRuntime_soldier` and then in your steam library find `Steam Linux Runtime - Soldier` and verify the files so they download again.

If you don't have it installed already you can try to install `steam-native-runtime` and then try launching the regular steam runtime again. Even if you aren't going to use it it can fix issues for some people since it pulls in a bunch of extra packages on your system which might help. Tho if wine works it might not do anything but is relatively fast to try out.

**Comment by IDeathByte** [comment]
I has native libs - result similar for runtime and native.
Steps with runtime_soldier didn't helped too.

**Comment by Blisto91** [comment]
Can you post a steam system information report as a gist or text file. You can find it in the steam gui -> Help - System information. Remember to wait 10-15 secs before copying to make sure it has gathered all the info.

**Comment by IDeathByte** [comment]
[sysconf.txt](https://github.com/ValveSoftware/Proton/files/8645891/sysconf.txt)

**Comment by Blisto91** [comment]
I am unsure if `"timeout: отслеживаемая команда завершилась созданием дампа"` where it checks vulkan drivers mean something is off or it's not relevant.

Were you using dxvk or vkd3d-proton for the games you launched through wine or lutris? If yes then your vulkan drivers are probably fine.

**Comment by IDeathByte** [comment]
Yep. Mostly for GOG titles, but all work fine.

**Comment by IDeathByte** [comment]
Seems like fixed now after last system update.
If it vulkan fault, possible what's vulkan-icd-loader-git solve problem.

**Comment by Blisto91** [comment]
Yay!
And boo cuz it's annoying when things randomly stop working and one is not sure what made it work again 😁

**Comment by eeyrjmr** [comment]
I'm facing something similar where proton-experimental and proton7 do not work but proton6 does

**Comment by kisak-valve** [comment]
Closing because this appears to have been a system config or video driver / render stack issue.
