### ISSUE TITLE
Ubisoft Connect for AC Odyssey won't allow game to launch

### ISSUE THREAD

**Issue by hartd0** [ValveSoftware/Proton#5829]
# Compatibility Report
- Name of the game with compatibility issues: Assassin's Creed Odyssey
- Steam AppID of the game: 812140

## System Information
- GPU: RTX 2060
- Driver/LLVM version: nvidia 510.68.02 -->
- Kernel version: 5.17.5-76051705-generic
- Link to full system information report as [Gist](https://gist.github.com/):  https://gist.github.com/hartd0/1e55bef02ccae26decb116bd9fdb1d3f
- Proton version:  All available in Steam including Experimental

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms   Attempt to launch AC Odyssey, Ubisoft Connect starts up at "Initializing" but ends with an error - "Connection Lost - A Ubisoft service is currently unavailable.  Please try again later."
But no matter how long you wait, it never works.  I've been playing this game for the last few years with little to no issues on Linux - over 500 hours, but now it won't launch.
[steam-812140.log](https://github.com/ValveSoftware/Proton/files/8663930/steam-812140.log)
![Screenshot from 2022-05-09 23-24-46](https://user-images.githubusercontent.com/105310070/167693702-7ef72129-c234-4d11-af54-6d6839793f66.png)
[systeminfo.txt](https://github.com/ValveSoftware/Proton/files/8663939/systeminfo.txt)

**Comment by kisak-valve** [comment]
Hello @hartd0, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1757#issuecomment-1122732200.
