### ISSUE TITLE
Elden ring controller issues

### ISSUE THREAD

**Issue by ShiroAmakusaTokisada** [ValveSoftware/Proton#5831]
# Compatibility Report
- Name of the game with compatibility issues: Elden Ring
- Steam AppID of the game: 1245620

## System Information
- GPU: Radeon RX 6600
- Driver/LLVM version: 13.0.1
- Kernel version: 5.17.4-artix1-1
- Proton version: Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Upon launching the game, the controller will not be recognized. I own a Dualshock 4 controller v2. Both that and my other controllers of note do not work with proton, but work with Windows. The game will recognize the touchpad as a computer mouse, but won't recognize the controller itself. This controller works well with other games and if it's used on Windows. 

## Reproduction
Launching the game and attempting to use the Ds4 will result in the ds4 being unresponsive, with the game only accepting keyboard and mouse. 

[steam-1245620.log](https://github.com/ValveSoftware/Proton/files/8665632/steam-1245620.log)

**Comment by kisak-valve** [comment]
Hello @westbelow, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1123036266.
