### ISSUE TITLE
Yakuza 0 Crash At Startup

### ISSUE THREAD

**Issue by MephresGH** [ValveSoftware/Proton#5834]
# Compatibility Report
- Name of the game with compatibility issues: Yakuza 0 (Vanilla) https://store.steampowered.com/app/638970/Yakuza_0
- Steam AppID of the game: 638970

## System Information
- System: EndeavourOS 22.1 SOTA
- GPU: NVIDIA KFA2 GTX 1050 Ti OC
- Driver/LLVM version: nvidia 510.68
- Kernel version: 5.17.5-arch1-2 (x64)
- Proton version: Experimental (7.0-2 3.16-9 and 4.11-13 tested as well)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

The game crashes on startup without any logical way to fix said issue. Multiple Proton versions were tried, even including the newest GloriousEggroll fork, but nothing resulted in the game starting up as intended. 

## Reproduction
- Start game with recent Proton version(s)
- Wait for start of game
- Experience crash

The files required for much more information have been linked to this post as well:
[System Information.txt](https://github.com/ValveSoftware/Proton/files/8672148/System.Information.txt)
[steam-638970.log](https://github.com/ValveSoftware/Proton/files/8672150/steam-638970.log)

**Comment by kisak-valve** [comment]
Hello @MephresGH, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/492#issuecomment-1124055526.
