### ISSUE TITLE
Thief 3: Deadly Shadows (6980)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#5837]
# Compatibility Report
- Thief 3: Deadly Shadows:
- Steam AppID: 6980:

## System Information
- GPU: Geforce GTX 1050m
- Driver/LLVM version: nvidia 515.43.04
- Kernel version: 5.17.7
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/RickStanley/3e3b0fdebbfd8bc10ba93e035cb7fc48
- Proton version: 1652278199 experimental-7.0-20220511 and 6.3

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Log: [steam-6980.log](https://github.com/ValveSoftware/Proton/files/8694257/steam-6980.log)

## Symptoms 
I try to launch the game, but it just changes to "playing" and nothing happens. I'm able to stop the game from Steam.

## Considerations
I saw that https://github.com/ValveSoftware/Proton/issues/586 tries to whitelist the game as playable, but I can't play at the moment.

Many report here: https://www.protondb.com/app/6980 that the game is playable.

I tried installing Sneaky Update but I found another issue, with the installer itself. When trying to execute the installer either with:
```bash
wine Setup_T3SneakyUpgrade_Full_1.1.10.exe
```

or

```bash
STEAM_COMPAT_CLIENT_INSTALL_PATH="$HOME/.steam/steam" STEAM_COMPAT_DATA_PATH=/mnt/spare/SteamLibrary/steamapps/compatdata/6980/ ~/.steam/steam/steamapps/common/Proton\ -\ Experimental/proton run Setup_T3SneakyUpgrade_Full_1.1.10.exe
```

(as suggested here: https://steamcommunity.com/sharedfiles/filedetails/?id=2163910408), it always yields: "Thief 3 registry not found. Please reinstall the game.".

!["Thief 3 not found in registry" error.](https://user-images.githubusercontent.com/23178554/168454281-963f95f5-785c-47b7-a5f7-6a045addbc50.png)

**Comment by ghost** [comment]
Trying with Proton 3.16 I get this: [steam-6980.log](https://github.com/ValveSoftware/Proton/files/8694276/steam-6980.log)
 
Not sure what to make of this... Is wine trying to find/open t3.exe and T3Main.exe and can't find/open?

**Comment by kisak-valve** [comment]
Hello @RickStanley, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/586#issuecomment-1126932944.
