### ISSUE TITLE
Space Rangers HD: A War Apart (214730) 

### ISSUE THREAD

**Issue by BetaVersionBY** [ValveSoftware/Proton#5840]
# Compatibility Report
- Name of the game with compatibility issues: Space Rangers HD: A War Apart
- Steam AppID of the game: 214730

## System Information
- GPU: RX 6600
- Driver/LLVM version: Mesa 22.0.3
- Kernel version: 5.17.6
- Link to full system information report as [Gist](https://gist.github.com/BetaVersionBY/3d04dac5f9e80a4feea1ed5b385cb252)
- Proton version: 4.2-9, 7.0-2 and Experimental
- [steam-214730.log](https://github.com/ValveSoftware/Proton/files/8695659/steam-214730.log) for Experimental
- [steam-214730.log](https://github.com/ValveSoftware/Proton/files/8695701/steam-214730.log) for 4.2-9

## I confirm:
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game won't launch. Tried with and w/o PROTON_NO_ESYNC=1 that was recommended in other report.
A year or two ago this game worked with Proton, but now it doesn't work with any version.

## Reproduction
Try launching the game.

**Comment by kisak-valve** [comment]
Hello @BetaVersionBY, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/750#issuecomment-1125318959.
