### ISSUE TITLE
Atelier Sophie: The Alchemist of the Mysterious Book DX (1502970)

### ISSUE THREAD

**Issue by sorathecrow** [ValveSoftware/Proton#5843]
# Compatibility Report
- Name of the game with compatibility issues: Atelier Sophie: The Alchemist of the Mysterious Book DX
- Steam AppID of the game: 1502970

## System Information
- GPU: AMD Steam Deck GPU
- Driver/LLVM version: 4.6 Mesa 22.0.0
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton Experimental

## I confirm:
- Yes-- that I haven't found an existing compatibility report for this game.
- [Yes ] that I have checked whether there are updates for my system available.

## Symptoms
Intro video loads on Proton Experimental fine when using Stable OS Update Channel, but on the Beta channel it plays a color calibration clip.

**Comment by kisak-valve** [comment]
Hello @sorathecrow, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the issue, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by sorathecrow** [comment]
I reinstalled the beta channel and tried to relaunch the game and now it won't even boot. I added that command to the launch options but I can't find where it is being stored.

**Comment by sorathecrow** [comment]
It is working now, I needed a space between the 1 and %. The video is playing with sound now too on the beta channel. I tried everything I could think of, validated both the game and the proton files, redownloaded, moved to internal storage, etc. None of it worked. But for some reason switching to stable channel then going back worked.
