### ISSUE TITLE
Hitman 2 D3D12 no longer supported

### ISSUE THREAD

**Issue by telometto** [ValveSoftware/Proton#5848]
# Compatibility Report
- Name of the game with compatibility issues: Hitman 2
- Steam AppID of the game: 863550

## System Information
- GPU: AMD RX6800 
- Driver/LLVM version: Mesa 22.2 
- Kernel version: 5.17.7-200.fc35.x86_64 
- Link to full system information report as [Gist](https://gist.github.com/): [Logs](https://gist.github.com/telometto/1d6e9ab27f50dc7e630fa1ccd5e72220)
- Proton version: Proton Experimental 7.0-20220511

## I confirm:
- [✅] that I haven't found an existing compatibility report for this game.
- [✅] that I have checked whether there are updates for my system available.

## Symptoms 
I used to be able to run Hitman 2 using D3D 12 in the previous Proton Experimental version, but now it is not possible anymore.

## Reproduction

1. Launch game.
2. When the launcher opens, select  '**Options**' > '**Graphics API**' > select '**Direct3D 12**' > save and close the settings.
3. Select '**Play**'.

**Comment by kisak-valve** [comment]
Hello @telometto, we're using one issue per unofficially supported game title, and usually I'd transfer this to #2121, however, your issue is straight forward. The build of VKD3D-Proton in Proton Experimental requires mesa 22.0 or newer, and the mesa 21.3.8 driver inside your Flatpak environment is too old. This requirement is intended and not a bug.

**Comment by telometto** [comment]
I see. Thank you for letting me know. Do you know if there's an update to VKD3D in the works?

**Comment by kisak-valve** [comment]
Can you clarify the intent of your question? An update to VKD3D-Proton has already happened, and more will happen over time with Proton Experimental.

**Comment by telometto** [comment]
> Can you clarify the intent of your question? An update to VKD3D-Proton has already happened, and more will happen over time with Proton Experimental.

Nothing in particular. I was just wondering in case I'll have to just roll back to the regular Steam package from the repos or just continue using Flatpak.
