### ISSUE TITLE
Xbox controller (serie X) not support vibration controller

### ISSUE THREAD

**Issue by NunzioArdi** [ValveSoftware/Proton#5849]
# Compatibility Report
- Name of the game with compatibility issues: Ori and the Will of the Wisps
- Steam AppID of the game: 1057090

## System Information
- GPU:  GTX 970
- Driver/LLVM version: nvidia 515.43.04-4
- Kernel version: 5.17.7-arch1-2
- Link to full system information report as [Gist](https://gist.github.com/): [link](https://gist.github.com/NunzioArdi/1f89a12878658e19614415ce833376f9)
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
my Xbox Series X controller is plugged into USB. It is recognized and usable in game, but no vibration is made.

**Comment by kisak-valve** [comment]
Hello @NunzioArdi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4528#issuecomment-1130381749.
