### ISSUE TITLE
Grounded The bugs strike back

### ISSUE THREAD

**Issue by Pyrrhu5** [ValveSoftware/Proton#5851]
# Compatibility Report
- Name of the game with compatibility issues: Grounded 
- Steam AppID of the game: 962130

## System Information
- GPU: NVIDIA GeForce RTX 2070 SUPER
- Driver/LLVM version: nvidia 510.68.02
- Kernel version: 5.15.38-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): [System info](https://gist.github.com/Pyrrhu5/11ad79aa435a36fe69bd956b2928580c)
- Proton version: Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

The game freezes on the loading screen systematically, only killing the process allows to exit it.

## Reproduction

Launching the game from any config as everyone is reporting the game borked on ProtonDB

Launching it from the terminal with the following command:

```
flatpak run com.valvesoftware.Steam steam://rungameid/962130
```

Raises the following error:

```
[0522/091018.734:ERROR:mf_helpers.cc(12)] Error in dxva_video_decode_accelerator_win.cc on line 355

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'SpeechSynthWrapper:_synthesizer' (4) due to: Could not load file or assembly 'System.Speech, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
  at (wrapper native-to-managed) <Module>.CreateSpeechSynthesizer()
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'SpeechSynthWrapper:_synthesizer' (4) due to: Could not load file or assembly 'System.Speech, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

```

**Comment by kisak-valve** [comment]
Hello @Pyrrhu5, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4102#issuecomment-1133888246.
