### ISSUE TITLE
Final Fantasy XIV - Unable to Complete Version Update

### ISSUE THREAD

**Issue by dbox1983** [ValveSoftware/Proton#5852]
# Compatibility Report
- Name of the game with compatibility issues: Final Fantasy XIV
- Steam AppID of the game: 39210

## System Information
- GPU: AMD RADV VANGOGH 
- Driver/LLVM version: Unsure?
- Kernel version: Linux version 5.13.0-valve10.3-1-neptune-02176-g5fe416c4acd8
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/dbox1983/2f25f3e6f20a70aa1a8be5b1e4e5cbde
- Proton version: Experimental 5/19/22

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

I'm able to open the FF14 launcher now, but I get an error "Unable to complete version update" with a code 30436. This error prevents the actual game files from being downloaded.

## Reproduction

Happens every time I try to log into the client.

Troubleshooting steps:
-Uninstall, reinstall
-Full system update in game mode and in KDE, reboot 
-Uninstall, deletion of files in PFX folder in case of misconfigured config files. Reboot, reinstall.
-Uninstall, reinstall on SD instead of internal SSD

In all cases, I get the same error (attached screen shot) 

![FF14 Launcher issue](https://user-images.githubusercontent.com/65613444/169704451-7dc83370-27a3-453d-905d-4fa25d31b051.png)
[steam-39210.log](https://github.com/ValveSoftware/Proton/files/8749752/steam-39210.log)

**Comment by kisak-valve** [comment]
Hello @dbox1983, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/580#issuecomment-1133928416.

**Comment by dbox1983** [comment]
@kisak-valve Sorry about that! I clearly misunderstood the assignment ;-).
