### ISSUE TITLE
Nioh 2 - The Complete Edition (1325200). Game crashes often after visiting skill menus.

### ISSUE THREAD

**Issue by neon-grim** [ValveSoftware/Proton#5853]
# Compatibility Report
- Name of the game with compatibility issues: Nioh 2 – The Complete Edition
- Steam AppID of the game: 1325200

## System Information
- GPU: AMD Radeon RX 6900 XT (sienna_cichlid, LLVM 14.0.0, DRM 3.44, 5.17.7-300.fc36.x86_64)
- Driver/LLVM version: Mesa 22.0.3
- Kernel version: 5.17.7-300.fc36.x86_64
- Link to full system information report as Gist: [gistfile1.txt](https://gist.github.com/Lialeth/64d4e2ae612887a7ebac069084cafadd)
- Proton version: Experimental, 7.0-2, GE 7-10, GE 7-18

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[Proton log. The files has a lot of lines.](https://drive.google.com/file/d/16bSq-m2r8FBr9By51MAr11psgdALIGpp/view?usp=sharing)

## Symptoms 

-VRR doesnt work natively under x11 (havent tested on wayland since I use gnome).
- Game crashes often when visiting menus such as the skill assignment menu for a specific weapon or Soul core menus.

Currently these are the launch options which I use. They make the game a bit more stable and gamescope allow for VRR to work.

`gamescope -f -b -e -r 110 -- gamemoderun mangohud PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 PROTON_LOG=1 ENABLE_VKBASALT=1 %command%`

## Reproduction

Enter a mission and then open the skill assignment menu for a weapon (odachi for example). Change skills on any stances, then leave. The game will crash before leaving the menu or a few minutes afterwards. Rarely the game doesnt crash at all, just repeat the process again.

**Comment by kisak-valve** [comment]
Hello @Lialeth, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4593#issuecomment-1131678453.
