### ISSUE TITLE
[need help]: borderlands 3 killed by systemd-oomd because of huge memory usage

### ISSUE THREAD

**Issue by lumingzh** [ValveSoftware/Proton#5854]
borderlands 3 runs with DirectX 12 API on a 16GB RAM laptop, but after some time like 20 minutes the memory usage will rise up to the whole RAM and killed by systemd-oomd.

Is there any way to limit or reduce the memory usage of borderlands 3 or fix this issue?

Is this relates to DirectX 12 or unreal Engine? Or it is borderlands' own bug?

Thank you.

**Comment by kisak-valve** [comment]
Hello @lumingzh, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3635#issuecomment-1134003364.
