### ISSUE TITLE
Memory Allocation Error

### ISSUE THREAD

**Issue by Osced86** [ValveSoftware/Proton#5855]
I'm using Proton 6.3 and have recently noted that I'm getting Memory Allocation problem, when using FO4Edit it crashes around 1,5-1,8 gb RAM, when I used an older version I had no problem. Have no idea what can have changed, since it worked before, more then upgraded Proton. Have tried Proton 7 and gives same error.

I've looked at the Proton debug log and found this error: virtual:try_map_free_area mmap() error cannot allocate memory, range 0xf4f60000-0x8ad0000, unix_prot 0x3.  Have found this error even when it doesn't crash, but I think it can be connected with my issue.

Hope that someone that can put me in the right direction to fix my problem.

Proton  Details.
Proton: 1638789187 proton-6.3-8c
SteamGameId: 377160
Command: ['/home/****/.local/share/Steam/steamapps/common/Fallout 4/Fallout4Launcher.exe']
Options: {'forcelgadd', 'noesync'}
depot: 0.20220329.49
pressure-vessel: 0.20220315.0
scripts: v0.20220311.0-0-gae4cbed
soldier: 0.20220329.0 soldier 0.20220329.0
Kernel: Linux 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64

**Comment by kisak-valve** [comment]
Hello @Osced86, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/308#issuecomment-1134009167.
