### ISSUE TITLE
make install fails with certificate error

### ISSUE THREAD

**Issue by khaddra** [ValveSoftware/Proton#5856]
Whenever I try to compile proton, with `make install` or with `configure.sh`, both docker and podman fail with 
`docker: Error response from daemon: Get "https://registry.gitlab.steamos.cloud/v2/": x509: certificate is valid for gitlab.steamos.cloud, not registry.gitlab.steamos.cloud.`
or 
`Error: initializing source docker://registry.gitlab.steamos.cloud/proton/soldier/sdk:0.20220119.0-1: pinging container registry registry.gitlab.steamos.cloud: Get "https://registry.gitlab.steamos.cloud/v2/": x509: certificate is valid for gitlab.steamos.cloud, not registry.gitlab.steamos.cloud`
which seems to suggest that Valve has set up its certificates incorrectly (or something on my OS is checking them too strictly).
I only pulled the repository yesterday did `git pull` and `git submodule update --recursive` before submitting this issue to make sure I was using the latest version.

`uname -r`:
`5.15.32-gentoo-r1-x86_64`

`docker --version`:
`Docker version 20.10.12, build e91ed5707e`

`podman --version`:
`podman version 4.0.3`

**Comment by smcv** [comment]
The registry is currently misconfigured. A fix is in progress.

**Comment by smcv** [comment]
The misconfiguration has been fixed.

**Comment by khaddra** [comment]
Now it compiles without error and works to run games. Thanks for your help.
