### ISSUE TITLE
Games do not launch via Steam Proton.

### ISSUE THREAD

**Issue by Creeperspielt** [ValveSoftware/Proton#5857]
Hello.
recently, games do not launch for me via proton. i already tried switching versions, reinstalling the game, reinstalling steam etc. it just wont work for me.

**Comment by Blisto91** [comment]
Can you generate a system report by going into steam -> Help -> System information -> wait 10 - 15 seconds -> copy paste all the text into a github gist or text file and link it here. Then we can hopefully quickly rule out anything system related.

Also for a game that doesn't launch try to add `PROTON_LOG=1 %command%` to the games launch options in steam and if it generates a log in your home folder then also include it here.

**Comment by Creeperspielt** [comment]
alright.
https://gist.github.com/Creeperspielt/4dc784f66ad18acc75c5bd90cee1d01a here is the system info.
https://gist.github.com/Creeperspielt/89d82ca0000ed5ebd1cbf8f77224304e here is the proton log

**Comment by kisak-valve** [comment]
Hello @Creeperspielt, a header only log hints that Proton hit an issue in its python before the actual games start. If you completely close Steam, then run `steam` from a terminal, is there a hint in the terminal spew when trying to run the game? What filesystem are you using with `/media/herrocis/Steam`?

**Comment by Creeperspielt** [comment]
`/media/herrocis/Steam` is my WD external hard drive, that shouldn't be an issue.
also no, there isnt any info when running the game when steam is started on terminal.
https://gist.github.com/Creeperspielt/145078493e04e933d647fb27c2fec96a this is what terminal says after i run steam and the game.

**Comment by bncmajor** [comment]
i'm not that familiar with this given that no exact error or anything can be seen... but, i've came across this during few games.. the external hard drive what filesystem has? ntfs made this bug for me definitely..
also if changing the game location does not solve it, you can try to mess around with proton versions, try older ones to see if game starts up..

**Comment by Creeperspielt** [comment]
yeah, im using NTFS. changing the location doesnt work, already tried. my pc hard drive has FAT32 though.

**Comment by bncmajor** [comment]
can't u try to change to ext4 maybe?

**Comment by Creeperspielt** [comment]
wich one? my external hdd or my main drive? also, how do i do that? will that wipe my entire drive?

**Comment by bncmajor** [comment]
i think the game should be on a ext4 partition, whatever you can change to it. it does erase the data - but you can split up the existing partitions and you can make the free space to ext4 on one of them

but i'm not entirely sure that will it solve ur issue or not, i have seen this in the past but maybe thousands of stuff could cause this

**Comment by Blisto91** [comment]
Proton does sometimes have issues with ntfs yes, tho i don't know the details. That's probably what kisak was getting at when asking about filesystem on the drive.

But if moving the library on to your main disk doesn't work, then i'm not sure.

Can you update your system info gist. It isn't fully complete and you need to let it run for around 10-15 seconds. I know it isn't very obvious it's still going in the background 🙂

**Comment by Creeperspielt** [comment]
alright, i updated the system info gist.
https://gist.github.com/Creeperspielt/4dc784f66ad18acc75c5bd90cee1d01a
i formatted my external hdd to EXT4 now. there wasnt much lost anyway.

**Comment by Creeperspielt** [comment]
yes! it seems to be working (for now!), pvz launches now, however i'll comment if it doensnt work anymore.
thanks a lot!

**Comment by kisak-valve** [comment]
Closing in favor of the [various older NTFS issue reports](https://github.com/ValveSoftware/Proton/search?q=ntfs&type=issues).

**Comment by Blisto91** [comment]
GZ on getting it working. Sad you had to reformat tho.
