### ISSUE TITLE
Microsoft Flight simulator 2020: Photogrametry does not work.

### ISSUE THREAD

**Issue by TheOrangeFlamingo** [ValveSoftware/Proton#5858]
# Compatibility Report
- Name of the game with compatibility issues: Microsoft Flight simulator
- Steam AppID of the game: 1250410

## System Information
- GPU: AMD Radeon 6900XT
- Driver/LLVM version: Mesa 22.0.4
- Kernel version: 5.17.9-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/MrNadix/e2059fbb63e2f3c0864208753d682593
- Proton version: 7.2

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

## Symptoms 

Photogrametry does not work.

## Reproduction
Open the game, enable photogrametry, fly over some city with photogrametry. Tested: (Vigo (With Iberic update), New york, Málaga (With Iberic update), Madrid (With Iberic update). There are going to be generic ugly buildings instead of photogrametry ones.

**Comment by kisak-valve** [comment]
Hello @MrNadix, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-1135102932.
