### ISSUE TITLE
Cyberpunk 2077 wont launch

### ISSUE THREAD

**Issue by tommipontinen76** [ValveSoftware/Proton#5859]
My system information https://gist.github.com/hamburgerghini1/9477487397119aed4b7ed60bab3f24e0

And proton log  https://gist.github.com/hamburgerghini1/93cdb8ee6d6426d04e6235a472a8a4fe

I have tried  with different  proton  versions but  it wont launch.

**Comment by kisak-valve** [comment]
Hello @hamburgerghini1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1135926262.
