### ISSUE TITLE
Devil May Cry 4: Special Edition (329050) can't launch in fullscreen

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#5860]
# Compatibility Report
- Name of the game with compatibility issues: Devil May Cry 4: Special Edition
- Steam AppID of the game: 329050

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/HeroshiHero/f5cb9c6f633b4bff3d9963f6554405ae)

## I confirm:
- [ v ] that I haven't found an existing compatibility report for this game.
- [ v ] that I have checked whether there are updates for my system available.

## Symptoms 
The game can't launch in full screen mode using DXVK

## Reproduction
- Open the game
- Go to the settings where you configure the graphics and resolution
- Set to "full screen" instead of windowed mode
- Close the game
- Open the game again

**Comment by kisak-valve** [comment]
Hello @HeroshiHero, please use #1779 for all feedback related to running Devil May Cry 4: Special Edition with Proton. Closing blank issue report template.
