### ISSUE TITLE
Attempting to run Death Stranding while Xbox One controller is connected causes a crash

### ISSUE THREAD

**Issue by Ointm3nt** [ValveSoftware/Proton#5862]
Death Stranding opens and runs perfectly well, but if my Xbox One controller is connected to the computer via bluetooth at any point during or after the game being launched/open, the game crashes with the below error message.
[error.txt](https://github.com/ValveSoftware/Proton/files/8775303/error.txt)

I'm on Arch Linux with the latest version of Steam, running Proton Experimental. My system is fully up-to date, and I'm running an AMD 6800 XT with vulkan-radeon drivers, along with an Intel 12700 CPU.

**Comment by kisak-valve** [comment]
Hello @Ointm3nt, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4069#issuecomment-1138012663.
