### ISSUE TITLE
Some issues about the documentation on sharing games between Windows and Pop OS/Ubuntu

### ISSUE THREAD

**Issue by Bandito11** [ValveSoftware/Proton#5863]
[https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows#editing-fstab=](url)

On the documentation, on this part, 

***UUID=38CE9483CE943AD8 /media/gamedisk lowntfs-3g uid=1000,gid=1000,rw,user,exec,umask=000 0 0***

If I take out the part about _**user**_ off the list, the game runs as expected on Pop OS 22.04 LTS and Windows 10 when sharing the folder.

**Comment by kisak-valve** [comment]
Hello @Bandito11, you can make this adjustment yourself.

It should also be noted that sharing a Steam library across OSes is an unsupported scenario on the Steam Client's side regardless of what has been written in Proton wiki pages.

**Comment by Bandito11** [comment]
Ok, thanks.

Esteban Morales

On May 26, 2022, at 7:13 AM, kisak-valve ***@***.***> wrote:

﻿

Hello @Bandito11<https://github.com/Bandito11>, you can make this adjustment yourself.

It should also be noted that sharing a Steam library across OSes is an unsupported scenario on the Steam Client's side regardless of what has been written in Proton wiki pages.
