### ISSUE TITLE
Styx: Shards of Darkness breaks when using HDMI for sound

### ISSUE THREAD

**Issue by mrmatteastwood** [ValveSoftware/Proton#5865]
[steam-355790.log](https://github.com/ValveSoftware/Proton/files/8777521/steam-355790.log)
# Compatibility Report
- Name of the game with compatibility issues: Styx: Shards of Darkness
- Steam AppID of the game: 355790

## System Information
- GPU: GTX 1080 Ti
- Driver/LLVM version: 510.73.05
- Kernel version: 5.13.0-27-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/mrmatteastwood/7c8d0032c967b58a39b7d0e46f0ee09d
- Full system info by Linux Mint: https://termbin.com/pm2r
- Proton version: Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
When launching Styx: Shards of Darkness using the PC's HDMI-out for sound, the game runs without any sound, the Unreal video plays overlaid by a pink screen and then everything just stops. Need to Alt-Tab out of the game and press Steam's "Stop" button. Issue does not occur when using another sound device, e.g. USB headphones.

## Reproduction
1. Set up a PC and home theatre system by running an HDMI cable from the graphics card to the AVR
2. Install Steam and Styx: Shards of Darkness on Linux Mint 20.2
3. Open Linux Mint's sound settings
4. Select HDMI device and set it to any profile (stereo, 5.1...)
5. Launch game from within Steam

## Notes
- Video showing the issue here: https://youtu.be/WWkS3NvdbJU
- No other bug reports found here that would be relevant to this problem.
- When running the game with another sound device and then switching to HDMI while the game is running, you can get stereo sound, but no surround.
- fwiw, this issue does not occur on Windows 10.

**Comment by mrmatteastwood** [comment]
Oh, I have some additional info!

## My screen setup:

- **Screen 1: ** PC => DisplayPort cable > Screen (2560x1440)
- **Screen 2: ** PC => DVI cable > Screen (1280x1024)
- **Screen 3: ** PC => HDMI cable > AVR > HDMI cable > Screen (1920x1080)

The game runs on **screen 1**.

## These don't fix the problem:

- Enabling/disabling "Enable the Steam Overlay while in-game" and "Use Desktop Game Theatre while SteamVR is active"
- Running the game with or without "gamemoderun %command%"
- Using GE-Proton7-18, Proton Experimental, Proton 7.0-2 or Proton 6.3-8
- Verifying all local files (they were all ok)

**Comment by kisak-valve** [comment]
Hello @mrmatteastwood, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/964#issuecomment-1138436039.

**Comment by mrmatteastwood** [comment]
Thanks, good to know! I will keep this in mind for the future. Will keep an eye on the other one. Let me know if there's anything else I can do to contribute :-) Really excited about Proton.
