### ISSUE TITLE
UI issues in Pathfinder WOTR

### ISSUE THREAD

**Issue by mercifulboss** [ValveSoftware/Proton#5866]
# Compatibility Report
- Name of the game with compatibility issues: Pathfinder Wrath of the Righteous (WOTR)
- Steam AppID of the game:  1184370

## System Information
- GPU: RTX2060 mobile
- Driver/LLVM version: NVIDIA 510.68.2 (same issue persists on the 515 driver)
- Kernel version: 5.17.9
- Link to full system information report as [Gist](https://gist.github.com/mercifulboss/e9583b7d1ecde7359028fd74d92b04f2:
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms Whenever I open the menus i get two bars above and below the screen, on inventory menu those bars also become gray.
![Pathfinder Wotr](https://user-images.githubusercontent.com/90151527/170523844-cbf4f80a-1bdb-4fe9-bfac-1562e11b79e3.png)

It seems to be a scaling issue that is not present in windows.

Also, the cursor doesn't render correctly

**Comment by kisak-valve** [comment]
Hello @mercifulboss, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5150#issuecomment-1138722920.
