### ISSUE TITLE
Skyrim Hungs

### ISSUE THREAD

**Issue by John-H-Smith** [ValveSoftware/Proton#5867]
# Compatibility Report
- Name of the game with compatibility issues: The Elder Scrolls V: Skyrim Special Edition
- Steam AppID of the game: 489830

## System Information
- GPU: GTX 970
- Driver/LLVM version: Nvidia 510.73.05, NVML 11.510.73.05
- Kernel version: Linux 5.10.117-1-MANJARO x86_64
- Link to full system information report as [Gist](https://gist.github.com/John-H-Smith/5d0e8207693b1cb80f55927daae803d6):
- Proton version: 70.0-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[Game Log here](https://gist.github.com/John-H-Smith/2cbe853ce0feec57edbc0faf3cef9a31)

## Symptoms 
If I get arrested by any of the city's guards, my game hungs up right after selecting "I will go to jail".

## Reproduction
Just kill some people in a city and wait until the guards arrive. Then, choose the "go to jail" dialog.

**Comment by kisak-valve** [comment]
Hello @John-H-Smith, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4#issuecomment-1139573372.
