### ISSUE TITLE
Railway Empire (503940)

### ISSUE THREAD

**Issue by sid013** [ValveSoftware/Proton#5870]
# Compatibility Report
- Name of the game with compatibility issues:Railway Empire
- Steam AppID of the game:503940

## System Information
- GPU: GEForce 840M
- Driver/LLVM version: Nvidia  -->
- Kernel version: 510.73.05
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/sid013/bba169edc46b9b461dd6dfac2c99394f
- Proton version: 7.0-2

## I confirm:
- [.] that I haven't found an existing compatibility report for this game.
- [.] that I have checked whether there are updates for my system available.

fo:  Game: RailwayEmpire.exe
info:  DXVK: v1.10.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
warn:  OpenXR: Unable to get required Vulkan instance extensions size
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Skipping CPU adapter: llvmpipe (LLVM 12.0.0, 256 bits)
warn:  OpenXR: Unable to get required Vulkan Device extensions size
info:  NVIDIA GeForce 840M:
info:    Driver: 510.73.5
info:    Vulkan: 1.3.194
info:    Memory Heap[0]: 
info:      Size: 2048 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 5901 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
info:  Intel(R) HD Graphics 5500 (BDW GT2):
info:    Driver: 21.2.6
info:    Vulkan: 1.2.182
info:    Memory Heap[0]: 
info:      Size: 5901 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0xf
warn:  DXGI: MakeWindowAssociation: Ignoring flags

## Symptoms 
Very low FPS(2-3)

## Reproduction
Open the game and launch any scenario/campaign

 https://github.com/ValveSoftware/steam-for-linux/issues/8422

**Comment by Blisto91** [comment]
Could you provide a proton log? :)

Edit: Maybe it's selecting your intel igpu.
Does either of these launch options help the issue?
```
VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json %command%
```
```
__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only %command%
```

**Comment by sid013** [comment]
I added PROTON_LOG=1 %command% to the launch options.
I don't see any logs in Home/Steam/                 

__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only %command%
with this launch option my frame rate has become 9-12 .
PS all graphic settings are kept at low

Thank you

**Comment by sid013** [comment]
Devs support please

**Comment by Blisto91** [comment]
Can you add `DXVK_HUD=full` to your launch parameters and take a ingame screenshot and post it here?
So launch parameters becomes
```
__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only DXVK_HUD=full %command%
```


Also how does it run on the native version not running through proton. Or doesn't that work? Dunno if that is what the steam for linux issue you linked is about.

**Comment by sid013** [comment]
On Native the game just crashes instantly.
I just did as you asked
![image](https://user-images.githubusercontent.com/28606108/171359389-179f58e7-7b70-4d90-b4b1-c1a4a917b0a5.png)

Also there was a steam client update just now. Which has made the gameplay stutter free.
For me game is **smooth now**. Don't know what fixed it. 

Thanks for your time and patience Blisto91

**Comment by Blisto91** [comment]
I'm glad it managed to improve more to the point of it being playable.
I see your GPU is maxed out so i think from here on your GPU is the limiting factor. Not ruling out dxvk having some small performance increases in the future ofc.
Maybe the native version can also give a bit extra if it starts working again.

**Comment by sid013** [comment]
Yeah :)
