### ISSUE TITLE
Bloons TD 6 (960090)

### ISSUE THREAD

**Issue by josesilveiraa** [ValveSoftware/Proton#5871]
# Compatibility Report
- Name of the game with compatibility issues: Bloons TD 6
- Steam AppID of the game: 960090

## System Information
- GPU: GTX 1050Ti
- Driver/LLVM version: nvidia 510.60.02
- Kernel version: 5.17.4-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/josesilveiraa/7965d5652fea6eef005aec8e3a112376
- Proton version: Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-960090.tar.gz](https://github.com/ValveSoftware/Proton/files/8792568/steam-960090.tar.gz)

## Symptoms 
The game runs very well, but there are glitches in the cursor, seems like a bad-cropped png image.

## Reproduction
Launch the game and move the cursor.

**Comment by kisak-valve** [comment]
Hello @josesilveiraa, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2330#issuecomment-1140420016.
