### ISSUE TITLE
Apex Legends - Mouse Sensitivity is Broken

### ISSUE THREAD

**Issue by pbogut** [ValveSoftware/Proton#5873]
Proton Version:
experimental-7.0-20220526

Games Affected:
Apex Legends

Issue:
Camera view is way too sensitive.

Looks like some kind of regression. When playing Apex Legends sensitivity is cranked up like 2.5 times.
I noticed it when I changed to Proton-GE-19 from Proton-GE-18. My mouse sensitivity in configuration is
the same, but camera in game is moving over 2 times faster. I tried to figure out if it was GE issue, but 
I have same problem with Proton Experimental, so my guess is its from upstream.

**Comment by kisak-valve** [comment]
Hello @pbogut, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1140535675.
