### ISSUE TITLE
Proton Experimental is failing to utilize DX12/dxvk but Proton7.0-2 works just fine

### ISSUE THREAD

**Issue by NagareHoshi** [ValveSoftware/Proton#5875]
# Games suffering this issue
- Name of the game with compatibility issues: Monster Hunter Rise, Deep Rock Galactic (DX12), and other games utilizing DX12
- Steam AppID of the game: 1446780, 548430

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 470.129.06
- OS version: Drauger OS 7.6 (Strigoi) - Ubuntu Jammy Based
- Kernel version: Linux 5.17.9-xanmod1 #0~git20220518.d88d798 SMP Wed May 18 21:07:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- https://gist.github.com/NagareHoshi/51714103ddfb3740d813836a7b0c2350#file-systeminfo-txt
- Proton version: Proton Experimental (Proton 7.0-2 surprisingly works)

## I confirm:
- [x] that these games used to work in Proton Experimental
- [x] that these games have good results in protondb

## The problem:
Proton experimental is failing to recognize that my system is compatible with DX12 or maybe it's failing to utilize dxvx which in effect, makes it think that my system does not support DX12. I'd usually be able to fix this by checking file integrity of Proton Experimental or Uninstalling+Installing it again, but sadly that's not working anymore. Weirdly enough, this isn't the case at all using Proton 7.0-2.

One thing to note is that this used to work just fine 3 weeks ago.

I've confirmed that vulkan is working as usual using vulkan-tools. Some guidance in figuring this out would be appreciated, especially if it looks like I'll have to open an issue with the xanmod kernel maintainers. Please let me know if you need additional information to assist me regarding this matter.

## Error messages when launching mentioned games:
MH Rise:
Path to MonsterHunterRise.exe
"d:\\reengine\\reengine\\gitroot\\runtime\\modules\\render\\os\\renderdevicedx12.cpp" 11963
D3D12CreateDeviceFailed
Please restart your computer.

Deep Rock Galactic:
DX12 is not supported on your system. Try running without the -dx12 or -d3d12 command line argument.

**Comment by kisak-valve** [comment]
Hello @NagareHoshi, the build of VKD3D-Proton in Proton Experimental requires the NVIDIA driver to be 510.47 or newer. This requirement is not a bug. Please update your video driver if you want to tinker with Proton Experimental.

**Comment by NagareHoshi** [comment]
> Hello @NagareHoshi, the build of VKD3D-Proton in Proton Experimental requires the NVIDIA driver to be 510.47 or newer. This requirement is not a bug. Please update your video driver if you want to tinker with Proton Experimental.

Man, so that's what it was, many thanks for letting me know! At least I have something solid to convince the maintainer of DraugerOS to push towards newer NVIDIA drivers.
