### ISSUE TITLE
Please make Master of Orion 1 Classic compatible with the Steam Deck

### ISSUE THREAD

**Issue by novasheikh** [ValveSoftware/Proton#5878]
# Compatibility Report
- Name of the game with compatibility issues: Master of Orion 1 (Classic)
- Steam AppID of the game: 410970

## System Information
- GPU:  SteamDeck
- Driver/LLVM version:  SteamDeck
- Kernel version:  SteamDeck latest OS 3.2
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Latest experimental

## I confirm:
- [# ] that I haven't found an existing compatibility report for this game.
- [# ] that I have checked whether there are updates for my system available.

## Symptoms  
The game fails to open in dosbox on steamOS but works in desktop mode with dosbox x using GOG version. Can we update the dosbox commands so the SteamOS version loads please? Thanks

**Comment by kisak-valve** [comment]
Hello @novasheikh, it looks like this game has a native linux build of Dosbox which is used by default and Proton is not involved. Issues with the native linux build should be reported to the game's dev(s). The request you're making here isn't directly handled by the Proton developers.

This issue tracker is intended for feedback with games run with the Proton compatibility layer, and not SteamOS in general. If you wnat to try running the game with Proton, then go to the per-game properties -> Compatibility -> check `Force the use of a specific Steam Play compatibility tool` and select a Proton version. If you're seeing issues with the game run with Proton, then please update this issue report with the new symptoms you're seeing, add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

I have to assume this feedback is for the Linux native variant of dosbox, which is out of scope for this issue tracker. Please give me a nudge if you chose to follow the previous paragraph and added the requested information.

**Comment by novasheikh** [comment]
I was directed to this github by the Valve tech support staff so I guess I was told the wrong thing. Honestly, this whole process is confusing. There should be someone at Valve with the game that can try opening it on a SteamDeck and see the problem on their end and fix it. I suspect there is an issue with the linux dosbox application that the SteamOS uses to run the game. I am not really familiar with Linux but do have experience with Windows and Dosbox.
