### ISSUE TITLE
Diakatana Works Fine Until Sub-Map Transition Near End of E1M1

### ISSUE THREAD

**Issue by PorcelainMouse** [ValveSoftware/Proton#5879]
# Compatibility Report
- Name of the game with compatibility issues: Diakatana
- Steam AppID of the game: https://steamdb.info/app/242980/

## System Information
- GPU: 6800XT
- Driver/LLVM version: MESA 21.3.8/Vulkan Inst Ver 1.3.204/LLVM 14.0.0
- Kernel version: 5.17.9
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/PorcelainMouse/f992faf831b49bb06a571487679aea1c
- Proton version: 6.3-8

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Game crashes on a *specific* sub-map transition.  At least, that's were I think it is crashing.  While working through the first map, I experienced five or so sub-map loadings/transitions, already, which worked fine, and those transitions still work. But the game crashes at a very specific point, when the player character walks over a specific point, which is very similar to the way the other map transitions were implemented; I'm assuming the crash occurs at such a point, although the loading screen doesn't appear before the crash.

While trying to provide requested logs, I ran a file integrity check, which turned up several corrupt files.  The second file integrity check passed and I tried the game again.  After this crash, file integrity check failed again and fixed itself.  Seems like the crash is unsafe and corrupts files.

## Reproduction
I am able to reproduce pretty reliably.

[steam-242980-2.log](https://github.com/ValveSoftware/Proton/files/8812454/steam-242980-2.log)

**Comment by Blisto91** [comment]
Hi there.

Does it behave the same on proton 7.0-2 & experimental?
If yes does it change anything if you launch the game with
```
PROTON_USE_WINED3D=1 %command%
```

**Comment by kisak-valve** [comment]
Hello @PorcelainMouse, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3678#issuecomment-1143505087.

**Comment by Blisto91** [comment]
Woops 😁
