### ISSUE TITLE
Persona 4 Golden video issues

### ISSUE THREAD

**Issue by Solljak** [ValveSoftware/Proton#5880]
# Compatibility Report
- Name of the game with compatibility issues: Persona 4 Golden
- Steam AppID of the game: 1113000

## System Information
- GPU:  Steam Deck
- Driver/LLVM version:  steam deck?
- Kernel version:  
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental Proton

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game. 
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 
I can't add the Proton log because I'm doing this on a phone, but the issue will be easily replicated as its a scene from the game. Its just far into the game so I don't think it's been tested. Games Deck Veriefied but this is the second in game event FMV that hasn't loaded when it was supposed to. I am concerned videos past a certain date haven't been tested to get that Deck Verified tick the game seems to have but clearly doesn't deserve. 
When a cutscene plays and a 2d animated video takes the form of the next scene, you get a black screen with a static tv bar at the top and the scene doesn't play out. It's happened on 2 scenes so far. One where the characters ride to the beach and the newest one when they perform their song at Junes. 

## Reproduction
You can reproduce this issue any time by visiting the games in game movie viewer under the 'TV listing' section of the main menu before loading up a save file or new game. If you do it from there, the game can even crash.
This game shouldn't be classed as Deck Verified as this seems to be happening more often.

**Comment by kisak-valve** [comment]
Hello @Solljak, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3982#issuecomment-1145868714.
