### ISSUE TITLE
Hardspace Shipbreaker (1161580)

### ISSUE THREAD

**Issue by maddoodles** [ValveSoftware/Proton#5883]
# Compatibility Report
- Name of the game with compatibility issues: Hardspace Shipbreaker
- Steam AppID of the game: 1161580

## System Information
- GPU: GTX 980 Ti
- Driver/LLVM version: 4.6.0 NVIDIA 510.73.05
- Kernel version: 5.17.5-76051705-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/maddoodles/d7f4ca34b5038ce0c363e827a0566b24
- Proton version: Experimental

## I confirm:
- [☑️] that I haven't found an existing compatibility report for this game.
- [☑️] that I have checked whether there are updates for my system available.

Proton Log:
[steam-1161580.log](https://github.com/ValveSoftware/Proton/files/8836261/steam-1161580.log)

## Symptoms 
- Cutscenes after the intro cutscene starting a new Career Mode game skip
- Online play (Leaderboards and RACE mode) is unplayable, cannot connect to servers.

## Reproduction
- Cutscenes: get to a point where a cutscene beyond the first plays (End of Act 3 or Epilogue)
- Online Play: try to connect view Leaderboards or current RACE ship.

**Comment by kisak-valve** [comment]
Hello @maddoodles, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4007#issuecomment-1146476871.
