### ISSUE TITLE
Noita doesn't start (881100)

### ISSUE THREAD

**Issue by arouene** [ValveSoftware/Proton#5889]
# Compatibility Report
- Name of the game with compatibility issues: Noita
- Steam AppID of the game: 881100

## System Information
- GPU: Radeon RX 6800 XT
- Driver/LLVM version: Mesa 21.1.8
- Kernel version: 5.17.11
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7.0-2

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

I have found an issue for Noita (#3176) but it's about performance.

[steam-881100.log](https://github.com/ValveSoftware/Proton/files/8845310/steam-881100.log)

## Symptoms 

Game doesn't start at all.
I tried various Proton options and various Proton versions (GE, experimental, 6.3) without a change. 

## Reproduction

1. Install Noita
2. Try to launch
3. Doesn't start

I have an AMD ThreadRipper, tried gamemode and multithreading disabled without amelioration.

**Comment by kisak-valve** [comment]
Hello @arouene, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3176#issuecomment-1147553203.
