### ISSUE TITLE
IL-2 Sturmovik: Battle of Stalingrad (307960) - D3D_Error - Failed to open texture

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#5893]
# Compatibility Report
- Name of the game with compatibility issues:  IL-2 Sturmovik: Battle of Stalingrad 
- Steam AppID of the game: 307960

## System Information
- GPU: EVGA 2080 Super FTW3, 8GB
- Driver/LLVM version: Nvidia 510.73.05
- Kernel version: Linux 5.15.41-1-MANJARO (x86_64)
- Link to full system information report as [Gist](https://gist.github.com/SquadFM/35039193ce7b6ff61bb706e653358fb6):
- Proton version: 7.0-2, Experimental (neither works)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
- game used to start flawlessly, however since the developer released update 4.705 the game does not start anymore on Linux computers
- when launching the game it displays a black screen and a pop-up that reads:

```
D3D_ERROR
Failed to open texture 'GRAPHICS\TEXTURES\DEFWHITE.BMP'
E_INVALIDARG (0x80070057)
```

## Reproduction
- install IL-2 Sturmovik: Battle of Stalingrad (307960)
- use Proton 7.0 or Experimental
- start the game and see that it does not work

## Reports in Forums
- https://steamcommunity.com/app/307960/discussions/0/3383905288031898897/
- https://steamcommunity.com/app/221410/discussions/8/3415430580678486888/

[steam-307960.log](https://github.com/ValveSoftware/Proton/files/8881617/steam-307960.log)

**Comment by kisak-valve** [comment]
Hello @SquadFM, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3106#issuecomment-1152661992.
