### ISSUE TITLE
Door Kickers 2 (1239080)

### ISSUE THREAD

**Issue by physixcat** [ValveSoftware/Proton#5894]
# Compatibility Report
- Name of the game with compatibility issues: Door Kickers 2
- Steam AppID of the game: 1239080

## System Information
- GPU: RX 6700 XT
- Driver/LLVM version: Mesa 22.0.5-1 and LLVM 1:14.0.4-4
- Kernel version: 5.17.0-3-amd64
- Link to full system information report as [Gist](https://gist.github.com/physixcat/e61d375f0a3ebaebc70ff0368f745f9f):
- Proton version: Proton Experimental (so newer than 7.0-2), have also tried older ones

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Proton Log:
[steam-1239080.log](https://github.com/ValveSoftware/Proton/files/8883214/steam-1239080.log)

## Symptoms
Since the SWAT update (v0.31), playing missions causes the game to slowly use more and more RAM (even when the game is paused to the menu or in the results screen). In ~20 minutes, it can go up to 2.6 GB of RAM of usage, and I've seen it run away up to 8 GB before I killed it. Previous to this update, it never seemed to ever go over 1 GB of RAM throughout long play sessions.

## Reproduction
1. Use any version of Proton, I'm using Experimental here (newer than 7.0-2, doesn't seem to matter though tried several, even the unofficial latest GE Proton release 7-20)
2. Start a program analogous to Task Manager (like bpytop or htop) that can track RAM usage of specific processes 
3. Start the game, run a mission (any will do, but for the purpose of standardizing let's go with Gate Crasher, the first non-tutorial ranger mission)
4. Complete the mission, then stay in the results (stars) screen for a couple minutes. The RAM usage continues to increase. For reference, a normal value here previous to SWAT update seemed to be ~850megs.

**Comment by Youshou-Rhea** [comment]
I can confirm this is happening with Proton 7.0-2.
Launched through Steam
It was about 1mb every 2-5 seconds.

Log File:
https://pastebin.com/Lq4CTkyh

**Comment by physixcat** [comment]
This issue has been resolved in the latest version of the game.
