### ISSUE TITLE
Use Python3.7

### ISSUE THREAD

**Issue by adds68** [ValveSoftware/Proton#59]
Hi,

This is awesome stuff from Valve :)

However what is the reason for Proton to depend on Python2.7?

There is less than [2 years](https://pythonclock.org/) left for updates and it is recommended to switch to python3 ASAP

**Comment by daniel-j** [comment]
https://github.com/ValveSoftware/Proton/pull/9

**Comment by kisak-valve** [comment]
Closing as a duplicate of #9.
