### ISSUE TITLE
Skyrim 

### ISSUE THREAD

**Issue by tmick2** [ValveSoftware/Proton#5901]
# Compatibility Report
- Name of the game with compatibility issues: Elderscrolls Skyrim
- Steam AppID of the game:72850

## System Information included in GIST link 
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/tmick2/25344715e76c927e0fee712a45981d1e
- Proton version:  7.02 and Experimental both fail 

## I confirm:
- [ Y] that I haven't found an existing compatibility report for this game.
- [Y ] that I have checked whether there are updates for my system available.

 done 

## Symptoms 
Game doesn't load, it will bring up menu, allow me to choose option but never get in the game. Mouse is choppy and video is slow

## Reproduction
run on Linux, seems to work fine in Windows 10

**Comment by kisak-valve** [comment]
Hello @tmick2, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #460, however, in your case it's straight forward.

Your Kaveri chipset is part of the Sea Islands (CIK) generation. By default the linux kernel uses the `radeon` kernel module by default with this generation and the `radeon` kernel module isn't compatible with Vulkan, so DXVK inside of Proton is trying to use lavapipe as a fallthrough attempt to render the game on the CPU. Please give https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games a read.

**Comment by tmick2** [comment]
Ummmm, I think your report is off? Well Steam's, It's integrated into
AMD A6-7400K Radeon R5 2C+4G (2) @ 4.075GHz which isn't part of
Kaverti. Two why should I have to modify GRUB to play one game? the
other Windows based games Borderlands 2 , Stellaris,  Witcher work
fine. I think I'll just quit using the game and find a better platform.

**Comment by kisak-valve** [comment]
A6-7400K, found in the Kaveri section of https://en.wikipedia.org/wiki/List_of_AMD_accelerated_processing_units#%22Kaveri%22_(2014)_&_%22Godavari%22_(2015) lining up with GCN2 / Sea Islands is accurate.

Borderlands 2, Stellaris, and I assume you're specifically referring to The Witcher 2 are all linux native with an OpenGL render path,

The chipset not supporting Vulkan by default is not a Proton issue.

**Comment by tmick2** [comment]
Just let you know, the setting you suggest in that KB broke my sound, I had no sound AT ALL after that change. Until I changed it to GRUB_CMDLINE_LINUX_DEFAULT="quiet amdgpu.cik_support=1 radeon.cik_support=1" I had no sound at all. The game doesn't launch but oh well, I'll spin up a VM of Windows and play it there, if at all. My system might be a one off or something but you might want to ensure your advice in that KB is relevant to Kernel 5.18 still.
