### ISSUE TITLE
Left 4 Dead 2 (550)

### ISSUE THREAD

**Issue by mdgsnb** [ValveSoftware/Proton#5904]
# Compatibility Report
- Name of the game with compatibility issues: Left 4 Dead 2, Counter-Strike Source
- Steam AppID of the game: 550, 240

## System Information
- GPU: RX 6800
- Driver/LLVM version: Mesa 22.1.1-2
- Kernel version: 5.18.3
- Link to full system information report as [Gist](https://gist.github.com/mdgsnb/ad769f3fae031ef99c7505d15b345166)
- Proton version: 7.0-2, Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-240.log](https://github.com/ValveSoftware/Proton/files/8896235/steam-240.log)
[steam-550.log](https://github.com/ValveSoftware/Proton/files/8896237/steam-550.log)

## Symptoms 
Any source engine game that uses VAC does not allow to join protected servers. The problem doesn't appear while using native build. 
Besides that, the fonts are barely visible and somewhat distorted on a 2K screen, changing the resolution does not change anything.

## Reproduction
Installing the games and launching them from Steam using Proton 7.0-2 or Experimental(using older versions like 6.3-8, 5.13-6, 5.0-10, 4.11-13, 4.2-9, 3.16-9 yield the same result; that should point to the problem's age and did not appear in recent builds) and joining any VAC-secured server(any official match in L4D2, any server in CSS).

**Comment by kisak-valve** [comment]
Hello @mdgsnb, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3831#issuecomment-1155132205. Counter-Strike: Source run with Proton is also being tracked at #5137.
