### ISSUE TITLE
Can't launch the game (Halo Infinite)

### ISSUE THREAD

**Issue by TheSiriuss** [ValveSoftware/Proton#5906]
# Compatibility Report
- Halo Infinite
- Steam AppID of the game:

## System Information
- GPU: RX 5700XT
- Driver/LLVM version: Mesa 22.1.1
- Kernel version: 5.17.14-1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental. 7.0 and 6.3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
I can't even open the game

**Comment by kisak-valve** [comment]
Hello @TheSiriuss, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5030#issuecomment-1155464115.
