### ISSUE TITLE
Secret of Mana (637670)

### ISSUE THREAD

**Issue by Nagakuro** [ValveSoftware/Proton#5909]
# Compatibility Report
- Name of the game with compatibility issues: Secret of Mana
- Steam AppID of the game: 637670

## System Information
- GPU: AMD Custom APU 0405/Steam Deck
- Driver/LLVM version: Mesa 22.0.0
- Kernel version: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a
- Proton version: both 7.0-3 and Proton Experimental as well as Proton 6.3-8 and all Proton GE 7 versions 7.1 to 7.20

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-637670.log](https://github.com/ValveSoftware/Proton/files/8904326/steam-637670.log)

## Symptoms: 
As of the latest Proton Experimental Update on June 14th 2022 the cutscenes in Secret of Mana appear black again now and skipping the cutscenes cause a crash, audio is fully functional, and subtitles display, but before this update literally just yesterday I was able to play it just fine on Proton Experimental, cutscenes were working fully and now they aren't. I tried seeing if the new implementations in 7.0-3 would work and nope, so now I have no way to enjoy the cutscenes in this game anymore. 

And on top of this, no other proton version has a working version with the cutscenes working anymore, sadly. I tried every Proton GE version, as well as all past versions of proton available for download Directly thru steam.

## Reproduction
Video issue:

1. Start a new game, pick language, pick text language, character name, press ok
2. Then the cutscene should start playing with a black screen, but will have audio and subtitles

Freeze:

1. proceeding to push the Start/Skip button for the cutscene, on the steam deck soft locks the game (game froze, and have to force exit) when trying to skip the cutscene.

![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/107516271/173702708-bddda4d3-459a-4391-8d10-c902642e7d1f.jpg)

**Comment by Nagakuro** [comment]
After further investigation, this issue was brought up 2 months ago, and the response given was 

"This is about EVR component:

1073.832:013c:0140:fixme:evr:video_presenter_control_GetCurrentImage 12EE003C, 0156FD3C, 0156FCBC, 0156FCA4, 0156FC9C.

The fix was pushed to experimental, please try to switch the game to "Proton Experimental" for retesting."

So it seems a regression in the update on June 14th 2022 of Proton Experimental and Proton 7.0-3 was made.

**Comment by kisak-valve** [comment]
Hello @Nagakuro, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5700#issuecomment-1155799179.
