### ISSUE TITLE
Tekken 7 no longer works with Proton 7.0-3

### ISSUE THREAD

**Issue by Doomguy1364** [ValveSoftware/Proton#5911]
Compatibility Report
- Name of the game with compatibility issues:Tekken 7

System Information
- GPU: <> GTX 3070
- Driver/LLVM version: <> 515.48.07
- Kernel version: <> 5.18.3

- Proton version: 7.0-3 and bleeding edge

I have checked whether there are updates for my system available.

Tekken 7 Hasn't worked on the bleeding edge version of proton for about a month, as of the 7.0-3 update to proton it no longer works, it used to work just fine on the 7.0-2 version.

**Comment by kisak-valve** [comment]
Hello @Doomguy136, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by kisak-valve** [comment]
Tekken 7 crash before main menu in proton 7.0-3 (works on previous versions)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5913.
@YoNoSoyVictor posted on 2022-06-15T13:28:20:

# Compatibility Report
- Name of the game with compatibility issues: Tekken 7
- Steam AppID of the game: 389730

## System Information
- GPU: AMD Radeon rx 6500 xt
- Driver/LLVM version:  Mesa 22.0.1. built-in kernel AMD drivers (more info in the full system info gist).
- Kernel version: 5.17.5-76051705-generic
- Link to full system information report as [Gist](https://gist.github.com/YoNoSoyVictor/30f6c6aca456821999b01fc4c188a5fd):
- Proton version: 7.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.


[steam-389730.log](https://github.com/ValveSoftware/Proton/files/8909673/steam-389730.log)

## Symptoms 
Launching the game works as expected. After the "Press any button" Screen the game crashes.

## Reproduction
Launch the game with the specified parameters, game will crash after the "Press any button" Screen.
Works fine in previous versions of proton (Specifically 6.3-8)

**Comment by ivyl** [comment]
Thanks for the reports. We are looking at the crash introduced in 7.0-3. In the meantime you can try setting the game's launch options to `PROTON_NO_FSYNC=1 %command%` which should work around the problem.

**Comment by Doomguy1364** [comment]
I apologize for not including this in my initial report, attached is the crash log if your team still needs it!
[steam-389730.log](https://github.com/ValveSoftware/Proton/files/8912666/steam-389730.log)
This is without the FSYNC being disabled which is currently an effective work around.

**Comment by alasky17** [comment]
@Doomguy136 We believe that this is fixed in current experimental.  Could you confirm if Tekken 7 is fixed with FSYNC using experimental-7.0-20220629?  If so I believe we can close this issue :)

**Comment by Doomguy1364** [comment]
@alasky17 The issue does seem to be fixed on the newest build of experimental, Thanks to you and your team for the great work!

**Comment by alasky17** [comment]
@Doomguy136 Thank you for testing!  I'm going to go ahead and close this issue.   Please comment on this issue and tag me and/or @kisak-valve  if 7.0-4 does not also fix the crash :)

**Comment by musamaanjum** [comment]
@alasky17 Tekken 7 is crashing again on proton-7.0-4 before I can see the main menu with Fsync on SteamOS v3.3.1. [steam-389730.log](https://github.com/ValveSoftware/Proton/files/9654476/steam-389730.log)

**Comment by kisak-valve** [comment]
Hello @musamaanjum, can you test how the game behaves with Proton Experimental and separately test Proton 7.0-4 with the game's launch options set to `PROTON_NO_FSYNC=1 %command%`?

Re-opening based on the matching backtrace in the log.

**Comment by musamaanjum** [comment]
@kisak-valve I'm sorry. I've just uninstalled it to make room for another game. It was working with `PROTON_NO_FSYNC=1 %command%` though.

**Comment by alasky17** [comment]
@musamaanjum Due to development reasons, we didn't end up including this in 7.0-4, so luckily this isn't a cause for alarm yet.  It *should* be in 7.0-5, but I will ping you after the release to confirm.  Thank you so much for following up! It is greatly appreciated :)

**Comment by AJuujarvi** [comment]
@musamaanjum The fix was included in Proton 7.0-5. You should be able to play the game now on a reinstall. :)

**Comment by Ilazki** [comment]
@kisak-valve @alasky17 I just wanted to mention that I'm still seeing Tekken 7 crash on launch with Proton Experimental unless fsync is disabled.  The game ran fine the first launch with the Steam Deck, but subsequent launches crash every time unless I add `PROTON_NO_FSYNC=1` to the launch options, so this still seems to be an issue.

Edit:  Okay, I just noticed that this isn't exactly accurate; Tekken 7 _does_ work correctly with Proton Experimental, but Steam's been ignoring my setting to run Experimental by default so the game was running with 7.0-4 despite Steam saying it was using Experimental.  To clarify, I have the Steam Deck's "Run other titles with:" option set to Proton Experimental, but it's been running games with 7.0-4 despite that and I didn't realise.  So, I was being misled into thinking it was using Experimental, which made me think this bug was back, but nope:  if I manually force Experimental it works, it's just that my Steam Deck has been lying to me about using it.

**Comment by alasky17** [comment]
@Ilazki @musamaanjum Proton 7.0-5 finally shipped and includes the fix for this.  Right now, it is only shipped on "Proton Next", but it should be on regular the regular Proton 7.0 branch soon :) Please let me know if you see the same failure again.
