### ISSUE TITLE
Tekken 7 crash before main menu in proton 7.0-3 (works on previous versions)

### ISSUE THREAD

**Issue by YoNoSoyVictor** [ValveSoftware/Proton#5913]
# Compatibility Report
- Name of the game with compatibility issues: Tekken 7
- Steam AppID of the game: 389730

## System Information
- GPU: AMD Radeon rx 6500 xt
- Driver/LLVM version:  Mesa 22.0.1. built-in kernel AMD drivers (more info in the full system info gist).
- Kernel version: 5.17.5-76051705-generic
- Link to full system information report as [Gist](https://gist.github.com/YoNoSoyVictor/30f6c6aca456821999b01fc4c188a5fd):
- Proton version: 7.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-389730.log](https://github.com/ValveSoftware/Proton/files/8909673/steam-389730.log)

## Symptoms 
Launching the game works as expected. After the "Press any button" Screen the game crashes.

## Reproduction
Launch the game with the specified parameters, game will crash after the "Press any button" Screen.
Works fine in previous versions of proton (Specifically 6.3-8)

**Comment by kisak-valve** [comment]
Hello @YoNoSoyVictor, this issue is already being tracked at #5911, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5911#issuecomment-1156518976.
