### ISSUE TITLE
DayZ w/Deerisle map not working

### ISSUE THREAD

**Issue by nzrf** [ValveSoftware/Proton#5914]
# Compatibility Report
- Name of the game with compatibility issues: DayZ
- Steam AppID of the game: 21100

## System Information

OS: Fedora Linux 35 (Thirty Five)
KERNEL: 5.17.13-200.fc35.x86_64
CPU: AMD Ryzen 9 3950X 16-Core
GPU: Mesa/X.org llvmpipe (LLVM 13.0.0, 256 bits)
GPU DRIVER: 4.5 Mesa 21.3.8
RAM: 32 GB

- GPU: 3090
- Driver/LLVM version: nvidia  515.48.07 / LLVM 13.0.0
- Kernel version: 5.17.13-200.fc35.x86_64
- Link to full system information report as [Gist] https://gist.github.com/nzrf/35a834b0db105f006be4240fa38eb6d1
- Proton version: 7.0-3, Multiple via steam console

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms Crashed:  While starting connecting to server screen flashes when trying to connect to server running deerisle mod only. I am able to use the mod for namalsk and other maps. Output attached. 

[steam-221100.log](https://github.com/ValveSoftware/Proton/files/8913304/steam-221100.log)

## Reproduction

1. install dayz via steam
2. either leave default or select forced compatibility select 7.0-3 or experimental 
3. run sudo sysctl -w vm.max_map_count=1048576
4. clone https://github.com/bastimeyer/dayz-linux-cli-launcher.git 
5. run connecting to server with mod e.g. ./dayz-launcher.sh -d -l -s 75.157.242.44 -p 27019
6. subscribe to mod when prompted e.g. Subscribe the mod here: https://steamcommunity.com/sharedfiles/filedetails/?id=1602372402
7. rerun launcher ./dayz-launcher.sh -d -l -s 75.157.242.44 -p 27019
8. get failure 

example of working mod
1. install dayz via steam
2. either leave default or select forced compatibility select 7.0-3 or experimental 
3. run sudo sysctl -w vm.max_map_count=1048576
4. clone https://github.com/bastimeyer/dayz-linux-cli-launcher.git 
5. run connecting to server with mod e.g. ./dayz-launcher.sh -d -l -s 75.157.242.44 
6. subscribe to mods when prompted e.g.  https://steamcommunity.com/sharedfiles/filedetails/?id=2289461232 and https://steamcommunity.com/sharedfiles/filedetails/?id=2289456201 
7. rerun launcher ./dayz-launcher.sh -d -l -s 75.157.242.44
10. start playing have fun :)

#EDIT Apologies. Correct file attached.

**Comment by kisak-valve** [comment]
Hello @nzrf, this issue report is incoherent.

The way I've read this issue report is that you're a Fedora user with a broken 32 bit OpenGL render path from missing NVIDIA userspace libraries, using a third party mod manager, and providing a Mass Effect Legendary Edition Proton log.

In general, we're using one issue report per unofficially supported game title, and DayZ is being tracked at #3899. Please re-evaluate the NVIDIA driver install on your system before adding your experience to the existing compatibility report.
