### ISSUE TITLE
Dishonored 2 (403640) 

### ISSUE THREAD

**Issue by giddyhup** [ValveSoftware/Proton#5917]
# Compatibility Report
- Name of the game with compatibility issues: Dishonored 2
- Steam AppID of the game: 403640

## System Information
- Steam Deck 512GB
- Proton version: proton-7.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam.log.zip](https://github.com/ValveSoftware/Proton/files/8926783/steam.log.zip)

## Symptoms 

No audio after resume from suspend on Steam Deck. Need to stop and restart game from Steam client to get it working again.

## Reproduction

Start game. Everything is fine and perfectly playable. Suspend game-play via Steam Deck power button. Wake up Steam Deck. Game comes up but without audio. Button/navigation audio keeps working in Steam menu.

Log attached.

**Comment by kisak-valve** [comment]
Hello @giddyhup, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/823#issuecomment-1158830726.

**Comment by giddyhup** [comment]
@kisak-valve , thanks for the transfer. I thought I had searched, apparently not. Sorry.
