### ISSUE TITLE
Slayers X Demo (2001540)

### ISSUE THREAD

**Issue by DaVince** [ValveSoftware/Proton#5918]
**Which game:**
The demo of this game: https://store.steampowered.com/app/1931020/Slayers_X_Terminal_Aftermath_Vengance_of_the_Slayer/

**The issue:**
Nothing happens when clicking the "Wishlist now... Or else" button in the corner of the title screen.

**What is supposed to happen:**
It's supposed to take me to the game page on either Steam or the browser.

**Details:**
Tested on Steam Deck, running the beta channel and Proton Experimental.

When I run Steam from the terminal, a line appears in the terminal for each time I click the button:
```
ThreadGetProcessExitCode: no such process 412406
ThreadGetProcessExitCode: no such process 412431
ThreadGetProcessExitCode: no such process 412415
ThreadGetProcessExitCode: no such process 412424
ThreadGetProcessExitCode: no such process 412412
ThreadGetProcessExitCode: no such process 412410
```

I'm half sure that this isn't just specific to this game, but something about the specific way some games might try to open a URL or Steam page.

**Comment by kisak-valve** [comment]
Hello @DaVince, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the issue, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by DaVince** [comment]
Alright. Here's the log:
[steam-2001540.tar.gz](https://github.com/ValveSoftware/Proton/files/8929370/steam-2001540.tar.gz)

I clicked the non-functional button about seven times or so.

System information: https://gist.github.com/DaVince/919ea11bf9d01199b48242c50d7f32a2

**Comment by alasky17** [comment]
@DaVince Could you try this again?  This button opened up the Steam store page for me today with current experimental on the deck.

**Comment by DaVince** [comment]
> @DaVince Could you try this again? This button opened up the Steam store page for me today with current experimental on the deck.

I can confirm that it works now!
