### ISSUE TITLE
video rendering only works with WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER=1

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [ValveSoftware/Proton#5920]
# Feature Request
I tested this feature using wine staging 7.11 and proton experimental
when I was testing the newly released version of PC building sim 2, I then ran the time spy benchmark in "free roam" mode, and saw that the video rendering was extremely broken (at least it was playing something lmao) meanwhile the output on wine staging 7.11 looks perfect. 

proton experimental:
![image](https://user-images.githubusercontent.com/45927311/174450321-9e776ebf-6769-475d-9e1f-b92b58c24b9f.png)

there were lots of video stuttering problems as well (similar artifacts can be seen in aimlab)

wine staging 7.11: 
![image](https://user-images.githubusercontent.com/45927311/174450625-e980da1c-66aa-466c-862a-9692382cb0f6.png)

edit: stuttering problems present in wine staging too (only in the port royale 3d mark test though)

**Comment by Etaash-mathamsetty** [comment]
WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER=1 is a workaround

**Comment by Blisto91** [comment]
For the video stuttering see if launching without fsync & esync helps.
```
PROTON_NO_FSYNC=1 PROTON_NO_ESYNC=1 %command%
```

**Comment by aeikum** [comment]
Yesterday's Proton Experimental release should fix the yellow/green/purple corrupt video issue. Can you retry?

**Comment by Etaash-mathamsetty** [comment]
seems like the beta period for the game ended lmao
what game should I test
I'll try PC building sim 1 then
edit: video playback only works with proton-ge in the first game, so I guess that's a dead end
let me try aimlab then
edit: aim lab won't even run, proton is crashing internally somewhere when trying to run aimlab, using PROTON_LOG=1 nothing is printed

**Comment by Etaash-mathamsetty** [comment]
ok so in aimlab, some videos look like this
![image](https://user-images.githubusercontent.com/45927311/175573378-ec5e84a3-b409-4eda-ac06-96519fcce36f.png)
while others look like this
![image](https://user-images.githubusercontent.com/45927311/175573473-d72bcf6b-ec51-4532-ba90-30e9ab1bdd0f.png)

I am pretty sure the ones that are broken in proton experimental work fine on GE (all though GE hasn't been updated and will have the corruption issue)

**Comment by Etaash-mathamsetty** [comment]
according to GloriousEggroll, the commits made on 6/24 completely break video playback

**Comment by kisak-valve** [comment]
Closing as fixed.

**Comment by GloriousEggroll** [comment]
> according to GloriousEggroll, the commits made on 6/24 completely break video playback

Just for clarification, that was already fixed, and WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER=1 is not related to those commits. WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER is only for videos that play but come out looking like the very first image in this tracker. This should not be confused with the blank media (color bars) -- color bars happen when there is no codec available to play the video, as opposed to video corruption.

**Comment by Etaash-mathamsetty** [comment]
> > according to GloriousEggroll, the commits made on 6/24 completely break video playback
> 
> Just for clarification, that was already fixed, and WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER=1 is not related to those commits. WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER is only for videos that play but come out looking like the very first image in this tracker. This should not be confused with the blank media (color bars) -- color bars happen when there is no codec available to play the video, as opposed to video corruption.

thanks for the clarification, i thought the commits that caused the color bar issue were related to the ones that fixed this

**Comment by Milor123** [comment]
@GloriousEggroll I have similar problem here bro, https://github.com/ValveSoftware/Proton/issues/7595#issuecomment-2512853255 but it `WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER=1` dont help, someone ENV for help to this?
