### ISSUE TITLE
DEATHLOOP (1252330)

### ISSUE THREAD

**Issue by Voltansky** [ValveSoftware/Proton#5928]
# Compatibility Report
- Name of the game with compatibility issues: DEATHLOOP
- Steam AppID of the game: 1252330

## System Information
- Hardware: Steamdeck 512 GB
- Proton version: 7.0-3 / Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @Voltansky, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5156#issuecomment-1164996214.
