### ISSUE TITLE
Apparent incompatibility with lib32-amdvlk

### ISSUE THREAD

**Issue by IlabSentuser** [ValveSoftware/Proton#5929]
# Compatibility Report
- Name of the game with compatibility issues: Planetside 2, Deep Rock Galactic
- Steam AppID of the game: 218230, 548430

## System Information
- GPU: nvidia GeForce GTX 1650
- Driver/LLVM version: nvidia 515.48.07-1
- Kernel version: 5.18.5-arch1-1 (Arch Linux)
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/IlabSentuser/a8fd79a0b999e0576f80ee62b020cdec
- Proton version: Several of them including: 7.0.3, 6.3.8, Proton Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
When opening certain games the game start fails. By doing some testing I have found it to be an incompatibility (or something similar) with lib32-amdvlk (2022.Q2.3-1), if that library is installed on the system the mentioned games fail to start, in the particular case of Deep Rock Galactic it shows an error (attached as screenshot). I know for sure that this library was installed before in its version (2022.Q2.2-1) and the mentioned games showed no errors. After upgrading it yesterday the problems with games running proton started to appear. That is why I had suspicions on that library, after removing this single library errors disappear immediately. The 64 bits version of the library does not affect the games as per my testing, yet the 32 bits is needed for some other apps in my system.

## Reproduction
1- Start an affected game (In my case it always fails with Planetside 2 and Deep Rock Galactic)
2- The game fails to start.
Gist: https://gist.github.com/IlabSentuser/a8fd79a0b999e0576f80ee62b020cdec

![Screenshot_20220623_220337](https://user-images.githubusercontent.com/71553739/175427804-aaa12b6a-0a40-4b9a-9347-d400ed1b7c56.png)
[deep_rock_galactic_steam-548430.log](https://github.com/ValveSoftware/Proton/files/8971827/deep_rock_galactic_steam-548430.log)
[planetside_2_steam-218230.log](https://github.com/ValveSoftware/Proton/files/8971828/planetside_2_steam-218230.log)

**Comment by kisak-valve** [comment]
Hello @IlabSentuser, AMDVLK breaking other video drivers is not a Proton bug. This particular failure is https://github.com/GPUOpen-Drivers/AMDVLK/issues/278.
