### ISSUE TITLE
POLYGON causing a gpu reset on RADV (new publictest beta with UE5)

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [ValveSoftware/Proton#5930]
proton version: proton experimental bleeding edge
here's how the issue works, so look into the sky, then look down and **BAM** the GPU will reset. I am using mesa 22.1.2 on a ryzen 7 4700u with its integrated graphics

**Comment by kisak-valve** [comment]
Hello @Etaash-mathamsetty, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5399#issuecomment-1165943476, but really, GPU resets should be reported to your video driver vendor.
