### ISSUE TITLE
Doom (2016) (379720) crashes at start with Intel HD 530

### ISSUE THREAD

**Issue by kbasaran** [ValveSoftware/Proton#5932]
# Compatibility Report
- Name of the game with compatibility issues: Doom
- Steam AppID of the game: 379720

## System Information
- GPU: Intel HD 530
- Driver/LLVM version: Intel Mesa Intel(R) HD Graphics 530 (SKL GT2), 4.6 (Compatibility Profile) Mesa 22.0.1
- Kernel version: 5.15.0-40-generic
- Link to full system information report as [Gist]: https://gist.github.com/kbasaran/8ea8b8c045b0836fa9c70d06091d96e0
- Proton version: Proton experimental (Steam is up-to-date. I had the same behavior with Proton 7.0.3 selected.)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-379720.log](https://github.com/ValveSoftware/Proton/files/8984285/steam-379720.log)

## Symptoms 
- Game does not start at all.
- Launch option "+r_renderapi 1" did not make a difference.
- I did not find a log file in either of these folders:
  - /steamapps/common/DOOM/base/
  - steamapps/compatdata/379720/pfx/drive_c/users/steamuser/Saved Games/id Software/DOOM/base/

**Comment by kisak-valve** [comment]
Hello @kbasaran, a header only Proton log hints that something went wrong early in Proton's startup, before the actual game is started. Can you completely close Steam, then run `steam` from a terminal and check the terminal spew for any hints around the time you tell the game to start?

Also, what filesystem are you using with `/media/kerem/HDD500/Steam`?

**Comment by kbasaran** [comment]
Hello kisak and thank you for the response.

There is this error:
```
Traceback (most recent call last):
  File "/home/kerem/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 1461, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/kerem/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 1263, in init_session
    g_compatdata.setup_prefix()
  File "/home/kerem/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 790, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
OSError: [Errno 22] Invalid argument: '../drive_c' -> '/media/kerem/HDD500/Steam/steamapps/compatdata/379720/pfx//dosdevices/c:'
Game process removed: AppID 379720 "/home/kerem/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=379720 -- '/home/kerem/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kerem/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/media/kerem/HDD500/Steam/steamapps/common/DOOM/DOOMx64.exe'", ProcID 35583
```
The HDD500 media is formatted with NTFS. It is an external drive connected to an hot-swappable SATA port.

**Comment by kisak-valve** [comment]
Proton interacting with NTFS is known to be finicky, and the general recommendation is to use a linux native filesystem instead.

This particular failure case `OSError: [Errno 22] Invalid argument: '../drive_c' -> '/media/kerem/HDD500/Steam/steamapps/compatdata/379720/pfx//dosdevices/c:'` is already being tracked at #5168.

If you really need to use NTFS with that Steam library and Proton, then give https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows a read.

Closing in favor of #5168.
