### ISSUE TITLE
Problem launching windows game on ntfs drive

### ISSUE THREAD

**Issue by Ludo-code** [ValveSoftware/Proton#5935]
Proton: 1655841837 experimental-7.0-20220621

I have tried to launch a game on my secondary drive (windows installed) and game doesn't launch and log print this : 

======================
Proton: 1655841837 experimental-7.0-20220621
SteamGameId: 24840
Command: ['/media/ludovic/F80AE5800AE53C6E/SteamLibrary/steamapps/common/Medal of Honor Airborne/UnrealEngine3/Binaries/MOHA.exe']
Options: {'forcelgadd'}
depot: 0.20220509.53
pressure-vessel: 0.20220420.0
scripts: v0.20220311.0-0-gae4cbed
soldier: 0.20220509.0 soldier 0.20220509.0
Kernel: Linux 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64
======================

Have you an idea to fix it ?

**Comment by kisak-valve** [comment]
Hello @Ludo-code, Proton interacting with NTFS is known to be finicky, and the general recommendation is to use a linux native filesystem with Proton.

There are [several issue reports](https://github.com/ValveSoftware/Proton/search?q=ntfs&type=issues) already tracking this issue and opening another one isn't particularly beneficial.

That said, you may be lucky with one of the workarounds at https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows.
