### ISSUE TITLE
Monster Hunter Rise Freezes Computer

### ISSUE THREAD

**Issue by Polifack** [ValveSoftware/Proton#5936]
# Compatibility Report
- Name of the game with compatibility issues: MONSTER HUNTER RISE
- Steam AppID of the game: 1446780

## System Information
- GPU: Intel TigerLake-LP GT2 [Iris Xe]
- Driver/LLVM version: Mesa 22.1.2
- Kernel version: 5.18.6-arch1-1 
- Link to full system information report as [Gist](https://gist.github.com/): [GIST](https://gist.github.com/Polifack/5706eb357a38e0b635d6aa6ed68f1069)
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1446780.log](https://github.com/ValveSoftware/Proton/files/8986282/steam-1446780.log)

## Symptoms 

When reaching the FMV during the boot of Monster Hunter Rise whole computer freezes (but still playing FMV sounds) and a hard reboot is needed. Confirmed that the game runs ok on Windows.

## Reproduction

Launch Monster Hunter Rise

**Comment by kisak-valve** [comment]
Hello @Polifack, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5495#issuecomment-1166520223.
