### ISSUE TITLE
Dark Souls remastered directx11 error

### ISSUE THREAD

**Issue by swaipyy** [ValveSoftware/Proton#5946]
# Compatibility Report
- Name of the game with compatibility issues: Dark Souls remastered 
- Steam AppID of the game: 570940

## System Information
- GPU: RX 560 
- Driver/LLVM version:  4.6 (Compatibility Profile) Mesa 22.1.2 LLVM 13.0.1
- Kernel version: 5.18.6-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/swaipyy/31982100dadc7a864da1de41d3520c9e
- Proton version: Experimental

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

## Symptoms 
Every time i open any game that runs under directx11 it pop up an error message realted to that, for example in DSR the message say: "The system does not meet the minimum DirectX11 / Shader Model 5.0 GPU requierement to run the application"

## Reproduction
open a game that runs under directx11

## Aditional notes
this happen with every game that runs under directx11 for example in Carx Drifting Racing Online say like the mentioned of DSR.
LOG of DSR: https://gist.github.com/swaipyy/e55e0d907a75903bcab6ccf77f894d94

**Comment by kisak-valve** [comment]
Hello @swaipyy, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #1026, but in your case it's a straight forward issue.

AMDVLK has broken Vulkan in general on your system (https://gist.github.com/swaipyy/31982100dadc7a864da1de41d3520c9e#file-hardware-information-L242-L255 and https://gist.github.com/swaipyy/31982100dadc7a864da1de41d3520c9e#file-hardware-information-L453-L466) from https://github.com/GPUOpen-Drivers/AMDVLK/issues/278. This is not a Proton bug.
