### ISSUE TITLE
Just Cause 3 (225540)

### ISSUE THREAD

**Issue by 5zymon** [ValveSoftware/Proton#5947]
# Compatibility Report
- Name of the game with compatibility issues: Just Cause 3 
- Steam AppID of the game: 225540

## System Information
- Steam Deck, newest Stable firmware
- Proton version: 7.0-3 / Proton GE / Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-225540.log](https://github.com/ValveSoftware/Proton/files/9008088/steam-225540.log)

## Symptoms 

I am not sure if this is actually proton update issue but game run perfectly fine on 7.0-2. I've noticed that proton was recently updated on steam deck to 7.0-3. I also tried other Proton versions. Right now game tries to start, but shuts down seconds after initialization ( you do not see anything from the game actually, just a black screen). I've noticed Iron Harvest(826630) having same issues, and it was also working fine before. I cannot figure out anything from the logs unfortunately. I've removed proton prefix, I've verified local files in steam, but this didn't change anything, same behaviour.

**Comment by kisak-valve** [comment]
Hello @5zymon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/682#issuecomment-1169969426.
