### ISSUE TITLE
game "bombix" not starting

### ISSUE THREAD

**Issue by gmankab** [ValveSoftware/Proton#5948]
https://store.steampowered.com/app/662830/Bombix
game closes right after starting

proton versions tested: `7.0-3` and `experimental`

```
hardware:
- Motherboard: Intel Corporation DX58OG
  - uefi
  - 6x DDR 3 RAM slots
  - 6 x SATA 2
  - 2 x SATA 3
  - 2 x pci-express 16x
  - 3 x pci-express 1x
  - 1 x pci
- CPU: Intel(R) Core(TM) i7 CPU 920 @ 2.67GHz, 8 cores
- GPU: NVIDIA GeForce GT 730, 2 GB
  - GPU driver: nvidia 390.151 (latest available on this gpu)
- Display: DELL S2340T @60 (1920 x 1080)
- RAM: 12 GB (3 x 4GB DDR 3 Kingston 1600 MHz)
- storage:
  - 64 GB sata SSD SPCC 200 MB/sec
  - 128 GB m2 SSD NVMe Netac connected to pci-e 1200 MB/sec
  ```
  
I tried to install ubuntu on 64 GB SSD and arch on 128 GB SSD, same result

**Comment by kisak-valve** [comment]
Hello @gmankab, the NVIDIA 390 series video driver is older than the support cutoff for Proton and causing you to encounter https://github.com/ValveSoftware/steam-runtime/issues/420.

There are 3 variants of the NVIDIA GT 730 video card, two of those variants are Kepler generation, one is Fermi generation. You should be able to run `lspci | grep VGA` in a terminal and if the info there includes something like `NVIDIA Corporation GK208` (K in the chipset means Kepler), then you could try using the NVIDIA 470 series video driver, which is the last driver series to support the Kepler generation. If you get something like `NVIDIA Corporation GF108` (F in the chipset means Fermi), then the 390 series video driver is the last series video driver for your card.

The Vulkan driver implementation in the 390 series is ancient and can't be supported.

**Comment by gmankab** [comment]
i'm getting `GF108`

okay, i understand
