### ISSUE TITLE
world of warships (steam) unhandled exception, access violation

### ISSUE THREAD

**Issue by Demonslayer2011** [ValveSoftware/Proton#595]
usually happens in game, when lots of things are going on at once. causes a fatal crash, sometimes freezes and has to be force closed, sometimes just crashes and exits.
system
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
hardware: ryzen 1600x, asus crosshair VI hero rev 1 firmware ver. 1201
8gbx4 DIMM DDR4 Synchronous Unbuffered (corsair vengeance) 2133 MHz (0.5 ns)
dual boot windows 10. both ubuntu and windows run on their own 1tb hdd, and share a third ntfs formatted drive.

have at time of post, newest steam update, the one that rolled out today.

here is the crash and dump files.

[WorldOfWarships-2018-08-25_13-38-43.crash.txt](https://github.com/ValveSoftware/Proton/files/2321067/WorldOfWarships-2018-08-25_13-38-43.crash.txt)
[WorldOfWarships-2018-08-25_13-38-43.dmp.txt](https://github.com/ValveSoftware/Proton/files/2321068/WorldOfWarships-2018-08-25_13-38-43.dmp.txt)

if more info is needed please let me know.

**Comment by kisak-valve** [comment]
Hello @Demonslayer2011, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue to https://github.com/ValveSoftware/Proton/issues/333#issuecomment-416005313.
