### ISSUE TITLE
All games trough proton fail

### ISSUE THREAD

**Issue by Lunatik00** [ValveSoftware/Proton#5953]
## System Information
- GPU: RX580
- Distro: Arch
- Proton version: all

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Can't launch most games using proton

## Reproduction

After an update something broke, it says "DX11 feature 10.0 is required to run the engine"  in multiple games, as of today, july 1st 2022 this persists, as of june 15th 2022 the error was not there, it has been there since june 20th or a few days after, i downgraded my system to the 15th to be able to play, i don't think the error is directly due to steam, since i can play using the old version, there was an AMD driver update and i think that is one the source of the problems, regardless to what is the source, for most users this would be a Steam issue, so, to reproduce this use Arch in the current day with AMD hardware (i don't know if it happens on intel and nvidia) and run something like Soulcalibur 6 or Tekken 7, both show the same error, and other games trough proton crash without showing an exact error, rocksmith, sekiro, megaman zero or another error message 30xx, the point is that there is no proton compatibility in any game that i tried as of today, yet the same games worked perfectly a few days ago, and if i downgrade they still work

Edit: it happens in all proton versions that i tested, including 6, 7, experimental, GE 6, 7-10 and 7-24

**Comment by kisak-valve** [comment]
Hello @Lunatik00, you've described https://github.com/GPUOpen-Drivers/AMDVLK/issues/278, which is not a Proton bug.

If AMDVLK is not installed on your system, then please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Closing as not-our-bug.

**Comment by Lunatik00** [comment]
Well, uninstalling amdvlk and lib32-amdvlk as said in the other issue worked, yet i still think is a bug related to steam, it might be something that broke a library call, the most important part in my opinion would be the user perception, how there needs to be at the very least a workaround for this bug to not be presented to the final user in steam, what a regular user will see is that they can't play games in steam using proton, thus degrading the brand perception for them and the people they know, i get is not a bug directly related to proton, but i think it can be solved in steam.

**Comment by Lunatik00** [comment]
A simple answer for people that find this: 

Try uninstalling amdvlk and lib32-amdvlk
