### ISSUE TITLE
Warframe launcher black screen

### ISSUE THREAD

**Issue by RSerejo** [ValveSoftware/Proton#5957]
Warframe launcher is broken with last proton version.
![image](https://user-images.githubusercontent.com/43152685/177005936-aa861d8d-9b37-4a46-ac33-861bf5526c2d.png)

**Comment by kisak-valve** [comment]
Hello @RSerejo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/167#issuecomment-1172921014.

**Comment by GloriousEggroll** [comment]
try disabling hardware acceleration in the launcher then close + reopen
