### ISSUE TITLE
I Am Fish (1472560)

### ISSUE THREAD

**Issue by o-kotb** [ValveSoftware/Proton#5959]
# Compatibility Report
- Name of the game with compatibility issues: I Am Fish
- Steam AppID of the game: 1472560

## System Information
- GPU:  RTX 2070
- Driver/LLVM version:  4.6.0 NVIDIA 510.68.02
- Kernel version:  5.18.7-200.fc36.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/o-kotb/96b486921c0b757cb0edaf061db9785e
- Proton version: Proton experimental-7.0-20220629

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 proton log
[steam-1472560.log](https://github.com/ValveSoftware/Proton/files/9033766/steam-1472560.log)

## Symptoms 
Weird artifacts and black boxes appear frequently around the game, and really bad performance.

## Reproduction
Use an nvidia gpu and play the game. According to protondb, AMD seems to be unaffected; hence the steam deck verification.

![Screenshot_20220702_233240](https://user-images.githubusercontent.com/72304125/177017118-06d5f156-763a-409d-85ad-c3c1f998da4e.png)

**Comment by Blisto91** [comment]
I am a bit unsure which directx version this game runs on but can you launch with this and see how it behaves then?

```
PROTON_USE_WINED3D=1 %command%
```

Another interesting thing if you are able would be to try and update your graphics drivers.

**Comment by o-kotb** [comment]
I'm not sure which directx version the game uses. Is there a command that prints this info?

Launching the game with PROTON_USE_WINED3D=1 makes the game have different, but just as bad, artifacts. It also makes the game overall very dark, as if it was horror game.
![Screenshot_20220704_224507](https://user-images.githubusercontent.com/72304125/177215140-aa3b9fbd-7e51-4830-b566-a943bffadc32.png)

I also should've mentioned this, but the performance is really bad given my hardware (at least with nvidia). I get better FPS and consistency with wined3d on highest settings than with DXVK on lowest settings. I thought it were shaders compiling, but it persisted on the same level and many restarts of the game.

I'm already on the latest nvidia drivers provided by my distribution. Although, I just updated to linux  "kernel-5.18.9-200.fc36.x86_64.rpm" but the issues still persist.

**Comment by erikjwaxx** [comment]
> I am a bit unsure which directx version this game runs on

@Blisto91 I'm assuming that, since launching with `PROTON_NO_D3D11` immediately crashes the game with a dialog indicating a failure to initialize graphics and to ensure DirectX 11 is installed, that it uses DX11? :)

![image](https://user-images.githubusercontent.com/2265605/177430898-915e1be2-e1a6-4dff-b5e7-8468da34089c.png)

**Comment by o-kotb** [comment]
> Another interesting thing if you are able would be to try and update your graphics drivers.

The nvidia 515.57 driver came to Fedora RPM Fusion today, and I promptly installed it. All the issues are still present.

I too couldn't launch the game with `PROTON_NO_D3D11=1`

**Comment by JMans15** [comment]
Same problem here on arch with driver version 535.54.03, on a laptop with nvidia dedicated GPU and a AMD integrated GPU
I can confirm that the problem is not present using the amd GPU (but I get 20 fps instead of 300)
It successfully launches with both PROTON_USE_WINED3D=1 and PROTON_NO_D3D11=1 but it doesn't change anything (lutris-GE-Proton8-9)

**Comment by tuananh** [comment]
any luck with driver v550? Just want to ask before I purchase the game.

**Comment by Inglebard** [comment]
> any luck with driver v550? Just want to ask before I purchase the game.

unfortunately, no.

Tested on 550.67 with GTX1060 and EG-Pronton-9-4.

Something change for me with wine 9.3, but still not playable.

**Comment by o-kotb** [comment]
You can always just buy the game to try and see if it works and refund it if it doesn't as long as it's within 2 weeks and playtime doesn't exceed 2 hours.

On April 17, 2024 12:13:02 PM GMT+02:00, Tuan Anh Tran ***@***.***> wrote:
>any luck with driver v550? Just want to ask before I purchase the game.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ValveSoftware/Proton/issues/5959#issuecomment-2060910069
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Omar Kotb

**Comment by Inglebard** [comment]
All is good now with nvidia 550.107.02.

**Comment by o-kotb** [comment]
> All is good now with nvidia 550.107.02.

Yes, looks like the latest driver fixed the issue. I think the latest one is 555.58.02 now, though.
