### ISSUE TITLE
Optimize the C and C++ with OpenACC

### ISSUE THREAD

**Issue by enigma101** [ValveSoftware/Proton#5969]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description  
I would like people to add labels to the source code that accelerate the code on GPU where it makes sense to speed up things with OpenACC API Technology.  This Technology works with GCC.  I hear speedups of 2x - 100x are expected.  

## Justification [optional] 
 I hear speedups of 2x - 100x are expected.  

## Risks [optional]
It might slow things down if done the wrong way.

## References [optional] 
https://www.openacc.org/
https://en.wikipedia.org/wiki/OpenACC#:~:text=OpenARC%20is%20an%20open%20source,Laguna%20(C%20language%20only).
https://www.youtube.com/c/OpenaccOrg

**Comment by kisak-valve** [comment]
Hello @enigma101, for this request to be viable, someone would need to have a working prototype explaining exactly how and where this would benefit Proton and/or wine.

A broad request to re-invent the wheel using a different language that the majority of devs are unfamiliar with impractical.
