### ISSUE TITLE
UI element from one game showing up in a completely different game

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/Proton#5970]
Back 4 Blood (924970) #5206
World of Warships (552990) #333
Proton Version: 6.3-8

I'm seeing a skill icon/image/texture/something from World of Warships inside the UI of Back4Blood. It appears in the upper left corner. This seems to happen intermittently, and I'm not sure what causes it. But I haven't even played World of Warships recently. It has been weeks or months since playing World of Warships, and the image still shows up every once in a while and persists in Back4Blood the entire game.

### 30 May 2022
![Screenshot_2022-05-30_10-44-53](https://user-images.githubusercontent.com/6024315/177368467-56edcc1c-5408-4b6e-9687-8e3bc7eb5c91.png)
![Screenshot_2022-05-30_10-31-08](https://user-images.githubusercontent.com/6024315/177368471-9478e651-2f1a-4403-9ac0-efaf428da7c9.png)
![Screenshot_2022-05-30_10-18-50](https://user-images.githubusercontent.com/6024315/177368474-e7b8ca0d-fcaf-4fab-9864-78890c16dc7e.png)

### 4 July 2022
![Screenshot_2022-07-04_21-22-25](https://user-images.githubusercontent.com/6024315/177368518-74ea7f83-1553-4bf6-a632-336123b3fc43.png)
![Screenshot_2022-07-04_21-22-11](https://user-images.githubusercontent.com/6024315/177368524-08afc33a-6505-49da-b12a-0d1a4839c24f.png)
![Screenshot_2022-07-04_21-21-47](https://user-images.githubusercontent.com/6024315/177368529-f4143d2d-88cf-4c0a-a547-148d2e763e47.png)

**Comment by CSahajdacny** [comment]
That happened to me on a Windows 10 machine, playing the game on PC GAMEPASS, so is not a PROTON or Steam issue.

**Comment by nightsky30** [comment]
> That happened to me on a Windows 10 machine, playing the game on PC GAMEPASS, so is not a PROTON or Steam issue.

That is very interesting. Thanks for the info. Maybe a driver issue? For reference:
```
Video Card:
    Driver:  NVIDIA Corporation NVIDIA GeForce GTX 1070/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 510.73.05
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1b81
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 2560 x 1440
    Primary Display Size: 23.62" x 13.39" (27.13" diag)
                                            60.0cm x 34.0cm (68.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 8192 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
```

**Comment by kisak-valve** [comment]
Hello @nightsky30, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5206#issuecomment-1175250499.
