### ISSUE TITLE
[Feature Request] Have Steam install games under a Steam Linux group and give each Linux user their own steamapps/compatdata/ directory.

### ISSUE THREAD

**Issue by saucepan14** [ValveSoftware/Proton#5971]
My wife and I share a computer for games and we have two separate Linux and Steam accounts. We have family sharing enabled for our games and games that are Linux native can be run by either of us no matter which user downloaded the games. However for games that run through proton if user A installs a game on a shared drive and user B tries to run it they will get a disk write error. This can be alleviated by manually changing ownership permissions to a common group with read, write, execute. Even after changing group ownership permissions when launching a game it will not start, I have narrowed this down to the ownership in steamapps/compatdata/[gameid]. When changing the owner the directory and the files inside the game will run just fine. However changing the group ownership does not fix the issue. And when changing the owner of the directory and files it breaks the game for the other user.

I am requesting a feature that changes the group ownership of installed games to a steam group such as "steamusers" with rwx. To allow any Linux user in the group to download updates for the game. Additionally I would like for each Linux user to have their own steamapps/compatdata/ directory where the wine prefixes will be stored for each user. 
I do not see the duplicate data becoming an issue as the directory uses very little disk space and is better solution than the current work around which is to install games in separate directories for each user.

**Comment by kisak-valve** [comment]
Hello @saucepan14, this issue is already being tracked at #4820 / https://github.com/ValveSoftware/steam-for-linux/issues/7793. Closing as a duplicate.
