### ISSUE TITLE
All games using DirectX recently broke for me.

### ISSUE THREAD

**Issue by radirgy** [ValveSoftware/Proton#5973]
## System Information
- GPU: AMD Radeon RX 6700 XT
- Driver/LLVM version: Mesa 22.1.3, llvm 14.0.6
- Kernel version: 5.18.9-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/liquidtown/360a16a5bd8ddd2571bd3cf193d4762a
- Proton version: Experimental, 7.0, 6.3, 5.13, 5.0, 4.11, 4.2, 3.16, 3.7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Every game I have tried with Proton so far has instantly crashed with either an error message stating that I don't have proper DirectX drivers, or no error message at all.
For example, Maximum Action will give me this error:
"Failed to initialize graphics.
Make sure you have DirectX 11 installed, have up to date
drivers for your graphics card and have not disabled
3D acceleration in display settings.
InitializeEngineGraphics failed"
and Borderlands 2 will just crash without giving me an error.

## Reproduction
Launch any game with Proton.

**Comment by kisak-valve** [comment]
Hello @liquidtown, Vulkan is broken in general on your system (https://gist.github.com/liquidtown/360a16a5bd8ddd2571bd3cf193d4762a#file-gistfile1-txt-L277-L290 and https://gist.github.com/liquidtown/360a16a5bd8ddd2571bd3cf193d4762a#file-gistfile1-txt-L425-L438) due to https://github.com/GPUOpen-Drivers/AMDVLK/issues/278. This is not a Proton bug.

**Comment by bkosowski** [comment]
@liquidtown You may want to try something that worked for my on Manjaro: https://github.com/ValveSoftware/Proton/issues/3189#issuecomment-1177829820
