### ISSUE TITLE
eso not launching

### ISSUE THREAD

**Issue by mihstaz** [ValveSoftware/Proton#5979]
nothing happens when I click play in the launcher. syslog says 

Jul 10 19:25:39 steam.desktop[10503]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Jul 10 19:25:40 steam.desktop[10503]: wine: Unhandled page fault on read access to 0000000000000000 at address 00000001421E881E (thread 04dc), starting debugger...
Jul 10 19:25:40 steam.desktop[10506]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Jul 10 19:25:40 steam.desktop[3786]: ThreadGetProcessExitCode: no such process 10506
Jul 10 19:25:40 steam.desktop[3786]: ThreadGetProcessExitCode: no such process 10503

I run proton experimental but tried the other versions, they dont work either.
start commands are: PROTON_NO_ESYNC=1 gamemoderun PROTON_USE_WINED3D11=1 %command%

Ubuntu 22.04

**Comment by kisak-valve** [comment]
Hello @mihstaz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/556#issuecomment-1179768740.
