### ISSUE TITLE
Yet another games not running in general with Proton issue report

### ISSUE THREAD

**Issue by RaggedVagabond** [ValveSoftware/Proton#5988]
#### Your system information

* Steam client version (build number or date): Jun 7 2022
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: I don't know...
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I toggle Steam Play for all titles on, Steam prompts to restart, I hit yes, steam restarts, and I go back into settings to find it's toggled back off.

This is a fresh install of Manjaro, it worked just fine previously, I've tried uninstalling and reinstalling steam, but I'm guessing there's a config file outside of the core Steam files cause it still had my login and everything when I started it back up.

I'm not as well versed in Linux as I could be, the Manjaro graphical package manager has spoiled the everloving hell out of me, so you might have to hold my hand just a little bit... 

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @RaggedVagabond, this reads like the issue being tracked at ValveSoftware/steam-for-linux#6043. If a third party Steam Play isn't involved, then let me know and I can re-open this issue report, otherwise this is a duplicate.

Closing in favor of the older issue report.

**Comment by RaggedVagabond** [comment]
Differences that I'm experiencing vs the ticket you've linked are, the other user states the client shows the compatibility settings as active in spite of the check box not being checked, I guess by looking in compatibility for the individual game? I'm not seeing anything that says it's trying to use Proton, and none of the games that I've had running on a previous Manjaro install ever start. Other difference, I get the same result whether I try to use a custom build or an official build, I actually didn't attempt the custom build until I was trying to fix this problem on my own.

**Comment by kisak-valve** [comment]
`none of the games that I've had running on a previous Manjaro install ever start` This sounds like Steam is allowing you to install Windows-based games (no greyed out install button?), but there's an issue somewhere that prevents the games you've tested from starting. Is this correct?

Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by RaggedVagabond** [comment]
https://gist.github.com/RaggedVagabond/a7c90262d1038e81022938c6fbb15f27

That is pretty weird, it is allowing me to install Windows exclusives even...

**Comment by RaggedVagabond** [comment]
Alright, I figured out how to check if Steam is applying Proton to a title, under the title's 'information' tab, and they are all saying that I've selected to run them on whatever version of Proton. Still can't get ANY of these titles to run on any version of Proton atm. Maybe I need to make a different ticket after all...

**Comment by kisak-valve** [comment]
That tells us that Steam is behaving as expected, and your issue should be pondered from Proton's side. There's no particular value in fragmenting this issue across multiple issue reports.

We're tracking issues with games run with Proton in the Proton issue tracker, so I've gone ahead and transferred this issue report and tentatively renamed it so that it would be less misleading. Feel free to change the issue report title to something more accurate.

Looking at your system information, it looks healthy overall with no obvious hint. There's two things we could try to get another hint to ponder. First, if you completely close Steam, then run `steam-runtime` from a terminal, are there any hints in the terminal spew when you tell Steam to run a game with Proton?
Second, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to one of the game's launch options, try to run it, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by RaggedVagabond** [comment]
Terminal:

[jack@Executive-Privelege ~]$ steam-runtime
steam.sh[84949]: Running Steam on manjarolinux 21.3.2 64-bit
steam.sh[84949]: STEAM_RUNTIME is enabled automatically
setup.sh[85023]: Steam runtime environment up-to-date!
steam.sh[84949]: Steam client's requirements are satisfied
[jack@Executive-Privelege ~]$ 

I'm assuming "$HOME/steam-$APPID.log" is supposed to be a path to the AppID.log file? My Steam's path where compatibilitytools.d is located for custom protons is Home/Jack/.steam/root/compatibilitytools.d , if that helps at all. I cannot locate the file

[Edit]
[jack@Executive-Privelege ~]$ $HOME/steam-1462040.log
bash: /home/jack/steam-1462040.log: Permission denied

**Comment by RaggedVagabond** [comment]
Yello, I'm not sure if I was unclear, I'm not sure how to pull the proton log. I'd like Linux to be my primary gaming platform, but I'm dual booting too, so no huge rush

**Comment by RaggedVagabond** [comment]
Idk how I... only just thought to search for the file with the numbered appID...
```
======================
Proton: 1657128959 experimental-7.0-20220706
SteamGameId: 1462040
Command: ['/run/media/jack/Media/SteamLibrary/steamapps/common/FINAL FANTASY VII REMAKE/ff7remake.exe']
Options: {'forcelgadd'}
depot: 0.20220602.55
pressure-vessel: 0.20220601.0
scripts: v0.20220527.0-0-g8669533
soldier: 0.20220601.0 soldier 0.20220601.0
Kernel: Linux 5.15.50-1-MANJARO #1 SMP PREEMPT Sun Jun 26 07:06:30 UTC 2022 x86_64
======================
```
This is literally the entire log. Steam said the game was starting, then stopped, and updated the cloud. Does this every time

**Comment by kisak-valve** [comment]
A header only log hints that there was an issue in Proton's python scripting before the game had a chance to run, which would be in the terminal spew as described before. What filesystem are you using with `/run/media/jack/Media/SteamLibrary`?

I suspect that you're using an NTFS partition. Proton is known to be finicky interacting with NTFS, to the point that the general recommendation is to use a linux native filesystem instead.

**Comment by RaggedVagabond** [comment]
GHA! It IS NTFS, but I'm pretty sure Manjaro installs with NTFS by default [I'll double check]
But I'm also trying to keep a common storage drive between Windows and Manjaro, mostly for the music but also in order to not have to download any games twice.

**Comment by kisak-valve** [comment]
It should be noted that sharing a Steam library folder between OSes is unsupported going back to the initial release of Steam for Linux (https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation). Undefined / untested behavior might occur from trying to do that.

That said, you might get lucky with some of notes at https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows.

The issues with NTFS are fairly well known and is being tracked in [several other issue reports](https://github.com/ValveSoftware/Proton/search?q=ntfs+-label%3A%22Game+Compatibility+-+Unofficial%22&type=issues) in this issue tracker going back to #11. Closing as a duplicate.
