### ISSUE TITLE
Ori and the Will of the Wisps

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#5990]
# Compatibility Report
- Ori and the Will of the Wisps
- Steam AppID of the game: 1057090

## System Information
- GPU: NVIDIA GTX960M
- Driver/LLVM version: Driver Version: 515.57       CUDA Version: 11.7         LLVM : 14.0.6
- Kernel version: 5.18.10-zen1-1-zen ( Arch-Linux , Linux-Zen Kernel )
- Link to full system information report as [Gist](https://gist.github.com/):
OS: Arch Linux x86_64 
Host: 80RN Lenovo Rescuer-14ISK 
DE: Plasma 5.25.3
CPU: Intel i5-6300HQ (4) @ 3.200GHz 
GPU: NVIDIA GeForce GTX 960M 
GPU: Intel HD Graphics 530 
Memory: 4690MiB / 11880MiB 

- Proton version:7.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
- [x] I have this game

Ori and the will of the wisps game is stuck when opening animation and  interlude animation are played,and the game is probably kept at 28-42fps (the resolution needs to be reduced to 800p)

**Comment by kisak-valve** [comment]
Hello @Slemoon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4528#issuecomment-1184352207.
