### ISSUE TITLE
Proton Experimental 22-07-14 Update - New Issues in Far Cry 3

### ISSUE THREAD

**Issue by K3zter** [ValveSoftware/Proton#5993]
Currently playing through Far Cry 3 on Steam Deck using Proton Experimental, was working okay however in the latest update there are strange colour issues and visual artefacts - when blood decals appear on the screen (e.g. when skinning an animal or being shot at), they are now luminous green, when going underwater there are flashes of various colours often filling the entire screen. Particle effects around glowing objects such as fire are also strangely discoloured.

**Comment by kisak-valve** [comment]
Hello @K3zter, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/727#issuecomment-1184435819.
