### ISSUE TITLE
Control Ultimate edition Stuck in mission = cant finish game

### ISSUE THREAD

**Issue by mushroomeo** [ValveSoftware/Proton#5994]
# Compatibility Report
- Name of the game with compatibility issues: Control Ultimate edition
- Steam AppID of the game: 870780

## System Information
- GPU: RTX 3080 Ti
- Driver/LLVM version: NVIDIA Driver Version: 515.57
- Kernel version: 5.18.11-xanmod-1-1, but tryed normal kernal too and didnt work
- Link to full system information report: https://gist.github.com/mushroomeo/dff5944a3a2c1b8f0d3da1a30dbaaaa6
- Proton version: All and additionally some glorious eggroll

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

PROTON LOG:
[steam-870780.log](https://github.com/ValveSoftware/Proton/files/9112177/steam-870780.log)

## Symptoms 
getting stuck by talking with npc. so cant progress/finish game
i can rorate camera and and go in menus but nothing happening else. the npcs just standing and no doalogue. = stuck

## Reproduction
just do the mission: my borthers keeper, find dylan. and talk to the npc after running through white bridge...

https://user-images.githubusercontent.com/9019563/178994150-e9350a8e-2659-4220-b0a7-a1fd0570db73.mp4

![b7useyl](https://user-images.githubusercontent.com/9019563/178994493-4d8a6975-5c08-44f5-9073-9a65b56f4af0.jpg)

trying verify integrity of game , tryed different protons, tryed find in internet about if someone got same bug, nothing seems to work , its proton or game bug i cant test since i dont have windows OS anymore.

**Comment by kisak-valve** [comment]
Hello @mushroomeo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4157#issuecomment-1184464454.

**Comment by mushroomeo** [comment]
ok finaly i resolved the issua by resraerring the mission from the game main menu and now it worked. i supersry for trouble . i htink it was game bug and not proton...
