### ISSUE TITLE
No Man's Sky - 275850 - Extreme Sound cracking with proton-experimental post 7.0-3

### ISSUE THREAD

**Issue by bk201doesntexist** [ValveSoftware/Proton#5997]
# Compatibility Report
- Name of the game with compatibility issues: No Man's Sky
- Steam AppID of the game: 275850

## System Information
- GPU: Nvidia 1070 ti
- Driver/LLVM version: nvidia 515.57
- Kernel version: 5.8.11
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.githubusercontent.com/bk201doesntexist/83bdbd4ee5a91dfd491ee6eb7992d9e6/raw/2ada46741f7ad0d96522accf9b06bf9554e32857/gistfile1.txt
- Proton version: 7.0-3, Proton-Experimental

## I confirm:
- [] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms

Extreme sound cracking is present after the two latest proton-experimental updates. This started happening last week 03-09/07/2022.
Extreme sound cracking is NOT present in Proton 7.0-3 release.

## Reproduction
Tested with multiple sound cards, even though none of them ever presented issues.
PulseAudio/Pipewire settings were reviewed, nothing out of place was found.

When different proton versions were selected for testing, the proton prefix was always deleted to ensure a clean start.
I also rebuilt proton-experimental from source, pointing it at 5206e22eaa1bd48427188c5cce3c1843b1351542, and sound cracking was fixed.

There was one compatibility report opened for appid 275850, but has nothing to do with this issue. Please let me know if there's anything else required, and I'll try to provide it.

**Comment by kisak-valve** [comment]
Hello @bk201doesntexist, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-1185508494.
