### ISSUE TITLE
[Whitelist] South Park™: The Stick of Truth™ (213670)

### ISSUE THREAD

**Issue by Thalionquses** [ValveSoftware/Proton#60]
I just tested South Park™: The Stick of Truth™ and it seemed to work perfectly fine (as it does with vanilla wine)

- Ubuntu 18.04.1
- GTX 1070 (396.51)
- Intel i5-6600k
- Proton 3.7 (default configuration)

[Steam System Information](https://gist.github.com/Thalionquses/021e9c18a7921c3813f3e4a99f6bda78)

**Comment by b8e5n** [comment]
Worked for me on two different system, both Ubuntu 18.04, default steam proton 3.7.
Old laptop, nouveau drivers gt310, intel i5 first gen.
desktop pc, nvidia drivers 396.45 gtx 650 ti, intel i7-3820

**Comment by mlassnig** [comment]
Works fine on desktop Debian 9.5 Stable, nvidia 396.51, i7-4790K, GTX970.

**Comment by Bulbyzarr** [comment]
UPlay works correctly with Proton 3.7 or you use unofficial version of these games ?

**Comment by Thalionquses** [comment]
@berillions it looks like that the Steam version doesn't use UPlay. Steam directly starts the game when you click on play.

**Comment by Houtworm** [comment]
I 100 percented this game without any crashes,

There is a small problem with glitches, In the cutscenes my character and my buddy (the person in your party) would dissapear if they made a movement of any kind, Not sure what caused it but it did not affect gameplay, It can be fixed by restarting the game.

Arch Linux
GNOME 3.28.2
Nvidia 396.54

**Comment by jgacas** [comment]
Also works beautifully on my machine.

System info: https://gist.github.com/jgacas/64704de0370633b265b2970b97ec7d35

**Comment by Mezentium** [comment]
Works perfect on Manjaro:

System1:
- AMD A8-7800
- RX 560 GPU
- 16 GB RAM

System2:
- Intel Core i7 3820QM
- Intel integrated graphics 4000
- 32 GB RAM

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.

**Comment by canismarko** [comment]
I'm having an issue with this game where after some period of playing (anywhere between 5 and 60 minutes) it will stop accepting keyboard input. It still responds to the mouse, and if I kill the process and restart it works again. I've tried this on 2 different machines and 2 different desktop environments and it happens consistently.

- Gentoo 2.6
- Linux 4.14.65
- Proton 3.16-4
- nvidia drivers
- i3 and gnome window managers
- AMD Ryzen 7 1800X
- GeForce GTX 1060 6GB
- 32 GB DDR4 RAM

**Comment by kisak-valve** [comment]
Hello @canismarko, please open a new issue report.
