### ISSUE TITLE
Rocket League (252950)

### ISSUE THREAD

**Issue by tatsujb** [ValveSoftware/Proton#6001]
# Compatibility Report
- Name of the game with compatibility issues: Rocket League
- Steam AppID of the game: 252950

## System Information
- GPU: GTX 1080
- Driver/LLVM version: nvidia 510
- Kernel version: 5.15.0-41-generic
- Link to full system information report as Gist : https://gist.github.com/tatsujb/275e7e3817dac46c7b1bce26b1e94c15
- Proton version: Experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
(I'm creating a new thread since rocket league worked fine before, this is a new issue that suddenly surfaced. I tried reporting it to Psyonics, I also made a reddit thread but it's when another said the issue went away for him when he downgraded proton version that I realized this might be due to a proton update : https://www.reddit.com/r/RocketLeague/comments/vyulfb/comment/igcagvi/?context=3 )
- [X] that I have checked whether there are updates for my system available.

[steam-252950.log](https://github.com/ValveSoftware/Proton/files/9125523/steam-252950.log)

## Symptoms 

player Nameplates don't appear since the 12th of July 2022
![Screenshot from 2022-07-14 19-45-28](https://user-images.githubusercontent.com/5132359/179349894-e533ac0c-3920-4876-8f00-463c513a5838.png)
as you can see neither my teamates nor myself have a nameplate and that makes players hard to see.

**Comment by tatsujb** [comment]
and yeah with Proton version 7.0 the nameplates are back : 
![Screenshot from 2022-07-16 11-57-24](https://user-images.githubusercontent.com/5132359/179350116-fc6f069e-afe9-488f-82c8-f960b29abbb7.png)

**Comment by kisak-valve** [comment]
Hello @tatsujb, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3521#issuecomment-1186181813.
