### ISSUE TITLE
Rocket League mouse wheel inconsistent scroll beahviour

### ISSUE THREAD

**Issue by Hackeitos** [ValveSoftware/Proton#6007]
# Compatibility Report
- Name of the game with compatibility issues: Rocket League
- Steam AppID of the game: 252950

## System Information
- GPU: RTX 3060 Ti
- Driver/LLVM version: nvidia-dkms 515.57-1
- Kernel version: 5.18.10-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): [Steam system report](https://gist.github.com/Hackeitos/f9360bbc30bcff2c38a366d4869f3ea1)
- Proton version: Proton 7.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Mouse wheel scroll behaviour seems inconsistent. Sometimes it works correctly, but sometimes input gets registered twice and sometimes it doesn't at all.

## Reproduction
- Open game
- Launch freeplay (or anything to get in-game)
- Bind any action to MWHEELUP or MWHEELDOWN (in my case I have "focus on ball", but other actions present the same problem)
- Move the mouse wheel accordingly to the keybind set a few times

[steam-252950.log](https://github.com/ValveSoftware/Proton/files/9127494/steam-252950.log)

**Comment by kisak-valve** [comment]
Hello @Hackeitos, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3521#issuecomment-1186508300.
