### ISSUE TITLE
Some games not open for apparenly no reason

### ISSUE THREAD

**Issue by swaipyy** [ValveSoftware/Proton#6008]
# Compatibility Report
- Name of the game with compatibility issues: Various titles
- Steam AppID of the game:91700, 4500, 217200

## System Information
- GPU: rx 560
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 22.1.2 LLVM 13.0.1
- Kernel version: 5.18.7-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): [System information](https://gist.github.com/swaipyy/64479c0c5dda6dc6ddc1f742fff156d2)
- Proton version: any

## I confirm:
- [✔️] that I haven't found an existing compatibility report for this game.
- [✔️] that I have checked whether there are updates for my system available.

Proton Logs:
[STALKER SOC steam-4500.log](https://github.com/ValveSoftware/Proton/files/9129019/steam-4500.log)
[WORMS ARMAGEDDON steam-217200.log](https://github.com/ValveSoftware/Proton/files/9129020/steam-217200.log)
[EYE DIVINE CYBERMANCY steam-91700.log](https://github.com/ValveSoftware/Proton/files/9129024/steam-91700.log)
Other games that DONT WORK:
-Any STALKER GAME (4500, 20510, 41700)
-POST VOID (1285670)
-DEATH'S GAMBIT: AFTERLIFE (356650)
-DARK DEVOTION (718590)

Games that ACTUALLY WORK:
- Dark Souls Remastered (570940)
here the log for this: [steam-570940.log](https://github.com/ValveSoftware/Proton/files/9129036/steam-570940.log)
- Cruelty Squad (1388770)
- Dread Templar (1334730)

## Symptoms 
Games won't launch and don't pop up any error message

## Reproduction
literally open a game

## Aditional Notes 
When i open Worms Armageddon (217200) with wine in terminal an error appear that says: "wine: read access denied"

**Comment by kisak-valve** [comment]
Hello @swaipyy, looking at your system information, 32 bit Vulkan is broken on your system (https://gist.github.com/swaipyy/64479c0c5dda6dc6ddc1f742fff156d2#file-gistfile1-txt-L277-L290) due to https://github.com/GPUOpen-Drivers/AMDVLK/issues/278.

This is a video driver issue, not a Proton issue.

**Comment by swaipyy** [comment]
Thanks uninstalling lib32-amdvlk and installing lib32-vulkan-radeon fix the problem, exist any guide to know how read that weird looking logs to troubleshooting myself?
