### ISSUE TITLE
Call of Duty Black Ops Stuttering

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#6010]
Whenever I play Call of Duty Black Ops often the game stutters and frames drop also btw I am on Linux Mint and I tried all version of proton and the game either didn't launch or it stutters during game play.

**Comment by kisak-valve** [comment]
Hello @ColdTrilogy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/790#issuecomment-1188981818.
