### ISSUE TITLE
Mass Effect Legendary Edition (1328670) strange start behaviour

### ISSUE THREAD

**Issue by hrrd** [ValveSoftware/Proton#6011]
# Compatibility Report
- Name of the game with compatibility issues: Mass Effect Legendary Edition
- Steam AppID of the game: 1328670

## System Information
- GPU: RTX 3060 TI
- Driver/LLVM version: 515.48.07
- Kernel version: 5.17.15
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7.0-3

## I confirm:
- [ yes] that I haven't found an existing compatibility report for this game.
- [ yes] that I have checked whether there are updates for my system available.

For me logging didn't worked. Tried with instructions also with troubleshooting. But nothing.

## Symptoms 

When I start the game I get a warning that Steam is not responding. Force quit does what it is supposed to. Waiting has taken a very strange turn. If you ignore this warning it disappears and you get to the menu. However, if I want to continue with the game state, strange things happen. It appears a loading screen of Mass Effect and if you look at the bottom of Steam icon then there are 4 different windows. After a short time the warning appears again that Steam is not responding and then this program crashes. However, it continues to run in the background you can hear the sounds.... However, it is in the other window. If you go to the Steam icon and select you on this window happens the first time nothing only at the second catches the window and the game then works and you can play save and yes. However with such an effort. I have tried to found out what these different 4 windows are and why before 2 are in between 4 and then again 2. The 4 windows are described as Steam, Mass Effect, Splash Screen and Mass Effect Launcher. When starting the game the windows are Steam and Mass Effect and after the crash it is the 4 windows I described before. After that I did not look. If it helps you, I can still do that with pleasure. It's like Steam is starting the game and Origin compulsively trying to take over. But just guessing no idea what is happening. The game works though. But with this hustle. But im worried that with time maybe it will break more. maybe mass effect 2 won't work.
I would be very grateful for your help.

## Reproduction
1. Proton 7.0.3 
2. Go to Library and launch the Game.
3. Don't click on force quit or wait for the program if the warning steam doesn't respond appears.
4. See the magic happening

**Comment by kisak-valve** [comment]
Hello @hrrd, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4823#issuecomment-1189172877.

**Comment by hrrd** [comment]
sorry for the inconvenience. Thanks
