### ISSUE TITLE
Hitman 3 Freezing/Crashing

### ISSUE THREAD

**Issue by ecameracci** [ValveSoftware/Proton#6013]
# Compatibility Report
- Name of the game with compatibility issues: Hitman 3
- Steam AppID of the game: 1659040

## System Information
- GPU: RX 6400
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 22.1.2
- Kernel version: 5.13.0-valve21-2-neptune-02209-g2a5bdc1102a0
- Link to full system information report as [Gist](https://gist.github.com/): [System Information](https://gist.github.com/ecameracci/b54ce0b4cd4c6e367ef4ea8b7e66d799)
- Proton version: proton-7.0-3 (also tried with experimental, but logs are captured with 7.0-3)

## I confirm:
- [ * ] that I haven't found an existing compatibility report for this game.
- [ * ] that I have checked whether there are updates for my system available.
[steam-1659040.zip](https://github.com/ValveSoftware/Proton/files/9145031/steam-1659040.zip)

## Symptoms 
When launching Hitman 3, I get the launcher screen. After selecting "Play" I see the "ioi" splash screen and then the game freezes. Attempting to launch the game again sometimes causes a crash or the freezing again. I have managed to get into game once after changing from exclusive fullscreen to fullscreen and from disabling vsync, but the freeze just happens later. The game is frozen,  but alt+tab (or exiting the game from the steam deck overlay menu) still works.

## Reproduction
* Launch the game
* Select "Play" on the splash screen.
* Observe game is frozen

## Notes
This is with a PC with HoloISO installed on it. This is the relevant output from neofetch:
```
OS: SteamOS Holo x86_64
Host: OptiPlex 3060
Kernel: 5.13.0-valve21-2-neptune-02209-g2a5bdc1102a0
Packages: 875 (pacman), 6 (flatpak)
Shell: bash 5.1.16
Resolution: 2560x1440
DE: Plasma 5.23.5
CPU: Intel i5-8400 (6) @ 4.000GHz
GPU: AMD ATI 03:00.0 Device 743f
GPU: Intel CoffeeLake-S GT2 [UHD Graphics 630]
Memory: 1816MiB / 7774MiB
```
This happens when launching in both the gamescope session and the desktop mode. The game is installed on the same ext4 formatted drive as the OS. Verified that the game runs under Windows to rule out a potential hardware issue.

**Comment by kisak-valve** [comment]
Hello @ecameracci, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5536#issuecomment-1189619654.
