### ISSUE TITLE
Alice: Madness Returns (19680)

### ISSUE THREAD

**Issue by DavidinCT** [ValveSoftware/Proton#6019]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

**Comment by DavidinCT** [comment]
I have been playing this game on Proton. The game runs and with the right controls (SteamDeck) it seems to run really good. The issue in the game you shrink to get in small places, on a Windows PC or Xbox, it will show like a bubble background(with a sound like hiccups). 

On Proton this shows just a black screen making these parts un-passable. This makes the game unplayable as there are parts in the game that YOU NEED to get small to pass. You can play to point but can not pass...

This was installed off a retail CD.

**Comment by DavidinCT** [comment]
I found more info on this, I have not tested this but, I will... It might be a work-around...

https://steamcommunity.com/app/19680/discussions/0/3417683648802408868/

I got this to stop by disabling post processing in the video settings. Hopefully that helps
[#](https://steamcommunity.com/app/19680/discussions/0/3417683648802408868/#c6117591958726685676)

**Comment by opal1974** [comment]
I already reported this, and this entry is a duplicate:

https://github.com/ValveSoftware/Proton/issues/522

6019 should be merged with 522

**Comment by kisak-valve** [comment]
Issue report transferred to https://github.com/ValveSoftware/Proton/issues/522#issuecomment-1193152815.
