### ISSUE TITLE
Ghost Recon Wildlands

### ISSUE THREAD

**Issue by Mr-McBride** [ValveSoftware/Proton#6020]
The game was playable for a day using Proton Experimental, but today when I launch the game it does not recognize any keyboard input.

Is there anything I can do to assist with troubleshooting this?

**Comment by kisak-valve** [comment]
Hello @Mr-McBride, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1507#issuecomment-1191484400.
