### ISSUE TITLE
R.U.S.E. support

### ISSUE THREAD

**Issue by Lamera** [ValveSoftware/Proton#6021]
Hello there
I try to run ruse on Ubuntu 22.04 LTS with Steam Proton experimental.
However I get this critical error on start:
![grafik](https://user-images.githubusercontent.com/19840658/180335951-6b20295d-1d77-4d7f-8475-e54bffcec4bd.png)

The following error appears after clicking on ok:

```
Version  : Final
UNKNOWN_EXCEPTION (Probably C++)

RaiseException (0)
RaiseException (0)
_wctype (0)
 (0)
 (0)
BaseThreadInitThunk (0)
RtlUserThreadStart (0)
RtlCreateUserThread (0)

Core dumped in C:\users\steamuser\Temp\000099_Ruse Final_29.dmp for post-mortem analysis.

The call stack was copied to the clipboard.

Press OK to report the dump by mail, CANCEL to quit.
```
Are there any options I can try to make it work?

**Comment by kisak-valve** [comment]
Hello @Lamera, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1602#issuecomment-1192062497.
