### ISSUE TITLE
documentaion error

### ISSUE THREAD

**Issue by cdoublejj** [ValveSoftware/Proton#6025]
the directions under attached disk say to use fdisk but, don't' warn the users about data loss OR "AttachED" needs to be "Attach"

**Comment by cdoublejj** [comment]
also document says media folder but, on mine it's mnt folder there is no mention as to this possible variation or talk of reasons for one directory such as media to be user over mnt directory.

**Comment by kisak-valve** [comment]
Hello @cdoublejj, you can adjust the wiki page yourself.

The location of mounted partitions can vary greatly based on personal preference. `/media/gamedisk` at https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows#create-a-mount-point is an arbitrary example and isn't right or wrong.

It looks like the usage of fdisk is to list all drive partitions, which shouldn't be a write operation and comes with no risk.
