### ISSUE TITLE
Game directory in compatdata not removed after uninstalling the game

### ISSUE THREAD

**Issue by joshas** [ValveSoftware/Proton#6029]
On Proton 7.0-3 after uninstalling game that used Proton (runs using Steam Play) directory steam/steamapps/compatdata/{GAME_ID} is not deleted. While most files are deleted, directory is left with few files in /pfx/dosdevices/ - `z:`, `c:`, `d:` and `d::`. This issue is recurring with most games I play using Proton, and could been in earlier Proton versions too.

**Comment by kisak-valve** [comment]
Hello @joshas, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/7418. Closing as a duplicate.
