### ISSUE TITLE
How to install language patches

### ISSUE THREAD

**Issue by jinzhongjia** [ValveSoftware/Proton#6030]
I am a Chinese player. There are many game language patches in exe format, which need to be run and installed. Is there any way to run the exe file correctly and let it install the patch to the game directory?
The version I am currently using: experimental version

**Comment by kisak-valve** [comment]
Hello @jinzhongjia, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5766. Closing as a duplicate.
