### ISSUE TITLE
MH Rise freezes in option menu

### ISSUE THREAD

**Issue by almightyfoon** [ValveSoftware/Proton#6040]
# Compatibility Report
- Name of the game with compatibility issues: Monster Hunter Rise
- Steam AppID of the game: 1446780

## System Information
- GPU: GeForce RTX 2060 Mobile
- Driver/LLVM version: 470.129.06
- Kernel version: 5.18.10-76051810-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/almightyfoon/6b01255488ab282ce4a6496333e18ee2
- Proton version: 7.0-3
- OS: pop os 22.10

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates f
or my system available.

[steam-1446780.log](https://github.com/ValveSoftware/Proton/files/9215804/steam-1446780.log)
## Symptoms 
When going into the options menu either in game or at the launch screen attempting to go to any option other than audio freezes the video. Audio still plays after a bit of being choppy. I thought it was a file permissions issue maybe so I've verified the files and reinstalled completely.

## Reproduction

1. Launch game
2. Go to options
3. move mouse to save data
4. game freezes

**Comment by kisak-valve** [comment]
Hello @almightyfoon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5495#issuecomment-1199171609.
