### ISSUE TITLE
Tekken 7 (389730) freezes whenever i hit another character,Reinstall fixes it once but after that it breaks again

### ISSUE THREAD

**Issue by xaetacorenet** [ValveSoftware/Proton#6042]
Turning off Vibration in game settings seems to fix this
# Compatibility Report
- Name of the game with compatibility issues: Tekken 7
- Steam AppID of the game: 389730

## System Information
- GPU: AMD Ryzen 7 5800X 8-Core Processor
- Driver/LLVM version: xf86-video-amdgpu-22.0.0-3.2.x86_64
- Kernel version: 5.18.11-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/JeroenMathon/af768570e991b069d09c9d214122985c
- Proton version: 7.x, 6.x  and Expirimental show the same issues

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Proton logs: https://gist.github.com/JeroenMathon/18e43165760ecbad5f28ac6502100a54
## Symptoms 
Whenever i hit another character in the game or get hit, on the first hit the game freezes, the music keeps playing but the game becomes unresponsive and the video freezes.

Reinstalling seems to fix it for one game, if i start a new session it does the same thing

## Reproduction
Start the game, Open practice or online, Hit or get hit by another character, Game freezes up and becomes unresponsive.
https://youtu.be/kky1f22mTD8 Video of the bug

I have tried nearly every version of proton even custom wine binaries but nothing seems to solve this

**Comment by ScarredDreams** [comment]
I had the same issue when connected few other controllers to the steam deck. 
Disabling vibration in game menu helps. Game freezes when vibration is about to trigger.

**Comment by xaetacorenet** [comment]
> ed few other controllers to the steam deck.
> Disabling vibration in game menu helps. Game freezes when vibration is

Oh my god this works, i think the reason why proton7.0-2 might work is because vibration does not work in it

**Comment by antonioortegajr** [comment]
This is also working for me.

**Comment by Enough7** [comment]
Playing the first mission chapter starting with the first fight the game instantly freezes and you see a "D-Pad press right". Disabling vibration in Tekkens Game Settings fixes this.

**Comment by xaetacorenet** [comment]
Disabling Vibration fixes this issue, after almost a year im closing this issue since the description does not match the issue anymore, feel free to open a new one for a fix with vibration, im not sure if its fixed in the newer versions if proton, for now im closing this with the following workarround:

Turn off Vibrations in the controller/gamepad settings to resolve the crashes
