### ISSUE TITLE
Grand Theft Auto V - Textures stop loading and game crashes

### ISSUE THREAD

**Issue by lukeskn** [ValveSoftware/Proton#6047]
# Compatibility Report
- Name of the game with compatibility issues: Grand theft Auto V
- Steam AppID of the game: 271590

This Bug only happens since the summer update a couple of days ago. Before that everything was fine.

## System Information
Steam Deck (latest Updates applied)
- Driver/LLVM version: AMD AMD Custom GPU 0405 (vangogh, LLVM 13.0.0, DRM 3.45, 5.13.0-valve21-1-neptune-02209-g2a5bdc1102a0)
- Proton version: Experimental and 7.03
- Entire System Information: https://gist.github.com/lukeskn/548f18a54d5617276e351052c2f2f28a

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

PROTON_LOG=1 %command%`-log to the session:
[steam-271590.tar.gz](https://github.com/ValveSoftware/Proton/files/9228693/steam-271590.tar.gz)

## Symptoms 
The game just crashes after about 10 to 120 minutes of playing. The textures stop loading in and after that the game crashes.
This is the first step (textures stop loading): https://imgur.com/a/fnEpHR5 and shortly after that the game crashes completly.

## Reproduction
Happens every time i try to play GTA V. With DirectX 10 it seems to happen more frequently but i had it happen w/ the DirectX 11 setting as well.

## Additional information from other peoeple
https://www.reddit.com/r/SteamDeck/comments/wa0792/playing_gta_v_on_the_sd_when_this_happens_anyone/
https://www.protondb.com/app/271590

**Comment by Spined** [comment]
I have the exact same issue.

**Comment by kisak-valve** [comment]
Hello @lukeskn, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-1200406170.
