### ISSUE TITLE
Black ops 3 crashes, generaly during cutscenes.

### ISSUE THREAD

**Issue by Tremmer2003** [ValveSoftware/Proton#6048]
During cut scenes or seemingly at random the game will crash to desktop or frees forcing me to hit the steam stop button. This can happen in other modes like zombies and is least prevalent in multiplayer but can happen. Hypocenter, one of the campaign levels, will crash every time the recon drone projects what it is seeing to the top left corner of the screen, this issue was only tested in coop. the previews level, I forgot the name, crashes at the half way point after the hand cutting scene and will continue to crash after trying to rejoin the host, who was playing on windows, though this is inconsistent. [https://steamcommunity.com/id/Tremmer](url) <- my steam account has over 100hours in the game all of witch were played using proton experimental and on the custom GE fork, the crashing issue happens on both versions. Although I tried to make the previous examples as specific as possible there are many more instances that make the game crash along with other issues like textures and bipeds not loading in on occasion making the mode unplayable. on a personal note the random zombies crash is most annoying. I am playing on ryzen 9 5000 RTX 3080 ti 64gb ram, latest Ubuntu version. feel free to contact me with questions or clarifications.

Edit, the most annoying issue is the random controller disconnects.

**Comment by kisak-valve** [comment]
Hello @Tremmer2003, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/864#issuecomment-1200487676.
