### ISSUE TITLE
Atelier Sophie 2: loading screen freezes

### ISSUE THREAD

**Issue by eltia** [ValveSoftware/Proton#6050]
# Compatibility Report
- Name of the game with compatibility issues: Atelier Sophie 2: The Alchemist of the Mysterious Dream
- Steam AppID of the game: 1621310

## System Information
- GPU: AMD Custom GPU 0405
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 22.0.0-devel (git-74a3f4e63a) / LLVM 13.0.0
- Kernel version: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a
- Link to full system information report as [Gist](https://gist.github.com/): Steam Deck 512GB
- Proton version: Proton Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
- Loading screen could freeze.
- When the loading screen freezes, music will continue playing in the background and performance overlay would freeze.  Steam overlay still work and can be used to terminate the game.
- Total memory utilization by GPU and CPU is less than 15GB.  Swap file size has been increased to 8GB to ensure the game has enough memory.

## Reproduction
- Enter loading screen by fast travelling, zoning between maps, entering cutscene.
- This bug does not appear to have any particular trigger aside from entering loading screen.

[steam-1621310.log](https://github.com/ValveSoftware/Proton/files/9234273/steam-1621310.log)

**Comment by kisak-valve** [comment]
Hello @eltia, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5841#issuecomment-1201232587.
