### ISSUE TITLE
GTA V (271590) Allways freezes when finishing a race.

### ISSUE THREAD

**Issue by Lepidos** [ValveSoftware/Proton#6053]
# Compatibility Report
- Steam AppID of the game: 271590

## System Information
- RX5600XT
- mesa-22.1.3
- 5.18.14
- Proton version: Experimental

## I confirm:
- This is new. I've played hundreds of races before. 

## Symptoms 
Just enter a race and wait for it to finish.
This is what it looks like.

https://user-images.githubusercontent.com/51986094/182684995-6c2da3c9-3e47-41c6-8aed-a944d50f9a4e.mp4

https://user-images.githubusercontent.com/51986094/182685002-f7772baa-7d20-4e13-a3bd-99bada68ff86.mp4

**Comment by kisak-valve** [comment]
Hello @Lepidos, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-1204354077.
