### ISSUE TITLE
Streets of Rage 4(985890) Cannot play with Proton. Don't want native, it's slow.

### ISSUE THREAD

**Issue by deathxxx123** [ValveSoftware/Proton#6056]
# Compatibility Report
- Name of the game with compatibility issues: Streets of Rage 4
- Steam AppID of the game: 985890

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: any

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Black screen with sound. I can play it if i'm blind.

## Reproduction
Install game + DLC and play with any proton.

**Comment by deathxxx123** [comment]
Just cannot be played with any Proton with any distro / any hardware.
I think this is happen after DLC release. Before that i play with Proton and was wonderful.
Native version was released but it's slow and laggy.
Proton version is so much much better.

**Comment by kisak-valve** [comment]
Hello @deathxxx123, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3818#issuecomment-1201782493.
