### ISSUE TITLE
GTA V textures don't load, cause ctd after moving any distance

### ISSUE THREAD

**Issue by TheLagginDragon** [ValveSoftware/Proton#6059]
# Compatibility Report
- Name of the game with compatibility issues: GRAND THEFT AUTO V
- Steam AppID of the game: 271590

## System Information
- GPU:  GTX 970 ZOTAC 4GB
- Driver/LLVM version:  nvidia 515.57, 515.65.01, 510.73.05 (tried all)
- Kernel version:   10.0-16-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/TheLagginDragon/00be7bafc9467636b418dbb6fcdfa4f2
- Proton version: GE27, experimental proton, proton 7.x, proton 5.x, 4.x, etc

## I confirm:
- [ not as far as i can see ] that I haven't found an existing compatibility report for this game.
- [ only for a couple things that dont effect this in any way, updating changed nothing ] that I have checked whether there are updates for my system available.

## Symptoms 
textures dont load even on lowest settings, texture streaming never occurs after initialization of 3d world and eventually results in a crash. 

## Reproduction
select proton runner compatibility checkbox, choose any runner
install game
play for less than 5 mins
textures dont stream or load, ctd or freeze shortly afterwards

*shouldnt the simi-stub in the error be 0x4000000 instead of 400000? idk if thats holding up the entire thing, doubtful but just a thought. im no programmer, im just a script kiddi, please advise great linux masters

**Comment by kisak-valve** [comment]
Hello @TheLagginDragon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-1206355313.
