### ISSUE TITLE
Regression: NieR Replicant on Proton Experimental

### ISSUE THREAD

**Issue by K4rakara** [ValveSoftware/Proton#6065]
# Compatibility Report
- Name of the game with compatibility issues: NieR Replicant ver.1.22474487139...
- Steam AppID of the game: 1113560

## System Information
- GPU: RX570
- Driver/LLVM version:  Mesa 21.3.9 / LLVM 12.0.1
- Kernel version: 5.18.13
- Link to full system information report as [Gist](https://gist.github.com/): [Here](https://gist.github.com/K4rakara/ef1a0afa2bbdca4541caa9bf5a7d385f)
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[Proton.log](https://github.com/ValveSoftware/Proton/files/9274257/Proton.log)

## Symptoms

Game immediately crashes after the window is created on latest experimental proton, but works on latest stable proton (7.0-3)

**Comment by Blisto91** [comment]
Hi there!
Experimental now uses dxvk master again instead of the 1.10.x branch.
dxvk master needs at least mesa (radv) 22.0 to work 🙂

**Comment by kisak-valve** [comment]
Hello @K4rakara, as @Blisto91 noted, DXVK in Proton's bleeding edge edge build has bumped the minimum requirement on video drivers and this is not a bug.

**Comment by K4rakara** [comment]
Ah, that's on me then! I'm on fedora silver blue and haven't updated my system in two weeks or so. Thanks!

**Comment by Blisto91** [comment]
Note that flatpak steam bundles it's own mesa drivers (but you probably know that since you use silver blue) and there isn't a stable version with the new ones ready yet. But i believe the new required stable runtime might be coming here in August.
But using the beta flatpak should include them afaik. Tho i don't use flatpak myself.
