### ISSUE TITLE
"No display found" on Proton Experimental only

### ISSUE THREAD

**Issue by Rattel** [ValveSoftware/Proton#6066]
# Compatibility Report
- Planet Zoo (703080)
- Serious Sam 3 (41070)

## System Information
- GPU:  AMD Radeon(TM) Vega 3 Graphics
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 21.2.6 (LLVM 12.0.0) 
- Kernel version: 5.4.0
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Rattel/3e700d7851b5b11c68ca5b9d6e9c972f
- Proton version: Proton Experimental

## I confirm:
- [x]  that I haven't found an existing compatibility report for this game.

- [x] that I have checked whether there are updates for my system available.

[steam-703080.log](https://github.com/ValveSoftware/Proton/files/9274743/steam-703080.log)

## Symptoms 
After a system update (not sure if the video drivers were updated) the mentioned games started throwing "No display found" and "Display drivers are outdated" errors. Switching to Proton 7.0-3 runs the games as before.

## Reproduction
Run the games under Proton Experimental with these video drivers

**Comment by Leopard1907** [comment]
Mesa 22 is needed now.

https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa

On Ubuntu based distros; you can add this ppa to your system, update drivers and try again with Experimental.

`sudo add-apt-repository ppa:kisak/kisak-mesa`

`sudo apt update`

https://github.com/doitsujin/dxvk/wiki/Driver-support#dxvk-next-release

Anything above DXVK 1.10.x branch needs Mesa 22 as minimum driver version.

**Comment by Rattel** [comment]
> Mesa 22 is needed now.
> 
> https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa
> 
> On Ubuntu based distros; you can add this ppa to your system, update drivers and try again with Experimental.
> 
> `sudo add-apt-repository ppa:kisak/kisak-mesa`
> 
> `sudo apt update`
> 
> https://github.com/doitsujin/dxvk/wiki/Driver-support#dxvk-next-release
> 
> Anything above DXVK 1.10.x branch needs Mesa 22 as minimum driver version.

Thank you, the update to Mesa 22 worked
