### ISSUE TITLE
Paradise Killer (1160220)

### ISSUE THREAD

**Issue by OpieSF** [ValveSoftware/Proton#6069]
# Compatibility Report
- Name of the game with compatibility issues: Paradise Killer
- Steam AppID of the game: 1160220

## System Information
Steam Deck / SteamOS 3.3

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

Proton Log: (https://drive.google.com/file/d/1aEk9w5qAQV8QUcdzHZLaEldryb2rZri9/view?usp=sharing)

**Comment by kisak-valve** [comment]
Hello @OpieSF, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4195#issuecomment-1207282287.
