### ISSUE TITLE
All proton games don't work

### ISSUE THREAD

**Issue by GamerTechUni** [ValveSoftware/Proton#6071]
# System Information
* GPU: AMD Radeon Vega 8 Graphics
* Distro: Fedora 36
* Driver: 4.6 (Compatibility Profile) Mesa 21.3.9 (git-78c96ae5b6)
* Information about vulkan: [https://gist.github.com/GamerTechUni/9a8e7bff2411465dd95ce0ab17e6ffa8](https://gist.github.com/GamerTechUni/9a8e7bff2411465dd95ce0ab17e6ffa8)
* Proton Version: Experimental

# Symptoms
Any game that is run under proton crashes and does not work. I get 'failed to initialize graphics' or just a crash.

# How to reproduce
Run any windows game under proton

**Comment by kisak-valve** [comment]
Hello @GamerTechUni, noted at the top of https://github.com/ValveSoftware/Proton/wiki/Changelog. The builds of DXVK and VKD3D-Proton that are part of Proton Experimental requires mesa 22.0 or newer.

The version of mesa you're using inside the Flatpak environment is too old and this minimum driver requirement is not a bug.
