### ISSUE TITLE
Elder Scrolls Oblivion and Ubuntu Mate 20.04, Worked before, now doesn't detect Nvidia

### ISSUE THREAD

**Issue by a1872** [ValveSoftware/Proton#6072]
Hi. I have the Geforce 1030 and have played Oblivion on this computer many times. The only OS I have is Ubuntu Mate 20.04. The game does not detect the Geforce, and after clicking play, there is an error about not detecting a renderer  I have attached the screenshots of both issues--there is nothing to select for the card or resolution. I have tried to uninstall and purge all Nvidia files, reboot, install the Nvidia-470 driver files, reboot, then start the game again with no luck. On the Additional Drivers screen, Nvidia-515 driver is listed, but with this version, I get stuck in a Login Loop. Since the 470-version was the one that worked for a long time, I removed the 515 and went back to Nvidia-470. After this process, the game worked normally, but then when started again, gave the error you see. I also have SpaceEngine, and that game works fine--I haven't found any other game besides Oblivion and a Vietnam game that has a problem.

![Error after clicking play](https://user-images.githubusercontent.com/47876421/183274530-72e7e3e6-2abc-493a-a194-5a6fea936cde.png)
![Nvidia not detected](https://user-images.githubusercontent.com/47876421/183274531-32e9b877-3670-4a03-97b7-1a48727b46a4.png)
;

**Comment by kisak-valve** [comment]
Hello @a1872, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/718#issuecomment-1207381369.
