### ISSUE TITLE
NieR:Automata (524220) won't start (displays "No Graphic Memory" error)

### ISSUE THREAD

**Issue by rebio** [ValveSoftware/Proton#6073]
# Compatibility Report
- Name of the game with compatibility issues: NieR:Automata
- Steam AppID of the game: 524220

## System Information
- GPU: AMD Radeon RX 5500M
- Driver/LLVM version: AMD AMD RENOIR (DRM 3.42.0, 5.15.0-43-generic, LLVM 12.0.1), Version:  4.6 (Compatibility Profile) Mesa 21.3.9 (git-78c96ae5b6)
- Kernel version: 5.15.0-43-generic (64-bit)
- [Link to full system information report as Gist](https://gist.github.com/rebio/646f322526fb31762dd18b4d79db58b1)
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game won't start. On startup it displays an error that says "No Graphic Memory".
![NieR:Automata launch error](https://user-images.githubusercontent.com/10911084/183278974-9e384cb2-1a6a-474d-9679-2640dad01c21.png)

## Reproduction
Start the game with Proton Experimental.
(Maybe it needs to be on Wayland. I have not tested this yet. I will update the report after I've done so)

## Additional information
Easy fix for me: Switch from Proton Experimental to v7.0-3

I have no idea what caused the bug. I had to abort a system update because it got stuck. I also switched to Wayland.
First I updated the system on the command line (seemed to work). I switched back to X11 (no idea if this did anything). I manually set Proton to version 7.0-3. I have no idea what of them fixed the issue, but I think it's the switch of the Proton version because after that it ran flawless. I am not sure though since I played the game for ~24 hours on the experimental version and it worked just as fine.

I will add the PROTON_LOG once I switched back to the experimental version. I assume the log when the game does not work is the better one.

I found a few entries for this problem online and in the steam forum. Much of them talked about that you have to manually set the Mesa driver to some version. Before I tested this (since I have no idea how to do this) I tried to set the step down the version of proton. Since it worked I did not do any further research.

**Comment by kisak-valve** [comment]
Hello @rebio, noted at the top of https://github.com/ValveSoftware/Proton/wiki/Changelog. The builds of DXVK and VKD3D-Proton that are part of Proton Experimental requires mesa 22.0 or newer.

The version of mesa you're using inside the Flatpak environment is too old and this minimum driver requirement is not a bug.
