### ISSUE TITLE
STAR WARS Squadrons won't launch on linux

### ISSUE THREAD

**Issue by drivera73** [ValveSoftware/Proton#6074]
# Compatibility Report
- Name of the game with compatibility issues: STAR WARS Squadrons
- Steam AppID of the game: 1222730

## System Information
- GPU: GTX 3090
- Driver/LLVM version: nVidia 515.65.01-0ubuntu0.22.04.1 , Mesa 22.0.5-0ubuntu0.1
- Kernel version: 5.15.0-43-generic
- Link to full system information report as [Gist](https://gist.github.com/drivera73/c7b2c9f89797e76f8094dab8ec45d56f)
- Proton version: 7.0-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

The [log can be found here](https://gist.github.com/drivera73/eca08ce3da52f2ddd83a0490b55733f6)

## Symptoms 

EAC window opens, progress bar goes all the way, game exits without errors.

## Reproduction

1. Launch the game
2. Watch EAC show up, and go all the way to completion
3. Game stops without error message, no game window is ever shown

Looking at the [ProtonDB page for the game](https://www.protondb.com/app/1222730) it appears that many people are having solid success running it. It also appears to [run on the Deck](https://www.youtube.com/watch?v=fn3YIQHSNeI) [without issue](https://www.youtube.com/watch?v=r3eG8f8osR8), which suggests it could be something in my installation. I'm well aware this may not be a Proton issue inasmuch as game compatibility, but the lack of a clearer error indication to dig for a solution to the issue _**could**_ be a Proton issue (I don't know if/how this could be resolved, though).

At any rate, I'm hoping someone with a keener eye than mine can spot what the issue might be.

I've also tried with the two prior Proton versions (6.3-8, 5.13-6) as well as the Experimental one. I have so far abstained from ProtonGE b/c reasons :)

Cheers!

**Comment by kisak-valve** [comment]
Hello @drivera73, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4238#issuecomment-1207468976.
