### ISSUE TITLE
Apex Legends: No incoming in-game voice chat

### ISSUE THREAD

**Issue by morgaesis** [ValveSoftware/Proton#6075]
# Compatibility Report
- Name of the game with compatibility issues: Apex Legends
- Steam AppID of the game: 1172470

## System Information
- GPU: Radeon 6900XT
- Driver/LLVM version: OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.1.4
- Kernel version: 5.18.15-200.fc36.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): [System information](https://gist.github.com/morgaesis/e549f32a01d8b68886c1bfe88c55fe98)
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1172470.log](https://github.com/ValveSoftware/Proton/files/9277419/steam-1172470.log)

## Reproduction

1. Install Steam (system) on Fedora (silverblue?) and Apex Legends
2. Enter match
3. Use voice comms/voice chat
4. Team mates can hear me, but no audio from team mates

I can hear team mates using in-game VC (voice chat) on Windows, team mates seem to hear me, Discord VC works fine. Discord team mate has to relay whatever in-game VC is going on. I can see the speaker icon showing that team mate is speaking in-game.

**Comment by kisak-valve** [comment]
Hello @morgaesis, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1207477612.
