### ISSUE TITLE
Cracking the Cryptic (2085970)

### ISSUE THREAD

**Issue by ikea-shark-official** [ValveSoftware/Proton#6077]
# Compatibility Report
- Name of the game with compatibility issues: Cracking the Cryptic
- Steam AppID of the game: 2085970

## System Information
- GPU: Vega 8 (Ryzen 3500U integrated graphics)
- Driver/LLVM version: Mesa 21.3.9
- Kernel version: 5.18.16
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ikea-shark-official/a082440c0fc308bd4a3064ffe0a5065e
- Proton version: Experimental. This bug does not occur on proton versions <= 7.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[log file of error](https://github.com/ValveSoftware/Proton/files/9279142/ctc-error.log)

## Symptoms 
When trying to launch the app it fails to launch with the following error window:

![Screenshot from 2022-08-07 19-31-48](https://user-images.githubusercontent.com/81495842/183350607-41208af2-51dc-43a4-8b27-44f25f0db100.png)

## Reproduction
Launch the game using proton experimental

**Comment by kisak-valve** [comment]
Hello @ikea-shark-official, the build of DXVK in Proton experimental now requires mesa 22.0 or newer and the mesa version provided by Falkpak is too old to be used with it. This minimum driver version bump is not a bug.
