### ISSUE TITLE
Fall guys [1097150]

### ISSUE THREAD

**Issue by davigamer987** [ValveSoftware/Proton#6081]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Proton version: Experimental Bleeding edge
- System info gist: https://gist.github.com/davigamer987/0fdef8ceb2d0124710c373781eeca598

## I confirm:
- [Y ] that I haven't found an existing compatibility report for this game.
- [ Y] that I have checked whether there are updates for my system available.

## Symptoms 
Steam says the game is open but nothing opens (Game process is open when checking htop), Using latest proton experimental bleeding edge, with eac runtime installed

**Comment by davigamer987** [comment]
I found that opening the game from the terminal works (I used this script to run proton from the terminal: https://gist.github.com/davigamer987/0e68ca9d695ac6eca24b5ce7fdf9ffef)

**Comment by davigamer987** [comment]
Seems like the log didn't upload here's a gist instead https://gist.github.com/davigamer987/78ae4556ba978e25c98467d7b1dcdd1f

**Comment by kisak-valve** [comment]
Hello @davigamer987, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #4123, but this specific issue reads more like #6051. Closing as a duplicate.

If that's not the case, then please add a note with your experience to #4123.
