### ISSUE TITLE
Fifa 22 Origin after update not works (Other apps already running)

### ISSUE THREAD

**Issue by senpl** [ValveSoftware/Proton#6083]
# Compatibility Report
- Name of the game with compatibility issues: Fifa 22
- Steam AppID of the game: 1506830
- BuildID 9186369

## System Information
- GPU: RTX 2060
- Driver/LLVM version: nvidia 515.65.01-2
- Kernel version: 5.18.16-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7.0.3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Games lunch today before update. 
After fifa update no longer starts (complains about other process or not starts at all).
system update not helps.

## Reproduction
1. Install Fifa 22
2. Install origin
3. start game( not possible in current version.

[steam-1506830.log](https://github.com/ValveSoftware/Proton/files/9293209/steam-1506830.log)

**Comment by kisak-valve** [comment]
Hello @senpl, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5673#issuecomment-1209771114.

**Comment by senpl** [comment]
My case was solved by deleting all Origin files. Still nothing in logs suggest what to do so it was many tries and miss.

**Comment by vaslabs** [comment]
@senpl can you share more details, I have the same issue, I get the origin crash window , tried different versions of proton and different ea games , no luck

**Comment by senpl** [comment]
@vaslabs Just delete all Origin folders. They will be installed once again but now should work. Check internet how to find all their places.

**Comment by vaslabs** [comment]
> @vaslabs Just delete all Origin folders. They will be installed once again but now should work. Check internet how to find all their places.

What do you mean? I even reinstalled the games and deleted the prefixes, there are more locations?

**Comment by vaslabs** [comment]
Ok turns out it was something in the Mesa updates I pulled from git, I did a distro sync and it works
