### ISSUE TITLE
Game controller (Snack Box Micro and presumably others) doesn't register down after up.

### ISSUE THREAD

**Issue by GoLD-ReaVeR** [ValveSoftware/Proton#6087]
Proton Experimental, Proton-tkg and wine-tkg.

Using SOCD behavior on a hitbox/snackbox micro this is the easiest to reproduce. Having jstest-gtk and wine control's test joystick open on the same device emits different behavior:

When holding down you get down, when holding up you get up. However, when holding down, then pressing up and releasing up will cause jstest-gtk to show down up down (this is indeed what the controller is sending, confirmed with JunkFood Arcades), while wine control shows down up neutral. This bug is affecting all games where a controller such as this is applicable, such as Guilty Gears, Street Fighters, BlazBlues, GranBlues, etc. This bug may also be in effect on other controllers without players being able to consistently reproduce this issue which would make it hard to find.

**Comment by kisak-valve** [comment]
Hello @GoLD-ReaVeR, this issue is already being tracked at #5527. Closing as a duplicate.
