### ISSUE TITLE
The Witcher Enhanced Edition (20900)

### ISSUE THREAD

**Issue by b1zzu** [ValveSoftware/Proton#6089]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher Enhanced Edition 
- Steam AppID of the game: 20900

## System Information
- GPU: NVIDIA GeForce GTX 960
- Driver/LLVM version: 4.6.0 NVIDIA 515.65.01
- Kernel version: 5.18.16-200.fc36.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/b1zzu/80f5ed85bc12c353e4dfba8ab1899314
- Proton version: 1659678174 experimental-7.0-20220805

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-20900.log](https://github.com/ValveSoftware/Proton/files/9332044/steam-20900.log)

## Symptoms 

The game doesn't start

## Reproduction

Run `The Witcher Enhanced Edition` from Steam with Proton Experimental 

## Additional Info

- I've tried with different Proton version but none seems to work for me
- From protondb other users have a similar problem

**Comment by kisak-valve** [comment]
Hello @b1zzu, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/255#issuecomment-1214216523.
