### ISSUE TITLE
Marvel's Spider-Man Remastered (1817070): Random Crashes During Normal Gameplay

### ISSUE THREAD

**Issue by Javillin** [ValveSoftware/Proton#6090]
# Compatibility Report
- Name of the game with compatibility issues: Marvel's Spider-Man Remastered
- Steam AppID of the game: 1817070

## System Information
- GPU: NVIDIA GeForce GTX 1080 Ti 
- Driver/LLVM version: NVIDIA 515.65.01
- Kernel version: 5.19.1-2-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Javillin/369d9e689299e90f991c8fdf3c7da99c
- Proton version: 1659678174 experimental-7.0-20220805 [Proton Experimental]

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
I have no launch options set other than steam proton logging.

The game will crash at random during normal game play. Sometimes I can get away with a couple hours of consistent game play and other times it crashes within a few minutes, but the same issue will happen every time.

The game will freeze while audio continues playing. I will have to alt+tab out of the game to force close it with steam. I have not done anything other than play the game to get the crashes and it doesn't matter if I play the story missions or side missions or just collect things around the world.

It seems to happen at random in the open world and sometimes when I transition from open world to inside a building for a mission. Everything else runs smooth and I have no issues other than random crashes at different times during game play.

Changing the graphics settings does not help and sometimes will cause the game to crash if graphic settings are changed during game play.
## Reproduction
Will crash all the time during gameplay. 

[steam-1817070.log](https://github.com/ValveSoftware/Proton/files/9332438/steam-1817070.log)

**Comment by kisak-valve** [comment]
Hello @Javillin, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6088#issuecomment-1214259370.

**Comment by Dishoungh** [comment]
Hey, we seem to be experiencing similar issues. From what I've gathered from comments in other forums, it seems to be an Nvidia driver issue. That may be the case. If I recall correctly, a similar situation happened with God of War when it first came out, though I don't remember it being as bad as this.

We might have to wait for a driver update or just simply play it on Windows unfortunately.

**Comment by Javillin** [comment]
@Dishoungh Yes, I agree. Glad I got to hear from someone else who has a similar setup having the same issue. I'm still holding off from playing it in Windows although I have thought about trying a Windows qemu vm. I just hope there will be a patch or driver update that will fix the issue soon.

**Comment by Dishoungh** [comment]
> @Dishoungh Yes, I agree. Glad I got to hear from someone else who has a similar setup having the same issue. I'm still holding off from playing it in Windows although I have thought about trying a Windows qemu vm. I just hope there will be a patch or driver update that will fix the issue soon.

I would do that, but as far as my knowledge serves me, that requires me to have an additional GPU to passthrough to the guest VM.

If you can accommodate that setup, then you can follow these guides:

https://github.com/vanities/GPU-Passthrough-Arch-Linux-to-Windows10
https://wiki.gentoo.org/wiki/GPU_passthrough_with_libvirt_qemu_kvm

**Comment by Javillin** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6090#issuecomment-1217351373

Thanks for the resources. I still don't know much about the whole process so I'll be looking into these. I heard about the potential of near native performance but forgot about the extra GPU so might be out a luck there. These are good future references though so much appreciated.
