### ISSUE TITLE
[SteamDeck] God Eater: Resurrection issue | Soft Locking

### ISSUE THREAD

**Issue by GingerBobRoss** [ValveSoftware/Proton#6091]
# Compatibility Report
- Name of the game with compatibility issues: God Eater Resurrection
- Steam AppID of the game: 460870

## System Information
- GPU:  GPU 0405 (Vangogh)
- Driver/LLVM version:  LLVM 12.0.0, DRM 3.45, 5.13.0-Valve21-1-Neptune-02209
- Kernel version: 5:13-Valve21-1-Neptune-02209
- Link to full system information report as https://github.com/GingerBobRoss/Gist-SystemInfo/blob/main/SteamDeckinto
- Proton version:7.03, ProtonGE 7.24, ProtonGE 7.28

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms: Game is rated as steam verified for the deck, but the game suffers from soft locks for 10-20 seconds during mission select and will soft lock mid game during hunts.
The game will sometimes have issues with audio playing as well, but the soft locking is the biggest issue to playability.

Issue can be semi resolved by using PROTON_NO_ESYNC=1 %command%, but game suffers from performance issues after playing with the command on.
Same effect when using PROTON_NO_FSYNC=1 %command% and  PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 %command%

Additionally, The game is not available to list issues on ProtonDB, due to the game not being available on the store as it comes bundles with God Eater 2 Rage burst

**Comment by kisak-valve** [comment]
Hello @GingerBobRoss, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1884#issuecomment-1214343678.
