### ISSUE TITLE
DEATHLOOP: problem when using the SteamDeck FPS limiter

### ISSUE THREAD

**Issue by hervegirod** [ValveSoftware/Proton#6094]
# Compatibility Report
- Name of the game with compatibility issues: DEATHLOOP
- Steam AppID of the game: 1252330

## System Information
- GPU: Steam Deck [AMD](https://fr.wikipedia.org/wiki/Advanced_Micro_Devices) RDNA 2
- Driver/LLVM version: Steam Deck Steam OS 3.3
- Kernel version: Steam Deck Steam OS 3.3
- Proton version: 7.0.3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
If I use the Steam Deck FPS limiter rather than the in-game FPS limiter, the game takes ages to load (several minutes). If I use the game limiter, there is no problem.

## Reproduction
In the Steam Deck, set the Steam Deck FPS limiter to 30 FPS, then the game takes a LOT of time to load the save game. If the Steam Deck limiter is set to Off (even if the in-game limiter is set to 30 FPS for example), loading takes a normal time to load.

**Comment by kisak-valve** [comment]
Hello @hervegirod, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5156#issuecomment-1214981473.

**Comment by hervegirod** [comment]
OK, thanks!

Le lun. 15 août 2022 à 15:00, kisak-valve ***@***.***> a
écrit :
