### ISSUE TITLE
GTA 4 refuses to work

### ISSUE THREAD

**Issue by sprmcell** [ValveSoftware/Proton#6098]
# Compatibility Report
- Name:
  Grand Theft Auto IV
- Steam AppID of the game:
  12210

## System Information

CPU: Ryzen 3 3100
GPU: NVIDIA GT610 2048MB
RAM: 16GB
Kernel: Zen Kernel 5.17.5
Proton: All version tried

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

## Log

[Steam Log](https://raw.githubusercontent.com/sprmcell/sprmcell/main/ignore/steam-12210.log)

## Symptoms 

Game used to launch to a black screen with no audio
as shown [here](https://www.youtube.com/watch?v=wjdoAhkhddQ)

Now its refuses to launch 
as shown [here](https://github.com/sprmcell/sprmcell/blob/main/ignore/image.png)

## Troubleshooting steps

- Yes i did reinstall
- Yes i did change proton versions
- Yes my drivers are up to date
- Yes i changed launch options

**Comment by kisak-valve** [comment]
Hello @sprmcell, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/350#issuecomment-1217952863.
