### ISSUE TITLE
Nvidia crappy card using Fermi and 5.13-16

### ISSUE THREAD

**Issue by Orochikyocr** [ValveSoftware/Proton#6108]
My computer was using a GT 630 and then switched to GT 710 card, because of reasons. It is not like I have a choice at least for now until I get more money for a new GPU.
I'm aware Nvidia is just cheaters selling 600 and 700 series with old Fermi chips. The GPUs I have are both Fermi.
So far I've been using PROTON_USE_WINED3D=1 %command% alongside Proton 5.0-10 to play some fighting games on my computer and everything run fine. 
But for some reason, Proton 5.13-6 and newer versions do not even try to launch these same games. Steam just straight opens the popup message saying the game is launching, it closes immediately then nothing happens with the green "Play" button available again.
BTW no Proton LOG file is generated at all.

If Proton 5.13-6 is only compatible with Vulkan or needs some newer version of OpenGL is unbeknownst to me. I had looked for info everywhere about this and I found zero information on the issue. 
If that is the case I think you should make it official that 5.13-6 and newer versions are only compatible with Vulkan-capable cards and the PROTON_USE_WINED3D=1 %command% trick will not work at all anymore. 

FYI INvidia claims these  600-700 cards are fully DX12 and Vulkan cards, which is a lie. For some reason, they shipped some of their GPUs with Fermi chip and others with Kepler. Kepler support was also dropped recently so please, do not buy Nvidia, my humble advice.

If you are looking for a cheap card to host 2 analog VGA monitors, DO NOT BUY THIS GT 710, this card only works with one analog and one digital monitor. HDMI and DVI converters will not work.

My PC specifications. I don't think they will matter but here we go.
AMD ATHLON X3 at 3.3GHZ
8GB RAM
NVIDIA CRAPPY GT 710 using obnoxious 390.156 drivers.
LUBUNTU 20.04 updated to the latest software releases.

Thanks for reading all this nonsense. Have a good day.

**Comment by kisak-valve** [comment]
Hello @Orochikyocr, Vulkan support is a requirement for Proton, the `PROTON_USE_WINED3D` runtime config option is not considered supported, and the NVIDIA 390 video driver series is older than the original minimum requirements back with the first release of the project. Sorry, but your hardware is not supported by Proton.

That said you've encountered the issue being tracked at https://github.com/ValveSoftware/steam-runtime/issues/420. Closing as a duplicate.
