### ISSUE TITLE
Elite Dangerous (359320) Black screen, and an error message.

### ISSUE THREAD

**Issue by ketronix-dev** [ValveSoftware/Proton#6111]
When trying to load the game first appears a black screen, starts playing intro music, and later appears an error message.

[Screenshot](https://imgur.com/zYm3sZ7)
[Video](https://mirror.osel.pp.ua/video.mp4)

## System Information
- GPU: AMD Radeon R5 340X
- Driver/LLVM version: Mesa 22.1.4
- Kernel version: 5.19.1
- Distro: openSUSE Tumbleweed
- Link to full system information report as [Pastebin](https://pastebin.com/AMmhLMdg):
- Proton version: 7.0.4

**Comment by kisak-valve** [comment]
Hello @ketronixdev, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/150#issuecomment-1221539477.
