### ISSUE TITLE
Final Fantasy XIV Online (39210)

### ISSUE THREAD

**Issue by iam-Ore** [ValveSoftware/Proton#6116]
# Compatibility Report
- Name of the game with compatibility issues: Final Fantasy XIV Online
- Steam AppID of the game: 39210

## System Information
- GPU: Nvidia GeForce GTX 1050 Ti 
- Driver/LLVM version: 4.6.0 NVIDIA 515.65.01 (NVML Version: 11.515.65.01)
- Kernel version: 5.19.2-arch1-1
- Window Manager: Xfwm4
- Link to full system information report as [Gist](https://gist.github.com/iam-Ore/db924c92feb489d66c658e9f6c39c857#file-gistfile1-txt):
- Proton version: Experimental (Tried 7.0-4 as well)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game launches just fine but the launcher just displays ffxiv's logo and it remains stuck there, I even tried changing browser in FFXIV_BOOT.cfg to 1 but that didn't work out:

![image](https://user-images.githubusercontent.com/95232133/186138281-8aab6f67-b849-44d0-9da4-bf8fd1d85b84.png)

**Comment by DanielR-I** [comment]
I am also experiencing the exact same issue... tried experimental, 7.0-4, and 6.3-8

I also tried disabling the default "General" settings for (1) Steam Overlay and (2) Desktop Game Theatre with SteamVR

Operating System: Manjaro Linux
KDE Plasma Version: 5.24.6
Kernel Version: 5.15.60-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6800 XT

**Comment by jdfthetech** [comment]
duplicated issue
experimental and 7.0.4
Tested on a windows machine and the launcher has some bugs where it thinks it's already loaded and refreshes a few times so it appears to be some changes there.

**Comment by kisak-valve** [comment]
Hello @iam-Ore, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/580#issuecomment-1224015191.

**Comment by DanielR-I** [comment]
Not sure why the merge of issues, as this one is specific to today's FF14 6.2 patched launcher.  Don't individual (and perhaps unrelated) issues get lost when all are merged under one game topic?

**Comment by srhb** [comment]
kisak is very diligent, and that issue has been doing good work for years :)
