### ISSUE TITLE
Magic: The Gathering Arena

### ISSUE THREAD

**Issue by jvalrog** [ValveSoftware/Proton#6118]
# Compatibility Report
- Name of the game with compatibility issues:
- Magic The Gathering Arena (external game)

## System Information
- Nvidia 1650 GTX
- 470.141.03
- 5.16.15
- Proton version: 7.0-4 and Experimental, both

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Game works great overall, but won't run with Experimetal branch at the moment.
With 7.0-4 works but the store is not accesible.

Magic Arena is coming to Steam this year so sooner or later this should be reviewed.

**Comment by kisak-valve** [comment]
Hello @jvalrog, the DXVK and VKD3D-Proton builds inside of Proton Experimental currently requires NVIDIA 510.47 or newer. Your video driver version is too old to use that Proton build.

**Comment by acranglesim** [comment]
With latest proton experimental and nvidia 525 the game doesn't install

The installer launches, I can select install folder, and then it doesn't progress any further.

Edit: the installer works if I use protonup-qt to download proton-tkg , so there must be some patches in there that make it work

**Comment by kisak-valve** [comment]
Closing in favor of #6826.
