### ISSUE TITLE
Monster Hunter Rise[: Sunbreak] Weird, constant stutters [NVidia GTX 1060 6GB]

### ISSUE THREAD

**Issue by awakenedCrowl** [ValveSoftware/Proton#6119]
Spec Info:
intel i5-9xxxk (can't remember exact number, but 9XXX series should be enough?)
NVidia GTX 1060 6GB
16GB Ram
Ubuntu Budgie
Latest Proprietary NVidia Drivers
Issue is persistent across all latest Proton Drivers (including GE)
Game installed on mounted internal m.2 ssd, different drive than OS

When I'm playing Sunbreak on my Linux Distros, I am experiencing some noticable stuttering (sudden, short FPS drops) in general gameplay. Compared to Windows (which I have in Dual Boot), on the same settings, the game also taxes the GPU much more and heats it up about 10°C further. On Windows, it runs just fine, barely gets my GPU temps above idle. It also has some occasional small stutters there, but unlike with Linux, they are only very situational and not consistently every few seconds.

Those stutters didn't seem to have been there from the beginning though. Although by now, I have changed quite some things as I experimented around, the stutters began seemingly randomly, with no notable change in the time around it.
The stuttering is just as bad, no matter whether I set the FPS Cap to 30, 60 or 120 (normally I put it to 60 as I only have a 60HZ monitor and don't want to heat my GPU more than necessary).

The only thing that seems to make the stutters significantly less frequent (almost on par with Windows) is turning of "Force Full Pipeline Composition" in the NVidia XServer Settings. But that then again, brings back very bad screen tearing.

On ProtonDB or anywhere else, I can't find anyone else with a similar problem. Maybe someone has an idea what might cause the problem?

I also already tried some launch options like something with NV_API and some Vulkan Options, but none seem to show any impact.

I am using visual mods, but even completely uninstalling them doesn't seem to have any effect.

**Comment by kisak-valve** [comment]
Hello @awakenedCrowl, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5495#issuecomment-1228514235.

**Comment by awakenedCrowl** [comment]
Oh, I'm sorry. I had just seen two MHRise issues (prolly just a filter I didn't notice) and such believed that I was in some kind of Sub-Area dedicated to this kind of issues. Should've read better
