### ISSUE TITLE
Dualsense not working with Dying Light 1

### ISSUE THREAD

**Issue by marcem7D0** [ValveSoftware/Proton#6121]
# Compatibility Report
- Name of the game with compatibility issues: 239140
- Steam AppID of the game: Dying Light

## System Information
- GPU: MSI GTX 1660 Super
- Driver version: Nvidia 515.65.01
- Distribution: Arch Linux
- Kernel version: Linux arch 5.19.4-arch1-1
- Proton version: Proton Experimental, 7.0-4, 6.3-8

## I confirm:
- [+] that I haven't found an existing compatibility report for this game.
- [+] that I have checked whether there are updates for my system available.

## Symptoms:

When I start Dying light from steam, the Dualsense controller buttons simple not working, pressing them result nothing. The touchpad works however. Tried all 3 mode without success (Disabled, Default, Enabled steam input). Tried Dying light 2 with the same 3 mode, works perfectly. (With disabled with Playstation button icons, with default the button icons are the Xbox icons.)

## Reproduction

1. Plug Dualsense through USB cable.
2. Start Dying light through proton.
3. Press the buttons to skip the intro(nothing happens)
4. Press the touchpad to skip the intro(The intro being skipped)

**Comment by kisak-valve** [comment]
Hello @marcellmittnacht, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2569#issuecomment-1229176227.

**Comment by marcem7D0** [comment]
Hello @kisak-valve , thanks for the information, will keep it in mind for next time! Thanks for the transfer!
