### ISSUE TITLE
The problem is in the online game Smite.

### ISSUE THREAD

**Issue by hrach333** [ValveSoftware/Proton#6124]
The game runs perfectly. The problem starts in online mode. When the match starts, it literally throws about 2 seconds (sometimes a little longer) into the game menu. I think it has to do with EasyAntiCheat. Please help.

**Comment by kisak-valve** [comment]
Hello @hrach333, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2208#issuecomment-1229484568.
