### ISSUE TITLE
Dark Souls III (374320) No sound after game update.

### ISSUE THREAD

**Issue by somewhatfrog** [ValveSoftware/Proton#6128]
# Compatibility Report
- Name of the game with compatibility issues: Dark Souls III
- Steam AppID of the game: 374320

## System Information
- GPU: 3060ti
- Driver/LLVM version: 515.65.01
- Kernel version: arch 5.19.4
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental (but any has same result)

## I confirm:
- [ + ] that I haven't found an existing compatibility report for this game.
- [ + ] that I have checked whether there are updates for my system available.

[steam-374320.log](https://github.com/ValveSoftware/Proton/files/9442302/steam-374320.log)

## Symptoms: 

No sound, long startup. 
I tried clean prefixes as well.
Game shows up in audio mixer.

## Reproduction: 

Start the game as usual. Sometimes sound works tho.

**Comment by BillFleming** [comment]
I have no sound or controller issues using newer protons with the following settings: (also xaudio override was required on proton 4.x last time I played years ago)
But a big warning **is that Steam might delete your game save when you switch from an old proton to a newer one**, so make sure to back up your old game save first if you haven't played it in a while. This game doesn't have cloud sync.

- Enable the Steam Overlay while in-game
- Controller->Use default settings
- Compatibility: Proton Experimental
- launch command:
-- `WINEDLLOVERRIDES="xaudio2_7=n,b" %command%`

edit: Still running 5.18.17-268-tkg-pds here on this PC.

**Comment by somewhatfrog** [comment]
Issue seem to go away with 5.19.5 kernel update.

I will close it later if it won't happen again in the next couple of days.
