### ISSUE TITLE
Warhammer Vermintide 2 EAC Insufficient Resources Error

### ISSUE THREAD

**Issue by Montagge** [ValveSoftware/Proton#6129]
# Compatibility Report
- Warhammer Vermintide 2
- Steam AppID of the game: 552500

## System Information
- GPU: GTX1050ti
- Driver/LLVM version: nVidia 515.65.01
- Kernel version: 5.15.0-46-generic
- Link to full system information report as [Gist](https://gist.github.com/Montagge/5d9850a381f52390247bfdf72a662cb4):
- Proton version: Experimental
- Using Steam Native
- Vermintide 2 is not installed on the same drive as Steam (it won't fit as I use a smaller SSD for the OS and software)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Proton Log
[steam-552500.log](https://github.com/ValveSoftware/Proton/files/9448703/steam-552500.log)

EAC Game Launcher Log
[gamelauncher.log](https://github.com/ValveSoftware/Proton/files/9448711/gamelauncher.log)

Vermintide 2 Console Log
[console-2022-08-30-00.52.13-c555b455-3458-4466-ad49-dd8afea87841.log](https://github.com/ValveSoftware/Proton/files/9448718/console-2022-08-30-00.52.13-c555b455-3458-4466-ad49-dd8afea87841.log)

## Symptoms 
Game will launch and get to the warning.  Once I click continue a notification at the top right of the screen will appear informing me that EAC has insufficient resources, cannot continue and I am Untrusted.  The game will hang here and needs to be forced closed.

I have on two occasions gotten it to launch all the way into the game.  Once was after a Proton Experimental update pushed out to the Steam client. The other time seemed almost random as I have not been able to replicate it.

I have tried in various orders and combinations tried
1. Deleting the compatdata folder
2. Reinstalling Proton EAC Runtime
3. Reinstall Steam Linux Runtime - Soldier
4. Verifying the game files
5. Installing Proton EAC Runtime on same disk as game
6. Installing Proton EAC Runtime on same disk as Steam
7. Running the EAC executable in the compatdata to repair the EAC install
8. Tried the launcher bypass beta
9. Didn't use any beta

## Reproduction
For me it's pretty much guaranteed if you try to play the game

[](url)

**Comment by kisak-valve** [comment]
Hello @Montagge, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1528#issuecomment-1231039865.
