### ISSUE TITLE
La Pucelle: Ragnarok (1866420)

### ISSUE THREAD

**Issue by ipr** [ValveSoftware/Proton#6133]
# Compatibility Report
- Name of the game with compatibility issues:La Pucelle: Ragnarok
- Steam AppID of the game:1866420

## System Information
- GPU: AMD Vega 56/64
- Driver/LLVM version: Mesa 22.2.0~rc3
- Kernel version: 5.19.6
- Proton version:7.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
During opening intro there is no display of the intro: there is green rectangle on upper-right corner but otherwise screen is black. You can hear sound played.
In the main menu there is no background image either.

## Reproduction
1. start the game
2. observe the screen

[steam-1866420.log.gz](https://github.com/ValveSoftware/Proton/files/9466962/steam-1866420.log.gz)

**Comment by Blisto91** [comment]
@ipr Hi there.
This is a issue with the wine implementation of `d3dcompiler_47` so to work around it for now you'll have to install the windows version through protontricks or winetricks.
As extra info see the dxvk issue https://github.com/doitsujin/dxvk/issues/2883 (tho note dxvk itself is not the problem)

**Comment by ipr** [comment]
There was update to the game which fixed the intro video.
Works fine now!
