### ISSUE TITLE
Counterside (1976440)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#6136]
# Compatibility Report
- Name of the game with compatibility issues: Counterside
- Steam AppID of the game: 1976440

## System Information
- GPU: GTX 1080
- Driver/LLVM version: nvidia-515.65.01_1
- Kernel version: 5.18.19_1
- Link to full system information report as [Gist](https://gist.github.com/miusaky/5fb21bf7250ae21cbc8173e8cb7453f6).
- Proton version: 7.0.4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game launches and shows the initial splash screen but never moves past that point. It does not crash, just remains what seems like a still frame of the initial loading screen. 

## Reproduction
Install the title and launch it.

**Comment by ghost** [comment]
[steam-1976440.log](https://github.com/ValveSoftware/Proton/files/9476279/steam-1976440.log)

Log upload failed in the initial post so here it is.

**Comment by kisak-valve** [comment]
Hello @miusaky, some possible lines of interest from your log:
```
err:   Failed to create shared resource: VK_KHR_EXTERNAL_MEMORY_WIN32 not supported
[...]
warn:  D3D11: Failed to write shared resource info for a texture
```

**Comment by ghost** [comment]
> Hello @miusaky, some possible lines of interest from your log:

Hey, thanks. Seems like something is missing on Void. Seems to run fine out of the box on Arch, and whilst this was about Steam on desktop, it also ran fine out of the box on the SteamDeck.
