### ISSUE TITLE
How to Build Proton Without Faudio - Revert to older Wine XAudio2 implementation

### ISSUE THREAD

**Issue by Tribalwarfare** [ValveSoftware/Proton#6142]
Hi,

I am currently using the latest version of Proton 7.0-4 stable to play Command and Conquer 3: Kanes Wrath from the Steam Library.
The APP ID is 24810.

In single player/Skirmish it runs great, however with any version of Proton or Wine that includes Faudio the game desyncs when playing LAN or Online multiplayer games.

Steam Proton 3.7-8 was the last version that did not cause and or result in desyncs as it did not include Faudio.

Is there a method to build the current stable Steam Proton version without the Faudio module and use the older Wine XAudio2 implementation? Can someone possibly provide a patch or guide on how to disable Faudio and use the older Wine XAudio2 implementation?

Thank you for your kind assistance,
AG

**Comment by kisak-valve** [comment]
Hello @Tribalwarfare, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/477#issuecomment-1238163029.
