### ISSUE TITLE
Dungeons & Dragons Online (DDO) (206480)

### ISSUE THREAD

**Issue by chknatwork** [ValveSoftware/Proton#6143]
# Compatibility Report
- Name of the game with compatibility issues: Dungeons & Dragons Online
- Steam AppID of the game: 206480

## System Information
- GPU: GTX 1650 Max-Q
- Driver/LLVM version: NVIDIA 515.65.01
- Kernel version: 5.19.1-3-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.githubusercontent.com/chknatwork/14fd72b4141b06c8c4c176b046acdf60/raw/bd17061e71581690e023520d9f2ac47e6188943b/gistfile1.txt
- Proton version: 7.0-4

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X
[steam-206480.log](https://github.com/ValveSoftware/Proton/files/9525260/steam-206480.log)
] that I have checked whether there are updates for my system available.

## Reproduction
Open Steam
Click Play, Launcher appears
Login
Select world to connect to, launcher closes
Steam doesn't launch game.

Same problem also occurs on Proton-GE 7.31-1, and other previous Proton versions up to 5.13-6

**Comment by Blisto91** [comment]
Does the issue happen if you launch with `PROTON_USE_WINED3D=1 %command%`

**Comment by kisak-valve** [comment]
Hello @chknatwork, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5695#issuecomment-1240643142.
