### ISSUE TITLE
Sword Art Online: Hollow Realization Deluxe Edition (607890)

### ISSUE THREAD

**Issue by Nathan-MV** [ValveSoftware/Proton#6144]
[steam-607890.log](https://github.com/ValveSoftware/Proton/files/9539260/steam-607890.log)
# Compatibility Report
- Name of the game with compatibility issues: Sword Art Online: Hollow Realization Deluxe Edition
- Steam AppID of the game: 607890

## System Information
- GPU: GTX 750TI
- Driver/LLVM version: nvidia 515.49.15
- Kernel version: 5.19.7
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Nathan-MV/1c1a77d4919dac17d03b11c1ca0313c8
- Proton version: 7.0-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Crashing the game and Steam after selecting Continue in the loading

## Reproduction
Start the Game
Select Continue

**Comment by zaps166** [comment]
Proton 7.0-4 - game freeze on loading screen when loading a city
Proton 6.3-8 - game is running ok

**Comment by kisak-valve** [comment]
Hello @zaps166, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by zaps166** [comment]
@kisak-valve 

Logs: [steam-607890.log.zip](https://github.com/ValveSoftware/Proton/files/9586243/steam-607890.log.zip)
[System information](https://gist.github.com/zaps166/b258955b4031297f8657a9b606cbf0d7)

**Comment by alasky17** [comment]
> Proton 7.0-4 - game freeze on loading screen when loading a city Proton 6.3-8 - game is running ok

This regression should be fixed with the most recent experimental release (experimental-7.0-20220919).  Thank you for reporting the regression :)

**Comment by SeongGino** [comment]
Can confirm that it works on current Experimental! Thank you for the fix.
