### ISSUE TITLE
Doom Eternal crash on open

### ISSUE THREAD

**Issue by kolemcrae** [ValveSoftware/Proton#6145]
# Compatibility Report
- Name of the game with compatibility issues: Doom Eternal
- Steam AppID of the game: 782330

## System Information
- CPU: i7-11370H
- RAM: 16 gigs
- GPU: Integrated Iris. Using Mesa Intel XE Graphics
- GPU driver version: 4.6
- Kernel version: 5.15.0-47-generic
- Proton version: experimental

## I confirm:
- [yes ] that I haven't found an existing compatibility report for this game.
- [ yes] that I have checked whether there are updates for my system available.

[steam-782330.log](https://github.com/ValveSoftware/Proton/files/9539252/steam-782330.log)

## Symptoms 
The game crashes after it shows the Bethesda logo. On first try it got to the ID logo but all tries since only the Bethesda. 

I can play Doom 2016 without issue. 

I have tried a TON to get this working, so here is the list: 
- Numerous versions of proton including GE versions
- turning off various things via launch options
- verifying game files
- uninstalling and reinstalling game
- reainstalling steam
- formatting my hard drive and installing a new operating system (I went from Pop_os 22.04 to Kubuntu 22.04) This step makes me think I have a rare bug or glitch with hardware. 

Other games all work fine with proton - Doom 2016 as mentioned, Rocketleague, Fallout 4, etc. 

Maybe you can find something I don't see in the log I attached?

**Comment by kisak-valve** [comment]
Hello @kolemcrae, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3773#issuecomment-1242574828.
