### ISSUE TITLE
Relative mouse mode broken in Proton 7.0.4 in several games for actual external mouse on Steam Deck

### ISSUE THREAD

**Issue by ell1e** [ValveSoftware/Proton#6146]
The relative mouse mode broken in Proton 7.0.4 in several games for an **actual external usb mouse** on the Steam Deck, it affects [Mass Effect Legendary Edition's mouse aim while walking around](https://www.protondb.com/app/1328670) and [Sims 3's photo mode (TAB key ingame while in live mode)](https://www.protondb.com/app/47890) and [Skyrim SE's mouse aim (requires disabling gamepad controls in the settings)](https://www.protondb.com/app/489830) for example. Since the games otherwise work fine and most notably the mouse works fine in all menus and all other situations with absolute mode (other than Skyrim where it's also broken for some menus), and also the Steam Deck built-in inputs work fine, this seems to be a bug with Proton's treatment of relative mouse input.

Since this seems to be quite fundamental, a fix would be nice, it kind of makes FPS games unplayable if one doesn't want to use the Steam Deck controller inputs. (Assuming that it affects more games than those I tested.)

Steps to reproduce in [Mass Effect Legendary Edition](https://www.protondb.com/app/1328670):

1. Boot a Steam Deck with default Steam OS with a standard usb mouse attached, non-beta, no desktop mode
2. Install [ME:LE](https://www.protondb.com/app/1328670), set proton/steam play settings to default which at least for me resulted in Proton 7.0.4
3. Launch the game from Steam via "Play" button in the regular Deck gamepad ui and do the Origin account link if needed, then start a new game in Mass Effect 1. As soon as you're through the dialogue and cutscenes and can walk around, try to look around with the mouse

Expected behavior: works

Actual behavior: extreme drift in some random direction, it's impossible to use the mouse to look around. Which for an FPS game is pretty bad

**Comment by Alexithymia2014** [comment]
This is also broken for me, I noticed this in Black Mesa. Booting into desktop mode is a workaround for now. Could be steam input related?

**Comment by FuzzyQuils** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6146#issue-1368643835

This sounds like a known bug in Gamescope that manifests when it's launched on it's own in a TTY, I ran into this on my non-Deck Archlinux system trying to run Overwatch in a dedicated Gamescope session. 
Unfortunately can't find a bug number for the issue in the Gamescope repo, it also only happens when trying to use a Gamescope session outside of a desktop session. (aka. running inside a desktop like KDE or GNOME works fine)

**Comment by ell1e** [comment]
I think any more newcomer user is most likely. if they use the Steam Deck in a dock with peripherals, to do so with the default gamepad UI and gamescope so it would be nice if this could be fixed since this seems like a major pitfall. The gamescope is also interesting to more advanced users for perf reasons, but this seems like quite the showstopper.

**Comment by ell1e** [comment]
Appears to be fixed with the upcoming Steam OS/upcoming GameScope versions: https://github.com/Plagman/gamescope/issues/633#issuecomment-1260141168
