### ISSUE TITLE
Defense Grid directx11 issue

### ISSUE THREAD

**Issue by pdanoe** [ValveSoftware/Proton#6147]
# Compatibility Report
- Name of the game with compatibility issues: Defense Grid
- Steam AppID of the game: 18500

## System Information
- GPU:  Corei7 onboard video
- Driver/LLVM version: 
- Kernel version:  xubuntu 18.04
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 3:7-8 3:16-9 4:2-9 4:11-13 5:0-10 5:13-6 6:3-8

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

Not sure what is asked for here. The problem has remained even when I downgraded the xubuntu from 20 to 18. So much I can say.

## Symptoms 
For about the last 2 years, I have been unable to make proton install directx11 when initialising the game after install. Until 2 years ago, I was able to make proton install directx11 by downloading the game, changing to a higer proton version, run the game (for which the proton version was too high, but it managed to discover that it should install directx11), change to lower proton version e.g. 3:7-8. run the game again, and there it would install the needed directx11.
When there is no directx11, the game will simply show a white screen.
Hope this is information enough for now.
Defense grid is an older game by now, but would be nice to see it work again

**Comment by kisak-valve** [comment]
Hello @pdanoe, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/669#issuecomment-1243003245.
