### ISSUE TITLE
Obduction [VR] (306760)

### ISSUE THREAD

**Issue by vpelletier** [ValveSoftware/Proton#615]
Debian sid
Linux 4.17.17
CPU i7-6700
GPU GTX 1060@6GB
Nvidia 396.51
Proton 3.7-4
Vive pro

- Main menu is not displayed in headset (only background - the asteroid field and planets in the distance). When removing headset, menu appears on screen and is functional, allowing to start a game.
- Sound goes through speakers instead of headset (although this is more a general issue with VR on linux).
- Sound in menu is choppy, but is fine once a game is started.
- In-game menu does not appear in headset nor on screen.

**Comment by kisak-valve** [comment]
Hello @vpelletier, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue to https://github.com/ValveSoftware/Proton/issues/327#issuecomment-416008137.
