### ISSUE TITLE
Proton Steam shim download

### ISSUE THREAD

**Issue by orowith2os** [ValveSoftware/Proton#6155]
I (and a few others) are looking to use Proton's Steam shim inside of bare Wine, since a game goes OOM with Proton but not Wine (Probably something with Proton?). Is there a shell script or the like for the Wine-Linux Steam shim that Proton includes?

**Comment by kisak-valve** [comment]
Hello @orowith2os, sorry, but creating a different flavor of wine is out of scope for this issue tracker and not supported.

**Comment by orowith2os** [comment]
Could I find a standalone installer for the Steam shim somewhere, at least, or will I have to pull it out of Proton by hand? Steam doesn't really play well inside of a Wine prefix.
