### ISSUE TITLE
Bail or Jail Demo (1881400)

### ISSUE THREAD

**Issue by Riesi** [ValveSoftware/Proton#6162]
# Compatibility Report
- Name of the game with compatibility issues: Bail or Jail Demo
- Steam AppID of the game: 1881400
- URL: https://store.steampowered.com/app/1715980/Bail_or_Jail/

## System Information
- GPU: GTX 970
- Driver/LLVM version: 515.49.14
- Kernel version: 5.19
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Riesi/87e8ece0a060b053b94755f8485640e7
- Proton version: 7.0-4 or Bleeding Edge

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-1881400_crash.log](https://github.com/ValveSoftware/Proton/files/9583390/steam-1881400_crash.log)
[steam-1881400_nocrash.log](https://github.com/ValveSoftware/Proton/files/9583391/steam-1881400_nocrash.log)

## Symptoms 
The game crashes after the first few greeting screens when opening the Terms of Service.  Reproduction of the crash should take a few seconds.
The "nocrash" log is from exiting the game before clicking the Terms of Service button.

## Reproduction

1. Start the demo and go through the initial greetings dialog screens until it asks to show you the Terms of Service.
2. Click the Terms of Service button
3. Game crashes

**Comment by gofman** [comment]
This is hopefully fixed in the current Proton Experimental ([bleeding-edge] branch, available to select in Proton Experimental properties, BETAS page).

**Comment by Riesi** [comment]
Demo doesn't crash anymore!
And games against AI seem to work fine!
Thanks.
