### ISSUE TITLE
FINAL FANTASY VIII - REMASTERED (Steam Deck)

### ISSUE THREAD

**Issue by maran** [ValveSoftware/Proton#6163]
# Compatibility Report
- Name of the game with compatibility issues: FINAL FANTASY VIII - REMASTERED
- Steam AppID of the game: 1026680

## System Information
- GPU: Steam Deck
- Driver/LLVM version: Steam Deck
- Kernel version: 5.13.0-valve21.1.1-neptune-02211-gc54cda5a36f3
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/maran/4fc11b7cf5868c6cedd39247d62bb128
- Proton version: Tested 5 to 7

## I confirm:
- [X] that I haven't found an existing compatibility report for this game. (There is an other one with different issues)
- [X] that I have checked whether there are updates for my system available.

Proton logs: https://gist.github.com/maran/e1ad7190b1ee3b5313f64816ee7f02a8

## Symptoms

After sleeping the Steam Deck and going into any menu (main menu / tutorial screen etc) the game graphics engine seems to freeze, sound does keep playing. Only way to fix is to restart. 

This does not happen on my Linux PCs with Proton, only on the Steam Deck. 

## Reproduction

1. Start game
2. Put Steam Deck to sleep via power button
3. Awake Steam Deck
4. Go into any menu (for instance by pressing the 'y' button)
5. Success (or rather failure)

I would love to learn more about Proton so if I can somehow contribute to this fix let me know.

**Comment by kisak-valve** [comment]
Hello @maran, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3040#issuecomment-1249354695.
