### ISSUE TITLE
Metal: Hellsinger (1061910)

### ISSUE THREAD

**Issue by Vladimir-A** [ValveSoftware/Proton#6164]
# Compatibility Report
- Name of the game with compatibility issues: Metal: Hellsinger
- Steam AppID of the game: 1061910

## System Information
- OS: Arch Linux
- KERNEL: 5.19.8-zen1-1-zen
- CPU: AMD Ryzen 7 5800X 8-Core
- GPU: AMD Radeon RX 6800 XT (sienna_cichlid, LLVM 14.0.6, DRM 3.47, 5.19.8-zen1-1-zen)
- GPU DRIVER: 4.6 Mesa 22.1.7
- RAM: 32 GB
- Link to full system information report as [Gist](https://gist.github.com/Vladimir-A/7a1aa84baaf140fdad941717c6f6a5bd):
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1061910.log](https://github.com/ValveSoftware/Proton/files/9585870/steam-1061910.log)

## Symptoms 
Crushed after click the new game button.

## Reproduction
1. Launch the game
2. Click on the new game button

**Comment by Gotchfutchian** [comment]
Same here (Was using Proton-GE-35, same issue happens on Experimental)

Games Log file for reference;
[Player.log](https://github.com/ValveSoftware/Proton/files/9620523/Player.log)
From what i can see, the game itself cant load a DLL/Module.

**Comment by neon-grim** [comment]
Same issue with proton experimental and proton GE version 30 to 36 (only tested these GE version). Game doesnt crash when using proton 7.04 but instead I'm faced with flickering / missing textures.

My current configuration: 
OS: Nobara Linux 36 (Thirty Six)
KERNEL: 5.19.12-201.fsync.fc36.x86_64
CPU: AMD Ryzen 7 5800X 8-Core
GPU: AMD Radeon RX 6900 XT (navi21, LLVM 14.0.5, DRM 3.47, 5.19.12-201.fsync.fc36.x86_64)
GPU DRIVER: 4.6 Mesa 22.3.0-develRAM: 32 GB

**Comment by Blisto91** [comment]
Should be fixed in [upstream  dxvk](https://github.com/doitsujin/dxvk/issues/2975) and be included in the next experimental update.
Bleeding edge should already have the fix.
