### ISSUE TITLE
Hardspace: Shipbreaker - tutorial overlay stuck on screen

### ISSUE THREAD

**Issue by bitcharmer** [ValveSoftware/Proton#6170]
# Compatibility Report
- Name of the game with compatibility issues: Hardspace: Shipbreaker
- Steam AppID of the game: 1161580

## System Information
- GPU: RTX 2080
- Driver/LLVM version: nvidia 515.65.01
- Kernel version: 5.15.36-xanmod1, 5.15.0 custom build
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/bitcharmer/007770db5331e94edb75a1ab5f093d34
- Proton version: 7.0.4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms

The tutorial overlay with key bindings stuck on screen. During training/tutorial shifts the game displays helpful information in an overlay in bottom left part of the screen. Unfortunately this overlay remains persistent across shifts and ships.
I first encountered this very early into the game. Back then it was some key binding info for flashlight, etc. I "worked around" it by starting a new career and unchecking tutorial. However after purchasing demo charges upgrade and going into the next shift the ">> Demo charge manual" overlay appears and stays persistent as described above.

## Reproduction

Start a new career with tutorials enabled, get to the point with keyboard hints for flashlight
OR
Start a game with tutorials disables and get to the point where demo charges are available.
The overlay will stay on screen and won't disappear.

![shipbreaker_overlay](https://user-images.githubusercontent.com/1662063/190976558-e1179602-baa1-47d6-96c1-e3d90a2fb66d.jpg)
[steam-1161580.log](https://github.com/ValveSoftware/Proton/files/9597188/steam-1161580.log)

**Comment by kisak-valve** [comment]
Hello @bitcharmer, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4007#issuecomment-1250956833.
