### ISSUE TITLE
Sea Of Thieves (1172620)

### ISSUE THREAD

**Issue by WiedenhoeverD** [ValveSoftware/Proton#6171]
# Compatibility Report
- Sea Of Thieves
- 1172620

## System Information
- CPU: Ryzen 3 3300X
- GPU: RX5700XT
- LLVM version: 14.0.6
- Driver/LLVM version: Mesa 22.1.7
- operating system: Arch Linux
- Kernel version: 5.15.68-1-lts
- Proton version: 7.0-4
- https://gist.github.com/WiedenhoeverD/33a173316396431ae472c9d0a6995bc8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Can't play the game.
Ingame error "Your connection to Xbox Live has been lost. Please check your connection and try again. (Cyanbeard)". 

## Reproduction
On first start I have to connect to Microsoft Account. This is working fine. After login into the Microsoft Account you can click "Start Game". Then it is loading and after some Seconds I get back to the start Menu with the error "Your connection to Xbox Live has been lost. Please check your connection and try again. (Cyanbeard)".

**Comment by kisak-valve** [comment]
Hello @WiedenhoeverD, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3931#issuecomment-1250964061.
