### ISSUE TITLE
AGE of Empires IV not start

### ISSUE THREAD

**Issue by JCDentonCore** [ValveSoftware/Proton#6176]
# Compatibility Report
- Name of the game with compatibility issues: Age of Empires IV
- Steam AppID of the game: 1466860

## System Information
- GPU: RTX 3070
- Driver/LLVM version: NVIDIA 515.65.01

- Kernel version: 6.0.0-1-MANJARO

- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/AceroRomano/568b1e5ae25a3aba0c802a273103eaa3
- Proton version:Experimental bleeding edge

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

https://gist.github.com/AceroRomano/087b70b59a052a99b8012fb973ce43a1

## Symptoms 

Not start exit at 5 seconds

## Reproduction

Start game, popup message warning old drivers of amd or something else and click ok, game start at fullscreen and shut down instantanly.

i try with beta of game but is same issue, try with proton 7.0-4 same.

**Comment by kisak-valve** [comment]
Hello @AceroRomano, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5258#issuecomment-1253037696.
