### ISSUE TITLE
Games crash without launching

### ISSUE THREAD

**Issue by Skaytacium** [ValveSoftware/Proton#6180]
## Overview
I'm not able to launch any game in my library without it immediately crashing. I click "Play", it turns to "Running" and without doing anything it crashes.

## Information
I've looked at a lot of issues relating to these but none of them seem to fit my case, including optimus based-issues. My `/usr/share/vulkan/icd.d` has only `nvidia_icd.json`, I've tried running the games with and without `prime-run` and other NVIDIA variables *`__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia`) but nothing works.

This happens in games that have gotten platinum ratings on ProtonDB (I've attached the logs for [Ultrakill #1229490](https://www.protondb.com/app/1229490), [Post Void #1285670](https://www.protondb.com/app/1285670) and [Superflight #732430](https://www.protondb.com/app/732430). All easy to run games (no anticheat, multiplayer, DRM) with good reports on ProtonDB).

I have tried using Proton Experimental and Proton 7.0-4. I've also installed all of the 32-bit requirements that I could see are needed (I use Void Linux so I was hoping its some configuration issue (so people smarter can help me) which from what i've read is what it seems to be).

All of the logs seem to have one thing in common:
```
:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
:err:winediag:nodrv_CreateWindow The explorer process failed to start.
```
I've looked this issue up to not much success and I also searched all the issues here but I couldn't really find anything that worked for me. Related issues seem to be: #5500, #5530, #5944, #4269 and most importantly #4266.

**Edit:** I forgot to mention that this is all on one ext4 partition, as that seemed to be an issue in some systems.

## Logs
[Superflight steam-732430.log](https://github.com/ValveSoftware/Proton/files/9632516/steam-732430.log)
[Post Void steam-1285670.log](https://github.com/ValveSoftware/Proton/files/9632521/steam-1285670.log)
[Ultrakill steam-1229490.log](https://github.com/ValveSoftware/Proton/files/9632525/steam-1229490.log)
[Steam sysinfo dump](https://github.com/ValveSoftware/Proton/files/9632536/sysinfo.log)
[lspci.log](https://github.com/ValveSoftware/Proton/files/9632547/lspci.log)
[vulkaninfo.log](https://github.com/ValveSoftware/Proton/files/9632552/vulkaninfo.log)
kernel cmdline: `root=PARTUUID=ef8...676 rw initrd=initramfs.img quiet intel_iommu=on iommu=pt`

## Notes
- Its interesting to note that i've ran Post Void and [Downwell](https://www.protondb.com/app/360740)(which also doesn't work because of the same reason) before on this machine. (Maybe some update has broken it? Not sure what though.)
- If it matters, I recently tried gaming in a virtual machine (via VFIO GPU passthrough in qemu) and I didn't see any real benefit to it other than learning how it works. The scripts I used for these are available [here](https://github.com/Skaytacium/.files/tree/msi/home/skay/vm)(qemu.sh is the entry point).
- I tried redirecting output from the game in launch options (`%command% &> ~/steam-log.txt`), but the file was blank.

**Comment by 2A4U** [comment]
[Here is a possible solve](https://github.com/ValveSoftware/steam-runtime/issues/533#issuecomment-1257092971) from issue 533 in Steam Runtime Soldier.

**Comment by RyuzakiKK** [comment]
I can't find any obvious error in your logs.

Can you please launch Steam with `STEAM_LINUX_RUNTIME_LOG=1` and upload the resulting log? You can find the instructions here https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information

Additionally, to iron out a possible regression, can you please switch "Steam Linux Runtime - Soldier" to the [previous_release](https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#using-a-beta-or-an-older-version) and test it again?

**Comment by Skaytacium** [comment]
Sorry for the inconvenience caused but I had to shift to Windows. If I ever shift to Linux again and get the same error i'll try this out. Thanks for the suggestions.
