### ISSUE TITLE
Hardspace Shipbreakers works but with 4+ min loading time

### ISSUE THREAD

**Issue by Navi-Professor** [ValveSoftware/Proton#6182]
# Compatibility Report
- Name of the game with compatibility issues: Hardspace Shipbreakers 
- Steam AppID of the game: 1161580

## System Information
Steam Deck
OS VER: 3.3.1
Os Build 20220817.1
Kernal ver: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3
- Proton version: Experimental,  7.0-4, 6.3-8 

## I confirm:
- [☑️] that I haven't found an existing compatibility report for this game.
- [☑️] that I have checked whether there are updates for my system available.

## Symptoms 
shipbreakers works, however it has a Excessive load time to get into the menu, between 3 ane 4 minutes before the main menu works.  

## Reproduction 
simply just launch the game, and wait.

**Comment by kisak-valve** [comment]
Hello @matthewv1998, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4007#issuecomment-1256643365.
