### ISSUE TITLE
太吾绘卷 The Scroll Of Taiwu (838350)  (正式版 official version)

### ISSUE THREAD

**Issue by tim110011** [ValveSoftware/Proton#6185]
# Compatibility Report
- Name of the game with compatibility issues: 太吾绘卷 The Scroll Of Taiwu
- Steam AppID of the game: 838350

## System Information
- GPU: GTX 750Ti
- Driver/LLVM version: nvidia 515.65.01
- Kernel version: 5.19.9
- Link to full system information report as [system_information.txt](https://github.com/ValveSoftware/Proton/files/9639784/system_information.txt)
- Proton version: Proton Experimental, Proton 7.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- (report https://github.com/ValveSoftware/Proton/issues/1545 is EA version issue.)
- [x] that I have checked whether there are updates for my system available.
[steam-838350.log.tar.gz](https://github.com/ValveSoftware/Proton/files/9639763/steam-838350.log.tar.gz)

## Symptoms 
-Game gets stuck at 90% loading
![taiwu_release](https://user-images.githubusercontent.com/8690917/192122867-0d40d51e-e218-4e21-9b87-a9af190dba61.jpg)

**Comment by kisak-valve** [comment]
Hello @tim110011, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1545#issuecomment-1257090779.
