### ISSUE TITLE
Raiden III Digital Edition (315670)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#6186]
# Compatibility Report
- Name of the game with compatibility issues: Raiden III Digital Edition 
- Steam AppID of the game: 315670

## System Information
- Steam Deck 512 gb
- Proton version: Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game seems to boot to the title fine, but silently exits to the game page when trying to start a game. According to protondb with the deck, it only runs on version 4.11-13, but some users on Linux computers have different results with other versions like 4.26 or 4.29. Deck rating is unsupported until this gets fixed.
[steam-315670.log](https://github.com/ValveSoftware/Proton/files/9639870/steam-315670.log)

## Reproduction
Start the game and let it go into the game demo or start a new game. It should crash right away.

**Comment by kisak-valve** [comment]
Hello @waspennator, it might be interesting to test how the game behaves with the game's launch options set to `PROTON_USE_WINED3D=1 %command%`.

**Comment by waspennator** [comment]
> Hello @waspennator, it might be interesting to test how the game behaves with the game's launch options set to `PROTON_USE_WINED3D=1 %command%`.

Tested it out with that command and that seems to fix it. Wined3d allows for one to actually start a game as well as making the in engine intro movie actually work. Dunno how much I can test after cause I suck at shmups though.

**Comment by kisak-valve** [comment]
Thanks, that isolates the issue to DXVK, which gained D3D9 support between Proton 4.11 and Proton 5.0. Can you mention this issue in the upstream DXVK issue tracker? (https://github.com/doitsujin/dxvk/issues)

**Comment by waspennator** [comment]
Disregard edits, it has been posted there.

**Comment by waspennator** [comment]
Still crashes when using dxvk with latest proton Experimental it seems.

**Comment by waspennator** [comment]
Update report, seems like the DXVK team finally got it fixed on their end, was able to get it working on my windows laptop with the latest dev build and apparently the fix had something to do with properly exposing MaxVertexBlendMatrixIndex, so either way, i'm assuming that whenever proton pulls in the dev build with the fix in question, I can close this issue report and someone can tell whoever's in charge of verifying games to retest this one.

**Comment by waspennator** [comment]
Proton Experimental seems to be using the version of DXVK with the fix now, tested it on deck and the game runs fine now, was able to beat the first level and the attract mode demo works too.

Closing report as the game now works fine out of the box, game is ready to be retested, should be ranked playable on deck now.
