### ISSUE TITLE
Warframe compatibility regression

### ISSUE THREAD

**Issue by Ninjastorm380** [ValveSoftware/Proton#6189]
# Compatibility Report
- Name of the game with compatibility issues: Warframe
- Steam AppID of the game: 230410

## System Information
- GPU: AMD RX 480
- Driver/LLVM version:  Mesa 22.1.7
- Kernel version: 5.19.11-zen1-1-zen (arch linux)
- Link to full system information report as [Gist](https://gist.github.com/Ninjastorm380/45565d9a0b9d3bd0874d2a5538b81125)
- Proton version:

## I confirm:
- [+] that I haven't found an existing compatibility report for this game.
- [+] that I have checked whether there are updates for my system available.

## Symptoms 
Compatibility regression in latest proton experimental. Game fails to bring up initial loading screen after starting from the launcher. last known working proton is 7.0-4

## Reproduction
attempt to launch warframe using proton experimental.

log: [steam-230410.log](https://github.com/ValveSoftware/Proton/files/9644683/steam-230410.log)

**Comment by kisak-valve** [comment]
Hello @Ninjastorm380, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/167#issuecomment-1257967215.
