### ISSUE TITLE
Game launches but doesn't display game window (252950)

### ISSUE THREAD

**Issue by Ahptt** [ValveSoftware/Proton#6194]
# Compatibility Report
- Name of the game with compatibility issues: Rocket League
- Steam AppID of the game: 252950
## System Information
- GPU: RTX 3080 FE
- Driver/LLVM version: nvidia 515.76-1
- Kernel version: 5.19.10-arch1-1
- Link to full system information report: https://gist.github.com/Ahptt/7cbd8454bacae2aac7c53e0e73c6a84c
- Proton version: Experimental, 7.0-4, 5.0-10, Steam Linux Runtime
- 
## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.
[steam-252950.log](https://github.com/ValveSoftware/Proton/files/9666434/steam-252950.log)
I have followed this issue and tried the remedies, still did not fix. https://github.com/ValveSoftware/Proton/issues/6076
I also created a post in the Arch Forums, but have not had any luck either. https://bbs.archlinux.org/viewtopic.php?id=279058

I have seen this post which mentions downgrading from the glibc 2.36 > 2.35, but I'm not looking to downgrade my packages, as it has been months since I've updated, and I have other packages on my system such as obs-studio that requires the glibc 2.36 package. (Along with this, Rocket League is not an EAC game) https://github.com/ValveSoftware/Proton/issues/6051

## Symptoms
Steam shows that the game is running, but no window is displayed with the game.

**Comment by kisak-valve** [comment]
Hello @Ahptt, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3521#issuecomment-1261118269.
