### ISSUE TITLE
Metal Gear Rising: Revengeance on Steam Deck in Desktop Mode

### ISSUE THREAD

**Issue by jukefr** [ValveSoftware/Proton#6198]
# Compatibility Report
- Name of the game with compatibility issues: Metal Gear Rising: Revengeance
- Steam AppID of the game: 235460

## System Information
- GPU: AMD RADV VANGOGH
- Driver/LLVM version: 22.1.99
- Kernel version: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3
- Proton version: 7.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-235460.log](https://github.com/ValveSoftware/Proton/files/9680847/steam-235460.log)

## Symptoms 

The game launches fine in Game Mode.
The game crashes on launch in Desktop Mode.

## Reproduction

1. Steam Deck on latest software and updates.
2. Install MGR.
3. Runs in Game Mode.
4. Crashes on launch in Desktop Mode.

I think this happens to every Steam Deck as I created a reddit post at first to ask and somebody else seems to be facing the exact same issue.

edit: seems to work with proton 5.0

**Comment by kisak-valve** [comment]
Hello @jukefr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/787#issuecomment-1263556454.
