### ISSUE TITLE
Cyberpunk 2077 (1091500) quest: life during wartime [bug - cannot kill last 2 drones]

### ISSUE THREAD

**Issue by deathxxx123** [ValveSoftware/Proton#6199]
# Compatibility Report
- Name of the game with compatibility issues: Cyberpunk 2077
- Steam AppID of the game: 1091500

## System Information
OS: Pop!_OS Linux 22.04 - kernel 5.19.0-76051900-generic
Mobo: Gigabyte X570S AORUS ELITE AX
CPU: AMD Ryzen 7 5800X3D
CPU Cooler: Noctua NH-D15 chromax.black
GPU: ASUS TUF GeForce RTX 3060 Ti - driver 515.65.01
RAM: Crucial Ballistix RGB 32 GB DDR4
- Proton version: Stable and Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Just cannot kill last 2 drones. It force me to get back in SUV and cannot shoot last 2 drones.
It's right about there in quest: https://youtu.be/Umr58NWVzAU?t=119
And there is right way to proceed with quest i expect: https://www.youtube.com/watch?v=cNtL8F5_9RM&t=130s

## Reproduction
Just play the game...

**Comment by deathxxx123** [comment]
I'm not sure if this is game bug or proton bug. But anyone else in youtube can kill this drones, the game gives them enough time.
But gives me about 2 seconds time or sometimes no time to kill them.

**Comment by deathxxx123** [comment]
It's happen exactly the same in Steam Deck with same save. Just cannot proceed and stuck in quest.

**Comment by deathxxx123** [comment]
I expect it's a game bug with some skill tree master i unlock. When someone detect me, i automatically get time slow and maybe that causes the bug with last 2 drones. Slow time forces me to get back in SUV .... i will reset my skill points and will test again without it.

**Comment by kisak-valve** [comment]
Hello @deathxxx123, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1263574043.
