### ISSUE TITLE
Mortal Kombat 11/Injustice 2 online fix

### ISSUE THREAD

**Issue by Catchal** [ValveSoftware/Proton#6203]
Mortal Kombat 11 and Injustice 2, among others, have online problems without a specific DLL replaced with a version from Microsoft. ucrtbase.dll. Also, Proton-GE has fixed the rest. I want this done in regular proton so MK11 and Injustice 2 can be Steam Deck Verified or Steam Deck Playable.

**Comment by kisak-valve** [comment]
Hello @Catchal, do you know exactly what Proton GE does differently with these two games compared to mainline Proton? Replacing a dll with a proprietary variant isn't a fix and is unmaintainable.

In general, this needs to be evaluated on a per-game basis. It's been noted on Mortal Kombat 11's compatibility report (#2594), but there's no specific note on the compatibility report for Injustice 2 (#1627).

**Comment by Catchal** [comment]
I don't know much about this stuff, and don't know how Proton-GE is different. I'm assuming protonfixes for MK11 and Injustice 2 I just want Mortal Kombat 11 and Injustice 2 to be Steam Deck Verified or Playable.

**Comment by kisak-valve** [comment]
Sorry, but protonfixes can't be used as a solution here because it's legally grey. The correct way forward is for ucrtbase in wine to improve so that no workaround is needed.

Feel free to add a note to #1627 that there's a ucrtbase specific quirk happening with the game.
