### ISSUE TITLE
Coromon

### ISSUE THREAD

**Issue by Fantasy1446** [ValveSoftware/Proton#6214]
Last version of Proton.
On steam deck , coromon's game afther 30 minutes of game the FPS down to 10/14 and the game Is unplayable.

**Comment by kisak-valve** [comment]
Hello @Fantasy1446, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5828#issuecomment-1267271616.
