### ISSUE TITLE
Super House of Dead Ninjas (224820)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#6216]
# Compatibility Report
- Name of the game with compatibility issues: Super House of Dead Ninjas
- Steam AppID of the game: 224820

## System Information
- Steam Deck 512 GB
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Checked on protondb and tested myself, despite being marked as playable, apparently something regressed from 6.3-8 because I'm noticing a frame time spike every few seconds on Experimental and 7.0.2 too. Kinda makes it harder to play as a result, considering its a twitchy arcade hack and slash kinda game.
[steam-224820.log](https://github.com/ValveSoftware/Proton/files/9718870/steam-224820.log)

Experimental: (Hard to tell via picture, but that spike happens every 1-3 seconds)
![download](https://user-images.githubusercontent.com/78768499/194159410-7705a016-ecdf-47f1-90dd-9713b4b8f8cc.jpeg)

6.3-8: (Stays smooth as silk, also the higher temps are from repeated testing.)
![download (1)](https://user-images.githubusercontent.com/78768499/194159471-8a2bb09f-f43a-4602-bc3a-f32949fe0e8f.jpeg)

## Reproduction
Start the game up with the mangohud overlay on and watch the frame time.

**Comment by alasky17** [comment]
@waspennator Thank you for the report!  We actually just pushed a performance regression fix for another game that in my testing seems to have fixed this game as well.  Currently, the fix is only on Experimental bleeding-edge, so you will need to select bleeding-edge under the Experimental beta branch options.  Please let me know if the performance regression persists for you with this new change :)

**Comment by waspennator** [comment]
I tried it and it seemed to be fixed initially, but after I tested a few games with similar issues (Out There Somewhere and Enemy Mind, they still have stutter issues) the stutter came back and persists even across multiple tests.

Yeah, I tried reinstalling the bleeding edge Experimental version and it made no difference, game still has the stutter issue.

**Comment by waspennator** [comment]
> @waspennator Thank you for the report! We actually just pushed a performance regression fix for another game that in my testing seems to have fixed this game as well. Currently, the fix is only on Experimental bleeding-edge, so you will need to select bleeding-edge under the Experimental beta branch options. Please let me know if the performance regression persists for you with this new change :)

Disregard my previous statement about it. Tried with the latest Experimental update and the game seems to be sticking at a stable steady 60 with no noticeable stutters. Gonna test out Enemy Mind and Out There Somewhere later too.

Edit: Tested out with all 3, games seem to be working fine now, closing since my main issue has been resolved.
