### ISSUE TITLE
LEGO Harry Potter Years 1-4 Requires Steamworks Common Redistributables to Run Correctly

### ISSUE THREAD

**Issue by reedlove** [ValveSoftware/Proton#6219]
# Compatibility Report
- Name of the game with compatibility issues: LEGO Harry Potter Years 1-4
- Steam AppID of the game: 21130

## System Information
- GPU:  NVIDIA Corporation NVIDIA GeForce GTX 960M/PCIe/SSE2
- Driver/LLVM version: 4.6.0 NVIDIA 515.65.01
- Kernel version: 5.15.0-48-generic
- Link to full system information report as [Gist](https://gist.github.com/): Nope
- Proton version: 7.0-4

## I confirm:
- [] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
If the "Steamworks Common Redistributables" are not installed, the installation script for the game will not install the needed DirectX and Visual C runtimes, resulting in a flashing screen with broken shaders and eventual system lock.

## Reproduction
- Fresh installation of Steam on Linux, enable "Steam Play for all other titles" and set it to "Proton 7.0-4".
- Install "LEGO Harry Potter Years 1-4"
- Run the game.

**Comment by reedlove** [comment]
Manually installing "Steamworks Common Redistributables" AppID 228980 will cause the install script to run.

**Comment by kisak-valve** [comment]
Hello @reedlove, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1920#issuecomment-1270773731.
