### ISSUE TITLE
central compatdata folder/pool for runtimes and launchers

### ISSUE THREAD

**Issue by nex86** [ValveSoftware/Proton#6220]
Well its known that Steam creates proton prefix folders under compatdata for each games, and all these folders mostly share the same identical files which contain dlls, runtimes, directx, launchers and much more which are just identical to other compatdata folder from other games.
Is all this redundancy necessary?  

I have have almost half of my internal 512GB SSD in my Steam Deck filled up with compatdata and shadercache (I know thats a different story), and 2 internally installed games, while the rest is stored across several SD cards.

but the more games I install on SD the less space I have on the internal SSD (which has around 21GB free atm)

So wouldn't it make sense to store all these redundant files in one central folder to save space?

**Comment by kisak-valve** [comment]
Hello @nex86, this issue is already being tracked at #4093 / #604 / https://github.com/ValveSoftware/steam-for-linux/issues/8587.

Closing as a duplicate.
