### ISSUE TITLE
Replace origin with ea app

### ISSUE THREAD

**Issue by senpl** [ValveSoftware/Proton#6223]
# Feature Request
Replace origin thin client with ea app. Ideally give users option to start ea app with steam coz turn it every time might not be what users want.

## I confirm:
- [ x] that I haven't found another request for this feature.
- [ x ] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description
Origin is slowly being replaced with ea app https://www.ea.com/en-gb/news/ea-app . This app should be default luncher for ea games.

## Justification [optional] 
More ea games will not work with time 

## Risks [optional]
Users that use origin might find problems with new app.

## References [optional] 
All ea games in future might be related.

**Comment by kisak-valve** [comment]
Hello @senpl, this doesn't seem right as a preemptive action taken by Proton devs. Windows users would be equally affected and EA needs to maintain their own games if that becomes a problem in the future,
