### ISSUE TITLE
Warriors Orochi 4 audio not playing in cutscenes 

### ISSUE THREAD

**Issue by VanishingBlaze** [ValveSoftware/Proton#6225]
# Compatibility Report
- Name of the game with compatibility issues: WARRIORS OROCHI 4
- Steam AppID of the game: 831560

## System Information
- Steam Deck
- Proton version: GE-Proton7-37

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
When playing cutscenes no audio is played. Just Silence 

## Reproduction 
If 1st playing the game start the game and a cutscene should play. If played before then go to gallery, then movies to play previously viewed cutscenes

**Comment by kisak-valve** [comment]
Hello @VanishingBlaze, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4000#issuecomment-1272412671.
