### ISSUE TITLE
Isolate the API libraries from the linux specifics (make additional code to replace native drivers on windows for dx9/11/12)

### ISSUE THREAD

**Issue by goofyseeker311** [ValveSoftware/Proton#6226]
Summary: make the isolated API translation libraries (non-os specific) clearly separately available.
Also, add Windows 10/11 driver interface install for windows 10/11 to disable manufacturer provided drivers and translate dx9/11/12 to Vulkan on windows. Why: shared efficient GPU graphics API translation codebase for all driver/GPU makers on any OS.

**Comment by kisak-valve** [comment]
Hello @goofyseeker311, DXVK is an independent project which you can find at https://github.com/doitsujin/dxvk. Supporting Windows as a host OS is not a design goal of Proton, but the individual translation layer might work for you.

Closing as out of scope for this project.

**Comment by goofyseeker311** [comment]
I expect valve quality, not random independent non-proton translation layers, maybe forking this.
