### ISSUE TITLE
Lotro - Mouse spins extremely fast when clicking to move camera angle

### ISSUE THREAD

**Issue by faptaincrunch** [ValveSoftware/Proton#6228]
# Compatibility Report
- Name of the game with compatibility issues: Lord of the Rings Online
- Steam AppID of the game: 212500

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 22.2/14.0.6
- Kernel version: 6.0
- Proton version: 7.0-4
- Ubuntu 22.04.1 Wayland
- https://gist.github.com/faptaincrunch/b623092b6a62c639be4920213be95698

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms  
On any proton version after 6.3-8 the mouse in lotro spins wildly when clicking on the screen and dragging the mouse to move/change camera angles. Version 6.3-8 and prior versions work as expected. Other user has same issue  [here](https://forums.lotro.com/forums/showthread.php?693557-Linux-wayland-erratic-mouse-input&s=7926dd4ed03a2a2825daf56ce5876681) and [here](https://steamcommunity.com/app/221410/discussions/0/3267934519718956030/) 

Reproduction

1. You can find the Steam AppID in the URL of the shop page of the game.
   e.g. for `The Lord of the Rings Online` the AppID is `212500`.
2. You can find your driver and Linux version, as well as your graphics
   processor's name in the system information report of Steam.
3. You can retrieve a full system information report by clicking
   `Help` > `System Information` in the Steam client on your machine.
4. Please copy it to your clipboard by pressing `Ctrl+A` and then `Ctrl+C`.
   Then paste it in a [Gist](https://gist.github.com/faptaincrunch/b623092b6a62c639be4920213be95698) and post the link in
   this issue.
5. Please search for open issues and pull requests by the name of the game and
   find out whether they are relevant and should be referenced above.

**Comment by kisak-valve** [comment]
Hello @faptaincrunch, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1816#issuecomment-1277648783.
