### ISSUE TITLE
Hired Ops (374280)

### ISSUE THREAD

**Issue by Faalagorn** [ValveSoftware/Proton#6229]
# Compatibility Report
- Name of the game with compatibility issues: Hired Ops
- Steam AppID of the game: 374280

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 22.2.1/14.0.6
- Kernel version: 6.0.1.zen1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Faalagorn/97ae8e82aaa856b119bce633dff6510b
- Proton version: experimental-bleeding-edge-7.0-26858-20221013-p9d6a87-wd9a000-d4bcabe-vf97edc

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-374280.log](https://github.com/ValveSoftware/Proton/files/9780079/steam-374280.log)

## Symptoms 
Game crashes with Proton Exerimental Bleeding edge updated today (2022-10-13) moment after getting into the match.

Proton Edge Experimental stable works, so it seems like regression.

## Reproduction
1. Launch the game.
2. Click Play.
3. Game should crash moments after loading.

**Comment by alasky17** [comment]
@Faalagorn Thank you for reporting this regression in bleeding-edge!  We are looking into how to fix it currently :)

**Comment by alasky17** [comment]
@Faalagorn This should be fixed in current bleeding-edge.  Please let me know if it is not resolved for you.

**Comment by Faalagorn** [comment]
> @Faalagorn This should be fixed in current bleeding-edge. Please let me know if it is not resolved for you.

Just tested, seems to work indeed! Out of curiosity, what was the issue here? Any link to the commit that fixed it maybe?
