### ISSUE TITLE
Guild Wars 2 (1284210)

### ISSUE THREAD

**Issue by logan001** [ValveSoftware/Proton#6233]
# Compatibility Report
- Name of the game with compatibility issues: Guild Wars 2
- Steam AppID of the game: 1284210

## System Information
- GPU: AMD APU
- Driver/LLVM version 14.0.6-3, mesa 22.2.1
- Kernel version: 5.19.14
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

i'll add a log next time the game crashes

## Symptoms 
game crashes randomly. 

## Reproduction
just play the game. sometimes the games runs find for 1-2 hours, sometimes it crashes in half an hour or less. with anet version under Lutris using wine from tkg i have no crashes.

the version from steam store works much better (fps) than the one from anet official page. i don't know why but an example is that i can play the game with best appearance with steam version compare to anet with average custom settings at the same fps or highers. also in crowded places its a huge difference. so the only problem is that the game crashes randomly.

edit: i've attached the log file. the game crashed when i open inventory for now. i think last time it crashed was on another window too.

[steam-1284210.log](https://github.com/ValveSoftware/Proton/files/9792234/steam-1284210.log)

**Comment by babattaja** [comment]
Hello, 
this may be unreleated, but i had this same problem while i was using "proton-TKG 7.16..." If plausible you could revert to "vanilla" kernel and try again.

**Comment by logan001** [comment]
i just did that. the game still crashed.
here is the log file
[steam-1284210.log](https://github.com/ValveSoftware/Proton/files/9813564/steam-1284210.log)

**Comment by alaborderie** [comment]
Hi everyone, I was playing without any issue yesterday but cannot start the game right now.

**EDIT: IT'S WORKING NOW**
**If you use arcdps and have the same issue remove it and restart the game. There was a gw2 update and arcdps made the game crash on start up**

On Steam using proton 7.0-4 and experimental (bleeding-edge) the game crashes after hitting the Arena Net launcher's "PLAY" button.
On older proton versions it crashes right before being able to login.

It's a Arena Net crash with logs being sent to them, saying:
```
Exception: c0000005  
Memory at address 00000001`42b15000 could not be read
App: Gw2-64.exe
```

Here is the steam log file in case it helps.
[steam-16279577183331024896.log](https://github.com/ValveSoftware/Proton/files/9833229/steam-16279577183331024896.log)

Not sure what is happening, nothing changed on my system I didn't even apt update / upgrade


EDIT: IT'S WORKING NOW
If you use arcdps and have the same issue remove it and restart the game. There was a gw2 update and arcdps made the game crash on start up

**Comment by Nuxmin** [comment]
The game works flawlessly. However, I've encountered a bug and I don't know if anyone else noticed about it. I'm using a Logitech G502 Hero mouse.

Just in case, I tried to run the game on Windows to try if my mouse was broken. On Windows it works with no issues. But somehow when I play on Linux through Proton there's a small issue that drives me crazy. If you press the wheel trying to use the button in a smooth way, it works as intended. If you do a stronger press on the wheel, for some reason the game gets you're pressing Mouse 3 and Mouse 4 at the same time.

It's not really something big, but it's a bothering issue. I've tried to look for a similar error on any other game and checked the log. But I don't see anything useful, so I'll post it here in case anyone notices what could be the cause.

[steam-1284210.log](https://github.com/ValveSoftware/Proton/files/9846961/steam-1284210.log)

**Comment by logan001** [comment]
im closing the issue. seems to work fine for the last 2 days. no crush anymore. maybe the update the other day fix something.

**Comment by Nuxmin** [comment]
> im closing the issue. seems to work fine for the last 2 days. no crush anymore. maybe the update the other day fix something.

Why closing it? The original issue is fixed but it still has the bug I wrote. And I think that only can be 1 issue x game : /. By the way, there could be more bugs we still aren't aware of.

**Comment by JoonasPitk** [comment]
> im closing the issue. seems to work fine for the last 2 days. no crush anymore. maybe the update the other day fix something.

This should be kept open for future issue reports.

**Comment by DerMax93** [comment]
For me both the standalone version (added to steam as external game) and the steam version crash after a somewhat random amount of time (~1h typically), always on a loadingscreen.
This sounds like that "memory leak" issue described here: https://en-forum.guildwars2.com/topic/22771-playing-guild-wars-2-on-linux-performance-optimizations-and-more/?do=findComment&comment=1742034 (5. in his list). If that is the case there really is not much proton can do to completely avoid it, however if there is a way to apply this "WINE_LARGE_ADDRESS_AWARE=1 " workaround to the steam+proton setup this could make it less annoying...

**Comment by kisak-valve** [comment]
Large address aware is enabled by default and has been for years.

**Comment by jake770321** [comment]
Potential workaround for the coherentUI crashes can be found here: https://twitter.com/that_shaman/status/1577651492617699331

I've just played for around 3 hours without a single crash so it's definitely fixed it for me. (I'd be lucky to make it past an hour previously.)

Edit: I should add that make sure this goes after %command% if you have any other launch options set.

**Comment by nyannyankas** [comment]
Unfortunately it seems like one of the latest _bleeding-edge_-versions broke this game completely. 

Once the game is launched, it is reported as running by Steam, but nothing else happens.

The update must have happened a day or two ago.

The proton log of the broken version ([steam-1284210-bleeding-edge.log](https://github.com/ValveSoftware/Proton/files/10746070/steam-1284210-bleeding-edge.log)) shows the line `00c0:00c4:err:sync:RtlLeaveCriticalSection section 00007FD67243BA60 is not acquired` over and over again, while it doesn't appear at all when disabling the _bleeding-edge_-version of Proton Experimental (example log of the game running fine: [steam-1284210.log](https://github.com/ValveSoftware/Proton/files/10746071/steam-1284210.log)).

It would be much appreciated if someone with more knowledge about Proton could look into a fix for this. :)

Edit: Forgot to mention: I've tested this on my Desktop as well as on my Steam Deck, so it doesn't seem to be a issue related to my PC.
