### ISSUE TITLE
Need for Speed™ Heat, OriginThinSetup problem

### ISSUE THREAD

**Issue by septemba** [ValveSoftware/Proton#6236]
# Compatibility Report
- Name of the game with compatibility issues: Need for Speed™ Heat
- Steam AppID of the game: 1222680

## System Information
- GPU: GTX 1650Ti Mobile
- Driver/LLVM version: nvidia 515.76
- Kernel version: 6.0.1-zen2-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/septemba/3dd100ecfd1901af44cba8c19894b7f6
- Proton version: 7.0-4

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.
 
## Symptoms 
OriginThinSetup black window (https://imgur.com/a/SC0bdFM)
The window seems to function but it's not that useful since i can't see what i am clicking

## Reproduction
Launch Game

[steam-1222680.log](https://github.com/ValveSoftware/Proton/files/9794657/steam-1222680.log)

**Comment by kisak-valve** [comment]
Hello @septemba, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3955#issuecomment-1279972804.
