### ISSUE TITLE
Geometry dash performance issues

### ISSUE THREAD

**Issue by GRBL-F** [ValveSoftware/Proton#6239]
# Compatibility Report
- Name of the game with compatibility issues: Geometry Dash
- Steam AppID of the game: 322170

## System Information
- GPU:  RTX 3060ti
- Driver/LLVM version:  nvidia 515.76/520.56 (both of these driver versions have the issue)
- Kernel version:  6.0.2
- Link to full system information report as [Gist Here](https://gist.github.com/Agreeable-f/4bf8ecd35f3fded972d01d007691d459):
- Proton version: 6.3-8, 7.0-4, GE 7-37

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game feels like it's running at a much lower framerate than is being rendered. for example the game is rendering 144fps but feels like it's running at 30 (possibly just a quirk of how geometry dash was developed but doesn't happen on native windows
[steam-322170.log](https://github.com/ValveSoftware/Proton/files/9803738/steam-322170.log)
).

## Reproduction

just play geometry dash. it'll happen.

**Comment by kisak-valve** [comment]
Hello @Agreeable-f, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5304#issuecomment-1281392941.
