### ISSUE TITLE
[incorrect behavior] Closing a cmd window kills programs launched by it

### ISSUE THREAD

**Issue by Worldwidebrine** [ValveSoftware/Proton#6244]
# Compatibility Report

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Closing a cmd window kills all processes launched by it.
On Windows, closing cmd doesn't cause anything.

## Reproduction
1. Open cmd.exe;
2. Execute command `explorer.exe` or any other GUI program;
3. Confirm that explorer is launched;
4. Close cmd.exe

Result:
explorer is killed.

Expected Result:
explorer is not killed.

**Comment by kisak-valve** [comment]
Hello @Worldwidebrine, this is behavior inherited from upstream wine. Reproduce this issue with vanilla wine and report the issue to https://bugs.winehq.org if it hasn't been already.
