### ISSUE TITLE
TrackMania Nations Forever crashes trying to load large maps, e.g. 128³ Deep Fear

### ISSUE THREAD

**Issue by qwertychouskie** [ValveSoftware/Proton#6247]
# Compatibility Report
- Name of the game with compatibility issues: TrackMania Nations Forever
- Steam AppID of the game: 11020

## System Information
- GPU: Nvidia RTX 3060 Mobile
- Driver/LLVM version: `nvidia-driver-515 515.76-0ubuntu1`
- Kernel version: 5.19.0.21.21
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Latest Experimental (also tested with regular version)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-11020.log](https://github.com/ValveSoftware/Proton/files/9825197/steam-11020.log)

## Symptoms 

The game crashes trying to load very large maps, e.g. 128³ Deep Fear

## Reproduction

 - Download map (https://tmnf.exchange/trackshow/6294984) and place it in `~/.steam/steam/steamapps/compatdata/11020/pfx/drive_c/users/steamuser/Documents/TrackMania/Tracks/Challenges/`
 - Launch game
 - Try to load map

**Comment by kisak-valve** [comment]
Hello @qwertychouskie, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/467#issuecomment-1284749472.
