### ISSUE TITLE
BrawlHalla : Doesn't lauch / Was working yesterday

### ISSUE THREAD

**Issue by feydreva** [ValveSoftware/Proton#6257]
# Compatibility Report
- Name of the game with compatibility issues: BrawlHalla
- Steam AppID of the game: 291550

## System Information
- GPU: AMD Radeaon RX 6600 XT
- Driver/LLVM version: Mesa 22.2.1
- Kernel version: 6.02-zbe1-1-zen (64-bit)
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/feydreva/c6196266fa1f80dd4684ce7f4093187a
- Proton version: Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Game doesnt lauch
Game worked OK yesterday, but not today.
After system upgrade, same issue
Ran steam-runtime reset : same issue
[steam-291550.log](https://github.com/ValveSoftware/Proton/files/9844152/steam-291550.log)

tested proton experimental and proton 7.0, same issue

## Reproduction
Run game, happens every time

**Comment by kisak-valve** [comment]
Hello @feydreva, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/83#issuecomment-1287775756.
