### ISSUE TITLE
MIR4 issue (Non-Steam Launcher)

### ISSUE THREAD

**Issue by M4rQu1Nh0S** [ValveSoftware/Proton#6261]
# Compatibility Report
- Name of the game with compatibility issues: MIR4

## System Information
- GPU: Nvidia GTX 1050ti 4GB
- Driver/LLVM version: nvidia 510.85.02
- Kernel version: 5.19.0-21-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/M4rQu1Nh0S/517f861361a08f627f3a9fb13698cedf
- Proton version: 1665575168 experimental-7.0-20221012

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

The game crashes with Proton running as Windows 10 Mode. with error in log: 

`Backtrace:
=>0 0x000000025d7419eb DwmIsCompositionEnabled+0x5b() in dwmapi (0x000000000335c050)
0x000000025d7419eb dwmapi+0x19eb: movl	%eax,(%rbx)`

But running the game with Proton as Windows XP work, but chromium embedded framework (CEF) not work in Windows XP mode and i can't login.

## Reproduction

Install the game from official launcher (https://live-dl.mir4global.com/global-launcher/Mir4Launcher_Install.exe)
Open the launcher and execute game 1.

MIR4 steam version freezes after some seconds after open the game.

Fixing the issue DwmIsCompositionEnabled can at last makes the MIR4 funtional.

**Comment by kisak-valve** [comment]
Hello @M4rQu1Nh0S, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5405#issuecomment-1287901197.
