### ISSUE TITLE
GTA IV: Colour flickering on Proton Experimental

### ISSUE THREAD

**Issue by lukelmy** [ValveSoftware/Proton#6265]
# Compatibility Report
- Name of the game with compatibility issues: Grand Theft Auto IV: The Complete Edition
- Steam AppID of the game: 12210

## System Information
- GPU: AMD 6900 XT
- Driver/LLVM version: AMDGPU stack 22.20
- Kernel version: 5.15.0
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When starting game with Proton Experimental, colour flickering can be observed. However, images are normal when using Proton 7.0-4. The problematic shader module is found with Renderdoc. If NAN judgement is added before extended instruction NMin(or NClamp) instead of only NMin(or NClamp) in the spirv-dis of problematic shader module, the image is normal. Guessing it's a SPIR-V generated issue.

![colour_flickering](https://user-images.githubusercontent.com/116545142/197479802-b2295d71-7377-4def-ac84-eea789fe573e.jpg)

The original spirv-dis and the modified spirv-dis of the problematic shader module on Proton Experimental are listed as follows:
[spv_pass.txt](https://github.com/ValveSoftware/Proton/files/9849964/spv_pass.txt)
[spv_fail.txt](https://github.com/ValveSoftware/Proton/files/9849967/spv_fail.txt)

## Reproduction
- Start a new game

**Comment by mbriar** [comment]
This is expected if you use the proprietary vulkan driver, which does not support VK_EXT_attachment_feedback_loop_layout (yet?). It shouldn't happen with RADV, which is also the recommended driver for proton in general.

**Comment by kisak-valve** [comment]
Hello @lukelmy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/350#issuecomment-1289037251.
