### ISSUE TITLE
Red Dead Redemption 2 won't boot on AMD graphics

### ISSUE THREAD

**Issue by dklementowski** [ValveSoftware/Proton#6266]
# Compatibility Report
- Name of the game with compatibility issues: Red Dead Redemption 2
- Steam AppID of the game: 1174180

## System Information
- GPU: AMD RX 6700XT
- Driver/LLVM version: Mesa 22.2.1
- Kernel version: 6.0.2
- Link to full system information report as [Gist](https://gist.github.com/): 
https://gist.github.com/dklementowski/91c16a142a2dffd82018be645eed4c95
- Proton version: 7.0-4, 6.3-8, Experimental, GE-7-26

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

[steam-1174180.log](https://github.com/ValveSoftware/Proton/files/9853205/steam-1174180.log)

## Symptoms
Rockstar Games Launcher installs, launches just fine, when it's done starting, nothing more happens, the launcher disappears and the game in Steam is fully stopped (can be launched again).

I changed my GPU recently and I never succeed in running that game, but I don't think it's something with configuration on my end, as my games generally work very well, whether it's Vulkan, D3D11 or D3D12. I use RADV driver with just regular Arch Linux Mesa packages. Previously I used NVIDIA RTX 3060Ti and the game worked (with issues). I tried reinstalling it completely, removing prefix directory many times, using different proton versions, using mesa-git. The effect is the same every time.

## Reproduction
Install RDR2 while using RX 6700XT, try to launch it

**Comment by kisak-valve** [comment]
Hello @dklementowski, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-1289290776.
