### ISSUE TITLE
Proton games not working in new install

### ISSUE THREAD

**Issue by alosarjos** [ValveSoftware/Proton#6267]
Just installed Arch on a new drive this weekend, was gonna play but no Proton games are working, at best I get a black screen and a popup to force exit.

Have tested with Beta and Stable client. Also tried disabling the shader pre-caching.

Proton Experimental

I don't see anything in the PROTON_LOGS. For example, from Condemned 2:

[steam-4720.log](https://github.com/ValveSoftware/Proton/files/9855431/steam-4720.log)

Arch Linux + Gnome Wayland + Linux 6.0.2 + mesa 22.2.1

**Comment by kisak-valve** [comment]
Hello @alosarjos, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by deathxxx123** [comment]
I see you have something wrong with RLIMIT_NICE is less than 20.
And ofcource, i'm not sure if that is because Wayland.
Try with Xorg.

**Comment by alosarjos** [comment]
There you go @kisak-valve 

https://gist.github.com/alosarjos/1e84f8de6ad7d959456886c319487b13

**Comment by alosarjos** [comment]
In case it helps, another log for Cult of the lamb, another game I was playing before

[steam-1313140.log](https://github.com/ValveSoftware/Proton/files/9857176/steam-1313140.log)

**Comment by kisak-valve** [comment]
Thanks, unfortunately no decent hints there. Your system information looks healthy minus va-api and I'm not seeing how those two games are actually failing. There's something subtle going on here or the issue is outside of Proton.

Blind guess, what is `/usr/local/bin/mesa-git-run` and does running Steam with `steam-runtime` from a terminal so that it is not involved have any effect on Proton?

**Comment by alosarjos** [comment]
@kisak-valve Is to test mesa-git with Steam. From here: https://gist.github.com/Venemo/a9483106565df3a83fc67a411191edbd

PD: Getting same results running directly steam-runtime without it.


To be honest I'm not sure either what's going on. If I'm missing some package or what. The system is behaving a bit strange. This morning trying to run AC: Origins, the game wouldn't install uPlay on the prefix, giving an error saying it could not locate it. Now after some trial and error seems to work.

Also, I'm trying to play Cult of the Lamb, bit the Devolver digital video intro is showing the test-video (Color bars and such). Do I need any specific package for that to work?


 pacman -Qe |grep mesa
mesa 22.2.1-1
lib32-libva-mesa-driver 22.2.1-1
lib32-mesa 22.2.1-1
libva-mesa-driver 22.2.1-1

pacman -Qe |grep vulkan
lib32-vulkan-radeon 22.2.1-1
vulkan-radeon 22.2.1-1

**Comment by alosarjos** [comment]
Welp... Seems I could fix it... Just did a pacman -Qe on the Steam Deck and started installing all the packages I saw there I thought I didn't need (xf86-video-amdgpu, mesa-vdpau,...) Now everything kinda seems to work.

I guess that for the full steam + Proton package more dependencies are required for Arch that the ones Steam has for itself

**Comment by kisak-valve** [comment]
Glad to hear you got it working. If you're able to narrow down which system package was missing, then that would be something to relay to Arch's package maintainer(s) for their Steam package.

Closing because this was a system config issue.
