### ISSUE TITLE
Problem launching S.T.A.L.K.E.R.: Clear Sky

### ISSUE THREAD

**Issue by dionixs** [ValveSoftware/Proton#6268]
# Compatibility Report
- Name of the game with compatibility issues: S.T.A.L.K.E.R.: Clear Sky
- Steam AppID of the game: 20510

## System Information
- GPU: NVIDIA GeForce GTX 1050 Ti
- Driver/LLVM version: NVIDIA 520
- Kernel version: 5.4.0-131-generic
- Link to full system information report as [Gist](https://gist.github.com/): [link](https://gist.github.com/dionixs/f77d98a34878973bcadaa8307e556c23)
- Proton version: proton-7.0-4

## Symptoms
Attempting to start the game opens an error window with the message: 'Your video card doesn't meet game requirements pixel shaders v1.1 or higher required'

## Reproduction
Attempting to start the game opens an error window with the message: 'Your video card doesn't meet game requirements
Pixel Shaders v1.1 or higher required'

[steam-20510.log](https://gist.github.com/dionixs/7334cbdc0e846340fbc21e5964cc1942)

**Comment by kisak-valve** [comment]
Hello @dionixs, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1166#issuecomment-1290557726.
