### ISSUE TITLE
Bioshock Remastered - Steam Deck

### ISSUE THREAD

**Issue by xfechx** [ValveSoftware/Proton#6269]
Bioshock 1 HD version (Remastered) is listed as playable on Steam Deck (Proton 7) while it does not work at all. I have tried Proton 7, 6 and Experimental versions of it.

**Comment by kisak-valve** [comment]
Hello @xfechx, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/399#issuecomment-1290635989.
