### ISSUE TITLE
FFXIV Freezes when Real Time Reflections are enabled

### ISSUE THREAD

**Issue by ulzeraj** [ValveSoftware/Proton#627]
Final Fantasy 14 (ID: 39210) works on DX11 mode after some manual workarounds which are editing the INI files to set browser type to 2, disable the opening cutscene and use winetricks xact into its prefix.

However… graphics stop working immediately after I enable “Real Time Reflections”. Enabling any level of this particular option freezes the game and X11. I can still log into through SSH and there are these messages:

[  384.698959] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, last signaled seq=202749, last emitted seq=202751
[  384.698964] [drm] GPU recovery disabled.

GPU is Saphire R9 390. System is OpenSUSE Tubleweed with kernel 4.18.0-1, using amdgpu and Mesa 18.1.6 LLVM6. Same hardware and game works fine on Windows 10 with Real Time Reflections on.

Thanks for the hard work.

**Comment by doitsujin** [comment]
Please test with LLVM 7 and Mesa 18.2, as suggested in [PREREQS.md](https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md).

**Comment by HereInPlainSight** [comment]
System info: Gentoo x86_64 | 4.14.65-gentoo | i5-6500 | NVIDIA GeForce GTX 1070 | NVIDIA 396.51

I had previously done the config file edits, just emerged llvm7 and added the xact winetricks to the prefix, switched to DX11 and can confirm I'm able to run with Real Time Reflections at any setting I want.

**Comment by doitsujin** [comment]
@HereInPlainSight The LLVM version is only relevant for AMD drivers because they use LLVM to compile shaders. Mesa needs to be built against LLVM 7 in order to work correctly.

**Comment by HereInPlainSight** [comment]
@doitsujin I wasn't 100% on that because the [DirectX11 info](https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md#directx-11-games) seems to indicate that LLVM7 is recommended to avoid GPU hangs, which is mentioned after the drivers section.  My gaming on Linux before the new SteamPlay info was fairly casual, so I opted to go safe over sorry.

**Comment by kisak-valve** [comment]
Hello @ulzeraj, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/580#issuecomment-416064574.
