### ISSUE TITLE
Dusk won't boot on steam deck despite it being steam deck verified

### ISSUE THREAD

**Issue by Zellagooey** [ValveSoftware/Proton#6273]
I redownloaded, viewed integrity of the games files, all it does is crash on my steam deck

**Comment by Blisto91** [comment]
Have you forced it to use Proton or is it the native version you are having issues with?

**Comment by kisak-valve** [comment]
Hello @Zellagooey, DUSK (519860) is a native linux game and is not using Proton on the Steam Deck by default.

I have forwarded this feedback, but this is also invalid for the Proton project and won't be tracked here.

If you've manually set the per-game override to Proton, then please add this feedback to #198.
