### ISSUE TITLE
DOOM becomes black when minimized

### ISSUE THREAD

**Issue by gianmarcogg03** [ValveSoftware/Proton#6274]
# Compatibility Report
- Name of the game with compatibility issues: DOOM
- Steam AppID of the game: 379720

## System Information
- GPU: RX 580
- Driver/LLVM version: amf-amdgpu-pro 22.10_1395274-1
- Kernel version: 6.0.2-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/gianmarcogg03/86382f45339b187f14f3d13313a203c9
- Proton version: GE_Proton7_37-1

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-379720.log](https://github.com/ValveSoftware/Proton/files/9890625/steam-379720.log)

## Symptoms 
When I unfocus from the game window, doesn't matter if in fullscreen or not, or whether I'm in a menu or in the game itself, it minimizes and when I restore it, the window is all black with no audio and all I can do is force quit the game.

## Reproduction
Open the game and Alt+Tab out of it or try clicking on another window, then restore it from the minimized state.

**Comment by kisak-valve** [comment]
Hello @gianmarcogg03, this issue is already being tracked at #583, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/583#issuecomment-1295274356.
