### ISSUE TITLE
Unable to login to any EA desktop game.

### ISSUE THREAD

**Issue by Bitwolfies** [ValveSoftware/Proton#6275]
With the new rollout of EA Desktop, all games that used Origin have been converted. The issue is that, while the login screen loads just fine, and you can even click where the inputs should be, but they don't render.
![Screenshot_20221028_140453](https://user-images.githubusercontent.com/65789901/198732714-73f6bddb-febd-43d9-ab33-c2b90836f1f2.png)
This makes logging into any EA Desktop game impossible, unless you wish to feel your way through it. This happens not only on my Deck but my normal Arch install with a GTX3080.

Using Wines Virtual desktop does not fix the issue, nor does using wined3d.

**Comment by Bitwolfies** [comment]
Update,[this reddit thread](https://www.reddit.com/r/SteamDeck/comments/yf2nsb/comment/iu1e10c/?context=3) has a solution, it works.      

- Select Install a Windows dll or component >> d3dcompiler_47
- Select Install a font >> liberation font

Might have to add a workaround for all EA Desktop games.

**Comment by robotman40** [comment]
This really needs to be fixed ASAP. This has essentially borked all EA games. (Aside from the ones that don't use Origin/EA App)

**Comment by Bitwolfies** [comment]
Looks like the newest bleeding edge fixed it.
