### ISSUE TITLE
Crossout crashing with `stack smashing detected`

### ISSUE THREAD

**Issue by vars1ty** [ValveSoftware/Proton#6278]
# Compatibility Report
- Name of the game with compatibility issues: Crossout
- Steam AppID of the game: 386180

## System Information
- GPU: MSI GeForce RTX 3070 TI
- Driver/LLVM version: 520.56.06
- Kernel version: 6.0.5
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/vars1ty/d17023663ad7f346cb26ccfd66f842e3
- Proton version: 7.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
    - There is one, but it doesn't relate to this specific issue.
- [x] that I have checked whether there are updates for my system available.

Log: https://gist.github.com/vars1ty/3520dfe0b103578daa67522bfd0bcd63

## Symptoms
The game fails to launch 9,5/10 of the times, ending up with errors like `stack smashing detected`.
I have also tried running it with Wine-GE and various different Proton versions (+ GE), none which were stable.
The only thing that has worked at times was running it through Bottles, setting the synchronization to FSync. But even with that, it only lasts a handful of minutes before crashing again.

## Reproduction
1. Install Crossout
2. Launch the game
3. Watch it crash most of the time

### Edit
I've also gotten it confirmed by someone else that it occurs for them too, and not just me. Their distro is Kubuntu.

**Comment by kisak-valve** [comment]
Hello @vars1ty, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1937#issuecomment-1295836286.
