### ISSUE TITLE
The Outlast Trials Closed Beta (2126550)

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/Proton#6279]
# Compatibility Report
- Name of the game with compatibility issues: The Outlast Trials
- Steam AppID of the game: 2126550

## System Information
- GPU: AMD Radeon 6900XT
- Driver/LLVM version: [Mesa 22.3-git](https://gitlab.freedesktop.org/mesa/mesa/-/commit/3f282b54fa305e3ae22490b02dd7aa91f88f59ce)/15.0.0
- Kernel version: 6.1-rc2
- Link to full system information report as [gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)
- Proton version: experimental-bleeding-edge-7.0-27365-20221020-p082fae-wd1dbda-de311f2-v27072c

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2126550.log](https://github.com/ValveSoftware/Proton/files/9896690/steam-2126550.log)
[steam-2126550-01.log](https://github.com/ValveSoftware/Proton/files/9896716/steam-2126550-01.log)
[steam-2126550-02.log](https://github.com/ValveSoftware/Proton/files/9896717/steam-2126550-02.log)

## Symptoms 
1. The game randomly stucks (picture freezes, sound continues played)
Reproduction - random
![Screenshot from 2022-10-31 00-48-42](https://user-images.githubusercontent.com/200750/198898650-d2f1d33c-6ca5-4e13-b981-67e906e57c82.png)

2. On AMD Radeon 6800M (on AMD Radeon 6900XT I not observed this) on picture appears artifacts in the form of multi-colored glare
Reproduction - always
![Screenshot from 2022-10-31 00-36-55](https://user-images.githubusercontent.com/200750/198898315-3a1265cb-4ba3-4978-bdc3-6b43ec0da250.png)

**Comment by hakzsam** [comment]
@NTMan Does RADV_DEBUG=nodcc fix it?

**Comment by hakzsam** [comment]
This issue should be fixed in Mesa main now https://gitlab.freedesktop.org/mesa/mesa/-/commit/06adf6ad117e92a832c5073326bd83b638b3ca37.

**Comment by NTMan** [comment]
> This issue should be fixed in Mesa main now https://gitlab.freedesktop.org/mesa/mesa/-/commit/06adf6ad117e92a832c5073326bd83b638b3ca37.

![image](https://user-images.githubusercontent.com/200750/200255917-52306acb-fa5f-4362-b66c-7609c4e14052.png)
Unfortunately I don't know how to check now. Testing is over :( .

**Comment by hakzsam** [comment]
Given the problem, I'm pretty sure it's fixed now anyways.

**Comment by kisak-valve** [comment]
Thanks for the pre-release closed beta testing @NTMan and @hakzsam.

Since it appears that this closed beta has run its course and is no longer available, I think we're done here. When the full game release becomes available, please open a new compatibility report with any new feedback for that appid.
