### ISSUE TITLE
Off-topic fire test for D3D11 support

### ISSUE THREAD

**Issue by kode54** [ValveSoftware/Proton#628]
If you want something to try to overload the D3D11 implementation to fire test any missing features, look no further than the #1 PC Demo from Assembly 2018, Number One/Another One, by Carillon & Cyberiad & Fairlight. It's powered by their commercial demo production software, and uses so many Direct3D 11 features and shader bits, it doesn't even run on either Proton 3.7 or wine-staging. And boy, does it spew out a huge load of warnings almost nonstop.

http://www.pouet.net/prod.php?which=77399

Should rank higher up there at random features that nobody has documented yet, compared to getting 3DMark running. At least, I guess. I'm not really sure if it'll be all that useful, but I'd sure love to be able to see it running in a version of Wine some day.

**Comment by kisak-valve** [comment]
Hello @kode54, I'm going to close this because this is informational and it's not specifically actionable.
