### ISSUE TITLE
Plants VS Zombies Battle For Neighborvile

### ISSUE THREAD

**Issue by TroubledPerson** [ValveSoftware/Proton#6282]
# Compatibility Report
- Name of the game with compatibility issues: Plants VS Zombies Battle For Neighborvile
- Steam AppID of the game: 1262240

## System Information
- GPU: NVIDIA Corporation Device 2482 or 3070ti
- Driver/LLVM version: nvidia-driver-520 Version 520.56.06-0ubuntu0.20.04.1 NVIDIA driver metapackage
- Kernel version: 5.4.0-128-generic
- https://gist.github.com/NeedsArt/f788a1f504e98763ad0c9738cb4f0cab
- Proton version: Experimental + 7.0 - 4
- OS Linux Mint 20.3 Cinnamon

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Log = https://drive.google.com/file/d/1DZxasQq2vC8c48aIQ_qNnLbHRjz8dPUi/view?usp=share_link)

## Symptoms
![Screenshot from 2022-10-28 12-46-20](https://user-images.githubusercontent.com/89006981/199168158-2787fdda-a8eb-41ce-9542-d720c2a4349f.png)

## Reproduction

use an ubuntu based OS 
use commands DXVK_HUD=1 PROTON_USE_WINED3D=1 PROTON_NO_FSYNC=1 %command%
should come up with the direct x error
-->

**Comment by kisak-valve** [comment]
Hello @NeedsArt, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4978#issuecomment-1298443674.
