### ISSUE TITLE
The witcher enhanced edition won't start

### ISSUE THREAD

**Issue by fbenedett** [ValveSoftware/Proton#6283]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher enhanced edition
- Steam AppID of the game: 20900

## System Information
- GPU: NVIDIA GeForce RTX 3050 Laptop GPU
- Driver/LLVM version: Driver Version: 520.56.06
- Kernel version: 5.15.0-52-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:
Experimental
7.0-4
and I tried many others

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-20900.log](https://github.com/ValveSoftware/Proton/files/9912901/steam-20900.log)

## Symptoms 
The game does NOT launch at all.

**Comment by kisak-valve** [comment]
Hello @fbenedett, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/255#issuecomment-1298960202.
