### ISSUE TITLE
All games played using Tahiti GPU with amdgpu support enabled have no cursor

### ISSUE THREAD

**Issue by atrauzzi** [ValveSoftware/Proton#6284]
I'm on a Linux system using a Radeon HD 7900 (Southern Islands) series video card with the `amdgpu` kernel drivers via: `amdgpu.dc=0 radeon.si_support=0 amdgpu.si_support=1 radeon.cik_support=0 amdgpu.cik_support=1`.

I'm attempting to run various games using both Proton via Steam as well as games through Bottles and its Proton-based runners.  It appears as though regardless of which games I run, none of them have a working cursor when fullscreen.  When I switch to windowed mode (where supported), I get the games cursor.  Other visuals in the game seem fine, it's *only* the mouse cursor that never seems to show up.

Of course, if I play natively supported games, I get a cursor when playing full screen.  It just seems like any version of Proton that I can get my hands on doesn't result in me being able to have a cursor while running full screen.

Other details:

 - Fedora 36
 - Wayland

**Comment by kisak-valve** [comment]
Hello @atrauzzi, this reads like an issue in the video driver render stack and should also be mentioned to your video driver vendor.

**Comment by atrauzzi** [comment]
It's hard to say if it is given that my mouse cursor works in non proton games.

It's only when using proton that any games don't have a cursor.

**Comment by Blisto91** [comment]
Could you post a proton log from a game with the behavior? 🙂

**Comment by atrauzzi** [comment]
Definitely, would you happen to have a guide for doing this or can you provide me the steps here?

**Comment by atrauzzi** [comment]
Hey @Blisto91 & @kisak-valve 

Here are some logs for a variety of games.  Each log is generated by running the game and then closing using alt-f4 or estimating where the mouse cursor is based on UI animations and highlights. :laughing: 

[hades-steam-1145360.log](https://github.com/ValveSoftware/Proton/files/9933677/hades-steam-1145360.log)
[supreme-commander-steam-40100.log](https://github.com/ValveSoftware/Proton/files/9933679/supreme-commander-steam-40100.log)
[warzone-2100-windows-steam-1241950.log](https://github.com/ValveSoftware/Proton/files/9933681/warzone-2100-windows-steam-1241950.log)
[songs-of-conquest-steam-867210.log](https://github.com/ValveSoftware/Proton/files/9933685/songs-of-conquest-steam-867210.log)

Each game demonstrates the no-cursor issue when played full screen.

**Comment by atrauzzi** [comment]
Update: I've also opened a bug over at the Fedora issue tracker: https://bugzilla.redhat.com/show_bug.cgi?id=2139967

Feel free to comment over there if there's any additional details that might be worth adding.

**Comment by atrauzzi** [comment]
Interesting, I just did another test with Cities Skylines and the cursor is missing there as well.  So yeah, probably a kernel issue.

**Comment by Blisto91** [comment]
> Definitely, would you happen to have a guide for doing this or can you provide me the steps here?

Oh yea sorry i forgot to reply back

**Comment by belenos** [comment]
I am experiencing the same issue. The kernel boot parameter `amdgpu.dc=0` disables DDC/CI, which fixes a screen flickering and a lock screen bugs that I have on my HDMI monitor, but then introduces this problem with the cursor on fullcreen

**Update:** Okay, so I installed [this extension](https://extensions.gnome.org/extension/1873/disable-unredirect-fullscreen-windows/) on Gnome and it fixed it.

The extension is described as "Disables unredirect fullscreen windows in gnome-shell to workaround https://bugzilla.redhat.com/show_bug.cgi?id=767397 and https://bugzilla.gnome.org/show_bug.cgi?id=738719". I hope it helps.
