### ISSUE TITLE
After Proton-7.0 my multiseat gameplay issue is fixed. Thank you!

### ISSUE THREAD

**Issue by salihmarangoz** [ValveSoftware/Proton#6285]
Hello,

I set up my system as shown in my blog: https://salihmarangoz.github.io/blog/Easy-Multiseat-Configuration-With-Laptop/

Also here is my setup:

![configuration_diagram](https://user-images.githubusercontent.com/12991962/199610921-168dd435-2150-41ea-a674-708f8995f43d.png)

I was unable to set up a multiseat configuration without going into trouble with xorg settings etc. This configuration was messed up after Proton 5 or 6 but now it is working again with Proton Experimental and Proton-GE >7.0 versions. 

I really don't know what is changed but it works now. Thank you!

**Comment by kisak-valve** [comment]
Closing as invalid because it appears there is no issue to ponder here.
