### ISSUE TITLE
Dungeons & Dragons Online (206480)

### ISSUE THREAD

**Issue by vpfeiffer** [ValveSoftware/Proton#6287]
# Compatibility Report
- Name of the game with compatibility issues: Dungeons & Dragons Online
- Steam AppID of the game: 206480

## System Information
- GPU: AMD Radeon RX 6800 XT
- Driver/LLVM version: Mesa 22.0.4
- Kernel version: 5.10.95
- Link to full system information report as [Gist](https://gist.github.com/vpfeiffer/4842d6df6c5a0dc01282886edc122f3e):
- Proton version: 7.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Launch options
PROTON_LOG=1 %command% PROTON_USE_WINED3D=1 %command%
[$HOME/steam-$APPID.log](https://gist.github.com/vpfeiffer/380088d4765162e55fca50587122b4e9)

## Symptoms 
The when attempting to move the camera, it spins uncontrollably and often gets stuck in a top down or bottom up view.

## Reproduction
1. Start the game.
2. Enter a world.
3. Try to move the camera.

**Comment by kisak-valve** [comment]
Hello @vpfeiffer, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5695#issuecomment-1302876559.
