### ISSUE TITLE
EA app still crashes as of 2022/11/04 with Proton Experimental (Battlefield 1)

### ISSUE THREAD

**Issue by hjpaul7** [ValveSoftware/Proton#6289]
# Compatibility Report
- Name of the game with compatibility issues: Battlefield 1 (EA App)
- Steam AppID of the game: 1238840

## System Information
- GPU: RTX 3070 Ti
- Driver/LLVM version: Nvidia 520.56.06
- Kernel version: 6.0.6-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): [Gist](https://gist.github.com/hustin-paul/7ba7769635f2af783c88bdb4b0177f22)
- Proton version: Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Reproduction

The Proton log is 1.1 GB, compressed is 75 MB. Over the 25 MB limit.

Edit: This was with the recent [Experimental Version](https://github.com/ValveSoftware/Proton/wiki/Changelog)

- Launch game
- EA app flickers on and off screen about 3-5 times
- EA app minimizes to a wine taskbar at the top left
- Click EA icon, EA app shows up
- Clicking on _anything_ results in a crash

**Comment by kisak-valve** [comment]
Hello @hustin-paul, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5047#issuecomment-1304212390.
