### ISSUE TITLE
[Whitelist] Infinos Gaiden (771070)

### ISSUE THREAD

**Issue by zakk4223** [ValveSoftware/Proton#629]
Game works great, very wine friendly. No issues on Mint 19 Cinnamon with latest nvidia drivers from ppa.

**Comment by kisak-valve** [comment]
Hello @zakk4223, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by zakk4223** [comment]
https://gist.github.com/zakk4223/8f44923cfe293255173306ad5f85c09a

**Comment by kisak-valve** [comment]
Found in the 2018-12-11 white list update.
