### ISSUE TITLE
EA desktop app hinders detection of a controller in game

### ISSUE THREAD

**Issue by fmoerl-real** [ValveSoftware/Proton#6292]
When playing Star Wars: Jedi Fallen Order, the EA desktop app hinders the game to detect any imputs coming from a controller. This is true in desktop mode and also in big picture. 

I also added the *.exe of Fallen Order as a non steam game, to start it without the EA app. In this case, the controller was detected from the game, so it is an issue by the EA app, obviously.

**Comment by kisak-valve** [comment]
Hello @fmoerl-real, this is functionally the same issue as #4009. Closing in favor of the older issue report.
