### ISSUE TITLE
Mortal Kombat X (307780)

### ISSUE THREAD

**Issue by TriVoxel** [ValveSoftware/Proton#6298]
# Compatibility Report
- Name of the game with compatibility issues: Mortal Kombat X
- Steam AppID of the game: 307780

## System Information
- GPU:  AMD RX 5700 XT
- Driver/LLVM version: 
- Kernel version: 6.0.5-200
- Link to full system information report: [Gist](https://gist.github.com/TriVoxel/f2d514785b9fc3352d0506982c4f9114)
- Proton version: experimental & [GE-Proton7-39](https://github.com/gloriouseggroll/proton-ge-custom/releases)

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

(no Proton log could be generated)

## Symptoms 
Game fails to launch at all with Proton Experimental, or GloriousEggroll's latest custom release. Additionally, since Proton 6.3-8 and Proton-6.12-GE-1, there have been considerable regressions in performance and stability. Newer Proton versions that do work (like GE-Proton7-38) will take a very long time to get past the opening screen, and can run at less than 10 fps if you go to Single Player > Towers and choose any option. Also, game will lag in-game, and audio issues will occur. These problems were apparently not present in Proton 6.3 or GE 6.12.

## Reproduction
Use a new Proton version in this game.

**Comment by kisak-valve** [comment]
Hello @TriVoxel, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/513#issuecomment-1305577014.
