### ISSUE TITLE
 South Park - The Stick of Truth (213670) | Crashes at launch

### ISSUE THREAD

**Issue by arbaes** [ValveSoftware/Proton#6302]
# Compatibility Report
- Name of the game with compatibility issues:  South Park - The Stick of Truth
- Steam AppID of the game: 213670

## System Information
- GPU: [AMD/ATI] Renoir (rev c3)
- Driver/LLVM version: Mesa 22.2.2 / LLVM 14.0.6
- Kernel version: 6.0.7-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/arbaes/25f850db093a2d2205a7b3d0413c488c
- Proton version: proton-7.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Proton Logs
[steam-213670.log](https://github.com/ValveSoftware/Proton/files/9966339/steam-213670.log)

## Symptoms 
 Game won't start, crashes immediatly (see proton logs attached)

## Reproduction

1) Launch the game
2) Black window opens then closes immediatly

**Comment by arbaes** [comment]
[steam-213670.log](https://github.com/ValveSoftware/Proton/files/9966336/steam-213670.log)

**Comment by kisak-valve** [comment]
Hello @arbaes, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5590#issuecomment-1308064035.
