### ISSUE TITLE
eXceed - Gun Bullet Children (207370)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#6311]
# Compatibility Report
- Name of the game with compatibility issues: eXceed - Gun Bullet Children
- Steam AppID of the game: 207370

## System Information
- 512 GB Steam Deck 
- Proton version: Experimental 
## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game boots up to a black screen, but sound plays perfectly fine and I can hear menu noises moving around. Checking protondb this was a regression that started after version 3.16-9. Seems to be similar to "eXceed 3rd - Jade Penetrate Black Package" and "eXceed 2nd - Vampire REX" too.
[steam-207370.log](https://github.com/ValveSoftware/Proton/files/9993000/steam-207370.log)

## Reproduction
Start the game up with proton stable or Experimental, notice the black screen, but you can still move in the menus.

**Comment by kisak-valve** [comment]
Hello @waspennator, can you confirm that the game runs with Proton 3.16 on your hardware instead of depending on second hand information?

**Comment by waspennator** [comment]
Testing further, I can confirm that manually forcing proton to 3.16-9 makes the screen appear normally (but started acting like i was holding up the entire time through the menu until i switched to a different controller layout), 4.2-9 still shows the screen, but everything appears completely white. 5.13-6 seems to display the screen no problem, but 6.3-8 and onwards is completely black.

So it seems like the regression started after 5.13-6

**Comment by waspennator** [comment]
Latest proton Experimental update fixed it, game now displays perfectly fine. Might be worth testing the other 2 exceed titles now too, considering protondb mentions similar issues for the both of em and Vampire rex is unsupported on deck

**Comment by waspennator** [comment]
Got my hand on the other 2 titles and both of em seem to progress to the title screen without the black screen issue at all, however i'm noticing another regression keeping those 2 titles from being considered playable. The controls do not seem to initialize at all, but i'll make separate reports for those 2.

For now i'll go ahead and close this since all 3 titles are now actually rendering screen wise though.
