### ISSUE TITLE
No Man's Sky (275850)

### ISSUE THREAD

**Issue by ArcAngelM666** [ValveSoftware/Proton#6315]
# Compatibility Report
- Name of the game with compatibility issues: No Man's Sky
- Steam AppID of the game: 275850

## System Information
- GPU: RTX 2070 SUPER
- Driver/LLVM version: Mesa 22.2.0-1 / nvidia-driver 515.48.07-1
- Kernel version: linux-image-6.0.0-3-amd64 / 6.0.7-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ArcAngelM666/dddf4fad6d7dd92d16390fc9e1859b76
- Proton version: 7.0-4 / Experimental / GE-Proton7-41

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

[steam-275850.log](https://github.com/ValveSoftware/Proton/files/9997990/steam-275850.log)
[FullLog.txt](https://github.com/ValveSoftware/Proton/files/9997991/FullLog.txt)

## Symptoms
The game crashes during start, no matter which which Proton version I choose. (On my Laptop but with an older AMD 2700U/Vega10 it works, same Debian version)

## Reproduction
Just start the game

**Comment by kisak-valve** [comment]
Hello @ArcAngelM666, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/438#issuecomment-1312841209.
