### ISSUE TITLE
Flight Simulator 2020 (1250410) - Won't start after Steam Update 11

### ISSUE THREAD

**Issue by santasemilla** [ValveSoftware/Proton#6316]
# Compatibility Report
- Name of the game with compatibility issues: Micrososft Flight Simulator 2020
- Steam AppID of the game: 1250410

## System Information
- GPU: RTX3060
- Driver/LLVM version: Nvidia515.65.1
- Kernel version: 5.4.0.131-Lowlatency
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

 ATTACHED

## Symptoms 
The game was working fine under Update 10 until November 11. All was working smooth even with DLSS. Right after Steam updates the main game, by clicking PLAY the game will fail after a couple of seconds. Nothing was updated on my machine, the rest of the games are working fine. MSFS2020 won't even start to a splash screen. I cannot understand if its a Proton problem or new dependency requirement.

I've tried restarting Steam, clearing the "Community folder", changing Proton to other versions (6.21-GE2; 7.0-4; 6.3-8) and the behavior was exactly the same. I'm running Steam under KUbuntu 20.04. No space problems, no RAM problem (32GB).
I'll appreciate your help! Thanks for your time.

## Reproduction
Update to Build ID: 9836553, try to run with Proton Experimental or mentioned builds.

[steam-1250410.log](https://github.com/ValveSoftware/Proton/files/9997994/steam-1250410.log)

**Comment by kisak-valve** [comment]
Hello @santasemilla, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-1312841984.
