### ISSUE TITLE
Transpot Fever 2 fails to start due crash in graphics (nvidia)

### ISSUE THREAD

**Issue by antonovvictor** [ValveSoftware/Proton#6325]
# Compatibility Report
- Name of the game with compatibility issues: Transport Fever 2
- Steam AppID of the game: 1066780

## System Information
- GPU:  Intel® Core™ i5-2400S CPU @ 2.50GHz × 4
-   GeForce GT 525M/PCIe/SSE2 / GeForce GT 525M/PCIe/SSE2    
- Driver version: nvidia 390.154
- Kernel version: Ubuntu 22.04.1 LTS  
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 

user data folder: /home/victor/.local/share/Steam/userdata/1474935806/1066780/local/
starting up build version: 35049

__CRASHDB_INIT__
Found 0 mods
Loaded 22 of 22 mod descriptions from disk
Update of mod descriptions: 445.383 ms
language: en
locale: en_US

========================================
Startup at Fri Nov 18 13:05:39 2022
========================================

seed: 1668769539
Saved settings to settings.lua
Requested instance extensions: 
 - VK_KHR_surface
 - VK_KHR_xlib_surface
 - VK_KHR_get_physical_device_properties2
Requested layers: 
Create Vulkan instance.
Supported depth resolve: { SampleZero | Average }
Supperted stencil resolve: { SampleZero }
Found device #0: llvmpipe (LLVM 13.0.1, 256 bits) (id: 0, vulkan version: 1.2.204, driver version: 1 [0.0.1], vendor id: 65541 [Unknown])
 -> Selected device #0
__CRASHDB_RENDERER__ Vulkan|Unknown|llvmpipe (LLVM 13.0.1, 256 bits)|1.2.204 0.0.1|1.2.204|0.0.1|
Count: 1
Flags: { Graphics | Compute | Transfer }
../../src/Lib/renderer/vulkan/VulkanRenderContext.cpp:1072: VulkanRenderContext::VulkanRenderContext(SDL_Window*, const IRenderContext::Options&): Assertion `m_graphicFamilyIndex && m_presentFamilyIndex' failed.
Exception type: Fatal error

Details:

Assertion Failure: Assertion `m_graphicFamilyIndex && m_presentFamilyIndex' failed.

Minidump: /home/victor/.local/share/Steam/userdata/1474935806/1066780/local/crash_dump/69fc433f-6981-48b9-790e87bc-45237a10.dmp

In file: ../../src/Lib/renderer/vulkan/VulkanRenderContext.cpp:1072

In function: VulkanRenderContext::VulkanRenderContext(SDL_Window*, const IRenderContext::Options&)

__CRASHDB_CRASH__ AssertException: ../../src/Lib/renderer/vulkan/VulkanRenderContext.cpp:1072: VulkanRenderContext::VulkanRenderContext(SDL_Window*, const IRenderContext::Options&): Assertion `m_graphicFamilyIndex && m_presentFamilyIndex' failed.
Exception type: Fatal error

Details:

Assertion Failure: Assertion `m_graphicFamilyIndex && m_presentFamilyIndex' failed.

Minidump: /home/victor/.local/share/Steam/userdata/1474935806/1066780/local/crash_dump/69fc433f-6981-48b9-790e87bc-45237a10.dmp

In file: ../../src/Lib/renderer/vulkan/VulkanRenderContext.cpp:1072

In function: VulkanRenderContext::VulkanRenderContext(SDL_Window*, const IRenderContext::Options&)

Goodbye.

========================================
Shutdown at Fri Nov 18 13:05:49 2022
========================================

**Comment by kisak-valve** [comment]
Hello @antonovvictor, your Intel Sandybrigde and NVIDIA Fermi generation video chipset does not support Vulkan, which makes your hardware unsupportable by Proton in general.
