### ISSUE TITLE
Hitman 3 missing DLSS ingame menu and raytracing in both launcher and ingame menu

### ISSUE THREAD

**Issue by Tarch1** [ValveSoftware/Proton#6327]
Hitman 3 v3.130.0

## System Information
- GPU: RTX 3060
- Driver/LLVM version: nvidia-lts 520.56.06-8 and nvidia-open-dkms 520.56.06-8
- Kernel version: linux-lts 5.15.77-1 ( I have kernel panic with linux 6.* )
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Tarch1/40f60815ac1e16bad1ab25f717437090
- Proton version: Proton Experimental (v?) - ProtonGE (v7.41) - WineGE(v7.34)

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

- Proton log: https://github.com/Tarch1/Hitman-steam-log
- Steam/ launch option/Lutris arguments: VKD3D_CONFIG=dxr11 PROTON_CONFIG=dxr11 VKD3D_FEATURE_LEVEL=12_1 PROTON_HIDE_NVIDIA_GPU=0 PROTON_ENABLE_NVAPI=1 -dx12

## Symptoms
- Launching it with steam I can't open the config in the launcher, it just start the game and in game DLSS (Intel and amd fsr selectable) and raytracing option are greyed out
- With Lutris and WineGE is another story, I can select DLSS in the launcher but not in the game (still grey) but it works, ray tracing menu in launcher is selectable but yes option is unselectable; in menu config is greyed out

**Comment by kisak-valve** [comment]
Hello @Tarch1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5536#issuecomment-1320348197.
