### ISSUE TITLE
Deck: Cannot download native Linux builds of games that by default use proton.

### ISSUE THREAD

**Issue by Bitwolfies** [ValveSoftware/Proton#6329]
Take for example, Little Inferno, has a perfectly fine Linux port, install it on my Deck, and it's the Windows port. The game is Deck verified, which means Valve has overridden it to download the Windows port by default. You can confirm this here. https://steamdb.info/app/221260/info/
![Screenshot_20221119_004905](https://user-images.githubusercontent.com/65789901/202842969-2b613cf0-21e9-4fb3-ab3b-fb75cd1b7d44.png)
While I don't mind Windows builds being used over Linux in some cases (there's bad ports, ones that lack features or DLC, ect.) you should absolutely allow us to download the Linux builds after if we so chose. Just make it work like it does on non deck systems where by unchecking the use compatibility tool  it downloads the Iinux build.

It's unfair to players to revoke this choice, and its unfair to devs who may have put effort into their ports.

**Comment by kisak-valve** [comment]
Hello @Bitwolfies, this is an issue with the Steam client, not Proton itself.

That said, per-game properties -> Compatibility -> check `Force the use of a specific Steam Play compatibility tool` -> select `Steam Linux Runtime` will configure Steam to use a game's native linux binary over the Steam Deck recommended runtime.
