### ISSUE TITLE
Mortal Kombat X Crashing OS on Startup

### ISSUE THREAD

**Issue by notdavidbarton** [ValveSoftware/Proton#6330]
---
name: Compatibility Report
about: Game compatibility issues.

---

# Compatibility Report
- Name of the game with compatibility issues: Mortal Kombat X
- Steam AppID of the game: 307780

## System Information
- GPU: GTX 1050
- Driver/LLVM version: Nvidia-driver-515  
- Kernel version: 6.0.6-76060006-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/notdavidbarton/02cb9bdae0b335901fae5edc62b065f9
- Proton version: Experimental

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
Launching game is freezing whole operating system at startup forcing reboot. Can still hear audio and see splash screen of game but mouse and display lose function and keyboard can only go into tty3, though that froze too.

## Reproduction

[steam-307780.log](https://github.com/ValveSoftware/Proton/files/10047638/steam-307780.log)

**Comment by kisak-valve** [comment]
Hello @notdavidbarton, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/513#issuecomment-1320936345.
