### ISSUE TITLE
Elex II - DirectX 12 version

### ISSUE THREAD

**Issue by Xenophobe-01** [ValveSoftware/Proton#6331]
# Compatibility Report
- Elex II - DirectX 12 mode
- Steam AppID 9000040

## System Information
- GPU: RX 6700 XT
- Driver/LLVM version: PPA 22.2.4-kisak-mesa
- Linux Mint 21, Kernel version: 5.15.0-53
- Link to full system information report as [Gist]:https://gist.github.com/Xenophobe-01/42d230975da00368ed7030102c8bd500
- Proton versions: 7.0-4 and Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
There is an odd fireball glitch that only occurs using the DX12 version of the game in Linux. This glitch does not occur with the DX12 version in windows. I'm submitting this report on the chance that this issue is caused by DX12 calls being converted to Vulkan.

## Reproduction
Start game in DX12 mode and play until you get to first meeting with Caya (does not take long to get there) and enter into dialog.  Here's a link to a Youtube clip of what I'm experiencing.  https://www.youtube.com/watch?v=Yx2AA0L9lcY
[steam-900040.log](https://github.com/ValveSoftware/Proton/files/10059527/steam-900040.log)

**Comment by kisak-valve** [comment]
Hello @Xenophobe-01, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5670#issuecomment-1322482080.

**Comment by Xenophobe-01** [comment]
cool, thanks for the notice.
