### ISSUE TITLE
IL-2 Sturmovik: Battle of Stalingrad (307960) "Array size is not a positive integer constant"

### ISSUE THREAD

**Issue by SunnyOd** [ValveSoftware/Proton#6333]
# Compatibility Report
- Name of the game with compatibility issues: Battle of Stalingrad
- Steam AppID of the game: 307960

## System Information
- GPU: NVidia GTX 1070
- Driver/LLVM version: nvidia 520.56.06
- Kernel version: 6.0.8-300.fc37.x86_64
- Link to full system information report as [Gist](https://gist.github.com/SunnyOd/cb143d70922e1277c037d5cd693d8db7):
- Proton version: 7.0.4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
 I'm on Linux (Fedora 37) and have Steam beta installed as a Flatpak.

I've tried starting the game with standard as well as experimental proton. I've also tried using the latest proton-ge.

I found a similar issue here https://github.com/ValveSoftware/Proton/issues/3106 but running it with protontricks launch option "flatpak run com.github.Matoking.protontricks 307960 d3dcompiler_47" didn't fix the issue (after I added my steam game folder to protontricks via flatseal).

I can't find any posts here or anywhere else, including the official forum, with this error. 

## Reproduction
Launching the game as described above opens the game in a window and within a couple of seconds I'm seeing this error:
![](https://forum.il2sturmovik.com/uploads/monthly_2022_11/image.png.ee27d5a03f3d4b98645d874900478864.png)

```
Graphics\Shaders\SysFont\SysFont.fx:13:20: E5008:
Array size is not a positive integer constant.
```

[steam-307960.log](https://github.com/ValveSoftware/Proton/files/10075023/steam-307960.log)

**Comment by JJones780** [comment]
@SunnyOd 
(here from [issue #3106](https://github.com/ValveSoftware/Proton/issues/3106) )
That looks familiar. I get those errors when I'm using older proton versions. If I use newer proton ( 7+) I don't get those but also can't run the game (I'm using nvidia 470 drivers). I see you have nvidia 520 drivers.. I was hoping that would enable proton 7 or higher to work. Which version of Proton are you trying? Have you tried a "Glorious Eggroll" version (I've got GE-Proton7-37) ?  Maybe one of people who have it working will tell us their specifics.

**Comment by SunnyOd** [comment]
@JJones780 
Yah, i've tried latest proton 7.0.4, proton experimental and also proton-ge, same error. Interesting that you got the same sort of errors before, was that in IL-2 or other games?

**Comment by JJones780** [comment]
Yes,  just IL-2 .. but I don't have many games to judge this on.
Note that I only get the index and texture errors on Proton 5.10 and 6.xx ( but after the protontricks I can esc past all the error windows and the game starts... but can't get past the hangar scene.  Proton 7 and above don't bring up the texture errors but can't start the game at all. I'm not sure what the difference is that allows the other gamers to get going again.

**Comment by kisak-valve** [comment]
Hello @SunnyOd, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3106#issuecomment-1325091655.
