### ISSUE TITLE
How to enable ray tracing on AMD RX6750XT in Resident Evil 3?

### ISSUE THREAD

**Issue by laichiaheng** [ValveSoftware/Proton#6334]
I tried to enable ray tracing on RX6750XT in Resident Evil 3, but I can't enable it.
RE2 and RE3 fail to start new games now, why??

**Comment by kisak-valve** [comment]
Hello @laichiaheng, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3719#issuecomment-1324993331.
