### ISSUE TITLE
Dark Tide (1361210) Crashes at prologue

### ISSUE THREAD

**Issue by djpiper28** [ValveSoftware/Proton#6337]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU:  AMD RX 6800
- Driver/LLVM version:  mesa 22.2.3-1
 llvm 14.0.6-4;
- Kernel version:  6.0.9-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): [https://termbin.com/n9lx](https://termbin.com/n9lx)
- Proton version: proton-ge-custom-bin 1:GE_Proton7_16-1

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

(tail 2000)
[https://termbin.com/gqtk](https://termbin.com/gqtk)

## Symptoms 
Game crashes before starting the prologue. The game opens allbeit with many graphical glitches. When you enter the prologue the game crashes and so does my entire desktop environment. 

## Reproduction

AppID: 1361210

**Comment by kisak-valve** [comment]
Hello @djpiper28, this game hasn't been released yet, and with your truncated log, I can't confirm that you're playing the main game's release. That said, there is a closed beta which pre-order players have access to and running that with Proton is being tracked at #6232.

We're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6232#issuecomment-1325839810.
