### ISSUE TITLE
Among Us Twitch Drops 

### ISSUE THREAD

**Issue by Francehelder** [ValveSoftware/Proton#6339]
Hello.

I'm playing the game on Linux with Proton 7.0-4.
The game works fine, but i never get to use twitch drops here.
I tried to connect to Twitch, but it didn't work.
The account has connected, but the callback request doesn't work, it did not open the game.
Any ideia to solve this?

![image](https://user-images.githubusercontent.com/14970431/203926353-90a73e2a-afe7-4f20-843d-8dc11d0d8692.png)
![image](https://user-images.githubusercontent.com/14970431/203926409-8003a99f-27bf-4409-ab1b-59237d9e7d58.png)

**Comment by kisak-valve** [comment]
Hello @Francehelder, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4190#issuecomment-1327506790.
