### ISSUE TITLE
Divinity: Original Sin 2 does not launch on steam

### ISSUE THREAD

**Issue by mantvius** [ValveSoftware/Proton#6340]
# Compatibility Report
- Name of the game with compatibility issues: Divinity: Original Sin 2 - Definitive Edition
- Steam AppID of the game: 435150

## System Information
- OS: Ubuntu 20.04.5 LTS (64 bit)
- GPU: Intel Corporation HD Graphics 630 (rev 04)
NVIDIA Corporation GP107M [GeForce GTX 1050 Ti Mobile] (rev a1)
- Driver/LLVM version: 4.6.0 NVIDIA 470.141.03
- Kernel version: 5.4.0-132-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/mantvius/8f187731cec8f594814db6bdbf853b85
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 

The game simply does not start.
I press play in the first screenshot, then press play on second screenshot. And the game closes. 
![first](https://user-images.githubusercontent.com/4012398/203934375-43c42f6f-79e6-4a66-8eb2-975012ed52d0.jpg)
![second](https://user-images.githubusercontent.com/4012398/203934380-283592cd-ad7f-4e23-a03b-5878d4950538.jpg)

I reported this to Steam support, but their answer was: 
"Currently, Divinity: Original Sin 2 isn't supported with Steam Play so you're likely to encounter difficulties with the title playing it in this way.

You may want to submit all issues or bugs occurring when using this new feature, to the [Valve - Proton Github](https://github.com/ValveSoftware/Proton) bug database using a [GitHub account](https://github.com/). This database is regularly reviewed by the Valve development team."

**Comment by mantvius** [comment]
Where can I find Proton version?

**Comment by mantvius** [comment]
Here are some recent crash dump files:
[Crashdumps.zip](https://github.com/ValveSoftware/Proton/files/11301381/Crashdumps.zip)

**Comment by kisak-valve** [comment]
Hello @mantvius, we're using one issue report per unofficially supported game title. Please use #413 to give feedback how this game is currently behaving with Proton for you.
