### ISSUE TITLE
Monster Hunter Rise twinkle Problem

### ISSUE THREAD

**Issue by YoungMaestro** [ValveSoftware/Proton#6342]
# Compatibility Report
- Name of the game with compatibility issues: Monster Hunter Rise
- Steam AppID of the game: 1446780

## System Information
- CPU: Intel Core 7700k
- Ram: 16gb
- GPU: Radeon RX 6700
- Proton version: Experimental and GE
- Gist: https://gist.github.com/YoungMaestro/9bdf3bcb1a725e1e87b141d68be11017

## I confirm:
- [ Y] that I haven't found an existing compatibility report for this game.
- [ Y] that I have checked whether there are updates for my system available.

## Symptoms 
The problem is the constant twinkling that happens when I open the game and doesnt stop even if I try to play it 
(the Twinkle is more constant that what appears in the video)
## Reproduction
Open the game

https://user-images.githubusercontent.com/119067917/204027999-45aaad09-4f3f-4082-bfc9-88353ec3d44e.mp4

**Comment by kisak-valve** [comment]
Hello @YoungMaestro, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5495#issuecomment-1327700724.
