### ISSUE TITLE
pls strumble guys for debian pls

### ISSUE THREAD

**Issue by rayanosco** [ValveSoftware/Proton#6346]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Closing as invalid due to a complete lack of information.

In general, this issue tracker is intended for feedback that helps Proton devs improve the compatibility layer, not requests to blindly try to get a game working.
