### ISSUE TITLE
help

### ISSUE THREAD

**Issue by AbdallahALSHARIQI** [ValveSoftware/Proton#6347]
![Screenshot from 2022-11-27 17-41-12](https://user-images.githubusercontent.com/77125548/204150963-edc1207e-70a7-4df7-8fd8-3e47363d4f3b.png)

batman Arkham asylum
my pc 

amd ryzen 5 3500u

12 gigb ram
vega 8 

fedora 37 gnome x.org with steam proton 

 i have batman arkham city
how i can fix that

**Comment by kisak-valve** [comment]
Hello @Abdullahalshriqi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/421#issuecomment-1328303984.
