### ISSUE TITLE
Star Wars - The Old Republic Game Launcher stopped working

### ISSUE THREAD

**Issue by schwigi** [ValveSoftware/Proton#6360]
## Symptoms 
With the latest release of Proton Experimental (2022-12-01) the Game Launcher does not show up on screen. The process is running though and not crashing.

## Reproduce
Run the game with Proton Experimental (2022-12-01) on the Steam Deck. This happens on my Desktop PC as well.

## Used Hardware
1) Steam Deck, running Steam Beta channel
2) AMD Ryzen 3600, RX 580 running a Manjaro Linux

[steam-1286830.log](https://github.com/ValveSoftware/Proton/files/10146081/steam-1286830.log)

### Additional Note
The reasons for running Proton Experimental at all, are graphic error on the Steam Deck when using Proton 7.0-4 or Proton Next 7.0-5 during the cut scenes.

**Comment by kisak-valve** [comment]
Hello @schwigi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4326#issuecomment-1336171092.
