### ISSUE TITLE
Keep asking me to reinstall it

### ISSUE THREAD

**Issue by Susquehanna94** [ValveSoftware/Proton#6366]
I have been trying to open it on EA App via Heroic Games. After reinstalling a couple of times, I keep getting a message to reinstall the game. Keeps not working.

**Comment by kisak-valve** [comment]
Hello @Susquehanna94, you've come across the issue tracker for the Proton project. Proton is a fork of wine intended to run games with the Steam for Linux client. Supporting the Heroic Games Launcher is out of scope for this issue tracker. You'll want to report this issue to their dev(s) to ponder.
