### ISSUE TITLE
Elden Ring: Inappropriate activity detected

### ISSUE THREAD

**Issue by RuneFFF** [ValveSoftware/Proton#6368]
# Compatibility Report
- Name of the game with compatibility issues: Elden Ring
- Steam AppID of the game: 1245620

## System Information
- GPU: RX6800XT
- Driver/LLVM version: mesa 22.2.3-1
- Kernel version: 6.0.11-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/RuneFFF/97caf35cdc7b11de76ac9b9bdc03c683
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Multiplayer can not be used. The game gives an error (Inappropriate activity detected) and restarts in offline mode.
I have talked to Bandai Namco Support. This is not a problem of me being banned. I am dual booting windows on the same system. Elden Ring can be played online on windows.
I have tried reinstalling as well as manually deleting the prefix in /compatdata. This did not help. The bleeding edge beta of proton did not help either.

## Reproduction
Launch Elden Ring and get to the main menu. The game logs in, and after around 3 seconds, the mentioned error occurs.

[steam-1245620.log](https://github.com/ValveSoftware/Proton/files/10188979/steam-1245620.log)

**Comment by kisak-valve** [comment]
Hello @RuneFFF, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1343277750.
