### ISSUE TITLE
EA App Crashing 

### ISSUE THREAD

**Issue by MoW9CHh** [ValveSoftware/Proton#6375]
# Compatibility Report
- Name of the game with compatibility issues: Sims 4 
- Steam AppID of the game: 1222670

## System Information
- GPU: R9 390
- Driver/LLVM version: Mesa 22.0.5
- Kernel version: 5.15.0-56-generic x86_64
- Link to full system information report as [Gist](https://gist.github.com/): **edit to add:** https://gist.github.com/MoW9CHh/b414af55b8d88d1b93329e72104b608a
- Proton version: Experimental, 7.0-5, 6.3-8, Hotfix, et al.  

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Compressed log file was too large to attach, here's a link: https://file.io/GaeZ5LHBQiYb

## Symptoms 

From late November up through Dec 6, the game ran relatively well.  Occasionally, I would need to do the "delete the game's compatdata folder" trick to get the EA app to run successfully.  But, starting the 6th, I'm unable to get past the app crashing.  I have tried:
1. Deleting the compatdata folder and trying multiple Proton versions.
2. Running updates on my machine.
3. Running the Steam client beta.
4. Power cycling, obviously. 

## Reproduction

Attempting to launch the game from the Steam client

**Comment by kisak-valve** [comment]
Hello @MoW9CHh, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4174#issuecomment-1345276760.
