### ISSUE TITLE
Horizon Zero Dawn (1151640)

### ISSUE THREAD

**Issue by Kira-PH** [ValveSoftware/Proton#6378]
# Compatibility Report
- Name of the game with compatibility issues: Horizon Zero Dawn
- Steam AppID of the game: 1151640

## System Information
- GPU: RTX 3080ti
- Driver/LLVM version: 525.60.13
- Kernel version: 5.19.0
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/HughPH/8ccf1582918f2af5beaf88e843e4ed52
- Proton version: Default

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms

Horizon Zero Dawn hangs in some open air conditions with driver 525. This was first noticed when meeting Rost at the North Gate. I switched to driver 520 and played through as far as Cauldron Sigma, then reinstalled driver 525 to try Portal RTX again with Canonical's latest official kernel 5.19 (see #6377 ). I completed Cauldron Sigma with driver 525, but the game hung once outside again.

## Reproduction

Install NVidia driver 525 and see how far you get

**Comment by kisak-valve** [comment]
Hello @HughPH, to reiterate again, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4125#issuecomment-1345351190.

**Comment by Kira-PH** [comment]
Thank you
