### ISSUE TITLE
eXceed 3rd - Jade Penetrate Black Package (207400)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#6381]
# Compatibility Report
- Name of the game with compatibility issues: eXceed 3rd - Jade Penetrate Black Package
- Steam AppID of the game: 207400

## System Information
- 512 GB Steam Deck
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Apparently a regression happened after 5.13-6, since the controls seemed to work fine somewhat in that version (had to swap to a community config), the controls don't seem to work at all on the latest experimental past the launcher.
[steam-207400.log](https://github.com/ValveSoftware/Proton/files/10205040/steam-207400.log)

## Reproduction
Launch the game, go through the launcher, then try to move around in the menu and notice that you cant. (Had to switch to a community config to be able to click through the menu.)

**Comment by kisak-valve** [comment]
Hello @waspennator, can you narrow the time frame of the regression you're seeing? Is Proton 6.3 equally affected?

EDIT: https://github.com/ValveSoftware/Proton/issues/6311#issuecomment-1312171301 paged back into memory, There's a rendering issue with this series of games and Proton 6.3/7.0 which blocked finer grained testing.

**Comment by waspennator** [comment]
> Hello @waspennator, can you narrow the time frame of the regression you're seeing? Is Proton 6.3 equally affected?
> 
> EDIT: [#6311 (comment)](https://github.com/ValveSoftware/Proton/issues/6311#issuecomment-1312171301) paged back into memory, There's a rendering issue with this series of games and Proton 6.3/7.0 which blocked finer grained testing.

Game still has the rendering issue from 6.3 onwards (not counting Experimental), but I can still get onto the title screen to check. 6.3-8 is the last confirmed version that I can hear the menu noises when trying to navigate around, 7.0.5 and Experimental have no controls past the launcher.

Someone on protondb also brought up a similar issue with the broken controls and black screen issue, so I guess that narrows it down.

**Comment by waspennator** [comment]
https://store.steampowered.com/news/app/207380/view/3624866351291661239

Just an extra heads up if you are wanting to get either Exceed 3rd or 2nd to test, apparently all 3 titles are getting delisted come Jan 6th cause the og devs just vanished.

Edit: All 3 titles are now delisted.

**Comment by waspennator** [comment]
Retesting it now on the latest Experimental build of Proton and setting my deck controls to the gamepad template, I seem to be able to move around the menu and Actually get in game now.

Closing since it seems like the issue is resolved now.

**Comment by waspennator** [comment]
Is there a specific reason why this game got marked as unsupported on deck? It seems to work fine on deck with 8.0-2 and the gamepad controller layout, only thing I've really noticed is that you can't edit your name for the highscore on the launcher with the virtual keyboard.

**Comment by waspennator** [comment]
> Is there a specific reason why this game got marked as unsupported on deck? It seems to work fine on deck with 8.0-2 and the gamepad controller layout, only thing I've really noticed is that you can't edit your name for the highscore on the launcher with the virtual keyboard.

Update on the editing name issue, tried it on my OLED Deck and it seems to work fine there.
