### ISSUE TITLE
Skeleton Boomerang (658150)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#6383]
# Compatibility Report
- Name of the game with compatibility issues: Skeleton Boomerang
- Steam AppID of the game: 658150

## System Information
-  512 GB Steam Deck
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game loads up to the title screen and main menu perfectly fine, but crashes as soon as you try to start a new game with a vertex shader error. Game dev is also aware of the issue and is looking into a way of fixing it if possible, if not, releasing a version without the shaders causing crashes on proton. Game seems to work if you use protontricks to install d3dcompiler_43 and d3dx9_43 or using Proton GE which has the fixes by default.
[steam-658150.log](https://github.com/ValveSoftware/Proton/files/10205350/steam-658150.log)

## Reproduction
Start the game up, go through the menu and try and start a new game, you won't get into the overworld before it dies.

**Comment by kisak-valve** [comment]
Hello @waspennator, these look like some lines of interest in your log:
```
FATAL ERROR in Vertex Shader compilation

ShaderName: shWater

memory:67:25: E5005: Function "transpose" is not defined.

at gml_Object_oOverworldWaterSprite_Draw_0
```
Related: https://bugs.winehq.org/show_bug.cgi?id=54126

**Comment by waspennator** [comment]
It seems to be a similar issue going on with Carrie's Order up, The Joylancer: Legendary Motor Knight, and Bete Grise from dread x collection 3 and probably others.

**Comment by waspennator** [comment]
Game has regressed from 8.0-5 to latest proton Experimental build. Game now renders as a display of random assets on the screen, some showing up, but mostly being pixel garbage and no longer able to navigate the menu.

[steam-658150.log](https://github.com/ValveSoftware/Proton/files/14471923/steam-658150.log)

Tried it with 8.0-5 and it still crashes when you try and start a new game.

![download (3)](https://github.com/ValveSoftware/Proton/assets/78768499/2636080b-bde0-4e67-9cec-ef7261ef218f)

**Comment by kisak-valve** [comment]
Hello @waspennator, these also look like some lines of interest in your Proton log:
```
err:d3dcompiler:D3DCompile2 Failed to compile shader, vkd3d result -4.
err:d3dcompiler:D3DCompile2 Shader log:
err:d3dcompiler:D3DCompile2     memory:237:13: E5005: Function "ceil" is not defined.
err:d3dcompiler:D3DCompile2 
```
That is likely fixed when https://gitlab.winehq.org/wine/vkd3d/-/merge_requests/417 in brought in from upstream.

**Comment by AJuujarvi** [comment]
> Game has regressed from 8.0-5 to latest proton Experimental build. Game now renders as a display of random assets on the screen, some showing up, but mostly being pixel garbage and no longer able to navigate the menu.

I took a look at this, and found it to be a DXVK regression. I reported it on their tracker here: https://github.com/doitsujin/dxvk/issues/3888

In regards to the error window when starting a new game, we are currently investigating that. Thank you for both reports. :)

**Comment by waspennator** [comment]
Seems like a DXVK pr already got pushed in to fix the visual regression. That was fast.

**Comment by K0bin** [comment]
We just fixed this in DXVK.

**Comment by waspennator** [comment]
Fix has landed in latest Experimental build

**Comment by plrusek** [comment]
Skeleton Boomerang developer here. We received and confirmed the Verified status for the game. The shader errors are no longer present as of 2024-10-18, using Proton Experimental. However, one of our testers still found a crash that we had to patch on our side:
![image](https://github.com/user-attachments/assets/9c34b6fa-a75a-4e60-8b55-59d3e35b4f0c)

We simply replaced the boolean variable in our fragment shader to an integer one on our end. Seems like though it's just another missing feature implementation in D3DCompiler on Wine's end.

**Comment by waspennator** [comment]
Tested it out on my end and can confirm the game works fine on my deck now. Played through the first level with no more issues, closing.

**Comment by K0bin** [comment]
@plrusek That's not a DXVK issue, it's a missing feature in the Wine implementation of D3DCompiler.

**Comment by AJuujarvi** [comment]
> Skeleton Boomerang developer here. We received and confirmed the Verified status for the game. The shader errors are no longer present as of 2024-10-18, using Proton Experimental. However, one of our testers still found a crash that we had to patch on our side: )
> 
> We simply replaced the boolean variable in our fragment shader to an integer one on our end. Seems like though it's just another missing feature implementation in DXVK on Proton's end.

@plrusek  Would it be possible to get a beta branch with a password of the previous build please? That way we can have someone look at this further to fix that issue as well. How far into the game is it/what are the repro steps? We didn't see this on boot like we were with the previous issue.

**Comment by waspennator** [comment]
I also believe that error is the same one that's effecting #6310, specifically the "SM1 cast from bool to interger" happening specifically with Bete Grise

**Comment by waspennator** [comment]
Update, function seems to be in the process of being applied here.

https://gitlab.winehq.org/wine/vkd3d/-/merge_requests/1263

**Comment by waspennator** [comment]
Bete Grise is working now, so it's probably very likely that this would have been the last thing keeping Skeleton Boomerang from working if cast from bool to interger issue wasn't patched around.

**Comment by alasky17** [comment]
@waspennator We have merged all the vkd3d work for this game into proton-experimental.  Are you still seeing any bugs with the game in experimental?

**Comment by waspennator** [comment]
I wasn't saying I ran into anymore issues, I'm just saying that the "SM1 cast from bool to interger" is resolved. I know Skeleton Boomerang got patched to work around the problem and it works fine.
