### ISSUE TITLE
Age of Mythology Extended Edition crashes on launch. XML parsing error in xFonts.xml

### ISSUE THREAD

**Issue by Eldhrimer** [ValveSoftware/Proton#6387]
# Compatibility Report
- Name of the game with compatibility issues: Age of Mythology: Extended Edition
- Steam AppID of the game: 266840

## System Information
- GPU: RX 570
- Driver/LLVM version: Mesa 22.3.0/LLVM 14.0.6
- Kernel version: 5.15.0-56-generic
- Link to full system information report as Gist: [Full System Info](https://gist.github.com/Eldhrimer/b87bd7fe40524fc3ef51519b6467ae26)
- Proton version: 7.0.5
- FLATPAK Version of Steam

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

[steam-266840.log](https://github.com/ValveSoftware/Proton/files/10212940/steam-266840.log)

## Symptoms 
When launching the game with either the bypass launcher or the normal way the game launches in full screen and a pop up appears that says:

![image](https://user-images.githubusercontent.com/18555381/207184837-aaad0622-fae8-49a3-a55d-f6ed7b3638c8.png)

When clicking the only button, "Ok", the game loads the splash screen and a pop up appears that says:

![image](https://user-images.githubusercontent.com/18555381/207185061-47225ac0-51da-44e5-83af-a484ac824f4f.png)

After that the game closes.

## Reproduction
It happens 100% of the time.

**Comment by kisak-valve** [comment]
Hello @Eldhrimer, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1547#issuecomment-1347552123.
