### ISSUE TITLE
The problem with the savegames

### ISSUE THREAD

**Issue by kgudalov** [ValveSoftware/Proton#64]
When you start games that have already been run in wine steam (Gothic 3, Skyrim SE ), you can not find the old save.

**Comment by tingvarsson** [comment]
Same applies to Mirrors Edge (save game is not synced).
However it does work for Final Fantasy VII, but could be because it has a launcher which seems to handle the sync potentially.

**Comment by kgudalov** [comment]
The situation even worse. The games mentioned above can't save the settings at all.

**Comment by kisak-valve** [comment]
Hello @kgudalov, @tingvarsson, cloud saves are managed by the steam client, not Proton. Let's track this issue in the steam-for-linux issue tracker at https://github.com/ValveSoftware/steam-for-linux/issues/5640.

**Comment by IamSonoma** [comment]
I thought this was just me. In Skyrim I am at level 54 and it can only find my level 10 save and older. I copied the ###54###.ess files in the location that the steam folder points too (/home/me/My documents/Skyrim SE/saves where the level 10 resided and it did not work.

I did find something I will try later. If you add SLocalSavePath=<insert custom directory here> to your Skyrim.ini file in you My Documents folder it should change the save location and allow you to reload your saves. I hope it works.

Then I need to figure out how to transfer my Doom 3 BFG directory from Lutris. It is 60 GBs and I do not want to re-download it.

Edit: Found my save location here
/home/your name/.local/share/Steam/steamapps/compatdata/#######/pfx/drive_c/users/steamuser/My Documents/My Games/Skyrim Special Edition/Skyrim.ini
I used this  find /home/your name/ -name "Skyrim.ini"

**Comment by alexzk1** [comment]
Yes, if I was using windows steam over wine it did saves in ~/Documents.
With proton it makes own folder for each game. Need some option to repoint it to such a path:

/home/your name/.local/share/Steam/steamapps/compatdata/#######/pfx/drive_c/users/steamuser/My Documents/My Games/Skyrim Special Edition/Skyrim.ini
