### ISSUE TITLE
rFactor 2 Dedicated Server (400300)

### ISSUE THREAD

**Issue by SoraBytes** [ValveSoftware/Proton#6400]
# Compatibility Report
- Name of the game with compatibility issues: rFactor 2 Dedicated Server
- Steam AppID of the game: 400300

## System Information
- GPU: N/A
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 22.2.3
- Kernel version: 6.0.13-300.fc37.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): [Personal SystemInfo](https://gist.github.com/Sora012/946e79a2d9ef4b7ddacc3074fc6407bf)
- Proton version: Proton Experimental & System Wine 7.22 & Wine GE 7-35

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
- Dedicated Server hosted on a linux cannot play with a human client >=2 with bots without causing latency issues (over 1000 ping, and constant desync or collision being disabled due to latency and teleporting clients)
- Server shows FPS value of ~300-400
- CPU shows as not overloaded.
- Single client with bots can play just fine

## Reproduction
- No GPU (Virtual Server/VM/Dedicated Hardware)
- Linux (Fedora and Arch in our case)
- Install SteamCMD
- Download rFactor 2 Server
- Install Wine or WineGE or Proton
- Install XPRA/Xvfb
- Configure XPRA/Xvfb using one of them for a virtual desktop
- CD to server Bin64 folder
- Use any of the versions of wine to launch Dedicated Server
```"rFactor2 Dedicated.exe" +path=".."```
- Add >=6 Bots
- Have ClientA join. ClientA can play
- ClientB joins
- ClientA and ClientB notice huge latency increase (Including ServerConsole) as well as teleporting and Bots crash/ram clients because they can't determine location(s).

# Notes
Will attach proton log later, after I install steam on the VPS.

**Comment by kisak-valve** [comment]
Hello @Sora012, without Steam or Proton involved, this feedback should go to the upstream wine devs to ponder (https://bugs.winehq.org/).
