### ISSUE TITLE
Japanese IME on Proton Experimental in Final Fantasy XIV

### ISSUE THREAD

**Issue by jeninto** [ValveSoftware/Proton#6401]
Running Proton Experimental on Steam Deck (beta channel).

The locale for the device is set to Japanese and have added the Japanese IME as an input method for the virtual keyboard in Game Mode settings. I'm able to type with the Japanese IME fine in Steam (search bar, etc.) with this method.

However in Final Fantasy XIV running on Proton Experimental (and earlier versions), while it is possible to bring up the virtual keyboard in the game with STEAM+X and switch the keyboard to Japanese, the resulting input out of the IME shows up as question marks (????) in the game.

Reproduction steps:
1. Install FFXIV (the Windows installer) via Steam with Proton
2. Launch the game
3. Place the text cursor in the chat entry box
4. Open the virtual keyboard (STEAM+X)
5. Switch the virtual keyboard's input language to Japanese
6. Type anything and press enter
7. Close the keyboard
8. Observe that the output is "???"

Researching this issue found similar reports on Twitter - https://twitter.com/search?q=ff14%20steam%20deck%20%E6%97%A5%E6%9C%AC%E8%AA%9E%E5%85%A5%E5%8A%9B&src=typed_query&f=top

There was a summary of issues relating to encoding here; https://gist.github.com/cfillion/4394c3b8cd051fb45721187053e92296

I followed the steps in that gist's solution for Problem 2 (setting HOST_LC_ALL to ja_JP.utf8), which successfully gets Proton to switch to Japanese locale - Wine system menus, etc. are shown in Japanese - but Japanese input is still broken in this mode. The same is also true for the script that is offered as a solution. In this case, text is output as garbage instead of ???s, double-byte input like "=g=x".

It might be possible to get around this by using the game's built-in keyboard according to this user? https://twitter.com/Vale_N14/status/1605043914750464000 (I actually didn't know such a keyboard was available)

**Comment by kisak-valve** [comment]
Hello @jeninto, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/580#issuecomment-1361472893.
