### ISSUE TITLE
Unreal Engine crashes on Intel GPU in trying to parse the driver version string

### ISSUE THREAD

**Issue by djdeath** [ValveSoftware/Proton#6402]
We got a report on the Intel/Mesa Vulkan driver about a crash in Unreal Engine : https://gitlab.freedesktop.org/mesa/mesa/-/issues/7928

The issue seems to be that Unreal Engine will try to figure out the driver version by poking at the Windows registry.

The only way we can potentially workaround this in the driver or in DXVK is to change the device vendor ID so that it doesn't hit the Intel code path in Unreal Engine.

It was suggested on the Mesa issue that maybe Proton/Wine could have a better workaround for this (I don't know actually know).

**Comment by Blisto91** [comment]
Should be solved both in upstream Wine and Proton Experimental via <https://gitlab.winehq.org/wine/wine/-/merge_requests/3104>

**Comment by kisak-valve** [comment]
Looks like this is in Proton 8.0-4 (Release candidate) https://github.com/ValveSoftware/wine/commit/813c406130522a17766e4b7c65837324c701abad
