### ISSUE TITLE
Grand Theft Auto 5 texture issues making the game freeze and crash after 10-20min of gameplay

### ISSUE THREAD

**Issue by linuxuser420** [ValveSoftware/Proton#6403]
# Compatibility Report
- Name of the game with compatibility issues: Grand Theft Auto 5
- Steam AppID of the game: 271590

## System Information
- GPU: RX 550
- Driver/LLVM version: 11.0.1
- Kernel version: 5.10.0-19-amd64
- Proton version: GE-Proton7-43

## I confirm:
- [ ] that I have found other people's compatibility issues the same as mine.
- [ ] that I have checked whether there are updates for my system available.

gamemoderun DXVK_ASYNC=1 WINE_FULLSCREEN_FSR=1 %command%.

## Symptoms 
You can play Gta 5 for 10-20 minutes depending on your luck before the textures start not rendering correctly and the game eventually freezes and crashes, i have seen lots  of peoples experiencing the same issue

**Comment by kisak-valve** [comment]
Hello @linuxuser420, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-1362100021.
