### ISSUE TITLE
Easy Anti-Cheat engine not loading in SteamOS 3.4

### ISSUE THREAD

**Issue by gmacbm** [ValveSoftware/Proton#6404]
4# Compatibility Report
- Name of the game with compatibility issues:Divine Knock-out
- Steam AppID of the game:1294660

## System Information
- GPU: AMD
- Driver/LLVM version: Steamdeck
- Kernel version: 
- Proton version:7.0

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Reproduction

1.  `Divine Knock out DKO` the AppID is 1294660
2. Linux version: Steam os 3.4
3. Steamdeck device
4. Easy anti cheat engine prevent the game from launching.

**Comment by kisak-valve** [comment]
Hello @gmacbm, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6384#issuecomment-1363533868.
