### ISSUE TITLE
CHAOS;HEAD NOAH (1961950)

### ISSUE THREAD

**Issue by WilsonNet** [ValveSoftware/Proton#6407]
# Compatibility Report
- Name of the game with compatibility issues: CHAOS;HEAD NOAH
- Steam AppID of the game: 1961950

## System Information
- GPU: NVIDIA GeForce MX250 
- Driver/LLVM version: video-hybrid-intel-nvidia-prime  2021.12.18 
- Kernel version: 6.0.5-2-rt14-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/WilsonNet/cfdb6035c3219fd00369fd38f726a0d3
- Proton version: 7.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game don't even launch, when I try to launch the game my status change to "Playing" and a few seconds later goes back to "Online"

## Reproduction

Just launch the game.

[steam-1961950.log](https://github.com/ValveSoftware/Proton/files/10297994/steam-1961950.log)

**Comment by kisak-valve** [comment]
Hello @WilsonNet, looking at your system information, the Vulkan render paths are broken in general (https://gist.github.com/WilsonNet/cfdb6035c3219fd00369fd38f726a0d3#file-gistfile1-txt-L184-L197 / https://gist.github.com/WilsonNet/cfdb6035c3219fd00369fd38f726a0d3#file-gistfile1-txt-L372-L385).

You could add the `vulkan-intel` and `lib32-vulkan-intel` system packages to install Vulkan drivers for your Intel graphics or give https://download.nvidia.com/XFree86/Linux-x86_64/525.60.11/README/primerenderoffload.html / https://wiki.archlinux.org/title/PRIME#PRIME_render_offload a try.

**Comment by WilsonNet** [comment]
thanks @kisak-valve, you nailed it

just installing `vulkan-intel` and `lib32-vulkan-intel` solved it

it's weird that I've been playing games on proton and it has been working fine, I thought everything here was setup properly

**Comment by twoda5h** [comment]
I can't reopen this but the game doesn't seem to work with any controllers plugged in.

[Proton Log](https://gist.github.com/twoda5h/c5204f49460fd9d7a3b548ea56675f4b)

**Comment by kisak-valve** [comment]
Hello @twoda5h, since this compatibility report was closed by the author and it appears there isn't another issue report tracking this game, please go ahead and open a new compatibility report to track your feedback with this game.
