### ISSUE TITLE
Manhunt (12130)

### ISSUE THREAD

**Issue by BlackShadow** [ValveSoftware/Proton#6409]
## System Information

- Steam Deck
- SteamOS 3.4.2 - 20221221.2
- Proton: 4.11-13

## I confirm:
- [ ✓ ] that I haven't found an existing compatibility report for this game.
- [ ✓ ] that I have checked whether there are updates for my system available.

## Symptoms 

Graphical issue when you look at light sources in-game, it reveals wireframes of the map, characters, objects.

![2022-12-24 231456](https://user-images.githubusercontent.com/30868395/209450115-d5d73709-d3e5-4fbc-8edf-314e86e9514b.png)

## Reproduction

Rotate ingame camera and look at to light sources. i.e: lamps.

**Comment by kisak-valve** [comment]
Hello @BlackShadow, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/62#issuecomment-1364586389.
