### ISSUE TITLE
Magic: The Gathering - Duels of the Planeswalkers 2013 (97330)

### ISSUE THREAD

**Issue by QuantumConundrum** [ValveSoftware/Proton#6412]
# Compatibility Report
- Name of the game with compatibility issues: Magic: The Gathering - Duels of the Planeswalkers 2013
- Steam AppID of the game: 97330

## System Information
- GPU: Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
- Driver/LLVM version: 3.0 Mesa 21.2.6

- Kernel version: 5.15.0-56-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/codefighter2/fddc2842664c82493636a7cd0c19d34b
- Proton version: Experimental

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

[steam-97330.log](https://github.com/ValveSoftware/Proton/files/10300458/steam-97330.log)

## Symptoms 

Game does not start successfully, no game window or anything ever shows up.

## Reproduction

- Enable Steam Play for unsupported games, with Proton Experimental.
- Install game and try to run.

**Comment by kisak-valve** [comment]
Hello @codefighter2, the build of DXVK in Proton Experimental requires mesa 22.0 or newer. Additionally, the Vulkan drivers for your Ivybridge chipset are not spec compliant, which makes your system unsupportable in general by Proton.

The specific lines of interest from your log:
```
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
warn:  Skipping Vulkan 1.2 adapter: Intel(R) HD Graphics 4000 (IVB GT2)
```

You could try updating your video drivers using a PPA like [oibaf](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) or [kisak-mesa](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa), but my understanding is that mesa/hasvk does not provide support for Vulkan 1.3 at this time. (https://gitlab.freedesktop.org/mesa/mesa/-/issues/7827)

You could try using Proton 7.0-5 or older with the game.

**Comment by QuantumConundrum** [comment]
@kisak-valve Thanks, it looks like it works with Proton 3.7-8.
