### ISSUE TITLE
Dragon Age Inquisition (1222690)

### ISSUE THREAD

**Issue by maniman303** [ValveSoftware/Proton#6418]
# Compatibility Report
- Name of the game with compatibility issues: Dragon Age Inquisition
- Steam AppID of the game: 1222690

## System Information
- Device: Steam Deck
- OS: SteamOS Stable 3.4.2
- Proton version: 7.0 experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Controller doesn't work, and to be more specific - it's recognized by the game (if game doesn't recognize any controller it shows proper message on start), but it's not registering any input.

I've made small xinput wrapper dll for myself that logs calls to xinput and when the game on windows calls them all the time when it's running, on Linux it stops after a few seconds after launch.

EDIT:
My wild guess is it's related to the game behaviour in terms of display. It's aggresively changing refresh rate of the monitor on windows, and it's also doing weird things with a game window at start.

## Reproduction

Have controller connected to PC and enabled in Steam.
Launch game.
Go to options -> controls, choose controller instead of K+M.
Go back to main settings page to approve changes.
Now the game is in a "gamepad" mode, but it doesn't detect any gamepad input.

**Comment by kisak-valve** [comment]
Hello @maniman303, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3950#issuecomment-1367490703.
