### ISSUE TITLE
Age of Empires III: Definitive Edition fix

### ISSUE THREAD

**Issue by AdolfRoxler** [ValveSoftware/Proton#6420]
# Compatibility Report
- Name of the game with compatibility issues: Age of Empires III: Definitive Edition
- Steam AppID of the game: 933110

## System Information
- GPU: RTX 3070M, Radeon 5800H APU
- Driver/LLVM version: nvidia 525.60.11-1 | mesa 22.3.1-1
- Kernel version: 6.1.1
- Proton version: any

## I confirm:
- [ YES] that I have checked whether there are updates for my system available.

## Symptoms 

The multiplayer will not work on newer proton versions. Last reported working version was 7.0-4 but I can't compile it because openvr.dll is missing.

The only proton version that worked for me is unfortunately GloriousEggroll's fork, specifically Proton-6.21-GE-2.

Now, as everyone knows because this is a Definitive Edition issue, multiplayer will still not work. Although this time, with the GE fork, now the listing appears (I guess the africa encryption is messed up on newer versions since the latest GE fork seems to have the same issue, alongside the newer proton versions.)

In order to fix the desync error or whatever, you have to install the correct vcredistx64 (presumably it's the 2015-19 one) onto the game's C:\ drive in the pfx. However, thanks to the guys developing cabextract, you can directly extract the cabinet files from the redistributable, specifically, the cabinet file a10 that contains the necessary dll's for multiplayer play.

Now, the steam deck doesn't have cabextract installed, so you'd have to disable write protection on / and populate the arch linux keyring to install the aforementioned software to make age of empires work on multiplayer.

**Comment by kisak-valve** [comment]
Hello @AdolfRoxler, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3712#issuecomment-1367924362.
