### ISSUE TITLE
Bridge Constructor Portal (684410)

### ISSUE THREAD

**Issue by martinpl** [ValveSoftware/Proton#6421]
# Compatibility Report
- Name of the game with compatibility issues: Bridge Constructor Portal 
- Steam AppID of the game: 684410

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

Current native Linux build of games have some issue with controls (not all buttons works).
This can be easy to fix by switching to Proton version, so main issue is here that game don't by default fallback to proton. Game have green Steam Deck verify status and configuration "recommended_runtime: native"

Discussion about issue: https://steamcommunity.com/app/684410/discussions/0/3267933887521370592/
Steam Deck Compatibility info: https://steamdb.info/app/684410/info/

**Comment by kisak-valve** [comment]
Hello @MartinPL, because Bridge Constructor Portal is a native linux game and is not using Proton on the Steam Deck by default, that makes your feedback invalid for the Proton issue tracker.

I've gone ahead and forwarded your feedback, but it won't be tracked here.
