### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by blankie1** [ValveSoftware/Proton#6422]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Reproduction

[steam-1672970.log](https://github.com/ValveSoftware/Proton/files/10326058/steam-1672970.log)

**Comment by kisak-valve** [comment]
Hello @blankie1, we're using one issue report per unofficially supported game title. Please use #5246 for feedback related to running Minecraft Dungeons with Proton.
