### ISSUE TITLE
Extremely laggy towers menu

### ISSUE THREAD

**Issue by Attula15** [ValveSoftware/Proton#6425]
# Compatibility Report
- Name of the game with compatibility issues: Mortal Kombat X
- Steam AppID of the game: 307780

## System Information
Steam Deck with the currently latest (2023.01.01. 23:52 GMT+1) OS and proton version.

## Symptoms
The problem is that with the currently latest proton version, I can play the game, however when I navigate to the "towers mode" menu it gets extremely laggy, like 1-2 fps, altough both the CPU and the GPU usage is around 50-60%.
When I fall back to proton version 6.3.8. it works fine, but in that case it always crashes in the story mode, while fighting with scorption in the first quick-time event cutsceen (around the 3. quick-time event).
In both cases, if you manage to get to play the game (actual combat), the game runs fine.

## Reproduction
I just simply downloaded the game, and started playing, nothing special, just out of the box.

**Comment by kisak-valve** [comment]
Hello @Attula15, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/513#issuecomment-1368563190.
