### ISSUE TITLE
Denuvo connection issue

### ISSUE THREAD

**Issue by DigitalDragon64** [ValveSoftware/Proton#6428]
# Compatibility Report
- Name of the game with compatibility issues: Sonic Frontiers
- Steam AppID of the game: 1237320

## System Information
- GPU: RX 5600 XT
- Driver/LLVM version: Mesa 22.3.1
- Kernel version: 6.1.1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/DigitalDragon64/2509f5311e653a9dbf8c8910805df9d2
- Proton version: 7.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1237320.log](https://github.com/ValveSoftware/Proton/files/10333659/steam-1237320.log)

## Symptoms 
Game does not start. Instead I get a window with the message

'The server is not reachable. Check your Internet connection and click "Retry"
In case the problem persists, click "Next" to open the support website in the default browser'
![20230102_23h40m56s_grim](https://user-images.githubusercontent.com/10868601/210283388-71ec2076-41ee-49fc-99ab-3b5ce5544f0a.png)

The next window where I have manually to open the website doesn't show the code, so I can't proceed with the manual method.
![20230102_23h42m19s_grim](https://user-images.githubusercontent.com/10868601/210283389-26f39d68-76dd-4672-909a-def509b41b71.png)

## Reproduction
Starting the game

**Comment by kisak-valve** [comment]
Hello @DigitalDragon64, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6303#issuecomment-1369259739.
