### ISSUE TITLE
Evaluate bugs.winehq.org 54251#c3 iphlpapi patch

### ISSUE THREAD

**Issue by mjevans** [ValveSoftware/Proton#6431]
A simple patch for iphlpapi (dll) already exists, but wine is currently in a code freeze. It would be nice if Proton applied this until it's fixed there.

https://bugs.winehq.org/show_bug.cgi?id=54251#c3 ( https://bugs.winehq.org/attachment.cgi?id=73813&action=diff )

Bug reports might include stack traces which call IpHlpApi.GetNetworkParams or System.Net.NetworkInformation.HostInformationPal.GetFixedInfo or any other function that obtains extended networking information including local machine name / DNS data, such as "ipconfig /all" like information rather than just ipconfig.

AppID 799600  / Cosmoteer

However this likely affects most multiplayer games on systems which have multiple network interfaces if any lack DNS servers.

It affects _all_ current Proton versions lacking the linked patch.

## I confirm:
- [X] that I haven't found an existing compatibility report for this game. (There is one other issue but it's related to multicore, not networking.)
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

Cosmoteer freezes just before the main menu screen, after what looks to be a shader and/or tile assets compile.  Other games might freeze when multiplayer components are loaded.

## Reproduction

Reproduction is related to having multiple network interfaces on the host system.  In my case two network interfaces are bridged with the real IP data on the bridge device.  The active physical bridge port has an IPv6 local link address but no DNS server routable from that subnet.  The other physical port is configured up (can send / get raw packets) but has no IP configuration at all.

**Comment by kisak-valve** [comment]
Hello @mjevans, the way you've presented this information really should be treated as a feature request to include the patch, not a compatibility report for the game.

Ignoring the timing with the feature freeze upstream, this change should still be evaluated in upstream wine and reviewed as a regular merge request at https://gitlab.winehq.org/wine/wine/ before requesting for it to be pulled into Proton's downstream fork of wine.

**Comment by mjevans** [comment]
The game is non-functional on my system without this patch.

I have tested the patch someone else wrote, it fixes the issue.

I skipped including the non-relevant details since a root cause and solution were both known.  Would additional information improve the response in the evaluation and inclusion of a fix that might fix the issue for others as well?  If so what data is useful for that evaluation?

**Comment by mjevans** [comment]
Wine 8.0 (or maybe rc4) should include this.

The fix is literally one line of new code though.

https://gitlab.winehq.org/wine/wine/-/merge_requests/1920/diffs

        if (err != ERROR_SUCCESS && err != ERROR_MORE_DATA) goto err;

Extremely reasonable to back-port to the stable Proton release.

**Comment by mjevans** [comment]
Wine 8.0 is released with the patch that fixes my issue included among the many other improvements.

https://www.winehq.org/announce/8.0

**Comment by kisak-valve** [comment]
Hello @mjevans, it looks like this was inherited from upstream as part of Proton 8.0-1.
