### ISSUE TITLE
Games go Backscreen after switching to other program / window

### ISSUE THREAD

**Issue by Windgott1910** [ValveSoftware/Proton#6434]
# Compatibility Report
- Name of the game with compatibility issues (I've seen it on these, could be more): Elite: Dangerous, Children of a dead Earth
- Steam AppID of the game: 359320 and 476530, respectively

## System Information
- Link to full system information report as [Gist]: https://gist.github.com/Windgott1910/d1baca0948fbd2bc0379406ae64b6232
- Proton version: tested with 7.0-5 (E:D) and 7..0-5 and 6.3-8 (CODE)

## I confirm:
- [x] that I have checked whether there are updates for my system available.

## Logs:
Steam Log: (CODE): https://gist.github.com/Windgott1910/8232fcf4761cd8a6ef3cbfdb9a7470a4
Proton Log: [steam-476530.log](https://github.com/ValveSoftware/Proton/files/10344884/steam-476530.log)

## Symptoms + Reproduction
the game goes Blackscreen when I alt + tab to another program / window, does not respond after that

**Comment by josef256** [comment]
happens for **starship troopers terran command (1202130)** too, black screen with audio whenever you alt-tab

**Comment by Windgott1910** [comment]
fixed it for me by setting window settings to something else than fullscreen.
@josef256 does it fix that for you?
i hope commenting works after closing ¯\ _ (ツ) _ /¯
