### ISSUE TITLE
Halo MCE Memory Hole

### ISSUE THREAD

**Issue by scottpk** [ValveSoftware/Proton#6445]
I was playing "The Truth and Reconciliation" campaign for the "Sniper School" playlist. (This is the part early in the game where you rescue Captain Keyes.) I noticed frequent stuttering and hanging, and so I opened up the System Monitor... the game was taking several gigabytes of RAM. I kept playing through, and it kept taking more and more RAM, and would freeze up every so often... I was not able to make it through, because I hit Escape during one of these slow-downs to try and fiddle with the settings and although my cursor moved around the menu it wouldn't let me resume the game.

I tried Proton-GE as well and had very similar results though I was able to finish that campaign (possibly because I learned my lesson and did not try to fiddle with settings). By the end of the campaign, it had taken over 30 GB of RAM. I doubt this is how it should be - I have 64 GB of RAM but most people don't. I had the settings on the highest level, but still, that's a lot of RAM.

APU: AMD Ryzen 7 5700G with Radeon graphics
Graphics: AMD Renoir
Memory: 64 GB DDR4 3200
OS: Ubuntu 22.04.1 LTS

**Comment by kisak-valve** [comment]
Hello @scottpk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2907#issuecomment-1377246767.
