### ISSUE TITLE
Steam overlay not working and other graphical glitches after "Insurgency: Sandstorm" update

### ISSUE THREAD

**Issue by mlandalv** [ValveSoftware/Proton#6450]
# Compatibility Report
- Name of the game with compatibility issues: Insurgency: Sandstorm
- Steam AppID of the game: 581320

## System Information
- GPU: Radeon 6700XT
- Driver/LLVM version: mesa 22.3.2-3
- Kernel version: 6.1.4-arch1-1
- [Link to full system information report](https://gist.github.com/mlandalv/bb059d24b8df8d1f843370bc64250109)
- Proton version: 7.0-5 and Proton Next (7.0-6)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-581320.log.zip](https://github.com/ValveSoftware/Proton/files/10404878/steam-581320.log.zip)

## Symptoms
1. Graphical artifacts if not using native resolution (I'm using 1920x1200 on my 3840x1600 monitor)
As soon as I take a screenshot or start screen recording the artifacts go away, hence the mobile photo. The issue starts being visible on picture 4 although not easy to spot on the picture due to so much dark. Easy to spot IRL due to some flicker.
![1](https://user-images.githubusercontent.com/710584/212147063-068dd821-9df2-4888-bc0e-81133f5ac320.jpg)
![2](https://user-images.githubusercontent.com/710584/212147077-f9f55a22-c3f2-4b61-8c06-3973116d3844.jpg)
![3](https://user-images.githubusercontent.com/710584/212147087-06254720-b8de-482b-a216-831f401ab568.jpg)
![4](https://user-images.githubusercontent.com/710584/212147100-c18f58c8-7c2d-4d34-b14c-7a0699cc2fc0.jpg)
![5](https://user-images.githubusercontent.com/710584/212147121-a8e85741-48f0-48b9-93f5-efa861701488.jpg)
![6](https://user-images.githubusercontent.com/710584/212147133-12633b9e-b224-4aca-a972-8477eed5b44b.jpg)

3. It is not possible to open the steam overlay
Not working regardless of resolution.

5. Steam FPS counter (top left) isn't working
Not working regardless of resolution.

## Reproduction

Happens 100 % of the time since the 2023-01-10 update of the game.

## Other notes

The graphical glitches disappear if i take a screenshot with `grim` or if I record with `wf-recorder`. After that the window also gets stretched (same thing happens when switching workspace and back).

When exiting the game this is printed:
```
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 7557 -- gameoverlayui

src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 7557 -- gameoverlayui

src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 7596 -- gameoverlayui

src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 7596 -- gameoverlayui

src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 7627 -- gameoverlayui

src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 7627 -- gameoverlayui
```

Also tried with [GE-Proton7-43](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton7-43) but it's even worse. So many graphical artifacts it's not possible to see anything.

**Comment by kisak-valve** [comment]
Hello @mlandalv, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1651#issuecomment-1380866604.

**Comment by georgehank** [comment]
Wow, an official pro-necro policy.  Also, a *very* weird and unusual (and bad, really bad) policy.
