### ISSUE TITLE
Command and Conquer: Red Alert 3 - Uprising (24800)

### ISSUE THREAD

**Issue by Industrial** [ValveSoftware/Proton#6459]
# Compatibility Report
- Name of the game with compatibility issues: Command and Conquer: Red Alert 3 - Uprising 
- Steam AppID of the game: 24800

## System Information
- GPU: AMD Radeon RX 6950 XT
- Driver/LLVM version: `video-linux            2018.05.04`
- Kernel version: 5.15.85-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Industrial/252a678905b709d4fb85f8cdb0109454
- Proton version: 7.0-5 (took stable to be sure)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

  
https://gist.github.com/Industrial/89c0fc64c5b8693a45f9d298f87079e4

## Symptoms 
"No Language Packs Found"

## Reproduction
When I start the game I get the error message "No Language Packs Found", "Please install at least one language pack"

When I right click on the game and go to Properties > Language and select another language (then English) it will download more data.

When that download is finished I press play again. I get the same error message.

**Comment by Industrial** [comment]
@kisak-valve Hi. What's unofficial about this compatibility issue?

**Comment by Industrial** [comment]
It's probably a really minor update to fix this and select the language so the game understand that the correct files have been installed.

**Comment by Wedge009** [comment]
Seems to work well on Proton 8.0-2. Does not suffer the issue I had with the base RA3 game (#402) where it takes a long time to start.

As with Tiberium Wars (#1187) and Kane's Wrath (#477), the only issue I had was window switching (Alt-Tab) and returning to the game results in a blank screen.

**Comment by julas23** [comment]
I have exactly the same issue running
Garuda Soaring Raptor (Arch Linux)
Kernel 6.4.12
Mate 1.26

With Ubuntu 23.04 worked perfectly. No necessary any adjustments. Now with Arch based system. Just got error asking to install at least 1 language pack. Follow below the output of Steam:

(wine:1380176): GStreamer-WARNING **: 17:22:22.664: Failed to load plugin '/usr/share/steam/compatibilitytools.d/proton-ge-custom/files/lib64/gstreamer-1.0/libprotonmediaconverter.so': /usr/share/steam/compatibilitytools.d/proton-ge-custom/files/lib64/gstreamer-1.0/libprotonmediaconverter.so: wrong ELF class: ELFCLASS64
ERROR: ld.so: object '/FS/GAME/steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
wine: configuration in L"/FS/GAME/steam/steamapps/compatdata/24800/pfx" has been updated.
ERROR: ld.so: object '/FS/GAME/steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Setting breakpad minidump AppID = 24800
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198021214249 [API loaded no]
ERROR: ld.so: object '/FS/GAME/steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
pid 1379257 != 1379256, skipping destruction (fork without exec?)


I play a lot  this game:
![image](https://github.com/ValveSoftware/Proton/assets/92172251/53492fa5-6940-48a4-b4ce-7de86ed07d25)

**Comment by julas23** [comment]
I have open once more ticket for support for this issue:

 HT-4XV9-RBVT-BDPV

**Comment by julas23** [comment]
I also have back to Ubuntu Mate 23.04 that is the system it was working before, and for my surprise, I got exactly the same problem, in a fresh installed system. So it seems some bug from the new version of Proton. Once It was running before, and in a fresh install, of Ubuntu or even Arch Linux, I got same problem.

**Comment by Wedge009** [comment]
There's a **regression in Proton 11** where custom scenarios and missions downloaded from the workshop are no longer found. Reverting to Proton 10 resolves this.

The same applies for #6800.

This issue should be re-opened.
