### ISSUE TITLE
[Feature Request] suggest developer / publisher a native linux port

### ISSUE THREAD

**Issue by shakeyourbunny** [ValveSoftware/Proton#646]
I dunno know if Valve has a Proton userbase tracking per game, but if there is one, it would be neat if the developers and/or publisher would get in regular intervals (may be disabled by them after 5th oder 10th mail) a suggestion to port the game to Linux instead of relying on Proton.

Example
Subject: Your game "Mages of Mystralia" (appid: 529660)

Hello dear developers / publishers,

we noticed that your game "Mages of Mystralia" (appid: 529660) is also played by more and more gamers who rely on our Windows compatibilty layer "Proton". According to our platform statistics there are %PLAYERS_THRESHOLD% Linux players which show up in your dashboard als Windows players.

Perhaps you would widen up your potential customers if you are willing to port this game to the Linux platform? If you are unfamiliar with Linux, we could provide some support or contacts for helping porting your game. Your game engine may already have a Linux version available, check your documentation.

Sincerely,
Valve.

This mail should only be sent after exceeding some threshold of a certain percent (installed/active) gamers who use Proton or a percent breakdown of the total amount of Windows players who in reality are using it for gaming.

Sending such mails would encourage developers and/or publishers to do a real port or at least considering packaging their games with the native Linux version of their game engines.

**Comment by omicron-b** [comment]
Proton players show up as Linux players though.

**Comment by kisak-valve** [comment]
Hello @shakeyourbunny, per platform interest is already available to developers via the Steam wishlist. Take a look at https://steamcommunity.com/games/221410/announcements/detail/1475356649450732547 for more details.
