### ISSUE TITLE
The Witcher 3 (v4) + Radeon + Mesa = Kernel panic

### ISSUE THREAD

**Issue by xanscale** [ValveSoftware/Proton#6461]
# Compatibility Report
- Name of the game with compatibility issues: The witcher 3 v4.00
- Steam AppID of the game: 292030

## System Information
- GPU: AMD AMD Radeon RX 6600 (navi23, LLVM 15.0.5, DRM 3.49, 6.1.6-060106-generic)
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 23.1.0-devel (git-bb003d4 2023-01-17 jammy-oibaf-ppa)
- Kernel version:  6.1.6-060106-generic
- Link to full system information report: [system-info.txt](https://github.com/ValveSoftware/Proton/files/10438274/system-info.txt)
- Proton version: Latest Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## steam log
[steam-292030.log](https://github.com/ValveSoftware/Proton/files/10438271/steam-292030.log)

## Symptoms / Reproduction
With this configuration running the game in DX12 mode after few minutes of perfect gaming, we receive a kernel panic (or just machine become totally frozen)
this is the dmesg log [crash.log](https://github.com/ValveSoftware/Proton/files/10438269/crash.log)
i noticed this bug with standard Ubuntu 20.04 packages, i updated kernel and mesa with last available and nothing changed

Also on https://www.protondb.com/app/292030 there is some other user with same config with same problem

**Comment by kisak-valve** [comment]
Hello @xanscale, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-1385870801.
