### ISSUE TITLE
Forza Horizon 4 freqeuntly crashes on SteamDeck

### ISSUE THREAD

**Issue by pawelsmagala** [ValveSoftware/Proton#6464]
# Compatibility Report
- Name of the game with compatibility issues: Forza Horizon 4
- Steam AppID of the game: 1293830

## System Information
- GPU: Steamdeck
- Driver/LLVM version:Mesa 22.2.0 (git-17e531202)
- Kernel version:  5.13.0-valve36-1-neptune
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/deadeyye/9d03f55e734d42abf6d102f06a02c92b
- Proton version: happens on every of those: 7.0-5, 7.0-6, Proton Experimental

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

Here are a couple of logs ending in crashes https://drive.google.com/file/d/1wZP5ZNuL23fj_Eb8uTv7TEP3bkhN4uhD/view?usp=share_link
Wanted to upload them here but the size limit is too low.

## Symptoms 
The game frequently crashes, after 5-30 minutes of running. Happens most frequently in menus, during loading, or when showing UI information. Those crashes happened from the start, but the frequency was much smaller (ie once per week). After spending many hours in the game, they become persistent (100% it will crash within 30 minutes of play). Reinstalling the game, and clearing the proton cache doesn't help.

## Reproduction
1. Run the game (I use the game of the year edition with all the DLC)
2. Play normally, use menus a lot (which is normal in this game)
3. Game will crash at a random moment, sometimes within 5 minutes, sometimes within 30. Every time I run the game, it will crash, making it unplayable on steamdeck.

**Comment by kisak-valve** [comment]
Hello @deadeyye, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4667#issuecomment-1397650004.

**Comment by pawelsmagala** [comment]
@kisak-valve thanks for comment. This game is marked as playable on Steamdeck. How to see if game is officially or unofficially supported?
