### ISSUE TITLE
MSFS: Getting FENIX A320 installed on Fedora with Proton-Experimental

### ISSUE THREAD

**Issue by rrllrr** [ValveSoftware/Proton#6466]
Hi,

I was trying to install the FENIX A320 for the Microsoft Flight Simulator but I got some error messages while trying it. I used the following command to get the exe file to run:
`STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/raphael/.local/share/Steam" \
STEAM_COMPAT_DATA_PATH="/home/raphael/.local/share/Steam/steamapps/compatdata/1250410" \
/home/raphael/.local/share/Steam/compatibilitytools.d/proton_tkg_experimental.bleeding.edge.7.0.27438.20221022/proton \
run \
FenixSimA320-1.0.6.146.exe`

And these are the error messages I get:
`fsync: up and running.`
`wine: RLIMIT_NICE is <= 20, unable to use setpriority safely`
`wine: failed to start L"C:\\Program Files (x86)\\Steam\\steam.exe"`
`Es konnte keine Anwendung gestartet werden, oder es ist keine Anwendung mit der angegebenen Datei verknüpft.`
`ShellExecuteEx fehlgeschlagen: Prozedur nicht gefunden.`

What can I do to solve this problem?

**Comment by kisak-valve** [comment]
Hello @rrllrr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-1399248995.
