### ISSUE TITLE
Proton does not run ANY  games anymore

### ISSUE THREAD

**Issue by ClumsyDerp** [ValveSoftware/Proton#6467]
Let me preface this by stating, that all titles that will be mentioned here, did run without issues in the past. I've not used my desktop in a while for gaming, so I can't say when - or why - it stopped working.  Lutris runs games fine (Path of Exile) and Linux native games through steam (RimWorld) work as well.

From my testing it affects _every_  (at the very least all I have tried) proton(-ge) versions ranging from experimental to older ones.

I am not even sure whether this is a system, driver, proton or potential DXVK issue.

What the Proton Log has in common is the following unhealthy excerpt:

> err:   D3D11CoreCreateDevice: Failed to create D3D11 device

Here goes anyway:

System Info (Taken from Steam System Info): Note that for gaming the RADV json override is active.

EDIT: [Gist](https://gist.github.com/ClumsyDerp/877ac8e41835605175e9f48288004a79)

> Operating System Version:
    "EndeavourOS Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  6.1.7-arch1-1
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12101006
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20221019.0

> Video Card:
    Driver:  AMD AMD Radeon RX 6900 XT (navi21, LLVM 15.0.7, DRM 3.49, 6.1.7-arch1-1)
    Driver Version:  4.6 (Compatibility Profile) Mesa 22.3.3
    OpenGL Version: 4.6
    [...]
    Primary VRAM: 16384 MB

Logs and screenshots are attached.

I have tried a steam run time reset and re-enabling proto compat layer but to no avail. From my understanding proton does either not recognize my GPU anymore or fails to make use of it, for whatever reasons. All AUR packages have been rebuild, to make sure dependency references are up-to-date, too.

If anyone knows of a fix it'd be greatly appreciated. If this needs to be taken elsewhere (mesa, DXVK?) then a pointer would be much appreciated, too.

Right now I rather not nuke everything if it can be avoided.

This issue may or may not loosely tie into: https://github.com/ValveSoftware/Proton/issues/6416

[steam-867210-songsOfConquest.log](https://github.com/ValveSoftware/Proton/files/10474404/steam-867210-songsOfConquest.log)
[steam-900040-elex2.log](https://github.com/ValveSoftware/Proton/files/10474405/steam-900040-elex2.log)
[steam-1245620-eldenring.log](https://github.com/ValveSoftware/Proton/files/10474406/steam-1245620-eldenring.log)
Forza: https://imgur.com/a/uY91m4c

**Comment by kisak-valve** [comment]
Hello @ClumsyDerp, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by ClumsyDerp** [comment]
Hey, added to the original issue.

I'll leave it here additionally.

[Gist](https://gist.github.com/ClumsyDerp/877ac8e41835605175e9f48288004a79)

**Comment by kisak-valve** [comment]
Thanks, it's not immediately obvious what's misbehaving here, but it seems like the Vulkan render paths could be unhealthy on your system. (https://gist.github.com/ClumsyDerp/877ac8e41835605175e9f48288004a79#file-gistfile1-txt-L300-L316 / https://gist.github.com/ClumsyDerp/877ac8e41835605175e9f48288004a79#file-gistfile1-txt-L579-L595 )

I would temporarily remove / disable AMDVLK, MangoHUD, and vkBasalt, see if that has an effect, and if it does, then re-introduce those back into the mix one at a time.

**Comment by ClumsyDerp** [comment]
@kisak-valve 

Removing AMDVLK seems to have done the trick. Games start up again.

God knows what went awry here, as I haven't made any active changes since forever, outside of updating the system irregularly.

Thanks for the pointer.
