### ISSUE TITLE
[Whitelist] Bejeweled 3 (78000)

### ISSUE THREAD

**Issue by Zero86Sk** [ValveSoftware/Proton#647]
Game on linux runs full speed with 3D acceleration.
It runs better than in Windows 10. (In Win10 its choppy and without 3D)

so whitelist it away :)

My Steam info:
https://gist.github.com/Zero86Sk/d629f657c1ae861c36657cdf238a7765

**Comment by KGOrphanides** [comment]
Confirmed over here. (And quietly thrilled, as Bejewelled 3 is my favourite chilled out casual gaming fix.)

System info:
https://gist.github.com/KGOrphanides/c0fe99f0d9824a8ab434907637c07400

**Comment by snarvaezsoft** [comment]
It is working perfect on Debian 10

My Specs:
Distro Debian 10
Driver: NVIDIA Corporation GeForce GTX 1070 Ti/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 390.77
Desktop: Mate

Installed everything from Debian repository or default, I have not added any extra config or parameter.

Here is the link to my Steam system info:
https://gist.github.com/snarvaezsoft/dd0a970ce0b9ba8ed19a6c91022d2a50

**Comment by dm2912** [comment]
Works perfectly on my system

Mint 19
Kernel 4.4
AMD E-450 APU
Mesa 18.1.6
8gb Ram

**Comment by veikk0** [comment]
I'm unable to get 3D acceleration in this game on my ThinkPad T420 with Intel integrated graphics running Linux Mint 19 MATE edition. 3D acceleration works fine on Windows 7 on the same machine. The lack of acceleration prevents setting the game to any resolution other than 800x600 and removes the 3D transitions between levels. The game has no other issues.

It should be noted that [the game's Steam forum](https://steamcommunity.com/app/78000/discussions/) is filled with complaints about 3D acceleration not working on some systems running Windows 8 or above, so this might very well not be an issue with Proton and the game could just be running "as intended", bugs and all.

When running the game via the /tmp/proton_run script the output is as follows:

    Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
    Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
    Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
    Setting breakpad minidump AppID = 78000
    Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197994276784 [API loaded no]

System info: https://gist.github.com/veikk0/820dc79b63661048bdb03fbb0bb7806d

**Comment by parkerlreed** [comment]
3D accel works here. RX 480, Mesa 18.30, LLVM 8.0.0. Was able to set accel on and bump to highest resolution.

**Comment by dm2912** [comment]
It will work here with 3D and highest resolution on.

But because my machines not very powerful (1.65ghz 4-core) I am playing it on lowest settings possible (as I do all games)

So my "works perfectly" is "works on low settings because my machine is old and weak" :dagger:

**Comment by kisak-valve** [comment]
Found in the 2018-10-05 white list update.

**Comment by bradgy** [comment]
Sorry to necro this... I know it's in the whitelist now but Bejeweled 3 silently crashes for me after clicking play. Either using the native libraries or using steam runtime. Could be an intel thing as it works fine on my desktop at home (NVIDIA) and htpc (AMD).

Antergos x64
Kernel 4.18.16
Proton 3.16 beta 4
Sys details:
https://pastebin.com/31HASfAC

Output from terminal:
https://pastebin.com/nE7UMY1t

Cheers

**Comment by kisak-valve** [comment]
Hello @bradgy, you're seeing the same issue as mentioned at https://github.com/ValveSoftware/Proton/issues/1676#issuecomment-435656108 which is not game or video card specific.

Please open a new issue report for your issue.
