### ISSUE TITLE
VRAM related FPS drop on nvidia gpu

### ISSUE THREAD

**Issue by an9949an** [ValveSoftware/Proton#6470]
## System Information
- GPU: any nvidia laptop gpu (didn't test on desktop), tested on gtx970 and rtx3050
- Driver: nvidia 525.78.01 and older
- Kernel version: 6.1 and older
- CPU: Intel 10500h (hybrid graphics)
- Proton version: all proton versions
- Distro: tested on fedora (35, 36) and manjaro

On all dx12 games (for example cyberpunk and star wars: jedi fallen order) when vram reach 100% fps in the same moment drops significantly and never back to the normal value (drops from for example 70 to 5-10). GPU load in this case displayed as 100%. So, looks like it start to use dynamic memory (ram) as dedicated (vram) instead of putting something don't needed to dynamic and using this free vram space (on windows it produce stutter, but not complete drop).
I didn't test it with dxvk (i don't have so vram heavy dx11 game). Also I don't know is it actual for AMD GPUs.
Issue is very critical for the 4Gb GPUs.

Maybe this issue should be reported to some other place (nvidia? vkd3d?) but I have no ideas how to figure out which.

**Comment by kisak-valve** [comment]
Hello @an9949an, poor performance with the NVIDIA driver if part of the hot path gets bumped to system ram has been a characteristic of the NVIDIA proprietary driver for over a decade, well before modern graphics APIs or Proton. This isn't new or specific to Proton in any way.

**Comment by an9949an** [comment]
> Hello @an9949an, poor performance with the NVIDIA driver if part of the hot path gets bumped to system ram has been a characteristic of the NVIDIA proprietary driver for over a decade, well before modern graphics APIs or Proton. This isn't new or specific to Proton in any way.

Hello @kisak-valve ! Thank you for the answer!

**Comment by maxdwit** [comment]
For Reference from the nvidia forum:
https://forums.developer.nvidia.com/t/vram-allocation-issues/239678/47

This is still an issue in 550 drivers.
