### ISSUE TITLE
Steam Link unable to input controls to GTA5

### ISSUE THREAD

**Issue by thelabcat** [ValveSoftware/Proton#6476]
# Compatibility Report
- Name of the game with compatibility issues: Grant Theft Auto V
- Steam AppID of the game: 271590

## System Information
- GPU: NVidoa GeForce RTX 2060 SUPER
- Driver/LLVM version: nvidia driver 525
- Kernel version: 5.15.0-58-generic (64 bit)
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/thelabcat/626c6bdf32a27734bf7dbfa23223c0a6
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.

- [x] that I have checked whether there are updates for my system available.

[steam-271590.log](https://github.com/ValveSoftware/Proton/files/10493928/steam-271590.log)

## Symptoms 
Although the game can launch via Steam Link on iOS via the touch mouse function, no other controls work. I can only look around and observe.

## Reproduction
Launch GTA5 from Steam Link on iOS, load a game, and attempt to do something (besides looking around).

**Comment by kisak-valve** [comment]
Hello @thelabcat, feedback on the Steam Link app is being tracked on the forums. Please post this at https://steamcommunity.com/app/353380/discussions/7/ for a Steam Link dev to ponder.

**Comment by thelabcat** [comment]
> Hello @thelabcat, feedback on the Steam Link app is being tracked on the forums. Please post this at https://steamcommunity.com/app/353380/discussions/7/ for a Steam Link dev to ponder.

Me: Contacts Steam Support.
Steam Support: "Wrong department! You need to file a bug report on Proton's GitHub page."
Me: Files bug report.
You: **"WRONG DEPARTMENT!** You must go back to Steam, and file a problem report on the community page for Steam Link." [closes as not planned]

Not planned. You don't say?
