### ISSUE TITLE
Update to Wine 8.0 

### ISSUE THREAD

**Issue by FerLuisxd** [ValveSoftware/Proton#6477]
# Feature Request
Wine 8.0 is out, maybe we can see an experimental build with this update
## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Update Wine to the latest release (8.0)
## Justification [optional] 
Direct3D updates
https://www.winehq.org/announce/8.0

**Comment by kisak-valve** [comment]
Hello @FerLuisxd, similar to previous iterations like #1854, #4806. A rebase of Proton onto a new wine version is a substantial time commitment and you can not request that this be expedited.

Proton's devs will rebase on newer wine when they are ready.
