### ISSUE TITLE
Cyberpunk 2077 4k Multi-Monitor Fullscreen displayed on wrong monitor

### ISSUE THREAD

**Issue by coolcatco888** [ValveSoftware/Proton#6478]
# Compatibility Report
- Name of the game with compatibility issues: Cyberpunk 2077
- Steam AppID of the game: 1091500
- Launch Args: MANGOHUD=1 PROTON_LOG=1 VKD3D_CONFIG=dxr,dxr11 VKD3D_FEATURE_LEVEL=12_1 AMD_VULKAN_ICD=AMDVLK gamemoderun %command% -vulkan -USEALLAVAILABLECORES -high cpuLoadRebalance

## System Information
- GPU: AMD Radeon RX 6900 XT ASRock Phantom Gaming D OC
- Driver/LLVM version: LLVM 15.0.6 DRM 3.48
- Kernel version: 6.012-x64v3-xanmod
- Proton version: Proton Experimental [bleeding-edge] Build ID: 10394609
- OS: Ubuntu 22.04 LTS
- Desktop Environment: GNOME 3
- Display Server: Wayland

## I confirm:
- [Y] that I haven't found an existing compatibility report for this game.
- [Y] that I have checked whether there are updates for my system available.

## Symptoms 
When launching Cyberpunk 2077 in fullscreen in a multi-monitor setup, it picks the left-most monitor.

My setup from left to right:
Samsung Monitor, ASUS 4K Gaming Monitor, Dell FHD Monitor

It displays it on the Samsung Monitor when it should display on the ASUS 4K Gaming Monitor. This does not happen on previous versions of Proton.

## Reproduction
1. Have a multi-monitor setup (3 monitors) and use the middle monitor for gaming
2. Launch Cyberpunk with latest bleeding-edge Proton Experimental
3. Note that when Cyberpunk is launched in fullscreen, it displays it on the left-most monitor when it should pick the middle one. (there is no way to make it display on the middle one.)
4. See screenshot for details.
![PXL_20230124_215306943](https://user-images.githubusercontent.com/11560032/214432390-5540ad97-39a2-429e-bc2c-1c619a21b40f.jpg)
[steam-1091500.log](https://github.com/ValveSoftware/Proton/files/10494479/steam-1091500.log)

**Comment by kisak-valve** [comment]
Hello @coolcatco888, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1402765857.
