### ISSUE TITLE
Possible conflict with Kartrider: Drift/Nexon Game Security and certain Steam Guide shortcuts

### ISSUE THREAD

**Issue by nodeunit** [ValveSoftware/Proton#6480]
# Compatibility Report
- Name of the game with compatibility issues: Kartrider: Drift
- Steam AppID of the game: 1184140

## System Information
- GPU: AMD Van Gogh 0405
- Driver/LLVM version:  amdgpu 
- Kernel version:  5.13.0-valve36-1-neptune
- Link to full system information report as [Gist](https://gist.github.com/nodeunit/eff56484697d0eaabb830a33bb4e1986):
- Proton version:  Next 7.0-6

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

Kartrider Drift is almost flawless except for some quirks that break Steam Input.
If you perform a screenshot using the guide shortcut (e.g. Steam + R-shoulder), the game stops responding to any controller input, and the Steam overlay also stops appearing on top of the game. On devices without a keyboard like the Steam Deck, this renders the device softlocked unless a peripheral is plugged in that can force another window to the top (e.g. using a remote device paired with KDE Connect, and then selecting Run command > Create command). Other commands that act similarly to the screenshot shortcut may also trigger this bug, but I could not confirm this.

I suspect this may be triggered by Nexon Game Security, the anticheat used in this game. 

## Reproduction

1. Launch Kartrider Drift
2. Login to the game
3. Perform a screenshot using the Guide button + the right shoulder button. The game should soon stop responding to any controller using Steam Input, as well as no longer showing Steam overlay.

**Comment by kisak-valve** [comment]
Hello @nodeunit, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6446#issuecomment-1403639158.
