### ISSUE TITLE
Yakuza Kiwami crashes on Launch

### ISSUE THREAD

**Issue by RazJuan** [ValveSoftware/Proton#6485]
# Compatibility Report
- Name of the game with compatibility issues: Yakuza Kiwami
- Steam AppID of the game: 834530

## System Information
- GPU: AMD AMD Radeon RX 5700 XT
- Driver/LLVM version: Mesa 22.3.3/LLVM 15.0.6
- Kernel version: 6.1.7-200.fc37
- Link to full system information report as [Gist](https://gist.github.com/): [Gist](https://gist.github.com/RazJuan/8cc5277e16866e36b3bafa2e4e5a726b)
- Proton version: 7.0-6 (tried 7.0-5 and Experimental with same results)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

The game launches, a black screen flashes for around 2 seconds then quits. The game was working fine a few hours prior to the crashing. 

I have done system updates and I have tried different versions of proton but unfortunately nothing has worked. 

[steam-834530.log](https://github.com/ValveSoftware/Proton/files/10519793/steam-834530.log)

## Reproduction
Launch the game.

**Comment by mbriar** [comment]
Have you tried to verify game files? Seems like it fails to load some files.

**Comment by kisak-valve** [comment]
Hello @RazJuan, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2403#issuecomment-1406669237.
