### ISSUE TITLE
Onmyoji in the Otherworld: Sayaka's Story (1746130)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#6490]
# Compatibility Report
- Name of the game with compatibility issues: Onmyoji in the Otherworld: Sayaka's Story
- Steam AppID of the game: 1746130

## System Information
- 512 GB Steam Deck
- Proton version: Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
[steam-1746130.log](https://github.com/ValveSoftware/Proton/files/10529177/steam-1746130.log)

Game suffers from graphical issues that makes it difficult to play. Visual issues can be noticed on the main menu, during the intro cutscene, and once you get into your first battle. (Heads up note that there is a NSFW scene that plays during the introduction, it is possible to fast forward past it to get into the battle quicker.)

How it looks on Deck with Proton:
![Onmyoji Proton 1](https://user-images.githubusercontent.com/78768499/215308686-96607c0d-cf76-4460-a006-c87fa300899b.png)
![Onmyoji Proton 2](https://user-images.githubusercontent.com/78768499/215308690-897d04f0-8144-41e8-b596-7e2d4afcfb15.png)
![Onmyoji Proton 3](https://user-images.githubusercontent.com/78768499/215308692-a4dd995f-9568-4670-895a-5805791c65cd.png)

How it looks on windows (Had to yank from a yt video cause apparently the game doesn't work on my windows laptop initially.)
![Onmyoji Windows 1](https://user-images.githubusercontent.com/78768499/215308752-f0c99c36-ab6b-4a46-a5eb-b2ac7103a584.png)
![Onmyoji Windows 2](https://user-images.githubusercontent.com/78768499/215308755-ae7169b6-9e98-42c9-97eb-f440e0b89e20.png)
![Onmyoji Windows 3](https://user-images.githubusercontent.com/78768499/215308757-f0373985-4e44-4a23-b035-64cc18986e45.png)

## Reproduction
Start the game up and go through the menu, cutscenes, and in game, notice the visual issues.

**Comment by mbriar** [comment]
This looks like it might be related to https://github.com/doitsujin/dxvk/issues/2749

Does it work if you set `PROTON_USE_WINED3D=1 %command%` as launch option?

**Comment by waspennator** [comment]
Tried it, game looks the same when using wined3d too.

**Comment by Blisto91** [comment]
I can reproduce the issue, but I'm not entirely sure what is going on yet.

Using native d3dcompiler and d3dx9 didn't change anything. 
Issue still shows all the way back with proton 3.7.
It doesn't show on Windows with dxvk.
It doesn't show with trace made native on Windows and replayed through Proton or Wine.
And a trace made with dxvk Proton just has the issue baked in when replayed on Windows native.

**Comment by waspennator** [comment]
Testing it out on windows again, apparently it requires MSVCP110.dll to boot properly, otherwise what's already been said. it looks perfectly fine on Windows with DXVK

**Comment by waspennator** [comment]
Graphics are still broken on latest Experimental, but a new regression has emerged too. The game is now dead silent on the latest Experimental build compared to 8.0-4. Also noticed certain text boxes when trying to exit the game are incorrect too.

[steam-1746130.log](https://github.com/ValveSoftware/Proton/files/13372105/steam-1746130.log)


![download](https://github.com/ValveSoftware/Proton/assets/78768499/48d1ce9d-9371-4b8e-8d44-ccb3c0268945)

**Comment by alasky17** [comment]
@waspennator Thank you for the heads up about the audio regression in experimental! Do you happen to know if the exit game text boxes have always been messed up on the steam deck or if they used to be correct?  I originally read your message as saying that both the audio and text boxes were regressions, but the text boxes seem to be broken as far back as 7.0-6 ... I'm wondering if you suspect this is still a regression somewhere, just not Proton?

**Comment by waspennator** [comment]
> @waspennator Thank you for the heads up about the audio regression in experimental! Do you happen to know if the exit game text boxes have always been messed up on the steam deck or if they used to be correct? I originally read your message as saying that both the audio and text boxes were regressions, but the text boxes seem to be broken as far back as 7.0-6 ... I'm wondering if you suspect this is still a regression somewhere, just not Proton?

I'll check it again later today, but I think the audio is the only regression, the text boxes might have always been borked on proton

**Comment by waspennator** [comment]
Broken text boxes do show up on 8.0-6, so those were not introduced by Experimental

**Comment by gofman** [comment]
This should hopefully work better now WRT all the mentioned glitches with the just updated Proton Experimental [bleeding-edge] branch.

UPDATE: out of the box, without any manual installs; not sure about the whole game but at least first battle.

**Comment by waspennator** [comment]
Hello again, opted into the bleeding-edge branch for Proton Experimental and I can confirm not only is the audio working again, but all the graphics seem to be looking correct too! Screenshots from deck with bleeding edge Experimental 

![download](https://github.com/ValveSoftware/Proton/assets/78768499/c7731e64-556f-4320-a614-6d33e51e7ee7)
![download (1)](https://github.com/ValveSoftware/Proton/assets/78768499/7b1d6967-0787-4f3e-9216-4bf4f2ea8800)
![download (2)](https://github.com/ValveSoftware/Proton/assets/78768499/9f103a99-3bb9-438f-9e4f-674a20f6059e)
![download (3)](https://github.com/ValveSoftware/Proton/assets/78768499/7817d47c-be41-4a71-98e2-fe62a7a368bb)

**Comment by waspennator** [comment]
Fixes have made their way into proton Experimental proper, so I guess this is resolved for now.
