### ISSUE TITLE
Cardfight!! Vanguard Dear Days (1881420)

### ISSUE THREAD

**Issue by HiroseKoichi** [ValveSoftware/Proton#6494]
Compatibility Report
Name of the game with compatibility issues: Cardfight!! Vanguard Dear Days
Steam AppID of the game: 1881420

System Information
Gpu: 6700xt
Driver: Mesa 22.3.3
Kernel Version: 6.1.7
https://gist.github.com/HiroseKoichi/1b6e306770687d898fb2812695fbd109
Proton Version: experimental

Symptoms:
When trying to use the keyboard to join online matches or search for cards the game crashes, this makes it impossible to play online modes and makes deck building extremely annoying.

Reproduction:
1. Launch the game with any proton version
2. Navigate to any menu that invokes the keyboard
3. Press any key
4. Game crashes

Proton log
[steam-1881420.log](https://github.com/ValveSoftware/Proton/files/10538929/steam-1881420.log)

**Comment by kisak-valve** [comment]
Hello @HiroseKoichi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6318#issuecomment-1409173817.
