### ISSUE TITLE
Mage Armor AC not being Calculated properly

### ISSUE THREAD

**Issue by tjuju-grimm** [ValveSoftware/Proton#6495]
My warlock has both Bracers of Defense and Cloth of the LIghtbringer attuned, yet whenever I cast mage armor I only receive the bonus (+2) from the bracers of defense and not the bonus (+3) from the cloth. My Ac calculation is 13+dex+2 instead of 13+dex+5.

Is this a bug or am I missing something?

![IMG_0810](https://user-images.githubusercontent.com/124000986/215609532-83a41eae-c585-46af-bbac-b9e22fa1a531.jpg)
![IMG_0811 (1)](https://user-images.githubusercontent.com/124000986/215609549-60d80058-d04e-4acc-9a0d-874eed3a39a1.jpg)
![IMG_0812](https://user-images.githubusercontent.com/124000986/215609556-2d5e4b37-d2de-4f69-8ada-04f036676b09.jpg)

**Comment by kisak-valve** [comment]
Hello @tjuju-grimm, you've come across the issue tracker for Proton, a compatibility layer for running Windows based games on Linux. Without context, this issue report is incoherent.

Closing as invalid.
