### ISSUE TITLE
[Meta] HDR support

### ISSUE THREAD

**Issue by romulasry** [ValveSoftware/Proton#6496]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
HDR support seems like it is already working in wine but it would be nice to link to the bugs all in one place

**Comment by kisak-valve** [comment]
Hello @romulasry, what HDR related support is available is already in Proton Experimental.
