### ISSUE TITLE
Ubisoft Connect broke all Ubisoft games using it

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/Proton#6498]
When you go to launch a Ubisoft game, it will load Ubisoft Connect and then [give an error message](https://www.gamingonlinux.com/2023/02/ubisoft-broke-their-games-on-linux-desktop-and-steam-deck/).

This affects all Ubisoft games using Ubisoft Connect including:

- [Ghost Recon Breakpoint](https://store.steampowered.com/app/2231380/Tom_Clancys_Ghost_Recon_Breakpoint/)
- [The Division 2](https://store.steampowered.com/app/2221490/Tom_Clancys_The_Division_2/)
- [Watch Dogs Legion](https://store.steampowered.com/app/2239550/Watch_Dogs_Legion/)
- [Assassin's Creed Valhalla](https://store.steampowered.com/app/2208920/Assassins_Creed_Valhalla/)
- etc

## System Information
- GPU: Steam Deck / NVIDIA 2080 Ti
- Driver/LLVM version: Steam Deck Stable + Fedora 37
- Kernel version: Steam Deck Stable + 6.1.6 on Fedora
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Here's my log of trying to run Breakpoint on Fedora where Ubisoft Connect now fails: 
[steam-2231380.log](https://github.com/ValveSoftware/Proton/files/10558972/steam-2231380.log)

A log of The Division 2 on Fedora, that log file should have captured the update attempt too.
[steam-2221490.log](https://github.com/ValveSoftware/Proton/files/10558973/steam-2221490.log)

Here's a log of The Division 2 on Steam Deck, after clearing Proton Files:
[steam-2221490.log](https://github.com/ValveSoftware/Proton/files/10559083/steam-2221490.log)

**Comment by TiZ-HugLife** [comment]
Okay, real talk. Valve, why do you even let developers and publishers mandate the use of these extraneous launchers that almost always make life harder for players? What value do they even get from doing this? Isn't it time you just put a stop to this nonsense?

**Comment by EwokExile** [comment]
Confirmed same behavior on my Steam deck and Nobara desktop

**Comment by Code-Slave** [comment]
Confirmed on SD and 22.04.1 budgie

**Comment by steveoa3d** [comment]
Confirmed, Division 2 updated Ubisoft Connect on Steam Deck and now it crashes with same error.  I have tried to reinstall, update GE-Proton, update Deck and still crashes.

**Comment by hovo1990** [comment]
Confirmed on Pop OS 20.04

**Comment by BreadYogurt** [comment]
Confirmed on Gentoo Testing

**Comment by mnlipp** [comment]
Confirmed on Fedora 37 and Gnome

**Comment by dhollinger** [comment]
> Okay, real talk. Valve, why do you even let developers and publishers mandate the use of these extraneous launchers that almost always make life harder for players? What value do they even get from doing this? Isn't it time you just put a stop to this nonsense?

Simple, those companies are big and have a lot of players. So, if Valve demands they don't use their launchers, then those Publishers can leave Steam, taking their userbase with them and likely hurting the Steam Deck's potential customer base.

**Comment by goffy59** [comment]
I changed my lutris wine version from GE 35/36 to the default one that ships with lutris(default) and it launched and let me play but after a short amount of time it kicked me for corruption of the game files/EAC.

**Comment by rasmus91** [comment]
> I changed my lutris wine version from GE 35/36 to the default one that ships with lutris(default) and it launched and let me play but after a short amount of time it kicked me for corruption of the game files/EAC.

Would this happen with any Ubisoft game i wonder?


Also in regards to OP, ran into this same problem on Assassin's Creed Odyssey on Ubuntu 22.04

**Comment by bastiHST90** [comment]
I know the division 2 Ubisoft connect version isn't working on Linux, but the steam version is. Maybe that's why? idk (in response to goffy59)

**Comment by Danacus** [comment]
I can't launch Ubisoft Connect either, regardless of whether I try to launch it directly or by launching a game.

**Comment by Krulas** [comment]
Confirming same behavior here ZorinOS 16 using proton experimental. Anno 2205 and 2070 are now broken. I manually installed Uplay in wine, Uplay works fine until it updates. update appears to have been pushed today, It has worked flawlessly for over a year.

**Comment by goffy59** [comment]
> > I changed my lutris wine version from GE 35/36 to the default one that ships with lutris(default) and it launched and let me play but after a short amount of time it kicked me for corruption of the game files/EAC.
> 
> Would this happen with any Ubisoft game i wonder?
> 
> Also in regards to OP, ran into this same problem on Assassin's Creed Odyssey on Ubuntu 22.04

Sorry for lack of clarification.. I was speaking of Division 2. But AC: O is singleplayer so I assumed that would work but up above someone mentioned it doesn't work either.

**Comment by bastiHST90** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6498#issuecomment-1412528761

But that someone wasn't using Lutris own wine version...?

Maybe even an old Proton/wine version might work? I can't test now unfortunately 

Because lutris' wine version is pretty old now.

**Comment by TiZ-HugLife** [comment]
> > Okay, real talk. Valve, why do you even let developers and publishers mandate the use of these extraneous launchers that almost always make life harder for players? What value do they even get from doing this? Isn't it time you just put a stop to this nonsense?
> 
> Simple, those companies are big and have a lot of players. So, if Valve demands they don't use their launchers, then those Publishers can leave Steam, taking their userbase with them and likely hurting the Steam Deck's potential customer base.

Why do they even care about those launchers though? Like, what are the launchers *actually doing* for these companies?

**Comment by goffy59** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6498#issuecomment-1412531245

I am going to download AC: O on steam, then if it works I will then download Division 2 from the same install of AC: O on steam to try it out. I will let you know once I finish downloading 108gb. I'll try experimental and GE editions/etc.. gonna be about an hour to download/etc.

**Comment by Danacus** [comment]
I can confirm that Ubisoft Connect *does* work on old versions of wine, such as lutris wine 7.2. The main downside is that the 100% CPU usage at startup bug occurs again when using such old version of wine.

Edit: or at least well enough to launch a game, the launcher UI itself does not work.

Edit 2: another unfortunate side-effect is that controller support on old versions of wine is a lot worse.

**Comment by bastiHST90** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6498#issuecomment-1412539026

You don't have to do that 😅
Is just something I thought.


I personally don't have any ubisoft games on Linux. I use Lutris to launch my Ubisoft games, which are all installed through the Ubisoft launcher.

From what I can see, for everyone the launcher just crashes. But you could use the launcher with Lutris' old wine version. That's why I think older proton/wine versions might work.

With The division 2 only the steam version is working on Linux with anti cheat, the Ubisoft connect version isn't working with linux. (iirc)

**Comment by goffy59** [comment]
> I can confirm that Ubisoft Connect _does_ work on old versions of wine, such as lutris wine 7.2. The main downside is that the 100% CPU usage at startup bug occurs again when using such old version of wine.
> 
> Edit: or at least well enough to launch a game, the launcher UI itself does not work.
> 
> Edit 2: another unfortunate side-effect is that controller support on old versions of wine is a lot worse.

For which games? As previously mentioned Div 2 works on older version of wine/lutris but you get kicked out/crashes with EAC error after about 20 minutes.

**Comment by goffy59** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6498#issuecomment-1412544876

I was using Lutris/GE to play Div2 with some EAC files I got from reddit:https://www.reddit.com/r/linux_gaming/comments/10gag7d/division_2_uplay_version_working_on_wine/

And for about a week it was working perfect. Now since all this started it doesn't work. So I am trying to figure out... is the issue with GE/LUTRIS/WINE/STEAM/etc or the special EAC files I got from that link above. I didn't buy Div 2 on steam so couldn't really test. Only other way is to install AC: O and then install Div 2 through the launcher via steam/AC:O. Anyhow I will let you know how it goes.

**Comment by Danacus** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6498#issuecomment-1412545621

I am playing Trackmania, it does not use EAC. Using an older version of wine (7.7 or lower) just fixes the Ubisoft Connect crash.

**Comment by bastiHST90** [comment]
Trackmania. Exactly what I play on Ubisoft most of the time haha 👍🏻

Good to know that it works with an older version.

Tommorow the game will release on steam itself. I'm wondering how that will work out of the box, with the Ubisoft launcher...

**Comment by jszarin** [comment]
> Okay, real talk. Valve, why do you even let developers and publishers mandate the use of these extraneous launchers that almost always make life harder for players? What value do they even get from doing this? Isn't it time you just put a stop to this nonsense?

PC gamers: I hate consoles because everything is controlled by one company. PC is much more free!

Also PC gamers: I HATE THIRD-PARTY GAME STORES! EVERYTHING SHOULD RUN VIA STEAM LAUNCHER

**Comment by dhollinger** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6498#issuecomment-1412555950

I don't hate third-party game stores. The issue here is that one store/client should not launch another one. Especially when Valve specifically called out Launchers as a pain point for supporting the Steam Deck

**Comment by TiZ-HugLife** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6498#issuecomment-1412555950

Your non-productive and blatantly provocative reply ignores several facts.

1. It's not that the third-party game store exists, it's that it has shoved itself between the store the game was actually bought from and the game itself, which only negatively impacts the experience. It mainly only serves to tell the player, "hey, you could have bought this from *our* store! you *should have* bought this from our store! we exist, and we want to make sure you know that! give us more of your money and data!"
2. Steam Deck is aiming to create a console-like experience, and consoles *absolutely do not* allow games to shove launchers in the middle.
3. It broke games that were already working, because it's an additional point of failure. And fail it did. The game itself didn't broke. Their stupid launcher did, because it is probably trying to do a bunch of things that nobody wants.
4. Cross-play is not a valid defense for third-party launchers shoving themselves in the middle, because a wide variety of games implement it just fine without a whole-ass program between the storefront and the game.

What I think should be mandatory is not a complete abolition of third-party launchers from the Steam store, but the ability to go straight into the game without any middlemen. I'm sure that these companies would respond by absolutely crippling the functionality of their game when launched this way, but I think that it *needs* to be possible.

It also bears mentioning that games bought from third party stores can be integrated into Steam with community-made tools, and when they are launched this way, they are less intrusive than games bought on Steam that are bringing their own launcher.

**Comment by Oxygels** [comment]
It's pretty sad since Trackmania is released tomorrow on Steam.
(Confirmed on Arch Linux)

**Comment by Saancreed** [comment]
Try Proton Experimental `bleeding-edge` branch, it should have a [fix](https://github.com/ValveSoftware/wine/commit/ae2fad7338cc2f914536469656448ecb5fdcf294) for this already.

**Comment by goffy59** [comment]
> Try Proton Experimental `bleeding-edge` branch, it should have a [fix](https://github.com/ValveSoftware/wine/commit/ae2fad7338cc2f914536469656448ecb5fdcf294) for this already.

Installed AC: O (which gave same error as this issue is about), installed Div 2 through the same launcher of the AC:O install and Div 2 worked for about 20 minutes and kicked me via EAC error.

Proton GE and experimental both fail.

**Comment by Oxygels** [comment]
> Try Proton Experimental `bleeding-edge` branch, it should have a [fix](https://github.com/ValveSoftware/wine/commit/ae2fad7338cc2f914536469656448ecb5fdcf294) for this already.

It fixed my issue ! Thanks for the quick answer, have a great day !

It was for trackmania initially but since it's a launcher problem it should be the same for other games.
My specific setup is Heroic Launcher + Proton Experimental (with bleeding-edge beta enabled via steam)

**Comment by goffy59** [comment]
> > Try Proton Experimental `bleeding-edge` branch, it should have a [fix](https://github.com/ValveSoftware/wine/commit/ae2fad7338cc2f914536469656448ecb5fdcf294) for this already.
> 
> It fixed my issue ! Thanks for the quick answer, have a great day !

For which game?

I can confirm does not work for Steam - AC: O with Proton Experimental.

Edit: Also using lutris with wine ge (latest as of this post) gives same error as this current issue shows (error launching ubisoft connect).

edit2:

Division 2 and Assassins Creed: Odyssey are not working on steam or lutris. Div 2 via ubisoftconnect can launch on lutris with default included wine (old) but kicks you out after 20 minutes with EAC error.

**Comment by hovo1990** [comment]
So just changed to the beta channel of proton experimental "bleeding edge" and Division 2 launched.

**Comment by goffy59** [comment]
> So just changed to the beta channel of proton experimental "bleeding edge" and Division 2 launched.

Is there another proton experimental I am not aware of? Also, did it kick you after 30 minutes?

**Comment by Oxygels** [comment]
> > So just changed to the beta channel of proton experimental "bleeding edge" and Division 2 launched.
> 
> Is there another proton experimental I am not aware of? Also, did it kick you after 30 minutes?

Correct me if I'm wrong but you know that proton and wine-ge/proton-ge aren't the same, right ?

**Comment by spaghetticodez** [comment]
> > So just changed to the beta channel of proton experimental "bleeding edge" and Division 2 launched.
> 
> Is there another proton experimental I am not aware of? Also, did it kick you after 30 minutes?

Library - Search proton exp. - right click - prop. - betas - bleeding edge.

**Comment by goffy59** [comment]
> 

I am totally aware. I've been trying both. Also just switched experimental to bleeding edge and going to try it out.. Will edit this reply when I confirm if it lets me play for more than 20-30 minutes.

After following spaghetticodez instructions to change experimental to bleeding edge AC: O launched and was playable. Now I am installing Div 2 through the same launcher and going to check if it lets me play for more than 20-30 minutes. I will update this post when I get the results. But so far for me AC:O is back to working on bleeding edge (experimental).

edit:

I cannot launch DIV 2 through the AC:O steam install. I also do not own Div 2 on steam; I have it on ubisoft connect. At this point I cannot play. Seems like for me in my situation I need GE to add the fixes from experimental into wine-ge for lutris. SO maybe he will release wine-ge 37 next? Fingers crossed.

**Comment by jeremynr** [comment]
> > > So just changed to the beta channel of proton experimental "bleeding edge" and Division 2 launched.
> > 
> > 
> > Is there another proton experimental I am not aware of? Also, did it kick you after 30 minutes?
> 
> Library - Search proton exp. - right click - prop. - betas - bleeding edge.

This seems to be the fix! I have been playing for 30+ minutes with no issues! Thanks for the instructions @spaghetticodez !!!

**Comment by jszarin** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6498#issuecomment-1412692494

great! hopefully this patch makes its way downstream soon for us bottles users who bought games directly thru Ubisoft.

**Comment by rasmus91** [comment]
> > Replying to https://github.com/ValveSoftware/Proton/issues/6498#issuecomment-1412528761
> 
> But that someone wasn't using Lutris own wine version...?
> 
> Maybe even an old Proton/wine version might work? I can't test now unfortunately 
> 
> Because lutris' wine version is pretty old now.

Sorry, been busy, my AC:O experience was installing via steam. (As in OPs example)

And Ubisoft connect just immediately crashes when trying to launch it.

**Comment by goffy59** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6498#issuecomment-1412778956

If you follow spaghetticodez(https://github.com/ValveSoftware/Proton/issues/6498#issuecomment-1412643957) instruction on switching proton experimental to bleeding edge AND then switching AC:O proton to proton experimental it will work for you just fine.

Division 2 will not work for us non-steam users though. Please GE add upstream fixes to wine-proton-ge(lutris build)! :)

edit:

if you want a quick and dirty "fix". If you are on lutris/uplay just have lutris use the proton-experimental (after switching to bleeding edge inside steam). You can do a symlink or just copy the proton - experimental directory over.. If you need clarification feel free to ask.

**Comment by asad-albadi** [comment]
same for me with AC Odyssey

**Comment by OlliC** [comment]
Will this fix be in Proton 7.0-6 ? I would rather wait for the next stable release than using Experimental.

**Comment by bblacher** [comment]
@OlliC My guess is that it won't be in 7.0-6. They already have 7.0-6 in Proton Next and I think they won't add any features to it anymore. I also think they are rebasing Proton to wine 8.0 right now like they did last year. I think we can expect Proton 8.0-1 this month which should also contain the Ubisoft Connect fix.

**Comment by jason-p-pickering** [comment]
AC Valhalla launches but crashes after about 15 minutes of gameplay on  Ubuntu 22.04 and using the suggested workaround of @spaghetticodez

**Comment by gegoxaren** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6498#issuecomment-1412646784

I found a way to make it work:

https://github.com/bottlesdevs/Bottles/issues/2648#issuecomment-1414027899

**Comment by bryanasdev000** [comment]
Working like a charm in Ghost Recon Wildlands, played about an hour without any issue on NixOS unstable.

**Comment by kisak-valve** [comment]
Hello, it looks like https://github.com/ValveSoftware/wine/commit/f497ac98efbb3c924a7ab9630963b88e20385ca4 has been fast tracked into Proton 7.0-6. Please retest with the Proton Next build which should include this commit.

**Comment by bryanasdev000** [comment]
> Hello, it looks like [ValveSoftware/wine@f497ac9](https://github.com/ValveSoftware/wine/commit/f497ac98efbb3c924a7ab9630963b88e20385ca4) has been fast tracked into Proton 7.0-6. Please retest with the Proton Next build which should include this commit.

Retried with GRW, having some lags but otherwise ok..

**Comment by Danacus** [comment]
Can confirm Ubisoft Connect works correctly with Proton Next. Tried using Trackmania on Steam.

**Comment by bastiHST90** [comment]
> Hello, it looks like [ValveSoftware/wine@f497ac9](https://github.com/ValveSoftware/wine/commit/f497ac98efbb3c924a7ab9630963b88e20385ca4) has been fast tracked into Proton 7.0-6. Please retest with the Proton Next build which should include this commit.

It's working for me too. I tried Trackmania.

The only whing that's odd, but maybe game specific, is that it's seems like Trackmania is forced vsync on in gaming mode, but not on desktop. My old non-steam shortcut didn't had that problem.

Edit: ah no, wait. I had to set my fps to 60 and then back to unlimited again.

Ok, working great now.

**Comment by Danacus** [comment]
One thing I noticed is high CPU usage while starting Ubisoft Connect, which is also the case on older versions of wine. It might be a side-effect of this workaround.

**Comment by bastiHST90** [comment]
> One thing I noticed is high CPU usage while starting Ubisoft Connect, which is also the case on older versions of wine. It might be a side-effect of this workaround.

I had that with my non-steam Trackmania game when I accidentally clicked on Ubisoft connect in-game. Yesterday i had the same. Idling in the main menu and super high CPU usage. I turned the Ubisoft overlay off in the launcher. Might have helped. But I don't know.

**Comment by rasmus91** [comment]
> > > So just changed to the beta channel of proton experimental "bleeding edge" and Division 2 launched.
> > 
> > Is there another proton experimental I am not aware of? Also, did it kick you after 30 minutes?
> 
> Library - Search proton exp. - right click - prop. - betas - bleeding edge.

I did this with AC Odyssey, and now the game kind of freezes and then takes a full minute or so to load the menu (map, inventory, etc) whenever i pause during gameplay.

Otherwise the game send to play as smoothly as it should

**Comment by kisak-valve** [comment]
Proton 7.0-6 has now shipped to resolve this issue.

Please use the per-game compatibility reports to discuss the behavior of individual games.

**Comment by kibibites** [comment]
I am still unable to launch UNO with the error that it cannot find the ubisoft connect installation
The compatibility is set to Proton Experimental with the bleeding-edge beta; Is there something I missed?

## System Details
```
OS: Arch Linux
KERNEL: 6.2.1-arch1-1
CPU: 12th Gen Intel Core i7-1260P
GPU: AMD Radeon RX 6600 XT (navi23, LLVM 14.0.6, DRM 3.48, 6.0.11-arch1-1)
GPU DRIVER: 4.6 Mesa 22.2.3RAM: 16 GB
```

**Comment by Richard-Degenne** [comment]
> Please use the per-game compatibility reports to discuss the behavior of individual games.

You probably should look for or create a new issue specifically for UNO.

**Comment by stixholder** [comment]
Ubisoft Connect will update work with Proton 7.0-6, and will also with 8.0-2 - provided that the Steam client has been switched to "Offline Mode" before - but only with the first one I'm able to actually launch games like "Assassin's Creed Black" Flag or "Far Cry Blood Dragon".

**The really ugly and bad part:** all your installed games and progress will vanish, after switching forth and back to and from another Proton version, like to 8.0-2 and back - although the game files and data are still in place - a real killer "feature"!

**Comment by lmm1191** [comment]
I know this thread is closed but I am still having issues with this. But, something different happened. After installing the Ubisoft game on steam, Ubisoft Connect opens and does a self update. But, after that, it opens Uplay. Then closes, then opens ubisoft connect again (as per the icon that shows on task bar) and comes with the error "Unrecoverable error"

Tried 7.0.6, Experimental, Lutris 7.2.2

System is Arch Linux
CPU: Intel i5 10th Gen
GPU: RTX 3070 Mobile
