### ISSUE TITLE
City of Gangsters (1386780)

### ISSUE THREAD

**Issue by Operativ** [ValveSoftware/Proton#6503]
# Compatibility Report
- Name of the game with compatibility issues: City of Gangsters
- Steam AppID of the game: 1386780

## System Information
- GPU: RX 5700 XT
- System: Pop! OS based on Ubuntu 22.04 LTS (up to date)
- Proton version: 7.0.6 and Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

City of Gangsters throws "App is not responding" errors on second and subsequent launches.

Compute shaders on/off do not make a difference. Tutorials on/hints only/off do not make a difference.

## Reproduction

Install City of Gangsters, launch it, close it, launch it and wait for a few seconds.

**Comment by kisak-valve** [comment]
Hello @Operativ, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5056#issuecomment-1416774297.
