### ISSUE TITLE
Proton Next to 7.0.6 transition Steam library issue

### ISSUE THREAD

**Issue by Operativ** [ValveSoftware/Proton#6504]
On 3rd February 2023 my Proton Next transitioned into 7.0.6 (and the Next became unavailable for selection). This caused strange behaviour for 7.0.6, as it cannot be uninstalled due to missing shared files error by Steam.

- Attempted to switch main Proton compatibility to Experimental, then uninstall 7.0.6, did not work.
- Verified file compatibility of 7.0.6, nothing unusual came out of it.
- Removed SteamApps folder of Proton 7.0.6, then verified files, did not work.

It seems like Proton 7.0.6 is missing some dependencies that allow it to be properly uninstalled from Steam library (tools).

System: Pop! OS based on Ubuntu 22.04 LTS (up to date)

**Comment by kisak-valve** [comment]
Hello @Operativ, you've described https://github.com/ValveSoftware/steam-for-linux/issues/7407. One or more games are currently configured to use the Proton version you're telling Steam to remove which leads to this scenario. If you completely close Steam and run it from a terminal, it should tell you which games need checked in the terminal spew.

Closing in favor of the older issue report.
