### ISSUE TITLE
Star Wars: Knights of the Old Republic II (208580) 

### ISSUE THREAD

**Issue by DarthMDev** [ValveSoftware/Proton#6506]
# Compatibility Report
- Name of the game with compatibility issues: Kotor II
- Steam AppID of the game: 208580

## System Information
Steam Deck
- Proton version: proton 7.0

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
When running the game via proton I run into a black screen issue on the menu so i cant do anything
(yes i have tried running in windowed mode and alt tabbing with no success)
game works with steam linux runtime but would prefer proton for the mods

## Reproduction

Launch the game and get into the menu 
-->

**Comment by kisak-valve** [comment]
Hello @MichaelGDev48, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6049#issuecomment-1420833544.

**Comment by DarthMDev** [comment]
My bad thank you
