### ISSUE TITLE
Prototype (10150)

### ISSUE THREAD

**Issue by ffrasisti** [ValveSoftware/Proton#6508]
# Compatibility Report
- Name of the game with compatibility issues: Prototype 
- Steam AppID of the game: 10150

## System Information
- Steam Deck 512GB
- OS: SteamOS Latest Stable
- Proton version: 7.0.6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. (There was some thread about the game but it was ancient and dead, and listed issues but it wasnt formatted as a compatibility report. I apologize if this shouldnt be here. 
)
- [x] that I have checked whether there are updates for my system available.

People report on protondb that Proton 6.3-8 runs it perfectly, other say it works but with no audio. In any case, it seems to be a regression.
The game currently has a Steam Deck Playable rating which it probably shouldn't have as of now. The game _for me_, seems to only run correctly on one old build of Proton GE, Proton-7.1-GE-1. Anything else, including new official proton versions or new GE builds will have the freezes.

## Symptoms 
Game freezes moments after getting to gameplay

## Reproduction
Pick your settings (I maxed them given the game's age)
Launch the game, start a new file, skip the cutscene, play for less than a minute before it freezes

**Comment by kisak-valve** [comment]
Hello @ffrasisti, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/164#issuecomment-1420247870. Yes, that issue report does predate a more formalized compatibility report template.
