### ISSUE TITLE
Social club error 17 on Ubuntu 20.04

### ISSUE THREAD

**Issue by Deathvvish** [ValveSoftware/Proton#6512]
Is it possible to fix it now?

**Comment by kisak-valve** [comment]
Hello @Deathvvish, in general, we're using one issue report per unofficially supported game title, and there's not enough information here to evaluate this issue.

Please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the affected game's launch options, and reproduce the issue. Also, copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

After you have collected that information, please search for the compatibility report for your game that is giving you trouble and attach the generated $HOME/steam-$APPID.log to the game's compatibility report as a file (Proton logs compress well if needed.) along with a link to your system information and describe the game behavior you're seeing.
