### ISSUE TITLE
Battlefield 1 not launching at all

### ISSUE THREAD

**Issue by Kidplayer666** [ValveSoftware/Proton#6516]
# Compatibility Report
- Battlefield 1
- Steam AppID of the game: 1238840

## System Information
- GPU: GTX 750Ti
- Driver/LLVM version: Nvidia 525.85.05
- Kernel version: 6.1.9-1
- Link to full system information report as [Gist](https://gist.github.com/Kidplayer666/95fdf7541223f4b64fb47e5d83b84689):
- Proton version: Attempted to use both proton experimental and the latest GE
- 
## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
I have this game on Steam, and it ran perfectly on windows. I've now tried installing it on Linux, but it simply does not run. I've tried the recommended suggestions on protondb.com, this guide [here](https://www.reddit.com/r/SteamDeck/comments/tx6srv/guide_installing_origin_on_the_steam_deck_the/) using proton GE and proton Experimental with a combination of the following commands 
`DXVK_ASYNC=1 %command%
STEAM_COMPAT_DATA_PATH="/home/MYUSERNAME/.local/share/Steam/steamapps/compatdata/3955941937" gamemoderun %command%'
MANGOHUD=1 DXVK_HUD=compiler RADV_PERFTEST=gpl gamemoderun %command%
DXVK_ASYNC=1 %command%
STEAM_COMPAT_DATA_PATH="STEAM_COMPAT_DATA_PATH="/home/MYUSERNAME/.local/share/Steam/steamapps/compatdata/3955941937/pfx/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop/" gamemoderun %command%'`

**Comment by kisak-valve** [comment]
Hello @Kidplayer666, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5047#issuecomment-1426030341.
