### ISSUE TITLE
American conquest : Fight Back (115220)

### ISSUE THREAD

**Issue by josef256** [ValveSoftware/Proton#6517]
# Compatibility Report
- Name of the game with compatibility issues: American conquest : Fight Back
- Steam AppID of the game: 115220

## System Information
- GPU: Steam Deck
- Driver/LLVM version:  4.6 Mesa 22.2.0
- Kernel version: 5.13.0-valve36-1-neptune
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-115220.log](https://github.com/ValveSoftware/Proton/files/10709300/steam-115220.log)

## Symptoms 
unlike the original game (American conquest : 115210) which crash randomly, in this game it crash whenever i click on a certain unit ability(artillery).

## Reproduction
1-open the game 
2- select a scenario where you have artillery units
3-select the artillery unit
4- click on **fire grapeshot**

**Comment by kisak-valve** [comment]
Hello @josef256, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1211#issuecomment-1426046867.
