### ISSUE TITLE
Far Cry 3 Blood Dragon

### ISSUE THREAD

**Issue by cretsiah** [ValveSoftware/Proton#6519]
# Compatibility Report
- Name of the game with compatibility issues: Far Cry 3 Blood Dragon 
- Steam AppID of the game: 233270

## System Information
- GPU: RX 550 4gig 
- Driver/LLVM version: driver: amdgpu, chip ID: 1002:699f, POLARIS12 DRM 3.40.0 5.10.0-21-amd64 LLVM 11.0.1 Mesa 20.3.5
- Kernel version: 5.10.0-21-amd64 x86_64
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/cretsiah/9168c43fef5166f295626dcd9720a858
- Proton version: 6.3-8

## I confirm:
- [ yes] that I haven't found an existing compatibility report for this game.
- [ yes] that I have checked whether there are updates for my system available.

[steam-233270.log](https://github.com/ValveSoftware/Proton/files/10711825/steam-233270.log)

## Symptoms 
- Under proton 6.3-8 missing uplay / ubisoftconnect comes up with Error Code: 1
- 53 missing files 
- re-install doesnt work
- clearing cache doesnt work

**Comment by kisak-valve** [comment]
Hello @cretsiah, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6514#issuecomment-1426389229.
