### ISSUE TITLE
Update Directx .dll files in compdata

### ISSUE THREAD

**Issue by londiebrondie** [ValveSoftware/Proton#6522]
# Feature Request

## I confirm:
- That I haven't found another request for this feature.
- That I have checked whether there are updates for my system available that
      contain this feature already.
- That this would be a sick feature to have.

## What I'm requesting: 
-I would like for proton to update the directx .dll files in /home/deck/.steam/steam/steamapps/compdata/gameid/pfx/drive_c/windows/system32 (and /windows/syswow64) for proton experimental. More info below in the "In Depth Notes"

## Why Proton and not Wine:
-It would be more convenient for steam deck users (and everyone) to add this to proton instead of wine.

## Possible Issues:
-I don't know why this hasn't already been done, maybe because updating the .dll files might mess up other games. This is why I suggest this feature being part of proton experimental.

## In Depth Notes:
-The .dll files that bottles use would be perfect for proton experimental. When testing the knuckle sandwich demo on steam (through any proton version), it crashes at a certain point, giving a directx error. When running through bottles, it can be run
all the way through with no issues. I decided to run a test: I transferred the /windows/system32 (and syswow64) files from the bottles directory to the steam compdata directory /windows/system32 (and syswow64) files and ran the game as normal, through the latest proton version (the one I has used before). The only difference from before was the transfer of system32 and syswow64 files. The game ran perfectly fine this time, and I hope you can integrate this feature as a default for users who do not wish to tinker with the game.

**Comment by Etaash-mathamsetty** [comment]
what wine version were you using in bottles

**Comment by kisak-valve** [comment]
Hello @londiebrondie, this feature request is not actionable as you have presented it. Wine as a sub-project gets built on every change to Proton Experimental including those dlls.

If you're able to determine what specific commit fixed your issue in upstream wine, you can request that commit be evaluated for backport to the version of wine found in Proton.

A general rebase of Proton onto a newer version of wine takes a substantial amount of time and can not be expedited by public request. Proton's devs will rebase on newer wine when they are ready.
