### ISSUE TITLE
Update dxvk to a newer version on proton experimental (2.0 or 2.1)

### ISSUE THREAD

**Issue by londiebrondie** [ValveSoftware/Proton#6523]
# Feature Request
Update dxvk to a newer version on proton experimental (2.0 or 2.1)
## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
I would like the packaged in dxvk to be update to a newer version, preferably version 2.0 or the latest version. I have found that some games that don't run through any of the vanilla proton version will run just fine through a custom version of proton that utilizes the newest version of dxvk. Yes, I have narrowed down that this is what makes the specific game I have in mind work (Knuckle Sandwich Demo). I myself did some research, and have found that the latest version of proton experimental uses dxvk v1.10.3-28-ge3daa699 or dxvk-nvapi. In conclusion, an updated version of dxvk would be greatly appreciated. 
## Risks
Of course, I would like this feature to be included in proton experimental, as including it in proton 7.0-6 would be inappropriate. It may or may not break some games that already run fine through proton 7.0-6.

**Comment by mbriar** [comment]
Experimental already ships current DXVK master, there is nothing to update.

**Comment by kisak-valve** [comment]
You can see what git commit of DXVK is used in the current build of Proton Experimental by selecting the branch and following the link to the git submodule. Example: https://github.com/ValveSoftware/Proton/tree/experimental_7.0 points at https://github.com/ValveSoftware/dxvk/tree/caf31033d711460e86781b16a4d9b0f41fa9e817 at the moment.

Closing as invalid.
