### ISSUE TITLE
Proton fails to find nvngx.dll on Debian

### ISSUE THREAD

**Issue by MiroslavR** [ValveSoftware/Proton#6524]
As a result, DLSS is not available in games. This is with Debian Testing's nvidia-driver package, version 520.56.06. Proton Experimental.

On Debian, the DLLs are located in `/usr/lib/x86_64-linux-gnu/nvidia/current/wine/` but Proton looks for them in `/usr/lib/x86_64-linux-gnu/nvidia/current/nvidia/wine`, which does not exist.

In `find_nvidia_wine_dll_dir`, `libglx_nvidia_realpath` = `/usr/lib/x86_64-linux-gnu/nvidia/current/libGLX_nvidia.so.520.56.06`. 

The issue can be worked around by symlinking `nvidia -> ../current/` or just copying the DLLs to the wineprefix manually.

**Comment by kisak-valve** [comment]
Hello @MiroslavR, this issue should also be reported to Debian's package maintainer(s) for the NVIDIA proprietary driver. `libnvidia-ngx1` inconsistently placing the library in a different relative folder compared to all other install methods of the driver could be considered a packaging bug.

**Comment by MiroslavR** [comment]
Hi, thanks for the quick response. I've reported it to the package maintaners: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031185

**Comment by MiroslavR** [comment]
This has been fixed at the package level. Closing the issue.
