### ISSUE TITLE
Catherine Classic (893180)

### ISSUE THREAD

**Issue by ItsRogueRen** [ValveSoftware/Proton#6527]
# Compatibility Report
- Name of the game with compatibility issues: Catherine Classic
- Steam AppID of the game: 893180

## System Information
- GPU: AMD RX 6650 XT
- Driver/LLVM version: Mesa 22.3.5
- Kernel version: 6.0.12-76060006-generic
- Link to full system information report as [Gist](https://gist.github.com/ItsRogueRen/5142b4d7c164c616cb9175f9acadca57): 
- Proton version: 7.0-6

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

[steam-893180.log](https://github.com/ValveSoftware/Proton/files/10717522/steam-893180.log)

## Symptoms 
Completely unplayable. Game SOMETIMES loads the main menu on some GE builds of proton, but hangs on loading the game. Standard Proton usually results in the game immediately crashing or freezing. Some users report being able to play somewhat after significant tweaking but typically with some sort of drawback such as skipping all cutscenes. The furthest I personally have been able to get to is the loading screen even after creating a new file, which resulted in an endless loading screen even after waiting upwards of 45 minutes.

## Reproduction
1) Install Catherine
2) Start game
3) Game crashes

UPDATE: Added system info gist

**Comment by kisak-valve** [comment]
Hello @ItsRogueRen, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2207#issuecomment-1427159091.

**Comment by ItsRogueRen** [comment]
> Hello @ItsRogueRen, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2207#issuecomment-1427159091.

My bad, I could have sworn I looked for an existing report and didn't find one
