### ISSUE TITLE
Forza 4 Steam Can't sign into Xbox Live

### ISSUE THREAD

**Issue by UberDog55** [ValveSoftware/Proton#6531]
# Compatibility Report
- Name of the game with compatibility issues: Forza Horizon 4
- Steam AppID of the game: 1293830

## System Information
- GPU:  AMD Radeon 6950XT
- Driver/LLVM version:  amdgpu
- Kernel version:  6.1.11-arch1-1 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7.0-6

## I confirm:
- [ *] that I haven't found an existing compatibility report for this game.
- [ *] that I have checked whether there are updates for my system available.

## Symptoms 

When loading up the game, there is no option to login. Only two options, both of which just provide an error warning saying:

"You may not proceed without being signed in to a profile."

Screenshots below:

https://imgur.com/7m4YYOm](steam://openurl/https://imgur.com/7m4YYOm

https://imgur.com/o6bomPd](steam://openurl/https://imgur.com/o6bomPd

The game did work briefly when I bought it last year when my PC had Zorin OS 16.2 installed. But I couldn't play it due to the nvidia drivers at the time.

Now what I have Arch installed using Proton experimental, 7.0-6 and 6.3-8 (anything earlier doesnt load the game) I experiance what it mentioned above.

Steam report:

https://gist.github.com/UberDog55/861b8a41da4fe15ef0af2a64053b44c2

## Reproduction

[ForzaHorizon4_dxgi.log](https://github.com/ValveSoftware/Proton/files/10725832/ForzaHorizon4_dxgi.log)

**Comment by kisak-valve** [comment]
Hello @UberDog55, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4667#issuecomment-1428605264.
