### ISSUE TITLE
Quantum Conundrum (200010)

### ISSUE THREAD

**Issue by Aperture32GLaDOS** [ValveSoftware/Proton#6532]
# Compatibility Report
- Name of the game with compatibility issues: Quantum Conundrum
- Steam AppID of the game: 200010

## System Information
- GPU: GeForce GTX 1060 6GB
- Driver/LLVM version: nvidia-lts 525.89.02
- Kernel version: linux-lts 5.15.93-1
- Link to full system information report as [Gist](https://gist.github.com/Aperture32GLaDOS/f6968c8b24c3eb5c657d8085a86a6bb0/):
- Proton version: 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-200010.log](https://github.com/ValveSoftware/Proton/files/10725959/steam-200010.log)

## Symptoms 
When starting up the game, steam shows that it is running and then it crashes. There is no graphical indication that the game is running other than steam reporting that the game is running (i.e. no window opens).

## Reproduction
This happens on every attempt to launch the game.

**Comment by kisak-valve** [comment]
Hello @Aperture32GLaDOS, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #1661, but in your case, `"vkCreateInstance (&inst_info, NULL, vk_instance) failed: ERROR_OUT_OF_HOST_MEMORY (-1)"` at https://gist.github.com/Aperture32GLaDOS/f6968c8b24c3eb5c657d8085a86a6bb0/#file-steam-system-information-L1211 tells us that 32 bit AMDVLK is breaking that render path with the NVIDIA driver. Retest with the `lib32-amdvlk` system package removed.

See https://github.com/GPUOpen-Drivers/AMDVLK/issues/315.

**Comment by Aperture32GLaDOS** [comment]
Yep; the game works flawlessly now! Thanks so much for your quick response; I'm slightly embarrassed I didn't notice it myself!
