### ISSUE TITLE
The Elder Scrolls Online: Installation black screens, No file check post install

### ISSUE THREAD

**Issue by msmafra** [ValveSoftware/Proton#6535]
# Compatibility Report
- Name of the game with compatibility issues: The Elder Scrolls Online
- Steam AppID of the game: 306130

## System Information
- GPU:  RTX 2060 mobile
- Driver/LLVM version: 525.89.02
- Kernel version: 6.1.10/6.1.11cb1/6.1.11cbl1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/msmafra/27d1f02cc9a2c08b4aab2e82267c4adb
- Proton version: 7.0-6/Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-306130.log.tar.gz](https://github.com/ValveSoftware/Proton/files/10732763/steam-306130.log.tar.gz)
## Symptoms 
The game runs perfectly (playing since December 2021), just the installation process is problematic, needs PROTON_SET_GAME_DRIVE=1 for it to work and during the process has black screens, pressing Enter repeatedly gives a glance of what is happening. And post-install, the file checking isn't working, it just checks Proton and Soldier.

## Reproduction
Install The Elder Scrolls Online, check the installation process and after try to Check Local files.

**Comment by kisak-valve** [comment]
Hello @msmafra, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/556#issuecomment-1429773817.
