### ISSUE TITLE
Age of empires 3 Definitive Edition: Not show any lobbies/Games

### ISSUE THREAD

**Issue by samuk190** [ValveSoftware/Proton#6536]
Before the last update it used to work, I Think its some issue with proton network ports or something blocking network traffic, it does not show any lobbies in-game.

issue happens in any GE EggRoll Proton builds and normal proton builds

**Comment by kisak-valve** [comment]
Hello @samuk190, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #3712, but this is clearly a duplicate of the most recent discussion there (https://github.com/ValveSoftware/Proton/issues/3712#issuecomment-1428378928).

Closing as a duplicate.
