### ISSUE TITLE
The Binding of Isaac crash

### ISSUE THREAD

**Issue by ardishko** [ValveSoftware/Proton#6539]
# Compatibility Report
- Name of the game with compatibility issues: The Binding of Isaac Repentance
- Steam AppID of the game: 250900

## System Information
- GPU: AMD RX 6900 XT
- Driver/LLVM version: mesa 22.3.4-1
- Kernel version: 6.1.11-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ardishco-the-great/9ea0237432f2b7e7398a37c30af5de5c
- Proton version: 7.0-6 and Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my syste

## Symptoms 
Game crashes in local coop when a player dies
[steam-250900.log](https://github.com/ValveSoftware/Proton/files/10747954/steam-250900.log)

## Reproduction

Using a wlroots wayland compositor might be also a step to this but It seems like the Steam Deck also has this issue, I had the exact same issue on the steam deck that uses gamescope which is an X11 session, albeit nested inside a Wayland session

**Comment by kisak-valve** [comment]
Hello @ardishco-the-great, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4868#issuecomment-1432076370.
