### ISSUE TITLE
[Whitelist] Mega Man Legacy Collection (363440)

### ISSUE THREAD

**Issue by Zero86Sk** [ValveSoftware/Proton#654]
Tested on Proton 3.7.4.beta
It works flawlessly.

My Steam Information:
https://gist.github.com/Zero86Sk/d629f657c1ae861c36657cdf238a7765

**Comment by kisak-valve** [comment]
Mega Man Legacy Collection (363440) Whitelist request.

Issue transferred from https://github.com/ValveSoftware/Proton/issues/801.
@chrisc174 posted on 2018-08-28T02:32:28:

Mega Man Legacy Collection
AppID: 363440

My Specs
AMD Ryzen 1700x
GTX 1060 6 GB
Driver: Nvidia 396.54
Proton Beta 3.7-4
16 GB of DDR4 Ram

Game works flawlessly with one exception, you have to have the controller plugged in before you start the game for it to recognize it. Plugging one in mid game and you'll have to restart for the game to see it. No big deal, but eventually and hopefully it's worked out.
***
@chrisc174 commented on 2018-08-28T02:33:17

gist: https://gist.github.com/chrisc174/3745548874211e8d95eccfbb2e3998b2

**Comment by Zero86Sk** [comment]
@chrisc174 The Controller needing to be plugged in before starting the game for it to work, is the same in Windows. Its a quirk of the game.

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.
