### ISSUE TITLE
Horizon Zero Dawn black screen on Fedora

### ISSUE THREAD

**Issue by Drago245** [ValveSoftware/Proton#6540]
Attempting to play Horizon Zero dawn on Fedora 37 through steam using the default "Proton Experimental" option. 

The game launches, and the main menu music can be heard. The cursor can be seen, and audio feedback is present when hovering over where the buttons would be, but the screen stays black. 

I've tried verifying the game files, using Proton GE, using protontricks to install VCrun2019 as suggested by another user, no change. 

System:

Fedora 37
Ryzen 7 5800X
RX6800XT
Mesa 22.3.4
Wayland
Kernel: Linux 6.1.8-200.fc37.x86_64 x86_64

Steps to reproduce:

1. Install Horizon Zero Dawn on Fedora 37 through steam
2. Launch Horizon Zero Dawn with default settings

**Comment by kisak-valve** [comment]
Hello @Drago245, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4125#issuecomment-1433077022.
