### ISSUE TITLE
Noita not starting

### ISSUE THREAD

**Issue by Brulijam** [ValveSoftware/Proton#6541]
# Compatibility Report
- Name of the game with compatibility issues: Noita
- Steam AppID of the game: 881100

## System Information
- GPU: NVIDIA GeForce RTX 4080
- Driver/LLVM version: nvidia 525.89.02
- Kernel version: 6.1.12-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/Brulijam/7539dc9b89b175eed8ed3ae7f86c3281):
- Proton version: 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game not launching.

## Reproduction
I don't know. Tried reinstalling Game, Steam, OS, home dir (in that order).

**Comment by kisak-valve** [comment]
Hello @Brulijam, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3176#issuecomment-1433085207.
