### ISSUE TITLE
EA App update causes The Sims 4 to no longer launch

### ISSUE THREAD

**Issue by robotman40** [ValveSoftware/Proton#6542]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: RX 6600 XT
- Driver/LLVM version: Mesa 22.3.5 Kisak
- Kernel version: 6.0.12
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Link to log:
https://drive.google.com/file/d/1l2C6Rwh66XmY47ELuaPAOxJTimHjbttd/view?usp=sharing

## Symptoms 
An EA App update came up. After that, the game won't launch anymore

## Reproduction
Update the EA App and see it does not launch. It goes to stop and after a few seconds, it goes back to Play

UPDATE: I tested this on Titanfall 2 and I am getting the same behavior. This seems to be an issue across games that use the EA App, and not specific to any game.

**Comment by kisak-valve** [comment]
Hello @GalacticalEdge, this issue is already being tracked at #6396. Closing as a duplicate.
