### ISSUE TITLE
italic text in Source Engine closed captions is cut off

### ISSUE THREAD

**Issue by BenLubar** [ValveSoftware/Proton#6544]
Proton 7.0-6

Tested in Alien Swarm: Reactive Drop, but it also works in any other Source 1 game that has italicized closed captions.

Repro steps:

1. (On the beta branch of appid 563560)
2. Enable full closed captions in audio settings.
3. Start the first level (Jacob's Rest: Landing Bay)
4. Walk through the level until you reach a locked door. (No enemies spawn before this point on Normal difficulty.) Punch the door by pressing right mouse button or B on a controller.
5. The caption *[Door hit]* has every letter missing pieces on Proton, which is not the case on Windows.

Alternative repro steps:

In any Source 1 game, trigger a caption that has `<I>` in it.

**Comment by kisak-valve** [comment]
Hello @BenLubar, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/942#issuecomment-1159349044.
