### ISSUE TITLE
How to use http proxy with proton?

### ISSUE THREAD

**Issue by shinji3887** [ValveSoftware/Proton#6545]
# Compatibility Report
- eFootball 2023

## System Information
- GPU: 3080ti
- Proton version:5.13-6
- OS: Ubuntu 2204
- CPU: intel i5 12600k

## Problem:
I want to accelerate some windows games with my http proxy. I found that the games run in proton mode cannot feel the proxy while the proxy works well in linux native games. How can I set proxy in proton? thx a lot!

**Comment by kisak-valve** [comment]
Hello @shinji3887, this issue is already being tracked at #4961. Closing as a duplicate.
