### ISSUE TITLE
Hunt Showdown (594650)

### ISSUE THREAD

**Issue by LukeDearden** [ValveSoftware/Proton#6549]
# Compatibility Report
- Name of the game with compatibility issues: Hunt Showdown
- Steam AppID of the game: 594650

## System Information
- GPU:  GTX 1660 Super
- Driver/LLVM version: NVIDIA 525.89.02
- Kernel version: 6.1.11-200.fc37.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/LukeDearden/ce60bf094640431cd332c0597f32d030
- Proton version: Experimental

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 

Game starts out looking fine but then textures stop loading and the graphics look blobby. Some kind of LOD issue

Adjusting graphics settings (memory usage target/texture quality) doesn't help

## Reproduction

Play a round of Bounty Hunt and traverse the map

**Comment by LukeDearden** [comment]
I'm unable to attach files to this issue for some reason

**Comment by an9949an** [comment]
The same on my RTX3050 mobile. Issue start happens when vram usage go close to the maximum (2 minutes of gameplay on minimal textures). Also I can see that VRAM usage is much much higher than on windows (~1.4gb more on the same settings).

**Comment by kisak-valve** [comment]
Hello @LukeDearden, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3898#issuecomment-1435670040.
