### ISSUE TITLE
THE LAST BLADE 2 (702110)

### ISSUE THREAD

**Issue by ngoquang2708** [ValveSoftware/Proton#6550]
# Compatibility Report
- Name of the game with compatibility issues: THE LAST BLADE 2
- Steam AppID of the game: 702110

## System Information
- GPU: AMD AMD Custom GPU 0405 (vangogh, LLVM 14.0.6, DRM 3.45, 5.13.0-valve36-1-neptune)
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 22.2.0 (git-17e5312102)
- Kernel version: 5.13.0-valve36-1-neptune
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ngoquang2708/5f09e4724ce47138e5d6144254b6e583
- Proton version: 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton log: 
[steam-702110.log](https://github.com/ValveSoftware/Proton/files/10774506/steam-702110.log)

## Symptoms
Game won't display any thing then the play button turn back to green.

## Reproduction
Just run the game.

**Comment by kisak-valve** [comment]
Hello @ngoquang2708, can you test how the game behaves with Proton 6.3-8?

**Comment by ngoquang2708** [comment]
The game run with Proton 6.3-8. Also note that the game run perfectly fine with Proton 6.3-8/7.0-6/Experimental on my laptop.

**Comment by waspennator** [comment]
Tested it out on my end with proton Experimental on my deck. Never installed the game before and it boots up perfectly fine. However, if I go into the options, video options, enable full screen, then close and reopen the game, then it starts refusing to start properly.

Proton version 6.3-8 has no problem starting with full screen enabled.

**Comment by ngoquang2708** [comment]
I observe the same full screen behavior following @waspennator steps on both my laptop and my steam deck with Proton 6.3-8/7.0-6/Experimental:
  * 6.3-8: game works fine on both of my devices with full screen enabled.
  * 7.0-6/Experimental: game crash on next play session on both of my devices after enable full screen.

The game keeps its config after uninstall so I have to manually delete it in order to play the game on proton 7.0-6/Experimental:
```
.../THE LAST BLADE 2/Data/~options.bin
```

**Comment by waspennator** [comment]
Testing on my end with proton 8.0-1, cannot replicate the full screen crash anymore least on my deck.

If it doesn't happen on op's end anymore, I think the default proton version can be changed from 6.3-8.

**Comment by ngoquang2708** [comment]
Issue seem resolved with Proton 8.0. Tested on my laptop and my SteamDeck.

**Comment by waspennator** [comment]
Guess that means the issue can be closed now and the proton version that's currently being set for Deck usage back up to stable again, whenever it gets set to proton 8.0
