### ISSUE TITLE
Brotato (1942280)

### ISSUE THREAD

**Issue by ProMix0** [ValveSoftware/Proton#6551]
#### Your system information

* Steam client version (build number or date): Feb 14 2023
* Distribution (e.g. Ubuntu): Ubuntu 22.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I expected to run game [Brotato, id: 1942280](https://store.steampowered.com/app/1942280/Brotato/) via Steam, but it doesn't

After some attempts to work around (including triple reinstall with different package managers and moving games directory to another disk) I just execute launch command from command line logs
`
/home/misha/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=1942280 -- /home/misha/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- '/home/misha/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/misha/.steam/debian-installation/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/steamgames/steamapps/common/Brotato/Brotato.exe'
`
and it works!

I was try to manually change start command to simple running via Proton, but it's also don't work 

So, next question - why the game (other games runs normally) can't be launched from Steam client?

#### Steps for reproducing this issue:

1. Buy
2. Try to run
3. Copy command from CLI and finally run

**Comment by kisak-valve** [comment]
Hello @ProMix0, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report.

Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

If you completely close Steam, then run `steam` from a terminal, are there any hints in the terminal spew when you tell Steam to start the game? Also, if you set the game's launch options to [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options), does that generate a log file at $HOME/steam-$APPID.log? If it does, then please attach that log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by ProMix0** [comment]
> Please copy your system information

[Gist](https://gist.github.com/ProMix0/504a4ddcee894cd9581f2098b7380b18)

> are there any hints in the terminal

No, I guess
![image](https://user-images.githubusercontent.com/54300969/219956530-0347fff7-94d4-4311-ac45-7002c9120181.png)

> does that generate a log

Yep, it does:
![image](https://user-images.githubusercontent.com/54300969/219956631-0a8698ae-4d2b-4360-a626-e3a6fedf76d8.png)
Useful, right? (sorry for toxic)

And now, updates

To make the game works I was followed this [guide](https://gist.github.com/sxiii/6b5cd2e7d2321df876730f8cafa12b2e). After restarting Steam I realized that can't run the game. After a few attempts I got that variables STEAM_COMPAT_CLIENT_INSTALL_PATH and STEAM_COMPAT_DATA_PATH must be defined. There is part of my .bashrc:
```
export STEAM_COMPAT_DATA_PATH=~/.steam/debian-installation/steamapps/compatdata
export STEAM_COMPAT_CLIENT_INSTALL_PATH=~/.local/share/Steam/steamapps/compatdata # un-existing path
``` 

After that next command will start the game:
```
~/.steam/debian-installation/steamapps/common/Proton\ -\ Experimental/proton run Brotato.exe
```
(logs in homedir still useless even when `PROTON_LOG=1`)

Command in original post also starts correctly... before I did restart Steam. I can't figure out why and how to fix it (but I did it twice) 

Anyway, successful run looks like this:
![image](https://user-images.githubusercontent.com/54300969/219959255-fb81be9c-29c8-4903-a945-3c3886a3c585.png)
Unsuccessful (via original post command) interrupts after message from wine silently

I hope this can be useful

**Comment by kisak-valve** [comment]
Your first screenshot has the critical detail `*** stack smashing detected ***: terminated` and paired with your system information `Driver Version:  4.6.0 NVIDIA 390.157`, that tells us you've encountered https://github.com/ValveSoftware/steam-runtime/issues/420.

Sorry, but the NVIDIA 390 series video driver is older than the support cutoff for Proton, and your Fermi generation video card does not support Vulkan, which makes your system unsupportable in general.

That said, you might get lucky with some games by using Proton 5.0 or older, which predates the use of the Steam Linux Runtime - Soldier container environment and the linked issue report. Also, you can try setting the game's launch options to `PROTON_USE_WINED3D=1 %command%` to tell Proton to use wine's DirectX to OpenGL render path, but this is also not considered supported and comes with a significant performance penalty.

The guide you found bypasses the Steam Linux Runtime - Soldier container environment. This might work by luck, but a future system update might break it in unexpected ways. Again, that's not really a supportable configuration.

**Comment by ProMix0** [comment]
Switching to Proton 5.0-10 helps, thanks
