### ISSUE TITLE
PS5 controller on Hogwarts Legacy

### ISSUE THREAD

**Issue by sdtsj** [ValveSoftware/Proton#6553]
Hello,
Not 100% sure if someone reported this or not or if this is a proton problem but it is worth a try.
When playing Hogwarts Legacy on PC (Windows 10) with PS5 controller connected with bluetooth, the game shows normal PS glyphs since the game supports them natively. However when I run the game on SteamDeck and connect the same controller to it, the game shows xbox glyphs. I have tried different layouts and even at one point I tried disabling the steam input to try to force the game to show PS glyphs but with no help.
Thank you in advance in looking into this :)

**Comment by kisak-valve** [comment]
Hello @sdtsj, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6510#issuecomment-1438485517.
