### ISSUE TITLE
Failed to compile source with tag: experimental-6.3-20220119

### ISSUE THREAD

**Issue by wanlizhu** [ValveSoftware/Proton#6560]
I tried to compile proton experimental-6.3-20220119 with the following commands:
```
git checkout experimental-6.3-20220119 
git submodule update --init --recursive
```
but there is a fatal error while updating submodule dxvk:
```
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 12 (delta 2), reused 8 (delta 2), pack-reused 0
Unpacking objects: 100% (12/12), 19.22 KiB | 9.61 MiB/s, done.
From https://github.com/doitsujin/dxvk
   caf31033..0d28be4a  master     -> origin/master
fatal: remote error: upload-pack: not our ref cafeea30375b274470419e7f82b8c29d4ee2950d
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'dxvk', but it did not contain cafeea30375b274470419e7f82b8c29d4ee2950d. Direct fetching of that commit failed.
```

It looks like proton is referencing to a dxvk version that doesn't exist in server.

**Comment by kisak-valve** [comment]
Hello @wanlizhu, it looks like the ValveSoftware fork of dxvk has this commit https://github.com/ValveSoftware/dxvk/commit/cafeea30375b274470419e7f82b8c29d4ee2950d. It's not particularly interesting to try to maintain an experimental dev build from over a year ago.
