### ISSUE TITLE
World War Z does not start at all

### ISSUE THREAD

**Issue by LightningRhino** [ValveSoftware/Proton#6562]
# Compatibility Report
- Name of the game with compatibility issues: World War Z
- Steam AppID of the game: 669130

## System Information
- GPU: AMD Radeon RX 6700 XT
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 22.2.5, OpenGL-Version: 4.6
- Kernel version: 6.1.12
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/LightningRhino/b19718a1d9659fdfa9afb6cf998767cd
- Proton version: 7.0-6 as well as Proton Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-699130.log](https://github.com/ValveSoftware/Proton/files/10824858/steam-699130.log)

## Symptoms 
Game does not start at all with any tested Proton version.
Also GE-Proton7-49 does not work.
I always get a crash dump sending utility.
I even tested with PROTON_USE_WINED3D=1 %command%, which also brings the crash dump sending utility. 

## Reproduction
Start the game and wait for just 2-3 seconds.

**Comment by mbriar** [comment]
Multiple problematic things in your log:

```
info:  AMD Radeon RX 6700 XT:
info:    Driver: 2.0.241
```
this means you're using amdvlk or the proprietary vulkan driver instead of mesa/radv, which is known to not work great with proton.

```
libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri, suffix _dri)
```
probably broken (32bit) opengl driver install as well, which the game might need for it's launcher or something.

**Comment by kisak-valve** [comment]
Hello @LightningRhino, we're using one issue per unofficially supported issue report, and usually I'd transfer this issue report to #6505, but in your case it's clear that you're seeing a NixOS specific Steam Linux Runtime - Soldier issue.

https://gist.github.com/LightningRhino/b19718a1d9659fdfa9afb6cf998767cd#file-gistfile1-txt-L1082-L1140 and https://gist.github.com/LightningRhino/b19718a1d9659fdfa9afb6cf998767cd#file-gistfile1-txt-L1248-L1324 tells us that mesa is outright broken in the container environment Proton runs inside.

Report this issue to nixpkgs for a NixOS package maintainer to ponder. https://github.com/NixOS/nixpkgs/issues/217344#issuecomment-1439198102 might be relevant.
