### ISSUE TITLE
No Proton log?

### ISSUE THREAD

**Issue by webaake** [ValveSoftware/Proton#6563]
I'm using Proton 7.x on an updated Steam, non-flatpak, for the game World of Warships. 
I do put the line `PROTON_LOG=1 %command%` set in the [Set Launch Options] for the game. I do not get any log file anywhere. It should pop up in my home directory as steam-$GAMEID.log but it don't. (Gameid is 1248250 in this case). 

Steam version is from 14 Feb 2023 (latest on Ubuntu).

Attached is Steam info/hardware
PS I started an issue 2021 but decided to make a new one since time has passed.
[steam-info.txt](https://github.com/ValveSoftware/Proton/files/10824976/steam-info.txt)

**Comment by kisak-valve** [comment]
Hello @webaake, there's no value in fragmenting the discussion of this issue over multiple issue reports. Closing as a duplicate of #5369.
