### ISSUE TITLE
Falcon BMS VR not working with SteamVR

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#6564]
# Compatibility Report
- Name of the game with compatibility issues: Falcon BMS (a mod for Falcon 4.0)
- Steam AppID of the game: 429530

## System Information
- GPU: NVIDIA GeForce RTX 2080
- Driver/LLVM version: nVidia 525.89.02
- Kernel version: 6.1.12-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/SquadFM/f1642250e9a823f3d1e3fc073e9eed99)
- Proton version: 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Falcon BMS does not start in VR (with SteamVR). It works fine in normal 2D mode.

## Reproduction
Falcon BMS is a mod for Falcon 4.0 (AppID 429530) and installs into the path `/home/x/.local/share/Steam/steamapps/compatdata/429530/pfx/drive_c/Falcon BMS 4.37/`. If needed, here are the Falcon BMS install instructions for Linux: https://github.com/SquadFM/Falcon-4-BMS

Falcon BMS starts in "normal" 2D mode with the command below and runs without issues: `STEAM_COMPAT_DATA_PATH="/home/x/.local/share/Steam/steamapps/compatdata/429530/" STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/x/.local/share/Steam/" "/home/x/.local/share/Steam/steamapps/common/Proton 7.0/proton" run "/home/x/.local/share/Steam/steamapps/compatdata/429530/pfx/drive_c/Falcon BMS 4.37/Bin/x64/Falcon BMS.exe"`

However, Falcon BMS does not start in VR (Steam is open; tried with SteamVR running and not running before starting the game - neither works). Also, VR is enabled in the game in the config file `/home/x/.local/share/Steam/steamapps/compatdata/429530/pfx/drive_c/Falcon BMS 4.37/User/Config/Falcon BMS.cfg` where `set g_nVRHMD` is set to `1`. It "just works" under Windows in SteamVR according to other users. 

## PROTON_LOG=1
The command below only creates the files `Falcon BMS_d3d11.log` and 'Falcon BMS_dxgi.log', however no file similar to `$HOME/steam-$APPID.log`.

Command to generate log files: `PROTON_LOG=1 STEAM_COMPAT_DATA_PATH="/home/x/.local/share/Steam/steamapps/compatdata/429530/" STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/x/.local/share/Steam/" "/home/x/.local/share/Steam/steamapps/common/Proton 7.0/proton" run "/home/x/.local/share/Steam/steamapps/compatdata/429530/pfx/drive_c/Falcon BMS 4.37/Bin/x64/Falcon BMS.exe"`

[Falcon BMS_d3d11.log](https://github.com/ValveSoftware/Proton/files/10825622/Falcon.BMS_d3d11.log)

[Falcon BMS_dxgi.log](https://github.com/ValveSoftware/Proton/files/10825625/Falcon.BMS_dxgi.log)

## Less important information: 
- Falcon BMS requires the original Falcon 4.0 installation, which can be found under `/home/x/.local/share/Steam/steamapps/common/Falcon 4.0/`
- I tested if other games run in VR via command line. For example, Beat Saber starts and runs in VR with the following command just fine: `STEAM_COMPAT_DATA_PATH="/home/x/.local/share/Steam/steamapps/compatdata/620980/" STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/x/.local/share/Steam/" "/home/x/.local/share/Steam/steamapps/common/Proton 7.0/proton" run "/home/x/.local/share/Steam/steamapps/common/Beat Saber/Beat Saber.exe"`

**Comment by kisak-valve** [comment]
Hello @SquadFM, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3991#issuecomment-1443831285.
