### ISSUE TITLE
Shadow of the Tomb Raider showing corruption with Proton 7.0-6 - Works with 7.0-5

### ISSUE THREAD

**Issue by LegiossOrig** [ValveSoftware/Proton#6566]
# Compatibility Report
- Name of the game with compatibility issues: Shadow of the Tomb Raider
- Steam AppID of the game: 750920

## System Information
- GPU: AMD 6800XT
- Driver/LLVM version: AMDVLK 22.3.0
- Kernel version: 5.19-0.32-generic
- Link to full system information report as [Gist](https://gist.github.com/): 
https://gist.github.com/LegiossOrig/938e6bbb37ff35287de6ffc60009057e
- Proton version: 7.0-6

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

## Symptoms 
I have been using Shadow of the Tomb Raider shortly after 7.0-5 went public. The game was fine in DX11 mode, no corruptions seen. But 7.0-6 was released and now the characters clothing have black triangles on them. I cannot roll back to 7.0-5 as this is not an available option. I am using the open source amdvlk vulkan driver. The AMD vulkan Pro driver shows the same issues. RadV is unaffected.

## Reproduction
Start Shadow if the Tomb Raider in DX11 mode, go to the settings and run the benchmark. You will see all the characters have black triangles on them.

<img width="1394" alt="Corruption" src="https://user-images.githubusercontent.com/104018120/221294483-9ae67ba5-91af-4b56-b5dd-bef85427655d.png">

<img width="1394" alt="Corruption 2" src="https://user-images.githubusercontent.com/104018120/221294690-78d90581-8044-4abe-aa60-6c893115c656.png">

**Comment by kisak-valve** [comment]
Hello @LegiossOrig, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1417#issuecomment-1444513880.
