### ISSUE TITLE
Hunt: Showdown (594650)

### ISSUE THREAD

**Issue by SamPurple22** [ValveSoftware/Proton#6569]
# Compatibility Report
- Name of the game with compatibility issues: Hunt: Showdown
- Steam AppID of the game: 594650

## System Information
- GPU: Radeon RX 7900 XTX
- Driver/LLVM version: Mesa 23.3.3
- Kernel version: 6.1.13-x64v3-xanmod1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton Experimental or 7.0-6 (and GE-Proton-49 and Proton 6.3 etc)
- Distro: Debian 12 (bookworm/testing)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Proton log: [steam-594650.tar.gz](https://github.com/ValveSoftware/Proton/files/10831136/steam-594650.tar.gz)

## Symptoms 
Game starts and works for offline play, like Tutorial mission or Trial mission. Does not work for online play, Bounty or Quickplay. When trying to play online you always need to choose your network regions, and it does not move forward from there.
The choose your network region dialog is also missing the ping, latency indicators on the buttons.

## Reproduction
Install the game, start it, try to play online. Cannot see latency indicators on select network region dialog. Cannot start online game.

Additional info found in game.log:
<11:53:34> [Hunt Online] [Account] Initializing.
<11:53:34> [Hunt Online] [Online Account] Platform initializing: waiting for authentication token.
<11:53:35> [Hunt Online] [Account] Initializing online services for client with 'live' settings
<11:53:35> [Hunt Online] CProfileInboxService::Init: successfully initialized
<11:53:35> [CryCloud] Trying to establish connection with 'capi1-lv-lw-wc.huntshowdown.com:61088' open
<11:53:35> [CryCloud] Connection Succeeded
<11:53:41> [CryCloud] Sending request: Invoke (0x01000000) remotely on server with messageId = 1, grainId = 0, bodysize = 528
<11:53:41> [CryCloud] [Warning] Obtaining RTT of TCP connection is not supported
<11:53:42> [CryCloud] RECV messageid: 1
<11:53:42> [CryCloud] [Client Session] Authentication succeed

[gamelog.tar.gz](https://github.com/ValveSoftware/Proton/files/10831151/gamelog.tar.gz)

**Comment by kisak-valve** [comment]
Hello @SamPurple22, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3898#issuecomment-1445135146.
