### ISSUE TITLE
Total War: WARHAMMER III (1142710) won't launch

### ISSUE THREAD

**Issue by RicardoVizcaya** [ValveSoftware/Proton#6570]
# Compatibility Report
- Name of the game with compatibility issues: Total War: WARHAMMER III
- Steam AppID of the game: 1142710

## System Information
- GPU: AMD® Radeon™ RX 6800M
- Driver/LLVM version: Mesa 22.3.6-1
- Kernel version: 6.1.12
- Link to full system information report: [Gist Link](https://gist.github.com/RicardoVizcaya/fe0ebd178557213e04c4ec72fe861cbc)
- Proton version: 7.0-6

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
Since around two months I have been unable to launch the game as I did before with the following launch options:
`DRI_PRIME=1 %command%`
The launcher opens alright, but the game crashes after clicking PLAY without even showing the black screen. The closest issue I could find to this was https://github.com/ValveSoftware/Proton/issues/6262; it is closed though and didn't apply to me. I have tried different Proton versions, opting in and out of Steam Beta, and toggling on and off the Vulkan shaders to no avail. The only way I can make the game run (as recommended in ProtonDB) is with the launch options:
`PROTON_USE_WINED3D11=1 %command%`
In this case though, only my integrated GPU is recognised by the game, which does not meet the requirements to play it. Even adding gamemoderun and configuring using the dedicated graphic card as environment variable does not make my dGPU appear in the game settings.
What can I do to have the game working again under Proton?

## Reproduction
1. Launch the game with PRIME arguments to select your dGPU
2. On the launcher, click PLAY
3. The game will close without opening.

## Proton Log
[steam-1142710.log](https://github.com/ValveSoftware/Proton/files/10831454/steam-1142710.log)

## PS
This is my first report so please let me know if I am missing to provide some information.

**Comment by kisak-valve** [comment]
Hello @RicardoVizcaya, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5976#issuecomment-1445149065.
