### ISSUE TITLE
Company of Heroes 3 on laptop with nvidia

### ISSUE THREAD

**Issue by b3nis** [ValveSoftware/Proton#6572]
# Compatibility Report
- Name of the game with compatibility issues: Company of Heroes 3
- Steam AppID of the game: 1677280

## System Information
- GPU: GTX 1660 Ti Mobile
- Driver/LLVM version: Dunno, latest on Fedora?
- Kernel version: 6.1.13-200.fc37.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): 
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available. 

My system:
https://gist.github.com/b3nis/1235a9ae56f8015f0ca6d16b66e824d3

Proton log:
 https://gist.github.com/b3nis/27ea6c8b0a320849f010199b5dc9e0d1

## Symptoms  
A dialog window with the text "Sorry, something went wrong. For solution please visit:
https://support.codefusion.technology/CoH3_gjsa_8945/?e=88500006&l=english"

## Reproduction
Install the game on a laptop with nvidia dgpu and launch it. All other games I play, including COH2, works with any mods. Seems to be something with the dgpu + proton + wine maybe? Seems to be working for a lot of people on desktop computers (with single gpu).

**Comment by kisak-valve** [comment]
Hello @b3nis, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6568#issuecomment-1445191370.
