### ISSUE TITLE
Dead Cells (588650)

### ISSUE THREAD

**Issue by DrLegitamate** [ValveSoftware/Proton#6576]
# Compatibility Report
- Name of the game with compatibility issues: Dead Cells (https://store.steampowered.com/app/588650/Dead_Cells/)
- Steam AppID of the game: 588650

## System Information
- GPU: Steam Deck
- Driver/LLVM version: Steam Deck stable (Steam OS 3.4)
- Kernel version: Steam OS 3.4
- Proton version: 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Audio Delay (~15s) after putting the steam deck to sleep and waking while dead cells is running

## Reproduction
Run the game
Press the power button to sleep device
Press the power button to wake device

**Comment by kisak-valve** [comment]
Hello @DrLegitamate, this game has a native Linux variant and is configured to use it by default on the Steam Deck. Without stronger evidence like a Proton log, Proton isn't involved with the issue you've encountered, making this feedback invalid for the Proton issue tracker.
