### ISSUE TITLE
Sid Meier's Civilization V -- Crash on launch of Steam overlay

### ISSUE THREAD

**Issue by TheGoblinPopper** [ValveSoftware/Proton#6579]
# Compatibility Report
- Name of the game with compatibility issues: Sid Meier's Civilization V
- Steam AppID of the game: 8930

## System Information
https://gist.github.com/TheGoblinPopper/ea29ad587d6e6cbd877d037ba31b797f
- Proton version: Experimental and 7.0-6

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Game crashes whenever steam overlay is triggered.

## Reproduction
1) Launch Game
2) Select Direct X 9 or 11
3) Allow game to fully load through initial movie.
4) launched steam overlay (shift + tab)
5) Wait for machine to ask if you want to crash the game.
(reproducible via any point of gameplay)

[steam-8930.log.tar.gz](https://github.com/ValveSoftware/Proton/files/10846075/steam-8930.log.tar.gz)

**Comment by kisak-valve** [comment]
Hello @TheGoblinPopper, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3190#issuecomment-1447499652.
