### ISSUE TITLE
Space Engineers - Workshop not downloaded

### ISSUE THREAD

**Issue by Windgott1910** [ValveSoftware/Proton#6582]
I am opening a new issue as my comment wasn't answered.
newest comment: https://github.com/ValveSoftware/Proton/issues/1792#issuecomment-1399305059 
# Compatibility Report
- Name of the game with compatibility issues: Space Engineers
- Steam AppID of the game:

## System Information
- look at comment

## I confirm:
- [x ] that I have checked whether there are updates for my system available.

## Symptoms
I can play the game just fine, but the workshop just wont load. I tried to reload but it didn't work

## Reproduction
Open SE
Start world
Open blueprint menu
try to get a workshop blueprint

**Comment by kisak-valve** [comment]
Hello @Windgott1910, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1792#issuecomment-1399305059.
