### ISSUE TITLE
./build_proton.sh: line 455: meson: command not found

### ISSUE THREAD

**Issue by goodforever** [ValveSoftware/Proton#659]
On macOS    ./build_proton.sh: line 455: meson: command not found

**Comment by CuriousTommy** [comment]
When you see `command not found`, it probably means that you don't have a tool installed. It is telling you that you don't have [meson](https://mesonbuild.com/) installed.

**Comment by goodforever** [comment]
You require that  brew install cmake nasm libtool automake on macOS , no meson.

**Comment by CuriousTommy** [comment]
@goodforever It is clearly [stated in the readme](https://github.com/ValveSoftware/Proton#building-for-macos) that not all of the dependencies needed are listed. So they probably forgot to add meson to the list of dependencies.

**Comment by flukejones** [comment]
@CuriousTommy they did. There are a few PR to correct this too.

@goodforever can you please close this as solved.
