### ISSUE TITLE
Akka Arrh (2005680)

### ISSUE THREAD

**Issue by cplr** [ValveSoftware/Proton#6591]
# Compatibility Report
- Name of the game with compatibility issues: Akka Arrh
- Steam AppID of the game: 2005680

## System Information
- Steam Deck: Steam OS Stable Channel v3.4.4
- Driver/LLVM version: 4.6, Mesa 22.2.0 (git-17e5312102)
- Kernel version: 5.13.0-valve36-1-neptune
- Proton version: 7.0-6, Experimental, 6.3, 5.13, 5.0
- Full system report: https://gist.github.com/cplr/36e91e38d194b0cb6040fc0d467cfbd0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms

Many of the game's textures/surfaces are rendered as white. This makes the game unplayable.

## Reproduction

1. Launch game
2. Notice draw color of many of the surfaces.

[steam-2005680.log](https://github.com/ValveSoftware/Proton/files/10885781/steam-2005680.log)

**Comment by cplr** [comment]
I am curious if the SteamOS 3.4.6 beta with new Mesa drivers resolves any of these issues, I did not test that.

**Comment by cplr** [comment]
I just tried out the 3.4.6 Preview Channel, and it does not change any behavior with this issue.

**Comment by cplr** [comment]
According to the developer:

https://toot.wales/@llamasoft_ox/110135099564473104 @schmidt if you have the deck you can play it right now. Just add one line to the launch parameters and it works fine.

`allow_glsl_extension_directive_midshader=true %command%`

**Comment by kisak-valve** [comment]
Hello @cplr, this workaround has also been applied to the pile of application specific workarounds built into mesa git main and is expected to be in mesa 23.0.2. Upstream commit: https://cgit.freedesktop.org/mesa/mesa/commit/?id=29c71b8eb0ce1424fc51dbb9a1d14f0750ceac64

**Comment by cplr** [comment]
I confirmed that after updating Mesa to 23.0.2 in Desktop mode, this issue is resolved.
