### ISSUE TITLE
Hogwarts Legacy (990080) - Long loading times/ Blank screen

### ISSUE THREAD

**Issue by NicolaiVdS** [ValveSoftware/Proton#6593]
# Compatibility Report
- Name of the game with compatibility issues: **Hogwarts Legacy**
- Steam AppID of the game: **990080**

## System Information
- GPU: **RTX 3070** 
- Driver/LLVM version: **nvidia 525.89.02** 
- Kernel version: **6.2.1-arch1-1** 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/NicolaiVdS/a5b6d847efe5f43cc91506985e7e7ac3
- Proton version: **GE-Proton7-49**

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-990080.log.zip](https://github.com/ValveSoftware/Proton/files/10888214/steam-990080.log.zip)

## Symptoms 
the game either takes ages to load to the main menu -> 5Min+ 
or it loads up i can hear the music but the screen is just blank 

## Reproduction
Simply playing the game on a RTX 3070 with Proton using the latest stable driver release seems to result in this issue pretty regularly.

**Comment by kisak-valve** [comment]
Hello @NicolaiVdS, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6510#issuecomment-1454737939.
