### ISSUE TITLE
Forza 5 continued crash on boot up

### ISSUE THREAD

**Issue by tgolden069** [ValveSoftware/Proton#6596]
# Compatibility Report
- Name of the game with compatibility issues: Forza Horizon 5
- Steam AppID of the game: 1551360

## System Information
- GPU: Operating System: SteamOS 3.4.4
KDE Plasma Version: 5.26.1
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 5.13.0-valve36-1-neptune (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Custom APU 0405
Memory: 11.5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405
Manufacturer: Valve
Product Name: Jupiter
System Version: 1

- Proton version: Proton Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @tgolden069, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5285#issuecomment-1454915050.
