### ISSUE TITLE
Vulkan not supported on given X window after NVIDIA driver update

### ISSUE THREAD

**Issue by kordax** [ValveSoftware/Proton#6598]
# Compatibility Report
All games don't work.

## System Information
- GPU: NVIDIA RTX 3050 Ti (laptop prme)
- Driver/LLVM version: 525.89.02/Mesa 22.2.5 (LLVM 15.0.6)
- Kernel version: 5.19.0-35-generic (Ubuntu)
- Link to full system information report as [Gist](https://gist.github.com/kordax/7230f8a155ce49e4eb2e5e218af0e8ac):
- Proton version: Proton experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
None of the games work anymore after updating, looks like the NVIDIA driver messed up the display mapping/vdpau library.
Everything worked previously before manually installing 525.89.02
Tried to reinstall all the drivers, and check debsums of the packages.

## Reproduction
Checking vulkan output gives me this:
~/.local/share/Steam/ubuntu12_32/steam-runtime/usr/libexec/steam-runtime-tools-0/x86_64-linux-gnu-check-vulkan
```
{"device-info":{"device-name":"Intel(R) UHD Graphics (TGL GT1)","device-type":1,"api-version":"1.3.224","driver-version":"0x5802005","driver-id":6,"driver-name":"Intel open-source Mesa driver","driver-info":"Mesa 22.2.5","vendor-id":"0x8086","device-id":"0x9a60"}}
{"device-info":{"device-name":"NVIDIA GeForce RTX 3050 Ti Laptop GPU","device-type":2,"api-version":"1.3.224","driver-version":"0x83564080","driver-id":4,"driver-name":"NVIDIA","driver-info":"525.89.02","vendor-id":"0x10de","device-id":"0x25a0"}}
{"device-info":{"device-name":"llvmpipe (LLVM 15.0.6, 256 bits)","device-type":4,"api-version":"1.3.224","driver-version":"0x1","driver-id":13,"driver-name":"llvmpipe","driver-info":"Mesa 22.2.5 (LLVM 15.0.6)","vendor-id":"0x10005","device-id":"0"}}
{"test":{"index":0,"can-draw":false,"error-message":"Vulkan not supported on given X window"}}
Segmentation fault
```
va-api also fails with error, but not sure if it should affect my games:
~/.local/share/Steam/ubuntu12_32/steam-runtime/usr/libexec/steam-runtime-tools-0/x86_64-linux-gnu-check-va-api 
```
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva info: va_openDriver() returns 0
vaCreateSurfaces (va_display, VA_RT_FORMAT_YUV420, width, height, surfaces, surfaces_count, &attr, 1) failed: attribute not supported (10)
x86_64-linux-gnu-check-va-api: vdpau_video.c:325: vdpau_DestroySurfaces: Assertion `obj_surface' failed.
Aborted
```
Any help is appreciated.

**Comment by kisak-valve** [comment]
Hello @kordax, the NVIDIA proprietary driver requires that the that the video driver's running kernel module, 32 bit userspace libraries, and 64 bit userspace libraries are all installed and exactly the same version to work properly.

Your system information tells us that your system is configured to run X on the NVIDIA proprietary driver, but you have no 32 bit userspace libraries installed for the NVIDIA proprietary driver. That is also causing Steam to fallback to llvmpipe (mesa's faster CPU renderer) for it to run at all.

On Ubuntu, this is generally found in the `libnvidia-gl-525:i386` system package for the 525 series NVIDIA driver.

Closing because this is a system config issue, not a Proton issue.

**Comment by kordax** [comment]
Thank you for your assistance, btw, how did you figure out that it's falling back to LVM?

**Comment by kisak-valve** [comment]
https://gist.github.com/kordax/7230f8a155ce49e4eb2e5e218af0e8ac#file-gistfile1-txt-L48
