### ISSUE TITLE
Anno 1800 multiplayer not working anymore

### ISSUE THREAD

**Issue by Asteliks** [ValveSoftware/Proton#6603]
# Compatibility Report
- Name of the game with compatibility issues: Anno 1800
- Steam AppID of the game: 916440

## System Information
- GPU: Nvidia RTX3080
- Driver/LLVM version: nvidia 525.89.02
- Kernel version: 6.1.14-200.fc37.x86_64
- Link to full system information report as [Gist](https://gist.github.com/Asteliks/268e5aec75ac6e341b6092d7d27433f6)
- Proton version: Proton Experimental (as of 2023/02/27) & 7.0-6

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

[steam-916440-.zip](https://github.com/ValveSoftware/Proton/files/10914690/steam-916440-.zip)
proton-6.3-8 crashes so fast that no log is created 
![obraz](https://user-images.githubusercontent.com/62251475/223568411-12dee9b8-6790-440c-81fd-6d5f3a57c3cb.png)

## Symptoms 
Unable to join multilayer games with the latest proton version. According to comments on protondb it used to work with proton 6.3-8 but unfortunately I'm getting an error when trying to start with that proton version.

## Reproduction

1. Start Anno 1800 with Proton 7.0-6
2. Host a multiplayer game see that no one can join you. Be that through the game, steam or Ubisoft connect;
3. Try joining your friends game (Friend was on Windows 10). See that the game tries to join you but fails with no error message;
4. Try running Anno 1800 with Proton 6.3-8 as recommended on [protondb](https://www.protondb.com/app/916440);
5. See that ubisoft connect crashes on lunch;
6. Check game files -> same result with ubisoft connect;
7. Reinstall the game;
8. Lunch running Anno 1800 with Proton 6.3-8;
9. See that ubisoft connect crashes on lunch.

**Comment by kisak-valve** [comment]
Hello @Asteliks, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2544#issuecomment-1459022711.
