### ISSUE TITLE
Halo Infinite (1240440)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#6604]
# Compatibility Report
- Name of the game with compatibility issues: Halo Infinite
- Steam AppID of the game:1240440

## System Information
- GPU: AMD Radeon RX 6900XT
- Driver/LLVM version: Mesa 22.3.5
- Kernel version: 6.1.15-200.fc37
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/baldwin-yeti/655ab74032e05c3ff5ecc7d29f5e0be2
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game crashes on startup with the latest update (from March 7)

## Reproduction
1. Start the game
2. Wait for the intro video to play
3. Game crashes on the loading screen

[steam-1240440.zip](https://github.com/ValveSoftware/Proton/files/10925706/steam-1240440.zip)

**Comment by kisak-valve** [comment]
Hello @baldwin-yeti, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5030#issuecomment-1460973228.
