### ISSUE TITLE
/steam directory not mounted

### ISSUE THREAD

**Issue by andrewille** [ValveSoftware/Proton#6608]
Hello,
my friend made a steam game that can load workshop contents from the steam directory. My steam directory is located in the root directory of the file system (as /steam) because my home folder is encrypted and I don't need steam/game files to be encrypted, but rather to load fast. He can retrieve the status of the workshop contents and get their paths, but the game is unable to access the files, because Proton doesn't mount the /steam directory as Z:\steam. I think that there may be some whitelist that blocks certain directories like /boot from being mounted in Proton, but Proton should check whether the steam directory is actually mounted.

My proton version is 7.0-6

**Comment by kisak-valve** [comment]
Hello @andrewille, Proton 5.13 and newer is run inside the Steam Linux Runtime - Soldier container environment. The container is not given unlimited access to the host system. This is not a Proton issue. See https://github.com/ValveSoftware/steam-runtime/issues/393 for a similar scenario.

**Comment by andrewille** [comment]
I fixed it by launching steam with the following option:
STEAM_COMPAT_MOUNTS=/steam
