### ISSUE TITLE
Hunt: Showdown stopped properly loading textures on Proton Experimental

### ISSUE THREAD

**Issue by hatani** [ValveSoftware/Proton#6616]
# Compatibility Report
- Name of the game with compatibility issues: Hunt: Showdown
- Steam AppID of the game: 594650

## System Information
- GPU:  RX 6800XT
- Driver/LLVM version:  mesa 23.1.0-devel
- Kernel version:  6.1.15-100
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/hatani/f1c448f205ebd0be3a44707a36dfa25d
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Reproduction
Use proton experimental, load the game, run a bit to see if textures go missing.
![image](https://user-images.githubusercontent.com/740982/225041384-f7e6e0e0-07b8-4c9c-a278-3a0a6a415470.png)

**Comment by kisak-valve** [comment]
Hello @hatani, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3898#issuecomment-1468301556.
