### ISSUE TITLE
Surviving Mars (464920)

### ISSUE THREAD

**Issue by RlndVt** [ValveSoftware/Proton#6619]
# Compatibility Report
- Name of the game with compatibility issues: Surviving Mars
- Steam AppID of the game: 464920

## System Information
- SteamDeck
- Native Version

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Left stick controller drift when in-game (does not happen in the main-menu). 

## Reproduction
Start tutorial 'Basic'.
Select/zoom in on a sector.
Camera starts panning in one direction. (Yesterday it was left, today it is downwards, and after a game-restart diagonally down-right.)

**Comment by RlndVt** [comment]
Using Proton instead of the native version the stick-drift stops.

Further, whilst using the native build, changing the controller layout back and forth eliminates the drift.

Maybe defaulting to Proton instead of native is a better solution?

**Comment by kisak-valve** [comment]
Hello @RlndVt, as you noted, Surviving Mars (464920) is a native linux game and is not using Proton on the Steam Deck by default.

I have forwarded this feedback, but this is also invalid for the Proton project and won't be tracked here.
