### ISSUE TITLE
F1 22 just wont launch 

### ISSUE THREAD

**Issue by Colon101** [ValveSoftware/Proton#6621]
im using proton experimental  but i tried like almost all versions but it just wont start heres what im seeing 

https://user-images.githubusercontent.com/99831740/226074281-f9fd51a9-f46c-4959-8029-ee2fcf35d7c3.mp4

i have an i5-8400
and a rx 6600

**Comment by kisak-valve** [comment]
Hello @Colon101, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5963#issuecomment-1474553844.
