### ISSUE TITLE
Olympia Rising (295910)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#6622]
# Compatibility Report
- Name of the game with compatibility issues: Olympia Rising
- Steam AppID of the game: 295910 

## System Information
- 512 GB Steam Deck
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
I can hear the sound of the game and the buttons do seem to work, the screen just isn't displaying the title screen at all, making the game unplayable. I also did some regression testing and found out that the last proton version that displayed the title screen was 5.13-6, after that, 6.3-8 and onwards was when the screen stopped displaying anything.
[steam-295910.log](https://github.com/ValveSoftware/Proton/files/11007691/steam-295910.log)

## Reproduction
Just start the game up with Proton Experimental and notice how the screen stays dark, but the music still plays and the sound effects still go off when pressing buttons.

**Comment by Blisto91** [comment]
Seems to be an issue with Proton Wine's `d3dcompiler_46.dll`. installing the Windows version through winetricks makes it work.

**Comment by waspennator** [comment]
Olympia Rising seems to be rendering the title screen with the latest Experimental build and seems to be playable now, closing since the issue is fixed now.
