### ISSUE TITLE
The Outer Worlds: Spacer's Choice Edition (1920490)

### ISSUE THREAD

**Issue by LukeFilewalker78** [ValveSoftware/Proton#6627]
# Compatibility Report
- Name of the game with compatibility issues:The Outer Worlds: Spacer's Choice Edition
- Steam AppID of the game:1920490

## System Information
- GPU: GTX 1070 Ti
- Driver/LLVM version: nvidia 525.89.02
- Kernel version: 6.2.7-2-Manjaro
- Link to full system information report as [Gist](https://gist.github.com/):Computer Information:
[System Info.txt](https://github.com/ValveSoftware/Proton/files/11010908/System.Info.txt)

- Proton version: Experimental 7.0-20230313

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
I was playing the original game without any issue, but since I bought the update, when I run the game there is no video image, like it has a problem to reproduce the intro video, and after I need to kill the app and restart the computer because the image freezes like there is something still running in the background, and also something is being copied into my clipboard;

LowLevelFatalError [File:Unknown] [Line: 1209] 
GameThread timed out waiting for RenderThread after 120.00 secs

0x000000007b01260e kernelbase.dll!UnknownFunction []
0x00000001419b5ba6 Indiana-Win64-Shipping.exe!UnknownFunction []

[steam-1920490.log](https://github.com/ValveSoftware/Proton/files/11010846/steam-1920490.log)

**Comment by mbriar** [comment]
Try setting `VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_wait %command%` as launch option (see https://github.com/HansKristian-Work/vkd3d-proton/issues/1389).

As a side note, seems like they switched to d3d12 by default in the Spaces's Choice Edition, which will likely perform significantly worse on Nvidia Pascal GPUs on Linux compared to d3d11. You can also try to set `%command% -dx11` as launch option to try and force it to run on d3d11.

**Comment by LukeFilewalker78** [comment]
Hello!! Thanks for your answer; I did try VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_id,VK_KHR_present_wait %command% and it worked for me. The other options failed both, same output, freeze and then crash, I hope it will be solved soon.

**Comment by jamie-pate** [comment]
This env variable no longer seems to work with proton 7,8, experimental.. videos are all blank

-dx11 just freezes (steamdeck, heroic launcher)

https://discord.com/channels/812703221789097985/1184210527547830362/1184215567075381248 
(wine-ge with prefer system libs fixes it in heroic launcher)

**Comment by TheFlagCourier** [comment]
> https://discord.com/channels/812703221789097985/1184210527547830362/1184215567075381248
 (wine-ge with prefer system libs fixes it in heroic launcher)

Just letting you know that your Discord link doesn't properly redirect. Just shows "No Text Channels" for me.

**Comment by jamie-pate** [comment]
I guess you need to have already joined the server?
https://discord.com/invite/rHJ2uqdquK
Yay for the erosion of the web by siloed communities :facepalm:
