### ISSUE TITLE
Touchpad pinch-to-zoom crashes most games under Xwayland

### ISSUE THREAD

**Issue by felixhaedicke** [ValveSoftware/Proton#6628]
Affected titles: Looks like any game is affected, e. g. Team Sonic Racing or Flight Simulator 2020 (Steam IDs 785260 / 1250410).

## System Information
- GPU: AMD RX 6800
- Driver/LLVM version: Mesa 23.0.0
- Kernel version: 6.2.6
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/felixhaedicke/61fd91e3dee17801129b7bd93a350538
- Proton version: 7.0-6

## Symptoms / Reproduction
Performing a simple pinch-to-zoom gesture on my multitouch touchpad (Apple Magic Trackpad 2) when a Proton game has focus crashes the game. See attached log.

This is reproducible on GNOME running under Wayland.
This is not reproducible in a non-Wayland session.
This is not reproducible on normal wine (tested Version 7.2 / 8.0) using the same games.

[steam-785260.log](https://github.com/ValveSoftware/Proton/files/11011292/steam-785260.log)

**Comment by kisak-valve** [comment]
Hello @felixhaedicke, this issue is already being tracked at #5744. Closing as a duplicate.
