### ISSUE TITLE
GPU Broken in Proton Experimental and Hotfix

### ISSUE THREAD

**Issue by VDavid003** [ValveSoftware/Proton#6629]
## System Information
- GPU: NVIDIA Quadro K2100M
- Driver/LLVM version: nvidia 470.161.03
- Kernel version: 6.2.7
- Link to full system information report as [Gist](https://gist.github.com/VDavid003/512eb6dff8ebd90cd3c37f9217b32bcf):
- Proton version: Experimental, Hotfix

Every game I've tested (All are Unity games) crash with Proton Experimental and Proton Hotfix, but start up fine with Proton 7.0.
The "Are You Ready for a Valve Index?" tool recognizes my Quadro K2100M with Proton 7.0, but shows "VideoController1" as the GPU when running on experimental.
Games with Unity show a "Failed to initialize player" message with the following details (dx9 games show dx9 instead of dx11 of course)
```Failed to initialize graphics.
Make sure you have DirectX 11 installed, have up to date
drivers for your graphics card and have not disabled
3D acceleration in display settings.

InitializeEngineGraphics failed
```
I'm not sure if only DirectX is broken, or the GPU as a whole. It may even be related to having a laptop optimus config with an integrated Intel GPU and a dedicated Quadro GPU.
I haven't found any other issue with this, so I'm not sure where the problem may be.
The games I've tested for now, are "Phasmophobia" and "Head Shot"

Here are logs for Phasmophobia on 7.0 and experimental:
[steam-739630-7.0.log](https://github.com/ValveSoftware/Proton/files/11019625/steam-739630-7.0.log)
[steam-739630-experimental.log](https://github.com/ValveSoftware/Proton/files/11019618/steam-739630-experimental.log)

**Comment by kisak-valve** [comment]
Hello @VDavid003, the builds of DXVK and VKD3D-Proton in Proton Experimental and future major Proton releases requires Vulkan 1.3 driver features provided by NVIDIA 510.47 and newer. (Currently noted at https://github.com/ValveSoftware/Proton/wiki/Changelog.)

Sorry, but NVIDIA ended support for the Kepler generation of video cards including your laptop with their 470 driver series and that means that your hardware will not work with Proton newer than 7.0.
