### ISSUE TITLE
call of duty: black ops 3 controller not being registered , game crashing. (app ID 366841)

### ISSUE THREAD

**Issue by yudatheboss** [ValveSoftware/Proton#6630]
call of duty black ops 3 will not launch and/or decks controller won't work. in compatibility mode (proton experimental) everything works fine up until the Zurich new world mission. when you open the door with your powers and walk in the robots break out of the glass and the screen goes purple/green and the game freezes and/or crashes.

**Comment by kisak-valve** [comment]
Hello @yudatheboss, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/864#issuecomment-1476537454.
