### ISSUE TITLE
Ghost Recon Wildlands (App ID: 460930) crashes on start up

### ISSUE THREAD

**Issue by nocnoc94** [ValveSoftware/Proton#6634]
# Compatibility Report
- Name of the game with compatibility issues: Ghost Recon Wildlands
- Steam AppID of the game: 460930

## System Information
- GPU: RTX 2070 Max Q
- Driver/LLVM version: nvidia 525.89.02
- Kernel version: 6.1.18-200.fc37.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/nocnoc94/a9665ff9dcbace9017e10620211f1e21
- Proton version: GE-Proton7-51, 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
- The game crashes on start up. After the uplay authorization, a small box with the game's logo appears. Then a back window appears and promptly disappears. Steam thinks the game is running but it hangs
- Judging from protonDB, this issue has appeared recently. Prior to this the game was reported to be working 
- [ProtonDB](https://www.protondb.com/app/460930)

## Reproduction
- Open the game and log into uplay with steam

[steam-460930.log](https://github.com/ValveSoftware/Proton/files/11031411/steam-460930.log)

**Comment by kisak-valve** [comment]
Hello @nocnoc94, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1507#issuecomment-1478292420.
