### ISSUE TITLE
 Sonic Frontiers (1237320)

### ISSUE THREAD

**Issue by DennisAnabones** [ValveSoftware/Proton#6636]
# Compatibility Report
- Name of the game with compatibility issues: Sonic Frontiers
- Steam AppID of the game: 1237320

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 23.0.0
- Kernel version: 6.2.7-arch1-1
- Proton version: Experimental

## I confirm:
- [ ] that I have checked whether there are updates for my system available.

Proton Log:
[steam-1237320.log](https://github.com/ValveSoftware/Proton/files/11043143/steam-1237320.log)

## Symptoms 
Frontiers won't boot and immediately stops

## Reproduction
Pressing play

**Comment by kisak-valve** [comment]
Hello @DennisAnabones we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6303#issuecomment-1480019660.
