### ISSUE TITLE
Ready or Not Vram Leak

### ISSUE THREAD

**Issue by GRBL-F** [ValveSoftware/Proton#6639]
# Compatibility Report
- Name of the game with compatibility issues: Ready or Not
- Steam AppID of the game: 1144200

## System Information
- GPU: RTX 3060ti OC 8GB
- Driver/LLVM version: nvidia 535.89.02
- Kernel version:  6.2.7-zen1-1-zen
- DE: KDE Plasma 5.27.3
- WM: KWin (X11)
- Link to full system information report as Gist: [System Info Report](https://gist.github.com/Agreeable-f/2375e518fc5ac60faaeb3e3398abf8f4)
- Proton version: 7.0-6, Proton Experimental, GE-Proton7-51

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

when loading into the main menu from startup the game takes up about 4.1GiB of vram. then when loading into the pre-game lobby it goes up to about 6.1GiB. then when loading into a game it will take up 7.8/8 GiB or for larger maps it will outright crash saying it ram out of video memory. the way it fills the Vram is similar to a ram leak however occuring on the video memory. this issue/behaviour does not happen on windows

## Reproduction

1. Start the game in either DX12 or DX11.
2. observe vram usage (i'm using KDE's plasma system monitor with vram usage shown on the gpu's history)
3. load into a pre-game lobby. (i joined a friend's private pre-game lobby as we were playing the game. not sure it matters but noting it for consistency)
4. observe Vram usage
5. load into a map. (the maps that crashed for me that were tested so far were neon clubhouse and valley of the dolls. 4u gas station was a case that used 7.8GiB of ram without crashing)
6. Observe Vram usage
7. if loaded into a map that crashes, observe the error message.

## Final notes

This was also tested in the ProtonGE discord on an amd card. same behaviour occurs where their Vram gets filled, however they had more Vram and did not crash.

The game's minimum spec requirements denote a gpu with 2GB of Vram. 8GiB should be more than enough on a 3060ti however it is still filled. The recommenced spec state 6GB Vram which is still below the 8GiB of my card

**Comment by kisak-valve** [comment]
Hello @Agreeable-f, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5985#issuecomment-1481423505.
