### ISSUE TITLE
Battlerite doesn't render character models in DX11 Mode.

### ISSUE THREAD

**Issue by Y4shin** [ValveSoftware/Proton#664]
Technically not a supported game, but works pretty well except for that issue. Launching in DX9 mode fixes it.

PC Info: https://gist.github.com/Y4shin/3cd43dded169c4ecc738cf6899c68eae
Issue consistent across Proton 3.7-3 and 3.7-4

**Comment by doitsujin** [comment]
It's a Unity Engine game and likely requires Stream Output. Will be fixed in DXVK as soon as an extension is publicly available.

**Comment by kisak-valve** [comment]
Hello @Y4shin, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue to https://github.com/ValveSoftware/Proton/issues/326#issuecomment-416063914.
