### ISSUE TITLE
World of Warships update 12.2 crashes Proton 7.x

### ISSUE THREAD

**Issue by webaake** [ValveSoftware/Proton#6643]
World of Warships update 12.2 (App id: 552990) crashes Proton 7.x. Crash report and Steam System Info attached. The crash occurs at or during Login to the game. First; "Game Loading..." then "Logging in..." = no sound and full stop. No messages - no nothing. Forced close needed. Crash report is generated and included below.

It does start with Proton 6.3-8. I can't test Experimental as I believe it needs Nvidia driver 510.x, which I can not use.
[WorldOfWarships64-2023-03-03_13-35-21.txt](https://github.com/ValveSoftware/Proton/files/11061171/WorldOfWarships64-2023-03-03_13-35-21.txt)
[steam_system_info.txt](https://github.com/ValveSoftware/Proton/files/11061174/steam_system_info.txt)

I also do not get any Proton logs which I reported in a separate issue here.

**Comment by kisak-valve** [comment]
Hello @webaake, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/333#issuecomment-1482774688.
