### ISSUE TITLE
The Binding of Isaac crashes whenever a X-Box 360 Controller is plugged in (USB)

### ISSUE THREAD

**Issue by alex-c3** [ValveSoftware/Proton#6644]
# Compatibility Report

    Name of the game with compatibility issues:Bind of Isaac: Rebirth (NON NATIVE REPENTANCE DLC)
    Steam AppID of the game:250900
    (THIS IS FOR THE REPENTANCE EXPANSION THAT ISNT LINUX NATIVE)

## System Information
Distro:Ubuntu 22.10
Kernel:5.19.0-35-generic
RAM:16 GB
GPU Driver:4.6 Mesa 22.2.5
GPU:Intel Mesa Intel UHD 630 (CFL GT2)
CPU:Intel Core i7-8850H @ 2.60GHz
Detailed System Information : https://gist.github.com/alex-c3/d62ecaed8741a5cf7a7c10f534311009

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

https://pastebin.com/uYWL4ehn

## Symptoms 
Whenever my X-Box 360 Controller is plugged in, the game crashes.
This means that:
1. If the controller is connected before the game launches, it will start loading to the point of showing a black blank window and crash in the next ~0.5s
2. If the game is launched without the controller plugged in, the games crashes just as the controller vibrates when plugged in (e.g. has been successfully connected). 
Notes:
a. The crash is "clean" : meaning that the window closes, and Steam detects it has closed. I can re-launch the game right after without issues, but it will crash following the patterns described above.
b. This happens using ProtonGE (7.53), ProtonExperimental and Proton 7.06
c. X-Box 360 Controller is the only USB device plugged-in.
d. Other games with Proton do work with the same controller (e.g. Hades), without crashing.
e. The game works perfectly when the controller is disconnected, as far as playing the first level.

## Reproduction
1. Install Steam
2. Force the use of Proton Experimental
3. Install The Binding Of Isaac (with Repentance)
4. Plug-in a 360 Controller
5. Launch the game

**Comment by kisak-valve** [comment]
Hello @alex-c3, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4868#issuecomment-1483034971.

**Comment by alex-c3** [comment]
@kisak-valve I'm so sorry but you can actually delete this issue.
I just realized that even the Native Non-Proton version crashes the same way, so, not a Proton issue as far as I understand.
