### ISSUE TITLE
Logitech G29 Detected as an XBOX Joystick on NFS HEAT

### ISSUE THREAD

**Issue by EazyAhmed** [ValveSoftware/Proton#6647]
# Compatibility Report
- Name of the game with compatibility issues: NFS Heat
- Steam AppID of the game: 1222680

## System Information
- GPU: GeForce RTX™ 3070 Ti
- Driver/LLVM version: nvidia 525.85.05
- Kernel version:5.15.0-67-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/izzijaz/5a0fd66338f3a47b0561df05fc1e69e6
- Proton version: Experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Logitech g29 Driving wheel is not bwing detected as a Wheel but as a joystick when i launch NFS heat.

**Comment by kisak-valve** [comment]
Hello @izzijaz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3955#issuecomment-1483895932.
