### ISSUE TITLE
東方謎縁塔 ~ Forsaken Labyrinth. Demo (2227430)

### ISSUE THREAD

**Issue by williewillus** [ValveSoftware/Proton#6649]
# Compatibility Report
- Name of the game with compatibility issues: 東方謎縁塔 ~ Forsaken Labyrinth. Demo
- Steam AppID of the game: 2227430 (Demo)

## System Information
Arch Linux packages

- GPU:  AMD RX5700XT
- Driver/LLVM version: Mesa 23.0.0-3
- Kernel version: 6.1.21-1-lts
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/williewillus/f85d1c79f46236516cecedd731ad486d
- Proton version: 7.0-6, reproduces on Experimental as of 2023-03-26

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Two issues. One, xaudio2 is missing DLLs. After downloading the xaudio2 32-bit DLL by hand and placing it into the game directory, an additional crash is observed due to missing shader functionality.

## Reproduction
1. Download the demo and try to launch. Get the following Proton log: https://gist.github.com/williewillus/efd301313143268fc289e23e6ed4e8e2
2. Get the 32-bit `xaudio2_9redist.dll` somehow (I downloaded the official [NuGet](https://www.nuget.org/packages/Microsoft.XAudio2.Redist/) package and extracted the dll from the zip) and place it into the game folder
3. Try to launch again. Now, there's a user level crash from the game as it tries to use unimplemented shader functionality. Logs: https://gist.github.com/williewillus/d9062f3c7993290e3f616d57a835eff7

**Comment by kisak-valve** [comment]
Hello @williewillus, it looks like depot 2227431 includes xaudio2_9redist.dll and d3dcompiler_47.dll, so I'd expect that to be beside the game binary and used.

**Comment by williewillus** [comment]
Sorry, looks like this is a false positive. I did a full reinstall/verify and things seem to work now. Thanks!
