### ISSUE TITLE
Tomb Raider I (224960)

### ISSUE THREAD

**Issue by taevasinine** [ValveSoftware/Proton#6652]
# Compatibility Report
- Name of the game with compatibility issues: Tomb Raider I
- Steam AppID of the game: 224960

## System Information
- 512 GB Steam Deck
- Proton version: 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

##
Proton log: [steam-224960.log](https://gist.github.com/Dimchkin/7f2b443d3bdaa5f733d40a9c501dc731)
##
## Symptoms 
Video cinematics like Lara's Home intro, level introduction videos are not displayed correctly - only black screen with audio.
Initial game FMV videos (logo and intro) are displayed correctly apart of aforementioned videos.

## Reproduction
Lara's Home intro video problem - start the game, enter Lara's Home level mode
Level Introduction video problem - start the new game
##
Would've been great to enjoy the title in all it's fully on Steam Deck, as the game itself works great, apart of the cinematics problems. I've tried Proton-GE as well, and all videos seem to work (in direct3d mode), but with atrocious game performance, so GE is not an option.

**Comment by kisak-valve** [comment]
Hello @Dimchkin, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3427#issuecomment-1487596954.
