### ISSUE TITLE
World of Tanks - Game crashes

### ISSUE THREAD

**Issue by matt32106** [ValveSoftware/Proton#6656]
# Compatibility Report
- Name of the game with compatibility issues: World of Tanks
- Steam AppID of the game: 1407200

## System Information
```
- GPU: GeForce RTX 3060 Ti Lite Hash Rate
- Driver/LLVM version: NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0   
- Kernel version: Linux 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 1679591355 experimental-7.0-20230323
```

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
Games crashes after using all memory (because OOM kills it).

## Reproduction
Launch game, wargaming center appears click play, when the window is displaying "connecting" the game freezes eats all memory + swap then crashes

Steam log:
[steam-1407200.zip](https://github.com/ValveSoftware/Proton/files/11114664/steam-1407200.zip)

**Comment by kisak-valve** [comment]
Hello @matt32106, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1369#issuecomment-1490837066.
