### ISSUE TITLE
Elden Ring (1245620)

### ISSUE THREAD

**Issue by Mobiacikaka** [ValveSoftware/Proton#6659]
# Compatibility Report
- Name of the game with compatibility issues: Elden Ring
- Steam AppID of the game: 1245620

## System Information
- GPU: NVIDIA T600 Mobile
- Driver/LLVM version: nvidia 530.41.03-2
- Kernel version: 6.2.9-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: proton-7.0-6e

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 
[steam-1245620.log](https://github.com/ValveSoftware/Proton/files/11139065/steam-1245620.log)

## Symptoms 
quit as soon as the game is launched. can't even see the logo.

## Reproduction
1. launch the game and it quits.

**Comment by kisak-valve** [comment]
Hello @Mobiacikaka, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1494422495.
