### ISSUE TITLE
Delete proton files also delete saves

### ISSUE THREAD

**Issue by Manflack** [ValveSoftware/Proton#6660]
Proton version: N/A
Platform: Steam Deck
OS version: 3.4.6
OS compilation: 20230313.1
Kernel version: 5.13.0-valve36-1-neptune

When Proton version is changed or press in options of game -> Developer -> Delete Proton files, delete also the game saves.
In case like Dark Souls 3 is annoying because doesn't have Cloud Saves.

Solution:
i. Encapsulate the files where is game files usually, so for each game will gonna be separate folder/files from this saved files.
ii. Copy and paste from old files to another Proton environment when changing compatibility tools performs.
iii. Along the first one, force cloud saves.

Steam Deck represent the cuspid of Valve user's and their love by ecosystem.
It's required to avoid friction between PC and Steam Deck experience solve this problem.

**Comment by kisak-valve** [comment]
Hello @Manflack,this issue is already being tracked at #428 / #231. Closing as a duplicate.
