### ISSUE TITLE
PlanetSide 2 (218230) Shader pre-caching issue

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#6663]
# Compatibility Report
- Name of the game with compatibility issues: PlanetSide 2
- Steam AppID of the game: 218230

## System Information
- GPU:  RX 580
- Driver/LLVM version:  Mesa 20.3.5
- Kernel version:  6.1.0
- Proton version: 6.21-GE-2 (occurs on vanilla as well as the 7.x/experimental series)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

 
[steam-218230.log](https://github.com/ValveSoftware/Proton/files/11165676/steam-218230.log)

## Symptoms 
The game ran perfectly fine with a smooth 60 FPS until a recent shader pre-cache has led the game running at a fixed 1-2 FPS when the main menu is displayed. Entering the server causes [Game error G12](https://www.planetside2.com/game-error?code=G12&info=Your%20graphics%20device%20driver%20crashed%20or%20reset.%20%20Please%20ensure%20your%20graphics%20drivers%20are%20up%20to%20date.%20(80070057)).

I've tried this with multiple Proton versions with the same result. I deleted the cache and even the entire game, re-downloaded, and resulted in the same problem. I am not sure how to get the game back to the way it was.

## Reproduction
Steam Flatpak was used, just run the game after a shader pre-cache.

**Comment by mbriar** [comment]
Has nothing to do with shader pre-caching, but you don't have a working vulkan driver for your AMD GPU, instead software rendering is used:

```
info:  llvmpipe (LLVM 15.0.7, 256 bits):
info:    Driver: 0.0.1
info:    Vulkan: 1.3.230
```

**Comment by kisak-valve** [comment]
Hello @hunter2k01, we're using one issue per unofficially supported game title, and usually I'd transfer this issue report to #5295, but as @mbriar points out, you're seeing a general video driver in Flatpak issue, not a Proton issue. This issue is something for the mesa package maintainers for Flatpak to ponder.

**Comment by ghost** [comment]
> Has nothing to do with shader pre-caching, but you don't have a working vulkan driver for your AMD GPU, instead software rendering is used:
> 
> ```
> info:  llvmpipe (LLVM 15.0.7, 256 bits):
> info:    Driver: 0.0.1
> info:    Vulkan: 1.3.230
> ```

> you're seeing a general video driver in Flatpak issue, not a Proton issue. This issue is something for the mesa package maintainers for Flatpak to ponder.

If this is a problem with the mesa driver in Flatpak then how do other games that utilize it able to run completely fine? (as in, no noticable issues, the games run with a much more expected FPS count)
