### ISSUE TITLE
Hot Wheels Unleased (1271700)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#6666]
# Compatibility Report
- Name of the game with compatibility issues: Hot Wheels Unleased
- Steam AppID of the game: 1271700

## System Information
- Steam Deck
- Proton version: 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

This is a verified title. Menu screen and boot screen are messed up / rainbow colors and split screen doesn't seem to work. Seems to be an issue with it loading certain assists.

![hotwheels](https://user-images.githubusercontent.com/130154278/230609030-1c03c63b-9a67-4a66-ba44-e5981edf1374.jpg)

## Reproduction

1. Download game to Steam Deck.
2. Play game.

**Comment by kisak-valve** [comment]
Hello @Lord-Krex, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5196#issuecomment-1500264146.
