### ISSUE TITLE
Elite Dangerous broke in recent update

### ISSUE THREAD

**Issue by cschalle** [ValveSoftware/Proton#6667]
A recent update to Elite Dangerous broke the rendering of the game on Proton (using NVidia graphics). The game used to work perfectly, but now there are rendering issues all over the place.  Attaching screenshot of how even the game menu mis-renders.
![Screenshot from 2023-04-07 09-38-02](https://user-images.githubusercontent.com/21689162/230618752-cdcf5cd4-76b1-436c-9708-1cfa064347b0.png)

**Comment by kisak-valve** [comment]
Hello @cschalle, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/150#issuecomment-1500308733.
