### ISSUE TITLE
Making Lovers (1200720)

### ISSUE THREAD

**Issue by DaeLliux99** [ValveSoftware/Proton#6671]
# Compatibility Report
- Name of the game with compatibility issues: Making Lovers
- Steam AppID of the game: 1200720

## System Information
- GPU: AMD ATI Radeon HD 7500M/7600M Series
- Driver/LLVM version: Mesa 23.0.1
- Kernel version: 6.2.10-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/DaeLliux99/81dd2dcde951247af9890a4e9d120730
- Proton version: All version (Experimental, 7.0-6, ...)

Logs with "PROTON_USE_WINED3D=1":
[steam-1200720.log](https://github.com/ValveSoftware/Proton/files/11182076/steam-1200720.log)

Logs without "PROTON_USE_WINED3D=1":
[steam-1200720.log](https://github.com/ValveSoftware/Proton/files/11182075/steam-1200720.log)
![image](https://user-images.githubusercontent.com/75711543/230692365-a638666b-7608-4402-8987-356fab80fb56.png)

## Symptoms 
When I wanted to play some games on Steam, I had to set the PROTON_USE_WINED3D=1 parameter and they ran fine. But from almost the beginning of this month (April/2023) a lot of games that ran with this parameter stopped working suddenly. It doesn't just happen with this particular game. I'm not sure if some system update caused it to break something or something, because I tried to do a pacman -U to downgrade the version of mesa or wine, but without success.

**Comment by kisak-valve** [comment]
Hello @DaeLliux99, your video card is a Terascale 2 generation video card. All Terascale cards do not support Vulkan and the `PROTON_USE_WINED3D` launch option is not considered supported.

Wined3d is the DirectX to OpenGL translation layer found in the upstream wine project. It's useful to have it around for troubleshooting, but any issues you have with it need to be reproduced with a vanilla wine install and reported to the upstream wine project and any fixes will come downstream to Proton when there is a major rebase to a newer wine version. The supported render path uses DXVK to translate DirectX 9-11 to Vulkan.

Sorry, but your hardware is unsupportable by Proton in general.
