### ISSUE TITLE
All RE Engine Games Crashing (Steam Deck)

### ISSUE THREAD

**Issue by SteadfastRPD** [ValveSoftware/Proton#6675]
I have tried to play all of the modern Resident Evil games using the RE Engine on my deck, but all seem to crash at random times. The screen will black out, turn back on with audio playing, but with the screen frozen, and then my deck will do a hard restart. I have exhausted everything imaginable, from ProtonGE, to reimaging, even to messing around with BIOS settings. I have tried it all, and to go into specifics as to all that I've tried would take hours to type. Every game is either playable or verified. 

I thought I had a faulty Deck, so I got my first one RMA'd, but it's still happening on my replacement Deck, too.

**Comment by kisak-valve** [comment]
Hello @SteadfastRPD, this needs to be evaluated on a per-game basis. Also, we're using one issue per unofficially supported game title, and these games have existing compatibility reports: https://github.com/ValveSoftware/Proton/search?q=resident+evil&type=issues

Please add your experience to the existing compatibility reports where they are relevant. In particular, if you're able to collect system and/or Proton logs of the crashes, that can be useful for the devs to ponder.
