### ISSUE TITLE
Path of Exile (238960) : random POE and steam closure

### ISSUE THREAD

**Issue by feydreva** [ValveSoftware/Proton#6677]
# Compatibility Report
- Name of the game with compatibility issues: Path Of Exile 
- Steam AppID of the game: 238960

## System Information
- GPU: AMD Radeon RX 6600 XT
- Driver/LLVM version: Mesa 23.0.1
- Kernel version: 6.2.8-zen1-1-zen (64-bit)
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/feydreva/03a852ee2ce24e8986841ee63a71ced0
- Proton version: Proton Experimental 

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-238960.log](https://github.com/ValveSoftware/Proton/files/11193979/steam-238960.log)

## Symptoms 
When playing game, game randomly crash.
it happened once in Hideout, once in Maps, when entering a zone in the campaign. (it happend after entering my hideout, after few second of play when I took the log)

game closes, and steam shuts down and close properly.

## Reproduction
Open stay, play path of exile  and wait it happens.

Thank you fr your help

**Comment by kisak-valve** [comment]
Hello @feydreva, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/58#issuecomment-1502321570.
