### ISSUE TITLE
Horizon Zero Dawn CPU 0 FPS in InGame Benchmark

### ISSUE THREAD

**Issue by the-coding-owl** [ValveSoftware/Proton#6680]
# Compatibility Report
- Name of the game with compatibility issues: Horizon Zero Dawn
- Steam AppID of the game: 1151640

## System Information
- GPU: Radeon 6600M
- Driver/LLVM version: AMD AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.49, 6.2.10-arch1-1)
- Kernel version: 6.2.10-arch1-1
- Link to full system information report as Gist: https://gist.github.com/the-coding-owl/80767b55b374c0d1ff2e5597d9039e1f
- Proton version: GE_Proton7_54-1

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

## Symptoms
I am on a Lenovo Legion 5 full AMD system from 2021 (5800H + 6600M) and experienced a lot of stuttering. While investigating this issue, I discovered something very strange with the benchmarks I can't make sense of.
The results show that the GPU is working good, producing lots of FPS, but the CPU is producing exactly 0 FPS.
I wonder if the stutter issue is caused by this non-FPS issue from the CPU, or if this is just a measurement glitch.

![20230413212104_1](https://user-images.githubusercontent.com/6013986/231864095-29af05d0-c56a-454b-b788-df8245075615.jpg)

## Reproduction
I just started the game and ran a benchmark.
The graphic settings doesn't seem to matter, I tried with a bunch of different presets and individual settings, the CPU never produces any FPS.
I also tried with some tips from the protondb website, which state that there is something weird going on with CPU clock timing, namely setting the kernel parameters "clocksource=tsc tsc=reliable" since someone mentioned he fixed stuttering on his machine this way.

[steam-1151640.log](https://github.com/ValveSoftware/Proton/files/11225788/steam-1151640.log)

**Comment by kisak-valve** [comment]
Hello @the-coding-owl, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4125#issuecomment-1507518284.
