### ISSUE TITLE
A Plague Tale: Innocence

### ISSUE THREAD

**Issue by Martin-DAN** [ValveSoftware/Proton#6684]
# Compatibility Report
- Name of the game with compatibility issues: A Plague Tale: Innocence
- Steam AppID of the game: 752590

## System Information
- GPU: NVIDIA GeForce RTX 3060
- Driver/LLVM version: NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0
- Kernel version: Linux 5.19.0-38-generic
- Link to full system information report as [Gist](https://gist.github.com/): [Report](https://gist.github.com/Martin-DAN/56e9df6130514ac8d86fc62e25a745c9)
- Proton version: 7.0-6

## I confirm:
- [1] that I haven't found an existing compatibility report for this game.
- [1] that I have checked whether there are updates for my system available.

[steam-752590.log](https://github.com/ValveSoftware/Proton/files/11235214/steam-752590.log)

## Symptoms 
Game starts but on the title screen (with all the rats), where it says "press any key", after pressing any key the game crashes to desktop.

## Reproduction

1. Launch game.
2. Wait for title screen, where the "press any key" button is.
3. Press any key or click the button.
4. Game crashes to desktop.
[steam-752590.log](https://github.com/ValveSoftware/Proton/files/11235214/steam-752590.log)

**Comment by kisak-valve** [comment]
Hello @Martin-DAN, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2739#issuecomment-1508949031.
