### ISSUE TITLE
Space Engineers

### ISSUE THREAD

**Issue by sanyanov** [ValveSoftware/Proton#6685]
# Compatibility Report
- Name of the game with compatibility issues: Space Engineers
- Steam AppID of the game: 244850

## System Information
- GPU: GTX 1060 6GB
- Driver/LLVM version: nvidia 530.41.03
- Kernel version: 6.1.22-1
- Link to full system information report: https://gist.github.com/sanyanov/88067e4f6311af4156dd45198d1c5e84
- Proton version: experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-244850.log](https://github.com/ValveSoftware/Proton/files/11237289/steam-244850.log)

## Symptoms 
The box appears at launch saying: "There is missing required C++ package. You have to accept elevation dialogs from the Steam to install prerequisistes". No dialog appears from steam and game can't launch.

## Reproduction
Start the game

**Comment by sanyanov** [comment]
Already tried to:
-Change Proton version
-Reinstall the game

Problem appeared after the new "Automatons" update. Previously the game worked fine.

**Comment by sanyanov** [comment]
Already tried to:
-Change Proton version
-Reinstall the game

Problem appeared after the new "Automatons" update. Previously the game worked fine.

**Comment by kisak-valve** [comment]
Hello @sanyanov, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1792#issuecomment-1509334162.
