### ISSUE TITLE
VRChat (438100)

### ISSUE THREAD

**Issue by illusioon** [ValveSoftware/Proton#6687]
## System Information
- GPU: RTX 2070S
- Driver/LLVM version: NVIDIA 525.105.17
- Kernel version: 6.1.21_1 (VOID LINUX)
- Proton version: Default/Experimental doesn't matter.

VRCHAT gui shows:

You are in offline testing mode and cannot travel to online worlds.
If you are trying to use VRCHAT normally, please ensure you start VRChat by starting launch.exe. You may need to update your shortcut.

Can't play VRCHAT anymore it won't let me join world.

When I start the game after installing, it logs me in through my Steam account as usual and then gives me the above message. If I click "okay", it comes back a second later. I can't use my account or do anything.

**Comment by kisak-valve** [comment]
Hello @illusioon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1199#issuecomment-1509762515.
