### ISSUE TITLE
Halo: MCC does not launch with Proton-Experimental

### ISSUE THREAD

**Issue by sunami88** [ValveSoftware/Proton#6688]
# Compatibility Report
- Name of the game with compatibility issues: Halo: The Master Chief Collection
- Steam AppID of the game: 976730

## System Information
- GPU: GTX 1650 Super
- Driver/LLVM version: nvidia 525.105.17
- Kernel version: 6.2.11-x64v3-xanmod1
- Link to full system information report: [Here](https://gist.github.com/sunami88/01f4ca7abec3fa7026bc10a91bc4be72)
- Proton version: Experimental and GE-7-55

## I confirm:
- [ ✅] that I haven't found an existing compatibility report for this game.
- [✅ ] that I have checked whether there are updates for my system available.

[Experimental-976730.log](https://gist.github.com/sunami88/2c675f4a058a130ecac3fcbfb26be88b)
[GE-7-55-steam-976730.log](https://gist.github.com/sunami88/3a780579e50c9984e16f6498c2386624)

## Symptoms 
Launch the game, I can see the EAC splashscreen, then the game stops and drops back to Steam.
(the same thing happens when launching with EAC disabled, just without the splashscreen obv)

## Reproduction
- With Experimental
Delete compdata folder
Delete Proton directories
Verify Integrity of everything
Try to start game, crashes

- With GE
Delete compdata folder
Delete GE directory
Extract GE .tar.gz
Verify Integrity of Halo: MCC
Try to start game, Steam performs first time installations, crashes

- Running Experimental after first time installations occurs with GE leads to the EAC splashscreen, then dropping back to Steam (game crashed). The .log after this is nearly 12,000 lines and I don't think it has anything new to add.

## Other
I've done so much messing around with this I feel like it has to be something simple. I've had this issue before but have usually just fallen back to an older version of Proton (i.e. 6.3 will indeed launch the game successfully), but now would LOVE to play multiplayer...

I have also:
Verified runtime/soldier/eac runtime many times
Messed around with protontricks and winetricks
Made sure my system wine is up to date (winehq-stable)
Running with system libs
Running with Steam integrated libs
Tried running the game from an NTFS partition and the steam-runtime (etc) from / instead of from game partition

**Comment by kisak-valve** [comment]
Hello @sunami88, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2907#issuecomment-1509998620.
