### ISSUE TITLE
Some games that use Proton launch in a transparent window

### ISSUE THREAD

**Issue by lavadrop** [ValveSoftware/Proton#6690]
#### Your system information
https://gist.github.com/lavadrop/1b70906569c739921d2976373e06259a

* Steam client version (build number or date): 1679680416
* Distribution (e.g. Ubuntu): OpenSUSE
* Opted into Steam client beta?: Yes and No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I've tested on both my system package version as well as the Flatpak version. System version has the Steam client beta activated and Flatpak version is stable version.
This just started today just after the last episode where Steam couldn't update itself last week. I hadn't used my computer, I was on vacation.
First, I tried running Steam remote play from my living room TV. I tried with the pipewire desktop capture since I was already in a Wayland session. The game I tried first was No Man's Sky. Game loaded fine over Steam Link on my remote living room computer and the UI was fine, however when the game loaded into my save, the game port was all red. Menus were fine but I did notice a loss of FPS. I suspected a regression of the bug that made Steam Remote play output the video stream in RGB instead of yuv420. So I exit the game and decided to end the steam play suspecting a pipewire capture issue. So I launch the game from my computer directly on its monitor and the game crashes my GPU and I'm forced to restart the system.
I restart and open an Xorg session this time. Now, when I opened No Man's Sky (which uses Proton Experimental) I got a transparent window with the music playing in the background. Then I tested Street Fighter V... same issue. Return to Monkey Island runs just fine (native client). Stray ran at first but now shows the same issue. Redout shows a transparent window too. Journey loads too and uses Proton. Record of Lodoss War loads and plays fine too and uses Proton. Hyper Light Drifter and FEZ load fine too, the former using Proton and the latter has a native client. Untitled Goose game also runs fine and is uses Proton. Skull Girls 2nd Encore also loads and uses Proton.

#### Steps for reproducing this issue:

1. Run a Proton-compatible game. 
 
![Screenshot from 2023-04-15 19-18-44](https://user-images.githubusercontent.com/6760790/232264776-9b48ce1b-7183-402f-b438-b5a7c5735a59.jpg)
![Screenshot from 2023-04-15 19-19-12](https://user-images.githubusercontent.com/6760790/232264777-4447f46d-6ebe-4e3e-aaed-b73915312074.jpg)
![Screenshot from 2023-04-15 20-30-02](https://user-images.githubusercontent.com/6760790/232264778-aef61c99-4042-49c1-a662-4de8c718085c.jpg)

**Comment by kisak-valve** [comment]
Hello @lavadrop, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report.

This reads more like a video driver issue than a Proton issue and should probably be mentioned to your video driver vendor. For posterity, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by lavadrop** [comment]
Thank you, I forgot about this tracker.

**Comment by lavadrop** [comment]
> Hello @lavadrop, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report.
> 
> This reads more like a video driver issue than a Proton issue and should probably be mentioned to your video driver vendor. For posterity, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

How do I contact AMD about this possibility?

**Comment by n00btube3D** [comment]
@lavadrop You are using Mesa, which is an open source driver. So you should make a issue on their gitlab bug tracker: https://gitlab.freedesktop.org/mesa/mesa/-/issues

I also think that proton logs will be great for easier debugging. 
(`PROTON_LOG=1 %command%` as launch option, a log file should be generated at `$HOME/steam-$APPID.log`)

**Comment by lavadrop** [comment]
Here's some proton logs from several games with other graphical/interactivity issues:
[steam-275850.log](https://github.com/ValveSoftware/Proton/files/11269039/steam-275850.log)
[steam-310950.log](https://github.com/ValveSoftware/Proton/files/11269041/steam-310950.log)
[steam-1685750.log](https://github.com/ValveSoftware/Proton/files/11269042/steam-1685750.log)

**Comment by JosSamLoh** [comment]
Also encountering this issue on an RTX 2080S in No Mans Sky using the Steam flatpak on Fedora Silverblue, using the [uBlue nvidia](https://ublue.it/) image. 

[System info and Proton log - No Mans Sky](https://gist.github.com/JosSamLoh/cb5335ccd0fd00d9e7d1533536a370fe)

**Comment by JosSamLoh** [comment]
Very strangely, running the game in Wayland first seems to completely fix the issue for me.

**Comment by lavadrop** [comment]
> Very strangely, running the game in Wayland first seems to completely fix the issue.

Running in wayland I get the blue and red screens, running on X, the transparent window.

**Comment by JosSamLoh** [comment]
> Very strangely, running the game in Wayland first seems to completely fix the issue for me.

Nevermind, now I am getting the same issue. At some point it seems to randomly fix itself I guess. Wayland works completely fine but X is invisible now.

**Comment by JosSamLoh** [comment]
Figured out a fix for No Mans Sky, at least for my case. Since I am using the flatpak version of steam, using flatseal and enabling "GPU acceleration" (`device=dri`), then running the game, has fixed it. Subsequent launches carry on the fix, even with the option disabled after the first launch.

**Comment by lavadrop** [comment]
It appears to be caused by this Mutter bug: 
https://gitlab.gnome.org/GNOME/mutter/-/issues/2678
Should this report be closed @kisak-valve ?

**Comment by lavadrop** [comment]
Fixed in latest Mutter update.
