### ISSUE TITLE
[Question] Proton 8

### ISSUE THREAD

**Issue by gabriele2000** [ValveSoftware/Proton#6691]
I've got to ask.
My life depends on fs_hack since I want to use FSR in every game I can (don't ever mention gamescope to me, I know it and it won't work well since I'm on Nvidia).

Because of this I'm stuck with wine-tkg-7.20 because fs_hack patch breaks since 7.21... 
Last year you guys released Proton 7 something like a month later since Wine 7, but we're in April, Wine 8 has been released since February and you've made almost no changes since 2 months.

Are you guys actually rebasing it?

**Comment by kisak-valve** [comment]
Hello @gabriele2000, same as https://github.com/ValveSoftware/Proton/issues/1854#issuecomment-435911478. Proton devs will rebase Proton on a newer release of wine when they are ready.

There are no time estimates given on when this happens.

**Comment by gabriele2000** [comment]
> Hello @gabriele2000, same as [#1854 (comment)](https://github.com/ValveSoftware/Proton/issues/1854#issuecomment-435911478). Proton devs will rebase Proton on a newer release of wine when they are ready.
> 
> There are no time estimates given on when this happens.

I read that comment but I was just curious **if** the rebase was in-progress: there's nothing at all since months.
The only actual stuff that gets updated is DXVK, DXVK-NVAPI and nothing else.

**Comment by gabriele2000** [comment]
Ahahah, the irony... Proton 8 released, YAY!
