### ISSUE TITLE
Forza Horizon 5 Crashes

### ISSUE THREAD

**Issue by TheEvilSkeleton** [ValveSoftware/Proton#6692]
# Compatibility Report
- Name of the game with compatibility issues: Forza Horizon 5
- Steam AppID of the game: 1551360

## System Information
- GPU:  Sapphire Nitro+ RX 580 4 GB
- Driver/LLVM version:  Mesa 23.0.2 (git-4d5e73870e) / LLVM 15.0.7
- Kernel version:  6.2.9-300.fc38.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/TheEvilSkeleton/a003ee665e30c849cf5472dd8d7a7da8
- Proton version: 7.0-6 and 8.0-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1551360.zip](https://github.com/ValveSoftware/Proton/files/11255986/steam-1551360.zip) (Proton 8.0-1 was used)

## Symptoms 

A few minutes after launching Forza Horizon 5 (from few seconds to 5 minutes), the game freezes for a few minutes, and crashes (exits).

## Reproduction

1. Launch Forza Horizon 5
2. Start playing, or go to the settings and wait for a few minutes.

**Comment by TheEvilSkeleton** [comment]
I just noticed https://github.com/ValveSoftware/Proton/issues/5285 from this comment https://github.com/ValveSoftware/Proton/issues/6596, my apologies

**Comment by kisak-valve** [comment]
Hello @TheEvilSkeleton, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5285#issuecomment-1512114890.
