### ISSUE TITLE
cant run battlefield 4 with proton 8

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#6694]
# Compatibility Report
- battlefield 4:
- https://store.steampowered.com/app/1238860/Battlefield_4/:

## System Information
- GPU:Mesa Intel® UHD Graphics (TGL GT1)
- Driver/LLVM version:*-display                 
       description: VGA compatible controller
       product: NVIDIA Corporation
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: /dev/fb0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller cap_list fb
       configuration: depth=32 latency=0 mode=1920x1080 visual=truecolor xres=1920 yres=1080
       resources: iomemory:600-5ff iomemory:620-61f memory:81000000-81ffffff memory:6000000000-61ffffffff memory:6200000000-6201ffffff ioport:4000(size=128) memory:82000000-8207ffff
  *-display
       description: VGA compatible controller
       product: Intel Corporation
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: iomemory:620-61f iomemory:400-3ff irq:157 memory:6202000000-6202ffffff memory:4000000000-400fffffff ioport:5000(size=64) memory:c0000-dffff memory:4010000000-4016ffffff memory:4020000000-40ffffffff

- Kernel version: 5.4 ga
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:8.0

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [O ] that I have checked whether there are updates for my system available.

## Symptoms 
when running bf4 in steam library it runs it as button shows and ea app window for login opens, bu there r no content in window so bf 4 cant be logged in to ea app
![Screenshot from 2023-04-18 15-20-59](https://user-images.githubusercontent.com/58201022/232742209-e038e144-c11a-44fc-b5fa-d6dfc99bb976.png)

**Comment by kisak-valve** [comment]
Hello @toyotominashimoto, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3994#issuecomment-1512995378.
