### ISSUE TITLE
Cyberpunk 2077 nonresponsive when started

### ISSUE THREAD

**Issue by Johwesh** [ValveSoftware/Proton#6695]
# Compatibility Report
- Name of the game with compatibility issues: Cyberpunk 2077
- Steam AppID of the game: 1091500

## System Information
- GPU: Intel arc a750
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 23.0.2
- Kernel version: 6.2.10-arch1-1
- Computer Information: https://gist.github.com/Johwesh/b44138e6ae4c1fa8adb975de35b11b9b
- Log file: [steam-1091500.log](https://github.com/ValveSoftware/Proton/files/11261545/steam-1091500.log)
      
- Proton version: 7.0-6, 8.0-1, experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 

## Symptoms 
Issue arose after 1.62 update. When starting the game, the cd projekt red launcher comes up as it's supposed to. However, when the game itself starts, it starts on a nonresponsive black screen. No sound, no input appears to register.

## Reproduction
Tried reinstalling the game, as well as running with proton 7, 8, and experimental. The same issue arises in all scenarios.
So far, there's no issue with other games ran through proton (tested Fallout 3 and Borderlands 2).

**Comment by kisak-valve** [comment]
Hello @Johwesh, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1513031863.
