### ISSUE TITLE
Minecraft Legends: unimplemented function

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#6697]
# Compatibility Report
- Name of the game with compatibility issues: Minecraft Legends
- Steam AppID of the game: [1928870](https://steamdb.info/app/1928870/)

## System Information
- GPU: Radeon RX 580 Armor 4G OC
- Driver/LLVM version: 4.6, Mesa 22.2.5
- Kernel version: 5.19.0-38-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Pavocracy/0afca5a929bbb19324ea3a9d66e528d2
- Proton version: Experimental (tried version 8 down to version 6 all fail)
[steam-1928870.log](https://github.com/ValveSoftware/Proton/files/11264230/steam-1928870.log)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game won't launch. Logs show the error: Unhandled exception: unimplemented function api-ms-win-core-psm-appnotify-l1-1-0.dll.RegisterAppStateChangeNotification called in 64-bit code (0x000000007b01260e).

## Reproduction
Install minecraft legends through steam on ubuntu 22.04, enable proton for experimental or version 8, 7 or 6, try to launch game.

**Comment by ghost** [comment]
whoops, looks like between searching for an existing issue and then taking the time to fill out this issue, another issue was posted for the same game but for the steam deck.

**Comment by kisak-valve** [comment]
Hello @Pavocracy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6696#issuecomment-1513489976.
