### ISSUE TITLE
Among us on linux

### ISSUE THREAD

**Issue by Greenator** [ValveSoftware/Proton#6698]
I can't get on among us on linux chromebook
![Screenshot 2023-04-18 1 39 10 PM](https://user-images.githubusercontent.com/117417022/232923950-67b22a4c-d9df-46de-8aa0-9ea079a6a66f.png)

This keeps coming up

**Comment by kisak-valve** [comment]
Hello @Greenator, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4190#issuecomment-1513897898.
