### ISSUE TITLE
Dragon Ball Z: Kakarot

### ISSUE THREAD

**Issue by Youshou-Rhea** [ValveSoftware/Proton#6703]
# Whitelist Request
- Name of the game to be whitelisted: Dragon Ball Z: Kakarot
- Steam AppID of the game: 851850

## System Information
- GPU:  Steam Deck
- Driver/LLVM version:  Steam Deck
- Distro version:  Steam Deck (Latest Stable)
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7.0

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [x] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @Youshou-Rhea, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4847#issuecomment-1514854399.
