### ISSUE TITLE
Red Dead Redemption 2 via Steam, Rockstar Launcher error popup appears twice and game does not launch

### ISSUE THREAD

**Issue by mareofnight** [ValveSoftware/Proton#6706]
My environment:

- Intel® Core™ i7-8750H CPU @ 2.20GHz × 12
- Nvidia GP106M [GeForce GTX 1060 Mobile]
- nvidia-driver-525 (proprietary)
- Ubuntu 22.04.1 LTS
- flatpak installation of Steam client
- Proton 6.3-8 selected in Red Dead Redemption 2 compatibility settings

When I click Play in the Steam client, I get a message that says:
> An error has occurred. Please make sure all instances of the Rockstar Launcher have been closed and try again. If you continue to see this error, please visit https://support.rockstargames.com

I watch my Process Monitor window while starting the game, and there is only one instance of the process "Rockstar-Games-" and it only appears when the error popup is visible. When I either close the popup or kill the process, the process and popup both go away. the game continues preparing to launch (processing vulcan shaders, etc) and then the same popup and "Rockstar-Games-" process appear a second time. After I close them, the game does not launch.

At the very end of the failed launch process, I get a new popup error that says:
> Failed to locate the Rockstar Games Launcher, please verify your game data and complete the Rockstar Games Launcher installation.

After that, Steam stops trying to launch the game and the play button reappears.

Possibly relevant, the folder "~/.var/app/com.valvesoftware.Steam/.steam/steam/steamapps/compatdata/1174180/pfx/drive_c/Program Files/Rockstar Games/Launcher" was initially empty, and "verify game files" didn't see a problem with that. Some online support articles indicated the launcher was supposed to be here, so I tried both installing the Rockstar-Games-Launcher.exe from Rockstar's website and putting it there, and copying the Rockstar-Games-Launcher.exe from the Steam installation on a different computer and putting it there. Neither of these things changed the result.

I have also tried:
- Earlier Proton version (same error)
- Later Proton versions (the game silently fails to launch without the Rockstar launcher even appearing)
- Reboot the computer and try launching the game first thing after reboot (same error)
- Verify integrity of game files... (no problems found)

Please advise me on what else I can do to fix this issue and play the game.

**Comment by FeRChImoNdE** [comment]
I'm having the same problem. Launcher fails twice, then switching to GE-Proton7-33 game launches but crash to desktop. Setting PROTON_LOG=1 can see that:

`wine: Unimplemented function winegstreamer.dll.winegstreamer_create_video_decoder called at address 000000007B0124DE (thread 048c), starting debugger...
`

**Comment by kisak-valve** [comment]
Hello @mareofnight, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-1517785017.

**Comment by Szlafrox** [comment]
If you have the launcher installed (you already played it on your machine and some update broke it), go thru the launcher's installation process and change the installation location. Just click "browse" and you get list of files installed in the sandbox, there should be folder named "Rockstar Games" (or Launcher idk) click it and there shouldn't be an error.

Worked for me 👍 . Btw reinstalation did not. Hope it helps someone
