### ISSUE TITLE
Games crash when using the GNOME 3 finger gesture to show applications running

### ISSUE THREAD

**Issue by dylanmtaylor** [ValveSoftware/Proton#6707]
I have a weird issue where many games just crash on GNOME Wayland when using the 3 finger gesture on my trackpad to show running applications (3 finger swipe up on the touchpad). Alt-Tab works, but the games just exit immediately with no warning. A few examples: Octopath Traveler II, Persona 3 Portable, Tetris Effect: Connected. I've hit this on Proton 8 and the latest experimental builds. I am running GNOME 44 on Ubuntu 23.04 on this system.

**Comment by dylanmtaylor** [comment]
Attaching some system info files in case they're helpful.

![image](https://user-images.githubusercontent.com/277927/233668267-8607c789-4ac1-4646-bfe6-3ff4748dfa4e.png)
![image](https://user-images.githubusercontent.com/277927/233668384-24257e94-0fca-4253-b78a-18b423b986b6.png)

[lshw.txt](https://github.com/ValveSoftware/Proton/files/11296860/lshw.txt)

**Comment by kisak-valve** [comment]
Hello @dylanmtaylor, this issue is already being tracked at #5744. Closing as a duplicate.
