### ISSUE TITLE
Dark Souls Remastered (570940) doesn't load in Ubuntu 23.04

### ISSUE THREAD

**Issue by dmwest** [ValveSoftware/Proton#6710]
# Compatibility Report
- Name of the game with compatibility issues: Dark Souls Remastered
- Steam AppID of the game: 570940

## System Information
- GPU: GTX 960
- Driver/LLVM version: nvidia 525.105.17
- Kernel version: 6.2.0-20-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/dmwest/3e4bf868148ec1bd169cb0c013ae7632
- Proton version: 1681743047 experimental-8.0-20230417

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

## Symptoms 

When you try to load the game the game window starts to open and then minimises. The screen then becomes frozen and you have to kill the game window to get back to the desktop. I have tried different proton versions but this doesn't appear to make any difference.

The game was working on Ubuntu 22.10 so something must have changed in the new version.

## Reproduction

Install Steam on Ubuntu 23.04 and run Dark Souls Remastered without any launch options.

[steam-570940.log](https://github.com/ValveSoftware/Proton/files/11301299/steam-570940.log)

**Comment by kisak-valve** [comment]
Hello @dmwest, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1026#issuecomment-1518660397.
