### ISSUE TITLE
Apex Legends (1172470) - EAC is broken

### ISSUE THREAD

**Issue by webbongithub** [ValveSoftware/Proton#6712]
# Compatibility Report
- Name of the game with compatibility issues: Apex Legends
- Steam AppID of the game: 1172470

## System Information
- GPU: GTX 1060 3GB
- Driver/LLVM version: Nvidia 525.105.17
- Kernel version: 6.2.21_1
- Link to full system information report as Gist: https://paste.sr.ht/~webb/76740c0ef25c2ca22656a6c08743c7dbc9796659 (GitHub Gist is broken right now for me)
- Proton version: experimental-8.0-20230417 (as well as other versions)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1172470.log](https://github.com/ValveSoftware/Proton/files/11303012/steam-1172470.log)

## Symptoms 

When starting the game a window pops up with "Easy Anti-Cheat Hash Catalogue not found"

## Reproduction

Launch the game with Proton Experimental and the EAC runtime installed on the hardware and software configuration.

**Comment by pollux78** [comment]
just launched the game with proton 8 and experimental (bleeding edge) on the native version of steam on nobara and have no issues.
what distro are you running?

**Comment by webbongithub** [comment]
I'm running Void Linux with glibc, as per the system report.

**Comment by kisak-valve** [comment]
Hello @webbongithub, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1519063241.

**Comment by webbongithub** [comment]
> Hello @webbongithub, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#4350 (comment)](https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1519063241).

The footer in the template implies that a seperate report should be made if the issue doesn't overlap. It might be worth rewording it.
