### ISSUE TITLE
New Proton expiremental on Ubuntu 23.04 eat CPU

### ISSUE THREAD

**Issue by PhanAlexandre** [ValveSoftware/Proton#6713]
On the new proton experimental, the CPU usage jump by 20% on all the core on Ubuntu 23.04 since this week.
For example with Cookies Clicker, the CPU usages jump from 5% on 1 core to 25% on all the CPU core.
I was able to open at least 5 low usages idle game at the same time, but now just Cookie Clicker and Antimatter Dimension use more than 60% of CPU on all core with a AMD 7 ryzen 5800X 16 cores.

**Comment by kisak-valve** [comment]
Hello @PhanAlexandre, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to some of the affected game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by PhanAlexandre** [comment]
here is the gist and the log of two of the game i was previously able to open without to much problem (cookies clicker and Antimatter dimension) but now use a lot a resources 

https://gist.github.com/PhanAlexandre/a59a0aad3a32d4b33a0ceaf5670904b0
[steam-1399720.log](https://github.com/ValveSoftware/Proton/files/11304714/steam-1399720.log)
[steam-1454400.log](https://github.com/ValveSoftware/Proton/files/11304718/steam-1454400.log)

**Comment by PhanAlexandre** [comment]
It might be a problem on my part my Nvidia 3600Ti is not list in the system spec

**Comment by kisak-valve** [comment]
Thanks, these are the lines to focus on in your system information:
https://gist.github.com/PhanAlexandre/a59a0aad3a32d4b33a0ceaf5670904b0#file-system-L48
https://gist.github.com/PhanAlexandre/a59a0aad3a32d4b33a0ceaf5670904b0#file-system-L165-L187
https://gist.github.com/PhanAlexandre/a59a0aad3a32d4b33a0ceaf5670904b0#file-system-L416-L438

Your system is configured to run everything on llvmpipe and lavapipe, which is mesa's faster CPU renderer. The entirety of the additional CPU load is because you're not using a GPU. It's more impressive that these games are running at all, and at a playable framerate than anything else.

**Comment by PhanAlexandre** [comment]
> Thanks, these are the lines to focus on in your system information: https://gist.github.com/PhanAlexandre/a59a0aad3a32d4b33a0ceaf5670904b0#file-system-L48 https://gist.github.com/PhanAlexandre/a59a0aad3a32d4b33a0ceaf5670904b0#file-system-L165-L187 https://gist.github.com/PhanAlexandre/a59a0aad3a32d4b33a0ceaf5670904b0#file-system-L416-L438
> 
> Your system is configured to run everything on llvmpipe and lavapipe, which is mesa's faster CPU renderer. The entirety of the additional CPU load is because you're not using a GPU. It's more impressive that these games are running at all, and at a playable framerate than anything else.

Is seems that my GPU is not recognize by Steam, i am currently reinstalling the driver

**Comment by PhanAlexandre** [comment]
all right, after reinstalling all the driver, reboot and re-download all the vulkan shader cache, every thing work just fine, its now just using 10% of the CPU with 6 games opens.
The problems was on my side, my gpu was not recognize by steam.
