### ISSUE TITLE
Btaman Arkham Asylum

### ISSUE THREAD

**Issue by AbdallahALSHARIQI** [ValveSoftware/Proton#6714]
proton 8 
![gghjg](https://user-images.githubusercontent.com/77125548/233872872-00908522-e0f2-4c85-9465-cadcf37b5ee9.png)
ubuntu 23.04

**Comment by AbdallahALSHARIQI** [comment]
but arkham city work very fine

**Comment by kisak-valve** [comment]
Hello @Abdullahalshriqi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/421#issuecomment-1519205941.
