### ISSUE TITLE
[REGRESSION] - Shatterline Doesn't Work In Proton 8

### ISSUE THREAD

**Issue by zaxlofful** [ValveSoftware/Proton#6716]
# Compatibility Report
- Name of the game with compatibility issues: Shatterline
- Steam AppID of the game: 2087030

## System Information
- GPU: NVIDIA Corporation NVIDIA GeForce RTX 3080/PCIe/SSE2
- Driver/LLVM version: 4.6.0 NVIDIA 515.105.01
- Kernel version: 5.19.0-40-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ZaxLofful/12c0287b8b69618707851128a99ea444
- Proton version: 8.0-1

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-2087030.tar.gz](https://github.com/ValveSoftware/Proton/files/11318696/steam-2087030.tar.gz)

## Symptoms 

Only splash screen launches and then it closes without fully launching.

## Reproduction

Use Proton 8.0-1, switching to 7.0-6 makes it work again.

**Comment by kisak-valve** [comment]
Hello @ZaxLofful, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6165#issuecomment-1521683485.
