### ISSUE TITLE
***stack smashing detected*** Tons of games don't work i.e.: DOOM(s)/Eternal, Cursed Castilla Ex, Quake II, etc...

### ISSUE THREAD

**Issue by pacomix** [ValveSoftware/Proton#6726]
Installed latest Lubuntu and Steam from the official webpage. Used Proton experimental, v8 and v7, all with the same effect.

Tried with DOOM, 3D Mark, Cursed Castilla EX, Quake II, Quake, etc.... Just after clicking on play and after 2/3 seconds the Play button gets highlighted again. Not even an attempt to open a window or something.

Steam log shows the ***stack smashing detected***. The overlay error on loading doesn't affect.
I'm using an eGPU (nVidia 560Ti) with 390 drivers. Lubuntu 22.04.

Linux 5.19.0-41-generic _#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 GNU/Linux
[Steam system info](https://gist.github.com/pacomix/d0e276b04def16d7f879a847eac0cf68#file-system-info-txt)
[Steam Output Log](https://gist.github.com/pacomix/d0e276b04def16d7f879a847eac0cf68#file-steam-log)

**Comment by kisak-valve** [comment]
Hello @pacomix, the NVIDIA 390 series video driver is older than the support cutoff for Proton. Additionally, there is no video driver which supported Vulkan on your Fermi generation NVIDIA card. Sorry, but your hardware is unsupportable in general by Proton.

That set aside, the issue you've encountered is being tracked at https://github.com/ValveSoftware/steam-runtime/issues/420.

**Comment by pacomix** [comment]
Thank you very much for your quick answer @kisak-valve 

That's really weird... I've been testing different Linux distros for my hardware (Acer Aspire 7750g + eGPU). (By the way it's a pleasure to have Linux + eGPU, no headaches like in Windows although I didn't pay YET the 15$ fee to get the config tool)

One of the distros I tried (Manjaro Linux) did run the aforementioned games without issues although a bit slow. Then I tried Fedora wich run the games way faster. And then I decided to try Lubuntu since "the official" supported distro.

The aforementioned games didn't run anymore but on the other side games like half life ran at double the FPS in comparison with the other two distros. So yes... somehow the drivers and system should be supported. I will take a look now at the referenced issue you mention in regard to the ***stack smashing detected***

**Comment by pacomix** [comment]
@kisak-valve Finally I discovered the cause (opening another issue for Steam client now). These games works absolutely fine with Fermi and nVidia 390.xx driver when selecting a lower version of Proton (some games work with 5+ and some other with 4+) but the problem was that for some reason Steam ignores the per-game compatibility tool selection. Setting it globally does the trick luckily.

What is quite distracting is your statement:

> ***the NVIDIA 390 series video driver is older than the support cutoff for Proton***

Thing that is valid for higher versions of Proton but switching to lower ones fixes the problem on my hardware setup. :)

I would add a correction to your statement:

> your hardware is unsupportable in general by Proton ***BUT*** you can try to use lower versions of Proton since sometimes they make the older games work with legacy drivers.
