### ISSUE TITLE
Age of Empires 3 Definitive Edition crash on Proton 8.0-1

### ISSUE THREAD

**Issue by orklann** [ValveSoftware/Proton#6727]
# Compatibility Report
- Age of Empires 2 Definitive Edition
- Steam AppID of the game: 813780

## System Information
- GPU: AMD RX 580
- Driver/LLVM version: Mesa Version: 22.2.5
- Kernel version: 5.19.0-41-generic (Ubuntu 22.04)
- Proton version: 8.0-1

## I confirm:
- [x] Starting the game will crash after a few seconds

## Symptoms 
Starting the game will crash after a few seconds. See crash screenshot at  the Screenshot section below

## Reproduction
1. Install the game on steam on Ubuntu
2. Set the compatibility to Proton 8.0-1
3. Run the game
4. Crash

## Screenshot 

![Screenshot from 2023-04-29 18-42-48](https://user-images.githubusercontent.com/5492042/235298634-0b3a7448-9512-40fb-8624-a497bf234eda.png)

**Comment by kisak-valve** [comment]
Hello @orklann, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3189#issuecomment-1528775420.
