### ISSUE TITLE
Please Fix Persona 5 Strikers video codec

### ISSUE THREAD

**Issue by Logge1002** [ValveSoftware/Proton#6731]
# Compatibility Report
- Persona 5 Strikers 
- Steam AppID of the game:

## System Information
- steam deck
- Proton version: 8.01 or proton Ge7.55

Game will work with proton ge 7.54 but the video playback only shows the video itself and the music track. Sfx and all voices are missing. Please fix that in the future. Already tried installing codecs with protontricks but didn’t help.

**Comment by kisak-valve** [comment]
Hello @Logge1002, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4636#issuecomment-1529041889.
