### ISSUE TITLE
Ability to install java for games written by java

### ISSUE THREAD

**Issue by MrThursby** [ValveSoftware/Proton#6735]
# Feature Request
I think it's worth adding the ability to install java for games written by java

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
When adding non-steam games written in java to the library, they do not run (

**Comment by kisak-valve** [comment]
Hello @MrThursby, Proton shouldn't be involved in a system installed java game.

Instead, the non-steam game entry should be configured to call java installed on the system with the target or launch options configured with the parameters it needs to find and run the java application.
