### ISSUE TITLE
Triangle Strategy - A770 Linux, crashes on startup

### ISSUE THREAD

**Issue by atrauzzi** [ValveSoftware/Proton#6737]
# Compatibility Report
- Name of the game with compatibility issues: Triangle Strategy
- Steam AppID of the game: 1850510

## System Information
- GPU: Intel A770
- Driver/LLVM version: Latest Fedora
- Kernel version: `6.2.12-300.fc38.x86_64`
- Proton version: 8/Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
I try running the game, a short amount of time passes and then I get a crash.

**Comment by kisak-valve** [comment]
Hello @atrauzzi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6349#issuecomment-1530602602.
