### ISSUE TITLE
Cannot install Microsoft Visual C++ Runtime error when launching Ground Branch and Ready or Not

### ISSUE THREAD

**Issue by sith-on-mars** [ValveSoftware/Proton#6739]
# Compatibility Report

- Name of the game with compatibility issues: [Ground Branch](https://www.protondb.com/app/16900) and [Ready or Not](https://www.protondb.com/app/1144200)
- Steam AppID of the game: 16900 and 1144200

## System Information

- GPU: Intel® UHD Graphics 630 (CFL GT2) (iGPU) and NVIDIA GeForce GTX 1050 Ti  (dGPU). I use Nvidia dGPU for playing Steam games.
- Driver/LLVM version: Nvidia-525
- Kernel version: Linux 6.2.12-1-default
- Link to full system information report as [Gist](https://gist.github.com/): [system information](https://gist.github.com/sith-on-mars/10378d17d46aa9da39772579c2db3b3b)
- Proton version: mainly use 7, 7-GE, 8, and experimental, but also tried out many other version

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[Log for Ground Branch (Proton 8) ](https://github.com/ValveSoftware/Proton/files/11371940/steam-16900.log)
[Log for Ready or Not (Proton 8)](https://github.com/ValveSoftware/Proton/files/11373060/steam-1144200.log)

## Symptoms 

I couldn't launch both games and they gave me the error `The following components are required to run this program: Microsoft Visual C++ Runtime. Would you like to install them now?`

![image](https://user-images.githubusercontent.com/37974764/235625347-139ff68f-86a8-447a-b3e1-0cb4b04582d3.png)

I have tested both games on Proton 7, 7-GE, 8, and experimental and none of them worked. It seems for some reasons Proton wasn't able to install Microsoft Visual C++ Runtime.

Strangely enough, I was able to run Ready or Not on Proton 6 and Ground Branch on Proton 4.29. But I don't think that's an optimal solution. On ProtonDB people were able to run two games with 7, 7-GE, and experimental. I'm running Steam Flatpak and I'm not sure if it might be the reason.

I lodge the bug report of two games because both are UE4 FPS and they show the same problem.

**Comment by wijjj** [comment]
@sith-on-mars did you find a way to fix the issue? I think I am running into a similar problem under comparable conditions at the moment.

**Comment by sith-on-mars** [comment]
@wijjj someone posted the fix here: https://github.com/flathub/com.valvesoftware.Steam/issues/1074#issuecomment-1611385723. This seems to be a OpenSUSE exclusive issue.
