### ISSUE TITLE
Mafia always launches setup window

### ISSUE THREAD

**Issue by Krelyshy** [ValveSoftware/Proton#6742]
# Compatibility Report
- Name of the game with compatibility issues: Mafia
- Steam AppID of the game: 40990

## System Information
- GPU: Intel UHD graphics 620 and (launching with) Nvidia MX 150
- Driver/LLVM version: nvidia 470.161.03
- Kernel version: 5.14.21
- Link to full system information report as [Gist](https://gist.github.com/Krelyshy/ba806b8cb5d835f0a74f1ab2dd3052d0)
- Proton version: unknown (default Steam setting)

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

[steam-40990.log](https://github.com/ValveSoftware/Proton/files/11400161/steam-40990.log)

## Symptoms
Game does not start, instead, every time I select "Play Mafia", the configuration window opens.

## Reproduction
Download Mafia on Linux (maybe only on openSUSE?).

**Comment by kisak-valve** [comment]
Hello @Krelyshy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2812#issuecomment-1535199693.
