### ISSUE TITLE
Noita not launching

### ISSUE THREAD

**Issue by flan7** [ValveSoftware/Proton#6743]
# Compatibility Report
- Name of the game with compatibility issues: Noita
- Steam AppID of the game: 881100

## System Information
- GPU: AMD 6600XT
- Driver/LLVM version:  4.6 (Compatibility Profile) Mesa 23.0.3
- Kernel version: linux-6.3.1.arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): [gist](https://gist.github.com/flan7/7009bdc3a9de1973a1fdb64b4169b19f)
- Proton version: Experimental

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

[steam-881100.log](https://github.com/ValveSoftware/Proton/files/11402032/steam-881100.log)

## Symptoms 
Game does not launch, I click play and it immediately crashes.

## Reproduction

This happened on nvidia-dkms, I switched to a new AMD gpu and am still facing this issue.

**Comment by kisak-valve** [comment]
Hello @flan7, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3176#issuecomment-1535495158.
