### ISSUE TITLE
Start Wars Jedi Survivor Controller Not Detected by Game. 

### ISSUE THREAD

**Issue by sp1ne7** [ValveSoftware/Proton#6745]
# Compatibility Report
- Name of the game with compatibility issues: Star Wars Jedi Survivor
- Steam AppID of the game: 1774580

## System Information
- OS: Linux Ubuntu 22.04.2 LTS (Latest Version as of this Post)
- GPU: Nvidia GeForce 1660 Super
- Driver/LLVM version: Nividia-driver-525 (Proprietary)
- Kernel version: 5.19.0-41-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton Experimental

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

**I apologize but I was unable to generate the log file using the PROTON_LOG=1 %command% launch options. It did not go where it was supposed to and I can not find it.**

## Symptoms
Any one else having this issue? I submitted a ticket to Steam but could not get help unfortunately. Here is the breakdown of what's happening.

Expect that I have tried all these steps I am about to list on both Bluetooth and a wired USB connection.

-I have tried all 3 settings. Disable Steam Input, Enable Steam Input, and Use Default Settings. Did not work.
-I have tried doing everything through Big Picture Mode. Did not work.
-I have tried it with making sure only Playstation Controller Support is selected. Did not work.
-I also tried all these steps with different DS4 controllers. Did not work.
-Basically every method you listed just now I have tried already long before I submitted this ticket. Rebooting my computer over and over again. I have been fighting with this issue for like 3 days in a row.
-I have tested my controller on other games using Steam Proton and works just fine. Eldin Ring in this example.
-I have been browsing the internet looking for solutions as well and every thing suggested failed for me.
-Steam has no issues detecting and recognising my controller whatsoever.
-Also tried using DS4DRV (Linux version of DS4 Windows)

There is only one online suggestion I have not been able to try because I can't get it to launch because its part of the game installation and that is EA Launcher. I am under the impression that there is controller settings in there, but because I can't get into it I can't check the settings.
I tried to get into it to check the settings using the following terminal command.

STEAM_COMPAT_CLIENT_INSTALL_PATH=/usr/games/steam STEAM_COMPAT_DATA_PATH=/mnt/games/SteamLibrary/steamapps/compatdata/1774580 /home/user/.steam/debian-installation/steamapps/common/Proton\ -\ Experimental/proton run /mnt/games/SteamLibrary/steamapps/compatdata/1774580/pfx/drive_c/Program\ Files/Electronic\ Arts/EA\ Desktop/EA\ Desktop\EALauncher.exe

But this did not work to let me launch the EA App that the game is installed in so I could check those settings. So if there is settings messing with the game not detecting the controller in there I can't even check them because I can't get into it.

When the game launches and I get to the main menu the only controls the game can detect is my keyboard and mouse. I can still use the trackpad on my controller as a mouse in game like I can before launching the game but no other buttons work.

## Reproduction
See the symptoms sections for how to reproduce the issue.

**Comment by kisak-valve** [comment]
Hello @sp1ne7, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6729#issuecomment-1536903907.
