### ISSUE TITLE
F1 2021 license verification pop-up window issue

### ISSUE THREAD

**Issue by shinjitumala** [ValveSoftware/Proton#6746]
# Compatibility Report
- Name of the game with compatibility issues: F1 2021
- Steam AppID of the game: 1134570

## System Information
- GPU: NVIDIA GeForce RTX 3080
- Driver/LLVM version: Nvidia 530.41.03
- Kernel version: 6.3.1-arch1-1
- Proton version: Proton 8.0-2

## I confirm:
- [x] that I have checked whether there are updates for my system available.
- [x] that I haven't found an existing compatibility report for this game.

## Symptoms 
The game is unable to reach the license server, so it is asking me to manually enter some activation code.
However, none of the buttons on the pop up menu are properly rendered, preventing me from activating and playing the game.

## Reproduction
Attempt to start the game after a fresh install. I assume the license servers  are currently down (probably for good).

**Comment by kisak-valve** [comment]
Hello @shinjitumala, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4966#issuecomment-1536957717.
