### ISSUE TITLE
Vanguard Dear days Keyboard Crash Issue

### ISSUE THREAD

**Issue by Jameskek** [ValveSoftware/Proton#6748]
when i try to type with keyboard the game quit . i tried all proton all same
When you try to go into the search bar/change deck name, as soon as you try to type, the game crashes
Every time you try to open more than one pack, the game crashes
When want to type by keyboard, game crash.

**Comment by kisak-valve** [comment]
Hello @Jameskek, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6318#issuecomment-1537130635.
