### ISSUE TITLE
MSFS 2020 Photogrammetry does not work on Steam Deck

### ISSUE THREAD

**Issue by marcuschildress** [ValveSoftware/Proton#6749]
# Compatibility Report
- Microsoft Flight Simulator 2020
- Steam AppID of the game: 1250410

## System Information
- GPU: Steam Deck
- Stable, Beta, and Preview versions as of 5/6/2022
- Proton version: 7, 8, stable and experimental/bleeding-edge versions

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Launch Options
PROTON_USE_DXVK=1 -FastLaunch

## Symptoms
Photogrammetry does not work. Map tiles don’t appear to be pulling from (guessing) Bing API

## Reproduction
Every flight

**Comment by kisak-valve** [comment]
Hello @marcuschildress, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-1537221123.
