### ISSUE TITLE
The Witcher 3 (292030) Cannot Utilize CPU Clock Speeds

### ISSUE THREAD

**Issue by Darkbloodking00** [ValveSoftware/Proton#6752]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher 3: Wild Hunt
- Steam AppID of the game: 292030

## System Information
- GPU: AMD RX5600M
- Driver/LLVM version: Mesa-22.3.7-r1 / LLVM-16.0.1
- Kernel version: 6.3.1 Custom Kernel
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Darkbloodking00/95332958285b948ebc4a43e4cfbaccb4
- Proton version: Proton Experimental 8.0-2

## I confirm:
- [ Yes ] that I haven't found an existing compatibility report for this game.
- [ Yes ] that I have checked whether there are updates for my system available.

ProtonLog: https://gist.github.com/Darkbloodking00/96858bfe0762fccfd06921df68abb31d

## Symptoms 
The Witcher 3 gradually lowers the CPU clock speeds until it hits 400-700 MHz which lowers my performance. I tried everything from changing the CPU governor to using different Proton versions. Even manually setting clock speeds and trying different BIOS options related to CPU power didn't fix my problem. I can confirm that it's not a heating problem since other games don't have such an unusual issue, my CPU can tolerate high temps like 93C, even if it's a heating issue clocks speeds shouldn't go below 400MHz.
![witcher](https://user-images.githubusercontent.com/71722525/236783501-15aed220-ff5c-44a6-92f6-6d3f4e477147.png)

## Reproduction

1-Launch the game by any means either with DirectX11 or DirectX12 with our without launcher.
2-Set the graphics options to "LOW".
3-Continue your game or start a new one.
4-Either stay still or play the game normally a while.
5-Experience lower clocks speeds and lower performance.

## Additional Information

Putting "**WINE_CPU_TOPOLOGY=4:0,1,2,3 %command%**" in launch options somehow fixes the problem but clock speed is still not in ideal range (it's locked to 2900 MHz) and performance is low.

**Comment by zaps166** [comment]
Do you use `acpi-cpufreq` with `performance` governor?
Did you change the power profile for integrated AMD GPU to LOW (idk why, but it can affect CPU speed)?
Are you sure you're not affected by SOC power limit? Is integrated GPU used somewhere else outside a game (it shares the same power limits with CPU)?
How about other games or other software?

**Comment by kisak-valve** [comment]
Hello @Darkbloodking00, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-1538332563.

**Comment by Darkbloodking00** [comment]
> Hello @Darkbloodking00, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#607 (comment)](https://github.com/ValveSoftware/Proton/issues/607#issuecomment-1538332563).

Ok, thank you for taking your time to transfer the issue ^^

**Comment by Darkbloodking00** [comment]
> Do you use `acpi-cpufreq` with `performance` governor? Did you change the power profile for integrated AMD GPU to LOW (idk why, but it can affect CPU speed)? Are you sure you're not affected by SOC power limit? Is integrated GPU used somewhere else outside a game (it shares the same power limits with CPU)? How about other games or other software?

Hello, yes I'm using **acpi-cpufreq** with **performance**. I often use CoreCtrl to set it to HIGH, that's my default profile but even if it's not activated I get the same results in Witcher 3. My OS setup is very minimal so integrated GPU isn't used outside of the game. My laptop has the SmartShift feature which cannot be disabled without BIOS hacking but it never lowers the cpu freq to 400 MHz to allocate more power to GPU. Other softwares and games aren't effected even if are they GPU itensive. Thank you for replying.
