### ISSUE TITLE
Total War: Rome 2 (214950)

### ISSUE THREAD

**Issue by Storm-Peter** [ValveSoftware/Proton#6754]
# Compatibility Report
- Name of the game with compatibility issues: Total War: Rome 2 - Emperor Edition
- Steam AppID of the game: 214950

## System Information
- GPU: RX 590
- Driver/LLVM version: 4.6 - Mesa 22.2.5 - LLVM 15.0.6
- Kernel version: Linux 5.15.0-70-generic
- Link to full system information report as [Gist](https://gist.github.com/): [System Information](https://gist.github.com/Storm-Peter/857348199b5755458b953cadd783efaf)
- Proton Log: [steam-214950.log](https://github.com/ValveSoftware/Proton/files/11422131/steam-214950.log)
- Proton version: experimental-8.0-20230505

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Overview
The game is almost working properly, there's just a few issues that break it. The campaign map works, the battles work and there's no obviously broken features in terms of gameplay. It's just not stable enough to play.

## Symptoms
- Settings aren't saved. They reset each time the game is opened. The game defaults to Ultra graphics and things like the sounds settings revert so I don't think it's actually saving any settings. Game saves still work so the filesystem works in general.
- The game freezes during loading transitions and seems to hang but then comes through most of the time.
- The game completely freezes and breaks during some critical transitions such as after the end of a battle, losing unsaved progress.
- The game completely freezes during some turn transitions

## Reproduction
- There is perma-freezing that occurs around battles. It's not 100% guaranteed that it will happen. It doesn't seem limited to played battles either, it can happen if an autoresolve battle happens.
- There is perma-freezing that occurs during turn transitions. Sometimes you can get through many turns with no issues at all, but eventually you'll get to a turn that perma-freezes towards the end of the AI's finishing their turns. But if you then load the save and run it again, it can get through fine.
- System memory is stable and when the game perma-freezes the CPU, GPU and OS are still functioning fine. You can tab out of the game and everything else is fine so it doesn't completely break anything.
- Because none of the freezes are guaranteed or related to specific moves/saves, it seems like a runtime error rather than anything being inherently broken. Maybe some sort of proton-specific resource that gets used up until it runs out and hangs?

This is my favourite game of all time so if you need me to test anything let me know. I really want to be able to play it again.

**Comment by kisak-valve** [comment]
Hello @Storm-Peter, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/512#issuecomment-1538587794.
