### ISSUE TITLE
Apex Legends (1172470) - crash when clicking Audio tab in settings

### ISSUE THREAD

**Issue by louis6321** [ValveSoftware/Proton#6755]
# Compatibility Report
- Name of the game with compatibility issues: Apex Legends
- Steam AppID of the game: 1172470

## System Information
- GPU: NVIDIA GeForce RTX 3080
- Driver/LLVM version: nvidia-driver-530 (530.41.03-0ubuntu0.22.04.2)
- Kernel version: Linux 5.15.0-71-generic x86_64
- Link to full system information report as Gist: https://gist.github.com/louis6321/fe1466e65e4b02674c53c97720cb6cbb
- Proton version: 1683569198 experimental-bleeding-edge-8.0-42943-20230508-p929fb3-wf14272-dbef2ef-vbc01f9 (crash does not occur on 7.0-6, but does occur on anything newer)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1172470.log](https://github.com/ValveSoftware/Proton/files/11424690/steam-1172470.log)

## Symptoms 
When I open Settings in-game and click the "Audio" tab, the game crashes. This does not occur on Proton 7.0-6, only on anything newer than that.

## Reproduction

- Set Proton version to anything newer than 7.0-6.
- Launch Apex Legends.
- Proceed into the lobby.
- Press esc
- Click Settings
- Click the Audio tab

**Comment by kisak-valve** [comment]
Hello @louis6321, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1538975838.
