### ISSUE TITLE
Sea of thieves: takes only 1 keyboard input per time (1172620)

### ISSUE THREAD

**Issue by Plarpoon** [ValveSoftware/Proton#6759]
# Compatibility Report
- Name of the game with compatibility issues: Sea of Thieves
- Steam AppID of the game: 1172620

## System Information
- GPU: AMD ATI Radeon RX 7900 XTX
- Driver/LLVM version: Mesa 23.0.3
- Kernel version: 6.2.14-300.fc38.x86_64
- Link to full system information report as [Gist](https://gist.github.com/Plarpoon/760782f099ba1ff6f745d38b416137aa):
- Proton version: Experimental and 8.0-2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game. **(There is another but it's not relevant to this issue)**
- [X] that I have checked whether there are updates for my system available.

The game contains a radial menu that can be opened with several buttons, taking as example the radial menu that appears when pressing "Q", [this](https://i.imgur.com/ynZFG0N.png) is the menu in question. The menu will remain open only while you are keeping the button "Q" pressed, to open any of the submenus (like "Throwables", "More" and "Quests"), without lifting your fringer from the first button, you will have to press one of the corresponding buttons to the submenu you want to open. Issue is that none of the submenus can actually be opened.

I supposed that it could be an issue given by the game not registering multiple inputs, but such a thing was proven wrong once I used the gun. Which requires to right click for aiming and left clicking to shoot. The issue seems to be present, exclusively for keyboard buttons.

Other infos:
I am currently running Fedora 38 (GNOME), I am currently using Proton Experimental but I did try the game with Proton 8.0-2 too and had the same issues. Currently these are my launch options "gamemoderun mangohud LFX=1 ENABLE_VKBASALT=1 %command%" but I tried without it and still nothing changed.

[steam-1172620.log](https://gist.github.com/Plarpoon/187837e55e9161351d65dde7e8615516)

**Comment by Plarpoon** [comment]
Had to make a small edit to the links in order to fix them

**Comment by kisak-valve** [comment]
Hello @Plarpoon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3931#issuecomment-1540809217.
