### ISSUE TITLE
Witcher 3 on Proton Experimental is not working.

### ISSUE THREAD

**Issue by Bodyash** [ValveSoftware/Proton#6768]
# Compatibility Report
- Name of the game with compatibility issues: Witcher 3: Wild Hunt
- Steam AppID of the game: https://store.steampowered.com/app/292030/_3/

## System Information
- GPU: AMD Radeon RX 6600M (navi23, LLVM 15.0.7, DRM 3.52, 6.3.1-arch2-1)
- Driver/LLVM version: 4.6 Mesa 23.0.3
- Kernel version: 6.3.1-arch2-1
- Proton version: Experimental (8.0.2c)

## I confirm:
- [v] that I haven't found an existing compatibility report for this game.
- [v] that I have checked whether there are updates for my system available.

## Proton 8.0.2c logs:
https://gist.github.com/Bodyash/b869b1f20adc2e0c00b72934c8586607

## Symptoms 
So, I'm using "force use proton for unsupported titles" and set it to experimental. Witcher 3 is supported, but still it's defaults to Experimental. So game is not starting with this proton version, game launcher also doesn't work.
Using start params: gamemoderun mangohud %command%  --launcher-skip
Current Proton Experimental version 8.0.2c
Also tried 7.0.6 - same symptoms.

And 8.0.2 is working fine, with no performance problems or any bugs.

**Comment by kisak-valve** [comment]
Hello @Bodyash, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-1544941682.
