### ISSUE TITLE
Monster Hunter Rise 

### ISSUE THREAD

**Issue by KuraiSiruru** [ValveSoftware/Proton#6769]
# Compatibility Report
- Name of the game with compatibility issues: Monster Hunter Rise
- Steam AppID of the game: 1446780

## System Information
- GPU: RTX 3060
- Driver/LLVM version: nvidia 530.41.03
- Kernel version: 5.15.0-71-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/KuraiSiruru/aa0e7d7b99ebe6be152af6c6e3d854b5
- Proton version: 8.0-2

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

[steam-1446780.log](https://github.com/ValveSoftware/Proton/files/11465950/steam-1446780.log)

## Symptoms 
Most versions of Proton produce a black windowed screen. Proton 8.0-2 allows the game to process shaders, however it freezes on the health screen directly after.

## Reproduction
start the game

**Comment by kisak-valve** [comment]
Hello @KuraiSiruru, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5495#issuecomment-1546046487.
