### ISSUE TITLE
[Whitelist] Synonymy (342890)

### ISSUE THREAD

**Issue by KGOrphanides** [ValveSoftware/Proton#677]
Installs and runs perfectly. 
Some keyframe loss compression glitches during the tutorial video, but not enough to adversely affect its usefulness.

My system spec: https://gist.github.com/KGOrphanides/c0fe99f0d9824a8ab434907637c07400

**Comment by kisak-valve** [comment]
This game was found in the 2019-07-31 whitelist update.

If you encounter an issue with this game, please search the open issues for 342890, and report any issues encountered with this game in separate issue reports, one issue per issue report.
