### ISSUE TITLE
Blazblue Central Fiction: Game crashes when selecting a specific character

### ISSUE THREAD

**Issue by 360nocompilesegfault** [ValveSoftware/Proton#6771]
# Compatibility Report
- Name of the game with compatibility issues: Blazblue Central Fiction
- Steam AppID of the game: 586140

## System Information
- GPU:  AMD RADEON RX 6900 XT
- Driver/LLVM version: AMD AMD Radeon RX 6900 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.3.1-arch2-1)
- Kernel version: 6.3.1-arch2-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/360nocompilesegfault/2c3a3c17fadaa3cd9db71dab6342a2d7
- Proton version: 8.0-2

## I confirm:
- [ !] that I haven't found an existing compatibility report for this game.
  - This issue was technically reported in an open ticket but is completely unrelated to the issue. Furthermore no STR or logs were given along with the bug report (https://github.com/ValveSoftware/Proton/issues/1031)
- [ x] that I have checked whether there are updates for my system available.

[steam-586140.log](https://github.com/ValveSoftware/Proton/files/11469060/steam-586140.log)

## Symptoms 
The game crashes when choosing a specific character (Mai Natsume) in training/challenge mode. I have yet to try other modes but it seems to only occur when the person (on Linux) chooses her. 

When online, opponents can choose her (presumably on windows) but the person on Linux will experience a crash.

I would like to note that this seems to occur with Proton 8.0_2. Proton 7.0_6 does not have this issue (I was able to switch back to this version and see that it works fine)

## Reproduction
1. Start game
2. Select Training > Training Mode OR Practice Mode
3. Select Mai Natsume (top right of character select)
4. Game crashes

**Comment by kisak-valve** [comment]
Hello @360nocompilesegfault, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1031#issuecomment-1546642053.
