### ISSUE TITLE
No proton games will launch

### ISSUE THREAD

**Issue by MajesticWaffle** [ValveSoftware/Proton#6775]
#### Your system information

* Steam Runtime Version: 
* Distribution (e.g. Ubuntu 18.04): Arch
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): [System info](https://gist.github.com/MajesticWaffle/738dfc48468e065d3ad3bf028c655bec)
  
* Have you checked for system updates?: [Yes/No] Yes
* What compatibility tool are you using?: [None / Steam Linux Runtime / Proton 5.13+ / older Proton] Proton Newer
* If you are using Steam Linux Runtime for native Linux games: I am not
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20230405.47174			# Overall version number
pressure-vessel	0.20230405.0	scout		# pressure-vessel-bin.tar.gz
scripts	0.20230405.0			# from steam-runtime-tools
soldier	0.20230405.47174	soldier	0.20230405.47174	# soldier_platform_0.20230405.47174/

#### Please describe your issue in as much detail as possible:
Seemingly at random, maybe coinciding with a reboot or update, no steam games using proton work. All games tested were previously known to work using my hardware and packages. 
[Example log](https://gist.github.com/MajesticWaffle/4f166a8cf69b1046cc36a6e01cff35cb)
I've noticed an error that may be of note, no idea if its actually important:
495.234:0020:00d4:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
495.234:0020:00d4:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."

Steps tried:
* Reinstalling / updating all graphics drivers / libraries
* Reinstalling steam
* General system update
* Reinstalling games, proton, and steam runtimes

#### Steps for reproducing this issue:
1. Launch any game using proton

**Comment by kisak-valve** [comment]
Hello @MajesticWaffle, your feedback reads more like a Proton issue than a runtime issue, so I've transferred this issue tracker to the Proton issue tracker.

**Comment by MajesticWaffle** [comment]
Reinstalled operating system, resolved issue
