### ISSUE TITLE
Path of Exile (238960) crash

### ISSUE THREAD

**Issue by Steamvoker** [ValveSoftware/Proton#6780]
# Compatibility Report
- Name of the game with compatibility issues: Path of Exile
- Steam AppID of the game: 238960

## System Information
- GPU: RTX 4090
- Driver/LLVM version: nvidia 530.41.03
- Kernel version: 6.3.2-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/Steamvoker/f94bb4ed70abebb9860229beb45ad39a):
- Proton version: 7.0-6, 8.0-2, experimental

## I confirm:
- [:heavy_check_mark: ] that I haven't found an existing compatibility report for this game.
- [:heavy_check_mark: ] that I have checked whether there are updates for my system available.

[steam-238960.log](https://github.com/ValveSoftware/Proton/files/11494745/steam-238960.log)

## Symptoms 
Game crashes.

## Reproduction
1. Open options.
2. In the UI tab check the "Hide login email".

**Comment by kisak-valve** [comment]
Hello @Steamvoker, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/58#issuecomment-1551314827.
