### ISSUE TITLE
Far Cry 6 freeze after 20-30min (co-op)

### ISSUE THREAD

**Issue by ungutknut** [ValveSoftware/Proton#6787]
# Compatibility Report
- Name of the game with compatibility issues: Far Cry 6
- Steam AppID of the game: 2369390

## System Information
- GPU: RTX3080
- Driver/LLVM version: nvidia 520.61.05
- Kernel version: 5.15.0-72
- Link to full system information report as [Gist](https://gist.github.com/ungutknut/ed0ca8954d658ae5364469623561b519):
- Proton version: Proton-experimental (18.05.2023), GE-Proton7-41, GE-Proton8-3, Proton8.0-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Game freezes after 20-30 minutes after launch. This seems to be a known issue (memory leak caused by ubisoft connect overlay) and the recommended remedy for it is to disable the ubisoft connect overlay in the ubisoft desktop app menu. This works ok in single player mode but as soon as I join a co-op session (either via overlay or from the ubisoft desktop app) the same crashes start to happen again.

## Reproduction
1. Start Far Cry 6
2. Accept invite to co-op session
3. Play co-op for ~20min
4. See it freezing

**Comment by kisak-valve** [comment]
Hello @ungutknut, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6767#issuecomment-1554468892.
