### ISSUE TITLE
EA App for Sims 4 (considered "playable") with Proton Experimental on Steam Deck not installable

### ISSUE THREAD

**Issue by ell1e** [ValveSoftware/Proton#6788]
# Compatibility Report
- Name of the game with compatibility issues: Sims 4
- Steam AppID of the game: 1222670

## System Information
- GPU: don't know (Steam Deck 64GB with default Steam OS install)
- Driver/LLVM version: don't know (Steam Deck 64GB with default Steam OS install)
- Kernel version: don't know (Steam Deck 64GB with default Steam OS install)
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: whatever is shipped by Steam as `Proton Experimental` as of 2023-05-19

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. *I have actually, but it describes different symptoms, even though also connected to EA App and it no longer launching but it seems to be for existing installs:* https://github.com/ValveSoftware/Proton/issues/6396
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
1. Install the game via a fresh download or delete all local data via verify game cache so it throws away the proton folder
2. Launch, which triggers EA App install process
3. EA App will eventually show a big warning symbol with no text other than a "Send error report" button. After using that button, everything will quit. If you try to launch the game again afterward, it just won't launch and immediately quit.

## Reproduction
See symptoms

**Comment by kisak-valve** [comment]
Hello @ell1e, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4174#issuecomment-1554759882.
