### ISSUE TITLE
The Witcher 3: Missing sounds and voices and DX11 option doesn't work  since  4.0.3 update 

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#6796]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 292030

## System Information
- GPU: RX 6700XT
- Driver/LLVM version: Mesa 23.0.3-1
- Kernel version:  6.1.29-1-MANJARO
- Proton version: 8.0.1

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

(Proton logs compress well if needed.)-->
DX12 log
https://gist.github.com/coreybruce/1f9fd6d210ed26abc35041d26da6f179

DX11 Log
https://gist.github.com/coreybruce/54ba2168db427ceadb5f05ab1e302d81

## Symptoms 
- Sounds and voices do not work, people talking are mute and only loading video cut-scene has sound. 
- DX11 fails to start, only DX12 option works

## Reproduction

1.  Play game using DX12 and proton 8.0.1, also tested this with experimental with the same results
2.  Try and use the DX11 option and the game will fail to run.

**Comment by kisak-valve** [comment]
Hello @coreybruce, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-1561023033.

**Comment by coreybruce** [comment]
> Hello @coreybruce, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#607 (comment)](https://github.com/ValveSoftware/Proton/issues/607#issuecomment-1561023033).

Yeah the only reason I made this here isntead of the one for game title is I couldn't find it. Thanks for transferring it for me.
