### ISSUE TITLE
Geometry Dash doesn't work

### ISSUE THREAD

**Issue by rAfEkk** [ValveSoftware/Proton#6799]
The game just won't start
The game was bought officially on Steam

OS: ALT Workstation K 10.1
Proton version: Proton Experimental

**Comment by kisak-valve** [comment]
Hello @rAfEkk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5304#issuecomment-1562878949.
