### ISSUE TITLE
Proton stopped working

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#6801]
Hello,

Today Proton just stopped working, Proton: 1684333320 experimental-8.0-20230517

SteamGameId: 238960

Attached the logs for one game, Path of Exile, but it is the same log for other Proton-enabled games. I play this game daily, I don't understand what happened. IMHO the important lines :

```
1384.995:0020:00c8:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
1384.995:0020:00c8:err:winediag:nodrv_CreateWindow The explorer process failed to start.
```

and this one

```
501.320:0060:006c:trace:seh:dispatch_exception code=6ba flags=0 addr=000000007B01260E ip=000000007B01260E tid=006c
501.320:0060:006c:warn:seh:dispatch_exception unknown exception (code=6ba) raised
```

[steam-238960.log](https://github.com/ValveSoftware/Proton/files/11573032/steam-238960.log)
[steam_stats.txt](https://github.com/ValveSoftware/Proton/files/11573101/steam_stats.txt)

**Comment by JoseZancanaro** [comment]
Same here, with the game Fallout New Vegas.
Yesterday it was running smoothly, today it says it is running, but the game window does not appear.

[steam-22380.log](https://github.com/ValveSoftware/Proton/files/11580051/steam-22380.log)

**Comment by ghost** [comment]
So I tried pretty much every item on this list, it still does not work :

https://steamcommunity.com/app/221410/discussions/0/1636417404917541481/

It is insane, it just stopped between session of the same game, no system update, no folder moving. It just stopped, no logs, nothing. I'm closing it as nobody cares, rightfully so. Bye !
