### ISSUE TITLE
S.T.A.L.K.E.R.: Call of Pripyat (41700)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#6803]
# Compatibility Report
S.T.A.L.K.E.R.: Call of Pripyat 41700

## System Information
- GPU: AMD RX570
- Driver/LLVM version: system has Mesa 23.1.1, steam in flatpak reports Mesa 23.0.2 (git-4d5e73870e)
- Kernel version: 6.4.0-0.rc3.20230525git933174ae28ba.31.fc39.x86_64
- Link to full system information report:
[Gist](https://gist.github.com/Vovkiv/8bfeb0b74ad7613c3354a8ae836025a2)
- Proton version: experimental-8.0-20230525b
- [Game Log](https://gist.github.com/Vovkiv/8e43473ac0e47eb0eed542fbb0fec627)

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

## Symptoms 
In latest proton experimental, game doesn't render fonts and some other UI:
![screenshot](https://github.com/ValveSoftware/Proton/assets/54743395/c10d084f-2716-442b-b62b-a09902f77e59)
Also, buttons (where text supposed to be) can't be clicked with mouse. Only with keyboard.

In proton-8.0-2d everything works fine:
![screenshot2](https://github.com/ValveSoftware/Proton/assets/54743395/6853dc9e-a773-452f-9355-18a3d73bdf94)

Loading into game, there also several UI artifacts:
PDA looks like this:
![3](https://github.com/ValveSoftware/Proton/assets/54743395/e4502d38-97e6-4e88-8477-39344921663e)
While should like this:
![4](https://github.com/ValveSoftware/Proton/assets/54743395/35ac1e1a-002d-4057-a0bb-c18fc8d981ef)

Inventory doesn't show up at all:
![5](https://github.com/ValveSoftware/Proton/assets/54743395/ec781b02-0ad5-4a6c-bce1-94c142e9466e)
And how it should:
![6](https://github.com/ValveSoftware/Proton/assets/54743395/17bb9e79-39c0-40ee-afe3-9a5e1cac829e)

## Reproduction

1. Run game with Proton Experimental 
2. Got no fonts and broken UI

**Comment by kisak-valve** [comment]
Hello @Vovkiv, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1174#issuecomment-1565422333.
