### ISSUE TITLE
Runtime Config Options for Intel XeSS

### ISSUE THREAD

**Issue by JustinKJChen** [ValveSoftware/Proton#6806]
# Feature Request
Runtime Config Options for scaling ratio and sharpness in Intel XeSS
## I confirm:
- [v ] that I haven't found another request for this feature.
- [v ] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Runtime Config Options for scaling ratio and sharpness in Intel XeSS
## Justification [optional] 
All of game can benefit by Intel XeSS

**Comment by kisak-valve** [comment]
Hello @JustinKJChen, my understanding is that XeSS is game-bundled. Proton shouldn't do anything special with this library to get it to run. This feature request seems like it should be sent upstream to the XeSS dev(s). Maybe https://github.com/intel/xess?
