### ISSUE TITLE
Proton runs one or twice, then fails with low FPS

### ISSUE THREAD

**Issue by CSV-12** [ValveSoftware/Proton#6807]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 393380/Squad/

## System Information
- GPU:  NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2
- Driver/LLVM version:   4.6.0 NVIDIA 530.41.03
- Kernel version:  5.15.0-72-generic x86_64
- Link to full systm information report as: https://gist.github.com/CSV-12/3ad7badeb6683dc8caa0090348b5c5ba
- Proton version:  8.02 , 7.06, Hotfix etc

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms Several Proton versions runs **GREAT** (45-65fps), one or two map sessions, typ 37% - 50% kernel load, max graphics settings , then slows down to 5-10fps and kernel load drops to 6-10%, after a map change.
Logfile:
[https://drive.google.com/file/d/1I4Wgc4buGZ2EUtdtENa1SHpfRwHNW7xV/view?usp=sharing](url)

## Reproduction
Just run the game a few times.

**Comment by CSV-12** [comment]
[https://drive.google.com/file/d/1I4Wgc4buGZ2EUtdtENa1SHpfRwHNW7xV/view](url)

**Comment by kisak-valve** [comment]
Hello @CSV-12, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/938#issuecomment-1567072784.

**Comment by mikk150** [comment]
Squad needs 11GB of VRAM.. you are just running out of VRAM

**Comment by CSV-12** [comment]
@mikk150  What do you base this on?  Win10 has no issues whatsoever with 8GB VRAM.
