### ISSUE TITLE
NieR:Automata - Page fault on execute access (524220)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#681]
Yet another sudden crash, though this time there was a noticeable frame drop right before it happened. 
I'm starting to wonder if it could have something to do with my active usage of the Steam overlay...

Log: [steam-524220.log.tar.gz](https://github.com/ValveSoftware/Proton/files/2321639/steam-524220.log.tar.gz)

Proton: 3.7-4 Beta
OS: Arch Linux
CPU: FX-6100
GPU: GTX 970
GPU Driver: 396.54

**Comment by ghost** [comment]
Aaaaaand crashed, sigh. Didn't use the overlay, so the crash probably doesn't have anything to do with my obsessed use of it.
Anyways last log, as I highly doubt the content changes that much between each time.

Log: [steam-524220.log.tar.gz](https://github.com/ValveSoftware/Proton/files/2321983/steam-524220.log.tar.gz)

**Comment by aeikum** [comment]
Hey @fureloka, looks like your system's file handle limit is too low. From the log:
`eventfd: Too many open files`
See the last paragraph here and let us know if that fixes this for you: https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md

**Comment by ghost** [comment]
It sure did, thanks! 

That's what I get for going full 360 in the span of six years... Arch -> Gentoo -> Debian -> Arch. I had utterly forgotten that Arch had low default values, and it sure bit my ass.

Closing, as the page fault doesn't happen anymore with a higher system file handle limit.
