### ISSUE TITLE
Warhammer 40,000: Boltgun - Framerate drop when Controller Rumble is active

### ISSUE THREAD

**Issue by abc-mikey** [ValveSoftware/Proton#6813]
# Compatibility Report
- Warhammer 40,000: Boltgun
- 2005010

## System Information
- Ditsro: Opensuse Tumbleweed 
- GPU: AMD 7900 XTX
- Driver/LLVM version: Mesa 23.0.3-1699.350.pm.4, llvm 16.0.4-1.1
- Kernel version: 6.3.2-1-default
- [Full system report](https://gist.github.com/abc-mikey/39b096a3bb6de81c8951439a09112d17):
- Proton version: Proton Experimental
- Controller: Playstation 4 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2005010.log](https://github.com/ValveSoftware/Proton/files/11597185/steam-2005010.log)

## Symptoms 

Whenever controller rumble is active (presumably) in the game the FPS drops from the normal steady framerate (120 FPS) to a steady (20 FPS). The framerate will stay at 20 FPS as long as the melee button is held. This also happens when landing from a jump or sprinting.

## Reproduction

1. Plug in a controller (you don't need to actually be using it).
2. Start Boltgun with MANGOHUD=1
3. Hold Melee button (default RMB).
4. Watch FPS drop to 20 FPS
5. Disable Controller Rumble under Accessibility options in game
6. Hold Melee button 
7. Watch FPS remain steady at normal frame rate

**Comment by ivyl** [comment]
Hi. The game doesn't pick up DualShock 4 or DualSense for me. Do you happen to have Steam Input enabled?

With XBox One / Series controllers and DS4 over Steam Input I don't see the behavior you've described on my system (5950X + 7900 XT). The game stays at the frame cap without any problem. 

Can you try disabling all the customizations, including proton logging (including removing `user_setting.py` if you ever set that up), gamemode and mangohud and instead use `DXVK_HUD=fps,devinfo,frametimes,version` for FPS info?

If the problem still occurs `PROTON_LOG=+dinput,+xinput,+hid,+rawinput` may shed some more light.

**Comment by kisak-valve** [comment]
Hello @abc-mikey, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6795#issuecomment-1568351156.
