### ISSUE TITLE
World of Warships (552990) has stopped working

### ISSUE THREAD

**Issue by zlay3r** [ValveSoftware/Proton#6814]
# Compatibility Report
- Name of the game with compatibility issues: World of Warships
- Steam AppID of the game: 552990

## System Information
- GPU: Mesa Intel® UHD Graphics (CML GT2)
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 22.2.5
- Kernel version: 6.1.0-1006-oem
- Link to full system information report as [Gist](https://gist.github.com/):  https://gist.github.com/zlay3r/8edc34fe2fcc8b6762cb39e9855d05b2
- Proton version: 5.13-6 and no newer versions will work.

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

## Symptoms 

Game crashes every time I try to use any sort of in-game chat. Also, game stability is very bad and the game will crash at random during other times. Sometimes switching views also causes crashes. No newer versions of proton will work; either they don't open the game at all or there is serious input lag issues from the keyboard. I've seen other linux steam users report these same issues on reddit and other places that have just decided to give up on steam all together because of this. You can probably find their posts on reddit, too.

## Reproduction

Log in to the game and try to use any sort of in-game chat feature with any other user. Try opening windows from the tabs on the left side for the armory, premium shop, dockyard, news, etc. Play a battle and try to use the chat feature in the battle mode.

[steam-552990.zip](https://github.com/ValveSoftware/Proton/files/11626789/steam-552990.zip)

**Comment by kisak-valve** [comment]
Hello @zlay3r, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/333#issuecomment-1572276362.
