### ISSUE TITLE
Geometry Wars 3: Dimensions Evolved (310790)

### ISSUE THREAD

**Issue by nentibusarchitectura** [ValveSoftware/Proton#6823]
# Compatibility Report
- Name of the game with compatibility issues: Geometry Wars 3  Dimensions Evolved
- Steam AppID of the game: 310790

## System Information
- GPU: RX6600XT
- Driver/LLVM version: Mesa 23.1.1-1
- Kernel version: 6.3.5-zen1-1-zen
- Link to full system information report as [Gist]: https://gist.github.com/nentibusarchitectura/b044e96453929cd1276dd1d951836ce0
- Proton version: Any (Proton GE_Proton8_3-1 on the report, but all recent versions exhibit same behaviour including experimental)

- Gist with the full proton log: https://gist.github.com/nentibusarchitectura/8406865d7791cf340147c7ff610652cf

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms

Game does not start, used to work fine on the same computer some months ago.

## Reproduction

Just trying to launch game on latest up-to-date Arch.

**Comment by kisak-valve** [comment]
Hello @nentibusarchitectura, you linked the same gist twice instead of sharing your system information. Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. If you're using the Steam client beta, then please share the Steam Runtime Diagnostics instead.

`info:    Device : Null hardware (RADV NAVI10)` in your Proton log makes me suspect that AMDVLK is interfering with mesa/RADV.

**Comment by nentibusarchitectura** [comment]
>> Hello @nentibusarchitectura, you linked the same gist twice instead of sharing your system information

Apologies for the snafu with the gist, I've updated it on the main comment.

>> in your Proton log makes me suspect that AMDVLK is interfering with mesa/RADV.

Strange to the best of my knowledge that computer shouldn't have AMDVLK installed...

I'll check that right away.

**Comment by kisak-valve** [comment]
https://gist.github.com/nentibusarchitectura/b044e96453929cd1276dd1d951836ce0#file-desktop-txt-L730-L740 Is a strong hint that lib32-amdvlk is installed, and 32 bit Vulkan is broken in general on your system. (https://gist.github.com/nentibusarchitectura/b044e96453929cd1276dd1d951836ce0#file-desktop-txt-L180-L197)

**Comment by nentibusarchitectura** [comment]
Thank you getting rid of pesky AMDVLK fixes it! spot on.

Somehow I had this intruder on my box:

```
pacman -Q | grep -i amd
lib32-amdvlk 2023.Q2.2-1
```

Hmm I didn't install it, how did it come to be?

Well:

```
pacman -Qi lib32-amdvlk
Name            : lib32-amdvlk
Version         : 2023.Q2.2-1
Description     : AMD's standalone Vulkan driver
Architecture    : x86_64
URL             : https://github.com/GPUOpen-Drivers
Licenses        : MIT
Groups          : None
Provides        : lib32-vulkan-driver
Depends On      : lib32-zstd
Optional Deps   : None
Required By     : steam
Optional For    : lib32-vulkan-icd-loader
Conflicts With  : None
Replaces        : None
Installed Size  : 89.48 MiB
Packager        : Laurent Carlier <lordheavym@archlinux.org>
Build Date      : Tue 23 May 2023 12:23:24 BST
Install Date    : Tue 23 May 2023 20:49:16 BST
**Install Reason  : Installed as a dependency for another package** ???????
Install Script  : No
Validated By    : Signature
```

```
pacman -Sii lib32-amdvlk
Repository      : multilib
Name            : lib32-amdvlk
Version         : 2023.Q2.2-1
Description     : AMD's standalone Vulkan driver
Architecture    : x86_64
URL             : https://github.com/GPUOpen-Drivers
Licenses        : MIT
Groups          : None
Provides        : lib32-vulkan-driver
Depends On      : lib32-zstd
Optional Deps   : None
**Required By     : steam  steam-native-runtime** <<<<< oh, well, that explains it.
Optional For    : lib32-vulkan-icd-loader
Conflicts With  : None
Replaces        : None
Download Size   : 22.47 MiB
Installed Size  : 89.48 MiB
Packager        : Laurent Carlier <lordheavym@archlinux.org>
Build Date      : Tue 23 May 2023 12:23:24 BST
MD5 Sum         : b1337f0ecac254ad057a895cbc813d94
SHA-256 Sum     : 0ce7312c4be7a8d5f9d8557e489fac5a3307b9ca219149f0b545b216316322e0
Signatures      : 06096A6AD1CEDDAC

```

It never crossed my mind that AMDLVK could be installed on this box as I installed everything manually and never installed AMDVLK manually.

However there is something that still intrigues me, if I have this exported:

`VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json"`

How comes Proton is picking AMDVLK?

And only for this game alone?

**Comment by nentibusarchitectura** [comment]
Ok, if any passer-by reads this post hope this will help.

In Arch since 2021.Q3.4 for `VK_ICD_FILENAMES` to work as the default Vulkan driver `AMD_VULKAN_ICD=RADV` also has to be set to switch from the AMDVLK default, alternatively `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1` can be set too.

So adding these to the `/etc/environment` file: (and rebooting)

```
AMD_VULKAN_ICD=RADV
VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
```

Will guarante that RADV is the default.

The reason for only having "Geometry Wars 3" Crash with AMDVLK is because I had only part of the 32bit vulkan libraries installed as part of a dependency, "Geometry Wars 3" is 32bit so Vulkan was defaulting to it and making the came crash.

Any other Windows game I have been running lately is 64 bit hence why I had not noticed this issue as on 64 bit I did not have any AMDVLK components installed.

**Comment by nentibusarchitectura** [comment]
Closing as solved.
