### ISSUE TITLE
Doom 2016 379720 performance issues on Vulkan

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#6827]
# Compatibility Report
- Name of the game with compatibility issues: Doom 2016
- Steam AppID of the game: 379720

## System Information
- CPU: AMD Ryzen™ 7 5700G with Radeon™ Graphics × 16
-  Ram: 32GB
- GPU: RX 6700XT
- Driver/LLVM version: Mesa 23.0.3-1
- Kernel version: 6.1.31-2-MANJARO
- Proton version: 8.02

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

 https://gist.github.com/coreybruce/e4eb6372c7a756a8f5563e6d7429fd5d

## Symptoms 
Performance under vulkan is significantly lower than it is with OpenGL 4.5

This is the settings I use for both Vulkan and OpenGL
![Screenshot from 2023-06-06 15-22-54](https://github.com/ValveSoftware/Proton/assets/8393780/36e87d9f-58c4-4a5e-99e6-4adf3c2057dd)

Vulkan:
![Screenshot from 2023-06-06 15-21-43](https://github.com/ValveSoftware/Proton/assets/8393780/509d0132-4024-44c6-a636-368ae3abdd2b)

OpenGL:
![Screenshot from 2023-06-06 15-22-44](https://github.com/ValveSoftware/Proton/assets/8393780/103d806b-0cc1-43bb-b14b-bf529c968987)

## Reproduction
Switch the Graphics API from OpenGL 4.5 to Vulkan

**Comment by mbriar** [comment]
Can you enable the full performance overlay of the game? I think it's pretty likely that the game runs on the integrated Vega GPU instead of the 6700XT when using vulkan? Do you set DRI_PRIME somewhere?

**Comment by coreybruce** [comment]
> Can you enable the full performance overlay of the game? I think it's pretty likely that the game runs on the integrated Vega GPU instead of the 6700XT when using vulkan? Do you set DRI_PRIME somewhere?

Oh ok I'll set it and take a look also no I haven't set DRI_PRIME anywhere

**Comment by coreybruce** [comment]
> Can you enable the full performance overlay of the game? I think it's pretty likely that the game runs on the integrated Vega GPU instead of the 6700XT when using vulkan? Do you set DRI_PRIME somewhere?

Hmm it seems to be using my RX 6700XT 

![image](https://github.com/ValveSoftware/Proton/assets/8393780/7be8f2fd-85cb-42b3-a5d9-44c0d8bf781c)

**Comment by mbriar** [comment]
Weird. I have the same GPU and the game runs at the 200 fps cap at max settings on vulkan.

**Comment by coreybruce** [comment]
> Weird. I have the same GPU and the game runs at the 200 fps cap at max settings on vulkan.

Hmm that's odd and what CPU and desktop do you have?

**Comment by kisak-valve** [comment]
Hello @coreybruce, this issue should also be mentioned to your video driver vendor if it hasn't been already.

**Comment by coreybruce** [comment]
> Hello @coreybruce, this issue should also be mentioned to your video driver vendor if it hasn't been already.

Like the distro or who makes the driver because I'm using the open source mesa driver

**Comment by core1983** [comment]
I have similar config to @coreybruce and on latest proton and there are frequently fps fdrop from 200fps to 38-45. When i run game with proton ge issue disappear.

**Comment by coreybruce** [comment]
> I have similar config to @coreybruce and on latest proton and there are frequently fps fdrop from 200fps to 38-45. When i run game with proton ge issue disappear.

Use OpenGL 4.5, the performance is fine when you use that

**Comment by Leopard1907** [comment]
I can't repro the issue here, Mesa 23.1.1, Proton 8.0-2.

Vulkan:

![Screenshot_20230609_140705](https://github.com/ValveSoftware/Proton/assets/24878978/6e547937-2075-47f3-915b-81473c79417f)

OpenGL:

![Screenshot_20230609_140812](https://github.com/ValveSoftware/Proton/assets/24878978/7bbcbff5-edf0-4d98-b598-4f5fdda18f84)

**Comment by coreybruce** [comment]
Seems to be fixed now
