### ISSUE TITLE
[Manjaro Linux] After update any games cant launch. Only invisible window with game sound

### ISSUE THREAD

**Issue by antonTroyan** [ValveSoftware/Proton#6830]
Proton 8.0-2
Apex Legends, Dying Light 2 etc.
Have never problem to run any of this games on this configuration. But after some updates 2 week ago issued the problems.
Steam launch game window, I can hear open sounds, but window is empty. And no errors
![image](https://github.com/ValveSoftware/Proton/assets/32644076/bde493d3-82cf-444d-a40d-ec512274ff41)
![image](https://github.com/ValveSoftware/Proton/assets/32644076/0bda9516-acdd-463f-80a5-4cae89b382ba)

**Comment by antonTroyan** [comment]
I reinstall steam and games. But no effect

**Comment by kisak-valve** [comment]
Hello @antonTroyan, this reads like #6760. Closing as a duplicate.
