### ISSUE TITLE
Problem with validation Doom Eternal on Ubuntu Linux 22.04.2 LTS (Jammy Jellyfish) 64-bit

### ISSUE THREAD

**Issue by grabarz666pg** [ValveSoftware/Proton#6833]
Hi.
I bought Doom Eternal on Steam. After about 7 hours of gameplay, the game stopped launching and the following message popped up:

> support.codefusion.technology/de_d90127jd781/?e=88500006&l=polish

which takes me to the page:

https://support.codefusion.technology/de_d90127jd781/?e=88500006&l=polish

I will add that I have not changed anything in the game or system options. I am running Ubuntu Linux 22.04.2 LTS (Jammy Jellyfish) 64-bit, with kernel 6.3.0-060300-generic x86_64, and graphics: AMD Radeon Vega 8 Graphics (raven, LLVM 15.0.7, DRM 3.52, 6.3.0-060300-generic).
I do not have this problem with Doom (2016).
I will be grateful for any hint.

Paweł,
Poland

**Comment by kisak-valve** [comment]
Hello @grabarz666pg, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3773#issuecomment-1582494114.
