### ISSUE TITLE
Proton 8.0-3 Release Candidate Testing

### ISSUE THREAD

**Issue by ivyl** [ValveSoftware/Proton#6834]
Hey all.

We've put together a new 8.0 Release Candidate build for you to test.

In the Steam client the Proton 8.0 app should have a release-candidate beta branch (look for Proton 8.0 in your Steam Library, right click -> Properties... -> BETAS) which you can choose to start testing the 8.0-3 Release Candidates (note that the name of the build in the Steam Settings dialog will not be updated). I will post changes here when we push new builds. The source for the latest RC build is available on the [proton_8.0-rc](https://github.com/ValveSoftware/Proton/tree/proton_8.0-rc) branch in this repository. This branch may be force pushed.

We are interested only in issues that are new to the 8.0-3 RC builds. If you believe that something broke please confirm that the problem does not occur with the none branch before reporting it here.

The changelog is tentative - it has not yet been verified by our QA staff, and can change before the final release as we add or remove features during RC testing.

- Previosly playable only with Proton Experimental:
  - Propnight
  - Combat Mission: Battle for Normandy
  - Bloodrayne Terminal Cut 1/2
  - Breakout 13
  - Murasaki Tsurugi
  - PooShooter: Toilet Invaders
  - Purgo Box
  - Olympia Rising
  - Summoners War: Chronicles
  - Tom Clancy's Ghost Recon Breakpoint
  - Minecraft Legends
  - STRANGER OF PARADISE FINAL FANTASY ORIGIN
  - Gunfire: Reborn
  - Super Bomberman R
- Newly playable: StreetStep: 21st Century Basketball.
- Fixed Call of Duty 2 hanging when loading maps.
- Fixed Creativerse hanging while exiting from a local game.
- Fixed Ubisoft Connect intermittently having an invisible window.
- Fixed a few Proton 8.0 regressions:
  - DJMAX RESPECT V is playable again.
  - Halo: The Master Chief Collection menus no longer are broken.
  - BeamNG.drive no longer crashes when a steering wheel is connected.
  - Cafe Stella no longer crashes with 2 elements on the flowchart.
  - Marvel’s Spider-Man Remastered no longer ignores controller input.
  - Indiana Jones and The Emperor no longer crashes on the splash screen.
  - Grand Theft Auto V no longer freezes on keyboard input.
  - TRAHA Global no longer crashes at end of second cutscene.
  - Intro video for Age of Empires II: Definitive Edition no longer crashes.
- Fixed scroll bar in Final Fantasy XIV Online launcher.
- Fixed Last Labyrinth displaying only a black screen on the Steam Deck.
- Fixed Creativerse not being able to connect to a local game with a VPN connection active.
- Fixed The Incredible Adventures of Van Helsing not rendering text in Polish correctly.
- Fixed game looking dark and improved performance with Nosferatu: The Wrath of Malachi.
- Fixed DXVK HUD not showing the correct git revision used.
- Improved video playback in Roboquest.
- Improved rendering of units in Total War: MEDIEVAL II – Definitive Edition.
- Fixed various memory leaks during video playback that were affecting Street Fighter 6.
- Enabled nvapi for many more games: Chernobylite Enhanced Edition, Dead Space (Remake), Forspoken, Forza Horizon 5, Hi-Fi Rush, Marvel's Avengers, Monster Hunter Rise, Need For Speed Unbound, Nioh 2, Propnight, Redfall, Returnal, Sackboy: A Big Adventure, SCP: 5K, Scum, The Last Of Us Part I, Watch Dogs Legion.
- Fixed Tales of Berseria suffering from screen tearing with vsync turned on while in fullscreen / borderless.
- Improved Final Fantasy XIII loading times.
- Fixed EA launcher crashing.
- Fixed Red Dead Redemption 2 taking long time to exit with Alt+F4.
- Fixed Battle.net not starting.
- Fixed multiple Unity titles flickering on the Steam Deck when switching display window options.
- Fixed The Elder Scrolls Online wrongly claiming not enough space.
- Fixed The Elder Scrolls Online launcher showing blank window.
- Fixed Madballs in Babo: Invasion claiming the game wasn't purchased.
- Fixed PlanetSide 2 launcher.
- Fixed various Wo Long: Fallen Dynasty issues around video playback.
- Fixed video playback in Nioh: Complete Edition.
- Fixed Pentiment not being playable on desktop.
- Fixed Grounded not being playable on desktop.
- Improved cutscene desync in Immortals Fenyx Rising.
- Fixed Witcher 3 launcher rendering issues.
- Fixed Call of Duty: Black Ops III graphical glitches when loading Hex Tower.
- Fixed video playback speed issues in METAL GEAR SOLID V: THE PHANTOM PAIN.
- Fixed Deus Ex: Human Revolution Director's Cut hanging on exit.
- Fixed connection error at the end of Chapter 2 in Life is Strange Remastered.
- Fixed EOS error message with Returnal and other EOS games.
- Fixed rendering issues in Uru: Complete Chronicles on Steam Deck.
- Fixed Richman: Classic not starting in OpenGL mode.
- Fixed No Man's Sky VR mode not working after a game update.
- Updated dxvk to v2.2-34-g4d254b13.
- Updated dxvk-nvapi to v0.6.3-4-g2483eac.
- Updated vkd3d-proton to v2.9-21-gf52e6482.

**Comment by ranplayer** [comment]
Hi there,

I've found a regression with this RC related to FSYNC in **Lara Croft and The Temple of Osiris**:  stuttering and weird frame timing. In the **Southern Cliffs level** the stuttering is so hard that makes the game unplayable. If you disable FSYNC (`PROTON_NO_FSYNC`), the game works normally. This issue is **not happening with Proton 8.0-2**.

Log file: 
[steam-289690.tar.gz](https://github.com/ValveSoftware/Proton/files/11854102/steam-289690.tar.gz)

Specs:
OS: Arch
Kernel: 6.1.35
GPU: RX 6700 XT (Mesa 23.1.2)
CPU: Ryzen 7 5700 G
Display server: X11

Game specs:
- All maxed out (1080p)

**Comment by alasky17** [comment]
@ranplayer Thank you for reporting this!  Would you mind uploading a save file for the Southern Cliffs level so that it is easier for us to investigate this?

Could you also get a log with PROTON_LOG=+fsync %command%?

**Comment by ranplayer** [comment]
Hi @alasky17 , I can upload the save and get the new logs next week (I'm not at home these days). I believe you are able to see the stuttering and weird frame timing also in the open map.

**Comment by alasky17** [comment]
@ranplayer Unfortunately I've been unable to reproduce any stuttering with the map -- I'm assuming you just meant the static map that you can open in the menu, next to the adventure log etc?  

When you are able to retest - could you also please try experimental-8.0 to see if the issue persists there? 

Also - were you using any program in particular to investigate the frame timing? I tried using mangohud and for some reason the overlay didn't show up for this game.

**Comment by ranplayer** [comment]
@alasky17 I meant the main open area where you can enter the levels (sorry for the wrong terminology). I've been using mangohud to check the frame timing, but I had the same issue as you. To solve it I had to recompile the mangohud package (I've been using the AUR's). When I get back home I'll test the latest experimental as well.

**Comment by alasky17** [comment]
@ranplayer Unfortunately I am not familiar with this game and so I'm not sure how to get to that open area.  I got past the first tutorial area, hoping that I would get into the open area after that, but it just took me to the next part of the map which seems to be called "shrine of osiris"(?) with no open area that sounds like what you described.  I guess maybe I'll just have to wait for you to get back to get a save file :)

**Comment by simifor** [comment]
I can reproduce the tomb raider issue, it actually appears since the gameplay starts so it takes no time to verify it. With 8.0-3 the game has constant stutters, with 8.0-2 it's locked to 60 fps. 
![Lara Croft and the Temple of Osiris 2023-06-29_18:54:21](https://github.com/ValveSoftware/Proton/assets/70454800/6bd1d5de-21a8-4649-ab9e-6e47f9aed16e)
[steam-289690.zip](https://github.com/ValveSoftware/Proton/files/11911029/steam-2
89690.zip) here is the log with `PROTON_LOG=+fsync %command%`
My [specs](https://gist.github.com/simifor/a1e596372d0d4746ceca7e686b44d5dc) like ranplayer, I have a zen 3 cpu (5600G)

Edit: Also tested proton 7 and GE proton 8-4. The problem isn't present in proton 7 but it is present in GE proton as well

**Comment by alasky17** [comment]
@simifor @ranplayer Good news - I was finally able to repro locally with another machine.  We are on the case and hoping to fix this for the final 8.0-3 build.  Thank you for testing the release candidate and reporting here :)

**Comment by alasky17** [comment]
@simifor @ranplayer This should be fixed in experimental-bleeding-edge.  If you have time to test and help confirm since this seems fairly hardware specific, that would be greatly appreciated :)

**Comment by ranplayer** [comment]
@alasky17 I've tested it against the latest experimental bleeding edge and it's working fine now. Thank you for digging into this issue (:

**Comment by simifor** [comment]
Experimental is working better than 8.0-3, but still worse than older versions @alasky17 

Experimental  ![Lara Croft and the Temple of Osiris 2023-07-04_18:10:54](https://github.com/ValveSoftware/Proton/assets/70454800/16f063d6-6148-4039-b028-480214884eab)

8.0-3 ![Lara Croft and the Temple of Osiris 2023-07-04_18:14:07](https://github.com/ValveSoftware/Proton/assets/70454800/7985049e-bee4-4853-9604-3a5759083a48)

7.0-6 ![Lara Croft and the Temple of Osiris 2023-07-04_18:23:42](https://github.com/ValveSoftware/Proton/assets/70454800/8f79353e-a768-4da7-90e8-2c792d15b3f4)

**Comment by alasky17** [comment]
@simifor I tried comparing 7.0-6, 8.0-2 and experimental-bleeding-edge, and they all behaved very similarly to me. I noticed that the very first time I went to a new area, there would be more blips in the mangohud frametime tracker, but I did not see a significant difference when I compared the same area and kept flipping back and forth between builds.  I am hoping that the difference you saw was only because you tested experimental first.

8.0-2 vs experimental-bleeding-edge is a better point of comparison because 7.0-6 is quite different.  If you are still seeing a difference between 8.0-2 and experimental-bleeding-edge, could you try disabling fsync on experimental to confirm if what you are seeing is still a fsync regression?

**Comment by ranplayer** [comment]
@simifor you have to change the **Experimental** branch to "bleeding edge" (via Properties -> Betas -> Beta Participation)

**Comment by VladimirMrzv** [comment]
In games with Original/EA client not working steam overlay. Only showing from Original/EA, and when got achievement it take focus on it and not in game.
Tested on Proton 7 / 8 / Experimental

**Comment by kisak-valve** [comment]
Hello @VladimirMrzv, that's a preexisting issue being tracked at #4009. It's not relevant here because this issue report is specifically for catching any new issues between Proton 8.0-2 and the 8.0-3 release candidate.

**Comment by simifor** [comment]
@ranplayer yeah, I was already on bleeding edge.
@alasky17 I don't see the same continuous spike, but moving around the map and during the cutscene (which had already played in a previous session), but there are still some weird spikes on Be even after reentering the same area
![Lara Croft and the Temple of Osiris 2023-07-05_16:37:53](https://github.com/ValveSoftware/Proton/assets/70454800/2a0965e9-709a-4159-b20c-7b27601198cc)
![Lara Croft and the Temple of Osiris 2023-07-05_16:40:00](https://github.com/ValveSoftware/Proton/assets/70454800/e10b835f-ca15-44cc-8051-e3303ec33a35)

on 8.0-2 there was only a single spike the moment the cutscene stared, but no spikes throughout or when moving around
![Lara Croft and the Temple of Osiris 2023-07-05_16:49:48](https://github.com/ValveSoftware/Proton/assets/70454800/ef86f537-48f8-4832-b334-6f04abd504ec)

BE with FSYNC disabled behaves like 8.0-2, no weird spikes while moving around
![Lara Croft and the Temple of Osiris 2023-07-05_16:55:09](https://github.com/ValveSoftware/Proton/assets/70454800/0eacdbf8-f01e-478e-b1ea-982b35538efa)

---

I need to specify the BE screenshots were "cherrypicked", those spikes weren't constant, but they could trigger while moving around the map (less often after they triggered once in a certain part of the map, but they didn't happen at all with 8.0-2 and with FSYNC disabled)

**Comment by alasky17** [comment]
@simifor I am still not seeing the spikes as I keep playing through the game.  There are a couple of things that could potentially help us investigate this, but I understand if the asks are too big:
1) Could you try using the stock kernel instead of tkg to eliminate a potential factor?
2) Could you confirm if the spikes still happen in the tutorial?  I think this might wipe your progress though, and I've had no luck with transferring saves, so be aware if you do this, a backup save file might not work :(

**Comment by simifor** [comment]
@alasky17 didn't retest tutorial area but I don't see the spikes anymore when using stock 6.4.1

**Comment by alasky17** [comment]
@simifor Thank you for checking that!  Greatly appreciated to help solve the mystery :)

**Comment by ZeroYamaoka** [comment]
Well nice that DJ Max Respect is playable but did ustable frame rate isuee gonna be fixed ?
[https://youtu.be/rtX2S6v3kiw](url) here is example of problem and its on new 8.0-3

**Comment by ivyl** [comment]
There's work on the DJ Max Respect happening in upstream. It was shortly in experimental but had to be reverted due to regressions it caused in other places. We'll bring it back once it's all sorted out.

**Comment by ivyl** [comment]
Closing since 8.0-3 was just released. Please report problems with any games in their respective issue threads. Thanks!
