### ISSUE TITLE
Our Life: Beginnings & Always (1129190)

### ISSUE THREAD

**Issue by Shadowalker125** [ValveSoftware/Proton#6835]
# Compatibility Report
- Our Life: Beginnings & Always 
- 1129190

## System Information
- Steam Deck
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[log.txt](https://github.com/ValveSoftware/Proton/files/11702277/log.txt)

## Symptoms 

When starting a new game, you are prompted to enter a name. The onscreen keyboard pops up and you can type in a first name, but there is no way to switch to the next text field. More importantly, its impossible to close the keyboard. If you attempt to close the keyboard, it immediately re-opens. Its even difficult to close the game. Steam+B doesn't work, and the steam overlay is very un-responsive.

## Reproduction

1. Open game
2. select New File
3. Attempt to enter name
4. keyboard remains open and cant be closed, unable to progress and difficult to close game

NOTE: The game works better in desktop mode, but then the keyboard doesn't open at all, but at least you can progress past that screen.

**Comment by kisak-valve** [comment]
Hello @Shadowalker125, `File "/home/deck/.local/share/Steam/steamapps/common/Our Life Beginnings And Always/lib/py2-linux-x86_64/../../OurLife.py",` in your log is from the linux native variant of RenPy running this game, and Proton is not involved. Feedback on the Linux native variant of games should be sent directly to the game's dev(s).

Closing as out-of-scope for the Proton project.
