### ISSUE TITLE
Sound distortions on Devil May Cry HD Collection

### ISSUE THREAD

**Issue by ardishko** [ValveSoftware/Proton#6837]
# Compatibility Report
- Name of the game with compatibility issues:
Devil May Cry HD Collection
- Steam AppID of the game:
631510
## System Information
- GPU AMD Radeon 6900 XT
- Driver/LLVM version: Mesa 23.1.1-1
- Kernel version: Linux Arch 6.3.6
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ardishco-the-great/ee53981803700f28a433d969a24c1d2f
- Proton version: Proton Experimental (DD/MM/YYYY: 09/06/2023)

ALSO TESTED WITH A STEAM DECK, BOTH YIELD THE SAME RESULTS

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

I have attached a video demonstrating the sound distortions on the Steam Deck and a logfile below. 

## Symptoms 

In cutscenes, sound distortions can be observed. Other than that, the game is functionally fine.

## Reproduction

1. Open DMCHD
2. Boot up DMC3
3. While the opening cutscene plays, sound distortions will be able to be observed. It is worth noting that the distortions are not random and are at the exact same points both on my desktop and my Steam Deck.

[steam-631510.log](https://github.com/ValveSoftware/Proton/files/11706632/steam-631510.log) (from my desktop)
Video of sound distortions: https://youtu.be/HpY-N9HyZvU

**Comment by kisak-valve** [comment]
Hello @ardishco-the-great, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4059#issuecomment-1584609545.
