### ISSUE TITLE
Apex Legends [Unkown file version (paks/Win64/pc_all.opt.starpack)

### ISSUE THREAD

**Issue by Cubuss** [ValveSoftware/Proton#6838]
# Compatibility Report
- Name of the game with compatibility issues: Apex Legends 
- Steam AppID of the game: 1172470

## System Information
- GPU: RTX 3080
- Driver/LLVM version: Nvidia 525
- Kernel version: 6.3.5-201.fsync.fc38.x86
- Link to full system information report as https://gist.github.com/Cubuss/76d14115589bbe7200c84f59c0348a8d
- Proton version: Tried experimental, 8.0, 8.2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms When i launch the game and just wait i get "Unknown file version (paks/Win64/pc_all.opt.starpak)

![image](https://github.com/ValveSoftware/Proton/assets/9220880/34719a94-7ed3-4cbc-8bb5-3e598dc604ee)

## Reproduction
Just start the game and wait does'nt mather what you do 

<!--
[steam-1172470.log](https://github.com/ValveSoftware/Proton/files/11708778/steam-1172470.log)

**Comment by kisak-valve** [comment]
Hello @Cubuss, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1584932145.
