### ISSUE TITLE
Last proton experimental broke Deep Rock Galactic

### ISSUE THREAD

**Issue by Alexandre-Fernandez** [ValveSoftware/Proton#6841]
# Compatibility Report
- Name of the game with compatibility issues: Deep Rock Galactic

## System Information
- GPU: RTX 3090
- Driver/LLVM version:r nvidia 525
- Link to full system information report as [Gist](https://gist.github.com/): ubuntu
- Proton version: last

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

## Symptoms 

Game can't go past the start screen.
Visual glitches can be seen on the start screen.

---

I changed the proton version to 8.0.2 and it works again.

**Comment by kisak-valve** [comment]
Hello @Alexandre-Fernandez, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/284#issuecomment-1586182801.
