### ISSUE TITLE
Doom Eternal - Steam Proton - Keyboard layout - Can't find dash

### ISSUE THREAD

**Issue by DenverJoeJohnson** [ValveSoftware/Proton#6843]
APP ID = 782330
Linux - Ubuntu v20.04
GPU1 = Quadro Pro P5000
GPU2= Quadro Pro P5000
NVida Driver = 530.41.03

When playing Steam - Doom Eternal - I need to jump a large gap.   I am only using a keyboard and mouse.  Per the video helper guides I need to jump then dash.  However I dont have a keyboard mapping for dash.  

Any help would be greatly appreciated.  

Thanks
Joe

**Comment by kisak-valve** [comment]
Hello @DenverJoeJohnson, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3773#issuecomment-1588207715.

**Comment by DenverJoeJohnson** [comment]
Hi @kisak-valve not sure what this link is showing me other than use updated drivers.  Can you please be more specfic on how to change the controller keyboard layout
