### ISSUE TITLE
Keyboard/Mouse input seemingly not working for various games under Proton Experimental (Bleeding-Edge).

### ISSUE THREAD

**Issue by kzdixon** [ValveSoftware/Proton#6845]
Proton Versions: **Proton Experimental (Bleeding-Edge)** as of 2023-06-13
System Info Gist: https://gist.github.com/kzdixon/3120d40e30660a654db274904a5ffeee
Basic System Info:
- OS: Gentoo Linux x86_64
  - gcc 13.1.1_p20230527
  - llvm 16.0.5/15.0.7-r3
- Kernel: 6.3.4-zen to 6.3.7-zen tested
- CPU: AMD Ryzen 9 7950X3D
- GPU: AMD Radeon 7900 XTX
- Memory: 64GB

Certain games under Proton seemingly are ignoring all keyboard/mouse input. This happens regardless of whether or not the Steam Overlay is enabled. This also occurs whether using either Native or Runtime versions of Steam for some games but not all.

Games Affected (of what I have installed):
- **Noita** (broken on Proton Experimental (Bleeding-Edge))
  - Sees Mouse position but does not respond to any clicks or key presses.
- **Muse Dash** (_was_ broken on Proton Experimental (Bleeding-Edge) but apparently that's the only one of the three working now on Experimental after retesting version swaps...?)
  - Cannot get to Main Menu by pressing any keys or clicking.
- **Baldur's Gate 3** (broken on Proton Experimental (Bleeding-Edge))
  - Reads first button press to get to Main Menu but then only sees Mouse position and does not respond to clicks or keyboard presses afterwards.

It seems to only be affecting a small number of games out of the ~50 I have installed currently, but is quite annoying nonetheless. This is also a fairly recent issue as I was testing Baldur's Gate 3 specifically just last week after purchasing it and was able to navigate menus fine. I have also been able to play Noita and Muse Dash in the past just fine as well. Wrapping these games in Gamescope does not seem to help.

Have rebuilt all ebuilds from the older `@steam` list as well as current `@esteam` results.

Based on retesting Proton version swaps and having Muse Dash suddenly work on Experimental again (after deleting the compatdata dir for the game), this could just be an intermittent regression belonging to just the current Experimental (Bleeding-Edge) build.

Hope to bring attention to it at least so it doesn't propagate down into the more stable versions!

**Comment by ghost** [comment]
i can confirm i have a similar problem on arch linux playing metro 2033 redux

**Comment by kzdixon** [comment]
> i can confirm i have a similar problem on arch linux playing metro 2033 redux

Upon testing, Metro 2033 Redux's native version seems to work fine. The menus under Proton Experimental (Bleeding-Edge) (as of 2023-06-14) seem to also be working fine for me.

Testing one of the games from my prior list shows that Noita is still not working on Proton Experimental (Bleeding-Edge) however. Noita specifically seems to not be taking any Mouse clicks as inputs but is accepting keyboard input. Tested with a fresh prefix.

**Comment by DenverJoeJohnson** [comment]
I have issues with Doom Eternal, not able to use keyboard command DASH.  Help please

**Comment by kzdixon** [comment]
The issues I had with mouse/keybourd input on Noita, Baldur's Gate 3, and Muse Dash on Proton Experimental (Bleeding-Edge) seem to have been resolved.

**Comment by DenverJoeJohnson** [comment]
@kzdixon how do I fix this?

**Comment by kzdixon** [comment]
> @kzdixon how do I fix this?

I haven't tried Doom Eternal;
The three games I had issues with seem fine now after Proton Experimental (Bleeding-Edge) had been updated sometime yesterday. If you're on that branch of Proton Experimental and still experiencing the issue I can try to confirm on my end later.

**Comment by Edward-Martinson** [comment]
Same thing happens to me in Noita, also I have an issue with the fps speed. It looks like is a old problem..

**Comment by dogw4t3r** [comment]
Has this been resolved?

**Comment by DenverJoeJohnson** [comment]
I just abandoned the game and requested a refund.

**Comment by xperttheef4** [comment]
same issue proton exp works with other proton versions just not exp but beam ng also needs proton exp wont run right on older proton versions note keyboard/controller both are unresponsive im on pop os also it was working fine beforee also im on Wayland/COSMIC helllllllpppppp meeeeeeeeee

**Comment by Hressa** [comment]
For anyone who finds this issue looking for a solution: I've had this problem with Severed Steel and State of Decay 2 on CachyOS Wayland (Niri). In both cases, switching to Proton 8.0-5 fixes the problem.
