### ISSUE TITLE
Different evaluation on Titanfall

### ISSUE THREAD

**Issue by Plarpoon** [ValveSoftware/Proton#6847]
Hello, I have currently downloaded and installed "Titanfall" (Steam ID: 1454890). I have noticed that when launching the game the EA App launches successfully, it does the login and even shows me the game library on it. Unfortunately at the moment it boots the game nothing appears on screen and shorty after it closes down on me.

I have written an issue already for this but then I realized that I don't know really for a fact if this is an issue present only with my configuration or it's more common. Would anyone that still has it downloaded please be able to tell me if the game boots up fine after the new EA App came to on Steam or if you also can't even launch the game?

Thank you in advance for your time, if the error is only mine I will be able to more accurately describe the issue when updating it, but if it's more generalized I would like to pinpoint which part of the process did it all go to fail.

**Comment by kisak-valve** [comment]
Hello @Plarpoon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4410#issuecomment-1586400051.
