### ISSUE TITLE
Pavlov VR Update 29

### ISSUE THREAD

**Issue by Maxb0tbeep** [ValveSoftware/Proton#6848]
# Compatibility Report
- Name of the game with compatibility issues: Pavlov VR
- Steam AppID of the game: 555160

## System Information
- GPU: RX 6700 XT
- Driver/LLVM version: Mesa 23.1.2
- Kernel version: 6.3.7-arch1-1

- Link to full system information report as [Pastebin](https://pastebin.com/YwkFCrfb)
- Proton version: Experimental, 8.0, 7.0, GE-7-55, GE-8-4

## I confirm:
- [yes] that I haven't found an existing compatibility report for this game.
- [yes] that I have checked whether there are updates for my system available.

[steam-555160.log](https://github.com/ValveSoftware/Proton/files/11750328/steam-555160.log)

## Symptoms 
Since the new update 29 was released, EAC shows this error when I launch the game:
![this](https://github.com/ValveSoftware/Proton/assets/55332100/95dbbe99-2cad-4759-8416-c3cb32abbc06)

## Reproduction
Open the game with the new update.

**Comment by kisak-valve** [comment]
Hello @Maxb0tbeep, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3012#issuecomment-1591959574.
