### ISSUE TITLE
Satisfactory crash with recent update to unreal engine 

### ISSUE THREAD

**Issue by jitoxx** [ValveSoftware/Proton#6849]
# Compatibility Report
- Name of the game with compatibility issues: Satisfactory
- Steam AppID of the game:526870

## System Information
- GPU:  Amd Radeon RX 6700 XT
- Driver/LLVM version:  Mesa 23.1.2
- Kernel version:  Debian 6.3.7-1
- Link to full system information report as [Gist](https://gist.github.com/): I use Debian unstable and have update my system recently
- Proton version: Proton 8

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Reproduction

--> Download Satisfactory experimental latest version and start it with Proton 8. 
[steam-526870.log](https://github.com/ValveSoftware/Proton/files/11757846/steam-526870.log)

**Comment by kisak-valve** [comment]
Hello @jitoxx, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3957#issuecomment-1593071520.

**Comment by AkechiShiro** [comment]
#3957 is closed and no longer tracking this issue however I am encountering this issue currently, could this one be reopened @kisak-valve ?
