### ISSUE TITLE
Downwell (360740)

### ISSUE THREAD

**Issue by edn9** [ValveSoftware/Proton#685]
Arch Linux
Kernel 4.18.3
Proton 3.7
bspwm 0.9.5
CPU Intel Core i3-2350m @ 4x 2.3GHz
RAM 4gb
GPU Intel(R) HD Graphics 3000

Game close after 15 seconds, not working.

https://store.steampowered.com/app/360740/Downwell/

**Comment by edn9** [comment]
Game working with beta.

**Comment by pnaf** [comment]
Game runs flawlessly with DualShock 4 controller support.

Compatibility tool: Proton 3.7-3

[System Information](https://gist.github.com/pnaf/aa15f6687874738a6192199c46b8a2c3)

@necronoise: Does the game still not work after switching to the Proton version mentioned above?

**Comment by pnaf** [comment]
# Whitelist Request
- Name of the game to be whitelisted: Downwell
- Steam AppID of the game: 360740

## System Information
- GPU: RX 480
- Driver/LLVM version: Mesa 18.1.7/6.0.1
- Kernel version: 4.17
- Link to full system information report as [Gist](https://gist.github.com/):
https://gist.github.com/pnaf/ff505353a40d3021af50589ab9ab1d49
- Proton version: 3.7-3

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

**Comment by pnaf** [comment]
@kisak-valve: Game is now working for both of us. Would you be fine with converting this issue into a whitelist request?

**Comment by ghost** [comment]
I still have the 15 seconds bug

**Comment by kisak-valve** [comment]
Hello @Utopanic, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, what version of Proton did you test with?

**Comment by ghost** [comment]
https://gist.github.com/Utopanic/106a4807d0c0079057a9b85c06634e06#file-utopanic-s-system
I tried it on every release of proton until 3.16.3.
By the way, thanks for the amazing works you guys are putting in proton ^^

**Comment by Cthuflu** [comment]
I ran the game with `PROTON_LOG=1 %command%` to find the following messages
```
8698.776:0028:0032:trace:module:LdrShutdownThread ()
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7a820000 L"opengl32.dll",THREAD_DETACH,(nil)) - CALL
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7a820000,THREAD_DETACH,(nil)) - RETURN 1
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x2b10000 L"steam.dll",THREAD_DETACH,(nil)) - CALL
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x2b10000,THREAD_DETACH,(nil)) - RETURN 1
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x3b400000 L"steam_api.dll",THREAD_DETACH,(nil)) - CALL
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x3b400000,THREAD_DETACH,(nil)) - RETURN 1
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7de00000 L"ole32.dll",THREAD_DETACH,(nil)) - CALL
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7de00000,THREAD_DETACH,(nil)) - RETURN 1
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7dd70000 L"rpcrt4.dll",THREAD_DETACH,(nil)) - CALL
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7dd70000,THREAD_DETACH,(nil)) - RETURN 1
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7e060000 L"msvcrt.dll",THREAD_DETACH,(nil)) - CALL
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7e060000,THREAD_DETACH,(nil)) - RETURN 1
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7ef80000 L"wininet.dll",THREAD_DETACH,(nil)) - CALL
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7ef80000,THREAD_DETACH,(nil)) - RETURN 1
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7e110000 L"ws2_32.dll",THREAD_DETACH,(nil)) - CALL
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7e110000,THREAD_DETACH,(nil)) - RETURN 1
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7db10000 L"imm32.dll",THREAD_DETACH,(nil)) - CALL
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7db10000,THREAD_DETACH,(nil)) - RETURN 1
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7ed40000 L"user32.dll",THREAD_DETACH,(nil)) - CALL
8698.776:0028:0032:trace:module:MODULE_InitDLL (0x7ed40000,THREAD_DETACH,(nil)) - RETURN 1
8698.794:0028:0029:trace:module:GetModuleFileNameW L"C:\\users\\steamuser\\Temp\\IXP000.TMP\\Downwell_v1_0_5.exe"
8698.795:0028:0029:trace:module:GetModuleFileNameW L"C:\\users\\steamuser\\Temp\\IXP000.TMP\\Downwell_v1_0_5.exe"
8698.795:0028:0029:trace:module:GetModuleFileNameW L"C:\\users\\steamuser\\Temp\\IXP000.TMP\\Downwell_v1_0_5.exe"
8698.795:0028:0029:trace:module:GetModuleFileNameW L"C:\\users\\steamuser\\Temp\\IXP000.TMP\\Downwell_v1_0_5.exe"
8698.819:0028:002b:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
8698.819:0028:002b:err:d3d:wined3d_debug_callback 0x213660: "GL_INVALID_OPERATION in glVertexAttribPointer(non-VBO array)".
...
//  [[[1000000 GL_INVALID_OPERATION errors]]]
...
8762.537:0028:002b:err:d3d:wined3d_debug_callback 0x213660: "GL_INVALID_OPERATION in glVertexAttribPointer(non-VBO array)".
8762.537:0028:002b:err:d3d:wined3d_debug_callback 0x213660: "GL_INVALID_OPERATION in glVertexAttribPointer(non-VBO array)".
eventfd: Too many open files
Protocol error: process 0028: sendmsg: Bad file descriptor
```

The game will run with the following launch options, which disables eventfd:

`PROTON_NO_ESYNC=1 %command%`

Post-disabling eventfd the message 
`d3d:wined3d_debug_callback 0x2134b0: "GL_INVALID_OPERATION in glVertexAttribPointer(non-VBO array)".`
still spams the log, but the game now seems to run without crashing.

[Here is my system information](https://gist.github.com/Cthuflu/1eb7cdeaeda4b1b7a30cf9ecf4550058)

**Comment by kisak-valve** [comment]
Hello @Cthuflu, please run [`ulimit -Hn`](https://github.com/ValveSoftware/Proton/wiki/Requirements#fd-limit-requirements) and verify that it is a high value and not 4096.

**Comment by Cthuflu** [comment]
@kisak-valve I ran the command you requested

```
$ ulimit -Hn
4096
```

**Comment by kisak-valve** [comment]
You'll want to raise that limit to about a million. There's some info on how to do that at https://github.com/zfigura/wine/blob/esync/README.esync.

**Comment by Cthuflu** [comment]
Raising that limit does work well enough to still be able to use esync.

I was able to run the game as normal in proton.

**Comment by Zero86Sk** [comment]
Game Works as intended.

[my steam specs](https://gist.github.com/Zero86Sk/849961ad66438e3e6240198d06fbce5c)

**Comment by ghost** [comment]
The game  now doesn't boot on my computer anymore
EDIT: I also tried PROTON_NO_ESYNC=1 %command%, but it didn't help

**Comment by ghost** [comment]
[steam-360740.log](https://github.com/ValveSoftware/Proton/files/2569204/steam-360740.log)

**Comment by Plagman** [comment]
There's a known regression where Proton 3.16 Beta causes Downwell and other games to crash on RadeonSI. Using 3.7 should still work.

**Comment by ghost** [comment]
Ok, any idea on how to fix the "after 15 seconds crash" bug?

**Comment by kisak-valve** [comment]
This game was found in the 2019-07-31 whitelist update.

If you encounter an issue with this game, please search the open issues for 360740, and report any issues encountered with this game in separate issue reports, one issue per issue report.
