### ISSUE TITLE
Cyberpunk 2077 (1091500) freezes on intro with the Proton experimental bleeding-edge 2023-06-15

### ISSUE THREAD

**Issue by Faalagorn** [ValveSoftware/Proton#6850]
Seems like Cyberpunk 2077 freezes continuously when playing the intro videos with the latest Proton-experimental bleeding-edge. Music plays, but the game become unresponsive. It can be killed. It worked with the bleeding-edge yesterday and downgrading to regular Proton experimental fixed the issue for me.

I launch the game with `--launcher-skip -skipStartScreen` parameters.

I didn't test any other games with that Proton version.

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 23.1.2/15.0.7
- Kernel version: 6.3.8-zen1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Faalagorn/065141e9978d0d5ffa734ac1178c21a3
- Proton version: Proton experimental bleeding-edge 2023-06-15

**Comment by kisak-valve** [comment]
Hello @Faalagorn, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1593659916.
