### ISSUE TITLE
Proton 8.0: DirectX missing or driver initialization failed

### ISSUE THREAD

**Issue by Almtesh** [ValveSoftware/Proton#6855]
Hello,

I have a Linux Steam client on Debian 11 with a Sapphire AMD Radeon RX 6700. I'm using backports kernel and firmwares to be able to run it. Seems good since Proton 7.0 work on it.

Proton 7.0 is still available, so I can still use games that support it, but I wanted to play Trackmania and Ubisoft Connect is unable to start on Proton 7.0 (and probably World of Warship and Marvel's Spider-Man Remastered). The error I get when I try to start a game with Proton 8.0 is something like unable to initialize graphic driver or about missing DirectX 10 or 11.

I don't know what to provide for more information, so felle free to ask, I can test things too.

Regards,
Almtesh

**Comment by mbriar** [comment]
Proton 8 requires a vulkan driver that supports vulkan 1.3, Debian 11's drivers are too old.

**Comment by kisak-valve** [comment]
Hello @Almtesh, as @mbriar noted, Proton 8.0 and newer requires Vulkan 1.3 for the builds of DXVK and VKD3D-Proton in it. This is provided by mesa 22.0 or newer.

It looks like Debian Bullseye provides mesa 20.3.5, which isn't going to work. Update your system if you want to use Proton 8.0 and newer.
