### ISSUE TITLE
Unity Input System: Start/Select Button swapped in low-level mapping

### ISSUE THREAD

**Issue by raybun** [ValveSoftware/Proton#6861]
**Expected Behaviour:** All controller buttons map correctly in Unity projects
**Observed Behaviour:** Using the current "new Unity Input System", the Start/Select buttons are swapped in mapping.

- Building the [Visualizers Sample](https://github.com/Unity-Technologies/InputSystem/tree/develop/Assets/Samples/Visualizers) shows that all the buttons map correctly in a native linux build of the Unity input tester app.
- The same project as a windows build, however, reveals that Start/Select are swapped, while all other buttons are reported correctly in the Unity input tester app.
- The problem affects the internal controller, as well as an Xbox One gamepad connected via bluetooth

Affects: Proton Experimental, Proton 8.0-2, Proton 7.0-6, possibly more
OS: SteamOS Beta 3.4.8 June 15th, Controller FW Nov 21, BIOS F7A0110

**Comment by raybun** [comment]
Windows Build of Input Tester Sample App from "Visualizers" package
[InputTester.zip](https://github.com/ValveSoftware/Proton/files/11781253/InputTester.zip)

Linux Build of Input Tester Sample App from "Visualizers" package
[InputTesterLinux.zip](https://github.com/ValveSoftware/Proton/files/11781257/InputTesterLinux.zip)

**Comment by raybun** [comment]
Link to Unity Issue:
https://issuetracker.unity3d.com/issues/linux-new-input-system-select-and-start-buttons-are-switched-when-running-the-build-with-proton

**Comment by rbernon** [comment]
Thanks for the report and sorry for the delay. I pushed a fix for this in which should be in the bleeding edge branch of  Proton Experimental. It will be in the next Proton Experimental release and I will make sure it lands into future stable releases as well.

**Comment by Francoimora** [comment]
Is there any ETA on this to be live for all Steam Deck users ? We will release a demo of our game next month for Steam Next Fest, do you think we have to handle this problem on our side or not ?

**Comment by rbernon** [comment]
This is planned for release in the upcoming Proton 8.0-5, which should hopefully be out in a matter of days (hopefully, though I can't give any guarantee but won't be too long).

**Comment by raybun** [comment]
It's out, woohoo!
