### ISSUE TITLE
Ubisoft Connect no longer works with Proton 7.0 or 8.0

### ISSUE THREAD

**Issue by bertogg** [ValveSoftware/Proton#6862]
Ubisoft recenty updated the UbisoftConnect program and it no longer works with Proton 7.0-6e or 8.0. The reason is the missing implementation of the `DiscardVirtualMemory` API:

```
steam-runtime-launch-client[47028]: Unhandled exception: unimplemented function KERNEL32.dll.DiscardVirtualMemory called in 32-bit code (0x7bc624c0).
steam-runtime-launch-client[47020]: 00000404 UplayWebCore.exe
```

This problem can be reproduced with Ubisoft Connect 142.1.10881 and it seems related to Ubisoft stopping support for older versions of Windows:

https://www.ubisoft.com/en-au/help/connectivity-and-performance/article/ubisoft-connect-pc-compatibility-with-windows-7/000102431

It can be reproduced by simply [downloading Ubisoft Connect](https://ubisoftconnect.com/en-US/) and installing it. After the installation is finished make sure that the "Launch Ubisoft Connect now" checkbox is enabled.

This was already fixed in Wine and it works fine with Proton Experimental:

https://github.com/ValveSoftware/wine/commit/551de225a0d834f73382c7f6fcb3ca9a5d7e7c5e

**Comment by sbritorodr** [comment]
I think this is happening to me as well. When I try to open AC Odyssey steam stays on "initializating" and doesn't execute the game "it doesn't show in green". Sometimes after deleting pfx, restarting steam and sigterm all "wine" processes it launches but the ubisoft connect crashes. However, proton experimental doesn't seem to work for me.

Don't know if it's the same problem.

**Comment by al12gamer** [comment]
While my reply here may not be helpful with the original releases of Proton, have you tried Proton-GE builds? An easy way to test them is to install Protonup-QT with `flatpak install pupgui2` and then open the app to install the most recent GE build. Is Ubisoft Connect still having issues then?
The only game that uses Ubisoft Connect that I play is The Division 2, and as of last week using both Proton 8.0.1 and the most recent Proton-GE build, it opens fine and runs fine.

**Comment by sbritorodr** [comment]
Hello, I forgot this post. Solved it by installing the flatpak version instead. It seems using my package manager is not a good option.

**Comment by isatsam** [comment]
I found this issue on Reddit while troubleshooting Warframe. DiscardVirtualMemory problem also affects Warframe (and probably some other games), which fails to launch, but the Play button in Steam library stays green for a second, during which WF throws this kind of error in journalctl several times:
`plasmashell[8088]: wine: Call from 00000001700621D8 to unimplemented function KERNEL32.dll.DiscardVirtualMemory, aborting`
I was also able to solve this by forcing Proton Experimental as the compatibility tool.

**Comment by ipr** [comment]
Works now on Proton 8.0-3.

**Comment by Xenonobi** [comment]
Hello everyone,

i thought i make myself an Account here to participate in this Bug reporting.
If i'm doing anything wrong please guide me what to do, but for now i can't confirm what the
Member ipr has said here,

https://github.com/ValveSoftware/Proton/issues/6862#issuecomment-1649355355

and i have described everything on the Steam Forum already.

https://steamcommunity.com/app/375910/discussions/0/3806154368652639338/

It doesn't matter if i'm using Proton Version 7, 8 or Experimental, the Ubisoft Launcher will not start the
second time, and even it is installed it will be not recognized from the Game Anno2205.

I'm on Ubuntu 22.04 with the proprietary Nvidia Driver 525.125.06 (not the Open Kernel version).

Like i said this is my first Bug report ever, so i hope i have done it correct.

**Comment by ipr** [comment]
> It doesn't matter if i'm using Proton Version 7, 8 or Experimental, the Ubisoft Launcher will not start the second time, and even it is installed it will be not recognized from the Game Anno2205.

Some games have older version of Uplay which seems to have some bug. In those cases it has helped to install Uplay manually instead of letting Steam install script handle it. I'm not certain what the cause is but it might be just some parameters.

It works in Anno 2205 for me, maybe you need a clean Proton prefix?

**Comment by Xenonobi** [comment]
Thanks for your response ipr but this is far from my Knowledge and Tech Level with Proton in Steam :(

You said,

> Some games have older version of Uplay

and to not get you wrong, but if you have seen my Comments on the Steam Forum, i downloaded the
Ubisoft Connect Software from the Ubisoft Website, so i don't know where to get an even more
recent Version from it.

Also please clarify "how to install Uplay manually" instead of letting Steam install script handle it,
and also how to get a "clean Proton prefix"?

Do you mean install Ubisoft Connect with PlayOnLinux for example? or directly with Wine?
by using the latest Repository from the Wine Website?

I'm sorry but like i said, i never dived deeper into Proton so if you have some further advice or just some
useful Links to a dedicated HowTo or Documentation for me, this would be very much appreciated.

**Comment by ipr** [comment]
> > Some games have older version of Uplay
> 
> and to not get you wrong, but if you have seen my Comments on the Steam Forum, i downloaded the Ubisoft Connect Software from the Ubisoft Website, so i don't know where to get an even more recent Version from it.

Some older Ubisoft games try to install old version of Uplay when they are first launched. I am guessing that isn't your problem in this case.

However, if you downloaded and installed it separately, there is the problem that games with Proton run with different prefixes, like a virtual drive for an analogy. This means that if you install Uplay under different prefix the game won't see it.

> Also please clarify "how to install Uplay manually" instead of letting Steam install script handle it, and also how to get a "clean Proton prefix"?

By manual I meant with command line with Proton or Wine directly. But let's put that aside for now..

> Do you mean install Ubisoft Connect with PlayOnLinux for example? or directly with Wine? by using the latest Repository from the Wine Website?
> 
> I'm sorry but like i said, i never dived deeper into Proton so if you have some further advice or just some useful Links to a dedicated HowTo or Documentation for me, this would be very much appreciated.

By far the easiest way to get a clean install is to uninstall from Steam, then install again, but that means plenty to download. 
Other method is to delete the prefix from ...Steam/steamapps/compatdata/appid where appid is the id number of the game, the start the game again from Steam.

Starting the game from Steam with Proton should install Uplay correctly. If you get an error you are likely using older version of Proton (not 8.0-3 which has a crucial fix). In this case, go to game properties in Steam client, select the "force compatibility.." and select Proton 8.0-3, then start the game from Steam.

**Comment by Xenonobi** [comment]
Here is what i was doing after some research and in addition to your last comment,

>Other method is to delete the prefix from ...Steam/steamapps/compatdata/appid where appid is the id
>number of the game, the start the game again from Steam.

>Starting the game from Steam with Proton should install Uplay correctly.
>If you get an error you are likely using older version of Proton (not 8.0-3 which has a crucial fix).
>In this case, go to game properties in Steam client, select the "force compatibility.." and select
>Proton 8.0-3, then start the game from Steam.

step by step with the expected result.

I have removed the the Game on July 23 already after my last Comment on the Steam Forum.
In the Steam Client i went to my Library, and i clicked on the Drop Down Menu, underneath Start page
to select Tools and deselect Games.
I scrolled down to all the installed Proton entries, to do a right click on them to selected uninstall,
and to remove them all.
I closed Steam and i visited the two following Locations in my File manager,
to delete all remaining Folders with the Name Proton in it on this location,

`~/.steam/debian-installation/steamapps/common/`

and deleted one remained Folder with a random Number (appid you mentioned before) on this location.

`~/.steam/steam/steamapps/compatdata/`

I started Steam and went to Steam -> Settings -> Compatibility to select

"Activate Steam Play for supported titles" and "Activate Steam Play for all other titles"

and i selected Proton Version 8.03 and proceeded the forced restart from Steam.

Back in the Client i downloaded Anno2205 again but before i started it, i made a right click on the Game
to choose under Compatibility Proton Version 8.03 and also under General to use the Custom Launch option

`PYTHONIOENCODING=utf-8 DXVK_STATE_CACHE=0 %command%`

like it was described here.

https://www.protondb.com/app/375910#FOajF3BDRw

I started the Game ... Vulkan Shader are being processed was visible in a small Steam own Window,
and a couple of seconds later i received this error Message,

`Unable to detect Uplay Installation. Please make sure Uplay is installed.`

like i described it on the Steam Forum already.

https://steamcommunity.com/app/375910/discussions/0/3806154368652639338/#c3808407347825227097

Removing the Custom Launch option under the General Tab brings up the same Error Message after started the Game.

**Comment by ipr** [comment]
> 
> I have removed the the Game on July 23 already after my last Comment on the Steam Forum. In the Steam Client i went to my Library, and i clicked on the Drop Down Menu, underneath Start page to select Tools and deselect Games. I scrolled down to all the installed Proton entries, to do a right click on them to selected uninstall, and to remove them all. I closed Steam and i visited the two following Locations in my File manager, to delete all remaining Folders with the Name Proton in it on this location,

It isn't necessary to uninstall Proton. That does not affect the prefix which is installed per game.

> 
> `PYTHONIOENCODING=utf-8 DXVK_STATE_CACHE=0 %command%`
> 
> like it was described here.
> 
> https://www.protondb.com/app/375910#FOajF3BDRw
> 

That is for very old Proton, it isn't necessary with current version.

> I started the Game ... Vulkan Shader are being processed was visible in a small Steam own Window, and a couple of seconds later i received this error Message,
> 
> `Unable to detect Uplay Installation. Please make sure Uplay is installed.`
> 

Can you instead run game with PROTON_LOG=1 %command% in and upload the resulting log file. This isn't going to progress otherwise.

**Comment by Xenonobi** [comment]
After my last Comment yesterday i closed Steam to left the situation with Anno behind me for the rest of the day.

Seen your Comment today i started the Game with Proton Version 8.0-3 still selected including your
recommended Command and Steam was showing the following Error Message.

`Compatibility Tool failed`

I switched back to Proton Version 7.0-6 and Anno seemed to start including your recommended Command,
but this time there was something different again, and i can't tell why ...
[steam-375910.log](https://github.com/ValveSoftware/Proton/files/12214824/steam-375910.log)

The Ubisoft Connect Launcher showed up, it was downloading some updates for it and once that was done
the Ubisoft Window was becoming Transparent.

The green Game entry on the left was showing that the Game was still running and a few seconds later
the Shadows of the Ubisoft Window disappeared and the Game stopped working again.

Here is the Logfile you have asked for ... i hope it helps.

**Comment by fishd72** [comment]
Seems like todays Ubisoft Connect update has (yet again) broken launching on Linux.

Watch_Dogs was working for me last night... today it updated the Ubisoft Connect launcher and now it freezes with the only the outline of the Ubisoft Connect splash screen visible. I tried with both Proton 8.0-3 and Experimental... I've also tried GE-Proton8-9 (which it was working flawlessly with) and none work anymore.

**Comment by puppet-head** [comment]
Yep the update has killed it for all proton versions.  Ubisoft launcher-log.txt shows
ERROR CefClientHandler.cpp (1051) CEF render process crashed.

loops the same error continually.

**Comment by i-r-t** [comment]
The same, just black screen after Ubisoft update on Steam Deck, Assassin's Creed: Origins.

**Comment by ipr** [comment]
Interesting.. Running new Uplay with plain Wine results in errors:
vkd3d:fixme:hlsl_yylex Unsupported preprocessor #pragma directive at line 9.
05a0:err:d3dcompiler:D3DCompile2 Failed to compile shader, vkd3d result -4.
05a0:err:d3dcompiler:D3DCompile2 Shader log:
05a0:err:d3dcompiler:D3DCompile2     C:\fakepath:42:52: E5000: syntax error, unexpected '(', expecting ';' or ','
05a0:err:d3dcompiler:D3DCompile2 

That would indicate Uplay has a bug in the shader, or the shader compiler has a bug. In the latter case, I think Mesa recently fixed some case with some characters in shader comments? If so, Mesa update could fix that..

**Comment by Akselmo** [comment]
Got the same error when trying to play Watch_Dogs 2. Tired of these broken launchers.

**Comment by fishd72** [comment]
After notification from someone on the GE Proton discord I switched Proton Experimental over to Bleeding Edge (using the Beta settings for Proton Experimental within Steam) and now my Ubisoft games are playable again.

**Comment by i-r-t** [comment]
Proton Experimental have been just updated (through Steam), now Ubisoft Connect Launcher runs fine.

**Comment by Xenonobi** [comment]
I can confirm it, and after visiting the Arch Wiki to fix some things on my end,

https://wiki.archlinux.org/title/Steam/Troubleshooting#Steam:_Compatibility_tool_configuration_failed

the Game is working now finally by using Proton experimental.

Thank you very much! for fixing it once more ♥

**Comment by Xenonobi** [comment]
Today the Game doesn't start again on my Machine any more.
If i click on the Play Button in Steam i'm getting again that specific error Message.

`Unable to detect Uplay Installation. Please make sure Uplay is installed.`

Here is one more Log File, i hope it helps once more.

[steam-375910.log](https://github.com/ValveSoftware/Proton/files/12294026/steam-375910.log)

**Comment by 1e1000000** [comment]
Win8.1 doesn't work, loading TM2020 nothing happens.
![image](https://github.com/ValveSoftware/Proton/assets/54700438/0f19732f-e945-4834-833d-503766c255c2)

**Comment by tuxtergames** [comment]
After a few days trying its running the division 2 here i got it, I need to exclude compatdata folder, set proton 6.3.8, it will leave to install uplay, it will hang installation trying to update the client, wait a few time then close and change to proton experimental, I'm using bleeding edge here, but looks like its better to use without it, don't forget to disable overlay

![image](https://github.com/ValveSoftware/Proton/assets/26095484/0883ed57-3b44-4d2c-b166-e027b06d0c70)

**Comment by simifor** [comment]
Starting with a fresh prefix for https://store.steampowered.com/app/2225070/Trackmania/ I saw the following:
With proton 8.0-3 the Ubisoft connect window appeared and downloaded some updates, but after it said the client would restart, the window turned transparent and I couldn't proceed into the game, closing and opening the game just lead to the transparent ubisoft connect (this time from the start).

Switching to proton experimental (I didn't clear the prefix) **worked**, it made the client visible again, ubisoft connect asked for my login credentials, and after that I was able to start and play the game normally.

**Comment by jpVm5jYYRE1VIKL** [comment]
In my case Ubisoft Connect start but cannot connect due to it i cannot start game and i spend whole money back cool down period fighting with ubisoft stupid launcher. Go offline also does not work . Any idea how to pass laucher. The most interesting that hacked copy of game start without any issue. 

![ksnip_20230919-140833](https://github.com/ValveSoftware/Proton/assets/22169129/87679a04-d5b1-49e6-a9c5-ad3368843584)
![ksnip_20230919-140959](https://github.com/ValveSoftware/Proton/assets/22169129/c69a0181-806c-4288-aa0e-5d5adef77458)


laucher generate log : 
```

348674.564:0230:02a4:trace:seh:NtGetContextThread 0xfffffffe: eax=000000a3 ebx=00000065 ecx=00000000 edx=00000000 esi=040cfcb4 edi=0000016c
348674.564:0230:02a4:trace:seh:NtGetContextThread 0xfffffffe: ebp=040cfc48 esp=040cfbdc eip=7bc0c1ac cs=0023 ss=002b flags=00000297
348674.564:0230:02a4:trace:seh:NtGetContextThread 0xfffffffe: ds=002b es=002b fs=0063 gs=006b
348674.570:0230:02a4:trace:seh:NtGetContextThread 0xfffffffe: eax=000000a3 ebx=00000064 ecx=00000000 edx=00000000 esi=040cfcb4 edi=0000016c
348674.570:0230:02a4:trace:seh:NtGetContextThread 0xfffffffe: ebp=040cfc48 esp=040cfbdc eip=7bc0c1ac cs=0023 ss=002b flags=00000297
348674.570:0230:02a4:trace:seh:NtGetContextThread 0xfffffffe: ds=002b es=002b fs=0063 gs=006b
348674.570:0164:01c0:trace:seh:NtGetContextThread 0xfffffffe: eax=000000a3 ebx=ffffffff ecx=00000000 edx=00000000 esi=1506fcb4 edi=000002bc
348674.571:0164:01c0:trace:seh:NtGetContextThread 0xfffffffe: ebp=1506fc48 esp=1506fbdc eip=7bc0c1ac cs=0023 ss=002b flags=00000246
348674.571:0164:01c0:trace:seh:NtGetContextThread 0xfffffffe: ds=002b es=002b fs=0063 gs=006b
```

**Comment by agurenko** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6862#issuecomment-1725392394

I used to work around this problem by setting mtu probing with `sudo sysctl net.ipv4.tcp_mtu_probing=1`

**Comment by jpVm5jYYRE1VIKL** [comment]
> > Replying to [#6862 (comment)](https://github.com/ValveSoftware/Proton/issues/6862#issuecomment-1725392394)
> 
> I used to work around this problem by setting mtu probing with `sudo sysctl net.ipv4.tcp_mtu_probing=1`

Thanks. Worked like a charm.

**Comment by kisak-valve** [comment]
Closing as fixed in Proton 8.0-4.

**Comment by bertogg** [comment]
Thanks, I confirm that it works fine with Proton 8.0-4

**Comment by Milor123** [comment]
I get this problem in the game `For Honor`

in the UAC log always show this
```
[2024.04.10-16.17.26] Loader initialized.
[2024.04.10-16.17.26] [Connection] Connecting to URL: https://download.eac-cdn.com/api/v1/games/104/client/wine64/download/?uuid=0f7ad1d3-1d3d-9f0f-e2b6-804753aa1a7f
[2024.04.10-16.17.26] Progreso de la descarga: 0%.
[2024.04.10-16.17.26] Progreso de la descarga: 0%.
[2024.04.10-16.17.26] [Connection] Connect result: No error (0) Response Code: 200 Destination IP: 3.163.49.86
[2024.04.10-16.17.26] Código de respuesta HTTP: 200 Código Curl: 0
[2024.04.10-16.17.26] Falling back to a secondary CDN path.
[2024.04.10-16.17.26] [Connection] Connecting to URL: https://download-alt.easyanticheat.net/api/v1/games/104/client/wine64/download/?uuid=9acb4e35-a61f-46d9-1efd-1fc62a414ead
[2024.04.10-16.17.26] Progreso de la descarga: 0%.
[2024.04.10-16.17.26] Progreso de la descarga: 0%.
[2024.04.10-16.17.27] [Connection] Connect result: No error (0) Response Code: 200 Destination IP: 104.18.2.180
[2024.04.10-16.17.27] Código de respuesta HTTP: 200 Código Curl: 0
[2024.04.10-16.17.27] [EAC Callback] Code 915. Message: 'Código de respuesta HTTP: 200 Código Curl: 0'.
```

I've tried `sudo sysctl net.ipv4.tcp_mtu_probing=1` , disable manghud, set manually the UAC files from steam

But nothings works, Try with all the proton versions possibles, from 8.0 to 9-1 
can someone help me please?
