### ISSUE TITLE
Mortal Kombat X cutscenes with audio crackling and then low fps

### ISSUE THREAD

**Issue by paparoxo360** [ValveSoftware/Proton#6863]
The game is running pretty well, without any issues at consistent 60fps, but at the start of the first cutscene (when Sub-Zero appears on the helicopter), the audio begins to crackle, and the game slows down significantly, to resolve this issue I have to restart the game.

I've tried ProtonGE, proton experimental and proton 6.3.8, and nothing, I saw online that other people had the same problem, and it's weird because normally proton works very well, do you have any suggestions or solutions? Thank you in advance.

Proton Experimental

GPU: RX550

OS: Ubuntu Mate 22.04

Kernel: 5.19.0-43-generic

Driver: Mesa 23.0.4 - kisak-mesa PPA

**Comment by kisak-valve** [comment]
Hello @paparoxo360, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/513#issuecomment-1597212675.
