### ISSUE TITLE
Circuit Superstars (1097130)

### ISSUE THREAD

**Issue by Mershl** [ValveSoftware/Proton#6870]
# Compatibility Report
- Name of the game with compatibility issues: Circuit Superstars
- Steam AppID of the game: 1097130

## System Information
- GPU: RX7900 XTX
- Driver/LLVM version: mesa 23.1.1
- Kernel version: 6.3.8
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Mershl/faace49cd42084a4423df6a0648cef3a
- Proton version: tested on clean prefix each: 7.0-6, 8.0-2, Proton Experimental

Proton Log: [steam-1097130.zip](https://github.com/ValveSoftware/Proton/files/11853856/steam-1097130.zip)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms

Game crashes on startup with default launch parameters since the last update (21st June 2023). Using `PROTON_LOG=1 %command%` crashes most of the time, but 1/5 times gets ingame and then performs nicely.

**Comment by kisak-valve** [comment]
Hello @Mershl, `warn:seh:handle_syscall_fault backtrace: --- Exception 0xc0000005 at 0x7f20d51fd772: /tmp/pressure-vessel-libs-WEHV61/x86_64/gameoverlayrenderer.so + 0x27772.` in your Proton log hints that you're seeing https://github.com/ValveSoftware/steam-for-linux/issues/9586.

**Comment by Mershl** [comment]
Hi @kisak-valve, that's a hit! Disabling the Steam overlay for Circuit Superstars fixes the crash on all tested Proton versions.
