### ISSUE TITLE
Audio crackles on all games (using wireplumber) when I've got a pactl script running.

### ISSUE THREAD

**Issue by amogusussy** [ValveSoftware/Proton#6872]
I've got this pactl script to reverse the audio output on my headphones:
```
pactl load-module module-remap-sink \
  sink_name=reverse-stereo \
  master=0 \
  channels=2 \
  master_channel_map=front-right,front-left \
  channel_map=front-left,front-right

pactl set-default-sink reverse-stereo
```

Whenever I try to play a game using proton with this script, the audio starts crackling to the point where you can't make out anything from the game.
This doesn't happen with any other applications (games or otherwise).

I'm using steam through flatpak, with proton version 8.0-2.
This only started happening after my distro (void linux) changed from pulseaudio-media-session to wireplumber.

**Comment by mbriar** [comment]
I think it would make more sense to report this to the pipewire gitlab instead of here, I don't see how that's a proton problem. Windows games on wine/proton just end up requesting a pretty low latency by default, which might make them more likely to hit this issue compared to other applications.

**Comment by amogusussy** [comment]
I've just made an issue on pipewire's gitlab. Here's the link if anyone wants to follow.

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3309

**Comment by kisak-valve** [comment]
Hello @amogusussy, let's treat this as a pipewire issue of some sort for now. If the pipewire dev(s) take a look and find an actionable hint which a Proton dev would need to look into, then add it as a comment here and give me a ping to re-open this issue report.
