### ISSUE TITLE
CANT DUEL WITH MY FRIEND USING STEAM LAUNCHER GWENT

### ISSUE THREAD

**Issue by gendonholaholo** [ValveSoftware/Proton#6873]
# Compatibility Report
- Name of the game with compatibility issues: GWENT
- Steam AppID of the game: 1284410

## System Information
- GPU: RTX 4090
- Driver/LLVM version: 525.105.17
- Kernel version: 6.1.35-x64v3-xanmod1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: GE-Proton7-55

## I confirm:
- [ yes] that I haven't found an existing compatibility report for this game.
- [ yes] that I have checked whether there are updates for my system available.

## Symptoms 
CANT DUEL WITH MY FRIEND USING STEAM LAUNCHER GWENT

**Comment by kisak-valve** [comment]
Hello @gendonholaholo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3890#issuecomment-1605579045.
