### ISSUE TITLE
Graphical glitches in-game if steam overlay disables and non-nativ resolution

### ISSUE THREAD

**Issue by mlandalv** [ValveSoftware/Proton#6881]
#### Your system information

* Steam client version (build number or date): 1687386907, Wed, Jun 21 23:18 UTC -08:00
* Distribution (e.g. Ubuntu):  Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11872224/steam-logs.tar.gz)
* GPU: AMD (mesa 23.1.3)
* [System Information](https://gist.github.com/mlandalv/3dbc5b50d820108fb2681a780d38b481)
* [Steam Runtime Diagnostics](https://gist.github.com/mlandalv/fa7f2bcf93ec217058a1d5868738534b)

Tested with Proton 8.0-2 and Proton Experimental.

#### Please describe your issue in as much detail as possible:
(Not sure if the issue is Proton, Steam, my GPU driver or a combination.)

When disabling the Steam overlay most proton games have graphical artifacts in the bottom of the screen if a non-native resolution is used. It's small flickering black boxes. I have a 3840x1600 monitor so all other resolutions than that results in the glitches. Unfortunately I can't run most games at that res. When the overlay is enabled all resolutions work fine.

#### Steps for reproducing this issue:

1. Find a Steam Play game
2. Right-click game and disable Steam overlay while in-game
3. Start game
4. Change to non-native resolution, e.g. 1920x1200
5. Make sure game is fullscreen

#### Games tested with issues

- GROUND BRANCH
- Hunt: Showdown
- Insurgency: Sandstorm
- Spelunky 2

#### Games tested without issues

-  GTFO

#### Images

![image](https://github.com/ValveSoftware/steam-for-linux/assets/710584/dd1bba5b-161b-499c-b637-98235594ae84)

![image](https://github.com/ValveSoftware/steam-for-linux/assets/710584/b32845ca-036a-46b7-8b53-bb7ca7f6cc9f)

![image](https://github.com/ValveSoftware/steam-for-linux/assets/710584/eb3d5474-f417-40ea-8883-27920d6dd263)

![image](https://github.com/ValveSoftware/steam-for-linux/assets/710584/35bcc285-cb04-4ef8-b809-8b75f6e78d02)

https://github.com/ValveSoftware/steam-for-linux/assets/710584/94468248-0b7b-4544-b0db-97f9599dc682

**Comment by kisak-valve** [comment]
Hello @mlandalv, in general, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report, but this reads like a video driver issue, not an issue caused by the absence of the Steam overlay. This issue should be mentioned to your video driver vendor.

Setting that aside, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by mlandalv** [comment]
Thanks @kisak-valve. I updated the initial post with Steam Runtime Diagnostics. I'm using RADV but will test with AMDVLK later today/tomorrow and file a bug to the video driver vendor instead.

**Comment by mlandalv** [comment]
I tried and everything is fine with AMDVLK so this is an issue with RADV.

Thanks for your help. Feel free to close.

**Comment by DNAmaster10** [comment]
Hi. I'm also experiencing this problem. Was any resolution of fix ever reached?

**Comment by mlandalv** [comment]
@DNAmaster10 It was fixed in mesa just a few days ago.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/8705#note_2657202
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/32115

This had nothing to do with proton, so I'm closing the issue.
