### ISSUE TITLE
Divinity: Original Sin 2

### ISSUE THREAD

**Issue by VeilSilence** [ValveSoftware/Proton#6883]
# Compatibility Report
Divinity:Original Sin 2 Definitive Edition.
Steam AppID of the game:435150

## System Information
- GPU: Nvidia RTX 3090
- Driver/LLVM version: nvidia-open-dkms 535.54.03-3
- Kernel version: 6.3.9-zen1-1-zen 
- Link to full system information report as [Gist](https://gist.github.com/VeilSilence/930fb062507e567e811a616150e6e5ce):
- Proton version:Proton 8.0.2, Proton Experimental, Proton 7.0.6

## I confirm:
- [✓] that I haven't found an existing compatibility report for this game.
- [✓] that I have checked whether there are updates for my system available.

## Symptoms 
Greetings. 
When i'm chosing in Divinity Launcher start "Definitive Edition" game crash after ~60% loading on start. If i chose "Classic" version however, game works properly.
Tried different proton version ( see proton version ) without any luck.

## Reproduction
1:Launch the game
2:Choose in Launcher "Definitive Edition"
3:Crash of loading

[steam-435150.log](https://github.com/ValveSoftware/Proton/files/11884969/steam-435150.log)

**Comment by kisak-valve** [comment]
Hello @VeilSilence, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/413#issuecomment-1609867586.
