### ISSUE TITLE
Risk of Rain 2 proton experimental Steam UI (Shift + Tab) results in crash

### ISSUE THREAD

**Issue by VadimKht** [ValveSoftware/Proton#6884]
# Compatibility Report
- Name of the game with compatibility issues: Risk of Rain 2
- Steam AppID of the game: 632360

## System Information
- GPU: NVIDIA GP107M [GeForce MX350]                                           (3D)
            Intel Corporation Iris Plus Graphics G1 (Ice Lake) (rev 07)  (VGA compatible controller)
 (it's some weird hybrid technology that uses both integrated graphics and gpu)
- Driver/LLVM version: NVRM version: NVIDIA UNIX x86_64 Kernel Module  535.54.03 
GCC version:  gcc (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)
- Kernel version: 6.3.8-200.fc38.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): [here](https://gist.github.com/vadiks2003/5c1414e35207be0e3faccd5769726117)
- Proton version: Experimental

## I confirm:
- [Y] that I haven't found an existing compatibility report for this game.
- [Y] that I have checked whether there are updates for my system available.

 
[steam-632360.zip](https://github.com/ValveSoftware/Proton/files/11888417/steam-632360.zip)
[steam-632360.zip](https://github.com/ValveSoftware/Proton/files/11888443/steam-632360.zip)
(read the ending lines)

## Symptoms 
when pressing shift + tab, ~~the game immediately just closes~~. after reinstalling drivers and signing them instead of doing that with secure boot constnatly off, insteaed of crashing, it just freezes until i press force quit. the proton logs are sent with infinite freeze crashes instead of instant crash (i dont know why i sent 2, i thought first time it didnt immediately crash because i did it in the game intro)

WHY I THINK THIS HAPPENS: there is an issue where steam by default forces to run itself to run on a non default gpu. this used to result in my steam loading, closing, opening up, loading, cosing, opening up, loading,... infinite loop. happened when my GPU driver was installed, but improperly (don't know how it goes about it now) until i added PrefersNonDefaultGPU=false into steam.desktop file. now that i installed drivers properly i don't know if it'd work with  PrefersNonDefaultGPU on. and i don't know if it keeps the same option on proton, but if it does not, there might be an issue!

## Reproduction
press shift tab ingame (open steam ui)

**Comment by VadimKht** [comment]
P.S. this doesnt happen in games that don't require proton to play them

**Comment by kisak-valve** [comment]
Hello @vadiks2003, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2476#issuecomment-1610458592.
