### ISSUE TITLE
Age of Empires 2 DE is broken since 87863

### ISSUE THREAD

**Issue by mistressAlisi** [ValveSoftware/Proton#6885]
# Compatibility Report
- Name of the game with compatibility issues: Age of Empires 2 Definitive Edition
- Steam AppID of the game: 813780

## System Information
- GPU: Radeon RX6750
- Driver/LLVM version: AMD Radeon RX 6750 XT (navi22, LLVM 15.0.6, DRM 3.52, 6.3.3)
- Kernel version:  6.3.3
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/mistressAlisi/010e7112cdb7a9fde8a06baffea56ca3
- Proton version: 8.0

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 
Game crashes during startup complaining about missing Compression/decompression routines:
5756.755:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.756:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.757:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.757:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.760:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.760:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.761:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.761:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.761:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.761:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.765:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.765:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.785:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.785:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.787:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.787:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.792:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.792:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.835:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.835:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.837:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.837:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.839:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.839:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.839:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.839:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.840:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5756.840:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5757.084:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5757.084:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5757.086:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5757.086:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5757.087:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5757.087:0120:0124:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
5757.088:0120:0124:warn:seh:OutputDebugStringA "Fatal Error: one or more game files is invalid\nError code: "
5757.088:0120:0124:trace:seh:dispatch_exception code=40010006 flags=0 addr=000000007B04153C ip=7b04153c
5757.088:0120:0124:trace:seh:dispatch_exception  info[0]=000000000000003c

## Reproduction
Simply install today's update, 87863 and the game will not run anymore.

[steam-813780.log](https://github.com/ValveSoftware/Proton/files/11888985/steam-813780.log)

**Comment by sssemil** [comment]
Somewhat related - https://github.com/wine-mirror/wine/commit/42bd5ea4c4c4c42af872b5a6a12e6109fc3e2ddf

**Comment by kisak-valve** [comment]
Hello @mistressAlisi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3189#issuecomment-1611315107.
