### ISSUE TITLE
Games not working on Arch after new update

### ISSUE THREAD

**Issue by BALVEY7** [ValveSoftware/Proton#6888]
system information:
* Steam client version - 1.0.0.78-1
* Distribution : Arch LTS 64 bit (latest)
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: 1050ti Nvidia(not mobile)/Intel i7-7700HQ (its a laptop)

The file:
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11899123/steam-logs.tar.gz)

This is what is happening:
Before running the command [`pacman -Syu`] the steam was able to play games that are 3D and require interaction on proton 8.0

After the command, the steam can only run 2D games which would classify as Hacknet and Midnight protocol. The other games like Code vein, paradise lost, timeline will not run.

What happens is that after you push play the game will show that is loading and instantly crash or go back to a green button play

I've tried using old versions or proton with no luck, same as going for experimental version.

Some have reported and said that you can run it using flatpak but is poorly documented and if there is an issue unfortunately a small majority of people will know what needs to be done in order to fix that issue.

As for graphics I am using Optimus prime and using it on hybrid

#### Steps for reproducing this issue:

1. open steam 
2. press play on a game that is 3D or 1st person
3. crashes and clauses going back to play button 

I'm looking forward from hearing you soon

**Comment by kisak-valve** [comment]
Hello @BALVEY7, in general, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report.

Please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to some of the affected game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, 
please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by simifor** [comment]
For what is worth, I can't reproduce the issue. Updated my system, opened steam and tried several 3D games and they work fine. Considering you mentioned 3D games specifically, perhaps it's an issue with the drivers, maybe it's trying to use the iGPU of the system?

**Comment by BALVEY7** [comment]
after doing some research I found that Optimus prime or the manager does not work at all not allowing me to use my gpu graphics at all, I've tried switching to gpu but instead it ended up in the error. I have reported this issue to the devs of optimus
if you have a solution of how I might be able to fix it. I believe it would be best to discuss this with Optimus devs.

here is the link:
https://github.com/Askannz/optimus-manager/issues/545

And here are the gist:
Steam runtime: https://gist.github.com/BALVEY7/c48d50f6a50b60f006791dde21edf94c
Steam ID LOG: https://gist.github.com/BALVEY7/dca337a3ff9c6effdef0ef9e4f6fe127
Steam system info: https://gist.github.com/BALVEY7/b4954498ad46d65cb9aecb9290231827

IF links do not work, here are the files

As for the files that were requested are here:
[New Folder.zip](https://github.com/ValveSoftware/Proton/files/11905191/New.Folder.zip)

Ive tried what you have suggested but it didn't work unfortunately.

**Comment by BALVEY7** [comment]
> For what is worth, I can't reproduce the issue. Updated my system, opened steam and tried several 3D games and they work fine. Considering you mentioned 3D games specifically, perhaps it's an issue with the drivers, maybe it's trying to use the iGPU of the system?


Do you use optimus prime?

**Comment by kisak-valve** [comment]
It might be interesting to test how Code Vein behaves with the game's launch options set to `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia %command%`.

**Comment by BALVEY7** [comment]
> 

which file you want in return to check that?

**Comment by BALVEY7** [comment]
> It might be interesting to test how Code Vein behaves with the game's launch options set to `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia %command%`.

I've recived the same result

**Comment by simifor** [comment]
@BALVEY7 no, my igpu is disabled and my card is amd so I can't test optimus

**Comment by BALVEY7** [comment]
> @BALVEY7 no, my igpu is disabled and my card is amd so I can't test optimus

yeah radeon seem to work fine is more down to nvidia 
I'm planing to fix the optimus first than if the issue still stands i report the progress more

**Comment by BALVEY7** [comment]
hello 
I'm back, after doing some digging and help from Barnabás Pőcze. Turns out it was Optimus-manager all along. The python launguage needed to be rebuild with the command 

```
paru -S --rebuild optimus-manager
q
y
optimus-manager --status "if ok you can reboot the system"
reboot
```
I would recommend to checking the tread:
https://github.com/Askannz/optimus-manager/issues/545

Thank you for your help
