### ISSUE TITLE
Batman Arkham Origins 209000

### ISSUE THREAD

**Issue by CarterTheSpaceman** [ValveSoftware/Proton#6892]
# Whitelist Request
- Name of the game to be whitelisted: Batman Arkham Origins
- Steam AppID of the game: 209000

## System Information
- GPU: AMD AMD Custtom GPU 0405 LLVM 14.0.6, DRM 3.45 5.13.0-VALVE36-1-NEPTUNE
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 22.2.0 (git-17e5312102)
- Distro version: 3.4.8
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 8.0.2

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello @CarterTheSpaceman, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1385#issuecomment-1613424084.
