### ISSUE TITLE
The Isle [Evrima beta branch] (376210)

### ISSUE THREAD

**Issue by KczBen** [ValveSoftware/Proton#6893]
# Compatibility Report
- Name of the game with compatibility issues: The Isle [Evrima]
- Steam AppID of the game: 376210

## System Information
- GPU: AMD Radeon RX 6800 XT
- Driver/LLVM version: Mesa 23.1.2-1, LLVM 15.0.7
- Kernel version: 6.3.10-x64v3-xanmod1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/KczBen/43f99ecb2565e5cbfa2b58374d4c5736
- Proton version: 8.0-2 (Also happens with Experimental 20230627)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Since the update to Unreal Engine 5, the game crashes with a shader compilation error when joining a server.

I also tried launching the game using the AMDVLK and AMDGPU-PRO drivers, but the game refused to start with a "DX12 is not supported on your system." error on both of those.

## Reproduction
1, Make sure the Evrima beta branch is selected
2, Start game - May fail to load, but I don't believe that's a Proton-specific issue as it happens on my Windows 11 system too
3, Try joining any server

Fatal shader compilation error comes up, game closes

[steam-376210.tar.gz](https://github.com/ValveSoftware/Proton/files/11908023/steam-376210.tar.gz)

**Comment by kisak-valve** [comment]
Hello @KczBen, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2528#issuecomment-1613496863.
