### ISSUE TITLE
Phasmophobia no longer works on 8.0-2 and above as well as crashing on lower versions

### ISSUE THREAD

**Issue by Veikrom** [ValveSoftware/Proton#6895]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:739630

## System Information
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Driver/LLVM version: Nvidia 470.182.03
- Kernel version: 5.10.0-23-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Veikrom/c912a339d00219d3c0f3b6146bc0e4ad
- Proton version: Proton 8.0-2
[steam-739630.log](https://github.com/ValveSoftware/Proton/files/11911958/steam-739630.log)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

When attempting to launch a game like Phasmophobia or I get the following error

`Failed to initialize graphics.
Make sure you have DirectX 11 installed, have up to date
drivers for your graphics card and have not disabled
3D acceleration in display settings.
InitializeEngineGraphics failed`

## Reproduction
Start the game

 
[steam-739630.log](https://github.com/ValveSoftware/Proton/files/11911959/steam-739630.log)

**Comment by kisak-valve** [comment]
Hello @Veikrom, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4295#issuecomment-1614019625.
