### ISSUE TITLE
Middle-Earth: Shadow of Mordor & War both

### ISSUE THREAD

**Issue by raddad772** [ValveSoftware/Proton#6896]
# Compatibility Report
- Middle Earth: Shadow of Mordor & War (same issue on both)
- Steam AppID of the game: 241930 (Mordor), 356190 (War)

## System Information
On Steam Deck.
- GPU: Steam Deck APU
- Driver/LLVM version: Latest Stable Steam Deck as of 6/30/23
- Kernel version: Steam Deck...
- Link to full system information report as [Gist](https://gist.github.com/): it's a Steam Deck? Do I need this?
- Proton version: Experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. <-- there are old ones from 2018 that are UNRELATED
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
When playing BOTH games, controls will randomly lock to keyboard/mouse. The Y button stops working on the gamepad, prompts (including for QTE) are showing with keyboard keys, and sometimes other parts of controls don't work anymore either.

This seems to be associated with volume keys and/or sleeping and resuming, perhaps during cutscenes.

I have disabled the touch screen, made sure there's no keyboard input from any buttons, etc.

If it helps, when you sleep the game, you can see it switch to kb/m before the system actually goes to sleep sometimes.

## Reproduction
This is very difficult to do, but there are many reports all over the internet. I suggest you:
1) Play the game at 40Hz, like me
2) Sleep the game, until the next day sometime (as I often do)
3) Wake the game, play some, sleep again
4) Adjust volume too, and/or use bluetooth earbuds

Usually this seems to happen after custcenes, but not always.

So best chance to reproduce is probably a lot of wake/sleep and turning bluetooth headphones on and off and hitting the volume keys a bunch.

**Comment by kisak-valve** [comment]
Hello @raddad772, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2251#issuecomment-1614607721.
