### ISSUE TITLE
Democracy 4 (1410710)

### ISSUE THREAD

**Issue by Folling** [ValveSoftware/Proton#6897]
# Compatibility Report
- Name of the game with compatibility issues: Democracy 4
- Steam AppID of the game: 1410710

## System Information
- GPU: AMD 6800XT
- Driver/LLVM version: Mesa 23.1.2
- Kernel version: Linux 6.3.8_1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Folling/4427bf5393841f23e8ca46684be2c558
- Proton version: multiple. latest was 8.0-2. 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1410710.log](https://github.com/ValveSoftware/Proton/files/11916865/steam-1410710.log)

## Symptoms 

Launching fails relatively quickly with a messagebox that displays the following:
> Failed to iniitialize 3D Engine:D\programming\democracy 4\builds\Democracy4\src\_all_operating_systems\app\app_game.cpp 406

## Reproduction

Launch the game.

PS: As I'm on wayland, I'm setting `SDL_VIDEODRIVER=x11`, otherwise the game doesn't launch at all since the bundled SDL fails to select a backend.

**Comment by kisak-valve** [comment]
Hello @Folling, it looks like this game uses the Windows variant of SDL2 (`trace:loaddll:build_module Loaded L"Z:\\mnt\\data\\steam\\steamapps\\common\\Democracy 4\\SDL2.dll" at 01680000: native`). This could be getting confused by `SDL_VIDEODRIVER=x11`. It would be interesting to test how the game behaves with the game's launch options set to `SDL_VIDEODRIVER=windows %command%`. (https://github.com/ValveSoftware/Proton/issues/5587#issuecomment-1202309902)

**Comment by Folling** [comment]
Would you look at that. Thanks a bunch!
