### ISSUE TITLE
[Proton 8.0-2c] Key ghosting with DragonRise ZeroDelay controllers

### ISSUE THREAD

**Issue by gsrodelgo** [ValveSoftware/Proton#6898]
Hi, Im a Batocera user that has sticky key or key ghosting problem with zeroDelay controllers from DragonRise with the last version of proton included (8.0-2c). In the last release version of Batocera (v37) they have updated wine proton to 8.0-2c and in Batocera 36 this were not happening. A Batocera dev points me to open this issue because this sounds familiar to him and thinks that this could be a stack regresion bug on your end.

The issue opened on batocera board describing the problem is: [https://github.com/batocera-linux/batocera.linux/issues/9131](https://github.com/batocera-linux/batocera.linux/issues/9131)

And the video of key ghosting in action is here. This happens after hitting right stick direction once: 

[https://user-images.githubusercontent.com/61735565/249855228-4ce7d629-8ab2-4b08-be07-37ddb60ebdc2.mp4](https://user-images.githubusercontent.com/61735565/249855228-4ce7d629-8ab2-4b08-be07-37ddb60ebdc2.mp4)

Could you address this in some way? Thank you!

**Comment by kisak-valve** [comment]
Hello @gsrodelgo, in general, we're tracking issues with Proton in the Proton issue tracker, so I've transferred this issue report. I'm not particularly familiar with this flavor of Linux. If they're pulling out the wine build bundled with Proton and using it for other purposes, that's not really something that can be supported.

**Comment by ivyl** [comment]
What was the Proton version used by the previous release of Batocera? I can check if there were any relevant code changes.

As Kisak has said, we don't really support Proton re-distributions and we haven't heard reports of anything similar. Can you check if you have the same problem with Proton launched via Steam? It may be unique to the controllers but I'm not sure where to get one.

**Comment by gsrodelgo** [comment]
Hi @ivyl the version of proton that worked perfectly fine in batocera 36 was 

wine-proton to 7.0-5
vkd3d-proton to v2.8

I dont know if this is something relevant to see major changes between 7.0 and 8.0 that could fit with this problem.

Thank you!

**Comment by gsrodelgo** [comment]
Hi, I think this issue could be closed because I have clues that point me to think this is not a proton bug. In case anyone has curiosity about what is this all about, you can continue reading in the original ticket on the batocera board.

Thank you!
