### ISSUE TITLE
FileNotFoundError: no such file or directory - compatdata dir when running certain games. (all versions steam/ proton)

### ISSUE THREAD

**Issue by teletrail** [ValveSoftware/Proton#6900]
#### Your system information
Current Steam version (tested with linux native -sniper n default steam)

distribution: gentoo

tested with beta and default

system is updated

error log:

https://gist.github.com/teletrail/669f32e3066659bd1dc66b1de28ddac0

gpu: nvidia 2060 (drivers up-to-date)

starting certain games results in briefly running the stopping again, with error re: compatdata dir not being found.

steam directory is symlinked to second drive, also tested without symlink (new .steam dir) and error is the same.

"FileNotFoundError: [Errno 2] No such file or directory: '../drive_c' -> '/media/project/organic/Steam/steamapps/compatdata/2055290/pfx//dosdevices/c:'"

this error appears for a lot of games now, not all of them though.

expected: game runs 

result: game briefly runs then quits with error about compatdata dir not being found.

tested with various versions of proton, including proton-ge.

reproducing: download game (also tested uninstalling n reinstalling, verifying game files, same result)
 run game

see error in logs.

the drive steam is symlinked to is ext4. some games run without complaint.

affected games so far:

guilty gear xrd

sonic colors ultimate

stray

thanks any help would be appreciated.

**Comment by kisak-valve** [comment]
Hello @teletrail, in general, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report.

Having written that, can you check if https://github.com/ValveSoftware/steam-runtime/issues/334 is the issue you're seeing?

**Comment by teletrail** [comment]
thanks for the reply. where should steam_compat_mounts  point to? I will attempt to run steam with this applied. should it be the base steam directory or the compatdata folder?

it is worth noting that not all games are affected by this, not sure what the common denominator is.


thanks again.

**Comment by kisak-valve** [comment]
For the test, I would try the folder you pointed your symlinks towards.

**Comment by teletrail** [comment]
"STEAM_COMPAT_MOUNTS=/media/project/organic/Steam steam" does not help, same error.

**Comment by teletrail** [comment]
sorry to bother, this is an error with proton-ge not creating a dosdevices folder. appreciate the help. when I removed compatdata dir and made proton-8.04 default games worked again.

thanks again.

**Comment by kisak-valve** [comment]
You'll probably want to follow up with the maintainer of the third party build. Closing because this doesn't appear to be a mainline Proton issue.

**Comment by libcg** [comment]
@kisak-valve I'm hitting the same issue with Proton 8.0-3 and Proton Experimental:
```
Proton: Upgrading prefix from None to 8.0-103 (/home/libcg/.local/share/Steam/steamapps/compatdata/548430/)
Traceback (most recent call last):
  File "/home/libcg/.local/share/Steam/steamapps/common/Proton 8.0/proton", line 1658, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/libcg/.local/share/Steam/steamapps/common/Proton 8.0/proton", line 1453, in init_session
    g_compatdata.setup_prefix()
  File "/home/libcg/.local/share/Steam/steamapps/common/Proton 8.0/proton", line 789, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
FileNotFoundError: [Errno 2] No such file or directory: '../drive_c' -> '/home/libcg/.local/share/Steam/steamapps/compatdata/548430/pfx//dosdevices/c:'
```
The error can be fixed by creating the missing `dosdevices` folder:
`mkdir /home/libcg/.local/share/Steam/steamapps/compatdata/548430/pfx//dosdevices`
