### ISSUE TITLE
Broken video in ASTRONEER - all other videos are okay

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [ValveSoftware/Proton#6901]
An opening cutscene in ASTRONEER (app id 361420) incorrectly appears as a color test pattern, but ONLY the one video is affected and all the others will still play normally, even though all of them are MP4 format, including the one with the problem.

Tested with 7.0-6 (the default), 8.0-2 and experimental

[steam-361420.log](https://github.com/ValveSoftware/Proton/files/11923876/steam-361420.log)

**Comment by kisak-valve** [comment]
Hello @UsernamesAreNotMyThing, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/243#issuecomment-1615326100.
