### ISSUE TITLE
PolyBridge3 not working on Linux

### ISSUE THREAD

**Issue by gertk64** [ValveSoftware/Proton#6902]
# Compatibility Report
- Name of the game with compatibility issues: Poly Bridge 3
- Steam AppID of the game:1850160

## System Information
- GPU: AMD AMD RENOIR (DRM 3.42.0, 5.15.0-76-generic, LLVM 12.0.1)
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 21.3.0-devel
- Kernel version: 5.15.0-76-generic #83~20.04.1-Ubuntu SMP
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/gertk64/8a76eacdbc5e0abac8da66323e204a00
- Proton version:

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

 no log created

**Comment by kisak-valve** [comment]
Hello @gertk64, it looks like this game has a native Linux variant. Without a stronger indicator, Proton isn't involved with running the game, which makes this feedback out of scope for this issue tracker.

In general, issues with Linux native variants of games should be mentioned directly to the game's dev(s).

As a side note, you're using a very old random git build of mesa from almost 2 years ago. That isn't something that people would want to support.

Closing as out of scope for this issue tracker.
