### ISSUE TITLE
DOOM (2016) demo crashes with Vulkan

### ISSUE THREAD

**Issue by SuperSamus** [ValveSoftware/Proton#6903]
# Compatibility Report
- Name of the game with compatibility issues: DOOM
- Steam AppID of the game: 379720

## System Information
- GPU: RX 6700XT
- Driver/LLVM version: Mesa 23.1.2
- Kernel version: 6.3.5-xanmod1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/SuperSamus/ce1a0f55670658ebcd4422acaba1d614/
- Proton version: Experimental (also tested GE)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Continuation of #185, which can be closed (as it works perfectly with OpenGL).
DOOM (2016) demo crashes when using the Vulkan API. It crashes as soon as you enable it, and it crashes every time you try to open the game afterward.
Logs by trying to open the game after the fact. Steam overlay is disabled. [steam-479030.log](https://github.com/ValveSoftware/Proton/files/11927720/steam-479030.log)

## Reproduction

1. Launch DOOM (2016) demo
2. Go on until you reach the game's settings (they are *after* you start a new campaign).
3. In the advanced settings, set Graphics API to Vulkan.
4. Crash.
5. Open the game again, crash again.

**Comment by kisak-valve** [comment]
Hello @SuperSamus, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/185#issuecomment-1616215445.

**Comment by massatt212** [comment]
Doom 2016 using openGL on amd gpu seems to be very laggy on proton 9 proton 8 woks good and also vulkan, but vulkan tends to crash on doom 2016 a lot.
