### ISSUE TITLE
Axial Disc 1 (1638430)

### ISSUE THREAD

**Issue by nightblade9** [ValveSoftware/Proton#6906]
# Compatibility Report
- Name of the game with compatibility issues: Axial Disc 1
- Steam AppID of the game: 1638430

## System Information
- GPU: GeForce GTX 1650 Ti Mobile
- Driver/LLVM version: I honestly don't know, sorry.
- Kernel version: 6.1.31-2
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/nightblade9/74971764595f0bad679bbdfa3103a9b9
- Proton version: 6.3-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton/App log:  [steam-1638430.log](https://github.com/ValveSoftware/Proton/files/11928533/steam-1638430.log)

## Symptoms

The game window shrinks constantly as you play; and it also doesn't resize correctly for my external monitor (which I'm not concerned with). This happens both in windowed and full-screen mode.

Happens more and more the longer you wait; here's how it looks after a couple of minutes (note the bottom is cut off).

![image](https://github.com/ValveSoftware/Proton/assets/31222662/39268f6f-f27e-44c1-8918-a9a601ab0351)

## Reproduction

- Launch the game (it's free to download)
- On the main menu, keep pressing left/right arrow keys
- Observe; the window will start shrinking.

## Work-Rround Notes

I tried several versions of Proton, starting with "experimental" and working back to 5.13-6. 5.13-6 works fine (albeit with an ugly blue game window), 6.3-8 and newer versions exhibit the problem.

## System Information

Launch Steam > Help > System Information. Results are [here](https://gist.github.com/nightblade9/5e6b592e8d64e26adccb7949130cb9f1).

**Comment by AJuujarvi** [comment]
@nightblade9 Hello! I have not been able to reproduce this so far on a few different Distros/DEs/WMs and I would love to try and figure this out. Can you please copy your system information from Steam (Open Steam Client -> Help (found on the top taskbar next to Games) -> System Information) and put it in a gist, then include a link to the gist in this issue report. If you're using the Steam client beta, then please also include the output from Steam Runtime Diagnostics.

**Comment by nightblade9** [comment]
@AJuujarvi I'm running Manjaro (latest) with KDE/Plasma, if that helps.

You can find my system info [here](https://gist.github.com/nightblade9/5e6b592e8d64e26adccb7949130cb9f1). I am not using the beta client as far as I know.

**Comment by AJuujarvi** [comment]
> @AJuujarvi I'm running Manjaro (latest) with KDE/Plasma, if that helps.
> 
> You can find my system info [here](https://gist.github.com/nightblade9/5e6b592e8d64e26adccb7949130cb9f1). I am not using the beta client as far as I know.

Your System Information seems to indicate that you are currently using your Intel Integrated GPU instead of your Nvidia GPU. Can you boot the game with your Nvidia GPU and see if you can still repro the issue? You can do this by right clicking the game in your Library and clicking "Properties". From there, you should see something that says Launch Options. Type in `DRI_PRIME=1 %command%` and then try to boot the game. Manjaro's official site has a section on dual GPUs and how to boot with the non-default one here which is where I got this command. https://wiki.manjaro.org/index.php?title=Configure_Graphics_Cards

If that works for you, please let me know.

**Comment by nightblade9** [comment]
Interesting, I didn't realize this machine has two GPUs. Thanks for that.

I reinstalled the game a couple of times, but the problem no longer reproduces (using Proton Experimental, even without changing the launch options). I am not sure how to interpret this. I will close this issue for now, and re-open it if the issue comes back (and if your suggestion doesn't fix it).

Thanks for looking into this!
