### ISSUE TITLE
Proton-Experimental games start with incredibly low performance (less than 1fps) when started as fullscreen

### ISSUE THREAD

**Issue by hikarutilmitt** [ValveSoftware/Proton#6907]
# Compatibility Report

## System Information
- GPU: RTX 3060 12GB
- Driver/LLVM version: 535.54.03
- Kernel version: 6.3.9-zen1-1-zen
- Link to full system information report as [Gist]: https://gist.github.com/hikarutilmitt/f1e3c3e9f22f54ee39370e553ab73a69
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton log example:
[steam-1342260-8.0-3RC.log](https://github.com/ValveSoftware/Proton/files/11928620/steam-1342260-8.0-3RC.log)
[steam-1342260-experimental.log](https://github.com/ValveSoftware/Proton/files/11928619/steam-1342260-experimental.log)

## Symptoms 
When starting most games with the current Proton Experimental if they run in fullscreen they will start with an immeasurably low FPS. 

## Reproduction
Set game compatibility to Proton Experimental
Start game

This doesn't happen with 8.0 or even the 8.0-3 RC at the moment, which I would assume has most of the changes from experimental baked into it. It's been happening for maybe a week (sadly I cannot remember when I first noticed it) and is worked around by using a stable release, so I'd assume there was some regression somewhere.

### Things I've tried while troubleshoot this:
rolling back to the previous stable Nvidia driver (the steam-runtime has issues with the current release, it turns out)
using the flatpak for Steam rather than the steam-runtime client (the current notes and logs are from flatpak)
disabling the compositor within kwin entirely
using a different kernel
changing resolution
completely removing the existing pfx and shader cache and letting them both rebuild

I'm open to it maybe being a Kwin issue since it seems to show the game running fine if it's not focused (like when alt-tabbing to get back to the Steam client and close the game) but it's not affecting anything else, nor does it happen when not using experimental.  I attached a log for Samurai Shodown for running it on Experimental as well as the 8.0-3 RC just for comparing a "normal" game start on the same game on my system, in case my system has any quirks I'm not aware of.

The only other change to my system that has happened within this past week was switching from using mkinitcpio as my initramfs builder to booster. The same exact kernel parameters are used for modesetting the nvidia driver as before. I couldn't imagine this being the reason for this change, (because, again, it's only affecting Experimental) but I don't rule out things as impossibilities and have seen weirder things before.

**Comment by kisak-valve** [comment]
Hello @hikarutilmitt, this reads like a duplicate #6869. Closing in favor of the older issue report.

**Comment by Jenrikku** [comment]
This is not a duplicated of issue #6869 as it does not seem to have anything to do with it. Even after downgrading the nvidia driver that caused said issue (#6869), this one still persists and so I am forced to downgrade my proton.

I am also using KWin as the creator of this issue which may or may not be related.

Edit: This seems to have been fixed in the latest Proton Experimental.

**Comment by perdakovich** [comment]
this is happening to me on Proton 10 ...

**Comment by perdakovich** [comment]
it was related to #6869 
setting workaround launch options helped
