### ISSUE TITLE
game runs on slowmotion!?

### ISSUE THREAD

**Issue by quaz33z** [ValveSoftware/Proton#6909]
# Compatibility Report
- Name of the game with compatibility issues: Farlight 84
- Steam AppID of the game:1928420

## System Information
- GPU:  gt 650
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental

## I confirm:
- [yes ] that I haven't found an existing compatibility report for this game.
- [yes ] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @quaz33z, in general, we're using one issue per unofficially supported game title, and feedback on Farlight 84 being run with Proton is being tracked at #6717.

Having written that, the NVIDIA GT 650 is a Kepler generation video card, and the newest NVIDIA proprietary driver to support that hardware generation is the 470 series video driver. That video driver series provides Vulkan 1.2. Proton 8.0 and newer requires Vulkan 1.3, making that video driver too old for continued support.  There's a good chance that Proton Experimental is being forced to use an Intel or AMD chipset that's part of your CPU as the only usable option.

Closing the almost blank compatibility report template.
