### ISSUE TITLE
Proton 8.0-2 DXSETUP.exe hanging on New Steam Installation

### ISSUE THREAD

**Issue by reedlove** [ValveSoftware/Proton#6912]
#### Your system information

* Steam client 
version (build number or date): 1687386907
* Distribution (e.g. Ubuntu): Linux Mint 21.1 Cinnamon
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11952331/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Proton 8.0-2 is freezing on a clean/new installation of Steam (both the Linux Mint package and .deb from steampowered.com). The Steam client itself does not freeze but it appears that Proton's wine services hang while trying to run DXSETUP.exe. I was able to fix it by running "Clear Cache" under "Downloads" in settings. After I do this and sign back in, Proton magically works again.

#### Steps for reproducing this issue:

1. Install Steam
2. Choose Proton 8.0-2 under compatibility settings for a windows game.
3. Run said game.

I've duplicated this on two separate machines.

Edit:
After messing around a bit more, it turns out that it's only Proton 8.0-2 that appears to hang when running a game for the first time on a clean installation of Steam. Again, it appears to be "DXSETUP.exe" that hangs.

**Comment by reedlove** [comment]
This randomly effects multiple games. Final Fantasy VII Remake, Overcooked, etc. Doesn't seem to be a rhyme or reason.

**Comment by tim-gromeyer** [comment]
I noticed the same in Assetto Corsa (#148). It would be really nice if they could add support for it. It works with GE-Proton, so it is possible
