### ISSUE TITLE
Master Duels

### ISSUE THREAD

**Issue by jonte450** [ValveSoftware/Proton#6915]
Hi i am running an Ubuntu 23.04 and i have tried to start Master Duels with Proton version 08..03
And i have written in PROTON_USE_WINE3D=1 %command% and the game doesn't start and i have tried in my launch options to write PROTON_LOG=1 %command% and i don't get any debug.log file in my home directory?

**Comment by kisak-valve** [comment]
Hello @jonte450, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5876#issuecomment-1621659679.
