### ISSUE TITLE
Street Fighter 6 (1364780) : "Generic Xbox Pad" freezes Challenge Screen for 60 seconds

### ISSUE THREAD

**Issue by d4ve89** [ValveSoftware/Proton#6916]
# Compatibility Report
- Name of the game with compatibility issues: Street Fighter 6
- Steam AppID of the game: 1364780

## System Information
- GPU: AMD RX 6600
- Driver/LLVM version:  Mesa 23.1.3-1 / LLVM 15.0.7
- Kernel version: 6.4.1-zen2-1-zen
- Proton version: experimental-8.0-20230627 (default)
- Input device: Snackbox Micro 2022, registered as "Generic Xbox Pad":
lsusb prompt: 
`0c12:0ef7 Zeroplus P4 Wired Gamepad` (when connected as PS4 Pad)
`0c12:0ef8 Zeroplus Controller` (when connected as Generic Xbox Pad)
`054c:0268 Sony Corp. Batoh Device / PlayStation 3 Controller`  (when connected as PS3 Pad)

## I confirm:
- that I haven't found an existing compatibility report for this game.
- that I have checked whether there are updates for my system available.

## Symptoms

When switching from Keyboard to  Gamepad input, the video freezes when the **Challenge Screen** 
appears in online match making (sound clip: "Here comes a new challenger" and "Ranked Match" video). 

After exactly 1 minute, the video continues, but game disconnects me from the match for inactivity.

When using "Generic Xbox Pad" (which is a Snackbox Micro), the bug appears as logged in this file:
[steam-1364780_bug.log](https://github.com/ValveSoftware/Proton/files/11956042/steam-1364780_bug.log)

When using a keyboard, the bug does not appear, as logged here:
[steam-1364780_nobug.log](https://github.com/ValveSoftware/Proton/files/11956072/steam-1364780_nobug.log)

You can even reproduce the bug outside of real match making, but when previewing your Challenge Screen:
```
Fighting Ground -> Battle Settings (X) 
-> Character Tab -> Update Character Settings (Y) 
-> Customize Challenges Tab -> Full Screen Preview (Y)
```

The video clip does not  fully play, because it stops mid-animation and I only see a few letters like: 
"R A N K E  _  M  _ T _  H ".

I have tried deleting the compatdata  and the shader cache multiple times and rebuilt them, 
but that did not fix the problem.

The exact error message when the bug appears is the following:
```
21708.031:0140:023c:err:sync:RtlpWaitForCriticalSection section 0000020000197368 (null) wait timed out in thread 023c, blocked by 01e8, retrying (60 sec)

21709.472:0140:01cc:err:sync:RtlpWaitForCriticalSection section 0000000259D96140 "../src-wine/dlls/xinput1_3/main.c: controllers[0].crit" wait timed out in thread 01cc, blocked by 01e8, retrying (60 sec)
```
It times out the game for exactly 60 seconds:  "**blocked by 01e8, retrying (60 sec)**"
0ef8 is the "Zeroplus Controller" (when Snackbox Micro is connected as Generic Xbox Pad)

### **edit:** 
The bug occurs when the arcade stick is being used in x-input mode (registered as "Generic Xbox Pad" 0c12:0ef8) and PS3-Mode (registered as "PS3 Controller" 054c:0268), but there are no problems in PS4-mode (registered as "Brook Univeral Fighting Board" 0c12:0ef7).

## Reproduction
You need a keyboard and another peripheral in x-input mode, registered as "Generic Xbox Pad"  
(in my case: Snackbox Micro 2022, 0c12:0ef8).

With the "Generic Xbox Pad", you trigger the bug like this:
```
Fighting Ground -> Battle Settings (X) 
-> Character Tab -> Update Character Settings (Y) 
-> Customize Challenges Tab -> Full Screen Preview (Y)
```

With keyboard input, the bug does not appear:
```
Fighting Ground -> Battle settings (R) 
-> Character Tab -> Update Character Settings (T) 
-> Customize Challenges Tab -> Full Screen Preview (T)
```

If you accept the match with your Keyboard and wait until the Challenge Screen is over,
you can switch to Gamepad and continue to play without any error.

**Comment by kisak-valve** [comment]
Hello @Dve89, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6817#issuecomment-1621664080.
