### ISSUE TITLE
New World

### ISSUE THREAD

**Issue by HydeFromT70s** [ValveSoftware/Proton#6920]
# Compatibility Report
- Name of the game with compatibility issues: **New World**
- Steam AppID of the game: **1063730**

## System Information
- GPU: **NVIDIA GTX 1070**
- Driver/LLVM version: **535.54.03-7 / 15.0.7-3**
- Kernel version: **6.4.2-arch1-1**
- Link to full system information report as [Gist](https://gist.github.com/HydeFromT70s/aedb7ebfb9481ad6e184ec333d9c663c)
- Proton version: **Experimental / 8.0-2**

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.

- [x] that I have checked whether there are updates for my system available.

Proton log as [Gist](https://gist.github.com/HydeFromT70s/8f818f2edbd4f6e16fcbfc9a236c2354)

## Symptoms 
The game stopped launching after the last update on July 6. In steam it has the status "Running", but after a few seconds the game crashes with an error as in the picture. Before the update the game was running without any problems.

![Crash Error](https://i.imgur.com/LjuQl5r.png)

NOTE: The game starts normal with Proton 7.0-6.

## Reproduction
Just start the game with Proton Experimental or Proton 8.0

**Comment by kisak-valve** [comment]
Hello @HydeFromT70s, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5772#issuecomment-1627749803.
