### ISSUE TITLE
Final Fantasy X/X-2 HD Remaster crashes on launch

### ISSUE THREAD

**Issue by kurtbixby** [ValveSoftware/Proton#6921]
# Compatibility Report
- Name of the game with compatibility issues: Final Fantasy X/X-2 HD Remaster
- Steam AppID of the game: 359870

## System Information
- GPU: Steam Deck
- Driver/LLVM version: Mesa 22.2.0
- Kernel version: 5.13.0
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7.0-6

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Proton Log
https://gist.github.com/kurtbixby/8c0366f76b68f65f3de5d90daf01f54d

## Symptoms 
Final Fantasy X-2 crashes on boot

## Reproduction
1) Start Final Fantasy X/X-2
2) Select Final Fantasy X-2 from the launcher
3) Game will crash after the autosave warning

**Comment by kurtbixby** [comment]
This appears to be a regression. The game launches successfully on Proton 6.3-8.

**Comment by kisak-valve** [comment]
Hello @kurtbixby, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/555#issuecomment-1630743654.
