### ISSUE TITLE
[GREYLIST] Bayonetta (460790)

### ISSUE THREAD

**Issue by mimattr** [ValveSoftware/Proton#693]
Ubuntu 16.04, NVIDIA GTX 970, Proton 3.7-4 Beta:

[Steam System Information](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)

Test | Result
-- | --
Singleplayer | Working^
Local Co-op | _N/A_
Online Multiplayer | _N/A_

Configuration | ...
-- | --
Input | Steam Controller
Display | 1920x1080
Fullscreen | Yes
Preset | Medium
VSync | On^^
API | DX9

^ [CRIWARE](https://www.criware.com) “Filmstrip” cutscenes display incorrectly
^^ Disabling “VSync” causes application freeze (#262)

**Comment by Zero86Sk** [comment]
i would say this is not whitelist worthy yet

**Comment by mimattr** [comment]
@Zero86Sk Please note this is a "Greylist" item (i.e. near feature complete), the "Whitelist" should be reserved for fully functional products.

**Comment by mimattr** [comment]
@Zero86Sk Please note this is a **GREYLIST** item (i.e. near feature complete), the **WHITELIST** should be reserved for fully functional products.

**Comment by kisak-valve** [comment]
Hello @mimattr, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/262#issuecomment-416069321.
