### ISSUE TITLE
Can't run `NARAKA BLADEPOINT` on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by sauntor** [ValveSoftware/Proton#6937]
# Compatibility Report
- Name of the game with compatibility issues: 永劫无间（NARAKA BLADEPOINT）
- Steam AppID of the game: 1203220

## System Information
- GPU: NVIDIA GeForce GTX 1050/PCIe/SSE2
- Driver/LLVM version: nvidia-drivers-G06-535.54.03-10.1.x86_64
- Kernel version: 6.4.3-1-default
- Full system information report(I've no access to Gist, attach it here):  [System Information](https://github.com/ValveSoftware/Proton/files/12098506/sysinfo.log)
- Proton version: 8.0-2
- Dell XPS 15 / 9560

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
  > issue #4907 
- [x ] that I have checked whether there are updates for my system available.

[steam-1203220.log](https://github.com/ValveSoftware/Proton/files/12098452/steam-1203220.log)
[logs from terminal](https://github.com/ValveSoftware/Proton/files/12098570/steam-in-cli.log)

## Symptoms
No interface shown after click the `Play` button, and a while later, the game will exit and the `Play` button will be clickable too.

## Reproduction
1. Fresh installed openSUSE Tumbleweed
2. Get all updates: `zypper ref && zypper inr && zypper dup`
3.  Install `32bit` runtime: `zypper in -t pattern 32bit`
4. Install NVIDIA G06 Driver:
   ```sh
   zypper ar -cefg https://download.nvidia.com/opensuse/tumbleweed/   nvidia
   zypper ref && zypper in --recommends nvidia-drivers-G06
   ```
5.  Install steam client: `zypper in --recommends steam`
6. Launch `Steam` and install `NARAKA BLADEPOINT`
7. Change the `Properties` of `NARAKA BLADEPOINT`, set `Compatibility` to `Proton 8.0-2`, in `General`,  set `Launch Options` to `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia`
8. Try to launch the game

**Comment by kisak-valve** [comment]
Hello @sauntor, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4907#issuecomment-1642507049.
