### ISSUE TITLE
Plants vs Zombies: Game of the Year - Hardware Acceleration

### ISSUE THREAD

**Issue by RedSoxFan04** [ValveSoftware/Proton#6940]
The game runs well, but as far as I can tell, it seems like it's just using software rendering instead of being rendered by the GPU. For reference, I have an AMD RX 5600 XT, which is very well-supported on Linux. I would like to be able to use GPU rendering because it would allow my PC to run much more quietly while playing this game.

**Comment by kisak-valve** [comment]
Hello @RedSoxFan04, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/238#issuecomment-1644420366.
