### ISSUE TITLE
Far Cry 4: It's impossible to play under any version of Proton

### ISSUE THREAD

**Issue by Plarpoon** [ValveSoftware/Proton#6942]
# Compatibility Report
- Name of the game with compatibility issues: Far Cry® 4
- Steam AppID of the game: 298110

## System Information
- GPU: 
- Driver/LLVM version: AMD AMD Radeon RX 7900 XTX (gfx1100, LLVM 16.0.6, DRM 3.52, 6.4.3-1-default)
- Kernel version: 6.4.3-1-default
- Link to full system information report as [Gist](https://gist.github.com/Plarpoon/71f189689e369fb75f884ff845760f02):
- Proton version: All versions up to 8.0-2 (for now)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Note:
* For all of the following logs I have used nothing else but the parameter "PROTON_LOG=1 %command%".
* My Linux distro of choice is OpenSUSE Tumbleweed, this distro has AppArmor constantly enabled in the background, this is noteworthy when doing debugging.

This log is with Proton 8.0-2, it fails immediately after having done the initialization of Ubisoft Connect, it can't even create the window of the game. You have to stop the process manually from within the Steam app by pressing "STOP" as after failure it will remain open in the background forever.
[steam-298110 8.0-2.log](https://github.com/ValveSoftware/Proton/files/12114831/steam-298110.8.0-2.log)

This log is done with GE-Proton8-6, I am aware this is not the place to report Proton GE issues but I am using it only to report what happens once you pass the Ubisoft connect phase and actually manage to create a window. In this case as said the window gets fully created but it crashes a few seconds in during the very first loading screen, not even allowing me to enter into the main menu.
In this case as-well the process will hang forever and the only way to make it stop is by stopping it from withing the Steam app.
[steam-298110 GE-Proton8-6.log](https://github.com/ValveSoftware/Proton/files/12114972/steam-298110.GE-Proton8-6.log)

Many reports on the game's [ProtonDB page](https://www.protondb.com/app/298110) suggest switching to a Proton version equal or inferior to 6.3 as that's the patch that broke the game into the current situation it's in. Unfortunately the behavior is virtually identical to the one of 8.0-2 as it can't pass from the Ubisoft connect launcher properly and it crashes before creating the game window.
[steam-298110 6.3-8.log](https://github.com/ValveSoftware/Proton/files/12115101/steam-298110.6.3-8.log)

I have also added a log with proton experimental (timestamped) but it behaves exactly like Proton 8.0-2.
[steam-298110 Proton Experimental 21 Jul 2023.log](https://github.com/ValveSoftware/Proton/files/12115291/steam-298110.Proton.Experimental.21.Jul.2023.log)

Currently for me it's impossible to play this game in any way shape or form, if I can be useful for any ulterior testing let me know and I will provide all the help I can!
Thank you in advance! :)

**Comment by kisak-valve** [comment]
Hello @Plarpoon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2143#issuecomment-1644852142.
