### ISSUE TITLE
Halo Infinite

### ISSUE THREAD

**Issue by ofili-1337** [ValveSoftware/Proton#6943]
# Compatibility Report
- Name of the game with compatibility issues: Halo Infinite
- Steam AppID of the game: 1240440

## System Information
- CPU: i5 12400f
- RAM: 16GB
- GPU: RX 5600XT
- SSD: 512GB
- OS: Linux Mint 21 XFCE
- Driver/LLVM version: amdgpu 23.10.2
- Kernel version: 5.15.0-76
- Proton version: 8.0-2

## Proton LOG:
https://pastebin.com/eH0BaFMc

I run Halo Infinity, in steam it shows that the game is running and after 3 seconds the game will close.

**Comment by kisak-valve** [comment]
Hello @ofili-1337, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5030#issuecomment-1645434285.

**Comment by ofili-1337** [comment]
https://gist.github.com/ofili-1337/03c59786679bf70b9bd4a06f92ca3e85
