### ISSUE TITLE
Red Dead Redemption 2 won't launch

### ISSUE THREAD

**Issue by jwakely** [ValveSoftware/Proton#6945]
# Compatibility Report
- Name of the game with compatibility issues: Red Dead Redemption 2
- Steam AppID of the game: 1174180

## System Information
- GPU: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
- Driver/LLVM version: nvidia 535.86.05
- Kernel version: 6.3.12-200.fc38.x86_64 (64-bit)
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/jwakely/671e929d0257ea2b4a42824d8e1e183d
- Proton version: Experimental / 8.0-2 / 7.0-6 (same problem with all of them)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms

When I click "Play" it says "Launching" and a message appears next to that button saying "Running install script (Vulkan Runtime Installer)" but then nothing ever happens, it just stays like that.

![image](https://github.com/ValveSoftware/Proton/assets/1254480/43ecb5f7-18c4-44ba-9d1a-670ce6e797b5)

The file `/home/jwakely/.local/share/Steam/standalone_installscript_progress_1174180.vdf` keeps being recreated with this same content, so it seems to be stuck in a loop:

```
"progress"
{
        "current_step"          "0"
        "step_count"            "6"
        "current_step_description"              "Vulkan Runtime Installer"
}
```

When I add `PROTON_LOG=1 %command%` to the launch options no `$HOME/steam-*.log` file is created, so I can't attach it here.

I can click "Cancel", but a `winedevice.exe` process continues to run in the background. If I try to exit Steam it closes the client GUI but the Steam icon stays in the systray and I can't restart Steam. I have to use `kill -9` to kill the `winedevice.exe` and `steam` processes (or rebooot) to use Steam again.

I'm using the `steam-1.0.0.78-1.fc38.i686` RPM on Fedora 38, I've tried both the negativo17.org RPM and the RPMFusion RPM, with the same results.

I get the same results with Proton Experimental, and Proton 8 and Proton 7. I've switched to the Steam Beta client, but still get the same results.

If I install the Steam flatpak from flathub and give it access to my Steam library (so I don't have to download RDR2 again) then I can successfully launch RDR2, install the Rockstar Launcher, and play the game. The flatpak is version 1.0.0.75, so a slightly older version, I don't know if that's why it works. I read online that the latest client is causing this issue with RDR2 for other people too. It also plays perfectly on my Steam Deck.

I changed the game to use Proton 6.3-8 and then launching the game appears to get a further, opening a "Launching Red Dead Redemption 2" popup that shows "Processing Vulkan shaders (xx%)" but after that finishes Steam thinks the game is running (The "Play" button changes to "Stop") but nothing appears. Now if I switch back to Proton 7 or 8 or experimental, it also seems to start, switching the "Play" button to "Stop" ... but no game window appears.

## Reproduction

Install steam on Fedora 38 using RPMFusion RPM, then start Steam, install RDR2, and click "Play".

**Comment by kisak-valve** [comment]
Hello @jwakely, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-1645564906.

**Comment by jwakely** [comment]
OK thanks. I did see that issue but the comments seemed to be about different problems, and I didn't realise you want all RDR2 issues in the one ticket. Thanks for moving it!
