### ISSUE TITLE
Issue that cant be fixed on every proton version

### ISSUE THREAD

**Issue by bebrik1332** [ValveSoftware/Proton#6947]
# Compatibility Report
- Name of the game with compatibility issues:Among us and every other proton game
- Steam AppID of the game:945360

## System Information
- GPU: GT 1030 ITX 2 GB
- Driver/LLVM version: 535 nvidia
- Kernel version: 5.19.0-46-generic
- Link to full system information report: https://gist.github.com/bebrik1332/7d66d2e68d9b165fdbbc7f6f7ad73ead
- Proton version: every, mainly 8.0.2
- OS: Ubuntu 22.0.4.2 LTS
- [ Y] that I haven't found an existing compatibility report for this game.
- [ Y] that I have checked whether there are updates for my system available.

proton logs dont generate and game is stuck at vulcan shader

**Comment by bebrik1332** [comment]
edit: Mesa llvmpipe (LLVM 15.0.7, 256 bits)

**Comment by kisak-valve** [comment]
Hello @bebrik1332, the NVIDIA proprietary driver requires that the video driver's running kernel module, 32 bit userspace libraries, and 64 bit userspace libraries are all installed and exactly the same version to work properly.

`llvmpipe` in your system information is telling you at least the 32 bit userspace libraries are missing and it's being forced to use mesa's faster CPU renderer to run Steam at all..

I'm guessing that the Ubuntu Core note at https://gist.github.com/bebrik1332/7d66d2e68d9b165fdbbc7f6f7ad73ead#file-gistfile1-txt-L37 means that you're using Canonical's Steam in Snap packaging, and that's currently broken or incompatible with the NVIDIA driver you have installed on the host system. This is most likely a Steam-in-Snap issue, not a Proton issue.

Having written that, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by bebrik1332** [comment]
ok, thank you!

**Comment by bebrik1332** [comment]
and steam runtime diagnostics just stuck at collecting system info

**Comment by bebrik1332** [comment]
ill try to download steam for official website

**Comment by bebrik1332** [comment]
so now, among us starts, but people playground with some buildings and mods stucks in launching state with proton, any way to fix it or wait when dev will think about transport ppg to linux?

**Comment by bebrik1332** [comment]
nvm it started after 5th try

**Comment by kisak-valve** [comment]
You'll want to ask the Steam in Snap package maintainers about your video driver issue in the container environment.

Closing as not a Proton issue.

**Comment by bebrik1332** [comment]
It IS Proton ISSUE, I INSTALLED OFFICIAL STEAM PACKAGE WITH DEB EXTENSION ON IT, FROM OFFICIAL SITE, AND GAMES STILL DONT LAUNCH, YOU THINK ITS FUNNY JUST TO CLOSE ISSUE WITH NO HELPING AT ALL? DID YOU KNOW THAT PEOPLE CAN SLEEP? OR YOU JUST SOULLESS BOT THAT HAVE PLACE IN HELL?
