### ISSUE TITLE
Street Fighter 6 Demo (2154900)

### ISSUE THREAD

**Issue by ErFuyl** [ValveSoftware/Proton#6948]
# Compatibility Report
- Name of the game with compatibility issues: Street Fighter 6 Demo
- Steam AppID of the game: 2154900

## System Information
- GPU: AMD Radeon Vega 7 Graphics
- Driver/LLVM version: Mesa 22.2.5-0ubuntu0.1~22.04.3
- Kernel version: 5.15.0-76-generic
- Link to full system information report as [Gist](https://gist.github.com/ErFuyl/a2cb5d43679af6df8c8f87fa92a61728/):
- Proton version: experimental-8.0-20230713
- Steam Runtime Diagnostics: [Gist](https://gist.github.com/ErFuyl/333f41232ce6f9d175f0070292e7bd27/):

## I confirm:
- [Y] that I haven't found an existing compatibility report for this game.
- [Y] that I have checked whether there are updates for my system available.

## Symptoms 
Game instantly crashes at startup

## Reproduction
Launch game

[steam-2154900.log](https://github.com/ValveSoftware/Proton/files/12134103/steam-2154900.log)

**Comment by kisak-valve** [comment]
Hello @ErFuyl, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6722#issuecomment-1646168788.
