### ISSUE TITLE
Spyro Reignited Trilogy not launching anymore

### ISSUE THREAD

**Issue by Git08hb** [ValveSoftware/Proton#6950]
# Compatibility Report
Spyro Reignited Trilogy not launching anymore
996580

## System Information
- GPU: NVIDIA 4060 ti (8 GB)
- Video driver version: 535.54.03-0ubuntu0.22.04.1
- Kernel version: 5.15.0-76-generic
- Proton version: Proton 8.0.2, Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

I'm having issues launching the game on proton experimental and 8.0.2 it just wont launch. When I click on play it's stuck on (launching) and the only thing i can do is click on cancel. I fixed this by clearing the download cache but it always logs me out of steam and I don't want to do this over and over again. Verifying the game files couldn't fix this either. I used to play it on Linux without any issues on my old hardware.

OLD HARDWARE
GPU: NVIDIA GTX 1660 SUPER
CPU: AMD Ryzen 5 3600
16 GB RAM

NEW HARDWARE/SOFTWARE
OS: Linux Mint 21.2 x86_64
Kernel: 5.15.0-76-generic
Shell: bash 5.1.16
DE: Cinnamon 5.8.4
WM: Mutter (Muffin)
CPU: AMD Ryzen 5 7600X (12) @ 4.700G (with integrated graphics)
GPU: NVIDIA 4060 ti (8GB)
32 GB RAM

**Comment by kisak-valve** [comment]
Hello @Git08hb, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3035#issuecomment-1646591042.

**Comment by Git08hb** [comment]
> Hello @Git08hb, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#3035 (comment)](https://github.com/ValveSoftware/Proton/issues/3035#issuecomment-1646591042).

I found a fix!!!

You have to kill DXVKSETUP.exe then the game will run perfectly fine!

**Comment by Git08hb** [comment]
> > Hello @Git08hb, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#3035 (comment)](https://github.com/ValveSoftware/Proton/issues/3035#issuecomment-1646591042).
> 
> I found a fix!!!
> 
> You have to kill DXVKSETUP.exe then the game will run perfectly fine!

Sorry dxsetup.exe
