### ISSUE TITLE
S.T.A.L.K.E.R Call of Pipyat

### ISSUE THREAD

**Issue by LethalManBoob** [ValveSoftware/Proton#6951]
# Compatibility Report
- Name of the game with compatibility issues: S.T.A.L.K.E.R Call of Pipyat
- Steam AppID of the game: 41700

## System Information
- GPU: RTX 3070
- Video driver version: NVIDIA 535.86.05
- Kernel version: 6.4.4-1-cachyos
- Proton version: Experimental - Bleeding Edge
- DE: Gnome 44

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
DX10 Crashes second upon starting game - crashing causes soft lock on pc input, necessitating hard shutdown.

## Reproduction
Start the game and look around.

## My notes
My logs will be presented with gamescope enabled which is identical in performance and crashing but doesnt result in the actual removal of my cursor or ability to use the keyboard.

[xray_steamuser.log](https://github.com/ValveSoftware/Proton/files/12136144/xray_steamuser.log)
[steam-41700.zip](https://github.com/ValveSoftware/Proton/files/12136145/steam-41700.zip)

**Comment by LethalManBoob** [comment]
Also DX11 Doesnt even start.

**Comment by kisak-valve** [comment]
Hello @LethalManBoob, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1174#issuecomment-1646595586.
