### ISSUE TITLE
Dwarf Fortress (975370)

### ISSUE THREAD

**Issue by SeTSeR** [ValveSoftware/Proton#6953]
# Compatibility Report
- Name of the game with compatibility issues: Dwarf Fortress
- Steam AppID of the game: 975370

## System Information
- GPU: AMD Radeon HD R7 
- Video driver version: Mesa 23.1.3
- Kernel version: 6.4.3-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/SeTSeR/c38991a662474f3a1b7309d0e22770de
- Proton version: 8.0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. Existing report for this game describes another problem.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Game crashes at start, with Proton trying to call unimplemented function, see game log at the end.

## Reproduction

Just launch the game. After a couple of minutes it crashes.

[steam-975370.log](https://github.com/ValveSoftware/Proton/files/12137137/steam-975370.log)

**Comment by kisak-valve** [comment]
Hello @SeTSeR, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6529#issuecomment-1646662423.
