### ISSUE TITLE
Balder's gate 3 Launch Issue

### ISSUE THREAD

**Issue by tarainnarelli** [ValveSoftware/Proton#6955]
# Compatibility Report
- Name of the game with compatibility issues: Balder's Gate 3
- Steam AppID of the game: 1086940

## System Information
- GPU: RTX 3070
- Video driver version: 4.6.0 NVIDIA 525.105.17
- Kernel version: PopOS 6.2.6-76060206-generic
- Link to full system information report as [Gist](https://gist.github.com/):
https://gist.github.com/tjinnarelli/eb315d46b0d503b226a8219360ad254b
- Proton version: 7.0-6

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
Hit PLay in Steam --> Launches Larian's Launcher -->  Click Play Game --> then I receive the following error 

"usage: dxdiag [/whql:off | /whql:on] [/t filename | /x filename]"
then the Larian Launcher simply close and I'm left back at the steam launcher
## Reproduction
This happens everytime when I follow the steps listed above

![Screenshot from 2023-07-22 22-56-32](https://github.com/ValveSoftware/Proton/assets/18597156/24c270ff-9180-47db-8d48-5959e3d4a696)

**Comment by kisak-valve** [comment]
Hello @tarainnarelli, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4243#issuecomment-1646830774.
