### ISSUE TITLE
Proton experimentstol useing. Ubisoft old luncher. Can’t play assassin creed syndicate

### ISSUE THREAD

**Issue by Brandonstone200** [ValveSoftware/Proton#6957]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: assassin creed syndicate 

## System Information
- GPU: 
- Video driver version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:experimental 

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.yes
- [ ] that I have checked whether there are updates for my system available.yes

## Symptoms 
U play out dated 

## Reproduction

Need Ubisoft connect 
![IMG_3262](https://github.com/ValveSoftware/Proton/assets/140339098/c146238d-56f8-4c03-9450-46ed6056cb4e)
/

**Comment by kisak-valve** [comment]
Hello @Brandonstone200, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2464#issuecomment-1646894660.
