### ISSUE TITLE
Command & Conquer Remastered Collection Fullscreen Mouse

### ISSUE THREAD

**Issue by fullmetalarmour** [ValveSoftware/Proton#6959]
# Compatibility Report
- Name of the game with compatibility issues: Command & Conquer Remastered Collection 
- Steam AppID of the game: 1213210

## System Information
- GPU: AMD ATI Radeon RX 5600
- Video driver version: mesa-23.1.4-2
- Kernel version: 6.4.4-arch1-1 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental

## I confirm:
- [ ✓] that I haven't found an existing compatibility report for this game.
- [✓ ] that I have checked whether there are updates for my system available.

## Symptoms 
Fullscreen don't work with mouse you can't move the map right and down alt+tab and alt+enter don't solve the issue.

## Reproduction
There is a workaround by setting Set Screen To Borderless Window and uncheck Contain Mouse Cursor to Window.

**Comment by kisak-valve** [comment]
Hello @fullmetalarmour, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3939#issuecomment-1646962802.
