### ISSUE TITLE
No Audio in FUEL by Asobo and Codemasters on Steam Deck

### ISSUE THREAD

**Issue by Jgr9** [ValveSoftware/Proton#6960]
# Compatibility Report
- Name of the game with compatibility issues: FUEL
- Steam AppID of the game: 12800

## System Information
- GPU: Steam Deck
- Video driver version: ?
- Kernel version: ?
- Link to full system information report as [Gist](https://gist.github.com/): ?
- Proton version: ?

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.

## Symptoms 

The game is long gone from purchase on Steam, but somebody in the game's Community reported that there's no sound in FUEL on Steam Deck.  I don't know any other details.

**Comment by kisak-valve** [comment]
Hello @Jgr9, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/906#issuecomment-1647076605.
