### ISSUE TITLE
Devil May Cry 4 Special Edition (329050)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#6961]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU:  GTX 1050 Ti
- Video driver version:  NVIDIA 535.54.03
- Kernel version:  6.3.12-200.fc38.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/FreireLevi/df5f100aefc7080d6fd32c538c2f0542
- Proton version: 8.0-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-329050.log](https://github.com/ValveSoftware/Proton/files/12156056/steam-329050.log)

## Symptoms 
When the game is set fullscreen, after close it and open again, it doesn't enter in-game anymore (Only happens when using DXVK).

## Reproduction
- Go to the game options at PC Settings;
- Set the fullscreen option to "On";
- Close the game;
- Try open it again;
- Game doesn't run anymore.

**Comment by kisak-valve** [comment]
Hello @FreireLevi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1779#issuecomment-1648830220.
