### ISSUE TITLE
Shadow Empire DLC Oceania not downloading

### ISSUE THREAD

**Issue by Vokda** [ValveSoftware/Proton#6969]
# Compatibility Report
- Name of the game with compatibility issues: Shadow Empire: Oceania
- Steam AppID of the game: 2183640

## System Information
- GPU:  GTX 1660
- Video driver version: nvidia  470.182.03-1
- Kernel version: 6.1.0-10-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Vokda/81ad3fc669fab9dc8af265927a9dc2ba
- Proton version: 6.3-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. (Not for the dlc specifically)
- [x] that I have checked whether there are updates for my system available.

## Logfile
[steam-1154840.log.zip](https://github.com/ValveSoftware/Proton/files/12176724/steam-1154840.log.zip)

## Symptoms 
The DLC is not downloaded and not installed.

## Reproduction
- Buy the DLC Shadow Empire: Oceania.
- Check for it to be downloaded and installed.
- Wait for nothing to happen.

## Additional Info:
- Reinstalling the base game (Shadow Empire) does not help.
- Clearing download cache does not help.
- Switching download region does not help. 
- Base game runs fine otherwise.

**Comment by kisak-valve** [comment]
Hello @Vokda, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4434#issuecomment-1652434280.
