### ISSUE TITLE
Street Fighter 6 (1364780) Crashes while loading matches

### ISSUE THREAD

**Issue by malucious81** [ValveSoftware/Proton#6970]
# Compatibility Report
- Street Fighter 6
- Steam AppID: 1364780

## System Information
- GPU: RX 6700XT
- Video driver version: Mesa 23.1.3
- Kernel version: 6.4.4-200
- Link to full system information report as [Gist](https://gist.github.com/malucious81/032087799e309a0004988c04e7d9b7d8)
- Proton version: 8.0-3, Experimental, GE-8-9
- Journald during crash: [Gist](https://gist.github.com/malucious81/9403832f3e2e6423e13c043a8606ead4)

## Symptoms 
Street fighter 6 is crashing when entering matches, which for me also ends up crashing my entire system. 
To describe the crash, the display goes completely black and I can still hear audio from the game. Eventually the audio stops and the system becomes unresponsive, no keyboard or mouse inputs.
I end up having to do a manual reset.

## Reproduction
- Start Street Fighter 6 and enter the Fighting Ground.
- Choose Versus 1 on 1 match.
- Select your Character or Characters and start the match.
- The game reaches the screen where the fighters can make faces at each other, but when it fades to black, the game crashes instead of loading the fighting stage.
- This crash occurs when attempting to enter an online match as well.

## Notes
- This crash does not happen EVERY time, but it never happened until the recent Street Fighter 6 update.
- I was SSH'd into the gaming system during the crash but I was still unable to issue a reboot command.

[steam-1364780.log](https://github.com/ValveSoftware/Proton/files/12179023/steam-1364780.log)

**Comment by kisak-valve** [comment]
Hello @malucious81, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6817#issuecomment-1653672056.
