### ISSUE TITLE
Severe performance issues in Multiplayer (Assetto Corsa Competizione)

### ISSUE THREAD

**Issue by tim-gromeyer** [ValveSoftware/Proton#6972]
# Compatibility Report
- Name of the game with compatibility issues: Assetto Corsa Competizione
- Steam AppID of the game: 805550

## System Information
- GPU: NVIDIA GeForce RTX 3050 Ti Laptop
- Video driver version: NVIDIA 535.86.05
- Kernel version: 6.4.4-1-default
- Link to full system information report: https://gist.github.com/tim-gromeyer/bd4d38a4fa24382d54cad98d0d1e8b15
- Proton version: Proton Experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

The Proton Log looks Pretty Interesting if you ask me

[steam-805550.log.zip](https://github.com/ValveSoftware/Proton/files/12198586/steam-805550.log.zip)

## Symptoms 

I have extreme performance issues in multiplayer. In Singleplayer I have 138 fps in average, in multiplayer 35. In both single and multiplayer, the GPU usage is at 100% and CPU is between 64 to 77% in singleplayer and 33 to 47% in multiplayer

## Reproduction

1. Use the same system as I do
2. Install it using proton experimental
3. Run it
4. select multiplayer
5. Play it
6. See the problem

**Comment by kisak-valve** [comment]
Hello @tim-gromeyer, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1420#issuecomment-1656370145.
