### ISSUE TITLE
Street Fighter 6 black screen, making desktop unusable. 

### ISSUE THREAD

**Issue by jcgit1** [ValveSoftware/Proton#6973]
# Compatibility Report
- Name of the game with compatibility issues: Street Fighter 6
- Steam AppID of the game: 1364780

## System Information
- GPU: AMD RX 7900 XTX
- Video driver version: Package: amdgpu
Version: 1:5.6.50600-1609671.22.04
- Kernel version: 6.2.0-26-generic
- Link to full system information report as [Gist](https://gist.github.com/jcgit1/412ddd7ffcbbcb6b3e865ba8586c4e03):
- Proton version: 8.9(?), Experimental 

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

[steam-1364780.log.gz](https://github.com/ValveSoftware/Proton/files/12205939/steam-1364780.log.gz)

## Symptoms 
Game crashes during Story or Training after several minutes. I've tried lowering the resolution, lowering various graphics settings from Highest to High, but it still randomly crashes. This began happening with the update that included the Rashid character.

## Reproduction
Enter Story mode, play the game. Seems to crash around 4-9 matches.
Note: Brave browser is also open and usually playing a youtube video. This is the only other thing I could think of that could be contributing?

**Comment by kisak-valve** [comment]
Hello @jcgit1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6817#issuecomment-1656511651.
