### ISSUE TITLE
Galaxy on Fire 2 Full HD (212010)

### ISSUE THREAD

**Issue by Subsonic-dev** [ValveSoftware/Proton#6975]
# Compatibility Report
- Name of the game with compatibility issues: Galaxy on Fire 2 HD 
- Steam AppID of the game: 212010

## System Information
- GPU: AMD custom GPU 0405
- Video driver version: Mesa 22.2.0 (git-17e5312102)
- Kernel version: 5.13.0-valve-36-1-neptune
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Subsonic-dev/0482395a79e7764c748dacfa92f2045a
- Proton version: 

- Proton Experimental 
- Proton 8.0-3
- Proton 7.0-6
- Proton 6.3-8
- Proton 5.13-6
- Proton 5.0-10
- Proton 4.11-13
- Proton 4.2-9
- Proton 3.16-9
- Proton 3.7-8
- Proton Hotfix
- Every version of Proton GE up to proton GE8-9

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

## Symptoms 

Despite being reported as working on protonDB with multiple versions, the game crashes after getting to the initial menu screen where you choose resolution. 

Tested on both a steam deck running stable branch and a desktop running Solus Linux. 

The strange part is the game will run with Wine using the bottles flatpak to run steam and then run the game.  

## Reproduction
1. Download Galaxy on Fire 2 from steam 
2. Launch game with default settings in either game mode (on steam deck) or desktop mode (steam deck and desktop Linux)
3. Game will let you choose a resolution 
4. Game crashes back to steam 
5. Try force using different versions of Proton and Proton GE
6. Game crashes as before 
7. Try running game in windowed mode inside the game 
8. Game crashes as before 
9. Try lowering resolution 
10. Game crashes as before

**Comment by Subsonic-dev** [comment]
Attached is the log file: 
file:///home/deck/steam-212010.log

**Comment by Subsonic-dev** [comment]
[steam-212010.zip](https://github.com/ValveSoftware/Proton/files/12206864/steam-212010.zip)

**Comment by Subsonic-dev** [comment]
Log file

[steam-212010.log](https://github.com/ValveSoftware/Proton/files/12206866/steam-212010.log)

**Comment by kisak-valve** [comment]
Hello @Subsonic-dev, these look like some lines of interest from your log:
```
err:d3dcompiler:D3DCompile2 Failed to compile shader, vkd3d result -5.
err:d3dcompiler:D3DCompile2 Shader log:
err:d3dcompiler:D3DCompile2     <anonymous>: E5017: Aborting due to not yet implemented feature: Uniform initializer.
err:d3dcompiler:D3DCompile2     <anonymous>:24:1: E5000: syntax error, unexpected KW_SAMPLER_STATE
err:d3dcompiler:D3DCompile2 
```

**Comment by Subsonic-dev** [comment]
> Hello @Subsonic-dev, these look like some lines of interest from your log:
> 
> ```
> err:d3dcompiler:D3DCompile2 Failed to compile shader, vkd3d result -5.
> err:d3dcompiler:D3DCompile2 Shader log:
> err:d3dcompiler:D3DCompile2     <anonymous>: E5017: Aborting due to not yet implemented feature: Uniform initializer.
> err:d3dcompiler:D3DCompile2     <anonymous>:24:1: E5000: syntax error, unexpected KW_SAMPLER_STATE
> err:d3dcompiler:D3DCompile2 
> ```

Yes I tried to clear the shader cache using the storage cleaner plugin and then reinstall. The only minor detail I missed from my initial reporting of this error was after I tried this it still crashed as normal using Proton GE8-9 but there was a noticeable crackling of audio before it crashes back to the steam launcher. Before I cleared the shader cache it just crashed with no sound.

**Comment by Subsonic-dev** [comment]
Small update:

I've been doing some troubleshooting and this is a weird one. Perhaps I have missed something in the below:

Over the past couple of weeks I tried different changes to see if this would cause the game to reboot. 

Changed steam deck update channel to beta (no effect)
Tried up to proton GE 8-13 (no effect)
Change game resolution (no effect)
Lower graphics quality (no effect)

At this point I went back to my desktop which running Solus Linux has a known issue where you must disable LSI (linux steam integration) which I had already done, but went back to check it was off (which it was). After this I reinstalled steam and the game was working again! So not the Linux wide issue I initially thought. 

I then tried the exact same working proton version on my steam deck but it would not work. 

Fast forward to today when I was in desktop mode and docked I tried the game to see if it would run (as I occasionally do to check and see if anything has changed) and amazingly it was running. I then closed the game, unplugged the dock and tried again with the game turning on as normal. I launched game mode to see if it was now working in there as well and it was (both docked and undocked). 

Fast forward a couple of hours and I put the deck into offline mode as I was heading out. When I rebooted the deck later in the day the game would now not boot again! Most confusing as previously in both online and offline mode it would not work. 

After testing the game will only load (with any proton version tested) with the steam deck in online mode with an active network connection. Online mode but without a connection does not load. 

I will try launching the game on my desktop PC with no network connection and see if it will run after cold booting the computer to hopefully see if this is a steam deck issue to be reported elsewhere or if this is a proton quirk.

**Comment by Subsonic-dev** [comment]
I can confirm the same behavior is encountered on my desktop PC. If there is no network connection, even with steam set to offline mode, the game will not load. Other games across both my desktop PC and steam deck do not have this issue. 

This also still happens if I go online, open the game and it runs, close the game, go offline and try to open the game again. 

There are no online features for this game.

**Comment by Subsonic-dev** [comment]
Right so I have done further testing and research. Despite getting it to work in bottles while offline and some reporting it to work offline, I consider this to be a fluke in testing as running the game on windows while offline does not work. Further research shows that for every one person saying it works offline they are many more saying it needs an internet connection (likely for DRM). 

As such I will now be closing this issue and updating my proton DB entry as this is not an issue with Proton as it is seemingly working as intended.
