### ISSUE TITLE
Thief Simulator GE 8.9

### ISSUE THREAD

**Issue by wae08** [ValveSoftware/Proton#6978]
# Compatibility Report
- Name of the game with compatibility issues: Thief Simulator
- Steam AppID of the game: 704850

## System Information
Linux Mint 21.2
- GPU: XFX RX 590
- Video driver version: Mesa 23.1.4 - kisak-mesa PPA
- Kernel version: 6.2.0-26-generic
- Proton version: GE 8.9

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

](https://mega.nz/file/Vx1XlC5A#EuSRnN4Pvj0dB-igt2VsTFt5o72muvbz3AnTxj6pokE)

## Symptoms 
Game crashes after short (somewhat random) periods of time.
been trying to receive help or ideas on Reddit etc. for a while

## Reproduction
Can sometimes force the crash by opening in-game menus, loading different maps or areas in the game world.
[steam-704850.log](https://github.com/ValveSoftware/Proton/files/12207794/steam-704850.log)

**Comment by kisak-valve** [comment]
Hello @wae08, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6668#issuecomment-1656839316.
