### ISSUE TITLE
Gears 5 freezes.

### ISSUE THREAD

**Issue by nipnipj** [ValveSoftware/Proton#6980]
Hello!
Some people says the games is playable. This is not my case. Now, I would like to report my experience with gears 5 and Proton.
When using Proton 8.0-3 or ProtonGE 8.0-12, the mage freezes itself at the first logo intro. When using Proton 7.0-6, everything runs normally till a wild random freeze appears. I could see the main menu and start the campaign, tho. I the game crashed 2 times. One in the training section (I think) and in the final seconds of the cinematic before the first chapter starts.

**Comment by kisak-valve** [comment]
Hello @nipnipj, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3042#issuecomment-1657293794.
