### ISSUE TITLE
Trove (304050) - Inventory problem

### ISSUE THREAD

**Issue by MrNessuno** [ValveSoftware/Proton#6983]
# Compatibility Report
- Name of the game with compatibility issues: Trove
- Steam AppID of the game: Trove (304050)

## System Information
- GPU: RX 580
- Video driver version: Mesa 23.0.2
- Kernel version: 6.4.6-1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton Experimental or Proton 8.0-3

## I confirm:
- [ ✓] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

[steam-304050.log](https://github.com/ValveSoftware/Proton/files/12222372/steam-304050.log)

## Reproduction
1. open the game
2. open the personal chest
3. navigate through inventory pages 

Extra info: This issue isn't happening with Proton v7

**Comment by kisak-valve** [comment]
Hello @MrNessuno, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2986#issuecomment-1659186152.
