### ISSUE TITLE
DXSETUP.exe hanging for multiple games on Proton 8.0-3 while running first time install script

### ISSUE THREAD

**Issue by reedlove** [ValveSoftware/Proton#6986]
# Compatibility Report
- Name of the game with compatibility issues: Final Fantasy VII Remake Intergrade, Rayman Legends, Overcooked, Katamari Damacy Rerolled, etc.
- Steam AppID of the game: Multiple

## System Information
- GPU: GeForce RTX 3060 Laptop, NVIDIA RTX A2000 6GB
- Video driver version: 535.54.03
- Kernel version: 5.15.0-78-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 8.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

I cannot add a proton log, as it won't log anything while DXSETUP.exe is stuck.

## Symptoms 
A growing number of games will not successfully launch under Proton 8.0-3, hanging at "Running install script (Microsoft DirectX)". The user will be stuck here indefinitely unless they kill the "DXSETUP.exe" process.

## Reproduction
1.) Install Steam
2.) Set "Run other titles with:" to "Proton 8.0-3" located under the "Compatibility" section of "Steam Settings".
3.) Try launching a game that requires the DirectX runtime.

Games will continue to launch after killing DXSETUP.exe, however, I have not tested to see if the runtime was actually installed correctly.

Let me know if you need more information.

Thanks.
-Reed

**Comment by kisak-valve** [comment]
Hello @reedlove, closing #6912 to repost the same issue again could be considered a form of abuse of the issue tracker, and is non-productive.

Having written that, it's fairly clear now that there's some kind of NVIDIA driver specific issue happening here and there's better details on this at #6859.

Closing as duplicate.

**Comment by reedlove** [comment]
I wasn't trying to be abusive. In my original report, I thought that the scope was limited, but as I've experimented more it appears that it is a bigger issue. I closed my original report to file another one to better articulate the broader issue at hand. If it's more than likely related to an NVIDIA driver issue, why was that not linked to the original post?

**Comment by reedlove** [comment]
Also, if multiple have come to discover the same issue that I have, wouldn't it be prudent to leave this post up, making it easier to find a trail to the issue report you've linked me to above?

**Comment by kisak-valve** [comment]
Fragmenting the discussion of an issue across multiple issue reports just makes it harder to keep track of information. Feel free to add your findings to #6859.

**Comment by reedlove** [comment]
@kisak-valve I promise that I'm not trying to be difficult, but I truly believe that these are NOT the same thing.

**Comment by reedlove** [comment]
@kisak-valve thanks
