### ISSUE TITLE
Thank you Ubiconnect Fix today but there is another problem

### ISSUE THREAD

**Issue by frontal7** [ValveSoftware/Proton#6987]
the game does not end normally, so I have to forcefully close it, but the ubisoft connect is not saved, so I always have to re-enter the password when reconnecting to Assassincreeds Black Flag or Unity.
![20230802_041103](https://github.com/ValveSoftware/Proton/assets/141180262/469ec3b6-f048-4ce8-9ae1-476914fe97c8)

**Comment by kisak-valve** [comment]
Hello @frontal7, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1733#issuecomment-1661113497. Feel free to also leave a note on #1789 if it makes sense.
