### ISSUE TITLE
Red Dead Redemption 2 doesn't start (1174180)

### ISSUE THREAD

**Issue by Feinschmecker1** [ValveSoftware/Proton#6988]
# Compatibility Report
- Red Dead Redemption 2
- 1174180

## System Information
- GPU: NVIDIA Corporation NVIDIA GeForce RTX 3060/PCIe/SSE2
- Video driver version: 4.6.0 NVIDIA 535.86.05
- Kernel version: 4.6
- Gist: https://gist.github.com/Feinschmecker1/3af54fa82593b362c387cf525b19be50
- Proton version: 8.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
I have a problem with Red Dead Redemption 2.
Until recently (approx. 2 weeks) the game worked perfectly. But now there is a problem as soon as I start the game. Namely, when I press play, the Rockstar Launcher loads initially. But then it dies in the middle of the loading process and the play button says "running" or something. This means that the game should now be normally on, but I don't see anything.

**Comment by kisak-valve** [comment]
Hello @Feinschmecker1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-1662169099.
