### ISSUE TITLE
Built -in browser issues with LOTRO store (212500) - steamdeck

### ISSUE THREAD

**Issue by james2432** [ValveSoftware/Proton#6991]
# Compatibility Report
- Name of the game with compatibility issues:Lord of the rings Online
- Steam AppID of the game:212500

## System Information
- GPU: steamdeck
- Video driver version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
https://gist.github.com/james2432/61646a6a8894f0ea8cbf921b75e5b9f9

- Proton version:Proton experimental 8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-212500.log](https://github.com/ValveSoftware/Proton/files/12251266/steam-212500.log)

## Symptoms 
No content loads from store

## Reproduction
Login
Open Lotro store on charater creation screen or in game with big gold coin
whatch content not load fully

**Comment by kisak-valve** [comment]
Hello @james2432, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1816#issuecomment-1663993331.
