### ISSUE TITLE
Stranded: Alien Dawn does not capture mouse cursor

### ISSUE THREAD

**Issue by rhagu** [ValveSoftware/Proton#6992]
# Compatibility Report
- Name of the game with compatibility issues: Stranded: Alien Dawn
- Steam AppID of the game: 1324130

## System Information
- GPU: RX 6700 XT
- Video driver version: Mesa 23.0.4
- Kernel version: 6.4.6-1
- Link to full system information report :  [Gist](https://gist.github.com/rhagu/d705a03f39c2f4c92341f34a66f88156) 
- Proton version: 8.0-3
- Gnome Version: 44.3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
- I can start the game, but once I see the main menu, the game is not able to "capture" my mouse cursor
- It still has the cursor icon of Gnome and does not change to the in game cursor
- When I try to click, the click is executed in a window in the background ( let it be a browser or file manager or whatever)
- This was not always the case and has changed about a month ago
- I had a look at journalctl output and found this: [Gist](https://gist.github.com/rhagu/24667424c6ab95d08c73268668aa1dd1) I am not sure if it is related though

## Reproduction
- Start Stranded: Alien Dawn on a Manjaro Gnome install
- Wait until you reach the main menu and click with your mouse

[steam-1324130.zip](https://github.com/ValveSoftware/Proton/files/12261191/steam-1324130.zip)

**Comment by rhagu** [comment]
I think I misunderstood the compatibility report question, how do I rewrite this as a bug?

**Comment by kisak-valve** [comment]
Hello @rhagu, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6577#issuecomment-1665642785.

**Comment by rhagu** [comment]
@kisak-valve  thank you very much
