### ISSUE TITLE
Binding of Isaac Repentance, Bombing/Making Stone bridges crashes game on Proton 8.0.3/Experimental but not proton 7.0.x

### ISSUE THREAD

**Issue by KoboDev** [ValveSoftware/Proton#6994]
# Compatibility Report
- Binding of Isaac Repentance
- Steam AppID of the game :250900

## System Information
- GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
- Video driver version: raven2, LLVM 15.0.7, DRM 3.52, 6.4.7-arch1-2
- Kernel version: 6.4.7-arch1-2
- Link to full system information report as [Gist](https://gist.github.com/KoboDev/ca3aeb6ba9b59c5a5198d8e6b1f79e1a):
- Proton version: 8.0.3 & Experimental (as of 8/4/2023)

## I confirm:
- [Y] that I haven't found an existing compatibility report for this game.
- [Y] that I have checked whether there are updates for my system available.

## Proton Log
[steam-250900.log](https://github.com/ValveSoftware/Proton/files/12262928/steam-250900.log)

## Symptoms 
Game Crashes whenever placing down an bomb near an rock that creates an bridge.

## Reproduction
1. Select Proton 8.0.3 or Experimental
2. Launch game, play until you got an good save file (This happens randomly but often.)
3. Find an spot that requires an bridge with a bomb.
4. CRASH!

**Comment by kisak-valve** [comment]
Hello @KoboDev, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4868#issuecomment-1666059218.
