### ISSUE TITLE
DOS 2 definitive edition doesn't start on steam deck

### ISSUE THREAD

**Issue by sumilinux** [ValveSoftware/Proton#6997]
# Compatibility Report
- Name of the game with compatibility issues: Divinity Original Sin 2 Definitive edition 
- Steam AppID of the game: 435150

## System Information
- GPU: 
- Video driver version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:  experimental/ 8.0-3

## I confirm:
- [ ✓] that I haven't found an existing compatibility report for this game.
- [ ✓] that I have checked whether there are updates for my system available.

## Symptoms 
Game crashes on startup. I see a black screen and then the game exists. 
Tried with different proton version like experimental,8.0-3 7.0-6. Crashes in both regular and desktop mode

**Comment by kisak-valve** [comment]
Hello @sumilinux, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/413#issuecomment-1666866172.

**Comment by sumilinux** [comment]
Sure. This games shows up  as deck compatible with a green tick on protondb. Dont know what got broken here.
