### ISSUE TITLE
Makai Kingdom: Reclaimed and Rebound (1732060)

### ISSUE THREAD

**Issue by ipr** [ValveSoftware/Proton#6998]
# Compatibility Report
- Name of the game with compatibility issues:Makai Kingdom: Reclaimed and Rebound
- Steam AppID of the game:1732060

## System Information
- GPU: AMD Vega 56/64
- Video driver version:Mesa 23.1.4
- Kernel version: 6.4.8
- Proton version:8.0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Proton 8.0 has a regression that the game does not start. You see window opening but game closes quickly after it.

With Proton 7.0 you can get into game so something in 8.0 has regressed.

## Reproduction
1. start game
2. note game window opening and closing

[steam-1732060.log](https://github.com/ValveSoftware/Proton/files/12285645/steam-1732060.log)

**Comment by alasky17** [comment]
@ipr Thank you for the report!  This is indeed a clear-cut regression and we will investigate :)

**Comment by alasky17** [comment]
@ipr This is now fixed in experimental-8.0-20230817.  Thank you again for the report :)

**Comment by ipr** [comment]
> @ipr This is now fixed in experimental-8.0-20230817. Thank you again for the report :)

Thanks for the fix :) 
Confirmed working with experimental
