### ISSUE TITLE
Command & Conquer: Red Alert 3 (17480)

### ISSUE THREAD

**Issue by RobertoAlexis** [ValveSoftware/Proton#7001]
# Compatibility Report
- Name of the game with compatibility issues: Red alert 3
- Steam AppID of the game: 17480

## System Information
- GPU: Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display 
- Video driver version:  Mesa 23.0.4
- Kernel version: 6.2.0-26-generic
- Link to full system information report as ([Gist](https://gist.github.com/):) [Gist](https://gist.github.com/RobertoAlexis/f4dbfc9ae8ecad9b5b31960a9153d5a3)
- Proton version: Proton 7, Proton 8 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

When the game launch window appears, a message appears saying that directx 9 is not installed, even though it is. This happened after the steam client update.

## Reproduction
Start the game but then when the loading window appears it closes with a message saying that directx 9 is not installed.
[steam-17480.log](https://github.com/ValveSoftware/Proton/files/12308508/steam-17480.log)

**Comment by kisak-valve** [comment]
Hello @RobertoAlexis, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6800#issuecomment-1673054087.
