### ISSUE TITLE
Can i report non steam game ?

### ISSUE THREAD

**Issue by xDoge26** [ValveSoftware/Proton#7002]
> allows games which are exclusive to Windows to run on the Linux operating system.

If i want to run gog version of a game that isnt available on steam for whatever reason, can i report it here if it doesnt work with proton ?

**Comment by kisak-valve** [comment]
Hello @xDoge26, yes, in general, we're using compatibility reports to track feedback on a per game basis regardless of where they came from. While the main focus is on games from the Steam storefront, this issue tracker is not summary restricted that.

It should be noted that Proton is still expected to be run from Steam. If third party tools have pulled in Proton and you're having trouble there, then that's something to be pondered with the other compatibility tool manager.
