### ISSUE TITLE
Quake 2 remaster.

### ISSUE THREAD

**Issue by korelabs** [ValveSoftware/Proton#7005]
# Compatibility Report
- Name of the game with compatibility issues: QUake 2 (remaster)
- Steam AppID of the game: 2320

## System Information
- GPU: 6900XT, I also have a tesla M40 inactive as nvenc/cuda.

- Video driver version: Driver Version: 4.6 (Compatibility Profile) Mesa 22.3.6

- Kernel version: 6.4.8-x64v3-xanmod1

- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/korelabs/74c55c11c24dc97beb08659224cdef48

 
- Proton version: experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game. 
- [X] that I have checked whether there are updates for my system available.

  
Attached.

## Reproduction
Load game on any proton version, on either GPU, same results.

[steam-2320.log](https://github.com/ValveSoftware/Proton/files/12322265/steam-2320.log)
[CRASHLOG.TXT](https://github.com/ValveSoftware/Proton/files/12322272/CRASHLOG.TXT)

**Comment by kisak-valve** [comment]
Hello @korelabs, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1410#issuecomment-1675099220.
