### ISSUE TITLE
Madden 24 SteamDeck

### ISSUE THREAD

**Issue by KingTMando** [ValveSoftware/Proton#7018]
I downloaded the game early so I could play early and the game looks like it’s going to start up and I just get a black screen. Not sure why but would like to help.
![Uploading IMG_6970.jpeg…]()

**Comment by kisak-valve** [comment]
Hello @KingTMando, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7016#issuecomment-1679460273.
