### ISSUE TITLE
Civilization VI: degraded multiplayer performance

### ISSUE THREAD

**Issue by sandervalcke** [ValveSoftware/Proton#7019]
# Compatibility Report
- Name of the game with compatibility issues: Sid Meier’s Civilization VI
- Steam AppID of the game: 289070

## System Information
- GPU: AMD Radeon RX 6800 XT
- Video driver version: Mesa 23.1.5
- Kernel version: 6.1.44-1-MANJARO (also tried 6.4)
- Link to full system information report as [Gist](https://gist.github.com/sandervalcke/45b54c6ca283ef6e6d0ca3b9d010343b)
- Proton version: Experimental or 8.0-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

With proton 7, 8 or experimental, my online FPS tanks, going up and down between 5 and 20. Using 6.3-8 I don't have this issue, a steady 100+. Offline play doesn't have this issue, works flawlessly in all of these versions. Issue is already present when creating an internet game with only computer opponents.

## Reproduction

Whether the issue is present can already be seen from the game creation lobby: 

Multiplayer > Internet > Create Game > Confirm Settings

with newer versions of proton my FPS is at 30 or below here, the animated background is jittery. With 6.3-8 FPS is 60-70 and everything is smooth. Actually proceeding to in-game the FPS will be even worse.

**Comment by kisak-valve** [comment]
Hello @sandervalcke, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4068#issuecomment-1679632518.
