### ISSUE TITLE
Orcs Must Die 1 & 2 C++ Runtime Error R6025

### ISSUE THREAD

**Issue by Shannibelle** [ValveSoftware/Proton#7020]
# Compatibility Report
- Name of the game with compatibility issues: Orcs Must Die 1 & 2
- Steam AppID of the game: 102600 201790

## System Information
- GPU: nvidia GTX 1060
- Video driver version: nvidia 535.98
- - System Info: https://gist.github.com/Shannibelle/81d9192c496bfae1c7ce1788ff52466a
- Kernel version: 6.4.9-arch1-1

- Proton version: Proton Experimental (tried all available versions)

## I confirm:
- [* ] that I haven't found an existing compatibility report for this game.
- [ *] that I have checked whether there are updates for my system available.

[steam-201790.log](https://github.com/ValveSoftware/Proton/files/12354271/steam-201790.log)

## Symptoms 
Game has run fine for years under Wine/Proton. After recent Steam Client and Runtime updates the game will crash on Launch with C++ Runtime error R6025 
![Screenshot_2023-08-14_16-33-16](https://github.com/ValveSoftware/Proton/assets/142366834/c011d7e2-c72c-44a5-b09b-ced2aeaf6eda)

**Comment by kisak-valve** [comment]
Hello @Shannibelle, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/398#issuecomment-1680531634.
