### ISSUE TITLE
S&box ToType error (sandbox gamemode)

### ISSUE THREAD

**Issue by zBomb12** [ValveSoftware/Proton#7024]
when i load in to the sandbox game there's error it says "ToType - please add ability to sandbox curvel"

**Comment by kisak-valve** [comment]
Hello @kuba64534, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4940#issuecomment-1683856395.
