### ISSUE TITLE
Dead by Daylight EAC Not Initiallize

### ISSUE THREAD

**Issue by wuilmerj24** [ValveSoftware/Proton#7028]
# Compatibility Report
- Name of the game with compatibility issues: Dead by Daylight
- Steam AppID of the game:381210

## System Information
- GPU: Integrated ryzen 7 5700G
- Video driver version: `OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.0-devel`
- Kernel version: `6.1.0-11-rt-amd64`
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: `8.0`

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
When I open Dead by Daylight, I can play with the bots, but when I play online, it reaches the lobby, but upon loading the game, it disconnects me.

## Reproduction

always

**Comment by kisak-valve** [comment]
Hello @wuilmerj24, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/519#issuecomment-1685275049.
