### ISSUE TITLE
Compatibility on macOS M2 Pro

### ISSUE THREAD

**Issue by wuilmerj24** [ValveSoftware/Proton#7029]
# Compatibility Report
- Name of the game with compatibility issues:Dead by Daylight or other games only for window
- Steam AppID of the game: I can only install games that are compatible with native Macs.

## System Information
- GPU: M2 pro 16 T
- Video driver version: not info.
- Kernel version: Mac os 13.2.1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: not compatobility

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
Is Proton compatible with macOS and with M2 Pro processor?

**Comment by kisak-valve** [comment]
Hello @wuilmerj24, Proton is not compatible with macOS. This is being tracked at #1344.

Closing as a duplicate.
