### ISSUE TITLE
God of War crashes when Alt Tabbing

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#7037]
# Compatibility Report
- Name of the game with compatibility issues: God of War
- Steam AppID of the game: 1593500

## System Information
- GPU: RX 6700XT
- Video driver version: Mesa 23.1.5-2
- Kernel version: 6.1.44-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/coreybruce/3a7dd24ead8b58d8b85b4f94f5906a58
- Proton version: 8.0-3

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

Proton Log: https://raw.githubusercontent.com/coreybruce/Bulk-logs/main/steam-1593500.log

## Symptoms 
Game will crash if you alt tab from the game and it will always crash

![Screenshot from 2023-08-22 23-20-24](https://github.com/ValveSoftware/Proton/assets/8393780/286ae8d1-9589-445f-8ecd-8014f6236309)

## Reproduction
Alt tab off game and go back

**Comment by kisak-valve** [comment]
Hello @coreybruce, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5511#issuecomment-1688249751.
