### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7038]
Proton 8.0-3

Mudrunner: The game is randomly closing at random times.
And the initial opening screen has brakes.
![Mudrunner](https://github.com/ValveSoftware/Proton/assets/141298203/af46fb01-387f-4d73-9ac0-13cb5670940c)

Efootball: the game closes when reaching the field configuration, initial menu, such as weather etc.
It is also not possible to use the joystick to confirm an option in the warning, before opening the game.
![Efootball](https://github.com/ValveSoftware/Proton/assets/141298203/56b96636-8e78-4374-b1ee-5f84c7a255b7)

It also generated this report in the system clipboard:
LowLevelFatalError [File:Unknown] [Line: 907] 
Rendering thread exception:
LowLevelFatalError [File:Unknown] [Line: 339] 
Direct3DDevice->CreateTexture3D(&TextureDesc, SubResData,TextureResource.GetInitReference()) failed 
 at G:\Enlighten\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Texture.cpp:1172 
 with error E_INVALIDARG, 
 Size=1280x95x5 PF=3 Format=DXGI_FORMAT_R8_UNORM(0x0000003D), NumMips=1, Flags=D3D11_BIND_SHADER_RESOURCE D3D11_BIND_UNORDERED_ACCESS , Usage:0x0, CPUFlags:0x0, MiscFlags:0x0, SampleCount:0x0, SampleQuality:0x0, SubresPtr:0x0000000079760000, SubresPitch:1280, SubresSlicePitch:121600

Burnout paradise remastered: the ea play screen does not show any information.
ea play opens twice before opening the game.
When you open the game, it closes right away after a few seconds, on the first screen. Then it reopens and play, without information and closes.
At random times, the big picture restarts before showing the last screen of ea play.
![eaplay2](https://github.com/ValveSoftware/Proton/assets/141298203/d3f5cfb4-7f99-435c-9886-d97994ac36b6)
![eaplay3](https://github.com/ValveSoftware/Proton/assets/141298203/8eec2d54-9f43-444f-850e-b4c1b05410b8)
![big](https://github.com/ValveSoftware/Proton/assets/141298203/10d38eff-e3ad-4182-a67a-25964230569a)

Fishing planet: sometimes, did not start on the first try, but started on the second or third

kubuntu lts
all updated
official steam, .deb
Intel i3 1115G4

swap 47GB+

Thanks

**Comment by kisak-valve** [comment]
Hello @QueDemais, these issues have to be evaluated on a per-game basis, and we're using one issue report per game title. Mashing feedback for random games together is an untrackable mess.

Feel free to add notes with your findings to the various compatibility reports for these games: #1532 #5187 #3960

Fishing Planet has a native linux variant which should be used by default. Feedback on native linux games should be reported directly to the game's dev(s). If you've explicitly told Steam to use Proton with that game, then please open a new compatibility report focusing on only that game.

**Comment by ghost** [comment]
Ok, thank you Kisak
