### ISSUE TITLE
Codecs

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7040]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

**Comment by kisak-valve** [comment]
Hello @QueDemais, this feature request is already being tracked at #1464. Closing as a duplicate.

**Comment by ghost** [comment]
ok, thanks Kisak, success for you there.  👍
