### ISSUE TITLE
MARVEL SNAP (1997040)

### ISSUE THREAD

**Issue by SBR2022** [ValveSoftware/Proton#7051]
# Compatibility Report
- Name of the game with compatibility issues: Marvel Snap
- Steam AppID of the game: 1997040

## System Information
- Memory: 6,0 GiB
- Processor: Intel Core | 3-4160 x 4
- GPU: Intel HD Graphics 4400 (HSW GT2)
- Video driver version: 4.6 (Compatibility Profile) Mesa 23.1.6 - kisak-mesa PPA
- Kernel version: Linux 6.2.0-27-generic
- Proton version: Proton Experimental (I also tried the others versions availables)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1997040.log](https://github.com/ValveSoftware/Proton/files/12446641/steam-1997040.log)

## Symptoms 
Game opens, but after a delay of 4 to 8 seconds it automatically closes.

**Comment by kisak-valve** [comment]
Hello @SBR2022, Proton 8.0 and newer requires that the Vuikan drivers for your video driver provide Vulkan 1.3. Your video driver provides a spec incomplete implementation of Vulkan 1.2, which is causing DXVK to fail to initialize. https://gitlab.freedesktop.org/mesa/mesa/-/issues/7827#note_1672395 has more fine grained details on why.

Sorry, but the incomplete implementation of Vulkan makes your system unsupportable in general. You may get lucky using Proton 7.0 or older since the driver requirements are lower.

**Comment by kisak-valve** [comment]
As an extra detail, I think that your Proton log is saying that it failed to use any Vulkan driver, not that it failed the minimum requirements for DXVK in Proton Experimental. I would check that the `mesa-vulkan-drivers` packages are installed with something like `apt policy mesa-vulkan-drivers mesa-vulkan-drivers:i386`, and if they're not installed, then installing them would let Proton try harder to run the game before failing with the previously mentioned minimum requirement note.

You can also try running the game with the game's launch options set to `PROTON_USE_WINED3D=1 %command%` to tell Proton to use wine's DirectX to OpenGL render path, but that runtime option comes with a significant performance penalty and is not considered supported.

**Comment by SBR2022** [comment]
> As an extra detail, I think that your Proton log is saying that it failed to use any Vulkan driver, not that it failed the minimum requirements for DXVK in Proton Experimental. I would check that the `mesa-vulkan-drivers` packages are installed with something like `apt policy mesa-vulkan-drivers mesa-vulkan-drivers:i386`, and if they're not installed, then installing them would let Proton try harder to run the game before failing with the previously mentioned minimum requirement note.

I got a similar error when trying to download a game through Lutris even though I installed Vulkan long before that... Also checked what you mentioned and the terminal gave me the following response:

```
mesa-vulkan-drivers:
  Installed: 23.1.6~kisak1~l
  Candidate: 23.1.6~kisak1~l
  Version table:
 *** 23.1.6~kisak1~l 500
        500 https://ppa.launchpadcontent.net/kisak/kisak-mesa/ubuntu lunar/main amd64 Packages
        100 /var/lib/dpkg/status
     23.0.4-0ubuntu1~23.04.1 500
        500 http://br.archive.ubuntu.com/ubuntu lunar-updates/main amd64 Packages
     23.0.2-1ubuntu1 500
        500 http://br.archive.ubuntu.com/ubuntu lunar/main amd64 Packages
mesa-vulkan-drivers:i386:
  Installed: 23.1.6~kisak1~l
  Candidate: 23.1.6~kisak1~l
  Version table:
 *** 23.1.6~kisak1~l 500
        500 https://ppa.launchpadcontent.net/kisak/kisak-mesa/ubuntu lunar/main i386 Packages
        100 /var/lib/dpkg/status
     23.0.4-0ubuntu1~23.04.1 500
        500 http://br.archive.ubuntu.com/ubuntu lunar-updates/main i386 Packages
     23.0.2-1ubuntu1 500
        500 http://br.archive.ubuntu.com/ubuntu lunar/main i386 Packages
```
> You can also try running the game with the game's launch options set to PROTON_USE_WINED3D=1 %command% to tell Proton to use wine's DirectX to OpenGL render path, but that runtime option comes with a significant performance penalty and is not considered supported.

Before reporting the problem I had tested this command by suggestion of [protondb](https://www.protondb.com/app/1997040) but unfortunately there is no result
