### ISSUE TITLE
Low FPS in game (Elden Ring) but solid 60 FPS in OBS.

### ISSUE THREAD

**Issue by curbthepain** [ValveSoftware/Proton#7052]
I am getting low FPS in Elden Ring. No matter the settings it runs poorly once I start doing stuff. But lets say I go record my gameplay with OBS. The preview and the recording are both a rock solid 60 fps. But on the actual screen its playing to it drops loads of frames. This low FPS continues whether I'm recording or not. I've yet to test out other recording software to see but I'm pretty confident its a Proton issue.

My specs: 5600x, X570A Pro MSI,1080 Ti, 16GB 3200mhz
Desktop Env/OS: Linux Mint 21.2, X11/Xorg, Cinnamon, Gdm3
GPU Driver: 535.86.05

**Comment by kisak-valve** [comment]
Hello @curbthepain, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1694656952.
