### ISSUE TITLE
Onimusha: Warlords (761600)

### ISSUE THREAD

**Issue by ffrasisti** [ValveSoftware/Proton#7053]
# Compatibility Report
- Name of the game with compatibility issues: Onimusha: Warlords
- Steam AppID of the game: 761600

## System Information
Steam Deck 256GB
Stable
- Proton version: 8, 7, Experimental,

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game crashes on opening new game or loading a save
Video cutscenes stuck on black screen. 

**However, game works flawlessly (without prerendered videos) on Proton  5.13-6 MAKING THIS A _REGRESSION_**

If the  5.13-6 behaviour can be put into current proton, the game would immediately be ready for playable state. A fix for the prerendered cutscenes (even though there's very few of them) would make it an instant verified.
On 5.13-6 Prerendered videos get autoskipped.

## Reproduction
Open game, attempt to start a a new game.

**Comment by kisak-valve** [comment]
Hello @ffrasisti, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3391#issuecomment-1694821397.
