### ISSUE TITLE
Multiple Games Failing to Launch

### ISSUE THREAD

**Issue by Aerodin** [ValveSoftware/Proton#7055]
I have been wrestling with this issue for 2 weeks.  What confuses me is that my non-Steam games whether native Linux games, via Lutris, Minecraft etc. all work great with zero issues.  It's only in Steam that this issue is occurring so I don't think it's my graphics card like I originally thought.

Things I have tried: 
1.) Switching between Snap, Flatpak, Ubuntu Steam, and steam directly from the Steam website
2.) swapping between AMD GPU drivers, Oibaf PPA, and stock drivers

Mixed success.  Sometimes the games will run but more often than not they do not.  I am unable to figure out exactly where the issue is so I'm making this thread to help trouble shoot this.  

Sometimes Counter-Strike works and other games won't and I'm trying to narrow down where the issue is.

# Compatibility Report
Counter-Strike: Global Operations, Forza Horizon 5, Jagged Alliance 3

## System Information
Steam => System Information output
https://gist.github.com/Aerodin/eec494a560dd7e4460ad778e1965026e

Steam => Runtime System Information
https://gist.github.com/Aerodin/905731acff3f557d926d4f3f4b0cdfee

## I confirm:
I found a bunch of different logs including the steam/logs as well as console.log via -condebug.  Just let me know which ones you want to see and for which game and I can show those.

(Proton logs compress well if needed.)-->

## Symptoms 
Games crash immediately on launch from Steam app.  Also occurs if I try to launch it from the menu as well.

## Reproduction
CSGO:
Jagged Alliance 3:
Forza Horizon 5:

**Comment by kisak-valve** [comment]
Hello @Aerodin, Vulkan is broken in general on your system https://gist.github.com/Aerodin/905731acff3f557d926d4f3f4b0cdfee#file-gistfile1-txt-L96-L111 / https://gist.github.com/Aerodin/905731acff3f557d926d4f3f4b0cdfee#file-gistfile1-txt-L265-L284

Unless you have a better hint, this is a mesa issue, not a Proton issue like https://gitlab.freedesktop.org/mesa/mesa/-/issues/9585 or https://gitlab.freedesktop.org/mesa/mesa/-/issues/9692.
