### ISSUE TITLE
Civilization 4

### ISSUE THREAD

**Issue by williamodavis** [ValveSoftware/Proton#7058]
# Compatibility Report
- Name of the game with compatibility issues: Sid Meiers Civilization 4 and all DLCs
- Steam AppID of the game: ?

## System Information
- GPU:  Integrated Intel UHD Graphics
- Video driver version:  No clue
- Kernel version:  no clue
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game launches fine, but no mouse clicks are detected. Keyboard and mouse movement input works fine, though.

## Reproduction
Just launch the game

**Comment by kisak-valve** [comment]
Hello @williamodavis, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4547#issuecomment-1698290472.
