### ISSUE TITLE
Tetris Effect: Connected - Won't Launch

### ISSUE THREAD

**Issue by k-e-i-z-a-i** [ValveSoftware/Proton#7060]
# Compatibility Report
- Name of the game with compatibility issues: Tetris Effect: Connected 
- Steam AppID of the game: 1003590

## System Information
- GPU: NVIDIA GeForce RTX 3060 Ti
- Video driver version: 4.6.0 NVIDIA 535.104.05
- Kernel version: 6.4.6-76060406-generic
- Link to full system information report as Gist: [Link](https://gist.github.com/k-e-i-z-a-i/13b3ecb30895efe94b054bc4aea62e54)
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Game is unable to fully launch. Only shows as "Running" but the game never launches. I have attempted multiple different versions of Proton and adding "SteamDeck=1" to the launch options (as recommended by a user on ProtonDB) with no lasting success.

Oddly enough, the game did launch once and I was able to play it. The next day, the problem had returned despite the fact I made no modifications to the setup. I've read elsewhere of user complaining that the game has to be launched several times before successfully launching. Despite this, I've only ever gotten it to work the one time.

## Reproduction

1. Launch game
2. Choose ' Play Etris: Effective: Connected' from among the three launch options (none of the three work) and click 'Play'.
3. In the sidebar, the game will go from 'Launching' to 'Running' but nothing ever launches.

[steam-1003590.log](https://github.com/ValveSoftware/Proton/files/12479578/steam-1003590.log)

**Comment by kisak-valve** [comment]
Hello @k-e-i-z-a-i, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5084#issuecomment-1699750514.
