### ISSUE TITLE
Serious Engine Games Regression with latest Proton Experimental

### ISSUE THREAD

**Issue by kodatarule** [ValveSoftware/Proton#7061]
# Compatibility Report 
- Name of the game with compatibility issues: Serious Sam Fusion, Serious Sam 4, Serious Sam Siberian Mayhem, basically most serious sam and talos principle games

## System Information
- GPU: RTX 3090
- Video driver version: 535.104.05
- Kernel version: 6.5.0-273-tkg-bore-eevdf 
- Link to full system information report as [Gist](https://gist.github.com/):  https://gist.github.com/kodatarule/2117cf172b2da8a09e09b6ddb914da48
- Proton version: latest experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
The games run at 30-40fps, with proton 8.0-3 it's fine.

[steam-564310.log](https://github.com/ValveSoftware/Proton/files/12488512/steam-564310.log)

**Comment by Ennea** [comment]
This appears to affect Unity games, too. Both Valheim and Shadow Gambit run noticeably slower (down to ~60-70 frames per second in Shadow Gambit, as opposed to a very stable 165 – which is my refresh rate – otherwise).

I got an RTX 3080, driver version 535.104.05 as well, Linux kernel 6.4.12.

**Comment by ShaqibK** [comment]
Can confirm this issue in naraka bladepoint. Gpu power usage dropped significantly and frame rates are now 30-40 from 165. Using any other version fixed the issue. 
6800h+3070ti mobile running endeavour os fully updated.

**Comment by Blisto91** [comment]
Hi there. Could i get you to try a quick test?
Copy the dll files from `~/.steam/steam/steamapps/common/Proton 8.0/dist/lib64/wine/dxvk/` and paste them in to `~/.steam/steam/steamapps/common/Proton - Experimental/files/lib64/wine/dxvk/` overwriting the files already present. Then test if there is still a performance drop on Experimental. 

Once you are done you can search for "Proton Experimental" in your Steam library -> right click on it and select "Properites" -> select the "Installed Files" tab -> Click "Verify integrity of tool files".
This should bring back Experimental to it's proper state.

**Comment by Ennea** [comment]
@Blisto91 Yup, this brings back the previous performance. A DXVK regression, then?

Edit: Looks like Philip has already taken care of this here: https://github.com/doitsujin/dxvk/commit/a3fa9c26dce09a4e21935789e4f13bb537b19021

**Comment by Blisto91** [comment]
Thank you for the report and testing. The offending commit have been found and reverted in dxvk. https://github.com/doitsujin/dxvk/commit/a3fa9c26dce09a4e21935789e4f13bb537b19021

**Comment by Blisto91** [comment]
@kodatarule Are you able to confirm the issue has been solved in current Experimental?

**Comment by kodatarule** [comment]
Yes it has been resolved now, the issue can be closed.

**Comment by Blisto91** [comment]
Cool 👍
