### ISSUE TITLE
Battlefield V crashing on map load every time with Proton Experimental 

### ISSUE THREAD

**Issue by mediocretwo** [ValveSoftware/Proton#7067]
# Compatibility Report
- Name of the game with compatibility issues: Battlefield V
- Steam AppID of the game: 1238810

## System Information
- GPU: AMD Radeon RX 5700 XT
- Video driver version: Mesa 23.1.4
- Kernel version: 6.1.38-4
- Link to full system information report as Gist: [Gist link to system info and runtime diagnostics](https://gist.github.com/mediocretwo/e045fbe42e7e28bb9073caae75fe9fcc)
- Proton version: Proton Experimental

## I confirm:
- [ * ] that I haven't found an existing compatibility report for this game.
- [ * ] that I have checked whether there are updates for my system available.

## Symptoms 
The game is freezing and completely crashing to desktop during loading screen, whenever I try to join a map (Team Death Match) or within few minutes. This issue is not occurring with Proton version 8.0.3.The logo animation on the loading screen completely freezes and after around 20-30 seconds the game fully crashes and exits to desktop. Happening on every launch, not some intermittent issue. I'm using steam as flatpak. 

## Note
The Proton log file generated was HUGE (2.1 GB) and compressing it is not enough to meet Github's 25 MB file upload limit. (The compressed file is still 120 MB). So I did not upload the log file here. Let me know how else you would like me to upload the Proton Log file.

## Reproduction
1. Install steam with flatpak (Debian 12, gnome)
2. Install Battlefield V and enable Proton Experimental in compatibility options.
3. Launch game, open Team Deathmatch in Multiplayer.
4. Select a lobby and join.
5. Game starts loading the map, then freezes for 20-30 seconds and then crashes to desktop during the loading screen animation or right after completing the loading of map.
6. Sometimes I can play for a few minutes and then the freeze occurs.
7. Happens every single time without fail.

**Comment by kisak-valve** [comment]
Hello @mediocretwo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3977#issuecomment-1703855264.
