### ISSUE TITLE
Counter-Strike 2 is receiving a VAC warning and crashing on the loading screen when launched in practice mode.

### ISSUE THREAD

**Issue by aarshparashar** [ValveSoftware/Proton#7068]
aarsh@aarsh-Mi-NoteBook-Horizon-Edition-14:~$ steam
steam.sh[14433]: Running Steam on ubuntu 23.04 64-bit
steam.sh[14433]: STEAM_RUNTIME is enabled automatically
setup.sh[14501]: Steam runtime environment up-to-date!
steam.sh[14433]: Steam client's requirements are satisfied
[2023-09-02 19:09:22] Startup - updater built Jul 28 2023 18:44:09
[2023-09-02 19:09:22] Startup - Steam Client launched with: '/home/aarsh/.steam/debian-installation/ubuntu12_32/steam' '-nominidumps' '-nobreakpad'
09/02 19:09:22 Init: Installing breakpad exception handler for appid(steam)/version(1690583737)/tid(14568)
[2023-09-02 19:09:22] Loading cached metrics from disk (/home/aarsh/.steam/debian-installation/package/steam_client_metrics.bin)
[2023-09-02 19:09:22] Using the following download hosts for Public, Realm steamglobal
[2023-09-02 19:09:22] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-09-02 19:09:22] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-09-02 19:09:22] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-09-02 19:09:22] Verifying installation...
[2023-09-02 19:09:22] Verification complete
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf08a49c0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf08a31f0
GetWin32Stats: display was not open yet, good
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[14576]: Runtime for steamwebhelper: defaulting to /home/aarsh/.steam/debian-installation/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[14576]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 18 milliseconds to initialize
/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
BRefreshApplicationsInLibrary 1: 1ms
BuildCompleteAppOverviewChange: 186 apps
RegisterForAppOverview 1: 7ms
RegisterForAppOverview 2: 7ms
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
/bin/sh\0-c\0/home/aarsh/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=730 -- /home/aarsh/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- '/home/aarsh/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/aarsh/.steam/debian-installation/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/aarsh/.steam/debian-installation/steamapps/common/Counter-Strike Global Offensive/game/bin/win64/cs2.exe' -steam -vulkan\0
chdir "/home/aarsh/.steam/debian-installation/steamapps/common/Counter-Strike Global Offensive"
ERROR: ld.so: object '/home/aarsh/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/aarsh/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/aarsh/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/aarsh/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/aarsh/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Setting breakpad minidump AppID = 730
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198047706689 [API loaded no]
Using breakpad crash handler
Setting breakpad minidump AppID = 730
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198047706689 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561198047706689
Setting breakpad minidump AppID = 2347771
Fossilize INFO: Overriding serialization path: "/home/aarsh/.steam/debian-installation/steamapps/shadercache/730/fozpipelinesv6/steamapprun_pipeline_cache".
Fossilize INFO: Overriding serialization path: "/home/aarsh/.steam/debian-installation/steamapps/shadercache/730/fozpipelinesv6/steamapprun_pipeline_cache".
09/02 19:09:57 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(20230728184426)/tid(15260)
09/02 19:09:57 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(15260)
Fontconfig warning: line 86: saw string, expected number
Fontconfig warning: "Z:\home\aarsh\.steam\debian-installation\steamapps\common\Counter-Strike Global Offensive\game\csgo\panorama\fonts\../../../core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in
<test> isn't supported and may not work as expected
Fontconfig warning: "Z:\home\aarsh\.steam\debian-installation\steamapps\common\Counter-Strike Global Offensive\game\csgo\panorama\fonts\../../../core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in
<test> isn't supported and may not work as expected
CAppInfoCacheReadFromDiskThread took 3 milliseconds to initialize
dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
Setting breakpad minidump AppID = 730
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561197960265728
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561197960265728
Setting breakpad minidump AppID = 2347771
e\game\bin\win64\cs2.exe: ../src-wine/dlls/ntdll/unix/virtual.c:1571: create_view: Assertion `!((UINT_PTR)base & page_mask)' failed.
pid 15116 != 15115, skipping destruction (fork without exec?)
Game 730 created interface STEAMAPPLIST_INTERFACE_VERSION001 /
Game 730 created interface STEAMAPPS_INTERFACE_VERSION008 /
Game 730 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_005 /
Game 730 created interface STEAMHTTP_INTERFACE_VERSION003 /
Game 730 created interface STEAMINVENTORY_INTERFACE_V003 /
Game 730 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 /
Game 730 created interface STEAMMUSIC_INTERFACE_VERSION001 /
Game 730 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION016 /
Game 730 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 /
Game 730 created interface STEAMUGC_INTERFACE_VERSION016 /
Game 730 created interface STEAMUSERSTATS_INTERFACE_VERSION012 /
Game 730 created interface STEAMVIDEO_INTERFACE_V003 /
Game 730 created interface SteamAppDisableUpdate001 /
Game 730 created interface SteamController008 /
Game 730 created interface SteamFriends017 /
Game 730 created interface SteamGameCoordinator001 /
Game 730 created interface SteamGameStats001 /
Game 730 created interface SteamInput006 /
Game 730 created interface SteamMatchGameSearch001 /
Game 730 created interface SteamMatchMaking009 /
Game 730 created interface SteamMatchMakingServers002 /
Game 730 created interface SteamNetworking006 /
Game 730 created interface SteamUser023 /
Game 730 created interface SteamUser023 / User
Game 730 created interface SteamUtils010 /
Game 730 created interface SteamUtils010 / Utils
Game 730 method call count for IClientUGC::AddRequiredTag : 1
Game 730 method call count for IClientUGC::ReleaseQueryUGCRequest : 1
Game 730 method call count for IClientUGC::SendQueryUGCRequest : 1
Game 730 method call count for IClientUGC::CreateQueryUserUGCRequest : 1
Game 730 method call count for IClientHTTP::ReleaseHTTPRequest : 8
Game 730 method call count for IClientHTTP::GetHTTPResponseBodyData : 8
Game 730 method call count for IClientHTTP::GetHTTPResponseBodySize : 8
Game 730 method call count for IClientHTTP::GetHTTPResponseHeaderValue : 1
Game 730 method call count for IClientHTTP::SendHTTPRequest : 8
Game 730 method call count for IClientHTTP::CreateHTTPRequest : 8
Game 730 method call count for IClientGameStats::GetNewSession : 1
Game 730 method call count for IClientGameCoordinator::RetrieveMessage : 11
Game 730 method call count for IClientGameCoordinator::IsMessageAvailable : 22
Game 730 method call count for IClientGameCoordinator::SendMessage : 8
Game 730 method call count for IClientRemoteStorage::FileExists : 2
Game 730 method call count for IClientRemoteStorage::GetFileTimestamp : 12
Game 730 method call count for IClientRemoteStorage::GetFileSize : 4
Game 730 method call count for IClientRemoteStorage::FileWriteAsync : 1
Game 730 method call count for IClientRemoteStorage::FileRead : 2
Game 730 method call count for IClientRemoteStorage::FileWrite : 14
Game 730 method call count for IClientUserStats::DownloadLeaderboardEntries : 8
Game 730 method call count for IClientUserStats::FindLeaderboard : 8
Game 730 method call count for IClientUserStats::GetStat : 244
Game 730 method call count for IClientUserStats::RequestCurrentStats : 1
Game 730 method call count for IClientAppManager::GetCurrentLanguage : 1
Game 730 method call count for IClientAppManager::GetLaunchCommandLine : 2
Game 730 method call count for IClientAppManager::GetAppStateInfo : 34
Game 730 method call count for IClientAppManager::BIsDlcEnabled : 1
Game 730 method call count for IClientUtils::RecordSteamInterfaceCreation : 134
Game 730 method call count for IClientUtils::FilterText : 22
Game 730 method call count for IClientUtils::InitFilterText : 1
Game 730 method call count for IClientUtils::IsSteamChina : 1
Game 730 method call count for IClientUtils::SetOverlayNotificationInset : 2
Game 730 method call count for IClientUtils::SetOverlayNotificationPosition : 2
Game 730 method call count for IClientUtils::GetLauncherType : 1
Game 730 method call count for IClientUtils::GetSteamUILanguage : 1
Game 730 method call count for IClientUtils::GetAPICallResult : 27
Game 730 method call count for IClientUtils::GetAppID : 145
Game 730 method call count for IClientUtils::GetImageRGBA : 42
Game 730 method call count for IClientUtils::GetImageSize : 42
Game 730 method call count for IClientUtils::GetServerRealTime : 3
Game 730 method call count for IClientFriends::GetProfileItemPropertyString : 12
Game 730 method call count for IClientFriends::RequestEquippedProfileItems : 41
Game 730 method call count for IClientFriends::GetFriendPersonaName_Public : 29
Game 730 method call count for IClientFriends::GetFriendSteamLevel : 4
Game 730 method call count for IClientFriends::RequestFriendRichPresence : 12
Game 730 method call count for IClientFriends::GetFriendRichPresenceKeyByIndex : 177
Game 730 method call count for IClientFriends::GetFriendRichPresenceKeyCount : 12
Game 730 method call count for IClientFriends::GetFriendRichPresence : 177
Game 730 method call count for IClientFriends::SetRichPresence : 220
Game 730 method call count for IClientFriends::RequestUserInformation : 42
Game 730 method call count for IClientFriends::GetClanActivityCounts : 3
Game 730 method call count for IClientFriends::GetClanTag : 3
Game 730 method call count for IClientFriends::GetClanByIndex : 6
Game 730 method call count for IClientFriends::GetClanCount : 2
Game 730 method call count for IClientFriends::GetFriendGamePlayed : 378
Game 730 method call count for IClientFriends::GetFriendByIndex : 378
Game 730 method call count for IClientFriends::GetFriendCount : 3
Game 730 method call count for IClientFriends::GetMediumFriendAvatar : 21
Game 730 method call count for IClientFriends::GetSmallFriendAvatar : 21
Game 730 method call count for IClientFriends::GetFriendPersonaState : 127
Game 730 method call count for IClientFriends::GetFriendRelationship : 127
Game 730 method call count for IClientFriends::GetPersonaName : 1
Game 730 method call count for IClientUser::BSetDurationControlOnlineState : 1
Game 730 method call count for IClientUser::BIsSubscribedApp : 34
Game 730 method call count for IClientUser::GetUserDataFolder : 1
Game 730 method call count for IClientUser::GetSteamID : 45
Game 730 method call count for IClientUser::BLoggedOn : 5
Uploaded AppInterfaceStats to Steam

(process:15260): GLib-GObject-CRITICAL **: 19:10:32.677: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[2023-09-02 19:10:40] Shutdown

**Comment by kisak-valve** [comment]
Hello @aarshparashar, we're using one issue report per unofficially supported game title. Since Counter-Strike 2 is a DLC of Counter-Strike: Global Offensive and shares the same appid, that makes it the same game for the purposes of tracking feedback of the game running with Proton. I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2704#issuecomment-1703856837.
