### ISSUE TITLE
Anno 1800 black screen

### ISSUE THREAD

**Issue by basculeo** [ValveSoftware/Proton#7069]
# Compatibility Report
- Name of the game with compatibility issues: Anno 1800
- Steam AppID of the game: 916440

## System Information
- GPU: RTX 1070
- Video driver version: nvidia 535.86.05
- Kernel version: 5.4.0
- Proton version: 7 / 8 / exp

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

 ## Proton log:
attachment didn't work...

## Symptoms 

I played Anno 1800 for months under proton 8, no problems aside from the usual ubi launcher bullshit. After the last game update, it no longer works. I get past the launcher and when the game loads, it's just a black screen with the Anno mouse cursor.

Things I've tried:

every recent version of proton, including some GE flavors
verifying game files
completely uninstalling and re-installing the game, including deleting shader cache and proton prefix
messing with the settings in engine.ini (game file inside the prefix)

Nothing works, I think we need a proton update.

**Comment by kisak-valve** [comment]
Hello @basculeo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2544#issuecomment-1704296736.
