### ISSUE TITLE
Mount & Blade II: Bannerlord

### ISSUE THREAD

**Issue by Nothankslads** [ValveSoftware/Proton#7077]
# Compatibility Report
- Name of the game with compatibility issues: Mount & Blade II: Bannerlord
- Steam AppID of the game: 261550

## System Information
- GPU: NVIDIA 3070
- Video driver version: 535.104.05

- Kernel version: 6.4
- https://pastebin.com/ghdMVgDY
- Proton version: Any proton above 6.3-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-261550.log](https://github.com/ValveSoftware/Proton/files/12566803/steam-261550.log)

## Symptoms
Game hangs either in the first loading screen, or immediately after this in the first opening cinema (with the sword being forged). Must be closed, will never advance passed this point.
This is fixed by using proton 6.3-8, but this prevents DLSS from being activated in the settings and leads to reduced performance.

## Reproduction
1. Use Proton experimental (or any recent proton build)
2. Launch mount and blade banner lord
3. Game hangs in opening cinema

Workaround:
1. Use proton 6.3-8 and go without DLSS and other optimizations

**Comment by kisak-valve** [comment]
Hello @Nothankslads, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3706#issuecomment-1708270610.

**Comment by Nothankslads** [comment]
> Hello @Nothankslads, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#3706 (comment)](https://github.com/ValveSoftware/Proton/issues/3706#issuecomment-1708270610).

Have done that now
