### ISSUE TITLE
Which is latest Proton version that supports nVidia 470 driver ?

### ISSUE THREAD

**Issue by donburch888** [ValveSoftware/Proton#7078]
# Compatibility Report
- Name of the game with compatibility issues: Civilization 6
- Steam AppID of the game:

## System Information
- GPU: nVidia GeForce 730
- Video driver version: nVidia 470.199.02
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:  THIS IS MY QUESTION.  Experimental and 8 say "no graphics card found"

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I done all available updates (Ubuntu, driver, etc).

**Comment by kisak-valve** [comment]
Hello @donburch888, noted at https://github.com/ValveSoftware/Proton/wiki/Changelog#available-in-proton-80, Proton 8.0 and newer needs the video driver to provide Vulkan 1.3. The NVIDIA 470 series video driver provides Vulkan 1.2.

Proton 7.0 and older doesn't have this requirement.

**Comment by donburch888** [comment]
Thanks Kisak, 
I did have a look in the changelog and in github for "Civilization".  I saw the mention of Vulkan, but assumed it was just another feature enhancement ... no hint that it means games won't run on older graphics cards.
