### ISSUE TITLE
The Surge 2 (644830)

### ISSUE THREAD

**Issue by wiscoinferno** [ValveSoftware/Proton#7079]
# Compatibility Report
- Name of the game with compatibility issues: The Surge 2
- Steam AppID of the game: 644830

## System Information
- GPU: Nvidia 3080 10GB
- Video driver version: nvidia 535.104.05
- Kernel version: 6.4.10-202.fsync.fc38.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/wiscoinferno/9b92e081614444ff8c6d9a6326de2ef4
- Proton version: Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
When conversing with NPCs, and navigating menus, the option to navigate via controller (dualsense wired) randomly drops. Still able to use the face buttons to choose the top most option (or exit dialog) but cannot move up/down to choose other options. Often exiting and re-entering dialog will enable movement, but it often drops again mid conversation.

## Reproduction
This happens at random using Proton Experimental. Will attach log files this evening after work and converse with an NPC.

**Comment by kisak-valve** [comment]
Hello @wiscoinferno, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3426#issuecomment-1708560124.
