### ISSUE TITLE
Payday 3 - Beta (1272080)

### ISSUE THREAD

**Issue by AQDuck97** [ValveSoftware/Proton#7087]
# Compatibility Report
- Name of the game with compatibility issues: Payday 3
- Steam AppID of the game: 1272080

## System Information
- GPU: RTX 3080
- Video driver version: nvidia 535.104
- Kernel version: 6.4.12-arch
- Link to full system information report as [Gist](https://gist.github.com/): [Gist](https://gist.github.com/AquaDuck97/84e0535c71a5b628c948629a550dc236)
- Proton version: GE-Proton 8-14

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms

I'm by no means an expert on memory management on Linux (or anything in general), but this is a really weird one to me and I just can't make sense of it.

After Payday 3/Steam has crashed from a potential memory leak, the memory "usage" only drops what the game + Steam are reported as using (6-8GiB), leaving the "Used" memory abnormally high for what the rest of the processes are actually using (as reported by `btop`, `htop`, `ps_mem`, etc.)

This does not feel like a case of "Linux ate my RAM" since then the "unused" "used" memory should have been moved to "Available" immediately after the game/Steam crashed/closed, but in this case only a small part of it was moved and the rest stayed in the "used" part until I either reboot the system or, for whatever reason, go back into the game and click "matchmake".

The second I hit "matchmake", the memory usage nosedives and moves into "available" to a much more reasonable level.

I unfortunately made a typo for PROTON_LOG=1 so I didn't get a log from that, but I will include a video clip of me launching btop, Payday 3, and keeping btop in view so you can see how the memory usage immediately drops only _after_ I hit "matchmake". The last time I played Payday 3 was last night and I only suspended my PC over the night.

I did not include the processes in the video because of privacy (name, also replaced it with "user" in the gist), but also because I didn't see anything "weird" when it came to memory usage per-process, Payday stayed at a 4.3-6 GiB usage and I sort the processes by memory usage and nothing ever topped it. I also tried running htop as root in TTY to see if there was some system process I couldn't see, but it looked the same.

[Streamable link to video](https://streamable.com/xakq1j)

## Reproduction

- Launch Payday 3
- Play until you run out of memory and Steam shuts down
- Watch the memory usage only drop slightly
- Launch the game again
- Click "Matchmake"

**Comment by Marc-Pierre-Barbier** [comment]
the game runs without any issue on my machine

**Comment by AQDuck97** [comment]
Issue was with the replay feature of a screen recorder I'm using, closing
