### ISSUE TITLE
Ravenswatch (2071280)

### ISSUE THREAD

**Issue by fabiojb** [ValveSoftware/Proton#7089]
# Compatibility Report
- Ravenswatch ver 0.14.01.03.22880
- 2071280

## System Information
- GPU: Radeon RX 580
- Video driver version: amdgpu / mesa 1:23.1.6-4 
- Kernel version: Linux archlinux 6.4.12-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/fabiojb/a7575200c910957a17e557a631ba87b6):
- Proton version: 8.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
I can play the game normally until finishing the first boss, when confirming to go to the next level, almost half of the times the game crashes. Also tried to select "save and exit", but the crash still occurs some times. Playing single player btw.

## Reproduction
* Start the game normally, select any character and start the first level
* After some time, the first boss will start. Kill the boss
* Randomly the game crashes after selecting any action ("continue" or "save and exit")

Didn't found any issues for the game here, but I found [a post on steam forum](https://steamcommunity.com/app/2071280/discussions/1/3820796140090474274/) with the same problem running on steam deck.

**Also tried playing** with proton experimental, but the crashes still occurs

And found those errors on logs:
> 7152.968:0134:0248:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
> 7152.984:0134:0248:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems

[steam-2071280.log](https://github.com/ValveSoftware/Proton/files/12571038/steam-2071280.log)

**Comment by Vincent-P** [comment]
Hi, I am not sure how compatibility reports are handled but this particular issue has been fixed.

**Comment by fabiojb** [comment]
This issue was also occurring on Steam Deck so they fixed it
