### ISSUE TITLE
SOULCALIBIUR VI Modding Tool - VODKALIBUR (544750)

### ISSUE THREAD

**Issue by ThisNekoGuy** [ValveSoftware/Proton#7092]
# Compatibility Report
- Name of the application with compatibility issues: Vodkalibur
- Steam AppID of the game: 544750

## System Information
- GPU: RTX 2080 Ti
- Video driver version: Nvidia 535.104.05
- Kernel version: [6.4.12-tkg-gentoo-gcc-zen2](https://github.com/frogging-family/linux-tkg)
- Link to full system information report: [Gist](https://gist.github.com/ThisNekoGuy/20c1b858fd61c31ad341d968dc43f368)
- Proton version: 8.0-3c

## I confirm:
- [x] that I have checked whether there are updates for my system available.

[steam-544750.log](https://github.com/ValveSoftware/Proton/files/12591683/steam-544750.log)

## Symptoms 
The Souldcalibur VI modding tool (Vodkalibur) fails to run in Proton 8.0-3c:
```c
. . . (non-error output)
58077.006:011c:0120:err:ole:apartment_add_dll couldn't find function DllGetClassObject in L"C:\\windows\\system32\\uiautomationcore.dll"
58077.006:011c:0120:err:ole:com_get_class_object no class object {ff48dba4-60ef-4201-aa87-54103eef594e} could be created for context 0x1
58077.006:011c:0120:err:tabtip:create_uia_event_handler Failed to create IUIAutomation interface, hr 0x800401f8
. . . (non-error output)
58077.920:0130:0134:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"VODKALIBUR.exe" cannot be loaded
58077.920:0130:0134:err:module:LdrInitializeThunk Importing dlls for L"Z:\\mnt\\chonker\\Gaming\\SteamLibrary\\steamapps\\common\\SoulcaliburVI\\vodkalibur\\VODKALIBUR.exe" failed, status c0000135
. . . (non-error output)
```

## Reproduction

1. Launch Soulcalibur VI
2. Close the game after reaching the main menu
3. Run `winetricks  -q wmp11 d3dcompiler_47 arial` on the game's compatdata prefix (`pfx` folder) location (vanilla Winetricks is required for `wmp11` to install)
4. After that, run `protontricks` (using the GUI is fine, just be sure to enable `silent install` in the menu; I used the flatpak) to install `dotnet48` (This will use Proton)
5. After that is complete, download [`vodkalibur`](https://web.archive.org/web/20230913000245/https://cdn.discordapp.com/attachments/651396632167841812/1147632239761424545/VODKALIBUR.exe) (A Soulcalibur VI modding tool)
6. Make a folder inside of the root of the Soulcalibur VI game folder called "vodkalibur" (`mkdir -p /path/togame/folder/vodkalibur`)
7. Place the executable in that folder
8. Add `eval $(echo "PROTON_LOG=1 %command%" | sed 's|SoulcaliburVI/Binaries/Win64/SoulcaliburVI.exe|vodkalibur/VODKALIBUR.exe|')` to the game's launch options
9. Click `Launch` in Steam

**Comment by kisak-valve** [comment]
Hello @ThisNekoGuy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1780#issuecomment-1716750277.

**Comment by ThisNekoGuy** [comment]
@kisak-valve Isn't this technically a different application though? I'd think that putting it with the actual game's report might actually get it drowned in other comments eventually since they're two different applications; since this is a tool and not the game.

**Comment by kisak-valve** [comment]
Third party mods, tweaks, and other utilities have consistently been paired with the game their modifying. In terms of support it's better to discuss them together.
