### ISSUE TITLE
No titles launching with any version of proton after 7.0-6 on btrfs

### ISSUE THREAD

**Issue by unixenon** [ValveSoftware/Proton#7097]
I believe this might have something to do with the steam runtime 3.0, as it is launching games with that in proton versions after 7.0-6 and with steam runtime 2.0 on versions 7.0-6 and previous. I was able to fix this issue by moving my proton files from my main btrfs partition to one formatted in ext4. I was getting no proton logs with the PROTON_LOG=1 flag, but I recorded my steam output wile I was fixing the issue. It should have failed attempts at launching games followed by one successful one.
[steam_output.txt](https://github.com/ValveSoftware/Proton/files/12604729/steam_output.txt)

I am on fedora linux with Nvidia drivers, an NVME ssd(main drive btrfs), sata ssd(secondary drive ext4), and an AMD cpu

**Comment by kisak-valve** [comment]
Hello @Dfirebug, these look like some lines of interest in your terminal spew:
```
Traceback (most recent call last):
  File "/home/daniel/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 1702, in <module>
    g_proton.do_steampipe_fixups()
  File "/home/daniel/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 454, in do_steampipe_fixups
    result_code = steampipe_fixups.do_restore(self.base_dir, fixups_json)
  File "/home/daniel/.local/share/Steam/steamapps/common/Proton - Experimental/steampipe_fixups.py", line 91, in do_restore
    os.chmod(this_file,
PermissionError: [Errno 1] Operation not permitted: '/home/daniel/.local/share/Steam/steamapps/common/Proton - Experimental/files/lib64/wine/dxvk/openvr_api_dxvk.dll'
```

**Comment by nm004** [comment]
> Hello @Dfirebug, these look like some lines of interest in your terminal spew:
> 
> ```
> Traceback (most recent call last):
>   File "/home/daniel/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 1702, in <module>
>     g_proton.do_steampipe_fixups()
>   File "/home/daniel/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 454, in do_steampipe_fixups
>     result_code = steampipe_fixups.do_restore(self.base_dir, fixups_json)
>   File "/home/daniel/.local/share/Steam/steamapps/common/Proton - Experimental/steampipe_fixups.py", line 91, in do_restore
>     os.chmod(this_file,
> PermissionError: [Errno 1] Operation not permitted: '/home/daniel/.local/share/Steam/steamapps/common/Proton - Experimental/files/lib64/wine/dxvk/openvr_api_dxvk.dll'
> ```

It seems that the dll's execution bit is off (`chmod -x`), so `Operation not permitted` error happened. The  file mode bits of that dll is `-r-xr-xr-x` in my system. I don't think this issue is related to btrfs.
