### ISSUE TITLE
[System.Resources.MissingManifestResourceException] Old software wont work [please help] [30$ reward when solved]

### ISSUE THREAD

**Issue by orithecapper** [ValveSoftware/Proton#7100]
Unhandled Exception:
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "rU=y,B(_Rs<3]88Nl:zY ]Gk!.resources" was correctly embedded or linked into assembly "VideoThumbnailsMaker" at compile time, or that all the satellite assemblies required are loadable and fully signed.

---------

Hello I would consider myself fairly tech savy... in terms of (rm -rf /)

anyways 

i've tried proton on very old software like 2009-ish and it wont work 
I bought a license to it even :crying_cat_face:

please help me 

command used ````
[ori@user **Video Thumbnails Maker**]$ proton VideoThumbnailsMaker.exe 
```


wine
command used ````
[ori@user **Video Thumbnails Maker**]$ wine VideoThumbnailsMaker.exe 
```

thanks been wanting a proper Thumbnails maker for years :)

**Comment by kisak-valve** [comment]
Hello @orithecapper, presenting this as a bug bounty and no usable information makes this issue report look fairly bad in my eyes. This reads more like something that should be reported to the upstream wine bug tracker (https://bugs.winehq.org/) if it hasn't been already,

In general, Proton is a downstream project for running Windows based games on Linux with Steam and this random utility (from Proton's perspective) is marginally relevant. Support would come from wine growing what it needs for this application to run and that coming downstream to Proton along with all other changes in wine during a major rebase to the wine version inside of Proton.
