### ISSUE TITLE
Apex Legends

### ISSUE THREAD

**Issue by jluthi** [ValveSoftware/Proton#7107]

**Comment by jluthi** [comment]
@kisak-valve Why was this closed? Is it not enough detail?  What? It's incredibly discouraging to take the time to actually report a bug only to have it closed with no explanation. Word of advise would be to improve on this as a user taking time to report a bug takes effort that most people wouldn't even bother with. Don't want to discourage bug reporting on your products because you loose valuable insight that would cause others to just quit using it altogether than go through the hassle.

**Comment by kisak-valve** [comment]
Hello @joell29, it's not that there's not enough detail, there's no details here at all which indicates a misclick more than anything.

Regardless, with Proton, we're using one issue report per unofficially supported game title, and feedback related to Apex Legends is being tracked at #4350. Feel free to add any feedback related to running that game with Proton on the older issue report.
