### ISSUE TITLE
(ea app)(Problem) Proton 8.0-4 Release Candidate testing still have some EA APP problems

### ISSUE THREAD

**Issue by 00pandora00** [ValveSoftware/Proton#7112]
i make this post to make a space about the problems of EA App that still persist.

everybody feel free to post your problems down here

My problem:
Sims 4 have a weird lag when you start to play (after the main menu)

**Comment by kisak-valve** [comment]
Hello @00pandora00, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4174#issuecomment-1723572058.
