### ISSUE TITLE
Destroy All Humans! 2 - Reprobed (1266700)

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/Proton#7113]
# Compatibility Report
- Name of the game with compatibility issues: Destroy All Humans! 2 - Reprobed
- Steam AppID of the game: 1266700

## System Information
- GPU: RX 6700XT
- Video driver version: Mesa 23.1.6-3
- Kernel version: 6.1.51-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/coreybruce/3a7dd24ead8b58d8b85b4f94f5906a58
- Proton version:  proton-8.0-3c

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

Proton Log: https://gist.github.com/coreybruce/371cb9e8d6d62a3cad2278ff1d6f2bf9

## Symptoms 
Game will memory leak very quickly after I leave my ship in the second area

https://youtu.be/Oj3HbYuGqzo

## Reproduction

Exit ship in  second area

**Comment by kisak-valve** [comment]
Hello @coreybruce, there's a known memory leak in mesa 23.1.6 (specifically) which has been fixed in mesa 23.1.7. Update your mesa install when it becomes available via your distro's normal update process.

**Comment by coreybruce** [comment]
> Hello @coreybruce, there's a known memory leak in mesa 23.1.6 (specifically) which has been fixed in mesa 23.1.7. Update your mesa install when it becomes available via your distro's normal update process.

Oh thank you for letting me know, I actually got the update today so I'll do another test and let you know if I have the same problem or not

**Comment by coreybruce** [comment]
> Hello @coreybruce, there's a known memory leak in mesa 23.1.6 (specifically) which has been fixed in mesa 23.1.7. Update your mesa install when it becomes available via your distro's normal update process.

Yep that Mesa update defiantly fixed the issue, thank you very much for informing me and I appreciate the hard work from the proton and mesa team!
