### ISSUE TITLE
Microsoft Flight Simulator (1250410) Logitech Extreme 3D throttle control/Joystick R-Axis X does not function when in flight

### ISSUE THREAD

**Issue by AbnocChinwads** [ValveSoftware/Proton#7121]
# Compatibility Report
- Name of the game with compatibility issues: Microsoft Flight Simulator
- Steam AppID of the game: 1250410

## System Information
- GPU: RX 7900 XT
- Video driver version: Mesa 23.1.7
- Kernel version: 6.2.0-32-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/AbnocChinwads/3cf11e89bd66e76b0d98532801013f34
- Proton version: 8.0-3

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

 [steam-1250410.zip](https://github.com/ValveSoftware/Proton/files/12704999/steam-1250410.zip)

## Symptoms 
The paddle button on the Logitech Extreme 3D josytick which controls the throttle while in flight doesn't register at all whilst in flight, but it does get picked up by the game as you can change it's settings under control options, selecting the joystick, going into the sensitivity options and changing the settings on the Josytick R-Axis X. Meaning in flight you have to constantly look towards your throttle and manually adjust it with the mouse, which is fine for most of the flight but it is not so useful when trying to land/taxi

## Reproduction
Plug in the joystick, plan a flight, start said flight from take off, attempt to adjust throttle with paddle button

**Comment by kisak-valve** [comment]
Hello @AbnocChinwads, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-1732121116.
