### ISSUE TITLE
Dark souls uses my integrated graphics card instead of my AMD Card

### ISSUE THREAD

**Issue by mohammadsingy** [ValveSoftware/Proton#7122]
Dark souls uses my integrated graphics card instead of my AMD Card

**Comment by kisak-valve** [comment]
Hello @mohammadsingy, this is a general system config issue more than it is an issue with Proton. The issue you've described is that Dark Souls is running in an environment that has the integrated GPU configured to be prioritized over the discrete GPU. Other Vulkan applications are most likely affected in the same way.

There are several ways to control what GPU a game is able to use with environment variables. On Mesa's side you can use `DRI_PRIME` (https://docs.mesa3d.org/envvars.html#envvar-DRI_PRIME) and `MESA_VK_DEVICE_SELECT` (https://docs.mesa3d.org/envvars.html#envvar-MESA_VK_DEVICE_SELECT). Alternatively, you can filter GPUs used by DXVK with `DXVK_FILTER_DEVICE_NAME` (https://github.com/doitsujin/dxvk#device-filter).

It's recommended to set that on a per game basis as needed by going to the per-game properties, and adding the environment variables you want to tinker with to the game's launch options followed by a single `%command%` afterwards.
