### ISSUE TITLE
arma 3 multiplayer issue

### ISSUE THREAD

**Issue by nitlott** [ValveSoftware/Proton#7123]
# Compatibility Report
- Name of the game with compatibility issues: Arma 3
- Steam AppID of the game: 107410

## System Information
- GPU: gtx 1070
- Video driver version: 
- Kernel version: 6.5.3-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: tried multiple versions even exprimental

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

## Symptoms 

Game launches fine, singleplayer works fine. BUT when i enter multiplayer i cant load in, i get stuck with a background of either desert or under water image, i can see the chat and i see one upp arrorw and one down arrow icon. but the game never loads in fully

## Reproduction

Game launches fine, singleplayer works fine. BUT when i enter multiplayer i cant load in, i get stuck with a background of either desert or under water image, i can see the chat and i see one upp arrorw and one down arrow icon. but the game never loads in fully

**Comment by kisak-valve** [comment]
Hello @nitlott, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2364#issuecomment-1732317135.
