### ISSUE TITLE
HOİ4 cant launch and game dont run at native.

### ISSUE THREAD

**Issue by mrdarwinjs** [ValveSoftware/Proton#7126]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam 394360 of the game:

## System Information
- GPU: RX 570
- Video driver version: Kernel driver in use: amdgpu  Kernel modules: amdgpu
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7 or 8 or expirmentel all tested

## I confirm:
- [ ✅ ] that I haven't found an existing compatibility report for this game.
- [ ✅ ] that I have checked whether there are updates for my system available.

![image](https://github.com/ValveSoftware/Proton/assets/62896862/2732602d-9217-466e-8965-b973141ce60f)
i cant find $HOME/steam-$APPID.log

## Symptoms 
Hey! i cant play hoi4 native. when i force opengl the game runs good but still luancer didint work. (paradox launcer)
![image](https://github.com/ValveSoftware/Proton/assets/62896862/d3205bc3-8096-4d27-9893-60e43c985e6f)

**Comment by kisak-valve** [comment]
Hello @altra1234, this game has a native Linux variant. Without a stronger indicator, that variant of the game is being used and Proton isn't involved at all.

Issues you see with native Linux games should be reported directly to the game's developer(s).
