### ISSUE TITLE
Sackboy: A Big Adventure (1599660)

### ISSUE THREAD

**Issue by vyktorjonas** [ValveSoftware/Proton#7127]
On version 8 of Proton, Sackboy always auto enables a ghost second user/joystick to which is controlled by myself, I play with two characters always doing the exact same thing, I can't choose only 1 player because it's always detecting a "second joystick", if I actually plug in a second joystick, there's then 4(!!) characters on screen, this issue doesn't happen in Proton version 7

**Comment by kisak-valve** [comment]
Hello @vyktorjonas, please grab the compatibility report template from https://github.com/ValveSoftware/Proton/issues/new?template=compatibility-report.md, copy it here, and fill out the requested details.

**Comment by vyktorjonas** [comment]
# Compatibility Report
- Sackboy: A Big Adventure
- 1599660

## System Information
- GPU: 780M
- Kernel version: 6.3.5
- Proton version: 8

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Reproduction
Simply starting the game and pressing start to go to the main menu and you can see the bug

**Comment by vyktorjonas** [comment]
Disabling Steam Input fixes the issue
