### ISSUE TITLE
Assassin's Creed: Director's Cut crashes upon launch

### ISSUE THREAD

**Issue by IPlayZed** [ValveSoftware/Proton#7128]
# Compatibility Report
- Name of the game with compatibility issues: Assassin's Creed: Director's Cut
- Steam AppID of the game: 15100

## System Information
- GPU: AMD RX 6800
- Video driver version: mesa 1:23.1.8-1
- Kernel version: 6.5.4-zen2-1-zen
- [Steam system information](https://gist.github.com/IPlayZed/cfdf14891016b917aaea750746ca7f56)
- Proton version: experimental-8.0-20230907
- [Steam runtime system information](https://gist.github.com/IPlayZed/671b57bb1e5fb84ef93f318b9de76768)
- [Proton log](https://gist.github.com/IPlayZed/9198410ebc9a68e1d9410d1e32a425f0)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Game crashes upon launch, only gets through the registration screen.

## Reproduction

1. Install game.
2. Launch it.
3. Refer or never activate (as activation opens the Wine browser, which will never load the webpage).
4. Crash.

**Comment by kisak-valve** [comment]
Hello @IPlayZed, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/183#issuecomment-1732636233.
