### ISSUE TITLE
Cant play CSGO any more after downloading Counter Strike 2 > Steam FATAL ERROR: Failed to connect with local Steam Client process!

### ISSUE THREAD

**Issue by Cytomax55** [ValveSoftware/Proton#7129]
**9-26-23 EDIT: I AM NOW USING CSGO NATIVE WITH -VULKAN AND CSGO SEEMS TO BE WORKING AGAIN PERFECTLY
ITS NOT ASKING ME IF I WANT TO LAUNCH CS2 OR CSGO ANYMORE BUT ILL TAKE IT.. I CONSIDER THIS FIXED**

# Compatibility Report
- Name of the game with compatibility issues: Counter Strike Global Offensive
- Steam AppID of the game: 730

## System Information
- GPU:  AMD AMD Radeon RX 6700 XT
- Video driver version:  Mesa 23.1.7-1
- Kernel version:  6.5.3-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Cytomax55/28ed1ce2a30889c4b25b44c3f32f2c17
- Proton version: 8.0-3

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

![2023-09-24_23-36](https://github.com/ValveSoftware/Proton/assets/39972769/62a53ce4-0fd9-42d3-8ecd-8bd5058ad923)

## Symptoms 
Counter Strike Global Offensive was working perfectly > I finished a match and while in the main menu of CSGO i was offered a slot to try out CS2 so i clicked enroll and restarted steam and it started downloading CS2 > after it installed i restarted my computer and i wasnt able to play CS2 > i found out it doesnt work with Linux so no problem > i then try to play CS GO and it gives me the error i took a screen shot of

Steam FATAL ERROR: Failed to connect with local Steam Client process!

I have been unable to play CSGO since

## Reproduction
try to play CS GO, doesnt matter if i try different protons, opengl, vulkan, nothing works

[steam-730.log](https://github.com/ValveSoftware/Proton/files/12710821/steam-730.log)

**Comment by asier-ochoa** [comment]
I have the same launcher error when using the windows build of CSGO. Still don't have access to cs2 so I can't comment on that. Have you tried disabling proton for CSGO so that steam uses the linux build instead?

**Comment by molecula451** [comment]
CS:GO has native linux supports, why yo should be trying proton?

**Comment by kisak-valve** [comment]
Hello @Cytomax55, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2704#issuecomment-1733618250.
