### ISSUE TITLE
Starfield (1716740)

### ISSUE THREAD

**Issue by g-dg** [ValveSoftware/Proton#7133]
# Compatibility Report
- Name of the game with compatibility issues: Starfield
- Steam AppID of the game: 1716740

## System Information
- GPU: AMD AMD Radeon RX 6700 XT (navi22, LLVM 16.0.6, DRM 3.49, 6.1.53-1-MANJARO)
- Video driver version: Mesa 23.1.7-1
- Kernel version: 6.1.53-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/g-dg/bc4719a8be4f9cd61df2a57abf1396fd
- Proton version: Proton Experimental (Build ID: 12135228)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
  - I found #7064 , but it seems to be a different issue.
- [x] that I have checked whether there are updates for my system available.

[steam-1716740.log](https://github.com/ValveSoftware/Proton/files/12729258/steam-1716740.log)

## Symptoms 
Ever since the game updated to 1.7.33 (build ID 12212450), The game has displayed the error "Graphics card does not meet the minimal specifications requirements." when I try to start it. Then when I click the "OK" option, the game exits. My graphics card (AMD Radeon RX 6700 XT) is above the minimum requirements, and before this update I was able to play it without any problem.

## Reproduction

1. Launch the current version of the game through Proton Experimental with a AMD Radeon RX 6700 XT.
2. Note the error dialog that says "Graphics card does not meet the minimal specifications requirements."
3. When you click "OK" in the dialog, the game exits.

**Comment by kisak-valve** [comment]
Hello @g-dg, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7064#issuecomment-1735811971.
