### ISSUE TITLE
Bannerlord not updating to 1.1.6

### ISSUE THREAD

**Issue by agoodside** [ValveSoftware/Proton#7135]
# Compatibility Report
- Name of the game with compatibility issues: Mount & Blade 2: Bannerlord
- Steam AppID of the game: 261550

## System Information
- GPU: Radeon RX 570 Series (POLARIS10, DRM 3.42.0, 5.15.0-84-generic, LLVM 12.0.0)Radeon RX 570 Series (POLARIS10, DRM 3.42.0, 5.15.0-84-generic, LLVM 12.0.0)
- Video driver version: AMD (amdgpu driver)
- Kernel version: Linux 5.15.0-84-generi
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental, 8.0.3 and below

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Proton log is not created

## Symptoms The following game modules do not update from 1.1.5 to 1.1.6:

- Native
- Sandbox
- Sandbox Core
- Storymode
- CustomBattle

## Reproduction

Run the game on Steam (linux OS)

https://gist.github.com/agoodside/7d122a163de1327d5f8438c490ce587d

**Comment by agoodside** [comment]
Sorry should have added that playing a save game crashes and is only possible in beta 1.1.5

**Comment by kisak-valve** [comment]
Hello @agoodside, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3706#issuecomment-1737300016.
