### ISSUE TITLE
Pioneers of Pagonia Demo (2552960) 

### ISSUE THREAD

**Issue by monarc99** [ValveSoftware/Proton#7147]
# Compatibility Report
- Name of the game: Pioneers of Pagonia - Demo
- Steam AppID of the game: 2552960

https://store.steampowered.com/app/2155180/Pioneers_of_Pagonia/
the demo is playable for everyone

the game is in development, and the developer are on their discord reachable:
https://discord.gg/yfswCNxKCu

## System Information
- Operating System Version: "Manjaro Linux" (64 bit)
- GPU: NVIDIA Corporation NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
- Video driver version: 4.6.0 NVIDIA 535.104.05
- Kernel version: 6.5.5-2-cachyos
- Link to full system information report: https://gist.github.com/monarc99/10e84b4f7db886bc5712b4f2f0dca197
- Proton version: 8.0-3 and 8.0-4-rc
- Steam Runtime Information gist: https://gist.github.com/monarc99/ae71465ea8a04dce157be4a3c83c1b67

[bugreport-steam-2552960.log](https://github.com/ValveSoftware/Proton/files/12792592/bugreport-steam-2552960.log)
[bugreport-vkd3d-2552960.log](https://github.com/ValveSoftware/Proton/files/12792632/bugreport-vkd3d-2552960.log)

## Symptoms 

the report is for the playable demo - the full game will be released in the future.

proton 8.0-3: 

the demo starts and is playable on my system. There are minor graphic bugs. If you want to build a road, some graphic elements are missing.

normally it looks like this in windows 11:
https://pioneers-wiki.com/wp-content/uploads/2023/09/schnelltest-768x213.webp

with proton you must build the roads and buildings blind. 

But the demo is fully playable on my system. I played the full demo (7 hours)
Some other linux players report a crash, if they build something - even with proton 8.0-3 

proton 8.0-4-rc or any newer proton: regression

the game starts with a error message. If you minimize the error message and open a new map, the game crash, if you place something on the map.

error message at start:
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (DX12 CreateCommittedResource Failed 80070057)
 ---> System.Runtime.InteropServices.ExternalException (0x80070057): DX12 CreateCommittedResource Failed 80070057
   at MagmaEngine.Display.Direct3D12.Device.CreateCommittedResource(HeapProperties*, HeapFlags, ResourceDesc*, ResourceStates, ClearValue*) + 0x154
   at MagmaEngine.Display.Direct3D12.Texture2D.ResetInternal(STexture2DDescription, Boolean) + 0x3d2
   at MagmaEngine.Display.Direct3D12.Device.CreateTexture2DAsync[T](STexture2DDescription, T[]) + 0x98
   at Frontend.Gui.Vis.PlanetMapRenderer.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext() + 0x223
   --- End of inner exception stack trace ---


OS Info: 
Name: Microsoft Windows 10.0.19043
Version: 10.0.19043.0
Culture: en-US
AvailablePhysicalMemory: 3675467776
AvailableVirtualMemory: 140736524926976
TotalVirtualMemory: 140737488224256
 
CPU:
CPU details not retrieved from WMI, error message: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
ProcessorCount: 4 
GPU:
GPU details not retrieved from WMI, error message: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
Current 1002:73DF
Direct3D:
Factory6:Yes

NVIDIA GeForce GTX 1060 6GB
Vendor: 1002
Device: 73DF
SubSys: 0000
Revision: 0000
Flags: AdapterFlagNone
DedicatedVideoMemory: 6700400640
DedicatedSystemMemory: 0
SharedSystemMemory: 6147428352
Luid: 0-3F2
VideoMemoryMemorySegmentGroupLocal
Budget: 5852299264
Usage: 623181824
AvailableForReservation: 3350200320
Reservation: 0
VideoMemoryMemorySegmentGroupNonLocal
Budget: 6147428352
Usage: 95600640
AvailableForReservation: 3073714176
Reservation: 0
Driver: 65535.65535.65535.65535
Output0:
\\.\DISPLAY1
Rotation:ModeRotationUnspecified
Dekstop:True
Coordinates:0/0 1920/1080
Size:1920x1080
Output1:
\\.\DISPLAY2
Rotation:ModeRotationUnspecified
Dekstop:True
Coordinates:-1920/0 0/1080
Size:1920x1080
```

## Reproduction

1) download demo
2) download rc-version 8.0-4-rc
3) start demo with 8.0-4-rc
4) minimize error message, don't close it
5) start a new map
6) try to build something
7) game will crash

**Comment by davidweisgerber** [comment]
I have similar issues on Ubuntu 23.04
The game loads with an error window and if I try to build a road, the game crashes.
