### ISSUE TITLE
Jurassic World Evolution 2 (1244460)

### ISSUE THREAD

**Issue by melvinredondotanis** [ValveSoftware/Proton#7148]
# Compatibility Report
- Name of the game with compatibility issues: Jurassic World Evolution 2
- Steam AppID of the game: 1244460

## System Information
- GPU:  Intel® Xe Graphics (TGL GT2)
- Video driver version:  23.1.6
- Kernel version:  Linux 6.5.5-200.fc38.x86_64
- Proton version: all

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 

Logs  : [Proton : 8.0-3](https://github.com/ValveSoftware/Proton/files/12795015/steam-1244460.log)
Image : ![error](https://github.com/ValveSoftware/Proton/assets/109587382/f354c0f9-18f6-4df0-b78d-3c5270d0f7fa)
(translation) : no 3D graphics card available, check that you have a graphics card compatible with directX12 and that the correct drivers are installed.

## Reproduction
- launch the game with Proton (not version specific)

**Comment by kisak-valve** [comment]
Hello @MelvinRedondoTanis, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6070#issuecomment-1745399450.

**Comment by melvinredondotanis** [comment]
thank you, I will be careful next time
