### ISSUE TITLE
Dota 2 won't launch on any version of Proton since latest update (Road to TI Compendium)

### ISSUE THREAD

**Issue by prnvp23** [ValveSoftware/Proton#7152]
**Compatibility Report**
- DotA 2
- 570

System Information
- Steam Deck
- Driver: AMD AMD Custom GPU 0405 (vangogh, LLVM 14.0.6, DRM 3.45, 5.13.0-valve37-1-neptune)
- Driver Version: 4.6 (Compatibility Profile) Mesa 22.2.0 (git-17e5312102)
- Kernel Version: 5.13.0-valve37-1-neptune
- Full System Info ([Gist](https://gist.github.com/prnvp23/535333931a33c1608bfe92a3fa73ffed))
- Proton version: 8.0-3, 7.0-6 & Experimental

**I confirm:**
- That I haven't found an existing compatibility report for this game.
- That I have checked whether there are updates for my system available.

[steam-570.log](https://github.com/ValveSoftware/Proton/files/12813286/steam-570.log)

**Symptoms**
Game won't launch on multiple versions of Proton, it just says Running for a while and then the button turns back into Play with no error messages, no screen turning black like the game launch even began, nothing. The native linux version works when Steam Play is turned off or Steam Linux Runtime 1.0 (scout) is selected instead of Proton

**Reproduction**
- Enable "Force the use of a specific Steam Play compatibility tool"
- Launch Dota 2

**Comment by kisak-valve** [comment]
Hello @prnvp23, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6631#issuecomment-1748751844.

**Comment by prnvp23** [comment]
Understood, I wasn't sure as that post is from Mar 21 and for me and seemingly many other users on Steam Deck this issue only happened recently with the TI Compendium update. 

Also I do not understand how is Dota 2 Unofficially supported? Is it not a Valve game and it has also been marked as Playable on Deck. Sorry if this is an obvious question I'm new here and to Github in general and don't know where to look for answers
