### ISSUE TITLE
Returnal crashes at random times

### ISSUE THREAD

**Issue by BeauTaapken** [ValveSoftware/Proton#7153]
Game: Returnal (https://store.steampowered.com/app/1649240/Returnal/)
Proton: Proton - Experimental (Bleeding Edge)
GPU: RTX 4090
Driver: 535.113.01

When i play Returnal, sometimes I can play for multiple hours without having this issue, and other times it crashes the instant the game shows anything 3d, this happens with raytracing on and off
[steam-1649240.log](https://github.com/ValveSoftware/Proton/files/12822746/steam-1649240.log)

**Comment by kisak-valve** [comment]
Hello @BeauTaapken, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6538#issuecomment-1749662929.
