### ISSUE TITLE
The Talos Principle 2 Demo - 2312690

### ISSUE THREAD

**Issue by jansalleine** [ValveSoftware/Proton#7155]
# Compatibility Report
- Name of the game with compatibility issues: The Talos Principle 2 Demo
- Steam AppID of the game: 2312690

## System Information
- GPU: AMD RX 5700
- Video driver version: 23.2.1
- Kernel version: 6.5.5.
- Link to full system information report as [TXT](https://trans.jansalleine.com/Talos2Demo/SteamSysinfo.txt):
- Proton version: 8.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

GPU crashes leading to black screen and then I get back to the login manager.
The Unity Engine Logs of the game say:
<pre>[2023.10.06-19.43.05:309][676]LogD3D12RHI: Warning: GPU timeout: A payload (0x00000000A790CFE0) on the [0x00000000035B0A80, 3D] queue has not completed after 5.000000 seconds.</pre>

And I guess this is the relevant part from the Proton Log:
<pre>498.546:0134:01fc:err:vkd3d-proton:vkd3d_wait_for_gpu_timeline_semaphore: Failed to wait for Vulkan timeline semaphore, vr -4.
X connection to :0 broken (explicit kill or server shutdown).</pre>

## Reproduction

I just play the game and after a while the GPU crashes.
Tested on Gnome 3 / X11, Gnome 3 / Wayland and XFCE / X11.

Proton Logs:
[steam-2312690.log – Gnome 3 / Wayland](https://trans.jansalleine.com/Talos2Demo/Gnome3-Wayland/steam-2312690.log)
[steam-2312690.log – Gnome 3 / X11](https://trans.jansalleine.com/Talos2Demo/Gnome3-X11/steam-2312690.log)
[steam-2312690.log – XFCE / X11](https://trans.jansalleine.com/Talos2Demo/XFCE-X11/steam-2312690.log)

Unity Engine Game Logs:
[Talos2.log – Gnome 3 / Wayland](https://trans.jansalleine.com/Talos2Demo/Gnome3-Wayland/Talos2.log)
[Talos2.log – Gnome 3 / X11](https://trans.jansalleine.com/Talos2Demo/Gnome3-X11/Talos2.log)
[Talos2.log – XFCE / X11](https://trans.jansalleine.com/Talos2Demo/XFCE-X11/Talos2.log)

**Comment by ghost** [comment]
On my end, it kinda freezes the system when the game is in focus (fullscreen). But it unblocks after I `Alt+Tab` out (more accurately 10-15s later since it's frozen). By clicking in the menu, then `Alt+Tab`-ing and waiting for a while, I managed to start a new game and it seems to render well, with decent FPS.... I was looking at it with another app in-focus over the game screen, but I could only get the camera to rotate.

Specs:
OS: Manjaro KDE
GPU: Nvidia 4070 (535.113.01 drivers)
CPU: AMD Ryzen 5700X
Proton: 8.0-4 and Experimental act the same

**Comment by jansalleine** [comment]
Ok. I found this in the mesa bug tracker: https://gitlab.freedesktop.org/mesa/mesa/-/issues/9932
And I can confirm, that after downgrading mesa to 23.1.8 the game isn't crashing anymore.
Doesn't seem to be a Proton issue then.

**Comment by jansalleine** [comment]
And I have to correct myself once more. This evening it crashed again with the same errors as above. Maybe there is more to it with this game than the mesa issue.

**Comment by RodoMa92** [comment]
~~Not even booting on my RX580, logs below:~~
```
LogRHI: Checking if RHI D3D12 with Feature Level SM6 is supported by your system.
LogD3D12RHI: Found D3D12 adapter 0: AMD Radeon RX 580 Series (VendorId: 1002, DeviceId: 67df, SubSysId: 0000, Revision: 0000
LogD3D12RHI:   Max supported Feature Level 12_0, shader model 6.5, binding tier 3, wave ops supported, atomic64 supported
LogD3D12RHI:   Adapter has 8192MB of dedicated video memory, 0MB of dedicated system memory, and 16008MB of shared system memory, 1 output[s]
LogD3D12RHI:   Driver Version: 31.0.14051.5006 (internal:31.0.14051.5006, unified:31.0.14051.5006)
LogD3D12RHI:      Driver Date: 10-11-2023
LogD3D12RHI: Found D3D12 adapter 1: AMD Radeon RX 580 Series (RADV POLARIS10) (VendorId: 1002, DeviceId: 67df, SubSysId: 0000, Revision: 0000
LogD3D12RHI:   Max supported Feature Level 12_0, shader model 6.5, binding tier 3, wave ops supported, atomic64 supported
LogD3D12RHI:   Adapter has 8192MB of dedicated video memory, 0MB of dedicated system memory, and 16009MB of shared system memory, 1 output[s]
LogD3D12RHI:   Driver Version: Unknown (internal:Unknown, unified:Unknown)
LogD3D12RHI:      Driver Date: Unknown
LogD3D12RHI: DirectX Agility SDK runtime found.
LogD3D12RHI: Chosen D3D12 Adapter Id = 0
LogD3D12RHI: Adapter only supports up to Feature Level 'SM5', requested Feature Level was 'SM6'
LogRHI: OS: Windows 10 (21H1) [10.0.19043.UNKNOWN]
LogRHI: RHI D3D12 is not supported on your system; Windows 10 (21H1) [10.0.19043.UNKNOWN]
Message dialog closed, result: Ok, title: Message, text: DirectX 12 is not supported on your system. Try running without the -dx12 or -d3d12 command line argument.
LogWindows: FPlatformMisc::RequestExit(1)
LogWindows: FPlatformMisc::RequestExitWithStatus(1, 0)
LogCore: Engine exit requested (reason: Win RequestExit)
```
~~But a lot of other people seems to have similar issues even on windows, so it might just be the new amazing UE5 code.~~

Oh, goddamn, it's selecting AMDVLK instead of RADV, just realized that now. I hate myself.

**Comment by simifor** [comment]
Beat the demo on a ~2 weeks old build of mesa-git (3d993e63bb5) with my rx 6600, there were no hangs. The only oddity I can mention is this and it might not even be a proton issue:
![Talos2   2023-10-14_17:52:41](https://github.com/ValveSoftware/Proton/assets/70454800/44a28be4-c46b-460a-b9a9-e36967215d9f)
I saw that happen twice after using the pods to switch locations, and both times it fixed itself after a few seconds, like the game wasn't done loading before presenting the scene.

**Comment by chrisbrasington** [comment]
Also frequently crashing for base game of `Talos Principle 2`.

# System Info
OS: Freedesktop.org SDK 23.08 (Flatpak runtime)
KERNEL: 6.1.0-13-amd64CPU: Intel Core i7-9700K @ 3.60GHz
GPU: AMD Radeon RX 5700 XT (navi10, LLVM 16.0.6, DRM 3.49, 6.1.0-13-amd64)
GPU DRIVER: 4.6 Mesa 23.2.1 (git-49a47f187e)
RAM: 32 GB
Proton version: Experimental

**Comment by jansalleine** [comment]
Turned out to be a mesa issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/10021
