### ISSUE TITLE
Street Fighter 6 not launching anymore on Linux

### ISSUE THREAD

**Issue by Roucseba** [ValveSoftware/Proton#7158]
# Compatibility Report
- Name of the game with compatibility issues: Street Fighter 6
- Steam AppID of the game: 1364780

## System Information
- GPU:  Intel Mesa Intel(R) UHD Graphics 630 (CFL GT2), or NVIDIA GeForce GTX 1650 with Max-Q Design
- Video driver version:  4.6 (Compatibility Profile) Mesa 23.1.7 - kisak-mesa PPA
- Kernel version:  5.15.0-84-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Roucseba/2152ee0a96ed45e6e291df6e8894f6d3
- Proton version: 8.0-4

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

 unfortunately, no log created :(

## Symptoms  I had no issue before and the game worked really well. But I am not able currently to launch it anymore. I press the green Play button, the system hangs for 30 or 40 seconds with the blue Stop button and goes back to Play. No messages, nothing launch. I deinstalled and reinstalled the game several time, the whole Steam... no effects.
Thank you in advance!

**Comment by Roucseba** [comment]
And this is the only game I have an issue with. 
Some other are older or pretty recent (King of Fighter XV ie) and work like a charm.

**Comment by kisak-valve** [comment]
Hello @Roucseba, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6817#issuecomment-1751797711.
