### ISSUE TITLE
[Whitelist] Kerbal Space Program (220200)

### ISSUE THREAD

**Issue by adrianlshaw** [ValveSoftware/Proton#716]
Everything seems to work well. It's a little slow but I think that's my ancient GPU, someone should be able to confirm if the speed is fine.

Specs: Proton 3.7-3, Ubuntu 18.04, NVIDIA Corporation G94GL [Quadro FX 1800] (rev a1)
Full specs: https://gist.github.com/adrianlshaw/13b21eae4d9ad3c6c79474396110feed

**Comment by ryao** [comment]
@adrianlshaw @kisak-valve Doesn't this game run natively on Linux?

**Comment by adrianlshaw** [comment]
Ah, good point. I didn't know.

**Comment by waspennator** [comment]
https://store.steampowered.com/news/app/220200/view/3385045248710979041

Game has a launcher stapled on now, might need to test and see if this breaks compatibility on proton.
