### ISSUE TITLE
Windjammers 2 (1114290)

### ISSUE THREAD

**Issue by TiZ-HugLife** [ValveSoftware/Proton#7166]
# Compatibility Report
- Name of the game with compatibility issues: Windjammers 2
- Steam AppID of the game: 1114290

## System Information
- GPU: Steam Deck's Aerith APU
- Video driver version: Mesa 23.1.3.170235.radeonsi_3.5.1-1 
- Kernel version: 6.1.52-valve2-1-neptune-61
- Link to full system information report as [Gist](https://gist.github.com/): [Okay, here you go.](https://gist.github.com/HugLifeTiZ/9cc00c4864bb54a5ee9484b8fe53b814)
- Proton version: 8.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1114290.log](https://github.com/ValveSoftware/Proton/files/12873057/steam-1114290.log)

## Symptoms 
When using the default (presumably Direct3D) version of Windjammers 2 on a Steam Deck instead of the OpenGL version, either the following assertion dialog appears, or it freezes up on a black screen. (I grabbed the screenshot of the dialog from the SoulCalibur VI issue, because I can't get it to appear anymore since going to Desktop and coming back.)

![Assertion dialog](https://github.com/ValveSoftware/Proton/assets/4130673/e18029ac-21ca-4eb7-9df3-d53e2f24868f)

Removing the compatdata for the game doesn't make any difference. The OpenGL version isn't *quite* at parity; stage art doesn't appear in that version, and there may be other issues I'm not remembering at the moment.

## Reproduction
Start Windjammers 2 on a Steam Deck on 3.5 with the default version, not the OpenGL version.

**Comment by LiamDawe** [comment]
Here to confirm the same issue happens on  Steam Deck and my Kubuntu desktop.

The OpenGL launch option does work just fine, even for online play, no issues with stage art not appearing over here though.

Desktop log file for when it gives a black screen: 
[steam-1114290.log](https://github.com/ValveSoftware/Proton/files/12915542/steam-1114290.log)
This is Proton 8.0-4. Proton Experimental has the same issue.

It's currently Steam Deck Verified, so either that needs to be removed or forced to the OpenGL version.

**Comment by TiZ-HugLife** [comment]
> The OpenGL launch option does work just fine, even for online play, no issues with stage art not appearing over here though.

By "stage art", I mainly mean the space above the stage selection screen; there's supposed to be an image of whatever stage is highlighted rather than a blank space. The stages themselves, fortunately, do load up fine. We couldn't use Steam Decks for tournaments at all if it was that bad! :)

**Comment by Oliver-1xok** [comment]
I can confirm this for Proton 8.0-4 under SteamOS 3.5.7. I have taken a picture of the of the error message, see below. However, it seems to work with Proton Experimental. Also with the OpenGL version. 

![Windjamme2_error](https://github.com/ValveSoftware/Proton/assets/40916755/ad01d2f8-76e2-43e4-a7c6-da6903ece7dd)

**Comment by waspennator** [comment]
Is this working on deck now or is it still broken, don't exactly have the game to check on my end?

**Comment by simifor** [comment]
The game is working with proton stable and beta (9), no need to switch to opengl.

**Comment by TiZ-HugLife** [comment]
I am confirming this too. The default Proton branch selected by the game works fine with the default D3D version of WJ2. Given that, I'll go ahead and close this issue.
