### ISSUE TITLE
Icarus failed with 8.0-4 worked with 8.0-3

### ISSUE THREAD

**Issue by RobVerduijn** [ValveSoftware/Proton#7168]
# Compatibility Report
- Name of the game with compatibility issues: Icarus
- Steam AppID of the game: 1149460

## System Information
- GPU: NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate] (rev a1)
- Video driver version: Mesa 23.1.8 or nvidia 535.113.01
- Kernel version: 6.5.6
- Link to full system information report as [Gist](https://gist.github.com/RobVerduijn/ef4573ab6559bcef158df1fed111271a):
- Proton version: 8.0-4 and experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
In the afternoon I was playing the game running proton 8.0-3, then steam released the proton 8.0-4 and when I came back that evening after the system had done an update the game no longer ran.
I noticed that proton was updated to 8.0-4

Now I can get the game only to run using proton 7.0-6 which has horrible performance
I used to run in epic mode without any issues, 
[steam-1149460.log](https://github.com/ValveSoftware/Proton/files/12878755/steam-1149460.log)

## Reproduction
Try to start the game using dx11, it will fail to run.

**Comment by lucifertdark** [comment]
Have you checked the ForceCompositionPipeline setting in Nvidia Settings? I was having the same thing with several games with that setting checked.

**Comment by RobVerduijn** [comment]
> Have you checked the ForceCompositionPipeline setting in Nvidia Settings? I was having the same thing with several games with that setting checked.

I've been reading up a bit about that option (since I didn't know how to enable it)

Found this little explanation
https://www.reddit.com/r/linux_gaming/comments/6voivr/can_anyone_explain_what_force_composition/

And I have a little doubt that that is the cullprit. Since I'm not rotating anything on my screens.
I'll give it a try though.

**Comment by lucifertdark** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/7168#issuecomment-1759506274

I was a little dubious myself, but I disabled it & 8.0-4 is now working perfectly for me. I had it enabled & that was causing the problems for me.

**Comment by RobVerduijn** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/7168#issuecomment-1759513337

Can't find the setting in nvidia-settings gui

neither any info about it when I query on the cli.
nvidia-settings -q CurrentMetaMode -t

So i assume it is off since I didn't enable it anywhere.

btw forgetting about this option, the more I read about it the less likely I find it to be the cause of the problem.

check out arch linux  about this topic
https://wiki.archlinux.org/title/NVIDIA/Troubleshooting#Avoid_screen_tearing_in_KDE_(KWin)

actually explains how to set it or disable it properly and how to make it permanent (did you enforce that?)

I think your problem was solved by something else when you thought you fixed it by setting this option.

**Comment by RobVerduijn** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/7168#issuecomment-1759550509

I should learn to read:

from the note:
ForceFullCompositionPipeline is known [to break some games](https://github.com/ValveSoftware/Proton/issues/6869) using Vulkan under Proton with NVIDIA driver 535.

So It probably fixed yours.
but since the currentmetamode query did not return { ForceFullCompositionPipeline = On } on my machine, it is off and not causing this issue

**Comment by kisak-valve** [comment]
Hello @RobVerduijn, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5465#issuecomment-1759619886.
