### ISSUE TITLE
Proton website bug: The protondb website crashes when trying to connect to steam.

### ISSUE THREAD

**Issue by ramsy0dev** [ValveSoftware/Proton#7169]
When visiting the [profile page in porotondb](https://www.protondb.com/profile) and i try to click where it says **sign in through steam** the following error pops up:

![image](https://github.com/ValveSoftware/Proton/assets/86024158/7378cf3e-c988-435f-bbd2-307a918a49c2)

**Comment by kisak-valve** [comment]
Hello @ramsy0dev, ProtonDB is not affiliated with Valve.

**Comment by ramsy0dev** [comment]
@kisak-valve i didn't know that, sorry.
