### ISSUE TITLE
Street Fighter 6 assertion failed "!status && vkCreateGraphicsPipelines"

### ISSUE THREAD

**Issue by pepi55** [ValveSoftware/Proton#7170]
# Compatibility Report
- Name of the game with compatibility issues: Street Fighter 6
- Steam AppID of the game: 1364780

## System Information
- GPU: AMD Radeon RX 6800 XT
- Video driver version: Mesa 23.1.8
- Kernel version: 6.1.57
- Link to full system information report as [Gist](https://gist.github.com/): [System Info](https://gist.github.com/pepi55/624bbc85d0eccf783bfa9876a3a9a195)
- Proton version: Tried with 8.0-4, Experimental and 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1364780.log](https://github.com/ValveSoftware/Proton/files/12899134/steam-1364780.log)

## Symptoms
Whats the problem? WHATS THE PROBLEM??? I'll tell you whats the problem! 

SF6 crashes when loading vulkan shaders. After the intro screens, which in Proton 8 and experimental work fine, once the compiling shaders screen pops up:
![image](https://github.com/ValveSoftware/Proton/assets/5328981/e3dde8de-90f7-46bf-95a3-f28af482c2ce)

The error messages also start popping up:
![image](https://github.com/ValveSoftware/Proton/assets/5328981/a356c531-2539-423a-8350-6e558606857b)

Pressing cancel brings up the debugger which after a while without interacting with it also errors:
(Takes about a minute or 8)
![image](https://github.com/ValveSoftware/Proton/assets/5328981/b475ebc7-b611-48b9-8fd3-11e31dcd0c1c)

On Proton 7, I can get to the "Press any key" screen but everything is all glitchy and deformed (including the intros, compiling shaders screen and the "press any key prompt). The game is also extremely laggy. After pressing the mythical any key, the game freezes on a black screen and I have to force quit it.

## Reproduction

 - Start gimma
 - Wait for the intros to finish (unskippable)
 - Once "Compiling shaders..." appears:
 - Wait for the error popups

**Comment by pepi55** [comment]
Additional info: The game used to run fine but the last time I tried playing was pre-Rashid patch.

**Comment by kisak-valve** [comment]
Hello @pepi55, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6817#issuecomment-1762254357.

**Comment by pepi55** [comment]
Aha, I was not aware. I thought existing compatibility report meant someone with the same issue, not the same game.

**Comment by JanGalek** [comment]
I have same issue with Nightingale
