### ISSUE TITLE
World Boss crash in proton experimental and Proton 8.0.4 with Proton 7.0 open but is just Vulkan unity backend

### ISSUE THREAD

**Issue by EliasOfWaffle** [ValveSoftware/Proton#7174]
# Compatibility Report
- Name of the game with compatibility issues: World Boss
- Steam AppID of the game: 1628620

## System Information
- GPU: Intel HD Graphics 2500 (IVB) Gen7 
- Video driver version: Mesa 23.1.2
- Kernel version: 6.1
- Proton version: Experimental and tested with 8.0.4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Try to open proton experimental causes crash because always try to open in OpenGL backend that for some reason causes a crash.
When open with other proton 6.0.4 and 7.0.4 this open in Vulkan Backend but crash because of driver i think this is my device that not have a conformance driver and HASVK is very unstable and lacks vulkan features and extensions and are very slow, the mostly fault is because of IVB and Haswell is a very older hardware.
this cause a fossilize warn:
 ``````````````
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
Fossilize WARN: Descriptor set layout handle 0x00007f2b2c0428f0 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
Fossilize WARN: Pipeline layout handle 0x00007f2b2c0429d0 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
`````````````````````````
but if i open with OpenGL backend using this common unity render parameter: "-force-opengl" in Proton 6.0.4 and 7.0.4
causes the same crash that exist in Proton Experimental, this looks because experimental tries to open with OpenGL.

## Reproduction
Open Game 

[steam-1628620.log](https://github.com/ValveSoftware/Proton/files/12907976/steam-1628620.log)

**Comment by kisak-valve** [comment]
Hello @EliasOfWaffle, the builds of DXVK and VKD3D-Proton in Proton 8.0 and newer requires that the video driver provide Vulkan 1.3. The video driver for your hardware generation provides a incomplete implementation of Vulkan 1.2.

Sorry, but your hardware is unsupportable by Proton in general. This is something that would need to be improved in the video driver, but that is unlikely (https://gitlab.freedesktop.org/mesa/mesa/-/issues/7827#note_1672803).

**Comment by EliasOfWaffle** [comment]
> Hello @EliasOfWaffle, the builds of DXVK and VKD3D-Proton in Proton 8.0 and newer requires that the video driver provide Vulkan 1.3. The video driver for your hardware generation provides a incomplete implementation of Vulkan 1.2.
> 
> Sorry, but your hardware is unsupportable by Proton in general. This is something that would need to be improved in the video driver, but that is unlikely (https://gitlab.freedesktop.org/mesa/mesa/-/issues/7827#note_1672803).

oh thanks, in this case i can just replace the dxvk files?
