### ISSUE TITLE
Game not recognizing button inputs

### ISSUE THREAD

**Issue by Such-Significance** [ValveSoftware/Proton#7177]
# Compatibility Report
- rainworld doesn't recognize any steam deck button inputs:
- Steam AppID of the game:

## System Information
- GPU: 
- Video driver version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7 and experimental

## I confirm:
- [ ×] that I haven't found an existing compatibility report for this game.
- [ ×] that I have checked whether there are updates for my system available.

**Comment by Such-Significance** [comment]
Sorry for not answering some of the questions i have no idea what they were asking

**Comment by kisak-valve** [comment]
Hello @Such-Significance, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1230#issuecomment-1766387762.
