### ISSUE TITLE
Sea of thieves

### ISSUE THREAD

**Issue by Djkm5** [ValveSoftware/Proton#7178]
Wont launch says change settings. Says avocado beard

- ![image](https://github.com/ValveSoftware/Proton/assets/148360484/85028c00-d64b-4a2d-953f-fcaa4cf36647)

**Comment by kisak-valve** [comment]
Hello @Djkm5, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3931#issuecomment-1768646472.
