### ISSUE TITLE
Sifu (2138710) freezes On Steam Deck

### ISSUE THREAD

**Issue by Edumadaluk** [ValveSoftware/Proton#7184]
Compatibility Report

Name of the game with compatibility issues: Sifu
Steam AppID of the game: 2138710
System Information

Steam Deck (Beta Channel)
Proton version: Proton Experimental/GE/8
I confirm:

 that I haven't found an existing compatibility report for this game.
 that I have checked whether there are updates for my system available.
[steam-2138710.log](https://github.com/ValveSoftware/Proton/files/11119595/steam-2138710.log)

Symptoms

Game freezes under certain conditions. On character tab.

Reproduction

One reproducible condition is after entering a map and being able to control the character, go into menu and switch between the menu tabs.
After a few actions of switching tabs, the game freezes around the CHARACTER tab.

**Comment by kisak-valve** [comment]
Hello @Edumadaluk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6657#issuecomment-1773349392.
