### ISSUE TITLE
The Game thinks im offline?

### ISSUE THREAD

**Issue by Crasher0711** [ValveSoftware/Proton#7185]
![image](https://github.com/ValveSoftware/Proton/assets/91910049/e1f9e4a7-96b6-46e2-b390-1c82cf524942)

No idea how this github reporting works but ill just sum it up here (if this even is the place for these kind of reports)

S&Box basically thinks im offline constatly which im, well, not, and on steam im also online, restarting, verifying game files and reinstalling didnt help so ill just make a report bout it. I also used to have that bug where the game only showed a black screen no matter what but that somehow just dissapeared after waiting a few weeks. If you need like pc specs of anything lmk.

**Comment by kisak-valve** [comment]
Hello @Crasher0711, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4940#issuecomment-1773775892.

**Comment by Grengo3** [comment]
the solution is easy, @Crasher0711 
just slit youre throat
