### ISSUE TITLE
Dark Souls 2 SOTFS - Intro video not working ("Verified" status)

### ISSUE THREAD

**Issue by X6205** [ValveSoftware/Proton#7189]
# Compatibility Report
- Name of the game with compatibility issues: DARK SOULS™ II: Scholar of the First Sin
- Steam AppID of the game: 335300

## System Information
- GPU: RX 6700 XT
- Video driver version: Mesa 23.2.1
- Kernel version: 6.2
- Proton version: 8.0-4

## Symptoms:
Game has "verified" status, but intro video is not playing on Proton 8.0-4. Only placeholder image with colored squares is shown instead of video. Otherwise game looks to be working. (With Proton GE is intro video working properly).

**Comment by kisak-valve** [comment]
Hello @X6205, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/137#issuecomment-1775064683.
