### ISSUE TITLE
Split Second (297860)

### ISSUE THREAD

**Issue by Mokolni** [ValveSoftware/Proton#7190]
# Compatibility Report
- Name of the game with compatibility issues: Split Second
- Steam AppID of the game: 297860

## System Information
- GPU: Steam Deck's Aerith APU
- Video driver version: Mesa Last STABLE
- Kernel version: Last STABLE
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: I have try all version

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

## Symptoms 
I crash games when launching the "airplane graveyard" map.
It's a real shame because everything else works perfectly.

## Reproduction
The bug is only present on steamdeck, not on computer

**Comment by kisak-valve** [comment]
Hello @Mokolni, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2257#issuecomment-1775740113.
