### ISSUE TITLE
ARMORED CORE™ VI FIRES OF RUBICON™ (1888160)

### ISSUE THREAD

**Issue by CaptainBasch** [ValveSoftware/Proton#7191]
# Compatibility Report
- Name of the game with compatibility issues: ARMORED CORE™ VI FIRES OF RUBICON™
- Steam AppID of the game: 1888160

## System Information
- GPU: RTX 3080
- Video driver version: nvidia 535.113.01
- Kernel version: 6.5.6-76060506-generic
- Link to full system information report as Gist: [System Information & Steam Runtime Diagnostics](https://gist.github.com/CaptainBasch/5deccb9af122b9c8bb10aa1b6302db71)
- Proton version: Proton 8.0-4, Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1888160.log](https://github.com/ValveSoftware/Proton/files/13112424/steam-1888160.log)

## Symptoms 
The decal cursor does not recognize the surface of the Armored Core model when in decal placing mode. As a result, decorating Armored Cores with decals is almost completely non-functional.

## Reproduction
1. Open Armored Core VI: Fires of Rubicon on any Linux distro with Steam Play enabled for all titles.
2. Play past the intro level, or get a save file that is past the intro.
3. Go to AC Design -> Decals -> Head/Core/Arms/Legs -> Custom Decals in the main menu.
4. Try to place a "Custom Decal" on any of the parts.
5. Move the cursor around and observe it's terrible unreliability.

**Comment by kisak-valve** [comment]
Hello @CaptainBasch, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7045#issuecomment-1777122435.
