### ISSUE TITLE
GTA 5 proton experimental 

### ISSUE THREAD

**Issue by budzmasters** [ValveSoftware/Proton#7196]
Steam deck proton experimental having issues with GTA 5 
Bad frame drops of 32-40Fps normal setting's
Previously on proton 7-37 was working fine with average of 60+FPS online, but now proton 7-37 isn't working with Rockstar games louncher
Only way how I'm able to play game is with proton experimental
However on experimental I have bad frame drops and screen tearing
Please find time to fix proton compatibility with grand theft auto 5
Some how only GTA 5 and dying light is getting that issue
Maybe it's because of steam os update

**Comment by kisak-valve** [comment]
Hello @budzmasters, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-1779227828.
