### ISSUE TITLE
Control: Ultimate Edition [870780]

### ISSUE THREAD

**Issue by Saijin-Naib** [ValveSoftware/Proton#7201]
# Compatibility Report
- Name of the game with compatibility issues: Control: Ultimate Edition
- Steam AppID of the game: 870780

## System Information
- GPU: ASRock Intel Arc A380 6GB
- Video driver version: Mesa 23.1.9
- Kernel version: 6.5.9
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton Experimental, Build 12481161

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-870780.log](https://github.com/ValveSoftware/Proton/files/13172422/steam-870780.log)

## Symptoms 
None of the DLC/Content associated with Control: Ultimate Edition is available within Steam for Linux, so I am missing the AWE DLC and the Foundation DLC.

## Reproduction
1) Run game in Steam for Linux
2) Observe that the Ultimate Edition Content is not present

## GISTs for System Information & Steam Runtime Information
https://gist.github.com/Saijin-Naib/47cc8edc0bc31a5110c3a0bb7bb0f144

**Comment by kisak-valve** [comment]
Hello @Saijin-Naib, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4157#issuecomment-1781054902.
