### ISSUE TITLE
DwarfFortress reverts from native Linux to Windows version on client restart

### ISSUE THREAD

**Issue by chdoc** [ValveSoftware/Proton#7204]
I have been playing DwarfFortress on Linux using Steam Play (manually fixing the most recent stable version of Proton via DwarfFortress -> Properties -> Compatibility, IIRC 7.0 when the game came out) basically since the launch of the game.

As of version v50.10 DwarfFortress offers a native Linux version. Thus, I unselected Proton in the settings, causing the Steam client to download the Linux version.

However, every time I restart the Steam client, the game is "updated" back to the Windows version, but without enabling Steam Play. Thus, when I hit Play (with the client started from the command line), I get the following error:

> Dwarf Fortress.exe: cannot execute binary file

At this point, selecting and then unselecting Proton in DwarfFortress -> Properties -> Compatibility causes the game to "update" back to the Linux version, and thus become playable, but only until the Steam client is restarted.

What can I do to persistently use the Linux version? I tried uninstalling and reinstalling the game, but this did not fix the problem.

Reference: Steam Suport Ticket: HT-8JYC-C89B-67NN

**Comment by kisak-valve** [comment]
Hello @chdoc, the Steam client is responsible for downloading and managing game content, not Proton itself.

This issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9875. Closing as a duplicate.

**Comment by chdoc** [comment]
@kisak-valve Thank you for pointing me to the right issue/place. I only did what the Steam Support told me to do. :man_shrugging:
