### ISSUE TITLE
Noita on Wayland crashes one second after window is created.

### ISSUE THREAD

**Issue by Kat-zorn** [ValveSoftware/Proton#7205]
# Compatibility Report
- Name of the game with compatibility issues: Noita
- Steam AppID of the game: 881100

## System Information
- GPU: AMD Radeon 7900 XTX
- Video driver version: Mesa-git 1:23.3.0_devel.179456.3de5da7a5d6-1
- Kernel version: 6.6.0-rc4-00284-gb9ddbb0cde2a (custom config)
- Link to full system information report as [Gist](https://gist.github.com/Blazing-Blast/6aa4dc842400508688e91ce184ea0768):
- Proton version: I tried 8, Experimental and Hotfix.

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
  - I have found one: https://github.com/ValveSoftware/Proton/issues/3176
- [x] that I have checked whether there are updates for my system available.

[logs](https://gist.github.com/Blazing-Blast/0ae993f324fa31de2033604c92279e06)

## Symptoms
The game crashes just after the window opens.

## Reproduction

Install Arch with Hyprland.
Launch the game.
Crash!

**Comment by kisak-valve** [comment]
Hello @Blazing-Blast, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3176#issuecomment-1781633999.
