### ISSUE TITLE
Predecessor [961200]

### ISSUE THREAD

**Issue by a-crate** [ValveSoftware/Proton#7210]
# Compatibility Report
- Name of the game with compatibility issues: Predecessor
- Steam AppID of the game: 961200

## System Information
- GPU: 6700 XT
- Video driver version:  4.6 mesa 23.2.1-2
- Kernel version: 6.5.7
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/a-crate/a9cbe1b31bb2615cfe3409fcd5eaa839
- Proton version: 8.0-4

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-961200.log](https://github.com/ValveSoftware/Proton/files/13197208/steam-961200.log)

## Symptoms 

Game window does not appear, process exits after a short time.

## Reproduction

Start Predecessor with Steam. Launcher appears, game starts, and then the process stops without the game window appearing.

Starting with game with system wine in the same prefix (`WINEPREFIX=~/.local/share/Steam/steamapps/compatdata/961200/pfx wine ~/.local/share/Steam/steamapps/common/Predecessor/PredecessorLauncher.exe`) allows the game window to appear.

**Comment by kisak-valve** [comment]
Hello @a-crate, your system is configured to run the game with AMDVLK. Can you test how the game behaves with mesa/RADV?

**Comment by a-crate** [comment]
I experienced the same behavior with `AMD_VULKAN_ICD=RADV`. [Log](https://gist.github.com/a-crate/bea928d386acf8c48827b2c9f1522293).

**Comment by gofman** [comment]
I think the issue observed in the log should be fixed in Proton 8.0-4c (or Proton Experimental; the log is from 8.0-4b).
