### ISSUE TITLE
Stray Stuck In Launching

### ISSUE THREAD

**Issue by Ezequiel-Valencia** [ValveSoftware/Proton#7211]
# Compatibility Report
- Name of the game with compatibility issues: Stray
- Steam AppID of the game: 1332010

## System Information
- GPU:  GTX 3060 Ti
- Video driver version: 4.6.0 NVIDIA 535.113.01
- Kernel version: 6.5.6-76060506-generic
- Link to full system information report as [Gist](https://gist.github.com/AvocadoMoon/107f734e72bcd28d2008af62bf146d35):
- Proton version: 8.04

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
- [x] Attempt to create proton logs

## Symptoms 
When I launch the game stray, nothing happens and it stays saying that it's currently launching. I try to generate some logs from Proton, but I get nothing which makes this significantly more difficult to find out whats the issue.

## Reproduction
I'm not fully sure how to, since all I do is attempt to play the game.

**Comment by kisak-valve** [comment]
Hello @AvocadoMoon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6017#issuecomment-1784144037.
