### ISSUE TITLE
MTG Arena now crashes, used to run fine.

### ISSUE THREAD

**Issue by jamincollins** [ValveSoftware/Proton#7212]
# Compatibility Report
- Name of the game with compatibility issues: MTG Arena
- Steam AppID of the game: 2141910

## System Information
- GPU: AMD AMD Radeon Graphics (renoir, LLVM 16.0.6, DRM 3.54, 6.5.8-arch1-1)
- Video driver version: 4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2
- Kernel version: 6.5.8-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/jamincollins/d8270baf3eff21dc7223c5c47d451186
- Proton version: proton 8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2141910.log](https://github.com/ValveSoftware/Proton/files/13198536/steam-2141910.log)

## Symptoms 

Application used to run fine, now just crashes with a Unity error dialog.

## Reproduction

Install the application, try to run it.

**Comment by kisak-valve** [comment]
Hello @jamincollins, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6826#issuecomment-1784154592.
