### ISSUE TITLE
Sons of The Forest [1326470]

### ISSUE THREAD

**Issue by TushieSushies** [ValveSoftware/Proton#7213]
# Compatibility Report
- Name of the game with compatibility issues: Sons of The Forest
- Steam AppID of the game: 1326470

## System Information
- GPU: RTX 3070
- Video driver version: 535.113.01
- Kernel version: 5.15.0-87-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/TushieSushies/b095effc617295c86cb27fab05efcf00
- Proton version: 8.0-4

## I confirm:
- [Yes] that I haven't found an existing compatibility report for this game.
- [Yes] that I have checked whether there are updates for my system available.

## Symptoms 
Incredibly long loading times

## Reproduction
Open the game
Start an existing save
The game takes a very long time to load even after pre-caching shaders

**Comment by kisak-valve** [comment]
Hello @TushieSushies, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6559#issuecomment-1785138689.
