### ISSUE TITLE
Need for speed Heat (1222680)

### ISSUE THREAD

**Issue by SherLock707** [ValveSoftware/Proton#7214]
# Compatibility Report
- Name of the game with compatibility issues: Need for speed : Heat 
- Steam AppID of the game: 1222680

## System Information
- GPU: AMD Radeon RX 6700 XT (navi22, LLVM 16.0.6, DRM 3.54, 6.5.9-zen2-1-zen)
- Video driver version: Mesa 23.2.1-arch1.2
- Kernel version: 6.5.9-zen2-1-zen
- Link to full system information report as [Gist](https://gist.github.com/SherLock707/0f50c893aeaf07e5cb1faeaa9200f4bc):
[https://gist.github.com/SherLock707/0f50c893aeaf07e5cb1faeaa9200f4bc](https://gist.github.com/SherLock707/0f50c893aeaf07e5cb1faeaa9200f4bc)
- Proton version: 8.0-4 | Experimental |Hotfix

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Lot of stutter in gameplay with 10-15 FPS in lowest setting
High frame-time observed through DXVK_HUD and mangoHud, Graph is red/at peak all the time

## Reproduction
1. launch steam
2. Install Need for speed: Heat
3. Turn on compatibility in setting
4. Select run in steam

Expected:
Game launches and is playable without stutter or frame-drops

Actual:
Game launches, high frame-time in cut-scene and worst in game leading to laggy gameplay with 10-15 FPS  and framerate graph is all in red (1 second +)

# Proton log
[steam-1222680.log](https://github.com/ValveSoftware/Proton/files/13204017/steam-1222680.log)

**Comment by kisak-valve** [comment]
Hello @SherLock707, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3955#issuecomment-1784850979.

**Comment by SherLock707** [comment]
@kisak-valve, I did not know that, thank you for transferring
