### ISSUE TITLE
Grand Theft Auto V won't start

### ISSUE THREAD

**Issue by DivinityCube** [ValveSoftware/Proton#7216]
Hello,
I've recently downloaded GTA V onto my Ubuntu 23.10 machine, launching the game opens the Rockstar Launcher, however an error then appears in said launcher stating '_Game executable path not found. Please reinstall the game._' After closing this error, another one appears, stating '_Unable to launch Grand Theft Auto V. If you continue to have problems with the game, please verify the integrity of your game files_'. Unfortunately, launching the Rockstar Launcher independently through Wine doesn't seem to work, as it thinks I don't own the game at all, so I can't verify any game files. Verifying through Steam, however, shows no problems with the files. _Both of these errors are attached._
So after **reinstalling the game again twice more,** the same error keeps appearing. This appears using Proton 8.0-4, Proton 7.0-6, even Proton Experimental. So I'm thinking it's either to do with the launcher, the version of Ubuntu I'm using, or my files.
I've looked around to the best of my ability, and I've seen that some people have seen the 'Unable to launch Grand Theft Auto V' error, but nobody seems to have encountered the 'Game executable path not found' error.
I would also like to state another observation, when GTA first starts it executes 'install scripts', however what's irked me is that it's **always** frozen on DirectX. I'm not sure why this is and I've tried using winetricks to install some DirectX files which hasn't helped at all. It seems restarting my computer seemed to fix that problem, though.

For reference, my kernel version is 6.5, and I've got Wine 8.19 installed.

Any help with this would be appreciated.

UPDATE: Issue has been fixed, I just had to switch from the steam snap to the steam package provided by Ubuntu.

**Comment by kisak-valve** [comment]
Hello @Taysy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-1785705340.
