### ISSUE TITLE
[Whitelist] Tomb Raider: Anniversary (8000)

### ISSUE THREAD

**Issue by adrianlshaw** [ValveSoftware/Proton#722]
Works flawlessly.

Specs: Proton 3.7-3, Ubuntu 18.04, NVIDIA Corporation G94GL [Quadro FX 1800] (rev a1)
Full specs: https://gist.github.com/adrianlshaw/13b21eae4d9ad3c6c79474396110feed

**Comment by ATypescriptEnjoyer** [comment]
If it works then it isn't really an issue :) You can add this game to the list here: https://docs.google.com/forms/d/e/1FAIpQLSeefaYQduMST_lg0IsYxZko8tHLKe2vtVZLFaPNycyhY4bidQ/viewform

**Comment by kisak-valve** [comment]
Closing in favor of #371.
