### ISSUE TITLE
Easy Anti-Cheat Closes 

### ISSUE THREAD

**Issue by 7Therion** [ValveSoftware/Proton#7221]
After installing the new Apex legends update the easy anti cheat closes out about a quarter of the way loading then the game starts and kicks me with easy anti cheat not running error. Tried without compatibility then with 8.0-4 then 7.0-6, restarted both steam then the steam deck itself and verified file integrity and reinstalled EAC files.

**Comment by kisak-valve** [comment]
Hello @7Therion, we're using one issue report per unofficially supported game title. Usually I'd transfer this issue report to #4350, but this specific feedback has been mentioned several times today already.

Closing in favor of the older issue report.
