### ISSUE TITLE
Conan Exiles (440900) Accented keys not working on AZERTY keyboard

### ISSUE THREAD

**Issue by Nyalnara** [ValveSoftware/Proton#7223]
In Conan Exiles (appid: 440900), accented keys of an azerty keyboard are not recognized, regardless of the actual keymap that is set.
I couldn't set the `é` and `è` as keybinds for the hotbar, they're not recognized.
Borrowed a keybinds file from a friend running the game on Windows, the keybinds are properly shown on the hotbar but when you press them, they're not recognized.

[Full system hardware](https://gist.github.com/Nyalnara/366511c3038552045e060ae4db2793dd), but it probably doesn't matter. Could reproduce with several different keyboards, all from different manufacturers.

Problem present with the following proton versions:

- Proton 8.0-4
- Proton Experimental
- GE-Proton8-20
- GE-Proton8-16

I didn't try older versions of Steam supplied proton, but as I did find a [2 years old reddit thread about this exact issue](https://old.reddit.com/r/ConanExiles/comments/nv02ku/french_keyboard_mapping_on_linux/), I would assume older versions are impacted too.

I would provide a full wine log, but the one generated when using `PROTON_LOG=1 %command%` as launch options doesn't show anything useful. I will definitely provide the log if provided with correct launch options.

**Comment by kisak-valve** [comment]
Hello @Nyalnara, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2563#issuecomment-1789094229.
