### ISSUE TITLE
Corrupted saves playing from Steamdeck and PC

### ISSUE THREAD

**Issue by Heatlass** [ValveSoftware/Proton#7227]
# Compatibility Report
- Name of the game with compatibility issues: Hollow Knight
- Steam AppID of the game: 367520

## System Information
- Steamdeck
- Proton version: 8.0-4

## Symptoms 

I play Hollow Night from Steamdeck and PC. it had been a long time since I played from PC, I installed it on Steamdeck and played two hours. From there the problems started. After I closed the game I verified that on Steamdeck it updated Steam Cloud and I turned on the PC to play from there but as soon as I opened Steam on PC I was informed that Steam CLoud fails to update. I tried deleting the local Steam Cloud folder from the PC but did not solve the problem, I even uninstalled steam from the PC but the problem persists. When I try to start the game from PC I am offered the choice to use the Steamdeck save, I use it, play the game and when I close the game I am informed that the Steam cloud save failed. What can I do about this? I would like to keep the cloud saves made from SteamDeck and continue to play the game from PC as well. How can I permanently delete the steamcloud saves made from PC? I specify that I have the same problem with several games

## Reproduction

I suppose the problem occurs because of the overlap of the saves made by steamdeck having the last Cloud save occurred from PC as a start, I attach the SteamCloud log

[cloud_log.txt](https://github.com/ValveSoftware/Proton/files/13235713/cloud_log.txt)

**Comment by kisak-valve** [comment]
Hello @Heatlass, Steam Cloud syncing is handled by the Steam client, not Proton. Skimming over the log you shared, this looks like a Steam (for Windows) client issue.

Please report this issue to [Steam Support](https://help.steampowered.com) for the larger Steam support team to ponder.
