### ISSUE TITLE
Games always update upon each Steam launch under Proton

### ISSUE THREAD

**Issue by bendamschke** [ValveSoftware/Proton#723]
I've noticed that every time I go to play a game with Steam Play, there's an update. I checked to see if a new version of the game was released, but there was not. I downloaded the update, played the game, then restarted Steam. After attempting to play the game again, I had to download the exact same update again.

**Comment by nstgc** [comment]
This is a known issue

**Comment by DenisBY** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/5644
