### ISSUE TITLE
The Talos Principle 2 (835960)

### ISSUE THREAD

**Issue by chrisbrasington** [ValveSoftware/Proton#7231]
# Compatibility Report
- Name of the game with compatibility issues:The Talos Principle 2
- Steam AppID of the game: 835960

## System Information
- GPU: AMD Radeon RX 5700 XT
- Video driver version: 4.6 Mesa 23.2.1 (git-49a47f187e)
- Kernel version: 6.1.0-13-amd64
- Link to full system information report as [Gist](https://gist.githubusercontent.com/chrisbrasington/1eeace752a2bf6c4048a5c67449f309e/raw/1e42cb67fd3a5004aa4f840b8354b5d367f71f26/gistfile1.txt):
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
  [Demo has a similar report](https://github.com/ValveSoftware/Proton/issues/7155)
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
GPU crashes leading to black screen and then I get back to the login manager.

## Reproduction
I just play the game and after a while the GPU crashes. Shortest duration: 1 minute. 

Tested Debian 12, Wayland/X11, Gnome 3

[steam-835960-wayland-crash.log.tar.gz](https://github.com/ValveSoftware/Proton/files/13247556/steam-835960-wayland-crash.log.tar.gz)
[steam-835960.log.tar.gz](https://github.com/ValveSoftware/Proton/files/13247524/steam-835960.log.tar.gz)

**Comment by chrisbrasington** [comment]
[steam-835960.log.tar.gz](https://github.com/ValveSoftware/Proton/files/13247521/steam-835960.log.tar.gz)

**Comment by Leopard1907** [comment]
If it works with `RADV_DEBUG=nodcc %command%` then issue is probably this and fix is not in your Mesa.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/10021

**Comment by chrisbrasington** [comment]
> If it works with `RADV_DEBUG=nodcc %command%` then issue is probably this and fix is not in your Mesa.
> 
> https://gitlab.freedesktop.org/mesa/mesa/-/issues/10021

This might have done the trick. I'll play as much as I can later this evening to test ;). Thanks so much.

**Comment by HolySoap** [comment]
@chrisbrasington your problem might be more severe, the 5700XT has a very very common hardware bug that results in GPU hangs and crashes (under mildly to heavy load). I had one for myself for 3 years and it got to a point where I couldn't endure it any more and needed to be replaced.
Sadly many 5700XT users don't know about that and falsely report issues that don't really exist. I advise you to test more demanding games and if they have the same issue you have a faulty GPU.

Anyway, something with The Talos Principle 2 isn't right, the game has MASSIVE fps drops that makes it unplayable. It goes from ~100fps (Ultra settings with FSR Quality) to literally 2fps when I move the camera. Changing graphic settings does nothing, Proton version doesn't matter (stable, Experimental, GE) with Mesa git on a 7800XT.
I report back when the first patch drops.

**Comment by chrisbrasington** [comment]
@HolySoap ~~I appreciate it, but I think that's unlikely. I have been gaming with this GPU in linux just fine since 2020. I didn't have an issue with cyberpunk (or elden ring, depends what you mean by more demanding game), so I'm leaning toward this is more a compatibility issue somewhere regarding UE5.~~

~~In Talos, when running I do get steady performance at medium settings (1440p) without drops (stays around 80-100 fps, can be 70 if I turn up global illumination - but again steady). So in my bug here, my crash is during stable performance - just an immediate halt.~~

I might do some sort of stress load test on the card to double check, so thanks for the comment.

**Comment by chrisbrasington** [comment]
@HolySoap my apologies, you're stop on. UE5 is demanding. I'm running quite a bit hotter than I've seen before (checked using `sensors`) and I was probably crashing due to this. I'll look at modifying my airflow on my machine and keeping it cooler. 

I'll likely close this after running it on high load for some time.

**Comment by chrisbrasington** [comment]
I'm an happy to report that I am a dummy and my machine was simply running too hot. I cleaned it up and installed 2 new fans did the trick.

I will keep `RADV_DEBUG=nodcc %command%` around because it does seem relevant.

Thanks all

**Comment by HolySoap** [comment]
Lucky you that you don't have a faulty GPU (it seems), but still this game has issues as I commented as well, no need to close this.

**Comment by jansalleine** [comment]
Had the same problems with the Talos 2 Demo (and the Robocop Demo) on an RX 5700. 
I can confirm that with `RADV_DEBUG=nodcc %command%` there are no more crashes.

EDIT: oh and @HolySoap that performance issue is really strange with such a good card. I get pretty much stable 60 FPS ingame on medium / 1440p / vsync.

**Comment by FilipVujicic** [comment]
I'm also getting really bad performance. Running a 6900xt tested with latest stable mesa and mesa-git
The main menu is fine but as soon as I start the game I get less than 1fps, even with all the graphics settings on minimum.

Getting a lot of GPU timeouts in the logs:
`LogD3D12RHI: Warning: GPU timeout: A payload (0x000000007FAD8740) on the [0x00000000238D0A80, 3D] queue has not completed after 7.957307 seconds.`

**Comment by artemyto** [comment]
Unplayable on laptop with Ryzen 9 6900HS and Radeon RX 6800S. Menu is fine, but less than 1 fps during loading when I am trying to start a new game. It took several minutes to show me "A prophet hath no honour in his own country."

No changes with RADV_DEBUG=nodcc and gamemode.

**Comment by artemyto** [comment]
@giantplaceholder This issue is closed. Please use the open one: https://github.com/ValveSoftware/Proton/issues/7237
