### ISSUE TITLE
Frostpunk doesn't launch

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7233]
# Compatibility Report
- Name of the game with compatibility issues: Frostpunk
- Steam AppID of the game: 323190

## System Information
- GPU: RX6600XT
- Video driver version: Mesa 23.2.1
- Kernel version: 6.5.9
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental/8.0.4/7.0.6/GE-8.22

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-323190_GE.log](https://github.com/ValveSoftware/Proton/files/13257023/steam-323190_GE.log)
[steam-323190_EXP.log](https://github.com/ValveSoftware/Proton/files/13257024/steam-323190_EXP.log)

## Symptoms 
I use Archlinux with Wayland(Hyprland) and I was not able to start the game. After pressing play button in steam it loads for 2 seconds and after that the play button reappears. I already tried some solutions that I found on protondb and on github, like starting the game with SDL_VIDEODRIVER="", etc. , but none of them worked.

## Reproduction
Open steam, and press the play button.

**Comment by kisak-valve** [comment]
Hello @Spartik24, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/412#issuecomment-1793485086.
