### ISSUE TITLE
New world crashing very often during loading screens

### ISSUE THREAD

**Issue by Kitsab77** [ValveSoftware/Proton#7234]
# Compatibility Report
- Name of the game with compatibility issues: New world
- Steam AppID of the game: https://store.steampowered.com/app/1063730/New_World/ -> 1063730

## System Information

- GPU: AMD (Navi33) 7600s
- Video driver version: amdgpu 23.10
- Kernel version: 6.5.5-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://hastebin.com/share/mazenaqevu.yaml
- Proton version: Proton Experimental (also tried 8.0-4, 7.0-6, 5.13-6, and Proton-GE which is a custom build)

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game **relating to this error**.
- [ x] that I have checked whether there are updates for my system available. **pacman -syu / yay -Sua**

 https://drive.google.com/file/d/1LVnKnSszH5Usy1HA-ZPTzLCaj5I76WrZ/view?usp=sharing
Game always crashes with a bunch of:
err:sync:RtlpWaitForCriticalSection section 000000017006F2A0 "../src-wine/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0340, blocked by 0784, retrying (60 sec)
at the end.

## Symptoms 
The game is crashing during loading screen (mostly in bigger cities or crowded places)
The crash always happens during loading screen. When logging into the game it needs sometimes up to 10 tries to logon.
Also happening when using recall to tavern or fast travel portals to cities. Sometimes also happens outside of cities.
Tried mesa drivers, tried amdgpu driver installed from Archlinux[Aur], tried different wine versions.
Actual launch options:
PROTON_LOG=1 DRI_PRIME=1 %command% -dx12 -high -novid -nojoy -vulkan -disable_d3d9ex -nohltv
Basic launch options I tried: 
DRI_PRIME=1 %command% -dx12 -high

## Reproduction
Could be reproduced very well, happening everytime I play the game. 

I searched the web for err:sync:RtlpWaitForCriticalSection, I found this should have been fixed by release Wine6.1

I tried a lot chaning graphic details, but this seems to be replated to a internet/game server connection timeout issue, or may I misunderstand this?

Thanks and best regards kitsab

**Comment by kisak-valve** [comment]
Hello @Kitsab77, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5772#issuecomment-1793571595.
