### ISSUE TITLE
Trackmania 2020. Ubisoft connect is not currently installed

### ISSUE THREAD

**Issue by DocCringol** [ValveSoftware/Proton#7235]
# Compatibility Report
- Name of the game with compatibility issues:
Trackmania 2022
- Steam AppID of the game:
2225070

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Problem, Reproduction, Symptoms

Launching trackmania 2020, on linux machine. Used proton experimantal and 8.0-4.
It shows Ubisoft connect is not currently installed
![image](https://github.com/ValveSoftware/Proton/assets/89182851/e96dd983-cc91-4332-b5e9-84753b42a8b9)

It should install it on a game installing process or on first launch, but it doesn't. So maybe there is the way to install it manually

**Comment by kisak-valve** [comment]
Hello @DocCringol, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6507#issuecomment-1793593301.
