### ISSUE TITLE
Red dead redemption 2 is currently running

### ISSUE THREAD

**Issue by Gimuck** [ValveSoftware/Proton#7239]
After Rockstarr starts up in RDR2 the box comes up as above 'A GAME IS CURRENTLY RUNNING' 'Red dead redemption 2 is currently running. By choosing to exit Red Dead Redempetion 2 will be quit and any unsaved access will be lost. RDR2 then crashes if quit or not quit. I am running proton8.0-4 on Mint 21.2 Victoria - Kernel: 5.15.0-88-generic x86_64.
Graphics:
  Device-1: NVIDIA TU116M [GeForce GTX 1660 Ti Mobile] vendor: ASUSTeK
    driver: nvidia v: 470.223.02 bus-ID: 01:00.0
  Device-2: AMD Renoir vendor: ASUSTeK driver: amdgpu v: kernel
    bus-ID: 06:00.0
  Device-3: IMC Networks USB2.0 HD UVC WebCam type: USB driver: uvcvideo
    bus-ID: 3-4:3
  Display: x11 server: X.Org v: 1.21.1.4 driver: X:
    loaded: amdgpu,ati,nvidia unloaded: fbdev,modesetting,nouveau,vesa
    gpu: amdgpu resolution: 1920x1080~144Hz
  OpenGL: renderer: RENOIR (renoir LLVM 15.0.7 DRM 3.42 5.15.0-88-generic)
    v: 4.6 Mesa 23.2.1 - kisak-mesa PPA direct render: Yes
Thanks,

**Comment by kisak-valve** [comment]
Hello @Gimuck, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-1793888413.
