### ISSUE TITLE
VRChat in VR mode crashes on startup -- proton experimental regression

### ISSUE THREAD

**Issue by hypevhs** [ValveSoftware/Proton#7241]
VRChat in SteamVR mode results in a Unity crash when running in Proton Experimental, but not in Proton 8.0. This is the "Crashes while logging in³" scenario described in @digitalf0x 's testing reports [from the main issue thread for VRChat](https://github.com/ValveSoftware/Proton/issues/1199#issuecomment-1790053082).

![Screenshot_20231107_181410](https://github.com/ValveSoftware/Proton/assets/3746656/3aa5fccb-22b8-482e-9974-fd9e1f7d5741)

My settings:

- AMD GPU
- Wayland
- SteamVR (rolled back to 1.27.5)
- VRChat latest stable (2023.4.1)
- Proton Experimental - Unity crash
- Proton 8.0 - works fine

I bisected Proton, this is the first bad commit.
"vrclient: Wrap parameters in structures."
https://github.com/ValveSoftware/Proton/commit/b60757e37189fc7b5eae5c7f54d5bd59bcf82a87

Logs here
[steam-438100.zip](https://github.com/ValveSoftware/Proton/files/13290486/steam-438100.zip)

**Comment by kisak-valve** [comment]
Hello @libjared, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1199#issuecomment-1800723435.
