### ISSUE TITLE
Quake2 remastered

### ISSUE THREAD

**Issue by tojestzart** [ValveSoftware/Proton#7242]
# Compatibility Report
- Name of the game with compatibility issues: quake2 RERERERERERERELEASE
- Steam AppID of the game: https://store.steampowered.com/app/2320/Quake_II/

## System Information
- GPU:    product: Cezanne [Radeon Vega Series / Radeon Vega Mobile Series]
- Video driver version:   not sure
- Kernel version:  6.5.0-10-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/tojestzart/cb12f31a3a121e7a0f5e5c573cca8599 and https://gist.github.com/tojestzart/bfa20d05a84652021218466b72412e8e
- Proton version:  proton experimental

## I confirm:
- [] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-2320.log](https://github.com/ValveSoftware/Proton/files/13291590/steam-2320.log)

## Symptoms 
not runningn

## Reproduction
try to run and dont run

**Comment by kisak-valve** [comment]
Hello @tojestzart, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1410#issuecomment-1801860968.
