### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Miste-X-GER** [ValveSoftware/Proton#7245]
# Compatibility Report
- Name of the game with compatibility issues: Ghostbusters: Spirits Unleashed Ecto Edition
- Steam AppID of the game: 2382990

## System Information
- GPU:  RTX 3080 TI
- Video driver version: NVIDIA 535.129.03
- Kernel version: 6.5.0-10-generic 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 8.0-4

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms If I start this game nothing happends. If I start it from shell with "steam steam://rungameid/2382990/" Steams shows a small window with "No license".
[Uploading steam-2383990.log…]()

**Comment by kisak-valve** [comment]
Hello @Miste-X-GER, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7182#issuecomment-1802504063.
