### ISSUE TITLE
Like a Dragon Gaiden: The Man Who Erased His Name (2375550)

### ISSUE THREAD

**Issue by ikaikahub** [ValveSoftware/Proton#7248]
# Compatibility Report
- Name of the game with compatibility issues: Like a Dragon Gaiden: The Man Who Erased His Name
- Steam AppID of the game: 2375550

## System Information
- GPU: Nvidia RTX 2070
- Video driver version: NVIDIA 525.125.06
- Kernel version: 6.1.0-13-amd64 Debian
- Link to full system information report as [Gist](https://gist.github.com/ikaikahub/bc8651b894badddfb964d2c05d4ebdc6):
- Proton version: proton-8.0-4c

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2375550.log](https://github.com/ValveSoftware/Proton/files/13305364/steam-2375550.log)

## Symptoms 
The game does not launch. It shows as running within steam for about 30 seconds. The startup.exe process exits after about 10 seconds. No windows appear

## Reproduction
Just clicking play

**Comment by ikaikahub** [comment]
Update: I switched the game to proton 7.0-6 and it worked. This was previously not working on experimental or 8.0

**Comment by alasky17** [comment]
@ikaikahub I'm assuming that when you switch back to Proton 8.0-4/experimental, the game is still failing?  If this is the case, could you try putting DXVK_FILTER_DEVICE_NAME="NVIDIA" %command% as a launch option and see if that helps the game launch on 8.0-x?

**Comment by Dinjoralo** [comment]
SEGA added FSR3 frame generation to Like A Dragon Gaiden in mid-December. I'm not certain how far along getting FSR3 working in Proton, or if it's being worked on actively, but I do hope this game is flagged to have it enabled when it does. (Alongside Like A Dragon: Infinite Wealth, which uses the same engine and will have the same rendering features.)

**Comment by Tsubajashi** [comment]
> @ikaikahub I'm assuming that when you switch back to Proton 8.0-4/experimental, the game is still failing? If this is the case, could you try putting DXVK_FILTER_DEVICE_NAME="NVIDIA" %command% as a launch option and see if that helps the game launch on 8.0-x?

i may not be OP, but this launch option fixed the game for me on RTX 3080, Fedora Silverblue, Steam Flatpak. :)

**Comment by ikaikahub** [comment]
Im not sure if this is an issue anymore. Im not able to test it anymore since i switched distros and it seems like there a working solution to some problem, related or not
