### ISSUE TITLE
The Elder Scrolls: Oblivion — Unable to skip launch cinematics

### ISSUE THREAD

**Issue by jonkoops** [ValveSoftware/Proton#7250]
# Compatibility Report
- Name of the game with compatibility issues: The Elder Scrolls: Oblivion
- Steam AppID of the game: 22330

## System Information
- GPU: AMD Radeon RX 6900 XT
- Video driver version: Mesa 23.1.9
- Kernel version: 6.6.1
- Proton version: 8.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms

On Windows it is possible to skip the intro cinematics (logos, etc) when launching the game by pressing the Escape key. Doing the same in Proton does not work.

## Reproduction

Press the Escape key upon launching the game.

**Comment by kisak-valve** [comment]
Hello @jonkoops, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/718#issuecomment-1805864111.
