### ISSUE TITLE
Sons of the forest multiplayer

### ISSUE THREAD

**Issue by Test-Account666** [ValveSoftware/Proton#7251]
# Compatibility Report
- Name of the game with compatibility issues: Sons of the forest
- Steam AppID of the game: 1326470

## System Information
- GPU: RX 6900 XT
- Video driver version: Mesa 23.1.9
- Kernel version: 6.6.0
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/TheBlackEntity/5a92d9ca6c4649e935de54d356159947
- Proton version: 7.0-6, 8.0-4 & Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1326470.tar.gz](https://github.com/ValveSoftware/Proton/files/13325758/steam-1326470.tar.gz)

## Symptoms 
Being the host in a multiplayer world crashes the game as soon as someone tries to join.
You can play as the host in said world, but only as long as nobody tries to join you.

Multiplayer itself works fine though

## Reproduction
1. Create a lobby
2. Invite a friend
3. Start the lobby

**Comment by kisak-valve** [comment]
Hello @TheBlackEntity, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6559#issuecomment-1806840768.
