### ISSUE TITLE
Doesn't run after update to Fedora 39

### ISSUE THREAD

**Issue by SolidCapo** [ValveSoftware/Proton#7254]
# Compatibility Report
- Name of the game with compatibility issues: Brawlhalla
- Steam AppID of the game: https://store.steampowered.com/app/291550/Brawlhalla/

## System Information
# Detalles del informe del sistema
---

## Detalles del informe
- **Fecha generada:**                              2023-11-11 17:51:14

## Hardware Information:
- **Modelo de hardware:**                          Gigabyte Technology Co., Ltd. H110M-S2PH
- **Memoria:**                                     16.0 GiB
- **Procesador:**                                  Intel® Core™ i7-7700 × 8
- **Gráficos:**                                   NVIDIA GeForce GTX 1060 6GB
- **Capacidad del disco:**                         3.2 TB

## Software Information:
- **Versión de firmware:**                         F22
- **Nombre del SO:**                               Fedora Linux 39 (Workstation Edition)
- **Construcción de SO:**                          (null)
- **Tipo de SO:**                                  64 bits
- **Versión de GNOME:**                            45.1
- **Sistema de ventanas:**                         Wayland
- **Versión del núcleo:**                          Linux 6.5.10-300.fc39.x86_64

- Proton version: Experimental

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
It runs, shows the splash, and then steam says it's running, but the game doesn't show or appears.

## Reproduction
Execute the game

**Comment by kisak-valve** [comment]
Hello @SolidCapo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/83#issuecomment-1806956661.
