### ISSUE TITLE
Ace Combat Assault Horizon - Enhanced Edition (228400)

### ISSUE THREAD

**Issue by AlexanderWKoenig** [ValveSoftware/Proton#7255]
# Compatibility Report
- Name of the game with compatibility issues: Ace Combat Assault Horizon - Enhanced Edition
- Steam AppID of the game: 228400

## System Information
- GPU: AMD RX6800
- Video driver version: Mesa 23.2.1
- Kernel version: 6.5.8-273-tkg-linux-tkg-eevdf
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/AlexanderWKoenig/8712d2344c6471c7ddc312fe74e85196
- Proton version:  8.0-4c

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-228400.log](https://github.com/ValveSoftware/Proton/files/13337868/steam-228400.log)

## Symptoms
Game crashes my entire X11 session at start of campain mission 5.
Here you have to land the plan I suppose. After the intro cutscene the game runs for about 5 seconds and crashes.
I've also tried proton experimental and proton-ge but the same issue appears. 
This happens also on my SteamDeck. Here it wont crash the session, but screen goes black for a while, after this the game is unresponsive.

## Reproduction
Try to play the 5th campain mission and wait for it do crash. Should be about 30s after mission loads

**Comment by kisak-valve** [comment]
Hello @AlexanderWKoenig, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2160#issuecomment-1808587576.
