### ISSUE TITLE
Errors:

### ISSUE THREAD

**Issue by MikhailStakhov** [ValveSoftware/Proton#7256]
# Compatibility Report
- Name of the game with compatibility issues: Yooka-Laylee Impossible Lair
- Steam AppID of the game: 846870

## System Information
- GPU:  ???
- Video driver version: Nividea 545
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7-04

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [_/ ] that I have checked whether there are updates for my system available.

## Symptoms  Not loading, best result (so far is on Proton 7), has this issue: Failed to initialize graphics.
Make sure you have DirectX 11 installed, have up to date
drivers for your graphics card and have not disabled
3D acceleration in display settings.
InitializeEngineGraphics failed

**Comment by MikhailStakhov** [comment]
Reproduction: Ubuntu. Open game

**Comment by kisak-valve** [comment]
Hello @MikhailStakhov, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3133#issuecomment-1808614396.
