### ISSUE TITLE
[EAC][DT_HASH] Paladins EAC always kick in match

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [ValveSoftware/Proton#7259]
# Compatibility Report
- Name of the game with compatibility issues: Paladins
- Steam AppID of the game:444090

## System Information
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Because GNU LIBC (GLIBC) have dropped DT_HASH a some years ago(Thanks Glibc high stable ABI, thanks thanks thanks), have more than 2 years that Paladins can't work because anticheat kicks during match, for some whatever reason trying build GLIBC with DT_HASH patch not working, idk if is necessary for elftools have be patch for work.
Have a way to Proton can make this work? a specific workaround for Anticheat or some thing similar?
Have a way to contact Hi-rex ?
Hi Rex don't look to fix this and bring this for linux (conspiracy theory time) (aluminum hat is ready to use)

**Comment by kisak-valve** [comment]
Hello @EliasTheGrandMasterOfMistakes, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1787#issuecomment-1810655897.

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> Hello @EliasTheGrandMasterOfMistakes, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#1787 (comment)](https://github.com/ValveSoftware/Proton/issues/1787#issuecomment-1810655897).

Thanks, sorry for my mistake
