### ISSUE TITLE
[Whilelist] Star Wars: Knights of the Old Republic (32370)

### ISSUE THREAD

**Issue by tbsteinb** [ValveSoftware/Proton#726]
All the game needs is a config tweak in the swkotor.ini file to set the resolution and it works perfectly. The reason for the tweak appears to occur in Windows itself as well (though not as consistently).

Specs: Proton 3.7-4, Artix Linux (Arch based), Steam flatpak install, NVIDIA Corporation GM206 [GeForce GTX 950] (rev a1)

**Comment by kisak-valve** [comment]
Hello @tbsteinb, this game is already being tracked at #550. Closing in favor of the existing issue report.
