### ISSUE TITLE
How to use Renderdoc with Proton?

### ISSUE THREAD

**Issue by Manipu1a** [ValveSoftware/Proton#7260]
Hello,
I'm trying to move game from pc to steam deck, but there are some graphics error.  I use steam devkit management tool, but it can't capture. 
Error Log: "Failed to create & inject :Renderdoc injection failed: Couldn't connect to target program.  Check that it didn't crash or exit during early initialisation, e.g. due to an incorrectly configured working directory."

**Comment by simifor** [comment]
How are you trying to attach renderdoc? If the game doesn't use opengl you can try adding the following enviironment variable to your game's launch parammeter `ENABLE_VULKAN_RENDERDOC_CAPTURE=1`
