### ISSUE TITLE
I Expect You To Die 2 & 3 - broken view projection on Proton Experimental

### ISSUE THREAD

**Issue by Supreeeme** [ValveSoftware/Proton#7262]
Using the current Proton Experimental (as of today, nov 16), I Expect You To Die 2 & 3 have broken view projections in the HMD. The eyes are not lined up properly, and turning left or right causes the world to appear to stretch. This does not occur on the stable Proton 8. Other games may be affected too but I've only run into it so far with these two. This was tested on an original HTC Vive.

**Comment by alasky17** [comment]
@Supreeeme Thank you for the report! I was able to reproduce and we are investigating why this regression happened.  We have some major changes in VR support right now in experimental, so regression reports like this are really helpful before the changes go to stable :)

**Comment by Supreeeme** [comment]
Just tested again today and it no longer seems to be an issue on Experimental, so I'll close this.
