### ISSUE TITLE
winhttp cannot receive more than max signed int bytes plus last buffer size on a get request

### ISSUE THREAD

**Issue by was421** [ValveSoftware/Proton#7264]
Tested: Proton Version 8.0-4

when pulling a large file (8gb) from S3 storage over a get request it fails at max int plus whatever the remaining buffer is, landing the total number of transferred bytes just over max signed int.

tests under windows do not result in the same outcome.

**Comment by ipr** [comment]
I think you should report this to Wine directly.

**Comment by hansleidekker** [comment]
This should be fixed with upstream Wine commit 75b41873e630c4c3ffd85976eceaf33ceaf7640a.

**Comment by alasky17** [comment]
The upstream wine commit shipped with Proton 9.0-beta.  @was421 Could you please retest this and close this issue if it is resolved?

**Comment by kisak-valve** [comment]
Closing pending feedback.
