### ISSUE TITLE
Apex Legends always recompiling using DX12

### ISSUE THREAD

**Issue by Freddycat** [ValveSoftware/Proton#7266]
# Compatibility Report
- Name of the game with compatibility issues: Apex Legends
- Steam AppID of the game: 1172470

## System Information
- GPU: GTX 1660 TI
- Video driver version: Mesa 23.2.1 NVIDIA 535/535 DKMS
- Kernel version: 6.6.0 (custom TKG kernel)
- Link to full system information report as [Gist](https://gist.github.com/): [Gist](https://gist.github.com/Freddycat/15d739292e28a5ea705cc6ff4c7094a3)
- Proton version: Latest/Any/GE 23/Proton experimental

## I confirm:
- [ *] that I haven't found an existing compatibility report for this game.
- [ *] that I have checked whether there are updates for my system available.

[steam-1172470.zip](https://github.com/ValveSoftware/Proton/files/13401170/steam-1172470.zip)

## Symptoms 
As of the most recent patch, (season 19) most of the time when I restart the game it compiles shaders from scratch, which takes about 20 minutes, rather inconsistently. I've had it happen after unexpected game close, after closing and opening the game for any reason from the menu after it's done compiling, not every time but MOST of the time, as well as every time I reboot my PC.
It used to be that when using DX12, it would compile once and then compile each map before you started playing each time, but not need to compile again unless there was an update or you update graphics drivers. I had steam set to NOT pre-cache vulkan shaders, and it worked perfectly for apex and every other game. Now I have tried everything, including these launch options: 
__GL_SHADER_DISK_CACHE_SIZE=4800000000 
__GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1
and adding those to the file /etc/environment
and shader pre-caching + allow processing in the background ON, but I still have to compile for 20 minutes + before playing the game each time, which is obviously very inconvenient for my friends. My alternative is switching back to DX11, which loads into the lobby much faster, but then it will not pre-cache the map which guarantees unplayable lag DURING the first 1-2 games, which is just not an option for me. 
Last detail, the folder where the game stores the shadercaches seems to always be at least ~25gb, but fluctuates to 40+gb and then seems to clear back down to 25. 
Anyways since it did work before, I'm hoping someone can shed some light on this issue here. Thanks!

## Reproduction

- Add -eac_launcher_settings SettingsDX12.json to launch options
- Allow shaders to compile, wait in lobby for map shader to compile
- Reboot game
- Shaders are compiling from the beginning again

**Comment by kisak-valve** [comment]
Hello @Freddycat, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1817593210.
