### ISSUE TITLE
What is the Proton version compatible with Geforce 600 series Kepler driver 470 ?

### ISSUE THREAD

**Issue by Augusto7743** [ValveSoftware/Proton#7268]
Hello.
Thanks for reading my topic.
What is the Proton version compatible with Geforce 600 video cards using driver 470 in Linux ?
Geforce 600 kepler is vulkan 1.2. VKD3D Proton current version requirements is Vulkan 1.3, but previous versions say Vulkan 1.2.
Well previous version works with Geforce 600 kepler driver 470 ?
I only want test few softwares and run a windows game d3d12 for see the performance.

Have an nice week.

**Comment by kisak-valve** [comment]
Hello @Augusto7743, Proton 7.0 was the last version that was compatible with the NVIDIA 470 series video driver.

Regardless of Proton version, it's highly likely you're going to encounter quirks and limitations when trying to run D3D12 games through VKD3D-Proton and the Kepler generation of NVIDIA hardware.

**Comment by Augusto7743** [comment]
Thanks for replying.
When you say "quirks and limitations" is Vulkan 1.3 use video card D3D12 features ?
I have copied the VKD3D Proton 2.6 (last version using Vulkan 1.2) in Proton 8.0. Game not start, but I not understand if is problem about VRAM requirement.
Only is for test.
Have an nice week.
