### ISSUE TITLE
Apex Legends

### ISSUE THREAD

**Issue by GentBinaku** [ValveSoftware/Proton#7269]
# Compatibility Report
- Name of the game with compatibility issues: Apex Legends
- Steam AppID of the game: 1172470

## System Information

Computer Information:
Manufacturer: ASUSTeK COMPUTER INC.
Model: PRIME H510M-K
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
CPU Family: 0x6
CPU Model: 0xa7
CPU Stepping: 0x1
CPU Type: 0x0
Speed: 4800 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Supported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Supported
AVX512VNNI: Supported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Ubuntu 22.04.3 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 6.2.0-36-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12101004
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20231024.64411
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce RTX 3060/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 470.223.02
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 164 Hz
VendorID: 0x10de
DeviceID: 0x2487
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 23.62" x 13.39" (27.13" diag), 60.0cm x 34.0cm (68.9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 12288 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: Realtek ALC897
Memory:
RAM: 23858 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 186655 MB
Largest Free Hard Disk Block: 132621 MB
Storage:
Number of SSDs: 3
SSD sizes: 500G,480G,240G
Number of HDDs: 0
Number of removable drives: 0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

[steam-1172470.log](https://github.com/ValveSoftware/Proton/files/13418409/steam-1172470.log)

## Symptoms 
Can't start the game

**Comment by kisak-valve** [comment]
Hello @GentBinaku, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1819629632.
