### ISSUE TITLE
[322170] Geometry Dash

### ISSUE THREAD

**Issue by TheBearodactyl** [ValveSoftware/Proton#7270]
# Compatibility Report
- Name of the game with compatibility issues: Geometry Dash
- Steam AppID of the game: 322170

## System Information
- GPU: Intel HD Graphics
- Video driver version: Mesa 23.2.1
- Kernel version: xanmod-6.6
- Link to full system information report as [Gist](https://gist.github.com/TheBearodactyl/529d61342961de5fd8dd717876b1be84):
- Proton version: Proton 8.0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-322170.log](https://github.com/ValveSoftware/Proton/files/13420958/steam-322170.log)

## Symptoms 
The game crashes every time I open it, and whenever it doesn't crash on the loading bar, it happens in the middle of editing a level.

## Reproduction
play the game.

**Comment by kisak-valve** [comment]
Hello @TheBearodactyl, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5304#issuecomment-1820103255.
