### ISSUE TITLE
Talos Principle 2 does not start

### ISSUE THREAD

**Issue by Leminski** [ValveSoftware/Proton#7275]
# Compatibility Report
- Name of the game with compatibility issues: Talos Principle 2
- Steam AppID of the game: 835960
[steam-835960.zip](https://github.com/ValveSoftware/Proton/files/13431932/steam-835960.zip)

## System Information
- GPU: NVIDIA Corporation NVIDIA GeForce RTX 3080/PCIe/SSE2
- Video driver version: Nvidia-driver-545 (545.29.02)
- Kernel version: 6.5.6-76060506-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Leminski/7b133cd9ca884c71738fd2b34d9a3b71
- Proton version: Experimental, 8.0-4 and 7.0-6

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game. (Not for it not starting. )
- [ X ] that I have checked whether there are updates for my system available. (All updated)

(Attached steam-835960.zip)

## Symptoms 
I can't get the game to run. I've tried different Proton versions, and the various commands listed on ProtonDB. It does not run. Simply a quick flash and then dies. I can't even screenshot it. I'm using X11 and once got sound using Wayland, but Wayland does not open Steam, and really that was only once. 

Running Steam via command line, then running the game gives the following:
https://gist.github.com/Leminski/08cd5c7084411291c1a6a4eecc10b1f6

I'm using Pop!_OS and an RTX3080. I've contacted Steam Support for help, who directed me here. 

LSHW: https://gist.github.com/Leminski/1f171bc98f075e85dc5d4f39da2562a8

## Reproduction
1. Install game. 
2. Double click Icon to run. 
3. Few seconds of nothing. 
4. Flashes a single frame of black. 
5. Dead. 

Thanks.

**Comment by kisak-valve** [comment]
Hello @Leminski, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7237#issuecomment-1821861462.

**Comment by Leminski** [comment]
Ok, sorry. I thought it would be a different issue. Thanks.

**Comment by Leminski** [comment]
Issue was that the game was attempting to run on the AMD iGPU that's on Ryzen 7000 CPUs. Disabling the iGPU in BIOS resolved the issue more or less entirely.
