### ISSUE TITLE
 Steam Linux | Path of Exile | Proton 8+ | comctl32.dll failed to initialize | Works with Proton 7

### ISSUE THREAD

**Issue by freddiehaddad** [ValveSoftware/Proton#7278]
# Compatibility Report
- Name of the game with compatibility issues: Path of Exile
- Steam AppID of the game: 238960

## System Information
- GPU: RX 7900 XTX
- Video driver version: Mesa 23.2.1
- Kernel version: 6.6.2
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 8 and Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

```text
40892.597:0124:0128:err:module:LdrInitializeThunk "COMCTL32.dll" failed to initialize, aborting
40892.597:0124:0128:err:module:LdrInitializeThunk Initializing dlls for L"Z:\\home\\freddiehaddad\\.local\\share\\Steam\\steamapps\\common\\Path of Exile\\PathOfExileSteam.exe" failed, status c0000005
```

https://gist.github.com/freddiehaddad/388bd33e062682a63ff0964ea78ef8e7

## Symptoms 

Game fails to start using Proton 8 and Proton Experimental, works with Proton 7.

Launch Options:

```bash
PROTON_LOG=1 WINEDLLOVERRIDES="version.dll=n,b" %command%
```

## Reproduction

1. Install Path of Exile via steam
2. Change launch options for game to:
   ```bash
   PROTON_LOG=1 WINEDLLOVERRIDES="version.dll=n,b" %command%
   ```
3. Download: https://github.com/RoseTheFlower/UltrawideIndex/releases/download/pathofexile/Path.of.Exile.Ultrawide.v1.1.zip
   1. Unzip archive to game directory.
   2. ```
      unzip ~/downloads/Path.of.Exile.Ultrawide.v1.1.zip -d ~/.local/share/Steam/steamapps/common/Path\ of\ Exile/
      ```
4. Attempt to launch game using Proton Experiment or Proton 8, game will not launch and logs will show the `comctl32.dll` error.
5. Switch to Proton 7 and game will launch.
   

<!--
1. You can find the Steam AppID in the URL of the shop page of the game.
   e.g. for `The Witcher 3: Wild Hunt` the AppID is `292030`.
4. You can find your driver and Linux version, as well as your graphics
   processor's name in the system information report of Steam.
6. You can retrieve a full system information report by clicking
   `Help` > `System Information` in the Steam client on your machine.
7. Please copy it to your clipboard by pressing `Ctrl+A` and then `Ctrl+C`.
   Then paste it in a [Gist](https://gist.github.com/) and post the link in
   this issue.
8. Also, please copy the contents of `Help` > `Steam Runtime Information` to
   the gist.
9. Please search for open issues and pull requests by the name of the game and
   find out whether they are relevant and should be referenced above.
-->

**Comment by kisak-valve** [comment]
Hello @freddiehaddad, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/58#issuecomment-1823369794.
