### ISSUE TITLE
League of Legends Patch Broken on Lutris

### ISSUE THREAD

**Issue by covalspace** [ValveSoftware/Proton#7281]
Please see https://forums.lutris.net/t/league-of-legends-reconnect-loop/19240 

Everyone is having the same issue with no success.

**Comment by kisak-valve** [comment]
Hello @covalspace, Proton is a fork of wine which is intended for use with the Steam for Linux client. The flavor of wine mentioned in that forum is elsewhere in the larger wine ecosystem and it doesn't look like there's any details that is useful for a Proton dev to ponder.

Sorry, but supporting Lutris is out of scope for this issue tracker.
