### ISSUE TITLE
Final Fantasy VII Remake Intergrade HDR mode doesn't work on the default Proton version

### ISSUE THREAD

**Issue by jams3223** [ValveSoftware/Proton#7287]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 1462040

## System Information
- GPU: Steam Deck Sephiroth
- Video driver version: Mesa 23.1.8
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: proton-7.0-3

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
Final Fantasy VII Remake Intergrade HDR mode doesn't work on the default Proton version but works when I choose the latest experimental branch.

**Comment by kisak-valve** [comment]
Hello @jams3223, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5415#issuecomment-1826348829.
