### ISSUE TITLE
LunarLux (1932680)

### ISSUE THREAD

**Issue by AlleyDismay** [ValveSoftware/Proton#7288]
# Compatibility Report
- Name of the game with compatibility issues: LunarLux
- Steam AppID of the game: 1932680

## System Information
- Link to full system information report as [Gist](https://gist.github.com/AlleyDismay/f8821eaa89436d1d8ad0fc5cc8ac7d2b):

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-1932680 - proton-7.0-6e ctd.log](https://github.com/ValveSoftware/Proton/files/13465176/steam-1932680.-.proton-7.0-6e.ctd.log)
[steam-1932680 - Shortest 6.3 Steam Overlay CTD.log](https://github.com/ValveSoftware/Proton/files/13465256/steam-1932680.-.Shortest.6.3.Steam.Overlay.CTD.log)

## Symptoms

Crashes after the publisher logo in Proton >=7.0-6e. Goes to start screen and beyond on lower versions. Making notes on Steam Overlay is really laggy and the NumLock doesn't work in it.

Only happened with this keyboard of mine as `lsub` reports:

`Bus 003 Device 007: ID 413c:2010 Dell Computer Corp. Keyboard` - SK-8135

My other keyboard was:

`Bus 003 Device 006: ID 04b3:301b IBM Corp. SK-8815 Keyboard` - SK-8815

..................

Sometimes it crashes when I try to use the Steam Overlay:

[steam-1932680 - Crashed on trying to Steam Overlay.log](https://github.com/ValveSoftware/Proton/files/13465224/steam-1932680.-.Crashed.on.trying.to.Steam.Overlay.log)

## Reproduction

Run the game in a Proton version 7.0-6e or higher, that's not Experimental. Experimental [bleeding-edge] as of Nov 28 10:29 EST seems to work fine, sometimes. Excepting this Overlay Crash:

[steam-1932680 - Experimental Seems to work, but Overlay CTD.log](https://github.com/ValveSoftware/Proton/files/13495794/steam-1932680.-.Experimental.Seems.to.work.but.Overlay.CTD.log)

And this one on next bootup attempt, but after that is fine?
[steam-1932680 - CTD Experimental Spinner Keyboard.log](https://github.com/ValveSoftware/Proton/files/13495809/steam-1932680.-.CTD.Experimental.Spinner.Keyboard.log)

**Comment by alasky17** [comment]
@AlleyDismay Could you give the model name/number for both of the keyboards?  Also - does the game crash anywhere if you disable steam overlay entirely?

**Comment by AlleyDismay** [comment]
@alasky17 - Added model numbers in the OP. ... In the keyboard that works okay, I've never had it crash unless it was from trying the Overlay sometimes.

And the latest version of Experimental can play at least 10+ minutes without crashing. Never seen a crash, just didn't feel like keeping it up longer.

**Comment by AJuujarvi** [comment]
@AlleyDismay I've been able to repro a similar issue, but not quite the same since mine doesn't seem to be tied to a keyboard or the steam overlay being on or off. I am hopeful the root cause is the same. I get a crash using Proton Experimental, Proton 7.0-6, and Proton 8.0-4c 90% of the time, with the occasional success. When it does crash, it crashes shortly after the dev splash screen, with various colors on the screen from the next intro video.

I was able to get a crash using 6.3-8. However it was rarely crashing, and usually working. When it did crash, it crashed on the Dev splash screen, before getting to the next video that has various colors.

Do either of these crashes seem familiar?

**Comment by AlleyDismay** [comment]
@AJuujarvi - For Experimental, are you using Bleeding Edge? Can you give crash logs with "PROTON_LOG=1 %command%"?

The Splash Screens go Freedom Games then CosmicNabob, my memories do fit that the crashes happen after CosmicNabob since after that's when the music starts.

Checking my 7.0-6 and 8.0-4c, they seem to work now. It seems that if it crashes once early, then it keeps doing so, but if it works, it keeps working. Not sure why.

**Comment by AJuujarvi** [comment]
@AlleyDismay Sure no problem if you wanted to take a look. I passed this along to our developers already for them to take a look. I can update here whenever they get a fix out for it. :) 
[crash-exp-be-steam-1932680.log](https://github.com/ValveSoftware/Proton/files/13516739/crash-exp-be-steam-1932680.log)

**Comment by AlleyDismay** [comment]
@AJuujarvi - Thanks! Yeah, this looks like my crash, if the last 9 lines are any indication.

"Assertion failed: !status && "vkQueuePresentKHR", file ../src-wine/dlls/winevulkan/loader_thunks.c, line 5551"

Very familiar.

**Comment by AlleyDismay** [comment]
I think it works now? It's been months since I've played this, so I'm not sure what, but something updated so that it now works on 8.05 and the 9 beta.

**Comment by alasky17** [comment]
@AlleyDismay It was likely a steam overlay update that fixed it.  Thank you for following up!

**Comment by AlleyDismay** [comment]
Since I don't have any problems now, I'm closing this.
