### ISSUE TITLE
"pfx is not owned by you" on EXT4 system

### ISSUE THREAD

**Issue by NeoRootPain** [ValveSoftware/Proton#7289]
I'm on Artix Linux, and I've been trying to share my library with another user on my computer, and although I did manage to share my library with him, with him being able to play some of my games, which are all native, games where I need to use proton, however, cannot run at all unless the user is logged into my account, which defeats the purpose of sharing a library

The error is something amongst the lines of "pfx is not owned by you"
I'm aware this is a common issue with NTFS filesystems, but I'm using an EXT4 system
I've already changed the owners of my library to a group called "Steam" which both users are included with chown, and I also changed the chmod to 770, -R option included, but the problem still persists

I've been looking for fixes for a while now, but no luck
What am I doing wrong here? Is there any way to solve or at least circumvent this?

**Comment by kisak-valve** [comment]
Hello @JuneSSai, this issue is already being tracked at #4820. Closing as a duplicate.
