### ISSUE TITLE
Burnout paradise can't start on resume

### ISSUE THREAD

**Issue by SaulNunez** [ValveSoftware/Proton#729]
On first start Burnout paradise runs ridiculously good. However after closing, probably after the save creation we can't return to that save file. It keeps on the loading screen previous to the car selection.

**Comment by kisak-valve** [comment]
Hello @SaulNunez, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/468#issuecomment-416229316.
