### ISSUE TITLE
HDR implementation broken in a couple Deck Playable titles without specific launch option

### ISSUE THREAD

**Issue by matte-schwartz** [ValveSoftware/Proton#7292]
I have been testing a lot of different games for HDR compatibility on my SD OLED, and I've found that some do not have functional HDR without the launch option `PROTON_ENABLE_AMD_AGS=1 %command%` 

Red Dead Redemption 2's HDR settings will not trigger the HDR badge in the quick settings menu without the `PROTON_ENABLE_AMD_AGS=1 %command%` launch option or the game is not set to Fullscreen. 

Assassin's Creed: Odyssey and Assassin's Creed: Origin will lock out HDR unless the game set to fullscreen in the game's settings menu, and `PROTON_ENABLE_AMD_AGS=1 %command%` in Steam's launch options.

There may be other Deck Verified/Playable titles I do not own that also have this issue + solution. There are also a couple of Non-Steam Games I've added as .exe files to Steam that have only had HDR with Proton Experimental, Fullscreen in-game settings, and `PROTON_ENABLE_AMD_AGS=1 %command%`: Death Stranding, Ratchet & Clank: Rift Apart. I'm unsure if the Steam versions need similar setup.

**Comment by kisak-valve** [comment]
Hello @matte-schwartz, this feedback needs to be evaluated on a per-game basis and can not be generalized.

I'm going to let this issue report sit open for visibility, but if you find any additional games with similar behavior, please add a note to the compatibility report for the separate game titles which need some attention from a Proton dev instead of commenting here.

**Comment by tehoblivious** [comment]
I've found some HDR games to be "fixed" having the reshade menu open (of course temporarily because you can't really play with the menu open) 
[examples of what i mean](https://www.youtube.com/watch?v=fY0L3IDc-v8)
I am so confused why it "fixes" HDR

**Comment by matte-schwartz** [comment]
closing this as Proton 9 and the AMD AGS changes appear to negate the need for this

**Comment by devurandom** [comment]
> closing this as Proton 9 and the AMD AGS changes appear to negate the need for this

Is AMD AGS enabled automatically in Proton 9?

I set `env PROTON_ENABLE_AMD_AGS=1 %command%` (cf. https://github.com/ValveSoftware/Proton/issues/7435) for Horizon Zero Dawn (cf. https://github.com/ValveSoftware/Proton/issues/4125) and the "HDR" setting is still greyed out.  (I have set the game to show on the screen that supports HDR.  HDR is enabled according to KDE display configuration and according to the monitor's own settings HUD.)  Doing the same for System Shock (cf. https://github.com/ValveSoftware/Proton/issues/6822), there is no HDR setting and no indication that HDR is working.

System:
```
Operating System: NixOS 24.05
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.2
Kernel Version: 6.10.0 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 9 6900HS with Radeon Graphics
Memory: 30,6 GiB of RAM
Graphics Processor: AMD Radeon Graphics
```

Window manager: https://invent.kde.org/-/snippets/3190

P.S. I now set `SDL_VIDEODRIVER=wayland`, `PROTON_ENABLE_AMD_AGS=1`, `ENABLE_HDR_WSI=1`, `DXVK_HDR=1` globally for Steam, and Horizon Zero Dawn enabled the HDR setting.  But when I switch it from "Off" (default) to "On" and press "Apply", the screen goes black for a while (only the mouse cursor stays visible and moves with the mouse).  When it returns to the settings menu, the HDR setting is "Off" again.

```
❯ flatpak info com.valvesoftware.Steam

Valve Corporation - Launcher for the Steam software distribution service

          ID: com.valvesoftware.Steam
         Ref: app/com.valvesoftware.Steam/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.0.79
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 45,5 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 173cd565d98d4951bd858bad290e8481a9e72dbf5f7c9c980165a060666184b1
      Parent: 98f034b154eed70b957bedcba0a5ce3785e70999b4aef85e1f6dd66f2eb15ff7
     Subject: Add pressure-vessel's overrides data dir to XDG_DATA_DIRS (ee358536)
        Date: 2024-04-03 13:45:40 +0000
```

**Comment by matte-schwartz** [comment]
You still need a compositor that composites and presents HDR properly, i.e. Gamescope, even with Plasma 6/KWin and the HDR Enabled checkbox enabled in your plasma display settings. AMD AGS in this scenario just tells the game that HDR is possible when all conditions are met.

What you are attempting right now without Gamescope won't be feasible for full HDR support until Proton is built with Wine Wayland. Until then, use `gamescope --hdr-enabled <all other launch options for Gamescope> -- %command%` which should work nested on Plasma 6 for you.
