### ISSUE TITLE
Game fails to launch; silently fails. (Pheonix Wright: Ace Attorney Trilogy and others)

### ISSUE THREAD

**Issue by jvan1234** [ValveSoftware/Proton#7294]
# Compatibility Report
- Name of the game with compatibility issues: Phoenix Wright Ace Attorney Trilogy
- Steam AppID of the game: 787480

## System Information
- GPU: GeForce GT 1030
- Video driver version: nvidia-driver-535
- Kernel version: 5.15.0-89-generic
- Link to full system information report as [Gist](https://gist.github.com/):[Link to Neofetch result](https://gist.github.com/jvan1234/ebfbea0623661209f36d8578436e8d79)
- Proton version: GE-Proton8-23

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-787480.log](https://github.com/ValveSoftware/Proton/files/13483470/steam-787480.log)

## Symptoms 
Whenever I attempt to run this game on my computer, it will say that it is starting, then quickly stop. No window appears displaying the game...

## Reproduction
1. Install game on exFAT partition (Holds other games that work without Proton)
2. Have similar specs
3. Use compatibility tool GloriousEggroll
4. Attempt to launch game
5. fail :(

**Comment by kisak-valve** [comment]
Hello @jvan1234, sorry, but exFAT lacks filesystem features that are required for Proton to run. The general recommendation is to use a Linux native filesystem with Proton.

This issue is already being tracked at #3835. Closing in favor of the older issue report.

**Comment by jvan1234** [comment]
Thank you! Will try
