### ISSUE TITLE
[Poton Experimental] The Last Of Us™ Part I

### ISSUE THREAD

**Issue by tojestzart** [ValveSoftware/Proton#7297]
# Compatibility Report
- Name of the game with compatibility issues:  The Last Of Us™ Part I
- Steam AppID of the game: https://store.steampowered.com/app/1888930/The_Last_of_Us_Part_I/

## System Information
- GPU:  RTX3050m 
- Video driver version:  535.129.03 
- Kernel version:  6.5.0-13-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/tojestzart/eb7496086155f12079077f2858e27c14
- Proton version: Proton Experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Sometimes it runs game after fresh reboot , sometimes it doesnt

## Reproduction
Run game
Wait
Nothing

[https://youtu.be/JWDs8z38XBg](url)

Sometimes it runs game sometimes doesnt, whats the cause?

**Comment by tojestzart** [comment]
[steam-1888930.log](https://github.com/ValveSoftware/Proton/files/13504172/steam-1888930.log)

**Comment by kisak-valve** [comment]
Hello @tojestzart, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6653#issuecomment-1832474881.
