### ISSUE TITLE
Winetricks + Proton?

### ISSUE THREAD

**Issue by SteveHeist** [ValveSoftware/Proton#73]
Question - do Winetricks and Proton get along? I tried to run a workaround that Call of Duty: Black Ops 2 needed (according to winehq), and it didn't seem to change anything.

If not, how do we configure the wine instances that Proton creates?

**Comment by E100Beta** [comment]
Please refer to https://github.com/ValveSoftware/Proton/issues/54

**Comment by SteveHeist** [comment]
Well, I did. And I tried.

`WINEPREFIX=~/.local/share/Steam/steamapps/compatdata/202970/pfx winetricks d3dx9 glsl-enable gdiplus`

It does change something, but I get this error sitting at the bottom of the steam log:

`pid 19054 != 19053, skipping destruction (fork without exec?)`.

I have the most up-to-date version of wine-stable currently installed separate from Proton. What might be the issue.

**Comment by C0rn3j** [comment]
If you get the game to launch (even into the menu), please ping me here with how you've done it. I've been trying to get it to run for about 3 years now.

**Comment by rosshadden** [comment]
I don't know what game that is and my situation certainly is not the same, but for my case I ran `WINEPREFIX=/media/data/games/proton/pfx winetricks vcrun2015` and it did work exactly as expected. Running things with that proton prefix have access to whatever was installed with winetricks.

**Comment by dreamer** [comment]
It was not mentioned yet, so just for the record - there's a proton-specific wrapper for winetricks called `protontricks` - at the moment it's hosted at https://github.com/Matoking/protontricks

@kisak-valve @SteveHeist I think there's no actual problem here? Can this issue be closed?
