### ISSUE TITLE
Burnout paradise can't use dedicated GPU

### ISSUE THREAD

**Issue by SaulNunez** [ValveSoftware/Proton#730]
Running on a **Nvidia GTX 960m** that has an Optimus setup. Currently using the options a stock Ubuntu installation has for it.
On Burnout Paradise there's a config screen when in Windows I could select which card to run. In Proton I can only select the integrated GPU, leading to a heavily downgraded experience.

**Comment by kode54** [comment]
Try changing the launch options to include the bumblebee launcher or whatever it is you normally run GL titles with?

`optirun %command%`

**Comment by kisak-valve** [comment]
Hello @SaulNunez, this issue fits better in #65, so I've transferred the issue report to https://github.com/ValveSoftware/Proton/issues/65#issuecomment-416230500.
