### ISSUE TITLE
Any old game that uses DirectInput that features a launcher cannot be controlled with joystick

### ISSUE THREAD

**Issue by hfc2x** [ValveSoftware/Proton#7303]
# Compatibility Report
- Name of the game with compatibility issues:
Any older game that features a launcher that doesn't close upon launch. This particularly affects Final Fantasy games, like VII and VIII
- Steam AppID of the game: [39150](https://steamdb.info/app/39150/) (Final Fantasy VIII)

## System Information
- Kernel version: 6.6.2
- Proton version: Latest Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
A game such as Final Fantasy VIII does not get controller input with Steam Input because whenever it launches, it keeps 2 windows open, and Steam only sends inputs to the first window.

The launcher window stays in the background receiving inputs, and blocking the inputs from reaching the game, which only responds to keyboard key presses.

This not only affects Final Fantasy VIII, but this is the most notable example I can name from the top of my head.

This happens with X11. Haven't tried Wayland.

This does not happen in Windows because the launcher is seemingly able to pass down the inputs to the game.

## Reproduction

1. Launch Steam Input configuration for Final Fantasy VIII, and set the controller's buttons. Don't set them as keyboard key presses.
2. Launch the game from Steam and check the input options in the provided launcher.
3. Launcher responds to controller buttons.
4. Launch the game through launcher.
5. Game doesn't receive any inputs _but the launcher does_.

**Comment by kisak-valve** [comment]
Hello @hfc2x, this feedback needs to be evaluated on a per-game basis, and we're using one issue report per unofficially supported game title. Since this issue report primarily focuses on Final Fantasy VIII, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/696#issuecomment-1836721048.

Feel free to also mention your findings on #694.

**Comment by hfc2x** [comment]
Okay
