### ISSUE TITLE
Bayonetta can't run on OpenMandriva Linux 23.10 Rome

### ISSUE THREAD

**Issue by satoayanami** [ValveSoftware/Proton#7309]
# Compatibility Report
- Name of the game with compatibility issues: Bayonetta
- Steam AppID of the game: 460790

## System Information
- GPU: 
- Video driver version:  
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/satoayanami/3ed8482059e2017302ebc0e69abe1c34
- Proton version: 8.0.4 & Proton Experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

[steam-460790.log](https://github.com/ValveSoftware/Proton/files/13538738/steam-460790.log)

## Symptoms 
I'm using Steam APP on OpenMandriva23.10 Linux AMD64, i've ran successfully the following games using Proton from 6 and up to 8.0-4c & experimental:

-Castlevania Lords Of Shadows APPID 234080
-Castlevania Lords Of Shadows 2 APPID 239250
-Pacman CEDX+ APPID 236450
-Saint Seiya Soldiers Soul  APPID 348710
-DOOM 64 APPID 1148590

Also, Steam installed by itself the runtimes "Sniper" and "Soldier.

When i try to run Bayonetta using Proton, on any version from 6 and up to experimental, the first time, the game compiled the vulkan shaders; then the game try to start, a window opens and closes quickly, and the game closes (can´t load)
![Screenshot_20231203_023101](https://github.com/ValveSoftware/Proton/assets/91169330/18bbb649-43ac-41d5-9d92-3082d3ec6009)

![Screenshot_20231203_052842](https://github.com/ValveSoftware/Proton/assets/91169330/02214ae4-9502-41ac-82cb-a4bdf20ed7ef)

![Screenshot_20231203_052858](https://github.com/ValveSoftware/Proton/assets/91169330/2a6bd391-756a-447e-84d6-9046a39efe04)

## Reproduction
Install OpenMandriva23.03 AMD64 on an AMD system without SMT (HT+)
Update the Operating System up to the 23.10 or newer version, make sure the system can run OpenGL and Vulkan games.
Download the Steam Linux APP from flathub at:
https://flathub.org/apps/com.valvesoftware.Steam
then install the Steam APP using the flatpak file.
I also tested Serious Sam 3 BFE with it's linux version and runs fine, so, you can use this as an OpenGL test.
Run Castlevania Lords of Shadows Ultimate Edition and Castlevania Lords of Shadows 2 in order to make sure that proton runs fine.
Run DOOM 64 using Vulkan API in order to make sure Vulkan runs fine.

Try to launch "Bayonetta" with proton versions from 6, and up to 8.0-4c and experimental.

**Comment by kisak-valve** [comment]
Hello @satoayanami, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/262#issuecomment-1837491044.
