### ISSUE TITLE
Sniper Elite 4 stuck launching until cache cleared

### ISSUE THREAD

**Issue by strattonbrazil** [ValveSoftware/Proton#7311]
# Compatibility Report
- Sniper Elite 4
- Steam AppID of the game: 312660

## System Information
- GPU: GTX 960
- Video driver version: 4.6.0 NVIDIA 535.129.03
- Kernel version: 6.2.0-37-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/strattonbrazil/3d215fab3742552c5c6bab3d535e0aa9
- Proton version: Experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

No logs generated

## Symptoms
Game Stuck "Launching" after play and reboot. No logs generated in home directory using `PROTON_LOG=1 %command%`. 

## Reproduction
- Hit "Play" to launch Sniper Elite 4 (launches Sniper Elite 4)
- Exit and restart system
- Hit "Play" to launch Sniper Elite 4
- (stuck)

## Workaround
- Clear the steam cache
- Restart system

**Comment by kisak-valve** [comment]
Hello @strattonbrazil, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2003#issuecomment-1838718879.
