### ISSUE TITLE
Elden Ring on RTX 6000 Ada

### ISSUE THREAD

**Issue by opyate** [ValveSoftware/Proton#7312]
# Compatibility Report
- Name of the game with compatibility issues: Elden Ring
- Steam AppID of the game: 1245620

## System Information
- GPU: RTX 6000 Ada (dual, but monitor is only plugged into one) (yes, sorry, not your typical gaming setup, but I'm winding down work over Xmas, and want to play something Souls-y)
- Video driver version: nvidia 535.129.03
- Kernel version: 6.5.0-13-generic
- Link to full system information report as [Gist](https://gist.github.com/opyate/80d14e5ad860bf2ecaaa2a81c28c5a79):
- Proton version: Experimental, 8.0-4, 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1245620.log](https://github.com/ValveSoftware/Proton/files/13551586/steam-1245620.log)

## Symptoms 

Game does not start. It shows a white screen and a black pointer in some cases, then exits. 

## Reproduction

I installed a brand new Ubuntu 23.10 today. Installed brand new Steam today. I also tried protons 8.0-4 and 7.0-6. I've tried some of the workarounds on ProtonDB, like `VKD3D_FEATURE_LEVEL=12_0` and copying `elden_ring.exe` over `start_protected_game.exe`.

**Comment by kisak-valve** [comment]
Hello @opyate, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1839565795.
