### ISSUE TITLE
Legend of Kay Anniversary crashes when playing videos

### ISSUE THREAD

**Issue by Aycros** [ValveSoftware/Proton#7313]
# Compatibility Report
- Name of the game with compatibility issues: Legend of Kay Anniversary
- Steam AppID of the game: 313810

## System Information
- GPU: RTX 3090
- Video driver version: Nvidia 545.29.06
- Kernel version: 6.6.3-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Aycros/5f92764787f2b2bb9d79b563f6164383
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game crashes as soon as you start a new game. From what I found online, it has to do something with the videos of the game that probably use the Media Foundation codec.

## Reproduction
Start a new game.

[steam-313810.log](https://github.com/ValveSoftware/Proton/files/13589292/steam-313810.log)

**Comment by kisak-valve** [comment]
Hello @Aycros, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/962#issuecomment-1843352878.
