### ISSUE TITLE
TOSS!🍌 (1270460)

### ISSUE THREAD

**Issue by purplebar0** [ValveSoftware/Proton#7314]
# Compatibility Report
- Name of the game with compatibility issues: TOSS!
- Steam AppID of the game: 1270460

## System Information
- GPU: AMD Radeon RX 6600 XT
- Video driver version: mesa 1:23.2.1-2
- Kernel version: linux-zen 6.6.4.zen1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/purplebar0/8c161b1e325d168bab555c2641e26dd6
- Proton version: 8.0-4
- SteamVR version: 2.1.9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Proton and game log:
[steam-1270460.log](https://github.com/ValveSoftware/Proton/files/13591644/steam-1270460.log)
[Player.log](https://github.com/ValveSoftware/Proton/files/13591651/Player.log)

## Symptoms
The game crashes in the first few seconds. Seems to be OVRPlugin or OpenXR-related.

## Reproduction
1. Start SteamVR
2. Start the game
3. Crash

**Comment by kisak-valve** [comment]
Hello @purplebar0, it might be interesting to test if the game gets further with Proton Experimental.

**Comment by purplebar0** [comment]
> Hello @purplebar0, it might be interesting to test if the game gets further with Proton Experimental.

Nope, no difference sadly.

**Comment by purplebar0** [comment]
[Apparently way overdue](https://www.protondb.com/app/1270460), but the game appears to work perfectly fine after Proton updates.
