### ISSUE TITLE
Naraka Bladepoint Texture visual bugs (1203220)

### ISSUE THREAD

**Issue by Milor123** [ValveSoftware/Proton#7315]
# Compatibility Report
- Name of the game with compatibility issues: Naraka Bladepoint
- Steam AppID of the game: 1203220

## System Information
- GPU: GTX 1050ti
- Video driver version:  NVIDIA Proprietary version 545.29.06
- Kernel version: 6.6.1-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:16 +0000 x86_64 GNU/Linux

## System Information (Neofetch)
OS: Manjaro Linux x86_64 
Kernel: 6.6.1-zen1-1-zen 
Uptime: 4 hours, 41 mins 
Packages: 2194 (pacman) 
Shell: zsh 5.9 
Resolution: 1920x1200 
DE: Cinnamon 6.0.0 
WM: Mutter (Muffin) 
WM Theme: Mint-L-Dark-Teal (Mint-Y) 
Theme: Mint-L-Dark-Teal [GTK2/3] 
Icons: Papirus-Adapta-Nokto-Maia [GTK2/3] 
Terminal: tilix 
CPU: 13th Gen Intel i5-13500 (20) @ 4.800GHz 
GPU: NVIDIA GeForce GTX 1050 Ti  Driver Version: 545.29.06
GPU: Intel AlderLake-S GT1 
Memory:  47471MiB 

- Proton version: ProtonGE 8-25  (Also tested with Proton 8.0-4c and Proton Experimental) 

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Proton log

[1203220.log](https://github.com/ValveSoftware/Proton/files/13605209/1203220.log)

##  What's the problem? 

The issue is that the game loads with some malformed or distorted textures, as if they were placed randomly, as shown in the following images:

![image](https://github.com/ValveSoftware/Proton/assets/14153649/aad9f580-df44-4cf0-8de8-943e93137e76)
![image](https://github.com/ValveSoftware/Proton/assets/14153649/4fd03501-f9b4-493f-982b-d208afa5c80e)
![ksnip_20231205-173649](https://github.com/ValveSoftware/Proton/assets/14153649/e2b1e941-bf9a-4faa-8840-fff8a8809994)

I've tried many things to fix it, such as clearing the ~/.cache/nvidia folder, also clearing the Steam caches, disabling shaders in Steam, re-enabling them, using only ESYNC, switching to only FSYNC, changing settings in DXVK, and clearing the DXVK cache. I've also reset the wineprefix, even installed SteamStinkerLaunch to try more options in the hope of finding a solution. This happened suddenly because it used to work fine.

I should mention that the game is installed on an HDD, but I have symbolic links from the Steam cache and compatdata to my root SSD ~/ (My operating system runs on an SSD).

I've also tried changing different GPU environment variables, such as:
```
__GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1 __GL_YIELD=USLEEP __GL_MaxFramesAllowed=0 __GL_THREADED_OPTIMIZATIONS=1
```

## About of my settings

My grub have this:
```
GRUB_CMDLINE_LINUX_DEFAULT="quiet nvidia_drm.modeset=1 apparmor=1 security=apparmor udev.log_priority=3"
```

My nvidia settings in xorg have:

```
Section "Device"
        Identifier "NVIDIA Card"
        Driver     "nvidia"
        VendorName "NVIDIA Corporation"
        BoardName  "GeForce GTX 1050 Ti"
        Option     "ForceCompositionPipeline" "On"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
EndSection
```

### And in modprobe:
```
options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp
```

[60-nvidia.rules.txt](https://github.com/ValveSoftware/Proton/files/13605362/60-nvidia.rules.txt)
[nvidia.conf.txt](https://github.com/ValveSoftware/Proton/files/13605363/nvidia.conf.txt)

The game is optimized, and all graphics settings are set to the minimum.

What should i try guys? Thank u very much!

**Comment by kisak-valve** [comment]
Hello @Milor123, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4907#issuecomment-1846164822.

**Comment by lboklin** [comment]
There are reports that changing to DX12 in the game's settings fixes the problem. However, the option to select anything but DX11 is greyed out for me. Is there some launch option I can use to enable it?

**Comment by Milor123** [comment]
> There are reports that changing to DX12 in the game's settings fixes the problem. However, the option to select anything but DX11 is greyed out for me. Is there some launch option I can use to enable it?

Its true, now i use 4070 and the direct x12 is enable for me, and it working without bugs not like dx11.

But i am not sure like force it to enable in our old cards.

**Comment by zss192** [comment]
> There are reports that changing to DX12 in the game's settings fixes the problem. However, the option to select anything but DX11 is greyed out for me. Is there some launch option I can use to enable it?有报告称，在游戏设置中更改为 DX12 可以解决该问题。但是，除了 DX11 之外的任何选择选项对我来说都是灰色的。我可以使用一些启动选项来启用它吗？

This problem has also troubled me for a long time. You can try setting it in the steam launch options: `WINEFSYNC=1 gamemoderun PROTON_ENABLE_NVAPI=1 DXVK_ASYNC=1 %command%`,Then you can see the dx12 option

**Comment by zss192** [comment]
> There are reports that changing to DX12 in the game's settings fixes the problem. However, the option to select anything but DX11 is greyed out for me. Is there some launch option I can use to enable it?

This problem has also troubled me for a long time. You can try setting it in the steam launch options: `WINEFSYNC=1 gamemoderun PROTON_ENABLE_NVAPI=1 DXVK_ASYNC=1 %command%`,Then you can see the dx12 option

**Comment by lboklin** [comment]
> > There are reports that changing to DX12 in the game's settings fixes the problem. However, the option to select anything but DX11 is greyed out for me. Is there some launch option I can use to enable it?
> 
> This problem has also troubled me for a long time. You can try setting it in the steam launch options: `WINEFSYNC=1 gamemoderun PROTON_ENABLE_NVAPI=1 DXVK_ASYNC=1 %command%`,Then you can see the dx12 option

This unfortunately didn't fix it for me. I have a GTX 1070, for the record. Some claim that DX12 is only available to RTX cards. I don't know why, and I wonder if it can be bypassed somehow.

**Comment by Milor123** [comment]
> > > There are reports that changing to DX12 in the game's settings fixes the problem. However, the option to select anything but DX11 is greyed out for me. Is there some launch option I can use to enable it?
> > 
> > This problem has also troubled me for a long time. You can try setting it in the steam launch options: `WINEFSYNC=1 gamemoderun PROTON_ENABLE_NVAPI=1 DXVK_ASYNC=1 %command%`,Then you can see the dx12 option
> 
> This unfortunately didn't fix it for me. I have a GTX 1070, for the record. Some claim that DX12 is only available to RTX cards. I don't know why, and I wonder if it can be bypassed somehow.

It neither work in my gtx 1050ti and the dxvk spoof neither.
