### ISSUE TITLE
[Whitelist] Geometry Dash

### ISSUE THREAD

**Issue by SaulNunez** [ValveSoftware/Proton#732]
It's a pretty simple game. Playing on levels seems fine and downloading and playing levels from other players work.

Running on:
- Ubuntu 18.04.1
- Intel Core i7 4720HQ
- 8 GB RAM

**Comment by vanyasem** [comment]
It's already whitelisted

**Comment by kisak-valve** [comment]
Closing per https://steamcommunity.com/games/221410/announcements/detail/1696055855739350561.
