### ISSUE TITLE
Savant - Ascent REMIX (2279330)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#7321]
# Compatibility Report
- Name of the game with compatibility issues: Savant - Ascent REMIX
- Steam AppID of the game: 2279330

## System Information
- 1 TB LE OLED steam deck 
- Proton version: Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game is marked as verified on deck, yet it has some major performance issues that keep it from feeling like an enjoyable experience. Here are some things I've noticed.

When starting a level in game, on the stable version chosen (8.0-4) and Experimental, the game seems to freeze up for like around 11 seconds before playing the level select noise and loading the level. On 6.3-8 and 7.0-6, it chimes right away and loads the level in 5 seconds.

In proton stable and Experimental, there is a noticable 1 second freeze hitch when you grab a cd which is not present on 6.3-8 (Could not check 7.0-6 cause it wouldn't pick up my controller.)

According to protondb, there are more instances in this game where it seems to hitch up alot more, might not be deck only issue.
[steam-2279330.log](https://github.com/ValveSoftware/Proton/files/13621713/steam-2279330.log)

## Reproduction
Easiest performance hitches to check is to start the tutorial or first level (whether you start for the first time or do the level select, it doesn't matter)

For the other 1 second hitch, start the first level and shoot the enemies till you get to the chest, blast the chest open and grab the disc using x

**Comment by alasky17** [comment]
@waspennator Thank you for the report! I was able to reproduce this hitching and we are looking into it.  In the meantime, I am planning to set the default Proton version to 7.0-6 so that it can maintain its verified status :)  You mentioned that you had trouble with a controller on 7.0-6 though which I could not reproduce.  Could you confirm if you are still seeing problems with your controller on 7.0-6 and if so, which controller is it?

**Comment by waspennator** [comment]
> @waspennator Thank you for the report! I was able to reproduce this hitching and we are looking into it. In the meantime, I am planning to set the default Proton version to 7.0-6 so that it can maintain its verified status :) You mentioned that you had trouble with a controller on 7.0-6 though which I could not reproduce. Could you confirm if you are still seeing problems with your controller on 7.0-6 and if so, which controller is it?

Tried it out again and it seems to work control wise, had an issue where sometimes it wouldn't pick up the deck controls and I had to exit and reopen the game, dunno if that's a game or proton issue.

Otherwise yeah, tried out the game on 7.0-6 and it was smooth from what I see, no hitches when grabbing disks.

**Comment by waspennator** [comment]
Game runs smooth now on my end with Experimental, didn't notice any 11 second hitches when loading levels or 1 second freezes when picking up discs.

@alasky17 
Dunno if this fix is or will be in 8.0-5 or not, but if it's not, id say the game should be set to Experimental till it gets pushed in.

**Comment by waspennator** [comment]
I can see this fix made it to proton 9.0, guess whenever the game can be set back to using that, I can close the report since it's currently pinned to 7.0-6.

**Comment by alasky17** [comment]
@waspennator Thank you for the update! The great post-rebase repinning effort is in progress, but it generally takes some time to update :)

**Comment by waspennator** [comment]
Closing since game has been set to proton Experimental
