### ISSUE TITLE
Elite: Dangerous Assertion failed: !status, file ../src-wine/dlls/winevulkan/loader.c, line 664

### ISSUE THREAD

**Issue by VortexAcherontic** [ValveSoftware/Proton#7323]
# Compatibility Report
- Name of the game with compatibility issues: Elite: Dangerous
- Steam AppID of the game: 359320

## System Information
- GPU: RTX 3080
- Video driver version: NVIDIA 545.29.6
- Kernel version: 6.6.3-1-default
- Link to full system information report as [Gist](https://gist.github.com/VortexAcherontic/2dbd976e130f4d0e26e3dfbb3a70a76c):
- Proton version: 1701933636 experimental-8.0-20231207

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-359320.log](https://github.com/ValveSoftware/Proton/files/13624081/steam-359320.log)

## Symptoms
The game does not start and claims do have ran into an Assertion failed: !status, file ../src-wine/dlls/winevulkan/loader.c, line 664  
Looking up the specified line in winevulkan revealed it's an issue which is present on nvidia + Wayland by choosing the wrong swap chain?
```
663: status = UNIX_CALL(vkCreateSwapchainKHR, &params);
664: assert(!status);
```
Looking up this error revealed an [nvidia bug](https://forums.developer.nvidia.com/t/negativo17-wayland-vkcreateswapchainkhr-returns-vk-error-initialization-failed/215593/1) report which is marked as closed and is over a year old. 

I run Steam from flatpak with runtime 23.08 with the latest nvidia driver runtime which ships `libnvidia-egl-wayland.so.1.1.12` according to the report this issue should be fixed with 1.1.10.

Since I have no clue about any of this I start reporting it here. If it is not an issue by Proton but something else, please let me know and I'll pass the issue to the correct people.

## Reproduction
1) Install Elite: Dangerous
2) Have a nVidia GPU with the latest proprietary driver
3) Run a Wayland session
4) Launch the game

Side note: Game runs fine on Steam Deck btw. But no surprise as this seems only be an issue with nvidia + wayland.

**Comment by kisak-valve** [comment]
Hello @VortexAcherontic, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/150#issuecomment-1848411926.
