### ISSUE TITLE
Ace Combat 7 opens no game window on Proton 8.0.4

### ISSUE THREAD

**Issue by hirak99** [ValveSoftware/Proton#7327]
# Compatibility Report
- Name of the game with compatibility issues: Ace Combat 7: Skies Unknown
- Steam AppID of the game: 502500

## System Information
- GPU: RTX 3090
- Video driver version: nvidia 545.29.06
- Kernel version: 6.6.4
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/hirak99/b31daeddf5355bd200532fb144a656d8
- Proton version: 8.0.4

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

(Proton logs compress well if needed.)--> [steam-502500.log.gz](https://github.com/ValveSoftware/Proton/files/13625412/steam-502500.log.gz)

## Symptoms

The game shows no window, even though Steam UI's "PLAY" turns into "STOP" as if the game has launched and remains there.

## Reproduction

- Set Proton version to 8.0.4.
- Launch the game clicking "PLAY".
- "PLAY" turns into "LAUNCHING", and then to "STOP".
- No game window is visible; but Steam UI thinks the game has launched.
- Eventually you'll need to click "STOP" from Steam to kill whatever process may be running in the background as the game.

**Comment by kisak-valve** [comment]
Hello @hirak99, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2307#issuecomment-1848630930.
