### ISSUE TITLE
TitanFall2 --> EA App: crashing every launch (background services crashed/the app crashed unexpectedly)

### ISSUE THREAD

**Issue by tjbbjt** [ValveSoftware/Proton#7328]
## Compatibility
---------------------
TitanFall 2
AppID: 1237970

## System Information
------------------------------
- Radeon VII
- Mesa 23.2.1
- 6.6.4
- Proton Experimental (and many others)
- Currently running steam in Bazzite-Arch container on Fedora Workstation but experienced the same crashes on RPM fusion steam 

## I confirm:
----------------
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.
- [steam-1237970.log](https://github.com/ValveSoftware/Proton/files/13626844/steam-1237970.log)

## Symptoms
------------------
Upon launching TitanFall 2 EA app installs fine, clicking through "Lets go" brings me to the "Background services crashed" screen restarting the app results in "The app crashed unexpectedly" screen. Launching game again goes to "Preparing game..." screen then is followed up by "The app crashed unexpectedly" and restarting the EA App to fix as it suggests results in "Background services crashed" screen again. The "Preparing game" screen tells me my steam account being linked to EA is being seen but the background services crash before the game launches.

## Reproduction
----------------------
Same thing happens every time game is launched. Also not getting any minimized EA taskbar item.

Removing compat folder starts the EA app reinstall cycle all over again.

Tried Northstar/GE Protons/Bottles/Lutris. Lutris can actually connect to EA account and my games are shown in Lutris after connecting the account but the moment I run the EA launcher it crashes in the same way as steam.

There are no SELinux warnings inhibiting wine. IPv6 is disabled in kernel, enabling IPv6 hasn't resolved this issue.  

Every Steam game works great with different Proton's unless this new EA app gets in the mix, the moment that happens nothing works.

**Comment by kisak-valve** [comment]
Hello @tjbbjt, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4001#issuecomment-1848968584.
