### ISSUE TITLE
Mechabellum (669330)

### ISSUE THREAD

**Issue by darkranger-red** [ValveSoftware/Proton#7329]
# Compatibility Report
- Name of the game with compatibility issues: Mechabellum
- Steam AppID of the game: 669330

## System Information
- OS: Fedora Linux 38 (Workstation Edition)
- KERNEL: 6.6.4-100.fc38.x86_64
- CPU: AMD FX-8350 Eight-Core
- GPU: NVIDIA GeForce GTX 1650
- GPU DRIVER: NVIDIA 545.29.06
- RAM: 16 GB

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
- Proton (Experimental) logs: [proton_log_experimental.tar.gz](https://github.com/ValveSoftware/Proton/files/13627120/proton_log_experimental.tar.gz)

## Symptoms 
The game's screen easily freezes and overall not playable on my system via Proton 8.0-4 and Proton Experimental. Only Proton 7.0-6 does not have such problem and fully playable.  But I also noticed there is some difference in the background of the main screen between 7.0-6 and 8.0-4 (also Experimental). Only 8.0-4 and Experimental have the dynamic background animation.

## Reproduction
Just run the game with the specified Proton version.

Proton 7.0-6 (Cannot see the background animation but the game is playable):
![game_screen_proton_7](https://github.com/ValveSoftware/Proton/assets/1746153/4b4796cf-4a58-4c3d-9c7a-d43de4e4895b)
Proton 8.0-4 (Freezes and not playable):
![game_screen_proton_8](https://github.com/ValveSoftware/Proton/assets/1746153/d9882b61-352e-4350-a09c-dc2965692bdb)
Proton Experimental (Freezes and not playable):
![game_screen_proton_experimental](https://github.com/ValveSoftware/Proton/assets/1746153/f86c9dfd-9bf3-4524-a4dc-eef3160e95db)

**Comment by alasky17** [comment]
@darkranger-red Could you try adding this as a launch option? - 
"DXVK_MONITOR_FALLBACK=1  %command%" 

If that doesn't fix the crashing, could you get a new log with that launch option set and some extra logging channels?  You can stack launch options like this: 

DXVK_MONITOR_FALLBACK=1 PROTON_LOG=+quartz,+strmbase,+strmbase_qc,+gstreamer,+amstream,+qcap,+qcap_v4l,+qedit,+mciqtz,+mci,+mfplat,+gstreamer,+evr,+dxva2,+wmvcore %command%

**Comment by darkranger-red** [comment]
Hello,

Yes, I can provide the updated Proton logs. Please see the attached archive. Unfortunately the problem remains via Proton 8.0-4 and Proton Experimental, after the additional "DXVK_MONITOR_FALLBACK=1" being applied.

I am curious about the DXVK_MONITOR_FALLBACK argument. It seems lack of documentation to explain this functionality?

[proton_log_experimental_1216.tar.gz](https://github.com/ValveSoftware/Proton/files/13691569/proton_log_experimental_1216.tar.gz)

**Comment by rbernon** [comment]
Could you try with only `WINEDLLOVERRIDES=winegstreamer=d %command%` and see if performance is better? This should disable the background video playback and isolate that from the other possible parameters.

> I am curious about the DXVK_MONITOR_FALLBACK argument. It seems lack of documentation to explain this functionality?

This is just an internal and temporary workaround that we can enable for hand-picked games. It's not documented because we intend to get rid of it.

**Comment by darkranger-red** [comment]
OK.... after using `WINEDLLOVERRIDES=winegstreamer=d %command%`, the background video is indeed gone on Proton 8.0-4 and Experimental, so the screen is just as same as 7.0-6. But the performance still freezes unfortunately, and it seems doesn't get any better on my system. I hope this information could be helpful.

**Comment by rbernon** [comment]
Thanks, at least it rules out the video playback from the culprit and it means that it comes from something else. I can see some unusual wineserver load, when that game runs, that might be worth investigating.

**Comment by darkranger-red** [comment]
I just realized there is something odd between fullscreen and windowed mode. Switched to the latter is actually playable on Proton 8 and Experimental. So I found #7206 and disabled "Force Composition Pipeline" in nvidia-settings. Now the game is fully playable and does not need to fall back to Proton 7. It seems to be the duplicate bug of that issue.
