### ISSUE TITLE
Docker support for building/shipping/testing locally

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#733]
The build process for linux is pretty bad, in my opinion. I would propose implementation of docker as a way of making the build pipeline easier and more robust.

There is a pull request open for the steam runtime I've reached out to, so we can get that integrated. If I don't hear back I'll start cracking away locally and seeing where it is messing up, and making another PR. 

If done right, docker can unify build/devel process for windows, mac, and linux.

https://github.com/ValveSoftware/steam-runtime/pull/91

**Comment by flukejones** [comment]
Given the current issue with dxvk building on macOS (#497) this would likely be very helpful.

**Comment by Nephyrin** [comment]
That PR is in fact a prerequisite for work on making Proton's build system more robust.  I should have some PRs to that effect this week.

**Comment by tingvarsson** [comment]
Speaking of building dxvk, there already is a docker image available for that specifically: https://github.com/cheald/dxvk-docker/

**Comment by Nephyrin** [comment]
#793 Adds support for builds that use the ValveSoftware/steam-runtime#91 docker images and are greatly reduced in setup requirements.  dxvk/mingw-w64 remains as a host-setup pain point.

**Comment by Nephyrin** [comment]
Proton now uses docker for building by default
