### ISSUE TITLE
Portal RTX is not working with last NVIDIA drivers

### ISSUE THREAD

**Issue by jgmatu** [ValveSoftware/Proton#7330]
# Compatibility Report
- Portal RTX
- Steam AppID 2012840

## System Information
- GPU: NVIDIA GeForce RTX 4070 Ti
- Video driver version: 546.29.0
- Kernel version: Windows 11 Pro 22H2 10.0.22621 Build 22621
- Link to full system information report as [system.txt](https://github.com/ValveSoftware/Proton/files/13628058/system.txt)
- Proton version: <?>

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

The intialize of vkCreateDevice is failing on wrapper.cpp:408 

_**warn: [06.12.2023 19-28-53][streamline][error]wrapper.cpp:408[vkCreateDevice] vkCreateDevice failed
err: DxvkAdapter: Failed to create device**_

I am using config rtx default files downloaded from steam. I played the game on January 2023 and it worked correctly.

## Reproduction

Go to steam library -> play game -> The game will not launch anymore.

## Data to reproduce the issue

[dxvk.txt](https://github.com/ValveSoftware/Proton/files/13628073/dxvk.txt)
[hl2_d3d9.log](https://github.com/ValveSoftware/Proton/files/13628032/hl2_d3d9.log)
[hl2_d3d9.txt](https://github.com/ValveSoftware/Proton/files/13628033/hl2_d3d9.txt)
[metrics.txt](https://github.com/ValveSoftware/Proton/files/13628034/metrics.txt)
[rtx.txt](https://github.com/ValveSoftware/Proton/files/13628035/rtx.txt)
[steam_appid.txt](https://github.com/ValveSoftware/Proton/files/13628036/steam_appid.txt)
[thirdpartylegalnotices.txt](https://github.com/ValveSoftware/Proton/files/13628037/thirdpartylegalnotices.txt)

**Comment by kisak-valve** [comment]
Hello again @jgmatu, sorry, I missed which operating system you are using with your feedback yesterday. DXVK is most commonly used as a part of Proton, and Proton is a compatibility layer for running Windows based games on Linux. Since you're running the game on Windows, Proton isn't involved at all.

This feedback needs to go to https://github.com/doitsujin/dxvk for a DXVK dev to ponder.

Closing as out of scope for this issue tracker.

**Comment by jgmatu** [comment]
Thanks for your guide kisak!
