### ISSUE TITLE
Proton doesn't work

### ISSUE THREAD

**Issue by stefan11111** [ValveSoftware/Proton#7331]
#### Your system information

* Steam client version (build number or date): 1701289036
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I tried to play TW3 with proton, however it doesn't work.
Not only it doesn't work, all the games that I tried to play with proton didn't work. I tried to play 140(https://store.steampowered.com/app/242820/140/), cs 1.6, cs2 and they also didn't run via proton, though they work fine natively.

Here is a log from 140(tiny game) when run with PROTON_LOG=1 %command%:
https://gist.github.com/stefan11111/092ba361951405de08cfcc1447ea269b

#### Steps for reproducing this issue:

1. Try to open game with proton.
2. Game Doesn't open.
3.

**Comment by kisak-valve** [comment]
Hello @stefan11111, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put them in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by stefan11111** [comment]
> Hello @stefan11111, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put them in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

System info:
https://gist.github.com/stefan11111/73cb7af0dc09961c9673243f4aca6ee1

System runtime diagnostics:
https://gist.github.com/stefan11111/044cd8e000735e281c46c18e7aca8d4d

**Comment by kisak-valve** [comment]
Thanks, it looks like your system is configured to run OpenGL on your Intel Tigerlake GPU, but Vulkan is forced to only have access to your NVIDIA GTX 1650. It might be interesting to test how a game behaves mesa/ANV being available and without `VK_DRIVER_FILES` and `VK_ICD_FILENAMES` set. The intent of that test would be to see if there's a usable render path when given a chance to only use the GPU that X and the user session is running on.

Then separately test how a game behaves with the game's launch options set `__NV_PRIME_RENDER_OFFLOAD=1 %command%` to enable NVIDIA's optimus layer.

**Comment by stefan11111** [comment]
> Thanks, it looks like your system is configured to run OpenGL on your Intel Tigerlake GPU, but Vulkan is forced to only have access to your NVIDIA GTX 1650. It might be interesting to test how a game behaves mesa/ANV being available and without `VK_DRIVER_FILES` and `VK_ICD_FILENAMES` set. The intent of that test would be to see if there's a usable render path when given a chance to only use the GPU that X and the user session is running on.
> 
> Then separately test how a game behaves with the game's launch options set `__NV_PRIME_RENDER_OFFLOAD=1 %command%` to enable NVIDIA's optimus layer.

Please tell me how exactly I need to run these tests.
What launch options should I set?
Should I then post the log with PROTON_LOG=1 %command%?

I tried adding __NV_PRIME_RENDER_OFFLOAD=1 %command%, but the game didn't launch.

**Comment by stefan11111** [comment]
I got this to work with a proper xorg.conf
