### ISSUE TITLE
Pinball FX (2328760) : Freeze on Pinball Noir table

### ISSUE THREAD

**Issue by Dinjoralo** [ValveSoftware/Proton#7333]
# Compatibility Report
- Name of the game with compatibility issues: Pinball FX
- Steam AppID of the game: 2328760

## System Information
- 1 TB OLED Steam Deck
- Proton version: 8.0.4, Experimental
- https://gist.github.com/Dinjoralo/ce39b8d000c83c0e14c69cd2f6aabcfb

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When playing the "Pinball Noir" table in Pinball FX, landing certain shots causes the game to freeze. 

## Reproduction

1. Start the game and start a game on the "Pinball Noir" table. 
2. Upon starting the game, launch the ball with the right stick and make the following shot with the triggers:
![image](https://github.com/ValveSoftware/Proton/assets/2925248/9678ef46-e153-4431-bd22-f8375c0ade8f)
[steam-2328760.log](https://github.com/ValveSoftware/Proton/files/13630263/steam-2328760.log)

After a moment, the game will stutter and then freeze completely.

**Comment by kisak-valve** [comment]
Hello @Dinjoralo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7109#issuecomment-1849234746.
