### ISSUE TITLE
Most games can't start, Unity issue?

### ISSUE THREAD

**Issue by Deleetdk** [ValveSoftware/Proton#7334]
# Compatibility Report
- Name of the game with compatibility issues: Many, but Minion Masters used to work, and now suddenly doesn't.
- Steam AppID of the game: https://store.steampowered.com/app/489520/Minion_Masters/

## System Information
- GPU: AMD Radeon RX 6650 XT (navi23, LLVM 16.0.6, DRM 3.54, 5.15.0-89-generic)
- Video driver version: AMD driver: amdgpu v: 6.2.4
- Kernel version: x86_64 Linux 5.15.0-89-generic
- Link to full system information report as [Gist](https://gist.github.com/Deleetdk/76116c43ff6e7aca42804dc57a2ae57c):
- Proton version: experimental, 1701933636 experimental-8.0-20231207

Proton log:
[steam-489520.log](https://github.com/ValveSoftware/Proton/files/13639016/steam-489520.log)

## Symptoms
Game can't open. Briefly flashes some small window. Video: 
[steam launch error-2023-12-11_18.41.18.mkv.zip](https://github.com/ValveSoftware/Proton/files/13639118/steam.launch.error-2023-12-11_18.41.18.mkv.zip)

## Reproduction
Just open the game.

**Comment by kisak-valve** [comment]
Hello @Deleetdk, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

`v: 4.6 Mesa 23.2.0-devel` makes it look like you're using a random, mildly dated git build of mesa. Can you test how the game behaves with a current point release of mesa?

**Comment by n00btube3D** [comment]
I'm not an expert on Proton, but `Required Vulkan extension VK_KHR_surface not supported` in your proton log suggests a driver problem. What is the output of `vulkaninfo`? You should try repo drivers as suggested. 
(Linux Mint: Mesa from from `ppa:kisak/kisak-mesa` PPA repository)
Also, in my experience, Unity is extremely compatible with proton.

**Comment by Deleetdk** [comment]
> Hello @Deleetdk, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.
> 
> `v: 4.6 Mesa 23.2.0-devel` makes it look like you're using a random, mildly dated git build of mesa. Can you test how the game behaves with a current point release of mesa?

I couldn't figure out what system info was being asked for, so I guess I posted the wrong one. Here's the Steam one: https://gist.github.com/Deleetdk/56ccfb76c0ced3e913ffa192a557ff74

@n00btube3D Here's the vulkaninfo: https://gist.github.com/Deleetdk/4f2a4358a5bffc9fcd793ff44c771358

mesa update, looks like some packages are held back, others not: https://gist.github.com/Deleetdk/bd16c9b58f56d3c1ea24bbda13490d81

**Comment by n00btube3D** [comment]
> vkCreateInstance (&inst_info, NULL, vk_instance) failed: ERROR_INCOMPATIBLE_DRIVER (-9)

This line in steam system info is under i386-linux-gnu, suggesting that vulkan is not working in 32 bit.
Under x86_64-linux-gnu (which is 64-bit), vulkan is detected properly.
So I would assume that the 32-bit drivers are missing/broken.

Unfortunately I am not familiar with Linux Mint and apt, so I'm afraid I cannot help you further.

**Comment by Deleetdk** [comment]
Updating mesa using `ppa:kisak/kisak-mesa`, did not solve the issue. Here's the new crash log: 
[steam-489520.log](https://github.com/ValveSoftware/Proton/files/13645529/steam-489520.log)

I'll try looking for some Vulkan 32-bit solution. The odd thing is that this game has been working for weeks, and only suddenly stopped working. So I was suspecting some Proton or game update broke it.

**Comment by Deleetdk** [comment]
OK, so I tried to do a deep clean, and it worked. I don't know what the specific issue was, but here's some steps that worked in the end.

Use aptitude instead of apt, since apt fails to install the 32bit mesa:

```
emil@computer:~$ sudo aptitude install mesa-vulkan-drivers mesa-vulkan-drivers:i386
The following NEW packages will be installed:
  libxcb-randr0:i386{a} mesa-vulkan-drivers:i386 
0 packages upgraded, 2 newly installed, 0 to remove and 14 not upgraded.
Need to get 9.949 kB of archives. After unpacking 46,5 MB will be used.
Do you want to continue? [Y/n/?]
```

Remove ppa's for amdpu and oibaf mesa:

```
mil@computer:~$ ls /etc/apt/sources.list.d/
additional-repositories.list  google-chrome.list                  oibaf-graphics-drivers-jammy.list  spotify.list       teamviewer.list
amdgpu.list                   kisak-kisak-mesa-jammy.list         rocm.list                          steam-beta.list    winehq-jammy.sources
brave-browser-release.list    microsoft-edge-dev.list             signal-xenial.list                 steam-stable.list
docker.list                   official-package-repositories.list  skype-stable.list                  sublime-text.list
emil@computer:~$ sudo rm /etc/apt/sources.list.d/amdgpu.list 
emil@computer:~$ sudo rm /etc/apt/sources.list.d/oibaf-graphics-drivers-jammy.list
```

Restart. Unity games now launch again.

The apt version mismatch is still there, and there are still held mesa packages:

```
emil@computer:~$ apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mesa-vulkan-drivers:i386 is already the newest version (23.0.4-0ubuntu1~22.04.1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mesa-vulkan-drivers : Breaks: mesa-vulkan-drivers:i386 (!= 23.3.0~kisak1~j) but 23.0.4-0ubuntu1~22.04.1 is to be installed
 mesa-vulkan-drivers:i386 : Breaks: mesa-vulkan-drivers (!= 23.0.4-0ubuntu1~22.04.1) but 23.3.0~kisak1~j is to be installed
E: Unable to correct problems, you have held broken packages.
```

```
emil@computer:~$ apt upgrade 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  libegl-mesa0 libegl-mesa0:i386 libgbm1 libgbm1:i386 libgl1-mesa-dri libgl1-mesa-dri:i386 libglapi-mesa libglapi-mesa:i386
  libglx-mesa0 libglx-mesa0:i386 libllvm15 libllvm15:i386 python3-update-manager update-manager-core
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
```

**Comment by kisak-valve** [comment]
Looking through the Steam runtime diagnostics you shared, it looks like you smashed AMD's standalone installer along with oibaf's mesa PPA. These can not be installed together without excessive and manual care. Throwing yet another mesa PPA onto the pile only makes it even more complicated an prone to failure.

You should use, at most, one mesa PPA at a time and ppa-purge the PPA before trying a different PPA.

```
 mesa-vulkan-drivers : Breaks: mesa-vulkan-drivers:i386 (!= 23.3.0~kisak1~j) but 23.0.4-0ubuntu1~22.04.1 is to be installed
 mesa-vulkan-drivers:i386 : Breaks: mesa-vulkan-drivers (!= 23.0.4-0ubuntu1~22.04.1) but 23.3.0~kisak1~j is to be installed
```

This reads like https://github.com/linuxmint/mintsources/issues/242, check if `/etc/apt/sources.list.d/kisak-kisak-mesa-jammy.list` has been restricted to 64 bit only with `arch=amd64` and remove the restriction if you find it.

Regardless, you've troubleshot this issue far enough to determine that your issue is a system config issue and not a Proton issue. If you have further issues with configuring video drivers in general, then it would be a good idea to ask around your distro's community for help specific to your particular flavor of Linux.

Closing as not a Proton issue.

**Comment by Deleetdk** [comment]
>This reads like https://github.com/linuxmint/mintsources/issues/242, check if /etc/apt/sources.list.d/kisak-kisak-mesa-jammy.list has been restricted to 64 bit only with arch=amd64 and remove the restriction if you find it.

There was indeed an `arch=amd64` tag. Removed, `apt update` and `apt upgrade`. Will see if everything still works. It is updating some mesa libraries:

```
The following packages will be upgraded:
  alsa-ucm-conf brave-browser fonts-noto-color-emoji fonts-opensymbol ghostscript ghostscript-x gnome-control-center
  gnome-control-center-data gnome-control-center-faces google-chrome-stable libegl-mesa0 libegl-mesa0:i386 libgbm1
  libgbm1:i386 libgl1-mesa-dri libgl1-mesa-dri:i386 libglapi-mesa libglapi-mesa:i386 libglx-mesa0 libglx-mesa0:i386 libgs9
  libgs9-common liblibreoffice-java libllvm15 libllvm15:i386 libreoffice-base libreoffice-base-core libreoffice-base-drivers
  libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk3
  libreoffice-help-common libreoffice-help-de libreoffice-help-en-gb libreoffice-help-en-us libreoffice-help-es
  libreoffice-help-fr libreoffice-help-it libreoffice-help-pt libreoffice-help-pt-br libreoffice-help-ru
  libreoffice-help-zh-cn libreoffice-help-zh-tw libreoffice-impress libreoffice-java-common libreoffice-l10n-de
  libreoffice-l10n-en-gb libreoffice-l10n-en-za libreoffice-l10n-es libreoffice-l10n-fr libreoffice-l10n-it
  libreoffice-l10n-pt libreoffice-l10n-pt-br libreoffice-l10n-ru libreoffice-l10n-zh-cn libreoffice-l10n-zh-tw
  libreoffice-math libreoffice-sdbc-hsqldb libreoffice-style-colibre libreoffice-writer libuno-cppu3 libuno-cppuhelpergcc3-3
  libuno-purpenvhelpergcc3-3 libuno-sal3 libuno-salhelpergcc3-3 libunoloader-java libyajl2 mesa-va-drivers:i386
  mesa-vulkan-drivers:i386 microsoft-edge-dev python3-uno signal-desktop uno-libs-private ure ure-java vim-common vim-tiny
  xserver-common xserver-xephyr xserver-xorg-core xserver-xorg-legacy xwayland xxd

Preparing to unpack .../03-libllvm15_1%3a15.0.7-1~kisak~j_i386.deb ...
De-configuring libllvm15:amd64 (1:15.0.7-0ubuntu0.22.04.2), to allow configuration of libllvm15:i386 (1:15.0.7-0ubuntu0.22.04.2)
 ...
Unpacking libllvm15:i386 (1:15.0.7-1~kisak~j) over (1:15.0.7-0ubuntu0.22.04.2) ...
Preparing to unpack .../04-libllvm15_1%3a15.0.7-1~kisak~j_amd64.deb ...
Unpacking libllvm15:amd64 (1:15.0.7-1~kisak~j) over (1:15.0.7-0ubuntu0.22.04.2) ...
Preparing to unpack .../05-libgl1-mesa-dri_23.3.1~kisak1~j_amd64.deb ...
De-configuring libgl1-mesa-dri:i386 (22.2.5-0ubuntu0.1~22.04.3), to allow configuration of libgl1-mesa-dri:amd64 (22.2.5-0ubuntu
0.1~22.04.3) ...
Unpacking libgl1-mesa-dri:amd64 (23.3.1~kisak1~j) over (22.2.5-0ubuntu0.1~22.04.3) ...
Preparing to unpack .../06-libgl1-mesa-dri_23.3.1~kisak1~j_i386.deb ...
Unpacking libgl1-mesa-dri:i386 (23.3.1~kisak1~j) over (22.2.5-0ubuntu0.1~22.04.3) ...
Preparing to unpack .../07-libglx-mesa0_23.3.1~kisak1~j_i386.deb ...
De-configuring libglx-mesa0:amd64 (22.2.5-0ubuntu0.1~22.04.3), to allow configuration of libglx-mesa0:i386 (22.2.5-0ubuntu0.1~22
.04.3) ...
Unpacking libglx-mesa0:i386 (23.3.1~kisak1~j) over (22.2.5-0ubuntu0.1~22.04.3) ...
Preparing to unpack .../08-libglx-mesa0_23.3.1~kisak1~j_amd64.deb ...
Unpacking libglx-mesa0:amd64 (23.3.1~kisak1~j) over (22.2.5-0ubuntu0.1~22.04.3) ...
Preparing to unpack .../09-libegl-mesa0_23.3.1~kisak1~j_i386.deb ...
De-configuring libegl-mesa0:amd64 (22.2.5-0ubuntu0.1~22.04.3), to allow configuration of libegl-mesa0:i386 (22.2.5-0ubuntu0.1~22
.04.3) ...
Unpacking libegl-mesa0:i386 (23.3.1~kisak1~j) over (22.2.5-0ubuntu0.1~22.04.3) ...
Preparing to unpack .../10-libegl-mesa0_23.3.1~kisak1~j_amd64.deb ...
Unpacking libegl-mesa0:amd64 (23.3.1~kisak1~j) over (22.2.5-0ubuntu0.1~22.04.3) ...
Preparing to unpack .../11-libglapi-mesa_23.3.1~kisak1~j_amd64.deb ...
De-configuring libglapi-mesa:i386 (22.2.5-0ubuntu0.1~22.04.3), to allow configuration of libglapi-mesa:amd64 (22.2.5-0ubuntu0.1~
22.04.3) ...
Unpacking libglapi-mesa:amd64 (23.3.1~kisak1~j) over (22.2.5-0ubuntu0.1~22.04.3) ...
Preparing to unpack .../12-libglapi-mesa_23.3.1~kisak1~j_i386.deb ...
Unpacking libglapi-mesa:i386 (23.3.1~kisak1~j) over (22.2.5-0ubuntu0.1~22.04.3) ...
Preparing to unpack .../13-libgbm1_23.3.1~kisak1~j_amd64.deb ...
De-configuring libgbm1:i386 (22.2.5-0ubuntu0.1~22.04.3), to allow configuration of libgbm1:amd64 (22.2.5-0ubuntu0.1~22.04.3) ...
Unpacking libgbm1:amd64 (23.3.1~kisak1~j) over (22.2.5-0ubuntu0.1~22.04.3) ...
Preparing to unpack .../14-libgbm1_23.3.1~kisak1~j_i386.deb ...
Unpacking libgbm1:i386 (23.3.1~kisak1~j) over (22.2.5-0ubuntu0.1~22.04.3) ...

```
