### ISSUE TITLE
Cyberpunk 2077 Freezes

### ISSUE THREAD

**Issue by fubarhouse** [ValveSoftware/Proton#7336]
I've been getting frequent screen freezes that lock the entire system up for a while - it is definitely new since the 2.0 release...

I can't close the application once it freezes up, I have to force a manual reboot. From what I've experienced this issue is isolated to one of my two Arch-bases systems - this one is the laptop.

I've tried on a lot of Proton versions, as well as using gamescope.

I'm currently using GEProton8.25 with the launch options: `PROTON_LOG=1 %command% --launcher-skip`.

Here's what I can report via logs - please let me know if I can provide more information...

[steam-1091500.log](https://github.com/ValveSoftware/Proton/files/13647803/steam-1091500.log)

```
2955.694:0140:01a0:warn:vkd3d-proton:d3d12_command_list_QueryInterface: {5b2662fb-eb28-4aec-819e-1c1b4de060f6} not implemented, returning E_NOINTERFACE.
2955.700:0140:024c:warn:vkd3d-proton:vkd3d_native_sync_handle_release: Failed to release semaphore (#12a).
2955.700:0140:024c:err:vkd3d-proton:vkd3d_waiting_event_signal: Failed to signal event, hr #80004005.
```

**Comment by kisak-valve** [comment]
Hello @fubarhouse, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1852122705.
