### ISSUE TITLE
Proton does no longer start games

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7340]
# Compatibility Report
- Name of the game with compatibility issues:
- Ultimate Admiral: Dreadnaughts
- Sniper Ghost Warrior Contracts
- Metal Fear Solid V: Ground zeros
- Sid Meierś Ace Patrol
- War on the Sea
- .......

- Steam AppID of the game:
- 1069660 (Dreadnaughts)
- 973580 (Sniper)
- 311340 (Metal Fear Solid)
- and so on-....-

## System Information
- GPU: 
- Video driver version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):      https://gist.github.com/TroKhon/7793220db8aaa5410be111553170f31b
- Proton version: 8.0.4,7.0.6, Experimental

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

 Have not found an log file of this type.

## Symptoms 
Games seem to start and then - nothing. Steam start window closes.

## Reproduction

Simply starting again - and then again nothing

webhelper.txt shows error messages.... All games have been working seamlessly before - I do not know the exatct time when this behaviour began, but I noticed it approx 4 days ago.

**Comment by n00btube3D** [comment]
I would start by checking your graphics driver.
> "graphics-details" : {
>        "x11/vulkan" : {
>          "renderer" : null,
>          "version" : null,
>          "issues" : [
>            "cannot-load",
>            "timeout",
>            "cannot-draw"
>          ],
>          "exit-status" : 124,
>          "devices" : [
>          ]
>        },

From your Steam Runtime Info Log.

Also:
> sh: 1: /media/xetcst/Steam/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point: Permission denied

I'm not sure whether this is related to your issue or not.

**Comment by ghost** [comment]
OK, have checked - from the information (nvidia-smi, vulkaninfo) I could see everything was rated ok. I have now reinstalled NVIDIA-drivers, vulkan libraries and X11. The error message regarding acces I can not judge. The directory and files had every access right for users (read,write,execute).

But now the good news, everything works again - Thank You !  I never would have suspected the drivers as reason since any other program works. By the way, your support has directed me to Github - I always thought it could not be a general Proton problem since it works on my other two computers - also with Linux and Nvidia cards. But again: BIG THANK YOU !
