### ISSUE TITLE
New World Crashing on Startup

### ISSUE THREAD

**Issue by bigwheel50** [ValveSoftware/Proton#7341]
# Compatibility Report
- Name of the game with compatibility issues: New World
- Steam AppID of the game: 1063730

## System Information
- GPU: Nvidia RTX 4090
- Video driver version: Nvidia 545.29.06
- Kernel version: 545.29.06
- Link to full system information report as [Gist](https://gist.github.com/bigwheel50/9387dd7d7460814ca43f6b0fa78a766f):
- Proton version: 8.0-4, Experimental, GE-Proton8-25, GE-Proton8-20, GE-Proton8-6, GE-Proton7-16. GE-Proton7-14

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-1063730.zip](https://github.com/ValveSoftware/Proton/files/13664092/steam-1063730.zip)

## Symptoms
The game crashes immediately during startup. 

## Reproduction

1. Launch game
2. [Don't] Profit

Have tried multiple versions of Proton, GE-Proton, launch options, etc.

**Comment by kisak-valve** [comment]
Hello @bigwheel50, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5772#issuecomment-1854509630.
