### ISSUE TITLE
Ready or Not (1144200)

### ISSUE THREAD

**Issue by Doomguy1364** [ValveSoftware/Proton#7345]
Compatibility Report
- Name of the game with compatibility issues: Ready or Not
- Steam AppID of the game: 1144200

System Information
- GPU: GTX 3070
- Video driver version: Nvidia proprietary 545.29.06-5
- Kernel version: 6.6.6-arch1-1
- Link to full system information report: https://gist.github.com/Doomguy1364/748e7b5bfc0d8cd421b788fde5d46a74
- Proton version: 8.0-4 and Experimental

I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-1144200.log](https://github.com/ValveSoftware/Proton/files/13668538/steam-1144200.log)

Symptoms:

Under DX12 the game will experience EXTREME freezing and stuttering with-in a few minutes of playing; I do use shader pre-caching, unfortunately it does not seem to help.
As of the 1.0 update for this game DX12 runs at roughly 60% higher FPS over DX11, however it is far from smooth at time of testing!

Reproduction: Always

Play the game for a few minutes on DX12, Extreme stutter and freezing.

**Comment by kisak-valve** [comment]
Hello @Doomguy1364, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5985#issuecomment-1855874219.
