### ISSUE TITLE
Ready or Not 1144200

### ISSUE THREAD

**Issue by quuinnn** [ValveSoftware/Proton#7347]
# Compatibility Report
- Name of the game with compatibility issues: Ready or Not
- Steam AppID of the game: 1144200

## System Information
- GPU: NVIDIA GTX 1650 Mobile
- Video driver version: NVIDIA 545.29.06
- Kernel version: 6.6.6-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/fortunef/977b409462dc161e2f86d03868ffc013):
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
 
The game is incredibly slow. And for some reason, Steam didn't pre-process the shaders 

## Reproduction

Launch the game in commander mode. Low and unstable framerate
[steam-1144200.log](https://github.com/ValveSoftware/Proton/files/13671499/steam-1144200.log)

**Comment by kisak-valve** [comment]
Hello @fortunef, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5985#issuecomment-1855904448.
