### ISSUE TITLE
Spiderman Miles Morales crash on start, nvidia 1650 4G, driver version 535

### ISSUE THREAD

**Issue by bucketsize** [ValveSoftware/Proton#7349]
Proton: 1701933636 experimental-8.0-20231207
SteamGameId: 1817190
Command: ["/mnt/data/__steam_lib_4/steamapps/common/Marvel's Spider-Man Miles Morales/MilesMorales.exe"]

Issue: Game crashes on launch, not even launcher is seen. Other games [skyrim; halo 1,2,3; Spiderman - REMASTERED] work perfectly with same version of proton and same launch options [nvrun %command%]
> nvrun - shell script wrapper to launch games - https://gist.github.com/bucketsize/b8bc86ce540dd86e3f77966e5c4db60f#file-nvrun

On another AMD [Ryzen 2200g, AMDGPU Rx6400] PC running linux 6.6.0-pikaos, even MilesMorales works perfectly.

System:
- hardware - laptop
> cpu: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
> gpu0: 00:02.0 VGA compatible controller: Intel Corporation CometLake-H GT2 [UHD Graphics] (rev 05)
> gpu1: 01:00.0 VGA compatible controller: NVIDIA Corporation TU117M (rev a1) -- gtx 1650 4gb ram
> ram: 16G
> steam library fs: btrfs, 700G, 40% free

- kernel: 6.6.0-pikaos
- driver: NVIDIA 535.129.03 from pikaos repo

Log:
- desg: https://gist.github.com/bucketsize/b8bc86ce540dd86e3f77966e5c4db60f#file-dmesg
- proton_log: https://gist.github.com/bucketsize/b8bc86ce540dd86e3f77966e5c4db60f#file-steam-1817190-log
- steam runtime diagnostic: https://gist.github.com/bucketsize/b8bc86ce540dd86e3f77966e5c4db60f#file-steam-runtime-diagnostics

**Comment by kisak-valve** [comment]
Hello @bucketsize, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6328#issuecomment-1856517719.
