### ISSUE TITLE
Darksiders Warmastered Edition crashes on launch (462780)

### ISSUE THREAD

**Issue by Cuddlypuff** [ValveSoftware/Proton#735]
Sys info: https://gist.github.com/Cuddlypuff/a518019d119623d9a1b7552e284c1f6d

as soon as the game's window appears a popup says the game has crashed and asks the user to create a minidump. Had to kill the game as it didn't shut down on its own.

No errors or related info to be found in steam's terminal output or the game's .log file

**Comment by grigi** [comment]
Confirmed same behaviour with a MESA 18.1.6 with Intel UHD620 GPU.

**Comment by tingvarsson** [comment]
I see the same issue, [sysinfo](https://gist.github.com/tingvarsson/dc2eec45ac3e1b67cc5316b61f32bd75).

**Comment by kisak-valve** [comment]
Hello @Cuddlypuff, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/394#issuecomment-416240226.

**Comment by Cuddlypuff** [comment]
apologies for the dupes @kisak-valve , I usually check before I file but I mustve skipped darksiders...

**Comment by pcfirebeats** [comment]
Same thing here.


My system:
Informações do computador:
    Fabricante: Unknown
    Modelo: Unknown
    Tipo: Computador de secretária
    Sem input táctil

Informação do processador:
    Fabricante do CPU: GenuineIntel
    Marca do CPU:         Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    Família do CPU: 0x6
    Modelo do CPU: 0x3a
    Versão do CPU: 0x9
    Tipo do CPU: 0x0
    Velocidade: 3600 Mhz
    4 processadores lógicos
    4 processadores físicos
    HyperThreading:  Não suportado
    FCMOV:  Suportado
    SSE2:  Suportado
    SSE3:  Suportado
    SSSE3:  Suportado
    SSE4a:  Não suportado
    SSE41:  Suportado
    SSE42:  Suportado
    AES: Suportado
    AVX: Suportado
    CMPXCHG16B: Suportado
    LAHF/SAHF: Suportado
    PrefetchW: Não suportado

Versão do Sistema Operativo:
    Ubuntu 18.04.1 LTS (64 bits)
    Nome do Kernel: Linux
    Versão do Kernel: 4.15.0-34-generic
    Editora de Servidor X: The X.Org Foundation
    Versão de Servidor X: 11906000
    Gestor de janelas X: GNOME Shell
    Versão Runtime do Steam: steam-runtime-beta-release_2018-06-14

Placa gráfica:
    Driver: X.Org AMD Radeon (TM) RX 470 Graphics (POLARIS10, DRM 3.23.0, 4.15.0-34-generic, LLVM 8.0.0)
    Versão do driver: 4.5 (Compatibility Profile) Mesa 18.3.0-devel - padoka PPA
    Versão do OpenGL: 4.5
    Profundidade de cor do ambiente de trabalho: 24 bits/pixel
    Taxa de Atualização do Monitor: 60 Hz
    Código do fabricante: 0x1002
    Código do dispositivo: 0x67df
    Revisão não detetada
    Número de monitores:  1
    Número de placas gráficas lógicas: 1
    Resolução do monitor principal: 1920 x 1080
    Resolução do ambiente de trabalho: 1920 x 1080
    Tamanho do monitor principal: 20.08" x 11.42" (23.07" diag)
 51.0cm x 29.0cm (58.6cm diag)
    VRAM principal: 4096 MB

Placa de som:
    Dispositivo de áudio: VIA VT1708S

Memória:
    RAM:  7911 Mb

Diversos:
    Idioma da interface:  Português (Portugal)
    Idioma: pt_PT.UTF-8
    Espaço total disponível em disco:  460828 Mb
    Maior bloco livre no disco rígido:  282752 Mb
    Headset de R.V.: Nenhum encontrado

Relatórios de falha recentes:
