### ISSUE TITLE
The 64 bit version of Far Cry 1 doesn't boot with Proton, but runs fine on Windows with DXVK

### ISSUE THREAD

**Issue by Deus-nsf** [ValveSoftware/Proton#7350]
I installed the 64 bit patch with protontricks using the Far Cry prefix (maybe that was a mistake?).
The patch installed correctly and the files are here, but while adding the 64 bit exe as a non steam game on windows works perfectly fine, even using dxvk, on the steam deck (didn't try desktop linux yet), the game just doesn't go somewhere, it just freezes at startup, but it doesn't crash...

I have no clue what is going wrong I'm sorry.

**Comment by kisak-valve** [comment]
Hello @Deus-nsf, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/715#issuecomment-1856560611.
