### ISSUE TITLE
Lethal Company (1966720) Freezes in Fullscreen Unless Another Window is on Top of it

### ISSUE THREAD

**Issue by SandFrog** [ValveSoftware/Proton#7351]
# Compatibility Report
- Name of the game with compatibility issues: Lethal Company
- Steam AppID of the game: 1966720

## System Information
- GPU: GTX 1070
- Video driver version: Nvidia 545.29.06
- Kernel version: 6.5.0-14-generic
- Link to full system information report as [Gist](https://gist.github.com/SandFrog/c4e4aa4b26d78afc9a1ec65562ff968d):
- Proton version: 8.0-4 (Also tested on Proton Experimental)

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game. (wait how does this work, there's another compatibility report but for a completely separate issue)
- [ x ] that I have checked whether there are updates for my system available.

Proton Logs:
[Gist of proton when the game froze](https://gist.github.com/SandFrog/1eaa9eef6c085dc1e93a01e88967835f)
[Gist of proton when the game didn't freeze](https://gist.github.com/SandFrog/40e6b10930d873b6b88c6f4df401a0e7)

## Symptoms 
Having the game in focus causes the problem. The issue presents itself in full screen and windowed full screen mode. When I start the game up it'll freeze at the unity logo. However when I'm alt tabbed it'll load just fine until I tab back into the game. I've been able to get around this issue by starting up a video in Firefox and using the picture in picture feature. This workaround will solve the issue with any window that you can set to "always on top" in the WM. It works perfectly fine once I have some other window open on top of the game.  Playing the game in windowed mode also solves this issue, however getting to the settings menu for someone opening the game for the first time would be difficult due to the issue.

## Reproduction
1. Start the game.
2. At the first loading screen the game will freeze, this will cause the x session to lag until tabbed away or pressing the super key to go to the gnome overview.
### Reproduction of solution
1. Open any window in gnome that supports right clicking on the window and selecting "Always on Top" and enable the option
2. Start the game

**Comment by kisak-valve** [comment]
Hello @SandFrog, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7320#issuecomment-1857881652.
