### ISSUE TITLE
Battlefield V Mouse Input sensitivity broken on vertical axis.

### ISSUE THREAD

**Issue by LethalManBoob** [ValveSoftware/Proton#7355]
Sens is halved when looking down but only when looking down. This is lessened when changing the raw input setting on or off but does not fix, i cannot get it to be consistent. 

- GPU: 3070
- Video driver version: 545.29.06
- Kernel version: 6.6.7
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: all versions have this issue, experimental, 8.0, cachyos-proton

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @LethalManBoob, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3977#issuecomment-1858935480.
