### ISSUE TITLE
make: *** [../proton/Makefile.in:1173: all] Error 2

### ISSUE THREAD

**Issue by wumo** [ValveSoftware/Proton#7360]
Ubuntu 22.04
git branch proton_8.0

[log.txt](https://github.com/ValveSoftware/Proton/files/13705262/log.txt)

**Comment by kisak-valve** [comment]
Hello @wumo, there's a couple lines of `Connecting to 127.0.0.1:8080... failed: Connection refused.` in your log which might be a hint.

Also:
```
wget -O /home/wumohu/proton/contrib/wine-gecko-2.47.3-x86_64.tar.xz https://dl.winehq.org/wine/wine-gecko/2.47.3/wine-gecko-2.47.3-x86_64.tar.xz
[...]
make: *** [../proton/Makefile.in:955: /home/wumohu/proton/contrib/wine-gecko-2.47.3-x86.tar.xz] Error 4
make: *** Waiting for unfinished jobs....
```
This download might have failed.

**Comment by wumo** [comment]
ok, I'll look into network issues. thx.
