### ISSUE TITLE
Forts using vulkan renders everything transparent and dark

### ISSUE THREAD

**Issue by tristanjl** [ValveSoftware/Proton#7362]
# Compatibility Report
- Name of the game with compatibility issues: Forts
- Steam AppID of the game: 410900

## System Information
- GPU: AMD 6800XT (Also occurs on steam deck. Does not occur Linux Mint with RX580)
- Video driver version: Mesa 23.3.0
- Kernel version: 6.6.6-200.fc39.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/tristanjl/532ae312c789750630d0eeb5001470a9
- Proton version: Tested Experimental, 8.0-4, 7.0-6

## I confirm:
- I confirm that I haven't found an existing compatibility report for this game.
- I confirm that I have checked whether there are updates for my system available.

[steam-410900.log](https://github.com/ValveSoftware/Proton/files/13709453/steam-410900.log)

## Symptoms
When vulkan rendering is enabled, everything in the game looks darker and transparent
When captured in render doc, the output pixel value is approximately 1/4 the alpha is should be. Due to blend modes, this is then multiplied through the colour, hence why everything looks dark
When debugging the shader in render doc, the pixel value result appears to be the correct value - but it does not match the actual pixel value.
In testing a debug build, it renders correctly run from wine directly (including wine used by proton). It also appears correct when disabling Vulkan (which uses OpenGL)

## Reproduction
Go to Options -> Video
Ensure 'Enable Vulkan' is checked
Restart the game
Notice that everything appears transparent and darker

**Comment by kisak-valve** [comment]
Hello @tristanjl, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/637#issuecomment-1861905772.
