### ISSUE TITLE
Native wayland support 

### ISSUE THREAD

**Issue by m1m1k4tz** [ValveSoftware/Proton#7363]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
I think it would be nice to use the native Wayland support being merged into wine it can be enabled with a registry change and running the program with the env variable DISPLAY=''

## Justification [optional] 
Might not be necessary in the future if wine defaults to Wayland support once it’s fully merged after the code freeze 
## Risks [optional]
Medium Keyboard support isn’t merged yet  and there’s some windowing issues currently but Vulkan support is merged and I’ve tested it with the new wow64 mode in wine 
## References [optional] 
https://bugs.winehq.org/show_bug.cgi?id=56013

**Comment by kisak-valve** [comment]
Hello @m1m1k4tz, this request is already being tracked at #4638. Closing as a duplicate.
