### ISSUE TITLE
GYLT (ID:2206210) won't play any cutscenes regardless of the proton version used

### ISSUE THREAD

**Issue by Ace120C** [ValveSoftware/Proton#7366]
# Compatibility Report
- Name of the game with compatibility issues: GYLT
- Steam AppID of the game: 2206210

## System Information
- GPU: AMD Radeon RX6500M
- Video driver version: Mesa 23.2.1-1ubuntu3.1
- Kernel version: 6.5.0-14-generic 
- Display Server: Wayland
- Link to full system information report as [Gist](https://gist.github.com/Ace120C/a06fdf31c20aab4f147e989444f1173d):
- Proton version: Experimental, 8.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game works fine but Cutscenes do not play but only show TV rainbow lines with the captions of the cutscenes if proton experimental is used or a blackscreen with nothing on it if custom GE Proton is used, you can skip the cutscenes in both cases and the game resumes as normal but the game is story heavy, and the cutscenes is what puts the game's story together.

## Reproduction

- play the game normally until sally (the player) finishes distributing the flyers, after the first cutscene it'll either be a blackscreen or a rainbow lines similar to what you find on non working channels on a TV, the cutscene would not play but of course it can be skipped. (I suspect all cutscenes are affected but I only played until that part to come to that conclusion, I also assume it could be a codec problem but I'm not sure)

![Screenshot from 2023-12-21 21-39-57](https://github.com/ValveSoftware/Proton/assets/145904614/6bf57ac2-e918-4968-a4dd-9f7af7d2a266)

**Comment by kisak-valve** [comment]
Hello @Ace120C, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7230#issuecomment-1867150353.

**Comment by trinukso** [comment]
Do you have any news? The game still does not play the cutscenes.

**Comment by Ace120C** [comment]
> Do you have any news? The game still does not play the cutscenes.

YES! 
you can use 

```
SteamDeck=1 %command% 
```

in your launch options and that should play your cutscenes just fine
