### ISSUE TITLE
Game crashes while trying to load main menu.

### ISSUE THREAD

**Issue by something12356** [ValveSoftware/Proton#7367]
# Compatibility Report
- Name of the game with compatibility issues: Dying Light 2
- Steam AppID of the game: 534380

## System Information
- GPU: RX 6600 XT
- Video driver version: Mesa 23.3.1-1
- Kernel version: 6.6.7-zen1-1
- Link to full system information report as [Gist](https://gist.github.com/something12356/57c3856721fe3d91b408eec1c4d29f89)
- Proton version: Have tried Experimental, 8.0-4, 7.0-6, GE-Proton7-20, and GE-Proton8-25

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-534380.log](https://github.com/ValveSoftware/Proton/files/13754108/steam-534380.log)
[Crash log created by the game.](https://github.com/ValveSoftware/Proton/files/13754084/crash_20231222_154616739.log)

## Symptoms 
After launching the game and getting to the screen where it says "press any button to continue", and then pressing a button, the game crashes. I can't even reach the main menu.

## Reproduction
Install Dying Light 2, click play, the game crashes. I'm on Arch Linux and running the version of steam I got through pacman.

**Comment by kisak-valve** [comment]
Hello @something12356, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5542#issuecomment-1867872319.
