### ISSUE TITLE
EA SPORTS™ WRC: Problems with force feedback

### ISSUE THREAD

**Issue by eruizc-dev** [ValveSoftware/Proton#7370]
# Compatibility Report

- Name of the game with compatibility issues: EA SPORTS™ WRC
- Steam AppID of the game: 1849250

## System Information

- GPU: RX 6650XT
- Video driver version: Mesa 23.3.0
- Kernel version: 6.6.7-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/eruizc-dev/9b88f865cd4b0347134d342b6dbe747e
- Proton version: tried both 7.0-6 and 8.0-4
- Wheel: Logitech Trueforce G923 - Play Station edition 

## I confirm:

- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

When using a Logitech wheel and force feedback settings are set to default, the wheel will start going left and right non stop after you turn it with a bit of force.

https://github.com/berarma/new-lg4ff/assets/58179604/30a6962d-9cd9-411e-9f38-4dc052f7b788

A workaround to this problem is to set tire friction settings to a low value (between 0 and 25)

## Reproduction

 1. Open the game
 2. Go into a stage with the default control settings
 3. Spin your wheel fast to either side
 4. It should start going left and right non-stop like in the video

**Comment by eruizc-dev** [comment]
Also reported in https://github.com/berarma/new-lg4ff/issues/86

**Comment by kisak-valve** [comment]
Hello @eruizc-dev, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7220#issuecomment-1867935690.

**Comment by eruizc-dev** [comment]
Okay thank you!
