### ISSUE TITLE
Skyinstaller on Kubuntu 23.10 does not disaplay install button

### ISSUE THREAD

**Issue by YukiAlmasy** [ValveSoftware/Proton#7373]
and when I browser the trails in the sky SC executable in, nothing happens, it just greys out the browse button, this happens with trails on current proton experimental, 8.0-4, and 8-25 GE

**Comment by kisak-valve** [comment]
Hello @YukiAlmasy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3570#issuecomment-1868636621.
