### ISSUE TITLE
Set soundcard with proton

### ISSUE THREAD

**Issue by stefan11111** [ValveSoftware/Proton#7376]
When I run a game with proton, card 0 is always used.
And many games don't have the option to set the sound card.
How can I make proton use the card from /etc/asound.conf?

**Comment by kisak-valve** [comment]
Hello @stefan11111, you've described a Steam Linux Runtime container issue which is being tracked at https://github.com/ValveSoftware/steam-runtime/issues/344 instead of a Proton issue. Please give that issue report a read.

Closing in favor of the older issue report.

**Comment by stefan11111** [comment]
Thanks for pointing me to that issue.
The workaround discussed, copying /etc/asound.conf to ~/.asoundrc worked.
