### ISSUE TITLE
[Terraria] Proton writes a key twice when typing.

### ISSUE THREAD

**Issue by RobotoSkunk** [ValveSoftware/Proton#7379]
# Compatibility Report
- Name of the game with compatibility issues: Terraria
- Steam AppID of the game: 105600

## System Information
- GPU: NVIDIA GeForce GTX 1650
- Video driver version: NVIDIA 545.29.02
- Kernel version: 6.5.0-5-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/8565afc915c9915c66e88c0b7f01628c
- Proton version: experimental, 8.0 and 7.0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When you type anything with the keyboard, it appears in the game as if you had pressed the same key twice.

This bug happens with every single key, except with the backspace. Only happens with Proton, launching the game as a Native app works correctly (but it's bugged because `Microsoft.Xna.Framework.Game` is missing after the first launch, so I have to launch it with Proton).

## Reproduction
1. Launch Terraria with some of the mentioned Proton versions above.
2. Go to any place to write text (the character creation name menu by example).
3. Type anything on it.

![image](https://github.com/ValveSoftware/Proton/assets/49355293/24919d67-df76-4269-8552-88cff8151c3b)

**Comment by kisak-valve** [comment]
Hello @RobotoSkunk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3341#issuecomment-1874041146.
