### ISSUE TITLE
[Whitelist] Star Explorers (502720)

### ISSUE THREAD

**Issue by MKSchmidt30** [ValveSoftware/Proton#738]
I was able to run my game Star Explorers on Ubuntu using WINE.  I tested an earlier version, but I have not changed any major things about the graphics or interface.  I would very much appreciate if you could let me know how to get it tested and hopefully added to the list!

**Comment by kisak-valve** [comment]
Hello @MKSchmidt30, these games should be tested against a version of Proton shipped in Steam's beta client, not a random version of wine. You should be able to enable Proton for all game titles in Steam's settings under the Steam Play section.

Additionally, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in the whitelist requests.

**Comment by MKSchmidt30** [comment]
Ok, thank you!  Should I resubmit this request once I do this, or should I just update this one?

**Comment by kisak-valve** [comment]
Makes no difference either way.

**Comment by kisak-valve** [comment]
Closing in favor of #914.
