### ISSUE TITLE
Performance regression on the new proton experimental(2023/12/20)

### ISSUE THREAD

**Issue by DekosAnjo** [ValveSoftware/Proton#7381]
I noticed a drop in performance after the recent Proton update. Gave it a shot with a few other games to check if it was just one game, but it seems to affect a couple of others too. Not all of them though. my RTX 3070 handles some games fine despite the performance hiccup.
Did some troubleshooting, played around with Nvidia driver settings, even tried downgrading the driver, but no luck. The issue only cleared up when I switched from Proton Experimental (2023/12/20) to Proton 8.0-4. Since then, no more performance problems.

here is the 3dMark results (1- Proton 8.0-4 , 2- Proton Experimental):
![Captura de tela de 2024-01-02 21-34-17](https://github.com/ValveSoftware/Proton/assets/10676754/02ae3494-fe3b-435e-9909-7dcbbb7dc738)

**Comment by kisak-valve** [comment]
Hello @rafaelhipercg, please note the games you saw a change in behavior as well as those which are unaffected so that there's a chance to find a pattern to ponder between them. Also, please be specific as to the time frame of "the recent Proton update."
