### ISSUE TITLE
NFS Heat doesn't open.

### ISSUE THREAD

**Issue by Faccinetto** [ValveSoftware/Proton#7384]
# Compatibility Report
- Name of the game with compatibility issues: Need for Speed™ Heat
- Steam AppID of the game: 1222680

## System Information
- GPU: AMD ATI Radeon 540/540X/550/550X
- Video driver version: Mesa 23.3.2-arch1.2
- Kernel version: 6.6.9-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Faccinetto/80e361f0f1473e52658250d00296529f
- Proton version: Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Is a 1.3GB file, so, I can attach via post, this is the message shows (I tried to upload a .zip file):
![photo_2024-01-04_11-30-41](https://github.com/ValveSoftware/Proton/assets/74318143/18bf553c-2227-471a-89cb-6f02cd12e5c1)

Also, I upload the log on Google Drive: https://drive.google.com/file/d/1YGl0cz1W1n_wBV1BAprD9-EnZE2IOehU/view?usp=sharing

## Symptoms 
I can't make Need for Speed Heat run, so far.
I've tried proton-ge and proton-experimental, and all that I get is this black screen, shortly after the game crashes.
Also, I've try one comment for use proton 5.0 and PROTON_NO_ESYNC=1 and Steam don't install EA App script.

**Comment by kisak-valve** [comment]
Hello @Faccinetto, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3955#issuecomment-1877515525.

**Comment by Faccinetto** [comment]
Ok, Thank you.
