### ISSUE TITLE
DCS World  Steam Edition - Proton 8.04 - Winwing Orion2 F16EX stick

### ISSUE THREAD

**Issue by mvrk69** [ValveSoftware/Proton#7385]
Hi,

I'm trying to use my new Winwing Orion2 F16EX stick on DCS, the stick is detected but several buttons don't work.

I've tried with or without SDL_LINUX_JOYSTICK_CLASSIC=1 and still no good.

Directly on Linux, with https://github.com/Grumbel/sdl-jstest all buttons are detected and work.

My System:
OS: Fedora 37 (x86_64)
Proton: 8.04

**Comment by kisak-valve** [comment]
Hello @mvrk69, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1722#issuecomment-1879198538.
