### ISSUE TITLE
[Whitelist] Dungeon of the endless (249050)

### ISSUE THREAD

**Issue by Cuddlypuff** [ValveSoftware/Proton#739]
system info: https://gist.github.com/Cuddlypuff/a518019d119623d9a1b7552e284c1f6d

Played through a whole level without any issues

**Comment by Pobega** [comment]
FWIW, on some configurations it seems to need `PROTON_USE_WINED3D11=1`. 

i5-5200u / Intel HD 5500 / Mesa 18.2 / LLVM 7 / Fedora 28 (`mesa*` installed from F29)

**Comment by NoXPhasma** [comment]
The game runs fine for me without any big problem. What does not proper work is my gamepad. It constantly moves in one direction in the menu, log file shows it's loading xinput1_3.dll, so I tried to fix it by installing `xinput` through protontricks, but no dice. However, shop site says partial gamepad support, so not sure how much of an impact that should have on the decision to whitelist it.

Proton Log: [steam-249050.log](https://github.com/ValveSoftware/Proton/files/2568650/steam-249050.log)
Proton version: 3.16-4
Sysinfo: https://gist.github.com/NoXPhasma/9ed85e6b0602b656c812acd013ee121f

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.
