### ISSUE TITLE
TEKKEN 8 - DEMO (2524440) Not Launching

### ISSUE THREAD

**Issue by msmalik681** [ValveSoftware/Proton#7392]
# Compatibility Report
- Name of the game with compatibility issues: TEKKEN 8 - DEMO
- Steam AppID of the game:2524440

## System Information
- GPU: GTX 1060 3GB
- Video driver version: nvidia 535.129.03-0ubuntu0.22.04.1
- Kernel version: 5.15.0-91-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental 

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

`PROTON_LOG=1 %command%` has no output.

## Symptoms 
Game is stuck on launching but never starts.

## Reproduction
Run Tekken 8 on Linux mint 21.2 from a steam package (not flatpak)

This URL has my system settings from steam and linux mint also added the terminal output when running steam then tekken 8 demo.
(https://gist.github.com/msmalik681/1cfd17b96da4582b2ea3b2cb95d11ca4)

**Comment by kisak-valve** [comment]
Hello @msmalik681, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7383#issuecomment-1881682347.
