### ISSUE TITLE
The Final Station (435530)

### ISSUE THREAD

**Issue by cprn** [ValveSoftware/Proton#7396]
# Compatibility Report
- Name of the game with compatibility issues: The Final Station
- Steam AppID of the game: 435530

## System Information
- GPU: AMD Radeon RX 7900 XTX
- Video driver version: Mesa 23.3.2-arch10.2
- Kernel version: 6.6.10-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/cprn/1066f9db36f5bee8551d229211029585
- Proton version: GE-Proton8-27

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-435530.log](https://github.com/ValveSoftware/Proton/files/13881869/steam-435530.log)

## Symptoms 
Bear with me, please. The game doesn't start. It [used to start for me](https://www.protondb.com/app/435530#R6rUFn7MAF) with Proton without issues about 3 years ago but there were many updates since then and I changed the GPU from NVIDIA to AMD.

I read the attached Proton log and it seems to be failing due to missing `VK_KHR_surface` extension but it doesn't make any sense since it's a very basic extension and other Vulkan games requiring it run fine (e.g. Ancestors: The Humankind Odyssey). Also it runs fine if I run it in terminal using `protontricks` without Steam like so:

```
protontricks-launch --appid 435530 .local/share/Steam/steamapps/common/TheFinalStation/TheFinalStation.exe
```
The only issue then is the Steam Controller doesn't work (as in: it works in kb+mouse desktop mode).

I tried many things but failed to find a solution.

When I run the game natively (without Proton) it starts, menus open fine but after starting the game the screen is black - I can move the mouse cursor, I hear shots when I click but nothing is rendered. When I was on NVIDIA I had that issue as well but back then I managed to resolve it by setting the game to the same resolution as the system (1440p) but it doesn't make a difference now (I'm in 4K now, tried in 1440p as well, still a black screen). Regardless, back then the native version was crashing to desktop after a few minutes, so I'm assuming it's unplayable on Linux without Proton anyway.

## Reproduction
1. Install the game
2. force Proton in Properties -> Compatibility
3. try to run the game

**Comment by cprn** [comment]
I tried Proton 8.0-4 and Proton Experimental - same issue, same log output. I think it's something within the Steam itself (`reaper` or `steam-launch-wrapper` or runtime or I have no idea).

**Comment by kisak-valve** [comment]
Hello @cprn, looking at your extended diagnostics information, it looks like you do not have a 32 bit Vulkan driver installed for your video card. Please add the `lib32-vulkan-radeon` system package and retest.

**Comment by cprn** [comment]
Oh, f... me! It works flawlessly now. I'm very very sorry, this can be closed. Why it worked without 32 bit driver when started by `protontricks-launch`, I have no idea.
