### ISSUE TITLE
call of duty warzone

### ISSUE THREAD

**Issue by ioannis120** [ValveSoftware/Proton#7401]
call of duty warzone
1938090 steam app id
https://gist.github.com/ioannis120/bd37382685340ca3e3a41c2badb6c621
It does not starts the game
Proton 8.0.4
[steam-1938090.log](https://github.com/ValveSoftware/Proton/files/13918684/steam-1938090.log)

**Comment by kisak-valve** [comment]
Hello @ioannis120, we're using one issue report per unofficially supported game title. Closing in favor of https://github.com/ValveSoftware/Proton/issues/5366#issuecomment-1888859180.
