### ISSUE TITLE
The Finals

### ISSUE THREAD

**Issue by UbuntuGaming** [ValveSoftware/Proton#7405]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 2073850

## System Information
- GPU: AMD Radeon 7800 XT
- Video driver version: Mesa 23.2.1-1ubuntu3.1
- Kernel version: 6.7.0
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/UbuntuGaming/1d9c49fa1a0aecf8b0127c1580ed9ab1
- Proton version: Proton Experimental

## I confirm:
- [] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms

- Crashes once loaded in game after a few minutes, Sometimes seconds.
- Sometimes crashes on loading in.
- Alt Tab crashes game if loading map.
- Audio lightly crackling.
- Sometimes when it crashes it takes the PC with it. (First game i've seen do this)

-Audio Input/Microphone crashes game (But i don't need this anyway)

Update: I've gave the logs names.
[steam-2073850.log.zip](https://github.com/ValveSoftware/Proton/files/13929724/steam-2073850.log.zip)

## Reproduction

Try to play the game on Ubuntu Mantic using Proton Experimental with Ryzen 3600, AMD Radeon 7800 XT.

## More Info:
Created this thread as, I'm new (I have no idea if issues go in the same thread or you create new ones) & the issues i'm having seem to be different to everyone elses.

**Comment by kisak-valve** [comment]
Hello @UbuntuGaming, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7317#issuecomment-1890778085.
