### ISSUE TITLE
DOS2 sound broken 

### ISSUE THREAD

**Issue by sumilinux** [ValveSoftware/Proton#7409]
# Compatibility Report
- Name of the game with compatibility issues: DOS2
- Steam AppID of the game:435150

## System Information
- Steamdeck
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 8.04 or experimental 
## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 

Ever since the upgrade to latest proton, the sound for the game is not working. 
Tried the following:
1. Restart deck
2. Downgrade and use older proton versions
3. Verify integrity of the game files
4. Reinstall the game.

None of the above restores the sound for the game.

**Comment by kisak-valve** [comment]
Hello @sumilinux, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/413#issuecomment-1891075967.
