### ISSUE TITLE
Evochron Mercenary doesn't start (71000)

### ISSUE THREAD

**Issue by Cuddlypuff** [ValveSoftware/Proton#741]
sys info: https://gist.github.com/Cuddlypuff/a518019d119623d9a1b7552e284c1f6d

couldnt find anything relevant in the steam terminal output or in the game's log. game process starts but sits idle at 0% cpu, no game window appears. Had to kill the process.

**Comment by muravey-omsk** [comment]
Same problem.
Tried to start with Proton 3.7 and Proton 3.16.
Tried to start with Ubuntu wine.

**Comment by muravey-omsk** [comment]
When game is "started" proton log repeat this line:
`50931.802:0008:0029:err:ntdll:RtlpWaitForCriticalSection section 0x7bceab20 "/home/proton/proton/wine/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0029, blocked by 0009, retrying (60 sec)`

**Comment by muravey-omsk** [comment]
Full log by Proton:
[steam-398170.log](https://github.com/ValveSoftware/Proton/files/2546171/steam-398170.log)

**Comment by AntipovDen** [comment]
I have the same error message for The Witcher: Enhanced Edition. Full log:
[steam-20900.log](https://github.com/ValveSoftware/Proton/files/2792038/steam-20900.log)

**Comment by zzhiyi** [comment]
Fixed in proton 4.2-3. Although first launch will show a error prompt because of missing WMV playback. Subsequent launch should work fine.

**Comment by Cuddlypuff** [comment]
Confirmed on 4.11-1, game does start the second time as zzhiyi says
Framerate felt pretty low though, although I have no idea if it's a proton-specific issue.
