### ISSUE TITLE
THE FINALS (2073850)

### ISSUE THREAD

**Issue by jackmalcom** [ValveSoftware/Proton#7413]
# Compatibility Report
- Name of the game with compatibility issues: THE FINALS
- Steam AppID of the game: 2073850

## System Information
- GPU: AMD Radeon RX 6700 XT
- Video driver version: 4.6 Mesa 23.3.3-arch1.1
- Kernel version: 6.7.0-arch3-1
- Link to full system information report as [Gist](https://gist.github.com/): [Link](https://gist.github.com/dizeeee/0820f69da8447d56f03ab6ee8538c524)
- Proton version: Experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-2073850.log](https://github.com/ValveSoftware/Proton/files/13944097/steam-2073850.log)

## Symptoms 

When trying to queue to join games, I get error TFGE0001. I have tried virtually every bit of troubleshooting advice I can to resolve this error. I have had success running the game on my Steam Deck though, which seems to indicate that this is something related to proton or my system configuration. On the Steam Deck, I verified that it worked both wired and wireless, since this issue seems to be network related. It runs without any config changes, and keeping crossplay enabled worked.

## Reproduction

- Start game
- Attempt to queue for any match

**Comment by kisak-valve** [comment]
Hello @dizeeee, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7317#issuecomment-1892933484.
