### ISSUE TITLE
Diablo IV freezes after a few minutes of playing

### ISSUE THREAD

**Issue by daqqad** [ValveSoftware/Proton#7414]
# Compatibility Report
- Name of the game with compatibility issues: Diablo IV
- Steam AppID of the game: 2344520

## System Information
- GPU: 1080Ti 11GB
- Video driver version: Nvidia 545.29.06-18.1
- Kernel version: 6.6.11
- Link to full system information report: https://gist.github.com/daqqad/f873820bd7cd9a00ff375f3f9851a678
- Runtime system info: https://gist.github.com/daqqad/0ce916487bc435ab328f8fa4c751f959
- Proton version: Experimental and 8.0-4

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
Game freezes after a few minutes. Accepts no input. Only option is to forcefully kill the game.
This is not the same issue as graphics card running out of VRAM. Will freeze even if VRAM is <80% full. 
Sound remains playing while the game is frozen (just in case it is relevant.)

## Reproduction
Play the game. Does not seem to be triggered by any specific action or sound. Will freeze during busy fights or while completely idle in town. 

[steam-2344520.zip](https://github.com/ValveSoftware/Proton/files/13944443/steam-2344520.zip)

**Comment by kisak-valve** [comment]
Hello @daqqad, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7199#issuecomment-1893015799.
