### ISSUE TITLE
Company of Heroes 2 Succesfully Runs Only Once Post Installation

### ISSUE THREAD

**Issue by surebia** [ValveSoftware/Proton#7415]
# Compatibility Report
- Name of the game with compatibility issues: Company of Heroes 2
- Steam AppID of the game: 231430

## System Information
- GPU: Nvidia GTX 1080TI
- Video driver version: nvidia 545.29.06-12
- Kernel version: 6.7.arch3-1
- Proton version: any recent one down to 4.2-19

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Company of Heroes 2, upon the second start of the game proceed to vanish from the screen and be impossible to bring back.

## Reproduction
Just opening the game a second time after a fresh download will reproduce this issue.
A couple of mentions in here might allude to the same issue: https://www.protondb.com/app/231430.

## Temporary fix
The file ```~/.steam/steam/steamapps/compat/231430/pfx/dosdevices/c\:/users/steamuser/My\ Documents/My\ Games/Company\ of\ Heroes\ 2/configuration_system.lua```, which is rebuilt after starting or closing the game seems to be malformed. Upon deletion of the mentioned file, the game opens as usual. It would probably be wise to check the ```configuration_user.lua``` file located in the same repository for this same issue. Deleting the aforementioned file works temporarily as the default file seems be used to run the game.

P.S tell me whether i should move this to the existing compatibility report. I figured, this way it would be easier to find for people who have the same issue.

**Comment by kisak-valve** [comment]
Hello @surebia, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3875#issuecomment-1893978512.
