### ISSUE TITLE
Cyberpunk 2077 freezes pc

### ISSUE THREAD

**Issue by s-b-repo** [ValveSoftware/Proton#7416]
# Compatibility Report
- Name of the game with compatibility issues: cyberpunk 2077
- [Steam AppID of the game](https://store.steampowered.com/app/1091500/Cyberpunk_2077/):

## System Information
- GPU: NVIDIA GeForce RTX 3060 Lite Hash Rate 
- GPU: AMD ATI Radeon RX 6400/6500 XT/6500M 
- nvidea latest and amd latest
- Kernel: 6.6.10-arch
- CPU: AMD Ryzen 5 5500 (12) @ 3.800GHz
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 can not freezes computer

## Symptoms 
complete pc freeze

## Reproduction
launch game

**Comment by kisak-valve** [comment]
Hello @coolst3r, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1894700121.

**Comment by s-b-repo** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/this-application-failed-to-start-because-no-qt/e5b31106-84a1-4196-92f3-a1ee633f68b0 its not because of that

This application failed to start because no Qt platform plugin could be initialised. Reinstalling the application may fix this problem.
