### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7419]
Hello, suggestion: install the Ea App just once and save the settings, and the app icon will be created on the desktop, to be configured and opened at any time.
Example: if you have 2 Ea games in your library, the Ea app will only be installed once.
Because the Ea app is installing more than 1 time, in each game the Ea app installs again. If you change the Proton version to an older one, the Ea app installs again. Even on the most recent Proton, after updating the app, it was necessary to configure it twice, log into the account twice, and the settings were different between them, even though it was already configured.

Example games: Need For Speed Most Wanted 2012, Burnout Paradise Remastered

Kubuntu lts
intel i3 1115G4
Proton 8.0-5rc, 8.0-4

Thank you very much in advance. 👍🙂

**Comment by kisak-valve** [comment]
Hello @AgoraSim21, the wineprefix for each game is intentionally separated by game title for general sanity and so that adding one game can not unexpectedly break another game that was added before. This is functionally the same issue as #604.

Closing as a duplicate.

**Comment by ghost** [comment]
Ok, thanks 👍🙂
