### ISSUE TITLE
Ubisoft Games not working because connection lost always.

### ISSUE THREAD

**Issue by vuaieo** [ValveSoftware/Proton#7420]
# Compatibility Report
- Name of the game with compatibility issues: ASSASINS CREED ORIGINS
- Steam AppID of the game: 582160

## System Information
- GPU: 3080 ti
- Video driver version: 535.154.05
- Kernel version: 6.7.0-204.fsync.fc39.x86_64 (64-bit)
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: many different , from most recent ones to 5.x...

## I confirm:
- [✅] that I haven't found an existing compatibility report for this game.
- [✅] that I have checked whether there are updates for my system available.

[steam-582160.log](https://github.com/ValveSoftware/Proton/files/13976391/steam-582160.log)

## Symptoms 

hi if i launch the assasins creed origins game then the ubisoft launcher starts and trying to connect to their service or so but it always fails, and cant run on offline mode because need at least 1 time need to be online in order to use offline mode, so i stuck in the loop and cant play ubisoft games anymore on steam. please help T_T
tryed many different proton and GE proton versions but nothing helps , its always the same.

here are the screenshots of the messages:

![ubisoft connect launcher connection lost](https://github.com/ValveSoftware/Proton/assets/110411323/caa5a812-ee82-42ff-93b6-d691b7f28932)
![offline mode](https://github.com/ValveSoftware/Proton/assets/110411323/a0440572-ffbb-40c4-a28c-4460da6badfb)

i remmber last year or so it worked "fine" so something musst have happen...

well if install the ubisoft launcher as a game and start it then the launcher works ok and i think i could play some games but because the assasins creed origin i got on steam its bound to steam acc and so clicking on download opens the launcher and its still same problem... = so cant play : (

## Reproduction

just start the assasins creed origin game 🖖

**Comment by kisak-valve** [comment]
Hello @vuaieo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/928#issuecomment-1898715114.
