### ISSUE TITLE
Hogwarts Legacy (990080): Crash on boot "Error of failed request:  BadMatch (invalid parameter attributes)"

### ISSUE THREAD

**Issue by MagiusCHE** [ValveSoftware/Proton#7421]
# Compatibility Report
- Name of the game with compatibility issues: Hogwarts Legacy
- Steam AppID of the game: 990080

## System Information
- GPU: NVIDIA GTX 4070 ti
- Video driver version: NVidia 545.29.6.0
- Kernel version: 6.7.0
- Link to full system information report as [inxi.log](https://github.com/ValveSoftware/Proton/files/13981368/inxi.log):
- Proton version: 8.0-104

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[proton.log](https://github.com/ValveSoftware/Proton/files/13981371/proton.log)

## Symptoms 
I just run the game with varius combination of ENV variables.
The problem is the same every time.
I got error just after 1 or 2 second after game start.
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Serial number of failed request:  636
  Current serial number in output stream:  647
```
I tried PROTON 8 and Experimental, even GE. Same error.

## Reproduction
1. Run the game via commandline just using PROTON
```
PROTON_LOG=1 VKD3D_CONFIG=dxr PROTON_ENABLE_NVAPI=1 PROTON_HIDE_NVIDIA_GPU=0 PROTON_NO_ESYNC=1
```
2. Game crash on error as reported

**Comment by kisak-valve** [comment]
Hello @MagiusCHE, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6510#issuecomment-1899250912.
