### ISSUE TITLE
Can't launch any games from steam on ubuntu22.04. 

### ISSUE THREAD

**Issue by chenghuaWang** [ValveSoftware/Proton#7422]
## System Information
- GPU: RTX2060
- Video driver version: nvidia 525.147.05
- Kernel version: 6.5.0
- Proton version: 8
- Can't run steam system info. It was used for a long time.
- Calling proton from Steam snap version

I can't launch any games from steam on ubuntu22.04. When I pressed the Play button, nothing happened. Everything worked fine until the recent update of Steam Proton. I also installed the Vulkan SDK(1.3.268). cuda tool kits is installed. 

And I can't find any log in $HOME by adding command `PROTON_LOG=1%command%`

**Comment by kisak-valve** [comment]
Hello @chenghuaWang, this is a Steam in Snap packaging issue.

https://github.com/canonical/steam-snap/issues/356 / https://github.com/ValveSoftware/steam-runtime/issues/640

Closing as a duplicate.
