### ISSUE TITLE
New Cycle new game crash

### ISSUE THREAD

**Issue by GerhardOfRivia** [ValveSoftware/Proton#7425]
# Compatibility Report
- Name of the game with compatibility issues: New Cycle
- Steam AppID of the game: 2198510

## System Information
- GPU: Mesa NV134
- Video driver version: 4.3 Mesa 23.0.4-0ubuntu1~22.04.1
- Kernel version: 6.5.0-14-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 8.0-4, 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[new-cycle-2198510.zip](https://github.com/ValveSoftware/Proton/files/13995325/new-cycle-2198510.zip)

## Symptoms 
Very slow menu, but once I start a new game the game crashes

## Reproduction
select new game, select any mode in any ecosystem. Start game and it crashes

**Comment by kisak-valve** [comment]
Hello @GerhardOfRivia, Proton requires a Vulkan capable video driver. Your Proton log includes `info:    Device : llvmpipe (LLVM 15.0.7, 256 bits)` which tells us that it was forced to use lavapipe (mesa's CPU based Vulkan driver) to render at all. This is not a supportable system config.

Reconfigure your system to use the NVIDIA Proprietary driver or update mesa to a version that is new enough to include NVK. (Note: mesa/NVK is fairly new at this point as is likely missing required driver features for Proton or have other bugs.)
