### ISSUE TITLE
Age of Empire IV wont launch with my Nvidia GPU

### ISSUE THREAD

**Issue by drmmwlt** [ValveSoftware/Proton#7429]
# Compatibility Report
- Name of the game with compatibility issues: Age of empire IV
- Steam AppID of the game: 1466860
- Steam version (flatpak, same bug on native) : 1705108172

## System Information
- GPU: GeForce RTX 3050 Mobile
- Video driver version: NVIDIA-SMI 545.29.06  Driver Version: 545.29.06   CUDA Version: 12.3  
- Kernel version:  6.5.13-7-MANJARO 
- Link to full system information report as [Gist][(https://gist.github.com/drmmwlt/acfedc780922ed0fbf53090a76fe9ff0)]
- Proton version: experimental or GE-25

## I confirm:
- [ y] that I haven't found an existing compatibility report for this game.
- [ y] that I have checked whether there are updates for my system available.

[steam-1466860.log](https://github.com/ValveSoftware/Proton/files/14003649/steam-1466860.log)

## Symptoms 

Some of my steam games runs very well like GTA V, Need for speed the Heat, or Dota 2. But in age of Empire IV, i dont see the shader compilation wizard and i only got 15-20 fps in solo or in multi... It also shows me in the display preference tab that the game is working on my iGpu, and not on discrete one! i just bought the game to play with friends, pls help !

I tried some launch commands like : 
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia %command% (game launches but unfortunately working with iGPU)
and
DXVK_FILTER_DEVICE_NAME="GeForce RTX 3050 Mobile" %command% (the game is compiling shader, then there is a wizard who displays i dont have a good directX library, i click OK or Later and the game crashes immediatly)

But here for the report i let blank the launch options

**Comment by kisak-valve** [comment]
Hello @drmmwlt, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5258#issuecomment-1902880339.
