### ISSUE TITLE
[SOLVED] Proton games don't start any more (Native Linux games still ok)

### ISSUE THREAD

**Issue by Pistos** [ValveSoftware/Proton#7433]
#### Your system information

* Steam Runtime Version: 3.0 and 2.0
* Distribution (e.g. Ubuntu 18.04): Gentoo, Linux kernel 6.1.67
* Link to your full system information (Help -> Steam Runtime Diagnostics) in a [Gist](https://gist.github.com/):  https://gist.github.com/Pistos/ac19cd5c12290f6dc941371b2211ff1e#file-00-steam-runtime-system-info-txt
* Have you checked for system updates?: [Yes/No] Yes
* What compatibility tool are you using?: [None / Steam Linux Runtime / Proton 5.13+ / older Proton] Proton 8, 7
* What versions are listed in `steamapps/common/SteamLinuxRuntime/VERSIONS.txt`?
```  #Name   Version         Runtime Runtime_Version Comment
  depot   0.20231128.0                    # Overall version number
  LD_LIBRARY_PATH -       scout   -       # see ~/.steam/root/ubuntu12_32/steam-runtime/version.txt
  scripts 0.20231128.0                    # from steam-runtime-tools
```
* What versions are listed in `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
  #Name   Version         Runtime Runtime_Version Comment
  depot   0.20231211.70176                        # Overall version number
  pressure-vessel 0.20231208.0    scout           # pressure-vessel-bin.tar.gz
  scripts 0.20231208.0                    # from steam-runtime-tools
  soldier 0.20231211.70176        soldier 0.20231211.70176        # soldier_platform_0.20231211.70176/
```
* What versions are listed in `steamapps/common/SteamLinuxRuntime_sniper/VERSIONS.txt`?
```
  #Name   Version         Runtime Runtime_Version Comment
  depot   0.20231211.70175                        # Overall version number
  pressure-vessel 0.20231208.0    scout           # pressure-vessel-bin.tar.gz
  scripts 0.20231208.0                    # from steam-runtime-tools
  sniper  0.20231211.70175        sniper  0.20231211.70175        # sniper_platform_0.20231211.70175/
```

#### Please describe your issue in as much detail as possible:

It seems that none of my games that use Proton launch any more. They either start up and exit in a few seconds (e.g. Whispers of a Machine, game id 631570), or start up and hang (e.g. Guild Wars 2, game id 1284210)

I had just recently done a system update, including all installed packages/apps, and also a Linux kernel major version jump, from 5.10.52 to 6.1.67.

Neither Steam Client beta, nor non-beta makes a difference.

Trying to force Proton 8 or 7 doesn't make a difference. Unchecking to not force a Proton version doesn't help.

Tried game file verification on several games. Tried uninstalling and reinstalling a game (Cook Serve Delicious 3).

Steam runtime logs and Proton logs for two games are provided in the linked gist:

* [slr-app1284210-t20240122T122342.log](https://gist.github.com/Pistos/ac19cd5c12290f6dc941371b2211ff1e#file-slr-app1284210-t20240122t122342-log)
* [steam-1284210.log](https://gist.github.com/Pistos/ac19cd5c12290f6dc941371b2211ff1e#file-steam-1284210-log)
* [slr-app631570-t20240122T122219.log](https://gist.github.com/Pistos/ac19cd5c12290f6dc941371b2211ff1e#file-slr-app631570-t20240122t122219-log)
* [steam-631570.log](https://gist.github.com/Pistos/ac19cd5c12290f6dc941371b2211ff1e#file-steam-631570-log)

In contrast, examples of native Linux games that launch and run just fine:

* Space Haven
* Just Shapes & Beats
* West of Loathing
* Pikuniku
* Pillars of Eternity

#### Steps for reproducing this issue:

1. Launch a Proton game, such as Whispers of a Machine, Guild Wars 2, Escape Simulator, Totally Accurate Battle Simulator, Crusader Kings III, Roki
2. Wait for game to start
3. (it never does)

**Comment by kisak-valve** [comment]
Hello @Pistos, this is the section of the extended runtime diagnostics to focus on: https://gist.github.com/Pistos/ac19cd5c12290f6dc941371b2211ff1e#file-00-steam-runtime-system-info-txt-L173-L197

It tells us that Vulkan is broken in general on your system, but it's not immediately obvious why.

**Comment by Pistos** [comment]
Thank you. That led me to the solution. Had to re-emerge `media-libs/vulkan-loader` with the `X` `USE` flag, as per https://wiki.gentoo.org/wiki/Vulkan#Loader .
