### ISSUE TITLE
Dinogen Online (2152990)

### ISSUE THREAD

**Issue by numerfolt** [ValveSoftware/Proton#7434]
# Compatibility Report
- Name of the game with compatibility issues: Dinogen Online
- Steam AppID of the game: 2152990

## System Information
- GPU: RX Vega 56
- Video driver version: Mesa 23.1.9-0tux1
- Kernel version: 6.5.0-10013-tuxedo
- Link to full system information report: https://gist.github.com/numerfolt/f1f6fafef05cd85d811bbf77e90feebe
- Proton version: Tried all available Proton versions, Protonlog created with Proton 8.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game is shown as running but no window appears at all.

## Reproduction
Install the game and run it.

## Logfile
[steam-2152990.log](https://github.com/ValveSoftware/Proton/files/14014192/steam-2152990.log)

**Comment by XaeroVincent** [comment]
Adding `WINE_SIMULATE_WRITECOPY=1 %command%` to the launch options allows this game to run.

**Comment by XaeroVincent** [comment]
I believe the above fix has been added to Proton bleeding-edge.

**Comment by numerfolt** [comment]
Yes, starting the game with Proton Experimental [bleeding edge] works just fine!
