### ISSUE TITLE
Command and Conquer 3: Kane's Wrath / 24810 / Black screen + loading freezes

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7436]
# Compatibility Report
- Name of the game with compatibility issues: **Command and Conquer 3: Kane's Wrath**
- Steam AppID of the game: **24810**

## System Information
- GPU: NVIDIA GeForce GTX 1050 Ti
- Video driver version: 535.146.02
- Kernel version: 5.15.0-91-generic
- Link to full system information report as Gist: [50a6c222506c7add0d88b3eb620d2b38](https://gist.github.com/st4r-w4rs/50a6c222506c7add0d88b3eb620d2b38)
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-24810.log](https://github.com/ValveSoftware/Proton/files/14025425/steam-24810.log)

## Symptoms 
1) Switching ingame resolution stucks the game within a black screen, then it freezes forever.
2) When trying launching the game (either campaingn or skirmish), the loading bar goes up to 80%, then it freezes forever.

_Same symptoms on Tiberium Wars!_
These games were working out of the box one week ago on my machine, now they are not. Something has changed, and I don't know what.

Switching to older proton version helps to start the game, but the textures are flickering there, so basically unplayable.

## Reproduction
Start game.
Try launching the game.
It freezes.

**Comment by kisak-valve** [comment]
Hello @st4r-w4rs, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/477#issuecomment-1906334107.

**Comment by ghost** [comment]
> Hello @st4r-w4rs, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#477 (comment)](https://github.com/ValveSoftware/Proton/issues/477#issuecomment-1906334107).

Sure thing, thanks @kisak-valve
