### ISSUE TITLE
Robocop: Rogue City UE Fatal Error after launch

### ISSUE THREAD

**Issue by makhlouta** [ValveSoftware/Proton#7437]
# Compatibility Report
- Name of the game with compatibility issues: Robocop: Rogude City
- Steam AppID of the game: AppId=1681430

## System Information
- GPU: RTX 4070 (Laptop Asus GA503)
- Video driver version: nvidia 545.29.06
- Kernel version: Linux fedora 6.6.12-200.fc39.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/makhlouta/5fc31bc99519ff49d29015e00657e63f
- Proton version: Experimental, 8.0-5

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

## Symptoms 
The game launches and show the title of the developer/publisher, then the Intel animation then a black screen. After that I get a UE fatal error.

## Reproduction
Game never worked, this is a consistent behavior

**Comment by kisak-valve** [comment]
Hello @makhlouta, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6918#issuecomment-1908175726.
