### ISSUE TITLE
[The last of us Part I] Nail or smoke bomb effect-textures problem

### ISSUE THREAD

**Issue by Hicks79** [ValveSoftware/Proton#7438]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: https://store.steampowered.com/app/1888930/The_Last_of_Us_Part_I/

## System Information
- GPU: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2
- Video driver version: nvidia 535.154.05
- Kernel version: 4.15.0-220-generic
- Link to full system information report as [Gist](https://gist.github.com/Hicks79/44812195fbd66a2843bd094724fe9c1e):
- Proton version: Proton Hotfix (doesnt work with 8.x)
[44812195fbd66a2843bd094724fe9c1e-9ade63595272879141d4e141f3e5a00629d66f00.zip](https://github.com/ValveSoftware/Proton/files/14040244/44812195fbd66a2843bd094724fe9c1e-9ade63595272879141d4e141f3e5a00629d66f00.zip)
## I confirm:

- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 
Screenshot. Before without problems, now smoke or nail bombs have no textures (just a flash).
![bombe](https://github.com/ValveSoftware/Proton/assets/144523021/44cc5f39-0672-4f73-988f-ed9700f1af95)

**Comment by kisak-valve** [comment]
Hello @Hicks79, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6653#issuecomment-1903455494.

**Comment by Hicks79** [comment]
Hi @kisak-valve no problem!

Thanks for the support and let me know if you need more information.
