### ISSUE TITLE
Steam client: Better separation between native Linux and Proton/SteamPlay games

### ISSUE THREAD

**Issue by akien-mga** [ValveSoftware/Proton#744]
I'd like to have a better separation / distinction between native Linux games (what we had until recently as "SteamOS + Linux" in the library) and Proton-powered Windows titles.

Currently Proton titles all show in the SteamOS + Linux tab, which can be bothersome when you have a big library (~700 native Linux games and ~1400 total in my case) and enable SteamPlay for all games in the settings.

I understand the rationale that for the many end users, whether a game is native or a whitelisted Proton game should not matter as it should be a seamless experience - but for some of us it does matter and having a clear way to separate the two would be very welcome.
It could be an option (opt-in) among the SteamPlay parameters, which would e.g. list Proton games under a "SteamPlay" or "Proton" category (like we have "Software" and "VR" categories in the library already).

**Comment by Zero86Sk** [comment]
@akien-mga This is more of a steam client request than a Proton one

I made a [Steam Feature Request](https://github.com/ValveSoftware/steam-for-linux/issues/5679) here.

**Comment by akien-mga** [comment]
Ah thanks, it indeed makes sense to get it filed there instead.

Closing as duplicate of ValveSoftware/steam-for-linux#5679.
