### ISSUE TITLE
The Witcher 3: Wild Hunt (292030): Glossary Bug

### ISSUE THREAD

**Issue by matheusfaustino** [ValveSoftware/Proton#7440]
# Compatibility Report
- The Witcher 3: Wild Hunt (v4.0.4)
- 292030

## System Information
- Steam Deck OLED
- Stock SteamOS 3.5.7 stable
- Experimental+Proton 8.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-292030.zip](https://github.com/ValveSoftware/Proton/files/14041319/steam-292030.zip)

## Symptoms 

Every time I enter the Glossary submenu (if enter the Glossary through the other options, it works, the problem is when it shows the submenu and I try to interact with it) using DX12, which allows HDR on the OLED, the game freezes and I have to force-quit the game. This issue also occurs in Gwen's tutorial. I initially tried DX12 for HDR since I couldn't enable HDR for DX11. It only occurs via DX12.

## Reproduction

1. Launch the game, as usual, and select DX12. 
2. It happens to me, independently, of the graphic preset, but I am using the Steam Deck preset.
3. Press Start (that 3 lines button on steam deck), it will show that stylish menu with Map/Quests/Inventory/etc
4. Go to Glossary and press down, it will move your cursor to the submenu which contains (Bestiary/Tutorial/Characters/Books/Crafting)
- After the submenu's animation, it freezes, and I cannot move anything (Even MangoHud is frozen).
5. It can also be stuck like that, if I enter at Gwen's Tutorial card game (the first time you talk with the scholar and he teaches you about the card game)

**Comment by kisak-valve** [comment]
Hello @matheusfaustino, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-1908703903.
