### ISSUE TITLE
steam says its runing but it dont show any window

### ISSUE THREAD

**Issue by Zockerboy1** [ValveSoftware/Proton#7441]
# Compatibility Report
- Name of the game with compatibility issues: gtaiv & episodes form liberaty city

## System Information
- GPU: gtx 680
- Video driver version: nvidia 470
- Kernel version: 5.15
cpu: AMD FX-8350 (8) @ 4.000GHz 
- Proton version: proton 8.04
it dont make a log file

## Symptoms 
steam says that the game is running, but it didnt show any game window

## Reproduction
idk how to reproduce it, i have installe steam as flatpack and it start the game but no window or sound or rockstar launcher

<!--
Computer Information:
Manufacturer: Gigabyte Technology Co., Ltd.
Model: GA-970A-UD3
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD FX(tm)-8350 Eight-Core Processor
CPU Family: 0x15
CPU Model: 0x2
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 4000 MHz
8 logical processors
8 physical processors
Hyper-threading: Unsupported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Unsupported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Freedesktop SDK 23.08 (Flatpak runtime) (64 bit)
Kernel Name: Linux
Kernel Version: 5.15.0-91-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12101004
X Window Manager: Mutter (Muffin)
Steam Runtime Version: steam-runtime_0.20231127.68515
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce GTX 680/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 470.223.02
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID: 0x10de
DeviceID: 0x1180
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1680 x 1050
Desktop Resolution: 1680 x 1050
Primary Display Size: 18.62" x 11.65" (21.93" diag), 47.3cm x 29.6cm (55.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: VIA VT2020
Memory:
RAM: 19974 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 219838 MB
Largest Free Hard Disk Block: 145742 MB
Storage:
Number of SSDs: 2
SSD sizes: 1000G,240G
Number of HDDs: 0
Number of removable drives: 0

**Comment by kisak-valve** [comment]
Hello @Zockerboy1, Proton 8.0 and newer requires the video driver to provide Vulkan 1.3 driver features. The NVIDIA 470 series video driver provides Vulkan 1.2. Since the NVIDIA 470 driver series is the last driver series to support your Kepler generation video card, this isn't a fixable issue.

You might get lucky using Proton 7.0 (or older), but since your video driver vendor has left you on a long term maintenance branch that doesn't have the necessary driver features, it makes your system unsupportable going forward.
