### ISSUE TITLE
error: decodebinX: Your GStreamer installation is missing a plug-in

### ISSUE THREAD

**Issue by DekosAnjo** [ValveSoftware/Proton#7445]
Videos play on my desktop but not on my notebook. The Proton log on my notebook indicates a missing GStreamer plugin, despite having all the necessary plugins (good, ugly, bad, base, etc.) installed.

Both devices run clean installations of Pop_OS! 22.04 LTS with installed GStreamer plugins. The sole difference is that I copied the .steam folder from another Pop_OS! installation to my desktop.

I've tested this across various Proton versions, including Proton Experimental, 8, and 7. All versions exhibit the same problem, videos failing to execute properly, even though they play flawlessly on my desktop.

I'm looking to resolve this issue, whether it's on my end or within Proton. I'm not inclined to install Windows solely for playing this game.

proton log:
```
winegstreamer error: decodebin2: Your GStreamer installation is missing a plug-in.
winegstreamer error: decodebin2: ../src-gst_base/gst/playback/gstdecodebin2.c(4704): gst_decode_bin_expose (): /GstBin:bin2/GstDecodeBin:decodebin2:
no suitable plugins found:
Couldn't set avdec_h264-1 to PAUSED
Couldn't set avdec_valve_h264-1 to PAUSED
```

```
$ apt list | grep instalado | grep gstreamer

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gir1.2-gstreamer-1.0/jammy-updates,now 1.20.3-0ubuntu1 amd64 [instalado,automático]
gstreamer1.0-alsa/jammy-security,jammy-updates,now 1.20.1-1ubuntu0.1 amd64 [instalado,automático]
gstreamer1.0-clutter-3.0/jammy-updates,now 3.0.27-2ubuntu1 amd64 [instalado,automático]
gstreamer1.0-gl/jammy-security,jammy-updates,now 1.20.1-1ubuntu0.1 amd64 [instalado,automático]
gstreamer1.0-libav/jammy-updates,now 1.20.3-0ubuntu1 amd64 [instalado]
gstreamer1.0-pipewire/jammy,now 1.0.0~1701092078~22.04~594e8f5 amd64 [instalado,automático]
gstreamer1.0-plugins-bad/jammy-security,jammy-updates,now 1.20.3-0ubuntu1.1 amd64 [instalado]
gstreamer1.0-plugins-base-apps/jammy-security,jammy-updates,now 1.20.1-1ubuntu0.1 amd64 [instalado,automático]
gstreamer1.0-plugins-base/jammy-security,jammy-updates,now 1.20.1-1ubuntu0.1 amd64 [instalado]
gstreamer1.0-plugins-good/jammy-security,jammy-updates,now 1.20.3-0ubuntu1.1 amd64 [instalado]
gstreamer1.0-plugins-ugly/jammy,now 1.20.1-1 amd64 [instalado]
gstreamer1.0-pulseaudio/jammy-security,jammy-updates,now 1.20.3-0ubuntu1.1 amd64 [instalado,automático]
gstreamer1.0-tools/jammy-updates,now 1.20.3-0ubuntu1 amd64 [instalado,automático]
gstreamer1.0-vaapi/jammy-updates,now 1.20.1-1ubuntu1 amd64 [instalado]
gstreamer1.0-x/jammy-security,jammy-updates,now 1.20.1-1ubuntu0.1 amd64 [instalado,automático]
libgstreamer-gl1.0-0/jammy-security,jammy-updates,now 1.20.1-1ubuntu0.1 amd64 [instalado,automático]
libgstreamer-plugins-bad1.0-0/jammy-security,jammy-updates,now 1.20.3-0ubuntu1.1 amd64 [instalado,automático]
libgstreamer-plugins-base1.0-0/jammy-security,jammy-updates,now 1.20.1-1ubuntu0.1 amd64 [instalado,automático]
libgstreamer-plugins-good1.0-0/jammy-security,jammy-updates,now 1.20.3-0ubuntu1.1 amd64 [instalado,automático]
libgstreamer1.0-0/jammy-updates,now 1.20.3-0ubuntu1 amd64 [instalado,automático]
```

Notebook:
![Captura_de_tela_de_2024-01-26_18-43-09](https://github.com/ValveSoftware/Proton/assets/10676754/279ef162-082b-4530-b748-512abdf38984)
Desktop:
![Captura de tela de 2024-01-26 18-40-52](https://github.com/ValveSoftware/Proton/assets/10676754/a3dd6677-7121-47c3-9322-8da58894c8c5)

**Comment by kisak-valve** [comment]
Hello @rafaelhipercg, what game are you showing in your screenshot?

The codecs installed on your host system are not used with Proton. Instead, the Steam client provides access to the h264 codec, but the game config needs to tell the Steam client that it's needed. There's a manual process mentioned at https://github.com/ValveSoftware/Proton/issues/5196#issuecomment-1502075962.

**Comment by DekosAnjo** [comment]
> Hello @rafaelhipercg, what game are you showing in your screenshot?
> 
> The codecs installed on your host system are not used with Proton. Instead, the Steam client provides access to the h264 codec, but the game config needs to tell the Steam client that it's needed. There's a manual process mentioned at [#5196 (comment)](https://github.com/ValveSoftware/Proton/issues/5196#issuecomment-1502075962).

DJMAX RESPECT V 960170

**Comment by kisak-valve** [comment]
Thanks, the config issue is a game-specific and we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5520#issuecomment-1912752665.

**Comment by DekosAnjo** [comment]
`steam steam://unlockh264/` It works, thank you very much! Why isn't this in the documentation?

**Comment by dpkirchner** [comment]
What's the deal with this `steam steam://unlockh264/` command? Is that how we must start steam if we want to workaround this issue, or is it a one-time thing, or what?
