### ISSUE TITLE
Mini Ninjas: Add OpenAL as a dependency to Proton for this title

### ISSUE THREAD

**Issue by ZeusThundr** [ValveSoftware/Proton#7447]
App ID: 35000
Proton Versions tested: GE-Proton-8-27, Proton Experimental, Proton 8.0-5, Proton 7.0-6
You will not hear any audio in game audio if you using pipewire. The only sound you will hear is the cutscenes, but during gameplay you will not hear anything.
```
Server Name: PulseAudio (on PipeWire 1.0.1)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
```
I have a feeling this could possibly be fixed or made to work without OpenAL if I changed my backend to regular pulseaudio or if I tinkered in [qpwgraph](https://github.com/rncbc/qpwgraph) but noone uses pulseaudio and not many people have tried qpwgraph including myself. The solution I provided streamlines the user experience for the avg joe.

Side note: adding and then removing `env SDL_AUDIODRIVER=pipewire gamemoderun %command%` to launch options made the audio stop working again (only working in cutscenes) I had to reinstall the game and openal again.

**Comment by kisak-valve** [comment]
Hello @ZeusThundr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/809#issuecomment-1913169104.
