### ISSUE TITLE
Elden Ring:  EAC fails to load, gives Launch Error:  "Unexpected Error:  #1"

### ISSUE THREAD

**Issue by ConHuevosGuey** [ValveSoftware/Proton#7452]
# Compatibility Report
- Name of the game with compatibility issues:  Elden Ring
- Steam AppID of the game:

## System Information
- Distrobution:  Slackware 15.0
- GPU:  Nvidia RTX 3090ti
- Video driver version: Nvidia 545.29.06
- Kernel version: 6.1.66
- Proton version:  Proton Experimental (Tried all available versions as well)

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

## Symptoms 
When launching the game the EAC popup occurs, attempts to load then has the title "Launch Error"  with "Unexpected Error: #1" and the game must exit.

## Reproduction
Launch the game.

##  Comments

I can find no other error logs as to why EAC keeps faiiling when loading.  If I use the flatpak version of steam, the game loads fine and EAC loads correctly and I can play online using Steam's flatpak version.  The game ran perfectly fine, including loading EAC when glibc 2.33 was installed.  However after updating glibc I continued to keep getting error #1 on the EAC loading banner.  I've confirmed with others that the game does indeed work with my current version of glibc (2.38), however they are Arch and Nobara distrobutions.

I'm unsure what the cause of this issue as I cannot find any information on error #1 or how to further troubleshoot it.  Nothing appears to fail in the logs and it simply seems to be the EAC module failing to load correctly for some reason.

**Comment by kisak-valve** [comment]
Hello @ConHuevosGuey, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1913639858.
