### ISSUE TITLE
Civilization VI crashes with PROTON_USE_WINED3D=1

### ISSUE THREAD

**Issue by andyflight** [ValveSoftware/Proton#7454]
I'm new to Linux, I've just installed Ubuntu 23.10 and installed civilization VI from Steam. However, for some reason I have maximum 25 fps in the game, when on Windows I got stable 60 fps. I tried to run game with the OpenGL instead of Vulkan using `PROTON_USE_WINED3D=1 PROTON_USE_WINE_DXGI=1 PROTON_NO_D3D11=1` but every time I launch game it crashes. 

- Name of the game with compatibility issues: Sid Meier's Civilization VI
- Steam AppID of the game: 289070

System Information
- GPU: Nvidia GeForce 940MX
- Video driver version: nvidia 535
- Kernel version: 6.5.0-15-generic
- Proton version: experimental-8.0-20240111c

[logs in terminal](https://gist.github.com/andyflight/c045cb1506b5bb3138dcbdaad5c7f2bd)

[proton log](https://gist.github.com/andyflight/0499fb02289127ae355218e723d4eba7)

### Symptoms 
When I try run a game with PROTON `PROTON_USE_WINED3D=1 PROTON_USE_WINE_DXGI=1 PROTON_NO_D3D11=1` game crashes in a few minnutes after launch.

### Reproduction
set `PROTON_USE_WINED3D=1 PROTON_USE_WINE_DXGI=1 PROTON_NO_D3D11=1` to launch options

**Comment by kisak-valve** [comment]
Hello @andyflight, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4068#issuecomment-1913776609.
