### ISSUE TITLE
Microsoft Flight Simulator (2020) crashes in SteamVR (using Valve Index headset) under multiple versions of Proton

### ISSUE THREAD

**Issue by sjoldzic101** [ValveSoftware/Proton#7455]
# Compatibility Report
- Name of the game with compatibility issues: Microsoft Flight Simulator
- Steam AppID of the game: 1250410
[steam-1250410.log](https://github.com/ValveSoftware/Proton/files/14078522/steam-1250410.log)
[steam console output msfs.txt](https://github.com/ValveSoftware/Proton/files/14078524/steam.console.output.msfs.txt)
![steamvr error 307](https://github.com/ValveSoftware/Proton/assets/7873471/6ee787d8-4599-41ea-abd4-a171e76397cc)
![msfs vr crash error proton](https://github.com/ValveSoftware/Proton/assets/7873471/c417dcb8-f86b-4971-aaec-48285a5566bf)

## System Information
- GPU: NVIDIA Corporation NVIDIA GeForce RTX 4080/PCIe/SSE2
- Video driver version: 4.6.0 NVIDIA 535.154.05
- Kernel version: 6.7.0-204.fsync.fc39.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/sjoldzic101/54738aab105f7107d19fce446bf5eb25
- Proton version: Proton 8.0-5 but I have tried virtually every other Proton version and it still crashes

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
If I start the game with SteamVR on, it loads up to the main screen, but the minute I put on my Valve Index headset and switch the game to VR mode and turn my head, it freezes and the game pops up two error messages and crashes. This has persisted among multiple Linux OS installs as I went distro hopping from Pop OS to Garuda Linux back to Pop OS to Nobara Linux. The issue has persisted each time. The game doesn't work either in Wayland or X11 mode on any distro I tried. My OS is up to date, so is Steam, so is SteamVR, and so is the game. This is only an issue in SteamVR.

## Reproduction
Start SteamVR first and make sure it's in SteamVR Home mode. Then boot up Microsoft Flight Simulator and wait for it to get to the main menu (you may have to update the game first). Once in main menu, put the headset on your head and click CTRL+TAB to initiate VR mode in the game. Turn your head and *viola* it crashes for me every time. The game pops up an error message that indicates a device reset and then a separate error message from SteamVR with error code 307 but the GPU is fine and this works in Windows via GPU passthrough just fine. MSFS 2020 used to work in SteamVR under Proton and Linux for me without issue for the longest time but it suddenly stopped working one day after an update and it's been a year now and it's still not working.

Attached is the log, as well as screenshots of the error messages that pop up afterward and the console output of me running "steam" from a bash prompt for this.

**Comment by kisak-valve** [comment]
Hello @sjoldzic101, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-1913792762.

**Comment by sjoldzic101** [comment]
> Hello @sjoldzic101, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-1913792762.

Thank you! I wasn't sure how this works.
