### ISSUE TITLE
Force Metal Gear Solid 2/3 to use the Deck Depot globally on Proton.

### ISSUE THREAD

**Issue by Bitwolfies** [ValveSoftware/Proton#7456]
Konami has fixed video playback in these titles on SteamDeck, but ONLY on Steam Deck, and it was done via two methods.

The first only applies to the bonus content: https://store.steampowered.com/app/2306740/METAL_GEAR_SOLID_MASTER_COLLECTION_Vol1_BONUS_CONTENT/

Adding SteamDeck=1 allows the videos to play over normal Proton, Forespoken also had a similar issue, it was fixed by globally adding SteamDeck=1 to the game when ran via Proton, the same should happen here.

As for the other two, they have custom Deck depots, which while possible to download on desktops, are not done by default, Proton should enforce the Deck repo on desktop to allow these games to function correctly.

https://store.steampowered.com/app/2131640/METAL_GEAR_SOLID_2_Sons_of_Liberty__Master_Collection_Version/
https://store.steampowered.com/app/2131650/METAL_GEAR_SOLID_3_Snake_Eater__Master_Collection_Version/

Note: The videos still don't actually play without converted versions from the compiled shader downloads or a modified proton, however you'd never be able to actually get to the videos without this new patch and command.

Yes, ideally Proton would be patched to fix the issues without workarounds, but for the time being this seems like a fair compromise to have the games work at all.

**Comment by NyaomiDEV** [comment]
Oh God this is worse than no support at all

**Comment by Bitwolfies** [comment]
No longer needed, latest proton bleeding edge video patches fix the videos.

**Comment by NyaomiDEV** [comment]
> No longer needed, latest proton bleeding edge video patches fix the videos.

I cannot reproduce today on Proton Experimental and game version 1.5.1. For me, on an unmodified installation, the intro video plays without audio still.

I don't know if the work on BE didn't get onto Experimental as of yet, but we're in September so I am at a loss.
