### ISSUE TITLE
Lethal Company (VR mod)

### ISSUE THREAD

**Issue by terminal-case** [ValveSoftware/Proton#7457]
# Compatibility Report
- Name of the game with compatibility issues: Lethal Company
- Steam AppID of the game: 1966720

## System Information
- GPU: NVIDIA GeForce RTX 3070 Lite Hash Rate
- Video driver version: nvidia-dkms 545.29.06
- Kernel version: 6.6.10-273-tkg-eevdf
- Link to full system information report as [Gist](https://gist.github.com/terminal-case/363c94105a5ac16144574f253e37a48f):
- Proton version: 8.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game (at least, not with this particular usage scenario)
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game runs just fine without the [VR mod](https://github.com/DaXcess/LCVR/tree/main), but with it, like with some other Unity OpenXR-based games and mods, the game will not run. Specifically, I get a few frames of the "Made with Unity" startup screen showing in my headset, and then the headset crashes with error (-203) and the game freezes and must be force-exited.

## Reproduction
Start up SteamVR and Index knuckle controllers, and attempt to launch Lethal Company modded through r2modman with only the LCVR mod and its one dependency active.
[steam-1966720.log](https://github.com/ValveSoftware/Proton/files/14087557/steam-1966720.log)
[vrcompositor.txt](https://github.com/ValveSoftware/Proton/files/14087558/vrcompositor.txt)

**Comment by kisak-valve** [comment]
Hello @terminal-case, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7320#issuecomment-1915254980.
