### ISSUE TITLE
Metal gear online - controls don't work

### ISSUE THREAD

**Issue by mangonebula** [ValveSoftware/Proton#7458]
# Compatibility Report
- Name of the game with compatibility issues:
- Metal gear solid v the phantom pain - metal gear online
- Steam AppID of the game:
287700

## System Information

On steamdeck
- GPU: 
- Video driver version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: latest

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [ x that I have checked whether there are updates for my system available.

## Symptoms 
The controls on the steamdeck don't work. The game thinks that is in keyboard and mouse mode. The joysticks don't move the character or allow you to look.
The controls work fine in the main game, but metal gear online is unplayable

**Comment by kisak-valve** [comment]
Hello @mangonebula, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/124#issuecomment-1915447337.
