### ISSUE TITLE
Mafia Definitive Edition: Button Icons appear as white squares

### ISSUE THREAD

**Issue by gu3st** [ValveSoftware/Proton#7462]
# Compatibility Report
- Name of the game with compatibility issues:  Mafia Definitive Edition
- Steam AppID of the game: 1030840

## System Information
- GPU: Steam Deck non-OLED 256GB
- Video driver version: Mesa 23.1.3 
- Kernel version: 6.1.52-valve9-1-neptune-61 
- Link to full system information report as [System Info Report Gist](https://gist.github.com/gu3st/4bbfee9fec0dd59a34cd055234308438):
- Proton version: 8.0-5c

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

In the UI the button glyphs seem to appear correctly, but not in the world.   On PC, the advice is to disable Steam Input + Steam Overlay to force the game to fall back to non-Steam Input glyphs, but that's not an option on Steam Deck

## Reproduction

Launch the game.  Either play a bit until you hit the foot chase scene and you'll see the button prompts for sprint/climb are white squares, not the Steam Input glyphs.

Alternatively, go into Carpedia and test drive a car.  Fail the test and see that the retry/quit icons are white glyphs instead of their proper buttons (Y and X appropriately

[steam-1030840.log](https://github.com/ValveSoftware/Proton/files/14115852/steam-1030840.log)

**Comment by kisak-valve** [comment]
Hello @gu3st, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4220#issuecomment-1919749905.

**Comment by nicdesu** [comment]
5 Months later still the same. Can't even get past the first chapter

**Comment by coreybruce** [comment]
Yeah this really needs to be fixed..
