### ISSUE TITLE
Relato de Problema com DmC Devil May Cry no Linux usando Proton

### ISSUE THREAD

**Issue by enzogabrielrochafreitas** [ValveSoftware/Proton#7466]
Olá equipe de suporte da Valve Software,

Espero que esta mensagem os encontre bem. Estou enfrentando dificuldades ao tentar jogar DmC Devil May Cry no Linux usando o recurso Steam Play Proton. O jogo apresenta crashes recorrentes em fases específicas, resultando em uma experiência de jogo prejudicada.

Detalhes do Problema:

Os crashes ocorrem em momentos específicos durante o jogo, sem uma mensagem de erro clara.
Já verifiquei e atualizei todas as configurações do meu sistema, incluindo versão do Linux, Proton e drivers gráficos.
Informações do Sistema:

Sistema Operacional: 6.1.71-1-MANJARO (64-bit)
Versão do Proton: 8.0-5
Especificações de Hardware: 15,5 GiB de RAM, Mesa Intel® HD Graphics 4000, 4 × Intel® Core™ i7-3537U CPU @ 2.00G

Passos para Reproduzir:

Os crashes parecem estar associados a fases específicas do jogo, mas não consigo identificar um padrão claro.
Logs e Mensagens de Erro:

Não há mensagens de erro visíveis; o jogo simplesmente trava e fecha.
Versão Específica do Jogo:

Estou utilizando a versão mais recente disponível do DmC Devil May Cry na Steam.
Agradeço antecipadamente por sua assistência na resolução deste problema. Caso necessitem de mais informações ou detalhes, estou à disposição para colaborar.

Atenciosamente,

Enzo

**Comment by kisak-valve** [comment]
Hello @enzogabrielrochafreitas, the Vulkan drivers for your Ivybridge generation Intel GPU is considered experimental by your video driver vendor and not spec-compliant. Graphical artifacts and/or crashes is generally expected with your GPU. Unfortunately, that also makes your system unsupportable by Proton in general and your issue is not really solvable without a newer hardware.

You might get lucky telling Proton to use wine's DirectX to OpenGL render path by setting the game's launch options to `PROTON_USE_WINED3D=1 %command%`, but this runtime option comes with a significant performance penalty and is not considered supported.

**Comment by enzogabrielrochafreitas** [comment]
Olá, @kisak-valve 

Agradeço pela resposta rápida. Compreendo que a GPU Intel Ivybridge e seus drivers Vulkan são considerados experimentais, o que pode levar a artefatos gráficos e travamentos.
 No entanto, é importante mencionar que, na primeira vez em que iniciei o jogo, utilizei o comando PROTON_USE_WINED3D=1 %command%, e isso possibilitou uma execução mais estável, mesmo que com algumas limitações gráficas. Além do problema mencionado, gostaria de informar que estou enfrentando crashes específicos nas missões 8 do jogo principal e a missão 2 de "Vergil's Downfall". Importante destacar que as outras  fases do jogo não apresentam esse problema.

Estes crashes ocorrem mesmo com as configurações gráficas reduzidas e com o comando  PROTON_USE_WINED3D=1 %command%.

Agradeço novamente pela atenção e aguardo orientações adicionais sobre como posso proceder.

Atenciosamente,

Enzo

**Comment by kisak-valve** [comment]
Regarding any issues you see with wine's DirectX to OpenGL render path, while it's sometimes useful for troubleshooting, it's not considered supported on Proton's side.

If you want to troubleshoot running anything with wined3d, then the way forward is to reproduce the issue with a current release of vanilla wine, report your issue upstream (https://bugs.winehq.org/), and if it gets fixed upstream, those changes will eventually make its way downstream in a future major update of Proton that pulls in a newer version of wine.

**Comment by enzogabrielrochafreitas** [comment]
Prezado @kisak-valve ,

Agradeço pela sua assistência e orientação. Suas informações foram recebidas e serão consideradas. Caso surjam novas dúvidas ou atualizações relevantes, entrarei em contato.

Atenciosamente,
Enzo
