### ISSUE TITLE
Ori and the Blind Forest: Definitive Edition (387290) graphics glitches

### ISSUE THREAD

**Issue by WinPooh32** [ValveSoftware/Proton#747]
Game looks working but it is not playable due to some graphics glitches.
Short video: [https://youtu.be/ovBmObU0cMQ](https://youtu.be/ovBmObU0cMQ)
[System information](https://gist.github.com/WinPooh32/e68bbc783c703ba3e8a9c4d6d9e56b3b)

**Comment by tournierjc** [comment]
Hello,

You should update your mesa drivers as other member reported this game as working fine.

**Comment by WinPooh32** [comment]
Installed Mesa 18.3.0-devel - padoka PPA
[glxinfo output](https://gist.github.com/WinPooh32/f3ebbbe7c78fc650dd9724bf087eeb7a)
I can see same glitches.

[steam-387290.log](https://github.com/ValveSoftware/Proton/files/2323457/steam-387290.log)

**Comment by WinPooh32** [comment]
Glitches were solved by `PROTON_USE_WINED3D11=1 %command%`

**Comment by kisak-valve** [comment]
Hello @WinPooh32, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/67#issuecomment-416249635.

That said, this reads like there's an mesa/intel/anv driver bug and should also be brought to the attention of your video driver vendor.
