### ISSUE TITLE
What is the SteamLinuxRuntime version latest version compatible with Proton 7.0-6 ?

### ISSUE THREAD

**Issue by Augusto7743** [ValveSoftware/Proton#7473]
Thanks for reading my topic.
Excuse me if here not is the correct area to post that topic. Report me and that topic will be closed.

Proton last version compatible with Nvidia kepler is Proton 7.0-6.
What is the Steam Linux Runtime last version to be used with Proton 7.0-6 ? version 3.0 is compatible ?

**Comment by kisak-valve** [comment]
Hello @Augusto7743, Steam automatically selects the runtime container that's required for use with specific Proton versions.

In Proton 7.0's case, it's been built against the Steam Linux Runtime 2.0 (Soldier)'s ABI and is only intended to be run in that runtime environment.

**Comment by Augusto7743** [comment]
Thanks kisak.
Have an nice week.
