### ISSUE TITLE
Is possible run command install internally inside Steam Client Proton ?

### ISSUE THREAD

**Issue by Augusto7743** [ValveSoftware/Proton#7474]
Hello.
Thanks for reading my topic.

Excuse me if here not is the correct area to post that topic. Report me and that topic will be closed.
Here Ubuntu 20.04.6 and Steam for Linux current version with Proton 8.0 and Experimental.
I have manually copied DXVK files inside steam lib paths, but not work. Is as if need change internal registry settings.
I want to do it because my video card is GF kepler using driver 470 having support only for vulkan 1.2.
I want see if is possible run Proton 8.0 using DXVK previous version. An test not will to do serious problems. I can reinstall Proton if need.

Is possible use command for install alternate DXVK version inside installed Proton 8.0 ? How to do it ?

Have an nice day.

**Comment by kisak-valve** [comment]
Hello @Augusto7743, manually swapping out bundled components of Proton is not something that can be supported. Sorry, but your hardware is not supportable going forward.

**Comment by Augusto7743** [comment]
Thanks for your reply.
However I want see if is possible install dxvk version compatible with kepler driver 470 only for use in dx11 games.
Really copying and swapping components can happen errors.
Is or not possible run command in terminal for install dxvk old versions ?

Hey you is the owner of https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa ?
If yes HUGE THANKS !!!
