### ISSUE TITLE
Persona 3 Reload - Bad Framerate with steamOS opposed to Windows

### ISSUE THREAD

**Issue by vreh1** [ValveSoftware/Proton#7476]
Name of the game with compatibility issues: Persona 3 Reloaded
Steam AppID of the game: 2161700

System Information
GPU: AMD 7900 XT
Video driver version: 23.1.9
Kernel version: 6.7.2
Link to full system information report as [Gist](https://gist.github.com/ciferkey/8581dcba9cf843df80d7e94cbaae0f22):
Proton version: 8.0-5 and Experimental

I confirm:
 that I haven't found an existing compatibility report for this game.
 that I have checked whether there are updates for my system available.
[steam-2161700.log](https://github.com/ValveSoftware/Proton/files/14140720/steam-2161700.log)

Symptoms
Games framerate runs terribly using steamOS or latest version of proton. Using windows seems to fix all issues present in steamOS. 

Reproduction
No settings were changed from default settings. Launch the game directly from steamOS. dips down to 20 in places like tarturus and velvet room even below that. When using windows, these drops arent present and even perform well with reflections on

**Comment by kisak-valve** [comment]
Hello @vreh1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7472#issuecomment-1925571010.
