### ISSUE TITLE
Apparmor  Ubuntu 23.10 preventing various games from launching  ( disabling apparmor allows games to run )

### ISSUE THREAD

**Issue by im000000** [ValveSoftware/Proton#7477]
# Compatibility Report
- Name of the game with compatibility issues:
- HumanKind
- Grand Theft Auto v
- possibly more
- 
- Steam AppID of the game:
1124300

## System Information
- GPU: 
- Video driver version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/im000000/513f3563e2c5c00fd3ef255041720d87
- Proton version:
- 8.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

** No proton logs generated, likely apparmor **     

## Symptoms 

apparmor preventing some steam games to launch.  i can get the games to run after I disable apparmor using the "aa-teardown" command

app armor denied messages:

seeing messages like this: 
[  273.570414] audit: type=1400 audit(1707055145.012:44642): apparmor="DENIED" operation="open" class="file" profile="snap.steam.steam" name="/proc/5047/environ" pid=5864 comm="steam" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000

link below:

https://gist.github.com/im000000/570f387dc9216a848a5a9cca64900afe

## Reproduction

Tried to launch games but it never starts.

**Comment by kisak-valve** [comment]
Hello @im000000, this is a Steam in Snap packaging issue, not a Proton issue and is being tracked at https://github.com/ValveSoftware/steam-runtime/issues/640 / https://github.com/canonical/steam-snap/issues/356.

Closing as a duplicate.
