### ISSUE TITLE
Life is Strange Before the storm crashes in proton both 3.7.3 and 3.7.4-beta

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#748]
App crashes and make dump files.
[Life is Strange - Before the Storm.tar.gz](https://github.com/ValveSoftware/Proton/files/2323254/Life.is.Strange.-.Before.the.Storm.tar.gz)

**Comment by Brisse89** [comment]
This game does not work with DXVK due to lack of stream output support in DXVK.

It should run fine if you set the following start parameter to disable DXVK:
`PROTON_USE_WINED3D11=1 %command%`

See also: https://github.com/ValveSoftware/Proton/issues/75

**Comment by ghost** [comment]
Thanks! I'll try to run with this command
