### ISSUE TITLE
Final Fantasy VII (39140) Using 7th Heaven - Freezing/Stuttering/Long Loading Times Since Proton 8.0-4

### ISSUE THREAD

**Issue by dotaxis** [ValveSoftware/Proton#7480]
# Compatibility Report
- Name of the game with compatibility issues: 7th Heaven (Final Fantasy VII)
- Steam AppID of the game: 39140
- 7th Heaven Project: https://github.com/tsunamods-codes/7th-Heaven
- 7thDeck Project (Installer): https://github.com/dotaxis/7thDeck/tree/dev

## System Information
- Steam Deck (LCD and OLED)
- All SteamOS versions
- Proton version: 8.0-4+

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
I maintain a small project ([7thDeck](https://github.com/dotaxis/7thDeck)) to get mods running on FF7 using 7th Heaven.

Since the release of Proton 8.0-4, about 50% of my users were reporting freezing and stuttering going into battles and cutscenes that were not present before. We did try downgrading DXVK and other dependencies via protontricks but found the issue to be with Proton itself, as far as we could tell. Our solution at the time was to roll back to Proton 7 and hope the next major update would fix this. It was not fixed in 8.0-5.

Unfortunately, we can not find anything useful in the logs to pin down what may be causing this, so I did not decide to report an issue sooner. It seems this only happens for about 50% of end-users, and I'm not able to reproduce it on my own hardware, so my ability to troubleshoot is also quite limited.

I am waiting on a proton log from an affected user and will attach it as soon as I can.

## Reproduction
1. Install 7th Heaven using the [proton8 branch of 7thDeck](https://github.com/dotaxis/7thDeck/tree/proton8)
2. Run game via 7th Heaven
3. Enter battle and observe load times and stuttering
4. Install 7th Heaven using the [dev branch of 7thDeck](https://github.com/dotaxis/7thDeck/tree/dev)
5. Run game via 7th Heaven
6. Observe improved load times and no stuttering

**Comment by kisak-valve** [comment]
Hello @dotaxis, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/694#issuecomment-1927697561.

**Comment by dotaxis** [comment]
This issue is only present when using 7th Heaven and as such is not necessarily directly tied to the game itself.

I'm not sure this report belongs in that thread.
