### ISSUE TITLE
steam deck

### ISSUE THREAD

**Issue by treceno** [ValveSoftware/Proton#7481]
Se queda el logo de steam dando vueltas despues de suspender y volver

**Comment by kisak-valve** [comment]
Hello @treceno, sorry, but this isn't coherent and doesn't appear to be related to the Proton compatibility layer.

**Comment by simifor** [comment]
@treceno esta pagina es especifica para reportes que tienen que ver con proton. Tu problema debe estar relacionado con el propio sistema operativo. Puedes usar este enlace para tener más información de donde reportar el problema https://help.steampowered.com/es/faqs/view/7DD4-C618-182E-0E49
