### ISSUE TITLE
[Regression] Hellblade Senoa's sacrifice (414340)

### ISSUE THREAD

**Issue by lyingpasta** [ValveSoftware/Proton#7488]
# Compatibility Report
- Name of the game with compatibility issues: Hellblade Senoa's sacrifice
- Steam AppID of the game: 414340

## System Information
- GPU: RX 650 XT
- Video driver version: Mesa 23.2.0-devel
- Kernel version: Ubuntu 23.10
- Proton version: 8.0-5 and Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Crash on startup with error 
![image](https://github.com/ValveSoftware/Proton/assets/99407640/bfb83df0-531a-4b8f-89f1-66f113cc7260)

Works fine with Proton 7, according to other's tests seems to work with proton 8.0-4

## Reproduction
Run the game with compatibility

**Comment by kisak-valve** [comment]
Hello @HarissaHero, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/943#issuecomment-1936480442.
