### ISSUE TITLE
Cyberpunk 2077 ctd

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7489]
# Compatibility Report
- Name of the game with compatibility issues: Cyberpunk 2077
- Steam AppID of the game: 1091500

## System Information
- GPU: AMD Radeon RX 7900XTX
- Video driver version: Mesa 23.3.5-arch1.1
- Kernel version: 6.7.4-arch1-1 
- Link to full system information report as [Gist](https://gist.github.com/alber-MnTn/7e3c98f7843266098aac1dd851dd29ef)
- Proton version: Experimental/8.0-5
- [steam-1091500.log](https://github.com/ValveSoftware/Proton/files/14228619/steam-1091500.log)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

The game CTDs in apparently random situations, with no warning nor error message. I say "apparently random" because sometimes it can be avoided, but during some main mission quests, the game crashes when I move the camera to certain points on the scene (sometimes the target)
The game worked perfectly for several days, I guess some update (weather in game or system) messed something up

## Reproduction

I include a save game file. If I move towards the camionet, I get the CTD
[ManualSave-1.zip](https://github.com/ValveSoftware/Proton/files/14228642/ManualSave-1.zip)

**Comment by kisak-valve** [comment]
Hello @alber-MnTn, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1937009882.
