### ISSUE TITLE
HELLDIVERS™ 2 (553850) No connection to server.

### ISSUE THREAD

**Issue by 19Topgun93** [ValveSoftware/Proton#7491]
# Compatibility Report
- Name of the game with compatibility issues: Helldivers 2
- Steam AppID of the game: 553850

## System Information
- GPU: Geforce GTX 1070
- Video driver version: nvidia 545.29.06
- Kernel version: 6.7.4-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/19Topgun93/b24ea714f0ce2c0eeeafca0b246d84b5
- Proton version: 1707597642 GE-Proton8-31-1-g6fb8c815
## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

``

## Symptoms 

After a update from Helldivers 2. It starts with no problems. I have connect my Playstation account to Steam. But at the start screen, I cannot connect to servers. The attachment.
![Bildschirmfoto vom 2024-02-11 12-18-21](https://github.com/ValveSoftware/Proton/assets/41064191/dd5716cf-533c-4485-ba25-2714815d8836)

I have reinstall the game twice, but the Problem is still there. In Protondb, it has now Gold status.
Can you help me please?

## Reproduction
By me. I start the game and that's it.

[steam-553850.log](https://github.com/ValveSoftware/Proton/files/14232294/steam-553850.log)

**Comment by kisak-valve** [comment]
Hello @19Topgun93, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7486#issuecomment-1937765128.
