### ISSUE TITLE
f1 2022 camera problem

### ISSUE THREAD

**Issue by lucada30** [ValveSoftware/Proton#7493]
steam version : 1705108172

Thanks to steam and proton I can play formula 1 on linux!!! 
Unfortunately I have an annoying problem when replaying F1 22.
For example, when I make a mistake on the track and I want to fix it, I pause and then choose the item "INSTANT REPLAY FLASHBACK" and the game goes back, unfortunately I can only choose cameras that look backwards (I attach photos of the available shots).
If I play with Windows the problem doesn't exist.

I also tried:
1) reinstall F1 22
2) reinstall steam
3) reinstall linux
but nothing worked for me.
Can anyone help me ???
![20240211200341_1](https://github.com/ValveSoftware/Proton/assets/60314104/9015a41f-2044-4e5c-90eb-9883290e663d)
![20240211200344_1](https://github.com/ValveSoftware/Proton/assets/60314104/1a64a439-1986-4bc8-ac8c-ba18d64160fb)
![20240211200346_1](https://github.com/ValveSoftware/Proton/assets/60314104/c47212c0-558a-4bdf-8bd8-387486e5846b)
![20240211200348_1](https://github.com/ValveSoftware/Proton/assets/60314104/854310a4-ee1e-42dd-96cf-258cb287db76)
![20240211200330_1](https://github.com/ValveSoftware/Proton/assets/60314104/486f1707-fb0f-4a5a-922d-fa2dbdbde826)

**Comment by lucada30** [comment]
steam version : 1705108172

-->Thanks to steam and proton I can play formula 1 on linux!!! 
Unfortunately I have an annoying problem when replaying F1 22.
For example, when I make a mistake on the track and I want to fix it, I pause and then choose the item "INSTANT REPLAY FLASHBACK" and the game goes back, unfortunately I can only choose cameras that look backwards (I attach photos of the available shots).
If I play with Windows the problem doesn't exist.

I also tried:
1) reinstall F1 22
2) reinstall steam
3) reinstall linux
but nothing worked for me.
Can anyone help me ???

**Comment by kisak-valve** [comment]
Hello @lucada30, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5963#issuecomment-1937886785.
