### ISSUE TITLE
Linux-native Half-Life 2 erroneously includes hl2.exe and tries to start it unless Steam Linux Runtime is forced in Compatibility tab

### ISSUE THREAD

**Issue by Cloudwalk9** [ValveSoftware/Proton#7495]
This is not a Proton issue directly but I don't know where else to put this.

**Comment by Cloudwalk9** [comment]
My bad, something went horribly wrong with my Steam Runtime 2.0 installation.

**Comment by kisak-valve** [comment]
This is https://github.com/ValveSoftware/steam-for-linux/issues/9875.

**Comment by Cloudwalk9** [comment]
@kisak-valve Oh, phew, it's not just me then. Thanks.
