### ISSUE TITLE
Games Close when using Mouspad Gestures

### ISSUE THREAD

**Issue by sicraftertv** [ValveSoftware/Proton#7496]
When using Linux on a Laptop Games that launch with Proton Close Instantly when using Mousgestures.
Iam using Ubuntu 22.04. and Proton Experimental.
The issue should be with every Game that uses Proton.
[steam-960090.log](https://github.com/ValveSoftware/Proton/files/14235853/steam-960090.log)

**Comment by kisak-valve** [comment]
Hello @sicraftertv, this issue is already being tracked at #5744. Closing as a duplicate.

**Comment by dylanmtaylor** [comment]
Hey, this is fixed in the new version of XWayland :) This version ships in Ubuntu 24.04. https://packages.ubuntu.com/source/noble/xwayland
