### ISSUE TITLE
Puzzle Bobble™2X/BUST-A-MOVE™2 Arcade Edition & Puzzle Bobble™3/BUST-A-MOVE™3 S-Tribute (1913620)

### ISSUE THREAD

**Issue by Mte90** [ValveSoftware/Proton#7497]
# Compatibility Report
- Name of the game with compatibility issues: uzzle Bobble™2X/BUST-A-MOVE™2 Arcade Edition & Puzzle Bobble™3/BUST-A-MOVE™3 S-Tribute
- Steam AppID of the game: 1913620

## System Information

Latest steam deck

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Reproduction

On Steam Deck with the dock station with 2 controllers the second one isn't detected. The game detects the first controller and the native steam deck.
From the controller settings on change order I get this:

![image](https://github.com/ValveSoftware/Proton/assets/403283/8ba028b5-7df6-400d-ad16-ab4aac86de46)

As you can see there is a different icon on the last one where usually games that detects rightly doesn't have that issue.
The similar issue on:

* https://github.com/ValveSoftware/Proton/issues/3375#issuecomment-1794487133
* https://github.com/ValveSoftware/Proton/issues/83#issuecomment-1497567666
* Broforce instead detects both the controllers but the first one works the analog sticks and in the second one after changing the controller order doesn't detect the stick of the second one

**Comment by simifor** [comment]
I was unable to reproduce this on steamos 3.6.20 after trying bust a move 2/3 and puzzle bobble 2x and 3, but I don't have xbox 360 controllers, I'm curious if you still face the same issue which would suggest your configuration is being treated differently.

**Comment by Mte90** [comment]
@simifor did you tried the game with the dock station and a couple of external controllers?

Because the stema deck works but not with external, so I can't play with other players in local coop.

**Comment by simifor** [comment]
I did. I now re-tested using the official dock and the DualShock 4, Dual
Sense and 8bitdo Pro 2 in the following combinations: DS4 + DS, DS4 + Pro2,
Pro2 + DS. I only opened bust a move 2 this time around, but in each of
those scenarios each of those controllers was assigned to a character, I
didn't manually change the controller order either.

**Comment by Mte90** [comment]
You are right, now seems working.

In the menu only the first controller wor it is enough to start a match with 2 players and works.
