### ISSUE TITLE
Poppy Playtime (1721470)

### ISSUE THREAD

**Issue by DrThomasXLight** [ValveSoftware/Proton#7498]
I'm trying to run Poppy Playtime from my Steam Library and receives the following  errors:
With Proton 8.0-5
![Screenshot from 2024-02-14 08-07-54](https://github.com/ValveSoftware/Proton/assets/56457861/7c417c8d-8f95-4471-ab0f-76662a79949c)

With Proton 7.0-6
![Screenshot from 2024-02-14 02-17-43](https://github.com/ValveSoftware/Proton/assets/56457861/c42cf941-a96c-49a5-9d51-386a8f71cf80)

![Screenshot from 2024-02-14 02-18-13](https://github.com/ValveSoftware/Proton/assets/56457861/ec5cf99a-e099-481b-a732-8564dd05ae09)

These are my computer specifications:

# System Details Report
---

## Report details
- **Date generated:**                              2024-02-14 08:12:17

## Hardware Information:
- **Hardware Model:**                              ASUS TUF GAMING B560M-PLUS WIFI
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i5-10400F × 12
- **Graphics:**                                    NVIDIA GeForce GTX 1650
- **Disk Capacity:**                               1.2 TB

## Software Information:
- **Firmware Version:**                            0811
- **OS Name:**                                     openSUSE Tumbleweed
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.3
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.7.4-1-default

I opened a case via STEAM and they redirect me here for some help.  I tried running it with a lower level Proton version (Proton 7.3), and still got the same errors. I play perfectly well Crysis, Dead Island, Portal, Black Mesa and others. What else can I do to run the game?

**Comment by kisak-valve** [comment]
Hello @DrThomasXLight, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by DrThomasXLight** [comment]
Here is the requested gist link:  https://gist.github.com/DrThomasXLight/bc40c4c4255d6ec8765bb979210d54de

**Comment by kisak-valve** [comment]
Proton 8.0 and newer requires that the video driver provides Vulkan 1.3. The NVIDIA 470 series driver provides Vulkan 1.2 which is too old for continued support. Please update your video driver and retest. If that doesn't help, then please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by DrThomasXLight** [comment]
Updated the graphics driver 470 series to nvidia-video-G06 545.29.06.. it's working now.. thanks for the help.

**Comment by DrThomasXLight** [comment]
Updated the graphics driver 470 series to nvidia-video-G06 545.29.06.. it's working now.. thanks for the help.

**Comment by villodres2013-cyber** [comment]
a mi m ocurre lo mismo cn el mismo error

**Comment by villodres2013-cyber** [comment]
que hago?
