### ISSUE TITLE
When using an NTFS volume on both Steam and Windows, Steam makes an entry using c: and z:

### ISSUE THREAD

**Issue by 0x6A7232** [ValveSoftware/Proton#7500]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
When using an NTFS volume on both Steam and Windows, Steam makes an entry using c: and z:  -- this is invalid characters for an NTFS volume to have, and therefore chkdsk will remove them.
Instead of creating invalid filenames on NTFS volumes, mount an ext4 VHDX image to the empty NTFS folder.  I can confirm that mounting a device to an empty NTFS folder works in Linux, and I've also mounted devices in Windows under blank NTFS folders.  Therefore, all that needs to be done is having Steam on Windows install an ext4 filesystem driver (such as https://github.com/bobranten/Ext4Fsd or what it is based on, Ext2Fsd, which also works on ext4 volumes).  

## Justification [optional] 

Compatibility.  Speaking of, you could use Proton on Windows as a compatibility layer for some older Win 9x games I bet...

## Risks [optional]

None that I'm aware of?

## References [optional] 
Run a game with a Steam prefix on it in a dual boot system or Steam Deck on an NTFS partition (so that you can share the storage instead of doubling it, one for both OSes).  Then boot to Windows and run a chkdsk c: /f

**Comment by kisak-valve** [comment]
Hello @0x6A7232, noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation, sharing Steam library folders between OSes is not supported and can lead to undefined behavior.
