### ISSUE TITLE
The Coffin Of Andy And Leyley (2378900)

### ISSUE THREAD

**Issue by nonetrix** [ValveSoftware/Proton#7502]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 2378900

## System Information
- GPU: RX 6800
- Video driver version: Mesa 23.3.5
- Kernel version: 6.7.4
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 8.0-5, also tested experimental and unofficial GE version

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Log
[steam-2378900.log](https://github.com/ValveSoftware/Proton/files/14320034/steam-2378900.log)

## Symptoms 
- Bugged almost unusable UI 
- Weird stretch effect/pixels repeating in game

## Reproduction
1. Download the game
2. Play the game
3. See broken UI
4. Start the game
5. See how the game is broken outside of the UI as well

## Screenshots
![2024-02-15-162324_hyprshot](https://github.com/ValveSoftware/Proton/assets/45698918/76d8cf66-9a9b-4d03-9ec5-868a2af8e6a9)
![20240217_13h40m17s_grim](https://github.com/ValveSoftware/Proton/assets/45698918/d0c8ef02-1080-46c9-9911-993e832dde24)
![20240217_13h38m08s_grim](https://github.com/ValveSoftware/Proton/assets/45698918/6cce1c63-8ac5-44b1-ba2a-35f23024a907)

**Comment by kisak-valve** [comment]
Hello @nonetrix, your system is configured to run the game with AMDVLK. Can you test if running the game with mesa/RADV has an effect?

**Comment by nonetrix** [comment]
I completely forgot I had that driver installed, no idea why it was preferring it over RADV. Fixed my issues, I guess I should make a issue to the AMDVLK driver?
