### ISSUE TITLE
Akane the Kunoichi (291130)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#7504]
# Compatibility Report
- Name of the game with compatibility issues: Akane the Kunoichi
- Steam AppID of the game: 291130

## System Information
- LE OLED 1 TB Steam Deck
- Proton version: Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game was marked as playable on deck and it seems to work fine for the first 3 levels, but starting from level 2-1 onward, 2 very noticable issues become present.

1: Level 2-1 is completely devoid of music, sound effects from characters still play, but no music plays.

2: Every 4 seconds, there is a noticable lag spikes hitch on level 2-1 onward that can be seen if you pull up Mangohud. Older Protondb reports say this used to happen on every level (along with the broken music), but I was not able to replicate. The only thing that I can confirm is that the issues show up from level 2-1 onward.
[steam-291130.log.txt](https://github.com/ValveSoftware/Proton/files/14321168/steam-291130.log.txt)

Pic (Shot from my phone cause I can't get mangohud using the built in screencapper, that frame spike shows up every 4 seconds)
![20240217_213031](https://github.com/ValveSoftware/Proton/assets/78768499/892938d6-ebd5-40a3-aeca-3d41140ef248)

## Reproduction
Play through the game and notice the working music and good performance until you get to 2-1, then notice the hitches and lack of music.

https://www.youtube.com/watch?app=desktop&v=mvwwS2Rh7AY&pp=ygUWYWthbmUgdGhlIGt1bm9pY2hpIDItMQ%3D%3D

**Comment by madewokherd** [comment]
Wild guess, this might be a similar issue to what I encountered with Cloudberry Kingdom: https://github.com/ValveSoftware/Proton/issues/1360#issuecomment-899808822

**Comment by waspennator** [comment]
> Wild guess, this might be a similar issue to what I encountered with Cloudberry Kingdom: [#1360 (comment)](https://github.com/ValveSoftware/Proton/issues/1360#issuecomment-899808822)

Weird, Protondb does says Cloudberry Kingdom should work with music as of the latest review with Experimental on deck, but I don't have the game to check and would need to find somewhere still selling keys since it's delisted.

Mostly confused why the music for Akane on the title and first few levels work fine, but not 2-1 onwards, if it's an audio conversion issue though.

**Comment by madewokherd** [comment]
Media is transcoded when enough people encounter it and upload it via the shader cache mechanism. So the earlier in the game (and, in Cloudberry Kingdom's case, the longer the game's been out), the more likely it is to have been transcoded.

**Comment by waspennator** [comment]
Oh yeah, checked the files and I'm assuming these are the files that need to be transcoded.

"Content/sound/music/boss.wma	wma	5.31 MiB
Content/sound/music/boss.xnb	xnb	122 B
Content/sound/music/ingame_1.wma	wma	1.46 MiB
Content/sound/music/ingame_1.xnb	xnb	126 B
Content/sound/music/ingame_2.wma	wma	4.60 MiB
Content/sound/music/ingame_2.xnb	xnb	126 B
Content/sound/music/ingame_3.wma	wma	5.83 MiB
Content/sound/music/ingame_3.xnb	xnb	126 B
Content/sound/music/ingame_4.wma	wma	4.62 MiB
Content/sound/music/ingame_4.xnb	xnb	126 B
Content/sound/music/ingame_5.wma	wma	5.01 MiB
Content/sound/music/ingame_5.xnb	xnb	126 B
Content/sound/music/Intro.wma	wma	3.78 MiB
Content/sound/music/Intro.xnb	xnb	123 B
Content/sound/music/level_end.wma	wma	354.39 KiB
Content/sound/music/level_end.xnb	xnb	127 B
Content/sound/music/start.wma	wma	4.21 MiB
Content/sound/music/start.xnb"

Dunno if there's an easier way to get em encoded though outside of playing through the game, considering its kinda difficult, barely anyone is playing this, and it erases your saves upon deletion.

**Comment by madewokherd** [comment]
Transcoding locally to .ogg files should work (the comment I linked has a script for that), though unfortunately that doesn't help anyone else playing.

**Comment by waspennator** [comment]
> Transcoding locally to .ogg files should work (the comment I linked has a script for that), though unfortunately that doesn't help anyone else playing.

Actually just hopped on my windows laptop, tried editing the sav file a bit and managed to create a save file with all the stages unlocked, so it should be easier to test and convert the wma files to work. Accidentally unlocked some achievements trying to set this up, but tbh I only bought this game to get it working on linux.

[data.zip](https://github.com/ValveSoftware/Proton/files/14391613/data.zip)

Update: Ran through the stages on Deck quickly, seems like Act 2, 3, 4, and 5 suffer from this issue. I quickly loaded up each level, dunno if there's anything more I need to do to get this cached.

**Comment by waspennator** [comment]
Strange, I dunno if it's it's cause I reverified game files or an update happened, but now none of the songs are working anymore, sound effects still play just fine.

[steam-291130.log.txt](https://github.com/user-attachments/files/16120852/steam-291130.log.txt)

**Comment by AJuujarvi** [comment]
> Strange, I dunno if it's it's cause I reverified game files or an update happened, but now none of the songs are working anymore, sound effects still play just fine.
> 
> [steam-291130.log.txt](https://github.com/user-attachments/files/16120852/steam-291130.log.txt)

@waspennator We are investigating this currently and working on a solution, but it is not trivial. It likely did happen due to reverifying the game files unfortunately. As a temporary solution to avoid this with other titles in the future, I  would recommend backing up the shader cache of the game. That way, if this happened again, you can restore the video playback with the older shader cache.

**Comment by waspennator** [comment]
Tried it out lately and the music is working properly again. Acts 2-1 to 2-3 are now finally playing music, but the remaining levels 3 to 5 are still silent, though i don't think I noticed the lag spikes during those levels anymore.

**Comment by waspennator** [comment]
Game seems to have gotten a patch moving from xna to fna and the audio works on all levels now, closing.
