### ISSUE TITLE
Trying to play Assassins Creed 2 on Steam

### ISSUE THREAD

**Issue by DrThomasXLight** [ValveSoftware/Proton#7507]
Hi,

I'm trying to play Assasins Creed II on my PC using Linux, but every time I launch the game, I receive this uplay window and I get stuck in it even when my credentials to ubisoft are correct.

How can I play this Game? I enjoy this game in PS4 and would like to play it again on STEAM now.

My System info:

# System Details Report
---

## Report details
- **Date generated:** 2024-02-17 19:28:08

## Hardware Information:
- **Hardware Model:** ASUS TUF GAMING B560M-PLUS WIFI
- **Memory:** 16.0 GiB
- **Processor:** Intel® Core™ i5-10400F × 12
- **Graphics:** NVIDIA GeForce GTX 1650
- **Disk Capacity:** 1.2 TB

## Software Information:
- **Firmware Version:** 0811
- **OS Name:** openSUSE Tumbleweed
- **OS Build:** (null)
- **OS Type:** 64-bit
- **GNOME Version:** 45.3
- **Windowing System:** X11
- **Kernel Version:** Linux 6.7.4-1-default
- 
![Screenshot from 2024-02-17 19-20-24](https://github.com/ValveSoftware/Proton/assets/56457861/97c5aa10-8c3b-4b9f-98b9-6289e8b99be3)
![Screenshot from 2024-02-17 19-20-24](https://github.com/ValveSoftware/Proton/assets/56457861/5e25ffa0-f621-4e57-8de0-91a8a393f027)

**Comment by kisak-valve** [comment]
Hello @DrThomasXLight, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/190#issuecomment-1952502111.
