### ISSUE TITLE
Microsoft Flightsimulator 2020 works but cannot interface with external devices

### ISSUE THREAD

**Issue by VeitHW13** [ValveSoftware/Proton#7509]
# Compatibility Report
- Name of the game with compatibility issues: Microsoft Flightsimulator 2020
- Steam AppID of the game:

## System Information
- GPU: NVIDIA GA106 [GeForce RTX 3060 Lite Hash Rate]
- Video driver version: nvidia-driver-535
- Kernel version:  5.15.0-94-generic x86_64 bits, Linux Mint Vera
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 
So far I managed to get the flightsimulator msfs2020 working, but I cannot connect it to my external navigation aids on a tablet. The msfs2020 seems to come with an API called "simconnect", which can be called from other programs to query e.g. the actual GPS coordinates or send commands from homecockpit devices. To link external devices there are many tools around like 'fs2020nmea.exe' or 'fsconny.exe' that can talk to the simulator and bridge over to the outside world. While all this seems to be working smoothly in a windows environment, it does not on linux. Whenever I launch these tools (also in steam with Proton experimental) I get messages like 'can't connect to sim'. This is surprising, because the SDK does work, and because the communication is TCP/IP-based there should not be any problem. So, how can I link my devices to msfs2020 on steam in linux - or is there a fundamental reason why this is impossible?
[SystemReport_PC_Veit.txt](https://github.com/ValveSoftware/Proton/files/14341826/SystemReport_PC_Veit.txt)

## Reproduction
Launch msfs2020 in steam with proton experimental (I normally have to do that twice, because first attempt just stops.) The launch either 'fs2020nmea.exe' or 'fsconny.exe' also in steam. fs2020nmea will launch in a terminal window and you see the sconds counting down, as it attempts to reach msfs. fsconny will show an error 'can't connect to sim'.

**Comment by kisak-valve** [comment]
Hello @VeitHW13, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-1954237877.
