### ISSUE TITLE
Omori - Graphical issues on Proton 8 and Experimental but is fine on Proton 7

### ISSUE THREAD

**Issue by Tetreos** [ValveSoftware/Proton#7510]
# Compatibility Report
- Name of the game with compatibility issues: OMORI
- Steam AppID of the game: 1150690

## System Information
- Steam Deck OLED (Current stable update channel 3.5.7)
- Proton version: 8 and experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Log: [steam-1150690.log](https://github.com/ValveSoftware/Proton/files/14342793/steam-1150690.log)

## Symptoms
When using Proton 8 or Experimental the game does not render a lot of the graphics and fonts correctly, a lot of dark scenes are barely visible on screen even with max brightness because of that and the text is hard to read.
To someone who has never played the game before it would be hard to tell that this is not the intended experience assuming they use the latest stable release of Proton.

## Reproduction
How to easily reproduce it is to check the 'load save' screen. Upon selecting a save from the main menu there is supposed to be an animated background which is visible on Proton 7 but turn completely black on a newer Proton version. Otherwise it's easy to see by looking at item descriptions, the font is hard to read as some letters are not even shown. A lot of other graphics are darker and less detailed. To see the very dark scene that is barely visible on screen you have to reach the point in the prologue where you wake up after Basil disappeared.

**Comment by kisak-valve** [comment]
Hello @Tetreos, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4578#issuecomment-1954253236.
