### ISSUE TITLE
Helldivers 2 crashes on launch

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7511]
# Compatibility Report
- Helldivers 2
- 553850

## System Information
- GPU: NVIDIA GeForce GTX 1050 Ti
- Video driver version: Nvidia 535.43.20
- Kernel version: 6.7.4-artix1-1
- Link to full system information report: [System Info](https://gist.github.com/veryrobust/cc366dd6111e3ee68de14461c0eb338b) and [Runtime Info](https://gist.github.com/veryrobust/352f52006abd9036a21b7ff1ffc7b0aa)
- Proton version: Experimental (the issue appears with other version too)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
The Helldivers 2 window is always black and I can't interact with it. It always does that as soon as I attempt to launch the game and I get past the nProtect GameGuard check.

## Reproduction
The issue occurred after playing the game without any problems a few times. I reinstalled the game in attempt to fix it, but then the issue reoccurred after playing for a couple of times just like last time.

[steam-553850.log](https://github.com/ValveSoftware/Proton/files/14345632/steam-553850.log)

**Comment by kisak-valve** [comment]
Hello @veryrobust, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7486#issuecomment-1954348437.
