### ISSUE TITLE
Insurgency Sandstorm (581320)

### ISSUE THREAD

**Issue by Tune45** [ValveSoftware/Proton#7517]
Compatibility Report
- Insurgency Sandstorm
- Steam AppID of the game: 581320 

## System Information
- GPU: AMD RX 580 8gb
- Video driver version: Mesa 24.0.1-arch1.1
- Kernel version:  6.7.5-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:Proton Experimental

## I confirm:
- [ x ]. first Insugengency didnt pass anticheats but do install glibc-eac ,now game can run
- [x] that I have checked whether there are [updates]([url](url)) for my system available.

## Symptoms 
issue with alphabet  keyboard controls .etc when i would to move fordword i need to press W.but in game these key are unreponsive .and i must press Alt+ W to move forword .maybe Locale or keyboard layout conflict relate idk. My locale is Thai and i have  EN-US for default layout and TH,RU and DE(german) on KDE settings (screenshot attached)

i tried to disable all layout and switched to EN_US .issue still persist
[steam-581320.tar.gz](https://github.com/ValveSoftware/Proton/files/14382266/steam-581320.tar.gz)
![Screenshot_20240222_190048](https://github.com/ValveSoftware/Proton/assets/138557979/bd697ff7-a754-455e-b04c-db43b087fc58)

**Comment by kisak-valve** [comment]
Hello @Tune45, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1651#issuecomment-1961382875.
