### ISSUE TITLE
MSFS addons 

### ISSUE THREAD

**Issue by linuslulatsch** [ValveSoftware/Proton#7519]
-- Steam support send me this server to get help --
# Compatibility Report
- Microsoft Flight Simulator 2020
- 1250410

## System Information
- 4x NVEDIA 1080 TI 
- X11 Window Manager
- Kernel version: 64-bit x86	6.5 (HWE)
- Linux Ubuntu 22.04.4 LTS
- Proton version: 8.0
- Graphic: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] / NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] / NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] / NVIDIA Corporation GP102 [GeForce GTX 1080 Ti]

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

I have trouble using addons on my Linux system. I downloaded Microsoft Flight Simulator via Steam and ran it via Proton 8.x. Since everything worked out I wanted to use addons like Volanta and the Fly-By-Wire Installer. I already contacted MS support but they told me that Linux weren't supported. On install both the installer and Volanta show that there is no Simulator running. I tried with the help of FAQs and the Discord of these programms but no help there. MSFS is installed in /home/user/.local/share/Steam/steamapps/compatdata/1250410/pfx/drive_c/users/steamuser/Appdata/"Microsoft Flight Simulator". When trying to install addons i used a WINEPREFIX with the path to "1250410/pfx". In the installer I now could see the game files but the next error was that the UserCfg.opt wasn't installed. I checked and the file was there. Im now stuck and don't know what to do. Any suggestions would be highly appreciated :)

**Comment by kisak-valve** [comment]
Hello @linuslulatsch, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-1962436606.
