### ISSUE TITLE
TEKKEN 8 Black Screen

### ISSUE THREAD

**Issue by AtomsForHire** [ValveSoftware/Proton#7522]
# Compatibility Report
- Name of the game with compatibility issues: TEKKEN 8
- Steam AppID of the game: 1778820

## System Information
- GPU: AMD ATI Radeon RX 6600M
- Video driver version: Mesa 23.3.5
- Kernel version: 6.7.5
- Link to full system information report as [Gist](https://gist.github.com/): [Gist](https://gist.github.com/AtomsForHire/9d12c9082446c9df94ad714a308feb78)
- Proton version: Hotfix
- OS: Nobara 39

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1778820.log](https://github.com/ValveSoftware/Proton/files/14396984/steam-1778820.log)

## Symptoms 
Unable to launch into main menu, but can view the splash screen and intro cinematic with sound. During the splash screens, everything feels fine but when trying to load the main menu screen GPU usage drops to 0. Can't even see Kazuya's face, just a black screen and the whole system feels choppy. Tried on both KDE X11 and Hyprland.

## Reproduction
1. Launch game with proton hotfix

**Comment by kisak-valve** [comment]
Hello @AtomsForHire, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7444#issuecomment-1963005104.

**Comment by CharlExMachina** [comment]
Having an issue with this game.

I have a Ryzen 9 7950X and a Radeon RX 7900 XTX. The game won't get past the opening cinematic. Once I skip the cinematic, instead of showing the game menu, the entire system will lag severely, making the interaction with any UI element incredibly slow. After I close the game from Steam, the PC's performance returns back to normal
