### ISSUE TITLE
deus ex the fall screenshots steamplay proton 7.0-6 

### ISSUE THREAD

**Issue by weron3** [ValveSoftware/Proton#7525]
deus ex the fall screenshots steamplay proton 7.0-6 

Computer Information:
Manufacturer: MSI
Model: B85M-E45 (MS-7817)
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Pentium(R) CPU G3420 @ 3.20GHz
CPU Family: 0x6
CPU Model: 0x3c
CPU Stepping: 0x3
CPU Type: 0x0
Speed: 3200 MHz
2 logical processors
2 physical processors
Hyper-threading: Unsupported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Unsupported
AVX: Unsupported
AVX2: Unsupported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Ubuntu 22.04.4 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 6.5.0-21-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12201001
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20231127.68515
Video Card:
Driver: Intel Mesa Intel(R) HD Graphics (HSW GT1)
Driver Version: 4.6 (Compatibility Profile) Mesa 24.0.1 - kisak-mesa PPA
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID: 0x8086
DeviceID: 0x402
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1024 x 768
Desktop Resolution: 1024 x 768
Primary Display Size: 10.67" x 7.99" (13.31" diag), 27.1cm x 20.3cm (33.8cm diag)
Primary VRAM Not Detected
Sound card:
Audio device: Intel Haswell HDMI
Memory:
RAM: 3769 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: fi_FI.UTF-8
Total Hard Disk Space Available: 937289 MB
Largest Free Hard Disk Block: 755021 MB
Storage:
Number of SSDs: 2
SSD sizes: 1000G,0B
Number of HDDs: 0
Number of removable drives: 0

![Kuvakaappaus - 2024-02-26 04-34-13](https://github.com/ValveSoftware/Proton/assets/161266754/d8bf2154-4f58-4979-b86b-2e11547f2c3c)
![Kuvakaappaus - 2024-02-26 04-34-15](https://github.com/ValveSoftware/Proton/assets/161266754/44532446-9563-4ed8-a2b5-00eeaadc4df4)
![Kuvakaappaus - 2024-02-26 04-34-27](https://github.com/ValveSoftware/Proton/assets/161266754/379f6050-f308-4d61-9984-6987d08f6702)
![Kuvakaappaus - 2024-02-26 04-34-43](https://github.com/ValveSoftware/Proton/assets/161266754/61965238-5a87-4ffd-96d2-19f03d6b0a1f)

**Comment by kisak-valve** [comment]
Hello @weron3, the video drivers for the Haswell generation of Intel GPUs provide an incomplete implementation of Vulkan. Graphical artifacts and/or crashes are expected as a result of this, and in general that makes the GPU generation unsupportable by Proton. Report this to your video driver vendor.

Additionally, please search for existing compatibility reports for the game you're giving feedback on before opening any further issue reports. (Deus Ex: The Fall would be #590)
