### ISSUE TITLE
Make the "Force compatibility of all game with proton" more visible.

### ISSUE THREAD

**Issue by H0R1Z0N** [ValveSoftware/Proton#7532]
I am sadden with how much noobies who switch on Linux due to how bad Microsoft's turning have the noobies, are doing a double take because they don't know that this option exist in the setting because noobies assume the default setting's the best and they never check the setting tab on any of their device/software.

This option should be enable by default or be a splash screen on the first run of Steam so that user choice to enable it if they desired.

It leave a lot of newbie to continue to perpetuate the "There's no game on Linux" bs after 5 years of your great work on this project.

Reminder that with you, Valve, dropping Windows 7 support and with Microsoft dropping Windows 10 soon, hundreds of millions of computer will be e-wasted due to the lack of knowledge that Linux exist and that Linux on gaming's awesome, just like on the Steam Deck, which a lot of commoner don't know it run Linux by default.

Today's the day to make "The years of the Linux Desktop" a reality. We know you guys won't be able to test every game for  compatibility, it's going to be impossible, even if you work for it for 10+ years.

**Comment by kisak-valve** [comment]
Hello @H0R1Z0N, this is a request for the Steam client, not Proton itself.

That written, my understanding is that support for running games with Proton is unofficial and unofficial options can't be enabled by default.
