### ISSUE TITLE
UI cursor speed broken in Warframe after Proton Experimental update

### ISSUE THREAD

**Issue by atimeofday** [ValveSoftware/Proton#7533]
Game: Warframe

Proton versions (broken): 9.0 beta, 02/26/2024 Proton Experimental
Proton version (before breakage): 02/25/2024 Proton Experimental

Issue: UI cursor speed is badly crippled; the in-game UI cursor speed setting does nothing.

I have no idea how this could happen, or be caused by Proton, but:
- I first encountered this issue when I tried Proton 9.0 beta.
- The issue disappeared when I reverted to Proton Experimental.
- Proton Experimental then received a large update.
- The issue then appeared while using Proton Experimental.

Tertiary information: I am using a Logitech MX Ergo trackball mouse, with cursor speed and behavior adjusted by Solaar.

**Comment by kisak-valve** [comment]
Hello @atimeofday, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/167#issuecomment-1966613137.
