### ISSUE TITLE
Terminal instruction to install Ptoton

### ISSUE THREAD

**Issue by QPAPA** [ValveSoftware/Proton#7535]
Hello! pls post the instruction, terminal commands for noobs to install Proton without Steam on Ubuntu. 
Pls add Proton on Ubuntu software - its a win on wine!

**Comment by kisak-valve** [comment]
Hello @QPAPA, Proton is designed specifically to be run as a sub-component of Steam and is distributed by that platform. Usage outside of that is not supportable. Use upstream wine or a different derivative for your purposes.

Closing as won't fix.
