### ISSUE TITLE
Steam Play appears to be missing resolutions between 1080p and 2160p!

### ISSUE THREAD

**Issue by jarrard** [ValveSoftware/Proton#754]
Just thought I open this issue that on my 1080ti with 396.54 drivers and antergos, all my steam play tested games are missing 1440p and 1600p as resolution options (sometimes there are others like 1800p etc).

It seems steam play only allows 1920x1080 / 1920 x 1200 / 3840 x 2160   Nothing in between, so I can't down scale from 4k to 1440p for example.

If anyone knows a workaround to resolve this issue let me know, I do not believe I've had this problem with DXVK alone, only with proton!

**Comment by LiamDawe** [comment]
Looks like this is being patched in Valve's Wine fork: https://github.com/ValveSoftware/wine/commit/fce451cc6c064f58864139c9fd5fa95962d18b89

**Comment by DissCent** [comment]
Actually, my resolution is still missing (2560x1080, 21:9 aspect ratio) :-/

**Comment by aeikum** [comment]
@DissCent The native resolution is always presented as an option to the game. If the game doesn't show it as an option to select, then the game doesn't support rendering at that resolution and you'll have to choose one that it does support.

**Comment by jarrard** [comment]
if the resolution is available outside of proton testing (wine+dxvk) then it certainly is a proton related issue.

**Comment by DissCent** [comment]
Aah okay, I got it - sorry for the confusion!

**Comment by jarrard** [comment]
this problem has been resolved with recent beta patch of proton.
