### ISSUE TITLE
NVAPI / Nvidia Reflex for Apex Legends

### ISSUE THREAD

**Issue by MTGPROD** [ValveSoftware/Proton#7540]
# Feature Request

## I confirm:
- [ x ] that I haven't found another request for this feature.
- [ x ] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

The possibility of using Nvidia Reflex on Apex Legends !

**Comment by kisak-valve** [comment]
Hello @MTGPROD, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1973877504.
