### ISSUE TITLE
Proton 9.0 Experimental broke Epic Games Store

### ISSUE THREAD

**Issue by gechoto** [ValveSoftware/Proton#7547]

**Comment by kisak-valve** [comment]
Hello @blacktowel, `wine: Call from 00006FFFFFC1CE87 to unimplemented function cfgmgr32.dll.CM_Get_Device_Interface_PropertyW, aborting` looks like the line of interest from your Proton log.

**Comment by SingleInfiniteLoop** [comment]
There's nothing you can do, I'm afraid. Proton 9.0 is missing following upstream change:
https://github.com/wine-mirror/wine/commit/91d60983acad0e8791b94f60dad5d318b67c0166

**Comment by alasky17** [comment]
@blacktowel @SingleInfiniteLoop Thank you for the report! I cherry-picked this commit to 9.0-experimental, and it should be in experimental-bleeding-edge soon.  I only tested the window opening, so please let me know if there is still regressive behavior further in.

**Comment by LiamDawe** [comment]
Just a note, this issue has begun happening again. You can install the Epic Games Store with any recent Proton version, but then trying to open it results in the Epic Store getting stuck in an update loop.

Tested across Proton 9, 10, Experimental and Experimental bleeding-edge Beta.

Proton log file: 

[steam-11109633888454967296.tar.gz](https://github.com/user-attachments/files/20997857/steam-11109633888454967296.tar.gz)

**Comment by LiamDawe** [comment]
Confirming fixed on bleeding-edge Beta.
