### ISSUE TITLE
Mouse movement is "filtered" since experimental update on all games

### ISSUE THREAD

**Issue by Nama** [ValveSoftware/Proton#7549]
# Compatibility Report
- Name of the game with compatibility issues: Overwatch and Helldivers 2. This might be game unrelated
- Steam AppID of the game: 2357570, 553850

## System Information
- GPU: RX 7900 XT
- Video driver version: 24.1.0_devel.184400.62fa5c8d0f0-1
- Kernel version: 6.7.7-AMD-znver3
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Proton Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Mouse movement is heavily filtered ingame. Menus aren't influenced.
You can see in the video, that the slightly diagonal movement is 100% horizontal outside of the menu. Small/slow movement don't get registered at all.

https://github.com/ValveSoftware/Proton/assets/2297270/8f6033f5-f71e-4be6-88c9-d33a67e42ddf

## Reproduction
Use Proton Experimental with any game which uses the mouse outside of menus.

**Comment by alasky17** [comment]
@Nama Is this new behavior?  Have you tried Proton 8.0-5 and/or experimental-8.0 (which is still present as a branch on experimental).

**Comment by Nama** [comment]
Yes, this is new behavior with the 9.0 update. This issue doesn't exist on 8.0 (~~and hotfix, yet~~ hotfix got updated for apex, same problem there now, too).

**Comment by alasky17** [comment]
@Nama I tried Helldivers 2 and was unable to reproduce what you are reporting. Could you try experimental-bleeing-edge (since there have been some rawinput cursor fixes there already)? If you are still seeing the issue, could you:
- Please copy your system information from Steam (Steam -> Help -> System Information and Steam -> Help -> Steam Runtime Diagnostics) and put each in a [gist](https://gist.github.com/), then include a link to the gists in this issue report.  
- Please get a log with PROTON_LOG=+x11drv,+x11settings,+event,+cursor,+win,+message,+rawinput %command%

**Comment by Nama** [comment]
Thank you for looking into this.

[System Information](https://gist.github.com/Nama/b2e727d70754817029867e647bef56bf)
[Runtime Diagnostic](https://gist.github.com/Nama/668700fbb24db54804c453cd3f582087)
[ow.tgz](https://github.com/ValveSoftware/Proton/files/14641089/ow.tgz)

The log is from Overwatch. On bleeding edge, the mouse moves in the menus, but there are no hover effects and I can't click anything.
Ingame, its the same as with 9.0.
On Helldivers 2 it didn't change. Mouse works in menus and ingame still very "filtered".

**Comment by gregorywaynepower** [comment]
> @Nama I tried Helldivers 2 and was unable to reproduce what you are reporting. Could you try experimental-bleeing-edge (since there have been some rawinput cursor fixes there already)? If you are still seeing the issue, could you:
> 
> * Please copy your system information from Steam (Steam -> Help -> System Information and Steam -> Help -> Steam Runtime Diagnostics) and put each in a [gist](https://gist.github.com/), then include a link to the gists in this issue report.
> * Please get a log with PROTON_LOG=+x11drv,+x11settings,+event,+cursor,+win,+message,+rawinput %command%

Just wondering, I'm having issues on my side of the fence with this particular issue. . Could I send some logs your way?

**Comment by alasky17** [comment]
@gregorywaynepower That would be great.  I have a few questions, since this kind of issue is much harder to solve if I'm not able to reproduce locally.  
1) Could you also attach your system information from Steam? 
2) What type of mouse are you using? 
3) Are you using any other "special peripherals" or other programs/settings that might be related to cursor input?

**Comment by Nama** [comment]
2. I'm using a Razer Mamber Hyperflux (comb with Firefly Hyperflux). This worked always out of the box and is recognized as a normal mouse. I'll try later with another mouse.
3. I had [libinput-config](https://gitlab.com/warningnonpotablewater/libinput-config), which I removed yesterday (totally forgot about that, could be the reason)  
Also [sway-input-config](https://github.com/Sunderland93/sway-input-config), which just generates a sway config. I use hyprland now.

I'll update this post soon.

**Update**
The issue is gone, on 9.0 and experimental. Since nobody except @gregorywaynepower had this issue, I assume, that `libinput-config` caused this. (Even tho, until proton 8, there wasn't this issue.)

I'm really sorry for wasting your time @alasky17 and appreciate your help.

In case @gregorywaynepower still has the issue, I keep it open?

**Comment by gregorywaynepower** [comment]
> @gregorywaynepower That would be great. I have a few questions, since this kind of issue is much harder to solve if I'm not able to reproduce locally.
> 
> 1. Could you also attach your system information from Steam?
> 2. What type of mouse are you using?
> 3. Are you using any other "special peripherals" or other programs/settings that might be related to cursor input?

<details><summary>1. Here's the specs:</summary>

OS: Pop!_OS 22.04 LTS
KERNEL: 6.4.6-76060406-generic
CPU: Intel Core i9-10900K @ 3.70GHz
GPU: NVIDIA GeForce RTX 2080 Super
GPU DRIVER: NVIDIA 535.86.05
RAM: 32 GB

Computer Information:
Manufacturer: System76
Model: Bonobo WS
No Touch Input Detected (Even though the Bonobo 14 does have touchpad.)
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
CPU Family: 0x6
CPU Model: 0xa5
CPU Stepping: 0x5
CPU Type: 0x0
Speed: 5300 MHz
20 logical processors
10 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Pop!_OS 22.04 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 6.4.6-76060406-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12101004
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20230606.51628
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce RTX 2080 Super/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 535.86.05
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x10de
DeviceID: 0x1ed3
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 3840 x 2160
Desktop Resolution: 3840 x 2160
Primary Display Size: 15.00" x 8.43" (17.17" diag), 38.1cm x 21.4cm (43.6cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 8192 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: Realtek ALC1220
Memory:
RAM: 32029 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 929227 MB
Largest Free Hard Disk Block: 122395 MB
Storage:
Number of SSDs: 1
SSD sizes: 1000G
Number of HDDs: 0
Number of removable drives: 

</details>

2. Logitech G502 HERO High Performance Wired Gaming Mouse, HERO 25K Sensor, 25,600 DPI, RGB, Adjustable Weights, 11 Programmable Buttons, On-Board Memory, PC / Mac
3. As far as I know, no. I did remove [System76's Mouse Configurator](https://github.com/pop-os/mouse-configurator) and still had this issue.

@Nama I'll double check to see if this issue still persists with the newer version of Proton.

Edit: Yeah, unfortunately with even with Proton 9.0 (Beta) and Proton (Experimental) my cursor is still not recognized.

**Comment by Nama** [comment]
> my cursor is still not recognized.

Wait, that sounds like an entire different issue.
The mouse movement was weird (shown on the video I posted), but the mouse still worked ingame.

**Comment by gregorywaynepower** [comment]
> > my cursor is still not recognized.
> 
> 
> 
> Wait, that sounds like an entire different issue.
> 
> The mouse movement was weird (shown on the video I posted), but the mouse still worked ingame.

Yeah, I could move my mouse to move the camera around but I couldn't left click, right click, or interact with menus.

**Comment by Nama** [comment]
Ya, you should open another issue.

**Comment by alasky17** [comment]
@Nama Thank you for updating this bug! I'm glad that the problem is fixed, and I appreciate the update so I didn't continue to look into it :) 

@gregorywaynepower If you opened another issue, I wasn't able to find it.  Feel free to @ me on the new issue, although I can't promise that I can fix it.

**Comment by gregorywaynepower** [comment]
I’m all right! This was an issue with my NVIDIA driver on my OS and was
unrelated to Proton.
