### ISSUE TITLE
Street Fighter 6 Screen Flickering on Borderless Windowed mode after the game's latest update

### ISSUE THREAD

**Issue by Kronos328** [ValveSoftware/Proton#7551]
# Compatibility Report
- Name of the game with compatibility issues: Street Fighter 6
- Steam AppID of the game: 1364780

## System Information
- GPU: AMD RX 6600
- Video driver version: Mesa 24.0.2
- Kernel version: 6.7.8-arch1-1
- Link to full system information report as Gist: https://gist.github.com/Kronos328/e830a1ee632b2256fa2c1e80e56956f3
- Proton version: 8.0.5 (But happens with 9.x and 7.x versions too)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Here are the proton logs of one short application run:
[steam-1364780.tar.gz](https://github.com/ValveSoftware/Proton/files/14500845/steam-1364780.tar.gz)

## Symptoms 
After the game's latest update a couple of days ago, whenever I try to put the game on Borderless Windowed mode, the screen flickers uncontrollably.

This behavior can be seen in the following video:

https://github.com/ValveSoftware/Proton/assets/37886706/892cea0e-2420-4743-ae8f-5e04afeb6036

I have two monitors, and this behavior happens equally if both monitors are running and if only one monitor is running.

## Reproduction
Sadly I have no idea how one could reproduce this bug. It may as well be a configuration issue on my end, any help is appreciated.

Strangely, I also have a laptop where I play SF6, It doesn't have a graphics card, but the processor is AMD too, and it still plays the game perfectly without flickering, even in borderless fullscreen. The distro, Kernel, Mesa Driver and Proton versions are the same, too.

Thank you very much in advance for any help.

**Comment by kisak-valve** [comment]
Hello @Kronos328, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6817#issuecomment-1979588618.
