### ISSUE TITLE
add Arm64 Linux support

### ISSUE THREAD

**Issue by Spidy123222** [ValveSoftware/Proton#7553]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Currently it is difficult to run proton easily with arm64 devices as you need to setup sub system of Linux for a program like fex-emu to use. I am suggesting to add fex-emu (supports both 32bit and 64bit) or box86/64

## Justification [optional] 
Proton has multiple libraries from what I understand like DXVK and wine to run programs easily on Linux devices that are for windows. Adding fex-emu to proton could allow easy access for arm devices and possibly even risc-v devices to use proton in a simple matter. This could also allow vr devices or handhelds utilize arm for the handhelds. The market is getting arm desktops and some are already here like with Apple silicon devices running asahi Linux.

Snapdragon devices have mesa drivers with vulkan support from what it seems and for Apple silicon has recent OpenGL 4.6 soon to be vulkan. The fex-emu dev uses a nvidia Orin with a AMD Radeon pro W7500 for example and is able to run monster hunter world: iceborne under their translation layer. https://youtu.be/0ZVC2Q_91FY?si=mNKysK2uALiIYbOa

Also to note there has been showcase of people running portal on asahi Linux for apple silicon using fex-emu on mastodon.

I also feel like adding it to proton can help the project.
## Risks [optional]

There shouldn't be any risk for existing devices not on arm64. But for user experience using this could be that some games might not work that x86_64 system can like with wine as the translation layer would need development and some anti-cheat *might* not like it currently. If using FEX-emu (needs 4kb pages currently unlike box64/qemu-userspace), There is the issue on some arm devices by default either needing 16kb pages for the mmu or the kernel of Linux for arm64 could be using a higher page size then 4kb. Newer raspberry pi5 kernel could default to 16kb pages some day for example or asahi requiring 16kb pages for the SOC's  MMU.

## References [optional] 

Some related issues could be the steamplay macOS issue https://github.com/ValveSoftware/Proton/issues/1344 and can be an alternative for those users. 

Thanks for hearing me out on this feature request. Hopefully this will benefit proton if it's ever added.

**Comment by kisak-valve** [comment]
Hello @Spidy123222, the previous evaluation of this request at https://github.com/ValveSoftware/Proton/issues/1493#issuecomment-422022116 is still relevant.

Closing as a duplicate.

**Comment by Spidy123222** [comment]
Ah sorry. GitHub isn’t showing the issue still some reason even looking in closed issues. Sorry about duplicate.

**Comment by N0rdmann** [comment]
Mhmm can't be the only one wondering how a **now 6 year old** decision can still be mentioned as a "relevant" reason to simply close such a request without any further consideration?? 🤔

Valve should know better than anyone else how outdated a half decade old decision in this market is... 🫠
Even Apple _(which are not famous at all for **any** gaming dev topics)_ picked up on this showing impressive results with their Game Porting Toolkit on silicon devices

Be it FEX/BOX or even Rosetta, the "translation layer" work is already quite impressive 😎

**Comment by SheMelody** [comment]
> Mhmm can't be the only one wondering how a **now 6 year old** decision can still be mentioned as a "relevant" reason to simply close such a request without any further consideration?? 🤔
> 
> Valve should know better than anyone else how outdated a half decade old decision in this market is... 🫠 Even Apple _(which are not famous at all for **any** gaming dev topics)_ picked up on this showing impressive results with their Game Porting Toolkit on silicon devices
> 
> Be it FEX/BOX or even Rosetta, the "translation layer" work is already quite impressive 😎

I'll try to add further consideration to this, although I don't work for Valve.

There's currently no big interest in ARM from developers of the opensource projects and layers Valve uses in Proton, which means it would be counterproductive and probably a waste of time to try developing a native Proton on ARM.

In order to convince other developers to develop these layers and projects specifically for ARM, natively, and add official ARM support and maintenance would require either funding or else there must be way more people interested in it so that it's at least worth the time and effort.

**Comment by teohhanhui** [comment]
> There's currently no big interest in ARM from developers of the opensource projects and layers Valve uses in Proton

There is quite a fair bit of development going on in Wine at least:
https://source.winehq.org/git/wine.git/?a=search&h=HEAD&st=commit&s=+ARM64

**Comment by SheMelody** [comment]
> > There's currently no big interest in ARM from developers of the opensource projects and layers Valve uses in Proton
> 
> There is quite a fair bit of development going on in Wine at least: https://source.winehq.org/git/wine.git/?a=search&h=HEAD&st=commit&s=+ARM64

Yes, there is, and it's going to raise gradually. There will be enough interest, it's just not there at the moment.

**Comment by devaba** [comment]
I'm interested, there is a flood of interest now due to M$ behaviour on windows.

In fact, more than just gaming, replace Windows enirely for everything, the world is the oyster. 😀

**Comment by Madad1996** [comment]
getting more intresting nowadays.  
with CPUs like the CIX CD8180 which support dGPU's.
Many non tripple-A titles run ok, some are running great when using Fex-Emu and Steam.

**Comment by udance4ever** [comment]
Doesn't the [new announcement for Arm support on their new VR headset](https://www.pcgamer.com/hardware/vr-hardware/steamos-launching-for-arm-fex-translation-layer/) change up the game just a tad?  My limited understanding is they are leveraging FEX which is the same translation layer the folks at Asahi Linux have been excited about in regards to [AAA gaming on Apple Silicon](https://asahilinux.org/2024/10/aaa-gaming-on-asahi-linux/) for quite awhile (about a year now) & the Fedora Project just updated their [Running x86/x86-64 applications on Fedora Asahi Remix](https://docs.fedoraproject.org/en-US/fedora-asahi-remix/x86-support/) page 3 days ago so the couldron is getting mighty tasty if you ask me! :)

**Comment by Madad1996** [comment]
> Doesn't the [new announcement for Arm support on their new VR headset](https://www.pcgamer.com/hardware/vr-hardware/steamos-launching-for-arm-fex-translation-layer/) change up the game just a tad? My limited understanding is they are leveraging FEX which is the same translation layer the folks at Asahi Linux have been excited about in regards to [AAA gaming on Apple Silicon](https://asahilinux.org/2024/10/aaa-gaming-on-asahi-linux/) for quite awhile (about a year now) & the Fedora Project just updated their [Running x86/x86-64 applications on Fedora Asahi Remix](https://docs.fedoraproject.org/en-US/fedora-asahi-remix/x86-support/) page 3 days ago so the couldron is getting mighty tasty if you ask me! :)


Just take a look at their bleeding-edge branch.
Fex is already added to proton.
https://github.com/ValveSoftware/Proton/tree/bleeding-edge
