### ISSUE TITLE
Evil Genius 2: World Domination (700600)

### ISSUE THREAD

**Issue by genestrashcan** [ValveSoftware/Proton#7557]
# Compatibility Report
- Name of the game with compatibility issues: Evil Genius 2: World Domination
- Steam AppID of the game: 700600

## System Information
https://gist.github.com/genestrashcan/c707ffccbc471e90293401224259ccce

using Proton 9 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-700600.log](https://github.com/ValveSoftware/Proton/files/14516070/steam-700600.log)

## Symptoms 

Upon entering build mode in game, the audio randomly starts lagging and gets very choppy. Upon confirming a build. it returns to normal. I have attached a YouTube video showing the issue happening.

https://www.youtube.com/watch?v=r29uS3-VXB8

## Reproduction

1. Launch the game
2. start building a base in sandbox mode
3. enter build mode
4. start placing things and building your base
5. wait for the audio to start lagging.

**Comment by kisak-valve** [comment]
Hello @genestrashcan, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4708#issuecomment-1981916387.
