### ISSUE TITLE
Nvidia VRAM reported as half of real value on an Optimus setup

### ISSUE THREAD

**Issue by b14ckw1d0w** [ValveSoftware/Proton#7558]
Hi, I am trying to run multiple games (GTA IV + Universe Sandbox) on Arch with a Haswell processor and a Nvidia GTX 770M.

Due to Haswell Vulkan support not being available I am running "PROTON_USE_WINED3D=1 primusrun %command%" for the custom command.

Both load fine but report that I only have 1.5GB VRAM when I have 3GB as reported by nvidia-smi.

I have seen posts regarding Vulkan doing similar things and being able to report my VRAM size in a configuration file manually, is this something I can do with D3D? I have tried many versions of Proton on Universe Sandbox, but have left GTA IV using Proton Hotfix which was default upon installation.

I know my hardware is extremely old but about 6 months ago I had GTA running perfectly while utilizing the whole 3GB of VRAM.

Does anyone have any greatly appreciated help for me?

**Comment by kisak-valve** [comment]
Hello @b14ckw1d0w, the `PROTON_USE_WINED3D=1` runtime option is not considered supported. Any issues you have with it needs to be reproduced with a vanilla install of wine, then reported and resolved in upstream wine.

Also, Proton 8.0 and newer requires that the video driver provide Vulkan 1.3 for support. Sorry, but your hardware is not supportable going forward.
