### ISSUE TITLE
NFS Unbound Low FPS with VOL6 Update

### ISSUE THREAD

**Issue by CosmicFusion** [ValveSoftware/Proton#7561]
# Compatibility Report
- Name of the game with compatibility issues: Need for Speed Unbound
- Steam AppID of the game: 1846380

## System Information
- GPU: RTX 4060 (same muxed to dgpu or using prime via intel iris xe)
- Video driver version: tried 545.29.06 (what originally worked), 550.40.07, 550.54.14
- Kernel version: tried 6.6.6 and 6.8 rc4
- Link to full system information report as [System Info](https://gist.github.com/CosmicFusion/0d9c1c245855556ec9af6de037e0cb9c) [Runtime Info](https://gist.github.com/CosmicFusion/2770bde72c4351c940f76053aa2174f3)
- Proton version: tried ge-8-21 (what originally worked), proton 8.0.1, and latest proton experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
* Low fps and bad frame times across the entire game
* Even the intro video runs at bearly 20fps
* The menu before loading any game resources is laggy runs at 20fps
* both CPU and GPU usage is below 10%
* Works fine in windows
* Used to work fine in linux before vol 6
* RDR2, and CS2 are fine on linux too
* Being on Ultra or low makes no difference

## Reproduction
* Use linux
* Play NFS Unbound

## Logs and Screenshots
[log](https://gist.github.com/CosmicFusion/9f64c5df00942692dc800e308d2ce0d1)

**Comment by kisak-valve** [comment]
Hello @CosmicFusion, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6502#issuecomment-1985717193.
