### ISSUE TITLE
 Remnant II (1282100) - Epic Social Overlay not working (prevents adding friends for crossplay)

### ISSUE THREAD

**Issue by dspec12** [ValveSoftware/Proton#7563]
# Compatibility Report
- Name of the game with compatibility issues: Remnant II
- Steam AppID of the game: 1282100

## System Information
- GPU: AMD Radeon RX 7900 XTX
- Video driver version: MESA 1:24.0.2
- Kernel version: 6.7.9-2-cachyos
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/dspec12/ed107b444bfbb03d6b2b7dc49b67a246
- Proton version: proton experimental, 8, 9 

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
The in-game keybind to bring up the Epic Social overlay does not work. This feature is needed to add console friends for crossplay.

Some research indicated that EpicGamesLauncher.exe needs to update.

[steam-1282100.zip](https://github.com/ValveSoftware/Proton/files/14541847/steam-1282100.zip)

## Reproduction
From the character selection screen pressing the key command to bring up the Epic Social Overlay. Shift + F3.

**Comment by kisak-valve** [comment]
Hello @dspec12, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6949#issuecomment-1986255498.
