### ISSUE TITLE
supreme commander 2 fails silently with proton experimental

### ISSUE THREAD

**Issue by hfs2** [ValveSoftware/Proton#7565]
# Compatibility Report
- Name of the game with compatibility issues: Supreme Commander 2
- Steam AppID of the game: 40100

## System Information
- GPU: RX 6600XT
- Video driver version: Mesa 23.3.6
- Kernel version: 6.7.7
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/hfs2/e8bb75edd4883a34f9847d2b9202e478
- Proton version: experimental

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

proton log: https://gist.github.com/hfs2/7529caedf335d441387963fdc453efb8

proton log with proton 9.0beta - runs OK - for reference:
https://gist.github.com/hfs2/000fde527e523210c6cb1671290319c2

## Symptoms
Game fails silently - never displays a window. The green Play button in the steam client flickers to blue Stop briefly (0.2 seconds?) then returns to green / Play. Command line output doesn't give _me_ any clues.
https://gist.github.com/hfs2/75ed1d388b01e951238725dd7ddd6532

## Reproduction
In the Steam client, go to properties for Supreme Commander 2
Force the use of Proton Experimental

The same game ran fine with the same settings on 2024-03-05 and maybe 03-06

**Comment by hfs2** [comment]
30 minutes after I posted this, the Supreme Commander 2 game itself somehow got an update via Steam. Now it seems to run fine with proton experimental. So this issue can be deleted or closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by hfs2** [comment]
Now I think all this was caused by confusion on my part regarding the Steam client global settings and game-level over-rides. Probably nothing to do with Proton. Closing. (er - I would have closed but kisak got there before me.)
