### ISSUE TITLE
Flashpoint Campaigns: Southern Storm

### ISSUE THREAD

**Issue by sith-on-mars** [ValveSoftware/Proton#7572]
# Compatibility Report
- Name of the game with compatibility issues: Flashpoint Campaigns: Southern Storm
- Steam AppID of the game: 22579106

Sorry that I don't own the game. A number of people reported on [ProtonDB](https://www.protondb.com/app/2366530) that they were able to boot into the game, but unable to click any button on the menu regardless of the version of Proton.

**Comment by kisak-valve** [comment]
Hello @sith-on-mars, as a proxy report, there's nothing of value to ponder here.

Someone who has the game can report their findings with details and logs for a Proton developer to take a look at.
