### ISSUE TITLE
Overwatch 2 2357570

### ISSUE THREAD

**Issue by Redhawk18** [ValveSoftware/Proton#7576]
# Compatibility Report
- Name of the game with compatibility issues: Overwatch 2
- Steam AppID of the game: 2357570

## System Information
https://gist.github.com/Redhawk18/bea6a899e6f101597e368fbd54947ae9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Either System freezes or application crashes in game. It seems to happen once every thirty minutes. 

## Reproduction
This log is 1GB, This was the only way I could upload it
[steam-2357570.7z.log](https://github.com/ValveSoftware/Proton/files/14596305/steam-2357570.7z.log)

**Comment by pollux78** [comment]
https://github.com/ValveSoftware/Proton/issues/7033 you can add this log to the already opened issue

**Comment by kisak-valve** [comment]
Hello @Redhawk18, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7033#issuecomment-1997408516.
