### ISSUE TITLE
Star Wars Battlefront 2 - 2005 (6060)

### ISSUE THREAD

**Issue by AQDuck97** [ValveSoftware/Proton#7577]
# Compatibility Report
- Name of the game with compatibility issues: Star Wars Battlefront 2 (classic, 2005)
- Steam AppID of the game: 6060

## System Information
- GPU: RX 580, RTX 3080 (Prime)
- Video driver version: Mesa 1:24.0.2, Nvidia 550.54
- Kernel version: 6.7.9-Zen
- Link to full system information report as [Gist](https://gist.github.com/): [Sys report + runtime](https://gist.github.com/AquaDuck97/4e4be61736332a5b2a55e6f2259ededc)
- Proton version: Experimental, 9,8, 7

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
The game starts in a very short lasting black screen on Proton above 7 and freezes on a black screen with Proton 7

I run Plasma 6 Wayland on Arch, tried with both the Nvidia GPU and Radeon with the same result.
A Valve employee told me to change Vulkan drivers for my 580, I did that and rebooted (and made sure to Rns the old) with the same result.

## Reproduction
Launch Star Wars: Battlefront 2 through Steam with any Proton version

[steam-6060.log](https://github.com/ValveSoftware/Proton/files/14609060/steam-6060.log)

**Comment by kisak-valve** [comment]
Hello again @AquaDuck97, the extended diagnostics information for your system looks healthier than before, but the game is still having a hard time with `warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup. A Vulkan 1.3 capable driver is required.` being the line of interest in your Proton log.

It wasn't immediately obvious that you had multiple GPUs in your previous comment and it looks like the 32 bit userspace libraries for the NVIDIA driver install are missing. Can you test if adding the `lib32-nvidia-utils` system package has an effect on the game's behavior?

**Comment by AQDuck97** [comment]
> Hello again @AquaDuck97, the extended diagnostics information for your system looks healthier than before, but the game is still having a hard time with `warn: DXVK: No adapters found. Please check your device filter settings and Vulkan setup. A Vulkan 1.3 capable driver is required.` being the line of interest in your Proton log.
> 
> It wasn't immediately obvious that you had multiple GPUs in your previous comment and it looks like the 32 bit userspace libraries for the NVIDIA driver install are missing. Can you test if adding the `lib32-nvidia-utils` system package has an effect on the game's behavior?

I swear I installed that package before, I even had the command for it in my zsh history! 
It must have been uninstalled at some point... 

But that did it, thanks!
