### ISSUE TITLE
Asterix & Obelix: Slap them All! (1492310)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7579]
# Compatibility Report
- Name of the game with compatibility issues: Asterix & Obelix: Slap them All! 
- Steam AppID of the game:1492310

## System Information
- GPU: AMD RX 5500 XT
- Video driver version: Mesa 24.0.1
- Kernel version: 6.6.15
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/kupschke/5e8622fc605d1e9b27f3714063da6203
- Proton version: 8.0

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
Game does not start. Tested with proton versions from 5.13 up to 9.0 beta.
Created a log file using proton version 8.0 with enabled debug symbols

## Reproduction
Step 1: Start the game
Step 2: Game crashed ;-)

**Comment by ghost** [comment]
[steam-1492310.log](https://github.com/ValveSoftware/Proton/files/14625323/steam-1492310.log)

**Comment by Blisto91** [comment]
Hi there.
```
info:  Required Vulkan extension VK_KHR_surface not supported
...
err:   DxvkInstance: Required instance extensions not supported
```
These lines from your log indicate there is a problem with the Vulkan drivers on your system. I would try to make sure that both 64bit and 32bit Vulkan drivers are installed properly.

**Comment by ghost** [comment]
After installing mesa-vulkan-drivers:i368 the game works!
Thank you!
