### ISSUE TITLE
Scorn (698670)

### ISSUE THREAD

**Issue by maunzCache** [ValveSoftware/Proton#7581]
# Compatibility Report
- Name of the game with compatibility issues: Scorn
- Steam AppID of the game: 698670

## System Information
- GPU: AMD Radeon RX 6900 XT
- Video driver version: 4.6 Mesa 24.0.3-arch1.1
- Kernel version: 6.7.9-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): [slr-app698670-t20240317T134926.log](https://github.com/ValveSoftware/Proton/files/14627431/slr-app698670-t20240317T134926.log)
- Proton version: 9.0 Beta or Experimental

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

[steam-698670.log](https://github.com/ValveSoftware/Proton/files/14627415/steam-698670.log)

## Symptoms 
Running the game with a Proton version >= 9.x will crash the game before startup

```
Wine C++ Runtime Library

Assertion failed!

Program: Z:\home\user\.local\share\Steam\steamapps\common\Scorn\Scorn...

File: ../src-wine/dlls/winevulkan/loader_thunks.c
Line: 3080

Expression: "!status && "vkCreateRayTracingPipelinesKHR"""
```

When using Proton 8.0-5 the game starts to generate the shaders and enters into a playable mode. ~Even though my error is different, i might be related to the regression found in #3773.~

Running `vulkaninfo` should confirm the feature is actually there:
```
VkPhysicalDeviceDriverProperties:
---------------------------------
	driverID        = DRIVER_ID_MESA_RADV
	driverName      = radv
	driverInfo      = Mesa 24.0.3-arch1.1

[...]

VkPhysicalDeviceVulkan12Properties:
-----------------------------------
	driverID                                             = DRIVER_ID_MESA_RADV
	driverName                                           = radv
	driverInfo                                           = Mesa 24.0.3-arch1.1

[...]

VkPhysicalDeviceRayTracingPipelineFeaturesKHR:
----------------------------------------------
	rayTracingPipeline                                    = true
	rayTracingPipelineShaderGroupHandleCaptureReplay      = true
	rayTracingPipelineShaderGroupHandleCaptureReplayMixed = false
	rayTracingPipelineTraceRaysIndirect                   = true
	rayTraversalPrimitiveCulling                          = true
```
[steamapp698670-vulkaninfo.txt](https://github.com/ValveSoftware/Proton/files/14627916/steamapp698670-vulkaninfo.txt)

~running on `vulkan-amdgpu-pro` using `amd_pro_icd64.json`.~ <- Report was incorrect. I don't use this driver.
Edit: running on the `amdgpu` driver using `radeon_icd.i686.json` amd `radeon_icd.x86_64.json` with a hard override to ensure it

```
# From ~/.config/environment.d/10-amd.conf

# Setup hardware acceleration
LIBVA_DRIVER_NAME=radeonsi
VDPAU_DRIVER=radeonsi

# Handle Vulkan drivers
# AMD_VULKAN_ICD=RADV # Should have Same effect as below
DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1
VK_DRIVERS_FILES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:usr/share/vulkan/icd.d/radeon_icd.x86_64.json steam
```

```
lspci -k | grep -A 2 -E "(VGA|3D)" 
0c:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c0)
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Radeon RX 6900 XT
	Kernel driver in use: amdgpu
```

## Reproduction

This is rather hard to generalize as i am using an Arch Linux setup, but for me this is like:

1. Install Scorn
2. Start it with all default settings
    1. or explicitly select a Proton version >= 9.x
4. Wait for it to crash

**Comment by kisak-valve** [comment]
Hello @maunzCache, can you test how the game behaves with mesa/RADV? Issues that happen with AMDGPU-Pro and not mesa/RADV should be reported to the AMDGPU-Pro devs.

**Comment by maunzCache** [comment]
Hi @kisak-valve thanks for the fast feedback. I reported a wrong driver because my vulkan driver setup was wrong. The kernel would always load the amdgpu driver not the amdgpu-pro. Fixed my environment variables and tried it again. Initial post was updated accordingly.

Edit: I will also try to remove the shader cache by hard (Edit2: no changes) and reinstall the game. Ping you if done.

**Comment by maunzCache** [comment]
Just noticed that in my tests Steam would pull the experimental branch and not 8.0-6. So i re-did all my tests with the fixed setup. Thus Scorn will only fail with 9.0 Beta or Experimental. 8.0-5 runs just fine.

You may close this issue if you don't want to support issues in a beta build.

**Comment by simifor** [comment]
@maunzCache I couldn't reproduce the issue here with arch, RX 6600, and mesa 24.0.3. Your current logs mention the proprietary drivers as well, so you might still have a configuration issue, or you haven't uploaded logs after making your changes. And we do want beta reports, it allows for issues to be fixed before they hit stable :+1:

**Comment by maunzCache** [comment]
@simifor thank you for the feedback. I'll try to dig deeper. I wouldn't be surprised to find some wrong configuration after yesterdays suprise that Proton 8 works again.

**Comment by maunzCache** [comment]
Okay i am going to close this issue. Thanks again @simifor for trying to reproduce this issue. Tracked down my packages and found the amdgpupro driver installed. Removed it and *tada* works again with 9.0 beta and experimental. I was so sure that i pinned the open source driver but never mind.
