### ISSUE TITLE
Issue with starting games

### ISSUE THREAD

**Issue by luke1776** [ValveSoftware/Proton#7582]
# Compatibility Report
- Name of the game with compatibility issues: Alex Jones: NWO Wars, and Fallout New Vegas
- Steam AppID of the game: 2487350, 22380

## System Information
- GPU: Nvidia Geforce GT 610
- Video driver version: Mesa NVD9, 4.3 (Compatibility Profile) Mesa 23.3.2 - kisak-mesa PPA, 
-More info- dkms status nvidia
nvidia/390.157, 5.15.0-58-generic, x86_64: installed
nvidia/390.157, 5.19.0-32-generic, x86_64: installed (WARNING! Diff between built and installed module!) (WARNING! Diff between built and installed module!) (WARNING! Diff between built and installed module!)
- Kernel version: Linux 6.5.0-25-generic #25~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Feb 20 16:09:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: proton-8.0-5c

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

[steam-2487350(Alex Jones: NWO Wars).log](https://github.com/ValveSoftware/Proton/files/14629281/steam-2487350.Alex.Jones.NWO.Wars.log)
[steam-22380(Fallout New Vegas).log](https://github.com/ValveSoftware/Proton/files/14629285/steam-22380.Fallout.New.Vegas.log)

**Comment by luke1776** [comment]
Computer Information:
Manufacturer: Unknown
Model: Unknown
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Phenom(tm) 9750 Quad-Core Processor
CPU Family: 0x10
CPU Model: 0x2
CPU Stepping: 0x3
CPU Type: 0x0
Speed: 2400 MHz
4 logical processors
4 physical processors
Hyper-threading: Unsupported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Unsupported
SSE4a: Supported
SSE41: Unsupported
SSE42: Unsupported
AES: Unsupported
AVX: Unsupported
AVX2: Unsupported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Ubuntu Core 22 (64 bit)
Kernel Name: Linux
Kernel Version: 6.5.0-25-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12201001
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20240304.79797
Video Card:
Driver: Mesa NVD9
Driver Version: 4.3 (Compatibility Profile) Mesa 23.3.2 - kisak-mesa PPA
OpenGL Version: 4.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID: 0x10de
DeviceID: 0x104a
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 15.75" x 9.84" (18.54" diag), 40.0cm x 25.0cm (47.1cm diag)
Primary VRAM: 1018 MB
Sound card:
Audio device: %1$s
Memory:
RAM: 7933 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 467848 MB
Largest Free Hard Disk Block: 3715 MB
Storage:
Number of SSDs: 0
Number of HDDs: 0
Number of removable drives: 0

**Comment by luke1776** [comment]
I hope you can take this info and make a better update for me.

**Comment by luke1776** [comment]
okay I got Both fallout New Vegas Running and Alex Jones: NWO Wars using this launch command: PROTON_USE_WINED3D=1 %command%

But Alex Jones NWO Wars starts and runs but its lagging and the sound also lags, and when I get done with first level it begins to load, and loads forever. Fallout New Vegas starts up, but is extremely buggy Extreme long loading and a window keeps coming up stating: "Steam" is not Responding. You may choose to wait a short while for it to continue or force the application to quit entirely.
![Screenshot from 2024-03-17 19-11-23](https://github.com/ValveSoftware/Proton/assets/163784388/40f32e74-b3b0-4b94-b85a-8883c34f605d)

**Comment by kisak-valve** [comment]
Hello @luke1776, Proton requires a Vulkan capable GPU. Your NVIDIA GT 610 is part of the Fermi hardware generation and there is no Vulkan driver for that generation. Additionally, the `PROTON_USE_WINED3D` runtime option is not considered supported. Sorry, but your hardware is not supportable by Proton in general.
