### ISSUE TITLE
Removes the Z:\ drive and add a launch option to enable it for security reasons

### ISSUE THREAD

**Issue by DekosAnjo** [ValveSoftware/Proton#7585]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description
Remove the Z:\ drive that provides access to all files on the host system at \ and all other folders with RW permission by the user. This only makes sense on Wine, which needs it for apps to read host files. It is rare for games to need this kind of access. For games that require it to access files, a launch option could be added and it could be pre-added to Proton's default_compat_config.

## Justification
Proton is excellent for running sandboxed games in a Windows-like environment, but having access to the host file system makes Linux users vulnerable to attacks such as RCEs (as seen in the recent Apex Legends incident) and malware from mods (used to fix old games or for customization). It isn't common for Linux users to have antivirus software to block such threats, making Linux users even more vulnerable to these kinds of attacks.

With a potential bad actor executing arbitrary code in the Proton sandbox environment with the \ exposure, they can access and write to the host system, opening up more vulnerabilities or potentially encrypting files for ransom.

**Comment by kisak-valve** [comment]
Hello @DekosAnjo, this is a duplicate of #3979 and https://github.com/ValveSoftware/Proton/issues/3979#issuecomment-643625114 is equally valid now as when it was written.

Proton (and wine) is not a security barrier and if you have security concerns, then take stronger measures to isolate untrusted applications than what Proton/wine can provide.
