### ISSUE TITLE
 Final Fantasy XIV (39210) login broke

### ISSUE THREAD

**Issue by amakelainen** [ValveSoftware/Proton#7586]
# Compatibility Report
- Name of the game with compatibility issues: Final Fantasy XIV Online
- Steam AppID of the game: 39210

## System Information
- GPU: RX 5700 XT
- Video driver version:  Mesa 23.3.6
- Kernel version:  6.7.6-201.fsync.fc39.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): [SysInfo](https://gist.github.com/amakelainen/dd76c06dd0216195a7775cd87d963d4e)
- Proton version: experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Login stopped working today after game update. Launcher pops out as usually but after filling passwd and otp -fields to login, launcher claims that i have no valid licence or subscription to platform i am using. But my sub is active and i can login from my kids windows machine with no problem. Was actually filling ticket to SE when find out steam deck user with same problem so decided to report it here.  Sadly i dont have another machine with specs good enough to try another distro/install .
![image](https://github.com/ValveSoftware/Proton/assets/143871978/915bc943-98da-4654-b0b8-926002204033)

## Reproduction
Start launcher enter passwd / and otp / and push Login

[steam-39210.log](https://github.com/ValveSoftware/Proton/files/14650761/steam-39210.log)

**Comment by kisak-valve** [comment]
Hello @amakelainen, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/580#issuecomment-2007484564.
