### ISSUE TITLE
Mass Effect Legendary Edition doesn't launch. Warning about optional parameter "-locale {locale}"

### ISSUE THREAD

**Issue by gnusuari0** [ValveSoftware/Proton#7587]
# Compatibility Report
- Name of the game with compatibility issues: Mass Effect Legendary Edition
- Steam AppID of the game: 1328670

## System Information
- GPU: Radeon VII
- Video driver version: Mesa 23.3.6 (radv)
[steam-1328670.log](https://github.com/ValveSoftware/Proton/files/14659059/steam-1328670.log)

- Kernel version: 6.7.9
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/gnusuari0/c7700e7fff6453818e72eb902d09a339
- Proton version: Proton 9.0 (beta)

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
It suddenly stopped working. I only wanted to restart a playthrough and I removed the old saved profiles. I can't launch the game anymore. I have tried with STEAM_RUNTIME=0 but doesn't work either.

Sometimes it crashes like in this issue: https://github.com/ValveSoftware/Proton/issues/7543
Other times Steam warns about the app trying to launch with optional parameter "-locale {locale}" and advises to cancel if I don't understand that. If I click on continue it launches again the EA App, it closes and shows the same message of optional parameter with one extra "locale", that is, "-locale {locale} -locale {locale}".
Other times EA App shows up and closes itself without further notice.
Other times nothing shows up at all.

Tried with Proton 7 which worked while Proton 8 didn't. But it also shows the same message about optional parameter. So does Proton 8. If you wait enough time with the dialog about optional parameter, the EA App may show its crash message window. Steamwebhelper is running in the background.

![imatge](https://github.com/ValveSoftware/Proton/assets/36234118/1fa4c4b9-ecb7-40e1-ba90-c041626e0683)

## Reproduction

Try to launch the game. It doesn't start. EA App can crash, closes itself or Steam show a message about optional parameter.

**Comment by gnusuari0** [comment]
Tried restarting the computer and verifying installation files. Nothing.

**Comment by kisak-valve** [comment]
Hello @gnusuari0, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4823#issuecomment-2008577790.
