### ISSUE TITLE
Frostpunk crashes on startup with runtime error

### ISSUE THREAD

**Issue by Kupferdrache** [ValveSoftware/Proton#7589]
# Compatibility Report
- Name of the game with compatibility issues: Frostpunk
- Steam AppID of the game: 323190

## System Information
- GPU: AMD Radeon RX6650
- Video driver version: Mesa 24.0
- Kernel version: 6.6
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/Kupferdrache/3d98895b4dbc4632a6c5e592d1dc68c7
![fp-proto-regression](https://github.com/ValveSoftware/Proton/assets/18716155/48cf11f6-28c3-4061-88f1-5e202736f4fe)
- Proton version:1710947987 experimental-9.0-20240320

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 the log file exceeds 25 MiB even compressed as archive

## Symptoms 
The Game crashes with a C++ runtime error in winevulkan/loader_thunks.c on line 5141 when no log is given as parameter and produces a multi GiB proton log file before force quitting the program via other method was used as the game just stayed on the black screen that the non log version gives without reaching the runtime error dialog.

## Reproduction
have the game installed and start the game with 1710947987 experimental-9.0-20240320 that was the default version at the time of writing this report.

Reverting back to 1710431022 proton-9.0-beta15 suggests this is a regression since beta15

**Comment by kisak-valve** [comment]
Hello @Kupferdrache, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/412#issuecomment-2012326598.
