### ISSUE TITLE
Command & Conquer Red Alert™, Counterstrike™ and The Aftermath™ (2229840)

### ISSUE THREAD

**Issue by iodream** [ValveSoftware/Proton#7591]
# Compatibility Report
- Name of the game with compatibility issues: Command & Conquer Red Alert™, Counterstrike™ and The Aftermath™
- Steam AppID of the game: 2229840

## System Information
- GPU: intel hd 3000
- Video driver version: Mesa 23.3.6
- Kernel version: 6.7.9
- Link to full system information report as [Gist](https://gist.github.com/): [report](https://gist.github.com/iodream/21f587c827e63400f174b3e3b084bd5a)
- Proton version: 1710947987 experimental-9.0-20240320

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton log:  [steam-2229840.log](https://github.com/ValveSoftware/Proton/files/14705045/steam-2229840.log)

## Symptoms 
Game crashes with "Unable to allocate primary video buffer"

This seems to be a regression because Proton 8 launches the game(albeit with other issues) 

![image](https://github.com/ValveSoftware/Proton/assets/42720874/40dc3d44-2e0d-464d-bae8-47efb5212f0b)

## Reproduction
Start CnC Red alert

**Comment by alasky17** [comment]
@iodream Thank you for reporting the regression!  We will look into it :)

**Comment by iodream** [comment]
Latest Proton experimental-bleeding-edge-9.0-86937-20240321-paf6cb7-we37b544-d28c7c0-v21008d fixes the issue!

I'll leave this issue open to confirm later on when the fix reaches the stable release and to post a couple further issues with this game.

**Comment by iodream** [comment]
Closing as fixed with Proton 9.0-3. 

Some other issues like slow game speed while panning view and flickering menus can be fixed either with gamescope or with cnc-ddraw
