### ISSUE TITLE
R.U.S.E freezes during loading screen, no crash

### ISSUE THREAD

**Issue by maximepires4** [ValveSoftware/Proton#7593]
# Compatibility Report
- Name of the game with compatibility issues: R.U.S.E
- Steam AppID of the game: 21970

## System Information
- GPU: RTX 3060 TI LHR
- Video driver version: 4.6.0 NVIDIA 550.54.14
- Kernel version: 6.6.10-76060610-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/maximepires4/ef770aa71f5f6f8ddd77de8079687712
- Proton version: 1710431022 proton-9.0-beta15

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-21970.log](https://github.com/ValveSoftware/Proton/files/14725113/steam-21970.log)

## Symptoms 

The game will launch but freeze during the loading screen.

## Reproduction

Install and launch the game.

**Comment by kisak-valve** [comment]
Hello @maximepires4, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1602#issuecomment-2015587964.
