### ISSUE TITLE
Star Trek Online Launcher has a black screen and is unusable

### ISSUE THREAD

**Issue by CallMeTheArrow** [ValveSoftware/Proton#7596]
See https://github.com/ValveSoftware/Proton/issues/1198#issuecomment-2016003845

**Comment by kisak-valve** [comment]
Hello @CallMeTheArrow, we're using one issue report per unofficially supported game title. Your previous comment at https://github.com/ValveSoftware/Proton/issues/1198#issuecomment-2016003845 was the correct place for feedback on the game's behavior with Proton.

Closing as a duplicate.

**Comment by CallMeTheArrow** [comment]
OK, thank you!
________________________________
