### ISSUE TITLE
The Witcher 3 - Freeze in Inventory

### ISSUE THREAD

**Issue by rariema** [ValveSoftware/Proton#7597]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher 3
- Steam AppID of the game: 292030

## System Information
- GPU: RX 6000
- Video driver version: Mesa 24.0.3
- Kernel version: 6.8.1-arch1-1
- Proton version: 9.0.5 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Game freezes in Inventory

## Reproduction

Start Game, load savegame.
Open Inventory, Map, Charakter etc. Do some stuff. Game will stop responding to inputs after a while.

Possible regression, game runs fine with Proton 8.0.5

[steam-292030-witcher3.log](https://github.com/ValveSoftware/Proton/files/14731307/steam-292030-witcher3.log)

**Comment by kisak-valve** [comment]
Hello @rariema, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/607#issuecomment-2016482099.

**Comment by rariema** [comment]
sorry, didn't know. so thx!
