### ISSUE TITLE
Command & Conquer: Tiberian Sun (2229880)

### ISSUE THREAD

**Issue by doomvrr** [ValveSoftware/Proton#7598]
# Compatibility Report
- Name of the game with compatibility issues: Command & Conquer™ Tiberian Sun™ and Firestorm™
- Steam AppID of the game: 2229880

## System Information
- GPU: intel HD520
- Video driver version: Mesa 23.3.6
- Kernel version: 6.7.9-200.fc39.x86_64
- Link to full system information report as [Gist](https://gist.github.com/doomvrr/230e3f9fb0af7039c0843287a01f7815):
- Proton version: 1710947987 experimental-9.0-20240320

## I confirm:
- [+] that I haven't found an existing compatibility report for this game.
- [+] that I have checked whether there are updates for my system available.

## Symptoms
In-game, game is very laggy whenever I hover mouse over a unit or building (mouse cursor changes to custom game one from default windows one)

## Reproduction
Start either C&C Tiberian Sun
Start either campaign or a skirmish game
Once loaded, move mouse around, hover over a unit, as default cursor is same as windows one and doesn't lag

[steam-2229880.log](https://github.com/ValveSoftware/Proton/files/14731571/steam-2229880.log)

**Comment by kisak-valve** [comment]
Hello @doomvrr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7584#issuecomment-2016494050.
