### ISSUE TITLE
Team Fortress 2 

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7599]
Hello, Team Fortress 2 is not working whatsoever for me on Linux, the issues are as follows:
The game, neither the Stable version or the 64-bit Beta will launch using Steam Play, only when Proton (9.0 or older) is enabled, would they launch

when Proton is enabled, the game won't let me enter matchmaking, saying that I am 'in Insecure mode', adding -secure to the launch options of Team Fortress 2 doesn't help, as the game crashes when joining a server when this parameter is added.

Now, with a reinstall, even with Proton, the game doesn't launch whatsoever.
Here's some system information:

Operating System: Bazzite 39
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.7.9-204.fsync.fc39.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 8 × AMD Custom APU 0405
Memory: 14.5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405
Manufacturer: Valve
Product Name: Jupiter
System Version: 1

## I confirm:
- [ ❌] that I haven't found an existing compatibility report for this game.
- [ ✔️] that I have checked whether there are updates for my system available.

I will be adding logs shortly in the reply section.

**Comment by kisak-valve** [comment]
Hello @tierwelder, we're using one issue report per unofficially supported game title run with Proton, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3150#issuecomment-2016550581.

Issues with the Linux native variant of the game should be evaluated on the ValveSoftware/Source-1-Games issue tracker.
