### ISSUE TITLE
Temtem: audio crackling

### ISSUE THREAD

**Issue by Pentadrago** [ValveSoftware/Proton#7607]
# Compatibility Report
- Name of the game with compatibility issues: Temtem
- Steam AppID of the game: 745920

## System Information
- GPU: AMD Radeon Vega 56
- Video driver version: Mesa 24.0.3
- Kernel version: 745920
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Pentadrago/60100eaab1f1f7fec3b2daa2ced2e442
- Proton version: 7 / 8 / 9

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-745920.tar.gz](https://github.com/ValveSoftware/Proton/files/14750163/steam-745920.tar.gz)

## Symptoms 
Audio becomes distorted after playing a few minutes, music and sound effects start crackling and disappearing.

## Reproduction
Start Temtem, play for a few moments, maybe enter a fight.

**Comment by kisak-valve** [comment]
Hello @Pentadrago, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3441#issuecomment-2019031043.

**Comment by Pentadrago** [comment]
@kisak-valve Thanks for the info. 
What exactly does unofficially supported game title mean? Temtem is marked as Steam Deck Verified.
