### ISSUE TITLE
NUKITASHI (2399220)

### ISSUE THREAD

**Issue by matte-schwartz** [ValveSoftware/Proton#7608]
# Compatibility Report
- Name of the game with compatibility issues: NUKITASHI
- Steam AppID of the game: 2399220

## System Information
- GPU: AMD VanGogh APU, Galileo OLED Deck
- Video driver version: Mesa 24.1.0
- Kernel version: 6.7.6-201.fsync.fc39.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/matte-schwartz/82b3c5c08bf984fac7ad83877c95fe51
- Proton version: Proton 8-05 and Proton 9 (Beta)

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

[Proton 8-05.log](https://github.com/ValveSoftware/Proton/files/14756219/steam-2399220-8-05.log)
[Proton 9 (Beta).log](https://github.com/ValveSoftware/Proton/files/14756226/steam-2399220-9-beta.log)

## Symptoms
Somewhere between Proton 8-05 and the current build of Proton 9 (Beta), videos in the game went from showing a multicolored error screen to showing a totally black screen. While Proton does not support playing back the video codec, this black screen seems to be unintended since the dummy video for `mediaconverter` doesn't appear to have changed between Proton 8-05 and Proton 9 (Beta). 

To provide some additional background context, videos and audio went from playing correctly in Proton-GE 8-32 to showing the same exact black screen as Proton 9 (Beta) in Proton-GE 9-1 and 9-2, even while still playing audio correctly. The fact that both Proton 9 (Beta) and GE-9 builds have the exact same black screen during video playback leads me to believe that it was an upstream Proton change that caused this to occur. 

If it was just an issue in Proton-GE then I wouldn't file it under this tracker, but this seems like the correct tracker for this specific error. Thanks!

## Reproduction
Fast forward all the way through the game until you get to the end credits video (~60 seconds of fast forward). At the very end you'll reach the video, and it will show the multicolored or black screen for a few seconds depending on Proton version before returning you to the main menu.

You can turn on skipping unread text in the settings menu to make things quicker for testing.

**Comment by AJuujarvi** [comment]
Thank you for the report! I was able to reproduce the regressive issue, we are looking into it. :)

**Comment by matte-schwartz** [comment]
Unsurprisingly, NUKITASHI 2 (2614070) appears to have the same black screen regression. I'll refrain from filing a separate report as you've already managed to replicate the regressive issue.

**Comment by matte-schwartz** [comment]
fixed as of latest experimental release
