### ISSUE TITLE
EA Launcher is broken on every Proton Version (example made with NFS Unbound)

### ISSUE THREAD

**Issue by maximemelian** [ValveSoftware/Proton#7611]
# Compatibility Report
- Name of the game with compatibility issues: Need for Speed Unbound
- Steam AppID of the game: 1846380

## System Information
- GPU: AMD Radeon RX 7900 XTX
- Video driver version: 24.0.3-2
- Kernel version: 6.8.2
- Link to full system information report as [Gist](https://gist.github.com/maximemelian/64d4b01011e0d6834722ff950018767c):
![grafik](https://github.com/ValveSoftware/Proton/assets/20738540/40467bde-3b1b-485e-a00d-dbb420c6925c)
- Proton version: Experimental as of 2024-03-28, but every version crashes the same.

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
  (( I haven't seen this specific game work, neither do I have seen the EA Launcher work, but Origin worked way back, so it did run some time ago. ))
- [x] that I have checked whether there are updates for my system available.

Grepping for errors reveals that some Qt5Pdf.dll is missing, I don't quite understand why the copy protection needs to do PDF stuff at this stage of starting up though...

```
[maximilian@shibuya ~]$ cat steam-1846380.log |grep :err: | grep 'dll'
5753.620:0128:012c:err:module:import_dll Library Qt5Pdf.dll (which is needed by L"C:\\Program Files\\Electronic Arts\\EA Desktop\\EA Desktop\\imageformats\\qpdf.dll") not found
5760.637:01ec:0204:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040111 for dll L"C:\\windows\\system32\\ieframe.dll"
5761.300:0408:040c:err:module:import_dll Library Qt5Pdf.dll (which is needed by L"C:\\Program Files\\Electronic Arts\\EA Desktop\\EA Desktop\\imageformats\\qpdf.dll") not found
5781.034:0408:040c:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040111 for dll L"C:\\windows\\system32\\ieframe.dll"
5784.888:03fc:03f0:err:module:import_dll Library Qt5Pdf.dll (which is needed by L"C:\\Program Files\\Electronic Arts\\EA Desktop\\EA Desktop\\imageformats\\qpdf.dll") not found
5785.376:0314:070c:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040111 for dll L"C:\\windows\\system32\\ieframe.dll"
5786.185:053c:0534:err:module:import_dll Library Qt5Pdf.dll (which is needed by L"C:\\Program Files\\Electronic Arts\\EA Desktop\\EA Desktop\\imageformats\\qpdf.dll") not found
5788.101:053c:0534:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040111 for dll L"C:\\windows\\system32\\ieframe.dll"
```

Kindly see attached log file for more information.
[steam-1846380.tar.gz](https://github.com/ValveSoftware/Proton/files/14782108/steam-1846380.tar.gz)

## Symptoms
The game wont start at all, as the copy protection EA Launcher crashes with an ominous GUI error. Supposedly background services crashed.

![grafik](https://github.com/ValveSoftware/Proton/assets/20738540/4991b2e7-5aa2-491c-917c-325fcc41f681)
![grafik](https://github.com/ValveSoftware/Proton/assets/20738540/cd7af829-cf30-4b4f-8cd9-473c220c8cc7)

## Reproduction
- Download NFS Unbound (or any game with EA Launcher copy protection for that matter)
- Start the game first time
- Embrace the crash! :-(

**Comment by kisak-valve** [comment]
Hello @maximemelian, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6502#issuecomment-2024237358.
