### ISSUE TITLE
STAR WARS™ Empire at War: Gold Pack (32470) no longer launches

### ISSUE THREAD

**Issue by CounterPillow** [ValveSoftware/Proton#7613]
# Compatibility Report
- Name of the game with compatibility issues: STAR WARS™ Empire at War: Gold Pack
- Steam AppID of the game: 32470

## System Information
- GPU: AMD Radeon RX 7900 XT
- Video driver version: mesa 24.0.3
- Kernel version: Linux 6.8.2-arch2-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/CounterPillow/974cb8b8ddce6ba6710f8d1302a1626c
- Proton version: 1710947987 experimental-9.0-20240320

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton Log: https://overviewer.org/~pillow/up/d33d1afc8d/steam-32470%20submitthis.log

## Symptoms 

Game flashes a white window briefly, then immediately closes. Used to run fine literally earlier today but then I had to restart the game because it froze and while I did that it seems Steam downloaded some runtime updates that borked it.

## Reproduction

1. Launch the game with Proton Experimental on Arch btw, KDE Plasma6 Wayland
2. Observe a white window briefly appearing and then disappearing

**Comment by kisak-valve** [comment]
Hello @CounterPillow, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/584#issuecomment-2027248685.
