### ISSUE TITLE
Granny (962400)

### ISSUE THREAD

**Issue by MateusNobreSilva** [ValveSoftware/Proton#7614]
# Compatibility Report
- Name of the game with compatibility issues: Granny
- Steam AppID of the game: 962400

## System Information
- CPU : AMD Ryzen 5 5500U with Radeon Graphics
- Kernel version: Linux 6.6.23-1-lts
- Proton version: proton 8.0-5

URL of the game: https://store.steampowered.com/app/962400/Granny/

## Symptoms
I'm using Arch Linux on my notebook, and I downloaded the game Granny through Steam. I tried running it with Proton 8.0-5, during the game menus the mouse worked, but during gameplay it froze in the center of the screen. I switched to Proton 7.0-6 and everything worked perfectly.

**Comment by kisak-valve** [comment]
Hello @MateusNobreSilva, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by MateusNobreSilva** [comment]
Hello, thanks to help.


The Proton 7 had the same problem, with the mouse fixed in the center.

the gist: https://gist.github.com/MateusNobreSilva/8fa23cba163e94df01ef98286ea8f501

the files:
[steam-962400.txt](https://github.com/ValveSoftware/Proton/files/14807777/steam-962400.txt)

**Comment by kisak-valve** [comment]
An Arch KDE wayland session suggests that your issue is https://github.com/ValveSoftware/Proton/issues/7564#issuecomment-2017700511.

**Comment by MateusNobreSilva** [comment]
thanks, i managet to get the mouse to work again when i disabled the option: "image effect" in the menu.
