### ISSUE TITLE
Vampire the Masquerade: Bloodlines - "Available Memory is less than 15mb" error on latest proton, but not on v3.7-8

### ISSUE THREAD

**Issue by syberphunk** [ValveSoftware/Proton#7615]
# Compatibility Report
- Name of the game with compatibility issues: Vampire the Masquerade: Bloodlines
- Steam AppID of the game: 2600

## System Information
- GPU: 04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 1435 (rev ae)
- Video driver version: mesa  23.1.3.170245.radeonsi_3.5.3-1
- Kernel version: Linux steamdeckole 6.1.52-valve16-1-neptune-61 1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000 x86_64 GNU/Linux
- Link to full system information report as [Gist](https://gist.github.com/): Guys, it's an OLED Steam Deck, you know your own hardware, otherwise provide the command to give this to you because this isn't obvious or straight forward in linux, and you lock the system down.
- Proton version: 1705700124 proton-8.0-5c

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-2600.log](https://github.com/ValveSoftware/Proton/files/14805345/steam-2600.log)

## Symptoms 
Game throws the error "Available memory is less than 15mb"

## Reproduction
- Install game
- Run game
- See error "Available memory is less than 15mb"
- Game closes

## Mitigation / Resolution
- Open game properties
- Go to Compatibility
- Force the use of a specific steam play compatibility tool
- Choose Proton 3.7-8
- Game now launches

I shouldn't have to do this to get the game to run. I'm aware there are also "unofficial patches" to get this game to run, but people can still pay £15 for this game on Steam, and it is unplayable on the Steam Deck because of this error.

There either needs to be some form of regression (is that the right word?) to incorporate why it works with the older proton version, or it should include the unofficial fix.

Here's the proton log when running with proton 3.7-8:

[steam-2600-proton3.7-8.log](https://github.com/ValveSoftware/Proton/files/14805413/steam-2600-proton3.7-8.log)

**Comment by kisak-valve** [comment]
Hello @syberphunk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1804#issuecomment-2027388157.
