### ISSUE TITLE
What is exactly required from game developer to fix EAC issue with DT_HASH?

### ISSUE THREAD

**Issue by In-line** [ValveSoftware/Proton#7619]
I'm playing a few Steam games, what work well with Proton, but their EAC anticheat doesn't support glibc without DT_HASH patch. Notable offenders are Squad, Insurgency: Sandstorm. This is cross game issue.

A while ago Arch Linux reverted their glibc patch, which previously fixed DT_HASH problem. And a while ago EAC released some update to fix DT_HASH issue on their side too (couldn't find source for this?).

I was in communication with Squad developers, Offworld Industries. In email communication they mentioned that 

> Hello Inline,
I brought this to the Dev team and was told that we are currently updatate as we can be on our end, we are on the latest version of the EOS SDK which EAC comes with. The issue may need to be fixed by Epic / EAC on their end.
Also as a reminder we do not natively support Proton or Linux so there will be no ETA for a hotfix on our end. 

So my question is. What is exactly required from game developer to fix EAC issue with DT_HASH? I think, if I gave Squad developers exact instructions on what they need to update, they will do it.

But I'm fairly certain, that EAC released some update a while ago to fix this issue on their end. This issue just seems to be undocumented in Proton documentation. And I couldn't fix any mention of it in Epic documentation. 

They seem to be as confused as me on this topic. This might be helpful for other game developers, that want to support Steam Play. 

Original reddit post: https://www.reddit.com/r/linux_gaming/comments/1brh5i2/what_is_exactly_required_from_game_developer_to/

**Comment by kisak-valve** [comment]
Hello @In-line, sorry, but it isn't sensible for a Proton developer to publicly discuss the implementation details of an anti-cheat vendor. This is an issue between the game developers and their anti-cheat vendor. It might be possible for a Proton developer to try to help figure out what's going on there, but that has to be handled on a non-public medium between the game devs, Proton devs, and anti-cheat devs.
