### ISSUE TITLE
Anno 1800 or Ubisoft launcher

### ISSUE THREAD

**Issue by Motze74** [ValveSoftware/Proton#7621]
# Compatibility Report
- Anno 1800 refuses to launch. Not sure this is an issue with proton, though
- Steam AppID of the game: 916440

## System Information
CPU: 6-core AMD Ryzen 5 5500 (-MT MCP-) speed/min/max: 400/400/4267 MHz
Kernel: 6.6.19-1-MANJARO x86_64 Up: 9m Mem: 5.31/15.49 GiB (34.3%)
Storage: 931.51 GiB (42.0% used) Procs: 362 Shell: Zsh inxi: 3.3.33

- Video driver version: <Device-1: AMD Navi 23 [Radeon RX 6600/6600 XT/6600M] driver: amdgpu
    v: kernel
  Device-2: Logitech Webcam C310 driver: snd-usb-audio,uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.11 with: Xwayland v: 23.2.4
    compositor: gnome-shell v: 45.4 driver: X: loaded: amdgpu
    unloaded: modesetting,radeon dri: radeonsi gpu: amdgpu
    resolution: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: radeonsi,swrast
    platforms: wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.2-manjaro1.1
    renderer: AMD Radeon RX 6600 (radeonsi navi23 LLVM 16.0.6 DRM 3.54
    6.6.19-1-MANJARO)
>
- Kernel version: <!6.6.19-1-MANJARO x86_64>
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Motze74/85fec622794cc78d1b8488f4cf8dc2d4 
- Proton version: Proton experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-916440.zip](https://github.com/ValveSoftware/Proton/files/14821388/steam-916440.zip)

## Symptoms 
- Steam does not properly recognize that I am online (e.g. store pages do not show), but Steam will download and install games and updates.
- UbiSoft connect does not recognize that I am online, and insists that my internet must not be working
- Anno 1800 does not launch in offline mode.   

## Reproduction
Entire machine went offline three days ago. Troubleshooting revealed that connection was up, but some ports appear to have been blocked (?). My machine uses an ethernet connection.

Access to Internet router via WLAN from other devices was possible, and the router both "saw" the computer in question, and assigned an IP adress, so no hardware issues. Assigning a permanent IP adress didn't result in any change. Broken DNS? If so, why?
    
Ultimately, what got the machine back online was booting out NetworkManager and replacing it with systemd-networkd (which, for lack of a better word, fells much more responsive and faster).

Now, everything online is working again, except for Steam and Ubisoft Connect. What that is supposed to be good for, I don't know.  

I tried switching from proton-experimental to proton-beta 9.0 and back. No change.
Am now trying to remove and reinstall ubisoft connect. Maybe that will help. Am now rapidly reaching the end of my rope. I'm not exactly a newbie, but also not familiar with linux commands, so learning while going along.

I tried a suggestion in  a forum and deleted subdirectory  916440 in the steamapps directory, but no change apart from a rebuild at attempted game launch. 

The issue seems to be how "Steam" and "Ubisoft connect" connect to the internet (through proton/wine?), no idea how to influence that.    

[steam-916440.zip](https://github.com/ValveSoftware/Proton/files/14821392/steam-916440.zip)

**Comment by Motze74** [comment]
There seems to be some connection to here... not sure, though, and why did it show up out of the blue three days ago?

**Comment by Motze74** [comment]
There seems to be some connection to here... not sure, though, and why did it show up out of the blue three days ago?
https://bugs.winehq.org/show_bug.cgi?id=53346

**Comment by kisak-valve** [comment]
Hello @Motze74, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2544#issuecomment-2029707565.
