### ISSUE TITLE
BOOMEROAD (2512820)

### ISSUE THREAD

**Issue by LeaPhant** [ValveSoftware/Proton#7622]
# Compatibility Report
- Name of the game with compatibility issues: BOOMEROAD
- Steam AppID of the game: 2512820

## System Information
- GPU: RX 7900 XT
- Video driver version: Mesa 24.0.3
- Kernel version: 6.8.2
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/LeaPhant/40ee5d8b30f268d3f03c425bc5b0b1ed
- Proton version: experimental-9.0-20240328c

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2512820.log](https://github.com/ValveSoftware/Proton/files/14821409/steam-2512820.log)

## Symptoms 

Game has no audio if ran through Proton. Possibly the same cause as https://github.com/ValveSoftware/Proton/issues/7612 since both games were released on the same day by the same studio.

## Reproduction

1. Launch game with Proton.
2. Music should start playing at "Click left mouse button screen", confirmation sound should play when clicking, neither happen.

**Comment by AJuujarvi** [comment]
@LeaPhant This should now be fixed in the latest Proton Experimental release. Let me know if you still have issues!
