### ISSUE TITLE
Terminator Resistance, worked until reboot

### ISSUE THREAD

**Issue by binaryhellstorm** [ValveSoftware/Proton#7624]
# Compatibility Report
- Name of the game with compatibility issues: Terminator Resistance
- Steam AppID of the game: 954740

## System Information
- GPU:  GeForce GTX 1650
- Video driver version:  nvidia-dri ver-535
- Kernel version: Linux 6.5.0-26-generic x86_64
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Tried with 8.0-5, 9.0, experimental, was working with Experimental 

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

 No logs generated

**Comment by kisak-valve** [comment]
Hello @binaryhellstorm, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4357#issuecomment-2029724655.
