### ISSUE TITLE
Nvidia Reflex causes random hangs/freezes in games

### ISSUE THREAD

**Issue by kodatarule** [ValveSoftware/Proton#7630]
# Compatibility Report

## System Information
- GPU: RTX 3090
- Video driver version: nvidia 550.67
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kodatarule/6cf33b60e96a611b6d320d7fe860788d
- Proton version: Experimental

## Symptoms 
Game either freezes on the startup sequence or after sometime of playing.

## Reproduction
Just enable nvidia reflex in-game

The following titles seem to be highly affected by this:
Cyberpunk(the game cannot even launch properly, it just hangs on logo)
Horizon forbidden west(it just stays black screen or complete freeze when reflex is enabled)
Robocop rogue city(freezes randomly when you play after reflex is enabled)

**Comment by xpander69** [comment]
Cyberpunk 2077 works fine here with reflex+boost enabled on proton-experimental. I do use nvidia vulkan dev drivers however. 

RTX 3080
550.40.59

Log: 
[steam-1091500.log](https://github.com/ValveSoftware/Proton/files/14848877/steam-1091500.log)

**Comment by esullivan-nvidia** [comment]
Thanks for the report. Are you able to reproduce this issue with any of the previous drivers in the 550 series?

**Comment by kodatarule** [comment]
Hi @esullivan-nvidia 
I was able to test further to this and it seems to trigger when gamescope is used(currently the only way to get HDR in games in KDE Plasma wayland), this doesn't happen when gamescope is not active.
For reference this is how I start the game using gamescope 

`MANGOHUD=0 ENABLE_HDR_WSI=1 gamescope --fullscreen -w 2560 -h 1440 --hdr-enabled --hdr-debug-force-output --hdr-sdr-content-nits 436 --adaptive-sync -- %command%`

EDIT: I did generate a log of cyberpunk
[steam-1091500.log](https://github.com/ValveSoftware/Proton/files/14856836/steam-1091500.log)

EDIT2: Further testing this seems to affect wayland and gamescope the most, on xorg I am unable to reproduce the problems.

**Comment by kodatarule** [comment]
This seems resolved in 555.58.02, haven't had such freeze problems.
