### ISSUE TITLE
Bloody Walls (531960)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#7632]
# Compatibility Report
- Name of the game with compatibility issues: Bloody Walls
- Steam AppID of the game: 531960

## System Information
- 1 TB OLED steam deck LE 
- Proton version: Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game gets stuck on a white screen as of latest Experimental proton. Issue has been present since 6.3-8 (5.0-10 crashed on launch so I dunno if it was in an older version), the game does render properly on 4.11-13 though.

[steam-531960.log](https://github.com/ValveSoftware/Proton/files/14865693/steam-531960.log)

## Reproduction
Start the game

**Comment by AJuujarvi** [comment]
@waspennator This should now work in Proton Experimental Bleeding Edge. You can check this by going to Proton Experimental -> Properties -> Beta -> Selecting Bleeding Edge from the drop down. Make sure to select the Bleeding Edge that uses Proton 9.

**Comment by waspennator** [comment]
Can confirm the game seems to work now, will close this issue when the next proton Experimental update occurs.

**Comment by waspennator** [comment]
Fix has officially hit regular Experimental, closing.
