### ISSUE TITLE
Gods Will Be Watching (274290)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#7634]
# Compatibility Report
- Name of the game with compatibility issues: God's Will Be Watching
- Steam AppID of the game: 274290

## System Information
- 1 TB OLED LE Steam Deck 
- Proton version: Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game seemed to work fine with what I'm assuming the version of proton it was tested with (6.3-8), but it seems like recent versions of Proton crash with a vertex shader error. Problematic since this game is marked currently as playable on deck using proton.
[steam-274290.log](https://github.com/ValveSoftware/Proton/files/14876888/steam-274290.log)

## Reproduction
Start the game.

**Comment by AJuujarvi** [comment]
@waspennator Thank you for the report! I am able to repro this, and we are looking into it. :)

**Comment by waspennator** [comment]
Still broken on latest Experimental build and still marked as playable on deck, here's a pic to show the specific errors, dunno why this worked on older Proton versions.

![download](https://github.com/ValveSoftware/Proton/assets/78768499/94875ba8-c5be-4852-892b-c71a194175ad)

**Comment by waspennator** [comment]
Regression has been fixed as of latest proton Experimental update.
