### ISSUE TITLE
Atmospherics stuck on low in God of War 2018

### ISSUE THREAD

**Issue by babiescanfly** [ValveSoftware/Proton#7635]
# Compatibility Report
- Name of the game with compatibility issues: God of War
- Steam AppID of the game: 1593500

## System Information
- GPU: AMD Radeon Graphics
- Video driver version: 3.6
- Kernel version: 6.1.52-valve19-1-neptune-61 (64-bit)
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/babiescanfly/fef74daedc9ba3c5136426b368b1b1ff
- Proton version: 8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Even if atmospherics in the graphics menu are set to anything other than low (including presets) the game will still use the low version. If a custom setting is used the game will always reset atmospherics to low.

## Reproduction
Always occours. Can't find an instance where it doesn't.

**Comment by kisak-valve** [comment]
Hello @babiescanfly, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5511#issuecomment-2038461146.
