### ISSUE TITLE
Battlefield 1 - seeing scope glint through objects

### ISSUE THREAD

**Issue by d3vilguard** [ValveSoftware/Proton#7643]
# Compatibility Report
- Name of the game with compatibility issues: Battlefield 1
- Steam AppID of the game: 1238840

## System Information
- GPU: RX 6800
- Video driver version: mesa-minimal-git-24.1.0_devel.187172.7c0b19a6071-1, compile against llvm-git
- Kernel version: 6.8.3 TKG BORE
- Link to full system information report as [Gist](https://gist.github.com/d3vilguard/486c1c3b373e9010e95e6f8fd97d1d2a):
- Proton version: Proton Experimental - Bleeding Edge (also issue with latest 8)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Sniper scope glint is visible through objects (essentially like I'm wallhacking). Confirmed with Bleeding Edge and 8. Also map ZEEBRUGGE seems to have object issues also. 

## Reproduction
Have a sniper scoped behind object and see the glint when you are not supposed to.

**Comment by kisak-valve** [comment]
Hello @d3vilguard, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5047#issuecomment-2041521161.
