### ISSUE TITLE
(Steam Deck) Doom 3 and RoE (both OG and BFG Edition) have graphical glitches when MSAA is enabled

### ISSUE THREAD

**Issue by Deus-nsf** [ValveSoftware/Proton#7647]
Most particularly visible on transparent surfaces with refraction (glass from windows, heat particles, etc...)
It creates a smearing white effect that is very unpleasant to look at.
No MSAA fixes it, but it's a shame since the Deck has plenty of GPU headroom.

It's very surprising though as ID Tech 4 uses OpenGL, so this is using native rendering, maybe an issue with Mesa drivers?

**Comment by kisak-valve** [comment]
Hello @Deus-nsf, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/569#issuecomment-2054039711.
