### ISSUE TITLE
Compiling Shaders Stuck

### ISSUE THREAD

**Issue by homanhluc** [ValveSoftware/Proton#7648]
# Compatibility Report
- Name of the game with compatibility issues: Street Fighter 6
- Steam AppID of the game: 1364780

## System Information
- GPU: Intel Mesa Intel(R) Graphics (RPL-U)
- Video driver version:  4.6 (Compatibility Profile) Mesa 24.0.5 - kisak-mesa PPA
- Kernel version: Ubuntu 22.04.4 LTS 
- Proton version: Proton 7,8, Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms
![image](https://github.com/ValveSoftware/Proton/assets/29135045/ee1452d1-ba17-4875-896b-f3c14e627205)

Compiling Shaders stuck when ~50% progress bar

How to fix?

**Comment by kisak-valve** [comment]
Hello @homanhluc, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6817#issuecomment-2059016589.
