### ISSUE TITLE
Yakuza 3 Remastered, closing at start

### ISSUE THREAD

**Issue by LEAL-original** [ValveSoftware/Proton#7649]
# Compatibility Report
- Yakuza 3: Remastered
- AppID: 1088710

## System Information
Note: I use Steam's flatpak, so the gist system report might not be accurate, hence why I took the liberty to add some details below in addition to, of course, the full system report through steam, as requested.

- GPU: NVIDIA RTX3060
- Video driver version: NVIDIA 550.67
- CPU: INTEL i5-13400F (16)@4.600Ghz
- RAM: 32GB 
- OS: Arch Linux x86_64
- Kernel version: 6.8.5-zen1-1-zen 
- DE: Hyprland
- Proton version: Proton Experimental (previously tried '8xx', '7xx', etc; none worked)
- Proton log: [steam-1088710.log](https://github.com/ValveSoftware/Proton/files/14970576/steam-1088710.log)
- Full system report: https://gist.github.com/LEAL-original/024b27849c265b3d18a8341187935c82
## I confirm:
- [ ] that I have found an existing compatibility report for this game; creating another one on this post, for I have a different issue.
- [ ] that I have checked whether there are updates for my system available.

Proton log attached.

## Symptoms 

The game installs, but once I open it, it closes immediately. Note that previous yakuza games worked perfectly on my system as well as the rest of my library. I even played AC Origins yesterday.
- The game opens; in some proton versions doesn't even open
- Once the black shows up up with MangoHUD, it closes; most times not even showing the usual Steam rectangle on the right left corner

## Reproduction
- I tried all the protons available on the steam client (not GE)
- Verifiying integrity
- Reinstalled
- Searched online
- I looked on ProtonDB and only one person besides me had the same issue, but he didn't have a solution
- I opened a Reddit post and equally posted a log and was advised to come here
- The user @zephyroths in this post, also seems to have the same problem as I do.

_Originally posted by @LEAL-original in https://github.com/ValveSoftware/Proton/issues/4702#issuecomment-2054029921_
  ### UPDATE
Installed protonGE and ''TKG and still presents the same problem; MangoHUD shows up as normal, moves for a split-second (although still in a black screen) and closes.
Please help. If anyone needs newer logs or so, let me know.

**Comment by LEAL-original** [comment]
I ran it through the terminal and it returned this:
`❯ com.valvesoftware.Steam steam://run/1088710
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
INFO:root:Will set XDG dirs prefix to /home/psel/.var/app/com.valvesoftware.Steam
DEBUG:root:Checking input devices permissions
INFO:root:Overriding TZ to Country
DEBUG:root:Addding /usr/lib/extensions/vulkan/MangoHud/bin to PATH
steam.sh[2]: Running Steam on org.freedesktop.platform 23.08 64-bit
steam.sh[2]: STEAM_RUNTIME is enabled automatically
setup.sh[75]: Steam runtime environment up-to-date!
steam.sh[2]: Steam client's requirements are satisfied
tid(109) burning pthread_key_t == 0 so we never use it
[2024-04-16 13:03:34] Startup - updater built Mar  6 2024 20:27:25
[2024-04-16 13:03:34] Startup - Steam Client launched with: '/home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox' 'steam://run/1088710'
minidumps folder is set to /tmp/dumps
04/16 13:03:34 Init: Installing breakpad exception handler for appid(steam)/version(1709846872)/tid(109)
[2024-04-16 13:03:34] Loading cached metrics from disk (/home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/package/steam_client_metrics.bin)
[2024-04-16 13:03:34] Using the following download hosts for Public, Realm steamglobal
[2024-04-16 13:03:34] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2024-04-16 13:03:34] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2024-04-16 13:03:34] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-04-16 13:03:34] Verifying installation...
[2024-04-16 13:03:34] Verification complete
UpdateUI: skip show logo
Steam logging initialized: directory: /home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xebdce8f0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xebdcd1c0
steamwebhelper.sh[115]: === Tue Apr 16 01:03:35 PM WEST 2024 ===
steamwebhelper.sh[115]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper
CAppInfoCacheReadFromDiskThread took 71 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 264
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
BRefreshApplicationsInLibrary 1: 1ms
BuildCompleteAppOverviewChange: 877 apps
RegisterForAppOverview 1: 28ms
RegisterForAppOverview 2: 29ms
fsync: up and running.
/bin/sh\0-c\0PROTON_LOG=1 /home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1088710 -- /home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/compatibilitytools.d/proton_tkg_experimental.bleeding.edge.9.0.91136.20240415'/proton waitforexitandrun '/home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Yakuza 3/Yakuza3.exe'\0
chdir "/home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Yakuza 3"
ERROR: ld.so: object '/home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameOverlay: started '/home/psel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayui' (pid 1172) for game process 1035
tid(1172) burning pthread_key_t == 0 so we never use it
minidumps folder is set to /tmp/dumps
04/16 13:03:59 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(20240306202747)/tid(1172)
04/16 13:03:59 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(1172)
Game 1088710 created interface STEAMAPPS_INTERFACE_VERSION008 / 
Game 1088710 created interface STEAMAPPTICKET_INTERFACE_VERSION001 / 
Game 1088710 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION014 / 
Game 1088710 created interface STEAMUSERSTATS_INTERFACE_VERSION011 / 
Game 1088710 created interface SteamController007 / 
Game 1088710 created interface SteamController007 / Controller
Game 1088710 created interface SteamInput001 / Controller
Game 1088710 created interface SteamUser017 / User
Game 1088710 created interface SteamUser020 / 
Game 1088710 created interface SteamUser020 / User
Game 1088710 created interface SteamUtils007 / Utils
Game 1088710 created interface SteamUtils009 / 
Game 1088710 created interface SteamUtils009 / Utils
Game 1088710 method call count for IClientControllerSerialized::GetHandleForGamepadIndex : 60
Game 1088710 method call count for IClientRemoteStorage::FileExists : 2
Game 1088710 method call count for IClientRemoteStorage::GetFileSize : 2
Game 1088710 method call count for IClientRemoteStorage::FileRead : 2
Game 1088710 method call count for IClientUserStats::GetAchievementDisplayAttribute : 100
Game 1088710 method call count for IClientUserStats::GetAchievement : 51
Game 1088710 method call count for IClientUserStats::RequestCurrentStats : 1
Game 1088710 method call count for IClientAppManager::GetCurrentLanguage : 8
Game 1088710 method call count for IClientUtils::RecordSteamInterfaceCreation : 14
Game 1088710 method call count for IClientUtils::GetAppID : 19
Game 1088710 method call count for IClientUser::GetAppOwnershipTicketExtendedData : 1
Game 1088710 method call count for IClientUser::GetSteamID : 3
Game 1088710 method call count for IClientUser::BLoggedOn : 1
Uploaded AppInterfaceStats to Steam

(process:1172): GLib-GObject-CRITICAL **: 13:04:04.907: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
reaping pid: 1172 -- gameoverlayui
[2024-04-16 13:05:35] Background update loop checking for update. . .
[2024-04-16 13:05:35] Checking for available updates...
[2024-04-16 13:05:35] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=2595332940
[2024-04-16 13:05:35] Manifest download: send request
[2024-04-16 13:05:35] Manifest download: waiting for download to finish
[2024-04-16 13:05:36] Manifest download: finished
[2024-04-16 13:05:36] Download skipped: /steam_client_ubuntu12?t=2595332940 version 1709846872, installed version 1709846872, existing pending version 0
[2024-04-16 13:05:36] Nothing to do`

**Comment by kisak-valve** [comment]
Hello @LEAL-original, we're using one issue report per unofficially supported game title. Your comment at https://github.com/ValveSoftware/Proton/issues/4702#issuecomment-2054029921 is the better place to discuss how the game is behaving with Proton.

Closing in favor of the game's compatibility report.
