### ISSUE TITLE
Tiny Tina's Wonderlands (1286680)

### ISSUE THREAD

**Issue by meguthe** [ValveSoftware/Proton#7650]
# Compatibility Report
- Name of the game with compatibility issues: Tiny Tina's Wonderlands
- Steam AppID of the game: 1286680

## System Information
- GPU: Radeon RX 7900
- Video driver version: Mesa 24.0.5-arch1.1
- Kernel version: 6.8.6-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/meguthe/f40d17dbed46112c3f4d1fc34173f4a2
- Proton version: experimental-9.0-20240411

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1286680.log](https://github.com/ValveSoftware/Proton/files/15021149/steam-1286680.log)

## Symptoms
No character voice audio plays during the game.

## Reproduction
Start game
Create new character
Opening cut-scene has SFX audio, but no character voice-over audio
Character creation screen also has SFX audio, but no voice-over audio

**Comment by simifor** [comment]
@meguthe Have you tried deleting the prefix and verifying game files? I tried the game on windows and linux and I didn't hear a difference between the two. Voice selection sample in character creation works fine, as do voice overs while progressing through the game.

**Comment by meguthe** [comment]
This turned out to be an issue with my analogue audio output devices. After more research, I found windows users also had this issue. The game plays audio through the center speaker for 5.1 surround, and when 5.1 is selected with a 2.1 system, it won't play any sound for the voice lines. For some reason, my center speaker is just playing the combined sound from my left and right speakers rather than acting as a real 5th speaker. Changing my line out audio to 4.1 temporarily "fixed" it for this game.
