### ISSUE TITLE
The Finals no audio intro screen

### ISSUE THREAD

**Issue by DAUNTIN** [ValveSoftware/Proton#7652]
The Finals
game id:2073850

System 
RTX 4070ti
Nvidia drivers 545.29.06
- Kernel version 6.5.0-27

- Proton version: Proton experimental

No audio on intro screen of the finals, when it says "connecting". after in main screen audio is restored

login to game

**Comment by kisak-valve** [comment]
Hello @DAUNTIN, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7317#issuecomment-2066565421.
