### ISSUE TITLE
Titanfall 2 not launching due to EA Launcher game activation issues

### ISSUE THREAD

**Issue by kernaltrap8** [ValveSoftware/Proton#7654]
# Compatibility Report
- Name of the game with compatibility issues: Titanfall 2
- Steam AppID of the game: 1237970

## System Information
- GPU: AMD RADEON RX570
- Video driver version: Mesa 2.0.279
- Kernel version: 6.8.5-gentoo-dist
- Link to full system information report as [Gist](https://gist.github.com/): [system info](https://gist.github.com/kernaltrap8/ec9a9fd4f2bf41aaf294009603194b4f)
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1237970.log.txt](https://github.com/ValveSoftware/Proton/files/15044878/steam-1237970.log.txt)

## Symptoms 
Upon launching Titanfall 2, once the EA App has been installed in the Proton prefix under `~/.local/share/Steam/steamapps/compatdata/1237970/`, a new window opens asking to enter my EA account details to activate the product. Once I do, it says "Invalid username or password". If i click on "Create new account", it says i dont have an internet connection (when i do). The Sims 4 works just fine, not sure why just Titanfall 2 doesnt. I did try reinstalling Titanfall 2 and the EA App multiple times to no avail. And yes, i did purchase Titanfall 2 via Steam.
![image](https://github.com/ValveSoftware/Proton/assets/94473358/bd24af53-6a9c-40fc-bcea-07a5e0f4567f)

## Reproduction
Launch Titanfall 2 with a fresh Proton prefix

**Comment by kisak-valve** [comment]
Hello @kernaltrap8, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4001#issuecomment-2067181893.
