### ISSUE TITLE
Vulkan/DXVK games spazzing out untill OpenGL game is launched once 

### ISSUE THREAD

**Issue by bpc1** [ValveSoftware/Proton#7655]
## System Information
- GPU:  6700XT
- Video driver version: Mesa 1:24.0.5-1
- Kernel version: 6.8.7-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/bpc1/c45661b71df08fb3f449d9500fbc3e10
- Proton version: Proton Experimental

## Symptoms 
Vulkan/DXVK games when launched after a system reboot have gpu/cpu usage spazzing out unless I run an OpenGL game once

[Video_2024-04-20_16-55-08.webm](https://github.com/ValveSoftware/Proton/assets/56302859/d9c22748-e483-4db6-84f8-01c5c5243d6c)

While checking the logs I've found that these lines keep spamming indefinitely in bad launches while in good launches it only happen 3 times.
```
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR (dynamic: no)
info:    Buffer size:  1920x1080
info:    Image count:  4
info:    Exclusive FS: 1
```
[steam-1086940-bad1.log](https://github.com/ValveSoftware/Proton/files/15048765/steam-1086940-bad1.log)
[steam-1086940-good1.log](https://github.com/ValveSoftware/Proton/files/15048767/steam-1086940-good1.log)
It's a fresh arch install, I've installed all the amd drivers as recommended in the [lutris docs](https://github.com/lutris/docs/blob/master/InstallingDrivers.md)

## Reproduction
1.Reboot
2. Start any Vulkan/DXVK game
3. The bug happens every time
4. Launch any OpenGL game once
5. The bug stops happening

**Comment by kisak-valve** [comment]
Hello @bpc1, Counter-Strike 2 is a Linux native Vulkan game. with it in your set of symptoms, you've removed both DXVK and Proton from your differential diagnosis.

Report this issue to your video driver vendor.
