### ISSUE TITLE
Antenna (443580)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#7663]
# Compatibility Report
- Name of the game with compatibility issues: Antenna 
- Steam AppID of the game: 443580

## System Information
- 1 TB OLED Steam deck LE 
- Proton version: Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game does not render on latest Experimental on deck, dropping to 5.13-6 fixes it.
[steam-443580.log](https://github.com/ValveSoftware/Proton/files/15088061/steam-443580.log)

## Reproduction
Launch the game on any version past 5.13-6

**Comment by kisak-valve** [comment]
Hello @waspennator, there's multiple years of development between the current build of Proton Experimental and Proton 5.13. Please note the oldest version you tested that shows the regression.

**Comment by waspennator** [comment]
> Hello @waspennator, there's multiple years of development between the current build of Proton Experimental and Proton 5.13. Please note the oldest version you tested that shows the regression.

6.3-8 is when the regression started showing

**Comment by waspennator** [comment]
Renders now on proton Experimental, but gets stuck visually on the loading screen at a certain percentage.

**Comment by waspennator** [comment]
Issue has been resolved, game is now ready for deck testing.
