### ISSUE TITLE
A Raven Monologue (744810)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#7664]
# Compatibility Report
- Name of the game with compatibility issues: A Raven Monologue
- Steam AppID of the game: 744810

## System Information
- 1 TB OLED Steam Deck LE 
- Proton version: Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game does not render on Deck with Experimental, game last rendered on 5.13-6.
[steam-744810.log](https://github.com/ValveSoftware/Proton/files/15088548/steam-744810.log)

## Reproduction
Start the game on any version above 5.13-6

**Comment by kisak-valve** [comment]
Hello @waspennator, similar to another recent compatibility report, it would be useful to note the closest Proton versions (that are easily testable) between the working and regressed states.

**Comment by waspennator** [comment]
6.3-8 was when the regression showed up.

**Comment by waspennator** [comment]
Latest bleeding edge seems to make the game render now, same for #7663, however it seems like both games now get stuck on a singular frame now compared 5.13-6.

I also believe #7665 will likely have the same issue whenever the fix gets added for it.

[steam-744810.zip](https://github.com/ValveSoftware/Proton/files/15194539/steam-744810.zip)

**Comment by waspennator** [comment]
Still the same now that the fixes have hit regular Experimental. Game seems to get visually stuck on a white screen with a logo.

**Comment by waspennator** [comment]
Issue has been fully resolved and game is playable from start to finish on deck, highly recommend game be bumped up to playable now on deck.
