### ISSUE TITLE
Banyu Lintar Angin - Little Storm - (744800)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#7665]
# Compatibility Report
- Name of the game with compatibility issues: Banyu Lintar Angin - Little Storm -
- Steam AppID of the game: 744800

## System Information
- 1 TB OLED Steam deck LE 
- Proton version: Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game does not render past 5.13-6 on deck
[steam-744800.log](https://github.com/ValveSoftware/Proton/files/15089768/steam-744800.log)

## Reproduction
Launch game past 5.13-6

**Comment by waspennator** [comment]
Regression shows on 6.3-8 and above

**Comment by waspennator** [comment]
Gane still renders to a black screen with Experimental proton.

Edit: Still present with today's proton Experimental build, apparently the game was made by the same devs of #7664, so maybe the same fixes would work here?

**Comment by waspennator** [comment]
Sorry for the double post, but I can now confirm that forcing "--use-angle=d3d9" makes the game render visually, combined with the latest proton Experimental build makes it work finally.

Would it be possible for this to be added into proton like Antenna and A Ravens Monologue did?

**Comment by waspennator** [comment]
@Gofman
Sorry for the ping but I just wanted to ask again, could the "--use-angle=d3d9" workaround be added in for this game like it was for A Raven Monologue and Antenna? I can confirm it makes the game work on proton Experimental and it's the only thing that's keeping me from being able to finally close this report?

Edit: Retested to check, the game is fully playable from start to finish with it. The game will also launch to a black screen without it.

**Comment by gofman** [comment]
> @gofman Sorry for the ping but I just wanted to ask again, could the "--use-angle=d3d9" workaround be added in for this game like it was for A Raven Monologue and Antenna? I can confirm it makes the game work on proton Experimental and it's the only thing that's keeping me from being able to finally close this report?

Thanks for the pointer, I added a bit different workaround ("--disable_direct_composition=1") to Proton Experimental [bleeding-edge] hopefully with the same result.

**Comment by waspennator** [comment]
> > @gofman Sorry for the ping but I just wanted to ask again, could the "--use-angle=d3d9" workaround be added in for this game like it was for A Raven Monologue and Antenna? I can confirm it makes the game work on proton Experimental and it's the only thing that's keeping me from being able to finally close this report?
> 
> Thanks for the pointer, I added a bit different workaround ("--disable_direct_composition=1") to Proton Experimental [bleeding-edge] hopefully with the same result.

I can confirm the game is now fully playable on my oled with Experimental bleeding edge proton. Once this fix hits regular Experimental, I'll close this and both this game and A Ravens Monologue can be bumped up to playable on deck.

**Comment by waspennator** [comment]
Closing since fix hit regular Experimental proton.
