### ISSUE TITLE
Doom & Destiny Advanced (361040)

### ISSUE THREAD

**Issue by at46** [ValveSoftware/Proton#7670]
# Compatibility Report
- Name of the game with compatibility issues: Doom & Destiny Advanced
- Steam AppID of the game: 361040

## System Information
- GPU: RX6600
- Video driver version: Mesa 23.3.5
- Kernel version: 6.3.7
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/at46/51134de8e41a8aa24351b8a47a1344f4
- Proton version: 8.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
edit: There is a linux version which does not work at all for me. But the game works fine with proton 7.0-6 and proton 8.0-5. 

## Reproduction
just click on play

**Comment by simifor** [comment]
@at46 While the game doesn't mention having linux support, it has linux depots, so when you click play without configuring anything else it'll try to use that depot and fail. From my testing, proton 8 works, it just won't be used by default. If you explicitly set steam to use proton 8 to run the game, does it work for you?

**Comment by at46** [comment]
> @at46 While the game doesn't mention having linux support, it has linux depots, so when you click play without configuring anything else it'll try to use that depot and fail. From my testing, proton 8 works, it just won't be used by default. If you explicitly set steam to use proton 8 to run the game, does it work for you?

Thanks @simifor. You are right. I accidentally used the linux verssion instead of proton 8.0. Can confirm that it works fine for me also now with proton 8.0-5.
@kisak-valve you can remove the regression flag or close the issue. Sorry for the wrong report.

**Comment by kisak-valve** [comment]
Hello @at46, that makes your primary issue one with the Linux native variant of the game and no remaining details related to the Proton compatibility layer.

Issues with the Linux native variants of games should be reported directly to the game's dev(s).
