### ISSUE TITLE
Spatial Audio Support

### ISSUE THREAD

**Issue by AndreH1009** [ValveSoftware/Proton#7672]
I notice that certain Steam Games like Shadow of the Tomb Raider or FF15 offer the option of "spatial audio". The setting is supposed to check the system for it's surround configuration, and output Dolby Atmos, if there is an Atmos system connected. According to the description this setting uses Windows Sonic Spatial audio. On linux I used Proton to have this setting available but on my Smyth A16 I only receive regular 8 channel PCM audio. That means the feature is not implemented yet via Proton. I would hereby kindly suggest to implement it such that we can enjoy Dolby Atmos for supported games on Linux.

**Comment by kisak-valve** [comment]
Hello @AndreH1009, this is functionally the same issue as #6138. Closing as a duplicate.
