### ISSUE TITLE
EA friends not showing up

### ISSUE THREAD

**Issue by legoraft** [ValveSoftware/Proton#7677]
# Compatibility Report
- Name of the game with compatibility issues: It Takes Two
- Steam AppID of the game: 1426210

## System Information
- GPU: AMD Radeon RX 570 4GB
- Video driver version: amdgpu
- Kernel version: 6.8.0-76060800daily20240311-generic
- Link to full system information report as Gist: [system report](https://gist.github.com/legoraft/8f878d305a44dddc1bcb5f8df89ea0e4)
- Proton version: experimental-9.0-20240419b

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Game launch log: 
[steam-1426210.log](https://github.com/ValveSoftware/Proton/files/15141921/steam-1426210.log)

## Symptoms 
Launching the game goes perfectly, but when trying to play in online mode with another computer, my account doesn't show   up as online for the other player (who uses windows). My own in game overlay also doesn't show any friends, even though both players are friends within the ea app (checked this by running ea app through proton).

My EA account is linked to my steam account and this worked flawlessly a few months ago. I've tried removing and re-adding friends, running proton 8.0-5 and 7.0-6 and reinstalling the full game. None of which worked.

## Reproduction
1. Launch It Takes Two from the steam library on both computers
2. Once launched, go to online play and press 'invite friend'
3. No friends show up, even though they're added and show up in the normal ea app
4. Try to send a friend request (from linux computer) with the ingame overlay (press Shift + F1)
5. Friend request sometimes arrives on the other (windows) computer, but nothing happens when accepted.
6. Sending friend requests the other way won't work because player is already added.

**Comment by kisak-valve** [comment]
Hello @legoraft, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4696#issuecomment-2081482973.
