### ISSUE TITLE
Cannot capture frame with AMD properitary driver

### ISSUE THREAD

**Issue by GinShio** [ValveSoftware/Proton#7678]
## Description

Hi,
Running the game *The Talos Principle 2* under Proton is okay. Either RADV or AMD proprietary driver.
When I run with Renderdoc, **RADV is okay**. But failed to start with AMD proprietary driver.

command follow as below (ref: #7260):
```shell
ENABLE_VULKAN_RENDERDOC_CAPTURE=1 %command%
```

Error Message as below:
```text
DirectX 12 is not supported on your system. Try running without the -dx12 or -d3d12 command line argument.
```
![image](https://github.com/ValveSoftware/Proton/assets/38715657/e8925d28-c1ac-4ff6-82fe-7bc9d377e7f5)

## Steps to reproduce

1. Use AMD proprietary driver
2. Setup the game *The Talos Principle 2* properties
    a. Set Launch options to `ENABLE_VULKAN_RENDERDOC_CAPTURE=1 %command%` in General
3. Run the game *The Talos Principle 2*

## Environment

 + RenderDoc Version: x64 v1.31
 + Operating System: openSUSE Tumbleweed x86_64, Linux 6.8.7-1-default
 + Graphics API: Vulkan
 + API Version: 1.3.283
 + Proton Version: 8.0-5
 + GPU: AMD RX 6600XT (Navi23)
 + Driver Info: AMD Proprietary Driver

## Log

[proton-log.zip](https://github.com/ValveSoftware/Proton/files/15142159/proton-log.zip)

**Comment by kisak-valve** [comment]
Hello @GinShio, https://github.com/baldurk/renderdoc/issues/3298#issuecomment-2071679693 is equally valid here as over there.

**Comment by GinShio** [comment]
Sorry. Please lock it too.
