### ISSUE TITLE
Counter Strike 2 running on Steam Linux Runtime 3.0 (Sniper) for some reason.

### ISSUE THREAD

**Issue by Billue69** [ValveSoftware/Proton#7681]
Hi, I really like CS2 and it is native on Linux but for some reason my CS2 is running on proton from what I can observe. I noticed it after I started to notice bad mouse behavior only on CS2(Apex legends on Proton experiment experienced no issue and L4D2 has no issue as well which is Linux native), and by that I mean that right, middle and left click randomly, for random amount of time just stop registering completely. 

I don't remember if it started after an update or it was always there but it is very annoying as I am a weak target in this game with this glitch. I started using the revolver as it has a delayed shot so before engaging in a fight, I keep clicking to see if the gun will fire without actually firing it to see if my mouse is registering clicks so I at least *hopefully* I can kill my opponent.  Also I believe this glitch happens in both game play and in the menu but I can't truly confirm the menu as there isn't a big visual, nor do I spend too much time there.

Also. mouse tracking, performance and keyboard works flawlessly during that time, in other words I can still move and aim at player, just I can't kill them. The glitch is very random(sometimes I go a few rounds without experiencing anything and other times it happens repeatably during rounds making the game unplayable)

I am not sure if Proton is causing this, if CS2 is running on Proton or that CS2 does not like my mouse. All I know is that there should not be a message saying that CS2 is running via steam play and it is selected by Valve testing(whatever that means, see the image below).

![image](https://github.com/ValveSoftware/Proton/assets/129647390/ee562bf6-751b-408b-b3bc-cb847dac0f4b)

Any help or diagnostics will be appreciated as I do want to play this game.
Thank you.

- Computer Information:
Manufacturer: ASUSTeK COMPUTER INC.
Model: TUF GAMING X570-PRO (WI-FI)
Form Factor: Desktop
No Touch Input Detected

- Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 5 5600G with Radeon Graphics
CPU Family: 0x19
CPU Model: 0x50
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 4200 MHz
12 logical processors
6 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported

- Operating System Version:
Debian GNU/Linux trixie/sid (64 bit)
Kernel Name: Linux
Kernel Version: 6.6.15-amd64
X Server Vendor: The X.Org Foundation
X Server Release: 12101011
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20240304.79797

- Video Card:
Driver: AMD AMD Radeon RX 6600 XT (radeonsi, navi23, LLVM 17.0.6, DRM 3.54, 6.6.15-amd64)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.3.5-1
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 164 Hz
VendorID: 0x1002
DeviceID: 0x73ff
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.91" x 11.77" (23.98" diag), 53.1cm x 29.9cm (60.9cm diag)
Primary VRAM: 8192 MB

- Sound card:
Audio device: ATI R6xx HDMI

-Memory:
RAM: 31882 Mb

- VR Hardware:
VR Headset: None detected

-Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 372469 MB
Largest Free Hard Disk Block: 107981 MB

- Storage:
Number of SSDs: 3
SSD sizes: 1024G,1000G,480G
Number of HDDs: 0
Number of removable drives: 0

**Comment by kisak-valve** [comment]
Hello @MomSlayerGX, the Linux native variant of Counter-Strike 2 is intended to run in the Steam Linux Runtime container environment and that is unrelated to Proton.
