### ISSUE TITLE
Fallout 4: Next Gen Update Gui Scaling Issues on Alternate Screen Sizes (377160)

### ISSUE THREAD

**Issue by deathmarine** [ValveSoftware/Proton#7682]
# Compatibility Report
- Name of the game with compatibility issues: Fallout 4
- Steam AppID of the game: 377160

## System Information
- GPU: Steam Deck (AMD Custom GPU 0405)
- Video driver version: Steam Deck 
- Kernel version: Steam Deck 6.1.52-valve16-1-neputune-61
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 8.0.5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Logs attached.
[steam-377160.log](https://github.com/ValveSoftware/Proton/files/15153729/steam-377160.log)

## Symptoms 
The UI within the game does not appear to be scaled correctly when the Steam Deck is connected to a different screen. I'm assuming this is due to the window in which the application is running as changes the fallout4perf.ini have no affect. 

## Reproduction
Connect Steam Deck to an external screen with any USB-C port replicator or dock.
Open vanilla Fallout 4 with latest updates. Controller Optional.
Menu is skewed slight down post loading screens. Menus in game are no longer visible will add screen shots.
![20240429104438_1](https://github.com/ValveSoftware/Proton/assets/1166193/fb3427bf-1ed5-4aff-a7d2-cabb09ac27d4)

**Comment by kisak-valve** [comment]
Hello @deathmarine, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/308#issuecomment-2083479716.

**Comment by deathmarine** [comment]
> Hello @deathmarine, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#308 (comment)](https://github.com/ValveSoftware/Proton/issues/308#issuecomment-2083479716).

Wait Steam Verified is not supported?
