### ISSUE TITLE
VRAM consumption on Proton Experimental

### ISSUE THREAD

**Issue by Skote2** [ValveSoftware/Proton#7685]
I am playing Forzo Horizon 4 on my arch desktop with a Ryzen 2600 and Fury X. Compared to the pinnned 8.0-5 release experimental is maxing out my 4GB of VRAM in Forza. The pinned 8 release is using only 2.8GB of VRAM on minimum settings. On high (dynamic) it's consuming 3.6GB. just my KDE 6 Wayland desktop is running behind it, taking around 800MB of VRAM. High settings on experimental we're still just maxed out and failing to draw textures.

**Comment by kisak-valve** [comment]
Hello @Skote2, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4667#issuecomment-2087758861.
