### ISSUE TITLE
Mafia broken since proton-5.13-6 and above

### ISSUE THREAD

**Issue by stsp** [ValveSoftware/Proton#7687]
# Compatibility Report
- Name of the game with compatibility issues:
Mafia (Lost Heaven)

- Steam AppID of the game:
40990

## System Information
- GPU: 
[AMD/ATI] RS780L [Radeon 3000]

- Video driver version: 
mesa-24.0.5

- Kernel version: 
6.9.0-rc4

- Link to full system information report as [Gist](https://gist.github.com/):
I don't think it is relevant.

- Proton version:
5.0-10 is the last version where the game works fine.
5.13-6 is the first broken version.

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

I don't think the logs are relevant.

## Symptoms 
Symptoms depends on a proton version in use.
On latest proton-experimental, the problem is
that the keyboard controls have something like
30 seconds lag, so the game is uncontrolable.
But that depends on a situation, eg in menus
the controls are good. But in the game itself,
the character reacts to a key-press something
like 30 seconds later.

## Reproduction
Run the game and start playing. Try to control
the character or drive the car - you can't.

**Comment by kisak-valve** [comment]
Hello @stsp, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2812#issuecomment-2088390429.

**Comment by stsp** [comment]
But please note that its a regression.
Shouldn't the regressions be handled
on a fast-track?
