### ISSUE TITLE
Support for multiseat environment

### ISSUE THREAD

**Issue by latykud** [ValveSoftware/Proton#769]
I have a multiseat setup on my home computer and encountered a limiting issue. The naming convention of running scripts of proton (proton_run etc.), created in /tmp/, does not specify or differ a user for which those scripts are created. The result is that only one user can use Proton on given machine at a time. Plus, if any other user wants to use it, he has to remove running scripts that were created for the first user.

Is there any plan on adding support for multiseat rigs?

**Comment by aeikum** [comment]
The /tmp/ issue is fixed in the Beta version. Note that you may run into issues if you have a common Steam library shared between users. This isn't recommended.

**Comment by latykud** [comment]
That is great to hear, thank you. As for shared libraries, this is not the case in my example, both users have their own. Will try it out the moment I'm back home.
