### ISSUE TITLE
RAGE 2 Crashing on TAB menu

### ISSUE THREAD

**Issue by Shadow-Hunt3r** [ValveSoftware/Proton#7692]
# Compatibility Report
- Name of the game with compatibility issues: RAGE 2
- Steam AppID of the game: 548570

## System Information
- GPU: NVIDIA GeForce MX450
- Video driver version: NVIDIA 535.171.04
- Kernel version: 5.15.0-105-generic
- Link to full system information report as [Gist](https://gist.github.com/): [Full System Info](https://gist.github.com/Shadow-Hunt3r/0229f458a8ba4c18d416b38657696e53.js)
- Proton version:(Tested the bug on) Experimental, 9.0-1, 8.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Experimental - [steam-548570.log](https://github.com/ValveSoftware/Proton/files/15203907/steam-548570.log)
9.0-1 - [steam-548570.log](https://github.com/ValveSoftware/Proton/files/15203910/steam-548570.log)
8.0-5 - [steam-548570.log](https://github.com/ValveSoftware/Proton/files/15203917/steam-548570.log)

## Symptoms 
Game hard crashes to a point where it shows last frame(of whatever you had loaded in the TAB menu) and to close it regardless of windowed, fullscreen or borderless you have to switch to the steam launcher and force stop the game

## Reproduction

1. Install RAGE 2 with any of the 3 proton versions I mentioned above
2. Run the game
3. Open TAB menu, this crash seems to occur a lot when in the wilderness, or mission zones

## Additional Notes
I have also attempted using protontricks, but to no change, then I tried using Virtual Desktop with the aid of WineCFG* to enable it, the frequency of the crashes dropped marginally however

*Along with the marginal change it gave it also worsened the preformance and added audio tearing in fullscreen mode, with windowed and borderless showed better results, those being much less audio tearing and better preformance along with decreasing the frequency of the crashes

**Comment by kisak-valve** [comment]
Hello @Shadow-Hunt3r, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2686#issuecomment-2093608445.
