### ISSUE TITLE
Games refuse to launch at all with NVIDIA drivers 550.76->550.78 update

### ISSUE THREAD

**Issue by 413x1nkp** [ValveSoftware/Proton#7695]
As of today the issue i've noticed with ALL of my games is that none of them work! Literally yesterday every one of them at least launched, but now none of them do...
That is, if i use Proton. If a game is linux-native, then it launches and works fine. However, due to some unspoken rules of gamedev, linux-native versions of the same game work two or three times worse compared to running the windows version using Proton.

I've mentioned this issue prior, here's the elaborate comment on it: https://github.com/ValveSoftware/steam-for-linux/issues/10842#issuecomment-2094000000

In the list of games that are affected by this issue you can add my whole steam games library (excluding the games that have linux-native versions available).

EDIT: As it turns out - launching the same game's EXEs with wine works, even if games are a **LOT** laggier. At least they launch...
Now the question is.. Why is that?

[Full Steam Runtime Diagnostics log](https://gist.github.com/alexlnkp/640175854344ab8402164431e0b249fc)

**Comment by kisak-valve** [comment]
Hello @alexlnkp, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by 413x1nkp** [comment]
Seems like there was a broken dependency or something of that sort, the issue is kind of fixed now.
But still, looking through the log produced by steam runtime diagnostics it does seem to error out in some places, even if it does launch.

Still, going to mark this as solved for the time being
