### ISSUE TITLE
Weird timestamp in GuildWars 2

### ISSUE THREAD

**Issue by Coolgeek789** [ValveSoftware/Proton#7699]
My system :
OS : Archlinux
CPU : Intel 13900KF
GC : RTX 4080 (driver nvidia 550.78)
Kernel : 6.8.9-arch1-1
Desktop : KDE 6
Language : French (fr_FR.UTF-8)

Since Proton 8 (still the case in Proton 9 and current git), I have a weird issue in Guildwars 2 (AppID : 1284210).
In the chat, I have the timestamp displayed in a weird way (the part in gray, at the beginning of the line):

![GW2 after](https://github.com/ValveSoftware/Proton/assets/34242863/61496512-0040-4ecf-b1cf-13d1914780f6)
(translation : 7h22 of the afternoon)

In Proton 7 (the way it is on Windows) :

![GW2 before](https://github.com/ValveSoftware/Proton/assets/34242863/567d53bf-58c6-40da-85e4-1f4cb85e7b71)

I tried to set LC_TIME=C and LC_ALL=C in the launch command in Steam but there was no change.
Current launch command : DXVK_ASYNC=1 %command% -ignorecoherentgpucrash -provider Portal

I tracked down the commit that does it : https://github.com/ValveSoftware/Proton/commit/2b95bc1771194a59204104ddc475739858fe5cb3

Removing it does the trick.

Is there a way to fix this ?

Thanks

**Comment by kisak-valve** [comment]
Hello @Coolgeek789, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6547#issuecomment-2094346806.
