### ISSUE TITLE
Simcity 4 deluxe (24780)

### ISSUE THREAD

**Issue by Eucalyptus90** [ValveSoftware/Proton#7703]
# Compatibility Report
- Name of the game with compatibility issues: Simcity4 Deluxe
- Steam AppID of the game: 24780

## System Information
- GPU: Intel Mesa Intel(R) HD Graphics 520 (SKL GT2)
- Kernel version: Ubuntu 22.04.4
- Proton version: all (last tried with Proton experimental)

## Symptoms 
When I launch the game, a window appears, an disappears immediately. The launching button then returns to "play".

[steam-24780.log](https://github.com/ValveSoftware/Proton/files/15211050/steam-24780.log)

**Comment by kisak-valve** [comment]
Hello @Eucalyptus90, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/453#issuecomment-2094423553.
