### ISSUE TITLE
Proton gaming not working

### ISSUE THREAD

**Issue by JustCauseWhyNot** [ValveSoftware/Proton#7705]
Proton-9.0-1, Proton-8.0-5, GE-Proton-9.{2,4}. I've tested this behavior with squad, warthunder, and hell let loose. Here's my [steam-runtime](https://paste.gentoo.zip/qEjIA2oD). The best way I can describe the issue is that my system freezes when the games window is focused. It doesn't actually freeze, but the time between frames/inputs is measured in tens of seconds. It's like my gpu isn't being used at all. I truly don't know why, but it's only a proton issue I've had. I can play native games just fine.

**Comment by kisak-valve** [comment]
Hello @JustCauseWhyNot, this is a blind guess, but can you temporarily move/remove/disable `VK_LAYER_FROG_gamescope_wsi_x86_64`, `VK_LAYER_LFX_LatencyFleX` (both of them), `VK_LAYER_MANGOHUD_overlay_x86_64`, and `VK_LAYER_VKBASALT_post_processing` and retest so that they can be excluded as potential factors. If that helps, then re-adding them one at a time might give you a hint to ponder.

**Comment by JustCauseWhyNot** [comment]
Those all should've been disabled while testing. Ik gamescope, and latencyflex weren't used. I've tested with vkbasalt, and mangohud disabled. While it does help a smidge it doesn't fix the issue.
If I wanted to disable those would I be able to with launch options?

**Comment by JustCauseWhyNot** [comment]
Here's a link to the [steam-log](https://paste.gentoo.zip/byQ0jmSX) of running warthunder through 8.0-5, and with as much confidence as I can have in making sure all those layers are disabled.

**Comment by JustCauseWhyNot** [comment]
It's still broken after doing a lot of updating of my system. Here's my [steam-236390.log](https://paste.gentoo.zip/c7Yc3liJ), and [steam-runtime](https://paste.gentoo.zip/8Hsa91TL). I've disabled vkbasalt in launch options, and the other three aren't showing in steam-runtime. Here's my launch options aswell `PROTON_LOG=1 ENABLE_VKBASALT=0 WINEDEBUG=-all %command%`

**Comment by JustCauseWhyNot** [comment]
I found it's not a wine issue. I emerged wine-proton, and it ran what I wanted without issue. I know now it's either a steam, or proton issue.

**Comment by Flygrounder** [comment]
I might have the same issue. Whenever the game window is focused, it is just static with rare frame updates. But when I hold alt+tab and Plasma window switching menu pops up, game renders as normal. Should I stop alt-tabbing, it is stuck again.

[My steam runtime](https://pastebin.com/heDDDf24).

**Comment by JustCauseWhyNot** [comment]
Sounds like the same issue I have. Only thing is I'm using dwm not kde so I'm not alt-tabbing. But I do think the game actually runs normally as far as I can tell when I'm not focusing it.

**Comment by Flygrounder** [comment]
I've tried running the game using i3 window manager and have the same issue. If I open dmenu, game renders fine as long as it is open. As soon as I close dmenu, the game freezes again.

**Comment by Flygrounder** [comment]
Interesting thing is that not all games with proton have this issue. I've tested The Elder Scrolls Online, Diablo IV and Braid: Anniversary Edition. ESO runs without issues, while Diablo and Braid have this problem.

**Comment by JustCauseWhyNot** [comment]
I found cs2 with proton didn't have this issue, until I changed graphics setting

**Comment by Flygrounder** [comment]
Found a [workaround](https://wiki.archlinux.org/title/Steam/Troubleshooting#Some_games_freeze_at_start_when_in_focus). Disabling ForceFullCompositionPipeline in nvidia settings fixes an issue for me.

**Comment by JustCauseWhyNot** [comment]
Unfortunately for me I already have `ForceFullCompositionPipeline` Disabled.

**Comment by JustCauseWhyNot** [comment]
Wait it's working. I had it accidentally on in xorg.conf, but nvidia-settings wasn't reporting it being on so I thought those had settings weren't making any impact. I disabled those, and were gaming again.

**Comment by JustCauseWhyNot** [comment]
Its https://github.com/ValveSoftware/Proton/issues/6869 this issue that is mine. I'll close this
