### ISSUE TITLE
Batman: Arkham Asylum, Failed to compile global shader

### ISSUE THREAD

**Issue by thenumber8equalsign** [ValveSoftware/Proton#7706]
# Compatibility Report
- Name of the game with compatibility issues: Batman: Arkham Asylum GOTY Edition
- Steam AppID of the game: 35140

## System Information
- GPU:  RX 6750XT
- Video driver version:  4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
OpenGL Version: 4.6
- Kernel version:  5.15.0-91-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/thenumber8equalsign/27314ab23a046454816cf9ade8a6a5b8
- Proton version: Proton Expiremental

## I confirm:
- [y] that I haven't found an existing compatibility report for this game.
- [y] that I have checked whether there are updates for my system available.

[steam-35140.log](https://github.com/ValveSoftware/Proton/files/15214304/steam-35140.log)

## Symptoms 
The game starts, then there is a message that says, "Failed to compile global shader", then the game closes.
## Reproduction
1. Launch the game
2. Click play

**Comment by kisak-valve** [comment]
Hello @thenumber8equalsign, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/421#issuecomment-2094951634.
