### ISSUE TITLE
Apex Legends (1172470)

### ISSUE THREAD

**Issue by westlyroots** [ValveSoftware/Proton#7708]
# Compatibility Report
- Name of the game with compatibility issues: Apex Legends
- Steam AppID of the game: 1172470

## System Information
- GPU: RX 6700 XT
- Video driver version: mesa 24.0.6-2
- Kernel version: 6.8.7-273-tkg-echo
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/red-star-fighter/99bf29be4c330050b5de18a5f5c8e5a2
- Proton version: Proton 9.0-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1172470.log](https://github.com/ValveSoftware/Proton/files/15239337/steam-1172470.log)
## Symptoms 
- Initial EAC Launcher runs
- EAC launcher closes as game attempts to start
- game silently crashes

## Reproduction
- Use any proton version
- Launch the game

**Comment by kisak-valve** [comment]
Hello @red-star-fighter, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-2099036989.

**Comment by Cubuss** [comment]
i tried swapping to default weapon skins but it still freezes?
