### ISSUE TITLE
Unreal Editor for Fornite: Menu disappear (Proton 9+ - GE Proton 8+)

### ISSUE THREAD

**Issue by mrdev023** [ValveSoftware/Proton#7713]
Proton 9.0-1

Run with PROTON_HIDE_NVIDIA_GPU=0 PROTON_ENABLE_NVAPI=1 VKD3D_CONFIG=dxr12 %command%

https://drive.google.com/file/d/1QLO_xkxr8LWnw4N2KUhsITo0kq1Ojicw/view?usp=sharing

https://bugs.winehq.org/show_bug.cgi?id=56654

**Comment by kisak-valve** [comment]
Hello @mrdev023, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7712#issuecomment-2101032632.
