### ISSUE TITLE
winevulkan/loader_thunks.c error

### ISSUE THREAD

**Issue by LuxLucian** [ValveSoftware/Proton#7714]
I keep getting this error while playing certain games. The two I've had issue with so far are Skyrim SSE and Darktide. I'm running EndeavorOS, up to date and using vulkan radeon drivers.
Hardware is an AMD 3600 CPU and a 5700 XT GPU. Wine versions were GE, 9.0, and 8,0.
![image](https://github.com/ValveSoftware/Proton/assets/63475999/7a6e5ce9-4935-4306-a512-ffd44fd6d901)

**Comment by LuxLucian** [comment]
Looking into it this seems to be related to GPL and Skyrim SSE ENB, I'll look into it and open an issue in the right section. I got past it with  
RADV_DEBUG=nogpl
and setting
EnableTerrainBlending=false
in enbseries.ini

I am still dealing with crashes however.

**Comment by j0ri500** [comment]
@LuxLucian I have the same error with the game Hunt: Showdown. How did you fix the problem?

**Comment by palko444** [comment]
same issue for any game using vulkan

**Comment by LuxLucian** [comment]
> @LuxLucian I have the same error with the game Hunt: Showdown. How did you fix the problem?



> same issue for any game using vulkan


I spent some time digging and it seems related to the 6.8.9 kernel, downgrading to 6.8.8 solved all my issues. This applied to both the Zen kernel and the LQX kernel.
Sorry I forgot about this post after I solved it.

**Comment by julian-siebert** [comment]
Having same issues with another Game

**Comment by julian-siebert** [comment]
Fedora Update took my Kernel version to 6.8.9.

**Comment by helpvisa** [comment]
Still experiencing this issue on Fedora 40 and Hunt: Showdown using Proton 9.0-1 with the 6.9.7 kernel and also with the 6.6.37 longterm kernel from kwizart's COPR repo.

Hardware details as follows:
- AMD Ryzen 3600XT
- Nvidia 3060ti (on Wayland session with proprietary 555.58.02 drivers)

Possibly this is related to the Wayland session? Haven't had a chance to test on Xorg yet; crashing seems to occur randomly after a period of about 25-40 minutes of continuous play. May also test using Nouveau.

My error is also slightly different, but seemingly still related to Vulkan:
![image](https://github.com/ValveSoftware/Proton/assets/89664809/3a4630ff-a3f3-4515-b584-0bfa36001a5c)

**Comment by kisak-valve** [comment]
Hello @helpvisa, the issue that was reported here ended up being an AMDGPU kernel module issue that was tracked at https://gitlab.freedesktop.org/drm/amd/-/issues/3343. The `loader_thunks.c` error message can not be generalized between different drivers. Please add a note to the compatibility report of the game you're seeing the issue with.
