### ISSUE TITLE
Wot not works

### ISSUE THREAD

**Issue by VitZayko** [ValveSoftware/Proton#7716]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:  1407200

## System Information
- GPU: Intel HD + RTX 2060
- Video driver version: 
- Kernel version: 550
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: any

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[Uploading steam-1407200.log…]()

**Comment by VitZayko** [comment]
arch KDE (both X11 and Wayland)

**Comment by kisak-valve** [comment]
Hello @VitZayko, we're using one issue report per unofficially supported game title. Usually I'd transfer this issue report to the preexisting compatibility report, but there's no actionable details here. Please add a note with your findings to #1369.
