### ISSUE TITLE
Crash Error: Assertion failed - winevulkan/loader_thunks.c   Game: A Plague Tale: Requiem

### ISSUE THREAD

**Issue by Allie55** [ValveSoftware/Proton#7720]
Hello!  I am having an issue loading up the game A Plague Tale: Requiem.   The game crashes after loading with this error popup. 
![image](https://github.com/ValveSoftware/Proton/assets/169485830/28e298cd-9a37-4649-99c6-7a6f86183ec0)

**Setup**
GPU:   RX 7900 XTX 
OS: Arch with KDE Plasma (Wayland)
GPU Drivers: Vulkan-radeon

**Issue**
Purchased the game yesterday.  Game loads up and crashes on initial load before getting to the main menu.  I have been able to get into the main menu a few times with some of the troubleshooting changes but the game will produce the same error and crash while loading into a new game. 

**Proton Versions**
        Proton Experimental
        GE-Proton 9-4
        9.0-1
        8.0-5
        7.0-6 (doesnt even start up the game)
        
**Troubleshooting**
Reinstalled
Different graphic options and frame rate options
Tried amdvlk drivers
Tried switching from Wayland to X11
Tried different Proton Versions as listed above
Tried various different launch options (including DirectX11) none seem to have any noticeable effect.
Tried on husbands computer who has identical setup except runs an Nvidia GPU - game loads up just fine for him

None of these attempts have made any difference. Game continues to crash with the same error.  If anyone has an suggestions for me or other ideas to try I would greatly appreciate it. Thank you so much.

**Comment by kisak-valve** [comment]
Hello @Allie55, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to the pre-existing compatibility report for the game at #6241, but it's highly likely that this specific issue is a kernel regression which was tracked at https://gitlab.freedesktop.org/drm/amd/-/issues/3343.

A quick workaround would be to reboot into an older kernel (6.6.30 does not count as older) until this is resolved upstream, most likely some time next week. If that doesn't work, then please add a note to the compatibility report for the game.

**Comment by Allie55** [comment]
Thank you so much.  In all my searches these links never popped up. I appreciate your time and for linking those for me.
