### ISSUE TITLE
Horizon Forbidden West starts and crash immediately

### ISSUE THREAD

**Issue by Paincho** [ValveSoftware/Proton#7724]
# Compatibility Report
- Name of the game with compatibility issues:Horizon Forbidden West
- Steam AppID of the game:2420110

## System Information
- GPU:AMD Radeon RX 7800 XT
- Video driver version: 
- Kernel version:6.8.9-300.fc40.x86_64 (64-bit)
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/Paincho/35cde189a10221743250a11bdff2c4a4
- Proton version:Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2420110.log](https://github.com/ValveSoftware/Proton/files/15283034/steam-2420110.log)

## Symptoms 
Game was playing with no issue yesterday but today it starts and crashes immediately
Game creates a memory dump to send to sony 
[Horizon Forbidden West Complete Edition.log](https://github.com/ValveSoftware/Proton/files/15283047/Horizon.Forbidden.West.Complete.Edition.log)
15:52:29:635 (00000296) > [Crash] Unhandled exception at address 0x00000000ffb0a459 (code: 0xc0000005): "Access violation"
This line seems to be the issue but I don't really know how to solve this...

**Comment by kisak-valve** [comment]
Hello @Paincho, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to the pre-existing compatibility report for the game at #7590, but it's highly likely that this specific issue is a kernel regression which was tracked at https://gitlab.freedesktop.org/drm/amd/-/issues/3343.

A quick workaround would be to reboot into an older kernel until this is resolved upstream, most likely some time next week. If that doesn't work, then please add a note to the compatibility report for the game.
