### ISSUE TITLE
Crash Bandicoot 4: It's About Time (1378990)

### ISSUE THREAD

**Issue by MattyPixels** [ValveSoftware/Proton#7727]
# Compatibility Report
- Name of the game with compatibility issues: Crash Bandicoot 4 : It's About Time
- Steam AppID of the game: 1378990

## System Information
- GPU: AMD RX 6700 XT
- Video driver version: Mesa 24.0.5 | OpenGL ES 3.2
- Kernel version: 6.8.9-301.fsync.fc40.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/MattyPixels/44a41b253533ef374b19d8b16ff2fe9b
- Proton version: GE-Proton9-4 (though I have tried Proton9-4, Proton Experimental & Proton Hotfix as well, and they all exhibit the same issue)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

I have verified game files, reinstalled the game and tried with a fresh prefix, the issue persists.

[steam-1378990.log](https://github.com/ValveSoftware/Proton/files/15288259/steam-1378990.log)

## Symptoms 
When launching certain levels at random, sometimes they will load properly, but most of the time, a dialog box
 is shown that says "Fatal Error!". When clicking "ok" on said dialog box, the game closes.

## Reproduction
1 - Open the game.
2 - Start any level.

**Comment by kisak-valve** [comment]
Hello @MattyPixels, can you check if https://gitlab.freedesktop.org/drm/amd/-/issues/3343 is relevant to your system? A quick test would be to reboot into an older kernel and see how the game behaves.

**Comment by MattyPixels** [comment]
Hi! I don't have an older kernel anymore (Fedora Atomic ostree distro), and I don't have an older kernel pinned. However if it helps, the game runs perfectly on my Steam Deck which has an older kernel (stock SteamOS, stable build).

**Comment by simifor** [comment]
@MattyPixels I couldn't reproduce the issue locally, if you're already on 6.9 please retest and see if it still crashes.

**Comment by MattyPixels** [comment]
@simifor Enabling 4G decoding and Rebar in my BIOS fixed the issue on 6.8.5.
No issue since on 6.8.10.
