### ISSUE TITLE
Assasins Creed Odyssey NOT starting / Loading

### ISSUE THREAD

**Issue by vuaieo** [ValveSoftware/Proton#7728]
# Compatibility Report
- Name of the game with compatibility issues: Assasins Creed Odyssey
- Steam AppID of the game: 812140

## System Information
- GPU: RTX 3080 ti
- Video driver version: Nvidia 550.67
- Kernel version: 6.8.7-201.fsync.fc39.x86_64 (64-bit)
- Link to full system information report:     https://pastebin.com/pbxp0gYS
- Proton version:      Proton Experimental and many other versions
[steam-812140.log](https://github.com/ValveSoftware/Proton/files/15288845/steam-812140.log)

## I confirm:
- [ y] that I haven't found an existing compatibility report for this game.
- [ y] that I have checked whether there are updates for my system available.

## Symptoms 
1. freezing / forever loading at start. very rarely after 5 times restarting game it would run. if it runs then fine but most of times freez / stuck...
 
2. so tryed to run on proton 8 version and after it it wouldnt find the uplay installation so i had to delete the ubisoft connect game launcher folder and verify and restart steam so it would install...

## Reproduction
just start the game and see it freezes on loading screens.

why is this game broken again last year somewhen was broken and then fixed and now broken again T__T

**Comment by kisak-valve** [comment]
Hello @vuaieo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1757#issuecomment-2107473128.
