### ISSUE TITLE
DCS: Square box's instead of text's.

### ISSUE THREAD

**Issue by SkippTekk** [ValveSoftware/Proton#7732]
# Compatibility Report
- Name of the game with compatibility issues: DCS world
- Steam AppID of the game: 223750 (non steam version)

## System Information
- GPU: 5700xt
- Video driver version: amdgpu (not sure how to properly get the data)
- Kernel version: 6.8.9-arch1-2 endeavourOS
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/SkippTekk/ead9f9bb34cef96ffdb51a5372f37a78
- Proton version: wine-ge-8-26-x86_64

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Reproduction

Load DCS, trial the Apache and turn it on, get's Box's instead of text's.

![Screenshot from 2024-05-14 17-13-49](https://github.com/ValveSoftware/Proton/assets/6195158/6f527b8a-fdda-4b2a-a418-800141f0c4b8)

Please note, this is NOT DCS steam version and running with Lutris. I haven't tried other Wine runners yet.

**Comment by kisak-valve** [comment]
Hello @SkippTekk, wine-ge is out of scope for the Proton issue tracker.

**Comment by SkippTekk** [comment]
Hi there, i would like to re-open this as i have Proton experimental  setting for the DCS application game. I'm having the same issues as previously stated.

**Comment by kisak-valve** [comment]
In general we're using one issue report per unofficially supported game title. Please add a note to #1722 with how the game is behaving with Proton for you.

**Comment by SkippTekk** [comment]
I would like to clarify that sure DCS world and DCS world steam are different ideals, but they are the same game. So results will vary. The one you have linked was closed hence the new open one, But i'll take your word and work in that one to hopefully finding a resolve.
