### ISSUE TITLE
Fallout 2 - Saves made on windows crash

### ISSUE THREAD

**Issue by poisonHornGames** [ValveSoftware/Proton#7734]
Version: Proton 9.1

Saves that were originally made on windows crash, this does not occur with saves made on linux

![Screenshot_20240515_150134](https://github.com/ValveSoftware/Proton/assets/155884736/52866745-1840-4704-8f31-dc4a77569764)

**Comment by kisak-valve** [comment]
Hello @poisonHornGames, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6491#issuecomment-2112605141.
