### ISSUE TITLE
proton doesn't work above 5.0

### ISSUE THREAD

**Issue by LucasHillebrand** [ValveSoftware/Proton#7738]
i wanted to use proton experimantal, it doesn't launch but with 5.0 it launches but with any version above it crashes ( i have this issue only on my main PC) os: voidlinux gpu: "Radeon RX7800 XT" (upgraded) cpu: "Ryzen 7 3700 X" in a vm it does work don't know why

**Comment by kisak-valve** [comment]
Hello @LucasHillebrand, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to a couple game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by LucasHillebrand** [comment]
https://gist.github.com/LucasHillebrand/9aeb6af03d9b9a238c75ea6868e8c65f

**Comment by kisak-valve** [comment]
```
pressure-vessel-wrap[4180]: W: Binding directories that are located under "/usr/" is not supported!
pressure-vessel-adverb[4245]: E: Failed to execute child process "/usr/storrage/games/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/bin/steam-runtime-launcher-interface-0" (No such file or directory)
```
at https://gist.github.com/LucasHillebrand/9aeb6af03d9b9a238c75ea6868e8c65f#file-gistfile1-txt-L616-L617 is probably the strongest hint.

Proton 5.13 and newer is run inside a Steam Linux Runtime container environment, and this comes with a handful of technical restrictions including having a hard time using any folder under /usr as a Steam library folder. (https://github.com/ValveSoftware/steam-runtime/blob/master/doc/steamlinuxruntime-known-issues.md#usrlocal)

Please move your secondary Steam library folder somewhere else in the filesystem tree and retest.

**Comment by LucasHillebrand** [comment]
thanks for your help
