### ISSUE TITLE
[BUG] Dark Souls: Remastered visually freezes but everything else works

### ISSUE THREAD

**Issue by sudoharun** [ValveSoftware/Proton#7744]
Video:

https://github.com/ValveSoftware/Proton/assets/123123333/f15b2381-ab12-4584-9fd7-dcbd436a9325

Steam log:
[steam-570940.log](https://github.com/ValveSoftware/Proton/files/15362242/steam-570940.log)

**Comment by kisak-valve** [comment]
Hello @sudoharun, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1026#issuecomment-2118811842.
