### ISSUE TITLE
DARK SOULS™ II: Scholar of the First Sin (335300) - Debug menu mod can't be opened via keyboard shortcut, but controller shortcut works fine

### ISSUE THREAD

**Issue by Vinjul1704** [ValveSoftware/Proton#7750]
# Compatibility Report
- Name of the game with compatibility issues: DARK SOULS™ II: Scholar of the First Sin
- Steam AppID of the game: 335300

## System Information
- GPU: Intel Arc A380
- Video driver version: mesa-tkg-git 24.2.0_devel.189250.2f02af39b34-1
- Kernel version: 6.8.9-zen1-2-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Vinjul1704/a87a80de2ce92591c347d1e386773a96
- Proton version: 8.0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton log: https://gist.github.com/Vinjul1704/abaa58416b89633f2550509d3d8dd601

The log had about 408 million lines of "trace:seh:__processing_throw ()" in the middle, which I removed in order to not send a 2 GB large log file. If you want me to upload the full log regardless to check if there might be something there, please let me know.

## Symptoms 
When using the following debug menu mod for testing and speedrun routing, the keyboard shortcut to open it (F10 by default) doesn't work, but the controller shortcut (L3 + Start) works fine: https://github.com/LordRadai/DebugManager-v2.0-Release

When asking the mod author how the keys are checked, their response was that "GetAsyncStateKey" is used with the released flag.

I hope it's fine to report issues with mods like this here. If it isn't, I apologize.

## Reproduction
Install debug menu mod -> Set appropriate dinput8.dll override -> Launch game -> Press F10 -> Nothing opens

**Comment by kisak-valve** [comment]
Hello @Vinjul1704, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/137#issuecomment-2119245085.

**Comment by Vinjul1704** [comment]
> Hello @Vinjul1704, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#137 (comment)](https://github.com/ValveSoftware/Proton/issues/137#issuecomment-2119245085).

Thank you. For some reason, the open issue didn't come up in the search results for me earlier.
