### ISSUE TITLE
Multiple Controllers Detected In Rocket League

### ISSUE THREAD

**Issue by Dex0112** [ValveSoftware/Proton#7752]
I've reproduced this with:
Proton Experimental
Proton 9.0-1
Proton 8.0-5

When my controller gets disconnect, for any amount of time, and reconnected in Rocket League it pops up "press options to join". There is not another controller connected so this shouldn't be appearing. I've tested this with Windows and the native linux build (It is outdated and no longer supported) and in both this issue doesn't occur. The only way to fix this issue is to entirely close the game and relaunch.

In [this](https://www.reddit.com/r/RocketLeague/comments/5g632z/pc_ps4_contollers_cause_second_player_to_join/) it is explained that this is typically caused by software that is used to handle controller input. I don't have any software like this on my system as I am on a brand new Arch Install.

**Comment by kisak-valve** [comment]
Hello @Dex0112, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3521#issuecomment-2121045115.
