### ISSUE TITLE
Helldivers 2 nothing happens after clicking start and no errors in the error log

### ISSUE THREAD

**Issue by mistrjirka** [ValveSoftware/Proton#7755]
Helldivers 2 

## System Information
Computer Information:
Manufacturer: Micro-Star International Co., Ltd
Model: B450-A PRO (MS-7B86)
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 7 5700X3D 8-Core Processor
CPU Family: 0x19
CPU Model: 0x21
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 4148 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"Manjaro Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.6.30-2-MANJARO
X Server Vendor: The X.Org Foundation
X Server Release: 12101013
X Window Manager: Mutter (Muffin)
Steam Runtime Version: steam-runtime_0.20240415.84615
Video Card:
Driver: AMD AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 17.0.6, DRM 3.54, 6.6.30-2-MANJARO)
Driver Version: 4.6 (Compatibility Profile) Mesa 24.0.6-manjaro1.1
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID: 0x1002
DeviceID: 0x747e
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 4480 x 1440
Primary Display Size: 23.50" x 13.23" (26.97" diag), 59.7cm x 33.6cm (68.5cm diag)
Primary VRAM: 16384 MB
Sound card:
Audio device: ATI R6xx HDMI
Memory:
RAM: 64226 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: cs_CZ.UTF-8
Total Hard Disk Space Available: 468058 MB
Largest Free Hard Disk Block: 104740 MB
Storage:
Number of SSDs: 4
SSD sizes: 2000G,512G,120G,0B
Number of HDDs: 0
Number of removable drives: 0

## I confirm:
- [ -] that I haven't found an existing compatibility report for this game.
- [- ] that I have checked whether there are updates for my system available.

[steam-553850.log](https://github.com/ValveSoftware/Proton/files/15402057/steam-553850.log)

## Symptoms 
Nothing happens no errors in the usual error logs:
`/bin/sh\0-c\0PROTON_LOG=1 /home/jirka/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=553850 -- /home/jirka/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/run/media/jirka/Nový svazek/programy/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/run/media/jirka/Nový svazek/programy/Steam/steamapps/common/Proton Hotfix'/proton waitforexitandrun  '/run/media/jirka/Nový svazek/programy/Steam/steamapps/common/Helldivers 2/bin/helldivers2.exe' --bundle-dir data --release\0
chdir "/run/media/jirka/Nový svazek/programy/Steam/steamapps/common/Helldivers 2"
ERROR: ld.so: object '/home/jirka/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jirka/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/jirka/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jirka/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jirka/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Game 553850 created interface STEAMAPPLIST_INTERFACE_VERSION001 / AppList
Game 553850 created interface STEAMAPPS_INTERFACE_VERSION008 / Apps
Game 553850 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_004 / HTMLSurface
Game 553850 created interface STEAMHTTP_INTERFACE_VERSION002 / HTTP
Game 553850 created interface STEAMINVENTORY_INTERFACE_V002 / Inventory
Game 553850 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 / MusicRemote
Game 553850 created interface STEAMMUSIC_INTERFACE_VERSION001 / Music
Game 553850 created interface STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / ParentalSettings
Game 553850 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION014 / RemoteStorage
Game 553850 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 / Screenshots
Game 553850 created interface STEAMUGC_INTERFACE_VERSION010 / UGC
Game 553850 created interface STEAMUSERSTATS_INTERFACE_VERSION011 / UserStats
Game 553850 created interface STEAMVIDEO_INTERFACE_V002 / Video
Game 553850 created interface SteamController006 / Controller
Game 553850 created interface SteamFriends015 / Friends
Game 553850 created interface SteamMatchMaking009 / Matchmaking
Game 553850 created interface SteamMatchMakingServers002 / MatchmakingServers
Game 553850 created interface SteamNetworking005 / Networking
Game 553850 created interface SteamUser019 / User
Game 553850 created interface SteamUtils009 / Utils
Game 553850 method call count for IClientAppManager::GetCurrentLanguage : 1
Game 553850 method call count for IClientAppManager::GetAvailableLanguages : 1
Game 553850 method call count for IClientAppManager::GetAppInstallState : 2
Game 553850 method call count for IClientUtils::RecordSteamInterfaceCreation : 22
Game 553850 method call count for IClientUtils::GetSteamUILanguage : 1
Game 553850 method call count for IClientUtils::GetAppID : 24
Game 553850 method call count for IClientUser::GetSteamID : 1
Uploaded AppInterfaceStats to Steam

`

## Reproduction

Start the game on basically any version of proton (including hotfix and experimental)

**Comment by kisak-valve** [comment]
Hello @mistrjirka, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #7486, however, there's a known kernel regression in the 6.6.30 Linux kernel which was tracked and fixed in https://gitlab.freedesktop.org/drm/amd/-/issues/3343. The fix is in 6.9.0, 6.8.10, and 6.6.31.

Reboot into a different kernel version.

**Comment by mistrjirka** [comment]
Did not help. Currently on 6.9.0-1-MANJARO but it acts exactly the same as before.
To me it  seems that the game binary does not even attempts to run because of  dependencies (from proton log):
`
4690.784:0124:0128:err:module:import_dll Library IMM32.dll (which is needed by L"Z:\\run\\media\\jirka\\Nov\00fd svazek\\programy\\Steam\\steamapps\\common\\Helldivers 2\\bin\\helldivers2.exe") not found
4690.784:0124:0128:err:module:import_dll Library DINPUT8.dll (which is needed by L"Z:\\run\\media\\jirka\\Nov\00fd svazek\\programy\\Steam\\steamapps\\common\\Helldivers 2\\bin\\helldivers2.exe") not found
4690.786:0124:0128:err:module:import_dll Library WLDAP32.dll (which is needed by L"Z:\\run\\media\\jirka\\Nov\00fd svazek\\programy\\Steam\\steamapps\\common\\Helldivers 2\\bin\\libcurl.dll") not found`
But I will write a comment to the mentioned issue

**Comment by mistrjirka** [comment]
Issue fixed by reinstalling shared libraries

**Comment by Alekisan** [comment]
> Issue fixed by reinstalling shared libraries

Can you elaborate on what exactly it was you did?
What shared libraries?

**Comment by mistrjirka** [comment]
> > Issue fixed by reinstalling shared libraries
> 
> Can you elaborate on what exactly it was you did? What shared libraries?

I found that some of the shared dlls were not loading. I reinstalled Steamworks and it somehow started working. The disk which is it was on was from windows system and maybe that has something to do with it.
