### ISSUE TITLE
Dead by Daylight [381210]

### ISSUE THREAD

**Issue by canofjuice** [ValveSoftware/Proton#7756]
# Compatibility Report
- Name of the game with compatibility issues: Dead by Daylight
- Steam AppID of the game: 381210

## System Information
- GPU: GTX 750 Ti
- Video driver version: NVIDIA 550.78
- Kernel version: 6.8.9
- Link to full system information report as [Gist.](https://gist.github.com/canofjuice/f7c8ed7949d569f3474f93fe18eb9df1) [Forgot to include Runtime System Info...](https://gist.github.com/canofjuice/5023d94b8c3a903e1761db172b28a7e3)
- Proton version: Tested 9.0-1 and Experimental

## I confirm:
- [ Y ] that I haven't found an existing compatibility report for this game.
- [ Y ] that I have checked whether there are updates for my system available.

[steam-381210.log](https://github.com/ValveSoftware/Proton/files/15408519/steam-381210.log)

## Symptoms 

Game crashes when i tried to enter a match. Specifically when the game shows "offerings" added by players.

## Reproduction

Use Proton 9.0-1 or Experimental, Open the game normally, find a match, ready up until the game starts and shows the "offerings" screen.

This crash doesn't occur while using Proton 8.0-5, but anything 2D flickers and there is noticeable lag/performance drop.

## Additional Notes

Tried running on EndeavourOS and now Bazzite, same issue. Both running KDE 6.
Steam on Bazzite uses the Flatpak Version.

**Comment by kisak-valve** [comment]
Hello @canofjuice, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/519#issuecomment-2125756247.

**Comment by canofjuice** [comment]
Got it!
