### ISSUE TITLE
Beecarbonize (2486750)

### ISSUE THREAD

**Issue by ChildishGiant** [ValveSoftware/Proton#7758]
# Compatibility Report
- Name of the game with compatibility issues: Beecarbonize
- Steam AppID of the game: 2486750

## System Information
- GPU: RX 480
- Video driver version: Mesa 24.0.6-manjaro1.1
- Kernel version: 6.9.0-1-MANJARO
- Proton version: 1715877763 experimental-9.0-20240516 (Recommended)
- Steam runtime diagnostics: https://gist.github.com/ChildishGiant/1b702c968de2cdd003c8f0454b1406a9
<details><summary>Full system information report</summary>

```
Computer Information:
Manufacturer: ASRock
Model: AB350 Pro4
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 5 1600X Six-Core Processor
CPU Family: 0x17
CPU Model: 0x1
CPU Stepping: 0x1
CPU Type: 0x0
Speed: 3600 MHz
12 logical processors
6 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"Manjaro Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.9.0-1-MANJARO
X Server Vendor: The X.Org Foundation
X Server Release: 12302006
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20240415.84615
Video Card:
Driver: AMD AMD Radeon RX 480 Graphics (radeonsi, polaris10, LLVM 17.0.6, DRM 3.57, 6.9.0-1-MANJARO)
Driver Version: 4.6 (Compatibility Profile) Mesa 24.0.6-manjaro1.1
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID: 0x1002
DeviceID: 0x67df
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 18.90" x 10.63" (21.65" diag), 48.0cm x 27.0cm (55.0cm diag)
Primary VRAM: 8192 MB
Sound card:
Audio device: ATI R6xx HDMI
Memory:
RAM: 32022 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_GB.UTF-8
Total Hard Disk Space Available: 902823 MB
Largest Free Hard Disk Block: 438061 MB
Storage:
Number of SSDs: 7
SSD sizes: 1000G,500G,250G,134G,120G,0B,0B
Number of HDDs: 0
Number of removable drives: 0

```
</details>

Proton log: [steam-2486750.log](https://github.com/ValveSoftware/Proton/files/15417744/steam-2486750.log)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When launched the app does nothing for a bit and then briefly shows a unity crash window before closing.
![image](https://github.com/ValveSoftware/Proton/assets/13716824/66727ac1-ce94-4084-9638-94ef2f14a79d)

## Reproduction
🤷🏻‍♀️  Happens every time on this install but worked on my previous Fedora install.

**Comment by kisak-valve** [comment]
Hello @ChildishGiant, https://gist.github.com/ChildishGiant/1b702c968de2cdd003c8f0454b1406a9#file-steam-runtime-diagnostics-L926-L940 is the section to focus on. Your system does not have a 32 bit Vulkan driver installed. Add the `lib32-vulkan-radeon` system package and retest.

**Comment by ChildishGiant** [comment]
That worked perfectly! My CPU is 64bit but I guess the app isn't? Either way, thank you for the help ❤️
