### ISSUE TITLE
[APPID:438100] VRChat with anti aliasing causes microstutering with ALVR/SteamVR

### ISSUE THREAD

**Issue by OzzyHelix** [ValveSoftware/Proton#7765]
# Compatibility Report
- Name of the game with compatibility issues: VRChat
- Steam AppID of the game: 438100

## System Information
- GPU: AMD RX 7800 XT
- Video driver version: Mesa 24.0.8
- Kernel version: 6.9.1 Zen Kernel
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/OzzyHelix/5bf35f2a77008446adae2827a938b72c
- Steam Runtime Infomation: https://gist.github.com/OzzyHelix/4f334c82e7c48d44b0ad5fb2fb7af86c
- Proton version: Proton 9 GE

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
VRChat's Anti Aliasing setting when enabled causes microstuttering on SteamVR/ALVR

## Reproduction
load up SteamVR on AMD RX 7800 XT
launch VRChat with Proton
enable anti aliasing and disable anti aliasing
it occurs at 90hz and 120hz 

![Screenshot_20240526_141325](https://github.com/ValveSoftware/Proton/assets/29835364/51001911-2b4d-44e0-8119-d8e51775da94)

![Screenshot_20240526_141813](https://github.com/ValveSoftware/Proton/assets/29835364/c0d8b914-b2d0-44bb-b527-1e8b651638cf)
[steam-438100.log](https://github.com/ValveSoftware/Proton/files/15448632/steam-438100.log)

**Comment by kisak-valve** [comment]
Hello @OzzyHelix, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1199#issuecomment-2132369444.

**Comment by OzzyHelix** [comment]
ok thanks sorry I thought VRChat hadn't been reported yet
