### ISSUE TITLE
Diablo 4 Korean input problem

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7766]
# Compatibility Report
- Name of the game with compatibility issues: diablo 4
- Steam AppID of the game: 2344520

## System Information
- GPU:  gtx 4060 ti
- Video driver version:  nvidia 550.78
- Kernel version:  6.8.10
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 9.0-1

## I confirm:
- [ *] that I haven't found an existing compatibility report for this game.
- [ *] that I have checked whether there are updates for my system available.

## Symptoms 

I can't enter Korean in Diablo 4 chat. 
In Proton 8.0-5, Korean input works fine. 
Proton 9.0-1 and proton experimental should not work. 
Please fix. 
I use fedora 40

**Comment by kisak-valve** [comment]
Hello @Sosouserf, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7199#issuecomment-2134139472.
