### ISSUE TITLE
Multiversus does not boot.

### ISSUE THREAD

**Issue by PedroZuuh** [ValveSoftware/Proton#7768]
# Compatibility Report
- Name of the game with compatibility issues: Multiversus

## System Information
OS: Pop!_OS 22.04 LTS
KERNEL: 6.8.0-76060800daily20240311-generic
CPU: Intel Core i5-8265U
GPU: Intel Mesa Intel UHD 620 (WHL GT2)
GPU DRIVER: 4.6 Mesa 24.0.6 (git-c659c7e660)
RAM: 12 GB
- Proton version: Experimental, 9, 8, 7.

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

![Captura de tela de 2024-05-28 20-43-18](https://github.com/ValveSoftware/Proton/assets/60187096/ee395cc6-0a20-4327-9c2c-212b23250cb0)

Game does not boot, and shows this error message. My iGPU is able to run DirectX11, Vulkan and other APIs.

## Reproduction
Just try to boot the game.

**Comment by sudoharun** [comment]
MultiVersus also does not run for me, however I don't get any messages displayed on my screen. Similarly, I have an Intel i5-10210U with Intel UHD 620 iGPU. Logs [here](https://drive.google.com/file/d/1JMTw9Yx1QVNp2QHMvMSF9prkWnc44Eg4/view?usp=sharing) (created with Proton 9.0-1).

**Comment by kisak-valve** [comment]
Hello @PedroZuuh, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6031#issuecomment-2137348048.
