### ISSUE TITLE
Black Ops 3 zombies shader issues

### ISSUE THREAD

**Issue by kodenamekrak** [ValveSoftware/Proton#7770]
# Compatibility Report
- Call of Duty®: Black Ops III
- 311210

## System Information
- GPU: Nvidia RTX 4070
- Video driver version: Nvidia 535.171.04
- Kernel version: 5.15.0-107-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kodenamekrak/70cd9ba7dacaf9d3eb4b699ea0ac611f
- Proton version: Proton Experimental

## I confirm:
- [x] I haven't found an existing compatibility report for this game - Other issues are open but i dont believe any report this problem
- [x] I have checked whether there are updates for my system available.

[steam-311210.log](https://github.com/ValveSoftware/Proton/files/15505934/steam-311210.log)

## Symptoms 
In the zombies mode some shaders are broken such as the skin shaders for other players which appears metalic, though it is most noticable on Kino Der Toten as many of the environment shaders are glowing very bright as seen below

![2024-05-30_21-51](https://github.com/ValveSoftware/Proton/assets/106346717/af0eb992-6306-4f50-90a1-bfec64bc8026)
![image](https://github.com/ValveSoftware/Proton/assets/106346717/2df1a2da-f15f-46a1-ab49-6e35145edfb5)

## Reproduction
Open the game and play any map in zombies mode, most notably Kino Der Toten

**Comment by kisak-valve** [comment]
Hello @kodenamekrak, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/864#issuecomment-2140899543.
