### ISSUE TITLE
Soft-linking to pre-downloaded game not works?

### ISSUE THREAD

**Issue by ssv-170379** [ValveSoftware/Proton#780]
(Sorry for bad English) The Evil Within 2. Created a soft-link to a folder with pre-downloaded game (from another Steam installation) in ~/.steam/steam/steamapps/common/ . When installing via Proton it checks for existing files for a moment but immediately starts to re-download the whole game, and finally fails to extract files to that linked folder (in passing ruining existing there installation). And only after removing soft link game files are deploying normally. But when installation is finished you may to move TheEvilWithin2 folder to other partition, create soft-link and play the game. i.e. soft-linking works correctly except the installation process.

**Comment by kisak-valve** [comment]
Hello @ssv-170379, downloads and updates to games is handled by the the steam client, not Proton, so I've gone ahead and transferred this issue to https://github.com/ValveSoftware/steam-for-linux/issues/5693.
