### ISSUE TITLE
Multiversus not loading

### ISSUE THREAD

**Issue by dfreck723** [ValveSoftware/Proton#7804]
# Compatibility Report
- Name of the game with compatibility issues: Multiversus
- Steam AppID of the game: 1818750

## System Information
- GPU: Intel® Iris® Xe Graphics
- Video driver version: 4.6 (Compatibility Profile) Mesa 24.0.7 (git-cc175010c5)
- Kernel version: 6.1.0-21-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/dfreck723/c0aaa102146137b86f9580b5a922dc9e
- Proton version: GE-Proton9-5(Global)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
[steam-1818750.log](https://github.com/user-attachments/files/15523468/steam-1818750.log)

**Comment by kisak-valve** [comment]
Hello @dfreck723, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6031#issuecomment-2143616476.
