### ISSUE TITLE
Resident Evil 0 fails show cutscenes

### ISSUE THREAD

**Issue by PNunesDev** [ValveSoftware/Proton#7806]
# Compatibility Report
- Name of the game with compatibility issues: Resident Evil 0
- Steam AppID of the game: 339340

## System Information
- GPU: GTX 1650 Super
- Video driver version: 535.171.04-0ubuntu0.22.04.01
- Kernel version: 5.15.0.107-generic
- Link to full system information report as [Gist](https://gist.github.com/): [gist:887f0d70b9b94f95f0324c1566d8c443](https://gist.github.com/PNunesDev/887f0d70b9b94f95f0324c1566d8c443)
- Proton version: (any) (tried experimental, 9.0-1 and GE-Proton9-5

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-339340.log](https://github.com/user-attachments/files/15527060/steam-339340.log)

## Symptoms 
Visual corruption with green and red pixels everywhere.
![20240602230926_1](https://github.com/ValveSoftware/Proton/assets/11355144/aabf887e-901b-4c58-9949-245d689fe4a7)
![20240602230939_1](https://github.com/ValveSoftware/Proton/assets/11355144/ee2490a8-69a8-4e66-8a36-96779f7505af)

## Reproduction
Start a new game
Play until the Secondary character is playable (Billy Coen), it should be playable after 5-10 minutes after starting a new game.
As soon as we reach that point, visual corruption appears.

Reproducted in proton experimental as well as 9.0-1, tried GE-Proton9-5 but issues continues.

**Comment by kisak-valve** [comment]
Hello @PNunesDev, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/576#issuecomment-2144040911.
