### ISSUE TITLE
Sea of Thieves (1172620)

### ISSUE THREAD

**Issue by Iancooles** [ValveSoftware/Proton#7810]
# Compatibility Report
- Name of the game with compatibility issues: Sea of Thieves
- Steam AppID of the game: 1172620

## System Information
- GPU: AMD Radeon RX 7900 XT
- Video driver version: Mesa 24.1.0-arch1.1
- Kernel version: 6.9.3-1-cachyos-bore-lto 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Iancooles/241e9796e95feda0ddae522fb0997163
- Proton version: 9.0-1

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
In the last month when I start the game, it asks me to sign in even though I already have my Xbox account linked. However, when the sign in window opens up, its completely black with no way to input anything. This has prevented me from playing the game for a while now with no workarounds to be seen.

## Reproduction
1. Download the game on a Linux based operating system and then run it.
2. When the at the title screen, click "Start Game"
3. A black window pops up that won't let you sign in.
4. Congratulations, the game you paid for doesn't let you play anymore.

[steam-1172620.log](https://github.com/user-attachments/files/15537611/steam-1172620.log)

**Comment by kisak-valve** [comment]
Hello @Iancooles, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3931#issuecomment-2145798760.
