### ISSUE TITLE
Monster hutner world: controler not being dected and mosue camera control is broken 

### ISSUE THREAD

**Issue by testc2n14** [ValveSoftware/Proton#7811]
# Compatibility Report
- Name of the game with compatibility issues: monster hunter world
- Steam AppID of the game:582010

## System Information
- GPU: 
- Video driver version: 
- Kernel version: 
- Link to full system information report as [Gist](https://pastebin.com/9XhgCitP/):
- Proton version:steam default

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

    the game dose not not launch affter trying to run the game with that command, even with otu the command 

## Symptoms 
so nwo affter runnign the proton log command the game dose not launch at all but befor the gaem woudl not reconsie the controler at all even tho both steam and my OS could reconise it perfectly fine and take inputs from it. 
thought this might be helpfull to add
```
             .',;::::;,'.                c2n14@fedora 
         .';:cccccccccccc:;,.            ------------ 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 40 (KDE Plasma) x86_64 
    .:cccccccccccccccccccccccccc:.       Host: B650M DS3H 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 6.8.11-300.fc40.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 8 hours 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 3164 (rpm), 78 (flatpak) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: bash 5.2.26 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 3840x2160 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: Plasma 6.0.5 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: kwin 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   Theme: Breeze-Dark [GTK2], Breeze [GTK3] 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Icons: Vivid-Dark-Icons [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Terminal: konsole 
cccccc;dNMWXXXWM0::cccccccccccccc:,      CPU: AMD Ryzen 7 7800X3D (16) @ 5.050GHz 
cccccccc;.:odl:.;cccccccccccccc:,.       GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT 
:cccccccccccccccccccccccccccc:'.         Memory: 10857MiB / 31723MiB 
.:cccccccccccccccccccccc:;,..
  '::cccccccccccccc::;,.                                         
                                                                 
```

**Comment by testc2n14** [comment]
i know ia dded the hardwre info but i guess i didn;t i will palce ti ehre, gpu is a 6800, drivers for mesa are 24.0.8. the kernnel is: 6.8.11-300.fc40.x86_64,   and ehre is a pastbin thign to the full steam system reporthttps://pastebin.com/9XhgCitP

**Comment by kisak-valve** [comment]
Hello @testc2n14, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/175#issuecomment-2146222829.

**Comment by testc2n14** [comment]
but monster hutner world is mark as verified on the steam store page
