### ISSUE TITLE
Elden Ring (start lauch but goes back to green play

### ISSUE THREAD

**Issue by RuairiLennon** [ValveSoftware/Proton#7815]
# Compatibility Report
- Name of the game with compatibility issues: Elden Ring
- Steam AppID of the game:440408

## System Information
- GPU: 
- Video driver version: 
- Kernel version: 

## Symptoms  clicking on play in steam launches the game but no window appears and the steam button returns to green "play"
[Steam  runtime information.txt](https://github.com/user-attachments/files/15595540/Steam.runtime.information.txt)
)

**Comment by kisak-valve** [comment]
Hello @Tomjlennon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-2150803171.
