### ISSUE TITLE
Satisfactory regression on nVidia 555.42.02 (explicit sync)

### ISSUE THREAD

**Issue by Baughn** [ValveSoftware/Proton#7817]
# Compatibility Report
- Name of the game with compatibility issues: Satisfactory
- Steam AppID of the game: 526870

## System Information
- GPU: RTX 4090
- Video driver version: NVIDIA proprietary 555.42.02
- Kernel version: 6.8.12
- Link to full system information report as [Gist](https://gist.github.com/Baughn/582242df99348066421ff47a32431bc2/).
- Proton version: Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Application log: [steam-526870.log.gz](https://github.com/user-attachments/files/15654844/steam-526870.log.gz)

However, enabling PROTON_LOG dramatically changed the behaviour of the application; instead of what I describe below, it instead immediately freezes,

## Symptoms 

After installing NVIDIA driver version 555, at a random time (typically a few seconds) after launching, the game crashes with the following error:
![image](https://github.com/ValveSoftware/Proton/assets/45811/362fa69e-0651-4010-b15c-74fd29a3a78c)

This is with `%command% -vulkan`. Without -vulkan it doesn't crash, but instead shows a black screen forever.

This is on Wayland. This driver version enabled the explicit swap chain for Xwayland, which I believe may have broken some assumption in winevulkan.

**Comment by kisak-valve** [comment]
Hello @Baughn, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7580#issuecomment-2152945600.
