### ISSUE TITLE
Underrail (250520)

### ISSUE THREAD

**Issue by Raikiri** [ValveSoftware/Proton#7821]
# Compatibility Report
- Name of the game with compatibility issues: Underrail
- Steam AppID of the game: 250520

## System Information
- GPU: RTX 4080
- Video driver version: 4.6 (Compatibility Profile) Mesa 24.0.7 (why is the report not showing my RTX 4080?)
- Kernel version: 6.6.32
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Raikiri/4c1b97645519083ab6433bbdc4fb0376
- Steam runtime diagnostics: https://gist.github.com/Raikiri/fc8c94cc4f4a77db9354269e8c956be6
- Proton version: 1716388226 experimental-9.0-20240522 , tried multiple other versions too with no difference.

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
In fullscreen mode when the game resolution does not match the resolution of the desktop, right mouse button teleports the cursor, effectively preventing interaction with items and dragging the view or the map.

## Reproduction
1. Use a high desktop resolution (>1080p)
2. In-game use fullscreen mode, 1080p swapchain resolution
3. Start a new game (skip dialogs until you can move with left mouse button)
4. Observe that clicking right mouse button teleports the cursor to a lower-left corner

Note: the problem happens because the game is trying to hold the cursor at the position where RMB was clicked (to allow indefinite scrolling of the view or the minimap), presumably using something akin to GetCursorPos()+SetCursorPos(). However, something goes wrong in the fullscreen mouse position transformation code and the mouse cursor is set to a different position as to where it was clicked.

I assume it's related to the fact that proton does not change the actual desktop resolution in fullscreen mode and instead rescales the game's rendertarget to whatever the desktop resolution is.

This breaks dragging the in-game view, dragging the map (opened with M) and RMB interaction with certain in-game items (jets, ventilation shafts and a bunch of other things you interact with using RMB).

[steam-250520.log](https://github.com/user-attachments/files/15738636/steam-250520.log)

**Comment by kisak-valve** [comment]
Hello @Raikiri, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/115#issuecomment-2154792587.

**Comment by Raikiri** [comment]
Okay thank you, I did not find that one during searching. I hope it gets addressed.
