### ISSUE TITLE
Hell Let Loose (Proton version: 1717684872 experimental-9.0-20240606)

### ISSUE THREAD

**Issue by Dzuelu** [ValveSoftware/Proton#7822]
# Compatibility Report
- Name of the game with compatibility issues: Hell Let Loose
- Steam AppID of the game: 686810

## System Information
- GPU: GIGABYTE GeForce RTX 4090
- Video driver version: nvidia v: 535.171.04
- Kernel version: 5.15.0-112-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Dzuelu/d0bd8f12cade561ed53eb9e4a1e27f51
- Proton version: 1717684872 experimental-9.0-20240606

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
  - [Other issue found is not the same](https://github.com/ValveSoftware/Proton/issues/2901). 
- [x] that I have checked whether there are updates for my system available.

[steam-686810.log](https://github.com/user-attachments/files/15746064/steam-686810.log)

## Symptoms 
Able to launch the game, join a server, and select a side. When selecting a spawn and about to spawn it crashes. Looking in the proton logs there is `*** stack smashing detected ***: terminated` which is where I'm assuming it's crashing.

## Reproduction
Launch game, may get same [TV input screen like this](https://github.com/ValveSoftware/Proton/issues/2901#issuecomment-813946736) but I get past the anti-cheat fine for the intro video and it does fix it's self eventually and can skip though too. Find server, select side and select a spawn. Just before spawning I've crashed several times today.

**Comment by kisak-valve** [comment]
Hello @Dzuelu, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2901#issuecomment-2155753590.
