### ISSUE TITLE
Fallout 76 - Unsupported

### ISSUE THREAD

**Issue by glenni83** [ValveSoftware/Proton#7823]
Hey!

I wonder if you guys can look at Fallout 76 again? Since the proton that was given out for that game, it has changed a lot. 

It used to play verry well, until a few months ago. I sat for a whole week, just getting the game to work ok. 

Meaning there are different issues today now in Fallout 76, it used to work very well on the old proton that was given out for the game, today there are different issues with mouse, not staying on screen, keyboard stop working, some crashing when try launching from time to time. I know about a few fixes. But they dont seem to work under multi monitors. Performance is not that good anymore either. Old proton could stay on the 60fps locked without dipping, now it has a 10% loss in fps down to 50fps, meaning its hard to get the game running 60fps on a 4070 laptop. Yesterday, i could not get the game to launch at all, even i have done nothing to change it. No idea why i could not launch either. There is also a major bug, where you cant exit the game atm. You need to kille the process for it.

Been nice if it was possible to apply a few fixes for it, or have a look at it. Its not running under the gold anymore in my opinion, compared of how it used to run. Applying different fixes from my own side, has been a nightmare. One side can fix one issue, but then something else breaks or runs bad. 

Main system running an 7800X3D, Nvidia 4090, CachyOs Distro. Laptop, Intel I7 Ark hybrid with 4070 dedicated gpu, also running Kernel: Linux 6.9.3-4-cachyos

Thanks!

**Comment by kisak-valve** [comment]
Hello @glenni83, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3766#issuecomment-2131369597.
