### ISSUE TITLE
Linux (arch if it's important) Rainbow Six Siege, Battleye issue 

### ISSUE THREAD

**Issue by kwalob** [ValveSoftware/Proton#7828]
# Compatibility Report
- Name of the game with compatibility issues: Tom Clancy's Rainbow Six® Siege
- Steam AppID of the game: 359550

## System Information
- GPU: 3060 12gb made by MSI
- Video driver version: 555.42.02
- Kernel version: 6.9.3-arch1-1 (64-bit)
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kwalob/682e056e7389c836903ea0baebee6ffd
- Proton version: 9.0-1

## I confirm:
- [✅] that I haven't found an existing compatibility report for this game.
- [✅ ] that I have checked whether there are updates for my system available.

 
[steam-359550.log](https://github.com/user-attachments/files/15803157/steam-359550.log)

## Symptoms 

so i wanted to play rainbow six siege on linux, but i cannot join a match due to not having Battleye installed, after trying to check for missing files with your steam confirmation thingy, it told me that everything's fine, i tried to install it with wine but not succeeded
the os i'm currently running is Arch linux (64x), everything is up to date
if there's more that y'all need to know ask me, i will do it but i need clear instructions

**Comment by kisak-valve** [comment]
Hello @kwalob, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/946#issuecomment-2162948051.

**Comment by Dahippo1555** [comment]
Hi, @kwalob.
Dont expect to R6S get supported anytime soon.
After +-9Closed R6Fix issues we were told because its more cheaters we wont get it.
Its F'in ubisoft afterall.
