### ISSUE TITLE
Warhammer 40k Darktide crashes during play, closes steam and causes gdm to restart

### ISSUE THREAD

**Issue by DarkeOne** [ValveSoftware/Proton#7830]
# Compatibility Report
- Warhammer 40k Darktide
- db# 1361210

## System Information
- Radeon RX 7900 xtx
- Mesa version 24.0.3
- Kernel version: 6.8.0
- System info...https://gist.github.com/DarkeOne/802f0de7400e43271614e71ba6fb59f6

- Proton version:8.0.5 to 9.0, even GE 9.7

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

[steam-1361210.log](https://github.com/user-attachments/files/15811975/steam-1361210.log)

## Symptoms
This game runs great on my system-right up until it crashes. The game freezes, screen goes black, and I'm dumped to a login screen because I _think_ GDM crashed too (newb here). Steam also crashes as well. If I try to run the game again, it simply won't run, generating a file with an error "_object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored."_

It doesn't matter what Proton version I use, what graphic setting I run (low or high), it happens. Sometimes right at the beginning of a match, sometimes after two or three matches. It does this on any linux distro I run (Pop OS, Fedora KDE, Nobara)

I really like this game, and I hate Windows. Any help is appreciated. Thanks for reading!

Steam Runtime Diagnostics...

https://gist.github.com/DarkeOne/ad54eef4780002ad1929ffb43afa3302

**Comment by kisak-valve** [comment]
Hello @DarkeOne, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6573#issuecomment-2164147676.

**Comment by DarkeOne** [comment]
Sorry for the mix up...thanks!
