### ISSUE TITLE
Ark: Survival Ascended (2399830)

### ISSUE THREAD

**Issue by BlakeRising** [ValveSoftware/Proton#7837]
# Compatibility Report
Ark: Survival Ascended
2399830

## System Information
- GPU: Nvidia Rtx 3070 Ti
- Video driver version: Nvidia 550.78
- Kernel version: 6.8.11
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.githubusercontent.com/BlakeRising/e1cd057afeac27e55ca18fd08d119f14/raw/1be834db802ac286ba64409c07cdd7b7a390b4d8/Blake%2520Gist
- Proton version: 9.0-2

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2399830.log](https://github.com/user-attachments/files/15857201/steam-2399830.log)

## Symptoms 

When loading into the game, oftentimes the logo will jitter and flash. But once you join either a multiplayer server or singleplayer, you will oftentimes encounter a black screen upon entering the world or if you do get into the world, the game will freeze after a couple of minutes of playing if you: Open your inventory, Close your inventory, open the pause menu, try to ride a dino, die and attempt to respawn, or download after uploading your character.

All of these are different crashes i've run into while trying to troubleshoot the game over the last couple of days, but i don't seem to get an error message on proton 9.0-2. But i have noticed i tend to get this error in particular when running Proton Experimental if its of any help.

Assertion Failed! 
File: /src-wine/dlls/winevulkan/loader_thunks.C

Expression: !status && "VkCreateSwapchainKHR"

This error code seems to happen when you attempt to open your inventory or the pause menu a few times.

## Reproduction

Note- All of my crashes were experienced on the map The Center, i can't say if any other map works or not.

Crash 1
1. Open the game and either join a multiplayer server or join a singleplayer game. 
2. If you don't have a character, create one.
3. On the spawn screen, click an area and respawn, it'll freeze on that screen.

Crash 2
1. In the game once you've made a character and spawned
2. run around until the game starts to jitter (usually takes less than 5 minutes)
3. Open your inventory, or the pause menu at least twice, and the game will crash.

Crash 3
1.  When in the game, upload your character at an obelisk or at a tek transmitter. 
2. When you see the screen to download your character, select your character.
3. When you select your character, the game will freeze.
4. If you make it through step 3, click download.
5. Upon choosing an a area to respawn, you will crash.

Crash 4

1. Open singleplayer.
2. Enable creativemode by opening the console with ~ and typing 'gcm'
3. Look at a large dino and force tame it by opening the console and typing 'forcetame'
4. Attempt to ride it, the game will immediately freeze and crash.

**Comment by kisak-valve** [comment]
Hello @BlakeRising, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7224#issuecomment-2171512285.
