### ISSUE TITLE
Halo: Reach Mod Tools – MCC (1695793)

### ISSUE THREAD

**Issue by SOI7** [ValveSoftware/Proton#7838]
# Compatibility Report
- Name of the game with compatibility issues: Halo: Reach Mod Tools – MCC
- Steam AppID of the game: 1695793

## System Information
- GPU: NVIDIA GeForce GTX 1660
- Video driver version: 4.6.0 NVIDIA 535.171.04
- Kernel version: 6.5.0-35-generic
- Linux distro: ZorinOS 17.1
- Proton version: Proton Experimental
- System Information report: [https://gist.github.com/SOI7/c184ae5c2dfb656e89fc78c2824a4252](url)
- Steam Runtime Diagnostic: [https://gist.github.com/SOI7/c793841f5beac01a730ae37426cea4d4](url)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton Log doesn't generate when I launch the tools

## Symptoms 

All the tools from the editing kit (Tagtest, Sapien and MegaloEdit) launch correctly except Foundation. When you try to launch it, Steam says that .NET Framework 3.5 and 4.5 are needed. 

I tried installing those packages using Protontricks, but Foundation still refuses to open. The only progress I got is making the warning message disappear

## Reproduction

Just start game and select "Launch Foundation"

**Comment by kisak-valve** [comment]
Hello @SOI7, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6235#issuecomment-2171744589.
