### ISSUE TITLE
Some Proton games do not work after system upgrade

### ISSUE THREAD

**Issue by Pistos** [ValveSoftware/Proton#7839]
# Compatibility Report
- Name of the game with compatibility issues: Guild Wars 2, Kingdom Come: Deliverance, Horizon Zero Dawn Complete Edition
- Steam AppID of the game:  1284210, 379430, 1151640

## System Information
- GPU: Radeon RX 580
- Video driver version: Mesa 24.0.7
- Kernel version: 6.6.30 (Gentoo Linux)
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Pistos/748b68e2d12d1b750e1a182879c89ab3
- Proton version: 9, but also tried Experimental and 8

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- There is the [Guild Wars 2](https://github.com/ValveSoftware/Proton/issues/6547) issue, but I think my problem applies to multiple games for the same reason
- [x] that I have checked whether there are updates for my system available.

Steam log for GW2 also included [in the same gist](https://gist.github.com/Pistos/748b68e2d12d1b750e1a182879c89ab3#file-01-steam-1284210-log)

## Symptoms 

For Guild Wars 2 and Horizon Zero Dawn, the game crashes right away with a Windows/WINE-styled dialogue window. For GW2 the crash report details given are [in the same gist](https://gist.github.com/Pistos/748b68e2d12d1b750e1a182879c89ab3#file-02-guild-wars-2-crash-report-txt). Other games start up, but hang very soon.

## Reproduction

1. Start one of these games
2. witness the crash or hang

Some games (like KCD) will start up okay, and seem to work, but within a few minutes will just hang. Many non-Proton games seem to work fine.

When a game hangs (such as House Flipper, game id 613100), the steam-613100.log has thousands of repetitions of [these lines](https://gist.github.com/Pistos/748b68e2d12d1b750e1a182879c89ab3#file-03-steam-613100-tail-log)

I see in the steam debug info that there some issue with bubblewrap/bwrap is reported

`"Child process exited with code 1: bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'."`

but I checked, and bubblewrap is [emerge](https://wiki.gentoo.org/wiki/Emerge)d with the `suid` USE flag, and the kernel config has user namespaces enabled:

```
# zcat /proc/config.gz | grep USER_NS
CONFIG_USER_NS=y
```

(`kernel.unprivileged_userns_clone` doesn't exist in Gentoo, as per https://forums.gentoo.org/viewtopic-p-8690449.html )

I happened to have a copy of my steam system info from a previous issue. The diff from then (late 2023) and now is [in the same gist](https://gist.github.com/Pistos/748b68e2d12d1b750e1a182879c89ab3#file-04-steam-runtime-system-info-diff). One noticeable difference between the two is in the `pinned_libs_32` and `pinned_libs_64` sections, where we see `libGLU` is removed and `libSDL2` is added. I don't know if that's relevant.

Some historical context: I've successfully used Steam on Linux for about 4 years now. There has been a problem related to bubblewrap before, but I was able to solve them. Games were running fine until a system upgrade ([profile](https://wiki.gentoo.org/wiki/Profile_(Portage)) update) [going to Gentoo profile version 23](https://www.gentoo.org/support/news-items/2024-03-22-new-23-profiles.html). This update involved rebuilding all packages, including such core packages as `gcc`, `glibc`, `binutils`, and `libtool`.

I'm trying to experiment with launch flags like `PROTON_NO_D3D11` and `PROTON_NO_ESYNC`. Sometimes it helps a game start up, but it still eventually hangs.

**Comment by kisak-valve** [comment]
Hello @Pistos, there's an AMDGPU kernel module regression in 6.6.30 that was tracked at https://gitlab.freedesktop.org/drm/amd/-/issues/3343.

Use a different kernel point release.

**Comment by Pistos** [comment]
Thank you. Using Linux kernel 6.1.90 fixes things for me.
