### ISSUE TITLE
Microsoft flight simulator crashes because of Wine C++ error

### ISSUE THREAD

**Issue by sn1pex1** [ValveSoftware/Proton#7845]
# Compatibility Report
- Name of the game with compatibility issues: Microsoft Flight Simulator 2020
- Steam AppID of the game: 1250410

## System Information
- GPU: RTX 2060
- Video driver version: nvidia 555.42
- Kernel version: 6.9.5-arch1-1
- Link to full system information report as [Gist]: [](https://gist.github.com/sn1pex1/9846052d4cadd2fac2e0fe0222661701)
- Proton version: Proton Experimental

## I confirm:
- [ *] that I haven't found an existing compatibility report for this game.
- [ *] that I have checked whether there are updates for my system available.

[steam-1250410.zip](https://github.com/user-attachments/files/15883627/steam-1250410.zip)

## Symptoms 
When the game loads after it has been updated wine shows error message Wine C++ before there are setting when you start msfs2020 after install. I tried using protontricks to install vcrun2019.
```
error message:
Assertion failed!
Program:
Wine C++ Runtime Library
X
Z:\home\snipex.local\share\Steam\steamapps\common\MicrosoftFlightSimulator\FlightSimulator.exe
File: ../src-wine/dlls/winevulkan/loader_thunks.c
X Line: 39
Expression: "Istatus && "vkAcquireNextImageKHR
```
![image](https://github.com/ValveSoftware/Proton/assets/173137639/981de069-22e0-4284-bfbd-c9a8473321ef)

## Reproduction
Launch msfs2020 in steam with proton experimental or other proton.

**Comment by kisak-valve** [comment]
Hello @sn1pex1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-2176015799.
