### ISSUE TITLE
cant start asseto corsa with proton 9.0.2

### ISSUE THREAD

**Issue by wowfilip999** [ValveSoftware/Proton#7848]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 244210

## System Information
- GPU: nvidia rtx 4060 ventus 2x black 8G  OC
- Video driver version: 01:00.0 VGA compatible controller: NVIDIA Corporation Device 2882 (rev a1)
- Kernel version: 6.5.0-41-generic
- gist https://gist.github.com/wowfilip999/2ef29e261c8b9fdffae7521d493ffc69 (full info)
- Proton version: proton 9.0.2
-OS: Ubuntu 22.04.4 LTS
-Window system :X11

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
cant start the game 
proton log:https://gist.github.com/wowfilip999/53fa4c23db342b64620e8e8248a38c24

**Comment by kisak-valve** [comment]
Hello @wowfilip999, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/148#issuecomment-2179686080.
