### ISSUE TITLE
[Bug] Game names and icons don't show properly on Gnome dock

### ISSUE THREAD

**Issue by Korgen1** [ValveSoftware/Proton#7853]
Tested on Proton 9 & experimental with Lethal Company and Deep Rock Galactic

Icons and game names are not working properly with the gnome dock on GNOME 46.2

The icon displays as a gear and the name shows up as steam_app_(number)

Example:
![image](https://github.com/ValveSoftware/Proton/assets/65197237/5d0765e6-b2a0-4d73-afde-f3e807e76cb4)

This seems to happen for all games using proton, it only affects running games in the dock, game shortcuts show up perfectly fine.

**Comment by Korgen1** [comment]
![image](https://github.com/ValveSoftware/Proton/assets/65197237/f47f64f1-1433-4ab7-8783-685c818e9411)

Also here is a better screenshot and this is with a different game (deep rock galactic) the first was lethal company so its not exclusive to one game

**Comment by kisak-valve** [comment]
Hello @Korgen1, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/11012.

Closing as a duplicate.
