### ISSUE TITLE
Left 4 Dead 2 (550)

### ISSUE THREAD

**Issue by Jackzmc** [ValveSoftware/Proton#7855]
# Compatibility Report
- Name of the game with compatibility issues: Left 4 Dead 2
- Steam AppID of the game: 550

## System Information
- GPU: RTX 4060 TI 
- Video driver version: nvidia 550
- Kernel version: 6.9.3-76060903-generic
- [steam-550.log](https://github.com/user-attachments/files/15980564/steam-550.log)
- [System Information](https://gist.github.com/Jackzmc/1a39192bdde35aaceb22a281277d446f) 
- [Steam Runtime Diagnostics](https://gist.github.com/Jackzmc/07457c231d38f6e28e9b9046defc4fdd)
- Proton version: Experimental, 9.0-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
  - There is, but it's another issue that needs to be fixed
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

After the latest update (of Jun 25th), the game crashes when taking control over character, such as end of map intro, or taking over a bot. The game then game freezes and then closes after ~3 seconds. I did see a discussion comment stating that it does not crash when playing as the infected in versus, but I have not tested that.

The game was running fantastically before the update, with proton. Now it's unplayable

Video of loading c1m1_hotel, I stopped it the moment it began crashing
https://github.com/ValveSoftware/Proton/assets/4030546/cb25dac2-91af-4d8b-8d52-67ce3a5408f4

## Reproduction
1. Launch any map, such as `map c4m1_milltown_a`
2. Wait for the map intro scene to end
3. Crash

## Other Information
This seems to be a proton issue, as the mess of a native build does not crash. 
This also happens with no addons, on singleplayer and community servers, and with `-safe`
I wasn't sure if this should be filed here or Source-1-Games, I can post it there if need be.

**Comment by kisak-valve** [comment]
Hello @Jackzmc, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3831#issuecomment-2190299209.
