### ISSUE TITLE
SimRail - The Railway Simulator (1422130)

### ISSUE THREAD

**Issue by Tropingenie** [ValveSoftware/Proton#7860]
# Compatibility Report
- Name of the game with compatibility issues: SimRail - The Railway Simulator
- Steam AppID of the game: 1422130

## System Information
- GPU: NVIDIA GeForce RTX 4070/ 
- Video driver version: 4.6.0 NVIDIA 535.104.05 
- Kernel version: 6.1.0-11-amd64 
- Link to full system information report as [Gist](https://gist.github.com/): [System information report](https://gist.github.com/Tropingenie/ef963cf09a355a7ab6af9a429a655516)
- Proton version: Default

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Memory leak. Observed process was using ~8GB after an hour of gameplay, and upwards of 18GB after two.

## Reproduction

1. Launch game
2. Play multiplayer in dispatch mode
3. Observe memory usage continually increases, until OS deadlocks

[steam-1422130.log](https://github.com/user-attachments/files/16038426/steam-1422130.log)

**Comment by kisak-valve** [comment]
Hello @Tropingenie, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6458#issuecomment-2197854239.

As a side note, "Proton version: Default" isn't a thing, at some point you selected a global default compatibility tool in Steam's settings.

**Comment by Tropingenie** [comment]
> As a side note, "Proton version: Default" isn't a thing, at some point you selected a global default compatibility tool in Steam's settings.

My bad, it's one of those set and forget kind of menus. Will update with a comment.

**Comment by Tropingenie** [comment]
And apologies for making a duplicate issue, misunderstood how the system went and incorrectly ticked a box :(
