### ISSUE TITLE
Elite Dangerous (359320) 2024

### ISSUE THREAD

**Issue by vernwinkle** [ValveSoftware/Proton#7861]
# Compatibility Report
- Elite: Dangerous
- App ID 359320

## System Information
- GPU: embedded i7-1365U
- Video driver version: GL 4.6 - Mesa/Mesa-Vulkan 22.3.6 (Debian Bookworm up-to-date) 
- Kernel version: 6.1.0-21
- Link to full system information report: https://gist.github.com/vernwinkle/6e5a3fc0d72c20fbceaa3e5e79721afc
- Proton version: Experimental (20240628)
- Launch: gamemoderun %command%     (maintainer version of gamemode.ini)

## I confirm:
- [N] that I haven't found an existing compatibility report for this game.
- [Y] that I have checked whether there are updates for my system available.

## Symptoms

The launcher is hogging CPU except/until a game has launched and exited or possibly just a time-lapse having occurred.

I cannot enter the game with the Odyssey expansion selected.  The first item on the Odyssey menu is 'Start' and it appears to be running an introduction/tutorial which terminates after three lines of green text with an Orange Sidewinder error.  No 'Stuck Recovery' just permanent error. I suspect possibly some missing content in this introductory sequence but can't rule out a Proton-related or platform-related issue.

If I play the Horizons expansion, I initially couldn't get past the 'Planet Generation' step until what I believe was a 'shader update.' 
I can now enter the Horizons game flawlessly *except*, if I attempt to enter the atmosphere of a planet, as I transition from orbital-flight to orbital glide or orbital-flight to emergency-drop, at that point I immediately get an Orange Sidewinder error with game exit to menu and upon attempting a restart I will immediately get the Orange Sidewinder until/unless I perform a 'Stuck Recovery' first.  I have tried reducing my display resolution to 640x320 and minimising all of the performance settings.  I normally would choose 1600x900 with the 'mid' performance profile.

I have a relatively high-latency internet connection.  I don't have any reason/insight to rule latency in or out as a contributing factor.

I have the 'Optimus' dual GPU design in this laptop, with the discrete GPU being an Nvidia A500 RTX.  I have the various bumblebee packages installed. I can happily run glxgears (and various native apps) with either GPU using 'optirun' but have yet to see the Steam client recognise the discrete GPU at all.

**Comment by kisak-valve** [comment]
Hello @vernwinkle, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/150#issuecomment-2198117039.
