### ISSUE TITLE
Bad Initialization makes Zuma Deluxe nearly unusable

### ISSUE THREAD

**Issue by khvolk** [ValveSoftware/Proton#7863]
Zuma Deluxe is an old Popcap Arcade game (Steam AppId 3330). It runs with no issues
on my Notebook in a Linux environment on a 640x480 Resolution. The Display is 16:9 
with a resolution 1920x1080.

The only problem is, that the mouse cursor can move over the bounds of the game field.
Normally the shooting system of the game follows the mouse cursor. And the shooting is 
done with the left mouse button. But when the mouse cursor has left the the game field,
(see screen dump attached to this mail) this mechanic is blocked and you can not play. 

It is needed, that the mouse cursor is locked to the 640x480 playing field.

AMD Ryzen 5 4500U with Radeon Graphics
Wayland (same with X11)
ThinkPad E14 Gen 2
Endeavour OS 6.9.6-arch1-1 x86_64

![bad cursor](https://github.com/ValveSoftware/Proton/assets/28837233/01079448-6e22-42f4-ac86-bfd5ab37acbb)

**Comment by kisak-valve** [comment]
Hello @khvolk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3033#issuecomment-2198225866.
