### ISSUE TITLE
Endless Space 2 Takes 20+ Minutes to Launch

### ISSUE THREAD

**Issue by Xelveki** [ValveSoftware/Proton#7866]
# Compatibility Report
- Name of the game with compatibility issues: Endless Space 2
- Steam AppID of the game: 392110

## System Information
- GPU: AMD AMD Radeon RX 6900 XT (radeonsi, navi21, LLVM 17.0.6, DRM 3.57, 6.8.12-200.fsync.fc39.x86_64)
- Video driver version: 4.6 (Compatibility Profile) Mesa 24.1.0
- Kernel version: 6.8.12-200.fsync.fc39.x86_64
- Link to full system information report as [Gist](https://gist.github.com/Xelveki/629e780916bec433d882c4eeab369e77):
- Proton version: 9.0-2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-392110.zip](https://github.com/user-attachments/files/16060121/steam-392110.zip)

## Symptoms 

The game takes 20 to 30 minutes to start. Once started, it runs well.

## Reproduction

Launch the game from steam with any compatibility mode.

**Comment by kisak-valve** [comment]
Hello @Xelveki, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2014#issuecomment-2201543572.
