### ISSUE TITLE
White Screen Crashes on startup - Linux Ubuntu

### ISSUE THREAD

**Issue by ncummons2** [ValveSoftware/Proton#7869]
# Compatibility Report
- Name of the game with compatibility issues: Elden Ring
[steam-1245620.log](https://github.com/user-attachments/files/16067865/steam-1245620.log)

- Steam AppID of the game: 1245620

## System Information
- GPU:  AMD Radeon™ RX 580
- Video driver version:  amdgpu
- Kernel version:  6.8.0-35
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ncummons2/b3464214a1fa72bec9d951cadaee8b92
- Proton version: 7, 8, 9, and Experimental

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

## Symptoms 
I am running Linux Ubuntu 24.04 LTS. When I launch the application (used Proton 7, 8, 9, and Experimental), it gets stuck on "Initializing" step for EAC. When I followed some guides on swapping the .exe files around to avoid EAC, it started up, bypassing the EAC but then showed a white screen, the cursor and very quickly crashed. My hardware meets the minimum requirements, from what I can tell. I have an Intel® Core™ i5-8400 × 6 CPU and AMD Radeon™ RX 580 Series GPU with 16GB of RAM. I have verified the integrity of the game files

## Reproduction

Change start_protected_game.exe to start_protected_game.exe.bak and copy eldenring.exe and rename copy to start_protected_game.exe then run game normally through Steam's Proton compatability layer. Game will begin to startup and see cursor/white screen, then crash very quickly.

**Comment by b02860de585071a2** [comment]
Same issue, different hardware (Nvidia), and my logs look a bit different from yours. In my case though, both executables cause the same white screen crash. 

This is a completely fresh Steam install, fresh game install, and clean prefix. Flatpak Steam works fine, so I think we have a dependency problem starting in the last few months.

I'll link my system info and log to compare against, nothing is standing out to me though:
- [System info](https://gist.github.com/b02860de585071a2/fd1062e1376eaf6d72002635db65205f)
- [steam-1245620.log](https://github.com/user-attachments/files/18279224/steam-1245620.log)

**Comment by kisak-valve** [comment]
Hello @ncummons2, @b02860de585071a2, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-2566466523.
