### ISSUE TITLE
Assassin’s Creed Origins - Black Screen

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7872]
# Compatibility Report
- Name of the game with compatibility issues: Assassin’s Creed Origins
- Steam AppID of the game: 582160

## System Information
- Steam Deck OLED - Steam OS 3.6.8
- Proton version: Experimental

## I confirm:
- [ ☑️] that I haven't found an existing compatibility report for this game.
- [ ☑️] that I have checked whether there are updates for my system available.

## Symptoms 

2 Days ago i opened Assassin’s Creed Origins on my Steam Deck OLED and it only shows a Black Screen, The Sound of the game still plays and the controller still functions, its just the screen thats pitch black.
I tried: Verifying the game files, Reinstalling the game from Steam, Clearing the Proton Compatibility Data (which deletes all game data and the Third Party Launcher requiring it to reinstall)
I also tried connecting it to a dock onto a TV, i tried forcing resolutions and it didn’t work. I also tried switching to Proton 9 and 8 and that didn’t work. i tried the Community Made GE-Proton and i get the same issue. I have no idea what causes it

**Comment by kisak-valve** [comment]
Hello @CreeperofDoom, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/928#issuecomment-2209380223.
