### ISSUE TITLE
Proton Experimental Bleeding Edge SDL input issues with non-Steam games (not Steam Input related)

### ISSUE THREAD

**Issue by sjp761** [ValveSoftware/Proton#7874]
With the newest bleeding edge of proton experimental, sdl based input (disabling hidraw) does not work anymore so an xbox controller is not emulated

Reg file used to disable

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\winebus]
"DisableHidraw"=dword:00000001

```

Issue is probably the winebus commits on July 3rd
https://github.com/ValveSoftware/wine/commits/bleeding-edge/

**Comment by rbernon** [comment]
Proton enables both SDL and evdev/hidraw backends and chooses the most appropriate backend depending on the device. I don't think you should or need to disable hidraw for anything. Is hidraw causing problems for some devices?

**Comment by sjp761** [comment]
I disable for games that don’t support the ps5 controller when using heroic
games launcher

**Comment by rbernon** [comment]
Okay, in any case SDL should still work, even with that setting. The changes are only related to the Steam Input virtual controller, so I'm not sure why it's breaking anything in your use case.

**Comment by sjp761** [comment]
Just to make it clear, I’m not using steam input at all. I launch the game
with heroic, not steam. Proton 9.0 makes it work fine, but experimental (regular and bleeding edge) causes the issue to pop up. GE does not have the issue either.

**Comment by sjp761** [comment]
[steam-976730.log](https://github.com/user-attachments/files/16132264/steam-976730.log)
Here is a log if it helps. Steam Input is disabled through steam. Hidraw is disabled through reg file.

**Comment by rbernon** [comment]
Thanks, could you add +hid to the debug channels too?

**Comment by sjp761** [comment]
Just PROTON_LOG=+hid?

**Comment by rbernon** [comment]
Yes, that should work.

**Comment by sjp761** [comment]
[steam-sdl-issue.log](https://github.com/user-attachments/files/16132510/steam-sdl-issue.log)
Here. Steam Input and hidraw are still both disabled.

**Comment by sjp761** [comment]
[steam-976730.log](https://github.com/user-attachments/files/16165552/steam-976730.log)
Here is a log for a previous proton version where the issue did not occur

**Comment by Kawazu0** [comment]
Can this be related to the issue I have with a VKB Gladiator joystick really badly recognized unless I disable SDL and xinput as told in https://www.reddit.com/r/linux_gaming/comments/xil6ra/joystick_axes_missing_in_games/ for all previous versions of proton but doesn't work at all in experimental and 9.0 after patch ?

note : joystick became unusable, buttons are not recognized or seen as weird combinations

**Comment by sjp761** [comment]
Probably not as as my issue does not happen on Proton 9, only experimental.

**Comment by Kawazu0** [comment]
> Probably not as as my issue does not happen on Proton 9, only experimental.

you're right. I forgot to delete reg files before switching ...

**Comment by sjp761** [comment]
Any update on this?

**Comment by rbernon** [comment]
I have pushed some change to Proton Experimental bleeding-edge which might resolve this. Please have a try and let me know.

**Comment by sjp761** [comment]
Yep, my issue is fixed with proton bleeding edge. Thanks for the help.
