### ISSUE TITLE
Proton unable to install dotnet35.exe

### ISSUE THREAD

**Issue by tenplus1** [ValveSoftware/Proton#7875]
Game: Alice Madness Returns

Os: Ubuntu 24.04
GPU: Radeon 780M
Mesa: 24.0.05
Kernel: 6.8

Proton: 9.0-2

This game use to run on proton the last few times I had it installed (last year), but now it downloads, installs, builds vulkan shaders, and when run fails to open because dotnet35.exe cannot be installed.

No error is shown but in console it fails on the dotnet35.exe install and wants the user to enable it via add/remove features in Windows which I cannot access (pic shown):

https://www.digitalcitizen.life/wp-content/uploads/2020/10/win_remove_features_9.png

Would it be possible to include the basic dotnet35.exe install inside the proton layer itself as a default for games to use ?

**Comment by kisak-valve** [comment]
Hello @tenplus1, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/522#issuecomment-2210901182.
