### ISSUE TITLE
Nvidia Reflex - The Finals

### ISSUE THREAD

**Issue by Dk000t** [ValveSoftware/Proton#7877]
Proton 9.0-2
Rtx 3080 with 555.58.02 driver. 
Gnome, Wayland session with VRR.

When i enable nvidia reflex in-game with "on" or "on + boost"  frame are not capped to 138 fps as on windows with a 144hz monitor, the only effect that i can perceive is that latency seems to be higher because input is less responsive and the fluidity of the images is worse.

I have tested Proton Experimental and the Bleeding Edge version with different nvidia driver but nothing.

**Comment by kisak-valve** [comment]
Hello @Ssdj3nt, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7317#issuecomment-2211456030.
