### ISSUE TITLE
Sonic Forces (637100)

### ISSUE THREAD

**Issue by d-anez3** [ValveSoftware/Proton#7882]
# Compatibility Report
- Name of the game with compatibility issues: Sonic Forces
- Steam AppID of the game: 637100

## System Information
- GPU: AMD Custom GPU 0405 (vangogh, LLVM 14.0.6, DRM 3.45, 5.13.0-valve36-1-neptune)
- Video driver version: 4.6 (Compatibility Profile) Mesa 22.2.0 (git-17e5312102)
- Kernel version: 5.13.0-valve36-1-neptune
- Link to full system information report as [Gist](https://gist.github.com/): unavailable, Deck is on RMA :(
- Proton version: Experimental, 8.0-5

## I confirm:
- [✔️ ] that I haven't found an existing compatibility report for this game.
- [✔️ ] that I have checked whether there are updates for my system available.

## Symptoms 
Sometime in between Proton 8 and 9, controller support for Sonic Forces broke, necessitating a switch back to Proton 8.0-5 to rectify the issue. The 2 latest reports on [ProtonDB](https://www.protondb.com/app/637100) have the same issue, one on another Deck and the other on Linux Mint.

## Reproduction
- Launch the game with Proton Experimental with a controller connected, and test any inputs on the title screen. Inputs should not be recognized, even though they should be (the game doesn't need a manual switch to controller vs. keyboard input).
- Switch to Proton 8.0-5, launch the game with a controller, and test any inputs on the title screen. Inputs should be properly recognized now.

**Comment by kisak-valve** [comment]
Hello @d-anez3, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3571#issuecomment-2218660909.
