### ISSUE TITLE
FSR 3.1 causes serious frame pacing issues that are not visible in mangohud in Horizon: Forbidden West under Proton

### ISSUE THREAD

**Issue by tfinnegan937** [ValveSoftware/Proton#7883]
# Compatibility Report
- Name of the game with compatibility issues: Horizon: Forbidden West
- Steam AppID of the game: 2420110

## System Information
- GPU: AMD RX 6950XT
- Video driver version: Mesa 24.1.2
- Kernel version: 6.9.7-200.fc40.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/tfinnegan937/ffcbf842c011294a87f6ca701c3e8674
- Proton version:
Proton Experimental

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

## Symptoms 

FSR 3.1 seems to be broken under Proton for Horizon: Forbidden West. This is not true for every game --  only this specific title, and only under Proton. I do not experience this issue on Windows.

When enabling FSR 3.1 Frame Generation, steam and mangohud will report a stable framerate, but the framepacing of the image gets noticeably bad, with microstutters and an overall lack of smoothness. Disabling Frame Generation fixes the issue.

This issue is NOT visible in mangohud, or in the steam framerate counter. According to those reports, the performance is fine. The issue is extremely noticeable to the naked eye, though -- the game looks like it's running at 30 FPS.

[steam-2420110.log](https://github.com/user-attachments/files/16151115/steam-2420110.log)

## Reproduction

1. Start Horizon: Forbidden West on a 144hz monitor
2. Enable AMD FSR3 upscaling (Any quality level)
3. Enable Exclusive Fullscreen, with a 144hz refresh rate
4. Enable FSR3 Frame Generation
5. While steam (and mangohud) report a solid framerate, the game's frame pacing gets noticeably bad with stutters and poor smoothness.

**Comment by kisak-valve** [comment]
Hello @tfinnegan937, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7590#issuecomment-2218829840.
