### ISSUE TITLE
Red Dead Redemption 2 on Framework 13 AMD 7840U

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7887]
# Compatibility Report
- Name of the game with compatibility issues:  Red Dead Redemption 2
- Steam AppID of the game: 1174180

## System Information
- GPU: AMD Ryzen™ 7 7840U w/ Radeon™ 780M Graphics × 16
- Video driver version: 
- Kernel version: Linux 6.9.7-200.fc40.x86_64
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

[steam-1174180.log](https://github.com/user-attachments/files/16179989/steam-1174180.log)

Log attached to this report

## Symptoms 
Once loaded, the game runs at 1-2 FPS and is unplayable.  System is Fedora 40 running GNOME under Wayland

**Comment by ghost** [comment]
I am trying to run Red Dead Redemption 2 on a Framework 13 laptop with an AMD7840 APU (integrated Radeon 780M) with 16 GB of RAM.  The game is slow to launch and gets terrible FPS in the 1-2 per second range.  My system is running Fedora 40 with GNOME and Wayland.

**Comment by kisak-valve** [comment]
Hello @Spaht, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-2223365875.

**Comment by shamsssaman** [comment]
# [Download Red Dead Redemption 2 For Mac & Windows 💹](https://corlubar.com/dl/)

**Comment by zahrakhan18040** [comment]
# [Red Dead Redemption 2 on Framework 13 AMD Download](https://rfsjh070725nwj.cfd/?p=553&pg=0&f=Download)
