### ISSUE TITLE
The First Descendant: After 1.0.2 patch refuses to launch

### ISSUE THREAD

**Issue by maxsupermanhd** [ValveSoftware/Proton#7889]
# Compatibility Report
- Name of the game with compatibility issues: The First Descendant
- Steam AppID of the game: 2074920

## System Information
- GPU: NVIDIA GeForce RTX 4060
- Video driver version: nvidia-open 555.58.02
- Kernel version: Linux 6.9.8-arch1-1
- Link to full system information report: [Gist](https://gist.github.com/maxsupermanhd/5bb0cde87543f1afb0bed9212cfd5c1a)
- Proton version: 7, 8, 9, Experimental (others not tested)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2074920.log](https://github.com/user-attachments/files/16184439/steam-2074920.log)

## Symptoms

It does not launch.

Right after opening the window (0 frames drawn) it either closes immediately or hangs in infinite loop consuming 2 cores of the CPU.

## Reproduction

Start the game

**Comment by kisak-valve** [comment]
Hello @maxsupermanhd, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7873#issuecomment-2224104724.
