### ISSUE TITLE
Civilization VI starts in offline mode

### ISSUE THREAD

**Issue by DzyubSpirit** [ValveSoftware/Proton#7890]
# Compatibility Report
- Name of the game with compatibility issues: Civilization VI
- Steam AppID of the game: 289070

## System Information
- GPU: GeForce RTX 3050 Mobile
- Video driver version: 550.67
- Kernel version: 6.9.3-76060903-generic
- Link to full system information report as [Gist](https://gist.github.com/DzyubSpirit/7e28dcef2e5dbf0b57ab66b0b8cd48f2):
- Proton version: 1720188280 experimental-9.0-20240705

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 

Game starts in offline mode.  Multiplayer features are not working.

## Reproduction

 [Steam Runtime Diagnostics](https://gist.github.com/DzyubSpirit/72cd3055b643f5d876ce6dce2720f1cd)  
   
[civ_bad.log](https://github.com/user-attachments/files/16193179/civ_bad.log)
   
[Another issue](https://github.com/ValveSoftware/Proton/issues/7142)
 for other games starting in offline mode might be related

I'm able to start the game in online mode if I clear the cache of 2K Launcher, wait for a bit and start Civilization VI:
[civ_good.log](https://github.com/user-attachments/files/16193232/civ_good.log)
But the next time I start the game it again starts in offline mode

**Comment by kisak-valve** [comment]
Hello @DzyubSpirit, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4068#issuecomment-2225521182.
