### ISSUE TITLE
Alan Wake's American Nightmare (202750)

### ISSUE THREAD

**Issue by ranplayer** [ValveSoftware/Proton#7893]
# Compatibility Report
- Name of the game with compatibility issues: Alan Wake's American Nightmare
- Steam AppID of the game: 202750

## System Information
- GPU: RX 6700 XT
- Video driver version: Mesa 23.1.3
- Kernel version: 6.6.37
- Link to full system information report as [Gist](https://gist.github.com/): [steam_system_report-2024_07_12.tar.gz](https://github.com/user-attachments/files/16194410/steam_system_report-2024_07_12.tar.gz)

- Proton version: 9.0-2 and Experimental (2024/07/05)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Proton logs: 
- [steam-202750-proton-exp.tar.gz](https://github.com/user-attachments/files/16194420/steam-202750-proton-exp.tar.gz)
- [steam-202750-proton902.tar.gz](https://github.com/user-attachments/files/16194421/steam-202750-proton902.tar.gz)

## Symptoms
- This game is crashing during the intro video with Proton **9.0-2** and **Experimental**. No problems with Proton **8.0-5**

## Reproduction
- Just start the game

**Comment by kisak-valve** [comment]
Hello @ranplayer, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/125#issuecomment-2225578793.

**Comment by ranplayer** [comment]
Hi @kisak-valve ... I'm sorry. I don't know why the Github's search didn't return this  game.
