### ISSUE TITLE
unable to use make install

### ISSUE THREAD

**Issue by millxisyes** [ValveSoftware/Proton#7899]
verbog@Verbogs-Air ~ % cd /Users/verbog/Downloads/Proton-proton-9.0-2
verbog@Verbogs-Air Proton-proton-9.0-2 % make install
fatal: not a git repository (or any of the parent directories): .git
mkdir -p build/build--local
if [ ! -e build/build--local/Makefile ]; then \
		(cd build/build--local && ../../configure.sh --build-name="-local" --enable-ccache); \
	fi
:: Configuring with build name: -local
:: Trying to find usable container engine.
:: Trying docker.
../../configure.sh: line 24: -1: substring expression < 0
+ 
../../configure.sh: line 32: docker: command not found
:: docker is unable to run the container.
:: Trying podman.
../../configure.sh: line 24: -1: substring expression < 0
+ 
../../configure.sh: line 32: podman: command not found
:: podman is unable to run the container.
!! Container engine discovery has failed. Please fix your setup.
make: *** [configure] Error 1
verbog@Verbogs-Air Proton-proton-9.0-2 % 

^^ this is my command line, I have no idea what any of this means

**Comment by millxisyes** [comment]
im on macOS btw

**Comment by kisak-valve** [comment]
Hello @millxisyes, Proton does not support being built or run on Mac in general.

Closing in favor of #1344.
