### ISSUE TITLE
Vampire Dynasty

### ISSUE THREAD

**Issue by monjh1** [ValveSoftware/Proton#7903]
# Compatibility Report
- Name of the game with compatibility issues: Vampire Dynasty
- Steam AppID of the game: 2191500

## System Information
- GPU: NVIDIA TU106 [GeForce GTX 1650]
- Video driver version: NVIDIA 545.29.06
- Kernel version: 5.15.0-91-generic x86_64 bits
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/monjh1/76ebc1c071e24c0013c211705ecde21c
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 Can't, see below.

## Symptoms --> The game demo (Vampire Dynasty: Diaries) refuses to even download. Support direct on the site didn't acknowledge any problem with the game itself, blaming my distro instead, not answering if it was a closed demo or anything and directing me here (I know none will be able to do anything without more information - I wish I had anything, and can test whatever to try to make it work). Attached is a print of the error.
![Untitled](https://github.com/user-attachments/assets/9978baaf-7317-43c6-ade0-edbbf9c49d46)

**Comment by monjh1** [comment]
First, I want to apologize, as I have found a workaround - reinstalling the Steam package fixed the error.

Looks like the problem was the launcher itself

**Comment by kisak-valve** [comment]
Hello @monjh1, see the discussion on https://github.com/ValveSoftware/steam-for-linux/issues/7877. Closing as not a Proton issue.
