### ISSUE TITLE
Star Wars: Jedi Survivor has no sound on Ubuntu 24.04 nor Ubuntu 22.04

### ISSUE THREAD

**Issue by kimothy** [ValveSoftware/Proton#7911]
# Compatibility Report
- Star Wars Jedi Survivor
- 1774580

## System Information
- AMD 7900 GRE
- amdgpu
- https://gist.github.com/kimothy/e00aea00b06bdcd4682e5ae6e5ed302a
- proton 9.0-2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
No sound

## Reproduction
Install Ubuntu 22,04 or 24,04
Optional: Install proprietary drivers
Install steam
Install game
Launch game

**Comment by kisak-valve** [comment]
Hello @kimothy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6729#issuecomment-2240782793.
