### ISSUE TITLE
Diabotical Rogue (2805060)

### ISSUE THREAD

**Issue by Szkodnix** [ValveSoftware/Proton#7915]
# Compatibility Report
- Name of the game with compatibility issues: Diabotical Rogue
- Steam AppID of the game: 2805060

## System Information
- GPU: RX 6600
- Video driver version: Mesa 24.1.3
- Kernel version: 6.9.9
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Szkodnix/5831ccfd0296154d7f31b8cd6182b047#file-gistfile1-txt
- Proton version: 9.0-2 (the same result in Experimental and GEProton9-10)
[steam-2805060.log](https://github.com/user-attachments/files/16323917/steam-2805060.log)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms

The game crashes instantly after launching with an error report that can be sent to game developers. So far the only workaround to get the game running is by turning off antialiasing in game (when you try to turn on antialiasing, game crashes instantly). I have no idea if it is the matter of Easy AntiCheat, the game or if that's the issue of a Proton itself.

## Reproduction

Just turn on the game itself and wait. If you somehow manage to get it running, turn on antialiasing. The crash will occur.

**Comment by kisak-valve** [comment]
Hello @Szkodnix, can you test if setting the game's launch options to `PROTON_DISABLE_NVAPI=1 %command%` has an effect?

**Comment by Szkodnix** [comment]
> Hello @Szkodnix, can you test if setting the game's launch options to `PROTON_DISABLE_NVAPI=1 %command%` has an effect?

Hi Kisak.

I'm afraid not :/ Still the issue persist. Sending a log with this option turned on.
[steam-2805060.log](https://github.com/user-attachments/files/16325501/steam-2805060.log)

**Comment by Szkodnix** [comment]
The game was patched and it does not seem to have this bug anymore.
