### ISSUE TITLE
Consistent Save Game Locations - Useful for intra-game save imports

### ISSUE THREAD

**Issue by dubiousgit** [ValveSoftware/Proton#7917]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
I think it would be sensible to either have a file picker, or some background mechanism, for unifying the save location for games. 

## Justification [optional] 
As it stands, if I want to import my save up through the Witcher games, or Pillars of Eternity, or any number of other games which support "importing" your previous game saves into the next release, or an updated release, it's a faff.

Either unifying the save location for the pseudo-wine-drive that Proton uses, or creating some sort of 'helper' in the Steam interface for save game management, would close this feature gap with Windows.

I've seen a few hacks/scripts that try to automate the process, but I usually just manually copy the saves around the filesystem.

* This is an area where Linux falls short of Windows

## Risks [optional]
It depends if you consider the 'unifying' of the pseudo-wine-drive to be a risk, I suppose.

## References [optional] 

- Witcher Series
- Mass Effect Series
- Pillars of Eternity Series
- Baldur's Gate I & II
- Probably others...

**Comment by kisak-valve** [comment]
Hello @dubiousgit, there's no standardized location for saves between games. That written, this request is already being tracked at #231. Closing as a duplicate.
