### ISSUE TITLE
METAL GEAR SOLID V: THE PHANTOM PAIN problems when changing chapters

### ISSUE THREAD

**Issue by cain-dev** [ValveSoftware/Proton#7918]
# Compatibility Report
- Name of the game with compatibility issues:
METAL GEAR SOLID V: THE PHANTOM PAIN
- Steam AppID of the game:
287700

## System Information
- GPU:
RX 7600
- Video driver version:
Mesa 24.1.3-arch1.1
- Kernel version:
6.6.40-1-lts
- Link to full system information report as [Gist](https://gist.github.com/): 
https://gist.github.com/cain-dev/5716ac462bf7cd6ed9d6af04867dfaf9
- Proton version:
Proton 9.0-2

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

Can't cause i've changed chapters now

## Symptoms 
The game breaks or fast forward after doing any mission to change chapters

## Reproduction
Just go to any mission that ends a chapter, things will break or fast forward

**Comment by kisak-valve** [comment]
Hello @cain-dev, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/124#issuecomment-2241778216.
