### ISSUE TITLE
cannot run Full version of 3DMark - opens in demo mode

### ISSUE THREAD

**Issue by LDWILLIAMS** [ValveSoftware/Proton#7919]
Compatibility Report
- Name of the game with compatibility issues: 3DMark
- Steam AppID of the game: 223850

System Information
- GPU: RTX 4090
- Video driver version:  555.58.02
- Kernel version:  Linux 6.9.9-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/LDWILLIAMS/27d846f54890b01222e8cf09f83e5916
- Proton version: tried all

I confirm:
 [X] that I haven't found an existing compatibility report for this game.
[X] that I have checked whether there are updates for my system available.

## Symptoms 

Firstly, I was directed here by valve 'support'.
Open 3DMark, it runs but opens in demo mode, not the advanced version that I have paid for.
Attempting to run the few benchmarks that are available in the demo version results in a zero score and saying that system information is not available

When attempting to sign in to 3DMark.com and merge accounts I get the following error  "Account Merge
Merging of accounts failed. Please contact support if the problem persists."
I have raised a ticket with their support.

## Reproduction

[steam-223850.log](https://github.com/user-attachments/files/16329454/steam-223850.log)

**Comment by kisak-valve** [comment]
Hello @LDWILLIAMS, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4034#issuecomment-2242837292.
