### ISSUE TITLE
Valkyria Chronicles audio distortion (294860)

### ISSUE THREAD

**Issue by dghodgson** [ValveSoftware/Proton#792]
When playing VC, I get audio distortion (as if audio frames are being dropped).

I'm running this in a VM (Ubuntu 18.04.1) on QEMU-KVM (v1.5.3 on Centos 7.5.1804) with VGA pass-through (GTX 960, driver 396.54), but I'm using the GPU's HDMI output for audio, so the game isn't (to my knowledge) using the virtual ICH9 audio chipset. I've tried other games installed natively without Proton (e.g. Rocket League) in this VM without any audio issues. 

I don't have any officially whitelisted games to try, so I can't confirm if this is more of a general problem related to my setup, or if it's specific to VC.

**Comment by kisak-valve** [comment]
Hello @Toasty27, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/491#issuecomment-416406282.
