### ISSUE TITLE
FlatOut 2 (2990)

### ISSUE THREAD

**Issue by GermanAizek** [ValveSoftware/Proton#7925]
# Compatibility Report
- Name of the game with compatibility issues: **FlatOut 2**
- Steam AppID of the game: **2990**

## System Information
- **GPU: AMD Radeon RX Graphics (RADV POLARIS11) [RX 560X]**
```
$ MESA_VK_DEVICE_SELECT=list vulkaninfo
  GPU 0: 1002:67ef "AMD Radeon RX Graphics (RADV POLARIS11)" discrete GPU 0000:01:00.0
  GPU 1: 1002:15dd "AMD Radeon Vega 8 Graphics (RADV RAVEN)" integrated GPU 0000:04:00.0
  GPU 2: 10005:0 "llvmpipe (LLVM 17.0.6, 256 bits)" CPU 0000:00:00.0
```
- Video driver version: 
![image](https://github.com/user-attachments/assets/0ba30e7f-1ffa-45e4-9b58-7dc9db3d2b8d)

- Kernel version:  **6.9.10-amd64**
- Link to full system information report as [4 Gist proton logs with different aliasing modes](https://gist.github.com/GermanAizek/b90ef9263d065f74cd1b150b1a8d87e3):
- Proton version: **latest Proton Experimental**

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Low fps if you use default settings when starting game on Linux Desktop or Steam Deck, with MSAA x8 fps in range 10-15, with smoothing x4 15-20, with smoothing x2 20-25. This is very uncomfortable, but it is enough to disable anti-aliasing in configuration tool and it will be more than 90 fps on my configuration.

**Comment by kisak-valve** [comment]
Hello @GermanAizek, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7764#issuecomment-2245978476.
