### ISSUE TITLE
[Regression] Saints Row The Third hanging for 20 seconds every 15 seconds

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7927]
# Compatibility Report
- Name of the game with compatibility issues: Saints Row: The Third
- Steam AppID of the game: 55230

## System Information
- GPU: AMD Radeon RX 7800 XT
- Video driver version: Mesa 24.1.4-2
- Kernel version: Linux 6.10.0-zen1-2-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/EyBmr/d6413e423db65c2e7c9b8fb84408fcf8
- Proton version: Proton Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

 
[steam-55230.tar.gz](https://github.com/user-attachments/files/16361958/steam-55230.tar.gz)

## Symptoms 
Saints Row The Third hangs up for 20 seconds, then it runs for 15 seconds and then it hangs up for 20 seconds again. This pattern repeats infinitely. The rhythm at which the game hangs up and runs is very constant. 20 seconds and 15 seconds.

Saints Row The Third used to work fine before the Proton Experimental update.

## Reproduction
Run Saints Row The Third with Proton Experimental.

**Comment by kisak-valve** [comment]
Hello @EyBmr, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2228#issuecomment-2247919974.
