### ISSUE TITLE
Apex Legends Steam Overlay Not Loading

### ISSUE THREAD

**Issue by TheIrishman01** [ValveSoftware/Proton#7929]
# Compatibility Report
- Name of the game with compatibility issues: Apex Legends
- Steam AppID of the game: 1172470

## System Information
- GPU: NVIDIA GeForce RTX 2080 Ti
- Video driver version: nvidia 550.90.07
- Kernel version: 6.5.0-44-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 9.0-2

## I confirm:
- [Y] that I haven't found an existing compatibility report for this game.
- [ Y] that I have checked whether there are updates for my system available.

## Symptoms 
Steam Overlay doesn't work can't register the game with EA to play

**Comment by kisak-valve** [comment]
Hello @TheIrishman01, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-2248666702.
