### ISSUE TITLE
Quake Champions' new update (1.23.RETAIL.158254/161263) is causing performance issues and possible memory leaks.

### ISSUE THREAD

**Issue by AAVVIronAlex** [ValveSoftware/Proton#7936]
# Compatibility Report
- Name of the game with compatibility issues: Quake Champions
- Steam AppID of the game: 611500

## System Information
- GPU: GTX 1080Ti
- Video driver version: nvidia 555.58.02
- Kernel version: 6.10.0
- Link to full system information report as [Gist](https://gist.github.com/AAVVIronAlex/db0ef243a7eb2067df4957a578f7d4f9):
- Proton version: 9.0-2 and 8.0-5 tried. 

## I confirm:
- [+] that I haven't found an existing compatibility report for this game.
- [+] that I have checked whether there are updates for my system available.

## Symptoms 
Extremely high VRAM and RAM usage, compared to Windows, upwards of 10GBs (my GPU has 11). Insane frame drops when the framebuffer is filled (memory leak?). I was running everything at low and with the textures on High (that can be done easily with 2GB card on Windows). I have friends who can play it using 980Tis, and they play on maximum settings, while I should use Picmip (gets rid of the textures) and low textures to play it. This has happened before too, because I recall a time when I was comfortable using Ultra settings, and the game was performing really well, the fix was just to lower the settings.

**Comment by kisak-valve** [comment]
Hello @AAVVIronAlex, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/225#issuecomment-2252696630.
