### ISSUE TITLE
Using Steam API without Proton

### ISSUE THREAD

**Issue by skylar779** [ValveSoftware/Proton#7939]
I've been wondering how to make it possible to give access to the Steam API without the use of Proton / launching something from Steam for applications that aren't available on Steam.

I've been reading through the script and have done steps similar to what it does, which would be to copy a few DLL files into the wine prefix and then try and execute `"c:\\windows\\system32\\steam.exe"` with wine, followed by additional arguments to run whatever executable we actually want to run. The issue I've found here is that this part would always error out, usually something along the lines of steam.exe not being found. I've also tried setting the DLL overrides for steam.exe, but that has changed nothing.

I wonder what the process actually is like to make the Steam API available for programs through wine.

**Comment by kisak-valve** [comment]
Hello @skylar779, if the applications aren't available with Steam, then they weren't designed to use Steam's API anyway and this doesn't functionally matter. Beyond that, this is more of a question for the upstream wine project than here.
