### ISSUE TITLE
Mounted games from Windows not launching

### ISSUE THREAD

**Issue by IdiotGirl** [ValveSoftware/Proton#7944]
(Tried Proton Experimental as well as Proton 9.0-2)

Recently started running Nobara (specifically the official version, which is just KDE but is custom themed), and when I tried to launch a game from my SSD, it would say that it was launching although it wouldn't actually open. This has been an issue with my entire steam library and I'm not sure how to fix it. The only games that I've tried are Ultrakill, CS 1.6, CS Source, and TF2, and none have worked.

**Comment by kisak-valve** [comment]
Hello @IdiotGirl, noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation, sharing a Steam library folder between OSes is not supported and can lead to undefined behavior.

Having written that, Proton is known to have a hard time with Steam libraries on NTFS partitions (https://github.com/search?q=repo%3AValveSoftware%2FProton+ntfs&type=issues) and the general recommendation is to use a Linux native partition. You might get lucky with one of the community contributed workarounds at https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows.

Closing in favor of the older NTFS issue reports.
