### ISSUE TITLE
Sleeping dogs definitive edition not launching then stoping fix in Kali Linux

### ISSUE THREAD

**Issue by vidakpop** [ValveSoftware/Proton#7947]
I have used proton experimental but the launch was flickering then stoping.I fixed the issue by adding this code on the launch options 

`PROTON_USE_WINED3D=1 %command%`

**Comment by Kuratius** [comment]
https://github.com/ValveSoftware/Proton/issues/872

Try to avoid multiple tracking issues for the same piece of software.

**Comment by kisak-valve** [comment]
Hello @vidakpop, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/872#issuecomment-2255825261.
