### ISSUE TITLE
PROTON_ENABLE_NGX_UPDATER=1 causing crashes in some UE games on 2nd+ run

### ISSUE THREAD

**Issue by warcode** [ValveSoftware/Proton#7948]
I will start with conceding that I do not know if PROTON_ENABLE_NGX_UPDATER=1 is necessary or the specifics of what it does, only that it has been recommended to me for any games with DLSS-type features.

### Tested games
- Deadlink (1676130) UE4. The game I have reproduced this with.
- Crime Boss: Rockay City (2933080) UE5. This one is anecdotal as I didn't realize this was the possible cause and it was refunded, but it had the same 2nd+ launch problem.

## System Information
- GPU: NVIDIA GeForce RTX 4090
- Video driver version: NVIDIA 555.58.02
- Kernel version: 6.10.2-arch1-1
- Proton version: Experimental

## Proton Log
This is the log from a 2nd run where it crashes.
[steam-1676130.zip](https://github.com/user-attachments/files/16416079/steam-1676130.zip)

## Symptoms
If PROTON_ENABLE_NGX_UPDATER=1 is included as a launch option the first time you run a game it will run fine. If you close the game and start it again it will crash on startup to the UE error reporting tool.

## Reproduction
1. Add PROTON_ENABLE_NGX_UPDATER=1 as a launch parameter.
2. Run the game, it starts fine and runs fine.
3. Close the game.
4. Run the game, it crashes on start with an Unreal Engine crash reporter.
5. Remove PROTON_ENABLE_NGX_UPDATER=1 as a launch parameter.
6. Run the game, it starts fine and runs fine.

## Workarounds
* Remove PROTON_ENABLE_NGX_UPDATER=1 from launch parameters
* The file /SteamLibrary/steamapps/compatdata/1676130/pfx/drive_c/ProgramData/NVIDIA/NGX/models/config/versions/1/files/nvngx_mapping.json is created. If this file is made blank & read-only the game also starts fine.

**Comment by kisak-valve** [comment]
Hello @warcode, despite its name, this environment variable does not exist in Proton. It's entirely a component of the NVIDIA proprietary driver.

Report this issue to the NVIDIA devs.

**Comment by Arcitec** [comment]
Just for completeness, this has been reported to NVIDIA and is being tracked by them:

https://forums.developer.nvidia.com/t/proton-enable-ngx-updater-1-causing-crashes-in-some-ue-games-on-2nd-run/301572

And NVNGX is something related to DLSS, by the way. In Unreal engine, the settings for upscaling are under `NGX.DLSS`.

All their AI features seem to be under NGX:

https://docs.nvidia.com/ngx/index.html
