### ISSUE TITLE
EA app complains that it can't install into a network path

### ISSUE THREAD

**Issue by braiam** [ValveSoftware/Proton#7954]
# Compatibility Report
- Name of the game with compatibility issues: Titanfall2
- Steam AppID of the game: 1237970

## System Information
- Proton version: Experimental (as of 2024-08-01)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

EA complains that the installation directory is a network share/path. I'm unsure if I can fake it, but I think it expects itself to be installed in the C drive (I've seen complains about this even on Windows).

Install any game with the EA application.

**Comment by kisak-valve** [comment]
Hello @braiam, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4001#issuecomment-2263895394.

**Comment by braiam** [comment]
@kisak-valve this also happens in Battlefield 1.
