### ISSUE TITLE
CODE VEIN crashes on start.

### ISSUE THREAD

**Issue by youstolemyjuice** [ValveSoftware/Proton#7958]
# Compatibility Report
- Name of the game with compatibility issues: CODE VEIN
- Steam AppID of the game: 678960

## System Information
- GPU: GeForce RTX 3070
- Video driver version: Nvidia-dkms 555.58.02-1
- Kernel version: 6.10.2-zen1-1-zen
- Link to full system information report as [Gist](): https://gist.github.com/youstolemyjuice/9ec38d8e98d3aa1eb890592feac0a971
- Proton version: 9.0-2

## I confirm:
- [ *] that I haven't found an existing compatibility report for this game.
- [ *] that I have checked whether there are updates for my system available.

 
[steam-678960.log](https://github.com/user-attachments/files/16472261/steam-678960.log)

## Symptoms 
Game either crashes after saying running for 5 mins, shows a unreal engine crash window with no information, or (very rare cases) shows a loading screen for 3 seconds and crashes right after. Same issue occurs on both native and flatpak versions of steam.

## Reproduction 
Starting the game with any version of proton, including experimental and GE versions.

**Comment by kisak-valve** [comment]
Hello @youstolemyjuice, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3357#issuecomment-2265811349.
