### ISSUE TITLE
No audio whatsoever

### ISSUE THREAD

**Issue by GitBingus** [ValveSoftware/Proton#7965]
# Compatibility Report
- Name of the game with compatibility issues: Cyberpunk 2077
- Steam AppID of the game: 1091500

## System Information
- GPU: RTX 2060 6GB
- Video driver version: 555.58.02
- Kernel version: 6.8.0-39-generic
- Link to full system information report as [Gist](https://gist.github.com/GitBingus/a8f2597a0ba92af388ce859ab314acf5):
- Proton version: GE-Proton9-10

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 
[steam-13822821710669283328.log](https://github.com/user-attachments/files/16500011/steam-13822821710669283328.log)

## Symptoms 

When I launch the game, absolutely no audio is played. I have tried changing the Wine audio backend from Pulse to ALSA and OCC with no change, as well as other audio output devices. I downloaded the game with Heroic Game Launcher on an EXT4 Hard Drive via GOG. I then added the game to Steam so I can use Proton-GE easier. Here are my runtime commands:

gamemoderun mangohud PROTON_LOG=1 PROTON_FORCE_NVAPI=1 WINEDLLOVERRIDES="xaudio2_7=n,b" PULSE_LATENCY_MSEC=60 %command%

When I launch the game, it should play the intro track, but I hear nothing, as well as, well, anything when I actually play the game.

**Comment by kisak-valve** [comment]
Hello @GitBingus, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-2269708965.
