### ISSUE TITLE
Delta Force Hawk Ops #2709440

### ISSUE THREAD

**Issue by gitshipdone** [ValveSoftware/Proton#7966]
# Compatibility Report
- Name of the game with compatibility issues: Delta Foce Hawk Ops
- Steam AppID of the game: 2709440

## System Information
- GPU: Nvidia 4080
- Video driver version: Driver Version: 555.58.02  
- Kernel version: 6.10.2-arch1-2
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: PE, P8-P11 tests

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2709440.tar.gz](https://github.com/user-attachments/files/16501185/steam-2709440.tar.gz)

## Symptoms 
Launcher will launch and save state, but getting vulkan error and error log. 
![image](https://github.com/user-attachments/assets/c5829741-50c4-4641-97b0-c3b12c5266dd)

## Reproduction
In beta testing, just try to launch game to no avail. Launcher launches but will not go to game

**Comment by kisak-valve** [comment]
Hello @bitbucket90, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7964#issuecomment-2269717761.
