### ISSUE TITLE
All Games Fail to Launch Through Protons Version >7

### ISSUE THREAD

**Issue by E-Allie** [ValveSoftware/Proton#7967]
# Compatibility Report
- Name of the game with compatibility issues: All Games, a log of Super Monkey Ball Banana Mania is presented as an example
- Steam AppID of the game: All, 1316910 is presented as an example

## System Information
- GPU: GTX 1080 Mobile
- Video driver version: 560.28.03
- Native Vulkan Version: 1.3.283
- Mesa Version: 21.1.4
- Kernel version: 6.8.12
- Link to full system information report as [Gist](https://gist.github.com/): [System Info](https://gist.github.com/E-Allie/eda219e1ec04c885b5285cc33c716df4)
- Proton version: >7

## I confirm:
- [✓] that I haven't found an existing compatibility report for this game.
- [✓] that I have checked whether there are updates for my system available.

[steam-1316910-NOTWORKING9.log](https://github.com/user-attachments/files/16503793/steam-1316910-NOTWORKING9.log)
[steam-1316910-WORKING7.log](https://github.com/user-attachments/files/16503794/steam-1316910-WORKING7.log)

## Symptoms 
On all proton versions greater than 7, all Windows games fail to launch. A black window opens up for a brief moment, and then closes

When going through the log, I found that this could be the primary error/point of divergence between Proton 7 [working], and those greater than that, found on line 5566:

`83586.114:0124:01c0:trace:seh:handle_syscall_fault code=c0000005 flags=0 addr=(nil) ip=0 tid=01c0
83586.114:0124:01c0:trace:seh:handle_syscall_fault  info[0]=0000000000000008
83586.114:0124:01c0:trace:seh:handle_syscall_fault  info[1]=0000000000000000
83586.114:0124:01c0:trace:seh:handle_syscall_fault  rax=000000000000008f rbx=00000001222fe1a0 rcx=0000000000000000 rdx=0000000000000002
83586.114:0124:01c0:trace:seh:handle_syscall_fault  rsi=00000001222fe1b0 rdi=00005555931ceda0 rbp=00000001222fa130 rsp=00000001222fa118
83586.114:0124:01c0:trace:seh:handle_syscall_fault   r8=0000000000000002  r9=0000000000000092 r10=0000000000000000 r11=000000000000007f
83586.114:0124:01c0:trace:seh:handle_syscall_fault  r12=00000001222fe1b0 r13=00005555931ceda0 r14=0000000000000223 r15=00000001222fa140
83586.114:0124:01c0:warn:seh:handle_syscall_fault backtrace: --- Exception 0xc0000005 at (nil):.
83586.114:0124:01c0:warn:seh:dump_syscall_fault backtrace: returning to user mode ip=00006ffff950e60a ret=c0000005
83586.114:0124:01c0:err:msvcrt:_wassert (L"!status && \"vkGetPhysicalDeviceSurfaceCapabilitiesKHR\"",L"../src-wine/dlls/winevulkan/loader_thunks.c",5115)`

The comparable line in the working log is 2779

## Reproduction

Freshly install Nvidia drivers, steam and proton.

**Comment by Blisto91** [comment]
If able then i would suggest you try the new 560.31.02 driver as the one you are using introduced crash issues on a whole bunch of setups

**Comment by E-Allie** [comment]
Great news, that fixed the issue!
