### ISSUE TITLE
Halo MCC (Halo 3) Assertion Failed (during power drain throw in multiplayer?)

### ISSUE THREAD

**Issue by slagernate** [ValveSoftware/Proton#7970]
# Compatibility Report
- Name of the game with compatibility issues: Halo Master Chief Collection (MCC) (Halo 3)
- Steam AppID of the game:

## System Information
- GPU: 
- Video driver version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Reproduction

![image](https://github.com/user-attachments/assets/1232aaa4-382b-4a14-a195-5cd796736806)

**Comment by kisak-valve** [comment]
Hello @slagernate, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2907#issuecomment-2273175912.
