### ISSUE TITLE
Request GameMode by default if available

### ISSUE THREAD

**Issue by Tiagoquix** [ValveSoftware/Proton#7975]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Request GameMode by default in all games if available in the host system ( https://github.com/FeralInteractive/gamemode ). Maybe also add gamemode package as a weak (recommended) dependency when installing Steam.

GameMode optimizes PC performance when playing.

## Risks [optional]
Desktop compositor will probably be disabled, killing desktop animations while the game is open, but I think this is already done even with no GameMode (compositors do this themselves for full-screen apps).

**Comment by Tiagoquix** [comment]
This may be more relevant for steam-runtime instead of Proton's repository.

**Comment by kisak-valve** [comment]
Hello @Tiagoquix, this is out of scope for the Proton project.

In general, the tuning of hardware is something for a distro / hardware vendor to decide (or your personal decision of course), not for individual games or a compatibility layer or Steam to micromanage.
