### ISSUE TITLE
(DOOM + DOOM II) Sprite flickering

### ISSUE THREAD

**Issue by SladeWilson52** [ValveSoftware/Proton#7976]
# Issue:
The new re-release of the classic DOOM games has some graphical glitches when running under Proton, leading to the entity sprites to flicker every few seconds.

# To reproduce:
Just run the game and play a level, you'll see it in front of you.

# System Information:
**CPU:** AMD Ryzen 3 2300X (4) @ 3.500GHz
**GPU:** AMD ATI Radeon RX 6600 XT
**RAM:** 16GB
**OS:** Artix Linux x86_64
**Kernel:** 6.10.2-artix1-1
**Proton Version:** Proton Experimental

**Comment by kisak-valve** [comment]
Hello @SladeWilson52, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1534#issuecomment-2277773617.
