### ISSUE TITLE
Once Human

### ISSUE THREAD

**Issue by glenni83** [ValveSoftware/Proton#7982]
# Compatibility Report
- Once Human - Stutter
- Steam AppID of the game: 2139460
>
## System Information
- GPU: RTX 4090
- Video driver version: nvidia 560 driver 
- Kernel version: 6.9 Arch
- (https://gist.github.com/glenni83/5f0194b69a90d63c72f405ef458876a0)
- Proton version: Experimental

## I confirm:
- [ *] that I haven't found an existing compatibility report for this game.
- [ *] that I have checked whether there are updates for my system available.

In windows as a write so cant add proton log.

## Symptoms
Major stutter even the game uses 15 min to compile vulkan shaders before starting the game. There are slowness in the builder options. Some built object also causes major stutter as you look at it, the second you look away, it eases up.

## Reproduction
Looking at a built garage or water collector the game starts to stutter. Going into cities, hubs or base can stutter.

Looking at ProtonDB no one has found a fix or made the game stable yet. Game has been out for over a month, with a lot of players around 300k-400k in it. But its not playable. The stutter is so bad in linux that I get motion sickness out of it. You can boot it up once and it looks fine. But when you start to come to hubs, cities or your own base, it gets really bad. 

I have tested all versions of proton from valve including experimental, where the 7.0.6 was the best working one but not flawless, I have teste proton-tkg, ge-proton and proton-cachyos, nothing works. I tested different kernels without luck, different distros, but its the same issue no matter what you do. 

So, if there was not a proton problem, one of those 400.000 players should have found a solution by now. 

Some state that they use DXVK_ASYNC=1 to fix the problem. But as far as i know, that feature has been disabled since proton 7. 
one is saying 7-50-GE on Vega64 and Arch works flawlessly. (This might be someone writing in the torturial, where the game runs good. Its when you exit torturial and get into the open world the problems starts.

**Comment by kisak-valve** [comment]
Hello @glenni83, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7888#issuecomment-2282264956.

**Comment by glenni83** [comment]
Okay thank you.

Seems they found a pretty good option to run the game from proton 7-50-GE. I tested the game my self on that proton now, and it seems pretty good. 

Some minor micro hangs from time to time, but its superior to anything else that I have tested so far. Its close to how good it runs on windows. I dont know Why exact this proton works. 

The community has been trying to run the game for 5 weeks now, without luck.  So typical that one found this solution last night as I was posting it now.

**Comment by nazgulsenpai** [comment]
Solution of using a GE 7-5X version no longer works as of  9/24 (I used GE 7-55) -- WinLicense Error prevents the game from loading on Proton versions < 9, which means massive stuttering. Tried every official Proton 9/Experimental/Hotfix release as well as every minor version of GE-Proton9-X. It runs, but it's virtually unplayable. I wonder what the difference is in GE 7-55 that made it run perfectly. Oh well.

![image](https://github.com/user-attachments/assets/13ebec17-4668-4947-a4b2-133665ddb8d8)

**Comment by glenni83** [comment]
I get the WinLicense error as well. 

Tinker Steps:
Custom Proton: GE, Changed configuration
In the filesteamapps/common/Once Human/Documents/GraphicConfig.xml find the following tags and set the value to <setting_enable_d3d12>0</setting_enable_d3d12> -> <setting_enable_d3d12>1</setting_enable_d3d12>, <setting_use_d3d12>0</setting_use_d3d12> -> <setting_use_d3d12>1</setting_use_d3d12>.

If you're experiencing a WinLicense error that says something to the effect of the DLL files don't match: I was using GE-Proton7-55 which worked perfectly with the game, but after a recent update I could not get the game to launch with any older version of Proton (anything older than 9). The problem is with other versions of Proton the game stuttered horribly, but I found that enabling DX12 in the GraphicsConfig.xml makes the game run as well as it did on 7-55.

Then we have reports that the experimental-proton runs better then 7.x

Worth a try. Servers are down for another 3 hours, so I cant confirm if it works yet.
