### ISSUE TITLE
Endzone - A World Apart  ( 933820 )

### ISSUE THREAD

**Issue by GhChancellor** [ValveSoftware/Proton#7983]
# Compatibility Report
- Name of the game with compatibility issues: Endzone - A World Apart
- Steam AppID of the game: 933820

## System Information
- OS: Ubuntu 24.04 LTS x86_64 
- Kernel: 6.8.0-40-generic 
- CPU: Intel i7-4790K (8) @ 4.400GHz 
- GPU: NVIDIA GeForce RTX 2080 Ti Rev. A
- Driver Version: 4.6.0 NVIDIA 535.183.01 
- Memory: 5154MiB / 15926MiB 
- Proton versions: Proton GE-9.11, Proton experimental, Proton 9.0-2, Proton 8.0-5, Proton 7.0-6, Proton 6.3-8, Proton 5.13-6, Proton 5.0-10
- Log: [steam-933820.zip](https://github.com/user-attachments/files/16579055/steam-933820.zip)

## I confirm:
- [I confirm] that I haven't found an existing compatibility report for this game.
- [I confirm] that I have checked whether there are updates for my system available.

## Symptoms 
The game doesn't start at all. It only "runs" for a few seconds before stopping.

I've tried GE-Proton 9.11, Proton Experimental, Proton 9.0-2, Proton 8.0-5, Proton 7.0-6, Proton 6.3-8, Proton 5.13-6, Proton 5.0-10.

I've also tested various launch options like:
PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 %command%

## Reproduction
The game doesn't start at all. It only "runs" for a few seconds (the initial loading screen) before stopping.

**Comment by kisak-valve** [comment]
Hello @GhChancellor, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4690#issuecomment-2283838177.
