### ISSUE TITLE
Hunt: Showdown (594650) new update

### ISSUE THREAD

**Issue by medexs** [ValveSoftware/Proton#7989]
# Compatibility Report
- Name of the game with compatibility issues: **Hunt: Showdown 1896**
- Steam AppID of the game: **594650**

## System Information
- GPU: **AMD Radeon RX 7800 XT**
- Video driver version: **4.6 Mesa 24.1.5**
- Kernel version: **6.10.3-200.fc40.x86_64**
- Link to full system information report as [Gist](https://gist.github.com/): [Steam System Information](https://gist.github.com/medexs/b5406d5dcc886b831a03bf07811267d1), [Steam Runtime Diagnostics](https://gist.github.com/medexs/dd1ed28daed1467efc3e7924dfa665c4)
- Proton version: **Proton Experimental**

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
The game Hunt: Showdown has been working completely fine on Linux via Proton up until today - there has been a big update to this game, where the biggest thing is an engine update, new UI and a new map. After starting the game, it stucks on black screen and crashes in a few seconds.

## Reproduction
Crashes after starting the game.
- Log file: [steam-594650.log](https://github.com/user-attachments/files/16626280/steam-594650.log)

**Comment by kisak-valve** [comment]
Hello @medexs, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3898#issuecomment-2291537478.
