### ISSUE TITLE
Hunt: Showdown 1896 no longer working

### ISSUE THREAD

**Issue by nintendoeats** [ValveSoftware/Proton#7990]
# Compatibility Report
- Name of the game with compatibility issues: Hunt: Showdown 1896
- Steam AppID of the game: 594650

## System Information
- GPU: Radeon 5700XT
- Video driver version: Mesa 23.2.1-1ubuntu3.1~22.04.2
- Kernel version: 5.15.0-118-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/nintendoeats/5316dabc24c2fa8e72dff35c878b94be
- Proton version: 9.0-2 and Experimental

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

[steam-594650.log](https://github.com/user-attachments/files/16627691/steam-594650.log)

## Symptoms
The game gives a black screen and cursor, sits there for a while, then closes.
This was not the case prior to the new update for Hunt: Showdown.

## Reproduction
1. Launch the game.

**Comment by kisak-valve** [comment]
Hello @nintendoeats, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3898#issuecomment-2291715112.
