### ISSUE TITLE
Fcitx5 can't  input chinese character in Monster Hunter World

### ISSUE THREAD

**Issue by po4920826** [ValveSoftware/Proton#7994]
# Compatibility Report
- Name of the game with compatibility issues:Monster Hunter:World
- Steam AppID of the game:582010

## System Information
- GPU: RTX 4070 SUPER
- Video driver version: nvidia 555.58.02
- Kernel version: 6.10.5-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/po4920826/c9b0ca623e4c8a5ca7dee746078aed9a):
- Proton version:proton-9.0-2
[steam-582010-proton9-2.log](https://github.com/user-attachments/files/16645630/steam-582010-proton9-2.log)

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
I am using the Steam Proton-9.0-2 compatibility layer on Arch Linux with the KDE Plasma 6 desktop (in Wayland mode) to play Monster Hunter: World. When I press Enter in-game to open the chat window, I am unable to type text using the Fcitx5 Chinese input extension. The input extension is running properly, but no Chinese characters are being input into the chat window. This issue does not occur when using the Proton-8.0-5 version.

## Reproduction
install fcitx5 IME:
sudo pacman -S fcitx5 fcitx5-gtk fcitx5-qt fcitx5-chinese-addons fcitx5-config-qt

edit ~/.bash_profile  , add these lines:
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx

Reboot, open systemsettings -- input method  -- add input method ,add pinyin

Launch steam ,play Monster Hunter :World , press Enter in-game to open the chat window.Input chinese character with fcitx5 pinyin (just typing randomly ,press space to submit).In my case,no Chinese characters are being input into the chat window.

I have uploaded a video on youtube:
https://www.youtube.com/watch?v=ug7eZd-fm90

**Comment by kisak-valve** [comment]
Hello @po4920826, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/175#issuecomment-2294915448.
