### ISSUE TITLE
gzdoom-rt fails due to missing `VK_KHR_external_fence_win32`

### ISSUE THREAD

**Issue by Vash63** [ValveSoftware/Proton#7997]
# Compatibility Report
- Name of the game with compatibility issues: gzdoom-rt mod for Doom II
- Steam AppID of the game: N/A - not on Steam (mod for appid 2280 but bug is not for that app)

## System Information
- GPU: RTX 3090
- Video driver version: 560.31.02
- Kernel version: 6.10.4-200.fc40.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Vash63/e02125eb4f43802f908355be00d71f26
- Proton version: Experimental as of 2024-08-18

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-2280.log](https://github.com/user-attachments/files/16648409/steam-2280.log)

## Symptoms 

Game fails to launch due to missing Vulkan extension in winevulkan
![Screenshot from 2024-08-18 14-15-08](https://github.com/user-attachments/assets/5fab010a-75f4-427a-a043-021cbac1aa7e)

## Reproduction

Download and unzip: https://github.com/vs-shirokii/gzdoom-rt/
Install Doom I & II on Steam (appid 2280)
Copy DOOM2.wad into gzdoom-rt directory
Set Steam launch options to target gzdoom instead of default, i.e. (adjust paths as needed): 
```
cmd=(%command%); cd "$PWD/gzdoom-rt-1.0.2/"; cmd[-1]=$PWD/gzdoom.exe; PROTON_LOG=1  "${cmd[@]}"
```

**Comment by kisak-valve** [comment]
Hello @Vash63, we're tracking issues with game mods with the game being modified. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1534#issuecomment-2295254691.
