### ISSUE TITLE
Hunt: Showdown 1896 unbearable input delay

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7998]
# Compatibility Report
- Name of the game with compatibility issues: Hunt: Showdown 1896
- Steam AppID of the game: 594650

## System Information
- GPU: RX 6800M
- Video driver version: Mesa 24.1.6
- Kernel version: 6.10.5
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/StellarHarbour/46eed07bacadedde54aa40d58d94395d
https://gist.github.com/StellarHarbour/7e1769b89f925f42596544efdf4bebbd
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-594650.zip](https://github.com/user-attachments/files/16651107/steam-594650.zip) X11 with bug happened
[steam-594650 (1).zip](https://github.com/user-attachments/files/16651903/steam-594650.1.zip) Wayland with bug happened

## Symptoms 

After some time, game become laggy/slimy as hell, with tons(seconds) of delay, you can't move or aim adequately, it will be fixed only after game restart, happens on both X11 and Wayland for me, KDE.

This is how it looks like: 

https://github.com/user-attachments/assets/590afce3-0eca-46c0-bfea-858024d21e6e

Related reddit post: https://www.reddit.com/r/HuntShowdown/comments/1cf072a/huge_input_delay_like_8_seconds_delay_after/

Steam Runtime Diagnostics: https://gist.github.com/StellarHarbour/63cd5228780bdbb41f9e8862456e221b

**Comment by kisak-valve** [comment]
Hello @StellarHarbour, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3898#issuecomment-2295381801.
