### ISSUE TITLE
New Steam Play/Proton performs poorly with OpenGL games

### ISSUE THREAD

**Issue by rea987** [ValveSoftware/Proton#80]
As I have just tried with Quake, GLQuakeGL, GLQuakeWorld and Deus Ex; OpenGL renderers crash the games or performs extremely poorly.

- [Quake](https://store.steampowered.com/app/2310/QUAKE/) (WinQuake) and QuakeWorld which use software renderer work fine.
- GLQuake and GLQuakeWorld crashes.
- [Deus Ex: Game of the Year Edition](https://store.steampowered.com/app/6910/Deus_Ex_Game_of_the_Year_Edition/) works fine with stock Direct3D renderer.
- Deus Ex: Game of the Year Edition works okay with software renderer.
- Deus Ex: Game of the Year Edition runs extremely bad with stock OpenGL renderer. (1 FPS)
- Deus Ex: Game of the Year Edition runs extremely bad with [UTGLR](http://www.cwdohnal.com/utglr/)'s OpenGL renderer. (1 FPS)

System:
Linux Mint 19 (x64) Mate, GeForce 940M (396.51 via Proprietary GPU Drivers PPA), Intel i5-6200U CPU

My  Steam - System Information:
https://gist.github.com/rea987/7a5d859effac81a09928b16520f88781

**Comment by Xalphenos** [comment]
I had major issues with Doom when It was trying to launch in OpenGL mode.  Vulkan mode was perfect.

**Comment by dawid2193487** [comment]
Quake Live uses OpenGL and it has no problems with rendering and it's performance is on par with Windows.

**Comment by IceAmaura** [comment]
OpenGL on Proton has worked for me at normal speed with the games I have tried. Using Mesa 18.3dev, LLVM7 and Intel Integrated with i915.

**Comment by rea987** [comment]
Making **Deus Ex** (OpenGL) and **Prey** (2006) to use native desktop resolution with native aspect ratio by editing games' config files fixed issue with those particular games. GLQuake still cannot be launched despite 2 Steam updates and a driver update for Nvidia.
