### ISSUE TITLE
Graphics Glitches in Final Fantasy XVI Demo

### ISSUE THREAD

**Issue by Cardiacman13** [ValveSoftware/Proton#8003]
# Compatibility Report
- **Name of the game with compatibility issues:** Final Fantasy XVI Demo
- **Steam AppID of the game:** 2738000
## System Information
- **GPU:** 4090 mobile
- **Video driver version:** 560.31.02
- **Kernel version:**  Linux 6.10.5-2
-  both X11/Wayland were tested.
- **Proton version:** experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
There are significant graphical glitches that occur when entering the first city area in the Final Fantasy XVI demo. The screen distorts, and the glitches make the game difficult to play.

![glitch ffxvi](https://github.com/user-attachments/assets/cf7b3832-f473-45c1-820d-54bf17deef23)

## Reproduction
1. Launch the Final Fantasy XVI demo.
2. Progress until the first city area is reached.
3. Observe the graphical glitches that occur immediately upon entering the city.

[steam runtime diagnostic ](https://gist.github.com/Cardiacman13/05dd1c3aa06711a298c2cbfef374c28a)
[System Information](https://gist.github.com/Cardiacman13/08c0d2179acae0e7706dc999cefe725e)

**Comment by Cardiacman13** [comment]
My bad already open here : https://github.com/ValveSoftware/Proton/issues/8001

**Comment by kisak-valve** [comment]
Hello @Cardiacman13, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/8001#issuecomment-2297658915.
