### ISSUE TITLE
OpenSuse Leap 15.6 // Steam // Proton // NVIDIA

### ISSUE THREAD

**Issue by killproc84** [ValveSoftware/Proton#8007]
Hi Communtity,
i try my luck here ;-) 

I've been trying for some time to get Windows games like GTA V and The Corridor to run with Steam on OpenSuse Leap 15.6 via Proton, but unfortunately I can't get any clues as to why the games won't start at all. The Play button goes to Cancel and then Back to Play. With GTA I also get the dialog for Story or Online and the product key.
I've already tried several versions of Proton in both;

- 3.7
- 5.13
- 6.3
- 7.0
- 8.0
- 9.0
- Experimental
- and GE 9.11

I used the start option "PROTON_LOG=1 %command%" to create a log file, but not much comes out;

```
======================
Proton: 1721062986 proton-9.0-2e
SteamGameId: 271590
Command: ['/run/media/killproc/Daten/Linux/Steam-Spiele/steamapps/common/Grand Theft Auto V/PlayGTAV.exe']
Options: {'noopwr', 'forcelgadd'}
depot: 0.20240806.97927
pressure-vessel: 0.20240806.0 scout
scripts: 0.20240806.0
sniper: 0.20240806.97927 sniper 0.20240806.97927
Kernel: Linux 6.4.0-150600.23.17-default #1 SMP PREEMPT_DYNAMIC Tue Jul 30 06:37:32 UTC 2024 (9c450d7) x86_64
Language: LC_ALL None, LC_MESSAGES None, LC_CTYPE None
Effective WINEDEBUG: +timestamp,+pid,+tid,+seh,+unwind,+threadname,+debugstr,+loaddll,+mscoree
======================
```

```
======================
Proton: 1705700124 proton-8.0-5c
SteamGameId: 1347030
Command: ['/run/media/killproc/Daten/Linux/Steam-Spiele/steamapps/common/THE CORRIDOR/THE CORRIDOR.exe']
Options: {'forcelgadd'}
depot: 0.20240806.97927
pressure-vessel: 0.20240806.0 scout
scripts: 0.20240806.0
sniper: 0.20240806.97927 sniper 0.20240806.97927
Kernel: Linux 6.4.0-150600.23.17-default #1 SMP PREEMPT_DYNAMIC Tue Jul 30 06:37:32 UTC 2024 (9c450d7) x86_64
Language: LC_ALL None, LC_MESSAGES None, LC_CTYPE None
Effective WINEDEBUG: +timestamp,+pid,+tid,+seh,+unwind,+threadname,+debugstr,+loaddll,+mscoree
======================
```

How can I continue troubleshooting?
Many users report success with OpenSuse, so I must have missed something.
I installed Steam with zypper and other facts;

- Manufacturer: LENOVO
- Model: LNVNB161216
- CPU brand: AMD Ryzen 7 5800H with Radeon Graphics
- RAM: 15842 MB

- Driver: NVIDIA Corporation NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2
- Driver version: 4.6.0 NVIDIA 550.100
- OpenGL version: 4.6

- "openSUSE Leap 15.6" (64 bit)
- Kernel version: 6.4.0-150600.23.17-default

Thank you
Regards

**Comment by kisak-valve** [comment]
Hello @killproc84, a header only Proton log hints that something went awry before the game itself had a chance to start. I would completely close Steam, then run `steam` from a terminal and check if there's a hint in the terminal spew when telling Steam to start the game.

This is most likely a filesystem issue. What filesystem are you using with `/run/media/killproc/Daten/Linux/Steam-Spiele`? The general recommendation is to use a Linux native filesystem with Proton.

**Comment by killproc84** [comment]
Hi @kisak-valve 
thanks, why didn't I think of that: /run/media/killproc/Daten/ is a filesystem shared with Win11 - so it's an exFAT FS and could be a problem - I'll try changing the installation directory. Here is the full output when I start the game;

```
chdir "/run/media/killproc/Daten/Linux/Steam-Spiele/steamapps/common/THE CORRIDOR"
ERROR: ld.so: object '/home/killproc/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/killproc/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Adding process 20304 for gameID 1347030
ERROR: ld.so: object '/home/killproc/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/killproc/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/killproc/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Adding process 20305 for gameID 1347030
Adding process 20306 for gameID 1347030
Adding process 20402 for gameID 1347030
Proton: Upgrading prefix from None to 9.0-200 (/run/media/killproc/Daten/Linux/Steam-Spiele/steamapps/compatdata/1347030/)
Traceback (most recent call last):
  File "/home/killproc/.local/share/Steam/steamapps/common/Proton 9.0 (Beta)/proton", line 1567, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/killproc/.local/share/Steam/steamapps/common/Proton 9.0 (Beta)/proton", line 1477, in init_session
    g_compatdata.setup_prefix()
  File "/home/killproc/.local/share/Steam/steamapps/common/Proton 9.0 (Beta)/proton", line 793, in setup_prefix
    self.migrate_user_paths()
  File "/home/killproc/.local/share/Steam/steamapps/common/Proton 9.0 (Beta)/proton", line 771, in migrate_user_paths
    os.symlink(src=link, dst=old)
PermissionError: [Errno 1] Operation not permitted: '../AppData/Local' -> '/run/media/killproc/Daten/Linux/Steam-Spiele/steamapps/compatdata/1347030/pfx/drive_c/users/steamuser/Local Settings/Application Data'
Uploaded AppInterfaceStats to Steam
Removing process 20402 for gameID 1347030
Removing process 20306 for gameID 1347030
Removing process 20305 for gameID 1347030
Removing process 20304 for gameID 1347030

```

- So I have to pay attention to that too;
`ERROR: ld.so: object '/home/killproc/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

Thanks for the quick reply - I'll report back when I've tested it.

Regards

**Comment by kisak-valve** [comment]
`PermissionError: [Errno 1] Operation not permitted: '../AppData/Local' -> '/run/media/killproc/Daten/Linux/Steam-Spiele/steamapps/compatdata/1347030/pfx/drive_c/users/steamuser/Local Settings/Application Data'` is the critical detail, and `ERROR: ld.so: object '/home/killproc/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.` is a red herring.

Using Proton with exFAT is not supported at this time (#3835), and separately, sharing a Steam Library folder between OSes is not supported and can lead to undefined behavior (https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation).

Closing in favor of #3835.

**Comment by killproc84** [comment]
Thanks, it works :-) 
and, it's not to share Steam, but other files ;-)
