### ISSUE TITLE
Mega Man Legacy Collection (363440) Whitelist request.

### ISSUE THREAD

**Issue by chrisc174** [ValveSoftware/Proton#801]
Mega Man Legacy Collection
AppID: 363440

My Specs
AMD Ryzen 1700x
GTX 1060 6 GB
Driver: Nvidia 396.54
Proton Beta 3.7-4
16 GB of DDR4 Ram

Game works flawlessly with one exception, you have to have the controller plugged in before you start the game for it to recognize it. Plugging one in mid game and you'll have to restart for the game to see it. No big deal, but eventually and hopefully it's worked out.

**Comment by chrisc174** [comment]
gist: https://gist.github.com/chrisc174/3745548874211e8d95eccfbb2e3998b2

**Comment by kisak-valve** [comment]
Hello @chrisc174, I've added this to the existing whitelist request at https://github.com/ValveSoftware/Proton/issues/654#issuecomment-416553166.

**Comment by kaincenteno** [comment]
@chrisc174 did you have issues with the audio? currently audio seems to be a bit off.
