### ISSUE TITLE
Im going to share a video from the CachyOs community of the state around RTX and DX12, where we do a lot of performance testing on a dailie basis for games..

### ISSUE THREAD

**Issue by glenni83** [ValveSoftware/Proton#8013]
https://www.youtube.com/watch?v=GaJmkgWXWHI

This video is made by A1RM4X.

Its a performance benchemark video, around some broken featurs we see today. Then the findings around different issues so far.

**Comment by kisak-valve** [comment]
Closing as an invalid issue report.
