### ISSUE TITLE
Unable to use specific version of Proton within steam for a specific game

### ISSUE THREAD

**Issue by Theoryless** [ValveSoftware/Proton#8014]
# Compatibility Report
- Name of the game with compatibility issues: theHunter: Call of the Wild™
- Steam AppID of the game:  518790

## System Information
- GPU: 6600xt
- Video driver version: driverInfo  = Mesa 24.2.0 - kisak-mesa PPA

- Kernel version: 6.9.1-060901-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Theoryless/59007b24610b4eeb60104de9f1db9692
- Proton version: 5.13-6

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

Unable to do this as no log gets generated, but here are logs from terminal when running steam: 
https://gist.github.com/Theoryless/8b6779bc7a4f7b8323c301eafa3c4ea1

## Symptoms 

Getting the above error when running this version of proton. This game ONLY works on this version of proton without getting a driver error. I used to play this game exclusively on this version when I was on linux a year ago, and I just came back to linux after a hiatus on windows and I can't play this game. Please assist me with getting this version working.

**Comment by kisak-valve** [comment]
Hello @Theoryless, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3073#issuecomment-2305482998.
