### ISSUE TITLE
SENRAN KAGURA Peach Ball (1074080)

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/Proton#8015]
# Compatibility Report
- Name of the game with compatibility issues: SENRAN KAGURA Peach Ball 
- Steam AppID of the game: 1074080

## System Information
- 1 TB OLED Steam deck LE 
- Proton version: Experimental 

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Characters face backwards during cutscenes out of the box using dxvk, switching to wined3d fixes this, but makes the game unable to boot unless you launch it in desktop mode.

![download](https://github.com/user-attachments/assets/2a87264f-bda1-48a1-8603-f830a814edf6)

How it should look
![Screenshot_20240822_191242_YouTube](https://github.com/user-attachments/assets/5764199e-b85c-40d6-b4e8-fae04b789f29)
[steam-1074080.log.txt](https://github.com/user-attachments/files/16720799/steam-1074080.log.txt)

## Reproduction
Just start the game up, and go through the prologue and you'll run into it rather quick

**Comment by waspennator** [comment]
Character models being backwards have been fixed on dxvks end and should be working once proton pulls in updates for it.

Providing a log for the wined3d game mode crash since that's the only real issue left now.

[steam-1074080.log.txt](https://github.com/user-attachments/files/16729242/steam-1074080.log.txt)

**Comment by kisak-valve** [comment]
Hello @waspennator, using the PROTON_USE_WINED3D runtime option is not considered supported. If you want to pursue that crash further, then reproduce that issue with upstream wine, and follow up with the upstream wine devs.

**Comment by waspennator** [comment]
Alright then, I'll just leave it at that and close the issue when the dxvk fixes come in then. Mostly brought it up since it works in desktop mode but crashes in game mode with wined3d.

**Comment by waspennator** [comment]
Issue with backwards characters is resolved with Experimental, closing.

Game is now ready to be retested for deck support.
