### ISSUE TITLE
Splitgate 2 (2918300 or 3145170)

### ISSUE THREAD

**Issue by Wolfhound905** [ValveSoftware/Proton#8021]
# Compatibility Report
- Splitgate 2
- 2918300 or 3145170

!Note: I got 3145170 from the proton logs, but the store page uses 2918300? They both link to the same game.

## System Information
- GPU: RTX 4090
- Video driver version: nvidia 555.58.02
- Kernel version: 6.10.6-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/Wolfhound905/9cd5a50d82a7da5ae8b9b0472198fcb3)
- [Steam Runtime Diagnostics](https://gist.github.com/Wolfhound905/7004157193a71eb89884fc4c908a7d5f)
- Proton version: 1724520524 experimental-bleeding-edge-9.0-114530-20240824-p95282c-w54c797-deb8d18-v56cc91

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
[steam-3145170.log](https://github.com/user-attachments/files/16737759/steam-3145170.log)

![image](https://github.com/user-attachments/assets/1db79ca9-0bdb-4023-af26-110d43f72043)

## Reproduction
Run the game.

**Comment by Wolfhound905** [comment]
Closing as duplicate.

**Comment by ProjectSynchro** [comment]
Going to leave a link to the duplicate here as ProtonDB points to this issue: https://github.com/ValveSoftware/Proton/issues/8010
