### ISSUE TITLE
Keyboard do not works and the buttons have moved from their normal places

### ISSUE THREAD

**Issue by Scinetist** [ValveSoftware/Proton#8022]
System - kubuntu 22.04
Game - Satisfactory (update 8, last ver)
PC - 4070 & r7 7700x

when I load a save in satisfactory and try to do something I can't do anything - only the mouse and the tab and escape keys work (maybe something else, I don't remember exactly). I also had this problem on epic games

And I also have problems applying settings, because all the buttons in all the menus have moved to the right and down, and some of them are behind the screen

https://github.com/user-attachments/assets/c01274e3-bb68-435c-aaf2-80201cbab8d8 - screen capture

**Comment by kisak-valve** [comment]
Hello @Scinetist, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7580#issuecomment-2308825541.
