### ISSUE TITLE
[Black Myth:Wukong] Specific scene makes game fps extremely low for several seconds

### ISSUE THREAD

**Issue by kamikaze211** [ValveSoftware/Proton#8024]
# Compatibility Report
- Name of the game with compatibility issues: Black Myth:Wukong
- Steam AppID of the game: 2358720

## System Information
- GPU: RX7900GRE
- Video driver version: 24.2.0
- Kernel version: 6.10.6-zen1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kamikaze211/d247a0c5ab77fc83b22b28a2e2bc10b0
- Proton version: Proton Experimental

## I confirm:
- [Yes] that I haven't found an existing compatibility report for this game.
- [Yes] that I have checked whether there are updates for my system available.

[steam-2358720.tar.gz](https://github.com/user-attachments/files/16741183/steam-2358720.tar.gz)

## Symptoms 
Specific scene makes game fps extremely low for several seconds, with frame time extremely long, and GPU usage very low.

## Reproduction
Attract archers to shoot arrows, then move to the bridge.
You will see the GPU usage will be very low, and the fps will be shown as none, and the frame time will be extremely long.
And I had tried to change another kernel, another Proton version, and updated the system to the latest, and set to the lowest graphic settings in the game.
I also tested on Windows 10, but without this issue.

![vlcsnap-2024-08-26-01h02m59s371](https://github.com/user-attachments/assets/3a94ac2d-c3b4-4977-9731-5b08d36c5c5a)

![vlcsnap-2024-08-26-00h49m28s313](https://github.com/user-attachments/assets/d5e8ad81-bad3-4e3b-9d8c-e2be76e0fbdc)

**Comment by kisak-valve** [comment]
Hello @kamikaze211, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/8004#issuecomment-2308926326.
