### ISSUE TITLE
Distorted pixelated graphics with Radeon RX 7900 XT with some games

### ISSUE THREAD

**Issue by jbwyatt4** [ValveSoftware/Proton#8026]
Severe pixalation occurs with games that does not show on Windows. Not sure what component to classify this as it could be the kernel space or the mesa user space drivers, or Proton with Steam. I believe it has happened since I got the card. One of my friends has an Radeon RX 7900 XTX that does not have this issue.

This issue does not occur on Windows.

The default choice Steam selects for Proton was used. Usually this is Proton Experimental. Fedora 40 with an Intel 10700K. Tested on both an upgraded Fedora 40 and a fresh Fedora 40 install on a separate ssd.

This was tested on both an upgraded to Fedora 40 and a fresh Fedora 40 install (only the first two games where it does show was tested on the fresh install). I am aware some of these games have Linux ports.

Pictures:
https://imgur.com/a/pMHcGhK

Games where it does show:
Batman Arkham Origins
Batman Arkham City
Lego Batman 3
Lego Marvel Super Heroes
Lego DC Supervillians
The Lego Movie: videogame
Lego Jurassic World
Lego Ninjago movie videogame

Games where it does not show:
Teenage Mutant Ninja Turtles: Shredders Revenge
Planescape Torment: Enhanced Edition
Stardew Valley
Doom 64
CounterStrike 2
Sonic Mania
Shadowrun: Hong Kong
Nier: Automata
Cyberpunk 2077
Ratchet and Clank: Rifts Apart
Batman Arkham Knight
Starbase Startopia
Middleearth shadow of war
Hollow Knight
Mad Max (Proton Experimental)

Misc
Mad Max (Feral Linux native, would not run)

While testing Arkham City, the shader compilation took an unusually long time. Like an hour. I ended up cancelling it to proceed with the game with it being stuck at 99%.

**Comment by kisak-valve** [comment]
Hello @jbwyatt4, this feedback should start with your video driver vendor and go from there. If they find a decent hint for a Proton dev to ponder, add a note and give me a ping and we can ponder this further.

**Comment by jbwyatt4** [comment]
Alright, that would be AMD's Radeon division. Where would you recommend I reach out to them for Linux support?

**Comment by kisak-valve** [comment]
Assuming you're using mesa/RADV, https://docs.mesa3d.org/bugs.html is a good starting point.
