### ISSUE TITLE
The Finals stuck at EAC anti cheat initializing and keep asking for secure boot enabled (2073850)

### ISSUE THREAD

**Issue by Headcrabed** [ValveSoftware/Proton#8033]
# Compatibility Report
- Name of the game with compatibility issues: The Finals
- Steam AppID of the game: 2073850

## System Information
- GPU: AMD Radeon RX 7800 XT
- Video driver version: Mesa 24.1.6
- Kernel version: 6.10.6-200.fc40.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Headcrabed/b0e81a6a01ff7655072d020014e3af37
- Proton version: 9.0-2 (GE-Proton9-11 won't work either)
- OS: Fedora 40
```
headcrab@Headcrab-PC-Lnx:~$ fastfetch
             .',;::::;,'.                 headcrab@Headcrab-PC-Lnx
         .';:cccccccccccc:;,.             ------------------------
      .;cccccccccccccccccccccc;.          OS: Fedora Linux 40 (KDE Plasma) x86_64
    .:cccccccccccccccccccccccccc:.        Kernel: Linux 6.10.6-200.fc40.x86_64
  .;ccccccccccccc;.:dddl:.;ccccccc;.      Uptime: 17 mins
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.     Packages: 2430 (rpm)
.:ccccccccccccc;KMMc;cc;xMMc;ccccccc:.    Shell: bash 5.2.26
,cccccccccccccc;MMM.;cc;;WW:;cccccccc,    Display (LG ULTRAGEAR): 2560x1440 @ 180 Hz in 31″ [External]
:cccccccccccccc;MMM.;cccccccccccccccc:    DE: KDE Plasma 6.1.4
:ccccccc;oxOOOo;MMM000k.;cccccccccccc:    WM: KWin (Wayland)
cccccc;0MMKxdd:;MMMkddc.;cccccccccccc;    WM Theme: Breeze
ccccc;XMO';cccc;MMM.;cccccccccccccccc'    Theme: Breeze (Dark) [Qt], Breeze [GTK3]
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;     Icons: breeze-dark [Qt], breeze-dark [GTK3/4]
ccccc;0MNc.ccc.xMMd;ccccccccccccccc;      Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK3/4]
cccccc;dNMWXXXWM0:;cccccccccccccc:,       Cursor: breeze (24px)
cccccccc;.:odl:.;cccccccccccccc:,.        Terminal: konsole 24.8.0
ccccccccccccccccccccccccccccc:'.          CPU: AMD Ryzen 9 7950X (32) @ 5.88 GHz
:ccccccccccccccccccccccc:;,..             GPU: AMD Radeon RX 7800 XT [Discrete]
 ':cccccccccccccccc::;,.                  Memory: 6.13 GiB / 30.97 GiB (20%)
                                          Swap: 0 B / 8.00 GiB (0%)
                                          Disk (/): 175.83 GiB / 1.86 TiB (9%) - btrfs
                                          Local IP (enp11s0f1np1): 192.168.1.128/24
                                          Locale: zh_CN.UTF-8
```

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When starting game, EAC anti cheat keep asking me to enable Secure Boot, However it is enabled and works with no problem in windows.  And setting ```PROTON_USE_EAC_LINUX=1``` has no effect. BIOS is also upgraded to newest version available.

![屏幕截图_20240829_011440](https://github.com/user-attachments/assets/2194e04f-82bc-477b-a2bb-71a30daf87c8)
```
headcrab@Headcrab-PC-Lnx:~$ mokutil --sb-state
SecureBoot enabled
```
[steam-2073850.log](https://github.com/user-attachments/files/16786930/steam-2073850.log)
[Steam Runtime Diagnostics Output](https://gist.github.com/Headcrabed/df10a66f50e0af10729892bd3c7f9eed)

## Reproduction
Just download and start the game under Fedora 40.

**Comment by kisak-valve** [comment]
Hello @Headcrabed, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7317#issuecomment-2313263649.
