### ISSUE TITLE
B-17 Flying Fortress - The Mighty 8th: Redux (2000800)

### ISSUE THREAD

**Issue by Arcnor** [ValveSoftware/Proton#8034]
# Compatibility Report
- Name of the game with compatibility issues: B-17 Flying Fortress - The Mighty 8th: Redux
- Steam AppID of the game: 2000800

## System Information
- GPU: Steam Deck OLED
- Video driver version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 9.0, Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2000800.log](https://github.com/user-attachments/files/16787110/steam-2000800.log)

## Symptoms 
Game never starts with Proton 8.0, 9.0 or Experimental (as of today), 7.0 works fine. Error on 9.0 and experimental is a bit baffling, complaining about a symbol on one of the game DLLs that's definitely there.

## Reproduction
Just try to run the game. We are also the developer and can modify things as needed, but we don't know how/if we can tackle that missing symbol issue.

**Comment by simifor** [comment]
@Arcnor the game should now work on proton experimental bleeding edge. The reason it couldn't find the symbol is that dxcore is also a system dll and that was being loaded instead of the game's one.

**Comment by Arcnor** [comment]
Thanks @simifor , so I guess that changed with 9.0?

In any case tried again, but Proton experimental doesn't want to update on my Deck, maybe I need to wait for a bit or something? 

Thanks anyway, appreciate the fast response!

**Comment by simifor** [comment]
You need the bleeding edge beta for proton experimental. Find its entry in
your library, go to properties and select bleeding edge in beta

**Comment by Arcnor** [comment]
> You need the bleeding edge beta for proton experimental. Find its entry in your library, go to properties and select bleeding edge in beta

Indeed, that's what I was missing, thanks! Game works great now, thank you :). I've asked support to set our game to use 7.0 in the meantime, although I'm not sure if that's possible, but will move back to the next version after it's published if they actually honor the request.

Thanks again!
