### ISSUE TITLE
ELDEN RING - Profound performance impact when videoes play on secondary monitor

### ISSUE THREAD

**Issue by Gabriel-Gebril** [ValveSoftware/Proton#8036]
# Compatibility Report
- Name of the game with compatibility issues: Elden Ring
- Steam AppID of the game: 1245620

## System Information
- GPU: RTX 2070 super and GTX 1050TI
- Video driver version: 560.35.03 
- Kernel version: 6.10.6-200.fsync.fc40.x86_64 (64-bit) 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Gabriel-Gebril/33064bfee5765b1d7bf1f9a8db9b0ffd
- Proton version: Experimental and 9.0-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
while using a single monitor the game runs perfectly. When video is playing on the second monitor which is connected to the 1050TI game framerate dips by 10-15. Problem doesn't occur in other titles.

## Reproduction
Play video on second screen while playing elden ring. Watch framerate tank.

**Comment by kisak-valve** [comment]
Hello @Gabriel-Gebril, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-2317549414.
