### ISSUE TITLE
Rendering errors in Soulcalibur 6 (Snow-Capped Showdown stage)

### ISSUE THREAD

**Issue by amverweij** [ValveSoftware/Proton#8037]
# Compatibility Report
- Name of the game with compatibility issues: Soulcalibur 6
- Steam AppID of the game: 544750

## System Information
- GPU: AMD Radeon RX 6800
- Video driver version: Mesa 24.1.3
- Kernel version: 5.15.162-gentoo-x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/amverweij/0b6c075e1a7cd8ebd85108e0bac36e97
- Proton version: 9.0-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

The Snow-Capped Showdown stage does not render correctly on my machine:
![20240829193545_1](https://github.com/user-attachments/assets/93e3c073-b80a-4556-aea3-035ce539151f)

It used to render correctly in the past. All other stages render correctly.

## Reproduction

- From the main menu, choose BATTLE->VERSUS->Start VS Battle
- Pick your favorite character and opponent, anyone will do
- Select the Snow-Capped Showdown stage
- Start playing. Rendering errors occur mostly around the center of the stage. It happens each and every time.

[steam-544750.log.zip](https://github.com/user-attachments/files/16803213/steam-544750.log.zip)

**Comment by kisak-valve** [comment]
Hello @amverweij, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1780#issuecomment-2318533087.
