### ISSUE TITLE
Shapez2 crashing since 0.0.8

### ISSUE THREAD

**Issue by feydreva** [ValveSoftware/Proton#8039]
# Compatibility Report
- Name of the game with compatibility issues: Shapez2
- Steam AppID of the game:[2162800](https://steamdb.info/app/2162800/)

## System Information
- GPU: AMD Radeon RX 6600 XT
- Video driver version: 4.6 (Compatibility Profile) Mesa 24.1.6-arch1.1
- Kernel version: 6.10.6-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/feydreva/dfc9e1427b4248c4cf226fc10a348be3
- Proton version: Proton Experimental

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

  No log created :/

## Symptoms 
Game crash after desktop receiving notification from nvchecker-notify

I have nvchecker-notify sending a notification every 5 min.
Each time, it makes the game crash.
This did not happen before 0.0.8. Bug started with 0.0.8

## Reproduction
I have nvchecker-notify running as a service, each 5 min, a pop up would be send to desktop, and crash the game.

**Comment by feydreva** [comment]
hmm sorry, I guess it runs a native build on linux. nothing to do with proton...
not sure where to report the bug. Could somebody point me to the right direction ?

**Comment by kisak-valve** [comment]
Hello @feydreva, you might have some luck reporting the issue on the game's community forums.

Closing as not a Proton issue.
