### ISSUE TITLE
Assassin’s Creed Valhalla (2208920)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#8041]
# Compatibility Report
- Name of the game with compatibility issues: Assassin’s Creed Valhalla
- Steam AppID of the game: 2208920

## System Information
- Device: Steam Deck OLED
- Proton version: Experimental
- Latest Stable Build

## I confirm:
- [☑️] that I haven't found an existing compatibility report for this game.
- [☑️] that I have checked whether there are updates for my system available.

<## Symptoms 
This game has Graphical and Audio Issues on Proton / Steam Deck, these are not present on Windows using the same graphics settings and resolution.

- Graphical Issues include: Flickering Vegetation and Terrain rapidly disappearing and reappearing

- Audio Issues include: Audio randomly cutting off, Such as Music, Sounds and Voices. Sometimes the Audio not playing when its suppose to.

- There is also loading problems: Sometimes the game won’t reach its Splash Screen (this isn’t an issue with the Third Party Launcher it requires), It will get stuck on the Splash Screen, It won’t load into the Main Menu, sometimes it will crash when loading In-Game and Sometimes it will randomly crash during gameplay.

I did Verify the Game Files through Steam and Install it onto the Internal SSD and these still seem to occur

## Reproduction

Using AC Valhalla’s High Settings
Anti Aliasing: Low
Steam Version of AC Valhalla, Steam Deck Stable Build

**Comment by kisak-valve** [comment]
Hello @CreeperofDoom, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6154#issuecomment-2322926298.
