### ISSUE TITLE
Max Payne 3 ERR_D3D_GFX_NOD3DX1_4

### ISSUE THREAD

**Issue by RBFraphael** [ValveSoftware/Proton#805]
When I try to run Max Payne 3, I got an pop-up that says "Unrecoverable error. Please restart the game." and this pop-up's title says "ERR_D3D_GFX_NOD3DX1_4". I've tried to run the game with this command `DRI_PRIME=1 %command% -dx9` to force using my dedicated graphics card (because I'm on a laptop with two gpus - processor's integrated and a dedicated gpu) and DirectX 9 (according to Rockstar's official post [here](https://support.rockstargames.com/hc/pt-br/articles/200152476-Full-list-of-command-line-parameters-for-Max-Payne-3-on-PC). So, how can I run Max Payne 3?

My computer specs:
Intel Core i5 5200U @2.7GHz 2x physical (4x logical) cores
8gb Ram DDR3L 1600MHz
AMD Radeon HD 8500M / Radeon R5 M230
Linux Mint 19 Tara
Kernel 4.15.0-33-generic

System information (from `inxi -Fxr` in Terminal):
**System:**
           Host: Lenovo-G40-80 Kernel: 4.15.0-33-generic x86_64
           bits: 64 gcc: 7.3.0
           Desktop: Cinnamon 3.8.8 (Gtk 3.22.30-1ubuntu1)
           Distro: Linux Mint 19 Tara
**Machine:**
           Device: laptop System: LENOVO product: 80JE v: Lenovo G40-80 serial: N/A
           Mobo: LENOVO model: Lancer 4A1 v: SDK0J40679 WIN serial: N/A
           UEFI: LENOVO v: B0CN99WW date: 08/09/2016
**Battery**
           BAT0: charge: 0.0 Wh 0.0% condition: 23.3/37.5 Wh (62%)
           model: Lenovo IdeaPad status: Charging
**CPU:**
           Dual core Intel Core i5-5200U (-MT-MCP-) 
           arch: Broadwell rev.4 cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 8779
           clock speeds: max: 2700 MHz 1: 2384 MHz 2: 2436 MHz 3: 2451 MHz
           4: 2290 MHz
**Graphics:**
           Card-1: Intel HD Graphics 5500 bus-ID: 00:02.0
           Card-2: Advanced Micro Devices [AMD/ATI] Sun LE [Radeon HD 8550M / R5 M230]
           bus-ID: 04:00.0
           Display Server: x11 (X.Org 1.19.6 )
           drivers: modesetting,ati,amdgpu (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.00hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 5500 (Broadwell GT2)
           version: 4.5 Mesa 18.0.5 Direct Render: Yes
**Audio:**
           Card-1 Intel Broadwell-U Audio Controller
           driver: snd_hda_intel bus-ID: 00:03.0
           Card-2 Intel Wildcat Point-LP High Def. Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture v: k4.15.0-33-generic
**Network:**
           Card-1: Realtek RTL8111/8168/8411 PCIE Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: 4000 bus-ID: 02:00.0
           IF: enp2s0 state: down mac: <filter>
           Card-2: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter
           driver: ath9k bus-ID: 03:00.0
           IF: wlp3s0 state: up mac: <filter>
**Drives:**
           HDD Total Size: 1000.2GB (57.7% used)
           ID-1: /dev/sda model: WDC_WD10JPCX size: 1000.2GB
**Partition:**
           ID-1: / size: 94G used: 41G (47%) fs: ext4 dev: /dev/sda4
           ID-2: /home size: 364G used: 337G (98%) fs: ext4 dev: /dev/sda5
**RAID:**
            No RAID devices: /proc/mdstat, md_mod kernel module present
**Sensors:**
           System Temperatures: cpu: 54.0C mobo: N/A gpu: 49.0
           Fan Speeds (in rpm): cpu: N/A
**Info:**
           Processes: 281 Uptime: 4:05 Memory: 4704.2/7892.1MB
           Init: systemd runlevel: 5 Gcc sys: 7.3.0
           Client: Shell (bash 4.4.191) inxi: 2.3.56

**Comment by kisak-valve** [comment]
Hello @RBFraphael, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/534#issuecomment-416572179.
