### ISSUE TITLE
The Incredibles (disney, 2004)

### ISSUE THREAD

**Issue by minuteworld1** [ValveSoftware/Proton#8060]
# Compatibility Report
- Name of the game with compatibility issues: The Incredibles
- Steam AppID of the game: Non steam game

## System Information
- GPU:  Nvidia RTX 3080
- Video driver version:  Nvidia driver 555 on linux mint
- Kernel version:  6.8.0-41-generic 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 9.2, GE proton 9-12

## I confirm:
- [o] that I haven't found an existing compatibility report for this game.
- [o] that I have checked whether there are updates for my system available.

## Symptoms 
game opens and hangs on black screen and crashes, runs fine on windows 10 VM

## Reproduction
get the game from old games download, apply the crack and add it as a non steam game. made easier on a windows VM

**Comment by kisak-valve** [comment]
Hello @minuteworld1, we can not support pirated copies of games.
