### ISSUE TITLE
Tarzan (disney, 1999)

### ISSUE THREAD

**Issue by minuteworld1** [ValveSoftware/Proton#8061]
# Compatibility Report
- Name of the game with compatibility issues: Disney's action game: Tarzan
- Steam AppID of the game: Non steam game

## System Information
- GPU:  Nvidia RTX 3080
- Video driver version:  nvidia 555 driver on linux mint
- Kernel version:  6.8.0-41-generic 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 9.2, GE-proton 9-11, GE proton 9-12

## I confirm:
- [o] that I haven't found an existing compatibility report for this game.
- [o] that I have checked whether there are updates for my system available.

## Symptoms 
game opens in tiny tiny window on the top left corner of the screen. the LGU repack that makes the game run well on modern systems packed with dgvoodoo2 does not seemingly work.

## Reproduction
get game from myabandonware, run

**Comment by kisak-valve** [comment]
Hello @minuteworld1, we can not support pirated copies of games.
