### ISSUE TITLE
3D Munch Man 2 (1999)

### ISSUE THREAD

**Issue by minuteworld1** [ValveSoftware/Proton#8062]
# Compatibility Report
- Name of the game with compatibility issues: 3D munch man 2
- Steam AppID of the game: non steam game

## System Information
- GPU:  RTX 3080
- Video driver version:  nvidia 555 on linux mint
- Kernel version:  6.8.0-41-generic 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: proton 9-2, GE proton 9-11, GE proton 9-12

## I confirm:
- [o] that I haven't found an existing compatibility report for this game.
- [o] that I have checked whether there are updates for my system available.

## Symptoms 
Game attempts to open up in a small window and then crashes as quickly as you open it.

## Reproduction
get the game on myabandonware, add as non steam game, run it

**Comment by minuteworld1** [comment]
if you use the original exe, it pops up an error saying "sorry, but this program requires directx 5.0 or newer to be installed on a windows 9x system. click ok to exit"

**Comment by kisak-valve** [comment]
Hello @minuteworld1, we can not support pirated copies of games.
