### ISSUE TITLE
Animaniacs: A Gigantic adventure (1999)

### ISSUE THREAD

**Issue by minuteworld1** [ValveSoftware/Proton#8063]
# Compatibility Report
- Name of the game with compatibility issues: Animaniacs: A Gigantic adventure
- Steam AppID of the game: non steam game

## System Information
- GPU:  Nvidia RTX 3080
- Video driver version:  nvidia driver 555 on linux mint
- Kernel version:  6.8.0-41-generic 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: experimental, 9-2, GE proton 9-11, GE proton 9-12

## I confirm:
- [o] that I haven't found an existing compatibility report for this game.
- [o] that I have checked whether there are updates for my system available.

## Symptoms 
once you launch the game, you are greeted to a fatal error: " animaniacs signaled the following error: could not set video mode 640x480x16 with any compatible mode. make sure your mode is supported by your adapter and that drivers for your video board are properly installed. if you have not installed directX, please do so. Please solve this problem and restart animaniacs"

## Reproduction
launch the game as non steam game, available on myabandonware

**Comment by kisak-valve** [comment]
Hello @minuteworld1, we can not support pirated copies of games.
