### ISSUE TITLE
Bugs bunny lost in time (1999)

### ISSUE THREAD

**Issue by minuteworld1** [ValveSoftware/Proton#8064]
# Compatibility Report
- Name of the game with compatibility issues: Bugs bunny lost in time
- Steam AppID of the game: non steam game

## System Information
- GPU:  Nvidia RTX 3080
- Video driver version:  nvidia driver 555
- Kernel version:  6.8.0-41-generic 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: proton experimental and down to 8, GE proton 9-12

## I confirm:
- [o] that I haven't found an existing compatibility report for this game.
- [o] that I have checked whether there are updates for my system available.

## Symptoms 
game just doesn't launch

## Reproduction
get game from myabandonware, run it

**Comment by kisak-valve** [comment]
Hello @minuteworld1, we can not support pirated copies of games.
