### ISSUE TITLE
Bust a move 3 DX (2001)

### ISSUE THREAD

**Issue by minuteworld1** [ValveSoftware/Proton#8065]
# Compatibility Report
- Name of the game with compatibility issues: Bust a move 3 DX
- Steam AppID of the game: non steam

## System Information
- GPU:  Nvidia RTX 3080
- Video driver version:  nvidia driver 555
- Kernel version:  6.8.0-41-generic 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:8, 9, experimental, ge proton 9-11 and 9-12

## I confirm:
- [o] that I haven't found an existing compatibility report for this game.
- [o] that I have checked whether there are updates for my system available.

## Symptoms 
launcher the site provides runs, game does not. got the game from myabandonware

## Reproduction
run game

**Comment by minuteworld1** [comment]
game doesn't run in windows either, the error box is filled with garbled nonsense.

**Comment by kisak-valve** [comment]
Hello @minuteworld1, we can not support pirated copies of games.
