### ISSUE TITLE
the emperors new groove (2000)

### ISSUE THREAD

**Issue by minuteworld1** [ValveSoftware/Proton#8066]
# Compatibility Report
- Name of the game with compatibility issues: the emperors new groove
- Steam AppID of the game: non steam

## System Information
- GPU:  RTX 3080
- Video driver version:  555
- Kernel version:  6.8.0-41-generic 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: the recent versions of valve's and GE proton

## I confirm:
- [o] that I haven't found an existing compatibility report for this game.
- [o] that I have checked whether there are updates for my system available.

## Symptoms 
game runs great and sound is great but it shows a fraction of the screen when ran 

## Reproduction
get it from my abandonware, patch it so it doesn't check for the cd (pcgamingwiki) and play 
![Screenshot from 2024-09-04 08-31-21](https://github.com/user-attachments/assets/d5f87ac6-f116-4fe3-9a80-83342a08cfd8)

**Comment by minuteworld1** [comment]
![Screenshot from 2024-09-04 08-38-12](https://github.com/user-attachments/assets/19afc6b6-2988-4ccb-b765-9d01b2ea9811)
got it to run in an extremely small window buy clicking on the icon on the taskbar and resizing it a few times

**Comment by minuteworld1** [comment]
![Screenshot from 2024-09-04 08-40-36](https://github.com/user-attachments/assets/bc1e9ff5-0e19-4c16-9f76-31849b4e98e4)
after going into the settings, it works fine now except using a dualsense and possibly other controllers through steam input, the joysticks that control the character are the opposite of what they should be. up is sideways and all that

**Comment by minuteworld1** [comment]
movement issue is the same on xbox controllers. once this is fixed, this game is fully playable.

**Comment by kisak-valve** [comment]
Hello @minuteworld1, we can not support pirated copies of games.
