### ISSUE TITLE
Fallout: New Vegas (22380) and Background Downloads

### ISSUE THREAD

**Issue by SteveHeist** [ValveSoftware/Proton#807]
This could potentially be a universal issue for all Proton games (or even all Steam games), but when installing any game in Steam while running Fallout: New Vegas, the game goes haywire momentarily, dropping all frames and audio for about a second.

Gist: https://gist.github.com/SteveHeist/1f51e113d17ac6bb8224c70a926d6508
Log (in a Google Doc because it's massive): https://drive.google.com/open?id=1Hpn8U-KuJjS6yUXJWmcGTDDK_ueFuCY2

Other than this, Fallout: New Vegas could very easily be whitelisted.

**Comment by kisak-valve** [comment]
Transferred to https://github.com/ValveSoftware/Proton/issues/356#issuecomment-416574466. Closing as a duplicate.
