### ISSUE TITLE
Proton 8.0-5 version works, stable 60 fps but there is keyboard input lag constantly.

### ISSUE THREAD

**Issue by MaxConz** [ValveSoftware/Proton#8070]
Proton 8.0-5 version works, stable 60 fps but there is keyboard input lag constantly.

fedora 40
Kernel 6.10.6-200.fc40.x86_64
nvidia 560.35.03
mesa 24.1.6-1

_Originally posted by @MaxConz in https://github.com/ValveSoftware/Proton/issues/2238#issuecomment-2326509355_

**Comment by kisak-valve** [comment]
Hello @MaxConz, we're using one issue report per unofficially supported game title.

Where you added a comment before is the right place to discuss how that game behaves on your system.
