### ISSUE TITLE
GUILTY GEAR Xrd REV 2 (520440)

### ISSUE THREAD

**Issue by robotman40** [ValveSoftware/Proton#8074]
# Compatibility Report
- Name of the game with compatibility issues: GUILTY GEAR Xrd REV 2
- Steam AppID of the game: 520440

## System Information
- GPU: Intel UHD 630
- Video driver version: Mesa 23.1.3
- Kernel version: 5.15
- Link to full system information report as
- Proton version: 9.0-2

## Symptoms 
NOTE: I am filing this report on behalf of someone who is struggling to run this game on their PC

The game will open a window with a black screen then close after a few seconds.
[steam-520440.log](https://github.com/user-attachments/files/16901463/steam-520440.log)

## Reproduction
Just launch the game

**Comment by kisak-valve** [comment]
Hello @robotman40, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/174#issuecomment-2332992538.
