### ISSUE TITLE
No Games work: An error occurred while launching this game: Compatibility tool failed

### ISSUE THREAD

**Issue by SlideShowGames** [ValveSoftware/Proton#8077]
Any game with any proton version.

I don't know where logs are so I can't send them rn.

A lot of my games have been becoming unplayable with proton for weeks and now they are ALL unplayable because of this stupid obscure error. I might switch to Windows because I have no clue what this is or if it can be fixed.

**Comment by SlideShowGames** [comment]
Update: When I uninstall proton it says missing shared content

**Comment by parkerlreed** [comment]
Is your library on NTFS?
