### ISSUE TITLE
PSO2 Classis (Not NGS): Transfer to a PSO2 block from menu or from within game = blackscreen requiring hard reboot (does not solve)

### ISSUE THREAD

**Issue by blb-works** [ValveSoftware/Proton#8078]
Game launched via compatibility tool: Steam Play. Cannot access PSO2 (original game) as intended from PSO2:NGS launcher.

Intended/expected behavior:

1. Select PSO2 from character screen
2. Land in PSO2 (original) gate area.

OR

1. Select Transfer to PSO2 Block from within PSO2:NGS
2. Land in PSO2 (original) gate area.

ACTUAL behavior trying EITHER of the two paths offered:

1. PSO2:NGS closes.
2. Another game window is spawned, remains black, never loads game.
3. Must hard cancel PID, close steam, and reboot system to regain ability to access PSO2:NGS.
4. PSO2 (original) game never loads.

Item of note - It appears that they are not supporting actual connection between these two games as, when you request PSO2 (classic), it shuts down the game, the launcher, and appears to launch both a new anti-cheat as well as a new game window - but the game never loads. 

I feel like there should be a way from the Steam launcher to manage this, as it consistently fails no matter what I'm doing or how I'm trying to manage it. If Steam would allow me to launch the PSO2 classic game, going from Classic to NGS hasn't been an issue, but going to PSO (classic) from NGS always is an issue. 

Some research indicates that there are requirements (i.e., no NGS items can be taken into Classic, only some Classic items can be taken into NGS), but I've been careful to observe these, so can say with confidence this is not contributing to the current issue. 

I have tried ProtonGE, Proton (current-stable), ProtonTricks, PSOTweaker (won't install), and various workarounds but none of them are helping.

Support request at Steam told me to come here and file an issue. Please let me know if I can provide additional information to assist. 

Thank you. Happy to make a short video to demonstrate issue if it would be helpful.

**Comment by kisak-valve** [comment]
Hello @blb-works, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4122#issuecomment-2335578536.
