### ISSUE TITLE
Kisak ppa

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#8079]
Hi, I wanted to ask about the kisak ppa, sorry for sending it here: can it include the libva-intel-driver intel-media-driver driver as well?

I looked in the distro, after including the ppa, to see if it was installed, to install etc., because of the hardware acceleration in Chrome/Chromium, to work well.

In a documentation I read, these drivers were mentioned.

Kubuntu 24.04.1
Intel i3 1115G4
8gb ram (4gb soldered + 4gb soddim)

😄

**Comment by kisak-valve** [comment]
Hello @Leandro599, this is out-of-scope for the Proton issue tracker.

Having written that, no, these VAAPI drivers are not part of mesa and this won't be picked up in the future as feature creep on that PPA. The distro's repositories already provide these packages https://packages.ubuntu.com/noble/i965-va-driver https://packages.ubuntu.com/noble/intel-media-va-driver

Closing as out of scope.

**Comment by ghost** [comment]
Ok, thanks 😄
