### ISSUE TITLE
The Elder Scrolls V: Skyrim Special Edition Screen flickering

### ISSUE THREAD

**Issue by donjuanplatinum** [ValveSoftware/Proton#8082]
# Compatibility Report
The Elder Scrolls V: Skyrim Special Edition
## System Information
GPU: AMD ATI Radeon RX 580 2048SP
CPU: Intel i7-8700K (12) @ 4.700GHz
OS: Gentoo Linux X86_64
Kernel: 6.6.47-gentoo-x86_64
MESA: media-libs/mesa-24.1.6::gentoo
Proton: wine-9.0 (Proton-9.0-1)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

At the beginning of the game, on the carriage
All materials are flashing
![https://s3.leaves.red/c33abb6ba76a441c9f0683b1723b90a7:red/2024/09/08/66dd914283f77.png](https://s3.leaves.red/c33abb6ba76a441c9f0683b1723b90a7:red/2024/09/08/66dd914283f77.png)
![elder4.png](https://s3.leaves.red/c33abb6ba76a441c9f0683b1723b90a7:red/2024/09/08/66dd92806244a.png)

**Comment by kisak-valve** [comment]
Hello @donjuanplatinum, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4#issuecomment-2336677034.
