### ISSUE TITLE
Non Native Games Won't Launch When Using NVIDIA Driver 560.35.58

### ISSUE THREAD

**Issue by BugsyReportsy** [ValveSoftware/Proton#8083]
# Compatibility Report
- Name of the game with compatibility issues: Won't Launch
- Steam AppID of the game: Any Non Native Game

## System Information
- GPU: RTX 3050 4GB (Laptop)
- Video driver version: 560.35.58
- Kernel version: 6.10.2 Generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Any

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Non native games won't launch on my Nvidia laptop when I'm using the latest 560.35.58 driver.

## Reproduction
1. Have the latest Nvidia driver installed on the system (I'm using Mint 22/Ubuntu 24.04).
2. Have an external monitor as the primary monitor if using a laptop.
3. Have "NVIDIA On-Demand" or "NVIDIA Performance Mode" selected on the Prime/Optimus settings if using a laptop.
4. Attempt to launch any non native game via Proton (seemingly any version including GE from my testing).

**Comment by kisak-valve** [comment]
Hello @BugsyReportsy, the NVIDIA 560 series video driver packages provided by https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa are currently incomplete and are missing 32 bit (i386) packages.

This can not be resolved on Proton's side and must be evaluated by the PPA packagers.

Report this issue to the PPA package maintainer(s) if it hasn't been already.
