### ISSUE TITLE
Online mode doesn't work in Elden Ring

### ISSUE THREAD

**Issue by satana-el** [ValveSoftware/Proton#8089]
# Compatibility Report
- Name of the game with compatibility issues: Elden Ring
- Steam AppID of the game: 1245620

## System Information
- GPU: GTX 1650 SUPER
- Video driver version: nvidia 560.35.03
- Kernel version: 6.10.9-arch1-2
- Link to full system information report as [Gist]: https://gist.github.com/satana-el/86615f1f7eaf412fad330e7f0e8636c8 
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1245620.log](https://github.com/user-attachments/files/16975535/steam-1245620.log)

## Symptoms:
When I launch the game it can't connect online. It started after patch 1.14.

## Reproduction
Launch the game in online mode or try logging in. I only own the base game not the DLC btw.

**Comment by kisak-valve** [comment]
Hello @satana-el, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-2346169612.
