### ISSUE TITLE
pc building simulator stopped working

### ISSUE THREAD

**Issue by skippy2blue** [ValveSoftware/Proton#8092]
# Compatibility Report
- Name of the game with compatibility issues: PC building simulator
- Steam AppID of the game: idk

## System Information
- GPU: 
- Video driver version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:expirimental

## I confirm:
- [ no] that I haven't found an existing compatibility report for this game.
- [ yes] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment]
Hello @skippy2blue, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #1919, but you've shared no details to ponder why the game is having a hard time on your system.

Feel free to add a comment with your experience to #1919. Closing in favor of the existing compatibility report.
