### ISSUE TITLE
Games refuse to launch if Proton is installed on another drive

### ISSUE THREAD

**Issue by PossiblyNocturnal** [ValveSoftware/Proton#8095]
#### Your system information
* Steam client version (build number or date): Fri, Sep 13 8:23 AM UTC +03:00
* Distribution (e.g. Ubuntu): EndeavourOS (KDE Plasma 6.1.5 running Wayland)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17006803/steam-logs.tar.gz)
* GPU: Nvidia GTX 980 running proprietary 560.35.03 driver

#### Please describe your issue in as much detail as possible:
Whenever I try to start any game, it simply doesn't open: Steam goes through typical launching steps at first, but games just doesn't start.
I tried to PROTON_LOG it in case it's an issue with Proton, but it seems like the game launch doesn't even reach that stage since no logs were generated that way(tried pointing it to a pre-made directory via PROTON_LOG_DIR to no avail).
I also tried starting Steam via terminal to see if it outputs any errors, but it doesn't seem to output anything special: processes for games are created, then instantly removed.
I thought it was Arch/Endeavour issue at first and tried it on Fedora, but the same thing happened there. Next guess was an issue with a native package from distributions' repos, so I tried Flatpak Steam which seemed to be fine at first, but it still ended up with the same thing in the end. The only distro I tried which seemingly didn't have the issue was Bazzite.
I checked Steam runtime system information right before posting this issue and it seems to have errors regarding LibGL(something to do with /etc/drirc/ and/or /home/$USER/.drirc not existing resulting in being unable to create a dri2 screen) alongside libva returning -1 error, maybe it has something to do with it?(Here's the [gist](https://gist.github.com/PossiblyNocturnal/4d9ddc3977f78732477ea3ab85e506f6)). I double checked if I have my libva/vdpau packages (properly) installed and I'm pretty sure that's the case given a fairly standard and sane output of both vdpauinfo and vainfo, so I'm not really sure what's going on. 
#### Steps for reproducing this issue:

1. Reboot system
2. Open Steam
3.  Try opening any game you have installed
4. Profit..?

(apologies if this is extremely messy, I rarely submit issues and properly wording technical issues isn't exactly my strong suit)

**Comment by kisak-valve** [comment]
Hello @PossiblyNocturnal, we're tracking issues with games run with Proton in the Proton issue tracker. In console_log.txt, it looks like all the games you recently tried are being run with Proton Experimental from a secondary Steam library folder.

No Proton log usually hints that something went awry before Proton had a chance to run. What filesystem are you using with `/mnt/ssd/steamapps/`? Did the way that partition is mounted change when you rebooted in a way that doesn't let execuables run from that Steam library?

`Could not connect to X session manager: Authentication Rejected, reason : MIT-MAGIC-COOKIE-1 authentication rejected` might also be a line of interest from that log.

**Comment by PossiblyNocturnal** [comment]
The ssd mounted only has one big btrfs partition created using kde's partition manager with nofail,relatime and users options. I didn't touch it's mountpoint since setting it up and it's fully owned by user and is writeable. I could try to re-format it as ext4, see if it fixes the issue.

as for X session manager error, I found [this steam discussion](https://steamcommunity.com/app/221410/discussions/0/3192486000819616194/), but the issue in that user's case seems to be an external ssd with a ntfs filesystem, not btrfs.

Edit: forgot to mention Proton version specifics. I tried Proton 9.0-2, 8.0-5 and 7.0-6 with the same results as Experimental.

**Comment by PossiblyNocturnal** [comment]
Okay, upon further throwing stuff at the wall and seeing what sticks I moved all proton versions to my /home and...it seemingly fixed it. Thought it was the problem with runtime and proton versions being installed on separate drives, but nope - if I have proton installation(s) on my 2nd ssd stuff just stops working period.

**Comment by spiffeeroo** [comment]
In your _/etc/fstab_, _users_ implies _noexec_, _nosuid_, and _nodev_. I believe Steam needs some of these mount options enabled (like _exec_ or _suid_) to run any binaries or bubblewrap sandboxes. You can try testing with by adding some of those mount options after _users_.

**Comment by PossiblyNocturnal** [comment]
I completely misread what you wrote at first,  so I'll just edit this. Thanks for the tip, will test either dropping in exec/suid/dev after users or just removing users altogether

**Comment by PossiblyNocturnal** [comment]
Yep, it worked. Thanks a lot for your help!
