### ISSUE TITLE
Apex Legends crashes since latest update (2024-09-12)

### ISSUE THREAD

**Issue by Gothfinger** [ValveSoftware/Proton#8101]
# Compatibility Report
- Name of the game with compatibility issues: Apex Legends (via Steam)
- Steam AppID of the game: 1172470

## System Information
- GPU: NVIDIA GeForce GTX 1060 6GB 
- Video driver version: nvidia-driver-550
- Kernel version: 5.15.0-121-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Gothfinger/a041961c39cb85fb369df734aceb95a7
- Proton version: GE-Proton9-13

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Couldn't add PROTON_LOG since it was 23.5GB

## Symptoms 
The game appears at first to be working, but crashes after ~1h of gameplay. Sometimes a bit earlier sometimes a bit later. Always the same - the game completely freezes up and only way to recover is to force quit the process.

I'm playing on steam flatpak version but apparently it's exactly the same issue on normal steam version as well.

I've tried many different (earlier versions) of Proton as well, same result.

## Reproduction
Install Apex Legends on Steam (either normal or flatpak steam)
Force compatibility of Proton
Start game - (optional skip shader render)
Play for 1-2 matches or ~1h and game freeze and crash.

**Comment by kisak-valve** [comment]
Hello @Gothfinger, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-2353937101.
