### ISSUE TITLE
Grand Theft Auto V (271590)  Looks like the latest update introduced battleye for the online mode

### ISSUE THREAD

**Issue by lzq960605** [ValveSoftware/Proton#8102]
# Compatibility Report
- Name of the game with compatibility issues:Grand Theft Auto V 
- Steam AppID of the game:271590

## System Information
Distribution: Steam Deck Oled  steam os 3.6.13   
CPU: AMD 0932
GPU: AMD 0932

Looks like the latest update introduced battleye for the online mode, seems like they didn't enable Linux support though for it.

**Comment by kisak-valve** [comment]
Hello @lzq960605, we're using one issue report per unofficially supported game title. Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/37#issuecomment-2355484833.
