### ISSUE TITLE
Assassin’s Creed IV Black Flag (242050)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#8104]
# Compatibility Report
- Name of the game with compatibility issues: Assassin’s Creed IV Black Flag
- Steam AppID of the game: 242050

## System Information
- Device: Steam Deck OLED
- Proton version: Experimental
- Stable Build 3.5.19

## I confirm:
- [ ☑️] that I haven't found an existing compatibility report for this game.
- [☑️ ] that I have checked whether there are updates for my system available.

## Symptoms 
This game has issues on Steam Deck, Such as: Graphical Issues and Flickering, Mostly In-Game Objects will Flicker usually in close view and disappear.

It also has alot of crashing problems, Either the game itself crashing, it completely freezing to where the device is inoperable or it will hard reboot the whole device.

## Reproduction
Set all In-Game settings to Very High / High and run it, it keeps having these issues on my end

**Comment by kisak-valve** [comment]
Hello @CreeperofDoom, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1733#issuecomment-2359227134.
