### ISSUE TITLE
Warhammer 40000: Darktide - stuck at "Processing Inquisitorial Clearance"

### ISSUE THREAD

**Issue by gliporace** [ValveSoftware/Proton#8108]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 1361210

## System Information
- GPU: RX 6650 XT
- Video driver version: Mesa 24.0.3 
- Kernel version: 6.5.0
- Link to full system information report: https://gist.github.com/gliporace/59ea6d5400f2aac68b1327d9ff58e0ca
- Steam Runtime Diagnostics: https://gist.github.com/gliporace/d84a24f88254a511b4531c1b8934de71
- Proton version: 9.0-2
- PROTON_LOG file: [steam-1361210.zip](https://github.com/user-attachments/files/17065252/steam-1361210.zip)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game stuck at "Processing Inquisitorial Clearance", with the game logo spinning in the bottom right corner and the music playing in the background.

## Reproduction

Just run the game, play or skip the introductory
 video, press space to continue and get the message Processing Inquisitorial Clearance".

**Comment by kisak-valve** [comment]
Hello @gliporace, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6573#issuecomment-2362005325.
