### ISSUE TITLE
BeamNG.Drive keybinder broken when under Proton

### ISSUE THREAD

**Issue by Buggem** [ValveSoftware/Proton#8113]
# Compatibility Report
- Name of the game with compatibility issues: BeamNG.Drive
- Steam AppID of the game: 284160

## System Information
- GPU: RTX 4070 Ti
- Video driver version: nVidia 555.58.02
- Kernel version: Linux 6.10.9-200.fc40.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Buggem/a9195589c05eada58d23caec2886b0d6
- Proton version: 9.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 Logs are too big (7.3gb)

## Symptoms 

Cannot set custom key bindings, shows up as `?`.

## Reproduction

1. Download BeamNG
2. Get Proton 9.0-3
3. On the main menu click "Options" and then click "Controls".
4. Click on any dropdown catagory
5. Click on any control name
6. Press any key
7. Control shows up as `?` and doesn't work in game

## Workaround

Edit the config JSON files, however this can get VERY annoying as the config resets every time you update the game.

**Comment by kisak-valve** [comment]
Hello @Buggem, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1237#issuecomment-2365174019.
