### ISSUE TITLE
Hellcard (1201540)

### ISSUE THREAD

**Issue by developen-technology** [ValveSoftware/Proton#8114]
# Compatibility Report
- Name of the game with compatibility issues: Hellcard
- Steam AppID of the game: 1201540

## System Information
- GPU: AMD Radeon RX 6700 XT
- Video driver version: Mesa 24.1.6-1
- Kernel version: 6.10.6-10-MANJARO (64 bits)
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/developen-technology/8d07d4c5e38669a5036382c97cb266c3
- Proton version: 9.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Attempting to launch with 9.0-3 it doesn't show anything on the screen.  

## Reproduction

[steam-1201540.log](https://github.com/user-attachments/files/17084485/steam-1201540.log)

**Comment by kisak-valve** [comment]
Hello @developen-technology, your system doesn't have a usable 32 bit Vulkan driver. Add the `lib32-vulkan-radeon` system package and retest.

**Comment by developen-technology** [comment]
thank you @kisak-valve that solved the problem!
