### ISSUE TITLE
[Red Dead Redemption 2] Frame spikes / stutter when using keybord

### ISSUE THREAD

**Issue by geludwig** [ValveSoftware/Proton#8116]
# Compatibility Report
- Name of the game with compatibility issues: Red_Dead_Redemption_2
- Steam AppID of the game: 1174180

## System Information
- GPU: AMD Radeon RX 7900 XTX
- Video driver version: Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
- Kernel version: 6.9.3-76060903-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/geludwig/7bc5e67726a1957ef2a687dd218816d6
- Proton version: Experimental, 9.0-3, 8.0-5

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
Frame spikes / stutter when using Keyboard since around 19/09/2024. No updates to system, only to game and Rockstar launcher (BattleEye update).
No issues when using gamepad.
Capping framerate to 60Hz mitigates this issue to an extend.
Game options: 3440x1440, 144Hz, Borderless Window, Ultra

## Reproduction
Press or hold any key when ingame.

Issue might be connected to:
7510.164:0550:0600:fixme:keyboard:NtUserActivateKeyboardLayout flags 40000000 not supported
7510.164:0550:0600:fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x4090409, 40000000: semi-stub!

[steam-1174180.log](https://github.com/user-attachments/files/17085406/steam-1174180.log)
Gamepad:
![gamepad](https://github.com/user-attachments/assets/15eb3313-af92-42b1-bc31-359662a6b8c7)
Keyboard:
![keyboard](https://github.com/user-attachments/assets/d231314d-d9ca-4655-b352-0d4744949f31)

**Comment by kisak-valve** [comment]
Hello @geludwig, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3291#issuecomment-2365286687.
