### ISSUE TITLE
Sticky Alt Key after Alt+Ctrl+Arrow Keys to Change Workspaces

### ISSUE THREAD

**Issue by delizin** [ValveSoftware/Proton#8120]
I am using Proton Experimental on Linux Mint with Cinnamon.

I have the hotkey, Right Alt + Right Ctrl + Left/Right Arrow, set to cycle left or right between workspaces. 

If I use this in a full screen game to switch to a different workspace and then back into the game, the game behaves as if the Alt key is being held down until I press and release Alt again while the game is in focus. 

This may be related to this old Wine issue with Alt-tabbing that was reported as fixed in Wine version 4.12.1: https://bugs.winehq.org/show_bug.cgi?id=47403

I don't use Wine outside of Proton so I don't know if it is a wider issue that would be better reported to them instead of here.

**Comment by kisak-valve** [comment]
Hello @delizin, you've described a desktop environment issue where it chooses to not send key up events to an application after switching away from the workspace that has the game. This is more likely a DE bug and not application specific. It should be mentioned to the DE dev(s) if it hasn't been already.

**Comment by delizin** [comment]
Thank you. I've opened an issue with Cinnamon, https://github.com/linuxmint/cinnamon/issues/12414, for this issue and I will close this one here.
