### ISSUE TITLE
Is there a localisation support?

### ISSUE THREAD

**Issue by Ricky-Tigg** [ValveSoftware/Proton#8122]
Searching for **locale language files** using relevant keywords in this Git tree does not yield any relevant results.  This would indicate there is no localisation support for this application. But is that so?

**Comment by kisak-valve** [comment]
Hello @Ricky-Tigg, as of this writing, Proton itself doesn't really have any interfaces to localize. Any localization would be part of the individual games.

There's also some inherited tools from wine an that should have localization from upstream (https://gitlab.winehq.org/wine/wine/-/tree/master/po).
