### ISSUE TITLE
GTA5 online broken due to BEAC

### ISSUE THREAD

**Issue by Krulas** [ValveSoftware/Proton#8130]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game: 271590

## System Information
- GPU: RTX 2070
- Video driver version: Nvidia 535 proprietary
- Kernel version: Linux 6.8.0-41 generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Krulas/df340b59388957decbf48cd081c1da62
- Proton version: 8.0-5 (persists regardless of version)

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms
Battle Eye Anti cheat prevents connecting to online sessions on any Linux based build. 

To reproduce this just try to join an online session. It will fail or forcibly remove you within seconds of logging in.  Rockstars FAQ says we need submit a report here: https://support.rockstargames.com/articles/33490543992467/Grand-Theft-Auto-Online-BattlEye-FAQ   I personally feel like the issue is that they have not permitted Battle eye to run in Linux under proton. The solution should be to enable Battle eye under Linux.

**Comment by kisak-valve** [comment]
Hello @Krulas, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-2386078864.
