### ISSUE TITLE
Hard Chip Demo (3033160)

### ISSUE THREAD

**Issue by K1ngfish3r** [ValveSoftware/Proton#8131]
# Compatibility Report
- Name of the game with compatibility issues: Hard Chip (using the demo)

- Steam AppID of the game: 2844290 (Demo uses 3033160)

## System Information
- GPU: r9 fury x
- Video driver version: Mesa 24.3.0-devel
- Kernel version: 6.10.11
- Link to full system information report as [Gist](https://gist.github.com/): [systeminfo.txt](https://gist.github.com/K1ngfish3r/8c6a5ea094dfa43d4bfc77ff1af87d0f)
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-3033160.log](https://github.com/user-attachments/files/17216082/steam-3033160.log)

## Symptoms 
Starts and Stops

## Reproduction
Try to Play the Game

## Fix/Workaround
Wine-master works flawlessly, so to run it in Steam, I obtained a build of Proton which uses it.
For reference, I used Proton-TKG built with wine-master (proton_tkg_9.17.r8.g1baaa8fb)
I'm not sure of the exact commit in wine-master which fixes this.

**Comment by EtienneLorthoy** [comment]
Adding some information that might be useful: the game is built with net8.0-windows and /p:PublishSingleFile=true /p:SelfContained=true. Which seems to be the issue with current proton version used in Steam

**Comment by K1ngfish3r** [comment]
Fixed in a recent Proton Experimental update
