### ISSUE TITLE
Squadgame crash

### ISSUE THREAD

**Issue by fzdas212** [ValveSoftware/Proton#8139]
# Compatibility Report
- Name of the game with compatibility issues:squad
- Steam AppID of the game:393380

## System Information
- GPU: RTX4090
- Video driver version: nvidia 550.120.
- Kernel version: 6.8.0-45-generic
- Link to full system information report as Gist](https://gist.github.com/fzdas212/e854672c36e8f51ae7cbd7881f9c407e)
- Proton version:9.0-3

## I confirm:
- [✔] that I haven't found an existing compatibility report for this game.
- [✔] that I have checked whether there are updates for my system available.

(https://github.com/user-attachments/assets/ee4bfe02-6784-4448-97c8-e88d40446dad)

![截图 2024-10-05 11-01-41](https://github.com/user-attachments/assets/fd352ce5-5bd9-413f-adf9-161562b2cc37)

The game crashes approximately every half hour. 

[steam-393380.zip](https://github.com/user-attachments/files/17264874/steam-393380.zip)

**Comment by fzdas212** [comment]
I still have this issue on my other computer as well.

**Comment by kisak-valve** [comment]
Hello @fzdas212, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/938#issuecomment-2395042108.
