### ISSUE TITLE
Finals in steam always downloads anupdate and even after its installation a similarly sized update will be downloaded next the time steam is opened 

### ISSUE THREAD

**Issue by izerotwo** [ValveSoftware/Proton#8140]
# Compatibility Report
- Name of the game with compatibility issues: The Finals 
- Steam AppID of the game: 2073850

## System Information
- GPU:  RTX 4060 Max Q
- Video driver version:  Nvidia 560.25.03
- Kernel version:  6.11.1-300
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/izerotwo/2e62f2f135813f5466112ec53db11ed0

- Proton version:Proton Experimental 

## I confirm:

- [yes]  that I haven't found an existing compatibility report for this game.

- [yes] that I have checked whether there are updates for my system available.

## Symptoms  
I have noticed whenever steam is turned on a 1.8 - 1.9 GB update comes up for Finals (even after installing the this update the next time i open steam it will still again show me this same update), this issue has persisted on both Steams Flatpak version and Fedora's RPM version of Steam, none of the other games have this issue.
On a further note it appears that if i move my mouse prior to a match loading ingame they kick me out, if there is anything that can be done about it, it would be useful. 

## Reproduction - 
Open Steam 
Check for updates/ Or try opening Finals 
A 1.8-1.9 GB appears if this update is stopped and the game is opened no issues in the game occur. And the game will run as expected

**Comment by kisak-valve** [comment]
Hello @izerotwo, you've described Steam shader pre-cache updates.

This issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/8076. Closing as a duplicate.
