### ISSUE TITLE
The Internet Of Steam Play(Linux) Not Work.So My Game Cannot Connect To Internet.

### ISSUE THREAD

**Issue by ColdWindScholar** [ValveSoftware/Proton#8143]
# Compatibility Report
- Name of the game with compatibility issues:[No More Room in Hell]
- Steam AppID of the game224260

## System Information
- GPU: unknown
- Video driver version: unknown
- Kernel version: 6.1.25
- Link to full system information report as [Gist](https://gist.github.com/):Debian
- Proton version:9.0

## Symptoms 

The Internet Of Steam Play(Linux) Not Work.So My Game Cannot Connect To Internet.

## Reproduction

The Internet Of Steam Play(Linux) Not Work.So My Game Cannot Connect To Internet.

**Comment by kisak-valve** [comment]
Hello @ColdWindScholar, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2520#issuecomment-2395422967.
