### ISSUE TITLE
Middle Earth Shadow of War - Incorrect Resolution

### ISSUE THREAD

**Issue by thebobbyboy420** [ValveSoftware/Proton#8144]
Unable to select the correct resolution in game.
Because of this it tries to enable Dynamic Resolution even when its disabled, and it makes my game downscale the graphics and it looks awful like a ps2 game. My screen is 21:9 3440x1440 and the game tries to tell me its 1290 x 540 (check screenshot)

Software information
Middle Earth Shadow of War 1.2.0 Latest version

System information
GPU: NVIDIA GeForce RTX 4070
Driver: 560.35.03
Wine version: Tried new and old versions, same results
DXVK version: 2.4.1
Even after manually editing the config file located here ~/Games/middle-earth-shadow-of-war/drive_c/users/home/Local Settings/Application Data/WB Games/Shadow of War/render.cfg

"ScreenHeight16by9" "1440.000000"
"ScreenWidth16by9" "3440.000000"

![Screenshot from 2024-10-07 15-28-57](https://github.com/user-attachments/assets/0d82e9be-ba6c-4430-94d6-9510cc594063)

**Comment by kisak-valve** [comment]
Hello @elogicuk, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/135#issuecomment-2395523666.
