### ISSUE TITLE
Game gets power limited to 20-30 watts of GPU power instead its general 90 watt power usage

### ISSUE THREAD

**Issue by izerotwo** [ValveSoftware/Proton#8148]
# Compatibility Report
- Name of the game with compatibility issues:The Finals 
- Steam AppID of the game:2073850

## System Information
- GPU: RTX 4060 Max Q 
- Video driver version: 560.35.03
- Kernel version: 6.11.2-300 
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/izerotwo/be2c7300cb2d8c1f22664f6e5e847093
- Proton version:Proton Experimental 

## I confirm:
- [yes] that I haven't found an existing compatibility report for this game.
- [yes] that I have checked whether there are updates for my system available.

[steam-2073850.zip](https://github.com/user-attachments/files/17306548/steam-2073850.zip)

## Symptoms 
The Finals game sometimes limits its max power consumed to 20 watts and absolutely destroys the games running performance from roughly 110 FPS to 35 ish. 
It should be using close to 80 watts in actuality.
I have not seen a similar issue in other games on steam or on lutris running on Proton GE
The occurrence is random and seems to happen more when the PC has been on for a while and occurs far less frequently 
when steam is opened right after the PC is turned on. 
This issue can be seen in both Steam Flatpak version and the Steam RPM version on Fedora 
Cavitate - Due to Finals Anti cheat when i had enabled Log the game would kick me out of the game but in menu too the affect is noticeable due to the characters being rendered in 3d in the game menu  
## Reproduction
Turn on Steam (the issue is far more common when the pc has been on for a while)
Start the Finals Game
In game it will only use roughly 20 watts 
instead over 80+ whilst providing 100 fps avg instead of 30

**Comment by kisak-valve** [comment]
Hello @izerotwo, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7317#issuecomment-2402227856.
