### ISSUE TITLE
Overwatch 2 - FPS problems and cursor position does not reset

### ISSUE THREAD

**Issue by Ciberbago** [ValveSoftware/Proton#8152]
# Compatibility Report
- Name of the game with compatibility issues: Overwatch 2
- Steam AppID of the game: 2357570

## System Information
- GPU: RX 5700 XT
- Video driver version: 24.2.4-1
- Kernel version: 6.11.2-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/Ciberbago/29a9cf37c1cc56d9bc4a45b404c5fae4):
- Proton version: Proton Experimental

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

[steam-10076119754646487040.zip](https://github.com/user-attachments/files/17334491/steam-10076119754646487040.zip)

## Symptoms 
If using Proton Experimental, it seems like FPS are locked at 60. Even though my screen is set at 144hz, I'm using latest version of Gnome in Arch linux.
Also the cursor position does not reset when using the communication wheel, I cannot remember since which update this started to happen. 

## Reproduction
I have 2 videos here. First one using proton experimental where you can see all my settings are fine and it's still locked at 60. 
[Proton Experimental](https://youtu.be/B9PzbZMfhis)

The second one using Proton-GE 9-15 where everything fps wise is perfect, except the same problem with the cursor not resetting position happens. I cannot report it to them because they say to test first in proton experimental and if it happens there, then report it here.
[Proton GE 9-15](https://youtu.be/dCVGWt6tfeI)

I did not find any issue here with these exact problems on Overwatch 2, that's why I opened a new one. Also, I have to say, I'm using overwatch through battle net right now, but the exact same thing happen when I use the official steam version (i can't post prove right now because I'm banned in game for a few days)

**Comment by kisak-valve** [comment]
Hello @Ciberbago, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7033#issuecomment-2406105198.
