### ISSUE TITLE
DICEOMANCER (2501600)

### ISSUE THREAD

**Issue by ayykamp** [ValveSoftware/Proton#8153]
# Compatibility Report
- Name of the game with compatibility issues: DICEOMANCER
- Steam AppID of the game: 2501600

## System Information
- GPU: Intel Mesa Intel(R) UHD Graphics 620
- Video driver version: 4.6 (Compatibility Profile) Mesa 24.2.3 (git-b235da6781)
- Kernel version: 6.10.10-1.surface.fc40.x86_64
- Link to full system information report as [Gist](https://gist.github.com/ayykamp/d2c91072c21b92b376505f9c24d24381):
- Proton version: Experimental, 9.0-3, GE-Proton9-15 (Flatpak)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Crashes after a few seconds.
Log: [steam-2501600.zip](https://github.com/user-attachments/files/17335029/steam-2501600.zip)

## Reproduction
1. Open the game
2. Observe crash

**Comment by kisak-valve** [comment]
Hello @ayykamp,
```
err:   DxvkMemoryAllocator: Memory allocation failed
err:     Size:      593940
err:     Alignment: 4096
err:     Mem types: 0,1,2
err:   Heap  Size (MiB)  Allocated   Used        Reserved    Budget
err:    0:     3924        3852        3770        3814        3924      
```
followed by `warn:seh:handle_syscall_fault backtrace: --- Exception 0xc0000005 at 0x7f92aca92016: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/vulkan/01/libvulkan_intel.so + 0x92016.` hints that the game ran out of vram, then the Intel Vulkan driver tripped over itself.

Your system has half the RAM requirement listed on the game's store page.
