### ISSUE TITLE
Proton defaults to Windows 7?

### ISSUE THREAD

**Issue by marco-calautti** [ValveSoftware/Proton#8158]
# Feature Request

## I confirm:
- [x ] that I haven't found another request for this feature.
- [ x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

It looks to me that when a non-steam game is added to Steam, and the corresponding proton prefix is created, the default setting is to specify Windows 7 as the Windows version. This breaks many games that check the windows version to verify DirectX 12 is supported. GIven Windows 7 is EOL since 2020, I would bump the default Windows version for new prefixes to Windows 10/11

**Comment by kisak-valve** [comment]
Hello @marco-calautti, Proton has been using a win10 wineprefix when doing a fresh prefix setup since Proton 5.0.
