### ISSUE TITLE
Palworld (1623730)

### ISSUE THREAD

**Issue by Aurontime777** [ValveSoftware/Proton#8159]
# Compatibility Report
- Name of the game with compatibility issues: Palworld
- Steam AppID of the game: 1623730

## System Information
- GPU: NVIDIA GeForce RTX 3070 Laptop GPU
- Video driver version: NVIDIA 560.35.03
- Kernel version: 6.11.3-200.fsync.fc40.x86_64 (64-bit)
- Link to full system information report as [Gist](https://gist.github.com/Aurontime777/4396eb288c88e7d4860e8bf9a1e90711):
- Proton version: Experimental

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. (#7892)
- [*] that I have checked whether there are updates for my system available.

Attached Log: 
- Without environment variables: [steam-1623730.log](https://github.com/user-attachments/files/17350510/steam-1623730.log)
- With environment variables: [steam-1623730.log](https://github.com/user-attachments/files/17350456/steam-1623730.log)

## Symptoms

Launching the game without environment variables opens the game normally but it didn't utilize dGPU at all, resulting in 15-30 fps even on 1280*720 lowest settings. Adding `VK_ICD_FILENAMES`, `DXVK_FILTER_DEVICE_NAME`, `force_vk_vendor` variables (both in tandem and in isolation) results in heavy stuttering at the main menu, before eventually crashes (at least in my case, others' cases seemed to work). According to #7892, it might have something to do with GPU enumeration of DirectX 11/12.

## Reproduction

1. Use laptop with multiple GPUs
2. Add environment variables (if you do, go to 4b.)
3. Launch the game (go to 4a.)
4. Encounter the issue symptoms mentioned above.

**Comment by kisak-valve** [comment]
Hello @Aurontime777, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7448#issuecomment-2408598202.
