### ISSUE TITLE
Satisfactory - mouse over text input box teleports mouse cursor

### ISSUE THREAD

**Issue by Omnifarious** [ValveSoftware/Proton#8165]
# Compatibility Report
- Name of the game with compatibility issues: Satisfactory
- Steam AppID of the game: 526870

## System Information
- GPU: ATI Radeon 7900 XTX
- Video driver version: Mesa 24.2.4
- Kernel version: 6.11.2-300.fc41.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Omnifarious/8ac4447b69bc9c99c1607ab71727a5a4
- Proton version: Experimental (as of Oct 15, 2024)

I will replace the above bit with my system information from the affected system.

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

<!-- Please add `PROTON_LOG=1 %command%` to the game's launch options and
attach the generated $HOME/steam-$APPID.log to this issue report as a file.
I will do this.

## Symptoms
Whenever I mouse over a text input box in the main game, my mouse teleports away from the box.

## Reproduction
Start the game, and then start a new game or load an existing game.
Press 'Q' (the default keybind for the build tool) to bring up a dialogue box of stuff to build.
Go over to the "search for building" box
See your mouse cursor teleport away

Oddly, this works on the system I detail here, which is why I think it's a Proton issue. I suspect this may have something to do with Fedora 41 and the fact it uses Wayland by default. It looks like the game is trying to switch to the system "I-bar" cursor for text entry when moving over a text entry box. And I suspect that mishandling this situation is what's causing the problem.

I should check to see if maybe FSR is causing the problem by getting some part of the system confused about screen space coordinates. Checking that, no effect. And the teleport seems to happen to a fixed location, which wouldn't be the case if it was coordinate confusion.

Link to gist of system that functions correctly: https://gist.github.com/Omnifarious/c521ef6a30543b25eaf20652878a0e1c

**Comment by kisak-valve** [comment]
Hello @Omnifarious, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7580#issuecomment-2414908729.
