### ISSUE TITLE
Iron Harvest

### ISSUE THREAD

**Issue by MichelN86** [ValveSoftware/Proton#8169]
Hi all,

I purchased the game Iron Harvest. I used GE-Proton9-16 (also tried 15 and 14) on this game. The game is stuttering a lot, when i read the protondb website i came across a message from a user who suggested proton 7.0.6, tried that one and the game runs perfectly fine. Proton 9 i also tested from steam is also a stuttering mess.

Please fix this issue, for people who comes from windows this is very frustrating.

**Comment by kisak-valve** [comment]
Hello @MichelN86, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5471#issuecomment-2417206940.
