### ISSUE TITLE
Space Engineers Gamepad issues

### ISSUE THREAD

**Issue by IAmTheShark223** [ValveSoftware/Proton#8176]
[steam-244850.log](https://github.com/user-attachments/files/17441880/steam-244850.log)
# Compatibility Report
- Name of the game with compatibility issues: Space Engineers 
- Steam AppID of the game: 244850

## System Information
Steam Deck OLED 512gb
- Proton version: 9.0.3 

## I confirm:
- [* ] that I haven't found an existing compatibility report for this game.
- [* ] that I have checked whether there are updates for my system available.

## Symptoms 
The game runs perfectly fine. Exept for the gamepad triggers which only function in menus. Character tools and weapons, also ship tools and weapons cannot be used by the triggers  The issue appears to not be present in Proton 6.3-8 however other aspects of the game like music and steam network connectivity are broken in that version

## Reproduction
Play the game on any recent Proton version on steam deck. Open up a creative mode world in the game. Select any character tools and try using it with the gamepad triggers. The bug is present if they do not work but you are able to use the triggers in menus for navigation or block placment

**Comment by kisak-valve** [comment]
Hello @IAmTheShark223. we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1792#issuecomment-2423424524.
