### ISSUE TITLE
Deck Verified and Platinum Rated Games Keep Crashing/Freezing with any Proton Version

### ISSUE THREAD

**Issue by BugsyReportsy** [ValveSoftware/Proton#8180]
# Compatibility Report
- Name of the game with compatibility issues: Ultrakill, Ultimate Admiral: Age of Sail (Presumably all my non native games are unplayable, but I chose these two as examples because of their Deck verification, ProtonDB rating, and by how I know they used to work before.)
- Steam AppID of the game: https://store.steampowered.com/app/1229490/ULTRAKILL/ https://store.steampowered.com/app/1069650/Ultimate_Admiral_Age_of_Sail/

## System Information
- GPU: RTX 3080 Ti Laptop
- Video driver version: nvidia 560.35.03-15
- Kernel version: 6.11.4-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/BugsyReportsy/85ee394d7b5fedde837a50e072ba4399
- Proton version: Experimental, 9, 8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Games running Proton keep crashing or freezing despite either being Deck verified or platinum rated on ProtonDB. The crashes occur regardless of Steam client, Steam overlay being on/off, Steam + games being reinstalled, and even after I fully updated my system including the firmware. I can confirm that these games worked perfectly fine when I was on Linux Mint a month ago, and when I initially installed Steam on EndeavourOS shortly after switching distro. 

I literally can't find these issues nor any working solutions anywhere online, even if I look outside of Arch based distros. Even after trying Lutris with gamemode and lib32-gamemode, deleting compatdata, configuring avm.max_map_count = 2147483642, installing the needed packages according to the Arch wiki, and verifying the integrity of games and Proton versions individually, nothing works.

## Reproduction
Play the aformentioned games (or likely any non native game) with Proton and expect them freeze or crash within an hour.

**Comment by kisak-valve** [comment]
Hello @BugsyReportsy, looking at your extended system diagnostics, you don't have a usable 32 bit Vulkan driver. Add the `lib32-vulkan-intel` and the `lib32-nvidia-utils` system packages and maybe drop the unused `lib32-amdvlk` system package.

**Comment by BugsyReportsy** [comment]
@kisak-valve I installed the drivers and rebooted my system just to be sure, but the games still crashed within an hour of playtime. I'm on the Steam Beta client, have the Steam overlay on to show FPS, Intel Turbo Boost disabled on systemd, and am using the Cinnamon desktop if any of that information is useful.
Update: I launched and tried the games again after posting this comment and turning off Steam overlay, and UA:AoS froze within 10 minutes.

**Comment by BugsyReportsy** [comment]
Update 2: Played UA:AoS after turning the Steam overlay back on and rebooting the system: the game froze after 30 minutes this time.

**Comment by BugsyReportsy** [comment]
@kisak-valve I also should've clarified this has been happening since at least yesterday, since that was the first time in a while I seriously tried playing my non native games again, meaning this could've been a long standing problem I hadn't noticed until now.

**Comment by BugsyReportsy** [comment]
Turns out the problem was that the latest nvidia driver, nvidia 560.35.03-15, is unable to play games via Proton or Wine without freezing/crashing a few minutes after launch. I fixed this by switching over to the nvidia-dkms version of the driver, then downgrading nvidia-dkms, nvidia-utils, lib32-nvidia-utils, and nvidia-settings to 555.58.02-1 via "sudo downgrade".

**Comment by kisak-valve** [comment]
It may be worthwhile to follow up with your video driver vendor.

**Comment by BugsyReportsy** [comment]
> It may be worthwhile to follow up with your video driver vendor.

I got my all my video drivers from the Arch Linux repository.

**Comment by fhteagle** [comment]
> Turns out the problem was that the latest nvidia driver, nvidia 560.35.03-15, is unable to play games via Proton or Wine without freezing/crashing a few minutes after launch. I fixed this by switching over to the nvidia-dkms version of the driver, then downgrading nvidia-dkms, nvidia-utils, lib32-nvidia-utils, and nvidia-settings to 555.58.02-1 via "sudo downgrade".

Tried downgrading to 555.58.02 and up to 565.57.01 . Tried kernel 6.6.58 through 6.11.5. Tried proton Experimental, 9, 8, and 7.  Tried wayland and non-wayland DEs. All attempts give no change in behavior. Everything using Proton compatibility layer is still horribly broken for me. Arch Linux on intel 13th gen x86_64, with and without nvidia eGPU.

**Comment by BugsyReportsy** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8180#issuecomment-2450518791

@fhteagle have you tried deleting Proton compdata, reinstalling all versions of Proton, reinstalling Steam itself (https://steamcommunity.com/sharedfiles/filedetails/?id=2307584451 ; steam.sh takes the place of steam.exe, click the steam desktop/taskbar icon to start reinstalling), reinstalling kernel headers, or using the Zen kernel w/zen headers (has Proton specific optimizations)?
