### ISSUE TITLE
New World: Aeternum (1063730)

### ISSUE THREAD

**Issue by kosimas** [ValveSoftware/Proton#8182]
# Compatibility Report
- Name of the game with compatibility issues: New World: Aeternum
- Steam AppID of the game: 1063730

## System Information
- GPU: AMD Radeon RX 7900 XTX
- Video driver version: Mesa 24.2.4-arch1.1
- Kernel version: 6.11.3-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kosimas/9c615b77c06d28f10e1e1d5c7a95bd01
- Proton version: 9.X, Experimental, GE Proton 9.X
[steam-1063730.log](https://github.com/user-attachments/files/17450753/steam-1063730.log)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Before the game launches I get a Window with the following contents: Unsupported CPU detected: CPU needs to support SSE, SSE2 and SSE3.
When clicking okay in that window the game launches without any problems but only 4 cores of my 32 cores are being used when playing. This results in poor performance.

## Reproduction
To reproduce the problem someone probably needs to own at least a 13th gen Intel CPU.

**Comment by kisak-valve** [comment]
Hello @kosimas, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5772#issuecomment-2425036000.
