### ISSUE TITLE
Horizon Forbidden West Freezes at Compiling Shaders Screen

### ISSUE THREAD

**Issue by joshontech** [ValveSoftware/Proton#8188]
# Compatibility Report
- Name of the game with compatibility issues: Horizon Forbidden West
- Steam AppID of the game: 2420110

## System Information
- GPU: Intel Arc A770 16gb
- Video driver version: 
   `client glx vendor string: Mesa Project and SGI
   Device: Mesa Intel(R) Arc(tm) A770 Graphics (DG2) (0x56a0)
   OpenGL renderer string: Mesa Intel(R) Arc(tm) A770 Graphics (DG2)
   OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.2.5-arch1.1
   OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.2.5-arch1.1
   OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.2.5-arch1.1`
- Kernel version: archlinux 6.11.5-arch1-1
- System Stats: [System-Stats.txt](https://github.com/user-attachments/files/17500650/System-Stats.txt)

- Proton version: Experimental, 9.0-3, I also tried a compiled version from git of proton-ge-custom.
- Proton Log: [steam-2420110.log](https://github.com/user-attachments/files/17500534/steam-2420110.log)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

### This issue does not happen on my Steam Deck or my Gaming Laptop with Nvidia running Arch.

The game starts and launches properly. When you either start a new game or continue a previous game the "compiling shaders" screen will then come up but freeze shortly after. The following lines are some errors I saw in the terminal when running steam from there.

`Fossilize ERROR: Cannot copy unknown pNext sType: 1000283002.`
`Fossilize WARN: Recording graphics pipeline failed, usually caused by unsupported pNext.`

I tracked down the pNext and sType as to something to do with vulkan variables but didn't dig much farther than that.

## Reproduction

I can reproduce this on my PC every time I install this game. It even happens on other distros such as Ubuntu and Fedora. 
1. Install steam
2. Install Horizon Forbidden West
3. Enable Proton Compatibility
4. Run Game and launch it
5. Either start new or continue
6. Wait till the title screen loads a little and then it will freeze.

**Comment by kisak-valve** [comment]
Hello @joshontech, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7590#issuecomment-2435219165.
