### ISSUE TITLE
Puyo Puyo Tetris [546050]

### ISSUE THREAD

**Issue by cyo93** [ValveSoftware/Proton#8194]
# Compatibility Report
- Name of the game with compatibility issues: Puyo Puyo Tetris
- Steam AppID of the game: 546050

## System Information
- GPU: 
- Video driver version: 24.0.5.183659.radeonsi_24.0.3-3
- Kernel version: 6.5.0-valve22-1-neptune-65-g9a338ed8a75e
- Link to full system information report as [Gist](https://gist.github.com/cyo93/486926ded91a23b918350de6c5325491):
- Proton version: 9.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Since the Latest Steam Deck update I have trouble launching the game offline. Before it worked fine offline, but since the latest update, it sometimes doesn't work after a cold boot. 

## Reproduction
Start the game online, then try to run it offline. You should see it work and reach the SEGA screen. Then try to restart or shut down the Steam deck. Try launching the game again offline, and you may see the message in the video that stops you from playing the game offline.

[steam-546050.log](https://github.com/user-attachments/files/17529056/steam-546050.log) Before bug
[steam-546050_after.log](https://github.com/user-attachments/files/17529057/steam-546050_after.log) After bug
[systemreport-20241026042022.txt](https://github.com/user-attachments/files/17529059/systemreport-20241026042022.txt) System Report before bug
[systemreport-20241026042439.txt](https://github.com/user-attachments/files/17529061/systemreport-20241026042439.txt)
System Report after bug

Video: https://drive.google.com/file/d/1e92OvSfXdUs2jBsgMvfvm6oQq7TS65qn/view?usp=drive_link

**Comment by kisak-valve** [comment]
Hello @cyo93, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/359#issuecomment-2439584813.
