### ISSUE TITLE
F.E.A.R. When flashlight is shined certain brushes there will be a black texture

### ISSUE THREAD

**Issue by UtopicTahu** [ValveSoftware/Proton#8196]
# Compatibility Report
- Name of the game with compatibility issues:F.E.A.R.
- Steam AppID of the game: 21090

## System Information
- GPU: Intel HD 620
- Video driver version:  4.6 Mesa 24.1.7
- Kernel version: 6.11.4-201.fc40.x86_64
- Proton version: 6.3-8 and Later and Experimental

When flashlight is shined at between brushes or at certain brushes there will be a black texture on the brush

## I confirm:
![Screenshot_20241027_190949](https://github.com/user-attachments/assets/557c57d6-22d6-4aed-83f6-c6c931316851)
![Screenshot_20241027_190855](https://github.com/user-attachments/assets/c3f0d8d5-e0b6-4651-9f31-33a98e40b801)

## Symptoms 
[enginemsg.txt](https://github.com/user-attachments/files/17535729/enginemsg.txt)

**Comment by kisak-valve** [comment]
Hello @UtopicTahu, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/481#issuecomment-2440232726.

**Comment by UtopicTahu** [comment]
> Hello @UtopicTahu, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#481 (comment)](https://github.com/ValveSoftware/Proton/issues/481#issuecomment-2440232726).

thanks
