### ISSUE TITLE
The finals crash after few minutes

### ISSUE THREAD

**Issue by reynum2** [ValveSoftware/Proton#8203]
# Compatibility Report
- Name of the game with compatibility issues: The Finals
- Steam AppID of the game: 2073850

## System Information
- GPU: AMD Radeon RX 580 Series (radeonsi, polaris10, LLVM 18.1.8, DRM 3.57, 6.10.11-amd64)
- Video driver version: 4.6 (Compatibility Profile) Mesa 24.2.2-1
- Kernel version: 6.10.11-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/reynum2/259128ac590636fe23228bae5565df06
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-2073850.log.gz](https://github.com/user-attachments/files/17574339/steam-2073850.log.gz)

## Symptoms 
After around 10 minutes of game it freezes completely
The only parameter I use is PROTON_USE_EAC_LINUX=1

## Reproduction
Each time I try to play the game on Linux (On windows it works well)

**Comment by kisak-valve** [comment]
Hello @reynum2, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7317#issuecomment-2447397735.

As a side note, `PROTON_USE_EAC_LINUX=1` is a placebo and doesn't do anything.
