### ISSUE TITLE
The Long Dark (305620)

### ISSUE THREAD

**Issue by PavelDobCZ23** [ValveSoftware/Proton#8204]
# Compatibility Report
- Name of the game with compatibility issues: **The Long Dark**
- Steam AppID of the game: **305620**

## System Information
- GPU: NVIDIA GeForce RTX 3060 Laptop GPU
- Video driver version: 4.6.0 NVIDIA 560.35.03
- Kernel version: 6.11.5-300.fc41.x86_64
- Link to full system information report as [Gist](https://gist.github.com/PavelDobCZ23/4f11ab16ba0db2158d2a9d3c1addcdf3)
- Proton version: **9.0-3**

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
After loading the game past all the disclaimers, it begins to periodically **freeze every second**. It is very noticeable and makes the game very uncomfortable to play. There seems to be no configuration, where this can be solved (like changing game's settings or adding a proton environment variable). The issue is present on versions of Proton 8 and above. The oldest version the game can run on is Proton 7, where this issue isn't present. It might be related to an error `Failed to find library for L"Windows.System.DispatcherQueue"`, which can be found in the attached log and seems to be printed out often as well.
It can be demonstrated with this graph generated by [MangoHud](https://github.com/flightlessmango/MangoHud) (NOTE: the problem also occurs when not using it).
![image](https://github.com/user-attachments/assets/42d95e85-d7ea-468b-ac31-28f095d89559)

## Reproduction
1. Go to game's "Properties" >"Compatibility" > "Force use of specific Steam Play compatibility tool" = "Proton 9.0-3"
2. Open the game, wait for it to load, create a new sandbox save file and play.
3. Notice periodic freezes every second affecting the graphical output. (Easy to notice when moving around.)

## Log
[steam-305620.log](https://github.com/user-attachments/files/17586138/steam-305620.log)

**Comment by kisak-valve** [comment]
Hello @PavelDobCZ23, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3892#issuecomment-2449720388.
