### ISSUE TITLE
Certain games treat left bumper as left trigger

### ISSUE THREAD

**Issue by Bestest-Coder** [ValveSoftware/Proton#8216]
#### Your system information

* Steam client version (build number or date): 1730416762 | Thu, Oct 31 6:19 PM UTC -08:00
* Distribution (e.g. Ubuntu): NixOS 24.05
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/user-attachments/files/17613543/steam-logs.tar.gz)

* GPU: AMD

#### Please describe your issue in as much detail as possible:
For several games, most notably Guilty Gear Strive and Street Fighter 6, any controller has their left bumper (L1) and left trigger (L2) both treated as left trigger (L2). This happens across many different controllers, including normal dualshock 4, snackbox micro (in all configurations), and many different kinds of arcade sticks. Notably however, this only affects xbox style controllers in SF6. On a previous computer I had this same issue happen in Hollow Knight as well, but I have not noticed it affecting any other games on my current system. The steam input test display shows correct inputs, as well as using `wine control` with the game's prefix. I have tried deleting the wine prefix to regenerate it, changing the controller settings with `wine control` to enable/disable SDL and hidraw, and enabling/disabling steam input for controllers per game. Please do advise if this is more properly a proton issue, rather than a steam issue, but as I cannot find any problems in the wine layer I assumed it is elsewhere

#### Steps for reproducing this issue:

1. Connect a controller
2. Open GGST/SF6
3. Press left bumper (L1)

**Comment by kisak-valve** [comment]
Hello @Bestest-Coder, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report.

Hollow Knight is likely separate and worked around by https://github.com/ValveSoftware/steam-for-linux/issues/8217#issuecomment-1179724343.

**Comment by Bestest-Coder** [comment]
This issue does not occur in the Guilty Gear Strive Team of 3 Beta, so I'm wondering if it's somehow tied to any kind of per-game controller settings in steam itself, but I don't know if there's any way to check or clear those. I don't use custom bindings in steam input or anything for any games, so I wouldn't mind if everything is reset to default.

**Comment by Bestest-Coder** [comment]
Manged to fix this, it was in the steam per-game controller configurations, which for some reason had left bumper mapped to left trigger. It was obviously one of the first things I checked, but I think the cloud sync kept reverting it when I opened the game, and I couldn't check properly because opening the controller menu in the steam overlay makes the steam overlay instantly close, and unable to be reopened.

**Comment by Vicus92** [comment]
For anyone in the future, same issue, same fix. Unsure why the mapping was changed as I didn't even know that UI existed, so i doubt i accidentally changed it.

Could be something triggering this in certain circumstances. 

For me, it was Final Fantasy 7 remake. Was correct one morning, was missing the mapping ~6 hours later after closing / re-opening it. Possibly something funky triggered by an Alt+F4?
