### ISSUE TITLE
Horizon Zero Dawn Remastered Crashes during Nixxes logo or early in first cutscene

### ISSUE THREAD

**Issue by wcpenney** [ValveSoftware/Proton#8218]
# Compatibility Report
- Name of the game with compatibility issues:Horizon Zero Dawn Remastered
- Steam AppID of the game:2561580

## System Information
- GPU: Nvidia RTX 4060 8Gb
- Video driver version: 535.183.01
- Kernel version: 6.1.0-26-amd64
- [Steam System Report, Information and Diagnostics](https://gist.github.com/wcpenney/20304789d2f500dc5089b455f38ea094)
- Proton version: Experimental-9.0-20241022

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Proton log:
[steam-2561580.log](https://github.com/user-attachments/files/17625559/steam-2561580.log)

## Symptoms:
Horizon Zero Dawn Remastered crashes during developer logos or shortly after during first cutscene with Rost and baby Aloy. Maximum amount of cutscene view was approx. 5 seconds. 

Horizon Zero Dawn Complete Edition, Horizon Forbidden West, and a host of other AAA titles work fine. Fresh install of Debian 12, Steam, and Nvidia drivers today. Previously tried (many times) with Debian Testing (6.11.4.1) and Nvidia 560.35.03 drivers from Nvidia website.

PSN and Steam previously linked via menu on Horizon Forbidden West. Received bonus Nora outfit during one recent attempt to start the game. 

## Reproduction:
Start Horizon Zero Dawn Remastered with -showlinkingqr switch in Steam. I have tried Proton Experimental and Proton 9.0-3.

**Comment by kisak-valve** [comment]
Hello @wcpenney, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/8205#issuecomment-2456061898.
