### ISSUE TITLE
Unable to login to xbox when playing forza horizon

### ISSUE THREAD

**Issue by yuyalun-allen** [ValveSoftware/Proton#8219]
# Compatibility Report
- Name of the game with compatibility issues: Forza Horizon 4
- Steam AppID of the game: 1293830

## System Information
- GPU: AMD Radeon RX 6650 XT
- Video driver version: 4.6 Mesa 24.2.5-arch1.1
- Kernel version: Arch Linux 6.11.5-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/yuyalun-allen/76c9e6c2e1e23bb80fa84800bfec0add
- Proton version: Proton 9.0-3 (and I've tried other versions like hotfix, experimental, 8.0, 7.0 and GE 9-13)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

when I signed in successfully ( I can confirm that sign-in is successful, otherwise it would complain "incorrect password" etc. but that not showed up), but then it immediately popped up "You may not proceed without being signed in to a profile."

![image](https://github.com/user-attachments/assets/ba5bfca3-b8eb-4899-8d01-49f503e36e3e)

## Reproduction

This issue could be reproduced every time when I clean the proton files and tried to login. If proton files not cleaned, only error popup shows up without any login popup.

[steam.log.zip](https://github.com/user-attachments/files/17629978/steam.log.zip)

I post issue here #4667 ,but no one came to help, so I want to provide more information here. I hope these would be helpful.

I really appreciate it if you could come and help!

**Comment by kisak-valve** [comment]
Hello @yuyalun-allen, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4667#issuecomment-2439558587.

**Comment by yuyalun-allen** [comment]
Okay, thanks for your attention!
