### ISSUE TITLE
The Dark Pictures Anthology Man of Medan (939850)

### ISSUE THREAD

**Issue by err0r2k** [ValveSoftware/Proton#8224]
# Compatibility Report
- Name of the game with compatibility issues: The Dark Pictures Anthology Man of Medan Version 1.19
- Steam AppID of the game: 939850

## System Information
- GPU:  RTX 2080 Mobile (discrete-gpu, no optimus)
- Video driver version:  555.58 and 560.35.03
- Kernel version:  6.1.0-22
- Link to full system information report as [Gist](https://gist.github.com/): [My Gist](https://gist.github.com/err0r2k/54f049b91c2850a0eb99d2244d518f5e)
- Proton version: 7.0-6, 8.0-5, 9.0-3 and some Proton-GE versions

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-939850-dx12.log](https://github.com/user-attachments/files/17681891/steam-939850-dx12.log)
[steam-939850-dx11.log](https://github.com/user-attachments/files/17681893/steam-939850-dx11.log)

## Symptoms 
After the first loading screen, the FPS dropping from 60 to 30-40 FPS. And the FPS will not stabilize. Lowering the resolution, quality and borderless-windowed, windowed or fullscreen mode makes no change. Locking the FPS to 30 FPS are also unstable. [Video](https://www.youtube.com/watch?v=r_b1yYE10ig) The mouse cursor look only like this in the recorded video, which I made with the new Steam record mode.
- The GSYNC Monitor refresh rate was lowered to 60 Hz -> same problem.
- Changing the Direct X Version does not help.
- Same problem on Arch with recent Kernel and NVIDIA Drivers.
- Run the game with or without mangohud and game mode -> same problem
- KDE Compositor is disabled
- X11 or Wayland -> same problem
- Works on Windows without problems on the same Hardware.

## Reproduction
Start the game The Dark Pictures Anthology Man of Medan with DirectX 11 or 12.

.

**Comment by kisak-valve** [comment]
Hello @err0r2k, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3024#issuecomment-2465425376.
