### ISSUE TITLE
Regression Cyberpunk 2077 with Proton experimental

### ISSUE THREAD

**Issue by dominikzogg** [ValveSoftware/Proton#8228]
I normaly use Proton Experimental for all my games in Steam. But i had to downgrade to 9.x stable in Cyberpunk 2077, cause with experimental the CPU and GPU use lowered and the 1% lows where very bad.

CPU: Intel i9 13900K (without any stability issues)
RAM 64GB - 3600Mhz
GPU: AMD 7900XTX

**Comment by kisak-valve** [comment]
Hello @dominikzogg, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-2466502475.
