### ISSUE TITLE
GTA Liberty City Stories is not opening in Proton or GE-Proton. Please fix this issue.

### ISSUE THREAD

**Issue by RaulKong898** [ValveSoftware/Proton#8230]
I want you to do something so that it can be opened through Bottles the port of GTA Liberty City Stories which is ported with PPSSPP and it's like it's for PC 

https://www.moddb.com/mods/gta-re-liberty-city-stories-pc/downloads/gta-liberty-city-stories-pc-full-edition-50 and I want it to be able to be opened through Proton and  GE Proton

**Comment by kisak-valve** [comment]
Hello @RaulKong898, in general, integrating console emulation software into Proton is out of scope for the project. That would need to be a completely independent compatibility tool. This request is a non-starter.

**Comment by RaulKong898** [comment]
> Hello @RaulKong898, in general, integrating console emulation software into Proton is out of scope for the project. That would need to be a completely independent compatibility tool. This request is a non-starter.

The game has been transplanted to PC and uses the PPSSPP engine, however it is actually GTA Liberty City Stories on PC, as you even say, it’s a PC game, not emulated or anything. The game shows the PC settings instead of PSP ones (these are for PPSSPP), and I am able to change the control pattern of it, especially during missions or other parts in which it breaks into new controls for you (those times where there is an indicator display the PC keyboard controls).So please, I humbly ask you to arrange it so that it works on Proton plus GE-Proton.
