### ISSUE TITLE
Game freezing issue during loading screen or while a new match starts

### ISSUE THREAD

**Issue by Miyutsukka** [ValveSoftware/Proton#8231]
# Compatibility Report
- Name of the game with compatibility issues: Dead by Daylight
- Steam AppID of the game: 381210

## System Information
- GPU:  Mesa Intel® UHD Graphics 770
- Video driver version:   xserver-xorg-video-intel 2:2.99.917, mesa-va-drivers 24.2.3-0
- Kernel version:  6.11.0-103009-tuxedo (64-bit)
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/Miyutsukka/3a013a9bade2c48d9308043fe385265c
- Proton version: 9.0-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

 
[steam-381210.log](https://github.com/user-attachments/files/17691572/steam-381210.log)

## Symptoms 
The game freezes while it loads into a new match or while the new match starts. 

## Reproduction
1. Open game
2. Start a match (both custom and online have the same issue)
3. Load into match and wait until it either freezes or starts as intended

**Comment by kisak-valve** [comment]
Hello @Miyutsukka, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/519#issuecomment-2466748749.
