### ISSUE TITLE
Huge performance drop (unplayable) after 40-50min when the cursor or camera is moving

### ISSUE THREAD

**Issue by Smyl3** [ValveSoftware/Proton#8232]
Affected game title:  Planetside 2

- Steam AppID of the game: 218230

## System Information
- GPU:  GTX 960
- Video driver version: nvidia 550.127.05
- Kernel version: 6.11.5-1-default
- Proton version: Experimental / GE-Proton9-19
[Steam system information](https://gist.github.com/Smyl3/b08c28cb9c70191e876b6b3fd42e9747)
[Steam Runtime Diagnostics](https://gist.github.com/Smyl3/f26afdd3eda4ff59a88ea28caded449d)
Steam Beta Branch:  Stable Client
Steam Version:  1730853027
Steam Client Build Date:  Tue, Nov 5 22:33 UTC -08:00
Steam Web Build Date:  Wed, Nov 6 01:21 UTC -08:00
Steam API Version:  SteamClient021

[steam_log.zip](https://github.com/user-attachments/files/17698257/steam_log.zip)

## Symptoms
After like 40-50 minutes of playing when cursor or camera is moving by keyboard or mouse, results huge performance loss and the game become unplayable after that time. Without moving, the fps is smooth.

## Workaround
add 

> LD_PRELOAD=

 to launch options of the game

**Comment by kisak-valve** [comment]
Hello @Smyl3, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/11446. Closing as a duplicate.
