### ISSUE TITLE
Random crashes with A Plague Tale: Requiem (1182900)

### ISSUE THREAD

**Issue by jeancf** [ValveSoftware/Proton#8237]
# Compatibility Report
- Name of the game with compatibility issues: A Plague Tale: Requiem
- Steam AppID of the game: 1192900

## System Information
- GPU: Advanced Micro Devices [AMD/ATI] Navi 21 [Radeon RX 6800 XT]
- Video driver version: Mesa 24.2.6 / xf86-video-amdgpu 23.0.0
- Kernel version: 6.11.6-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/jeancf/5c768b7ee23015bd09c41d63062f083a)
- Proton version: tested with experimental / 9.0-3 / 8.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1182900.log](https://github.com/user-attachments/files/17719260/steam-1182900.log)

## Symptoms 
Game crashes randomly and returns to desktop. Sometimes after a few seconds, sometimes after 30-60 minutes. No error message is displayed.

## Reproduction
Every time I run the game and play long enough.

**Comment by kisak-valve** [comment]
Hello @jeancf, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6241#issuecomment-2470968942.
