### ISSUE TITLE
Tomb Raider 203160

### ISSUE THREAD

**Issue by Chevek** [ValveSoftware/Proton#8239]
# Compatibility Report
- Name of the game with compatibility issues: Tomb Raider
- Steam AppID of the game: 203160

## System Information
- GPU: TX 7900 XTX
- Video driver version: 24.2.6
- Kernel version: 6.11.7-300.fc41.x86_64
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Linux nativ

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
The game wont launch if using nativ (works with proton). Once fixed with linux nativ, performance are better.

Error :
/home/steam/jeux/SteamLibrary/steamapps/common/Tomb Raider/bin/TombRaider: error while loading shared libraries: libicui18n.so.51: cannot open shared object file: No such file or directory

But this librairy is provided by the game:
$ pwd
/home/steam/jeux/SteamLibrary/steamapps/common/Tomb Raider/lib/i686
$ ls
libcef.so                 libcrypto.so.1.0.0  libfmodex.so      libicui18n.so.51  libpdf.so        libsteam_api.so
libCoreFoundation.so.476  libcurl.so.4        libicudata.so.51  libicuuc.so.51    libssl.so.1.0.0  libtcmalloc_minimal.so
## Reproduction
Always

How to fix it:
Found this tip here: https://steamcommunity.com/app/203160/discussions/0/4356746952212516512/#c4763207599014167023

First edit TombRaider.sh in the game folder and add right above LD_PRELOAD_ADDITIONS=

`export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:../lib/i686/"`

Then right below LD_PRELOAD_ADDITIONS=

`LD_PRELOAD_ADDITIONS="../lib/i686/libcurl.so.4:${LD_PRELOAD_ADDITIONS}"`

**Comment by kisak-valve** [comment]
Hello @Chevek, if you're using the Linux native variant of the game, then Proton isn't involved with this issue. Report this issue to the game's dev(s).
