### ISSUE TITLE
Mouse Button Mapping

### ISSUE THREAD

**Issue by dajusc** [ValveSoftware/Proton#824]
On Windows I use customized key-bindings for my mouse buttons, e.g. I assign ESC to the mouses thumb-button to quickly exit in-game menus. I use "Logitech Gaming Software" for this, which is unfortunately not available for Linux.

I tried to achieve the same customization in Linux via _xbindkeys_ and _xautomation_, which works fine as long as I am in the desktop (Linux Mint Cinnamon). Unfortunately it is apparently not working within games launched via Proton.

Question: Is there already a way to achieve customized key-bindings as described above?
If not: That would be an awesome feature! :)

**Comment by FlipB** [comment]
I haven't tried but there's https://github.com/libratbag/piper

**Comment by dajusc** [comment]
@FlipB thanks for the tip. :)

At the moment I'm struggling with building it, but I will report back as soon as I got it running.

**Comment by dajusc** [comment]
Still didn't get key-assignment with piper to work.
Meanwhile I tested **xbindkeys** and **imwheelrc** which work fine on my desktop, but immediately stop working within proton/wine.

**Comment by dajusc** [comment]
After I couldn't find any solution that works as expected, I implemented something myself:
https://github.com/dajusc/Linux-Mouse-Keybinds

**Comment by dajusc** [comment]
Nothing new within a year. As I have a working solution and no one else seems to have a problem with it I will close this issue.
