### ISSUE TITLE
Old School RuneScape - Audio issues

### ISSUE THREAD

**Issue by Operativ** [ValveSoftware/Proton#8240]
# Compatibility Report
- Name of the game with compatibility issues: Old School RuneScape
- Steam AppID of the game: 1343370

## System Information
- GPU: RTX 4070
- Video driver version: NVIDIA 560
- Kernel version: 6.11.7
- Proton version: 9.0.3

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

## Symptoms

Audio is distorted, sometimes pops with a crackling sound when music/OST is playing. The biggest issue is when standing near the Town Crier NPC (eg. near Varrock East Bank, or Hosidius bank). When this NPC plays the "bell" animation, instead of the usual ringing, you can hear a variety of sounds, from growling, to flashy explosions, sometimes put on a permanent loop until app is closed. These persist even after log-out, until app is fully closed.

## Reproduction

1. Log-in,
2. Visit Varrock east bank,
3. Wait until the nearby Town Crier rings his bell a few times. Check the audio you hear.

**Comment by kisak-valve** [comment]
Hello @Operativ, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4652#issuecomment-2473741757.
