### ISSUE TITLE
Portal with RTX works stable with DLSS Frame Generation

### ISSUE THREAD

**Issue by mineLdiver** [ValveSoftware/Proton#8241]
OS: Arch Linux
GPU: RTX 4060
Nvidia drivers: 565.57.01-3 (proprietary due to presence of a second, older GPU)
Proton version: 9.0 experimental

Description: Portal with RTX has hardware-accelerated GPU scheduling disabled by default, however, enabling it back and running with DLSS FG hasn't given me any issues throughout the main game levels yet substantially increased the FPS. It might be worth removing it from the blacklist.

**Comment by kisak-valve** [comment]
Hello @mineLdiver, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6367#issuecomment-2476395227.

**Comment by philipl** [comment]
@mineLdiver How did you enable HAGS?

Sorry, had to ask here as you can't @ arbitrary people on other issues.

**Comment by mineLdiver** [comment]
@philipl I used `WINE_DISABLE_HARDWARE_SCHEDULING=0` in the environment variables, but for some reason it stopped working at one point. Not sure if it does now.

**Comment by philipl** [comment]
Huh. When I set that, the game becomes incredible unstable with NvRemixBridge freezing or crashing when I get to the main menu, or even earlier sometimes.
