### ISSUE TITLE
Mikrofonlar çalışmıyor.

### ISSUE THREAD

**Issue by 10927438** [ValveSoftware/Proton#8242]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Video driver version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Reproduction

Steam Linux  Runtime 3.0 (sniper) sadece bunda maç bulabiliyorum diğer sürümlerde dosyalarda eksik olabilir hatası veriyor ve  sadece bu sürümde (Steam Linux  Runtime 3.0 (sniper))  mikrofon aygıtımı değiştirebileceğim bir ayar bulunmuyor ve mikrofonumu kullanamıyorum.

**Comment by kisak-valve** [comment]
Hello @10927438, sorry, but this isn't coherent. The Steam Linux Runtime is a container environment, has no audio selection interface of its own and doesn't interact with microphones directly.

**Comment by 10927438** [comment]
@kisak-valve  ama diğer sürümlerde de maça girmiyor. Dosya doğrulaması istiyor ve yapıyorum ve başarıyla tamamlanıyor ona rağmen Valve Antı Hıle uyarısı verıyor.
