### ISSUE TITLE
Valve Anti Cheat Warning

### ISSUE THREAD

**Issue by 10927438** [ValveSoftware/Proton#8243]
# Compatibility Report
- Name of the game with compatibility issues: CS2
- Steam AppID of the game:

## System Information
- GPU: Gıgabyte Eagle OC RTX 4070
- Video driver version: 550.120
- Kernel version: 6.8.0-48-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 9.0-3

## I confirm:
- [ T] that I haven't found an existing compatibility report for this game.
- [ T] that I have checked whether there are updates for my system available.

## Reproduction

When I enter CS2 with Proton 9.0-3 version and press find a match, I get a Valve Anti-Cheat warning. It asks me to verify the files, I verify them and there is no problem, but it gives the warning again. How can I solve this?

**Comment by kisak-valve** [comment]
Hello again @10927438, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2704#issuecomment-2476678276.
