### ISSUE TITLE
Warframe (230410) - Unstable frame rates after 40 minutes

### ISSUE THREAD

**Issue by NoviceOtter** [ValveSoftware/Proton#8245]
# Compatibility Report
- Name of the game with compatibility issues: Warframe
- Steam AppID of the game: 230410

## System Information
- GPU: NVIDIA Corporation GA104 [GeForce RTX 3070] 
- Video driver version: nvidia 560.35.03
- Kernel version: 6.9.3-76060903-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/NoviceOtter/e714f144fd9e186c10162182eaf8c33e
- Proton version: Experimental and 9.0-3 both affected

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game. 
- [ X ] that I have checked whether there are updates for my system available.

[steam-230410.zip](https://github.com/user-attachments/files/17769618/steam-230410.zip)

## Symptoms 

At the patch where the Warframe 1999 demo released I started experiencing frame rate issues in Warframe but only after about 30-40 minutes of playing. Up to then I get solid 60 frames per second then suddenly it becomes a laggy mess. I have checked for back ground processes starting or something similar but a simple quit and restart of Warframe resolves the issue. All game modes affect solo or online. I have tried Proton Experimental and 9.0-3. Changing graphics settings to minimum does not resolve the issue either. Verified PC is not overheating, max core temp was 55 so well below anything I would worry about, immediate restart also gives another 30-40 minutes of play before issues start again so 99% sure its not heat related. Uninstalled and reinstalled Warframe completely. Let shaders precompile in steam, skip shaders, disable shaders, all the same result. DX11 and DX12 same result. 

Issues are not present when running the game in windows.

## Reproduction

Start game, begin playing after about 30-40 minutes begin experiencing major frame rate instability resulting in very poor game play

**Comment by kisak-valve** [comment]
Hello @NoviceOtter, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/167#issuecomment-2478774434.
