### ISSUE TITLE
The Binding of Isaac: Repentance MALLOC crash

### ISSUE THREAD

**Issue by LyCH-OS** [ValveSoftware/Proton#8246]
Tested with the following Proton types:
- Experimental
- 5.0-10
- 5.13-6
- 6.3-8
- 7.0-6
- 8.0-5
- 9.0-3

OS: Manjaro Linux x86_64 
Kernel: 6.11.2-zen3-xanmod1-1 
Resolution: 1920x1080, 1920x1080 
DE: Plasma 6.1.5 
WM: KWin 
CPU: AMD Ryzen 7 5800X (16) @ 4.851GHz 
GPU: AMD ATI Radeon RX 6900 XT Merc 319
Memory: 64214MiB
Mesa: 24.3.0_devel.196104.b339c525f44.d41d8cd-1

Crash Description:
After playing for an indeterminate and random time (i.e. very first room, last room of the game, entering a secret room, bombing a rock, killing an enemy, etc), the game will crash with the following terminal output,

```
Adding process 3165165 for gameID 250900
Adding process 3165166 for gameID 250900
Adding process 3165167 for gameID 250900
Adding process 3165276 for gameID 250900
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Adding process 3165277 for gameID 250900
Adding process 3165278 for gameID 250900
Adding process 3165279 for gameID 250900
Adding process 3165282 for gameID 250900
Adding process 3165284 for gameID 250900
Adding process 3165287 for gameID 250900
Adding process 3165295 for gameID 250900
Adding process 3165301 for gameID 250900
Adding process 3165316 for gameID 250900
Adding process 3165321 for gameID 250900
Adding process 3165330 for gameID 250900
Setting breakpad minidump AppID = 250900
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197998992394 [API loaded no]
Adding process 3165344 for gameID 250900
11/15 00:11:35 minidumps folder is set to /tmp/dumps
11/15 00:11:35 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(20241112170934)/tid(3165371)
11/15 00:11:35 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(3165371)
malloc(): corrupted top size
```

**Comment by kisak-valve** [comment]
Hello @LyCH-OS, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4868#issuecomment-2478808896.
