### ISSUE TITLE
EA-Launcher stopped working with Proton 7 & FIFA 22

### ISSUE THREAD

**Issue by puxplaying** [ValveSoftware/Proton#8249]
# Compatibility Report
- Name of the game with compatibility issues: FIFA 22
- Steam AppID of the game: 1506830

## System Information
- GPU:  RX 6750 XT
- Video driver version:  Mesa 24.2.7-arch1.1
- Kernel version:  6.11.8-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/puxplaying/d0fa4a0f6a7f767a3d7a2624d50316a5
- Proton version: 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The EA launcher does not start anymore with Proton 7 - and hence the game FIFA 22 can not be launched.
- The reason to use Proton 7 is, it is the only version which is able to run this game at 60 FPS on AMD GPU's in cut-scenes, pro-cam and the menu. Any other (newer) Proton version is capped at 30 FPS in DX11 and DX12 mode.

## Reproduction
Run FIFA 22 via Proton 7

[PROTON_LOG](https://gist.github.com/puxplaying/9e05b69a27e31a039c83ddd6e429ba40)
[Steam Runtime Diagnostics](https://gist.github.com/puxplaying/a96f05df446f9059160643bc9dca458f)

**Comment by kisak-valve** [comment]
Hello @puxplaying, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5673#issuecomment-2480558725.

**Comment by puxplaying** [comment]
Hello @kisak-valve, thanks for moving the issue to the right place! I was not sure if it should be posted [there](https://github.com/ValveSoftware/Proton/issues/5673) as it is different from the OP, so I decided to open a new issue. :smiley:
