### ISSUE TITLE
Grand Theft Auto V on Gentoo Linux 

### ISSUE THREAD

**Issue by Kreyren** [ValveSoftware/Proton#826]
**DISCLAIMER**
I coudn't find any other thread on ValveSoftware/Proton that reports this issue with Grand Theft Auto V

**ISSUE**
Grand Theft Auto is able to run, but mouse movement is restricted on +- 280° it seems that mouse cursor is restricted by sides of accesable DE. It seems that mouse cursor is moving in background and is stopped by left and right side of a monitor.
Game also freeze every few seconds-minutes on load while driving a car or moving to a location where character wasn't before. freezes on few seconds.
Also Game was able to crash Xorg once i hit a bridge in full sped in Veiron.

**INFO**
`emerge --info` - https://paste.pound-python.org/show/1jergtB0ZSBI88eH1PGI/
`vulkaninfo` - https://paste.pound-python.org/show/DvgUS21HaW0894bFtRnx/
Gentoo Linux  kernel 4.17.14 with `vulkan` USE flag emerged.
Proton - 3.7-4 Beta
`system info` - https://pastebin.com/jF0WcUuM
_let me know what else i can provide not familiar with Proton diagnostics._

**STEPS TO REPRODUCE**
1) Install (emerge) steam
2) log-in
3) install Grand Theft Auto V.
4) Run the game
5) game starts
6) wait for load. 
7) move to a location where you wasn't before -> should result in freeze on few seconds.
8) Try to turn around with mouse -> should be restricted on +- 280°
Suspect same issue on other distros.

Let me know if i can help :+1: 
- DK

**Comment by kisak-valve** [comment]
Hello @KostWarCZE, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-416605926.
