### ISSUE TITLE
Path of Exile starts stuttering after 30 minutes

### ISSUE THREAD

**Issue by TrueNeutralDesu** [ValveSoftware/Proton#8266]
# Compatibility Report
- Name of the game with compatibility issues: Path of Exile
- Steam AppID of the game: 238960

## System Information
- GPU: AMD Radeon RX 6800 XT
- Video driver version: Mesa 24.2.7-arch1.1
- Kernel version: 6.12.1-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/TrueNeutralDesu/c4be8dd4ead4985ed2fb3e60e16081ff
- Proton version: Proton Experimental (9.0-3 ?not sure)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-238960.tar.gz](https://github.com/user-attachments/files/17907918/steam-238960.tar.gz)

## Symptoms 
After about 30 minutes of playing Path of Exile game starts stuttering. Ingame graph shows CPU related lag going from about 5ms to about 55ms. This doesn't happen when playing on standalone client, however if you add standalone client as non-Steam game and launch it from Steam then stuttering also occurs after half an hour of playtime. Changing any options in game as well as Proton versions does nothing to help the issue. Only way to get rid of it is to restart a game.
I added logfile (compressed since it was 60Mb) but the relevant lines seems to be:

> ...
16563.907:0124:0128:err:font:alloc_font_handle out of realized font handles
16563.907:0124:0128:err:font:alloc_font_handle out of realized font handles
16563.907:0124:0128:err:font:alloc_font_handle out of realized font handles
16563.907:0124:0128:err:font:alloc_font_handle out of realized font handles
16563.907:0124:0128:err:font:alloc_font_handle out of realized font handles
16563.907:0124:0128:err:font:alloc_font_handle out of realized font handles
16563.907:0124:0128:err:font:alloc_font_handle out of realized font handles
16563.907:0124:0128:err:font:alloc_font_handle out of realized font handles
16566.510:0124:0188:err:font:alloc_font_handle out of realized font handles
16566.510:0124:0188:fixme:font:get_nearest_charset TCI failing on 20000000
16566.510:0124:0188:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 20000000 file = (null)
16566.510:0124:0188:err:font:alloc_font_handle out of realized font handles
16566.510:0124:0188:err:font:alloc_font_handle out of realized font handles
16566.510:0124:0188:err:font:alloc_font_handle out of realized font handles
16566.511:0124:0188:err:font:alloc_font_handle out of realized font handles
16566.511:0124:0188:err:font:alloc_font_handle out of realized font handles
16566.511:0124:0188:err:font:alloc_font_handle out of realized font handles
16566.511:0124:0188:err:font:alloc_font_handle out of realized font handles
...

Haven't found anything related directly to this issue online. Problem is present for a few days now.

## Reproduction
Any time game is played for more then 30 minutes.

**Comment by Saancreed** [comment]
Are you sure this isn't just https://github.com/ValveSoftware/steam-for-linux/issues/11446?

**Comment by TrueNeutralDesu** [comment]
Yeah, looks very similar. I'll have to try the `LD_PRELOAD=""` workaround.

**Comment by kisak-valve** [comment]
Hello @TrueNeutralDesu, as @Saancreed noted, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/11446. If that workaround doesn't affect how the game behaves, then please add a note to the older compatibility report for the game at #58 and we can continue to ponder it over there.

Closing as a duplicate.
