### ISSUE TITLE
MS Flightsimulator 2024 video playback issue - only color bars (codec issue?)

### ISSUE THREAD

**Issue by TechGameGeek** [ValveSoftware/Proton#8267]
# Compatibility Report
- Microsoft Flight Simulator 2024
- Steam AppID of the game:  2537590

## System Information
- GPU: Radeon RX 7900 XT
- Video driver version: amdgpu 23.0.0-1 (xserver-xorg-video-amdgpu)
- Kernel version: 6.10.11+bpo-amd64
- Link to full system information report as [Gist] https://gist.github.com/TechGameGeek/1f356ebcf0ea259eb9ca8bea1bfb4c6a
- Proton version: Proton Experimental (bleeding edge - Beta)

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

## Symptoms 

Videoplayback seems to have a codec issue, cause videos just show a placeholder (color bars)
Video plays with latest Proton-GE (9.20) but with Proton-GE 9.20 the game is not working.

Found this in the logs:
 WINE wg_source.c:423:check_decoding_support: pad <avdec_h264-0:sink>
Cannot decode caps video/x-h264, stream-format=(string)avc, alignment=(string)au, level=(string)5.2, profile=(string)main, codec_data=(buffer)014d4034ffe10018674d4034965280780087d35010101400000fa4000753021001000568e9093520, width=(int)3840, height=(int)2160, framerate=(fraction)60000/1001, pixel-aspect-ratio=(fraction)1/1
0:00:00.195620598 38222 0x7fcb2404fd30 ERROR                   WINE wg_source.c:423:check_decoding_support: pad <avdec_h264-1:sink>
0:00:00.195651988 38222 0x7fcb2404fd30 ERROR                   WINE wg_source.c:449:sink_event_caps: Cannot decode caps video/x-h264, stream-format=(string)avc, alignment=(string)au, level=(string)5.2, profile=(string)main, codec_data=(buffer)014d4034ffe10018674d4034965280780087d35010101400000fa4000753021001000568e9093520, width=(int)3840, height=(int)2160, framerate=(fraction)60000/1001, pixel-aspect-ratio=(fraction)1/1

## Reproduction
Install MS FS 2024 -- choose Proton Experimental Beta (bleeding edge)
Start MS FS 2024 with Proton Experimental  Beta (bleeding edge)

[steamlog.tar.gz](https://github.com/user-attachments/files/17909135/steamlog.tar.gz)

**Comment by kisak-valve** [comment]
Hello @TechGameGeek, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/8255#issuecomment-2499091455.
