### ISSUE TITLE
Marvel's Spider-Man: Miles Morales (1817190)

### ISSUE THREAD

**Issue by niltonperimneto** [ValveSoftware/Proton#8272]
# Compatibility Report
- Name of the game with compatibility issues: Marvel's Spider-Man: Miles Morales
- Steam AppID of the game: 1817190

## System Information
- GPU: RX 580 8GB
- Video driver version: Mesa 23.2.8, Mesa 23.3-git and Mesa 23.5-devel
- Kernel version: 6.12.1 and 6.12.1-TKG-eevdf
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/niltonperimneto/a8410735f008dfa470285d4b6fc61e43
- Proton version: Proton 9.0-3, Proton Experimental and Proton Experimental bleeding-edge

## I confirm:

- [x] that I haven't found an existing compatibility report for this game.

- [x] that I have checked whether there are updates for my system available.

[steam-1817190.log](https://github.com/user-attachments/files/17953948/steam-1817190.log)

## Symptoms 

The game seems to have a memory leak as it starts fine and during the gameplay, out of nowhere the framerate tanks more than half becoming unplayable

## Reproduction

Start playing, after an hour of gameplay the framerate tanks to 20fps (my framerate avarages around the 80s), even on the main menu

**Comment by kisak-valve** [comment]
Hello @niltonperimneto, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6328#issuecomment-2507805985.
