### ISSUE TITLE
STAR WARS Jedi: Survivor (1774580)

### ISSUE THREAD

**Issue by niltonperimneto** [ValveSoftware/Proton#8273]
# Compatibility Report
- Name of the game with compatibility issues: STAR WARS Jedi: Survivor
- Steam AppID of the game: 1774580

## System Information
- GPU: RX 580 8GB
- Video driver version: Mesa 23.2.8, Mesa 23.3-git and Mesa 23.5-devel 
- Kernel version:  6.12.1 and 6.12.1-TKG-eevdf
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/niltonperimneto/a8410735f008dfa470285d4b6fc61e43
- Proton version: Proton 9.0-3, Proton Experimental and Proton Experimental bleeding-edge

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton log [steam-1774580.zip](https://github.com/user-attachments/files/17954013/steam-1774580.zip)

## Symptoms 

The textures are stuck with a really low LoD and doesn´t get better, maybe it is a texture streaming issue.

## Reproduction

Just play the game, the issue persists throughout all the gameplay
Here a screenshot of the issue

![Captura de tela de 2024-11-22 19-32-18](https://github.com/user-attachments/assets/4177b814-bff7-4bba-801f-880195141a97)

**Comment by kisak-valve** [comment]
Hello @niltonperimneto, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6729#issuecomment-2507811115.
