### ISSUE TITLE
Ultrakill freezes after playing or launching any other games that use Steam Play before it, forcing me to delete its compatdata folder as a workaround.

### ISSUE THREAD

**Issue by BugsyReportsy** [ValveSoftware/Proton#8274]
# Compatibility Report
- Name of the game with compatibility issues: Ultrakill
- Steam AppID of the game: 1229490

## System Information
- GPU: RTX 3080 Ti Max-Q
- Video driver version: NVIDIA 560.35.03
- Kernel version: 6.9.3-76060903-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/BugsyReportsy/523d2435c923b49d6842690f5e97e2b4
- Proton version: Experimental, any version

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When I try to launch Ultrakill with any version of Proton, the game would freeze a few seconds after launch. The only way to fix this is to delete the game's compatdata folder and sometimes to verify the integrity of the installed files afterwards. This has occured repeatedly and frequently within the past 2 months regardless of what OS I'm using. I've played on Endeavour OS, Linux Mint, and Pop!_OS, where I had the exact same issue and workaround. So far I have only experienced this issue often with Ultrakill and less often with games that don't officially support Proton such as Ultimate Admiral: AoS, since Deadlock doesn't have the same problem despite using Proton Experimental.

## Reproduction
1. Launch Ultrakill after having previously played/launched a different Steam game which either uses Proton or Linux Runtime, TF2 or Deadlock for my specific case.
2. Expect Ultrakill to freeze a few seconds after launch, expect it to be a 50% chance.

**Comment by kisak-valve** [comment]
Hello @BugsyReportsy, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4406#issuecomment-2508960344.
