### ISSUE TITLE
My Dream Setup (2200780)

### ISSUE THREAD

**Issue by legoraft** [ValveSoftware/Proton#8278]
# Compatibility Report
- Name of the game with compatibility issues: My Dream Setup
- Steam AppID of the game: 2200780

## System Information
- GPU: -
- Video driver version: Mesa 24.2.7
- Kernel version: 6.6.63_1
- Link to full system information report as [Gist](https://gist.github.com/): [Sys Info](https://gist.github.com/legoraft/257fa52dad41de402db7b4b3df4ea9cb)
- Proton version: experimental

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

[Game log](https://file.io/G8oT8aSiI1Zc)

## Symptoms 
The game launches for about 5 seconds and then crashes without any error displayed

## Reproduction
1. Open My Dream Setup
2. See the game loading
3. Game crashes before loading bar is completed

**Comment by kisak-valve** [comment]
Hello @legoraft, your Proton log is saying there's not enough memory to use with DXVK and your Intel GPU. You might get lucky be adding a swap partition or swap file.

**Comment by legoraft** [comment]
ah thank you, will close this now
