### ISSUE TITLE
Portal 2 Authoring Tools (629)

### ISSUE THREAD

**Issue by Hex4dec** [ValveSoftware/Proton#8279]
# Compatibility Report
- Name of the game with compatibility issues: Portal 2 Authoring Tools
- Steam AppID of the game: 629

## System Information
- GPU:  RX 6600 XT
- Video driver version:  Mesa 24.2.5
- Kernel version:  6.11.6
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Hex4dec/4f51cf6b524fdc62deb0ce5f3d4550e7
- Proton version: 3.16, 3.7, Hotfix, 5.0, 4.2, 4.11, 5.13, 9.0, Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

From Proton version 5.13:
[steam-629.log](https://github.com/user-attachments/files/17969553/steam-629.log)

## Symptoms 

Does not launch at all. Some 4.x and 5.x Proton versions take slightly longer to crash, but no window appears.

## Reproduction

Launch the game.

**Comment by Hex4dec** [comment]
I could've sworn there wasn't an issue for this, but apparently there is: #1278. I have reproduced the fix for this (downloading the depot) and it works. However, this hasn't received an official Valve statement and the issue doesn't look correctly formatted so I'm letting other people close this if needed.

**Comment by kisak-valve** [comment]
Hello @Hex4dec, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1278#issuecomment-2510024481.
