### ISSUE TITLE
Skyrim SE stuck at loading screen

### ISSUE THREAD

**Issue by TRPB** [ValveSoftware/Proton#828]
I've seen several people say that Skyrim SE works with a solution for NPC audio, however I can't get that far.

Weirdly it works fine under Wine+DXVK so it seems to be a proton issue.

I get to the main menu fine but if I load a game or start a new game it just sits on the loading screen forever. It doesn't crash but it keeps zooming in and out of whatever model is loaded and brings up tips. I've left it for 5 minutes and nothing happens.

It happens with both proton and proton beta. I've tried a fresh install of Arch Linux with the same result as my standard install.

Specs:
Arch Linux
AMD Threadripper 1950x
32gb RAM
nvidia 980ti with 396.54 driver
KDE Plasma desktop
Playing at 3840x2160 but running 1080p makes no difference
no mods, vanilla game straight from steam

**Comment by nstgc** [comment]
Could you provide both a log (use PROTON_LOG=1 in launch options) and your system information (in the client help==>system information)?

**Comment by TRPB** [comment]
System information:

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen Threadripper 1950X 16-Core Processor 
    CPU Family:  0x17
    CPU Model:  0x1
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3400 Mhz
    32 logical processors
    16 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux 4.x (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.18.5-arch1-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12001000
    X Window Manager:  KWin
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 980 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.54
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x17c8
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  3840 x 2160
    Desktop Resolution: 7680 x 2160
    Primary Display Size: 20.51" x 11.54" (23.50" diag)
                                            52.1cm x 29.3cm (59.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 6144 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC1220

Memory:
    RAM:  32025 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Total Hard Disk Space Available:  468083 Mb
    Largest Free Hard Disk Block:  418381 Mb
    VR Headset: None detected

Recent Failure Reports:

```
And log file:

[steam-489830.log](https://github.com/ValveSoftware/Proton/files/2328453/steam-489830.log)

**Comment by kisak-valve** [comment]
Hello @TomBZombie, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4#issuecomment-416607621.

**Comment by yoshi314** [comment]
Same problem here. The other interesting thing to note is that i only see the menus and no 3d geometry.

When starting a new game, i keep seeing the game tips, and they keep changing every few seconds but the rest of the screen is black - there is supposed to be some kind of 3d model with some fog on the left side of the screen. It never loads into actual gameplay.
