### ISSUE TITLE
Ancestors Legacy Multiplayer (620590)

### ISSUE THREAD

**Issue by truckingcareer421** [ValveSoftware/Proton#8280]
This is my first time submitting a report so bear with me.

# Compatibility Report
- Name of the game with compatibility issues: Ancestors Legacy
- Steam AppID of the game: 620590

## System Information
- GPU: NVIDIA GEFORCE GTX 980TI 8GB VRAM
- Video driver version: Nvidia 565.57.01
- Kernel version: 6.12.1-zen1-1-zen
- Proton version: 9.0-3

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
When attempting to host a private or public lobby/server it give out the following error
"Failed to create the game lobby. Please try again later" 
I've been unable to find a server today, but in the past i gotten similar errors when i attempt to join a lobby. this has been an issue for atleast a few years as far i'm aware of.

## Reproduction
1. Launch Ancestors Legacy
2. In the games main menu click on "Multiplayer" 
3. Click on "Host New Game"
4.  Click on either "Host Public Game" or "Host Private Game"

[steam-620590.log](https://github.com/user-attachments/files/17969583/steam-620590.log)

**Comment by kisak-valve** [comment]
Hello @truckingcareer421, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3792#issuecomment-2510010271.
