### ISSUE TITLE
Need for Speed: Heat quietly crashing at startup

### ISSUE THREAD

**Issue by elizj3** [ValveSoftware/Proton#8284]
# Compatibility Report
- Name of the game with compatibility issues: Need For Speed: Heat
- Steam AppID of the game: 1222680

## System Information
- GPU: MSI GeForce GTX 1050 Ti GAMING X
- Video driver version: nvidia 565.57.01
- Kernel version: 6.12.1-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/sech1p/254fe5b656604312e91fc08477bb7ff2
- Proton version: Proton Experimental (also tried with Proton GE)
## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

Game completely not working, despites I tried to run it, game just crashing at startup without any error

**Comment by kisak-valve** [comment]
Hello @sech1p, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3955#issuecomment-2511954335.
