### ISSUE TITLE
Black Desert won't run in true fullscreen

### ISSUE THREAD

**Issue by fxzxmicah** [ValveSoftware/Proton#8295]
# Compatibility Report
- Name of the game with compatibility issues: Black Desert
- Steam AppID of the game: 582660

## System Information
- GPU: GTX 1060
- Video driver version: nvidia 555.135
- Kernel version: 6.11
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: experimental_9.0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Sorry I'm not using the proton provided directly in steam, so I don't know how to enable logging.

## Symptoms 
![截图 2024-12-06 16-13-46](https://github.com/user-attachments/assets/e594668d-caa1-49e6-a8cd-9102d6682a0d)

You can see that the game is full screen, but the rendered portion doesn't show up on the entire screen.

I have a feeling it might have something to do with the xwayland scaling of the gnome desktop. This is because the resolution reported within the game is 1536x864.

1536 = 1920 / 1.25
864 = 1080 / 1.25

Another possibility is that the game makes room for the top panel due to the presence of gnome's top panel? See the screen recording.
[录屏 2024-12-06 16-55-21.webm](https://github.com/user-attachments/assets/f3084972-4d50-451c-9957-ef7fd080fa16)

## Reproduction
Start the game.

**Comment by kisak-valve** [comment]
Hello @fxzxmicah, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3620#issuecomment-2523315869.
