### ISSUE TITLE
Life is Strange: Before the Storm - Crash

### ISSUE THREAD

**Issue by Xeers** [ValveSoftware/Proton#830]
Arch Linux
Nvidia Geforce 950 GTX
AMD FX

Pastebin:
https://paste.drhack.net/?f57a54d0ac442495#ZXIeakX5YnpS4gaT1EZhFANZDPjU0lKaAZ0OsyBkmZI=

========== OUTPUTING STACK TRACE ==================

RtlLookupFunctionEntry returned NULL function. Aborting stack walk.
<Missing stacktrace information>

========== END OF STACKTRACE ===========

**** Crash! ****
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
Game removed: AppID 554620 "", ProcID 7809 
No cached sticky mapping in ActivateActionSet.JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
pid 7815 != 7812, skipping destruction (fork without exec?)

**Comment by Zero86Sk** [comment]
did you try running the game with `PROTON_USE_WINED3D11=1 %command%` ?

**Comment by Xeers** [comment]
Thank you very much. This seems to work

**Comment by kisak-valve** [comment]
Closing as a duplicate of #75.

**Comment by thermalthrottle** [comment]
It doesn't work for me, running Mint 19
