### ISSUE TITLE
Overwatch 2 (2357570)

### ISSUE THREAD

**Issue by Mx-Angel** [ValveSoftware/Proton#8301]
# Compatibility Report
- Name of the game with compatibility issues: Overwatch 2
- Steam AppID of the game: 2357570

## System Information
- GPU: RX 7800XT
- Video driver version: Mesa 24.3.1-arch1.2
- Kernel version: 6.6.63-1-lts
- Link to full system information report as [Gist](https://gist.github.com/Mx-Angel/a5a2c5104eb7561dc433cec0bfccb2de):
- Proton version: Proton-Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton log:  [steam-2357570-OW2.log](https://github.com/user-attachments/files/18052753/steam-2357570-OW2.log)

## Symptoms
Whilst playing Overwatch 2 if I tab out and try and watch a video or any stream, then the audio for both programs will start to stutter, and my PC will start to stutter as well. Slowing down until nothing moves, I can't open or close anything or make any movements, then it finally crashes. After it crashes I recognize that all my network devices are disconnected and get reconnected quickly after. This also occurs if you never tab out but play around 5 games.

## Reproduction

1. Set Overwatch 2 to use proton experimental
2. Start game
3. Try to queue for a match
4. Whilst queuing tab out the game and start watching video content (either Youtube or a Discord stream should work)
5. (Can also happen on home screen or in game, I found it mostly happened during queue)

**Comment by pollux78** [comment]
Please move your report to this one, as this will count as a duplicate and will be closed, thank you 

https://github.com/ValveSoftware/Proton/issues/7033

**Comment by kisak-valve** [comment]
Hello @Mx-Angel, as @polluxau noted, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7033#issuecomment-2526202899.
