### ISSUE TITLE
Proton games randomly stutter after long sessions

### ISSUE THREAD

**Issue by ToreadorVTM** [ValveSoftware/Proton#8307]
Currently playing The Outer Worlds on Steam via experimental, after about an hour or so the game just starts tearing but only if I move my mouse as using the idle camera doesn't cause it 

Demo:
[https://youtu.be/I_nj3nr7z8s](url)

This is also not game specific as I've been having this issue with Red Dead Redemption and Red Dead Redemption 2

Lollipop Chainsaw RePoP is also on experimental but the issue doesn't appear here

**Comment by Leopard1907** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/11446

**Comment by kisak-valve** [comment]
Hello @ToreadorVTM, as @Leopard1907 noted, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/11446. Closing as a duplicate.
