### ISSUE TITLE
Selective rendering in EverQuest

### ISSUE THREAD

**Issue by Qiset** [ValveSoftware/Proton#8309]
# Compatibility Report
- Name of the game with compatibility issues: EverQuest F2P
- Steam AppID of the game: 205710
                                                  build id: 739123
## System Information
- GPU:  RX 560
- Video driver version:  amdgpu
- Kernel version:  Linux 5.10.0-33-amd64 x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Qiset/a6bbdb3240a396715dcac4a46984233d
- Proton version: 7.0-6

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

 No such file was created. Is this perhaps because the game runs with no errors it just has rendering problems but doesn't see that as an error?

## Symptoms 
Rendering of certain terrains within the game fails.  Examples are the land 
and water in the Ocean of Tears ( solid black and solid green, respectively) or the land in North Ro or South Ro (also solid black).  Certain items are also not rendered correctly such as the Words of Darkness or The Harvester (both of which render completely white). 
I'm not sure of the date of this occurrence, since there was a gap of about a year between now and when I previously played this game.   
The only reference to this issue was on the Everquest web site in the comments.  Someone suggested that it might be caused by the drivers especially if it was an Nvidia gpu.  I was using a GT 1030 Nvidia card so I switched out the card to this RX 560. The same problem occurs with both.  

## Reproduction
This issue is present every time I run the game.  I've verified that it doesn't occur when running the game in Windows 11 only when running it on linux.

**Comment by kisak-valve** [comment]
Hello @Qiset, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1885#issuecomment-2537155297.

**Comment by Qiset** [comment]
Ok, thank you.
