### ISSUE TITLE
Mouse input glitchy in non-native resolution

### ISSUE THREAD

**Issue by dreamer** [ValveSoftware/Proton#831]
### Steps to reproduce

1) Start game (affected game list below)
2) The cursor moves 1px up with every mouse event. Happens only if the game runs in non-native resolution.

### Workaround

Setting the game to native resolution solves the problem. However, this workaround might be impossible/hard/inconvenient for users or might lead to stretched game UI in some cases.

### Affected games

This issue was observed in several older titles using DirectX 9 or OpenGL, running on the Id Tech3 or Unreal engine:

* Quake III: Team Arena
* STAR WARS™ Jedi Knight - Jedi Academy™
* Deus Ex: Game of the Year Edition

Some reports on SPCR sheet mentioned, that this issue does not happen in Vanilla wine.

[my specs](https://gist.github.com/dreamer/03179db6f82b01e06ec8fa41faf09f00)

**Comment by dreamer** [comment]
Proton version 3.7-5 Beta fixed this issue (I tested Deus Ex and Jedi Academy in non-native resolutions), so I guess this was a duplicate :)

**Comment by NerosTie** [comment]
Tested with Dungeon Siege and Red Faction, I can confirm it's fixed!

**Comment by Ruedii** [comment]
I know it's impractical, but up-scaling the display output buffer instead of changing the display resolution may work for this issue.  I'm not sure if this would require upstream changes in wine.

**Comment by dreamer** [comment]
@Ruedii Proton already does exactly this (it's one of the differences compared to upstream wine).

**Comment by Ruedii** [comment]
> @Ruedii Proton already does exactly this (it's one of the differences compared to upstream wine).

Is this where the bug might be?

**Comment by legluondunet** [comment]
> @Ruedii Proton already does exactly this (it's one of the differences compared to upstream wine).

it's a proton only patch? Even the wine-staging does not have this feature?

**Comment by dreamer** [comment]
@legluondunet I use wine-staging 3.17 packaged by Fedora and it does not have this feature (it's very noticeable when running the same .exe in wine and in Proton). Maybe it was ported since then.

@Ruedii what bug? This bug (mouse input glitch) was fixed 3.7-5 :) I can't reproduce it since that release.
