### ISSUE TITLE
Satisfactory - Mouse at 1000 Hz causing stutter when turning camera.

### ISSUE THREAD

**Issue by innersp4ce** [ValveSoftware/Proton#8313]
# Compatibility Report
- Name of the game with compatibility issues: Satisfactory
- Steam AppID of the game: 526870

## System Information
- GPU: AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 18.1.8, DRM 3.59, 6.12.4-arch1-1)
- Video driver version: 4.6 Mesa 24.3.1-arch1.3
- Kernel version: 6.12.4-arch1-1
- Link to full system information report as [gist: 20241213_Sysreport-innerspace](https://gist.github.com/innersp4ce/fc3f0963625fcd6117ec874eac7e925b):
- Proton version: Experimental, 9.0-4, Experimental, Hotfix, GE-Proton9-20

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[protondrive: steam-526870.log](https://drive.proton.me/urls/THZE7WPCSM#OYrrT1lmiaGo) 67MiB, not uploadable to gist.
[gist: 20241213_Steamruntimeinfo](https://gist.github.com/innersp4ce/3ed4c06a4f6d3ea28777c73185958b75)

## Symptoms 

After > 30 minutes of gameplay the game becomes stuttery. When standing still and not moving the mouse no stutters occur. When moving with WASD no stutter occurs. When moving the mouse in combination of any of the preceding the stutter occurs. The issues are caused by the 1000 Hz polling rate of my mouse.

Workaround was found by adhering the advice in the link below. Setting the polling rate of the mouse to 500 Hz 
[Archwiki Polling rate resulting in lag with wine](https://wiki.archlinux.org/title/Mouse_polling_rate#Polling_rate_resulting_in_lag_with_wine)

Possibly reintroduced this bug?

Symptoms started between November 1st 2024 and December 11th 2024. No issues before that time.

## Reproduction

use a BenQ ZOWIE EC2-CW mouse and set the polling rate to 1000Hz on the underside of the mouse.

**Comment by kisak-valve** [comment]
Hello @innersp4ce, we're using one issue report per unofficially supported game, and usually I'd transfer this issue report to #7580, but you've pretty much described the issue being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/11446.

Closing as a duplicate.
