### ISSUE TITLE
[Feature Request] Add Xbox-like Quick Resume Feature

### ISSUE THREAD

**Issue by Sporesirius** [ValveSoftware/Proton#8321]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
I'm not sure if the Proton repo is the right place for this, but it would be great to add a feature similar to Xbox's Quick Resume to the Steam Deck/SteamOS, or possibly Proton, that allows users to pause and switch between games without needing to restart them.
This could be further enhanced with the Steamworks Dynamic Cloud Sync feature, enabling players to resume their suspended game on other devices.

**Comment by kisak-valve** [comment]
Hello @Sporesirius, this request is already being tracked at https://github.com/ValveSoftware/SteamOS/issues/734. Closing as a duplicate.
