### ISSUE TITLE
Disney Speestorm on Proton GE 20 or newer

### ISSUE THREAD

**Issue by lucasgabmoreno** [ValveSoftware/Proton#8323]
# Compatibility Report
- Name of the game with compatibility issues: Disney Speedstorm
- Steam AppID of the game: 1537830

## System Information
- GPU: GTX 1650
- Video driver version: nvidia 550.120
- Kernel version: 6.12.5-x64v3-xanmod1
- Link to full system information report as [Gist](https://gist.github.com/): Creating PROTON_LOG=1 %command% file, results in 1,8 GB size log file with Proton GE-21 and still getting bigger until stop game.
- Proton version: Proton GE 20 or 21

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 

Game doesn't work on Proton  20 or newer.
Game works when downgrade to Proton GE-19.

## Reproduction

Add Proton GE 20 or newer and start game.

**Comment by kisak-valve** [comment]
Hello @lucasgabmoreno, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/8156#issuecomment-2547376681.
