### ISSUE TITLE
DEADBOLT (394970)

### ISSUE THREAD

**Issue by Damglador** [ValveSoftware/Proton#8325]
# Compatibility Report
- Name of the game with compatibility issues: DEADBOLT
- Steam AppID of the game: 394970

## System Information
- GPU: 
- Video driver version: mesa 1:24.3.1-3
- Kernel version: 6.12.4-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/Damglador/a02b595154a947005e91e2b0e483f738):
- Proton version: Experimental, 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Game can't launch at all

## Reproduction
Try to launch the game through Steam using Proton

## Additional Notes
I was able to launch and successfully play the game using Bottles gaming preset with disabled DXVK and VK3D with soda-9.0-1

Proton log:
[steam-394970.log](https://github.com/user-attachments/files/18172829/steam-394970.log)

**Comment by kisak-valve** [comment]
Hello @Damglador, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

DXVK failing to initialize usually hints that there isn't a usable Vulkan render path. I'd check if the `vulkan-intel` and `lib32-vulkan-intel` system packages are installed and add them if they're missing.

**Comment by Damglador** [comment]
Yup, installed `lib32-vulkan-intel` and looks like it works fine. Also adding `PROTON_USE_WINED3D=1 %command%` makes it work. That also fixed other oldish games with the same issue
