### ISSUE TITLE
Civilization V launches in DX9 even when DX11 option is selected

### ISSUE THREAD

**Issue by Piotr-Wieczorek** [ValveSoftware/Proton#8327]
# Compatibility Report
- Name of the game with compatibility issues: Sid Meier's Civilization V
- Steam AppID of the game:
8930
## System Information
- GPU:  NVIDIA GeForce RTX 3060 Laptop GPU / NVIDIA Quadro M5000M
- Video driver version:  NVIDIA 550.120
- Kernel version:  6.8.0-51-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Piotr-Wieczorek/61f475c94e76a248ab2833e15b08f429
- Proton version: experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 [steam-8930.log](https://github.com/user-attachments/files/18198195/steam-8930.log)

## Symptoms 
1. Civilization V launches in DX9 even when DX11 option is selected. The native version is unstable and mods need the DX11 Windows version of the game.
2. Also the game doesn't see the mods that launch on startup located in: "/home/piotr/.steam/root/steamapps/compatdata/8930/pfx/drive_c/Program Files (x86)/Steam/steamapps/common/Sid Meier's Civilization V/Assets/DLC"

## Reproduction
1. Never happens on the first attempt. Launch the game with forced experimental.
2. Install any mod in this directory: "/home/piotr/.steam/root/steamapps/compatdata/8930/pfx/drive_c/Program Files (x86)/Steam/steamapps/common/Sid Meier's Civilization V/Assets/DLC"

**Comment by kisak-valve** [comment]
Hello @Piotr-Wieczorek, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3190#issuecomment-2554050620.
