### ISSUE TITLE
Total War: WARHAMMER III hangs on Options screen

### ISSUE THREAD

**Issue by GrafDiffusore** [ValveSoftware/Proton#8329]
# Compatibility Report
- Name of the game with compatibility issues: Total War Warhammer 3
- Steam AppID of the game: 1142710

## System Information
- Ubuntu 24.04 LTS (64 bit)
- Kernel Version: 6.8.0-49-generic
- X Server Vendor: The X.Org Foundation
- X Server Release: 12101011
- X Window Manager: Xfwm4
- Steam Runtime Version: steam-runtime_0.20241024.105847
- Driver: NVIDIA Corporation NVIDIA GeForce RTX 4060/PCIe/SSE2
- Driver Version: 4.6.0 NVIDIA 550.120

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When I start game, it shows "Options" window frame with its contents absent, instead filled with whatever was right in its place before it appeared.

Seems like game can't be even started at all, as no proton log file is generated, only runtime log.
Link to runtime log: https://gist.github.com/GrafDiffusore/217e658717f13b10c67aac3f85e8b752

## Reproduction
Start the game.

**Comment by kisak-valve** [comment]
Hello @GrafDiffusore, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5976#issuecomment-2555893776.
