### ISSUE TITLE
Saints Row IV Controller Issue

### ISSUE THREAD

**Issue by urmanjosh** [ValveSoftware/Proton#8332]
# Compatibility Report
- Saints Row IV (main build and legacy build)
- 206420
- Proton version: Anything after 6.3

No Controller Support unless I use Proton 6.3

Not sure as to what changed but SRIV doesn't get modern Proton Support as the controller doesn't work in the game. Only KB+M. I have tried various controllers and the game will not use the inputs

**Comment by kisak-valve** [comment]
Hello @urmanjosh, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4081#issuecomment-2557452548.
