### ISSUE TITLE
[BUG] Lethal Company.

### ISSUE THREAD

**Issue by VolRencs** [ValveSoftware/Proton#8334]
# Compatibility Report
- Name of the game with compatibility issues: Lethal Company
- Steam AppID of the game: 1966720

## System Information
- GPU: GTX 1660 Ti
- Video driver version: 565.77
- Kernel version: 6.12.6
- Link to full system information report as [Gist](https://gist.github.com/VolRencs/5135cedd415b0ec679ab1abba52bc676):
- Proton version: Experemintal

## I confirm:
- [ Yes] that I haven't found an existing compatibility report for this game.
- [ Yes] that I have checked whether there are updates for my system available.

I can't send logs as they weigh 500MB, here is a line that is repeated a million times: 0:00:01:01.451814886 80141 0x7a07601072c0 ERROR WINE unixlib.c:246:push_event: Failed to push eos event 0x7a0738001c70 to pad src.

1. Going into the game.
2. Create a lobby.
3. I wait for about 15-20 seconds and the game hangs completely.

**Comment by kisak-valve** [comment]
Hello @VolRencs, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7320#issuecomment-2558544272.
