### ISSUE TITLE
JOY OF PROGRAMMING - Software Engineering Simulator - count of operations is doubled (incorrectly) compared to on windows

### ISSUE THREAD

**Issue by mark9539** [ValveSoftware/Proton#8335]
# Compatibility Report
- Name of the game with compatibility issues: JOY OF PROGRAMMING - Software Engineering Simulator
- Steam AppID of the game: 2216770

## System Information
- GPU: RTX 3060 Ti
- Video driver version: NVIDIA 565.77
- Kernel version: 6.12.6-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/mark9539/1e130cb17718f86b41bbca8e5240ef57
- Proton version: tested with 7.0-6, 8.0-5, 9.0-4, Experimental (and bleeding edge), hotfix

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 (Proton log added as a zip file)

## Symptoms 
In some levels there is an extra challenge to complete the objective using a limited number of commands - when running this game from my linux partition then each of the commands appears to be double counted (making it hard to complete!). 
If the same python script is run (on the same pc) under Windows then the commands count for 1 each as expected.
On Linux it does count as a single operation if using  the single step over under "Debug" - it is the "Run" mode which shows the problem.

I have checked the main branch as well as pre-release. Using DirectX 12 and directx 11 launch options.

## Reproduction
<I've broken down the minimal steps without having to understand or solve the problem on the level, or import an example script>
0) Click "Play Game" on the computer to get into the game proper. 
1) From the main menu: click "Play Scenario", "Logistics", "Crane Lift" to load the level
2) Click Code icon at the top, select script 2, press clear to get a starting template. (I am using script 2 so I don't lose my solution in script 1 - it will happen from any script page)
3) Enter the following line at line:11: (should be an empty line in the template)

AirliftCrane.first().pickup()

It goes before the while loop so it only executes once. This should count as a single command for the challenge.

To reproduce the error:
4) a)  Press the reset sim environment button - lower right side - ( the counter will not reset between tests otherwise)
    b)  Under the map briefing text on the right side of the screen there will be a counter in yellow or green text (Note: the  extra challenge text and counter appear only after starting the 1st run - not on load)
     b) Press Run at the top of the code window, the count of operations updates to 2 (bug) - this does not happen under windows - it will count 1 operation as expected

Alternatively: (demonstrates counter is working in debug mode)
5) a)  Click reset again to clear current state / operations counter to 0.
     b) Click beside line number 11 to set a breakpoint
     c) Press the Debug icon at the top of the screen
     d) Press "Over" (F10) to single step past the "pickup()" operation. 
          Then single step again or run (F5) to ensure it is in the while loop - the count will remain at 1 (correct)
     e) It is the single step that is key, choosing either Continue (Free run to next breakpoint) or Into (Step into) will
         produce the error.

**Comment by mark9539** [comment]
[steam-2216770.zip](https://github.com/user-attachments/files/18222889/steam-2216770.zip)
Here is the proton log, I guess drop didn't work.

**Comment by kisak-valve** [comment]
Hello @mark9539, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7539#issuecomment-2558549592.
