### ISSUE TITLE
Hogwarts Legacy - Artifacts 

### ISSUE THREAD

**Issue by Shanrya** [ValveSoftware/Proton#8340]
## Compatibility Report
- Name of the game with compatibility issues: Hogwarts Legacy
- Steam AppID of the game: 990080

## System Information
- GPU: Arc B580
- Video driver version: Mesa 24.2.8
- Kernel version: 6.12.5-200.fc41.x86_64 (64 bit)
- [Gist](https://gist.githubusercontent.com/Shanrya/71ff7a9a824a21d98e53ffe0bf9cd9c7/raw/f6319472dcc2b6377704dcaeb2c9e7e1f196c3ed/gistfile1.txt)
- Proton version: 9.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Issues with textures and lightnings

## Reproduction
Just started the game.
I've tried to change graphic settings but nothing worked.
The two clips were recorded with everything maxed out, FHD with v-sync on, upscalers disabled (tried XeSS and FSR 2 but nothing changed).

https://github.com/user-attachments/assets/2af15856-021e-4f42-bbe4-93c3cfc97c5c

https://github.com/user-attachments/assets/f7b90ffe-a029-4607-8def-92ddad32d16d

[steam-990080.log](https://github.com/user-attachments/files/18240297/steam-990080.log)
[Steam_SystemReport_20241224.txt](https://github.com/user-attachments/files/18240298/Steam_SystemReport_20241224.txt)
[vulkaninfo_--summary.txt](https://github.com/user-attachments/files/18240299/vulkaninfo_--summary.txt)

**Comment by kisak-valve** [comment]
Hello @Shanrya, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6510#issuecomment-2561212812.
