### ISSUE TITLE
Omensight: Definitive Edition Crash on start up and crash the whole Steam Client

### ISSUE THREAD

**Issue by daishishi** [ValveSoftware/Proton#8343]
# Compatibility Report
- Omensight: Definitive Edition
- Steam AppID of the game: 455820

## System Information
- GPU: Radeon RX 6570XT
- Video driver version: Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
- Kernel version: 6.9.3-76060903-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/daishishi/455a9447a5580efb1b531d3f118767d4
- Proton version: Proton Hotfix / Proton Experimental / Proton 8 / Proton 7 / Proton 6

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

 
[steam-455820.log](https://github.com/user-attachments/files/18246605/steam-455820.log)
[Dumps.zip](https://github.com/user-attachments/files/18246607/Dumps.zip) -> Here are various dump files also.

## Symptoms  
The game crashes immediately when click Run, and also the whole steam client closes with it.
Weirdly I can run the game executable directly using Lutris, and the wine **ge-proton 8**, and it run without a problem with fmv.

## Reproduction
Try to run the game.

**Comment by kisak-valve** [comment]
Hello @daishishi, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1106#issuecomment-2561940852.
