### ISSUE TITLE
file descriptor limit

### ISSUE THREAD

**Issue by ipr** [ValveSoftware/Proton#8345]
Proton is complaining about low file descriptor limit of 65536 when system limit is much higher: 9223372036854775807

This occurs with systemd 257-2 which apparently has changed something in handling of limits (limits.conf has hard limit of 524288, which isn't that high but still higher than Proton expects).

This occurs with Proton 9.0-4 and Experimental. Both had recent hotfix. 
Game that refuses to start is Crime Scene Cleaner (appid 1040200).

Edit: problem with starting seems to be due to bad block in filesystem. So that warning from Proton is actually just misleading.

**Comment by layercak3** [comment]
The hard limit by systemd is still 524288, unless your distribution changed something (systemd version 257-2?) or maybe you're running under a unit with a lower LimitNOFILE set?

**Comment by ipr** [comment]
> The hard limit by systemd is still 524288, unless your distribution changed something (systemd version 257-2?) or maybe you're running under a unit with a lower LimitNOFILE set?

Looks like /etc/security/limits.conf no longer has effect since sysctl fs.file-max reports essentially unlimited.

As far as I can see, DefaultLimitNOFILE is commented out everywhere so unlimited is the default?

Either way, the warning seems outdated when limit is much higher (whatever it is).

**Comment by layercak3** [comment]
`fs.file-max` is a global thing for the kernel, the per-process RLIMIT_NOFILE which proton checks for and is what is important can be found with `prlimit -n`.

**Comment by ipr** [comment]
> `fs.file-max` is a global thing for the kernel, the per-process RLIMIT_NOFILE which proton checks for and is what is important can be found with `prlimit -n`.

Ah, right. My mistake then.
