### ISSUE TITLE
UEVR injector for VR enablement

### ISSUE THREAD

**Issue by drjoms** [ValveSoftware/Proton#8346]
UEVR fails to detect game's process for injection.
See attachment for more information.
[uevr.txt](https://github.com/user-attachments/files/18253653/uevr.txt)

**Comment by kisak-valve** [comment]
Hello @drjoms, we're using one issue report per unofficially supported game title (game mods are discussed with the base games), so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7667#issuecomment-2562904245.
