### ISSUE TITLE
Grand Theft Auto: Vice City

### ISSUE THREAD

**Issue by Xeers** [ValveSoftware/Proton#835]
Nvidia Geforce GTX 950
CPU AMD FX
https://gist.github.com/Xeers/219b4b3e5eb10c6ec225d7cc8c61be44

These commands do not work:

PROTON_USE_WINED3D11=1 %command%

"Created gta_dxvk.conf file":

dxgi.customDeviceId = E366
dxgi.customVendorId = 1002

"Went to the game properties and set launch options":

DXVK_CONFIG_FILE=/path/to/gta_dxvk.conf %command%

Pastebin:
https://paste.drhack.net/?c79d628393d03bc3#RPw3ViDvblIt9va6px3Q6UGpZONKSTBlV1e7ql9yv50=

**Comment by kisak-valve** [comment]
Hello @Xeers, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/291#issuecomment-416635623.
