### ISSUE TITLE
Persona 3 Reload (2161700)

### ISSUE THREAD

**Issue by space2ninja101** [ValveSoftware/Proton#8356]
# Compatibility Report
- Name of the game with compatibility issues: Persona 3 Reload
- Steam AppID of the game: 2161700

## System Information
- GPU: GTX 1050 Ti
- Video driver version: nvidia 565.77
- Kernel version: 6.12.4-artix1-1
- Link to full system information report as https://gist.github.com/space2ninja101/52c4a70dc9f913ea4cf45e1588143459
- Proton version: Proton 9.0.4

Launch arguments: `PROTON_LOG=1 WINEDEBUG="+timestamp,+pid,+tid,+seh,+debugstr,+module" %command%`

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2161700.log](https://github.com/user-attachments/files/18271417/steam-2161700.log)
## Symptoms 
Game crashes immediately parsing shaders, disabled pre-caching and has same result.
No window pops up, just UE4's crash reporter.
Running with PROTON_USE_WINED3D=1 does however make a black fullscreen window appear, however it crashes after a few seconds. I have no plans to use WINED3D.

## Reproduction
Run Persona 3 Reload with Proton 9.0.4.

![image](https://github.com/user-attachments/assets/b79206f5-9929-4cd0-a60d-a43872dfdf50)
Window that comes up:

**Comment by kisak-valve** [comment]
Hello @space2ninja101, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7472#issuecomment-2564942606.
