### ISSUE TITLE
Option to change proton's wine-prefix on per-user basis

### ISSUE THREAD

**Issue by BillGHero** [ValveSoftware/Proton#8359]
# Feature Request

## I confirm:
- [confirmed ] that I haven't found another request for this feature.
- [confirmed ] that I have checked whether there are updates for my system available that
      contain this feature already.

**Comment by kisak-valve** [comment]
Hello @BillGHero, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/6958. Closing as a duplicate.
