### ISSUE TITLE
Bioshock 2 hangs during transfer from one level to another

### ISSUE THREAD

**Issue by zvbarev** [ValveSoftware/Proton#836]
Ubuntu 18.04
Proton 3.73
Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz
NVIDIA GeForce GT 735M
Driver Nvidia 396.54

Game runs smoothly but when I go from level 1 to Atlantic Express game hangs.
Adding PROTON_NO_ESYNC=1 %command% to the launch options fixed the problem

**Comment by kisak-valve** [comment]
Hello @Sebastian1978, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/389#issuecomment-416637975.
