### ISSUE TITLE
DuckTales remastered

### ISSUE THREAD

**Issue by shaphanpena1** [ValveSoftware/Proton#844]
Works flawlessly. Instantly detected steam controller as game pad. Have yet to test Xbox 360 controller.

**Comment by Gustavo17pacheco** [comment]
I don't see how this is a issue.

**Comment by Dazarlin** [comment]
Please mark the title as a [Whitelist Request] and give your system info.

**Comment by HonkingGoose** [comment]
Hello @shaphanpena1 
Issue  #597 Is already covering this, as a Whitelist request.
You might add your comment to that issue.
