### ISSUE TITLE
Lego marvel superheroes

### ISSUE THREAD

**Issue by shaphanpena1** [ValveSoftware/Proton#845]
Works flawlessly. Instantly detected steam controller. Have yet to test Xbox 360 controller. My system specs are: Intel core i3 4170, 8gb ram, gigabyte 2gb ddr5 gt 1030

**Comment by Zero86Sk** [comment]
Games that worked should be marked 
[Whitelist] Game Name (app id) so:
[Whitelist] LEGO Marvel Super Heroes (249130)

also copy the steam information to a gist and link it here.

**Comment by shaphanpena1** [comment]
Whitelist] LEGO Marvel Super Heroes. Works. Latest steamos and Nvidia drivers. My specs are as follows: Intel core i3 4170, 8gb ram, Nvidia 2gb ddr5 gt 1030

**Comment by brauliobo** [comment]
with Proton 5.13 I found the following regressions:
1) controller can't be dynamically plugged (turned on and connected to a 2nd player during gameplay)
2) Voice not being reproduced, for instance when joining a Deadpool phase

**Comment by kisak-valve** [comment]
Hello @brauliobo, looks like the reporting user has chosen to close this issue report and there's no other compatibility report tracking this game. Please open a new compatibility report.
