### ISSUE TITLE
SUSE users?

### ISSUE THREAD

**Issue by hemna** [ValveSoftware/Proton#85]
Do you have any instructions for those of us that run SUSE Leap?

**Comment by aeikum** [comment]
It's not something we've tested, but Proton should work on any sane Linux distro that otherwise works well with Steam. Are you having a problem?

**Comment by rombert** [comment]
@hemna - I just gave this a quick test on openSUSE Tumbleweed and it worked - I don't expected any problems on Leap.

**Comment by hellcp** [comment]
@rombert I wouldn't be so fast to judge that, Ubuntu 18.04 needs updated drivers, and Leap runs on older kernel, on top of that Nvidia 396 is not available in our repos (neither for Leap nor Tumbleweed), so it requires manual installation.

@hemna It's openSUSE, not SUSE :D

**Comment by rombert** [comment]
Well, trying is still the best way to test that :-)

**Comment by hemna** [comment]
My bad, 
I was reading the instructions on the article that said I had to build proton.   I just enabled the steam beta and proton seems to be working on my Leap 42.3.   That being said, there doesn't seem to be a way for us to build it....fwiw.
