### ISSUE TITLE
[Whitelist] Bioshock Remastered (PROTON_NO_ESYNC)

### ISSUE THREAD

**Issue by Vash63** [ValveSoftware/Proton#856]
Game works perfectly once esync is disabled. With esync enabled, many textures fail to load and are extremely, extremely blurry. Example of blurry textures: https://steamuserimages-a.akamaihd.net/ugc/959718413753068067/533AB9395D598DA36A38B26AADD27D00EC17C8AB/

Probably the same for the sequel.

System info: https://gist.github.com/Vash63/2f11788f9121a21548d573c9856100c4

**Comment by d10sfan** [comment]
There's a ticket for this one already: #399

**Comment by Vash63** [comment]
Thanks, closing. Not sure why that didn't come up in my search earlier. Must have typo'd.
