### ISSUE TITLE
[Question]: PBA patches?

### ISSUE THREAD

**Issue by Mushoz** [ValveSoftware/Proton#86]
For the games that use WineD3D, are the PBA patches included in Proton to offer better performance?

**Comment by cjwijtmans** [comment]
no. this project focuses on DXVK as far as i know.

**Comment by Mushoz** [comment]
I know, but lots of games use dx9, which is unsupported by DXVK. PBA would help WineD3D in these cases.

**Comment by cjwijtmans** [comment]
new version of DXVK might support DX9, perhaps valve could merge VK9 with DXVK.

**Comment by aeikum** [comment]
We're working on getting the PBA and related patches upstreamed.

**Comment by Mushoz** [comment]
That is fantastic news! Should the PBA patches be rejected upstream, would they be included in Proton regardless?

**Comment by mirh** [comment]
And why would they have to be rejected if they are totally relevant to the proper functioning of wine?
If any the right question should be how they are going to treat staging or experimental patches.

**Comment by IceAmaura** [comment]
I think another way to ask Mushoz's question is would the PBA patches be included into Proton if anything were to prevent quick upstreaming? (not necessarily rejection)

**Comment by ibrokemypie** [comment]
not sure if this has been touched already (or even if it is already included) but the gallium nine patches would be fantastic for amd (and future intel) users

**Comment by mirh** [comment]
#66... (why people don't search?)

**Comment by ZachBacon** [comment]
@cjwijtmans so yeah.. dxvk won't support dx9, nor do I think they'll merge with vk9. Much different code bases.

**Comment by yaomtc** [comment]
Just tested Guild Wars 2, which is a good example of a modern demanding DirectX 9 game, with the same settings twice. First with Lutris, where I use Wine with the PBA patches installed, among others. I get around 70 fps. Next I test with Steam Play, with the same environment variables (minus the one specific to pba), with the same character in the same location... and I get around 40 fps. I know GW2 isn't on Steam, but I'm sure there's plenty of Steam games that could greatly benefit from the PBA patches. Hope it can be upstreamed soon, or at least brought into Proton.
