### ISSUE TITLE
Bejeweled Twist (3560) Fatal Error

### ISSUE THREAD

**Issue by Zero86Sk** [ValveSoftware/Proton#861]
When you launch the game. It gives you an error.
`Invalid command line parameter: -changedir`

[steam-3560.log](https://github.com/ValveSoftware/Proton/files/2329756/steam-3560.log)

[My Steam Information](https://gist.github.com/Zero86Sk/d629f657c1ae861c36657cdf238a7765)

**Comment by kisak-valve** [comment]
Hello @Zero86Sk, this issue is already being tracked at #340. Closing in favor of the existing issue report.
