### ISSUE TITLE
[Question] Will Proton be rebased against newer Wine versions?

### ISSUE THREAD

**Issue by XaeroVincent** [ValveSoftware/Proton#870]
Proton is based on Wine 3.7 but the latest is 3.14.

Will Proton be rebased on newer Wine releases on a regular basis or be a fork of v3.7 with cherry-picked commits from upstream and Valve modifications going forward and eventually diverge further and further from upstream as times goes on, similar to how Cadega had?

**Comment by NickZ** [comment]
It looks like the guy who is making most of the changes on the Valve fork of wine is a CodeWeavers employee, so I doubt that they'd let that happen.

**Comment by aeikum** [comment]
Yes, there are plans to upgrade Proton with the latest changes from Wine.
