### ISSUE TITLE
[Request] Please let us install the windows version of a game even if there's a native linux build available

### ISSUE THREAD

**Issue by UntouchedWagons** [ValveSoftware/Proton#878]
The linux build of Civ 6 is - to put it nicely - unplayable. At the moment I have to resort to a virtual machine running windows with a dedicated GPU which is less than ideal. So, please give us the option to install the windows build of a game even if there's a native linux build available.

**Comment by vanyasem** [comment]
[This reddit post](https://www.reddit.com/r/SteamPlay/comments/9anque/steamplayprotonlutris_cheat_sheet/) describes how to install a Windows version of the game via SteamCMD as a temp workaround

**Comment by Pobega** [comment]
A way to do it in-client would be nice. For example, I want to run Binding of Isaac but the native Linux port hasn't worked in Wayland in a year. I also use the Steam Flatpak, so I don't easily have access to steamcmd.

**Comment by NoXPhasma** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/5638

**Comment by kisak-valve** [comment]
Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5638.

**Comment by UntouchedWagons** [comment]
@vanyasem How would I find the steam App ID for a game?
