### ISSUE TITLE
Support windows applications natively in Linux?

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/Proton#88]
This is first a question, and maybe a feature request.

Many people are concerned that "emulation" like with proton means that developers are disincentivized to make native linux applications and games.

But windows-only applications are ubiquitous and we will need something like wine/proton to run a huge mountain of legacy applications anyway.

So why not implement native support for Windows applications in Linux.
When implementing native support for the windows PE executable format and the windows Syscalls in the kernel (and maybe some non trivial glue code), windows applications could run natively in linux by making use of the win32 API implemented in native userland libraries (open source implementations by wine).

One project that has been working on this is Longene: https://en.wikipedia.org/wiki/Longene

Unfortunately

> As of August 2018, the official website is gone, signifying the end of the project. However, the source code is still available on GitHub.

Maybe this project could be revived?

**Comment by thunder1410** [comment]
I think this is hard to do without having license issues with Microsoft.
Maybe not everyone wants to have windows stuff compiled into their linux kernel?

**Comment by cjwijtmans** [comment]
not in the scope of this project.
