### ISSUE TITLE
[suggestion] install the right python version when not avaliable

### ISSUE THREAD

**Issue by thunder1410** [ValveSoftware/Proton#89]
At first I couldn't get anything working because I didn't have python installed?
Is it possible for steam to check if the right version is installed and maybe ask to install it?

**Comment by Rosalie241** [comment]
why would *they* need to do work *you* should have done?

There are many distributions and it's a pain to install the right dependencies for each of them using 1 script

You need to setup *your* own development env :)

Also, maybe read [this](https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md) and read the README to get you started

**Comment by cjwijtmans** [comment]
this is the task of your distribution not for valve.

**Comment by thunder1410** [comment]
it didn't came with my ubuntu 18.04.1 LTS install, so at first I didn't know what was wrong but I found out after reading issue #15 .
Ok maybe just say that you need to install python (2.7) with a link to an install page.
Just so you know if it is not installed what is missing and why it isn't working instead of just not starting the game.
Maybe an autoinstall for the supported distros like ubuntu,STEAM OS (and maybe debian)?

**Comment by kisak-valve** [comment]
Hello @thunder1410, automatically installing additional system dependencies is outside of the scope of this project and the rest of this discussion is already being tracked at #15.

Closing in favor of #15.
