### ISSUE TITLE
Question: how to enable DXVK HUD with proton?

### ISSUE THREAD

**Issue by legluondunet** [ValveSoftware/Proton#891]
Hello,
Could you tell me how to enable DXVK HUD with Proton?
Thanks.

**Comment by pchome** [comment]
Possible solutions:
* place it into your ~/.profile as `export DXVK_HUD=fps`
* run Steam with `env DXVK_HUD=fps steam`
* modify game launch params as `DXVK_HUD=fps %command%`
* ...

_I'm not sure about any of this variants._

**Comment by LeD3F** [comment]
In launch options DXVK_HUD=1 %command% or DXVK_HUD=fps,devinfo %command%

**Comment by aeikum** [comment]
The above will work. You can also add it to user_settings.py in the Proton folder to enable it for all games.
