### ISSUE TITLE
[Whitelist] Pathfinder adventures (480640)

### ISSUE THREAD

**Issue by Cuddlypuff** [ValveSoftware/Proton#892]
Even though it outputs a surprising amount of stuff to the terminal, everything seems to be working (played through the tutorial without issues)

https://gist.github.com/Cuddlypuff/a518019d119623d9a1b7552e284c1f6d

**Comment by jvalrog** [comment]
Did my own testing. [My specs](https://gist.github.com/jvalrog/93c304fabb18142bbec0c6e839db06f9).

### What works:

* Sound/Music settings
* In-game store menu
* Assigning keybindings
* Alt-tabbing
* Fullscreen/Windowed
* Different resolutions
* Collections menu
* Quitting
* Steam overlay
* Tutorial
* Normal games

### What doesn't work:

* Changing back to my original resolution (2560x1080), but
it's a game bug according to this [forum post](https://steamcommunity.com/app/480640/discussions/0/1697169163395760547/). ~~Solution is to use regedit for fixing it.~~
* I think the game doesn't support ultra-wide screens even though it works the first time. Many things are misplaced in the game at 21:9 resolution. After setting it to 1920x1080 there is no way to return to 2560x1080. So it looks like a game bug to me.

### What I didn't test:

* Linking a device

### Conclusions:

* Game is a definitive whitelist candidate

**Comment by jvalrog** [comment]
More on the issue stated above.

I think it's an Unity bug since the same happens in the Unity game **80 Days**. I'm able to achieve 2560x1080 but the drop down menu of resolutions will never show it as a choice.

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.
