### ISSUE TITLE
Some games save steam cloud files to pfx instead of documents.

### ISSUE THREAD

**Issue by juppso** [ValveSoftware/Proton#897]
I have noted that Fallout 4 and Skyrim: Special edition save their save games and config files to the My Games folder, in the My Documents of wine user steamuser inside of the prefix, as opposed to in the Linux users home folder. It would appear that normal wine does this using a symlink from my documents of the other user to ~/Documents, perhaps such a setup needs to be done for the steamuser, or games should be loaded as the linux usernamed wine user.

**Comment by NoXPhasma** [comment]
I think the current behaviour is much better. I was never pleased by the fact that Wine created Windows folders in my home.

**Comment by Dexter9313** [comment]
I agree with @NoXPhasma

**Comment by kisak-valve** [comment]
Hello @juppso, this is already being tracked at #231. Closing as a duplicate.
