### ISSUE TITLE
Request: show beta testers an in-client survey after trying a non-supported game, offer common solutions 

### ISSUE THREAD

**Issue by hzulla** [ValveSoftware/Proton#900]
Hi,

Proton is mightily impressive, but the current way of collecting feedback here is madness: Github issues, forum threads and public spreadsheets? _This doesn't scale,_ this can't be the way to go. I will gladly continue to try non-supported games with Proton on my Linux machine, but please offer a more streamlined way to provide feedback to you.

Please consider this:

- Beta testers opt-in to a survey after running non-whitelisted games.
- The survey asks the user to rank the gaming experience.
- The survey offers checkboxes for common symptoms (e.g. vsync issues, audio missing, audio loop issues, DX9 crashes etc.) and _will provide possible alternative settings to the beta tester to try_. (*) The beta tester will be encouraged to try these fixes and the client will allow the beta tester to report if the proposed fix was successful.
- The survey results and fix reports will be collected with system info logs to Valve. Based on the incoming reports, you guys then can easily identify whitelisting candidates, popular yet buggy games or see where further research is needed.

I hesitate to create more Github issues, but would love to click through my game library and fill out a survey after each game to get Proton up to speed.

(*) E.g., #524 is an example of a readily-available fix to a known symptom that could be offered and tested that way.

**Comment by kisak-valve** [comment]
Hello @hzulla, this is a feature request for the steam client, not Proton, and also being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5662. Closing as a duplicate.
