### ISSUE TITLE
[whitelist] blackwell epiphany (236930)

### ISSUE THREAD

**Issue by voidplayer** [ValveSoftware/Proton#91]
Everything seems to work

**Comment by kisak-valve** [comment]
Hello @voidplayer, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by voidplayer** [comment]
https://gist.github.com/voidplayer/944d4bbd6dda4f726d479cd99bb66481

**Comment by kisak-valve** [comment]
Closing per the comment at https://github.com/ValveSoftware/Proton/issues/2492#issuecomment-1053185103.
