### ISSUE TITLE
Control problems in the S.T.A.L.K.E.R: Shadow of Chernobyl (4500)

### ISSUE THREAD

**Issue by skobkin** [ValveSoftware/Proton#911]
When I'm trying to set up "sprint" key in the controls section of the settings I'm encountering bug.

If I press "shift" key then game recognizes it as `Num_Lock` and if "caps lock" is enabled when I press "shift" game recognizes it as `Caps_Lock`.

System info: https://gist.github.com/skobkin/a37176c8512da3c59017eb7540dc571b

**Comment by kisak-valve** [comment]
Hello @skobkin, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by skobkin** [comment]
@kisak-valve Done, thanks.

**Comment by sputniktr02** [comment]
@skobkin I have the same issue, as a workaround you can disable "num lock" on your keyboard, that way game recognizes keys correctly.

**Comment by skobkin** [comment]
@sputniktr02 I have no "Num lock" key on my keyboard :)

Although I don't really need it to work now (I've just tested Proton and wasn't intended to play this game) thanks for workaround. Hope Valve will fix this issue.

**Comment by martinpl** [comment]
Jacek Caban send fix for that:
https://source.winehq.org/patches/data/152924

**Comment by aeikum** [comment]
Thanks for reporting. This should be fixed in 3.16-4.

**Comment by aeikum** [comment]
Thanks, this was fixed a while ago.

**Comment by kisak-valve** [comment]
@aeikum, we may want to hold this issue open as a request to bump the proton version for the game in the white list.

**Comment by aeikum** [comment]
Oh, good point, you're right. Thanks.

**Comment by kisak-valve** [comment]
The whitelist entry for this game has been bumped to Proton 3.16 (non-beta).
