### ISSUE TITLE
[Whitelist] Star Explorers (502720)

### ISSUE THREAD

**Issue by MKSchmidt30** [ValveSoftware/Proton#914]
Star Explorers appears to be working without any errors.  

A player (drakend) has tested it successfully with the current version of Steam Play / Proton.

https://steamcommunity.com/app/502720/discussions/0/1519260397785320598/?tscn=1535552023

I was also able to run it with WINE previously.

**Comment by kisak-valve** [comment]
Congratulations, you've made a duplicate of your own whitelist request. Closing as a duplicate of #738.

**Comment by kisak-valve** [comment]
Congratulations, you've made a duplicate of your own whitelist request. Closing as a duplicate of #738.

**Comment by MKSchmidt30** [comment]
I noticed that this request did not receive the "whitelist request" label.  Does that mean anything?

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.
