### ISSUE TITLE
Twilight Struggle crashes on startup (406290)

### ISSUE THREAD

**Issue by zelmor** [ValveSoftware/Proton#923]
Game crashed with access violation, but keeps running in the background according to Steam. 
Profile shows in game, locking up Steam in the process. From attached error.log:

Unity Player [version: Unity 5.4.3f1_01f4c123905a]

TwilightStruggle.exe caused an Access Violation (0xc0000005)
  in module TwilightStruggle.exe at 0023:005276f9.

Error occurred at 2018-08-29_182530.
Z:\home\zelmor\.local\share\Steam\steamapps\common\Twilight Struggle\TwilightStruggle.exe, run by steamuser.
41% memory in use.
0 MB physical memory [0 MB free].
0 MB paging file [2048 MB free].
0 MB user address space [0 MB free].
Read from location 00000000 caused an access violation.

Context:
EDI:    0x013ff49c  ESI: 0x013ff448  EAX:   0x00000000
EBX:    0x00000000  ECX: 0x0033f6fc  EDX:   0x048d13b8
EIP:    0x005276f9  EBP: 0x0033f704  SegCs: 0x00000023
EFlags: 0x00010206  ESP: 0x0033f564  SegSs: 0x0000002b

Bytes at CS:EIP:
8b 10 8b 52 1c 53 50 33 ff 88 5d ff ff d2 85 c0 

Ssytem information:
Debian stable on a Thinkpad T420.
Linux t420 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux

[error.log](https://github.com/ValveSoftware/Proton/files/2332944/error.log)

[output_log.txt](https://github.com/ValveSoftware/Proton/files/2332945/output_log.txt)

**Comment by kisak-valve** [comment]
Hello @zelmor, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by zelmor** [comment]
@kisak-valve :     _X Window Manager:  i3_, but also tried in xfce, same result. Works when running steam through Wine, even with multiple Wine versions.

https://gist.github.com/zelmor/9abed45a108fef154a244295f18c0b9b

**Comment by pmykc1** [comment]
Given this is a Unity game and you have an Intel graphics card, I think this might be a specific case of this issue:
https://github.com/ValveSoftware/Proton/issues/537

**Comment by torvic9** [comment]
Game installs and runs flawlessly here.
Manjaro Linux, nvidia 410.57 with GTX 1070, mesa 18.2.2, proton 3.7-6

**Comment by timschumi** [comment]
@zelmor Try forcing D3D through the launch options (`-force-d3d9`, `-force-d3d10`, `-force-d3d11`, etc.)

**Comment by zelmor** [comment]
@timschumi Forcing didn't work with d9, d10, d11 flags. Error output:

```
Failed to initialize graphics.
Make sure you have DirectX 11 installed, have up to date
drivers for your graphics card and have not disabled
3D acceleration in display settings.
InitializeEngineGraphics failed
```

**Comment by zelmor** [comment]
Issue persists still in Proton 3.16-3 Beta, Debian Stable (same as original defect)

**Comment by zelmor** [comment]
@kisak-valve this issue is resolved in the latest Proton experimental.
