### ISSUE TITLE
Compiling in Fedora 28 ?

### ISSUE THREAD

**Issue by Sebastiangperez** [ValveSoftware/Proton#924]
Is there any way that i can compile this in Fedora ?

**Comment by Numblesix** [comment]
I would also like to see this in Fedora, so i could get rid of dual boot at all :)

**Comment by Sebastiangperez** [comment]
@Numblesix I been using Fedora has my main OS from 4 years or so , and is the best also i have a dedicated ssd with Win7 (I occasionally use ).
I ditched Windows gaming long time ago and now i have two options , Steam for linux and Wine ( now with DXVK).
I think the only missing part of ditching windows entirely is Adobe , if there is any chance that Proton not only run games but also runs apps like Photoshop , this will be huge.

**Comment by Numblesix** [comment]
@Sebastiangperez Yes thats true on my main station im on win10, which is okay but id like to get rid of windows. Seeing this nativ in fedora would be a big plus i would finally have a single os to do all the things i need from work up to gaming :)
