### ISSUE TITLE
[Whitelist] Outlast 2 (414700)

### ISSUE THREAD

**Issue by pprotonrep** [ValveSoftware/Proton#925]
Works very smootly, very impressed by the performance on this one.

- Ubuntu 18.04.1 LTS (64 bit 4.15.0-33-generic)
- GeForce GTX 1070/PCIe/SSE2 (396.54)
- Proton Beta 3.7-4

[System information from steam](https://gist.github.com/pprotonrep/c67cbb6f56d9b88af24952fa45652cdf)

**Comment by mimattr** [comment]
Ubuntu 16.04, NVIDIA GTX 970, Proton 3.7-5 Beta:

[Steam System Information](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)

Test | Result
-- | --
Singleplayer | Working as expected
Local Co-op | _N/A_
Online Multiplayer | _N/A_

Configuration | ...
-- | --
Input | Steam Controller
Display | 1920x1080
Fullscreen | Yes
Preset | Medium^
VSync | On^^
API | DX11

^ Default graphics preset is **Very High**
^^ Frequent screen tearing if VSync setting is **Off**

_NOTE: Testing excludes demo product (521240)_

**Comment by michaeltintiuc** [comment]
Confirming to work just fine
OS: Solus
Graphics: GTX 1050 Ti running 396.54 drivers
Proton: 3.7-3

**Comment by VortexAcherontic** [comment]
I can also confirm, played the whole game with Steam Play

OS: openSUSE Leap 15.0
Kernel: 4.12.14-lp150.12.16-default (Based on 4.12.14)
NVidia driver: 390.87
GPU: GTX 1080
Proton: 3.7-6

[Full specs](https://gist.github.com/VortexAcherontic/8f4720384451f723c5ee64186a298484)

**Comment by kisak-valve** [comment]
This game was found in the 2019-07-31 whitelist update.

If you encounter an issue with this game, please search the open issues for 414700, and report any issues encountered with this game in separate issue reports, one issue per issue report.
