### ISSUE TITLE
Battlezone - Combat Commander (624970)

### ISSUE THREAD

**Issue by teepean** [ValveSoftware/Proton#930]
The game starts to a black screen (opening video?) and stays there. 

Gist:
https://gist.github.com/teepean/a7294a5a3ff5d08790ff7d0095505e54

[steam-624970.log](https://github.com/ValveSoftware/Proton/files/2333338/steam-624970.log)

[Battlezone-Crashed 2018-08-29 01.01.06.4820.log](https://github.com/ValveSoftware/Proton/files/2333362/Battlezone-Crashed.2018-08-29.01.01.06.4820.log)

**Comment by LtSich** [comment]
The game now start with Proton 4.11 but when you try to start a mission the game crash with the error : Bad FPU Control Word

**Comment by kisak-valve** [comment]
Hello @LtSich, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by LtSich** [comment]
Another try with Proton 4.11-2
The game launch fine, when I start a mission the game continu to crash wit the bad fpu word.

Here is my system specs : https://gist.github.com/LtSich/7a5c7dbd795a1bb69c5ce1845599f485
Here is the proton log : https://dl.cafe-philo.net/steam-624970.log

Hope this can help you. The game never worked on Linux for the moment.

**Comment by LtSich** [comment]
Hi everyone,
Now the game is working, we can play with the last proton version.
But I can't assign the keys 2,7,9 and 10... 
I use French keyboard layout. I have try to reassign or change keyboard layout but that doesn't change anything...

**Comment by LtSich** [comment]
If anyone is here, the game now work fine for me, except that I can't regroup unit with ctrl + F(x).
shift + F1 / F2 work fine. F1 / F2 work fine to select unit. But impossible to regroup units...
As there are no option to change this layout I'm unable to test assigning other keys.

Does anyone else have this same issue ?

XFCE already use those shortcuts, can this be the issue ?

**Comment by kisak-valve** [comment]
Hello @LtSich, in general, yes, if a desktop environment has globally binded hotkeys, they are expected to take priority over the game's input, regardless if it's a native linux game or run with Proton.

**Comment by LtSich** [comment]
Yes ! Finally ! That was the issue !
Disabling those shorcut on XFCE was the solution !

Thx, now the game work perfectly out of the box !
