### ISSUE TITLE
Add option to use Windows version of a game even if a Linux port is available

### ISSUE THREAD

**Issue by BeppeInfo** [ValveSoftware/Proton#931]
Some Linux ports don't really run properly, or lack features compared with their Windows counterparts. Having an option to individually select Steam Library entries to prefer the Windows version would be great

**Comment by pprotonrep** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/5638

**Comment by BeppeInfo** [comment]
@pprotonrep Thanks, I didn't look there. My bad. Closing the issue
