### ISSUE TITLE
Warhammer 40,000 dawn of war soulstorm fails to launch (9450)

### ISSUE THREAD

**Issue by BinaryJava** [ValveSoftware/Proton#941]
Running ubuntu 18.04 with a GTX 1080ti and nvidia driver 396.54. Driver has been reinstalled and system restarted.

System info: https://gist.github.com/BinaryJava/e51030a50989f5a16b307d4358268987

**Comment by kisak-valve** [comment]
Hello @BinaryJava, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Additionally, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by BinaryJava** [comment]
I added the launch command and the graphics setup menu appeared, I configured it but after it closed the game still won't open. I cannot find a steam-$9450.log file anywhere on my system, I have enabled hidden files and searched from /

Ultimate doom also crashes on my system, although it opens two windows first.

Edit: After adding the launch option ultimate doom runs even when I remove it

**Comment by BinaryJava** [comment]
Somebody on the steamcommunity forums has fixed it for me, by adding this to launch options: WINEPREFIX=$STEAM_LIBRARY/steamapps/compatdata/9450/pfx
