### ISSUE TITLE
DXVK Fails to initialize

### ISSUE THREAD

**Issue by HeroCC** [ValveSoftware/Proton#945]
Hello Valve! First of all, thank you for starting the Proton project. Between you, Wine, DXVK, and GPU driver devs, this is amazing. Now for my issue. 

It seems to me that for some reason on my system DXVK simply doesn't work. I'm not sure exactly why, it is not game specific, and following DXVK's advice I have no `game_d3d11.log` or `game_dxgi.log` in GTA V or The Witcher III. Both fail to launch, citing lack of a DX11 adapter / driver / compatible card. When launching TW3 with `PROTON_USE_WINED3D11=true %command%` it launches fine, leading me to think that something is up with my DXVK / Vulkan installation, making games think I have no DirectX libraries.

Here is some debug information, let me know if you need more:
Steam System Information: https://pastebin.com/CZaUP3jW
Hardware: AMD FX 8350 / R9 208x Tahiti
I'm running Arch, using the latest stable mesa, and have installed the 32 and 64 bit vulkan drivers / libraries.

**Comment by kisak-valve** [comment]
Hello @HeroCC, give #813 a read.

**Comment by HeroCC** [comment]
That fixed it, thanks @kisak-valve and @davidebeatrici!

**Comment by davidebeatrici** [comment]
You're welcome!
