### ISSUE TITLE
[Whitelist] Call of Juarez Gunslinger

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#951]
Distro: Manjaro XFCE 17.1.12
GPU: GTX 1060, Nvidia proprietary driver 396.54
Resolution: 1920x1080
RAM: 8GB
Proton 3.7-4 Beta

All is fine and Xbox Controller work !

**Comment by d10sfan** [comment]
#951

**Comment by d10sfan** [comment]
#366
