### ISSUE TITLE
[Whitelist] Need for Speed: Hot Pursuit (47870)

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#952]
Distro: Manjaro XFCE 17.1.12
GPU: GTX 1060, Nvidia proprietary driver 396.54
Resolution: 1920x1080
RAM: 8GB
Proton 3.7-4 Beta

All is fine and Xbox Controller work !
No have try MP

**Comment by kisak-valve** [comment]
Hello @liberodark, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/349#issuecomment-417290914.
