### ISSUE TITLE
[Whitelist] Magic 2014 (213850)

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#954]
Distro: Manjaro XFCE 17.1.12
GPU: GTX 1060, Nvidia proprietary driver 396.54
Resolution: 1920x1080
RAM: 8GB
Proton 3.7-4 Beta

All is fine !
MP no try

**Comment by kisak-valve** [comment]
Hello @liberodark, this game is already being tracked at #650. Closing as a duplicate.
