### ISSUE TITLE
Very low performance in certain games (missing 32 bit mpg123)

### ISSUE THREAD

**Issue by psyke83** [ValveSoftware/Proton#957]
System: Ubuntu 18.10 x64 with latest Mesa installed via PPA, switchable graphics (Intel HD 4400 & AMD R7 M260), ```ulimit -Hn``` manually set to 1048576.
Proton: 3.7-4 (stable version also tested)

Issue: unexpectedly low framerate (10-15fps) with constant stuttering in game, followed by the game crashing within a few seconds. Setting ```PROTON_NO_ESYNC=1``` prevents the crash, but not the low performance.

Cause: ```libmpg123-0:i386``` was not marked for installation by the Steam client or Proton, which causes Proton's ```l3codeca.acm.so``` not to load correctly and cause the performance/stability issue.

Resolution: installing the above package resolves the performance issue - no more stutter, and framerate increases to ~40-60fps even on the integrated graphics. ESYNC can also be re-enabled without causing crashes.

Tested on Elder Scrolls IV: Oblivion

**Comment by omicron-b** [comment]
just want to note that TES III: Morrowind is also affected by that
https://github.com/ValveSoftware/Proton/issues/157

**Comment by kisak-valve** [comment]
Related commit: https://github.com/ValveSoftware/steam-runtime/commit/d71625fe19d054d61392517b2f9c9febf4b99734
