### ISSUE TITLE
Fallout Shelter crashes on launch

### ISSUE THREAD

**Issue by samsalot007** [ValveSoftware/Proton#958]
[2018-08-29_231952.zip](https://github.com/ValveSoftware/Proton/files/2334819/2018-08-29_231952.zip)

I am having issues with launching fallout shelter.``
![screenshot from 2018-08-29 23-20-17](https://user-images.githubusercontent.com/2097276/44833266-60cff480-abe2-11e8-9345-8ba9273f21c6.png)

Error log https://gist.github.com/samsalot007/2601c1648198edc0fb074f431977b7fc
System specs https://gist.github.com/samsalot007/7d88303aba1d88185ab335d6a7944686

Anything you can do to help would  be greatly appreciated.

**Comment by kisak-valve** [comment]
Hello @samsalot007, does any vulkan application like `vulkaninfo` work on your system?

Give #813 a read and see if it applies to your system.

**Comment by samsalot007** [comment]
Okay https://github.com/ValveSoftware/Proton/issues/813 has entirely fixed it. I greatly appreciate the help.

**Comment by kisak-valve** [comment]
Closing per the last comment.
