### ISSUE TITLE
changed does not display text (814540)

### ISSUE THREAD

**Issue by prototype99** [ValveSoftware/Proton#961]
everything else functions, however no text displays. a missing font? however i'm not sure what font

**Comment by kisak-valve** [comment]
Hello @prototype99, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Some users have reported adding the corefonts system package helped some games with missing text.

**Comment by prototype99** [comment]
https://gist.github.com/prototype99/9a83970a72601e1a068b2aecc7cf4a4c

however, the corefonts package did indeed do it for me. all the same i guess it is good future reference for other people.

**Comment by dreamer** [comment]
@prototype99 can you reopen this issue? It is not fixed yet - we just know the workaround.
