### ISSUE TITLE
Grand Theft Auto V - blurry textures

### ISSUE THREAD

**Issue by headlesscyborg** [ValveSoftware/Proton#968]
Hi, I play GTA5 using Proton 3.7-3 and it runs great, howewer textures look bad. I'm not sure why, I have AF set to 16x and textures to high.
![20180830120711_1](https://user-images.githubusercontent.com/28152817/44846274-3b79cf80-ac50-11e8-8afb-983105ce7173.jpg)
**A few more screens including in-game settings:** https://imgur.com/a/iOoQiym

See? The far you look the worse the textures are. It looks like broken anisotropic filtering even though it's set to 16x.

**Computer info:**
OS: Arch Linux x64 + Gnome Shell 3.28
CPU: i5 7300HQ
GPU: NVIDIA GeForce GTX 1050 Ti [396.54 driver]
RAM: 24GB DDR4 2400MHz
Steam system info: https://pastebin.com/dnWnu34p

I tried disabling AF in the game, forcing AF to 16x in Nvidia settings, setting shader to high but it's exactly the same.

I use default Proton 3.7-3 with only the workaround suggested by @AlexeyProkhin here https://github.com/ValveSoftware/Proton/issues/37#issuecomment-415833819

**Comment by kisak-valve** [comment]
Hello @headlesscyborg, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-417299386.
