### ISSUE TITLE
RWBY: Grimm Eclipse (418340) fix Controller

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#972]
Distro: Manjaro XFCE 17.1.12
GPU: GTX 1060, Nvidia proprietary driver 396.54
Resolution: 1920x1080
RAM: 8GB
Proton 3.7-4 Beta

Xbox Controller not work !
And error to look perso

**Comment by kisak-valve** [comment]
Hello @liberodark, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/233#issuecomment-417300391.
