### ISSUE TITLE
Sniper: Ghost Warrior (34830)

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#975]
Distro: Manjaro XFCE 17.1.12
GPU: GTX 1060, Nvidia proprietary driver 396.54
Resolution: 1920x1080
RAM: 8GB
Proton 3.7-4 Beta

Not run great and Xbox Controller work !
Full Screen work need to wait and configure game for make full screen
Windows return not work good

**Comment by kisak-valve** [comment]
Hello @liberodark, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/294#issuecomment-417302415.
