### ISSUE TITLE
[Whitelist] Cat Goes Fishing (343780)

### ISSUE THREAD

**Issue by DarkoGNU** [ValveSoftware/Proton#979]
Another little game that works like a charm :) Played for over an hour, tested most features
OS: Ubuntu 18.04
Proton 3.7-4 Beta
https://gist.github.com/DarkoGNU/d280a29b095e42721668abefad8e40b3

**Comment by kisak-valve** [comment]
Found in the 2018-10-05 white list update.

**Comment by vinicioscardoso2419-ops** [comment]
###

**Comment by vinicioscardoso2419-ops** [comment]
Cat goes fishing
