### ISSUE TITLE
[Fail to launch] Assetto Corsa

### ISSUE THREAD

**Issue by adds68** [ValveSoftware/Proton#98]
Running using Proton installed via The Flatpak Steam client

openat(AT_FDCWD, "/home/adds68/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime/d_libs_32/tls/haswell/libpython2.7.so.1.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

**Comment by mirh** [comment]
Do you have python 2.7 installed for starters?

**Comment by alexhaydock** [comment]
This looks like it might be more of an issue with the Flatpak than with Proton.

Might be better to track here: flathub/com.valvesoftware.Steam#152

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/flathub/com.valvesoftware.Steam/issues/152.
