### ISSUE TITLE
Grand Theft Auto V - Input causes frame times to spike after a while

### ISSUE THREAD

**Issue by Clifforus** [ValveSoftware/Proton#985]
Game runs incredibly well for me except from this one issue. After playing for some time, usually about an hour, suddenly every keyboard input and movement of the mouse will cause the frame time to spike for that frame, resulting in a stuttering unplayable mess. If I don't touch the keyboard and mouse, then performance continues to be smooth. Only way to stop the stuttering is to restart the game.

Specs:

CPU: AMD Ryzen 5 1600
GPU: Sapphire 8GB RX 480 Nitro+
RAM: 16GB Corsair Vengeance LPX DDR4 3200MHz
Motherboard: MSI Tomahawk B350

Boot drive: 250GB Samsung 850 EVO
GTA V installed on: 3TB Toshiba 7200RPM SATA III HDD

OS: Lubuntu 18.04
Kernel: 4.18.5-041805-generic
Mesa version: 18.3.0-devel (padoka PPA)
Proton version: 3.7-4 Beta

Apologies if this isn't enough info, I'm not exactly an expert. Please let me know if there's any logs that might be of use or any other information I can post.

**Comment by kisak-valve** [comment]
Hello @Clifforus, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-417317841.

**Comment by FabianK-Dev** [comment]
I can reproduce the exact same issue.
Has it been solved so far?
