### ISSUE TITLE
Can't run Life is Strange: Before the Storm even after the PROTON_USE_WINED3D11=1 command

### ISSUE THREAD

**Issue by thermalthrottle** [ValveSoftware/Proton#989]
Hi guys, I'm having trouble with running Life is Strange: Before the Storm on Proton, even after using PROTON_USE_WINED3D11=1. Also I'm pretty new to Wine and Linux in general
The operating system I'm using is Linux Mint 19 "Tara". 
System specs:
i7-4510U 2GHz
8GB RAM
GT 840M 2GB
1TB Hitachi HDD
On Windows 7 Ultimate I'm able to run it on 1920x1080 Ultra(Hella High) with around 40fps without any issues.
The Proton version is 3.7-3 but it doesn't work with 3.7-4 either

Thanks in advance

Here's the log file:

Unity Player [version: Unity 5.5.3p1_b27954c0d351]

Life is Strange - Before the Storm.exe caused an Access Violation (0xc0000005)
  in module Life is Strange - Before the Storm.exe at 0033:407b50a3.

Error occurred at 2018-08-30_182244.
Z:\home\dimitar\.local\share\Steam\steamapps\common\Life is Strange - Before the Storm\Life is Strange - Before the Storm.exe, run by steamuser.
13% memory in use.
4096 MB physical memory [4096 MB free].
4096 MB paging file [-2048 MB free].
4096 MB user address space [4096 MB free].
Read from location 00000000 caused an access violation.

Context:
RDI:    0x00000000  RSI: 0x00000001  RAX:   0x887a0004
RBX:    0x0023f880  RCX: 0x00000000  RDX:   0x003500b0
RIP:    0x407b50a3  RBP: 0x0023f1d0  SegCs: 0x00000033
EFlags: 0x00010206  RSP: 0x0023f0d0  SegSs: 0x0000002b
R8:    0x003654e8  R9: 0x0000005a  R10:   0x00000000
R11:    0x0000009b  R12: 0x00000000  R13:   0x01b9c700
R14:    0x6f200000  R15: 0x0023f348

Bytes at CS:EIP:
48 8b 01 4c 8d 85 28 01 00 00 33 d2 44 8b e7 32 

Stack:
0x0023f0d0: 0065006c 00200073 00000000 00000001 l.e.s. .........
0x0023f0e0: 00000556 00000300 0000003c 00000075 V.......<...u...
0x0023f0f0: 003a0043 0077005c 00000000 00000000 C.:.\.w.........
0x0023f100: 6f200000 00000000 00000000 00000000 .. o............
0x0023f110: 70795400 64490065 69746e65 72656966 .Type.Identifier
0x0023f120: 00000000 00000000 00000000 00000000 ................
0x0023f130: 00202020 00000000 00000000 00000000    .............
0x0023f140: 00000000 00000000 00000000 00000000 ................
0x0023f150: 00000000 00000000 00000000 00000000 ................
0x0023f160: 00000000 00000000 00000000 00000000 ................
0x0023f170: 00000000 00000000 00000000 00000000 ................
0x0023f180: 00000000 00000000 00000000 00000000 ................
0x0023f190: ffffffd5 ffffffff 01b9c828 00000000 ........(.......
0x0023f1a0: 0023f1d0 00000000 dc003fd8 00007fd9 ..#......?......
0x0023f1b0: ffffffd5 ffffffff 01b9c828 00000000 ........(.......
0x0023f1c0: 000e8450 00000000 01b9c7b0 00000000 P...............
0x0023f1d0: 0023f320 00000000 dc0a9930 00007fd9  .#.....0.......
0x0023f1e0: 006c6290 00000000 000005ad 00000000 .bl.............
0x0023f1f0: 00000030 00000000 40010555 00000001 0.......U..@....
0x0023f200: 005c005c 005c002e 00490044 00500053 \.\...\.D.I.S.P.
0x0023f210: 0041004c 00310059 00000000 00000000 L.A.Y.1.........
0x0023f220: 00000000 00000000 00000000 00000000 ................
0x0023f230: 00000000 00000000 00000000 00000000 ................
0x0023f240: 00000000 00000000 00000556 00000300 ........V.......
0x0023f250: 00000001 00000001 00000001 00000000 ................
0x0023f260: 003a0043 0077005c 00000000 00000000 C.:.\.w.........
0x0023f270: 0065006c 00200073 00000000 00000000 l.e.s. .........
0x0023f280: 70795400 64490065 69746e65 72656966 .Type.Identifier
0x0023f290: 00000000 00000000 00000000 00000000 ................
0x0023f2a0: 00000000 00000000 00000000 00000000 ................
0x0023f2b0: 000e8450 00000000 01b9c7b0 00000000 P...............
0x0023f2c0: 01b9c828 00000000 ffffffd5 ffffffff (...............
0x0023f2d0: 0023f430 00000000 407b58ad 00000001 0.#......X{@....
0x0023f2e0: 0023f880 00000000 0023f340 00000000 ..#.....@.#.....
0x0023f2f0: 0023f300 00000000 00000000 00000000 ..#.............
0x0023f300: 00000000 00000000 ffffffd5 ffffffff ................
0x0023f310: 01b9c828 00000000 00000000 00000000 (...............
0x0023f320: 00000006 00000000 407ffe94 00000001 ...........@....
0x0023f330: 00000006 00000000 ffffffd5 ffffffff ................
0x0023f340: 00000000 00000000 00000000 00000000 ................
0x0023f350: 00000013 00000000 0000000f 00000000 ................
0x0023f360: 00001100 00000000 00000047 00000000 ........G.......
0x0023f370: 0023f4a0 00000000 dc0a9ed2 00007fd9 ..#.............
0x0023f380: 006af250 00000000 0000066f 00000000 P.j.....o.......
0x0023f390: 0000000c 00000000 4000fe1b 00000001 ...........@....
0x0023f3a0: 00000000 00000000 00000008 00000001 ................
0x0023f3b0: 00000000 00000000 0000000f 00000000 ................
0x0023f3c0: 0000000c 00000000 006c6200 00000000 .........bl.....
0x0023f3d0: 0000000c 00000000 00000000 00000000 ................
0x0023f3e0: 0000000f 00000000 00000000 00000000 ................
0x0023f3f0: 75646769 6d69646d 642e3233 00006c6c igdumdim32.dll..
0x0023f400: 00000000 00000000 00000000 00000000 ................
0x0023f410: 00000000 00000000 00000000 00000000 ................
0x0023f420: 00000000 00000000 00000000 00000000 ................
0x0023f430: 00000000 00000000 00000000 00000000 ................
0x0023f440: 00000000 00000000 00000000 00000000 ................
0x0023f450: 00000000 00000000 00000000 00000000 ................
0x0023f460: 00000000 00000000 00000000 00000000 ................
0x0023f470: 00000000 00000000 00000000 00000000 ................
0x0023f480: 00000000 00000000 00000000 00000000 ................
0x0023f490: 00000000 00000000 00000000 00000000 ................
0x0023f4a0: 00000000 00000000 00000000 00000000 ................
0x0023f4b0: 00000000 00000000 00000000 00000000 ................
0x0023f4c0: 00000000 00000000 00000000 00000000 ................
0x0023f4d0: 00000000 00000000 00000000 00000000 ................
0x0023f4e0: 00000000 00000000 00000000 00000000 ................
0x0023f4f0: 00000000 00000000 00000000 00000000 ................
0x0023f500: 00000000 00000000 00000000 00000000 ................
0x0023f510: 00000000 00000000 00000000 00000000 ................
0x0023f520: 00000000 00000000 00000000 00000000 ................
0x0023f530: 00000000 00000000 00000000 00000000 ................
0x0023f540: 00000000 00000000 00000000 00000000 ................
0x0023f550: 00000000 00000000 00000000 00000000 ................
0x0023f560: 00000000 00000000 00000000 00000000 ................
0x0023f570: 00000000 00000000 00000000 00000000 ................
0x0023f580: 00000000 00000000 00000000 00000000 ................
0x0023f590: 00000000 00000000 00000000 00000000 ................
0x0023f5a0: 00000000 00000000 00000000 00000000 ................
0x0023f5b0: 00000000 00000000 00000000 00000000 ................
0x0023f5c0: 00000000 00000000 00000000 00000000 ................
0x0023f5d0: 00000000 00000000 00000000 00000000 ................
0x0023f5e0: 00000000 00000000 00000000 00000000 ................
0x0023f5f0: 65746e49 2952286c 20444820 70617247 Intel(R) HD Grap
0x0023f600: 73636968 30363420 00000030 00000000 hics 4600.......
0x0023f610: 00000000 00000000 00000000 00000000 ................
0x0023f620: 00000000 00000000 00000000 00000000 ................
0x0023f630: 00000000 00000000 00000000 00000000 ................
0x0023f640: 00000000 00000000 00000000 00000000 ................
0x0023f650: 00000000 00000000 00000000 00000000 ................
0x0023f660: 00000000 00000000 00000000 00000000 ................
0x0023f670: 00000000 00000000 00000000 00000000 ................
0x0023f680: 00000000 00000000 00000000 00000000 ................
0x0023f690: 00000000 00000000 00000000 00000000 ................
0x0023f6a0: 00000000 00000000 00000000 00000000 ................
0x0023f6b0: 00000000 00000000 00000000 00000000 ................
0x0023f6c0: 00000000 00000000 00000000 00000000 ................
0x0023f6d0: 00000000 00000000 00000000 00000000 ................
0x0023f6e0: 00000000 00000000 00000000 00000000 ................
0x0023f6f0: 00000000 00000000 00000000 00000000 ................
0x0023f700: 00000000 00000000 00000000 00000000 ................
0x0023f710: 00000000 00000000 00000000 00000000 ................
0x0023f720: 00000000 00000000 00000000 00000000 ................
0x0023f730: 00000000 00000000 00000000 00000000 ................
0x0023f740: 00000000 00000000 00000000 00000000 ................
0x0023f750: 00000000 00000000 00000000 00000000 ................
0x0023f760: 00000000 00000000 00000000 00000000 ................
0x0023f770: 00000000 00000000 00000000 00000000 ................
0x0023f780: 00000000 00000000 00000000 00000000 ................
0x0023f790: 00000000 00000000 00000000 00000000 ................
0x0023f7a0: 00000000 00000000 00000000 00000000 ................
0x0023f7b0: 00000000 00000000 00000000 00000000 ................
0x0023f7c0: 00000000 00000000 00000000 00000000 ................
0x0023f7d0: 00000000 00000000 00000000 00000000 ................
0x0023f7e0: 00000000 00000000 00000000 00000000 ................
0x0023f7f0: 5c2e5c5c 50534944 3159414c 00000000 \\.\DISPLAY1....
0x0023f800: 00000001 00000000 00000001 00000000 ................
0x0023f810: 000f1100 00080013 00008086 00000416 ................
0x0023f820: 00000000 00000000 aeb2cdd4 43ea6e41 ............An.C
0x0023f830: 61831c94 810776cc 00000001 00000000 ...a.v..........
0x0023f840: 00000000 00000000 00000000 00000000 ................
0x0023f850: 00000001 00000000 00000001 00000000 ................
0x0023f860: 00000000 00000000 014b8b90 00000000 ..........K.....
0x0023f870: 00000001 00000000 407fdd3d 00000001 ........=..@....
0x0023f880: 41051420 00000001 00080013 000f1100  ..A............
0x0023f890: 000e8450 00000000 00000000 00000000 P...............
0x0023f8a0: 0000004e 00000001 000000c5 00000000 N...............
0x0023f8b0: 0069f290 00000000 40832071 00000001 ..i.....q .@....
0x0023f8c0: 0069f290 00000000 01d9bf30 00000000 ..i.....0.......
0x0023f8d0: 41051420 00000001 41051420 00000001  ..A.... ..A....
0x0023f8e0: 41051420 00000001 0000004e 00000000  ..A....N.......
0x0023f8f0: 00000001 00000000 40832a2e 00000001 .........*.@....
0x0023f900: 00000000 00000000 014b8b90 00000000 ..........K.....
0x0023f910: 00000001 00000000 00000000 00000000 ................
0x0023f920: 00000001 00000000 00000000 00000000 ................
0x0023f930: 00000000 00000000 40832243 00000001 ........C".@....
0x0023f940: 01d9a7e0 00000000 00000000 00000000 ................
0x0023f950: 00000001 00000000 0000001f 00000000 ................
0x0023f960: 00000064 00000000 00000000 00000000 d...............
0x0023f970: 00000000 00000000 00000000 00000000 ................
0x0023f980: 0023fa19 00000000 402d6109 00000001 ..#......a-@....
0x0023f990: 00000000 00000000 00000000 00000000 ................
0x0023f9a0: 00000001 00000000 00000000 00000000 ................
0x0023f9b0: 00000000 00000000 00000000 00000000 ................
0x0023f9c0: 00000000 00000000 00000000 00000000 ................
0x0023f9d0: 63726f66 66672d65 6f6a2d78 00007362 force-gfx-jobs..
0x0023f9e0: 0000000e 00000000 0000000f 00000000 ................
0x0023f9f0: 00000000 00000000 41072c98 00000001 .........,.A....
0x0023fa00: 0023fa88 00000000 407c7eb0 00000001 ..#......~|@....
0x0023fa10: 41072c98 00000001 401cfd97 00000001 .,.A.......@....
0x0023fa20: 413497c0 00000001 0023fa88 00000000 ..4A......#.....
0x0023fa30: 006cb670 00000000 00000021 00000000 p.l.....!.......
0x0023fa40: 00000000 00000000 401cfdda 00000001 ...........@....
0x0023fa50: 0000000a 00000000 40000000 00000001 ...........@....
0x0023fa60: 00000000 00000000 00571cb0 00000000 ..........W.....
0x0023fa70: 0023fb20 00000000 40212b8b 00000001  .#......+!@....
0x0023fa80: 41072c98 00000001 00000000 00000000 .,.A............
0x0023fa90: 00000000 00000000 006cb670 00000000 ........p.l.....
0x0023faa0: 0000000b 00000000 401f8aee 00000001 ...........@....
0x0023fab0: 00000027 00000000 0000001f 00000000 '...............
0x0023fac0: 65646900 646e6957 4000776f 00000001 .ideWindow.@....
0x0023fad0: 00000000 00000000 0000000f 00000000 ................
0x0023fae0: 00000000 00000000 40000000 00000001 ...........@....
0x0023faf0: 00010046 00000000 00000000 00000000 F...............
0x0023fb00: 00000000 00000000 0000000a 00000000 ................
0x0023fb10: 40000000 00000001 00000000 00000000 ...@............
0x0023fb20: 0023fc30 00000000 407c99ee 00000001 0.#.......|@....
0x0023fb30: 00000000 00000000 00571cb0 00000000 ..........W.....
0x0023fb40: 00000000 00000000 00000000 00000000 ................
0x0023fb50: 00462a00 00000000 00460000 00000000 .*F.......F.....
0x0023fb60: 0023fbe0 00000000 408c9e07 00000001 ..#........@....
0x0023fb70: 00000000 00000001 6f6e6f4d 6e6f6d2f ........Mono/mon
0x0023fb80: 6c642e6f 7265006c 0000000d 00000000 o.dll.er........
0x0023fb90: 0000000f 00000000 1c004121 01c0003f ........!A..?...
0x0023fba0: 0000003f 00000000 1c004122 01c0003f ?......."A..?...
0x0023fbb0: 0000003f 00000000 1c004143 01c0003f ?.......CA..?...
0x0023fbc0: 000001ff 00000000 00571cb0 00000000 ..........W.....
0x0023fbd0: 00000000 00000000 408c9e07 00000001 ...........@....
0x0023fbe0: 00000000 00000000 0000000f 00000000 ................
0x0023fbf0: 003a0043 0077005c 00571d20 00000000 C.:.\.w. .W.....
0x0023fc00: 0069f890 00000000 00780028 00360038 ..i.....(.x.8.6.
0x0023fc10: 0000007e 00000000 0000007f 00000000 ~...............
0x0023fc20: 0023ffd0 00000000 006a3a30 00000000 ..#.....0:j.....
0x0023fc30: 006a3a80 00000000 006a3a80 00000000 .:j......:j.....
0x0023fc40: 00000000 00000000 0149c820 00000000 ........ .I.....
0x0023fc50: 00000004 00000000 0000008d 00000000 ................
0x0023fc60: 0000008f 00000000 756e6547 49656e69 ........GenuineI
0x0023fc70: 0149cf50 00000000 00000000 00000000 P.I.............
0x0023fc80: 0000008c 00000000 0000008f 00000000 ................
0x0023fc90: 00000000 00000000 0149ce90 00000000 ..........I.....
0x0023fca0: 0023ffd0 00000000 00000087 00000000 ..#.............
0x0023fcb0: 0000008f 00000000 408ec9f0 00000001 ...........@....
0x0023fcc0: 00571cb0 00000000 00571cb0 00000000 ..W.......W.....
0x0023fcd0: 41050588 00100800 40e0b509 bfebfbff ...A.......@....
0x0023fce0: 4134ab00 00000001 00462cb0 00000000 ..4A.....,F.....
0x0023fcf0: 00460330 00000000 00000000 00000000 0.F.............
0x0023fd00: 00000000 00000000 00000000 00000000 ................
0x0023fd10: 0000000f 00000000 00000000 00000000 ................
0x0023fd20: 00000000 00000000 00000000 00000000 ................
0x0023fd30: 0023ffd0 00000000 408d0b50 00000001 ..#.....P..@....
0x0023fd40: 00000000 00000000 00000000 00000000 ................
0x0023fd50: 40000000 00000001 00000000 00000000 ...@............
0x0023fd60: 0023fdc8 00000000 00000000 00000000 ..#.............
0x0023fd70: 00000068 00000000 00000000 00000000 h...............
0x0023fd80: 00000000 00000000 00011fd0 00000000 ................
0x0023fd90: 00000000 00000000 00000000 00000000 ................
0x0023fda0: 00000000 00000000 00000000 00000000 ................
0x0023fdb0: 00000001 00000000 00000000 00000000 ................
0x0023fdc0: 00000004 00000000 00000008 00000000 ................
0x0023fdd0: 0000000c 00000000 00000000 00000000 ................
0x0023fde0: 0023fe40 00000000 7b4777ce 00000000 @.#......wG{....
0x0023fdf0: 00000000 00000000 00000000 00000000 ................
0x0023fe00: 00000000 00000000 00000000 00000000 ................
0x0023fe10: 00000000 00000000 00000000 00000000 ................
0x0023fe20: ffffffff ffffffff 7b4a0850 00000000 ........P.J{....
0x0023fe30: 7b44af50 00000000 00000000 00000000 P.D{............
0x0023fe40: 00000000 00000000 65c3813a f5674ea3 ........:..e.Ng.
0x0023fe50: 00000000 00000000 00000000 00000000 ................
0x0023fe60: 00000000 00000000 00000000 00000000 ................
0x0023fe70: 6183813a f5674ea3 74a5813a f567b86a :..a.Ng.:..tj.g.
0x0023fe80: 00000000 00000000 00000000 00000000 ................
0x0023fe90: 00000000 00000000 00000000 00000000 ................
0x0023fea0: 00000000 00000000 00000000 00000000 ................
0x0023feb0: 00000000 00000000 00000000 00000000 ................
0x0023fec0: 00000000 00000000 00000000 00000000 ................
0x0023fed0: 00000000 00000000 00000000 00000000 ................
0x0023fee0: 00000000 00000000 00000000 00000000 ................
0x0023fef0: 00000000 00000000 00000000 00000000 ................
0x0023ff00: 00000000 00000000 00000000 00000000 ................
0x0023ff10: 00000000 00000000 00000000 00000000 ................
0x0023ff20: 003a0043 0077005c 006e0069 006f0064 C.:.\.w.i.n.d.o.
0x0023ff30: 0065006c 00200073 00780028 00360038 l.e.s. .(.x.8.6.
0x0023ff40: 70795400 64490065 69746e65 72656966 .Type.Identifier
0x0023ff50: 00000000 00000000 00000000 00000000 ................
0x0023ff60: 00202020 00000000 00000000 00000000    .............
0x0023ff70: 00000000 00000000 00000000 00000000 ................
0x0023ff80: 00000000 00000000 00000000 00000000 ................
0x0023ff90: 00000000 00000000 00000000 00000000 ................
0x0023ffa0: 00000000 00000000 00000000 00000000 ................
0x0023ffb0: 00000000 00000000 00000000 00000000 ................
0x0023ffc0: 00000000 00000000 00000000 00000000 ................
0x0023ffd0: 00000000 00000000 00000000 00000000 ................
0x0023ffe0: 4163d310 00000001 ffeaf000 00007fff ..cA............
0x0023fff0: 00000000 00000000 00000000 00000000 ................

Module 1
C:\windows\system32\openvr_api_dxvk.dll
Image Base: 0x80000000  Image Size: 0x00097000
File Size:  600864      File Time:  2018-08-30_182234
Version:
   Company:    Valve
   Product:    OpenVR
   FileDesc:   OpenVR Loader DLL
   FileVer:    1.0.10.0
   ProdVer:    1.0.10.0

Module 2
C:\windows\system32\d3d11.dll
Image Base: 0x6a340000  Image Size: 0x001f6000
File Size:  2017792     File Time:  2018-08-24_215406
Version:
   Company:    
   Product:    
   FileDesc:   
   FileVer:    0.0.0.0
   ProdVer:    0.0.0.0

Module 3
C:\windows\system32\dxgi.dll
Image Base: 0x6f200000  Image Size: 0x0018c000
File Size:  1577472     File Time:  2018-08-24_215406
Version:
   Company:    
   Product:    
   FileDesc:   
   FileVer:    0.0.0.0
   ProdVer:    0.0.0.0

Module 4
C:\windows\system32\opengl32.dll
Image Base: 0x7a850000  Image Size: 0x001b4000
File Size:  2400        File Time:  2018-08-30_173812
Version:
   Company:    Microsoft Corporation
   Product:    Wine
   FileDesc:   Wine OpenGL Client
   FileVer:    5.1.2600.2082
   ProdVer:    5.1.2600.2082

Module 5
C:\windows\system32\KERNEL32.dll
Image Base: 0x7b420000  Image Size: 0x003f1000
File Size:  1716524     File Time:  2018-08-30_173808
Version:
   Company:    Microsoft Corporation
   Product:    Wine
   FileDesc:   Wine kernel DLL
   FileVer:    5.1.2600.2180
   ProdVer:    5.1.2600.2180

Module 6
C:\windows\system32\ntdll.dll
Image Base: 0x7bc20000  Image Size: 0x00112000
File Size:  2476        File Time:  2018-08-30_173810
Version:
   Company:    Microsoft Corporation
   Product:    Wine
   FileDesc:   Wine ntdll
   FileVer:    6.1.7601.24059
   ProdVer:    6.1.7601.24059

== [end of error.log] ==

**Comment by kisak-valve** [comment]
Hello @batgo6o, we'll be using one issue report per unofficially supported game title, and you've already posted on #75. Closing in favor of #75.

**Comment by thermalthrottle** [comment]
What I am trying to say is that no one mentions about this issue
